Read&Watch: django.contrib.auth.forms.BaseUserCreationForm Class Reference
django.contrib.auth.forms.BaseUserCreationForm Class Reference
Classes
class Meta
Public Member Functions
__init__ (self, *args, **kwargs)
clean (self)
save (self, commit=True)
Public Member Functions inherited from django.contrib.auth.forms.SetPasswordMixin
validate_passwords (self, password1_field_name="password1", password2_field_name="password2")
validate_password_for_user (self, user, password_field_name="password2")
set_password_and_save (self, user, password_field_name="password1", commit=True)
Public Member Functions inherited from django.forms.models.BaseModelForm
__init__ (self, data=None, files=None, auto_id="id_%s", prefix=None, initial=None, error_class=ErrorList, label_suffix=None, empty_permitted=False, instance=None, use_required_attribute=None, renderer=None)
validate_unique (self)
Public Member Functions inherited from django.forms.forms.BaseForm
__init__ (self, data=None, files=None, auto_id="id_%s", prefix=None, initial=None, error_class=ErrorList, label_suffix=None, empty_permitted=False, field_order=None, use_required_attribute=None, renderer=None)
order_fields (self, field_order)
__repr__ (self)
__iter__ (self)
__getitem__ (self, name)
errors (self)
is_valid (self)
add_prefix (self, field_name)
add_initial_prefix (self, field_name)
template_name (self)
get_context (self)
non_field_errors (self)
add_error (self, field, error)
has_error (self, field, code=None)
full_clean (self)
has_changed (self)
changed_data (self)
media (self)
is_multipart (self)
hidden_fields (self)
visible_fields (self)
get_initial_for_field (self, field, field_name)
Public Member Functions inherited from django.forms.utils.RenderableFormMixin
as_p (self)
as_table (self)
as_ul (self)
as_div (self)
Public Member Functions inherited from django.forms.utils.RenderableMixin
render (self, template_name=None, context=None, renderer=None)
Public Member Functions inherited from django.db.models.utils.AltersData
__init_subclass__ (cls, **kwargs)
Public Member Functions inherited from django.forms.models.ModelFormMetaclass
__new__ (mcs, name, bases, attrs)
Public Member Functions inherited from django.forms.forms.DeclarativeFieldsMetaclass
__new__ (mcs, name, bases, attrs)
Public Member Functions inherited from django.forms.widgets.MediaDefiningClass
__new__ (mcs, name, bases, attrs)
Static Public Attributes
password1
password2
Static Public Attributes inherited from django.contrib.auth.forms.SetPasswordMixin
dict error_messages
Static Public Attributes inherited from django.forms.models.BaseModelForm
alters_data
Static Public Attributes inherited from django.forms.forms.BaseForm
default_renderer = None
field_order = None
prefix = None
bool use_required_attribute = True
str template_name_label = "django/forms/label.html"
Protected Member Functions
_post_clean (self)
Protected Member Functions inherited from django.forms.models.BaseModelForm
_get_validation_exclusions (self)
_update_errors (self, errors)
_save_m2m (self)
Protected Member Functions inherited from django.forms.forms.BaseForm
_bound_items (self)
_widget_data_value (self, widget, html_name)
_clean_fields (self)
_clean_form (self)
Additional Inherited Members
Static Public Member Functions inherited from django.contrib.auth.forms.SetPasswordMixin
create_password_fields (label1=_("Password"), label2=_("Password confirmation"))
Public Attributes inherited from django.contrib.auth.forms.SetPasswordMixin
errors
Public Attributes inherited from django.forms.models.BaseModelForm
instance = opts.model()
save_m2m = self._save_m2m
Public Attributes inherited from django.forms.forms.BaseForm
# Stop further processing. is_bound = data is not None or files is not None
data = MultiValueDict() if data is None else data
files = MultiValueDict() if files is None else files
auto_id = auto_id
initial = initial or {}
error_class = error_class
label_suffix = label_suffix if label_suffix is not None else _(":")
empty_permitted = empty_permitted
fields = copy.deepcopy(self.base_fields)
renderer = renderer
errors
dict cleaned_data = self.error_class(renderer=self.renderer)
changed_data
Public Attributes inherited from django.forms.utils.RenderableFormMixin
template_name_p
template_name_table
template_name_ul
template_name_div
Protected Attributes inherited from django.forms.models.BaseModelForm
bool _validate_unique = False
Protected Attributes inherited from django.forms.forms.BaseForm
_errors = None
dict _bound_fields_cache = {}
Detailed Description
A form that creates a user, with no privileges, from the given username and
password.
This is the documented base class for customizing the user creation form.
It should be kept mostly unchanged to ensure consistency and compatibility.
Definition at line 221 of file forms.py.
Constructor & Destructor Documentation
__init__()
django.contrib.auth.forms.BaseUserCreationForm.__init__ (self, * args, ** kwargs)
Definition at line 237 of file forms.py.
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self._meta.model.USERNAME_FIELD in self.fields:
            self.fields[self._meta.model.USERNAME_FIELD].widget.attrs[
                "autofocus"
            ] = True
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Function Documentation
_post_clean()
django.contrib.auth.forms.BaseUserCreationForm._post_clean (self) protected
An internal hook for performing additional cleaning after form cleaning
is complete. Used for model validation in model forms.
Reimplemented from django.forms.models.BaseModelForm.
Definition at line 248 of file forms.py.
    def _post_clean(self):
        super()._post_clean()
        # Validate the password after self.instance is updated with form data
        # by super().
        self.validate_password_for_user(self.instance)
References _post_clean().
Referenced by _post_clean(), and django.forms.forms.BaseForm.full_clean().
clean()
django.contrib.auth.forms.BaseUserCreationForm.clean (self)
Hook for doing any extra form-wide cleaning after Field.clean() has been
called on every field. Any ValidationError raised by this method will
not be associated with a particular field; it will have a special-case
association with the field named '__all__'.
Reimplemented from django.forms.models.BaseModelForm.
Definition at line 244 of file forms.py.
    def clean(self):
        self.validate_passwords()
        return super().clean()
References clean(), and django.contrib.auth.forms.SetPasswordMixin.validate_passwords().
Referenced by django.core.validators.BaseValidator.__call__(), django.core.validators.StepValueValidator.__call__(), django.forms.fields.Field._clean_bound_field(), django.forms.fields.FileField._clean_bound_field(), django.forms.forms.BaseForm._clean_form(), clean(), django.db.models.base.Model.full_clean(), and movie.models.Movie.save().
save()
django.contrib.auth.forms.BaseUserCreationForm.save (self, commit = True)
Save this form's self.instance object if commit=True. Otherwise, add
a save_m2m() method to the form which can be called after the instance
is saved manually at a later time. Return the model instance.
Reimplemented from django.forms.models.BaseModelForm.
Reimplemented in users.forms.RegisterForm.
Definition at line 254 of file forms.py.
    def save(self, commit=True):
        user = super().save(commit=False)
        user = self.set_password_and_save(user, commit=commit)
        if commit and hasattr(self, "save_m2m"):
            self.save_m2m()
        return user
References save(), django.forms.models.BaseModelForm.save_m2m, and django.contrib.auth.forms.SetPasswordMixin.set_password_and_save().
Referenced by PIL.Image.Image._dump(), PIL.Image.Image._repr_image(), save(), django.core.serializers.base.DeserializedObject.save_deferred_fields(), and pylint.pyreverse.writer.DiagramWriter.write().
Member Data Documentation
password1
django.contrib.auth.forms.BaseUserCreationForm.password1 static
Definition at line 230 of file forms.py.
password2
django.contrib.auth.forms.BaseUserCreationForm.password2 static
Definition at line 230 of file forms.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/auth/forms.py