Read&Watch: pylint.checkers.base.basic_checker.BasicChecker Class Reference
pylint.checkers.base.basic_checker.BasicChecker Class Reference
Public Member Functions
None __init__ (self, PyLinter linter)
None open (self)
None visit_if (self, nodes.If node)
None visit_ifexp (self, nodes.IfExp node)
None visit_comprehension (self, nodes.Comprehension node)
None visit_module (self, nodes.Module _)
None visit_classdef (self, nodes.ClassDef _)
None visit_expr (self, nodes.Expr node)
None visit_lambda (self, nodes.Lambda node)
None visit_functiondef (self, nodes.FunctionDef node)
None visit_return (self, nodes.Return node)
None visit_continue (self, nodes.Continue node)
None visit_break (self, nodes.Break node)
None visit_raise (self, nodes.Raise node)
None visit_call (self, nodes.Call node)
None visit_assert (self, nodes.Assert node)
None visit_dict (self, nodes.Dict node)
None visit_set (self, nodes.Set node)
None visit_try (self, nodes.Try node)
None leave_try (self, nodes.Try _)
None visit_with (self, nodes.With node)
None visit_assign (self, nodes.Assign node)
None visit_for (self, nodes.For node)
Public Member Functions inherited from pylint.checkers.base_checker.BaseChecker
None __init__ (self, PyLinter linter)
bool __gt__ (self, Any other)
bool __eq__ (self, object other)
int __hash__ (self)
str __repr__ (self)
str __str__ (self)
str get_full_documentation (self, dict[str, MessageDefinitionTuple] msgs, Iterable[tuple[str, OptionDict, Any]] options, Sequence[tuple[str, str, ReportsCallable]] reports, str|None doc=None, str|None module=None, bool show_options=True)
None add_message (self, str msgid, int|None line=None, nodes.NodeNG|None node=None, Any args=None, Confidence|None confidence=None, int|None col_offset=None, int|None end_lineno=None, int|None end_col_offset=None)
None check_consistency (self)
MessageDefinition create_message_definition_from_tuple (self, str msgid, MessageDefinitionTuple msg_tuple)
list[MessageDefinition] messages (self)
None close (self)
Any get_map_data (self)
None reduce_map_data (self, PyLinter linter, list[Any] data)
Public Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
None __init__ (self, _ArgumentsManager arguments_manager)
Static Public Attributes
None visit_asyncfunctiondef = visit_functiondef
Static Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
str name = ""
dict msgs = {}
tuple reports = ()
bool enabled = True
Static Public Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
tuple options = ()
dict option_groups_descs = {}
Protected Member Functions
None _check_using_constant_test (self, nodes.If|nodes.IfExp|nodes.Comprehension node, nodes.NodeNG|None test)
None _check_dangerous_default (self, nodes.FunctionDef node)
None _check_misplaced_format_function (self, nodes.Call call_node)
None _check_unreachable (self, nodes.Return|nodes.Continue|nodes.Break|nodes.Raise|nodes.Call node, Confidence confidence=HIGH)
None _check_not_in_finally (self, nodes.Break|nodes.Return node, str node_name, tuple[nodes.NodeNG,...] breaker_classes=())
None _check_reversed (self, nodes.Call node)
None _check_self_assigning_variable (self, nodes.Assign node)
None _check_redeclared_assign_name (self, list[nodes.NodeNG|None] targets)
Protected Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
Any _option_value (self, str opt)
Iterator[ tuple[str, list[tuple[str, OptionDict, Any]]]|tuple[None, dict[str, list[tuple[str, OptionDict, Any]]]]] _options_by_section (self)
Iterator[tuple[str, OptionDict, Any]] _options_and_values (self, Options|None options=None)
Static Protected Member Functions
tuple[bool, nodes.Call|None] _name_holds_generator (nodes.Name test)
Iterator[nodes.NodeNG] _filter_vararg (nodes.Lambda node, list[nodes.NodeNG] call_args)
bool _has_variadic_argument (list[nodes.Starred|nodes.Keyword] args, str variadic_name)
Protected Attributes
list[nodes.Try] _trys
tuple _py38_plus = (3, 8)
Protected Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
_arguments_manager = arguments_manager
Additional Inherited Members
Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
linter = linter
messages
Detailed Description
Basic checker.
Checks for :
* doc strings
* number of arguments, local variables, branches, returns and statements in
functions, methods
* required module attributes
* dangerous default values as arguments
* redefinition of function / method / class
* uses of the global statement
Definition at line 102 of file basic_checker.py.
Constructor & Destructor Documentation
__init__()
None pylint.checkers.base.basic_checker.BasicChecker.__init__ (self, PyLinter linter)
Definition at line 273 of file basic_checker.py.
    def __init__(self, linter: PyLinter) -> None:
        super().__init__(linter)
        self._trys: list[nodes.Try]
References __init__().
Referenced by __init__().
Member Function Documentation
_check_dangerous_default()
None pylint.checkers.base.basic_checker.BasicChecker._check_dangerous_default (self, nodes.FunctionDef node) protected
Check for dangerous default values as arguments.
Definition at line 597 of file basic_checker.py.
    def _check_dangerous_default(self, node: nodes.FunctionDef) -> None:
        """Check for dangerous default values as arguments."""
        def is_iterable(internal_node: nodes.NodeNG) -> bool:
            return isinstance(internal_node, (nodes.List, nodes.Set, nodes.Dict))
        defaults = (node.args.defaults or []) + (node.args.kw_defaults or [])
        for default in defaults:
            if not default:
                continue
            try:
                value = next(default.infer())
            except astroid.InferenceError:
                continue
            if (
                isinstance(value, astroid.Instance)
                and value.qname() in DEFAULT_ARGUMENT_SYMBOLS
            ):
                if value is default:
                    msg = DEFAULT_ARGUMENT_SYMBOLS[value.qname()]
                elif isinstance(value, astroid.Instance) or is_iterable(value):
                    # We are here in the following situation(s):
                    #   * a dict/set/list/tuple call which wasn't inferred
                    #     to a syntax node ({}, () etc.). This can happen
                    #     when the arguments are invalid or unknown to
                    #     the inference.
                    #   * a variable from somewhere else, which turns out to be a list
                    #     or a dict.
                    if is_iterable(default):
                        msg = value.pytype()
                    elif isinstance(default, nodes.Call):
                        msg = f"{value.name}() ({value.qname()})"
                    else:
                        msg = f"{default.as_string()} ({value.qname()})"
                else:
                    # this argument is a name
                    msg = f"{default.as_string()} ({DEFAULT_ARGUMENT_SYMBOLS[value.qname()]})"
                self.add_message("dangerous-default-value", node=node, args=(msg,))
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_functiondef().
_check_misplaced_format_function()
None pylint.checkers.base.basic_checker.BasicChecker._check_misplaced_format_function (self, nodes.Call call_node) protected
Definition at line 678 of file basic_checker.py.
    def _check_misplaced_format_function(self, call_node: nodes.Call) -> None:
        if not isinstance(call_node.func, nodes.Attribute):
            return
        if call_node.func.attrname != "format":
            return
        expr = utils.safe_infer(call_node.func.expr)
        if isinstance(expr, util.UninferableBase):
            return
        if not expr:
            # we are doubtful on inferred type of node, so here just check if format
            # was called on print()
            call_expr = call_node.func.expr
            if not isinstance(call_expr, nodes.Call):
                return
            if (
                isinstance(call_expr.func, nodes.Name)
                and call_expr.func.name == "print"
            ):
                self.add_message("misplaced-format-function", node=call_node)
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_call().
_check_not_in_finally()
None pylint.checkers.base.basic_checker.BasicChecker._check_not_in_finally (self, nodes.Break | nodes.Return node, str node_name, tuple[nodes.NodeNG, ...] breaker_classes = ()) protected
Check that a node is not inside a 'finally' clause of a
'try...finally' statement.
If we find a parent which type is in breaker_classes before
a 'try...finally' block we skip the whole check.
Definition at line 800 of file basic_checker.py.
    ) -> None:
        """Check that a node is not inside a 'finally' clause of a
        'try...finally' statement.
        If we find a parent which type is in breaker_classes before
        a 'try...finally' block we skip the whole check.
        """
        # if self._trys is empty, we're not an in try block
        if not self._trys:
            return
        # the node could be a grand-grand...-child of the 'try...finally'
        _parent = node.parent
        _node = node
        while _parent and not isinstance(_parent, breaker_classes):
            if hasattr(_parent, "finalbody") and _node in _parent.finalbody:
                self.add_message("lost-exception", node=node, args=node_name)
                return
            _node = _parent
            _parent = _node.parent
References _trys, and pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_break(), and visit_return().
_check_redeclared_assign_name()
None pylint.checkers.base.basic_checker.BasicChecker._check_redeclared_assign_name (self, list[nodes.NodeNG | None] targets) protected
Definition at line 939 of file basic_checker.py.
    def _check_redeclared_assign_name(self, targets: list[nodes.NodeNG | None]) -> None:
        dummy_variables_rgx = self.linter.config.dummy_variables_rgx
        for target in targets:
            if not isinstance(target, nodes.Tuple):
                continue
            found_names = []
            for element in target.elts:
                if isinstance(element, nodes.Tuple):
                    self._check_redeclared_assign_name([element])
                elif isinstance(element, nodes.AssignName) and element.name != "_":
                    if dummy_variables_rgx and dummy_variables_rgx.match(element.name):
                        return
                    found_names.append(element.name)
            names = collections.Counter(found_names)
            for name, count in names.most_common():
                if count > 1:
                    self.add_message(
                        "redeclared-assigned-name", args=(name,), node=target
                    )
References _check_redeclared_assign_name(), pylint.checkers.base_checker.BaseChecker.add_message(), and pylint.checkers.base_checker.BaseChecker.linter.
Referenced by _check_redeclared_assign_name(), visit_assign(), and visit_for().
_check_reversed()
None pylint.checkers.base.basic_checker.BasicChecker._check_reversed (self, nodes.Call node) protected
Check that the argument to `reversed` is a sequence.
Definition at line 825 of file basic_checker.py.
    def _check_reversed(self, node: nodes.Call) -> None:
        """Check that the argument to `reversed` is a sequence."""
        try:
            argument = utils.safe_infer(utils.get_argument_from_call(node, position=0))
        except utils.NoSuchArgumentError:
            pass
        else:
            if isinstance(argument, util.UninferableBase):
                return
            if argument is None:
                # Nothing was inferred.
                # Try to see if we have iter().
                if isinstance(node.args[0], nodes.Call):
                    try:
                        func = next(node.args[0].func.infer())
                    except astroid.InferenceError:
                        return
                    if getattr(
                        func, "name", None
                    ) == "iter" and utils.is_builtin_object(func):
                        self.add_message("bad-reversed-sequence", node=node)
                return
            if isinstance(argument, (nodes.List, nodes.Tuple)):
                return
            # dicts are reversible, but only from Python 3.8 onward. Prior to
            # that, any class based on dict must explicitly provide a
            # __reversed__ method
            if not self._py38_plus and isinstance(argument, astroid.Instance):
                if any(
                    ancestor.name == "dict" and utils.is_builtin_object(ancestor)
                    for ancestor in itertools.chain(
                        (argument._proxied,), argument._proxied.ancestors()
                    )
                ):
                    try:
                        argument.locals[REVERSED_PROTOCOL_METHOD]
                    except KeyError:
                        self.add_message("bad-reversed-sequence", node=node)
                    return
            if hasattr(argument, "getattr"):
                # everything else is not a proper sequence for reversed()
                for methods in REVERSED_METHODS:
                    for meth in methods:
                        try:
                            argument.getattr(meth)
                        except astroid.NotFoundError:
                            break
                    else:
                        break
                else:
                    self.add_message("bad-reversed-sequence", node=node)
            else:
                self.add_message("bad-reversed-sequence", node=node)
References _py38_plus, and pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_call().
_check_self_assigning_variable()
None pylint.checkers.base.basic_checker.BasicChecker._check_self_assigning_variable (self, nodes.Assign node) protected
Definition at line 898 of file basic_checker.py.
    def _check_self_assigning_variable(self, node: nodes.Assign) -> None:
        # Detect assigning to the same variable.
        scope = node.scope()
        scope_locals = scope.locals
        rhs_names = []
        targets = node.targets
        if isinstance(targets[0], nodes.Tuple):
            if len(targets) != 1:
                # A complex assignment, so bail out early.
                return
            targets = targets[0].elts
            if len(targets) == 1:
                # Unpacking a variable into the same name.
                return
        if isinstance(node.value, nodes.Name):
            if len(targets) != 1:
                return
            rhs_names = [node.value]
        elif isinstance(node.value, nodes.Tuple):
            rhs_count = len(node.value.elts)
            if len(targets) != rhs_count or rhs_count == 1:
                return
            rhs_names = node.value.elts
        for target, lhs_name in zip(targets, rhs_names):
            if not isinstance(lhs_name, nodes.Name):
                continue
            if not isinstance(target, nodes.AssignName):
                continue
            # Check that the scope is different from a class level, which is usually
            # a pattern to expose module level attributes as class level ones.
            if isinstance(scope, nodes.ClassDef) and target.name in scope_locals:
                continue
            if target.name == lhs_name.name:
                self.add_message(
                    "self-assigning-variable", args=(target.name,), node=target
                )
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_assign().
_check_unreachable()
None pylint.checkers.base.basic_checker.BasicChecker._check_unreachable (self, nodes.Return | nodes.Continue | nodes.Break | nodes.Raise | nodes.Call node, Confidence confidence = HIGH) protected
Check unreachable code.
Definition at line 778 of file basic_checker.py.
    ) -> None:
        """Check unreachable code."""
        unreachable_statement = node.next_sibling()
        if unreachable_statement is not None:
            if (
                isinstance(node, nodes.Return)
                and isinstance(unreachable_statement, nodes.Expr)
                and isinstance(unreachable_statement.value, nodes.Yield)
            ):
                # Don't add 'unreachable' for empty generators.
                # Only add warning if 'yield' is followed by another node.
                unreachable_statement = unreachable_statement.next_sibling()
                if unreachable_statement is None:
                    return
            self.add_message(
                "unreachable", node=unreachable_statement, confidence=confidence
            )
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_break(), visit_call(), visit_continue(), visit_raise(), and visit_return().
_check_using_constant_test()
None pylint.checkers.base.basic_checker.BasicChecker._check_using_constant_test (self, nodes.If | nodes.IfExp | nodes.Comprehension node, nodes.NodeNG | None test) protected
Definition at line 304 of file basic_checker.py.
    ) -> None:
        const_nodes = (
            nodes.Module,
            nodes.GeneratorExp,
            nodes.Lambda,
            nodes.FunctionDef,
            nodes.ClassDef,
            astroid.bases.Generator,
            astroid.UnboundMethod,
            astroid.BoundMethod,
            nodes.Module,
        )
        structs = (nodes.Dict, nodes.Tuple, nodes.Set, nodes.List)
        # These nodes are excepted, since they are not constant
        # values, requiring a computation to happen.
        except_nodes = (
            nodes.Call,
            nodes.BinOp,
            nodes.BoolOp,
            nodes.UnaryOp,
            nodes.Subscript,
        )
        inferred = None
        emit = isinstance(test, (nodes.Const, *structs, *const_nodes))
        maybe_generator_call = None
        if not isinstance(test, except_nodes):
            inferred = utils.safe_infer(test)
            if isinstance(inferred, util.UninferableBase) and isinstance(
                test, nodes.Name
            ):
                emit, maybe_generator_call = BasicChecker._name_holds_generator(test)
        # Emit if calling a function that only returns GeneratorExp (always tests True)
        elif isinstance(test, nodes.Call):
            maybe_generator_call = test
        if maybe_generator_call:
            inferred_call = utils.safe_infer(maybe_generator_call.func)
            if isinstance(inferred_call, nodes.FunctionDef):
                # Can't use all(x) or not any(not x) for this condition, because it
                # will return True for empty generators, which is not what we want.
                all_returns_were_generator = None
                for return_node in inferred_call._get_return_nodes_skip_functions():
                    if not isinstance(return_node.value, nodes.GeneratorExp):
                        all_returns_were_generator = False
                        break
                    all_returns_were_generator = True
                if all_returns_were_generator:
                    self.add_message(
                        "using-constant-test", node=node, confidence=INFERENCE
                    )
                    return
        if emit:
            self.add_message("using-constant-test", node=test, confidence=INFERENCE)
        elif isinstance(inferred, const_nodes):
            # If the constant node is a FunctionDef or Lambda then
            # it may be an illicit function call due to missing parentheses
            call_inferred = None
            try:
                # Just forcing the generator to infer all elements.
                # astroid.exceptions.InferenceError are false positives
                # see https://github.com/pylint-dev/pylint/pull/8185
                if isinstance(inferred, nodes.FunctionDef):
                    call_inferred = list(inferred.infer_call_result(node))
                elif isinstance(inferred, nodes.Lambda):
                    call_inferred = list(inferred.infer_call_result(node))
            except astroid.InferenceError:
                call_inferred = None
            if call_inferred:
                self.add_message(
                    "missing-parentheses-for-call-in-test",
                    node=test,
                    confidence=INFERENCE,
                )
            self.add_message("using-constant-test", node=test, confidence=INFERENCE)
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_comprehension(), visit_if(), and visit_ifexp().
_filter_vararg()
Iterator[nodes.NodeNG] pylint.checkers.base.basic_checker.BasicChecker._filter_vararg (nodes.Lambda node, list[nodes.NodeNG] call_args) static protected
Definition at line 500 of file basic_checker.py.
    ) -> Iterator[nodes.NodeNG]:
        # Return the arguments for the given call which are
        # not passed as vararg.
        for arg in call_args:
            if isinstance(arg, nodes.Starred):
                if (
                    isinstance(arg.value, nodes.Name)
                    and arg.value.name != node.args.vararg
                ):
                    yield arg
            else:
                yield arg
Referenced by visit_lambda().
_has_variadic_argument()
bool pylint.checkers.base.basic_checker.BasicChecker._has_variadic_argument (list[nodes.Starred | nodes.Keyword] args, str variadic_name) static protected
Definition at line 516 of file basic_checker.py.
    ) -> bool:
        return not args or any(
            isinstance(a.value, nodes.Name)
            and a.value.name != variadic_name
            or not isinstance(a.value, nodes.Name)
            for a in args
        )
Referenced by visit_lambda().
_name_holds_generator()
tuple[bool, nodes.Call | None] pylint.checkers.base.basic_checker.BasicChecker._name_holds_generator (nodes.Name test) static protected
Return whether `test` tests a name certain to hold a generator, or optionally
a call that should be then tested to see if *it* returns only generators.
Definition at line 386 of file basic_checker.py.
    def _name_holds_generator(test: nodes.Name) -> tuple[bool, nodes.Call | None]:
        """Return whether `test` tests a name certain to hold a generator, or optionally
        a call that should be then tested to see if *it* returns only generators.
        """
        assert isinstance(test, nodes.Name)
        emit = False
        maybe_generator_call = None
        lookup_result = test.frame().lookup(test.name)
        if not lookup_result:
            return emit, maybe_generator_call
        maybe_generator_assigned = (
            isinstance(assign_name.parent.value, nodes.GeneratorExp)
            for assign_name in lookup_result[1]
            if isinstance(assign_name.parent, nodes.Assign)
        )
        first_item = next(maybe_generator_assigned, None)
        if first_item is not None:
            # Emit if this variable is certain to hold a generator
            if all(itertools.chain((first_item,), maybe_generator_assigned)):
                emit = True
            # If this variable holds the result of a call, save it for next test
            elif (
                len(lookup_result[1]) == 1
                and isinstance(lookup_result[1][0].parent, nodes.Assign)
                and isinstance(lookup_result[1][0].parent.value, nodes.Call)
            ):
                maybe_generator_call = lookup_result[1][0].parent.value
        return emit, maybe_generator_call
leave_try()
None pylint.checkers.base.basic_checker.BasicChecker.leave_try (self, nodes.Try _)
Update try block flag.
Definition at line 774 of file basic_checker.py.
    def leave_try(self, _: nodes.Try) -> None:
        """Update try block flag."""
        self._trys.pop()
References _trys.
open()
None pylint.checkers.base.basic_checker.BasicChecker.open (self)
Initialize visit variables and statistics.
Reimplemented from pylint.checkers.base_checker.BaseChecker.
Definition at line 277 of file basic_checker.py.
    def open(self) -> None:
        """Initialize visit variables and statistics."""
        py_version = self.linter.config.py_version
        self._py38_plus = py_version >= (3, 8)
        self._trys = []
        self.linter.stats.reset_node_count()
References pylint.checkers.base_checker.BaseChecker.linter.
Referenced by django.contrib.staticfiles.storage.HashedFilesMixin.hashed_name().
visit_assert()
None pylint.checkers.base.basic_checker.BasicChecker.visit_assert (self, nodes.Assert node)
Check whether assert is used on a tuple or string literal.
Definition at line 724 of file basic_checker.py.
    def visit_assert(self, node: nodes.Assert) -> None:
        """Check whether assert is used on a tuple or string literal."""
        if isinstance(node.test, nodes.Tuple) and len(node.test.elts) > 0:
            self.add_message("assert-on-tuple", node=node, confidence=HIGH)
        if isinstance(node.test, nodes.Const) and isinstance(node.test.value, str):
            if node.test.value:
                when = "never"
            else:
                when = "always"
            self.add_message("assert-on-string-literal", node=node, args=(when,))
References pylint.checkers.base_checker.BaseChecker.add_message().
visit_assign()
None pylint.checkers.base.basic_checker.BasicChecker.visit_assign (self, nodes.Assign node)
Definition at line 965 of file basic_checker.py.
    def visit_assign(self, node: nodes.Assign) -> None:
        self._check_self_assigning_variable(node)
        self._check_redeclared_assign_name(node.targets)
References _check_redeclared_assign_name(), and _check_self_assigning_variable().
visit_break()
None pylint.checkers.base.basic_checker.BasicChecker.visit_break (self, nodes.Break node)
Break node visitor.
1 - check if the node has a right sibling (if so, that's some
unreachable code)
2 - check if the node is inside the 'finally' clause of a 'try...finally'
block
Definition at line 658 of file basic_checker.py.
    def visit_break(self, node: nodes.Break) -> None:
        """Break node visitor.
        1 - check if the node has a right sibling (if so, that's some
        unreachable code)
        2 - check if the node is inside the 'finally' clause of a 'try...finally'
        block
        """
        # 1 - Is it right sibling ?
        self._check_unreachable(node)
        # 2 - Is it inside final body of a try...finally block ?
        self._check_not_in_finally(node, "break", (nodes.For, nodes.While))
References _check_not_in_finally(), and _check_unreachable().
visit_call()
None pylint.checkers.base.basic_checker.BasicChecker.visit_call (self, nodes.Call node)
Visit a Call node.
Definition at line 706 of file basic_checker.py.
    def visit_call(self, node: nodes.Call) -> None:
        """Visit a Call node."""
        if utils.is_terminating_func(node):
            self._check_unreachable(node, confidence=INFERENCE)
        self._check_misplaced_format_function(node)
        if isinstance(node.func, nodes.Name):
            name = node.func.name
            # ignore the name if it's not a builtin (i.e. not defined in the
            # locals nor globals scope)
            if not (name in node.frame() or name in node.root()):
                if name == "exec":
                    self.add_message("exec-used", node=node)
                elif name == "reversed":
                    self._check_reversed(node)
                elif name == "eval":
                    self.add_message("eval-used", node=node)
References _check_misplaced_format_function(), _check_reversed(), _check_unreachable(), and pylint.checkers.base_checker.BaseChecker.add_message().
visit_classdef()
None pylint.checkers.base.basic_checker.BasicChecker.visit_classdef (self, nodes.ClassDef _)
Check module name, docstring and redefinition
increment branch counter.
Definition at line 419 of file basic_checker.py.
    def visit_classdef(self, _: nodes.ClassDef) -> None:
        """Check module name, docstring and redefinition
        increment branch counter.
        """
        self.linter.stats.node_count["klass"] += 1
References pylint.checkers.base_checker.BaseChecker.linter.
Referenced by pylint.pyreverse.inspector.Linker.visit_assignname(), and pylint.checkers.exceptions.ExceptionRaiseLeafVisitor.visit_instance().
visit_comprehension()
None pylint.checkers.base.basic_checker.BasicChecker.visit_comprehension (self, nodes.Comprehension node)
Definition at line 299 of file basic_checker.py.
    def visit_comprehension(self, node: nodes.Comprehension) -> None:
        if node.ifs:
            for if_test in node.ifs:
                self._check_using_constant_test(node, if_test)
References _check_using_constant_test().
visit_continue()
None pylint.checkers.base.basic_checker.BasicChecker.visit_continue (self, nodes.Continue node)
Check is the node has a right sibling (if so, that's some unreachable
code).
Definition at line 651 of file basic_checker.py.
    def visit_continue(self, node: nodes.Continue) -> None:
        """Check is the node has a right sibling (if so, that's some unreachable
        code).
        """
        self._check_unreachable(node)
References _check_unreachable().
visit_dict()
None pylint.checkers.base.basic_checker.BasicChecker.visit_dict (self, nodes.Dict node)
Check duplicate key in dictionary.
Definition at line 737 of file basic_checker.py.
    def visit_dict(self, node: nodes.Dict) -> None:
        """Check duplicate key in dictionary."""
        keys = set()
        for k, _ in node.items:
            if isinstance(k, nodes.Const):
                key = k.value
            elif isinstance(k, nodes.Attribute):
                key = k.as_string()
            else:
                continue
            if key in keys:
                self.add_message("duplicate-key", node=node, args=key)
            keys.add(key)
References pylint.checkers.base_checker.BaseChecker.add_message().
visit_expr()
None pylint.checkers.base.basic_checker.BasicChecker.visit_expr (self, nodes.Expr node)
Check for various kind of statements without effect.
Definition at line 432 of file basic_checker.py.
    def visit_expr(self, node: nodes.Expr) -> None:
        """Check for various kind of statements without effect."""
        expr = node.value
        if isinstance(expr, nodes.Const) and isinstance(expr.value, str):
            # treat string statement in a separated message
            # Handle PEP-257 attribute docstrings.
            # An attribute docstring is defined as being a string right after
            # an assignment at the module level, class level or __init__ level.
            scope = expr.scope()
            if isinstance(scope, (nodes.ClassDef, nodes.Module, nodes.FunctionDef)):
                if isinstance(scope, nodes.FunctionDef) and scope.name != "__init__":
                    pass
                else:
                    sibling = expr.previous_sibling()
                    if (
                        sibling is not None
                        and sibling.scope() is scope
                        and isinstance(
                            sibling, (nodes.Assign, nodes.AnnAssign, nodes.TypeAlias)
                        )
                    ):
                        return
            self.add_message("pointless-string-statement", node=node)
            return
        # Warn W0133 for exceptions that are used as statements
        if isinstance(expr, nodes.Call):
            name = ""
            if isinstance(expr.func, nodes.Name):
                name = expr.func.name
            elif isinstance(expr.func, nodes.Attribute):
                name = expr.func.attrname
            # Heuristic: only run inference for names that begin with an uppercase char
            # This reduces W0133's coverage, but retains acceptable runtime performance
            # For more details, see: https://github.com/pylint-dev/pylint/issues/8073
            inferred = utils.safe_infer(expr) if name[:1].isupper() else None
            if isinstance(inferred, objects.ExceptionInstance):
                self.add_message(
                    "pointless-exception-statement", node=node, confidence=INFERENCE
                )
            return
        # Ignore if this is :
        # * the unique child of a try/except body
        # * a yield statement
        # * an ellipsis (which can be used on Python 3 instead of pass)
        # warn W0106 if we have any underlying function call (we can't predict
        # side effects), else pointless-statement
        if (
            isinstance(expr, (nodes.Yield, nodes.Await))
            or (
                isinstance(node.parent, (nodes.Try, nodes.TryStar))
                and node.parent.body == [node]
            )
            or (isinstance(expr, nodes.Const) and expr.value is Ellipsis)
        ):
            return
        if isinstance(expr, nodes.NamedExpr):
            self.add_message("named-expr-without-context", node=node, confidence=HIGH)
        elif any(expr.nodes_of_class(nodes.Call)):
            self.add_message(
                "expression-not-assigned", node=node, args=expr.as_string()
            )
        else:
            self.add_message("pointless-statement", node=node)
References pylint.checkers.base_checker.BaseChecker.add_message().
visit_for()
None pylint.checkers.base.basic_checker.BasicChecker.visit_for (self, nodes.For node)
Definition at line 970 of file basic_checker.py.
    def visit_for(self, node: nodes.For) -> None:
        self._check_redeclared_assign_name([node.target])
References _check_redeclared_assign_name().
visit_functiondef()
None pylint.checkers.base.basic_checker.BasicChecker.visit_functiondef (self, nodes.FunctionDef node)
Check function name, docstring, arguments, redefinition,
variable names, max locals.
Definition at line 585 of file basic_checker.py.
    def visit_functiondef(self, node: nodes.FunctionDef) -> None:
        """Check function name, docstring, arguments, redefinition,
        variable names, max locals.
        """
        if node.is_method():
            self.linter.stats.node_count["method"] += 1
        else:
            self.linter.stats.node_count["function"] += 1
        self._check_dangerous_default(node)
References _check_dangerous_default(), and pylint.checkers.base_checker.BaseChecker.linter.
Referenced by pylint.pyreverse.inspector.Linker.visit_assignname().
visit_if()
None pylint.checkers.base.basic_checker.BasicChecker.visit_if (self, nodes.If node)
Definition at line 287 of file basic_checker.py.
    def visit_if(self, node: nodes.If) -> None:
        self._check_using_constant_test(node, node.test)
References _check_using_constant_test().
visit_ifexp()
None pylint.checkers.base.basic_checker.BasicChecker.visit_ifexp (self, nodes.IfExp node)
Definition at line 293 of file basic_checker.py.
    def visit_ifexp(self, node: nodes.IfExp) -> None:
        self._check_using_constant_test(node, node.test)
References _check_using_constant_test().
visit_lambda()
None pylint.checkers.base.basic_checker.BasicChecker.visit_lambda (self, nodes.Lambda node)
Check whether the lambda is suspicious.
Definition at line 527 of file basic_checker.py.
    def visit_lambda(self, node: nodes.Lambda) -> None:
        """Check whether the lambda is suspicious."""
        # if the body of the lambda is a call expression with the same
        # argument list as the lambda itself, then the lambda is
        # possibly unnecessary and at least suspicious.
        if node.args.defaults:
            # If the arguments of the lambda include defaults, then a
            # judgment cannot be made because there is no way to check
            # that the defaults defined by the lambda are the same as
            # the defaults defined by the function called in the body
            # of the lambda.
            return
        call = node.body
        if not isinstance(call, nodes.Call):
            # The body of the lambda must be a function call expression
            # for the lambda to be unnecessary.
            return
        if isinstance(node.body.func, nodes.Attribute) and isinstance(
            node.body.func.expr, nodes.Call
        ):
            # Chained call, the intermediate call might
            # return something else (but we don't check that, yet).
            return
        ordinary_args = list(node.args.args)
        new_call_args = list(self._filter_vararg(node, call.args))
        if node.args.kwarg:
            if self._has_variadic_argument(call.keywords, node.args.kwarg):
                return
        elif call.keywords:
            return
        if node.args.vararg:
            if self._has_variadic_argument(call.starargs, node.args.vararg):
                return
        elif call.starargs:
            return
        # The "ordinary" arguments must be in a correspondence such that:
        # ordinary_args[i].name == call.args[i].name.
        if len(ordinary_args) != len(new_call_args):
            return
        for arg, passed_arg in zip(ordinary_args, new_call_args):
            if not isinstance(passed_arg, nodes.Name):
                return
            if arg.name != passed_arg.name:
                return
        # The lambda is necessary if it uses its parameter in the function it is
        # calling in the lambda's body
        # e.g. lambda foo: (func1 if foo else func2)(foo)
        for name in call.func.nodes_of_class(nodes.Name):
            if name.lookup(name.name)[0] is node:
                return
        self.add_message("unnecessary-lambda", line=node.fromlineno, node=node)
References _filter_vararg(), _has_variadic_argument(), and pylint.checkers.base_checker.BaseChecker.add_message().
visit_module()
None pylint.checkers.base.basic_checker.BasicChecker.visit_module (self, nodes.Module _)
Check module name, docstring and required arguments.
Definition at line 415 of file basic_checker.py.
    def visit_module(self, _: nodes.Module) -> None:
        """Check module name, docstring and required arguments."""
        self.linter.stats.node_count["module"] += 1
References pylint.checkers.base_checker.BaseChecker.linter.
Referenced by pylint.pyreverse.inspector.Linker.visit_assignname().
visit_raise()
None pylint.checkers.base.basic_checker.BasicChecker.visit_raise (self, nodes.Raise node)
Check if the node has a right sibling (if so, that's some unreachable
code).
Definition at line 672 of file basic_checker.py.
    def visit_raise(self, node: nodes.Raise) -> None:
        """Check if the node has a right sibling (if so, that's some unreachable
        code).
        """
        self._check_unreachable(node)
References _check_unreachable().
visit_return()
None pylint.checkers.base.basic_checker.BasicChecker.visit_return (self, nodes.Return node)
Return node visitor.
1 - check if the node has a right sibling (if so, that's some
unreachable code)
2 - check if the node is inside the 'finally' clause of a 'try...finally'
block
Definition at line 638 of file basic_checker.py.
    def visit_return(self, node: nodes.Return) -> None:
        """Return node visitor.
        1 - check if the node has a right sibling (if so, that's some
        unreachable code)
        2 - check if the node is inside the 'finally' clause of a 'try...finally'
        block
        """
        self._check_unreachable(node)
        # Is it inside final body of a try...finally block ?
        self._check_not_in_finally(node, "return", (nodes.FunctionDef,))
References _check_not_in_finally(), and _check_unreachable().
Referenced by pylint.checkers.refactoring.refactoring_checker.RefactoringChecker.visit_assign().
visit_set()
None pylint.checkers.base.basic_checker.BasicChecker.visit_set (self, nodes.Set node)
Check duplicate value in set.
Definition at line 752 of file basic_checker.py.
    def visit_set(self, node: nodes.Set) -> None:
        """Check duplicate value in set."""
        values = set()
        for v in node.elts:
            if isinstance(v, nodes.Const):
                value = v.value
            else:
                continue
            if value in values:
                self.add_message(
                    "duplicate-value", node=node, args=value, confidence=HIGH
                )
            values.add(value)
References pylint.checkers.base_checker.BaseChecker.add_message().
visit_try()
None pylint.checkers.base.basic_checker.BasicChecker.visit_try (self, nodes.Try node)
Update try block flag.
Definition at line 766 of file basic_checker.py.
    def visit_try(self, node: nodes.Try) -> None:
        """Update try block flag."""
        self._trys.append(node)
        for final_node in node.finalbody:
            for return_node in final_node.nodes_of_class(nodes.Return):
                self.add_message("return-in-finally", node=return_node, confidence=HIGH)
References _trys, and pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by pylint.checkers.exceptions.ExceptionsChecker.visit_trystar().
visit_with()
None pylint.checkers.base.basic_checker.BasicChecker.visit_with (self, nodes.With node)
Definition at line 883 of file basic_checker.py.
    def visit_with(self, node: nodes.With) -> None:
        # a "with" statement with multiple managers corresponds
        # to one AST "With" node with multiple items
        pairs = node.items
        if pairs:
            for prev_pair, pair in zip(pairs, pairs[1:]):
                if isinstance(prev_pair[1], nodes.AssignName) and (
                    pair[1] is None and not isinstance(pair[0], nodes.Call)
                ):
                    # Don't emit a message if the second is a function call
                    # there's no way that can be mistaken for a name assignment.
                    # If the line number doesn't match
                    # we assume it's a nested "with".
                    self.add_message("confusing-with-statement", node=node)
References pylint.checkers.base_checker.BaseChecker.add_message().
Member Data Documentation
_py38_plus
tuple pylint.checkers.base.basic_checker.BasicChecker._py38_plus = (3, 8) protected
Definition at line 280 of file basic_checker.py.
Referenced by pylint.checkers.base.basic_error_checker.BasicErrorChecker._check_in_loop(), pylint.checkers.classes.class_checker.ClassChecker._check_invalid_overridden_method(), _check_reversed(), pylint.checkers.classes.class_checker.ClassChecker._check_typing_final(), pylint.checkers.unsupported_version.UnsupportedVersionChecker._check_typing_final(), pylint.checkers.unsupported_version.UnsupportedVersionChecker.visit_arguments(), pylint.extensions.code_style.CodeStyleChecker.visit_if(), and pylint.checkers.unsupported_version.UnsupportedVersionChecker.visit_namedexpr().
_trys
list[nodes.Try] pylint.checkers.base.basic_checker.BasicChecker._trys protected
Definition at line 275 of file basic_checker.py.
Referenced by _check_not_in_finally(), leave_try(), and visit_try().
visit_asyncfunctiondef
None pylint.checkers.base.basic_checker.BasicChecker.visit_asyncfunctiondef = visit_functiondef static
Definition at line 595 of file basic_checker.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pylint/checkers/base/basic_checker.py