Read&Watch: django.contrib.gis.management.commands.inspectdb.Command Class Reference
django.contrib.gis.management.commands.inspectdb.Command Class Reference
Public Member Functions
get_field_type (self, connection, table_name, row)
Static Public Attributes
str db_module = "django.contrib.gis.db"
Detailed Description
Definition at line 4 of file inspectdb.py.
Member Function Documentation
get_field_type()
django.contrib.gis.management.commands.inspectdb.Command.get_field_type (self, connection, table_name, row)
Definition at line 7 of file inspectdb.py.
    def get_field_type(self, connection, table_name, row):
        field_type, field_params, field_notes = super().get_field_type(
            connection, table_name, row
        )
        if field_type == "GeometryField":
            # Getting a more specific field type and any additional parameters
            # from the `get_geometry_type` routine for the spatial backend.
            field_type, geo_params = connection.introspection.get_geometry_type(
                table_name, row
            )
            field_params.update(geo_params)
        return field_type, field_params, field_notes
References get_field_type().
Referenced by get_field_type(), and django.core.management.commands.inspectdb.Command.handle_inspection().
Member Data Documentation
db_module
str django.contrib.gis.management.commands.inspectdb.Command.db_module = "django.contrib.gis.db" static
Definition at line 5 of file inspectdb.py.
Referenced by django.core.management.commands.inspectdb.Command.handle_inspection().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/gis/management/commands/inspectdb.py