Read&Watch: crispy_forms.bootstrap.Accordion Class Reference
crispy_forms.bootstrap.Accordion Class Reference
Public Member Functions
__init__ (self, *accordion_groups, css_id=None, css_class=None, template=None, **kwargs)
render (self, form, context, template_pack=TEMPLATE_PACK, **kwargs)
Public Member Functions inherited from crispy_forms.bootstrap.ContainerHolder
first_container_with_errors (self, errors)
open_target_group_for_form (self, form)
Public Member Functions inherited from crispy_forms.layout.Div
__init__ (self, *fields, css_id=None, css_class=None, template=None, **kwargs)
Public Member Functions inherited from crispy_forms.layout.LayoutObject
__getitem__ (self, slice)
__setitem__ (self, slice, value)
__delitem__ (self, slice)
__len__ (self)
__getattr__ (self, name)
get_field_names (self, index=None)
get_layout_objects (self, *LayoutClasses, index=None, max_level=0, greedy=False)
get_rendered_fields (self, form, context, template_pack=TEMPLATE_PACK, **kwargs)
Public Member Functions inherited from crispy_forms.layout.TemplateNameMixin
get_template_name (self, template_pack)
Additional Inherited Members
Public Attributes inherited from crispy_forms.layout.Div
css_id = css_id
flat_attrs = flatatt(kwargs)
Public Attributes inherited from crispy_forms.layout.LayoutObject
fields
Public Attributes inherited from crispy_forms.layout.TemplateNameMixin
template
Static Public Attributes inherited from crispy_forms.layout.Div
css_class = None
Detailed Description
Accordion menu object. It wraps `AccordionGroup` objects in a container
Attributes
----------
template : str
    The default template which this Layout Object will be rendered
    with.
css_class : str, optional
    CSS classes to be applied to the ``<div>``. By default None.
Parameters
----------
*accordion_groups : str, LayoutObject
    Any number of layout objects as positional arguments to be rendered
    within the ``<div>``.
css_id : str, optional
    A DOM id for the layout object which will be added to the ``<div>`` if
    provided. By default None.
css_class : str, optional
    Additional CSS classes to be applied in addition to those declared by
    the class itself. By default None.
template : str, optional
    Overrides the default template, if provided. By default None.
**kwargs : dict, optional
    Additional attributes are passed to ``flatatt`` and converted into
    key="value", pairs. These attributes are added to the ``<div>``.
Examples
--------
Example::
    Accordion(
        AccordionGroup("group name", "form_field_1", "form_field_2"),
        AccordionGroup("another group name", "form_field")
    )
Definition at line 835 of file bootstrap.py.
Constructor & Destructor Documentation
__init__()
crispy_forms.bootstrap.Accordion.__init__ (self, * accordion_groups, css_id = None, css_class = None, template = None, ** kwargs)
Definition at line 877 of file bootstrap.py.
    def __init__(self, *accordion_groups, css_id=None, css_class=None, template=None, **kwargs):
        super().__init__(*accordion_groups, css_id=css_id, css_class=css_class, template=template, **kwargs)
        # Accordion needs to have a unique id
        if not self.css_id:
            self.css_id = "-".join(["accordion", str(randint(1000, 9999))])
        # AccordionGroup need to have 'data-parent="#Accordion.id"'
        for accordion_group in accordion_groups:
            accordion_group.data_parent = self.css_id
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Function Documentation
render()
crispy_forms.bootstrap.Accordion.render (self, form, context, template_pack = TEMPLATE_PACK, ** kwargs)
Reimplemented from crispy_forms.layout.Div.
Definition at line 888 of file bootstrap.py.
    def render(self, form, context, template_pack=TEMPLATE_PACK, **kwargs):
        content = SafeString("")
        # Open the group that should be open.
        self.open_target_group_for_form(form)
        for group in self.fields:
            group.data_parent = self.css_id
            content += render_field(group, form, context, template_pack=template_pack, **kwargs)
        template = self.get_template_name(template_pack)
        context.update({"accordion": self, "content": content})
        return render_to_string(template, context.flatten())
References crispy_forms.bootstrap.ContainerHolder.open_target_group_for_form().
Referenced by pip._vendor.rich.progress.ProgressColumn.__call__(), pip._vendor.rich.layout.Layout.__rich_console__(), pip._vendor.rich.spinner.Spinner.__rich_console__(), pip._vendor.rich.spinner.Spinner.__rich_measure__(), django.forms.widgets.Media.__str__(), django.forms.utils.RenderableFieldMixin.as_field_group(), pip._vendor.rich.console.Console.log(), pip._vendor.rich.console.Console.print(), django.templatetags.i18n.BlockTranslateNode.render(), pip._vendor.rich.console.Console.render(), pip._vendor.rich.console.Console.render_lines(), django.db.migrations.writer.OperationWriter.serialize(), and pip._vendor.rich.console.Console.update_screen_lines().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/crispy_forms/bootstrap.py