Read&Watch: PIL.BlpImagePlugin.BLP1Decoder Class Reference
PIL.BlpImagePlugin.BLP1Decoder Class Reference
Protected Member Functions
None _load (self)
None _decode_jpeg_stream (self)
Protected Member Functions inherited from PIL.BlpImagePlugin._BLPBaseDecoder
None _read_blp_header (self)
bytes _safe_read (self, int length)
list[tuple[int, int, int, int]] _read_palette (self)
bytearray _read_bgra (self, list[tuple[int, int, int, int]] palette)
Additional Inherited Members
Public Member Functions inherited from PIL.BlpImagePlugin._BLPBaseDecoder
tuple[int, int] decode (self, bytes|Image.SupportsArrayInterface buffer)
Public Member Functions inherited from PIL.ImageFile.PyDecoder
bool pulls_fd (self)
None set_as_raw (self, bytes data, str|None rawmode=None, tuple[Any,...] extra=())
Public Member Functions inherited from PIL.ImageFile.PyCodec
None __init__ (self, str mode, *Any args)
None init (self, tuple[Any,...] args)
None cleanup (self)
None setfd (self, IO[bytes] fd)
None setimage (self, Image.core.ImagingCore im, tuple[int, int, int, int]|None extents=None)
Public Attributes inherited from PIL.BlpImagePlugin._BLPBaseDecoder
size = struct.unpack("<II", self._safe_read(8))
Public Attributes inherited from PIL.ImageFile.PyCodec
Image.core.ImagingCore|None im = None
state = PyCodecState()
mode = mode
args = args
Static Public Attributes inherited from PIL.ImageFile.PyCodec
IO fd [bytes] | None
Protected Attributes inherited from PIL.BlpImagePlugin._BLPBaseDecoder
_blp_compression
_blp_encoding = struct.unpack("<i", self._safe_read(4))
_blp_alpha_depth = struct.unpack("<b", self._safe_read(1))
_blp_alpha_encoding = struct.unpack("<b", self._safe_read(1))
_blp_offsets = struct.unpack("<16I", self._safe_read(16 * 4))
_blp_lengths = struct.unpack("<16I", self._safe_read(16 * 4))
Static Protected Attributes inherited from PIL.ImageFile.PyDecoder
bool _pulls_fd = False
Detailed Description
Definition at line 345 of file BlpImagePlugin.py.
Member Function Documentation
_decode_jpeg_stream()
None PIL.BlpImagePlugin.BLP1Decoder._decode_jpeg_stream (self) protected
Definition at line 362 of file BlpImagePlugin.py.
    def _decode_jpeg_stream(self) -> None:
        from .JpegImagePlugin import JpegImageFile
        (jpeg_header_size,) = struct.unpack("<I", self._safe_read(4))
        jpeg_header = self._safe_read(jpeg_header_size)
        assert self.fd is not None
        self._safe_read(self._blp_offsets[0] - self.fd.tell())  # What IS this?
        data = self._safe_read(self._blp_lengths[0])
        data = jpeg_header + data
        image = JpegImageFile(BytesIO(data))
        Image._decompression_bomb_check(image.size)
        if image.mode == "CMYK":
            decoder_name, extents, offset, args = image.tile[0]
            assert isinstance(args, tuple)
            image.tile = [
                ImageFile._Tile(decoder_name, extents, offset, (args[0], "CMYK"))
            ]
        r, g, b = image.convert("RGB").split()
        reversed_image = Image.merge("RGB", (b, g, r))
        self.set_as_raw(reversed_image.tobytes())
References PIL.BlpImagePlugin._BLPBaseDecoder._blp_lengths, PIL.BlpImagePlugin._BLPBaseDecoder._blp_offsets, PIL.BlpImagePlugin._BLPBaseDecoder._safe_read(), PIL.BlpImagePlugin._BLPBaseDecoder.fd, and PIL.ImageFile.PyDecoder.set_as_raw().
_load()
None PIL.BlpImagePlugin.BLP1Decoder._load (self) protected
Reimplemented from PIL.BlpImagePlugin._BLPBaseDecoder.
Definition at line 346 of file BlpImagePlugin.py.
    def _load(self) -> None:
        if self._blp_compression == Format.JPEG:
            self._decode_jpeg_stream()
        elif self._blp_compression == 1:
            if self._blp_encoding in (4, 5):
                palette = self._read_palette()
                data = self._read_bgra(palette)
                self.set_as_raw(data)
            else:
                msg = f"Unsupported BLP encoding {repr(self._blp_encoding)}"
                raise BLPFormatError(msg)
        else:
            msg = f"Unsupported BLP compression {repr(self._blp_encoding)}"
            raise BLPFormatError(msg)
Referenced by PIL.ImageFile.StubImageFile.load().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/PIL/BlpImagePlugin.py