Read&Watch: django.utils.translation.override Class Reference
django.utils.translation.override Class Reference
Public Member Functions
__init__ (self, language, deactivate=False)
__enter__ (self)
__exit__ (self, exc_type, exc_value, traceback)
Public Attributes
language = language
deactivate = deactivate
old_language = get_language()
Detailed Description
Definition at line 189 of file __init__.py.
Constructor & Destructor Documentation
__init__()
django.utils.translation.override.__init__ (self, language, deactivate = False)
Definition at line 190 of file __init__.py.
    def __init__(self, language, deactivate=False):
        self.language = language
        self.deactivate = deactivate
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
__enter__()
django.utils.translation.override.__enter__ (self)
Definition at line 194 of file __init__.py.
    def __enter__(self):
        self.old_language = get_language()
        if self.language is not None:
            activate(self.language)
        else:
            deactivate_all()
__exit__()
django.utils.translation.override.__exit__ (self, exc_type, exc_value, traceback)
Definition at line 201 of file __init__.py.
    def __exit__(self, exc_type, exc_value, traceback):
        if self.old_language is None:
            deactivate_all()
        elif self.deactivate:
            deactivate()
        else:
            activate(self.old_language)
References django.utils.translation.activate(), deactivate, django.utils.translation.deactivate_all(), and old_language.
Member Data Documentation
deactivate
django.utils.translation.override.deactivate = deactivate
Definition at line 192 of file __init__.py.
Referenced by __exit__().
language
django.utils.translation.override.language = language
Definition at line 191 of file __init__.py.
old_language
django.utils.translation.override.old_language = get_language()
Definition at line 195 of file __init__.py.
Referenced by __exit__().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/utils/translation/__init__.py