Read&Watch: django.template.base.DebugLexer Class Reference
django.template.base.DebugLexer Class Reference
Public Member Functions
tokenize (self)
Public Member Functions inherited from django.template.base.Lexer
__init__ (self, template_string)
__repr__ (self)
create_token (self, token_string, position, lineno, in_tag)
Protected Member Functions
_tag_re_split_positions (self)
_tag_re_split (self)
Additional Inherited Members
Public Attributes inherited from django.template.base.Lexer
template_string = template_string
bool verbatim = False
Detailed Description
Definition at line 401 of file base.py.
Member Function Documentation
_tag_re_split()
django.template.base.DebugLexer._tag_re_split (self) protected
Definition at line 412 of file base.py.
    def _tag_re_split(self):
        for position in self._tag_re_split_positions():
            yield self.template_string[slice(*position)], position
References _tag_re_split_positions(), and django.template.base.Lexer.template_string.
Referenced by tokenize().
_tag_re_split_positions()
django.template.base.DebugLexer._tag_re_split_positions (self) protected
Definition at line 402 of file base.py.
    def _tag_re_split_positions(self):
        last = 0
        for match in tag_re.finditer(self.template_string):
            start, end = match.span()
            yield last, start
            yield start, end
            last = end
        yield last, len(self.template_string)
Referenced by _tag_re_split().
tokenize()
django.template.base.DebugLexer.tokenize (self)
Split a template string into tokens and annotates each token with its
start and end position in the source. This is slower than the default
lexer so only use it when debug is True.
Reimplemented from django.template.base.Lexer.
Definition at line 416 of file base.py.
    def tokenize(self):
        """
        Split a template string into tokens and annotates each token with its
        start and end position in the source. This is slower than the default
        lexer so only use it when debug is True.
        """
        # For maintainability, it is helpful if the implementation below can
        # continue to closely parallel Lexer.tokenize()'s implementation.
        in_tag = False
        lineno = 1
        result = []
        for token_string, position in self._tag_re_split():
            if token_string:
                result.append(self.create_token(token_string, position, lineno, in_tag))
                lineno += token_string.count("\n")
            in_tag = not in_tag
        return result
References _tag_re_split(), and django.template.base.Lexer.create_token().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/template/base.py