Read&Watch: pylint.checkers.stdlib.StdlibChecker Class Reference
pylint.checkers.stdlib.StdlibChecker Class Reference
Public Member Functions
None __init__ (self, PyLinter linter)
None visit_call (self, nodes.Call node)
None visit_unaryop (self, nodes.UnaryOp node)
None visit_if (self, nodes.If node)
None visit_ifexp (self, nodes.IfExp node)
None visit_boolop (self, nodes.BoolOp node)
None visit_functiondef (self, nodes.FunctionDef node)
set[str] deprecated_methods (self)
tuple[tuple[int|None, str],...] deprecated_arguments (self, str method)
Iterable[str] deprecated_classes (self, str module)
Iterable[str] deprecated_decorators (self)
Iterable[str] deprecated_attributes (self)
Public Member Functions inherited from pylint.checkers.deprecated.DeprecatedMixin
None visit_attribute (self, astroid.Attribute node)
None visit_import (self, nodes.Import node)
None visit_decorators (self, nodes.Decorators node)
None visit_importfrom (self, nodes.ImportFrom node)
Iterable[str] deprecated_modules (self)
None check_deprecated_attribute (self, astroid.Attribute node)
None check_deprecated_module (self, nodes.Import node, str|None mod_path)
None check_deprecated_method (self, nodes.Call node, nodes.NodeNG inferred)
None check_deprecated_class (self, nodes.NodeNG node, str mod_name, Iterable[str] class_names)
None check_deprecated_class_in_call (self, nodes.Call node)
Public Member Functions inherited from pylint.checkers.base_checker.BaseChecker
None __init__ (self, PyLinter linter)
bool __gt__ (self, Any other)
bool __eq__ (self, object other)
int __hash__ (self)
str __repr__ (self)
str __str__ (self)
str get_full_documentation (self, dict[str, MessageDefinitionTuple] msgs, Iterable[tuple[str, OptionDict, Any]] options, Sequence[tuple[str, str, ReportsCallable]] reports, str|None doc=None, str|None module=None, bool show_options=True)
None add_message (self, str msgid, int|None line=None, nodes.NodeNG|None node=None, Any args=None, Confidence|None confidence=None, int|None col_offset=None, int|None end_lineno=None, int|None end_col_offset=None)
None check_consistency (self)
MessageDefinition create_message_definition_from_tuple (self, str msgid, MessageDefinitionTuple msg_tuple)
list[MessageDefinition] messages (self)
None open (self)
None close (self)
Any get_map_data (self)
None reduce_map_data (self, PyLinter linter, list[Any] data)
Public Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
None __init__ (self, _ArgumentsManager arguments_manager)
Protected Member Functions
None _check_bad_thread_instantiation (self, nodes.Call node)
None _check_for_preexec_fn_in_popen (self, nodes.Call node)
None _check_for_check_kw_in_run (self, nodes.Call node)
None _check_shallow_copy_environ (self, nodes.Call node)
None _check_lru_cache_decorators (self, nodes.FunctionDef node)
None _check_dispatch_decorators (self, nodes.FunctionDef node)
None _check_redundant_assert (self, nodes.Call node, InferenceResult infer)
None _check_datetime (self, nodes.NodeNG node)
None _check_open_call (self, nodes.Call node, str open_module, str func_name)
None _check_env_function (self, nodes.Call node, nodes.FunctionDef infer)
None _check_invalid_envvar_value (self, nodes.Call node, nodes.FunctionDef infer, str message, InferenceResult|None call_arg, bool allow_none)
Protected Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
Any _option_value (self, str opt)
Iterator[ tuple[str, list[tuple[str, OptionDict, Any]]]|tuple[None, dict[str, list[tuple[str, OptionDict, Any]]]]] _options_by_section (self)
Iterator[tuple[str, OptionDict, Any]] _options_and_values (self, Options|None options=None)
Protected Attributes
set[str] _deprecated_methods = set()
dict _deprecated_arguments = {}
dict _deprecated_classes = {}
set[str] _deprecated_decorators = set()
set[str] _deprecated_attributes = set()
Protected Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
_arguments_manager = arguments_manager
Additional Inherited Members
Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
linter = linter
messages
Static Public Attributes inherited from pylint.checkers.deprecated.DeprecatedMixin
dict DEPRECATED_ATTRIBUTE_MESSAGE
dict DEPRECATED_MODULE_MESSAGE
dict DEPRECATED_METHOD_MESSAGE
dict DEPRECATED_ARGUMENT_MESSAGE
dict DEPRECATED_CLASS_MESSAGE
dict DEPRECATED_DECORATOR_MESSAGE
Static Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
str name = ""
dict msgs = {}
tuple reports = ()
bool enabled = True
Static Public Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
tuple options = ()
dict option_groups_descs = {}
Detailed Description
Definition at line 460 of file stdlib.py.
Constructor & Destructor Documentation
__init__()
None pylint.checkers.stdlib.StdlibChecker.__init__ (self, PyLinter linter)
Definition at line 582 of file stdlib.py.
    def __init__(self, linter: PyLinter) -> None:
        BaseChecker.__init__(self, linter)
        self._deprecated_methods: set[str] = set()
        self._deprecated_arguments: dict[str, tuple[tuple[int | None, str], ...]] = {}
        self._deprecated_classes: dict[str, set[str]] = {}
        self._deprecated_decorators: set[str] = set()
        self._deprecated_attributes: set[str] = set()
        for since_vers, func_list in DEPRECATED_METHODS[sys.version_info[0]].items():
            if since_vers <= sys.version_info:
                self._deprecated_methods.update(func_list)
        for since_vers, args_list in DEPRECATED_ARGUMENTS.items():
            if since_vers <= sys.version_info:
                self._deprecated_arguments.update(args_list)
        for since_vers, class_list in DEPRECATED_CLASSES.items():
            if since_vers <= sys.version_info:
                self._deprecated_classes.update(class_list)
        for since_vers, decorator_list in DEPRECATED_DECORATORS.items():
            if since_vers <= sys.version_info:
                self._deprecated_decorators.update(decorator_list)
        for since_vers, attribute_list in DEPRECATED_ATTRIBUTES.items():
            if since_vers <= sys.version_info:
                self._deprecated_attributes.update(attribute_list)
        # Modules are checked by the ImportsChecker, because the list is
        # synced with the config argument deprecated-modules
Member Function Documentation
_check_bad_thread_instantiation()
None pylint.checkers.stdlib.StdlibChecker._check_bad_thread_instantiation (self, nodes.Call node) protected
Definition at line 608 of file stdlib.py.
    def _check_bad_thread_instantiation(self, node: nodes.Call) -> None:
        func_kwargs = {key.arg for key in node.keywords}
        if "target" in func_kwargs:
            return
        if len(node.args) < 2 and (not node.kwargs or "target" not in func_kwargs):
            self.add_message(
                "bad-thread-instantiation", node=node, confidence=interfaces.HIGH
            )
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_call().
_check_datetime()
None pylint.checkers.stdlib.StdlibChecker._check_datetime (self, nodes.NodeNG node) protected
Check that a datetime was inferred, if so, emit boolean-datetime warning.
Definition at line 809 of file stdlib.py.
    def _check_datetime(self, node: nodes.NodeNG) -> None:
        """Check that a datetime was inferred, if so, emit boolean-datetime warning."""
        try:
            inferred = next(node.infer())
        except astroid.InferenceError:
            return
        if isinstance(inferred, astroid.Instance) and inferred.qname() in {
            "_pydatetime.time",
            "datetime.time",
        }:
            self.add_message("boolean-datetime", node=node)
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_boolop(), visit_if(), visit_ifexp(), and visit_unaryop().
_check_dispatch_decorators()
None pylint.checkers.stdlib.StdlibChecker._check_dispatch_decorators (self, nodes.FunctionDef node) protected
Definition at line 768 of file stdlib.py.
    def _check_dispatch_decorators(self, node: nodes.FunctionDef) -> None:
        decorators_map: dict[str, tuple[nodes.NodeNG, interfaces.Confidence]] = {}
        for decorator in node.decorators.nodes:
            if isinstance(decorator, nodes.Name) and decorator.name:
                decorators_map[decorator.name] = (decorator, interfaces.HIGH)
            elif utils.is_registered_in_singledispatch_function(node):
                decorators_map["singledispatch"] = (decorator, interfaces.INFERENCE)
            elif utils.is_registered_in_singledispatchmethod_function(node):
                decorators_map["singledispatchmethod"] = (
                    decorator,
                    interfaces.INFERENCE,
                )
        if node.is_method():
            if "singledispatch" in decorators_map:
                self.add_message(
                    "singledispatch-method",
                    node=decorators_map["singledispatch"][0],
                    confidence=decorators_map["singledispatch"][1],
                )
        elif "singledispatchmethod" in decorators_map:
            self.add_message(
                "singledispatchmethod-function",
                node=decorators_map["singledispatchmethod"][0],
                confidence=decorators_map["singledispatchmethod"][1],
            )
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_functiondef().
_check_env_function()
None pylint.checkers.stdlib.StdlibChecker._check_env_function (self, nodes.Call node, nodes.FunctionDef infer) protected
Definition at line 896 of file stdlib.py.
    def _check_env_function(self, node: nodes.Call, infer: nodes.FunctionDef) -> None:
        env_name_kwarg = "key"
        env_value_kwarg = "default"
        if node.keywords:
            kwargs = {keyword.arg: keyword.value for keyword in node.keywords}
        else:
            kwargs = None
        if node.args:
            env_name_arg = node.args[0]
        elif kwargs and env_name_kwarg in kwargs:
            env_name_arg = kwargs[env_name_kwarg]
        else:
            env_name_arg = None
        if env_name_arg:
            self._check_invalid_envvar_value(
                node=node,
                message="invalid-envvar-value",
                call_arg=utils.safe_infer(env_name_arg),
                infer=infer,
                allow_none=False,
            )
        if len(node.args) == 2:
            env_value_arg = node.args[1]
        elif kwargs and env_value_kwarg in kwargs:
            env_value_arg = kwargs[env_value_kwarg]
        else:
            env_value_arg = None
        if env_value_arg:
            self._check_invalid_envvar_value(
                node=node,
                infer=infer,
                message="invalid-envvar-default",
                call_arg=utils.safe_infer(env_value_arg),
                allow_none=True,
            )
References _check_invalid_envvar_value().
Referenced by visit_call().
_check_for_check_kw_in_run()
None pylint.checkers.stdlib.StdlibChecker._check_for_check_kw_in_run (self, nodes.Call node) protected
Definition at line 624 of file stdlib.py.
    def _check_for_check_kw_in_run(self, node: nodes.Call) -> None:
        kwargs = {keyword.arg for keyword in (node.keywords or ())}
        if "check" not in kwargs:
            self.add_message("subprocess-run-check", node=node, confidence=INFERENCE)
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_call().
_check_for_preexec_fn_in_popen()
None pylint.checkers.stdlib.StdlibChecker._check_for_preexec_fn_in_popen (self, nodes.Call node) protected
Definition at line 618 of file stdlib.py.
    def _check_for_preexec_fn_in_popen(self, node: nodes.Call) -> None:
        if node.keywords:
            for keyword in node.keywords:
                if keyword.arg == "preexec_fn":
                    self.add_message("subprocess-popen-preexec-fn", node=node)
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_call().
_check_invalid_envvar_value()
None pylint.checkers.stdlib.StdlibChecker._check_invalid_envvar_value (self, nodes.Call node, nodes.FunctionDef infer, str message, InferenceResult | None call_arg, bool allow_none) protected
Definition at line 935 of file stdlib.py.
    ) -> None:
        if call_arg is None or isinstance(call_arg, util.UninferableBase):
            return
        name = infer.qname()
        if isinstance(call_arg, nodes.Const):
            emit = False
            if call_arg.value is None:
                emit = not allow_none
            elif not isinstance(call_arg.value, str):
                emit = True
            if emit:
                self.add_message(message, node=node, args=(name, call_arg.pytype()))
        else:
            self.add_message(message, node=node, args=(name, call_arg.pytype()))
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by _check_env_function().
_check_lru_cache_decorators()
None pylint.checkers.stdlib.StdlibChecker._check_lru_cache_decorators (self, nodes.FunctionDef node) protected
Check if instance methods are decorated with functools.lru_cache.
Definition at line 726 of file stdlib.py.
    def _check_lru_cache_decorators(self, node: nodes.FunctionDef) -> None:
        """Check if instance methods are decorated with functools.lru_cache."""
        if any(utils.is_enum(ancestor) for ancestor in node.parent.ancestors()):
            # method of class inheriting from Enum is exempt from this check.
            return
        lru_cache_nodes: list[nodes.NodeNG] = []
        for d_node in node.decorators.nodes:
            # pylint: disable = too-many-try-statements
            try:
                for infered_node in d_node.infer():
                    q_name = infered_node.qname()
                    if q_name in NON_INSTANCE_METHODS:
                        return
                    # Check if there is a maxsize argument set to None in the call
                    if q_name in LRU_CACHE and isinstance(d_node, nodes.Call):
                        try:
                            arg = utils.get_argument_from_call(
                                d_node, position=0, keyword="maxsize"
                            )
                        except utils.NoSuchArgumentError:
                            arg = utils.infer_kwarg_from_call(d_node, "maxsize")
                        if not isinstance(arg, nodes.Const) or arg.value is not None:
                            break
                        lru_cache_nodes.append(d_node)
                        break
                    if q_name == "functools.cache":
                        lru_cache_nodes.append(d_node)
                        break
            except astroid.InferenceError:
                pass
        for lru_cache_node in lru_cache_nodes:
            self.add_message(
                "method-cache-max-size-none",
                node=lru_cache_node,
                confidence=interfaces.INFERENCE,
            )
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_functiondef().
_check_open_call()
None pylint.checkers.stdlib.StdlibChecker._check_open_call (self, nodes.Call node, str open_module, str func_name) protected
Various checks for an open call.
Definition at line 821 of file stdlib.py.
    ) -> None:
        """Various checks for an open call."""
        mode_arg = None
        confidence = HIGH
        try:
            if open_module == "_io":
                mode_arg = utils.get_argument_from_call(
                    node, position=1, keyword="mode"
                )
            elif open_module in PATHLIB_MODULE:
                mode_arg = utils.get_argument_from_call(
                    node, position=0, keyword="mode"
                )
        except utils.NoSuchArgumentError:
            mode_arg = utils.infer_kwarg_from_call(node, keyword="mode")
            if mode_arg:
                confidence = INFERENCE
        if mode_arg:
            mode_arg = utils.safe_infer(mode_arg)
            if (
                func_name in OPEN_FILES_MODE
                and isinstance(mode_arg, nodes.Const)
                and not _check_mode_str(mode_arg.value)
            ):
                self.add_message(
                    "bad-open-mode",
                    node=node,
                    args=mode_arg.value or str(mode_arg.value),
                    confidence=confidence,
                )
        if (
            not mode_arg
            or isinstance(mode_arg, nodes.Const)
            and (not mode_arg.value or "b" not in str(mode_arg.value))
        ):
            confidence = HIGH
            try:
                if open_module in PATHLIB_MODULE:
                    if node.func.attrname == "read_text":
                        encoding_arg = utils.get_argument_from_call(
                            node, position=0, keyword="encoding"
                        )
                    elif node.func.attrname == "write_text":
                        encoding_arg = utils.get_argument_from_call(
                            node, position=1, keyword="encoding"
                        )
                    else:
                        encoding_arg = utils.get_argument_from_call(
                            node, position=2, keyword="encoding"
                        )
                else:
                    encoding_arg = utils.get_argument_from_call(
                        node, position=3, keyword="encoding"
                    )
            except utils.NoSuchArgumentError:
                encoding_arg = utils.infer_kwarg_from_call(node, keyword="encoding")
                if encoding_arg:
                    confidence = INFERENCE
                else:
                    self.add_message(
                        "unspecified-encoding", node=node, confidence=confidence
                    )
            if encoding_arg:
                encoding_arg = utils.safe_infer(encoding_arg)
                if isinstance(encoding_arg, nodes.Const) and encoding_arg.value is None:
                    self.add_message(
                        "unspecified-encoding", node=node, confidence=confidence
                    )
References pylint.checkers.stdlib._check_mode_str(), and pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_call().
_check_redundant_assert()
None pylint.checkers.stdlib.StdlibChecker._check_redundant_assert (self, nodes.Call node, InferenceResult infer) protected
Definition at line 796 of file stdlib.py.
    def _check_redundant_assert(self, node: nodes.Call, infer: InferenceResult) -> None:
        if (
            isinstance(infer, astroid.BoundMethod)
            and node.args
            and isinstance(node.args[0], nodes.Const)
            and infer.name in {"assertTrue", "assertFalse"}
        ):
            self.add_message(
                "redundant-unittest-assert",
                args=(infer.name, node.args[0].value),
                node=node,
            )
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_call().
_check_shallow_copy_environ()
None pylint.checkers.stdlib.StdlibChecker._check_shallow_copy_environ (self, nodes.Call node) protected
Definition at line 629 of file stdlib.py.
    def _check_shallow_copy_environ(self, node: nodes.Call) -> None:
        confidence = HIGH
        try:
            arg = utils.get_argument_from_call(node, position=0, keyword="x")
        except utils.NoSuchArgumentError:
            arg = utils.infer_kwarg_from_call(node, keyword="x")
            if not arg:
                return
            confidence = INFERENCE
        try:
            inferred_args = arg.inferred()
        except astroid.InferenceError:
            return
        for inferred in inferred_args:
            if inferred.qname() == OS_ENVIRON:
                self.add_message(
                    "shallow-copy-environ", node=node, confidence=confidence
                )
                break
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_call().
deprecated_arguments()
tuple[tuple[int | None, str], ...] pylint.checkers.stdlib.StdlibChecker.deprecated_arguments (self, str method)
Callback returning the deprecated arguments of method/function.
Args:
    method (str): name of function/method checked for deprecated arguments
Returns:
    collections.abc.Iterable in form:
        ((POSITION1, PARAM1), (POSITION2: PARAM2) ...)
    where
        * POSITIONX - position of deprecated argument PARAMX in function definition.
          If argument is keyword-only, POSITIONX should be None.
        * PARAMX - name of the deprecated argument.
    E.g. suppose function:
    .. code-block:: python
        def bar(arg1, arg2, arg3, arg4, arg5='spam')
    with deprecated arguments `arg2` and `arg4`. `deprecated_arguments` should return:
    .. code-block:: python
        ((1, 'arg2'), (3, 'arg4'))
Reimplemented from pylint.checkers.deprecated.DeprecatedMixin.
Definition at line 961 of file stdlib.py.
    def deprecated_arguments(self, method: str) -> tuple[tuple[int | None, str], ...]:
        return self._deprecated_arguments.get(method, ())
References _deprecated_arguments.
deprecated_attributes()
Iterable[str] pylint.checkers.stdlib.StdlibChecker.deprecated_attributes (self)
Callback returning the deprecated attributes.
Reimplemented from pylint.checkers.deprecated.DeprecatedMixin.
Definition at line 970 of file stdlib.py.
    def deprecated_attributes(self) -> Iterable[str]:
        return self._deprecated_attributes
References _deprecated_attributes.
deprecated_classes()
Iterable[str] pylint.checkers.stdlib.StdlibChecker.deprecated_classes (self, str module)
Callback returning the deprecated classes of module.
Args:
    module (str): name of module checked for deprecated classes
Returns:
    collections.abc.Container of deprecated class names.
Reimplemented from pylint.checkers.deprecated.DeprecatedMixin.
Definition at line 964 of file stdlib.py.
    def deprecated_classes(self, module: str) -> Iterable[str]:
        return self._deprecated_classes.get(module, ())
References _deprecated_classes.
deprecated_decorators()
Iterable[str] pylint.checkers.stdlib.StdlibChecker.deprecated_decorators (self)
Callback returning the deprecated decorators.
Returns:
    collections.abc.Container of deprecated decorator names.
Reimplemented from pylint.checkers.deprecated.DeprecatedMixin.
Definition at line 967 of file stdlib.py.
    def deprecated_decorators(self) -> Iterable[str]:
        return self._deprecated_decorators
References _deprecated_decorators.
deprecated_methods()
set[str] pylint.checkers.stdlib.StdlibChecker.deprecated_methods (self)
Callback returning the deprecated methods/functions.
Returns:
    collections.abc.Container of deprecated function/method names.
Reimplemented from pylint.checkers.deprecated.DeprecatedMixin.
Definition at line 958 of file stdlib.py.
    def deprecated_methods(self) -> set[str]:
        return self._deprecated_methods
References _deprecated_methods.
visit_boolop()
None pylint.checkers.stdlib.StdlibChecker.visit_boolop (self, nodes.BoolOp node)
Definition at line 711 of file stdlib.py.
    def visit_boolop(self, node: nodes.BoolOp) -> None:
        for value in node.values:
            self._check_datetime(value)
References _check_datetime().
visit_call()
None pylint.checkers.stdlib.StdlibChecker.visit_call (self, nodes.Call node)
Visit a Call node.
Reimplemented from pylint.checkers.deprecated.DeprecatedMixin.
Definition at line 664 of file stdlib.py.
    def visit_call(self, node: nodes.Call) -> None:
        """Visit a Call node."""
        self.check_deprecated_class_in_call(node)
        for inferred in utils.infer_all(node.func):
            if isinstance(inferred, util.UninferableBase):
                continue
            if inferred.root().name in OPEN_MODULE:
                open_func_name: str | None = None
                if isinstance(node.func, nodes.Name):
                    open_func_name = node.func.name
                if isinstance(node.func, nodes.Attribute):
                    open_func_name = node.func.attrname
                if open_func_name in OPEN_FILES_FUNCS:
                    self._check_open_call(node, inferred.root().name, open_func_name)
            elif inferred.root().name == UNITTEST_CASE:
                self._check_redundant_assert(node, inferred)
            elif isinstance(inferred, nodes.ClassDef):
                if inferred.qname() == THREADING_THREAD:
                    self._check_bad_thread_instantiation(node)
                elif inferred.qname() == SUBPROCESS_POPEN:
                    self._check_for_preexec_fn_in_popen(node)
            elif isinstance(inferred, nodes.FunctionDef):
                name = inferred.qname()
                if name == COPY_COPY:
                    self._check_shallow_copy_environ(node)
                elif name in ENV_GETTERS:
                    self._check_env_function(node, inferred)
                elif name == SUBPROCESS_RUN:
                    self._check_for_check_kw_in_run(node)
                elif name in DEBUG_BREAKPOINTS:
                    self.add_message("forgotten-debug-statement", node=node)
            self.check_deprecated_method(node, inferred)
References _check_bad_thread_instantiation(), _check_env_function(), _check_for_check_kw_in_run(), _check_for_preexec_fn_in_popen(), _check_open_call(), _check_redundant_assert(), _check_shallow_copy_environ(), pylint.checkers.base_checker.BaseChecker.add_message(), pylint.checkers.deprecated.DeprecatedMixin.check_deprecated_class_in_call(), and pylint.checkers.deprecated.DeprecatedMixin.check_deprecated_method().
visit_functiondef()
None pylint.checkers.stdlib.StdlibChecker.visit_functiondef (self, nodes.FunctionDef node)
Definition at line 720 of file stdlib.py.
    def visit_functiondef(self, node: nodes.FunctionDef) -> None:
        if node.decorators:
            if isinstance(node.parent, nodes.ClassDef):
                self._check_lru_cache_decorators(node)
            self._check_dispatch_decorators(node)
References _check_dispatch_decorators(), and _check_lru_cache_decorators().
Referenced by pylint.pyreverse.inspector.Linker.visit_assignname().
visit_if()
None pylint.checkers.stdlib.StdlibChecker.visit_if (self, nodes.If node)
Definition at line 703 of file stdlib.py.
    def visit_if(self, node: nodes.If) -> None:
        self._check_datetime(node.test)
References _check_datetime().
visit_ifexp()
None pylint.checkers.stdlib.StdlibChecker.visit_ifexp (self, nodes.IfExp node)
Definition at line 707 of file stdlib.py.
    def visit_ifexp(self, node: nodes.IfExp) -> None:
        self._check_datetime(node.test)
References _check_datetime().
visit_unaryop()
None pylint.checkers.stdlib.StdlibChecker.visit_unaryop (self, nodes.UnaryOp node)
Definition at line 698 of file stdlib.py.
    def visit_unaryop(self, node: nodes.UnaryOp) -> None:
        if node.op == "not":
            self._check_datetime(node.operand)
References _check_datetime().
Member Data Documentation
_deprecated_arguments
dict pylint.checkers.stdlib.StdlibChecker._deprecated_arguments = {} protected
Definition at line 585 of file stdlib.py.
Referenced by deprecated_arguments().
_deprecated_attributes
set[str] pylint.checkers.stdlib.StdlibChecker._deprecated_attributes = set() protected
Definition at line 588 of file stdlib.py.
Referenced by deprecated_attributes().
_deprecated_classes
dict pylint.checkers.stdlib.StdlibChecker._deprecated_classes = {} protected
Definition at line 586 of file stdlib.py.
Referenced by deprecated_classes().
_deprecated_decorators
set[str] pylint.checkers.stdlib.StdlibChecker._deprecated_decorators = set() protected
Definition at line 587 of file stdlib.py.
Referenced by deprecated_decorators().
_deprecated_methods
set[str] pylint.checkers.stdlib.StdlibChecker._deprecated_methods = set() protected
Definition at line 584 of file stdlib.py.
Referenced by deprecated_methods().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pylint/checkers/stdlib.py