Read&Watch: pip._internal.index.package_finder.LinkType Class Reference
pip._internal.index.package_finder.LinkType Class Reference
Static Public Attributes
candidate = enum.auto()
different_project = enum.auto()
yanked = enum.auto()
format_unsupported = enum.auto()
format_invalid = enum.auto()
platform_mismatch = enum.auto()
requires_python_mismatch = enum.auto()
Detailed Description
Definition at line 99 of file package_finder.py.
Member Data Documentation
candidate
pip._internal.index.package_finder.LinkType.candidate = enum.auto() static
Definition at line 100 of file package_finder.py.
Referenced by pip._internal.resolution.resolvelib.requirements.ExplicitRequirement.__eq__(), pip._internal.resolution.resolvelib.requirements.ExplicitRequirement.__hash__(), pip._internal.resolution.resolvelib.requirements.ExplicitRequirement.__str__(), pip._vendor.resolvelib.resolvers.InconsistentCandidate.__str__(), pip._internal.resolution.resolvelib.requirements.ExplicitRequirement.format_for_error(), pip._internal.resolution.resolvelib.requirements.ExplicitRequirement.get_candidate_lookup(), pip._internal.resolution.resolvelib.requirements.ExplicitRequirement.is_satisfied_by(), pip._internal.resolution.resolvelib.requirements.ExplicitRequirement.name(), and pip._internal.resolution.resolvelib.requirements.ExplicitRequirement.project_name().
different_project
pip._internal.index.package_finder.LinkType.different_project = enum.auto() static
Definition at line 101 of file package_finder.py.
format_invalid
pip._internal.index.package_finder.LinkType.format_invalid = enum.auto() static
Definition at line 104 of file package_finder.py.
format_unsupported
pip._internal.index.package_finder.LinkType.format_unsupported = enum.auto() static
Definition at line 103 of file package_finder.py.
platform_mismatch
pip._internal.index.package_finder.LinkType.platform_mismatch = enum.auto() static
Definition at line 105 of file package_finder.py.
requires_python_mismatch
pip._internal.index.package_finder.LinkType.requires_python_mismatch = enum.auto() static
Definition at line 106 of file package_finder.py.
yanked
pip._internal.index.package_finder.LinkType.yanked = enum.auto() static
Definition at line 102 of file package_finder.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_internal/index/package_finder.py