Read&Watch: pylint.checkers.typecheck.IterableChecker Class Reference
pylint.checkers.typecheck.IterableChecker Class Reference
Public Member Functions
None visit_for (self, nodes.For node)
None visit_asyncfor (self, nodes.AsyncFor node)
None visit_yieldfrom (self, nodes.YieldFrom node)
None visit_call (self, nodes.Call node)
None visit_listcomp (self, nodes.ListComp node)
None visit_dictcomp (self, nodes.DictComp node)
None visit_setcomp (self, nodes.SetComp node)
None visit_generatorexp (self, nodes.GeneratorExp node)
Public Member Functions inherited from pylint.checkers.base_checker.BaseChecker
None __init__ (self, PyLinter linter)
bool __gt__ (self, Any other)
bool __eq__ (self, object other)
int __hash__ (self)
str __repr__ (self)
str __str__ (self)
str get_full_documentation (self, dict[str, MessageDefinitionTuple] msgs, Iterable[tuple[str, OptionDict, Any]] options, Sequence[tuple[str, str, ReportsCallable]] reports, str|None doc=None, str|None module=None, bool show_options=True)
None add_message (self, str msgid, int|None line=None, nodes.NodeNG|None node=None, Any args=None, Confidence|None confidence=None, int|None col_offset=None, int|None end_lineno=None, int|None end_col_offset=None)
None check_consistency (self)
MessageDefinition create_message_definition_from_tuple (self, str msgid, MessageDefinitionTuple msg_tuple)
list[MessageDefinition] messages (self)
None open (self)
None close (self)
Any get_map_data (self)
None reduce_map_data (self, PyLinter linter, list[Any] data)
Public Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
None __init__ (self, _ArgumentsManager arguments_manager)
Protected Member Functions
None _check_iterable (self, nodes.NodeNG node, bool check_async=False)
None _check_mapping (self, nodes.NodeNG node)
Protected Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
Any _option_value (self, str opt)
Iterator[ tuple[str, list[tuple[str, OptionDict, Any]]]|tuple[None, dict[str, list[tuple[str, OptionDict, Any]]]]] _options_by_section (self)
Iterator[tuple[str, OptionDict, Any]] _options_and_values (self, Options|None options=None)
Static Protected Member Functions
bool _is_asyncio_coroutine (nodes.NodeNG node)
Additional Inherited Members
Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
linter = linter
messages
Static Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
str name = ""
dict msgs = {}
tuple reports = ()
bool enabled = True
Static Public Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
tuple options = ()
dict option_groups_descs = {}
Protected Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
_arguments_manager = arguments_manager
Detailed Description
Checks for non-iterables used in an iterable context.
Contexts include:
- for-statement
- starargs in function call
- `yield from`-statement
- list, dict and set comprehensions
- generator expressions
Also checks for non-mappings in function call kwargs.
Definition at line 2227 of file typecheck.py.
Member Function Documentation
_check_iterable()
None pylint.checkers.typecheck.IterableChecker._check_iterable (self, nodes.NodeNG node, bool check_async = False) protected
Definition at line 2275 of file typecheck.py.
    def _check_iterable(self, node: nodes.NodeNG, check_async: bool = False) -> None:
        if is_inside_abstract_class(node):
            return
        inferred = safe_infer(node)
        if not inferred or is_comprehension(inferred):
            return
        if not is_iterable(inferred, check_async=check_async):
            self.add_message("not-an-iterable", args=node.as_string(), node=node)
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_asyncfor(), visit_call(), visit_dictcomp(), visit_for(), visit_generatorexp(), visit_listcomp(), visit_setcomp(), and visit_yieldfrom().
_check_mapping()
None pylint.checkers.typecheck.IterableChecker._check_mapping (self, nodes.NodeNG node) protected
Definition at line 2284 of file typecheck.py.
    def _check_mapping(self, node: nodes.NodeNG) -> None:
        if is_inside_abstract_class(node):
            return
        if isinstance(node, nodes.DictComp):
            return
        inferred = safe_infer(node)
        if inferred is None or isinstance(inferred, util.UninferableBase):
            return
        if not is_mapping(inferred):
            self.add_message("not-a-mapping", args=node.as_string(), node=node)
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_call().
_is_asyncio_coroutine()
bool pylint.checkers.typecheck.IterableChecker._is_asyncio_coroutine (nodes.NodeNG node) static protected
Definition at line 2257 of file typecheck.py.
    def _is_asyncio_coroutine(node: nodes.NodeNG) -> bool:
        if not isinstance(node, nodes.Call):
            return False
        inferred_func = safe_infer(node.func)
        if not isinstance(inferred_func, nodes.FunctionDef):
            return False
        if not inferred_func.decorators:
            return False
        for decorator in inferred_func.decorators.nodes:
            inferred_decorator = safe_infer(decorator)
            if not isinstance(inferred_decorator, nodes.FunctionDef):
                continue
            if inferred_decorator.qname() != ASYNCIO_COROUTINE:
                continue
            return True
        return False
Referenced by visit_yieldfrom().
visit_asyncfor()
None pylint.checkers.typecheck.IterableChecker.visit_asyncfor (self, nodes.AsyncFor node)
Definition at line 2300 of file typecheck.py.
    def visit_asyncfor(self, node: nodes.AsyncFor) -> None:
        self._check_iterable(node.iter, check_async=True)
References _check_iterable().
visit_call()
None pylint.checkers.typecheck.IterableChecker.visit_call (self, nodes.Call node)
Definition at line 2310 of file typecheck.py.
    def visit_call(self, node: nodes.Call) -> None:
        for stararg in node.starargs:
            self._check_iterable(stararg.value)
        for kwarg in node.kwargs:
            self._check_mapping(kwarg.value)
References _check_iterable(), and _check_mapping().
visit_dictcomp()
None pylint.checkers.typecheck.IterableChecker.visit_dictcomp (self, nodes.DictComp node)
Definition at line 2322 of file typecheck.py.
    def visit_dictcomp(self, node: nodes.DictComp) -> None:
        for gen in node.generators:
            self._check_iterable(gen.iter, check_async=gen.is_async)
References _check_iterable().
visit_for()
None pylint.checkers.typecheck.IterableChecker.visit_for (self, nodes.For node)
Definition at line 2296 of file typecheck.py.
    def visit_for(self, node: nodes.For) -> None:
        self._check_iterable(node.iter)
References _check_iterable().
visit_generatorexp()
None pylint.checkers.typecheck.IterableChecker.visit_generatorexp (self, nodes.GeneratorExp node)
Definition at line 2332 of file typecheck.py.
    def visit_generatorexp(self, node: nodes.GeneratorExp) -> None:
        for gen in node.generators:
            self._check_iterable(gen.iter, check_async=gen.is_async)
References _check_iterable().
visit_listcomp()
None pylint.checkers.typecheck.IterableChecker.visit_listcomp (self, nodes.ListComp node)
Definition at line 2317 of file typecheck.py.
    def visit_listcomp(self, node: nodes.ListComp) -> None:
        for gen in node.generators:
            self._check_iterable(gen.iter, check_async=gen.is_async)
References _check_iterable().
visit_setcomp()
None pylint.checkers.typecheck.IterableChecker.visit_setcomp (self, nodes.SetComp node)
Definition at line 2327 of file typecheck.py.
    def visit_setcomp(self, node: nodes.SetComp) -> None:
        for gen in node.generators:
            self._check_iterable(gen.iter, check_async=gen.is_async)
References _check_iterable().
visit_yieldfrom()
None pylint.checkers.typecheck.IterableChecker.visit_yieldfrom (self, nodes.YieldFrom node)
Definition at line 2304 of file typecheck.py.
    def visit_yieldfrom(self, node: nodes.YieldFrom) -> None:
        if self._is_asyncio_coroutine(node.value):
            return
        self._check_iterable(node.value)
References _check_iterable(), and _is_asyncio_coroutine().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pylint/checkers/typecheck.py