Read&Watch: pip._vendor.distlib.version.LegacyMatcher Class Reference
pip._vendor.distlib.version.LegacyMatcher Class Reference
Static Public Attributes
numeric_re = re.compile(r'^(\d+(\.\d+)*)')
Static Public Attributes inherited from pip._vendor.distlib.version.Matcher
version_class = None
Protected Member Functions
_match_compatible (self, version, constraint, prefix)
Protected Member Functions inherited from pip._vendor.distlib.version.Matcher
_check_compatible (self, other)
Additional Inherited Members
Public Member Functions inherited from pip._vendor.distlib.version.Matcher
parse_requirement (self, s)
__init__ (self, s)
match (self, version)
exact_version (self)
__eq__ (self, other)
__ne__ (self, other)
__hash__ (self)
__repr__ (self)
__str__ (self)
Public Attributes inherited from pip._vendor.distlib.version.Matcher
name = r.name
key = self.name.lower()
Protected Attributes inherited from pip._vendor.distlib.version.Matcher
_string = s.strip()
_parts = tuple(clist)
Static Protected Attributes inherited from pip._vendor.distlib.version.Matcher
dict _operators
Detailed Description
Definition at line 628 of file version.py.
Member Function Documentation
_match_compatible()
pip._vendor.distlib.version.LegacyMatcher._match_compatible (self, version, constraint, prefix) protected
Definition at line 636 of file version.py.
    def _match_compatible(self, version, constraint, prefix):
        if version < constraint:
            return False
        m = self.numeric_re.match(str(constraint))
        if not m:
            logger.warning('Cannot compute compatible match for version %s '
                           ' and constraint %s', version, constraint)
            return True
        s = m.groups()[0]
        if '.' in s:
            s = s.rsplit('.', 1)[0]
        return _match_prefix(version, s)
#
#   Semantic versioning
#
References pip._vendor.distlib.version._match_prefix(), pip._vendor.distlib.version.Matcher.match(), and numeric_re.
Member Data Documentation
numeric_re
pip._vendor.distlib.version.LegacyMatcher.numeric_re = re.compile(r'^(\d+(\.\d+)*)') static
Definition at line 634 of file version.py.
Referenced by _match_compatible().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/distlib/version.py