Read&Watch: django.contrib.auth.password_validation.NumericPasswordValidator Class Reference
django.contrib.auth.password_validation.NumericPasswordValidator Class Reference
Public Member Functions
validate (self, password, user=None)
get_help_text (self)
Detailed Description
Validate that the password is not entirely numeric.
Definition at line 253 of file password_validation.py.
Member Function Documentation
get_help_text()
django.contrib.auth.password_validation.NumericPasswordValidator.get_help_text (self)
Definition at line 265 of file password_validation.py.
    def get_help_text(self):
        return _("Your password can’t be entirely numeric.")
validate()
django.contrib.auth.password_validation.NumericPasswordValidator.validate (self, password, user = None)
Definition at line 258 of file password_validation.py.
    def validate(self, password, user=None):
        if password.isdigit():
            raise ValidationError(
                _("This password is entirely numeric."),
                code="password_entirely_numeric",
            )
Referenced by django.db.models.fields.Field.clean(), django.forms.fields.Field.clean(), and pip._vendor.distlib.metadata.Metadata.write().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/auth/password_validation.py