Read&Watch: pip._vendor.platformdirs.macos.MacOS Class Reference
pip._vendor.platformdirs.macos.MacOS Class Reference
Public Member Functions
str user_data_dir (self)
str site_data_dir (self)
str user_config_dir (self)
str site_config_dir (self)
str user_cache_dir (self)
str site_cache_dir (self)
str user_state_dir (self)
str user_log_dir (self)
str user_documents_dir (self)
str user_downloads_dir (self)
str user_pictures_dir (self)
str user_videos_dir (self)
str user_music_dir (self)
str user_desktop_dir (self)
str user_runtime_dir (self)
str site_runtime_dir (self)
Public Member Functions inherited from pip._vendor.platformdirs.api.PlatformDirsABC
None __init__ (self, str|None appname=None, str|None|Literal[False] appauthor=None, str|None version=None, bool roaming=False, bool multipath=False, bool opinion=True, bool ensure_exists=False)
Path user_data_path (self)
Path site_data_path (self)
Path user_config_path (self)
Path site_config_path (self)
Path user_cache_path (self)
Path site_cache_path (self)
Path user_state_path (self)
Path user_log_path (self)
Path user_documents_path (self)
Path user_downloads_path (self)
Path user_pictures_path (self)
Path user_videos_path (self)
Path user_music_path (self)
Path user_desktop_path (self)
Path user_runtime_path (self)
Path site_runtime_path (self)
Iterator[str] iter_config_dirs (self)
Iterator[str] iter_data_dirs (self)
Iterator[str] iter_cache_dirs (self)
Iterator[str] iter_runtime_dirs (self)
Iterator[Path] iter_config_paths (self)
Iterator[Path] iter_data_paths (self)
Iterator[Path] iter_cache_paths (self)
Iterator[Path] iter_runtime_paths (self)
Additional Inherited Members
Public Attributes inherited from pip._vendor.platformdirs.api.PlatformDirsABC
appname = appname
appauthor = appauthor
version = version
roaming = roaming
multipath = multipath
opinion = opinion
ensure_exists = ensure_exists
Protected Member Functions inherited from pip._vendor.platformdirs.api.PlatformDirsABC
str _append_app_name_and_version (self, *str base)
None _optionally_create_directory (self, str path)
Detailed Description
Platform directories for the macOS operating system.
Follows the guidance from
`Apple documentation <https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/MacOSXDirectories/MacOSXDirectories.html>`_.
Makes use of the `appname <platformdirs.api.PlatformDirsABC.appname>`,
`version <platformdirs.api.PlatformDirsABC.version>`,
`ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
Definition at line 11 of file macos.py.
Member Function Documentation
site_cache_dir()
str pip._vendor.platformdirs.macos.MacOS.site_cache_dir (self)
:return: cache directory shared by users, e.g. ``/Library/Caches/$appname/$version``.
  If we're using a Python binary managed by `Homebrew <https://brew.sh>`_, the directory
  will be under the Homebrew prefix, e.g. ``/opt/homebrew/var/cache/$appname/$version``.
  If `multipath <platformdirs.api.PlatformDirsABC.multipath>` is enabled, and we're in Homebrew,
  the response is a multi-path string separated by ":", e.g.
  ``/opt/homebrew/var/cache/$appname/$version:/Library/Caches/$appname/$version``
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 61 of file macos.py.
    def site_cache_dir(self) -> str:
        """
        :return: cache directory shared by users, e.g. ``/Library/Caches/$appname/$version``.
          If we're using a Python binary managed by `Homebrew <https://brew.sh>`_, the directory
          will be under the Homebrew prefix, e.g. ``/opt/homebrew/var/cache/$appname/$version``.
          If `multipath <platformdirs.api.PlatformDirsABC.multipath>` is enabled, and we're in Homebrew,
          the response is a multi-path string separated by ":", e.g.
          ``/opt/homebrew/var/cache/$appname/$version:/Library/Caches/$appname/$version``
        """
        is_homebrew = sys.prefix.startswith("/opt/homebrew")
        path_list = [self._append_app_name_and_version("/opt/homebrew/var/cache")] if is_homebrew else []
        path_list.append(self._append_app_name_and_version("/Library/Caches"))
        if self.multipath:
            return os.pathsep.join(path_list)
        return path_list[0]
References pip._vendor.platformdirs.api.PlatformDirsABC._append_app_name_and_version(), and pip._vendor.platformdirs.api.PlatformDirsABC.multipath.
site_config_dir()
str pip._vendor.platformdirs.macos.MacOS.site_config_dir (self)
:return: config directory shared by the users, same as `site_data_dir`
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 51 of file macos.py.
    def site_config_dir(self) -> str:
        """:return: config directory shared by the users, same as `site_data_dir`"""
        return self.site_data_dir
References pip._vendor.platformdirs.api.PlatformDirsABC.site_data_dir.
site_data_dir()
str pip._vendor.platformdirs.macos.MacOS.site_data_dir (self)
:return: data directory shared by users, e.g. ``/Library/Application Support/$appname/$version``.
  If we're using a Python binary managed by `Homebrew <https://brew.sh>`_, the directory
  will be under the Homebrew prefix, e.g. ``/opt/homebrew/share/$appname/$version``.
  If `multipath <platformdirs.api.PlatformDirsABC.multipath>` is enabled, and we're in Homebrew,
  the response is a multi-path string separated by ":", e.g.
  ``/opt/homebrew/share/$appname/$version:/Library/Application Support/$appname/$version``
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 29 of file macos.py.
    def site_data_dir(self) -> str:
        """
        :return: data directory shared by users, e.g. ``/Library/Application Support/$appname/$version``.
          If we're using a Python binary managed by `Homebrew <https://brew.sh>`_, the directory
          will be under the Homebrew prefix, e.g. ``/opt/homebrew/share/$appname/$version``.
          If `multipath <platformdirs.api.PlatformDirsABC.multipath>` is enabled, and we're in Homebrew,
          the response is a multi-path string separated by ":", e.g.
          ``/opt/homebrew/share/$appname/$version:/Library/Application Support/$appname/$version``
        """
        is_homebrew = sys.prefix.startswith("/opt/homebrew")
        path_list = [self._append_app_name_and_version("/opt/homebrew/share")] if is_homebrew else []
        path_list.append(self._append_app_name_and_version("/Library/Application Support"))
        if self.multipath:
            return os.pathsep.join(path_list)
        return path_list[0]
References pip._vendor.platformdirs.api.PlatformDirsABC._append_app_name_and_version().
site_runtime_dir()
str pip._vendor.platformdirs.macos.MacOS.site_runtime_dir (self)
:return: runtime directory shared by users, same as `user_runtime_dir`
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 123 of file macos.py.
    def site_runtime_dir(self) -> str:
        """:return: runtime directory shared by users, same as `user_runtime_dir`"""
        return self.user_runtime_dir
References pip._vendor.platformdirs.api.PlatformDirsABC.user_runtime_dir.
user_cache_dir()
str pip._vendor.platformdirs.macos.MacOS.user_cache_dir (self)
:return: cache directory tied to the user, e.g. ``~/Library/Caches/$appname/$version``
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 56 of file macos.py.
    def user_cache_dir(self) -> str:
        """:return: cache directory tied to the user, e.g. ``~/Library/Caches/$appname/$version``"""
        return self._append_app_name_and_version(os.path.expanduser("~/Library/Caches"))  # noqa: PTH111
References pip._vendor.platformdirs.api.PlatformDirsABC._append_app_name_and_version().
user_config_dir()
str pip._vendor.platformdirs.macos.MacOS.user_config_dir (self)
:return: config directory tied to the user, same as `user_data_dir`
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 46 of file macos.py.
    def user_config_dir(self) -> str:
        """:return: config directory tied to the user, same as `user_data_dir`"""
        return self.user_data_dir
References pip._vendor.platformdirs.api.PlatformDirsABC.user_data_dir.
user_data_dir()
str pip._vendor.platformdirs.macos.MacOS.user_data_dir (self)
:return: data directory tied to the user, e.g. ``~/Library/Application Support/$appname/$version``
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 24 of file macos.py.
    def user_data_dir(self) -> str:
        """:return: data directory tied to the user, e.g. ``~/Library/Application Support/$appname/$version``"""
        return self._append_app_name_and_version(os.path.expanduser("~/Library/Application Support"))  # noqa: PTH111
References pip._vendor.platformdirs.api.PlatformDirsABC._append_app_name_and_version().
user_desktop_dir()
str pip._vendor.platformdirs.macos.MacOS.user_desktop_dir (self)
:return: desktop directory tied to the user, e.g. ``~/Desktop``
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 113 of file macos.py.
    def user_desktop_dir(self) -> str:
        """:return: desktop directory tied to the user, e.g. ``~/Desktop``"""
        return os.path.expanduser("~/Desktop")  # noqa: PTH111
user_documents_dir()
str pip._vendor.platformdirs.macos.MacOS.user_documents_dir (self)
:return: documents directory tied to the user, e.g. ``~/Documents``
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 88 of file macos.py.
    def user_documents_dir(self) -> str:
        """:return: documents directory tied to the user, e.g. ``~/Documents``"""
        return os.path.expanduser("~/Documents")  # noqa: PTH111
user_downloads_dir()
str pip._vendor.platformdirs.macos.MacOS.user_downloads_dir (self)
:return: downloads directory tied to the user, e.g. ``~/Downloads``
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 93 of file macos.py.
    def user_downloads_dir(self) -> str:
        """:return: downloads directory tied to the user, e.g. ``~/Downloads``"""
        return os.path.expanduser("~/Downloads")  # noqa: PTH111
user_log_dir()
str pip._vendor.platformdirs.macos.MacOS.user_log_dir (self)
:return: log directory tied to the user, e.g. ``~/Library/Logs/$appname/$version``
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 83 of file macos.py.
    def user_log_dir(self) -> str:
        """:return: log directory tied to the user, e.g. ``~/Library/Logs/$appname/$version``"""
        return self._append_app_name_and_version(os.path.expanduser("~/Library/Logs"))  # noqa: PTH111
References pip._vendor.platformdirs.api.PlatformDirsABC._append_app_name_and_version().
user_music_dir()
str pip._vendor.platformdirs.macos.MacOS.user_music_dir (self)
:return: music directory tied to the user, e.g. ``~/Music``
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 108 of file macos.py.
    def user_music_dir(self) -> str:
        """:return: music directory tied to the user, e.g. ``~/Music``"""
        return os.path.expanduser("~/Music")  # noqa: PTH111
user_pictures_dir()
str pip._vendor.platformdirs.macos.MacOS.user_pictures_dir (self)
:return: pictures directory tied to the user, e.g. ``~/Pictures``
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 98 of file macos.py.
    def user_pictures_dir(self) -> str:
        """:return: pictures directory tied to the user, e.g. ``~/Pictures``"""
        return os.path.expanduser("~/Pictures")  # noqa: PTH111
user_runtime_dir()
str pip._vendor.platformdirs.macos.MacOS.user_runtime_dir (self)
:return: runtime directory tied to the user, e.g. ``~/Library/Caches/TemporaryItems/$appname/$version``
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 118 of file macos.py.
    def user_runtime_dir(self) -> str:
        """:return: runtime directory tied to the user, e.g. ``~/Library/Caches/TemporaryItems/$appname/$version``"""
        return self._append_app_name_and_version(os.path.expanduser("~/Library/Caches/TemporaryItems"))  # noqa: PTH111
References pip._vendor.platformdirs.api.PlatformDirsABC._append_app_name_and_version().
user_state_dir()
str pip._vendor.platformdirs.macos.MacOS.user_state_dir (self)
:return: state directory tied to the user, same as `user_data_dir`
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 78 of file macos.py.
    def user_state_dir(self) -> str:
        """:return: state directory tied to the user, same as `user_data_dir`"""
        return self.user_data_dir
References pip._vendor.platformdirs.api.PlatformDirsABC.user_data_dir.
user_videos_dir()
str pip._vendor.platformdirs.macos.MacOS.user_videos_dir (self)
:return: videos directory tied to the user, e.g. ``~/Movies``
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 103 of file macos.py.
    def user_videos_dir(self) -> str:
        """:return: videos directory tied to the user, e.g. ``~/Movies``"""
        return os.path.expanduser("~/Movies")  # noqa: PTH111
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/platformdirs/macos.py