Read&Watch: django.db.models.fields.json.KeyTransformTextLookupMixin Class Reference
django.db.models.fields.json.KeyTransformTextLookupMixin Class Reference
Public Member Functions
__init__ (self, key_transform, *args, **kwargs)
Detailed Description
Mixin for combining with a lookup expecting a text lhs from a JSONField
key lookup. On PostgreSQL, make use of the ->> operator instead of casting
key values to text and performing the lookup on the resulting
representation.
Definition at line 422 of file json.py.
Constructor & Destructor Documentation
__init__()
django.db.models.fields.json.KeyTransformTextLookupMixin.__init__ (self, key_transform, * args, ** kwargs)
Definition at line 430 of file json.py.
    def __init__(self, key_transform, *args, **kwargs):
        if not isinstance(key_transform, KeyTransform):
            raise TypeError(
                "Transform should be an instance of KeyTransform in order to "
                "use this lookup."
            )
        key_text_transform = KeyTextTransform(
            key_transform.key_name,
            *key_transform.source_expressions,
            **key_transform.extra,
        )
        super().__init__(key_text_transform, *args, **kwargs)
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/db/models/fields/json.py