Read&Watch: pip._vendor.rich.progress.DownloadColumn Class Reference
pip._vendor.rich.progress.DownloadColumn Class Reference
Public Member Functions
None __init__ (self, bool binary_units=False, Optional[Column] table_column=None)
Text render (self, "Task" task)
Public Member Functions inherited from pip._vendor.rich.progress.ProgressColumn
None __init__ (self, Optional[Column] table_column=None)
Column get_table_column (self)
RenderableType __call__ (self, "Task" task)
Public Attributes
binary_units = binary_units
Additional Inherited Members
Static Public Attributes inherited from pip._vendor.rich.progress.ProgressColumn
Optional max_refresh = None
Protected Attributes inherited from pip._vendor.rich.progress.ProgressColumn
_table_column = table_column
dict _renderable_cache = {}
Optional[float] _update_time = None
Detailed Description
Renders file size downloaded and total, e.g. '0.5/2.3 GB'.
Args:
    binary_units (bool, optional): Use binary units, KiB, MiB etc. Defaults to False.
Definition at line 853 of file progress.py.
Constructor & Destructor Documentation
__init__()
None pip._vendor.rich.progress.DownloadColumn.__init__ (self, bool binary_units = False, Optional[Column] table_column = None)
Definition at line 860 of file progress.py.
    ) -> None:
        self.binary_units = binary_units
        super().__init__(table_column=table_column)
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
render()
Text pip._vendor.rich.progress.DownloadColumn.render (self, "Task" task)
Calculate common unit for completed and total.
Reimplemented from pip._vendor.rich.progress.ProgressColumn.
Definition at line 866 of file progress.py.
    def render(self, task: "Task") -> Text:
        """Calculate common unit for completed and total."""
        completed = int(task.completed)
        unit_and_suffix_calculation_base = (
            int(task.total) if task.total is not None else completed
        )
        if self.binary_units:
            unit, suffix = filesize.pick_unit_and_suffix(
                unit_and_suffix_calculation_base,
                ["bytes", "KiB", "MiB", "GiB", "TiB", "PiB", "EiB", "ZiB", "YiB"],
                1024,
            )
        else:
            unit, suffix = filesize.pick_unit_and_suffix(
                unit_and_suffix_calculation_base,
                ["bytes", "kB", "MB", "GB", "TB", "PB", "EB", "ZB", "YB"],
                1000,
            )
        precision = 0 if unit == 1 else 1
        completed_ratio = completed / unit
        completed_str = f"{completed_ratio:,.{precision}f}"
        if task.total is not None:
            total = int(task.total)
            total_ratio = total / unit
            total_str = f"{total_ratio:,.{precision}f}"
        else:
            total_str = "?"
        download_status = f"{completed_str}/{total_str} {suffix}"
        download_text = Text(download_status, style="progress.download")
        return download_text
References binary_units.
Referenced by pip._vendor.rich.spinner.Spinner.__rich_console__(), and pip._vendor.rich.spinner.Spinner.__rich_measure__().
Member Data Documentation
binary_units
pip._vendor.rich.progress.DownloadColumn.binary_units = binary_units
Definition at line 863 of file progress.py.
Referenced by render().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/rich/progress.py