Read&Watch: PIL.IcnsImagePlugin.IcnsFile Class Reference
PIL.IcnsImagePlugin.IcnsFile Class Reference
Public Member Functions
None __init__ (self, IO[bytes] fobj)
list[tuple[int, int, int]] itersizes (self)
tuple[int, int, int] bestsize (self)
dict[str, Image.Image] dataforsize (self, tuple[int, int, int] size)
Image.Image getimage (self, tuple[int, int]|tuple[int, int, int]|None size=None)
Public Attributes
dict dct = {}
fobj = fobj
Static Public Attributes
dict SIZES
Detailed Description
Definition at line 150 of file IcnsImagePlugin.py.
Constructor & Destructor Documentation
__init__()
None PIL.IcnsImagePlugin.IcnsFile.__init__ (self, IO[bytes] fobj)
fobj is a file-like object as an icns resource
Definition at line 178 of file IcnsImagePlugin.py.
    def __init__(self, fobj: IO[bytes]) -> None:
        """
        fobj is a file-like object as an icns resource
        """
        # signature : (start, length)
        self.dct = {}
        self.fobj = fobj
        sig, filesize = nextheader(fobj)
        if not _accept(sig):
            msg = "not an icns file"
            raise SyntaxError(msg)
        i = HEADERSIZE
        while i < filesize:
            sig, blocksize = nextheader(fobj)
            if blocksize <= 0:
                msg = "invalid block header"
                raise SyntaxError(msg)
            i += HEADERSIZE
            blocksize -= HEADERSIZE
            self.dct[sig] = (i, blocksize)
            fobj.seek(blocksize, io.SEEK_CUR)
            i += blocksize
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
bestsize()
tuple[int, int, int] PIL.IcnsImagePlugin.IcnsFile.bestsize (self)
Definition at line 210 of file IcnsImagePlugin.py.
    def bestsize(self) -> tuple[int, int, int]:
        sizes = self.itersizes()
        if not sizes:
            msg = "No 32bit icon resources found"
            raise SyntaxError(msg)
        return max(sizes)
References itersizes().
Referenced by getimage().
dataforsize()
dict[str, Image.Image] PIL.IcnsImagePlugin.IcnsFile.dataforsize (self, tuple[int, int, int] size)
Get an icon resource as {channel: array}.  Note that
the arrays are bottom-up like windows bitmaps and will likely
need to be flipped or transposed in some way.
Definition at line 217 of file IcnsImagePlugin.py.
    def dataforsize(self, size: tuple[int, int, int]) -> dict[str, Image.Image]:
        """
        Get an icon resource as {channel: array}.  Note that
        the arrays are bottom-up like windows bitmaps and will likely
        need to be flipped or transposed in some way.
        """
        dct = {}
        for code, reader in self.SIZES[size]:
            desc = self.dct.get(code)
            if desc is not None:
                dct.update(reader(self.fobj, desc, size))
        return dct
References dct, fobj, and SIZES.
Referenced by getimage().
getimage()
Image.Image PIL.IcnsImagePlugin.IcnsFile.getimage (self, tuple[int, int] | tuple[int, int, int] | None size = None)
Definition at line 230 of file IcnsImagePlugin.py.
    ) -> Image.Image:
        if size is None:
            size = self.bestsize()
        elif len(size) == 2:
            size = (size[0], size[1], 1)
        channels = self.dataforsize(size)
        im = channels.get("RGBA")
        if im:
            return im
        im = channels["RGB"].copy()
        try:
            im.putalpha(channels["A"])
        except KeyError:
            pass
        return im
References bestsize(), and dataforsize().
itersizes()
list[tuple[int, int, int]] PIL.IcnsImagePlugin.IcnsFile.itersizes (self)
Definition at line 201 of file IcnsImagePlugin.py.
    def itersizes(self) -> list[tuple[int, int, int]]:
        sizes = []
        for size, fmts in self.SIZES.items():
            for fmt, reader in fmts:
                if fmt in self.dct:
                    sizes.append(size)
                    break
        return sizes
References dct, and SIZES.
Referenced by bestsize().
Member Data Documentation
dct
dict PIL.IcnsImagePlugin.IcnsFile.dct = {}
Definition at line 183 of file IcnsImagePlugin.py.
Referenced by dataforsize(), and itersizes().
fobj
PIL.IcnsImagePlugin.IcnsFile.fobj = fobj
Definition at line 184 of file IcnsImagePlugin.py.
Referenced by dataforsize().
SIZES
dict PIL.IcnsImagePlugin.IcnsFile.SIZES static
Initial value:
=  {
        (512, 512, 2): [(b"ic10", read_png_or_jpeg2000)],
        (512, 512, 1): [(b"ic09", read_png_or_jpeg2000)],
        (256, 256, 2): [(b"ic14", read_png_or_jpeg2000)],
        (256, 256, 1): [(b"ic08", read_png_or_jpeg2000)],
        (128, 128, 2): [(b"ic13", read_png_or_jpeg2000)],
        (128, 128, 1): [
            (b"ic07", read_png_or_jpeg2000),
            (b"it32", read_32t),
            (b"t8mk", read_mk),
        ],
        (64, 64, 1): [(b"icp6", read_png_or_jpeg2000)],
        (32, 32, 2): [(b"ic12", read_png_or_jpeg2000)],
        (48, 48, 1): [(b"ih32", read_32), (b"h8mk", read_mk)],
        (32, 32, 1): [
            (b"icp5", read_png_or_jpeg2000),
            (b"il32", read_32),
            (b"l8mk", read_mk),
        ],
        (16, 16, 2): [(b"ic11", read_png_or_jpeg2000)],
        (16, 16, 1): [
            (b"icp4", read_png_or_jpeg2000),
            (b"is32", read_32),
            (b"s8mk", read_mk),
        ],
    }
Definition at line 151 of file IcnsImagePlugin.py.
Referenced by dataforsize(), and itersizes().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/PIL/IcnsImagePlugin.py