Read&Watch: responses.CallList Class Reference
responses.CallList Class Reference
Public Member Functions
None __init__ (self)
Iterator[Call] __iter__ (self)
int __len__ (self)
Call __getitem__ (self, int idx)
List[Call] __getitem__ (self, "slice[int, int, Optional[int]]" idx)
Union[Call, List[Call]] __getitem__ (self, Union[int, slice] idx)
None add (self, "PreparedRequest" request, "_Body" response)
None add_call (self, Call call)
None reset (self)
Protected Attributes
list _calls = []
Detailed Description
Definition at line 237 of file __init__.py.
Constructor & Destructor Documentation
__init__()
None responses.CallList.__init__ (self)
Definition at line 238 of file __init__.py.
    def __init__(self) -> None:
        self._calls: List[Call] = []
Member Function Documentation
__getitem__() [1/3]
List[Call] responses.CallList.__getitem__ (self, "slice[int, int, Optional[int]]" idx)
Definition at line 252 of file __init__.py.
    def __getitem__(self, idx: "slice[int, int, Optional[int]]") -> List[Call]:
        ...
__getitem__() [2/3]
Call responses.CallList.__getitem__ (self, int idx)
Definition at line 248 of file __init__.py.
    def __getitem__(self, idx: int) -> Call:
        ...
__getitem__() [3/3]
Union[Call, List[Call]] responses.CallList.__getitem__ (self, Union[int, slice] idx)
Definition at line 255 of file __init__.py.
    def __getitem__(self, idx: Union[int, slice]) -> Union[Call, List[Call]]:
        return self._calls[idx]
References _calls.
__iter__()
Iterator[Call] responses.CallList.__iter__ (self)
Definition at line 241 of file __init__.py.
    def __iter__(self) -> Iterator[Call]:
        return iter(self._calls)
References _calls.
Referenced by django.db.models.query.BaseIterable._async_generator().
__len__()
int responses.CallList.__len__ (self)
Definition at line 244 of file __init__.py.
    def __len__(self) -> int:
        return len(self._calls)
References _calls.
add()
None responses.CallList.add (self, "PreparedRequest" request, "_Body" response)
Definition at line 258 of file __init__.py.
    def add(self, request: "PreparedRequest", response: "_Body") -> None:
        self._calls.append(Call(request, response))
References _calls.
Referenced by responses.RequestsMock._add_from_file(), urllib3._collections.HTTPHeaderDict.extend(), and responses.RequestsMock.upsert().
add_call()
None responses.CallList.add_call (self, Call call)
Definition at line 261 of file __init__.py.
    def add_call(self, call: Call) -> None:
        self._calls.append(call)
References _calls.
reset()
None responses.CallList.reset (self)
Definition at line 264 of file __init__.py.
    def reset(self) -> None:
        self._calls = []
References _calls.
Referenced by responses.RequestsMock.__exit__(), django.utils.html.MLStripper.__init__(), and pylint.extensions.mccabe.PathGraphingAstVisitor._subgraph().
Member Data Documentation
_calls
responses.CallList._calls = [] protected
Definition at line 239 of file __init__.py.
Referenced by __getitem__(), __iter__(), __len__(), responses.RequestsMock._on_request(), add(), add_call(), responses.BaseResponse.call_count(), responses.BaseResponse.calls(), responses.RequestsMock.calls(), reset(), and responses.RequestsMock.reset().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/responses/__init__.py