Read&Watch: apscheduler.triggers.cron.expressions.MonthRangeExpression Class Reference
apscheduler.triggers.cron.expressions.MonthRangeExpression Class Reference
Public Member Functions
__init__ (self, first, last=None)
__str__ (self)
__repr__ (self)
Public Member Functions inherited from apscheduler.triggers.cron.expressions.RangeExpression
__init__ (self, first, last=None, step=None)
validate_range (self, field_name)
get_next_value (self, date, field)
__eq__ (self, other)
__str__ (self)
__repr__ (self)
Public Member Functions inherited from apscheduler.triggers.cron.expressions.AllExpression
__init__ (self, step=None)
__eq__ (self, other)
__str__ (self)
__repr__ (self)
Additional Inherited Members
Public Attributes inherited from apscheduler.triggers.cron.expressions.RangeExpression
first = first
last = last
Public Attributes inherited from apscheduler.triggers.cron.expressions.AllExpression
int step = asint(step)
Static Public Attributes inherited from apscheduler.triggers.cron.expressions.AllExpression
value_re = re.compile(r"\*(?:/(?P<step>\d+))?$")
Detailed Description
Definition at line 159 of file expressions.py.
Constructor & Destructor Documentation
__init__()
apscheduler.triggers.cron.expressions.MonthRangeExpression.__init__ (self, first, last = None)
Definition at line 162 of file expressions.py.
    def __init__(self, first, last=None):
        try:
            first_num = MONTHS.index(first.lower()) + 1
        except ValueError:
            raise ValueError(f'Invalid month name "{first}"')
        if last:
            try:
                last_num = MONTHS.index(last.lower()) + 1
            except ValueError:
                raise ValueError(f'Invalid month name "{last}"')
        else:
            last_num = None
        super().__init__(first_num, last_num)
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Function Documentation
__repr__()
apscheduler.triggers.cron.expressions.MonthRangeExpression.__repr__ (self)
Definition at line 183 of file expressions.py.
    def __repr__(self):
        args = [f"'{MONTHS[self.first]}'"]
        if self.last != self.first and self.last is not None:
            args.append(f"'{MONTHS[self.last - 1]}'")
        return "{}({})".format(self.__class__.__name__, ", ".join(args))
References apscheduler.triggers.cron.expressions.AllExpression.__class__, apscheduler.triggers.cron.expressions.RangeExpression.first, and apscheduler.triggers.cron.expressions.RangeExpression.last.
__str__()
apscheduler.triggers.cron.expressions.MonthRangeExpression.__str__ (self)
Definition at line 178 of file expressions.py.
    def __str__(self):
        if self.last != self.first and self.last is not None:
            return f"{MONTHS[self.first - 1]}-{MONTHS[self.last - 1]}"
        return MONTHS[self.first - 1]
References apscheduler.triggers.cron.expressions.RangeExpression.first, and apscheduler.triggers.cron.expressions.RangeExpression.last.
Referenced by PIL.PdfParser.IndirectReference.__bytes__().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/apscheduler/triggers/cron/expressions.py