Read&Watch: django.contrib.gis.feeds.W3CGeoFeed Class Reference
django.contrib.gis.feeds.W3CGeoFeed Class Reference
Public Member Functions
rss_attributes (self)
add_item_elements (self, handler, item)
add_root_elements (self, handler)
Public Member Functions inherited from django.utils.feedgenerator.RssFeed
write (self, outfile, encoding)
write_items (self, handler)
endChannelElement (self, handler)
Public Member Functions inherited from django.utils.feedgenerator.SyndicationFeed
__init__ (self, title, link, description, language=None, author_email=None, author_name=None, author_link=None, subtitle=None, categories=None, feed_url=None, feed_copyright=None, feed_guid=None, ttl=None, **kwargs)
add_item (self, title, link, description, author_email=None, author_name=None, author_link=None, pubdate=None, comments=None, unique_id=None, unique_id_is_permalink=None, categories=(), item_copyright=None, ttl=None, updateddate=None, enclosures=None, **kwargs)
num_items (self)
root_attributes (self)
item_attributes (self, item)
writeString (self, encoding)
latest_post_date (self)
Public Member Functions inherited from django.contrib.gis.feeds.GeoFeedMixin
georss_coords (self, coords)
add_georss_point (self, handler, coords, w3c_geo=False)
add_georss_element (self, handler, item, w3c_geo=False)
Additional Inherited Members
Public Attributes inherited from django.utils.feedgenerator.SyndicationFeed
dict feed
list items = []
Static Public Attributes inherited from django.utils.feedgenerator.RssFeed
str content_type = "application/rss+xml; charset=utf-8"
Protected Attributes inherited from django.utils.feedgenerator.RssFeed
_version
Detailed Description
Definition at line 121 of file feeds.py.
Member Function Documentation
add_item_elements()
django.contrib.gis.feeds.W3CGeoFeed.add_item_elements (self, handler, item)
Add elements on each item (i.e. item/entry) element.
Reimplemented from django.utils.feedgenerator.Rss201rev2Feed.
Definition at line 127 of file feeds.py.
    def add_item_elements(self, handler, item):
        super().add_item_elements(handler, item)
        self.add_georss_element(handler, item, w3c_geo=True)
References django.contrib.gis.feeds.GeoFeedMixin.add_georss_element(), and add_item_elements().
Referenced by add_item_elements().
add_root_elements()
django.contrib.gis.feeds.W3CGeoFeed.add_root_elements (self, handler)
Add elements in the root (i.e. feed/channel) element. Called
from write().
Reimplemented from django.utils.feedgenerator.RssFeed.
Definition at line 131 of file feeds.py.
    def add_root_elements(self, handler):
        super().add_root_elements(handler)
        self.add_georss_element(handler, self.feed, w3c_geo=True)
# ### Feed subclass ###
References add_root_elements().
Referenced by add_root_elements(), django.utils.feedgenerator.Atom1Feed.write(), and django.utils.feedgenerator.RssFeed.write().
rss_attributes()
django.contrib.gis.feeds.W3CGeoFeed.rss_attributes (self)
Reimplemented from django.utils.feedgenerator.RssFeed.
Definition at line 122 of file feeds.py.
    def rss_attributes(self):
        attrs = super().rss_attributes()
        attrs["xmlns:geo"] = "http://www.w3.org/2003/01/geo/wgs84_pos#"
        return attrs
References rss_attributes().
Referenced by rss_attributes(), and django.utils.feedgenerator.RssFeed.write().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/gis/feeds.py