Read&Watch: pylint.extensions.redefined_loop_name.RedefinedLoopNameChecker Class Reference
pylint.extensions.redefined_loop_name.RedefinedLoopNameChecker Class Reference
Public Member Functions
None __init__ (self, PyLinter linter)
None visit_assignname (self, nodes.AssignName node)
None visit_for (self, nodes.For node)
None leave_for (self, nodes.For node)
Public Member Functions inherited from pylint.checkers.base_checker.BaseChecker
None __init__ (self, PyLinter linter)
bool __gt__ (self, Any other)
bool __eq__ (self, object other)
int __hash__ (self)
str __repr__ (self)
str __str__ (self)
str get_full_documentation (self, dict[str, MessageDefinitionTuple] msgs, Iterable[tuple[str, OptionDict, Any]] options, Sequence[tuple[str, str, ReportsCallable]] reports, str|None doc=None, str|None module=None, bool show_options=True)
None add_message (self, str msgid, int|None line=None, nodes.NodeNG|None node=None, Any args=None, Confidence|None confidence=None, int|None col_offset=None, int|None end_lineno=None, int|None end_col_offset=None)
None check_consistency (self)
MessageDefinition create_message_definition_from_tuple (self, str msgid, MessageDefinitionTuple msg_tuple)
list[MessageDefinition] messages (self)
None open (self)
None close (self)
Any get_map_data (self)
None reduce_map_data (self, PyLinter linter, list[Any] data)
Public Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
None __init__ (self, _ArgumentsManager arguments_manager)
Protected Attributes
list[ _loop_variables
Protected Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
_arguments_manager = arguments_manager
Additional Inherited Members
Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
linter = linter
messages
Static Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
str name = ""
dict msgs = {}
tuple reports = ()
bool enabled = True
Static Public Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
tuple options = ()
dict option_groups_descs = {}
Protected Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
Any _option_value (self, str opt)
Iterator[ tuple[str, list[tuple[str, OptionDict, Any]]]|tuple[None, dict[str, list[tuple[str, OptionDict, Any]]]]] _options_by_section (self)
Iterator[tuple[str, OptionDict, Any]] _options_and_values (self, Options|None options=None)
Detailed Description
Definition at line 17 of file redefined_loop_name.py.
Constructor & Destructor Documentation
__init__()
None pylint.extensions.redefined_loop_name.RedefinedLoopNameChecker.__init__ (self, PyLinter linter)
Definition at line 28 of file redefined_loop_name.py.
    def __init__(self, linter: PyLinter) -> None:
        super().__init__(linter)
        self._loop_variables: list[
            tuple[nodes.For, list[str], nodes.LocalsDictNodeNG]
        ] = []
References __init__().
Referenced by __init__().
Member Function Documentation
leave_for()
None pylint.extensions.redefined_loop_name.RedefinedLoopNameChecker.leave_for (self, nodes.For node)
Definition at line 83 of file redefined_loop_name.py.
    def leave_for(self, node: nodes.For) -> None:  # pylint: disable=unused-argument
        self._loop_variables.pop()
References _loop_variables.
visit_assignname()
None pylint.extensions.redefined_loop_name.RedefinedLoopNameChecker.visit_assignname (self, nodes.AssignName node)
Definition at line 35 of file redefined_loop_name.py.
    def visit_assignname(self, node: nodes.AssignName) -> None:
        assign_type = node.assign_type()
        if not isinstance(assign_type, (nodes.Assign, nodes.AugAssign)):
            return
        node_scope = node.scope()
        for outer_for, outer_variables, outer_for_scope in self._loop_variables:
            if node_scope is not outer_for_scope:
                continue
            if node.name in outer_variables and not utils.in_for_else_branch(
                outer_for, node
            ):
                self.add_message(
                    "redefined-loop-name",
                    args=(node.name, outer_for.fromlineno),
                    node=node,
                    confidence=HIGH,
                )
                break
References _loop_variables, and pylint.checkers.base_checker.BaseChecker.add_message().
visit_for()
None pylint.extensions.redefined_loop_name.RedefinedLoopNameChecker.visit_for (self, nodes.For node)
Definition at line 55 of file redefined_loop_name.py.
    def visit_for(self, node: nodes.For) -> None:
        assigned_to = [a.name for a in node.target.nodes_of_class(nodes.AssignName)]
        # Only check variables that are used
        assigned_to = [
            var
            for var in assigned_to
            if not self.linter.config.dummy_variables_rgx.match(var)
        ]
        node_scope = node.scope()
        for variable in assigned_to:
            for outer_for, outer_variables, outer_for_scope in self._loop_variables:
                if node_scope is not outer_for_scope:
                    continue
                if variable in outer_variables and not utils.in_for_else_branch(
                    outer_for, node
                ):
                    self.add_message(
                        "redefined-loop-name",
                        args=(variable, outer_for.fromlineno),
                        node=node,
                        confidence=HIGH,
                    )
                    break
        self._loop_variables.append((node, assigned_to, node.scope()))
References _loop_variables, pylint.checkers.base_checker.BaseChecker.add_message(), and pylint.checkers.base_checker.BaseChecker.linter.
Member Data Documentation
_loop_variables
list[ pylint.extensions.redefined_loop_name.RedefinedLoopNameChecker._loop_variables protected
Definition at line 30 of file redefined_loop_name.py.
Referenced by leave_for(), visit_assignname(), and visit_for().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pylint/extensions/redefined_loop_name.py