Read&Watch: django.contrib.messages.storage.cookie.MessageDecoder Class Reference
django.contrib.messages.storage.cookie.MessageDecoder Class Reference
Public Member Functions
process_messages (self, obj)
decode (self, s, **kwargs)
Detailed Description
Decode JSON that includes serialized ``Message`` instances.
Definition at line 29 of file cookie.py.
Member Function Documentation
decode()
django.contrib.messages.storage.cookie.MessageDecoder.decode (self, s, ** kwargs)
Definition at line 45 of file cookie.py.
    def decode(self, s, **kwargs):
        decoded = super().decode(s, **kwargs)
        return self.process_messages(decoded)
References decode(), and process_messages().
Referenced by django.contrib.sessions.backends.cached_db.SessionStore.aload(), django.contrib.sessions.backends.db.SessionStore.aload(), decode(), django.contrib.sessions.backends.cached_db.SessionStore.load(), django.contrib.sessions.backends.db.SessionStore.load(), and django.contrib.sessions.backends.file.SessionStore.load().
process_messages()
django.contrib.messages.storage.cookie.MessageDecoder.process_messages (self, obj)
Definition at line 34 of file cookie.py.
    def process_messages(self, obj):
        if isinstance(obj, list) and obj:
            if obj[0] == MessageEncoder.message_key:
                if obj[1]:
                    obj[3] = mark_safe(obj[3])
                return Message(*obj[2:])
            return [self.process_messages(item) for item in obj]
        if isinstance(obj, dict):
            return {key: self.process_messages(value) for key, value in obj.items()}
        return obj
References process_messages().
Referenced by decode(), and process_messages().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/messages/storage/cookie.py