Read&Watch: pip._vendor.typing_extensions._NamedTupleMeta Class Reference
pip._vendor.typing_extensions._NamedTupleMeta Class Reference
Public Member Functions
__new__ (cls, typename, bases, ns)
Detailed Description
Definition at line 3112 of file typing_extensions.py.
Member Function Documentation
__new__()
pip._vendor.typing_extensions._NamedTupleMeta.__new__ (cls, typename, bases, ns)
Definition at line 3113 of file typing_extensions.py.
        def __new__(cls, typename, bases, ns):
            assert _NamedTuple in bases
            for base in bases:
                if base is not _NamedTuple and base is not typing.Generic:
                    raise TypeError(
                        'can only inherit from a NamedTuple type and Generic')
            bases = tuple(tuple if base is _NamedTuple else base for base in bases)
            if "__annotations__" in ns:
                types = ns["__annotations__"]
            elif "__annotate__" in ns:
                # TODO: Use inspect.VALUE here, and make the annotations lazily evaluated
                types = ns["__annotate__"](1)
            else:
                types = {}
            default_names = []
            for field_name in types:
                if field_name in ns:
                    default_names.append(field_name)
                elif default_names:
                    raise TypeError(f"Non-default namedtuple field {field_name} "
                                    f"cannot follow default field"
                                    f"{'s' if len(default_names) > 1 else ''} "
                                    f"{', '.join(default_names)}")
            nm_tpl = _make_nmtuple(
                typename, types.items(),
                defaults=[ns[n] for n in default_names],
                module=ns['__module__']
            )
            nm_tpl.__bases__ = bases
            if typing.Generic in bases:
                if hasattr(typing, '_generic_class_getitem'):  # 3.12+
                    nm_tpl.__class_getitem__ = classmethod(typing._generic_class_getitem)
                else:
                    class_getitem = typing.Generic.__class_getitem__.__func__
                    nm_tpl.__class_getitem__ = classmethod(class_getitem)
            # update from user namespace without overriding special namedtuple attributes
            for key, val in ns.items():
                if key in _prohibited_namedtuple_fields:
                    raise AttributeError("Cannot overwrite NamedTuple attribute " + key)
                elif key not in _special_namedtuple_fields:
                    if key not in nm_tpl._fields:
                        setattr(nm_tpl, key, ns[key])
                    try:
                        set_name = type(val).__set_name__
                    except AttributeError:
                        pass
                    else:
                        try:
                            set_name(val, nm_tpl, key)
                        except BaseException as e:
                            msg = (
                                f"Error calling __set_name__ on {type(val).__name__!r} "
                                f"instance {key!r} in {typename!r}"
                            )
                            # BaseException.add_note() existed on py311,
                            # but the __set_name__ machinery didn't start
                            # using add_note() until py312.
                            # Making sure exceptions are raised in the same way
                            # as in "normal" classes seems most important here.
                            if sys.version_info >= (3, 12):
                                e.add_note(msg)
                                raise
                            else:
                                raise RuntimeError(msg) from e
            if typing.Generic in bases:
                nm_tpl.__init_subclass__()
            return nm_tpl
    _NamedTuple = type.__new__(_NamedTupleMeta, 'NamedTuple', (), {})
References pip._vendor.typing_extensions._make_nmtuple().
Referenced by apscheduler.triggers.combining.BaseCombiningTrigger.__setstate__(), pip._vendor.rich.style.Style._add(), pip._vendor.rich.style.Style.clear_meta_and_links(), yaml.constructor.SafeConstructor.construct_yaml_object(), pip._vendor.rich.style.Style.copy(), pip._vendor.rich.style.Style.from_color(), pip._vendor.rich.json.JSON.from_data(), pip._vendor.rich.style.Style.from_meta(), yaml.constructor.FullConstructor.make_python_instance(), pip._vendor.rich.style.Style.update_link(), and pip._vendor.rich.style.Style.without_color().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/typing_extensions.py