Read&Watch: django.db.backends.oracle.utils.InsertVar Class Reference
django.db.backends.oracle.utils.InsertVar Class Reference
Public Member Functions
__init__ (self, field)
bind_parameter (self, cursor)
get_value (self)
Public Attributes
dict db_type = self.types.get(internal_type, str)
bound_param = None
Static Public Attributes
dict types
Detailed Description
A late-binding cursor variable that can be passed to Cursor.execute
as a parameter, in order to receive the id of the row created by an
insert statement.
Definition at line 7 of file utils.py.
Constructor & Destructor Documentation
__init__()
django.db.backends.oracle.utils.InsertVar.__init__ (self, field)
Definition at line 31 of file utils.py.
    def __init__(self, field):
        internal_type = getattr(field, "target_field", field).get_internal_type()
        self.db_type = self.types.get(internal_type, str)
        self.bound_param = None
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
bind_parameter()
django.db.backends.oracle.utils.InsertVar.bind_parameter (self, cursor)
Definition at line 36 of file utils.py.
    def bind_parameter(self, cursor):
        self.bound_param = cursor.cursor.var(self.db_type)
        return self.bound_param
References bound_param, and db_type.
get_value()
django.db.backends.oracle.utils.InsertVar.get_value (self)
Definition at line 40 of file utils.py.
    def get_value(self):
        return self.bound_param.getvalue()
References bound_param.
Referenced by PIL.PdfParser.PdfParser.get_value(), PIL.PdfParser.PdfParser.interpret_trailer(), and PIL.PdfParser.PdfParser.read_indirect().
Member Data Documentation
bound_param
django.db.backends.oracle.utils.InsertVar.bound_param = None
Definition at line 34 of file utils.py.
Referenced by bind_parameter(), and get_value().
db_type
dict django.db.backends.oracle.utils.InsertVar.db_type = self.types.get(internal_type, str)
Definition at line 33 of file utils.py.
Referenced by bind_parameter(), django.db.models.fields.Field.cast_db_type(), django.db.models.fields.Field.db_parameters(), django.db.models.fields.related.ForeignKey.db_parameters(), django.contrib.postgres.fields.array.ArrayField.get_placeholder(), django.contrib.postgres.fields.ranges.RangeField.get_placeholder(), django.db.models.fields.Field.rel_db_type(), and django.db.models.fields.PositiveIntegerRelDbTypeMixin.rel_db_type().
types
dict django.db.backends.oracle.utils.InsertVar.types static
Initial value:
=  {
        "AutoField": int,
        "BigAutoField": int,
        "SmallAutoField": int,
        "IntegerField": int,
        "BigIntegerField": int,
        "SmallIntegerField": int,
        "PositiveBigIntegerField": int,
        "PositiveSmallIntegerField": int,
        "PositiveIntegerField": int,
        "BooleanField": int,
        "FloatField": Database.DB_TYPE_BINARY_DOUBLE,
        "DateTimeField": Database.DB_TYPE_TIMESTAMP,
        "DateField": Database.Date,
        "DecimalField": decimal.Decimal,
    }
Definition at line 14 of file utils.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/db/backends/oracle/utils.py