Read&Watch: pylint.extensions.typing.TypingChecker Class Reference
pylint.extensions.typing.TypingChecker Class Reference
Public Member Functions
None __init__ (self, PyLinter linter)
None open (self)
None visit_name (self, nodes.Name node)
None visit_attribute (self, nodes.Attribute node)
None visit_annassign (self, nodes.AnnAssign node)
None visit_subscript (self, nodes.Subscript node)
None leave_module (self, nodes.Module node)
Public Member Functions inherited from pylint.checkers.base_checker.BaseChecker
None __init__ (self, PyLinter linter)
bool __gt__ (self, Any other)
bool __eq__ (self, object other)
int __hash__ (self)
str __repr__ (self)
str __str__ (self)
str get_full_documentation (self, dict[str, MessageDefinitionTuple] msgs, Iterable[tuple[str, OptionDict, Any]] options, Sequence[tuple[str, str, ReportsCallable]] reports, str|None doc=None, str|None module=None, bool show_options=True)
None add_message (self, str msgid, int|None line=None, nodes.NodeNG|None node=None, Any args=None, Confidence|None confidence=None, int|None col_offset=None, int|None end_lineno=None, int|None end_col_offset=None)
None check_consistency (self)
MessageDefinition create_message_definition_from_tuple (self, str msgid, MessageDefinitionTuple msg_tuple)
list[MessageDefinition] messages (self)
None close (self)
Any get_map_data (self)
None reduce_map_data (self, PyLinter linter, list[Any] data)
Public Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
None __init__ (self, _ArgumentsManager arguments_manager)
Protected Member Functions
str _msg_postponed_eval_hint (self, nodes.NodeNG node)
bool _is_binop_union_annotation (self, nodes.NodeNG annotation)
list[nodes.NodeNG] _parse_binops_typehints (self, nodes.BinOp binop_node, list[nodes.NodeNG]|None typehints_list=None)
None _check_union_types (self, list[nodes.NodeNG] types, nodes.NodeNG annotation)
None _check_for_alternative_union_syntax (self, nodes.Name|nodes.Attribute node, str name)
None _check_for_typing_alias (self, nodes.Name|nodes.Attribute node)
None _check_broken_noreturn (self, nodes.Name|nodes.Attribute node)
None _check_broken_callable (self, nodes.Name|nodes.Attribute node)
bool _broken_callable_location (self, nodes.Name|nodes.Attribute node)
Protected Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
Any _option_value (self, str opt)
Iterator[ tuple[str, list[tuple[str, OptionDict, Any]]]|tuple[None, dict[str, list[tuple[str, OptionDict, Any]]]]] _options_by_section (self)
Iterator[tuple[str, OptionDict, Any]] _options_and_values (self, Options|None options=None)
Static Protected Member Functions
bool _is_deprecated_union_annotation (nodes.NodeNG annotation, str union_name)
bool _is_optional_none_annotation (nodes.Subscript annotation)
Protected Attributes
bool _found_broken_callable_location = False
set[str] _alias_name_collisions = set()
list _deprecated_typing_alias_msgs = []
list _consider_using_alias_msgs = []
tuple _py37_plus = (3, 7)
tuple _py39_plus = (3, 9)
tuple _py310_plus = (3, 10)
tuple _py313_plus = (3, 13)
tuple _should_check_typing_alias
tuple _should_check_alternative_union_syntax
_should_check_noreturn = py_version < (3, 7, 2)
_should_check_callable = py_version < (3, 9, 2)
Protected Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
_arguments_manager = arguments_manager
Additional Inherited Members
Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
linter = linter
messages
Static Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
str name = ""
dict msgs = {}
tuple reports = ()
bool enabled = True
Static Public Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
tuple options = ()
dict option_groups_descs = {}
Detailed Description
Find issue specifically related to type annotations.
Definition at line 89 of file typing.py.
Constructor & Destructor Documentation
__init__()
None pylint.extensions.typing.TypingChecker.__init__ (self, PyLinter linter)
Initialize checker instance.
Definition at line 171 of file typing.py.
    def __init__(self, linter: PyLinter) -> None:
        """Initialize checker instance."""
        super().__init__(linter=linter)
        self._found_broken_callable_location: bool = False
        self._alias_name_collisions: set[str] = set()
        self._deprecated_typing_alias_msgs: list[DeprecatedTypingAliasMsg] = []
        self._consider_using_alias_msgs: list[DeprecatedTypingAliasMsg] = []
References __init__().
Referenced by __init__().
Member Function Documentation
_broken_callable_location()
bool pylint.extensions.typing.TypingChecker._broken_callable_location (self, nodes.Name | nodes.Attribute node) protected
Check if node would be a broken location for collections.abc.Callable.
Definition at line 498 of file typing.py.
    def _broken_callable_location(self, node: nodes.Name | nodes.Attribute) -> bool:
        """Check if node would be a broken location for collections.abc.Callable."""
        if (
            in_type_checking_block(node)
            or is_postponed_evaluation_enabled(node)
            and is_node_in_type_annotation_context(node)
        ):
            return False
        # Check first Callable arg is a list of arguments -> Callable[[int], None]
        if not (
            isinstance(node.parent, nodes.Subscript)
            and isinstance(node.parent.slice, nodes.Tuple)
            and len(node.parent.slice.elts) == 2
            and isinstance(node.parent.slice.elts[0], nodes.List)
        ):
            return False
        # Check nested inside Optional or Union
        parent_subscript = node.parent.parent
        if isinstance(parent_subscript, nodes.BaseContainer):
            parent_subscript = parent_subscript.parent
        if not (
            isinstance(parent_subscript, nodes.Subscript)
            and isinstance(parent_subscript.value, (nodes.Name, nodes.Attribute))
        ):
            return False
        inferred_parent = safe_infer(parent_subscript.value)
        if not (
            isinstance(inferred_parent, nodes.FunctionDef)
            and inferred_parent.qname() in {"typing.Optional", "typing.Union"}
            or isinstance(inferred_parent, astroid.bases.Instance)
            and inferred_parent.qname() == "typing._SpecialForm"
        ):
            return False
        return True
Referenced by _check_broken_callable(), and _check_for_typing_alias().
_check_broken_callable()
None pylint.extensions.typing.TypingChecker._check_broken_callable (self, nodes.Name | nodes.Attribute node) protected
Check for 'collections.abc.Callable' inside Optional and Union.
Definition at line 486 of file typing.py.
    def _check_broken_callable(self, node: nodes.Name | nodes.Attribute) -> None:
        """Check for 'collections.abc.Callable' inside Optional and Union."""
        inferred = safe_infer(node)
        if not (
            isinstance(inferred, nodes.ClassDef)
            and inferred.qname() == "_collections_abc.Callable"
            and self._broken_callable_location(node)
        ):
            return
        self.add_message("broken-collections-callable", node=node, confidence=INFERENCE)
References _broken_callable_location(), and pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_attribute(), and visit_name().
_check_broken_noreturn()
None pylint.extensions.typing.TypingChecker._check_broken_noreturn (self, nodes.Name | nodes.Attribute node) protected
Check for 'NoReturn' inside compound types.
Definition at line 460 of file typing.py.
    def _check_broken_noreturn(self, node: nodes.Name | nodes.Attribute) -> None:
        """Check for 'NoReturn' inside compound types."""
        if not isinstance(node.parent, nodes.BaseContainer):
            # NoReturn not part of a Union or Callable type
            return
        if (
            in_type_checking_block(node)
            or is_postponed_evaluation_enabled(node)
            and is_node_in_type_annotation_context(node)
        ):
            return
        for inferred in node.infer():
            # To deal with typing_extensions, don't use safe_infer
            if (
                isinstance(inferred, (nodes.FunctionDef, nodes.ClassDef))
                and inferred.qname() in TYPING_NORETURN
                # In Python 3.7 - 3.8, NoReturn is alias of '_SpecialForm'
                or isinstance(inferred, astroid.bases.BaseInstance)
                and isinstance(inferred._proxied, nodes.ClassDef)
                and inferred._proxied.qname() == "typing._SpecialForm"
            ):
                self.add_message("broken-noreturn", node=node, confidence=INFERENCE)
                break
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_attribute(), and visit_name().
_check_for_alternative_union_syntax()
None pylint.extensions.typing.TypingChecker._check_for_alternative_union_syntax (self, nodes.Name | nodes.Attribute node, str name) protected
Check if alternative union syntax could be used.
Requires
- Python 3.10
- OR: Python 3.7+ with postponed evaluation in
      a type annotation context
Definition at line 336 of file typing.py.
    ) -> None:
        """Check if alternative union syntax could be used.
        Requires
        - Python 3.10
        - OR: Python 3.7+ with postponed evaluation in
              a type annotation context
        """
        inferred = safe_infer(node)
        if not (
            isinstance(inferred, nodes.FunctionDef)
            and inferred.qname() in {"typing.Optional", "typing.Union"}
            or isinstance(inferred, astroid.bases.Instance)
            and inferred.qname() == "typing._SpecialForm"
        ):
            return
        if not (self._py310_plus or is_node_in_type_annotation_context(node)):
            return
        self.add_message(
            "consider-alternative-union-syntax",
            node=node,
            args=(name, self._msg_postponed_eval_hint(node)),
            confidence=INFERENCE,
        )
References _msg_postponed_eval_hint(), pylint.checkers.typecheck.TypeChecker._py310_plus, _py310_plus, and pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_attribute(), and visit_name().
_check_for_typing_alias()
None pylint.extensions.typing.TypingChecker._check_for_typing_alias (self, nodes.Name | nodes.Attribute node) protected
Check if typing alias is deprecated or could be replaced.
Requires
- Python 3.9
- OR: Python 3.7+ with postponed evaluation in
      a type annotation context
For Python 3.7+: Only emit message if change doesn't create
    any name collisions, only ever used in a type annotation
    context, and can safely be replaced.
Definition at line 365 of file typing.py.
    ) -> None:
        """Check if typing alias is deprecated or could be replaced.
        Requires
        - Python 3.9
        - OR: Python 3.7+ with postponed evaluation in
              a type annotation context
        For Python 3.7+: Only emit message if change doesn't create
            any name collisions, only ever used in a type annotation
            context, and can safely be replaced.
        """
        inferred = safe_infer(node)
        if not isinstance(inferred, nodes.ClassDef):
            return
        alias = DEPRECATED_TYPING_ALIASES.get(inferred.qname(), None)
        if alias is None:
            return
        if self._py39_plus:
            if inferred.qname() == "typing.Callable" and self._broken_callable_location(
                node
            ):
                self._found_broken_callable_location = True
            self._deprecated_typing_alias_msgs.append(
                DeprecatedTypingAliasMsg(
                    node,
                    inferred.qname(),
                    alias.name,
                )
            )
            return
        # For PY37+, check for type annotation context first
        if not is_node_in_type_annotation_context(node) and isinstance(
            node.parent, nodes.Subscript
        ):
            if alias.name_collision is True:
                self._alias_name_collisions.add(inferred.qname())
            return
        self._consider_using_alias_msgs.append(
            DeprecatedTypingAliasMsg(
                node,
                inferred.qname(),
                alias.name,
                isinstance(node.parent, nodes.Subscript),
            )
        )
References _alias_name_collisions, _broken_callable_location(), _consider_using_alias_msgs, _deprecated_typing_alias_msgs, _found_broken_callable_location, and _py39_plus.
Referenced by visit_attribute(), and visit_name().
_check_union_types()
None pylint.extensions.typing.TypingChecker._check_union_types (self, list[nodes.NodeNG] types, nodes.NodeNG annotation) protected
Definition at line 320 of file typing.py.
    ) -> None:
        types_set = set()
        for typehint in types:
            typehint_str = typehint.as_string()
            if typehint_str in types_set:
                self.add_message(
                    "redundant-typehint-argument",
                    node=annotation,
                    args=(typehint_str),
                    confidence=HIGH,
                )
            else:
                types_set.add(typehint_str)
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_annassign().
_is_binop_union_annotation()
bool pylint.extensions.typing.TypingChecker._is_binop_union_annotation (self, nodes.NodeNG annotation) protected
Definition at line 296 of file typing.py.
    def _is_binop_union_annotation(self, annotation: nodes.NodeNG) -> bool:
        return self._should_check_alternative_union_syntax and isinstance(
            annotation, nodes.BinOp
        )
References _should_check_alternative_union_syntax.
Referenced by visit_annassign().
_is_deprecated_union_annotation()
bool pylint.extensions.typing.TypingChecker._is_deprecated_union_annotation (nodes.NodeNG annotation, str union_name) static protected
Definition at line 287 of file typing.py.
    ) -> bool:
        return (
            isinstance(annotation, nodes.Subscript)
            and isinstance(annotation.value, nodes.Name)
            and annotation.value.name == union_name
        )
Referenced by visit_annassign().
_is_optional_none_annotation()
bool pylint.extensions.typing.TypingChecker._is_optional_none_annotation (nodes.Subscript annotation) static protected
Definition at line 302 of file typing.py.
    def _is_optional_none_annotation(annotation: nodes.Subscript) -> bool:
        return (
            isinstance(annotation.slice, nodes.Const) and annotation.slice.value is None
        )
Referenced by visit_annassign().
_msg_postponed_eval_hint()
str pylint.extensions.typing.TypingChecker._msg_postponed_eval_hint (self, nodes.NodeNG node) protected
Message hint if postponed evaluation isn't enabled.
Definition at line 196 of file typing.py.
    def _msg_postponed_eval_hint(self, node: nodes.NodeNG) -> str:
        """Message hint if postponed evaluation isn't enabled."""
        if self._py310_plus or "annotations" in node.root().future_imports:
            return ""
        return ". Add 'from __future__ import annotations' as well"
References pylint.checkers.typecheck.TypeChecker._py310_plus, and _py310_plus.
Referenced by _check_for_alternative_union_syntax(), and leave_module().
_parse_binops_typehints()
list[nodes.NodeNG] pylint.extensions.typing.TypingChecker._parse_binops_typehints (self, nodes.BinOp binop_node, list[nodes.NodeNG] | None typehints_list = None) protected
Definition at line 307 of file typing.py.
    ) -> list[nodes.NodeNG]:
        typehints_list = typehints_list or []
        if isinstance(binop_node.left, nodes.BinOp):
            typehints_list.extend(
                self._parse_binops_typehints(binop_node.left, typehints_list)
            )
        else:
            typehints_list.append(binop_node.left)
        typehints_list.append(binop_node.right)
        return typehints_list
References _parse_binops_typehints().
Referenced by _parse_binops_typehints(), and visit_annassign().
leave_module()
None pylint.extensions.typing.TypingChecker.leave_module (self, nodes.Module node)
After parsing of module is complete, add messages for
'consider-using-alias' check.
Make sure results are safe to recommend / collision free.
Definition at line 418 of file typing.py.
    def leave_module(self, node: nodes.Module) -> None:
        """After parsing of module is complete, add messages for
        'consider-using-alias' check.
        Make sure results are safe to recommend / collision free.
        """
        if self._py39_plus:
            for msg in self._deprecated_typing_alias_msgs:
                if (
                    self._found_broken_callable_location
                    and msg.qname == "typing.Callable"
                ):
                    continue
                self.add_message(
                    "deprecated-typing-alias",
                    node=msg.node,
                    args=(msg.qname, msg.alias),
                    confidence=INFERENCE,
                )
        elif self._py37_plus:
            msg_future_import = self._msg_postponed_eval_hint(node)
            for msg in self._consider_using_alias_msgs:
                if msg.qname in self._alias_name_collisions:
                    continue
                self.add_message(
                    "consider-using-alias",
                    node=msg.node,
                    args=(
                        msg.qname,
                        msg.alias,
                        msg_future_import if msg.parent_subscript else "",
                    ),
                    confidence=INFERENCE,
                )
        # Clear all module cache variables
        self._found_broken_callable_location = False
        self._deprecated_typing_alias_msgs.clear()
        self._alias_name_collisions.clear()
        self._consider_using_alias_msgs.clear()
References _alias_name_collisions, _consider_using_alias_msgs, _deprecated_typing_alias_msgs, _found_broken_callable_location, _msg_postponed_eval_hint(), _py37_plus, _py39_plus, and pylint.checkers.base_checker.BaseChecker.add_message().
open()
None pylint.extensions.typing.TypingChecker.open (self)
Called before visiting project (i.e. set of modules).
Reimplemented from pylint.checkers.base_checker.BaseChecker.
Definition at line 179 of file typing.py.
    def open(self) -> None:
        py_version = self.linter.config.py_version
        self._py37_plus = py_version >= (3, 7)
        self._py39_plus = py_version >= (3, 9)
        self._py310_plus = py_version >= (3, 10)
        self._py313_plus = py_version >= (3, 13)
        self._should_check_typing_alias = self._py39_plus or (
            self._py37_plus and self.linter.config.runtime_typing is False
        )
        self._should_check_alternative_union_syntax = self._py310_plus or (
            self._py37_plus and self.linter.config.runtime_typing is False
        )
        self._should_check_noreturn = py_version < (3, 7, 2)
        self._should_check_callable = py_version < (3, 9, 2)
References pylint.checkers.base_checker.BaseChecker.linter.
Referenced by django.contrib.staticfiles.storage.HashedFilesMixin.hashed_name().
visit_annassign()
None pylint.extensions.typing.TypingChecker.visit_annassign (self, nodes.AnnAssign node)
Definition at line 237 of file typing.py.
    def visit_annassign(self, node: nodes.AnnAssign) -> None:
        annotation = node.annotation
        if self._is_deprecated_union_annotation(annotation, "Optional"):
            if self._is_optional_none_annotation(annotation):
                self.add_message(
                    "redundant-typehint-argument",
                    node=annotation,
                    args="None",
                    confidence=HIGH,
                )
            return
        if self._is_deprecated_union_annotation(annotation, "Union") and isinstance(
            annotation.slice, nodes.Tuple
        ):
            types = annotation.slice.elts
        elif self._is_binop_union_annotation(annotation):
            types = self._parse_binops_typehints(annotation)
        else:
            return
        self._check_union_types(types, node)
References _check_union_types(), _is_binop_union_annotation(), _is_deprecated_union_annotation(), _is_optional_none_annotation(), _parse_binops_typehints(), and pylint.checkers.base_checker.BaseChecker.add_message().
visit_attribute()
None pylint.extensions.typing.TypingChecker.visit_attribute (self, nodes.Attribute node)
Definition at line 226 of file typing.py.
    def visit_attribute(self, node: nodes.Attribute) -> None:
        if self._should_check_typing_alias and node.attrname in ALIAS_NAMES:
            self._check_for_typing_alias(node)
        if self._should_check_alternative_union_syntax and node.attrname in UNION_NAMES:
            self._check_for_alternative_union_syntax(node, node.attrname)
        if self._should_check_noreturn and node.attrname == "NoReturn":
            self._check_broken_noreturn(node)
        if self._should_check_callable and node.attrname == "Callable":
            self._check_broken_callable(node)
References _check_broken_callable(), _check_broken_noreturn(), _check_for_alternative_union_syntax(), _check_for_typing_alias(), _should_check_alternative_union_syntax, _should_check_callable, _should_check_noreturn, and _should_check_typing_alias.
visit_name()
None pylint.extensions.typing.TypingChecker.visit_name (self, nodes.Name node)
Definition at line 209 of file typing.py.
    def visit_name(self, node: nodes.Name) -> None:
        if self._should_check_typing_alias and node.name in ALIAS_NAMES:
            self._check_for_typing_alias(node)
        if self._should_check_alternative_union_syntax and node.name in UNION_NAMES:
            self._check_for_alternative_union_syntax(node, node.name)
        if self._should_check_noreturn and node.name == "NoReturn":
            self._check_broken_noreturn(node)
        if self._should_check_callable and node.name == "Callable":
            self._check_broken_callable(node)
References _check_broken_callable(), _check_broken_noreturn(), _check_for_alternative_union_syntax(), _check_for_typing_alias(), _should_check_alternative_union_syntax, _should_check_callable, _should_check_noreturn, and _should_check_typing_alias.
visit_subscript()
None pylint.extensions.typing.TypingChecker.visit_subscript (self, nodes.Subscript node)
Definition at line 260 of file typing.py.
    def visit_subscript(self, node: nodes.Subscript) -> None:
        inferred = safe_infer(node.value)
        if (  # pylint: disable=too-many-boolean-expressions
            isinstance(inferred, nodes.ClassDef)
            and (
                inferred.qname() in {"typing.Generator", "typing.AsyncGenerator"}
                and self._py313_plus
                or inferred.qname()
                in {"_collections_abc.Generator", "_collections_abc.AsyncGenerator"}
            )
            and isinstance(node.slice, nodes.Tuple)
            and all(
                (isinstance(el, nodes.Const) and el.value is None)
                for el in node.slice.elts[1:]
            )
        ):
            suggested_str = (
                f"{node.value.as_string()}[{node.slice.elts[0].as_string()}]"
            )
            self.add_message(
                "unnecessary-default-type-args",
                args=(node.as_string(), suggested_str),
                node=node,
                confidence=HIGH,
            )
References _py313_plus, and pylint.checkers.base_checker.BaseChecker.add_message().
Member Data Documentation
_alias_name_collisions
set[str] pylint.extensions.typing.TypingChecker._alias_name_collisions = set() protected
Definition at line 175 of file typing.py.
Referenced by _check_for_typing_alias(), and leave_module().
_consider_using_alias_msgs
list pylint.extensions.typing.TypingChecker._consider_using_alias_msgs = [] protected
Definition at line 177 of file typing.py.
Referenced by _check_for_typing_alias(), and leave_module().
_deprecated_typing_alias_msgs
list pylint.extensions.typing.TypingChecker._deprecated_typing_alias_msgs = [] protected
Definition at line 176 of file typing.py.
Referenced by _check_for_typing_alias(), and leave_module().
_found_broken_callable_location
bool pylint.extensions.typing.TypingChecker._found_broken_callable_location = False protected
Definition at line 174 of file typing.py.
Referenced by _check_for_typing_alias(), and leave_module().
_py310_plus
tuple pylint.extensions.typing.TypingChecker._py310_plus = (3, 10) protected
Definition at line 183 of file typing.py.
Referenced by _check_for_alternative_union_syntax(), and _msg_postponed_eval_hint().
_py313_plus
tuple pylint.extensions.typing.TypingChecker._py313_plus = (3, 13) protected
Definition at line 184 of file typing.py.
Referenced by visit_subscript().
_py37_plus
tuple pylint.extensions.typing.TypingChecker._py37_plus = (3, 7) protected
Definition at line 181 of file typing.py.
Referenced by leave_module().
_py39_plus
tuple pylint.extensions.typing.TypingChecker._py39_plus = (3, 9) protected
Definition at line 182 of file typing.py.
Referenced by _check_for_typing_alias(), and leave_module().
_should_check_alternative_union_syntax
tuple pylint.extensions.typing.TypingChecker._should_check_alternative_union_syntax protected
Initial value:
=  self._py310_plus or (
            self._py37_plus and self.linter.config.runtime_typing is False
        )
Definition at line 189 of file typing.py.
Referenced by _is_binop_union_annotation(), visit_attribute(), and visit_name().
_should_check_callable
pylint.extensions.typing.TypingChecker._should_check_callable = py_version < (3, 9, 2) protected
Definition at line 194 of file typing.py.
Referenced by visit_attribute(), and visit_name().
_should_check_noreturn
pylint.extensions.typing.TypingChecker._should_check_noreturn = py_version < (3, 7, 2) protected
Definition at line 193 of file typing.py.
Referenced by visit_attribute(), and visit_name().
_should_check_typing_alias
tuple pylint.extensions.typing.TypingChecker._should_check_typing_alias protected
Initial value:
=  self._py39_plus or (
            self._py37_plus and self.linter.config.runtime_typing is False
        )
Definition at line 186 of file typing.py.
Referenced by visit_attribute(), and visit_name().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pylint/extensions/typing.py