Read&Watch: pip._vendor.cachecontrol.heuristics.ExpiresAfter Class Reference
pip._vendor.cachecontrol.heuristics.ExpiresAfter Class Reference
Public Member Functions
None __init__ (self, **Any kw)
dict[str, str] update_headers (self, HTTPResponse response)
str|None warning (self, HTTPResponse response)
Public Member Functions inherited from pip._vendor.cachecontrol.heuristics.BaseHeuristic
HTTPResponse apply (self, HTTPResponse response)
Public Attributes
delta = timedelta(**kw)
Detailed Description
Cache **all** requests for a defined time period.
Definition at line 77 of file heuristics.py.
Constructor & Destructor Documentation
__init__()
None pip._vendor.cachecontrol.heuristics.ExpiresAfter.__init__ (self, **Any kw)
Definition at line 82 of file heuristics.py.
    def __init__(self, **kw: Any) -> None:
        self.delta = timedelta(**kw)
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
update_headers()
dict[str, str] pip._vendor.cachecontrol.heuristics.ExpiresAfter.update_headers (self, HTTPResponse response)
Update the response headers with any new headers.
NOTE: This SHOULD always include some Warning header to
      signify that the response was cached by the client, not
      by way of the provided headers.
Reimplemented from pip._vendor.cachecontrol.heuristics.BaseHeuristic.
Definition at line 85 of file heuristics.py.
    def update_headers(self, response: HTTPResponse) -> dict[str, str]:
        expires = expire_after(self.delta)
        return {"expires": datetime_to_header(expires), "cache-control": "public"}
References pip._vendor.cachecontrol.heuristics.datetime_to_header(), delta, and pip._vendor.cachecontrol.heuristics.expire_after().
warning()
str | None pip._vendor.cachecontrol.heuristics.ExpiresAfter.warning (self, HTTPResponse response)
Return a valid 1xx warning header value describing the cache
adjustments.
The response is provided too allow warnings like 113
http://tools.ietf.org/html/rfc7234#section-5.5.4 where we need
to explicitly say response is over 24 hours old.
Reimplemented from pip._vendor.cachecontrol.heuristics.BaseHeuristic.
Definition at line 89 of file heuristics.py.
    def warning(self, response: HTTPResponse) -> str | None:
        tmpl = "110 - Automatically cached for %s. Response might be stale"
        return tmpl % self.delta
References delta.
Member Data Documentation
delta
pip._vendor.cachecontrol.heuristics.ExpiresAfter.delta = timedelta(**kw)
Definition at line 83 of file heuristics.py.
Referenced by update_headers(), and warning().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/cachecontrol/heuristics.py