Read&Watch: pip._internal.cache.WheelCache Class Reference
pip._internal.cache.WheelCache Class Reference
Public Member Functions
None __init__ (self, str cache_dir)
str get_path_for_link (self, Link link)
str get_ephem_path_for_link (self, Link link)
Link get (self, Link link, Optional[str] package_name, List[Tag] supported_tags)
Optional[CacheEntry] get_cache_entry (self, Link link, Optional[str] package_name, List[Tag] supported_tags)
Public Member Functions inherited from pip._internal.cache.Cache
None __init__ (self, str cache_dir)
Static Public Member Functions
None record_download_origin (str cache_dir, DirectUrl download_info)
Protected Attributes
_wheel_cache = SimpleWheelCache(cache_dir)
_ephem_cache = EphemWheelCache()
Additional Inherited Members
Public Attributes inherited from pip._internal.cache.Cache
cache_dir = cache_dir or None
Protected Member Functions inherited from pip._internal.cache.Cache
List[str] _get_cache_path_parts (self, Link link)
List[Any] _get_candidates (self, Link link, str canonical_package_name)
Detailed Description
Wraps EphemWheelCache and SimpleWheelCache into a single Cache
This Cache allows for gracefully degradation, using the ephem wheel cache
when a certain link is not found in the simple wheel cache first.
Definition at line 208 of file cache.py.
Constructor & Destructor Documentation
__init__()
None pip._internal.cache.WheelCache.__init__ (self, str cache_dir)
Definition at line 215 of file cache.py.
    def __init__(self, cache_dir: str) -> None:
        super().__init__(cache_dir)
        self._wheel_cache = SimpleWheelCache(cache_dir)
        self._ephem_cache = EphemWheelCache()
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
get()
Link pip._internal.cache.WheelCache.get (self, Link link, Optional[str] package_name, List[Tag] supported_tags)
Returns a link to a cached item if it exists, otherwise returns the
passed link.
Reimplemented from pip._internal.cache.Cache.
Definition at line 226 of file cache.py.
    ) -> Link:
        cache_entry = self.get_cache_entry(link, package_name, supported_tags)
        if cache_entry is None:
            return link
        return cache_entry.link
Referenced by pip._vendor.distlib.metadata.LegacyMetadata.__getitem__(), pip._vendor.rich.layout.Layout.__getitem__(), django.test.client.ClientMixin._follow_redirect(), pip._vendor.distlib.metadata.LegacyMetadata.check(), PIL.Image.Exif.get_ifd(), and pip._vendor.distlib.metadata.LegacyMetadata.write_file().
get_cache_entry()
Optional[CacheEntry] pip._internal.cache.WheelCache.get_cache_entry (self, Link link, Optional[str] package_name, List[Tag] supported_tags)
Returns a CacheEntry with a link to a cached item if it exists or
None. The cache entry indicates if the item was found in the persistent
or ephemeral cache.
Definition at line 237 of file cache.py.
    ) -> Optional[CacheEntry]:
        """Returns a CacheEntry with a link to a cached item if it exists or
        None. The cache entry indicates if the item was found in the persistent
        or ephemeral cache.
        """
        retval = self._wheel_cache.get(
            link=link,
            package_name=package_name,
            supported_tags=supported_tags,
        )
        if retval is not link:
            return CacheEntry(retval, persistent=True)
        retval = self._ephem_cache.get(
            link=link,
            package_name=package_name,
            supported_tags=supported_tags,
        )
        if retval is not link:
            return CacheEntry(retval, persistent=False)
        return None
get_ephem_path_for_link()
str pip._internal.cache.WheelCache.get_ephem_path_for_link (self, Link link)
Definition at line 223 of file cache.py.
    def get_ephem_path_for_link(self, link: Link) -> str:
        return self._ephem_cache.get_path_for_link(link)
get_path_for_link()
str pip._internal.cache.WheelCache.get_path_for_link (self, Link link)
Return a directory to store cached items in for link.
Reimplemented from pip._internal.cache.Cache.
Definition at line 220 of file cache.py.
    def get_path_for_link(self, link: Link) -> str:
        return self._wheel_cache.get_path_for_link(link)
record_download_origin()
None pip._internal.cache.WheelCache.record_download_origin (str cache_dir, DirectUrl download_info) static
Definition at line 266 of file cache.py.
    def record_download_origin(cache_dir: str, download_info: DirectUrl) -> None:
        origin_path = Path(cache_dir) / ORIGIN_JSON_NAME
        if origin_path.exists():
            try:
                origin = DirectUrl.from_json(origin_path.read_text(encoding="utf-8"))
            except Exception as e:
                logger.warning(
                    "Could not read origin file %s in cache entry (%s). "
                    "Will attempt to overwrite it.",
                    origin_path,
                    e,
                )
            else:
                # TODO: use DirectUrl.equivalent when
                # https://github.com/pypa/pip/pull/10564 is merged.
                if origin.url != download_info.url:
                    logger.warning(
                        "Origin URL %s in cache entry %s does not match download URL "
                        "%s. This is likely a pip bug or a cache corruption issue. "
                        "Will overwrite it with the new value.",
                        origin.url,
                        cache_dir,
                        download_info.url,
                    )
        origin_path.write_text(download_info.to_json(), encoding="utf-8")
Member Data Documentation
_ephem_cache
pip._internal.cache.WheelCache._ephem_cache = EphemWheelCache() protected
Definition at line 218 of file cache.py.
_wheel_cache
pip._internal.cache.WheelCache._wheel_cache = SimpleWheelCache(cache_dir) protected
Definition at line 217 of file cache.py.
Referenced by pip._internal.resolution.resolvelib.factory.Factory.get_wheel_cache_entry().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_internal/cache.py