Read&Watch: django.utils.html.Urlizer Class Reference
django.utils.html.Urlizer Class Reference
Public Member Functions
__call__ (self, text, trim_url_limit=None, nofollow=False, autoescape=False)
handle_word (self, word, *, safe_input, trim_url_limit=None, nofollow=False, autoescape=False)
trim_url (self, x, *, limit)
wrapping_punctuation_openings (self)
trailing_punctuation_chars_no_semicolon (self)
trailing_punctuation_chars_has_semicolon (self)
trim_punctuation (self, word)
Static Public Member Functions
is_email_simple (value)
Static Public Attributes
str trailing_punctuation_chars = ".,:;!"
list wrapping_punctuation = [("(", ")"), ("[", "]")]
simple_url_re = _lazy_re_compile(r"^https?://\[?\w", re.IGNORECASE)
simple_url_2_re
word_split_re = _lazy_re_compile()
str mailto_template = "mailto:{local}@{domain}"
str url_template = '<a href="{href}"{attrs}>{url}</a>'
Detailed Description
Convert any URLs in text into clickable links.
Work on http://, https://, www. links, and also on links ending in one of
the original seven gTLDs (.com, .edu, .gov, .int, .mil, .net, and .org).
Links can have trailing punctuation (periods, commas, close-parens) and
leading punctuation (opening parens) and it'll still do the right thing.
Definition at line 273 of file html.py.
Member Function Documentation
__call__()
django.utils.html.Urlizer.__call__ (self, text, trim_url_limit = None, nofollow = False, autoescape = False)
If trim_url_limit is not None, truncate the URLs in the link text
longer than this limit to trim_url_limit - 1 characters and append an
ellipsis.
If nofollow is True, give the links a rel="nofollow" attribute.
If autoescape is True, autoescape the link text and URLs.
Definition at line 295 of file html.py.
    def __call__(self, text, trim_url_limit=None, nofollow=False, autoescape=False):
        """
        If trim_url_limit is not None, truncate the URLs in the link text
        longer than this limit to trim_url_limit - 1 characters and append an
        ellipsis.
        If nofollow is True, give the links a rel="nofollow" attribute.
        If autoescape is True, autoescape the link text and URLs.
        """
        safe_input = isinstance(text, SafeData)
        words = self.word_split_re.split(str(text))
        return "".join(
            [
                self.handle_word(
                    word,
                    safe_input=safe_input,
                    trim_url_limit=trim_url_limit,
                    nofollow=nofollow,
                    autoescape=autoescape,
                )
                for word in words
            ]
        )
References handle_word(), and word_split_re.
handle_word()
django.utils.html.Urlizer.handle_word (self, word, * , safe_input, trim_url_limit = None, nofollow = False, autoescape = False)
Definition at line 321 of file html.py.
    ):
        if "." in word or "@" in word or ":" in word:
            # lead: Punctuation trimmed from the beginning of the word.
            # middle: State of the word.
            # trail: Punctuation trimmed from the end of the word.
            lead, middle, trail = self.trim_punctuation(word)
            # Make URL we want to point to.
            url = None
            nofollow_attr = ' rel="nofollow"' if nofollow else ""
            if len(middle) <= MAX_URL_LENGTH and self.simple_url_re.match(middle):
                url = smart_urlquote(html.unescape(middle))
            elif len(middle) <= MAX_URL_LENGTH and self.simple_url_2_re.match(middle):
                url = smart_urlquote("http://%s" % html.unescape(middle))
            elif ":" not in middle and self.is_email_simple(middle):
                local, domain = middle.rsplit("@", 1)
                try:
                    domain = punycode(domain)
                except UnicodeError:
                    return word
                url = self.mailto_template.format(local=local, domain=domain)
                nofollow_attr = ""
            # Make link.
            if url:
                trimmed = self.trim_url(middle, limit=trim_url_limit)
                if autoescape and not safe_input:
                    lead, trail = escape(lead), escape(trail)
                    trimmed = escape(trimmed)
                middle = self.url_template.format(
                    href=escape(url),
                    attrs=nofollow_attr,
                    url=trimmed,
                )
                return mark_safe(f"{lead}{middle}{trail}")
            else:
                if safe_input:
                    return mark_safe(word)
                elif autoescape:
                    return escape(word)
        elif safe_input:
            return mark_safe(word)
        elif autoescape:
            return escape(word)
        return word
References django.utils.html.escape(), is_email_simple(), mailto_template, simple_url_2_re, simple_url_re, django.utils.html.smart_urlquote(), trim_punctuation(), trim_url(), and url_template.
Referenced by __call__().
is_email_simple()
django.utils.html.Urlizer.is_email_simple (value) static
Return True if value looks like an email address.
Definition at line 448 of file html.py.
    def is_email_simple(value):
        """Return True if value looks like an email address."""
        # An @ must be in the middle of the value.
        if "@" not in value or value.startswith("@") or value.endswith("@"):
            return False
        try:
            p1, p2 = value.split("@")
        except ValueError:
            # value contains more than one @.
            return False
        # Max length for domain name labels is 63 characters per RFC 1034.
        # Helps to avoid ReDoS vectors in the domain part.
        if len(p2) > 63:
            return False
        # Dot must be in p2 (e.g. example.com)
        if "." not in p2 or p2.startswith("."):
            return False
        return True
Referenced by handle_word().
trailing_punctuation_chars_has_semicolon()
django.utils.html.Urlizer.trailing_punctuation_chars_has_semicolon (self)
Definition at line 387 of file html.py.
    def trailing_punctuation_chars_has_semicolon(self):
        return ";" in self.trailing_punctuation_chars
References trailing_punctuation_chars.
Referenced by trim_punctuation().
trailing_punctuation_chars_no_semicolon()
django.utils.html.Urlizer.trailing_punctuation_chars_no_semicolon (self)
Definition at line 383 of file html.py.
    def trailing_punctuation_chars_no_semicolon(self):
        return self.trailing_punctuation_chars.replace(";", "")
References trailing_punctuation_chars.
Referenced by trim_punctuation().
trim_punctuation()
django.utils.html.Urlizer.trim_punctuation (self, word)
Trim trailing and wrapping punctuation from `word`. Return the items of
the new state.
Definition at line 390 of file html.py.
    def trim_punctuation(self, word):
        """
        Trim trailing and wrapping punctuation from `word`. Return the items of
        the new state.
        """
        # Strip all opening wrapping punctuation.
        middle = word.lstrip(self.wrapping_punctuation_openings)
        lead = word[: len(word) - len(middle)]
        trail = ""
        # Continue trimming until middle remains unchanged.
        trimmed_something = True
        counts = CountsDict(word=middle)
        while trimmed_something and middle:
            trimmed_something = False
            # Trim wrapping punctuation.
            for opening, closing in self.wrapping_punctuation:
                if counts[opening] < counts[closing]:
                    rstripped = middle.rstrip(closing)
                    if rstripped != middle:
                        strip = counts[closing] - counts[opening]
                        trail = middle[-strip:]
                        middle = middle[:-strip]
                        trimmed_something = True
                        counts[closing] -= strip
            amp = middle.rfind("&")
            if amp == -1:
                rstripped = middle.rstrip(self.trailing_punctuation_chars)
            else:
                rstripped = middle.rstrip(self.trailing_punctuation_chars_no_semicolon)
            if rstripped != middle:
                trail = middle[len(rstripped) :] + trail
                middle = rstripped
                trimmed_something = True
            if self.trailing_punctuation_chars_has_semicolon and middle.endswith(";"):
                # Only strip if not part of an HTML entity.
                potential_entity = middle[amp:]
                escaped = html.unescape(potential_entity)
                if escaped == potential_entity or escaped.endswith(";"):
                    rstripped = middle.rstrip(self.trailing_punctuation_chars)
                    trail_start = len(rstripped)
                    amount_trailing_semicolons = len(middle) - len(middle.rstrip(";"))
                    if amp > -1 and amount_trailing_semicolons > 1:
                        # Leave up to most recent semicolon as might be an entity.
                        recent_semicolon = middle[trail_start:].index(";")
                        middle_semicolon_index = recent_semicolon + trail_start + 1
                        trail = middle[middle_semicolon_index:] + trail
                        middle = rstripped + middle[trail_start:middle_semicolon_index]
                    else:
                        trail = middle[trail_start:] + trail
                        middle = rstripped
                    trimmed_something = True
        return lead, middle, trail
References trailing_punctuation_chars, trailing_punctuation_chars_has_semicolon(), trailing_punctuation_chars_no_semicolon(), wrapping_punctuation, and wrapping_punctuation_openings().
Referenced by handle_word().
trim_url()
django.utils.html.Urlizer.trim_url (self, x, * , limit)
Definition at line 373 of file html.py.
    def trim_url(self, x, *, limit):
        if limit is None or len(x) <= limit:
            return x
        return "%s…" % x[: max(0, limit - 1)]
Referenced by handle_word().
wrapping_punctuation_openings()
django.utils.html.Urlizer.wrapping_punctuation_openings (self)
Definition at line 379 of file html.py.
    def wrapping_punctuation_openings(self):
        return "".join(dict(self.wrapping_punctuation).keys())
References wrapping_punctuation.
Referenced by trim_punctuation().
Member Data Documentation
mailto_template
str django.utils.html.Urlizer.mailto_template = "mailto:{local}@{domain}" static
Definition at line 292 of file html.py.
Referenced by handle_word().
simple_url_2_re
django.utils.html.Urlizer.simple_url_2_re static
Initial value:
=  _lazy_re_compile(
        r"^www\.|^(?!http)\w[^@]+\.(com|edu|gov|int|mil|net|org)($|/.*)$", re.IGNORECASE
    )
Definition at line 287 of file html.py.
Referenced by handle_word().
simple_url_re
django.utils.html.Urlizer.simple_url_re = _lazy_re_compile(r"^https?://\[?\w", re.IGNORECASE) static
Definition at line 286 of file html.py.
Referenced by handle_word().
trailing_punctuation_chars
str django.utils.html.Urlizer.trailing_punctuation_chars = ".,:;!" static
Definition at line 283 of file html.py.
Referenced by trailing_punctuation_chars_has_semicolon(), trailing_punctuation_chars_no_semicolon(), and trim_punctuation().
url_template
str django.utils.html.Urlizer.url_template = '<a href="{href}"{attrs}>{url}</a>' static
Definition at line 293 of file html.py.
Referenced by handle_word().
word_split_re
django.utils.html.Urlizer.word_split_re = _lazy_re_compile() static
Definition at line 290 of file html.py.
Referenced by __call__().
wrapping_punctuation
django.utils.html.Urlizer.wrapping_punctuation = [("(", ")"), ("[", "]")] static
Definition at line 284 of file html.py.
Referenced by trim_punctuation(), and wrapping_punctuation_openings().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/utils/html.py