Read&Watch: crispy_forms.templatetags.crispy_forms_tags.CrispyFormNode Class Reference
crispy_forms.templatetags.crispy_forms_tags.CrispyFormNode Class Reference
Public Member Functions
render (self, context)
Public Member Functions inherited from crispy_forms.templatetags.crispy_forms_tags.BasicNode
__init__ (self, form, helper, template_pack=None)
get_render (self, context)
get_response_dict (self, helper, context, is_formset)
Additional Inherited Members
Public Attributes inherited from crispy_forms.templatetags.crispy_forms_tags.BasicNode
form = form
helper = helper
template_pack = template_pack or get_template_pack()
actual_helper = helper
Detailed Description
Definition at line 197 of file crispy_forms_tags.py.
Member Function Documentation
render()
crispy_forms.templatetags.crispy_forms_tags.CrispyFormNode.render (self, context)
Definition at line 198 of file crispy_forms_tags.py.
    def render(self, context):
        c = self.get_render(context).flatten()
        if self.actual_helper is not None and getattr(self.actual_helper, "template", False):
            template = get_template(self.actual_helper.template)
        else:
            if c["is_formset"]:
                template = whole_uni_formset_template(self.template_pack)
            else:
                template = whole_uni_form_template(self.template_pack)
        return template.render(c)
# {% crispy %} tag
@register.tag(name="crispy")
References crispy_forms.templatetags.crispy_forms_tags.BasicNode.get_render().
Referenced by pip._vendor.rich.progress.ProgressColumn.__call__(), pip._vendor.rich.layout.Layout.__rich_console__(), pip._vendor.rich.spinner.Spinner.__rich_console__(), pip._vendor.rich.spinner.Spinner.__rich_measure__(), django.forms.widgets.Media.__str__(), django.forms.utils.RenderableFieldMixin.as_field_group(), pip._vendor.rich.console.Console.log(), pip._vendor.rich.console.Console.print(), django.templatetags.i18n.BlockTranslateNode.render(), pip._vendor.rich.console.Console.render(), pip._vendor.rich.console.Console.render_lines(), django.db.migrations.writer.OperationWriter.serialize(), and pip._vendor.rich.console.Console.update_screen_lines().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/crispy_forms/templatetags/crispy_forms_tags.py