Read&Watch: pip._vendor.rich.progress.TimeRemainingColumn Class Reference
pip._vendor.rich.progress.TimeRemainingColumn Class Reference
Public Member Functions
__init__ (self, bool compact=False, bool elapsed_when_finished=False, Optional[Column] table_column=None)
Text render (self, "Task" task)
Public Member Functions inherited from pip._vendor.rich.progress.ProgressColumn
None __init__ (self, Optional[Column] table_column=None)
Column get_table_column (self)
RenderableType __call__ (self, "Task" task)
Public Attributes
compact = compact
elapsed_when_finished = elapsed_when_finished
Additional Inherited Members
Static Public Attributes inherited from pip._vendor.rich.progress.ProgressColumn
Optional max_refresh = None
Protected Attributes inherited from pip._vendor.rich.progress.ProgressColumn
_table_column = table_column
dict _renderable_cache = {}
Optional[float] _update_time = None
Detailed Description
Renders estimated time remaining.
Args:
    compact (bool, optional): Render MM:SS when time remaining is less than an hour. Defaults to False.
    elapsed_when_finished (bool, optional): Render time elapsed when the task is finished. Defaults to False.
Definition at line 760 of file progress.py.
Constructor & Destructor Documentation
__init__()
pip._vendor.rich.progress.TimeRemainingColumn.__init__ (self, bool compact = False, bool elapsed_when_finished = False, Optional[Column] table_column = None)
Definition at line 771 of file progress.py.
    ):
        self.compact = compact
        self.elapsed_when_finished = elapsed_when_finished
        super().__init__(table_column=table_column)
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
render()
Text pip._vendor.rich.progress.TimeRemainingColumn.render (self, "Task" task)
Show time remaining.
Reimplemented from pip._vendor.rich.progress.ProgressColumn.
Definition at line 781 of file progress.py.
    def render(self, task: "Task") -> Text:
        """Show time remaining."""
        if self.elapsed_when_finished and task.finished:
            task_time = task.finished_time
            style = "progress.elapsed"
        else:
            task_time = task.time_remaining
            style = "progress.remaining"
        if task.total is None:
            return Text("", style=style)
        if task_time is None:
            return Text("--:--" if self.compact else "-:--:--", style=style)
        # Based on https://github.com/tqdm/tqdm/blob/master/tqdm/std.py
        minutes, seconds = divmod(int(task_time), 60)
        hours, minutes = divmod(minutes, 60)
        if self.compact and not hours:
            formatted = f"{minutes:02d}:{seconds:02d}"
        else:
            formatted = f"{hours:d}:{minutes:02d}:{seconds:02d}"
        return Text(formatted, style=style)
References compact, and elapsed_when_finished.
Referenced by pip._vendor.rich.spinner.Spinner.__rich_console__(), and pip._vendor.rich.spinner.Spinner.__rich_measure__().
Member Data Documentation
compact
pip._vendor.rich.progress.TimeRemainingColumn.compact = compact
Definition at line 777 of file progress.py.
Referenced by sqlparse.filters.reindent.ReindentFilter._process_case(), and render().
elapsed_when_finished
pip._vendor.rich.progress.TimeRemainingColumn.elapsed_when_finished = elapsed_when_finished
Definition at line 778 of file progress.py.
Referenced by render().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/rich/progress.py