Read&Watch: pip._vendor.pyproject_hooks._impl.HookMissing Class Reference
pip._vendor.pyproject_hooks._impl.HookMissing Class Reference
Public Member Functions
__init__ (self, hook_name)
Public Attributes
hook_name = hook_name
Detailed Description
Will be raised on missing hooks (if a fallback can't be used).
Definition at line 37 of file _impl.py.
Constructor & Destructor Documentation
__init__()
pip._vendor.pyproject_hooks._impl.HookMissing.__init__ (self, hook_name)
Definition at line 39 of file _impl.py.
    def __init__(self, hook_name):
        super().__init__(hook_name)
        self.hook_name = hook_name
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Data Documentation
hook_name
pip._vendor.pyproject_hooks._impl.HookMissing.hook_name = hook_name
Definition at line 41 of file _impl.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/pyproject_hooks/_impl.py