Read&Watch: pip._vendor.rich.file_proxy.FileProxy Class Reference
pip._vendor.rich.file_proxy.FileProxy Class Reference
Public Member Functions
None __init__ (self, "Console" console, IO[str] file)
IO[str] rich_proxied_file (self)
Any __getattr__ (self, str name)
int write (self, str text)
None flush (self)
int fileno (self)
Detailed Description
Wraps a file (e.g. sys.stdout) and redirects writes to a console.
Definition at line 11 of file file_proxy.py.
Constructor & Destructor Documentation
__init__()
None pip._vendor.rich.file_proxy.FileProxy.__init__ (self, "Console" console, IO[str] file)
Definition at line 14 of file file_proxy.py.
    def __init__(self, console: "Console", file: IO[str]) -> None:
        self.__console = console
        self.__file = file
        self.__buffer: List[str] = []
        self.__ansi_decoder = AnsiDecoder()
References __ansi_decoder, __buffer, __console, and __file.
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
__getattr__()
Any pip._vendor.rich.file_proxy.FileProxy.__getattr__ (self, str name)
Definition at line 25 of file file_proxy.py.
    def __getattr__(self, name: str) -> Any:
        return getattr(self.__file, name)
References __file.
fileno()
int pip._vendor.rich.file_proxy.FileProxy.fileno (self)
Definition at line 56 of file file_proxy.py.
    def fileno(self) -> int:
        return self.__file.fileno()
References __file, and fileno().
Referenced by fileno().
flush()
None pip._vendor.rich.file_proxy.FileProxy.flush (self)
Definition at line 50 of file file_proxy.py.
    def flush(self) -> None:
        output = "".join(self.__buffer)
        if output:
            self.__console.print(output)
        del self.__buffer[:]
References __buffer, __console, and pip._vendor.rich.print().
Referenced by pip._vendor.pygments.util.UnclosingTextIOWrapper.close().
rich_proxied_file()
IO[str] pip._vendor.rich.file_proxy.FileProxy.rich_proxied_file (self)
Get proxied file.
Definition at line 21 of file file_proxy.py.
    def rich_proxied_file(self) -> IO[str]:
        """Get proxied file."""
        return self.__file
References __file.
write()
int pip._vendor.rich.file_proxy.FileProxy.write (self, str text)
Definition at line 28 of file file_proxy.py.
    def write(self, text: str) -> int:
        if not isinstance(text, str):
            raise TypeError(f"write() argument must be str, not {type(text).__name__}")
        buffer = self.__buffer
        lines: List[str] = []
        while text:
            line, new_line, text = text.partition("\n")
            if new_line:
                lines.append("".join(buffer) + line)
                buffer.clear()
            else:
                buffer.append(line)
                break
        if lines:
            console = self.__console
            with console:
                output = Text("\n").join(
                    self.__ansi_decoder.decode_line(line) for line in lines
                )
                console.print(output)
        return len(text)
References __ansi_decoder, __buffer, and __console.
Referenced by pylint.reporters.ureports.text_writer.TextWriter.default_table(), pylint.reporters.ureports.text_writer.TextWriter.visit_text(), and pylint.reporters.ureports.base_writer.BaseWriter.writeln().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/rich/file_proxy.py