Read&Watch: astroid.constraint.NoneConstraint Class Reference
astroid.constraint.NoneConstraint Class Reference
Public Member Functions
Self|None match (cls, _NameNodes node, nodes.NodeNG expr, bool negate=False)
bool satisfied_by (self, InferenceResult inferred)
Public Member Functions inherited from astroid.constraint.Constraint
None __init__ (self, nodes.NodeNG node, bool negate)
Static Public Attributes
nodes CONST_NONE = nodes.Const(None)
Additional Inherited Members
Public Attributes inherited from astroid.constraint.Constraint
node = node
negate = negate
Detailed Description
Represents an "is None" or "is not None" constraint.
Definition at line 52 of file constraint.py.
Member Function Documentation
match()
Self | None astroid.constraint.NoneConstraint.match (cls, _NameNodes node, nodes.NodeNG expr, bool negate = False)
Return a new constraint for node matched from expr, if expr matches
the constraint pattern.
Negate the constraint based on the value of negate.
Reimplemented from astroid.constraint.Constraint.
Definition at line 58 of file constraint.py.
    ) -> Self | None:
        """Return a new constraint for node matched from expr, if expr matches
        the constraint pattern.
        Negate the constraint based on the value of negate.
        """
        if isinstance(expr, nodes.Compare) and len(expr.ops) == 1:
            left = expr.left
            op, right = expr.ops[0]
            if op in {"is", "is not"} and (
                _matches(left, node) and _matches(right, cls.CONST_NONE)
            ):
                negate = (op == "is" and negate) or (op == "is not" and not negate)
                return cls(node=node, negate=negate)
        return None
References astroid.constraint._matches(), and CONST_NONE.
satisfied_by()
bool astroid.constraint.NoneConstraint.satisfied_by (self, InferenceResult inferred)
Return True if this constraint is satisfied by the given inferred value.
Reimplemented from astroid.constraint.Constraint.
Definition at line 77 of file constraint.py.
    def satisfied_by(self, inferred: InferenceResult) -> bool:
        """Return True if this constraint is satisfied by the given inferred value."""
        # Assume true if uninferable
        if isinstance(inferred, util.UninferableBase):
            return True
        # Return the XOR of self.negate and matches(inferred, self.CONST_NONE)
        return self.negate ^ _matches(inferred, self.CONST_NONE)
References astroid.constraint._matches(), CONST_NONE, and astroid.constraint.Constraint.negate.
Member Data Documentation
CONST_NONE
astroid.constraint.NoneConstraint.CONST_NONE = nodes.Const(None) static
Definition at line 55 of file constraint.py.
Referenced by match(), and satisfied_by().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/astroid/constraint.py