Read&Watch: pip._vendor.distlib.version.NormalizedMatcher Class Reference
pip._vendor.distlib.version.NormalizedMatcher Class Reference
Protected Member Functions
_adjust_local (self, version, constraint, prefix)
_match_lt (self, version, constraint, prefix)
_match_gt (self, version, constraint, prefix)
_match_le (self, version, constraint, prefix)
_match_ge (self, version, constraint, prefix)
_match_eq (self, version, constraint, prefix)
_match_arbitrary (self, version, constraint, prefix)
_match_ne (self, version, constraint, prefix)
_match_compatible (self, version, constraint, prefix)
Protected Member Functions inherited from pip._vendor.distlib.version.Matcher
_check_compatible (self, other)
Additional Inherited Members
Public Member Functions inherited from pip._vendor.distlib.version.Matcher
parse_requirement (self, s)
__init__ (self, s)
match (self, version)
exact_version (self)
__eq__ (self, other)
__ne__ (self, other)
__hash__ (self)
__repr__ (self)
__str__ (self)
Public Attributes inherited from pip._vendor.distlib.version.Matcher
name = r.name
key = self.name.lower()
Static Public Attributes inherited from pip._vendor.distlib.version.Matcher
version_class = None
Protected Attributes inherited from pip._vendor.distlib.version.Matcher
_string = s.strip()
_parts = tuple(clist)
Static Protected Attributes inherited from pip._vendor.distlib.version.Matcher
dict _operators
Detailed Description
Definition at line 303 of file version.py.
Member Function Documentation
_adjust_local()
pip._vendor.distlib.version.NormalizedMatcher._adjust_local (self, version, constraint, prefix) protected
Definition at line 318 of file version.py.
    def _adjust_local(self, version, constraint, prefix):
        if prefix:
            strip_local = '+' not in constraint and version._parts[-1]
        else:
            # both constraint and version are
            # NormalizedVersion instances.
            # If constraint does not have a local component,
            # ensure the version doesn't, either.
            strip_local = not constraint._parts[-1] and version._parts[-1]
        if strip_local:
            s = version._string.split('+', 1)[0]
            version = self.version_class(s)
        return version, constraint
References pip._vendor.distlib.version.Matcher.version_class.
Referenced by _match_compatible(), _match_eq(), _match_ge(), _match_gt(), _match_le(), _match_lt(), and _match_ne().
_match_arbitrary()
pip._vendor.distlib.version.NormalizedMatcher._match_arbitrary (self, version, constraint, prefix) protected
Definition at line 364 of file version.py.
    def _match_arbitrary(self, version, constraint, prefix):
        return str(version) == str(constraint)
_match_compatible()
pip._vendor.distlib.version.NormalizedMatcher._match_compatible (self, version, constraint, prefix) protected
Definition at line 375 of file version.py.
    def _match_compatible(self, version, constraint, prefix):
        version, constraint = self._adjust_local(version, constraint, prefix)
        if version == constraint:
            return True
        if version < constraint:
            return False
#        if not prefix:
#            return True
        release_clause = constraint._release_clause
        if len(release_clause) > 1:
            release_clause = release_clause[:-1]
        pfx = '.'.join([str(i) for i in release_clause])
        return _match_prefix(version, pfx)
References _adjust_local(), and pip._vendor.distlib.version._match_prefix().
_match_eq()
pip._vendor.distlib.version.NormalizedMatcher._match_eq (self, version, constraint, prefix) protected
Definition at line 356 of file version.py.
    def _match_eq(self, version, constraint, prefix):
        version, constraint = self._adjust_local(version, constraint, prefix)
        if not prefix:
            result = (version == constraint)
        else:
            result = _match_prefix(version, constraint)
        return result
References _adjust_local(), and pip._vendor.distlib.version._match_prefix().
_match_ge()
pip._vendor.distlib.version.NormalizedMatcher._match_ge (self, version, constraint, prefix) protected
Definition at line 352 of file version.py.
    def _match_ge(self, version, constraint, prefix):
        version, constraint = self._adjust_local(version, constraint, prefix)
        return version >= constraint
References _adjust_local().
_match_gt()
pip._vendor.distlib.version.NormalizedMatcher._match_gt (self, version, constraint, prefix) protected
Definition at line 340 of file version.py.
    def _match_gt(self, version, constraint, prefix):
        version, constraint = self._adjust_local(version, constraint, prefix)
        if version <= constraint:
            return False
        release_clause = constraint._release_clause
        pfx = '.'.join([str(i) for i in release_clause])
        return not _match_prefix(version, pfx)
References _adjust_local(), and pip._vendor.distlib.version._match_prefix().
_match_le()
pip._vendor.distlib.version.NormalizedMatcher._match_le (self, version, constraint, prefix) protected
Definition at line 348 of file version.py.
    def _match_le(self, version, constraint, prefix):
        version, constraint = self._adjust_local(version, constraint, prefix)
        return version <= constraint
References _adjust_local().
_match_lt()
pip._vendor.distlib.version.NormalizedMatcher._match_lt (self, version, constraint, prefix) protected
Definition at line 332 of file version.py.
    def _match_lt(self, version, constraint, prefix):
        version, constraint = self._adjust_local(version, constraint, prefix)
        if version >= constraint:
            return False
        release_clause = constraint._release_clause
        pfx = '.'.join([str(i) for i in release_clause])
        return not _match_prefix(version, pfx)
References _adjust_local(), and pip._vendor.distlib.version._match_prefix().
_match_ne()
pip._vendor.distlib.version.NormalizedMatcher._match_ne (self, version, constraint, prefix) protected
Definition at line 367 of file version.py.
    def _match_ne(self, version, constraint, prefix):
        version, constraint = self._adjust_local(version, constraint, prefix)
        if not prefix:
            result = (version != constraint)
        else:
            result = not _match_prefix(version, constraint)
        return result
References _adjust_local(), and pip._vendor.distlib.version._match_prefix().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/distlib/version.py