Read&Watch: django.db.utils.ConnectionHandler Class Reference
django.db.utils.ConnectionHandler Class Reference
Public Member Functions
configure_settings (self, databases)
databases (self)
create_connection (self, alias)
Public Member Functions inherited from django.utils.connection.BaseConnectionHandler
__init__ (self, settings=None)
settings (self)
__getitem__ (self, alias)
__setitem__ (self, key, value)
__delitem__ (self, key)
__iter__ (self)
all (self, initialized_only=False)
close_all (self)
Additional Inherited Members
Public Attributes inherited from django.utils.connection.BaseConnectionHandler
settings
Static Public Attributes inherited from django.utils.connection.BaseConnectionHandler
settings_name = None
exception_class = ConnectionDoesNotExist
bool thread_critical = False
Protected Attributes inherited from django.utils.connection.BaseConnectionHandler
_settings = settings
_connections = Local(self.thread_critical)
Detailed Description
Definition at line 138 of file utils.py.
Member Function Documentation
configure_settings()
django.db.utils.ConnectionHandler.configure_settings (self, databases)
Reimplemented from django.utils.connection.BaseConnectionHandler.
Definition at line 147 of file utils.py.
    def configure_settings(self, databases):
        databases = super().configure_settings(databases)
        if databases == {}:
            databases[DEFAULT_DB_ALIAS] = {"ENGINE": "django.db.backends.dummy"}
        elif DEFAULT_DB_ALIAS not in databases:
            raise ImproperlyConfigured(
                f"You must define a '{DEFAULT_DB_ALIAS}' database."
            )
        elif databases[DEFAULT_DB_ALIAS] == {}:
            databases[DEFAULT_DB_ALIAS]["ENGINE"] = "django.db.backends.dummy"
        # Configure default settings.
        for conn in databases.values():
            conn.setdefault("ATOMIC_REQUESTS", False)
            conn.setdefault("AUTOCOMMIT", True)
            conn.setdefault("ENGINE", "django.db.backends.dummy")
            if conn["ENGINE"] == "django.db.backends." or not conn["ENGINE"]:
                conn["ENGINE"] = "django.db.backends.dummy"
            conn.setdefault("CONN_MAX_AGE", 0)
            conn.setdefault("CONN_HEALTH_CHECKS", False)
            conn.setdefault("OPTIONS", {})
            conn.setdefault("TIME_ZONE", None)
            for setting in ["NAME", "USER", "PASSWORD", "HOST", "PORT"]:
                conn.setdefault(setting, "")
            test_settings = conn.setdefault("TEST", {})
            default_test_settings = [
                ("CHARSET", None),
                ("COLLATION", None),
                ("MIGRATE", True),
                ("MIRROR", None),
                ("NAME", None),
            ]
            for key, value in default_test_settings:
                test_settings.setdefault(key, value)
        return databases
References configure_settings().
Referenced by configure_settings(), and django.utils.connection.BaseConnectionHandler.settings().
create_connection()
django.db.utils.ConnectionHandler.create_connection (self, alias)
Reimplemented from django.utils.connection.BaseConnectionHandler.
Definition at line 191 of file utils.py.
    def create_connection(self, alias):
        db = self.settings[alias]
        backend = load_backend(db["ENGINE"])
        return backend.DatabaseWrapper(db, alias)
References django.db.utils.load_backend(), and django.utils.connection.BaseConnectionHandler.settings.
databases()
django.db.utils.ConnectionHandler.databases (self)
Definition at line 185 of file utils.py.
    def databases(self):
        # Maintained for backward compatibility as some 3rd party packages have
        # made use of this private API in the past. It is no longer used within
        # Django itself.
        return self.settings
References django.utils.connection.BaseConnectionHandler.settings.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/db/utils.py