Read&Watch: django.contrib.redirects.models.Redirect.Meta Class Reference
django.contrib.redirects.models.Redirect.Meta Class Reference
Static Public Attributes
verbose_name = _("redirect")
verbose_name_plural = _("redirects")
str db_table = "django_redirect"
list unique_together = [["site", "old_path"]]
list ordering = ["old_path"]
Detailed Description
Definition at line 27 of file models.py.
Member Data Documentation
db_table
str django.contrib.redirects.models.Redirect.Meta.db_table = "django_redirect" static
Definition at line 30 of file models.py.
Referenced by django.db.models.fields.related.ManyToManyField._get_m2m_db_table(), django.db.models.fields.related.ManyToManyField.deconstruct(), and django.db.models.options.Options.setup_proxy().
ordering
list django.contrib.redirects.models.Redirect.Meta.ordering = ["old_path"] static
Definition at line 32 of file models.py.
Referenced by django.db.models.options.Options._prepare(), django.views.generic.dates.BaseDateListView.get_ordering(), and django.views.generic.list.MultipleObjectMixin.get_ordering().
unique_together
list django.contrib.redirects.models.Redirect.Meta.unique_together = [["site", "old_path"]] static
Definition at line 31 of file models.py.
verbose_name
django.contrib.redirects.models.Redirect.Meta.verbose_name = _("redirect") static
Definition at line 28 of file models.py.
Referenced by django.db.models.fields.Field.formfield(), django.db.models.fields.related.RelatedField.set_attributes_from_rel(), and django.db.models.options.Options.verbose_name_raw().
verbose_name_plural
django.contrib.redirects.models.Redirect.Meta.verbose_name_plural = _("redirects") static
Definition at line 29 of file models.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/redirects/models.py