Read&Watch: colorama.winterm.WinTerm Class Reference
colorama.winterm.WinTerm Class Reference
Public Member Functions
__init__ (self)
get_attrs (self)
set_attrs (self, value)
reset_all (self, on_stderr=None)
fore (self, fore=None, light=False, on_stderr=False)
back (self, back=None, light=False, on_stderr=False)
style (self, style=None, on_stderr=False)
set_console (self, attrs=None, on_stderr=False)
get_position (self, handle)
set_cursor_position (self, position=None, on_stderr=False)
cursor_adjust (self, x, y, on_stderr=False)
erase_screen (self, mode=0, on_stderr=False)
erase_line (self, mode=0, on_stderr=False)
set_title (self, title)
Protected Attributes
_default = win32.GetConsoleScreenBufferInfo(win32.STDOUT).wAttributes
_default_fore = self._fore
_default_back = self._back
_default_style = self._style
int _light = 0
int _fore = value & 7
tuple _back = (value >> 4) & 7
_style = value & (WinStyle.BRIGHT | WinStyle.BRIGHT_BACKGROUND)
Detailed Description
Definition at line 28 of file winterm.py.
Constructor & Destructor Documentation
__init__()
colorama.winterm.WinTerm.__init__ (self)
Definition at line 30 of file winterm.py.
    def __init__(self):
        self._default = win32.GetConsoleScreenBufferInfo(win32.STDOUT).wAttributes
        self.set_attrs(self._default)
        self._default_fore = self._fore
        self._default_back = self._back
        self._default_style = self._style
        # In order to emulate LIGHT_EX in windows, we borrow the BRIGHT style.
        # So that LIGHT_EX colors and BRIGHT style do not clobber each other,
        # we track them separately, since LIGHT_EX is overwritten by Fore/Back
        # and BRIGHT is overwritten by Style codes.
        self._light = 0
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
back()
colorama.winterm.WinTerm.back (self, back = None, light = False, on_stderr = False)
Definition at line 66 of file winterm.py.
    def back(self, back=None, light=False, on_stderr=False):
        if back is None:
            back = self._default_back
        self._back = back
        # Emulate LIGHT_EX with BRIGHT_BACKGROUND Style
        if light:
            self._light |= WinStyle.BRIGHT_BACKGROUND
        else:
            self._light &= ~WinStyle.BRIGHT_BACKGROUND
        self.set_console(on_stderr=on_stderr)
References _back, _default_back, _light, and set_console().
cursor_adjust()
colorama.winterm.WinTerm.cursor_adjust (self, x, y, on_stderr = False)
Definition at line 109 of file winterm.py.
    def cursor_adjust(self, x, y, on_stderr=False):
        handle = win32.STDOUT
        if on_stderr:
            handle = win32.STDERR
        position = self.get_position(handle)
        adjusted_position = (position.Y + y, position.X + x)
        win32.SetConsoleCursorPosition(handle, adjusted_position, adjust=False)
References get_position().
erase_line()
colorama.winterm.WinTerm.erase_line (self, mode = 0, on_stderr = False)
Definition at line 149 of file winterm.py.
    def erase_line(self, mode=0, on_stderr=False):
        # 0 should clear from the cursor to the end of the line.
        # 1 should clear from the cursor to the beginning of the line.
        # 2 should clear the entire line.
        handle = win32.STDOUT
        if on_stderr:
            handle = win32.STDERR
        csbi = win32.GetConsoleScreenBufferInfo(handle)
        if mode == 0:
            from_coord = csbi.dwCursorPosition
            cells_to_erase = csbi.dwSize.X - csbi.dwCursorPosition.X
        elif mode == 1:
            from_coord = win32.COORD(0, csbi.dwCursorPosition.Y)
            cells_to_erase = csbi.dwCursorPosition.X
        elif mode == 2:
            from_coord = win32.COORD(0, csbi.dwCursorPosition.Y)
            cells_to_erase = csbi.dwSize.X
        else:
            # invalid mode
            return
        # fill the entire screen with blanks
        win32.FillConsoleOutputCharacter(handle, ' ', cells_to_erase, from_coord)
        # now set the buffer's attributes accordingly
        win32.FillConsoleOutputAttribute(handle, self.get_attrs(), cells_to_erase, from_coord)
References get_attrs().
erase_screen()
colorama.winterm.WinTerm.erase_screen (self, mode = 0, on_stderr = False)
Definition at line 117 of file winterm.py.
    def erase_screen(self, mode=0, on_stderr=False):
        # 0 should clear from the cursor to the end of the screen.
        # 1 should clear from the cursor to the beginning of the screen.
        # 2 should clear the entire screen, and move cursor to (1,1)
        handle = win32.STDOUT
        if on_stderr:
            handle = win32.STDERR
        csbi = win32.GetConsoleScreenBufferInfo(handle)
        # get the number of character cells in the current buffer
        cells_in_screen = csbi.dwSize.X * csbi.dwSize.Y
        # get number of character cells before current cursor position
        cells_before_cursor = csbi.dwSize.X * csbi.dwCursorPosition.Y + csbi.dwCursorPosition.X
        if mode == 0:
            from_coord = csbi.dwCursorPosition
            cells_to_erase = cells_in_screen - cells_before_cursor
        elif mode == 1:
            from_coord = win32.COORD(0, 0)
            cells_to_erase = cells_before_cursor
        elif mode == 2:
            from_coord = win32.COORD(0, 0)
            cells_to_erase = cells_in_screen
        else:
            # invalid mode
            return
        # fill the entire screen with blanks
        win32.FillConsoleOutputCharacter(handle, ' ', cells_to_erase, from_coord)
        # now set the buffer's attributes accordingly
        win32.FillConsoleOutputAttribute(handle, self.get_attrs(), cells_to_erase, from_coord)
        if mode == 2:
            # put the cursor where needed
            win32.SetConsoleCursorPosition(handle, (1, 1))
References get_attrs().
fore()
colorama.winterm.WinTerm.fore (self, fore = None, light = False, on_stderr = False)
Definition at line 55 of file winterm.py.
    def fore(self, fore=None, light=False, on_stderr=False):
        if fore is None:
            fore = self._default_fore
        self._fore = fore
        # Emulate LIGHT_EX with BRIGHT Style
        if light:
            self._light |= WinStyle.BRIGHT
        else:
            self._light &= ~WinStyle.BRIGHT
        self.set_console(on_stderr=on_stderr)
References _default_fore, _fore, _light, and set_console().
get_attrs()
colorama.winterm.WinTerm.get_attrs (self)
Definition at line 42 of file winterm.py.
    def get_attrs(self):
        return self._fore + self._back * 16 + (self._style | self._light)
References _back, _fore, _light, and _style.
Referenced by erase_line(), erase_screen(), pylint.pyreverse.diagrams.ClassDiagram.extract_relationships(), and set_console().
get_position()
colorama.winterm.WinTerm.get_position (self, handle)
Definition at line 91 of file winterm.py.
    def get_position(self, handle):
        position = win32.GetConsoleScreenBufferInfo(handle).dwCursorPosition
        # Because Windows coordinates are 0-based,
        # and win32.SetConsoleCursorPosition expects 1-based.
        position.X += 1
        position.Y += 1
        return position
Referenced by cursor_adjust().
reset_all()
colorama.winterm.WinTerm.reset_all (self, on_stderr = None)
Definition at line 50 of file winterm.py.
    def reset_all(self, on_stderr=None):
        self.set_attrs(self._default)
        self.set_console(attrs=self._default)
        self._light = 0
References _default, _light, set_attrs(), and set_console().
set_attrs()
colorama.winterm.WinTerm.set_attrs (self, value)
Definition at line 45 of file winterm.py.
    def set_attrs(self, value):
        self._fore = value & 7
        self._back = (value >> 4) & 7
        self._style = value & (WinStyle.BRIGHT | WinStyle.BRIGHT_BACKGROUND)
Referenced by reset_all().
set_console()
colorama.winterm.WinTerm.set_console (self, attrs = None, on_stderr = False)
Definition at line 83 of file winterm.py.
    def set_console(self, attrs=None, on_stderr=False):
        if attrs is None:
            attrs = self.get_attrs()
        handle = win32.STDOUT
        if on_stderr:
            handle = win32.STDERR
        win32.SetConsoleTextAttribute(handle, attrs)
References get_attrs().
Referenced by back(), fore(), reset_all(), and style().
set_cursor_position()
colorama.winterm.WinTerm.set_cursor_position (self, position = None, on_stderr = False)
Definition at line 99 of file winterm.py.
    def set_cursor_position(self, position=None, on_stderr=False):
        if position is None:
            # I'm not currently tracking the position, so there is no default.
            # position = self.get_position()
            return
        handle = win32.STDOUT
        if on_stderr:
            handle = win32.STDERR
        win32.SetConsoleCursorPosition(handle, position)
set_title()
colorama.winterm.WinTerm.set_title (self, title)
Definition at line 174 of file winterm.py.
    def set_title(self, title):
        win32.SetConsoleTitle(title)
style()
colorama.winterm.WinTerm.style (self, style = None, on_stderr = False)
Definition at line 77 of file winterm.py.
    def style(self, style=None, on_stderr=False):
        if style is None:
            style = self._default_style
        self._style = style
        self.set_console(on_stderr=on_stderr)
References _default_style, _style, and set_console().
Member Data Documentation
_back
tuple colorama.winterm.WinTerm._back = (value >> 4) & 7 protected
Definition at line 47 of file winterm.py.
Referenced by back(), and get_attrs().
_default
colorama.winterm.WinTerm._default = win32.GetConsoleScreenBufferInfo(win32.STDOUT).wAttributes protected
Definition at line 31 of file winterm.py.
Referenced by pip._vendor.msgpack.fallback.Packer._pack(), and reset_all().
_default_back
colorama.winterm.WinTerm._default_back = self._back protected
Definition at line 34 of file winterm.py.
Referenced by back(), and pip._vendor.rich._win32_console.LegacyWindowsTerm.write_styled().
_default_fore
colorama.winterm.WinTerm._default_fore = self._fore protected
Definition at line 33 of file winterm.py.
Referenced by fore(), and pip._vendor.rich._win32_console.LegacyWindowsTerm.write_styled().
_default_style
colorama.winterm.WinTerm._default_style = self._style protected
Definition at line 35 of file winterm.py.
Referenced by style().
_fore
int colorama.winterm.WinTerm._fore = value & 7 protected
Definition at line 46 of file winterm.py.
Referenced by fore(), and get_attrs().
_light
colorama.winterm.WinTerm._light = 0 protected
Definition at line 40 of file winterm.py.
Referenced by back(), fore(), get_attrs(), and reset_all().
_style
colorama.winterm.WinTerm._style = value & (WinStyle.BRIGHT | WinStyle.BRIGHT_BACKGROUND) protected
Definition at line 48 of file winterm.py.
Referenced by get_attrs(), and style().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/colorama/winterm.py