Read&Watch: pip._vendor.urllib3.response.MultiDecoder Class Reference
pip._vendor.urllib3.response.MultiDecoder Class Reference
Public Member Functions
__init__ (self, modes)
flush (self)
decompress (self, data)
Protected Attributes
list _decoders = [_get_decoder(m.strip()) for m in modes.split(",")]
Detailed Description
From RFC7231:
    If one or more encodings have been applied to a representation, the
    sender that applied the encodings MUST generate a Content-Encoding
    header field that lists the content codings in the order in which
    they were applied.
Definition at line 123 of file response.py.
Constructor & Destructor Documentation
__init__()
pip._vendor.urllib3.response.MultiDecoder.__init__ (self, modes)
Definition at line 132 of file response.py.
    def __init__(self, modes):
        self._decoders = [_get_decoder(m.strip()) for m in modes.split(",")]
Member Function Documentation
decompress()
pip._vendor.urllib3.response.MultiDecoder.decompress (self, data)
Definition at line 138 of file response.py.
    def decompress(self, data):
        for d in reversed(self._decoders):
            data = d.decompress(data)
        return data
References _decoders.
Referenced by urllib3.response.DeflateDecoder.decompress().
flush()
pip._vendor.urllib3.response.MultiDecoder.flush (self)
Definition at line 135 of file response.py.
    def flush(self):
        return self._decoders[0].flush()
References _decoders, and flush().
Referenced by pip._vendor.pygments.util.UnclosingTextIOWrapper.close(), and flush().
Member Data Documentation
_decoders
pip._vendor.urllib3.response.MultiDecoder._decoders = [_get_decoder(m.strip()) for m in modes.split(",")] protected
Definition at line 133 of file response.py.
Referenced by decompress(), urllib3.response.MultiDecoder.decompress(), flush(), and urllib3.response.MultiDecoder.flush().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/urllib3/response.py