Read&Watch: PIL.PngImagePlugin._idat Class Reference
PIL.PngImagePlugin._idat Class Reference
Public Member Functions
None __init__ (self, IO[bytes] fp, Callable[..., None] chunk)
None write (self, bytes data)
Public Attributes
fp = fp
chunk = chunk
Detailed Description
Definition at line 1124 of file PngImagePlugin.py.
Constructor & Destructor Documentation
__init__()
None PIL.PngImagePlugin._idat.__init__ (self, IO[bytes] fp, Callable[..., None] chunk)
Definition at line 1127 of file PngImagePlugin.py.
    def __init__(self, fp: IO[bytes], chunk: Callable[..., None]) -> None:
        self.fp = fp
        self.chunk = chunk
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
write()
None PIL.PngImagePlugin._idat.write (self, bytes data)
Definition at line 1131 of file PngImagePlugin.py.
    def write(self, data: bytes) -> None:
        self.chunk(self.fp, b"IDAT", data)
Referenced by pylint.reporters.ureports.text_writer.TextWriter.default_table(), pylint.reporters.ureports.text_writer.TextWriter.visit_text(), and pylint.reporters.ureports.base_writer.BaseWriter.writeln().
Member Data Documentation
chunk
PIL.PngImagePlugin._idat.chunk = chunk
Definition at line 1129 of file PngImagePlugin.py.
fp
PIL.PngImagePlugin._idat.fp = fp
Definition at line 1128 of file PngImagePlugin.py.
Referenced by PIL.PSDraw.PSDraw.begin_document(), PIL.PSDraw.PSDraw.end_document(), PIL.PSDraw.PSDraw.image(), PIL.PSDraw.PSDraw.line(), PIL.PSDraw.PSDraw.rectangle(), PIL.PSDraw.PSDraw.setfont(), and PIL.PSDraw.PSDraw.text().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/PIL/PngImagePlugin.py