Read&Watch: django.core.servers.basehttp.WSGIServer Class Reference
django.core.servers.basehttp.WSGIServer Class Reference
Public Member Functions
__init__ (self, *args, ipv6=False, allow_reuse_address=True, **kwargs)
handle_error (self, request, client_address)
Public Attributes
address_family = socket.AF_INET6
allow_reuse_address = allow_reuse_address
Static Public Attributes
int request_queue_size = 10
Detailed Description
BaseHTTPServer that implements the Python WSGI protocol
Definition at line 68 of file basehttp.py.
Constructor & Destructor Documentation
__init__()
django.core.servers.basehttp.WSGIServer.__init__ (self, * args, ipv6 = False, allow_reuse_address = True, ** kwargs)
Definition at line 73 of file basehttp.py.
    def __init__(self, *args, ipv6=False, allow_reuse_address=True, **kwargs):
        if ipv6:
            self.address_family = socket.AF_INET6
        self.allow_reuse_address = allow_reuse_address
        super().__init__(*args, **kwargs)
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
handle_error()
django.core.servers.basehttp.WSGIServer.handle_error (self, request, client_address)
Definition at line 79 of file basehttp.py.
    def handle_error(self, request, client_address):
        if is_broken_pipe_error():
            logger.info("- Broken pipe from %s", client_address)
        else:
            super().handle_error(request, client_address)
References handle_error(), and django.core.servers.basehttp.is_broken_pipe_error().
Referenced by handle_error().
Member Data Documentation
address_family
django.core.servers.basehttp.WSGIServer.address_family = socket.AF_INET6
Definition at line 75 of file basehttp.py.
allow_reuse_address
django.core.servers.basehttp.WSGIServer.allow_reuse_address = allow_reuse_address
Definition at line 76 of file basehttp.py.
request_queue_size
int django.core.servers.basehttp.WSGIServer.request_queue_size = 10 static
Definition at line 71 of file basehttp.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/core/servers/basehttp.py