Read&Watch: pip._vendor.pygments.filters.GobbleFilter Class Reference
pip._vendor.pygments.filters.GobbleFilter Class Reference
Public Member Functions
__init__ (self, **options)
gobble (self, value, left)
filter (self, lexer, stream)
Public Member Functions inherited from pip._vendor.pygments.filter.Filter
__init__ (self, **options)
Public Attributes
n = get_int_opt(options, 'n', 0)
Public Attributes inherited from pip._vendor.pygments.filter.Filter
options = options
Detailed Description
Gobbles source code lines (eats initial characters).
This filter drops the first ``n`` characters off every line of code.  This
may be useful when the source code fed to the lexer is indented by a fixed
amount of space that isn't desired in the output.
Options accepted:
`n` : int
   The number of characters to gobble.
.. versionadded:: 1.2
Definition at line 868 of file __init__.py.
Constructor & Destructor Documentation
__init__()
pip._vendor.pygments.filters.GobbleFilter.__init__ (self, ** options)
Definition at line 882 of file __init__.py.
    def __init__(self, **options):
        Filter.__init__(self, **options)
        self.n = get_int_opt(options, 'n', 0)
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
filter()
pip._vendor.pygments.filters.GobbleFilter.filter (self, lexer, stream)
Reimplemented from pip._vendor.pygments.filter.Filter.
Definition at line 892 of file __init__.py.
    def filter(self, lexer, stream):
        n = self.n
        left = n  # How many characters left to gobble.
        for ttype, value in stream:
            # Remove ``left`` tokens from first line, ``n`` from all others.
            parts = value.split('\n')
            (parts[0], left) = self.gobble(parts[0], left)
            for i in range(1, len(parts)):
                (parts[i], left) = self.gobble(parts[i], n)
            value = '\n'.join(parts)
            if value != '':
                yield ttype, value
References gobble(), and n.
gobble()
pip._vendor.pygments.filters.GobbleFilter.gobble (self, value, left)
Definition at line 886 of file __init__.py.
    def gobble(self, value, left):
        if left < len(value):
            return value[left:], 0
        else:
            return '', left - len(value)
Referenced by filter().
Member Data Documentation
n
pip._vendor.pygments.filters.GobbleFilter.n = get_int_opt(options, 'n', 0)
Definition at line 884 of file __init__.py.
Referenced by filter(), sqlparse.filters.aligned_indent.AlignedIndentFilter.nl(), and sqlparse.filters.reindent.ReindentFilter.nl().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/pygments/filters/__init__.py