Read&Watch: pip._internal.resolution.resolvelib.base.Candidate Class Reference
pip._internal.resolution.resolvelib.base.Candidate Class Reference
Public Member Functions
NormalizedName project_name (self)
str name (self)
Version version (self)
bool is_installed (self)
bool is_editable (self)
Optional[Link] source_link (self)
Iterable[Optional[Requirement]] iter_dependencies (self, bool with_requires)
Optional[InstallRequirement] get_install_requirement (self)
str format_for_error (self)
Detailed Description
Definition at line 96 of file base.py.
Member Function Documentation
format_for_error()
str pip._internal.resolution.resolvelib.base.Candidate.format_for_error (self)
Reimplemented in pip._internal.resolution.resolvelib.candidates._InstallRequirementBackedCandidate, pip._internal.resolution.resolvelib.candidates.AlreadyInstalledCandidate, pip._internal.resolution.resolvelib.candidates.ExtrasCandidate, and pip._internal.resolution.resolvelib.candidates.RequiresPythonCandidate.
Definition at line 138 of file base.py.
    def format_for_error(self) -> str:
        raise NotImplementedError("Subclass should override")
get_install_requirement()
Optional[InstallRequirement] pip._internal.resolution.resolvelib.base.Candidate.get_install_requirement (self)
Reimplemented in pip._internal.resolution.resolvelib.candidates._InstallRequirementBackedCandidate, pip._internal.resolution.resolvelib.candidates.AlreadyInstalledCandidate, pip._internal.resolution.resolvelib.candidates.ExtrasCandidate, and pip._internal.resolution.resolvelib.candidates.RequiresPythonCandidate.
Definition at line 135 of file base.py.
    def get_install_requirement(self) -> Optional[InstallRequirement]:
        raise NotImplementedError("Override in subclass")
is_editable()
bool pip._internal.resolution.resolvelib.base.Candidate.is_editable (self)
Reimplemented in pip._internal.resolution.resolvelib.candidates.AlreadyInstalledCandidate, and pip._internal.resolution.resolvelib.candidates.ExtrasCandidate.
Definition at line 125 of file base.py.
    def is_editable(self) -> bool:
        raise NotImplementedError("Override in subclass")
is_installed()
bool pip._internal.resolution.resolvelib.base.Candidate.is_installed (self)
Reimplemented in pip._internal.resolution.resolvelib.candidates.ExtrasCandidate.
Definition at line 121 of file base.py.
    def is_installed(self) -> bool:
        raise NotImplementedError("Override in subclass")
iter_dependencies()
Iterable[Optional[Requirement]] pip._internal.resolution.resolvelib.base.Candidate.iter_dependencies (self, bool with_requires)
Reimplemented in pip._internal.resolution.resolvelib.candidates._InstallRequirementBackedCandidate, pip._internal.resolution.resolvelib.candidates.AlreadyInstalledCandidate, pip._internal.resolution.resolvelib.candidates.ExtrasCandidate, and pip._internal.resolution.resolvelib.candidates.RequiresPythonCandidate.
Definition at line 132 of file base.py.
    def iter_dependencies(self, with_requires: bool) -> Iterable[Optional[Requirement]]:
        raise NotImplementedError("Override in subclass")
name()
str pip._internal.resolution.resolvelib.base.Candidate.name (self)
The name identifying this candidate in the resolver.
This is different from ``project_name`` if this candidate contains
extras, where ``project_name`` would not contain the ``[...]`` part.
Reimplemented in pip._internal.resolution.resolvelib.candidates._InstallRequirementBackedCandidate, pip._internal.resolution.resolvelib.candidates.AlreadyInstalledCandidate, pip._internal.resolution.resolvelib.candidates.ExtrasCandidate, and pip._internal.resolution.resolvelib.candidates.RequiresPythonCandidate.
Definition at line 108 of file base.py.
    def name(self) -> str:
        """The name identifying this candidate in the resolver.
        This is different from ``project_name`` if this candidate contains
        extras, where ``project_name`` would not contain the ``[...]`` part.
        """
        raise NotImplementedError("Override in subclass")
Referenced by pip._vendor.rich.markup.Tag.__str__(), pip._vendor.distro.distro.LinuxDistribution.linux_distribution(), and astroid.nodes.scoped_nodes.mixin.LocalsDictNodeNG.qname().
project_name()
NormalizedName pip._internal.resolution.resolvelib.base.Candidate.project_name (self)
The "project name" of the candidate.
This is different from ``name`` if this candidate contains extras,
in which case ``name`` would contain the ``[...]`` part, while this
refers to the name of the project.
Reimplemented in pip._internal.resolution.resolvelib.candidates._InstallRequirementBackedCandidate, pip._internal.resolution.resolvelib.candidates.AlreadyInstalledCandidate, pip._internal.resolution.resolvelib.candidates.ExtrasCandidate, and pip._internal.resolution.resolvelib.candidates.RequiresPythonCandidate.
Definition at line 98 of file base.py.
    def project_name(self) -> NormalizedName:
        """The "project name" of the candidate.
        This is different from ``name`` if this candidate contains extras,
        in which case ``name`` would contain the ``[...]`` part, while this
        refers to the name of the project.
        """
        raise NotImplementedError("Override in subclass")
Referenced by pip._internal.resolution.resolvelib.candidates._InstallRequirementBackedCandidate.name(), and pip._internal.resolution.resolvelib.candidates.AlreadyInstalledCandidate.name().
source_link()
Optional[Link] pip._internal.resolution.resolvelib.base.Candidate.source_link (self)
Reimplemented in pip._internal.resolution.resolvelib.candidates._InstallRequirementBackedCandidate, and pip._internal.resolution.resolvelib.candidates.ExtrasCandidate.
Definition at line 129 of file base.py.
    def source_link(self) -> Optional[Link]:
        raise NotImplementedError("Override in subclass")
version()
Version pip._internal.resolution.resolvelib.base.Candidate.version (self)
Reimplemented in pip._internal.resolution.resolvelib.candidates._InstallRequirementBackedCandidate, pip._internal.resolution.resolvelib.candidates.AlreadyInstalledCandidate, pip._internal.resolution.resolvelib.candidates.ExtrasCandidate, and pip._internal.resolution.resolvelib.candidates.RequiresPythonCandidate.
Definition at line 117 of file base.py.
    def version(self) -> Version:
        raise NotImplementedError("Override in subclass")
Referenced by pip._vendor.urllib3.contrib.securetransport.WrappedSocket._custom_validate(), pip._vendor.distro.distro.LinuxDistribution.info(), pip._vendor.distro.distro.LinuxDistribution.linux_distribution(), pip._vendor.distro.distro.LinuxDistribution.name(), and pip._vendor.distro.distro.LinuxDistribution.version_parts().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_internal/resolution/resolvelib/base.py