Read&Watch: pip._vendor.packaging.specifiers.BaseSpecifier Class Reference
pip._vendor.packaging.specifiers.BaseSpecifier Class Reference
Public Member Functions
str __str__ (self)
int __hash__ (self)
bool __eq__ (self, object other)
bool|None prereleases (self)
None prereleases (self, bool value)
bool contains (self, str item, bool|None prereleases=None)
Iterator[UnparsedVersionVar] filter (self, Iterable[UnparsedVersionVar] iterable, bool|None prereleases=None)
Detailed Description
Definition at line 44 of file specifiers.py.
Member Function Documentation
__eq__()
bool pip._vendor.packaging.specifiers.BaseSpecifier.__eq__ (self, object other)
Returns a boolean representing whether or not the two Specifier-like
objects are equal.
:param other: The other object to check against.
Definition at line 59 of file specifiers.py.
    def __eq__(self, other: object) -> bool:
        """
        Returns a boolean representing whether or not the two Specifier-like
        objects are equal.
        :param other: The other object to check against.
        """
Referenced by dotenv.variables.Atom.__ne__(), pip._vendor.urllib3._collections.HTTPHeaderDict.__ne__(), responses.BaseResponse.__ne__(), and urllib3._collections.HTTPHeaderDict.__ne__().
__hash__()
int pip._vendor.packaging.specifiers.BaseSpecifier.__hash__ (self)
Returns a hash value for this Specifier-like object.
Definition at line 53 of file specifiers.py.
    def __hash__(self) -> int:
        """
        Returns a hash value for this Specifier-like object.
        """
Referenced by pip._vendor.rich.style.Style.__eq__(), and pip._vendor.rich.style.Style.__ne__().
__str__()
str pip._vendor.packaging.specifiers.BaseSpecifier.__str__ (self)
Returns the str representation of this Specifier-like object. This
should be representative of the Specifier itself.
Definition at line 46 of file specifiers.py.
    def __str__(self) -> str:
        """
        Returns the str representation of this Specifier-like object. This
        should be representative of the Specifier itself.
        """
contains()
bool pip._vendor.packaging.specifiers.BaseSpecifier.contains (self, str item, bool | None prereleases = None)
Determines if the given item is contained within this specifier.
Reimplemented in pip._vendor.packaging.specifiers.Specifier, and pip._vendor.packaging.specifiers.SpecifierSet.
Definition at line 84 of file specifiers.py.
    def contains(self, item: str, prereleases: bool | None = None) -> bool:
        """
        Determines if the given item is contained within this specifier.
        """
Referenced by pip._vendor.packaging.specifiers.Specifier.__contains__(), pip._vendor.packaging.specifiers.SpecifierSet.__contains__(), and pip._vendor.packaging.specifiers.Specifier.filter().
filter()
Iterator[UnparsedVersionVar] pip._vendor.packaging.specifiers.BaseSpecifier.filter (self, Iterable[UnparsedVersionVar] iterable, bool | None prereleases = None)
Takes an iterable of items and filters them so that only items which
are contained within this specifier are allowed in it.
Reimplemented in pip._vendor.packaging.specifiers.Specifier, and pip._vendor.packaging.specifiers.SpecifierSet.
Definition at line 90 of file specifiers.py.
    ) -> Iterator[UnparsedVersionVar]:
        """
        Takes an iterable of items and filters them so that only items which
        are contained within this specifier are allowed in it.
        """
prereleases() [1/2]
bool | None pip._vendor.packaging.specifiers.BaseSpecifier.prereleases (self)
Whether or not pre-releases as a whole are allowed.
This can be set to either ``True`` or ``False`` to explicitly enable or disable
prereleases or it can be set to ``None`` (the default) to use default semantics.
Reimplemented in pip._vendor.packaging.specifiers.Specifier, pip._vendor.packaging.specifiers.Specifier, pip._vendor.packaging.specifiers.SpecifierSet, and pip._vendor.packaging.specifiers.SpecifierSet.
Definition at line 69 of file specifiers.py.
    def prereleases(self) -> bool | None:
        """Whether or not pre-releases as a whole are allowed.
        This can be set to either ``True`` or ``False`` to explicitly enable or disable
        prereleases or it can be set to ``None`` (the default) to use default semantics.
        """
Referenced by pip._vendor.packaging.specifiers.Specifier.contains(), pip._vendor.packaging.specifiers.SpecifierSet.contains(), pip._vendor.packaging.specifiers.Specifier.filter(), and pip._vendor.packaging.specifiers.SpecifierSet.filter().
prereleases() [2/2]
None pip._vendor.packaging.specifiers.BaseSpecifier.prereleases (self, bool value)
Setter for :attr:`prereleases`.
:param value: The value to set.
Reimplemented in pip._vendor.packaging.specifiers.Specifier, pip._vendor.packaging.specifiers.Specifier, pip._vendor.packaging.specifiers.SpecifierSet, and pip._vendor.packaging.specifiers.SpecifierSet.
Definition at line 77 of file specifiers.py.
    def prereleases(self, value: bool) -> None:
        """Setter for :attr:`prereleases`.
        :param value: The value to set.
        """
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/packaging/specifiers.py