Read&Watch: django.template.defaulttags.CsrfTokenNode Class Reference
django.template.defaulttags.CsrfTokenNode Class Reference
Public Member Functions
render (self, context)
Public Member Functions inherited from django.template.base.Node
render_annotated (self, context)
get_nodes_by_type (self, nodetype)
Additional Inherited Members
Static Public Attributes inherited from django.template.base.Node
bool must_be_first = False
tuple child_nodelists = ("nodelist",)
token = None
Detailed Description
Definition at line 70 of file defaulttags.py.
Member Function Documentation
render()
django.template.defaulttags.CsrfTokenNode.render (self, context)
Return the node rendered as a string.
Reimplemented from django.template.base.Node.
Definition at line 73 of file defaulttags.py.
    def render(self, context):
        csrf_token = context.get("csrf_token")
        if csrf_token:
            if csrf_token == "NOTPROVIDED":
                return format_html("")
            else:
                return format_html(
                    '<input type="hidden" name="csrfmiddlewaretoken" value="{}">',
                    csrf_token,
                )
        else:
            # It's very probable that the token is missing because of
            # misconfiguration, so we raise a warning
            if settings.DEBUG:
                warnings.warn(
                    "A {% csrf_token %} was used in a template, but the context "
                    "did not provide the value.  This is usually caused by not "
                    "using RequestContext."
                )
            return ""
Referenced by pip._vendor.rich.progress.ProgressColumn.__call__(), pip._vendor.rich.layout.Layout.__rich_console__(), pip._vendor.rich.spinner.Spinner.__rich_console__(), pip._vendor.rich.spinner.Spinner.__rich_measure__(), pip._vendor.rich.console.Console.log(), pip._vendor.rich.console.Console.print(), django.templatetags.i18n.BlockTranslateNode.render(), pip._vendor.rich.console.Console.render(), pip._vendor.rich.console.Console.render_lines(), and pip._vendor.rich.console.Console.update_screen_lines().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/template/defaulttags.py