Read&Watch: asgiref.current_thread_executor.CurrentThreadExecutor Class Reference
asgiref.current_thread_executor.CurrentThreadExecutor Class Reference
Public Member Functions
None __init__ (self)
None run_until_future (self, "Future[Any]" future)
submit (self, fn, *args, **kwargs)
Protected Member Functions
"Future[_R]" _submit (self, Callable[_P, _R] fn, *_P.args args, **_P.kwargs kwargs)
Protected Attributes
_work_thread = threading.current_thread()
queue.Queue[Union[_WorkItem,]] _work_queue = queue.Queue()
bool _broken = False
Detailed Description
An Executor that actually runs code in the thread it is instantiated in.
Passed to other threads running async code, so they can run sync code in
the thread they came from.
Definition at line 49 of file current_thread_executor.py.
Constructor & Destructor Documentation
__init__()
None asgiref.current_thread_executor.CurrentThreadExecutor.__init__ (self)
Definition at line 56 of file current_thread_executor.py.
    def __init__(self) -> None:
        self._work_thread = threading.current_thread()
        self._work_queue: queue.Queue[Union[_WorkItem, "Future[Any]"]] = queue.Queue()
        self._broken = False
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
_submit()
"Future[_R]" asgiref.current_thread_executor.CurrentThreadExecutor._submit (self, Callable[_P, _R] fn, *_P.args args, **_P.kwargs kwargs) protected
Definition at line 86 of file current_thread_executor.py.
    ) -> "Future[_R]":
        # Check they're not submitting from the same thread
        if threading.current_thread() == self._work_thread:
            raise RuntimeError(
                "You cannot submit onto CurrentThreadExecutor from its own thread"
            )
        # Check they're not too late or the executor errored
        if self._broken:
            raise RuntimeError("CurrentThreadExecutor already quit or is broken")
        # Add to work queue
        f: "Future[_R]" = Future()
        work_item = _WorkItem(f, fn, *args, **kwargs)
        self._work_queue.put(work_item)
        # Return the future
        return f
References _broken, _work_queue, and _work_thread.
Referenced by submit().
run_until_future()
None asgiref.current_thread_executor.CurrentThreadExecutor.run_until_future (self, "Future[Any]" future)
Runs the code in the work queue until a result is available from the future.
Should be run from the thread the executor is initialised in.
Definition at line 61 of file current_thread_executor.py.
    def run_until_future(self, future: "Future[Any]") -> None:
        """
        Runs the code in the work queue until a result is available from the future.
        Should be run from the thread the executor is initialised in.
        """
        # Check we're in the right thread
        if threading.current_thread() != self._work_thread:
            raise RuntimeError(
                "You cannot run CurrentThreadExecutor from a different thread"
            )
        future.add_done_callback(self._work_queue.put)
        # Keep getting and running work items until we get the future we're waiting for
        # back via the future's done callback.
        try:
            while True:
                # Get a work item and run it
                work_item = self._work_queue.get()
                if work_item is future:
                    return
                assert isinstance(work_item, _WorkItem)
                work_item.run()
                del work_item
        finally:
            self._broken = True
References _broken, _work_queue, and _work_thread.
submit()
asgiref.current_thread_executor.CurrentThreadExecutor.submit (self, fn, * args, ** kwargs)
Definition at line 114 of file current_thread_executor.py.
        def submit(self, fn, *args, **kwargs):
            return self._submit(fn, *args, **kwargs)
References _submit().
Member Data Documentation
_broken
bool asgiref.current_thread_executor.CurrentThreadExecutor._broken = False protected
Definition at line 59 of file current_thread_executor.py.
Referenced by _submit(), and run_until_future().
_work_queue
queue.Queue[Union[_WorkItem, ]] asgiref.current_thread_executor.CurrentThreadExecutor._work_queue = queue.Queue() protected
Definition at line 58 of file current_thread_executor.py.
Referenced by _submit(), and run_until_future().
_work_thread
asgiref.current_thread_executor.CurrentThreadExecutor._work_thread = threading.current_thread() protected
Definition at line 57 of file current_thread_executor.py.
Referenced by _submit(), and run_until_future().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/asgiref/current_thread_executor.py