Read&Watch: apscheduler.executors.pool.ProcessPoolExecutor Class Reference
apscheduler.executors.pool.ProcessPoolExecutor Class Reference
Public Member Functions
__init__ (self, max_workers=10, pool_kwargs=None)
Public Member Functions inherited from apscheduler.executors.pool.BasePoolExecutor
__init__ (self, pool)
shutdown (self, wait=True)
Public Member Functions inherited from apscheduler.executors.base.BaseExecutor
__init__ (self)
start (self, scheduler, alias)
submit_job (self, job, run_times)
Public Attributes
pool_kwargs = pool_kwargs or {}
Protected Member Functions
_do_submit_job (self, job, run_times)
Protected Member Functions inherited from apscheduler.executors.base.BaseExecutor
_run_job_success (self, job_id, events)
_run_job_error (self, job_id, exc, traceback=None)
Additional Inherited Members
Protected Attributes inherited from apscheduler.executors.pool.BasePoolExecutor
_pool = pool
Protected Attributes inherited from apscheduler.executors.base.BaseExecutor
_instances = defaultdict(lambda: 0)
Static Protected Attributes inherited from apscheduler.executors.base.BaseExecutor
_scheduler = None
_lock = None
_logger = logging.getLogger("apscheduler.executors")
Detailed Description
An executor that runs jobs in a concurrent.futures process pool.
Plugin alias: ``processpool``
:param max_workers: the maximum number of spawned processes.
:param pool_kwargs: dict of keyword arguments to pass to the underlying
    ProcessPoolExecutor constructor
Definition at line 53 of file pool.py.
Constructor & Destructor Documentation
__init__()
apscheduler.executors.pool.ProcessPoolExecutor.__init__ (self, max_workers = 10, pool_kwargs = None)
Definition at line 64 of file pool.py.
    def __init__(self, max_workers=10, pool_kwargs=None):
        self.pool_kwargs = pool_kwargs or {}
        self.pool_kwargs.setdefault("mp_context", multiprocessing.get_context("spawn"))
        pool = concurrent.futures.ProcessPoolExecutor(
            int(max_workers), **self.pool_kwargs
        )
        super().__init__(pool)
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
_do_submit_job()
apscheduler.executors.pool.ProcessPoolExecutor._do_submit_job (self, job, run_times) protected
Performs the actual task of scheduling `run_job` to be called.
Reimplemented from apscheduler.executors.pool.BasePoolExecutor.
Definition at line 72 of file pool.py.
    def _do_submit_job(self, job, run_times):
        try:
            super()._do_submit_job(job, run_times)
        except BrokenProcessPool:
            self._logger.warning(
                "Process pool is broken; replacing pool with a fresh instance"
            )
            self._pool = self._pool.__class__(
                self._pool._max_workers, **self.pool_kwargs
            )
            super()._do_submit_job(job, run_times)
References _do_submit_job(), and apscheduler.executors.base.BaseExecutor._logger.
Referenced by _do_submit_job().
Member Data Documentation
pool_kwargs
apscheduler.executors.pool.ProcessPoolExecutor.pool_kwargs = pool_kwargs or {}
Definition at line 65 of file pool.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/apscheduler/executors/pool.py