Read&Watch: django.contrib.admin.tests.AdminSeleniumTestCase Class Reference
django.contrib.admin.tests.AdminSeleniumTestCase Class Reference
Public Member Functions
wait_until (self, callback, timeout=10)
wait_for_and_switch_to_popup (self, num_windows=2, timeout=10)
wait_for (self, css_selector, timeout=10)
wait_for_text (self, css_selector, text, timeout=10)
wait_for_value (self, css_selector, text, timeout=10)
wait_until_visible (self, css_selector, timeout=10)
wait_until_invisible (self, css_selector, timeout=10)
wait_page_ready (self, timeout=10)
wait_page_loaded (self, timeout=10)
admin_login (self, username, password, login_url="/admin/")
select_option (self, selector, value)
deselect_option (self, selector, value)
assertCountSeleniumElements (self, selector, count, root_element=None)
assertSelectOptions (self, selector, values)
assertSelectedOptions (self, selector, values)
has_css_class (self, selector, klass)
Public Member Functions inherited from django.test.selenium.SeleniumTestCase
__init_subclass__ (cls, **kwargs)
live_server_url (cls)
allowed_host (cls)
setUpClass (cls)
desktop_size (self)
small_screen_size (self)
mobile_size (self)
rtl (self)
dark (self)
set_emulated_media (self, *, media=None, features=None)
high_contrast (self)
take_screenshot (self, name)
disable_implicit_wait (self)
Public Member Functions inherited from django.test.testcases.TransactionTestCase
assertQuerySetEqual (self, qs, values, transform=None, ordered=True, msg=None)
assertNumQueries (self, num, func=None, *args, using=DEFAULT_DB_ALIAS, **kwargs)
Public Member Functions inherited from django.test.testcases.SimpleTestCase
ensure_connection_patch_method (cls)
__call__ (self, result=None)
__getstate__ (self)
debug (self)
enterClassContext (cls, cm)
settings (self, **kwargs)
modify_settings (self, **kwargs)
assertRedirects (self, response, expected_url, status_code=302, target_status_code=200, msg_prefix="", fetch_redirect_response=True)
assertURLEqual (self, url1, url2, msg_prefix="")
assertContains (self, response, text, count=None, status_code=200, msg_prefix="", html=False)
assertNotContains (self, response, text, status_code=200, msg_prefix="", html=False)
assertFormError (self, form, field, errors, msg_prefix="")
assertFormSetError (self, formset, form_index, field, errors, msg_prefix="")
assertTemplateUsed (self, response=None, template_name=None, msg_prefix="", count=None)
assertTemplateNotUsed (self, response=None, template_name=None, msg_prefix="")
assertRaisesMessage (self, expected_exception, expected_message, *args, **kwargs)
assertWarnsMessage (self, expected_warning, expected_message, *args, **kwargs)
assertFieldOutput (self, fieldclass, valid, invalid, field_args=None, field_kwargs=None, empty_value="")
assertHTMLEqual (self, html1, html2, msg=None)
assertHTMLNotEqual (self, html1, html2, msg=None)
assertInHTML (self, needle, haystack, count=None, msg_prefix="")
assertNotInHTML (self, needle, haystack, msg_prefix="")
assertJSONEqual (self, raw, expected_data, msg=None)
assertJSONNotEqual (self, raw, expected_data, msg=None)
assertXMLEqual (self, xml1, xml2, msg=None)
assertXMLNotEqual (self, xml1, xml2, msg=None)
Public Member Functions inherited from django.test.selenium.SeleniumTestCaseBase
__new__ (cls, name, bases, attrs)
import_webdriver (cls, browser)
import_options (cls, browser)
get_capability (cls, browser)
create_options (self)
create_webdriver (self)
Protected Member Functions
_assertOptionsValues (self, options_selector, values)
Protected Member Functions inherited from django.test.selenium.SeleniumTestCase
_quit_selenium (cls)
Protected Member Functions inherited from django.test.testcases.LiveServerTestCase
_make_connections_override (cls)
_start_server_thread (cls)
_create_server_thread (cls, connections_override)
_terminate_thread (cls)
Protected Member Functions inherited from django.test.testcases.TransactionTestCase
_pre_setup (self)
_databases_names (cls, include_mirrors=True)
_reset_sequences (self, db_name)
_fixture_setup (self)
_should_reload_connections (self)
_post_teardown (self)
_fixture_teardown (self)
Protected Member Functions inherited from django.test.testcases.SimpleTestCase
_validate_databases (cls)
_add_databases_failures (cls)
_remove_databases_failures (cls)
_setup_and_call (self, result, debug=False)
_assert_contains (self, response, text, status_code, msg_prefix, html)
_check_test_client_response (self, response, attribute, method_name)
_assert_form_error (self, form, field, errors, msg_prefix, form_repr)
_get_template_used (self, response, template_name, msg_prefix, method_name)
_assert_template_used (self, template_name, template_names, msg_prefix, count)
_assert_raises_or_warns_cm (self, func, cm_attr, expected_exception, expected_message)
_assertFooMessage (self, func, cm_attr, expected_exception, expected_message, *args, **kwargs)
Additional Inherited Members
Public Attributes inherited from django.test.selenium.SeleniumTestCase
selenium = cls.create_webdriver()
Public Attributes inherited from django.test.testcases.LiveServerTestCase
server_thread = cls._create_server_thread(connections_override)
Public Attributes inherited from django.test.testcases.SimpleTestCase
ensure_connection
client = self.client_class()
async_client = self.async_client_class()
addClassCleanup
assertRaises
assertWarns
Static Public Attributes inherited from django.test.selenium.SeleniumTestCase
int implicit_wait = 10
bool screenshots = False
Static Public Attributes inherited from django.test.testcases.LiveServerTestCase
str host = "localhost"
int port = 0
server_thread_class = LiveServerThread
static_handler = _StaticFilesHandler
Static Public Attributes inherited from django.test.testcases.TransactionTestCase
bool reset_sequences = False
available_apps = None
fixtures = None
bool serialized_rollback = False
Static Public Attributes inherited from django.test.testcases.SimpleTestCase
client_class = Client
async_client_class = AsyncClient
str databases = set()
Static Public Attributes inherited from django.test.selenium.SeleniumTestCaseBase
list browsers = []
selenium_hub = None
external_host = None
browser = None
bool headless = False
Protected Attributes inherited from django.test.selenium.SeleniumTestCase
_quit_selenium
Protected Attributes inherited from django.test.testcases.LiveServerTestCase
_terminate_thread = True
Protected Attributes inherited from django.test.testcases.SimpleTestCase
_remove_databases_failures
_testMethodName
Static Protected Attributes inherited from django.test.testcases.SimpleTestCase
_overridden_settings = None
_modified_settings = None
tuple _disallowed_database_msg
list _disallowed_connection_methods
Detailed Description
Definition at line 19 of file tests.py.
Member Function Documentation
_assertOptionsValues()
django.contrib.admin.tests.AdminSeleniumTestCase._assertOptionsValues (self, options_selector, values) protected
Definition at line 184 of file tests.py.
    def _assertOptionsValues(self, options_selector, values):
        from selenium.webdriver.common.by import By
        if values:
            options = self.selenium.find_elements(By.CSS_SELECTOR, options_selector)
            actual_values = []
            for option in options:
                actual_values.append(option.get_attribute("value"))
            self.assertEqual(values, actual_values)
        else:
            # Prevent the `find_elements(By.CSS_SELECTOR, )` call from blocking
            # if the selector doesn't match any options as we expect it
            # to be the case.
            with self.disable_implicit_wait():
                self.wait_until(
                    lambda driver: not driver.find_elements(
                        By.CSS_SELECTOR, options_selector
                    )
                )
References django.test.selenium.SeleniumTestCase.disable_implicit_wait(), selenium, and wait_until().
Referenced by assertSelectedOptions(), and assertSelectOptions().
admin_login()
django.contrib.admin.tests.AdminSeleniumTestCase.admin_login (self, username, password, login_url = "/admin/")
Log in to the admin.
Definition at line 132 of file tests.py.
    def admin_login(self, username, password, login_url="/admin/"):
        """
        Log in to the admin.
        """
        from selenium.webdriver.common.by import By
        self.selenium.get("%s%s" % (self.live_server_url, login_url))
        username_input = self.selenium.find_element(By.NAME, "username")
        username_input.send_keys(username)
        password_input = self.selenium.find_element(By.NAME, "password")
        password_input.send_keys(password)
        login_text = _("Log in")
        with self.wait_page_loaded():
            self.selenium.find_element(
                By.XPATH, '//input[@value="%s"]' % login_text
            ).click()
assertCountSeleniumElements()
django.contrib.admin.tests.AdminSeleniumTestCase.assertCountSeleniumElements (self, selector, count, root_element = None)
Assert number of matches for a CSS selector.
`root_element` allow restriction to a pre-selected node.
Definition at line 171 of file tests.py.
    def assertCountSeleniumElements(self, selector, count, root_element=None):
        """
        Assert number of matches for a CSS selector.
        `root_element` allow restriction to a pre-selected node.
        """
        from selenium.webdriver.common.by import By
        root_element = root_element or self.selenium
        self.assertEqual(
            len(root_element.find_elements(By.CSS_SELECTOR, selector)), count
        )
References selenium.
assertSelectedOptions()
django.contrib.admin.tests.AdminSeleniumTestCase.assertSelectedOptions (self, selector, values)
Assert that the <SELECT> widget identified by `selector` has the
selected options with the given `values`.
Definition at line 211 of file tests.py.
    def assertSelectedOptions(self, selector, values):
        """
        Assert that the <SELECT> widget identified by `selector` has the
        selected options with the given `values`.
        """
        self._assertOptionsValues("%s > option:checked" % selector, values)
References _assertOptionsValues().
assertSelectOptions()
django.contrib.admin.tests.AdminSeleniumTestCase.assertSelectOptions (self, selector, values)
Assert that the <SELECT> widget identified by `selector` has the
options with the given `values`.
Definition at line 204 of file tests.py.
    def assertSelectOptions(self, selector, values):
        """
        Assert that the <SELECT> widget identified by `selector` has the
        options with the given `values`.
        """
        self._assertOptionsValues("%s > option" % selector, values)
References _assertOptionsValues().
deselect_option()
django.contrib.admin.tests.AdminSeleniumTestCase.deselect_option (self, selector, value)
Deselect the <OPTION> with the value `value` inside the <SELECT> widget
identified by the CSS selector `selector`.
Definition at line 160 of file tests.py.
    def deselect_option(self, selector, value):
        """
        Deselect the <OPTION> with the value `value` inside the <SELECT> widget
        identified by the CSS selector `selector`.
        """
        from selenium.webdriver.common.by import By
        from selenium.webdriver.support.ui import Select
        select = Select(self.selenium.find_element(By.CSS_SELECTOR, selector))
        select.deselect_by_value(value)
References selenium.
has_css_class()
django.contrib.admin.tests.AdminSeleniumTestCase.has_css_class (self, selector, klass)
Return True if the element identified by `selector` has the CSS class
`klass`.
Definition at line 218 of file tests.py.
    def has_css_class(self, selector, klass):
        """
        Return True if the element identified by `selector` has the CSS class
        `klass`.
        """
        from selenium.webdriver.common.by import By
        return (
            self.selenium.find_element(
                By.CSS_SELECTOR,
                selector,
            )
            .get_attribute("class")
            .find(klass)
            != -1
        )
References selenium.
select_option()
django.contrib.admin.tests.AdminSeleniumTestCase.select_option (self, selector, value)
Select the <OPTION> with the value `value` inside the <SELECT> widget
identified by the CSS selector `selector`.
Definition at line 149 of file tests.py.
    def select_option(self, selector, value):
        """
        Select the <OPTION> with the value `value` inside the <SELECT> widget
        identified by the CSS selector `selector`.
        """
        from selenium.webdriver.common.by import By
        from selenium.webdriver.support.ui import Select
        select = Select(self.selenium.find_element(By.CSS_SELECTOR, selector))
        select.select_by_value(value)
References selenium.
wait_for()
django.contrib.admin.tests.AdminSeleniumTestCase.wait_for (self, css_selector, timeout = 10)
Block until a CSS selector is found on the page.
Definition at line 49 of file tests.py.
    def wait_for(self, css_selector, timeout=10):
        """
        Block until a CSS selector is found on the page.
        """
        from selenium.webdriver.common.by import By
        from selenium.webdriver.support import expected_conditions as ec
        self.wait_until(
            ec.presence_of_element_located((By.CSS_SELECTOR, css_selector)), timeout
        )
References wait_until().
wait_for_and_switch_to_popup()
django.contrib.admin.tests.AdminSeleniumTestCase.wait_for_and_switch_to_popup (self, num_windows = 2, timeout = 10)
Block until `num_windows` are present and are ready (usually 2, but can
be overridden in the case of pop-ups opening other pop-ups). Switch the
current window to the new pop-up.
Definition at line 39 of file tests.py.
    def wait_for_and_switch_to_popup(self, num_windows=2, timeout=10):
        """
        Block until `num_windows` are present and are ready (usually 2, but can
        be overridden in the case of pop-ups opening other pop-ups). Switch the
        current window to the new pop-up.
        """
        self.wait_until(lambda d: len(d.window_handles) == num_windows, timeout)
        self.selenium.switch_to.window(self.selenium.window_handles[-1])
        self.wait_page_ready()
References selenium, wait_page_ready(), and wait_until().
wait_for_text()
django.contrib.admin.tests.AdminSeleniumTestCase.wait_for_text (self, css_selector, text, timeout = 10)
Block until the text is found in the CSS selector.
Definition at line 60 of file tests.py.
    def wait_for_text(self, css_selector, text, timeout=10):
        """
        Block until the text is found in the CSS selector.
        """
        from selenium.webdriver.common.by import By
        from selenium.webdriver.support import expected_conditions as ec
        self.wait_until(
            ec.text_to_be_present_in_element((By.CSS_SELECTOR, css_selector), text),
            timeout,
        )
References wait_until().
wait_for_value()
django.contrib.admin.tests.AdminSeleniumTestCase.wait_for_value (self, css_selector, text, timeout = 10)
Block until the value is found in the CSS selector.
Definition at line 72 of file tests.py.
    def wait_for_value(self, css_selector, text, timeout=10):
        """
        Block until the value is found in the CSS selector.
        """
        from selenium.webdriver.common.by import By
        from selenium.webdriver.support import expected_conditions as ec
        self.wait_until(
            ec.text_to_be_present_in_element_value(
                (By.CSS_SELECTOR, css_selector), text
            ),
            timeout,
        )
References wait_until().
wait_page_loaded()
django.contrib.admin.tests.AdminSeleniumTestCase.wait_page_loaded (self, timeout = 10)
Block until a new page has loaded and is ready.
Definition at line 119 of file tests.py.
    def wait_page_loaded(self, timeout=10):
        """
        Block until a new page has loaded and is ready.
        """
        from selenium.webdriver.common.by import By
        from selenium.webdriver.support import expected_conditions as ec
        old_page = self.selenium.find_element(By.TAG_NAME, "html")
        yield
        # Wait for the next page to be loaded
        self.wait_until(ec.staleness_of(old_page), timeout=timeout)
        self.wait_page_ready(timeout=timeout)
References selenium, wait_page_ready(), and wait_until().
wait_page_ready()
django.contrib.admin.tests.AdminSeleniumTestCase.wait_page_ready (self, timeout = 10)
Block until the  page is ready.
Definition at line 108 of file tests.py.
    def wait_page_ready(self, timeout=10):
        """
        Block until the  page is ready.
        """
        self.wait_until(
            lambda driver: driver.execute_script("return document.readyState;")
            == "complete",
            timeout,
        )
References wait_until().
Referenced by wait_for_and_switch_to_popup(), and wait_page_loaded().
wait_until()
django.contrib.admin.tests.AdminSeleniumTestCase.wait_until (self, callback, timeout = 10)
Block the execution of the tests until the specified callback returns a
value that is not falsy. This method can be called, for example, after
clicking a link or submitting a form. See the other public methods that
call this function for more details.
Definition at line 28 of file tests.py.
    def wait_until(self, callback, timeout=10):
        """
        Block the execution of the tests until the specified callback returns a
        value that is not falsy. This method can be called, for example, after
        clicking a link or submitting a form. See the other public methods that
        call this function for more details.
        """
        from selenium.webdriver.support.wait import WebDriverWait
        WebDriverWait(self.selenium, timeout).until(callback)
Referenced by _assertOptionsValues(), wait_for(), wait_for_and_switch_to_popup(), wait_for_text(), wait_for_value(), wait_page_loaded(), wait_page_ready(), wait_until_invisible(), and wait_until_visible().
wait_until_invisible()
django.contrib.admin.tests.AdminSeleniumTestCase.wait_until_invisible (self, css_selector, timeout = 10)
Block until the element described by the CSS selector is invisible.
Definition at line 97 of file tests.py.
    def wait_until_invisible(self, css_selector, timeout=10):
        """
        Block until the element described by the CSS selector is invisible.
        """
        from selenium.webdriver.common.by import By
        from selenium.webdriver.support import expected_conditions as ec
        self.wait_until(
            ec.invisibility_of_element_located((By.CSS_SELECTOR, css_selector)), timeout
        )
References wait_until().
wait_until_visible()
django.contrib.admin.tests.AdminSeleniumTestCase.wait_until_visible (self, css_selector, timeout = 10)
Block until the element described by the CSS selector is visible.
Definition at line 86 of file tests.py.
    def wait_until_visible(self, css_selector, timeout=10):
        """
        Block until the element described by the CSS selector is visible.
        """
        from selenium.webdriver.common.by import By
        from selenium.webdriver.support import expected_conditions as ec
        self.wait_until(
            ec.visibility_of_element_located((By.CSS_SELECTOR, css_selector)), timeout
        )
References wait_until().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/admin/tests.py