Read&Watch: pip._internal.metadata.importlib._envs._DistributionFinder Class Reference
pip._internal.metadata.importlib._envs._DistributionFinder Class Reference
Public Member Functions
None __init__ (self)
Iterator[BaseDistribution] find (self, str location)
Iterator[BaseDistribution] find_linked (self, str location)
Iterator[BaseDistribution] find_eggs (self, str location)
Static Public Attributes
FoundResult = Tuple[importlib.metadata.Distribution, Optional[BasePath]]
Protected Member Functions
Iterator[FoundResult] _find_impl (self, str location)
Iterator[BaseDistribution] _find_eggs_in_dir (self, str location)
Iterator[BaseDistribution] _find_eggs_in_zip (self, str location)
Protected Attributes
Set[NormalizedName] _found_names = set()
Detailed Description
Finder to locate distributions.
The main purpose of this class is to memoize found distributions' names, so
only one distribution is returned for each package name. At lot of pip code
assumes this (because it is setuptools's behavior), and not doing the same
can potentially cause a distribution in lower precedence path to override a
higher precedence one if the caller is not careful.
Eventually we probably want to make it possible to see lower precedence
installations as well. It's useful feature, after all.
Definition at line 34 of file _envs.py.
Constructor & Destructor Documentation
__init__()
None pip._internal.metadata.importlib._envs._DistributionFinder.__init__ (self)
Definition at line 49 of file _envs.py.
    def __init__(self) -> None:
        self._found_names: Set[NormalizedName] = set()
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
_find_eggs_in_dir()
Iterator[BaseDistribution] pip._internal.metadata.importlib._envs._DistributionFinder._find_eggs_in_dir (self, str location) protected
Definition at line 109 of file _envs.py.
    def _find_eggs_in_dir(self, location: str) -> Iterator[BaseDistribution]:
        from pip._vendor.pkg_resources import find_distributions
        from pip._internal.metadata import pkg_resources as legacy
        with os.scandir(location) as it:
            for entry in it:
                if not entry.name.endswith(".egg"):
                    continue
                for dist in find_distributions(entry.path):
                    yield legacy.Distribution(dist)
Referenced by find_eggs().
_find_eggs_in_zip()
Iterator[BaseDistribution] pip._internal.metadata.importlib._envs._DistributionFinder._find_eggs_in_zip (self, str location) protected
Definition at line 121 of file _envs.py.
    def _find_eggs_in_zip(self, location: str) -> Iterator[BaseDistribution]:
        from pip._vendor.pkg_resources import find_eggs_in_zip
        from pip._internal.metadata import pkg_resources as legacy
        try:
            importer = zipimport.zipimporter(location)
        except zipimport.ZipImportError:
            return
        for dist in find_eggs_in_zip(importer, location):
            yield legacy.Distribution(dist)
Referenced by find_eggs().
_find_impl()
Iterator[FoundResult] pip._internal.metadata.importlib._envs._DistributionFinder._find_impl (self, str location) protected
Find distributions in a location.
Definition at line 52 of file _envs.py.
    def _find_impl(self, location: str) -> Iterator[FoundResult]:
        """Find distributions in a location."""
        # Skip looking inside a wheel. Since a package inside a wheel is not
        # always valid (due to .data directories etc.), its .dist-info entry
        # should not be considered an installed distribution.
        if _looks_like_wheel(location):
            return
        # To know exactly where we find a distribution, we have to feed in the
        # paths one by one, instead of dumping the list to importlib.metadata.
        for dist in importlib.metadata.distributions(path=[location]):
            info_location = get_info_location(dist)
            try:
                name = get_dist_canonical_name(dist)
            except BadMetadata as e:
                logger.warning("Skipping %s due to %s", info_location, e.reason)
                continue
            if name in self._found_names:
                continue
            self._found_names.add(name)
            yield dist, info_location
References _found_names, and pip._internal.metadata.importlib._envs._looks_like_wheel().
Referenced by find(), and find_linked().
find()
Iterator[BaseDistribution] pip._internal.metadata.importlib._envs._DistributionFinder.find (self, str location)
Find distributions in a location.
The path can be either a directory, or a ZIP archive.
Definition at line 73 of file _envs.py.
    def find(self, location: str) -> Iterator[BaseDistribution]:
        """Find distributions in a location.
        The path can be either a directory, or a ZIP archive.
        """
        for dist, info_location in self._find_impl(location):
            if info_location is None:
                installed_location: Optional[BasePath] = None
            else:
                installed_location = info_location.parent
            yield Distribution(dist, info_location, installed_location)
References _find_impl().
Referenced by pip._vendor.distlib.resources.ResourceFinder.iterator().
find_eggs()
Iterator[BaseDistribution] pip._internal.metadata.importlib._envs._DistributionFinder.find_eggs (self, str location)
Find eggs in a location.
This actually uses the old *pkg_resources* backend. We likely want to
deprecate this so we can eventually remove the *pkg_resources*
dependency entirely. Before that, this should first emit a deprecation
warning for some versions when using the fallback since importing
*pkg_resources* is slow for those who don't need it.
Definition at line 133 of file _envs.py.
    def find_eggs(self, location: str) -> Iterator[BaseDistribution]:
        """Find eggs in a location.
        This actually uses the old *pkg_resources* backend. We likely want to
        deprecate this so we can eventually remove the *pkg_resources*
        dependency entirely. Before that, this should first emit a deprecation
        warning for some versions when using the fallback since importing
        *pkg_resources* is slow for those who don't need it.
        """
        if os.path.isdir(location):
            yield from self._find_eggs_in_dir(location)
        if zipfile.is_zipfile(location):
            yield from self._find_eggs_in_zip(location)
@functools.lru_cache(maxsize=None)  # Warn a distribution exactly once.
References _find_eggs_in_dir(), and _find_eggs_in_zip().
find_linked()
Iterator[BaseDistribution] pip._internal.metadata.importlib._envs._DistributionFinder.find_linked (self, str location)
Read location in egg-link files and return distributions in there.
The path should be a directory; otherwise this returns nothing. This
follows how setuptools does this for compatibility. The first non-empty
line in the egg-link is read as a path (resolved against the egg-link's
containing directory if relative). Distributions found at that linked
location are returned.
Definition at line 85 of file _envs.py.
    def find_linked(self, location: str) -> Iterator[BaseDistribution]:
        """Read location in egg-link files and return distributions in there.
        The path should be a directory; otherwise this returns nothing. This
        follows how setuptools does this for compatibility. The first non-empty
        line in the egg-link is read as a path (resolved against the egg-link's
        containing directory if relative). Distributions found at that linked
        location are returned.
        """
        path = pathlib.Path(location)
        if not path.is_dir():
            return
        for child in path.iterdir():
            if child.suffix != ".egg-link":
                continue
            with child.open() as f:
                lines = (line.strip() for line in f)
                target_rel = next((line for line in lines if line), "")
            if not target_rel:
                continue
            target_location = str(path.joinpath(target_rel))
            for dist, info_location in self._find_impl(target_location):
                yield Distribution(dist, info_location, path)
References _find_impl().
Member Data Documentation
_found_names
Set[NormalizedName] pip._internal.metadata.importlib._envs._DistributionFinder._found_names = set() protected
Definition at line 50 of file _envs.py.
Referenced by _find_impl().
FoundResult
pip._internal.metadata.importlib._envs._DistributionFinder.FoundResult = Tuple[importlib.metadata.Distribution, Optional[BasePath]] static
Definition at line 47 of file _envs.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_internal/metadata/importlib/_envs.py