Read&Watch: django.contrib.gis.db.backends.oracle.adapter.OracleSpatialAdapter Class Reference
django.contrib.gis.db.backends.oracle.adapter.OracleSpatialAdapter Class Reference
Public Member Functions
__init__ (self, geom)
Public Member Functions inherited from django.contrib.gis.db.backends.base.adapter.WKTAdapter
__init__ (self, geom)
__eq__ (self, other)
__hash__ (self)
__str__ (self)
Static Public Attributes
input_size = oracledb.CLOB
Protected Member Functions
_fix_polygon (cls, poly, clone=True)
_fix_geometry_collection (cls, coll)
Static Protected Member Functions
_polygon_must_be_fixed (poly)
Additional Inherited Members
Public Attributes inherited from django.contrib.gis.db.backends.base.adapter.WKTAdapter
wkt = geom.wkt
srid = geom.srid
Detailed Description
Definition at line 6 of file adapter.py.
Constructor & Destructor Documentation
__init__()
django.contrib.gis.db.backends.oracle.adapter.OracleSpatialAdapter.__init__ (self, geom)
Oracle requires that polygon rings are in proper orientation. This
affects spatial operations and an invalid orientation may cause
failures. Correct orientations are:
 * Outer ring - counter clockwise
 * Inner ring(s) - clockwise
Definition at line 9 of file adapter.py.
    def __init__(self, geom):
        """
        Oracle requires that polygon rings are in proper orientation. This
        affects spatial operations and an invalid orientation may cause
        failures. Correct orientations are:
         * Outer ring - counter clockwise
         * Inner ring(s) - clockwise
        """
        if isinstance(geom, Polygon):
            if self._polygon_must_be_fixed(geom):
                geom = self._fix_polygon(geom)
        elif isinstance(geom, GeometryCollection):
            if any(
                isinstance(g, Polygon) and self._polygon_must_be_fixed(g) for g in geom
            ):
                geom = self._fix_geometry_collection(geom)
        self.wkt = geom.wkt
        self.srid = geom.srid
References _fix_geometry_collection(), django.contrib.gis.db.backends.base.adapter.WKTAdapter._fix_polygon(), and _polygon_must_be_fixed().
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
_fix_geometry_collection()
django.contrib.gis.db.backends.oracle.adapter.OracleSpatialAdapter._fix_geometry_collection (cls, coll) protected
Fix polygon orientations in geometry collections as described in
__init__().
Definition at line 52 of file adapter.py.
    def _fix_geometry_collection(cls, coll):
        """
        Fix polygon orientations in geometry collections as described in
        __init__().
        """
        coll = coll.clone()
        for i, geom in enumerate(coll):
            if isinstance(geom, Polygon):
                coll[i] = cls._fix_polygon(geom, clone=False)
        return coll
References django.contrib.gis.db.backends.base.adapter.WKTAdapter._fix_polygon().
Referenced by __init__().
_fix_polygon()
django.contrib.gis.db.backends.oracle.adapter.OracleSpatialAdapter._fix_polygon (cls, poly, clone = True) protected
Fix single polygon orientation as described in __init__().
Reimplemented from django.contrib.gis.db.backends.base.adapter.WKTAdapter.
Definition at line 37 of file adapter.py.
    def _fix_polygon(cls, poly, clone=True):
        """Fix single polygon orientation as described in __init__()."""
        if clone:
            poly = poly.clone()
        if not poly.exterior_ring.is_counterclockwise:
            poly.exterior_ring = list(reversed(poly.exterior_ring))
        for i in range(1, len(poly)):
            if poly[i].is_counterclockwise:
                poly[i] = list(reversed(poly[i]))
        return poly
_polygon_must_be_fixed()
django.contrib.gis.db.backends.oracle.adapter.OracleSpatialAdapter._polygon_must_be_fixed (poly) static protected
Definition at line 30 of file adapter.py.
    def _polygon_must_be_fixed(poly):
        return not poly.empty and (
            not poly.exterior_ring.is_counterclockwise
            or any(x.is_counterclockwise for x in poly)
        )
Referenced by __init__().
Member Data Documentation
input_size
django.contrib.gis.db.backends.oracle.adapter.OracleSpatialAdapter.input_size = oracledb.CLOB static
Definition at line 7 of file adapter.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/gis/db/backends/oracle/adapter.py