Read&Watch: isort.io._EmptyIO Class Reference
isort.io._EmptyIO Class Reference
Public Member Functions
None write (self, *Any args, **Any kwargs)
Detailed Description
Definition at line 67 of file io.py.
Member Function Documentation
write()
None isort.io._EmptyIO.write (self, *Any args, **Any kwargs)
Definition at line 68 of file io.py.
    def write(self, *args: Any, **kwargs: Any) -> None:  # type: ignore # skipcq: PTC-W0049
        pass
Referenced by pylint.reporters.ureports.text_writer.TextWriter.default_table(), pylint.reporters.ureports.text_writer.TextWriter.visit_text(), and pylint.reporters.ureports.base_writer.BaseWriter.writeln().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/isort/io.py