Read&Watch: django.utils.text.TruncateWordsHTMLParser Class Reference
django.utils.text.TruncateWordsHTMLParser Class Reference
Public Member Functions
process (self, data)
Public Member Functions inherited from django.utils.text.TruncateHTMLParser
__init__ (self, *, length, replacement, convert_charrefs=True)
void_elements (self)
handle_startendtag (self, tag, attrs)
handle_starttag (self, tag, attrs)
handle_endtag (self, tag)
handle_data (self, data)
feed (self, data)
Additional Inherited Members
Public Attributes inherited from django.utils.text.TruncateHTMLParser
tags = deque()
str output = ""
int remaining = length
replacement = replacement
void_elements
TruncationCompleted
Detailed Description
Definition at line 176 of file text.py.
Member Function Documentation
process()
django.utils.text.TruncateWordsHTMLParser.process (self, data)
Definition at line 177 of file text.py.
    def process(self, data):
        data = re.split(r"(?<=\S)\s+(?=\S)", data)
        output = escape(" ".join(data[: self.remaining]))
        return data, output
References django.utils.text.TruncateHTMLParser.remaining.
Referenced by django.utils.text.TruncateHTMLParser.handle_data(), sqlparse.filters.others.SpacesAroundOperatorsFilter.process(), sqlparse.filters.others.StripCommentsFilter.process(), and sqlparse.filters.others.StripWhitespaceFilter.process().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/utils/text.py