Read&Watch: astroid.nodes._base_nodes.OperatorNode Class Reference
astroid.nodes._base_nodes.OperatorNode Class Reference
Static Protected Member Functions
Generator[InferenceResult] _filter_operation_errors (Callable[[InferenceContext|None], Generator[InferenceResult|util.BadOperationMessage],] infer_callable, InferenceContext|None context, type[util.BadOperationMessage] error)
bool _is_not_implemented (const)
tuple[util.UninferableBase|nodes.Const] _infer_old_style_string_formatting (nodes.Const instance, nodes.NodeNG other, InferenceContext context)
Generator[InferenceResult] _invoke_binop_inference (InferenceResult instance, nodes.AugAssign|nodes.BinOp opnode, str op, InferenceResult other, InferenceContext context, str method_name)
partial[Generator[InferenceResult]] _aug_op (InferenceResult instance, nodes.AugAssign opnode, str op, InferenceResult other, InferenceContext context, bool reverse=False)
partial[Generator[InferenceResult]] _bin_op (InferenceResult instance, nodes.AugAssign|nodes.BinOp opnode, str op, InferenceResult other, InferenceContext context, bool reverse=False)
Generator[InferenceResult] _bin_op_or_union_type (bases.UnionType|nodes.ClassDef|nodes.Const left, bases.UnionType|nodes.ClassDef|nodes.Const right)
_get_binop_contexts (context, left, right)
bool _same_type (type1, type2)
list[partial[Generator[InferenceResult]]] _get_aug_flow (InferenceResult left, InferenceResult|None left_type, nodes.AugAssign aug_opnode, InferenceResult right, InferenceResult|None right_type, InferenceContext context, InferenceContext reverse_context)
list[partial[Generator[InferenceResult]]] _get_binop_flow (InferenceResult left, InferenceResult|None left_type, nodes.AugAssign|nodes.BinOp binary_opnode, InferenceResult right, InferenceResult|None right_type, InferenceContext context, InferenceContext reverse_context)
Generator[InferenceResult|util.BadBinaryOperationMessage] _infer_binary_operation (InferenceResult left, InferenceResult right, nodes.AugAssign|nodes.BinOp binary_opnode, InferenceContext context, GetFlowFactory flow_factory)
Additional Inherited Members
Public Member Functions inherited from astroid.nodes.node_ng.NodeNG
None __init__ (self, int|None lineno, int|None col_offset, NodeNG|None parent, *, int|None end_lineno, int|None end_col_offset)
Generator[InferenceResult] infer (self, InferenceContext|None context=None, **Any kwargs)
str repr_name (self)
str __str__ (self)
str __repr__ (self)
str accept (self, AsStringVisitor visitor)
Iterator[NodeNG] get_children (self)
NodeNG|None last_child (self)
Iterator[NodeNG] node_ancestors (self)
bool parent_of (self, node)
_base_nodes.Statement statement (self, *, Literal[None, True] future=None)
nodes.FunctionDef|nodes.Module|nodes.ClassDef|nodes.Lambda frame (self, *, Literal[None, True] future=None)
nodes.LocalsDictNodeNG scope (self)
nodes.Module root (self)
child_sequence (self, child)
locate_child (self, child)
next_sibling (self)
previous_sibling (self)
int fromlineno (self)
int tolineno (self)
tuple[int, int] block_range (self, int lineno)
None set_local (self, str name, NodeNG stmt)
Iterator[_NodesT] nodes_of_class (self, type[_NodesT] klass, SkipKlassT skip_klass=...)
Iterator[_NodesT]|Iterator[_NodesT2] nodes_of_class (self, tuple[type[_NodesT], type[_NodesT2]] klass, SkipKlassT skip_klass=...)
Iterator[_NodesT]|Iterator[_NodesT2]|Iterator[_NodesT3] nodes_of_class (self, tuple[type[_NodesT], type[_NodesT2], type[_NodesT3]] klass, SkipKlassT skip_klass=...)
Iterator[_NodesT] nodes_of_class (self, tuple[type[_NodesT],...] klass, SkipKlassT skip_klass=...)
Iterator[_NodesT]|Iterator[_NodesT2]|Iterator[_NodesT3] nodes_of_class (self,(type[_NodesT]|tuple[type[_NodesT], type[_NodesT2]]|tuple[type[_NodesT], type[_NodesT2], type[_NodesT3]]|tuple[type[_NodesT],...]) klass, SkipKlassT skip_klass=None)
inferred (self)
instantiate_class (self)
bool has_base (self, node)
bool callable (self)
bool eq (self, value)
str as_string (self)
str repr_tree (self, ids=False, include_linenos=False, ast_state=False, indent=" ", max_depth=0, max_width=80)
bool_value (self, InferenceContext|None context=None)
op_precedence (self)
bool op_left_associative (self)
Public Attributes inherited from astroid.nodes.node_ng.NodeNG
lineno = lineno
col_offset = col_offset
parent = parent
end_lineno = end_lineno
end_col_offset = end_col_offset
Position|None position = None
Static Public Attributes inherited from astroid.nodes.node_ng.NodeNG
ClassVar is_statement = False
tuple optional_assign
ClassVar is_function = False
ClassVar is_lambda = False
Protected Member Functions inherited from astroid.nodes.node_ng.NodeNG
int _fixed_source_line (self)
list[nodes.Assign] _assign_nodes_in_scope (self)
_get_name_nodes (self)
_get_return_nodes_skip_functions (self)
_get_yield_nodes_skip_functions (self)
_get_yield_nodes_skip_lambdas (self)
_infer_name (self, frame, name)
Generator[InferenceResult, None, InferenceErrorInfo|None] _infer (self, InferenceContext|None context=None, **Any kwargs)
Static Protected Attributes inherited from astroid.nodes.node_ng.NodeNG
tuple _astroid_fields = ()
tuple _other_fields = ()
tuple _other_other_fields = ()
InferFn _explicit_inference = None
Detailed Description
Definition at line 326 of file _base_nodes.py.
Member Function Documentation
_aug_op()
partial[Generator[InferenceResult]] astroid.nodes._base_nodes.OperatorNode._aug_op (InferenceResult instance, nodes.AugAssign opnode, str op, InferenceResult other, InferenceContext context, bool reverse = False) static protected
Get an inference callable for an augmented binary operation.
Definition at line 427 of file _base_nodes.py.
    ) -> partial[Generator[InferenceResult]]:
        """Get an inference callable for an augmented binary operation."""
        method_name = AUGMENTED_OP_METHOD[op]
        return partial(
            OperatorNode._invoke_binop_inference,
            instance=instance,
            op=op,
            opnode=opnode,
            other=other,
            context=context,
            method_name=method_name,
        )
_bin_op()
partial[Generator[InferenceResult]] astroid.nodes._base_nodes.OperatorNode._bin_op (InferenceResult instance, nodes.AugAssign | nodes.BinOp opnode, str op, InferenceResult other, InferenceContext context, bool reverse = False) static protected
Get an inference callable for a normal binary operation.
If *reverse* is True, then the reflected method will be used instead.
Definition at line 448 of file _base_nodes.py.
    ) -> partial[Generator[InferenceResult]]:
        """Get an inference callable for a normal binary operation.
        If *reverse* is True, then the reflected method will be used instead.
        """
        if reverse:
            method_name = REFLECTED_BIN_OP_METHOD[op]
        else:
            method_name = BIN_OP_METHOD[op]
        return partial(
            OperatorNode._invoke_binop_inference,
            instance=instance,
            op=op,
            opnode=opnode,
            other=other,
            context=context,
            method_name=method_name,
        )
_bin_op_or_union_type()
Generator[InferenceResult] astroid.nodes._base_nodes.OperatorNode._bin_op_or_union_type (bases.UnionType | nodes.ClassDef | nodes.Const left, bases.UnionType | nodes.ClassDef | nodes.Const right) static protected
Create a new UnionType instance for binary or, e.g. int | str.
Definition at line 475 of file _base_nodes.py.
    ) -> Generator[InferenceResult]:
        """Create a new UnionType instance for binary or, e.g. int | str."""
        yield bases.UnionType(left, right)
_filter_operation_errors()
Generator[InferenceResult] astroid.nodes._base_nodes.OperatorNode._filter_operation_errors (Callable[ [InferenceContext | None], Generator[InferenceResult | util.BadOperationMessage], ] infer_callable, InferenceContext | None context, type[util.BadOperationMessage] error) static protected
Definition at line 328 of file _base_nodes.py.
    ) -> Generator[InferenceResult]:
        for result in infer_callable(context):
            if isinstance(result, error):
                # For the sake of .infer(), we don't care about operation
                # errors, which is the job of a linter. So return something
                # which shows that we can't infer the result.
                yield util.Uninferable
            else:
                yield result
Referenced by astroid.nodes.node_classes.AugAssign._infer(), astroid.nodes.node_classes.BinOp._infer(), and astroid.nodes.node_classes.UnaryOp._infer().
_get_aug_flow()
list[partial[Generator[InferenceResult]]] astroid.nodes._base_nodes.OperatorNode._get_aug_flow (InferenceResult left, InferenceResult | None left_type, nodes.AugAssign aug_opnode, InferenceResult right, InferenceResult | None right_type, InferenceContext context, InferenceContext reverse_context) static protected
Get the flow for augmented binary operations.
The rules are a bit messy:
    * if left and right have the same type, then left.__augop__(right)
    is first tried and then left.__op__(right).
    * if left and right are unrelated typewise, then
    left.__augop__(right) is tried, then left.__op__(right)
    is tried and then right.__rop__(left) is tried.
    * if left is a subtype of right, then left.__augop__(right)
    is tried and then left.__op__(right).
    * if left is a supertype of right, then left.__augop__(right)
    is tried, then right.__rop__(left) and then
    left.__op__(right)
Definition at line 504 of file _base_nodes.py.
    ) -> list[partial[Generator[InferenceResult]]]:
        """Get the flow for augmented binary operations.
        The rules are a bit messy:
            * if left and right have the same type, then left.__augop__(right)
            is first tried and then left.__op__(right).
            * if left and right are unrelated typewise, then
            left.__augop__(right) is tried, then left.__op__(right)
            is tried and then right.__rop__(left) is tried.
            * if left is a subtype of right, then left.__augop__(right)
            is tried and then left.__op__(right).
            * if left is a supertype of right, then left.__augop__(right)
            is tried, then right.__rop__(left) and then
            left.__op__(right)
        """
        from astroid import helpers  # pylint: disable=import-outside-toplevel
        bin_op = aug_opnode.op.strip("=")
        aug_op = aug_opnode.op
        if OperatorNode._same_type(left_type, right_type):
            methods = [
                OperatorNode._aug_op(left, aug_opnode, aug_op, right, context),
                OperatorNode._bin_op(left, aug_opnode, bin_op, right, context),
            ]
        elif helpers.is_subtype(left_type, right_type):
            methods = [
                OperatorNode._aug_op(left, aug_opnode, aug_op, right, context),
                OperatorNode._bin_op(left, aug_opnode, bin_op, right, context),
            ]
        elif helpers.is_supertype(left_type, right_type):
            methods = [
                OperatorNode._aug_op(left, aug_opnode, aug_op, right, context),
                OperatorNode._bin_op(
                    right, aug_opnode, bin_op, left, reverse_context, reverse=True
                ),
                OperatorNode._bin_op(left, aug_opnode, bin_op, right, context),
            ]
        else:
            methods = [
                OperatorNode._aug_op(left, aug_opnode, aug_op, right, context),
                OperatorNode._bin_op(left, aug_opnode, bin_op, right, context),
                OperatorNode._bin_op(
                    right, aug_opnode, bin_op, left, reverse_context, reverse=True
                ),
            ]
        return methods
Referenced by astroid.nodes.node_classes.AugAssign._infer_augassign().
_get_binop_contexts()
astroid.nodes._base_nodes.OperatorNode._get_binop_contexts (context, left, right) static protected
Get contexts for binary operations.
This will return two inference contexts, the first one
for x.__op__(y), the other one for y.__rop__(x), where
only the arguments are inversed.
Definition at line 483 of file _base_nodes.py.
    def _get_binop_contexts(context, left, right):
        """Get contexts for binary operations.
        This will return two inference contexts, the first one
        for x.__op__(y), the other one for y.__rop__(x), where
        only the arguments are inversed.
        """
        # The order is important, since the first one should be
        # left.__op__(right).
        for arg in (right, left):
            new_context = context.clone()
            new_context.callcontext = CallContext(args=[arg])
            new_context.boundnode = None
            yield new_context
_get_binop_flow()
list[partial[Generator[InferenceResult]]] astroid.nodes._base_nodes.OperatorNode._get_binop_flow (InferenceResult left, InferenceResult | None left_type, nodes.AugAssign | nodes.BinOp binary_opnode, InferenceResult right, InferenceResult | None right_type, InferenceContext context, InferenceContext reverse_context) static protected
Get the flow for binary operations.
The rules are a bit messy:
    * if left and right have the same type, then only one
    method will be called, left.__op__(right)
    * if left and right are unrelated typewise, then first
    left.__op__(right) is tried and if this does not exist
    or returns NotImplemented, then right.__rop__(left) is tried.
    * if left is a subtype of right, then only left.__op__(right)
    is tried.
    * if left is a supertype of right, then right.__rop__(left)
    is first tried and then left.__op__(right)
Definition at line 561 of file _base_nodes.py.
    ) -> list[partial[Generator[InferenceResult]]]:
        """Get the flow for binary operations.
        The rules are a bit messy:
            * if left and right have the same type, then only one
            method will be called, left.__op__(right)
            * if left and right are unrelated typewise, then first
            left.__op__(right) is tried and if this does not exist
            or returns NotImplemented, then right.__rop__(left) is tried.
            * if left is a subtype of right, then only left.__op__(right)
            is tried.
            * if left is a supertype of right, then right.__rop__(left)
            is first tried and then left.__op__(right)
        """
        from astroid import helpers  # pylint: disable=import-outside-toplevel
        op = binary_opnode.op
        if OperatorNode._same_type(left_type, right_type):
            methods = [OperatorNode._bin_op(left, binary_opnode, op, right, context)]
        elif helpers.is_subtype(left_type, right_type):
            methods = [OperatorNode._bin_op(left, binary_opnode, op, right, context)]
        elif helpers.is_supertype(left_type, right_type):
            methods = [
                OperatorNode._bin_op(
                    right, binary_opnode, op, left, reverse_context, reverse=True
                ),
                OperatorNode._bin_op(left, binary_opnode, op, right, context),
            ]
        else:
            methods = [
                OperatorNode._bin_op(left, binary_opnode, op, right, context),
                OperatorNode._bin_op(
                    right, binary_opnode, op, left, reverse_context, reverse=True
                ),
            ]
        if (
            PY310_PLUS
            and op == "|"
            and (
                isinstance(left, (bases.UnionType, nodes.ClassDef))
                or isinstance(left, nodes.Const)
                and left.value is None
            )
            and (
                isinstance(right, (bases.UnionType, nodes.ClassDef))
                or isinstance(right, nodes.Const)
                and right.value is None
            )
        ):
            methods.extend([partial(OperatorNode._bin_op_or_union_type, left, right)])
        return methods
Referenced by astroid.nodes.node_classes.BinOp._infer_binop().
_infer_binary_operation()
Generator[InferenceResult | util.BadBinaryOperationMessage] astroid.nodes._base_nodes.OperatorNode._infer_binary_operation (InferenceResult left, InferenceResult right, nodes.AugAssign | nodes.BinOp binary_opnode, InferenceContext context, GetFlowFactory flow_factory) static protected
Infer a binary operation between a left operand and a right operand.
This is used by both normal binary operations and augmented binary
operations, the only difference is the flow factory used.
Definition at line 624 of file _base_nodes.py.
    ) -> Generator[InferenceResult | util.BadBinaryOperationMessage]:
        """Infer a binary operation between a left operand and a right operand.
        This is used by both normal binary operations and augmented binary
        operations, the only difference is the flow factory used.
        """
        from astroid import helpers  # pylint: disable=import-outside-toplevel
        context, reverse_context = OperatorNode._get_binop_contexts(
            context, left, right
        )
        left_type = helpers.object_type(left)
        right_type = helpers.object_type(right)
        methods = flow_factory(
            left, left_type, binary_opnode, right, right_type, context, reverse_context
        )
        for method in methods:
            try:
                results = list(method())
            except AttributeError:
                continue
            except AttributeInferenceError:
                continue
            except InferenceError:
                yield util.Uninferable
                return
            else:
                if any(isinstance(result, util.UninferableBase) for result in results):
                    yield util.Uninferable
                    return
                if all(map(OperatorNode._is_not_implemented, results)):
                    continue
                not_implemented = sum(
                    1 for result in results if OperatorNode._is_not_implemented(result)
                )
                if not_implemented and not_implemented != len(results):
                    # Can't infer yet what this is.
                    yield util.Uninferable
                    return
                yield from results
                return
        # The operation doesn't seem to be supported so let the caller know about it
        yield util.BadBinaryOperationMessage(left_type, binary_opnode.op, right_type)
Referenced by astroid.nodes.node_classes.AugAssign._infer_augassign(), and astroid.nodes.node_classes.BinOp._infer_binop().
_infer_old_style_string_formatting()
tuple[util.UninferableBase | nodes.Const] astroid.nodes._base_nodes.OperatorNode._infer_old_style_string_formatting (nodes.Const instance, nodes.NodeNG other, InferenceContext context) static protected
Infer the result of '"string" % ...'.
TODO: Instead of returning Uninferable we should rely
on the call to '%' to see if the result is actually uninferable.
Definition at line 351 of file _base_nodes.py.
    ) -> tuple[util.UninferableBase | nodes.Const]:
        """Infer the result of '"string" % ...'.
        TODO: Instead of returning Uninferable we should rely
        on the call to '%' to see if the result is actually uninferable.
        """
        if isinstance(other, nodes.Tuple):
            if util.Uninferable in other.elts:
                return (util.Uninferable,)
            inferred_positional = [util.safe_infer(i, context) for i in other.elts]
            if all(isinstance(i, nodes.Const) for i in inferred_positional):
                values = tuple(i.value for i in inferred_positional)
            else:
                values = None
        elif isinstance(other, nodes.Dict):
            values: dict[Any, Any] = {}
            for pair in other.items:
                key = util.safe_infer(pair[0], context)
                if not isinstance(key, nodes.Const):
                    return (util.Uninferable,)
                value = util.safe_infer(pair[1], context)
                if not isinstance(value, nodes.Const):
                    return (util.Uninferable,)
                values[key.value] = value.value
        elif isinstance(other, nodes.Const):
            values = other.value
        else:
            return (util.Uninferable,)
        try:
            return (nodes.const_factory(instance.value % values),)
        except (TypeError, KeyError, ValueError):
            return (util.Uninferable,)
_invoke_binop_inference()
Generator[InferenceResult] astroid.nodes._base_nodes.OperatorNode._invoke_binop_inference (InferenceResult instance, nodes.AugAssign | nodes.BinOp opnode, str op, InferenceResult other, InferenceContext context, str method_name) static protected
Invoke binary operation inference on the given instance.
Definition at line 388 of file _base_nodes.py.
    ) -> Generator[InferenceResult]:
        """Invoke binary operation inference on the given instance."""
        methods = dunder_lookup.lookup(instance, method_name)
        context = bind_context_to_node(context, instance)
        method = methods[0]
        context.callcontext.callee = method
        if (
            isinstance(instance, nodes.Const)
            and isinstance(instance.value, str)
            and op == "%"
        ):
            return iter(
                OperatorNode._infer_old_style_string_formatting(
                    instance, other, context
                )
            )
        try:
            inferred = next(method.infer(context=context))
        except StopIteration as e:
            raise InferenceError(node=method, context=context) from e
        if isinstance(inferred, util.UninferableBase):
            raise InferenceError
        if not isinstance(
            instance,
            (nodes.Const, nodes.Tuple, nodes.List, nodes.ClassDef, bases.Instance),
        ):
            raise InferenceError  # pragma: no cover # Used as a failsafe
        return instance.infer_binary_op(opnode, op, other, context, inferred)
_is_not_implemented()
bool astroid.nodes._base_nodes.OperatorNode._is_not_implemented (const) static protected
Check if the given const node is NotImplemented.
Definition at line 346 of file _base_nodes.py.
    def _is_not_implemented(const) -> bool:
        """Check if the given const node is NotImplemented."""
        return isinstance(const, nodes.Const) and const.value is NotImplemented
_same_type()
bool astroid.nodes._base_nodes.OperatorNode._same_type (type1, type2) static protected
Check if type1 is the same as type2.
Definition at line 499 of file _base_nodes.py.
    def _same_type(type1, type2) -> bool:
        """Check if type1 is the same as type2."""
        return type1.qname() == type2.qname()
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/astroid/nodes/_base_nodes.py