Read&Watch: PIL.PdfParser.XrefTable Class Reference
PIL.PdfParser.XrefTable Class Reference
Public Member Functions
None __init__ (self)
None __setitem__ (self, int key, tuple[int, int] value)
tuple[int, int] __getitem__ (self, int key)
None __delitem__ (self, int key)
bool __contains__ (self, int key)
int __len__ (self)
set[int] keys (self)
int write (self, IO[bytes] f)
Public Attributes
tuple existing_entries
tuple new_entries
dict deleted_entries = {0: 65536}
bool reading_finished = False
Detailed Description
Definition at line 114 of file PdfParser.py.
Constructor & Destructor Documentation
__init__()
None PIL.PdfParser.XrefTable.__init__ (self)
Definition at line 115 of file PdfParser.py.
    def __init__(self) -> None:
        self.existing_entries: dict[int, tuple[int, int]] = (
            {}
        )  # object ID => (offset, generation)
        self.new_entries: dict[int, tuple[int, int]] = (
            {}
        )  # object ID => (offset, generation)
        self.deleted_entries = {0: 65536}  # object ID => generation
        self.reading_finished = False
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
__contains__()
bool PIL.PdfParser.XrefTable.__contains__ (self, int key)
Definition at line 153 of file PdfParser.py.
    def __contains__(self, key: int) -> bool:
        return key in self.existing_entries or key in self.new_entries
References existing_entries, and new_entries.
__delitem__()
None PIL.PdfParser.XrefTable.__delitem__ (self, int key)
Definition at line 139 of file PdfParser.py.
    def __delitem__(self, key: int) -> None:
        if key in self.new_entries:
            generation = self.new_entries[key][1] + 1
            del self.new_entries[key]
            self.deleted_entries[key] = generation
        elif key in self.existing_entries:
            generation = self.existing_entries[key][1] + 1
            self.deleted_entries[key] = generation
        elif key in self.deleted_entries:
            generation = self.deleted_entries[key]
        else:
            msg = f"object ID {key} cannot be deleted because it doesn't exist"
            raise IndexError(msg)
References deleted_entries, existing_entries, and new_entries.
__getitem__()
tuple[int, int] PIL.PdfParser.XrefTable.__getitem__ (self, int key)
Definition at line 133 of file PdfParser.py.
    def __getitem__(self, key: int) -> tuple[int, int]:
        try:
            return self.new_entries[key]
        except KeyError:
            return self.existing_entries[key]
References existing_entries, and new_entries.
__len__()
int PIL.PdfParser.XrefTable.__len__ (self)
Definition at line 156 of file PdfParser.py.
    def __len__(self) -> int:
        return len(
            set(self.existing_entries.keys())
            | set(self.new_entries.keys())
            | set(self.deleted_entries.keys())
        )
References deleted_entries, existing_entries, keys(), and new_entries.
__setitem__()
None PIL.PdfParser.XrefTable.__setitem__ (self, int key, tuple[int, int] value)
Definition at line 125 of file PdfParser.py.
    def __setitem__(self, key: int, value: tuple[int, int]) -> None:
        if self.reading_finished:
            self.new_entries[key] = value
        else:
            self.existing_entries[key] = value
        if key in self.deleted_entries:
            del self.deleted_entries[key]
References deleted_entries, existing_entries, new_entries, and reading_finished.
keys()
set[int] PIL.PdfParser.XrefTable.keys (self)
Definition at line 163 of file PdfParser.py.
    def keys(self) -> set[int]:
        return (
            set(self.existing_entries.keys()) - set(self.deleted_entries.keys())
        ) | set(self.new_entries.keys())
References deleted_entries, existing_entries, keys(), and new_entries.
Referenced by pip._vendor.distlib.metadata.LegacyMetadata.__iter__(), __len__(), pip._vendor.distlib.metadata.LegacyMetadata.items(), keys(), pip._vendor.distlib.metadata.LegacyMetadata.values(), and write().
write()
int PIL.PdfParser.XrefTable.write (self, IO[bytes] f)
Definition at line 168 of file PdfParser.py.
    def write(self, f: IO[bytes]) -> int:
        keys = sorted(set(self.new_entries.keys()) | set(self.deleted_entries.keys()))
        deleted_keys = sorted(set(self.deleted_entries.keys()))
        startxref = f.tell()
        f.write(b"xref\n")
        while keys:
            # find a contiguous sequence of object IDs
            prev: int | None = None
            for index, key in enumerate(keys):
                if prev is None or prev + 1 == key:
                    prev = key
                else:
                    contiguous_keys = keys[:index]
                    keys = keys[index:]
                    break
            else:
                contiguous_keys = keys
                keys = []
            f.write(b"%d %d\n" % (contiguous_keys[0], len(contiguous_keys)))
            for object_id in contiguous_keys:
                if object_id in self.new_entries:
                    f.write(b"%010d %05d n \n" % self.new_entries[object_id])
                else:
                    this_deleted_object_id = deleted_keys.pop(0)
                    check_format_condition(
                        object_id == this_deleted_object_id,
                        f"expected the next deleted object ID to be {object_id}, "
                        f"instead found {this_deleted_object_id}",
                    )
                    try:
                        next_in_linked_list = deleted_keys[0]
                    except IndexError:
                        next_in_linked_list = 0
                    f.write(
                        b"%010d %05d f \n"
                        % (next_in_linked_list, self.deleted_entries[object_id])
                    )
        return startxref
References PIL.PdfParser.check_format_condition(), deleted_entries, keys(), and new_entries.
Referenced by pylint.reporters.ureports.text_writer.TextWriter.default_table(), pylint.reporters.ureports.text_writer.TextWriter.visit_text(), and pylint.reporters.ureports.base_writer.BaseWriter.writeln().
Member Data Documentation
deleted_entries
dict PIL.PdfParser.XrefTable.deleted_entries = {0: 65536}
Definition at line 122 of file PdfParser.py.
Referenced by __delitem__(), __len__(), __setitem__(), keys(), and write().
existing_entries
tuple PIL.PdfParser.XrefTable.existing_entries
Initial value:
=  (
            {}
        )
Definition at line 116 of file PdfParser.py.
Referenced by __contains__(), __delitem__(), __getitem__(), __len__(), __setitem__(), and keys().
new_entries
tuple PIL.PdfParser.XrefTable.new_entries
Initial value:
=  (
            {}
        )
Definition at line 119 of file PdfParser.py.
Referenced by __contains__(), __delitem__(), __getitem__(), __len__(), __setitem__(), keys(), and write().
reading_finished
bool PIL.PdfParser.XrefTable.reading_finished = False
Definition at line 123 of file PdfParser.py.
Referenced by __setitem__().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/PIL/PdfParser.py