Read&Watch: django.template.backends.dummy.TemplateStrings Class Reference
django.template.backends.dummy.TemplateStrings Class Reference
Public Member Functions
__init__ (self, params)
from_string (self, template_code)
get_template (self, template_name)
Public Member Functions inherited from django.template.backends.base.BaseEngine
__init__ (self, params)
check (self, **kwargs)
app_dirname (self)
template_dirs (self)
iter_template_filenames (self, template_name)
Additional Inherited Members
Public Attributes inherited from django.template.backends.base.BaseEngine
name = params.pop("NAME")
dirs = list(params.pop("DIRS"))
app_dirs = params.pop("APP_DIRS")
template_dirs
Detailed Description
Definition at line 11 of file dummy.py.
Constructor & Destructor Documentation
__init__()
django.template.backends.dummy.TemplateStrings.__init__ (self, params)
Definition at line 14 of file dummy.py.
    def __init__(self, params):
        params = params.copy()
        options = params.pop("OPTIONS").copy()
        if options:
            raise ImproperlyConfigured("Unknown options: {}".format(", ".join(options)))
        super().__init__(params)
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Function Documentation
from_string()
django.template.backends.dummy.TemplateStrings.from_string (self, template_code)
Create and return a template for the given source code.
This method is optional.
Reimplemented from django.template.backends.base.BaseEngine.
Definition at line 21 of file dummy.py.
    def from_string(self, template_code):
        return Template(template_code)
get_template()
django.template.backends.dummy.TemplateStrings.get_template (self, template_name)
Load and return a template for the given name.
Raise TemplateDoesNotExist if no such template exists.
Reimplemented from django.template.backends.base.BaseEngine.
Definition at line 24 of file dummy.py.
    def get_template(self, template_name):
        tried = []
        for template_file in self.iter_template_filenames(template_name):
            try:
                with open(template_file, encoding="utf-8") as fp:
                    template_code = fp.read()
            except FileNotFoundError:
                tried.append(
                    (
                        Origin(template_file, template_name, self),
                        "Source does not exist",
                    )
                )
            else:
                return Template(template_code)
        raise TemplateDoesNotExist(template_name, tried=tried, backend=self)
References django.template.backends.base.BaseEngine.iter_template_filenames().
Referenced by django.template.engine.Engine.render_to_string(), and django.template.engine.Engine.select_template().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/template/backends/dummy.py