Read&Watch: apscheduler.events.JobSubmissionEvent Class Reference
apscheduler.events.JobSubmissionEvent Class Reference
Public Member Functions
__init__ (self, code, job_id, jobstore, scheduled_run_times)
Public Member Functions inherited from apscheduler.events.JobEvent
__init__ (self, code, job_id, jobstore)
Public Member Functions inherited from apscheduler.events.SchedulerEvent
__init__ (self, code, alias=None)
__repr__ (self)
Public Attributes
scheduled_run_times = scheduled_run_times
Public Attributes inherited from apscheduler.events.JobEvent
job_id = job_id
jobstore = jobstore
Public Attributes inherited from apscheduler.events.SchedulerEvent
code = code
alias = alias
Detailed Description
An event that concerns the submission of a job to its executor.
:ivar scheduled_run_times: a list of datetimes when the job was intended to run
Definition at line 98 of file events.py.
Constructor & Destructor Documentation
__init__()
apscheduler.events.JobSubmissionEvent.__init__ (self, code, job_id, jobstore, scheduled_run_times)
Definition at line 105 of file events.py.
    def __init__(self, code, job_id, jobstore, scheduled_run_times):
        super().__init__(code, job_id, jobstore)
        self.scheduled_run_times = scheduled_run_times
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Data Documentation
scheduled_run_times
apscheduler.events.JobSubmissionEvent.scheduled_run_times = scheduled_run_times
Definition at line 107 of file events.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/apscheduler/events.py