Read&Watch: astroid.interpreter._import.spec.ZipFinder Class Reference
astroid.interpreter._import.spec.ZipFinder Class Reference
Public Member Functions
None __init__ (self, Sequence[str] path)
ModuleSpec|None find_module (self, str modname, Sequence[str] module_parts, list[str] processed, Sequence[str]|None submodule_path)
Public Member Functions inherited from astroid.interpreter._import.spec.Finder
None __init__ (self, Sequence[str]|None path=None)
Sequence[str]|None contribute_to_path (self, ModuleSpec spec, list[str] processed)
Additional Inherited Members
Protected Attributes inherited from astroid.interpreter._import.spec.Finder
_path = path or sys.path
Detailed Description
Finder that knows how to find a module inside zip files.
Definition at line 287 of file spec.py.
Constructor & Destructor Documentation
__init__()
None astroid.interpreter._import.spec.ZipFinder.__init__ (self, Sequence[str] path)
Definition at line 290 of file spec.py.
    def __init__(self, path: Sequence[str]) -> None:
        super().__init__(path)
        for entry_path in path:
            if entry_path not in sys.path_importer_cache:
                try:
                    sys.path_importer_cache[entry_path] = zipimport.zipimporter(  # type: ignore[assignment]
                        entry_path
                    )
                except zipimport.ZipImportError:
                    continue
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Function Documentation
find_module()
ModuleSpec | None astroid.interpreter._import.spec.ZipFinder.find_module (self, str modname, Sequence[str] module_parts, list[str] processed, Sequence[str] | None submodule_path)
Find the given module.
Each finder is responsible for each protocol of finding, as long as
they all return a ModuleSpec.
:param modname: The module which needs to be searched.
:param module_parts: It should be a list of strings,
                          where each part contributes to the module's
                          namespace.
:param processed: What parts from the module parts were processed
                       so far.
:param submodule_path: A list of paths where the module
                            can be looked into.
:returns: A ModuleSpec, describing how and where the module was found,
          None, otherwise.
Reimplemented from astroid.interpreter._import.spec.Finder.
Definition at line 301 of file spec.py.
    ) -> ModuleSpec | None:
        try:
            file_type, filename, path = _search_zip(module_parts)
        except ImportError:
            return None
        return ModuleSpec(
            name=modname,
            location=filename,
            origin="egg",
            type=file_type,
            submodule_search_locations=path,
        )
References astroid.interpreter._import.spec._search_zip().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/astroid/interpreter/_import/spec.py