Read&Watch: pip._vendor.rich.style.StyleStack Class Reference
pip._vendor.rich.style.StyleStack Class Reference
Public Member Functions
None __init__ (self, "Style" default_style)
str __repr__ (self)
Style current (self)
None push (self, Style style)
Style pop (self)
Protected Attributes
list _stack = [default_style]
Detailed Description
A stack of styles.
Definition at line 765 of file style.py.
Constructor & Destructor Documentation
__init__()
None pip._vendor.rich.style.StyleStack.__init__ (self, "Style" default_style)
Definition at line 770 of file style.py.
    def __init__(self, default_style: "Style") -> None:
        self._stack: List[Style] = [default_style]
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
__repr__()
str pip._vendor.rich.style.StyleStack.__repr__ (self)
Definition at line 773 of file style.py.
    def __repr__(self) -> str:
        return f"<stylestack {self._stack!r}>"
current()
Style pip._vendor.rich.style.StyleStack.current (self)
Get the Style at the top of the stack.
Definition at line 777 of file style.py.
    def current(self) -> Style:
        """Get the Style at the top of the stack."""
        return self._stack[-1]
References _stack.
pop()
Style pip._vendor.rich.style.StyleStack.pop (self)
Pop last style and discard.
Returns:
    Style: New current style (also available as stack.current)
Definition at line 789 of file style.py.
    def pop(self) -> Style:
        """Pop last style and discard.
        Returns:
            Style: New current style (also available as stack.current)
        """
        self._stack.pop()
        return self._stack[-1]
References _stack, and pop().
Referenced by pop().
push()
None pip._vendor.rich.style.StyleStack.push (self, Style style)
Push a new style on to the stack.
Args:
    style (Style): New style to combine with current style.
Definition at line 781 of file style.py.
    def push(self, style: Style) -> None:
        """Push a new style on to the stack.
        Args:
            style (Style): New style to combine with current style.
        """
        self._stack.append(self._stack[-1] + style)
References _stack.
Member Data Documentation
_stack
list pip._vendor.rich.style.StyleStack._stack = [default_style] protected
Definition at line 771 of file style.py.
Referenced by current(), pop(), and push().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/rich/style.py