Read&Watch: django.middleware.clickjacking.XFrameOptionsMiddleware Class Reference
django.middleware.clickjacking.XFrameOptionsMiddleware Class Reference
Public Member Functions
process_response (self, request, response)
get_xframe_options_value (self, request, response)
Public Member Functions inherited from django.utils.deprecation.MiddlewareMixin
__init__ (self, get_response)
__repr__ (self)
__call__ (self, request)
__acall__ (self, request)
Additional Inherited Members
Public Attributes inherited from django.utils.deprecation.MiddlewareMixin
get_response = get_response
async_mode = iscoroutinefunction(self.get_response)
Static Public Attributes inherited from django.utils.deprecation.MiddlewareMixin
bool sync_capable = True
bool async_capable = True
Detailed Description
Set the X-Frame-Options HTTP header in HTTP responses.
Do not set the header if it's already set or if the response contains
a xframe_options_exempt value set to True.
By default, set the X-Frame-Options header to 'DENY', meaning the response
cannot be displayed in a frame, regardless of the site attempting to do so.
To enable the response to be loaded on a frame within the same site, set
X_FRAME_OPTIONS in your project's Django settings to 'SAMEORIGIN'.
Definition at line 12 of file clickjacking.py.
Member Function Documentation
get_xframe_options_value()
django.middleware.clickjacking.XFrameOptionsMiddleware.get_xframe_options_value (self, request, response)
Get the value to set for the X_FRAME_OPTIONS header. Use the value from
the X_FRAME_OPTIONS setting, or 'DENY' if not set.
This method can be overridden if needed, allowing it to vary based on
the request or response.
Definition at line 40 of file clickjacking.py.
    def get_xframe_options_value(self, request, response):
        """
        Get the value to set for the X_FRAME_OPTIONS header. Use the value from
        the X_FRAME_OPTIONS setting, or 'DENY' if not set.
        This method can be overridden if needed, allowing it to vary based on
        the request or response.
        """
        return getattr(settings, "X_FRAME_OPTIONS", "DENY").upper()
Referenced by process_response().
process_response()
django.middleware.clickjacking.XFrameOptionsMiddleware.process_response (self, request, response)
Definition at line 25 of file clickjacking.py.
    def process_response(self, request, response):
        # Don't set it if it's already in the response
        if response.get("X-Frame-Options") is not None:
            return response
        # Don't set it if they used @xframe_options_exempt
        if getattr(response, "xframe_options_exempt", False):
            return response
        response.headers["X-Frame-Options"] = self.get_xframe_options_value(
            request,
            response,
        )
        return response
References get_xframe_options_value().
Referenced by django.utils.deprecation.MiddlewareMixin.__acall__(), django.utils.deprecation.MiddlewareMixin.__call__(), and pip._vendor.rich.prompt.PromptBase.__call__().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/middleware/clickjacking.py