Read&Watch: pylint.pyreverse.inspector.IdGeneratorMixIn Class Reference
pylint.pyreverse.inspector.IdGeneratorMixIn Class Reference
Public Member Functions
None __init__ (self, int start_value=0)
None init_counter (self, int start_value=0)
int generate_id (self)
Public Attributes
id_count = start_value
Detailed Description
Mixin adding the ability to generate integer uid.
Definition at line 46 of file inspector.py.
Constructor & Destructor Documentation
__init__()
None pylint.pyreverse.inspector.IdGeneratorMixIn.__init__ (self, int start_value = 0)
Definition at line 49 of file inspector.py.
    def __init__(self, start_value: int = 0) -> None:
        self.id_count = start_value
Member Function Documentation
generate_id()
int pylint.pyreverse.inspector.IdGeneratorMixIn.generate_id (self)
Generate a new identifier.
Definition at line 56 of file inspector.py.
    def generate_id(self) -> int:
        """Generate a new identifier."""
        self.id_count += 1
        return self.id_count
References id_count.
Referenced by pylint.pyreverse.inspector.Linker.visit_classdef(), pylint.pyreverse.inspector.Linker.visit_functiondef(), pylint.pyreverse.inspector.Linker.visit_module(), and pylint.pyreverse.inspector.Linker.visit_project().
init_counter()
None pylint.pyreverse.inspector.IdGeneratorMixIn.init_counter (self, int start_value = 0)
Init the id counter.
Definition at line 52 of file inspector.py.
    def init_counter(self, start_value: int = 0) -> None:
        """Init the id counter."""
        self.id_count = start_value
References id_count.
Member Data Documentation
id_count
pylint.pyreverse.inspector.IdGeneratorMixIn.id_count = start_value
Definition at line 50 of file inspector.py.
Referenced by generate_id(), and init_counter().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pylint/pyreverse/inspector.py