Read&Watch: apscheduler.executors.base.MaxInstancesReachedError Class Reference
apscheduler.executors.base.MaxInstancesReachedError Class Reference
Public Member Functions
__init__ (self, job)
Detailed Description
Definition at line 17 of file base.py.
Constructor & Destructor Documentation
__init__()
apscheduler.executors.base.MaxInstancesReachedError.__init__ (self, job)
Definition at line 18 of file base.py.
    def __init__(self, job):
        super().__init__(
            'Job "%s" has already reached its maximum number of instances (%d)'
            % (job.id, job.max_instances)
        )
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/apscheduler/executors/base.py