Read&Watch: pip._vendor.typing_extensions.Annotated Class Reference
pip._vendor.typing_extensions.Annotated Class Reference
Public Member Functions
__new__ (cls, *args, **kwargs)
__class_getitem__ (cls, params)
__init_subclass__ (cls, *args, **kwargs)
Detailed Description
Add context specific metadata to a type.
Example: Annotated[int, runtime_check.Unsigned] indicates to the
hypothetical runtime_check module that this type is an unsigned int.
Every other consumer of this type can ignore this metadata and treat
this type as int.
The first argument to Annotated must be a valid type (and will be in
the __origin__ field), the remaining arguments are kept as a tuple in
the __extra__ field.
Details:
- It's an error to call `Annotated` with less than two arguments.
- Nested Annotated are flattened::
    Annotated[Annotated[T, Ann1, Ann2], Ann3] == Annotated[T, Ann1, Ann2, Ann3]
- Instantiating an annotated type is equivalent to instantiating the
underlying type::
    Annotated[C, Ann1](5) == C(5)
- Annotated can be used as a generic type alias::
    Optimized = Annotated[T, runtime.Optimize()]
    Optimized[int] == Annotated[int, runtime.Optimize()]
    OptimizedList = Annotated[List[T], runtime.Optimize()]
    OptimizedList[int] == Annotated[List[int], runtime.Optimize()]
Definition at line 1287 of file typing_extensions.py.
Member Function Documentation
__class_getitem__()
pip._vendor.typing_extensions.Annotated.__class_getitem__ (cls, params)
Definition at line 1326 of file typing_extensions.py.
        def __class_getitem__(cls, params):
            if not isinstance(params, tuple) or len(params) < 2:
                raise TypeError("Annotated[...] should be used "
                                "with at least two arguments (a type and an "
                                "annotation).")
            allowed_special_forms = (ClassVar, Final)
            if get_origin(params[0]) in allowed_special_forms:
                origin = params[0]
            else:
                msg = "Annotated[t, ...]: t must be a type."
                origin = typing._type_check(params[0], msg)
            metadata = tuple(params[1:])
            return _AnnotatedAlias(origin, metadata)
References pip._vendor.typing_extensions.get_origin.
__init_subclass__()
pip._vendor.typing_extensions.Annotated.__init_subclass__ (cls, * args, ** kwargs)
Definition at line 1340 of file typing_extensions.py.
        def __init_subclass__(cls, *args, **kwargs):
            raise TypeError(
                f"Cannot subclass {cls.__module__}.Annotated"
            )
# Python 3.8 has get_origin() and get_args() but those implementations aren't
# Annotated-aware, so we can't use those. Python 3.9's versions don't support
# ParamSpecArgs and ParamSpecKwargs, so only Python 3.10's versions will do.
__new__()
pip._vendor.typing_extensions.Annotated.__new__ (cls, * args, ** kwargs)
Definition at line 1322 of file typing_extensions.py.
        def __new__(cls, *args, **kwargs):
            raise TypeError("Type Annotated cannot be instantiated.")
Referenced by apscheduler.triggers.combining.BaseCombiningTrigger.__setstate__(), pip._vendor.rich.style.Style._add(), pip._vendor.rich.style.Style.clear_meta_and_links(), yaml.constructor.SafeConstructor.construct_yaml_object(), pip._vendor.rich.style.Style.copy(), pip._vendor.rich.style.Style.from_color(), pip._vendor.rich.json.JSON.from_data(), pip._vendor.rich.style.Style.from_meta(), yaml.constructor.FullConstructor.make_python_instance(), pip._vendor.rich.style.Style.update_link(), and pip._vendor.rich.style.Style.without_color().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/typing_extensions.py