Read&Watch: pylint.checkers.base.name_checker.checker.NameChecker Class Reference
pylint.checkers.base.name_checker.checker.NameChecker Class Reference
Public Member Functions
None __init__ (self, PyLinter linter)
None open (self)
None visit_module (self, nodes.Module node)
None leave_module (self, nodes.Module _)
None visit_classdef (self, nodes.ClassDef node)
None visit_functiondef (self, nodes.FunctionDef node)
None visit_assignname (self, nodes.AssignName node)
Public Member Functions inherited from pylint.checkers.base_checker.BaseChecker
None __init__ (self, PyLinter linter)
bool __gt__ (self, Any other)
bool __eq__ (self, object other)
int __hash__ (self)
str __repr__ (self)
str __str__ (self)
str get_full_documentation (self, dict[str, MessageDefinitionTuple] msgs, Iterable[tuple[str, OptionDict, Any]] options, Sequence[tuple[str, str, ReportsCallable]] reports, str|None doc=None, str|None module=None, bool show_options=True)
None add_message (self, str msgid, int|None line=None, nodes.NodeNG|None node=None, Any args=None, Confidence|None confidence=None, int|None col_offset=None, int|None end_lineno=None, int|None end_col_offset=None)
None check_consistency (self)
MessageDefinition create_message_definition_from_tuple (self, str msgid, MessageDefinitionTuple msg_tuple)
list[MessageDefinition] messages (self)
None close (self)
Any get_map_data (self)
None reduce_map_data (self, PyLinter linter, list[Any] data)
Public Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
None __init__ (self, _ArgumentsManager arguments_manager)
Static Public Attributes
None visit_asyncfunctiondef = visit_functiondef
Static Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
str name = ""
dict msgs = {}
tuple reports = ()
bool enabled = True
Static Public Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
tuple options = ()
dict option_groups_descs = {}
Protected Member Functions
tuple[dict[str, Pattern[str]], dict[str, str]] _create_naming_rules (self)
None _recursive_check_names (self, list[nodes.AssignName] args)
str _find_name_group (self, str node_type)
None _raise_name_warning (self, str|None prevalent_group, nodes.NodeNG node, str node_type, str name, interfaces.Confidence confidence, str warning="invalid-name")
bool _name_allowed_by_regex (self, str name)
bool _name_disallowed_by_regex (self, str name)
None _check_name (self, str node_type, str name, nodes.NodeNG node, interfaces.Confidence confidence=interfaces.HIGH, bool disallowed_check_only=False)
None _check_typevar (self, str name, nodes.AssignName node)
Protected Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
Any _option_value (self, str opt)
Iterator[ tuple[str, list[tuple[str, OptionDict, Any]]]|tuple[None, dict[str, list[tuple[str, OptionDict, Any]]]]] _options_by_section (self)
Iterator[tuple[str, OptionDict, Any]] _options_and_values (self, Options|None options=None)
Static Protected Member Functions
bool _assigns_typevar (nodes.NodeNG|None node)
bool _assigns_typealias (nodes.NodeNG|None node)
Protected Attributes
dict _name_group = {}
dict _bad_names = {}
dict _name_regexps = {}
dict _name_hints = {}
list _good_names_rgxs_compiled = []
list _bad_names_rgxs_compiled = []
Protected Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
_arguments_manager = arguments_manager
Static Protected Attributes
tuple _options
Additional Inherited Members
Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
linter = linter
messages
Detailed Description
Definition at line 156 of file checker.py.
Constructor & Destructor Documentation
__init__()
None pylint.checkers.base.name_checker.checker.NameChecker.__init__ (self, PyLinter linter)
Definition at line 276 of file checker.py.
    def __init__(self, linter: PyLinter) -> None:
        super().__init__(linter)
        self._name_group: dict[str, str] = {}
        self._bad_names: dict[str, dict[str, list[_BadNamesTuple]]] = {}
        self._name_regexps: dict[str, re.Pattern[str]] = {}
        self._name_hints: dict[str, str] = {}
        self._good_names_rgxs_compiled: list[re.Pattern[str]] = []
        self._bad_names_rgxs_compiled: list[re.Pattern[str]] = []
References __init__().
Referenced by __init__().
Member Function Documentation
_assigns_typealias()
bool pylint.checkers.base.name_checker.checker.NameChecker._assigns_typealias (nodes.NodeNG | None node) static protected
Check if a node is assigning a TypeAlias.
Definition at line 608 of file checker.py.
    def _assigns_typealias(node: nodes.NodeNG | None) -> bool:
        """Check if a node is assigning a TypeAlias."""
        inferred = utils.safe_infer(node)
        if isinstance(inferred, nodes.ClassDef):
            qname = inferred.qname()
            if qname == "typing.TypeAlias":
                return True
            if qname == ".Union":
                # Union is a special case because it can be used as a type alias
                # or as a type annotation. We only want to check the former.
                assert node is not None
                return not isinstance(node.parent, nodes.AnnAssign)
        elif isinstance(inferred, nodes.FunctionDef):
            # TODO: when py3.12 is minimum, remove this condition
            # TypeAlias became a class in python 3.12
            if inferred.qname() == "typing.TypeAlias":
                return True
        return False
Referenced by visit_assignname().
_assigns_typevar()
bool pylint.checkers.base.name_checker.checker.NameChecker._assigns_typevar (nodes.NodeNG | None node) static protected
Check if a node is assigning a TypeVar.
Definition at line 596 of file checker.py.
    def _assigns_typevar(node: nodes.NodeNG | None) -> bool:
        """Check if a node is assigning a TypeVar."""
        if isinstance(node, astroid.Call):
            inferred = utils.safe_infer(node.func)
            if (
                isinstance(inferred, astroid.ClassDef)
                and inferred.qname() in TYPE_VAR_QNAME
            ):
                return True
        return False
Referenced by visit_assignname().
_check_name()
None pylint.checkers.base.name_checker.checker.NameChecker._check_name (self, str node_type, str name, nodes.NodeNG node, interfaces.Confidence confidence = interfaces.HIGH, bool disallowed_check_only = False) protected
Check for a name using the type's regexp.
Definition at line 549 of file checker.py.
    ) -> None:
        """Check for a name using the type's regexp."""
        def _should_exempt_from_invalid_name(node: nodes.NodeNG) -> bool:
            if node_type == "variable":
                inferred = utils.safe_infer(node)
                if isinstance(inferred, nodes.ClassDef):
                    return True
            return False
        if self._name_allowed_by_regex(name=name):
            return
        if self._name_disallowed_by_regex(name=name):
            self.linter.stats.increase_bad_name(node_type, 1)
            self.add_message(
                "disallowed-name", node=node, args=name, confidence=interfaces.HIGH
            )
            return
        regexp = self._name_regexps[node_type]
        match = regexp.match(name)
        if _is_multi_naming_match(match, node_type, confidence):
            name_group = self._find_name_group(node_type)
            bad_name_group = self._bad_names.setdefault(name_group, {})
            # Ignored because this is checked by the if statement
            warnings = bad_name_group.setdefault(match.lastgroup, [])  # type: ignore[union-attr, arg-type]
            warnings.append((node, node_type, name, confidence))
        if (
            match is None
            and not disallowed_check_only
            and not _should_exempt_from_invalid_name(node)
        ):
            self._raise_name_warning(None, node, node_type, name, confidence)
        # Check TypeVar names for variance suffixes
        if node_type == "typevar":
            self._check_typevar(name, node)
References _bad_names, _check_typevar(), _find_name_group(), pylint.checkers.base.name_checker.checker._is_multi_naming_match(), _name_allowed_by_regex(), _name_disallowed_by_regex(), _name_regexps, _raise_name_warning(), pylint.checkers.base_checker.BaseChecker.add_message(), and pylint.checkers.base_checker.BaseChecker.linter.
Referenced by pylint.checkers.non_ascii_names.NonAsciiNameChecker._check_module_import(), _recursive_check_names(), visit_assignname(), pylint.checkers.non_ascii_names.NonAsciiNameChecker.visit_assignname(), pylint.checkers.non_ascii_names.NonAsciiNameChecker.visit_call(), visit_classdef(), pylint.checkers.non_ascii_names.NonAsciiNameChecker.visit_classdef(), visit_functiondef(), pylint.checkers.non_ascii_names.NonAsciiNameChecker.visit_functiondef(), pylint.checkers.non_ascii_names.NonAsciiNameChecker.visit_global(), visit_module(), and pylint.checkers.non_ascii_names.NonAsciiNameChecker.visit_module().
_check_typevar()
None pylint.checkers.base.name_checker.checker.NameChecker._check_typevar (self, str name, nodes.AssignName node) protected
Check for TypeVar lint violations.
Definition at line 627 of file checker.py.
    def _check_typevar(self, name: str, node: nodes.AssignName) -> None:
        """Check for TypeVar lint violations."""
        variance: TypeVarVariance = TypeVarVariance.invariant
        if isinstance(node.parent, nodes.Assign):
            keywords = node.assign_type().value.keywords
            args = node.assign_type().value.args
        elif isinstance(node.parent, nodes.Tuple):
            keywords = (
                node.assign_type().value.elts[node.parent.elts.index(node)].keywords
            )
            args = node.assign_type().value.elts[node.parent.elts.index(node)].args
        else:  # PEP 695 generic type nodes
            keywords = ()
            args = ()
            variance = TypeVarVariance.inferred
        name_arg = None
        for kw in keywords:
            if variance == TypeVarVariance.double_variant:
                pass
            elif kw.arg == "covariant" and kw.value.value:
                variance = (
                    TypeVarVariance.covariant
                    if variance != TypeVarVariance.contravariant
                    else TypeVarVariance.double_variant
                )
            elif kw.arg == "contravariant" and kw.value.value:
                variance = (
                    TypeVarVariance.contravariant
                    if variance != TypeVarVariance.covariant
                    else TypeVarVariance.double_variant
                )
            if kw.arg == "name" and isinstance(kw.value, nodes.Const):
                name_arg = kw.value.value
        if name_arg is None and args and isinstance(args[0], nodes.Const):
            name_arg = args[0].value
        if variance == TypeVarVariance.inferred:
            # Ignore variance check for PEP 695 type parameters.
            # The variance is inferred by the type checker.
            # Adding _co or _contra suffix can help to reason about TypeVar.
            pass
        elif variance == TypeVarVariance.double_variant:
            self.add_message(
                "typevar-double-variance",
                node=node,
                confidence=interfaces.INFERENCE,
            )
            self.add_message(
                "typevar-name-incorrect-variance",
                node=node,
                args=("",),
                confidence=interfaces.INFERENCE,
            )
        elif variance == TypeVarVariance.covariant and not name.endswith("_co"):
            suggest_name = f"{re.sub('_contra$', '', name)}_co"
            self.add_message(
                "typevar-name-incorrect-variance",
                node=node,
                args=(f'. "{name}" is covariant, use "{suggest_name}" instead'),
                confidence=interfaces.INFERENCE,
            )
        elif variance == TypeVarVariance.contravariant and not name.endswith("_contra"):
            suggest_name = f"{re.sub('_co$', '', name)}_contra"
            self.add_message(
                "typevar-name-incorrect-variance",
                node=node,
                args=(f'. "{name}" is contravariant, use "{suggest_name}" instead'),
                confidence=interfaces.INFERENCE,
            )
        elif variance == TypeVarVariance.invariant and (
            name.endswith(("_co", "_contra"))
        ):
            suggest_name = re.sub("_contra$|_co$", "", name)
            self.add_message(
                "typevar-name-incorrect-variance",
                node=node,
                args=(f'. "{name}" is invariant, use "{suggest_name}" instead'),
                confidence=interfaces.INFERENCE,
            )
        if name_arg is not None and name_arg != name:
            self.add_message(
                "typevar-name-mismatch",
                node=node,
                args=(name_arg, name),
                confidence=interfaces.INFERENCE,
            )
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by _check_name().
_create_naming_rules()
tuple[dict[str, Pattern[str]], dict[str, str]] pylint.checkers.base.name_checker.checker.NameChecker._create_naming_rules (self) protected
Definition at line 301 of file checker.py.
    def _create_naming_rules(self) -> tuple[dict[str, Pattern[str]], dict[str, str]]:
        regexps: dict[str, Pattern[str]] = {}
        hints: dict[str, str] = {}
        for name_type in KNOWN_NAME_TYPES:
            if name_type in KNOWN_NAME_TYPES_WITH_STYLE:
                naming_style_name = getattr(
                    self.linter.config, f"{name_type}_naming_style"
                )
                regexps[name_type] = NAMING_STYLES[naming_style_name].get_regex(
                    name_type
                )
            else:
                naming_style_name = "predefined"
                regexps[name_type] = DEFAULT_PATTERNS[name_type]
            custom_regex_setting_name = f"{name_type}_rgx"
            custom_regex = getattr(self.linter.config, custom_regex_setting_name, None)
            if custom_regex is not None:
                regexps[name_type] = custom_regex
            if custom_regex is not None:
                hints[name_type] = f"{custom_regex.pattern!r} pattern"
            else:
                hints[name_type] = f"{naming_style_name} naming style"
        return regexps, hints
References pylint.checkers.base_checker.BaseChecker.linter.
Referenced by open().
_find_name_group()
str pylint.checkers.base.name_checker.checker.NameChecker._find_name_group (self, str node_type) protected
Definition at line 509 of file checker.py.
    def _find_name_group(self, node_type: str) -> str:
        return self._name_group.get(node_type, node_type)
References _name_group.
Referenced by _check_name().
_name_allowed_by_regex()
bool pylint.checkers.base.name_checker.checker.NameChecker._name_allowed_by_regex (self, str name) protected
Definition at line 539 of file checker.py.
    def _name_allowed_by_regex(self, name: str) -> bool:
        return name in self.linter.config.good_names or any(
            pattern.match(name) for pattern in self._good_names_rgxs_compiled
        )
References _good_names_rgxs_compiled, and pylint.checkers.base_checker.BaseChecker.linter.
Referenced by _check_name().
_name_disallowed_by_regex()
bool pylint.checkers.base.name_checker.checker.NameChecker._name_disallowed_by_regex (self, str name) protected
Definition at line 544 of file checker.py.
    def _name_disallowed_by_regex(self, name: str) -> bool:
        return name in self.linter.config.bad_names or any(
            pattern.match(name) for pattern in self._bad_names_rgxs_compiled
        )
References _bad_names_rgxs_compiled, and pylint.checkers.base_checker.BaseChecker.linter.
Referenced by _check_name().
_raise_name_warning()
None pylint.checkers.base.name_checker.checker.NameChecker._raise_name_warning (self, str | None prevalent_group, nodes.NodeNG node, str node_type, str name, interfaces.Confidence confidence, str warning = "invalid-name") protected
Definition at line 512 of file checker.py.
    ) -> None:
        type_label = constants.HUMAN_READABLE_TYPES[node_type]
        hint = self._name_hints[node_type]
        if prevalent_group:
            # This happens in the multi naming match case. The expected
            # prevalent group needs to be spelled out to make the message
            # correct.
            hint = f"the `{prevalent_group}` group in the {hint}"
        if self.linter.config.include_naming_hint:
            hint += f" ({self._name_regexps[node_type].pattern!r} pattern)"
        args = (
            (type_label.capitalize(), name, hint)
            if warning == "invalid-name"
            else (type_label.capitalize(), name)
        )
        self.add_message(warning, node=node, args=args, confidence=confidence)
        self.linter.stats.increase_bad_name(node_type, 1)
References _name_hints, pylint.checkers.base_checker.BaseChecker.add_message(), and pylint.checkers.base_checker.BaseChecker.linter.
Referenced by _check_name(), and leave_module().
_recursive_check_names()
None pylint.checkers.base.name_checker.checker.NameChecker._recursive_check_names (self, list[nodes.AssignName] args) protected
Check names in a possibly recursive list <arg>.
Definition at line 504 of file checker.py.
    def _recursive_check_names(self, args: list[nodes.AssignName]) -> None:
        """Check names in a possibly recursive list <arg>."""
        for arg in args:
            self._check_name("argument", arg.name, arg)
References _check_name().
Referenced by visit_functiondef().
leave_module()
None pylint.checkers.base.name_checker.checker.NameChecker.leave_module (self, nodes.Module _)
Definition at line 334 of file checker.py.
    def leave_module(self, _: nodes.Module) -> None:
        for all_groups in self._bad_names.values():
            if len(all_groups) < 2:
                continue
            groups: collections.defaultdict[int, list[list[_BadNamesTuple]]] = (
                collections.defaultdict(list)
            )
            min_warnings = sys.maxsize
            prevalent_group, _ = max(all_groups.items(), key=lambda item: len(item[1]))
            for group in all_groups.values():
                groups[len(group)].append(group)
                min_warnings = min(len(group), min_warnings)
            if len(groups[min_warnings]) > 1:
                by_line = sorted(
                    groups[min_warnings],
                    key=lambda group: min(
                        warning[0].lineno
                        for warning in group
                        if warning[0].lineno is not None
                    ),
                )
                warnings: Iterable[_BadNamesTuple] = itertools.chain(*by_line[1:])
            else:
                warnings = groups[min_warnings][0]
            for args in warnings:
                self._raise_name_warning(prevalent_group, *args)
References _bad_names, and _raise_name_warning().
open()
None pylint.checkers.base.name_checker.checker.NameChecker.open (self)
Called before visiting project (i.e. set of modules).
Reimplemented from pylint.checkers.base_checker.BaseChecker.
Definition at line 285 of file checker.py.
    def open(self) -> None:
        self.linter.stats.reset_bad_names()
        for group in self.linter.config.name_group:
            for name_type in group.split(":"):
                self._name_group[name_type] = f"group_{group}"
        regexps, hints = self._create_naming_rules()
        self._name_regexps = regexps
        self._name_hints = hints
        self._good_names_rgxs_compiled = [
            re.compile(rgxp) for rgxp in self.linter.config.good_names_rgxs
        ]
        self._bad_names_rgxs_compiled = [
            re.compile(rgxp) for rgxp in self.linter.config.bad_names_rgxs
        ]
References _bad_names_rgxs_compiled, _create_naming_rules(), _good_names_rgxs_compiled, _name_group, _name_hints, _name_regexps, and pylint.checkers.base_checker.BaseChecker.linter.
Referenced by django.contrib.staticfiles.storage.HashedFilesMixin.hashed_name().
visit_assignname()
None pylint.checkers.base.name_checker.checker.NameChecker.visit_assignname (self, nodes.AssignName node)
Check module level assigned names.
Definition at line 402 of file checker.py.
    ) -> None:
        """Check module level assigned names."""
        frame = node.frame()
        assign_type = node.assign_type()
        # Check names defined in comprehensions
        if isinstance(assign_type, nodes.Comprehension):
            self._check_name("inlinevar", node.name, node)
        elif isinstance(assign_type, nodes.TypeVar):
            self._check_name("typevar", node.name, node)
        elif isinstance(assign_type, nodes.TypeAlias):
            self._check_name("typealias", node.name, node)
        # Check names defined in module scope
        elif isinstance(frame, nodes.Module):
            # Check names defined in Assign nodes
            if isinstance(assign_type, nodes.Assign):
                inferred_assign_type = utils.safe_infer(assign_type.value)
                # Check TypeVar's and TypeAliases assigned alone or in tuple assignment
                if isinstance(node.parent, nodes.Assign):
                    if self._assigns_typevar(assign_type.value):
                        self._check_name("typevar", assign_type.targets[0].name, node)
                        return
                    if self._assigns_typealias(assign_type.value):
                        self._check_name("typealias", assign_type.targets[0].name, node)
                        return
                if (
                    isinstance(node.parent, nodes.Tuple)
                    and isinstance(assign_type.value, nodes.Tuple)
                    # protect against unbalanced tuple unpacking
                    and node.parent.elts.index(node) < len(assign_type.value.elts)
                ):
                    assigner = assign_type.value.elts[node.parent.elts.index(node)]
                    if self._assigns_typevar(assigner):
                        self._check_name(
                            "typevar",
                            assign_type.targets[0]
                            .elts[node.parent.elts.index(node)]
                            .name,
                            node,
                        )
                        return
                    if self._assigns_typealias(assigner):
                        self._check_name(
                            "typealias",
                            assign_type.targets[0]
                            .elts[node.parent.elts.index(node)]
                            .name,
                            node,
                        )
                        return
                # Check classes (TypeVar's are classes so they need to be excluded first)
                elif isinstance(inferred_assign_type, nodes.ClassDef):
                    self._check_name("class", node.name, node)
                # Don't emit if the name redefines an import in an ImportError except handler.
                elif not _redefines_import(node) and isinstance(
                    inferred_assign_type, nodes.Const
                ):
                    self._check_name("const", node.name, node)
                else:
                    self._check_name(
                        "variable", node.name, node, disallowed_check_only=True
                    )
            # Check names defined in AnnAssign nodes
            elif isinstance(assign_type, nodes.AnnAssign):
                if utils.is_assign_name_annotated_with(node, "Final"):
                    self._check_name("const", node.name, node)
                elif self._assigns_typealias(assign_type.annotation):
                    self._check_name("typealias", node.name, node)
        # Check names defined in function scopes
        elif isinstance(frame, nodes.FunctionDef):
            # global introduced variable aren't in the function locals
            if node.name in frame and node.name not in frame.argnames():
                if not _redefines_import(node):
                    if isinstance(
                        assign_type, nodes.AnnAssign
                    ) and self._assigns_typealias(assign_type.annotation):
                        self._check_name("typealias", node.name, node)
                    else:
                        self._check_name("variable", node.name, node)
        # Check names defined in class scopes
        elif isinstance(frame, nodes.ClassDef) and not any(
            frame.local_attr_ancestors(node.name)
        ):
            if utils.is_enum_member(node) or utils.is_assign_name_annotated_with(
                node, "Final"
            ):
                self._check_name("class_const", node.name, node)
            else:
                self._check_name("class_attribute", node.name, node)
References _assigns_typealias(), _assigns_typevar(), _check_name(), and pylint.checkers.base.name_checker.checker._redefines_import().
visit_classdef()
None pylint.checkers.base.name_checker.checker.NameChecker.visit_classdef (self, nodes.ClassDef node)
Definition at line 362 of file checker.py.
    def visit_classdef(self, node: nodes.ClassDef) -> None:
        self._check_name("class", node.name, node)
        for attr, anodes in node.instance_attrs.items():
            if not any(node.instance_attr_ancestors(attr)):
                self._check_name("attr", attr, anodes[0])
References _check_name().
Referenced by pylint.pyreverse.inspector.Linker.visit_assignname(), and pylint.checkers.exceptions.ExceptionRaiseLeafVisitor.visit_instance().
visit_functiondef()
None pylint.checkers.base.name_checker.checker.NameChecker.visit_functiondef (self, nodes.FunctionDef node)
Definition at line 369 of file checker.py.
    def visit_functiondef(self, node: nodes.FunctionDef) -> None:
        # Do not emit any warnings if the method is just an implementation
        # of a base class method.
        confidence = interfaces.HIGH
        if node.is_method():
            if utils.overrides_a_method(node.parent.frame(), node.name):
                return
            confidence = (
                interfaces.INFERENCE
                if utils.has_known_bases(node.parent.frame())
                else interfaces.INFERENCE_FAILURE
            )
        self._check_name(
            _determine_function_name_type(node, config=self.linter.config),
            node.name,
            node,
            confidence,
        )
        # Check argument names
        args = node.args.args
        if args is not None:
            self._recursive_check_names(args)
References _check_name(), pylint.checkers.base.name_checker.checker._determine_function_name_type(), _recursive_check_names(), and pylint.checkers.base_checker.BaseChecker.linter.
Referenced by pylint.pyreverse.inspector.Linker.visit_assignname().
visit_module()
None pylint.checkers.base.name_checker.checker.NameChecker.visit_module (self, nodes.Module node)
Definition at line 330 of file checker.py.
    def visit_module(self, node: nodes.Module) -> None:
        self._check_name("module", node.name.split(".")[-1], node)
        self._bad_names = {}
References _bad_names, and _check_name().
Referenced by pylint.pyreverse.inspector.Linker.visit_assignname().
Member Data Documentation
_bad_names
dict pylint.checkers.base.name_checker.checker.NameChecker._bad_names = {} protected
Definition at line 279 of file checker.py.
Referenced by _check_name(), leave_module(), and visit_module().
_bad_names_rgxs_compiled
list pylint.checkers.base.name_checker.checker.NameChecker._bad_names_rgxs_compiled = [] protected
Definition at line 283 of file checker.py.
Referenced by _name_disallowed_by_regex(), and open().
_good_names_rgxs_compiled
list pylint.checkers.base.name_checker.checker.NameChecker._good_names_rgxs_compiled = [] protected
Definition at line 282 of file checker.py.
Referenced by _name_allowed_by_regex(), and open().
_name_group
dict pylint.checkers.base.name_checker.checker.NameChecker._name_group = {} protected
Definition at line 278 of file checker.py.
Referenced by _find_name_group(), and open().
_name_hints
dict pylint.checkers.base.name_checker.checker.NameChecker._name_hints = {} protected
Definition at line 281 of file checker.py.
Referenced by _raise_name_warning(), and open().
_name_regexps
dict pylint.checkers.base.name_checker.checker.NameChecker._name_regexps = {} protected
Definition at line 280 of file checker.py.
Referenced by _check_name(), and open().
_options
tuple pylint.checkers.base.name_checker.checker.NameChecker._options static protected
Definition at line 198 of file checker.py.
Referenced by urllib3.contrib.pyopenssl.PyOpenSSLContext._set_ctx_options(), urllib3.contrib.pyopenssl.PyOpenSSLContext.options(), and urllib3.contrib.pyopenssl.PyOpenSSLContext.options().
visit_asyncfunctiondef
None pylint.checkers.base.name_checker.checker.NameChecker.visit_asyncfunctiondef = visit_functiondef static
Definition at line 393 of file checker.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pylint/checkers/base/name_checker/checker.py