Read&Watch: django.contrib.contenttypes.models.ContentType.Meta Class Reference
django.contrib.contenttypes.models.ContentType.Meta Class Reference
Static Public Attributes
verbose_name = _("content type")
verbose_name_plural = _("content types")
str db_table = "django_content_type"
list unique_together = [["app_label", "model"]]
Detailed Description
Definition at line 139 of file models.py.
Member Data Documentation
db_table
str django.contrib.contenttypes.models.ContentType.Meta.db_table = "django_content_type" static
Definition at line 142 of file models.py.
Referenced by django.db.models.fields.related.ManyToManyField._get_m2m_db_table(), django.db.models.fields.related.ManyToManyField.deconstruct(), and django.db.models.options.Options.setup_proxy().
unique_together
list django.contrib.contenttypes.models.ContentType.Meta.unique_together = [["app_label", "model"]] static
Definition at line 143 of file models.py.
verbose_name
django.contrib.contenttypes.models.ContentType.Meta.verbose_name = _("content type") static
Definition at line 140 of file models.py.
Referenced by django.db.models.fields.Field.formfield(), django.db.models.fields.related.RelatedField.set_attributes_from_rel(), and django.db.models.options.Options.verbose_name_raw().
verbose_name_plural
django.contrib.contenttypes.models.ContentType.Meta.verbose_name_plural = _("content types") static
Definition at line 141 of file models.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/contenttypes/models.py