Read&Watch: pip._internal.utils.hashes.MissingHashes Class Reference
pip._internal.utils.hashes.MissingHashes Class Reference
Public Member Functions
None __init__ (self)
Public Member Functions inherited from pip._internal.utils.hashes.Hashes
None __init__ (self, Optional[Dict[str, List[str]]] hashes=None)
"Hashes" __and__ (self, "Hashes" other)
int digest_count (self)
bool is_hash_allowed (self, str hash_name, str hex_digest)
None check_against_chunks (self, Iterable[bytes] chunks)
None check_against_file (self, BinaryIO file)
None check_against_path (self, str path)
bool has_one_of (self, Dict[str, str] hashes)
bool __bool__ (self)
bool __eq__ (self, object other)
int __hash__ (self)
Protected Member Functions
"NoReturn" _raise (self, Dict[str, "_Hash"] gots)
Additional Inherited Members
Protected Attributes inherited from pip._internal.utils.hashes.Hashes
_allowed = allowed
Detailed Description
A workalike for Hashes used when we're missing a hash for a requirement
It computes the actual hash of the requirement and raises a HashMissing
exception showing it to the user.
Definition at line 132 of file hashes.py.
Constructor & Destructor Documentation
__init__()
None pip._internal.utils.hashes.MissingHashes.__init__ (self)
Don't offer the ``hashes`` kwarg.
Definition at line 140 of file hashes.py.
    def __init__(self) -> None:
        """Don't offer the ``hashes`` kwarg."""
        # Pass our favorite hash in to generate a "gotten hash". With the
        # empty list, it will never match, so an error will always raise.
        super().__init__(hashes={FAVORITE_HASH: []})
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Function Documentation
_raise()
"NoReturn" pip._internal.utils.hashes.MissingHashes._raise (self, Dict[str, "_Hash"] gots) protected
Reimplemented from pip._internal.utils.hashes.Hashes.
Definition at line 146 of file hashes.py.
    def _raise(self, gots: Dict[str, "_Hash"]) -> "NoReturn":
        raise HashMissing(gots[FAVORITE_HASH].hexdigest())
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_internal/utils/hashes.py