Read&Watch: django.utils.html.CountsDict Class Reference
django.utils.html.CountsDict Class Reference
Public Member Functions
__init__ (self, *args, word, **kwargs)
__missing__ (self, key)
Public Attributes
word = word
Detailed Description
Definition at line 263 of file html.py.
Constructor & Destructor Documentation
__init__()
django.utils.html.CountsDict.__init__ (self, * args, word, ** kwargs)
Definition at line 264 of file html.py.
    def __init__(self, *args, word, **kwargs):
        super().__init__(*args, *kwargs)
        self.word = word
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Function Documentation
__missing__()
django.utils.html.CountsDict.__missing__ (self, key)
Definition at line 268 of file html.py.
    def __missing__(self, key):
        self[key] = self.word.count(key)
        return self[key]
References word.
Referenced by pip._vendor.distlib.compat.ChainMap.__getitem__().
Member Data Documentation
word
django.utils.html.CountsDict.word = word
Definition at line 266 of file html.py.
Referenced by __missing__().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/utils/html.py