Read&Watch: django.db.models.sql.compiler.PositionRef Class Reference
django.db.models.sql.compiler.PositionRef Class Reference
Public Member Functions
__init__ (self, ordinal, refs, source)
as_sql (self, compiler, connection)
Public Member Functions inherited from django.db.models.expressions.Ref
__init__ (self, refs, source)
__repr__ (self)
get_source_expressions (self)
set_source_expressions (self, exprs)
resolve_expression (self, query=None, allow_joins=True, reuse=None, summarize=False, for_save=False)
get_refs (self)
relabeled_clone (self, relabels)
get_group_by_cols (self)
Public Member Functions inherited from django.db.models.expressions.Expression
identity (self)
__eq__ (self, other)
__hash__ (self)
Public Member Functions inherited from django.db.models.expressions.BaseExpression
__init__ (self, output_field=None)
__getstate__ (self)
get_db_converters (self, connection)
contains_aggregate (self)
contains_over_clause (self)
contains_column_references (self)
contains_subquery (self)
conditional (self)
field (self)
output_field (self)
convert_value (self)
get_lookup (self, lookup)
get_transform (self, name)
replace_expressions (self, replacements)
copy (self)
prefix_references (self, prefix)
get_source_fields (self)
asc (self, **kwargs)
desc (self, **kwargs)
reverse_ordering (self)
flatten (self)
select_format (self, compiler, sql, params)
get_expression_for_validation (self)
Public Member Functions inherited from django.db.models.expressions.Combinable
__neg__ (self)
OPERATORS #.
__add__ (self, other)
__sub__ (self, other)
__mul__ (self, other)
__truediv__ (self, other)
__mod__ (self, other)
__pow__ (self, other)
__and__ (self, other)
bitand (self, other)
bitleftshift (self, other)
bitrightshift (self, other)
__xor__ (self, other)
bitxor (self, other)
__or__ (self, other)
bitor (self, other)
__radd__ (self, other)
__rsub__ (self, other)
__rmul__ (self, other)
__rtruediv__ (self, other)
__rmod__ (self, other)
__rpow__ (self, other)
__rand__ (self, other)
__ror__ (self, other)
__rxor__ (self, other)
__invert__ (self)
Public Attributes
ordinal = ordinal
Public Attributes inherited from django.db.models.expressions.Ref
refs
source = refs, source
Public Attributes inherited from django.db.models.expressions.Expression
identity
Public Attributes inherited from django.db.models.expressions.BaseExpression
output_field = output_field
contains_aggregate
Additional Inherited Members
Static Public Attributes inherited from django.db.models.expressions.BaseExpression
empty_result_set_value = NotImplemented
bool is_summary = False
bool filterable = True
bool window_compatible = False
bool allowed_default = False
bool constraint_validation_compatible = True
Static Public Attributes inherited from django.db.models.expressions.Combinable
str ADD = "+"
str SUB = "-"
str MUL = "*"
str DIV = "/"
str POW = "^"
str MOD = "%%"
str BITAND = "&"
str BITOR = "|"
str BITLEFTSHIFT = "<<"
str BITRIGHTSHIFT = ">>"
str BITXOR = "#"
Protected Member Functions inherited from django.db.models.expressions.Expression
_constructor_signature (cls)
Protected Member Functions inherited from django.db.models.expressions.BaseExpression
_parse_expressions (self, *expressions)
_output_field_or_none (self)
_resolve_output_field (self)
Protected Member Functions inherited from django.db.models.expressions.Combinable
_combine (self, other, connector, reversed)
Static Protected Member Functions inherited from django.db.models.expressions.BaseExpression
_convert_value_noop (value, expression, connection)
Static Protected Attributes inherited from django.db.models.expressions.BaseExpression
bool _output_field_resolved_to_none = False
Detailed Description
Definition at line 30 of file compiler.py.
Constructor & Destructor Documentation
__init__()
django.db.models.sql.compiler.PositionRef.__init__ (self, ordinal, refs, source)
Definition at line 31 of file compiler.py.
    def __init__(self, ordinal, refs, source):
        self.ordinal = ordinal
        super().__init__(refs, source)
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
as_sql()
django.db.models.sql.compiler.PositionRef.as_sql (self, compiler, connection)
Responsible for returning a (sql, [params]) tuple to be included
in the current query.
Different backends can provide their own implementation, by
providing an `as_{vendor}` method and patching the Expression:
```
def override_as_sql(self, compiler, connection):
    # custom logic
    return super().as_sql(compiler, connection)
setattr(Expression, 'as_' + connection.vendor, override_as_sql)
```
Arguments:
 * compiler: the query compiler responsible for generating the query.
   Must have a compile method, returning a (sql, [params]) tuple.
   Calling compiler(value) will return a quoted `value`.
 * connection: the database connection used for the current query.
Return: (sql, params)
  Where `sql` is a string containing ordered sql parameters to be
  replaced with the elements of the list `params`.
Reimplemented from django.db.models.expressions.Ref.
Definition at line 35 of file compiler.py.
    def as_sql(self, compiler, connection):
        return str(self.ordinal), ()
References ordinal.
Referenced by django.db.models.expressions.SQLiteNumericMixin.as_sqlite(), django.db.backends.mysql.compiler.SQLCompiler.as_subquery_condition(), django.db.models.sql.compiler.SQLCompiler.as_subquery_condition(), django.db.models.sql.compiler.SQLCompiler.execute_sql(), and django.db.models.sql.compiler.SQLInsertCompiler.execute_sql().
Member Data Documentation
ordinal
django.db.models.sql.compiler.PositionRef.ordinal = ordinal
Definition at line 32 of file compiler.py.
Referenced by as_sql().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/db/models/sql/compiler.py