Read&Watch: django.contrib.postgres.indexes.BrinIndex Class Reference
django.contrib.postgres.indexes.BrinIndex Class Reference
Public Member Functions
__init__ (self, *expressions, autosummarize=None, pages_per_range=None, **kwargs)
deconstruct (self)
get_with_params (self)
Public Member Functions inherited from django.contrib.postgres.indexes.PostgresIndex
max_name_length (self)
create_sql (self, model, schema_editor, using="", **kwargs)
check_supported (self, schema_editor)
Public Member Functions inherited from django.db.models.indexes.Index
__init__ (self, *expressions, fields=(), name=None, db_tablespace=None, opclasses=(), condition=None, include=None)
contains_expressions (self)
remove_sql (self, model, schema_editor, **kwargs)
clone (self)
set_name_with_model (self, model)
__repr__ (self)
__eq__ (self, other)
Public Attributes
autosummarize = autosummarize
pages_per_range = pages_per_range
Public Attributes inherited from django.db.models.indexes.Index
fields = list(fields)
list fields_orders
str name = name or ""
db_tablespace = db_tablespace
opclasses = opclasses
condition = condition
include = tuple(include) if include else ()
expressions
Additional Inherited Members
Static Public Attributes inherited from django.db.models.indexes.Index
str suffix = "idx"
Protected Member Functions inherited from django.db.models.indexes.Index
_get_condition_sql (self, model, schema_editor)
Detailed Description
Definition at line 86 of file indexes.py.
Constructor & Destructor Documentation
__init__()
django.contrib.postgres.indexes.BrinIndex.__init__ (self, * expressions, autosummarize = None, pages_per_range = None, ** kwargs)
Definition at line 89 of file indexes.py.
    ):
        if pages_per_range is not None and pages_per_range <= 0:
            raise ValueError("pages_per_range must be None or a positive integer")
        self.autosummarize = autosummarize
        self.pages_per_range = pages_per_range
        super().__init__(*expressions, **kwargs)
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
deconstruct()
django.contrib.postgres.indexes.BrinIndex.deconstruct (self)
Reimplemented from django.db.models.indexes.Index.
Definition at line 98 of file indexes.py.
    def deconstruct(self):
        path, args, kwargs = super().deconstruct()
        if self.autosummarize is not None:
            kwargs["autosummarize"] = self.autosummarize
        if self.pages_per_range is not None:
            kwargs["pages_per_range"] = self.pages_per_range
        return path, args, kwargs
References autosummarize, deconstruct(), and pages_per_range.
Referenced by django.db.models.indexes.Index.__eq__(), django.db.models.constraints.BaseConstraint.clone(), django.db.models.fields.Field.clone(), django.db.models.indexes.Index.clone(), deconstruct(), and django.db.models.query_utils.Q.identity().
get_with_params()
django.contrib.postgres.indexes.BrinIndex.get_with_params (self)
Reimplemented from django.contrib.postgres.indexes.PostgresIndex.
Definition at line 106 of file indexes.py.
    def get_with_params(self):
        with_params = []
        if self.autosummarize is not None:
            with_params.append(
                "autosummarize = %s" % ("on" if self.autosummarize else "off")
            )
        if self.pages_per_range is not None:
            with_params.append("pages_per_range = %d" % self.pages_per_range)
        return with_params
References autosummarize, and pages_per_range.
Member Data Documentation
autosummarize
django.contrib.postgres.indexes.BrinIndex.autosummarize = autosummarize
Definition at line 94 of file indexes.py.
Referenced by deconstruct(), and get_with_params().
pages_per_range
django.contrib.postgres.indexes.BrinIndex.pages_per_range = pages_per_range
Definition at line 95 of file indexes.py.
Referenced by deconstruct(), and get_with_params().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/postgres/indexes.py