Read&Watch: apscheduler.executors.asyncio.AsyncIOExecutor Class Reference
apscheduler.executors.asyncio.AsyncIOExecutor Class Reference
Public Member Functions
start (self, scheduler, alias)
shutdown (self, wait=True)
Public Member Functions inherited from apscheduler.executors.base.BaseExecutor
__init__ (self)
submit_job (self, job, run_times)
Protected Member Functions
_do_submit_job (self, job, run_times)
Protected Member Functions inherited from apscheduler.executors.base.BaseExecutor
_run_job_success (self, job_id, events)
_run_job_error (self, job_id, exc, traceback=None)
Protected Attributes
_eventloop = scheduler._eventloop
_pending_futures = set()
Protected Attributes inherited from apscheduler.executors.base.BaseExecutor
_instances = defaultdict(lambda: 0)
Additional Inherited Members
Static Protected Attributes inherited from apscheduler.executors.base.BaseExecutor
_scheduler = None
_lock = None
_logger = logging.getLogger("apscheduler.executors")
Detailed Description
Runs jobs in the default executor of the event loop.
If the job function is a native coroutine function, it is scheduled to be run directly in the
event loop as soon as possible. All other functions are run in the event loop's default
executor which is usually a thread pool.
Plugin alias: ``asyncio``
Definition at line 7 of file asyncio.py.
Member Function Documentation
_do_submit_job()
apscheduler.executors.asyncio.AsyncIOExecutor._do_submit_job (self, job, run_times) protected
Performs the actual task of scheduling `run_job` to be called.
Reimplemented from apscheduler.executors.base.BaseExecutor.
Definition at line 31 of file asyncio.py.
    def _do_submit_job(self, job, run_times):
        def callback(f):
            self._pending_futures.discard(f)
            try:
                events = f.result()
            except BaseException:
                self._run_job_error(job.id, *sys.exc_info()[1:])
            else:
                self._run_job_success(job.id, events)
        if iscoroutinefunction_partial(job.func):
            coro = run_coroutine_job(
                job, job._jobstore_alias, run_times, self._logger.name
            )
            f = self._eventloop.create_task(coro)
        else:
            f = self._eventloop.run_in_executor(
                None, run_job, job, job._jobstore_alias, run_times, self._logger.name
            )
        f.add_done_callback(callback)
        self._pending_futures.add(f)
References _eventloop, apscheduler.executors.base.BaseExecutor._logger, _pending_futures, apscheduler.executors.base.BaseExecutor._run_job_error(), and apscheduler.executors.base.BaseExecutor._run_job_success().
shutdown()
apscheduler.executors.asyncio.AsyncIOExecutor.shutdown (self, wait = True)
Shuts down this executor.
:param bool wait: ``True`` to wait until all submitted jobs
    have been executed
Reimplemented from apscheduler.executors.base.BaseExecutor.
Definition at line 23 of file asyncio.py.
    def shutdown(self, wait=True):
        # There is no way to honor wait=True without converting this method into a coroutine method
        for f in self._pending_futures:
            if not f.done():
                f.cancel()
        self._pending_futures.clear()
References _pending_futures.
start()
apscheduler.executors.asyncio.AsyncIOExecutor.start (self, scheduler, alias)
Called by the scheduler when the scheduler is being started or when the executor is being
added to an already running scheduler.
:param apscheduler.schedulers.base.BaseScheduler scheduler: the scheduler that is starting
    this executor
:param str|unicode alias: alias of this executor as it was assigned to the scheduler
Reimplemented from apscheduler.executors.base.BaseExecutor.
Definition at line 18 of file asyncio.py.
    def start(self, scheduler, alias):
        super().start(scheduler, alias)
        self._eventloop = scheduler._eventloop
        self._pending_futures = set()
References start().
Referenced by pip._vendor.rich.live.Live.__enter__(), pip._vendor.rich.progress._TrackThread.__enter__(), pip._vendor.rich.progress.Progress.__enter__(), pip._vendor.rich.status.Status.__enter__(), responses.RequestsMock.__enter__(), and start().
Member Data Documentation
_eventloop
apscheduler.executors.asyncio.AsyncIOExecutor._eventloop = scheduler._eventloop protected
Definition at line 20 of file asyncio.py.
Referenced by apscheduler.schedulers.asyncio.AsyncIOScheduler._configure(), _do_submit_job(), apscheduler.schedulers.asyncio.AsyncIOScheduler._start_timer(), and apscheduler.schedulers.asyncio.AsyncIOScheduler.start().
_pending_futures
apscheduler.executors.asyncio.AsyncIOExecutor._pending_futures = set() protected
Definition at line 21 of file asyncio.py.
Referenced by _do_submit_job(), and shutdown().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/apscheduler/executors/asyncio.py