Read&Watch: django.template.base.VariableNode Class Reference
django.template.base.VariableNode Class Reference
Public Member Functions
__init__ (self, filter_expression)
__repr__ (self)
render (self, context)
Public Member Functions inherited from django.template.base.Node
render_annotated (self, context)
get_nodes_by_type (self, nodetype)
Public Attributes
filter_expression = filter_expression
Additional Inherited Members
Static Public Attributes inherited from django.template.base.Node
bool must_be_first = False
tuple child_nodelists = ("nodelist",)
token = None
Detailed Description
Definition at line 1056 of file base.py.
Constructor & Destructor Documentation
__init__()
django.template.base.VariableNode.__init__ (self, filter_expression)
Definition at line 1059 of file base.py.
    def __init__(self, filter_expression):
        self.filter_expression = filter_expression
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
__repr__()
django.template.base.VariableNode.__repr__ (self)
Definition at line 1062 of file base.py.
    def __repr__(self):
        return "<Variable Node: %s>" % self.filter_expression
References filter_expression.
render()
django.template.base.VariableNode.render (self, context)
Return the node rendered as a string.
Reimplemented from django.template.base.Node.
Definition at line 1065 of file base.py.
    def render(self, context):
        try:
            output = self.filter_expression.resolve(context)
        except UnicodeDecodeError:
            # Unicode conversion can fail sometimes for reasons out of our
            # control (e.g. exception rendering). In that case, we fail
            # quietly.
            return ""
        return render_value_in_context(output, context)
# Regex for token keyword arguments
References filter_expression, and django.template.base.render_value_in_context().
Referenced by pip._vendor.rich.progress.ProgressColumn.__call__(), pip._vendor.rich.layout.Layout.__rich_console__(), pip._vendor.rich.spinner.Spinner.__rich_console__(), pip._vendor.rich.spinner.Spinner.__rich_measure__(), pip._vendor.rich.console.Console.log(), pip._vendor.rich.console.Console.print(), django.templatetags.i18n.BlockTranslateNode.render(), pip._vendor.rich.console.Console.render(), pip._vendor.rich.console.Console.render_lines(), and pip._vendor.rich.console.Console.update_screen_lines().
Member Data Documentation
filter_expression
django.template.base.VariableNode.filter_expression = filter_expression
Definition at line 1060 of file base.py.
Referenced by __repr__(), render(), and django.templatetags.i18n.TranslateNode.render().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/template/base.py