Read&Watch: apscheduler.jobstores.base.JobLookupError Class Reference
apscheduler.jobstores.base.JobLookupError Class Reference
Public Member Functions
__init__ (self, job_id)
Detailed Description
Raised when the job store cannot find a job for update or removal.
Definition at line 5 of file base.py.
Constructor & Destructor Documentation
__init__()
apscheduler.jobstores.base.JobLookupError.__init__ (self, job_id)
Definition at line 8 of file base.py.
    def __init__(self, job_id):
        super().__init__(f"No job by the id of {job_id} was found")
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/apscheduler/jobstores/base.py