Read&Watch: django.contrib.gis.geos.prototypes.threadsafe.GEOSFunc Class Reference
django.contrib.gis.geos.prototypes.threadsafe.GEOSFunc Class Reference
Public Member Functions
__init__ (self, func_name)
__call__ (self, *args)
__str__ (self)
Public Attributes
cfunc = getattr(lgeos, func_name + "_r")
thread_context = thread_context
Protected Member Functions
_get_argtypes (self)
_set_argtypes (self, argtypes)
_get_restype (self)
_set_restype (self, restype)
_get_errcheck (self)
_set_errcheck (self, errcheck)
Properties
argtypes = property(_get_argtypes, _set_argtypes)
restype = property(_get_restype, _set_restype)
errcheck = property(_get_errcheck, _set_errcheck)
Detailed Description
Serve as a wrapper for GEOS C Functions. Use thread-safe function
variants when available.
Definition at line 28 of file threadsafe.py.
Constructor & Destructor Documentation
__init__()
django.contrib.gis.geos.prototypes.threadsafe.GEOSFunc.__init__ (self, func_name)
Definition at line 34 of file threadsafe.py.
    def __init__(self, func_name):
        # GEOS thread-safe function signatures end with '_r' and take an
        # additional context handle parameter.
        self.cfunc = getattr(lgeos, func_name + "_r")
        # Create a reference to thread_context so it's not garbage-collected
        # before an attempt to call this object.
        self.thread_context = thread_context
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
__call__()
django.contrib.gis.geos.prototypes.threadsafe.GEOSFunc.__call__ (self, * args)
Definition at line 42 of file threadsafe.py.
    def __call__(self, *args):
        # Create a context handle if one doesn't exist for this thread.
        self.thread_context.handle = self.thread_context.handle or GEOSContextHandle()
        # Call the threaded GEOS routine with the pointer of the context handle
        # as the first argument.
        return self.cfunc(self.thread_context.handle.ptr, *args)
References cfunc, and thread_context.
__str__()
django.contrib.gis.geos.prototypes.threadsafe.GEOSFunc.__str__ (self)
Definition at line 49 of file threadsafe.py.
    def __str__(self):
        return self.cfunc.__name__
References cfunc.
Referenced by PIL.PdfParser.IndirectReference.__bytes__().
_get_argtypes()
django.contrib.gis.geos.prototypes.threadsafe.GEOSFunc._get_argtypes (self) protected
Definition at line 53 of file threadsafe.py.
    def _get_argtypes(self):
        return self.cfunc.argtypes
References cfunc.
_get_errcheck()
django.contrib.gis.geos.prototypes.threadsafe.GEOSFunc._get_errcheck (self) protected
Definition at line 71 of file threadsafe.py.
    def _get_errcheck(self):
        return self.cfunc.errcheck
References cfunc.
_get_restype()
django.contrib.gis.geos.prototypes.threadsafe.GEOSFunc._get_restype (self) protected
Definition at line 62 of file threadsafe.py.
    def _get_restype(self):
        return self.cfunc.restype
References cfunc.
_set_argtypes()
django.contrib.gis.geos.prototypes.threadsafe.GEOSFunc._set_argtypes (self, argtypes) protected
Definition at line 56 of file threadsafe.py.
    def _set_argtypes(self, argtypes):
        self.cfunc.argtypes = [CONTEXT_PTR, *argtypes]
References cfunc.
_set_errcheck()
django.contrib.gis.geos.prototypes.threadsafe.GEOSFunc._set_errcheck (self, errcheck) protected
Definition at line 74 of file threadsafe.py.
    def _set_errcheck(self, errcheck):
        self.cfunc.errcheck = errcheck
References cfunc.
_set_restype()
django.contrib.gis.geos.prototypes.threadsafe.GEOSFunc._set_restype (self, restype) protected
Definition at line 65 of file threadsafe.py.
    def _set_restype(self, restype):
        self.cfunc.restype = restype
References cfunc.
Member Data Documentation
cfunc
django.contrib.gis.geos.prototypes.threadsafe.GEOSFunc.cfunc = getattr(lgeos, func_name + "_r")
Definition at line 37 of file threadsafe.py.
Referenced by __call__(), __str__(), _get_argtypes(), _get_errcheck(), _get_restype(), _set_argtypes(), _set_errcheck(), and _set_restype().
thread_context
django.contrib.gis.geos.prototypes.threadsafe.GEOSFunc.thread_context = thread_context
Definition at line 40 of file threadsafe.py.
Referenced by __call__().
Property Documentation
argtypes
django.contrib.gis.geos.prototypes.threadsafe.GEOSFunc.argtypes = property(_get_argtypes, _set_argtypes) static
Definition at line 59 of file threadsafe.py.
errcheck
django.contrib.gis.geos.prototypes.threadsafe.GEOSFunc.errcheck = property(_get_errcheck, _set_errcheck) static
Definition at line 77 of file threadsafe.py.
restype
django.contrib.gis.geos.prototypes.threadsafe.GEOSFunc.restype = property(_get_restype, _set_restype) static
Definition at line 68 of file threadsafe.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/gis/geos/prototypes/threadsafe.py