Read&Watch: pip._vendor.distlib.database.DependencyGraph Class Reference
pip._vendor.distlib.database.DependencyGraph Class Reference
Public Member Functions
__init__ (self)
add_distribution (self, distribution)
add_edge (self, x, y, label=None)
add_missing (self, distribution, requirement)
repr_node (self, dist, level=1)
to_dot (self, f, skip_disconnected=True)
topological_sort (self)
__repr__ (self)
Public Attributes
dict adjacency_list = {}
dict reverse_list = {}
dict missing = {}
Protected Member Functions
_repr_dist (self, dist)
Detailed Description
Represents a dependency graph between distributions.
The dependency relationships are stored in an ``adjacency_list`` that maps
distributions to a list of ``(other, label)`` tuples where  ``other``
is a distribution and the edge is labeled with ``label`` (i.e. the version
specifier, if such was provided). Also, for more efficient traversal, for
every distribution ``x``, a list of predecessors is kept in
``reverse_list[x]``. An edge from distribution ``a`` to
distribution ``b`` means that ``a`` depends on ``b``. If any missing
dependencies are found, they are stored in ``missing``, which is a
dictionary that maps distributions to a list of requirements that were not
provided by any other distributions.
Definition at line 1071 of file database.py.
Constructor & Destructor Documentation
__init__()
pip._vendor.distlib.database.DependencyGraph.__init__ (self)
Definition at line 1087 of file database.py.
    def __init__(self):
        self.adjacency_list = {}
        self.reverse_list = {}
        self.missing = {}
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
__repr__()
pip._vendor.distlib.database.DependencyGraph.__repr__ (self)
Representation of the graph
Definition at line 1205 of file database.py.
    def __repr__(self):
        """Representation of the graph"""
        output = []
        for dist, adjs in self.adjacency_list.items():
            output.append(self.repr_node(dist))
        return '\n'.join(output)
References adjacency_list, and repr_node().
_repr_dist()
pip._vendor.distlib.database.DependencyGraph._repr_dist (self, dist) protected
Definition at line 1128 of file database.py.
    def _repr_dist(self, dist):
        return '%s %s' % (dist.name, dist.version)
Referenced by repr_node().
add_distribution()
pip._vendor.distlib.database.DependencyGraph.add_distribution (self, distribution)
Add the *distribution* to the graph.
:type distribution: :class:`distutils2.database.InstalledDistribution`
                    or :class:`distutils2.database.EggInfoDistribution`
Definition at line 1092 of file database.py.
    def add_distribution(self, distribution):
        """Add the *distribution* to the graph.
        :type distribution: :class:`distutils2.database.InstalledDistribution`
                            or :class:`distutils2.database.EggInfoDistribution`
        """
        self.adjacency_list[distribution] = []
        self.reverse_list[distribution] = []
        # self.missing[distribution] = []
References adjacency_list, and reverse_list.
Referenced by pip._vendor.distlib.locators.AggregatingLocator.get_distribution_names().
add_edge()
pip._vendor.distlib.database.DependencyGraph.add_edge (self, x, y, label = None)
Add an edge from distribution *x* to distribution *y* with the given
*label*.
:type x: :class:`distutils2.database.InstalledDistribution` or
         :class:`distutils2.database.EggInfoDistribution`
:type y: :class:`distutils2.database.InstalledDistribution` or
         :class:`distutils2.database.EggInfoDistribution`
:type label: ``str`` or ``None``
Definition at line 1102 of file database.py.
    def add_edge(self, x, y, label=None):
        """Add an edge from distribution *x* to distribution *y* with the given
        *label*.
        :type x: :class:`distutils2.database.InstalledDistribution` or
                 :class:`distutils2.database.EggInfoDistribution`
        :type y: :class:`distutils2.database.InstalledDistribution` or
                 :class:`distutils2.database.EggInfoDistribution`
        :type label: ``str`` or ``None``
        """
        self.adjacency_list[x].append((y, label))
        # multiple edges are allowed, so be careful
        if x not in self.reverse_list[y]:
            self.reverse_list[y].append(x)
References adjacency_list, and reverse_list.
add_missing()
pip._vendor.distlib.database.DependencyGraph.add_missing (self, distribution, requirement)
Add a missing *requirement* for the given *distribution*.
:type distribution: :class:`distutils2.database.InstalledDistribution`
                    or :class:`distutils2.database.EggInfoDistribution`
:type requirement: ``str``
Definition at line 1117 of file database.py.
    def add_missing(self, distribution, requirement):
        """
        Add a missing *requirement* for the given *distribution*.
        :type distribution: :class:`distutils2.database.InstalledDistribution`
                            or :class:`distutils2.database.EggInfoDistribution`
        :type requirement: ``str``
        """
        logger.debug('%s missing %r', distribution, requirement)
        self.missing.setdefault(distribution, []).append(requirement)
References missing.
repr_node()
pip._vendor.distlib.database.DependencyGraph.repr_node (self, dist, level = 1)
Prints only a subgraph
Definition at line 1131 of file database.py.
    def repr_node(self, dist, level=1):
        """Prints only a subgraph"""
        output = [self._repr_dist(dist)]
        for other, label in self.adjacency_list[dist]:
            dist = self._repr_dist(other)
            if label is not None:
                dist = '%s [%s]' % (dist, label)
            output.append('    ' * level + str(dist))
            suboutput = self.repr_node(other, level + 1)
            subs = suboutput.split('\n')
            output.extend(subs[1:])
        return '\n'.join(output)
References _repr_dist(), adjacency_list, and repr_node().
Referenced by __repr__(), and repr_node().
to_dot()
pip._vendor.distlib.database.DependencyGraph.to_dot (self, f, skip_disconnected = True)
Writes a DOT output for the graph to the provided file *f*.
If *skip_disconnected* is set to ``True``, then all distributions
that are not dependent on any other distribution are skipped.
:type f: has to support ``file``-like operations
:type skip_disconnected: ``bool``
Definition at line 1144 of file database.py.
    def to_dot(self, f, skip_disconnected=True):
        """Writes a DOT output for the graph to the provided file *f*.
        If *skip_disconnected* is set to ``True``, then all distributions
        that are not dependent on any other distribution are skipped.
        :type f: has to support ``file``-like operations
        :type skip_disconnected: ``bool``
        """
        disconnected = []
        f.write("digraph dependencies {\n")
        for dist, adjs in self.adjacency_list.items():
            if len(adjs) == 0 and not skip_disconnected:
                disconnected.append(dist)
            for other, label in adjs:
                if label is not None:
                    f.write('"%s" -> "%s" [label="%s"]\n' % (dist.name, other.name, label))
                else:
                    f.write('"%s" -> "%s"\n' % (dist.name, other.name))
        if not skip_disconnected and len(disconnected) > 0:
            f.write('subgraph disconnected {\n')
            f.write('label = "Disconnected"\n')
            f.write('bgcolor = red\n')
            for dist in disconnected:
                f.write('"%s"' % dist.name)
                f.write('\n')
            f.write('}\n')
        f.write('}\n')
References adjacency_list.
topological_sort()
pip._vendor.distlib.database.DependencyGraph.topological_sort (self)
Perform a topological sort of the graph.
:return: A tuple, the first element of which is a topologically sorted
         list of distributions, and the second element of which is a
         list of distributions that cannot be sorted because they have
         circular dependencies and so form a cycle.
Definition at line 1175 of file database.py.
    def topological_sort(self):
        """
        Perform a topological sort of the graph.
        :return: A tuple, the first element of which is a topologically sorted
                 list of distributions, and the second element of which is a
                 list of distributions that cannot be sorted because they have
                 circular dependencies and so form a cycle.
        """
        result = []
        # Make a shallow copy of the adjacency list
        alist = {}
        for k, v in self.adjacency_list.items():
            alist[k] = v[:]
        while True:
            # See what we can remove in this run
            to_remove = []
            for k, v in list(alist.items())[:]:
                if not v:
                    to_remove.append(k)
                    del alist[k]
            if not to_remove:
                # What's left in alist (if anything) is a cycle.
                break
            # Remove from the adjacency list of others
            for k, v in alist.items():
                alist[k] = [(d, r) for d, r in v if d not in to_remove]
            logger.debug('Moving to result: %s', ['%s (%s)' % (d.name, d.version) for d in to_remove])
            result.extend(to_remove)
        return result, list(alist.keys())
References adjacency_list.
Member Data Documentation
adjacency_list
dict pip._vendor.distlib.database.DependencyGraph.adjacency_list = {}
Definition at line 1088 of file database.py.
Referenced by __repr__(), add_distribution(), add_edge(), repr_node(), to_dot(), and topological_sort().
missing
dict pip._vendor.distlib.database.DependencyGraph.missing = {}
Definition at line 1090 of file database.py.
Referenced by add_missing().
reverse_list
dict pip._vendor.distlib.database.DependencyGraph.reverse_list = {}
Definition at line 1089 of file database.py.
Referenced by add_distribution(), and add_edge().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/distlib/database.py