Read&Watch: pylint.checkers.raw_metrics.RawMetricsChecker Class Reference
pylint.checkers.raw_metrics.RawMetricsChecker Class Reference
Public Member Functions
None open (self)
None process_tokens (self, list[tokenize.TokenInfo] tokens)
Public Member Functions inherited from pylint.checkers.base_checker.BaseChecker
None __init__ (self, PyLinter linter)
bool __gt__ (self, Any other)
bool __eq__ (self, object other)
int __hash__ (self)
str __repr__ (self)
str __str__ (self)
str get_full_documentation (self, dict[str, MessageDefinitionTuple] msgs, Iterable[tuple[str, OptionDict, Any]] options, Sequence[tuple[str, str, ReportsCallable]] reports, str|None doc=None, str|None module=None, bool show_options=True)
None add_message (self, str msgid, int|None line=None, nodes.NodeNG|None node=None, Any args=None, Confidence|None confidence=None, int|None col_offset=None, int|None end_lineno=None, int|None end_col_offset=None)
None check_consistency (self)
MessageDefinition create_message_definition_from_tuple (self, str msgid, MessageDefinitionTuple msg_tuple)
list[MessageDefinition] messages (self)
None close (self)
Any get_map_data (self)
None reduce_map_data (self, PyLinter linter, list[Any] data)
Public Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
None __init__ (self, _ArgumentsManager arguments_manager)
Additional Inherited Members
Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
linter = linter
messages
Static Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
str name = ""
dict msgs = {}
tuple reports = ()
bool enabled = True
Static Public Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
tuple options = ()
dict option_groups_descs = {}
Protected Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
Any _option_value (self, str opt)
Iterator[ tuple[str, list[tuple[str, OptionDict, Any]]]|tuple[None, dict[str, list[tuple[str, OptionDict, Any]]]]] _options_by_section (self)
Iterator[tuple[str, OptionDict, Any]] _options_and_values (self, Options|None options=None)
Protected Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
_arguments_manager = arguments_manager
Detailed Description
Checker that provides raw metrics instead of checking anything.
Provides:
* total number of lines
* total number of code lines
* total number of docstring lines
* total number of comments lines
* total number of empty lines
Definition at line 43 of file raw_metrics.py.
Member Function Documentation
open()
None pylint.checkers.raw_metrics.RawMetricsChecker.open (self)
Init statistics.
Reimplemented from pylint.checkers.base_checker.BaseChecker.
Definition at line 63 of file raw_metrics.py.
    def open(self) -> None:
        """Init statistics."""
        self.linter.stats.reset_code_count()
References pylint.checkers.base_checker.BaseChecker.linter.
Referenced by django.contrib.staticfiles.storage.HashedFilesMixin.hashed_name().
process_tokens()
None pylint.checkers.raw_metrics.RawMetricsChecker.process_tokens (self, list[tokenize.TokenInfo] tokens)
Update stats.
Reimplemented from pylint.checkers.base_checker.BaseTokenChecker.
Definition at line 67 of file raw_metrics.py.
    def process_tokens(self, tokens: list[tokenize.TokenInfo]) -> None:
        """Update stats."""
        i = 0
        tokens = list(tokens)
        while i < len(tokens):
            i, lines_number, line_type = get_type(tokens, i)
            self.linter.stats.code_type_count["total"] += lines_number
            self.linter.stats.code_type_count[line_type] += lines_number
References pylint.checkers.raw_metrics.get_type(), and pylint.checkers.base_checker.BaseChecker.linter.
Referenced by pylint.lint.pylinter.PyLinter._check_astroid_module().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pylint/checkers/raw_metrics.py