Read&Watch: pip._internal.cache.SimpleWheelCache Class Reference
pip._internal.cache.SimpleWheelCache Class Reference
Public Member Functions
None __init__ (self, str cache_dir)
str get_path_for_link (self, Link link)
Link get (self, Link link, Optional[str] package_name, List[Tag] supported_tags)
Public Member Functions inherited from pip._internal.cache.Cache
None __init__ (self, str cache_dir)
Additional Inherited Members
Public Attributes inherited from pip._internal.cache.Cache
cache_dir = cache_dir or None
Protected Member Functions inherited from pip._internal.cache.Cache
List[str] _get_cache_path_parts (self, Link link)
List[Any] _get_candidates (self, Link link, str canonical_package_name)
Detailed Description
A cache of wheels for future installs.
Definition at line 102 of file cache.py.
Constructor & Destructor Documentation
__init__()
None pip._internal.cache.SimpleWheelCache.__init__ (self, str cache_dir)
Definition at line 105 of file cache.py.
    def __init__(self, cache_dir: str) -> None:
        super().__init__(cache_dir)
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
get()
Link pip._internal.cache.SimpleWheelCache.get (self, Link link, Optional[str] package_name, List[Tag] supported_tags)
Returns a link to a cached item if it exists, otherwise returns the
passed link.
Reimplemented from pip._internal.cache.Cache.
Definition at line 128 of file cache.py.
    ) -> Link:
        candidates = []
        if not package_name:
            return link
        canonical_package_name = canonicalize_name(package_name)
        for wheel_name, wheel_dir in self._get_candidates(link, canonical_package_name):
            try:
                wheel = Wheel(wheel_name)
            except InvalidWheelFilename:
                continue
            if canonicalize_name(wheel.name) != canonical_package_name:
                logger.debug(
                    "Ignoring cached wheel %s for %s as it "
                    "does not match the expected distribution name %s.",
                    wheel_name,
                    link,
                    package_name,
                )
                continue
            if not wheel.supported(supported_tags):
                # Built for a different python/arch/etc
                continue
            candidates.append(
                (
                    wheel.support_index_min(supported_tags),
                    wheel_name,
                    wheel_dir,
                )
            )
        if not candidates:
            return link
        _, wheel_name, wheel_dir = min(candidates)
        return Link(path_to_url(os.path.join(wheel_dir, wheel_name)))
Referenced by pip._vendor.distlib.metadata.LegacyMetadata.__getitem__(), pip._vendor.rich.layout.Layout.__getitem__(), django.test.client.ClientMixin._follow_redirect(), pip._vendor.distlib.metadata.LegacyMetadata.check(), PIL.Image.Exif.get_ifd(), and pip._vendor.distlib.metadata.LegacyMetadata.write_file().
get_path_for_link()
str pip._internal.cache.SimpleWheelCache.get_path_for_link (self, Link link)
Return a directory to store cached wheels for link
Because there are M wheels for any one sdist, we provide a directory
to cache them in, and then consult that directory when looking up
cache hits.
We only insert things into the cache if they have plausible version
numbers, so that we don't contaminate the cache with things that were
not unique. E.g. ./package might have dozens of installs done for it
and build a version of 0.0...and if we built and cached a wheel, we'd
end up using the same wheel even if the source has been edited.
:param link: The link of the sdist for which this will cache wheels.
Reimplemented from pip._internal.cache.Cache.
Definition at line 108 of file cache.py.
    def get_path_for_link(self, link: Link) -> str:
        """Return a directory to store cached wheels for link
        Because there are M wheels for any one sdist, we provide a directory
        to cache them in, and then consult that directory when looking up
        cache hits.
        We only insert things into the cache if they have plausible version
        numbers, so that we don't contaminate the cache with things that were
        not unique. E.g. ./package might have dozens of installs done for it
        and build a version of 0.0...and if we built and cached a wheel, we'd
        end up using the same wheel even if the source has been edited.
        :param link: The link of the sdist for which this will cache wheels.
        """
        parts = self._get_cache_path_parts(link)
        assert self.cache_dir
        # Store wheels within the root cache_dir
        return os.path.join(self.cache_dir, "wheels", *parts)
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_internal/cache.py