Read&Watch: pip._vendor.cachecontrol.adapter.CacheControlAdapter Class Reference
pip._vendor.cachecontrol.adapter.CacheControlAdapter Class Reference
Public Member Functions
None __init__ (self, BaseCache|None cache=None, bool cache_etags=True, type[CacheController]|None controller_class=None, Serializer|None serializer=None, BaseHeuristic|None heuristic=None, Collection[str]|None cacheable_methods=None, *Any args, **Any kw)
Response send (self, PreparedRequest request, bool stream=False, None|float|tuple[float, float]|tuple[float, None] timeout=None, bool|str verify=True,(None|bytes|str|tuple[bytes|str, bytes|str]) cert=None, Mapping[str, str]|None proxies=None, Collection[str]|None cacheable_methods=None)
Response build_response (self, PreparedRequest request, HTTPResponse response, bool from_cache=False, Collection[str]|None cacheable_methods=None)
None close (self)
Public Member Functions inherited from pip._vendor.requests.adapters.HTTPAdapter
__init__ (self, pool_connections=DEFAULT_POOLSIZE, pool_maxsize=DEFAULT_POOLSIZE, max_retries=DEFAULT_RETRIES, pool_block=DEFAULT_POOLBLOCK)
__getstate__ (self)
__setstate__ (self, state)
init_poolmanager (self, connections, maxsize, block=DEFAULT_POOLBLOCK, **pool_kwargs)
proxy_manager_for (self, proxy, **proxy_kwargs)
cert_verify (self, conn, url, verify, cert)
build_connection_pool_key_attributes (self, request, verify, cert=None)
get_connection_with_tls_context (self, request, verify, proxies=None, cert=None)
get_connection (self, url, proxies=None)
request_url (self, request, proxies)
add_headers (self, request, **kwargs)
proxy_headers (self, proxy)
Public Member Functions inherited from pip._vendor.requests.adapters.BaseAdapter
__init__ (self)
Public Attributes
cache = DictCache() if cache is None else cache
heuristic = heuristic
cacheable_methods = cacheable_methods or ("GET",)
controller
int chunk_left = 0:
Public Attributes inherited from pip._vendor.requests.adapters.HTTPAdapter
max_retries = Retry(0, read=False)
dict config = {}
dict proxy_manager = {}
poolmanager
Static Public Attributes
dict invalidating_methods = {"PUT", "PATCH", "DELETE"}
Additional Inherited Members
Protected Attributes inherited from pip._vendor.requests.adapters.HTTPAdapter
_pool_connections = pool_connections
_pool_maxsize = pool_maxsize
_pool_block = pool_block
Detailed Description
Definition at line 26 of file adapter.py.
Constructor & Destructor Documentation
__init__()
None pip._vendor.cachecontrol.adapter.CacheControlAdapter.__init__ (self, BaseCache | None cache = None, bool cache_etags = True, type[CacheController] | None controller_class = None, Serializer | None serializer = None, BaseHeuristic | None heuristic = None, Collection[str] | None cacheable_methods = None, *Any args, **Any kw)
Definition at line 29 of file adapter.py.
    ) -> None:
        super().__init__(*args, **kw)
        self.cache = DictCache() if cache is None else cache
        self.heuristic = heuristic
        self.cacheable_methods = cacheable_methods or ("GET",)
        controller_factory = controller_class or CacheController
        self.controller = controller_factory(
            self.cache, cache_etags=cache_etags, serializer=serializer
        )
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Function Documentation
build_response()
Response pip._vendor.cachecontrol.adapter.CacheControlAdapter.build_response (self, PreparedRequest request, HTTPResponse response, bool from_cache = False, Collection[str] | None cacheable_methods = None)
Build a response by making a request or using the cache.
This will end up calling send and returning a potentially
cached response
Reimplemented from pip._vendor.requests.adapters.HTTPAdapter.
Definition at line 80 of file adapter.py.
    ) -> Response:
        """
        Build a response by making a request or using the cache.
        This will end up calling send and returning a potentially
        cached response
        """
        cacheable = cacheable_methods or self.cacheable_methods
        if not from_cache and request.method in cacheable:
            # Check for any heuristics that might update headers
            # before trying to cache.
            if self.heuristic:
                response = self.heuristic.apply(response)
            # apply any expiration heuristics
            if response.status == 304:
                # We must have sent an ETag request. This could mean
                # that we've been expired already or that we simply
                # have an etag. In either case, we want to try and
                # update the cache if that is the case.
                cached_response = self.controller.update_cached_response(
                    request, response
                )
                if cached_response is not response:
                    from_cache = True
                # We are done with the server response, read a
                # possible response body (compliant servers will
                # not return one, but we cannot be 100% sure) and
                # release the connection back to the pool.
                response.read(decode_content=False)
                response.release_conn()
                response = cached_response
            # We always cache the 301 responses
            elif int(response.status) in PERMANENT_REDIRECT_STATUSES:
                self.controller.cache_response(request, response)
            else:
                # Wrap the response file with a wrapper that will cache the
                #   response when the stream has been consumed.
                response._fp = CallbackFileWrapper(  # type: ignore[assignment]
                    response._fp,  # type: ignore[arg-type]
                    functools.partial(
                        self.controller.cache_response, request, response
                    ),
                )
                if response.chunked:
                    super_update_chunk_length = response._update_chunk_length
                    def _update_chunk_length(self: HTTPResponse) -> None:
                        super_update_chunk_length()
                        if self.chunk_left == 0:
                            self._fp._close()  # type: ignore[union-attr]
                    response._update_chunk_length = types.MethodType(  # type: ignore[method-assign]
                        _update_chunk_length, response
                    )
        resp: Response = super().build_response(request, response)  # type: ignore[no-untyped-call]
        # See if we should invalidate the cache.
        if request.method in self.invalidating_methods and resp.ok:
            assert request.url is not None
            cache_url = self.controller.cache_url(request.url)
            self.cache.delete(cache_url)
        # Give the request a from_cache attr to let people use it
        resp.from_cache = from_cache  # type: ignore[attr-defined]
        return resp
References cacheable_methods, controller, and heuristic.
Referenced by send().
close()
None pip._vendor.cachecontrol.adapter.CacheControlAdapter.close (self)
Disposes of any internal state.
Currently, this closes the PoolManager and any active ProxyManager,
which closes any pooled connections.
Reimplemented from pip._vendor.requests.adapters.HTTPAdapter.
Definition at line 159 of file adapter.py.
    def close(self) -> None:
        self.cache.close()
        super().close()  # type: ignore[no-untyped-call]
References cache, and close().
Referenced by urllib3.contrib.emscripten.fetch._ReadStream.__del__(), django.db.backends.utils.CursorWrapper.__exit__(), pip._vendor.distlib.compat.ZipExtFile.__exit__(), pip._vendor.distlib.compat.ZipFile.__exit__(), pip._vendor.requests.models.Response.__exit__(), pip._vendor.requests.sessions.Session.__exit__(), pip._vendor.rich.progress._Reader.__exit__(), pip._vendor.urllib3.connectionpool.ConnectionPool.__exit__(), pip._vendor.urllib3.util.ssltransport.SSLTransport.__exit__(), requests.models.Response.__exit__(), requests.sessions.Session.__exit__(), urllib3.connectionpool.ConnectionPool.__exit__(), urllib3.util.ssltransport.SSLTransport.__exit__(), pip._vendor.urllib3.contrib.securetransport.WrappedSocket._custom_validate(), pip._vendor.urllib3.contrib.pyopenssl.WrappedSocket._decref_socketios(), pip._vendor.urllib3.contrib.securetransport.WrappedSocket._decref_socketios(), urllib3.contrib.pyopenssl.WrappedSocket._decref_socketios(), pip._vendor.urllib3.contrib.pyopenssl.WrappedSocket._drop(), pip._vendor.urllib3.contrib.securetransport.WrappedSocket._drop(), pip._vendor.urllib3.contrib.securetransport.WrappedSocket._raise_on_error(), urllib3.connection.HTTPConnection._tunnel(), pip._vendor.urllib3.response.HTTPResponse._update_chunk_length(), urllib3.response.HTTPResponse._update_chunk_length(), close(), urllib3.contrib.emscripten.response.EmscriptenHttpResponseWrapper.drain_conn(), urllib3.contrib.emscripten.fetch._ReadStream.readinto(), pip._vendor.urllib3.contrib.securetransport.WrappedSocket.recv_into(), pylint.checkers.imports.ImportsChecker.reduce_map_data(), and pylint.checkers.symilar.SimilaritiesChecker.reduce_map_data().
send()
Response pip._vendor.cachecontrol.adapter.CacheControlAdapter.send (self, PreparedRequest request, bool stream = False, None | float | tuple[float, float] | tuple[float, None] timeout = None, bool | str verify = True, (None | bytes | str | tuple[bytes | str, bytes | str]) cert = None, Mapping[str, str] | None proxies = None, Collection[str] | None cacheable_methods = None)
Send a request. Use the request information to see if it
exists in the cache and cache the response if we need to and can.
Reimplemented from pip._vendor.requests.adapters.HTTPAdapter.
Definition at line 50 of file adapter.py.
    ) -> Response:
        """
        Send a request. Use the request information to see if it
        exists in the cache and cache the response if we need to and can.
        """
        cacheable = cacheable_methods or self.cacheable_methods
        if request.method in cacheable:
            try:
                cached_response = self.controller.cached_request(request)
            except zlib.error:
                cached_response = None
            if cached_response:
                return self.build_response(request, cached_response, from_cache=True)
            # check for etags and add headers if appropriate
            request.headers.update(self.controller.conditional_headers(request))
        resp = super().send(request, stream, timeout, verify, cert, proxies)
        return resp
References build_response(), cacheable_methods, controller, and send().
Referenced by urllib3.connection.HTTPConnection._tunnel(), pip._vendor.requests.sessions.Session.request(), requests.sessions.Session.request(), pip._vendor.urllib3.connection.HTTPConnection.request_chunked(), send(), pip._vendor.urllib3.contrib.securetransport.WrappedSocket.sendall(), pip._vendor.urllib3.util.ssltransport.SSLTransport.sendall(), and urllib3.util.ssltransport.SSLTransport.sendall().
Member Data Documentation
cache
pip._vendor.cachecontrol.adapter.CacheControlAdapter.cache = DictCache() if cache is None else cache
Definition at line 41 of file adapter.py.
Referenced by pip._vendor.cachecontrol.controller.CacheController._cache_set(), pip._vendor.cachecontrol.controller.CacheController._load_from_cache(), pip._vendor.cachecontrol.controller.CacheController.cache_response(), pip._vendor.cachecontrol.controller.CacheController.cached_request(), close(), django.middleware.cache.FetchFromCacheMiddleware.process_request(), and django.middleware.cache.UpdateCacheMiddleware.process_response().
cacheable_methods
pip._vendor.cachecontrol.adapter.CacheControlAdapter.cacheable_methods = cacheable_methods or ("GET",)
Definition at line 43 of file adapter.py.
Referenced by build_response(), and send().
chunk_left
int pip._vendor.cachecontrol.adapter.CacheControlAdapter.chunk_left = 0:
Definition at line 139 of file adapter.py.
Referenced by pip._vendor.urllib3.response.HTTPResponse._handle_chunk(), urllib3.response.HTTPResponse._handle_chunk(), pip._vendor.urllib3.response.HTTPResponse._update_chunk_length(), urllib3.response.HTTPResponse._update_chunk_length(), pip._vendor.urllib3.response.HTTPResponse.read_chunked(), and urllib3.response.HTTPResponse.read_chunked().
controller
pip._vendor.cachecontrol.adapter.CacheControlAdapter.controller
Initial value:
=  controller_factory(
            self.cache, cache_etags=cache_etags, serializer=serializer
        )
Definition at line 46 of file adapter.py.
Referenced by build_response(), and send().
heuristic
pip._vendor.cachecontrol.adapter.CacheControlAdapter.heuristic = heuristic
Definition at line 42 of file adapter.py.
Referenced by build_response().
invalidating_methods
dict pip._vendor.cachecontrol.adapter.CacheControlAdapter.invalidating_methods = {"PUT", "PATCH", "DELETE"} static
Definition at line 27 of file adapter.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/cachecontrol/adapter.py