Read&Watch: pip._internal.exceptions.HashErrors Class Reference
pip._internal.exceptions.HashErrors Class Reference
Public Member Functions
None __init__ (self)
None append (self, "HashError" error)
str __str__ (self)
bool __bool__ (self)
Public Attributes
list errors = []
head
Detailed Description
Multiple HashError instances rolled into one for reporting
Definition at line 430 of file exceptions.py.
Constructor & Destructor Documentation
__init__()
None pip._internal.exceptions.HashErrors.__init__ (self)
Definition at line 433 of file exceptions.py.
    def __init__(self) -> None:
        self.errors: List[HashError] = []
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
__bool__()
bool pip._internal.exceptions.HashErrors.__bool__ (self)
Definition at line 449 of file exceptions.py.
    def __bool__(self) -> bool:
        return bool(self.errors)
__str__()
str pip._internal.exceptions.HashErrors.__str__ (self)
Definition at line 439 of file exceptions.py.
    def __str__(self) -> str:
        lines = []
        self.errors.sort(key=lambda e: e.order)
        for cls, errors_of_cls in groupby(self.errors, lambda e: e.__class__):
            lines.append(cls.head)
            lines.extend(e.body() for e in errors_of_cls)
        if lines:
            return "\n".join(lines)
        return ""
append()
None pip._internal.exceptions.HashErrors.append (self, "HashError" error)
Definition at line 436 of file exceptions.py.
    def append(self, error: "HashError") -> None:
        self.errors.append(error)
Referenced by pylint.reporters.ureports.nodes.BaseLayout.__init__(), pylint.reporters.ureports.nodes.EvaluationSection.__init__(), tomlkit.container.Container.__setitem__(), tomlkit.container.Container._handle_dotted_key(), tomlkit.container.Container._replace_at(), tomlkit.container.Container.add(), tomlkit.items.AbstractTable.add(), and pip._vendor.rich._stack.Stack.push().
Member Data Documentation
errors
pip._internal.exceptions.HashErrors.errors = []
Definition at line 434 of file exceptions.py.
Referenced by pip._vendor.distlib.locators.SimpleScrapingLocator._fetch(), pip._vendor.distlib.locators.PyPIJSONLocator._get_project(), django.test.runner.DebugSQLTextTestResult.addError(), django.test.runner.DebugSQLTextTestResult.addSubTest(), pip._vendor.distlib.locators.Locator.get_errors(), django.forms.formsets.BaseFormSet.is_valid(), and django.forms.formsets.BaseFormSet.total_error_count().
head
pip._internal.exceptions.HashErrors.head
Definition at line 443 of file exceptions.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_internal/exceptions.py