Read&Watch: pylint.checkers.misc.EncodingChecker Class Reference
pylint.checkers.misc.EncodingChecker Class Reference
Public Member Functions
None open (self)
None process_module (self, nodes.Module node)
None process_tokens (self, list[tokenize.TokenInfo] tokens)
Public Member Functions inherited from pylint.checkers.base_checker.BaseChecker
None __init__ (self, PyLinter linter)
bool __gt__ (self, Any other)
bool __eq__ (self, object other)
int __hash__ (self)
str __repr__ (self)
str __str__ (self)
str get_full_documentation (self, dict[str, MessageDefinitionTuple] msgs, Iterable[tuple[str, OptionDict, Any]] options, Sequence[tuple[str, str, ReportsCallable]] reports, str|None doc=None, str|None module=None, bool show_options=True)
None add_message (self, str msgid, int|None line=None, nodes.NodeNG|None node=None, Any args=None, Confidence|None confidence=None, int|None col_offset=None, int|None end_lineno=None, int|None end_col_offset=None)
None check_consistency (self)
MessageDefinition create_message_definition_from_tuple (self, str msgid, MessageDefinitionTuple msg_tuple)
list[MessageDefinition] messages (self)
None close (self)
Any get_map_data (self)
None reduce_map_data (self, PyLinter linter, list[Any] data)
Public Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
None __init__ (self, _ArgumentsManager arguments_manager)
Protected Member Functions
str|None _check_encoding (self, int lineno, bytes line, str file_encoding)
Protected Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
Any _option_value (self, str opt)
Iterator[ tuple[str, list[tuple[str, OptionDict, Any]]]|tuple[None, dict[str, list[tuple[str, OptionDict, Any]]]]] _options_by_section (self)
Iterator[tuple[str, OptionDict, Any]] _options_and_values (self, Options|None options=None)
Protected Attributes
_fixme_pattern = re.compile(regex_string, re.I)
Protected Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
_arguments_manager = arguments_manager
Additional Inherited Members
Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
linter = linter
messages
Static Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
str name = ""
dict msgs = {}
tuple reports = ()
bool enabled = True
Static Public Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
tuple options = ()
dict option_groups_descs = {}
Detailed Description
BaseChecker for encoding issues.
Checks for:
* warning notes in the code like FIXME, XXX
* encoding issues.
Definition at line 53 of file misc.py.
Member Function Documentation
_check_encoding()
str | None pylint.checkers.misc.EncodingChecker._check_encoding (self, int lineno, bytes line, str file_encoding) protected
Definition at line 106 of file misc.py.
    ) -> str | None:
        try:
            return line.decode(file_encoding)
        except UnicodeDecodeError:
            pass
        except LookupError:
            if (
                line.startswith(b"#")
                and "coding" in str(line)
                and file_encoding in str(line)
            ):
                msg = f"Cannot decode using encoding '{file_encoding}', bad encoding"
                self.add_message("syntax-error", line=lineno, args=msg)
        return None
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by process_module().
open()
None pylint.checkers.misc.EncodingChecker.open (self)
Called before visiting project (i.e. set of modules).
Reimplemented from pylint.checkers.base_checker.BaseChecker.
Definition at line 95 of file misc.py.
    def open(self) -> None:
        super().open()
        notes = "|".join(re.escape(note) for note in self.linter.config.notes)
        if self.linter.config.notes_rgx:
            regex_string = rf"#\s*({notes}|{self.linter.config.notes_rgx})(?=(:|\s|\Z))"
        else:
            regex_string = rf"#\s*({notes})(?=(:|\s|\Z))"
        self._fixme_pattern = re.compile(regex_string, re.I)
References pylint.checkers.base_checker.BaseChecker.linter, and open().
Referenced by django.contrib.staticfiles.storage.HashedFilesMixin.hashed_name(), and open().
process_module()
None pylint.checkers.misc.EncodingChecker.process_module (self, nodes.Module node)
Inspect the source file to find encoding problem.
Reimplemented from pylint.checkers.base_checker.BaseRawFileChecker.
Definition at line 123 of file misc.py.
    def process_module(self, node: nodes.Module) -> None:
        """Inspect the source file to find encoding problem."""
        encoding = node.file_encoding if node.file_encoding else "ascii"
        with node.stream() as stream:
            for lineno, line in enumerate(stream):
                self._check_encoding(lineno + 1, line, encoding)
References _check_encoding().
process_tokens()
None pylint.checkers.misc.EncodingChecker.process_tokens (self, list[tokenize.TokenInfo] tokens)
Inspect the source to find fixme problems.
Reimplemented from pylint.checkers.base_checker.BaseTokenChecker.
Definition at line 131 of file misc.py.
    def process_tokens(self, tokens: list[tokenize.TokenInfo]) -> None:
        """Inspect the source to find fixme problems."""
        if not self.linter.config.notes:
            return
        for token_info in tokens:
            if token_info.type != tokenize.COMMENT:
                continue
            comment_text = token_info.string[1:].lstrip()  # trim '#' and white-spaces
            if self._fixme_pattern.search("#" + comment_text.lower()):
                self.add_message(
                    "fixme",
                    col_offset=token_info.start[1] + 1,
                    args=comment_text,
                    line=token_info.start[0],
                )
References _fixme_pattern, pylint.checkers.base_checker.BaseChecker.add_message(), and pylint.checkers.base_checker.BaseChecker.linter.
Referenced by pylint.lint.pylinter.PyLinter._check_astroid_module().
Member Data Documentation
_fixme_pattern
pylint.checkers.misc.EncodingChecker._fixme_pattern = re.compile(regex_string, re.I) protected
Definition at line 104 of file misc.py.
Referenced by process_tokens().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pylint/checkers/misc.py