Read&Watch: pip._vendor.rich.syntax.PygmentsSyntaxTheme Class Reference
pip._vendor.rich.syntax.PygmentsSyntaxTheme Class Reference
Public Member Functions
None __init__ (self, Union[str, Type[PygmentsStyle]] theme)
Style get_style_for_token (self, TokenType token_type)
Style get_background_style (self)
Protected Attributes
dict _style_cache = {}
_pygments_style_class = get_style_by_name(theme)
_background_color = self._pygments_style_class.background_color
_background_style = Style(bgcolor=self._background_color)
Detailed Description
Syntax theme that delegates to Pygments theme.
Definition at line 137 of file syntax.py.
Constructor & Destructor Documentation
__init__()
None pip._vendor.rich.syntax.PygmentsSyntaxTheme.__init__ (self, Union[str, Type[PygmentsStyle]] theme)
Definition at line 140 of file syntax.py.
    def __init__(self, theme: Union[str, Type[PygmentsStyle]]) -> None:
        self._style_cache: Dict[TokenType, Style] = {}
        if isinstance(theme, str):
            try:
                self._pygments_style_class = get_style_by_name(theme)
            except ClassNotFound:
                self._pygments_style_class = get_style_by_name("default")
        else:
            self._pygments_style_class = theme
        self._background_color = self._pygments_style_class.background_color
        self._background_style = Style(bgcolor=self._background_color)
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
get_background_style()
Style pip._vendor.rich.syntax.PygmentsSyntaxTheme.get_background_style (self)
Get the background color.
Reimplemented from pip._vendor.rich.syntax.SyntaxTheme.
Definition at line 175 of file syntax.py.
    def get_background_style(self) -> Style:
        return self._background_style
References _background_style.
get_style_for_token()
Style pip._vendor.rich.syntax.PygmentsSyntaxTheme.get_style_for_token (self, TokenType token_type)
Get a style from a Pygments class.
Reimplemented from pip._vendor.rich.syntax.SyntaxTheme.
Definition at line 153 of file syntax.py.
    def get_style_for_token(self, token_type: TokenType) -> Style:
        """Get a style from a Pygments class."""
        try:
            return self._style_cache[token_type]
        except KeyError:
            try:
                pygments_style = self._pygments_style_class.style_for_token(token_type)
            except KeyError:
                style = Style.null()
            else:
                color = pygments_style["color"]
                bgcolor = pygments_style["bgcolor"]
                style = Style(
                    color="#" + color if color else "#000000",
                    bgcolor="#" + bgcolor if bgcolor else self._background_color,
                    bold=pygments_style["bold"],
                    italic=pygments_style["italic"],
                    underline=pygments_style["underline"],
                )
            self._style_cache[token_type] = style
        return style
References _background_color, _pygments_style_class, and _style_cache.
Member Data Documentation
_background_color
pip._vendor.rich.syntax.PygmentsSyntaxTheme._background_color = self._pygments_style_class.background_color protected
Definition at line 150 of file syntax.py.
Referenced by get_style_for_token().
_background_style
pip._vendor.rich.syntax.PygmentsSyntaxTheme._background_style = Style(bgcolor=self._background_color) protected
Definition at line 151 of file syntax.py.
Referenced by pip._vendor.rich.syntax.ANSISyntaxTheme.get_background_style(), and get_background_style().
_pygments_style_class
pip._vendor.rich.syntax.PygmentsSyntaxTheme._pygments_style_class = get_style_by_name(theme) protected
Definition at line 144 of file syntax.py.
Referenced by get_style_for_token().
_style_cache
dict pip._vendor.rich.syntax.PygmentsSyntaxTheme._style_cache = {} protected
Definition at line 141 of file syntax.py.
Referenced by pip._vendor.rich.syntax.ANSISyntaxTheme.get_style_for_token(), and get_style_for_token().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/rich/syntax.py