Read&Watch: pylint.checkers.design_analysis.MisdesignChecker Class Reference
pylint.checkers.design_analysis.MisdesignChecker Class Reference
Public Member Functions
None __init__ (self, PyLinter linter)
None open (self)
None visit_classdef (self, nodes.ClassDef node)
None leave_classdef (self, nodes.ClassDef node)
None visit_functiondef (self, nodes.FunctionDef node)
None leave_functiondef (self, nodes.FunctionDef node)
None visit_return (self, nodes.Return _)
None visit_default (self, nodes.NodeNG node)
None visit_try (self, nodes.Try node)
None visit_if (self, nodes.If node)
None visit_while (self, nodes.While node)
Public Member Functions inherited from pylint.checkers.base_checker.BaseChecker
None __init__ (self, PyLinter linter)
bool __gt__ (self, Any other)
bool __eq__ (self, object other)
int __hash__ (self)
str __repr__ (self)
str __str__ (self)
str get_full_documentation (self, dict[str, MessageDefinitionTuple] msgs, Iterable[tuple[str, OptionDict, Any]] options, Sequence[tuple[str, str, ReportsCallable]] reports, str|None doc=None, str|None module=None, bool show_options=True)
None add_message (self, str msgid, int|None line=None, nodes.NodeNG|None node=None, Any args=None, Confidence|None confidence=None, int|None col_offset=None, int|None end_lineno=None, int|None end_col_offset=None)
None check_consistency (self)
MessageDefinition create_message_definition_from_tuple (self, str msgid, MessageDefinitionTuple msg_tuple)
list[MessageDefinition] messages (self)
None close (self)
Any get_map_data (self)
None reduce_map_data (self, PyLinter linter, list[Any] data)
Public Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
None __init__ (self, _ArgumentsManager arguments_manager)
Static Public Attributes
None visit_asyncfunctiondef = visit_functiondef
None leave_asyncfunctiondef = leave_functiondef
None visit_for = visit_while
Static Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
str name = ""
dict msgs = {}
tuple reports = ()
bool enabled = True
Static Public Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
tuple options = ()
dict option_groups_descs = {}
Protected Member Functions
None _inc_all_stmts (self, int amount)
None _check_boolean_expressions (self, nodes.If node)
None _inc_branch (self, nodes.NodeNG node, int branchesnum=1)
Protected Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
Any _option_value (self, str opt)
Iterator[ tuple[str, list[tuple[str, OptionDict, Any]]]|tuple[None, dict[str, list[tuple[str, OptionDict, Any]]]]] _options_by_section (self)
Iterator[tuple[str, OptionDict, Any]] _options_and_values (self, Options|None options=None)
Protected Attributes
list[int] _returns
defaultdict[nodes.LocalsDictNodeNG, int] _branches
list[int] _stmts
tuple _exclude_too_few_public_methods
Protected Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
_arguments_manager = arguments_manager
Additional Inherited Members
Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
linter = linter
messages
Detailed Description
Checker of potential misdesigns.
Checks for sign of poor/misdesign:
* number of methods, attributes, local variables...
* size, complexity of functions, methods
Definition at line 290 of file design_analysis.py.
Constructor & Destructor Documentation
__init__()
None pylint.checkers.design_analysis.MisdesignChecker.__init__ (self, PyLinter linter)
Definition at line 429 of file design_analysis.py.
    def __init__(self, linter: PyLinter) -> None:
        super().__init__(linter)
        self._returns: list[int]
        self._branches: defaultdict[nodes.LocalsDictNodeNG, int]
        self._stmts: list[int]
References __init__().
Referenced by __init__().
Member Function Documentation
_check_boolean_expressions()
None pylint.checkers.design_analysis.MisdesignChecker._check_boolean_expressions (self, nodes.If node) protected
Go through "if" node `node` and count its boolean expressions
if the 'if' node test is a BoolOp node.
Definition at line 672 of file design_analysis.py.
    def _check_boolean_expressions(self, node: nodes.If) -> None:
        """Go through "if" node `node` and count its boolean expressions
        if the 'if' node test is a BoolOp node.
        """
        condition = node.test
        if not isinstance(condition, astroid.BoolOp):
            return
        nb_bool_expr = _count_boolean_expressions(condition)
        if nb_bool_expr > self.linter.config.max_bool_expr:
            self.add_message(
                "too-many-boolean-expressions",
                node=condition,
                args=(nb_bool_expr, self.linter.config.max_bool_expr),
            )
References pylint.checkers.design_analysis._count_boolean_expressions(), pylint.checkers.base_checker.BaseChecker.add_message(), and pylint.checkers.base_checker.BaseChecker.linter.
Referenced by visit_if().
_inc_all_stmts()
None pylint.checkers.design_analysis.MisdesignChecker._inc_all_stmts (self, int amount) protected
Definition at line 445 of file design_analysis.py.
    def _inc_all_stmts(self, amount: int) -> None:
        for i, _ in enumerate(self._stmts):
            self._stmts[i] += amount
References _stmts.
Referenced by visit_default(), visit_if(), and visit_try().
_inc_branch()
None pylint.checkers.design_analysis.MisdesignChecker._inc_branch (self, nodes.NodeNG node, int branchesnum = 1) protected
Increments the branches counter.
Definition at line 696 of file design_analysis.py.
    def _inc_branch(self, node: nodes.NodeNG, branchesnum: int = 1) -> None:
        """Increments the branches counter."""
        self._branches[node.scope()] += branchesnum
References _branches.
Referenced by visit_if(), visit_try(), and visit_while().
leave_classdef()
None pylint.checkers.design_analysis.MisdesignChecker.leave_classdef (self, nodes.ClassDef node)
Check number of public methods.
Definition at line 486 of file design_analysis.py.
    def leave_classdef(self, node: nodes.ClassDef) -> None:
        """Check number of public methods."""
        my_methods = sum(
            1 for method in node.mymethods() if not method.name.startswith("_")
        )
        # Does the class contain less than n public methods ?
        # This checks only the methods defined in the current class,
        # since the user might not have control over the classes
        # from the ancestors. It avoids some false positives
        # for classes such as unittest.TestCase, which provides
        # a lot of assert methods. It doesn't make sense to warn
        # when the user subclasses TestCase to add his own tests.
        if my_methods > self.linter.config.max_public_methods:
            self.add_message(
                "too-many-public-methods",
                node=node,
                args=(my_methods, self.linter.config.max_public_methods),
            )
        # Stop here if the class is excluded via configuration.
        if node.type == "class" and self._exclude_too_few_public_methods:
            for ancestor in node.ancestors():
                if any(
                    pattern.match(ancestor.qname())
                    for pattern in self._exclude_too_few_public_methods
                ):
                    return
        # Stop here for exception, metaclass, interface classes and other
        # classes for which we don't need to count the methods.
        if node.type != "class" or _is_exempt_from_public_methods(node):
            return
        # Does the class contain more than n public methods ?
        # This checks all the methods defined by ancestors and
        # by the current class.
        all_methods = _count_methods_in_class(node)
        if all_methods < self.linter.config.min_public_methods:
            self.add_message(
                "too-few-public-methods",
                node=node,
                args=(all_methods, self.linter.config.min_public_methods),
            )
References pylint.checkers.design_analysis._count_methods_in_class(), _exclude_too_few_public_methods, pylint.checkers.design_analysis._is_exempt_from_public_methods(), pylint.checkers.base_checker.BaseChecker.add_message(), and pylint.checkers.base_checker.BaseChecker.linter.
leave_functiondef()
None pylint.checkers.design_analysis.MisdesignChecker.leave_functiondef (self, nodes.FunctionDef node)
Most of the work is done here on close:
checks for max returns, branch, return in __init__.
Definition at line 607 of file design_analysis.py.
    def leave_functiondef(self, node: nodes.FunctionDef) -> None:
        """Most of the work is done here on close:
        checks for max returns, branch, return in __init__.
        """
        returns = self._returns.pop()
        if returns > self.linter.config.max_returns:
            self.add_message(
                "too-many-return-statements",
                node=node,
                args=(returns, self.linter.config.max_returns),
            )
        branches = self._branches[node]
        if branches > self.linter.config.max_branches:
            self.add_message(
                "too-many-branches",
                node=node,
                args=(branches, self.linter.config.max_branches),
            )
        # check number of statements
        stmts = self._stmts.pop()
        if stmts > self.linter.config.max_statements:
            self.add_message(
                "too-many-statements",
                node=node,
                args=(stmts, self.linter.config.max_statements),
            )
References _branches, _returns, _stmts, pylint.checkers.base_checker.BaseChecker.add_message(), and pylint.checkers.base_checker.BaseChecker.linter.
open()
None pylint.checkers.design_analysis.MisdesignChecker.open (self)
Initialize visit variables.
Reimplemented from pylint.checkers.base_checker.BaseChecker.
Definition at line 435 of file design_analysis.py.
    def open(self) -> None:
        """Initialize visit variables."""
        self.linter.stats.reset_node_count()
        self._returns = []
        self._branches = defaultdict(int)
        self._stmts = []
        self._exclude_too_few_public_methods = (
            self.linter.config.exclude_too_few_public_methods
        )
References _branches, _returns, _stmts, and pylint.checkers.base_checker.BaseChecker.linter.
Referenced by django.contrib.staticfiles.storage.HashedFilesMixin.hashed_name().
visit_classdef()
None pylint.checkers.design_analysis.MisdesignChecker.visit_classdef (self, nodes.ClassDef node)
Check size of inheritance hierarchy and number of instance attributes.
Definition at line 455 of file design_analysis.py.
    def visit_classdef(self, node: nodes.ClassDef) -> None:
        """Check size of inheritance hierarchy and number of instance attributes."""
        parents = _get_parents(
            node,
            STDLIB_CLASSES_IGNORE_ANCESTOR.union(self.linter.config.ignored_parents),
        )
        nb_parents = len(parents)
        if nb_parents > self.linter.config.max_parents:
            self.add_message(
                "too-many-ancestors",
                node=node,
                args=(nb_parents, self.linter.config.max_parents),
            )
        # Something at inference time is modifying instance_attrs to add
        # properties from parent classes. Given how much we cache inference
        # results, mutating instance_attrs can become a real mess. Filter
        # them out here until the root cause is solved.
        # https://github.com/pylint-dev/astroid/issues/2273
        root = node.root()
        filtered_attrs = [
            k for (k, v) in node.instance_attrs.items() if v[0].root() is root
        ]
        if len(filtered_attrs) > self.linter.config.max_attributes:
            self.add_message(
                "too-many-instance-attributes",
                node=node,
                args=(len(filtered_attrs), self.linter.config.max_attributes),
            )
References pylint.checkers.design_analysis._get_parents(), pylint.checkers.base_checker.BaseChecker.add_message(), and pylint.checkers.base_checker.BaseChecker.linter.
Referenced by pylint.pyreverse.inspector.Linker.visit_assignname(), and pylint.checkers.exceptions.ExceptionRaiseLeafVisitor.visit_instance().
visit_default()
None pylint.checkers.design_analysis.MisdesignChecker.visit_default (self, nodes.NodeNG node)
Default visit method -> increments the statements counter if
necessary.
Definition at line 642 of file design_analysis.py.
    def visit_default(self, node: nodes.NodeNG) -> None:
        """Default visit method -> increments the statements counter if
        necessary.
        """
        if node.is_statement:
            self._inc_all_stmts(1)
References _inc_all_stmts().
Referenced by pylint.checkers.exceptions.BaseVisitor.visit().
visit_functiondef()
None pylint.checkers.design_analysis.MisdesignChecker.visit_functiondef (self, nodes.FunctionDef node)
Check function name, docstring, arguments, redefinition,
variable names, max locals.
Definition at line 540 of file design_analysis.py.
    def visit_functiondef(self, node: nodes.FunctionDef) -> None:
        """Check function name, docstring, arguments, redefinition,
        variable names, max locals.
        """
        # init branch and returns counters
        self._returns.append(0)
        # check number of arguments
        args = node.args.args + node.args.posonlyargs + node.args.kwonlyargs
        pos_args = node.args.args + node.args.posonlyargs
        ignored_argument_names = self.linter.config.ignored_argument_names
        if args is not None:
            ignored_args_num = 0
            if ignored_argument_names:
                ignored_pos_args_num = sum(
                    1 for arg in pos_args if ignored_argument_names.match(arg.name)
                )
                ignored_kwonly_args_num = sum(
                    1
                    for arg in node.args.kwonlyargs
                    if ignored_argument_names.match(arg.name)
                )
                ignored_args_num = ignored_pos_args_num + ignored_kwonly_args_num
            argnum = len(args) - ignored_args_num
            if argnum > self.linter.config.max_args:
                self.add_message(
                    "too-many-arguments",
                    node=node,
                    args=(len(args), self.linter.config.max_args),
                )
            pos_args_count = (
                len(args) - len(node.args.kwonlyargs) - ignored_pos_args_num
            )
            if pos_args_count > self.linter.config.max_positional_arguments:
                self.add_message(
                    "too-many-positional-arguments",
                    node=node,
                    args=(pos_args_count, self.linter.config.max_positional_arguments),
                    confidence=HIGH,
                )
        else:
            ignored_args_num = 0
        # check number of local variables
        locnum = len(node.locals) - ignored_args_num
        # decrement number of local variables if '_' is one of them
        if "_" in node.locals:
            locnum -= 1
        if locnum > self.linter.config.max_locals:
            self.add_message(
                "too-many-locals",
                node=node,
                args=(locnum, self.linter.config.max_locals),
            )
        # init new statements counter
        self._stmts.append(1)
References _returns, _stmts, pylint.checkers.base_checker.BaseChecker.add_message(), and pylint.checkers.base_checker.BaseChecker.linter.
Referenced by pylint.pyreverse.inspector.Linker.visit_assignname().
visit_if()
None pylint.checkers.design_analysis.MisdesignChecker.visit_if (self, nodes.If node)
Increments the branches counter and checks boolean expressions.
Definition at line 660 of file design_analysis.py.
    def visit_if(self, node: nodes.If) -> None:
        """Increments the branches counter and checks boolean expressions."""
        self._check_boolean_expressions(node)
        branches = 1
        # don't double count If nodes coming from some 'elif'
        if node.orelse and (
            len(node.orelse) > 1 or not isinstance(node.orelse[0], astroid.If)
        ):
            branches += 1
        self._inc_branch(node, branches)
        self._inc_all_stmts(branches)
References _check_boolean_expressions(), _inc_all_stmts(), and _inc_branch().
visit_return()
None pylint.checkers.design_analysis.MisdesignChecker.visit_return (self, nodes.Return _)
Count number of returns.
Definition at line 636 of file design_analysis.py.
    def visit_return(self, _: nodes.Return) -> None:
        """Count number of returns."""
        if not self._returns:
            return  # return outside function, reported by the base checker
        self._returns[-1] += 1
References _returns.
Referenced by pylint.checkers.refactoring.refactoring_checker.RefactoringChecker.visit_assign().
visit_try()
None pylint.checkers.design_analysis.MisdesignChecker.visit_try (self, nodes.Try node)
Increments the branches counter.
Definition at line 649 of file design_analysis.py.
    def visit_try(self, node: nodes.Try) -> None:
        """Increments the branches counter."""
        branches = len(node.handlers)
        if node.orelse:
            branches += 1
        if node.finalbody:
            branches += 1
        self._inc_branch(node, branches)
        self._inc_all_stmts(branches)
References _inc_all_stmts(), and _inc_branch().
Referenced by pylint.checkers.exceptions.ExceptionsChecker.visit_trystar().
visit_while()
None pylint.checkers.design_analysis.MisdesignChecker.visit_while (self, nodes.While node)
Increments the branches counter.
Definition at line 687 of file design_analysis.py.
    def visit_while(self, node: nodes.While) -> None:
        """Increments the branches counter."""
        branches = 1
        if node.orelse:
            branches += 1
        self._inc_branch(node, branches)
References _inc_branch().
Member Data Documentation
_branches
defaultdict[nodes.LocalsDictNodeNG, int] pylint.checkers.design_analysis.MisdesignChecker._branches protected
Definition at line 432 of file design_analysis.py.
Referenced by _inc_branch(), leave_functiondef(), and open().
_exclude_too_few_public_methods
tuple pylint.checkers.design_analysis.MisdesignChecker._exclude_too_few_public_methods protected
Initial value:
=  (
            self.linter.config.exclude_too_few_public_methods
        )
Definition at line 441 of file design_analysis.py.
Referenced by leave_classdef().
_returns
list[int] pylint.checkers.design_analysis.MisdesignChecker._returns protected
Definition at line 431 of file design_analysis.py.
Referenced by leave_functiondef(), open(), visit_functiondef(), and visit_return().
_stmts
pylint.checkers.design_analysis.MisdesignChecker._stmts protected
Definition at line 433 of file design_analysis.py.
Referenced by _inc_all_stmts(), leave_functiondef(), open(), and visit_functiondef().
leave_asyncfunctiondef
None pylint.checkers.design_analysis.MisdesignChecker.leave_asyncfunctiondef = leave_functiondef static
Definition at line 634 of file design_analysis.py.
visit_asyncfunctiondef
None pylint.checkers.design_analysis.MisdesignChecker.visit_asyncfunctiondef = visit_functiondef static
Definition at line 598 of file design_analysis.py.
visit_for
None pylint.checkers.design_analysis.MisdesignChecker.visit_for = visit_while static
Definition at line 694 of file design_analysis.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pylint/checkers/design_analysis.py