Read&Watch: pip._vendor.platformdirs.android.Android Class Reference
pip._vendor.platformdirs.android.Android Class Reference
Public Member Functions
str user_data_dir (self)
str site_data_dir (self)
str user_config_dir (self)
str site_config_dir (self)
str user_cache_dir (self)
str site_cache_dir (self)
str user_state_dir (self)
str user_log_dir (self)
str user_documents_dir (self)
str user_downloads_dir (self)
str user_pictures_dir (self)
str user_videos_dir (self)
str user_music_dir (self)
str user_desktop_dir (self)
str user_runtime_dir (self)
str site_runtime_dir (self)
Public Member Functions inherited from pip._vendor.platformdirs.api.PlatformDirsABC
None __init__ (self, str|None appname=None, str|None|Literal[False] appauthor=None, str|None version=None, bool roaming=False, bool multipath=False, bool opinion=True, bool ensure_exists=False)
Path user_data_path (self)
Path site_data_path (self)
Path user_config_path (self)
Path site_config_path (self)
Path user_cache_path (self)
Path site_cache_path (self)
Path user_state_path (self)
Path user_log_path (self)
Path user_documents_path (self)
Path user_downloads_path (self)
Path user_pictures_path (self)
Path user_videos_path (self)
Path user_music_path (self)
Path user_desktop_path (self)
Path user_runtime_path (self)
Path site_runtime_path (self)
Iterator[str] iter_config_dirs (self)
Iterator[str] iter_data_dirs (self)
Iterator[str] iter_cache_dirs (self)
Iterator[str] iter_runtime_dirs (self)
Iterator[Path] iter_config_paths (self)
Iterator[Path] iter_data_paths (self)
Iterator[Path] iter_cache_paths (self)
Iterator[Path] iter_runtime_paths (self)
Additional Inherited Members
Public Attributes inherited from pip._vendor.platformdirs.api.PlatformDirsABC
appname = appname
appauthor = appauthor
version = version
roaming = roaming
multipath = multipath
opinion = opinion
ensure_exists = ensure_exists
Protected Member Functions inherited from pip._vendor.platformdirs.api.PlatformDirsABC
str _append_app_name_and_version (self, *str base)
None _optionally_create_directory (self, str path)
Detailed Description
Follows the guidance `from here <https://android.stackexchange.com/a/216132>`_.
Makes use of the `appname <platformdirs.api.PlatformDirsABC.appname>`, `version
<platformdirs.api.PlatformDirsABC.version>`, `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
Definition at line 14 of file android.py.
Member Function Documentation
site_cache_dir()
str pip._vendor.platformdirs.android.Android.site_cache_dir (self)
:return: cache directory shared by users, same as `user_cache_dir`
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 52 of file android.py.
    def site_cache_dir(self) -> str:
        """:return: cache directory shared by users, same as `user_cache_dir`"""
        return self.user_cache_dir
References pip._vendor.platformdirs.api.PlatformDirsABC.user_cache_dir.
site_config_dir()
str pip._vendor.platformdirs.android.Android.site_config_dir (self)
:return: config directory shared by the users, same as `user_config_dir`
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 42 of file android.py.
    def site_config_dir(self) -> str:
        """:return: config directory shared by the users, same as `user_config_dir`"""
        return self.user_config_dir
References pip._vendor.platformdirs.api.PlatformDirsABC.user_config_dir.
site_data_dir()
str pip._vendor.platformdirs.android.Android.site_data_dir (self)
:return: data directory shared by users, same as `user_data_dir`
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 29 of file android.py.
    def site_data_dir(self) -> str:
        """:return: data directory shared by users, same as `user_data_dir`"""
        return self.user_data_dir
References pip._vendor.platformdirs.api.PlatformDirsABC.user_data_dir.
site_runtime_dir()
str pip._vendor.platformdirs.android.Android.site_runtime_dir (self)
:return: runtime directory shared by users, same as `user_runtime_dir`
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 114 of file android.py.
    def site_runtime_dir(self) -> str:
        """:return: runtime directory shared by users, same as `user_runtime_dir`"""
        return self.user_runtime_dir
@lru_cache(maxsize=1)
References pip._vendor.platformdirs.api.PlatformDirsABC.user_runtime_dir.
user_cache_dir()
str pip._vendor.platformdirs.android.Android.user_cache_dir (self)
:return: cache directory tied to the user, e.g.,``/data/user/<userid>/<packagename>/cache/<AppName>``
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 47 of file android.py.
    def user_cache_dir(self) -> str:
        """:return: cache directory tied to the user, e.g.,``/data/user/<userid>/<packagename>/cache/<AppName>``"""
        return self._append_app_name_and_version(cast(str, _android_folder()), "cache")
References pip._vendor.platformdirs.android._android_folder(), and pip._vendor.platformdirs.api.PlatformDirsABC._append_app_name_and_version().
user_config_dir()
str pip._vendor.platformdirs.android.Android.user_config_dir (self)
:return: config directory tied to the user, e.g. \
``/data/user/<userid>/<packagename>/shared_prefs/<AppName>``
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 34 of file android.py.
    def user_config_dir(self) -> str:
        """
        :return: config directory tied to the user, e.g. \
        ``/data/user/<userid>/<packagename>/shared_prefs/<AppName>``
        """
        return self._append_app_name_and_version(cast(str, _android_folder()), "shared_prefs")
References pip._vendor.platformdirs.android._android_folder(), and pip._vendor.platformdirs.api.PlatformDirsABC._append_app_name_and_version().
user_data_dir()
str pip._vendor.platformdirs.android.Android.user_data_dir (self)
:return: data directory tied to the user, e.g. ``/data/user/<userid>/<packagename>/files/<AppName>``
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 24 of file android.py.
    def user_data_dir(self) -> str:
        """:return: data directory tied to the user, e.g. ``/data/user/<userid>/<packagename>/files/<AppName>``"""
        return self._append_app_name_and_version(cast(str, _android_folder()), "files")
References pip._vendor.platformdirs.android._android_folder(), and pip._vendor.platformdirs.api.PlatformDirsABC._append_app_name_and_version().
user_desktop_dir()
str pip._vendor.platformdirs.android.Android.user_desktop_dir (self)
:return: desktop directory tied to the user e.g. ``/storage/emulated/0/Desktop``
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 98 of file android.py.
    def user_desktop_dir(self) -> str:
        """:return: desktop directory tied to the user e.g. ``/storage/emulated/0/Desktop``"""
        return "/storage/emulated/0/Desktop"
user_documents_dir()
str pip._vendor.platformdirs.android.Android.user_documents_dir (self)
:return: documents directory tied to the user e.g. ``/storage/emulated/0/Documents``
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 73 of file android.py.
    def user_documents_dir(self) -> str:
        """:return: documents directory tied to the user e.g. ``/storage/emulated/0/Documents``"""
        return _android_documents_folder()
References pip._vendor.platformdirs.android._android_documents_folder().
user_downloads_dir()
str pip._vendor.platformdirs.android.Android.user_downloads_dir (self)
:return: downloads directory tied to the user e.g. ``/storage/emulated/0/Downloads``
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 78 of file android.py.
    def user_downloads_dir(self) -> str:
        """:return: downloads directory tied to the user e.g. ``/storage/emulated/0/Downloads``"""
        return _android_downloads_folder()
References pip._vendor.platformdirs.android._android_downloads_folder().
user_log_dir()
str pip._vendor.platformdirs.android.Android.user_log_dir (self)
:return: log directory tied to the user, same as `user_cache_dir` if not opinionated else ``log`` in it,
  e.g. ``/data/user/<userid>/<packagename>/cache/<AppName>/log``
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 62 of file android.py.
    def user_log_dir(self) -> str:
        """
        :return: log directory tied to the user, same as `user_cache_dir` if not opinionated else ``log`` in it,
          e.g. ``/data/user/<userid>/<packagename>/cache/<AppName>/log``
        """
        path = self.user_cache_dir
        if self.opinion:
            path = os.path.join(path, "log")  # noqa: PTH118
        return path
References pip._vendor.platformdirs.api.PlatformDirsABC.user_cache_dir.
user_music_dir()
str pip._vendor.platformdirs.android.Android.user_music_dir (self)
:return: music directory tied to the user e.g. ``/storage/emulated/0/Music``
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 93 of file android.py.
    def user_music_dir(self) -> str:
        """:return: music directory tied to the user e.g. ``/storage/emulated/0/Music``"""
        return _android_music_folder()
References pip._vendor.platformdirs.android._android_music_folder().
user_pictures_dir()
str pip._vendor.platformdirs.android.Android.user_pictures_dir (self)
:return: pictures directory tied to the user e.g. ``/storage/emulated/0/Pictures``
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 83 of file android.py.
    def user_pictures_dir(self) -> str:
        """:return: pictures directory tied to the user e.g. ``/storage/emulated/0/Pictures``"""
        return _android_pictures_folder()
References pip._vendor.platformdirs.android._android_pictures_folder().
user_runtime_dir()
str pip._vendor.platformdirs.android.Android.user_runtime_dir (self)
:return: runtime directory tied to the user, same as `user_cache_dir` if not opinionated else ``tmp`` in it,
  e.g. ``/data/user/<userid>/<packagename>/cache/<AppName>/tmp``
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 103 of file android.py.
    def user_runtime_dir(self) -> str:
        """
        :return: runtime directory tied to the user, same as `user_cache_dir` if not opinionated else ``tmp`` in it,
          e.g. ``/data/user/<userid>/<packagename>/cache/<AppName>/tmp``
        """
        path = self.user_cache_dir
        if self.opinion:
            path = os.path.join(path, "tmp")  # noqa: PTH118
        return path
References opinion, and pip._vendor.platformdirs.api.PlatformDirsABC.user_cache_dir.
user_state_dir()
str pip._vendor.platformdirs.android.Android.user_state_dir (self)
:return: state directory tied to the user, same as `user_data_dir`
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 57 of file android.py.
    def user_state_dir(self) -> str:
        """:return: state directory tied to the user, same as `user_data_dir`"""
        return self.user_data_dir
References pip._vendor.platformdirs.api.PlatformDirsABC.user_data_dir.
user_videos_dir()
str pip._vendor.platformdirs.android.Android.user_videos_dir (self)
:return: videos directory tied to the user e.g. ``/storage/emulated/0/DCIM/Camera``
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 88 of file android.py.
    def user_videos_dir(self) -> str:
        """:return: videos directory tied to the user e.g. ``/storage/emulated/0/DCIM/Camera``"""
        return _android_videos_folder()
References pip._vendor.platformdirs.android._android_videos_folder().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/platformdirs/android.py