Read&Watch: astroid.builder.AstroidBuilder Class Reference
astroid.builder.AstroidBuilder Class Reference
Public Member Functions
None __init__ (self, AstroidManager|None manager=None, bool apply_transforms=True)
nodes.Module module_build (self, types.ModuleType module, str|None modname=None)
nodes.Module file_build (self, str path, str|None modname=None)
nodes.Module string_build (self, str data, str modname="", str|None path=None)
None add_from_names_to_locals (self, nodes.ImportFrom node)
None delayed_assattr (self, nodes.AssignAttr node)
Public Member Functions inherited from astroid.raw_building.InspectBuilder
None __init__ (self, AstroidManager|None manager_instance=None)
nodes.Module inspect_build (self, types.ModuleType module, str|None modname=None, str|None path=None)
None object_build (self, nodes.Module|nodes.ClassDef node, types.ModuleType|type obj)
bool imported_member (self, node, member, str name)
Protected Member Functions
nodes.Module _post_build (self, nodes.Module module, rebuilder.TreeRebuilder builder, str encoding)
tuple[nodes.Module, rebuilder.TreeRebuilder] _data_build (self, str data, str modname, str|None path)
Protected Attributes
_apply_transforms = apply_transforms
Protected Attributes inherited from astroid.raw_building.InspectBuilder
_manager = manager_instance or AstroidManager()
dict _done = {}
types.ModuleType _module = member.__func__
Additional Inherited Members
Static Public Attributes inherited from astroid.raw_building.InspectBuilder
bool bootstrapped = False
Static Protected Attributes inherited from astroid.raw_building.InspectBuilder
dict _CONST_PROXY = {}
Detailed Description
Class for building an astroid tree from source code or from a live module.
The param *manager* specifies the manager class which should be used.
If no manager is given, then the default one will be used. The
param *apply_transforms* determines if the transforms should be
applied after the tree was built from source or from a live object,
by default being True.
Definition at line 62 of file builder.py.
Constructor & Destructor Documentation
__init__()
None astroid.builder.AstroidBuilder.__init__ (self, AstroidManager | None manager = None, bool apply_transforms = True)
Definition at line 72 of file builder.py.
    ) -> None:
        super().__init__(manager)
        self._apply_transforms = apply_transforms
        if not raw_building.InspectBuilder.bootstrapped:
            raw_building._astroid_bootstrapping()
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Function Documentation
_data_build()
tuple[nodes.Module, rebuilder.TreeRebuilder] astroid.builder.AstroidBuilder._data_build (self, str data, str modname, str | None path) protected
Build tree node from data and add some informations.
Definition at line 176 of file builder.py.
    ) -> tuple[nodes.Module, rebuilder.TreeRebuilder]:
        """Build tree node from data and add some informations."""
        try:
            node, parser_module = _parse_string(
                data, type_comments=True, modname=modname
            )
        except (TypeError, ValueError, SyntaxError) as exc:
            raise AstroidSyntaxError(
                "Parsing Python code failed:\n{error}",
                source=data,
                modname=modname,
                path=path,
                error=exc,
            ) from exc
        if path is not None:
            node_file = os.path.abspath(path)
        else:
            node_file = "<?>"
        if modname.endswith(".__init__"):
            modname = modname[:-9]
            package = True
        else:
            package = (
                path is not None
                and os.path.splitext(os.path.basename(path))[0] == "__init__"
            )
        builder = rebuilder.TreeRebuilder(self._manager, parser_module, data)
        module = builder.visit_module(node, modname, node_file, package)
        return module, builder
References astroid.raw_building.InspectBuilder._manager, and astroid.builder._parse_string().
Referenced by file_build(), and string_build().
_post_build()
nodes.Module astroid.builder.AstroidBuilder._post_build (self, nodes.Module module, rebuilder.TreeRebuilder builder, str encoding) protected
Handles encoding and delayed nodes after a module has been built.
Definition at line 155 of file builder.py.
    ) -> nodes.Module:
        """Handles encoding and delayed nodes after a module has been built."""
        module.file_encoding = encoding
        self._manager.cache_module(module)
        # post tree building steps after we stored the module in the cache:
        for from_node in builder._import_from_nodes:
            if from_node.modname == "__future__":
                for symbol, _ in from_node.names:
                    module.future_imports.add(symbol)
            self.add_from_names_to_locals(from_node)
        # handle delayed assattr nodes
        for delayed in builder._delayed_assattr:
            self.delayed_assattr(delayed)
        # Visit the transforms
        if self._apply_transforms:
            module = self._manager.visit_transforms(module)
        return module
References _apply_transforms, astroid.raw_building.InspectBuilder._manager, add_from_names_to_locals(), and delayed_assattr().
Referenced by file_build(), and string_build().
add_from_names_to_locals()
None astroid.builder.AstroidBuilder.add_from_names_to_locals (self, nodes.ImportFrom node)
Store imported names to the locals.
Resort the locals if coming from a delayed node
Definition at line 209 of file builder.py.
    def add_from_names_to_locals(self, node: nodes.ImportFrom) -> None:
        """Store imported names to the locals.
        Resort the locals if coming from a delayed node
        """
        def _key_func(node: nodes.NodeNG) -> int:
            return node.fromlineno or 0
        def sort_locals(my_list: list[nodes.NodeNG]) -> None:
            my_list.sort(key=_key_func)
        assert node.parent  # It should always default to the module
        for name, asname in node.names:
            if name == "*":
                try:
                    imported = node.do_import_module()
                except AstroidBuildingError:
                    continue
                for name in imported.public_names():
                    node.parent.set_local(name, node)
                    sort_locals(node.parent.scope().locals[name])  # type: ignore[arg-type]
            else:
                node.parent.set_local(asname or name, node)
                sort_locals(node.parent.scope().locals[asname or name])  # type: ignore[arg-type]
Referenced by _post_build().
delayed_assattr()
None astroid.builder.AstroidBuilder.delayed_assattr (self, nodes.AssignAttr node)
Visit a AssAttr node.
This adds name to locals and handle members definition.
Definition at line 235 of file builder.py.
    def delayed_assattr(self, node: nodes.AssignAttr) -> None:
        """Visit a AssAttr node.
        This adds name to locals and handle members definition.
        """
        from astroid import objects  # pylint: disable=import-outside-toplevel
        try:
            for inferred in node.expr.infer():
                if isinstance(inferred, util.UninferableBase):
                    continue
                try:
                    # pylint: disable=unidiomatic-typecheck # We want a narrow check on the
                    # parent type, not all of its subclasses
                    if type(inferred) in {bases.Instance, objects.ExceptionInstance}:
                        inferred = inferred._proxied
                        iattrs = inferred.instance_attrs
                        if not _can_assign_attr(inferred, node.attrname):
                            continue
                    elif isinstance(inferred, bases.Instance):
                        # Const, Tuple or other containers that inherit from
                        # `Instance`
                        continue
                    elif isinstance(inferred, (bases.Proxy, util.UninferableBase)):
                        continue
                    elif inferred.is_function:
                        iattrs = inferred.instance_attrs
                    else:
                        iattrs = inferred.locals
                except AttributeError:
                    # XXX log error
                    continue
                values = iattrs.setdefault(node.attrname, [])
                if node in values:
                    continue
                values.append(node)
        except InferenceError:
            pass
References astroid.builder._can_assign_attr().
Referenced by _post_build().
file_build()
nodes.Module astroid.builder.AstroidBuilder.file_build (self, str path, str | None modname = None)
Build astroid from a source code file (i.e. from an ast).
*path* is expected to be a python source file
Definition at line 109 of file builder.py.
    def file_build(self, path: str, modname: str | None = None) -> nodes.Module:
        """Build astroid from a source code file (i.e. from an ast).
        *path* is expected to be a python source file
        """
        try:
            stream, encoding, data = open_source_file(path)
        except OSError as exc:
            raise AstroidBuildingError(
                "Unable to load file {path}:\n{error}",
                modname=modname,
                path=path,
                error=exc,
            ) from exc
        except (SyntaxError, LookupError) as exc:
            raise AstroidSyntaxError(
                "Python 3 encoding specification error or unknown encoding:\n"
                "{error}",
                modname=modname,
                path=path,
                error=exc,
            ) from exc
        except UnicodeError as exc:  # wrong encoding
            # detect_encoding returns utf-8 if no encoding specified
            raise AstroidBuildingError(
                "Wrong or no encoding specified for {filename}.", filename=path
            ) from exc
        with stream:
            # get module name if necessary
            if modname is None:
                try:
                    modname = ".".join(modutils.modpath_from_file(path))
                except ImportError:
                    modname = os.path.splitext(os.path.basename(path))[0]
            # build astroid representation
            module, builder = self._data_build(data, modname, path)
            return self._post_build(module, builder, encoding)
References _data_build(), _post_build(), and astroid.builder.open_source_file().
Referenced by module_build().
module_build()
nodes.Module astroid.builder.AstroidBuilder.module_build (self, types.ModuleType module, str | None modname = None)
Build an astroid from a living module instance.
Definition at line 80 of file builder.py.
    ) -> nodes.Module:
        """Build an astroid from a living module instance."""
        node = None
        path = getattr(module, "__file__", None)
        loader = getattr(module, "__loader__", None)
        # Prefer the loader to get the source rather than assuming we have a
        # filesystem to read the source file from ourselves.
        if loader:
            modname = modname or module.__name__
            source = loader.get_source(modname)
            if source:
                node = self.string_build(source, modname, path=path)
        if node is None and path is not None:
            path_, ext = os.path.splitext(modutils._path_from_filename(path))
            if ext in {".py", ".pyc", ".pyo"} and os.path.exists(path_ + ".py"):
                node = self.file_build(path_ + ".py", modname)
        if node is None:
            # this is a built-in module
            # get a partial representation by introspection
            node = self.inspect_build(module, modname=modname, path=path)
            if self._apply_transforms:
                # We have to handle transformation by ourselves since the
                # rebuilder isn't called for builtin nodes
                node = self._manager.visit_transforms(node)
        assert isinstance(node, nodes.Module)
        return node
References _apply_transforms, astroid.raw_building.InspectBuilder._manager, file_build(), astroid.raw_building.InspectBuilder.inspect_build(), and string_build().
string_build()
nodes.Module astroid.builder.AstroidBuilder.string_build (self, str data, str modname = "", str | None path = None)
Build astroid from source code string.
Definition at line 147 of file builder.py.
    ) -> nodes.Module:
        """Build astroid from source code string."""
        module, builder = self._data_build(data, modname, path)
        module.file_bytes = data.encode("utf-8")
        return self._post_build(module, builder, "utf-8")
References _data_build(), and _post_build().
Referenced by module_build().
Member Data Documentation
_apply_transforms
astroid.builder.AstroidBuilder._apply_transforms = apply_transforms protected
Definition at line 76 of file builder.py.
Referenced by _post_build(), and module_build().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/astroid/builder.py