Read&Watch: django.template.backends.jinja2.Jinja2 Class Reference
django.template.backends.jinja2.Jinja2 Class Reference
Public Member Functions
__init__ (self, params)
from_string (self, template_code)
get_template (self, template_name)
template_context_processors (self)
Public Member Functions inherited from django.template.backends.base.BaseEngine
__init__ (self, params)
check (self, **kwargs)
app_dirname (self)
template_dirs (self)
iter_template_filenames (self, template_name)
Public Attributes
context_processors = options.pop("context_processors", [])
env = environment_cls(**options)
Public Attributes inherited from django.template.backends.base.BaseEngine
name = params.pop("NAME")
dirs = list(params.pop("DIRS"))
app_dirs = params.pop("APP_DIRS")
template_dirs
Detailed Description
Definition at line 14 of file jinja2.py.
Constructor & Destructor Documentation
__init__()
django.template.backends.jinja2.Jinja2.__init__ (self, params)
Definition at line 17 of file jinja2.py.
    def __init__(self, params):
        params = params.copy()
        options = params.pop("OPTIONS").copy()
        super().__init__(params)
        self.context_processors = options.pop("context_processors", [])
        environment = options.pop("environment", "jinja2.Environment")
        environment_cls = import_string(environment)
        if "loader" not in options:
            options["loader"] = jinja2.FileSystemLoader(self.template_dirs)
        options.setdefault("autoescape", True)
        options.setdefault("auto_reload", settings.DEBUG)
        options.setdefault(
            "undefined", jinja2.DebugUndefined if settings.DEBUG else jinja2.Undefined
        )
        self.env = environment_cls(**options)
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Function Documentation
from_string()
django.template.backends.jinja2.Jinja2.from_string (self, template_code)
Create and return a template for the given source code.
This method is optional.
Reimplemented from django.template.backends.base.BaseEngine.
Definition at line 37 of file jinja2.py.
    def from_string(self, template_code):
        return Template(self.env.from_string(template_code), self)
References env, and from_string().
Referenced by from_string().
get_template()
django.template.backends.jinja2.Jinja2.get_template (self, template_name)
Load and return a template for the given name.
Raise TemplateDoesNotExist if no such template exists.
Reimplemented from django.template.backends.base.BaseEngine.
Definition at line 40 of file jinja2.py.
    def get_template(self, template_name):
        try:
            return Template(self.env.get_template(template_name), self)
        except jinja2.TemplateNotFound as exc:
            raise TemplateDoesNotExist(exc.name, backend=self) from exc
        except jinja2.TemplateSyntaxError as exc:
            new = TemplateSyntaxError(exc.args)
            new.template_debug = get_exception_info(exc)
            raise new from exc
References env, django.template.backends.jinja2.get_exception_info(), and get_template().
Referenced by get_template(), django.template.engine.Engine.render_to_string(), and django.template.engine.Engine.select_template().
template_context_processors()
django.template.backends.jinja2.Jinja2.template_context_processors (self)
Definition at line 51 of file jinja2.py.
    def template_context_processors(self):
        return [import_string(path) for path in self.context_processors]
References context_processors.
Member Data Documentation
context_processors
django.template.backends.jinja2.Jinja2.context_processors = options.pop("context_processors", [])
Definition at line 22 of file jinja2.py.
Referenced by django.template.engine.Engine.__repr__(), template_context_processors(), and django.template.engine.Engine.template_context_processors().
env
django.template.backends.jinja2.Jinja2.env = environment_cls(**options)
Definition at line 35 of file jinja2.py.
Referenced by from_string(), and get_template().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/template/backends/jinja2.py