Read&Watch: django.utils.archive.BaseArchive Class Reference
django.utils.archive.BaseArchive Class Reference
Public Member Functions
split_leading_dir (self, path)
has_leading_dir (self, paths)
target_filename (self, to_path, name)
extract (self)
list (self)
Static Protected Member Functions
_copy_permissions (mode, filename)
Detailed Description
Base Archive class.  Implementations should inherit this class.
Definition at line 102 of file archive.py.
Member Function Documentation
_copy_permissions()
django.utils.archive.BaseArchive._copy_permissions (mode, filename) static protected
If the file in the archive has some permissions (this assumes a file
won't be writable/executable without being readable), apply those
permissions to the unarchived file.
Definition at line 108 of file archive.py.
    def _copy_permissions(mode, filename):
        """
        If the file in the archive has some permissions (this assumes a file
        won't be writable/executable without being readable), apply those
        permissions to the unarchived file.
        """
        if mode & stat.S_IROTH:
            os.chmod(filename, mode)
Referenced by django.utils.archive.TarArchive.extract(), and django.utils.archive.ZipArchive.extract().
extract()
django.utils.archive.BaseArchive.extract (self)
Reimplemented in django.utils.archive.TarArchive, and django.utils.archive.ZipArchive.
Definition at line 152 of file archive.py.
    def extract(self):
        raise NotImplementedError(
            "subclasses of BaseArchive must provide an extract() method"
        )
Referenced by pip._vendor.rich.traceback.Traceback.__init__(), tomlkit.parser.Parser._parse_bare_key(), tomlkit.parser.Parser._parse_comment_trail(), tomlkit.parser.Parser._parse_item(), tomlkit.parser.Parser._parse_key_value(), tomlkit.parser.Parser._parse_quoted_key(), tomlkit.parser.Parser._parse_string(), tomlkit.parser.Parser._parse_table(), tomlkit.parser.Parser._parse_value(), tomlkit.parser.Parser._peek_unicode(), and pip._vendor.rich.traceback.Traceback.from_exception().
has_leading_dir()
django.utils.archive.BaseArchive.has_leading_dir (self, paths)
Return True if all the paths have the same leading path name
(i.e., everything is in one subdirectory in an archive).
Definition at line 129 of file archive.py.
    def has_leading_dir(self, paths):
        """
        Return True if all the paths have the same leading path name
        (i.e., everything is in one subdirectory in an archive).
        """
        common_prefix = None
        for path in paths:
            prefix, rest = self.split_leading_dir(path)
            if not prefix:
                return False
            elif common_prefix is None:
                common_prefix = prefix
            elif prefix != common_prefix:
                return False
        return True
References split_leading_dir().
Referenced by django.utils.archive.TarArchive.extract(), and django.utils.archive.ZipArchive.extract().
list()
django.utils.archive.BaseArchive.list (self)
Reimplemented in django.utils.archive.TarArchive, and django.utils.archive.ZipArchive.
Definition at line 157 of file archive.py.
    def list(self):
        raise NotImplementedError(
            "subclasses of BaseArchive must provide a list() method"
        )
split_leading_dir()
django.utils.archive.BaseArchive.split_leading_dir (self, path)
Definition at line 117 of file archive.py.
    def split_leading_dir(self, path):
        path = str(path)
        path = path.lstrip("/").lstrip("\\")
        if "/" in path and (
            ("\\" in path and path.find("/") < path.find("\\")) or "\\" not in path
        ):
            return path.split("/", 1)
        elif "\\" in path:
            return path.split("\\", 1)
        else:
            return path, ""
Referenced by django.utils.archive.TarArchive.extract(), django.utils.archive.ZipArchive.extract(), and has_leading_dir().
target_filename()
django.utils.archive.BaseArchive.target_filename (self, to_path, name)
Definition at line 145 of file archive.py.
    def target_filename(self, to_path, name):
        target_path = os.path.abspath(to_path)
        filename = os.path.abspath(os.path.join(target_path, name))
        if not filename.startswith(target_path):
            raise SuspiciousOperation("Archive contains invalid path: '%s'" % name)
        return filename
Referenced by django.utils.archive.TarArchive.extract(), and django.utils.archive.ZipArchive.extract().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/utils/archive.py