Read&Watch: django.forms.renderers.Jinja2DivFormRenderer Class Reference
django.forms.renderers.Jinja2DivFormRenderer Class Reference
Public Member Functions
__init__ (self, *args, **kwargs)
Public Member Functions inherited from django.forms.renderers.Jinja2
backend (self)
Public Member Functions inherited from django.forms.renderers.EngineMixin
get_template (self, template_name)
engine (self)
Public Member Functions inherited from django.forms.renderers.BaseRenderer
get_template (self, template_name)
render (self, template_name, context, request=None)
Additional Inherited Members
Static Public Attributes inherited from django.forms.renderers.BaseRenderer
str form_template_name = "django/forms/div.html"
str formset_template_name = "django/forms/formsets/div.html"
str field_template_name = "django/forms/field.html"
Detailed Description
Load Jinja2 templates from the built-in widget templates in
django/forms/jinja2 and from apps' 'jinja2' directory.
Definition at line 88 of file renderers.py.
Constructor & Destructor Documentation
__init__()
django.forms.renderers.Jinja2DivFormRenderer.__init__ (self, * args, ** kwargs)
Definition at line 94 of file renderers.py.
    def __init__(self, *args, **kwargs):
        warnings.warn(
            "The Jinja2DivFormRenderer transitional form renderer is deprecated. Use "
            "Jinja2 instead.",
            RemovedInDjango60Warning,
        )
        super().__init__(*args, **kwargs)
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/forms/renderers.py