Read&Watch: isort.exceptions.AssignmentsFormatMismatch Class Reference
isort.exceptions.AssignmentsFormatMismatch Class Reference
Public Member Functions
__init__ (self, str code)
Public Member Functions inherited from isort.exceptions.ISortError
__reduce__ (self)
Public Attributes
code = code
Detailed Description
Raised when isort is told to sort assignments but the format of the assignment section
doesn't match isort's expectation.
Definition at line 140 of file exceptions.py.
Constructor & Destructor Documentation
__init__()
isort.exceptions.AssignmentsFormatMismatch.__init__ (self, str code)
Definition at line 145 of file exceptions.py.
    def __init__(self, code: str):
        super().__init__(
            "isort was told to sort a section of assignments, however the given code:\n\n"
            f"{code}\n\n"
            "Does not match isort's strict single line formatting requirement for assignment "
            "sorting:\n\n"
            "{variable_name} = {value}\n"
            "{variable_name2} = {value2}\n"
            "...\n\n"
        )
        self.code = code
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Data Documentation
code
isort.exceptions.AssignmentsFormatMismatch.code = code
Definition at line 155 of file exceptions.py.
Referenced by pip._vendor.rich.syntax.Syntax._get_syntax(), and pip._vendor.rich.syntax.Syntax._numbers_column_width().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/isort/exceptions.py