Read&Watch: pip._vendor.rich.progress.MofNCompleteColumn Class Reference
pip._vendor.rich.progress.MofNCompleteColumn Class Reference
Public Member Functions
__init__ (self, str separator="/", Optional[Column] table_column=None)
Text render (self, "Task" task)
Public Member Functions inherited from pip._vendor.rich.progress.ProgressColumn
None __init__ (self, Optional[Column] table_column=None)
Column get_table_column (self)
RenderableType __call__ (self, "Task" task)
Public Attributes
separator = separator
Additional Inherited Members
Static Public Attributes inherited from pip._vendor.rich.progress.ProgressColumn
Optional max_refresh = None
Protected Attributes inherited from pip._vendor.rich.progress.ProgressColumn
_table_column = table_column
dict _renderable_cache = {}
Optional[float] _update_time = None
Detailed Description
Renders completed count/total, e.g. '  10/1000'.
Best for bounded tasks with int quantities.
Space pads the completed count so that progress length does not change as task progresses
past powers of 10.
Args:
    separator (str, optional): Text to separate completed and total values. Defaults to "/".
Definition at line 826 of file progress.py.
Constructor & Destructor Documentation
__init__()
pip._vendor.rich.progress.MofNCompleteColumn.__init__ (self, str separator = "/", Optional[Column] table_column = None)
Definition at line 838 of file progress.py.
    def __init__(self, separator: str = "/", table_column: Optional[Column] = None):
        self.separator = separator
        super().__init__(table_column=table_column)
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
render()
Text pip._vendor.rich.progress.MofNCompleteColumn.render (self, "Task" task)
Show completed/total.
Reimplemented from pip._vendor.rich.progress.ProgressColumn.
Definition at line 842 of file progress.py.
    def render(self, task: "Task") -> Text:
        """Show completed/total."""
        completed = int(task.completed)
        total = int(task.total) if task.total is not None else "?"
        total_width = len(str(total))
        return Text(
            f"{completed:{total_width}d}{self.separator}{total}",
            style="progress.download",
        )
Referenced by pip._vendor.rich.spinner.Spinner.__rich_console__(), and pip._vendor.rich.spinner.Spinner.__rich_measure__().
Member Data Documentation
separator
pip._vendor.rich.progress.MofNCompleteColumn.separator = separator
Definition at line 839 of file progress.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/rich/progress.py