Read&Watch: astroid.interpreter.objectmodel.GeneratorModel Class Reference
astroid.interpreter.objectmodel.GeneratorModel Class Reference
Public Member Functions
__new__ (cls, *args, **kwargs)
attr___name__ (self)
attr___doc__ (self)
Public Member Functions inherited from astroid.interpreter.objectmodel.FunctionModel
attr___qualname__ (self)
attr___defaults__ (self)
attr___annotations__ (self)
attr___dict__ (self)
attr___kwdefaults__ (self)
attr___module__ (self)
attr___get__ (self)
attr___ne__ (self)
Public Member Functions inherited from astroid.interpreter.objectmodel.ObjectModel
__init__ (self)
__repr__ (self)
__call__ (self, instance)
__get__ (self, instance, cls=None)
bool __contains__ (self, name)
list[str] attributes (self)
lookup (self, name)
bases.BoundMethod attr___new__ (self)
bases.BoundMethod attr___init__ (self)
Public Member Functions inherited from astroid.interpreter.objectmodel.ContextManagerModel
bases.BoundMethod attr___enter__ (self)
bases.BoundMethod attr___exit__ (self)
Additional Inherited Members
Static Public Attributes inherited from astroid.interpreter.objectmodel.FunctionModel
attr___globals__ = attr___dict__
attr___subclasshook__ = attr___ne__
attr___str__ = attr___ne__
attr___sizeof__ = attr___ne__
attr___setattr___ = attr___ne__
attr___repr__ = attr___ne__
attr___reduce__ = attr___ne__
attr___reduce_ex__ = attr___ne__
attr___lt__ = attr___ne__
attr___eq__ = attr___ne__
attr___gt__ = attr___ne__
attr___format__ = attr___ne__
attr___delattr___ = attr___ne__
attr___getattribute__ = attr___ne__
attr___hash__ = attr___ne__
attr___dir__ = attr___ne__
attr___call__ = attr___ne__
attr___class__ = attr___ne__
attr___closure__ = attr___ne__
attr___code__ = attr___ne__
Protected Attributes inherited from astroid.interpreter.objectmodel.ObjectModel
_instance = None
Detailed Description
Definition at line 707 of file objectmodel.py.
Member Function Documentation
__new__()
astroid.interpreter.objectmodel.GeneratorModel.__new__ (cls, * args, ** kwargs)
Definition at line 708 of file objectmodel.py.
    def __new__(cls, *args, **kwargs):
        # Append the values from the GeneratorType unto this object.
        ret = super().__new__(cls, *args, **kwargs)
        generator = AstroidManager().builtins_module["generator"]
        for name, values in generator.locals.items():
            method = values[0]
            def patched(cls, meth=method):
                return meth
            setattr(type(ret), IMPL_PREFIX + name, property(patched))
        return ret
References __new__().
Referenced by __new__(), django.test.selenium.SeleniumTestCaseBase.__new__(), apscheduler.triggers.combining.BaseCombiningTrigger.__setstate__(), pip._vendor.rich.style.Style._add(), pip._vendor.rich.style.Style.clear_meta_and_links(), yaml.constructor.SafeConstructor.construct_yaml_object(), pip._vendor.rich.style.Style.copy(), pip._vendor.rich.style.Style.from_color(), pip._vendor.rich.json.JSON.from_data(), pip._vendor.rich.style.Style.from_meta(), yaml.constructor.FullConstructor.make_python_instance(), pip._vendor.rich.style.Style.update_link(), and pip._vendor.rich.style.Style.without_color().
attr___doc__()
astroid.interpreter.objectmodel.GeneratorModel.attr___doc__ (self)
Reimplemented from astroid.interpreter.objectmodel.FunctionModel.
Definition at line 729 of file objectmodel.py.
    def attr___doc__(self):
        return node_classes.Const(
            value=getattr(self._instance.parent.doc_node, "value", None),
            parent=self._instance,
        )
References astroid.interpreter.objectmodel.ObjectModel._instance.
attr___name__()
astroid.interpreter.objectmodel.GeneratorModel.attr___name__ (self)
Reimplemented from astroid.interpreter.objectmodel.FunctionModel.
Definition at line 723 of file objectmodel.py.
    def attr___name__(self):
        return node_classes.Const(
            value=self._instance.parent.name, parent=self._instance
        )
References astroid.interpreter.objectmodel.ObjectModel._instance.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/astroid/interpreter/objectmodel.py