Read&Watch: asgiref.local.Local Class Reference
asgiref.local.Local Class Reference
Public Member Functions
None __init__ (self, bool thread_critical=False)
__getattr__ (self, key)
__setattr__ (self, key, value)
__delattr__ (self, key)
Protected Member Functions
_lock_storage (self)
Protected Attributes
_thread_critical = thread_critical
_thread_lock = threading.RLock()
_storage
Detailed Description
Local storage for async tasks.
This is a namespace object (similar to `threading.local`) where data is
also local to the current async task (if there is one).
In async threads, local means in the same sense as the `contextvars`
module - i.e. a value set in an async frame will be visible:
- to other async code `await`-ed from this frame.
- to tasks spawned using `asyncio` utilities (`create_task`, `wait_for`,
  `gather` and probably others).
- to code scheduled in a sync thread using `sync_to_async`
In "sync" threads (a thread with no async event loop running), the
data is thread-local, but additionally shared with async code executed
via the `async_to_sync` utility, which schedules async code in a new thread
and copies context across to that thread.
If `thread_critical` is True, then the local will only be visible per-thread,
behaving exactly like `threading.local` if the thread is sync, and as
`contextvars` if the thread is async. This allows genuinely thread-sensitive
code (such as DB handles) to be kept stricly to their initial thread and
disable the sharing across `sync_to_async` and `async_to_sync` wrapped calls.
Unlike plain `contextvars` objects, this utility is threadsafe.
Definition at line 40 of file local.py.
Constructor & Destructor Documentation
__init__()
None asgiref.local.Local.__init__ (self, bool thread_critical = False)
Definition at line 68 of file local.py.
    def __init__(self, thread_critical: bool = False) -> None:
        self._thread_critical = thread_critical
        self._thread_lock = threading.RLock()
        self._storage: "Union[threading.local, _CVar]"
        if thread_critical:
            # Thread-local storage
            self._storage = threading.local()
        else:
            # Contextvar storage
            self._storage = _CVar()
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
__delattr__()
asgiref.local.Local.__delattr__ (self, key)
Definition at line 126 of file local.py.
    def __delattr__(self, key):
        with self._lock_storage() as storage:
            delattr(storage, key)
References _lock_storage().
__getattr__()
asgiref.local.Local.__getattr__ (self, key)
Definition at line 116 of file local.py.
    def __getattr__(self, key):
        with self._lock_storage() as storage:
            return getattr(storage, key)
References _lock_storage().
__setattr__()
asgiref.local.Local.__setattr__ (self, key, value)
Definition at line 120 of file local.py.
    def __setattr__(self, key, value):
        if key in ("_local", "_storage", "_thread_critical", "_thread_lock"):
            return super().__setattr__(key, value)
        with self._lock_storage() as storage:
            setattr(storage, key, value)
References __setattr__(), and _lock_storage().
Referenced by __setattr__().
_lock_storage()
asgiref.local.Local._lock_storage (self) protected
Definition at line 82 of file local.py.
    def _lock_storage(self):
        # Thread safe access to storage
        if self._thread_critical:
            try:
                # this is a test for are we in a async or sync
                # thread - will raise RuntimeError if there is
                # no current loop
                asyncio.get_running_loop()
            except RuntimeError:
                # We are in a sync thread, the storage is
                # just the plain thread local (i.e, "global within
                # this thread" - it doesn't matter where you are
                # in a call stack you see the same storage)
                yield self._storage
            else:
                # We are in an async thread - storage is still
                # local to this thread, but additionally should
                # behave like a context var (is only visible with
                # the same async call stack)
                # Ensure context exists in the current thread
                if not hasattr(self._storage, "cvar"):
                    self._storage.cvar = _CVar()
                # self._storage is a thread local, so the members
                # can't be accessed in another thread (we don't
                # need any locks)
                yield self._storage.cvar
        else:
            # Lock for thread_critical=False as other threads
            # can access the exact same storage object
            with self._thread_lock:
                yield self._storage
References _storage, _thread_critical, and _thread_lock.
Referenced by __delattr__(), __getattr__(), and __setattr__().
Member Data Documentation
_storage
asgiref.local.Local._storage protected
Definition at line 72 of file local.py.
Referenced by _lock_storage().
_thread_critical
asgiref.local.Local._thread_critical = thread_critical protected
Definition at line 69 of file local.py.
Referenced by _lock_storage().
_thread_lock
asgiref.local.Local._thread_lock = threading.RLock() protected
Definition at line 70 of file local.py.
Referenced by responses.RequestsMock._find_match(), and _lock_storage().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/asgiref/local.py