Read&Watch: django.db.models.expressions.DatabaseDefault Class Reference
django.db.models.expressions.DatabaseDefault Class Reference
Public Member Functions
__init__ (self, expression, output_field=None)
get_source_expressions (self)
set_source_expressions (self, exprs)
resolve_expression (self, query=None, allow_joins=True, reuse=None, summarize=False, for_save=False)
as_sql (self, compiler, connection)
Public Member Functions inherited from django.db.models.expressions.Expression
identity (self)
__eq__ (self, other)
__hash__ (self)
Public Member Functions inherited from django.db.models.expressions.BaseExpression
__init__ (self, output_field=None)
__getstate__ (self)
get_db_converters (self, connection)
contains_aggregate (self)
contains_over_clause (self)
contains_column_references (self)
contains_subquery (self)
conditional (self)
field (self)
output_field (self)
convert_value (self)
get_lookup (self, lookup)
get_transform (self, name)
relabeled_clone (self, change_map)
replace_expressions (self, replacements)
get_refs (self)
copy (self)
prefix_references (self, prefix)
get_group_by_cols (self)
get_source_fields (self)
asc (self, **kwargs)
desc (self, **kwargs)
reverse_ordering (self)
flatten (self)
select_format (self, compiler, sql, params)
get_expression_for_validation (self)
Public Member Functions inherited from django.db.models.expressions.Combinable
__neg__ (self)
OPERATORS #.
__add__ (self, other)
__sub__ (self, other)
__mul__ (self, other)
__truediv__ (self, other)
__mod__ (self, other)
__pow__ (self, other)
__and__ (self, other)
bitand (self, other)
bitleftshift (self, other)
bitrightshift (self, other)
__xor__ (self, other)
bitxor (self, other)
__or__ (self, other)
bitor (self, other)
__radd__ (self, other)
__rsub__ (self, other)
__rmul__ (self, other)
__rtruediv__ (self, other)
__rmod__ (self, other)
__rpow__ (self, other)
__rand__ (self, other)
__ror__ (self, other)
__rxor__ (self, other)
__invert__ (self)
Public Attributes
expression = expression
Public Attributes inherited from django.db.models.expressions.Expression
identity
Public Attributes inherited from django.db.models.expressions.BaseExpression
output_field = output_field
contains_aggregate
Additional Inherited Members
Static Public Attributes inherited from django.db.models.expressions.BaseExpression
empty_result_set_value = NotImplemented
bool is_summary = False
bool filterable = True
bool window_compatible = False
bool allowed_default = False
bool constraint_validation_compatible = True
Static Public Attributes inherited from django.db.models.expressions.Combinable
str ADD = "+"
str SUB = "-"
str MUL = "*"
str DIV = "/"
str POW = "^"
str MOD = "%%"
str BITAND = "&"
str BITOR = "|"
str BITLEFTSHIFT = "<<"
str BITRIGHTSHIFT = ">>"
str BITXOR = "#"
Protected Member Functions inherited from django.db.models.expressions.Expression
_constructor_signature (cls)
Protected Member Functions inherited from django.db.models.expressions.BaseExpression
_parse_expressions (self, *expressions)
_output_field_or_none (self)
_resolve_output_field (self)
Protected Member Functions inherited from django.db.models.expressions.Combinable
_combine (self, other, connector, reversed)
Static Protected Member Functions inherited from django.db.models.expressions.BaseExpression
_convert_value_noop (value, expression, connection)
Static Protected Attributes inherited from django.db.models.expressions.BaseExpression
bool _output_field_resolved_to_none = False
Detailed Description
Expression to use DEFAULT keyword during insert otherwise the underlying expression.
Definition at line 1252 of file expressions.py.
Constructor & Destructor Documentation
__init__()
django.db.models.expressions.DatabaseDefault.__init__ (self, expression, output_field = None)
Definition at line 1257 of file expressions.py.
    def __init__(self, expression, output_field=None):
        super().__init__(output_field)
        self.expression = expression
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
as_sql()
django.db.models.expressions.DatabaseDefault.as_sql (self, compiler, connection)
Responsible for returning a (sql, [params]) tuple to be included
in the current query.
Different backends can provide their own implementation, by
providing an `as_{vendor}` method and patching the Expression:
```
def override_as_sql(self, compiler, connection):
    # custom logic
    return super().as_sql(compiler, connection)
setattr(Expression, 'as_' + connection.vendor, override_as_sql)
```
Arguments:
 * compiler: the query compiler responsible for generating the query.
   Must have a compile method, returning a (sql, [params]) tuple.
   Calling compiler(value) will return a quoted `value`.
 * connection: the database connection used for the current query.
Return: (sql, params)
  Where `sql` is a string containing ordered sql parameters to be
  replaced with the elements of the list `params`.
Reimplemented from django.db.models.expressions.BaseExpression.
Definition at line 1285 of file expressions.py.
    def as_sql(self, compiler, connection):
        if not connection.features.supports_default_keyword_in_insert:
            return compiler.compile(self.expression)
        return "DEFAULT", []
References expression.
Referenced by django.db.models.expressions.SQLiteNumericMixin.as_sqlite(), django.db.backends.mysql.compiler.SQLCompiler.as_subquery_condition(), django.db.models.sql.compiler.SQLCompiler.as_subquery_condition(), django.db.models.sql.compiler.SQLCompiler.execute_sql(), and django.db.models.sql.compiler.SQLInsertCompiler.execute_sql().
get_source_expressions()
django.db.models.expressions.DatabaseDefault.get_source_expressions (self)
Reimplemented from django.db.models.expressions.BaseExpression.
Definition at line 1261 of file expressions.py.
    def get_source_expressions(self):
        return [self.expression]
References expression.
Referenced by django.contrib.gis.db.models.functions.OracleToleranceMixin.as_oracle(), django.db.models.functions.mixins.FixDurationInputMixin.as_oracle(), and django.db.models.functions.mixins.FixDecimalInputMixin.as_postgresql().
resolve_expression()
django.db.models.expressions.DatabaseDefault.resolve_expression (self, query = None, allow_joins = True, reuse = None, summarize = False, for_save = False)
Provide the chance to do any preprocessing or validation before being
added to the query.
Arguments:
 * query: the backend query implementation
 * allow_joins: boolean allowing or denying use of joins
   in this query
 * reuse: a set of reusable joins for multijoins
 * summarize: a terminal aggregate clause
 * for_save: whether this expression about to be used in a save or update
Return: an Expression to be added to the query.
Reimplemented from django.db.models.expressions.BaseExpression.
Definition at line 1267 of file expressions.py.
    ):
        resolved_expression = self.expression.resolve_expression(
            query=query,
            allow_joins=allow_joins,
            reuse=reuse,
            summarize=summarize,
            for_save=for_save,
        )
        # Defaults used outside an INSERT context should resolve to their
        # underlying expression.
        if not for_save:
            return resolved_expression
        return DatabaseDefault(
            resolved_expression, output_field=self._output_field_or_none
        )
References django.db.models.expressions.BaseExpression._output_field_or_none(), expression, and resolve_expression().
Referenced by django.template.defaulttags.RegroupNode.render(), and resolve_expression().
set_source_expressions()
django.db.models.expressions.DatabaseDefault.set_source_expressions (self, exprs)
Reimplemented from django.db.models.expressions.BaseExpression.
Definition at line 1264 of file expressions.py.
    def set_source_expressions(self, exprs):
        (self.expression,) = exprs
References expression.
Member Data Documentation
expression
django.db.models.expressions.DatabaseDefault.expression = expression
Definition at line 1259 of file expressions.py.
Referenced by django.db.models.expressions.NegatedExpression.__invert__(), django.db.models.expressions.ExpressionWrapper.__repr__(), django.db.models.expressions.OrderBy.__repr__(), django.db.models.expressions.ExpressionWrapper.allowed_default(), django.db.models.expressions.OrderBy.as_oracle(), as_sql(), django.db.models.expressions.ExpressionWrapper.as_sql(), django.db.models.expressions.OrderBy.as_sql(), django.db.models.fields.generated.GeneratedField.deconstruct(), django.db.models.fields.generated.GeneratedField.generated_sql(), django.db.models.expressions.ExpressionWrapper.get_group_by_cols(), get_source_expressions(), django.db.models.expressions.ExpressionWrapper.get_source_expressions(), django.db.models.expressions.OrderBy.get_source_expressions(), django.template.smartif.IfParser.parse(), resolve_expression(), django.template.defaulttags.RegroupNode.resolve_expression(), django.db.models.expressions.NegatedExpression.select_format(), set_source_expressions(), django.db.models.expressions.ExpressionWrapper.set_source_expressions(), and django.db.models.expressions.OrderBy.set_source_expressions().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/db/models/expressions.py