Read&Watch: pip._internal.metadata.importlib._envs.Environment Class Reference
pip._internal.metadata.importlib._envs.Environment Class Reference
Public Member Functions
None __init__ (self, Sequence[str] paths)
BaseEnvironment default (cls)
BaseEnvironment from_paths (cls, Optional[List[str]] paths)
Optional[BaseDistribution] get_distribution (self, str name)
Public Member Functions inherited from pip._internal.metadata.base.BaseEnvironment
Iterator[BaseDistribution] iter_all_distributions (self)
Iterator[BaseDistribution] iter_installed_distributions (self, bool local_only=True, Container[str] skip=stdlib_pkgs, bool include_editables=True, bool editables_only=False, bool user_only=False)
Protected Member Functions
Iterator[BaseDistribution] _iter_distributions (self)
Protected Attributes
_paths = paths
Detailed Description
Definition at line 158 of file _envs.py.
Constructor & Destructor Documentation
__init__()
None pip._internal.metadata.importlib._envs.Environment.__init__ (self, Sequence[str] paths)
Definition at line 159 of file _envs.py.
    def __init__(self, paths: Sequence[str]) -> None:
        self._paths = paths
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
_iter_distributions()
Iterator[BaseDistribution] pip._internal.metadata.importlib._envs.Environment._iter_distributions (self) protected
Iterate through installed distributions.
This function should be implemented by subclass, but never called
directly. Use the public ``iter_distribution()`` instead, which
implements additional logic to make sure the distributions are valid.
Reimplemented from pip._internal.metadata.base.BaseEnvironment.
Definition at line 172 of file _envs.py.
    def _iter_distributions(self) -> Iterator[BaseDistribution]:
        finder = _DistributionFinder()
        for location in self._paths:
            yield from finder.find(location)
            for dist in finder.find_eggs(location):
                _emit_egg_deprecation(dist.location)
                yield dist
            # This must go last because that's how pkg_resources tie-breaks.
            yield from finder.find_linked(location)
References pip._internal.metadata.importlib._envs._emit_egg_deprecation(), and _paths.
default()
BaseEnvironment pip._internal.metadata.importlib._envs.Environment.default (cls)
Reimplemented from pip._internal.metadata.base.BaseEnvironment.
Definition at line 163 of file _envs.py.
    def default(cls) -> BaseEnvironment:
        return cls(sys.path)
from_paths()
BaseEnvironment pip._internal.metadata.importlib._envs.Environment.from_paths (cls, Optional[List[str]] paths)
Reimplemented from pip._internal.metadata.base.BaseEnvironment.
Definition at line 167 of file _envs.py.
    def from_paths(cls, paths: Optional[List[str]]) -> BaseEnvironment:
        if paths is None:
            return cls(sys.path)
        return cls(paths)
get_distribution()
Optional[BaseDistribution] pip._internal.metadata.importlib._envs.Environment.get_distribution (self, str name)
Given a requirement name, return the installed distributions.
The name may not be normalized. The implementation must canonicalize
it for lookup.
Reimplemented from pip._internal.metadata.base.BaseEnvironment.
Definition at line 182 of file _envs.py.
    def get_distribution(self, name: str) -> Optional[BaseDistribution]:
        canonical_name = canonicalize_name(name)
        matches = (
            distribution
            for distribution in self.iter_all_distributions()
            if distribution.canonical_name == canonical_name
        )
        return next(matches, None)
References pip._internal.metadata.base.BaseEnvironment.iter_all_distributions().
Referenced by pip._vendor.distlib.database.DistributionPath.get_file_path().
Member Data Documentation
_paths
pip._internal.metadata.importlib._envs.Environment._paths = paths protected
Definition at line 160 of file _envs.py.
Referenced by pip._internal.req.req_uninstall.UninstallPathSet._allowed_to_proceed(), _iter_distributions(), pip._internal.req.req_uninstall.UninstallPathSet.add(), and pip._internal.req.req_uninstall.UninstallPathSet.remove().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_internal/metadata/importlib/_envs.py