Read&Watch: responses.registries.FirstMatchRegistry Class Reference
responses.registries.FirstMatchRegistry Class Reference
Public Member Functions
None __init__ (self)
List["BaseResponse"] registered (self)
None reset (self)
Tuple[Optional["BaseResponse"], List[str]] find (self, "PreparedRequest" request)
"BaseResponse" add (self, "BaseResponse" response)
List["BaseResponse"] remove (self, "BaseResponse" response)
"BaseResponse" replace (self, "BaseResponse" response)
Public Attributes
registered
Protected Attributes
list _responses = []
Detailed Description
Definition at line 14 of file registries.py.
Constructor & Destructor Documentation
__init__()
None responses.registries.FirstMatchRegistry.__init__ (self)
Definition at line 15 of file registries.py.
    def __init__(self) -> None:
        self._responses: List["BaseResponse"] = []
Member Function Documentation
add()
"BaseResponse" responses.registries.FirstMatchRegistry.add (self, "BaseResponse" response)
Definition at line 49 of file registries.py.
    def add(self, response: "BaseResponse") -> "BaseResponse":
        if any(response is resp for resp in self.registered):
            # if user adds multiple responses that reference the same instance.
            # do a comparison by memory allocation address.
            # see https://github.com/getsentry/responses/issues/479
            response = copy.deepcopy(response)
        self.registered.append(response)
        return response
References registered.
Referenced by urllib3._collections.HTTPHeaderDict.extend().
find()
Tuple[Optional["BaseResponse"], List[str]] responses.registries.FirstMatchRegistry.find (self, "PreparedRequest" request)
Reimplemented in responses.registries.OrderedRegistry.
Definition at line 25 of file registries.py.
    ) -> Tuple[Optional["BaseResponse"], List[str]]:
        found = None
        found_match = None
        match_failed_reasons = []
        for i, response in enumerate(self.registered):
            match_result, reason = response.matches(request)
            if match_result:
                if found is None:
                    found = i
                    found_match = response
                else:
                    if self.registered[found].call_count > 0:
                        # that assumes that some responses were added between calls
                        self.registered.pop(found)
                        found_match = response
                        break
                    # Multiple matches found.  Remove & return the first response.
                    return self.registered.pop(found), match_failed_reasons
            else:
                match_failed_reasons.append(reason)
        return found_match, match_failed_reasons
registered()
List["BaseResponse"] responses.registries.FirstMatchRegistry.registered (self)
Definition at line 19 of file registries.py.
    def registered(self) -> List["BaseResponse"]:
        return self._responses
References _responses.
remove()
List["BaseResponse"] responses.registries.FirstMatchRegistry.remove (self, "BaseResponse" response)
Definition at line 59 of file registries.py.
    def remove(self, response: "BaseResponse") -> List["BaseResponse"]:
        removed_responses = []
        while response in self.registered:
            self.registered.remove(response)
            removed_responses.append(response)
        return removed_responses
References registered, and responses.remove.
Referenced by tomlkit.container.Container.__delitem__(), tomlkit.items.AbstractTable.__delitem__(), and tomlkit.container.Container._replace_at().
replace()
"BaseResponse" responses.registries.FirstMatchRegistry.replace (self, "BaseResponse" response)
Definition at line 66 of file registries.py.
    def replace(self, response: "BaseResponse") -> "BaseResponse":
        try:
            index = self.registered.index(response)
        except ValueError:
            raise ValueError(f"Response is not registered for URL {response.url}")
        self.registered[index] = response
        return response
References registered.
reset()
None responses.registries.FirstMatchRegistry.reset (self)
Definition at line 22 of file registries.py.
    def reset(self) -> None:
        self._responses = []
References _responses.
Referenced by django.utils.html.MLStripper.__init__(), and pylint.extensions.mccabe.PathGraphingAstVisitor._subgraph().
Member Data Documentation
_responses
list responses.registries.FirstMatchRegistry._responses = [] protected
Definition at line 16 of file registries.py.
Referenced by registered(), and reset().
registered
responses.registries.FirstMatchRegistry.registered
Definition at line 31 of file registries.py.
Referenced by responses.RequestsMock._on_request(), responses.RequestsMock._set_registry(), add(), remove(), replace(), and responses.RequestsMock.stop().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/responses/registries.py