Read&Watch: pylint.checkers.base.docstring_checker.DocStringChecker Class Reference
pylint.checkers.base.docstring_checker.DocStringChecker Class Reference
Public Member Functions
None open (self)
None visit_module (self, nodes.Module node)
None visit_classdef (self, nodes.ClassDef node)
None visit_functiondef (self, nodes.FunctionDef node)
Public Member Functions inherited from pylint.checkers.base_checker.BaseChecker
None __init__ (self, PyLinter linter)
bool __gt__ (self, Any other)
bool __eq__ (self, object other)
int __hash__ (self)
str __repr__ (self)
str __str__ (self)
str get_full_documentation (self, dict[str, MessageDefinitionTuple] msgs, Iterable[tuple[str, OptionDict, Any]] options, Sequence[tuple[str, str, ReportsCallable]] reports, str|None doc=None, str|None module=None, bool show_options=True)
None add_message (self, str msgid, int|None line=None, nodes.NodeNG|None node=None, Any args=None, Confidence|None confidence=None, int|None col_offset=None, int|None end_lineno=None, int|None end_col_offset=None)
None check_consistency (self)
MessageDefinition create_message_definition_from_tuple (self, str msgid, MessageDefinitionTuple msg_tuple)
list[MessageDefinition] messages (self)
None close (self)
Any get_map_data (self)
None reduce_map_data (self, PyLinter linter, list[Any] data)
Public Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
None __init__ (self, _ArgumentsManager arguments_manager)
Static Public Attributes
None visit_asyncfunctiondef = visit_functiondef
Static Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
str name = ""
dict msgs = {}
tuple reports = ()
bool enabled = True
Static Public Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
tuple options = ()
dict option_groups_descs = {}
Protected Member Functions
None _check_docstring (self, Literal["class", "function", "method", "module"] node_type, nodes.Module|nodes.ClassDef|nodes.FunctionDef node, bool report_missing=True, interfaces.Confidence confidence=interfaces.HIGH)
Protected Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
Any _option_value (self, str opt)
Iterator[ tuple[str, list[tuple[str, OptionDict, Any]]]|tuple[None, dict[str, list[tuple[str, OptionDict, Any]]]]] _options_by_section (self)
Iterator[tuple[str, OptionDict, Any]] _options_and_values (self, Options|None options=None)
Additional Inherited Members
Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
linter = linter
messages
Protected Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
_arguments_manager = arguments_manager
Detailed Description
Definition at line 45 of file docstring_checker.py.
Member Function Documentation
_check_docstring()
None pylint.checkers.base.docstring_checker.DocStringChecker._check_docstring (self, Literal["class", "function", "method", "module"] node_type, nodes.Module | nodes.ClassDef | nodes.FunctionDef node, bool report_missing = True, interfaces.Confidence confidence = interfaces.HIGH) protected
Check if the node has a non-empty docstring.
Definition at line 152 of file docstring_checker.py.
    ) -> None:
        """Check if the node has a non-empty docstring."""
        docstring = node.doc_node.value if node.doc_node else None
        if docstring is None:
            docstring = _infer_dunder_doc_attribute(node)
        if docstring is None:
            if not report_missing:
                return
            lines = utils.get_node_last_lineno(node) - node.lineno
            if node_type == "module" and not lines:
                # If the module does not have a body, there's no reason
                # to require a docstring.
                return
            max_lines = self.linter.config.docstring_min_length
            if node_type != "module" and max_lines > -1 and lines < max_lines:
                return
            if node_type == "class":
                self.linter.stats.undocumented["klass"] += 1
            else:
                self.linter.stats.undocumented[node_type] += 1
            if (
                node.body
                and isinstance(node.body[0], nodes.Expr)
                and isinstance(node.body[0].value, nodes.Call)
            ):
                # Most likely a string with a format call. Let's see.
                func = utils.safe_infer(node.body[0].value.func)
                if isinstance(func, astroid.BoundMethod) and isinstance(
                    func.bound, astroid.Instance
                ):
                    # Strings.
                    if func.bound.name in {"str", "unicode", "bytes"}:
                        return
            if node_type == "module":
                message = "missing-module-docstring"
            elif node_type == "class":
                message = "missing-class-docstring"
            else:
                message = "missing-function-docstring"
            self.add_message(message, node=node, confidence=confidence)
        elif not docstring.strip():
            if node_type == "class":
                self.linter.stats.undocumented["klass"] += 1
            else:
                self.linter.stats.undocumented[node_type] += 1
            self.add_message(
                "empty-docstring", node=node, args=(node_type,), confidence=confidence
            )
References pylint.checkers.base.docstring_checker._infer_dunder_doc_attribute(), pylint.checkers.base_checker.BaseChecker.add_message(), and pylint.checkers.base_checker.BaseChecker.linter.
Referenced by visit_classdef(), pylint.checkers.spelling.SpellingChecker.visit_classdef(), pylint.extensions.docstyle.DocStringStyleChecker.visit_classdef(), visit_functiondef(), pylint.checkers.spelling.SpellingChecker.visit_functiondef(), pylint.extensions.docstyle.DocStringStyleChecker.visit_functiondef(), visit_module(), pylint.checkers.spelling.SpellingChecker.visit_module(), and pylint.extensions.docstyle.DocStringStyleChecker.visit_module().
open()
None pylint.checkers.base.docstring_checker.DocStringChecker.open (self)
Called before visiting project (i.e. set of modules).
Reimplemented from pylint.checkers.base_checker.BaseChecker.
Definition at line 103 of file docstring_checker.py.
    def open(self) -> None:
        self.linter.stats.reset_undocumented()
References pylint.checkers.base_checker.BaseChecker.linter.
Referenced by django.contrib.staticfiles.storage.HashedFilesMixin.hashed_name().
visit_classdef()
None pylint.checkers.base.docstring_checker.DocStringChecker.visit_classdef (self, nodes.ClassDef node)
Definition at line 111 of file docstring_checker.py.
    def visit_classdef(self, node: nodes.ClassDef) -> None:
        if self.linter.config.no_docstring_rgx.match(node.name) is None:
            self._check_docstring("class", node)
References _check_docstring(), and pylint.checkers.base_checker.BaseChecker.linter.
Referenced by pylint.pyreverse.inspector.Linker.visit_assignname(), and pylint.checkers.exceptions.ExceptionRaiseLeafVisitor.visit_instance().
visit_functiondef()
None pylint.checkers.base.docstring_checker.DocStringChecker.visit_functiondef (self, nodes.FunctionDef node)
Definition at line 116 of file docstring_checker.py.
    def visit_functiondef(self, node: nodes.FunctionDef) -> None:
        if self.linter.config.no_docstring_rgx.match(node.name) is None:
            ftype = "method" if node.is_method() else "function"
            if (
                is_property_setter(node)
                or is_property_deleter(node)
                or is_overload_stub(node)
            ):
                return
            if isinstance(node.parent.frame(), nodes.ClassDef):
                overridden = False
                confidence = (
                    interfaces.INFERENCE
                    if utils.has_known_bases(node.parent.frame())
                    else interfaces.INFERENCE_FAILURE
                )
                # check if node is from a method overridden by its ancestor
                for ancestor in node.parent.frame().ancestors():
                    if ancestor.qname() == "builtins.object":
                        continue
                    if node.name in ancestor and isinstance(
                        ancestor[node.name], nodes.FunctionDef
                    ):
                        overridden = True
                        break
                self._check_docstring(
                    ftype, node, report_missing=not overridden, confidence=confidence  # type: ignore[arg-type]
                )
            elif isinstance(node.parent.frame(), nodes.Module):
                self._check_docstring(ftype, node)  # type: ignore[arg-type]
            else:
                return
References _check_docstring(), and pylint.checkers.base_checker.BaseChecker.linter.
Referenced by pylint.pyreverse.inspector.Linker.visit_assignname().
visit_module()
None pylint.checkers.base.docstring_checker.DocStringChecker.visit_module (self, nodes.Module node)
Definition at line 107 of file docstring_checker.py.
    def visit_module(self, node: nodes.Module) -> None:
        self._check_docstring("module", node)
References _check_docstring().
Referenced by pylint.pyreverse.inspector.Linker.visit_assignname().
Member Data Documentation
visit_asyncfunctiondef
None pylint.checkers.base.docstring_checker.DocStringChecker.visit_asyncfunctiondef = visit_functiondef static
Definition at line 150 of file docstring_checker.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pylint/checkers/base/docstring_checker.py