Read&Watch: django.contrib.auth.forms.UsernameField Class Reference
django.contrib.auth.forms.UsernameField Class Reference
Public Member Functions
to_python (self, value)
widget_attrs (self, widget)
Public Member Functions inherited from django.forms.fields.CharField
__init__ (self, *, max_length=None, min_length=None, strip=True, empty_value="", **kwargs)
Public Member Functions inherited from django.forms.fields.Field
__init__ (self, *, required=True, widget=None, label=None, initial=None, help_text="", error_messages=None, show_hidden_initial=False, validators=(), localize=False, disabled=False, label_suffix=None, template_name=None)
prepare_value (self, value)
validate (self, value)
run_validators (self, value)
clean (self, value)
bound_data (self, data, initial)
has_changed (self, initial, data)
get_bound_field (self, form, field_name)
__deepcopy__ (self, memo)
Additional Inherited Members
Public Attributes inherited from django.forms.fields.CharField
max_length = max_length
min_length = min_length
strip = strip
empty_value = empty_value
Public Attributes inherited from django.forms.fields.Field
required
label
initial = required, label, initial
show_hidden_initial = show_hidden_initial
help_text = help_text
disabled = disabled
label_suffix = label_suffix
localize = localize
error_messages = messages
list validators = [*self.default_validators, *validators]
template_name = template_name
Static Public Attributes inherited from django.forms.fields.Field
widget = TextInput
tuple hidden_widget
list default_validators = []
dict default_error_messages
empty_values = list(validators.EMPTY_VALUES)
Protected Member Functions inherited from django.forms.fields.Field
_clean_bound_field (self, bf)
Detailed Description
Definition at line 78 of file forms.py.
Member Function Documentation
to_python()
django.contrib.auth.forms.UsernameField.to_python (self, value)
Return a string.
Reimplemented from django.forms.fields.CharField.
Definition at line 79 of file forms.py.
    def to_python(self, value):
        value = super().to_python(value)
        if self.max_length is not None and len(value) > self.max_length:
            # Normalization can increase the string length (e.g.
            # "ﬀ" -> "ff", "½" -> "1⁄2") but cannot reduce it, so there is no
            # point in normalizing invalid data. Moreover, Unicode
            # normalization is very slow on Windows and can be a DoS attack
            # vector.
            return value
        return unicodedata.normalize("NFKC", value)
References to_python().
Referenced by django.db.models.fields.Field.clean(), django.forms.fields.Field.clean(), django.db.models.fields.Field.formfield(), django.db.models.fields.DecimalField.get_db_prep_save(), django.db.models.fields.UUIDField.get_db_prep_value(), django.db.models.fields.BooleanField.get_prep_value(), django.db.models.fields.CharField.get_prep_value(), django.db.models.fields.DateField.get_prep_value(), django.db.models.fields.DateTimeField.get_prep_value(), django.db.models.fields.DecimalField.get_prep_value(), django.db.models.fields.TextField.get_prep_value(), django.db.models.fields.TimeField.get_prep_value(), django.db.models.fields.UUIDField.get_prep_value(), django.contrib.gis.forms.fields.GeometryField.has_changed(), django.contrib.postgres.forms.array.SimpleArrayField.has_changed(), django.contrib.postgres.forms.array.SplitArrayField.has_changed(), django.contrib.postgres.forms.hstore.HStoreField.has_changed(), django.forms.fields.Field.has_changed(), django.forms.fields.JSONField.has_changed(), and to_python().
widget_attrs()
django.contrib.auth.forms.UsernameField.widget_attrs (self, widget)
Given a Widget instance (*not* a Widget class), return a dictionary of
any HTML attributes that should be added to the Widget, based on this
Field.
Reimplemented from django.forms.fields.CharField.
Definition at line 90 of file forms.py.
    def widget_attrs(self, widget):
        return {
            **super().widget_attrs(widget),
            "autocapitalize": "none",
            "autocomplete": "username",
        }
References widget_attrs().
Referenced by widget_attrs().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/auth/forms.py