Read&Watch: pip._internal.index.collector.CacheablePageContent Class Reference
pip._internal.index.collector.CacheablePageContent Class Reference
Public Member Functions
None __init__ (self, "IndexContent" page)
bool __eq__ (self, object other)
int __hash__ (self)
Public Attributes
page = page
Detailed Description
Definition at line 187 of file collector.py.
Constructor & Destructor Documentation
__init__()
None pip._internal.index.collector.CacheablePageContent.__init__ (self, "IndexContent" page)
Definition at line 188 of file collector.py.
    def __init__(self, page: "IndexContent") -> None:
        assert page.cache_link_parsing
        self.page = page
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
__eq__()
bool pip._internal.index.collector.CacheablePageContent.__eq__ (self, object other)
Definition at line 192 of file collector.py.
    def __eq__(self, other: object) -> bool:
        return isinstance(other, type(self)) and self.page.url == other.page.url
References page.
Referenced by pip._vendor.distlib.version.Version.__ge__(), pip._vendor.distlib.version.Version.__gt__(), pip._vendor.distlib.version.Version.__le__(), dotenv.variables.Atom.__ne__(), pip._vendor.distlib.version.Matcher.__ne__(), pip._vendor.distlib.version.Version.__ne__(), pip._vendor.msgpack.ext.Timestamp.__ne__(), pip._vendor.urllib3._collections.HTTPHeaderDict.__ne__(), responses.BaseResponse.__ne__(), and urllib3._collections.HTTPHeaderDict.__ne__().
__hash__()
int pip._internal.index.collector.CacheablePageContent.__hash__ (self)
Definition at line 195 of file collector.py.
    def __hash__(self) -> int:
        return hash(self.page.url)
References page.
Referenced by pip._vendor.rich.style.Style.__eq__(), and pip._vendor.rich.style.Style.__ne__().
Member Data Documentation
page
pip._internal.index.collector.CacheablePageContent.page = page
Definition at line 190 of file collector.py.
Referenced by __eq__(), __hash__(), and django.core.paginator.Paginator.get_page().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_internal/index/collector.py