Read&Watch: django.contrib.admindocs.views.TemplateFilterIndexView Class Reference
django.contrib.admindocs.views.TemplateFilterIndexView Class Reference
Public Member Functions
get_context_data (self, **kwargs)
Public Member Functions inherited from django.contrib.admindocs.views.BaseAdminDocsView
dispatch (self, request, *args, **kwargs)
Public Member Functions inherited from django.views.generic.base.TemplateView
get (self, request, *args, **kwargs)
Public Member Functions inherited from django.views.generic.base.TemplateResponseMixin
render_to_response (self, context, **response_kwargs)
get_template_names (self)
Public Member Functions inherited from django.views.generic.base.View
__init__ (self, **kwargs)
view_is_async (cls)
as_view (cls, **initkwargs)
setup (self, request, *args, **kwargs)
http_method_not_allowed (self, request, *args, **kwargs)
options (self, request, *args, **kwargs)
Additional Inherited Members
Public Attributes inherited from django.views.generic.base.View
view_is_async = cls.dispatch.__annotations__
head = self.get
request = request
args = args
kwargs = kwargs
Static Public Attributes inherited from django.views.generic.base.TemplateResponseMixin
template_name = None
template_engine = None
response_class = TemplateResponse
content_type = None
Static Public Attributes inherited from django.views.generic.base.ContextMixin
extra_context = None
Static Public Attributes inherited from django.views.generic.base.View
list http_method_names
Protected Member Functions inherited from django.views.generic.base.View
_allowed_methods (self)
Detailed Description
Definition at line 102 of file views.py.
Member Function Documentation
get_context_data()
django.contrib.admindocs.views.TemplateFilterIndexView.get_context_data (self, ** kwargs)
Reimplemented from django.contrib.admindocs.views.BaseAdminDocsView.
Definition at line 105 of file views.py.
    def get_context_data(self, **kwargs):
        filters = []
        try:
            engine = Engine.get_default()
        except ImproperlyConfigured:
            # Non-trivial TEMPLATES settings aren't supported (#24125).
            pass
        else:
            app_libs = sorted(engine.template_libraries.items())
            builtin_libs = [("", lib) for lib in engine.template_builtins]
            for module_name, library in builtin_libs + app_libs:
                for filter_name, filter_func in library.filters.items():
                    title, body, metadata = utils.parse_docstring(filter_func.__doc__)
                    title = title and utils.parse_rst(
                        title, "filter", _("filter:") + filter_name
                    )
                    body = body and utils.parse_rst(
                        body, "filter", _("filter:") + filter_name
                    )
                    for key in metadata:
                        metadata[key] = utils.parse_rst(
                            metadata[key], "filter", _("filter:") + filter_name
                        )
                    tag_library = module_name.split(".")[-1]
                    filters.append(
{
                            "name": filter_name,
                            "title": title,
                            "body": body,
                            "meta": metadata,
                            "library": tag_library,
                        }
                    )
        return super().get_context_data(**{**kwargs, "filters": filters})
References get_context_data().
Referenced by django.views.generic.edit.FormMixin.form_invalid(), django.views.generic.base.TemplateView.get(), django.views.generic.edit.ProcessFormView.get(), get_context_data(), and django.contrib.syndication.views.Feed.get_feed().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/admindocs/views.py