Read&Watch: django.core.mail.backends.locmem.EmailBackend Class Reference
django.core.mail.backends.locmem.EmailBackend Class Reference
Public Member Functions
__init__ (self, *args, **kwargs)
send_messages (self, messages)
Public Member Functions inherited from django.core.mail.backends.base.BaseEmailBackend
__init__ (self, fail_silently=False, **kwargs)
open (self)
close (self)
__enter__ (self)
__exit__ (self, exc_type, exc_value, traceback)
Additional Inherited Members
Public Attributes inherited from django.core.mail.backends.base.BaseEmailBackend
fail_silently = fail_silently
Detailed Description
An email backend for use during test sessions.
The test connection stores email messages in a dummy outbox,
rather than sending them out on the wire.
The dummy outbox is accessible through the outbox instance attribute.
Definition at line 11 of file locmem.py.
Constructor & Destructor Documentation
__init__()
django.core.mail.backends.locmem.EmailBackend.__init__ (self, * args, ** kwargs)
Definition at line 21 of file locmem.py.
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if not hasattr(mail, "outbox"):
            mail.outbox = []
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Function Documentation
send_messages()
django.core.mail.backends.locmem.EmailBackend.send_messages (self, messages)
Redirect messages to the dummy outbox
Reimplemented from django.core.mail.backends.base.BaseEmailBackend.
Definition at line 26 of file locmem.py.
    def send_messages(self, messages):
        """Redirect messages to the dummy outbox"""
        msg_count = 0
        for message in messages:  # .message() triggers header validation
            message.message()
            mail.outbox.append(copy.deepcopy(message))
            msg_count += 1
        return msg_count
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/core/mail/backends/locmem.py