Read&Watch: general.models.RecentlyViewed Class Reference
general.models.RecentlyViewed Class Reference
Classes
class Meta
Static Public Attributes
user = models.ForeignKey(User, on_delete=models.CASCADE)
content_type = models.CharField(max_length=10, choices=[('book', 'Book'), ('movie', 'Movie'), ('show', 'Show')])
item_id = models.CharField(max_length=20)
title = models.CharField(max_length=255)
cover_image_url = models.URLField(blank=True, null=True)
viewed_at = models.DateTimeField(default=now)
Static Public Attributes inherited from django.db.models.base.Model
alters_data
Additional Inherited Members
Public Member Functions inherited from django.db.models.base.Model
__init__ (self, *args, **kwargs)
from_db (cls, db, field_names, values)
__repr__ (self)
__str__ (self)
__eq__ (self, other)
__hash__ (self)
__reduce__ (self)
__getstate__ (self)
__setstate__ (self, state)
get_deferred_fields (self)
refresh_from_db (self, using=None, fields=None, from_queryset=None)
arefresh_from_db (self, using=None, fields=None, from_queryset=None)
serializable_value (self, field_name)
save (self, *args, force_insert=False, force_update=False, using=None, update_fields=None)
asave (self, *args, force_insert=False, force_update=False, using=None, update_fields=None)
save_base (self, raw=False, force_insert=False, force_update=False, using=None, update_fields=None)
delete (self, using=None, keep_parents=False)
adelete (self, using=None, keep_parents=False)
prepare_database_save (self, field)
clean (self)
validate_unique (self, exclude=None)
date_error_message (self, lookup_type, field_name, unique_for)
unique_error_message (self, model_class, unique_check)
get_constraints (self)
validate_constraints (self, exclude=None)
full_clean (self, exclude=None, validate_unique=True, validate_constraints=True)
clean_fields (self, exclude=None)
check (cls, **kwargs)
Public Member Functions inherited from django.db.models.utils.AltersData
__init_subclass__ (cls, **kwargs)
Public Member Functions inherited from django.db.models.base.ModelBase
__new__ (cls, name, bases, attrs, **kwargs)
add_to_class (cls, name, value)
Public Attributes inherited from django.db.models.base.Model
refresh_from_db
save
delete
Public Attributes inherited from django.db.models.base.ModelBase
get_next_in_order
get_previous_in_order
Protected Member Functions inherited from django.db.models.base.Model
_get_pk_val (self, meta=None)
_set_pk_val (self, value)
_parse_params (self, *args, method_name, **kwargs)
_validate_force_insert (cls, force_insert)
_save_parents (self, cls, using, update_fields, force_insert, updated_parents=None)
_save_table (self, raw=False, cls=None, force_insert=False, force_update=False, using=None, update_fields=None)
_do_update (self, base_qs, using, pk_val, values, update_fields, forced_update)
_do_insert (self, manager, using, fields, returning_fields, raw)
_prepare_related_fields_for_save (self, operation_name, fields=None)
_get_FIELD_display (self, field)
_get_next_or_previous_by_FIELD (self, field, is_next, **kwargs)
_get_next_or_previous_in_order (self, is_next)
_get_field_expression_map (self, meta, exclude=None)
_get_unique_checks (self, exclude=None, include_meta_constraints=False)
_perform_unique_checks (self, unique_checks)
_perform_date_checks (self, date_checks)
_check_default_pk (cls)
_check_db_table_comment (cls, databases)
_check_swappable (cls)
_check_model (cls)
_check_managers (cls, **kwargs)
_check_fields (cls, **kwargs)
_check_m2m_through_same_relationship (cls)
_check_id_field (cls)
_check_field_name_clashes (cls)
_check_column_name_clashes (cls)
_check_model_name_db_lookup_clashes (cls)
_check_property_name_related_field_accessor_clashes (cls)
_check_single_primary_key (cls)
_check_unique_together (cls)
_check_indexes (cls, databases)
_check_local_fields (cls, fields, option)
_check_ordering (cls)
_check_long_column_names (cls, databases)
_get_expr_references (cls, expr)
_check_constraints (cls, databases)
Protected Member Functions inherited from django.db.models.base.ModelBase
_prepare (cls)
_base_manager (cls)
_default_manager (cls)
Protected Attributes inherited from django.db.models.base.Model
_state = ModelState()
dict _prefetched_objects_cache = {}
tuple _order
Properties inherited from django.db.models.base.Model
pk = property(_get_pk_val, _set_pk_val)
Detailed Description
@class RecentlyViewed
@brief A model that stores recently viewed media items by a user.
This model keeps track of media items (book, movie, or show) that a user has recently viewed,
including the item's title, content type, cover image URL, and the timestamp of when it was viewed.
@attribute user The user who viewed the media item (ForeignKey to User model).
@attribute content_type The type of the media item (Book, Movie, or Show).
@attribute item_id The unique identifier for the media item.
@attribute title The title of the media item.
@attribute cover_image_url The URL of the media item's cover image (optional).
@attribute viewed_at The timestamp when the media item was viewed.
Definition at line 32 of file models.py.
Member Data Documentation
content_type
general.models.RecentlyViewed.content_type = models.CharField(max_length=10, choices=[('book', 'Book'), ('movie', 'Movie'), ('show', 'Show')]) static
Definition at line 48 of file models.py.
cover_image_url
general.models.RecentlyViewed.cover_image_url = models.URLField(blank=True, null=True) static
Definition at line 51 of file models.py.
item_id
general.models.RecentlyViewed.item_id = models.CharField(max_length=20) static
Definition at line 49 of file models.py.
title
general.models.RecentlyViewed.title = models.CharField(max_length=255) static
Definition at line 50 of file models.py.
Referenced by general.models.MediaItem.__str__().
user
general.models.RecentlyViewed.user = models.ForeignKey(User, on_delete=models.CASCADE) static
Definition at line 47 of file models.py.
Referenced by movie.tests.AddOrUpdateMovieTest.test_add_new_movie(), TVshow.tests.ShowDetailTest.test_add_to_recently_viewed(), movie.tests.MovieModelTest.test_create_movie_successfully(), TVshow.tests.TVshowModelTest.test_default_status(), movie.tests.MovieModelTest.test_default_values(), movie.tests.MovieModelTest.test_foreign_key_cascade_delete(), movie.tests.MovieModelTest.test_invalid_status_choice(), movie.tests.MovieModelTest.test_last_updated_field(), movie.tests.MovieDetailTest.test_movie_not_in_database_but_in_api(), movie.tests.MovieSearchTest.test_recently_viewed_movies_display(), movie.tests.MovieModelTest.test_str_representation(), movie.tests.MovieModelTest.test_unique_together_constraint(), TVshow.tests.TVshowModelTest.test_unique_together_constraint(), movie.tests.AddOrUpdateMovieTest.test_update_existing_movie_status(), and TVshow.tests.AddOrUpdateShowTest.test_update_show_status().
viewed_at
general.models.RecentlyViewed.viewed_at = models.DateTimeField(default=now) static
Definition at line 52 of file models.py.
The documentation for this class was generated from the following file:
project/library/general/models.py