Read&Watch: isort.exceptions.UnsupportedSettings Class Reference
isort.exceptions.UnsupportedSettings Class Reference
Public Member Functions
__init__ (self, Dict[str, Dict[str, str]] unsupported_settings)
Public Member Functions inherited from isort.exceptions.ISortError
__reduce__ (self)
Public Attributes
unsupported_settings = unsupported_settings
Static Protected Member Functions
str _format_option (str name, Any value, str source)
Detailed Description
Raised when settings are passed into isort (either from config, CLI, or runtime)
that it doesn't support.
Definition at line 158 of file exceptions.py.
Constructor & Destructor Documentation
__init__()
isort.exceptions.UnsupportedSettings.__init__ (self, Dict[str, Dict[str, str]] unsupported_settings)
Definition at line 167 of file exceptions.py.
    def __init__(self, unsupported_settings: Dict[str, Dict[str, str]]):
        errors = "\n".join(
            self._format_option(name, **option) for name, option in unsupported_settings.items()
        )
        super().__init__(
            "isort was provided settings that it doesn't support:\n\n"
            f"{errors}\n\n"
            "For a complete and up-to-date listing of supported settings see: "
            "https://pycqa.github.io/isort/docs/configuration/options.\n"
        )
        self.unsupported_settings = unsupported_settings
References __init__(), and _format_option().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Function Documentation
_format_option()
str isort.exceptions.UnsupportedSettings._format_option (str name, Any value, str source) static protected
Definition at line 164 of file exceptions.py.
    def _format_option(name: str, value: Any, source: str) -> str:
        return f"\t- {name} = {value}  (source: '{source}')"
Referenced by __init__().
Member Data Documentation
unsupported_settings
isort.exceptions.UnsupportedSettings.unsupported_settings = unsupported_settings
Definition at line 178 of file exceptions.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/isort/exceptions.py