Read&Watch: astroid.nodes._base_nodes.MultiLineBlockNode Class Reference
astroid.nodes._base_nodes.MultiLineBlockNode Class Reference
Protected Member Functions
_multi_line_blocks (self)
_get_return_nodes_skip_functions (self)
_get_yield_nodes_skip_functions (self)
_get_yield_nodes_skip_lambdas (self)
list[nodes.Assign] _assign_nodes_in_scope (self)
Protected Member Functions inherited from astroid.nodes.node_ng.NodeNG
int _fixed_source_line (self)
_get_name_nodes (self)
_infer_name (self, frame, name)
Generator[InferenceResult, None, InferenceErrorInfo|None] _infer (self, InferenceContext|None context=None, **Any kwargs)
Protected Attributes
_multi_line_blocks
Static Protected Attributes
tuple _multi_line_block_fields = ()
Static Protected Attributes inherited from astroid.nodes.node_ng.NodeNG
tuple _astroid_fields = ()
tuple _other_fields = ()
tuple _other_other_fields = ()
InferFn _explicit_inference = None
Additional Inherited Members
Public Member Functions inherited from astroid.nodes.node_ng.NodeNG
None __init__ (self, int|None lineno, int|None col_offset, NodeNG|None parent, *, int|None end_lineno, int|None end_col_offset)
Generator[InferenceResult] infer (self, InferenceContext|None context=None, **Any kwargs)
str repr_name (self)
str __str__ (self)
str __repr__ (self)
str accept (self, AsStringVisitor visitor)
Iterator[NodeNG] get_children (self)
NodeNG|None last_child (self)
Iterator[NodeNG] node_ancestors (self)
bool parent_of (self, node)
_base_nodes.Statement statement (self, *, Literal[None, True] future=None)
nodes.FunctionDef|nodes.Module|nodes.ClassDef|nodes.Lambda frame (self, *, Literal[None, True] future=None)
nodes.LocalsDictNodeNG scope (self)
nodes.Module root (self)
child_sequence (self, child)
locate_child (self, child)
next_sibling (self)
previous_sibling (self)
int fromlineno (self)
int tolineno (self)
tuple[int, int] block_range (self, int lineno)
None set_local (self, str name, NodeNG stmt)
Iterator[_NodesT] nodes_of_class (self, type[_NodesT] klass, SkipKlassT skip_klass=...)
Iterator[_NodesT]|Iterator[_NodesT2] nodes_of_class (self, tuple[type[_NodesT], type[_NodesT2]] klass, SkipKlassT skip_klass=...)
Iterator[_NodesT]|Iterator[_NodesT2]|Iterator[_NodesT3] nodes_of_class (self, tuple[type[_NodesT], type[_NodesT2], type[_NodesT3]] klass, SkipKlassT skip_klass=...)
Iterator[_NodesT] nodes_of_class (self, tuple[type[_NodesT],...] klass, SkipKlassT skip_klass=...)
Iterator[_NodesT]|Iterator[_NodesT2]|Iterator[_NodesT3] nodes_of_class (self,(type[_NodesT]|tuple[type[_NodesT], type[_NodesT2]]|tuple[type[_NodesT], type[_NodesT2], type[_NodesT3]]|tuple[type[_NodesT],...]) klass, SkipKlassT skip_klass=None)
inferred (self)
instantiate_class (self)
bool has_base (self, node)
bool callable (self)
bool eq (self, value)
str as_string (self)
str repr_tree (self, ids=False, include_linenos=False, ast_state=False, indent=" ", max_depth=0, max_width=80)
bool_value (self, InferenceContext|None context=None)
op_precedence (self)
bool op_left_associative (self)
Public Attributes inherited from astroid.nodes.node_ng.NodeNG
lineno = lineno
col_offset = col_offset
parent = parent
end_lineno = end_lineno
end_col_offset = end_col_offset
Position|None position = None
Static Public Attributes inherited from astroid.nodes.node_ng.NodeNG
ClassVar is_statement = False
tuple optional_assign
ClassVar is_function = False
ClassVar is_lambda = False
Detailed Description
Base node for multi-line blocks, e.g. For and FunctionDef.
Note that this does not apply to every node with a `body` field.
For instance, an If node has a multi-line body, but the body of an
IfExpr is not multi-line, and hence cannot contain Return nodes,
Assign nodes, etc.
Definition at line 192 of file _base_nodes.py.
Member Function Documentation
_assign_nodes_in_scope()
list[nodes.Assign] astroid.nodes._base_nodes.MultiLineBlockNode._assign_nodes_in_scope (self) protected
Reimplemented from astroid.nodes.node_ng.NodeNG.
Definition at line 229 of file _base_nodes.py.
    def _assign_nodes_in_scope(self) -> list[nodes.Assign]:
        children_assign_nodes = (
            child_node._assign_nodes_in_scope
            for block in self._multi_line_blocks
            for child_node in block
        )
        return list(itertools.chain.from_iterable(children_assign_nodes))
References _multi_line_blocks.
_get_return_nodes_skip_functions()
astroid.nodes._base_nodes.MultiLineBlockNode._get_return_nodes_skip_functions (self) protected
Reimplemented from astroid.nodes.node_ng.NodeNG.
Definition at line 207 of file _base_nodes.py.
    def _get_return_nodes_skip_functions(self):
        for block in self._multi_line_blocks:
            for child_node in block:
                if child_node.is_function:
                    continue
                yield from child_node._get_return_nodes_skip_functions()
Referenced by astroid.nodes.scoped_nodes.scoped_nodes.FunctionDef.infer_call_result().
_get_yield_nodes_skip_functions()
astroid.nodes._base_nodes.MultiLineBlockNode._get_yield_nodes_skip_functions (self) protected
Reimplemented from astroid.nodes.node_ng.NodeNG.
Reimplemented in astroid.nodes.node_classes.If, and astroid.nodes.node_classes.While.
Definition at line 214 of file _base_nodes.py.
    def _get_yield_nodes_skip_functions(self):
        for block in self._multi_line_blocks:
            for child_node in block:
                if child_node.is_function:
                    continue
                yield from child_node._get_yield_nodes_skip_functions()
References _multi_line_blocks.
Referenced by astroid.nodes.scoped_nodes.scoped_nodes.FunctionDef.is_generator().
_get_yield_nodes_skip_lambdas()
astroid.nodes._base_nodes.MultiLineBlockNode._get_yield_nodes_skip_lambdas (self) protected
Reimplemented from astroid.nodes.node_ng.NodeNG.
Reimplemented in astroid.nodes.node_classes.If, and astroid.nodes.node_classes.While.
Definition at line 221 of file _base_nodes.py.
    def _get_yield_nodes_skip_lambdas(self):
        for block in self._multi_line_blocks:
            for child_node in block:
                if child_node.is_lambda:
                    continue
                yield from child_node._get_yield_nodes_skip_lambdas()
References _multi_line_blocks.
Referenced by astroid.nodes.scoped_nodes.scoped_nodes.FunctionDef.is_generator().
_multi_line_blocks()
astroid.nodes._base_nodes.MultiLineBlockNode._multi_line_blocks (self) protected
Definition at line 204 of file _base_nodes.py.
    def _multi_line_blocks(self):
        return tuple(getattr(self, field) for field in self._multi_line_block_fields)
References _multi_line_block_fields.
Member Data Documentation
_multi_line_block_fields
astroid.nodes._base_nodes.MultiLineBlockNode._multi_line_block_fields = () static protected
Definition at line 201 of file _base_nodes.py.
Referenced by _multi_line_blocks().
_multi_line_blocks
astroid.nodes._base_nodes.MultiLineBlockNode._multi_line_blocks protected
Definition at line 208 of file _base_nodes.py.
Referenced by _assign_nodes_in_scope(), _get_yield_nodes_skip_functions(), and _get_yield_nodes_skip_lambdas().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/astroid/nodes/_base_nodes.py