Read&Watch: pip._vendor.pygments.formatters.latex.LatexFormatter Class Reference
pip._vendor.pygments.formatters.latex.LatexFormatter Class Reference
Public Member Functions
__init__ (self, **options)
get_style_defs (self, arg='')
format_unencoded (self, tokensource, outfile)
Public Member Functions inherited from pip._vendor.pygments.formatter.Formatter
__init__ (self, **options)
format (self, tokensource, outfile)
__class_getitem__ (cls, name)
Public Attributes
nowrap = get_bool_opt(options, 'nowrap', False)
docclass = options.get('docclass', 'article')
preamble = options.get('preamble', '')
linenos = get_bool_opt(options, 'linenos', False)
linenostart = abs(get_int_opt(options, 'linenostart', 1))
linenostep = abs(get_int_opt(options, 'linenostep', 1))
verboptions = options.get('verboptions', '')
nobackground = get_bool_opt(options, 'nobackground', False)
commandprefix = options.get('commandprefix', 'PY')
texcomments = get_bool_opt(options, 'texcomments', False)
mathescape = get_bool_opt(options, 'mathescape', False)
str escapeinside = options.get('escapeinside', '')
left = self.escapeinside[0]
right = self.escapeinside[1]
envname = options.get('envname', 'Verbatim')
Public Attributes inherited from pip._vendor.pygments.formatter.Formatter
style = _lookup_style(options.get('style', 'default'))
full = get_bool_opt(options, 'full', False)
title = options.get('title', '')
str encoding = options.get('encoding', None) or None
options = options
Protected Member Functions
_create_stylesheet (self)
Additional Inherited Members
Static Public Attributes inherited from pip._vendor.pygments.formatter.Formatter
name = None
list aliases = []
list filenames = []
bool unicodeoutput = True
Detailed Description
Format tokens as LaTeX code. This needs the `fancyvrb` and `color`
standard packages.
Without the `full` option, code is formatted as one ``Verbatim``
environment, like this:
.. sourcecode:: latex
    \begin{Verbatim}[commandchars=\\\{\}]
    \PY{k}{def }\PY{n+nf}{foo}(\PY{n}{bar}):
        \PY{k}{pass}
    \end{Verbatim}
Wrapping can be disabled using the `nowrap` option.
The special command used here (``\PY``) and all the other macros it needs
are output by the `get_style_defs` method.
With the `full` option, a complete LaTeX document is output, including
the command definitions in the preamble.
The `get_style_defs()` method of a `LatexFormatter` returns a string
containing ``\def`` commands defining the macros needed inside the
``Verbatim`` environments.
Additional options accepted:
`nowrap`
    If set to ``True``, don't wrap the tokens at all, not even inside a
    ``\begin{Verbatim}`` environment. This disables most other options
    (default: ``False``).
`style`
    The style to use, can be a string or a Style subclass (default:
    ``'default'``).
`full`
    Tells the formatter to output a "full" document, i.e. a complete
    self-contained document (default: ``False``).
`title`
    If `full` is true, the title that should be used to caption the
    document (default: ``''``).
`docclass`
    If the `full` option is enabled, this is the document class to use
    (default: ``'article'``).
`preamble`
    If the `full` option is enabled, this can be further preamble commands,
    e.g. ``\usepackage`` (default: ``''``).
`linenos`
    If set to ``True``, output line numbers (default: ``False``).
`linenostart`
    The line number for the first line (default: ``1``).
`linenostep`
    If set to a number n > 1, only every nth line number is printed.
`verboptions`
    Additional options given to the Verbatim environment (see the *fancyvrb*
    docs for possible values) (default: ``''``).
`commandprefix`
    The LaTeX commands used to produce colored output are constructed
    using this prefix and some letters (default: ``'PY'``).
    .. versionadded:: 0.7
    .. versionchanged:: 0.10
       The default is now ``'PY'`` instead of ``'C'``.
`texcomments`
    If set to ``True``, enables LaTeX comment lines.  That is, LaTex markup
    in comment tokens is not escaped so that LaTeX can render it (default:
    ``False``).
    .. versionadded:: 1.2
`mathescape`
    If set to ``True``, enables LaTeX math mode escape in comments. That
    is, ``'$...$'`` inside a comment will trigger math mode (default:
    ``False``).
    .. versionadded:: 1.2
`escapeinside`
    If set to a string of length 2, enables escaping to LaTeX. Text
    delimited by these 2 characters is read as LaTeX code and
    typeset accordingly. It has no effect in string literals. It has
    no effect in comments if `texcomments` or `mathescape` is
    set. (default: ``''``).
    .. versionadded:: 2.0
`envname`
    Allows you to pick an alternative environment name replacing Verbatim.
    The alternate environment still has to support Verbatim's option syntax.
    (default: ``'Verbatim'``).
    .. versionadded:: 2.0
Definition at line 147 of file latex.py.
Constructor & Destructor Documentation
__init__()
pip._vendor.pygments.formatters.latex.LatexFormatter.__init__ (self, ** options)
Definition at line 256 of file latex.py.
    def __init__(self, **options):
        Formatter.__init__(self, **options)
        self.nowrap = get_bool_opt(options, 'nowrap', False)
        self.docclass = options.get('docclass', 'article')
        self.preamble = options.get('preamble', '')
        self.linenos = get_bool_opt(options, 'linenos', False)
        self.linenostart = abs(get_int_opt(options, 'linenostart', 1))
        self.linenostep = abs(get_int_opt(options, 'linenostep', 1))
        self.verboptions = options.get('verboptions', '')
        self.nobackground = get_bool_opt(options, 'nobackground', False)
        self.commandprefix = options.get('commandprefix', 'PY')
        self.texcomments = get_bool_opt(options, 'texcomments', False)
        self.mathescape = get_bool_opt(options, 'mathescape', False)
        self.escapeinside = options.get('escapeinside', '')
        if len(self.escapeinside) == 2:
            self.left = self.escapeinside[0]
            self.right = self.escapeinside[1]
        else:
            self.escapeinside = ''
        self.envname = options.get('envname', 'Verbatim')
        self._create_stylesheet()
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
_create_stylesheet()
pip._vendor.pygments.formatters.latex.LatexFormatter._create_stylesheet (self) protected
Definition at line 279 of file latex.py.
    def _create_stylesheet(self):
        t2n = self.ttype2name = {Token: ''}
        c2d = self.cmd2def = {}
        cp = self.commandprefix
        def rgbcolor(col):
            if col:
                return ','.join(['%.2f' % (int(col[i] + col[i + 1], 16) / 255.0)
                                 for i in (0, 2, 4)])
            else:
                return '1,1,1'
        for ttype, ndef in self.style:
            name = _get_ttype_name(ttype)
            cmndef = ''
            if ndef['bold']:
                cmndef += r'\let\$$@bf=\textbf'
            if ndef['italic']:
                cmndef += r'\let\$$@it=\textit'
            if ndef['underline']:
                cmndef += r'\let\$$@ul=\underline'
            if ndef['roman']:
                cmndef += r'\let\$$@ff=\textrm'
            if ndef['sans']:
                cmndef += r'\let\$$@ff=\textsf'
            if ndef['mono']:
                cmndef += r'\let\$$@ff=\textsf'
            if ndef['color']:
                cmndef += (r'\def\$$@tc##1{{\textcolor[rgb]{{{}}}{{##1}}}}'.format(rgbcolor(ndef['color'])))
            if ndef['border']:
                cmndef += (r'\def\$$@bc##1{{{{\setlength{{\fboxsep}}{{\string -\fboxrule}}'
                           r'\fcolorbox[rgb]{{{}}}{{{}}}{{\strut ##1}}}}}}'.format(rgbcolor(ndef['border']),
                            rgbcolor(ndef['bgcolor'])))
            elif ndef['bgcolor']:
                cmndef += (r'\def\$$@bc##1{{{{\setlength{{\fboxsep}}{{0pt}}'
                           r'\colorbox[rgb]{{{}}}{{\strut ##1}}}}}}'.format(rgbcolor(ndef['bgcolor'])))
            if cmndef == '':
                continue
            cmndef = cmndef.replace('$$', cp)
            t2n[ttype] = name
            c2d[name] = cmndef
References commandprefix.
format_unencoded()
pip._vendor.pygments.formatters.latex.LatexFormatter.format_unencoded (self, tokensource, outfile)
Definition at line 333 of file latex.py.
    def format_unencoded(self, tokensource, outfile):
        # TODO: add support for background colors
        t2n = self.ttype2name
        cp = self.commandprefix
        if self.full:
            realoutfile = outfile
            outfile = StringIO()
        if not self.nowrap:
            outfile.write('\\begin{' + self.envname + '}[commandchars=\\\\\\{\\}')
            if self.linenos:
                start, step = self.linenostart, self.linenostep
                outfile.write(',numbers=left' +
                              (start and ',firstnumber=%d' % start or '') +
                              (step and ',stepnumber=%d' % step or ''))
            if self.mathescape or self.texcomments or self.escapeinside:
                outfile.write(',codes={\\catcode`\\$=3\\catcode`\\^=7'
                              '\\catcode`\\_=8\\relax}')
            if self.verboptions:
                outfile.write(',' + self.verboptions)
            outfile.write(']\n')
        for ttype, value in tokensource:
            if ttype in Token.Comment:
                if self.texcomments:
                    # Try to guess comment starting lexeme and escape it ...
                    start = value[0:1]
                    for i in range(1, len(value)):
                        if start[0] != value[i]:
                            break
                        start += value[i]
                    value = value[len(start):]
                    start = escape_tex(start, cp)
                    # ... but do not escape inside comment.
                    value = start + value
                elif self.mathescape:
                    # Only escape parts not inside a math environment.
                    parts = value.split('$')
                    in_math = False
                    for i, part in enumerate(parts):
                        if not in_math:
                            parts[i] = escape_tex(part, cp)
                        in_math = not in_math
                    value = '$'.join(parts)
                elif self.escapeinside:
                    text = value
                    value = ''
                    while text:
                        a, sep1, text = text.partition(self.left)
                        if sep1:
                            b, sep2, text = text.partition(self.right)
                            if sep2:
                                value += escape_tex(a, cp) + b
                            else:
                                value += escape_tex(a + sep1 + b, cp)
                        else:
                            value += escape_tex(a, cp)
                else:
                    value = escape_tex(value, cp)
            elif ttype not in Token.Escape:
                value = escape_tex(value, cp)
            styles = []
            while ttype is not Token:
                try:
                    styles.append(t2n[ttype])
                except KeyError:
                    # not in current style
                    styles.append(_get_ttype_name(ttype))
                ttype = ttype.parent
            styleval = '+'.join(reversed(styles))
            if styleval:
                spl = value.split('\n')
                for line in spl[:-1]:
                    if line:
                        outfile.write(f"\\{cp}{{{styleval}}}{{{line}}}")
                    outfile.write('\n')
                if spl[-1]:
                    outfile.write(f"\\{cp}{{{styleval}}}{{{spl[-1]}}}")
            else:
                outfile.write(value)
        if not self.nowrap:
            outfile.write('\\end{' + self.envname + '}\n')
        if self.full:
            encoding = self.encoding or 'utf8'
            # map known existings encodings from LaTeX distribution
            encoding = {
                'utf_8': 'utf8',
                'latin_1': 'latin1',
                'iso_8859_1': 'latin1',
            }.get(encoding.replace('-', '_'), encoding)
            realoutfile.write(DOC_TEMPLATE %
                dict(docclass  = self.docclass,
                     preamble  = self.preamble,
                     title     = self.title,
                     encoding  = encoding,
                     styledefs = self.get_style_defs(),
                     code      = outfile.getvalue()))
References commandprefix.
Referenced by pip._vendor.pygments.formatter.Formatter.format().
get_style_defs()
pip._vendor.pygments.formatters.latex.LatexFormatter.get_style_defs (self, arg = '')
Return the command sequences needed to define the commands
used to format text in the verbatim environment. ``arg`` is ignored.
Reimplemented from pip._vendor.pygments.formatter.Formatter.
Definition at line 321 of file latex.py.
    def get_style_defs(self, arg=''):
        """
        Return the command sequences needed to define the commands
        used to format text in the verbatim environment. ``arg`` is ignored.
        """
        cp = self.commandprefix
        styles = []
        for name, definition in self.cmd2def.items():
            styles.append(rf'\@namedef{{{cp}@tok@{name}}}{{{definition}}}')
        return STYLE_TEMPLATE % {'cp': self.commandprefix,
                                 'styles': '\n'.join(styles)}
References commandprefix.
Member Data Documentation
commandprefix
pip._vendor.pygments.formatters.latex.LatexFormatter.commandprefix = options.get('commandprefix', 'PY')
Definition at line 266 of file latex.py.
Referenced by _create_stylesheet(), format_unencoded(), and get_style_defs().
docclass
pip._vendor.pygments.formatters.latex.LatexFormatter.docclass = options.get('docclass', 'article')
Definition at line 259 of file latex.py.
envname
pip._vendor.pygments.formatters.latex.LatexFormatter.envname = options.get('envname', 'Verbatim')
Definition at line 275 of file latex.py.
escapeinside
pip._vendor.pygments.formatters.latex.LatexFormatter.escapeinside = options.get('escapeinside', '')
Definition at line 269 of file latex.py.
left
pip._vendor.pygments.formatters.latex.LatexFormatter.left = self.escapeinside[0]
Definition at line 271 of file latex.py.
Referenced by pip._vendor.rich.padding.Padding.__rich_console__(), pip._vendor.rich.padding.Padding.__rich_measure__(), and pip._vendor.pygments.formatters.latex.LatexEmbeddedLexer._find_escape_tokens().
linenos
pip._vendor.pygments.formatters.latex.LatexFormatter.linenos = get_bool_opt(options, 'linenos', False)
Definition at line 261 of file latex.py.
Referenced by pip._vendor.pygments.formatters.rtf.RtfFormatter._create_color_mapping(), pip._vendor.pygments.formatters.terminal.TerminalFormatter.format_unencoded(), and pip._vendor.pygments.formatters.terminal256.Terminal256Formatter.format_unencoded().
linenostart
pip._vendor.pygments.formatters.latex.LatexFormatter.linenostart = abs(get_int_opt(options, 'linenostart', 1))
Definition at line 262 of file latex.py.
linenostep
pip._vendor.pygments.formatters.latex.LatexFormatter.linenostep = abs(get_int_opt(options, 'linenostep', 1))
Definition at line 263 of file latex.py.
mathescape
pip._vendor.pygments.formatters.latex.LatexFormatter.mathescape = get_bool_opt(options, 'mathescape', False)
Definition at line 268 of file latex.py.
nobackground
pip._vendor.pygments.formatters.latex.LatexFormatter.nobackground = get_bool_opt(options, 'nobackground', False)
Definition at line 265 of file latex.py.
nowrap
pip._vendor.pygments.formatters.latex.LatexFormatter.nowrap = get_bool_opt(options, 'nowrap', False)
Definition at line 258 of file latex.py.
Referenced by pip._vendor.pygments.formatters.svg.SvgFormatter.format_unencoded().
preamble
pip._vendor.pygments.formatters.latex.LatexFormatter.preamble = options.get('preamble', '')
Definition at line 260 of file latex.py.
right
pip._vendor.pygments.formatters.latex.LatexFormatter.right = self.escapeinside[1]
Definition at line 272 of file latex.py.
Referenced by pip._vendor.rich.padding.Padding.__rich_console__(), pip._vendor.rich.padding.Padding.__rich_measure__(), and pip._vendor.pygments.formatters.latex.LatexEmbeddedLexer._find_escape_tokens().
texcomments
pip._vendor.pygments.formatters.latex.LatexFormatter.texcomments = get_bool_opt(options, 'texcomments', False)
Definition at line 267 of file latex.py.
verboptions
pip._vendor.pygments.formatters.latex.LatexFormatter.verboptions = options.get('verboptions', '')
Definition at line 264 of file latex.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/pygments/formatters/latex.py