Read&Watch: apscheduler.events.JobExecutionEvent Class Reference
apscheduler.events.JobExecutionEvent Class Reference
Public Member Functions
__init__ (self, code, job_id, jobstore, scheduled_run_time, retval=None, exception=None, traceback=None)
Public Member Functions inherited from apscheduler.events.JobEvent
__init__ (self, code, job_id, jobstore)
Public Member Functions inherited from apscheduler.events.SchedulerEvent
__init__ (self, code, alias=None)
__repr__ (self)
Public Attributes
scheduled_run_time = scheduled_run_time
retval = retval
exception = exception
traceback = traceback
Public Attributes inherited from apscheduler.events.JobEvent
job_id = job_id
jobstore = jobstore
Public Attributes inherited from apscheduler.events.SchedulerEvent
code = code
alias = alias
Detailed Description
An event that concerns the running of a job within its executor.
:ivar scheduled_run_time: the time when the job was scheduled to be run
:ivar retval: the return value of the successfully executed job
:ivar exception: the exception raised by the job
:ivar traceback: a formatted traceback for the exception
Definition at line 110 of file events.py.
Constructor & Destructor Documentation
__init__()
apscheduler.events.JobExecutionEvent.__init__ (self, code, job_id, jobstore, scheduled_run_time, retval = None, exception = None, traceback = None)
Definition at line 120 of file events.py.
    ):
        super().__init__(code, job_id, jobstore)
        self.scheduled_run_time = scheduled_run_time
        self.retval = retval
        self.exception = exception
        self.traceback = traceback
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Data Documentation
exception
apscheduler.events.JobExecutionEvent.exception = exception
Definition at line 133 of file events.py.
Referenced by django.core.serializers.BadSerializer.__call__(), and pip._vendor.pygments.filters.RaiseOnErrorTokenFilter.filter().
retval
apscheduler.events.JobExecutionEvent.retval = retval
Definition at line 132 of file events.py.
scheduled_run_time
apscheduler.events.JobExecutionEvent.scheduled_run_time = scheduled_run_time
Definition at line 131 of file events.py.
traceback
apscheduler.events.JobExecutionEvent.traceback = traceback
Definition at line 134 of file events.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/apscheduler/events.py