Read&Watch: charset_normalizer.models.CharsetMatches Class Reference
charset_normalizer.models.CharsetMatches Class Reference
Public Member Functions
__init__ (self, Optional[List[CharsetMatch]] results=None)
Iterator[CharsetMatch] __iter__ (self)
CharsetMatch __getitem__ (self, Union[int, str] item)
int __len__ (self)
bool __bool__ (self)
None append (self, CharsetMatch item)
Optional["CharsetMatch"] best (self)
Optional["CharsetMatch"] first (self)
Protected Attributes
List[CharsetMatch] _results = sorted(results) if results else []
Detailed Description
Container with every CharsetMatch items ordered by default from most probable to the less one.
Act like a list(iterable) but does not implements all related methods.
Definition at line 244 of file models.py.
Constructor & Destructor Documentation
__init__()
charset_normalizer.models.CharsetMatches.__init__ (self, Optional[List[CharsetMatch]] results = None)
Definition at line 250 of file models.py.
    def __init__(self, results: Optional[List[CharsetMatch]] = None):
        self._results: List[CharsetMatch] = sorted(results) if results else []
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
__bool__()
bool charset_normalizer.models.CharsetMatches.__bool__ (self)
Definition at line 273 of file models.py.
    def __bool__(self) -> bool:
        return len(self._results) > 0
References _results.
__getitem__()
CharsetMatch charset_normalizer.models.CharsetMatches.__getitem__ (self, Union[int, str] item)
Retrieve a single item either by its position or encoding name (alias may be used here).
Raise KeyError upon invalid index or encoding not present in results.
Definition at line 256 of file models.py.
    def __getitem__(self, item: Union[int, str]) -> CharsetMatch:
        """
        Retrieve a single item either by its position or encoding name (alias may be used here).
        Raise KeyError upon invalid index or encoding not present in results.
        """
        if isinstance(item, int):
            return self._results[item]
        if isinstance(item, str):
            item = iana_name(item, False)
            for result in self._results:
                if item in result.could_be_from_charset:
                    return result
        raise KeyError
References _results.
Referenced by django.test.utils.ContextList.get().
__iter__()
Iterator[CharsetMatch] charset_normalizer.models.CharsetMatches.__iter__ (self)
Definition at line 253 of file models.py.
    def __iter__(self) -> Iterator[CharsetMatch]:
        yield from self._results
References _results.
Referenced by django.db.models.query.BaseIterable._async_generator().
__len__()
int charset_normalizer.models.CharsetMatches.__len__ (self)
Definition at line 270 of file models.py.
    def __len__(self) -> int:
        return len(self._results)
References _results.
append()
None charset_normalizer.models.CharsetMatches.append (self, CharsetMatch item)
Insert a single match. Will be inserted accordingly to preserve sort.
Can be inserted as a submatch.
Definition at line 276 of file models.py.
    def append(self, item: CharsetMatch) -> None:
        """
        Insert a single match. Will be inserted accordingly to preserve sort.
        Can be inserted as a submatch.
        """
        if not isinstance(item, CharsetMatch):
            raise ValueError(
                "Cannot append instance '{}' to CharsetMatches".format(
                    str(item.__class__)
                )
            )
        # We should disable the submatch factoring when the input file is too heavy (conserve RAM usage)
        if len(item.raw) < TOO_BIG_SEQUENCE:
            for match in self._results:
                if match.fingerprint == item.fingerprint and match.chaos == item.chaos:
                    match.add_submatch(item)
                    return
        self._results.append(item)
        self._results = sorted(self._results)
References _results, and append().
Referenced by pylint.reporters.ureports.nodes.BaseLayout.__init__(), pylint.reporters.ureports.nodes.EvaluationSection.__init__(), tomlkit.container.Container.__setitem__(), tomlkit.container.Container._handle_dotted_key(), tomlkit.container.Container._replace_at(), tomlkit.container.Container.add(), tomlkit.items.AbstractTable.add(), append(), and pip._vendor.rich._stack.Stack.push().
best()
Optional["CharsetMatch"] charset_normalizer.models.CharsetMatches.best (self)
Simply return the first match. Strict equivalent to matches[0].
Definition at line 296 of file models.py.
    def best(self) -> Optional["CharsetMatch"]:
        """
        Simply return the first match. Strict equivalent to matches[0].
        """
        if not self._results:
            return None
        return self._results[0]
References _results.
Referenced by first().
first()
Optional["CharsetMatch"] charset_normalizer.models.CharsetMatches.first (self)
Redundant method, call the method best(). Kept for BC reasons.
Definition at line 304 of file models.py.
    def first(self) -> Optional["CharsetMatch"]:
        """
        Redundant method, call the method best(). Kept for BC reasons.
        """
        return self.best()
References best().
Member Data Documentation
_results
charset_normalizer.models.CharsetMatches._results = sorted(results) if results else [] protected
Definition at line 251 of file models.py.
Referenced by __bool__(), __getitem__(), __iter__(), __len__(), append(), and best().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/charset_normalizer/models.py