Read&Watch: pip._vendor.platformdirs.windows.Windows Class Reference
pip._vendor.platformdirs.windows.Windows Class Reference
Public Member Functions
str user_data_dir (self)
str site_data_dir (self)
str user_config_dir (self)
str site_config_dir (self)
str user_cache_dir (self)
str site_cache_dir (self)
str user_state_dir (self)
str user_log_dir (self)
str user_documents_dir (self)
str user_downloads_dir (self)
str user_pictures_dir (self)
str user_videos_dir (self)
str user_music_dir (self)
str user_desktop_dir (self)
str user_runtime_dir (self)
str site_runtime_dir (self)
Public Member Functions inherited from pip._vendor.platformdirs.api.PlatformDirsABC
None __init__ (self, str|None appname=None, str|None|Literal[False] appauthor=None, str|None version=None, bool roaming=False, bool multipath=False, bool opinion=True, bool ensure_exists=False)
Path user_data_path (self)
Path site_data_path (self)
Path user_config_path (self)
Path site_config_path (self)
Path user_cache_path (self)
Path site_cache_path (self)
Path user_state_path (self)
Path user_log_path (self)
Path user_documents_path (self)
Path user_downloads_path (self)
Path user_pictures_path (self)
Path user_videos_path (self)
Path user_music_path (self)
Path user_desktop_path (self)
Path user_runtime_path (self)
Path site_runtime_path (self)
Iterator[str] iter_config_dirs (self)
Iterator[str] iter_data_dirs (self)
Iterator[str] iter_cache_dirs (self)
Iterator[str] iter_runtime_dirs (self)
Iterator[Path] iter_config_paths (self)
Iterator[Path] iter_data_paths (self)
Iterator[Path] iter_cache_paths (self)
Iterator[Path] iter_runtime_paths (self)
Protected Member Functions
str _append_parts (self, str path, *, str|None opinion_value=None)
Protected Member Functions inherited from pip._vendor.platformdirs.api.PlatformDirsABC
str _append_app_name_and_version (self, *str base)
None _optionally_create_directory (self, str path)
Additional Inherited Members
Public Attributes inherited from pip._vendor.platformdirs.api.PlatformDirsABC
appname = appname
appauthor = appauthor
version = version
roaming = roaming
multipath = multipath
opinion = opinion
ensure_exists = ensure_exists
Detailed Description
`MSDN on where to store app data files <https://learn.microsoft.com/en-us/windows/win32/shell/knownfolderid>`_.
Makes use of the `appname <platformdirs.api.PlatformDirsABC.appname>`, `appauthor
<platformdirs.api.PlatformDirsABC.appauthor>`, `version <platformdirs.api.PlatformDirsABC.version>`, `roaming
<platformdirs.api.PlatformDirsABC.roaming>`, `opinion <platformdirs.api.PlatformDirsABC.opinion>`, `ensure_exists
<platformdirs.api.PlatformDirsABC.ensure_exists>`.
Definition at line 16 of file windows.py.
Member Function Documentation
_append_parts()
str pip._vendor.platformdirs.windows.Windows._append_parts (self, str path, * , str | None opinion_value = None) protected
Definition at line 38 of file windows.py.
    def _append_parts(self, path: str, *, opinion_value: str | None = None) -> str:
        params = []
        if self.appname:
            if self.appauthor is not False:
                author = self.appauthor or self.appname
                params.append(author)
            params.append(self.appname)
            if opinion_value is not None and self.opinion:
                params.append(opinion_value)
            if self.version:
                params.append(self.version)
        path = os.path.join(path, *params)  # noqa: PTH118
        self._optionally_create_directory(path)
        return path
Referenced by site_cache_dir(), platformdirs.windows.Windows.site_cache_dir(), site_data_dir(), platformdirs.windows.Windows.site_data_dir(), user_cache_dir(), platformdirs.windows.Windows.user_cache_dir(), user_data_dir(), platformdirs.windows.Windows.user_data_dir(), user_runtime_dir(), and platformdirs.windows.Windows.user_runtime_dir().
site_cache_dir()
str pip._vendor.platformdirs.windows.Windows.site_cache_dir (self)
:return: cache directory shared by users, e.g. ``C:\\ProgramData\\$appauthor\\$appname\\Cache\\$version``
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 79 of file windows.py.
    def site_cache_dir(self) -> str:
        """:return: cache directory shared by users, e.g. ``C:\\ProgramData\\$appauthor\\$appname\\Cache\\$version``"""
        path = os.path.normpath(get_win_folder("CSIDL_COMMON_APPDATA"))
        return self._append_parts(path, opinion_value="Cache")
References _append_parts(), and pip._vendor.platformdirs.windows.get_win_folder.
site_config_dir()
str pip._vendor.platformdirs.windows.Windows.site_config_dir (self)
:return: config directory shared by the users, same as `site_data_dir`
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 65 of file windows.py.
    def site_config_dir(self) -> str:
        """:return: config directory shared by the users, same as `site_data_dir`"""
        return self.site_data_dir
References pip._vendor.platformdirs.api.PlatformDirsABC.site_data_dir.
site_data_dir()
str pip._vendor.platformdirs.windows.Windows.site_data_dir (self)
:return: data directory shared by users, e.g. ``C:\\ProgramData\\$appauthor\\$appname``
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 54 of file windows.py.
    def site_data_dir(self) -> str:
        """:return: data directory shared by users, e.g. ``C:\\ProgramData\\$appauthor\\$appname``"""
        path = os.path.normpath(get_win_folder("CSIDL_COMMON_APPDATA"))
        return self._append_parts(path)
References _append_parts(), and pip._vendor.platformdirs.windows.get_win_folder.
site_runtime_dir()
str pip._vendor.platformdirs.windows.Windows.site_runtime_dir (self)
:return: runtime directory shared by users, same as `user_runtime_dir`
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 138 of file windows.py.
    def site_runtime_dir(self) -> str:
        """:return: runtime directory shared by users, same as `user_runtime_dir`"""
        return self.user_runtime_dir
References pip._vendor.platformdirs.api.PlatformDirsABC.user_runtime_dir.
user_cache_dir()
str pip._vendor.platformdirs.windows.Windows.user_cache_dir (self)
:return: cache directory tied to the user (if opinionated with ``Cache`` folder within ``$appname``) e.g.
 ``%USERPROFILE%\\AppData\\Local\\$appauthor\\$appname\\Cache\\$version``
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 70 of file windows.py.
    def user_cache_dir(self) -> str:
        """
        :return: cache directory tied to the user (if opinionated with ``Cache`` folder within ``$appname``) e.g.
         ``%USERPROFILE%\\AppData\\Local\\$appauthor\\$appname\\Cache\\$version``
        """
        path = os.path.normpath(get_win_folder("CSIDL_LOCAL_APPDATA"))
        return self._append_parts(path, opinion_value="Cache")
References _append_parts(), and pip._vendor.platformdirs.windows.get_win_folder.
user_config_dir()
str pip._vendor.platformdirs.windows.Windows.user_config_dir (self)
:return: config directory tied to the user, same as `user_data_dir`
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 60 of file windows.py.
    def user_config_dir(self) -> str:
        """:return: config directory tied to the user, same as `user_data_dir`"""
        return self.user_data_dir
References pip._vendor.platformdirs.api.PlatformDirsABC.user_data_dir.
user_data_dir()
str pip._vendor.platformdirs.windows.Windows.user_data_dir (self)
:return: data directory tied to the user, e.g.
 ``%USERPROFILE%\\AppData\\Local\\$appauthor\\$appname`` (not roaming) or
 ``%USERPROFILE%\\AppData\\Roaming\\$appauthor\\$appname`` (roaming)
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 28 of file windows.py.
    def user_data_dir(self) -> str:
        """
        :return: data directory tied to the user, e.g.
         ``%USERPROFILE%\\AppData\\Local\\$appauthor\\$appname`` (not roaming) or
         ``%USERPROFILE%\\AppData\\Roaming\\$appauthor\\$appname`` (roaming)
        """
        const = "CSIDL_APPDATA" if self.roaming else "CSIDL_LOCAL_APPDATA"
        path = os.path.normpath(get_win_folder(const))
        return self._append_parts(path)
References _append_parts(), pip._vendor.platformdirs.windows.get_win_folder, and pip._vendor.platformdirs.api.PlatformDirsABC.roaming.
user_desktop_dir()
str pip._vendor.platformdirs.windows.Windows.user_desktop_dir (self)
:return: desktop directory tied to the user, e.g. ``%USERPROFILE%\\Desktop``
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 124 of file windows.py.
    def user_desktop_dir(self) -> str:
        """:return: desktop directory tied to the user, e.g. ``%USERPROFILE%\\Desktop``"""
        return os.path.normpath(get_win_folder("CSIDL_DESKTOPDIRECTORY"))
References pip._vendor.platformdirs.windows.get_win_folder.
user_documents_dir()
str pip._vendor.platformdirs.windows.Windows.user_documents_dir (self)
:return: documents directory tied to the user e.g. ``%USERPROFILE%\\Documents``
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 99 of file windows.py.
    def user_documents_dir(self) -> str:
        """:return: documents directory tied to the user e.g. ``%USERPROFILE%\\Documents``"""
        return os.path.normpath(get_win_folder("CSIDL_PERSONAL"))
References pip._vendor.platformdirs.windows.get_win_folder.
user_downloads_dir()
str pip._vendor.platformdirs.windows.Windows.user_downloads_dir (self)
:return: downloads directory tied to the user e.g. ``%USERPROFILE%\\Downloads``
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 104 of file windows.py.
    def user_downloads_dir(self) -> str:
        """:return: downloads directory tied to the user e.g. ``%USERPROFILE%\\Downloads``"""
        return os.path.normpath(get_win_folder("CSIDL_DOWNLOADS"))
References pip._vendor.platformdirs.windows.get_win_folder.
user_log_dir()
str pip._vendor.platformdirs.windows.Windows.user_log_dir (self)
:return: log directory tied to the user, same as `user_data_dir` if not opinionated else ``Logs`` in it
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 90 of file windows.py.
    def user_log_dir(self) -> str:
        """:return: log directory tied to the user, same as `user_data_dir` if not opinionated else ``Logs`` in it"""
        path = self.user_data_dir
        if self.opinion:
            path = os.path.join(path, "Logs")  # noqa: PTH118
            self._optionally_create_directory(path)
        return path
References pip._vendor.platformdirs.api.PlatformDirsABC._optionally_create_directory(), pip._vendor.platformdirs.android.Android.opinion, pip._vendor.platformdirs.api.PlatformDirsABC.opinion, and pip._vendor.platformdirs.api.PlatformDirsABC.user_data_dir.
user_music_dir()
str pip._vendor.platformdirs.windows.Windows.user_music_dir (self)
:return: music directory tied to the user e.g. ``%USERPROFILE%\\Music``
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 119 of file windows.py.
    def user_music_dir(self) -> str:
        """:return: music directory tied to the user e.g. ``%USERPROFILE%\\Music``"""
        return os.path.normpath(get_win_folder("CSIDL_MYMUSIC"))
References pip._vendor.platformdirs.windows.get_win_folder.
user_pictures_dir()
str pip._vendor.platformdirs.windows.Windows.user_pictures_dir (self)
:return: pictures directory tied to the user e.g. ``%USERPROFILE%\\Pictures``
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 109 of file windows.py.
    def user_pictures_dir(self) -> str:
        """:return: pictures directory tied to the user e.g. ``%USERPROFILE%\\Pictures``"""
        return os.path.normpath(get_win_folder("CSIDL_MYPICTURES"))
References pip._vendor.platformdirs.windows.get_win_folder.
user_runtime_dir()
str pip._vendor.platformdirs.windows.Windows.user_runtime_dir (self)
:return: runtime directory tied to the user, e.g.
 ``%USERPROFILE%\\AppData\\Local\\Temp\\$appauthor\\$appname``
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 129 of file windows.py.
    def user_runtime_dir(self) -> str:
        """
        :return: runtime directory tied to the user, e.g.
         ``%USERPROFILE%\\AppData\\Local\\Temp\\$appauthor\\$appname``
        """
        path = os.path.normpath(os.path.join(get_win_folder("CSIDL_LOCAL_APPDATA"), "Temp"))  # noqa: PTH118
        return self._append_parts(path)
References _append_parts(), and pip._vendor.platformdirs.windows.get_win_folder.
user_state_dir()
str pip._vendor.platformdirs.windows.Windows.user_state_dir (self)
:return: state directory tied to the user, same as `user_data_dir`
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 85 of file windows.py.
    def user_state_dir(self) -> str:
        """:return: state directory tied to the user, same as `user_data_dir`"""
        return self.user_data_dir
References pip._vendor.platformdirs.api.PlatformDirsABC.user_data_dir.
user_videos_dir()
str pip._vendor.platformdirs.windows.Windows.user_videos_dir (self)
:return: videos directory tied to the user e.g. ``%USERPROFILE%\\Videos``
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 114 of file windows.py.
    def user_videos_dir(self) -> str:
        """:return: videos directory tied to the user e.g. ``%USERPROFILE%\\Videos``"""
        return os.path.normpath(get_win_folder("CSIDL_MYVIDEO"))
References pip._vendor.platformdirs.windows.get_win_folder.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/platformdirs/windows.py