Read&Watch: pip._vendor.platformdirs.unix.Unix Class Reference
pip._vendor.platformdirs.unix.Unix Class Reference
Public Member Functions
str user_data_dir (self)
str site_data_dir (self)
str user_config_dir (self)
str site_config_dir (self)
str user_cache_dir (self)
str site_cache_dir (self)
str user_state_dir (self)
str user_log_dir (self)
str user_documents_dir (self)
str user_downloads_dir (self)
str user_pictures_dir (self)
str user_videos_dir (self)
str user_music_dir (self)
str user_desktop_dir (self)
str user_runtime_dir (self)
str site_runtime_dir (self)
Path site_data_path (self)
Path site_config_path (self)
Path site_cache_path (self)
Iterator[str] iter_config_dirs (self)
Iterator[str] iter_data_dirs (self)
Public Member Functions inherited from pip._vendor.platformdirs.api.PlatformDirsABC
None __init__ (self, str|None appname=None, str|None|Literal[False] appauthor=None, str|None version=None, bool roaming=False, bool multipath=False, bool opinion=True, bool ensure_exists=False)
Path user_data_path (self)
Path user_config_path (self)
Path user_cache_path (self)
Path user_state_path (self)
Path user_log_path (self)
Path user_documents_path (self)
Path user_downloads_path (self)
Path user_pictures_path (self)
Path user_videos_path (self)
Path user_music_path (self)
Path user_desktop_path (self)
Path user_runtime_path (self)
Path site_runtime_path (self)
Iterator[str] iter_cache_dirs (self)
Iterator[str] iter_runtime_dirs (self)
Iterator[Path] iter_config_paths (self)
Iterator[Path] iter_data_paths (self)
Iterator[Path] iter_cache_paths (self)
Iterator[Path] iter_runtime_paths (self)
Protected Member Functions
list[str] _site_data_dirs (self)
list[str] _site_config_dirs (self)
Path _first_item_as_path_if_multipath (self, str directory)
Protected Member Functions inherited from pip._vendor.platformdirs.api.PlatformDirsABC
str _append_app_name_and_version (self, *str base)
None _optionally_create_directory (self, str path)
Additional Inherited Members
Public Attributes inherited from pip._vendor.platformdirs.api.PlatformDirsABC
appname = appname
appauthor = appauthor
version = version
roaming = roaming
multipath = multipath
opinion = opinion
ensure_exists = ensure_exists
Detailed Description
On Unix/Linux, we follow the `XDG Basedir Spec <https://specifications.freedesktop.org/basedir-spec/basedir-spec-
latest.html>`_.
The spec allows overriding directories with environment variables. The examples shown are the default values,
alongside the name of the environment variable that overrides them. Makes use of the `appname
<platformdirs.api.PlatformDirsABC.appname>`, `version <platformdirs.api.PlatformDirsABC.version>`, `multipath
<platformdirs.api.PlatformDirsABC.multipath>`, `opinion <platformdirs.api.PlatformDirsABC.opinion>`, `ensure_exists
<platformdirs.api.PlatformDirsABC.ensure_exists>`.
Definition at line 23 of file unix.py.
Member Function Documentation
_first_item_as_path_if_multipath()
Path pip._vendor.platformdirs.unix.Unix._first_item_as_path_if_multipath (self, str directory) protected
Definition at line 221 of file unix.py.
    def _first_item_as_path_if_multipath(self, directory: str) -> Path:
        if self.multipath:
            # If multipath is True, the first path is returned.
            directory = directory.split(os.pathsep)[0]
        return Path(directory)
References pip._vendor.platformdirs.api.PlatformDirsABC.multipath.
_site_config_dirs()
list[str] pip._vendor.platformdirs.unix.Unix._site_config_dirs (self) protected
Definition at line 79 of file unix.py.
    def _site_config_dirs(self) -> list[str]:
        path = os.environ.get("XDG_CONFIG_DIRS", "")
        if not path.strip():
            path = "/etc/xdg"
        return [self._append_app_name_and_version(p) for p in path.split(os.pathsep)]
References pip._vendor.platformdirs.api.PlatformDirsABC._append_app_name_and_version().
Referenced by iter_config_dirs(), platformdirs.unix.Unix.iter_config_dirs(), site_config_dir(), and platformdirs.unix.Unix.site_config_dir().
_site_data_dirs()
list[str] pip._vendor.platformdirs.unix.Unix._site_data_dirs (self) protected
Definition at line 48 of file unix.py.
    def _site_data_dirs(self) -> list[str]:
        path = os.environ.get("XDG_DATA_DIRS", "")
        if not path.strip():
            path = f"/usr/local/share{os.pathsep}/usr/share"
        return [self._append_app_name_and_version(p) for p in path.split(os.pathsep)]
References pip._vendor.platformdirs.api.PlatformDirsABC._append_app_name_and_version().
Referenced by iter_data_dirs(), platformdirs.unix.Unix.iter_data_dirs(), site_data_dir(), and platformdirs.unix.Unix.site_data_dir().
iter_config_dirs()
Iterator[str] pip._vendor.platformdirs.unix.Unix.iter_config_dirs (self)
:yield: all user and site configuration directories.
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 227 of file unix.py.
    def iter_config_dirs(self) -> Iterator[str]:
        """:yield: all user and site configuration directories."""
        yield self.user_config_dir
        yield from self._site_config_dirs
References _site_config_dirs(), and pip._vendor.platformdirs.api.PlatformDirsABC.user_config_dir.
iter_data_dirs()
Iterator[str] pip._vendor.platformdirs.unix.Unix.iter_data_dirs (self)
:yield: all user and site data directories.
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 232 of file unix.py.
    def iter_data_dirs(self) -> Iterator[str]:
        """:yield: all user and site data directories."""
        yield self.user_data_dir
        yield from self._site_data_dirs
References _site_data_dirs(), and pip._vendor.platformdirs.api.PlatformDirsABC.user_data_dir.
site_cache_dir()
str pip._vendor.platformdirs.unix.Unix.site_cache_dir (self)
:return: cache directory shared by users, e.g. ``/var/cache/$appname/$version``
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 110 of file unix.py.
    def site_cache_dir(self) -> str:
        """:return: cache directory shared by users, e.g. ``/var/cache/$appname/$version``"""
        return self._append_app_name_and_version("/var/cache")
References pip._vendor.platformdirs.api.PlatformDirsABC._append_app_name_and_version().
site_cache_path()
Path pip._vendor.platformdirs.unix.Unix.site_cache_path (self)
:return: cache path shared by users. Only return the first item, even if ``multipath`` is set to ``True``
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 217 of file unix.py.
    def site_cache_path(self) -> Path:
        """:return: cache path shared by users. Only return the first item, even if ``multipath`` is set to ``True``"""
        return self._first_item_as_path_if_multipath(self.site_cache_dir)
site_config_dir()
str pip._vendor.platformdirs.unix.Unix.site_config_dir (self)
:return: config directories shared by users (if `multipath <platformdirs.api.PlatformDirsABC.multipath>`
 is enabled and ``XDG_CONFIG_DIRS`` is set and a multi path the response is also a multi path separated by
 the OS path separator), e.g. ``/etc/xdg/$appname/$version``
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 86 of file unix.py.
    def site_config_dir(self) -> str:
        """
        :return: config directories shared by users (if `multipath <platformdirs.api.PlatformDirsABC.multipath>`
         is enabled and ``XDG_CONFIG_DIRS`` is set and a multi path the response is also a multi path separated by
         the OS path separator), e.g. ``/etc/xdg/$appname/$version``
        """
        # XDG default for $XDG_CONFIG_DIRS only first, if multipath is False
        dirs = self._site_config_dirs
        if not self.multipath:
            return dirs[0]
        return os.pathsep.join(dirs)
References _site_config_dirs(), and pip._vendor.platformdirs.api.PlatformDirsABC.multipath.
site_config_path()
Path pip._vendor.platformdirs.unix.Unix.site_config_path (self)
:return: config path shared by the users, returns the first item, even if ``multipath`` is set to ``True``
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 212 of file unix.py.
    def site_config_path(self) -> Path:
        """:return: config path shared by the users, returns the first item, even if ``multipath`` is set to ``True``"""
        return self._first_item_as_path_if_multipath(self.site_config_dir)
site_data_dir()
str pip._vendor.platformdirs.unix.Unix.site_data_dir (self)
:return: data directories shared by users (if `multipath <platformdirs.api.PlatformDirsABC.multipath>` is
 enabled and ``XDG_DATA_DIRS`` is set and a multi path the response is also a multi path separated by the
 OS path separator), e.g. ``/usr/local/share/$appname/$version`` or ``/usr/share/$appname/$version``
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 55 of file unix.py.
    def site_data_dir(self) -> str:
        """
        :return: data directories shared by users (if `multipath <platformdirs.api.PlatformDirsABC.multipath>` is
         enabled and ``XDG_DATA_DIRS`` is set and a multi path the response is also a multi path separated by the
         OS path separator), e.g. ``/usr/local/share/$appname/$version`` or ``/usr/share/$appname/$version``
        """
        # XDG default for $XDG_DATA_DIRS; only first, if multipath is False
        dirs = self._site_data_dirs
        if not self.multipath:
            return dirs[0]
        return os.pathsep.join(dirs)
References _site_data_dirs().
site_data_path()
Path pip._vendor.platformdirs.unix.Unix.site_data_path (self)
:return: data path shared by users. Only return the first item, even if ``multipath`` is set to ``True``
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 207 of file unix.py.
    def site_data_path(self) -> Path:
        """:return: data path shared by users. Only return the first item, even if ``multipath`` is set to ``True``"""
        return self._first_item_as_path_if_multipath(self.site_data_dir)
site_runtime_dir()
str pip._vendor.platformdirs.unix.Unix.site_runtime_dir (self)
:return: runtime directory shared by users, e.g. ``/run/$appname/$version`` or \
``$XDG_RUNTIME_DIR/$appname/$version``.
Note that this behaves almost exactly like `user_runtime_dir` if ``$XDG_RUNTIME_DIR`` is set, but will
fall back to paths associated to the root user instead of a regular logged-in user if it's not set.
If you wish to ensure that a logged-in root user path is returned e.g. ``/run/user/0``, use `user_runtime_dir`
instead.
For FreeBSD/OpenBSD/NetBSD, it would return ``/var/run/$appname/$version`` if ``$XDG_RUNTIME_DIR`` is not set.
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 185 of file unix.py.
    def site_runtime_dir(self) -> str:
        """
        :return: runtime directory shared by users, e.g. ``/run/$appname/$version`` or \
        ``$XDG_RUNTIME_DIR/$appname/$version``.
        Note that this behaves almost exactly like `user_runtime_dir` if ``$XDG_RUNTIME_DIR`` is set, but will
        fall back to paths associated to the root user instead of a regular logged-in user if it's not set.
        If you wish to ensure that a logged-in root user path is returned e.g. ``/run/user/0``, use `user_runtime_dir`
        instead.
        For FreeBSD/OpenBSD/NetBSD, it would return ``/var/run/$appname/$version`` if ``$XDG_RUNTIME_DIR`` is not set.
        """
        path = os.environ.get("XDG_RUNTIME_DIR", "")
        if not path.strip():
            if sys.platform.startswith(("freebsd", "openbsd", "netbsd")):
                path = "/var/run"
            else:
                path = "/run"
        return self._append_app_name_and_version(path)
References pip._vendor.platformdirs.api.PlatformDirsABC._append_app_name_and_version().
user_cache_dir()
str pip._vendor.platformdirs.unix.Unix.user_cache_dir (self)
:return: cache directory tied to the user, e.g. ``~/.cache/$appname/$version`` or
 ``~/$XDG_CACHE_HOME/$appname/$version``
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 99 of file unix.py.
    def user_cache_dir(self) -> str:
        """
        :return: cache directory tied to the user, e.g. ``~/.cache/$appname/$version`` or
         ``~/$XDG_CACHE_HOME/$appname/$version``
        """
        path = os.environ.get("XDG_CACHE_HOME", "")
        if not path.strip():
            path = os.path.expanduser("~/.cache")  # noqa: PTH111
        return self._append_app_name_and_version(path)
References pip._vendor.platformdirs.api.PlatformDirsABC._append_app_name_and_version().
user_config_dir()
str pip._vendor.platformdirs.unix.Unix.user_config_dir (self)
:return: config directory tied to the user, e.g. ``~/.config/$appname/$version`` or
 ``$XDG_CONFIG_HOME/$appname/$version``
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 68 of file unix.py.
    def user_config_dir(self) -> str:
        """
        :return: config directory tied to the user, e.g. ``~/.config/$appname/$version`` or
         ``$XDG_CONFIG_HOME/$appname/$version``
        """
        path = os.environ.get("XDG_CONFIG_HOME", "")
        if not path.strip():
            path = os.path.expanduser("~/.config")  # noqa: PTH111
        return self._append_app_name_and_version(path)
References pip._vendor.platformdirs.api.PlatformDirsABC._append_app_name_and_version().
user_data_dir()
str pip._vendor.platformdirs.unix.Unix.user_data_dir (self)
:return: data directory tied to the user, e.g. ``~/.local/share/$appname/$version`` or
 ``$XDG_DATA_HOME/$appname/$version``
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 37 of file unix.py.
    def user_data_dir(self) -> str:
        """
        :return: data directory tied to the user, e.g. ``~/.local/share/$appname/$version`` or
         ``$XDG_DATA_HOME/$appname/$version``
        """
        path = os.environ.get("XDG_DATA_HOME", "")
        if not path.strip():
            path = os.path.expanduser("~/.local/share")  # noqa: PTH111
        return self._append_app_name_and_version(path)
References pip._vendor.platformdirs.api.PlatformDirsABC._append_app_name_and_version().
user_desktop_dir()
str pip._vendor.platformdirs.unix.Unix.user_desktop_dir (self)
:return: desktop directory tied to the user, e.g. ``~/Desktop``
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 160 of file unix.py.
    def user_desktop_dir(self) -> str:
        """:return: desktop directory tied to the user, e.g. ``~/Desktop``"""
        return _get_user_media_dir("XDG_DESKTOP_DIR", "~/Desktop")
References pip._vendor.platformdirs.unix._get_user_media_dir().
user_documents_dir()
str pip._vendor.platformdirs.unix.Unix.user_documents_dir (self)
:return: documents directory tied to the user, e.g. ``~/Documents``
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 135 of file unix.py.
    def user_documents_dir(self) -> str:
        """:return: documents directory tied to the user, e.g. ``~/Documents``"""
        return _get_user_media_dir("XDG_DOCUMENTS_DIR", "~/Documents")
References pip._vendor.platformdirs.unix._get_user_media_dir().
user_downloads_dir()
str pip._vendor.platformdirs.unix.Unix.user_downloads_dir (self)
:return: downloads directory tied to the user, e.g. ``~/Downloads``
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 140 of file unix.py.
    def user_downloads_dir(self) -> str:
        """:return: downloads directory tied to the user, e.g. ``~/Downloads``"""
        return _get_user_media_dir("XDG_DOWNLOAD_DIR", "~/Downloads")
References pip._vendor.platformdirs.unix._get_user_media_dir().
user_log_dir()
str pip._vendor.platformdirs.unix.Unix.user_log_dir (self)
:return: log directory tied to the user, same as `user_state_dir` if not opinionated else ``log`` in it
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 126 of file unix.py.
    def user_log_dir(self) -> str:
        """:return: log directory tied to the user, same as `user_state_dir` if not opinionated else ``log`` in it"""
        path = self.user_state_dir
        if self.opinion:
            path = os.path.join(path, "log")  # noqa: PTH118
            self._optionally_create_directory(path)
        return path
References pip._vendor.platformdirs.api.PlatformDirsABC.user_state_dir.
user_music_dir()
str pip._vendor.platformdirs.unix.Unix.user_music_dir (self)
:return: music directory tied to the user, e.g. ``~/Music``
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 155 of file unix.py.
    def user_music_dir(self) -> str:
        """:return: music directory tied to the user, e.g. ``~/Music``"""
        return _get_user_media_dir("XDG_MUSIC_DIR", "~/Music")
References pip._vendor.platformdirs.unix._get_user_media_dir().
user_pictures_dir()
str pip._vendor.platformdirs.unix.Unix.user_pictures_dir (self)
:return: pictures directory tied to the user, e.g. ``~/Pictures``
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 145 of file unix.py.
    def user_pictures_dir(self) -> str:
        """:return: pictures directory tied to the user, e.g. ``~/Pictures``"""
        return _get_user_media_dir("XDG_PICTURES_DIR", "~/Pictures")
References pip._vendor.platformdirs.unix._get_user_media_dir().
user_runtime_dir()
str pip._vendor.platformdirs.unix.Unix.user_runtime_dir (self)
:return: runtime directory tied to the user, e.g. ``/run/user/$(id -u)/$appname/$version`` or
 ``$XDG_RUNTIME_DIR/$appname/$version``.
 For FreeBSD/OpenBSD/NetBSD, it would return ``/var/run/user/$(id -u)/$appname/$version`` if
 exists, otherwise ``/tmp/runtime-$(id -u)/$appname/$version``, if``$XDG_RUNTIME_DIR``
 is not set.
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 165 of file unix.py.
    def user_runtime_dir(self) -> str:
        """
        :return: runtime directory tied to the user, e.g. ``/run/user/$(id -u)/$appname/$version`` or
         ``$XDG_RUNTIME_DIR/$appname/$version``.
         For FreeBSD/OpenBSD/NetBSD, it would return ``/var/run/user/$(id -u)/$appname/$version`` if
         exists, otherwise ``/tmp/runtime-$(id -u)/$appname/$version``, if``$XDG_RUNTIME_DIR``
         is not set.
        """
        path = os.environ.get("XDG_RUNTIME_DIR", "")
        if not path.strip():
            if sys.platform.startswith(("freebsd", "openbsd", "netbsd")):
                path = f"/var/run/user/{getuid()}"
                if not Path(path).exists():
                    path = f"/tmp/runtime-{getuid()}"  # noqa: S108
            else:
                path = f"/run/user/{getuid()}"
        return self._append_app_name_and_version(path)
References pip._vendor.platformdirs.api.PlatformDirsABC._append_app_name_and_version().
user_state_dir()
str pip._vendor.platformdirs.unix.Unix.user_state_dir (self)
:return: state directory tied to the user, e.g. ``~/.local/state/$appname/$version`` or
 ``$XDG_STATE_HOME/$appname/$version``
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 115 of file unix.py.
    def user_state_dir(self) -> str:
        """
        :return: state directory tied to the user, e.g. ``~/.local/state/$appname/$version`` or
         ``$XDG_STATE_HOME/$appname/$version``
        """
        path = os.environ.get("XDG_STATE_HOME", "")
        if not path.strip():
            path = os.path.expanduser("~/.local/state")  # noqa: PTH111
        return self._append_app_name_and_version(path)
References pip._vendor.platformdirs.api.PlatformDirsABC._append_app_name_and_version().
user_videos_dir()
str pip._vendor.platformdirs.unix.Unix.user_videos_dir (self)
:return: videos directory tied to the user, e.g. ``~/Videos``
Reimplemented from pip._vendor.platformdirs.api.PlatformDirsABC.
Definition at line 150 of file unix.py.
    def user_videos_dir(self) -> str:
        """:return: videos directory tied to the user, e.g. ``~/Videos``"""
        return _get_user_media_dir("XDG_VIDEOS_DIR", "~/Videos")
References pip._vendor.platformdirs.unix._get_user_media_dir().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/platformdirs/unix.py