Read&Watch: django.template.response.TemplateResponse Class Reference
django.template.response.TemplateResponse Class Reference
Public Member Functions
__init__ (self, request, template, context=None, content_type=None, status=None, charset=None, using=None, headers=None)
Public Member Functions inherited from django.template.response.SimpleTemplateResponse
__init__ (self, template, context=None, content_type=None, status=None, charset=None, using=None, headers=None)
__getstate__ (self)
resolve_template (self, template)
resolve_context (self, context)
rendered_content (self)
add_post_render_callback (self, callback)
render (self)
is_rendered (self)
__iter__ (self)
content (self)
content (self, value)
Public Member Functions inherited from django.http.response.HttpResponse
__init__ (self, content=b"", *args, **kwargs)
__repr__ (self)
serialize (self)
__iter__ (self)
write (self, content)
tell (self)
getvalue (self)
writable (self)
writelines (self, lines)
Public Member Functions inherited from django.http.response.HttpResponseBase
__init__ (self, content_type=None, status=None, reason=None, charset=None, headers=None)
reason_phrase (self)
reason_phrase (self, value)
charset (self)
charset (self, value)
serialize_headers (self)
__setitem__ (self, header, value)
__delitem__ (self, header)
__getitem__ (self, header)
has_header (self, header)
items (self)
get (self, header, alternate=None)
set_cookie (self, key, value="", max_age=None, expires=None, path="/", domain=None, secure=False, httponly=False, samesite=None)
setdefault (self, key, value)
set_signed_cookie (self, key, value, salt="", **kwargs)
delete_cookie (self, key, path="/", domain=None, samesite=None)
make_bytes (self, value)
close (self)
flush (self)
readable (self)
seekable (self)
Additional Inherited Members
Public Attributes inherited from django.template.response.SimpleTemplateResponse
template_name = template
context_data = context
using = using
Public Attributes inherited from django.http.response.HttpResponseBase
headers = ResponseHeaders(headers)
cookies = SimpleCookie()
bool closed = False
charset
Static Public Attributes inherited from django.template.response.SimpleTemplateResponse
list rendering_attrs = ["template_name", "context_data", "_post_render_callbacks"]
Static Public Attributes inherited from django.http.response.HttpResponse
bool streaming = False
Static Public Attributes inherited from django.http.response.HttpResponseBase
int status_code = 200
Protected Member Functions inherited from django.http.response.HttpResponseBase
_content_type_for_repr (self)
Protected Attributes inherited from django.template.response.SimpleTemplateResponse
list _post_render_callbacks = []
_request = None
bool _is_rendered = False
Protected Attributes inherited from django.http.response.HttpResponse
list _container
Protected Attributes inherited from django.http.response.HttpResponseBase
_charset = charset
list _resource_closers = []
_handler_class = None
_reason_phrase = reason
Detailed Description
Definition at line 147 of file response.py.
Constructor & Destructor Documentation
__init__()
django.template.response.TemplateResponse.__init__ (self, request, template, context = None, content_type = None, status = None, charset = None, using = None, headers = None)
Definition at line 150 of file response.py.
    ):
        super().__init__(
            template, context, content_type, status, charset, using, headers=headers
        )
        self._request = request
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/template/response.py