Read&Watch: pip._vendor.pkg_resources.Distribution Class Reference
pip._vendor.pkg_resources.Distribution Class Reference
Public Member Functions
__init__ (self, str|None location=None, _MetadataType metadata=None, str|None project_name=None, str|None version=None, str|None py_version=PY_MAJOR, str|None platform=None, int precedence=EGG_DIST)
Distribution from_location (cls, str location, StrPath basename, _MetadataType metadata=None, **int kw)
hashcmp (self)
__hash__ (self)
__lt__ (self, Distribution other)
__le__ (self, Distribution other)
__gt__ (self, Distribution other)
__ge__ (self, Distribution other)
__eq__ (self, object other)
__ne__ (self, object other)
key (self)
parsed_version (self)
version (self)
requires (self, Iterable[str] extras=())
activate (self, list[str]|None path=None, bool replace=False)
egg_name (self)
__repr__ (self)
__str__ (self)
__getattr__ (self, attr)
__dir__ (self)
from_filename (cls, StrPath filename, _MetadataType metadata=None, **int kw)
as_requirement (self)
_ResolvedEntryPoint load_entry_point (self, str group, str name)
dict[str, dict[str, EntryPoint]] get_entry_map (self, None group=None)
dict[str, EntryPoint] get_entry_map (self, str group)
get_entry_map (self, str|None group=None)
get_entry_info (self, str group, str name)
insert_on (self, list[str] path, loc=None, bool replace=False)
check_version_conflict (self)
has_version (self)
clone (self, **str|int|IResourceProvider|None kw)
extras (self)
Public Attributes
project_name = safe_name(project_name or 'Unknown')
py_version = py_version
platform = platform
location = location
precedence = precedence
str key
hashcmp
parsed_version
Static Public Attributes
str PKG_INFO = 'PKG-INFO'
Protected Member Functions
_reload_version (self)
_forgiving_parsed_version (self)
_dep_map (self)
_build_dep_map (self)
_get_metadata_path_for_display (self, name)
_get_metadata (self, name)
_get_version (self)
Static Protected Member Functions
_filter_extras (dict[str|None, list[Requirement]] dm)
Protected Attributes
_version = safe_version(version)
_provider = metadata or empty_provider
_forgiving_parsed_version
_key = self.project_name.lower()
_parsed_version = parse_version(self.version)
_ep_map
Detailed Description
Wrap an actual or potential sys.path entry w/metadata
Definition at line 2871 of file __init__.py.
Constructor & Destructor Documentation
__init__()
pip._vendor.pkg_resources.Distribution.__init__ (self, str | None location = None, _MetadataType metadata = None, str | None project_name = None, str | None version = None, str | None py_version = PY_MAJOR, str | None platform = None, int precedence = EGG_DIST)
Definition at line 2876 of file __init__.py.
    ):
        self.project_name = safe_name(project_name or 'Unknown')
        if version is not None:
            self._version = safe_version(version)
        self.py_version = py_version
        self.platform = platform
        self.location = location
        self.precedence = precedence
        self._provider = metadata or empty_provider
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
__dir__()
pip._vendor.pkg_resources.Distribution.__dir__ (self)
Definition at line 3150 of file __init__.py.
    def __dir__(self):
        return list(
            set(super().__dir__())
            | set(attr for attr in self._provider.__dir__() if not attr.startswith('_'))
        )
__eq__()
pip._vendor.pkg_resources.Distribution.__eq__ (self, object other)
Definition at line 2952 of file __init__.py.
    def __eq__(self, other: object):
        if not isinstance(other, self.__class__):
            # It's not a Distribution, so they are not equal
            return False
        return self.hashcmp == other.hashcmp
Referenced by dotenv.variables.Atom.__ne__(), pip._vendor.urllib3._collections.HTTPHeaderDict.__ne__(), responses.BaseResponse.__ne__(), and urllib3._collections.HTTPHeaderDict.__ne__().
__ge__()
pip._vendor.pkg_resources.Distribution.__ge__ (self, Distribution other)
Definition at line 2949 of file __init__.py.
    def __ge__(self, other: Distribution):
        return self.hashcmp >= other.hashcmp
__getattr__()
pip._vendor.pkg_resources.Distribution.__getattr__ (self, attr)
Delegate all unrecognized public attributes to .metadata provider
Definition at line 3144 of file __init__.py.
    def __getattr__(self, attr):
        """Delegate all unrecognized public attributes to .metadata provider"""
        if attr.startswith('_'):
            raise AttributeError(attr)
        return getattr(self._provider, attr)
__gt__()
pip._vendor.pkg_resources.Distribution.__gt__ (self, Distribution other)
Definition at line 2946 of file __init__.py.
    def __gt__(self, other: Distribution):
        return self.hashcmp > other.hashcmp
__hash__()
pip._vendor.pkg_resources.Distribution.__hash__ (self)
Definition at line 2937 of file __init__.py.
    def __hash__(self):
        return hash(self.hashcmp)
Referenced by pip._vendor.rich.style.Style.__eq__(), and pip._vendor.rich.style.Style.__ne__().
__le__()
pip._vendor.pkg_resources.Distribution.__le__ (self, Distribution other)
Definition at line 2943 of file __init__.py.
    def __le__(self, other: Distribution):
        return self.hashcmp <= other.hashcmp
__lt__()
pip._vendor.pkg_resources.Distribution.__lt__ (self, Distribution other)
Definition at line 2940 of file __init__.py.
    def __lt__(self, other: Distribution):
        return self.hashcmp < other.hashcmp
__ne__()
pip._vendor.pkg_resources.Distribution.__ne__ (self, object other)
Definition at line 2958 of file __init__.py.
    def __ne__(self, other: object):
        return not self == other
__repr__()
pip._vendor.pkg_resources.Distribution.__repr__ (self)
Definition at line 3130 of file __init__.py.
    def __repr__(self):
        if self.location:
            return "%s (%s)" % (self, self.location)
        else:
            return str(self)
__str__()
pip._vendor.pkg_resources.Distribution.__str__ (self)
Definition at line 3136 of file __init__.py.
    def __str__(self):
        try:
            version = getattr(self, 'version', None)
        except ValueError:
            version = None
        version = version or "[unknown version]"
        return "%s %s" % (self.project_name, version)
_build_dep_map()
pip._vendor.pkg_resources.Distribution._build_dep_map (self) protected
Definition at line 3061 of file __init__.py.
    def _build_dep_map(self):
        dm = {}
        for name in 'requires.txt', 'depends.txt':
            for extra, reqs in split_sections(self._get_metadata(name)):
                dm.setdefault(extra, []).extend(parse_requirements(reqs))
        return dm
_dep_map()
pip._vendor.pkg_resources.Distribution._dep_map (self) protected
A map of extra to its list of (direct) requirements
for this distribution, including the null extra.
Reimplemented in pip._vendor.pkg_resources.DistInfoDistribution.
Definition at line 3029 of file __init__.py.
    def _dep_map(self):
        """
        A map of extra to its list of (direct) requirements
        for this distribution, including the null extra.
        """
        try:
            return self.__dep_map
        except AttributeError:
            self.__dep_map = self._filter_extras(self._build_dep_map())
        return self.__dep_map
_filter_extras()
pip._vendor.pkg_resources.Distribution._filter_extras (dict[str | None, list[Requirement]] dm) static protected
Given a mapping of extras to dependencies, strip off
environment markers and filter out any dependencies
not matching the markers.
Definition at line 3041 of file __init__.py.
    def _filter_extras(dm: dict[str | None, list[Requirement]]):
        """
        Given a mapping of extras to dependencies, strip off
        environment markers and filter out any dependencies
        not matching the markers.
        """
        for extra in list(filter(None, dm)):
            new_extra: str | None = extra
            reqs = dm.pop(extra)
            new_extra, _, marker = extra.partition(':')
            fails_marker = marker and (
                invalid_marker(marker) or not evaluate_marker(marker)
            )
            if fails_marker:
                reqs = []
            new_extra = safe_extra(new_extra) or None
            dm.setdefault(new_extra, []).extend(reqs)
        return dm
_forgiving_parsed_version()
pip._vendor.pkg_resources.Distribution._forgiving_parsed_version (self) protected
Definition at line 2988 of file __init__.py.
    def _forgiving_parsed_version(self):
        try:
            return self.parsed_version
        except _packaging_version.InvalidVersion as ex:
            self._parsed_version = parse_version(_forgiving_version(self.version))
            notes = "\n".join(getattr(ex, "__notes__", []))  # PEP 678
            msg = f"""!!\n\n
            *************************************************************************
            {str(ex)}\n{notes}
            This is a long overdue deprecation.
            For the time being, `pkg_resources` will use `{self._parsed_version}`
            as a replacement to avoid breaking existing environments,
            but no future compatibility is guaranteed.
            If you maintain package {self.project_name} you should implement
            the relevant changes to adequate the project to PEP 440 immediately.
            *************************************************************************
            \n\n!!
            """
            warnings.warn(msg, DeprecationWarning)
            return self._parsed_version
_get_metadata()
pip._vendor.pkg_resources.Distribution._get_metadata (self, name) protected
Definition at line 3099 of file __init__.py.
    def _get_metadata(self, name):
        if self.has_metadata(name):
            yield from self.get_metadata_lines(name)
_get_metadata_path_for_display()
pip._vendor.pkg_resources.Distribution._get_metadata_path_for_display (self, name) protected
Return the path to the given metadata file, if available.
Definition at line 3082 of file __init__.py.
    def _get_metadata_path_for_display(self, name):
        """
        Return the path to the given metadata file, if available.
        """
        try:
            # We need to access _get_metadata_path() on the provider object
            # directly rather than through this class's __getattr__()
            # since _get_metadata_path() is marked private.
            path = self._provider._get_metadata_path(name)
        # Handle exceptions e.g. in case the distribution's metadata
        # provider doesn't support _get_metadata_path().
        except Exception:
            return '[could not detect]'
        return path
_get_version()
pip._vendor.pkg_resources.Distribution._get_version (self) protected
Definition at line 3103 of file __init__.py.
    def _get_version(self):
        lines = self._get_metadata(self.PKG_INFO)
        return _version_from_file(lines)
_reload_version()
pip._vendor.pkg_resources.Distribution._reload_version (self) protected
Reimplemented in pip._vendor.pkg_resources.EggInfoDistribution.
Definition at line 2923 of file __init__.py.
    def _reload_version(self):
        return self
activate()
pip._vendor.pkg_resources.Distribution.activate (self, list[str] | None path = None, bool replace = False)
Ensure distribution is importable on `path` (default=sys.path)
Definition at line 3107 of file __init__.py.
    def activate(self, path: list[str] | None = None, replace: bool = False):
        """Ensure distribution is importable on `path` (default=sys.path)"""
        if path is None:
            path = sys.path
        self.insert_on(path, replace=replace)
        if path is sys.path and self.location is not None:
            fixup_namespace_packages(self.location)
            for pkg in self._get_metadata('namespace_packages.txt'):
                if pkg in sys.modules:
                    declare_namespace(pkg)
as_requirement()
pip._vendor.pkg_resources.Distribution.as_requirement (self)
Return a ``Requirement`` that matches this distribution exactly
Definition at line 3167 of file __init__.py.
    def as_requirement(self):
        """Return a ``Requirement`` that matches this distribution exactly"""
        if isinstance(self.parsed_version, _packaging_version.Version):
            spec = "%s==%s" % (self.project_name, self.parsed_version)
        else:
            spec = "%s===%s" % (self.project_name, self.parsed_version)
        return Requirement.parse(spec)
check_version_conflict()
pip._vendor.pkg_resources.Distribution.check_version_conflict (self)
Definition at line 3275 of file __init__.py.
    def check_version_conflict(self):
        if self.key == 'setuptools':
            # ignore the inevitable setuptools self-conflicts  :(
            return
        nsp = dict.fromkeys(self._get_metadata('namespace_packages.txt'))
        loc = normalize_path(self.location)
        for modname in self._get_metadata('top_level.txt'):
            if (
                modname not in sys.modules
                or modname in nsp
                or modname in _namespace_packages
            ):
                continue
            if modname in ('pkg_resources', 'setuptools', 'site'):
                continue
            fn = getattr(sys.modules[modname], '__file__', None)
            if fn and (
                normalize_path(fn).startswith(loc) or fn.startswith(self.location)
            ):
                continue
            issue_warning(
                "Module %s was already imported from %s, but %s is being added"
                " to sys.path" % (modname, fn, self.location),
            )
clone()
pip._vendor.pkg_resources.Distribution.clone (self, **str | int | IResourceProvider | None kw)
Copy this distribution, substituting in any changed keyword args
Definition at line 3312 of file __init__.py.
    def clone(self, **kw: str | int | IResourceProvider | None):
        """Copy this distribution, substituting in any changed keyword args"""
        names = 'project_name version py_version platform location precedence'
        for attr in names.split():
            kw.setdefault(attr, getattr(self, attr, None))
        kw.setdefault('metadata', self._provider)
        # Unsafely unpacking. But keeping **kw for backwards and subclassing compatibility
        return self.__class__(**kw)  # type:ignore[arg-type]
egg_name()
pip._vendor.pkg_resources.Distribution.egg_name (self)
Return what this distribution's standard .egg filename should be
Definition at line 3118 of file __init__.py.
    def egg_name(self):
        """Return what this distribution's standard .egg filename should be"""
        filename = "%s-%s-py%s" % (
            to_filename(self.project_name),
            to_filename(self.version),
            self.py_version or PY_MAJOR,
        )
        if self.platform:
            filename += '-' + self.platform
        return filename
extras()
pip._vendor.pkg_resources.Distribution.extras (self)
Definition at line 3322 of file __init__.py.
    def extras(self):
        return [dep for dep in self._dep_map if dep]
from_filename()
pip._vendor.pkg_resources.Distribution.from_filename (cls, StrPath filename, _MetadataType metadata = None, **int kw)
Definition at line 3157 of file __init__.py.
    ):
        return cls.from_location(
            _normalize_cached(filename), os.path.basename(filename), metadata, **kw
        )
from_location()
Distribution pip._vendor.pkg_resources.Distribution.from_location (cls, str location, StrPath basename, _MetadataType metadata = None, **int kw)
Definition at line 2896 of file __init__.py.
    ) -> Distribution:
        project_name, version, py_version, platform = [None] * 4
        basename, ext = os.path.splitext(basename)
        if ext.lower() in _distributionImpl:
            cls = _distributionImpl[ext.lower()]
            match = EGG_NAME(basename)
            if match:
                project_name, version, py_version, platform = match.group(
                    'name', 'ver', 'pyver', 'plat'
                )
        return cls(
            location,
            metadata,
            project_name=project_name,
            version=version,
            py_version=py_version,
            platform=platform,
            **kw,
        )._reload_version()
get_entry_info()
pip._vendor.pkg_resources.Distribution.get_entry_info (self, str group, str name)
Return the EntryPoint object for `group`+`name`, or ``None``
Definition at line 3197 of file __init__.py.
    def get_entry_info(self, group: str, name: str):
        """Return the EntryPoint object for `group`+`name`, or ``None``"""
        return self.get_entry_map(group).get(name)
get_entry_map() [1/3]
dict[str, dict[str, EntryPoint]] pip._vendor.pkg_resources.Distribution.get_entry_map (self, None group = None)
Definition at line 3184 of file __init__.py.
    def get_entry_map(self, group: None = None) -> dict[str, dict[str, EntryPoint]]: ...
get_entry_map() [2/3]
dict[str, EntryPoint] pip._vendor.pkg_resources.Distribution.get_entry_map (self, str group)
Definition at line 3186 of file __init__.py.
    def get_entry_map(self, group: str) -> dict[str, EntryPoint]: ...
get_entry_map() [3/3]
pip._vendor.pkg_resources.Distribution.get_entry_map (self, str | None group = None)
Return the entry point map for `group`, or the full entry map
Definition at line 3187 of file __init__.py.
    def get_entry_map(self, group: str | None = None):
        """Return the entry point map for `group`, or the full entry map"""
        if not hasattr(self, "_ep_map"):
            self._ep_map = EntryPoint.parse_map(
                self._get_metadata('entry_points.txt'), self
            )
        if group is not None:
            return self._ep_map.get(group, {})
        return self._ep_map
has_version()
pip._vendor.pkg_resources.Distribution.has_version (self)
Definition at line 3301 of file __init__.py.
    def has_version(self):
        try:
            self.version
        except ValueError:
            issue_warning("Unbuilt egg for " + repr(self))
            return False
        except SystemError:
            # TODO: remove this except clause when python/cpython#103632 is fixed.
            return False
        return True
hashcmp()
pip._vendor.pkg_resources.Distribution.hashcmp (self)
Definition at line 2927 of file __init__.py.
    def hashcmp(self):
        return (
            self._forgiving_parsed_version,
            self.precedence,
            self.key,
            self.location,
            self.py_version or '',
            self.platform or '',
        )
insert_on()
pip._vendor.pkg_resources.Distribution.insert_on (self, list[str] path, loc = None, bool replace = False)
Ensure self.location is on path
If replace=False (default):
    - If location is already in path anywhere, do nothing.
    - Else:
      - If it's an egg and its parent directory is on path,
        insert just ahead of the parent.
      - Else: add to the end of path.
If replace=True:
    - If location is already on path anywhere (not eggs)
      or higher priority than its parent (eggs)
      do nothing.
    - Else:
      - If it's an egg and its parent directory is on path,
        insert just ahead of the parent,
        removing any lower-priority entries.
      - Else: add it to the front of path.
Definition at line 3202 of file __init__.py.
    ):
        """Ensure self.location is on path
        If replace=False (default):
            - If location is already in path anywhere, do nothing.
            - Else:
              - If it's an egg and its parent directory is on path,
                insert just ahead of the parent.
              - Else: add to the end of path.
        If replace=True:
            - If location is already on path anywhere (not eggs)
              or higher priority than its parent (eggs)
              do nothing.
            - Else:
              - If it's an egg and its parent directory is on path,
                insert just ahead of the parent,
                removing any lower-priority entries.
              - Else: add it to the front of path.
        """
        loc = loc or self.location
        if not loc:
            return
        nloc = _normalize_cached(loc)
        bdir = os.path.dirname(nloc)
        npath = [(p and _normalize_cached(p) or p) for p in path]
        for p, item in enumerate(npath):
            if item == nloc:
                if replace:
                    break
                else:
                    # don't modify path (even removing duplicates) if
                    # found and not replace
                    return
            elif item == bdir and self.precedence == EGG_DIST:
                # if it's an .egg, give it precedence over its directory
                # UNLESS it's already been added to sys.path and replace=False
                if (not replace) and nloc in npath[p:]:
                    return
                if path is sys.path:
                    self.check_version_conflict()
                path.insert(p, loc)
                npath.insert(p, nloc)
                break
        else:
            if path is sys.path:
                self.check_version_conflict()
            if replace:
                path.insert(0, loc)
            else:
                path.append(loc)
            return
        # p is the spot where we found or inserted loc; now remove duplicates
        while True:
            try:
                np = npath.index(nloc, p + 1)
            except ValueError:
                break
            else:
                del npath[np], path[np]
                # ha!
                p = np
        return
key()
pip._vendor.pkg_resources.Distribution.key (self)
Definition at line 2966 of file __init__.py.
    def key(self):
        try:
            return self._key
        except AttributeError:
            self._key = key = self.project_name.lower()
            return key
load_entry_point()
_ResolvedEntryPoint pip._vendor.pkg_resources.Distribution.load_entry_point (self, str group, str name)
Return the `name` entry point of `group` or raise ImportError
Definition at line 3176 of file __init__.py.
    def load_entry_point(self, group: str, name: str) -> _ResolvedEntryPoint:
        """Return the `name` entry point of `group` or raise ImportError"""
        ep = self.get_entry_info(group, name)
        if ep is None:
            raise ImportError("Entry point %r not found" % ((group, name),))
        return ep.load()
parsed_version()
pip._vendor.pkg_resources.Distribution.parsed_version (self)
Definition at line 2974 of file __init__.py.
    def parsed_version(self):
        if not hasattr(self, "_parsed_version"):
            try:
                self._parsed_version = parse_version(self.version)
            except _packaging_version.InvalidVersion as ex:
                info = f"(package: {self.project_name})"
                if hasattr(ex, "add_note"):
                    ex.add_note(info)  # PEP 678
                    raise
                raise _packaging_version.InvalidVersion(f"{str(ex)} {info}") from None
        return self._parsed_version
requires()
pip._vendor.pkg_resources.Distribution.requires (self, Iterable[str] extras = ())
List of Requirements needed for this distro if `extras` are used
Definition at line 3068 of file __init__.py.
    def requires(self, extras: Iterable[str] = ()):
        """List of Requirements needed for this distro if `extras` are used"""
        dm = self._dep_map
        deps: list[Requirement] = []
        deps.extend(dm.get(None, ()))
        for ext in extras:
            try:
                deps.extend(dm[safe_extra(ext)])
            except KeyError as e:
                raise UnknownExtra(
                    "%s has no such extra feature %r" % (self, ext)
                ) from e
        return deps
version()
pip._vendor.pkg_resources.Distribution.version (self)
Definition at line 3014 of file __init__.py.
    def version(self):
        try:
            return self._version
        except AttributeError as e:
            version = self._get_version()
            if version is None:
                path = self._get_metadata_path_for_display(self.PKG_INFO)
                msg = ("Missing 'Version:' header and/or {} file at path: {}").format(
                    self.PKG_INFO, path
                )
                raise ValueError(msg, self) from e
            return version
Referenced by pip._vendor.urllib3.contrib.securetransport.WrappedSocket._custom_validate().
Member Data Documentation
_ep_map
pip._vendor.pkg_resources.Distribution._ep_map protected
Initial value:
=  EntryPoint.parse_map(
                self._get_metadata('entry_points.txt'), self
            )
Definition at line 3190 of file __init__.py.
_forgiving_parsed_version
pip._vendor.pkg_resources.Distribution._forgiving_parsed_version protected
Definition at line 2929 of file __init__.py.
_key
pip._vendor.pkg_resources.Distribution._key = self.project_name.lower() protected
Definition at line 2970 of file __init__.py.
_parsed_version
pip._vendor.pkg_resources.Distribution._parsed_version = parse_version(self.version) protected
Definition at line 2977 of file __init__.py.
_provider
pip._vendor.pkg_resources.Distribution._provider = metadata or empty_provider protected
Definition at line 2893 of file __init__.py.
_version
pip._vendor.pkg_resources.Distribution._version = safe_version(version) protected
Definition at line 2888 of file __init__.py.
hashcmp
pip._vendor.pkg_resources.Distribution.hashcmp
Definition at line 2938 of file __init__.py.
key
str pip._vendor.pkg_resources.Distribution.key
Definition at line 2931 of file __init__.py.
Referenced by tomlkit.items.SingleKey.__eq__(), tomlkit.items.SingleKey.__hash__(), and pip._internal.self_outdated_check.SelfCheckState.set().
location
pip._vendor.pkg_resources.Distribution.location = location
Definition at line 2891 of file __init__.py.
Referenced by pip._internal.metadata.base.BaseDistribution._iter_declared_entries_from_legacy(), pip._internal.metadata.base.BaseDistribution.editable_project_location(), and pip._internal.metadata.base.BaseDistribution.installed_as_egg().
parsed_version
pip._vendor.pkg_resources.Distribution.parsed_version
Definition at line 3169 of file __init__.py.
PKG_INFO
str pip._vendor.pkg_resources.Distribution.PKG_INFO = 'PKG-INFO' static
Definition at line 2874 of file __init__.py.
platform
pip._vendor.pkg_resources.Distribution.platform = platform
Definition at line 2890 of file __init__.py.
precedence
pip._vendor.pkg_resources.Distribution.precedence = precedence
Definition at line 2892 of file __init__.py.
project_name
pip._vendor.pkg_resources.Distribution.project_name = safe_name(project_name or 'Unknown')
Definition at line 2886 of file __init__.py.
Referenced by pip._internal.resolution.resolvelib.candidates._InstallRequirementBackedCandidate.name(), and pip._internal.resolution.resolvelib.candidates.AlreadyInstalledCandidate.name().
py_version
pip._vendor.pkg_resources.Distribution.py_version = py_version
Definition at line 2889 of file __init__.py.
Referenced by pylint.message.message_definition_store.MessageDefinitionStore.find_emittable_messages().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/pkg_resources/__init__.py