Read&Watch: _virtualenv._Finder Class Reference
_virtualenv._Finder Class Reference
Public Member Functions
find_spec (self, fullname, path, target=None)
Static Public Member Functions
exec_module (old, module)
load_module (old, name)
Static Public Attributes
fullname = None
list lock = []
Detailed Description
A meta path finder that allows patching the imported distutils modules.
Definition at line 42 of file _virtualenv.py.
Member Function Documentation
exec_module()
_virtualenv._Finder.exec_module (old, module) static
Definition at line 90 of file _virtualenv.py.
    def exec_module(old, module):
        old(module)
        if module.__name__ in _DISTUTILS_PATCH:
            patch_dist(module)
References _virtualenv.patch_dist().
Referenced by find_spec().
find_spec()
_virtualenv._Finder.find_spec (self, fullname, path, target = None)
Definition at line 52 of file _virtualenv.py.
    def find_spec(self, fullname, path, target=None):  # noqa: ARG002
        if fullname in _DISTUTILS_PATCH and self.fullname is None:  # noqa: PLR1702
            # initialize lock[0] lazily
            if len(self.lock) == 0:
                import threading  # noqa: PLC0415
                lock = threading.Lock()
                # there is possibility that two threads T1 and T2 are simultaneously running into find_spec,
                # observing .lock as empty, and further going into hereby initialization. However due to the GIL,
                # list.append() operation is atomic and this way only one of the threads will "win" to put the lock
                # - that every thread will use - into .lock[0].
                # https://docs.python.org/3/faq/library.html#what-kinds-of-global-value-mutation-are-thread-safe
                self.lock.append(lock)
            from functools import partial  # noqa: PLC0415
            from importlib.util import find_spec  # noqa: PLC0415
            with self.lock[0]:
                self.fullname = fullname
                try:
                    spec = find_spec(fullname, path)
                    if spec is not None:
                        # https://www.python.org/dev/peps/pep-0451/#how-loading-will-work
                        is_new_api = hasattr(spec.loader, "exec_module")
                        func_name = "exec_module" if is_new_api else "load_module"
                        old = getattr(spec.loader, func_name)
                        func = self.exec_module if is_new_api else self.load_module
                        if old is not func:
                            try:  # noqa: SIM105
                                setattr(spec.loader, func_name, partial(func, old))
                            except AttributeError:
                                pass  # C-Extension loaders are r/o such as zipimporter with <3.7
                        return spec
                finally:
                    self.fullname = None
        return None
References exec_module(), find_spec(), fullname, load_module(), and lock.
Referenced by find_spec().
load_module()
_virtualenv._Finder.load_module (old, name) static
Definition at line 96 of file _virtualenv.py.
    def load_module(old, name):
        module = old(name)
        if module.__name__ in _DISTUTILS_PATCH:
            patch_dist(module)
        return module
References _virtualenv.patch_dist().
Referenced by pip._vendor.urllib3.packages.six._SixMetaPathImporter.create_module(), six._SixMetaPathImporter.create_module(), and find_spec().
Member Data Documentation
fullname
_virtualenv._Finder.fullname = None static
Definition at line 45 of file _virtualenv.py.
Referenced by find_spec().
lock
_virtualenv._Finder.lock = [] static
Definition at line 50 of file _virtualenv.py.
Referenced by pip._vendor.urllib3._collections.RecentlyUsedContainer.__delitem__(), urllib3._collections.RecentlyUsedContainer.__delitem__(), urllib3.http2.connection._LockedObject.__enter__(), urllib3.http2.connection._LockedObject.__exit__(), pip._vendor.urllib3._collections.RecentlyUsedContainer.__getitem__(), urllib3._collections.RecentlyUsedContainer.__getitem__(), pip._vendor.urllib3._collections.RecentlyUsedContainer.__len__(), urllib3._collections.RecentlyUsedContainer.__len__(), pip._vendor.urllib3._collections.RecentlyUsedContainer.__setitem__(), urllib3._collections.RecentlyUsedContainer.__setitem__(), django.dispatch.dispatcher.Signal._live_receivers(), pip._vendor.urllib3._collections.RecentlyUsedContainer.clear(), urllib3._collections.RecentlyUsedContainer.clear(), pip._vendor.cachecontrol.cache.DictCache.delete(), django.dispatch.dispatcher.Signal.disconnect(), find_spec(), pip._vendor.urllib3._collections.RecentlyUsedContainer.keys(), urllib3._collections.RecentlyUsedContainer.keys(), and pip._vendor.cachecontrol.cache.DictCache.set().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/_virtualenv.py