Read&Watch: django.contrib.auth.backends.RemoteUserBackend Class Reference
django.contrib.auth.backends.RemoteUserBackend Class Reference
Public Member Functions
authenticate (self, request, remote_user)
clean_username (self, username)
configure_user (self, request, user, created=True)
Public Member Functions inherited from django.contrib.auth.backends.ModelBackend
user_can_authenticate (self, user)
get_user_permissions (self, user_obj, obj=None)
get_group_permissions (self, user_obj, obj=None)
get_all_permissions (self, user_obj, obj=None)
has_perm (self, user_obj, perm, obj=None)
has_module_perms (self, user_obj, app_label)
with_perm (self, perm, is_active=True, include_superusers=True, obj=None)
get_user (self, user_id)
Static Public Attributes
bool create_unknown_user = True
Additional Inherited Members
Protected Member Functions inherited from django.contrib.auth.backends.ModelBackend
_get_user_permissions (self, user_obj)
_get_group_permissions (self, user_obj)
_get_permissions (self, user_obj, obj, from_name)
Detailed Description
This backend is to be used in conjunction with the ``RemoteUserMiddleware``
found in the middleware module of this package, and is used when the server
is handling authentication outside of Django.
By default, the ``authenticate`` method creates ``User`` objects for
usernames that don't already exist in the database.  Subclasses can disable
this behavior by setting the ``create_unknown_user`` attribute to
``False``.
Definition at line 168 of file backends.py.
Member Function Documentation
authenticate()
django.contrib.auth.backends.RemoteUserBackend.authenticate (self, request, remote_user)
The username passed as ``remote_user`` is considered trusted. Return
the ``User`` object with the given username. Create a new ``User``
object if ``create_unknown_user`` is ``True``.
Return None if ``create_unknown_user`` is ``False`` and a ``User``
object with the given username is not found in the database.
Reimplemented from django.contrib.auth.backends.ModelBackend.
Definition at line 183 of file backends.py.
    def authenticate(self, request, remote_user):
        """
        The username passed as ``remote_user`` is considered trusted. Return
        the ``User`` object with the given username. Create a new ``User``
        object if ``create_unknown_user`` is ``True``.
        Return None if ``create_unknown_user`` is ``False`` and a ``User``
        object with the given username is not found in the database.
        """
        if not remote_user:
            return
        created = False
        user = None
        username = self.clean_username(remote_user)
        # Note that this could be accomplished in one try-except clause, but
        # instead we use get_or_create when creating unknown users since it has
        # built-in safeguards for multiple threads.
        if self.create_unknown_user:
            user, created = UserModel._default_manager.get_or_create(
                **{UserModel.USERNAME_FIELD: username}
            )
        else:
            try:
                user = UserModel._default_manager.get_by_natural_key(username)
            except UserModel.DoesNotExist:
                pass
        user = self.configure_user(request, user, created=created)
        return user if self.user_can_authenticate(user) else None
References clean_username(), configure_user(), create_unknown_user, and django.contrib.auth.backends.ModelBackend.user_can_authenticate().
clean_username()
django.contrib.auth.backends.RemoteUserBackend.clean_username (self, username)
Perform any cleaning on the "username" prior to using it to get or
create the user object.  Return the cleaned username.
By default, return the username unchanged.
Definition at line 213 of file backends.py.
    def clean_username(self, username):
        """
        Perform any cleaning on the "username" prior to using it to get or
        create the user object.  Return the cleaned username.
        By default, return the username unchanged.
        """
        return username
Referenced by authenticate(), and django.contrib.auth.middleware.RemoteUserMiddleware.process_request().
configure_user()
django.contrib.auth.backends.RemoteUserBackend.configure_user (self, request, user, created = True)
Configure a user and return the updated user.
By default, return the user unmodified.
Definition at line 222 of file backends.py.
    def configure_user(self, request, user, created=True):
        """
        Configure a user and return the updated user.
        By default, return the user unmodified.
        """
        return user
Referenced by authenticate().
Member Data Documentation
create_unknown_user
bool django.contrib.auth.backends.RemoteUserBackend.create_unknown_user = True static
Definition at line 181 of file backends.py.
Referenced by authenticate().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/auth/backends.py