Read&Watch: django.template.defaulttags.IfChangedNode Class Reference
django.template.defaulttags.IfChangedNode Class Reference
Public Member Functions
__init__ (self, nodelist_true, nodelist_false, *varlist)
render (self, context)
Public Member Functions inherited from django.template.base.Node
render_annotated (self, context)
get_nodes_by_type (self, nodetype)
Public Attributes
nodelist_true = nodelist_true
nodelist_false = nodelist_false
Protected Member Functions
_get_context_stack_frame (self, context)
Protected Attributes
_varlist = varlist
Additional Inherited Members
Static Public Attributes inherited from django.template.base.Node
bool must_be_first = False
tuple child_nodelists = ("nodelist",)
token = None
Detailed Description
Definition at line 253 of file defaulttags.py.
Constructor & Destructor Documentation
__init__()
django.template.defaulttags.IfChangedNode.__init__ (self, nodelist_true, nodelist_false, * varlist)
Definition at line 256 of file defaulttags.py.
    def __init__(self, nodelist_true, nodelist_false, *varlist):
        self.nodelist_true = nodelist_true
        self.nodelist_false = nodelist_false
        self._varlist = varlist
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
_get_context_stack_frame()
django.template.defaulttags.IfChangedNode._get_context_stack_frame (self, context) protected
Definition at line 286 of file defaulttags.py.
    def _get_context_stack_frame(self, context):
        # The Context object behaves like a stack where each template tag can
        # create a new scope. Find the place where to store the state to detect
        # changes.
        if "forloop" in context:
            # Ifchanged is bound to the local for loop.
            # When there is a loop-in-loop, the state is bound to the inner loop,
            # so it resets when the outer loop continues.
            return context["forloop"]
        else:
            # Using ifchanged outside loops. Effectively this is a no-op
            # because the state is associated with 'self'.
            return context.render_context
Referenced by render().
render()
django.template.defaulttags.IfChangedNode.render (self, context)
Return the node rendered as a string.
Reimplemented from django.template.base.Node.
Definition at line 261 of file defaulttags.py.
    def render(self, context):
        # Init state storage
        state_frame = self._get_context_stack_frame(context)
        state_frame.setdefault(self)
        nodelist_true_output = None
        if self._varlist:
            # Consider multiple parameters. This behaves like an OR evaluation
            # of the multiple variables.
            compare_to = [
                var.resolve(context, ignore_failures=True) for var in self._varlist
            ]
        else:
            # The "{% ifchanged %}" syntax (without any variables) compares
            # the rendered output.
            compare_to = nodelist_true_output = self.nodelist_true.render(context)
        if compare_to != state_frame[self]:
            state_frame[self] = compare_to
            # render true block if not already rendered
            return nodelist_true_output or self.nodelist_true.render(context)
        elif self.nodelist_false:
            return self.nodelist_false.render(context)
        return ""
References _get_context_stack_frame(), _varlist, nodelist_false, nodelist_true, and render().
Referenced by pip._vendor.rich.progress.ProgressColumn.__call__(), pip._vendor.rich.layout.Layout.__rich_console__(), pip._vendor.rich.spinner.Spinner.__rich_console__(), pip._vendor.rich.spinner.Spinner.__rich_measure__(), pip._vendor.rich.console.Console.log(), pip._vendor.rich.console.Console.print(), render(), django.templatetags.i18n.BlockTranslateNode.render(), pip._vendor.rich.console.Console.render(), pip._vendor.rich.console.Console.render_lines(), and pip._vendor.rich.console.Console.update_screen_lines().
Member Data Documentation
_varlist
django.template.defaulttags.IfChangedNode._varlist = varlist protected
Definition at line 259 of file defaulttags.py.
Referenced by render().
nodelist_false
django.template.defaulttags.IfChangedNode.nodelist_false = nodelist_false
Definition at line 258 of file defaulttags.py.
Referenced by render().
nodelist_true
django.template.defaulttags.IfChangedNode.nodelist_true = nodelist_true
Definition at line 257 of file defaulttags.py.
Referenced by render().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/template/defaulttags.py