Read&Watch: django.contrib.staticfiles.storage.ManifestFilesMixin Class Reference
django.contrib.staticfiles.storage.ManifestFilesMixin Class Reference
Public Member Functions
__init__ (self, *args, manifest_storage=None, **kwargs)
read_manifest (self)
load_manifest (self)
post_process (self, *args, **kwargs)
save_manifest (self)
stored_name (self, name)
Public Member Functions inherited from django.contrib.staticfiles.storage.HashedFilesMixin
__init__ (self, *args, **kwargs)
file_hash (self, name, content=None)
hashed_name (self, name, content=None, filename=None)
url (self, name, force=False)
url_converter (self, name, hashed_files, template=None)
clean_name (self, name)
hash_key (self, name)
Public Attributes
manifest_storage = manifest_storage
manifest_hash = self.load_manifest()
Public Attributes inherited from django.contrib.staticfiles.storage.HashedFilesMixin
dict hashed_files = {}
Static Public Attributes
str manifest_version = "1.1"
str manifest_name = "staticfiles.json"
bool manifest_strict = True
Static Public Attributes inherited from django.contrib.staticfiles.storage.HashedFilesMixin
str default_template = """url("%(url)s")"""
int max_post_process_passes = 5
bool support_js_module_import_aggregation = False
tuple patterns
bool keep_intermediate_files = True
Additional Inherited Members
Protected Member Functions inherited from django.contrib.staticfiles.storage.HashedFilesMixin
_url (self, hashed_name_func, name, force=False, hashed_files=None)
_post_process (self, paths, adjustable_paths, hashed_files)
_stored_name (self, name, hashed_files)
Protected Attributes inherited from django.contrib.staticfiles.storage.HashedFilesMixin
dict _patterns = {}
Static Protected Attributes inherited from django.contrib.staticfiles.storage.HashedFilesMixin
tuple _js_module_import_aggregation_patterns
Detailed Description
Definition at line 452 of file storage.py.
Constructor & Destructor Documentation
__init__()
django.contrib.staticfiles.storage.ManifestFilesMixin.__init__ (self, * args, manifest_storage = None, ** kwargs)
Definition at line 458 of file storage.py.
    def __init__(self, *args, manifest_storage=None, **kwargs):
        super().__init__(*args, **kwargs)
        if manifest_storage is None:
            manifest_storage = self
        self.manifest_storage = manifest_storage
        self.hashed_files, self.manifest_hash = self.load_manifest()
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Function Documentation
load_manifest()
django.contrib.staticfiles.storage.ManifestFilesMixin.load_manifest (self)
Definition at line 472 of file storage.py.
    def load_manifest(self):
        content = self.read_manifest()
        if content is None:
            return {}, ""
        try:
            stored = json.loads(content)
        except json.JSONDecodeError:
            pass
        else:
            version = stored.get("version")
            if version in ("1.0", "1.1"):
                return stored.get("paths", {}), stored.get("hash", "")
        raise ValueError(
            "Couldn't load manifest '%s' (version %s)"
            % (self.manifest_name, self.manifest_version)
        )
References manifest_name, manifest_version, and read_manifest().
post_process()
django.contrib.staticfiles.storage.ManifestFilesMixin.post_process (self, * paths, ** dry_run)
Post process the given dictionary of files (called from collectstatic).
Processing is actually two separate operations:
1. renaming files to include a hash of their content for cache-busting,
   and copying those files to the target storage.
2. adjusting files which contain references to other files so they
   refer to the cache-busting filenames.
If either of these are performed on a file, then that file is considered
post-processed.
Reimplemented from django.contrib.staticfiles.storage.HashedFilesMixin.
Definition at line 489 of file storage.py.
    def post_process(self, *args, **kwargs):
        self.hashed_files = {}
        yield from super().post_process(*args, **kwargs)
        if not kwargs.get("dry_run"):
            self.save_manifest()
References django.contrib.staticfiles.storage.HashedFilesMixin.hashed_files, post_process(), and save_manifest().
Referenced by post_process().
read_manifest()
django.contrib.staticfiles.storage.ManifestFilesMixin.read_manifest (self)
Definition at line 465 of file storage.py.
    def read_manifest(self):
        try:
            with self.manifest_storage.open(self.manifest_name) as manifest:
                return manifest.read().decode()
        except FileNotFoundError:
            return None
References manifest_name, and manifest_storage.
Referenced by load_manifest().
save_manifest()
django.contrib.staticfiles.storage.ManifestFilesMixin.save_manifest (self)
Definition at line 495 of file storage.py.
    def save_manifest(self):
        self.manifest_hash = self.file_hash(
            None, ContentFile(json.dumps(sorted(self.hashed_files.items())).encode())
        )
        payload = {
            "paths": self.hashed_files,
            "version": self.manifest_version,
            "hash": self.manifest_hash,
        }
        if self.manifest_storage.exists(self.manifest_name):
            self.manifest_storage.delete(self.manifest_name)
        contents = json.dumps(payload).encode()
        self.manifest_storage._save(self.manifest_name, ContentFile(contents))
References django.contrib.staticfiles.storage.HashedFilesMixin.file_hash(), django.contrib.staticfiles.storage.HashedFilesMixin.hashed_files, manifest_hash, manifest_name, manifest_storage, and manifest_version.
Referenced by post_process().
stored_name()
django.contrib.staticfiles.storage.ManifestFilesMixin.stored_name (self, name)
Reimplemented from django.contrib.staticfiles.storage.HashedFilesMixin.
Definition at line 509 of file storage.py.
    def stored_name(self, name):
        parsed_name = urlsplit(unquote(name))
        clean_name = parsed_name.path.strip()
        hash_key = self.hash_key(clean_name)
        cache_name = self.hashed_files.get(hash_key)
        if cache_name is None:
            if self.manifest_strict:
                raise ValueError(
                    "Missing staticfiles manifest entry for '%s'" % clean_name
                )
            cache_name = self.clean_name(self.hashed_name(name))
        unparsed_name = list(parsed_name)
        unparsed_name[2] = cache_name
        # Special casing for a @font-face hack, like url(myfont.eot?#iefix")
        # http://www.fontspring.com/blog/the-new-bulletproof-font-face-syntax
        if "?#" in name and not unparsed_name[3]:
            unparsed_name[2] += "?"
        return urlunsplit(unparsed_name)
References django.contrib.staticfiles.storage.HashedFilesMixin.clean_name(), django.contrib.staticfiles.storage.HashedFilesMixin.hash_key(), django.contrib.staticfiles.storage.HashedFilesMixin.hashed_files, django.contrib.staticfiles.storage.HashedFilesMixin.hashed_name(), and manifest_strict.
Member Data Documentation
manifest_hash
django.contrib.staticfiles.storage.ManifestFilesMixin.manifest_hash = self.load_manifest()
Definition at line 463 of file storage.py.
Referenced by save_manifest().
manifest_name
django.contrib.staticfiles.storage.ManifestFilesMixin.manifest_name = "staticfiles.json" static
Definition at line 454 of file storage.py.
Referenced by load_manifest(), read_manifest(), and save_manifest().
manifest_storage
django.contrib.staticfiles.storage.ManifestFilesMixin.manifest_storage = manifest_storage
Definition at line 462 of file storage.py.
Referenced by read_manifest(), and save_manifest().
manifest_strict
bool django.contrib.staticfiles.storage.ManifestFilesMixin.manifest_strict = True static
Definition at line 455 of file storage.py.
Referenced by stored_name().
manifest_version
django.contrib.staticfiles.storage.ManifestFilesMixin.manifest_version = "1.1" static
Definition at line 453 of file storage.py.
Referenced by load_manifest(), and save_manifest().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/staticfiles/storage.py