Read&Watch: django.forms.renderers.BaseRenderer Class Reference
django.forms.renderers.BaseRenderer Class Reference
Public Member Functions
get_template (self, template_name)
render (self, template_name, context, request=None)
Static Public Attributes
str form_template_name = "django/forms/div.html"
str formset_template_name = "django/forms/formsets/div.html"
str field_template_name = "django/forms/field.html"
Detailed Description
Definition at line 19 of file renderers.py.
Member Function Documentation
get_template()
django.forms.renderers.BaseRenderer.get_template (self, template_name)
Reimplemented in django.forms.renderers.TemplatesSetting.
Definition at line 24 of file renderers.py.
    def get_template(self, template_name):
        raise NotImplementedError("subclasses must implement get_template()")
Referenced by render(), django.template.engine.Engine.render_to_string(), and django.template.engine.Engine.select_template().
render()
django.forms.renderers.BaseRenderer.render (self, template_name, context, request = None)
Definition at line 27 of file renderers.py.
    def render(self, template_name, context, request=None):
        template = self.get_template(template_name)
        return template.render(context, request=request).strip()
References get_template().
Referenced by pip._vendor.rich.progress.ProgressColumn.__call__(), pip._vendor.rich.layout.Layout.__rich_console__(), pip._vendor.rich.spinner.Spinner.__rich_console__(), pip._vendor.rich.spinner.Spinner.__rich_measure__(), django.forms.widgets.Media.__str__(), django.forms.utils.RenderableFieldMixin.as_field_group(), pip._vendor.rich.console.Console.log(), pip._vendor.rich.console.Console.print(), django.templatetags.i18n.BlockTranslateNode.render(), pip._vendor.rich.console.Console.render(), pip._vendor.rich.console.Console.render_lines(), and pip._vendor.rich.console.Console.update_screen_lines().
Member Data Documentation
field_template_name
str django.forms.renderers.BaseRenderer.field_template_name = "django/forms/field.html" static
Definition at line 22 of file renderers.py.
form_template_name
str django.forms.renderers.BaseRenderer.form_template_name = "django/forms/div.html" static
Definition at line 20 of file renderers.py.
formset_template_name
str django.forms.renderers.BaseRenderer.formset_template_name = "django/forms/formsets/div.html" static
Definition at line 21 of file renderers.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/forms/renderers.py