Read&Watch: django.contrib.staticfiles.management.commands.runserver.Command Class Reference
django.contrib.staticfiles.management.commands.runserver.Command Class Reference
Public Member Functions
add_arguments (self, parser)
get_handler (self, *args, **options)
Static Public Attributes
tuple help
Detailed Description
Definition at line 6 of file runserver.py.
Member Function Documentation
add_arguments()
django.contrib.staticfiles.management.commands.runserver.Command.add_arguments (self, parser)
Definition at line 11 of file runserver.py.
    def add_arguments(self, parser):
        super().add_arguments(parser)
        parser.add_argument(
            "--nostatic",
            action="store_false",
            dest="use_static_handler",
            help="Tells Django to NOT automatically serve static files at STATIC_URL.",
        )
        parser.add_argument(
            "--insecure",
            action="store_true",
            dest="insecure_serving",
            help="Allows serving static files even if DEBUG is False.",
        )
References add_arguments().
Referenced by add_arguments(), and django.core.management.base.BaseCommand.create_parser().
get_handler()
django.contrib.staticfiles.management.commands.runserver.Command.get_handler (self, * args, ** options)
Return the static files serving handler wrapping the default handler,
if static files should be served. Otherwise return the default handler.
Definition at line 26 of file runserver.py.
    def get_handler(self, *args, **options):
        """
        Return the static files serving handler wrapping the default handler,
        if static files should be served. Otherwise return the default handler.
        """
        handler = super().get_handler(*args, **options)
        use_static_handler = options["use_static_handler"]
        insecure_serving = options["insecure_serving"]
        if use_static_handler and (settings.DEBUG or insecure_serving):
            return StaticFilesHandler(handler)
        return handler
References get_handler().
Referenced by get_handler(), and django.core.management.commands.runserver.Command.inner_run().
Member Data Documentation
help
tuple django.contrib.staticfiles.management.commands.runserver.Command.help static
Initial value:
=  (
        "Starts a lightweight web server for development and also serves static files."
    )
Definition at line 7 of file runserver.py.
Referenced by pip._vendor.rich._inspect.Inspect._get_formatted_doc(), django.core.management.base.BaseCommand.create_parser(), and pylint.pyreverse.main.Run.run().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/staticfiles/management/commands/runserver.py