Read&Watch: django.forms.fields.RegexField Class Reference
django.forms.fields.RegexField Class Reference
Public Member Functions
__init__ (self, regex, **kwargs)
Public Member Functions inherited from django.forms.fields.CharField
__init__ (self, *, max_length=None, min_length=None, strip=True, empty_value="", **kwargs)
to_python (self, value)
widget_attrs (self, widget)
Public Member Functions inherited from django.forms.fields.Field
__init__ (self, *, required=True, widget=None, label=None, initial=None, help_text="", error_messages=None, show_hidden_initial=False, validators=(), localize=False, disabled=False, label_suffix=None, template_name=None)
prepare_value (self, value)
validate (self, value)
run_validators (self, value)
clean (self, value)
bound_data (self, data, initial)
has_changed (self, initial, data)
get_bound_field (self, form, field_name)
__deepcopy__ (self, memo)
Protected Member Functions
_get_regex (self)
_set_regex (self, regex)
Protected Member Functions inherited from django.forms.fields.Field
_clean_bound_field (self, bf)
Protected Attributes
_regex = regex
_regex_validator = validators.RegexValidator(regex=regex)
Properties
regex = property(_get_regex, _set_regex)
Additional Inherited Members
Public Attributes inherited from django.forms.fields.CharField
max_length = max_length
min_length = min_length
strip = strip
empty_value = empty_value
Public Attributes inherited from django.forms.fields.Field
required
label
initial = required, label, initial
show_hidden_initial = show_hidden_initial
help_text = help_text
disabled = disabled
label_suffix = label_suffix
localize = localize
error_messages = messages
list validators = [*self.default_validators, *validators]
template_name = template_name
Static Public Attributes inherited from django.forms.fields.Field
widget = TextInput
tuple hidden_widget
list default_validators = []
dict default_error_messages
empty_values = list(validators.EMPTY_VALUES)
Detailed Description
Definition at line 592 of file fields.py.
Constructor & Destructor Documentation
__init__()
django.forms.fields.RegexField.__init__ (self, regex, ** kwargs)
regex can be either a string or a compiled regular expression object.
Definition at line 593 of file fields.py.
    def __init__(self, regex, **kwargs):
        """
        regex can be either a string or a compiled regular expression object.
        """
        kwargs.setdefault("strip", False)
        super().__init__(**kwargs)
        self._set_regex(regex)
References __init__(), and _set_regex().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Function Documentation
_get_regex()
django.forms.fields.RegexField._get_regex (self) protected
Definition at line 601 of file fields.py.
    def _get_regex(self):
        return self._regex
References _regex.
_set_regex()
django.forms.fields.RegexField._set_regex (self, regex) protected
Definition at line 604 of file fields.py.
    def _set_regex(self, regex):
        if isinstance(regex, str):
            regex = re.compile(regex)
        self._regex = regex
        if (
            hasattr(self, "_regex_validator")
            and self._regex_validator in self.validators
        ):
            self.validators.remove(self._regex_validator)
        self._regex_validator = validators.RegexValidator(regex=regex)
        self.validators.append(self._regex_validator)
Referenced by __init__().
Member Data Documentation
_regex
django.forms.fields.RegexField._regex = regex protected
Definition at line 607 of file fields.py.
Referenced by pip._vendor.packaging.specifiers.Specifier.__init__(), pip._vendor.packaging.version.Version.__init__(), django.urls.resolvers.RegexPattern.__str__(), django.urls.resolvers.RegexPattern._check_include_trailing_dollar(), django.urls.resolvers.CheckURLMixin._check_pattern_startswith_slash(), and _get_regex().
_regex_validator
django.forms.fields.RegexField._regex_validator = validators.RegexValidator(regex=regex) protected
Definition at line 612 of file fields.py.
Property Documentation
regex
django.forms.fields.RegexField.regex = property(_get_regex, _set_regex) static
Definition at line 616 of file fields.py.
Referenced by django.urls.resolvers.RegexPattern.match(), and django.urls.resolvers.RoutePattern.match().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/forms/fields.py