Read&Watch: astroid.exceptions.AstroidSyntaxError Class Reference
astroid.exceptions.AstroidSyntaxError Class Reference
Public Member Functions
None __init__ (self, str message, str|None modname, Exception error, str|None path, str|None source=None)
Public Member Functions inherited from astroid.exceptions.AstroidBuildingError
None __init__ (self, str message="Failed to import module {modname}.", str|None modname=None, Exception|None error=None, str|None source=None, str|None path=None, type|None cls=None, str|None class_repr=None, **Any kws)
Public Member Functions inherited from astroid.exceptions.AstroidError
None __init__ (self, str message="", **Any kws)
str __str__ (self)
Additional Inherited Members
Public Attributes inherited from astroid.exceptions.AstroidBuildingError
modname = modname
error = error
source = source
path = path
cls = cls
class_repr = class_repr
Public Attributes inherited from astroid.exceptions.AstroidError
message = message
Detailed Description
Exception class used when a module can't be parsed.
Definition at line 123 of file exceptions.py.
Constructor & Destructor Documentation
__init__()
None astroid.exceptions.AstroidSyntaxError.__init__ (self, str message, str | None modname, Exception error, str | None path, str | None source = None)
Definition at line 126 of file exceptions.py.
    ) -> None:
        super().__init__(message, modname, error, source, path)
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/astroid/exceptions.py