Read&Watch: django.contrib.gis.sitemaps.kml.KMLSitemap Class Reference
django.contrib.gis.sitemaps.kml.KMLSitemap Class Reference
Public Member Functions
__init__ (self, locations=None)
get_urls (self, page=1, site=None, protocol=None)
items (self)
location (self, obj)
Public Member Functions inherited from django.contrib.sitemaps.Sitemap
get_languages_for_item (self, item)
paginator (self)
get_protocol (self, protocol=None)
get_domain (self, site=None)
get_latest_lastmod (self)
Public Attributes
locations = self._build_kml_sources(locations)
Public Attributes inherited from django.contrib.sitemaps.Sitemap
lastmod
latest_lastmod = latest_lastmod
Static Public Attributes
str geo_format = "kml"
Static Public Attributes inherited from django.contrib.sitemaps.Sitemap
int limit = 50000
protocol = None
bool i18n = False
languages = None
bool alternates = False
bool x_default = False
Protected Member Functions
_build_kml_sources (self, sources)
Protected Member Functions inherited from django.contrib.sitemaps.Sitemap
_get (self, name, item, default=None)
_languages (self)
_items (self)
_location (self, item, force_lang_code=None)
_urls (self, page, protocol, domain)
Detailed Description
A minimal hook to produce KML sitemaps.
Definition at line 8 of file kml.py.
Constructor & Destructor Documentation
__init__()
django.contrib.gis.sitemaps.kml.KMLSitemap.__init__ (self, locations = None)
Definition at line 15 of file kml.py.
    def __init__(self, locations=None):
        # If no locations specified, then we try to build for
        # every model in installed applications.
        self.locations = self._build_kml_sources(locations)
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
_build_kml_sources()
django.contrib.gis.sitemaps.kml.KMLSitemap._build_kml_sources (self, sources) protected
Go through the given sources and return a 3-tuple of the application
label, module name, and field name of every GeometryField encountered
in the sources.
If no sources are provided, then all models.
Definition at line 20 of file kml.py.
    def _build_kml_sources(self, sources):
        """
        Go through the given sources and return a 3-tuple of the application
        label, module name, and field name of every GeometryField encountered
        in the sources.
        If no sources are provided, then all models.
        """
        kml_sources = []
        if sources is None:
            sources = apps.get_models()
        for source in sources:
            if isinstance(source, models.base.ModelBase):
                for field in source._meta.fields:
                    if isinstance(field, GeometryField):
                        kml_sources.append(
                            (
                                source._meta.app_label,
                                source._meta.model_name,
                                field.name,
                            )
                        )
            elif isinstance(source, (list, tuple)):
                if len(source) != 3:
                    raise ValueError(
                        "Must specify a 3-tuple of (app_label, module_name, "
                        "field_name)."
                    )
                kml_sources.append(source)
            else:
                raise TypeError("KML Sources must be a model or a 3-tuple.")
        return kml_sources
get_urls()
django.contrib.gis.sitemaps.kml.KMLSitemap.get_urls (self, page = 1, site = None, protocol = None)
This method is overridden so the appropriate `geo_format` attribute
is placed on each URL element.
Reimplemented from django.contrib.sitemaps.Sitemap.
Definition at line 53 of file kml.py.
    def get_urls(self, page=1, site=None, protocol=None):
        """
        This method is overridden so the appropriate `geo_format` attribute
        is placed on each URL element.
        """
        urls = Sitemap.get_urls(self, page=page, site=site, protocol=protocol)
        for url in urls:
            url["geo_format"] = self.geo_format
        return urls
References geo_format.
items()
django.contrib.gis.sitemaps.kml.KMLSitemap.items (self)
Reimplemented from django.contrib.sitemaps.Sitemap.
Definition at line 63 of file kml.py.
    def items(self):
        return self.locations
References locations.
Referenced by PIL.PdfParser.PdfDict.__bytes__(), django.utils.datastructures.CaseInsensitiveMapping.__eq__(), pip._vendor.distlib.compat.OrderedDict.__eq__(), pip._vendor.distlib.compat.OrderedDict.__repr__(), pip._vendor.requests.structures.CaseInsensitiveDict.__repr__(), requests.structures.CaseInsensitiveDict.__repr__(), django.contrib.sitemaps.Sitemap._items(), django.forms.utils.ErrorDict.as_data(), django.forms.utils.ErrorDict.get_context(), django.forms.utils.ErrorDict.get_json_data(), tomlkit.items.Table.is_super_table(), PIL.TiffImagePlugin.ImageFileDirectory_v2.named(), PIL.Image.Exif.tobytes(), tomlkit.container.Container.unwrap(), and tomlkit.items.AbstractTable.unwrap().
location()
django.contrib.gis.sitemaps.kml.KMLSitemap.location (self, obj)
Reimplemented from django.contrib.sitemaps.Sitemap.
Definition at line 66 of file kml.py.
    def location(self, obj):
        return reverse(
            "django.contrib.gis.sitemaps.views.%s" % self.geo_format,
            kwargs={
                "label": obj[0],
                "model": obj[1],
                "field_name": obj[2],
            },
        )
References geo_format.
Referenced by pip._internal.metadata.base.BaseDistribution._iter_declared_entries_from_legacy(), pip._internal.metadata.base.BaseDistribution.editable_project_location(), and pip._internal.metadata.base.BaseDistribution.installed_as_egg().
Member Data Documentation
geo_format
django.contrib.gis.sitemaps.kml.KMLSitemap.geo_format = "kml" static
Definition at line 13 of file kml.py.
Referenced by get_urls(), and location().
locations
django.contrib.gis.sitemaps.kml.KMLSitemap.locations = self._build_kml_sources(locations)
Definition at line 18 of file kml.py.
Referenced by django.contrib.staticfiles.finders.FileSystemFinder.find(), items(), and django.contrib.staticfiles.finders.FileSystemFinder.list().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/gis/sitemaps/kml.py