Read&Watch: pip._vendor.typing_extensions.Any Class Reference
pip._vendor.typing_extensions.Any Class Reference
Public Member Functions
__new__ (cls, *args, **kwargs)
Public Member Functions inherited from pip._vendor.typing_extensions._AnyMeta
__instancecheck__ (self, obj)
__repr__ (self)
Detailed Description
Special type indicating an unconstrained type.
- Any is compatible with every type.
- Any assumed to have all methods.
- All values assumed to be instances of Any.
Note that all the above statements are true from the point of view of
static type checkers. At runtime, Any should not be used with instance
checks.
Definition at line 192 of file typing_extensions.py.
Member Function Documentation
__new__()
pip._vendor.typing_extensions.Any.__new__ (cls, * args, ** kwargs)
Definition at line 201 of file typing_extensions.py.
        def __new__(cls, *args, **kwargs):
            if cls is Any:
                raise TypeError("Any cannot be instantiated")
            return super().__new__(cls, *args, **kwargs)
References __new__().
Referenced by __new__(), apscheduler.triggers.combining.BaseCombiningTrigger.__setstate__(), pip._vendor.rich.style.Style._add(), pip._vendor.rich.style.Style.clear_meta_and_links(), yaml.constructor.SafeConstructor.construct_yaml_object(), pip._vendor.rich.style.Style.copy(), pip._vendor.rich.style.Style.from_color(), pip._vendor.rich.json.JSON.from_data(), pip._vendor.rich.style.Style.from_meta(), yaml.constructor.FullConstructor.make_python_instance(), pip._vendor.rich.style.Style.update_link(), and pip._vendor.rich.style.Style.without_color().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/typing_extensions.py