Read&Watch: pip._internal.cli.spinners.RateLimiter Class Reference
pip._internal.cli.spinners.RateLimiter Class Reference
Public Member Functions
None __init__ (self, float min_update_interval_seconds)
bool ready (self)
None reset (self)
Protected Attributes
_min_update_interval_seconds = min_update_interval_seconds
float _last_update = 0
Detailed Description
Definition at line 101 of file spinners.py.
Constructor & Destructor Documentation
__init__()
None pip._internal.cli.spinners.RateLimiter.__init__ (self, float min_update_interval_seconds)
Definition at line 102 of file spinners.py.
    def __init__(self, min_update_interval_seconds: float) -> None:
        self._min_update_interval_seconds = min_update_interval_seconds
        self._last_update: float = 0
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
ready()
bool pip._internal.cli.spinners.RateLimiter.ready (self)
Definition at line 106 of file spinners.py.
    def ready(self) -> bool:
        now = time.time()
        delta = now - self._last_update
        return delta >= self._min_update_interval_seconds
References _last_update, and _min_update_interval_seconds.
reset()
None pip._internal.cli.spinners.RateLimiter.reset (self)
Definition at line 111 of file spinners.py.
    def reset(self) -> None:
        self._last_update = time.time()
@contextlib.contextmanager
References _last_update.
Referenced by responses.RequestsMock.__exit__(), django.utils.html.MLStripper.__init__(), pylint.extensions.mccabe.PathGraphingAstVisitor._subgraph(), and pylint.testutils.reporter_for_tests.GenericTestReporter.finalize().
Member Data Documentation
_last_update
float pip._internal.cli.spinners.RateLimiter._last_update = 0 protected
Definition at line 104 of file spinners.py.
Referenced by ready(), and reset().
_min_update_interval_seconds
pip._internal.cli.spinners.RateLimiter._min_update_interval_seconds = min_update_interval_seconds protected
Definition at line 103 of file spinners.py.
Referenced by ready().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_internal/cli/spinners.py