Read&Watch: django.utils.safestring.SafeString Class Reference
django.utils.safestring.SafeString Class Reference
Public Member Functions
__add__ (self, rhs)
__str__ (self)
Public Member Functions inherited from django.utils.safestring.SafeData
__html__ (self)
Detailed Description
A str subclass that has been specifically marked as "safe" for HTML output
purposes.
Definition at line 25 of file safestring.py.
Member Function Documentation
__add__()
django.utils.safestring.SafeString.__add__ (self, rhs)
Concatenating a safe string with another safe bytestring or
safe string is safe. Otherwise, the result is no longer safe.
Definition at line 33 of file safestring.py.
    def __add__(self, rhs):
        """
        Concatenating a safe string with another safe bytestring or
        safe string is safe. Otherwise, the result is no longer safe.
        """
        t = super().__add__(rhs)
        if isinstance(rhs, SafeData):
            return SafeString(t)
        return t
References __add__().
Referenced by __add__().
__str__()
django.utils.safestring.SafeString.__str__ (self)
Definition at line 43 of file safestring.py.
    def __str__(self):
        return self
Referenced by PIL.PdfParser.IndirectReference.__bytes__().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/utils/safestring.py