Read&Watch: pylint.checkers.misc.ByIdManagedMessagesChecker Class Reference
pylint.checkers.misc.ByIdManagedMessagesChecker Class Reference
Public Member Functions
None process_module (self, nodes.Module node)
Public Member Functions inherited from pylint.checkers.base_checker.BaseChecker
None __init__ (self, PyLinter linter)
bool __gt__ (self, Any other)
bool __eq__ (self, object other)
int __hash__ (self)
str __repr__ (self)
str __str__ (self)
str get_full_documentation (self, dict[str, MessageDefinitionTuple] msgs, Iterable[tuple[str, OptionDict, Any]] options, Sequence[tuple[str, str, ReportsCallable]] reports, str|None doc=None, str|None module=None, bool show_options=True)
None add_message (self, str msgid, int|None line=None, nodes.NodeNG|None node=None, Any args=None, Confidence|None confidence=None, int|None col_offset=None, int|None end_lineno=None, int|None end_col_offset=None)
None check_consistency (self)
MessageDefinition create_message_definition_from_tuple (self, str msgid, MessageDefinitionTuple msg_tuple)
list[MessageDefinition] messages (self)
None open (self)
None close (self)
Any get_map_data (self)
None reduce_map_data (self, PyLinter linter, list[Any] data)
Public Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
None __init__ (self, _ArgumentsManager arguments_manager)
Protected Member Functions
None _clear_by_id_managed_msgs (self)
list[ManagedMessage] _get_by_id_managed_msgs (self)
Protected Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
Any _option_value (self, str opt)
Iterator[ tuple[str, list[tuple[str, OptionDict, Any]]]|tuple[None, dict[str, list[tuple[str, OptionDict, Any]]]]] _options_by_section (self)
Iterator[tuple[str, OptionDict, Any]] _options_and_values (self, Options|None options=None)
Additional Inherited Members
Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
linter = linter
messages
Static Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
str name = ""
dict msgs = {}
tuple reports = ()
bool enabled = True
Static Public Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
tuple options = ()
dict option_groups_descs = {}
Protected Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
_arguments_manager = arguments_manager
Detailed Description
Checks for messages that are enabled or disabled by id instead of symbol.
Definition at line 22 of file misc.py.
Member Function Documentation
_clear_by_id_managed_msgs()
None pylint.checkers.misc.ByIdManagedMessagesChecker._clear_by_id_managed_msgs (self) protected
Definition at line 36 of file misc.py.
    def _clear_by_id_managed_msgs(self) -> None:
        self.linter._by_id_managed_msgs.clear()
References pylint.checkers.base_checker.BaseChecker.linter.
Referenced by process_module().
_get_by_id_managed_msgs()
list[ManagedMessage] pylint.checkers.misc.ByIdManagedMessagesChecker._get_by_id_managed_msgs (self) protected
Definition at line 39 of file misc.py.
    def _get_by_id_managed_msgs(self) -> list[ManagedMessage]:
        return self.linter._by_id_managed_msgs
References pylint.checkers.base_checker.BaseChecker.linter.
Referenced by process_module().
process_module()
None pylint.checkers.misc.ByIdManagedMessagesChecker.process_module (self, nodes.Module node)
Inspect the source file to find messages activated or deactivated by id.
Reimplemented from pylint.checkers.base_checker.BaseRawFileChecker.
Definition at line 42 of file misc.py.
    def process_module(self, node: nodes.Module) -> None:
        """Inspect the source file to find messages activated or deactivated by id."""
        managed_msgs = self._get_by_id_managed_msgs()
        for mod_name, msgid, symbol, lineno, is_disabled in managed_msgs:
            if mod_name == node.name:
                verb = "disable" if is_disabled else "enable"
                txt = f"'{msgid}' is cryptic: use '# pylint: {verb}={symbol}' instead"
                self.add_message("use-symbolic-message-instead", line=lineno, args=txt)
        self._clear_by_id_managed_msgs()
References _clear_by_id_managed_msgs(), _get_by_id_managed_msgs(), and pylint.checkers.base_checker.BaseChecker.add_message().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pylint/checkers/misc.py