Read&Watch: urllib3.contrib.emscripten.fetch._StreamingFetcher Class Reference
urllib3.contrib.emscripten.fetch._StreamingFetcher Class Reference
Public Member Functions
None __init__ (self)
EmscriptenResponse send (self, EmscriptenRequest request)
Public Attributes
bool streaming_ready = False
js_worker = js.globalThis.Worker.new(js_data_url)
js_worker_ready_promise = js.globalThis.Promise.new(promise_resolver)
Detailed Description
Definition at line 194 of file fetch.py.
Constructor & Destructor Documentation
__init__()
None urllib3.contrib.emscripten.fetch._StreamingFetcher.__init__ (self)
Definition at line 195 of file fetch.py.
    def __init__(self) -> None:
        # make web-worker and data buffer on startup
        self.streaming_ready = False
        js_data_blob = js.Blob.new(
            [_STREAMING_WORKER_CODE], _obj_from_dict({"type": "application/javascript"})
        )
        def promise_resolver(js_resolve_fn: JsProxy, js_reject_fn: JsProxy) -> None:
            def onMsg(e: JsProxy) -> None:
                self.streaming_ready = True
                js_resolve_fn(e)
            def onErr(e: JsProxy) -> None:
                js_reject_fn(e)  # Defensive: never happens in ci
            self.js_worker.onmessage = onMsg
            self.js_worker.onerror = onErr
        js_data_url = js.URL.createObjectURL(js_data_blob)
        self.js_worker = js.globalThis.Worker.new(js_data_url)
        self.js_worker_ready_promise = js.globalThis.Promise.new(promise_resolver)
Member Function Documentation
send()
EmscriptenResponse urllib3.contrib.emscripten.fetch._StreamingFetcher.send (self, EmscriptenRequest request)
Definition at line 218 of file fetch.py.
    def send(self, request: EmscriptenRequest) -> EmscriptenResponse:
        headers = {
            k: v for k, v in request.headers.items() if k not in HEADERS_TO_IGNORE
        }
        body = request.body
        fetch_data = {"headers": headers, "body": to_js(body), "method": request.method}
        # start the request off in the worker
        timeout = int(1000 * request.timeout) if request.timeout > 0 else None
        js_shared_buffer = js.SharedArrayBuffer.new(1048576)
        js_int_buffer = js.Int32Array.new(js_shared_buffer)
        js_byte_buffer = js.Uint8Array.new(js_shared_buffer, 8)
        js.Atomics.store(js_int_buffer, 0, ERROR_TIMEOUT)
        js.Atomics.notify(js_int_buffer, 0)
        js_absolute_url = js.URL.new(request.url, js.location).href
        self.js_worker.postMessage(
            _obj_from_dict(
                {
                    "buffer": js_shared_buffer,
                    "url": js_absolute_url,
                    "fetchParams": fetch_data,
                }
            )
        )
        # wait for the worker to send something
        js.Atomics.wait(js_int_buffer, 0, ERROR_TIMEOUT, timeout)
        if js_int_buffer[0] == ERROR_TIMEOUT:
            raise _TimeoutError(
                "Timeout connecting to streaming request",
                request=request,
                response=None,
            )
        elif js_int_buffer[0] == SUCCESS_HEADER:
            # got response
            # header length is in second int of intBuffer
            string_len = js_int_buffer[1]
            # decode the rest to a JSON string
            js_decoder = js.TextDecoder.new()
            # this does a copy (the slice) because decode can't work on shared array
            # for some silly reason
            json_str = js_decoder.decode(js_byte_buffer.slice(0, string_len))
            # get it as an object
            response_obj = json.loads(json_str)
            return EmscriptenResponse(
                request=request,
                status_code=response_obj["status"],
                headers=response_obj["headers"],
                body=_ReadStream(
                    js_int_buffer,
                    js_byte_buffer,
                    request.timeout,
                    self.js_worker,
                    response_obj["connectionID"],
                    request,
                ),
            )
        elif js_int_buffer[0] == ERROR_EXCEPTION:
            string_len = js_int_buffer[1]
            # decode the error string
            js_decoder = js.TextDecoder.new()
            json_str = js_decoder.decode(js_byte_buffer.slice(0, string_len))
            raise _StreamingError(
                f"Exception thrown in fetch: {json_str}", request=request, response=None
            )
        else:
            raise _StreamingError(
                f"Unknown status from worker in fetch: {js_int_buffer[0]}",
                request=request,
                response=None,
            )
# check if we are in a worker or not
References urllib3.contrib.emscripten.fetch._obj_from_dict(), and js_worker.
Referenced by urllib3.connection.HTTPConnection._tunnel(), pip._vendor.urllib3.connection.HTTPConnection.request_chunked(), and urllib3.util.ssltransport.SSLTransport.sendall().
Member Data Documentation
js_worker
urllib3.contrib.emscripten.fetch._StreamingFetcher.js_worker = js.globalThis.Worker.new(js_data_url)
Definition at line 215 of file fetch.py.
Referenced by send().
js_worker_ready_promise
urllib3.contrib.emscripten.fetch._StreamingFetcher.js_worker_ready_promise = js.globalThis.Promise.new(promise_resolver)
Definition at line 216 of file fetch.py.
streaming_ready
bool urllib3.contrib.emscripten.fetch._StreamingFetcher.streaming_ready = False
Definition at line 197 of file fetch.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/urllib3/contrib/emscripten/fetch.py