Read&Watch: django.contrib.redirects.middleware.RedirectFallbackMiddleware Class Reference
django.contrib.redirects.middleware.RedirectFallbackMiddleware Class Reference
Public Member Functions
__init__ (self, get_response)
process_response (self, request, response)
Public Member Functions inherited from django.utils.deprecation.MiddlewareMixin
__init__ (self, get_response)
__repr__ (self)
__call__ (self, request)
__acall__ (self, request)
Static Public Attributes
response_gone_class = HttpResponseGone
response_redirect_class = HttpResponsePermanentRedirect
Static Public Attributes inherited from django.utils.deprecation.MiddlewareMixin
bool sync_capable = True
bool async_capable = True
Additional Inherited Members
Public Attributes inherited from django.utils.deprecation.MiddlewareMixin
get_response = get_response
async_mode = iscoroutinefunction(self.get_response)
Detailed Description
Definition at line 10 of file middleware.py.
Constructor & Destructor Documentation
__init__()
django.contrib.redirects.middleware.RedirectFallbackMiddleware.__init__ (self, get_response)
Definition at line 15 of file middleware.py.
    def __init__(self, get_response):
        if not apps.is_installed("django.contrib.sites"):
            raise ImproperlyConfigured(
                "You cannot use RedirectFallbackMiddleware when "
                "django.contrib.sites is not installed."
            )
        super().__init__(get_response)
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Function Documentation
process_response()
django.contrib.redirects.middleware.RedirectFallbackMiddleware.process_response (self, request, response)
Definition at line 23 of file middleware.py.
    def process_response(self, request, response):
        # No need to check for a redirect for non-404 responses.
        if response.status_code != 404:
            return response
        full_path = request.get_full_path()
        current_site = get_current_site(request)
        r = None
        try:
            r = Redirect.objects.get(site=current_site, old_path=full_path)
        except Redirect.DoesNotExist:
            pass
        if r is None and settings.APPEND_SLASH and not request.path.endswith("/"):
            try:
                r = Redirect.objects.get(
                    site=current_site,
                    old_path=request.get_full_path(force_append_slash=True),
                )
            except Redirect.DoesNotExist:
                pass
        if r is not None:
            if r.new_path == "":
                return self.response_gone_class()
            return self.response_redirect_class(r.new_path)
        # No redirect was found. Return the response.
        return response
References response_gone_class, and response_redirect_class.
Referenced by django.utils.deprecation.MiddlewareMixin.__acall__(), django.utils.deprecation.MiddlewareMixin.__call__(), and pip._vendor.rich.prompt.PromptBase.__call__().
Member Data Documentation
response_gone_class
django.contrib.redirects.middleware.RedirectFallbackMiddleware.response_gone_class = HttpResponseGone static
Definition at line 12 of file middleware.py.
Referenced by process_response().
response_redirect_class
django.contrib.redirects.middleware.RedirectFallbackMiddleware.response_redirect_class = HttpResponsePermanentRedirect static
Definition at line 13 of file middleware.py.
Referenced by django.middleware.common.CommonMiddleware.process_request(), process_response(), django.middleware.common.CommonMiddleware.process_response(), and django.middleware.locale.LocaleMiddleware.process_response().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/redirects/middleware.py