Read&Watch: django.contrib.admin.utils.NestedObjects Class Reference
django.contrib.admin.utils.NestedObjects Class Reference
Public Member Functions
__init__ (self, *args, **kwargs)
add_edge (self, source, target)
collect (self, objs, source=None, source_attr=None, **kwargs)
related_objects (self, related_model, related_fields, objs)
nested (self, format_callback=None)
can_fast_delete (self, *args, **kwargs)
Public Member Functions inherited from django.db.models.deletion.Collector
__init__ (self, using, origin=None)
add (self, objs, source=None, nullable=False, reverse_dependency=False)
add_dependency (self, model, dependency, reverse_dependency=False)
add_field_update (self, field, value, objs)
add_restricted_objects (self, field, objs)
clear_restricted_objects_from_set (self, model, objs)
clear_restricted_objects_from_queryset (self, model, qs)
get_del_batches (self, objs, fields)
instances_with_model (self)
sort (self)
delete (self)
Public Attributes
dict edges = {}
protected = set()
model_objs = defaultdict(set)
Public Attributes inherited from django.db.models.deletion.Collector
using = using
origin = origin
dict data = defaultdict(set)
field_updates = defaultdict(list)
restricted_objects = defaultdict(partial(defaultdict, set))
list fast_deletes = []
dependencies = defaultdict(set)
Protected Member Functions
_nested (self, obj, seen, format_callback)
Protected Member Functions inherited from django.db.models.deletion.Collector
_has_signal_listeners (self, model)
Detailed Description
Definition at line 183 of file utils.py.
Constructor & Destructor Documentation
__init__()
django.contrib.admin.utils.NestedObjects.__init__ (self, * args, ** kwargs)
Definition at line 184 of file utils.py.
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.edges = {}  # {from_instance: [to_instances]}
        self.protected = set()
        self.model_objs = defaultdict(set)
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Function Documentation
_nested()
django.contrib.admin.utils.NestedObjects._nested (self, obj, seen, format_callback) protected
Definition at line 217 of file utils.py.
    def _nested(self, obj, seen, format_callback):
        if obj in seen:
            return []
        seen.add(obj)
        children = []
        for child in self.edges.get(obj, ()):
            children.extend(self._nested(child, seen, format_callback))
        if format_callback:
            ret = [format_callback(obj)]
        else:
            ret = [obj]
        if children:
            ret.append(children)
        return ret
References _nested(), and edges.
Referenced by _nested(), and nested().
add_edge()
django.contrib.admin.utils.NestedObjects.add_edge (self, source, target)
Definition at line 190 of file utils.py.
    def add_edge(self, source, target):
        self.edges.setdefault(source, []).append(target)
References edges.
Referenced by collect().
can_fast_delete()
django.contrib.admin.utils.NestedObjects.can_fast_delete (self, * args, ** kwargs)
We always want to load the objects into memory so that we can display
them to the user in confirm page.
Reimplemented from django.db.models.deletion.Collector.
Definition at line 242 of file utils.py.
    def can_fast_delete(self, *args, **kwargs):
        """
        We always want to load the objects into memory so that we can display
        them to the user in confirm page.
        """
        return False
Referenced by django.db.models.deletion.Collector.collect(), and django.db.models.deletion.Collector.delete().
collect()
django.contrib.admin.utils.NestedObjects.collect (self, objs, source = None, nullable = None, ** collect_related)
Add 'objs' to the collection of objects to be deleted as well as all
parent instances.  'objs' must be a homogeneous iterable collection of
model instances (e.g. a QuerySet).  If 'collect_related' is True,
related objects will be handled by their respective on_delete handler.
If the call is the result of a cascade, 'source' should be the model
that caused it and 'nullable' should be set to True, if the relation
can be null.
If 'reverse_dependency' is True, 'source' will be deleted before the
current model, rather than after. (Needed for cascading to parent
models, the one case in which the cascade follows the forwards
direction of an FK rather than the reverse direction.)
If 'keep_parents' is True, data of parent model's will be not deleted.
If 'fail_on_restricted' is False, error won't be raised even if it's
prohibited to delete such objects due to RESTRICT, that defers
restricted object checking in recursive calls where the top-level call
may need to collect more objects to determine whether restricted ones
can be deleted.
Reimplemented from django.db.models.deletion.Collector.
Definition at line 193 of file utils.py.
    def collect(self, objs, source=None, source_attr=None, **kwargs):
        for obj in objs:
            if source_attr and not source_attr.endswith("+"):
                related_name = source_attr % {
                    "class": source._meta.model_name,
                    "app_label": source._meta.app_label,
                }
                self.add_edge(getattr(obj, related_name), obj)
            else:
                self.add_edge(None, obj)
            self.model_objs[obj._meta.model].add(obj)
        try:
            return super().collect(objs, source_attr=source_attr, **kwargs)
        except models.ProtectedError as e:
            self.protected.update(e.protected_objects)
        except models.RestrictedError as e:
            self.protected.update(e.restricted_objects)
References django.db.models.deletion.Collector.add(), add_edge(), collect(), model_objs, and protected.
Referenced by collect(), django.db.models.deletion.Collector.collect(), and django.contrib.staticfiles.management.commands.collectstatic.Command.handle().
nested()
django.contrib.admin.utils.NestedObjects.nested (self, format_callback = None)
Return the graph as a nested list.
Definition at line 232 of file utils.py.
    def nested(self, format_callback=None):
        """
        Return the graph as a nested list.
        """
        seen = set()
        roots = []
        for root in self.edges.get(None, ()):
            roots.extend(self._nested(root, seen, format_callback))
        return roots
References _nested(), and edges.
related_objects()
django.contrib.admin.utils.NestedObjects.related_objects (self, related_model, related_fields, objs)
Get a QuerySet of the related model to objs via related fields.
Reimplemented from django.db.models.deletion.Collector.
Definition at line 211 of file utils.py.
    def related_objects(self, related_model, related_fields, objs):
        qs = super().related_objects(related_model, related_fields, objs)
        return qs.select_related(
            *[related_field.name for related_field in related_fields]
        )
References related_objects().
Referenced by django.db.models.options.Options._reverse_one_to_one_field_names(), django.db.models.deletion.Collector.collect(), and related_objects().
Member Data Documentation
edges
dict django.contrib.admin.utils.NestedObjects.edges = {}
Definition at line 186 of file utils.py.
Referenced by _nested(), add_edge(), and nested().
model_objs
django.contrib.admin.utils.NestedObjects.model_objs = defaultdict(set)
Definition at line 188 of file utils.py.
Referenced by collect().
protected
django.contrib.admin.utils.NestedObjects.protected = set()
Definition at line 187 of file utils.py.
Referenced by collect().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/admin/utils.py