Read&Watch: django.core.cache.backends.dummy.DummyCache Class Reference
django.core.cache.backends.dummy.DummyCache Class Reference
Public Member Functions
__init__ (self, host, *args, **kwargs)
add (self, key, value, timeout=DEFAULT_TIMEOUT, version=None)
get (self, key, default=None, version=None)
set (self, key, value, timeout=DEFAULT_TIMEOUT, version=None)
touch (self, key, timeout=DEFAULT_TIMEOUT, version=None)
delete (self, key, version=None)
has_key (self, key, version=None)
clear (self)
Public Member Functions inherited from django.core.cache.backends.base.BaseCache
__init__ (self, params)
get_backend_timeout (self, timeout=DEFAULT_TIMEOUT)
make_key (self, key, version=None)
validate_key (self, key)
make_and_validate_key (self, key, version=None)
aadd (self, key, value, timeout=DEFAULT_TIMEOUT, version=None)
aget (self, key, default=None, version=None)
aset (self, key, value, timeout=DEFAULT_TIMEOUT, version=None)
atouch (self, key, timeout=DEFAULT_TIMEOUT, version=None)
adelete (self, key, version=None)
get_many (self, keys, version=None)
aget_many (self, keys, version=None)
get_or_set (self, key, default, timeout=DEFAULT_TIMEOUT, version=None)
aget_or_set (self, key, default, timeout=DEFAULT_TIMEOUT, version=None)
ahas_key (self, key, version=None)
incr (self, key, delta=1, version=None)
aincr (self, key, delta=1, version=None)
decr (self, key, delta=1, version=None)
adecr (self, key, delta=1, version=None)
__contains__ (self, key)
set_many (self, data, timeout=DEFAULT_TIMEOUT, version=None)
aset_many (self, data, timeout=DEFAULT_TIMEOUT, version=None)
delete_many (self, keys, version=None)
adelete_many (self, keys, version=None)
aclear (self)
incr_version (self, key, delta=1, version=None)
aincr_version (self, key, delta=1, version=None)
decr_version (self, key, delta=1, version=None)
adecr_version (self, key, delta=1, version=None)
close (self, **kwargs)
aclose (self, **kwargs)
Additional Inherited Members
Public Attributes inherited from django.core.cache.backends.base.BaseCache
default_timeout = timeout
key_prefix = params.get("KEY_PREFIX", "")
version = params.get("VERSION", 1)
key_func = get_key_func(params.get("KEY_FUNCTION"))
Protected Attributes inherited from django.core.cache.backends.base.BaseCache
int _max_entries = int(max_entries)
int _cull_frequency = int(cull_frequency)
Static Protected Attributes inherited from django.core.cache.backends.base.BaseCache
_missing_key = object()
Detailed Description
Definition at line 6 of file dummy.py.
Constructor & Destructor Documentation
__init__()
django.core.cache.backends.dummy.DummyCache.__init__ (self, host, * args, ** kwargs)
Definition at line 7 of file dummy.py.
    def __init__(self, host, *args, **kwargs):
        super().__init__(*args, **kwargs)
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Function Documentation
add()
django.core.cache.backends.dummy.DummyCache.add (self, key, value, timeout = DEFAULT_TIMEOUT, version = None)
Reimplemented from django.core.cache.backends.base.BaseCache.
Definition at line 10 of file dummy.py.
    def add(self, key, value, timeout=DEFAULT_TIMEOUT, version=None):
        self.make_and_validate_key(key, version=version)
        return True
References django.core.cache.backends.base.BaseCache.make_and_validate_key().
Referenced by responses.RequestsMock._add_from_file(), pip._internal.req.req_uninstall.UninstallPathSet.add(), pip._vendor.distlib.manifest.Manifest.add_many(), django.db.models.deletion.Collector.collect(), pip._vendor.urllib3._collections.HTTPHeaderDict.extend(), urllib3._collections.HTTPHeaderDict.extend(), pip._internal.operations.build.build_tracker.BuildTracker.track(), and responses.RequestsMock.upsert().
clear()
django.core.cache.backends.dummy.DummyCache.clear (self)
Reimplemented from django.core.cache.backends.base.BaseCache.
Definition at line 33 of file dummy.py.
    def clear(self):
        pass
Referenced by pip._vendor.urllib3.poolmanager.PoolManager.__exit__(), urllib3.poolmanager.PoolManager.__exit__(), django.contrib.sessions.backends.cached_db.SessionStore.aflush(), and django.contrib.sessions.backends.cached_db.SessionStore.flush().
delete()
django.core.cache.backends.dummy.DummyCache.delete (self, key, version = None)
Reimplemented from django.core.cache.backends.base.BaseCache.
Definition at line 25 of file dummy.py.
    def delete(self, key, version=None):
        self.make_and_validate_key(key, version=version)
        return False
References django.core.cache.backends.base.BaseCache.make_and_validate_key().
Referenced by django.contrib.staticfiles.storage.HashedFilesMixin._post_process(), and django.views.generic.edit.DeletionMixin.post().
get()
django.core.cache.backends.dummy.DummyCache.get (self, key, default = None, version = None)
Reimplemented from django.core.cache.backends.base.BaseCache.
Definition at line 14 of file dummy.py.
    def get(self, key, default=None, version=None):
        self.make_and_validate_key(key, version=version)
        return default
References django.core.cache.backends.base.BaseCache.make_and_validate_key().
Referenced by pip._vendor.distlib.metadata.LegacyMetadata.__getitem__(), pip._vendor.rich.layout.Layout.__getitem__(), django.test.client.ClientMixin._follow_redirect(), pip._vendor.distlib.metadata.LegacyMetadata.check(), django.views.generic.base.RedirectView.delete(), PIL.Image.Exif.get_ifd(), django.views.generic.base.RedirectView.head(), django.views.generic.base.RedirectView.options(), django.views.generic.base.RedirectView.patch(), django.views.generic.base.RedirectView.post(), django.views.generic.base.RedirectView.put(), and pip._vendor.distlib.metadata.LegacyMetadata.write_file().
has_key()
django.core.cache.backends.dummy.DummyCache.has_key (self, key, version = None)
Return True if the key is in the cache and has not expired.
Reimplemented from django.core.cache.backends.base.BaseCache.
Definition at line 29 of file dummy.py.
    def has_key(self, key, version=None):
        self.make_and_validate_key(key, version=version)
        return False
References django.core.cache.backends.base.BaseCache.make_and_validate_key().
set()
django.core.cache.backends.dummy.DummyCache.set (self, key, value, timeout = DEFAULT_TIMEOUT, version = None)
Reimplemented from django.core.cache.backends.base.BaseCache.
Definition at line 18 of file dummy.py.
    def set(self, key, value, timeout=DEFAULT_TIMEOUT, version=None):
        self.make_and_validate_key(key, version=version)
References django.core.cache.backends.base.BaseCache.make_and_validate_key().
Referenced by pip._vendor.distlib.metadata.LegacyMetadata.__setitem__(), pip._vendor.requests.cookies.RequestsCookieJar.__setitem__(), requests.cookies.RequestsCookieJar.__setitem__(), pip._vendor.tomli._parser.Flags.finalize_pending(), pip._vendor.distlib.metadata.LegacyMetadata.read_file(), and pip._vendor.distlib.metadata.LegacyMetadata.update().
touch()
django.core.cache.backends.dummy.DummyCache.touch (self, key, timeout = DEFAULT_TIMEOUT, version = None)
Reimplemented from django.core.cache.backends.base.BaseCache.
Definition at line 21 of file dummy.py.
    def touch(self, key, timeout=DEFAULT_TIMEOUT, version=None):
        self.make_and_validate_key(key, version=version)
        return False
References django.core.cache.backends.base.BaseCache.make_and_validate_key().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/core/cache/backends/dummy.py