Read&Watch: django.utils.timezone.override Class Reference
django.utils.timezone.override Class Reference
Public Member Functions
__init__ (self, timezone)
__enter__ (self)
__exit__ (self, exc_type, exc_value, traceback)
Public Attributes
timezone = timezone
old_timezone = getattr(_active, "value", None)
Detailed Description
Temporarily set the time zone for the current thread.
This is a context manager that uses django.utils.timezone.activate()
to set the timezone on entry and restores the previously active timezone
on exit.
The ``timezone`` argument must be an instance of a ``tzinfo`` subclass, a
time zone name, or ``None``. If it is ``None``, Django enables the default
time zone.
Definition at line 113 of file timezone.py.
Constructor & Destructor Documentation
__init__()
django.utils.timezone.override.__init__ (self, timezone)
Definition at line 126 of file timezone.py.
    def __init__(self, timezone):
        self.timezone = timezone
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
__enter__()
django.utils.timezone.override.__enter__ (self)
Definition at line 129 of file timezone.py.
    def __enter__(self):
        self.old_timezone = getattr(_active, "value", None)
        if self.timezone is None:
            deactivate()
        else:
            activate(self.timezone)
__exit__()
django.utils.timezone.override.__exit__ (self, exc_type, exc_value, traceback)
Definition at line 136 of file timezone.py.
    def __exit__(self, exc_type, exc_value, traceback):
        if self.old_timezone is None:
            deactivate()
        else:
            _active.value = self.old_timezone
# Templates
References django.utils.timezone.deactivate(), and old_timezone.
Member Data Documentation
old_timezone
django.utils.timezone.override.old_timezone = getattr(_active, "value", None)
Definition at line 130 of file timezone.py.
Referenced by __exit__().
timezone
django.utils.timezone.override.timezone = timezone
Definition at line 127 of file timezone.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/utils/timezone.py