Read&Watch: django.utils.autoreload.StatReloader Class Reference
django.utils.autoreload.StatReloader Class Reference
Public Member Functions
tick (self)
snapshot_files (self)
check_availability (cls)
Public Member Functions inherited from django.utils.autoreload.BaseReloader
__init__ (self)
watch_dir (self, path, glob)
watched_files (self, include_globs=True)
wait_for_apps_ready (self, app_reg, django_main_thread)
run (self, django_main_thread)
run_loop (self)
notify_file_changed (self, path)
should_stop (self)
stop (self)
Static Public Attributes
int SLEEP_TIME = 1
Additional Inherited Members
Public Attributes inherited from django.utils.autoreload.BaseReloader
extra_files = set()
directory_globs = defaultdict(set)
should_stop
Protected Attributes inherited from django.utils.autoreload.BaseReloader
_stop_condition = threading.Event()
Detailed Description
Definition at line 384 of file autoreload.py.
Member Function Documentation
check_availability()
django.utils.autoreload.StatReloader.check_availability (cls)
Reimplemented from django.utils.autoreload.BaseReloader.
Definition at line 423 of file autoreload.py.
    def check_availability(cls):
        return True
snapshot_files()
django.utils.autoreload.StatReloader.snapshot_files (self)
Definition at line 408 of file autoreload.py.
    def snapshot_files(self):
        # watched_files may produce duplicate paths if globs overlap.
        seen_files = set()
        for file in self.watched_files():
            if file in seen_files:
                continue
            try:
                mtime = file.stat().st_mtime
            except OSError:
                # This is thrown when the file does not exist.
                continue
            seen_files.add(file)
            yield file, mtime
References django.utils.autoreload.BaseReloader.watched_files().
Referenced by tick().
tick()
django.utils.autoreload.StatReloader.tick (self)
This generator is called in a loop from run_loop. It's important that
the method takes care of pausing or otherwise waiting for a period of
time. This split between run_loop() and tick() is to improve the
testability of the reloader implementations by decoupling the work they
do from the loop.
Reimplemented from django.utils.autoreload.BaseReloader.
Definition at line 387 of file autoreload.py.
    def tick(self):
        mtimes = {}
        while True:
            for filepath, mtime in self.snapshot_files():
                old_time = mtimes.get(filepath)
                mtimes[filepath] = mtime
                if old_time is None:
                    logger.debug("File %s first seen with mtime %s", filepath, mtime)
                    continue
                elif mtime > old_time:
                    logger.debug(
                        "File %s previous mtime: %s, current mtime: %s",
                        filepath,
                        old_time,
                        mtime,
                    )
                    self.notify_file_changed(filepath)
            time.sleep(self.SLEEP_TIME)
            yield
References django.utils.autoreload.BaseReloader.notify_file_changed(), SLEEP_TIME, and snapshot_files().
Member Data Documentation
SLEEP_TIME
django.utils.autoreload.StatReloader.SLEEP_TIME = 1 static
Definition at line 385 of file autoreload.py.
Referenced by tick().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/utils/autoreload.py