Read&Watch: django.core.management.base.DjangoHelpFormatter Class Reference
django.core.management.base.DjangoHelpFormatter Class Reference
Public Member Functions
add_usage (self, usage, actions, *args, **kwargs)
add_arguments (self, actions)
Static Public Attributes
dict show_last
Protected Member Functions
_reordered_actions (self, actions)
Detailed Description
Customized formatter so that command-specific arguments appear in the
--help output before arguments common to all commands.
Definition at line 116 of file base.py.
Member Function Documentation
_reordered_actions()
django.core.management.base.DjangoHelpFormatter._reordered_actions (self, actions) protected
Definition at line 133 of file base.py.
    def _reordered_actions(self, actions):
        return sorted(
            actions, key=lambda a: set(a.option_strings) & self.show_last != set()
        )
References show_last.
Referenced by add_arguments(), and add_usage().
add_arguments()
django.core.management.base.DjangoHelpFormatter.add_arguments (self, actions)
Definition at line 141 of file base.py.
    def add_arguments(self, actions):
        super().add_arguments(self._reordered_actions(actions))
References _reordered_actions(), and add_arguments().
Referenced by add_arguments(), and django.core.management.base.BaseCommand.create_parser().
add_usage()
django.core.management.base.DjangoHelpFormatter.add_usage (self, usage, actions, * args, ** kwargs)
Definition at line 138 of file base.py.
    def add_usage(self, usage, actions, *args, **kwargs):
        super().add_usage(usage, self._reordered_actions(actions), *args, **kwargs)
References _reordered_actions(), and add_usage().
Referenced by add_usage().
Member Data Documentation
show_last
dict django.core.management.base.DjangoHelpFormatter.show_last static
Initial value:
=  {
        "--version",
        "--verbosity",
        "--traceback",
        "--settings",
        "--pythonpath",
        "--no-color",
        "--force-color",
        "--skip-checks",
    }
Definition at line 122 of file base.py.
Referenced by _reordered_actions().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/core/management/base.py