Read&Watch: pip._internal.cache.Cache Class Reference
pip._internal.cache.Cache Class Reference
Public Member Functions
None __init__ (self, str cache_dir)
str get_path_for_link (self, Link link)
Link get (self, Link link, Optional[str] package_name, List[Tag] supported_tags)
Public Attributes
cache_dir = cache_dir or None
Protected Member Functions
List[str] _get_cache_path_parts (self, Link link)
List[Any] _get_candidates (self, Link link, str canonical_package_name)
Detailed Description
An abstract class - provides cache directories for data from links
:param cache_dir: The root of the cache.
Definition at line 32 of file cache.py.
Constructor & Destructor Documentation
__init__()
None pip._internal.cache.Cache.__init__ (self, str cache_dir)
Definition at line 38 of file cache.py.
    def __init__(self, cache_dir: str) -> None:
        super().__init__()
        assert not cache_dir or os.path.isabs(cache_dir)
        self.cache_dir = cache_dir or None
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Function Documentation
_get_cache_path_parts()
List[str] pip._internal.cache.Cache._get_cache_path_parts (self, Link link) protected
Get parts of part that must be os.path.joined with cache_dir
Definition at line 43 of file cache.py.
    def _get_cache_path_parts(self, link: Link) -> List[str]:
        """Get parts of part that must be os.path.joined with cache_dir"""
        # We want to generate an url to use as our cache key, we don't want to
        # just reuse the URL because it might have other items in the fragment
        # and we don't care about those.
        key_parts = {"url": link.url_without_fragment}
        if link.hash_name is not None and link.hash is not None:
            key_parts[link.hash_name] = link.hash
        if link.subdirectory_fragment:
            key_parts["subdirectory"] = link.subdirectory_fragment
        # Include interpreter name, major and minor version in cache key
        # to cope with ill-behaved sdists that build a different wheel
        # depending on the python version their setup.py is being run on,
        # and don't encode the difference in compatibility tags.
        # https://github.com/pypa/pip/issues/7296
        key_parts["interpreter_name"] = interpreter_name()
        key_parts["interpreter_version"] = interpreter_version()
        # Encode our key url with sha224, we'll use this because it has similar
        # security properties to sha256, but with a shorter total output (and
        # thus less secure). However the differences don't make a lot of
        # difference for our use case here.
        hashed = _hash_dict(key_parts)
        # We want to nest the directories some to prevent having a ton of top
        # level directories where we might run out of sub directories on some
        # FS.
        parts = [hashed[:2], hashed[2:4], hashed[4:6], hashed[6:]]
        return parts
_get_candidates()
List[Any] pip._internal.cache.Cache._get_candidates (self, Link link, str canonical_package_name) protected
Definition at line 76 of file cache.py.
    def _get_candidates(self, link: Link, canonical_package_name: str) -> List[Any]:
        can_not_cache = not self.cache_dir or not canonical_package_name or not link
        if can_not_cache:
            return []
        path = self.get_path_for_link(link)
        if os.path.isdir(path):
            return [(candidate, path) for candidate in os.listdir(path)]
        return []
get()
Link pip._internal.cache.Cache.get (self, Link link, Optional[str] package_name, List[Tag] supported_tags)
Returns a link to a cached item if it exists, otherwise returns the
passed link.
Reimplemented in pip._internal.cache.SimpleWheelCache, and pip._internal.cache.WheelCache.
Definition at line 90 of file cache.py.
    ) -> Link:
        """Returns a link to a cached item if it exists, otherwise returns the
        passed link.
        """
        raise NotImplementedError()
Referenced by pip._vendor.distlib.metadata.LegacyMetadata.__getitem__(), pip._vendor.rich.layout.Layout.__getitem__(), django.test.client.ClientMixin._follow_redirect(), pip._vendor.distlib.metadata.LegacyMetadata.check(), PIL.Image.Exif.get_ifd(), and pip._vendor.distlib.metadata.LegacyMetadata.write_file().
get_path_for_link()
str pip._internal.cache.Cache.get_path_for_link (self, Link link)
Return a directory to store cached items in for link.
Reimplemented in pip._internal.cache.SimpleWheelCache, and pip._internal.cache.WheelCache.
Definition at line 86 of file cache.py.
    def get_path_for_link(self, link: Link) -> str:
        """Return a directory to store cached items in for link."""
        raise NotImplementedError()
Member Data Documentation
cache_dir
pip._internal.cache.Cache.cache_dir = cache_dir or None
Definition at line 41 of file cache.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_internal/cache.py