Read&Watch: django.template.defaulttags.CycleNode Class Reference
django.template.defaulttags.CycleNode Class Reference
Public Member Functions
__init__ (self, cyclevars, variable_name=None, silent=False)
render (self, context)
reset (self, context)
Public Member Functions inherited from django.template.base.Node
render_annotated (self, context)
get_nodes_by_type (self, nodetype)
Public Attributes
cyclevars = cyclevars
variable_name = variable_name
silent = silent
Additional Inherited Members
Static Public Attributes inherited from django.template.base.Node
bool must_be_first = False
tuple child_nodelists = ("nodelist",)
token = None
Detailed Description
Definition at line 95 of file defaulttags.py.
Constructor & Destructor Documentation
__init__()
django.template.defaulttags.CycleNode.__init__ (self, cyclevars, variable_name = None, silent = False)
Definition at line 96 of file defaulttags.py.
    def __init__(self, cyclevars, variable_name=None, silent=False):
        self.cyclevars = cyclevars
        self.variable_name = variable_name
        self.silent = silent
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
render()
django.template.defaulttags.CycleNode.render (self, context)
Return the node rendered as a string.
Reimplemented from django.template.base.Node.
Definition at line 101 of file defaulttags.py.
    def render(self, context):
        if self not in context.render_context:
            # First time the node is rendered in template
            context.render_context[self] = itertools_cycle(self.cyclevars)
        cycle_iter = context.render_context[self]
        value = next(cycle_iter).resolve(context)
        if self.variable_name:
            context.set_upward(self.variable_name, value)
        if self.silent:
            return ""
        return render_value_in_context(value, context)
References cyclevars, silent, and variable_name.
Referenced by pip._vendor.rich.progress.ProgressColumn.__call__(), pip._vendor.rich.layout.Layout.__rich_console__(), pip._vendor.rich.spinner.Spinner.__rich_console__(), pip._vendor.rich.spinner.Spinner.__rich_measure__(), pip._vendor.rich.console.Console.log(), pip._vendor.rich.console.Console.print(), django.templatetags.i18n.BlockTranslateNode.render(), pip._vendor.rich.console.Console.render(), pip._vendor.rich.console.Console.render_lines(), and pip._vendor.rich.console.Console.update_screen_lines().
reset()
django.template.defaulttags.CycleNode.reset (self, context)
Reset the cycle iteration back to the beginning.
Definition at line 113 of file defaulttags.py.
    def reset(self, context):
        """
        Reset the cycle iteration back to the beginning.
        """
        context.render_context[self] = itertools_cycle(self.cyclevars)
References cyclevars.
Referenced by responses.RequestsMock.__exit__(), django.utils.html.MLStripper.__init__(), pylint.extensions.mccabe.PathGraphingAstVisitor._subgraph(), pylint.testutils.reporter_for_tests.GenericTestReporter.finalize(), and PIL.TiffImagePlugin.ImageFileDirectory_v2.load().
Member Data Documentation
cyclevars
django.template.defaulttags.CycleNode.cyclevars = cyclevars
Definition at line 97 of file defaulttags.py.
Referenced by render(), and reset().
silent
django.template.defaulttags.CycleNode.silent = silent
Definition at line 99 of file defaulttags.py.
Referenced by render().
variable_name
django.template.defaulttags.CycleNode.variable_name = variable_name
Definition at line 98 of file defaulttags.py.
Referenced by render().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/template/defaulttags.py