Read&Watch: django.contrib.gis.gdal.raster.source.TransformPoint Class Reference
django.contrib.gis.gdal.raster.source.TransformPoint Class Reference
Public Member Functions
__init__ (self, raster, prop)
x (self)
x (self, value)
y (self)
y (self, value)
Static Public Attributes
dict indices
Protected Attributes
_raster = raster
_prop = prop
Detailed Description
Definition at line 35 of file source.py.
Constructor & Destructor Documentation
__init__()
django.contrib.gis.gdal.raster.source.TransformPoint.__init__ (self, raster, prop)
Definition at line 42 of file source.py.
    def __init__(self, raster, prop):
        x = raster.geotransform[self.indices[prop][0]]
        y = raster.geotransform[self.indices[prop][1]]
        super().__init__([x, y])
        self._raster = raster
        self._prop = prop
References __init__(), and indices.
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Function Documentation
x() [1/2]
django.contrib.gis.gdal.raster.source.TransformPoint.x (self)
Definition at line 50 of file source.py.
    def x(self):
        return self[0]
Referenced by django.contrib.gis.geos.point.Point._get_single_external().
x() [2/2]
django.contrib.gis.gdal.raster.source.TransformPoint.x (self, value)
Definition at line 54 of file source.py.
    def x(self, value):
        gtf = self._raster.geotransform
        gtf[self.indices[self._prop][0]] = value
        self._raster.geotransform = gtf
References _prop, _raster, and indices.
Referenced by django.contrib.gis.geos.point.Point._get_single_external().
y() [1/2]
django.contrib.gis.gdal.raster.source.TransformPoint.y (self)
Definition at line 60 of file source.py.
    def y(self):
        return self[1]
Referenced by django.contrib.gis.geos.point.Point._get_single_external().
y() [2/2]
django.contrib.gis.gdal.raster.source.TransformPoint.y (self, value)
Definition at line 64 of file source.py.
    def y(self, value):
        gtf = self._raster.geotransform
        gtf[self.indices[self._prop][1]] = value
        self._raster.geotransform = gtf
References _prop, _raster, and indices.
Referenced by django.contrib.gis.geos.point.Point._get_single_external().
Member Data Documentation
_prop
django.contrib.gis.gdal.raster.source.TransformPoint._prop = prop protected
Definition at line 47 of file source.py.
Referenced by x(), and y().
_raster
django.contrib.gis.gdal.raster.source.TransformPoint._raster = raster protected
Definition at line 46 of file source.py.
Referenced by x(), and y().
indices
dict django.contrib.gis.gdal.raster.source.TransformPoint.indices static
Initial value:
=  {
        "origin": (0, 3),
        "scale": (1, 5),
        "skew": (2, 4),
    }
Definition at line 36 of file source.py.
Referenced by __init__(), x(), and y().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/gis/gdal/raster/source.py