Read&Watch: pip._internal.utils.misc.ConfiguredBuildBackendHookCaller Class Reference
pip._internal.utils.misc.ConfiguredBuildBackendHookCaller Class Reference
Public Member Functions
__init__ (self, Any config_holder, str source_dir, str build_backend, Optional[str] backend_path=None, Optional[Callable[..., None]] runner=None, Optional[str] python_executable=None)
str build_wheel (self, str wheel_directory, Optional[Dict[str, Union[str, List[str]]]] config_settings=None, Optional[str] metadata_directory=None)
str build_sdist (self, str sdist_directory, Optional[Dict[str, Union[str, List[str]]]] config_settings=None)
str build_editable (self, str wheel_directory, Optional[Dict[str, Union[str, List[str]]]] config_settings=None, Optional[str] metadata_directory=None)
List[str] get_requires_for_build_wheel (self, Optional[Dict[str, Union[str, List[str]]]] config_settings=None)
List[str] get_requires_for_build_sdist (self, Optional[Dict[str, Union[str, List[str]]]] config_settings=None)
List[str] get_requires_for_build_editable (self, Optional[Dict[str, Union[str, List[str]]]] config_settings=None)
str prepare_metadata_for_build_wheel (self, str metadata_directory, Optional[Dict[str, Union[str, List[str]]]] config_settings=None, bool _allow_fallback=True)
str prepare_metadata_for_build_editable (self, str metadata_directory, Optional[Dict[str, Union[str, List[str]]]] config_settings=None, bool _allow_fallback=True)
Public Member Functions inherited from pip._vendor.pyproject_hooks._impl.BuildBackendHookCaller
__init__ (self, source_dir, build_backend, backend_path=None, runner=None, python_executable=None)
subprocess_runner (self, runner)
Public Attributes
config_holder = config_holder
Public Attributes inherited from pip._vendor.pyproject_hooks._impl.BuildBackendHookCaller
source_dir = abspath(source_dir)
build_backend = build_backend
backend_path = backend_path
python_executable = python_executable
Additional Inherited Members
Protected Member Functions inherited from pip._vendor.pyproject_hooks._impl.BuildBackendHookCaller
_supported_features (self)
_call_hook (self, hook_name, kwargs)
Protected Attributes inherited from pip._vendor.pyproject_hooks._impl.BuildBackendHookCaller
_subprocess_runner = runner
Detailed Description
Definition at line 652 of file misc.py.
Constructor & Destructor Documentation
__init__()
pip._internal.utils.misc.ConfiguredBuildBackendHookCaller.__init__ (self, Any config_holder, str source_dir, str build_backend, Optional[str] backend_path = None, Optional[Callable[..., None]] runner = None, Optional[str] python_executable = None)
Definition at line 653 of file misc.py.
    ):
        super().__init__(
            source_dir, build_backend, backend_path, runner, python_executable
        )
        self.config_holder = config_holder
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Function Documentation
build_editable()
str pip._internal.utils.misc.ConfiguredBuildBackendHookCaller.build_editable (self, str wheel_directory, Optional[Dict[str, Union[str, List[str]]]] config_settings = None, Optional[str] metadata_directory = None)
Build an editable wheel from this project.
:returns:
    The name of the newly created wheel within ``wheel_directory``.
.. admonition:: Interaction with fallback
    If the ``build_editable`` hook was called in the fallback for
    :meth:`prepare_metadata_for_build_editable`, the build backend
    would not be invoked. Instead, the previously built wheel will be
    copied to ``wheel_directory`` and the name of that file will be
    returned.
Reimplemented from pip._vendor.pyproject_hooks._impl.BuildBackendHookCaller.
Definition at line 686 of file misc.py.
    ) -> str:
        cs = self.config_holder.config_settings
        return super().build_editable(
            wheel_directory, config_settings=cs, metadata_directory=metadata_directory
        )
References build_editable(), and config_holder.
Referenced by build_editable().
build_sdist()
str pip._internal.utils.misc.ConfiguredBuildBackendHookCaller.build_sdist (self, str sdist_directory, Optional[Dict[str, Union[str, List[str]]]] config_settings = None)
Build an sdist from this project.
:returns:
    The name of the newly created sdist within ``wheel_directory``.
Reimplemented from pip._vendor.pyproject_hooks._impl.BuildBackendHookCaller.
Definition at line 678 of file misc.py.
    ) -> str:
        cs = self.config_holder.config_settings
        return super().build_sdist(sdist_directory, config_settings=cs)
References build_sdist(), and config_holder.
Referenced by build_sdist().
build_wheel()
str pip._internal.utils.misc.ConfiguredBuildBackendHookCaller.build_wheel (self, str wheel_directory, Optional[Dict[str, Union[str, List[str]]]] config_settings = None, Optional[str] metadata_directory = None)
Build a wheel from this project.
:returns:
    The name of the newly created wheel within ``wheel_directory``.
.. admonition:: Interaction with fallback
    If the ``build_wheel`` hook was called in the fallback for
    :meth:`prepare_metadata_for_build_wheel`, the build backend would
    not be invoked. Instead, the previously built wheel will be copied
    to ``wheel_directory`` and the name of that file will be returned.
Reimplemented from pip._vendor.pyproject_hooks._impl.BuildBackendHookCaller.
Definition at line 667 of file misc.py.
    ) -> str:
        cs = self.config_holder.config_settings
        return super().build_wheel(
            wheel_directory, config_settings=cs, metadata_directory=metadata_directory
        )
References build_wheel(), and config_holder.
Referenced by build_wheel().
get_requires_for_build_editable()
List[str] pip._internal.utils.misc.ConfiguredBuildBackendHookCaller.get_requires_for_build_editable (self, Optional[Dict[str, Union[str, List[str]]]] config_settings = None)
Get additional dependencies required for building an editable wheel.
:returns: A list of :pep:`dependency specifiers <508>`.
:rtype: list[str]
.. admonition:: Fallback
    If the build backend does not defined a hook with this name, an
    empty list will be returned.
Reimplemented from pip._vendor.pyproject_hooks._impl.BuildBackendHookCaller.
Definition at line 709 of file misc.py.
    ) -> List[str]:
        cs = self.config_holder.config_settings
        return super().get_requires_for_build_editable(config_settings=cs)
References config_holder, and get_requires_for_build_editable().
Referenced by get_requires_for_build_editable().
get_requires_for_build_sdist()
List[str] pip._internal.utils.misc.ConfiguredBuildBackendHookCaller.get_requires_for_build_sdist (self, Optional[Dict[str, Union[str, List[str]]]] config_settings = None)
Get additional dependencies required for building an sdist.
:returns: A list of :pep:`dependency specifiers <508>`.
:rtype: list[str]
Reimplemented from pip._vendor.pyproject_hooks._impl.BuildBackendHookCaller.
Definition at line 703 of file misc.py.
    ) -> List[str]:
        cs = self.config_holder.config_settings
        return super().get_requires_for_build_sdist(config_settings=cs)
References config_holder, and get_requires_for_build_sdist().
Referenced by get_requires_for_build_sdist().
get_requires_for_build_wheel()
List[str] pip._internal.utils.misc.ConfiguredBuildBackendHookCaller.get_requires_for_build_wheel (self, Optional[Dict[str, Union[str, List[str]]]] config_settings = None)
Get additional dependencies required for building a wheel.
:returns: A list of :pep:`dependency specifiers <508>`.
:rtype: list[str]
.. admonition:: Fallback
    If the build backend does not defined a hook with this name, an
    empty list will be returned.
Reimplemented from pip._vendor.pyproject_hooks._impl.BuildBackendHookCaller.
Definition at line 697 of file misc.py.
    ) -> List[str]:
        cs = self.config_holder.config_settings
        return super().get_requires_for_build_wheel(config_settings=cs)
References config_holder, and get_requires_for_build_wheel().
Referenced by get_requires_for_build_wheel().
prepare_metadata_for_build_editable()
str pip._internal.utils.misc.ConfiguredBuildBackendHookCaller.prepare_metadata_for_build_editable (self, str metadata_directory, Optional[Dict[str, Union[str, List[str]]]] config_settings = None, bool _allow_fallback = True)
Prepare a ``*.dist-info`` folder with metadata for this project.
:returns: Name of the newly created subfolder within
          ``metadata_directory``, containing the metadata.
:rtype: str
.. admonition:: Fallback
    If the build backend does not define a hook with this name and
    ``_allow_fallback`` is truthy, the backend will be asked to build a
    wheel via the ``build_editable`` hook and the dist-info
    extracted from that will be returned.
Reimplemented from pip._vendor.pyproject_hooks._impl.BuildBackendHookCaller.
Definition at line 728 of file misc.py.
    ) -> str:
        cs = self.config_holder.config_settings
        return super().prepare_metadata_for_build_editable(
            metadata_directory=metadata_directory,
            config_settings=cs,
            _allow_fallback=_allow_fallback,
        )
References config_holder, and prepare_metadata_for_build_editable().
Referenced by prepare_metadata_for_build_editable().
prepare_metadata_for_build_wheel()
str pip._internal.utils.misc.ConfiguredBuildBackendHookCaller.prepare_metadata_for_build_wheel (self, str metadata_directory, Optional[Dict[str, Union[str, List[str]]]] config_settings = None, bool _allow_fallback = True)
Prepare a ``*.dist-info`` folder with metadata for this project.
:returns: Name of the newly created subfolder within
          ``metadata_directory``, containing the metadata.
:rtype: str
.. admonition:: Fallback
    If the build backend does not define a hook with this name and
    ``_allow_fallback`` is truthy, the backend will be asked to build a
    wheel via the ``build_wheel`` hook and the dist-info extracted from
    that will be returned.
Reimplemented from pip._vendor.pyproject_hooks._impl.BuildBackendHookCaller.
Definition at line 715 of file misc.py.
    ) -> str:
        cs = self.config_holder.config_settings
        return super().prepare_metadata_for_build_wheel(
            metadata_directory=metadata_directory,
            config_settings=cs,
            _allow_fallback=_allow_fallback,
        )
References config_holder, and prepare_metadata_for_build_wheel().
Referenced by prepare_metadata_for_build_wheel().
Member Data Documentation
config_holder
pip._internal.utils.misc.ConfiguredBuildBackendHookCaller.config_holder = config_holder
Definition at line 665 of file misc.py.
Referenced by build_editable(), build_sdist(), build_wheel(), get_requires_for_build_editable(), get_requires_for_build_sdist(), get_requires_for_build_wheel(), prepare_metadata_for_build_editable(), and prepare_metadata_for_build_wheel().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_internal/utils/misc.py