Read&Watch: astroid.interpreter.objectmodel.DictModel Class Reference
astroid.interpreter.objectmodel.DictModel Class Reference
Public Member Functions
attr___class__ (self)
attr_items (self)
attr_keys (self)
attr_values (self)
Public Member Functions inherited from astroid.interpreter.objectmodel.ObjectModel
__init__ (self)
__repr__ (self)
__call__ (self, instance)
__get__ (self, instance, cls=None)
bool __contains__ (self, name)
list[str] attributes (self)
lookup (self, name)
bases.BoundMethod attr___new__ (self)
bases.BoundMethod attr___init__ (self)
Protected Member Functions
_generic_dict_attribute (self, obj, name)
Additional Inherited Members
Protected Attributes inherited from astroid.interpreter.objectmodel.ObjectModel
_instance = None
Detailed Description
Definition at line 852 of file objectmodel.py.
Member Function Documentation
_generic_dict_attribute()
astroid.interpreter.objectmodel.DictModel._generic_dict_attribute (self, obj, name) protected
Generate a bound method that can infer the given *obj*.
Definition at line 857 of file objectmodel.py.
    def _generic_dict_attribute(self, obj, name):
        """Generate a bound method that can infer the given *obj*."""
        class DictMethodBoundMethod(astroid.BoundMethod):
            def infer_call_result(
                self,
                caller: SuccessfulInferenceResult | None,
                context: InferenceContext | None = None,
            ) -> Iterator[InferenceResult]:
                yield obj
        meth = next(self._instance._proxied.igetattr(name), None)
        return DictMethodBoundMethod(proxy=meth, bound=self._instance)
References astroid.interpreter.objectmodel.ObjectModel._instance.
Referenced by attr_items(), attr_keys(), and attr_values().
attr___class__()
astroid.interpreter.objectmodel.DictModel.attr___class__ (self)
Definition at line 854 of file objectmodel.py.
    def attr___class__(self):
        return self._instance._proxied
References astroid.interpreter.objectmodel.ObjectModel._instance.
attr_items()
astroid.interpreter.objectmodel.DictModel.attr_items (self)
Definition at line 872 of file objectmodel.py.
    def attr_items(self):
        from astroid import objects  # pylint: disable=import-outside-toplevel
        elems = []
        obj = node_classes.List(parent=self._instance)
        for key, value in self._instance.items:
            elem = node_classes.Tuple(parent=obj)
            elem.postinit((key, value))
            elems.append(elem)
        obj.postinit(elts=elems)
        items_obj = objects.DictItems(obj)
        return self._generic_dict_attribute(items_obj, "items")
References _generic_dict_attribute(), and astroid.interpreter.objectmodel.ObjectModel._instance.
attr_keys()
astroid.interpreter.objectmodel.DictModel.attr_keys (self)
Definition at line 887 of file objectmodel.py.
    def attr_keys(self):
        from astroid import objects  # pylint: disable=import-outside-toplevel
        keys = [key for (key, _) in self._instance.items]
        obj = node_classes.List(parent=self._instance)
        obj.postinit(elts=keys)
        keys_obj = objects.DictKeys(obj)
        return self._generic_dict_attribute(keys_obj, "keys")
References _generic_dict_attribute(), and astroid.interpreter.objectmodel.ObjectModel._instance.
attr_values()
astroid.interpreter.objectmodel.DictModel.attr_values (self)
Definition at line 898 of file objectmodel.py.
    def attr_values(self):
        from astroid import objects  # pylint: disable=import-outside-toplevel
        values = [value for (_, value) in self._instance.items]
        obj = node_classes.List(parent=self._instance)
        obj.postinit(values)
        values_obj = objects.DictValues(obj)
        return self._generic_dict_attribute(values_obj, "values")
References _generic_dict_attribute(), and astroid.interpreter.objectmodel.ObjectModel._instance.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/astroid/interpreter/objectmodel.py