Read&Watch: apscheduler.executors.pool.BasePoolExecutor Class Reference
apscheduler.executors.pool.BasePoolExecutor Class Reference
Public Member Functions
__init__ (self, pool)
shutdown (self, wait=True)
Public Member Functions inherited from apscheduler.executors.base.BaseExecutor
__init__ (self)
start (self, scheduler, alias)
submit_job (self, job, run_times)
Protected Member Functions
_do_submit_job (self, job, run_times)
Protected Member Functions inherited from apscheduler.executors.base.BaseExecutor
_run_job_success (self, job_id, events)
_run_job_error (self, job_id, exc, traceback=None)
Protected Attributes
_pool = pool
Protected Attributes inherited from apscheduler.executors.base.BaseExecutor
_instances = defaultdict(lambda: 0)
Additional Inherited Members
Static Protected Attributes inherited from apscheduler.executors.base.BaseExecutor
_scheduler = None
_lock = None
_logger = logging.getLogger("apscheduler.executors")
Detailed Description
Definition at line 9 of file pool.py.
Constructor & Destructor Documentation
__init__()
apscheduler.executors.pool.BasePoolExecutor.__init__ (self, pool)
Definition at line 11 of file pool.py.
    def __init__(self, pool):
        super().__init__()
        self._pool = pool
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Function Documentation
_do_submit_job()
apscheduler.executors.pool.BasePoolExecutor._do_submit_job (self, job, run_times) protected
Performs the actual task of scheduling `run_job` to be called.
Reimplemented from apscheduler.executors.base.BaseExecutor.
Reimplemented in apscheduler.executors.pool.ProcessPoolExecutor.
Definition at line 15 of file pool.py.
    def _do_submit_job(self, job, run_times):
        def callback(f):
            exc, tb = (
                f.exception_info()
                if hasattr(f, "exception_info")
                else (f.exception(), getattr(f.exception(), "__traceback__", None))
            )
            if exc:
                self._run_job_error(job.id, exc, tb)
            else:
                self._run_job_success(job.id, f.result())
        f = self._pool.submit(
            run_job, job, job._jobstore_alias, run_times, self._logger.name
        )
        f.add_done_callback(callback)
References apscheduler.executors.base.BaseExecutor._logger, _pool, apscheduler.executors.base.BaseExecutor._run_job_error(), and apscheduler.executors.base.BaseExecutor._run_job_success().
shutdown()
apscheduler.executors.pool.BasePoolExecutor.shutdown (self, wait = True)
Shuts down this executor.
:param bool wait: ``True`` to wait until all submitted jobs
    have been executed
Reimplemented from apscheduler.executors.base.BaseExecutor.
Definition at line 32 of file pool.py.
    def shutdown(self, wait=True):
        self._pool.shutdown(wait)
References _pool, and shutdown().
Referenced by shutdown().
Member Data Documentation
_pool
apscheduler.executors.pool.BasePoolExecutor._pool = pool protected
Definition at line 13 of file pool.py.
Referenced by _do_submit_job(), pip._vendor.urllib3.response.HTTPResponse._error_catcher(), urllib3.response.HTTPResponse._error_catcher(), pip._vendor.urllib3.response.HTTPResponse.release_conn(), urllib3.contrib.emscripten.response.EmscriptenHttpResponseWrapper.release_conn(), urllib3.response.HTTPResponse.release_conn(), and shutdown().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/apscheduler/executors/pool.py