Read&Watch: django.contrib.postgres.fields.ranges.DateRangeField Class Reference
django.contrib.postgres.fields.ranges.DateRangeField Class Reference
Public Member Functions
db_type (self, connection)
Public Member Functions inherited from django.contrib.postgres.fields.ranges.RangeField
__init__ (self, *args, **kwargs)
model (self)
model (self, model)
get_placeholder (self, value, compiler, connection)
get_prep_value (self, value)
to_python (self, value)
set_attributes_from_name (self, name)
value_to_string (self, obj)
formfield (self, **kwargs)
Public Member Functions inherited from django.db.models.fields.Field
__init__ (self, verbose_name=None, name=None, primary_key=False, max_length=None, unique=False, blank=False, null=False, db_index=False, rel=None, default=NOT_PROVIDED, editable=True, serialize=True, unique_for_date=None, unique_for_month=None, unique_for_year=None, choices=None, help_text="", db_column=None, db_tablespace=None, auto_created=False, validators=(), error_messages=None, db_comment=None, db_default=NOT_PROVIDED)
__str__ (self)
__repr__ (self)
check (self, **kwargs)
get_col (self, alias, output_field=None)
choices (self)
choices (self, value)
cached_col (self)
select_format (self, compiler, sql, params)
deconstruct (self)
clone (self)
__eq__ (self, other)
__lt__ (self, other)
__hash__ (self)
__deepcopy__ (self, memodict)
__copy__ (self)
__reduce__ (self)
get_pk_value_on_save (self, instance)
error_messages (self)
validators (self)
run_validators (self, value)
validate (self, value, model_instance)
clean (self, value, model_instance)
db_type_parameters (self, connection)
db_check (self, connection)
rel_db_type (self, connection)
cast_db_type (self, connection)
db_parameters (self, connection)
db_type_suffix (self, connection)
get_db_converters (self, connection)
unique (self)
db_tablespace (self)
db_returning (self)
contribute_to_class (self, cls, name, private_only=False)
get_filter_kwargs_for_object (self, obj)
get_attname (self)
get_attname_column (self)
get_internal_type (self)
pre_save (self, model_instance, add)
get_db_prep_value (self, value, connection, prepared=False)
get_db_prep_save (self, value, connection)
has_default (self)
get_default (self)
get_choices (self, include_blank=True, blank_choice=BLANK_CHOICE_DASH, limit_choices_to=None, ordering=())
flatchoices (self)
save_form_data (self, instance, data)
value_from_object (self, obj)
slice_expression (self, expression, start, length)
Public Member Functions inherited from django.db.models.query_utils.RegisterLookupMixin
get_class_lookups (cls)
get_instance_lookups (self)
get_lookup (self, lookup_name)
get_transform (self, lookup_name)
register_class_lookup (cls, lookup, lookup_name=None)
register_instance_lookup (self, lookup, lookup_name=None)
Static Public Attributes
range_type = DateRange
Static Public Attributes inherited from django.db.models.fields.Field
bool empty_strings_allowed = True
empty_values = list(validators.EMPTY_VALUES)
int creation_counter = 0
int auto_creation_counter = -1
list default_validators = []
dict default_error_messages
system_check_deprecated_details = None
system_check_removed_details = None
tuple non_db_attrs
bool hidden = False
many_to_many = None
many_to_one = None
one_to_many = None
one_to_one = None
related_model = None
bool generated = False
descriptor_class = DeferredAttribute
Static Public Attributes inherited from django.db.models.query_utils.RegisterLookupMixin
get_lookups = class_or_instance_method(get_class_lookups, get_instance_lookups)
get_class_lookups = classmethod(get_class_lookups)
register_lookup
register_class_lookup = classmethod(register_class_lookup)
Additional Inherited Members
Static Public Member Functions inherited from django.db.models.query_utils.RegisterLookupMixin
merge_dicts (dicts)
Public Attributes inherited from django.contrib.postgres.fields.ranges.RangeField
base_field = self.base_field()
form_field
Public Attributes inherited from django.db.models.fields.Field
str name = name
str verbose_name = verbose_name
primary_key = primary_key
max_length
blank
null = blank, null
remote_field = rel
is_relation = self.remote_field is not None
default = default
db_default = db_default
editable = editable
serialize = serialize
unique_for_date = unique_for_date
unique_for_month = unique_for_month
unique_for_year = unique_for_year
choices = choices
help_text = help_text
db_index = db_index
db_column = db_column
db_comment = db_comment
auto_created = auto_created
validators
error_messages = []
attname = self.name or name
column = self.get_attname_column()
concrete = self.column is not None
Public Attributes inherited from django.db.models.query_utils.RegisterLookupMixin
dict class_lookups = {}
dict instance_lookups = {}
Protected Member Functions inherited from django.contrib.postgres.fields.ranges.RangeField
_choices_is_value (cls, value)
Protected Member Functions inherited from django.db.models.fields.Field
_description (self)
_check_field_name (self)
_check_choices (self)
_check_db_default (self, databases=None, **kwargs)
_check_db_index (self)
_check_db_comment (self, databases=None, **kwargs)
_check_null_allowed_for_primary_keys (self)
_check_backend_specific_checks (self, databases=None, **kwargs)
_check_validators (self)
_check_deprecation_details (self)
_get_default (self)
_db_default_expression (self)
Protected Member Functions inherited from django.db.models.query_utils.RegisterLookupMixin
_get_lookup (self, lookup_name)
_clear_cached_class_lookups (cls)
_unregister_class_lookup (cls, lookup, lookup_name=None)
_unregister_instance_lookup (self, lookup, lookup_name=None)
Protected Attributes inherited from django.db.models.fields.Field
_verbose_name = verbose_name
_unique = max_length, unique
_db_tablespace = db_tablespace
_validators = list(validators)
_error_messages = error_messages
_db_default_expression = connections[db]
_choices = normalize_choices(value)
_get_FIELD_display
Static Protected Attributes inherited from django.db.models.query_utils.RegisterLookupMixin
_unregister_lookup
_unregister_class_lookup = classmethod(_unregister_class_lookup)
Properties inherited from django.db.models.fields.Field
description = property(_description)
Detailed Description
Definition at line 203 of file ranges.py.
Member Function Documentation
db_type()
django.contrib.postgres.fields.ranges.DateRangeField.db_type (self, connection)
Return the database column data type for this field, for the provided
connection.
Reimplemented from django.db.models.fields.Field.
Definition at line 208 of file ranges.py.
    def db_type(self, connection):
        return "daterange"
Referenced by django.db.models.fields.Field.cast_db_type(), django.db.models.fields.Field.db_parameters(), django.db.models.fields.related.ForeignKey.db_parameters(), django.contrib.postgres.fields.ranges.RangeField.get_placeholder(), django.db.models.fields.Field.rel_db_type(), and django.db.models.fields.PositiveIntegerRelDbTypeMixin.rel_db_type().
Member Data Documentation
range_type
django.contrib.postgres.fields.ranges.DateRangeField.range_type = DateRange static
Definition at line 205 of file ranges.py.
Referenced by django.contrib.postgres.forms.ranges.BaseRangeField.compress(), django.contrib.postgres.fields.ranges.ContinuousRangeField.get_prep_value(), django.contrib.postgres.fields.ranges.RangeField.get_prep_value(), and django.contrib.postgres.fields.ranges.RangeField.to_python().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/postgres/fields/ranges.py