Read&Watch: django.utils.autoreload.BaseReloader Class Reference
django.utils.autoreload.BaseReloader Class Reference
Public Member Functions
__init__ (self)
watch_dir (self, path, glob)
watched_files (self, include_globs=True)
wait_for_apps_ready (self, app_reg, django_main_thread)
run (self, django_main_thread)
run_loop (self)
tick (self)
check_availability (cls)
notify_file_changed (self, path)
should_stop (self)
stop (self)
Public Attributes
extra_files = set()
directory_globs = defaultdict(set)
should_stop
Protected Attributes
_stop_condition = threading.Event()
Detailed Description
Definition at line 279 of file autoreload.py.
Constructor & Destructor Documentation
__init__()
django.utils.autoreload.BaseReloader.__init__ (self)
Definition at line 280 of file autoreload.py.
    def __init__(self):
        self.extra_files = set()
        self.directory_globs = defaultdict(set)
        self._stop_condition = threading.Event()
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
check_availability()
django.utils.autoreload.BaseReloader.check_availability (cls)
Reimplemented in django.utils.autoreload.StatReloader, and django.utils.autoreload.WatchmanReloader.
Definition at line 366 of file autoreload.py.
    def check_availability(cls):
        raise NotImplementedError("subclasses must implement check_availability().")
notify_file_changed()
django.utils.autoreload.BaseReloader.notify_file_changed (self, path)
Definition at line 369 of file autoreload.py.
    def notify_file_changed(self, path):
        results = file_changed.send(sender=self, file_path=path)
        logger.debug("%s notified as changed. Signal results: %s.", path, results)
        if not any(res[1] for res in results):
            trigger_reload(path)
References django.utils.autoreload.trigger_reload().
Referenced by django.utils.autoreload.WatchmanReloader._check_subscription(), and django.utils.autoreload.StatReloader.tick().
run()
django.utils.autoreload.BaseReloader.run (self, django_main_thread)
Definition at line 329 of file autoreload.py.
    def run(self, django_main_thread):
        logger.debug("Waiting for apps ready_event.")
        self.wait_for_apps_ready(apps, django_main_thread)
        from django.urls import get_resolver
        # Prevent a race condition where URL modules aren't loaded when the
        # reloader starts by accessing the urlconf_module property.
        try:
            get_resolver().urlconf_module
        except Exception:
            # Loading the urlconf can result in errors during development.
            # If this occurs then swallow the error and continue.
            pass
        logger.debug("Apps ready_event triggered. Sending autoreload_started signal.")
        autoreload_started.send(sender=self)
        self.run_loop()
References run_loop(), and wait_for_apps_ready().
Referenced by pylint.pyreverse.main.Run.__init__(), and pip._internal.cli.base_command.Command._run_wrapper().
run_loop()
django.utils.autoreload.BaseReloader.run_loop (self)
Definition at line 346 of file autoreload.py.
    def run_loop(self):
        ticker = self.tick()
        while not self.should_stop:
            try:
                next(ticker)
            except StopIteration:
                break
        self.stop()
References tick().
Referenced by run().
should_stop()
django.utils.autoreload.BaseReloader.should_stop (self)
Definition at line 377 of file autoreload.py.
    def should_stop(self):
        return self._stop_condition.is_set()
References _stop_condition.
stop()
django.utils.autoreload.BaseReloader.stop (self)
Reimplemented in django.utils.autoreload.WatchmanReloader.
Definition at line 380 of file autoreload.py.
    def stop(self):
        self._stop_condition.set()
References _stop_condition.
Referenced by pip._vendor.rich.live.Live.__exit__(), pip._vendor.rich.progress.Progress.__exit__(), pip._vendor.rich.status.Status.__exit__(), responses.RequestsMock.__exit__(), and pip._vendor.rich.live.Live.start().
tick()
django.utils.autoreload.BaseReloader.tick (self)
This generator is called in a loop from run_loop. It's important that
the method takes care of pausing or otherwise waiting for a period of
time. This split between run_loop() and tick() is to improve the
testability of the reloader implementations by decoupling the work they
do from the loop.
Reimplemented in django.utils.autoreload.StatReloader, and django.utils.autoreload.WatchmanReloader.
Definition at line 355 of file autoreload.py.
    def tick(self):
        """
        This generator is called in a loop from run_loop. It's important that
        the method takes care of pausing or otherwise waiting for a period of
        time. This split between run_loop() and tick() is to improve the
        testability of the reloader implementations by decoupling the work they
        do from the loop.
        """
        raise NotImplementedError("subclasses must implement tick().")
Referenced by run_loop().
wait_for_apps_ready()
django.utils.autoreload.BaseReloader.wait_for_apps_ready (self, app_reg, django_main_thread)
Wait until Django reports that the apps have been loaded. If the given
thread has terminated before the apps are ready, then a SyntaxError or
other non-recoverable error has been raised. In that case, stop waiting
for the apps_ready event and continue processing.
Return True if the thread is alive and the ready event has been
triggered, or False if the thread is terminated while waiting for the
event.
Definition at line 311 of file autoreload.py.
    def wait_for_apps_ready(self, app_reg, django_main_thread):
        """
        Wait until Django reports that the apps have been loaded. If the given
        thread has terminated before the apps are ready, then a SyntaxError or
        other non-recoverable error has been raised. In that case, stop waiting
        for the apps_ready event and continue processing.
        Return True if the thread is alive and the ready event has been
        triggered, or False if the thread is terminated while waiting for the
        event.
        """
        while django_main_thread.is_alive():
            if app_reg.ready_event.wait(timeout=0.1):
                return True
        else:
            logger.debug("Main Django thread has terminated before apps are ready.")
            return False
Referenced by run().
watch_dir()
django.utils.autoreload.BaseReloader.watch_dir (self, path, glob)
Definition at line 285 of file autoreload.py.
    def watch_dir(self, path, glob):
        path = Path(path)
        try:
            path = path.absolute()
        except FileNotFoundError:
            logger.debug(
                "Unable to watch directory %s as it cannot be resolved.",
                path,
                exc_info=True,
            )
            return
        logger.debug("Watching dir %s with glob %s.", path, glob)
        self.directory_globs[path].add(glob)
References directory_globs.
watched_files()
django.utils.autoreload.BaseReloader.watched_files (self, include_globs = True)
Yield all files that need to be watched, including module files and
files within globs.
Definition at line 299 of file autoreload.py.
    def watched_files(self, include_globs=True):
        """
        Yield all files that need to be watched, including module files and
        files within globs.
        """
        yield from iter_all_python_module_files()
        yield from self.extra_files
        if include_globs:
            for directory, patterns in self.directory_globs.items():
                for pattern in patterns:
                    yield from directory.glob(pattern)
References directory_globs, extra_files, and django.utils.autoreload.iter_all_python_module_files().
Referenced by django.utils.autoreload.WatchmanReloader._update_watches(), and django.utils.autoreload.StatReloader.snapshot_files().
Member Data Documentation
_stop_condition
django.utils.autoreload.BaseReloader._stop_condition = threading.Event() protected
Definition at line 283 of file autoreload.py.
Referenced by should_stop(), and stop().
directory_globs
django.utils.autoreload.BaseReloader.directory_globs = defaultdict(set)
Definition at line 282 of file autoreload.py.
Referenced by django.utils.autoreload.WatchmanReloader._update_watches(), watch_dir(), watched_files(), and django.utils.autoreload.WatchmanReloader.watched_roots().
extra_files
django.utils.autoreload.BaseReloader.extra_files = set()
Definition at line 281 of file autoreload.py.
Referenced by watched_files().
should_stop
django.utils.autoreload.BaseReloader.should_stop
Definition at line 348 of file autoreload.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/utils/autoreload.py