Read&Watch: apscheduler.triggers.cron.expressions.AllExpression Class Reference
apscheduler.triggers.cron.expressions.AllExpression Class Reference
Public Member Functions
__init__ (self, step=None)
validate_range (self, field_name)
get_next_value (self, date, field)
__eq__ (self, other)
__str__ (self)
__repr__ (self)
Public Attributes
int step = asint(step)
Static Public Attributes
value_re = re.compile(r"\*(?:/(?P<step>\d+))?$")
Detailed Description
Definition at line 33 of file expressions.py.
Constructor & Destructor Documentation
__init__()
apscheduler.triggers.cron.expressions.AllExpression.__init__ (self, step = None)
Definition at line 36 of file expressions.py.
    def __init__(self, step=None):
        self.step = asint(step)
        if self.step == 0:
            raise ValueError("Increment must be higher than 0")
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
__eq__()
apscheduler.triggers.cron.expressions.AllExpression.__eq__ (self, other)
Definition at line 66 of file expressions.py.
    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.step == other.step
References __class__, and step.
Referenced by pip._vendor.distlib.version.Version.__ge__(), pip._vendor.distlib.version.Version.__gt__(), pip._vendor.distlib.version.Version.__le__(), dotenv.variables.Atom.__ne__(), pip._vendor.distlib.version.Matcher.__ne__(), pip._vendor.distlib.version.Version.__ne__(), pip._vendor.msgpack.ext.Timestamp.__ne__(), pip._vendor.urllib3._collections.HTTPHeaderDict.__ne__(), responses.BaseResponse.__ne__(), and urllib3._collections.HTTPHeaderDict.__ne__().
__repr__()
apscheduler.triggers.cron.expressions.AllExpression.__repr__ (self)
Definition at line 74 of file expressions.py.
    def __repr__(self):
        return f"{self.__class__.__name__}({self.step})"
__str__()
apscheduler.triggers.cron.expressions.AllExpression.__str__ (self)
Definition at line 69 of file expressions.py.
    def __str__(self):
        if self.step:
            return "*/%d" % self.step
        return "*"
References step.
Referenced by PIL.PdfParser.IndirectReference.__bytes__().
get_next_value()
apscheduler.triggers.cron.expressions.AllExpression.get_next_value (self, date, field)
Reimplemented in apscheduler.triggers.cron.expressions.LastDayOfMonthExpression, apscheduler.triggers.cron.expressions.RangeExpression, and apscheduler.triggers.cron.expressions.WeekdayPositionExpression.
Definition at line 51 of file expressions.py.
    def get_next_value(self, date, field):
        start = field.get_value(date)
        minval = field.get_min(date)
        maxval = field.get_max(date)
        start = max(start, minval)
        if not self.step:
            next = start
        else:
            distance_to_next = (self.step - (start - minval)) % self.step
            next = start + distance_to_next
        if next <= maxval:
            return next
References step.
validate_range()
apscheduler.triggers.cron.expressions.AllExpression.validate_range (self, field_name)
Reimplemented in apscheduler.triggers.cron.expressions.RangeExpression.
Definition at line 41 of file expressions.py.
    def validate_range(self, field_name):
        from apscheduler.triggers.cron.fields import MAX_VALUES, MIN_VALUES
        value_range = MAX_VALUES[field_name] - MIN_VALUES[field_name]
        if self.step and self.step > value_range:
            raise ValueError(
                f"the step value ({self.step}) is higher than the total range of the "
                f"expression ({value_range})"
            )
References step.
Member Data Documentation
step
int apscheduler.triggers.cron.expressions.AllExpression.step = asint(step)
Definition at line 37 of file expressions.py.
Referenced by __eq__(), apscheduler.triggers.cron.expressions.RangeExpression.__repr__(), __str__(), apscheduler.triggers.cron.expressions.RangeExpression.__str__(), astroid.nodes.node_classes.Slice.get_children(), get_next_value(), astroid.nodes.node_classes.Slice.igetattr(), astroid.nodes.node_classes.Slice.postinit(), validate_range(), and apscheduler.triggers.cron.expressions.RangeExpression.validate_range().
value_re
apscheduler.triggers.cron.expressions.AllExpression.value_re = re.compile(r"\*(?:/(?P<step>\d+))?$") static
Definition at line 34 of file expressions.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/apscheduler/triggers/cron/expressions.py