Read&Watch: django.forms.fields.IntegerField Class Reference
django.forms.fields.IntegerField Class Reference
Public Member Functions
__init__ (self, *, max_value=None, min_value=None, step_size=None, **kwargs)
to_python (self, value)
widget_attrs (self, widget)
Public Member Functions inherited from django.forms.fields.Field
__init__ (self, *, required=True, widget=None, label=None, initial=None, help_text="", error_messages=None, show_hidden_initial=False, validators=(), localize=False, disabled=False, label_suffix=None, template_name=None)
prepare_value (self, value)
validate (self, value)
run_validators (self, value)
clean (self, value)
bound_data (self, data, initial)
has_changed (self, initial, data)
get_bound_field (self, form, field_name)
__deepcopy__ (self, memo)
Public Attributes
max_value
min_value
step_size = max_value, min_value, step_size
Public Attributes inherited from django.forms.fields.Field
required
label
initial = required, label, initial
show_hidden_initial = show_hidden_initial
help_text = help_text
disabled = disabled
label_suffix = label_suffix
localize = localize
error_messages = messages
list validators = [*self.default_validators, *validators]
template_name = template_name
Static Public Attributes
re_decimal = _lazy_re_compile(r"\.0*\s*$")
Static Public Attributes inherited from django.forms.fields.Field
widget = TextInput
tuple hidden_widget
list default_validators = []
dict default_error_messages
empty_values = list(validators.EMPTY_VALUES)
Additional Inherited Members
Protected Member Functions inherited from django.forms.fields.Field
_clean_bound_field (self, bf)
Detailed Description
Definition at line 305 of file fields.py.
Constructor & Destructor Documentation
__init__()
django.forms.fields.IntegerField.__init__ (self, * , max_value = None, min_value = None, step_size = None, ** kwargs)
Definition at line 312 of file fields.py.
    def __init__(self, *, max_value=None, min_value=None, step_size=None, **kwargs):
        self.max_value, self.min_value, self.step_size = max_value, min_value, step_size
        if kwargs.get("localize") and self.widget == NumberInput:
            # Localized number input is not well supported on most browsers
            kwargs.setdefault("widget", super().widget)
        super().__init__(**kwargs)
        if max_value is not None:
            self.validators.append(validators.MaxValueValidator(max_value))
        if min_value is not None:
            self.validators.append(validators.MinValueValidator(min_value))
        if step_size is not None:
            self.validators.append(
                validators.StepValueValidator(step_size, offset=min_value)
            )
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
to_python()
django.forms.fields.IntegerField.to_python (self, value)
Validate that int() can be called on the input. Return the result
of int() or None for empty values.
Reimplemented from django.forms.fields.Field.
Reimplemented in django.forms.fields.DecimalField, and django.forms.fields.FloatField.
Definition at line 328 of file fields.py.
    def to_python(self, value):
        """
        Validate that int() can be called on the input. Return the result
        of int() or None for empty values.
        """
        value = super().to_python(value)
        if value in self.empty_values:
            return None
        if self.localize:
            value = formats.sanitize_separators(value)
        # Strip trailing decimal and zeros.
        try:
            value = int(self.re_decimal.sub("", str(value)))
        except (ValueError, TypeError):
            raise ValidationError(self.error_messages["invalid"], code="invalid")
        return value
References to_python().
Referenced by to_python().
widget_attrs()
django.forms.fields.IntegerField.widget_attrs (self, widget)
Given a Widget instance (*not* a Widget class), return a dictionary of
any HTML attributes that should be added to the Widget, based on this
Field.
Reimplemented from django.forms.fields.Field.
Reimplemented in django.forms.fields.DecimalField, and django.forms.fields.FloatField.
Definition at line 345 of file fields.py.
    def widget_attrs(self, widget):
        attrs = super().widget_attrs(widget)
        if isinstance(widget, NumberInput):
            if self.min_value is not None:
                attrs["min"] = self.min_value
            if self.max_value is not None:
                attrs["max"] = self.max_value
            if self.step_size is not None:
                attrs["step"] = self.step_size
        return attrs
References max_value, min_value, step_size, and widget_attrs().
Referenced by widget_attrs().
Member Data Documentation
max_value
django.forms.fields.IntegerField.max_value
Definition at line 313 of file fields.py.
Referenced by widget_attrs().
min_value
django.forms.fields.IntegerField.min_value
Definition at line 313 of file fields.py.
Referenced by widget_attrs().
re_decimal
django.forms.fields.IntegerField.re_decimal = _lazy_re_compile(r"\.0*\s*$") static
Definition at line 310 of file fields.py.
step_size
django.forms.fields.IntegerField.step_size = max_value, min_value, step_size
Definition at line 313 of file fields.py.
Referenced by django.forms.fields.FloatField.widget_attrs(), and widget_attrs().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/forms/fields.py