Read&Watch: PIL.TiffImagePlugin.IFDRational Class Reference
PIL.TiffImagePlugin.IFDRational Class Reference
Public Member Functions
None __init__ (self, float|Fraction|IFDRational value, int denominator=1)
IntegralLike numerator (self)
int denominator (self)
tuple[IntegralLike, int] limit_rational (self, int max_denominator)
str __repr__ (self)
int __hash__ (self)
bool __eq__ (self, object other)
list[float|Fraction|IntegralLike] __getstate__ (self)
None __setstate__ (self, list[float|Fraction|IntegralLike] state)
Public Attributes
int denominator = 0:
numerator
Protected Attributes
Fraction|float _val
IntegralLike _numerator = value.numerator
int _denominator = value.denominator
Detailed Description
Implements a rational class where 0/0 is a legal value to match
the in the wild use of exif rationals.
e.g., DigitalZoomRatio - 0.00/0.00  indicates that no digital zoom was used
 If the denominator is 0, store this as a float('nan'), otherwise store
as a fractions.Fraction(). Delegate as appropriate
Definition at line 334 of file TiffImagePlugin.py.
Constructor & Destructor Documentation
__init__()
None PIL.TiffImagePlugin.IFDRational.__init__ (self, float | Fraction | IFDRational value, int denominator = 1)
:param value: either an integer numerator, a
float/rational/other number, or an IFDRational
:param denominator: Optional integer denominator
Definition at line 348 of file TiffImagePlugin.py.
    ) -> None:
        """
        :param value: either an integer numerator, a
        float/rational/other number, or an IFDRational
        :param denominator: Optional integer denominator
        """
        self._val: Fraction | float
        if isinstance(value, IFDRational):
            self._numerator = value.numerator
            self._denominator = value.denominator
            self._val = value._val
            return
        if isinstance(value, Fraction):
            self._numerator = value.numerator
            self._denominator = value.denominator
        else:
            if TYPE_CHECKING:
                self._numerator = cast(IntegralLike, value)
            else:
                self._numerator = value
            self._denominator = denominator
        if denominator == 0:
            self._val = float("nan")
        elif denominator == 1:
            self._val = Fraction(value)
        elif int(value) == value:
            self._val = Fraction(int(value), denominator)
        else:
            self._val = Fraction(value / denominator)
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
__eq__()
bool PIL.TiffImagePlugin.IFDRational.__eq__ (self, object other)
Definition at line 410 of file TiffImagePlugin.py.
    def __eq__(self, other: object) -> bool:
        val = self._val
        if isinstance(other, IFDRational):
            other = other._val
        if isinstance(other, float):
            val = float(val)
        return val == other
References _val.
Referenced by pip._vendor.distlib.version.Version.__ge__(), pip._vendor.distlib.version.Version.__gt__(), pip._vendor.distlib.version.Version.__le__(), dotenv.variables.Atom.__ne__(), pip._vendor.distlib.version.Matcher.__ne__(), pip._vendor.distlib.version.Version.__ne__(), pip._vendor.msgpack.ext.Timestamp.__ne__(), pip._vendor.urllib3._collections.HTTPHeaderDict.__ne__(), responses.BaseResponse.__ne__(), and urllib3._collections.HTTPHeaderDict.__ne__().
__getstate__()
list[float | Fraction | IntegralLike] PIL.TiffImagePlugin.IFDRational.__getstate__ (self)
Definition at line 418 of file TiffImagePlugin.py.
    def __getstate__(self) -> list[float | Fraction | IntegralLike]:
        return [self._val, self._numerator, self._denominator]
References _denominator, _numerator, and _val.
__hash__()
int PIL.TiffImagePlugin.IFDRational.__hash__ (self)
Definition at line 407 of file TiffImagePlugin.py.
    def __hash__(self) -> int:
        return self._val.__hash__()
References __hash__(), and _val.
Referenced by pip._vendor.rich.style.Style.__eq__(), __hash__(), and pip._vendor.rich.style.Style.__ne__().
__repr__()
str PIL.TiffImagePlugin.IFDRational.__repr__ (self)
Definition at line 404 of file TiffImagePlugin.py.
    def __repr__(self) -> str:
        return str(float(self._val))
References _val.
__setstate__()
None PIL.TiffImagePlugin.IFDRational.__setstate__ (self, list[float | Fraction | IntegralLike] state)
Definition at line 421 of file TiffImagePlugin.py.
    def __setstate__(self, state: list[float | Fraction | IntegralLike]) -> None:
        IFDRational.__init__(self, 0)
        _val, _numerator, _denominator = state
        assert isinstance(_val, (float, Fraction))
        self._val = _val
        if TYPE_CHECKING:
            self._numerator = cast(IntegralLike, _numerator)
        else:
            self._numerator = _numerator
        assert isinstance(_denominator, int)
        self._denominator = _denominator
References PIL.TiffImagePlugin._delegate(), _denominator, _numerator, and _val.
denominator()
int PIL.TiffImagePlugin.IFDRational.denominator (self)
Definition at line 387 of file TiffImagePlugin.py.
    def denominator(self) -> int:
        return self._denominator
References _denominator.
limit_rational()
tuple[IntegralLike, int] PIL.TiffImagePlugin.IFDRational.limit_rational (self, int max_denominator)
:param max_denominator: Integer, the maximum denominator value
:returns: Tuple of (numerator, denominator)
Definition at line 390 of file TiffImagePlugin.py.
    def limit_rational(self, max_denominator: int) -> tuple[IntegralLike, int]:
        """
        :param max_denominator: Integer, the maximum denominator value
        :returns: Tuple of (numerator, denominator)
        """
        if self.denominator == 0:
            return self.numerator, self.denominator
        assert isinstance(self._val, Fraction)
        f = self._val.limit_denominator(max_denominator)
        return f.numerator, f.denominator
numerator()
IntegralLike PIL.TiffImagePlugin.IFDRational.numerator (self)
Definition at line 383 of file TiffImagePlugin.py.
    def numerator(self) -> IntegralLike:
        return self._numerator
References _numerator.
Member Data Documentation
_denominator
int PIL.TiffImagePlugin.IFDRational._denominator = value.denominator protected
Definition at line 359 of file TiffImagePlugin.py.
Referenced by __getstate__(), __setstate__(), and denominator().
_numerator
PIL.TiffImagePlugin.IFDRational._numerator = value.numerator protected
Definition at line 358 of file TiffImagePlugin.py.
Referenced by __getstate__(), __setstate__(), and numerator().
_val
PIL.TiffImagePlugin.IFDRational._val protected
Definition at line 356 of file TiffImagePlugin.py.
Referenced by __eq__(), __getstate__(), __hash__(), __repr__(), and __setstate__().
denominator
int PIL.TiffImagePlugin.IFDRational.denominator = 0:
Definition at line 397 of file TiffImagePlugin.py.
numerator
PIL.TiffImagePlugin.IFDRational.numerator
Definition at line 398 of file TiffImagePlugin.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/PIL/TiffImagePlugin.py