Read&Watch: django.test.utils.override_system_checks Class Reference
django.test.utils.override_system_checks Class Reference
Public Member Functions
__init__ (self, new_checks, deployment_checks=None)
enable (self)
disable (self)
Public Member Functions inherited from django.test.utils.TestContextDecorator
__init__ (self, attr_name=None, kwarg_name=None)
__enter__ (self)
__exit__ (self, exc_type, exc_value, traceback)
decorate_class (self, cls)
decorate_callable (self, func)
__call__ (self, decorated)
Public Attributes
registry = registry
new_checks = new_checks
deployment_checks = deployment_checks
old_checks = self.registry.registered_checks
old_deployment_checks = self.registry.deployment_checks
Public Attributes inherited from django.test.utils.TestContextDecorator
attr_name = attr_name
kwarg_name = kwarg_name
setUp = setUp
Detailed Description
Act as a decorator. Override list of registered system checks.
Useful when you override `INSTALLED_APPS`, e.g. if you exclude `auth` app,
you also need to exclude its system checks.
Definition at line 593 of file utils.py.
Constructor & Destructor Documentation
__init__()
django.test.utils.override_system_checks.__init__ (self, new_checks, deployment_checks = None)
Definition at line 600 of file utils.py.
    def __init__(self, new_checks, deployment_checks=None):
        from django.core.checks.registry import registry
        self.registry = registry
        self.new_checks = new_checks
        self.deployment_checks = deployment_checks
        super().__init__()
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
disable()
django.test.utils.override_system_checks.disable (self)
Reimplemented from django.test.utils.TestContextDecorator.
Definition at line 619 of file utils.py.
    def disable(self):
        self.registry.registered_checks = self.old_checks
        self.registry.deployment_checks = self.old_deployment_checks
References old_checks, old_deployment_checks, and registry.
Referenced by pylint.lint.pylinter.PyLinter._parse_error_mode(), pylint.lint.message_state_handler._MessageStateHandler.disable_noerror_messages(), and pylint.lint.pylinter.PyLinter.register_checker().
enable()
django.test.utils.override_system_checks.enable (self)
Reimplemented from django.test.utils.TestContextDecorator.
Definition at line 608 of file utils.py.
    def enable(self):
        self.old_checks = self.registry.registered_checks
        self.registry.registered_checks = set()
        for check in self.new_checks:
            self.registry.register(check, *getattr(check, "tags", ()))
        self.old_deployment_checks = self.registry.deployment_checks
        if self.deployment_checks is not None:
            self.registry.deployment_checks = set()
            for check in self.deployment_checks:
                self.registry.register(check, *getattr(check, "tags", ()), deploy=True)
Referenced by pylint.lint.pylinter.PyLinter.enable_fail_on_messages().
Member Data Documentation
deployment_checks
django.test.utils.override_system_checks.deployment_checks = deployment_checks
Definition at line 605 of file utils.py.
new_checks
django.test.utils.override_system_checks.new_checks = new_checks
Definition at line 604 of file utils.py.
old_checks
django.test.utils.override_system_checks.old_checks = self.registry.registered_checks
Definition at line 609 of file utils.py.
Referenced by disable().
old_deployment_checks
django.test.utils.override_system_checks.old_deployment_checks = self.registry.deployment_checks
Definition at line 613 of file utils.py.
Referenced by disable().
registry
django.test.utils.override_system_checks.registry = registry
Definition at line 603 of file utils.py.
Referenced by disable().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/test/utils.py