Read&Watch: django.core.files.storage.memory.TimingMixin Class Reference
django.core.files.storage.memory.TimingMixin Class Reference
Public Attributes
created_time = now()
accessed_time = self.created_time
modified_time = self.created_time
Protected Member Functions
_initialize_times (self)
_update_accessed_time (self)
_update_modified_time (self)
Detailed Description
Definition at line 27 of file memory.py.
Member Function Documentation
_initialize_times()
django.core.files.storage.memory.TimingMixin._initialize_times (self) protected
Definition at line 28 of file memory.py.
    def _initialize_times(self):
        self.created_time = now()
        self.accessed_time = self.created_time
        self.modified_time = self.created_time
_update_accessed_time()
django.core.files.storage.memory.TimingMixin._update_accessed_time (self) protected
Definition at line 33 of file memory.py.
    def _update_accessed_time(self):
        self.accessed_time = now()
References accessed_time.
Referenced by django.core.files.storage.memory.InMemoryDirNode._resolve_child(), django.core.files.storage.memory.InMemoryFileNode.open(), and django.core.files.storage.memory.InMemoryDirNode.remove_child().
_update_modified_time()
django.core.files.storage.memory.TimingMixin._update_modified_time (self) protected
Definition at line 36 of file memory.py.
    def _update_modified_time(self):
        self.modified_time = now()
References modified_time.
Referenced by django.core.files.storage.memory.InMemoryDirNode._resolve_child(), django.core.files.storage.memory.InMemoryDirNode.remove_child(), and django.core.files.storage.memory.InMemoryFileNode.write().
Member Data Documentation
accessed_time
django.core.files.storage.memory.TimingMixin.accessed_time = self.created_time
Definition at line 30 of file memory.py.
Referenced by _update_accessed_time().
created_time
django.core.files.storage.memory.TimingMixin.created_time = now()
Definition at line 29 of file memory.py.
modified_time
django.core.files.storage.memory.TimingMixin.modified_time = self.created_time
Definition at line 31 of file memory.py.
Referenced by _update_modified_time().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/core/files/storage/memory.py