Read&Watch: pylint.checkers.classes.class_checker.ClassChecker Class Reference
pylint.checkers.classes.class_checker.ClassChecker Class Reference
Public Member Functions
None __init__ (self, PyLinter linter)
None open (self)
None visit_classdef (self, nodes.ClassDef node)
None leave_classdef (self, nodes.ClassDef node)
None visit_functiondef (self, nodes.FunctionDef node)
None leave_functiondef (self, nodes.FunctionDef node)
None visit_attribute (self, nodes.Attribute node)
None visit_assignattr (self, nodes.AssignAttr node)
None visit_assign (self, nodes.Assign assign_node)
Public Member Functions inherited from pylint.checkers.base_checker.BaseChecker
None __init__ (self, PyLinter linter)
bool __gt__ (self, Any other)
bool __eq__ (self, object other)
int __hash__ (self)
str __repr__ (self)
str __str__ (self)
str get_full_documentation (self, dict[str, MessageDefinitionTuple] msgs, Iterable[tuple[str, OptionDict, Any]] options, Sequence[tuple[str, str, ReportsCallable]] reports, str|None doc=None, str|None module=None, bool show_options=True)
None add_message (self, str msgid, int|None line=None, nodes.NodeNG|None node=None, Any args=None, Confidence|None confidence=None, int|None col_offset=None, int|None end_lineno=None, int|None end_col_offset=None)
None check_consistency (self)
MessageDefinition create_message_definition_from_tuple (self, str msgid, MessageDefinitionTuple msg_tuple)
list[MessageDefinition] messages (self)
None close (self)
Any get_map_data (self)
None reduce_map_data (self, PyLinter linter, list[Any] data)
Public Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
None __init__ (self, _ArgumentsManager arguments_manager)
Static Public Attributes
None visit_asyncfunctiondef = visit_functiondef
None leave_asyncfunctiondef = leave_functiondef
Static Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
str name = ""
dict msgs = {}
tuple reports = ()
bool enabled = True
Static Public Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
tuple options = ()
dict option_groups_descs = {}
Protected Member Functions
Pattern[str] _dummy_rgx (self)
None _check_declare_non_slot (self, nodes.ClassDef node)
None _check_consistent_mro (self, nodes.ClassDef node)
None _check_enum_base (self, nodes.ClassDef node, nodes.ClassDef ancestor)
None _check_proper_bases (self, nodes.ClassDef node)
None _check_typing_final (self, nodes.ClassDef node)
None _check_unused_private_functions (self, nodes.ClassDef node)
None _check_unused_private_variables (self, nodes.ClassDef node)
None _check_unused_private_attributes (self, nodes.ClassDef node)
None _check_attribute_defined_outside_init (self, nodes.ClassDef cnode)
None _check_useless_super_delegation (self, nodes.FunctionDef function)
None _check_property_with_parameters (self, nodes.FunctionDef node)
None _check_invalid_overridden_method (self, nodes.FunctionDef function_node, nodes.FunctionDef parent_function_node)
bool _check_functools_or_not (self, nodes.Attribute decorator)
bool _has_valid_slots (self, nodes.ClassDef node)
None _check_slots (self, nodes.ClassDef node)
list[str] _get_classdef_slots_names (self, nodes.ClassDef node)
list[str] _get_slots_names (self, list[nodes.NodeNG] slots_list)
None _check_redefined_slots (self, nodes.ClassDef node, nodes.NodeNG slots_node, list[nodes.NodeNG] slots_list)
None _check_slots_elt (self, SuccessfulInferenceResult elt, nodes.ClassDef node)
None _check_super_without_brackets (self, nodes.Attribute node)
None _check_invalid_class_object (self, nodes.AssignAttr node)
None _check_in_slots (self, nodes.AssignAttr node)
None _check_classmethod_declaration (self, nodes.Assign node)
None _check_protected_attribute_access (self, nodes.Attribute|nodes.AssignAttr node)
bool _is_type_self_call (self, nodes.NodeNG expr)
None _check_accessed_members (self, nodes.ClassDef node, dict[str, list[_AccessNodes]] accessed)
None _check_first_arg_for_type (self, nodes.FunctionDef node, bool metaclass)
None _check_first_arg_config (self, str|None first, Sequence[str] config, nodes.FunctionDef node, str message, str method_name)
None _check_bases_classes (self, nodes.ClassDef node)
None _check_init (self, nodes.FunctionDef node, nodes.ClassDef klass_node)
None _check_signature (self, nodes.FunctionDef method1, nodes.FunctionDef refmethod, nodes.ClassDef cls)
bool _uses_mandatory_method_param (self, nodes.Attribute|nodes.Assign|nodes.AssignAttr node)
bool _is_mandatory_method_param (self, nodes.NodeNG node)
Protected Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
Any _option_value (self, str opt)
Iterator[ tuple[str, list[tuple[str, OptionDict, Any]]]|tuple[None, dict[str, list[tuple[str, OptionDict, Any]]]]] _options_by_section (self)
Iterator[tuple[str, OptionDict, Any]] _options_and_values (self, Options|None options=None)
Static Protected Member Functions
bool _is_called_inside_special_method (nodes.NodeNG node)
bool _is_classmethod (LocalsDictNodeNG func)
bool _is_inferred_instance (nodes.NodeNG expr, nodes.ClassDef klass)
bool _is_class_or_instance_attribute (str name, nodes.ClassDef klass)
Protected Attributes
_accessed = ScopeAccessMap()
list _first_attrs = []
_mixin_class_rgx = self.linter.config.mixin_class_rgx
tuple _py38_plus = (3, 8)
Protected Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
_arguments_manager = arguments_manager
Additional Inherited Members
Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
linter = linter
messages
Detailed Description
Checker for class nodes.
Checks for :
* methods without self as first argument
* overridden methods signature
* access only to existent members via self
* attributes not defined in the __init__ method
* unreachable code
Definition at line 767 of file class_checker.py.
Constructor & Destructor Documentation
__init__()
None pylint.checkers.classes.class_checker.ClassChecker.__init__ (self, PyLinter linter)
Definition at line 851 of file class_checker.py.
    def __init__(self, linter: PyLinter) -> None:
        super().__init__(linter)
        self._accessed = ScopeAccessMap()
        self._first_attrs: list[str | None] = []
References __init__().
Referenced by __init__().
Member Function Documentation
_check_accessed_members()
None pylint.checkers.classes.class_checker.ClassChecker._check_accessed_members (self, nodes.ClassDef node, dict[str, list[_AccessNodes]] accessed) protected
Check that accessed members are defined.
Definition at line 2053 of file class_checker.py.
    ) -> None:
        """Check that accessed members are defined."""
        excs = ("AttributeError", "Exception", "BaseException")
        for attr, nodes_lst in accessed.items():
            try:
                # is it a class attribute ?
                node.local_attr(attr)
                # yes, stop here
                continue
            except astroid.NotFoundError:
                pass
            # is it an instance attribute of a parent class ?
            try:
                next(node.instance_attr_ancestors(attr))
                # yes, stop here
                continue
            except StopIteration:
                pass
            # is it an instance attribute ?
            try:
                defstmts = node.instance_attr(attr)
            except astroid.NotFoundError:
                pass
            else:
                # filter out augment assignment nodes
                defstmts = [stmt for stmt in defstmts if stmt not in nodes_lst]
                if not defstmts:
                    # only augment assignment for this node, no-member should be
                    # triggered by the typecheck checker
                    continue
                # filter defstmts to only pick the first one when there are
                # several assignments in the same scope
                scope = defstmts[0].scope()
                defstmts = [
                    stmt
                    for i, stmt in enumerate(defstmts)
                    if i == 0 or stmt.scope() is not scope
                ]
                # if there are still more than one, don't attempt to be smarter
                # than we can be
                if len(defstmts) == 1:
                    defstmt = defstmts[0]
                    # check that if the node is accessed in the same method as
                    # it's defined, it's accessed after the initial assignment
                    frame = defstmt.frame()
                    lno = defstmt.fromlineno
                    for _node in nodes_lst:
                        if (
                            _node.frame() is frame
                            and _node.fromlineno < lno
                            and not astroid.are_exclusive(
                                _node.statement(), defstmt, excs
                            )
                        ):
                            self.add_message(
                                "access-member-before-definition",
                                node=_node,
                                args=(attr, lno),
                            )
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by _check_attribute_defined_outside_init().
_check_attribute_defined_outside_init()
None pylint.checkers.classes.class_checker.ClassChecker._check_attribute_defined_outside_init (self, nodes.ClassDef cnode) protected
Definition at line 1197 of file class_checker.py.
    def _check_attribute_defined_outside_init(self, cnode: nodes.ClassDef) -> None:
        # check access to existent members on non metaclass classes
        if (
            "attribute-defined-outside-init"
            in self.linter.config.ignored_checks_for_mixins
            and self._mixin_class_rgx.match(cnode.name)
        ):
            # We are in a mixin class. No need to try to figure out if
            # something is missing, since it is most likely that it will
            # miss.
            return
        accessed = self._accessed.accessed(cnode)
        if cnode.type != "metaclass":
            self._check_accessed_members(cnode, accessed)
        # checks attributes are defined in an allowed method such as __init__
        if not self.linter.is_message_enabled("attribute-defined-outside-init"):
            return
        defining_methods = self.linter.config.defining_attr_methods
        current_module = cnode.root()
        for attr, nodes_lst in cnode.instance_attrs.items():
            # Exclude `__dict__` as it is already defined.
            if attr == "__dict__":
                continue
            # Skip nodes which are not in the current module and it may screw up
            # the output, while it's not worth it
            nodes_lst = [
                n
                for n in nodes_lst
                if not isinstance(n.statement(), (nodes.Delete, nodes.AugAssign))
                and n.root() is current_module
            ]
            if not nodes_lst:
                continue  # error detected by typechecking
            # Check if any method attr is defined in is a defining method
            # or if we have the attribute defined in a setter.
            frames = (node.frame() for node in nodes_lst)
            if any(
                frame.name in defining_methods or is_property_setter(frame)
                for frame in frames
            ):
                continue
            # check attribute is defined in a parent's __init__
            for parent in cnode.instance_attr_ancestors(attr):
                attr_defined = False
                # check if any parent method attr is defined in is a defining method
                for node in parent.instance_attrs[attr]:
                    if node.frame().name in defining_methods:
                        attr_defined = True
                if attr_defined:
                    # we're done :)
                    break
            else:
                # check attribute is defined as a class attribute
                try:
                    cnode.local_attr(attr)
                except astroid.NotFoundError:
                    for node in nodes_lst:
                        if node.frame().name not in defining_methods:
                            # If the attribute was set by a call in any
                            # of the defining methods, then don't emit
                            # the warning.
                            if _called_in_methods(
                                node.frame(), cnode, defining_methods
                            ):
                                continue
                            self.add_message(
                                "attribute-defined-outside-init", args=attr, node=node
                            )
References _accessed, pylint.checkers.classes.class_checker._called_in_methods(), _check_accessed_members(), pylint.checkers.async.AsyncChecker._mixin_class_rgx, _mixin_class_rgx, pylint.checkers.base_checker.BaseChecker.add_message(), and pylint.checkers.base_checker.BaseChecker.linter.
Referenced by leave_classdef().
_check_bases_classes()
None pylint.checkers.classes.class_checker.ClassChecker._check_bases_classes (self, nodes.ClassDef node) protected
Check that the given class node implements abstract methods from
base classes.
Definition at line 2209 of file class_checker.py.
    def _check_bases_classes(self, node: nodes.ClassDef) -> None:
        """Check that the given class node implements abstract methods from
        base classes.
        """
        def is_abstract(method: nodes.FunctionDef) -> bool:
            return method.is_abstract(pass_is_abstract=False)  # type: ignore[no-any-return]
        # check if this class abstract
        if class_is_abstract(node):
            return
        methods = sorted(
            unimplemented_abstract_methods(node, is_abstract).items(),
            key=lambda item: item[0],
        )
        for name, method in methods:
            owner = method.parent.frame()
            if owner is node:
                continue
            # owner is not this class, it must be a parent class
            # check that the ancestor's method is not abstract
            if name in node.locals:
                # it is redefined as an attribute or with a descriptor
                continue
            self.add_message(
                "abstract-method",
                node=node,
                args=(name, owner.name, node.name),
                confidence=INFERENCE,
            )
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_classdef().
_check_classmethod_declaration()
None pylint.checkers.classes.class_checker.ClassChecker._check_classmethod_declaration (self, nodes.Assign node) protected
Checks for uses of classmethod() or staticmethod().
When a @classmethod or @staticmethod decorator should be used instead.
A message will be emitted only if the assignment is at a class scope
and only if the classmethod's argument belongs to the class where it
is defined.
`node` is an assign node.
Definition at line 1858 of file class_checker.py.
    def _check_classmethod_declaration(self, node: nodes.Assign) -> None:
        """Checks for uses of classmethod() or staticmethod().
        When a @classmethod or @staticmethod decorator should be used instead.
        A message will be emitted only if the assignment is at a class scope
        and only if the classmethod's argument belongs to the class where it
        is defined.
        `node` is an assign node.
        """
        if not isinstance(node.value, nodes.Call):
            return
        # check the function called is "classmethod" or "staticmethod"
        func = node.value.func
        if not isinstance(func, nodes.Name) or func.name not in (
            "classmethod",
            "staticmethod",
        ):
            return
        msg = (
            "no-classmethod-decorator"
            if func.name == "classmethod"
            else "no-staticmethod-decorator"
        )
        # assignment must be at a class scope
        parent_class = node.scope()
        if not isinstance(parent_class, nodes.ClassDef):
            return
        # Check if the arg passed to classmethod is a class member
        classmeth_arg = node.value.args[0]
        if not isinstance(classmeth_arg, nodes.Name):
            return
        method_name = classmeth_arg.name
        if any(method_name == member.name for member in parent_class.mymethods()):
            self.add_message(msg, node=node.targets[0])
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_assign().
_check_consistent_mro()
None pylint.checkers.classes.class_checker.ClassChecker._check_consistent_mro (self, nodes.ClassDef node) protected
Detect that a class has a consistent mro or duplicate bases.
Definition at line 933 of file class_checker.py.
    def _check_consistent_mro(self, node: nodes.ClassDef) -> None:
        """Detect that a class has a consistent mro or duplicate bases."""
        try:
            node.mro()
        except astroid.InconsistentMroError:
            self.add_message("inconsistent-mro", args=node.name, node=node)
        except astroid.DuplicateBasesError:
            self.add_message("duplicate-bases", args=node.name, node=node)
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_classdef().
_check_declare_non_slot()
None pylint.checkers.classes.class_checker.ClassChecker._check_declare_non_slot (self, nodes.ClassDef node) protected
Definition at line 890 of file class_checker.py.
    def _check_declare_non_slot(self, node: nodes.ClassDef) -> None:
        if not self._has_valid_slots(node):
            return
        slot_names = self._get_classdef_slots_names(node)
        # Stop if empty __slots__ in the class body, this likely indicates that
        # this class takes part in multiple inheritance with other slotted classes.
        if not slot_names:
            return
        # Stop if we find __dict__, since this means attributes can be set
        # dynamically
        if "__dict__" in slot_names:
            return
        for base in node.bases:
            ancestor = safe_infer(base)
            if not isinstance(ancestor, nodes.ClassDef):
                continue
            # if any base doesn't have __slots__, attributes can be set dynamically, so stop
            if not self._has_valid_slots(ancestor):
                return
            for slot_name in self._get_classdef_slots_names(ancestor):
                if slot_name == "__dict__":
                    return
                slot_names.append(slot_name)
        # Every class in bases has __slots__, our __slots__ is non-empty and there is no __dict__
        for child in node.body:
            if isinstance(child, nodes.AnnAssign):
                if child.value is not None:
                    continue
                if isinstance(child.target, nodes.AssignName):
                    if child.target.name not in slot_names:
                        self.add_message(
                            "declare-non-slot",
                            args=child.target.name,
                            node=child.target,
                            confidence=INFERENCE,
                        )
References _get_classdef_slots_names(), _has_valid_slots(), and pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_classdef().
_check_enum_base()
None pylint.checkers.classes.class_checker.ClassChecker._check_enum_base (self, nodes.ClassDef node, nodes.ClassDef ancestor) protected
Definition at line 942 of file class_checker.py.
    def _check_enum_base(self, node: nodes.ClassDef, ancestor: nodes.ClassDef) -> None:
        members = ancestor.getattr("__members__")
        if members and isinstance(members[0], nodes.Dict) and members[0].items:
            for _, name_node in members[0].items:
                # Exempt type annotations without value assignments
                if all(
                    isinstance(item.parent, nodes.AnnAssign)
                    and item.parent.value is None
                    for item in ancestor.getattr(name_node.name)
                ):
                    continue
                self.add_message(
                    "invalid-enum-extension",
                    args=ancestor.name,
                    node=node,
                    confidence=INFERENCE,
                )
                break
        if ancestor.is_subtype_of("enum.IntFlag"):
            # Collect integer flag assignments present on the class
            assignments = defaultdict(list)
            for assign_name in node.nodes_of_class(nodes.AssignName):
                if isinstance(assign_name.parent, nodes.Assign):
                    value = getattr(assign_name.parent.value, "value", None)
                    if isinstance(value, int):
                        assignments[value].append(assign_name)
            # For each bit position, collect all the flags that set the bit
            bit_flags = defaultdict(set)
            for flag in assignments:
                flag_bits = (i for i, c in enumerate(reversed(bin(flag))) if c == "1")
                for bit in flag_bits:
                    bit_flags[bit].add(flag)
            # Collect the minimum, unique values that each flag overlaps with
            overlaps = defaultdict(list)
            for flags in bit_flags.values():
                source, *conflicts = sorted(flags)
                for conflict in conflicts:
                    overlaps[conflict].append(source)
            # Report the overlapping values
            for overlap in overlaps:
                for assignment_node in assignments[overlap]:
                    self.add_message(
                        "implicit-flag-alias",
                        node=assignment_node,
                        args={
                            "overlap": f"<{node.name}.{assignment_node.name}: {overlap}>",
                            "sources": ", ".join(
                                f"<{node.name}.{assignments[source][0].name}: {source}> "
                                f"({overlap} & {source} = {overlap & source})"
                                for source in overlaps[overlap]
                            ),
                        },
                        confidence=INFERENCE,
                    )
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by _check_proper_bases().
_check_first_arg_config()
None pylint.checkers.classes.class_checker.ClassChecker._check_first_arg_config (self, str | None first, Sequence[str] config, nodes.FunctionDef node, str message, str method_name) protected
Definition at line 2193 of file class_checker.py.
    ) -> None:
        if first not in config:
            if len(config) == 1:
                valid = repr(config[0])
            else:
                valid = ", ".join(repr(v) for v in config[:-1])
                valid = f"{valid} or {config[-1]!r}"
            self.add_message(message, args=(method_name, valid), node=node)
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by _check_first_arg_for_type().
_check_first_arg_for_type()
None pylint.checkers.classes.class_checker.ClassChecker._check_first_arg_for_type (self, nodes.FunctionDef node, bool metaclass) protected
Check the name of first argument, expect:.
* 'self' for a regular method
* 'cls' for a class method or a metaclass regular method (actually
  valid-classmethod-first-arg value)
* 'mcs' for a metaclass class method (actually
  valid-metaclass-classmethod-first-arg)
* not one of the above for a static method
Definition at line 2115 of file class_checker.py.
    ) -> None:
        """Check the name of first argument, expect:.
        * 'self' for a regular method
        * 'cls' for a class method or a metaclass regular method (actually
          valid-classmethod-first-arg value)
        * 'mcs' for a metaclass class method (actually
          valid-metaclass-classmethod-first-arg)
        * not one of the above for a static method
        """
        # don't care about functions with unknown argument (builtins)
        if node.args.args is None:
            return
        if node.args.posonlyargs:
            first_arg = node.args.posonlyargs[0].name
        elif node.args.args:
            first_arg = node.argnames()[0]
        else:
            first_arg = None
        self._first_attrs.append(first_arg)
        first = self._first_attrs[-1]
        # static method
        if node.type == "staticmethod":
            if (
                first_arg == "self"
                or first_arg in self.linter.config.valid_classmethod_first_arg
                or first_arg in self.linter.config.valid_metaclass_classmethod_first_arg
            ):
                self.add_message("bad-staticmethod-argument", args=first, node=node)
                return
            self._first_attrs[-1] = None
        elif "builtins.staticmethod" in node.decoratornames():
            # Check if there is a decorator which is not named `staticmethod`
            # but is assigned to one.
            return
        # class / regular method with no args
        elif not (
            node.args.args
            or node.args.posonlyargs
            or node.args.vararg
            or node.args.kwarg
        ):
            self.add_message("no-method-argument", node=node, args=node.name)
        # metaclass
        elif metaclass:
            # metaclass __new__ or classmethod
            if node.type == "classmethod":
                self._check_first_arg_config(
                    first,
                    self.linter.config.valid_metaclass_classmethod_first_arg,
                    node,
                    "bad-mcs-classmethod-argument",
                    node.name,
                )
            # metaclass regular method
            else:
                self._check_first_arg_config(
                    first,
                    self.linter.config.valid_classmethod_first_arg,
                    node,
                    "bad-mcs-method-argument",
                    node.name,
                )
        # regular class with class method
        elif node.type == "classmethod" or node.name == "__class_getitem__":
            self._check_first_arg_config(
                first,
                self.linter.config.valid_classmethod_first_arg,
                node,
                "bad-classmethod-argument",
                node.name,
            )
        # regular class with regular method without self as argument
        elif first != "self":
            self.add_message("no-self-argument", node=node, args=node.name)
References _check_first_arg_config(), _first_attrs, pylint.checkers.base_checker.BaseChecker.add_message(), and pylint.checkers.base_checker.BaseChecker.linter.
Referenced by visit_functiondef(), and pylint.extensions.no_self_use.NoSelfUseChecker.visit_functiondef().
_check_functools_or_not()
bool pylint.checkers.classes.class_checker.ClassChecker._check_functools_or_not (self, nodes.Attribute decorator) protected
Definition at line 1518 of file class_checker.py.
    def _check_functools_or_not(self, decorator: nodes.Attribute) -> bool:
        if decorator.attrname != "cached_property":
            return False
        if not isinstance(decorator.expr, nodes.Name):
            return False
        _, import_nodes = decorator.expr.lookup(decorator.expr.name)
        if not import_nodes:
            return False
        import_node = import_nodes[0]
        if not isinstance(import_node, (astroid.Import, astroid.ImportFrom)):
            return False
        return "functools" in dict(import_node.names)
Referenced by visit_functiondef().
_check_in_slots()
None pylint.checkers.classes.class_checker.ClassChecker._check_in_slots (self, nodes.AssignAttr node) protected
Check that the given AssignAttr node
is defined in the class slots.
Definition at line 1770 of file class_checker.py.
    def _check_in_slots(self, node: nodes.AssignAttr) -> None:
        """Check that the given AssignAttr node
        is defined in the class slots.
        """
        inferred = safe_infer(node.expr)
        if not isinstance(inferred, astroid.Instance):
            return
        klass = inferred._proxied
        if not has_known_bases(klass):
            return
        if "__slots__" not in klass.locals:
            return
        # If `__setattr__` is defined on the class, then we can't reason about
        # what will happen when assigning to an attribute.
        if any(
            base.locals.get("__setattr__")
            for base in klass.mro()
            if base.qname() != "builtins.object"
        ):
            return
        # If 'typing.Generic' is a base of bases of klass, the cached version
        # of 'slots()' might have been evaluated incorrectly, thus deleted cache entry.
        if any(base.qname() == "typing.Generic" for base in klass.mro()):
            cache = getattr(klass, "__cache", None)
            if cache and cache.get(klass.slots) is not None:
                del cache[klass.slots]
        slots = klass.slots()
        if slots is None:
            return
        # If any ancestor doesn't use slots, the slots
        # defined for this class are superfluous.
        if any(
            "__slots__" not in ancestor.locals
            and ancestor.name not in ("Generic", "object")
            for ancestor in klass.ancestors()
        ):
            return
        if not any(slot.value == node.attrname for slot in slots):
            # If we have a '__dict__' in slots, then
            # assigning any name is valid.
            if not any(slot.value == "__dict__" for slot in slots):
                if _is_attribute_property(node.attrname, klass):
                    # Properties circumvent the slots mechanism,
                    # so we should not emit a warning for them.
                    return
                if node.attrname != "__class__" and utils.is_class_attr(
                    node.attrname, klass
                ):
                    return
                if node.attrname in klass.locals:
                    for local_name in klass.locals.get(node.attrname):
                        statement = local_name.statement()
                        if (
                            isinstance(statement, nodes.AnnAssign)
                            and not statement.value
                        ):
                            return
                    if _has_data_descriptor(klass, node.attrname):
                        # Descriptors circumvent the slots mechanism as well.
                        return
                if node.attrname == "__class__" and _has_same_layout_slots(
                    slots, node.parent.value
                ):
                    return
                self.add_message(
                    "assigning-non-slot",
                    args=(node.attrname,),
                    node=node,
                    confidence=INFERENCE,
                )
References pylint.checkers.classes.class_checker._has_data_descriptor(), pylint.checkers.classes.class_checker._has_same_layout_slots(), pylint.checkers.classes.class_checker._is_attribute_property(), and pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_assignattr().
_check_init()
None pylint.checkers.classes.class_checker.ClassChecker._check_init (self, nodes.FunctionDef node, nodes.ClassDef klass_node) protected
Check that the __init__ method call super or ancestors'__init__
method (unless it is used for type hinting with `typing.overload`).
Definition at line 2242 of file class_checker.py.
    def _check_init(self, node: nodes.FunctionDef, klass_node: nodes.ClassDef) -> None:
        """Check that the __init__ method call super or ancestors'__init__
        method (unless it is used for type hinting with `typing.overload`).
        """
        if not self.linter.is_message_enabled(
            "super-init-not-called"
        ) and not self.linter.is_message_enabled("non-parent-init-called"):
            return
        to_call = _ancestors_to_call(klass_node)
        not_called_yet = dict(to_call)
        parents_with_called_inits: set[bases.UnboundMethod] = set()
        for stmt in node.nodes_of_class(nodes.Call):
            expr = stmt.func
            if not isinstance(expr, nodes.Attribute) or expr.attrname != "__init__":
                continue
            # skip the test if using super
            if (
                isinstance(expr.expr, nodes.Call)
                and isinstance(expr.expr.func, nodes.Name)
                and expr.expr.func.name == "super"
            ):
                return
            # pylint: disable = too-many-try-statements
            try:
                for klass in expr.expr.infer():
                    if isinstance(klass, util.UninferableBase):
                        continue
                    # The inferred klass can be super(), which was
                    # assigned to a variable and the `__init__`
                    # was called later.
                    #
                    # base = super()
                    # base.__init__(...)
                    if (
                        isinstance(klass, astroid.Instance)
                        and isinstance(klass._proxied, nodes.ClassDef)
                        and is_builtin_object(klass._proxied)
                        and klass._proxied.name == "super"
                    ):
                        return
                    if isinstance(klass, astroid.objects.Super):
                        return
                    try:
                        method = not_called_yet.pop(klass)
                        # Record that the class' init has been called
                        parents_with_called_inits.add(node_frame_class(method))
                    except KeyError:
                        if klass not in klass_node.ancestors(recurs=False):
                            self.add_message(
                                "non-parent-init-called", node=expr, args=klass.name
                            )
            except astroid.InferenceError:
                continue
        for klass, method in not_called_yet.items():
            # Check if the init of the class that defines this init has already
            # been called.
            if node_frame_class(method) in parents_with_called_inits:
                return
            if utils.is_protocol_class(klass):
                return
            if decorated_with(node, ["typing.overload"]):
                continue
            self.add_message(
                "super-init-not-called",
                args=klass.name,
                node=node,
                confidence=INFERENCE,
            )
References pylint.checkers.classes.class_checker._ancestors_to_call(), pylint.checkers.base_checker.BaseChecker.add_message(), and pylint.checkers.base_checker.BaseChecker.linter.
Referenced by visit_functiondef().
_check_invalid_class_object()
None pylint.checkers.classes.class_checker.ClassChecker._check_invalid_class_object (self, nodes.AssignAttr node) protected
Definition at line 1742 of file class_checker.py.
    def _check_invalid_class_object(self, node: nodes.AssignAttr) -> None:
        if not node.attrname == "__class__":
            return
        if isinstance(node.parent, nodes.Tuple):
            class_index = -1
            for i, elt in enumerate(node.parent.elts):
                if hasattr(elt, "attrname") and elt.attrname == "__class__":
                    class_index = i
            if class_index == -1:
                # This should not happen because we checked that the node name
                # is '__class__' earlier, but let's not be too confident here
                return  # pragma: no cover
            inferred = safe_infer(node.parent.parent.value.elts[class_index])
        else:
            inferred = safe_infer(node.parent.value)
        if (
            isinstance(inferred, (nodes.ClassDef, util.UninferableBase))
            or inferred is None
        ):
            # If is uninferable, we allow it to prevent false positives
            return
        self.add_message(
            "invalid-class-object",
            node=node,
            args=inferred.__class__.__name__,
            confidence=INFERENCE,
        )
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_assignattr().
_check_invalid_overridden_method()
None pylint.checkers.classes.class_checker.ClassChecker._check_invalid_overridden_method (self, nodes.FunctionDef function_node, nodes.FunctionDef parent_function_node) protected
Definition at line 1468 of file class_checker.py.
    ) -> None:
        parent_is_property = decorated_with_property(
            parent_function_node
        ) or is_property_setter_or_deleter(parent_function_node)
        current_is_property = decorated_with_property(
            function_node
        ) or is_property_setter_or_deleter(function_node)
        if parent_is_property and not current_is_property:
            self.add_message(
                "invalid-overridden-method",
                args=(function_node.name, "property", function_node.type),
                node=function_node,
            )
        elif not parent_is_property and current_is_property:
            self.add_message(
                "invalid-overridden-method",
                args=(function_node.name, "method", "property"),
                node=function_node,
            )
        parent_is_async = isinstance(parent_function_node, nodes.AsyncFunctionDef)
        current_is_async = isinstance(function_node, nodes.AsyncFunctionDef)
        if parent_is_async and not current_is_async:
            self.add_message(
                "invalid-overridden-method",
                args=(function_node.name, "async", "non-async"),
                node=function_node,
            )
        elif not parent_is_async and current_is_async:
            self.add_message(
                "invalid-overridden-method",
                args=(function_node.name, "non-async", "async"),
                node=function_node,
            )
        if (
            decorated_with(parent_function_node, ["typing.final"])
            or uninferable_final_decorators(parent_function_node.decorators)
        ) and self._py38_plus:
            self.add_message(
                "overridden-final-method",
                args=(function_node.name, parent_function_node.parent.frame().name),
                node=function_node,
            )
References pylint.checkers.base.basic_checker.BasicChecker._py38_plus, pylint.checkers.base.basic_error_checker.BasicErrorChecker._py38_plus, _py38_plus, and pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_functiondef().
_check_proper_bases()
None pylint.checkers.classes.class_checker.ClassChecker._check_proper_bases (self, nodes.ClassDef node) protected
Detect that a class inherits something which is not
a class or a type.
Definition at line 1001 of file class_checker.py.
    def _check_proper_bases(self, node: nodes.ClassDef) -> None:
        """Detect that a class inherits something which is not
        a class or a type.
        """
        for base in node.bases:
            ancestor = safe_infer(base)
            if not ancestor:
                continue
            if isinstance(ancestor, astroid.Instance) and (
                ancestor.is_subtype_of("builtins.type")
                or ancestor.is_subtype_of(".Protocol")
            ):
                continue
            if not isinstance(ancestor, nodes.ClassDef) or _is_invalid_base_class(
                ancestor
            ):
                self.add_message("inherit-non-class", args=base.as_string(), node=node)
            if isinstance(ancestor, nodes.ClassDef) and ancestor.is_subtype_of(
                "enum.Enum"
            ):
                self._check_enum_base(node, ancestor)
            if ancestor.name == object.__name__:
                self.add_message(
                    "useless-object-inheritance", args=node.name, node=node
                )
References _check_enum_base(), pylint.checkers.classes.class_checker._is_invalid_base_class(), and pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_classdef().
_check_property_with_parameters()
None pylint.checkers.classes.class_checker.ClassChecker._check_property_with_parameters (self, nodes.FunctionDef node) protected
Definition at line 1460 of file class_checker.py.
    def _check_property_with_parameters(self, node: nodes.FunctionDef) -> None:
        if (
            len(node.args.arguments) > 1
            and decorated_with_property(node)
            and not is_property_setter(node)
        ):
            self.add_message("property-with-parameters", node=node, confidence=HIGH)
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_functiondef().
_check_protected_attribute_access()
None pylint.checkers.classes.class_checker.ClassChecker._check_protected_attribute_access (self, nodes.Attribute | nodes.AssignAttr node) protected
Given an attribute access node (set or get), check if attribute
access is legitimate.
Call _check_first_attr with node before calling
this method. Valid cases are:
* self._attr in a method or cls._attr in a classmethod. Checked by
_check_first_attr.
* Klass._attr inside "Klass" class.
* Klass2._attr inside "Klass" class when Klass2 is a base class of
    Klass.
Definition at line 1897 of file class_checker.py.
    ) -> None:
        """Given an attribute access node (set or get), check if attribute
        access is legitimate.
        Call _check_first_attr with node before calling
        this method. Valid cases are:
        * self._attr in a method or cls._attr in a classmethod. Checked by
        _check_first_attr.
        * Klass._attr inside "Klass" class.
        * Klass2._attr inside "Klass" class when Klass2 is a base class of
            Klass.
        """
        attrname = node.attrname
        if (
            not is_attr_protected(attrname)
            or attrname in self.linter.config.exclude_protected
        ):
            return
        # Typing annotations in function definitions can include protected members
        if utils.is_node_in_type_annotation_context(node):
            return
        # Return if `attrname` is defined at the module-level or as a class attribute
        # and is listed in `exclude-protected`.
        inferred = safe_infer(node.expr)
        if (
            inferred
            and isinstance(inferred, (nodes.ClassDef, nodes.Module))
            and f"{inferred.name}.{attrname}" in self.linter.config.exclude_protected
        ):
            return
        klass = node_frame_class(node)
        if klass is None:
            # We are not in a class, no remaining valid case
            self.add_message("protected-access", node=node, args=attrname)
            return
        # In classes, check we are not getting a parent method
        # through the class object or through super
        # If the expression begins with a call to super, that's ok.
        if (
            isinstance(node.expr, nodes.Call)
            and isinstance(node.expr.func, nodes.Name)
            and node.expr.func.name == "super"
        ):
            return
        # If the expression begins with a call to type(self), that's ok.
        if self._is_type_self_call(node.expr):
            return
        # Check if we are inside the scope of a class or nested inner class
        inside_klass = True
        outer_klass = klass
        callee = node.expr.as_string()
        parents_callee = callee.split(".")
        parents_callee.reverse()
        for callee in parents_callee:
            if not outer_klass or callee != outer_klass.name:
                inside_klass = False
                break
            # Move up one level within the nested classes
            outer_klass = get_outer_class(outer_klass)
        # We are in a class, one remaining valid cases, Klass._attr inside
        # Klass
        if not (inside_klass or callee in klass.basenames):
            # Detect property assignments in the body of the class.
            # This is acceptable:
            #
            # class A:
            #     b = property(lambda: self._b)
            stmt = node.parent.statement()
            if (
                isinstance(stmt, nodes.Assign)
                and len(stmt.targets) == 1
                and isinstance(stmt.targets[0], nodes.AssignName)
            ):
                name = stmt.targets[0].name
                if _is_attribute_property(name, klass):
                    return
            if (
                self._is_classmethod(node.frame())
                and self._is_inferred_instance(node.expr, klass)
                and self._is_class_or_instance_attribute(attrname, klass)
            ):
                return
            licit_protected_member = not attrname.startswith("__")
            if (
                not self.linter.config.check_protected_access_in_special_methods
                and licit_protected_member
                and self._is_called_inside_special_method(node)
            ):
                return
            self.add_message("protected-access", node=node, args=attrname)
References pylint.checkers.classes.class_checker._is_attribute_property(), _is_called_inside_special_method(), _is_class_or_instance_attribute(), _is_classmethod(), _is_inferred_instance(), _is_type_self_call(), pylint.checkers.base_checker.BaseChecker.add_message(), and pylint.checkers.base_checker.BaseChecker.linter.
Referenced by visit_assign(), and visit_attribute().
_check_redefined_slots()
None pylint.checkers.classes.class_checker.ClassChecker._check_redefined_slots (self, nodes.ClassDef node, nodes.NodeNG slots_node, list[nodes.NodeNG] slots_list) protected
Check if `node` redefines a slot which is defined in an ancestor class.
Definition at line 1623 of file class_checker.py.
    ) -> None:
        """Check if `node` redefines a slot which is defined in an ancestor class."""
        slots_names: list[str] = self._get_slots_names(slots_list)
        # Slots of all parent classes
        ancestors_slots_names = {
            slot.value
            for ancestor in node.local_attr_ancestors("__slots__")
            for slot in ancestor.slots() or []
        }
        # Slots which are common to `node` and its parent classes
        redefined_slots = ancestors_slots_names.intersection(slots_names)
        if redefined_slots:
            self.add_message(
                "redefined-slots-in-subclass",
                args=([name for name in slots_names if name in redefined_slots],),
                node=slots_node,
            )
References _get_slots_names(), and pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by _check_slots().
_check_signature()
None pylint.checkers.classes.class_checker.ClassChecker._check_signature (self, nodes.FunctionDef method1, nodes.FunctionDef refmethod, nodes.ClassDef cls) protected
Check that the signature of the two given methods match.
Definition at line 2314 of file class_checker.py.
    ) -> None:
        """Check that the signature of the two given methods match."""
        if not (
            isinstance(method1, nodes.FunctionDef)
            and isinstance(refmethod, nodes.FunctionDef)
        ):
            self.add_message(
                "method-check-failed", args=(method1, refmethod), node=method1
            )
            return
        instance = cls.instantiate_class()
        method1 = astroid.scoped_nodes.function_to_method(method1, instance)
        refmethod = astroid.scoped_nodes.function_to_method(refmethod, instance)
        # Don't care about functions with unknown argument (builtins).
        if method1.args.args is None or refmethod.args.args is None:
            return
        # Ignore private to class methods.
        if is_attr_private(method1.name):
            return
        # Ignore setters, they have an implicit extra argument,
        # which shouldn't be taken in consideration.
        if is_property_setter(method1):
            return
        arg_differ_output = _different_parameters(
            refmethod, method1, dummy_parameter_regex=self._dummy_rgx
        )
        class_type = "overriding"
        if len(arg_differ_output) > 0:
            for msg in arg_differ_output:
                if "Number" in msg:
                    total_args_method1 = len(method1.args.args)
                    if method1.args.vararg:
                        total_args_method1 += 1
                    if method1.args.kwarg:
                        total_args_method1 += 1
                    if method1.args.kwonlyargs:
                        total_args_method1 += len(method1.args.kwonlyargs)
                    total_args_refmethod = len(refmethod.args.args)
                    if refmethod.args.vararg:
                        total_args_refmethod += 1
                    if refmethod.args.kwarg:
                        total_args_refmethod += 1
                    if refmethod.args.kwonlyargs:
                        total_args_refmethod += len(refmethod.args.kwonlyargs)
                    error_type = "arguments-differ"
                    msg_args = (
                        msg
                        + f"was {total_args_refmethod} in '{refmethod.parent.frame().name}.{refmethod.name}' and "
                        f"is now {total_args_method1} in",
                        class_type,
                        f"{method1.parent.frame().name}.{method1.name}",
                    )
                elif "renamed" in msg:
                    error_type = "arguments-renamed"
                    msg_args = (
                        msg,
                        class_type,
                        f"{method1.parent.frame().name}.{method1.name}",
                    )
                else:
                    error_type = "arguments-differ"
                    msg_args = (
                        msg,
                        class_type,
                        f"{method1.parent.frame().name}.{method1.name}",
                    )
                self.add_message(error_type, args=msg_args, node=method1)
        elif (
            len(method1.args.defaults) < len(refmethod.args.defaults)
            and not method1.args.vararg
        ):
            class_type = "overridden"
            self.add_message(
                "signature-differs", args=(class_type, method1.name), node=method1
            )
References pylint.checkers.classes.class_checker._different_parameters(), _dummy_rgx(), pylint.checkers.base_checker.BaseChecker.add_message(), and astroid.nodes.node_ng.NodeNG.instantiate_class().
Referenced by visit_functiondef().
_check_slots()
None pylint.checkers.classes.class_checker.ClassChecker._check_slots (self, nodes.ClassDef node) protected
Definition at line 1558 of file class_checker.py.
    def _check_slots(self, node: nodes.ClassDef) -> None:
        if "__slots__" not in node.locals:
            return
        try:
            inferred_slots = tuple(node.ilookup("__slots__"))
        except astroid.InferenceError:
            return
        for slots in inferred_slots:
            # check if __slots__ is a valid type
            if isinstance(slots, util.UninferableBase):
                continue
            if not is_iterable(slots) and not is_comprehension(slots):
                self.add_message("invalid-slots", node=node)
                continue
            if isinstance(slots, nodes.Const):
                # a string, ignore the following checks
                self.add_message("single-string-used-for-slots", node=node)
                continue
            if not hasattr(slots, "itered"):
                # we can't obtain the values, maybe a .deque?
                continue
            if isinstance(slots, nodes.Dict):
                values = [item[0] for item in slots.items]
            else:
                values = slots.itered()
            if isinstance(values, util.UninferableBase):
                continue
            for elt in values:
                try:
                    self._check_slots_elt(elt, node)
                except astroid.InferenceError:
                    continue
            self._check_redefined_slots(node, slots, values)
References _check_redefined_slots(), _check_slots_elt(), and pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_classdef().
_check_slots_elt()
None pylint.checkers.classes.class_checker.ClassChecker._check_slots_elt (self, SuccessfulInferenceResult elt, nodes.ClassDef node) protected
Definition at line 1649 of file class_checker.py.
    ) -> None:
        for inferred in elt.infer():
            if isinstance(inferred, util.UninferableBase):
                continue
            if not isinstance(inferred, nodes.Const) or not isinstance(
                inferred.value, str
            ):
                self.add_message(
                    "invalid-slots-object",
                    args=elt.as_string(),
                    node=elt,
                    confidence=INFERENCE,
                )
                continue
            if not inferred.value:
                self.add_message(
                    "invalid-slots-object",
                    args=elt.as_string(),
                    node=elt,
                    confidence=INFERENCE,
                )
            # Check if we have a conflict with a class variable.
            class_variable = node.locals.get(inferred.value)
            if class_variable:
                # Skip annotated assignments which don't conflict at all with slots.
                if len(class_variable) == 1:
                    parent = class_variable[0].parent
                    if isinstance(parent, nodes.AnnAssign) and parent.value is None:
                        return
                self.add_message(
                    "class-variable-slots-conflict", args=(inferred.value,), node=elt
                )
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by _check_slots().
_check_super_without_brackets()
None pylint.checkers.classes.class_checker.ClassChecker._check_super_without_brackets (self, nodes.Attribute node) protected
Check if there is a function call on a super call without brackets.
Definition at line 1716 of file class_checker.py.
    def _check_super_without_brackets(self, node: nodes.Attribute) -> None:
        """Check if there is a function call on a super call without brackets."""
        # Check if attribute call is in frame definition in class definition
        frame = node.frame()
        if not isinstance(frame, nodes.FunctionDef):
            return
        if not isinstance(frame.parent.frame(), nodes.ClassDef):
            return
        if not isinstance(node.parent, nodes.Call):
            return
        if not isinstance(node.expr, nodes.Name):
            return
        if node.expr.name == "super":
            self.add_message("super-without-brackets", node=node.expr, confidence=HIGH)
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_attribute().
_check_typing_final()
None pylint.checkers.classes.class_checker.ClassChecker._check_typing_final (self, nodes.ClassDef node) protected
Detect that a class does not subclass a class decorated with
`typing.final`.
Definition at line 1030 of file class_checker.py.
    def _check_typing_final(self, node: nodes.ClassDef) -> None:
        """Detect that a class does not subclass a class decorated with
        `typing.final`.
        """
        if not self._py38_plus:
            return
        for base in node.bases:
            ancestor = safe_infer(base)
            if not ancestor:
                continue
            if isinstance(ancestor, nodes.ClassDef) and (
                decorated_with(ancestor, ["typing.final"])
                or uninferable_final_decorators(ancestor.decorators)
            ):
                self.add_message(
                    "subclassed-final-class",
                    args=(node.name, ancestor.name),
                    node=node,
                )
References pylint.checkers.base.basic_checker.BasicChecker._py38_plus, pylint.checkers.base.basic_error_checker.BasicErrorChecker._py38_plus, _py38_plus, and pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_classdef(), and pylint.checkers.unsupported_version.UnsupportedVersionChecker.visit_decorators().
_check_unused_private_attributes()
None pylint.checkers.classes.class_checker.ClassChecker._check_unused_private_attributes (self, nodes.ClassDef node) protected
Definition at line 1146 of file class_checker.py.
    def _check_unused_private_attributes(self, node: nodes.ClassDef) -> None:
        for assign_attr in node.nodes_of_class(nodes.AssignAttr):
            if not is_attr_private(assign_attr.attrname) or not isinstance(
                assign_attr.expr, nodes.Name
            ):
                continue
            # Logic for checking false positive when using __new__,
            # Get the returned object names of the __new__ magic function
            # Then check if the attribute was consumed in other instance methods
            acceptable_obj_names: list[str] = ["self"]
            scope = assign_attr.scope()
            if isinstance(scope, nodes.FunctionDef) and scope.name == "__new__":
                acceptable_obj_names.extend(
                    [
                        return_node.value.name
                        for return_node in scope.nodes_of_class(nodes.Return)
                        if isinstance(return_node.value, nodes.Name)
                    ]
                )
            for attribute in node.nodes_of_class(nodes.Attribute):
                if attribute.attrname != assign_attr.attrname:
                    continue
                if not isinstance(attribute.expr, nodes.Name):
                    continue
                if assign_attr.expr.name in {
                    "cls",
                    node.name,
                } and attribute.expr.name in {"cls", "self", node.name}:
                    # If assigned to cls or class name, can be accessed by cls/self/class name
                    break
                if (
                    assign_attr.expr.name in acceptable_obj_names
                    and attribute.expr.name == "self"
                ):
                    # If assigned to self.attrib, can only be accessed by self
                    # Or if __new__ was used, the returned object names are acceptable
                    break
                if assign_attr.expr.name == attribute.expr.name == node.name:
                    # Recognise attributes which are accessed via the class name
                    break
            else:
                args = (node.name, assign_attr.attrname)
                self.add_message("unused-private-member", node=assign_attr, args=args)
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by leave_classdef().
_check_unused_private_functions()
None pylint.checkers.classes.class_checker.ClassChecker._check_unused_private_functions (self, nodes.ClassDef node) protected
Definition at line 1067 of file class_checker.py.
    def _check_unused_private_functions(self, node: nodes.ClassDef) -> None:
        for function_def in node.nodes_of_class(nodes.FunctionDef):
            if not is_attr_private(function_def.name):
                continue
            parent_scope = function_def.parent.scope()
            if isinstance(parent_scope, nodes.FunctionDef):
                # Handle nested functions
                if function_def.name in (
                    n.name for n in parent_scope.nodes_of_class(nodes.Name)
                ):
                    continue
            for child in node.nodes_of_class((nodes.Name, nodes.Attribute)):
                # Check for cases where the functions are used as a variable instead of as a
                # method call
                if isinstance(child, nodes.Name) and child.name == function_def.name:
                    break
                if isinstance(child, nodes.Attribute):
                    # Ignore recursive calls
                    if (
                        child.attrname != function_def.name
                        or child.scope() == function_def
                    ):
                        continue
                    # Check self.__attrname, cls.__attrname, node_name.__attrname
                    if isinstance(child.expr, nodes.Name) and child.expr.name in {
                        "self",
                        "cls",
                        node.name,
                    }:
                        break
                    # Check type(self).__attrname
                    if isinstance(child.expr, nodes.Call):
                        inferred = safe_infer(child.expr)
                        if (
                            isinstance(inferred, nodes.ClassDef)
                            and inferred.name == node.name
                        ):
                            break
            else:
                name_stack = []
                curr = parent_scope
                # Generate proper names for nested functions
                while curr != node:
                    name_stack.append(curr.name)
                    curr = curr.parent.scope()
                outer_level_names = f"{'.'.join(reversed(name_stack))}"
                function_repr = f"{outer_level_names}.{function_def.name}({function_def.args.as_string()})"
                self.add_message(
                    "unused-private-member",
                    node=function_def,
                    args=(node.name, function_repr.lstrip(".")),
                )
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by leave_classdef().
_check_unused_private_variables()
None pylint.checkers.classes.class_checker.ClassChecker._check_unused_private_variables (self, nodes.ClassDef node) protected
Check if private variables are never used within a class.
Definition at line 1123 of file class_checker.py.
    def _check_unused_private_variables(self, node: nodes.ClassDef) -> None:
        """Check if private variables are never used within a class."""
        for assign_name in node.nodes_of_class(nodes.AssignName):
            if isinstance(assign_name.parent, nodes.Arguments):
                continue  # Ignore function arguments
            if not is_attr_private(assign_name.name):
                continue
            for child in node.nodes_of_class((nodes.Name, nodes.Attribute)):
                if isinstance(child, nodes.Name) and child.name == assign_name.name:
                    break
                if isinstance(child, nodes.Attribute):
                    if not isinstance(child.expr, nodes.Name):
                        break
                    if child.attrname == assign_name.name and child.expr.name in (
                        "self",
                        "cls",
                        node.name,
                    ):
                        break
            else:
                args = (node.name, assign_name.name)
                self.add_message("unused-private-member", node=assign_name, args=args)
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by leave_classdef().
_check_useless_super_delegation()
None pylint.checkers.classes.class_checker.ClassChecker._check_useless_super_delegation (self, nodes.FunctionDef function) protected
Check if the given function node is an useless method override.
We consider it *useless* if it uses the super() builtin, but having
nothing additional whatsoever than not implementing the method at all.
If the method uses super() to delegate an operation to the rest of the MRO,
and if the method called is the same as the current one, the arguments
passed to super() are the same as the parameters that were passed to
this method, then the method could be removed altogether, by letting
other implementation to take precedence.
Definition at line 1372 of file class_checker.py.
    def _check_useless_super_delegation(self, function: nodes.FunctionDef) -> None:
        """Check if the given function node is an useless method override.
        We consider it *useless* if it uses the super() builtin, but having
        nothing additional whatsoever than not implementing the method at all.
        If the method uses super() to delegate an operation to the rest of the MRO,
        and if the method called is the same as the current one, the arguments
        passed to super() are the same as the parameters that were passed to
        this method, then the method could be removed altogether, by letting
        other implementation to take precedence.
        """
        if not _is_trivial_super_delegation(function):
            return
        call: nodes.Call = function.body[0].value
        # Classes that override __eq__ should also override
        # __hash__, even a trivial override is meaningful
        if function.name == "__hash__":
            for other_method in function.parent.mymethods():
                if other_method.name == "__eq__":
                    return
        # Check values of default args
        klass = function.parent.frame()
        meth_node = None
        for overridden in klass.local_attr_ancestors(function.name):
            # get astroid for the searched method
            try:
                meth_node = overridden[function.name]
            except KeyError:
                # we have found the method but it's not in the local
                # dictionary.
                # This may happen with astroid build from living objects
                continue
            if (
                not isinstance(meth_node, nodes.FunctionDef)
                # If the method have an ancestor which is not a
                # function then it is legitimate to redefine it
                or _has_different_parameters_default_value(
                    meth_node.args, function.args
                )
                # arguments to builtins such as Exception.__init__() cannot be inspected
                or (meth_node.args.args is None and function.argnames() != ["self"])
            ):
                return
            break
        # Detect if the parameters are the same as the call's arguments.
        params = _signature_from_arguments(function.args)
        args = _signature_from_call(call)
        if meth_node is not None:
            # Detect if the super method uses varargs and the function doesn't or makes some of those explicit
            if meth_node.args.vararg and (
                not function.args.vararg
                or len(function.args.args) > len(meth_node.args.args)
            ):
                return
            def form_annotations(arguments: nodes.Arguments) -> list[str]:
                annotations = chain(
                    (arguments.posonlyargs_annotations or []), arguments.annotations
                )
                return [ann.as_string() for ann in annotations if ann is not None]
            called_annotations = form_annotations(function.args)
            overridden_annotations = form_annotations(meth_node.args)
            if called_annotations and overridden_annotations:
                if called_annotations != overridden_annotations:
                    return
            if (
                function.returns is not None
                and meth_node.returns is not None
                and meth_node.returns.as_string() != function.returns.as_string()
            ):
                # Override adds typing information to the return type
                return
        if _definition_equivalent_to_call(params, args):
            self.add_message(
                "useless-parent-delegation",
                node=function,
                args=(function.name,),
                confidence=INFERENCE,
            )
References pylint.checkers.classes.class_checker._definition_equivalent_to_call(), pylint.checkers.classes.class_checker._has_different_parameters_default_value(), pylint.checkers.classes.class_checker._is_trivial_super_delegation(), pylint.checkers.classes.class_checker._signature_from_arguments(), pylint.checkers.classes.class_checker._signature_from_call(), and pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_functiondef().
_dummy_rgx()
Pattern[str] pylint.checkers.classes.class_checker.ClassChecker._dummy_rgx (self) protected
Definition at line 862 of file class_checker.py.
    def _dummy_rgx(self) -> Pattern[str]:
        return self.linter.config.dummy_variables_rgx  # type: ignore[no-any-return]
References pylint.checkers.base_checker.BaseChecker.linter.
Referenced by pylint.checkers.refactoring.refactoring_checker.RefactoringChecker._check_redefined_argument_from_local(), and _check_signature().
_get_classdef_slots_names()
list[str] pylint.checkers.classes.class_checker.ClassChecker._get_classdef_slots_names (self, nodes.ClassDef node) protected
Definition at line 1595 of file class_checker.py.
    def _get_classdef_slots_names(self, node: nodes.ClassDef) -> list[str]:
        slots_names: list[str] = []
        try:
            inferred_slots = tuple(node.ilookup("__slots__"))
        except astroid.InferenceError:  # pragma: no cover
            return slots_names
        for slots in inferred_slots:
            if isinstance(slots, nodes.Dict):
                values = [item[0] for item in slots.items]
            else:
                values = slots.itered()
            slots_names.extend(self._get_slots_names(values))
        return slots_names
References _get_slots_names().
Referenced by _check_declare_non_slot().
_get_slots_names()
list[str] pylint.checkers.classes.class_checker.ClassChecker._get_slots_names (self, list[nodes.NodeNG] slots_list) protected
Definition at line 1611 of file class_checker.py.
    def _get_slots_names(self, slots_list: list[nodes.NodeNG]) -> list[str]:
        slots_names: list[str] = []
        for slot in slots_list:
            if isinstance(slot, nodes.Const):
                slots_names.append(slot.value)
            else:
                inferred_slot = safe_infer(slot)
                inferred_slot_value = getattr(inferred_slot, "value", None)
                if isinstance(inferred_slot_value, str):
                    slots_names.append(inferred_slot_value)
        return slots_names
Referenced by _check_redefined_slots(), and _get_classdef_slots_names().
_has_valid_slots()
bool pylint.checkers.classes.class_checker.ClassChecker._has_valid_slots (self, nodes.ClassDef node) protected
Definition at line 1536 of file class_checker.py.
    def _has_valid_slots(self, node: nodes.ClassDef) -> bool:
        if "__slots__" not in node.locals:
            return False
        try:
            inferred_slots = tuple(node.ilookup("__slots__"))
        except astroid.InferenceError:
            return False
        for slots in inferred_slots:
            # check if __slots__ is a valid type
            if isinstance(slots, util.UninferableBase):
                return False
            if not is_iterable(slots) and not is_comprehension(slots):
                return False
            if isinstance(slots, nodes.Const):
                return False
            if not hasattr(slots, "itered"):
                # we can't obtain the values, maybe a .deque?
                return False
        return True
Referenced by _check_declare_non_slot().
_is_called_inside_special_method()
bool pylint.checkers.classes.class_checker.ClassChecker._is_called_inside_special_method (nodes.NodeNG node) static protected
Returns true if the node is located inside a special (aka dunder) method.
Definition at line 2005 of file class_checker.py.
    def _is_called_inside_special_method(node: nodes.NodeNG) -> bool:
        """Returns true if the node is located inside a special (aka dunder) method."""
        frame_name = node.frame().name
        return frame_name and frame_name in PYMETHODS
Referenced by _check_protected_attribute_access().
_is_class_or_instance_attribute()
bool pylint.checkers.classes.class_checker.ClassChecker._is_class_or_instance_attribute (str name, nodes.ClassDef klass) static protected
Check if the given attribute *name* is a class or instance member of the
given *klass*.
Returns ``True`` if the name is a property in the given klass,
``False`` otherwise.
Definition at line 2037 of file class_checker.py.
    def _is_class_or_instance_attribute(name: str, klass: nodes.ClassDef) -> bool:
        """Check if the given attribute *name* is a class or instance member of the
        given *klass*.
        Returns ``True`` if the name is a property in the given klass,
        ``False`` otherwise.
        """
        if utils.is_class_attr(name, klass):
            return True
        try:
            klass.instance_attr(name)
            return True
        except astroid.NotFoundError:
            return False
Referenced by _check_protected_attribute_access().
_is_classmethod()
bool pylint.checkers.classes.class_checker.ClassChecker._is_classmethod (LocalsDictNodeNG func) static protected
Check if the given *func* node is a class method.
Definition at line 2020 of file class_checker.py.
    def _is_classmethod(func: LocalsDictNodeNG) -> bool:
        """Check if the given *func* node is a class method."""
        return isinstance(func, nodes.FunctionDef) and (
            func.type == "classmethod" or func.name == "__class_getitem__"
        )
Referenced by _check_protected_attribute_access().
_is_inferred_instance()
bool pylint.checkers.classes.class_checker.ClassChecker._is_inferred_instance (nodes.NodeNG expr, nodes.ClassDef klass) static protected
Check if the inferred value of the given *expr* is an instance of
*klass*.
Definition at line 2027 of file class_checker.py.
    def _is_inferred_instance(expr: nodes.NodeNG, klass: nodes.ClassDef) -> bool:
        """Check if the inferred value of the given *expr* is an instance of
        *klass*.
        """
        inferred = safe_infer(expr)
        if not isinstance(inferred, astroid.Instance):
            return False
        return inferred._proxied is klass
Referenced by _check_protected_attribute_access().
_is_mandatory_method_param()
bool pylint.checkers.classes.class_checker.ClassChecker._is_mandatory_method_param (self, nodes.NodeNG node) protected
Check if nodes.Name corresponds to first attribute variable name.
Name is `self` for method, `cls` for classmethod and `mcs` for metaclass.
Static methods return False.
Definition at line 2410 of file class_checker.py.
    def _is_mandatory_method_param(self, node: nodes.NodeNG) -> bool:
        """Check if nodes.Name corresponds to first attribute variable name.
        Name is `self` for method, `cls` for classmethod and `mcs` for metaclass.
        Static methods return False.
        """
        if self._first_attrs:
            first_attr = self._first_attrs[-1]
        else:
            # It's possible the function was already unregistered.
            closest_func = utils.get_node_first_ancestor_of_type(
                node, nodes.FunctionDef
            )
            if closest_func is None:
                return False
            if not closest_func.is_bound():
                return False
            if not closest_func.args.args:
                return False
            first_attr = closest_func.args.args[0].name
        return isinstance(node, nodes.Name) and node.name == first_attr
References _first_attrs.
Referenced by _is_type_self_call(), and _uses_mandatory_method_param().
_is_type_self_call()
bool pylint.checkers.classes.class_checker.ClassChecker._is_type_self_call (self, nodes.NodeNG expr) protected
Definition at line 2010 of file class_checker.py.
    def _is_type_self_call(self, expr: nodes.NodeNG) -> bool:
        return (
            isinstance(expr, nodes.Call)
            and isinstance(expr.func, nodes.Name)
            and expr.func.name == "type"
            and len(expr.args) == 1
            and self._is_mandatory_method_param(expr.args[0])
        )
References _is_mandatory_method_param().
Referenced by _check_protected_attribute_access().
_uses_mandatory_method_param()
bool pylint.checkers.classes.class_checker.ClassChecker._uses_mandatory_method_param (self, nodes.Attribute | nodes.Assign | nodes.AssignAttr node) protected
Check that attribute lookup name use first attribute variable name.
Name is `self` for method, `cls` for classmethod and `mcs` for metaclass.
Definition at line 2401 of file class_checker.py.
    ) -> bool:
        """Check that attribute lookup name use first attribute variable name.
        Name is `self` for method, `cls` for classmethod and `mcs` for metaclass.
        """
        return self._is_mandatory_method_param(node.expr)
References _is_mandatory_method_param().
Referenced by visit_assign(), visit_assignattr(), and visit_attribute().
leave_classdef()
None pylint.checkers.classes.class_checker.ClassChecker.leave_classdef (self, nodes.ClassDef node)
Checker for Class nodes.
check that instance attributes are defined in __init__ and check
access to existent members
Definition at line 1056 of file class_checker.py.
    def leave_classdef(self, node: nodes.ClassDef) -> None:
        """Checker for Class nodes.
        check that instance attributes are defined in __init__ and check
        access to existent members
        """
        self._check_unused_private_functions(node)
        self._check_unused_private_variables(node)
        self._check_unused_private_attributes(node)
        self._check_attribute_defined_outside_init(node)
References _check_attribute_defined_outside_init(), _check_unused_private_attributes(), _check_unused_private_functions(), and _check_unused_private_variables().
leave_functiondef()
None pylint.checkers.classes.class_checker.ClassChecker.leave_functiondef (self, nodes.FunctionDef node)
On method node, check if this method couldn't be a function.
ignore class, static and abstract methods, initializer,
methods overridden from a parent class.
Definition at line 1685 of file class_checker.py.
    def leave_functiondef(self, node: nodes.FunctionDef) -> None:
        """On method node, check if this method couldn't be a function.
        ignore class, static and abstract methods, initializer,
        methods overridden from a parent class.
        """
        if node.is_method():
            if node.args.args is not None:
                self._first_attrs.pop()
References _first_attrs.
open()
None pylint.checkers.classes.class_checker.ClassChecker.open (self)
Called before visiting project (i.e. set of modules).
Reimplemented from pylint.checkers.base_checker.BaseChecker.
Definition at line 856 of file class_checker.py.
    def open(self) -> None:
        self._mixin_class_rgx = self.linter.config.mixin_class_rgx
        py_version = self.linter.config.py_version
        self._py38_plus = py_version >= (3, 8)
Referenced by django.contrib.staticfiles.storage.HashedFilesMixin.hashed_name().
visit_assign()
None pylint.checkers.classes.class_checker.ClassChecker.visit_assign (self, nodes.Assign assign_node)
Definition at line 1848 of file class_checker.py.
    def visit_assign(self, assign_node: nodes.Assign) -> None:
        self._check_classmethod_declaration(assign_node)
        node = assign_node.targets[0]
        if not isinstance(node, nodes.AssignAttr):
            return
        if self._uses_mandatory_method_param(node):
            return
        self._check_protected_attribute_access(node)
References _check_classmethod_declaration(), _check_protected_attribute_access(), and _uses_mandatory_method_param().
visit_assignattr()
None pylint.checkers.classes.class_checker.ClassChecker.visit_assignattr (self, nodes.AssignAttr node)
Definition at line 1734 of file class_checker.py.
    def visit_assignattr(self, node: nodes.AssignAttr) -> None:
        if isinstance(
            node.assign_type(), nodes.AugAssign
        ) and self._uses_mandatory_method_param(node):
            self._accessed.set_accessed(node)
        self._check_in_slots(node)
        self._check_invalid_class_object(node)
References _accessed, _check_in_slots(), _check_invalid_class_object(), and _uses_mandatory_method_param().
visit_attribute()
None pylint.checkers.classes.class_checker.ClassChecker.visit_attribute (self, nodes.Attribute node)
Check if the getattr is an access to a class member
if so, register it.
Also check for access to protected
class member from outside its class (but ignore __special__
methods)
Definition at line 1697 of file class_checker.py.
    def visit_attribute(self, node: nodes.Attribute) -> None:
        """Check if the getattr is an access to a class member
        if so, register it.
        Also check for access to protected
        class member from outside its class (but ignore __special__
        methods)
        """
        self._check_super_without_brackets(node)
        # Check self
        if self._uses_mandatory_method_param(node):
            self._accessed.set_accessed(node)
            return
        if not self.linter.is_message_enabled("protected-access"):
            return
        self._check_protected_attribute_access(node)
References _accessed, _check_protected_attribute_access(), _check_super_without_brackets(), _uses_mandatory_method_param(), and pylint.checkers.base_checker.BaseChecker.linter.
Referenced by pylint.checkers.typecheck.TypeChecker.visit_assignattr(), and pylint.checkers.typecheck.TypeChecker.visit_delattr().
visit_classdef()
None pylint.checkers.classes.class_checker.ClassChecker.visit_classdef (self, nodes.ClassDef node)
Init visit variable _accessed.
Definition at line 881 of file class_checker.py.
    def visit_classdef(self, node: nodes.ClassDef) -> None:
        """Init visit variable _accessed."""
        self._check_bases_classes(node)
        self._check_slots(node)
        self._check_proper_bases(node)
        self._check_typing_final(node)
        self._check_consistent_mro(node)
        self._check_declare_non_slot(node)
References _check_bases_classes(), _check_consistent_mro(), _check_declare_non_slot(), _check_proper_bases(), _check_slots(), and _check_typing_final().
Referenced by pylint.pyreverse.inspector.Linker.visit_assignname(), and pylint.checkers.exceptions.ExceptionRaiseLeafVisitor.visit_instance().
visit_functiondef()
None pylint.checkers.classes.class_checker.ClassChecker.visit_functiondef (self, nodes.FunctionDef node)
Check method arguments, overriding.
Definition at line 1271 of file class_checker.py.
    def visit_functiondef(self, node: nodes.FunctionDef) -> None:
        """Check method arguments, overriding."""
        # ignore actual functions
        if not node.is_method():
            return
        self._check_useless_super_delegation(node)
        self._check_property_with_parameters(node)
        # 'is_method()' is called and makes sure that this is a 'nodes.ClassDef'
        klass: nodes.ClassDef = node.parent.frame()
        # check first argument is self if this is actually a method
        self._check_first_arg_for_type(node, klass.type == "metaclass")
        if node.name == "__init__":
            self._check_init(node, klass)
            return
        # check signature if the method overloads inherited method
        for overridden in klass.local_attr_ancestors(node.name):
            # get astroid for the searched method
            try:
                parent_function = overridden[node.name]
            except KeyError:
                # we have found the method but it's not in the local
                # dictionary.
                # This may happen with astroid build from living objects
                continue
            if not isinstance(parent_function, nodes.FunctionDef):
                continue
            self._check_signature(node, parent_function, klass)
            self._check_invalid_overridden_method(node, parent_function)
            break
        if node.decorators:
            for decorator in node.decorators.nodes:
                if isinstance(decorator, nodes.Attribute) and decorator.attrname in {
                    "getter",
                    "setter",
                    "deleter",
                }:
                    # attribute affectation will call this method, not hiding it
                    return
                if isinstance(decorator, nodes.Name):
                    if decorator.name in ALLOWED_PROPERTIES:
                        # attribute affectation will either call a setter or raise
                        # an attribute error, anyway not hiding the function
                        return
                if isinstance(decorator, nodes.Attribute):
                    if self._check_functools_or_not(decorator):
                        return
                # Infer the decorator and see if it returns something useful
                inferred = safe_infer(decorator)
                if not inferred:
                    return
                if isinstance(inferred, nodes.FunctionDef):
                    # Okay, it's a decorator, let's see what it can infer.
                    try:
                        inferred = next(inferred.infer_call_result(inferred))
                    except astroid.InferenceError:
                        return
                try:
                    if (
                        isinstance(inferred, (astroid.Instance, nodes.ClassDef))
                        and inferred.getattr("__get__")
                        and inferred.getattr("__set__")
                    ):
                        return
                except astroid.AttributeInferenceError:
                    pass
        # check if the method is hidden by an attribute
        # pylint: disable = too-many-try-statements
        try:
            overridden = klass.instance_attr(node.name)[0]
            overridden_frame = overridden.frame()
            if (
                isinstance(overridden_frame, nodes.FunctionDef)
                and overridden_frame.type == "method"
            ):
                overridden_frame = overridden_frame.parent.frame()
            if not (
                isinstance(overridden_frame, nodes.ClassDef)
                and klass.is_subtype_of(overridden_frame.qname())
            ):
                return
            # If a subclass defined the method then it's not our fault.
            for ancestor in klass.ancestors():
                if node.name in ancestor.instance_attrs and is_attr_private(node.name):
                    return
                for obj in ancestor.lookup(node.name)[1]:
                    if isinstance(obj, nodes.FunctionDef):
                        return
            args = (overridden.root().name, overridden.fromlineno)
            self.add_message("method-hidden", args=args, node=node)
        except astroid.NotFoundError:
            pass
References _check_first_arg_for_type(), _check_functools_or_not(), _check_init(), _check_invalid_overridden_method(), _check_property_with_parameters(), _check_signature(), _check_useless_super_delegation(), and pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by pylint.pyreverse.inspector.Linker.visit_assignname().
Member Data Documentation
_accessed
pylint.checkers.classes.class_checker.ClassChecker._accessed = ScopeAccessMap() protected
Definition at line 853 of file class_checker.py.
Referenced by _check_attribute_defined_outside_init(), visit_assignattr(), and visit_attribute().
_first_attrs
list pylint.checkers.classes.class_checker.ClassChecker._first_attrs = [] protected
Definition at line 854 of file class_checker.py.
Referenced by _check_first_arg_for_type(), pylint.extensions.no_self_use.NoSelfUseChecker._check_first_arg_for_type(), _is_mandatory_method_param(), leave_functiondef(), pylint.extensions.no_self_use.NoSelfUseChecker.leave_functiondef(), and pylint.extensions.no_self_use.NoSelfUseChecker.visit_name().
_mixin_class_rgx
pylint.checkers.classes.class_checker.ClassChecker._mixin_class_rgx = self.linter.config.mixin_class_rgx protected
Definition at line 857 of file class_checker.py.
Referenced by _check_attribute_defined_outside_init(), and pylint.checkers.typecheck.TypeChecker.visit_attribute().
_py38_plus
tuple pylint.checkers.classes.class_checker.ClassChecker._py38_plus = (3, 8) protected
Definition at line 859 of file class_checker.py.
Referenced by _check_invalid_overridden_method(), _check_typing_final(), pylint.checkers.unsupported_version.UnsupportedVersionChecker._check_typing_final(), pylint.checkers.unsupported_version.UnsupportedVersionChecker.visit_arguments(), pylint.extensions.code_style.CodeStyleChecker.visit_if(), and pylint.checkers.unsupported_version.UnsupportedVersionChecker.visit_namedexpr().
leave_asyncfunctiondef
None pylint.checkers.classes.class_checker.ClassChecker.leave_asyncfunctiondef = leave_functiondef static
Definition at line 1695 of file class_checker.py.
visit_asyncfunctiondef
None pylint.checkers.classes.class_checker.ClassChecker.visit_asyncfunctiondef = visit_functiondef static
Definition at line 1370 of file class_checker.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pylint/checkers/classes/class_checker.py