Read&Watch: django.contrib.admin.checks.ModelAdminChecks Class Reference
django.contrib.admin.checks.ModelAdminChecks Class Reference
Public Member Functions
check (self, admin_obj, **kwargs)
Protected Member Functions
_check_save_as (self, obj)
_check_save_on_top (self, obj)
_check_inlines (self, obj)
_check_inlines_item (self, obj, inline, label)
_check_list_display (self, obj)
_check_list_display_item (self, obj, item, label)
_check_list_display_links (self, obj)
_check_list_display_links_item (self, obj, field_name, label)
_check_list_filter (self, obj)
_check_list_filter_item (self, obj, item, label)
_check_list_select_related (self, obj)
_check_list_per_page (self, obj)
_check_list_max_show_all (self, obj)
_check_list_editable (self, obj)
_check_list_editable_item (self, obj, field_name, label)
_check_search_fields (self, obj)
_check_date_hierarchy (self, obj)
_check_actions (self, obj)
Protected Member Functions inherited from django.contrib.admin.checks.BaseModelAdminChecks
_check_autocomplete_fields (self, obj)
_check_autocomplete_fields_item (self, obj, field_name, label)
_check_raw_id_fields (self, obj)
_check_raw_id_fields_item (self, obj, field_name, label)
_check_fields (self, obj)
_check_fieldsets (self, obj)
_check_fieldsets_item (self, obj, fieldset, label, seen_fields)
_check_field_spec (self, obj, fields, label)
_check_field_spec_item (self, obj, field_name, label)
_check_exclude (self, obj)
_check_form (self, obj)
_check_filter_vertical (self, obj)
_check_filter_horizontal (self, obj)
_check_filter_item (self, obj, field_name, label)
_check_radio_fields (self, obj)
_check_radio_fields_key (self, obj, field_name, label)
_check_radio_fields_value (self, obj, val, label)
_check_view_on_site_url (self, obj)
_check_prepopulated_fields (self, obj)
_check_prepopulated_fields_key (self, obj, field_name, label)
_check_prepopulated_fields_value (self, obj, val, label)
_check_prepopulated_fields_value_item (self, obj, field_name, label)
_check_ordering (self, obj)
_check_ordering_item (self, obj, field_name, label)
_check_readonly_fields (self, obj)
_check_readonly_fields_item (self, obj, field_name, label)
Detailed Description
Definition at line 803 of file checks.py.
Member Function Documentation
_check_actions()
django.contrib.admin.checks.ModelAdminChecks._check_actions (self, obj) protected
Definition at line 1197 of file checks.py.
    def _check_actions(self, obj):
        errors = []
        actions = obj._get_base_actions()
        # Actions with an allowed_permission attribute require the ModelAdmin
        # to implement a has_<perm>_permission() method for each permission.
        for func, name, _ in actions:
            if not hasattr(func, "allowed_permissions"):
                continue
            for permission in func.allowed_permissions:
                method_name = "has_%s_permission" % permission
                if not hasattr(obj, method_name):
                    errors.append(
                        checks.Error(
                            "%s must define a %s() method for the %s action."
                            % (
                                obj.__class__.__name__,
                                method_name,
                                func.__name__,
                            ),
                            obj=obj.__class__,
                            id="admin.E129",
                        )
                    )
        # Names need to be unique.
        names = collections.Counter(name for _, name, _ in actions)
        for name, count in names.items():
            if count > 1:
                errors.append(
                    checks.Error(
                        "__name__ attributes of actions defined in %s must be "
                        "unique. Name %r is not unique."
                        % (
                            obj.__class__.__name__,
                            name,
                        ),
                        obj=obj.__class__,
                        id="admin.E130",
                    )
                )
        return errors
Referenced by check().
_check_date_hierarchy()
django.contrib.admin.checks.ModelAdminChecks._check_date_hierarchy (self, obj) protected
Check that date_hierarchy refers to DateField or DateTimeField.
Definition at line 1169 of file checks.py.
    def _check_date_hierarchy(self, obj):
        """Check that date_hierarchy refers to DateField or DateTimeField."""
        if obj.date_hierarchy is None:
            return []
        else:
            try:
                field = get_fields_from_path(obj.model, obj.date_hierarchy)[-1]
            except (NotRelationField, FieldDoesNotExist):
                return [
                    checks.Error(
                        "The value of 'date_hierarchy' refers to '%s', which "
                        "does not refer to a Field." % obj.date_hierarchy,
                        obj=obj.__class__,
                        id="admin.E127",
                    )
                ]
            else:
                if field.get_internal_type() not in {"DateField", "DateTimeField"}:
                    return must_be(
                        "a DateField or DateTimeField",
                        option="date_hierarchy",
                        obj=obj,
                        id="admin.E128",
                    )
                else:
                    return []
References django.contrib.admin.checks.must_be().
Referenced by check().
_check_inlines()
django.contrib.admin.checks.ModelAdminChecks._check_inlines (self, obj) protected
Check all inline model admin classes.
Definition at line 838 of file checks.py.
    def _check_inlines(self, obj):
        """Check all inline model admin classes."""
        if not isinstance(obj.inlines, (list, tuple)):
            return must_be(
                "a list or tuple", option="inlines", obj=obj, id="admin.E103"
            )
        else:
            return list(
                chain.from_iterable(
                    self._check_inlines_item(obj, item, "inlines[%d]" % index)
                    for index, item in enumerate(obj.inlines)
                )
            )
References _check_inlines_item(), and django.contrib.admin.checks.must_be().
Referenced by check().
_check_inlines_item()
django.contrib.admin.checks.ModelAdminChecks._check_inlines_item (self, obj, inline, label) protected
Check one inline model admin.
Definition at line 853 of file checks.py.
    def _check_inlines_item(self, obj, inline, label):
        """Check one inline model admin."""
        try:
            inline_label = inline.__module__ + "." + inline.__name__
        except AttributeError:
            return [
                checks.Error(
                    "'%s' must inherit from 'InlineModelAdmin'." % obj,
                    obj=obj.__class__,
                    id="admin.E104",
                )
            ]
        from django.contrib.admin.options import InlineModelAdmin
        if not _issubclass(inline, InlineModelAdmin):
            return [
                checks.Error(
                    "'%s' must inherit from 'InlineModelAdmin'." % inline_label,
                    obj=obj.__class__,
                    id="admin.E104",
                )
            ]
        elif not inline.model:
            return [
                checks.Error(
                    "'%s' must have a 'model' attribute." % inline_label,
                    obj=obj.__class__,
                    id="admin.E105",
                )
            ]
        elif not _issubclass(inline.model, models.Model):
            return must_be(
                "a Model", option="%s.model" % inline_label, obj=obj, id="admin.E106"
            )
        else:
            return inline(obj.model, obj.admin_site).check()
References django.contrib.admin.checks._issubclass(), check(), and django.contrib.admin.checks.must_be().
Referenced by _check_inlines().
_check_list_display()
django.contrib.admin.checks.ModelAdminChecks._check_list_display (self, obj) protected
Check that list_display only contains fields or usable attributes.
Definition at line 891 of file checks.py.
    def _check_list_display(self, obj):
        """Check that list_display only contains fields or usable attributes."""
        if not isinstance(obj.list_display, (list, tuple)):
            return must_be(
                "a list or tuple", option="list_display", obj=obj, id="admin.E107"
            )
        else:
            return list(
                chain.from_iterable(
                    self._check_list_display_item(obj, item, "list_display[%d]" % index)
                    for index, item in enumerate(obj.list_display)
                )
            )
References _check_list_display_item(), and django.contrib.admin.checks.must_be().
Referenced by check().
_check_list_display_item()
django.contrib.admin.checks.ModelAdminChecks._check_list_display_item (self, obj, item, label) protected
Definition at line 906 of file checks.py.
    def _check_list_display_item(self, obj, item, label):
        if callable(item):
            return []
        elif hasattr(obj, item):
            return []
        try:
            field = obj.model._meta.get_field(item)
        except FieldDoesNotExist:
            try:
                field = getattr(obj.model, item)
            except AttributeError:
                try:
                    field = get_fields_from_path(obj.model, item)[-1]
                except (FieldDoesNotExist, NotRelationField):
                    return [
                        checks.Error(
                            f"The value of '{label}' refers to '{item}', which is not "
                            f"a callable or attribute of '{obj.__class__.__name__}', "
                            "or an attribute, method, or field on "
                            f"'{obj.model._meta.label}'.",
                            obj=obj.__class__,
                            id="admin.E108",
                        )
                    ]
        if (
            getattr(field, "is_relation", False)
            and (field.many_to_many or field.one_to_many)
        ) or (getattr(field, "rel", None) and field.rel.field.many_to_one):
            return [
                checks.Error(
                    f"The value of '{label}' must not be a many-to-many field or a "
                    f"reverse foreign key.",
                    obj=obj.__class__,
                    id="admin.E109",
                )
            ]
        return []
Referenced by _check_list_display().
_check_list_display_links()
django.contrib.admin.checks.ModelAdminChecks._check_list_display_links (self, obj) protected
Check that list_display_links is a unique subset of list_display.
Definition at line 944 of file checks.py.
    def _check_list_display_links(self, obj):
        """Check that list_display_links is a unique subset of list_display."""
        from django.contrib.admin.options import ModelAdmin
        if obj.list_display_links is None:
            return []
        elif not isinstance(obj.list_display_links, (list, tuple)):
            return must_be(
                "a list, a tuple, or None",
                option="list_display_links",
                obj=obj,
                id="admin.E110",
            )
        # Check only if ModelAdmin.get_list_display() isn't overridden.
        elif obj.get_list_display.__func__ is ModelAdmin.get_list_display:
            return list(
                chain.from_iterable(
                    self._check_list_display_links_item(
                        obj, field_name, "list_display_links[%d]" % index
                    )
                    for index, field_name in enumerate(obj.list_display_links)
                )
            )
        return []
References _check_list_display_links_item(), and django.contrib.admin.checks.must_be().
Referenced by check().
_check_list_display_links_item()
django.contrib.admin.checks.ModelAdminChecks._check_list_display_links_item (self, obj, field_name, label) protected
Definition at line 969 of file checks.py.
    def _check_list_display_links_item(self, obj, field_name, label):
        if field_name not in obj.list_display:
            return [
                checks.Error(
                    "The value of '%s' refers to '%s', which is not defined in "
                    "'list_display'." % (label, field_name),
                    obj=obj.__class__,
                    id="admin.E111",
                )
            ]
        else:
            return []
Referenced by _check_list_display_links().
_check_list_editable()
django.contrib.admin.checks.ModelAdminChecks._check_list_editable (self, obj) protected
Check that list_editable is a sequence of editable fields from
list_display without first element.
Definition at line 1087 of file checks.py.
    def _check_list_editable(self, obj):
        """Check that list_editable is a sequence of editable fields from
        list_display without first element."""
        if not isinstance(obj.list_editable, (list, tuple)):
            return must_be(
                "a list or tuple", option="list_editable", obj=obj, id="admin.E120"
            )
        else:
            return list(
                chain.from_iterable(
                    self._check_list_editable_item(
                        obj, item, "list_editable[%d]" % index
                    )
                    for index, item in enumerate(obj.list_editable)
                )
            )
References _check_list_editable_item(), and django.contrib.admin.checks.must_be().
Referenced by check().
_check_list_editable_item()
django.contrib.admin.checks.ModelAdminChecks._check_list_editable_item (self, obj, field_name, label) protected
Definition at line 1105 of file checks.py.
    def _check_list_editable_item(self, obj, field_name, label):
        try:
            field = obj.model._meta.get_field(field_name)
        except FieldDoesNotExist:
            return refer_to_missing_field(
                field=field_name, option=label, obj=obj, id="admin.E121"
            )
        else:
            if field_name not in obj.list_display:
                return [
                    checks.Error(
                        "The value of '%s' refers to '%s', which is not "
                        "contained in 'list_display'." % (label, field_name),
                        obj=obj.__class__,
                        id="admin.E122",
                    )
                ]
            elif obj.list_display_links and field_name in obj.list_display_links:
                return [
                    checks.Error(
                        "The value of '%s' cannot be in both 'list_editable' and "
                        "'list_display_links'." % field_name,
                        obj=obj.__class__,
                        id="admin.E123",
                    )
                ]
            # If list_display[0] is in list_editable, check that
            # list_display_links is set. See #22792 and #26229 for use cases.
            elif (
                obj.list_display[0] == field_name
                and not obj.list_display_links
                and obj.list_display_links is not None
            ):
                return [
                    checks.Error(
                        "The value of '%s' refers to the first field in 'list_display' "
                        "('%s'), which cannot be used unless 'list_display_links' is "
                        "set." % (label, obj.list_display[0]),
                        obj=obj.__class__,
                        id="admin.E124",
                    )
                ]
            elif not field.editable or field.primary_key:
                return [
                    checks.Error(
                        "The value of '%s' refers to '%s', which is not editable "
                        "through the admin." % (label, field_name),
                        obj=obj.__class__,
                        id="admin.E125",
                    )
                ]
            else:
                return []
References django.contrib.admin.checks.refer_to_missing_field().
Referenced by _check_list_editable().
_check_list_filter()
django.contrib.admin.checks.ModelAdminChecks._check_list_filter (self, obj) protected
Definition at line 982 of file checks.py.
    def _check_list_filter(self, obj):
        if not isinstance(obj.list_filter, (list, tuple)):
            return must_be(
                "a list or tuple", option="list_filter", obj=obj, id="admin.E112"
            )
        else:
            return list(
                chain.from_iterable(
                    self._check_list_filter_item(obj, item, "list_filter[%d]" % index)
                    for index, item in enumerate(obj.list_filter)
                )
            )
References _check_list_filter_item(), and django.contrib.admin.checks.must_be().
Referenced by check().
_check_list_filter_item()
django.contrib.admin.checks.ModelAdminChecks._check_list_filter_item (self, obj, item, label) protected
Check one item of `list_filter`, i.e. check if it is one of three options:
1. 'field' -- a basic field filter, possibly w/ relationships (e.g.
   'field__rel')
2. ('field', SomeFieldListFilter) - a field-based list filter class
3. SomeListFilter - a non-field list filter class
Definition at line 995 of file checks.py.
    def _check_list_filter_item(self, obj, item, label):
        """
        Check one item of `list_filter`, i.e. check if it is one of three options:
        1. 'field' -- a basic field filter, possibly w/ relationships (e.g.
           'field__rel')
        2. ('field', SomeFieldListFilter) - a field-based list filter class
        3. SomeListFilter - a non-field list filter class
        """
        from django.contrib.admin import FieldListFilter, ListFilter
        if callable(item) and not isinstance(item, models.Field):
            # If item is option 3, it should be a ListFilter...
            if not _issubclass(item, ListFilter):
                return must_inherit_from(
                    parent="ListFilter", option=label, obj=obj, id="admin.E113"
                )
            # ...  but not a FieldListFilter.
            elif issubclass(item, FieldListFilter):
                return [
                    checks.Error(
                        "The value of '%s' must not inherit from 'FieldListFilter'."
                        % label,
                        obj=obj.__class__,
                        id="admin.E114",
                    )
                ]
            else:
                return []
        elif isinstance(item, (tuple, list)):
            # item is option #2
            field, list_filter_class = item
            if not _issubclass(list_filter_class, FieldListFilter):
                return must_inherit_from(
                    parent="FieldListFilter",
                    option="%s[1]" % label,
                    obj=obj,
                    id="admin.E115",
                )
            else:
                return []
        else:
            # item is option #1
            field = item
            # Validate the field string
            try:
                get_fields_from_path(obj.model, field)
            except (NotRelationField, FieldDoesNotExist):
                return [
                    checks.Error(
                        "The value of '%s' refers to '%s', which does not refer to a "
                        "Field." % (label, field),
                        obj=obj.__class__,
                        id="admin.E116",
                    )
                ]
            else:
                return []
References django.contrib.admin.checks._issubclass(), and django.contrib.admin.checks.must_inherit_from().
Referenced by _check_list_filter().
_check_list_max_show_all()
django.contrib.admin.checks.ModelAdminChecks._check_list_max_show_all (self, obj) protected
Check that list_max_show_all is an integer.
Definition at line 1077 of file checks.py.
    def _check_list_max_show_all(self, obj):
        """Check that list_max_show_all is an integer."""
        if not isinstance(obj.list_max_show_all, int):
            return must_be(
                "an integer", option="list_max_show_all", obj=obj, id="admin.E119"
            )
        else:
            return []
References django.contrib.admin.checks.must_be().
Referenced by check().
_check_list_per_page()
django.contrib.admin.checks.ModelAdminChecks._check_list_per_page (self, obj) protected
Check that list_per_page is an integer.
Definition at line 1067 of file checks.py.
    def _check_list_per_page(self, obj):
        """Check that list_per_page is an integer."""
        if not isinstance(obj.list_per_page, int):
            return must_be(
                "an integer", option="list_per_page", obj=obj, id="admin.E118"
            )
        else:
            return []
References django.contrib.admin.checks.must_be().
Referenced by check().
_check_list_select_related()
django.contrib.admin.checks.ModelAdminChecks._check_list_select_related (self, obj) protected
Check that list_select_related is a boolean, a list or a tuple.
Definition at line 1054 of file checks.py.
    def _check_list_select_related(self, obj):
        """Check that list_select_related is a boolean, a list or a tuple."""
        if not isinstance(obj.list_select_related, (bool, list, tuple)):
            return must_be(
                "a boolean, tuple or list",
                option="list_select_related",
                obj=obj,
                id="admin.E117",
            )
        else:
            return []
References django.contrib.admin.checks.must_be().
Referenced by check().
_check_save_as()
django.contrib.admin.checks.ModelAdminChecks._check_save_as (self, obj) protected
Check save_as is a boolean.
Definition at line 822 of file checks.py.
    def _check_save_as(self, obj):
        """Check save_as is a boolean."""
        if not isinstance(obj.save_as, bool):
            return must_be("a boolean", option="save_as", obj=obj, id="admin.E101")
        else:
            return []
References django.contrib.admin.checks.must_be().
Referenced by check().
_check_save_on_top()
django.contrib.admin.checks.ModelAdminChecks._check_save_on_top (self, obj) protected
Check save_on_top is a boolean.
Definition at line 830 of file checks.py.
    def _check_save_on_top(self, obj):
        """Check save_on_top is a boolean."""
        if not isinstance(obj.save_on_top, bool):
            return must_be("a boolean", option="save_on_top", obj=obj, id="admin.E102")
        else:
            return []
References django.contrib.admin.checks.must_be().
Referenced by check().
_check_search_fields()
django.contrib.admin.checks.ModelAdminChecks._check_search_fields (self, obj) protected
Check search_fields is a sequence.
Definition at line 1159 of file checks.py.
    def _check_search_fields(self, obj):
        """Check search_fields is a sequence."""
        if not isinstance(obj.search_fields, (list, tuple)):
            return must_be(
                "a list or tuple", option="search_fields", obj=obj, id="admin.E126"
            )
        else:
            return []
References django.contrib.admin.checks.must_be().
Referenced by check().
check()
django.contrib.admin.checks.ModelAdminChecks.check (self, admin_obj, ** kwargs)
Reimplemented from django.contrib.admin.checks.BaseModelAdminChecks.
Definition at line 804 of file checks.py.
    def check(self, admin_obj, **kwargs):
        return [
            *super().check(admin_obj),
            *self._check_save_as(admin_obj),
            *self._check_save_on_top(admin_obj),
            *self._check_inlines(admin_obj),
            *self._check_list_display(admin_obj),
            *self._check_list_display_links(admin_obj),
            *self._check_list_filter(admin_obj),
            *self._check_list_select_related(admin_obj),
            *self._check_list_per_page(admin_obj),
            *self._check_list_max_show_all(admin_obj),
            *self._check_list_editable(admin_obj),
            *self._check_search_fields(admin_obj),
            *self._check_date_hierarchy(admin_obj),
            *self._check_actions(admin_obj),
        ]
References _check_actions(), _check_date_hierarchy(), _check_inlines(), _check_list_display(), _check_list_display_links(), _check_list_editable(), _check_list_filter(), _check_list_max_show_all(), _check_list_per_page(), _check_list_select_related(), _check_save_as(), _check_save_on_top(), _check_search_fields(), and check().
Referenced by _check_inlines_item(), check(), pip._vendor.packaging._tokenizer.Tokenizer.consume(), pip._vendor.packaging._tokenizer.Tokenizer.enclosing_tokens(), django.core.management.base.BaseCommand.execute(), pip._vendor.packaging._tokenizer.Tokenizer.expect(), django.core.management.commands.check.Command.handle(), django.core.management.commands.migrate.Command.handle(), django.core.management.commands.runserver.Command.inner_run(), and pip._vendor.pygments.scanner.Scanner.test().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/admin/checks.py