Read&Watch: django.template.loader_tags.BlockContext Class Reference
django.template.loader_tags.BlockContext Class Reference
Public Member Functions
__init__ (self)
__repr__ (self)
add_blocks (self, blocks)
pop (self, name)
push (self, name, block)
get_block (self, name)
Public Attributes
blocks = defaultdict(list)
Detailed Description
Definition at line 14 of file loader_tags.py.
Constructor & Destructor Documentation
__init__()
django.template.loader_tags.BlockContext.__init__ (self)
Definition at line 15 of file loader_tags.py.
    def __init__(self):
        # Dictionary of FIFO queues.
        self.blocks = defaultdict(list)
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
__repr__()
django.template.loader_tags.BlockContext.__repr__ (self)
Definition at line 19 of file loader_tags.py.
    def __repr__(self):
        return f"<{self.__class__.__qualname__}: blocks={self.blocks!r}>"
add_blocks()
django.template.loader_tags.BlockContext.add_blocks (self, blocks)
Definition at line 22 of file loader_tags.py.
    def add_blocks(self, blocks):
        for name, block in blocks.items():
            self.blocks[name].insert(0, block)
References blocks.
get_block()
django.template.loader_tags.BlockContext.get_block (self, name)
Definition at line 35 of file loader_tags.py.
    def get_block(self, name):
        try:
            return self.blocks[name][-1]
        except IndexError:
            return None
References blocks.
pop()
django.template.loader_tags.BlockContext.pop (self, name)
Definition at line 26 of file loader_tags.py.
    def pop(self, name):
        try:
            return self.blocks[name].pop()
        except IndexError:
            return None
References blocks, and pop().
Referenced by pop().
push()
django.template.loader_tags.BlockContext.push (self, name, block)
Definition at line 32 of file loader_tags.py.
    def push(self, name, block):
        self.blocks[name].append(block)
References blocks.
Member Data Documentation
blocks
django.template.loader_tags.BlockContext.blocks = defaultdict(list)
Definition at line 17 of file loader_tags.py.
Referenced by add_blocks(), get_block(), pop(), push(), and django.template.loader_tags.ExtendsNode.render().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/template/loader_tags.py