Read&Watch: astroid.exceptions.StatementMissing Class Reference
astroid.exceptions.StatementMissing Class Reference
Public Member Functions
None __init__ (self, nodes.NodeNG target)
Public Member Functions inherited from astroid.exceptions.ParentMissingError
None __init__ (self, nodes.NodeNG target)
Public Member Functions inherited from astroid.exceptions.AstroidError
None __init__ (self, str message="", **Any kws)
str __str__ (self)
Additional Inherited Members
Public Attributes inherited from astroid.exceptions.ParentMissingError
target = target
Public Attributes inherited from astroid.exceptions.AstroidError
message = message
Detailed Description
Raised when a call to node.statement() does not return a node.
This is because a node in the chain does not have a parent attribute
and therefore does not return a node for statement().
Standard attributes:
    target: The node for which the parent lookup failed.
Definition at line 398 of file exceptions.py.
Constructor & Destructor Documentation
__init__()
None astroid.exceptions.StatementMissing.__init__ (self, nodes.NodeNG target)
Definition at line 408 of file exceptions.py.
    def __init__(self, target: nodes.NodeNG) -> None:
        super(ParentMissingError, self).__init__(
            message=f"Statement not found on {target!r}"
        )
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/astroid/exceptions.py