Read&Watch: django.db.migrations.serializer.FunctionTypeSerializer Class Reference
django.db.migrations.serializer.FunctionTypeSerializer Class Reference
Public Member Functions
serialize (self)
Public Member Functions inherited from django.db.migrations.serializer.BaseSerializer
__init__ (self, value)
Additional Inherited Members
Public Attributes inherited from django.db.migrations.serializer.BaseSerializer
value = value
Detailed Description
Definition at line 173 of file serializer.py.
Member Function Documentation
serialize()
django.db.migrations.serializer.FunctionTypeSerializer.serialize (self)
Reimplemented from django.db.migrations.serializer.BaseSerializer.
Definition at line 174 of file serializer.py.
    def serialize(self):
        if getattr(self.value, "__self__", None) and isinstance(
            self.value.__self__, type
        ):
            klass = self.value.__self__
            module = klass.__module__
            return "%s.%s.%s" % (module, klass.__qualname__, self.value.__name__), {
                "import %s" % module
            }
        # Further error checking
        if self.value.__name__ == "<lambda>":
            raise ValueError("Cannot serialize function: lambda")
        if self.value.__module__ is None:
            raise ValueError("Cannot serialize function %r: No module" % self.value)
        module_name = self.value.__module__
        if "<" not in self.value.__qualname__:  # Qualname can include <locals>
            return "%s.%s" % (module_name, self.value.__qualname__), {
                "import %s" % self.value.__module__
            }
        raise ValueError(
            "Could not find function %s in %s.\n" % (self.value.__name__, module_name)
        )
Referenced by django.db.migrations.writer.MigrationWriter.as_string(), pylint.reporters.json_reporter.JSON2Reporter.display_messages(), pylint.reporters.json_reporter.JSONReporter.display_messages(), pip._vendor.cachecontrol.serialize.Serializer.dumps(), and yaml.representer.BaseRepresenter.represent().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/db/migrations/serializer.py