Read&Watch: isort.deprecated.finders.RequirementsFinder Class Reference
isort.deprecated.finders.RequirementsFinder Class Reference
Static Public Attributes
tuple exts = (".txt", ".in")
Static Public Attributes inherited from isort.deprecated.finders.ReqsBaseFinder
bool enabled = False
Protected Member Functions
Iterator[str] _get_files_from_dir (self, str path)
List[str] _get_files_from_dir_cached (cls, str path)
Iterator[str] _get_names (self, str path)
List[str] _get_names_cached (cls, str path)
Protected Member Functions inherited from isort.deprecated.finders.ReqsBaseFinder
List[str] _load_names (self)
Iterator[str] _get_files (self)
str _normalize_name (self, str name)
Additional Inherited Members
Public Member Functions inherited from isort.deprecated.finders.ReqsBaseFinder
None __init__ (self, Config config, str path=".")
Optional[str] find (self, str module_name)
Public Member Functions inherited from isort.deprecated.finders.BaseFinder
None __init__ (self, Config config)
Public Attributes inherited from isort.deprecated.finders.ReqsBaseFinder
path = path
Optional[Dict[str, str]] mapping = self._load_mapping()
List[str] names = self._load_names()
Public Attributes inherited from isort.deprecated.finders.BaseFinder
config = config
Static Protected Member Functions inherited from isort.deprecated.finders.ReqsBaseFinder
Optional[Dict[str, str]] _load_mapping ()
Iterator[str] _get_parents (str path)
Detailed Description
Definition at line 290 of file finders.py.
Member Function Documentation
_get_files_from_dir()
Iterator[str] isort.deprecated.finders.RequirementsFinder._get_files_from_dir (self, str path) protected
Return paths to requirements files from passed dir.
Reimplemented from isort.deprecated.finders.ReqsBaseFinder.
Definition at line 294 of file finders.py.
    def _get_files_from_dir(self, path: str) -> Iterator[str]:
        """Return paths to requirements files from passed dir."""
        yield from self._get_files_from_dir_cached(path)
References _get_files_from_dir_cached().
_get_files_from_dir_cached()
List[str] isort.deprecated.finders.RequirementsFinder._get_files_from_dir_cached (cls, str path) protected
Definition at line 300 of file finders.py.
    def _get_files_from_dir_cached(cls, path: str) -> List[str]:
        results = []
        for fname in os.listdir(path):
            if "requirements" not in fname:
                continue
            full_path = os.path.join(path, fname)
            # *requirements*/*.{txt,in}
            if os.path.isdir(full_path):
                for subfile_name in os.listdir(full_path):
                    for ext in cls.exts:
                        if subfile_name.endswith(ext):
                            results.append(os.path.join(full_path, subfile_name))
                continue
            # *requirements*.{txt,in}
            if os.path.isfile(full_path):
                for ext in cls.exts:
                    if fname.endswith(ext):
                        results.append(full_path)
                        break
        return results
References exts.
Referenced by _get_files_from_dir().
_get_names()
Iterator[str] isort.deprecated.finders.RequirementsFinder._get_names (self, str path) protected
Load required packages from path to requirements file
Reimplemented from isort.deprecated.finders.ReqsBaseFinder.
Definition at line 325 of file finders.py.
    def _get_names(self, path: str) -> Iterator[str]:
        """Load required packages from path to requirements file"""
        yield from self._get_names_cached(path)
References _get_names_cached().
_get_names_cached()
List[str] isort.deprecated.finders.RequirementsFinder._get_names_cached (cls, str path) protected
Definition at line 331 of file finders.py.
    def _get_names_cached(cls, path: str) -> List[str]:
        result = []
        with chdir(os.path.dirname(path)):
            requirements = parse_requirements(Path(path))
            for req in requirements.values():
                if req.name:
                    result.append(req.name)
        return result
References isort.deprecated.finders.chdir(), and isort.deprecated.finders.parse_requirements.
Referenced by _get_names().
Member Data Documentation
exts
tuple isort.deprecated.finders.RequirementsFinder.exts = (".txt", ".in") static
Definition at line 291 of file finders.py.
Referenced by _get_files_from_dir_cached().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/isort/deprecated/finders.py