Read&Watch: PIL.ImageTk.PhotoImage Class Reference
PIL.ImageTk.PhotoImage Class Reference
Public Member Functions
None __init__ (self, Image.Image|str|None image=None, tuple[int, int]|None size=None, **Any kw)
None __del__ (self)
str __str__ (self)
int width (self)
int height (self)
None paste (self, Image.Image im)
Public Attributes
tk = self.__photo.tk
Detailed Description
A Tkinter-compatible photo image.  This can be used
everywhere Tkinter expects an image object.  If the image is an RGBA
image, pixels having alpha 0 are treated as transparent.
The constructor takes either a PIL image, or a mode and a size.
Alternatively, you can use the ``file`` or ``data`` options to initialize
the photo image object.
:param image: Either a PIL image, or a mode string.  If a mode string is
              used, a size must also be given.
:param size: If the first argument is a mode string, this defines the size
             of the image.
:keyword file: A filename to load the image from (using
               ``Image.open(file)``).
:keyword data: An 8-bit string containing image data (as loaded from an
               image file).
Definition at line 72 of file ImageTk.py.
Constructor & Destructor Documentation
__init__()
None PIL.ImageTk.PhotoImage.__init__ (self, Image.Image | str | None image = None, tuple[int, int] | None size = None, **Any kw)
Definition at line 92 of file ImageTk.py.
    ) -> None:
        # Tk compatibility: file or data
        if image is None:
            image = _get_image_from_kw(kw)
        if image is None:
            msg = "Image is required"
            raise ValueError(msg)
        elif isinstance(image, str):
            mode = image
            image = None
            if size is None:
                msg = "If first argument is mode, size is required"
                raise ValueError(msg)
        else:
            # got an image instead of a mode
            mode = image.mode
            if mode == "P":
                # palette mapped data
                image.apply_transparency()
                image.load()
                mode = image.palette.mode if image.palette else "RGB"
            size = image.size
            kw["width"], kw["height"] = size
        if mode not in ["1", "L", "RGB", "RGBA"]:
            mode = Image.getmodebase(mode)
        self.__mode = mode
        self.__size = size
        self.__photo = tkinter.PhotoImage(**kw)
        self.tk = self.__photo.tk
        if image:
            self.paste(image)
References __mode, __photo, __size, and PIL.ImageTk._get_image_from_kw().
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
__del__()
None PIL.ImageTk.PhotoImage.__del__ (self)
Definition at line 133 of file ImageTk.py.
    def __del__(self) -> None:
        try:
            name = self.__photo.name
        except AttributeError:
            return
        self.__photo.name = None
        try:
            self.__photo.tk.call("image", "delete", name)
        except Exception:
            pass  # ignore internal errors
References __photo.
Member Function Documentation
__str__()
str PIL.ImageTk.PhotoImage.__str__ (self)
Get the Tkinter photo image identifier.  This method is automatically
called by Tkinter whenever a PhotoImage object is passed to a Tkinter
method.
:return: A Tkinter photo image identifier (a string).
Definition at line 144 of file ImageTk.py.
    def __str__(self) -> str:
        """
        Get the Tkinter photo image identifier.  This method is automatically
        called by Tkinter whenever a PhotoImage object is passed to a Tkinter
        method.
        :return: A Tkinter photo image identifier (a string).
        """
        return str(self.__photo)
References __photo.
Referenced by PIL.PdfParser.IndirectReference.__bytes__().
height()
int PIL.ImageTk.PhotoImage.height (self)
Get the height of the image.
:return: The height, in pixels.
Definition at line 162 of file ImageTk.py.
    def height(self) -> int:
        """
        Get the height of the image.
        :return: The height, in pixels.
        """
        return self.__size[1]
References __size.
paste()
None PIL.ImageTk.PhotoImage.paste (self, Image.Image im)
Paste a PIL image into the photo image.  Note that this can
be very slow if the photo image is displayed.
:param im: A PIL image. The size must match the target region.  If the
           mode does not match, the image is converted to the mode of
           the bitmap image.
Definition at line 170 of file ImageTk.py.
    def paste(self, im: Image.Image) -> None:
        """
        Paste a PIL image into the photo image.  Note that this can
        be very slow if the photo image is displayed.
        :param im: A PIL image. The size must match the target region.  If the
                   mode does not match, the image is converted to the mode of
                   the bitmap image.
        """
        # convert to blittable
        ptr = im.getim()
        image = im.im
        if not image.isblock() or im.mode != self.__mode:
            block = Image.core.new_block(self.__mode, im.size)
            image.convert2(block, image)  # convert directly between buffers
            ptr = block.ptr
        _pyimagingtkcall("PyImagingPhoto", self.__photo, ptr)
# --------------------------------------------------------------------
# BitmapImage
References __mode, __photo, and PIL.ImageTk._pyimagingtkcall().
width()
int PIL.ImageTk.PhotoImage.width (self)
Get the width of the image.
:return: The width, in pixels.
Definition at line 154 of file ImageTk.py.
    def width(self) -> int:
        """
        Get the width of the image.
        :return: The width, in pixels.
        """
        return self.__size[0]
References __size.
Member Data Documentation
tk
PIL.ImageTk.PhotoImage.tk = self.__photo.tk
Definition at line 129 of file ImageTk.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/PIL/ImageTk.py