Read&Watch: django.contrib.auth.password_validation.UserAttributeSimilarityValidator Class Reference
django.contrib.auth.password_validation.UserAttributeSimilarityValidator Class Reference
Public Member Functions
__init__ (self, user_attributes=DEFAULT_USER_ATTRIBUTES, max_similarity=0.7)
validate (self, password, user=None)
get_help_text (self)
Public Attributes
user_attributes = user_attributes
max_similarity = max_similarity
Static Public Attributes
tuple DEFAULT_USER_ATTRIBUTES = ("username", "first_name", "last_name", "email")
Detailed Description
Validate that the password is sufficiently different from the user's
attributes.
If no specific attributes are provided, look at a sensible list of
defaults. Attributes that don't exist are ignored. Comparison is made to
not only the full attribute value, but also its components, so that, for
example, a password is validated against either part of an email address,
as well as the full address.
Definition at line 159 of file password_validation.py.
Constructor & Destructor Documentation
__init__()
django.contrib.auth.password_validation.UserAttributeSimilarityValidator.__init__ (self, user_attributes = DEFAULT_USER_ATTRIBUTES, max_similarity = 0.7)
Definition at line 173 of file password_validation.py.
    def __init__(self, user_attributes=DEFAULT_USER_ATTRIBUTES, max_similarity=0.7):
        self.user_attributes = user_attributes
        if max_similarity < 0.1:
            raise ValueError("max_similarity must be at least 0.1")
        self.max_similarity = max_similarity
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
get_help_text()
django.contrib.auth.password_validation.UserAttributeSimilarityValidator.get_help_text (self)
Definition at line 211 of file password_validation.py.
    def get_help_text(self):
        return _(
            "Your password can’t be too similar to your other personal information."
        )
validate()
django.contrib.auth.password_validation.UserAttributeSimilarityValidator.validate (self, password, user = None)
Definition at line 179 of file password_validation.py.
    def validate(self, password, user=None):
        if not user:
            return
        password = password.lower()
        for attribute_name in self.user_attributes:
            value = getattr(user, attribute_name, None)
            if not value or not isinstance(value, str):
                continue
            value_lower = value.lower()
            value_parts = re.split(r"\W+", value_lower) + [value_lower]
            for value_part in value_parts:
                if exceeds_maximum_length_ratio(
                    password, self.max_similarity, value_part
                ):
                    continue
                if (
                    SequenceMatcher(a=password, b=value_part).quick_ratio()
                    >= self.max_similarity
                ):
                    try:
                        verbose_name = str(
                            user._meta.get_field(attribute_name).verbose_name
                        )
                    except FieldDoesNotExist:
                        verbose_name = attribute_name
                    raise ValidationError(
                        _("The password is too similar to the %(verbose_name)s."),
                        code="password_too_similar",
                        params={"verbose_name": verbose_name},
                    )
References django.contrib.auth.password_validation.exceeds_maximum_length_ratio(), max_similarity, and user_attributes.
Referenced by django.db.models.fields.Field.clean(), django.forms.fields.Field.clean(), and pip._vendor.distlib.metadata.Metadata.write().
Member Data Documentation
DEFAULT_USER_ATTRIBUTES
tuple django.contrib.auth.password_validation.UserAttributeSimilarityValidator.DEFAULT_USER_ATTRIBUTES = ("username", "first_name", "last_name", "email") static
Definition at line 171 of file password_validation.py.
max_similarity
django.contrib.auth.password_validation.UserAttributeSimilarityValidator.max_similarity = max_similarity
Definition at line 177 of file password_validation.py.
Referenced by validate().
user_attributes
django.contrib.auth.password_validation.UserAttributeSimilarityValidator.user_attributes = user_attributes
Definition at line 174 of file password_validation.py.
Referenced by validate().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/auth/password_validation.py