Read&Watch: pip._internal.utils.temp_dir.TempDirectory Class Reference
pip._internal.utils.temp_dir.TempDirectory Class Reference
Public Member Functions
__init__ (self, Optional[str] path=None, Union[bool, None, _Default] delete=_default, str kind="temp", bool globally_managed=False, bool ignore_cleanup_errors=True)
str path (self)
str __repr__ (self)
_T __enter__ (_T self)
None __exit__ (self, Any exc, Any value, Any tb)
None cleanup (self)
Public Attributes
delete = delete
kind = kind
ignore_cleanup_errors = ignore_cleanup_errors
Protected Member Functions
str _create (self, str kind)
Protected Attributes
str _path = path
bool _deleted = False
Detailed Description
Helper class that owns and cleans up a temporary directory.
This class can be used as a context manager or as an OO representation of a
temporary directory.
Attributes:
    path
        Location to the created temporary directory
    delete
        Whether the directory should be deleted when exiting
        (when used as a contextmanager)
Methods:
    cleanup()
        Deletes the temporary directory
When used as a context manager, if the delete attribute is True, on
exiting the context the temporary directory is deleted.
Definition at line 93 of file temp_dir.py.
Constructor & Destructor Documentation
__init__()
pip._internal.utils.temp_dir.TempDirectory.__init__ (self, Optional[str] path = None, Union[bool, None, _Default] delete = _default, str kind = "temp", bool globally_managed = False, bool ignore_cleanup_errors = True)
Definition at line 114 of file temp_dir.py.
    ):
        super().__init__()
        if delete is _default:
            if path is not None:
                # If we were given an explicit directory, resolve delete option
                # now.
                delete = False
            else:
                # Otherwise, we wait until cleanup and see what
                # tempdir_registry says.
                delete = None
        # The only time we specify path is in for editables where it
        # is the value of the --src option.
        if path is None:
            path = self._create(kind)
        self._path = path
        self._deleted = False
        self.delete = delete
        self.kind = kind
        self.ignore_cleanup_errors = ignore_cleanup_errors
        if globally_managed:
            assert _tempdir_manager is not None
            _tempdir_manager.enter_context(self)
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
__enter__()
_T pip._internal.utils.temp_dir.TempDirectory.__enter__ (_T self)
Definition at line 157 of file temp_dir.py.
    def __enter__(self: _T) -> _T:
        return self
__exit__()
None pip._internal.utils.temp_dir.TempDirectory.__exit__ (self, Any exc, Any value, Any tb)
Definition at line 160 of file temp_dir.py.
    def __exit__(self, exc: Any, value: Any, tb: Any) -> None:
        if self.delete is not None:
            delete = self.delete
        elif _tempdir_registry:
            delete = _tempdir_registry.get_delete(self.kind)
        else:
            delete = True
        if delete:
            self.cleanup()
__repr__()
str pip._internal.utils.temp_dir.TempDirectory.__repr__ (self)
Definition at line 154 of file temp_dir.py.
    def __repr__(self) -> str:
        return f"<{self.__class__.__name__} {self.path!r}>"
_create()
str pip._internal.utils.temp_dir.TempDirectory._create (self, str kind) protected
Create a temporary directory and store its path in self.path
Reimplemented in pip._internal.utils.temp_dir.AdjacentTempDirectory.
Definition at line 171 of file temp_dir.py.
    def _create(self, kind: str) -> str:
        """Create a temporary directory and store its path in self.path"""
        # We realpath here because some systems have their default tmpdir
        # symlinked to another directory.  This tends to confuse build
        # scripts, so we canonicalize the path by traversing potential
        # symlinks here.
        path = os.path.realpath(tempfile.mkdtemp(prefix=f"pip-{kind}-"))
        logger.debug("Created temporary directory: %s", path)
        return path
cleanup()
None pip._internal.utils.temp_dir.TempDirectory.cleanup (self)
Remove the temporary directory created and reset state
Definition at line 181 of file temp_dir.py.
    def cleanup(self) -> None:
        """Remove the temporary directory created and reset state"""
        self._deleted = True
        if not os.path.exists(self._path):
            return
        errors: List[BaseException] = []
        def onerror(
            func: Callable[..., Any],
            path: Path,
            exc_val: BaseException,
        ) -> None:
            """Log a warning for a `rmtree` error and continue"""
            formatted_exc = "\n".join(
                traceback.format_exception_only(type(exc_val), exc_val)
            )
            formatted_exc = formatted_exc.rstrip()  # remove trailing new line
            if func in (os.unlink, os.remove, os.rmdir):
                logger.debug(
                    "Failed to remove a temporary file '%s' due to %s.\n",
                    path,
                    formatted_exc,
                )
            else:
                logger.debug("%s failed with %s.", func.__qualname__, formatted_exc)
            errors.append(exc_val)
        if self.ignore_cleanup_errors:
            try:
                # first try with @retry; retrying to handle ephemeral errors
                rmtree(self._path, ignore_errors=False)
            except OSError:
                # last pass ignore/log all errors
                rmtree(self._path, onexc=onerror)
            if errors:
                logger.warning(
                    "Failed to remove contents in a temporary directory '%s'.\n"
                    "You can safely remove it manually.",
                    self._path,
                )
        else:
            rmtree(self._path)
path()
str pip._internal.utils.temp_dir.TempDirectory.path (self)
Definition at line 150 of file temp_dir.py.
    def path(self) -> str:
        assert not self._deleted, f"Attempted to access deleted path: {self._path}"
        return self._path
Referenced by pip._internal.operations.prepare.File.__post_init__(), isort.io.File.extension(), pip._vendor.urllib3.util.url.Url.request_uri(), and urllib3.util.url.Url.request_uri().
Member Data Documentation
_deleted
pip._internal.utils.temp_dir.TempDirectory._deleted = False protected
Definition at line 140 of file temp_dir.py.
_path
pip._internal.utils.temp_dir.TempDirectory._path = path protected
Definition at line 139 of file temp_dir.py.
Referenced by tomlkit.toml_file.TOMLFile.read(), and tomlkit.toml_file.TOMLFile.write().
delete
pip._internal.utils.temp_dir.TempDirectory.delete = delete
Definition at line 141 of file temp_dir.py.
Referenced by django.contrib.staticfiles.storage.HashedFilesMixin._post_process(), and django.views.generic.edit.DeletionMixin.post().
ignore_cleanup_errors
pip._internal.utils.temp_dir.TempDirectory.ignore_cleanup_errors = ignore_cleanup_errors
Definition at line 143 of file temp_dir.py.
kind
pip._internal.utils.temp_dir.TempDirectory.kind = kind
Definition at line 142 of file temp_dir.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_internal/utils/temp_dir.py