Read&Watch: isort.exceptions.LiteralParsingFailure Class Reference
isort.exceptions.LiteralParsingFailure Class Reference
Public Member Functions
__init__ (self, str code, Union[Exception, Type[Exception]] original_error)
Public Member Functions inherited from isort.exceptions.ISortError
__reduce__ (self)
Public Attributes
code = code
original_error = original_error
Detailed Description
Raised when one of isorts literal sorting comments is used but isort can't parse the
the given data structure.
Definition at line 111 of file exceptions.py.
Constructor & Destructor Documentation
__init__()
isort.exceptions.LiteralParsingFailure.__init__ (self, str code, Union[Exception, Type[Exception]] original_error)
Definition at line 116 of file exceptions.py.
    def __init__(self, code: str, original_error: Union[Exception, Type[Exception]]):
        super().__init__(
            f"isort failed to parse the given literal {code}. It's important to note "
            "that isort literal sorting only supports simple literals parsable by "
            f"ast.literal_eval which gave the exception of {original_error}."
        )
        self.code = code
        self.original_error = original_error
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Data Documentation
code
isort.exceptions.LiteralParsingFailure.code = code
Definition at line 122 of file exceptions.py.
Referenced by pip._vendor.rich.syntax.Syntax._get_syntax(), and pip._vendor.rich.syntax.Syntax._numbers_column_width().
original_error
isort.exceptions.LiteralParsingFailure.original_error = original_error
Definition at line 123 of file exceptions.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/isort/exceptions.py