Read&Watch: django.contrib.admindocs.views.BaseAdminDocsView Class Reference
django.contrib.admindocs.views.BaseAdminDocsView Class Reference
Public Member Functions
dispatch (self, request, *args, **kwargs)
get_context_data (self, **kwargs)
Public Member Functions inherited from django.views.generic.base.TemplateView
get (self, request, *args, **kwargs)
Public Member Functions inherited from django.views.generic.base.TemplateResponseMixin
render_to_response (self, context, **response_kwargs)
get_template_names (self)
Public Member Functions inherited from django.views.generic.base.View
__init__ (self, **kwargs)
view_is_async (cls)
as_view (cls, **initkwargs)
setup (self, request, *args, **kwargs)
http_method_not_allowed (self, request, *args, **kwargs)
options (self, request, *args, **kwargs)
Additional Inherited Members
Public Attributes inherited from django.views.generic.base.View
view_is_async = cls.dispatch.__annotations__
head = self.get
request = request
args = args
kwargs = kwargs
Static Public Attributes inherited from django.views.generic.base.TemplateResponseMixin
template_name = None
template_engine = None
response_class = TemplateResponse
content_type = None
Static Public Attributes inherited from django.views.generic.base.ContextMixin
extra_context = None
Static Public Attributes inherited from django.views.generic.base.View
list http_method_names
Protected Member Functions inherited from django.views.generic.base.View
_allowed_methods (self)
Detailed Description
Base view for admindocs views.
Definition at line 39 of file views.py.
Member Function Documentation
dispatch()
django.contrib.admindocs.views.BaseAdminDocsView.dispatch (self, request, * args, ** kwargs)
Reimplemented from django.views.generic.base.View.
Definition at line 45 of file views.py.
    def dispatch(self, request, *args, **kwargs):
        if not utils.docutils_is_available:
            # Display an error message for people without docutils
            self.template_name = "admin_doc/missing_docutils.html"
            return self.render_to_response(admin.site.each_context(request))
        return super().dispatch(request, *args, **kwargs)
Referenced by django.views.generic.base.View.as_view(), mccabe.ASTVisitor.default(), and pylint.extensions.mccabe.PathGraphingAstVisitor.default().
get_context_data()
django.contrib.admindocs.views.BaseAdminDocsView.get_context_data (self, ** kwargs)
Reimplemented from django.views.generic.base.ContextMixin.
Reimplemented in django.contrib.admindocs.views.ModelDetailView, django.contrib.admindocs.views.ModelIndexView, django.contrib.admindocs.views.TemplateDetailView, django.contrib.admindocs.views.TemplateFilterIndexView, django.contrib.admindocs.views.TemplateTagIndexView, django.contrib.admindocs.views.ViewDetailView, and django.contrib.admindocs.views.ViewIndexView.
Definition at line 52 of file views.py.
    def get_context_data(self, **kwargs):
        return super().get_context_data(
            **{
                **kwargs,
                **admin.site.each_context(self.request),
            }
        )
References get_context_data().
Referenced by django.views.generic.edit.FormMixin.form_invalid(), django.views.generic.base.TemplateView.get(), django.views.generic.edit.ProcessFormView.get(), get_context_data(), and django.contrib.syndication.views.Feed.get_feed().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/admindocs/views.py