Read&Watch: django.contrib.auth.password_validation.MinimumLengthValidator Class Reference
django.contrib.auth.password_validation.MinimumLengthValidator Class Reference
Public Member Functions
__init__ (self, min_length=8)
validate (self, password, user=None)
get_help_text (self)
Public Attributes
min_length = min_length
Detailed Description
Validate that the password is of a minimum length.
Definition at line 99 of file password_validation.py.
Constructor & Destructor Documentation
__init__()
django.contrib.auth.password_validation.MinimumLengthValidator.__init__ (self, min_length = 8)
Definition at line 104 of file password_validation.py.
    def __init__(self, min_length=8):
        self.min_length = min_length
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
get_help_text()
django.contrib.auth.password_validation.MinimumLengthValidator.get_help_text (self)
Definition at line 121 of file password_validation.py.
    def get_help_text(self):
        return ngettext(
            "Your password must contain at least %(min_length)d character.",
            "Your password must contain at least %(min_length)d characters.",
            self.min_length,
        ) % {"min_length": self.min_length}
References min_length.
validate()
django.contrib.auth.password_validation.MinimumLengthValidator.validate (self, password, user = None)
Definition at line 107 of file password_validation.py.
    def validate(self, password, user=None):
        if len(password) < self.min_length:
            raise ValidationError(
                ngettext(
                    "This password is too short. It must contain at least "
                    "%(min_length)d character.",
                    "This password is too short. It must contain at least "
                    "%(min_length)d characters.",
                    self.min_length,
                ),
                code="password_too_short",
                params={"min_length": self.min_length},
            )
References min_length.
Referenced by django.db.models.fields.Field.clean(), django.forms.fields.Field.clean(), and pip._vendor.distlib.metadata.Metadata.write().
Member Data Documentation
min_length
django.contrib.auth.password_validation.MinimumLengthValidator.min_length = min_length
Definition at line 105 of file password_validation.py.
Referenced by get_help_text(), validate(), and django.forms.fields.CharField.widget_attrs().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/auth/password_validation.py