Read&Watch: django.test.utils.TimeKeeper Class Reference
django.test.utils.TimeKeeper Class Reference
Public Member Functions
__init__ (self)
timed (self, name)
print_results (self)
Public Attributes
records = collections.defaultdict(list)
Detailed Description
Definition at line 932 of file utils.py.
Constructor & Destructor Documentation
__init__()
django.test.utils.TimeKeeper.__init__ (self)
Definition at line 933 of file utils.py.
    def __init__(self):
        self.records = collections.defaultdict(list)
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
print_results()
django.test.utils.TimeKeeper.print_results (self)
Definition at line 946 of file utils.py.
    def print_results(self):
        for name, end_times in self.records.items():
            for record_time in end_times:
                record = "%s took %.3fs" % (name, record_time)
                sys.stderr.write(record + os.linesep)
References records.
timed()
django.test.utils.TimeKeeper.timed (self, name)
Definition at line 937 of file utils.py.
    def timed(self, name):
        self.records[name]
        start_time = time.perf_counter()
        try:
            yield
        finally:
            end_time = time.perf_counter() - start_time
            self.records[name].append(end_time)
References records.
Member Data Documentation
records
django.test.utils.TimeKeeper.records = collections.defaultdict(list)
Definition at line 934 of file utils.py.
Referenced by print_results(), and timed().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/test/utils.py