Read&Watch: charset_normalizer.md.MessDetectorPlugin Class Reference
charset_normalizer.md.MessDetectorPlugin Class Reference
Public Member Functions
bool eligible (self, str character)
None feed (self, str character)
None reset (self)
float ratio (self)
Detailed Description
Base abstract class used for mess detection plugins.
All detectors MUST extend and implement given methods.
Definition at line 31 of file md.py.
Member Function Documentation
eligible()
bool charset_normalizer.md.MessDetectorPlugin.eligible (self, str character)
Determine if given character should be fed in.
Reimplemented in charset_normalizer.md.ArabicIsolatedFormPlugin, charset_normalizer.md.ArchaicUpperLowerPlugin, charset_normalizer.md.CjkInvalidStopPlugin, charset_normalizer.md.SuperWeirdWordPlugin, charset_normalizer.md.SuspiciousDuplicateAccentPlugin, charset_normalizer.md.SuspiciousRange, charset_normalizer.md.TooManyAccentuatedPlugin, charset_normalizer.md.TooManySymbolOrPunctuationPlugin, and charset_normalizer.md.UnprintablePlugin.
Definition at line 37 of file md.py.
    def eligible(self, character: str) -> bool:
        """
        Determine if given character should be fed in.
        """
        raise NotImplementedError  # pragma: nocover
feed()
None charset_normalizer.md.MessDetectorPlugin.feed (self, str character)
The main routine to be executed upon character.
Insert the logic in witch the text would be considered chaotic.
Reimplemented in charset_normalizer.md.ArabicIsolatedFormPlugin, charset_normalizer.md.ArchaicUpperLowerPlugin, charset_normalizer.md.CjkInvalidStopPlugin, charset_normalizer.md.SuperWeirdWordPlugin, charset_normalizer.md.SuspiciousDuplicateAccentPlugin, charset_normalizer.md.SuspiciousRange, charset_normalizer.md.TooManyAccentuatedPlugin, charset_normalizer.md.TooManySymbolOrPunctuationPlugin, and charset_normalizer.md.UnprintablePlugin.
Definition at line 43 of file md.py.
    def feed(self, character: str) -> None:
        """
        The main routine to be executed upon character.
        Insert the logic in witch the text would be considered chaotic.
        """
        raise NotImplementedError  # pragma: nocover
Referenced by PIL.ImageFile.Parser.close(), and django.db.migrations.writer.OperationWriter.serialize().
ratio()
float charset_normalizer.md.MessDetectorPlugin.ratio (self)
Compute the chaos ratio based on what your feed() has seen.
Must NOT be lower than 0.; No restriction gt 0.
Reimplemented in charset_normalizer.md.ArabicIsolatedFormPlugin, charset_normalizer.md.ArchaicUpperLowerPlugin, charset_normalizer.md.CjkInvalidStopPlugin, charset_normalizer.md.SuperWeirdWordPlugin, charset_normalizer.md.SuspiciousDuplicateAccentPlugin, charset_normalizer.md.SuspiciousRange, charset_normalizer.md.TooManyAccentuatedPlugin, charset_normalizer.md.TooManySymbolOrPunctuationPlugin, and charset_normalizer.md.UnprintablePlugin.
Definition at line 57 of file md.py.
    def ratio(self) -> float:
        """
        Compute the chaos ratio based on what your feed() has seen.
        Must NOT be lower than 0.; No restriction gt 0.
        """
        raise NotImplementedError  # pragma: nocover
reset()
None charset_normalizer.md.MessDetectorPlugin.reset (self)
Permit to reset the plugin to the initial state.
Reimplemented in charset_normalizer.md.ArabicIsolatedFormPlugin, charset_normalizer.md.ArchaicUpperLowerPlugin, charset_normalizer.md.CjkInvalidStopPlugin, charset_normalizer.md.SuperWeirdWordPlugin, charset_normalizer.md.SuspiciousDuplicateAccentPlugin, charset_normalizer.md.SuspiciousRange, charset_normalizer.md.TooManyAccentuatedPlugin, charset_normalizer.md.TooManySymbolOrPunctuationPlugin, and charset_normalizer.md.UnprintablePlugin.
Definition at line 50 of file md.py.
    def reset(self) -> None:  # pragma: no cover
        """
        Permit to reset the plugin to the initial state.
        """
        raise NotImplementedError
Referenced by responses.RequestsMock.__exit__(), django.utils.html.MLStripper.__init__(), pylint.extensions.mccabe.PathGraphingAstVisitor._subgraph(), pylint.testutils.reporter_for_tests.GenericTestReporter.finalize(), and PIL.TiffImagePlugin.ImageFileDirectory_v2.load().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/charset_normalizer/md.py