Read&Watch: django.contrib.sessions.middleware.SessionMiddleware Class Reference
django.contrib.sessions.middleware.SessionMiddleware Class Reference
Public Member Functions
__init__ (self, get_response)
process_request (self, request)
process_response (self, request, response)
Public Member Functions inherited from django.utils.deprecation.MiddlewareMixin
__init__ (self, get_response)
__repr__ (self)
__call__ (self, request)
__acall__ (self, request)
Public Attributes
SessionStore = engine.SessionStore
Public Attributes inherited from django.utils.deprecation.MiddlewareMixin
get_response = get_response
async_mode = iscoroutinefunction(self.get_response)
Additional Inherited Members
Static Public Attributes inherited from django.utils.deprecation.MiddlewareMixin
bool sync_capable = True
bool async_capable = True
Detailed Description
Definition at line 12 of file middleware.py.
Constructor & Destructor Documentation
__init__()
django.contrib.sessions.middleware.SessionMiddleware.__init__ (self, get_response)
Definition at line 13 of file middleware.py.
    def __init__(self, get_response):
        super().__init__(get_response)
        engine = import_module(settings.SESSION_ENGINE)
        self.SessionStore = engine.SessionStore
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Function Documentation
process_request()
django.contrib.sessions.middleware.SessionMiddleware.process_request (self, request)
Definition at line 18 of file middleware.py.
    def process_request(self, request):
        session_key = request.COOKIES.get(settings.SESSION_COOKIE_NAME)
        request.session = self.SessionStore(session_key)
References SessionStore.
Referenced by django.utils.deprecation.MiddlewareMixin.__acall__(), and django.utils.deprecation.MiddlewareMixin.__call__().
process_response()
django.contrib.sessions.middleware.SessionMiddleware.process_response (self, request, response)
If request.session was modified, or if the configuration is to save the
session every time, save the changes and set a session cookie or delete
the session cookie if the session has been emptied.
Definition at line 22 of file middleware.py.
    def process_response(self, request, response):
        """
        If request.session was modified, or if the configuration is to save the
        session every time, save the changes and set a session cookie or delete
        the session cookie if the session has been emptied.
        """
        try:
            accessed = request.session.accessed
            modified = request.session.modified
            empty = request.session.is_empty()
        except AttributeError:
            return response
        # First check if we need to delete this cookie.
        # The session should be deleted only if the session is entirely empty.
        if settings.SESSION_COOKIE_NAME in request.COOKIES and empty:
            response.delete_cookie(
                settings.SESSION_COOKIE_NAME,
                path=settings.SESSION_COOKIE_PATH,
                domain=settings.SESSION_COOKIE_DOMAIN,
                samesite=settings.SESSION_COOKIE_SAMESITE,
            )
            patch_vary_headers(response, ("Cookie",))
        else:
            if accessed:
                patch_vary_headers(response, ("Cookie",))
            if (modified or settings.SESSION_SAVE_EVERY_REQUEST) and not empty:
                if request.session.get_expire_at_browser_close():
                    max_age = None
                    expires = None
                else:
                    max_age = request.session.get_expiry_age()
                    expires_time = time.time() + max_age
                    expires = http_date(expires_time)
                # Save the session data and refresh the client cookie.
                # Skip session save for 5xx responses.
                if response.status_code < 500:
                    try:
                        request.session.save()
                    except UpdateError:
                        raise SessionInterrupted(
                            "The request's session was deleted before the "
                            "request completed. The user may have logged "
                            "out in a concurrent request, for example."
                        )
                    response.set_cookie(
                        settings.SESSION_COOKIE_NAME,
                        request.session.session_key,
                        max_age=max_age,
                        expires=expires,
                        domain=settings.SESSION_COOKIE_DOMAIN,
                        path=settings.SESSION_COOKIE_PATH,
                        secure=settings.SESSION_COOKIE_SECURE or None,
                        httponly=settings.SESSION_COOKIE_HTTPONLY or None,
                        samesite=settings.SESSION_COOKIE_SAMESITE,
                    )
        return response
Referenced by django.utils.deprecation.MiddlewareMixin.__acall__(), django.utils.deprecation.MiddlewareMixin.__call__(), and pip._vendor.rich.prompt.PromptBase.__call__().
Member Data Documentation
SessionStore
django.contrib.sessions.middleware.SessionMiddleware.SessionStore = engine.SessionStore
Definition at line 16 of file middleware.py.
Referenced by process_request().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/sessions/middleware.py