Read&Watch: pylint.checkers.logging.LoggingChecker Class Reference
pylint.checkers.logging.LoggingChecker Class Reference
Public Member Functions
None visit_module (self, nodes.Module _)
None visit_importfrom (self, nodes.ImportFrom node)
None visit_import (self, nodes.Import node)
None visit_call (self, nodes.Call node)
Public Member Functions inherited from pylint.checkers.base_checker.BaseChecker
None __init__ (self, PyLinter linter)
bool __gt__ (self, Any other)
bool __eq__ (self, object other)
int __hash__ (self)
str __repr__ (self)
str __str__ (self)
str get_full_documentation (self, dict[str, MessageDefinitionTuple] msgs, Iterable[tuple[str, OptionDict, Any]] options, Sequence[tuple[str, str, ReportsCallable]] reports, str|None doc=None, str|None module=None, bool show_options=True)
None add_message (self, str msgid, int|None line=None, nodes.NodeNG|None node=None, Any args=None, Confidence|None confidence=None, int|None col_offset=None, int|None end_lineno=None, int|None end_col_offset=None)
None check_consistency (self)
MessageDefinition create_message_definition_from_tuple (self, str msgid, MessageDefinitionTuple msg_tuple)
list[MessageDefinition] messages (self)
None open (self)
None close (self)
Any get_map_data (self)
None reduce_map_data (self, PyLinter linter, list[Any] data)
Public Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
None __init__ (self, _ArgumentsManager arguments_manager)
Protected Member Functions
None _check_log_method (self, nodes.Call node, str name)
str _helper_string (self, nodes.Call node)
None _check_call_func (self, nodes.Call node)
None _check_format_string (self, nodes.Call node, Literal[0, 1] format_arg)
Protected Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
Any _option_value (self, str opt)
Iterator[ tuple[str, list[tuple[str, OptionDict, Any]]]|tuple[None, dict[str, list[tuple[str, OptionDict, Any]]]]] _options_by_section (self)
Iterator[tuple[str, OptionDict, Any]] _options_and_values (self, Options|None options=None)
Static Protected Member Functions
bool _is_operand_literal_str (InferenceResult|None operand)
bool _is_node_explicit_str_concatenation (nodes.NodeNG node)
Protected Attributes
set[str] _logging_names = set()
str _format_style = self.linter.config.logging_format_style
_logging_modules = set(logging_mods)
dict _from_imports = {}
Protected Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
_arguments_manager = arguments_manager
Additional Inherited Members
Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
linter = linter
messages
Static Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
str name = ""
dict msgs = {}
tuple reports = ()
bool enabled = True
Static Public Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
tuple options = ()
dict option_groups_descs = {}
Detailed Description
Checks use of the logging module.
Definition at line 128 of file logging.py.
Member Function Documentation
_check_call_func()
None pylint.checkers.logging.LoggingChecker._check_call_func (self, nodes.Call node) protected
Checks that function call is not format_string.format().
Definition at line 305 of file logging.py.
    def _check_call_func(self, node: nodes.Call) -> None:
        """Checks that function call is not format_string.format()."""
        func = utils.safe_infer(node.func)
        types = ("str", "unicode")
        methods = ("format",)
        if (
            isinstance(func, astroid.BoundMethod)
            and is_method_call(func, types, methods)
            and not is_complex_format_str(func.bound)
        ):
            self.add_message(
                "logging-format-interpolation",
                node=node,
                args=(self._helper_string(node),),
            )
References _helper_string(), pylint.checkers.base_checker.BaseChecker.add_message(), pylint.checkers.logging.is_complex_format_str(), and pylint.checkers.logging.is_method_call().
Referenced by _check_log_method().
_check_format_string()
None pylint.checkers.logging.LoggingChecker._check_format_string (self, nodes.Call node, Literal[0, 1] format_arg) protected
Checks that format string tokens match the supplied arguments.
Args:
  node: AST node to be checked.
  format_arg: Index of the format string in the node arguments.
Definition at line 321 of file logging.py.
    def _check_format_string(self, node: nodes.Call, format_arg: Literal[0, 1]) -> None:
        """Checks that format string tokens match the supplied arguments.
        Args:
          node: AST node to be checked.
          format_arg: Index of the format string in the node arguments.
        """
        num_args = _count_supplied_tokens(node.args[format_arg + 1 :])
        if not num_args:
            # If no args were supplied the string is not interpolated and can contain
            # formatting characters - it's used verbatim. Don't check any further.
            return
        format_string = node.args[format_arg].value
        required_num_args = 0
        if isinstance(format_string, bytes):
            format_string = format_string.decode()
        if isinstance(format_string, str):
            try:
                if self._format_style == "old":
                    keyword_args, required_num_args, _, _ = utils.parse_format_string(
                        format_string
                    )
                    if keyword_args:
                        # Keyword checking on logging strings is complicated by
                        # special keywords - out of scope.
                        return
                elif self._format_style == "new":
                    (
                        keyword_arguments,
                        implicit_pos_args,
                        explicit_pos_args,
                    ) = utils.parse_format_method_string(format_string)
                    keyword_args_cnt = len(
                        {k for k, _ in keyword_arguments if not isinstance(k, int)}
                    )
                    required_num_args = (
                        keyword_args_cnt + implicit_pos_args + explicit_pos_args
                    )
            except utils.UnsupportedFormatCharacter as ex:
                char = format_string[ex.index]
                self.add_message(
                    "logging-unsupported-format",
                    node=node,
                    args=(char, ord(char), ex.index),
                )
                return
            except utils.IncompleteFormatString:
                self.add_message("logging-format-truncated", node=node)
                return
        if num_args > required_num_args:
            self.add_message("logging-too-many-args", node=node, confidence=HIGH)
        elif num_args < required_num_args:
            self.add_message("logging-too-few-args", node=node)
References pylint.checkers.logging._count_supplied_tokens(), _format_style, and pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by _check_log_method().
_check_log_method()
None pylint.checkers.logging.LoggingChecker._check_log_method (self, nodes.Call node, str name) protected
Checks calls to logging.log(level, format, *format_args).
Definition at line 223 of file logging.py.
    def _check_log_method(self, node: nodes.Call, name: str) -> None:
        """Checks calls to logging.log(level, format, *format_args)."""
        if name == "log":
            if node.starargs or node.kwargs or len(node.args) < 2:
                # Either a malformed call, star args, or double-star args. Beyond
                # the scope of this checker.
                return
            format_pos: Literal[0, 1] = 1
        elif name in CHECKED_CONVENIENCE_FUNCTIONS:
            if node.starargs or node.kwargs or not node.args:
                # Either no args, star args, or double-star args. Beyond the
                # scope of this checker.
                return
            format_pos = 0
        else:
            return
        format_arg = node.args[format_pos]
        if isinstance(format_arg, nodes.BinOp):
            binop = format_arg
            emit = binop.op == "%"
            if binop.op == "+" and not self._is_node_explicit_str_concatenation(binop):
                total_number_of_strings = sum(
                    1
                    for operand in (binop.left, binop.right)
                    if self._is_operand_literal_str(utils.safe_infer(operand))
                )
                emit = total_number_of_strings > 0
            if emit:
                self.add_message(
                    "logging-not-lazy",
                    node=node,
                    args=(self._helper_string(node),),
                )
        elif isinstance(format_arg, nodes.Call):
            self._check_call_func(format_arg)
        elif isinstance(format_arg, nodes.Const):
            self._check_format_string(node, format_pos)
        elif isinstance(format_arg, nodes.JoinedStr):
            if str_formatting_in_f_string(format_arg):
                return
            self.add_message(
                "logging-fstring-interpolation",
                node=node,
                args=(self._helper_string(node),),
            )
References _check_call_func(), _check_format_string(), _helper_string(), _is_node_explicit_str_concatenation(), _is_operand_literal_str(), pylint.checkers.base_checker.BaseChecker.add_message(), and pylint.checkers.logging.str_formatting_in_f_string().
Referenced by visit_call().
_helper_string()
str pylint.checkers.logging.LoggingChecker._helper_string (self, nodes.Call node) protected
Create a string that lists the valid types of formatting for this node.
Definition at line 270 of file logging.py.
    def _helper_string(self, node: nodes.Call) -> str:
        """Create a string that lists the valid types of formatting for this node."""
        valid_types = ["lazy %"]
        if not self.linter.is_message_enabled(
            "logging-fstring-formatting", node.fromlineno
        ):
            valid_types.append("fstring")
        if not self.linter.is_message_enabled(
            "logging-format-interpolation", node.fromlineno
        ):
            valid_types.append(".format()")
        if not self.linter.is_message_enabled("logging-not-lazy", node.fromlineno):
            valid_types.append("%")
        return " or ".join(valid_types)
References pylint.checkers.base_checker.BaseChecker.linter.
Referenced by _check_call_func(), and _check_log_method().
_is_node_explicit_str_concatenation()
bool pylint.checkers.logging.LoggingChecker._is_node_explicit_str_concatenation (nodes.NodeNG node) static protected
Return True if the node represents an explicitly concatenated string.
Definition at line 293 of file logging.py.
    def _is_node_explicit_str_concatenation(node: nodes.NodeNG) -> bool:
        """Return True if the node represents an explicitly concatenated string."""
        if not isinstance(node, nodes.BinOp):
            return False
        return (
            LoggingChecker._is_operand_literal_str(node.left)
            or LoggingChecker._is_node_explicit_str_concatenation(node.left)
        ) and (
            LoggingChecker._is_operand_literal_str(node.right)
            or LoggingChecker._is_node_explicit_str_concatenation(node.right)
        )
Referenced by _check_log_method().
_is_operand_literal_str()
bool pylint.checkers.logging.LoggingChecker._is_operand_literal_str (InferenceResult | None operand) static protected
Return True if the operand in argument is a literal string.
Definition at line 288 of file logging.py.
    def _is_operand_literal_str(operand: InferenceResult | None) -> bool:
        """Return True if the operand in argument is a literal string."""
        return isinstance(operand, nodes.Const) and operand.name == "str"
Referenced by _check_log_method().
visit_call()
None pylint.checkers.logging.LoggingChecker.visit_call (self, nodes.Call node)
Checks calls to logging methods.
Definition at line 191 of file logging.py.
    def visit_call(self, node: nodes.Call) -> None:
        """Checks calls to logging methods."""
        def is_logging_name() -> bool:
            return (
                isinstance(node.func, nodes.Attribute)
                and isinstance(node.func.expr, nodes.Name)
                and node.func.expr.name in self._logging_names
            )
        def is_logger_class() -> tuple[bool, str | None]:
            for inferred in infer_all(node.func):
                if isinstance(inferred, astroid.BoundMethod):
                    parent = inferred._proxied.parent
                    if isinstance(parent, nodes.ClassDef) and (
                        parent.qname() == "logging.Logger"
                        or any(
                            ancestor.qname() == "logging.Logger"
                            for ancestor in parent.ancestors()
                        )
                    ):
                        return True, inferred._proxied.name
            return False, None
        if is_logging_name():
            name = node.func.attrname
        else:
            result, name = is_logger_class()
            if not result:
                return
        self._check_log_method(node, name)
References _check_log_method(), and _logging_names.
visit_import()
None pylint.checkers.logging.LoggingChecker.visit_import (self, nodes.Import node)
Checks to see if this module uses Python's built-in logging.
Definition at line 185 of file logging.py.
    def visit_import(self, node: nodes.Import) -> None:
        """Checks to see if this module uses Python's built-in logging."""
        for module, as_name in node.names:
            if module in self._logging_modules:
                self._logging_names.add(as_name or module)
References _logging_modules, and _logging_names.
visit_importfrom()
None pylint.checkers.logging.LoggingChecker.visit_importfrom (self, nodes.ImportFrom node)
Checks to see if a module uses a non-Python logging module.
Definition at line 175 of file logging.py.
    def visit_importfrom(self, node: nodes.ImportFrom) -> None:
        """Checks to see if a module uses a non-Python logging module."""
        try:
            logging_name = self._from_imports[node.modname]
            for module, as_name in node.names:
                if module == logging_name:
                    self._logging_names.add(as_name or module)
        except KeyError:
            pass
References _from_imports, and _logging_names.
visit_module()
None pylint.checkers.logging.LoggingChecker.visit_module (self, nodes.Module _)
Clears any state left in this checker from last module checked.
Definition at line 158 of file logging.py.
    def visit_module(self, _: nodes.Module) -> None:
        """Clears any state left in this checker from last module checked."""
        # The code being checked can just as easily "import logging as foo",
        # so it is necessary to process the imports and store in this field
        # what name the logging module is actually given.
        self._logging_names: set[str] = set()
        logging_mods = self.linter.config.logging_modules
        self._format_style = self.linter.config.logging_format_style
        self._logging_modules = set(logging_mods)
        self._from_imports = {}
        for logging_mod in logging_mods:
            parts = logging_mod.rsplit(".", 1)
            if len(parts) > 1:
                self._from_imports[parts[0]] = parts[1]
Referenced by pylint.pyreverse.inspector.Linker.visit_assignname().
Member Data Documentation
_format_style
str pylint.checkers.logging.LoggingChecker._format_style = self.linter.config.logging_format_style protected
Definition at line 166 of file logging.py.
Referenced by _check_format_string().
_from_imports
dict pylint.checkers.logging.LoggingChecker._from_imports = {} protected
Definition at line 169 of file logging.py.
Referenced by visit_importfrom().
_logging_modules
pylint.checkers.logging.LoggingChecker._logging_modules = set(logging_mods) protected
Definition at line 168 of file logging.py.
Referenced by visit_import().
_logging_names
set[str] pylint.checkers.logging.LoggingChecker._logging_names = set() protected
Definition at line 163 of file logging.py.
Referenced by visit_call(), visit_import(), and visit_importfrom().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pylint/checkers/logging.py