Read&Watch: pip._vendor.typing_extensions.Doc Class Reference
pip._vendor.typing_extensions.Doc Class Reference
Public Member Functions
None __init__ (self, str documentation)
str __repr__ (self)
int __hash__ (self)
bool __eq__ (self, object other)
Public Attributes
documentation = documentation
Detailed Description
Define the documentation of a type annotation using ``Annotated``, to be
 used in class attributes, function and method parameters, return values,
 and variables.
The value should be a positional-only string literal to allow static tools
like editors and documentation generators to use it.
This complements docstrings.
The string value passed is available in the attribute ``documentation``.
Example::
    >>> from typing_extensions import Annotated, Doc
    >>> def hi(to: Annotated[str, Doc("Who to say hi to")]) -> None: ...
Definition at line 3553 of file typing_extensions.py.
Constructor & Destructor Documentation
__init__()
None pip._vendor.typing_extensions.Doc.__init__ (self, str documentation)
Definition at line 3570 of file typing_extensions.py.
        def __init__(self, documentation: str, /) -> None:
            self.documentation = documentation
Member Function Documentation
__eq__()
bool pip._vendor.typing_extensions.Doc.__eq__ (self, object other)
Definition at line 3579 of file typing_extensions.py.
        def __eq__(self, other: object) -> bool:
            if not isinstance(other, Doc):
                return NotImplemented
            return self.documentation == other.documentation
References documentation.
Referenced by dotenv.variables.Atom.__ne__(), pip._vendor.urllib3._collections.HTTPHeaderDict.__ne__(), responses.BaseResponse.__ne__(), and urllib3._collections.HTTPHeaderDict.__ne__().
__hash__()
int pip._vendor.typing_extensions.Doc.__hash__ (self)
Definition at line 3576 of file typing_extensions.py.
        def __hash__(self) -> int:
            return hash(self.documentation)
References documentation.
__repr__()
str pip._vendor.typing_extensions.Doc.__repr__ (self)
Definition at line 3573 of file typing_extensions.py.
        def __repr__(self) -> str:
            return f"Doc({self.documentation!r})"
Member Data Documentation
documentation
pip._vendor.typing_extensions.Doc.documentation = documentation
Definition at line 3571 of file typing_extensions.py.
Referenced by __eq__(), and __hash__().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/typing_extensions.py