Read&Watch: django.middleware.common.BrokenLinkEmailsMiddleware Class Reference
django.middleware.common.BrokenLinkEmailsMiddleware Class Reference
Public Member Functions
process_response (self, request, response)
is_internal_request (self, domain, referer)
is_ignorable_request (self, request, uri, domain, referer)
Public Member Functions inherited from django.utils.deprecation.MiddlewareMixin
__init__ (self, get_response)
__repr__ (self)
__call__ (self, request)
__acall__ (self, request)
Additional Inherited Members
Public Attributes inherited from django.utils.deprecation.MiddlewareMixin
get_response = get_response
async_mode = iscoroutinefunction(self.get_response)
Static Public Attributes inherited from django.utils.deprecation.MiddlewareMixin
bool sync_capable = True
bool async_capable = True
Detailed Description
Definition at line 118 of file common.py.
Member Function Documentation
is_ignorable_request()
django.middleware.common.BrokenLinkEmailsMiddleware.is_ignorable_request (self, request, uri, domain, referer)
Return True if the given request *shouldn't* notify the site managers
according to project settings or in situations outlined by the inline
comments.
Definition at line 153 of file common.py.
    def is_ignorable_request(self, request, uri, domain, referer):
        """
        Return True if the given request *shouldn't* notify the site managers
        according to project settings or in situations outlined by the inline
        comments.
        """
        # The referer is empty.
        if not referer:
            return True
        # APPEND_SLASH is enabled and the referer is equal to the current URL
        # without a trailing slash indicating an internal redirect.
        if settings.APPEND_SLASH and uri.endswith("/") and referer == uri[:-1]:
            return True
        # A '?' in referer is identified as a search engine source.
        if not self.is_internal_request(domain, referer) and "?" in referer:
            return True
        # The referer is equal to the current URL, ignoring the scheme (assumed
        # to be a poorly implemented bot).
        parsed_referer = urlparse(referer)
        if parsed_referer.netloc in ["", domain] and parsed_referer.path == uri:
            return True
        return any(pattern.search(uri) for pattern in settings.IGNORABLE_404_URLS)
References is_internal_request().
Referenced by process_response().
is_internal_request()
django.middleware.common.BrokenLinkEmailsMiddleware.is_internal_request (self, domain, referer)
Return True if the referring URL is the same domain as the current
request.
Definition at line 145 of file common.py.
    def is_internal_request(self, domain, referer):
        """
        Return True if the referring URL is the same domain as the current
        request.
        """
        # Different subdomains are treated as different domains.
        return bool(re.match("^https?://%s/" % re.escape(domain), referer))
Referenced by is_ignorable_request(), and process_response().
process_response()
django.middleware.common.BrokenLinkEmailsMiddleware.process_response (self, request, response)
Send broken link emails for relevant 404 NOT FOUND responses.
Definition at line 119 of file common.py.
    def process_response(self, request, response):
        """Send broken link emails for relevant 404 NOT FOUND responses."""
        if response.status_code == 404 and not settings.DEBUG:
            domain = request.get_host()
            path = request.get_full_path()
            referer = request.META.get("HTTP_REFERER", "")
            if not self.is_ignorable_request(request, path, domain, referer):
                ua = request.META.get("HTTP_USER_AGENT", "<none>")
                ip = request.META.get("REMOTE_ADDR", "<none>")
                mail_managers(
                    "Broken %slink on %s"
                    % (
                        (
                            "INTERNAL "
                            if self.is_internal_request(domain, referer)
                            else ""
                        ),
                        domain,
                    ),
                    "Referrer: %s\nRequested URL: %s\nUser agent: %s\n"
                    "IP address: %s\n" % (referer, path, ua, ip),
                    fail_silently=True,
                )
        return response
References is_ignorable_request(), and is_internal_request().
Referenced by django.utils.deprecation.MiddlewareMixin.__acall__(), django.utils.deprecation.MiddlewareMixin.__call__(), and pip._vendor.rich.prompt.PromptBase.__call__().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/middleware/common.py