Read&Watch: charset_normalizer.md.CjkInvalidStopPlugin Class Reference
charset_normalizer.md.CjkInvalidStopPlugin Class Reference
Public Member Functions
None __init__ (self)
bool eligible (self, str character)
None feed (self, str character)
None reset (self)
float ratio (self)
Protected Attributes
int _wrong_stop_count = 0
int _cjk_character_count = 0
Detailed Description
GB(Chinese) based encoding often render the stop incorrectly when the content does not fit and
can be easily detected. Searching for the overuse of '丅' and '丄'.
Definition at line 367 of file md.py.
Constructor & Destructor Documentation
__init__()
None charset_normalizer.md.CjkInvalidStopPlugin.__init__ (self)
Definition at line 373 of file md.py.
    def __init__(self) -> None:
        self._wrong_stop_count: int = 0
        self._cjk_character_count: int = 0
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
eligible()
bool charset_normalizer.md.CjkInvalidStopPlugin.eligible (self, str character)
Determine if given character should be fed in.
Reimplemented from charset_normalizer.md.MessDetectorPlugin.
Definition at line 377 of file md.py.
    def eligible(self, character: str) -> bool:
        return True
feed()
None charset_normalizer.md.CjkInvalidStopPlugin.feed (self, str character)
The main routine to be executed upon character.
Insert the logic in witch the text would be considered chaotic.
Reimplemented from charset_normalizer.md.MessDetectorPlugin.
Definition at line 380 of file md.py.
    def feed(self, character: str) -> None:
        if character in {"丅", "丄"}:
            self._wrong_stop_count += 1
            return
        if is_cjk(character):
            self._cjk_character_count += 1
References _cjk_character_count, and _wrong_stop_count.
Referenced by PIL.ImageFile.Parser.close(), and django.db.migrations.writer.OperationWriter.serialize().
ratio()
float charset_normalizer.md.CjkInvalidStopPlugin.ratio (self)
Compute the chaos ratio based on what your feed() has seen.
Must NOT be lower than 0.; No restriction gt 0.
Reimplemented from charset_normalizer.md.MessDetectorPlugin.
Definition at line 392 of file md.py.
    def ratio(self) -> float:
        if self._cjk_character_count < 16:
            return 0.0
        return self._wrong_stop_count / self._cjk_character_count
References _cjk_character_count, and _wrong_stop_count.
reset()
None charset_normalizer.md.CjkInvalidStopPlugin.reset (self)
Permit to reset the plugin to the initial state.
Reimplemented from charset_normalizer.md.MessDetectorPlugin.
Definition at line 387 of file md.py.
    def reset(self) -> None:  # pragma: no cover
        self._wrong_stop_count = 0
        self._cjk_character_count = 0
References _cjk_character_count, and _wrong_stop_count.
Referenced by responses.RequestsMock.__exit__(), django.utils.html.MLStripper.__init__(), pylint.extensions.mccabe.PathGraphingAstVisitor._subgraph(), pylint.testutils.reporter_for_tests.GenericTestReporter.finalize(), and PIL.TiffImagePlugin.ImageFileDirectory_v2.load().
Member Data Documentation
_cjk_character_count
int charset_normalizer.md.CjkInvalidStopPlugin._cjk_character_count = 0 protected
Definition at line 375 of file md.py.
Referenced by feed(), ratio(), and reset().
_wrong_stop_count
int charset_normalizer.md.CjkInvalidStopPlugin._wrong_stop_count = 0 protected
Definition at line 374 of file md.py.
Referenced by feed(), ratio(), and reset().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/charset_normalizer/md.py