Read&Watch: crispy_forms.layout.ButtonHolder Class Reference
crispy_forms.layout.ButtonHolder Class Reference
Public Member Functions
__init__ (self, *fields, css_id=None, css_class=None, template=None)
render (self, form, context, template_pack=TEMPLATE_PACK, **kwargs)
Public Member Functions inherited from crispy_forms.layout.LayoutObject
__getitem__ (self, slice)
__setitem__ (self, slice, value)
__delitem__ (self, slice)
__len__ (self)
__getattr__ (self, name)
get_field_names (self, index=None)
get_layout_objects (self, *LayoutClasses, index=None, max_level=0, greedy=False)
get_rendered_fields (self, form, context, template_pack=TEMPLATE_PACK, **kwargs)
Public Member Functions inherited from crispy_forms.layout.TemplateNameMixin
get_template_name (self, template_pack)
Public Attributes
css_id = css_id
css_class = css_class
Public Attributes inherited from crispy_forms.layout.LayoutObject
fields
Public Attributes inherited from crispy_forms.layout.TemplateNameMixin
template
Detailed Description
Layout object. It wraps fields in a <div class="buttonHolder">
This is where you should put Layout objects that render to form buttons
Attributes
----------
template: str
    The default template which this Layout Object will be rendered
    with.
Parameters
----------
*fields : HTML or BaseInput
    The layout objects to render within the ``ButtonHolder``. It should
    only hold `HTML` and `BaseInput` inherited objects.
css_id : str, optional
    A custom DOM id for the layout object. If not provided the name
    argument is slugified and turned into the id for the submit button.
    By default None.
css_class : str, optional
    Additional CSS classes to be applied to the ``<input>``. By default
    None.
template : str, optional
    Overrides the default template, if provided. By default None.
Examples
--------
An example using ``ButtonHolder`` in your layout::
    ButtonHolder(
        HTML(<span style="display: hidden;">Information Saved</span>),
        Submit('Save', 'Save')
    )
Definition at line 145 of file layout.py.
Constructor & Destructor Documentation
__init__()
crispy_forms.layout.ButtonHolder.__init__ (self, * fields, css_id = None, css_class = None, template = None)
Definition at line 185 of file layout.py.
    def __init__(self, *fields, css_id=None, css_class=None, template=None):
        self.fields = list(fields)
        self.css_id = css_id
        self.css_class = css_class
        self.template = template or self.template
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
render()
crispy_forms.layout.ButtonHolder.render (self, form, context, template_pack = TEMPLATE_PACK, ** kwargs)
Definition at line 191 of file layout.py.
    def render(self, form, context, template_pack=TEMPLATE_PACK, **kwargs):
        html = self.get_rendered_fields(form, context, template_pack, **kwargs)
        template = self.get_template_name(template_pack)
        context.update({"buttonholder": self, "fields_output": html})
        return render_to_string(template, context.flatten())
References crispy_forms.layout.LayoutObject.get_rendered_fields(), and crispy_forms.layout.TemplateNameMixin.get_template_name().
Referenced by pip._vendor.rich.progress.ProgressColumn.__call__(), pip._vendor.rich.layout.Layout.__rich_console__(), pip._vendor.rich.spinner.Spinner.__rich_console__(), pip._vendor.rich.spinner.Spinner.__rich_measure__(), django.forms.widgets.Media.__str__(), django.forms.utils.RenderableFieldMixin.as_field_group(), pip._vendor.rich.console.Console.log(), pip._vendor.rich.console.Console.print(), django.templatetags.i18n.BlockTranslateNode.render(), pip._vendor.rich.console.Console.render(), pip._vendor.rich.console.Console.render_lines(), django.db.migrations.writer.OperationWriter.serialize(), and pip._vendor.rich.console.Console.update_screen_lines().
Member Data Documentation
css_class
crispy_forms.layout.ButtonHolder.css_class = css_class
Definition at line 188 of file layout.py.
Referenced by crispy_forms.layout.MultiField.render().
css_id
crispy_forms.layout.ButtonHolder.css_id = css_id
Definition at line 187 of file layout.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/crispy_forms/layout.py