Read&Watch: django.contrib.staticfiles.finders.BaseFinder Class Reference
django.contrib.staticfiles.finders.BaseFinder Class Reference
Public Member Functions
check (self, **kwargs)
find (self, path, all=False)
list (self, ignore_patterns)
Detailed Description
A base file finder to be used for custom staticfiles finder classes.
Definition at line 18 of file finders.py.
Member Function Documentation
check()
django.contrib.staticfiles.finders.BaseFinder.check (self, ** kwargs)
Reimplemented in django.contrib.staticfiles.finders.FileSystemFinder.
Definition at line 23 of file finders.py.
    def check(self, **kwargs):
        raise NotImplementedError(
            "subclasses may provide a check() method to verify the finder is "
            "configured correctly."
        )
Referenced by pip._vendor.packaging._tokenizer.Tokenizer.consume(), pip._vendor.packaging._tokenizer.Tokenizer.enclosing_tokens(), django.core.management.base.BaseCommand.execute(), pip._vendor.packaging._tokenizer.Tokenizer.expect(), django.core.management.commands.check.Command.handle(), django.core.management.commands.migrate.Command.handle(), django.core.management.commands.runserver.Command.inner_run(), and pip._vendor.pygments.scanner.Scanner.test().
find()
django.contrib.staticfiles.finders.BaseFinder.find (self, path, all = False)
Given a relative file path, find an absolute file path.
If the ``all`` parameter is False (default) return only the first found
file path; if True, return a list of all found files paths.
Reimplemented in django.contrib.staticfiles.finders.AppDirectoriesFinder, django.contrib.staticfiles.finders.BaseStorageFinder, and django.contrib.staticfiles.finders.FileSystemFinder.
Definition at line 29 of file finders.py.
    def find(self, path, all=False):
        """
        Given a relative file path, find an absolute file path.
        If the ``all`` parameter is False (default) return only the first found
        file path; if True, return a list of all found files paths.
        """
        raise NotImplementedError(
            "subclasses of BaseFinder must provide a find() method"
        )
Referenced by pip._vendor.distlib.resources.ResourceFinder.iterator().
list()
django.contrib.staticfiles.finders.BaseFinder.list (self, ignore_patterns)
Given an optional list of paths to ignore, return a two item iterable
consisting of the relative path and storage instance.
Reimplemented in django.contrib.staticfiles.finders.AppDirectoriesFinder, django.contrib.staticfiles.finders.BaseStorageFinder, and django.contrib.staticfiles.finders.FileSystemFinder.
Definition at line 40 of file finders.py.
    def list(self, ignore_patterns):
        """
        Given an optional list of paths to ignore, return a two item iterable
        consisting of the relative path and storage instance.
        """
        raise NotImplementedError(
            "subclasses of BaseFinder must provide a list() method"
        )
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/staticfiles/finders.py