Read&Watch: pip._vendor.typing_extensions._LiteralGenericAlias Class Reference
pip._vendor.typing_extensions._LiteralGenericAlias Class Reference
Public Member Functions
__eq__ (self, other)
__hash__ (self)
Detailed Description
Definition at line 277 of file typing_extensions.py.
Member Function Documentation
__eq__()
pip._vendor.typing_extensions._LiteralGenericAlias.__eq__ (self, other)
Definition at line 278 of file typing_extensions.py.
        def __eq__(self, other):
            if not isinstance(other, _LiteralGenericAlias):
                return NotImplemented
            these_args_deduped = set(_value_and_type_iter(self.__args__))
            other_args_deduped = set(_value_and_type_iter(other.__args__))
            return these_args_deduped == other_args_deduped
References __args__, and pip._vendor.typing_extensions._value_and_type_iter().
Referenced by dotenv.variables.Atom.__ne__(), pip._vendor.urllib3._collections.HTTPHeaderDict.__ne__(), responses.BaseResponse.__ne__(), and urllib3._collections.HTTPHeaderDict.__ne__().
__hash__()
pip._vendor.typing_extensions._LiteralGenericAlias.__hash__ (self)
Definition at line 285 of file typing_extensions.py.
        def __hash__(self):
            return hash(frozenset(_value_and_type_iter(self.__args__)))
    class _LiteralForm(_ExtensionsSpecialForm, _root=True):
References __args__, and pip._vendor.typing_extensions._value_and_type_iter().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/typing_extensions.py