Read&Watch: isort.pylama_isort.Linter Class Reference
isort.pylama_isort.Linter Class Reference
Public Member Functions
bool allow (self, str path)
List[Dict[str, Any]] run (self, str path, Optional[Dict[str, Any]] params=None, **Any meta)
Detailed Description
Definition at line 22 of file pylama_isort.py.
Member Function Documentation
allow()
bool isort.pylama_isort.Linter.allow (self, str path)
Determine if this path should be linted.
Definition at line 23 of file pylama_isort.py.
    def allow(self, path: str) -> bool:
        """Determine if this path should be linted."""
        return path.endswith(".py")
run()
List[Dict[str, Any]] isort.pylama_isort.Linter.run (self, str path, Optional[Dict[str, Any]] params = None, **Any meta)
Lint the file. Return an array of error dicts if appropriate.
Definition at line 27 of file pylama_isort.py.
    ) -> List[Dict[str, Any]]:
        """Lint the file. Return an array of error dicts if appropriate."""
        with suppress_stdout():
            try:
                if not api.check_file(path, disregard_skip=False, **params or {}):
                    return [
{
                            "lnum": 0,
                            "col": 0,
                            "text": "Incorrectly sorted imports.",
                            "type": "ISORT",
                        }
                    ]
            except FileSkipped:
                pass
            return []
References isort.pylama_isort.suppress_stdout().
Referenced by pylint.pyreverse.main.Run.__init__(), and pip._internal.cli.base_command.Command._run_wrapper().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/isort/pylama_isort.py