Read&Watch: pip._internal.resolution.resolvelib.base.Requirement Class Reference
pip._internal.resolution.resolvelib.base.Requirement Class Reference
Public Member Functions
NormalizedName project_name (self)
str name (self)
bool is_satisfied_by (self, "Candidate" candidate)
CandidateLookup get_candidate_lookup (self)
str format_for_error (self)
Detailed Description
Definition at line 60 of file base.py.
Member Function Documentation
format_for_error()
str pip._internal.resolution.resolvelib.base.Requirement.format_for_error (self)
Reimplemented in pip._internal.resolution.resolvelib.requirements.ExplicitRequirement, pip._internal.resolution.resolvelib.requirements.RequiresPythonRequirement, pip._internal.resolution.resolvelib.requirements.SpecifierRequirement, and pip._internal.resolution.resolvelib.requirements.UnsatisfiableRequirement.
Definition at line 86 of file base.py.
    def format_for_error(self) -> str:
        raise NotImplementedError("Subclass should override")
get_candidate_lookup()
CandidateLookup pip._internal.resolution.resolvelib.base.Requirement.get_candidate_lookup (self)
Reimplemented in pip._internal.resolution.resolvelib.requirements.ExplicitRequirement, pip._internal.resolution.resolvelib.requirements.RequiresPythonRequirement, pip._internal.resolution.resolvelib.requirements.SpecifierRequirement, and pip._internal.resolution.resolvelib.requirements.UnsatisfiableRequirement.
Definition at line 83 of file base.py.
    def get_candidate_lookup(self) -> CandidateLookup:
        raise NotImplementedError("Subclass should override")
is_satisfied_by()
bool pip._internal.resolution.resolvelib.base.Requirement.is_satisfied_by (self, "Candidate" candidate)
Reimplemented in pip._internal.resolution.resolvelib.requirements.ExplicitRequirement, pip._internal.resolution.resolvelib.requirements.RequiresPythonRequirement, pip._internal.resolution.resolvelib.requirements.SpecifierRequirement, and pip._internal.resolution.resolvelib.requirements.UnsatisfiableRequirement.
Definition at line 80 of file base.py.
    def is_satisfied_by(self, candidate: "Candidate") -> bool:
        return False
Referenced by pip._internal.resolution.resolvelib.provider.PipProvider.find_matches().
name()
str pip._internal.resolution.resolvelib.base.Requirement.name (self)
The name identifying this requirement in the resolver.
This is different from ``project_name`` if this requirement contains
extras, where ``project_name`` would not contain the ``[...]`` part.
Reimplemented in pip._internal.resolution.resolvelib.requirements.ExplicitRequirement, pip._internal.resolution.resolvelib.requirements.RequiresPythonRequirement, pip._internal.resolution.resolvelib.requirements.SpecifierRequirement, and pip._internal.resolution.resolvelib.requirements.UnsatisfiableRequirement.
Definition at line 72 of file base.py.
    def name(self) -> str:
        """The name identifying this requirement in the resolver.
        This is different from ``project_name`` if this requirement contains
        extras, where ``project_name`` would not contain the ``[...]`` part.
        """
        raise NotImplementedError("Subclass should override")
Referenced by pip._vendor.rich.markup.Tag.__str__(), pip._internal.resolution.resolvelib.requirements.SpecifierRequirement.is_satisfied_by(), pip._vendor.distro.distro.LinuxDistribution.linux_distribution(), and astroid.nodes.scoped_nodes.mixin.LocalsDictNodeNG.qname().
project_name()
NormalizedName pip._internal.resolution.resolvelib.base.Requirement.project_name (self)
The "project name" of a requirement.
This is different from ``name`` if this requirement contains extras,
in which case ``name`` would contain the ``[...]`` part, while this
refers to the name of the project.
Reimplemented in pip._internal.resolution.resolvelib.requirements.ExplicitRequirement, pip._internal.resolution.resolvelib.requirements.RequiresPythonRequirement, pip._internal.resolution.resolvelib.requirements.SpecifierRequirement, and pip._internal.resolution.resolvelib.requirements.UnsatisfiableRequirement.
Definition at line 62 of file base.py.
    def project_name(self) -> NormalizedName:
        """The "project name" of a requirement.
        This is different from ``name`` if this requirement contains extras,
        in which case ``name`` would contain the ``[...]`` part, while this
        refers to the name of the project.
        """
        raise NotImplementedError("Subclass should override")
Referenced by pip._internal.resolution.resolvelib.candidates._InstallRequirementBackedCandidate.name(), and pip._internal.resolution.resolvelib.candidates.AlreadyInstalledCandidate.name().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_internal/resolution/resolvelib/base.py