Read&Watch: pip._internal.exceptions.HashMissing Class Reference
pip._internal.exceptions.HashMissing Class Reference
Public Member Functions
None __init__ (self, str gotten_hash)
str body (self)
Public Member Functions inherited from pip._internal.exceptions.HashError
str __str__ (self)
Public Attributes
gotten_hash = gotten_hash
Additional Inherited Members
Static Public Attributes inherited from pip._internal.exceptions.HashError
Optional req = None
str head = ""
int order = -1
Protected Member Functions inherited from pip._internal.exceptions.HashError
str _requirement_name (self)
Detailed Description
A hash was needed for a requirement but is absent.
Definition at line 521 of file exceptions.py.
Constructor & Destructor Documentation
__init__()
None pip._internal.exceptions.HashMissing.__init__ (self, str gotten_hash)
:param gotten_hash: The hash of the (possibly malicious) archive we
    just downloaded
Definition at line 535 of file exceptions.py.
    def __init__(self, gotten_hash: str) -> None:
        """
        :param gotten_hash: The hash of the (possibly malicious) archive we
            just downloaded
        """
        self.gotten_hash = gotten_hash
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
body()
str pip._internal.exceptions.HashMissing.body (self)
Return a summary of me for display under the heading.
This default implementation simply prints a description of the
triggering requirement.
:param req: The InstallRequirement that provoked this error, with
    its link already populated by the resolver's _populate_link().
Reimplemented from pip._internal.exceptions.HashError.
Definition at line 542 of file exceptions.py.
    def body(self) -> str:
        # Dodge circular import.
        from pip._internal.utils.hashes import FAVORITE_HASH
        package = None
        if self.req:
            # In the case of URL-based requirements, display the original URL
            # seen in the requirements file rather than the package name,
            # so the output can be directly copied into the requirements file.
            package = (
                self.req.original_link
                if self.req.is_direct
                # In case someone feeds something downright stupid
                # to InstallRequirement's constructor.
                else getattr(self.req, "req", None)
            )
        return "    {} --hash={}:{}".format(
            package or "unknown package", FAVORITE_HASH, self.gotten_hash
        )
Referenced by tomlkit.container.Container.__copy__(), and astroid.nodes.scoped_nodes.mixin.LocalsDictNodeNG._append_node().
Member Data Documentation
gotten_hash
pip._internal.exceptions.HashMissing.gotten_hash = gotten_hash
Definition at line 540 of file exceptions.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_internal/exceptions.py