Read&Watch: pylint.extensions.broad_try_clause.BroadTryClauseChecker Class Reference
pylint.extensions.broad_try_clause.BroadTryClauseChecker Class Reference
Public Member Functions
None visit_try (self, nodes.Try node)
Public Member Functions inherited from pylint.checkers.base_checker.BaseChecker
None __init__ (self, PyLinter linter)
bool __gt__ (self, Any other)
bool __eq__ (self, object other)
int __hash__ (self)
str __repr__ (self)
str __str__ (self)
str get_full_documentation (self, dict[str, MessageDefinitionTuple] msgs, Iterable[tuple[str, OptionDict, Any]] options, Sequence[tuple[str, str, ReportsCallable]] reports, str|None doc=None, str|None module=None, bool show_options=True)
None add_message (self, str msgid, int|None line=None, nodes.NodeNG|None node=None, Any args=None, Confidence|None confidence=None, int|None col_offset=None, int|None end_lineno=None, int|None end_col_offset=None)
None check_consistency (self)
MessageDefinition create_message_definition_from_tuple (self, str msgid, MessageDefinitionTuple msg_tuple)
list[MessageDefinition] messages (self)
None open (self)
None close (self)
Any get_map_data (self)
None reduce_map_data (self, PyLinter linter, list[Any] data)
Public Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
None __init__ (self, _ArgumentsManager arguments_manager)
Protected Member Functions
int _count_statements (self, nodes.For|nodes.If|nodes.Try|nodes.While|nodes.With node)
Protected Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
Any _option_value (self, str opt)
Iterator[ tuple[str, list[tuple[str, OptionDict, Any]]]|tuple[None, dict[str, list[tuple[str, OptionDict, Any]]]]] _options_by_section (self)
Iterator[tuple[str, OptionDict, Any]] _options_and_values (self, Options|None options=None)
Additional Inherited Members
Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
linter = linter
messages
Static Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
str name = ""
dict msgs = {}
tuple reports = ()
bool enabled = True
Static Public Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
tuple options = ()
dict option_groups_descs = {}
Protected Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
_arguments_manager = arguments_manager
Detailed Description
Checks for try clauses with too many lines.
According to PEP 8, ``try`` clauses shall contain the absolute minimum
amount of code. This checker enforces a maximum number of statements within
``try`` clauses.
Definition at line 19 of file broad_try_clause.py.
Member Function Documentation
_count_statements()
int pylint.extensions.broad_try_clause.BroadTryClauseChecker._count_statements (self, nodes.For | nodes.If | nodes.Try | nodes.While | nodes.With node) protected
Definition at line 49 of file broad_try_clause.py.
    ) -> int:
        statement_count = len(node.body)
        for body_node in node.body:
            if isinstance(body_node, (nodes.For, nodes.If, nodes.While, nodes.With)):
                statement_count += self._count_statements(body_node)
        return statement_count
References _count_statements().
Referenced by _count_statements(), and visit_try().
visit_try()
None pylint.extensions.broad_try_clause.BroadTryClauseChecker.visit_try (self, nodes.Try node)
Definition at line 60 of file broad_try_clause.py.
    def visit_try(self, node: nodes.Try) -> None:
        try_clause_statements = self._count_statements(node)
        if try_clause_statements > self.linter.config.max_try_statements:
            msg = (
                f"try clause contains {try_clause_statements} statements, expected at"
                f" most {self.linter.config.max_try_statements}"
            )
            self.add_message(
                "too-many-try-statements", node.lineno, node=node, args=msg
            )
References _count_statements(), pylint.checkers.base_checker.BaseChecker.add_message(), and pylint.checkers.base_checker.BaseChecker.linter.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pylint/extensions/broad_try_clause.py