Read&Watch: tomlkit.items.Whitespace Class Reference
tomlkit.items.Whitespace Class Reference
Public Member Functions
None __init__ (self, str s, bool fixed=False)
str s (self)
str value (self)
Trivia trivia (self)
int discriminant (self)
bool is_fixed (self)
str as_string (self)
str __repr__ (self)
Public Member Functions inherited from tomlkit.items.Item
None __init__ (self, Trivia trivia)
Any unwrap (self)
Item comment (self, str comment)
Item indent (self, int indent)
bool is_boolean (self)
bool is_table (self)
bool is_inline_table (self)
bool is_aot (self)
__reduce__ (self)
__reduce_ex__ (self, protocol)
Protected Member Functions
_getstate (self, protocol=3)
Protected Attributes
str _s = s
_fixed = fixed
Protected Attributes inherited from tomlkit.items.Item
Trivia _trivia = trivia
Detailed Description
A whitespace literal.
Definition at line 519 of file items.py.
Constructor & Destructor Documentation
__init__()
None tomlkit.items.Whitespace.__init__ (self, str s, bool fixed = False)
Definition at line 524 of file items.py.
    def __init__(self, s: str, fixed: bool = False) -> None:
        self._s = s
        self._fixed = fixed
Member Function Documentation
__repr__()
str tomlkit.items.Whitespace.__repr__ (self)
Definition at line 552 of file items.py.
    def __repr__(self) -> str:
        return f"<{self.__class__.__name__} {self._s!r}>"
_getstate()
tomlkit.items.Whitespace._getstate (self, protocol = 3) protected
Reimplemented from tomlkit.items.Item.
Definition at line 555 of file items.py.
    def _getstate(self, protocol=3):
        return self._s, self._fixed
References _fixed, and _s.
as_string()
str tomlkit.items.Whitespace.as_string (self)
The TOML representation
Reimplemented from tomlkit.items.Item.
Definition at line 549 of file items.py.
    def as_string(self) -> str:
        return self._s
References _s.
discriminant()
int tomlkit.items.Whitespace.discriminant (self)
Reimplemented from tomlkit.items.Item.
Definition at line 542 of file items.py.
    def discriminant(self) -> int:
        return 0
is_fixed()
bool tomlkit.items.Whitespace.is_fixed (self)
If the whitespace is fixed, it can't be merged or discarded from the output.
Definition at line 545 of file items.py.
    def is_fixed(self) -> bool:
        """If the whitespace is fixed, it can't be merged or discarded from the output."""
        return self._fixed
References _fixed.
s()
str tomlkit.items.Whitespace.s (self)
Definition at line 529 of file items.py.
    def s(self) -> str:
        return self._s
References _s.
trivia()
Trivia tomlkit.items.Whitespace.trivia (self)
The trivia element associated with this item
Reimplemented from tomlkit.items.Item.
Definition at line 538 of file items.py.
    def trivia(self) -> Trivia:
        raise RuntimeError("Called trivia on a Whitespace variant.")
value()
str tomlkit.items.Whitespace.value (self)
The wrapped string of the whitespace
Reimplemented from tomlkit.items.Item.
Definition at line 533 of file items.py.
    def value(self) -> str:
        """The wrapped string of the whitespace"""
        return self._s
References _s.
Referenced by pip._internal.models.link.LinkHash.as_hashes(), pip._internal.models.link.LinkHash.is_hash_allowed(), and tomlkit.items.StringType.unit().
Member Data Documentation
_fixed
tomlkit.items.Whitespace._fixed = fixed protected
Definition at line 526 of file items.py.
Referenced by _getstate(), and is_fixed().
_s
tomlkit.items.Whitespace._s = s protected
Definition at line 525 of file items.py.
Referenced by _getstate(), as_string(), s(), and value().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/tomlkit/items.py