Read&Watch: apscheduler.events.JobEvent Class Reference
apscheduler.events.JobEvent Class Reference
Public Member Functions
__init__ (self, code, job_id, jobstore)
Public Member Functions inherited from apscheduler.events.SchedulerEvent
__init__ (self, code, alias=None)
__repr__ (self)
Public Attributes
job_id = job_id
jobstore = jobstore
Public Attributes inherited from apscheduler.events.SchedulerEvent
code = code
alias = alias
Detailed Description
An event that concerns a job.
:ivar code: the type code of this event
:ivar job_id: identifier of the job in question
:ivar jobstore: alias of the job store containing the job in question
Definition at line 82 of file events.py.
Constructor & Destructor Documentation
__init__()
apscheduler.events.JobEvent.__init__ (self, code, job_id, jobstore)
Definition at line 91 of file events.py.
    def __init__(self, code, job_id, jobstore):
        super().__init__(code)
        self.code = code
        self.job_id = job_id
        self.jobstore = jobstore
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Data Documentation
job_id
apscheduler.events.JobEvent.job_id = job_id
Definition at line 94 of file events.py.
jobstore
apscheduler.events.JobEvent.jobstore = jobstore
Definition at line 95 of file events.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/apscheduler/events.py