Read&Watch: crispy_forms.layout.Fieldset Class Reference
crispy_forms.layout.Fieldset Class Reference
Public Member Functions
__init__ (self, legend, *fields, css_class=None, css_id=None, template=None, **kwargs)
render (self, form, context, template_pack=TEMPLATE_PACK, **kwargs)
Public Member Functions inherited from crispy_forms.layout.LayoutObject
__getitem__ (self, slice)
__setitem__ (self, slice, value)
__delitem__ (self, slice)
__len__ (self)
__getattr__ (self, name)
get_field_names (self, index=None)
get_layout_objects (self, *LayoutClasses, index=None, max_level=0, greedy=False)
get_rendered_fields (self, form, context, template_pack=TEMPLATE_PACK, **kwargs)
Public Member Functions inherited from crispy_forms.layout.TemplateNameMixin
get_template_name (self, template_pack)
Public Attributes
legend = legend
css_class = css_class
css_id = css_id
flat_attrs = flatatt(kwargs)
Public Attributes inherited from crispy_forms.layout.LayoutObject
fields
Public Attributes inherited from crispy_forms.layout.TemplateNameMixin
template
Detailed Description
A layout object which wraps fields in a ``<fieldset>``
Parameters
----------
legend : str
    The content of the fieldset's ``<legend>``. This text is context
    aware, to bring this to life see the examples section.
*fields : str | LayoutObject | HTML
    Any number of fields as positional arguments to be rendered within
    the ``<fieldset>``
css_class : str, optional
    Additional CSS classes to be applied to the ``<input>``. By default
    None.
css_id : str, optional
    A custom DOM id for the layout object. If not provided the name
    argument is slugified and turned into the id for the submit button.
    By default None.
template : str, optional
    Overrides the default template, if provided. By default None.
**kwargs : dict, optional
    Additional attributes are passed to ``flatatt`` and converted into
    key="value", pairs. These attributes are added to the ``<fieldset>``.
Examples
--------
The Fieldset Layout object is added to your ``Layout`` for example::
    Fieldset("Text for the legend",
        "form_field_1",
        "form_field_2",
        css_id="my-fieldset-id",
        css_class="my-fieldset-class",
        data="my-data"
    )
The above layout will be rendered as::
    '''
    <fieldset id="fieldset-id" class="my-fieldset-class" data="my-data">
       <legend>Text for the legend</legend>
       # form fields render here
    </fieldset>
    '''
The first parameter is the text for the fieldset legend. This text is context aware,
so you can do things like::
    Fieldset("Data for {{ user.username }}",
        'form_field_1',
        'form_field_2'
    )
Definition at line 512 of file layout.py.
Constructor & Destructor Documentation
__init__()
crispy_forms.layout.Fieldset.__init__ (self, legend, * fields, css_class = None, css_id = None, template = None, ** kwargs)
Definition at line 570 of file layout.py.
    def __init__(self, legend, *fields, css_class=None, css_id=None, template=None, **kwargs):
        self.fields = list(fields)
        self.legend = legend
        self.css_class = css_class
        self.css_id = css_id
        self.template = template or self.template
        self.flat_attrs = flatatt(kwargs)
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
render()
crispy_forms.layout.Fieldset.render (self, form, context, template_pack = TEMPLATE_PACK, ** kwargs)
Definition at line 578 of file layout.py.
    def render(self, form, context, template_pack=TEMPLATE_PACK, **kwargs):
        fields = self.get_rendered_fields(form, context, template_pack, **kwargs)
        if self.legend:
            legend = Template(str(self.legend)).render(context)
        else:
            legend = SafeString("")
        template = self.get_template_name(template_pack)
        context.update({"fieldset": self, "legend": legend, "fields": fields})
        return render_to_string(template, context.flatten())
References crispy_forms.layout.LayoutObject.get_rendered_fields(), crispy_forms.layout.TemplateNameMixin.get_template_name(), legend, and render().
Referenced by pip._vendor.rich.progress.ProgressColumn.__call__(), pip._vendor.rich.layout.Layout.__rich_console__(), pip._vendor.rich.spinner.Spinner.__rich_console__(), pip._vendor.rich.spinner.Spinner.__rich_measure__(), django.forms.widgets.Media.__str__(), django.forms.utils.RenderableFieldMixin.as_field_group(), pip._vendor.rich.console.Console.log(), pip._vendor.rich.console.Console.print(), render(), django.templatetags.i18n.BlockTranslateNode.render(), pip._vendor.rich.console.Console.render(), pip._vendor.rich.console.Console.render_lines(), django.db.migrations.writer.OperationWriter.serialize(), and pip._vendor.rich.console.Console.update_screen_lines().
Member Data Documentation
css_class
crispy_forms.layout.Fieldset.css_class = css_class
Definition at line 573 of file layout.py.
Referenced by crispy_forms.layout.MultiField.render().
css_id
crispy_forms.layout.Fieldset.css_id = css_id
Definition at line 574 of file layout.py.
flat_attrs
crispy_forms.layout.Fieldset.flat_attrs = flatatt(kwargs)
Definition at line 576 of file layout.py.
legend
crispy_forms.layout.Fieldset.legend = legend
Definition at line 572 of file layout.py.
Referenced by render().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/crispy_forms/layout.py