Read&Watch: pip._vendor.typing_extensions._SpecialGenericAlias Class Reference
pip._vendor.typing_extensions._SpecialGenericAlias Class Reference
Public Member Functions
__init__ (self, origin, nparams, *, inst=True, name=None, defaults=())
__setattr__ (self, attr, val)
__getitem__ (self, params)
Protected Attributes
_nparams = nparams
_defaults = defaults
Detailed Description
Definition at line 431 of file typing_extensions.py.
Constructor & Destructor Documentation
__init__()
pip._vendor.typing_extensions._SpecialGenericAlias.__init__ (self, origin, nparams, * , inst = True, name = None, defaults = ())
Definition at line 432 of file typing_extensions.py.
        def __init__(self, origin, nparams, *, inst=True, name=None, defaults=()):
            if _special_generic_alias_base is typing._GenericAlias:
                # Python <3.9
                self.__origin__ = origin
                self._nparams = nparams
                super().__init__(origin, nparams, special=True, inst=inst, name=name)
            else:
                # Python >= 3.9
                super().__init__(origin, nparams, inst=inst, name=name)
            self._defaults = defaults
References __origin__.
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
__getitem__()
pip._vendor.typing_extensions._SpecialGenericAlias.__getitem__ (self, params)
Definition at line 454 of file typing_extensions.py.
        def __getitem__(self, params):
            if not isinstance(params, tuple):
                params = (params,)
            msg = "Parameters to generic types must be types."
            params = tuple(typing._type_check(p, msg) for p in params)
            if (
                self._defaults
                and len(params) < self._nparams
                and len(params) + len(self._defaults) >= self._nparams
            ):
                params = (*params, *self._defaults[len(params) - self._nparams:])
            actual_len = len(params)
            if actual_len != self._nparams:
                if self._defaults:
                    expected = f"at least {self._nparams - len(self._defaults)}"
                else:
                    expected = str(self._nparams)
                if not self._nparams:
                    raise TypeError(f"{self} is not a generic class")
                raise TypeError(
                    f"Too {'many' if actual_len > self._nparams else 'few'}"
                    f" arguments for {self};"
                    f" actual {actual_len}, expected {expected}"
                )
            return self.copy_with(params)
    _NoneType = type(None)
References _defaults, _nparams, and pip._vendor.typing_extensions._AnnotatedAlias.copy_with().
__setattr__()
pip._vendor.typing_extensions._SpecialGenericAlias.__setattr__ (self, attr, val)
Definition at line 443 of file typing_extensions.py.
        def __setattr__(self, attr, val):
            allowed_attrs = {'_name', '_inst', '_nparams', '_defaults'}
            if _special_generic_alias_base is typing._GenericAlias:
                # Python <3.9
                allowed_attrs.add("__origin__")
            if _is_dunder(attr) or attr in allowed_attrs:
                object.__setattr__(self, attr, val)
            else:
                setattr(self.__origin__, attr, val)
References __origin__, and pip._vendor.typing_extensions._is_dunder().
Member Data Documentation
_defaults
pip._vendor.typing_extensions._SpecialGenericAlias._defaults = defaults protected
Definition at line 441 of file typing_extensions.py.
Referenced by __getitem__().
_nparams
pip._vendor.typing_extensions._SpecialGenericAlias._nparams = nparams protected
Definition at line 436 of file typing_extensions.py.
Referenced by __getitem__().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/typing_extensions.py