Read&Watch: crispy_forms.layout.Layout Class Reference
crispy_forms.layout.Layout Class Reference
Public Member Functions
__init__ (self, *fields)
render (self, form, context, template_pack=TEMPLATE_PACK, **kwargs)
Public Member Functions inherited from crispy_forms.layout.LayoutObject
__getitem__ (self, slice)
__setitem__ (self, slice, value)
__delitem__ (self, slice)
__len__ (self)
__getattr__ (self, name)
get_field_names (self, index=None)
get_layout_objects (self, *LayoutClasses, index=None, max_level=0, greedy=False)
get_rendered_fields (self, form, context, template_pack=TEMPLATE_PACK, **kwargs)
Public Member Functions inherited from crispy_forms.layout.TemplateNameMixin
get_template_name (self, template_pack)
Additional Inherited Members
Public Attributes inherited from crispy_forms.layout.LayoutObject
fields
Public Attributes inherited from crispy_forms.layout.TemplateNameMixin
template
Detailed Description
Form Layout. It is conformed by Layout objects: `Fieldset`, `Row`, `Column`, `MultiField`,
`HTML`, `ButtonHolder`, `Button`, `Hidden`, `Reset`, `Submit` and fields. Form fields
have to be strings.
Layout objects `Fieldset`, `Row`, `Column`, `MultiField` and `ButtonHolder` can hold other
Layout objects within. Though `ButtonHolder` should only hold `HTML` and BaseInput
inherited classes: `Button`, `Hidden`, `Reset` and `Submit`.
Example::
    helper.layout = Layout(
        Fieldset('Company data',
            'is_company'
        ),
        Fieldset(_('Contact details'),
            'email',
            Row('password1', 'password2'),
            'first_name',
            'last_name',
            HTML('<img src="/media/somepicture.jpg"/>'),
            'company'
        ),
        ButtonHolder(
            Submit('Save', 'Save', css_class='button white'),
        ),
    )
Definition at line 109 of file layout.py.
Constructor & Destructor Documentation
__init__()
crispy_forms.layout.Layout.__init__ (self, * fields)
Definition at line 138 of file layout.py.
    def __init__(self, *fields):
        self.fields = list(fields)
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
render()
crispy_forms.layout.Layout.render (self, form, context, template_pack = TEMPLATE_PACK, ** kwargs)
Definition at line 141 of file layout.py.
    def render(self, form, context, template_pack=TEMPLATE_PACK, **kwargs):
        return self.get_rendered_fields(form, context, template_pack, **kwargs)
References crispy_forms.layout.LayoutObject.get_rendered_fields().
Referenced by pip._vendor.rich.progress.ProgressColumn.__call__(), pip._vendor.rich.layout.Layout.__rich_console__(), pip._vendor.rich.spinner.Spinner.__rich_console__(), pip._vendor.rich.spinner.Spinner.__rich_measure__(), django.forms.widgets.Media.__str__(), django.forms.utils.RenderableFieldMixin.as_field_group(), pip._vendor.rich.console.Console.log(), pip._vendor.rich.console.Console.print(), django.templatetags.i18n.BlockTranslateNode.render(), pip._vendor.rich.console.Console.render(), pip._vendor.rich.console.Console.render_lines(), django.db.migrations.writer.OperationWriter.serialize(), and pip._vendor.rich.console.Console.update_screen_lines().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/crispy_forms/layout.py