Read&Watch: pip._internal.index.package_finder.CandidateEvaluator Class Reference
pip._internal.index.package_finder.CandidateEvaluator Class Reference
Public Member Functions
"CandidateEvaluator" create (cls, str project_name, Optional[TargetPython] target_python=None, bool prefer_binary=False, bool allow_all_prereleases=False, Optional[specifiers.BaseSpecifier] specifier=None, Optional[Hashes] hashes=None)
None __init__ (self, str project_name, List[Tag] supported_tags, specifiers.BaseSpecifier specifier, bool prefer_binary=False, bool allow_all_prereleases=False, Optional[Hashes] hashes=None)
List[InstallationCandidate] get_applicable_candidates (self, List[InstallationCandidate] candidates)
Optional[InstallationCandidate] sort_best_candidate (self, List[InstallationCandidate] candidates)
BestCandidateResult compute_best_candidate (self, List[InstallationCandidate] candidates)
Protected Member Functions
CandidateSortingKey _sort_key (self, InstallationCandidate candidate)
Protected Attributes
_allow_all_prereleases = allow_all_prereleases
_hashes = hashes
_prefer_binary = prefer_binary
_project_name = project_name
_specifier = specifier
_supported_tags = supported_tags
dict _wheel_tag_preferences
Detailed Description
Responsible for filtering and sorting candidates for installation based
on what tags are valid.
Definition at line 377 of file package_finder.py.
Constructor & Destructor Documentation
__init__()
None pip._internal.index.package_finder.CandidateEvaluator.__init__ (self, str project_name, List[Tag] supported_tags, specifiers.BaseSpecifier specifier, bool prefer_binary = False, bool allow_all_prereleases = False, Optional[Hashes] hashes = None)
:param supported_tags: The PEP 425 tags supported by the target
    Python in order of preference (most preferred first).
Definition at line 419 of file package_finder.py.
    ) -> None:
        """
        :param supported_tags: The PEP 425 tags supported by the target
            Python in order of preference (most preferred first).
        """
        self._allow_all_prereleases = allow_all_prereleases
        self._hashes = hashes
        self._prefer_binary = prefer_binary
        self._project_name = project_name
        self._specifier = specifier
        self._supported_tags = supported_tags
        # Since the index of the tag in the _supported_tags list is used
        # as a priority, precompute a map from tag to index/priority to be
        # used in wheel.find_most_preferred_tag.
        self._wheel_tag_preferences = {
            tag: idx for idx, tag in enumerate(supported_tags)
        }
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
_sort_key()
CandidateSortingKey pip._internal.index.package_finder.CandidateEvaluator._sort_key (self, InstallationCandidate candidate) protected
Function to pass as the `key` argument to a call to sorted() to sort
InstallationCandidates by preference.
Returns a tuple such that tuples sorting as greater using Python's
default comparison operator are more preferred.
The preference is as follows:
First and foremost, candidates with allowed (matching) hashes are
always preferred over candidates without matching hashes. This is
because e.g. if the only candidate with an allowed hash is yanked,
we still want to use that candidate.
Second, excepting hash considerations, candidates that have been
yanked (in the sense of PEP 592) are always less preferred than
candidates that haven't been yanked. Then:
If not finding wheels, they are sorted by version only.
If finding wheels, then the sort order is by version, then:
  1. existing installs
  2. wheels ordered via Wheel.support_index_min(self._supported_tags)
  3. source archives
If prefer_binary was set, then all wheels are sorted above sources.
Note: it was considered to embed this logic into the Link
      comparison operators, but then different sdist links
      with the same version, would have to be considered equal
Definition at line 480 of file package_finder.py.
    def _sort_key(self, candidate: InstallationCandidate) -> CandidateSortingKey:
        """
        Function to pass as the `key` argument to a call to sorted() to sort
        InstallationCandidates by preference.
        Returns a tuple such that tuples sorting as greater using Python's
        default comparison operator are more preferred.
        The preference is as follows:
        First and foremost, candidates with allowed (matching) hashes are
        always preferred over candidates without matching hashes. This is
        because e.g. if the only candidate with an allowed hash is yanked,
        we still want to use that candidate.
        Second, excepting hash considerations, candidates that have been
        yanked (in the sense of PEP 592) are always less preferred than
        candidates that haven't been yanked. Then:
        If not finding wheels, they are sorted by version only.
        If finding wheels, then the sort order is by version, then:
          1. existing installs
          2. wheels ordered via Wheel.support_index_min(self._supported_tags)
          3. source archives
        If prefer_binary was set, then all wheels are sorted above sources.
        Note: it was considered to embed this logic into the Link
              comparison operators, but then different sdist links
              with the same version, would have to be considered equal
        """
        valid_tags = self._supported_tags
        support_num = len(valid_tags)
        build_tag: BuildTag = ()
        binary_preference = 0
        link = candidate.link
        if link.is_wheel:
            # can raise InvalidWheelFilename
            wheel = Wheel(link.filename)
            try:
                pri = -(
                    wheel.find_most_preferred_tag(
                        valid_tags, self._wheel_tag_preferences
                    )
                )
            except ValueError:
                raise UnsupportedWheel(
                    f"{wheel.filename} is not a supported wheel for this platform. It "
                    "can't be sorted."
                )
            if self._prefer_binary:
                binary_preference = 1
            if wheel.build_tag is not None:
                match = re.match(r"^(\d+)(.*)$", wheel.build_tag)
                assert match is not None, "guaranteed by filename validation"
                build_tag_groups = match.groups()
                build_tag = (int(build_tag_groups[0]), build_tag_groups[1])
        else:  # sdist
            pri = -(support_num)
        has_allowed_hash = int(link.is_hash_allowed(self._hashes))
        yank_value = -1 * int(link.is_yanked)  # -1 for yanked.
        return (
            has_allowed_hash,
            yank_value,
            binary_preference,
            candidate.version,
            pri,
            build_tag,
        )
References _hashes, _prefer_binary, _supported_tags, and _wheel_tag_preferences.
Referenced by get_applicable_candidates(), and sort_best_candidate().
compute_best_candidate()
BestCandidateResult pip._internal.index.package_finder.CandidateEvaluator.compute_best_candidate (self, List[InstallationCandidate] candidates)
Compute and return a `BestCandidateResult` instance.
Definition at line 562 of file package_finder.py.
    ) -> BestCandidateResult:
        """
        Compute and return a `BestCandidateResult` instance.
        """
        applicable_candidates = self.get_applicable_candidates(candidates)
        best_candidate = self.sort_best_candidate(applicable_candidates)
        return BestCandidateResult(
            candidates,
            applicable_candidates=applicable_candidates,
            best_candidate=best_candidate,
        )
References get_applicable_candidates(), and sort_best_candidate().
create()
"CandidateEvaluator" pip._internal.index.package_finder.CandidateEvaluator.create (cls, str project_name, Optional[TargetPython] target_python = None, bool prefer_binary = False, bool allow_all_prereleases = False, Optional[specifiers.BaseSpecifier] specifier = None, Optional[Hashes] hashes = None)
Create a CandidateEvaluator object.
:param target_python: The target Python interpreter to use when
    checking compatibility. If None (the default), a TargetPython
    object will be constructed from the running Python.
:param specifier: An optional object implementing `filter`
    (e.g. `packaging.specifiers.SpecifierSet`) to filter applicable
    versions.
:param hashes: An optional collection of allowed hashes.
Definition at line 384 of file package_finder.py.
    ) -> "CandidateEvaluator":
        """Create a CandidateEvaluator object.
        :param target_python: The target Python interpreter to use when
            checking compatibility. If None (the default), a TargetPython
            object will be constructed from the running Python.
        :param specifier: An optional object implementing `filter`
            (e.g. `packaging.specifiers.SpecifierSet`) to filter applicable
            versions.
        :param hashes: An optional collection of allowed hashes.
        """
        if target_python is None:
            target_python = TargetPython()
        if specifier is None:
            specifier = specifiers.SpecifierSet()
        supported_tags = target_python.get_sorted_tags()
        return cls(
            project_name=project_name,
            supported_tags=supported_tags,
            specifier=specifier,
            prefer_binary=prefer_binary,
            allow_all_prereleases=allow_all_prereleases,
            hashes=hashes,
        )
get_applicable_candidates()
List[InstallationCandidate] pip._internal.index.package_finder.CandidateEvaluator.get_applicable_candidates (self, List[InstallationCandidate] candidates)
Return the applicable candidates from a list of candidates.
Definition at line 445 of file package_finder.py.
    ) -> List[InstallationCandidate]:
        """
        Return the applicable candidates from a list of candidates.
        """
        # Using None infers from the specifier instead.
        allow_prereleases = self._allow_all_prereleases or None
        specifier = self._specifier
        # We turn the version object into a str here because otherwise
        # when we're debundled but setuptools isn't, Python will see
        # packaging.version.Version and
        # pkg_resources._vendor.packaging.version.Version as different
        # types. This way we'll use a str as a common data interchange
        # format. If we stop using the pkg_resources provided specifier
        # and start using our own, we can drop the cast to str().
        candidates_and_versions = [(c, str(c.version)) for c in candidates]
        versions = set(
            specifier.filter(
                (v for _, v in candidates_and_versions),
                prereleases=allow_prereleases,
            )
        )
        applicable_candidates = [c for c, v in candidates_and_versions if v in versions]
        filtered_applicable_candidates = filter_unallowed_hashes(
            candidates=applicable_candidates,
            hashes=self._hashes,
            project_name=self._project_name,
        )
        return sorted(filtered_applicable_candidates, key=self._sort_key)
References _allow_all_prereleases, _hashes, _project_name, _sort_key(), _specifier, and pip._internal.index.package_finder.filter_unallowed_hashes().
Referenced by compute_best_candidate().
sort_best_candidate()
Optional[InstallationCandidate] pip._internal.index.package_finder.CandidateEvaluator.sort_best_candidate (self, List[InstallationCandidate] candidates)
Return the best candidate per the instance's sort order, or None if
no candidate is acceptable.
Definition at line 549 of file package_finder.py.
    ) -> Optional[InstallationCandidate]:
        """
        Return the best candidate per the instance's sort order, or None if
        no candidate is acceptable.
        """
        if not candidates:
            return None
        best_candidate = max(candidates, key=self._sort_key)
        return best_candidate
References _sort_key().
Referenced by compute_best_candidate().
Member Data Documentation
_allow_all_prereleases
pip._internal.index.package_finder.CandidateEvaluator._allow_all_prereleases = allow_all_prereleases protected
Definition at line 432 of file package_finder.py.
Referenced by get_applicable_candidates().
_hashes
pip._internal.index.package_finder.CandidateEvaluator._hashes = hashes protected
Definition at line 433 of file package_finder.py.
Referenced by _sort_key(), pip._internal.models.link.Link.as_hashes(), get_applicable_candidates(), pip._internal.models.link.Link.has_hash(), pip._internal.models.link.Link.hash(), pip._internal.models.link.Link.hash_name(), and pip._internal.models.link.Link.is_hash_allowed().
_prefer_binary
pip._internal.index.package_finder.CandidateEvaluator._prefer_binary = prefer_binary protected
Definition at line 434 of file package_finder.py.
Referenced by _sort_key().
_project_name
pip._internal.index.package_finder.CandidateEvaluator._project_name = project_name protected
Definition at line 435 of file package_finder.py.
Referenced by pip._internal.index.sources._FlatDirectorySource.file_links(), and get_applicable_candidates().
_specifier
pip._internal.index.package_finder.CandidateEvaluator._specifier = specifier protected
Definition at line 436 of file package_finder.py.
Referenced by get_applicable_candidates().
_supported_tags
pip._internal.index.package_finder.CandidateEvaluator._supported_tags = supported_tags protected
Definition at line 437 of file package_finder.py.
Referenced by _sort_key().
_wheel_tag_preferences
dict pip._internal.index.package_finder.CandidateEvaluator._wheel_tag_preferences protected
Initial value:
=  {
            tag: idx for idx, tag in enumerate(supported_tags)
        }
Definition at line 441 of file package_finder.py.
Referenced by _sort_key().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_internal/index/package_finder.py