Read&Watch: django.middleware.http.ConditionalGetMiddleware Class Reference
django.middleware.http.ConditionalGetMiddleware Class Reference
Public Member Functions
process_response (self, request, response)
needs_etag (self, response)
Public Member Functions inherited from django.utils.deprecation.MiddlewareMixin
__init__ (self, get_response)
__repr__ (self)
__call__ (self, request)
__acall__ (self, request)
Additional Inherited Members
Public Attributes inherited from django.utils.deprecation.MiddlewareMixin
get_response = get_response
async_mode = iscoroutinefunction(self.get_response)
Static Public Attributes inherited from django.utils.deprecation.MiddlewareMixin
bool sync_capable = True
bool async_capable = True
Detailed Description
Handle conditional GET operations. If the response has an ETag or
Last-Modified header and the request has If-None-Match or If-Modified-Since,
replace the response with HttpNotModified. Add an ETag header if needed.
Definition at line 6 of file http.py.
Member Function Documentation
needs_etag()
django.middleware.http.ConditionalGetMiddleware.needs_etag (self, response)
Return True if an ETag header should be added to response.
Definition at line 37 of file http.py.
    def needs_etag(self, response):
        """Return True if an ETag header should be added to response."""
        cache_control_headers = cc_delim_re.split(response.get("Cache-Control", ""))
        return all(header.lower() != "no-store" for header in cache_control_headers)
Referenced by process_response().
process_response()
django.middleware.http.ConditionalGetMiddleware.process_response (self, request, response)
Definition at line 13 of file http.py.
    def process_response(self, request, response):
        # It's too late to prevent an unsafe request with a 412 response, and
        # for a HEAD request, the response body is always empty so computing
        # an accurate ETag isn't possible.
        if request.method != "GET":
            return response
        if self.needs_etag(response) and not response.has_header("ETag"):
            set_response_etag(response)
        etag = response.get("ETag")
        last_modified = response.get("Last-Modified")
        last_modified = last_modified and parse_http_date_safe(last_modified)
        if etag or last_modified:
            return get_conditional_response(
                request,
                etag=etag,
                last_modified=last_modified,
                response=response,
            )
        return response
References needs_etag().
Referenced by django.utils.deprecation.MiddlewareMixin.__acall__(), django.utils.deprecation.MiddlewareMixin.__call__(), and pip._vendor.rich.prompt.PromptBase.__call__().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/middleware/http.py