Read&Watch: pylint.checkers.symilar.LineSetStartCouple Class Reference
pylint.checkers.symilar.LineSetStartCouple Class Reference
Public Member Functions
str __repr__ (self)
bool __eq__ (self, object other)
int __hash__ (self)
LineSetStartCouple increment (self, Index value)
Public Attributes
fst_lineset_index = other.fst_lineset_index
snd_lineset_index = other.snd_lineset_index
Detailed Description
Indices in both linesets that mark the beginning of successive lines.
Definition at line 175 of file symilar.py.
Member Function Documentation
__eq__()
bool pylint.checkers.symilar.LineSetStartCouple.__eq__ (self, object other)
Definition at line 186 of file symilar.py.
    def __eq__(self, other: object) -> bool:
        if not isinstance(other, LineSetStartCouple):
            return NotImplemented
        return (
            self.fst_lineset_index == other.fst_lineset_index
            and self.snd_lineset_index == other.snd_lineset_index
        )
Referenced by dotenv.variables.Atom.__ne__(), responses.BaseResponse.__ne__(), and urllib3._collections.HTTPHeaderDict.__ne__().
__hash__()
int pylint.checkers.symilar.LineSetStartCouple.__hash__ (self)
Definition at line 194 of file symilar.py.
    def __hash__(self) -> int:
        return hash(self.fst_lineset_index) + hash(self.snd_lineset_index)
References fst_lineset_index, and snd_lineset_index.
__repr__()
str pylint.checkers.symilar.LineSetStartCouple.__repr__ (self)
Definition at line 181 of file symilar.py.
    def __repr__(self) -> str:
        return (
            f"<LineSetStartCouple <{self.fst_lineset_index};{self.snd_lineset_index}>>"
        )
increment()
LineSetStartCouple pylint.checkers.symilar.LineSetStartCouple.increment (self, Index value)
Definition at line 197 of file symilar.py.
    def increment(self, value: Index) -> LineSetStartCouple:
        return LineSetStartCouple(
            Index(self.fst_lineset_index + value),
            Index(self.snd_lineset_index + value),
        )
References fst_lineset_index, pylint.checkers.symilar.Index, and snd_lineset_index.
Member Data Documentation
fst_lineset_index
pylint.checkers.symilar.LineSetStartCouple.fst_lineset_index = other.fst_lineset_index
Definition at line 190 of file symilar.py.
Referenced by __hash__(), and increment().
snd_lineset_index
pylint.checkers.symilar.LineSetStartCouple.snd_lineset_index = other.snd_lineset_index
Definition at line 191 of file symilar.py.
Referenced by __hash__(), and increment().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pylint/checkers/symilar.py