Read&Watch: django.core.cache.backends.db.DatabaseCache Class Reference
django.core.cache.backends.db.DatabaseCache Class Reference
Public Member Functions
get (self, key, default=None, version=None)
get_many (self, keys, version=None)
set (self, key, value, timeout=DEFAULT_TIMEOUT, version=None)
add (self, key, value, timeout=DEFAULT_TIMEOUT, version=None)
touch (self, key, timeout=DEFAULT_TIMEOUT, version=None)
delete (self, key, version=None)
delete_many (self, keys, version=None)
has_key (self, key, version=None)
clear (self)
Public Member Functions inherited from django.core.cache.backends.db.BaseDatabaseCache
__init__ (self, table, params)
Public Member Functions inherited from django.core.cache.backends.base.BaseCache
__init__ (self, params)
get_backend_timeout (self, timeout=DEFAULT_TIMEOUT)
make_key (self, key, version=None)
validate_key (self, key)
make_and_validate_key (self, key, version=None)
aadd (self, key, value, timeout=DEFAULT_TIMEOUT, version=None)
aget (self, key, default=None, version=None)
aset (self, key, value, timeout=DEFAULT_TIMEOUT, version=None)
atouch (self, key, timeout=DEFAULT_TIMEOUT, version=None)
adelete (self, key, version=None)
aget_many (self, keys, version=None)
get_or_set (self, key, default, timeout=DEFAULT_TIMEOUT, version=None)
aget_or_set (self, key, default, timeout=DEFAULT_TIMEOUT, version=None)
ahas_key (self, key, version=None)
incr (self, key, delta=1, version=None)
aincr (self, key, delta=1, version=None)
decr (self, key, delta=1, version=None)
adecr (self, key, delta=1, version=None)
__contains__ (self, key)
set_many (self, data, timeout=DEFAULT_TIMEOUT, version=None)
aset_many (self, data, timeout=DEFAULT_TIMEOUT, version=None)
adelete_many (self, keys, version=None)
aclear (self)
incr_version (self, key, delta=1, version=None)
aincr_version (self, key, delta=1, version=None)
decr_version (self, key, delta=1, version=None)
adecr_version (self, key, delta=1, version=None)
close (self, **kwargs)
aclose (self, **kwargs)
Static Public Attributes
pickle_protocol = pickle.HIGHEST_PROTOCOL
Protected Member Functions
_base_set (self, mode, key, value, timeout=DEFAULT_TIMEOUT)
_base_delete_many (self, keys)
_cull (self, db, cursor, now, num)
Additional Inherited Members
Public Attributes inherited from django.core.cache.backends.db.BaseDatabaseCache
cache_model_class = CacheEntry
Public Attributes inherited from django.core.cache.backends.base.BaseCache
default_timeout = timeout
key_prefix = params.get("KEY_PREFIX", "")
version = params.get("VERSION", 1)
key_func = get_key_func(params.get("KEY_FUNCTION"))
Protected Attributes inherited from django.core.cache.backends.db.BaseDatabaseCache
_table = table
Protected Attributes inherited from django.core.cache.backends.base.BaseCache
int _max_entries = int(max_entries)
int _cull_frequency = int(cull_frequency)
Static Protected Attributes inherited from django.core.cache.backends.base.BaseCache
_missing_key = object()
Detailed Description
Definition at line 42 of file db.py.
Member Function Documentation
_base_delete_many()
django.core.cache.backends.db.DatabaseCache._base_delete_many (self, keys) protected
Definition at line 213 of file db.py.
    def _base_delete_many(self, keys):
        if not keys:
            return False
        db = router.db_for_write(self.cache_model_class)
        connection = connections[db]
        quote_name = connection.ops.quote_name
        table = quote_name(self._table)
        with connection.cursor() as cursor:
            cursor.execute(
                "DELETE FROM %s WHERE %s IN (%s)"
                % (
                    table,
                    quote_name("cache_key"),
                    ", ".join(["%s"] * len(keys)),
                ),
                keys,
            )
            return bool(cursor.rowcount)
References django.core.cache.backends.db.BaseDatabaseCache._table, and django.core.cache.backends.db.BaseDatabaseCache.cache_model_class.
Referenced by delete(), delete_many(), and get_many().
_base_set()
django.core.cache.backends.db.DatabaseCache._base_set (self, mode, key, value, timeout = DEFAULT_TIMEOUT) protected
Definition at line 112 of file db.py.
    def _base_set(self, mode, key, value, timeout=DEFAULT_TIMEOUT):
        timeout = self.get_backend_timeout(timeout)
        db = router.db_for_write(self.cache_model_class)
        connection = connections[db]
        quote_name = connection.ops.quote_name
        table = quote_name(self._table)
        with connection.cursor() as cursor:
            cursor.execute("SELECT COUNT(*) FROM %s" % table)
            num = cursor.fetchone()[0]
            now = tz_now()
            now = now.replace(microsecond=0)
            if timeout is None:
                exp = datetime.max
            else:
                tz = timezone.utc if settings.USE_TZ else None
                exp = datetime.fromtimestamp(timeout, tz=tz)
            exp = exp.replace(microsecond=0)
            if num > self._max_entries:
                self._cull(db, cursor, now, num)
            pickled = pickle.dumps(value, self.pickle_protocol)
            # The DB column is expecting a string, so make sure the value is a
            # string, not bytes. Refs #19274.
            b64encoded = base64.b64encode(pickled).decode("latin1")
            try:
                # Note: typecasting for datetimes is needed by some 3rd party
                # database backends. All core backends work without typecasting,
                # so be careful about changes here - test suite will NOT pick
                # regressions.
                with transaction.atomic(using=db):
                    cursor.execute(
                        "SELECT %s, %s FROM %s WHERE %s = %%s"
                        % (
                            quote_name("cache_key"),
                            quote_name("expires"),
                            table,
                            quote_name("cache_key"),
                        ),
                        [key],
                    )
                    result = cursor.fetchone()
                    if result:
                        current_expires = result[1]
                        expression = models.Expression(
                            output_field=models.DateTimeField()
                        )
                        for converter in connection.ops.get_db_converters(
                            expression
                        ) + expression.get_db_converters(connection):
                            current_expires = converter(
                                current_expires, expression, connection
                            )
                    exp = connection.ops.adapt_datetimefield_value(exp)
                    if result and mode == "touch":
                        cursor.execute(
                            "UPDATE %s SET %s = %%s WHERE %s = %%s"
                            % (table, quote_name("expires"), quote_name("cache_key")),
                            [exp, key],
                        )
                    elif result and (
                        mode == "set" or (mode == "add" and current_expires < now)
                    ):
                        cursor.execute(
                            "UPDATE %s SET %s = %%s, %s = %%s WHERE %s = %%s"
                            % (
                                table,
                                quote_name("value"),
                                quote_name("expires"),
                                quote_name("cache_key"),
                            ),
                            [b64encoded, exp, key],
                        )
                    elif mode != "touch":
                        cursor.execute(
                            "INSERT INTO %s (%s, %s, %s) VALUES (%%s, %%s, %%s)"
                            % (
                                table,
                                quote_name("cache_key"),
                                quote_name("value"),
                                quote_name("expires"),
                            ),
                            [key, b64encoded, exp],
                        )
                    else:
                        return False  # touch failed.
            except DatabaseError:
                # To be threadsafe, updates/inserts are allowed to fail silently
                return False
            else:
                return True
References django.core.cache.backends.db.BaseDatabaseCache._table, django.core.cache.backends.db.BaseDatabaseCache.cache_model_class, and django.core.cache.backends.base.BaseCache.get_backend_timeout().
Referenced by add(), set(), and touch().
_cull()
django.core.cache.backends.db.DatabaseCache._cull (self, db, cursor, now, num) protected
Definition at line 256 of file db.py.
    def _cull(self, db, cursor, now, num):
        if self._cull_frequency == 0:
            self.clear()
        else:
            connection = connections[db]
            table = connection.ops.quote_name(self._table)
            cursor.execute(
                "DELETE FROM %s WHERE %s < %%s"
                % (
                    table,
                    connection.ops.quote_name("expires"),
                ),
                [connection.ops.adapt_datetimefield_value(now)],
            )
            deleted_count = cursor.rowcount
            remaining_num = num - deleted_count
            if remaining_num > self._max_entries:
                cull_num = remaining_num // self._cull_frequency
                cursor.execute(
                    connection.ops.cache_key_culling_sql() % table, [cull_num]
                )
                last_cache_key = cursor.fetchone()
                if last_cache_key:
                    cursor.execute(
                        "DELETE FROM %s WHERE %s < %%s"
                        % (
                            table,
                            connection.ops.quote_name("cache_key"),
                        ),
                        [last_cache_key[0]],
                    )
Referenced by django.core.cache.backends.locmem.LocMemCache._set(), and django.core.cache.backends.filebased.FileBasedCache.set().
add()
django.core.cache.backends.db.DatabaseCache.add (self, key, value, timeout = DEFAULT_TIMEOUT, version = None)
Reimplemented from django.core.cache.backends.base.BaseCache.
Definition at line 104 of file db.py.
    def add(self, key, value, timeout=DEFAULT_TIMEOUT, version=None):
        key = self.make_and_validate_key(key, version=version)
        return self._base_set("add", key, value, timeout)
References _base_set(), and django.core.cache.backends.base.BaseCache.make_and_validate_key().
Referenced by responses.RequestsMock._add_from_file(), pip._internal.req.req_uninstall.UninstallPathSet.add(), pip._vendor.distlib.manifest.Manifest.add_many(), django.db.models.deletion.Collector.collect(), pip._vendor.urllib3._collections.HTTPHeaderDict.extend(), urllib3._collections.HTTPHeaderDict.extend(), pip._internal.operations.build.build_tracker.BuildTracker.track(), and responses.RequestsMock.upsert().
clear()
django.core.cache.backends.db.DatabaseCache.clear (self)
Reimplemented from django.core.cache.backends.base.BaseCache.
Definition at line 288 of file db.py.
    def clear(self):
        db = router.db_for_write(self.cache_model_class)
        connection = connections[db]
        table = connection.ops.quote_name(self._table)
        with connection.cursor() as cursor:
            cursor.execute("DELETE FROM %s" % table)
References django.core.cache.backends.db.BaseDatabaseCache._table, and django.core.cache.backends.db.BaseDatabaseCache.cache_model_class.
Referenced by pip._vendor.urllib3.poolmanager.PoolManager.__exit__(), urllib3.poolmanager.PoolManager.__exit__(), django.contrib.sessions.backends.cached_db.SessionStore.aflush(), and django.contrib.sessions.backends.cached_db.SessionStore.flush().
delete()
django.core.cache.backends.db.DatabaseCache.delete (self, key, version = None)
Reimplemented from django.core.cache.backends.base.BaseCache.
Definition at line 205 of file db.py.
    def delete(self, key, version=None):
        key = self.make_and_validate_key(key, version=version)
        return self._base_delete_many([key])
References _base_delete_many(), and django.core.cache.backends.base.BaseCache.make_and_validate_key().
Referenced by django.contrib.staticfiles.storage.HashedFilesMixin._post_process(), and django.views.generic.edit.DeletionMixin.post().
delete_many()
django.core.cache.backends.db.DatabaseCache.delete_many (self, keys, version = None)
Delete a bunch of values in the cache at once. For certain backends
(memcached), this is much more efficient than calling delete() multiple
times.
Reimplemented from django.core.cache.backends.base.BaseCache.
Definition at line 209 of file db.py.
    def delete_many(self, keys, version=None):
        keys = [self.make_and_validate_key(key, version=version) for key in keys]
        self._base_delete_many(keys)
References _base_delete_many(), and django.core.cache.backends.base.BaseCache.make_and_validate_key().
get()
django.core.cache.backends.db.DatabaseCache.get (self, key, default = None, version = None)
Reimplemented from django.core.cache.backends.base.BaseCache.
Definition at line 51 of file db.py.
    def get(self, key, default=None, version=None):
        return self.get_many([key], version).get(key, default)
References django.core.cache.backends.base.BaseCache.get, and django.core.cache.backends.base.BaseCache.get_many().
Referenced by pip._vendor.distlib.metadata.LegacyMetadata.__getitem__(), pip._vendor.rich.layout.Layout.__getitem__(), django.test.client.ClientMixin._follow_redirect(), pip._vendor.distlib.metadata.LegacyMetadata.check(), django.views.generic.base.RedirectView.delete(), PIL.Image.Exif.get_ifd(), django.views.generic.base.RedirectView.head(), django.views.generic.base.RedirectView.options(), django.views.generic.base.RedirectView.patch(), django.views.generic.base.RedirectView.post(), django.views.generic.base.RedirectView.put(), and pip._vendor.distlib.metadata.LegacyMetadata.write_file().
get_many()
django.core.cache.backends.db.DatabaseCache.get_many (self, keys, version = None)
Fetch a bunch of keys from the cache. For certain backends (memcached,
pgsql) this can be *much* faster when fetching multiple values.
Return a dict mapping each key in keys to its value. If the given
key is missing, it will be missing from the response dict.
Reimplemented from django.core.cache.backends.base.BaseCache.
Definition at line 54 of file db.py.
    def get_many(self, keys, version=None):
        if not keys:
            return {}
        key_map = {
            self.make_and_validate_key(key, version=version): key for key in keys
        }
        db = router.db_for_read(self.cache_model_class)
        connection = connections[db]
        quote_name = connection.ops.quote_name
        table = quote_name(self._table)
        with connection.cursor() as cursor:
            cursor.execute(
                "SELECT %s, %s, %s FROM %s WHERE %s IN (%s)"
                % (
                    quote_name("cache_key"),
                    quote_name("value"),
                    quote_name("expires"),
                    table,
                    quote_name("cache_key"),
                    ", ".join(["%s"] * len(key_map)),
                ),
                list(key_map),
            )
            rows = cursor.fetchall()
        result = {}
        expired_keys = []
        expression = models.Expression(output_field=models.DateTimeField())
        converters = connection.ops.get_db_converters(
            expression
        ) + expression.get_db_converters(connection)
        for key, value, expires in rows:
            for converter in converters:
                expires = converter(expires, expression, connection)
            if expires < tz_now():
                expired_keys.append(key)
            else:
                value = connection.ops.process_clob(value)
                value = pickle.loads(base64.b64decode(value.encode()))
                result[key_map.get(key)] = value
        self._base_delete_many(expired_keys)
        return result
References _base_delete_many(), django.core.cache.backends.db.BaseDatabaseCache._table, django.core.cache.backends.db.BaseDatabaseCache.cache_model_class, and django.core.cache.backends.base.BaseCache.make_and_validate_key().
has_key()
django.core.cache.backends.db.DatabaseCache.has_key (self, key, version = None)
Return True if the key is in the cache and has not expired.
Reimplemented from django.core.cache.backends.base.BaseCache.
Definition at line 234 of file db.py.
    def has_key(self, key, version=None):
        key = self.make_and_validate_key(key, version=version)
        db = router.db_for_read(self.cache_model_class)
        connection = connections[db]
        quote_name = connection.ops.quote_name
        now = tz_now().replace(microsecond=0, tzinfo=None)
        with connection.cursor() as cursor:
            cursor.execute(
                "SELECT %s FROM %s WHERE %s = %%s and %s > %%s"
                % (
                    quote_name("cache_key"),
                    quote_name(self._table),
                    quote_name("cache_key"),
                    quote_name("expires"),
                ),
                [key, connection.ops.adapt_datetimefield_value(now)],
            )
            return cursor.fetchone() is not None
References django.core.cache.backends.db.BaseDatabaseCache.cache_model_class, and django.core.cache.backends.base.BaseCache.make_and_validate_key().
set()
django.core.cache.backends.db.DatabaseCache.set (self, key, value, timeout = DEFAULT_TIMEOUT, version = None)
Reimplemented from django.core.cache.backends.base.BaseCache.
Definition at line 100 of file db.py.
    def set(self, key, value, timeout=DEFAULT_TIMEOUT, version=None):
        key = self.make_and_validate_key(key, version=version)
        self._base_set("set", key, value, timeout)
References _base_set(), and django.core.cache.backends.base.BaseCache.make_and_validate_key().
Referenced by pip._vendor.distlib.metadata.LegacyMetadata.__setitem__(), pip._vendor.requests.cookies.RequestsCookieJar.__setitem__(), requests.cookies.RequestsCookieJar.__setitem__(), pip._vendor.tomli._parser.Flags.finalize_pending(), pip._vendor.distlib.metadata.LegacyMetadata.read_file(), and pip._vendor.distlib.metadata.LegacyMetadata.update().
touch()
django.core.cache.backends.db.DatabaseCache.touch (self, key, timeout = DEFAULT_TIMEOUT, version = None)
Reimplemented from django.core.cache.backends.base.BaseCache.
Definition at line 108 of file db.py.
    def touch(self, key, timeout=DEFAULT_TIMEOUT, version=None):
        key = self.make_and_validate_key(key, version=version)
        return self._base_set("touch", key, None, timeout)
References _base_set(), and django.core.cache.backends.base.BaseCache.make_and_validate_key().
Member Data Documentation
pickle_protocol
django.core.cache.backends.db.DatabaseCache.pickle_protocol = pickle.HIGHEST_PROTOCOL static
Definition at line 49 of file db.py.
Referenced by django.core.cache.backends.filebased.FileBasedCache._write_content(), django.core.cache.backends.locmem.LocMemCache.add(), django.core.cache.backends.locmem.LocMemCache.incr(), and django.core.cache.backends.locmem.LocMemCache.set().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/core/cache/backends/db.py