Read&Watch: django.contrib.gis.feeds.GeoFeedMixin Class Reference
django.contrib.gis.feeds.GeoFeedMixin Class Reference
Public Member Functions
georss_coords (self, coords)
add_georss_point (self, handler, coords, w3c_geo=False)
add_georss_element (self, handler, item, w3c_geo=False)
Detailed Description
This mixin provides the necessary routines for SyndicationFeed subclasses
to produce simple GeoRSS or W3C Geo elements.
Definition at line 5 of file feeds.py.
Member Function Documentation
add_georss_element()
django.contrib.gis.feeds.GeoFeedMixin.add_georss_element (self, handler, item, w3c_geo = False)
Add a GeoRSS XML element using the given item and handler.
Definition at line 32 of file feeds.py.
    def add_georss_element(self, handler, item, w3c_geo=False):
        """Add a GeoRSS XML element using the given item and handler."""
        # Getting the Geometry object.
        geom = item.get("geometry")
        if geom is not None:
            if isinstance(geom, (list, tuple)):
                # Special case if a tuple/list was passed in.  The tuple may be
                # a point or a box
                box_coords = None
                if isinstance(geom[0], (list, tuple)):
                    # Box: ( (X0, Y0), (X1, Y1) )
                    if len(geom) == 2:
                        box_coords = geom
                    else:
                        raise ValueError("Only should be two sets of coordinates.")
                else:
                    if len(geom) == 2:
                        # Point: (X, Y)
                        self.add_georss_point(handler, geom, w3c_geo=w3c_geo)
                    elif len(geom) == 4:
                        # Box: (X0, Y0, X1, Y1)
                        box_coords = (geom[:2], geom[2:])
                    else:
                        raise ValueError("Only should be 2 or 4 numeric elements.")
                # If a GeoRSS box was given via tuple.
                if box_coords is not None:
                    if w3c_geo:
                        raise ValueError(
                            "Cannot use simple GeoRSS box in W3C Geo feeds."
                        )
                    handler.addQuickElement(
                        "georss:box", self.georss_coords(box_coords)
                    )
            else:
                # Getting the lowercase geometry type.
                gtype = str(geom.geom_type).lower()
                if gtype == "point":
                    self.add_georss_point(handler, geom.coords, w3c_geo=w3c_geo)
                else:
                    if w3c_geo:
                        raise ValueError("W3C Geo only supports Point geometries.")
                    # For formatting consistent w/the GeoRSS simple standard:
                    # http://georss.org/1.0#simple
                    if gtype in ("linestring", "linearring"):
                        handler.addQuickElement(
                            "georss:line", self.georss_coords(geom.coords)
                        )
                    elif gtype in ("polygon",):
                        # Only support the exterior ring.
                        handler.addQuickElement(
                            "georss:polygon", self.georss_coords(geom[0].coords)
                        )
                    else:
                        raise ValueError(
                            'Geometry type "%s" not supported.' % geom.geom_type
                        )
# ### SyndicationFeed subclasses ###
References add_georss_point(), and georss_coords().
Referenced by django.contrib.gis.feeds.GeoAtom1Feed.add_item_elements(), django.contrib.gis.feeds.GeoRSSFeed.add_item_elements(), and django.contrib.gis.feeds.W3CGeoFeed.add_item_elements().
add_georss_point()
django.contrib.gis.feeds.GeoFeedMixin.add_georss_point (self, handler, coords, w3c_geo = False)
Adds a GeoRSS point with the given coords using the given handler.
Handles the differences between simple GeoRSS and the more popular
W3C Geo specification.
Definition at line 19 of file feeds.py.
    def add_georss_point(self, handler, coords, w3c_geo=False):
        """
        Adds a GeoRSS point with the given coords using the given handler.
        Handles the differences between simple GeoRSS and the more popular
        W3C Geo specification.
        """
        if w3c_geo:
            lon, lat = coords[:2]
            handler.addQuickElement("geo:lat", "%f" % lat)
            handler.addQuickElement("geo:lon", "%f" % lon)
        else:
            handler.addQuickElement("georss:point", self.georss_coords((coords,)))
References georss_coords().
Referenced by add_georss_element().
georss_coords()
django.contrib.gis.feeds.GeoFeedMixin.georss_coords (self, coords)
In GeoRSS coordinate pairs are ordered by lat/lon and separated by
a single white space. Given a tuple of coordinates, return a string
GeoRSS representation.
Definition at line 11 of file feeds.py.
    def georss_coords(self, coords):
        """
        In GeoRSS coordinate pairs are ordered by lat/lon and separated by
        a single white space. Given a tuple of coordinates, return a string
        GeoRSS representation.
        """
        return " ".join("%f %f" % (coord[1], coord[0]) for coord in coords)
Referenced by add_georss_element(), and add_georss_point().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/gis/feeds.py