Read&Watch: isort.exceptions.FormattingPluginDoesNotExist Class Reference
isort.exceptions.FormattingPluginDoesNotExist Class Reference
Public Member Functions
__init__ (self, str formatter)
Public Member Functions inherited from isort.exceptions.ISortError
__reduce__ (self)
Public Attributes
formatter = formatter
Detailed Description
Raised when a formatting plugin is set by the user that doesn't exist
Definition at line 103 of file exceptions.py.
Constructor & Destructor Documentation
__init__()
isort.exceptions.FormattingPluginDoesNotExist.__init__ (self, str formatter)
Definition at line 106 of file exceptions.py.
    def __init__(self, formatter: str):
        super().__init__(f"Specified formatting plugin of {formatter} does not exist. ")
        self.formatter = formatter
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Data Documentation
formatter
isort.exceptions.FormattingPluginDoesNotExist.formatter = formatter
Definition at line 108 of file exceptions.py.
Referenced by pip._vendor.rich.logging.RichHandler.render().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/isort/exceptions.py