Read&Watch: django.contrib.auth.middleware.LoginRequiredMiddleware Class Reference
django.contrib.auth.middleware.LoginRequiredMiddleware Class Reference
Public Member Functions
process_view (self, request, view_func, view_args, view_kwargs)
get_login_url (self, view_func)
get_redirect_field_name (self, view_func)
handle_no_permission (self, request, view_func)
Public Member Functions inherited from django.utils.deprecation.MiddlewareMixin
__init__ (self, get_response)
__repr__ (self)
__call__ (self, request)
__acall__ (self, request)
Static Public Attributes
redirect_field_name = REDIRECT_FIELD_NAME
Static Public Attributes inherited from django.utils.deprecation.MiddlewareMixin
bool sync_capable = True
bool async_capable = True
Additional Inherited Members
Public Attributes inherited from django.utils.deprecation.MiddlewareMixin
get_response = get_response
async_mode = iscoroutinefunction(self.get_response)
Detailed Description
Middleware that redirects all unauthenticated requests to a login page.
Views using the login_not_required decorator will not be redirected.
Definition at line 41 of file middleware.py.
Member Function Documentation
get_login_url()
django.contrib.auth.middleware.LoginRequiredMiddleware.get_login_url (self, view_func)
Definition at line 59 of file middleware.py.
    def get_login_url(self, view_func):
        login_url = getattr(view_func, "login_url", None) or settings.LOGIN_URL
        if not login_url:
            raise ImproperlyConfigured(
                "No login URL to redirect to. Define settings.LOGIN_URL or "
                "provide a login_url via the 'django.contrib.auth.decorators."
                "login_required' decorator."
            )
        return str(login_url)
Referenced by handle_no_permission(), and django.contrib.auth.mixins.AccessMixin.handle_no_permission().
get_redirect_field_name()
django.contrib.auth.middleware.LoginRequiredMiddleware.get_redirect_field_name (self, view_func)
Definition at line 69 of file middleware.py.
    def get_redirect_field_name(self, view_func):
        return getattr(view_func, "redirect_field_name", self.redirect_field_name)
References redirect_field_name.
Referenced by handle_no_permission(), and django.contrib.auth.mixins.AccessMixin.handle_no_permission().
handle_no_permission()
django.contrib.auth.middleware.LoginRequiredMiddleware.handle_no_permission (self, request, view_func)
Definition at line 72 of file middleware.py.
    def handle_no_permission(self, request, view_func):
        path = request.build_absolute_uri()
        resolved_login_url = resolve_url(self.get_login_url(view_func))
        # If the login url is the same scheme and net location then use the
        # path as the "next" url.
        login_scheme, login_netloc = urlparse(resolved_login_url)[:2]
        current_scheme, current_netloc = urlparse(path)[:2]
        if (not login_scheme or login_scheme == current_scheme) and (
            not login_netloc or login_netloc == current_netloc
        ):
            path = request.get_full_path()
        return redirect_to_login(
            path,
            resolved_login_url,
            self.get_redirect_field_name(view_func),
        )
References get_login_url(), and get_redirect_field_name().
Referenced by django.contrib.auth.mixins.LoginRequiredMixin.dispatch(), django.contrib.auth.mixins.PermissionRequiredMixin.dispatch(), django.contrib.auth.mixins.UserPassesTestMixin.dispatch(), and process_view().
process_view()
django.contrib.auth.middleware.LoginRequiredMiddleware.process_view (self, request, view_func, view_args, view_kwargs)
Definition at line 50 of file middleware.py.
    def process_view(self, request, view_func, view_args, view_kwargs):
        if request.user.is_authenticated:
            return None
        if not getattr(view_func, "login_required", True):
            return None
        return self.handle_no_permission(request, view_func)
References handle_no_permission().
Member Data Documentation
redirect_field_name
django.contrib.auth.middleware.LoginRequiredMiddleware.redirect_field_name = REDIRECT_FIELD_NAME static
Definition at line 48 of file middleware.py.
Referenced by get_redirect_field_name(), django.contrib.auth.mixins.AccessMixin.get_redirect_field_name(), and django.contrib.auth.views.RedirectURLMixin.get_redirect_url().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/auth/middleware.py