Read&Watch: pip._internal.operations.install.wheel.MissingCallableSuffix Class Reference
pip._internal.operations.install.wheel.MissingCallableSuffix Class Reference
Public Member Functions
None __init__ (self, str entry_point)
Detailed Description
Definition at line 398 of file wheel.py.
Constructor & Destructor Documentation
__init__()
None pip._internal.operations.install.wheel.MissingCallableSuffix.__init__ (self, str entry_point)
Definition at line 399 of file wheel.py.
    def __init__(self, entry_point: str) -> None:
        super().__init__(
            f"Invalid script entry point: {entry_point} - A callable "
            "suffix is required. Cf https://packaging.python.org/"
            "specifications/entry-points/#use-for-scripts for more "
            "information."
        )
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_internal/operations/install/wheel.py