Read&Watch: django.contrib.gis.geos.geometry.GEOSGeometry Class Reference
django.contrib.gis.geos.geometry.GEOSGeometry Class Reference
Public Member Functions
__init__ (self, geo_input, srid=None)
Public Member Functions inherited from django.contrib.gis.geos.geometry.GEOSGeometryBase
__init__ (self, ptr, cls)
__copy__ (self)
__deepcopy__ (self, memodict)
__str__ (self)
__repr__ (self)
__getstate__ (self)
__setstate__ (self, state)
from_gml (cls, gml_string)
__eq__ (self, other)
__hash__ (self)
__or__ (self, other)
__and__ (self, other)
__sub__ (self, other)
__xor__ (self, other)
coord_seq (self)
geom_type (self)
geom_typeid (self)
num_geom (self)
num_coords (self)
num_points (self)
dims (self)
normalize (self, clone=False)
make_valid (self)
empty (self)
hasz (self)
ring (self)
simple (self)
valid (self)
valid_reason (self)
contains (self, other)
covers (self, other)
crosses (self, other)
disjoint (self, other)
equals (self, other)
equals_exact (self, other, tolerance=0)
equals_identical (self, other)
intersects (self, other)
overlaps (self, other)
relate_pattern (self, other, pattern)
touches (self, other)
within (self, other)
srid (self)
srid (self, srid)
ewkt (self)
wkt (self)
hex (self)
hexewkb (self)
json (self)
wkb (self)
ewkb (self)
kml (self)
prepared (self)
ogr (self)
srs (self)
crs (self)
transform (self, ct, clone=False)
boundary (self)
buffer (self, width, quadsegs=8)
buffer_with_style (self, width, quadsegs=8, end_cap_style=1, join_style=1, mitre_limit=5.0)
centroid (self)
convex_hull (self)
difference (self, other)
envelope (self)
intersection (self, other)
point_on_surface (self)
relate (self, other)
simplify (self, tolerance=0.0, preserve_topology=False)
sym_difference (self, other)
unary_union (self)
union (self, other)
area (self)
distance (self, other)
extent (self)
length (self)
clone (self)
Public Member Functions inherited from django.contrib.gis.ptr.CPointerBase
ptr (self)
ptr (self, ptr)
__del__ (self)
Public Member Functions inherited from django.contrib.gis.geos.mutable_list.ListMixin
__init__ (self, *args, **kwargs)
__getitem__ (self, index)
__delitem__ (self, index)
__setitem__ (self, index, val)
__add__ (self, other)
__radd__ (self, other)
__iadd__ (self, other)
__mul__ (self, n)
__rmul__ (self, n)
__imul__ (self, n)
__eq__ (self, other)
__lt__ (self, other)
count (self, val)
index (self, val)
append (self, val)
extend (self, vals)
insert (self, index, val)
pop (self, index=-1)
remove (self, val)
reverse (self)
sort (self, key=None, reverse=False)
Additional Inherited Members
Static Public Member Functions inherited from django.contrib.gis.geos.geometry.GEOSGeometryBase
from_ewkt (ewkt)
Public Attributes inherited from django.contrib.gis.geos.geometry.GEOSGeometryBase
geom_type
wkb
srid = srid
wkt
srs
Public Attributes inherited from django.contrib.gis.ptr.CPointerBase
ptr
Static Public Attributes inherited from django.contrib.gis.geos.geometry.GEOSGeometryBase
bool has_cs = False
geojson = json
Static Public Attributes inherited from django.contrib.gis.ptr.CPointerBase
ptr_type = c_void_p
destructor = None
null_ptr_exception_class = AttributeError
Protected Member Functions inherited from django.contrib.gis.geos.geometry.GEOSGeometryBase
_post_init (self)
_to_pickle_wkb (self)
_from_pickle_wkb (self, wkb)
_from_wkb (cls, wkb)
_ogr_ptr (self)
_topology (self, gptr)
Protected Member Functions inherited from django.contrib.gis.geos.mutable_list.ListMixin
_rebuild (self, newLen, newItems)
_set_single_rebuild (self, index, value)
_checkindex (self, index)
_check_allowed (self, items)
_set_slice (self, index, values)
_assign_extended_slice_rebuild (self, start, stop, step, valueList)
_assign_extended_slice (self, start, stop, step, valueList)
_assign_simple_slice (self, start, stop, valueList)
Static Protected Member Functions inherited from django.contrib.gis.geos.geometry.GEOSGeometryBase
_from_wkt (wkt)
Protected Attributes inherited from django.contrib.gis.geos.geometry.GEOSGeometryBase
tuple _cs
Protected Attributes inherited from django.contrib.gis.geos.mutable_list.ListMixin
_get_single_internal = self._get_single_external
_set_single = self._set_single_rebuild
_assign_extended_slice = self._assign_extended_slice_rebuild
_allowed
Static Protected Attributes inherited from django.contrib.gis.geos.geometry.GEOSGeometryBase
_GEOS_CLASSES = None
Static Protected Attributes inherited from django.contrib.gis.ptr.CPointerBase
_ptr = None
Static Protected Attributes inherited from django.contrib.gis.geos.mutable_list.ListMixin
int _minlength = 0
_maxlength = None
Detailed Description
Definition at line 720 of file geometry.py.
Constructor & Destructor Documentation
__init__()
django.contrib.gis.geos.geometry.GEOSGeometry.__init__ (self, geo_input, srid = None)
The base constructor for GEOS geometry objects. It may take the
following inputs:
 * strings:
    - WKT
    - HEXEWKB (a PostGIS-specific canonical form)
    - GeoJSON (requires GDAL)
 * memoryview:
    - WKB
The `srid` keyword specifies the Source Reference Identifier (SRID)
number for this Geometry. If not provided, it defaults to None.
Definition at line 723 of file geometry.py.
    def __init__(self, geo_input, srid=None):
        """
        The base constructor for GEOS geometry objects. It may take the
        following inputs:
         * strings:
            - WKT
            - HEXEWKB (a PostGIS-specific canonical form)
            - GeoJSON (requires GDAL)
         * memoryview:
            - WKB
        The `srid` keyword specifies the Source Reference Identifier (SRID)
        number for this Geometry. If not provided, it defaults to None.
        """
        input_srid = None
        if isinstance(geo_input, bytes):
            geo_input = force_str(geo_input)
        if isinstance(geo_input, str):
            wkt_m = wkt_regex.match(geo_input)
            if wkt_m:
                # Handle WKT input.
                if wkt_m["srid"]:
                    input_srid = int(wkt_m["srid"])
                g = self._from_wkt(force_bytes(wkt_m["wkt"]))
            elif hex_regex.match(geo_input):
                # Handle HEXEWKB input.
                g = wkb_r().read(force_bytes(geo_input))
            elif json_regex.match(geo_input):
                # Handle GeoJSON input.
                ogr = gdal.OGRGeometry.from_json(geo_input)
                g = ogr._geos_ptr()
                input_srid = ogr.srid
            else:
                raise ValueError("String input unrecognized as WKT EWKT, and HEXEWKB.")
        elif isinstance(geo_input, GEOM_PTR):
            # When the input is a pointer to a geometry (GEOM_PTR).
            g = geo_input
        elif isinstance(geo_input, memoryview):
            # When the input is a memoryview (WKB).
            g = wkb_r().read(geo_input)
        elif isinstance(geo_input, GEOSGeometry):
            g = capi.geom_clone(geo_input.ptr)
        else:
            raise TypeError("Improper geometry input type: %s" % type(geo_input))
        if not g:
            raise GEOSException("Could not initialize GEOS Geometry with given input.")
        input_srid = input_srid or capi.geos_get_srid(g) or None
        if input_srid and srid and input_srid != srid:
            raise ValueError("Input geometry already has SRID: %d." % input_srid)
        super().__init__(g, None)
        # Set the SRID, if given.
        srid = input_srid or srid
        if srid and isinstance(srid, int):
            self.srid = srid
References __init__(), and django.contrib.gis.geos.geometry.GEOSGeometryBase._from_wkt().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/gis/geos/geometry.py