Read&Watch: django.contrib.admin.tests.CSPMiddleware Class Reference
django.contrib.admin.tests.CSPMiddleware Class Reference
Public Member Functions
process_response (self, request, response)
Public Member Functions inherited from django.utils.deprecation.MiddlewareMixin
__init__ (self, get_response)
__repr__ (self)
__call__ (self, request)
__acall__ (self, request)
Additional Inherited Members
Public Attributes inherited from django.utils.deprecation.MiddlewareMixin
get_response = get_response
async_mode = iscoroutinefunction(self.get_response)
Static Public Attributes inherited from django.utils.deprecation.MiddlewareMixin
bool sync_capable = True
bool async_capable = True
Detailed Description
The admin's JavaScript should be compatible with CSP.
Definition at line 10 of file tests.py.
Member Function Documentation
process_response()
django.contrib.admin.tests.CSPMiddleware.process_response (self, request, response)
Definition at line 13 of file tests.py.
    def process_response(self, request, response):
        response.headers["Content-Security-Policy"] = "default-src 'self'"
        return response
@modify_settings(MIDDLEWARE={"append": "django.contrib.admin.tests.CSPMiddleware"})
Referenced by django.utils.deprecation.MiddlewareMixin.__acall__(), django.utils.deprecation.MiddlewareMixin.__call__(), and pip._vendor.rich.prompt.PromptBase.__call__().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/admin/tests.py