Read&Watch: colorama.tests.initialise_test.JustFixWindowsConsoleTest Class Reference
colorama.tests.initialise_test.JustFixWindowsConsoleTest Class Reference
Public Member Functions
tearDown (self)
testJustFixWindowsConsole (self)
Protected Member Functions
_reset (self)
Detailed Description
Definition at line 119 of file initialise_test.py.
Member Function Documentation
_reset()
colorama.tests.initialise_test.JustFixWindowsConsoleTest._reset (self) protected
Definition at line 120 of file initialise_test.py.
    def _reset(self):
        _wipe_internal_state_for_tests()
        sys.stdout = orig_stdout
        sys.stderr = orig_stderr
Referenced by sqlparse.engine.statement_splitter.StatementSplitter.__init__(), PIL.WebPImagePlugin.WebPImageFile._get_next(), PIL.WebPImagePlugin.WebPImageFile._seek(), sqlparse.engine.statement_splitter.StatementSplitter.process(), tearDown(), and testJustFixWindowsConsole().
tearDown()
colorama.tests.initialise_test.JustFixWindowsConsoleTest.tearDown (self)
Definition at line 125 of file initialise_test.py.
    def tearDown(self):
        self._reset()
References _reset().
testJustFixWindowsConsole()
colorama.tests.initialise_test.JustFixWindowsConsoleTest.testJustFixWindowsConsole (self)
Definition at line 129 of file initialise_test.py.
    def testJustFixWindowsConsole(self):
        if sys.platform != "win32":
            # just_fix_windows_console should be a no-op
            just_fix_windows_console()
            self.assertIs(sys.stdout, orig_stdout)
            self.assertIs(sys.stderr, orig_stderr)
        else:
            def fake_std():
                # Emulate stdout=not a tty, stderr=tty
                # to check that we handle both cases correctly
                stdout = Mock()
                stdout.closed = False
                stdout.isatty.return_value = False
                stdout.fileno.return_value = 1
                sys.stdout = stdout
                stderr = Mock()
                stderr.closed = False
                stderr.isatty.return_value = True
                stderr.fileno.return_value = 2
                sys.stderr = stderr
            for native_ansi in [False, True]:
                with patch(
                    'colorama.ansitowin32.enable_vt_processing',
                    lambda *_: native_ansi
                ):
                    self._reset()
                    fake_std()
                    # Regular single-call test
                    prev_stdout = sys.stdout
                    prev_stderr = sys.stderr
                    just_fix_windows_console()
                    self.assertIs(sys.stdout, prev_stdout)
                    if native_ansi:
                        self.assertIs(sys.stderr, prev_stderr)
                    else:
                        self.assertIsNot(sys.stderr, prev_stderr)
                    # second call without resetting is always a no-op
                    prev_stdout = sys.stdout
                    prev_stderr = sys.stderr
                    just_fix_windows_console()
                    self.assertIs(sys.stdout, prev_stdout)
                    self.assertIs(sys.stderr, prev_stderr)
                    self._reset()
                    fake_std()
                    # If init() runs first, just_fix_windows_console should be a no-op
                    init()
                    prev_stdout = sys.stdout
                    prev_stderr = sys.stderr
                    just_fix_windows_console()
                    self.assertIs(prev_stdout, sys.stdout)
                    self.assertIs(prev_stderr, sys.stderr)
References _reset().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/colorama/tests/initialise_test.py