Read&Watch: pip._internal.commands.debug.DebugCommand Class Reference
pip._internal.commands.debug.DebugCommand Class Reference
Public Member Functions
None add_options (self)
int run (self, Values options, List[str] args)
Public Member Functions inherited from pip._internal.cli.base_command.Command
None __init__ (self, str name, str summary, bool isolated=False)
None handle_pip_version_check (self, Values options)
Tuple[Values, List[str]] parse_args (self, List[str] args)
int main (self, List[str] args)
Public Member Functions inherited from pip._internal.cli.command_context.CommandContextMixIn
None __init__ (self)
Generator[None, None, None] main_context (self)
_T enter_context (self, ContextManager[_T] context_provider)
Additional Inherited Members
Public Attributes inherited from pip._internal.cli.base_command.Command
name = name
summary = summary
parser
Optional[TempDirRegistry] tempdir_registry = None
cmd_opts = optparse.OptionGroup(self.parser, optgroup_name)
verbosity = options.verbose - options.quiet
Static Public Attributes inherited from pip._internal.cli.base_command.Command
str usage = ""
bool ignore_require_venv = False
Protected Member Functions inherited from pip._internal.cli.base_command.Command
int _run_wrapper (self, int level_number, Values options, List[str] args)
int _main (self, List[str] args)
Protected Attributes inherited from pip._internal.cli.command_context.CommandContextMixIn
bool _in_main_context = False
_main_context = ExitStack()
Detailed Description
Display debug information.
Definition at line 158 of file debug.py.
Member Function Documentation
add_options()
None pip._internal.commands.debug.DebugCommand.add_options (self)
Reimplemented from pip._internal.cli.base_command.Command.
Definition at line 167 of file debug.py.
    def add_options(self) -> None:
        cmdoptions.add_target_python_options(self.cmd_opts)
        self.parser.insert_option_group(0, self.cmd_opts)
        self.parser.config.load()
run()
int pip._internal.commands.debug.DebugCommand.run (self, Values options, List[str] args)
Reimplemented from pip._internal.cli.base_command.Command.
Definition at line 172 of file debug.py.
    def run(self, options: Values, args: List[str]) -> int:
        logger.warning(
            "This command is only meant for debugging. "
            "Do not use this with automation for parsing and getting these "
            "details, since the output and options of this command may "
            "change without notice."
        )
        show_value("pip version", get_pip_version())
        show_value("sys.version", sys.version)
        show_value("sys.executable", sys.executable)
        show_value("sys.getdefaultencoding", sys.getdefaultencoding())
        show_value("sys.getfilesystemencoding", sys.getfilesystemencoding())
        show_value(
            "locale.getpreferredencoding",
            locale.getpreferredencoding(),
        )
        show_value("sys.platform", sys.platform)
        show_sys_implementation()
        show_value("'cert' config value", ca_bundle_info(self.parser.config))
        show_value("REQUESTS_CA_BUNDLE", os.environ.get("REQUESTS_CA_BUNDLE"))
        show_value("CURL_CA_BUNDLE", os.environ.get("CURL_CA_BUNDLE"))
        show_value("pip._vendor.certifi.where()", where())
        show_value("pip._vendor.DEBUNDLED", pip._vendor.DEBUNDLED)
        show_vendor_versions()
        show_tags(options)
        return SUCCESS
References pip._internal.commands.debug.ca_bundle_info(), pip._internal.cli.base_command.Command.parser, pip._internal.commands.debug.show_sys_implementation(), pip._internal.commands.debug.show_tags(), pip._internal.commands.debug.show_value(), and pip._internal.commands.debug.show_vendor_versions().
Referenced by pylint.pyreverse.main.Run.__init__().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_internal/commands/debug.py