Read&Watch: django.core.mail.utils.CachedDnsName Class Reference
django.core.mail.utils.CachedDnsName Class Reference
Public Member Functions
__str__ (self)
get_fqdn (self)
Protected Attributes
_fqdn = punycode(socket.getfqdn())
Detailed Description
Definition at line 12 of file utils.py.
Member Function Documentation
__str__()
django.core.mail.utils.CachedDnsName.__str__ (self)
Definition at line 13 of file utils.py.
    def __str__(self):
        return self.get_fqdn()
References get_fqdn().
Referenced by PIL.PdfParser.IndirectReference.__bytes__().
get_fqdn()
django.core.mail.utils.CachedDnsName.get_fqdn (self)
Definition at line 16 of file utils.py.
    def get_fqdn(self):
        if not hasattr(self, "_fqdn"):
            self._fqdn = punycode(socket.getfqdn())
        return self._fqdn
Referenced by __str__().
Member Data Documentation
_fqdn
django.core.mail.utils.CachedDnsName._fqdn = punycode(socket.getfqdn()) protected
Definition at line 18 of file utils.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/core/mail/utils.py