Read&Watch: django.contrib.postgres.indexes.BTreeIndex Class Reference
django.contrib.postgres.indexes.BTreeIndex Class Reference
Public Member Functions
__init__ (self, *expressions, fillfactor=None, deduplicate_items=None, **kwargs)
deconstruct (self)
get_with_params (self)
Public Member Functions inherited from django.contrib.postgres.indexes.PostgresIndex
max_name_length (self)
create_sql (self, model, schema_editor, using="", **kwargs)
check_supported (self, schema_editor)
Public Member Functions inherited from django.db.models.indexes.Index
__init__ (self, *expressions, fields=(), name=None, db_tablespace=None, opclasses=(), condition=None, include=None)
contains_expressions (self)
remove_sql (self, model, schema_editor, **kwargs)
clone (self)
set_name_with_model (self, model)
__repr__ (self)
__eq__ (self, other)
Public Attributes
fillfactor = fillfactor
deduplicate_items = deduplicate_items
Public Attributes inherited from django.db.models.indexes.Index
fields = list(fields)
list fields_orders
str name = name or ""
db_tablespace = db_tablespace
opclasses = opclasses
condition = condition
include = tuple(include) if include else ()
expressions
Additional Inherited Members
Static Public Attributes inherited from django.db.models.indexes.Index
str suffix = "idx"
Protected Member Functions inherited from django.db.models.indexes.Index
_get_condition_sql (self, model, schema_editor)
Detailed Description
Definition at line 117 of file indexes.py.
Constructor & Destructor Documentation
__init__()
django.contrib.postgres.indexes.BTreeIndex.__init__ (self, * expressions, fillfactor = None, deduplicate_items = None, ** kwargs)
Definition at line 120 of file indexes.py.
    def __init__(self, *expressions, fillfactor=None, deduplicate_items=None, **kwargs):
        self.fillfactor = fillfactor
        self.deduplicate_items = deduplicate_items
        super().__init__(*expressions, **kwargs)
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
deconstruct()
django.contrib.postgres.indexes.BTreeIndex.deconstruct (self)
Reimplemented from django.db.models.indexes.Index.
Definition at line 125 of file indexes.py.
    def deconstruct(self):
        path, args, kwargs = super().deconstruct()
        if self.fillfactor is not None:
            kwargs["fillfactor"] = self.fillfactor
        if self.deduplicate_items is not None:
            kwargs["deduplicate_items"] = self.deduplicate_items
        return path, args, kwargs
References deconstruct(), deduplicate_items, and fillfactor.
Referenced by django.db.models.indexes.Index.__eq__(), django.db.models.constraints.BaseConstraint.clone(), django.db.models.fields.Field.clone(), django.db.models.indexes.Index.clone(), deconstruct(), and django.db.models.query_utils.Q.identity().
get_with_params()
django.contrib.postgres.indexes.BTreeIndex.get_with_params (self)
Reimplemented from django.contrib.postgres.indexes.PostgresIndex.
Definition at line 133 of file indexes.py.
    def get_with_params(self):
        with_params = []
        if self.fillfactor is not None:
            with_params.append("fillfactor = %d" % self.fillfactor)
        if self.deduplicate_items is not None:
            with_params.append(
                "deduplicate_items = %s" % ("on" if self.deduplicate_items else "off")
            )
        return with_params
References deduplicate_items, and fillfactor.
Member Data Documentation
deduplicate_items
django.contrib.postgres.indexes.BTreeIndex.deduplicate_items = deduplicate_items
Definition at line 122 of file indexes.py.
Referenced by deconstruct(), and get_with_params().
fillfactor
django.contrib.postgres.indexes.BTreeIndex.fillfactor = fillfactor
Definition at line 121 of file indexes.py.
Referenced by deconstruct(), django.contrib.postgres.indexes.GistIndex.deconstruct(), django.contrib.postgres.indexes.HashIndex.deconstruct(), django.contrib.postgres.indexes.SpGistIndex.deconstruct(), get_with_params(), django.contrib.postgres.indexes.GistIndex.get_with_params(), django.contrib.postgres.indexes.HashIndex.get_with_params(), and django.contrib.postgres.indexes.SpGistIndex.get_with_params().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/postgres/indexes.py