Read&Watch: pip._internal.utils.misc.StreamWrapper Class Reference
pip._internal.utils.misc.StreamWrapper Class Reference
Public Member Functions
"StreamWrapper" from_stream (cls, TextIO orig_stream)
str encoding (self)
Detailed Description
Definition at line 377 of file misc.py.
Member Function Documentation
encoding()
str pip._internal.utils.misc.StreamWrapper.encoding (self)
Definition at line 389 of file misc.py.
    def encoding(self) -> str:  # type: ignore
        return self.orig_stream.encoding
# Simulates an enum
Referenced by pip._vendor.rich.console.ConsoleOptions.ascii_only(), yaml.scanner.Scanner.fetch_stream_start(), and pip._vendor.rich.console.Console.options().
from_stream()
"StreamWrapper" pip._internal.utils.misc.StreamWrapper.from_stream (cls, TextIO orig_stream)
Definition at line 381 of file misc.py.
    def from_stream(cls, orig_stream: TextIO) -> "StreamWrapper":
        ret = cls()
        ret.orig_stream = orig_stream
        return ret
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_internal/utils/misc.py