Read&Watch: apscheduler.jobstores.memory.MemoryJobStore Class Reference
apscheduler.jobstores.memory.MemoryJobStore Class Reference
Public Member Functions
__init__ (self)
lookup_job (self, job_id)
get_due_jobs (self, now)
get_next_run_time (self)
get_all_jobs (self)
add_job (self, job)
update_job (self, job)
remove_job (self, job_id)
remove_all_jobs (self)
shutdown (self)
Public Member Functions inherited from apscheduler.jobstores.base.BaseJobStore
start (self, scheduler, alias)
__repr__ (self)
Protected Member Functions
_get_job_index (self, timestamp, job_id)
Protected Member Functions inherited from apscheduler.jobstores.base.BaseJobStore
_fix_paused_jobs_sorting (self, jobs)
Protected Attributes
list _jobs = []
dict _jobs_index = {}
Additional Inherited Members
Static Protected Attributes inherited from apscheduler.jobstores.base.BaseJobStore
_scheduler = None
_alias = None
_logger = logging.getLogger("apscheduler.jobstores")
Detailed Description
Stores jobs in an array in RAM. Provides no persistence support.
Plugin alias: ``memory``
Definition at line 5 of file memory.py.
Constructor & Destructor Documentation
__init__()
apscheduler.jobstores.memory.MemoryJobStore.__init__ (self)
Definition at line 12 of file memory.py.
    def __init__(self):
        super().__init__()
        # list of (job, timestamp), sorted by next_run_time and job id (ascending)
        self._jobs = []
        self._jobs_index = {}  # id -> (job, timestamp) lookup table
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Function Documentation
_get_job_index()
apscheduler.jobstores.memory.MemoryJobStore._get_job_index (self, timestamp, job_id) protected
Returns the index of the given job, or if it's not found, the index where the job should be
inserted based on the given timestamp.
:type timestamp: int
:type job_id: str
Definition at line 80 of file memory.py.
    def _get_job_index(self, timestamp, job_id):
        """
        Returns the index of the given job, or if it's not found, the index where the job should be
        inserted based on the given timestamp.
        :type timestamp: int
        :type job_id: str
        """
        lo, hi = 0, len(self._jobs)
        timestamp = float("inf") if timestamp is None else timestamp
        while lo < hi:
            mid = (lo + hi) // 2
            mid_job, mid_timestamp = self._jobs[mid]
            mid_timestamp = float("inf") if mid_timestamp is None else mid_timestamp
            if mid_timestamp > timestamp:
                hi = mid
            elif mid_timestamp < timestamp:
                lo = mid + 1
            elif mid_job.id > job_id:
                hi = mid
            elif mid_job.id < job_id:
                lo = mid + 1
            else:
                return mid
        return lo
References _jobs.
Referenced by add_job(), remove_job(), and update_job().
add_job()
apscheduler.jobstores.memory.MemoryJobStore.add_job (self, job)
Adds the given job to this store.
:param Job job: the job to add
:raises ConflictingIdError: if there is another job in this store with the same ID
Reimplemented from apscheduler.jobstores.base.BaseJobStore.
Definition at line 37 of file memory.py.
    def add_job(self, job):
        if job.id in self._jobs_index:
            raise ConflictingIdError(job.id)
        timestamp = datetime_to_utc_timestamp(job.next_run_time)
        index = self._get_job_index(timestamp, job.id)
        self._jobs.insert(index, (job, timestamp))
        self._jobs_index[job.id] = (job, timestamp)
References _get_job_index(), _jobs, and _jobs_index.
Referenced by apscheduler.schedulers.base.BaseScheduler.scheduled_job().
get_all_jobs()
apscheduler.jobstores.memory.MemoryJobStore.get_all_jobs (self)
Returns a list of all jobs in this job store.
The returned jobs should be sorted by next run time (ascending).
Paused jobs (next_run_time == None) should be sorted last.
The job store is responsible for setting the ``scheduler`` and ``jobstore`` attributes of
the returned jobs to point to the scheduler and itself, respectively.
:rtype: list[Job]
Reimplemented from apscheduler.jobstores.base.BaseJobStore.
Definition at line 34 of file memory.py.
    def get_all_jobs(self):
        return [j[0] for j in self._jobs]
References _jobs.
get_due_jobs()
apscheduler.jobstores.memory.MemoryJobStore.get_due_jobs (self, now)
Returns the list of jobs that have ``next_run_time`` earlier or equal to ``now``.
The returned jobs must be sorted by next run time (ascending).
:param datetime.datetime now: the current (timezone aware) datetime
:rtype: list[Job]
Reimplemented from apscheduler.jobstores.base.BaseJobStore.
Definition at line 21 of file memory.py.
    def get_due_jobs(self, now):
        now_timestamp = datetime_to_utc_timestamp(now)
        pending = []
        for job, timestamp in self._jobs:
            if timestamp is None or timestamp > now_timestamp:
                break
            pending.append(job)
        return pending
References _jobs.
get_next_run_time()
apscheduler.jobstores.memory.MemoryJobStore.get_next_run_time (self)
Returns the earliest run time of all the jobs stored in this job store, or ``None`` if
there are no active jobs.
:rtype: datetime.datetime
Reimplemented from apscheduler.jobstores.base.BaseJobStore.
Definition at line 31 of file memory.py.
    def get_next_run_time(self):
        return self._jobs[0][0].next_run_time if self._jobs else None
References _jobs.
lookup_job()
apscheduler.jobstores.memory.MemoryJobStore.lookup_job (self, job_id)
Returns a specific job, or ``None`` if it isn't found..
The job store is responsible for setting the ``scheduler`` and ``jobstore`` attributes of
the returned job to point to the scheduler and itself, respectively.
:param str|unicode job_id: identifier of the job
:rtype: Job
Reimplemented from apscheduler.jobstores.base.BaseJobStore.
Definition at line 18 of file memory.py.
    def lookup_job(self, job_id):
        return self._jobs_index.get(job_id, (None, None))[0]
References _jobs_index.
remove_all_jobs()
apscheduler.jobstores.memory.MemoryJobStore.remove_all_jobs (self)
Removes all jobs from this store.
Reimplemented from apscheduler.jobstores.base.BaseJobStore.
Definition at line 73 of file memory.py.
    def remove_all_jobs(self):
        self._jobs = []
        self._jobs_index = {}
References _jobs, and _jobs_index.
remove_job()
apscheduler.jobstores.memory.MemoryJobStore.remove_job (self, job_id)
Removes the given job from this store.
:param str|unicode job_id: identifier of the job
:raises JobLookupError: if the job does not exist
Reimplemented from apscheduler.jobstores.base.BaseJobStore.
Definition at line 64 of file memory.py.
    def remove_job(self, job_id):
        job, timestamp = self._jobs_index.get(job_id, (None, None))
        if job is None:
            raise JobLookupError(job_id)
        index = self._get_job_index(timestamp, job_id)
        del self._jobs[index]
        del self._jobs_index[job.id]
References _get_job_index(), _jobs, and _jobs_index.
Referenced by apscheduler.schedulers.base.BaseScheduler._process_jobs(), and apscheduler.schedulers.base.BaseScheduler.resume_job().
shutdown()
apscheduler.jobstores.memory.MemoryJobStore.shutdown (self)
Frees any resources still bound to this job store.
Reimplemented from apscheduler.jobstores.base.BaseJobStore.
Definition at line 77 of file memory.py.
    def shutdown(self):
        self.remove_all_jobs()
References apscheduler.jobstores.base.BaseJobStore.remove_all_jobs().
update_job()
apscheduler.jobstores.memory.MemoryJobStore.update_job (self, job)
Replaces the job in the store with the given newer version.
:param Job job: the job to update
:raises JobLookupError: if the job does not exist
Reimplemented from apscheduler.jobstores.base.BaseJobStore.
Definition at line 46 of file memory.py.
    def update_job(self, job):
        old_job, old_timestamp = self._jobs_index.get(job.id, (None, None))
        if old_job is None:
            raise JobLookupError(job.id)
        # If the next run time has not changed, simply replace the job in its present index.
        # Otherwise, reinsert the job to the list to preserve the ordering.
        old_index = self._get_job_index(old_timestamp, old_job.id)
        new_timestamp = datetime_to_utc_timestamp(job.next_run_time)
        if old_timestamp == new_timestamp:
            self._jobs[old_index] = (job, new_timestamp)
        else:
            del self._jobs[old_index]
            new_index = self._get_job_index(new_timestamp, job.id)
            self._jobs.insert(new_index, (job, new_timestamp))
        self._jobs_index[old_job.id] = (job, new_timestamp)
References _get_job_index(), _jobs, and _jobs_index.
Member Data Documentation
_jobs
list apscheduler.jobstores.memory.MemoryJobStore._jobs = [] protected
Definition at line 15 of file memory.py.
Referenced by _get_job_index(), add_job(), get_all_jobs(), get_due_jobs(), get_next_run_time(), remove_all_jobs(), remove_job(), and update_job().
_jobs_index
dict apscheduler.jobstores.memory.MemoryJobStore._jobs_index = {} protected
Definition at line 16 of file memory.py.
Referenced by add_job(), lookup_job(), remove_all_jobs(), remove_job(), and update_job().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/apscheduler/jobstores/memory.py