Read&Watch: crispy_forms.bootstrap.Modal Class Reference
crispy_forms.bootstrap.Modal Class Reference
Public Member Functions
__init__ (self, *fields, template=None, css_id="modal_id", title="Modal Title", title_id="modal_title_id", css_class=None, title_class=None, **kwargs)
render (self, form, context, template_pack=TEMPLATE_PACK, **kwargs)
Public Member Functions inherited from crispy_forms.layout.LayoutObject
__getitem__ (self, slice)
__setitem__ (self, slice, value)
__delitem__ (self, slice)
__len__ (self)
__getattr__ (self, name)
get_field_names (self, index=None)
get_layout_objects (self, *LayoutClasses, index=None, max_level=0, greedy=False)
get_rendered_fields (self, form, context, template_pack=TEMPLATE_PACK, **kwargs)
Public Member Functions inherited from crispy_forms.layout.TemplateNameMixin
get_template_name (self, template_pack)
Public Attributes
css_id = css_id
str css_class = css_class or ""
title = title
title_id = title_id
str title_class = title_class or ""
flat_attrs = flatatt(kwargs)
Public Attributes inherited from crispy_forms.layout.LayoutObject
fields
Public Attributes inherited from crispy_forms.layout.TemplateNameMixin
template
Detailed Description
Boostrap layout object for rendering crispy forms objects inside a
bootstrap modal.
Attributes
----------
template : str
    The default template which this Layout Object will be rendered
    with.
Parameters
----------
*fields : str
    The fields to be rendered within the modal.
template : str, optional
    Overrides the default template, if provided. By default ``None``.
css_id: str, optional
    The modal's DOM id. By default ``modal_id``.
title: str, optional
    Text to display in the modal's header which will be wrapped in an
    ``<H5>`` tag. By default ``Modal Title``.
title_id: str, optional
    The title's DOM id. By default ``modal_title_id``.
css_class : str, optional
    CSS classes to be applied to the field. These are added to any classes
    included in the ``attrs`` dict. By default None.
title_class: str, optional
    Additional CSS classes to be applied to the title. By default None.
**kwargs : dict, optional
    Additional attributes are converted into key="value", pairs. These
    attributes are added to the ``<div>``.
Examples
--------
Example::
    Modal(
        'field1',
        Div('field2'),
        css_id="modal-id-ex",
        css_class="modal-class-ex,
        title="This is my modal",
    )
Definition at line 1055 of file bootstrap.py.
Constructor & Destructor Documentation
__init__()
crispy_forms.bootstrap.Modal.__init__ (self, * fields, template = None, css_id = "modal_id", title = "Modal Title", title_id = "modal_title_id", css_class = None, title_class = None, ** kwargs)
Definition at line 1104 of file bootstrap.py.
    ):
        self.fields = list(fields)
        self.template = template or self.template
        self.css_id = css_id
        self.css_class = css_class or ""
        self.title = title
        self.title_id = title_id
        self.title_class = title_class or ""
        kwargs = {**kwargs, "tabindex": "-1", "role": "dialog", "aria-labelledby": "%s-label" % self.title_id}
        self.flat_attrs = flatatt(kwargs)
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
render()
crispy_forms.bootstrap.Modal.render (self, form, context, template_pack = TEMPLATE_PACK, ** kwargs)
Definition at line 1127 of file bootstrap.py.
    def render(self, form, context, template_pack=TEMPLATE_PACK, **kwargs):
        fields = self.get_rendered_fields(form, context, template_pack, **kwargs)
        template = self.get_template_name(template_pack)
        return render_to_string(template, {"modal": self, "fields": fields})
References crispy_forms.layout.LayoutObject.get_rendered_fields(), and crispy_forms.layout.TemplateNameMixin.get_template_name().
Referenced by pip._vendor.rich.progress.ProgressColumn.__call__(), pip._vendor.rich.layout.Layout.__rich_console__(), pip._vendor.rich.spinner.Spinner.__rich_console__(), pip._vendor.rich.spinner.Spinner.__rich_measure__(), django.forms.widgets.Media.__str__(), django.forms.utils.RenderableFieldMixin.as_field_group(), pip._vendor.rich.console.Console.log(), pip._vendor.rich.console.Console.print(), django.templatetags.i18n.BlockTranslateNode.render(), pip._vendor.rich.console.Console.render(), pip._vendor.rich.console.Console.render_lines(), django.db.migrations.writer.OperationWriter.serialize(), and pip._vendor.rich.console.Console.update_screen_lines().
Member Data Documentation
css_class
str crispy_forms.bootstrap.Modal.css_class = css_class or ""
Definition at line 1118 of file bootstrap.py.
Referenced by crispy_forms.layout.MultiField.render().
css_id
crispy_forms.bootstrap.Modal.css_id = css_id
Definition at line 1117 of file bootstrap.py.
flat_attrs
crispy_forms.bootstrap.Modal.flat_attrs = flatatt(kwargs)
Definition at line 1125 of file bootstrap.py.
title
crispy_forms.bootstrap.Modal.title = title
Definition at line 1119 of file bootstrap.py.
Referenced by pip._vendor.rich._inspect.Inspect.__rich__(), pip._vendor.rich.columns.Columns.__rich_console__(), pip._vendor.rich.rule.Rule.__rich_console__(), pip._vendor.rich.table.Table.__rich_console__(), django.contrib.flatpages.models.FlatPage.__str__(), general.models.MediaItem.__str__(), pip._vendor.rich.panel.Panel._title(), pip._vendor.pygments.formatters.html.HtmlFormatter._wrap_full(), and pylint.pyreverse.dot_printer.DotPrinter.generate().
title_class
str crispy_forms.bootstrap.Modal.title_class = title_class or ""
Definition at line 1121 of file bootstrap.py.
title_id
crispy_forms.bootstrap.Modal.title_id = title_id
Definition at line 1120 of file bootstrap.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/crispy_forms/bootstrap.py