Read&Watch: apscheduler.triggers.date.DateTrigger Class Reference
apscheduler.triggers.date.DateTrigger Class Reference
Public Member Functions
__init__ (self, run_date=None, timezone=None)
get_next_fire_time (self, previous_fire_time, now)
__getstate__ (self)
__setstate__ (self, state)
__str__ (self)
__repr__ (self)
Public Attributes
run_date = convert_to_datetime(run_date, timezone, "run_date")
Additional Inherited Members
Protected Member Functions inherited from apscheduler.triggers.base.BaseTrigger
_apply_jitter (self, next_fire_time, jitter, now)
Detailed Description
Triggers once on the given datetime. If ``run_date`` is left empty, current time is used.
:param datetime|str run_date: the date/time to run the job at
:param datetime.tzinfo|str timezone: time zone for ``run_date`` if it doesn't have one already
Definition at line 9 of file date.py.
Constructor & Destructor Documentation
__init__()
apscheduler.triggers.date.DateTrigger.__init__ (self, run_date = None, timezone = None)
Definition at line 19 of file date.py.
    def __init__(self, run_date=None, timezone=None):
        timezone = astimezone(timezone) or get_localzone()
        if run_date is not None:
            self.run_date = convert_to_datetime(run_date, timezone, "run_date")
        else:
            self.run_date = datetime.now(timezone)
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
__getstate__()
apscheduler.triggers.date.DateTrigger.__getstate__ (self)
Definition at line 29 of file date.py.
    def __getstate__(self):
        return {"version": 1, "run_date": self.run_date}
References run_date.
Referenced by django.db.models.base.Model.__reduce__().
__repr__()
apscheduler.triggers.date.DateTrigger.__repr__ (self)
Definition at line 48 of file date.py.
    def __repr__(self):
        return (
            f"<{self.__class__.__name__} (run_date='{datetime_repr(self.run_date)}')>"
        )
__setstate__()
apscheduler.triggers.date.DateTrigger.__setstate__ (self, state)
Definition at line 32 of file date.py.
    def __setstate__(self, state):
        # This is for compatibility with APScheduler 3.0.x
        if isinstance(state, tuple):
            state = state[1]
        if state.get("version", 1) > 1:
            raise ValueError(
                f"Got serialized data for version {state['version']} of "
                f"{self.__class__.__name__}, but only version 1 can be handled"
            )
        self.run_date = state["run_date"]
References run_date.
__str__()
apscheduler.triggers.date.DateTrigger.__str__ (self)
Definition at line 45 of file date.py.
    def __str__(self):
        return f"date[{datetime_repr(self.run_date)}]"
Referenced by PIL.PdfParser.IndirectReference.__bytes__().
get_next_fire_time()
apscheduler.triggers.date.DateTrigger.get_next_fire_time (self, previous_fire_time, now)
Returns the next datetime to fire on, If no such datetime can be calculated, returns
``None``.
:param datetime.datetime previous_fire_time: the previous time the trigger was fired
:param datetime.datetime now: current datetime
Reimplemented from apscheduler.triggers.base.BaseTrigger.
Definition at line 26 of file date.py.
    def get_next_fire_time(self, previous_fire_time, now):
        return self.run_date if previous_fire_time is None else None
References run_date.
Member Data Documentation
run_date
apscheduler.triggers.date.DateTrigger.run_date = convert_to_datetime(run_date, timezone, "run_date")
Definition at line 22 of file date.py.
Referenced by __getstate__(), __setstate__(), and get_next_fire_time().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/apscheduler/triggers/date.py