Read&Watch: pylint.extensions._check_docs_utils.GoogleDocstring Class Reference
pylint.extensions._check_docs_utils.GoogleDocstring Class Reference
Public Member Functions
int matching_sections (self)
bool has_params (self)
bool has_returns (self)
bool has_rtype (self)
bool has_property_returns (self)
bool has_property_type (self)
bool has_yields (self)
bool has_yields_type (self)
set[str] exceptions (self)
tuple[set[str], set[str]] match_param_docs (self)
Public Member Functions inherited from pylint.extensions._check_docs_utils.Docstring
None __init__ (self, nodes.Const|None doc)
str __repr__ (self)
bool params_documented_elsewhere (self)
Static Public Member Functions
int min_section_indent (re.Match[str] section_match)
Static Public Attributes
re_type = SphinxDocstring.re_type
re_xref = SphinxDocstring.re_xref
str re_container_type
str re_multiple_type
re_param_section
re_keyword_param_section
re_param_line
re_raise_section
re_raise_line
re_returns_section
re_returns_line
re_property_returns_line
re_yields_section
re_yields_line = re_returns_line
Static Public Attributes inherited from pylint.extensions._check_docs_utils.Docstring
re_for_parameters_see
bool supports_yields = False
Protected Member Functions
str _first_line (self)
list[str] _parse_section (self, re.Pattern[str] section_re)
Static Protected Member Functions
bool _is_section_header (str _)
Static Protected Attributes
str _re_section_template
Additional Inherited Members
Public Attributes inherited from pylint.extensions._check_docs_utils.Docstring
doc = docstring.expandtabs()
Detailed Description
Definition at line 540 of file _check_docs_utils.py.
Member Function Documentation
_first_line()
str pylint.extensions._check_docs_utils.GoogleDocstring._first_line (self) protected
Definition at line 764 of file _check_docs_utils.py.
    def _first_line(self) -> str:
        return self.doc.lstrip().split("\n", 1)[0]
References pylint.extensions._check_docs_utils.Docstring.doc.
Referenced by has_property_returns(), and has_property_type().
_is_section_header()
bool pylint.extensions._check_docs_utils.GoogleDocstring._is_section_header (str _) static protected
Reimplemented in pylint.extensions._check_docs_utils.NumpyDocstring.
Definition at line 772 of file _check_docs_utils.py.
    def _is_section_header(_: str) -> bool:
        # Google parsing does not need to detect section headers,
        # because it works off of indentation level only
        return False
Referenced by _parse_section().
_parse_section()
list[str] pylint.extensions._check_docs_utils.GoogleDocstring._parse_section (self, re.Pattern[str] section_re) protected
Definition at line 777 of file _check_docs_utils.py.
    def _parse_section(self, section_re: re.Pattern[str]) -> list[str]:
        section_match = section_re.search(self.doc)
        if section_match is None:
            return []
        min_indentation = self.min_section_indent(section_match)
        entries: list[str] = []
        entry: list[str] = []
        is_first = True
        for line in section_match.group(2).splitlines():
            if not line.strip():
                continue
            indentation = space_indentation(line)
            if indentation < min_indentation:
                break
            # The first line after the header defines the minimum
            # indentation.
            if is_first:
                min_indentation = indentation
                is_first = False
            if indentation == min_indentation:
                if self._is_section_header(line):
                    break
                # Lines with minimum indentation must contain the beginning
                # of a new parameter documentation.
                if entry:
                    entries.append("\n".join(entry))
                    entry = []
            entry.append(line)
        if entry:
            entries.append("\n".join(entry))
        return entries
References _is_section_header(), pylint.extensions._check_docs_utils.Docstring.doc, min_section_indent(), and pylint.extensions._check_docs_utils.space_indentation().
Referenced by exceptions(), has_returns(), has_rtype(), has_yields(), has_yields_type(), match_param_docs(), and pylint.extensions._check_docs_utils.NumpyDocstring.match_param_docs().
exceptions()
set[str] pylint.extensions._check_docs_utils.GoogleDocstring.exceptions (self)
Reimplemented from pylint.extensions._check_docs_utils.Docstring.
Definition at line 722 of file _check_docs_utils.py.
    def exceptions(self) -> set[str]:
        types: set[str] = set()
        entries = self._parse_section(self.re_raise_section)
        for entry in entries:
            match = self.re_raise_line.match(entry)
            if not match:
                continue
            exc_type = match.group(1)
            exc_desc = match.group(2)
            if exc_desc:
                types.update(_split_multiple_exc_types(exc_type))
        return types
References _parse_section(), pylint.extensions._check_docs_utils._split_multiple_exc_types(), re_raise_line, and re_raise_section.
has_params()
bool pylint.extensions._check_docs_utils.GoogleDocstring.has_params (self)
Reimplemented from pylint.extensions._check_docs_utils.Docstring.
Definition at line 635 of file _check_docs_utils.py.
    def has_params(self) -> bool:
        if not self.doc:
            return False
        return self.re_param_section.search(self.doc) is not None
References pylint.extensions._check_docs_utils.Docstring.doc, and re_param_section.
has_property_returns()
bool pylint.extensions._check_docs_utils.GoogleDocstring.has_property_returns (self)
Reimplemented from pylint.extensions._check_docs_utils.Docstring.
Definition at line 673 of file _check_docs_utils.py.
    def has_property_returns(self) -> bool:
        # The summary line is the return doc,
        # so the first line must not be a known directive.
        first_line = self._first_line()
        return not bool(
            self.re_param_section.search(first_line)
            or self.re_raise_section.search(first_line)
            or self.re_returns_section.search(first_line)
            or self.re_yields_section.search(first_line)
        )
References _first_line(), re_param_section, re_raise_section, re_returns_section, and re_yields_section.
has_property_type()
bool pylint.extensions._check_docs_utils.GoogleDocstring.has_property_type (self)
Reimplemented from pylint.extensions._check_docs_utils.Docstring.
Definition at line 684 of file _check_docs_utils.py.
    def has_property_type(self) -> bool:
        if not self.doc:
            return False
        return bool(self.re_property_returns_line.match(self._first_line()))
References _first_line(), pylint.extensions._check_docs_utils.Docstring.doc, and re_property_returns_line.
has_returns()
bool pylint.extensions._check_docs_utils.GoogleDocstring.has_returns (self)
Reimplemented from pylint.extensions._check_docs_utils.Docstring.
Definition at line 641 of file _check_docs_utils.py.
    def has_returns(self) -> bool:
        if not self.doc:
            return False
        entries = self._parse_section(self.re_returns_section)
        for entry in entries:
            match = self.re_returns_line.match(entry)
            if not match:
                continue
            return_desc = match.group(2)
            if return_desc:
                return True
        return False
References _parse_section(), pylint.extensions._check_docs_utils.Docstring.doc, re_returns_line, and re_returns_section.
has_rtype()
bool pylint.extensions._check_docs_utils.GoogleDocstring.has_rtype (self)
Reimplemented from pylint.extensions._check_docs_utils.Docstring.
Definition at line 657 of file _check_docs_utils.py.
    def has_rtype(self) -> bool:
        if not self.doc:
            return False
        entries = self._parse_section(self.re_returns_section)
        for entry in entries:
            match = self.re_returns_line.match(entry)
            if not match:
                continue
            return_type = match.group(1)
            if return_type:
                return True
        return False
References _parse_section(), pylint.extensions._check_docs_utils.Docstring.doc, re_returns_line, and re_returns_section.
has_yields()
bool pylint.extensions._check_docs_utils.GoogleDocstring.has_yields (self)
Reimplemented from pylint.extensions._check_docs_utils.Docstring.
Definition at line 690 of file _check_docs_utils.py.
    def has_yields(self) -> bool:
        if not self.doc:
            return False
        entries = self._parse_section(self.re_yields_section)
        for entry in entries:
            match = self.re_yields_line.match(entry)
            if not match:
                continue
            yield_desc = match.group(2)
            if yield_desc:
                return True
        return False
References _parse_section(), pylint.extensions._check_docs_utils.Docstring.doc, re_yields_line, and re_yields_section.
has_yields_type()
bool pylint.extensions._check_docs_utils.GoogleDocstring.has_yields_type (self)
Reimplemented from pylint.extensions._check_docs_utils.Docstring.
Definition at line 706 of file _check_docs_utils.py.
    def has_yields_type(self) -> bool:
        if not self.doc:
            return False
        entries = self._parse_section(self.re_yields_section)
        for entry in entries:
            match = self.re_yields_line.match(entry)
            if not match:
                continue
            yield_type = match.group(1)
            if yield_type:
                return True
        return False
References _parse_section(), pylint.extensions._check_docs_utils.Docstring.doc, re_yields_line, and re_yields_section.
match_param_docs()
tuple[set[str], set[str]] pylint.extensions._check_docs_utils.GoogleDocstring.match_param_docs (self)
Reimplemented from pylint.extensions._check_docs_utils.Docstring.
Reimplemented in pylint.extensions._check_docs_utils.NumpyDocstring.
Definition at line 738 of file _check_docs_utils.py.
    def match_param_docs(self) -> tuple[set[str], set[str]]:
        params_with_doc: set[str] = set()
        params_with_type: set[str] = set()
        entries = self._parse_section(self.re_param_section)
        entries.extend(self._parse_section(self.re_keyword_param_section))
        for entry in entries:
            match = self.re_param_line.match(entry)
            if not match:
                continue
            param_name = match.group(1)
            # Remove escape characters necessary for asterisks
            param_name = param_name.replace("\\", "")
            param_type = match.group(2)
            param_desc = match.group(3)
            if param_type:
                params_with_type.add(param_name)
            if param_desc:
                params_with_doc.add(param_name)
        return params_with_doc, params_with_type
References _parse_section(), re_keyword_param_section, re_param_line, and re_param_section.
matching_sections()
int pylint.extensions._check_docs_utils.GoogleDocstring.matching_sections (self)
Returns the number of matching docstring sections.
Reimplemented from pylint.extensions._check_docs_utils.Docstring.
Definition at line 622 of file _check_docs_utils.py.
    def matching_sections(self) -> int:
        """Returns the number of matching docstring sections."""
        return sum(
            bool(i)
            for i in (
                self.re_param_section.search(self.doc),
                self.re_raise_section.search(self.doc),
                self.re_returns_section.search(self.doc),
                self.re_yields_section.search(self.doc),
                self.re_property_returns_line.search(self._first_line()),
            )
        )
min_section_indent()
int pylint.extensions._check_docs_utils.GoogleDocstring.min_section_indent (re.Match[str] section_match) static
Reimplemented in pylint.extensions._check_docs_utils.NumpyDocstring.
Definition at line 768 of file _check_docs_utils.py.
    def min_section_indent(section_match: re.Match[str]) -> int:
        return len(section_match.group(1)) + 1
Referenced by _parse_section().
Member Data Documentation
_re_section_template
str pylint.extensions._check_docs_utils.GoogleDocstring._re_section_template static protected
Initial value:
=  r"""
        ^([ ]*)   {0} \s*:   \s*$     # Google parameter header
        (  .* )                       # section
        """
Definition at line 555 of file _check_docs_utils.py.
re_container_type
str pylint.extensions._check_docs_utils.GoogleDocstring.re_container_type static
Initial value:
=  rf"""
        (?:{re_type}|{re_xref})       # a container type
        [\‍(\[] [^\n]+ [\‍)\]]          # with the contents of the container
    """
Definition at line 545 of file _check_docs_utils.py.
re_keyword_param_section
pylint.extensions._check_docs_utils.GoogleDocstring.re_keyword_param_section static
Initial value:
=  re.compile(
        _re_section_template.format(r"Keyword\s(?:Args|Arguments|Parameters)"),
        re.X | re.S | re.M,
    )
Definition at line 565 of file _check_docs_utils.py.
Referenced by match_param_docs().
re_multiple_type
str pylint.extensions._check_docs_utils.GoogleDocstring.re_multiple_type static
Initial value:
=  rf"""
        (?:{re_container_type}|{re_type}|{re_xref})
        (?:(?:\s+(?:of|or)\s+|\s*,\s*|\s+\|\s+)(?:{re_container_type}|{re_type}|{re_xref}))*
    """
Definition at line 550 of file _check_docs_utils.py.
re_param_line
pylint.extensions._check_docs_utils.GoogleDocstring.re_param_line static
Initial value:
=  re.compile(
        rf,
        re.X | re.S | re.M,
    )
Definition at line 570 of file _check_docs_utils.py.
Referenced by match_param_docs().
re_param_section
pylint.extensions._check_docs_utils.GoogleDocstring.re_param_section static
Initial value:
=  re.compile(
        _re_section_template.format(r"(?:Args|Arguments|Parameters)"),
        re.X | re.S | re.M,
    )
Definition at line 560 of file _check_docs_utils.py.
Referenced by has_params(), has_property_returns(), match_param_docs(), and pylint.extensions._check_docs_utils.NumpyDocstring.match_param_docs().
re_property_returns_line
pylint.extensions._check_docs_utils.GoogleDocstring.re_property_returns_line static
Initial value:
=  re.compile(
        rf,
        re.X | re.S | re.M,
    )
Definition at line 606 of file _check_docs_utils.py.
Referenced by has_property_type().
re_raise_line
pylint.extensions._check_docs_utils.GoogleDocstring.re_raise_line static
Initial value:
=  re.compile(
        rf,
        re.X | re.S | re.M,
    )
Definition at line 586 of file _check_docs_utils.py.
Referenced by exceptions().
re_raise_section
pylint.extensions._check_docs_utils.GoogleDocstring.re_raise_section static
Initial value:
=  re.compile(
        _re_section_template.format(r"Raises"), re.X | re.S | re.M
    )
Definition at line 582 of file _check_docs_utils.py.
Referenced by exceptions(), and has_property_returns().
re_returns_line
pylint.extensions._check_docs_utils.GoogleDocstring.re_returns_line static
Initial value:
=  re.compile(
        rf,
        re.X | re.S | re.M,
    )
Definition at line 598 of file _check_docs_utils.py.
Referenced by has_returns(), and has_rtype().
re_returns_section
pylint.extensions._check_docs_utils.GoogleDocstring.re_returns_section static
Initial value:
=  re.compile(
        _re_section_template.format(r"Returns?"), re.X | re.S | re.M
    )
Definition at line 594 of file _check_docs_utils.py.
Referenced by has_property_returns(), has_returns(), and has_rtype().
re_type
pylint.extensions._check_docs_utils.GoogleDocstring.re_type = SphinxDocstring.re_type static
Definition at line 541 of file _check_docs_utils.py.
re_xref
pylint.extensions._check_docs_utils.GoogleDocstring.re_xref = SphinxDocstring.re_xref static
Definition at line 543 of file _check_docs_utils.py.
re_yields_line
pylint.extensions._check_docs_utils.GoogleDocstring.re_yields_line = re_returns_line static
Definition at line 618 of file _check_docs_utils.py.
Referenced by has_yields(), and has_yields_type().
re_yields_section
pylint.extensions._check_docs_utils.GoogleDocstring.re_yields_section static
Initial value:
=  re.compile(
        _re_section_template.format(r"Yields?"), re.X | re.S | re.M
    )
Definition at line 614 of file _check_docs_utils.py.
Referenced by has_property_returns(), has_yields(), and has_yields_type().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pylint/extensions/_check_docs_utils.py