Read&Watch: pylint.extensions.for_any_all.ConsiderUsingAnyOrAllChecker Class Reference
pylint.extensions.for_any_all.ConsiderUsingAnyOrAllChecker Class Reference
Public Member Functions
None visit_for (self, nodes.For node)
Public Member Functions inherited from pylint.checkers.base_checker.BaseChecker
None __init__ (self, PyLinter linter)
bool __gt__ (self, Any other)
bool __eq__ (self, object other)
int __hash__ (self)
str __repr__ (self)
str __str__ (self)
str get_full_documentation (self, dict[str, MessageDefinitionTuple] msgs, Iterable[tuple[str, OptionDict, Any]] options, Sequence[tuple[str, str, ReportsCallable]] reports, str|None doc=None, str|None module=None, bool show_options=True)
None add_message (self, str msgid, int|None line=None, nodes.NodeNG|None node=None, Any args=None, Confidence|None confidence=None, int|None col_offset=None, int|None end_lineno=None, int|None end_col_offset=None)
None check_consistency (self)
MessageDefinition create_message_definition_from_tuple (self, str msgid, MessageDefinitionTuple msg_tuple)
list[MessageDefinition] messages (self)
None open (self)
None close (self)
Any get_map_data (self)
None reduce_map_data (self, PyLinter linter, list[Any] data)
Public Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
None __init__ (self, _ArgumentsManager arguments_manager)
Static Protected Member Functions
bool _if_statement_returns_bool (list[nodes.NodeNG] if_children, nodes.NodeNG node_after_loop)
bool _assigned_reassigned_returned (nodes.For node, list[nodes.NodeNG] if_children, nodes.NodeNG node_after_loop)
str _build_suggested_string (nodes.For node, bool final_return_bool)
Additional Inherited Members
Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
linter = linter
messages
Static Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
str name = ""
dict msgs = {}
tuple reports = ()
bool enabled = True
Static Public Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
tuple options = ()
dict option_groups_descs = {}
Protected Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
Any _option_value (self, str opt)
Iterator[ tuple[str, list[tuple[str, OptionDict, Any]]]|tuple[None, dict[str, list[tuple[str, OptionDict, Any]]]]] _options_by_section (self)
Iterator[tuple[str, OptionDict, Any]] _options_and_values (self, Options|None options=None)
Protected Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
_arguments_manager = arguments_manager
Detailed Description
Definition at line 25 of file for_any_all.py.
Member Function Documentation
_assigned_reassigned_returned()
bool pylint.extensions.for_any_all.ConsiderUsingAnyOrAllChecker._assigned_reassigned_returned (nodes.For node, list[nodes.NodeNG] if_children, nodes.NodeNG node_after_loop) static protected
Detect boolean-assign, for-loop, re-assign, return pattern:
Ex:
    def check_lines(lines, max_chars):
        long_line = False
        for line in lines:
            if len(line) > max_chars:
                long_line = True
            # no elif / else statement
        return long_line
Definition at line 95 of file for_any_all.py.
    ) -> bool:
        """Detect boolean-assign, for-loop, re-assign, return pattern:
        Ex:
            def check_lines(lines, max_chars):
                long_line = False
                for line in lines:
                    if len(line) > max_chars:
                        long_line = True
                    # no elif / else statement
                return long_line
        """
        node_before_loop = node.previous_sibling()
        if not assigned_bool(node_before_loop):
            # node before loop isn't assigning to boolean
            return False
        assign_children = [x for x in if_children if isinstance(x, nodes.Assign)]
        if not assign_children:
            # if-nodes inside loop aren't assignments
            return False
        # We only care for the first assign node of the if-children. Otherwise it breaks the pattern.
        first_target = assign_children[0].targets[0]
        target_before_loop = node_before_loop.targets[0]
        if not (
            isinstance(first_target, nodes.AssignName)
            and isinstance(target_before_loop, nodes.AssignName)
        ):
            return False
        node_before_loop_name = node_before_loop.targets[0].name
        return (
            first_target.name == node_before_loop_name
            and isinstance(node_after_loop, nodes.Return)
            and isinstance(node_after_loop.value, nodes.Name)
            and node_after_loop.value.name == node_before_loop_name
        )
Referenced by visit_for().
_build_suggested_string()
str pylint.extensions.for_any_all.ConsiderUsingAnyOrAllChecker._build_suggested_string (nodes.For node, bool final_return_bool) static protected
When a nodes.For node can be rewritten as an any/all statement, return a
suggestion for that statement.
'final_return_bool' is the boolean literal returned after the for loop if all
conditions fail.
Definition at line 139 of file for_any_all.py.
    def _build_suggested_string(node: nodes.For, final_return_bool: bool) -> str:
        """When a nodes.For node can be rewritten as an any/all statement, return a
        suggestion for that statement.
        'final_return_bool' is the boolean literal returned after the for loop if all
        conditions fail.
        """
        loop_var = node.target.as_string()
        loop_iter = node.iter.as_string()
        test_node = next(node.body[0].get_children())
        if isinstance(test_node, nodes.UnaryOp) and test_node.op == "not":
            # The condition is negated. Advance the node to the operand and modify the suggestion
            test_node = test_node.operand
            suggested_function = "all" if final_return_bool else "not all"
        else:
            suggested_function = "not any" if final_return_bool else "any"
        test = test_node.as_string()
        return f"{suggested_function}({test} for {loop_var} in {loop_iter})"
Referenced by visit_for().
_if_statement_returns_bool()
bool pylint.extensions.for_any_all.ConsiderUsingAnyOrAllChecker._if_statement_returns_bool (list[nodes.NodeNG] if_children, nodes.NodeNG node_after_loop) static protected
Detect for-loop, if-statement, return pattern:
Ex:
    def any_uneven(items):
        for item in items:
            if not item % 2 == 0:
                return True
        return False
Definition at line 73 of file for_any_all.py.
    ) -> bool:
        """Detect for-loop, if-statement, return pattern:
        Ex:
            def any_uneven(items):
                for item in items:
                    if not item % 2 == 0:
                        return True
                return False
        """
        if not len(if_children) == 2:
            # The If node has only a comparison and return
            return False
        if not returns_bool(if_children[1]):
            return False
        # Check for terminating boolean return right after the loop
        return returns_bool(node_after_loop)
Referenced by visit_for().
visit_for()
None pylint.extensions.for_any_all.ConsiderUsingAnyOrAllChecker.visit_for (self, nodes.For node)
Definition at line 36 of file for_any_all.py.
    def visit_for(self, node: nodes.For) -> None:
        if len(node.body) != 1:  # Only If node with no Else
            return
        if not isinstance(node.body[0], nodes.If):
            return
        if_children = list(node.body[0].get_children())
        if any(isinstance(child, nodes.If) for child in if_children):
            # an if node within the if-children indicates an elif clause,
            # suggesting complex logic.
            return
        node_after_loop = node.next_sibling()
        if self._assigned_reassigned_returned(node, if_children, node_after_loop):
            final_return_bool = node_after_loop.value.name
            suggested_string = self._build_suggested_string(node, final_return_bool)
            self.add_message(
                "consider-using-any-or-all",
                node=node,
                args=suggested_string,
                confidence=HIGH,
            )
            return
        if self._if_statement_returns_bool(if_children, node_after_loop):
            final_return_bool = node_after_loop.value.value
            suggested_string = self._build_suggested_string(node, final_return_bool)
            self.add_message(
                "consider-using-any-or-all",
                node=node,
                args=suggested_string,
                confidence=HIGH,
            )
            return
References _assigned_reassigned_returned(), _build_suggested_string(), _if_statement_returns_bool(), and pylint.checkers.base_checker.BaseChecker.add_message().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pylint/extensions/for_any_all.py