Read&Watch: django.test.testcases.TestCase Class Reference
django.test.testcases.TestCase Class Reference
Public Member Functions
setUpClass (cls)
tearDownClass (cls)
setUpTestData (cls)
captureOnCommitCallbacks (cls, *, using=DEFAULT_DB_ALIAS, execute=False)
Public Member Functions inherited from django.test.testcases.TransactionTestCase
assertQuerySetEqual (self, qs, values, transform=None, ordered=True, msg=None)
assertNumQueries (self, num, func=None, *args, using=DEFAULT_DB_ALIAS, **kwargs)
Public Member Functions inherited from django.test.testcases.SimpleTestCase
ensure_connection_patch_method (cls)
__call__ (self, result=None)
__getstate__ (self)
debug (self)
enterClassContext (cls, cm)
settings (self, **kwargs)
modify_settings (self, **kwargs)
assertRedirects (self, response, expected_url, status_code=302, target_status_code=200, msg_prefix="", fetch_redirect_response=True)
assertURLEqual (self, url1, url2, msg_prefix="")
assertContains (self, response, text, count=None, status_code=200, msg_prefix="", html=False)
assertNotContains (self, response, text, status_code=200, msg_prefix="", html=False)
assertFormError (self, form, field, errors, msg_prefix="")
assertFormSetError (self, formset, form_index, field, errors, msg_prefix="")
assertTemplateUsed (self, response=None, template_name=None, msg_prefix="", count=None)
assertTemplateNotUsed (self, response=None, template_name=None, msg_prefix="")
assertRaisesMessage (self, expected_exception, expected_message, *args, **kwargs)
assertWarnsMessage (self, expected_warning, expected_message, *args, **kwargs)
assertFieldOutput (self, fieldclass, valid, invalid, field_args=None, field_kwargs=None, empty_value="")
assertHTMLEqual (self, html1, html2, msg=None)
assertHTMLNotEqual (self, html1, html2, msg=None)
assertInHTML (self, needle, haystack, count=None, msg_prefix="")
assertNotInHTML (self, needle, haystack, msg_prefix="")
assertJSONEqual (self, raw, expected_data, msg=None)
assertJSONNotEqual (self, raw, expected_data, msg=None)
assertXMLEqual (self, xml1, xml2, msg=None)
assertXMLNotEqual (self, xml1, xml2, msg=None)
Public Attributes
cls_atomics = cls._enter_atomics()
atomics = self._enter_atomics()
Public Attributes inherited from django.test.testcases.SimpleTestCase
ensure_connection
client = self.client_class()
async_client = self.async_client_class()
addClassCleanup
assertRaises
assertWarns
Protected Member Functions
_enter_atomics (cls)
_rollback_atomics (cls, atomics)
_databases_support_transactions (cls)
_databases_support_savepoints (cls)
_should_reload_connections (self)
_fixture_setup (self)
_fixture_teardown (self)
_should_check_constraints (self, connection)
Protected Member Functions inherited from django.test.testcases.TransactionTestCase
_pre_setup (self)
_databases_names (cls, include_mirrors=True)
_reset_sequences (self, db_name)
_post_teardown (self)
Protected Member Functions inherited from django.test.testcases.SimpleTestCase
_validate_databases (cls)
_add_databases_failures (cls)
_remove_databases_failures (cls)
_setup_and_call (self, result, debug=False)
_assert_contains (self, response, text, status_code, msg_prefix, html)
_check_test_client_response (self, response, attribute, method_name)
_assert_form_error (self, form, field, errors, msg_prefix, form_repr)
_get_template_used (self, response, template_name, msg_prefix, method_name)
_assert_template_used (self, template_name, template_names, msg_prefix, count)
_assert_raises_or_warns_cm (self, func, cm_attr, expected_exception, expected_message)
_assertFooMessage (self, func, cm_attr, expected_exception, expected_message, *args, **kwargs)
Additional Inherited Members
Static Public Attributes inherited from django.test.testcases.TransactionTestCase
bool reset_sequences = False
available_apps = None
fixtures = None
bool serialized_rollback = False
Static Public Attributes inherited from django.test.testcases.SimpleTestCase
client_class = Client
async_client_class = AsyncClient
str databases = set()
Protected Attributes inherited from django.test.testcases.SimpleTestCase
_remove_databases_failures
_testMethodName
Static Protected Attributes inherited from django.test.testcases.SimpleTestCase
_overridden_settings = None
_modified_settings = None
tuple _disallowed_database_msg
list _disallowed_connection_methods
Detailed Description
Similar to TransactionTestCase, but use `transaction.atomic()` to achieve
test isolation.
In most situations, TestCase should be preferred to TransactionTestCase as
it allows faster execution. However, there are some situations where using
TransactionTestCase might be necessary (e.g. testing some transactional
behavior).
On database backends with no transaction support, TestCase behaves as
TransactionTestCase.
Definition at line 1336 of file testcases.py.
Member Function Documentation
_databases_support_savepoints()
django.test.testcases.TestCase._databases_support_savepoints (cls) protected
Definition at line 1373 of file testcases.py.
    def _databases_support_savepoints(cls):
        return connections_support_savepoints(cls.databases)
References django.test.testcases.connections_support_savepoints(), and django.test.testcases.SimpleTestCase.databases.
Referenced by setUpClass(), and tearDownClass().
_databases_support_transactions()
django.test.testcases.TestCase._databases_support_transactions (cls) protected
Definition at line 1369 of file testcases.py.
    def _databases_support_transactions(cls):
        return connections_support_transactions(cls.databases)
Referenced by _fixture_setup(), _fixture_teardown(), setUpClass(), and tearDownClass().
_enter_atomics()
django.test.testcases.TestCase._enter_atomics (cls) protected
Open atomic blocks for multiple databases.
Definition at line 1351 of file testcases.py.
    def _enter_atomics(cls):
        """Open atomic blocks for multiple databases."""
        atomics = {}
        for db_name in cls._databases_names():
            atomic = transaction.atomic(using=db_name)
            atomic._from_testcase = True
            atomic.__enter__()
            atomics[db_name] = atomic
        return atomics
References django.test.testcases.TransactionTestCase._databases_names().
_fixture_setup()
django.test.testcases.TestCase._fixture_setup (self) protected
Reimplemented from django.test.testcases.TransactionTestCase.
Definition at line 1429 of file testcases.py.
    def _fixture_setup(self):
        if not self._databases_support_transactions():
            # If the backend does not support transactions, we should reload
            # class data before each test
            self.setUpTestData()
            return super()._fixture_setup()
        if self.reset_sequences:
            raise TypeError("reset_sequences cannot be used on TestCase instances")
        self.atomics = self._enter_atomics()
        if not self._databases_support_savepoints():
            if self.fixtures:
                for db_name in self._databases_names(include_mirrors=False):
                    call_command(
                        "loaddata",
                        *self.fixtures,
                        **{"verbosity": 0, "database": db_name},
                    )
            self.setUpTestData()
References _databases_support_transactions(), _fixture_setup(), and setUpTestData().
Referenced by _fixture_setup().
_fixture_teardown()
django.test.testcases.TestCase._fixture_teardown (self) protected
Reimplemented from django.test.testcases.TransactionTestCase.
Definition at line 1449 of file testcases.py.
    def _fixture_teardown(self):
        if not self._databases_support_transactions():
            return super()._fixture_teardown()
        try:
            for db_name in reversed(self._databases_names()):
                if self._should_check_constraints(connections[db_name]):
                    connections[db_name].check_constraints()
        finally:
            self._rollback_atomics(self.atomics)
References django.test.testcases.TransactionTestCase._databases_names(), _databases_support_transactions(), _fixture_teardown(), _rollback_atomics(), _should_check_constraints(), and atomics.
Referenced by _fixture_teardown().
_rollback_atomics()
django.test.testcases.TestCase._rollback_atomics (cls, atomics) protected
Rollback atomic blocks opened by the previous method.
Definition at line 1362 of file testcases.py.
    def _rollback_atomics(cls, atomics):
        """Rollback atomic blocks opened by the previous method."""
        for db_name in reversed(cls._databases_names()):
            transaction.set_rollback(True, using=db_name)
            atomics[db_name].__exit__(None, None, None)
References django.test.testcases.TransactionTestCase._databases_names().
Referenced by _fixture_teardown(), and tearDownClass().
_should_check_constraints()
django.test.testcases.TestCase._should_check_constraints (self, connection) protected
Definition at line 1459 of file testcases.py.
    def _should_check_constraints(self, connection):
        return (
            connection.features.can_defer_constraint_checks
            and not connection.needs_rollback
            and connection.is_usable()
        )
Referenced by _fixture_teardown().
_should_reload_connections()
django.test.testcases.TestCase._should_reload_connections (self) protected
Reimplemented from django.test.testcases.TransactionTestCase.
Definition at line 1424 of file testcases.py.
    def _should_reload_connections(self):
        if self._databases_support_transactions():
            return False
        return super()._should_reload_connections()
captureOnCommitCallbacks()
django.test.testcases.TestCase.captureOnCommitCallbacks (cls, * , using = DEFAULT_DB_ALIAS, execute = False)
Context manager to capture transaction.on_commit() callbacks.
Definition at line 1468 of file testcases.py.
    def captureOnCommitCallbacks(cls, *, using=DEFAULT_DB_ALIAS, execute=False):
        """Context manager to capture transaction.on_commit() callbacks."""
        callbacks = []
        start_count = len(connections[using].run_on_commit)
        try:
            yield callbacks
        finally:
            while True:
                callback_count = len(connections[using].run_on_commit)
                for _, callback, robust in connections[using].run_on_commit[
                    start_count:
                ]:
                    callbacks.append(callback)
                    if execute:
                        if robust:
                            try:
                                callback()
                            except Exception as e:
                                logger.error(
                                    f"Error calling {callback.__qualname__} in "
                                    f"on_commit() (%s).",
                                    e,
                                    exc_info=True,
                                )
                        else:
                            callback()
                if callback_count == len(connections[using].run_on_commit):
                    break
                start_count = callback_count
setUpClass()
django.test.testcases.TestCase.setUpClass (cls)
Reimplemented from django.test.testcases.SimpleTestCase.
Definition at line 1377 of file testcases.py.
    def setUpClass(cls):
        super().setUpClass()
        if not (
            cls._databases_support_transactions()
            and cls._databases_support_savepoints()
        ):
            return
        cls.cls_atomics = cls._enter_atomics()
        if cls.fixtures:
            for db_name in cls._databases_names(include_mirrors=False):
                try:
                    call_command(
                        "loaddata",
                        *cls.fixtures,
                        verbosity=0,
                        database=db_name,
                    )
                except Exception:
                    cls._rollback_atomics(cls.cls_atomics)
                    raise
        pre_attrs = cls.__dict__.copy()
        try:
            cls.setUpTestData()
        except Exception:
            cls._rollback_atomics(cls.cls_atomics)
            raise
        for name, value in cls.__dict__.items():
            if value is not pre_attrs.get(name):
                setattr(cls, name, TestData(name, value))
References _databases_support_savepoints(), _databases_support_transactions(), and setUpClass().
Referenced by setUpClass().
setUpTestData()
django.test.testcases.TestCase.setUpTestData (cls)
Load initial data for the TestCase.
Definition at line 1420 of file testcases.py.
    def setUpTestData(cls):
        """Load initial data for the TestCase."""
        pass
Referenced by _fixture_setup().
tearDownClass()
django.test.testcases.TestCase.tearDownClass (cls)
Definition at line 1409 of file testcases.py.
    def tearDownClass(cls):
        if (
            cls._databases_support_transactions()
            and cls._databases_support_savepoints()
        ):
            cls._rollback_atomics(cls.cls_atomics)
            for conn in connections.all(initialized_only=True):
                conn.close()
        super().tearDownClass()
References _databases_support_savepoints(), _databases_support_transactions(), _rollback_atomics(), cls_atomics, and tearDownClass().
Referenced by tearDownClass().
Member Data Documentation
atomics
django.test.testcases.TestCase.atomics = self._enter_atomics()
Definition at line 1438 of file testcases.py.
Referenced by _fixture_teardown().
cls_atomics
django.test.testcases.TestCase.cls_atomics = cls._enter_atomics()
Definition at line 1384 of file testcases.py.
Referenced by tearDownClass().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/test/testcases.py