Read&Watch: django.contrib.auth.backends.ModelBackend Class Reference
django.contrib.auth.backends.ModelBackend Class Reference
Public Member Functions
authenticate (self, request, username=None, password=None, **kwargs)
user_can_authenticate (self, user)
get_user_permissions (self, user_obj, obj=None)
get_group_permissions (self, user_obj, obj=None)
get_all_permissions (self, user_obj, obj=None)
has_perm (self, user_obj, perm, obj=None)
has_module_perms (self, user_obj, app_label)
with_perm (self, perm, is_active=True, include_superusers=True, obj=None)
get_user (self, user_id)
Protected Member Functions
_get_user_permissions (self, user_obj)
_get_group_permissions (self, user_obj)
_get_permissions (self, user_obj, obj, from_name)
Detailed Description
Authenticates against settings.AUTH_USER_MODEL.
Definition at line 31 of file backends.py.
Member Function Documentation
_get_group_permissions()
django.contrib.auth.backends.ModelBackend._get_group_permissions (self, user_obj) protected
Definition at line 61 of file backends.py.
    def _get_group_permissions(self, user_obj):
        user_groups_field = get_user_model()._meta.get_field("groups")
        user_groups_query = "group__%s" % user_groups_field.related_query_name()
        return Permission.objects.filter(**{user_groups_query: user_obj})
References django.contrib.auth.get_user_model().
_get_permissions()
django.contrib.auth.backends.ModelBackend._get_permissions (self, user_obj, obj, from_name) protected
Return the permissions of `user_obj` from `from_name`. `from_name` can
be either "group" or "user" to return permissions from
`_get_group_permissions` or `_get_user_permissions` respectively.
Definition at line 66 of file backends.py.
    def _get_permissions(self, user_obj, obj, from_name):
        """
        Return the permissions of `user_obj` from `from_name`. `from_name` can
        be either "group" or "user" to return permissions from
        `_get_group_permissions` or `_get_user_permissions` respectively.
        """
        if not user_obj.is_active or user_obj.is_anonymous or obj is not None:
            return set()
        perm_cache_name = "_%s_perm_cache" % from_name
        if not hasattr(user_obj, perm_cache_name):
            if user_obj.is_superuser:
                perms = Permission.objects.all()
            else:
                perms = getattr(self, "_get_%s_permissions" % from_name)(user_obj)
            perms = perms.values_list("content_type__app_label", "codename").order_by()
            setattr(
                user_obj, perm_cache_name, {"%s.%s" % (ct, name) for ct, name in perms}
            )
        return getattr(user_obj, perm_cache_name)
Referenced by get_group_permissions(), and get_user_permissions().
_get_user_permissions()
django.contrib.auth.backends.ModelBackend._get_user_permissions (self, user_obj) protected
Definition at line 58 of file backends.py.
    def _get_user_permissions(self, user_obj):
        return user_obj.user_permissions.all()
authenticate()
django.contrib.auth.backends.ModelBackend.authenticate (self, request, username = None, password = None, ** kwargs)
Reimplemented from django.contrib.auth.backends.BaseBackend.
Reimplemented in django.contrib.auth.backends.RemoteUserBackend.
Definition at line 36 of file backends.py.
    def authenticate(self, request, username=None, password=None, **kwargs):
        if username is None:
            username = kwargs.get(UserModel.USERNAME_FIELD)
        if username is None or password is None:
            return
        try:
            user = UserModel._default_manager.get_by_natural_key(username)
        except UserModel.DoesNotExist:
            # Run the default password hasher once to reduce the timing
            # difference between an existing and a nonexistent user (#20760).
            UserModel().set_password(password)
        else:
            if user.check_password(password) and self.user_can_authenticate(user):
                return user
References user_can_authenticate(), and django.contrib.auth.backends.UserModel.
get_all_permissions()
django.contrib.auth.backends.ModelBackend.get_all_permissions (self, user_obj, obj = None)
Reimplemented from django.contrib.auth.backends.BaseBackend.
Definition at line 101 of file backends.py.
    def get_all_permissions(self, user_obj, obj=None):
        if not user_obj.is_active or user_obj.is_anonymous or obj is not None:
            return set()
        if not hasattr(user_obj, "_perm_cache"):
            user_obj._perm_cache = super().get_all_permissions(user_obj)
        return user_obj._perm_cache
References get_all_permissions().
Referenced by get_all_permissions().
get_group_permissions()
django.contrib.auth.backends.ModelBackend.get_group_permissions (self, user_obj, obj = None)
Return a set of permission strings the user `user_obj` has from the
groups they belong.
Reimplemented from django.contrib.auth.backends.BaseBackend.
Definition at line 94 of file backends.py.
    def get_group_permissions(self, user_obj, obj=None):
        """
        Return a set of permission strings the user `user_obj` has from the
        groups they belong.
        """
        return self._get_permissions(user_obj, obj, "group")
References _get_permissions().
get_user()
django.contrib.auth.backends.ModelBackend.get_user (self, user_id)
Reimplemented from django.contrib.auth.backends.BaseBackend.
Definition at line 155 of file backends.py.
    def get_user(self, user_id):
        try:
            user = UserModel._default_manager.get(pk=user_id)
        except UserModel.DoesNotExist:
            return None
        return user if self.user_can_authenticate(user) else None
References user_can_authenticate().
get_user_permissions()
django.contrib.auth.backends.ModelBackend.get_user_permissions (self, user_obj, obj = None)
Return a set of permission strings the user `user_obj` has from their
`user_permissions`.
Reimplemented from django.contrib.auth.backends.BaseBackend.
Definition at line 87 of file backends.py.
    def get_user_permissions(self, user_obj, obj=None):
        """
        Return a set of permission strings the user `user_obj` has from their
        `user_permissions`.
        """
        return self._get_permissions(user_obj, obj, "user")
References _get_permissions().
has_module_perms()
django.contrib.auth.backends.ModelBackend.has_module_perms (self, user_obj, app_label)
Return True if user_obj has any permissions in the given app_label.
Definition at line 111 of file backends.py.
    def has_module_perms(self, user_obj, app_label):
        """
        Return True if user_obj has any permissions in the given app_label.
        """
        return user_obj.is_active and any(
            perm[: perm.index(".")] == app_label
            for perm in self.get_all_permissions(user_obj)
        )
References django.contrib.auth.backends.BaseBackend.get_all_permissions().
has_perm()
django.contrib.auth.backends.ModelBackend.has_perm (self, user_obj, perm, obj = None)
Reimplemented from django.contrib.auth.backends.BaseBackend.
Definition at line 108 of file backends.py.
    def has_perm(self, user_obj, perm, obj=None):
        return user_obj.is_active and super().has_perm(user_obj, perm, obj=obj)
References has_perm().
Referenced by has_perm(), django.contrib.auth.models.AnonymousUser.has_perms(), and django.contrib.auth.models.PermissionsMixin.has_perms().
user_can_authenticate()
django.contrib.auth.backends.ModelBackend.user_can_authenticate (self, user)
Reject users with is_active=False. Custom user models that don't have
that attribute are allowed.
Reimplemented in django.contrib.auth.backends.AllowAllUsersModelBackend, and django.contrib.auth.backends.AllowAllUsersRemoteUserBackend.
Definition at line 51 of file backends.py.
    def user_can_authenticate(self, user):
        """
        Reject users with is_active=False. Custom user models that don't have
        that attribute are allowed.
        """
        return getattr(user, "is_active", True)
Referenced by authenticate(), django.contrib.auth.backends.RemoteUserBackend.authenticate(), and get_user().
with_perm()
django.contrib.auth.backends.ModelBackend.with_perm (self, perm, is_active = True, include_superusers = True, obj = None)
Return users that have permission "perm". By default, filter out
inactive users and include superusers.
Definition at line 120 of file backends.py.
    def with_perm(self, perm, is_active=True, include_superusers=True, obj=None):
        """
        Return users that have permission "perm". By default, filter out
        inactive users and include superusers.
        """
        if isinstance(perm, str):
            try:
                app_label, codename = perm.split(".")
            except ValueError:
                raise ValueError(
                    "Permission name should be in the form "
                    "app_label.permission_codename."
                )
        elif not isinstance(perm, Permission):
            raise TypeError(
                "The `perm` argument must be a string or a permission instance."
            )
        if obj is not None:
            return UserModel._default_manager.none()
        permission_q = Q(group__user=OuterRef("pk")) | Q(user=OuterRef("pk"))
        if isinstance(perm, Permission):
            permission_q &= Q(pk=perm.pk)
        else:
            permission_q &= Q(codename=codename, content_type__app_label=app_label)
        user_q = Exists(Permission.objects.filter(permission_q))
        if include_superusers:
            user_q |= Q(is_superuser=True)
        if is_active is not None:
            user_q &= Q(is_active=is_active)
        return UserModel._default_manager.filter(user_q)
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/auth/backends.py