Read&Watch: pip._vendor.distlib.util.Progress Class Reference
pip._vendor.distlib.util.Progress Class Reference
Public Member Functions
__init__ (self, minval=0, maxval=100)
update (self, curval)
increment (self, incr)
start (self)
stop (self)
maximum (self)
percentage (self)
format_duration (self, duration)
ETA (self)
speed (self)
Public Attributes
min = minval
max = maxval
started = None
int elapsed = 0
bool done = False
cur = curval
Static Public Attributes
str unknown = 'UNKNOWN'
Detailed Description
Definition at line 1313 of file util.py.
Constructor & Destructor Documentation
__init__()
pip._vendor.distlib.util.Progress.__init__ (self, minval = 0, maxval = 100)
Definition at line 1316 of file util.py.
    def __init__(self, minval=0, maxval=100):
        assert maxval is None or maxval >= minval
        self.min = self.cur = minval
        self.max = maxval
        self.started = None
        self.elapsed = 0
        self.done = False
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
ETA()
pip._vendor.distlib.util.Progress.ETA (self)
Definition at line 1372 of file util.py.
    def ETA(self):
        if self.done:
            prefix = 'Done'
            t = self.elapsed
            # import pdb; pdb.set_trace()
        else:
            prefix = 'ETA '
            if self.max is None:
                t = -1
            elif self.elapsed == 0 or (self.cur == self.min):
                t = 0
            else:
                # import pdb; pdb.set_trace()
                t = float(self.max - self.min)
                t /= self.cur - self.min
                t = (t - 1) * self.elapsed
        return '%s: %s' % (prefix, self.format_duration(t))
format_duration()
pip._vendor.distlib.util.Progress.format_duration (self, duration)
Definition at line 1362 of file util.py.
    def format_duration(self, duration):
        if (duration <= 0) and self.max is None or self.cur == self.min:
            result = '??:??:??'
        # elif duration < 1:
        #     result = '--:--:--'
        else:
            result = time.strftime('%H:%M:%S', time.gmtime(duration))
        return result
increment()
pip._vendor.distlib.util.Progress.increment (self, incr)
Definition at line 1334 of file util.py.
    def increment(self, incr):
        assert incr >= 0
        self.update(self.cur + incr)
maximum()
pip._vendor.distlib.util.Progress.maximum (self)
Definition at line 1348 of file util.py.
    def maximum(self):
        return self.unknown if self.max is None else self.max
Referenced by pip._vendor.rich.measure.Measurement.span().
percentage()
pip._vendor.distlib.util.Progress.percentage (self)
Definition at line 1352 of file util.py.
    def percentage(self):
        if self.done:
            result = '100 %'
        elif self.max is None:
            result = ' ?? %'
        else:
            v = 100.0 * (self.cur - self.min) / (self.max - self.min)
            result = '%3d %%' % v
        return result
speed()
pip._vendor.distlib.util.Progress.speed (self)
Definition at line 1391 of file util.py.
    def speed(self):
        if self.elapsed == 0:
            result = 0.0
        else:
            result = (self.cur - self.min) / self.elapsed
        for unit in UNITS:
            if result < 1000:
                break
            result /= 1000.0
        return '%d %sB/s' % (result, unit)
#
# Glob functionality
#
start()
pip._vendor.distlib.util.Progress.start (self)
Definition at line 1338 of file util.py.
    def start(self):
        self.update(self.min)
        return self
Referenced by pip._vendor.rich.live.Live.__enter__(), pip._vendor.rich.progress._TrackThread.__enter__(), pip._vendor.rich.progress.Progress.__enter__(), pip._vendor.rich.status.Status.__enter__(), and responses.RequestsMock.__enter__().
stop()
pip._vendor.distlib.util.Progress.stop (self)
Definition at line 1342 of file util.py.
    def stop(self):
        if self.max is not None:
            self.update(self.max)
        self.done = True
Referenced by pip._vendor.rich.live.Live.__exit__(), pip._vendor.rich.progress.Progress.__exit__(), pip._vendor.rich.status.Status.__exit__(), responses.RequestsMock.__exit__(), and pip._vendor.rich.live.Live.start().
update()
pip._vendor.distlib.util.Progress.update (self, curval)
Definition at line 1324 of file util.py.
    def update(self, curval):
        assert self.min <= curval
        assert self.max is None or curval <= self.max
        self.cur = curval
        now = time.time()
        if self.started is None:
            self.started = now
        else:
            self.elapsed = now - self.started
Referenced by tomlkit._types._CustomDict.__ior__(), yaml.reader.Reader.determine_encoding(), yaml.reader.Reader.forward(), pip._vendor.rich.progress.Progress.open(), yaml.reader.Reader.peek(), yaml.reader.Reader.prefix(), pip._vendor.rich.progress.Progress.track(), and pip._vendor.rich.progress.Progress.wrap_file().
Member Data Documentation
cur
pip._vendor.distlib.util.Progress.cur = curval
Definition at line 1327 of file util.py.
done
bool pip._vendor.distlib.util.Progress.done = False
Definition at line 1322 of file util.py.
Referenced by pip._vendor.rich.progress._TrackThread.__exit__(), yaml.scanner.Scanner.fetch_stream_end(), yaml.scanner.Scanner.need_more_tokens(), pip._vendor.rich.live._RefreshThread.run(), pip._vendor.rich.progress._TrackThread.run(), and pip._vendor.rich.live._RefreshThread.stop().
elapsed
int pip._vendor.distlib.util.Progress.elapsed = 0
Definition at line 1321 of file util.py.
max
pip._vendor.distlib.util.Progress.max = maxval
Definition at line 1319 of file util.py.
min
pip._vendor.distlib.util.Progress.min = minval
Definition at line 1318 of file util.py.
started
pip._vendor.distlib.util.Progress.started = None
Definition at line 1320 of file util.py.
unknown
str pip._vendor.distlib.util.Progress.unknown = 'UNKNOWN' static
Definition at line 1314 of file util.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/distlib/util.py