Read&Watch: PIL.PngImagePlugin._fdat Class Reference
PIL.PngImagePlugin._fdat Class Reference
Public Member Functions
None __init__ (self, IO[bytes] fp, Callable[..., None] chunk, int seq_num)
None write (self, bytes data)
Public Attributes
fp = fp
chunk = chunk
seq_num = seq_num
Detailed Description
Definition at line 1135 of file PngImagePlugin.py.
Constructor & Destructor Documentation
__init__()
None PIL.PngImagePlugin._fdat.__init__ (self, IO[bytes] fp, Callable[..., None] chunk, int seq_num)
Definition at line 1138 of file PngImagePlugin.py.
    def __init__(self, fp: IO[bytes], chunk: Callable[..., None], seq_num: int) -> None:
        self.fp = fp
        self.chunk = chunk
        self.seq_num = seq_num
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
write()
None PIL.PngImagePlugin._fdat.write (self, bytes data)
Definition at line 1143 of file PngImagePlugin.py.
    def write(self, data: bytes) -> None:
        self.chunk(self.fp, b"fdAT", o32(self.seq_num), data)
        self.seq_num += 1
Referenced by pylint.reporters.ureports.text_writer.TextWriter.default_table(), pylint.reporters.ureports.text_writer.TextWriter.visit_text(), and pylint.reporters.ureports.base_writer.BaseWriter.writeln().
Member Data Documentation
chunk
PIL.PngImagePlugin._fdat.chunk = chunk
Definition at line 1140 of file PngImagePlugin.py.
fp
PIL.PngImagePlugin._fdat.fp = fp
Definition at line 1139 of file PngImagePlugin.py.
Referenced by PIL.PSDraw.PSDraw.begin_document(), PIL.PSDraw.PSDraw.end_document(), PIL.PSDraw.PSDraw.image(), PIL.PSDraw.PSDraw.line(), PIL.PSDraw.PSDraw.rectangle(), PIL.PSDraw.PSDraw.setfont(), and PIL.PSDraw.PSDraw.text().
seq_num
PIL.PngImagePlugin._fdat.seq_num = seq_num
Definition at line 1141 of file PngImagePlugin.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/PIL/PngImagePlugin.py