Read&Watch: pylint.checkers.variables.VariablesChecker Class Reference
pylint.checkers.variables.VariablesChecker Class Reference
Public Member Functions
None __init__ (self, PyLinter linter)
None visit_for (self, nodes.For node)
None leave_for (self, nodes.For node)
None visit_module (self, nodes.Module node)
None leave_module (self, nodes.Module node)
None visit_classdef (self, nodes.ClassDef node)
None leave_classdef (self, nodes.ClassDef node)
None visit_lambda (self, nodes.Lambda node)
None leave_lambda (self, nodes.Lambda _)
None visit_generatorexp (self, nodes.GeneratorExp node)
None leave_generatorexp (self, nodes.GeneratorExp _)
None visit_dictcomp (self, nodes.DictComp node)
None leave_dictcomp (self, nodes.DictComp _)
None visit_setcomp (self, nodes.SetComp node)
None leave_setcomp (self, nodes.SetComp _)
None visit_functiondef (self, nodes.FunctionDef node)
None leave_functiondef (self, nodes.FunctionDef node)
None visit_global (self, nodes.Global node)
None visit_assignname (self, nodes.AssignName node)
None visit_delname (self, nodes.DelName node)
None visit_name (self, nodes.Name|nodes.AssignName|nodes.DelName node)
None visit_excepthandler (self, nodes.ExceptHandler node)
None leave_excepthandler (self, nodes.ExceptHandler node)
None visit_import (self, nodes.Import node)
None visit_importfrom (self, nodes.ImportFrom node)
None visit_assign (self, nodes.Assign node)
None visit_listcomp (self, nodes.ListComp node)
None leave_listcomp (self, nodes.ListComp _)
None leave_assign (self, nodes.Assign node)
None leave_with (self, nodes.With node)
None visit_arguments (self, nodes.Arguments node)
None visit_subscript (self, nodes.Subscript node)
None visit_const (self, nodes.Const node)
Public Member Functions inherited from pylint.checkers.base_checker.BaseChecker
None __init__ (self, PyLinter linter)
bool __gt__ (self, Any other)
bool __eq__ (self, object other)
int __hash__ (self)
str __repr__ (self)
str __str__ (self)
str get_full_documentation (self, dict[str, MessageDefinitionTuple] msgs, Iterable[tuple[str, OptionDict, Any]] options, Sequence[tuple[str, str, ReportsCallable]] reports, str|None doc=None, str|None module=None, bool show_options=True)
None add_message (self, str msgid, int|None line=None, nodes.NodeNG|None node=None, Any args=None, Confidence|None confidence=None, int|None col_offset=None, int|None end_lineno=None, int|None end_col_offset=None)
None check_consistency (self)
MessageDefinition create_message_definition_from_tuple (self, str msgid, MessageDefinitionTuple msg_tuple)
list[MessageDefinition] messages (self)
None open (self)
None close (self)
Any get_map_data (self)
None reduce_map_data (self, PyLinter linter, list[Any] data)
Public Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
None __init__ (self, _ArgumentsManager arguments_manager)
Static Public Attributes
None visit_asyncfunctiondef = visit_functiondef
None leave_asyncfunctiondef = leave_functiondef
Static Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
str name = ""
dict msgs = {}
tuple reports = ()
bool enabled = True
Static Public Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
tuple options = ()
dict option_groups_descs = {}
Protected Member Functions
None _undefined_and_used_before_checker (self, nodes.Name node, nodes.NodeNG stmt)
bool _should_node_be_skipped (self, nodes.Name node, NamesConsumer consumer, bool is_start_index)
tuple[VariableVisitConsumerAction, list[nodes.NodeNG]|None] _check_consumer (self, nodes.Name node, nodes.NodeNG stmt, nodes.LocalsDictNodeNG frame, NamesConsumer current_consumer, str base_scope_type)
None _report_unfound_name_definition (self, nodes.NodeNG node, NamesConsumer current_consumer)
list[nodes.NodeNG] _filter_type_checking_import_from_consumption (self, nodes.NodeNG node, list[nodes.NodeNG] nodes_to_consume)
bool _analyse_fallback_blocks (self)
Iterable[str] _ignored_modules (self)
bool _allow_global_unused_variables (self)
bool _is_builtin (self, str name)
bool _ignore_class_scope (self, nodes.NodeNG node)
None _loopvar_name (self, astroid.Name node)
None _check_is_unused (self, str name, nodes.FunctionDef node, nodes.NodeNG stmt, set[str] global_names, Iterable[str] nonlocal_names, Iterable[str] comprehension_target_names)
re.Pattern[str]|re.Match[str]|None _is_name_ignored (self, nodes.NodeNG stmt, str name)
None _check_unused_arguments (self, str name, nodes.FunctionDef node, nodes.NodeNG stmt, list[str] argnames, Iterable[str] nonlocal_names)
None _check_late_binding_closure (self, nodes.Name node)
bool _should_ignore_redefined_builtin (self, nodes.NodeNG stmt)
bool _allowed_redefined_builtin (self, str name)
None _store_type_annotation_node (self, nodes.NodeNG type_annotation)
None _store_type_annotation_names (self, nodes.For|nodes.Assign|nodes.With node)
None _check_self_cls_assign (self, nodes.Assign node)
None _check_unpacking (self, InferenceResult inferred, nodes.Assign node, list[nodes.NodeNG] targets)
None _report_unbalanced_unpacking (self, nodes.NodeNG node, InferenceResult inferred, list[nodes.NodeNG] targets, int values_count, str details)
None _report_unpacking_non_sequence (self, nodes.NodeNG node, str details)
nodes.Module|None _check_module_attrs (self, _base_nodes.ImportNode node, nodes.Module module, list[str] module_names)
None _check_all (self, nodes.Module node, dict[str, list[nodes.NodeNG]] not_consumed)
None _check_globals (self, dict[str, nodes.NodeNG] not_consumed)
None _check_imports (self, dict[str, list[nodes.NodeNG]] not_consumed)
None _check_metaclasses (self, nodes.Module|nodes.FunctionDef node)
list[tuple[dict[str, list[nodes.NodeNG]], str]] _check_classdef_metaclasses (self, nodes.ClassDef klass, nodes.Module|nodes.FunctionDef parent_node)
int _inferred_iterable_length (self, nodes.Tuple|nodes.List iterable)
None _check_potential_index_error (self, nodes.Subscript node, nodes.NodeNG|None inferred_slice)
Protected Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
Any _option_value (self, str opt)
Iterator[ tuple[str, list[tuple[str, OptionDict, Any]]]|tuple[None, dict[str, list[tuple[str, OptionDict, Any]]]]] _options_by_section (self)
Iterator[tuple[str, OptionDict, Any]] _options_and_values (self, Options|None options=None)
Static Protected Member Functions
bool _defined_in_function_definition (nodes.NodeNG node, nodes.NodeNG frame)
bool _in_lambda_or_comprehension_body (nodes.NodeNG node, nodes.NodeNG frame)
tuple[bool, bool, bool] _is_variable_violation (nodes.Name node, nodes.NodeNG defnode, _base_nodes.Statement stmt, _base_nodes.Statement defstmt, nodes.LocalsDictNodeNG frame, nodes.LocalsDictNodeNG defframe, str base_scope_type, bool is_recursive_klass)
bool _maybe_used_and_assigned_at_once (_base_nodes.Statement defstmt)
bool _is_only_type_assignment (nodes.Name node, _base_nodes.Statement defstmt)
tuple[VariableVisitConsumerAction, list[nodes.NodeNG]|None] _is_first_level_self_reference (nodes.Name node, nodes.ClassDef defstmt, list[nodes.NodeNG] found_nodes)
bool _is_never_evaluated (nodes.NamedExpr defnode, nodes.IfExp defnode_parent)
bool _is_variable_annotation_in_function (nodes.NodeNG node)
bool _comprehension_between_frame_and_node (nodes.Name node)
int _get_value_length (nodes.NodeNG value_node)
list[nodes.NodeNG]|None _nodes_to_unpack (nodes.NodeNG node)
Protected Attributes
list _to_consume = []
list _type_annotation_names = []
list[ _except_handler_names_queue
dict[ _evaluated_type_checking_scopes
bool _postponed_evaluation_enabled = False
_ignored_modules
_allow_global_unused_variables
Protected Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
_arguments_manager = arguments_manager
Additional Inherited Members
Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
linter = linter
messages
Detailed Description
BaseChecker for variables.
Checks for
* unused variables / imports
* undefined variables
* redefinition of variable from builtins or from an outer scope or except handler
* use of variable before assignment
* __all__ consistency
* self/cls assignment
Definition at line 1217 of file variables.py.
Constructor & Destructor Documentation
__init__()
None pylint.checkers.variables.VariablesChecker.__init__ (self, PyLinter linter)
Definition at line 1319 of file variables.py.
    def __init__(self, linter: PyLinter) -> None:
        super().__init__(linter)
        self._to_consume: list[NamesConsumer] = []
        self._type_annotation_names: list[str] = []
        self._except_handler_names_queue: list[
            tuple[nodes.ExceptHandler, nodes.AssignName]
        ] = []
        """This is a queue, last in first out."""
        self._evaluated_type_checking_scopes: dict[
            str, list[nodes.LocalsDictNodeNG]
        ] = {}
        self._postponed_evaluation_enabled = False
References __init__().
Referenced by __init__().
Member Function Documentation
_allow_global_unused_variables()
bool pylint.checkers.variables.VariablesChecker._allow_global_unused_variables (self) protected
Definition at line 2174 of file variables.py.
    def _allow_global_unused_variables(self) -> bool:
        return bool(self.linter.config.allow_global_unused_variables)
References pylint.checkers.base_checker.BaseChecker.linter.
_allowed_redefined_builtin()
bool pylint.checkers.variables.VariablesChecker._allowed_redefined_builtin (self, str name) protected
Definition at line 2939 of file variables.py.
    def _allowed_redefined_builtin(self, name: str) -> bool:
        return name in self.linter.config.allowed_redefined_builtins
References pylint.checkers.base_checker.BaseChecker.linter.
Referenced by visit_functiondef().
_analyse_fallback_blocks()
bool pylint.checkers.variables.VariablesChecker._analyse_fallback_blocks (self) protected
Definition at line 2166 of file variables.py.
    def _analyse_fallback_blocks(self) -> bool:
        return bool(self.linter.config.analyse_fallback_blocks)
References pylint.checkers.base_checker.BaseChecker.linter.
Referenced by visit_import(), and visit_importfrom().
_check_all()
None pylint.checkers.variables.VariablesChecker._check_all (self, nodes.Module node, dict[str, list[nodes.NodeNG]] not_consumed) protected
Definition at line 3146 of file variables.py.
    ) -> None:
        try:
            assigned = next(node.igetattr("__all__"))
        except astroid.InferenceError:
            return
        if isinstance(assigned, util.UninferableBase):
            return
        if assigned.pytype() not in {"builtins.list", "builtins.tuple"}:
            line, col = assigned.tolineno, assigned.col_offset
            self.add_message("invalid-all-format", line=line, col_offset=col, node=node)
            return
        for elt in getattr(assigned, "elts", ()):
            try:
                elt_name = next(elt.infer())
            except astroid.InferenceError:
                continue
            if isinstance(elt_name, util.UninferableBase):
                continue
            if not elt_name.parent:
                continue
            if not isinstance(elt_name, nodes.Const) or not isinstance(
                elt_name.value, str
            ):
                self.add_message("invalid-all-object", args=elt.as_string(), node=elt)
                continue
            elt_name = elt_name.value
            # If elt is in not_consumed, remove it from not_consumed
            if elt_name in not_consumed:
                del not_consumed[elt_name]
                continue
            if elt_name not in node.locals:
                if not node.package:
                    self.add_message(
                        "undefined-all-variable", args=(elt_name,), node=elt
                    )
                else:
                    basename = os.path.splitext(node.file)[0]
                    if os.path.basename(basename) == "__init__":
                        name = node.name + "." + elt_name
                        try:
                            astroid.modutils.file_from_modpath(name.split("."))
                        except ImportError:
                            self.add_message(
                                "undefined-all-variable", args=(elt_name,), node=elt
                            )
                        except SyntaxError:
                            # don't yield a syntax-error warning,
                            # because it will be later yielded
                            # when the file will be checked
                            pass
References pylint.checkers.base_checker.BaseChecker.add_message(), and astroid.modutils.file_from_modpath().
Referenced by leave_module().
_check_classdef_metaclasses()
list[tuple[dict[str, list[nodes.NodeNG]], str]] pylint.checkers.variables.VariablesChecker._check_classdef_metaclasses (self, nodes.ClassDef klass, nodes.Module | nodes.FunctionDef parent_node) protected
Definition at line 3314 of file variables.py.
    ) -> list[tuple[dict[str, list[nodes.NodeNG]], str]]:
        if not klass._metaclass:
            # Skip if this class doesn't use explicitly a metaclass, but inherits it from ancestors
            return []
        consumed: list[tuple[dict[str, list[nodes.NodeNG]], str]] = []
        metaclass = klass.metaclass()
        name = ""
        if isinstance(klass._metaclass, nodes.Name):
            name = klass._metaclass.name
        elif isinstance(klass._metaclass, nodes.Attribute) and klass._metaclass.expr:
            attr = klass._metaclass.expr
            while not isinstance(attr, nodes.Name):
                attr = attr.expr
            name = attr.name
        elif isinstance(klass._metaclass, nodes.Call) and isinstance(
            klass._metaclass.func, nodes.Name
        ):
            name = klass._metaclass.func.name
        elif metaclass:
            name = metaclass.root().name
        found = False
        name = METACLASS_NAME_TRANSFORMS.get(name, name)
        if name:
            # check enclosing scopes starting from most local
            for scope_locals, _, _, _ in self._to_consume[::-1]:
                found_nodes = scope_locals.get(name, [])
                for found_node in found_nodes:
                    if found_node.lineno <= klass.lineno:
                        consumed.append((scope_locals, name))
                        found = True
                        break
            # Check parent scope
            nodes_in_parent_scope = parent_node.locals.get(name, [])
            for found_node_parent in nodes_in_parent_scope:
                if found_node_parent.lineno <= klass.lineno:
                    found = True
                    break
        if (
            not found
            and not metaclass
            and not (
                name in nodes.Module.scope_attrs
                or utils.is_builtin(name)
                or name in self.linter.config.additional_builtins
            )
        ):
            self.add_message("undefined-variable", node=klass, args=(name,))
        return consumed
References _to_consume, pylint.checkers.base_checker.BaseChecker.add_message(), and pylint.checkers.base_checker.BaseChecker.linter.
Referenced by _check_metaclasses().
_check_consumer()
tuple[VariableVisitConsumerAction, list[nodes.NodeNG] | None] pylint.checkers.variables.VariablesChecker._check_consumer (self, nodes.Name node, nodes.NodeNG stmt, nodes.LocalsDictNodeNG frame, NamesConsumer current_consumer, str base_scope_type) protected
Checks a consumer for conditions that should trigger messages.
Definition at line 1803 of file variables.py.
    ) -> tuple[VariableVisitConsumerAction, list[nodes.NodeNG] | None]:
        """Checks a consumer for conditions that should trigger messages."""
        # If the name has already been consumed, only check it's not a loop
        # variable used outside the loop.
        if node.name in current_consumer.consumed:
            # Avoid the case where there are homonyms inside function scope and
            # comprehension current scope (avoid bug #1731)
            if utils.is_func_decorator(current_consumer.node) or not isinstance(
                node, nodes.ComprehensionScope
            ):
                self._check_late_binding_closure(node)
                return (VariableVisitConsumerAction.RETURN, None)
        found_nodes = current_consumer.get_next_to_consume(node)
        if found_nodes is None:
            return (VariableVisitConsumerAction.CONTINUE, None)
        if not found_nodes:
            self._report_unfound_name_definition(node, current_consumer)
            # Mark for consumption any nodes added to consumed_uncertain by
            # get_next_to_consume() because they might not have executed.
            nodes_to_consume = current_consumer.consumed_uncertain[node.name]
            nodes_to_consume = self._filter_type_checking_import_from_consumption(
                node, nodes_to_consume
            )
            return (
                VariableVisitConsumerAction.RETURN,
                nodes_to_consume,
            )
        self._check_late_binding_closure(node)
        defnode = utils.assign_parent(found_nodes[0])
        defstmt = defnode.statement()
        defframe = defstmt.frame()
        # The class reuses itself in the class scope.
        is_recursive_klass: bool = (
            frame is defframe
            and defframe.parent_of(node)
            and isinstance(defframe, nodes.ClassDef)
            and node.name == defframe.name
        )
        if (
            is_recursive_klass
            and utils.get_node_first_ancestor_of_type(node, nodes.Lambda)
            and (
                not utils.is_default_argument(node)
                or node.scope().parent.scope() is not defframe
            )
        ):
            # Self-referential class references are fine in lambda's --
            # As long as they are not part of the default argument directly
            # under the scope of the parent self-referring class.
            # Example of valid default argument:
            # class MyName3:
            #     myattr = 1
            #     mylambda3 = lambda: lambda a=MyName3: a
            # Example of invalid default argument:
            # class MyName4:
            #     myattr = 1
            #     mylambda4 = lambda a=MyName4: lambda: a
            # If the above conditional is True,
            # there is no possibility of undefined-variable
            # Also do not consume class name
            # (since consuming blocks subsequent checks)
            # -- quit
            return (VariableVisitConsumerAction.RETURN, None)
        (
            maybe_before_assign,
            annotation_return,
            use_outer_definition,
        ) = self._is_variable_violation(
            node,
            defnode,
            stmt,
            defstmt,
            frame,
            defframe,
            base_scope_type,
            is_recursive_klass,
        )
        if use_outer_definition:
            return (VariableVisitConsumerAction.CONTINUE, None)
        if (
            maybe_before_assign
            and not utils.is_defined_before(node)
            and not astroid.are_exclusive(stmt, defstmt, ("NameError",))
        ):
            # Used and defined in the same place, e.g `x += 1` and `del x`
            defined_by_stmt = defstmt is stmt and isinstance(
                node, (nodes.DelName, nodes.AssignName)
            )
            if (
                is_recursive_klass
                or defined_by_stmt
                or annotation_return
                or isinstance(defstmt, nodes.Delete)
            ):
                if not utils.node_ignores_exception(node, NameError):
                    # Handle postponed evaluation of annotations
                    if not (
                        self._postponed_evaluation_enabled
                        and isinstance(
                            stmt,
                            (
                                nodes.AnnAssign,
                                nodes.FunctionDef,
                                nodes.Arguments,
                            ),
                        )
                        and node.name in node.root().locals
                    ):
                        if defined_by_stmt:
                            return (VariableVisitConsumerAction.CONTINUE, [node])
                        return (VariableVisitConsumerAction.CONTINUE, None)
            elif base_scope_type != "lambda":
                # E0601 may *not* occurs in lambda scope.
                # Skip postponed evaluation of annotations
                # and unevaluated annotations inside a function body
                if not (
                    self._postponed_evaluation_enabled
                    and isinstance(stmt, (nodes.AnnAssign, nodes.FunctionDef))
                ) and not (
                    isinstance(stmt, nodes.AnnAssign)
                    and utils.get_node_first_ancestor_of_type(stmt, nodes.FunctionDef)
                ):
                    self.add_message(
                        "used-before-assignment",
                        args=node.name,
                        node=node,
                        confidence=HIGH,
                    )
                    return (VariableVisitConsumerAction.RETURN, found_nodes)
            elif base_scope_type == "lambda":
                # E0601 can occur in class-level scope in lambdas, as in
                # the following example:
                #   class A:
                #      x = lambda attr: f + attr
                #      f = 42
                # We check lineno because doing the following is fine:
                #   class A:
                #      x = 42
                #      y = lambda attr: x + attr
                if (
                    isinstance(frame, nodes.ClassDef)
                    and node.name in frame.locals
                    and stmt.fromlineno <= defstmt.fromlineno
                ):
                    self.add_message(
                        "used-before-assignment",
                        args=node.name,
                        node=node,
                        confidence=HIGH,
                    )
        elif not self._is_builtin(node.name) and self._is_only_type_assignment(
            node, defstmt
        ):
            if node.scope().locals.get(node.name):
                self.add_message(
                    "used-before-assignment", args=node.name, node=node, confidence=HIGH
                )
            else:
                self.add_message(
                    "undefined-variable", args=node.name, node=node, confidence=HIGH
                )
            return (VariableVisitConsumerAction.RETURN, found_nodes)
        elif (
            isinstance(defstmt, nodes.ClassDef) and defnode not in defframe.type_params
        ):
            return self._is_first_level_self_reference(node, defstmt, found_nodes)
        elif isinstance(defnode, nodes.NamedExpr):
            if isinstance(defnode.parent, nodes.IfExp):
                if self._is_never_evaluated(defnode, defnode.parent):
                    self.add_message(
                        "undefined-variable",
                        args=node.name,
                        node=node,
                        confidence=INFERENCE,
                    )
                    return (VariableVisitConsumerAction.RETURN, found_nodes)
        return (VariableVisitConsumerAction.RETURN, found_nodes)
References _check_late_binding_closure(), _filter_type_checking_import_from_consumption(), pylint.checkers.refactoring.recommendation_checker.RecommendationChecker._is_builtin(), _is_builtin(), _is_first_level_self_reference(), _is_never_evaluated(), _is_only_type_assignment(), _is_variable_violation(), _postponed_evaluation_enabled, _report_unfound_name_definition(), and pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by _undefined_and_used_before_checker().
_check_globals()
None pylint.checkers.variables.VariablesChecker._check_globals (self, dict[str, nodes.NodeNG] not_consumed) protected
Definition at line 3202 of file variables.py.
    def _check_globals(self, not_consumed: dict[str, nodes.NodeNG]) -> None:
        if self._allow_global_unused_variables:
            return
        for name, node_lst in not_consumed.items():
            for node in node_lst:
                if in_type_checking_block(node):
                    continue
                self.add_message("unused-variable", args=(name,), node=node)
Referenced by leave_module().
_check_imports()
None pylint.checkers.variables.VariablesChecker._check_imports (self, dict[str, list[nodes.NodeNG]] not_consumed) protected
Definition at line 3212 of file variables.py.
    def _check_imports(self, not_consumed: dict[str, list[nodes.NodeNG]]) -> None:
        local_names = _fix_dot_imports(not_consumed)
        checked = set()
        unused_wildcard_imports: defaultdict[
            tuple[str, nodes.ImportFrom], list[str]
        ] = collections.defaultdict(list)
        for name, stmt in local_names:
            for imports in stmt.names:
                real_name = imported_name = imports[0]
                if imported_name == "*":
                    real_name = name
                as_name = imports[1]
                if real_name in checked:
                    continue
                if name not in (real_name, as_name):
                    continue
                checked.add(real_name)
                is_type_annotation_import = (
                    imported_name in self._type_annotation_names
                    or as_name in self._type_annotation_names
                )
                is_dummy_import = (
                    as_name
                    and self.linter.config.dummy_variables_rgx
                    and self.linter.config.dummy_variables_rgx.match(as_name)
                )
                if isinstance(stmt, nodes.Import) or (
                    isinstance(stmt, nodes.ImportFrom) and not stmt.modname
                ):
                    if isinstance(stmt, nodes.ImportFrom) and SPECIAL_OBJ.search(
                        imported_name
                    ):
                        # Filter special objects (__doc__, __all__) etc.,
                        # because they can be imported for exporting.
                        continue
                    if is_type_annotation_import or is_dummy_import:
                        # Most likely a typing import if it wasn't used so far.
                        # Also filter dummy variables.
                        continue
                    if as_name is None:
                        msg = f"import {imported_name}"
                    else:
                        msg = f"{imported_name} imported as {as_name}"
                    if not in_type_checking_block(stmt):
                        self.add_message("unused-import", args=msg, node=stmt)
                elif isinstance(stmt, nodes.ImportFrom) and stmt.modname != FUTURE:
                    if SPECIAL_OBJ.search(imported_name):
                        # Filter special objects (__doc__, __all__) etc.,
                        # because they can be imported for exporting.
                        continue
                    if _is_from_future_import(stmt, name):
                        # Check if the name is in fact loaded from a
                        # __future__ import in another module.
                        continue
                    if is_type_annotation_import or is_dummy_import:
                        # Most likely a typing import if it wasn't used so far.
                        # Also filter dummy variables.
                        continue
                    if imported_name == "*":
                        unused_wildcard_imports[(stmt.modname, stmt)].append(name)
                    else:
                        if as_name is None:
                            msg = f"{imported_name} imported from {stmt.modname}"
                        else:
                            msg = f"{imported_name} imported from {stmt.modname} as {as_name}"
                        if not in_type_checking_block(stmt):
                            self.add_message("unused-import", args=msg, node=stmt)
        # Construct string for unused-wildcard-import message
        for module, unused_list in unused_wildcard_imports.items():
            if len(unused_list) == 1:
                arg_string = unused_list[0]
            else:
                arg_string = (
                    f"{', '.join(i for i in unused_list[:-1])} and {unused_list[-1]}"
                )
            self.add_message(
                "unused-wildcard-import", args=(arg_string, module[0]), node=module[1]
            )
        del self._to_consume
References pylint.checkers.variables._fix_dot_imports(), pylint.checkers.variables._is_from_future_import(), _to_consume, _type_annotation_names, pylint.checkers.base_checker.BaseChecker.add_message(), and pylint.checkers.base_checker.BaseChecker.linter.
Referenced by leave_module().
_check_is_unused()
None pylint.checkers.variables.VariablesChecker._check_is_unused (self, str name, nodes.FunctionDef node, nodes.NodeNG stmt, set[str] global_names, Iterable[str] nonlocal_names, Iterable[str] comprehension_target_names) protected
Definition at line 2711 of file variables.py.
    ) -> None:
        # Ignore some special names specified by user configuration.
        if self._is_name_ignored(stmt, name):
            return
        # Ignore names that were added dynamically to the Function scope
        if (
            isinstance(node, nodes.FunctionDef)
            and name == "__class__"
            and len(node.locals["__class__"]) == 1
            and isinstance(node.locals["__class__"][0], nodes.ClassDef)
        ):
            return
        # Ignore names imported by the global statement.
        if isinstance(stmt, (nodes.Global, nodes.Import, nodes.ImportFrom)):
            # Detect imports, assigned to global statements.
            if global_names and _import_name_is_global(stmt, global_names):
                return
        # Ignore names in comprehension targets
        if name in comprehension_target_names:
            return
        # Ignore names in string literal type annotation.
        if name in self._type_annotation_names:
            return
        argnames = node.argnames()
        # Care about functions with unknown argument (builtins)
        if name in argnames:
            if node.name == "__new__":
                is_init_def = False
                # Look for the `__init__` method in all the methods of the same class.
                for n in node.parent.get_children():
                    is_init_def = hasattr(n, "name") and (n.name == "__init__")
                    if is_init_def:
                        break
                # Ignore unused arguments check for `__new__` if `__init__` is defined.
                if is_init_def:
                    return
            self._check_unused_arguments(name, node, stmt, argnames, nonlocal_names)
        else:
            if stmt.parent and isinstance(
                stmt.parent, (nodes.Assign, nodes.AnnAssign, nodes.Tuple, nodes.For)
            ):
                if name in nonlocal_names:
                    return
            qname = asname = None
            if isinstance(stmt, (nodes.Import, nodes.ImportFrom)):
                # Need the complete name, which we don't have in .locals.
                if len(stmt.names) > 1:
                    import_names = next(
                        (names for names in stmt.names if name in names), None
                    )
                else:
                    import_names = stmt.names[0]
                if import_names:
                    qname, asname = import_names
                    name = asname or qname
            if _has_locals_call_after_node(stmt, node.scope()):
                message_name = "possibly-unused-variable"
            else:
                if isinstance(stmt, nodes.Import):
                    if asname is not None:
                        msg = f"{qname} imported as {asname}"
                    else:
                        msg = f"import {name}"
                    self.add_message("unused-import", args=msg, node=stmt)
                    return
                if isinstance(stmt, nodes.ImportFrom):
                    if asname is not None:
                        msg = f"{qname} imported from {stmt.modname} as {asname}"
                    else:
                        msg = f"{name} imported from {stmt.modname}"
                    self.add_message("unused-import", args=msg, node=stmt)
                    return
                message_name = "unused-variable"
            if isinstance(stmt, nodes.FunctionDef) and stmt.decorators:
                return
            # Don't check function stubs created only for type information
            if utils.is_overload_stub(node):
                return
            # Special case for exception variable
            if isinstance(stmt.parent, nodes.ExceptHandler) and any(
                n.name == name for n in stmt.parent.nodes_of_class(nodes.Name)
            ):
                return
            self.add_message(message_name, args=name, node=stmt)
References _check_unused_arguments(), pylint.checkers.variables._has_locals_call_after_node(), pylint.checkers.variables._import_name_is_global(), _is_name_ignored(), _type_annotation_names, and pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by leave_functiondef().
_check_late_binding_closure()
None pylint.checkers.variables.VariablesChecker._check_late_binding_closure (self, nodes.Name node) protected
Check whether node is a cell var that is assigned within a containing loop.
Special cases where we don't care about the error:
1. When the node's function is immediately called, e.g. (lambda: i)()
2. When the node's function is returned from within the loop, e.g. return lambda: i
Definition at line 2884 of file variables.py.
    def _check_late_binding_closure(self, node: nodes.Name) -> None:
        """Check whether node is a cell var that is assigned within a containing loop.
        Special cases where we don't care about the error:
        1. When the node's function is immediately called, e.g. (lambda: i)()
        2. When the node's function is returned from within the loop, e.g. return lambda: i
        """
        if not self.linter.is_message_enabled("cell-var-from-loop"):
            return
        node_scope = node.frame()
        # If node appears in a default argument expression,
        # look at the next enclosing frame instead
        if utils.is_default_argument(node, node_scope):
            node_scope = node_scope.parent.frame()
        # Check if node is a cell var
        if (
            not isinstance(node_scope, (nodes.Lambda, nodes.FunctionDef))
            or node.name in node_scope.locals
        ):
            return
        assign_scope, stmts = node.lookup(node.name)
        if not stmts or not assign_scope.parent_of(node_scope):
            return
        if utils.is_comprehension(assign_scope):
            self.add_message("cell-var-from-loop", node=node, args=node.name)
        else:
            # Look for an enclosing For loop.
            # Currently, we only consider the first assignment
            assignment_node = stmts[0]
            maybe_for = assignment_node
            while maybe_for and not isinstance(maybe_for, nodes.For):
                if maybe_for is assign_scope:
                    break
                maybe_for = maybe_for.parent
            else:
                if (
                    maybe_for
                    and maybe_for.parent_of(node_scope)
                    and not utils.is_being_called(node_scope)
                    and node_scope.parent
                    and not isinstance(node_scope.statement(), nodes.Return)
                ):
                    self.add_message("cell-var-from-loop", node=node, args=node.name)
References pylint.checkers.base_checker.BaseChecker.add_message(), and pylint.checkers.base_checker.BaseChecker.linter.
Referenced by _check_consumer().
_check_metaclasses()
None pylint.checkers.variables.VariablesChecker._check_metaclasses (self, nodes.Module | nodes.FunctionDef node) protected
Update consumption analysis for metaclasses.
Definition at line 3301 of file variables.py.
    def _check_metaclasses(self, node: nodes.Module | nodes.FunctionDef) -> None:
        """Update consumption analysis for metaclasses."""
        consumed: list[tuple[dict[str, list[nodes.NodeNG]], str]] = []
        for child_node in node.get_children():
            if isinstance(child_node, nodes.ClassDef):
                consumed.extend(self._check_classdef_metaclasses(child_node, node))
        # Pop the consumed items, in order to avoid having
        # unused-import and unused-variable false positives
        for scope_locals, name in consumed:
            scope_locals.pop(name, None)
References _check_classdef_metaclasses().
Referenced by leave_functiondef(), and leave_module().
_check_module_attrs()
nodes.Module | None pylint.checkers.variables.VariablesChecker._check_module_attrs (self, _base_nodes.ImportNode node, nodes.Module module, list[str] module_names) protected
Check that module_names (list of string) are accessible through the
given module, if the latest access name corresponds to a module, return it.
Definition at line 3105 of file variables.py.
    ) -> nodes.Module | None:
        """Check that module_names (list of string) are accessible through the
        given module, if the latest access name corresponds to a module, return it.
        """
        while module_names:
            name = module_names.pop(0)
            if name == "__dict__":
                module = None
                break
            try:
                module = module.getattr(name)[0]
                if not isinstance(module, nodes.Module):
                    module = next(module.infer())
                    if not isinstance(module, nodes.Module):
                        return None
            except astroid.NotFoundError:
                # Unable to import `name` from `module`. Since `name` may itself be a
                # module, we first check if it matches the ignored modules.
                if is_module_ignored(f"{module.qname()}.{name}", self._ignored_modules):
                    return None
                self.add_message(
                    "no-name-in-module", args=(name, module.name), node=node
                )
                return None
            except astroid.InferenceError:
                return None
        if module_names:
            modname = module.name if module else "__dict__"
            self.add_message(
                "no-name-in-module", node=node, args=(".".join(module_names), modname)
            )
            return None
        if isinstance(module, nodes.Module):
            return module
        return None
Referenced by visit_import(), and visit_importfrom().
_check_potential_index_error()
None pylint.checkers.variables.VariablesChecker._check_potential_index_error (self, nodes.Subscript node, nodes.NodeNG | None inferred_slice) protected
Check for the potential-index-error message.
Definition at line 3386 of file variables.py.
    ) -> None:
        """Check for the potential-index-error message."""
        # Currently we only check simple slices of a single integer
        if not isinstance(inferred_slice, nodes.Const) or not isinstance(
            inferred_slice.value, int
        ):
            return
        # If the node.value is a Tuple or List without inference it is defined in place
        if isinstance(node.value, (nodes.Tuple, nodes.List)):
            # Add 1 because iterables are 0-indexed
            if self._inferred_iterable_length(node.value) < inferred_slice.value + 1:
                self.add_message(
                    "potential-index-error", node=node, confidence=INFERENCE
                )
            return
References _inferred_iterable_length(), and pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_subscript().
_check_self_cls_assign()
None pylint.checkers.variables.VariablesChecker._check_self_cls_assign (self, nodes.Assign node) protected
Check that self/cls don't get assigned.
Definition at line 2987 of file variables.py.
    def _check_self_cls_assign(self, node: nodes.Assign) -> None:
        """Check that self/cls don't get assigned."""
        assign_names: set[str | None] = set()
        for target in node.targets:
            if isinstance(target, nodes.AssignName):
                assign_names.add(target.name)
            elif isinstance(target, nodes.Tuple):
                assign_names.update(
                    elt.name for elt in target.elts if isinstance(elt, nodes.AssignName)
                )
        scope = node.scope()
        nonlocals_with_same_name = node.scope().parent and any(
            child for child in scope.body if isinstance(child, nodes.Nonlocal)
        )
        if nonlocals_with_same_name:
            scope = node.scope().parent.scope()
        if not (
            isinstance(scope, nodes.FunctionDef)
            and scope.is_method()
            and "builtins.staticmethod" not in scope.decoratornames()
        ):
            return
        argument_names = scope.argnames()
        if not argument_names:
            return
        self_cls_name = argument_names[0]
        if self_cls_name in assign_names:
            self.add_message("self-cls-assignment", node=node, args=(self_cls_name,))
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_assign().
_check_unpacking()
None pylint.checkers.variables.VariablesChecker._check_unpacking (self, InferenceResult inferred, nodes.Assign node, list[nodes.NodeNG] targets) protected
Check for unbalanced tuple unpacking
and unpacking non sequences.
Definition at line 3017 of file variables.py.
    ) -> None:
        """Check for unbalanced tuple unpacking
        and unpacking non sequences.
        """
        if utils.is_inside_abstract_class(node):
            return
        if utils.is_comprehension(node):
            return
        if isinstance(inferred, util.UninferableBase):
            return
        if (
            isinstance(inferred.parent, nodes.Arguments)
            and isinstance(node.value, nodes.Name)
            and node.value.name == inferred.parent.vararg
        ):
            # Variable-length argument, we can't determine the length.
            return
        # Attempt to check unpacking is properly balanced
        values = self._nodes_to_unpack(inferred)
        details = _get_unpacking_extra_info(node, inferred)
        if values is not None:
            if len(targets) != len(values):
                self._report_unbalanced_unpacking(
                    node, inferred, targets, len(values), details
                )
        # attempt to check unpacking may be possible (i.e. RHS is iterable)
        elif not utils.is_iterable(inferred):
            self._report_unpacking_non_sequence(node, details)
References pylint.checkers.variables._get_unpacking_extra_info(), _nodes_to_unpack(), _report_unbalanced_unpacking(), and _report_unpacking_non_sequence().
Referenced by visit_assign().
_check_unused_arguments()
None pylint.checkers.variables.VariablesChecker._check_unused_arguments (self, str name, nodes.FunctionDef node, nodes.NodeNG stmt, list[str] argnames, Iterable[str] nonlocal_names) protected
Definition at line 2831 of file variables.py.
    ) -> None:
        is_method = node.is_method()
        klass = node.parent.frame()
        if is_method and isinstance(klass, nodes.ClassDef):
            confidence = (
                INFERENCE if utils.has_known_bases(klass) else INFERENCE_FAILURE
            )
        else:
            confidence = HIGH
        if is_method:
            # Don't warn for the first argument of a (non static) method
            if node.type != "staticmethod" and name == argnames[0]:
                return
            # Don't warn for argument of an overridden method
            overridden = overridden_method(klass, node.name)
            if overridden is not None and name in overridden.argnames():
                return
            if node.name in utils.PYMETHODS and node.name not in (
                "__init__",
                "__new__",
            ):
                return
        # Don't check callback arguments
        if any(
            node.name.startswith(cb) or node.name.endswith(cb)
            for cb in self.linter.config.callbacks
        ):
            return
        # Don't check arguments of singledispatch.register function.
        if utils.is_registered_in_singledispatch_function(node):
            return
        # Don't check function stubs created only for type information
        if utils.is_overload_stub(node):
            return
        # Don't check protocol classes
        if utils.is_protocol_class(klass):
            return
        if name in nonlocal_names:
            return
        self.add_message("unused-argument", args=name, node=stmt, confidence=confidence)
References pylint.checkers.base_checker.BaseChecker.add_message(), and pylint.checkers.base_checker.BaseChecker.linter.
Referenced by _check_is_unused().
_comprehension_between_frame_and_node()
bool pylint.checkers.variables.VariablesChecker._comprehension_between_frame_and_node (nodes.Name node) static protected
Return True if a ComprehensionScope intervenes between `node` and its
frame.
Definition at line 2943 of file variables.py.
    def _comprehension_between_frame_and_node(node: nodes.Name) -> bool:
        """Return True if a ComprehensionScope intervenes between `node` and its
        frame.
        """
        closest_comprehension_scope = utils.get_node_first_ancestor_of_type(
            node, nodes.ComprehensionScope
        )
        return closest_comprehension_scope is not None and node.frame().parent_of(
            closest_comprehension_scope
        )
_defined_in_function_definition()
bool pylint.checkers.variables.VariablesChecker._defined_in_function_definition (nodes.NodeNG node, nodes.NodeNG frame) static protected
Definition at line 2178 of file variables.py.
    ) -> bool:
        in_annotation_or_default_or_decorator = False
        if isinstance(frame, nodes.FunctionDef) and node.statement() is frame:
            in_annotation_or_default_or_decorator = (
                (
                    node in frame.args.annotations
                    or node in frame.args.posonlyargs_annotations
                    or node in frame.args.kwonlyargs_annotations
                    or node is frame.args.varargannotation
                    or node is frame.args.kwargannotation
                )
                or frame.args.parent_of(node)
                or (frame.decorators and frame.decorators.parent_of(node))
                or (
                    frame.returns
                    and (node is frame.returns or frame.returns.parent_of(node))
                )
            )
        return in_annotation_or_default_or_decorator
Referenced by _ignore_class_scope(), and _should_node_be_skipped().
_filter_type_checking_import_from_consumption()
list[nodes.NodeNG] pylint.checkers.variables.VariablesChecker._filter_type_checking_import_from_consumption (self, nodes.NodeNG node, list[nodes.NodeNG] nodes_to_consume) protected
Do not consume type-checking import node as used-before-assignment
may invoke in different scopes.
Definition at line 2043 of file variables.py.
    ) -> list[nodes.NodeNG]:
        """Do not consume type-checking import node as used-before-assignment
        may invoke in different scopes.
        """
        type_checking_import = next(
            (
                n
                for n in nodes_to_consume
                if isinstance(n, (nodes.Import, nodes.ImportFrom))
                and in_type_checking_block(n)
            ),
            None,
        )
        # If used-before-assignment reported for usage of type checking import
        # keep track of its scope
        if type_checking_import and not self._is_variable_annotation_in_function(node):
            self._evaluated_type_checking_scopes.setdefault(node.name, []).append(
                node.scope()
            )
        nodes_to_consume = [n for n in nodes_to_consume if n != type_checking_import]
        return nodes_to_consume
References _evaluated_type_checking_scopes, and _is_variable_annotation_in_function().
Referenced by _check_consumer().
_get_value_length()
int pylint.checkers.variables.VariablesChecker._get_value_length (nodes.NodeNG value_node) static protected
Definition at line 3051 of file variables.py.
    def _get_value_length(value_node: nodes.NodeNG) -> int:
        value_subnodes = VariablesChecker._nodes_to_unpack(value_node)
        if value_subnodes is not None:
            return len(value_subnodes)
        if isinstance(value_node, nodes.Const) and isinstance(
            value_node.value, (str, bytes)
        ):
            return len(value_node.value)
        if isinstance(value_node, nodes.Subscript):
            step = value_node.slice.step or 1
            splice_range = value_node.slice.upper.value - value_node.slice.lower.value
            splice_length = int(math.ceil(splice_range / step))
            return splice_length
        return 1
Referenced by visit_for().
_ignore_class_scope()
bool pylint.checkers.variables.VariablesChecker._ignore_class_scope (self, nodes.NodeNG node) protected
Return True if the node is in a local class scope, as an assignment.
Detect if we are in a local class scope, as an assignment.
For example, the following is fair game.
class A:
   b = 1
   c = lambda b=b: b * b
class B:
   tp = 1
   def func(self, arg: tp):
       ...
class C:
   tp = 2
   def func(self, arg=tp):
       ...
class C:
   class Tp:
       pass
   class D(Tp):
       ...
Definition at line 2523 of file variables.py.
    def _ignore_class_scope(self, node: nodes.NodeNG) -> bool:
        """Return True if the node is in a local class scope, as an assignment.
        Detect if we are in a local class scope, as an assignment.
        For example, the following is fair game.
        class A:
           b = 1
           c = lambda b=b: b * b
        class B:
           tp = 1
           def func(self, arg: tp):
               ...
        class C:
           tp = 2
           def func(self, arg=tp):
               ...
        class C:
           class Tp:
               pass
           class D(Tp):
               ...
        """
        name = node.name
        frame = node.statement().scope()
        in_annotation_or_default_or_decorator = self._defined_in_function_definition(
            node, frame
        )
        in_ancestor_list = utils.is_ancestor_name(frame, node)
        if in_annotation_or_default_or_decorator or in_ancestor_list:
            frame_locals = frame.parent.scope().locals
        else:
            frame_locals = frame.locals
        return not (
            (isinstance(frame, nodes.ClassDef) or in_annotation_or_default_or_decorator)
            and not self._in_lambda_or_comprehension_body(node, frame)
            and name in frame_locals
        )
References _defined_in_function_definition(), and _in_lambda_or_comprehension_body().
Referenced by _should_node_be_skipped().
_ignored_modules()
Iterable[str] pylint.checkers.variables.VariablesChecker._ignored_modules (self) protected
Definition at line 2170 of file variables.py.
    def _ignored_modules(self) -> Iterable[str]:
        return self.linter.config.ignored_modules  # type: ignore[no-any-return]
References pylint.checkers.base_checker.BaseChecker.linter.
_in_lambda_or_comprehension_body()
bool pylint.checkers.variables.VariablesChecker._in_lambda_or_comprehension_body (nodes.NodeNG node, nodes.NodeNG frame) static protected
Return True if node within a lambda/comprehension body (or similar) and thus
should not have access to class attributes in frame.
Definition at line 2201 of file variables.py.
    ) -> bool:
        """Return True if node within a lambda/comprehension body (or similar) and thus
        should not have access to class attributes in frame.
        """
        child = node
        parent = node.parent
        while parent is not None:
            if parent is frame:
                return False
            if isinstance(parent, nodes.Lambda) and child is not parent.args:
                # Body of lambda should not have access to class attributes.
                return True
            if isinstance(parent, nodes.Comprehension) and child is not parent.iter:
                # Only iter of list/set/dict/generator comprehension should have access.
                return True
            if isinstance(parent, nodes.ComprehensionScope) and not (
                parent.generators and child is parent.generators[0]
            ):
                # Body of list/set/dict/generator comprehension should not have access to class attributes.
                # Furthermore, only the first generator (if multiple) in comprehension should have access.
                return True
            child = parent
            parent = parent.parent
        return False
Referenced by _ignore_class_scope().
_inferred_iterable_length()
int pylint.checkers.variables.VariablesChecker._inferred_iterable_length (self, nodes.Tuple | nodes.List iterable) protected
Definition at line 3373 of file variables.py.
    def _inferred_iterable_length(self, iterable: nodes.Tuple | nodes.List) -> int:
        length = 0
        for elt in iterable.elts:
            if not isinstance(elt, nodes.Starred):
                length += 1
                continue
            unpacked = utils.safe_infer(elt.value)
            if isinstance(unpacked, nodes.BaseContainer):
                length += len(unpacked.elts)
            else:
                length += 1
        return length
Referenced by _check_potential_index_error().
_is_builtin()
bool pylint.checkers.variables.VariablesChecker._is_builtin (self, str name) protected
Definition at line 2416 of file variables.py.
    def _is_builtin(self, name: str) -> bool:
        return name in self.linter.config.additional_builtins or utils.is_builtin(name)
References pylint.checkers.base_checker.BaseChecker.linter.
Referenced by _check_consumer(), and _report_unfound_name_definition().
_is_first_level_self_reference()
tuple[VariableVisitConsumerAction, list[nodes.NodeNG] | None] pylint.checkers.variables.VariablesChecker._is_first_level_self_reference (nodes.Name node, nodes.ClassDef defstmt, list[nodes.NodeNG] found_nodes) static protected
Check if a first level method's annotation or default values
refers to its own class, and return a consumer action.
Definition at line 2478 of file variables.py.
    ) -> tuple[VariableVisitConsumerAction, list[nodes.NodeNG] | None]:
        """Check if a first level method's annotation or default values
        refers to its own class, and return a consumer action.
        """
        if node.frame().parent == defstmt and node.statement() == node.frame():
            # Check if used as type annotation
            # Break if postponed evaluation is enabled
            if utils.is_node_in_type_annotation_context(node):
                if not utils.is_postponed_evaluation_enabled(node):
                    return (VariableVisitConsumerAction.CONTINUE, None)
                return (VariableVisitConsumerAction.RETURN, None)
            # Check if used as default value by calling the class
            if isinstance(node.parent, nodes.Call) and isinstance(
                node.parent.parent, nodes.Arguments
            ):
                return (VariableVisitConsumerAction.CONTINUE, None)
        return (VariableVisitConsumerAction.RETURN, found_nodes)
Referenced by _check_consumer().
_is_name_ignored()
re.Pattern[str] | re.Match[str] | None pylint.checkers.variables.VariablesChecker._is_name_ignored (self, nodes.NodeNG stmt, str name) protected
Definition at line 2814 of file variables.py.
    ) -> re.Pattern[str] | re.Match[str] | None:
        authorized_rgx = self.linter.config.dummy_variables_rgx
        if (
            isinstance(stmt, nodes.AssignName)
            and isinstance(stmt.parent, nodes.Arguments)
            or isinstance(stmt, nodes.Arguments)
        ):
            regex: re.Pattern[str] = self.linter.config.ignored_argument_names
        else:
            regex = authorized_rgx
        # See https://stackoverflow.com/a/47007761/2519059 to
        # understand what this function return. Please do NOT use
        # this elsewhere, this is confusing for no benefit
        return regex and regex.match(name)
References pylint.checkers.base_checker.BaseChecker.linter.
Referenced by _check_is_unused(), and visit_functiondef().
_is_never_evaluated()
bool pylint.checkers.variables.VariablesChecker._is_never_evaluated (nodes.NamedExpr defnode, nodes.IfExp defnode_parent) static protected
Check if a NamedExpr is inside a side of if ... else that never
gets evaluated.
Definition at line 2499 of file variables.py.
    ) -> bool:
        """Check if a NamedExpr is inside a side of if ... else that never
        gets evaluated.
        """
        inferred_test = utils.safe_infer(defnode_parent.test)
        if isinstance(inferred_test, nodes.Const):
            if inferred_test.value is True and defnode == defnode_parent.orelse:
                return True
            if inferred_test.value is False and defnode == defnode_parent.body:
                return True
        return False
Referenced by _check_consumer().
_is_only_type_assignment()
bool pylint.checkers.variables.VariablesChecker._is_only_type_assignment (nodes.Name node, _base_nodes.Statement defstmt) static protected
Check if variable only gets assigned a type and never a value.
Definition at line 2420 of file variables.py.
    ) -> bool:
        """Check if variable only gets assigned a type and never a value."""
        if not isinstance(defstmt, nodes.AnnAssign) or defstmt.value:
            return False
        defstmt_frame = defstmt.frame()
        node_frame = node.frame()
        parent = node
        while parent is not defstmt_frame.parent:
            parent_scope = parent.scope()
            # Find out if any nonlocals receive values in nested functions
            for inner_func in parent_scope.nodes_of_class(nodes.FunctionDef):
                if inner_func is parent_scope:
                    continue
                if any(
                    node.name in nl.names
                    for nl in inner_func.nodes_of_class(nodes.Nonlocal)
                ) and any(
                    node.name == an.name
                    for an in inner_func.nodes_of_class(nodes.AssignName)
                ):
                    return False
            local_refs = parent_scope.locals.get(node.name, [])
            for ref_node in local_refs:
                # If local ref is in the same frame as our node, but on a later lineno
                # we don't actually care about this local ref.
                # Local refs are ordered, so we break.
                #     print(var)
                #     var = 1  # <- irrelevant
                if defstmt_frame == node_frame and ref_node.lineno > node.lineno:
                    break
                # If the parent of the local reference is anything but an AnnAssign
                # Or if the AnnAssign adds a value the variable will now have a value
                #     var = 1  # OR
                #     var: int = 1
                if (
                    not isinstance(ref_node.parent, nodes.AnnAssign)
                    or ref_node.parent.value
                ) and not (
                    # EXCEPTION: will not have a value if a self-referencing named expression
                    # var: int
                    # if (var := var * var)  <-- "var" still undefined
                    isinstance(ref_node.parent, nodes.NamedExpr)
                    and any(
                        anc is ref_node.parent.value for anc in node.node_ancestors()
                    )
                ):
                    return False
            parent = parent_scope.parent
        return True
Referenced by _check_consumer().
_is_variable_annotation_in_function()
bool pylint.checkers.variables.VariablesChecker._is_variable_annotation_in_function (nodes.NodeNG node) static protected
Definition at line 2514 of file variables.py.
    def _is_variable_annotation_in_function(node: nodes.NodeNG) -> bool:
        is_annotation = utils.get_node_first_ancestor_of_type(node, nodes.AnnAssign)
        return (
            is_annotation
            and utils.get_node_first_ancestor_of_type(  # type: ignore[return-value]
                is_annotation, nodes.FunctionDef
            )
        )
Referenced by _filter_type_checking_import_from_consumption(), and _report_unfound_name_definition().
_is_variable_violation()
tuple[bool, bool, bool] pylint.checkers.variables.VariablesChecker._is_variable_violation (nodes.Name node, nodes.NodeNG defnode, _base_nodes.Statement stmt, _base_nodes.Statement defstmt, nodes.LocalsDictNodeNG frame, nodes.LocalsDictNodeNG defframe, str base_scope_type, bool is_recursive_klass) static protected
Definition at line 2229 of file variables.py.
    ) -> tuple[bool, bool, bool]:
        maybe_before_assign = True
        annotation_return = False
        use_outer_definition = False
        if frame is not defframe:
            maybe_before_assign = _detect_global_scope(node, frame, defframe)
        elif defframe.parent is None:
            # we are at the module level, check the name is not
            # defined in builtins
            if (
                node.name in defframe.scope_attrs
                or astroid.builtin_lookup(node.name)[1]
            ):
                maybe_before_assign = False
        else:
            # we are in a local scope, check the name is not
            # defined in global or builtin scope
            # skip this lookup if name is assigned later in function scope/lambda
            # Note: the node.frame() is not the same as the `frame` argument which is
            # equivalent to frame.statement().scope()
            forbid_lookup = (
                isinstance(frame, nodes.FunctionDef)
                or isinstance(node.frame(), nodes.Lambda)
            ) and _assigned_locally(node)
            if not forbid_lookup and defframe.root().lookup(node.name)[1]:
                maybe_before_assign = False
                use_outer_definition = stmt == defstmt and not isinstance(
                    defnode, nodes.Comprehension
                )
            # check if we have a nonlocal
            elif node.name in defframe.locals:
                maybe_before_assign = not any(
                    isinstance(child, nodes.Nonlocal) and node.name in child.names
                    for child in defframe.get_children()
                )
        if (
            base_scope_type == "lambda"
            and isinstance(frame, nodes.ClassDef)
            and node.name in frame.locals
        ):
            # This rule verifies that if the definition node of the
            # checked name is an Arguments node and if the name
            # is used a default value in the arguments defaults
            # and the actual definition of the variable label
            # is happening before the Arguments definition.
            #
            # bar = None
            # foo = lambda bar=bar: bar
            #
            # In this case, maybe_before_assign should be False, otherwise
            # it should be True.
            maybe_before_assign = not (
                isinstance(defnode, nodes.Arguments)
                and node in defnode.defaults
                and frame.locals[node.name][0].fromlineno < defstmt.fromlineno
            )
        elif isinstance(defframe, nodes.ClassDef) and isinstance(
            frame, nodes.FunctionDef
        ):
            # Special rule for function return annotations,
            # using a name defined earlier in the class containing the function.
            if node is frame.returns and defframe.parent_of(frame.returns):
                annotation_return = True
                if frame.returns.name in defframe.locals:
                    definition = defframe.locals[node.name][0]
                    if definition.lineno is None or definition.lineno < frame.lineno:
                        # Detect class assignments with a name defined earlier in the
                        # class. In this case, no warning should be raised.
                        maybe_before_assign = False
                    else:
                        maybe_before_assign = True
                else:
                    maybe_before_assign = True
            if isinstance(node.parent, nodes.Arguments):
                maybe_before_assign = stmt.fromlineno <= defstmt.fromlineno
        elif is_recursive_klass:
            maybe_before_assign = True
        else:
            maybe_before_assign = (
                maybe_before_assign and stmt.fromlineno <= defstmt.fromlineno
            )
            if maybe_before_assign and stmt.fromlineno == defstmt.fromlineno:
                if (
                    isinstance(defframe, nodes.FunctionDef)
                    and frame is defframe
                    and defframe.parent_of(node)
                    and (
                        defnode in defframe.type_params
                        # Single statement function, with the statement on the
                        # same line as the function definition
                        or stmt is not defstmt
                    )
                ):
                    maybe_before_assign = False
                elif (
                    isinstance(defstmt, NODES_WITH_VALUE_ATTR)
                    and VariablesChecker._maybe_used_and_assigned_at_once(defstmt)
                    and frame is defframe
                    and defframe.parent_of(node)
                    and stmt is defstmt
                ):
                    # Single statement if, with assignment expression on same
                    # line as assignment
                    # x = b if (b := True) else False
                    maybe_before_assign = False
                elif (
                    isinstance(  # pylint: disable=too-many-boolean-expressions
                        defnode, nodes.NamedExpr
                    )
                    and frame is defframe
                    and defframe.parent_of(stmt)
                    and stmt is defstmt
                    and (
                        (
                            defnode.lineno == node.lineno
                            and defnode.col_offset < node.col_offset
                        )
                        or (defnode.lineno < node.lineno)
                    )
                ):
                    # Relation of a name to the same name in a named expression
                    # Could be used before assignment if self-referencing:
                    # (b := b)
                    # Otherwise, safe if used after assignment:
                    # (b := 2) and b
                    maybe_before_assign = defnode.value is node or any(
                        anc is defnode.value for anc in node.node_ancestors()
                    )
                elif (
                    isinstance(defframe, nodes.ClassDef)
                    and defnode in defframe.type_params
                ):
                    # Generic on parent class:
                    # class Child[_T](Parent[_T])
                    maybe_before_assign = False
        return maybe_before_assign, annotation_return, use_outer_definition
References pylint.checkers.variables._assigned_locally(), and pylint.checkers.variables._detect_global_scope().
Referenced by _check_consumer().
_loopvar_name()
None pylint.checkers.variables.VariablesChecker._loopvar_name (self, astroid.Name node) protected
Definition at line 2564 of file variables.py.
    def _loopvar_name(self, node: astroid.Name) -> None:
        # filter variables according to node's scope
        astmts = [s for s in node.lookup(node.name)[1] if hasattr(s, "assign_type")]
        # If this variable usage exists inside a function definition
        # that exists in the same loop,
        # the usage is safe because the function will not be defined either if
        # the variable is not defined.
        scope = node.scope()
        if isinstance(scope, (nodes.Lambda, nodes.FunctionDef)) and any(
            asmt.scope().parent_of(scope) for asmt in astmts
        ):
            return
        # Filter variables according to their respective scope. Test parent
        # and statement to avoid #74747. This is not a total fix, which would
        # introduce a mechanism similar to special attribute lookup in
        # modules. Also, in order to get correct inference in this case, the
        # scope lookup rules would need to be changed to return the initial
        # assignment (which does not exist in code per se) as well as any later
        # modifications.
        if (
            not astmts  # pylint: disable=too-many-boolean-expressions
            or (
                astmts[0].parent == astmts[0].root()
                and astmts[0].parent.parent_of(node)
            )
            or (
                astmts[0].is_statement
                or not isinstance(astmts[0].parent, nodes.Module)
                and astmts[0].statement().parent_of(node)
            )
        ):
            _astmts = []
        else:
            _astmts = astmts[:1]
        for i, stmt in enumerate(astmts[1:]):
            try:
                astmt_statement = astmts[i].statement()
            except astroid.exceptions.ParentMissingError:
                continue
            if astmt_statement.parent_of(stmt) and not utils.in_for_else_branch(
                astmt_statement, stmt
            ):
                continue
            _astmts.append(stmt)
        astmts = _astmts
        if len(astmts) != 1:
            return
        assign = astmts[0].assign_type()
        if not (
            isinstance(assign, (nodes.For, nodes.Comprehension, nodes.GeneratorExp))
            and assign.statement() is not node.statement()
        ):
            return
        if not isinstance(assign, nodes.For):
            self.add_message("undefined-loop-variable", args=node.name, node=node)
            return
        for else_stmt in assign.orelse:
            if isinstance(
                else_stmt, (nodes.Return, nodes.Raise, nodes.Break, nodes.Continue)
            ):
                return
            # TODO: 4.0: Consider using utils.is_terminating_func
            # after merging it with RefactoringChecker._is_function_def_never_returning
            if isinstance(else_stmt, nodes.Expr) and isinstance(
                else_stmt.value, nodes.Call
            ):
                inferred_func = utils.safe_infer(else_stmt.value.func)
                if (
                    isinstance(inferred_func, nodes.FunctionDef)
                    and inferred_func.returns
                ):
                    inferred_return = utils.safe_infer(inferred_func.returns)
                    if isinstance(
                        inferred_return, nodes.FunctionDef
                    ) and inferred_return.qname() in {
                        *TYPING_NORETURN,
                        *TYPING_NEVER,
                        "typing._SpecialForm",
                    }:
                        return
                    # typing_extensions.NoReturn returns a _SpecialForm
                    if (
                        isinstance(inferred_return, bases.Instance)
                        and inferred_return.qname() == "typing._SpecialForm"
                    ):
                        return
        maybe_walrus = utils.get_node_first_ancestor_of_type(node, nodes.NamedExpr)
        if maybe_walrus:
            maybe_comprehension = utils.get_node_first_ancestor_of_type(
                maybe_walrus, nodes.Comprehension
            )
            if maybe_comprehension:
                comprehension_scope = utils.get_node_first_ancestor_of_type(
                    maybe_comprehension, nodes.ComprehensionScope
                )
                if comprehension_scope is None:
                    # Should not be possible.
                    pass
                elif (
                    comprehension_scope.parent.scope() is scope
                    and node.name in comprehension_scope.locals
                ):
                    return
        # For functions we can do more by inferring the length of the itered object
        try:
            inferred = next(assign.iter.infer())
            # Prefer the target of enumerate() rather than the enumerate object itself
            if (
                isinstance(inferred, astroid.Instance)
                and inferred.qname() == "builtins.enumerate"
            ):
                likely_call = assign.iter
                if isinstance(assign.iter, nodes.IfExp):
                    likely_call = assign.iter.body
                if isinstance(likely_call, nodes.Call) and likely_call.args:
                    inferred = next(likely_call.args[0].infer())
        except astroid.InferenceError:
            self.add_message("undefined-loop-variable", args=node.name, node=node)
        else:
            if (
                isinstance(inferred, astroid.Instance)
                and inferred.qname() == BUILTIN_RANGE
            ):
                # Consider range() objects safe, even if they might not yield any results.
                return
            # Consider sequences.
            sequences = (
                nodes.List,
                nodes.Tuple,
                nodes.Dict,
                nodes.Set,
                astroid.objects.FrozenSet,
            )
            if not isinstance(inferred, sequences):
                self.add_message("undefined-loop-variable", args=node.name, node=node)
                return
            elements = getattr(inferred, "elts", getattr(inferred, "items", []))
            if not elements:
                self.add_message("undefined-loop-variable", args=node.name, node=node)
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_name().
_maybe_used_and_assigned_at_once()
bool pylint.checkers.variables.VariablesChecker._maybe_used_and_assigned_at_once (_base_nodes.Statement defstmt) static protected
Check if `defstmt` has the potential to use and assign a name in the
same statement.
Definition at line 2378 of file variables.py.
    def _maybe_used_and_assigned_at_once(defstmt: _base_nodes.Statement) -> bool:
        """Check if `defstmt` has the potential to use and assign a name in the
        same statement.
        """
        if isinstance(defstmt, nodes.Match):
            return any(case.guard for case in defstmt.cases)
        if isinstance(defstmt, nodes.IfExp):
            return True
        if isinstance(defstmt, nodes.TypeAlias):
            return True
        if isinstance(defstmt.value, nodes.BaseContainer):
            return any(
                VariablesChecker._maybe_used_and_assigned_at_once(elt)
                for elt in defstmt.value.elts
                if isinstance(elt, (*NODES_WITH_VALUE_ATTR, nodes.IfExp, nodes.Match))
            )
        value = defstmt.value
        if isinstance(value, nodes.IfExp):
            return True
        if isinstance(value, nodes.Lambda) and isinstance(value.body, nodes.IfExp):
            return True
        if isinstance(value, nodes.Dict) and any(
            isinstance(item[0], nodes.IfExp) or isinstance(item[1], nodes.IfExp)
            for item in value.items
        ):
            return True
        if not isinstance(value, nodes.Call):
            return False
        return any(
            any(isinstance(kwarg.value, nodes.IfExp) for kwarg in call.keywords)
            or any(isinstance(arg, nodes.IfExp) for arg in call.args)
            or (
                isinstance(call.func, nodes.Attribute)
                and isinstance(call.func.expr, nodes.IfExp)
            )
            for call in value.nodes_of_class(klass=nodes.Call)
        )
_nodes_to_unpack()
list[nodes.NodeNG] | None pylint.checkers.variables.VariablesChecker._nodes_to_unpack (nodes.NodeNG node) static protected
Return the list of values of the `Assign` node.
Definition at line 3067 of file variables.py.
    def _nodes_to_unpack(node: nodes.NodeNG) -> list[nodes.NodeNG] | None:
        """Return the list of values of the `Assign` node."""
        if isinstance(node, (nodes.Tuple, nodes.List, nodes.Set, *DICT_TYPES)):
            return node.itered()  # type: ignore[no-any-return]
        if isinstance(node, astroid.Instance) and any(
            ancestor.qname() == "typing.NamedTuple" for ancestor in node.ancestors()
        ):
            return [i for i in node.values() if isinstance(i, nodes.AssignName)]
        return None
Referenced by _check_unpacking(), and visit_for().
_report_unbalanced_unpacking()
None pylint.checkers.variables.VariablesChecker._report_unbalanced_unpacking (self, nodes.NodeNG node, InferenceResult inferred, list[nodes.NodeNG] targets, int values_count, str details) protected
Definition at line 3077 of file variables.py.
    ) -> None:
        args = (
            details,
            len(targets),
            "" if len(targets) == 1 else "s",
            values_count,
            "" if values_count == 1 else "s",
        )
        symbol = (
            "unbalanced-dict-unpacking"
            if isinstance(inferred, DICT_TYPES)
            else "unbalanced-tuple-unpacking"
        )
        self.add_message(symbol, node=node, args=args, confidence=INFERENCE)
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by _check_unpacking(), and visit_for().
_report_unfound_name_definition()
None pylint.checkers.variables.VariablesChecker._report_unfound_name_definition (self, nodes.NodeNG node, NamesConsumer current_consumer) protected
Reports used-before-assignment when all name definition nodes
get filtered out by NamesConsumer.
Definition at line 2004 of file variables.py.
    ) -> None:
        """Reports used-before-assignment when all name definition nodes
        get filtered out by NamesConsumer.
        """
        if (
            self._postponed_evaluation_enabled
            and utils.is_node_in_type_annotation_context(node)
        ):
            return
        if self._is_builtin(node.name):
            return
        if self._is_variable_annotation_in_function(node):
            return
        if (
            node.name in self._evaluated_type_checking_scopes
            and node.scope() in self._evaluated_type_checking_scopes[node.name]
        ):
            return
        confidence = HIGH
        if node.name in current_consumer.names_under_always_false_test:
            confidence = INFERENCE
        elif node.name in current_consumer.consumed_uncertain:
            confidence = CONTROL_FLOW
        if node.name in current_consumer.names_defined_under_one_branch_only:
            msg = "possibly-used-before-assignment"
        else:
            msg = "used-before-assignment"
        self.add_message(
            msg,
            args=node.name,
            node=node,
            confidence=confidence,
        )
References _evaluated_type_checking_scopes, pylint.checkers.refactoring.recommendation_checker.RecommendationChecker._is_builtin(), _is_builtin(), _is_variable_annotation_in_function(), _postponed_evaluation_enabled, and pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by _check_consumer().
_report_unpacking_non_sequence()
None pylint.checkers.variables.VariablesChecker._report_unpacking_non_sequence (self, nodes.NodeNG node, str details) protected
Definition at line 3100 of file variables.py.
    def _report_unpacking_non_sequence(self, node: nodes.NodeNG, details: str) -> None:
        if details and not details.startswith(" "):
            details = f" {details}"
        self.add_message("unpacking-non-sequence", node=node, args=details)
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by _check_unpacking().
_should_ignore_redefined_builtin()
bool pylint.checkers.variables.VariablesChecker._should_ignore_redefined_builtin (self, nodes.NodeNG stmt) protected
Definition at line 2934 of file variables.py.
    def _should_ignore_redefined_builtin(self, stmt: nodes.NodeNG) -> bool:
        if not isinstance(stmt, nodes.ImportFrom):
            return False
        return stmt.modname in self.linter.config.redefining_builtins_modules
References pylint.checkers.base_checker.BaseChecker.linter.
Referenced by visit_functiondef(), and visit_module().
_should_node_be_skipped()
bool pylint.checkers.variables.VariablesChecker._should_node_be_skipped (self, nodes.Name node, NamesConsumer consumer, bool is_start_index) protected
Tests a consumer and node for various conditions in which the node shouldn't
be checked for the undefined-variable and used-before-assignment checks.
Definition at line 1755 of file variables.py.
    ) -> bool:
        """Tests a consumer and node for various conditions in which the node shouldn't
        be checked for the undefined-variable and used-before-assignment checks.
        """
        if consumer.scope_type == "class":
            # The list of base classes in the class definition is not part
            # of the class body.
            # If the current scope is a class scope but it's not the inner
            # scope, ignore it. This prevents to access this scope instead of
            # the globals one in function members when there are some common
            # names.
            if utils.is_ancestor_name(consumer.node, node) or (
                not is_start_index and self._ignore_class_scope(node)
            ):
                if any(
                    node.name == param.name.name for param in consumer.node.type_params
                ):
                    return False
                return True
            # Ignore inner class scope for keywords in class definition
            if isinstance(node.parent, nodes.Keyword) and isinstance(
                node.parent.parent, nodes.ClassDef
            ):
                return True
        elif consumer.scope_type == "function" and self._defined_in_function_definition(
            node, consumer.node
        ):
            if any(node.name == param.name.name for param in consumer.node.type_params):
                return False
            # If the name node is used as a function default argument's value or as
            # a decorator, then start from the parent frame of the function instead
            # of the function frame - and thus open an inner class scope
            return True
        elif consumer.scope_type == "lambda" and utils.is_default_argument(
            node, consumer.node
        ):
            return True
        return False
References _defined_in_function_definition(), and _ignore_class_scope().
Referenced by _undefined_and_used_before_checker().
_store_type_annotation_names()
None pylint.checkers.variables.VariablesChecker._store_type_annotation_names (self, nodes.For | nodes.Assign | nodes.With node) protected
Definition at line 2979 of file variables.py.
    ) -> None:
        type_annotation = node.type_annotation
        if not type_annotation:
            return
        self._store_type_annotation_node(node.type_annotation)
References _store_type_annotation_node().
Referenced by leave_assign(), leave_for(), and leave_with().
_store_type_annotation_node()
None pylint.checkers.variables.VariablesChecker._store_type_annotation_node (self, nodes.NodeNG type_annotation) protected
Given a type annotation, store all the name nodes it refers to.
Definition at line 2954 of file variables.py.
    def _store_type_annotation_node(self, type_annotation: nodes.NodeNG) -> None:
        """Given a type annotation, store all the name nodes it refers to."""
        if isinstance(type_annotation, nodes.Name):
            self._type_annotation_names.append(type_annotation.name)
            return
        if isinstance(type_annotation, nodes.Attribute):
            self._store_type_annotation_node(type_annotation.expr)
            return
        if not isinstance(type_annotation, nodes.Subscript):
            return
        if (
            isinstance(type_annotation.value, nodes.Attribute)
            and isinstance(type_annotation.value.expr, nodes.Name)
            and type_annotation.value.expr.name == TYPING_MODULE
        ):
            self._type_annotation_names.append(TYPING_MODULE)
            return
        self._type_annotation_names.extend(
            annotation.name for annotation in type_annotation.nodes_of_class(nodes.Name)
        )
References _store_type_annotation_node(), and _type_annotation_names.
Referenced by _store_type_annotation_names(), _store_type_annotation_node(), leave_functiondef(), visit_arguments(), and visit_const().
_undefined_and_used_before_checker()
None pylint.checkers.variables.VariablesChecker._undefined_and_used_before_checker (self, nodes.Name node, nodes.NodeNG stmt) protected
Definition at line 1707 of file variables.py.
    ) -> None:
        frame = stmt.scope()
        start_index = len(self._to_consume) - 1
        # iterates through parent scopes, from the inner to the outer
        base_scope_type = self._to_consume[start_index].scope_type
        for i in range(start_index, -1, -1):
            current_consumer = self._to_consume[i]
            # Certain nodes shouldn't be checked as they get checked another time
            if self._should_node_be_skipped(node, current_consumer, i == start_index):
                continue
            action, nodes_to_consume = self._check_consumer(
                node, stmt, frame, current_consumer, base_scope_type
            )
            if nodes_to_consume:
                # Any nodes added to consumed_uncertain by get_next_to_consume()
                # should be added back so that they are marked as used.
                # They will have already had a chance to emit used-before-assignment.
                # We check here instead of before every single return in _check_consumer()
                nodes_to_consume += current_consumer.consumed_uncertain[node.name]
                current_consumer.mark_as_consumed(node.name, nodes_to_consume)
            if action is VariableVisitConsumerAction.CONTINUE:
                continue
            if action is VariableVisitConsumerAction.RETURN:
                return
        # we have not found the name, if it isn't a builtin, that's an
        # undefined name !
        if not (
            node.name in nodes.Module.scope_attrs
            or utils.is_builtin(node.name)
            or node.name in self.linter.config.additional_builtins
            or (
                node.name == "__class__"
                and any(
                    i.is_method()
                    for i in node.node_ancestors()
                    if isinstance(i, nodes.FunctionDef)
                )
            )
        ) and not utils.node_ignores_exception(node, NameError):
            self.add_message("undefined-variable", args=node.name, node=node)
References _check_consumer(), _should_node_be_skipped(), _to_consume, pylint.checkers.base_checker.BaseChecker.add_message(), and pylint.checkers.base_checker.BaseChecker.linter.
Referenced by visit_name().
leave_assign()
None pylint.checkers.variables.VariablesChecker.leave_assign (self, nodes.Assign node)
Definition at line 2154 of file variables.py.
    def leave_assign(self, node: nodes.Assign) -> None:
        self._store_type_annotation_names(node)
References _store_type_annotation_names().
leave_classdef()
None pylint.checkers.variables.VariablesChecker.leave_classdef (self, nodes.ClassDef node)
Leave class: update consumption analysis variable.
Definition at line 1437 of file variables.py.
    def leave_classdef(self, node: nodes.ClassDef) -> None:
        """Leave class: update consumption analysis variable."""
        # Check for hidden ancestor names
        # e.g. "six" in: Class X(six.with_metaclass(ABCMeta, object)):
        for name_node in node.nodes_of_class(nodes.Name):
            if (
                isinstance(name_node.parent, nodes.Call)
                and isinstance(name_node.parent.func, nodes.Attribute)
                and isinstance(name_node.parent.func.expr, nodes.Name)
            ):
                hidden_name_node = name_node.parent.func.expr
                for consumer in self._to_consume:
                    if hidden_name_node.name in consumer.to_consume:
                        consumer.mark_as_consumed(
                            hidden_name_node.name,
                            consumer.to_consume[hidden_name_node.name],
                        )
                        break
        self._to_consume.pop()
References _to_consume.
leave_dictcomp()
None pylint.checkers.variables.VariablesChecker.leave_dictcomp (self, nodes.DictComp _)
Leave dictcomp: update consumption analysis variable.
Definition at line 1479 of file variables.py.
    def leave_dictcomp(self, _: nodes.DictComp) -> None:
        """Leave dictcomp: update consumption analysis variable."""
        # do not check for not used locals here
        self._to_consume.pop()
References _to_consume.
leave_excepthandler()
None pylint.checkers.variables.VariablesChecker.leave_excepthandler (self, nodes.ExceptHandler node)
Definition at line 1702 of file variables.py.
    def leave_excepthandler(self, node: nodes.ExceptHandler) -> None:
        if not node.name or not isinstance(node.name, nodes.AssignName):
            return
        self._except_handler_names_queue.pop()
References _except_handler_names_queue.
leave_for()
None pylint.checkers.variables.VariablesChecker.leave_for (self, nodes.For node)
Definition at line 1387 of file variables.py.
    def leave_for(self, node: nodes.For) -> None:
        self._store_type_annotation_names(node)
References _store_type_annotation_names().
leave_functiondef()
None pylint.checkers.variables.VariablesChecker.leave_functiondef (self, nodes.FunctionDef node)
Leave function: check function's locals are consumed.
Definition at line 1542 of file variables.py.
    def leave_functiondef(self, node: nodes.FunctionDef) -> None:
        """Leave function: check function's locals are consumed."""
        self._check_metaclasses(node)
        if node.type_comment_returns:
            self._store_type_annotation_node(node.type_comment_returns)
        if node.type_comment_args:
            for argument_annotation in node.type_comment_args:
                self._store_type_annotation_node(argument_annotation)
        not_consumed = self._to_consume.pop().to_consume
        if not (
            self.linter.is_message_enabled("unused-variable")
            or self.linter.is_message_enabled("possibly-unused-variable")
            or self.linter.is_message_enabled("unused-argument")
        ):
            return
        # Don't check arguments of function which are only raising an exception.
        if utils.is_error(node):
            return
        # Don't check arguments of abstract methods or within an interface.
        is_method = node.is_method()
        if is_method and node.is_abstract():
            return
        global_names = _flattened_scope_names(node.nodes_of_class(nodes.Global))
        nonlocal_names = _flattened_scope_names(node.nodes_of_class(nodes.Nonlocal))
        comprehension_target_names: set[str] = set()
        for comprehension_scope in node.nodes_of_class(nodes.ComprehensionScope):
            for generator in comprehension_scope.generators:
                for name in utils.find_assigned_names_recursive(generator.target):
                    comprehension_target_names.add(name)
        for name, stmts in not_consumed.items():
            self._check_is_unused(
                name,
                node,
                stmts[0],
                global_names,
                nonlocal_names,
                comprehension_target_names,
            )
References _check_is_unused(), _check_metaclasses(), pylint.checkers.variables._flattened_scope_names(), _store_type_annotation_node(), _to_consume, and pylint.checkers.base_checker.BaseChecker.linter.
leave_generatorexp()
None pylint.checkers.variables.VariablesChecker.leave_generatorexp (self, nodes.GeneratorExp _)
Leave genexpr: update consumption analysis variable.
Definition at line 1470 of file variables.py.
    def leave_generatorexp(self, _: nodes.GeneratorExp) -> None:
        """Leave genexpr: update consumption analysis variable."""
        # do not check for not used locals here
        self._to_consume.pop()
References _to_consume.
leave_lambda()
None pylint.checkers.variables.VariablesChecker.leave_lambda (self, nodes.Lambda _)
Leave lambda: update consumption analysis variable.
Definition at line 1461 of file variables.py.
    def leave_lambda(self, _: nodes.Lambda) -> None:
        """Leave lambda: update consumption analysis variable."""
        # do not check for not used locals here
        self._to_consume.pop()
References _to_consume.
leave_listcomp()
None pylint.checkers.variables.VariablesChecker.leave_listcomp (self, nodes.ListComp _)
Leave listcomp: update consumption analysis variable.
Definition at line 2149 of file variables.py.
    def leave_listcomp(self, _: nodes.ListComp) -> None:
        """Leave listcomp: update consumption analysis variable."""
        # do not check for not used locals here
        self._to_consume.pop()
References _to_consume.
leave_module()
None pylint.checkers.variables.VariablesChecker.leave_module (self, nodes.Module node)
Leave module: check globals.
Definition at line 1413 of file variables.py.
    def leave_module(self, node: nodes.Module) -> None:
        """Leave module: check globals."""
        assert len(self._to_consume) == 1
        self._check_metaclasses(node)
        not_consumed = self._to_consume.pop().to_consume
        # attempt to check for __all__ if defined
        if "__all__" in node.locals:
            self._check_all(node, not_consumed)
        # check for unused globals
        self._check_globals(not_consumed)
        # don't check unused imports in __init__ files
        if not self.linter.config.init_import and node.package:
            return
        self._check_imports(not_consumed)
        self._type_annotation_names = []
References _check_all(), _check_globals(), _check_imports(), _check_metaclasses(), _to_consume, _type_annotation_names, and pylint.checkers.base_checker.BaseChecker.linter.
leave_setcomp()
None pylint.checkers.variables.VariablesChecker.leave_setcomp (self, nodes.SetComp _)
Leave setcomp: update consumption analysis variable.
Definition at line 1488 of file variables.py.
    def leave_setcomp(self, _: nodes.SetComp) -> None:
        """Leave setcomp: update consumption analysis variable."""
        # do not check for not used locals here
        self._to_consume.pop()
References _to_consume.
leave_with()
None pylint.checkers.variables.VariablesChecker.leave_with (self, nodes.With node)
Definition at line 2157 of file variables.py.
    def leave_with(self, node: nodes.With) -> None:
        self._store_type_annotation_names(node)
References _store_type_annotation_names().
visit_arguments()
None pylint.checkers.variables.VariablesChecker.visit_arguments (self, nodes.Arguments node)
Definition at line 2160 of file variables.py.
    def visit_arguments(self, node: nodes.Arguments) -> None:
        for annotation in node.type_comment_args:
            self._store_type_annotation_node(annotation)
References _store_type_annotation_node().
visit_assign()
None pylint.checkers.variables.VariablesChecker.visit_assign (self, nodes.Assign node)
Check unbalanced tuple unpacking for assignments and unpacking
non-sequences as well as in case self/cls get assigned.
Definition at line 2123 of file variables.py.
    def visit_assign(self, node: nodes.Assign) -> None:
        """Check unbalanced tuple unpacking for assignments and unpacking
        non-sequences as well as in case self/cls get assigned.
        """
        self._check_self_cls_assign(node)
        if not isinstance(node.targets[0], (nodes.Tuple, nodes.List)):
            return
        targets = node.targets[0].itered()
        # Check if we have starred nodes.
        if any(isinstance(target, nodes.Starred) for target in targets):
            return
        try:
            inferred = utils.safe_infer(node.value)
            if inferred is not None:
                self._check_unpacking(inferred, node, targets)
        except astroid.InferenceError:
            return
References _check_self_cls_assign(), and _check_unpacking().
visit_assignname()
None pylint.checkers.variables.VariablesChecker.visit_assignname (self, nodes.AssignName node)
Definition at line 1663 of file variables.py.
    def visit_assignname(self, node: nodes.AssignName) -> None:
        if isinstance(node.assign_type(), nodes.AugAssign):
            self.visit_name(node)
References astroid.nodes.as_string.AsStringVisitor.visit_name(), astroid.rebuilder.TreeRebuilder.visit_name(), pylint.checkers.exceptions.ExceptionRaiseRefVisitor.visit_name(), and visit_name().
visit_classdef()
None pylint.checkers.variables.VariablesChecker.visit_classdef (self, nodes.ClassDef node)
Visit class: update consumption analysis variable.
Definition at line 1433 of file variables.py.
    def visit_classdef(self, node: nodes.ClassDef) -> None:
        """Visit class: update consumption analysis variable."""
        self._to_consume.append(NamesConsumer(node, "class"))
References _to_consume.
Referenced by pylint.pyreverse.inspector.Linker.visit_assignname().
visit_const()
None pylint.checkers.variables.VariablesChecker.visit_const (self, nodes.Const node)
Take note of names that appear inside string literal type annotations
unless the string is a parameter to `typing.Literal` or `typing.Annotation`.
Definition at line 3409 of file variables.py.
    def visit_const(self, node: nodes.Const) -> None:
        """Take note of names that appear inside string literal type annotations
        unless the string is a parameter to `typing.Literal` or `typing.Annotation`.
        """
        if node.pytype() != "builtins.str":
            return
        if not utils.is_node_in_type_annotation_context(node):
            return
        # Check if parent's or grandparent's first child is typing.Literal
        parent = node.parent
        if isinstance(parent, nodes.Tuple):
            parent = parent.parent
        if isinstance(parent, nodes.Subscript):
            origin = next(parent.get_children(), None)
            if origin is not None and utils.is_typing_member(
                origin, ("Annotated", "Literal")
            ):
                return
        try:
            annotation = extract_node(node.value)
            self._store_type_annotation_node(annotation)
        except ValueError:
            # e.g. node.value is white space
            pass
        except astroid.AstroidSyntaxError:
            # e.g. "?" or ":" in typing.Literal["?", ":"]
            pass
References _store_type_annotation_node().
visit_delname()
None pylint.checkers.variables.VariablesChecker.visit_delname (self, nodes.DelName node)
Definition at line 1667 of file variables.py.
    def visit_delname(self, node: nodes.DelName) -> None:
        self.visit_name(node)
References astroid.nodes.as_string.AsStringVisitor.visit_name(), astroid.rebuilder.TreeRebuilder.visit_name(), pylint.checkers.exceptions.ExceptionRaiseRefVisitor.visit_name(), and visit_name().
visit_dictcomp()
None pylint.checkers.variables.VariablesChecker.visit_dictcomp (self, nodes.DictComp node)
Visit dictcomp: update consumption analysis variable.
Definition at line 1475 of file variables.py.
    def visit_dictcomp(self, node: nodes.DictComp) -> None:
        """Visit dictcomp: update consumption analysis variable."""
        self._to_consume.append(NamesConsumer(node, "comprehension"))
References _to_consume.
visit_excepthandler()
None pylint.checkers.variables.VariablesChecker.visit_excepthandler (self, nodes.ExceptHandler node)
Definition at line 1686 of file variables.py.
    def visit_excepthandler(self, node: nodes.ExceptHandler) -> None:
        if not node.name or not isinstance(node.name, nodes.AssignName):
            return
        for outer_except, outer_except_assign_name in self._except_handler_names_queue:
            if node.name.name == outer_except_assign_name.name:
                self.add_message(
                    "redefined-outer-name",
                    args=(outer_except_assign_name.name, outer_except.fromlineno),
                    node=node,
                )
                break
        self._except_handler_names_queue.append((node, node.name))
References _except_handler_names_queue, and pylint.checkers.base_checker.BaseChecker.add_message().
visit_for()
None pylint.checkers.variables.VariablesChecker.visit_for (self, nodes.For node)
Definition at line 1335 of file variables.py.
    def visit_for(self, node: nodes.For) -> None:
        if not isinstance(node.target, nodes.Tuple):
            return
        targets = node.target.elts
        inferred = utils.safe_infer(node.iter)
        if not isinstance(inferred, DICT_TYPES):
            return
        values = self._nodes_to_unpack(inferred)
        if not values:
            # no dict items returned
            return
        if isinstance(inferred, astroid.objects.DictItems):
            # dict.items() is a bit special because values will be a tuple
            # So as long as there are always 2 targets and values each are
            # a tuple with two items, this will unpack correctly.
            # Example: `for key, val in {1: 2, 3: 4}.items()`
            if len(targets) == 2 and all(len(x.elts) == 2 for x in values):
                return
            # Starred nodes indicate ambiguous unpacking
            # if `dict.items()` is used so we won't flag them.
            if any(isinstance(target, nodes.Starred) for target in targets):
                return
        if isinstance(inferred, nodes.Dict):
            if isinstance(node.iter, nodes.Name):
                # If this a case of 'dict-items-missing-iter', we don't want to
                # report it as an 'unbalanced-dict-unpacking' as well
                # TODO (performance), merging both checks would streamline this
                if len(targets) == 2:
                    return
        else:
            is_starred_targets = any(
                isinstance(target, nodes.Starred) for target in targets
            )
            for value in values:
                value_length = self._get_value_length(value)
                is_valid_star_unpack = is_starred_targets and value_length >= len(
                    targets
                )
                if len(targets) != value_length and not is_valid_star_unpack:
                    details = _get_unpacking_extra_info(node, inferred)
                    self._report_unbalanced_unpacking(
                        node, inferred, targets, value_length, details
                    )
                    break
References pylint.checkers.variables._get_unpacking_extra_info(), _get_value_length(), _nodes_to_unpack(), and _report_unbalanced_unpacking().
visit_functiondef()
None pylint.checkers.variables.VariablesChecker.visit_functiondef (self, nodes.FunctionDef node)
Visit function: update consumption analysis variable and check locals.
Definition at line 1493 of file variables.py.
    def visit_functiondef(self, node: nodes.FunctionDef) -> None:
        """Visit function: update consumption analysis variable and check locals."""
        self._to_consume.append(NamesConsumer(node, "function"))
        if not (
            self.linter.is_message_enabled("redefined-outer-name")
            or self.linter.is_message_enabled("redefined-builtin")
        ):
            return
        globs = node.root().globals
        for name, stmt in node.items():
            if name in globs and not isinstance(stmt, nodes.Global):
                definition = globs[name][0]
                if (
                    isinstance(definition, nodes.ImportFrom)
                    and definition.modname == FUTURE
                ):
                    # It is a __future__ directive, not a symbol.
                    continue
                # Do not take in account redefined names for the purpose
                # of type checking.:
                if any(
                    in_type_checking_block(definition) for definition in globs[name]
                ):
                    continue
                # Suppress emitting the message if the outer name is in the
                # scope of an exception assignment.
                # For example: the `e` in `except ValueError as e`
                global_node = globs[name][0]
                if isinstance(global_node, nodes.AssignName) and isinstance(
                    global_node.parent, nodes.ExceptHandler
                ):
                    continue
                line = definition.fromlineno
                if not self._is_name_ignored(stmt, name):
                    self.add_message(
                        "redefined-outer-name", args=(name, line), node=stmt
                    )
            elif (
                utils.is_builtin(name)
                and not self._allowed_redefined_builtin(name)
                and not self._should_ignore_redefined_builtin(stmt)
            ):
                # do not print Redefining builtin for additional builtins
                self.add_message("redefined-builtin", args=name, node=stmt)
References _allowed_redefined_builtin(), _is_name_ignored(), _should_ignore_redefined_builtin(), _to_consume, pylint.checkers.base_checker.BaseChecker.add_message(), and pylint.checkers.base_checker.BaseChecker.linter.
Referenced by pylint.pyreverse.inspector.Linker.visit_assignname().
visit_generatorexp()
None pylint.checkers.variables.VariablesChecker.visit_generatorexp (self, nodes.GeneratorExp node)
Visit genexpr: update consumption analysis variable.
Definition at line 1466 of file variables.py.
    def visit_generatorexp(self, node: nodes.GeneratorExp) -> None:
        """Visit genexpr: update consumption analysis variable."""
        self._to_consume.append(NamesConsumer(node, "comprehension"))
References _to_consume.
visit_global()
None pylint.checkers.variables.VariablesChecker.visit_global (self, nodes.Global node)
Check names imported exists in the global scope.
Definition at line 1598 of file variables.py.
    def visit_global(self, node: nodes.Global) -> None:
        """Check names imported exists in the global scope."""
        frame = node.frame()
        if isinstance(frame, nodes.Module):
            self.add_message("global-at-module-level", node=node, confidence=HIGH)
            return
        module = frame.root()
        default_message = True
        locals_ = node.scope().locals
        for name in node.names:
            try:
                assign_nodes = module.getattr(name)
            except astroid.NotFoundError:
                # unassigned global, skip
                assign_nodes = []
            not_defined_locally_by_import = not any(
                isinstance(local, (nodes.Import, nodes.ImportFrom))
                for local in locals_.get(name, ())
            )
            if (
                not utils.is_reassigned_after_current(node, name)
                and not utils.is_deleted_after_current(node, name)
                and not_defined_locally_by_import
            ):
                self.add_message(
                    "global-variable-not-assigned",
                    args=name,
                    node=node,
                    confidence=HIGH,
                )
                default_message = False
                continue
            for anode in assign_nodes:
                if (
                    isinstance(anode, nodes.AssignName)
                    and anode.name in module.special_attributes
                ):
                    self.add_message("redefined-builtin", args=name, node=node)
                    break
                if anode.frame() is module:
                    # module level assignment
                    break
                if (
                    isinstance(anode, (nodes.ClassDef, nodes.FunctionDef))
                    and anode.parent is module
                ):
                    # module level function assignment
                    break
            else:
                if not_defined_locally_by_import:
                    # global undefined at the module scope
                    self.add_message(
                        "global-variable-undefined",
                        args=name,
                        node=node,
                        confidence=HIGH,
                    )
                    default_message = False
        if default_message:
            self.add_message("global-statement", node=node, confidence=HIGH)
References pylint.checkers.base_checker.BaseChecker.add_message().
visit_import()
None pylint.checkers.variables.VariablesChecker.visit_import (self, nodes.Import node)
Check modules attribute accesses.
Definition at line 2068 of file variables.py.
    def visit_import(self, node: nodes.Import) -> None:
        """Check modules attribute accesses."""
        if not self._analyse_fallback_blocks and utils.is_from_fallback_block(node):
            # No need to verify this, since ImportError is already
            # handled by the client code.
            return
        # Don't verify import if part of guarded import block
        if in_type_checking_block(node):
            return
        if isinstance(node.parent, nodes.If) and is_sys_guard(node.parent):
            return
        for name, _ in node.names:
            parts = name.split(".")
            try:
                module = next(_infer_name_module(node, parts[0]))
            except astroid.ResolveError:
                continue
            if not isinstance(module, nodes.Module):
                continue
            self._check_module_attrs(node, module, parts[1:])
References _analyse_fallback_blocks(), _check_module_attrs(), and pylint.checkers.variables._infer_name_module().
visit_importfrom()
None pylint.checkers.variables.VariablesChecker.visit_importfrom (self, nodes.ImportFrom node)
Check modules attribute accesses.
Definition at line 2091 of file variables.py.
    def visit_importfrom(self, node: nodes.ImportFrom) -> None:
        """Check modules attribute accesses."""
        if not self._analyse_fallback_blocks and utils.is_from_fallback_block(node):
            # No need to verify this, since ImportError is already
            # handled by the client code.
            return
        # Don't verify import if part of guarded import block
        # I.e. `sys.version_info` or `typing.TYPE_CHECKING`
        if in_type_checking_block(node):
            return
        if isinstance(node.parent, nodes.If) and is_sys_guard(node.parent):
            return
        name_parts = node.modname.split(".")
        try:
            module = node.do_import_module(name_parts[0])
        except astroid.AstroidBuildingError:
            return
        module = self._check_module_attrs(node, module, name_parts[1:])
        if not module:
            return
        for name, _ in node.names:
            if name == "*":
                continue
            self._check_module_attrs(node, module, name.split("."))
References _analyse_fallback_blocks(), and _check_module_attrs().
visit_lambda()
None pylint.checkers.variables.VariablesChecker.visit_lambda (self, nodes.Lambda node)
Visit lambda: update consumption analysis variable.
Definition at line 1457 of file variables.py.
    def visit_lambda(self, node: nodes.Lambda) -> None:
        """Visit lambda: update consumption analysis variable."""
        self._to_consume.append(NamesConsumer(node, "lambda"))
References _to_consume.
visit_listcomp()
None pylint.checkers.variables.VariablesChecker.visit_listcomp (self, nodes.ListComp node)
Visit listcomp: update consumption analysis variable.
Definition at line 2145 of file variables.py.
    def visit_listcomp(self, node: nodes.ListComp) -> None:
        """Visit listcomp: update consumption analysis variable."""
        self._to_consume.append(NamesConsumer(node, "comprehension"))
References _to_consume.
visit_module()
None pylint.checkers.variables.VariablesChecker.visit_module (self, nodes.Module node)
Visit module : update consumption analysis variable
checks globals doesn't overrides builtins.
Definition at line 1390 of file variables.py.
    def visit_module(self, node: nodes.Module) -> None:
        """Visit module : update consumption analysis variable
        checks globals doesn't overrides builtins.
        """
        self._to_consume = [NamesConsumer(node, "module")]
        self._postponed_evaluation_enabled = is_postponed_evaluation_enabled(node)
        for name, stmts in node.locals.items():
            if utils.is_builtin(name):
                if self._should_ignore_redefined_builtin(stmts[0]) or name == "__doc__":
                    continue
                self.add_message("redefined-builtin", args=name, node=stmts[0])
References _postponed_evaluation_enabled, _should_ignore_redefined_builtin(), _to_consume, and pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by pylint.pyreverse.inspector.Linker.visit_assignname().
visit_name()
None pylint.checkers.variables.VariablesChecker.visit_name (self, nodes.Name | nodes.AssignName | nodes.DelName node)
Don't add the 'utils.only_required_for_messages' decorator here!
It's important that all 'Name' nodes are visited, otherwise the
'NamesConsumers' won't be correct.
Definition at line 1670 of file variables.py.
    def visit_name(self, node: nodes.Name | nodes.AssignName | nodes.DelName) -> None:
        """Don't add the 'utils.only_required_for_messages' decorator here!
        It's important that all 'Name' nodes are visited, otherwise the
        'NamesConsumers' won't be correct.
        """
        stmt = node.statement()
        if stmt.fromlineno is None:
            # name node from an astroid built from live code, skip
            assert not stmt.root().file.endswith(".py")
            return
        self._undefined_and_used_before_checker(node, stmt)
        self._loopvar_name(node)
References _loopvar_name(), and _undefined_and_used_before_checker().
Referenced by visit_assignname(), and visit_delname().
visit_setcomp()
None pylint.checkers.variables.VariablesChecker.visit_setcomp (self, nodes.SetComp node)
Visit setcomp: update consumption analysis variable.
Definition at line 1484 of file variables.py.
    def visit_setcomp(self, node: nodes.SetComp) -> None:
        """Visit setcomp: update consumption analysis variable."""
        self._to_consume.append(NamesConsumer(node, "comprehension"))
References _to_consume.
visit_subscript()
None pylint.checkers.variables.VariablesChecker.visit_subscript (self, nodes.Subscript node)
Definition at line 3368 of file variables.py.
    def visit_subscript(self, node: nodes.Subscript) -> None:
        inferred_slice = utils.safe_infer(node.slice)
        self._check_potential_index_error(node, inferred_slice)
References _check_potential_index_error().
Member Data Documentation
_allow_global_unused_variables
pylint.checkers.variables.VariablesChecker._allow_global_unused_variables protected
Definition at line 3203 of file variables.py.
_evaluated_type_checking_scopes
dict[ pylint.checkers.variables.VariablesChecker._evaluated_type_checking_scopes protected
Definition at line 1327 of file variables.py.
Referenced by _filter_type_checking_import_from_consumption(), and _report_unfound_name_definition().
_except_handler_names_queue
list[ pylint.checkers.variables.VariablesChecker._except_handler_names_queue protected
Definition at line 1323 of file variables.py.
Referenced by leave_excepthandler(), and visit_excepthandler().
_ignored_modules
pylint.checkers.variables.VariablesChecker._ignored_modules protected
Definition at line 3128 of file variables.py.
_postponed_evaluation_enabled
bool pylint.checkers.variables.VariablesChecker._postponed_evaluation_enabled = False protected
Definition at line 1330 of file variables.py.
Referenced by _check_consumer(), _report_unfound_name_definition(), and visit_module().
_to_consume
pylint.checkers.variables.VariablesChecker._to_consume = [] protected
Definition at line 1321 of file variables.py.
Referenced by _check_classdef_metaclasses(), _check_imports(), _undefined_and_used_before_checker(), leave_classdef(), leave_dictcomp(), leave_functiondef(), leave_generatorexp(), leave_lambda(), leave_listcomp(), leave_module(), leave_setcomp(), visit_classdef(), visit_dictcomp(), visit_functiondef(), visit_generatorexp(), visit_lambda(), visit_listcomp(), visit_module(), and visit_setcomp().
_type_annotation_names
list pylint.checkers.variables.VariablesChecker._type_annotation_names = [] protected
Definition at line 1322 of file variables.py.
Referenced by _check_imports(), _check_is_unused(), _store_type_annotation_node(), and leave_module().
leave_asyncfunctiondef
None pylint.checkers.variables.VariablesChecker.leave_asyncfunctiondef = leave_functiondef static
Definition at line 1589 of file variables.py.
visit_asyncfunctiondef
None pylint.checkers.variables.VariablesChecker.visit_asyncfunctiondef = visit_functiondef static
Definition at line 1588 of file variables.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pylint/checkers/variables.py