Read&Watch: pylint.checkers.modified_iterating_checker.ModifiedIterationChecker Class Reference
pylint.checkers.modified_iterating_checker.ModifiedIterationChecker Class Reference
Public Member Functions
None visit_for (self, nodes.For node)
Public Member Functions inherited from pylint.checkers.base_checker.BaseChecker
None __init__ (self, PyLinter linter)
bool __gt__ (self, Any other)
bool __eq__ (self, object other)
int __hash__ (self)
str __repr__ (self)
str __str__ (self)
str get_full_documentation (self, dict[str, MessageDefinitionTuple] msgs, Iterable[tuple[str, OptionDict, Any]] options, Sequence[tuple[str, str, ReportsCallable]] reports, str|None doc=None, str|None module=None, bool show_options=True)
None add_message (self, str msgid, int|None line=None, nodes.NodeNG|None node=None, Any args=None, Confidence|None confidence=None, int|None col_offset=None, int|None end_lineno=None, int|None end_col_offset=None)
None check_consistency (self)
MessageDefinition create_message_definition_from_tuple (self, str msgid, MessageDefinitionTuple msg_tuple)
list[MessageDefinition] messages (self)
None open (self)
None close (self)
Any get_map_data (self)
None reduce_map_data (self, PyLinter linter, list[Any] data)
Public Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
None __init__ (self, _ArgumentsManager arguments_manager)
Protected Member Functions
None _modified_iterating_check_on_node_and_children (self, nodes.NodeNG body_node, nodes.NodeNG iter_obj)
None _modified_iterating_check (self, nodes.NodeNG node, nodes.NodeNG iter_obj)
bool _modified_iterating_list_cond (self, nodes.NodeNG node, nodes.Name|nodes.Attribute iter_obj)
bool _modified_iterating_dict_cond (self, nodes.NodeNG node, nodes.Name|nodes.Attribute iter_obj)
bool _modified_iterating_set_cond (self, nodes.NodeNG node, nodes.Name|nodes.Attribute iter_obj)
bool _deleted_iteration_target_cond (self, nodes.DelName node, nodes.NodeNG iter_obj)
Protected Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
Any _option_value (self, str opt)
Iterator[ tuple[str, list[tuple[str, OptionDict, Any]]]|tuple[None, dict[str, list[tuple[str, OptionDict, Any]]]]] _options_by_section (self)
Iterator[tuple[str, OptionDict, Any]] _options_and_values (self, Options|None options=None)
Static Protected Member Functions
bool _is_node_expr_that_calls_attribute_name (nodes.NodeNG node)
bool _common_cond_list_set (nodes.Expr node, nodes.Name|nodes.Attribute iter_obj, nodes.List|nodes.Set infer_val)
bool _is_node_assigns_subscript_name (nodes.NodeNG node)
Additional Inherited Members
Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
linter = linter
messages
Static Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
str name = ""
dict msgs = {}
tuple reports = ()
bool enabled = True
Static Public Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
tuple options = ()
dict option_groups_descs = {}
Protected Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
_arguments_manager = arguments_manager
Detailed Description
Checks for modified iterators in for loops iterations.
Currently supports `for` loops for Sets, Dictionaries and Lists.
Definition at line 22 of file modified_iterating_checker.py.
Member Function Documentation
_common_cond_list_set()
bool pylint.checkers.modified_iterating_checker.ModifiedIterationChecker._common_cond_list_set (nodes.Expr node, nodes.Name | nodes.Attribute iter_obj, nodes.List | nodes.Set infer_val) static protected
Definition at line 110 of file modified_iterating_checker.py.
    ) -> bool:
        iter_obj_name = (
            iter_obj.attrname
            if isinstance(iter_obj, nodes.Attribute)
            else iter_obj.name
        )
        return (infer_val == utils.safe_infer(iter_obj)) and (  # type: ignore[no-any-return]
            node.value.func.expr.name == iter_obj_name
        )
Referenced by _modified_iterating_list_cond(), and _modified_iterating_set_cond().
_deleted_iteration_target_cond()
bool pylint.checkers.modified_iterating_checker.ModifiedIterationChecker._deleted_iteration_target_cond (self, nodes.DelName node, nodes.NodeNG iter_obj) protected
Definition at line 182 of file modified_iterating_checker.py.
    ) -> bool:
        if not isinstance(node, nodes.DelName):
            return False
        if not isinstance(iter_obj.parent, nodes.For):
            return False
        if not isinstance(
            iter_obj.parent.target, (nodes.AssignName, nodes.BaseContainer)
        ):
            return False
        return any(
            t == node.name
            for t in utils.find_assigned_names_recursive(iter_obj.parent.target)
        )
Referenced by _modified_iterating_check().
_is_node_assigns_subscript_name()
bool pylint.checkers.modified_iterating_checker.ModifiedIterationChecker._is_node_assigns_subscript_name (nodes.NodeNG node) static protected
Definition at line 125 of file modified_iterating_checker.py.
    def _is_node_assigns_subscript_name(node: nodes.NodeNG) -> bool:
        return isinstance(node, nodes.Assign) and (
            isinstance(node.targets[0], nodes.Subscript)
            and (isinstance(node.targets[0].value, nodes.Name))
        )
Referenced by _modified_iterating_dict_cond().
_is_node_expr_that_calls_attribute_name()
bool pylint.checkers.modified_iterating_checker.ModifiedIterationChecker._is_node_expr_that_calls_attribute_name (nodes.NodeNG node) static protected
Definition at line 101 of file modified_iterating_checker.py.
    def _is_node_expr_that_calls_attribute_name(node: nodes.NodeNG) -> bool:
        return (
            isinstance(node, nodes.Expr)
            and isinstance(node.value, nodes.Call)
            and isinstance(node.value.func, nodes.Attribute)
            and isinstance(node.value.func.expr, nodes.Name)
        )
Referenced by _modified_iterating_list_cond(), and _modified_iterating_set_cond().
_modified_iterating_check()
None pylint.checkers.modified_iterating_checker.ModifiedIterationChecker._modified_iterating_check (self, nodes.NodeNG node, nodes.NodeNG iter_obj) protected
Definition at line 70 of file modified_iterating_checker.py.
    ) -> None:
        msg_id = None
        if isinstance(node, nodes.Delete) and any(
            self._deleted_iteration_target_cond(t, iter_obj) for t in node.targets
        ):
            inferred = utils.safe_infer(iter_obj)
            if isinstance(inferred, nodes.List):
                msg_id = "modified-iterating-list"
            elif isinstance(inferred, nodes.Dict):
                msg_id = "modified-iterating-dict"
            elif isinstance(inferred, nodes.Set):
                msg_id = "modified-iterating-set"
        elif not isinstance(iter_obj, (nodes.Name, nodes.Attribute)):
            pass
        elif self._modified_iterating_list_cond(node, iter_obj):
            msg_id = "modified-iterating-list"
        elif self._modified_iterating_dict_cond(node, iter_obj):
            msg_id = "modified-iterating-dict"
        elif self._modified_iterating_set_cond(node, iter_obj):
            msg_id = "modified-iterating-set"
        if msg_id:
            self.add_message(
                msg_id,
                node=node,
                args=(iter_obj.repr_name(),),
                confidence=interfaces.INFERENCE,
            )
References _deleted_iteration_target_cond(), _modified_iterating_dict_cond(), _modified_iterating_list_cond(), _modified_iterating_set_cond(), and pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by _modified_iterating_check_on_node_and_children().
_modified_iterating_check_on_node_and_children()
None pylint.checkers.modified_iterating_checker.ModifiedIterationChecker._modified_iterating_check_on_node_and_children (self, nodes.NodeNG body_node, nodes.NodeNG iter_obj) protected
See if node or any of its children raises modified iterating messages.
Definition at line 62 of file modified_iterating_checker.py.
    ) -> None:
        """See if node or any of its children raises modified iterating messages."""
        self._modified_iterating_check(body_node, iter_obj)
        for child in body_node.get_children():
            self._modified_iterating_check_on_node_and_children(child, iter_obj)
References _modified_iterating_check(), and _modified_iterating_check_on_node_and_children().
Referenced by _modified_iterating_check_on_node_and_children(), and visit_for().
_modified_iterating_dict_cond()
bool pylint.checkers.modified_iterating_checker.ModifiedIterationChecker._modified_iterating_dict_cond (self, nodes.NodeNG node, nodes.Name | nodes.Attribute iter_obj) protected
Definition at line 144 of file modified_iterating_checker.py.
    ) -> bool:
        if not self._is_node_assigns_subscript_name(node):
            return False
        # Do not emit when merely updating the same key being iterated
        if (
            isinstance(iter_obj, nodes.Name)
            and iter_obj.name == node.targets[0].value.name
            and isinstance(iter_obj.parent.target, nodes.AssignName)
            and isinstance(node.targets[0].slice, nodes.Name)
            and iter_obj.parent.target.name == node.targets[0].slice.name
        ):
            return False
        infer_val = utils.safe_infer(node.targets[0].value)
        if not isinstance(infer_val, nodes.Dict):
            return False
        if infer_val != utils.safe_infer(iter_obj):
            return False
        if isinstance(iter_obj, nodes.Attribute):
            iter_obj_name = iter_obj.attrname
        else:
            iter_obj_name = iter_obj.name
        return node.targets[0].value.name == iter_obj_name  # type: ignore[no-any-return]
References _is_node_assigns_subscript_name().
Referenced by _modified_iterating_check().
_modified_iterating_list_cond()
bool pylint.checkers.modified_iterating_checker.ModifiedIterationChecker._modified_iterating_list_cond (self, nodes.NodeNG node, nodes.Name | nodes.Attribute iter_obj) protected
Definition at line 131 of file modified_iterating_checker.py.
    ) -> bool:
        if not self._is_node_expr_that_calls_attribute_name(node):
            return False
        infer_val = utils.safe_infer(node.value.func.expr)
        if not isinstance(infer_val, nodes.List):
            return False
        return (
            self._common_cond_list_set(node, iter_obj, infer_val)
            and node.value.func.attrname in _LIST_MODIFIER_METHODS
        )
References _common_cond_list_set(), and _is_node_expr_that_calls_attribute_name().
Referenced by _modified_iterating_check().
_modified_iterating_set_cond()
bool pylint.checkers.modified_iterating_checker.ModifiedIterationChecker._modified_iterating_set_cond (self, nodes.NodeNG node, nodes.Name | nodes.Attribute iter_obj) protected
Definition at line 169 of file modified_iterating_checker.py.
    ) -> bool:
        if not self._is_node_expr_that_calls_attribute_name(node):
            return False
        infer_val = utils.safe_infer(node.value.func.expr)
        if not isinstance(infer_val, nodes.Set):
            return False
        return (
            self._common_cond_list_set(node, iter_obj, infer_val)
            and node.value.func.attrname in _SET_MODIFIER_METHODS
        )
References _common_cond_list_set(), and _is_node_expr_that_calls_attribute_name().
Referenced by _modified_iterating_check().
visit_for()
None pylint.checkers.modified_iterating_checker.ModifiedIterationChecker.visit_for (self, nodes.For node)
Definition at line 57 of file modified_iterating_checker.py.
    def visit_for(self, node: nodes.For) -> None:
        iter_obj = node.iter
        for body_node in node.body:
            self._modified_iterating_check_on_node_and_children(body_node, iter_obj)
References _modified_iterating_check_on_node_and_children().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pylint/checkers/modified_iterating_checker.py