Read&Watch: pip._vendor.rich.console.ConsoleThreadLocals Class Reference
pip._vendor.rich.console.ConsoleThreadLocals Class Reference
Static Public Attributes
List buffer = field(default_factory=list)
int buffer_index = 0
Detailed Description
Thread local values for Console context.
Definition at line 549 of file console.py.
Member Data Documentation
buffer
List pip._vendor.rich.console.ConsoleThreadLocals.buffer = field(default_factory=list) static
Definition at line 553 of file console.py.
Referenced by yaml.reader.Reader.check_printable(), yaml.reader.Reader.forward(), urllib3.response.BytesQueueBuffer.get(), urllib3.response.BytesQueueBuffer.get_all(), yaml.reader.Reader.get_mark(), yaml.error.Mark.get_snippet(), yaml.reader.Reader.peek(), yaml.reader.Reader.prefix(), urllib3.response.BytesQueueBuffer.put(), and yaml.reader.Reader.update().
buffer_index
int pip._vendor.rich.console.ConsoleThreadLocals.buffer_index = 0 static
Definition at line 554 of file console.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/rich/console.py