Read&Watch: pip._vendor.pygments.lexers.python.PythonConsoleLexer Class Reference
pip._vendor.pygments.lexers.python.PythonConsoleLexer Class Reference
Public Member Functions
__init__ (self, **options)
Public Member Functions inherited from pip._vendor.pygments.lexer.DelegatingLexer
__init__ (self, _root_lexer, _language_lexer, _needle=Other, **options)
get_tokens_unprocessed (self, text)
Public Member Functions inherited from pip._vendor.pygments.lexer.Lexer
__init__ (self, **options)
__repr__ (self)
add_filter (self, filter_, **options)
analyse_text (text)
get_tokens (self, text, unfiltered=False)
Public Member Functions inherited from pip._vendor.pygments.lexer.LexerMeta
__new__ (mcs, name, bases, d)
Additional Inherited Members
Public Attributes inherited from pip._vendor.pygments.lexer.DelegatingLexer
root_lexer = _root_lexer(**options)
language_lexer = _language_lexer(**options)
needle = _needle
Public Attributes inherited from pip._vendor.pygments.lexer.Lexer
options = options
stripnl = get_bool_opt(options, 'stripnl', True)
stripall = get_bool_opt(options, 'stripall', False)
ensurenl = get_bool_opt(options, 'ensurenl', True)
tabsize = get_int_opt(options, 'tabsize', 0)
str encoding = options.get('encoding', 'guess')
list filters = []
Static Public Attributes inherited from pip._vendor.pygments.lexer.Lexer
name = None
list aliases = []
list filenames = []
list alias_filenames = []
list mimetypes = []
int priority = 0
url = None
version_added = None
Protected Member Functions inherited from pip._vendor.pygments.lexer.Lexer
_preprocess_lexer_input (self, text)
Static Protected Attributes inherited from pip._vendor.pygments.lexer.Lexer
_example = None
Detailed Description
For Python console output or doctests, such as:
.. sourcecode:: pycon
    >>> a = 'foo'
    >>> print(a)
    foo
    >>> 1 / 0
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ZeroDivisionError: integer division or modulo by zero
Additional options:
`python3`
    Use Python 3 lexer for code.  Default is ``True``.
    .. versionadded:: 1.0
    .. versionchanged:: 2.5
       Now defaults to ``True``.
Definition at line 674 of file python.py.
Constructor & Destructor Documentation
__init__()
pip._vendor.pygments.lexers.python.PythonConsoleLexer.__init__ (self, ** options)
Definition at line 704 of file python.py.
    def __init__(self, **options):
        python3 = get_bool_opt(options, 'python3', True)
        if python3:
            pylexer = PythonLexer
            tblexer = PythonTracebackLexer
        else:
            pylexer = Python2Lexer
            tblexer = Python2TracebackLexer
        # We have two auxiliary lexers. Use DelegatingLexer twice with
        # different tokens.  TODO: DelegatingLexer should support this
        # directly, by accepting a tuplet of auxiliary lexers and a tuple of
        # distinguishing tokens. Then we wouldn't need this intermediary
        # class.
        class _ReplaceInnerCode(DelegatingLexer):
            def __init__(self, **options):
                super().__init__(pylexer, _PythonConsoleLexerBase, Other.Code, **options)
        super().__init__(tblexer, _ReplaceInnerCode, Other.Traceback, **options)
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/pygments/lexers/python.py