Read&Watch: requests.adapters.BaseAdapter Class Reference
requests.adapters.BaseAdapter Class Reference
Public Member Functions
__init__ (self)
send (self, request, stream=False, timeout=None, verify=True, cert=None, proxies=None)
close (self)
Detailed Description
The Base Transport Adapter
Definition at line 137 of file adapters.py.
Constructor & Destructor Documentation
__init__()
requests.adapters.BaseAdapter.__init__ (self)
Definition at line 140 of file adapters.py.
    def __init__(self):
        super().__init__()
Member Function Documentation
close()
requests.adapters.BaseAdapter.close (self)
Cleans up adapter specific items.
Reimplemented in requests.adapters.HTTPAdapter.
Definition at line 162 of file adapters.py.
    def close(self):
        """Cleans up adapter specific items."""
        raise NotImplementedError
Referenced by urllib3.contrib.emscripten.fetch._ReadStream.__del__(), django.db.backends.utils.CursorWrapper.__exit__(), pip._vendor.distlib.compat.ZipExtFile.__exit__(), pip._vendor.distlib.compat.ZipFile.__exit__(), requests.models.Response.__exit__(), requests.sessions.Session.__exit__(), urllib3.connectionpool.ConnectionPool.__exit__(), urllib3.util.ssltransport.SSLTransport.__exit__(), urllib3.contrib.pyopenssl.WrappedSocket._decref_socketios(), urllib3.connection.HTTPConnection._tunnel(), urllib3.response.HTTPResponse._update_chunk_length(), urllib3.contrib.emscripten.response.EmscriptenHttpResponseWrapper.drain_conn(), and urllib3.contrib.emscripten.fetch._ReadStream.readinto().
send()
requests.adapters.BaseAdapter.send (self, request, stream = False, timeout = None, verify = True, cert = None, proxies = None)
Sends PreparedRequest object. Returns Response object.
:param request: The :class:`PreparedRequest <PreparedRequest>` being sent.
:param stream: (optional) Whether to stream the request content.
:param timeout: (optional) How long to wait for the server to send
    data before giving up, as a float, or a :ref:`(connect timeout,
    read timeout) <timeouts>` tuple.
:type timeout: float or tuple
:param verify: (optional) Either a boolean, in which case it controls whether we verify
    the server's TLS certificate, or a string, in which case it must be a path
    to a CA bundle to use
:param cert: (optional) Any user-provided SSL certificate to be trusted.
:param proxies: (optional) The proxies dictionary to apply to the request.
Reimplemented in requests.adapters.HTTPAdapter.
Definition at line 143 of file adapters.py.
    ):
        """Sends PreparedRequest object. Returns Response object.
        :param request: The :class:`PreparedRequest <PreparedRequest>` being sent.
        :param stream: (optional) Whether to stream the request content.
        :param timeout: (optional) How long to wait for the server to send
            data before giving up, as a float, or a :ref:`(connect timeout,
            read timeout) <timeouts>` tuple.
        :type timeout: float or tuple
        :param verify: (optional) Either a boolean, in which case it controls whether we verify
            the server's TLS certificate, or a string, in which case it must be a path
            to a CA bundle to use
        :param cert: (optional) Any user-provided SSL certificate to be trusted.
        :param proxies: (optional) The proxies dictionary to apply to the request.
        """
        raise NotImplementedError
Referenced by urllib3.connection.HTTPConnection._tunnel(), requests.sessions.Session.request(), pip._vendor.urllib3.connection.HTTPConnection.request_chunked(), and urllib3.util.ssltransport.SSLTransport.sendall().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/requests/adapters.py