Read&Watch: pip._vendor.rich.highlighter.JSONHighlighter Class Reference
pip._vendor.rich.highlighter.JSONHighlighter Class Reference
Public Member Functions
None highlight (self, Text text)
Public Member Functions inherited from pip._vendor.rich.highlighter.Highlighter
Text __call__ (self, Union[str, Text] text)
Static Public Attributes
str JSON_STR = r"(?<![\\\w])(?P<str>b?\".*?(?<!\\‍)\")"
dict JSON_WHITESPACE = {" ", "\n", "\r", "\t"}
Static Public Attributes inherited from pip._vendor.rich.highlighter.RegexHighlighter
list highlights = []
str base_style = ""
Detailed Description
Highlights JSON
Definition at line 106 of file highlighter.py.
Member Function Documentation
highlight()
None pip._vendor.rich.highlighter.JSONHighlighter.highlight (self, Text text)
Highlight :class:`rich.text.Text` using regular expressions.
Args:
    text (~Text): Text to highlighted.
Reimplemented from pip._vendor.rich.highlighter.RegexHighlighter.
Definition at line 123 of file highlighter.py.
    def highlight(self, text: Text) -> None:
        super().highlight(text)
        # Additional work to handle highlighting JSON keys
        plain = text.plain
        append = text.spans.append
        whitespace = self.JSON_WHITESPACE
        for match in re.finditer(self.JSON_STR, plain):
            start, end = match.span()
            cursor = end
            while cursor < len(plain):
                char = plain[cursor]
                cursor += 1
                if char == ":":
                    append(Span(start, end, "json.key"))
                elif char in whitespace:
                    continue
                break
References highlight(), JSON_STR, and JSON_WHITESPACE.
Referenced by pip._vendor.rich.syntax.Syntax._get_syntax(), and highlight().
Member Data Documentation
JSON_STR
pip._vendor.rich.highlighter.JSONHighlighter.JSON_STR = r"(?<![\\\w])(?P<str>b?\".*?(?<!\\‍)\")" static
Definition at line 110 of file highlighter.py.
Referenced by highlight().
JSON_WHITESPACE
dict pip._vendor.rich.highlighter.JSONHighlighter.JSON_WHITESPACE = {" ", "\n", "\r", "\t"} static
Definition at line 111 of file highlighter.py.
Referenced by highlight().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/rich/highlighter.py