Read&Watch: django.core.validators.MaxLengthValidator Class Reference
django.core.validators.MaxLengthValidator Class Reference
Public Member Functions
compare (self, a, b)
clean (self, x)
Public Member Functions inherited from django.core.validators.BaseValidator
__init__ (self, limit_value, message=None)
__call__ (self, value)
__eq__ (self, other)
Additional Inherited Members
Public Attributes inherited from django.core.validators.BaseValidator
limit_value = limit_value
Static Public Attributes inherited from django.core.validators.BaseValidator
message = _("Ensure this value is %(limit_value)s (it is %(show_value)s).")
str code = "limit_value"
Detailed Description
Definition at line 507 of file validators.py.
Member Function Documentation
clean()
django.core.validators.MaxLengthValidator.clean (self, x)
Reimplemented from django.core.validators.BaseValidator.
Definition at line 520 of file validators.py.
    def clean(self, x):
        return len(x)
@deconstructible
Referenced by django.forms.fields.Field._clean_bound_field(), django.forms.fields.FileField._clean_bound_field(), django.forms.forms.BaseForm._clean_form(), django.db.models.base.Model.full_clean(), and movie.models.Movie.save().
compare()
django.core.validators.MaxLengthValidator.compare (self, a, b)
Reimplemented from django.core.validators.BaseValidator.
Definition at line 517 of file validators.py.
    def compare(self, a, b):
        return a > b
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/core/validators.py