Read&Watch: pylint.checkers.classes.special_methods_checker.SpecialMethodsChecker Class Reference
pylint.checkers.classes.special_methods_checker.SpecialMethodsChecker Class Reference
Public Member Functions
None __init__ (self, PyLinter linter)
None visit_functiondef (self, nodes.FunctionDef node)
Public Member Functions inherited from pylint.checkers.base_checker.BaseChecker
None __init__ (self, PyLinter linter)
bool __gt__ (self, Any other)
bool __eq__ (self, object other)
int __hash__ (self)
str __repr__ (self)
str __str__ (self)
str get_full_documentation (self, dict[str, MessageDefinitionTuple] msgs, Iterable[tuple[str, OptionDict, Any]] options, Sequence[tuple[str, str, ReportsCallable]] reports, str|None doc=None, str|None module=None, bool show_options=True)
None add_message (self, str msgid, int|None line=None, nodes.NodeNG|None node=None, Any args=None, Confidence|None confidence=None, int|None col_offset=None, int|None end_lineno=None, int|None end_col_offset=None)
None check_consistency (self)
MessageDefinition create_message_definition_from_tuple (self, str msgid, MessageDefinitionTuple msg_tuple)
list[MessageDefinition] messages (self)
None open (self)
None close (self)
Any get_map_data (self)
None reduce_map_data (self, PyLinter linter, list[Any] data)
Public Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
None __init__ (self, _ArgumentsManager arguments_manager)
Static Public Attributes
None visit_asyncfunctiondef = visit_functiondef
Static Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
str name = ""
dict msgs = {}
tuple reports = ()
bool enabled = True
Static Public Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
tuple options = ()
dict option_groups_descs = {}
Protected Member Functions
None _check_unexpected_method_signature (self, nodes.FunctionDef node)
None _check_iter (self, nodes.FunctionDef node, InferenceResult inferred)
None _check_len (self, nodes.FunctionDef node, InferenceResult inferred)
None _check_bool (self, nodes.FunctionDef node, InferenceResult inferred)
None _check_index (self, nodes.FunctionDef node, InferenceResult inferred)
None _check_repr (self, nodes.FunctionDef node, InferenceResult inferred)
None _check_str (self, nodes.FunctionDef node, InferenceResult inferred)
None _check_bytes (self, nodes.FunctionDef node, InferenceResult inferred)
None _check_hash (self, nodes.FunctionDef node, InferenceResult inferred)
None _check_length_hint (self, nodes.FunctionDef node, InferenceResult inferred)
None _check_format (self, nodes.FunctionDef node, InferenceResult inferred)
None _check_getnewargs (self, nodes.FunctionDef node, InferenceResult inferred)
None _check_getnewargs_ex (self, nodes.FunctionDef node, InferenceResult inferred)
Protected Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
Any _option_value (self, str opt)
Iterator[ tuple[str, list[tuple[str, OptionDict, Any]]]|tuple[None, dict[str, list[tuple[str, OptionDict, Any]]]]] _options_by_section (self)
Iterator[tuple[str, OptionDict, Any]] _options_and_values (self, Options|None options=None)
Static Protected Member Functions
bool _is_wrapped_type (InferenceResult node, str type_)
bool _is_int (InferenceResult node)
bool _is_str (InferenceResult node)
bool _is_bool (InferenceResult node)
bool _is_bytes (InferenceResult node)
bool _is_tuple (InferenceResult node)
bool _is_dict (InferenceResult node)
bool _is_iterator (InferenceResult node)
Protected Attributes
dict[ _protocol_map
_is_tuple
_is_dict
Protected Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
_arguments_manager = arguments_manager
Additional Inherited Members
Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
linter = linter
messages
Detailed Description
Checker which verifies that special methods
are implemented correctly.
Definition at line 56 of file special_methods_checker.py.
Constructor & Destructor Documentation
__init__()
None pylint.checkers.classes.special_methods_checker.SpecialMethodsChecker.__init__ (self, PyLinter linter)
Definition at line 145 of file special_methods_checker.py.
    def __init__(self, linter: PyLinter) -> None:
        super().__init__(linter)
        self._protocol_map: dict[
            str, Callable[[nodes.FunctionDef, InferenceResult], None]
        ] = {
            "__iter__": self._check_iter,
            "__len__": self._check_len,
            "__bool__": self._check_bool,
            "__index__": self._check_index,
            "__repr__": self._check_repr,
            "__str__": self._check_str,
            "__bytes__": self._check_bytes,
            "__hash__": self._check_hash,
            "__length_hint__": self._check_length_hint,
            "__format__": self._check_format,
            "__getnewargs__": self._check_getnewargs,
            "__getnewargs_ex__": self._check_getnewargs_ex,
        }
References __init__().
Referenced by __init__().
Member Function Documentation
_check_bool()
None pylint.checkers.classes.special_methods_checker.SpecialMethodsChecker._check_bool (self, nodes.FunctionDef node, InferenceResult inferred) protected
Definition at line 332 of file special_methods_checker.py.
    def _check_bool(self, node: nodes.FunctionDef, inferred: InferenceResult) -> None:
        if not self._is_bool(inferred):
            self.add_message("invalid-bool-returned", node=node)
References _is_bool(), and pylint.checkers.base_checker.BaseChecker.add_message().
_check_bytes()
None pylint.checkers.classes.special_methods_checker.SpecialMethodsChecker._check_bytes (self, nodes.FunctionDef node, InferenceResult inferred) protected
Definition at line 348 of file special_methods_checker.py.
    def _check_bytes(self, node: nodes.FunctionDef, inferred: InferenceResult) -> None:
        if not self._is_bytes(inferred):
            self.add_message("invalid-bytes-returned", node=node)
References _is_bytes(), and pylint.checkers.base_checker.BaseChecker.add_message().
_check_format()
None pylint.checkers.classes.special_methods_checker.SpecialMethodsChecker._check_format (self, nodes.FunctionDef node, InferenceResult inferred) protected
Definition at line 364 of file special_methods_checker.py.
    def _check_format(self, node: nodes.FunctionDef, inferred: InferenceResult) -> None:
        if not self._is_str(inferred):
            self.add_message("invalid-format-returned", node=node)
References _is_str(), and pylint.checkers.base_checker.BaseChecker.add_message().
_check_getnewargs()
None pylint.checkers.classes.special_methods_checker.SpecialMethodsChecker._check_getnewargs (self, nodes.FunctionDef node, InferenceResult inferred) protected
Definition at line 368 of file special_methods_checker.py.
    ) -> None:
        if not self._is_tuple(inferred):
            self.add_message("invalid-getnewargs-returned", node=node)
References _is_tuple, and pylint.checkers.base_checker.BaseChecker.add_message().
_check_getnewargs_ex()
None pylint.checkers.classes.special_methods_checker.SpecialMethodsChecker._check_getnewargs_ex (self, nodes.FunctionDef node, InferenceResult inferred) protected
Definition at line 374 of file special_methods_checker.py.
    ) -> None:
        if not self._is_tuple(inferred):
            self.add_message("invalid-getnewargs-ex-returned", node=node)
            return
        if not isinstance(inferred, nodes.Tuple):
            # If it's not an astroid.Tuple we can't analyze it further
            return
        found_error = False
        if len(inferred.elts) != 2:
            found_error = True
        else:
            for arg, check in (
                (inferred.elts[0], self._is_tuple),
                (inferred.elts[1], self._is_dict),
            ):
                if isinstance(arg, nodes.Call):
                    arg = safe_infer(arg)
                if arg and not isinstance(arg, util.UninferableBase):
                    if not check(arg):
                        found_error = True
                        break
        if found_error:
            self.add_message("invalid-getnewargs-ex-returned", node=node)
References _is_tuple, and pylint.checkers.base_checker.BaseChecker.add_message().
_check_hash()
None pylint.checkers.classes.special_methods_checker.SpecialMethodsChecker._check_hash (self, nodes.FunctionDef node, InferenceResult inferred) protected
Definition at line 352 of file special_methods_checker.py.
    def _check_hash(self, node: nodes.FunctionDef, inferred: InferenceResult) -> None:
        if not self._is_int(inferred):
            self.add_message("invalid-hash-returned", node=node)
References _is_int(), and pylint.checkers.base_checker.BaseChecker.add_message().
_check_index()
None pylint.checkers.classes.special_methods_checker.SpecialMethodsChecker._check_index (self, nodes.FunctionDef node, InferenceResult inferred) protected
Definition at line 336 of file special_methods_checker.py.
    def _check_index(self, node: nodes.FunctionDef, inferred: InferenceResult) -> None:
        if not self._is_int(inferred):
            self.add_message("invalid-index-returned", node=node)
References _is_int(), and pylint.checkers.base_checker.BaseChecker.add_message().
_check_iter()
None pylint.checkers.classes.special_methods_checker.SpecialMethodsChecker._check_iter (self, nodes.FunctionDef node, InferenceResult inferred) protected
Definition at line 322 of file special_methods_checker.py.
    def _check_iter(self, node: nodes.FunctionDef, inferred: InferenceResult) -> None:
        if not self._is_iterator(inferred):
            self.add_message("non-iterator-returned", node=node)
References _is_iterator(), and pylint.checkers.base_checker.BaseChecker.add_message().
_check_len()
None pylint.checkers.classes.special_methods_checker.SpecialMethodsChecker._check_len (self, nodes.FunctionDef node, InferenceResult inferred) protected
Definition at line 326 of file special_methods_checker.py.
    def _check_len(self, node: nodes.FunctionDef, inferred: InferenceResult) -> None:
        if not self._is_int(inferred):
            self.add_message("invalid-length-returned", node=node)
        elif isinstance(inferred, nodes.Const) and inferred.value < 0:
            self.add_message("invalid-length-returned", node=node)
References _is_int(), and pylint.checkers.base_checker.BaseChecker.add_message().
_check_length_hint()
None pylint.checkers.classes.special_methods_checker.SpecialMethodsChecker._check_length_hint (self, nodes.FunctionDef node, InferenceResult inferred) protected
Definition at line 356 of file special_methods_checker.py.
    ) -> None:
        if not self._is_int(inferred):
            self.add_message("invalid-length-hint-returned", node=node)
        elif isinstance(inferred, nodes.Const) and inferred.value < 0:
            self.add_message("invalid-length-hint-returned", node=node)
References _is_int(), and pylint.checkers.base_checker.BaseChecker.add_message().
_check_repr()
None pylint.checkers.classes.special_methods_checker.SpecialMethodsChecker._check_repr (self, nodes.FunctionDef node, InferenceResult inferred) protected
Definition at line 340 of file special_methods_checker.py.
    def _check_repr(self, node: nodes.FunctionDef, inferred: InferenceResult) -> None:
        if not self._is_str(inferred):
            self.add_message("invalid-repr-returned", node=node)
References _is_str(), and pylint.checkers.base_checker.BaseChecker.add_message().
_check_str()
None pylint.checkers.classes.special_methods_checker.SpecialMethodsChecker._check_str (self, nodes.FunctionDef node, InferenceResult inferred) protected
Definition at line 344 of file special_methods_checker.py.
    def _check_str(self, node: nodes.FunctionDef, inferred: InferenceResult) -> None:
        if not self._is_str(inferred):
            self.add_message("invalid-str-returned", node=node)
References _is_str(), and pylint.checkers.base_checker.BaseChecker.add_message().
_check_unexpected_method_signature()
None pylint.checkers.classes.special_methods_checker.SpecialMethodsChecker._check_unexpected_method_signature (self, nodes.FunctionDef node) protected
Definition at line 197 of file special_methods_checker.py.
    def _check_unexpected_method_signature(self, node: nodes.FunctionDef) -> None:
        expected_params = SPECIAL_METHODS_PARAMS[node.name]
        if expected_params is None:
            # This can support a variable number of parameters.
            return
        if not node.args.args and not node.args.vararg:
            # Method has no parameter, will be caught
            # by no-method-argument.
            return
        if decorated_with(node, ["builtins.staticmethod"]):
            # We expect to not take in consideration self.
            all_args = node.args.args
        else:
            all_args = node.args.args[1:]
        mandatory = len(all_args) - len(node.args.defaults)
        optional = len(node.args.defaults)
        current_params = mandatory + optional
        emit = False  # If we don't know we choose a false negative
        if isinstance(expected_params, tuple):
            # The expected number of parameters can be any value from this
            # tuple, although the user should implement the method
            # to take all of them in consideration.
            emit = mandatory not in expected_params
            # mypy thinks that expected_params has type tuple[int, int] | int | None
            # But at this point it must be 'tuple[int, int]' because of the type check
            expected_params = f"between {expected_params[0]} or {expected_params[1]}"  # type: ignore[assignment]
        else:
            # If the number of mandatory parameters doesn't
            # suffice, the expected parameters for this
            # function will be deduced from the optional
            # parameters.
            rest = expected_params - mandatory
            if rest == 0:
                emit = False
            elif rest < 0:
                emit = True
            elif rest > 0:
                emit = not ((optional - rest) >= 0 or node.args.vararg)
        if emit:
            verb = "was" if current_params <= 1 else "were"
            self.add_message(
                "unexpected-special-method-signature",
                args=(node.name, expected_params, current_params, verb),
                node=node,
            )
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_functiondef().
_is_bool()
bool pylint.checkers.classes.special_methods_checker.SpecialMethodsChecker._is_bool (InferenceResult node) static protected
Definition at line 270 of file special_methods_checker.py.
    def _is_bool(node: InferenceResult) -> bool:
        if SpecialMethodsChecker._is_wrapped_type(node, "bool"):
            return True
        return isinstance(node, nodes.Const) and isinstance(node.value, bool)
Referenced by _check_bool().
_is_bytes()
bool pylint.checkers.classes.special_methods_checker.SpecialMethodsChecker._is_bytes (InferenceResult node) static protected
Definition at line 277 of file special_methods_checker.py.
    def _is_bytes(node: InferenceResult) -> bool:
        if SpecialMethodsChecker._is_wrapped_type(node, "bytes"):
            return True
        return isinstance(node, nodes.Const) and isinstance(node.value, bytes)
Referenced by _check_bytes().
_is_dict()
bool pylint.checkers.classes.special_methods_checker.SpecialMethodsChecker._is_dict (InferenceResult node) static protected
Definition at line 291 of file special_methods_checker.py.
    def _is_dict(node: InferenceResult) -> bool:
        if SpecialMethodsChecker._is_wrapped_type(node, "dict"):
            return True
        return isinstance(node, nodes.Const) and isinstance(node.value, dict)
_is_int()
bool pylint.checkers.classes.special_methods_checker.SpecialMethodsChecker._is_int (InferenceResult node) static protected
Definition at line 256 of file special_methods_checker.py.
    def _is_int(node: InferenceResult) -> bool:
        if SpecialMethodsChecker._is_wrapped_type(node, "int"):
            return True
        return isinstance(node, nodes.Const) and isinstance(node.value, int)
Referenced by _check_hash(), _check_index(), _check_len(), and _check_length_hint().
_is_iterator()
bool pylint.checkers.classes.special_methods_checker.SpecialMethodsChecker._is_iterator (InferenceResult node) static protected
Definition at line 298 of file special_methods_checker.py.
    def _is_iterator(node: InferenceResult) -> bool:
        if isinstance(node, bases.Generator):
            # Generators can be iterated.
            return True
        if isinstance(node, nodes.ComprehensionScope):
            # Comprehensions can be iterated.
            return True
        if isinstance(node, bases.Instance):
            try:
                node.local_attr(NEXT_METHOD)
                return True
            except astroid.NotFoundError:
                pass
        elif isinstance(node, nodes.ClassDef):
            metaclass = node.metaclass()
            if metaclass and isinstance(metaclass, nodes.ClassDef):
                try:
                    metaclass.local_attr(NEXT_METHOD)
                    return True
                except astroid.NotFoundError:
                    pass
        return False
Referenced by _check_iter().
_is_str()
bool pylint.checkers.classes.special_methods_checker.SpecialMethodsChecker._is_str (InferenceResult node) static protected
Definition at line 263 of file special_methods_checker.py.
    def _is_str(node: InferenceResult) -> bool:
        if SpecialMethodsChecker._is_wrapped_type(node, "str"):
            return True
        return isinstance(node, nodes.Const) and isinstance(node.value, str)
Referenced by _check_format(), _check_repr(), and _check_str().
_is_tuple()
bool pylint.checkers.classes.special_methods_checker.SpecialMethodsChecker._is_tuple (InferenceResult node) static protected
Definition at line 284 of file special_methods_checker.py.
    def _is_tuple(node: InferenceResult) -> bool:
        if SpecialMethodsChecker._is_wrapped_type(node, "tuple"):
            return True
        return isinstance(node, nodes.Const) and isinstance(node.value, tuple)
_is_wrapped_type()
bool pylint.checkers.classes.special_methods_checker.SpecialMethodsChecker._is_wrapped_type (InferenceResult node, str type_) static protected
Definition at line 248 of file special_methods_checker.py.
    def _is_wrapped_type(node: InferenceResult, type_: str) -> bool:
        return (
            isinstance(node, bases.Instance)
            and node.name == type_
            and not isinstance(node, nodes.Const)
        )
visit_functiondef()
None pylint.checkers.classes.special_methods_checker.SpecialMethodsChecker.visit_functiondef (self, nodes.FunctionDef node)
Definition at line 179 of file special_methods_checker.py.
    def visit_functiondef(self, node: nodes.FunctionDef) -> None:
        if not node.is_method():
            return
        inferred = _safe_infer_call_result(node, node)
        # Only want to check types that we are able to infer
        if (
            inferred
            and node.name in self._protocol_map
            and not is_function_body_ellipsis(node)
        ):
            self._protocol_map[node.name](node, inferred)
        if node.name in PYMETHODS:
            self._check_unexpected_method_signature(node)
References _check_unexpected_method_signature(), _protocol_map, and pylint.checkers.classes.special_methods_checker._safe_infer_call_result().
Referenced by pylint.pyreverse.inspector.Linker.visit_assignname().
Member Data Documentation
_is_dict
pylint.checkers.classes.special_methods_checker.SpecialMethodsChecker._is_dict protected
Definition at line 392 of file special_methods_checker.py.
_is_tuple
pylint.checkers.classes.special_methods_checker.SpecialMethodsChecker._is_tuple protected
Definition at line 391 of file special_methods_checker.py.
Referenced by _check_getnewargs(), and _check_getnewargs_ex().
_protocol_map
dict[ pylint.checkers.classes.special_methods_checker.SpecialMethodsChecker._protocol_map protected
Definition at line 147 of file special_methods_checker.py.
Referenced by visit_functiondef().
visit_asyncfunctiondef
None pylint.checkers.classes.special_methods_checker.SpecialMethodsChecker.visit_asyncfunctiondef = visit_functiondef static
Definition at line 195 of file special_methods_checker.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pylint/checkers/classes/special_methods_checker.py