Read&Watch: django.template.base.Node Class Reference
django.template.base.Node Class Reference
Public Member Functions
render (self, context)
render_annotated (self, context)
get_nodes_by_type (self, nodetype)
Static Public Attributes
bool must_be_first = False
tuple child_nodelists = ("nodelist",)
token = None
Detailed Description
Definition at line 948 of file base.py.
Member Function Documentation
get_nodes_by_type()
django.template.base.Node.get_nodes_by_type (self, nodetype)
Return a list of all nodes (within this node and its nodelist)
of the given type
Definition at line 987 of file base.py.
    def get_nodes_by_type(self, nodetype):
        """
        Return a list of all nodes (within this node and its nodelist)
        of the given type
        """
        nodes = []
        if isinstance(self, nodetype):
            nodes.append(self)
        for attr in self.child_nodelists:
            nodelist = getattr(self, attr, None)
            if nodelist:
                nodes.extend(nodelist.get_nodes_by_type(nodetype))
        return nodes
References child_nodelists.
render()
django.template.base.Node.render (self, context)
Return the node rendered as a string.
Reimplemented in django.contrib.admin.templatetags.base.InclusionAdminNode, django.template.base.TextNode, django.template.base.VariableNode, django.template.defaulttags.AutoEscapeControlNode, django.template.defaulttags.CommentNode, django.template.defaulttags.CsrfTokenNode, django.template.defaulttags.CycleNode, django.template.defaulttags.DebugNode, django.template.defaulttags.FilterNode, django.template.defaulttags.FirstOfNode, django.template.defaulttags.ForNode, django.template.defaulttags.IfChangedNode, django.template.defaulttags.IfNode, django.template.defaulttags.LoadNode, django.template.defaulttags.LoremNode, django.template.defaulttags.NowNode, django.template.defaulttags.RegroupNode, django.template.defaulttags.ResetCycleNode, django.template.defaulttags.SpacelessNode, django.template.defaulttags.TemplateTagNode, django.template.defaulttags.URLNode, django.template.defaulttags.VerbatimNode, django.template.defaulttags.WidthRatioNode, django.template.defaulttags.WithNode, django.template.library.InclusionNode, django.template.library.SimpleNode, django.template.loader_tags.BlockNode, django.template.loader_tags.ExtendsNode, and django.template.loader_tags.IncludeNode.
Definition at line 955 of file base.py.
    def render(self, context):
        """
        Return the node rendered as a string.
        """
        pass
Referenced by pip._vendor.rich.progress.ProgressColumn.__call__(), pip._vendor.rich.layout.Layout.__rich_console__(), pip._vendor.rich.spinner.Spinner.__rich_console__(), pip._vendor.rich.spinner.Spinner.__rich_measure__(), pip._vendor.rich.console.Console.log(), pip._vendor.rich.console.Console.print(), django.templatetags.i18n.BlockTranslateNode.render(), pip._vendor.rich.console.Console.render(), pip._vendor.rich.console.Console.render_lines(), and pip._vendor.rich.console.Console.update_screen_lines().
render_annotated()
django.template.base.Node.render_annotated (self, context)
Render the node. If debug is True and an exception occurs during
rendering, the exception is annotated with contextual line information
where it occurred in the template. For internal usage this method is
preferred over using the render method directly.
Reimplemented in django.template.base.TextNode.
Definition at line 961 of file base.py.
    def render_annotated(self, context):
        """
        Render the node. If debug is True and an exception occurs during
        rendering, the exception is annotated with contextual line information
        where it occurred in the template. For internal usage this method is
        preferred over using the render method directly.
        """
        try:
            return self.render(context)
        except Exception as e:
            if context.template.engine.debug:
                # Store the actual node that caused the exception.
                if not hasattr(e, "_culprit_node"):
                    e._culprit_node = self
                if (
                    not hasattr(e, "template_debug")
                    and context.render_context.template.origin == e._culprit_node.origin
                ):
                    e.template_debug = (
                        context.render_context.template.get_exception_info(
                            e,
                            e._culprit_node.token,
                        )
                    )
            raise
Member Data Documentation
child_nodelists
tuple django.template.base.Node.child_nodelists = ("nodelist",) static
Definition at line 952 of file base.py.
Referenced by get_nodes_by_type().
must_be_first
bool django.template.base.Node.must_be_first = False static
Definition at line 951 of file base.py.
token
django.template.base.Node.token = None static
Definition at line 953 of file base.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/template/base.py