Read&Watch: django.forms.widgets.CheckboxInput Class Reference
django.forms.widgets.CheckboxInput Class Reference
Public Member Functions
__init__ (self, attrs=None, check_test=None)
format_value (self, value)
get_context (self, name, value, attrs)
value_from_datadict (self, data, files, name)
value_omitted_from_data (self, data, files, name)
Public Member Functions inherited from django.forms.widgets.Input
__init__ (self, attrs=None)
Public Member Functions inherited from django.forms.widgets.Widget
__init__ (self, attrs=None)
__deepcopy__ (self, memo)
is_hidden (self)
subwidgets (self, name, value, attrs=None)
render (self, name, value, attrs=None, renderer=None)
build_attrs (self, base_attrs, extra_attrs=None)
id_for_label (self, id_)
use_required_attribute (self, initial)
Public Member Functions inherited from django.forms.widgets.MediaDefiningClass
__new__ (mcs, name, bases, attrs)
Public Attributes
check_test = boolean_check if check_test is None else check_test
Public Attributes inherited from django.forms.widgets.Widget
dict attrs = {} if attrs is None else attrs.copy()
str input_type = "hidden" if hasattr(self, "input_type") else False
is_hidden
template_name
Additional Inherited Members
Static Public Attributes inherited from django.forms.widgets.Widget
bool needs_multipart_form = False
bool is_localized = False
bool is_required = False
bool supports_microseconds = True
bool use_fieldset = False
Protected Member Functions inherited from django.forms.widgets.Widget
_render (self, template_name, context, renderer=None)
Detailed Description
Definition at line 578 of file widgets.py.
Constructor & Destructor Documentation
__init__()
django.forms.widgets.CheckboxInput.__init__ (self, attrs = None, check_test = None)
Definition at line 582 of file widgets.py.
    def __init__(self, attrs=None, check_test=None):
        super().__init__(attrs)
        # check_test is a callable that takes a value and returns True
        # if the checkbox should be checked for that value.
        self.check_test = boolean_check if check_test is None else check_test
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Function Documentation
format_value()
django.forms.widgets.CheckboxInput.format_value (self, value)
Only return the 'value' attribute if value isn't empty.
Reimplemented from django.forms.widgets.Widget.
Definition at line 588 of file widgets.py.
    def format_value(self, value):
        """Only return the 'value' attribute if value isn't empty."""
        if value is True or value is False or value is None or value == "":
            return
        return str(value)
get_context()
django.forms.widgets.CheckboxInput.get_context (self, name, value, attrs)
Reimplemented from django.forms.widgets.Input.
Definition at line 594 of file widgets.py.
    def get_context(self, name, value, attrs):
        if self.check_test(value):
            attrs = {**(attrs or {}), "checked": True}
        return super().get_context(name, value, attrs)
References check_test, and get_context().
Referenced by get_context().
value_from_datadict()
django.forms.widgets.CheckboxInput.value_from_datadict (self, data, files, name)
Given a dictionary of data and this widget's name, return the value
of this widget or None if it's not provided.
Reimplemented from django.forms.widgets.Widget.
Definition at line 599 of file widgets.py.
    def value_from_datadict(self, data, files, name):
        if name not in data:
            # A missing value means False because HTML form submission does not
            # send results for unselected checkboxes.
            return False
        value = data.get(name)
        # Translate true and false strings to boolean values.
        values = {"true": True, "false": False}
        if isinstance(value, str):
            value = values.get(value.lower(), value)
        return bool(value)
value_omitted_from_data()
django.forms.widgets.CheckboxInput.value_omitted_from_data (self, data, files, name)
Reimplemented from django.forms.widgets.Widget.
Definition at line 611 of file widgets.py.
    def value_omitted_from_data(self, data, files, name):
        # HTML checkboxes don't appear in POST data if not checked, so it's
        # never known if the value is actually omitted.
        return False
Member Data Documentation
check_test
django.forms.widgets.CheckboxInput.check_test = boolean_check if check_test is None else check_test
Definition at line 586 of file widgets.py.
Referenced by get_context().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/forms/widgets.py