Read&Watch: pip._internal.utils.misc.HiddenText Class Reference
pip._internal.utils.misc.HiddenText Class Reference
Public Member Functions
str __repr__ (self)
str __str__ (self)
bool __eq__ (self, Any other)
Public Attributes
secret = other.secret
Detailed Description
Definition at line 541 of file misc.py.
Member Function Documentation
__eq__()
bool pip._internal.utils.misc.HiddenText.__eq__ (self, Any other)
Definition at line 552 of file misc.py.
    def __eq__(self, other: Any) -> bool:
        if type(self) is not type(other):
            return False
        # The string being used for redaction doesn't also have to match,
        # just the raw, original string.
        return self.secret == other.secret
Referenced by pip._vendor.distlib.version.Version.__ge__(), pip._vendor.distlib.version.Version.__gt__(), pip._vendor.distlib.version.Version.__le__(), dotenv.variables.Atom.__ne__(), pip._vendor.distlib.version.Matcher.__ne__(), pip._vendor.distlib.version.Version.__ne__(), pip._vendor.msgpack.ext.Timestamp.__ne__(), pip._vendor.urllib3._collections.HTTPHeaderDict.__ne__(), responses.BaseResponse.__ne__(), and urllib3._collections.HTTPHeaderDict.__ne__().
__repr__()
str pip._internal.utils.misc.HiddenText.__repr__ (self)
Definition at line 545 of file misc.py.
    def __repr__(self) -> str:
        return f"<HiddenText {str(self)!r}>"
__str__()
str pip._internal.utils.misc.HiddenText.__str__ (self)
Definition at line 548 of file misc.py.
    def __str__(self) -> str:
        return self.redacted
Member Data Documentation
secret
pip._internal.utils.misc.HiddenText.secret = other.secret
Definition at line 558 of file misc.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_internal/utils/misc.py