Read&Watch: isort.exceptions.ProfileDoesNotExist Class Reference
isort.exceptions.ProfileDoesNotExist Class Reference
Public Member Functions
__init__ (self, str profile)
Public Member Functions inherited from isort.exceptions.ISortError
__reduce__ (self)
Public Attributes
profile = profile
Detailed Description
Raised when a profile is set by the user that doesn't exist
Definition at line 80 of file exceptions.py.
Constructor & Destructor Documentation
__init__()
isort.exceptions.ProfileDoesNotExist.__init__ (self, str profile)
Definition at line 83 of file exceptions.py.
    def __init__(self, profile: str):
        super().__init__(
            f"Specified profile of {profile} does not exist. "
            f"Available profiles: {','.join(profiles)}."
        )
        self.profile = profile
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Data Documentation
profile
isort.exceptions.ProfileDoesNotExist.profile = profile
Definition at line 88 of file exceptions.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/isort/exceptions.py