Read&Watch: pip._internal.cli.command_context.CommandContextMixIn Class Reference
pip._internal.cli.command_context.CommandContextMixIn Class Reference
Public Member Functions
None __init__ (self)
Generator[None, None, None] main_context (self)
_T enter_context (self, ContextManager[_T] context_provider)
Protected Attributes
bool _in_main_context = False
_main_context = ExitStack()
Detailed Description
Definition at line 7 of file command_context.py.
Constructor & Destructor Documentation
__init__()
None pip._internal.cli.command_context.CommandContextMixIn.__init__ (self)
Definition at line 8 of file command_context.py.
    def __init__(self) -> None:
        super().__init__()
        self._in_main_context = False
        self._main_context = ExitStack()
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Function Documentation
enter_context()
_T pip._internal.cli.command_context.CommandContextMixIn.enter_context (self, ContextManager[_T] context_provider)
Definition at line 24 of file command_context.py.
    def enter_context(self, context_provider: ContextManager[_T]) -> _T:
        assert self._in_main_context
        return self._main_context.enter_context(context_provider)
References _in_main_context, _main_context, and enter_context().
Referenced by pip._internal.cli.base_command.Command._main(), enter_context(), pip._internal.cli.index_command.SessionCommandMixin.get_default_session(), pip._internal.commands.download.DownloadCommand.run(), pip._internal.commands.install.InstallCommand.run(), and pip._internal.commands.wheel.WheelCommand.run().
main_context()
Generator[None, None, None] pip._internal.cli.command_context.CommandContextMixIn.main_context (self)
Definition at line 14 of file command_context.py.
    def main_context(self) -> Generator[None, None, None]:
        assert not self._in_main_context
        self._in_main_context = True
        try:
            with self._main_context:
                yield
        finally:
            self._in_main_context = False
References _in_main_context, and _main_context.
Referenced by pip._internal.cli.base_command.Command.main().
Member Data Documentation
_in_main_context
bool pip._internal.cli.command_context.CommandContextMixIn._in_main_context = False protected
Definition at line 10 of file command_context.py.
Referenced by enter_context(), and main_context().
_main_context
pip._internal.cli.command_context.CommandContextMixIn._main_context = ExitStack() protected
Definition at line 11 of file command_context.py.
Referenced by enter_context(), and main_context().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_internal/cli/command_context.py