Read&Watch: isort.literal.ISortPrettyPrinter Class Reference
isort.literal.ISortPrettyPrinter Class Reference
Public Member Functions
__init__ (self, Config config)
Static Public Attributes
dict type_mapping = {}
Detailed Description
an isort customized pretty printer for sorted literals
Definition at line 13 of file literal.py.
Constructor & Destructor Documentation
__init__()
isort.literal.ISortPrettyPrinter.__init__ (self, Config config)
Definition at line 16 of file literal.py.
    def __init__(self, config: Config):
        super().__init__(width=config.line_length, compact=True)
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Data Documentation
type_mapping
dict isort.literal.ISortPrettyPrinter.type_mapping = {} static
Definition at line 20 of file literal.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/isort/literal.py