Read&Watch: django.contrib.auth.views.PasswordResetCompleteView Class Reference
django.contrib.auth.views.PasswordResetCompleteView Class Reference
Public Member Functions
get_context_data (self, **kwargs)
Public Member Functions inherited from django.views.generic.base.TemplateView
get (self, request, *args, **kwargs)
Public Member Functions inherited from django.views.generic.base.TemplateResponseMixin
render_to_response (self, context, **response_kwargs)
get_template_names (self)
Public Member Functions inherited from django.views.generic.base.View
__init__ (self, **kwargs)
view_is_async (cls)
as_view (cls, **initkwargs)
setup (self, request, *args, **kwargs)
dispatch (self, request, *args, **kwargs)
http_method_not_allowed (self, request, *args, **kwargs)
options (self, request, *args, **kwargs)
Additional Inherited Members
Public Attributes inherited from django.contrib.auth.views.PasswordContextMixin
title
Public Attributes inherited from django.views.generic.base.View
view_is_async = cls.dispatch.__annotations__
head = self.get
request = request
args = args
kwargs = kwargs
Static Public Attributes inherited from django.contrib.auth.views.PasswordContextMixin
extra_context = None
Static Public Attributes inherited from django.views.generic.base.TemplateResponseMixin
template_name = None
template_engine = None
response_class = TemplateResponse
content_type = None
Static Public Attributes inherited from django.views.generic.base.ContextMixin
extra_context = None
Static Public Attributes inherited from django.views.generic.base.View
list http_method_names
Protected Member Functions inherited from django.views.generic.base.View
_allowed_methods (self)
Detailed Description
Definition at line 343 of file views.py.
Member Function Documentation
get_context_data()
django.contrib.auth.views.PasswordResetCompleteView.get_context_data (self, ** kwargs)
Reimplemented from django.contrib.auth.views.PasswordContextMixin.
Definition at line 347 of file views.py.
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["login_url"] = resolve_url(settings.LOGIN_URL)
        return context
References get_context_data().
Referenced by django.views.generic.edit.FormMixin.form_invalid(), django.views.generic.base.TemplateView.get(), django.views.generic.edit.ProcessFormView.get(), get_context_data(), and django.contrib.syndication.views.Feed.get_feed().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/auth/views.py