Read&Watch: crispy_forms.bootstrap.FormActions Class Reference
crispy_forms.bootstrap.FormActions Class Reference
Public Member Functions
__init__ (self, *fields, css_id=None, css_class=None, template=None, **kwargs)
render (self, form, context, template_pack=TEMPLATE_PACK, **kwargs)
Public Member Functions inherited from crispy_forms.layout.LayoutObject
__getitem__ (self, slice)
__setitem__ (self, slice, value)
__delitem__ (self, slice)
__len__ (self)
__getattr__ (self, name)
get_field_names (self, index=None)
get_layout_objects (self, *LayoutClasses, index=None, max_level=0, greedy=False)
get_rendered_fields (self, form, context, template_pack=TEMPLATE_PACK, **kwargs)
Public Member Functions inherited from crispy_forms.layout.TemplateNameMixin
get_template_name (self, template_pack)
Public Attributes
id = css_id
css_class = css_class
flat_attrs = flatatt(kwargs)
Public Attributes inherited from crispy_forms.layout.LayoutObject
fields
Public Attributes inherited from crispy_forms.layout.TemplateNameMixin
template
Detailed Description
Bootstrap layout object. It wraps fields in a <div class="form-actions">
Attributes
----------
template: str
    The default template which this Layout Object will be rendered with.
Parameters
----------
*fields : HTML or BaseInput
    The layout objects to render within the ``ButtonHolder``. It should
    only hold `HTML` and `BaseInput` inherited objects.
css_id : str, optional
    A custom DOM id for the layout object which will be added to the
    ``<div>`` if provided. By default None.
css_class : str, optional
    Additional CSS classes to be applied to the ``<div>``. By default
    None.
template : str, optional
    Overrides the default template, if provided. By default None.
**kwargs : dict, optional
    Additional attributes are passed to ``flatatt`` and converted into
    key="value", pairs. These attributes are added to the ``<div>``.
Examples
--------
An example using ``FormActions`` in your layout::
    FormActions(
        HTML(<span style="display: hidden;">Information Saved</span>),
        Submit('Save', 'Save', css_class='btn-primary')
    )
Definition at line 259 of file bootstrap.py.
Constructor & Destructor Documentation
__init__()
crispy_forms.bootstrap.FormActions.__init__ (self, * fields, css_id = None, css_class = None, template = None, ** kwargs)
Definition at line 299 of file bootstrap.py.
    def __init__(self, *fields, css_id=None, css_class=None, template=None, **kwargs):
        self.fields = list(fields)
        self.id = css_id
        self.css_class = css_class
        self.template = template or self.template
        self.flat_attrs = flatatt(kwargs)
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
render()
crispy_forms.bootstrap.FormActions.render (self, form, context, template_pack = TEMPLATE_PACK, ** kwargs)
Definition at line 306 of file bootstrap.py.
    def render(self, form, context, template_pack=TEMPLATE_PACK, **kwargs):
        html = self.get_rendered_fields(form, context, template_pack, **kwargs)
        template = self.get_template_name(template_pack)
        context.update({"formactions": self, "fields_output": html})
        return render_to_string(template, context.flatten())
References crispy_forms.layout.LayoutObject.get_rendered_fields(), and crispy_forms.layout.TemplateNameMixin.get_template_name().
Referenced by pip._vendor.rich.progress.ProgressColumn.__call__(), pip._vendor.rich.layout.Layout.__rich_console__(), pip._vendor.rich.spinner.Spinner.__rich_console__(), pip._vendor.rich.spinner.Spinner.__rich_measure__(), django.forms.widgets.Media.__str__(), django.forms.utils.RenderableFieldMixin.as_field_group(), pip._vendor.rich.console.Console.log(), pip._vendor.rich.console.Console.print(), django.templatetags.i18n.BlockTranslateNode.render(), pip._vendor.rich.console.Console.render(), pip._vendor.rich.console.Console.render_lines(), django.db.migrations.writer.OperationWriter.serialize(), and pip._vendor.rich.console.Console.update_screen_lines().
Member Data Documentation
css_class
crispy_forms.bootstrap.FormActions.css_class = css_class
Definition at line 302 of file bootstrap.py.
Referenced by crispy_forms.bootstrap.Alert.__init__(), and crispy_forms.layout.MultiField.render().
flat_attrs
crispy_forms.bootstrap.FormActions.flat_attrs = flatatt(kwargs)
Definition at line 304 of file bootstrap.py.
id
crispy_forms.bootstrap.FormActions.id = css_id
Definition at line 301 of file bootstrap.py.
Referenced by django.core.checks.messages.CheckMessage.__repr__(), django.template.smartif.Literal.__repr__(), django.template.smartif.TokenBase.__repr__(), django.core.checks.messages.CheckMessage.__str__(), django.template.smartif.TokenBase.display(), pip._vendor.distro.distro.LinuxDistribution.info(), django.core.checks.messages.CheckMessage.is_silenced(), django.template.smartif.TokenBase.led(), pip._vendor.distro.distro.LinuxDistribution.linux_distribution(), django.template.smartif.TokenBase.nud(), and pip._vendor.distro.distro.LinuxDistribution.version().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/crispy_forms/bootstrap.py