Read&Watch: PIL.PngImagePlugin.PngImageFile Class Reference
PIL.PngImagePlugin.PngImageFile Class Reference
Image plugin for PNG images.
Public Member Functions
dict[str, str|iTXt] text (self)
None verify (self)
None seek (self, int frame)
int tell (self)
None load_prepare (self)
bytes load_read (self, int read_bytes)
None load_end (self)
Image.Exif getexif (self)
Public Member Functions inherited from PIL.ImageFile.ImageFile
None __init__ (self, StrOrBytesPath|IO[bytes] fp, str|bytes|None filename=None)
str|None get_format_mimetype (self)
None __setstate__ (self, list[Any] state)
Image.core.PixelAccess|None load (self)
Public Member Functions inherited from PIL.Image.Image
None __init__ (self)
core.ImagingCore im (self)
None im (self, core.ImagingCore im)
int width (self)
int height (self)
tuple[int, int] size (self)
str mode (self)
__enter__ (self)
__exit__ (self, *args)
None close (self)
bool __eq__ (self, object other)
str __repr__ (self)
dict[str, str|bytes|int|tuple[int,...]] __array_interface__ (self)
list[Any] __getstate__ (self)
None __setstate__ (self, list[Any] state)
bytes tobytes (self, str encoder_name="raw", *Any args)
bytes tobitmap (self, str name="image")
None frombytes (self, bytes|bytearray|SupportsArrayInterface data, str decoder_name="raw", *Any args)
Image convert (self, str|None mode=None, tuple[float,...]|None matrix=None, Dither|None dither=None, Palette palette=Palette.WEB, int colors=256)
Image quantize (self, int colors=256, int|None method=None, int kmeans=0, Image|None palette=None, Dither dither=Dither.FLOYDSTEINBERG)
Image copy (self)
Image crop (self, tuple[float, float, float, float]|None box=None)
tuple[str, tuple[int, int, float, float]]|None draft (self, str|None mode, tuple[int, int]|None size)
Image filter (self, ImageFilter.Filter|type[ImageFilter.Filter] filter)
tuple[str,...] getbands (self)
tuple[int, int, int, int]|None getbbox (self, *, bool alpha_only=True)
list[tuple[int, tuple[int,...]]]|list[tuple[int, float]]|None getcolors (self, int maxcolors=256)
core.ImagingCore getdata (self, int|None band=None)
tuple[float, float]|tuple[tuple[int, int],...] getextrema (self)
dict[str, Any] getxmp (self)
list[ImageFile.ImageFile] get_child_images (self)
CapsuleType getim (self)
list[int]|None getpalette (self, str|None rawmode="RGB")
bool has_transparency_data (self)
None apply_transparency (self)
float|tuple[int,...]|None getpixel (self, tuple[int, int]|list[int] xy)
tuple[list[int], list[int]] getprojection (self)
list[int] histogram (self, Image|None mask=None, tuple[float, float]|None extrema=None)
float entropy (self, Image|None mask=None, tuple[float, float]|None extrema=None)
None paste (self, Image|str|float|tuple[float,...] im, Image|tuple[int, int, int, int]|tuple[int, int]|None box=None, Image|None mask=None)
None alpha_composite (self, Image im, Sequence[int] dest=(0, 0), Sequence[int] source=(0, 0))
Image point (self,(Sequence[float]|NumpyArray|Callable[[int], float]|Callable[[ImagePointTransform], ImagePointTransform|float]|ImagePointHandler) lut, str|None mode=None)
None putalpha (self, Image|int alpha)
None putdata (self, Sequence[float]|Sequence[Sequence[int]]|core.ImagingCore|NumpyArray data, float scale=1.0, float offset=0.0)
None putpalette (self, ImagePalette.ImagePalette|bytes|Sequence[int] data, str rawmode="RGB")
None putpixel (self, tuple[int, int] xy, float|tuple[int,...]|list[int] value)
Image remap_palette (self, list[int] dest_map, bytes|bytearray|None source_palette=None)
Image resize (self, tuple[int, int]|list[int]|NumpyArray size, int|None resample=None, tuple[float, float, float, float]|None box=None, float|None reducing_gap=None)
Image reduce (self, int|tuple[int, int] factor, tuple[int, int, int, int]|None box=None)
Image rotate (self, float angle, Resampling resample=Resampling.NEAREST, int|bool expand=False, tuple[float, float]|None center=None, tuple[int, int]|None translate=None, float|tuple[float,...]|str|None fillcolor=None)
None save (self, StrOrBytesPath|IO[bytes] fp, str|None format=None, **Any params)
None show (self, str|None title=None)
tuple[Image,...] split (self)
Image getchannel (self, int|str channel)
None thumbnail (self, tuple[float, float] size, Resampling resample=Resampling.BICUBIC, float|None reducing_gap=2.0)
Image transform (self, tuple[int, int] size, Transform|ImageTransformHandler|SupportsGetData method, Sequence[Any]|None data=None, int resample=Resampling.NEAREST, int fill=1, float|tuple[float,...]|str|None fillcolor=None)
Image transpose (self, Transpose method)
Image effect_spread (self, int distance)
ImageQt.ImageQt toqimage (self)
ImageQt.QPixmap toqpixmap (self)
Public Attributes
list private_chunks = []
PngStream|None png = PngStream(self.fp)
PngStream|None n_frames = self.png.im_n_frames or 1
PngStream|None default_image = self.info.get("default_image", False)
PngStream|None is_animated = self.n_frames > 1
_imaging.ImagingCore|None dispose = f"cannot seek to frame {frame}"
PngStream|None dispose_op = self.info.get("disposal")
PngStream|None blend_op = self.info.get("blend")
tuple[float, float, float, float] dispose_extent = updated.convert("RGBA")
Public Attributes inherited from PIL.ImageFile.ImageFile
str|None custom_mimetype = None
list tile = []
tuple decoderconfig = ()
decodermaxblock = MAXBLOCK
str filename = os.path.realpath(os.fspath(fp))
Public Attributes inherited from PIL.Image.Image
ImagePalette.ImagePalette|None palette = None
dict info = {}
int readonly = 0
fp = self.tag_v2._endian
mmap.mmap|None map = None
core.ImagingCore im = self.im.copy()
str mode = other.mode
tuple[int, int] size = other.size
int width = 0:
encoderinfo = params
tuple encoderconfig = ()
Protected Member Functions
None _open (self)
None _seek (self, int frame, bool rewind=False)
dict[int, Any]|None _getexif (self)
Protected Member Functions inherited from PIL.ImageFile.ImageFile
bool _seek_check (self, int frame)
Protected Member Functions inherited from PIL.Image.Image
Image _new (self, core.ImagingCore im)
_close_fp (self)
None _copy (self)
None _ensure_mutable (self)
str _dump (self, str|None file=None, str|None format=None, **Any options)
None _repr_pretty_ (self, PrettyPrinter p, bool cycle)
bytes|None _repr_image (self, str image_format, **Any kwargs)
bytes|None _repr_png_ (self)
bytes|None _repr_jpeg_ (self)
core.ImagingCore _crop (self, core.ImagingCore im, tuple[float, float, float, float] box)
Image _expand (self, int xmargin, int|None ymargin=None)
None _reload_exif (self)
tuple[int, int, int, int] _get_safe_box (self, tuple[int, int] size, Resampling resample, tuple[float, float, float, float] box)
Protected Attributes
dict[str, str|iTXt]|None _text = None
_prev_im = None
Protected Attributes inherited from PIL.ImageFile.ImageFile
int _min_frame = 0
bool _exclusive_fp = True
Protected Attributes inherited from PIL.Image.Image
core.ImagingCore|DeferredError|None _im = None
str _mode = ""
tuple _size = (0, 0)
Exif|None _exif = None
_fp = DeferredError(ValueError("Operation on closed image"))
_new
Additional Inherited Members
Static Public Attributes inherited from PIL.Image.Image
str format = None
str format_description = None
Static Protected Attributes inherited from PIL.Image.Image
bool _close_exclusive_fp_after_loading = True
Detailed Description
Image plugin for PNG images.
Definition at line 750 of file PngImagePlugin.py.
Member Function Documentation
_getexif()
dict[int, Any] | None PIL.PngImagePlugin.PngImageFile._getexif (self) protected
Definition at line 1076 of file PngImagePlugin.py.
    def _getexif(self) -> dict[int, Any] | None:
        if "exif" not in self.info:
            self.load()
        if "exif" not in self.info and "Raw profile type exif" not in self.info:
            return None
        return self.getexif()._get_merged_dict()
_open()
None PIL.PngImagePlugin.PngImageFile._open (self) protected
Reimplemented from PIL.ImageFile.ImageFile.
Definition at line 754 of file PngImagePlugin.py.
    def _open(self) -> None:
        if not _accept(self.fp.read(8)):
            msg = "not a PNG file"
            raise SyntaxError(msg)
        self._fp = self.fp
        self.__frame = 0
        #
        # Parse headers up to the first IDAT or fDAT chunk
        self.private_chunks: list[tuple[bytes, bytes] | tuple[bytes, bytes, bool]] = []
        self.png: PngStream | None = PngStream(self.fp)
        while True:
            #
            # get next chunk
            cid, pos, length = self.png.read()
            try:
                s = self.png.call(cid, pos, length)
            except EOFError:
                break
            except AttributeError:
                logger.debug("%r %s %s (unknown)", cid, pos, length)
                s = ImageFile._safe_read(self.fp, length)
                if cid[1:2].islower():
                    self.private_chunks.append((cid, s))
            self.png.crc(cid, s)
        #
        # Copy relevant attributes from the PngStream.  An alternative
        # would be to let the PngStream class modify these attributes
        # directly, but that introduces circular references which are
        # difficult to break if things go wrong in the decoder...
        # (believe me, I've tried ;-)
        self._mode = self.png.im_mode
        self._size = self.png.im_size
        self.info = self.png.im_info
        self._text: dict[str, str | iTXt] | None = None
        self.tile = self.png.im_tile
        self.custom_mimetype = self.png.im_custom_mimetype
        self.n_frames = self.png.im_n_frames or 1
        self.default_image = self.info.get("default_image", False)
        if self.png.im_palette:
            rawmode, data = self.png.im_palette
            self.palette = ImagePalette.raw(rawmode, data)
        if cid == b"fdAT":
            self.__prepare_idat = length - 4
        else:
            self.__prepare_idat = length  # used by load_prepare()
        if self.png.im_n_frames is not None:
            self._close_exclusive_fp_after_loading = False
            self.png.save_rewind()
            self.__rewind_idat = self.__prepare_idat
            self.__rewind = self._fp.tell()
            if self.default_image:
                # IDAT chunk contains default image and not first animation frame
                self.n_frames += 1
            self._seek(0)
        self.is_animated = self.n_frames > 1
Referenced by django.core.files.storage.base.Storage.open().
_seek()
None PIL.PngImagePlugin.PngImageFile._seek (self, int frame, bool rewind = False) protected
Definition at line 870 of file PngImagePlugin.py.
    def _seek(self, frame: int, rewind: bool = False) -> None:
        assert self.png is not None
        self.dispose: _imaging.ImagingCore | None
        dispose_extent = None
        if frame == 0:
            if rewind:
                self._fp.seek(self.__rewind)
                self.png.rewind()
                self.__prepare_idat = self.__rewind_idat
                self._im = None
                self.info = self.png.im_info
                self.tile = self.png.im_tile
                self.fp = self._fp
            self._prev_im = None
            self.dispose = None
            self.default_image = self.info.get("default_image", False)
            self.dispose_op = self.info.get("disposal")
            self.blend_op = self.info.get("blend")
            dispose_extent = self.info.get("bbox")
            self.__frame = 0
        else:
            if frame != self.__frame + 1:
                msg = f"cannot seek to frame {frame}"
                raise ValueError(msg)
            # ensure previous frame was loaded
            self.load()
            if self.dispose:
                self.im.paste(self.dispose, self.dispose_extent)
            self._prev_im = self.im.copy()
            self.fp = self._fp
            # advance to the next frame
            if self.__prepare_idat:
                ImageFile._safe_read(self.fp, self.__prepare_idat)
                self.__prepare_idat = 0
            frame_start = False
            while True:
                self.fp.read(4)  # CRC
                try:
                    cid, pos, length = self.png.read()
                except (struct.error, SyntaxError):
                    break
                if cid == b"IEND":
                    msg = "No more images in APNG file"
                    raise EOFError(msg)
                if cid == b"fcTL":
                    if frame_start:
                        # there must be at least one fdAT chunk between fcTL chunks
                        msg = "APNG missing frame data"
                        raise SyntaxError(msg)
                    frame_start = True
                try:
                    self.png.call(cid, pos, length)
                except UnicodeDecodeError:
                    break
                except EOFError:
                    if cid == b"fdAT":
                        length -= 4
                        if frame_start:
                            self.__prepare_idat = length
                            break
                    ImageFile._safe_read(self.fp, length)
                except AttributeError:
                    logger.debug("%r %s %s (unknown)", cid, pos, length)
                    ImageFile._safe_read(self.fp, length)
            self.__frame = frame
            self.tile = self.png.im_tile
            self.dispose_op = self.info.get("disposal")
            self.blend_op = self.info.get("blend")
            dispose_extent = self.info.get("bbox")
            if not self.tile:
                msg = "image not found in APNG frame"
                raise EOFError(msg)
        if dispose_extent:
            self.dispose_extent: tuple[float, float, float, float] = dispose_extent
        # setup frame disposal (actual disposal done when needed in the next _seek())
        if self._prev_im is None and self.dispose_op == Disposal.OP_PREVIOUS:
            self.dispose_op = Disposal.OP_BACKGROUND
        self.dispose = None
        if self.dispose_op == Disposal.OP_PREVIOUS:
            if self._prev_im:
                self.dispose = self._prev_im.copy()
                self.dispose = self._crop(self.dispose, self.dispose_extent)
        elif self.dispose_op == Disposal.OP_BACKGROUND:
            self.dispose = Image.core.fill(self.mode, self.size)
            self.dispose = self._crop(self.dispose, self.dispose_extent)
Referenced by PIL.WebPImagePlugin.WebPImageFile.load(), PIL.TiffImagePlugin.TiffImageFile.n_frames(), and PIL.TiffImagePlugin.TiffImageFile.seek().
getexif()
Image.Exif PIL.PngImagePlugin.PngImageFile.getexif (self)
Gets EXIF data from the image.
:returns: an :py:class:`~PIL.Image.Exif` object.
Reimplemented from PIL.Image.Image.
Definition at line 1083 of file PngImagePlugin.py.
    def getexif(self) -> Image.Exif:
        if "exif" not in self.info:
            self.load()
        return super().getexif()
# --------------------------------------------------------------------
# PNG writer
load_end()
None PIL.PngImagePlugin.PngImageFile.load_end (self)
internal: finished reading image data
Reimplemented from PIL.ImageFile.ImageFile.
Definition at line 1014 of file PngImagePlugin.py.
    def load_end(self) -> None:
        """internal: finished reading image data"""
        assert self.png is not None
        if self.__idat != 0:
            self.fp.read(self.__idat)
        while True:
            self.fp.read(4)  # CRC
            try:
                cid, pos, length = self.png.read()
            except (struct.error, SyntaxError):
                break
            if cid == b"IEND":
                break
            elif cid == b"fcTL" and self.is_animated:
                # start of the next frame, stop reading
                self.__prepare_idat = 0
                self.png.push(cid, pos, length)
                break
            try:
                self.png.call(cid, pos, length)
            except UnicodeDecodeError:
                break
            except EOFError:
                if cid == b"fdAT":
                    length -= 4
                try:
                    ImageFile._safe_read(self.fp, length)
                except OSError as e:
                    if ImageFile.LOAD_TRUNCATED_IMAGES:
                        break
                    else:
                        raise e
            except AttributeError:
                logger.debug("%r %s %s (unknown)", cid, pos, length)
                s = ImageFile._safe_read(self.fp, length)
                if cid[1:2].islower():
                    self.private_chunks.append((cid, s, True))
        self._text = self.png.im_text
        if not self.is_animated:
            self.png.close()
            self.png = None
        else:
            if self._prev_im and self.blend_op == Blend.OP_OVER:
                updated = self._crop(self.im, self.dispose_extent)
                if self.im.mode == "RGB" and "transparency" in self.info:
                    mask = updated.convert_transparent(
                        "RGBA", self.info["transparency"]
                    )
                else:
                    if self.im.mode == "P" and "transparency" in self.info:
                        t = self.info["transparency"]
                        if isinstance(t, bytes):
                            updated.putpalettealphas(t)
                        elif isinstance(t, int):
                            updated.putpalettealpha(t)
                    mask = updated.convert("RGBA")
                self._prev_im.paste(updated, self.dispose_extent, mask)
                self.im = self._prev_im
load_prepare()
None PIL.PngImagePlugin.PngImageFile.load_prepare (self)
internal: prepare to read PNG file
Reimplemented from PIL.ImageFile.ImageFile.
Definition at line 971 of file PngImagePlugin.py.
    def load_prepare(self) -> None:
        """internal: prepare to read PNG file"""
        if self.info.get("interlace"):
            self.decoderconfig = self.decoderconfig + (1,)
        self.__idat = self.__prepare_idat  # used by load_read()
        ImageFile.ImageFile.load_prepare(self)
load_read()
bytes PIL.PngImagePlugin.PngImageFile.load_read (self, int read_bytes)
internal: read more image data
Definition at line 980 of file PngImagePlugin.py.
    def load_read(self, read_bytes: int) -> bytes:
        """internal: read more image data"""
        assert self.png is not None
        while self.__idat == 0:
            # end of chunk, skip forward to next one
            self.fp.read(4)  # CRC
            cid, pos, length = self.png.read()
            if cid not in [b"IDAT", b"DDAT", b"fdAT"]:
                self.png.push(cid, pos, length)
                return b""
            if cid == b"fdAT":
                try:
                    self.png.call(cid, pos, length)
                except EOFError:
                    pass
                self.__idat = length - 4  # sequence_num has already been read
            else:
                self.__idat = length  # empty chunks are allowed
        # read more data from this chunk
        if read_bytes <= 0:
            read_bytes = self.__idat
        else:
            read_bytes = min(read_bytes, self.__idat)
        self.__idat = self.__idat - read_bytes
        return self.fp.read(read_bytes)
seek()
None PIL.PngImagePlugin.PngImageFile.seek (self, int frame)
Seeks to the given frame in this sequence file. If you seek
beyond the end of the sequence, the method raises an
``EOFError`` exception. When a sequence file is opened, the
library automatically seeks to frame 0.
See :py:meth:`~PIL.Image.Image.tell`.
If defined, :attr:`~PIL.Image.Image.n_frames` refers to the
number of available frames.
:param frame: Frame number, starting at 0.
:exception EOFError: If the call attempts to seek beyond the end
    of the sequence.
Reimplemented from PIL.Image.Image.
Definition at line 855 of file PngImagePlugin.py.
    def seek(self, frame: int) -> None:
        if not self._seek_check(frame):
            return
        if frame < self.__frame:
            self._seek(0, True)
        last_frame = self.__frame
        for f in range(self.__frame + 1, frame + 1):
            try:
                self._seek(f)
            except EOFError as e:
                self.seek(last_frame)
                msg = "no more images in APNG file"
                raise EOFError(msg) from e
Referenced by pip._internal.network.lazy_wheel.LazyZipOverHTTP._download(), pip._internal.network.lazy_wheel.LazyZipOverHTTP._stay(), and django.utils.text.StreamingBuffer.read().
tell()
int PIL.PngImagePlugin.PngImageFile.tell (self)
Returns the current frame number. See :py:meth:`~PIL.Image.Image.seek`.
If defined, :attr:`~PIL.Image.Image.n_frames` refers to the
number of available frames.
:returns: Frame number, starting with 0.
Reimplemented from PIL.Image.Image.
Definition at line 968 of file PngImagePlugin.py.
    def tell(self) -> int:
        return self.__frame
Referenced by pip._internal.network.lazy_wheel.LazyZipOverHTTP._stay(), and pip._internal.network.lazy_wheel.LazyZipOverHTTP.read().
text()
dict[str, str | iTXt] PIL.PngImagePlugin.PngImageFile.text (self)
Definition at line 822 of file PngImagePlugin.py.
    def text(self) -> dict[str, str | iTXt]:
        # experimental
        if self._text is None:
            # iTxt, tEXt and zTXt chunks may appear at the end of the file
            # So load the file to ensure that they are read
            if self.is_animated:
                frame = self.__frame
                # for APNG, seek to the final frame before loading
                self.seek(self.n_frames - 1)
            self.load()
            if self.is_animated:
                self.seek(frame)
        assert self._text is not None
        return self._text
verify()
None PIL.PngImagePlugin.PngImageFile.verify (self)
Verify PNG file
Reimplemented from PIL.ImageFile.ImageFile.
Definition at line 837 of file PngImagePlugin.py.
    def verify(self) -> None:
        """Verify PNG file"""
        if self.fp is None:
            msg = "verify must be called directly after open"
            raise RuntimeError(msg)
        # back up to beginning of IDAT block
        self.fp.seek(self.tile[0][2] - 8)
        assert self.png is not None
        self.png.verify()
        self.png.close()
        if self._exclusive_fp:
            self.fp.close()
        self.fp = None
Member Data Documentation
_prev_im
PIL.PngImagePlugin.PngImageFile._prev_im = None protected
Definition at line 884 of file PngImagePlugin.py.
_text
dict[str, str | iTXt] | None PIL.PngImagePlugin.PngImageFile._text = None protected
Definition at line 795 of file PngImagePlugin.py.
Referenced by pylint.checkers.spelling.ForwardSlashChunker._next(), pip._vendor.rich.text.Text.append(), pip._vendor.rich.text.Text.append_text(), pip._vendor.rich.text.Text.append_tokens(), pip._vendor.pygments.lexer._PseudoMatch.end(), pip._vendor.rich.text.Text.expand_tabs(), pip._vendor.rich.text.Text.extend_style(), pip._vendor.pygments.lexer._PseudoMatch.group(), pip._vendor.pygments.lexer._PseudoMatch.groups(), pip._vendor.rich.text.Text.plain(), pip._vendor.rich.text.Text.plain(), pip._vendor.rich.text.Text.right_crop(), and pip._vendor.rich.text.Text.truncate().
blend_op
PngStream | None PIL.PngImagePlugin.PngImageFile.blend_op = self.info.get("blend")
Definition at line 888 of file PngImagePlugin.py.
default_image
PngStream | None PIL.PngImagePlugin.PngImageFile.default_image = self.info.get("default_image", False)
Definition at line 799 of file PngImagePlugin.py.
dispose
PIL.PngImagePlugin.PngImageFile.dispose = f"cannot seek to frame {frame}"
Definition at line 873 of file PngImagePlugin.py.
dispose_extent
PIL.PngImagePlugin.PngImageFile.dispose_extent = updated.convert("RGBA")
Definition at line 900 of file PngImagePlugin.py.
dispose_op
PngStream | None PIL.PngImagePlugin.PngImageFile.dispose_op = self.info.get("disposal")
Definition at line 887 of file PngImagePlugin.py.
is_animated
PngStream | None PIL.PngImagePlugin.PngImageFile.is_animated = self.n_frames > 1
Definition at line 819 of file PngImagePlugin.py.
n_frames
PngStream | None PIL.PngImagePlugin.PngImageFile.n_frames = self.png.im_n_frames or 1
Definition at line 798 of file PngImagePlugin.py.
png
PngStream | None PIL.PngImagePlugin.PngImageFile.png = PngStream(self.fp)
Definition at line 765 of file PngImagePlugin.py.
private_chunks
list PIL.PngImagePlugin.PngImageFile.private_chunks = []
Definition at line 764 of file PngImagePlugin.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/PIL/PngImagePlugin.py