Read&Watch: django.views.generic.list.BaseListView Class Reference
django.views.generic.list.BaseListView Class Reference
Public Member Functions
get (self, request, *args, **kwargs)
Public Member Functions inherited from django.views.generic.list.MultipleObjectMixin
get_queryset (self)
get_ordering (self)
paginate_queryset (self, queryset, page_size)
get_paginate_by (self, queryset)
get_paginator (self, queryset, per_page, orphans=0, allow_empty_first_page=True, **kwargs)
get_paginate_orphans (self)
get_allow_empty (self)
get_context_object_name (self, object_list)
get_context_data (self, *, object_list=None, **kwargs)
Public Member Functions inherited from django.views.generic.base.View
__init__ (self, **kwargs)
view_is_async (cls)
as_view (cls, **initkwargs)
setup (self, request, *args, **kwargs)
dispatch (self, request, *args, **kwargs)
http_method_not_allowed (self, request, *args, **kwargs)
options (self, request, *args, **kwargs)
Public Attributes
object_list = self.get_queryset()
Public Attributes inherited from django.views.generic.base.View
view_is_async = cls.dispatch.__annotations__
head = self.get
request = request
args = args
kwargs = kwargs
Additional Inherited Members
Static Public Attributes inherited from django.views.generic.list.MultipleObjectMixin
bool allow_empty = True
queryset = None
model = None
paginate_by = None
int paginate_orphans = 0
context_object_name = None
paginator_class = Paginator
str page_kwarg = "page"
ordering = None
Static Public Attributes inherited from django.views.generic.base.ContextMixin
extra_context = None
Static Public Attributes inherited from django.views.generic.base.View
list http_method_names
Protected Member Functions inherited from django.views.generic.base.View
_allowed_methods (self)
Detailed Description
A base view for displaying a list of objects.
Definition at line 150 of file list.py.
Member Function Documentation
get()
django.views.generic.list.BaseListView.get (self, request, * args, ** kwargs)
Reimplemented in django.contrib.admin.views.autocomplete.AutocompleteJsonView.
Definition at line 153 of file list.py.
    def get(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()
        allow_empty = self.get_allow_empty()
        if not allow_empty:
            # When pagination is enabled and object_list is a queryset,
            # it's better to do a cheap query than to load the unpaginated
            # queryset in memory.
            if self.get_paginate_by(self.object_list) is not None and hasattr(
                self.object_list, "exists"
            ):
                is_empty = not self.object_list.exists()
            else:
                is_empty = not self.object_list
            if is_empty:
                raise Http404(
                    _("Empty list and “%(class_name)s.allow_empty” is False.")
                    % {
                        "class_name": self.__class__.__name__,
                    }
                )
        context = self.get_context_data()
        return self.render_to_response(context)
Referenced by pip._vendor.distlib.metadata.LegacyMetadata.__getitem__(), pip._vendor.rich.layout.Layout.__getitem__(), django.test.client.ClientMixin._follow_redirect(), pip._vendor.distlib.metadata.LegacyMetadata.check(), PIL.Image.Exif.get_ifd(), and pip._vendor.distlib.metadata.LegacyMetadata.write_file().
Member Data Documentation
object_list
django.views.generic.list.BaseListView.object_list = self.get_queryset()
Definition at line 154 of file list.py.
Referenced by django.views.generic.list.MultipleObjectMixin.get_context_data().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/views/generic/list.py