Read&Watch: django.core.files.storage.DefaultStorage Class Reference
django.core.files.storage.DefaultStorage Class Reference
Protected Member Functions
_setup (self)
Additional Inherited Members
Public Member Functions inherited from django.utils.functional.LazyObject
__init__ (self)
__getattribute__ (self, name)
__setattr__ (self, name, value)
__delattr__ (self, name)
__reduce__ (self)
__copy__ (self)
__deepcopy__ (self, memo)
Static Protected Attributes inherited from django.utils.functional.LazyObject
_wrapped = None
Detailed Description
Definition at line 21 of file __init__.py.
Member Function Documentation
_setup()
django.core.files.storage.DefaultStorage._setup (self) protected
Must be implemented by subclasses to initialize the wrapped object.
Reimplemented from django.utils.functional.LazyObject.
Definition at line 22 of file __init__.py.
    def _setup(self):
        self._wrapped = storages[DEFAULT_STORAGE_ALIAS]
Referenced by django.utils.functional.LazyObject.__delattr__(), django.utils.functional.LazyObject.__reduce__(), django.utils.functional.LazyObject.__setattr__(), django.utils.text.Truncator.chars(), and django.utils.text.Truncator.words().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/core/files/storage/__init__.py