Read&Watch: django.core.checks.registry.CheckRegistry Class Reference
django.core.checks.registry.CheckRegistry Class Reference
Public Member Functions
__init__ (self)
register (self, check=None, *tags, **kwargs)
run_checks (self, app_configs=None, tags=None, include_deployment_checks=False, databases=None)
tag_exists (self, tag, include_deployment_checks=False)
tags_available (self, deployment_checks=False)
get_checks (self, include_deployment_checks=False)
Public Attributes
registered_checks = set()
deployment_checks = set()
Detailed Description
Definition at line 28 of file registry.py.
Constructor & Destructor Documentation
__init__()
django.core.checks.registry.CheckRegistry.__init__ (self)
Definition at line 29 of file registry.py.
    def __init__(self):
        self.registered_checks = set()
        self.deployment_checks = set()
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
get_checks()
django.core.checks.registry.CheckRegistry.get_checks (self, include_deployment_checks = False)
Definition at line 107 of file registry.py.
    def get_checks(self, include_deployment_checks=False):
        checks = list(self.registered_checks)
        if include_deployment_checks:
            checks.extend(self.deployment_checks)
        return checks
References deployment_checks, and registered_checks.
Referenced by run_checks(), and tags_available().
register()
django.core.checks.registry.CheckRegistry.register (self, check = None, * tags, ** kwargs)
Can be used as a function or a decorator. Register given function
`f` labeled with given `tags`. The function should receive **kwargs
and return list of Errors and Warnings.
Example::
    registry = CheckRegistry()
    @registry.register('mytag', 'anothertag')
    def my_check(app_configs, **kwargs):
        # ... perform checks and collect `errors` ...
        return errors
    # or
    registry.register(my_check, 'mytag', 'anothertag')
Definition at line 33 of file registry.py.
    def register(self, check=None, *tags, **kwargs):
        """
        Can be used as a function or a decorator. Register given function
        `f` labeled with given `tags`. The function should receive **kwargs
        and return list of Errors and Warnings.
        Example::
            registry = CheckRegistry()
            @registry.register('mytag', 'anothertag')
            def my_check(app_configs, **kwargs):
                # ... perform checks and collect `errors` ...
                return errors
            # or
            registry.register(my_check, 'mytag', 'anothertag')
        """
        def inner(check):
            if not func_accepts_kwargs(check):
                raise TypeError(
                    "Check functions must accept keyword arguments (**kwargs)."
                )
            check.tags = tags
            checks = (
                self.deployment_checks
                if kwargs.get("deploy")
                else self.registered_checks
            )
            checks.add(check)
            return check
        if callable(check):
            return inner(check)
        else:
            if check:
                tags += (check,)
            return inner
References deployment_checks, and registered_checks.
run_checks()
django.core.checks.registry.CheckRegistry.run_checks (self, app_configs = None, tags = None, include_deployment_checks = False, databases = None)
Run all registered checks and return list of Errors and Warnings.
Definition at line 71 of file registry.py.
    ):
        """
        Run all registered checks and return list of Errors and Warnings.
        """
        errors = []
        checks = self.get_checks(include_deployment_checks)
        if tags is not None:
            checks = [check for check in checks if not set(check.tags).isdisjoint(tags)]
        for check in checks:
            new_errors = check(app_configs=app_configs, databases=databases)
            if not isinstance(new_errors, Iterable):
                raise TypeError(
                    "The function %r did not return a list. All functions "
                    "registered with the checks registry must return a list." % check,
                )
            errors.extend(new_errors)
        return errors
References get_checks().
Referenced by django.test.runner.DiscoverRunner.run_tests().
tag_exists()
django.core.checks.registry.CheckRegistry.tag_exists (self, tag, include_deployment_checks = False)
Definition at line 97 of file registry.py.
    def tag_exists(self, tag, include_deployment_checks=False):
        return tag in self.tags_available(include_deployment_checks)
References tags_available().
tags_available()
django.core.checks.registry.CheckRegistry.tags_available (self, deployment_checks = False)
Definition at line 100 of file registry.py.
    def tags_available(self, deployment_checks=False):
        return set(
            chain.from_iterable(
                check.tags for check in self.get_checks(deployment_checks)
            )
        )
References get_checks().
Referenced by tag_exists().
Member Data Documentation
deployment_checks
django.core.checks.registry.CheckRegistry.deployment_checks = set()
Definition at line 31 of file registry.py.
Referenced by get_checks(), and register().
registered_checks
django.core.checks.registry.CheckRegistry.registered_checks = set()
Definition at line 30 of file registry.py.
Referenced by get_checks(), and register().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/core/checks/registry.py