Read&Watch: astroid.bases.BaseInstance Class Reference
astroid.bases.BaseInstance Class Reference
Public Member Functions
str display_type (self)
list[InferenceResult] getattr (self, str name, InferenceContext|None context=None, bool lookupclass=True)
Iterator[InferenceResult] igetattr (self, str name, InferenceContext|None context=None)
Iterator[InferenceResult] infer_call_result (self, SuccessfulInferenceResult|None caller, InferenceContext|None context=None)
Public Member Functions inherited from astroid.bases.Proxy
None __init__ (self,(nodes.ClassDef|nodes.FunctionDef|nodes.Lambda|UnboundMethod|None) proxied=None)
Any __getattr__ (self, str name)
collections.abc.Generator[InferenceResult, None, InferenceErrorInfo|None] infer (self, InferenceContext|None context=None, **Any kwargs)
Static Public Attributes
objectmodel special_attributes .ObjectModel
Protected Member Functions
Iterator[InferenceResult] _wrap_attr (self, Iterable[InferenceResult] attrs, InferenceContext|None context=None)
Additional Inherited Members
Static Protected Attributes inherited from astroid.bases.Proxy
nodes _proxied .ClassDef | nodes.FunctionDef | nodes.Lambda | UnboundMethod
Detailed Description
An instance base class, which provides lookup methods for potential
instances.
Definition at line 224 of file bases.py.
Member Function Documentation
_wrap_attr()
Iterator[InferenceResult] astroid.bases.BaseInstance._wrap_attr (self, Iterable[InferenceResult] attrs, InferenceContext | None context = None) protected
Wrap bound methods of attrs in a InstanceMethod proxies.
Definition at line 292 of file bases.py.
    ) -> Iterator[InferenceResult]:
        """Wrap bound methods of attrs in a InstanceMethod proxies."""
        for attr in attrs:
            if isinstance(attr, UnboundMethod):
                if _is_property(attr):
                    yield from attr.infer_call_result(self, context)
                else:
                    yield BoundMethod(attr, self)
            elif isinstance(attr, nodes.Lambda):
                if attr.args.arguments and attr.args.arguments[0].name == "self":
                    yield BoundMethod(attr, self)
                    continue
                yield attr
            else:
                yield attr
References astroid.bases._is_property().
Referenced by igetattr().
display_type()
str astroid.bases.BaseInstance.display_type (self)
Reimplemented in astroid.bases.AsyncGenerator, astroid.bases.Generator, astroid.bases.Instance, and astroid.bases.UnionType.
Definition at line 233 of file bases.py.
    def display_type(self) -> str:
        return "Instance of"
getattr()
list[InferenceResult] astroid.bases.BaseInstance.getattr (self, str name, InferenceContext | None context = None, bool lookupclass = True)
Definition at line 236 of file bases.py.
    ) -> list[InferenceResult]:
        try:
            values = self._proxied.instance_attr(name, context)
        except AttributeInferenceError as exc:
            if self.special_attributes and name in self.special_attributes:
                return [self.special_attributes.lookup(name)]
            if lookupclass:
                # Class attributes not available through the instance
                # unless they are explicitly defined.
                return self._proxied.getattr(name, context, class_context=False)
            raise AttributeInferenceError(
                target=self, attribute=name, context=context
            ) from exc
        # since we've no context information, return matching class members as
        # well
        if lookupclass:
            try:
                return values + self._proxied.getattr(
                    name, context, class_context=False
                )
            except AttributeInferenceError:
                pass
        return values
References astroid.bases.Proxy._proxied, getattr(), and special_attributes.
Referenced by astroid.bases.Instance.callable(), getattr(), igetattr(), astroid.nodes.node_classes.Slice.igetattr(), astroid.nodes.scoped_nodes.scoped_nodes.FunctionDef.igetattr(), astroid.nodes.scoped_nodes.scoped_nodes.Module.igetattr(), and astroid.nodes.scoped_nodes.scoped_nodes.Module.scope_lookup().
igetattr()
Iterator[InferenceResult] astroid.bases.BaseInstance.igetattr (self, str name, InferenceContext | None context = None)
Inferred getattr.
Definition at line 267 of file bases.py.
    ) -> Iterator[InferenceResult]:
        """Inferred getattr."""
        if not context:
            context = InferenceContext()
        try:
            context.lookupname = name
            # XXX frame should be self._proxied, or not ?
            get_attr = self.getattr(name, context, lookupclass=False)
            yield from _infer_stmts(
                self._wrap_attr(get_attr, context), context, frame=self
            )
        except AttributeInferenceError:
            try:
                # fallback to class.igetattr since it has some logic to handle
                # descriptors
                # But only if the _proxied is the Class.
                if self._proxied.__class__.__name__ != "ClassDef":
                    raise
                attrs = self._proxied.igetattr(name, context, class_context=False)
                yield from self._wrap_attr(attrs, context)
            except AttributeInferenceError as error:
                raise InferenceError(**vars(error)) from error
References astroid.bases._infer_stmts(), astroid.bases.Proxy._proxied, _wrap_attr(), getattr(), and igetattr().
Referenced by astroid.objects.Super.getattr(), astroid.bases.Instance.getitem(), igetattr(), and infer_call_result().
infer_call_result()
Iterator[InferenceResult] astroid.bases.BaseInstance.infer_call_result (self, SuccessfulInferenceResult | None caller, InferenceContext | None context = None)
Infer what a class instance is returning when called.
Definition at line 310 of file bases.py.
    ) -> Iterator[InferenceResult]:
        """Infer what a class instance is returning when called."""
        context = bind_context_to_node(context, self)
        inferred = False
        # If the call is an attribute on the instance, we infer the attribute itself
        if isinstance(caller, nodes.Call) and isinstance(caller.func, nodes.Attribute):
            for res in self.igetattr(caller.func.attrname, context):
                inferred = True
                yield res
        # Otherwise we infer the call to the __call__ dunder normally
        for node in self._proxied.igetattr("__call__", context):
            if isinstance(node, UninferableBase) or not node.callable():
                continue
            if isinstance(node, BaseInstance) and node._proxied is self._proxied:
                inferred = True
                yield node
                # Prevent recursion.
                continue
            for res in node.infer_call_result(caller, context):
                inferred = True
                yield res
        if not inferred:
            raise InferenceError(node=self, caller=caller, context=context)
References astroid.bases.Proxy._proxied, and igetattr().
Member Data Documentation
special_attributes
objectmodel astroid.bases.BaseInstance.special_attributes .ObjectModel static
Reimplemented in astroid.objects.ExceptionInstance.
Definition at line 231 of file bases.py.
Referenced by getattr(), astroid.bases.UnboundMethod.getattr(), astroid.nodes.scoped_nodes.scoped_nodes.FunctionDef.getattr(), astroid.nodes.scoped_nodes.scoped_nodes.Lambda.getattr(), astroid.nodes.scoped_nodes.scoped_nodes.Module.getattr(), astroid.bases.UnboundMethod.igetattr(), and astroid.objects.Super.igetattr().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/astroid/bases.py