Read&Watch: sqlparse.lexer.Lexer Class Reference
sqlparse.lexer.Lexer Class Reference
Public Member Functions
get_default_instance (cls)
default_initialization (self)
clear (self)
set_SQL_REGEX (self, SQL_REGEX)
add_keywords (self, keywords)
is_keyword (self, value)
get_tokens (self, text, encoding=None)
Protected Attributes
list _SQL_REGEX = []
list _keywords = []
Static Protected Attributes
_default_instance = None
_lock = Lock()
Detailed Description
The Lexer supports configurable syntax.
To add support for additional keywords, use the `add_keywords` method.
Definition at line 23 of file lexer.py.
Member Function Documentation
add_keywords()
sqlparse.lexer.Lexer.add_keywords (self, keywords)
Add keyword dictionaries. Keywords are looked up in the same order
that dictionaries were added.
Definition at line 89 of file lexer.py.
    def add_keywords(self, keywords):
        """Add keyword dictionaries. Keywords are looked up in the same order
        that dictionaries were added."""
        self._keywords.append(keywords)
clear()
sqlparse.lexer.Lexer.clear (self)
Clear all syntax configurations.
Useful if you want to load a reduced set of syntax configurations.
After this call, regexps and keyword dictionaries need to be loaded
to make the lexer functional again.
Definition at line 73 of file lexer.py.
    def clear(self):
        """Clear all syntax configurations.
        Useful if you want to load a reduced set of syntax configurations.
        After this call, regexps and keyword dictionaries need to be loaded
        to make the lexer functional again."""
        self._SQL_REGEX = []
        self._keywords = []
Referenced by urllib3.poolmanager.PoolManager.__exit__(), django.contrib.sessions.backends.cached_db.SessionStore.aflush(), and django.contrib.sessions.backends.cached_db.SessionStore.flush().
default_initialization()
sqlparse.lexer.Lexer.default_initialization (self)
Initialize the lexer with default dictionaries.
Useful if you need to revert custom syntax settings.
Definition at line 58 of file lexer.py.
    def default_initialization(self):
        """Initialize the lexer with default dictionaries.
        Useful if you need to revert custom syntax settings."""
        self.clear()
        self.set_SQL_REGEX(keywords.SQL_REGEX)
        self.add_keywords(keywords.KEYWORDS_COMMON)
        self.add_keywords(keywords.KEYWORDS_ORACLE)
        self.add_keywords(keywords.KEYWORDS_MYSQL)
        self.add_keywords(keywords.KEYWORDS_PLPGSQL)
        self.add_keywords(keywords.KEYWORDS_HQL)
        self.add_keywords(keywords.KEYWORDS_MSACCESS)
        self.add_keywords(keywords.KEYWORDS_SNOWFLAKE)
        self.add_keywords(keywords.KEYWORDS_BIGQUERY)
        self.add_keywords(keywords.KEYWORDS)
get_default_instance()
sqlparse.lexer.Lexer.get_default_instance (cls)
Returns the lexer instance used internally
by the sqlparse core functions.
Definition at line 49 of file lexer.py.
    def get_default_instance(cls):
        """Returns the lexer instance used internally
        by the sqlparse core functions."""
        with cls._lock:
            if cls._default_instance is None:
                cls._default_instance = cls()
                cls._default_instance.default_initialization()
        return cls._default_instance
get_tokens()
sqlparse.lexer.Lexer.get_tokens (self, text, encoding = None)
Return an iterable of (tokentype, value) pairs generated from
`text`. If `unfiltered` is set to `True`, the filtering mechanism
is bypassed even if filters are defined.
Also preprocess the text, i.e. expand tabs and strip it if
wanted and applies registered filters.
Split ``text`` into (tokentype, text) pairs.
``stack`` is the initial stack (default: ``['root']``)
Definition at line 107 of file lexer.py.
    def get_tokens(self, text, encoding=None):
        """
        Return an iterable of (tokentype, value) pairs generated from
        `text`. If `unfiltered` is set to `True`, the filtering mechanism
        is bypassed even if filters are defined.
        Also preprocess the text, i.e. expand tabs and strip it if
        wanted and applies registered filters.
        Split ``text`` into (tokentype, text) pairs.
        ``stack`` is the initial stack (default: ``['root']``)
        """
        if isinstance(text, TextIOBase):
            text = text.read()
        if isinstance(text, str):
            pass
        elif isinstance(text, bytes):
            if encoding:
                text = text.decode(encoding)
            else:
                try:
                    text = text.decode('utf-8')
                except UnicodeDecodeError:
                    text = text.decode('unicode-escape')
        else:
            raise TypeError("Expected text or file-like object, got {!r}".
                            format(type(text)))
        iterable = enumerate(text)
        for pos, char in iterable:
            for rexmatch, action in self._SQL_REGEX:
                m = rexmatch(text, pos)
                if not m:
                    continue
                elif isinstance(action, tokens._TokenType):
                    yield action, m.group()
                elif action is keywords.PROCESS_AS_KEYWORD:
                    yield self.is_keyword(m.group())
                consume(iterable, m.end() - pos - 1)
                break
            else:
                yield tokens.Error, char
is_keyword()
sqlparse.lexer.Lexer.is_keyword (self, value)
Checks for a keyword.
If the given value is in one of the KEYWORDS_* dictionary
it's considered a keyword. Otherwise, tokens.Name is returned.
Definition at line 94 of file lexer.py.
    def is_keyword(self, value):
        """Checks for a keyword.
        If the given value is in one of the KEYWORDS_* dictionary
        it's considered a keyword. Otherwise, tokens.Name is returned.
        """
        val = value.upper()
        for kwdict in self._keywords:
            if val in kwdict:
                return kwdict[val], value
        else:
            return tokens.Name, value
set_SQL_REGEX()
sqlparse.lexer.Lexer.set_SQL_REGEX (self, SQL_REGEX)
Set the list of regex that will parse the SQL.
Definition at line 81 of file lexer.py.
    def set_SQL_REGEX(self, SQL_REGEX):
        """Set the list of regex that will parse the SQL."""
        FLAGS = re.IGNORECASE | re.UNICODE
        self._SQL_REGEX = [
            (re.compile(rx, FLAGS).match, tt)
            for rx, tt in SQL_REGEX
        ]
Member Data Documentation
_default_instance
sqlparse.lexer.Lexer._default_instance = None static protected
Definition at line 27 of file lexer.py.
_keywords
list sqlparse.lexer.Lexer._keywords = [] protected
Definition at line 79 of file lexer.py.
_lock
sqlparse.lexer.Lexer._lock = Lock() static protected
Definition at line 28 of file lexer.py.
Referenced by urllib3.http2.probe._HTTP2ProbeCache._reset(), urllib3.http2.probe._HTTP2ProbeCache._values(), and urllib3.http2.probe._HTTP2ProbeCache.acquire_and_get().
_SQL_REGEX
list sqlparse.lexer.Lexer._SQL_REGEX = [] protected
Definition at line 78 of file lexer.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/sqlparse/lexer.py