Read&Watch: django.contrib.contenttypes.management.commands.remove_stale_contenttypes.Command Class Reference
django.contrib.contenttypes.management.commands.remove_stale_contenttypes.Command Class Reference
Public Member Functions
add_arguments (self, parser)
handle (self, **options)
Public Member Functions inherited from django.core.management.base.BaseCommand
__init__ (self, stdout=None, stderr=None, no_color=False, force_color=False)
get_version (self)
create_parser (self, prog_name, subcommand, **kwargs)
add_base_argument (self, parser, *args, **kwargs)
print_help (self, prog_name, subcommand)
run_from_argv (self, argv)
execute (self, *args, **options)
check (self, app_configs=None, tags=None, display_num_errors=False, include_deployment_checks=False, fail_level=checks.ERROR, databases=None)
check_migrations (self)
Additional Inherited Members
Public Attributes inherited from django.core.management.base.BaseCommand
stdout = OutputWrapper(stdout or sys.stdout)
stderr = OutputWrapper(stderr or sys.stderr)
style = no_style()
Static Public Attributes inherited from django.core.management.base.BaseCommand
str help = ""
bool output_transaction = False
bool requires_migrations_checks = False
str requires_system_checks = "__all__"
tuple base_stealth_options = ("stderr", "stdout")
tuple stealth_options = ()
suppressed_base_arguments = set()
Static Protected Attributes inherited from django.core.management.base.BaseCommand
bool _called_from_command_line = False
Detailed Description
Definition at line 10 of file remove_stale_contenttypes.py.
Member Function Documentation
add_arguments()
django.contrib.contenttypes.management.commands.remove_stale_contenttypes.Command.add_arguments (self, parser)
Entry point for subclassed commands to add custom arguments.
Reimplemented from django.core.management.base.BaseCommand.
Definition at line 13 of file remove_stale_contenttypes.py.
    def add_arguments(self, parser):
        parser.add_argument(
            "--noinput",
            "--no-input",
            action="store_false",
            dest="interactive",
            help="Tells Django to NOT prompt the user for input of any kind.",
        )
        parser.add_argument(
            "--database",
            default=DEFAULT_DB_ALIAS,
            choices=tuple(connections),
            help='Nominates the database to use. Defaults to the "default" database.',
        )
        parser.add_argument(
            "--include-stale-apps",
            action="store_true",
            default=False,
            help=(
                "Deletes stale content types including ones from previously "
                "installed apps that have been removed from INSTALLED_APPS."
            ),
        )
Referenced by django.core.management.base.BaseCommand.create_parser().
handle()
django.contrib.contenttypes.management.commands.remove_stale_contenttypes.Command.handle (self, ** args)
The actual logic of the command. Subclasses must implement
this method.
Reimplemented from django.core.management.base.BaseCommand.
Definition at line 37 of file remove_stale_contenttypes.py.
    def handle(self, **options):
        db = options["database"]
        include_stale_apps = options["include_stale_apps"]
        interactive = options["interactive"]
        verbosity = options["verbosity"]
        if not router.allow_migrate_model(db, ContentType):
            return
        ContentType.objects.clear_cache()
        apps_content_types = itertools.groupby(
            ContentType.objects.using(db).order_by("app_label", "model"),
            lambda obj: obj.app_label,
        )
        for app_label, content_types in apps_content_types:
            if not include_stale_apps and app_label not in apps.app_configs:
                continue
            to_remove = [ct for ct in content_types if ct.model_class() is None]
            # Confirm that the content type is stale before deletion.
            using = router.db_for_write(ContentType)
            if to_remove:
                if interactive:
                    ct_info = []
                    for ct in to_remove:
                        ct_info.append(
                            "    - Content type for %s.%s" % (ct.app_label, ct.model)
                        )
                        collector = NoFastDeleteCollector(using=using, origin=ct)
                        collector.collect([ct])
                        for obj_type, objs in collector.data.items():
                            if objs != {ct}:
                                ct_info.append(
                                    "    - %s %s object(s)"
                                    % (
                                        len(objs),
                                        obj_type._meta.label,
                                    )
                                )
                    content_type_display = "\n".join(ct_info)
                    self.stdout.write(
                        "Some content types in your database are stale and can be "
                        "deleted.\n"
                        "Any objects that depend on these content types will also be "
                        "deleted.\n"
                        "The content types and dependent objects that would be deleted "
                        "are:\n\n"
                        f"{content_type_display}\n\n"
                        "This list doesn't include any cascade deletions to data "
                        "outside of Django\n"
                        "models (uncommon).\n\n"
                        "Are you sure you want to delete these content types?\n"
                        "If you're unsure, answer 'no'."
                    )
                    ok_to_delete = input("Type 'yes' to continue, or 'no' to cancel: ")
                else:
                    ok_to_delete = "yes"
                if ok_to_delete == "yes":
                    for ct in to_remove:
                        if verbosity >= 2:
                            self.stdout.write(
                                "Deleting stale content type '%s | %s'"
                                % (ct.app_label, ct.model)
                            )
                        ct.delete()
                else:
                    if verbosity >= 2:
                        self.stdout.write("Stale content types remain.")
References django.core.management.base.BaseCommand.stdout.
Referenced by django.core.handlers.asgi.ASGIHandler.__call__(), and django.core.management.base.BaseCommand.execute().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/contenttypes/management/commands/remove_stale_contenttypes.py