Read&Watch: django.http.request.HttpHeaders Class Reference
django.http.request.HttpHeaders Class Reference
Public Member Functions
__init__ (self, environ)
__getitem__ (self, key)
parse_header_name (cls, header)
to_wsgi_name (cls, header)
to_asgi_name (cls, header)
to_wsgi_names (cls, headers)
to_asgi_names (cls, headers)
Public Member Functions inherited from django.utils.datastructures.CaseInsensitiveMapping
__init__ (self, data)
__getitem__ (self, key)
__len__ (self)
__eq__ (self, other)
__iter__ (self)
__repr__ (self)
copy (self)
Static Public Attributes
str HTTP_PREFIX = "HTTP_"
dict UNPREFIXED_HEADERS = {"CONTENT_TYPE", "CONTENT_LENGTH"}
Additional Inherited Members
Static Protected Member Functions inherited from django.utils.datastructures.CaseInsensitiveMapping
_unpack_items (data)
Protected Attributes inherited from django.utils.datastructures.CaseInsensitiveMapping
dict _store = {k.lower(): (k, v) for k, v in self._unpack_items(data)}
Detailed Description
Definition at line 433 of file request.py.
Constructor & Destructor Documentation
__init__()
django.http.request.HttpHeaders.__init__ (self, environ)
Definition at line 438 of file request.py.
    def __init__(self, environ):
        headers = {}
        for header, value in environ.items():
            name = self.parse_header_name(header)
            if name:
                headers[name] = value
        super().__init__(headers)
References __init__(), and parse_header_name().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Function Documentation
__getitem__()
django.http.request.HttpHeaders.__getitem__ (self, key)
Allow header lookup using underscores in place of hyphens.
Definition at line 446 of file request.py.
    def __getitem__(self, key):
        """Allow header lookup using underscores in place of hyphens."""
        return super().__getitem__(key.replace("_", "-"))
References __getitem__().
Referenced by __getitem__(), and django.test.utils.ContextList.get().
parse_header_name()
django.http.request.HttpHeaders.parse_header_name (cls, header)
Definition at line 451 of file request.py.
    def parse_header_name(cls, header):
        if header.startswith(cls.HTTP_PREFIX):
            header = header.removeprefix(cls.HTTP_PREFIX)
        elif header not in cls.UNPREFIXED_HEADERS:
            return None
        return header.replace("_", "-").title()
References HTTP_PREFIX, and UNPREFIXED_HEADERS.
Referenced by __init__().
to_asgi_name()
django.http.request.HttpHeaders.to_asgi_name (cls, header)
Definition at line 466 of file request.py.
    def to_asgi_name(cls, header):
        return header.replace("-", "_").upper()
Referenced by to_asgi_names().
to_asgi_names()
django.http.request.HttpHeaders.to_asgi_names (cls, headers)
Definition at line 477 of file request.py.
    def to_asgi_names(cls, headers):
        return {
            cls.to_asgi_name(header_name): value
            for header_name, value in headers.items()
        }
References to_asgi_name().
to_wsgi_name()
django.http.request.HttpHeaders.to_wsgi_name (cls, header)
Definition at line 459 of file request.py.
    def to_wsgi_name(cls, header):
        header = header.replace("-", "_").upper()
        if header in cls.UNPREFIXED_HEADERS:
            return header
        return f"{cls.HTTP_PREFIX}{header}"
References UNPREFIXED_HEADERS.
Referenced by to_wsgi_names().
to_wsgi_names()
django.http.request.HttpHeaders.to_wsgi_names (cls, headers)
Definition at line 470 of file request.py.
    def to_wsgi_names(cls, headers):
        return {
            cls.to_wsgi_name(header_name): value
            for header_name, value in headers.items()
        }
References to_wsgi_name().
Member Data Documentation
HTTP_PREFIX
django.http.request.HttpHeaders.HTTP_PREFIX = "HTTP_" static
Definition at line 434 of file request.py.
Referenced by parse_header_name().
UNPREFIXED_HEADERS
dict django.http.request.HttpHeaders.UNPREFIXED_HEADERS = {"CONTENT_TYPE", "CONTENT_LENGTH"} static
Definition at line 436 of file request.py.
Referenced by parse_header_name(), and to_wsgi_name().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/http/request.py