Read&Watch: dill.tests.test_classdef._class2 Class Reference
dill.tests.test_classdef._class2 Class Reference
Public Member Functions
__call__ (self)
ok (self)
Detailed Description
Definition at line 21 of file test_classdef.py.
Member Function Documentation
__call__()
dill.tests.test_classdef._class2.__call__ (self)
Definition at line 22 of file test_classdef.py.
    def __call__(self):
        pass
ok()
dill.tests.test_classdef._class2.ok (self)
Definition at line 24 of file test_classdef.py.
    def ok(self):
        return True
Referenced by pip._vendor.requests.models.Response.__bool__(), requests.models.Response.__bool__(), pip._vendor.requests.models.Response.__nonzero__(), and requests.models.Response.__nonzero__().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/dill/tests/test_classdef.py