Read&Watch: colorama.tests.isatty_test.IsattyTest Class Reference
colorama.tests.isatty_test.IsattyTest Class Reference
Public Member Functions
test_TTY (self)
test_nonTTY (self)
test_withPycharm (self)
test_withPycharmTTYOverride (self)
test_withPycharmNonTTYOverride (self)
test_withPycharmNoneOverride (self)
test_withPycharmStreamWrapped (self)
Detailed Description
Definition at line 12 of file isatty_test.py.
Member Function Documentation
test_nonTTY()
colorama.tests.isatty_test.IsattyTest.test_nonTTY (self)
Definition at line 20 of file isatty_test.py.
    def test_nonTTY(self):
        non_tty = StreamNonTTY()
        self.assertFalse(is_a_tty(non_tty))
        with pycharm():
            self.assertFalse(is_a_tty(non_tty))
References colorama.tests.isatty_test.is_a_tty().
test_TTY()
colorama.tests.isatty_test.IsattyTest.test_TTY (self)
Definition at line 14 of file isatty_test.py.
    def test_TTY(self):
        tty = StreamTTY()
        self.assertTrue(is_a_tty(tty))
        with pycharm():
            self.assertTrue(is_a_tty(tty))
References colorama.tests.isatty_test.is_a_tty().
test_withPycharm()
colorama.tests.isatty_test.IsattyTest.test_withPycharm (self)
Definition at line 26 of file isatty_test.py.
    def test_withPycharm(self):
        with pycharm():
            self.assertTrue(is_a_tty(sys.stderr))
            self.assertTrue(is_a_tty(sys.stdout))
References colorama.tests.isatty_test.is_a_tty().
test_withPycharmNoneOverride()
colorama.tests.isatty_test.IsattyTest.test_withPycharmNoneOverride (self)
Definition at line 41 of file isatty_test.py.
    def test_withPycharmNoneOverride(self):
        with pycharm():
            with replace_by(None), replace_original_by(None):
                self.assertFalse(is_a_tty(None))
                self.assertFalse(is_a_tty(StreamNonTTY()))
                self.assertTrue(is_a_tty(StreamTTY()))
References colorama.tests.isatty_test.is_a_tty().
test_withPycharmNonTTYOverride()
colorama.tests.isatty_test.IsattyTest.test_withPycharmNonTTYOverride (self)
Definition at line 36 of file isatty_test.py.
    def test_withPycharmNonTTYOverride(self):
        non_tty = StreamNonTTY()
        with pycharm(), replace_by(non_tty):
            self.assertFalse(is_a_tty(non_tty))
References colorama.tests.isatty_test.is_a_tty().
test_withPycharmStreamWrapped()
colorama.tests.isatty_test.IsattyTest.test_withPycharmStreamWrapped (self)
Definition at line 48 of file isatty_test.py.
    def test_withPycharmStreamWrapped(self):
        with pycharm():
            self.assertTrue(AnsiToWin32(StreamTTY()).stream.isatty())
            self.assertFalse(AnsiToWin32(StreamNonTTY()).stream.isatty())
            self.assertTrue(AnsiToWin32(sys.stdout).stream.isatty())
            self.assertTrue(AnsiToWin32(sys.stderr).stream.isatty())
test_withPycharmTTYOverride()
colorama.tests.isatty_test.IsattyTest.test_withPycharmTTYOverride (self)
Definition at line 31 of file isatty_test.py.
    def test_withPycharmTTYOverride(self):
        tty = StreamTTY()
        with pycharm(), replace_by(tty):
            self.assertTrue(is_a_tty(tty))
References colorama.tests.isatty_test.is_a_tty().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/colorama/tests/isatty_test.py