Read&Watch: pylint.checkers.strings.StringConstantChecker Class Reference
pylint.checkers.strings.StringConstantChecker Class Reference
Public Member Functions
None __init__ (self, PyLinter linter)
None process_module (self, nodes.Module node)
None process_tokens (self, list[tokenize.TokenInfo] tokens)
None visit_call (self, nodes.Call node)
None visit_list (self, nodes.List node)
None visit_set (self, nodes.Set node)
None visit_tuple (self, nodes.Tuple node)
None visit_assign (self, nodes.Assign node)
None check_for_consistent_string_delimiters (self, Iterable[tokenize.TokenInfo] tokens)
None check_for_concatenated_strings (self, Sequence[nodes.NodeNG] elements, str iterable_type)
None process_string_token (self, str token, int start_row, int start_col)
None process_non_raw_string_token (self, str prefix, str string_body, int start_row, int string_start_col)
None visit_const (self, nodes.Const node)
Public Member Functions inherited from pylint.checkers.base_checker.BaseChecker
None __init__ (self, PyLinter linter)
bool __gt__ (self, Any other)
bool __eq__ (self, object other)
int __hash__ (self)
str __repr__ (self)
str __str__ (self)
str get_full_documentation (self, dict[str, MessageDefinitionTuple] msgs, Iterable[tuple[str, OptionDict, Any]] options, Sequence[tuple[str, str, ReportsCallable]] reports, str|None doc=None, str|None module=None, bool show_options=True)
None add_message (self, str msgid, int|None line=None, nodes.NodeNG|None node=None, Any args=None, Confidence|None confidence=None, int|None col_offset=None, int|None end_lineno=None, int|None end_col_offset=None)
None check_consistency (self)
MessageDefinition create_message_definition_from_tuple (self, str msgid, MessageDefinitionTuple msg_tuple)
list[MessageDefinition] messages (self)
None open (self)
None close (self)
Any get_map_data (self)
None reduce_map_data (self, PyLinter linter, list[Any] data)
Public Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
None __init__ (self, _ArgumentsManager arguments_manager)
Public Attributes
dict[ string_tokens
Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
linter = linter
messages
Static Public Attributes
str ESCAPE_CHARACTERS = "abfnrtvx\n\r\t\\'\"01234567"
str UNICODE_ESCAPE_CHARACTERS = "uUN"
Static Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
str name = ""
dict msgs = {}
tuple reports = ()
bool enabled = True
Static Public Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
tuple options = ()
dict option_groups_descs = {}
Protected Member Functions
bool _is_initial_string_token (self, int index, Sequence[tokenize.TokenInfo] tokens)
bool _is_parenthesized (self, int index, list[tokenize.TokenInfo] tokens)
tokenize.TokenInfo|None _find_prev_token (self, int index, Sequence[tokenize.TokenInfo] tokens, *, tuple[int,...] ignore=_PAREN_IGNORE_TOKEN_TYPES)
tokenize.TokenInfo|None _find_next_token (self, int index, Sequence[tokenize.TokenInfo] tokens, *, tuple[int,...] ignore=_PAREN_IGNORE_TOKEN_TYPES)
None _detect_u_string_prefix (self, nodes.Const node)
Protected Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
Any _option_value (self, str opt)
Iterator[ tuple[str, list[tuple[str, OptionDict, Any]]]|tuple[None, dict[str, list[tuple[str, OptionDict, Any]]]]] _options_by_section (self)
Iterator[tuple[str, OptionDict, Any]] _options_and_values (self, Options|None options=None)
Protected Attributes
dict _parenthesized_string_tokens = {}
str _unicode_literals = "unicode_literals" in node.future_imports
Protected Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
_arguments_manager = arguments_manager
Detailed Description
Check string literals.
Definition at line 639 of file strings.py.
Constructor & Destructor Documentation
__init__()
None pylint.checkers.strings.StringConstantChecker.__init__ (self, PyLinter linter)
Definition at line 713 of file strings.py.
    def __init__(self, linter: PyLinter) -> None:
        super().__init__(linter)
        self.string_tokens: dict[
            tuple[int, int], tuple[str, tokenize.TokenInfo | None]
        ] = {}
        """Token position -> (token value, next token)."""
        self._parenthesized_string_tokens: dict[tuple[int, int], bool] = {}
References __init__().
Referenced by __init__().
Member Function Documentation
_detect_u_string_prefix()
None pylint.checkers.strings.StringConstantChecker._detect_u_string_prefix (self, nodes.Const node) protected
Check whether strings include a 'u' prefix like u'String'.
Definition at line 1006 of file strings.py.
    def _detect_u_string_prefix(self, node: nodes.Const) -> None:
        """Check whether strings include a 'u' prefix like u'String'."""
        if node.kind == "u":
            self.add_message(
                "redundant-u-string-prefix",
                line=node.lineno,
                col_offset=node.col_offset,
            )
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_const().
_find_next_token()
tokenize.TokenInfo | None pylint.checkers.strings.StringConstantChecker._find_next_token (self, int index, Sequence[tokenize.TokenInfo] tokens, * , tuple[int, ...] ignore = _PAREN_IGNORE_TOKEN_TYPES) protected
Definition at line 792 of file strings.py.
    ) -> tokenize.TokenInfo | None:
        i = index + 1
        while i < len(tokens) and tokens[i].type in ignore:
            i += 1
        return tokens[i] if i < len(tokens) else None
Referenced by _is_initial_string_token(), and _is_parenthesized().
_find_prev_token()
tokenize.TokenInfo | None pylint.checkers.strings.StringConstantChecker._find_prev_token (self, int index, Sequence[tokenize.TokenInfo] tokens, * , tuple[int, ...] ignore = _PAREN_IGNORE_TOKEN_TYPES) protected
Definition at line 780 of file strings.py.
    ) -> tokenize.TokenInfo | None:
        i = index - 1
        while i >= 0 and tokens[i].type in ignore:
            i -= 1
        return tokens[i] if i >= 0 else None
Referenced by _is_initial_string_token(), and _is_parenthesized().
_is_initial_string_token()
bool pylint.checkers.strings.StringConstantChecker._is_initial_string_token (self, int index, Sequence[tokenize.TokenInfo] tokens) protected
Definition at line 756 of file strings.py.
    ) -> bool:
        # Must NOT be preceded by a string literal
        prev_token = self._find_prev_token(index, tokens)
        if prev_token and prev_token.type == tokenize.STRING:
            return False
        # Must be followed by a string literal token.
        next_token = self._find_next_token(index, tokens)
        return bool(next_token and next_token.type == tokenize.STRING)
References _find_next_token(), and _find_prev_token().
Referenced by process_tokens().
_is_parenthesized()
bool pylint.checkers.strings.StringConstantChecker._is_parenthesized (self, int index, list[tokenize.TokenInfo] tokens) protected
Definition at line 767 of file strings.py.
    def _is_parenthesized(self, index: int, tokens: list[tokenize.TokenInfo]) -> bool:
        prev_token = self._find_prev_token(
            index, tokens, ignore=(*_PAREN_IGNORE_TOKEN_TYPES, tokenize.STRING)
        )
        if not prev_token or prev_token.type != tokenize.OP or prev_token[1] != "(":
            return False
        next_token = self._find_next_token(
            index, tokens, ignore=(*_PAREN_IGNORE_TOKEN_TYPES, tokenize.STRING)
        )
        return bool(
            next_token and next_token.type == tokenize.OP and next_token[1] == ")"
        )
References _find_next_token(), and _find_prev_token().
Referenced by process_tokens().
check_for_concatenated_strings()
None pylint.checkers.strings.StringConstantChecker.check_for_concatenated_strings (self, Sequence[nodes.NodeNG] elements, str iterable_type)
Definition at line 872 of file strings.py.
    ) -> None:
        for elt in elements:
            if not (
                isinstance(elt, nodes.Const) and elt.pytype() in _AST_NODE_STR_TYPES
            ):
                continue
            if elt.col_offset < 0:
                # This can happen in case of escaped newlines
                continue
            token_index = (elt.lineno, elt.col_offset)
            if token_index not in self.string_tokens:
                # This may happen with Latin1 encoding
                # cf. https://github.com/pylint-dev/pylint/issues/2610
                continue
            matching_token, next_token = self.string_tokens[token_index]
            # We detect string concatenation: the AST Const is the
            # combination of 2 string tokens
            if (
                matching_token != elt.value
                and next_token is not None
                and next_token.type == tokenize.STRING
            ):
                if next_token.start[0] == elt.lineno or (
                    self.linter.config.check_str_concat_over_line_jumps
                    # Allow implicitly concatenated strings in parens.
                    # See https://github.com/pylint-dev/pylint/issues/8552.
                    and not self._parenthesized_string_tokens.get(
                        (elt.lineno, elt.col_offset)
                    )
                ):
                    self.add_message(
                        "implicit-str-concat",
                        line=elt.lineno,
                        args=(iterable_type,),
                        confidence=HIGH,
                    )
References _parenthesized_string_tokens, pylint.checkers.base_checker.BaseChecker.add_message(), pylint.checkers.base_checker.BaseChecker.linter, and string_tokens.
Referenced by visit_assign(), visit_call(), visit_list(), visit_set(), and visit_tuple().
check_for_consistent_string_delimiters()
None pylint.checkers.strings.StringConstantChecker.check_for_consistent_string_delimiters (self, Iterable[tokenize.TokenInfo] tokens)
Adds a message for each string using inconsistent quote delimiters.
Quote delimiters are used inconsistently if " and ' are mixed in a module's
shortstrings without having done so to avoid escaping an internal quote
character.
Args:
  tokens: The tokens to be checked against for consistent usage.
Definition at line 824 of file strings.py.
    ) -> None:
        """Adds a message for each string using inconsistent quote delimiters.
        Quote delimiters are used inconsistently if " and ' are mixed in a module's
        shortstrings without having done so to avoid escaping an internal quote
        character.
        Args:
          tokens: The tokens to be checked against for consistent usage.
        """
        string_delimiters: Counter[str] = collections.Counter()
        inside_fstring = False  # whether token is inside f-string (since 3.12)
        target_py312 = self.linter.config.py_version >= (3, 12)
        # First, figure out which quote character predominates in the module
        for tok_type, token, _, _, _ in tokens:
            if sys.version_info[:2] >= (3, 12):
                # pylint: disable=no-member,useless-suppression
                if tok_type == tokenize.FSTRING_START:
                    inside_fstring = True
                elif tok_type == tokenize.FSTRING_END:
                    inside_fstring = False
                if inside_fstring and not target_py312:
                    # skip analysis of f-string contents
                    continue
            if tok_type == tokenize.STRING and _is_quote_delimiter_chosen_freely(token):
                string_delimiters[_get_quote_delimiter(token)] += 1
        if len(string_delimiters) > 1:
            # Ties are broken arbitrarily
            most_common_delimiter = string_delimiters.most_common(1)[0][0]
            for tok_type, token, start, _, _ in tokens:
                if tok_type != tokenize.STRING:
                    continue
                quote_delimiter = _get_quote_delimiter(token)
                if (
                    _is_quote_delimiter_chosen_freely(token)
                    and quote_delimiter != most_common_delimiter
                ):
                    self.add_message(
                        "inconsistent-quotes", line=start[0], args=(quote_delimiter,)
                    )
References pylint.checkers.strings._get_quote_delimiter(), pylint.checkers.strings._is_quote_delimiter_chosen_freely(), pylint.checkers.base_checker.BaseChecker.add_message(), and pylint.checkers.base_checker.BaseChecker.linter.
Referenced by process_tokens().
process_module()
None pylint.checkers.strings.StringConstantChecker.process_module (self, nodes.Module node)
Process a module.
The module's content is accessible via ``astroid.stream``
Reimplemented from pylint.checkers.base_checker.BaseRawFileChecker.
Definition at line 721 of file strings.py.
    def process_module(self, node: nodes.Module) -> None:
        self._unicode_literals = "unicode_literals" in node.future_imports
process_non_raw_string_token()
None pylint.checkers.strings.StringConstantChecker.process_non_raw_string_token (self, str prefix, str string_body, int start_row, int string_start_col)
Check for bad escapes in a non-raw string.
prefix: lowercase string of string prefix markers ('ur').
string_body: the un-parsed body of the string, not including the quote
marks.
start_row: line number in the source.
string_start_col: col number of the string start in the source.
Definition at line 937 of file strings.py.
    ) -> None:
        """Check for bad escapes in a non-raw string.
        prefix: lowercase string of string prefix markers ('ur').
        string_body: the un-parsed body of the string, not including the quote
        marks.
        start_row: line number in the source.
        string_start_col: col number of the string start in the source.
        """
        # Walk through the string; if we see a backslash then escape the next
        # character, and skip over it.  If we see a non-escaped character,
        # alert, and continue.
        #
        # Accept a backslash when it escapes a backslash, or a quote, or
        # end-of-line, or one of the letters that introduce a special escape
        # sequence <https://docs.python.org/reference/lexical_analysis.html>
        #
        index = 0
        while True:
            index = string_body.find("\\", index)
            if index == -1:
                break
            # There must be a next character; having a backslash at the end
            # of the string would be a SyntaxError.
            next_char = string_body[index + 1]
            match = string_body[index : index + 2]
            # The column offset will vary depending on whether the string token
            # is broken across lines. Calculate relative to the nearest line
            # break or relative to the start of the token's line.
            last_newline = string_body.rfind("\n", 0, index)
            if last_newline == -1:
                line = start_row
                col_offset = index + string_start_col
            else:
                line = start_row + string_body.count("\n", 0, index)
                col_offset = index - last_newline - 1
            if next_char in self.UNICODE_ESCAPE_CHARACTERS:
                if "u" in prefix:
                    pass
                elif "b" not in prefix:
                    pass  # unicode by default
                else:
                    self.add_message(
                        "anomalous-unicode-escape-in-string",
                        line=line,
                        args=(match,),
                        col_offset=col_offset,
                    )
            elif next_char not in self.ESCAPE_CHARACTERS:
                self.add_message(
                    "anomalous-backslash-in-string",
                    line=line,
                    args=(match,),
                    col_offset=col_offset,
                )
            # Whether it was a valid escape or not, backslash followed by
            # another character can always be consumed whole: the second
            # character can never be the start of a new backslash escape.
            index += 2
References pylint.checkers.base_checker.BaseChecker.add_message(), ESCAPE_CHARACTERS, and UNICODE_ESCAPE_CHARACTERS.
Referenced by process_string_token().
process_string_token()
None pylint.checkers.strings.StringConstantChecker.process_string_token (self, str token, int start_row, int start_col)
Definition at line 911 of file strings.py.
    def process_string_token(self, token: str, start_row: int, start_col: int) -> None:
        quote_char = None
        for _index, char in enumerate(token):
            if char in "'\"":
                quote_char = char
                break
        if quote_char is None:
            return
        # pylint: disable=undefined-loop-variable
        prefix = token[:_index].lower()  # markers like u, b, r.
        after_prefix = token[_index:]
        # pylint: enable=undefined-loop-variable
        # Chop off quotes
        quote_length = (
            3 if after_prefix[:3] == after_prefix[-3:] == 3 * quote_char else 1
        )
        string_body = after_prefix[quote_length:-quote_length]
        # No special checks on raw strings at the moment.
        if "r" not in prefix:
            self.process_non_raw_string_token(
                prefix,
                string_body,
                start_row,
                start_col + len(prefix) + quote_length,
            )
References process_non_raw_string_token().
Referenced by process_tokens().
process_tokens()
None pylint.checkers.strings.StringConstantChecker.process_tokens (self, list[tokenize.TokenInfo] tokens)
Should be overridden by subclasses.
Reimplemented from pylint.checkers.base_checker.BaseTokenChecker.
Definition at line 724 of file strings.py.
    def process_tokens(self, tokens: list[tokenize.TokenInfo]) -> None:
        encoding = "ascii"
        for i, (token_type, token, start, _, line) in enumerate(tokens):
            if token_type == tokenize.ENCODING:
                # this is always the first token processed
                encoding = token
            elif token_type == tokenize.STRING:
                # 'token' is the whole un-parsed token; we can look at the start
                # of it to see whether it's a raw or unicode string etc.
                self.process_string_token(token, start[0], start[1])
                # We figure the next token, ignoring comments & newlines:
                j = i + 1
                while j < len(tokens) and tokens[j].type in (
                    tokenize.NEWLINE,
                    tokenize.NL,
                    tokenize.COMMENT,
                ):
                    j += 1
                next_token = tokens[j] if j < len(tokens) else None
                if encoding != "ascii":
                    # We convert `tokenize` character count into a byte count,
                    # to match with astroid `.col_offset`
                    start = (start[0], len(line[: start[1]].encode(encoding)))
                self.string_tokens[start] = (str_eval(token), next_token)
                is_parenthesized = self._is_initial_string_token(
                    i, tokens
                ) and self._is_parenthesized(i, tokens)
                self._parenthesized_string_tokens[start] = is_parenthesized
        if self.linter.config.check_quote_consistency:
            self.check_for_consistent_string_delimiters(tokens)
References _is_initial_string_token(), _is_parenthesized(), _parenthesized_string_tokens, check_for_consistent_string_delimiters(), pylint.checkers.base_checker.BaseChecker.linter, process_string_token(), pylint.checkers.strings.str_eval(), and string_tokens.
Referenced by pylint.lint.pylinter.PyLinter._check_astroid_module().
visit_assign()
None pylint.checkers.strings.StringConstantChecker.visit_assign (self, nodes.Assign node)
Definition at line 820 of file strings.py.
    def visit_assign(self, node: nodes.Assign) -> None:
        if isinstance(node.value, nodes.Const) and isinstance(node.value.value, str):
            self.check_for_concatenated_strings([node.value], "assignment")
References check_for_concatenated_strings().
visit_call()
None pylint.checkers.strings.StringConstantChecker.visit_call (self, nodes.Call node)
Definition at line 805 of file strings.py.
    def visit_call(self, node: nodes.Call) -> None:
        self.check_for_concatenated_strings(node.args, "call")
References check_for_concatenated_strings().
visit_const()
None pylint.checkers.strings.StringConstantChecker.visit_const (self, nodes.Const node)
Definition at line 1000 of file strings.py.
    def visit_const(self, node: nodes.Const) -> None:
        if node.pytype() == "builtins.str" and not isinstance(
            node.parent, nodes.JoinedStr
        ):
            self._detect_u_string_prefix(node)
References _detect_u_string_prefix().
visit_list()
None pylint.checkers.strings.StringConstantChecker.visit_list (self, nodes.List node)
Definition at line 809 of file strings.py.
    def visit_list(self, node: nodes.List) -> None:
        self.check_for_concatenated_strings(node.elts, "list")
References check_for_concatenated_strings().
visit_set()
None pylint.checkers.strings.StringConstantChecker.visit_set (self, nodes.Set node)
Definition at line 813 of file strings.py.
    def visit_set(self, node: nodes.Set) -> None:
        self.check_for_concatenated_strings(node.elts, "set")
References check_for_concatenated_strings().
visit_tuple()
None pylint.checkers.strings.StringConstantChecker.visit_tuple (self, nodes.Tuple node)
Definition at line 817 of file strings.py.
    def visit_tuple(self, node: nodes.Tuple) -> None:
        self.check_for_concatenated_strings(node.elts, "tuple")
References check_for_concatenated_strings().
Member Data Documentation
_parenthesized_string_tokens
dict pylint.checkers.strings.StringConstantChecker._parenthesized_string_tokens = {} protected
Definition at line 719 of file strings.py.
Referenced by check_for_concatenated_strings(), and process_tokens().
_unicode_literals
str pylint.checkers.strings.StringConstantChecker._unicode_literals = "unicode_literals" in node.future_imports protected
Definition at line 722 of file strings.py.
ESCAPE_CHARACTERS
str pylint.checkers.strings.StringConstantChecker.ESCAPE_CHARACTERS = "abfnrtvx\n\r\t\\'\"01234567" static
Definition at line 707 of file strings.py.
Referenced by process_non_raw_string_token().
string_tokens
dict[ pylint.checkers.strings.StringConstantChecker.string_tokens
Definition at line 715 of file strings.py.
Referenced by check_for_concatenated_strings(), and process_tokens().
UNICODE_ESCAPE_CHARACTERS
str pylint.checkers.strings.StringConstantChecker.UNICODE_ESCAPE_CHARACTERS = "uUN" static
Definition at line 711 of file strings.py.
Referenced by process_non_raw_string_token().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pylint/checkers/strings.py