Read&Watch: pip._vendor.distlib.util.EventMixin Class Reference
pip._vendor.distlib.util.EventMixin Class Reference
Public Member Functions
__init__ (self)
add (self, event, subscriber, append=True)
remove (self, event, subscriber)
get_subscribers (self, event)
publish (self, event, *args, **kwargs)
Protected Attributes
dict _subscribers = {}
Detailed Description
A very simple publish/subscribe system.
Definition at line 1007 of file util.py.
Constructor & Destructor Documentation
__init__()
pip._vendor.distlib.util.EventMixin.__init__ (self)
Definition at line 1012 of file util.py.
    def __init__(self):
        self._subscribers = {}
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
add()
pip._vendor.distlib.util.EventMixin.add (self, event, subscriber, append = True)
Add a subscriber for an event.
:param event: The name of an event.
:param subscriber: The subscriber to be added (and called when the
                   event is published).
:param append: Whether to append or prepend the subscriber to an
               existing subscriber list for the event.
Definition at line 1015 of file util.py.
    def add(self, event, subscriber, append=True):
        """
        Add a subscriber for an event.
        :param event: The name of an event.
        :param subscriber: The subscriber to be added (and called when the
                           event is published).
        :param append: Whether to append or prepend the subscriber to an
                       existing subscriber list for the event.
        """
        subs = self._subscribers
        if event not in subs:
            subs[event] = deque([subscriber])
        else:
            sq = subs[event]
            if append:
                sq.append(subscriber)
            else:
                sq.appendleft(subscriber)
References _subscribers.
Referenced by responses.RequestsMock._add_from_file(), pip._vendor.urllib3._collections.HTTPHeaderDict.extend(), urllib3._collections.HTTPHeaderDict.extend(), and responses.RequestsMock.upsert().
get_subscribers()
pip._vendor.distlib.util.EventMixin.get_subscribers (self, event)
Return an iterator for the subscribers for an event.
:param event: The event to return subscribers for.
Definition at line 1047 of file util.py.
    def get_subscribers(self, event):
        """
        Return an iterator for the subscribers for an event.
        :param event: The event to return subscribers for.
        """
        return iter(self._subscribers.get(event, ()))
References _subscribers.
Referenced by publish().
publish()
pip._vendor.distlib.util.EventMixin.publish (self, event, * args, ** kwargs)
Publish a event and return a list of values returned by its
subscribers.
:param event: The event to publish.
:param args: The positional arguments to pass to the event's
             subscribers.
:param kwargs: The keyword arguments to pass to the event's
               subscribers.
Definition at line 1054 of file util.py.
    def publish(self, event, *args, **kwargs):
        """
        Publish a event and return a list of values returned by its
        subscribers.
        :param event: The event to publish.
        :param args: The positional arguments to pass to the event's
                     subscribers.
        :param kwargs: The keyword arguments to pass to the event's
                       subscribers.
        """
        result = []
        for subscriber in self.get_subscribers(event):
            try:
                value = subscriber(event, *args, **kwargs)
            except Exception:
                logger.exception('Exception during event publication')
                value = None
            result.append(value)
        logger.debug('publish %s: args = %s, kwargs = %s, result = %s', event, args, kwargs, result)
        return result
#
# Simple sequencing
#
References get_subscribers().
remove()
pip._vendor.distlib.util.EventMixin.remove (self, event, subscriber)
Remove a subscriber for an event.
:param event: The name of an event.
:param subscriber: The subscriber to be removed.
Definition at line 1035 of file util.py.
    def remove(self, event, subscriber):
        """
        Remove a subscriber for an event.
        :param event: The name of an event.
        :param subscriber: The subscriber to be removed.
        """
        subs = self._subscribers
        if event not in subs:
            raise ValueError('No subscribers: %r' % event)
        subs[event].remove(subscriber)
References _subscribers, and remove().
Referenced by tomlkit.container.Container.__delitem__(), tomlkit.items.AbstractTable.__delitem__(), tomlkit.container.Container._replace_at(), remove(), and pip._vendor.distlib.util.Sequencer.remove_node().
Member Data Documentation
_subscribers
dict pip._vendor.distlib.util.EventMixin._subscribers = {} protected
Definition at line 1013 of file util.py.
Referenced by add(), get_subscribers(), and remove().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/distlib/util.py