Read&Watch: pip._vendor.rich.control.Control Class Reference
pip._vendor.rich.control.Control Class Reference
Public Member Functions
None __init__ (self, *Union[ControlType, ControlCode] codes)
"Control" bell (cls)
"Control" home (cls)
"Control" move (cls, int x=0, int y=0)
"Control" move_to_column (cls, int x, int y=0)
"Control" move_to (cls, int x, int y)
"Control" clear (cls)
"Control" show_cursor (cls, bool show)
"Control" alt_screen (cls, bool enable)
"Control" title (cls, str title)
str __str__ (self)
"RenderResult" __rich_console__ (self, "Console" console, "ConsoleOptions" options)
Public Attributes
segment = Segment(rendered_codes, None, control_codes)
Detailed Description
A renderable that inserts a control code (non printable but may move cursor).
Args:
    *codes (str): Positional arguments are either a :class:`~rich.segment.ControlType` enum or a
        tuple of ControlType and an integer parameter
Definition at line 54 of file control.py.
Constructor & Destructor Documentation
__init__()
None pip._vendor.rich.control.Control.__init__ (self, *Union[ControlType, ControlCode] codes)
Definition at line 64 of file control.py.
    def __init__(self, *codes: Union[ControlType, ControlCode]) -> None:
        control_codes: List[ControlCode] = [
            (code,) if isinstance(code, ControlType) else code for code in codes
        ]
        _format_map = CONTROL_CODES_FORMAT
        rendered_codes = "".join(
            _format_map[code](*parameters) for code, *parameters in control_codes
        )
        self.segment = Segment(rendered_codes, None, control_codes)
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
__rich_console__()
"RenderResult" pip._vendor.rich.control.Control.__rich_console__ (self, "Console" console, "ConsoleOptions" options)
Definition at line 180 of file control.py.
    ) -> "RenderResult":
        if self.segment.text:
            yield self.segment
References segment.
__str__()
str pip._vendor.rich.control.Control.__str__ (self)
Definition at line 177 of file control.py.
    def __str__(self) -> str:
        return self.segment.text
References segment.
alt_screen()
"Control" pip._vendor.rich.control.Control.alt_screen (cls, bool enable)
Enable or disable alt screen.
Definition at line 161 of file control.py.
    def alt_screen(cls, enable: bool) -> "Control":
        """Enable or disable alt screen."""
        if enable:
            return cls(ControlType.ENABLE_ALT_SCREEN, ControlType.HOME)
        else:
            return cls(ControlType.DISABLE_ALT_SCREEN)
bell()
"Control" pip._vendor.rich.control.Control.bell (cls)
Ring the 'bell'.
Definition at line 75 of file control.py.
    def bell(cls) -> "Control":
        """Ring the 'bell'."""
        return cls(ControlType.BELL)
clear()
"Control" pip._vendor.rich.control.Control.clear (cls)
Clear the screen.
Definition at line 151 of file control.py.
    def clear(cls) -> "Control":
        """Clear the screen."""
        return cls(ControlType.CLEAR)
Referenced by pip._vendor.urllib3.poolmanager.PoolManager.__exit__(), urllib3.poolmanager.PoolManager.__exit__(), django.contrib.sessions.backends.cached_db.SessionStore.aflush(), and django.contrib.sessions.backends.cached_db.SessionStore.flush().
home()
"Control" pip._vendor.rich.control.Control.home (cls)
Move cursor to 'home' position.
Definition at line 80 of file control.py.
    def home(cls) -> "Control":
        """Move cursor to 'home' position."""
        return cls(ControlType.HOME)
move()
"Control" pip._vendor.rich.control.Control.move (cls, int x = 0, int y = 0)
Move cursor relative to current position.
Args:
    x (int): X offset.
    y (int): Y offset.
Returns:
    ~Control: Control object.
Definition at line 85 of file control.py.
    def move(cls, x: int = 0, y: int = 0) -> "Control":
        """Move cursor relative to current position.
        Args:
            x (int): X offset.
            y (int): Y offset.
        Returns:
            ~Control: Control object.
        """
        def get_codes() -> Iterable[ControlCode]:
            control = ControlType
            if x:
                yield (
                    control.CURSOR_FORWARD if x > 0 else control.CURSOR_BACKWARD,
                    abs(x),
                )
            if y:
                yield (
                    control.CURSOR_DOWN if y > 0 else control.CURSOR_UP,
                    abs(y),
                )
        control = cls(*get_codes())
        return control
move_to()
"Control" pip._vendor.rich.control.Control.move_to (cls, int x, int y)
Move cursor to absolute position.
Args:
    x (int): x offset (column)
    y (int): y offset (row)
Returns:
    ~Control: Control object.
Definition at line 138 of file control.py.
    def move_to(cls, x: int, y: int) -> "Control":
        """Move cursor to absolute position.
        Args:
            x (int): x offset (column)
            y (int): y offset (row)
        Returns:
            ~Control: Control object.
        """
        return cls((ControlType.CURSOR_MOVE_TO, x, y))
move_to_column()
"Control" pip._vendor.rich.control.Control.move_to_column (cls, int x, int y = 0)
Move to the given column, optionally add offset to row.
Returns:
    x (int): absolute x (column)
    y (int): optional y offset (row)
Returns:
    ~Control: Control object.
Definition at line 114 of file control.py.
    def move_to_column(cls, x: int, y: int = 0) -> "Control":
        """Move to the given column, optionally add offset to row.
        Returns:
            x (int): absolute x (column)
            y (int): optional y offset (row)
        Returns:
            ~Control: Control object.
        """
        return (
            cls(
                (ControlType.CURSOR_MOVE_TO_COLUMN, x),
                (
                    ControlType.CURSOR_DOWN if y > 0 else ControlType.CURSOR_UP,
                    abs(y),
                ),
            )
            if y
            else cls((ControlType.CURSOR_MOVE_TO_COLUMN, x))
        )
show_cursor()
"Control" pip._vendor.rich.control.Control.show_cursor (cls, bool show)
Show or hide the cursor.
Definition at line 156 of file control.py.
    def show_cursor(cls, show: bool) -> "Control":
        """Show or hide the cursor."""
        return cls(ControlType.SHOW_CURSOR if show else ControlType.HIDE_CURSOR)
title()
"Control" pip._vendor.rich.control.Control.title (cls, str title)
Set the terminal window title
Args:
    title (str): The new terminal window title
Definition at line 169 of file control.py.
    def title(cls, title: str) -> "Control":
        """Set the terminal window title
        Args:
            title (str): The new terminal window title
        """
        return cls((ControlType.SET_WINDOW_TITLE, title))
Member Data Documentation
segment
pip._vendor.rich.control.Control.segment = Segment(rendered_codes, None, control_codes)
Definition at line 72 of file control.py.
Referenced by __rich_console__(), and __str__().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/rich/control.py