Read&Watch: apscheduler.triggers.cron.expressions.WeekdayRangeExpression Class Reference
apscheduler.triggers.cron.expressions.WeekdayRangeExpression Class Reference
Public Member Functions
__init__ (self, first, last=None)
__str__ (self)
__repr__ (self)
Public Member Functions inherited from apscheduler.triggers.cron.expressions.RangeExpression
__init__ (self, first, last=None, step=None)
validate_range (self, field_name)
get_next_value (self, date, field)
__eq__ (self, other)
__str__ (self)
__repr__ (self)
Public Member Functions inherited from apscheduler.triggers.cron.expressions.AllExpression
__init__ (self, step=None)
__eq__ (self, other)
__str__ (self)
__repr__ (self)
Additional Inherited Members
Public Attributes inherited from apscheduler.triggers.cron.expressions.RangeExpression
first = first
last = last
Public Attributes inherited from apscheduler.triggers.cron.expressions.AllExpression
int step = asint(step)
Static Public Attributes inherited from apscheduler.triggers.cron.expressions.AllExpression
value_re = re.compile(r"\*(?:/(?P<step>\d+))?$")
Detailed Description
Definition at line 190 of file expressions.py.
Constructor & Destructor Documentation
__init__()
apscheduler.triggers.cron.expressions.WeekdayRangeExpression.__init__ (self, first, last = None)
Definition at line 193 of file expressions.py.
    def __init__(self, first, last=None):
        try:
            first_num = WEEKDAYS.index(first.lower())
        except ValueError:
            raise ValueError(f'Invalid weekday name "{first}"')
        if last:
            try:
                last_num = WEEKDAYS.index(last.lower())
            except ValueError:
                raise ValueError(f'Invalid weekday name "{last}"')
        else:
            last_num = None
        super().__init__(first_num, last_num)
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Function Documentation
__repr__()
apscheduler.triggers.cron.expressions.WeekdayRangeExpression.__repr__ (self)
Definition at line 214 of file expressions.py.
    def __repr__(self):
        args = [f"'{WEEKDAYS[self.first]}'"]
        if self.last != self.first and self.last is not None:
            args.append(f"'{WEEKDAYS[self.last]}'")
        return "{}({})".format(self.__class__.__name__, ", ".join(args))
References apscheduler.triggers.cron.expressions.AllExpression.__class__, apscheduler.triggers.cron.expressions.RangeExpression.first, and apscheduler.triggers.cron.expressions.RangeExpression.last.
__str__()
apscheduler.triggers.cron.expressions.WeekdayRangeExpression.__str__ (self)
Definition at line 209 of file expressions.py.
    def __str__(self):
        if self.last != self.first and self.last is not None:
            return f"{WEEKDAYS[self.first]}-{WEEKDAYS[self.last]}"
        return WEEKDAYS[self.first]
References apscheduler.triggers.cron.expressions.RangeExpression.first, and apscheduler.triggers.cron.expressions.RangeExpression.last.
Referenced by PIL.PdfParser.IndirectReference.__bytes__().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/apscheduler/triggers/cron/expressions.py