Read&Watch: pip._internal.utils.logging.IndentingFormatter Class Reference
pip._internal.utils.logging.IndentingFormatter Class Reference
Public Member Functions
None __init__ (self, *Any args, bool add_timestamp=False, **Any kwargs)
str get_message_start (self, str formatted, int levelno)
str format (self, logging.LogRecord record)
Public Attributes
add_timestamp = add_timestamp
Static Public Attributes
str default_time_format = "%Y-%m-%dT%H:%M:%S"
Detailed Description
Definition at line 73 of file logging.py.
Constructor & Destructor Documentation
__init__()
None pip._internal.utils.logging.IndentingFormatter.__init__ (self, *Any args, bool add_timestamp = False, **Any kwargs)
A logging.Formatter that obeys the indent_log() context manager.
:param add_timestamp: A bool indicating output lines should be prefixed
    with their record's timestamp.
Definition at line 76 of file logging.py.
    ) -> None:
        """
        A logging.Formatter that obeys the indent_log() context manager.
        :param add_timestamp: A bool indicating output lines should be prefixed
            with their record's timestamp.
        """
        self.add_timestamp = add_timestamp
        super().__init__(*args, **kwargs)
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
format()
str pip._internal.utils.logging.IndentingFormatter.format (self, logging.LogRecord record)
Calls the standard formatter, but will indent all of the log message
lines by our current indentation level.
Definition at line 107 of file logging.py.
    def format(self, record: logging.LogRecord) -> str:
        """
        Calls the standard formatter, but will indent all of the log message
        lines by our current indentation level.
        """
        formatted = super().format(record)
        message_start = self.get_message_start(formatted, record.levelno)
        formatted = message_start + formatted
        prefix = ""
        if self.add_timestamp:
            prefix = f"{self.formatTime(record)} "
        prefix += " " * get_indentation()
        formatted = "".join([prefix + line for line in formatted.splitlines(True)])
        return formatted
@dataclass
References add_timestamp, format(), pip._internal.utils.logging.get_indentation(), and get_message_start().
Referenced by django.utils.log.AdminEmailHandler.emit(), pip._internal.utils.logging.RichPipStreamHandler.emit(), pip._vendor.rich.logging.RichHandler.emit(), and format().
get_message_start()
str pip._internal.utils.logging.IndentingFormatter.get_message_start (self, str formatted, int levelno)
Return the start of the formatted log message (not counting the
prefix to add to each line).
Definition at line 91 of file logging.py.
    def get_message_start(self, formatted: str, levelno: int) -> str:
        """
        Return the start of the formatted log message (not counting the
        prefix to add to each line).
        """
        if levelno < logging.WARNING:
            return ""
        if formatted.startswith(DEPRECATION_MSG_PREFIX):
            # Then the message already has a prefix.  We don't want it to
            # look like "WARNING: DEPRECATION: ...."
            return ""
        if levelno < logging.ERROR:
            return "WARNING: "
        return "ERROR: "
Referenced by format().
Member Data Documentation
add_timestamp
pip._internal.utils.logging.IndentingFormatter.add_timestamp = add_timestamp
Definition at line 88 of file logging.py.
Referenced by format().
default_time_format
str pip._internal.utils.logging.IndentingFormatter.default_time_format = "%Y-%m-%dT%H:%M:%S" static
Definition at line 74 of file logging.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_internal/utils/logging.py