Read&Watch: apscheduler.executors.tornado.TornadoExecutor Class Reference
apscheduler.executors.tornado.TornadoExecutor Class Reference
Public Member Functions
__init__ (self, max_workers=10)
start (self, scheduler, alias)
Public Member Functions inherited from apscheduler.executors.base.BaseExecutor
__init__ (self)
shutdown (self, wait=True)
submit_job (self, job, run_times)
Public Attributes
executor = ThreadPoolExecutor(max_workers)
Protected Member Functions
_do_submit_job (self, job, run_times)
Protected Member Functions inherited from apscheduler.executors.base.BaseExecutor
_run_job_success (self, job_id, events)
_run_job_error (self, job_id, exc, traceback=None)
Protected Attributes
_ioloop = scheduler._ioloop
Protected Attributes inherited from apscheduler.executors.base.BaseExecutor
_instances = defaultdict(lambda: 0)
Additional Inherited Members
Static Protected Attributes inherited from apscheduler.executors.base.BaseExecutor
_scheduler = None
_lock = None
_logger = logging.getLogger("apscheduler.executors")
Detailed Description
Runs jobs either in a thread pool or directly on the I/O loop.
If the job function is a native coroutine function, it is scheduled to be run directly in the
I/O loop as soon as possible. All other functions are run in a thread pool.
Plugin alias: ``tornado``
:param int max_workers: maximum number of worker threads in the thread pool
Definition at line 10 of file tornado.py.
Constructor & Destructor Documentation
__init__()
apscheduler.executors.tornado.TornadoExecutor.__init__ (self, max_workers = 10)
Definition at line 22 of file tornado.py.
    def __init__(self, max_workers=10):
        super().__init__()
        self.executor = ThreadPoolExecutor(max_workers)
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Function Documentation
_do_submit_job()
apscheduler.executors.tornado.TornadoExecutor._do_submit_job (self, job, run_times) protected
Performs the actual task of scheduling `run_job` to be called.
Reimplemented from apscheduler.executors.base.BaseExecutor.
Definition at line 30 of file tornado.py.
    def _do_submit_job(self, job, run_times):
        def callback(f):
            try:
                events = f.result()
            except BaseException:
                self._run_job_error(job.id, *sys.exc_info()[1:])
            else:
                self._run_job_success(job.id, events)
        if iscoroutinefunction_partial(job.func):
            f = run_coroutine_job(
                job, job._jobstore_alias, run_times, self._logger.name
            )
        else:
            f = self.executor.submit(
                run_job, job, job._jobstore_alias, run_times, self._logger.name
            )
        f = convert_yielded(f)
        f.add_done_callback(callback)
References apscheduler.executors.base.BaseExecutor._logger, apscheduler.executors.base.BaseExecutor._run_job_error(), apscheduler.executors.base.BaseExecutor._run_job_success(), and executor.
start()
apscheduler.executors.tornado.TornadoExecutor.start (self, scheduler, alias)
Called by the scheduler when the scheduler is being started or when the executor is being
added to an already running scheduler.
:param apscheduler.schedulers.base.BaseScheduler scheduler: the scheduler that is starting
    this executor
:param str|unicode alias: alias of this executor as it was assigned to the scheduler
Reimplemented from apscheduler.executors.base.BaseExecutor.
Definition at line 26 of file tornado.py.
    def start(self, scheduler, alias):
        super().start(scheduler, alias)
        self._ioloop = scheduler._ioloop
References start().
Referenced by pip._vendor.rich.live.Live.__enter__(), pip._vendor.rich.progress._TrackThread.__enter__(), pip._vendor.rich.progress.Progress.__enter__(), pip._vendor.rich.status.Status.__enter__(), responses.RequestsMock.__enter__(), and start().
Member Data Documentation
_ioloop
apscheduler.executors.tornado.TornadoExecutor._ioloop = scheduler._ioloop protected
Definition at line 28 of file tornado.py.
Referenced by apscheduler.schedulers.tornado.TornadoScheduler._configure(), apscheduler.schedulers.tornado.TornadoScheduler._start_timer(), and apscheduler.schedulers.tornado.TornadoScheduler._stop_timer().
executor
apscheduler.executors.tornado.TornadoExecutor.executor = ThreadPoolExecutor(max_workers)
Definition at line 24 of file tornado.py.
Referenced by _do_submit_job().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/apscheduler/executors/tornado.py