Read&Watch: pip._internal.distributions.sdist.SourceDistribution Class Reference
pip._internal.distributions.sdist.SourceDistribution Class Reference
Public Member Functions
Optional[str] build_tracker_id (self)
BaseDistribution get_metadata_distribution (self)
None prepare_distribution_metadata (self, "PackageFinder" finder, bool build_isolation, bool check_build_deps)
Public Member Functions inherited from pip._internal.distributions.base.AbstractDistribution
None __init__ (self, InstallRequirement req)
Protected Member Functions
None _prepare_build_backend (self, "PackageFinder" finder)
Iterable[str] _get_build_requires_wheel (self)
Iterable[str] _get_build_requires_editable (self)
None _install_build_reqs (self, "PackageFinder" finder)
None _raise_conflicts (self, str conflicting_with, Set[Tuple[str, str]] conflicting_reqs)
None _raise_missing_reqs (self, Set[str] missing)
Additional Inherited Members
Public Attributes inherited from pip._internal.distributions.base.AbstractDistribution
req = req
Detailed Description
Represents a source distribution.
The preparation step for these needs metadata for the packages to be
generated, either using PEP 517 or using the legacy `setup.py egg_info`.
Definition at line 16 of file sdist.py.
Member Function Documentation
_get_build_requires_editable()
Iterable[str] pip._internal.distributions.sdist.SourceDistribution._get_build_requires_editable (self) protected
Definition at line 105 of file sdist.py.
    def _get_build_requires_editable(self) -> Iterable[str]:
        with self.req.build_env:
            runner = runner_with_spinner_message(
                "Getting requirements to build editable"
            )
            backend = self.req.pep517_backend
            assert backend is not None
            with backend.subprocess_runner(runner):
                return backend.get_requires_for_build_editable()
References pip._internal.distributions.base.AbstractDistribution.req.
Referenced by _install_build_reqs().
_get_build_requires_wheel()
Iterable[str] pip._internal.distributions.sdist.SourceDistribution._get_build_requires_wheel (self) protected
Definition at line 97 of file sdist.py.
    def _get_build_requires_wheel(self) -> Iterable[str]:
        with self.req.build_env:
            runner = runner_with_spinner_message("Getting requirements to build wheel")
            backend = self.req.pep517_backend
            assert backend is not None
            with backend.subprocess_runner(runner):
                return backend.get_requires_for_build_wheel()
References pip._internal.distributions.base.AbstractDistribution.req.
Referenced by _install_build_reqs().
_install_build_reqs()
None pip._internal.distributions.sdist.SourceDistribution._install_build_reqs (self, "PackageFinder" finder) protected
Definition at line 115 of file sdist.py.
    def _install_build_reqs(self, finder: "PackageFinder") -> None:
        # Install any extra build dependencies that the backend requests.
        # This must be done in a second pass, as the pyproject.toml
        # dependencies must be installed before we can call the backend.
        if (
            self.req.editable
            and self.req.permit_editable_wheels
            and self.req.supports_pyproject_editable
        ):
            build_reqs = self._get_build_requires_editable()
        else:
            build_reqs = self._get_build_requires_wheel()
        conflicting, missing = self.req.build_env.check_requirements(build_reqs)
        if conflicting:
            self._raise_conflicts("the backend dependencies", conflicting)
        self.req.build_env.install_requirements(
            finder, missing, "normal", kind="backend dependencies"
        )
References _get_build_requires_editable(), _get_build_requires_wheel(), _raise_conflicts(), and pip._internal.distributions.base.AbstractDistribution.req.
Referenced by prepare_distribution_metadata().
_prepare_build_backend()
None pip._internal.distributions.sdist.SourceDistribution._prepare_build_backend (self, "PackageFinder" finder) protected
Definition at line 71 of file sdist.py.
    def _prepare_build_backend(self, finder: "PackageFinder") -> None:
        # Isolate in a BuildEnvironment and install the build-time
        # requirements.
        pyproject_requires = self.req.pyproject_requires
        assert pyproject_requires is not None
        self.req.build_env = BuildEnvironment()
        self.req.build_env.install_requirements(
            finder, pyproject_requires, "overlay", kind="build dependencies"
        )
        conflicting, missing = self.req.build_env.check_requirements(
            self.req.requirements_to_check
        )
        if conflicting:
            self._raise_conflicts("PEP 517/518 supported requirements", conflicting)
        if missing:
            logger.warning(
                "Missing build requirements in pyproject.toml for %s.",
                self.req,
            )
            logger.warning(
                "The project does not specify a build backend, and "
                "pip cannot fall back to setuptools without %s.",
                " and ".join(map(repr, sorted(missing))),
            )
References _raise_conflicts(), and pip._internal.distributions.base.AbstractDistribution.req.
Referenced by prepare_distribution_metadata().
_raise_conflicts()
None pip._internal.distributions.sdist.SourceDistribution._raise_conflicts (self, str conflicting_with, Set[Tuple[str, str]] conflicting_reqs) protected
Definition at line 134 of file sdist.py.
    ) -> None:
        format_string = (
            "Some build dependencies for {requirement} "
            "conflict with {conflicting_with}: {description}."
        )
        error_message = format_string.format(
            requirement=self.req,
            conflicting_with=conflicting_with,
            description=", ".join(
                f"{installed} is incompatible with {wanted}"
                for installed, wanted in sorted(conflicting_reqs)
            ),
        )
        raise InstallationError(error_message)
References pip._internal.distributions.base.AbstractDistribution.req.
Referenced by _install_build_reqs(), _prepare_build_backend(), and prepare_distribution_metadata().
_raise_missing_reqs()
None pip._internal.distributions.sdist.SourceDistribution._raise_missing_reqs (self, Set[str] missing) protected
Definition at line 151 of file sdist.py.
    def _raise_missing_reqs(self, missing: Set[str]) -> None:
        format_string = (
            "Some build dependencies for {requirement} are missing: {missing}."
        )
        error_message = format_string.format(
            requirement=self.req, missing=", ".join(map(repr, sorted(missing)))
        )
        raise InstallationError(error_message)
References pip._internal.distributions.base.AbstractDistribution.req.
Referenced by prepare_distribution_metadata().
build_tracker_id()
Optional[str] pip._internal.distributions.sdist.SourceDistribution.build_tracker_id (self)
Identify this requirement uniquely by its link.
Reimplemented from pip._internal.distributions.base.AbstractDistribution.
Definition at line 24 of file sdist.py.
    def build_tracker_id(self) -> Optional[str]:
        """Identify this requirement uniquely by its link."""
        assert self.req.link
        return self.req.link.url_without_fragment
References pip._internal.distributions.base.AbstractDistribution.req.
get_metadata_distribution()
BaseDistribution pip._internal.distributions.sdist.SourceDistribution.get_metadata_distribution (self)
Reimplemented from pip._internal.distributions.base.AbstractDistribution.
Definition at line 29 of file sdist.py.
    def get_metadata_distribution(self) -> BaseDistribution:
        return self.req.get_dist()
References pip._internal.distributions.base.AbstractDistribution.req.
prepare_distribution_metadata()
None pip._internal.distributions.sdist.SourceDistribution.prepare_distribution_metadata (self, "PackageFinder" finder, bool build_isolation, bool check_build_deps)
Reimplemented from pip._internal.distributions.base.AbstractDistribution.
Definition at line 32 of file sdist.py.
    ) -> None:
        # Load pyproject.toml, to determine whether PEP 517 is to be used
        self.req.load_pyproject_toml()
        # Set up the build isolation, if this requirement should be isolated
        should_isolate = self.req.use_pep517 and build_isolation
        if should_isolate:
            # Setup an isolated environment and install the build backend static
            # requirements in it.
            self._prepare_build_backend(finder)
            # Check that if the requirement is editable, it either supports PEP 660 or
            # has a setup.py or a setup.cfg. This cannot be done earlier because we need
            # to setup the build backend to verify it supports build_editable, nor can
            # it be done later, because we want to avoid installing build requirements
            # needlessly. Doing it here also works around setuptools generating
            # UNKNOWN.egg-info when running get_requires_for_build_wheel on a directory
            # without setup.py nor setup.cfg.
            self.req.isolated_editable_sanity_check()
            # Install the dynamic build requirements.
            self._install_build_reqs(finder)
        # Check if the current environment provides build dependencies
        should_check_deps = self.req.use_pep517 and check_build_deps
        if should_check_deps:
            pyproject_requires = self.req.pyproject_requires
            assert pyproject_requires is not None
            conflicting, missing = self.req.build_env.check_requirements(
                pyproject_requires
            )
            if conflicting:
                self._raise_conflicts("the backend dependencies", conflicting)
            if missing:
                self._raise_missing_reqs(missing)
        self.req.prepare_metadata()
References _install_build_reqs(), _prepare_build_backend(), _raise_conflicts(), _raise_missing_reqs(), and pip._internal.distributions.base.AbstractDistribution.req.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_internal/distributions/sdist.py