Read&Watch: idna.codec.Codec Class Reference
idna.codec.Codec Class Reference
Public Member Functions
Tuple[bytes, int] encode (self, str data, str errors="strict")
Tuple[str, int] decode (self, bytes data, str errors="strict")
Detailed Description
Definition at line 10 of file codec.py.
Member Function Documentation
decode()
Tuple[str, int] idna.codec.Codec.decode (self, bytes data, str errors = "strict")
Definition at line 20 of file codec.py.
    def decode(self, data: bytes, errors: str = "strict") -> Tuple[str, int]:
        if errors != "strict":
            raise IDNAError('Unsupported error handling "{}"'.format(errors))
        if not data:
            return "", 0
        return decode(data), len(data)
References decode().
Referenced by django.contrib.sessions.backends.cached_db.SessionStore.aload(), decode(), and django.contrib.sessions.backends.cached_db.SessionStore.load().
encode()
Tuple[bytes, int] idna.codec.Codec.encode (self, str data, str errors = "strict")
Definition at line 11 of file codec.py.
    def encode(self, data: str, errors: str = "strict") -> Tuple[bytes, int]:
        if errors != "strict":
            raise IDNAError('Unsupported error handling "{}"'.format(errors))
        if not data:
            return b"", 0
        return encode(data), len(data)
References encode().
Referenced by pip._vendor.cachecontrol.caches.file_cache._FileCacheMixin._fn(), encode(), and PIL.ImageFile.PyEncoder.encode_to_file().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/idna/codec.py