Read&Watch: pip._internal.resolution.base.BaseResolver Class Reference
pip._internal.resolution.base.BaseResolver Class Reference
Public Member Functions
RequirementSet resolve (self, List[InstallRequirement] root_reqs, bool check_supported_wheels)
List[InstallRequirement] get_installation_order (self, RequirementSet req_set)
Detailed Description
Definition at line 11 of file base.py.
Member Function Documentation
get_installation_order()
List[InstallRequirement] pip._internal.resolution.base.BaseResolver.get_installation_order (self, RequirementSet req_set)
Reimplemented in pip._internal.resolution.legacy.resolver.Resolver, and pip._internal.resolution.resolvelib.resolver.Resolver.
Definition at line 17 of file base.py.
    ) -> List[InstallRequirement]:
        raise NotImplementedError()
resolve()
RequirementSet pip._internal.resolution.base.BaseResolver.resolve (self, List[InstallRequirement] root_reqs, bool check_supported_wheels)
Reimplemented in pip._internal.resolution.legacy.resolver.Resolver, and pip._internal.resolution.resolvelib.resolver.Resolver.
Definition at line 12 of file base.py.
    ) -> RequirementSet:
        raise NotImplementedError()
Referenced by yaml.composer.Composer.compose_mapping_node(), yaml.composer.Composer.compose_scalar_node(), yaml.composer.Composer.compose_sequence_node(), pip._vendor.distlib.compat.BaseConfigurator.configure_custom(), pip._vendor.distlib.compat.BaseConfigurator.ext_convert(), and yaml.serializer.Serializer.serialize_node().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_internal/resolution/base.py