Read&Watch: pip._internal.operations.install.wheel.PipScriptMaker Class Reference
pip._internal.operations.install.wheel.PipScriptMaker Class Reference
Public Member Functions
List[str] make (self, str specification, Optional[Dict[str, Any]] options=None)
Public Member Functions inherited from pip._vendor.distlib.scripts.ScriptMaker
__init__ (self, source_dir, target_dir, add_launchers=True, dry_run=False, fileop=None)
get_manifest (self, exename)
get_script_filenames (self, name)
dry_run (self)
dry_run (self, value)
make_multiple (self, specifications, options=None)
Additional Inherited Members
Public Attributes inherited from pip._vendor.distlib.scripts.ScriptMaker
source_dir = source_dir
target_dir = target_dir
add_launchers = add_launchers
bool force = False
bool clobber = False
tuple set_mode = (os.name == 'posix') or (os.name == 'java' and os._name == 'posix')
variants = set(('', 'X.Y'))
version_info = sys.version_info
dry_run
Static Public Attributes inherited from pip._vendor.distlib.scripts.ScriptMaker
script_template = SCRIPT_TEMPLATE
executable = None
manifest = _DEFAULT_MANIFEST
str variant_separator = '-'
Protected Member Functions inherited from pip._vendor.distlib.scripts.ScriptMaker
_get_alternate_executable (self, executable, options)
_is_shell (self, executable)
_fix_jython_executable (self, executable)
_build_shebang (self, executable, post_interp)
_get_shebang (self, encoding, post_interp=b'', options=None)
_get_script_text (self, entry)
_write_script (self, names, shebang, script_bytes, filenames, ext)
_make_script (self, entry, filenames, options=None)
_copy_script (self, script, filenames)
_get_launcher (self, kind)
Protected Attributes inherited from pip._vendor.distlib.scripts.ScriptMaker
_fileop = fileop or FileOperator(dry_run)
str _is_nt = 'nt' or (os.name == 'java' and os._name == 'nt')
Detailed Description
Definition at line 414 of file wheel.py.
Member Function Documentation
make()
List[str] pip._internal.operations.install.wheel.PipScriptMaker.make (self, str specification, Optional[Dict[str, Any]] options = None)
Make a script.
:param specification: The specification, which is either a valid export
                      entry specification (to make a script from a
                      callable) or a filename (to make a script by
                      copying from a source location).
:param options: A dictionary of options controlling script generation.
:return: A list of all absolute pathnames written to.
Reimplemented from pip._vendor.distlib.scripts.ScriptMaker.
Definition at line 415 of file wheel.py.
    ) -> List[str]:
        _raise_for_invalid_entrypoint(specification)
        return super().make(specification, options)
References pip._internal.operations.install.wheel._raise_for_invalid_entrypoint(), and make().
Referenced by make(), and pip._vendor.distlib.scripts.ScriptMaker.make_multiple().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_internal/operations/install/wheel.py