Read&Watch: PIL.BdfFontFile.BdfFontFile Class Reference
PIL.BdfFontFile.BdfFontFile Class Reference
Public Member Functions
None __init__ (self, BinaryIO fp)
Public Member Functions inherited from PIL.FontFile.FontFile
None __init__ (self)
(tuple[ tuple[int, int], tuple[int, int, int, int], tuple[int, int, int, int], Image.Image,]|None) __getitem__ (self, int ix)
None compile (self)
None save (self, str filename)
Additional Inherited Members
Public Attributes inherited from PIL.FontFile.FontFile
dict info = {}
list[ glyph
ysize = h
list[ metrics = Image.new("1", (xsize, ysize))
Static Public Attributes inherited from PIL.FontFile.FontFile
Image bitmap = None
Detailed Description
Font file plugin for the X11 BDF format.
Definition at line 103 of file BdfFontFile.py.
Constructor & Destructor Documentation
__init__()
None PIL.BdfFontFile.BdfFontFile.__init__ (self, BinaryIO fp)
Definition at line 106 of file BdfFontFile.py.
    def __init__(self, fp: BinaryIO) -> None:
        super().__init__()
        s = fp.readline()
        if s[:13] != b"STARTFONT 2.1":
            msg = "not a valid BDF file"
            raise SyntaxError(msg)
        props = {}
        comments = []
        while True:
            s = fp.readline()
            if not s or s[:13] == b"ENDPROPERTIES":
                break
            i = s.find(b" ")
            props[s[:i].decode("ascii")] = s[i + 1 : -1].decode("ascii")
            if s[:i] in [b"COMMENT", b"COPYRIGHT"]:
                if s.find(b"LogicalFontDescription") < 0:
                    comments.append(s[i + 1 : -1].decode("ascii"))
        while True:
            c = bdf_char(fp)
            if not c:
                break
            id, ch, (xy, dst, src), im = c
            if 0 <= ch < len(self.glyph):
                self.glyph[ch] = xy, dst, src, im
References __init__(), PIL.BdfFontFile.bdf_char(), and PIL.FontFile.FontFile.glyph.
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/PIL/BdfFontFile.py