Read&Watch: django.db.backends.ddl_references.ForeignKeyName Class Reference
django.db.backends.ddl_references.ForeignKeyName Class Reference
Public Member Functions
__init__ (self, from_table, from_columns, to_table, to_columns, suffix_template, create_fk_name)
references_table (self, table)
references_column (self, table, column)
rename_table_references (self, old_table, new_table)
rename_column_references (self, table, old_column, new_column)
__str__ (self)
Public Member Functions inherited from django.db.backends.ddl_references.TableColumns
__init__ (self, table, columns)
Public Member Functions inherited from django.db.backends.ddl_references.Table
__init__ (self, table, quote_name)
references_index (self, table, index)
__str__ (self)
Public Member Functions inherited from django.db.backends.ddl_references.Reference
__repr__ (self)
__str__ (self)
Public Attributes
to_reference = TableColumns(to_table, to_columns)
suffix_template = suffix_template
create_fk_name = create_fk_name
Public Attributes inherited from django.db.backends.ddl_references.TableColumns
columns = columns
Public Attributes inherited from django.db.backends.ddl_references.Table
table = table
quote_name = quote_name
Detailed Description
Hold a reference to a foreign key name.
Definition at line 148 of file ddl_references.py.
Constructor & Destructor Documentation
__init__()
django.db.backends.ddl_references.ForeignKeyName.__init__ (self, from_table, from_columns, to_table, to_columns, suffix_template, create_fk_name)
Definition at line 151 of file ddl_references.py.
    ):
        self.to_reference = TableColumns(to_table, to_columns)
        self.suffix_template = suffix_template
        self.create_fk_name = create_fk_name
        super().__init__(
            from_table,
            from_columns,
        )
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
__str__()
django.db.backends.ddl_references.ForeignKeyName.__str__ (self)
Definition at line 186 of file ddl_references.py.
    def __str__(self):
        suffix = self.suffix_template % {
            "to_table": self.to_reference.table,
            "to_column": self.to_reference.columns[0],
        }
        return self.create_fk_name(self.table, self.columns, suffix)
References suffix_template, and to_reference.
Referenced by PIL.PdfParser.IndirectReference.__bytes__().
references_column()
django.db.backends.ddl_references.ForeignKeyName.references_column (self, table, column)
Return whether or not this instance references the specified column.
Reimplemented from django.db.backends.ddl_references.TableColumns.
Definition at line 173 of file ddl_references.py.
    def references_column(self, table, column):
        return super().references_column(
            table, column
        ) or self.to_reference.references_column(table, column)
References references_column(), and to_reference.
Referenced by references_column().
references_table()
django.db.backends.ddl_references.ForeignKeyName.references_table (self, table)
Return whether or not this instance references the specified table.
Reimplemented from django.db.backends.ddl_references.Table.
Definition at line 168 of file ddl_references.py.
    def references_table(self, table):
        return super().references_table(table) or self.to_reference.references_table(
            table
        )
References references_table(), and to_reference.
Referenced by references_table().
rename_column_references()
django.db.backends.ddl_references.ForeignKeyName.rename_column_references (self, table, old_column, new_column)
Rename all references to the old_column to the new_column.
Reimplemented from django.db.backends.ddl_references.TableColumns.
Definition at line 182 of file ddl_references.py.
    def rename_column_references(self, table, old_column, new_column):
        super().rename_column_references(table, old_column, new_column)
        self.to_reference.rename_column_references(table, old_column, new_column)
References rename_column_references(), and to_reference.
Referenced by rename_column_references().
rename_table_references()
django.db.backends.ddl_references.ForeignKeyName.rename_table_references (self, old_table, new_table)
Rename all references to the old_name to the new_table.
Reimplemented from django.db.backends.ddl_references.Table.
Definition at line 178 of file ddl_references.py.
    def rename_table_references(self, old_table, new_table):
        super().rename_table_references(old_table, new_table)
        self.to_reference.rename_table_references(old_table, new_table)
References rename_table_references(), and to_reference.
Referenced by rename_table_references().
Member Data Documentation
create_fk_name
django.db.backends.ddl_references.ForeignKeyName.create_fk_name = create_fk_name
Definition at line 162 of file ddl_references.py.
suffix_template
django.db.backends.ddl_references.ForeignKeyName.suffix_template = suffix_template
Definition at line 161 of file ddl_references.py.
Referenced by __str__().
to_reference
django.db.backends.ddl_references.ForeignKeyName.to_reference = TableColumns(to_table, to_columns)
Definition at line 160 of file ddl_references.py.
Referenced by __str__(), references_column(), references_table(), rename_column_references(), and rename_table_references().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/db/backends/ddl_references.py