Read&Watch: astroid.nodes.as_string.AsStringVisitor Class Reference
astroid.nodes.as_string.AsStringVisitor Class Reference
Public Member Functions
__init__ (self, str indent=" ")
str __call__ (self, node)
str visit_await (self, node)
str visit_asyncwith (self, node)
str visit_asyncfor (self, node)
str visit_arguments (self, node)
str visit_assignattr (self, node)
str visit_assert (self, node)
str visit_assignname (self, node)
str visit_assign (self, node)
str visit_augassign (self, node)
str visit_annassign (self, node)
str visit_binop (self, node)
str visit_boolop (self, node)
str visit_break (self, node)
str visit_call (self, node)
str visit_classdef (self, node)
str visit_compare (self, node)
str visit_comprehension (self, node)
str visit_const (self, node)
str visit_continue (self, node)
str visit_delete (self, node)
str visit_delattr (self, node)
str visit_delname (self, node)
str visit_decorators (self, node)
str visit_dict (self, node)
str visit_dictunpack (self, node)
str visit_dictcomp (self, node)
str visit_expr (self, node)
str visit_emptynode (self, node)
str visit_excepthandler (self, node)
str visit_empty (self, node)
str visit_for (self, node)
str visit_importfrom (self, node)
str visit_joinedstr (self, node)
str visit_formattedvalue (self, node)
str handle_functiondef (self, nodes.FunctionDef node, str keyword)
str visit_functiondef (self, nodes.FunctionDef node)
str visit_asyncfunctiondef (self, nodes.AsyncFunctionDef node)
str visit_generatorexp (self, node)
str visit_attribute (self, node)
str visit_global (self, node)
str visit_if (self, node)
str visit_ifexp (self, node)
str visit_import (self, node)
str visit_keyword (self, node)
str visit_lambda (self, node)
str visit_list (self, node)
str visit_listcomp (self, node)
str visit_module (self, node)
str visit_name (self, node)
str visit_namedexpr (self, node)
str visit_nonlocal (self, node)
str visit_paramspec (self, nodes.ParamSpec node)
str visit_pass (self, node)
str visit_partialfunction (self, objects.PartialFunction node)
str visit_raise (self, node)
str visit_return (self, node)
str visit_set (self, node)
str visit_setcomp (self, node)
str visit_slice (self, node)
str visit_subscript (self, node)
str visit_try (self, node)
str visit_trystar (self, node)
str visit_tuple (self, node)
str visit_typealias (self, nodes.TypeAlias node)
str visit_typevar (self, nodes.TypeVar node)
str visit_typevartuple (self, nodes.TypeVarTuple node)
str visit_unaryop (self, node)
str visit_while (self, node)
str visit_with (self, node)
str visit_yield (self, node)
str visit_yieldfrom (self, node)
str visit_starred (self, node)
str visit_match (self, Match node)
str visit_matchcase (self, MatchCase node)
str visit_matchvalue (self, MatchValue node)
str visit_matchsequence (self, MatchSequence node)
str visit_matchmapping (self, MatchMapping node)
str visit_matchclass (self, MatchClass node)
str visit_matchstar (self, MatchStar node)
str visit_matchas (self, MatchAs node)
str visit_matchor (self, MatchOr node)
visit_frozenset (self, node)
visit_super (self, node)
visit_uninferable (self, node)
visit_property (self, node)
visit_evaluatedobject (self, node)
str visit_unknown (self, Unknown node)
Static Public Member Functions
str visit_matchsingleton (MatchSingleton node)
Public Attributes
str indent = indent
Protected Member Functions
str _docs_dedent (self, Const|None doc_node)
str _stmt_list (self, list stmts, bool indent=True)
str _precedence_parens (self, node, child, bool is_left=True)
bool _should_wrap (self, node, child, bool is_left)
Iterator[str] _visit_dict (self, node)
Detailed Description
Visitor to render an Astroid node as a valid python code string
Definition at line 39 of file as_string.py.
Constructor & Destructor Documentation
__init__()
astroid.nodes.as_string.AsStringVisitor.__init__ (self, str indent = " ")
Definition at line 42 of file as_string.py.
    def __init__(self, indent: str = "    "):
        self.indent: str = indent
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
__call__()
str astroid.nodes.as_string.AsStringVisitor.__call__ (self, node)
Makes this visitor behave as a simple function
Definition at line 45 of file as_string.py.
    def __call__(self, node) -> str:
        """Makes this visitor behave as a simple function"""
        return node.accept(self).replace(DOC_NEWLINE, "\n")
_docs_dedent()
str astroid.nodes.as_string.AsStringVisitor._docs_dedent (self, Const | None doc_node) protected
Stop newlines in docs being indented by self._stmt_list
Definition at line 49 of file as_string.py.
    def _docs_dedent(self, doc_node: Const | None) -> str:
        """Stop newlines in docs being indented by self._stmt_list"""
        if not doc_node:
            return ""
        return '\n{}"""{}"""'.format(
            self.indent, doc_node.value.replace("\n", DOC_NEWLINE)
        )
References indent.
Referenced by handle_functiondef(), and visit_classdef().
_precedence_parens()
str astroid.nodes.as_string.AsStringVisitor._precedence_parens (self, node, child, bool is_left = True) protected
Wrap child in parens only if required to keep same semantics
Definition at line 68 of file as_string.py.
    def _precedence_parens(self, node, child, is_left: bool = True) -> str:
        """Wrap child in parens only if required to keep same semantics"""
        if self._should_wrap(node, child, is_left):
            return f"({child.accept(self)})"
        return child.accept(self)
References _should_wrap().
Referenced by visit_attribute(), visit_binop(), visit_call(), and visit_ifexp().
_should_wrap()
bool astroid.nodes.as_string.AsStringVisitor._should_wrap (self, node, child, bool is_left) protected
Wrap child if:
- it has lower precedence
- same precedence with position opposite to associativity direction
Definition at line 75 of file as_string.py.
    def _should_wrap(self, node, child, is_left: bool) -> bool:
        """Wrap child if:
        - it has lower precedence
        - same precedence with position opposite to associativity direction
        """
        node_precedence = node.op_precedence()
        child_precedence = child.op_precedence()
        if node_precedence > child_precedence:
            # 3 * (4 + 5)
            return True
        if (
            node_precedence == child_precedence
            and is_left != node.op_left_associative()
        ):
            # 3 - (4 - 5)
            # (2**3)**4
            return True
        return False
Referenced by _precedence_parens().
_stmt_list()
str astroid.nodes.as_string.AsStringVisitor._stmt_list (self, list stmts, bool indent = True) protected
return a list of nodes to string
Definition at line 58 of file as_string.py.
    def _stmt_list(self, stmts: list, indent: bool = True) -> str:
        """return a list of nodes to string"""
        stmts_str: str = "\n".join(
            nstr for nstr in [n.accept(self) for n in stmts] if nstr
        )
        if not indent:
            return stmts_str
        return self.indent + stmts_str.replace("\n", "\n" + self.indent)
References indent.
Referenced by handle_functiondef(), visit_classdef(), and visit_for().
_visit_dict()
Iterator[str] astroid.nodes.as_string.AsStringVisitor._visit_dict (self, node) protected
Definition at line 232 of file as_string.py.
    def _visit_dict(self, node) -> Iterator[str]:
        for key, value in node.items:
            key = key.accept(self)
            value = value.accept(self)
            if key == "**":
                # It can only be a DictUnpack node.
                yield key + value
            else:
                yield f"{key}: {value}"
Referenced by visit_dict().
handle_functiondef()
str astroid.nodes.as_string.AsStringVisitor.handle_functiondef (self, nodes.FunctionDef node, str keyword)
return a (possibly async) function definition node as string
Definition at line 331 of file as_string.py.
    def handle_functiondef(self, node: nodes.FunctionDef, keyword: str) -> str:
        """return a (possibly async) function definition node as string"""
        decorate = node.decorators.accept(self) if node.decorators else ""
        docs = self._docs_dedent(node.doc_node)
        trailer = ":"
        if node.returns:
            return_annotation = " -> " + node.returns.as_string()
            trailer = return_annotation + ":"
        # TODO: handle type_params
        def_format = "\n%s%s %s(%s)%s%s\n%s"
        return def_format % (
            decorate,
            keyword,
            node.name,
            node.args.accept(self),
            trailer,
            docs,
            self._stmt_list(node.body),
        )
References _docs_dedent(), and _stmt_list().
Referenced by visit_asyncfunctiondef(), and visit_functiondef().
visit_annassign()
str astroid.nodes.as_string.AsStringVisitor.visit_annassign (self, node)
Return an astroid.AugAssign node as string
Definition at line 135 of file as_string.py.
    def visit_annassign(self, node) -> str:
        """Return an astroid.AugAssign node as string"""
        target = node.target.accept(self)
        annotation = node.annotation.accept(self)
        if node.value is None:
            return f"{target}: {annotation}"
        return f"{target}: {annotation} = {node.value.accept(self)}"
visit_arguments()
str astroid.nodes.as_string.AsStringVisitor.visit_arguments (self, node)
return an astroid.Function node as string
Definition at line 108 of file as_string.py.
    def visit_arguments(self, node) -> str:
        """return an astroid.Function node as string"""
        return node.format_args()
visit_assert()
str astroid.nodes.as_string.AsStringVisitor.visit_assert (self, node)
return an astroid.Assert node as string
Definition at line 116 of file as_string.py.
    def visit_assert(self, node) -> str:
        """return an astroid.Assert node as string"""
        if node.fail:
            return f"assert {node.test.accept(self)}, {node.fail.accept(self)}"
        return f"assert {node.test.accept(self)}"
visit_assign()
str astroid.nodes.as_string.AsStringVisitor.visit_assign (self, node)
return an astroid.Assign node as string
Definition at line 126 of file as_string.py.
    def visit_assign(self, node) -> str:
        """return an astroid.Assign node as string"""
        lhs = " = ".join(n.accept(self) for n in node.targets)
        return f"{lhs} = {node.value.accept(self)}"
visit_assignattr()
str astroid.nodes.as_string.AsStringVisitor.visit_assignattr (self, node)
return an astroid.AssAttr node as string
Definition at line 112 of file as_string.py.
    def visit_assignattr(self, node) -> str:
        """return an astroid.AssAttr node as string"""
        return self.visit_attribute(node)
References visit_attribute().
visit_assignname()
str astroid.nodes.as_string.AsStringVisitor.visit_assignname (self, node)
return an astroid.AssName node as string
Definition at line 122 of file as_string.py.
    def visit_assignname(self, node) -> str:
        """return an astroid.AssName node as string"""
        return node.name
Referenced by astroid.rebuilder.TreeRebuilder.visit_arg(), astroid.rebuilder.TreeRebuilder.visit_excepthandler(), astroid.rebuilder.TreeRebuilder.visit_matchas(), astroid.rebuilder.TreeRebuilder.visit_matchmapping(), astroid.rebuilder.TreeRebuilder.visit_matchstar(), astroid.rebuilder.TreeRebuilder.visit_paramspec(), astroid.rebuilder.TreeRebuilder.visit_typevar(), and astroid.rebuilder.TreeRebuilder.visit_typevartuple().
visit_asyncfor()
str astroid.nodes.as_string.AsStringVisitor.visit_asyncfor (self, node)
Definition at line 105 of file as_string.py.
    def visit_asyncfor(self, node) -> str:
        return f"async {self.visit_for(node)}"
visit_asyncfunctiondef()
str astroid.nodes.as_string.AsStringVisitor.visit_asyncfunctiondef (self, nodes.AsyncFunctionDef node)
return an astroid.AsyncFunction node as string
Definition at line 355 of file as_string.py.
    def visit_asyncfunctiondef(self, node: nodes.AsyncFunctionDef) -> str:
        """return an astroid.AsyncFunction node as string"""
        return self.handle_functiondef(node, "async def")
References handle_functiondef().
visit_asyncwith()
str astroid.nodes.as_string.AsStringVisitor.visit_asyncwith (self, node)
Definition at line 102 of file as_string.py.
    def visit_asyncwith(self, node) -> str:
        return f"async {self.visit_with(node)}"
visit_attribute()
str astroid.nodes.as_string.AsStringVisitor.visit_attribute (self, node)
return an astroid.Getattr node as string
Definition at line 365 of file as_string.py.
    def visit_attribute(self, node) -> str:
        """return an astroid.Getattr node as string"""
        try:
            left = self._precedence_parens(node, node.expr)
        except RecursionError:
            warnings.warn(
                "Recursion limit exhausted; defaulting to adding parentheses.",
                UserWarning,
                stacklevel=2,
            )
            left = f"({node.expr.accept(self)})"
        if left.isdigit():
            left = f"({left})"
        return f"{left}.{node.attrname}"
References _precedence_parens().
Referenced by visit_assignattr(), pylint.checkers.typecheck.TypeChecker.visit_assignattr(), visit_delattr(), and pylint.checkers.typecheck.TypeChecker.visit_delattr().
visit_augassign()
str astroid.nodes.as_string.AsStringVisitor.visit_augassign (self, node)
return an astroid.AugAssign node as string
Definition at line 131 of file as_string.py.
    def visit_augassign(self, node) -> str:
        """return an astroid.AugAssign node as string"""
        return f"{node.target.accept(self)} {node.op} {node.value.accept(self)}"
visit_await()
str astroid.nodes.as_string.AsStringVisitor.visit_await (self, node)
Definition at line 99 of file as_string.py.
    def visit_await(self, node) -> str:
        return f"await {node.value.accept(self)}"
visit_binop()
str astroid.nodes.as_string.AsStringVisitor.visit_binop (self, node)
return an astroid.BinOp node as string
Definition at line 144 of file as_string.py.
    def visit_binop(self, node) -> str:
        """return an astroid.BinOp node as string"""
        left = self._precedence_parens(node, node.left)
        right = self._precedence_parens(node, node.right, is_left=False)
        if node.op == "**":
            return f"{left}{node.op}{right}"
        return f"{left} {node.op} {right}"
References _precedence_parens().
visit_boolop()
str astroid.nodes.as_string.AsStringVisitor.visit_boolop (self, node)
return an astroid.BoolOp node as string
Definition at line 153 of file as_string.py.
    def visit_boolop(self, node) -> str:
        """return an astroid.BoolOp node as string"""
        values = [f"{self._precedence_parens(node, n)}" for n in node.values]
        return (f" {node.op} ").join(values)
visit_break()
str astroid.nodes.as_string.AsStringVisitor.visit_break (self, node)
return an astroid.Break node as string
Definition at line 158 of file as_string.py.
    def visit_break(self, node) -> str:
        """return an astroid.Break node as string"""
        return "break"
visit_call()
str astroid.nodes.as_string.AsStringVisitor.visit_call (self, node)
return an astroid.Call node as string
Definition at line 162 of file as_string.py.
    def visit_call(self, node) -> str:
        """return an astroid.Call node as string"""
        expr_str = self._precedence_parens(node, node.func)
        args = [arg.accept(self) for arg in node.args]
        if node.keywords:
            keywords = [kwarg.accept(self) for kwarg in node.keywords]
        else:
            keywords = []
        args.extend(keywords)
        return f"{expr_str}({', '.join(args)})"
References _precedence_parens().
visit_classdef()
str astroid.nodes.as_string.AsStringVisitor.visit_classdef (self, node)
return an astroid.ClassDef node as string
Definition at line 174 of file as_string.py.
    def visit_classdef(self, node) -> str:
        """return an astroid.ClassDef node as string"""
        decorate = node.decorators.accept(self) if node.decorators else ""
        args = [n.accept(self) for n in node.bases]
        if node._metaclass and not node.has_metaclass_hack():
            args.append("metaclass=" + node._metaclass.accept(self))
        args += [n.accept(self) for n in node.keywords]
        args_str = f"({', '.join(args)})" if args else ""
        docs = self._docs_dedent(node.doc_node)
        # TODO: handle type_params
        return "\n\n{}class {}{}:{}\n{}\n".format(
            decorate, node.name, args_str, docs, self._stmt_list(node.body)
        )
References _docs_dedent(), and _stmt_list().
Referenced by pylint.pyreverse.inspector.Linker.visit_assignname(), and pylint.checkers.exceptions.ExceptionRaiseLeafVisitor.visit_instance().
visit_compare()
str astroid.nodes.as_string.AsStringVisitor.visit_compare (self, node)
return an astroid.Compare node as string
Definition at line 188 of file as_string.py.
    def visit_compare(self, node) -> str:
        """return an astroid.Compare node as string"""
        rhs_str = " ".join(
            f"{op} {self._precedence_parens(node, expr, is_left=False)}"
            for op, expr in node.ops
        )
        return f"{self._precedence_parens(node, node.left)} {rhs_str}"
visit_comprehension()
str astroid.nodes.as_string.AsStringVisitor.visit_comprehension (self, node)
return an astroid.Comprehension node as string
Definition at line 196 of file as_string.py.
    def visit_comprehension(self, node) -> str:
        """return an astroid.Comprehension node as string"""
        ifs = "".join(f" if {n.accept(self)}" for n in node.ifs)
        generated = f"for {node.target.accept(self)} in {node.iter.accept(self)}{ifs}"
        return f"{'async ' if node.is_async else ''}{generated}"
visit_const()
str astroid.nodes.as_string.AsStringVisitor.visit_const (self, node)
return an astroid.Const node as string
Definition at line 202 of file as_string.py.
    def visit_const(self, node) -> str:
        """return an astroid.Const node as string"""
        if node.value is Ellipsis:
            return "..."
        return repr(node.value)
visit_continue()
str astroid.nodes.as_string.AsStringVisitor.visit_continue (self, node)
return an astroid.Continue node as string
Definition at line 208 of file as_string.py.
    def visit_continue(self, node) -> str:
        """return an astroid.Continue node as string"""
        return "continue"
visit_decorators()
str astroid.nodes.as_string.AsStringVisitor.visit_decorators (self, node)
return an astroid.Decorators node as string
Definition at line 224 of file as_string.py.
    def visit_decorators(self, node) -> str:
        """return an astroid.Decorators node as string"""
        return "@%s\n" % "\n@".join(item.accept(self) for item in node.nodes)
Referenced by astroid.rebuilder.TreeRebuilder._visit_functiondef(), and astroid.rebuilder.TreeRebuilder.visit_classdef().
visit_delattr()
str astroid.nodes.as_string.AsStringVisitor.visit_delattr (self, node)
return an astroid.DelAttr node as string
Definition at line 216 of file as_string.py.
    def visit_delattr(self, node) -> str:
        """return an astroid.DelAttr node as string"""
        return self.visit_attribute(node)
References visit_attribute().
visit_delete()
str astroid.nodes.as_string.AsStringVisitor.visit_delete (self, node)
return an astroid.Delete node as string
Definition at line 212 of file as_string.py.
    def visit_delete(self, node) -> str:  # XXX check if correct
        """return an astroid.Delete node as string"""
        return f"del {', '.join(child.accept(self) for child in node.targets)}"
visit_delname()
str astroid.nodes.as_string.AsStringVisitor.visit_delname (self, node)
return an astroid.DelName node as string
Definition at line 220 of file as_string.py.
    def visit_delname(self, node) -> str:
        """return an astroid.DelName node as string"""
        return node.name
visit_dict()
str astroid.nodes.as_string.AsStringVisitor.visit_dict (self, node)
return an astroid.Dict node as string
Definition at line 228 of file as_string.py.
    def visit_dict(self, node) -> str:
        """return an astroid.Dict node as string"""
        return "{%s}" % ", ".join(self._visit_dict(node))
References _visit_dict().
visit_dictcomp()
str astroid.nodes.as_string.AsStringVisitor.visit_dictcomp (self, node)
return an astroid.DictComp node as string
Definition at line 245 of file as_string.py.
    def visit_dictcomp(self, node) -> str:
        """return an astroid.DictComp node as string"""
        return "{{{}: {} {}}}".format(
            node.key.accept(self),
            node.value.accept(self),
            " ".join(n.accept(self) for n in node.generators),
        )
visit_dictunpack()
str astroid.nodes.as_string.AsStringVisitor.visit_dictunpack (self, node)
Definition at line 242 of file as_string.py.
    def visit_dictunpack(self, node) -> str:
        return "**"
visit_empty()
str astroid.nodes.as_string.AsStringVisitor.visit_empty (self, node)
return an Empty node as string
Definition at line 274 of file as_string.py.
    def visit_empty(self, node) -> str:
        """return an Empty node as string"""
        return ""
visit_emptynode()
str astroid.nodes.as_string.AsStringVisitor.visit_emptynode (self, node)
dummy method for visiting an Empty node
Definition at line 257 of file as_string.py.
    def visit_emptynode(self, node) -> str:
        """dummy method for visiting an Empty node"""
        return ""
visit_evaluatedobject()
astroid.nodes.as_string.AsStringVisitor.visit_evaluatedobject (self, node)
Definition at line 684 of file as_string.py.
    def visit_evaluatedobject(self, node):
        return node.original.accept(self)
visit_excepthandler()
str astroid.nodes.as_string.AsStringVisitor.visit_excepthandler (self, node)
Definition at line 261 of file as_string.py.
    def visit_excepthandler(self, node) -> str:
        n = "except"
        if isinstance(getattr(node, "parent", None), nodes.TryStar):
            n = "except*"
        if node.type:
            if node.name:
                excs = f"{n} {node.type.accept(self)} as {node.name.accept(self)}"
            else:
                excs = f"{n} {node.type.accept(self)}"
        else:
            excs = f"{n}"
        return f"{excs}:\n{self._stmt_list(node.body)}"
visit_expr()
str astroid.nodes.as_string.AsStringVisitor.visit_expr (self, node)
return an astroid.Discard node as string
Definition at line 253 of file as_string.py.
    def visit_expr(self, node) -> str:
        """return an astroid.Discard node as string"""
        return node.value.accept(self)
visit_for()
str astroid.nodes.as_string.AsStringVisitor.visit_for (self, node)
return an astroid.For node as string
Definition at line 278 of file as_string.py.
    def visit_for(self, node) -> str:
        """return an astroid.For node as string"""
        fors = "for {} in {}:\n{}".format(
            node.target.accept(self), node.iter.accept(self), self._stmt_list(node.body)
        )
        if node.orelse:
            fors = f"{fors}\nelse:\n{self._stmt_list(node.orelse)}"
        return fors
References _stmt_list().
visit_formattedvalue()
str astroid.nodes.as_string.AsStringVisitor.visit_formattedvalue (self, node)
Definition at line 320 of file as_string.py.
    def visit_formattedvalue(self, node) -> str:
        result = node.value.accept(self)
        if node.conversion and node.conversion >= 0:
            # e.g. if node.conversion == 114: result += "!r"
            result += "!" + chr(node.conversion)
        if node.format_spec:
            # The format spec is itself a JoinedString, i.e. an f-string
            # We strip the f and quotes of the ends
            result += ":" + node.format_spec.accept(self)[2:-1]
        return "{%s}" % result
visit_frozenset()
astroid.nodes.as_string.AsStringVisitor.visit_frozenset (self, node)
Definition at line 672 of file as_string.py.
    def visit_frozenset(self, node):
        return node.parent.accept(self)
visit_functiondef()
str astroid.nodes.as_string.AsStringVisitor.visit_functiondef (self, nodes.FunctionDef node)
return an astroid.FunctionDef node as string
Definition at line 351 of file as_string.py.
    def visit_functiondef(self, node: nodes.FunctionDef) -> str:
        """return an astroid.FunctionDef node as string"""
        return self.handle_functiondef(node, "def")
References handle_functiondef().
Referenced by pylint.pyreverse.inspector.Linker.visit_assignname(), and visit_partialfunction().
visit_generatorexp()
str astroid.nodes.as_string.AsStringVisitor.visit_generatorexp (self, node)
return an astroid.GeneratorExp node as string
Definition at line 359 of file as_string.py.
    def visit_generatorexp(self, node) -> str:
        """return an astroid.GeneratorExp node as string"""
        return "({} {})".format(
            node.elt.accept(self), " ".join(n.accept(self) for n in node.generators)
        )
visit_global()
str astroid.nodes.as_string.AsStringVisitor.visit_global (self, node)
return an astroid.Global node as string
Definition at line 380 of file as_string.py.
    def visit_global(self, node) -> str:
        """return an astroid.Global node as string"""
        return f"global {', '.join(node.names)}"
visit_if()
str astroid.nodes.as_string.AsStringVisitor.visit_if (self, node)
return an astroid.If node as string
Definition at line 384 of file as_string.py.
    def visit_if(self, node) -> str:
        """return an astroid.If node as string"""
        ifs = [f"if {node.test.accept(self)}:\n{self._stmt_list(node.body)}"]
        if node.has_elif_block():
            ifs.append(f"el{self._stmt_list(node.orelse, indent=False)}")
        elif node.orelse:
            ifs.append(f"else:\n{self._stmt_list(node.orelse)}")
        return "\n".join(ifs)
visit_ifexp()
str astroid.nodes.as_string.AsStringVisitor.visit_ifexp (self, node)
return an astroid.IfExp node as string
Definition at line 393 of file as_string.py.
    def visit_ifexp(self, node) -> str:
        """return an astroid.IfExp node as string"""
        return "{} if {} else {}".format(
            self._precedence_parens(node, node.body, is_left=True),
            self._precedence_parens(node, node.test, is_left=True),
            self._precedence_parens(node, node.orelse, is_left=False),
        )
References _precedence_parens().
visit_import()
str astroid.nodes.as_string.AsStringVisitor.visit_import (self, node)
return an astroid.Import node as string
Definition at line 401 of file as_string.py.
    def visit_import(self, node) -> str:
        """return an astroid.Import node as string"""
        return f"import {_import_string(node.names)}"
visit_importfrom()
str astroid.nodes.as_string.AsStringVisitor.visit_importfrom (self, node)
return an astroid.ImportFrom node as string
Definition at line 287 of file as_string.py.
    def visit_importfrom(self, node) -> str:
        """return an astroid.ImportFrom node as string"""
        return "from {} import {}".format(
            "." * (node.level or 0) + node.modname, _import_string(node.names)
        )
References astroid.nodes.as_string._import_string().
visit_joinedstr()
str astroid.nodes.as_string.AsStringVisitor.visit_joinedstr (self, node)
Definition at line 293 of file as_string.py.
    def visit_joinedstr(self, node) -> str:
        string = "".join(
            # Use repr on the string literal parts
            # to get proper escapes, e.g. \n, \\, \"
            # But strip the quotes off the ends
            # (they will always be one character: ' or ")
            (
                repr(value.value)[1:-1]
                # Literal braces must be doubled to escape them
                .replace("{", "{{").replace("}", "}}")
                # Each value in values is either a string literal (Const)
                # or a FormattedValue
                if type(value).__name__ == "Const"
                else value.accept(self)
            )
            for value in node.values
        )
        # Try to find surrounding quotes that don't appear at all in the string.
        # Because the formatted values inside {} can't contain backslash (\‍)
        # using a triple quote is sometimes necessary
        for quote in ("'", '"', '"""', "'''"):
            if quote not in string:
                break
        return "f" + quote + string + quote
visit_keyword()
str astroid.nodes.as_string.AsStringVisitor.visit_keyword (self, node)
return an astroid.Keyword node as string
Definition at line 405 of file as_string.py.
    def visit_keyword(self, node) -> str:
        """return an astroid.Keyword node as string"""
        if node.arg is None:
            return f"**{node.value.accept(self)}"
        return f"{node.arg}={node.value.accept(self)}"
visit_lambda()
str astroid.nodes.as_string.AsStringVisitor.visit_lambda (self, node)
return an astroid.Lambda node as string
Definition at line 411 of file as_string.py.
    def visit_lambda(self, node) -> str:
        """return an astroid.Lambda node as string"""
        args = node.args.accept(self)
        body = node.body.accept(self)
        if args:
            return f"lambda {args}: {body}"
        return f"lambda: {body}"
visit_list()
str astroid.nodes.as_string.AsStringVisitor.visit_list (self, node)
return an astroid.List node as string
Definition at line 420 of file as_string.py.
    def visit_list(self, node) -> str:
        """return an astroid.List node as string"""
        return f"[{', '.join(child.accept(self) for child in node.elts)}]"
visit_listcomp()
str astroid.nodes.as_string.AsStringVisitor.visit_listcomp (self, node)
return an astroid.ListComp node as string
Definition at line 424 of file as_string.py.
    def visit_listcomp(self, node) -> str:
        """return an astroid.ListComp node as string"""
        return "[{} {}]".format(
            node.elt.accept(self), " ".join(n.accept(self) for n in node.generators)
        )
visit_match()
str astroid.nodes.as_string.AsStringVisitor.visit_match (self, Match node)
Return an astroid.Match node as string.
Definition at line 596 of file as_string.py.
    def visit_match(self, node: Match) -> str:
        """Return an astroid.Match node as string."""
        return f"match {node.subject.accept(self)}:\n{self._stmt_list(node.cases)}"
visit_matchas()
str astroid.nodes.as_string.AsStringVisitor.visit_matchas (self, MatchAs node)
Return an astroid.MatchAs node as string.
Definition at line 651 of file as_string.py.
    def visit_matchas(self, node: MatchAs) -> str:
        """Return an astroid.MatchAs node as string."""
        # pylint: disable=import-outside-toplevel
        # Prevent circular dependency
        from astroid.nodes.node_classes import MatchClass, MatchMapping, MatchSequence
        if isinstance(node.parent, (MatchSequence, MatchMapping, MatchClass)):
            return node.name.accept(self) if node.name else "_"
        return (
            f"{node.pattern.accept(self) if node.pattern else '_'}"
            f"{f' as {node.name.accept(self)}' if node.name else ''}"
        )
visit_matchcase()
str astroid.nodes.as_string.AsStringVisitor.visit_matchcase (self, MatchCase node)
Return an astroid.MatchCase node as string.
Definition at line 600 of file as_string.py.
    def visit_matchcase(self, node: MatchCase) -> str:
        """Return an astroid.MatchCase node as string."""
        guard_str = f" if {node.guard.accept(self)}" if node.guard else ""
        return (
            f"case {node.pattern.accept(self)}{guard_str}:\n"
            f"{self._stmt_list(node.body)}"
        )
visit_matchclass()
str astroid.nodes.as_string.AsStringVisitor.visit_matchclass (self, MatchClass node)
Return an astroid.MatchClass node as string.
Definition at line 635 of file as_string.py.
    def visit_matchclass(self, node: MatchClass) -> str:
        """Return an astroid.MatchClass node as string."""
        if node.cls is None:
            raise AssertionError(f"{node} does not have a 'cls' node")
        class_strings: list[str] = []
        if node.patterns:
            class_strings.extend(p.accept(self) for p in node.patterns)
        if node.kwd_attrs and node.kwd_patterns:
            for attr, pattern in zip(node.kwd_attrs, node.kwd_patterns):
                class_strings.append(f"{attr}={pattern.accept(self)}")
        return f"{node.cls.accept(self)}({', '.join(class_strings)})"
visit_matchmapping()
str astroid.nodes.as_string.AsStringVisitor.visit_matchmapping (self, MatchMapping node)
Return an astroid.MatchMapping node as string.
Definition at line 623 of file as_string.py.
    def visit_matchmapping(self, node: MatchMapping) -> str:
        """Return an astroid.MatchMapping node as string."""
        mapping_strings: list[str] = []
        if node.keys and node.patterns:
            mapping_strings.extend(
                f"{key.accept(self)}: {p.accept(self)}"
                for key, p in zip(node.keys, node.patterns)
            )
        if node.rest:
            mapping_strings.append(f"**{node.rest.accept(self)}")
        return f"{'{'}{', '.join(mapping_strings)}{'}'}"
visit_matchor()
str astroid.nodes.as_string.AsStringVisitor.visit_matchor (self, MatchOr node)
Return an astroid.MatchOr node as string.
Definition at line 664 of file as_string.py.
    def visit_matchor(self, node: MatchOr) -> str:
        """Return an astroid.MatchOr node as string."""
        if node.patterns is None:
            raise AssertionError(f"{node} does not have pattern nodes")
        return " | ".join(p.accept(self) for p in node.patterns)
visit_matchsequence()
str astroid.nodes.as_string.AsStringVisitor.visit_matchsequence (self, MatchSequence node)
Return an astroid.MatchSequence node as string.
Definition at line 617 of file as_string.py.
    def visit_matchsequence(self, node: MatchSequence) -> str:
        """Return an astroid.MatchSequence node as string."""
        if node.patterns is None:
            return "[]"
        return f"[{', '.join(p.accept(self) for p in node.patterns)}]"
visit_matchsingleton()
str astroid.nodes.as_string.AsStringVisitor.visit_matchsingleton (MatchSingleton node) static
Return an astroid.MatchSingleton node as string.
Definition at line 613 of file as_string.py.
    def visit_matchsingleton(node: MatchSingleton) -> str:
        """Return an astroid.MatchSingleton node as string."""
        return str(node.value)
visit_matchstar()
str astroid.nodes.as_string.AsStringVisitor.visit_matchstar (self, MatchStar node)
Return an astroid.MatchStar node as string.
Definition at line 647 of file as_string.py.
    def visit_matchstar(self, node: MatchStar) -> str:
        """Return an astroid.MatchStar node as string."""
        return f"*{node.name.accept(self) if node.name else '_'}"
visit_matchvalue()
str astroid.nodes.as_string.AsStringVisitor.visit_matchvalue (self, MatchValue node)
Return an astroid.MatchValue node as string.
Definition at line 608 of file as_string.py.
    def visit_matchvalue(self, node: MatchValue) -> str:
        """Return an astroid.MatchValue node as string."""
        return node.value.accept(self)
visit_module()
str astroid.nodes.as_string.AsStringVisitor.visit_module (self, node)
return an astroid.Module node as string
Definition at line 430 of file as_string.py.
    def visit_module(self, node) -> str:
        """return an astroid.Module node as string"""
        docs = f'"""{node.doc_node.value}"""\n\n' if node.doc_node else ""
        return docs + "\n".join(n.accept(self) for n in node.body) + "\n\n"
Referenced by pylint.pyreverse.inspector.Linker.visit_assignname().
visit_name()
str astroid.nodes.as_string.AsStringVisitor.visit_name (self, node)
return an astroid.Name node as string
Definition at line 435 of file as_string.py.
    def visit_name(self, node) -> str:
        """return an astroid.Name node as string"""
        return node.name
Referenced by pylint.checkers.variables.VariablesChecker.visit_assignname(), pylint.checkers.exceptions.ExceptionRaiseRefVisitor.visit_call(), and pylint.checkers.variables.VariablesChecker.visit_delname().
visit_namedexpr()
str astroid.nodes.as_string.AsStringVisitor.visit_namedexpr (self, node)
Return an assignment expression node as string
Definition at line 439 of file as_string.py.
    def visit_namedexpr(self, node) -> str:
        """Return an assignment expression node as string"""
        target = node.target.accept(self)
        value = node.value.accept(self)
        return f"{target} := {value}"
visit_nonlocal()
str astroid.nodes.as_string.AsStringVisitor.visit_nonlocal (self, node)
return an astroid.Nonlocal node as string
Definition at line 445 of file as_string.py.
    def visit_nonlocal(self, node) -> str:
        """return an astroid.Nonlocal node as string"""
        return f"nonlocal {', '.join(node.names)}"
visit_paramspec()
str astroid.nodes.as_string.AsStringVisitor.visit_paramspec (self, nodes.ParamSpec node)
return an astroid.ParamSpec node as string
Definition at line 449 of file as_string.py.
    def visit_paramspec(self, node: nodes.ParamSpec) -> str:
        """return an astroid.ParamSpec node as string"""
        return node.name.accept(self)
visit_partialfunction()
str astroid.nodes.as_string.AsStringVisitor.visit_partialfunction (self, objects.PartialFunction node)
Return an objects.PartialFunction as string.
Definition at line 457 of file as_string.py.
    def visit_partialfunction(self, node: objects.PartialFunction) -> str:
        """Return an objects.PartialFunction as string."""
        return self.visit_functiondef(node)
References visit_functiondef(), and pylint.extensions.redefined_variable_type.MultipleTypesChecker.visit_functiondef.
visit_pass()
str astroid.nodes.as_string.AsStringVisitor.visit_pass (self, node)
return an astroid.Pass node as string
Definition at line 453 of file as_string.py.
    def visit_pass(self, node) -> str:
        """return an astroid.Pass node as string"""
        return "pass"
visit_property()
astroid.nodes.as_string.AsStringVisitor.visit_property (self, node)
Definition at line 681 of file as_string.py.
    def visit_property(self, node):
        return node.function.accept(self)
visit_raise()
str astroid.nodes.as_string.AsStringVisitor.visit_raise (self, node)
return an astroid.Raise node as string
Definition at line 461 of file as_string.py.
    def visit_raise(self, node) -> str:
        """return an astroid.Raise node as string"""
        if node.exc:
            if node.cause:
                return f"raise {node.exc.accept(self)} from {node.cause.accept(self)}"
            return f"raise {node.exc.accept(self)}"
        return "raise"
visit_return()
str astroid.nodes.as_string.AsStringVisitor.visit_return (self, node)
return an astroid.Return node as string
Definition at line 469 of file as_string.py.
    def visit_return(self, node) -> str:
        """return an astroid.Return node as string"""
        if node.is_tuple_return() and len(node.value.elts) > 1:
            elts = [child.accept(self) for child in node.value.elts]
            return f"return {', '.join(elts)}"
        if node.value:
            return f"return {node.value.accept(self)}"
        return "return"
Referenced by pylint.checkers.refactoring.refactoring_checker.RefactoringChecker.visit_assign().
visit_set()
str astroid.nodes.as_string.AsStringVisitor.visit_set (self, node)
return an astroid.Set node as string
Definition at line 480 of file as_string.py.
    def visit_set(self, node) -> str:
        """return an astroid.Set node as string"""
        return "{%s}" % ", ".join(child.accept(self) for child in node.elts)
visit_setcomp()
str astroid.nodes.as_string.AsStringVisitor.visit_setcomp (self, node)
return an astroid.SetComp node as string
Definition at line 484 of file as_string.py.
    def visit_setcomp(self, node) -> str:
        """return an astroid.SetComp node as string"""
        return "{{{} {}}}".format(
            node.elt.accept(self), " ".join(n.accept(self) for n in node.generators)
        )
visit_slice()
str astroid.nodes.as_string.AsStringVisitor.visit_slice (self, node)
return an astroid.Slice node as string
Definition at line 490 of file as_string.py.
    def visit_slice(self, node) -> str:
        """return an astroid.Slice node as string"""
        lower = node.lower.accept(self) if node.lower else ""
        upper = node.upper.accept(self) if node.upper else ""
        step = node.step.accept(self) if node.step else ""
        if step:
            return f"{lower}:{upper}:{step}"
        return f"{lower}:{upper}"
visit_starred()
str astroid.nodes.as_string.AsStringVisitor.visit_starred (self, node)
return Starred node as string
Definition at line 592 of file as_string.py.
    def visit_starred(self, node) -> str:
        """return Starred node as string"""
        return "*" + node.value.accept(self)
visit_subscript()
str astroid.nodes.as_string.AsStringVisitor.visit_subscript (self, node)
return an astroid.Subscript node as string
Definition at line 499 of file as_string.py.
    def visit_subscript(self, node) -> str:
        """return an astroid.Subscript node as string"""
        idx = node.slice
        if idx.__class__.__name__.lower() == "index":
            idx = idx.value
        idxstr = idx.accept(self)
        if idx.__class__.__name__.lower() == "tuple" and idx.elts:
            # Remove parenthesis in tuple and extended slice.
            # a[(::1, 1:)] is not valid syntax.
            idxstr = idxstr[1:-1]
        return f"{self._precedence_parens(node, node.value)}[{idxstr}]"
visit_super()
astroid.nodes.as_string.AsStringVisitor.visit_super (self, node)
Definition at line 675 of file as_string.py.
    def visit_super(self, node):
        return node.parent.accept(self)
visit_try()
str astroid.nodes.as_string.AsStringVisitor.visit_try (self, node)
return an astroid.Try node as string
Definition at line 511 of file as_string.py.
    def visit_try(self, node) -> str:
        """return an astroid.Try node as string"""
        trys = [f"try:\n{self._stmt_list(node.body)}"]
        for handler in node.handlers:
            trys.append(handler.accept(self))
        if node.orelse:
            trys.append(f"else:\n{self._stmt_list(node.orelse)}")
        if node.finalbody:
            trys.append(f"finally:\n{self._stmt_list(node.finalbody)}")
        return "\n".join(trys)
Referenced by pylint.checkers.exceptions.ExceptionsChecker.visit_trystar().
visit_trystar()
str astroid.nodes.as_string.AsStringVisitor.visit_trystar (self, node)
return an astroid.TryStar node as string
Definition at line 522 of file as_string.py.
    def visit_trystar(self, node) -> str:
        """return an astroid.TryStar node as string"""
        trys = [f"try:\n{self._stmt_list(node.body)}"]
        for handler in node.handlers:
            trys.append(handler.accept(self))
        if node.orelse:
            trys.append(f"else:\n{self._stmt_list(node.orelse)}")
        if node.finalbody:
            trys.append(f"finally:\n{self._stmt_list(node.finalbody)}")
        return "\n".join(trys)
visit_tuple()
str astroid.nodes.as_string.AsStringVisitor.visit_tuple (self, node)
return an astroid.Tuple node as string
Definition at line 533 of file as_string.py.
    def visit_tuple(self, node) -> str:
        """return an astroid.Tuple node as string"""
        if len(node.elts) == 1:
            return f"({node.elts[0].accept(self)}, )"
        return f"({', '.join(child.accept(self) for child in node.elts)})"
visit_typealias()
str astroid.nodes.as_string.AsStringVisitor.visit_typealias (self, nodes.TypeAlias node)
return an astroid.TypeAlias node as string
Definition at line 539 of file as_string.py.
    def visit_typealias(self, node: nodes.TypeAlias) -> str:
        """return an astroid.TypeAlias node as string"""
        return node.name.accept(self) if node.name else "_"
visit_typevar()
str astroid.nodes.as_string.AsStringVisitor.visit_typevar (self, nodes.TypeVar node)
return an astroid.TypeVar node as string
Definition at line 543 of file as_string.py.
    def visit_typevar(self, node: nodes.TypeVar) -> str:
        """return an astroid.TypeVar node as string"""
        return node.name.accept(self) if node.name else "_"
visit_typevartuple()
str astroid.nodes.as_string.AsStringVisitor.visit_typevartuple (self, nodes.TypeVarTuple node)
return an astroid.TypeVarTuple node as string
Definition at line 547 of file as_string.py.
    def visit_typevartuple(self, node: nodes.TypeVarTuple) -> str:
        """return an astroid.TypeVarTuple node as string"""
        return "*" + node.name.accept(self) if node.name else ""
visit_unaryop()
str astroid.nodes.as_string.AsStringVisitor.visit_unaryop (self, node)
return an astroid.UnaryOp node as string
Definition at line 551 of file as_string.py.
    def visit_unaryop(self, node) -> str:
        """return an astroid.UnaryOp node as string"""
        if node.op == "not":
            operator = "not "
        else:
            operator = node.op
        return f"{operator}{self._precedence_parens(node, node.operand)}"
visit_uninferable()
astroid.nodes.as_string.AsStringVisitor.visit_uninferable (self, node)
Definition at line 678 of file as_string.py.
    def visit_uninferable(self, node):
        return str(node)
visit_unknown()
str astroid.nodes.as_string.AsStringVisitor.visit_unknown (self, Unknown node)
Definition at line 687 of file as_string.py.
    def visit_unknown(self, node: Unknown) -> str:
        return str(node)
visit_while()
str astroid.nodes.as_string.AsStringVisitor.visit_while (self, node)
return an astroid.While node as string
Definition at line 559 of file as_string.py.
    def visit_while(self, node) -> str:
        """return an astroid.While node as string"""
        whiles = f"while {node.test.accept(self)}:\n{self._stmt_list(node.body)}"
        if node.orelse:
            whiles = f"{whiles}\nelse:\n{self._stmt_list(node.orelse)}"
        return whiles
visit_with()
str astroid.nodes.as_string.AsStringVisitor.visit_with (self, node)
return an astroid.With node as string
Definition at line 566 of file as_string.py.
    def visit_with(self, node) -> str:  # 'with' without 'as' is possible
        """return an astroid.With node as string"""
        items = ", ".join(
            f"{expr.accept(self)}" + (v and f" as {v.accept(self)}" or "")
            for expr, v in node.items
        )
        return f"with {items}:\n{self._stmt_list(node.body)}"
visit_yield()
str astroid.nodes.as_string.AsStringVisitor.visit_yield (self, node)
yield an ast.Yield node as string
Definition at line 574 of file as_string.py.
    def visit_yield(self, node) -> str:
        """yield an ast.Yield node as string"""
        yi_val = (" " + node.value.accept(self)) if node.value else ""
        expr = "yield" + yi_val
        if node.parent.is_statement:
            return expr
        return f"({expr})"
visit_yieldfrom()
str astroid.nodes.as_string.AsStringVisitor.visit_yieldfrom (self, node)
Return an astroid.YieldFrom node as string.
Definition at line 583 of file as_string.py.
    def visit_yieldfrom(self, node) -> str:
        """Return an astroid.YieldFrom node as string."""
        yi_val = (" " + node.value.accept(self)) if node.value else ""
        expr = "yield from" + yi_val
        if node.parent.is_statement:
            return expr
        return f"({expr})"
Member Data Documentation
indent
astroid.nodes.as_string.AsStringVisitor.indent = indent
Definition at line 43 of file as_string.py.
Referenced by tomlkit.items._ArrayItemGroup.__iter__(), _docs_dedent(), sqlparse.filters.aligned_indent.AlignedIndentFilter._process_statement(), django.core.serializers.xml_serializer.Serializer._start_relational_field(), _stmt_list(), yaml.scanner.Scanner.add_indent(), django.core.serializers.xml_serializer.Serializer.end_object(), django.core.serializers.xml_serializer.Serializer.end_serialization(), yaml.emitter.Emitter.expect_block_mapping_key(), yaml.emitter.Emitter.expect_block_sequence_item(), yaml.emitter.Emitter.expect_first_flow_mapping_key(), yaml.emitter.Emitter.expect_first_flow_sequence_item(), yaml.emitter.Emitter.expect_flow_mapping_key(), yaml.emitter.Emitter.expect_flow_sequence_item(), yaml.emitter.Emitter.expect_scalar(), django.core.serializers.xml_serializer.Serializer.handle_field(), yaml.emitter.Emitter.increase_indent(), sqlparse.filters.reindent.ReindentFilter.leading_ws(), sqlparse.filters.aligned_indent.AlignedIndentFilter.nl(), yaml.scanner.Scanner.save_possible_simple_key(), yaml.scanner.Scanner.scan_block_scalar(), yaml.scanner.Scanner.scan_plain(), django.db.migrations.writer.OperationWriter.serialize(), django.core.serializers.xml_serializer.Serializer.start_object(), yaml.scanner.Scanner.unwind_indent(), and yaml.emitter.Emitter.write_indent().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/astroid/nodes/as_string.py