Read&Watch: pylint.checkers.deprecated.DeprecatedMixin Class Reference
pylint.checkers.deprecated.DeprecatedMixin Class Reference
Public Member Functions
None visit_attribute (self, astroid.Attribute node)
None visit_call (self, nodes.Call node)
None visit_import (self, nodes.Import node)
Iterable[str] deprecated_decorators (self)
None visit_decorators (self, nodes.Decorators node)
None visit_importfrom (self, nodes.ImportFrom node)
Container[str] deprecated_methods (self)
Iterable[tuple[int|None, str]] deprecated_arguments (self, str method)
Iterable[str] deprecated_modules (self)
Iterable[str] deprecated_classes (self, str module)
Iterable[str] deprecated_attributes (self)
None check_deprecated_attribute (self, astroid.Attribute node)
None check_deprecated_module (self, nodes.Import node, str|None mod_path)
None check_deprecated_method (self, nodes.Call node, nodes.NodeNG inferred)
None check_deprecated_class (self, nodes.NodeNG node, str mod_name, Iterable[str] class_names)
None check_deprecated_class_in_call (self, nodes.Call node)
Public Member Functions inherited from pylint.checkers.base_checker.BaseChecker
None __init__ (self, PyLinter linter)
bool __gt__ (self, Any other)
bool __eq__ (self, object other)
int __hash__ (self)
str __repr__ (self)
str __str__ (self)
str get_full_documentation (self, dict[str, MessageDefinitionTuple] msgs, Iterable[tuple[str, OptionDict, Any]] options, Sequence[tuple[str, str, ReportsCallable]] reports, str|None doc=None, str|None module=None, bool show_options=True)
None add_message (self, str msgid, int|None line=None, nodes.NodeNG|None node=None, Any args=None, Confidence|None confidence=None, int|None col_offset=None, int|None end_lineno=None, int|None end_col_offset=None)
None check_consistency (self)
MessageDefinition create_message_definition_from_tuple (self, str msgid, MessageDefinitionTuple msg_tuple)
list[MessageDefinition] messages (self)
None open (self)
None close (self)
Any get_map_data (self)
None reduce_map_data (self, PyLinter linter, list[Any] data)
Public Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
None __init__ (self, _ArgumentsManager arguments_manager)
Static Public Attributes
dict DEPRECATED_ATTRIBUTE_MESSAGE
dict DEPRECATED_MODULE_MESSAGE
dict DEPRECATED_METHOD_MESSAGE
dict DEPRECATED_ARGUMENT_MESSAGE
dict DEPRECATED_CLASS_MESSAGE
dict DEPRECATED_DECORATOR_MESSAGE
Static Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
str name = ""
dict msgs = {}
tuple reports = ()
bool enabled = True
Static Public Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
tuple options = ()
dict option_groups_descs = {}
Additional Inherited Members
Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
linter = linter
messages
Protected Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
Any _option_value (self, str opt)
Iterator[ tuple[str, list[tuple[str, OptionDict, Any]]]|tuple[None, dict[str, list[tuple[str, OptionDict, Any]]]]] _options_by_section (self)
Iterator[tuple[str, OptionDict, Any]] _options_and_values (self, Options|None options=None)
Protected Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
_arguments_manager = arguments_manager
Detailed Description
A mixin implementing logic for checking deprecated symbols.
A class implementing mixin must define "deprecated-method" Message.
Definition at line 31 of file deprecated.py.
Member Function Documentation
check_deprecated_attribute()
None pylint.checkers.deprecated.DeprecatedMixin.check_deprecated_attribute (self, astroid.Attribute node)
Checks if the attribute is deprecated.
Definition at line 213 of file deprecated.py.
    def check_deprecated_attribute(self, node: astroid.Attribute) -> None:
        """Checks if the attribute is deprecated."""
        inferred_expr = safe_infer(node.expr)
        if not isinstance(inferred_expr, (nodes.ClassDef, Instance, nodes.Module)):
            return
        attribute_qname = ".".join((inferred_expr.qname(), node.attrname))
        for deprecated_name in self.deprecated_attributes():
            if attribute_qname == deprecated_name:
                self.add_message(
                    "deprecated-attribute",
                    node=node,
                    args=(attribute_qname,),
                    confidence=INFERENCE,
                )
References pylint.checkers.base_checker.BaseChecker.add_message(), and deprecated_attributes().
Referenced by visit_attribute().
check_deprecated_class()
None pylint.checkers.deprecated.DeprecatedMixin.check_deprecated_class (self, nodes.NodeNG node, str mod_name, Iterable[str] class_names)
Checks if the class is deprecated.
Definition at line 270 of file deprecated.py.
    ) -> None:
        """Checks if the class is deprecated."""
        for class_name in class_names:
            if class_name in self.deprecated_classes(mod_name):
                self.add_message(
                    "deprecated-class", node=node, args=(class_name, mod_name)
                )
References pylint.checkers.base_checker.BaseChecker.add_message(), and deprecated_classes().
Referenced by check_deprecated_class_in_call(), visit_import(), and visit_importfrom().
check_deprecated_class_in_call()
None pylint.checkers.deprecated.DeprecatedMixin.check_deprecated_class_in_call (self, nodes.Call node)
Checks if call the deprecated class.
Definition at line 280 of file deprecated.py.
    def check_deprecated_class_in_call(self, node: nodes.Call) -> None:
        """Checks if call the deprecated class."""
        if isinstance(node.func, nodes.Attribute) and isinstance(
            node.func.expr, nodes.Name
        ):
            mod_name = node.func.expr.name
            class_name = node.func.attrname
            self.check_deprecated_class(node, mod_name, (class_name,))
References check_deprecated_class().
Referenced by visit_call(), and pylint.checkers.stdlib.StdlibChecker.visit_call().
check_deprecated_method()
None pylint.checkers.deprecated.DeprecatedMixin.check_deprecated_method (self, nodes.Call node, nodes.NodeNG inferred)
Executes the checker for the given node.
This method should be called from the checker implementing this mixin.
Definition at line 234 of file deprecated.py.
    def check_deprecated_method(self, node: nodes.Call, inferred: nodes.NodeNG) -> None:
        """Executes the checker for the given node.
        This method should be called from the checker implementing this mixin.
        """
        # Reject nodes which aren't of interest to us.
        if not isinstance(inferred, ACCEPTABLE_NODES):
            return
        if isinstance(node.func, nodes.Attribute):
            func_name = node.func.attrname
        elif isinstance(node.func, nodes.Name):
            func_name = node.func.name
        else:
            # Not interested in other nodes.
            return
        qnames = {inferred.qname(), func_name}
        if any(name in self.deprecated_methods() for name in qnames):
            self.add_message("deprecated-method", node=node, args=(func_name,))
            return
        num_of_args = len(node.args)
        kwargs = {kw.arg for kw in node.keywords} if node.keywords else {}
        deprecated_arguments = (self.deprecated_arguments(qn) for qn in qnames)
        for position, arg_name in chain(*deprecated_arguments):
            if arg_name in kwargs:
                # function was called with deprecated argument as keyword argument
                self.add_message(
                    "deprecated-argument", node=node, args=(arg_name, func_name)
                )
            elif position is not None and position < num_of_args:
                # function was called with deprecated argument as positional argument
                self.add_message(
                    "deprecated-argument", node=node, args=(arg_name, func_name)
                )
References pylint.checkers.base_checker.BaseChecker.add_message(), deprecated_arguments(), and deprecated_methods().
Referenced by visit_call(), and pylint.checkers.stdlib.StdlibChecker.visit_call().
check_deprecated_module()
None pylint.checkers.deprecated.DeprecatedMixin.check_deprecated_module (self, nodes.Import node, str | None mod_path)
Checks if the module is deprecated.
Definition at line 228 of file deprecated.py.
    def check_deprecated_module(self, node: nodes.Import, mod_path: str | None) -> None:
        """Checks if the module is deprecated."""
        for mod_name in self.deprecated_modules():
            if mod_path == mod_name or mod_path and mod_path.startswith(mod_name + "."):
                self.add_message("deprecated-module", node=node, args=mod_path)
References pylint.checkers.base_checker.BaseChecker.add_message(), and deprecated_modules().
Referenced by visit_import(), pylint.checkers.imports.ImportsChecker.visit_import(), visit_importfrom(), and pylint.checkers.imports.ImportsChecker.visit_importfrom().
deprecated_arguments()
Iterable[tuple[int | None, str]] pylint.checkers.deprecated.DeprecatedMixin.deprecated_arguments (self, str method)
Callback returning the deprecated arguments of method/function.
Args:
    method (str): name of function/method checked for deprecated arguments
Returns:
    collections.abc.Iterable in form:
        ((POSITION1, PARAM1), (POSITION2: PARAM2) ...)
    where
        * POSITIONX - position of deprecated argument PARAMX in function definition.
          If argument is keyword-only, POSITIONX should be None.
        * PARAMX - name of the deprecated argument.
    E.g. suppose function:
    .. code-block:: python
        def bar(arg1, arg2, arg3, arg4, arg5='spam')
    with deprecated arguments `arg2` and `arg4`. `deprecated_arguments` should return:
    .. code-block:: python
        ((1, 'arg2'), (3, 'arg4'))
Reimplemented in pylint.checkers.stdlib.StdlibChecker.
Definition at line 163 of file deprecated.py.
    def deprecated_arguments(self, method: str) -> Iterable[tuple[int | None, str]]:
        """Callback returning the deprecated arguments of method/function.
        Args:
            method (str): name of function/method checked for deprecated arguments
        Returns:
            collections.abc.Iterable in form:
                ((POSITION1, PARAM1), (POSITION2: PARAM2) ...)
            where
                * POSITIONX - position of deprecated argument PARAMX in function definition.
                  If argument is keyword-only, POSITIONX should be None.
                * PARAMX - name of the deprecated argument.
            E.g. suppose function:
            .. code-block:: python
                def bar(arg1, arg2, arg3, arg4, arg5='spam')
            with deprecated arguments `arg2` and `arg4`. `deprecated_arguments` should return:
            .. code-block:: python
                ((1, 'arg2'), (3, 'arg4'))
        """
        # pylint: disable=unused-argument
        return ()
Referenced by check_deprecated_method().
deprecated_attributes()
Iterable[str] pylint.checkers.deprecated.DeprecatedMixin.deprecated_attributes (self)
Callback returning the deprecated attributes.
Reimplemented in pylint.checkers.stdlib.StdlibChecker.
Definition at line 209 of file deprecated.py.
    def deprecated_attributes(self) -> Iterable[str]:
        """Callback returning the deprecated attributes."""
        return ()
Referenced by check_deprecated_attribute().
deprecated_classes()
Iterable[str] pylint.checkers.deprecated.DeprecatedMixin.deprecated_classes (self, str module)
Callback returning the deprecated classes of module.
Args:
    module (str): name of module checked for deprecated classes
Returns:
    collections.abc.Container of deprecated class names.
Reimplemented in pylint.checkers.stdlib.StdlibChecker.
Definition at line 197 of file deprecated.py.
    def deprecated_classes(self, module: str) -> Iterable[str]:
        """Callback returning the deprecated classes of module.
        Args:
            module (str): name of module checked for deprecated classes
        Returns:
            collections.abc.Container of deprecated class names.
        """
        # pylint: disable=unused-argument
        return ()
Referenced by check_deprecated_class().
deprecated_decorators()
Iterable[str] pylint.checkers.deprecated.DeprecatedMixin.deprecated_decorators (self)
Callback returning the deprecated decorators.
Returns:
    collections.abc.Container of deprecated decorator names.
Reimplemented in pylint.checkers.stdlib.StdlibChecker.
Definition at line 121 of file deprecated.py.
    def deprecated_decorators(self) -> Iterable[str]:
        """Callback returning the deprecated decorators.
        Returns:
            collections.abc.Container of deprecated decorator names.
        """
        return ()
Referenced by visit_decorators().
deprecated_methods()
Container[str] pylint.checkers.deprecated.DeprecatedMixin.deprecated_methods (self)
Callback returning the deprecated methods/functions.
Returns:
    collections.abc.Container of deprecated function/method names.
Reimplemented in pylint.checkers.stdlib.StdlibChecker.
Definition at line 155 of file deprecated.py.
    def deprecated_methods(self) -> Container[str]:
        """Callback returning the deprecated methods/functions.
        Returns:
            collections.abc.Container of deprecated function/method names.
        """
        return ()
Referenced by check_deprecated_method().
deprecated_modules()
Iterable[str] pylint.checkers.deprecated.DeprecatedMixin.deprecated_modules (self)
Callback returning the deprecated modules.
Returns:
    collections.abc.Container of deprecated module names.
Reimplemented in pylint.checkers.imports.ImportsChecker.
Definition at line 189 of file deprecated.py.
    def deprecated_modules(self) -> Iterable[str]:
        """Callback returning the deprecated modules.
        Returns:
            collections.abc.Container of deprecated module names.
        """
        return ()
Referenced by check_deprecated_module().
visit_attribute()
None pylint.checkers.deprecated.DeprecatedMixin.visit_attribute (self, astroid.Attribute node)
Called when an `astroid.Attribute` node is visited.
Definition at line 92 of file deprecated.py.
    def visit_attribute(self, node: astroid.Attribute) -> None:
        """Called when an `astroid.Attribute` node is visited."""
        self.check_deprecated_attribute(node)
References check_deprecated_attribute().
Referenced by pylint.checkers.typecheck.TypeChecker.visit_assignattr(), and pylint.checkers.typecheck.TypeChecker.visit_delattr().
visit_call()
None pylint.checkers.deprecated.DeprecatedMixin.visit_call (self, nodes.Call node)
Called when a :class:`nodes.Call` node is visited.
Reimplemented in pylint.checkers.stdlib.StdlibChecker.
Definition at line 101 of file deprecated.py.
    def visit_call(self, node: nodes.Call) -> None:
        """Called when a :class:`nodes.Call` node is visited."""
        self.check_deprecated_class_in_call(node)
        for inferred in infer_all(node.func):
            # Calling entry point for deprecation check logic.
            self.check_deprecated_method(node, inferred)
References check_deprecated_class_in_call(), and check_deprecated_method().
visit_decorators()
None pylint.checkers.deprecated.DeprecatedMixin.visit_decorators (self, nodes.Decorators node)
Triggered when a decorator statement is seen.
Definition at line 130 of file deprecated.py.
    def visit_decorators(self, node: nodes.Decorators) -> None:
        """Triggered when a decorator statement is seen."""
        children = list(node.get_children())
        if not children:
            return
        if isinstance(children[0], nodes.Call):
            inf = safe_infer(children[0].func)
        else:
            inf = safe_infer(children[0])
        qname = inf.qname() if inf else None
        if qname in self.deprecated_decorators():
            self.add_message("deprecated-decorator", node=node, args=qname)
References pylint.checkers.base_checker.BaseChecker.add_message(), and deprecated_decorators().
visit_import()
None pylint.checkers.deprecated.DeprecatedMixin.visit_import (self, nodes.Import node)
Triggered when an import statement is seen.
Reimplemented in pylint.checkers.imports.ImportsChecker.
Definition at line 112 of file deprecated.py.
    def visit_import(self, node: nodes.Import) -> None:
        """Triggered when an import statement is seen."""
        for name in (name for name, _ in node.names):
            self.check_deprecated_module(node, name)
            if "." in name:
                # Checking deprecation for import module with class
                mod_name, class_name = name.split(".", 1)
                self.check_deprecated_class(node, mod_name, (class_name,))
References check_deprecated_class(), and check_deprecated_module().
visit_importfrom()
None pylint.checkers.deprecated.DeprecatedMixin.visit_importfrom (self, nodes.ImportFrom node)
Triggered when a from statement is seen.
Reimplemented in pylint.checkers.imports.ImportsChecker.
Definition at line 147 of file deprecated.py.
    def visit_importfrom(self, node: nodes.ImportFrom) -> None:
        """Triggered when a from statement is seen."""
        basename = node.modname
        basename = get_import_name(node, basename)
        self.check_deprecated_module(node, basename)
        class_names = (name for name, _ in node.names)
        self.check_deprecated_class(node, basename, class_names)
References check_deprecated_class(), and check_deprecated_module().
Member Data Documentation
DEPRECATED_ARGUMENT_MESSAGE
dict pylint.checkers.deprecated.DeprecatedMixin.DEPRECATED_ARGUMENT_MESSAGE static
Initial value:
=  {
        "W4903": (
            "Using deprecated argument %s of method %s()",
            "deprecated-argument",
            "The argument is marked as deprecated and will be removed in the future.",
            {"old_names": [("W1511", "old-deprecated-argument")], "shared": True},
        ),
    }
Definition at line 64 of file deprecated.py.
DEPRECATED_ATTRIBUTE_MESSAGE
dict pylint.checkers.deprecated.DeprecatedMixin.DEPRECATED_ATTRIBUTE_MESSAGE static
Initial value:
=  {
        "W4906": (
            "Using deprecated attribute %r",
            "deprecated-attribute",
            "The attribute is marked as deprecated and will be removed in the future.",
            {"shared": True},
        ),
    }
Definition at line 37 of file deprecated.py.
DEPRECATED_CLASS_MESSAGE
dict pylint.checkers.deprecated.DeprecatedMixin.DEPRECATED_CLASS_MESSAGE static
Initial value:
=  {
        "W4904": (
            "Using deprecated class %s of module %s",
            "deprecated-class",
            "The class is marked as deprecated and will be removed in the future.",
            {"old_names": [("W1512", "old-deprecated-class")], "shared": True},
        ),
    }
Definition at line 73 of file deprecated.py.
DEPRECATED_DECORATOR_MESSAGE
dict pylint.checkers.deprecated.DeprecatedMixin.DEPRECATED_DECORATOR_MESSAGE static
Initial value:
=  {
        "W4905": (
            "Using deprecated decorator %s()",
            "deprecated-decorator",
            "The decorator is marked as deprecated and will be removed in the future.",
            {"old_names": [("W1513", "old-deprecated-decorator")], "shared": True},
        ),
    }
Definition at line 82 of file deprecated.py.
DEPRECATED_METHOD_MESSAGE
dict pylint.checkers.deprecated.DeprecatedMixin.DEPRECATED_METHOD_MESSAGE static
Initial value:
=  {
        "W4902": (
            "Using deprecated method %s()",
            "deprecated-method",
            "The method is marked as deprecated and will be removed in the future.",
            {"old_names": [("W1505", "old-deprecated-method")], "shared": True},
        ),
    }
Definition at line 55 of file deprecated.py.
DEPRECATED_MODULE_MESSAGE
dict pylint.checkers.deprecated.DeprecatedMixin.DEPRECATED_MODULE_MESSAGE static
Initial value:
=  {
        "W4901": (
            "Deprecated module %r",
            "deprecated-module",
            "A module marked as deprecated is imported.",
            {"old_names": [("W0402", "old-deprecated-module")], "shared": True},
        ),
    }
Definition at line 46 of file deprecated.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pylint/checkers/deprecated.py