Read&Watch: pylint.extensions.redefined_variable_type.MultipleTypesChecker Class Reference
pylint.extensions.redefined_variable_type.MultipleTypesChecker Class Reference
Public Member Functions
None visit_classdef (self, nodes.ClassDef _)
None leave_classdef (self, nodes.ClassDef _)
None visit_module (self, nodes.Module _)
None visit_assign (self, nodes.Assign node)
Public Member Functions inherited from pylint.checkers.base_checker.BaseChecker
None __init__ (self, PyLinter linter)
bool __gt__ (self, Any other)
bool __eq__ (self, object other)
int __hash__ (self)
str __repr__ (self)
str __str__ (self)
str get_full_documentation (self, dict[str, MessageDefinitionTuple] msgs, Iterable[tuple[str, OptionDict, Any]] options, Sequence[tuple[str, str, ReportsCallable]] reports, str|None doc=None, str|None module=None, bool show_options=True)
None add_message (self, str msgid, int|None line=None, nodes.NodeNG|None node=None, Any args=None, Confidence|None confidence=None, int|None col_offset=None, int|None end_lineno=None, int|None end_col_offset=None)
None check_consistency (self)
MessageDefinition create_message_definition_from_tuple (self, str msgid, MessageDefinitionTuple msg_tuple)
list[MessageDefinition] messages (self)
None open (self)
None close (self)
Any get_map_data (self)
None reduce_map_data (self, PyLinter linter, list[Any] data)
Public Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
None __init__ (self, _ArgumentsManager arguments_manager)
Static Public Attributes
None visit_functiondef = visit_classdef
None leave_functiondef = leave_classdef
Static Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
str name = ""
dict msgs = {}
tuple reports = ()
bool enabled = True
Static Public Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
tuple options = ()
dict option_groups_descs = {}
Protected Member Functions
None _check_and_add_messages (self)
Protected Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
Any _option_value (self, str opt)
Iterator[ tuple[str, list[tuple[str, OptionDict, Any]]]|tuple[None, dict[str, list[tuple[str, OptionDict, Any]]]]] _options_by_section (self)
Iterator[tuple[str, OptionDict, Any]] _options_and_values (self, Options|None options=None)
Protected Attributes
list _assigns = [{}]
Protected Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
_arguments_manager = arguments_manager
Additional Inherited Members
Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
linter = linter
messages
Detailed Description
Checks for variable type redefinition (NoneType excepted).
At a function, method, class or module scope
This rule could be improved:
- Currently, if an attribute is set to different types in 2 methods of a
  same class, it won't be detected (see functional test)
- One could improve the support for inference on assignment with tuples,
  ifexpr, etc. Also, it would be great to have support for inference on
  str.split()
Definition at line 18 of file redefined_variable_type.py.
Member Function Documentation
_check_and_add_messages()
None pylint.extensions.redefined_variable_type.MultipleTypesChecker._check_and_add_messages (self) protected
Definition at line 55 of file redefined_variable_type.py.
    def _check_and_add_messages(self) -> None:
        assigns = self._assigns.pop()
        for name, args in assigns.items():
            if len(args) <= 1:
                continue
            orig_node, orig_type = args[0]
            # Check if there is a type in the following nodes that would be
            # different from orig_type.
            for redef_node, redef_type in args[1:]:
                if redef_type == orig_type:
                    continue
                # if a variable is defined to several types in an if node,
                # this is not actually redefining.
                orig_parent = orig_node.parent
                redef_parent = redef_node.parent
                if isinstance(orig_parent, nodes.If):
                    if orig_parent == redef_parent:
                        if (
                            redef_node in orig_parent.orelse
                            and orig_node not in orig_parent.orelse
                        ):
                            orig_node, orig_type = redef_node, redef_type
                            continue
                    elif isinstance(
                        redef_parent, nodes.If
                    ) and redef_parent in orig_parent.nodes_of_class(nodes.If):
                        orig_node, orig_type = redef_node, redef_type
                        continue
                orig_type = orig_type.replace("builtins.", "")
                redef_type = redef_type.replace("builtins.", "")
                self.add_message(
                    "redefined-variable-type",
                    node=redef_node,
                    args=(name, orig_type, redef_type),
                )
                break
References _assigns, and pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by leave_classdef().
leave_classdef()
None pylint.extensions.redefined_variable_type.MultipleTypesChecker.leave_classdef (self, nodes.ClassDef _)
Definition at line 46 of file redefined_variable_type.py.
    def leave_classdef(self, _: nodes.ClassDef) -> None:
        self._check_and_add_messages()
References _check_and_add_messages().
visit_assign()
None pylint.extensions.redefined_variable_type.MultipleTypesChecker.visit_assign (self, nodes.Assign node)
Definition at line 92 of file redefined_variable_type.py.
    def visit_assign(self, node: nodes.Assign) -> None:
        # we don't handle multiple assignment nor slice assignment
        target = node.targets[0]
        if isinstance(target, (nodes.Tuple, nodes.Subscript)):
            return
        # ignore NoneType
        if is_none(node):
            return
        _type = node_type(node.value)
        if _type:
            self._assigns[-1].setdefault(target.as_string(), []).append(
                (node, _type.pytype())
            )
References _assigns.
visit_classdef()
None pylint.extensions.redefined_variable_type.MultipleTypesChecker.visit_classdef (self, nodes.ClassDef _)
Definition at line 42 of file redefined_variable_type.py.
    def visit_classdef(self, _: nodes.ClassDef) -> None:
        self._assigns.append({})
References _assigns.
Referenced by pylint.pyreverse.inspector.Linker.visit_assignname().
visit_module()
None pylint.extensions.redefined_variable_type.MultipleTypesChecker.visit_module (self, nodes.Module _)
Definition at line 52 of file redefined_variable_type.py.
    def visit_module(self, _: nodes.Module) -> None:
        self._assigns: list[dict[str, list[tuple[nodes.Assign, str]]]] = [{}]
Referenced by pylint.pyreverse.inspector.Linker.visit_assignname().
Member Data Documentation
_assigns
list pylint.extensions.redefined_variable_type.MultipleTypesChecker._assigns = [{}] protected
Definition at line 53 of file redefined_variable_type.py.
Referenced by _check_and_add_messages(), visit_assign(), and visit_classdef().
leave_functiondef
None pylint.extensions.redefined_variable_type.MultipleTypesChecker.leave_functiondef = leave_classdef static
Definition at line 50 of file redefined_variable_type.py.
visit_functiondef
None pylint.extensions.redefined_variable_type.MultipleTypesChecker.visit_functiondef = visit_classdef static
Definition at line 49 of file redefined_variable_type.py.
Referenced by pylint.pyreverse.inspector.Linker.visit_assignname(), and astroid.nodes.as_string.AsStringVisitor.visit_partialfunction().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pylint/extensions/redefined_variable_type.py