Read&Watch: django.core.signing.TimestampSigner Class Reference
django.core.signing.TimestampSigner Class Reference
Public Member Functions
timestamp (self)
sign (self, value)
unsign (self, value, max_age=None)
Public Member Functions inherited from django.core.signing.Signer
__init__ (self, *, key=None, sep=":", salt=None, algorithm=None, fallback_keys=None)
signature (self, value, key=None)
sign_object (self, obj, serializer=JSONSerializer, compress=False)
unsign_object (self, signed_obj, serializer=JSONSerializer, **kwargs)
Additional Inherited Members
Public Attributes inherited from django.core.signing.Signer
key = key or settings.SECRET_KEY
tuple fallback_keys
sep = sep
str salt
str algorithm = algorithm or "sha256"
Detailed Description
Definition at line 254 of file signing.py.
Member Function Documentation
sign()
django.core.signing.TimestampSigner.sign (self, value)
Reimplemented from django.core.signing.Signer.
Definition at line 258 of file signing.py.
    def sign(self, value):
        value = "%s%s%s" % (value, self.sep, self.timestamp())
        return super().sign(value)
References django.core.signing.Signer.sep, sign(), and timestamp().
Referenced by sign().
timestamp()
django.core.signing.TimestampSigner.timestamp (self)
Definition at line 255 of file signing.py.
    def timestamp(self):
        return b62_encode(int(time.time()))
References django.core.signing.b62_encode().
Referenced by sign().
unsign()
django.core.signing.TimestampSigner.unsign (self, value, max_age = None)
Retrieve original value and check it wasn't signed more
than max_age seconds ago.
Reimplemented from django.core.signing.Signer.
Definition at line 262 of file signing.py.
    def unsign(self, value, max_age=None):
        """
        Retrieve original value and check it wasn't signed more
        than max_age seconds ago.
        """
        result = super().unsign(value)
        value, timestamp = result.rsplit(self.sep, 1)
        timestamp = b62_decode(timestamp)
        if max_age is not None:
            if isinstance(max_age, datetime.timedelta):
                max_age = max_age.total_seconds()
            # Check timestamp is not older than max_age
            age = time.time() - timestamp
            if age > max_age:
                raise SignatureExpired("Signature age %s > %s seconds" % (age, max_age))
        return value
References django.core.signing.b62_decode(), django.core.signing.Signer.sep, and unsign().
Referenced by unsign().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/core/signing.py