Read&Watch: django.contrib.admin.checks.InlineModelAdminChecks Class Reference
django.contrib.admin.checks.InlineModelAdminChecks Class Reference
Public Member Functions
check (self, inline_obj, **kwargs)
Protected Member Functions
_check_exclude_of_parent_model (self, obj, parent_model)
_check_relation (self, obj, parent_model)
_check_extra (self, obj)
_check_max_num (self, obj)
_check_min_num (self, obj)
_check_formset (self, obj)
Protected Member Functions inherited from django.contrib.admin.checks.BaseModelAdminChecks
_check_autocomplete_fields (self, obj)
_check_autocomplete_fields_item (self, obj, field_name, label)
_check_raw_id_fields (self, obj)
_check_raw_id_fields_item (self, obj, field_name, label)
_check_fields (self, obj)
_check_fieldsets (self, obj)
_check_fieldsets_item (self, obj, fieldset, label, seen_fields)
_check_field_spec (self, obj, fields, label)
_check_field_spec_item (self, obj, field_name, label)
_check_exclude (self, obj)
_check_form (self, obj)
_check_filter_vertical (self, obj)
_check_filter_horizontal (self, obj)
_check_filter_item (self, obj, field_name, label)
_check_radio_fields (self, obj)
_check_radio_fields_key (self, obj, field_name, label)
_check_radio_fields_value (self, obj, val, label)
_check_view_on_site_url (self, obj)
_check_prepopulated_fields (self, obj)
_check_prepopulated_fields_key (self, obj, field_name, label)
_check_prepopulated_fields_value (self, obj, val, label)
_check_prepopulated_fields_value_item (self, obj, field_name, label)
_check_ordering (self, obj)
_check_ordering_item (self, obj, field_name, label)
_check_readonly_fields (self, obj)
_check_readonly_fields_item (self, obj, field_name, label)
Detailed Description
Definition at line 1240 of file checks.py.
Member Function Documentation
_check_exclude_of_parent_model()
django.contrib.admin.checks.InlineModelAdminChecks._check_exclude_of_parent_model (self, obj, parent_model) protected
Reimplemented in django.contrib.contenttypes.admin.GenericInlineModelAdminChecks.
Definition at line 1253 of file checks.py.
    def _check_exclude_of_parent_model(self, obj, parent_model):
        # Do not perform more specific checks if the base checks result in an
        # error.
        errors = super()._check_exclude(obj)
        if errors:
            return []
        # Skip if `fk_name` is invalid.
        if self._check_relation(obj, parent_model):
            return []
        if obj.exclude is None:
            return []
        fk = _get_foreign_key(parent_model, obj.model, fk_name=obj.fk_name)
        if fk.name in obj.exclude:
            return [
                checks.Error(
                    "Cannot exclude the field '%s', because it is the foreign key "
                    "to the parent model '%s'."
                    % (
                        fk.name,
                        parent_model._meta.label,
                    ),
                    obj=obj.__class__,
                    id="admin.E201",
                )
            ]
        else:
            return []
References django.contrib.admin.checks.BaseModelAdminChecks._check_exclude(), and _check_relation().
Referenced by check().
_check_extra()
django.contrib.admin.checks.InlineModelAdminChecks._check_extra (self, obj) protected
Check that extra is an integer.
Definition at line 1292 of file checks.py.
    def _check_extra(self, obj):
        """Check that extra is an integer."""
        if not isinstance(obj.extra, int):
            return must_be("an integer", option="extra", obj=obj, id="admin.E203")
        else:
            return []
References django.contrib.admin.checks.must_be().
Referenced by check().
_check_formset()
django.contrib.admin.checks.InlineModelAdminChecks._check_formset (self, obj) protected
Check formset is a subclass of BaseModelFormSet.
Definition at line 1320 of file checks.py.
    def _check_formset(self, obj):
        """Check formset is a subclass of BaseModelFormSet."""
        if not _issubclass(obj.formset, BaseModelFormSet):
            return must_inherit_from(
                parent="BaseModelFormSet", option="formset", obj=obj, id="admin.E206"
            )
        else:
            return []
References django.contrib.admin.checks._issubclass(), and django.contrib.admin.checks.must_inherit_from().
Referenced by check().
_check_max_num()
django.contrib.admin.checks.InlineModelAdminChecks._check_max_num (self, obj) protected
Check that max_num is an integer.
Definition at line 1300 of file checks.py.
    def _check_max_num(self, obj):
        """Check that max_num is an integer."""
        if obj.max_num is None:
            return []
        elif not isinstance(obj.max_num, int):
            return must_be("an integer", option="max_num", obj=obj, id="admin.E204")
        else:
            return []
References django.contrib.admin.checks.must_be().
Referenced by check().
_check_min_num()
django.contrib.admin.checks.InlineModelAdminChecks._check_min_num (self, obj) protected
Check that min_num is an integer.
Definition at line 1310 of file checks.py.
    def _check_min_num(self, obj):
        """Check that min_num is an integer."""
        if obj.min_num is None:
            return []
        elif not isinstance(obj.min_num, int):
            return must_be("an integer", option="min_num", obj=obj, id="admin.E205")
        else:
            return []
References django.contrib.admin.checks.must_be().
Referenced by check().
_check_relation()
django.contrib.admin.checks.InlineModelAdminChecks._check_relation (self, obj, parent_model) protected
Reimplemented in django.contrib.contenttypes.admin.GenericInlineModelAdminChecks.
Definition at line 1284 of file checks.py.
    def _check_relation(self, obj, parent_model):
        try:
            _get_foreign_key(parent_model, obj.model, fk_name=obj.fk_name)
        except ValueError as e:
            return [checks.Error(e.args[0], obj=obj.__class__, id="admin.E202")]
        else:
            return []
Referenced by _check_exclude_of_parent_model(), and check().
check()
django.contrib.admin.checks.InlineModelAdminChecks.check (self, inline_obj, ** kwargs)
Reimplemented from django.contrib.admin.checks.BaseModelAdminChecks.
Definition at line 1241 of file checks.py.
    def check(self, inline_obj, **kwargs):
        parent_model = inline_obj.parent_model
        return [
            *super().check(inline_obj),
            *self._check_relation(inline_obj, parent_model),
            *self._check_exclude_of_parent_model(inline_obj, parent_model),
            *self._check_extra(inline_obj),
            *self._check_max_num(inline_obj),
            *self._check_min_num(inline_obj),
            *self._check_formset(inline_obj),
        ]
References _check_exclude_of_parent_model(), _check_extra(), _check_formset(), _check_max_num(), _check_min_num(), _check_relation(), and check().
Referenced by check(), pip._vendor.packaging._tokenizer.Tokenizer.consume(), pip._vendor.packaging._tokenizer.Tokenizer.enclosing_tokens(), django.core.management.base.BaseCommand.execute(), pip._vendor.packaging._tokenizer.Tokenizer.expect(), django.core.management.commands.check.Command.handle(), django.core.management.commands.migrate.Command.handle(), django.core.management.commands.runserver.Command.inner_run(), and pip._vendor.pygments.scanner.Scanner.test().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/admin/checks.py