Read&Watch: django.core.files.uploadedfile.SimpleUploadedFile Class Reference
django.core.files.uploadedfile.SimpleUploadedFile Class Reference
Public Member Functions
__init__ (self, name, content, content_type="text/plain")
from_dict (cls, file_dict)
Public Member Functions inherited from django.core.files.uploadedfile.InMemoryUploadedFile
__init__ (self, file, field_name, name, content_type, size, charset, content_type_extra=None)
open (self, mode=None)
chunks (self, chunk_size=None)
multiple_chunks (self, chunk_size=None)
Public Member Functions inherited from django.core.files.uploadedfile.UploadedFile
__init__ (self, file=None, name=None, content_type=None, size=None, charset=None, content_type_extra=None)
__repr__ (self)
Public Member Functions inherited from django.core.files.base.File
__init__ (self, file, name=None)
__str__ (self)
__repr__ (self)
__bool__ (self)
__len__ (self)
size (self)
__iter__ (self)
__enter__ (self)
__exit__ (self, exc_type, exc_value, tb)
close (self)
Public Member Functions inherited from django.core.files.utils.FileProxyMixin
closed (self)
readable (self)
writable (self)
seekable (self)
__iter__ (self)
Additional Inherited Members
Public Attributes inherited from django.core.files.uploadedfile.InMemoryUploadedFile
field_name = field_name
Public Attributes inherited from django.core.files.uploadedfile.UploadedFile
content_type = content_type
charset = charset
content_type_extra = content_type_extra
Public Attributes inherited from django.core.files.base.File
name = name
mode = file.mode
Public Attributes inherited from django.core.files.utils.FileProxyMixin
closed
file
Static Public Attributes inherited from django.core.files.base.File
int DEFAULT_CHUNK_SIZE = 64 * 2**10
Protected Member Functions inherited from django.core.files.uploadedfile.UploadedFile
_get_name (self)
_set_name (self, name)
Protected Attributes inherited from django.core.files.uploadedfile.UploadedFile
_name = name
Properties inherited from django.core.files.uploadedfile.UploadedFile
name = property(_get_name, _set_name)
Properties inherited from django.core.files.utils.FileProxyMixin
encoding = property(lambda self: self.file.encoding)
fileno = property(lambda self: self.file.fileno)
flush = property(lambda self: self.file.flush)
isatty = property(lambda self: self.file.isatty)
newlines = property(lambda self: self.file.newlines)
read = property(lambda self: self.file.read)
readinto = property(lambda self: self.file.readinto)
readline = property(lambda self: self.file.readline)
readlines = property(lambda self: self.file.readlines)
seek = property(lambda self: self.file.seek)
tell = property(lambda self: self.file.tell)
truncate = property(lambda self: self.file.truncate)
write = property(lambda self: self.file.write)
writelines = property(lambda self: self.file.writelines)
Detailed Description
A simple representation of a file, which just has content, size, and a name.
Definition at line 127 of file uploadedfile.py.
Constructor & Destructor Documentation
__init__()
django.core.files.uploadedfile.SimpleUploadedFile.__init__ (self, name, content, content_type = "text/plain")
Definition at line 132 of file uploadedfile.py.
    def __init__(self, name, content, content_type="text/plain"):
        content = content or b""
        super().__init__(
            BytesIO(content), None, name, content_type, len(content), None, None
        )
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Function Documentation
from_dict()
django.core.files.uploadedfile.SimpleUploadedFile.from_dict (cls, file_dict)
Create a SimpleUploadedFile object from a dictionary with keys:
   - filename
   - content-type
   - content
Definition at line 139 of file uploadedfile.py.
    def from_dict(cls, file_dict):
        """
        Create a SimpleUploadedFile object from a dictionary with keys:
           - filename
           - content-type
           - content
        """
        return cls(
            file_dict["filename"],
            file_dict["content"],
            file_dict.get("content-type", "text/plain"),
        )
Referenced by pip._internal.models.direct_url.DirectUrl.from_json(), and pip._internal.models.direct_url.DirectUrl.validate().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/core/files/uploadedfile.py