Read&Watch: pip._vendor.resolvelib.structs.DirectedGraph Class Reference
pip._vendor.resolvelib.structs.DirectedGraph Class Reference
Public Member Functions
__init__ (self)
__iter__ (self)
__len__ (self)
__contains__ (self, key)
copy (self)
add (self, key)
remove (self, key)
connected (self, f, t)
connect (self, f, t)
iter_edges (self)
iter_children (self, key)
iter_parents (self, key)
Protected Attributes
_vertices = set()
dict _forwards = {}
dict _backwards = {}
Detailed Description
A graph structure with directed edges.
Definition at line 6 of file structs.py.
Constructor & Destructor Documentation
__init__()
pip._vendor.resolvelib.structs.DirectedGraph.__init__ (self)
Definition at line 9 of file structs.py.
    def __init__(self):
        self._vertices = set()
        self._forwards = {}  # <key> -> Set[<key>]
        self._backwards = {}  # <key> -> Set[<key>]
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
__contains__()
pip._vendor.resolvelib.structs.DirectedGraph.__contains__ (self, key)
Definition at line 20 of file structs.py.
    def __contains__(self, key):
        return key in self._vertices
References _vertices.
__iter__()
pip._vendor.resolvelib.structs.DirectedGraph.__iter__ (self)
Definition at line 14 of file structs.py.
    def __iter__(self):
        return iter(self._vertices)
References _vertices.
Referenced by django.db.models.query.BaseIterable._async_generator().
__len__()
pip._vendor.resolvelib.structs.DirectedGraph.__len__ (self)
Definition at line 17 of file structs.py.
    def __len__(self):
        return len(self._vertices)
References _vertices.
add()
pip._vendor.resolvelib.structs.DirectedGraph.add (self, key)
Add a new vertex to the graph.
Definition at line 31 of file structs.py.
    def add(self, key):
        """Add a new vertex to the graph."""
        if key in self._vertices:
            raise ValueError("vertex exists")
        self._vertices.add(key)
        self._forwards[key] = set()
        self._backwards[key] = set()
References _backwards, _forwards, _vertices, and add().
Referenced by responses.RequestsMock._add_from_file(), add(), connect(), pip._vendor.urllib3._collections.HTTPHeaderDict.extend(), urllib3._collections.HTTPHeaderDict.extend(), and responses.RequestsMock.upsert().
connect()
pip._vendor.resolvelib.structs.DirectedGraph.connect (self, f, t)
Connect two existing vertices.
Nothing happens if the vertices are already connected.
Definition at line 50 of file structs.py.
    def connect(self, f, t):
        """Connect two existing vertices.
        Nothing happens if the vertices are already connected.
        """
        if t not in self._vertices:
            raise KeyError(t)
        self._forwards[f].add(t)
        self._backwards[t].add(f)
References _backwards, _forwards, _vertices, and add().
connected()
pip._vendor.resolvelib.structs.DirectedGraph.connected (self, f, t)
Definition at line 47 of file structs.py.
    def connected(self, f, t):
        return f in self._backwards[t] and t in self._forwards[f]
References _backwards, and _forwards.
copy()
pip._vendor.resolvelib.structs.DirectedGraph.copy (self)
Return a shallow copy of this graph.
Definition at line 23 of file structs.py.
    def copy(self):
        """Return a shallow copy of this graph."""
        other = DirectedGraph()
        other._vertices = set(self._vertices)
        other._forwards = {k: set(v) for k, v in self._forwards.items()}
        other._backwards = {k: set(v) for k, v in self._backwards.items()}
        return other
References _backwards, _forwards, and _vertices.
Referenced by pip._vendor.rich.text.Text.__add__(), tomlkit._types._CustomList.__add__(), tomlkit._types._CustomDict.__or__(), urllib3._collections.HTTPHeaderDict.__or__(), django.contrib.gis.db.models.functions.OracleToleranceMixin.as_oracle(), django.db.models.functions.mixins.FixDecimalInputMixin.as_postgresql(), django.contrib.gis.db.models.functions.SQLiteDecimalToFloatMixin.as_sqlite(), pip._vendor.rich.text.Text.divide(), pip._vendor.rich.console.ConsoleOptions.reset_height(), pip._vendor.rich.text.Text.split(), pip._vendor.rich.console.ConsoleOptions.update(), pip._vendor.rich.console.ConsoleOptions.update_dimensions(), pip._vendor.rich.console.ConsoleOptions.update_height(), pip._vendor.rich.console.ConsoleOptions.update_width(), and pip._vendor.rich.text.Text.with_indent_guides().
iter_children()
pip._vendor.resolvelib.structs.DirectedGraph.iter_children (self, key)
Definition at line 65 of file structs.py.
    def iter_children(self, key):
        return iter(self._forwards[key])
References _forwards.
iter_edges()
pip._vendor.resolvelib.structs.DirectedGraph.iter_edges (self)
Definition at line 60 of file structs.py.
    def iter_edges(self):
        for f, children in self._forwards.items():
            for t in children:
                yield f, t
References _forwards.
iter_parents()
pip._vendor.resolvelib.structs.DirectedGraph.iter_parents (self, key)
Definition at line 68 of file structs.py.
    def iter_parents(self, key):
        return iter(self._backwards[key])
References _backwards.
remove()
pip._vendor.resolvelib.structs.DirectedGraph.remove (self, key)
Remove a vertex from the graph, disconnecting all edges from/to it.
Definition at line 39 of file structs.py.
    def remove(self, key):
        """Remove a vertex from the graph, disconnecting all edges from/to it."""
        self._vertices.remove(key)
        for f in self._forwards.pop(key):
            self._backwards[f].remove(key)
        for t in self._backwards.pop(key):
            self._forwards[t].remove(key)
References _backwards, _forwards, _vertices, and remove().
Referenced by tomlkit.container.Container.__delitem__(), tomlkit.items.AbstractTable.__delitem__(), tomlkit.container.Container._replace_at(), and remove().
Member Data Documentation
_backwards
dict pip._vendor.resolvelib.structs.DirectedGraph._backwards = {} protected
Definition at line 12 of file structs.py.
Referenced by add(), connect(), connected(), copy(), iter_parents(), and remove().
_forwards
dict pip._vendor.resolvelib.structs.DirectedGraph._forwards = {} protected
Definition at line 11 of file structs.py.
Referenced by add(), connect(), connected(), copy(), iter_children(), iter_edges(), and remove().
_vertices
pip._vendor.resolvelib.structs.DirectedGraph._vertices = set() protected
Definition at line 10 of file structs.py.
Referenced by __contains__(), __iter__(), __len__(), add(), connect(), copy(), and remove().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/resolvelib/structs.py