Read&Watch: sqlparse.sql.Identifier Class Reference
sqlparse.sql.Identifier Class Reference
Public Member Functions
is_wildcard (self)
get_typecast (self)
get_ordering (self)
get_array_indices (self)
Public Member Functions inherited from sqlparse.sql.NameAliasMixin
get_real_name (self)
get_alias (self)
Public Member Functions inherited from sqlparse.sql.TokenList
__init__ (self, tokens=None)
__str__ (self)
__iter__ (self)
__getitem__ (self, item)
get_token_at_offset (self, offset)
flatten (self)
get_sublists (self)
token_first (self, skip_ws=True, skip_cm=False)
token_next_by (self, i=None, m=None, t=None, idx=-1, end=None)
token_not_matching (self, funcs, idx)
token_matching (self, funcs, idx)
token_prev (self, idx, skip_ws=True, skip_cm=False)
token_next (self, idx, skip_ws=True, skip_cm=False, _reverse=False)
token_index (self, token, start=0)
group_tokens (self, grp_cls, start, end, include_end=True, extend=False)
insert_before (self, where, token)
insert_after (self, where, token, skip_ws=True)
has_alias (self)
get_alias (self)
get_name (self)
get_real_name (self)
get_parent_name (self)
Public Member Functions inherited from sqlparse.sql.Token
__init__ (self, ttype, value)
__str__ (self)
__repr__ (self)
match (self, ttype, values, regex=False)
within (self, group_cls)
is_child_of (self, other)
has_ancestor (self, other)
Additional Inherited Members
Public Attributes inherited from sqlparse.sql.NameAliasMixin
tokens
Public Attributes inherited from sqlparse.sql.TokenList
tokens = tokens or []
Public Attributes inherited from sqlparse.sql.Token
value = value
ttype = ttype
parent = None
bool is_group = False
is_keyword = ttype in T.Keyword
is_whitespace = self.ttype in T.Whitespace
is_newline = self.ttype in T.Newline
normalized = value.upper() if self.is_keyword else value
Protected Member Functions inherited from sqlparse.sql.TokenList
_get_repr_name (self)
_pprint_tree (self, max_depth=None, depth=0, f=None, _pre='')
_groupable_tokens (self)
_token_matching (self, funcs, start=0, end=None, reverse=False)
_get_first_name (self, idx=None, reverse=False, keywords=False, real_name=False)
Protected Member Functions inherited from sqlparse.sql.Token
_get_repr_value (self)
Detailed Description
Represents an identifier.
Identifiers may have aliases or typecasts.
Definition at line 448 of file sql.py.
Member Function Documentation
get_array_indices()
sqlparse.sql.Identifier.get_array_indices (self)
Returns an iterator of index token lists
Definition at line 470 of file sql.py.
    def get_array_indices(self):
        """Returns an iterator of index token lists"""
        for token in self.tokens:
            if isinstance(token, SquareBrackets):
                # Use [1:-1] index to discard the square brackets
                yield token.tokens[1:-1]
get_ordering()
sqlparse.sql.Identifier.get_ordering (self)
Returns the ordering or ``None`` as uppercase string.
Definition at line 465 of file sql.py.
    def get_ordering(self):
        """Returns the ordering or ``None`` as uppercase string."""
        _, ordering = self.token_next_by(t=T.Keyword.Order)
        return ordering.normalized if ordering else None
References sqlparse.sql.TokenList.token_next_by().
get_typecast()
sqlparse.sql.Identifier.get_typecast (self)
Returns the typecast or ``None`` of this object as a string.
Definition at line 459 of file sql.py.
    def get_typecast(self):
        """Returns the typecast or ``None`` of this object as a string."""
        midx, marker = self.token_next_by(m=(T.Punctuation, '::'))
        nidx, next_ = self.token_next(midx, skip_ws=False)
        return next_.value if next_ else None
References sqlparse.sql.TokenList.token_next(), and sqlparse.sql.TokenList.token_next_by().
is_wildcard()
sqlparse.sql.Identifier.is_wildcard (self)
Return ``True`` if this identifier contains a wildcard.
Definition at line 454 of file sql.py.
    def is_wildcard(self):
        """Return ``True`` if this identifier contains a wildcard."""
        _, token = self.token_next_by(t=T.Wildcard)
        return token is not None
References sqlparse.sql.TokenList.token_next_by().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/sqlparse/sql.py