Read&Watch: tomli._parser.Flags Class Reference
tomli._parser.Flags Class Reference
Public Member Functions
None __init__ (self)
None unset_all (self, Key key)
None set_for_relative_key (self, Key head_key, Key rel_key, int flag)
None set (self, Key key, int flag, *, bool recursive)
bool is_ (self, Key key, int flag)
Static Public Attributes
int FROZEN = 0
int EXPLICIT_NEST = 1
Protected Attributes
dict _flags = {}
Detailed Description
Flags that map to parsed keys/namespaces.
Definition at line 131 of file _parser.py.
Constructor & Destructor Documentation
__init__()
None tomli._parser.Flags.__init__ (self)
Definition at line 140 of file _parser.py.
    def __init__(self) -> None:
        self._flags: Dict[str, dict] = {}
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
is_()
bool tomli._parser.Flags.is_ (self, Key key, int flag)
Definition at line 175 of file _parser.py.
    def is_(self, key: Key, flag: int) -> bool:
        if not key:
            return False  # document root has no flags
        cont = self._flags
        for k in key[:-1]:
            if k not in cont:
                return False
            inner_cont = cont[k]
            if flag in inner_cont["recursive_flags"]:
                return True
            cont = inner_cont["nested"]
        key_stem = key[-1]
        if key_stem in cont:
            cont = cont[key_stem]
            return flag in cont["flags"] or flag in cont["recursive_flags"]
        return False
References _flags.
set()
None tomli._parser.Flags.set (self, Key key, int flag, * , bool recursive)
Definition at line 164 of file _parser.py.
    def set(self, key: Key, flag: int, *, recursive: bool) -> None:  # noqa: A003
        cont = self._flags
        key_parent, key_stem = key[:-1], key[-1]
        for k in key_parent:
            if k not in cont:
                cont[k] = {"flags": set(), "recursive_flags": set(), "nested": {}}
            cont = cont[k]["nested"]
        if key_stem not in cont:
            cont[key_stem] = {"flags": set(), "recursive_flags": set(), "nested": {}}
        cont[key_stem]["recursive_flags" if recursive else "flags"].add(flag)
References _flags, and set().
Referenced by pip._vendor.distlib.metadata.LegacyMetadata.__setitem__(), pip._vendor.requests.cookies.RequestsCookieJar.__setitem__(), requests.cookies.RequestsCookieJar.__setitem__(), pip._vendor.tomli._parser.Flags.finalize_pending(), pip._vendor.distlib.metadata.LegacyMetadata.read_file(), set(), set_for_relative_key(), and pip._vendor.distlib.metadata.LegacyMetadata.update().
set_for_relative_key()
None tomli._parser.Flags.set_for_relative_key (self, Key head_key, Key rel_key, int flag)
Definition at line 151 of file _parser.py.
    def set_for_relative_key(self, head_key: Key, rel_key: Key, flag: int) -> None:
        cont = self._flags
        for k in head_key:
            if k not in cont:
                cont[k] = {"flags": set(), "recursive_flags": set(), "nested": {}}
            cont = cont[k]["nested"]
        for k in rel_key:
            if k in cont:
                cont[k]["flags"].add(flag)
            else:
                cont[k] = {"flags": {flag}, "recursive_flags": set(), "nested": {}}
            cont = cont[k]["nested"]
References _flags, and set().
unset_all()
None tomli._parser.Flags.unset_all (self, Key key)
Definition at line 143 of file _parser.py.
    def unset_all(self, key: Key) -> None:
        cont = self._flags
        for k in key[:-1]:
            if k not in cont:
                return
            cont = cont[k]["nested"]
        cont.pop(key[-1], None)
References _flags.
Member Data Documentation
_flags
dict tomli._parser.Flags._flags = {} protected
Definition at line 141 of file _parser.py.
Referenced by pip._vendor.tomli._parser.Flags.is_(), is_(), pip._vendor.tomli._parser.Flags.set(), set(), set_for_relative_key(), pip._vendor.tomli._parser.Flags.unset_all(), and unset_all().
EXPLICIT_NEST
int tomli._parser.Flags.EXPLICIT_NEST = 1 static
Definition at line 138 of file _parser.py.
FROZEN
int tomli._parser.Flags.FROZEN = 0 static
Definition at line 135 of file _parser.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/isort/_vendored/tomli/_parser.py