Read&Watch: isort.exceptions.InvalidSettingsPath Class Reference
isort.exceptions.InvalidSettingsPath Class Reference
Public Member Functions
__init__ (self, str settings_path)
Public Member Functions inherited from isort.exceptions.ISortError
__reduce__ (self)
Public Attributes
settings_path = settings_path
Detailed Description
Raised when a settings path is provided that is neither a valid file or directory
Definition at line 17 of file exceptions.py.
Constructor & Destructor Documentation
__init__()
isort.exceptions.InvalidSettingsPath.__init__ (self, str settings_path)
Definition at line 20 of file exceptions.py.
    def __init__(self, settings_path: str):
        super().__init__(
            f"isort was told to use the settings_path: {settings_path} as the base directory or "
            "file that represents the starting point of config file discovery, but it does not "
            "exist."
        )
        self.settings_path = settings_path
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Data Documentation
settings_path
isort.exceptions.InvalidSettingsPath.settings_path = settings_path
Definition at line 26 of file exceptions.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/isort/exceptions.py