Read&Watch: pylint.extensions.private_import.PrivateImportChecker Class Reference
pylint.extensions.private_import.PrivateImportChecker Class Reference
Public Member Functions
None __init__ (self, PyLinter linter)
None visit_import (self, nodes.Import node)
None visit_importfrom (self, nodes.ImportFrom node)
Public Member Functions inherited from pylint.checkers.base_checker.BaseChecker
None __init__ (self, PyLinter linter)
bool __gt__ (self, Any other)
bool __eq__ (self, object other)
int __hash__ (self)
str __repr__ (self)
str __str__ (self)
str get_full_documentation (self, dict[str, MessageDefinitionTuple] msgs, Iterable[tuple[str, OptionDict, Any]] options, Sequence[tuple[str, str, ReportsCallable]] reports, str|None doc=None, str|None module=None, bool show_options=True)
None add_message (self, str msgid, int|None line=None, nodes.NodeNG|None node=None, Any args=None, Confidence|None confidence=None, int|None col_offset=None, int|None end_lineno=None, int|None end_col_offset=None)
None check_consistency (self)
MessageDefinition create_message_definition_from_tuple (self, str msgid, MessageDefinitionTuple msg_tuple)
list[MessageDefinition] messages (self)
None open (self)
None close (self)
Any get_map_data (self)
None reduce_map_data (self, PyLinter linter, list[Any] data)
Public Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
None __init__ (self, _ArgumentsManager arguments_manager)
Static Public Member Functions
bool same_root_dir (nodes.Import|nodes.ImportFrom node, str import_mod_name)
Public Attributes
dict all_used_type_annotations = {}
bool populated_annotations = False
Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
linter = linter
messages
Protected Member Functions
list[str] _get_private_imports (self, list[str] names)
list[str] _get_type_annotation_names (self, nodes.Import|nodes.ImportFrom node, list[str] names)
None _populate_type_annotations (self, nodes.LocalsDictNodeNG node, dict[str, bool] all_used_type_annotations)
None _populate_type_annotations_function (self, nodes.FunctionDef node, dict[str, bool] all_used_type_annotations)
str|None _populate_type_annotations_annotation (self, nodes.Attribute|nodes.Subscript|nodes.Name|None node, dict[str, bool] all_used_type_annotations)
Protected Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
Any _option_value (self, str opt)
Iterator[ tuple[str, list[tuple[str, OptionDict, Any]]]|tuple[None, dict[str, list[tuple[str, OptionDict, Any]]]]] _options_by_section (self)
Iterator[tuple[str, OptionDict, Any]] _options_and_values (self, Options|None options=None)
Static Protected Member Functions
bool _name_is_private (str name)
bool _assignments_call_private_name (list[nodes.AnnAssign|nodes.Assign] assignments, str private_name)
Additional Inherited Members
Static Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
str name = ""
dict msgs = {}
tuple reports = ()
bool enabled = True
Static Public Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
tuple options = ()
dict option_groups_descs = {}
Protected Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
_arguments_manager = arguments_manager
Detailed Description
Definition at line 21 of file private_import.py.
Constructor & Destructor Documentation
__init__()
None pylint.extensions.private_import.PrivateImportChecker.__init__ (self, PyLinter linter)
Definition at line 33 of file private_import.py.
    def __init__(self, linter: PyLinter) -> None:
        BaseChecker.__init__(self, linter)
        # A mapping of private names used as a type annotation to whether it is an acceptable import
        self.all_used_type_annotations: dict[str, bool] = {}
        self.populated_annotations = False
Member Function Documentation
_assignments_call_private_name()
bool pylint.extensions.private_import.PrivateImportChecker._assignments_call_private_name (list[nodes.AnnAssign | nodes.Assign] assignments, str private_name) static protected
Returns True if no assignments involve accessing `private_name`.
Definition at line 218 of file private_import.py.
    ) -> bool:
        """Returns True if no assignments involve accessing `private_name`."""
        if all(not assignment.value for assignment in assignments):
            # Variable annotated but unassigned is not allowed because there may be
            # possible illegal access elsewhere
            return False
        for assignment in assignments:
            current_attribute = None
            if isinstance(assignment.value, nodes.Call):
                current_attribute = assignment.value.func
            elif isinstance(assignment.value, nodes.Attribute):
                current_attribute = assignment.value
            elif isinstance(assignment.value, nodes.Name):
                current_attribute = assignment.value.name
            if not current_attribute:
                continue
            while isinstance(current_attribute, (nodes.Attribute, nodes.Call)):
                if isinstance(current_attribute, nodes.Call):
                    current_attribute = current_attribute.func
                if not isinstance(current_attribute, nodes.Name):
                    current_attribute = current_attribute.expr
            if (
                isinstance(current_attribute, nodes.Name)
                and current_attribute.name == private_name
            ):
                return False
        return True
Referenced by _populate_type_annotations().
_get_private_imports()
list[str] pylint.extensions.private_import.PrivateImportChecker._get_private_imports (self, list[str] names) protected
Returns the private names from input names by a simple string check.
Definition at line 99 of file private_import.py.
    def _get_private_imports(self, names: list[str]) -> list[str]:
        """Returns the private names from input names by a simple string check."""
        return [name for name in names if self._name_is_private(name)]
References _name_is_private().
Referenced by visit_import(), and visit_importfrom().
_get_type_annotation_names()
list[str] pylint.extensions.private_import.PrivateImportChecker._get_type_annotation_names (self, nodes.Import | nodes.ImportFrom node, list[str] names) protected
Removes from names any names that are used as type annotations with no other
illegal usages.
Definition at line 114 of file private_import.py.
    ) -> list[str]:
        """Removes from names any names that are used as type annotations with no other
        illegal usages.
        """
        if names and not self.populated_annotations:
            self._populate_type_annotations(node.root(), self.all_used_type_annotations)
            self.populated_annotations = True
        return [
            n
            for n in names
            if n not in self.all_used_type_annotations
            or (
                n in self.all_used_type_annotations
                and not self.all_used_type_annotations[n]
            )
        ]
References _populate_type_annotations(), all_used_type_annotations, and populated_annotations.
Referenced by visit_import(), and visit_importfrom().
_name_is_private()
bool pylint.extensions.private_import.PrivateImportChecker._name_is_private (str name) static protected
Returns true if the name exists, starts with `_`, and if len(name) > 4
it is not a dunder, i.e. it does not begin and end with two underscores.
Definition at line 104 of file private_import.py.
    def _name_is_private(name: str) -> bool:
        """Returns true if the name exists, starts with `_`, and if len(name) > 4
        it is not a dunder, i.e. it does not begin and end with two underscores.
        """
        return (
            bool(name)
            and name[0] == "_"
            and (len(name) <= 4 or name[1] != "_" or name[-2:] != "__")
        )
Referenced by _get_private_imports().
_populate_type_annotations()
None pylint.extensions.private_import.PrivateImportChecker._populate_type_annotations (self, nodes.LocalsDictNodeNG node, dict[str, bool] all_used_type_annotations) protected
Adds to `all_used_type_annotations` all names ever used as a type annotation
in the node's (nested) scopes and whether they are only used as annotation.
Definition at line 134 of file private_import.py.
    ) -> None:
        """Adds to `all_used_type_annotations` all names ever used as a type annotation
        in the node's (nested) scopes and whether they are only used as annotation.
        """
        for name in node.locals:
            # If we find a private type annotation, make sure we do not mask illegal usages
            private_name = None
            # All the assignments using this variable that we might have to check for
            # illegal usages later
            name_assignments = []
            for usage_node in node.locals[name]:
                if isinstance(usage_node, nodes.AssignName) and isinstance(
                    usage_node.parent, (nodes.AnnAssign, nodes.Assign)
                ):
                    assign_parent = usage_node.parent
                    if isinstance(assign_parent, nodes.AnnAssign):
                        name_assignments.append(assign_parent)
                        private_name = self._populate_type_annotations_annotation(
                            usage_node.parent.annotation, all_used_type_annotations
                        )
                    elif isinstance(assign_parent, nodes.Assign):
                        name_assignments.append(assign_parent)
                if isinstance(usage_node, nodes.FunctionDef):
                    self._populate_type_annotations_function(
                        usage_node, all_used_type_annotations
                    )
                if isinstance(usage_node, nodes.LocalsDictNodeNG):
                    self._populate_type_annotations(
                        usage_node, all_used_type_annotations
                    )
            if private_name is not None:
                # Found a new private annotation, make sure we are not accessing it elsewhere
                all_used_type_annotations[private_name] = (
                    self._assignments_call_private_name(name_assignments, private_name)
                )
References _assignments_call_private_name(), _populate_type_annotations(), _populate_type_annotations_annotation(), and _populate_type_annotations_function().
Referenced by _get_type_annotation_names(), and _populate_type_annotations().
_populate_type_annotations_annotation()
str | None pylint.extensions.private_import.PrivateImportChecker._populate_type_annotations_annotation (self, nodes.Attribute | nodes.Subscript | nodes.Name | None node, dict[str, bool] all_used_type_annotations) protected
Handles the possibility of an annotation either being a Name, i.e. just type,
or a Subscript e.g. `Optional[type]` or an Attribute, e.g. `pylint.lint.linter`.
Definition at line 189 of file private_import.py.
    ) -> str | None:
        """Handles the possibility of an annotation either being a Name, i.e. just type,
        or a Subscript e.g. `Optional[type]` or an Attribute, e.g. `pylint.lint.linter`.
        """
        if isinstance(node, nodes.Name) and node.name not in all_used_type_annotations:
            all_used_type_annotations[node.name] = True
            return node.name  # type: ignore[no-any-return]
        if isinstance(node, nodes.Subscript):  # e.g. Optional[List[str]]
            # slice is the next nested type
            self._populate_type_annotations_annotation(
                node.slice, all_used_type_annotations
            )
            # value is the current type name: could be a Name or Attribute
            return self._populate_type_annotations_annotation(
                node.value, all_used_type_annotations
            )
        if isinstance(node, nodes.Attribute):
            # An attribute is a type like `pylint.lint.pylinter`. node.expr is the next level
            # up, could be another attribute
            return self._populate_type_annotations_annotation(
                node.expr, all_used_type_annotations
            )
        return None
References _populate_type_annotations_annotation().
Referenced by _populate_type_annotations(), _populate_type_annotations_annotation(), and _populate_type_annotations_function().
_populate_type_annotations_function()
None pylint.extensions.private_import.PrivateImportChecker._populate_type_annotations_function (self, nodes.FunctionDef node, dict[str, bool] all_used_type_annotations) protected
Adds all names used as type annotation in the arguments and return type of
the function node into the dict `all_used_type_annotations`.
Definition at line 173 of file private_import.py.
    ) -> None:
        """Adds all names used as type annotation in the arguments and return type of
        the function node into the dict `all_used_type_annotations`.
        """
        if node.args and node.args.annotations:
            for annotation in node.args.annotations:
                self._populate_type_annotations_annotation(
                    annotation, all_used_type_annotations
                )
        if node.returns:
            self._populate_type_annotations_annotation(
                node.returns, all_used_type_annotations
            )
References _populate_type_annotations_annotation().
Referenced by _populate_type_annotations().
same_root_dir()
bool pylint.extensions.private_import.PrivateImportChecker.same_root_dir (nodes.Import | nodes.ImportFrom node, str import_mod_name) static
Does the node's file's path contain the base name of `import_mod_name`?
Definition at line 249 of file private_import.py.
    ) -> bool:
        """Does the node's file's path contain the base name of `import_mod_name`?"""
        if not import_mod_name:  # from . import ...
            return True
        if node.level:  # from .foo import ..., from ..bar import ...
            return True
        base_import_package = import_mod_name.split(".")[0]
        return base_import_package in Path(node.root().file).parent.parts
Referenced by visit_importfrom().
visit_import()
None pylint.extensions.private_import.PrivateImportChecker.visit_import (self, nodes.Import node)
Definition at line 41 of file private_import.py.
    def visit_import(self, node: nodes.Import) -> None:
        if utils.in_type_checking_block(node):
            return
        names = [name[0] for name in node.names]
        private_names = self._get_private_imports(names)
        private_names = self._get_type_annotation_names(node, private_names)
        if private_names:
            imported_identifier = "modules" if len(private_names) > 1 else "module"
            private_name_string = ", ".join(private_names)
            self.add_message(
                "import-private-name",
                node=node,
                args=(imported_identifier, private_name_string),
                confidence=HIGH,
            )
References _get_private_imports(), _get_type_annotation_names(), and pylint.checkers.base_checker.BaseChecker.add_message().
visit_importfrom()
None pylint.extensions.private_import.PrivateImportChecker.visit_importfrom (self, nodes.ImportFrom node)
Definition at line 58 of file private_import.py.
    def visit_importfrom(self, node: nodes.ImportFrom) -> None:
        if utils.in_type_checking_block(node):
            return
        # Only check imported names if the module is external
        if self.same_root_dir(node, node.modname):
            return
        names = [n[0] for n in node.names]
        # Check the imported objects first. If they are all valid type annotations,
        # the package can be private
        private_names = self._get_type_annotation_names(node, names)
        if not private_names:
            return
        # There are invalid imported objects, so check the name of the package
        private_module_imports = self._get_private_imports([node.modname])
        private_module_imports = self._get_type_annotation_names(
            node, private_module_imports
        )
        if private_module_imports:
            self.add_message(
                "import-private-name",
                node=node,
                args=("module", private_module_imports[0]),
                confidence=HIGH,
            )
            return  # Do not emit messages on the objects if the package is private
        private_names = self._get_private_imports(private_names)
        if private_names:
            imported_identifier = "objects" if len(private_names) > 1 else "object"
            private_name_string = ", ".join(private_names)
            self.add_message(
                "import-private-name",
                node=node,
                args=(imported_identifier, private_name_string),
                confidence=HIGH,
            )
References _get_private_imports(), _get_type_annotation_names(), pylint.checkers.base_checker.BaseChecker.add_message(), and same_root_dir().
Member Data Documentation
all_used_type_annotations
pylint.extensions.private_import.PrivateImportChecker.all_used_type_annotations = {}
Definition at line 37 of file private_import.py.
Referenced by _get_type_annotation_names().
populated_annotations
bool pylint.extensions.private_import.PrivateImportChecker.populated_annotations = False
Definition at line 38 of file private_import.py.
Referenced by _get_type_annotation_names().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pylint/extensions/private_import.py