Read&Watch: django.core.checks.messages.Error Class Reference
django.core.checks.messages.Error Class Reference
Public Member Functions
__init__ (self, *args, **kwargs)
Public Member Functions inherited from django.core.checks.messages.CheckMessage
__init__ (self, level, msg, hint=None, obj=None, id=None)
__eq__ (self, other)
__str__ (self)
__repr__ (self)
is_serious (self, level=ERROR)
is_silenced (self)
Additional Inherited Members
Public Attributes inherited from django.core.checks.messages.CheckMessage
level = level
msg = msg
hint = hint
obj = obj
id = id
Detailed Description
Definition at line 74 of file messages.py.
Constructor & Destructor Documentation
__init__()
django.core.checks.messages.Error.__init__ (self, * args, ** kwargs)
Definition at line 75 of file messages.py.
    def __init__(self, *args, **kwargs):
        super().__init__(ERROR, *args, **kwargs)
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/core/checks/messages.py