Read&Watch: django.db.models.fields.URLField Class Reference
django.db.models.fields.URLField Class Reference
Public Member Functions
__init__ (self, verbose_name=None, name=None, **kwargs)
deconstruct (self)
formfield (self, **kwargs)
Public Member Functions inherited from django.db.models.fields.CharField
__init__ (self, *args, db_collation=None, **kwargs)
description (self)
check (self, **kwargs)
cast_db_type (self, connection)
db_parameters (self, connection)
get_internal_type (self)
to_python (self, value)
get_prep_value (self, value)
slice_expression (self, expression, start, length)
Public Member Functions inherited from django.db.models.fields.Field
__init__ (self, verbose_name=None, name=None, primary_key=False, max_length=None, unique=False, blank=False, null=False, db_index=False, rel=None, default=NOT_PROVIDED, editable=True, serialize=True, unique_for_date=None, unique_for_month=None, unique_for_year=None, choices=None, help_text="", db_column=None, db_tablespace=None, auto_created=False, validators=(), error_messages=None, db_comment=None, db_default=NOT_PROVIDED)
__str__ (self)
__repr__ (self)
get_col (self, alias, output_field=None)
choices (self)
choices (self, value)
cached_col (self)
select_format (self, compiler, sql, params)
clone (self)
__eq__ (self, other)
__lt__ (self, other)
__hash__ (self)
__deepcopy__ (self, memodict)
__copy__ (self)
__reduce__ (self)
get_pk_value_on_save (self, instance)
error_messages (self)
validators (self)
run_validators (self, value)
validate (self, value, model_instance)
clean (self, value, model_instance)
db_type_parameters (self, connection)
db_check (self, connection)
db_type (self, connection)
rel_db_type (self, connection)
db_type_suffix (self, connection)
get_db_converters (self, connection)
unique (self)
db_tablespace (self)
db_returning (self)
set_attributes_from_name (self, name)
contribute_to_class (self, cls, name, private_only=False)
get_filter_kwargs_for_object (self, obj)
get_attname (self)
get_attname_column (self)
pre_save (self, model_instance, add)
get_db_prep_value (self, value, connection, prepared=False)
get_db_prep_save (self, value, connection)
has_default (self)
get_default (self)
get_choices (self, include_blank=True, blank_choice=BLANK_CHOICE_DASH, limit_choices_to=None, ordering=())
value_to_string (self, obj)
flatchoices (self)
save_form_data (self, instance, data)
value_from_object (self, obj)
Public Member Functions inherited from django.db.models.query_utils.RegisterLookupMixin
get_class_lookups (cls)
get_instance_lookups (self)
get_lookup (self, lookup_name)
get_transform (self, lookup_name)
register_class_lookup (cls, lookup, lookup_name=None)
register_instance_lookup (self, lookup, lookup_name=None)
Additional Inherited Members
Static Public Member Functions inherited from django.db.models.query_utils.RegisterLookupMixin
merge_dicts (dicts)
Public Attributes inherited from django.db.models.fields.CharField
db_collation = db_collation
Public Attributes inherited from django.db.models.fields.Field
str name = name
str verbose_name = verbose_name
primary_key = primary_key
max_length
blank
null = blank, null
remote_field = rel
is_relation = self.remote_field is not None
default = default
db_default = db_default
editable = editable
serialize = serialize
unique_for_date = unique_for_date
unique_for_month = unique_for_month
unique_for_year = unique_for_year
choices = choices
help_text = help_text
db_index = db_index
db_column = db_column
db_comment = db_comment
auto_created = auto_created
model = []
validators
error_messages = []
attname = self.name or name
column = self.get_attname_column()
concrete = self.column is not None
Public Attributes inherited from django.db.models.query_utils.RegisterLookupMixin
dict class_lookups = {}
dict instance_lookups = {}
Static Public Attributes inherited from django.db.models.fields.Field
bool empty_strings_allowed = True
empty_values = list(validators.EMPTY_VALUES)
int creation_counter = 0
int auto_creation_counter = -1
list default_validators = []
dict default_error_messages
system_check_deprecated_details = None
system_check_removed_details = None
tuple non_db_attrs
bool hidden = False
many_to_many = None
many_to_one = None
one_to_many = None
one_to_one = None
related_model = None
bool generated = False
descriptor_class = DeferredAttribute
Static Public Attributes inherited from django.db.models.query_utils.RegisterLookupMixin
get_lookups = class_or_instance_method(get_class_lookups, get_instance_lookups)
get_class_lookups = classmethod(get_class_lookups)
register_lookup
register_class_lookup = classmethod(register_class_lookup)
Protected Member Functions inherited from django.db.models.fields.CharField
_check_max_length_attribute (self, **kwargs)
_check_db_collation (self, databases)
Protected Member Functions inherited from django.db.models.fields.Field
_description (self)
_check_field_name (self)
_choices_is_value (cls, value)
_check_choices (self)
_check_db_default (self, databases=None, **kwargs)
_check_db_index (self)
_check_db_comment (self, databases=None, **kwargs)
_check_null_allowed_for_primary_keys (self)
_check_backend_specific_checks (self, databases=None, **kwargs)
_check_validators (self)
_check_deprecation_details (self)
_get_default (self)
_db_default_expression (self)
Protected Member Functions inherited from django.db.models.query_utils.RegisterLookupMixin
_get_lookup (self, lookup_name)
_clear_cached_class_lookups (cls)
_unregister_class_lookup (cls, lookup, lookup_name=None)
_unregister_instance_lookup (self, lookup, lookup_name=None)
Protected Attributes inherited from django.db.models.fields.Field
_verbose_name = verbose_name
_unique = max_length, unique
_db_tablespace = db_tablespace
_validators = list(validators)
_error_messages = error_messages
_db_default_expression = connections[db]
_choices = normalize_choices(value)
_get_FIELD_display
Static Protected Attributes inherited from django.db.models.query_utils.RegisterLookupMixin
_unregister_lookup
_unregister_class_lookup = classmethod(_unregister_class_lookup)
Detailed Description
Definition at line 2635 of file __init__.py.
Constructor & Destructor Documentation
__init__()
django.db.models.fields.URLField.__init__ (self, verbose_name = None, name = None, ** kwargs)
Definition at line 2639 of file __init__.py.
    def __init__(self, verbose_name=None, name=None, **kwargs):
        kwargs.setdefault("max_length", 200)
        super().__init__(verbose_name, name, **kwargs)
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Function Documentation
deconstruct()
django.db.models.fields.URLField.deconstruct (self)
Return enough information to recreate the field as a 4-tuple:
 * The name of the field on the model, if contribute_to_class() has
   been run.
 * The import path of the field, including the class, e.g.
   django.db.models.IntegerField. This should be the most portable
   version, so less specific may be better.
 * A list of positional arguments.
 * A dict of keyword arguments.
Note that the positional or keyword arguments must contain values of
the following types (including inner values of collection types):
 * None, bool, str, int, float, complex, set, frozenset, list, tuple,
   dict
 * UUID
 * datetime.datetime (naive), datetime.date
 * top-level classes, top-level functions - will be referenced by their
   full import path
 * Storage instances - these have their own deconstruct() method
This is because the values here must be serialized into a text format
(possibly new Python code, possibly JSON) and these are the only types
with encoding handlers defined.
There's no need to return the exact way the field was instantiated this
time, just ensure that the resulting field is the same - prefer keyword
arguments over positional ones, and omit parameters with their default
values.
Reimplemented from django.db.models.fields.CharField.
Definition at line 2643 of file __init__.py.
    def deconstruct(self):
        name, path, args, kwargs = super().deconstruct()
        if kwargs.get("max_length") == 200:
            del kwargs["max_length"]
        return name, path, args, kwargs
References deconstruct().
Referenced by django.db.models.indexes.Index.__eq__(), django.db.models.indexes.Index.clone(), deconstruct(), and django.db.models.query_utils.Q.identity().
formfield()
django.db.models.fields.URLField.formfield (self, ** form_class)
Return a django.forms.Field instance for this field.
Reimplemented from django.db.models.fields.CharField.
Definition at line 2649 of file __init__.py.
    def formfield(self, **kwargs):
        # As with CharField, this will cause URL validation to be performed
        # twice.
        return super().formfield(
            **{
                "form_class": forms.URLField,
                **kwargs,
            }
        )
References formfield().
Referenced by formfield().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/db/models/fields/__init__.py