Read&Watch: django.core.serializers.json.DjangoJSONEncoder Class Reference
django.core.serializers.json.DjangoJSONEncoder Class Reference
Public Member Functions
default (self, o)
Detailed Description
JSONEncoder subclass that knows how to encode date/time, decimal types, and
UUIDs.
Definition at line 77 of file json.py.
Member Function Documentation
default()
django.core.serializers.json.DjangoJSONEncoder.default (self, o)
Definition at line 83 of file json.py.
    def default(self, o):
        # See "Date Time String Format" in the ECMA-262 specification.
        if isinstance(o, datetime.datetime):
            r = o.isoformat()
            if o.microsecond:
                r = r[:23] + r[26:]
            if r.endswith("+00:00"):
                r = r.removesuffix("+00:00") + "Z"
            return r
        elif isinstance(o, datetime.date):
            return o.isoformat()
        elif isinstance(o, datetime.time):
            if is_aware(o):
                raise ValueError("JSON can't represent timezone-aware times.")
            r = o.isoformat()
            if o.microsecond:
                r = r[:12]
            return r
        elif isinstance(o, datetime.timedelta):
            return duration_iso_string(o)
        elif isinstance(o, (decimal.Decimal, uuid.UUID, Promise)):
            return str(o)
        else:
            return super().default(o)
References default().
Referenced by default(), and mccabe.ASTVisitor.dispatch().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/core/serializers/json.py