Read&Watch: django.core.management.ManagementUtility Class Reference
django.core.management.ManagementUtility Class Reference
Public Member Functions
__init__ (self, argv=None)
main_help_text (self, commands_only=False)
fetch_command (self, subcommand)
autocomplete (self)
execute (self)
Public Attributes
argv = argv or sys.argv[:]
str prog_name = os.path.basename(self.argv[0])
settings_exception = None
Detailed Description
Encapsulate the logic of the django-admin and manage.py utilities.
Definition at line 197 of file __init__.py.
Constructor & Destructor Documentation
__init__()
django.core.management.ManagementUtility.__init__ (self, argv = None)
Definition at line 202 of file __init__.py.
    def __init__(self, argv=None):
        self.argv = argv or sys.argv[:]
        self.prog_name = os.path.basename(self.argv[0])
        if self.prog_name == "__main__.py":
            self.prog_name = "python -m django"
        self.settings_exception = None
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
autocomplete()
django.core.management.ManagementUtility.autocomplete (self)
Output completion suggestions for BASH.
The output of this function is passed to BASH's `COMPREPLY` variable
and treated as completion suggestions. `COMPREPLY` expects a space
separated string as the result.
The `COMP_WORDS` and `COMP_CWORD` BASH environment variables are used
to get information about the cli input. Please refer to the BASH
man-page for more information about this variables.
Subcommand options are saved as pairs. A pair consists of
the long option string (e.g. '--exclude') and a boolean
value indicating if the option requires arguments. When printing to
stdout, an equal sign is appended to options which require arguments.
Note: If debugging this function, it is recommended to write the debug
output in a separate file. Otherwise the debug output will be treated
and formatted as potential completion suggestions.
Definition at line 278 of file __init__.py.
    def autocomplete(self):
        """
        Output completion suggestions for BASH.
        The output of this function is passed to BASH's `COMPREPLY` variable
        and treated as completion suggestions. `COMPREPLY` expects a space
        separated string as the result.
        The `COMP_WORDS` and `COMP_CWORD` BASH environment variables are used
        to get information about the cli input. Please refer to the BASH
        man-page for more information about this variables.
        Subcommand options are saved as pairs. A pair consists of
        the long option string (e.g. '--exclude') and a boolean
        value indicating if the option requires arguments. When printing to
        stdout, an equal sign is appended to options which require arguments.
        Note: If debugging this function, it is recommended to write the debug
        output in a separate file. Otherwise the debug output will be treated
        and formatted as potential completion suggestions.
        """
        # Don't complete if user hasn't sourced bash_completion file.
        if "DJANGO_AUTO_COMPLETE" not in os.environ:
            return
        cwords = os.environ["COMP_WORDS"].split()[1:]
        cword = int(os.environ["COMP_CWORD"])
        try:
            curr = cwords[cword - 1]
        except IndexError:
            curr = ""
        subcommands = [*get_commands(), "help"]
        options = [("--help", False)]
        # subcommand
        if cword == 1:
            print(" ".join(sorted(filter(lambda x: x.startswith(curr), subcommands))))
        # subcommand options
        # special case: the 'help' subcommand has no options
        elif cwords[0] in subcommands and cwords[0] != "help":
            subcommand_cls = self.fetch_command(cwords[0])
            # special case: add the names of installed apps to options
            if cwords[0] in ("dumpdata", "sqlmigrate", "sqlsequencereset", "test"):
                try:
                    app_configs = apps.get_app_configs()
                    # Get the last part of the dotted path as the app name.
                    options.extend((app_config.label, 0) for app_config in app_configs)
                except ImportError:
                    # Fail silently if DJANGO_SETTINGS_MODULE isn't set. The
                    # user will find out once they execute the command.
                    pass
            parser = subcommand_cls.create_parser("", cwords[0])
            options.extend(
                (min(s_opt.option_strings), s_opt.nargs != 0)
                for s_opt in parser._actions
                if s_opt.option_strings
            )
            # filter out previously specified options from available options
            prev_opts = {x.split("=")[0] for x in cwords[1 : cword - 1]}
            options = (opt for opt in options if opt[0] not in prev_opts)
            # filter options by current input
            options = sorted((k, v) for k, v in options if k.startswith(curr))
            for opt_label, require_arg in options:
                # append '=' to options which require args
                if require_arg:
                    opt_label += "="
                print(opt_label)
        # Exit code of the bash completion function is never passed back to
        # the user, so it's safe to always exit with 0.
        # For more details see #25420.
        sys.exit(0)
References fetch_command(), and django.core.management.get_commands().
Referenced by execute().
execute()
django.core.management.ManagementUtility.execute (self)
Given the command-line arguments, figure out which subcommand is being
run, create a parser appropriate to that command, and run it.
Definition at line 353 of file __init__.py.
    def execute(self):
        """
        Given the command-line arguments, figure out which subcommand is being
        run, create a parser appropriate to that command, and run it.
        """
        try:
            subcommand = self.argv[1]
        except IndexError:
            subcommand = "help"  # Display help if no arguments were given.
        # Preprocess options to extract --settings and --pythonpath.
        # These options could affect the commands that are available, so they
        # must be processed early.
        parser = CommandParser(
            prog=self.prog_name,
            usage="%(prog)s subcommand [options] [args]",
            add_help=False,
            allow_abbrev=False,
        )
        parser.add_argument("--settings")
        parser.add_argument("--pythonpath")
        parser.add_argument("args", nargs="*")  # catch-all
        try:
            options, args = parser.parse_known_args(self.argv[2:])
            handle_default_options(options)
        except CommandError:
            pass  # Ignore any option errors at this point.
        try:
            settings.INSTALLED_APPS
        except ImproperlyConfigured as exc:
            self.settings_exception = exc
        except ImportError as exc:
            self.settings_exception = exc
        if settings.configured:
            # Start the auto-reloading dev server even if the code is broken.
            # The hardcoded condition is a code smell but we can't rely on a
            # flag on the command class because we haven't located it yet.
            if subcommand == "runserver" and "--noreload" not in self.argv:
                try:
                    autoreload.check_errors(django.setup)()
                except Exception:
                    # The exception will be raised later in the child process
                    # started by the autoreloader. Pretend it didn't happen by
                    # loading an empty list of applications.
                    apps.all_models = defaultdict(dict)
                    apps.app_configs = {}
                    apps.apps_ready = apps.models_ready = apps.ready = True
                    # Remove options not compatible with the built-in runserver
                    # (e.g. options for the contrib.staticfiles' runserver).
                    # Changes here require manually testing as described in
                    # #27522.
                    _parser = self.fetch_command("runserver").create_parser(
                        "django", "runserver"
                    )
                    _options, _args = _parser.parse_known_args(self.argv[2:])
                    for _arg in _args:
                        self.argv.remove(_arg)
            # In all other cases, django.setup() is required to succeed.
            else:
                django.setup()
        self.autocomplete()
        if subcommand == "help":
            if "--commands" in args:
                sys.stdout.write(self.main_help_text(commands_only=True) + "\n")
            elif not options.args:
                sys.stdout.write(self.main_help_text() + "\n")
            else:
                self.fetch_command(options.args[0]).print_help(
                    self.prog_name, options.args[0]
                )
        # Special-cases: We want 'django-admin --version' and
        # 'django-admin --help' to work, for backwards compatibility.
        elif subcommand == "version" or self.argv[1:] == ["--version"]:
            sys.stdout.write(django.get_version() + "\n")
        elif self.argv[1:] in (["--help"], ["-h"]):
            sys.stdout.write(self.main_help_text() + "\n")
        else:
            self.fetch_command(subcommand).run_from_argv(self.argv)
References argv, autocomplete(), fetch_command(), main_help_text(), prog_name, settings_exception, and django.setup().
Referenced by django.db.backends.base.schema.BaseDatabaseSchemaEditor.__exit__(), django.db.backends.postgresql.schema.DatabaseSchemaEditor._alter_column_type_sql(), django.db.backends.base.schema.BaseDatabaseSchemaEditor._alter_field(), django.db.backends.postgresql.schema.DatabaseSchemaEditor._alter_field(), django.db.backends.sqlite3.schema.DatabaseSchemaEditor._alter_field(), django.db.backends.oracle.schema.DatabaseSchemaEditor._alter_field_type_workaround(), django.db.backends.sqlite3.schema.DatabaseSchemaEditor._alter_many_to_many(), django.db.backends.mysql.schema.DatabaseSchemaEditor._create_missing_fk_index(), django.db.backends.base.schema.BaseDatabaseSchemaEditor._delete_composed_index(), django.db.backends.base.schema.BaseDatabaseSchemaEditor._delete_primary_key(), django.db.backends.oracle.schema.DatabaseSchemaEditor._drop_identity(), django.db.backends.sqlite3.schema.DatabaseSchemaEditor._remake_table(), django.db.backends.base.schema.BaseDatabaseSchemaEditor.add_constraint(), django.contrib.gis.db.backends.spatialite.schema.SpatialiteSchemaEditor.add_field(), django.db.backends.base.schema.BaseDatabaseSchemaEditor.add_field(), django.db.backends.mysql.schema.DatabaseSchemaEditor.add_field(), django.db.backends.base.schema.BaseDatabaseSchemaEditor.add_index(), django.db.backends.postgresql.schema.DatabaseSchemaEditor.add_index(), django.contrib.gis.db.backends.spatialite.schema.SpatialiteSchemaEditor.alter_db_table(), django.db.backends.base.schema.BaseDatabaseSchemaEditor.alter_db_table(), django.db.backends.base.schema.BaseDatabaseSchemaEditor.alter_db_table_comment(), django.db.backends.base.schema.BaseDatabaseSchemaEditor.alter_db_tablespace(), django.db.backends.oracle.schema.DatabaseSchemaEditor.alter_field(), django.db.backends.base.schema.BaseDatabaseSchemaEditor.alter_index_together(), django.db.backends.base.schema.BaseDatabaseSchemaEditor.alter_unique_together(), django.db.backends.postgresql.base.CursorMixin.callproc(), django.contrib.gis.db.backends.spatialite.schema.SpatialiteSchemaEditor.create_model(), django.db.backends.base.schema.BaseDatabaseSchemaEditor.create_model(), django.contrib.gis.db.backends.mysql.schema.MySQLGISSchemaEditor.create_spatial_indexes(), django.contrib.gis.db.backends.oracle.schema.OracleGISSchemaEditor.delete_model(), django.contrib.gis.db.backends.spatialite.schema.SpatialiteSchemaEditor.delete_model(), django.db.backends.base.schema.BaseDatabaseSchemaEditor.delete_model(), django.db.backends.oracle.schema.DatabaseSchemaEditor.delete_model(), django.db.backends.sqlite3.schema.DatabaseSchemaEditor.delete_model(), django.db.backends.base.schema.BaseDatabaseSchemaEditor.remove_constraint(), django.contrib.gis.db.backends.mysql.schema.MySQLGISSchemaEditor.remove_field(), django.contrib.gis.db.backends.oracle.schema.OracleGISSchemaEditor.remove_field(), django.db.backends.base.schema.BaseDatabaseSchemaEditor.remove_field(), django.contrib.gis.db.backends.spatialite.schema.SpatialiteSchemaEditor.remove_geometry_metadata(), django.db.backends.base.schema.BaseDatabaseSchemaEditor.remove_index(), django.db.backends.postgresql.schema.DatabaseSchemaEditor.remove_index(), django.db.backends.base.schema.BaseDatabaseSchemaEditor.remove_procedure(), django.db.backends.base.schema.BaseDatabaseSchemaEditor.rename_index(), django.core.management.base.BaseCommand.run_from_argv(), and django.contrib.gis.db.backends.oracle.schema.OracleGISSchemaEditor.run_geometry_sql().
fetch_command()
django.core.management.ManagementUtility.fetch_command (self, subcommand)
Try to fetch the given subcommand, printing a message with the
appropriate command called from the command line (usually
"django-admin" or "manage.py") if it can't be found.
Definition at line 246 of file __init__.py.
    def fetch_command(self, subcommand):
        """
        Try to fetch the given subcommand, printing a message with the
        appropriate command called from the command line (usually
        "django-admin" or "manage.py") if it can't be found.
        """
        # Get commands outside of try block to prevent swallowing exceptions
        commands = get_commands()
        try:
            app_name = commands[subcommand]
        except KeyError:
            if os.environ.get("DJANGO_SETTINGS_MODULE"):
                # If `subcommand` is missing due to misconfigured settings, the
                # following line will retrigger an ImproperlyConfigured exception
                # (get_commands() swallows the original one) so the user is
                # informed about it.
                settings.INSTALLED_APPS
            elif not settings.configured:
                sys.stderr.write("No Django settings specified.\n")
            possible_matches = get_close_matches(subcommand, commands)
            sys.stderr.write("Unknown command: %r" % subcommand)
            if possible_matches:
                sys.stderr.write(". Did you mean %s?" % possible_matches[0])
            sys.stderr.write("\nType '%s help' for usage.\n" % self.prog_name)
            sys.exit(1)
        if isinstance(app_name, BaseCommand):
            # If the command is already loaded, use it directly.
            klass = app_name
        else:
            klass = load_command_class(app_name, subcommand)
        return klass
References django.core.management.get_commands(), django.core.management.load_command_class(), and prog_name.
Referenced by autocomplete(), and execute().
main_help_text()
django.core.management.ManagementUtility.main_help_text (self, commands_only = False)
Return the script's main help text, as a string.
Definition at line 209 of file __init__.py.
    def main_help_text(self, commands_only=False):
        """Return the script's main help text, as a string."""
        if commands_only:
            usage = sorted(get_commands())
        else:
            usage = [
                "",
                "Type '%s help <subcommand>' for help on a specific subcommand."
                % self.prog_name,
                "",
                "Available subcommands:",
            ]
            commands_dict = defaultdict(lambda: [])
            for name, app in get_commands().items():
                if app == "django.core":
                    app = "django"
                else:
                    app = app.rpartition(".")[-1]
                commands_dict[app].append(name)
            style = color_style()
            for app in sorted(commands_dict):
                usage.append("")
                usage.append(style.NOTICE("[%s]" % app))
                for name in sorted(commands_dict[app]):
                    usage.append("    %s" % name)
            # Output an extra note if settings are not properly configured
            if self.settings_exception is not None:
                usage.append(
                    style.NOTICE(
                        "Note that only Django core commands are listed "
                        "as settings are not properly configured (error: %s)."
                        % self.settings_exception
                    )
                )
        return "\n".join(usage)
References django.core.management.get_commands(), prog_name, and settings_exception.
Referenced by execute().
Member Data Documentation
argv
django.core.management.ManagementUtility.argv = argv or sys.argv[:]
Definition at line 203 of file __init__.py.
Referenced by execute().
prog_name
django.core.management.ManagementUtility.prog_name = os.path.basename(self.argv[0])
Definition at line 204 of file __init__.py.
Referenced by execute(), fetch_command(), and main_help_text().
settings_exception
django.core.management.ManagementUtility.settings_exception = None
Definition at line 207 of file __init__.py.
Referenced by execute(), and main_help_text().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/core/management/__init__.py