Read&Watch: django.core.files.storage.memory.InMemoryDirNode Class Reference
django.core.files.storage.memory.InMemoryDirNode Class Reference
Public Member Functions
__init__ (self)
resolve (self, path, create_if_missing=False, leaf_cls=None, check_exists=True)
listdir (self)
remove_child (self, name)
Protected Member Functions
_resolve_child (self, path_segment, create_if_missing, child_cls)
Protected Member Functions inherited from django.core.files.storage.memory.TimingMixin
_initialize_times (self)
_update_accessed_time (self)
_update_modified_time (self)
Protected Attributes
dict _children = {}
Additional Inherited Members
Public Attributes inherited from django.core.files.storage.memory.TimingMixin
created_time = now()
accessed_time = self.created_time
modified_time = self.created_time
Detailed Description
Helper class representing an in-memory directory node.
Handle path navigation of directory trees, creating missing nodes if
needed.
Definition at line 82 of file memory.py.
Constructor & Destructor Documentation
__init__()
django.core.files.storage.memory.InMemoryDirNode.__init__ (self)
Definition at line 90 of file memory.py.
    def __init__(self):
        self._children = {}
        self._initialize_times()
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
_resolve_child()
django.core.files.storage.memory.InMemoryDirNode._resolve_child (self, path_segment, create_if_missing, child_cls) protected
Definition at line 141 of file memory.py.
    def _resolve_child(self, path_segment, create_if_missing, child_cls):
        if create_if_missing:
            self._update_accessed_time()
            self._update_modified_time()
            return self._children.setdefault(path_segment, child_cls())
        return self._children.get(path_segment)
References _children, django.core.files.storage.memory.TimingMixin._update_accessed_time(), and django.core.files.storage.memory.TimingMixin._update_modified_time().
listdir()
django.core.files.storage.memory.InMemoryDirNode.listdir (self)
Definition at line 148 of file memory.py.
    def listdir(self):
        directories, files = [], []
        for name, entry in self._children.items():
            if isinstance(entry, InMemoryDirNode):
                directories.append(name)
            else:
                files.append(name)
        return directories, files
References _children.
remove_child()
django.core.files.storage.memory.InMemoryDirNode.remove_child (self, name)
Definition at line 157 of file memory.py.
    def remove_child(self, name):
        if name in self._children:
            self._update_accessed_time()
            self._update_modified_time()
            del self._children[name]
@deconstructible(path="django.core.files.storage.InMemoryStorage")
References _children, django.core.files.storage.memory.TimingMixin._update_accessed_time(), and django.core.files.storage.memory.TimingMixin._update_modified_time().
resolve()
django.core.files.storage.memory.InMemoryDirNode.resolve (self, path, create_if_missing = False, leaf_cls = None, check_exists = True)
Navigate current directory tree, returning node matching path or
creating a new one, if missing.
- path: path of the node to search
- create_if_missing: create nodes if not exist. Defaults to False.
- leaf_cls: expected type of leaf node. Defaults to None.
- check_exists: if True and the leaf node does not exist, raise a
  FileNotFoundError. Defaults to True.
Definition at line 94 of file memory.py.
    def resolve(self, path, create_if_missing=False, leaf_cls=None, check_exists=True):
        """
        Navigate current directory tree, returning node matching path or
        creating a new one, if missing.
        - path: path of the node to search
        - create_if_missing: create nodes if not exist. Defaults to False.
        - leaf_cls: expected type of leaf node. Defaults to None.
        - check_exists: if True and the leaf node does not exist, raise a
          FileNotFoundError. Defaults to True.
        """
        path_segments = list(pathlib.Path(path).parts)
        current_node = self
        while path_segments:
            path_segment = path_segments.pop(0)
            # If current node is a file node and there are unprocessed
            # segments, raise an error.
            if isinstance(current_node, InMemoryFileNode):
                path_segments = os.path.split(path)
                current_path = "/".join(
                    path_segments[: path_segments.index(path_segment)]
                )
                raise NotADirectoryError(
                    errno.ENOTDIR, os.strerror(errno.ENOTDIR), current_path
                )
            current_node = current_node._resolve_child(
                path_segment,
                create_if_missing,
                leaf_cls if len(path_segments) == 0 else InMemoryDirNode,
            )
            if current_node is None:
                break
        if current_node is None and check_exists:
            raise FileNotFoundError(errno.ENOENT, os.strerror(errno.ENOENT), path)
        # If a leaf_cls is not None, check if leaf node is of right type.
        if leaf_cls and not isinstance(current_node, leaf_cls):
            error_cls, error_code = (
                (NotADirectoryError, errno.ENOTDIR)
                if leaf_cls is InMemoryDirNode
                else (IsADirectoryError, errno.EISDIR)
            )
            raise error_cls(error_code, os.strerror(error_code), path)
        return current_node
Referenced by yaml.composer.Composer.compose_mapping_node(), yaml.composer.Composer.compose_scalar_node(), yaml.composer.Composer.compose_sequence_node(), pip._vendor.distlib.compat.BaseConfigurator.configure_custom(), pip._vendor.distlib.compat.BaseConfigurator.ext_convert(), and yaml.serializer.Serializer.serialize_node().
Member Data Documentation
_children
dict django.core.files.storage.memory.InMemoryDirNode._children = {} protected
Definition at line 91 of file memory.py.
Referenced by _resolve_child(), pip._vendor.rich.layout.Layout.add_split(), pip._vendor.rich.layout.Layout.children(), pip._vendor.rich.layout.Layout.get(), listdir(), remove_child(), pip._vendor.rich.layout.Layout.renderable(), pip._vendor.rich.layout.Layout.split(), and pip._vendor.rich.layout.Layout.unsplit().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/core/files/storage/memory.py