Read&Watch: django.db.models.signals.ModelSignal Class Reference
django.db.models.signals.ModelSignal Class Reference
Public Member Functions
connect (self, receiver, sender=None, weak=True, dispatch_uid=None, apps=None)
disconnect (self, receiver=None, sender=None, dispatch_uid=None, apps=None)
Public Member Functions inherited from django.dispatch.dispatcher.Signal
__init__ (self, use_caching=False)
has_listeners (self, sender=None)
send (self, sender, **named)
asend (self, sender, **named)
send_robust (self, sender, **named)
asend_robust (self, sender, **named)
Protected Member Functions
_lazy_method (self, method, apps, receiver, sender, **kwargs)
Protected Member Functions inherited from django.dispatch.dispatcher.Signal
_log_robust_failure (self, receiver, err)
_clear_dead_receivers (self)
_live_receivers (self, sender)
_remove_receiver (self, receiver=None)
Additional Inherited Members
Public Attributes inherited from django.dispatch.dispatcher.Signal
list receivers = []
lock = threading.Lock()
use_caching = use_caching
sender_receivers_cache = weakref.WeakKeyDictionary() if use_caching else {}
Protected Attributes inherited from django.dispatch.dispatcher.Signal
bool _dead_receivers = False
_remove_receiver
Detailed Description
Signal subclass that allows the sender to be lazily specified as a string
of the `app_label.ModelName` form.
Definition at line 9 of file signals.py.
Member Function Documentation
_lazy_method()
django.db.models.signals.ModelSignal._lazy_method (self, method, apps, receiver, sender, ** kwargs) protected
Definition at line 15 of file signals.py.
    def _lazy_method(self, method, apps, receiver, sender, **kwargs):
        from django.db.models.options import Options
        # This partial takes a single optional argument named "sender".
        partial_method = partial(method, receiver, **kwargs)
        if isinstance(sender, str):
            apps = apps or Options.default_apps
            apps.lazy_model_operation(partial_method, make_model_tuple(sender))
        else:
            return partial_method(sender)
Referenced by connect(), and disconnect().
connect()
django.db.models.signals.ModelSignal.connect (self, receiver, sender = None, weak = True, dispatch_uid = None, apps = None)
Connect receiver to sender for signal.
Arguments:
    receiver
        A function or an instance method which is to receive signals.
        Receivers must be hashable objects. Receivers can be
        asynchronous.
        If weak is True, then receiver must be weak referenceable.
        Receivers must be able to accept keyword arguments.
        If a receiver is connected with a dispatch_uid argument, it
        will not be added if another receiver was already connected
        with that dispatch_uid.
    sender
        The sender to which the receiver should respond. Must either be
        a Python object, or None to receive events from any sender.
    weak
        Whether to use weak references to the receiver. By default, the
        module will attempt to use weak references to the receiver
        objects. If this parameter is false, then strong references will
        be used.
    dispatch_uid
        An identifier used to uniquely identify a particular instance of
        a receiver. This will usually be a string, though it may be
        anything hashable.
Reimplemented from django.dispatch.dispatcher.Signal.
Definition at line 26 of file signals.py.
    def connect(self, receiver, sender=None, weak=True, dispatch_uid=None, apps=None):
        self._lazy_method(
            super().connect,
            apps,
            receiver,
            sender,
            weak=weak,
            dispatch_uid=dispatch_uid,
        )
References _lazy_method().
disconnect()
django.db.models.signals.ModelSignal.disconnect (self, receiver = None, sender = None, dispatch_uid = None, apps = None)
Disconnect receiver from sender for signal.
If weak references are used, disconnect need not be called. The receiver
will be removed from dispatch automatically.
Arguments:
    receiver
        The registered receiver to disconnect. May be none if
        dispatch_uid is specified.
    sender
        The registered sender to disconnect
    dispatch_uid
        the unique identifier of the receiver to disconnect
Reimplemented from django.dispatch.dispatcher.Signal.
Definition at line 36 of file signals.py.
    def disconnect(self, receiver=None, sender=None, dispatch_uid=None, apps=None):
        return self._lazy_method(
            super().disconnect, apps, receiver, sender, dispatch_uid=dispatch_uid
        )
References _lazy_method().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/db/models/signals.py