Read&Watch: pip._vendor.rich.progress.TaskProgressColumn Class Reference
pip._vendor.rich.progress.TaskProgressColumn Class Reference
Public Member Functions
None __init__ (self, str text_format="[progress.percentage]{task.percentage:>3.0f}%", str text_format_no_percentage="", StyleType style="none", JustifyMethod justify="left", bool markup=True, Optional[Highlighter] highlighter=None, Optional[Column] table_column=None, bool show_speed=False)
Text render_speed (cls, Optional[float] speed)
Text render (self, "Task" task)
Public Member Functions inherited from pip._vendor.rich.progress.TextColumn
None __init__ (self, str text_format, StyleType style="none", JustifyMethod justify="left", bool markup=True, Optional[Highlighter] highlighter=None, Optional[Column] table_column=None)
Public Member Functions inherited from pip._vendor.rich.progress.ProgressColumn
None __init__ (self, Optional[Column] table_column=None)
Column get_table_column (self)
RenderableType __call__ (self, "Task" task)
Public Attributes
text_format_no_percentage = text_format_no_percentage
show_speed = show_speed
Public Attributes inherited from pip._vendor.rich.progress.TextColumn
text_format = text_format
JustifyMethod justify = justify
style = style
markup = markup
highlighter = highlighter
Additional Inherited Members
Static Public Attributes inherited from pip._vendor.rich.progress.ProgressColumn
Optional max_refresh = None
Protected Attributes inherited from pip._vendor.rich.progress.ProgressColumn
_table_column = table_column
dict _renderable_cache = {}
Optional[float] _update_time = None
Detailed Description
Show task progress as a percentage.
Args:
    text_format (str, optional): Format for percentage display. Defaults to "[progress.percentage]{task.percentage:>3.0f}%".
    text_format_no_percentage (str, optional): Format if percentage is unknown. Defaults to "".
    style (StyleType, optional): Style of output. Defaults to "none".
    justify (JustifyMethod, optional): Text justification. Defaults to "left".
    markup (bool, optional): Enable markup. Defaults to True.
    highlighter (Optional[Highlighter], optional): Highlighter to apply to output. Defaults to None.
    table_column (Optional[Column], optional): Table Column to use. Defaults to None.
    show_speed (bool, optional): Show speed if total is unknown. Defaults to False.
Definition at line 688 of file progress.py.
Constructor & Destructor Documentation
__init__()
None pip._vendor.rich.progress.TaskProgressColumn.__init__ (self, str text_format = "[progress.percentage]{task.percentage:>3.0f}%", str text_format_no_percentage = "", StyleType style = "none", JustifyMethod justify = "left", bool markup = True, Optional[Highlighter] highlighter = None, Optional[Column] table_column = None, bool show_speed = False)
Definition at line 702 of file progress.py.
    ) -> None:
        self.text_format_no_percentage = text_format_no_percentage
        self.show_speed = show_speed
        super().__init__(
            text_format=text_format,
            style=style,
            justify=justify,
            markup=markup,
            highlighter=highlighter,
            table_column=table_column,
        )
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
render()
Text pip._vendor.rich.progress.TaskProgressColumn.render (self, "Task" task)
Should return a renderable object.
Reimplemented from pip._vendor.rich.progress.TextColumn.
Definition at line 744 of file progress.py.
    def render(self, task: "Task") -> Text:
        if task.total is None and self.show_speed:
            return self.render_speed(task.finished_speed or task.speed)
        text_format = (
            self.text_format_no_percentage if task.total is None else self.text_format
        )
        _text = text_format.format(task=task)
        if self.markup:
            text = Text.from_markup(_text, style=self.style, justify=self.justify)
        else:
            text = Text(_text, style=self.style, justify=self.justify)
        if self.highlighter:
            self.highlighter.highlight(text)
        return text
References render_speed(), show_speed, pip._vendor.rich.progress.TextColumn.text_format, and text_format_no_percentage.
Referenced by pip._vendor.rich.spinner.Spinner.__rich_console__(), and pip._vendor.rich.spinner.Spinner.__rich_measure__().
render_speed()
Text pip._vendor.rich.progress.TaskProgressColumn.render_speed (cls, Optional[float] speed)
Render the speed in iterations per second.
Args:
    task (Task): A Task object.
Returns:
    Text: Text object containing the task speed.
Definition at line 725 of file progress.py.
    def render_speed(cls, speed: Optional[float]) -> Text:
        """Render the speed in iterations per second.
        Args:
            task (Task): A Task object.
        Returns:
            Text: Text object containing the task speed.
        """
        if speed is None:
            return Text("", style="progress.percentage")
        unit, suffix = filesize.pick_unit_and_suffix(
            int(speed),
            ["", "×10³", "×10⁶", "×10⁹", "×10¹²"],
            1000,
        )
        data_speed = speed / unit
        return Text(f"{data_speed:.1f}{suffix} it/s", style="progress.percentage")
Referenced by render().
Member Data Documentation
show_speed
pip._vendor.rich.progress.TaskProgressColumn.show_speed = show_speed
Definition at line 714 of file progress.py.
Referenced by render().
text_format_no_percentage
pip._vendor.rich.progress.TaskProgressColumn.text_format_no_percentage = text_format_no_percentage
Definition at line 713 of file progress.py.
Referenced by render().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/rich/progress.py