Read&Watch: django.contrib.auth.models.Permission.Meta Class Reference
django.contrib.auth.models.Permission.Meta Class Reference
Static Public Attributes
verbose_name = _("permission")
verbose_name_plural = _("permissions")
list unique_together = [["content_type", "codename"]]
list ordering = ["content_type__app_label", "content_type__model", "codename"]
Detailed Description
Definition at line 73 of file models.py.
Member Data Documentation
ordering
list django.contrib.auth.models.Permission.Meta.ordering = ["content_type__app_label", "content_type__model", "codename"] static
Definition at line 77 of file models.py.
Referenced by django.db.models.options.Options._prepare(), django.views.generic.dates.BaseDateListView.get_ordering(), and django.views.generic.list.MultipleObjectMixin.get_ordering().
unique_together
list django.contrib.auth.models.Permission.Meta.unique_together = [["content_type", "codename"]] static
Definition at line 76 of file models.py.
verbose_name
django.contrib.auth.models.Permission.Meta.verbose_name = _("permission") static
Definition at line 74 of file models.py.
Referenced by django.db.models.fields.Field.formfield(), django.db.models.fields.related.RelatedField.set_attributes_from_rel(), and django.db.models.options.Options.verbose_name_raw().
verbose_name_plural
django.contrib.auth.models.Permission.Meta.verbose_name_plural = _("permissions") static
Definition at line 75 of file models.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/auth/models.py