Read&Watch: pip._vendor.distlib.util.ServerProxy Class Reference
pip._vendor.distlib.util.ServerProxy Class Reference
Public Member Functions
__init__ (self, uri, **kwargs)
Public Attributes
timeout = kwargs.pop('timeout', None)
transport = t
Detailed Description
Definition at line 1576 of file util.py.
Constructor & Destructor Documentation
__init__()
pip._vendor.distlib.util.ServerProxy.__init__ (self, uri, ** kwargs)
Definition at line 1578 of file util.py.
    def __init__(self, uri, **kwargs):
        self.timeout = timeout = kwargs.pop('timeout', None)
        # The above classes only come into play if a timeout
        # is specified
        if timeout is not None:
            # scheme = splittype(uri)  # deprecated as of Python 3.8
            scheme = urlparse(uri)[0]
            use_datetime = kwargs.get('use_datetime', 0)
            if scheme == 'https':
                tcls = SafeTransport
            else:
                tcls = Transport
            kwargs['transport'] = t = tcls(timeout, use_datetime=use_datetime)
            self.transport = t
        xmlrpclib.ServerProxy.__init__(self, uri, **kwargs)
#
# CSV functionality. This is provided because on 2.x, the csv module can't
# handle Unicode. However, we need to deal with Unicode in e.g. RECORD files.
#
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Data Documentation
timeout
pip._vendor.distlib.util.ServerProxy.timeout = kwargs.pop('timeout', None)
Definition at line 1579 of file util.py.
Referenced by urllib3.connectionpool.HTTPConnectionPool._get_timeout(), pip._vendor.urllib3.connection.HTTPConnection._new_conn(), urllib3.connection.HTTPConnection._new_conn(), urllib3.connection.HTTPConnection.getresponse(), urllib3.contrib.emscripten.fetch._ReadStream.readinto(), and pip._vendor.urllib3.connection.HTTPConnection.request().
transport
pip._vendor.distlib.util.ServerProxy.transport = t
Definition at line 1591 of file util.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/distlib/util.py