Read&Watch: pylint.extensions._check_docs_utils.Docstring Class Reference
pylint.extensions._check_docs_utils.Docstring Class Reference
Public Member Functions
None __init__ (self, nodes.Const|None doc)
str __repr__ (self)
int matching_sections (self)
set[str] exceptions (self)
bool has_params (self)
bool has_returns (self)
bool has_rtype (self)
bool has_property_returns (self)
bool has_property_type (self)
bool has_yields (self)
bool has_yields_type (self)
tuple[set[str], set[str]] match_param_docs (self)
bool params_documented_elsewhere (self)
Public Attributes
doc = docstring.expandtabs()
Static Public Attributes
re_for_parameters_see
bool supports_yields = False
Detailed Description
Definition at line 282 of file _check_docs_utils.py.
Constructor & Destructor Documentation
__init__()
None pylint.extensions._check_docs_utils.Docstring.__init__ (self, nodes.Const | None doc)
Definition at line 297 of file _check_docs_utils.py.
    def __init__(self, doc: nodes.Const | None) -> None:
        docstring: str = doc.value if doc else ""
        self.doc = docstring.expandtabs()
Member Function Documentation
__repr__()
str pylint.extensions._check_docs_utils.Docstring.__repr__ (self)
Definition at line 301 of file _check_docs_utils.py.
    def __repr__(self) -> str:
        return f"<{self.__class__.__name__}:'''{self.doc}'''>"
exceptions()
set[str] pylint.extensions._check_docs_utils.Docstring.exceptions (self)
Reimplemented in pylint.extensions._check_docs_utils.GoogleDocstring, and pylint.extensions._check_docs_utils.SphinxDocstring.
Definition at line 308 of file _check_docs_utils.py.
    def exceptions(self) -> set[str]:
        return set()
has_params()
bool pylint.extensions._check_docs_utils.Docstring.has_params (self)
Reimplemented in pylint.extensions._check_docs_utils.GoogleDocstring, and pylint.extensions._check_docs_utils.SphinxDocstring.
Definition at line 311 of file _check_docs_utils.py.
    def has_params(self) -> bool:
        return False
has_property_returns()
bool pylint.extensions._check_docs_utils.Docstring.has_property_returns (self)
Reimplemented in pylint.extensions._check_docs_utils.EpytextDocstring, pylint.extensions._check_docs_utils.GoogleDocstring, and pylint.extensions._check_docs_utils.SphinxDocstring.
Definition at line 320 of file _check_docs_utils.py.
    def has_property_returns(self) -> bool:
        return False
has_property_type()
bool pylint.extensions._check_docs_utils.Docstring.has_property_type (self)
Reimplemented in pylint.extensions._check_docs_utils.GoogleDocstring, and pylint.extensions._check_docs_utils.SphinxDocstring.
Definition at line 323 of file _check_docs_utils.py.
    def has_property_type(self) -> bool:
        return False
has_returns()
bool pylint.extensions._check_docs_utils.Docstring.has_returns (self)
Reimplemented in pylint.extensions._check_docs_utils.GoogleDocstring, and pylint.extensions._check_docs_utils.SphinxDocstring.
Definition at line 314 of file _check_docs_utils.py.
    def has_returns(self) -> bool:
        return False
has_rtype()
bool pylint.extensions._check_docs_utils.Docstring.has_rtype (self)
Reimplemented in pylint.extensions._check_docs_utils.GoogleDocstring, and pylint.extensions._check_docs_utils.SphinxDocstring.
Definition at line 317 of file _check_docs_utils.py.
    def has_rtype(self) -> bool:
        return False
has_yields()
bool pylint.extensions._check_docs_utils.Docstring.has_yields (self)
Reimplemented in pylint.extensions._check_docs_utils.GoogleDocstring.
Definition at line 326 of file _check_docs_utils.py.
    def has_yields(self) -> bool:
        return False
has_yields_type()
bool pylint.extensions._check_docs_utils.Docstring.has_yields_type (self)
Reimplemented in pylint.extensions._check_docs_utils.GoogleDocstring.
Definition at line 329 of file _check_docs_utils.py.
    def has_yields_type(self) -> bool:
        return False
match_param_docs()
tuple[set[str], set[str]] pylint.extensions._check_docs_utils.Docstring.match_param_docs (self)
Reimplemented in pylint.extensions._check_docs_utils.GoogleDocstring, pylint.extensions._check_docs_utils.NumpyDocstring, and pylint.extensions._check_docs_utils.SphinxDocstring.
Definition at line 332 of file _check_docs_utils.py.
    def match_param_docs(self) -> tuple[set[str], set[str]]:
        return set(), set()
matching_sections()
int pylint.extensions._check_docs_utils.Docstring.matching_sections (self)
Returns the number of matching docstring sections.
Reimplemented in pylint.extensions._check_docs_utils.GoogleDocstring, and pylint.extensions._check_docs_utils.SphinxDocstring.
Definition at line 304 of file _check_docs_utils.py.
    def matching_sections(self) -> int:
        """Returns the number of matching docstring sections."""
        return 0
params_documented_elsewhere()
bool pylint.extensions._check_docs_utils.Docstring.params_documented_elsewhere (self)
Definition at line 335 of file _check_docs_utils.py.
    def params_documented_elsewhere(self) -> bool:
        return self.re_for_parameters_see.search(self.doc) is not None
References doc, and re_for_parameters_see.
Member Data Documentation
doc
pylint.extensions._check_docs_utils.Docstring.doc = docstring.expandtabs()
Definition at line 299 of file _check_docs_utils.py.
Referenced by pylint.extensions._check_docs_utils.GoogleDocstring._first_line(), pylint.extensions._check_docs_utils.GoogleDocstring._parse_section(), pylint.extensions._check_docs_utils.SphinxDocstring.exceptions(), pylint.extensions._check_docs_utils.GoogleDocstring.has_params(), pylint.extensions._check_docs_utils.SphinxDocstring.has_params(), pylint.extensions._check_docs_utils.SphinxDocstring.has_property_returns(), pylint.extensions._check_docs_utils.GoogleDocstring.has_property_type(), pylint.extensions._check_docs_utils.SphinxDocstring.has_property_type(), pylint.extensions._check_docs_utils.GoogleDocstring.has_returns(), pylint.extensions._check_docs_utils.SphinxDocstring.has_returns(), pylint.extensions._check_docs_utils.GoogleDocstring.has_rtype(), pylint.extensions._check_docs_utils.SphinxDocstring.has_rtype(), pylint.extensions._check_docs_utils.GoogleDocstring.has_yields(), pylint.extensions._check_docs_utils.GoogleDocstring.has_yields_type(), pylint.extensions._check_docs_utils.SphinxDocstring.match_param_docs(), and params_documented_elsewhere().
re_for_parameters_see
pylint.extensions._check_docs_utils.Docstring.re_for_parameters_see static
Initial value:
=  re.compile(
        ,
        re.X | re.S,
    )
Definition at line 283 of file _check_docs_utils.py.
Referenced by params_documented_elsewhere().
supports_yields
bool pylint.extensions._check_docs_utils.Docstring.supports_yields = False static
Definition at line 290 of file _check_docs_utils.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pylint/extensions/_check_docs_utils.py