Read&Watch: urllib3._base_connection.BaseHTTPConnection Class Reference
urllib3._base_connection.BaseHTTPConnection Class Reference
Public Member Functions
None __init__ (self, str host, int|None port=None, *, _TYPE_TIMEOUT timeout=_DEFAULT_TIMEOUT, tuple[str, int]|None source_address=None, int blocksize=8192, _TYPE_SOCKET_OPTIONS|None socket_options=..., Url|None proxy=None, ProxyConfig|None proxy_config=None)
None set_tunnel (self, str host, int|None port=None, typing.Mapping[str, str]|None headers=None, str scheme="http")
None connect (self)
None request (self, str method, str url, _TYPE_BODY|None body=None, typing.Mapping[str, str]|None headers=None, *, bool chunked=False, bool preload_content=True, bool decode_content=True, bool enforce_content_length=True)
BaseHTTPResponse getresponse (self)
None close (self)
bool is_closed (self)
bool is_connected (self)
bool has_connected_to_proxy (self)
Static Public Attributes
typing default_port .ClassVar[int]
typing default_socket_options .ClassVar[_TYPE_SOCKET_OPTIONS]
None timeout
tuple source_address [str, int] | None
_TYPE_SOCKET_OPTIONS socket_options | None
Url proxy | None
ProxyConfig proxy_config | None
bool proxy_is_verified | None
Detailed Description
Definition at line 35 of file _base_connection.py.
Constructor & Destructor Documentation
__init__()
None urllib3._base_connection.BaseHTTPConnection.__init__ (self, str host, int | None port = None, * , _TYPE_TIMEOUT timeout = _DEFAULT_TIMEOUT, tuple[str, int] | None source_address = None, int blocksize = 8192, _TYPE_SOCKET_OPTIONS | None socket_options = ..., Url | None proxy = None, ProxyConfig | None proxy_config = None)
Definition at line 54 of file _base_connection.py.
        ) -> None:
            ...
Member Function Documentation
close()
None urllib3._base_connection.BaseHTTPConnection.close (self)
Definition at line 100 of file _base_connection.py.
        def close(self) -> None:
            ...
Referenced by urllib3.contrib.emscripten.fetch._ReadStream.__del__(), django.db.backends.utils.CursorWrapper.__exit__(), pip._vendor.distlib.compat.ZipExtFile.__exit__(), pip._vendor.distlib.compat.ZipFile.__exit__(), urllib3.connectionpool.ConnectionPool.__exit__(), urllib3.util.ssltransport.SSLTransport.__exit__(), urllib3.contrib.pyopenssl.WrappedSocket._decref_socketios(), urllib3.connection.HTTPConnection._tunnel(), urllib3.response.HTTPResponse._update_chunk_length(), urllib3.contrib.emscripten.response.EmscriptenHttpResponseWrapper.drain_conn(), and urllib3.contrib.emscripten.fetch._ReadStream.readinto().
connect()
None urllib3._base_connection.BaseHTTPConnection.connect (self)
Definition at line 77 of file _base_connection.py.
        def connect(self) -> None:
            ...
getresponse()
BaseHTTPResponse urllib3._base_connection.BaseHTTPConnection.getresponse (self)
Definition at line 97 of file _base_connection.py.
        def getresponse(self) -> BaseHTTPResponse:
            ...
has_connected_to_proxy()
bool urllib3._base_connection.BaseHTTPConnection.has_connected_to_proxy (self)
Whether the connection has successfully connected to its proxy.
This returns False if no proxy is in use. Used to determine whether
errors are coming from the proxy layer or from tunnelling to the target origin.
Definition at line 115 of file _base_connection.py.
        def has_connected_to_proxy(self) -> bool:
            """Whether the connection has successfully connected to its proxy.
            This returns False if no proxy is in use. Used to determine whether
            errors are coming from the proxy layer or from tunnelling to the target origin.
            """
    class BaseHTTPSConnection(BaseHTTPConnection, Protocol):
is_closed()
bool urllib3._base_connection.BaseHTTPConnection.is_closed (self)
Whether the connection either is brand new or has been previously closed.
If this property is True then both ``is_connected`` and ``has_connected_to_proxy``
properties must be False.
Definition at line 104 of file _base_connection.py.
        def is_closed(self) -> bool:
            """Whether the connection either is brand new or has been previously closed.
            If this property is True then both ``is_connected`` and ``has_connected_to_proxy``
            properties must be False.
            """
Referenced by urllib3.contrib.emscripten.fetch._ReadStream.close(), and urllib3.contrib.emscripten.fetch._ReadStream.closed().
is_connected()
bool urllib3._base_connection.BaseHTTPConnection.is_connected (self)
Whether the connection is actively connected to any origin (proxy or target)
Definition at line 111 of file _base_connection.py.
        def is_connected(self) -> bool:
            """Whether the connection is actively connected to any origin (proxy or target)"""
request()
None urllib3._base_connection.BaseHTTPConnection.request (self, str method, str url, _TYPE_BODY | None body = None, typing.Mapping[str, str] | None headers = None, * , bool chunked = False, bool preload_content = True, bool decode_content = True, bool enforce_content_length = True)
Definition at line 80 of file _base_connection.py.
        ) -> None:
            ...
Referenced by django.views.generic.dates.DayMixin.get_day(), django.contrib.admin.filters.FacetsMixin.get_facet_queryset(), django.views.generic.edit.FormMixin.get_form_kwargs(), django.views.generic.dates.MonthMixin.get_month(), django.contrib.auth.views.RedirectURLMixin.get_redirect_url(), django.contrib.auth.views.RedirectURLMixin.get_success_url_allowed_hosts(), django.views.generic.dates.WeekMixin.get_week(), django.views.generic.dates.YearMixin.get_year(), django.contrib.auth.mixins.AccessMixin.handle_no_permission(), django.contrib.auth.mixins.PermissionRequiredMixin.has_permission(), django.views.generic.list.MultipleObjectMixin.paginate_queryset(), django.views.generic.base.TemplateResponseMixin.render_to_response(), and urllib3.connection.HTTPConnection.request_chunked().
set_tunnel()
None urllib3._base_connection.BaseHTTPConnection.set_tunnel (self, str host, int | None port = None, typing.Mapping[str, str] | None headers = None, str scheme = "http")
Definition at line 68 of file _base_connection.py.
        ) -> None:
            ...
Member Data Documentation
default_port
typing urllib3._base_connection.BaseHTTPConnection.default_port .ClassVar[int] static
Definition at line 36 of file _base_connection.py.
default_socket_options
typing urllib3._base_connection.BaseHTTPConnection.default_socket_options .ClassVar[_TYPE_SOCKET_OPTIONS] static
Definition at line 37 of file _base_connection.py.
proxy
Url urllib3._base_connection.BaseHTTPConnection.proxy | None static
Definition at line 48 of file _base_connection.py.
Referenced by urllib3.connectionpool.HTTPSConnectionPool._prepare_proxy(), urllib3.poolmanager.PoolManager._proxy_requires_url_absolute_form(), urllib3.poolmanager.ProxyManager.connection_from_host(), urllib3.connection.HTTPConnection.proxy_is_forwarding(), urllib3.connectionpool.HTTPConnectionPool.urlopen(), and urllib3.poolmanager.ProxyManager.urlopen().
proxy_config
ProxyConfig urllib3._base_connection.BaseHTTPConnection.proxy_config | None static
Definition at line 49 of file _base_connection.py.
Referenced by urllib3.connection.HTTPSConnection._connect_tls_proxy(), urllib3.poolmanager.PoolManager._proxy_requires_url_absolute_form(), urllib3.connectionpool.HTTPConnectionPool.urlopen(), and urllib3.poolmanager.ProxyManager.urlopen().
proxy_is_verified
bool urllib3._base_connection.BaseHTTPConnection.proxy_is_verified | None static
Definition at line 52 of file _base_connection.py.
Referenced by urllib3.connection.HTTPSConnection._connect_tls_proxy(), and urllib3.connection.HTTPConnection.close().
socket_options
_TYPE_SOCKET_OPTIONS urllib3._base_connection.BaseHTTPConnection.socket_options | None static
Definition at line 46 of file _base_connection.py.
Referenced by urllib3.connection.HTTPConnection.__init__(), and urllib3.connection.HTTPConnection._new_conn().
source_address
tuple urllib3._base_connection.BaseHTTPConnection.source_address [str, int] | None static
Definition at line 45 of file _base_connection.py.
Referenced by urllib3.connection.HTTPConnection._new_conn().
timeout
None urllib3._base_connection.BaseHTTPConnection.timeout static
Initial value:
 | (
            float
        )
Definition at line 41 of file _base_connection.py.
Referenced by urllib3.connectionpool.HTTPConnectionPool._get_timeout(), urllib3.connection.HTTPConnection._new_conn(), urllib3.connection.HTTPConnection.getresponse(), and urllib3.contrib.emscripten.fetch._ReadStream.readinto().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/urllib3/_base_connection.py