Read&Watch: pip._internal.exceptions.HashMismatch Class Reference
pip._internal.exceptions.HashMismatch Class Reference
Public Member Functions
None __init__ (self, Dict[str, List[str]] allowed, Dict[str, "_Hash"] gots)
str body (self)
Public Member Functions inherited from pip._internal.exceptions.HashError
str __str__ (self)
Public Attributes
allowed = allowed
gots = gots
Protected Member Functions
str _hash_comparison (self)
Protected Member Functions inherited from pip._internal.exceptions.HashError
str _requirement_name (self)
Additional Inherited Members
Static Public Attributes inherited from pip._internal.exceptions.HashError
Optional req = None
str head = ""
int order = -1
Detailed Description
Distribution file hash values don't match.
:ivar package_name: The name of the package that triggered the hash
    mismatch. Feel free to write to this after the exception is raise to
    improve its error message.
Definition at line 574 of file exceptions.py.
Constructor & Destructor Documentation
__init__()
None pip._internal.exceptions.HashMismatch.__init__ (self, Dict[str, List[str]] allowed, Dict[str, "_Hash"] gots)
:param allowed: A dict of algorithm names pointing to lists of allowed
    hex digests
:param gots: A dict of algorithm names pointing to hashes we
    actually got from the files under suspicion
Definition at line 592 of file exceptions.py.
    def __init__(self, allowed: Dict[str, List[str]], gots: Dict[str, "_Hash"]) -> None:
        """
        :param allowed: A dict of algorithm names pointing to lists of allowed
            hex digests
        :param gots: A dict of algorithm names pointing to hashes we
            actually got from the files under suspicion
        """
        self.allowed = allowed
        self.gots = gots
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
_hash_comparison()
str pip._internal.exceptions.HashMismatch._hash_comparison (self) protected
Return a comparison of actual and expected hash values.
Example::
       Expected sha256 abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde
                    or 123451234512345123451234512345123451234512345
            Got        bcdefbcdefbcdefbcdefbcdefbcdefbcdefbcdefbcdef
Definition at line 605 of file exceptions.py.
    def _hash_comparison(self) -> str:
        """
        Return a comparison of actual and expected hash values.
        Example::
               Expected sha256 abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde
                            or 123451234512345123451234512345123451234512345
                    Got        bcdefbcdefbcdefbcdefbcdefbcdefbcdefbcdefbcdef
        """
        def hash_then_or(hash_name: str) -> "chain[str]":
            # For now, all the decent hashes have 6-char names, so we can get
            # away with hard-coding space literals.
            return chain([hash_name], repeat("    or"))
        lines: List[str] = []
        for hash_name, expecteds in self.allowed.items():
            prefix = hash_then_or(hash_name)
            lines.extend((f"        Expected {next(prefix)} {e}") for e in expecteds)
            lines.append(
                f"             Got        {self.gots[hash_name].hexdigest()}\n"
            )
        return "\n".join(lines)
body()
str pip._internal.exceptions.HashMismatch.body (self)
Return a summary of me for display under the heading.
This default implementation simply prints a description of the
triggering requirement.
:param req: The InstallRequirement that provoked this error, with
    its link already populated by the resolver's _populate_link().
Reimplemented from pip._internal.exceptions.HashError.
Definition at line 602 of file exceptions.py.
    def body(self) -> str:
        return f"    {self._requirement_name()}:\n{self._hash_comparison()}"
Referenced by tomlkit.container.Container.__copy__(), and astroid.nodes.scoped_nodes.mixin.LocalsDictNodeNG._append_node().
Member Data Documentation
allowed
pip._internal.exceptions.HashMismatch.allowed = allowed
Definition at line 599 of file exceptions.py.
gots
pip._internal.exceptions.HashMismatch.gots = gots
Definition at line 600 of file exceptions.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_internal/exceptions.py