Read&Watch: pip._vendor.pygments.lexer.DelegatingLexer Class Reference
pip._vendor.pygments.lexer.DelegatingLexer Class Reference
Public Member Functions
__init__ (self, _root_lexer, _language_lexer, _needle=Other, **options)
get_tokens_unprocessed (self, text)
Public Member Functions inherited from pip._vendor.pygments.lexer.Lexer
__init__ (self, **options)
__repr__ (self)
add_filter (self, filter_, **options)
analyse_text (text)
get_tokens (self, text, unfiltered=False)
Public Member Functions inherited from pip._vendor.pygments.lexer.LexerMeta
__new__ (mcs, name, bases, d)
Public Attributes
root_lexer = _root_lexer(**options)
language_lexer = _language_lexer(**options)
needle = _needle
Public Attributes inherited from pip._vendor.pygments.lexer.Lexer
options = options
stripnl = get_bool_opt(options, 'stripnl', True)
stripall = get_bool_opt(options, 'stripall', False)
ensurenl = get_bool_opt(options, 'ensurenl', True)
tabsize = get_int_opt(options, 'tabsize', 0)
str encoding = options.get('encoding', 'guess')
list filters = []
Additional Inherited Members
Static Public Attributes inherited from pip._vendor.pygments.lexer.Lexer
name = None
list aliases = []
list filenames = []
list alias_filenames = []
list mimetypes = []
int priority = 0
url = None
version_added = None
Protected Member Functions inherited from pip._vendor.pygments.lexer.Lexer
_preprocess_lexer_input (self, text)
Static Protected Attributes inherited from pip._vendor.pygments.lexer.Lexer
_example = None
Detailed Description
This lexer takes two lexer as arguments. A root lexer and
a language lexer. First everything is scanned using the language
lexer, afterwards all ``Other`` tokens are lexed using the root
lexer.
The lexers from the ``template`` lexer package use this base lexer.
Definition at line 291 of file lexer.py.
Constructor & Destructor Documentation
__init__()
pip._vendor.pygments.lexer.DelegatingLexer.__init__ (self, _root_lexer, _language_lexer, _needle = Other, ** options)
Definition at line 301 of file lexer.py.
    def __init__(self, _root_lexer, _language_lexer, _needle=Other, **options):
        self.root_lexer = _root_lexer(**options)
        self.language_lexer = _language_lexer(**options)
        self.needle = _needle
        Lexer.__init__(self, **options)
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
get_tokens_unprocessed()
pip._vendor.pygments.lexer.DelegatingLexer.get_tokens_unprocessed (self, text)
This method should process the text and return an iterable of
``(index, tokentype, value)`` tuples where ``index`` is the starting
position of the token within the input text.
It must be overridden by subclasses. It is recommended to
implement it as a generator to maximize effectiveness.
Reimplemented from pip._vendor.pygments.lexer.Lexer.
Definition at line 307 of file lexer.py.
    def get_tokens_unprocessed(self, text):
        buffered = ''
        insertions = []
        lng_buffer = []
        for i, t, v in self.language_lexer.get_tokens_unprocessed(text):
            if t is self.needle:
                if lng_buffer:
                    insertions.append((len(buffered), lng_buffer))
                    lng_buffer = []
                buffered += v
            else:
                lng_buffer.append((i, t, v))
        if lng_buffer:
            insertions.append((len(buffered), lng_buffer))
        return do_insertions(insertions,
                             self.root_lexer.get_tokens_unprocessed(buffered))
# ------------------------------------------------------------------------------
# RegexLexer and ExtendedRegexLexer
#
References pip._vendor.pygments.lexer.do_insertions(), get_tokens_unprocessed(), language_lexer, needle, and root_lexer.
Referenced by get_tokens_unprocessed().
Member Data Documentation
language_lexer
pip._vendor.pygments.lexer.DelegatingLexer.language_lexer = _language_lexer(**options)
Definition at line 303 of file lexer.py.
Referenced by get_tokens_unprocessed().
needle
pip._vendor.pygments.lexer.DelegatingLexer.needle = _needle
Definition at line 304 of file lexer.py.
Referenced by get_tokens_unprocessed().
root_lexer
pip._vendor.pygments.lexer.DelegatingLexer.root_lexer = _root_lexer(**options)
Definition at line 302 of file lexer.py.
Referenced by get_tokens_unprocessed().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/pygments/lexer.py