Read&Watch: yaml.representer.Representer Class Reference
yaml.representer.Representer Class Reference
Public Member Functions
represent_complex (self, data)
represent_tuple (self, data)
represent_name (self, data)
represent_module (self, data)
represent_object (self, data)
represent_ordered_dict (self, data)
Public Member Functions inherited from yaml.representer.SafeRepresenter
ignore_aliases (self, data)
represent_none (self, data)
represent_str (self, data)
represent_binary (self, data)
represent_bool (self, data)
represent_int (self, data)
represent_float (self, data)
represent_list (self, data)
represent_dict (self, data)
represent_set (self, data)
represent_date (self, data)
represent_datetime (self, data)
represent_yaml_object (self, tag, data, cls, flow_style=None)
represent_undefined (self, data)
Public Member Functions inherited from yaml.representer.BaseRepresenter
__init__ (self, default_style=None, default_flow_style=False, sort_keys=True)
represent (self, data)
represent_data (self, data)
add_representer (cls, data_type, representer)
add_multi_representer (cls, data_type, representer)
represent_scalar (self, tag, value, style=None)
represent_sequence (self, tag, sequence, flow_style=None)
represent_mapping (self, tag, mapping, flow_style=None)
Additional Inherited Members
Public Attributes inherited from yaml.representer.BaseRepresenter
default_style = default_style
sort_keys = sort_keys
default_flow_style = default_flow_style
dict represented_objects = {}
list object_keeper = []
alias_key = None
Static Public Attributes inherited from yaml.representer.SafeRepresenter
int inf_value = 1e300
Static Public Attributes inherited from yaml.representer.BaseRepresenter
dict yaml_representers = {}
dict yaml_multi_representers = {}
Detailed Description
Definition at line 272 of file representer.py.
Member Function Documentation
represent_complex()
yaml.representer.Representer.represent_complex (self, data)
Definition at line 274 of file representer.py.
    def represent_complex(self, data):
        if data.imag == 0.0:
            data = '%r' % data.real
        elif data.real == 0.0:
            data = '%rj' % data.imag
        elif data.imag > 0:
            data = '%r+%rj' % (data.real, data.imag)
        else:
            data = '%r%rj' % (data.real, data.imag)
        return self.represent_scalar('tag:yaml.org,2002:python/complex', data)
References yaml.representer.BaseRepresenter.represent_scalar().
represent_module()
yaml.representer.Representer.represent_module (self, data)
Definition at line 292 of file representer.py.
    def represent_module(self, data):
        return self.represent_scalar(
                'tag:yaml.org,2002:python/module:'+data.__name__, '')
References yaml.representer.BaseRepresenter.represent_scalar().
represent_name()
yaml.representer.Representer.represent_name (self, data)
Definition at line 288 of file representer.py.
    def represent_name(self, data):
        name = '%s.%s' % (data.__module__, data.__name__)
        return self.represent_scalar('tag:yaml.org,2002:python/name:'+name, '')
References yaml.representer.BaseRepresenter.represent_scalar().
represent_object()
yaml.representer.Representer.represent_object (self, data)
Definition at line 296 of file representer.py.
    def represent_object(self, data):
        # We use __reduce__ API to save the data. data.__reduce__ returns
        # a tuple of length 2-5:
        #   (function, args, state, listitems, dictitems)
        # For reconstructing, we calls function(*args), then set its state,
        # listitems, and dictitems if they are not None.
        # A special case is when function.__name__ == '__newobj__'. In this
        # case we create the object with args[0].__new__(*args).
        # Another special case is when __reduce__ returns a string - we don't
        # support it.
        # We produce a !!python/object, !!python/object/new or
        # !!python/object/apply node.
        cls = type(data)
        if cls in copyreg.dispatch_table:
            reduce = copyreg.dispatch_table[cls](data)
        elif hasattr(data, '__reduce_ex__'):
            reduce = data.__reduce_ex__(2)
        elif hasattr(data, '__reduce__'):
            reduce = data.__reduce__()
        else:
            raise RepresenterError("cannot represent an object", data)
        reduce = (list(reduce)+[None]*5)[:5]
        function, args, state, listitems, dictitems = reduce
        args = list(args)
        if state is None:
            state = {}
        if listitems is not None:
            listitems = list(listitems)
        if dictitems is not None:
            dictitems = dict(dictitems)
        if function.__name__ == '__newobj__':
            function = args[0]
            args = args[1:]
            tag = 'tag:yaml.org,2002:python/object/new:'
            newobj = True
        else:
            tag = 'tag:yaml.org,2002:python/object/apply:'
            newobj = False
        function_name = '%s.%s' % (function.__module__, function.__name__)
        if not args and not listitems and not dictitems \
                and isinstance(state, dict) and newobj:
            return self.represent_mapping(
                    'tag:yaml.org,2002:python/object:'+function_name, state)
        if not listitems and not dictitems  \
                and isinstance(state, dict) and not state:
            return self.represent_sequence(tag+function_name, args)
        value = {}
        if args:
            value['args'] = args
        if state or not isinstance(state, dict):
            value['state'] = state
        if listitems:
            value['listitems'] = listitems
        if dictitems:
            value['dictitems'] = dictitems
        return self.represent_mapping(tag+function_name, value)
References yaml.representer.BaseRepresenter.represent_mapping(), and yaml.representer.BaseRepresenter.represent_sequence().
represent_ordered_dict()
yaml.representer.Representer.represent_ordered_dict (self, data)
Definition at line 358 of file representer.py.
    def represent_ordered_dict(self, data):
        # Provide uniform representation across different Python versions.
        data_type = type(data)
        tag = 'tag:yaml.org,2002:python/object/apply:%s.%s' \
                % (data_type.__module__, data_type.__name__)
        items = [[key, value] for key, value in data.items()]
        return self.represent_sequence(tag, [items])
References yaml.representer.BaseRepresenter.represent_sequence().
represent_tuple()
yaml.representer.Representer.represent_tuple (self, data)
Definition at line 285 of file representer.py.
    def represent_tuple(self, data):
        return self.represent_sequence('tag:yaml.org,2002:python/tuple', data)
References yaml.representer.BaseRepresenter.represent_sequence().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/yaml/representer.py