Read&Watch: django.db.models.expressions.OuterRef Class Reference
django.db.models.expressions.OuterRef Class Reference
Public Member Functions
resolve_expression (self, *args, **kwargs)
relabeled_clone (self, relabels)
Public Member Functions inherited from django.db.models.expressions.F
__init__ (self, name)
__repr__ (self)
__getitem__ (self, subscript)
__contains__ (self, other)
replace_expressions (self, replacements)
asc (self, **kwargs)
desc (self, **kwargs)
__eq__ (self, other)
__hash__ (self)
copy (self)
Public Member Functions inherited from django.db.models.expressions.Combinable
__neg__ (self)
OPERATORS #.
__add__ (self, other)
__sub__ (self, other)
__mul__ (self, other)
__truediv__ (self, other)
__mod__ (self, other)
__pow__ (self, other)
__and__ (self, other)
bitand (self, other)
bitleftshift (self, other)
bitrightshift (self, other)
__xor__ (self, other)
bitxor (self, other)
__or__ (self, other)
bitor (self, other)
__radd__ (self, other)
__rsub__ (self, other)
__rmul__ (self, other)
__rtruediv__ (self, other)
__rmod__ (self, other)
__rpow__ (self, other)
__rand__ (self, other)
__ror__ (self, other)
__rxor__ (self, other)
__invert__ (self)
Static Public Attributes
bool contains_aggregate = False
bool contains_over_clause = False
Static Public Attributes inherited from django.db.models.expressions.F
bool allowed_default = False
Static Public Attributes inherited from django.db.models.expressions.Combinable
str ADD = "+"
str SUB = "-"
str MUL = "*"
str DIV = "/"
str POW = "^"
str MOD = "%%"
str BITAND = "&"
str BITOR = "|"
str BITLEFTSHIFT = "<<"
str BITRIGHTSHIFT = ">>"
str BITXOR = "#"
Additional Inherited Members
Public Attributes inherited from django.db.models.expressions.F
name = name
Protected Member Functions inherited from django.db.models.expressions.Combinable
_combine (self, other, connector, reversed)
Detailed Description
Definition at line 953 of file expressions.py.
Member Function Documentation
relabeled_clone()
django.db.models.expressions.OuterRef.relabeled_clone (self, relabels)
Definition at line 962 of file expressions.py.
    def relabeled_clone(self, relabels):
        return self
Referenced by django.db.models.sql.datastructures.Join.demote(), and django.db.models.sql.datastructures.Join.promote().
resolve_expression()
django.db.models.expressions.OuterRef.resolve_expression (self, * args, ** kwargs)
Reimplemented from django.db.models.expressions.F.
Definition at line 957 of file expressions.py.
    def resolve_expression(self, *args, **kwargs):
        if isinstance(self.name, self.__class__):
            return self.name
        return ResolvedOuterRef(self.name)
Referenced by django.template.defaulttags.RegroupNode.render().
Member Data Documentation
contains_aggregate
bool django.db.models.expressions.OuterRef.contains_aggregate = False static
Definition at line 954 of file expressions.py.
contains_over_clause
bool django.db.models.expressions.OuterRef.contains_over_clause = False static
Definition at line 955 of file expressions.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/db/models/expressions.py