Read&Watch: django.contrib.gis.gdal.envelope.Envelope Class Reference
django.contrib.gis.gdal.envelope.Envelope Class Reference
Public Member Functions
__init__ (self, *args)
__eq__ (self, other)
__str__ (self)
expand_to_include (self, *args)
min_x (self)
min_y (self)
max_x (self)
max_y (self)
ur (self)
ll (self)
tuple (self)
wkt (self)
Public Attributes
max_x = 4:
max_y
min_x = other.min_x)
min_y = other.min_y)
tuple
Protected Member Functions
_from_sequence (self, seq)
Protected Attributes
_envelope = args[0]
Detailed Description
The Envelope object is a C structure that contains the minimum and
maximum X, Y coordinates for a rectangle bounding box.  The naming
of the variables is compatible with the OGR Envelope structure.
Definition at line 32 of file envelope.py.
Constructor & Destructor Documentation
__init__()
django.contrib.gis.gdal.envelope.Envelope.__init__ (self, * args)
The initialization function may take an OGREnvelope structure, 4-element
tuple or list, or 4 individual arguments.
Definition at line 39 of file envelope.py.
    def __init__(self, *args):
        """
        The initialization function may take an OGREnvelope structure, 4-element
        tuple or list, or 4 individual arguments.
        """
        if len(args) == 1:
            if isinstance(args[0], OGREnvelope):
                # OGREnvelope (a ctypes Structure) was passed in.
                self._envelope = args[0]
            elif isinstance(args[0], (tuple, list)):
                # A tuple was passed in.
                if len(args[0]) != 4:
                    raise GDALException(
                        "Incorrect number of tuple elements (%d)." % len(args[0])
                    )
                else:
                    self._from_sequence(args[0])
            else:
                raise TypeError("Incorrect type of argument: %s" % type(args[0]))
        elif len(args) == 4:
            # Individual parameters passed in.
            #  Thanks to ww for the help
            self._from_sequence([float(a) for a in args])
        else:
            raise GDALException("Incorrect number (%d) of arguments." % len(args))
        # Checking the x,y coordinates
        if self.min_x > self.max_x:
            raise GDALException("Envelope minimum X > maximum X.")
        if self.min_y > self.max_y:
            raise GDALException("Envelope minimum Y > maximum Y.")
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
__eq__()
django.contrib.gis.gdal.envelope.Envelope.__eq__ (self, other)
Return True if the envelopes are equivalent; can compare against
other Envelopes and 4-tuples.
Definition at line 72 of file envelope.py.
    def __eq__(self, other):
        """
        Return True if the envelopes are equivalent; can compare against
        other Envelopes and 4-tuples.
        """
        if isinstance(other, Envelope):
            return (
                (self.min_x == other.min_x)
                and (self.min_y == other.min_y)
                and (self.max_x == other.max_x)
                and (self.max_y == other.max_y)
            )
        elif isinstance(other, tuple) and len(other) == 4:
            return (
                (self.min_x == other[0])
                and (self.min_y == other[1])
                and (self.max_x == other[2])
                and (self.max_y == other[3])
            )
        else:
            raise GDALException("Equivalence testing only works with other Envelopes.")
Referenced by pip._vendor.distlib.version.Version.__ge__(), pip._vendor.distlib.version.Version.__gt__(), pip._vendor.distlib.version.Version.__le__(), dotenv.variables.Atom.__ne__(), pip._vendor.distlib.version.Matcher.__ne__(), pip._vendor.distlib.version.Version.__ne__(), pip._vendor.msgpack.ext.Timestamp.__ne__(), pip._vendor.urllib3._collections.HTTPHeaderDict.__ne__(), responses.BaseResponse.__ne__(), and urllib3._collections.HTTPHeaderDict.__ne__().
__str__()
django.contrib.gis.gdal.envelope.Envelope.__str__ (self)
Definition at line 94 of file envelope.py.
    def __str__(self):
        "Return a string representation of the tuple."
        return str(self.tuple)
Referenced by PIL.PdfParser.IndirectReference.__bytes__().
_from_sequence()
django.contrib.gis.gdal.envelope.Envelope._from_sequence (self, seq) protected
Definition at line 98 of file envelope.py.
    def _from_sequence(self, seq):
        "Initialize the C OGR Envelope structure from the given sequence."
        self._envelope = OGREnvelope()
        self._envelope.MinX = seq[0]
        self._envelope.MinY = seq[1]
        self._envelope.MaxX = seq[2]
        self._envelope.MaxY = seq[3]
References _envelope.
expand_to_include()
django.contrib.gis.gdal.envelope.Envelope.expand_to_include (self, * args)
Modify the envelope to expand to include the boundaries of
the passed-in 2-tuple (a point), 4-tuple (an extent) or
envelope.
Definition at line 106 of file envelope.py.
    def expand_to_include(self, *args):
        """
        Modify the envelope to expand to include the boundaries of
        the passed-in 2-tuple (a point), 4-tuple (an extent) or
        envelope.
        """
        # We provide a number of different signatures for this method,
        # and the logic here is all about converting them into a
        # 4-tuple single parameter which does the actual work of
        # expanding the envelope.
        if len(args) == 1:
            if isinstance(args[0], Envelope):
                return self.expand_to_include(args[0].tuple)
            elif hasattr(args[0], "x") and hasattr(args[0], "y"):
                return self.expand_to_include(
                    args[0].x, args[0].y, args[0].x, args[0].y
                )
            elif isinstance(args[0], (tuple, list)):
                # A tuple was passed in.
                if len(args[0]) == 2:
                    return self.expand_to_include(
                        (args[0][0], args[0][1], args[0][0], args[0][1])
                    )
                elif len(args[0]) == 4:
                    (minx, miny, maxx, maxy) = args[0]
                    if minx < self._envelope.MinX:
                        self._envelope.MinX = minx
                    if miny < self._envelope.MinY:
                        self._envelope.MinY = miny
                    if maxx > self._envelope.MaxX:
                        self._envelope.MaxX = maxx
                    if maxy > self._envelope.MaxY:
                        self._envelope.MaxY = maxy
                else:
                    raise GDALException(
                        "Incorrect number of tuple elements (%d)." % len(args[0])
                    )
            else:
                raise TypeError("Incorrect type of argument: %s" % type(args[0]))
        elif len(args) == 2:
            # An x and an y parameter were passed in
            return self.expand_to_include((args[0], args[1], args[0], args[1]))
        elif len(args) == 4:
            # Individual parameters passed in.
            return self.expand_to_include(args)
        else:
            raise GDALException("Incorrect number (%d) of arguments." % len(args[0]))
References _envelope, and expand_to_include().
Referenced by expand_to_include().
ll()
django.contrib.gis.gdal.envelope.Envelope.ll (self)
Definition at line 180 of file envelope.py.
    def ll(self):
        "Return the lower-left coordinate."
        return (self.min_x, self.min_y)
References min_x, and min_y.
max_x()
django.contrib.gis.gdal.envelope.Envelope.max_x (self)
Definition at line 165 of file envelope.py.
    def max_x(self):
        "Return the value of the maximum X coordinate."
        return self._envelope.MaxX
References _envelope.
max_y()
django.contrib.gis.gdal.envelope.Envelope.max_y (self)
Definition at line 170 of file envelope.py.
    def max_y(self):
        "Return the value of the maximum Y coordinate."
        return self._envelope.MaxY
References _envelope.
min_x()
django.contrib.gis.gdal.envelope.Envelope.min_x (self)
Definition at line 155 of file envelope.py.
    def min_x(self):
        "Return the value of the minimum X coordinate."
        return self._envelope.MinX
References _envelope.
min_y()
django.contrib.gis.gdal.envelope.Envelope.min_y (self)
Definition at line 160 of file envelope.py.
    def min_y(self):
        "Return the value of the minimum Y coordinate."
        return self._envelope.MinY
References _envelope.
tuple()
django.contrib.gis.gdal.envelope.Envelope.tuple (self)
Definition at line 185 of file envelope.py.
    def tuple(self):
        "Return a tuple representing the envelope."
        return (self.min_x, self.min_y, self.max_x, self.max_y)
References max_x, max_y, min_x, and min_y.
ur()
django.contrib.gis.gdal.envelope.Envelope.ur (self)
Definition at line 175 of file envelope.py.
    def ur(self):
        "Return the upper-right coordinate."
        return (self.max_x, self.max_y)
References max_x, and max_y.
wkt()
django.contrib.gis.gdal.envelope.Envelope.wkt (self)
Definition at line 190 of file envelope.py.
    def wkt(self):
        "Return WKT representing a Polygon for this envelope."
        # TODO: Fix significant figures.
        return "POLYGON((%s %s,%s %s,%s %s,%s %s,%s %s))" % (
            self.min_x,
            self.min_y,
            self.min_x,
            self.max_y,
            self.max_x,
            self.max_y,
            self.max_x,
            self.min_y,
            self.min_x,
            self.min_y,
        )
References max_x, max_y, min_x, and min_y.
Member Data Documentation
_envelope
django.contrib.gis.gdal.envelope.Envelope._envelope = args[0] protected
Definition at line 48 of file envelope.py.
Referenced by _from_sequence(), expand_to_include(), max_x(), max_y(), min_x(), and min_y().
max_x
django.contrib.gis.gdal.envelope.Envelope.max_x = 4:
Definition at line 67 of file envelope.py.
Referenced by tuple(), ur(), and wkt().
max_y
django.contrib.gis.gdal.envelope.Envelope.max_y
Definition at line 69 of file envelope.py.
Referenced by tuple(), ur(), and wkt().
min_x
django.contrib.gis.gdal.envelope.Envelope.min_x = other.min_x)
Definition at line 79 of file envelope.py.
Referenced by ll(), tuple(), and wkt().
min_y
django.contrib.gis.gdal.envelope.Envelope.min_y = other.min_y)
Definition at line 80 of file envelope.py.
Referenced by ll(), tuple(), and wkt().
tuple
django.contrib.gis.gdal.envelope.Envelope.tuple
Definition at line 96 of file envelope.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/gis/gdal/envelope.py