Read&Watch: django.db.models.functions.datetime.TimezoneMixin Class Reference
django.db.models.functions.datetime.TimezoneMixin Class Reference
Public Member Functions
get_tzname (self)
Static Public Attributes
tzinfo = None
Detailed Description
Definition at line 24 of file datetime.py.
Member Function Documentation
get_tzname()
django.db.models.functions.datetime.TimezoneMixin.get_tzname (self)
Definition at line 27 of file datetime.py.
    def get_tzname(self):
        # Timezone conversions must happen to the input datetime *before*
        # applying a function. 2015-12-31 23:00:00 -02:00 is stored in the
        # database as 2016-01-01 01:00:00 +00:00. Any results should be
        # based on the input datetime not the stored datetime.
        tzname = None
        if settings.USE_TZ:
            if self.tzinfo is None:
                tzname = timezone.get_current_timezone_name()
            else:
                tzname = timezone._get_timezone_name(self.tzinfo)
        return tzname
References tzinfo.
Referenced by django.db.models.functions.datetime.Extract.as_sql(), django.db.models.functions.datetime.TruncBase.as_sql(), django.db.models.functions.datetime.TruncDate.as_sql(), and django.db.models.functions.datetime.TruncTime.as_sql().
Member Data Documentation
tzinfo
django.db.models.functions.datetime.TimezoneMixin.tzinfo = None static
Definition at line 25 of file datetime.py.
Referenced by tomlkit.items.DateTime.__add__(), django.db.models.functions.datetime.TruncBase.__init__(), tomlkit.items.DateTime.__sub__(), django.db.models.functions.datetime.Extract.as_sql(), django.db.models.functions.datetime.TruncBase.as_sql(), django.db.models.functions.datetime.TruncBase.convert_value(), and get_tzname().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/db/models/functions/datetime.py