Read&Watch: django.urls.resolvers.LocalePrefixPattern Class Reference
django.urls.resolvers.LocalePrefixPattern Class Reference
Public Member Functions
__init__ (self, prefix_default_language=True)
regex (self)
language_prefix (self)
match (self, path)
check (self)
describe (self)
__str__ (self)
Public Attributes
prefix_default_language = prefix_default_language
dict converters = {}
language_prefix
Detailed Description
Definition at line 378 of file resolvers.py.
Constructor & Destructor Documentation
__init__()
django.urls.resolvers.LocalePrefixPattern.__init__ (self, prefix_default_language = True)
Definition at line 379 of file resolvers.py.
    def __init__(self, prefix_default_language=True):
        self.prefix_default_language = prefix_default_language
        self.converters = {}
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
__str__()
django.urls.resolvers.LocalePrefixPattern.__str__ (self)
Definition at line 408 of file resolvers.py.
    def __str__(self):
        return self.language_prefix
References language_prefix.
Referenced by PIL.PdfParser.IndirectReference.__bytes__().
check()
django.urls.resolvers.LocalePrefixPattern.check (self)
Definition at line 402 of file resolvers.py.
    def check(self):
        return []
Referenced by pip._vendor.packaging._tokenizer.Tokenizer.consume(), pip._vendor.packaging._tokenizer.Tokenizer.enclosing_tokens(), pip._vendor.packaging._tokenizer.Tokenizer.expect(), and pip._vendor.pygments.scanner.Scanner.test().
describe()
django.urls.resolvers.LocalePrefixPattern.describe (self)
Definition at line 405 of file resolvers.py.
    def describe(self):
        return "'{}'".format(self)
language_prefix()
django.urls.resolvers.LocalePrefixPattern.language_prefix (self)
Definition at line 389 of file resolvers.py.
    def language_prefix(self):
        language_code = get_language() or settings.LANGUAGE_CODE
        if language_code == settings.LANGUAGE_CODE and not self.prefix_default_language:
            return ""
        else:
            return "%s/" % language_code
References prefix_default_language.
match()
django.urls.resolvers.LocalePrefixPattern.match (self, path)
Definition at line 396 of file resolvers.py.
    def match(self, path):
        language_prefix = self.language_prefix
        if path.startswith(language_prefix):
            return path.removeprefix(language_prefix), (), {}
        return None
References language_prefix.
regex()
django.urls.resolvers.LocalePrefixPattern.regex (self)
Definition at line 384 of file resolvers.py.
    def regex(self):
        # This is only used by reverse() and cached in _reverse_dict.
        return re.compile(re.escape(self.language_prefix))
Member Data Documentation
converters
dict django.urls.resolvers.LocalePrefixPattern.converters = {}
Definition at line 381 of file resolvers.py.
language_prefix
django.urls.resolvers.LocalePrefixPattern.language_prefix
Definition at line 386 of file resolvers.py.
Referenced by __str__(), and match().
prefix_default_language
django.urls.resolvers.LocalePrefixPattern.prefix_default_language = prefix_default_language
Definition at line 380 of file resolvers.py.
Referenced by language_prefix().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/urls/resolvers.py