Read&Watch: django.contrib.sessions.backends.signed_cookies.SessionStore Class Reference
django.contrib.sessions.backends.signed_cookies.SessionStore Class Reference
Public Member Functions
load (self)
aload (self)
create (self)
acreate (self)
save (self, must_create=False)
asave (self, must_create=False)
exists (self, session_key=None)
aexists (self, session_key=None)
delete (self, session_key=None)
adelete (self, session_key=None)
cycle_key (self)
acycle_key (self)
clear_expired (cls)
aclear_expired (cls)
Public Member Functions inherited from django.contrib.sessions.backends.base.SessionBase
__init__ (self, session_key=None)
__contains__ (self, key)
__getitem__ (self, key)
__setitem__ (self, key, value)
aset (self, key, value)
__delitem__ (self, key)
key_salt (self)
get (self, key, default=None)
aget (self, key, default=None)
pop (self, key, default=__not_given)
apop (self, key, default=__not_given)
setdefault (self, key, value)
asetdefault (self, key, value)
set_test_cookie (self)
aset_test_cookie (self)
test_cookie_worked (self)
atest_cookie_worked (self)
delete_test_cookie (self)
adelete_test_cookie (self)
encode (self, session_dict)
decode (self, session_data)
update (self, dict_)
aupdate (self, dict_)
has_key (self, key)
ahas_key (self, key)
keys (self)
akeys (self)
values (self)
avalues (self)
items (self)
aitems (self)
clear (self)
is_empty (self)
get_session_cookie_age (self)
get_expiry_age (self, **kwargs)
aget_expiry_age (self, **kwargs)
get_expiry_date (self, **kwargs)
aget_expiry_date (self, **kwargs)
set_expiry (self, value)
aset_expiry (self, value)
get_expire_at_browser_close (self)
aget_expire_at_browser_close (self)
flush (self)
aflush (self)
Protected Member Functions
_get_session_key (self)
Protected Member Functions inherited from django.contrib.sessions.backends.base.SessionBase
_get_new_session_key (self)
_aget_new_session_key (self)
_get_or_create_session_key (self)
_aget_or_create_session_key (self)
_validate_session_key (self, key)
_set_session_key (self, value)
_get_session (self, no_load=False)
_aget_session (self, no_load=False)
Additional Inherited Members
Public Attributes inherited from django.contrib.sessions.backends.base.SessionBase
bool accessed = False
bool modified = False
serializer = import_string(settings.SESSION_SERIALIZER)
Static Public Attributes inherited from django.contrib.sessions.backends.base.SessionBase
str TEST_COOKIE_NAME = "testcookie"
str TEST_COOKIE_VALUE = "worked"
Protected Attributes inherited from django.contrib.sessions.backends.base.SessionBase
dict _session_cache = {}
Properties inherited from django.contrib.sessions.backends.base.SessionBase
session_key = property(_get_session_key)
_session_key = property(_get_session_key, _set_session_key)
_session = property(_get_session)
Detailed Description
Definition at line 5 of file signed_cookies.py.
Member Function Documentation
_get_session_key()
django.contrib.sessions.backends.signed_cookies.SessionStore._get_session_key (self) protected
Instead of generating a random string, generate a secure url-safe
base64-encoded string of data as our session key.
Reimplemented from django.contrib.sessions.backends.base.SessionBase.
Definition at line 85 of file signed_cookies.py.
    def _get_session_key(self):
        """
        Instead of generating a random string, generate a secure url-safe
        base64-encoded string of data as our session key.
        """
        return signing.dumps(
            self._session,
            compress=True,
            salt="django.contrib.sessions.backends.signed_cookies",
            serializer=self.serializer,
        )
aclear_expired()
django.contrib.sessions.backends.signed_cookies.SessionStore.aclear_expired (cls)
Reimplemented from django.contrib.sessions.backends.base.SessionBase.
Definition at line 102 of file signed_cookies.py.
    async def aclear_expired(cls):
        pass
acreate()
django.contrib.sessions.backends.signed_cookies.SessionStore.acreate (self)
Reimplemented from django.contrib.sessions.backends.base.SessionBase.
Definition at line 36 of file signed_cookies.py.
    async def acreate(self):
        return self.create()
References django.contrib.sessions.backends.base.SessionBase.create.
acycle_key()
django.contrib.sessions.backends.signed_cookies.SessionStore.acycle_key (self)
Create a new session key, while retaining the current session data.
Reimplemented from django.contrib.sessions.backends.base.SessionBase.
Definition at line 82 of file signed_cookies.py.
    async def acycle_key(self):
        return self.cycle_key()
References django.contrib.sessions.backends.base.SessionBase.cycle_key().
adelete()
django.contrib.sessions.backends.signed_cookies.SessionStore.adelete (self, session_key = None)
Reimplemented from django.contrib.sessions.backends.base.SessionBase.
Definition at line 72 of file signed_cookies.py.
    async def adelete(self, session_key=None):
        return self.delete(session_key=session_key)
References django.contrib.sessions.backends.base.SessionBase.delete.
Referenced by django.core.cache.backends.base.BaseCache.adelete_many(), and django.core.cache.backends.base.BaseCache.aincr_version().
aexists()
django.contrib.sessions.backends.signed_cookies.SessionStore.aexists (self, session_key = None)
Reimplemented from django.contrib.sessions.backends.base.SessionBase.
Definition at line 59 of file signed_cookies.py.
    async def aexists(self, session_key=None):
        return self.exists(session_key=session_key)
References django.contrib.sessions.backends.base.SessionBase.exists.
aload()
django.contrib.sessions.backends.signed_cookies.SessionStore.aload (self)
Reimplemented from django.contrib.sessions.backends.base.SessionBase.
Definition at line 26 of file signed_cookies.py.
    async def aload(self):
        return self.load()
References django.contrib.sessions.backends.base.SessionBase.load.
asave()
django.contrib.sessions.backends.signed_cookies.SessionStore.asave (self, must_create = False)
Reimplemented from django.contrib.sessions.backends.base.SessionBase.
Definition at line 48 of file signed_cookies.py.
    async def asave(self, must_create=False):
        return self.save(must_create=must_create)
References django.contrib.sessions.backends.base.SessionBase.save.
Referenced by django.contrib.auth.base_user.AbstractBaseUser.acheck_password().
clear_expired()
django.contrib.sessions.backends.signed_cookies.SessionStore.clear_expired (cls)
Reimplemented from django.contrib.sessions.backends.base.SessionBase.
Definition at line 98 of file signed_cookies.py.
    def clear_expired(cls):
        pass
create()
django.contrib.sessions.backends.signed_cookies.SessionStore.create (self)
To create a new key, set the modified flag so that the cookie is set
on the client for the current request.
Reimplemented from django.contrib.sessions.backends.base.SessionBase.
Definition at line 29 of file signed_cookies.py.
    def create(self):
        """
        To create a new key, set the modified flag so that the cookie is set
        on the client for the current request.
        """
        self.modified = True
Referenced by django.utils.tree.Node.__copy__(), django.utils.tree.Node.__deepcopy__(), django.db.models.query_utils.Q._combine(), django.db.models.sql.where.WhereNode.clone(), and django.db.models.sql.where.WhereNode.replace_expressions().
cycle_key()
django.contrib.sessions.backends.signed_cookies.SessionStore.cycle_key (self)
Keep the same data but with a new key. Call save() and it will
automatically save a cookie with a new key at the end of the request.
Reimplemented from django.contrib.sessions.backends.base.SessionBase.
Definition at line 75 of file signed_cookies.py.
    def cycle_key(self):
        """
        Keep the same data but with a new key. Call save() and it will
        automatically save a cookie with a new key at the end of the request.
        """
        self.save()
References django.contrib.sessions.backends.base.SessionBase.save.
delete()
django.contrib.sessions.backends.signed_cookies.SessionStore.delete (self, session_key = None)
To delete, clear the session key and the underlying data structure
and set the modified flag so that the cookie is set on the client for
the current request.
Reimplemented from django.contrib.sessions.backends.base.SessionBase.
Definition at line 62 of file signed_cookies.py.
    def delete(self, session_key=None):
        """
        To delete, clear the session key and the underlying data structure
        and set the modified flag so that the cookie is set on the client for
        the current request.
        """
        self._session_key = ""
        self._session_cache = {}
        self.modified = True
References django.contrib.sessions.backends.base.SessionBase._session_key.
Referenced by django.contrib.staticfiles.storage.HashedFilesMixin._post_process(), and django.views.generic.edit.DeletionMixin.post().
exists()
django.contrib.sessions.backends.signed_cookies.SessionStore.exists (self, session_key = None)
This method makes sense when you're talking to a shared resource, but
it doesn't matter when you're storing the information in the client's
cookie.
Reimplemented from django.contrib.sessions.backends.base.SessionBase.
Definition at line 51 of file signed_cookies.py.
    def exists(self, session_key=None):
        """
        This method makes sense when you're talking to a shared resource, but
        it doesn't matter when you're storing the information in the client's
        cookie.
        """
        return False
Referenced by django.contrib.staticfiles.storage.HashedFilesMixin._post_process(), django.db.models.sql.query.Query.has_results(), django.contrib.staticfiles.storage.HashedFilesMixin.hashed_name(), and django.core.files.storage.base.Storage.is_name_available().
load()
django.contrib.sessions.backends.signed_cookies.SessionStore.load (self)
Load the data from the key itself instead of fetching from some
external data store. Opposite of _get_session_key(), raise BadSignature
if signature fails.
Reimplemented from django.contrib.sessions.backends.base.SessionBase.
Definition at line 6 of file signed_cookies.py.
    def load(self):
        """
        Load the data from the key itself instead of fetching from some
        external data store. Opposite of _get_session_key(), raise BadSignature
        if signature fails.
        """
        try:
            return signing.loads(
                self.session_key,
                serializer=self.serializer,
                # This doesn't handle non-default expiry dates, see #19201
                max_age=self.get_session_cookie_age(),
                salt="django.contrib.sessions.backends.signed_cookies",
            )
        except Exception:
            # BadSignature, ValueError, or unpickling exceptions. If any of
            # these happen, reset the session.
            self.create()
        return {}
Referenced by PIL.Image.Image._copy(), PIL.Image.Image._dump(), PIL.Image.Image._ensure_mutable(), PIL.Image.Image._expand(), PIL.FliImagePlugin.FliImageFile._seek(), PIL.Image.Image.copy(), PIL.Image.Image.crop(), PIL.Image.Image.effect_spread(), PIL.Image.Image.entropy(), PIL.Image.Image.filter(), PIL.Image.Image.getbbox(), PIL.Image.Image.getchannel(), PIL.Image.Image.getcolors(), PIL.Image.Image.getdata(), PIL.Image.Image.getextrema(), PIL.Image.Image.getim(), PIL.Image.Image.getpalette(), PIL.Image.Image.getpixel(), PIL.Image.Image.getprojection(), PIL.Image.Image.histogram(), PIL.Image.Image.point(), PIL.Image.Image.putpalette(), PIL.Image.Image.putpixel(), PIL.Image.Image.quantize(), PIL.Image.Image.reduce(), PIL.Image.Image.remap_palette(), PIL.Image.Image.resize(), PIL.Image.Image.split(), PIL.Image.Image.tobitmap(), PIL.Image.Image.tobytes(), PIL.Image.Image.transform(), and PIL.Image.Image.transpose().
save()
django.contrib.sessions.backends.signed_cookies.SessionStore.save (self, must_create = False)
To save, get the session key as a securely signed string and then set
the modified flag so that the cookie is set on the client for the
current request.
Reimplemented from django.contrib.sessions.backends.base.SessionBase.
Definition at line 39 of file signed_cookies.py.
    def save(self, must_create=False):
        """
        To save, get the session key as a securely signed string and then set
        the modified flag so that the cookie is set on the client for the
        current request.
        """
        self._session_key = self._get_session_key()
        self.modified = True
Referenced by PIL.Image.Image._dump(), PIL.Image.Image._repr_image(), django.core.serializers.base.DeserializedObject.save_deferred_fields(), and pylint.pyreverse.writer.DiagramWriter.write().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/sessions/backends/signed_cookies.py