Read&Watch: colorama.ansitowin32.AnsiToWin32 Class Reference
colorama.ansitowin32.AnsiToWin32 Class Reference
Public Member Functions
__init__ (self, wrapped, convert=None, strip=None, autoreset=False)
should_wrap (self)
get_win32_calls (self)
write (self, text)
reset_all (self)
write_and_convert (self, text)
write_plain_text (self, text, start, end)
convert_ansi (self, paramstring, command)
extract_params (self, command, paramstring)
call_win32 (self, command, params)
convert_osc (self, text)
flush (self)
Public Attributes
wrapped = wrapped
autoreset = autoreset
stream = StreamWrapper(wrapped, self)
strip = strip
convert = convert
win32_calls = self.get_win32_calls()
on_stderr = self.wrapped is sys.stderr
Static Public Attributes
ANSI_CSI_RE = re.compile('\001?\033\\[((?:\\d|;)*)([a-zA-Z])\002?')
ANSI_OSC_RE = re.compile('\001?\033\\]([^\a]*)(\a)\002?')
Detailed Description
Implements a 'write()' method which, on Windows, will strip ANSI character
sequences from the text, and if outputting to a tty, will convert them into
win32 function calls.
Definition at line 72 of file ansitowin32.py.
Constructor & Destructor Documentation
__init__()
colorama.ansitowin32.AnsiToWin32.__init__ (self, wrapped, convert = None, strip = None, autoreset = False)
Definition at line 81 of file ansitowin32.py.
    def __init__(self, wrapped, convert=None, strip=None, autoreset=False):
        # The wrapped stream (normally sys.stdout or sys.stderr)
        self.wrapped = wrapped
        # should we reset colors to defaults after every .write()
        self.autoreset = autoreset
        # create the proxy wrapping our output stream
        self.stream = StreamWrapper(wrapped, self)
        on_windows = os.name == 'nt'
        # We test if the WinAPI works, because even if we are on Windows
        # we may be using a terminal that doesn't support the WinAPI
        # (e.g. Cygwin Terminal). In this case it's up to the terminal
        # to support the ANSI codes.
        conversion_supported = on_windows and winapi_test()
        try:
            fd = wrapped.fileno()
        except Exception:
            fd = -1
        system_has_native_ansi = not on_windows or enable_vt_processing(fd)
        have_tty = not self.stream.closed and self.stream.isatty()
        need_conversion = conversion_supported and not system_has_native_ansi
        # should we strip ANSI sequences from our output?
        if strip is None:
            strip = need_conversion or not have_tty
        self.strip = strip
        # should we should convert ANSI sequences into win32 calls?
        if convert is None:
            convert = need_conversion and have_tty
        self.convert = convert
        # dict of ansi codes to win32 functions and parameters
        self.win32_calls = self.get_win32_calls()
        # are we wrapping stderr?
        self.on_stderr = self.wrapped is sys.stderr
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
call_win32()
colorama.ansitowin32.AnsiToWin32.call_win32 (self, command, params)
Definition at line 238 of file ansitowin32.py.
    def call_win32(self, command, params):
        if command == 'm':
            for param in params:
                if param in self.win32_calls:
                    func_args = self.win32_calls[param]
                    func = func_args[0]
                    args = func_args[1:]
                    kwargs = dict(on_stderr=self.on_stderr)
                    func(*args, **kwargs)
        elif command in 'J':
            winterm.erase_screen(params[0], on_stderr=self.on_stderr)
        elif command in 'K':
            winterm.erase_line(params[0], on_stderr=self.on_stderr)
        elif command in 'Hf':     # cursor position - absolute
            winterm.set_cursor_position(params, on_stderr=self.on_stderr)
        elif command in 'ABCD':   # cursor position - relative
            n = params[0]
            # A - up, B - down, C - forward, D - back
            x, y = {'A': (0, -n), 'B': (0, n), 'C': (n, 0), 'D': (-n, 0)}[command]
            winterm.cursor_adjust(x, y, on_stderr=self.on_stderr)
References on_stderr, and win32_calls.
Referenced by convert_ansi(), and reset_all().
convert_ansi()
colorama.ansitowin32.AnsiToWin32.convert_ansi (self, paramstring, command)
Definition at line 214 of file ansitowin32.py.
    def convert_ansi(self, paramstring, command):
        if self.convert:
            params = self.extract_params(command, paramstring)
            self.call_win32(command, params)
References call_win32(), convert, and extract_params().
Referenced by write_and_convert().
convert_osc()
colorama.ansitowin32.AnsiToWin32.convert_osc (self, text)
Definition at line 260 of file ansitowin32.py.
    def convert_osc(self, text):
        for match in self.ANSI_OSC_RE.finditer(text):
            start, end = match.span()
            text = text[:start] + text[end:]
            paramstring, command = match.groups()
            if command == BEL:
                if paramstring.count(";") == 1:
                    params = paramstring.split(";")
                    # 0 - change title and icon (we will only change title)
                    # 1 - change icon (we don't support this)
                    # 2 - change title
                    if params[0] in '02':
                        winterm.set_title(params[1])
        return text
References ANSI_OSC_RE.
Referenced by write_and_convert().
extract_params()
colorama.ansitowin32.AnsiToWin32.extract_params (self, command, paramstring)
Definition at line 220 of file ansitowin32.py.
    def extract_params(self, command, paramstring):
        if command in 'Hf':
            params = tuple(int(p) if len(p) != 0 else 1 for p in paramstring.split(';'))
            while len(params) < 2:
                # defaults:
                params = params + (1,)
        else:
            params = tuple(int(p) for p in paramstring.split(';') if len(p) != 0)
            if len(params) == 0:
                # defaults:
                if command in 'JKm':
                    params = (0,)
                elif command in 'ABCD':
                    params = (1,)
        return params
Referenced by convert_ansi().
flush()
colorama.ansitowin32.AnsiToWin32.flush (self)
Definition at line 276 of file ansitowin32.py.
    def flush(self):
        self.wrapped.flush()
References flush(), and wrapped.
Referenced by pip._vendor.pygments.util.UnclosingTextIOWrapper.close(), flush(), write(), and write_plain_text().
get_win32_calls()
colorama.ansitowin32.AnsiToWin32.get_win32_calls (self)
Definition at line 131 of file ansitowin32.py.
    def get_win32_calls(self):
        if self.convert and winterm:
            return {
                AnsiStyle.RESET_ALL: (winterm.reset_all, ),
                AnsiStyle.BRIGHT: (winterm.style, WinStyle.BRIGHT),
                AnsiStyle.DIM: (winterm.style, WinStyle.NORMAL),
                AnsiStyle.NORMAL: (winterm.style, WinStyle.NORMAL),
                AnsiFore.BLACK: (winterm.fore, WinColor.BLACK),
                AnsiFore.RED: (winterm.fore, WinColor.RED),
                AnsiFore.GREEN: (winterm.fore, WinColor.GREEN),
                AnsiFore.YELLOW: (winterm.fore, WinColor.YELLOW),
                AnsiFore.BLUE: (winterm.fore, WinColor.BLUE),
                AnsiFore.MAGENTA: (winterm.fore, WinColor.MAGENTA),
                AnsiFore.CYAN: (winterm.fore, WinColor.CYAN),
                AnsiFore.WHITE: (winterm.fore, WinColor.GREY),
                AnsiFore.RESET: (winterm.fore, ),
                AnsiFore.LIGHTBLACK_EX: (winterm.fore, WinColor.BLACK, True),
                AnsiFore.LIGHTRED_EX: (winterm.fore, WinColor.RED, True),
                AnsiFore.LIGHTGREEN_EX: (winterm.fore, WinColor.GREEN, True),
                AnsiFore.LIGHTYELLOW_EX: (winterm.fore, WinColor.YELLOW, True),
                AnsiFore.LIGHTBLUE_EX: (winterm.fore, WinColor.BLUE, True),
                AnsiFore.LIGHTMAGENTA_EX: (winterm.fore, WinColor.MAGENTA, True),
                AnsiFore.LIGHTCYAN_EX: (winterm.fore, WinColor.CYAN, True),
                AnsiFore.LIGHTWHITE_EX: (winterm.fore, WinColor.GREY, True),
                AnsiBack.BLACK: (winterm.back, WinColor.BLACK),
                AnsiBack.RED: (winterm.back, WinColor.RED),
                AnsiBack.GREEN: (winterm.back, WinColor.GREEN),
                AnsiBack.YELLOW: (winterm.back, WinColor.YELLOW),
                AnsiBack.BLUE: (winterm.back, WinColor.BLUE),
                AnsiBack.MAGENTA: (winterm.back, WinColor.MAGENTA),
                AnsiBack.CYAN: (winterm.back, WinColor.CYAN),
                AnsiBack.WHITE: (winterm.back, WinColor.GREY),
                AnsiBack.RESET: (winterm.back, ),
                AnsiBack.LIGHTBLACK_EX: (winterm.back, WinColor.BLACK, True),
                AnsiBack.LIGHTRED_EX: (winterm.back, WinColor.RED, True),
                AnsiBack.LIGHTGREEN_EX: (winterm.back, WinColor.GREEN, True),
                AnsiBack.LIGHTYELLOW_EX: (winterm.back, WinColor.YELLOW, True),
                AnsiBack.LIGHTBLUE_EX: (winterm.back, WinColor.BLUE, True),
                AnsiBack.LIGHTMAGENTA_EX: (winterm.back, WinColor.MAGENTA, True),
                AnsiBack.LIGHTCYAN_EX: (winterm.back, WinColor.CYAN, True),
                AnsiBack.LIGHTWHITE_EX: (winterm.back, WinColor.GREY, True),
            }
        return dict()
References convert.
reset_all()
colorama.ansitowin32.AnsiToWin32.reset_all (self)
Definition at line 185 of file ansitowin32.py.
    def reset_all(self):
        if self.convert:
            self.call_win32('m', (0,))
        elif not self.strip and not self.stream.closed:
            self.wrapped.write(Style.RESET_ALL)
References call_win32(), convert, stream, strip, wrapped, and write().
Referenced by write().
should_wrap()
colorama.ansitowin32.AnsiToWin32.should_wrap (self)
True if this class is actually needed. If false, then the output
stream will not be affected, nor will win32 calls be issued, so
wrapping stdout is not actually required. This will generally be
False on non-Windows platforms, unless optional functionality like
autoreset has been requested using kwargs to init()
Definition at line 121 of file ansitowin32.py.
    def should_wrap(self):
        '''
        True if this class is actually needed. If false, then the output
        stream will not be affected, nor will win32 calls be issued, so
        wrapping stdout is not actually required. This will generally be
        False on non-Windows platforms, unless optional functionality like
        autoreset has been requested using kwargs to init()
        '''
        return self.convert or self.strip or self.autoreset
References autoreset, convert, and strip.
write()
colorama.ansitowin32.AnsiToWin32.write (self, text)
Definition at line 175 of file ansitowin32.py.
    def write(self, text):
        if self.strip or self.convert:
            self.write_and_convert(text)
        else:
            self.wrapped.write(text)
            self.wrapped.flush()
        if self.autoreset:
            self.reset_all()
References autoreset, convert, flush(), reset_all(), strip, wrapped, write(), and write_and_convert().
Referenced by pylint.reporters.ureports.text_writer.TextWriter.default_table(), reset_all(), pylint.reporters.ureports.text_writer.TextWriter.visit_text(), write(), write_plain_text(), django.http.response.HttpResponse.writelines(), pylint.reporters.ureports.base_writer.BaseWriter.writeln(), and django.utils.feedgenerator.SyndicationFeed.writeString().
write_and_convert()
colorama.ansitowin32.AnsiToWin32.write_and_convert (self, text)
Write the given text to our wrapped stream, stripping any ANSI
sequences from the text, and optionally converting them into win32
calls.
Definition at line 192 of file ansitowin32.py.
    def write_and_convert(self, text):
        '''
        Write the given text to our wrapped stream, stripping any ANSI
        sequences from the text, and optionally converting them into win32
        calls.
        '''
        cursor = 0
        text = self.convert_osc(text)
        for match in self.ANSI_CSI_RE.finditer(text):
            start, end = match.span()
            self.write_plain_text(text, cursor, start)
            self.convert_ansi(*match.groups())
            cursor = end
        self.write_plain_text(text, cursor, len(text))
References ANSI_CSI_RE, convert_ansi(), convert_osc(), and write_plain_text().
Referenced by write().
write_plain_text()
colorama.ansitowin32.AnsiToWin32.write_plain_text (self, text, start, end)
Definition at line 208 of file ansitowin32.py.
    def write_plain_text(self, text, start, end):
        if start < end:
            self.wrapped.write(text[start:end])
            self.wrapped.flush()
References flush(), wrapped, and write().
Referenced by write_and_convert().
Member Data Documentation
ANSI_CSI_RE
colorama.ansitowin32.AnsiToWin32.ANSI_CSI_RE = re.compile('\001?\033\\[((?:\\d|;)*)([a-zA-Z])\002?') static
Definition at line 78 of file ansitowin32.py.
Referenced by write_and_convert().
ANSI_OSC_RE
colorama.ansitowin32.AnsiToWin32.ANSI_OSC_RE = re.compile('\001?\033\\]([^\a]*)(\a)\002?') static
Definition at line 79 of file ansitowin32.py.
Referenced by convert_osc().
autoreset
colorama.ansitowin32.AnsiToWin32.autoreset = autoreset
Definition at line 86 of file ansitowin32.py.
Referenced by should_wrap(), and write().
convert
colorama.ansitowin32.AnsiToWin32.convert = convert
Definition at line 113 of file ansitowin32.py.
Referenced by convert_ansi(), pip._vendor.pygments.filters.KeywordCaseFilter.filter(), get_win32_calls(), sqlparse.filters.tokens._CaseFilter.process(), sqlparse.filters.tokens.IdentifierCaseFilter.process(), PIL.Image.Image.reduce(), reset_all(), PIL.Image.Image.resize(), should_wrap(), PIL.Image.Image.transform(), and write().
on_stderr
colorama.ansitowin32.AnsiToWin32.on_stderr = self.wrapped is sys.stderr
Definition at line 119 of file ansitowin32.py.
Referenced by call_win32().
stream
colorama.ansitowin32.AnsiToWin32.stream = StreamWrapper(wrapped, self)
Definition at line 89 of file ansitowin32.py.
Referenced by pip._vendor.urllib3.response.HTTPResponse.__iter__(), urllib3.response.HTTPResponse.__iter__(), dotenv.main.DotEnv._get_stream(), pip._internal.metadata.base.MemoryWheel.as_zipfile(), dill.session._PeekableReader.close(), django.core.mail.backends.filebased.EmailBackend.close(), django.contrib.gis.serializers.geojson.Serializer.end_serialization(), django.core.serializers.json.Serializer.end_serialization(), yaml.emitter.Emitter.expect_stream_start(), yaml.emitter.Emitter.flush_stream(), yaml.reader.Reader.get_mark(), django.core.serializers.base.Serializer.getvalue(), PIL.FpxImagePlugin.FpxImageFile.load(), pip._vendor.requests.sessions.Session.merge_environment_settings(), requests.sessions.Session.merge_environment_settings(), django.core.mail.backends.filebased.EmailBackend.open(), dill.session._PeekableReader.peek(), dill.session._PeekableReader.read(), dill.session._PeekableReader.readline(), reset_all(), pip._vendor.requests.sessions.Session.send(), requests.sessions.Session.send(), django.core.mail.backends.console.EmailBackend.send_messages(), django.core.serializers.json.Serializer.start_serialization(), dill.session._PeekableReader.tell(), yaml.reader.Reader.update(), yaml.reader.Reader.update_raw(), yaml.emitter.Emitter.write_double_quoted(), yaml.emitter.Emitter.write_folded(), yaml.emitter.Emitter.write_indent(), yaml.emitter.Emitter.write_indicator(), yaml.emitter.Emitter.write_line_break(), yaml.emitter.Emitter.write_literal(), django.core.mail.backends.console.EmailBackend.write_message(), django.core.mail.backends.filebased.EmailBackend.write_message(), yaml.emitter.Emitter.write_plain(), yaml.emitter.Emitter.write_single_quoted(), yaml.emitter.Emitter.write_stream_start(), yaml.emitter.Emitter.write_tag_directive(), and yaml.emitter.Emitter.write_version_directive().
strip
colorama.ansitowin32.AnsiToWin32.strip = strip
Definition at line 108 of file ansitowin32.py.
Referenced by reset_all(), should_wrap(), and write().
win32_calls
colorama.ansitowin32.AnsiToWin32.win32_calls = self.get_win32_calls()
Definition at line 116 of file ansitowin32.py.
Referenced by call_win32().
wrapped
colorama.ansitowin32.AnsiToWin32.wrapped = wrapped
Definition at line 83 of file ansitowin32.py.
Referenced by django.test.utils.override_settings.disable(), flush(), reset_all(), write(), and write_plain_text().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/colorama/ansitowin32.py