Read&Watch: PIL.ImageQt.ImageQt Class Reference
PIL.ImageQt.ImageQt Class Reference
Public Member Functions
None __init__ (self, Image.Image|str|QByteArray im)
Detailed Description
Definition at line 185 of file ImageQt.py.
Constructor & Destructor Documentation
__init__()
None PIL.ImageQt.ImageQt.__init__ (self, Image.Image | str | QByteArray im)
An PIL image wrapper for Qt.  This is a subclass of PyQt's QImage
class.
:param im: A PIL Image object, or a file name (given either as
    Python string or a PyQt string object).
Definition at line 186 of file ImageQt.py.
        def __init__(self, im: Image.Image | str | QByteArray) -> None:
            """
            An PIL image wrapper for Qt.  This is a subclass of PyQt's QImage
            class.
            :param im: A PIL Image object, or a file name (given either as
                Python string or a PyQt string object).
            """
            im_data = _toqclass_helper(im)
            # must keep a reference, or Qt will crash!
            # All QImage constructors that take data operate on an existing
            # buffer, so this buffer has to hang on for the life of the image.
            # Fixes https://github.com/python-pillow/Pillow/issues/1370
            self.__data = im_data["data"]
            super().__init__(
                self.__data,
                im_data["size"][0],
                im_data["size"][1],
                im_data["format"],
            )
            if im_data["colortable"]:
                self.setColorTable(im_data["colortable"])
References __data, __init__(), and PIL.ImageQt._toqclass_helper().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/PIL/ImageQt.py