Read&Watch: pip._vendor.distlib.locators.DistPathLocator Class Reference
pip._vendor.distlib.locators.DistPathLocator Class Reference
Public Member Functions
__init__ (self, distpath, **kwargs)
Public Member Functions inherited from pip._vendor.distlib.locators.Locator
__init__ (self, scheme='default')
get_errors (self)
clear_errors (self)
clear_cache (self)
get_distribution_names (self)
get_project (self, name)
score_url (self, url)
prefer_url (self, url1, url2)
split_filename (self, filename, project_name)
convert_url_to_download_info (self, url, project_name)
locate (self, requirement, prereleases=False)
Public Attributes
distpath = distpath
Public Attributes inherited from pip._vendor.distlib.locators.Locator
opener = build_opener(RedirectHandler())
matcher = None
errors = queue.Queue()
Protected Member Functions
_get_project (self, name)
Protected Member Functions inherited from pip._vendor.distlib.locators.Locator
_get_scheme (self)
_set_scheme (self, value)
_get_digest (self, info)
_update_version_data (self, result, info)
Additional Inherited Members
Static Public Attributes inherited from pip._vendor.distlib.locators.Locator
tuple source_extensions = ('.tar.gz', '.tar.bz2', '.tar', '.zip', '.tgz', '.tbz')
tuple binary_extensions = ('.egg', '.exe', '.whl')
tuple excluded_extensions = ('.pdf',)
wheel_tags = None
tuple downloadable_extensions = source_extensions + ('.whl',)
Protected Attributes inherited from pip._vendor.distlib.locators.Locator
dict _cache = {}
_scheme = value
Properties inherited from pip._vendor.distlib.locators.Locator
scheme = property(_get_scheme, _set_scheme)
Detailed Description
This locator finds installed distributions in a path. It can be useful for
adding to an :class:`AggregatingLocator`.
Definition at line 932 of file locators.py.
Constructor & Destructor Documentation
__init__()
pip._vendor.distlib.locators.DistPathLocator.__init__ (self, distpath, ** kwargs)
Initialise an instance.
:param distpath: A :class:`DistributionPath` instance to search.
Definition at line 938 of file locators.py.
    def __init__(self, distpath, **kwargs):
        """
        Initialise an instance.
        :param distpath: A :class:`DistributionPath` instance to search.
        """
        super(DistPathLocator, self).__init__(**kwargs)
        assert isinstance(distpath, DistributionPath)
        self.distpath = distpath
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Function Documentation
_get_project()
pip._vendor.distlib.locators.DistPathLocator._get_project (self, name) protected
For a given project, get a dictionary mapping available versions to Distribution
instances.
This should be implemented in subclasses.
If called from a locate() request, self.matcher will be set to a
matcher for the requirement to satisfy, otherwise it will be None.
Reimplemented from pip._vendor.distlib.locators.Locator.
Definition at line 948 of file locators.py.
    def _get_project(self, name):
        dist = self.distpath.get_distribution(name)
        if dist is None:
            result = {'urls': {}, 'digests': {}}
        else:
            result = {
                dist.version: dist,
                'urls': {
                    dist.version: set([dist.source_url])
                },
                'digests': {
                    dist.version: set([None])
                }
            }
        return result
References distpath.
Member Data Documentation
distpath
pip._vendor.distlib.locators.DistPathLocator.distpath = distpath
Definition at line 946 of file locators.py.
Referenced by _get_project().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/distlib/locators.py