Read&Watch: django.utils.deprecation.RenameMethodsBase Class Reference
django.utils.deprecation.RenameMethodsBase Class Reference
Public Member Functions
__new__ (cls, name, bases, attrs)
Static Public Attributes
tuple renamed_methods = ()
Detailed Description
Handles the deprecation paths when renaming a method.
It does the following:
    1) Define the new method if missing and complain about it.
    2) Define the old method if missing.
    3) Complain whenever an old method is called.
See #15363 for more details.
Definition at line 40 of file deprecation.py.
Member Function Documentation
__new__()
django.utils.deprecation.RenameMethodsBase.__new__ (cls, name, bases, attrs)
Definition at line 54 of file deprecation.py.
    def __new__(cls, name, bases, attrs):
        new_class = super().__new__(cls, name, bases, attrs)
        for base in inspect.getmro(new_class):
            class_name = base.__name__
            for renamed_method in cls.renamed_methods:
                old_method_name = renamed_method[0]
                old_method = base.__dict__.get(old_method_name)
                new_method_name = renamed_method[1]
                new_method = base.__dict__.get(new_method_name)
                deprecation_warning = renamed_method[2]
                wrapper = warn_about_renamed_method(class_name, *renamed_method)
                # Define the new method if missing and complain about it
                if not new_method and old_method:
                    warnings.warn(
                        "`%s.%s` method should be renamed `%s`."
                        % (class_name, old_method_name, new_method_name),
                        deprecation_warning,
                        2,
                    )
                    setattr(base, new_method_name, old_method)
                    setattr(base, old_method_name, wrapper(old_method))
                # Define the old method as a wrapped call to the new method.
                if not old_method and new_method:
                    setattr(base, old_method_name, wrapper(new_method))
        return new_class
References __new__(), and renamed_methods.
Referenced by __new__(), apscheduler.triggers.combining.BaseCombiningTrigger.__setstate__(), pip._vendor.rich.style.Style._add(), pip._vendor.rich.style.Style.clear_meta_and_links(), yaml.constructor.SafeConstructor.construct_yaml_object(), pip._vendor.rich.style.Style.copy(), pip._vendor.rich.style.Style.from_color(), pip._vendor.rich.json.JSON.from_data(), pip._vendor.rich.style.Style.from_meta(), yaml.constructor.FullConstructor.make_python_instance(), pip._vendor.rich.style.Style.update_link(), and pip._vendor.rich.style.Style.without_color().
Member Data Documentation
renamed_methods
tuple django.utils.deprecation.RenameMethodsBase.renamed_methods = () static
Definition at line 52 of file deprecation.py.
Referenced by __new__().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/utils/deprecation.py