Read&Watch: django.contrib.flatpages.middleware.FlatpageFallbackMiddleware Class Reference
django.contrib.flatpages.middleware.FlatpageFallbackMiddleware Class Reference
Public Member Functions
process_response (self, request, response)
Public Member Functions inherited from django.utils.deprecation.MiddlewareMixin
__init__ (self, get_response)
__repr__ (self)
__call__ (self, request)
__acall__ (self, request)
Additional Inherited Members
Public Attributes inherited from django.utils.deprecation.MiddlewareMixin
get_response = get_response
async_mode = iscoroutinefunction(self.get_response)
Static Public Attributes inherited from django.utils.deprecation.MiddlewareMixin
bool sync_capable = True
bool async_capable = True
Detailed Description
Definition at line 7 of file middleware.py.
Member Function Documentation
process_response()
django.contrib.flatpages.middleware.FlatpageFallbackMiddleware.process_response (self, request, response)
Definition at line 8 of file middleware.py.
    def process_response(self, request, response):
        if response.status_code != 404:
            return response  # No need to check for a flatpage for non-404 responses.
        try:
            return flatpage(request, request.path_info)
        # Return the original response if any errors happened. Because this
        # is a middleware, we can't assume the errors will be caught elsewhere.
        except Http404:
            return response
        except Exception:
            if settings.DEBUG:
                raise
            return response
Referenced by django.utils.deprecation.MiddlewareMixin.__acall__(), django.utils.deprecation.MiddlewareMixin.__call__(), and pip._vendor.rich.prompt.PromptBase.__call__().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/flatpages/middleware.py