Read&Watch: tomlkit.items.Null Class Reference
tomlkit.items.Null Class Reference
Public Member Functions
None __init__ (self)
None unwrap (self)
int discriminant (self)
None value (self)
str as_string (self)
Public Member Functions inherited from tomlkit.items.Item
None __init__ (self, Trivia trivia)
Trivia trivia (self)
Item comment (self, str comment)
Item indent (self, int indent)
bool is_boolean (self)
bool is_table (self)
bool is_inline_table (self)
bool is_aot (self)
__reduce__ (self)
__reduce_ex__ (self, protocol)
Protected Member Functions
tuple _getstate (self, protocol=3)
Additional Inherited Members
Protected Attributes inherited from tomlkit.items.Item
Trivia _trivia = trivia
Detailed Description
A null item.
Definition at line 1937 of file items.py.
Constructor & Destructor Documentation
__init__()
None tomlkit.items.Null.__init__ (self)
Definition at line 1942 of file items.py.
    def __init__(self) -> None:
        super().__init__(Trivia(trail=""))
References __init__().
Referenced by __init__().
Member Function Documentation
_getstate()
tuple tomlkit.items.Null._getstate (self, protocol = 3) protected
Reimplemented from tomlkit.items.Item.
Definition at line 1959 of file items.py.
    def _getstate(self, protocol=3) -> tuple:
        return ()
as_string()
str tomlkit.items.Null.as_string (self)
The TOML representation
Reimplemented from tomlkit.items.Item.
Definition at line 1956 of file items.py.
    def as_string(self) -> str:
        return ""
discriminant()
int tomlkit.items.Null.discriminant (self)
Reimplemented from tomlkit.items.Item.
Definition at line 1949 of file items.py.
    def discriminant(self) -> int:
        return -1
unwrap()
None tomlkit.items.Null.unwrap (self)
Returns as pure python object (ppo)
Reimplemented from tomlkit.items.Item.
Definition at line 1945 of file items.py.
    def unwrap(self) -> None:
        return None
value()
None tomlkit.items.Null.value (self)
Reimplemented from tomlkit.items.Item.
Definition at line 1953 of file items.py.
    def value(self) -> None:
        return None
Referenced by pip._internal.models.link.LinkHash.as_hashes(), pip._internal.models.link.LinkHash.is_hash_allowed(), and tomlkit.items.StringType.unit().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/tomlkit/items.py