Read&Watch: django.contrib.flatpages.sitemaps.FlatPageSitemap Class Reference
django.contrib.flatpages.sitemaps.FlatPageSitemap Class Reference
Public Member Functions
items (self)
Public Member Functions inherited from django.contrib.sitemaps.Sitemap
get_languages_for_item (self, item)
paginator (self)
location (self, item)
get_protocol (self, protocol=None)
get_domain (self, site=None)
get_urls (self, page=1, site=None, protocol=None)
get_latest_lastmod (self)
Additional Inherited Members
Public Attributes inherited from django.contrib.sitemaps.Sitemap
lastmod
latest_lastmod = latest_lastmod
Static Public Attributes inherited from django.contrib.sitemaps.Sitemap
int limit = 50000
protocol = None
bool i18n = False
languages = None
bool alternates = False
bool x_default = False
Protected Member Functions inherited from django.contrib.sitemaps.Sitemap
_get (self, name, item, default=None)
_languages (self)
_items (self)
_location (self, item, force_lang_code=None)
_urls (self, page, protocol, domain)
Detailed Description
Definition at line 6 of file sitemaps.py.
Member Function Documentation
items()
django.contrib.flatpages.sitemaps.FlatPageSitemap.items (self)
Reimplemented from django.contrib.sitemaps.Sitemap.
Definition at line 7 of file sitemaps.py.
    def items(self):
        if not django_apps.is_installed("django.contrib.sites"):
            raise ImproperlyConfigured(
                "FlatPageSitemap requires django.contrib.sites, which isn't installed."
            )
        Site = django_apps.get_model("sites.Site")
        current_site = Site.objects.get_current()
        return current_site.flatpage_set.filter(registration_required=False)
Referenced by PIL.PdfParser.PdfDict.__bytes__(), django.utils.datastructures.CaseInsensitiveMapping.__eq__(), pip._vendor.distlib.compat.OrderedDict.__eq__(), pip._vendor.distlib.compat.OrderedDict.__repr__(), pip._vendor.requests.structures.CaseInsensitiveDict.__repr__(), requests.structures.CaseInsensitiveDict.__repr__(), django.contrib.sitemaps.Sitemap._items(), django.forms.utils.ErrorDict.as_data(), django.forms.utils.ErrorDict.get_context(), django.forms.utils.ErrorDict.get_json_data(), tomlkit.items.Table.is_super_table(), PIL.TiffImagePlugin.ImageFileDirectory_v2.named(), PIL.Image.Exif.tobytes(), tomlkit.container.Container.unwrap(), and tomlkit.items.AbstractTable.unwrap().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/flatpages/sitemaps.py