Read&Watch: isort.exceptions.MissingSection Class Reference
isort.exceptions.MissingSection Class Reference
Public Member Functions
__init__ (self, str import_module, str section)
Public Member Functions inherited from isort.exceptions.ISortError
__reduce__ (self)
Detailed Description
Raised when isort encounters an import that matches a section that is not defined
Definition at line 189 of file exceptions.py.
Constructor & Destructor Documentation
__init__()
isort.exceptions.MissingSection.__init__ (self, str import_module, str section)
Definition at line 192 of file exceptions.py.
    def __init__(self, import_module: str, section: str):
        super().__init__(
            f"Found {import_module} import while parsing, but {section} was not included "
            "in the `sections` setting of your config. Please add it before continuing\n"
            "See https://pycqa.github.io/isort/#custom-sections-and-ordering "
            "for more info."
        )
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/isort/exceptions.py