Read&Watch: django.db.models.fields.files.ImageFieldFile Class Reference
django.db.models.fields.files.ImageFieldFile Class Reference
Public Member Functions
delete (self, save=True)
Public Member Functions inherited from django.core.files.images.ImageFile
width (self)
height (self)
Public Member Functions inherited from django.core.files.base.File
__init__ (self, file, name=None)
__str__ (self)
__repr__ (self)
__bool__ (self)
__len__ (self)
chunks (self, chunk_size=None)
multiple_chunks (self, chunk_size=None)
__iter__ (self)
__enter__ (self)
__exit__ (self, exc_type, exc_value, tb)
Public Member Functions inherited from django.core.files.utils.FileProxyMixin
readable (self)
writable (self)
seekable (self)
__iter__ (self)
Public Member Functions inherited from django.db.models.fields.files.FieldFile
__init__ (self, instance, field, name)
__eq__ (self, other)
__hash__ (self)
path (self)
url (self)
size (self)
open (self, mode="rb")
save (self, name, content, save=True)
closed (self)
close (self)
__getstate__ (self)
__setstate__ (self, state)
Public Member Functions inherited from django.db.models.utils.AltersData
__init_subclass__ (cls, **kwargs)
Protected Member Functions
_set_instance_attribute (self, name, content)
Protected Member Functions inherited from django.core.files.images.ImageFile
_get_image_dimensions (self)
Protected Member Functions inherited from django.db.models.fields.files.FieldFile
_require_file (self)
_get_file (self)
_set_file (self, file)
_del_file (self)
Additional Inherited Members
Public Attributes inherited from django.core.files.base.File
name = name
mode = file.mode
Public Attributes inherited from django.core.files.utils.FileProxyMixin
file
Public Attributes inherited from django.db.models.fields.files.FieldFile
instance = instance
field = field
storage = field.storage
Static Public Attributes inherited from django.core.files.base.File
int DEFAULT_CHUNK_SIZE = 64 * 2**10
Static Public Attributes inherited from django.db.models.fields.files.FieldFile
alters_data
Protected Attributes inherited from django.core.files.images.ImageFile
_dimensions_cache = get_image_dimensions(self, close=close)
Protected Attributes inherited from django.db.models.fields.files.FieldFile
bool _committed = True
_file = self.storage.open(self.name, "rb")
Properties inherited from django.core.files.utils.FileProxyMixin
encoding = property(lambda self: self.file.encoding)
fileno = property(lambda self: self.file.fileno)
flush = property(lambda self: self.file.flush)
isatty = property(lambda self: self.file.isatty)
newlines = property(lambda self: self.file.newlines)
read = property(lambda self: self.file.read)
readinto = property(lambda self: self.file.readinto)
readline = property(lambda self: self.file.readline)
readlines = property(lambda self: self.file.readlines)
seek = property(lambda self: self.file.seek)
tell = property(lambda self: self.file.tell)
truncate = property(lambda self: self.file.truncate)
write = property(lambda self: self.file.write)
writelines = property(lambda self: self.file.writelines)
Properties inherited from django.db.models.fields.files.FieldFile
file = property(_get_file, _set_file, _del_file)
Detailed Description
Definition at line 403 of file files.py.
Member Function Documentation
_set_instance_attribute()
django.db.models.fields.files.ImageFieldFile._set_instance_attribute (self, name, content) protected
Reimplemented from django.db.models.fields.files.FieldFile.
Definition at line 404 of file files.py.
    def _set_instance_attribute(self, name, content):
        setattr(self.instance, self.field.attname, content)
        # Update the name in case generate_filename() or storage.save() changed
        # it, but bypass the descriptor to avoid re-reading the file.
        self.instance.__dict__[self.field.attname] = self.name
delete()
django.db.models.fields.files.ImageFieldFile.delete (self, save = True)
Reimplemented from django.db.models.fields.files.FieldFile.
Definition at line 410 of file files.py.
    def delete(self, save=True):
        # Clear the image dimensions cache
        if hasattr(self, "_dimensions_cache"):
            del self._dimensions_cache
        super().delete(save)
References django.core.files.images.ImageFile._dimensions_cache, and delete().
Referenced by django.contrib.staticfiles.storage.HashedFilesMixin._post_process(), delete(), and django.views.generic.edit.DeletionMixin.post().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/db/models/fields/files.py