Read&Watch: django.db.migrations.operations.models.AlterIndexTogether Class Reference
django.db.migrations.operations.models.AlterIndexTogether Class Reference
Public Member Functions
__init__ (self, name, index_together)
Public Member Functions inherited from django.db.migrations.operations.models.AlterTogetherOptionOperation
__init__ (self, name, option_value)
option_value (self)
deconstruct (self)
state_forwards (self, app_label, state)
database_forwards (self, app_label, schema_editor, from_state, to_state)
database_backwards (self, app_label, schema_editor, from_state, to_state)
references_field (self, model_name, name, app_label)
describe (self)
migration_name_fragment (self)
can_reduce_through (self, operation, app_label)
Public Member Functions inherited from django.db.migrations.operations.models.ModelOptionOperation
reduce (self, operation, app_label)
Public Member Functions inherited from django.db.migrations.operations.models.ModelOperation
__init__ (self, name)
name_lower (self)
references_model (self, name, app_label)
Public Member Functions inherited from django.db.migrations.operations.base.Operation
__new__ (cls, *args, **kwargs)
formatted_description (self)
allow_migrate_model (self, connection_alias, model)
__repr__ (self)
Additional Inherited Members
Public Attributes inherited from django.db.migrations.operations.models.AlterTogetherOptionOperation
option_value
Public Attributes inherited from django.db.migrations.operations.models.ModelOperation
name = name
Static Public Attributes inherited from django.db.migrations.operations.models.AlterTogetherOptionOperation
self.option_value}, option_name = None
Static Public Attributes inherited from django.db.migrations.operations.base.Operation
bool reversible = True
bool reduces_to_sql = True
bool atomic = False
bool elidable = False
list serialization_expand_args = []
category = None
Protected Attributes inherited from django.db.migrations.operations.base.Operation
tuple _constructor_args = (args, kwargs)
Detailed Description
Change the value of index_together to the target one.
Input value of index_together must be a set of tuples.
Definition at line 718 of file models.py.
Constructor & Destructor Documentation
__init__()
django.db.migrations.operations.models.AlterIndexTogether.__init__ (self, name, index_together)
Definition at line 726 of file models.py.
    def __init__(self, name, index_together):
        super().__init__(name, index_together)
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/db/migrations/operations/models.py