Read&Watch: pip._vendor.packaging._parser.Variable Class Reference
pip._vendor.packaging._parser.Variable Class Reference
Public Member Functions
str serialize (self)
Public Member Functions inherited from pip._vendor.packaging._parser.Node
None __init__ (self, str value)
str __str__ (self)
str __repr__ (self)
Additional Inherited Members
Public Attributes inherited from pip._vendor.packaging._parser.Node
value = value
Detailed Description
Definition at line 29 of file _parser.py.
Member Function Documentation
serialize()
str pip._vendor.packaging._parser.Variable.serialize (self)
Reimplemented from pip._vendor.packaging._parser.Node.
Definition at line 30 of file _parser.py.
    def serialize(self) -> str:
        return str(self)
Referenced by pylint.reporters.json_reporter.JSON2Reporter.display_messages(), pylint.reporters.json_reporter.JSONReporter.display_messages(), and yaml.representer.BaseRepresenter.represent().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/packaging/_parser.py