Read&Watch: django.contrib.postgres.indexes.GinIndex Class Reference
django.contrib.postgres.indexes.GinIndex Class Reference
Public Member Functions
__init__ (self, *expressions, fastupdate=None, gin_pending_list_limit=None, **kwargs)
deconstruct (self)
get_with_params (self)
Public Member Functions inherited from django.contrib.postgres.indexes.PostgresIndex
max_name_length (self)
create_sql (self, model, schema_editor, using="", **kwargs)
check_supported (self, schema_editor)
Public Member Functions inherited from django.db.models.indexes.Index
__init__ (self, *expressions, fields=(), name=None, db_tablespace=None, opclasses=(), condition=None, include=None)
contains_expressions (self)
remove_sql (self, model, schema_editor, **kwargs)
clone (self)
set_name_with_model (self, model)
__repr__ (self)
__eq__ (self, other)
Public Attributes
fastupdate = fastupdate
gin_pending_list_limit = gin_pending_list_limit
Public Attributes inherited from django.db.models.indexes.Index
fields = list(fields)
list fields_orders
str name = name or ""
db_tablespace = db_tablespace
opclasses = opclasses
condition = condition
include = tuple(include) if include else ()
expressions
Additional Inherited Members
Static Public Attributes inherited from django.db.models.indexes.Index
str suffix = "idx"
Protected Member Functions inherited from django.db.models.indexes.Index
_get_condition_sql (self, model, schema_editor)
Detailed Description
Definition at line 144 of file indexes.py.
Constructor & Destructor Documentation
__init__()
django.contrib.postgres.indexes.GinIndex.__init__ (self, * expressions, fastupdate = None, gin_pending_list_limit = None, ** kwargs)
Definition at line 147 of file indexes.py.
    ):
        self.fastupdate = fastupdate
        self.gin_pending_list_limit = gin_pending_list_limit
        super().__init__(*expressions, **kwargs)
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
deconstruct()
django.contrib.postgres.indexes.GinIndex.deconstruct (self)
Reimplemented from django.db.models.indexes.Index.
Definition at line 154 of file indexes.py.
    def deconstruct(self):
        path, args, kwargs = super().deconstruct()
        if self.fastupdate is not None:
            kwargs["fastupdate"] = self.fastupdate
        if self.gin_pending_list_limit is not None:
            kwargs["gin_pending_list_limit"] = self.gin_pending_list_limit
        return path, args, kwargs
References deconstruct(), fastupdate, and gin_pending_list_limit.
Referenced by django.db.models.indexes.Index.__eq__(), django.db.models.constraints.BaseConstraint.clone(), django.db.models.fields.Field.clone(), django.db.models.indexes.Index.clone(), deconstruct(), and django.db.models.query_utils.Q.identity().
get_with_params()
django.contrib.postgres.indexes.GinIndex.get_with_params (self)
Reimplemented from django.contrib.postgres.indexes.PostgresIndex.
Definition at line 162 of file indexes.py.
    def get_with_params(self):
        with_params = []
        if self.gin_pending_list_limit is not None:
            with_params.append(
                "gin_pending_list_limit = %d" % self.gin_pending_list_limit
            )
        if self.fastupdate is not None:
            with_params.append("fastupdate = %s" % ("on" if self.fastupdate else "off"))
        return with_params
References fastupdate, and gin_pending_list_limit.
Member Data Documentation
fastupdate
django.contrib.postgres.indexes.GinIndex.fastupdate = fastupdate
Definition at line 150 of file indexes.py.
Referenced by deconstruct(), and get_with_params().
gin_pending_list_limit
django.contrib.postgres.indexes.GinIndex.gin_pending_list_limit = gin_pending_list_limit
Definition at line 151 of file indexes.py.
Referenced by deconstruct(), and get_with_params().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/postgres/indexes.py