Read&Watch: PIL.ImageDraw2.Draw Class Reference
PIL.ImageDraw2.Draw Class Reference
Public Member Functions
None __init__ (self, Image.Image|str image, tuple[int, int]|list[int]|None size=None, float|tuple[float,...]|str|None color=None)
Image.Image flush (self)
None render (self, str op, Coords xy, Pen|Brush|None pen, Brush|Pen|None brush=None, **Any kwargs)
None settransform (self, tuple[float, float] offset)
None arc (self, Coords xy, Pen|Brush|None pen, float start, float end, *Any options)
None chord (self, Coords xy, Pen|Brush|None pen, float start, float end, *Any options)
None ellipse (self, Coords xy, Pen|Brush|None pen, *Any options)
None line (self, Coords xy, Pen|Brush|None pen, *Any options)
None pieslice (self, Coords xy, Pen|Brush|None pen, float start, float end, *Any options)
None polygon (self, Coords xy, Pen|Brush|None pen, *Any options)
None rectangle (self, Coords xy, Pen|Brush|None pen, *Any options)
None text (self, tuple[float, float] xy, AnyStr text, Font font)
tuple[float, float, float, float] textbbox (self, tuple[float, float] xy, AnyStr text, Font font)
float textlength (self, AnyStr text, Font font)
Public Attributes
draw = ImageDraw.Draw(image)
image = image
tuple[float, float, float, float, float, float]|None transform = None
Detailed Description
(Experimental) WCK-style drawing interface
Definition at line 59 of file ImageDraw2.py.
Constructor & Destructor Documentation
__init__()
None PIL.ImageDraw2.Draw.__init__ (self, Image.Image | str image, tuple[int, int] | list[int] | None size = None, float | tuple[float, ...] | str | None color = None)
Definition at line 64 of file ImageDraw2.py.
    ) -> None:
        if isinstance(image, str):
            if size is None:
                msg = "If image argument is mode string, size must be a list or tuple"
                raise ValueError(msg)
            image = Image.new(image, size, color)
        self.draw = ImageDraw.Draw(image)
        self.image = image
        self.transform: tuple[float, float, float, float, float, float] | None = None
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
arc()
None PIL.ImageDraw2.Draw.arc (self, Coords xy, Pen | Brush | None pen, float start, float end, *Any options)
Draws an arc (a portion of a circle outline) between the start and end
angles, inside the given bounding box.
.. seealso:: :py:meth:`PIL.ImageDraw.ImageDraw.arc`
Definition at line 123 of file ImageDraw2.py.
    ) -> None:
        """
        Draws an arc (a portion of a circle outline) between the start and end
        angles, inside the given bounding box.
        .. seealso:: :py:meth:`PIL.ImageDraw.ImageDraw.arc`
        """
        self.render("arc", xy, pen, *options, start=start, end=end)
chord()
None PIL.ImageDraw2.Draw.chord (self, Coords xy, Pen | Brush | None pen, float start, float end, *Any options)
Same as :py:meth:`~PIL.ImageDraw2.Draw.arc`, but connects the end points
with a straight line.
.. seealso:: :py:meth:`PIL.ImageDraw.ImageDraw.chord`
Definition at line 139 of file ImageDraw2.py.
    ) -> None:
        """
        Same as :py:meth:`~PIL.ImageDraw2.Draw.arc`, but connects the end points
        with a straight line.
        .. seealso:: :py:meth:`PIL.ImageDraw.ImageDraw.chord`
        """
        self.render("chord", xy, pen, *options, start=start, end=end)
ellipse()
None PIL.ImageDraw2.Draw.ellipse (self, Coords xy, Pen | Brush | None pen, *Any options)
Draws an ellipse inside the given bounding box.
.. seealso:: :py:meth:`PIL.ImageDraw.ImageDraw.ellipse`
Definition at line 155 of file ImageDraw2.py.
    def ellipse(self, xy: Coords, pen: Pen | Brush | None, *options: Any) -> None:
        """
        Draws an ellipse inside the given bounding box.
        .. seealso:: :py:meth:`PIL.ImageDraw.ImageDraw.ellipse`
        """
        self.render("ellipse", xy, pen, *options)
flush()
Image.Image PIL.ImageDraw2.Draw.flush (self)
Definition at line 79 of file ImageDraw2.py.
    def flush(self) -> Image.Image:
        return self.image
Referenced by pip._vendor.pygments.util.UnclosingTextIOWrapper.close().
line()
None PIL.ImageDraw2.Draw.line (self, Coords xy, Pen | Brush | None pen, *Any options)
Draws a line between the coordinates in the ``xy`` list.
.. seealso:: :py:meth:`PIL.ImageDraw.ImageDraw.line`
Definition at line 163 of file ImageDraw2.py.
    def line(self, xy: Coords, pen: Pen | Brush | None, *options: Any) -> None:
        """
        Draws a line between the coordinates in the ``xy`` list.
        .. seealso:: :py:meth:`PIL.ImageDraw.ImageDraw.line`
        """
        self.render("line", xy, pen, *options)
Referenced by yaml.scanner.Scanner.save_possible_simple_key(), and yaml.scanner.Scanner.stale_possible_simple_keys().
pieslice()
None PIL.ImageDraw2.Draw.pieslice (self, Coords xy, Pen | Brush | None pen, float start, float end, *Any options)
Same as arc, but also draws straight lines between the end points and the
center of the bounding box.
.. seealso:: :py:meth:`PIL.ImageDraw.ImageDraw.pieslice`
Definition at line 171 of file ImageDraw2.py.
    ) -> None:
        """
        Same as arc, but also draws straight lines between the end points and the
        center of the bounding box.
        .. seealso:: :py:meth:`PIL.ImageDraw.ImageDraw.pieslice`
        """
        self.render("pieslice", xy, pen, *options, start=start, end=end)
polygon()
None PIL.ImageDraw2.Draw.polygon (self, Coords xy, Pen | Brush | None pen, *Any options)
Draws a polygon.
The polygon outline consists of straight lines between the given
coordinates, plus a straight line between the last and the first
coordinate.
.. seealso:: :py:meth:`PIL.ImageDraw.ImageDraw.polygon`
Definition at line 187 of file ImageDraw2.py.
    def polygon(self, xy: Coords, pen: Pen | Brush | None, *options: Any) -> None:
        """
        Draws a polygon.
        The polygon outline consists of straight lines between the given
        coordinates, plus a straight line between the last and the first
        coordinate.
        .. seealso:: :py:meth:`PIL.ImageDraw.ImageDraw.polygon`
        """
        self.render("polygon", xy, pen, *options)
rectangle()
None PIL.ImageDraw2.Draw.rectangle (self, Coords xy, Pen | Brush | None pen, *Any options)
Draws a rectangle.
.. seealso:: :py:meth:`PIL.ImageDraw.ImageDraw.rectangle`
Definition at line 200 of file ImageDraw2.py.
    def rectangle(self, xy: Coords, pen: Pen | Brush | None, *options: Any) -> None:
        """
        Draws a rectangle.
        .. seealso:: :py:meth:`PIL.ImageDraw.ImageDraw.rectangle`
        """
        self.render("rectangle", xy, pen, *options)
render()
None PIL.ImageDraw2.Draw.render (self, str op, Coords xy, Pen | Brush | None pen, Brush | Pen | None brush = None, **Any kwargs)
Definition at line 82 of file ImageDraw2.py.
    ) -> None:
        # handle color arguments
        outline = fill = None
        width = 1
        if isinstance(pen, Pen):
            outline = pen.color
            width = pen.width
        elif isinstance(brush, Pen):
            outline = brush.color
            width = brush.width
        if isinstance(brush, Brush):
            fill = brush.color
        elif isinstance(pen, Brush):
            fill = pen.color
        # handle transformation
        if self.transform:
            path = ImagePath.Path(xy)
            path.transform(self.transform)
            xy = path
        # render the item
        if op in ("arc", "line"):
            kwargs.setdefault("fill", outline)
        else:
            kwargs.setdefault("fill", fill)
            kwargs.setdefault("outline", outline)
        if op == "line":
            kwargs.setdefault("width", width)
        getattr(self.draw, op)(xy, **kwargs)
Referenced by pip._vendor.rich.progress.ProgressColumn.__call__(), pip._vendor.rich.layout.Layout.__rich_console__(), pip._vendor.rich.spinner.Spinner.__rich_console__(), pip._vendor.rich.spinner.Spinner.__rich_measure__(), pip._vendor.rich.console.Console.log(), pip._vendor.rich.console.Console.print(), pip._vendor.rich.console.Console.render(), pip._vendor.rich.console.Console.render_lines(), and pip._vendor.rich.console.Console.update_screen_lines().
settransform()
None PIL.ImageDraw2.Draw.settransform (self, tuple[float, float] offset)
Sets a transformation offset.
Definition at line 118 of file ImageDraw2.py.
    def settransform(self, offset: tuple[float, float]) -> None:
        """Sets a transformation offset."""
        (xoffset, yoffset) = offset
        self.transform = (1, 0, xoffset, 0, 1, yoffset)
text()
None PIL.ImageDraw2.Draw.text (self, tuple[float, float] xy, AnyStr text, Font font)
Draws the string at the given position.
.. seealso:: :py:meth:`PIL.ImageDraw.ImageDraw.text`
Definition at line 208 of file ImageDraw2.py.
    def text(self, xy: tuple[float, float], text: AnyStr, font: Font) -> None:
        """
        Draws the string at the given position.
        .. seealso:: :py:meth:`PIL.ImageDraw.ImageDraw.text`
        """
        if self.transform:
            path = ImagePath.Path(xy)
            path.transform(self.transform)
            xy = path
        self.draw.text(xy, text, font=font.font, fill=font.color)
textbbox()
tuple[float, float, float, float] PIL.ImageDraw2.Draw.textbbox (self, tuple[float, float] xy, AnyStr text, Font font)
Returns bounding box (in pixels) of given text.
:return: ``(left, top, right, bottom)`` bounding box
.. seealso:: :py:meth:`PIL.ImageDraw.ImageDraw.textbbox`
Definition at line 220 of file ImageDraw2.py.
    ) -> tuple[float, float, float, float]:
        """
        Returns bounding box (in pixels) of given text.
        :return: ``(left, top, right, bottom)`` bounding box
        .. seealso:: :py:meth:`PIL.ImageDraw.ImageDraw.textbbox`
        """
        if self.transform:
            path = ImagePath.Path(xy)
            path.transform(self.transform)
            xy = path
        return self.draw.textbbox(xy, text, font=font.font)
textlength()
float PIL.ImageDraw2.Draw.textlength (self, AnyStr text, Font font)
Returns length (in pixels) of given text.
This is the amount by which following text should be offset.
.. seealso:: :py:meth:`PIL.ImageDraw.ImageDraw.textlength`
Definition at line 236 of file ImageDraw2.py.
    def textlength(self, text: AnyStr, font: Font) -> float:
        """
        Returns length (in pixels) of given text.
        This is the amount by which following text should be offset.
        .. seealso:: :py:meth:`PIL.ImageDraw.ImageDraw.textlength`
        """
        return self.draw.textlength(text, font=font.font)
Member Data Documentation
draw
PIL.ImageDraw2.Draw.draw = ImageDraw.Draw(image)
Definition at line 75 of file ImageDraw2.py.
image
PIL.ImageDraw2.Draw.image = image
Definition at line 76 of file ImageDraw2.py.
Referenced by PIL.ImageFile.Parser.close(), PIL.ImageWin.Dib.draw(), PIL.ImageEnhance._Enhance.enhance(), PIL.ImageWin.Dib.expose(), PIL.ImageFile.Parser.feed(), PIL.ImageWin.Dib.frombytes(), PIL.ImageWin.Dib.paste(), PIL.ImageWin.Dib.query_palette(), PIL.ImageWin.Dib.tobytes(), and PIL.ImageWin.ImageWindow.ui_handle_repair().
transform
PIL.ImageDraw2.Draw.transform = None
Definition at line 77 of file ImageDraw2.py.
Referenced by PIL.Image.Image.rotate().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/PIL/ImageDraw2.py