Read&Watch: django.contrib.auth.forms.PasswordResetForm Class Reference
django.contrib.auth.forms.PasswordResetForm Class Reference
Public Member Functions
send_mail (self, subject_template_name, email_template_name, context, from_email, to_email, html_email_template_name=None)
get_users (self, email)
save (self, domain_override=None, subject_template_name="registration/password_reset_subject.txt", email_template_name="registration/password_reset_email.html", use_https=False, token_generator=default_token_generator, from_email=None, request=None, html_email_template_name=None, extra_email_context=None)
Public Member Functions inherited from django.forms.forms.BaseForm
__init__ (self, data=None, files=None, auto_id="id_%s", prefix=None, initial=None, error_class=ErrorList, label_suffix=None, empty_permitted=False, field_order=None, use_required_attribute=None, renderer=None)
order_fields (self, field_order)
__repr__ (self)
__iter__ (self)
__getitem__ (self, name)
errors (self)
is_valid (self)
add_prefix (self, field_name)
add_initial_prefix (self, field_name)
template_name (self)
get_context (self)
non_field_errors (self)
add_error (self, field, error)
has_error (self, field, code=None)
full_clean (self)
clean (self)
has_changed (self)
changed_data (self)
media (self)
is_multipart (self)
hidden_fields (self)
visible_fields (self)
get_initial_for_field (self, field, field_name)
Public Member Functions inherited from django.forms.utils.RenderableFormMixin
as_p (self)
as_table (self)
as_ul (self)
as_div (self)
Public Member Functions inherited from django.forms.utils.RenderableMixin
render (self, template_name=None, context=None, renderer=None)
Public Member Functions inherited from django.forms.forms.DeclarativeFieldsMetaclass
__new__ (mcs, name, bases, attrs)
Public Member Functions inherited from django.forms.widgets.MediaDefiningClass
__new__ (mcs, name, bases, attrs)
Static Public Attributes
email
Static Public Attributes inherited from django.forms.forms.BaseForm
default_renderer = None
field_order = None
prefix = None
bool use_required_attribute = True
str template_name_label = "django/forms/label.html"
Additional Inherited Members
Public Attributes inherited from django.forms.forms.BaseForm
# Stop further processing. is_bound = data is not None or files is not None
data = MultiValueDict() if data is None else data
files = MultiValueDict() if files is None else files
auto_id = auto_id
initial = initial or {}
error_class = error_class
label_suffix = label_suffix if label_suffix is not None else _(":")
empty_permitted = empty_permitted
fields = copy.deepcopy(self.base_fields)
renderer = renderer
errors
dict cleaned_data = self.error_class(renderer=self.renderer)
changed_data
Public Attributes inherited from django.forms.utils.RenderableFormMixin
template_name_p
template_name_table
template_name_ul
template_name_div
Protected Member Functions inherited from django.forms.forms.BaseForm
_bound_items (self)
_widget_data_value (self, widget, html_name)
_clean_fields (self)
_clean_form (self)
_post_clean (self)
Protected Attributes inherited from django.forms.forms.BaseForm
_errors = None
dict _bound_fields_cache = {}
Detailed Description
Definition at line 394 of file forms.py.
Member Function Documentation
get_users()
django.contrib.auth.forms.PasswordResetForm.get_users (self, email)
Given an email, return matching user(s) who should receive a reset.
This allows subclasses to more easily customize the default policies
that prevent inactive users and users with unusable passwords from
resetting their password.
Definition at line 430 of file forms.py.
    def get_users(self, email):
        """Given an email, return matching user(s) who should receive a reset.
        This allows subclasses to more easily customize the default policies
        that prevent inactive users and users with unusable passwords from
        resetting their password.
        """
        email_field_name = UserModel.get_email_field_name()
        active_users = UserModel._default_manager.filter(
            **{
                "%s__iexact" % email_field_name: email,
                "is_active": True,
            }
        )
        return (
            u
            for u in active_users
            if u.has_usable_password()
            and _unicode_ci_compare(email, getattr(u, email_field_name))
        )
References django.contrib.auth.forms._unicode_ci_compare().
Referenced by save().
save()
django.contrib.auth.forms.PasswordResetForm.save (self, domain_override = None, subject_template_name = "registration/password_reset_subject.txt", email_template_name = "registration/password_reset_email.html", use_https = False, token_generator = default_token_generator, from_email = None, request = None, html_email_template_name = None, extra_email_context = None)
Generate a one-use only link for resetting password and send it to the
user.
Definition at line 451 of file forms.py.
    ):
        """
        Generate a one-use only link for resetting password and send it to the
        user.
        """
        email = self.cleaned_data["email"]
        if not domain_override:
            current_site = get_current_site(request)
            site_name = current_site.name
            domain = current_site.domain
        else:
            site_name = domain = domain_override
        email_field_name = UserModel.get_email_field_name()
        for user in self.get_users(email):
            user_email = getattr(user, email_field_name)
            context = {
                "email": user_email,
                "domain": domain,
                "site_name": site_name,
                "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                "user": user,
                "token": token_generator.make_token(user),
                "protocol": "https" if use_https else "http",
                **(extra_email_context or {}),
            }
            self.send_mail(
                subject_template_name,
                email_template_name,
                context,
                from_email,
                user_email,
                html_email_template_name=html_email_template_name,
            )
References django.forms.forms.BaseForm.cleaned_data, get_users(), and send_mail().
Referenced by PIL.Image.Image._dump(), PIL.Image.Image._repr_image(), django.core.serializers.base.DeserializedObject.save_deferred_fields(), and pylint.pyreverse.writer.DiagramWriter.write().
send_mail()
django.contrib.auth.forms.PasswordResetForm.send_mail (self, subject_template_name, email_template_name, context, from_email, to_email, html_email_template_name = None)
Send a django.core.mail.EmailMultiAlternatives to `to_email`.
Definition at line 401 of file forms.py.
    ):
        """
        Send a django.core.mail.EmailMultiAlternatives to `to_email`.
        """
        subject = loader.render_to_string(subject_template_name, context)
        # Email subject *must not* contain newlines
        subject = "".join(subject.splitlines())
        body = loader.render_to_string(email_template_name, context)
        email_message = EmailMultiAlternatives(subject, body, from_email, [to_email])
        if html_email_template_name is not None:
            html_email = loader.render_to_string(html_email_template_name, context)
            email_message.attach_alternative(html_email, "text/html")
        try:
            email_message.send()
        except Exception:
            logger.exception(
                "Failed to send password reset email to %s", context["user"].pk
            )
Referenced by django.utils.log.AdminEmailHandler.emit(), and save().
Member Data Documentation
email
django.contrib.auth.forms.PasswordResetForm.email static
Initial value:
=  forms.EmailField(
        label=_("Email"),
        max_length=254,
        widget=forms.EmailInput(attrs={"autocomplete": "email"}),
    )
Definition at line 395 of file forms.py.
Referenced by django.contrib.auth.models.AbstractUser.clean(), and django.contrib.auth.models.AbstractUser.email_user().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/auth/forms.py