Read&Watch: pip._internal.resolution.resolvelib.candidates.LinkCandidate Class Reference
pip._internal.resolution.resolvelib.candidates.LinkCandidate Class Reference
Public Member Functions
None __init__ (self, Link link, InstallRequirement template, "Factory" factory, Optional[NormalizedName] name=None, Optional[Version] version=None)
Public Member Functions inherited from pip._internal.resolution.resolvelib.candidates._InstallRequirementBackedCandidate
None __init__ (self, Link link, Link source_link, InstallRequirement ireq, "Factory" factory, Optional[NormalizedName] name=None, Optional[Version] version=None)
str __str__ (self)
str __repr__ (self)
int __hash__ (self)
bool __eq__ (self, Any other)
Optional[Link] source_link (self)
NormalizedName project_name (self)
str name (self)
Version version (self)
str format_for_error (self)
Iterable[Optional[Requirement]] iter_dependencies (self, bool with_requires)
Optional[InstallRequirement] get_install_requirement (self)
Public Member Functions inherited from pip._internal.resolution.resolvelib.base.Candidate
bool is_installed (self)
bool is_editable (self)
Protected Member Functions
BaseDistribution _prepare_distribution (self)
Protected Member Functions inherited from pip._internal.resolution.resolvelib.candidates._InstallRequirementBackedCandidate
None _check_metadata_consistency (self, BaseDistribution dist)
BaseDistribution _prepare (self)
Additional Inherited Members
Public Attributes inherited from pip._internal.resolution.resolvelib.candidates._InstallRequirementBackedCandidate
BaseDistribution dist = self._prepare()
Protected Attributes inherited from pip._internal.resolution.resolvelib.candidates._InstallRequirementBackedCandidate
_link = link
Optional[Link] _source_link = source_link
_factory = factory
_ireq = ireq
str _name = name
Version _version = version
Optional[int] _hash = None
Detailed Description
Definition at line 261 of file candidates.py.
Constructor & Destructor Documentation
__init__()
None pip._internal.resolution.resolvelib.candidates.LinkCandidate.__init__ (self, Link link, InstallRequirement template, "Factory" factory, Optional[NormalizedName] name = None, Optional[Version] version = None)
Definition at line 264 of file candidates.py.
    ) -> None:
        source_link = link
        cache_entry = factory.get_wheel_cache_entry(source_link, name)
        if cache_entry is not None:
            logger.debug("Using cached wheel link: %s", cache_entry.link)
            link = cache_entry.link
        ireq = make_install_req_from_link(link, template)
        assert ireq.link == link
        if ireq.link.is_wheel and not ireq.link.is_file:
            wheel = Wheel(ireq.link.filename)
            wheel_name = canonicalize_name(wheel.name)
            assert name == wheel_name, f"{name!r} != {wheel_name!r} for wheel"
            # Version may not be present for PEP 508 direct URLs
            if version is not None:
                wheel_version = Version(wheel.version)
                assert (
                    version == wheel_version
                ), f"{version!r} != {wheel_version!r} for wheel {name}"
        if cache_entry is not None:
            assert ireq.link.is_wheel
            assert ireq.link.is_file
            if cache_entry.persistent and template.link is template.original_link:
                ireq.cached_wheel_source_link = source_link
            if cache_entry.origin is not None:
                ireq.download_info = cache_entry.origin
            else:
                # Legacy cache entry that does not have origin.json.
                # download_info may miss the archive_info.hashes field.
                ireq.download_info = direct_url_from_link(
                    source_link, link_is_in_wheel_cache=cache_entry.persistent
                )
        super().__init__(
            link=link,
            source_link=source_link,
            ireq=ireq,
            factory=factory,
            name=name,
            version=version,
        )
References __init__(), and pip._internal.resolution.resolvelib.candidates.make_install_req_from_link().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Function Documentation
_prepare_distribution()
BaseDistribution pip._internal.resolution.resolvelib.candidates.LinkCandidate._prepare_distribution (self) protected
Reimplemented from pip._internal.resolution.resolvelib.candidates._InstallRequirementBackedCandidate.
Definition at line 313 of file candidates.py.
    def _prepare_distribution(self) -> BaseDistribution:
        preparer = self._factory.preparer
        return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
References pip._internal.resolution.resolvelib.candidates._InstallRequirementBackedCandidate._factory.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_internal/resolution/resolvelib/candidates.py