Read&Watch: django.db.migrations.serializer.FloatSerializer Class Reference
django.db.migrations.serializer.FloatSerializer Class Reference
Public Member Functions
serialize (self)
Public Member Functions inherited from django.db.migrations.serializer.BaseSerializer
__init__ (self, value)
Additional Inherited Members
Public Attributes inherited from django.db.migrations.serializer.BaseSerializer
value = value
Detailed Description
Definition at line 161 of file serializer.py.
Member Function Documentation
serialize()
django.db.migrations.serializer.FloatSerializer.serialize (self)
Reimplemented from django.db.migrations.serializer.BaseSimpleSerializer.
Definition at line 162 of file serializer.py.
    def serialize(self):
        if math.isnan(self.value) or math.isinf(self.value):
            return 'float("{}")'.format(self.value), set()
        return super().serialize()
Referenced by django.db.migrations.writer.MigrationWriter.as_string(), pylint.reporters.json_reporter.JSON2Reporter.display_messages(), pylint.reporters.json_reporter.JSONReporter.display_messages(), pip._vendor.cachecontrol.serialize.Serializer.dumps(), and yaml.representer.BaseRepresenter.represent().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/db/migrations/serializer.py