Read&Watch: pip._vendor.rich.progress.SpinnerColumn Class Reference
pip._vendor.rich.progress.SpinnerColumn Class Reference
Public Member Functions
__init__ (self, str spinner_name="dots", Optional[StyleType] style="progress.spinner", float speed=1.0, TextType finished_text=" ", Optional[Column] table_column=None)
None set_spinner (self, str spinner_name, Optional[StyleType] spinner_style="progress.spinner", float speed=1.0)
RenderableType render (self, "Task" task)
Public Member Functions inherited from pip._vendor.rich.progress.ProgressColumn
None __init__ (self, Optional[Column] table_column=None)
Column get_table_column (self)
RenderableType __call__ (self, "Task" task)
Public Attributes
spinner = Spinner(spinner_name, style=style, speed=speed)
tuple finished_text
Additional Inherited Members
Static Public Attributes inherited from pip._vendor.rich.progress.ProgressColumn
Optional max_refresh = None
Protected Attributes inherited from pip._vendor.rich.progress.ProgressColumn
_table_column = table_column
dict _renderable_cache = {}
Optional[float] _update_time = None
Detailed Description
A column with a 'spinner' animation.
Args:
    spinner_name (str, optional): Name of spinner animation. Defaults to "dots".
    style (StyleType, optional): Style of spinner. Defaults to "progress.spinner".
    speed (float, optional): Speed factor of spinner. Defaults to 1.0.
    finished_text (TextType, optional): Text used when task is finished. Defaults to " ".
Definition at line 554 of file progress.py.
Constructor & Destructor Documentation
__init__()
pip._vendor.rich.progress.SpinnerColumn.__init__ (self, str spinner_name = "dots", Optional[StyleType] style = "progress.spinner", float speed = 1.0, TextType finished_text = " ", Optional[Column] table_column = None)
Definition at line 564 of file progress.py.
    ):
        self.spinner = Spinner(spinner_name, style=style, speed=speed)
        self.finished_text = (
            Text.from_markup(finished_text)
            if isinstance(finished_text, str)
            else finished_text
        )
        super().__init__(table_column=table_column)
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
render()
RenderableType pip._vendor.rich.progress.SpinnerColumn.render (self, "Task" task)
Should return a renderable object.
Reimplemented from pip._vendor.rich.progress.ProgressColumn.
Definition at line 595 of file progress.py.
    def render(self, task: "Task") -> RenderableType:
        text = (
            self.finished_text
            if task.finished
            else self.spinner.render(task.get_time())
        )
        return text
References finished_text, render(), and spinner.
Referenced by pip._vendor.rich.spinner.Spinner.__rich_console__(), pip._vendor.rich.spinner.Spinner.__rich_measure__(), and render().
set_spinner()
None pip._vendor.rich.progress.SpinnerColumn.set_spinner (self, str spinner_name, Optional[StyleType] spinner_style = "progress.spinner", float speed = 1.0)
Set a new spinner.
Args:
    spinner_name (str): Spinner name, see python -m rich.spinner.
    spinner_style (Optional[StyleType], optional): Spinner style. Defaults to "progress.spinner".
    speed (float, optional): Speed factor of spinner. Defaults to 1.0.
Definition at line 580 of file progress.py.
    ) -> None:
        """Set a new spinner.
        Args:
            spinner_name (str): Spinner name, see python -m rich.spinner.
            spinner_style (Optional[StyleType], optional): Spinner style. Defaults to "progress.spinner".
            speed (float, optional): Speed factor of spinner. Defaults to 1.0.
        """
        self.spinner = Spinner(spinner_name, style=spinner_style, speed=speed)
References spinner.
Member Data Documentation
finished_text
tuple pip._vendor.rich.progress.SpinnerColumn.finished_text
Initial value:
=  (
            Text.from_markup(finished_text)
            if isinstance(finished_text, str)
            else finished_text
        )
Definition at line 573 of file progress.py.
Referenced by render().
spinner
pip._vendor.rich.progress.SpinnerColumn.spinner = Spinner(spinner_name, style=style, speed=speed)
Definition at line 572 of file progress.py.
Referenced by render(), and set_spinner().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/rich/progress.py