Read&Watch: pip._internal.metadata.base.BaseEnvironment Class Reference
pip._internal.metadata.base.BaseEnvironment Class Reference
Public Member Functions
"BaseEnvironment" default (cls)
"BaseEnvironment" from_paths (cls, Optional[List[str]] paths)
Optional["BaseDistribution"] get_distribution (self, str name)
Iterator[BaseDistribution] iter_all_distributions (self)
Iterator[BaseDistribution] iter_installed_distributions (self, bool local_only=True, Container[str] skip=stdlib_pkgs, bool include_editables=True, bool editables_only=False, bool user_only=False)
Protected Member Functions
Iterator["BaseDistribution"] _iter_distributions (self)
Detailed Description
An environment containing distributions to introspect.
Definition at line 582 of file base.py.
Member Function Documentation
_iter_distributions()
Iterator["BaseDistribution"] pip._internal.metadata.base.BaseEnvironment._iter_distributions (self) protected
Iterate through installed distributions.
This function should be implemented by subclass, but never called
directly. Use the public ``iter_distribution()`` instead, which
implements additional logic to make sure the distributions are valid.
Reimplemented in pip._internal.metadata.importlib._envs.Environment, and pip._internal.metadata.pkg_resources.Environment.
Definition at line 601 of file base.py.
    def _iter_distributions(self) -> Iterator["BaseDistribution"]:
        """Iterate through installed distributions.
        This function should be implemented by subclass, but never called
        directly. Use the public ``iter_distribution()`` instead, which
        implements additional logic to make sure the distributions are valid.
        """
        raise NotImplementedError()
Referenced by iter_all_distributions().
default()
"BaseEnvironment" pip._internal.metadata.base.BaseEnvironment.default (cls)
Reimplemented in pip._internal.metadata.importlib._envs.Environment, and pip._internal.metadata.pkg_resources.Environment.
Definition at line 586 of file base.py.
    def default(cls) -> "BaseEnvironment":
        raise NotImplementedError()
from_paths()
"BaseEnvironment" pip._internal.metadata.base.BaseEnvironment.from_paths (cls, Optional[List[str]] paths)
Reimplemented in pip._internal.metadata.importlib._envs.Environment, and pip._internal.metadata.pkg_resources.Environment.
Definition at line 590 of file base.py.
    def from_paths(cls, paths: Optional[List[str]]) -> "BaseEnvironment":
        raise NotImplementedError()
get_distribution()
Optional["BaseDistribution"] pip._internal.metadata.base.BaseEnvironment.get_distribution (self, str name)
Given a requirement name, return the installed distributions.
The name may not be normalized. The implementation must canonicalize
it for lookup.
Reimplemented in pip._internal.metadata.importlib._envs.Environment, and pip._internal.metadata.pkg_resources.Environment.
Definition at line 593 of file base.py.
    def get_distribution(self, name: str) -> Optional["BaseDistribution"]:
        """Given a requirement name, return the installed distributions.
        The name may not be normalized. The implementation must canonicalize
        it for lookup.
        """
        raise NotImplementedError()
Referenced by pip._vendor.distlib.database.DistributionPath.get_file_path().
iter_all_distributions()
Iterator[BaseDistribution] pip._internal.metadata.base.BaseEnvironment.iter_all_distributions (self)
Iterate through all installed distributions without any filtering.
Definition at line 610 of file base.py.
    def iter_all_distributions(self) -> Iterator[BaseDistribution]:
        """Iterate through all installed distributions without any filtering."""
        for dist in self._iter_distributions():
            # Make sure the distribution actually comes from a valid Python
            # packaging distribution. Pip's AdjacentTempDirectory leaves folders
            # e.g. ``~atplotlib.dist-info`` if cleanup was interrupted. The
            # valid project name pattern is taken from PEP 508.
            project_name_valid = re.match(
                r"^([A-Z0-9]|[A-Z0-9][A-Z0-9._-]*[A-Z0-9])$",
                dist.canonical_name,
                flags=re.IGNORECASE,
            )
            if not project_name_valid:
                logger.warning(
                    "Ignoring invalid distribution %s (%s)",
                    dist.canonical_name,
                    dist.location,
                )
                continue
            yield dist
References _iter_distributions().
Referenced by pip._internal.metadata.pkg_resources.Environment._search_distribution(), pip._internal.metadata.importlib._envs.Environment.get_distribution(), and iter_installed_distributions().
iter_installed_distributions()
Iterator[BaseDistribution] pip._internal.metadata.base.BaseEnvironment.iter_installed_distributions (self, bool local_only = True, Container[str] skip = stdlib_pkgs, bool include_editables = True, bool editables_only = False, bool user_only = False)
Return a list of installed distributions.
This is based on ``iter_all_distributions()`` with additional filtering
options. Note that ``iter_installed_distributions()`` without arguments
is *not* equal to ``iter_all_distributions()``, since some of the
configurations exclude packages by default.
:param local_only: If True (default), only return installations
local to the current virtualenv, if in a virtualenv.
:param skip: An iterable of canonicalized project names to ignore;
    defaults to ``stdlib_pkgs``.
:param include_editables: If False, don't report editables.
:param editables_only: If True, only report editables.
:param user_only: If True, only report installations in the user
site directory.
Definition at line 631 of file base.py.
    ) -> Iterator[BaseDistribution]:
        """Return a list of installed distributions.
        This is based on ``iter_all_distributions()`` with additional filtering
        options. Note that ``iter_installed_distributions()`` without arguments
        is *not* equal to ``iter_all_distributions()``, since some of the
        configurations exclude packages by default.
        :param local_only: If True (default), only return installations
        local to the current virtualenv, if in a virtualenv.
        :param skip: An iterable of canonicalized project names to ignore;
            defaults to ``stdlib_pkgs``.
        :param include_editables: If False, don't report editables.
        :param editables_only: If True, only report editables.
        :param user_only: If True, only report installations in the user
        site directory.
        """
        it = self.iter_all_distributions()
        if local_only:
            it = (d for d in it if d.local)
        if not include_editables:
            it = (d for d in it if not d.editable)
        if editables_only:
            it = (d for d in it if d.editable)
        if user_only:
            it = (d for d in it if d.in_usersite)
        return (d for d in it if d.canonical_name not in skip)
References iter_all_distributions().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_internal/metadata/base.py