Read&Watch: pylint.extensions.docparams.DocstringParameterChecker Class Reference
pylint.extensions.docparams.DocstringParameterChecker Class Reference
Public Member Functions
None visit_functiondef (self, nodes.FunctionDef node)
None check_functiondef_params (self, nodes.FunctionDef node, Docstring node_doc)
None check_functiondef_returns (self, nodes.FunctionDef node, Docstring node_doc)
None check_functiondef_yields (self, nodes.FunctionDef node, Docstring node_doc)
None visit_raise (self, nodes.Raise node)
None visit_return (self, nodes.Return node)
None visit_yield (self, nodes.Yield|nodes.YieldFrom node)
None check_arguments_in_docstring (self, Docstring doc, astroid.Arguments arguments_node, astroid.NodeNG warning_node, bool|None accept_no_param_doc=None)
None check_single_constructor_params (self, Docstring class_doc, Docstring init_doc, nodes.ClassDef class_node)
Public Member Functions inherited from pylint.checkers.base_checker.BaseChecker
None __init__ (self, PyLinter linter)
bool __gt__ (self, Any other)
bool __eq__ (self, object other)
int __hash__ (self)
str __repr__ (self)
str __str__ (self)
str get_full_documentation (self, dict[str, MessageDefinitionTuple] msgs, Iterable[tuple[str, OptionDict, Any]] options, Sequence[tuple[str, str, ReportsCallable]] reports, str|None doc=None, str|None module=None, bool show_options=True)
None add_message (self, str msgid, int|None line=None, nodes.NodeNG|None node=None, Any args=None, Confidence|None confidence=None, int|None col_offset=None, int|None end_lineno=None, int|None end_col_offset=None)
None check_consistency (self)
MessageDefinition create_message_definition_from_tuple (self, str msgid, MessageDefinitionTuple msg_tuple)
list[MessageDefinition] messages (self)
None open (self)
None close (self)
Any get_map_data (self)
None reduce_map_data (self, PyLinter linter, list[Any] data)
Public Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
None __init__ (self, _ArgumentsManager arguments_manager)
Static Public Attributes
dict constructor_names = {"__init__", "__new__"}
dict not_needed_param_in_docstring = {"self", "cls"}
None visit_asyncfunctiondef = visit_functiondef
None visit_yieldfrom = visit_yield
Static Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
str name = ""
dict msgs = {}
tuple reports = ()
bool enabled = True
Static Public Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
tuple options = ()
dict option_groups_descs = {}
Protected Member Functions
None _compare_missing_args (self, set[str] found_argument_names, str message_id, set[str] not_needed_names, set[str] expected_argument_names, nodes.NodeNG warning_node)
None _compare_different_args (self, set[str] found_argument_names, str message_id, set[str] not_needed_names, set[str] expected_argument_names, nodes.NodeNG warning_node)
None _compare_ignored_args (self, set[str] found_argument_names, str message_id, set[str] ignored_argument_names, nodes.NodeNG warning_node)
None _add_raise_message (self, set[str] missing_exceptions, nodes.FunctionDef node)
Protected Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
Any _option_value (self, str opt)
Iterator[ tuple[str, list[tuple[str, OptionDict, Any]]]|tuple[None, dict[str, list[tuple[str, OptionDict, Any]]]]] _options_by_section (self)
Iterator[tuple[str, OptionDict, Any]] _options_and_values (self, Options|None options=None)
Additional Inherited Members
Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
linter = linter
messages
Protected Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
_arguments_manager = arguments_manager
Detailed Description
Checker for Sphinx, Google, or Numpy style docstrings.
* Check that all function, method and constructor parameters are mentioned
  in the params and types part of the docstring.  Constructor parameters
  can be documented in either the class docstring or ``__init__`` docstring,
  but not both.
* Check that there are no naming inconsistencies between the signature and
  the documentation, i.e. also report documented parameters that are missing
  in the signature. This is important to find cases where parameters are
  renamed only in the code, not in the documentation.
* Check that all explicitly raised exceptions in a function are documented
  in the function docstring. Caught exceptions are ignored.
Activate this checker by adding the line::
    load-plugins=pylint.extensions.docparams
to the ``MAIN`` section of your ``.pylintrc``.
Definition at line 25 of file docparams.py.
Member Function Documentation
_add_raise_message()
None pylint.extensions.docparams.DocstringParameterChecker._add_raise_message (self, set[str] missing_exceptions, nodes.FunctionDef node) protected
Adds a message on :param:`node` for the missing exception type.
:param missing_exceptions: A list of missing exception types.
:param node: The node to show the message on.
Definition at line 653 of file docparams.py.
    ) -> None:
        """Adds a message on :param:`node` for the missing exception type.
        :param missing_exceptions: A list of missing exception types.
        :param node: The node to show the message on.
        """
        if node.is_abstract():
            try:
                missing_exceptions.remove("NotImplementedError")
            except KeyError:
                pass
        if missing_exceptions:
            self.add_message(
                "missing-raises-doc",
                args=(", ".join(sorted(missing_exceptions)),),
                node=node,
                confidence=HIGH,
            )
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_raise().
_compare_different_args()
None pylint.extensions.docparams.DocstringParameterChecker._compare_different_args (self, set[str] found_argument_names, str message_id, set[str] not_needed_names, set[str] expected_argument_names, nodes.NodeNG warning_node) protected
Compare the found argument names with the expected ones and
generate a message if there are extra arguments found.
:param found_argument_names: argument names found in the docstring
:param message_id: pylint message id
:param not_needed_names: names that may be omitted
:param expected_argument_names: Expected argument names
:param warning_node: The node to be analyzed
Definition at line 435 of file docparams.py.
    ) -> None:
        """Compare the found argument names with the expected ones and
        generate a message if there are extra arguments found.
        :param found_argument_names: argument names found in the docstring
        :param message_id: pylint message id
        :param not_needed_names: names that may be omitted
        :param expected_argument_names: Expected argument names
        :param warning_node: The node to be analyzed
        """
        # Handle variadic and keyword args without asterisks
        modified_expected_argument_names: set[str] = set()
        for name in expected_argument_names:
            if name.replace("*", "") in found_argument_names:
                modified_expected_argument_names.add(name.replace("*", ""))
            else:
                modified_expected_argument_names.add(name)
        differing_argument_names = (
            (modified_expected_argument_names ^ found_argument_names)
            - not_needed_names
            - expected_argument_names
        )
        if differing_argument_names:
            self.add_message(
                message_id,
                args=(", ".join(sorted(differing_argument_names)),),
                node=warning_node,
                confidence=HIGH,
            )
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by check_arguments_in_docstring().
_compare_ignored_args()
None pylint.extensions.docparams.DocstringParameterChecker._compare_ignored_args (self, set[str] found_argument_names, str message_id, set[str] ignored_argument_names, nodes.NodeNG warning_node) protected
Compare the found argument names with the ignored ones and
generate a message if there are ignored arguments found.
:param found_argument_names: argument names found in the docstring
:param message_id: pylint message id
:param ignored_argument_names: Expected argument names
:param warning_node: The node to be analyzed
Definition at line 478 of file docparams.py.
    ) -> None:
        """Compare the found argument names with the ignored ones and
        generate a message if there are ignored arguments found.
        :param found_argument_names: argument names found in the docstring
        :param message_id: pylint message id
        :param ignored_argument_names: Expected argument names
        :param warning_node: The node to be analyzed
        """
        existing_ignored_argument_names = ignored_argument_names & found_argument_names
        if existing_ignored_argument_names:
            self.add_message(
                message_id,
                args=(", ".join(sorted(existing_ignored_argument_names)),),
                node=warning_node,
                confidence=HIGH,
            )
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by check_arguments_in_docstring().
_compare_missing_args()
None pylint.extensions.docparams.DocstringParameterChecker._compare_missing_args (self, set[str] found_argument_names, str message_id, set[str] not_needed_names, set[str] expected_argument_names, nodes.NodeNG warning_node) protected
Compare the found argument names with the expected ones and
generate a message if there are arguments missing.
:param found_argument_names: argument names found in the docstring
:param message_id: pylint message id
:param not_needed_names: names that may be omitted
:param expected_argument_names: Expected argument names
:param warning_node: The node to be analyzed
Definition at line 395 of file docparams.py.
    ) -> None:
        """Compare the found argument names with the expected ones and
        generate a message if there are arguments missing.
        :param found_argument_names: argument names found in the docstring
        :param message_id: pylint message id
        :param not_needed_names: names that may be omitted
        :param expected_argument_names: Expected argument names
        :param warning_node: The node to be analyzed
        """
        potential_missing_argument_names = (
            expected_argument_names - found_argument_names
        ) - not_needed_names
        # Handle variadic and keyword args without asterisks
        missing_argument_names = set()
        for name in potential_missing_argument_names:
            if name.replace("*", "") in found_argument_names:
                continue
            missing_argument_names.add(name)
        if missing_argument_names:
            self.add_message(
                message_id,
                args=(", ".join(sorted(missing_argument_names)),),
                node=warning_node,
                confidence=HIGH,
            )
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by check_arguments_in_docstring().
check_arguments_in_docstring()
None pylint.extensions.docparams.DocstringParameterChecker.check_arguments_in_docstring (self, Docstring doc, astroid.Arguments arguments_node, astroid.NodeNG warning_node, bool | None accept_no_param_doc = None)
Check that all parameters are consistent with the parameters mentioned
in the parameter documentation (e.g. the Sphinx tags 'param' and 'type').
* Undocumented parameters except 'self' are noticed.
* Undocumented parameter types except for 'self' and the ``*<args>``
  and ``**<kwargs>`` parameters are noticed.
* Parameters mentioned in the parameter documentation that don't or no
  longer exist in the function parameter list are noticed.
* If the text "For the parameters, see" or "For the other parameters,
  see" (ignoring additional white-space) is mentioned in the docstring,
  missing parameter documentation is tolerated.
* If there's no Sphinx style, Google style or NumPy style parameter
  documentation at all, i.e. ``:param`` is never mentioned etc., the
  checker assumes that the parameters are documented in another format
  and the absence is tolerated.
:param doc: Docstring for the function, method or class.
:type doc: :class:`Docstring`
:param arguments_node: Arguments node for the function, method or
    class constructor.
:type arguments_node: :class:`astroid.scoped_nodes.Arguments`
:param warning_node: The node to assign the warnings to
:type warning_node: :class:`astroid.scoped_nodes.Node`
:param accept_no_param_doc: Whether to allow no parameters to be
    documented. If None then this value is read from the configuration.
:type accept_no_param_doc: bool or None
Definition at line 503 of file docparams.py.
    ) -> None:
        """Check that all parameters are consistent with the parameters mentioned
        in the parameter documentation (e.g. the Sphinx tags 'param' and 'type').
        * Undocumented parameters except 'self' are noticed.
        * Undocumented parameter types except for 'self' and the ``*<args>``
          and ``**<kwargs>`` parameters are noticed.
        * Parameters mentioned in the parameter documentation that don't or no
          longer exist in the function parameter list are noticed.
        * If the text "For the parameters, see" or "For the other parameters,
          see" (ignoring additional white-space) is mentioned in the docstring,
          missing parameter documentation is tolerated.
        * If there's no Sphinx style, Google style or NumPy style parameter
          documentation at all, i.e. ``:param`` is never mentioned etc., the
          checker assumes that the parameters are documented in another format
          and the absence is tolerated.
        :param doc: Docstring for the function, method or class.
        :type doc: :class:`Docstring`
        :param arguments_node: Arguments node for the function, method or
            class constructor.
        :type arguments_node: :class:`astroid.scoped_nodes.Arguments`
        :param warning_node: The node to assign the warnings to
        :type warning_node: :class:`astroid.scoped_nodes.Node`
        :param accept_no_param_doc: Whether to allow no parameters to be
            documented. If None then this value is read from the configuration.
        :type accept_no_param_doc: bool or None
        """
        # Tolerate missing param or type declarations if there is a link to
        # another method carrying the same name.
        if not doc.doc:
            return
        if accept_no_param_doc is None:
            accept_no_param_doc = self.linter.config.accept_no_param_doc
        tolerate_missing_params = doc.params_documented_elsewhere()
        # Collect the function arguments.
        expected_argument_names = {arg.name for arg in arguments_node.args}
        expected_argument_names.update(
            a.name for a in arguments_node.posonlyargs + arguments_node.kwonlyargs
        )
        not_needed_type_in_docstring = self.not_needed_param_in_docstring.copy()
        expected_but_ignored_argument_names = set()
        ignored_argument_names = self.linter.config.ignored_argument_names
        if ignored_argument_names:
            expected_but_ignored_argument_names = {
                arg
                for arg in expected_argument_names
                if ignored_argument_names.match(arg)
            }
        if arguments_node.vararg is not None:
            expected_argument_names.add(f"*{arguments_node.vararg}")
            not_needed_type_in_docstring.add(f"*{arguments_node.vararg}")
        if arguments_node.kwarg is not None:
            expected_argument_names.add(f"**{arguments_node.kwarg}")
            not_needed_type_in_docstring.add(f"**{arguments_node.kwarg}")
        params_with_doc, params_with_type = doc.match_param_docs()
        # Tolerate no parameter documentation at all.
        if not params_with_doc and not params_with_type and accept_no_param_doc:
            tolerate_missing_params = True
        # This is before the update of params_with_type because this must check only
        # the type documented in a docstring, not the one using pep484
        # See #4117 and #4593
        self._compare_ignored_args(
            params_with_type,
            "useless-type-doc",
            expected_but_ignored_argument_names,
            warning_node,
        )
        params_with_type |= utils.args_with_annotation(arguments_node)
        if not tolerate_missing_params:
            missing_param_doc = (expected_argument_names - params_with_doc) - (
                self.not_needed_param_in_docstring | expected_but_ignored_argument_names
            )
            missing_type_doc = (expected_argument_names - params_with_type) - (
                not_needed_type_in_docstring | expected_but_ignored_argument_names
            )
            if (
                missing_param_doc == expected_argument_names == missing_type_doc
                and len(expected_argument_names) != 0
            ):
                self.add_message(
                    "missing-any-param-doc",
                    args=(warning_node.name,),
                    node=warning_node,
                    confidence=HIGH,
                )
            else:
                self._compare_missing_args(
                    params_with_doc,
                    "missing-param-doc",
                    self.not_needed_param_in_docstring
                    | expected_but_ignored_argument_names,
                    expected_argument_names,
                    warning_node,
                )
                self._compare_missing_args(
                    params_with_type,
                    "missing-type-doc",
                    not_needed_type_in_docstring | expected_but_ignored_argument_names,
                    expected_argument_names,
                    warning_node,
                )
        self._compare_different_args(
            params_with_doc,
            "differing-param-doc",
            self.not_needed_param_in_docstring,
            expected_argument_names,
            warning_node,
        )
        self._compare_different_args(
            params_with_type,
            "differing-type-doc",
            not_needed_type_in_docstring,
            expected_argument_names,
            warning_node,
        )
        self._compare_ignored_args(
            params_with_doc,
            "useless-param-doc",
            expected_but_ignored_argument_names,
            warning_node,
        )
References _compare_different_args(), _compare_ignored_args(), _compare_missing_args(), pylint.checkers.base_checker.BaseChecker.add_message(), pylint.checkers.base_checker.BaseChecker.linter, and not_needed_param_in_docstring.
Referenced by check_functiondef_params().
check_functiondef_params()
None pylint.extensions.docparams.DocstringParameterChecker.check_functiondef_params (self, nodes.FunctionDef node, Docstring node_doc)
Definition at line 223 of file docparams.py.
    ) -> None:
        node_allow_no_param = None
        if node.name in self.constructor_names:
            class_node = checker_utils.node_frame_class(node)
            if class_node is not None:
                class_doc = utils.docstringify(
                    class_node.doc_node, self.linter.config.default_docstring_type
                )
                self.check_single_constructor_params(class_doc, node_doc, class_node)
                # __init__ or class docstrings can have no parameters documented
                # as long as the other documents them.
                node_allow_no_param = (
                    class_doc.has_params()
                    or class_doc.params_documented_elsewhere()
                    or None
                )
                class_allow_no_param = (
                    node_doc.has_params()
                    or node_doc.params_documented_elsewhere()
                    or None
                )
                self.check_arguments_in_docstring(
                    class_doc, node.args, class_node, class_allow_no_param
                )
        self.check_arguments_in_docstring(
            node_doc, node.args, node, node_allow_no_param
        )
References check_arguments_in_docstring(), check_single_constructor_params(), constructor_names, and pylint.checkers.base_checker.BaseChecker.linter.
Referenced by visit_functiondef().
check_functiondef_returns()
None pylint.extensions.docparams.DocstringParameterChecker.check_functiondef_returns (self, nodes.FunctionDef node, Docstring node_doc)
Definition at line 256 of file docparams.py.
    ) -> None:
        if (not node_doc.supports_yields and node.is_generator()) or node.is_abstract():
            return
        return_nodes = node.nodes_of_class(astroid.Return)
        if (node_doc.has_returns() or node_doc.has_rtype()) and not any(
            utils.returns_something(ret_node) for ret_node in return_nodes
        ):
            self.add_message("redundant-returns-doc", node=node, confidence=HIGH)
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_functiondef().
check_functiondef_yields()
None pylint.extensions.docparams.DocstringParameterChecker.check_functiondef_yields (self, nodes.FunctionDef node, Docstring node_doc)
Definition at line 268 of file docparams.py.
    ) -> None:
        if not node_doc.supports_yields or node.is_abstract():
            return
        if (
            node_doc.has_yields() or node_doc.has_yields_type()
        ) and not node.is_generator():
            self.add_message("redundant-yields-doc", node=node)
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_functiondef().
check_single_constructor_params()
None pylint.extensions.docparams.DocstringParameterChecker.check_single_constructor_params (self, Docstring class_doc, Docstring init_doc, nodes.ClassDef class_node)
Definition at line 642 of file docparams.py.
    ) -> None:
        if class_doc.has_params() and init_doc.has_params():
            self.add_message(
                "multiple-constructor-doc",
                args=(class_node.name,),
                node=class_node,
                confidence=HIGH,
            )
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by check_functiondef_params().
visit_functiondef()
None pylint.extensions.docparams.DocstringParameterChecker.visit_functiondef (self, nodes.FunctionDef node)
Called for function and method definitions (def).
:param node: Node for a function or method definition in the AST
:type node: :class:`astroid.scoped_nodes.Function`
Definition at line 193 of file docparams.py.
    def visit_functiondef(self, node: nodes.FunctionDef) -> None:
        """Called for function and method definitions (def).
        :param node: Node for a function or method definition in the AST
        :type node: :class:`astroid.scoped_nodes.Function`
        """
        if checker_utils.is_overload_stub(node):
            return
        node_doc = utils.docstringify(
            node.doc_node, self.linter.config.default_docstring_type
        )
        # skip functions that match the 'no-docstring-rgx' config option
        no_docstring_rgx = self.linter.config.no_docstring_rgx
        if no_docstring_rgx and re.match(no_docstring_rgx, node.name):
            return
        # skip functions smaller than 'docstring-min-length'
        lines = checker_utils.get_node_last_lineno(node) - node.lineno
        max_lines = self.linter.config.docstring_min_length
        if max_lines > -1 and lines < max_lines:
            return
        self.check_functiondef_params(node, node_doc)
        self.check_functiondef_returns(node, node_doc)
        self.check_functiondef_yields(node, node_doc)
References check_functiondef_params(), check_functiondef_returns(), check_functiondef_yields(), and pylint.checkers.base_checker.BaseChecker.linter.
Referenced by pylint.pyreverse.inspector.Linker.visit_assignname().
visit_raise()
None pylint.extensions.docparams.DocstringParameterChecker.visit_raise (self, nodes.Raise node)
Definition at line 279 of file docparams.py.
    def visit_raise(self, node: nodes.Raise) -> None:
        func_node = node.frame()
        if not isinstance(func_node, astroid.FunctionDef):
            return
        # skip functions that match the 'no-docstring-rgx' config option
        no_docstring_rgx = self.linter.config.no_docstring_rgx
        if no_docstring_rgx and re.match(no_docstring_rgx, func_node.name):
            return
        expected_excs = utils.possible_exc_types(node)
        if not expected_excs:
            return
        if not func_node.doc_node:
            # If this is a property setter,
            # the property should have the docstring instead.
            property_ = utils.get_setters_property(func_node)
            if property_:
                func_node = property_
        doc = utils.docstringify(
            func_node.doc_node, self.linter.config.default_docstring_type
        )
        if self.linter.config.accept_no_raise_doc and not doc.exceptions():
            return
        if not doc.matching_sections():
            if doc.doc:
                missing = {exc.name for exc in expected_excs}
                self._add_raise_message(missing, func_node)
            return
        found_excs_full_names = doc.exceptions()
        # Extract just the class name, e.g. "error" from "re.error"
        found_excs_class_names = {exc.split(".")[-1] for exc in found_excs_full_names}
        missing_excs = set()
        for expected in expected_excs:
            for found_exc in found_excs_class_names:
                if found_exc == expected.name:
                    break
                if found_exc == "error" and expected.name == "PatternError":
                    # Python 3.13: re.error aliases re.PatternError
                    break
                if any(found_exc == ancestor.name for ancestor in expected.ancestors()):
                    break
            else:
                missing_excs.add(expected.name)
        self._add_raise_message(missing_excs, func_node)
References _add_raise_message(), and pylint.checkers.base_checker.BaseChecker.linter.
visit_return()
None pylint.extensions.docparams.DocstringParameterChecker.visit_return (self, nodes.Return node)
Definition at line 334 of file docparams.py.
    def visit_return(self, node: nodes.Return) -> None:
        if not utils.returns_something(node):
            return
        if self.linter.config.accept_no_return_doc:
            return
        func_node: astroid.FunctionDef = node.frame()
        # skip functions that match the 'no-docstring-rgx' config option
        no_docstring_rgx = self.linter.config.no_docstring_rgx
        if no_docstring_rgx and re.match(no_docstring_rgx, func_node.name):
            return
        doc = utils.docstringify(
            func_node.doc_node, self.linter.config.default_docstring_type
        )
        is_property = checker_utils.decorated_with_property(func_node)
        if not (doc.has_returns() or (doc.has_property_returns() and is_property)):
            self.add_message("missing-return-doc", node=func_node, confidence=HIGH)
        if func_node.returns or func_node.type_comment_returns:
            return
        if not (doc.has_rtype() or (doc.has_property_type() and is_property)):
            self.add_message("missing-return-type-doc", node=func_node, confidence=HIGH)
References pylint.checkers.base_checker.BaseChecker.add_message(), and pylint.checkers.base_checker.BaseChecker.linter.
visit_yield()
None pylint.extensions.docparams.DocstringParameterChecker.visit_yield (self, nodes.Yield | nodes.YieldFrom node)
Definition at line 363 of file docparams.py.
    def visit_yield(self, node: nodes.Yield | nodes.YieldFrom) -> None:
        if self.linter.config.accept_no_yields_doc:
            return
        func_node: astroid.FunctionDef = node.frame()
        # skip functions that match the 'no-docstring-rgx' config option
        no_docstring_rgx = self.linter.config.no_docstring_rgx
        if no_docstring_rgx and re.match(no_docstring_rgx, func_node.name):
            return
        doc = utils.docstringify(
            func_node.doc_node, self.linter.config.default_docstring_type
        )
        if doc.supports_yields:
            doc_has_yields = doc.has_yields()
            doc_has_yields_type = doc.has_yields_type()
        else:
            doc_has_yields = doc.has_returns()
            doc_has_yields_type = doc.has_rtype()
        if not doc_has_yields:
            self.add_message("missing-yield-doc", node=func_node, confidence=HIGH)
        if not (
            doc_has_yields_type or func_node.returns or func_node.type_comment_returns
        ):
            self.add_message("missing-yield-type-doc", node=func_node, confidence=HIGH)
References pylint.checkers.base_checker.BaseChecker.add_message(), and pylint.checkers.base_checker.BaseChecker.linter.
Member Data Documentation
constructor_names
dict pylint.extensions.docparams.DocstringParameterChecker.constructor_names = {"__init__", "__new__"} static
Definition at line 190 of file docparams.py.
Referenced by check_functiondef_params().
not_needed_param_in_docstring
pylint.extensions.docparams.DocstringParameterChecker.not_needed_param_in_docstring = {"self", "cls"} static
Definition at line 191 of file docparams.py.
Referenced by check_arguments_in_docstring().
visit_asyncfunctiondef
None pylint.extensions.docparams.DocstringParameterChecker.visit_asyncfunctiondef = visit_functiondef static
Definition at line 221 of file docparams.py.
visit_yieldfrom
None pylint.extensions.docparams.DocstringParameterChecker.visit_yieldfrom = visit_yield static
Definition at line 393 of file docparams.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pylint/extensions/docparams.py