Read&Watch: pip._vendor.typing_extensions.TypeVar Class Reference
pip._vendor.typing_extensions.TypeVar Class Reference
Public Member Functions
__new__ (cls, name, *constraints, bound=None, covariant=False, contravariant=False, default=NoDefault, infer_variance=False)
None __init_subclass__ (cls)
Public Member Functions inherited from pip._vendor.typing_extensions._TypeVarLikeMeta
bool __instancecheck__ (cls, Any __instance)
Additional Inherited Members
Protected Attributes inherited from pip._vendor.typing_extensions._TypeVarLikeMeta
_backported_typevarlike
Detailed Description
Type variable.
Definition at line 1503 of file typing_extensions.py.
Member Function Documentation
__init_subclass__()
None pip._vendor.typing_extensions.TypeVar.__init_subclass__ (cls)
Definition at line 1537 of file typing_extensions.py.
        def __init_subclass__(cls) -> None:
            raise TypeError(f"type '{__name__}.TypeVar' is not an acceptable base type")
# Python 3.10+ has PEP 612
__new__()
pip._vendor.typing_extensions.TypeVar.__new__ (cls, name, * constraints, bound = None, covariant = False, contravariant = False, default = NoDefault, infer_variance = False)
Definition at line 1508 of file typing_extensions.py.
                    default=NoDefault, infer_variance=False):
            if hasattr(typing, "TypeAliasType"):
                # PEP 695 implemented (3.12+), can pass infer_variance to typing.TypeVar
                typevar = typing.TypeVar(name, *constraints, bound=bound,
                                         covariant=covariant, contravariant=contravariant,
                                         infer_variance=infer_variance)
            else:
                typevar = typing.TypeVar(name, *constraints, bound=bound,
                                         covariant=covariant, contravariant=contravariant)
                if infer_variance and (covariant or contravariant):
                    raise ValueError("Variance cannot be specified with infer_variance.")
                typevar.__infer_variance__ = infer_variance
            _set_default(typevar, default)
            _set_module(typevar)
            def _tvar_prepare_subst(alias, args):
                if (
                    typevar.has_default()
                    and alias.__parameters__.index(typevar) == len(args)
                ):
                    args += (typevar.__default__,)
                return args
            typevar.__typing_prepare_subst__ = _tvar_prepare_subst
            return typevar
References pip._vendor.typing_extensions._set_default(), and pip._vendor.typing_extensions._set_module().
Referenced by apscheduler.triggers.combining.BaseCombiningTrigger.__setstate__(), pip._vendor.rich.style.Style._add(), pip._vendor.rich.style.Style.clear_meta_and_links(), yaml.constructor.SafeConstructor.construct_yaml_object(), pip._vendor.rich.style.Style.copy(), pip._vendor.rich.style.Style.from_color(), pip._vendor.rich.json.JSON.from_data(), pip._vendor.rich.style.Style.from_meta(), yaml.constructor.FullConstructor.make_python_instance(), pip._vendor.rich.style.Style.update_link(), and pip._vendor.rich.style.Style.without_color().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/typing_extensions.py