Read&Watch: tomlkit.items.Bool Class Reference
tomlkit.items.Bool Class Reference
Public Member Functions
None __init__ (self, int t, Trivia trivia)
bool unwrap (self)
int discriminant (self)
bool value (self)
str as_string (self)
__bool__ (self)
__eq__ (self, other)
__hash__ (self)
__repr__ (self)
Public Member Functions inherited from tomlkit.items.Item
None __init__ (self, Trivia trivia)
Trivia trivia (self)
Item comment (self, str comment)
Item indent (self, int indent)
bool is_boolean (self)
bool is_table (self)
bool is_inline_table (self)
bool is_aot (self)
__reduce__ (self)
__reduce_ex__ (self, protocol)
Protected Member Functions
_getstate (self, protocol=3)
Protected Attributes
_value = bool(t)
Protected Attributes inherited from tomlkit.items.Item
Trivia _trivia = trivia
Detailed Description
A boolean literal.
Definition at line 748 of file items.py.
Constructor & Destructor Documentation
__init__()
None tomlkit.items.Bool.__init__ (self, int t, Trivia trivia)
Definition at line 753 of file items.py.
    def __init__(self, t: int, trivia: Trivia) -> None:
        super().__init__(trivia)
        self._value = bool(t)
References __init__().
Referenced by __init__().
Member Function Documentation
__bool__()
tomlkit.items.Bool.__bool__ (self)
Definition at line 776 of file items.py.
    def __bool__(self):
        return self._value
References _value.
__eq__()
tomlkit.items.Bool.__eq__ (self, other)
Definition at line 781 of file items.py.
    def __eq__(self, other):
        if not isinstance(other, bool):
            return NotImplemented
        return other == self._value
References _value.
Referenced by dotenv.variables.Atom.__ne__(), and urllib3._collections.HTTPHeaderDict.__ne__().
__hash__()
tomlkit.items.Bool.__hash__ (self)
Definition at line 787 of file items.py.
    def __hash__(self):
        return hash(self._value)
References _value.
__repr__()
tomlkit.items.Bool.__repr__ (self)
Definition at line 790 of file items.py.
    def __repr__(self):
        return repr(self._value)
References _value.
_getstate()
tomlkit.items.Bool._getstate (self, protocol = 3) protected
Reimplemented from tomlkit.items.Item.
Definition at line 773 of file items.py.
    def _getstate(self, protocol=3):
        return self._value, self._trivia
References tomlkit.items.Item._trivia, and _value.
as_string()
str tomlkit.items.Bool.as_string (self)
The TOML representation
Reimplemented from tomlkit.items.Item.
Definition at line 770 of file items.py.
    def as_string(self) -> str:
        return str(self._value).lower()
References _value.
discriminant()
int tomlkit.items.Bool.discriminant (self)
Reimplemented from tomlkit.items.Item.
Definition at line 762 of file items.py.
    def discriminant(self) -> int:
        return 4
unwrap()
bool tomlkit.items.Bool.unwrap (self)
Returns as pure python object (ppo)
Reimplemented from tomlkit.items.Item.
Definition at line 758 of file items.py.
    def unwrap(self) -> bool:
        return bool(self)
value()
bool tomlkit.items.Bool.value (self)
The wrapped boolean value
Reimplemented from tomlkit.items.Item.
Definition at line 766 of file items.py.
    def value(self) -> bool:
        """The wrapped boolean value"""
        return self._value
References _value.
Referenced by pip._internal.models.link.LinkHash.as_hashes(), pip._internal.models.link.LinkHash.is_hash_allowed(), and tomlkit.items.StringType.unit().
Member Data Documentation
_value
tomlkit.items.Bool._value = bool(t) protected
Definition at line 756 of file items.py.
Referenced by __bool__(), tomlkit.items.InlineTable.__copy__(), tomlkit.items.Table.__copy__(), tomlkit.items.Array.__delitem__(), __eq__(), tomlkit.items.AbstractTable.__getitem__(), __hash__(), tomlkit.items.AbstractTable.__iter__(), tomlkit.items.AbstractTable.__len__(), __repr__(), tomlkit.items.AbstractTable.__setitem__(), tomlkit.items.Array.__setitem__(), _getstate(), tomlkit.items.Array._iter_items(), tomlkit.items.Array._reindex(), tomlkit.items.Array.add_line(), tomlkit.items.Table.append(), tomlkit.items.Array.as_string(), as_string(), tomlkit.items.InlineTable.as_string(), tomlkit.items.Table.as_string(), tomlkit.items.Array.clear(), tomlkit.items.Table.indent(), tomlkit.items.Array.insert(), tomlkit.items.Table.raw_append(), tomlkit.items.AbstractTable.remove(), tomlkit.items.AbstractTable.value(), and value().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/tomlkit/items.py