Read&Watch: pip._vendor.pkg_resources.Requirement Class Reference
pip._vendor.pkg_resources.Requirement Class Reference
Public Member Functions
__init__ (self, str requirement_string)
__eq__ (self, object other)
__ne__ (self, other)
bool __contains__ (self, Distribution|str|tuple[str,...] item)
__hash__ (self)
__repr__ (self)
Static Public Member Functions
parse (str|Iterable[str] s)
Public Attributes
unsafe_name = self.name
project_name
key = project_name, project_name.lower()
list specs = [(spec.operator, spec.version) for spec in self.specifier]
tuple[str] extras = tuple(map(safe_extra, self.extras))
tuple hashCmp
Detailed Description
Definition at line 3431 of file __init__.py.
Constructor & Destructor Documentation
__init__()
pip._vendor.pkg_resources.Requirement.__init__ (self, str requirement_string)
DO NOT CALL THIS UNDOCUMENTED METHOD; use Requirement.parse()!
Definition at line 3432 of file __init__.py.
    def __init__(self, requirement_string: str):
        """DO NOT CALL THIS UNDOCUMENTED METHOD; use Requirement.parse()!"""
        super().__init__(requirement_string)
        self.unsafe_name = self.name
        project_name = safe_name(self.name)
        self.project_name, self.key = project_name, project_name.lower()
        self.specs = [(spec.operator, spec.version) for spec in self.specifier]
        # packaging.requirements.Requirement uses a set for its extras. We use a variable-length tuple
        self.extras: tuple[str] = tuple(map(safe_extra, self.extras))
        self.hashCmp = (
            self.key,
            self.url,
            self.specifier,
            frozenset(self.extras),
            str(self.marker) if self.marker else None,
        )
        self.__hash = hash(self.hashCmp)
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
__contains__()
bool pip._vendor.pkg_resources.Requirement.__contains__ (self, Distribution | str | tuple[str, ...] item)
Definition at line 3456 of file __init__.py.
    def __contains__(self, item: Distribution | str | tuple[str, ...]) -> bool:
        if isinstance(item, Distribution):
            if item.key != self.key:
                return False
            item = item.version
        # Allow prereleases always in order to match the previous behavior of
        # this method. In the future this should be smarter and follow PEP 440
        # more accurately.
        return self.specifier.contains(item, prereleases=True)
__eq__()
pip._vendor.pkg_resources.Requirement.__eq__ (self, object other)
Definition at line 3450 of file __init__.py.
    def __eq__(self, other: object):
        return isinstance(other, Requirement) and self.hashCmp == other.hashCmp
Referenced by dotenv.variables.Atom.__ne__(), pip._vendor.urllib3._collections.HTTPHeaderDict.__ne__(), responses.BaseResponse.__ne__(), and urllib3._collections.HTTPHeaderDict.__ne__().
__hash__()
pip._vendor.pkg_resources.Requirement.__hash__ (self)
Definition at line 3468 of file __init__.py.
    def __hash__(self):
        return self.__hash
Referenced by pip._vendor.rich.style.Style.__eq__(), and pip._vendor.rich.style.Style.__ne__().
__ne__()
pip._vendor.pkg_resources.Requirement.__ne__ (self, other)
Definition at line 3453 of file __init__.py.
    def __ne__(self, other):
        return not self == other
__repr__()
pip._vendor.pkg_resources.Requirement.__repr__ (self)
Definition at line 3471 of file __init__.py.
    def __repr__(self):
        return "Requirement.parse(%r)" % str(self)
parse()
pip._vendor.pkg_resources.Requirement.parse (str | Iterable[str] s) static
Definition at line 3475 of file __init__.py.
    def parse(s: str | Iterable[str]):
        (req,) = parse_requirements(s)
        return req
Referenced by pip._vendor.rich.style.Style.normalize().
Member Data Documentation
extras
tuple[str] pip._vendor.pkg_resources.Requirement.extras = tuple(map(safe_extra, self.extras))
Definition at line 3440 of file __init__.py.
hashCmp
tuple pip._vendor.pkg_resources.Requirement.hashCmp
Initial value:
=  (
            self.key,
            self.url,
            self.specifier,
            frozenset(self.extras),
            str(self.marker) if self.marker else None,
        )
Definition at line 3441 of file __init__.py.
key
pip._vendor.pkg_resources.Requirement.key = project_name, project_name.lower()
Definition at line 3437 of file __init__.py.
Referenced by tomlkit.items.SingleKey.__eq__(), tomlkit.items.SingleKey.__hash__(), and pip._internal.self_outdated_check.SelfCheckState.set().
project_name
pip._vendor.pkg_resources.Requirement.project_name
Definition at line 3437 of file __init__.py.
Referenced by pip._internal.resolution.resolvelib.candidates._InstallRequirementBackedCandidate.name(), and pip._internal.resolution.resolvelib.candidates.AlreadyInstalledCandidate.name().
specs
list pip._vendor.pkg_resources.Requirement.specs = [(spec.operator, spec.version) for spec in self.specifier]
Definition at line 3438 of file __init__.py.
unsafe_name
pip._vendor.pkg_resources.Requirement.unsafe_name = self.name
Definition at line 3435 of file __init__.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/pkg_resources/__init__.py