Read&Watch: django.core.serializers.xml_serializer.DefusedExpatParser Class Reference
django.core.serializers.xml_serializer.DefusedExpatParser Class Reference
Public Member Functions
__init__ (self, *args, **kwargs)
start_doctype_decl (self, name, sysid, pubid, has_internal_subset)
entity_decl (self, name, is_parameter_entity, value, base, sysid, pubid, notation_name)
unparsed_entity_decl (self, name, base, sysid, pubid, notation_name)
external_entity_ref_handler (self, context, base, sysid, pubid)
reset (self)
Detailed Description
An expat parser hardened against XML bomb attacks.
Forbid DTDs, external entity references
Definition at line 414 of file xml_serializer.py.
Constructor & Destructor Documentation
__init__()
django.core.serializers.xml_serializer.DefusedExpatParser.__init__ (self, * args, ** kwargs)
Definition at line 421 of file xml_serializer.py.
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.setFeature(handler.feature_external_ges, False)
        self.setFeature(handler.feature_external_pes, False)
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Function Documentation
entity_decl()
django.core.serializers.xml_serializer.DefusedExpatParser.entity_decl (self, name, is_parameter_entity, value, base, sysid, pubid, notation_name)
Definition at line 429 of file xml_serializer.py.
    ):
        raise EntitiesForbidden(name, value, base, sysid, pubid, notation_name)
Referenced by reset().
external_entity_ref_handler()
django.core.serializers.xml_serializer.DefusedExpatParser.external_entity_ref_handler (self, context, base, sysid, pubid)
Definition at line 438 of file xml_serializer.py.
    def external_entity_ref_handler(self, context, base, sysid, pubid):
        raise ExternalReferenceForbidden(context, base, sysid, pubid)
Referenced by reset().
reset()
django.core.serializers.xml_serializer.DefusedExpatParser.reset (self)
Definition at line 441 of file xml_serializer.py.
    def reset(self):
        _ExpatParser.reset(self)
        parser = self._parser
        parser.StartDoctypeDeclHandler = self.start_doctype_decl
        parser.EntityDeclHandler = self.entity_decl
        parser.UnparsedEntityDeclHandler = self.unparsed_entity_decl
        parser.ExternalEntityRefHandler = self.external_entity_ref_handler
References entity_decl(), external_entity_ref_handler(), start_doctype_decl(), and unparsed_entity_decl().
Referenced by responses.RequestsMock.__exit__(), django.utils.html.MLStripper.__init__(), pylint.extensions.mccabe.PathGraphingAstVisitor._subgraph(), pylint.testutils.reporter_for_tests.GenericTestReporter.finalize(), and PIL.TiffImagePlugin.ImageFileDirectory_v2.load().
start_doctype_decl()
django.core.serializers.xml_serializer.DefusedExpatParser.start_doctype_decl (self, name, sysid, pubid, has_internal_subset)
Definition at line 426 of file xml_serializer.py.
    def start_doctype_decl(self, name, sysid, pubid, has_internal_subset):
        raise DTDForbidden(name, sysid, pubid)
Referenced by reset().
unparsed_entity_decl()
django.core.serializers.xml_serializer.DefusedExpatParser.unparsed_entity_decl (self, name, base, sysid, pubid, notation_name)
Definition at line 434 of file xml_serializer.py.
    def unparsed_entity_decl(self, name, base, sysid, pubid, notation_name):
        # expat 1.2
        raise EntitiesForbidden(name, None, base, sysid, pubid, notation_name)
Referenced by reset().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/core/serializers/xml_serializer.py