Read&Watch: pip._internal.commands.help.HelpCommand Class Reference
pip._internal.commands.help.HelpCommand Class Reference
Public Member Functions
int run (self, Values options, List[str] args)
Public Member Functions inherited from pip._internal.cli.base_command.Command
None __init__ (self, str name, str summary, bool isolated=False)
None add_options (self)
None handle_pip_version_check (self, Values options)
Tuple[Values, List[str]] parse_args (self, List[str] args)
int main (self, List[str] args)
Public Member Functions inherited from pip._internal.cli.command_context.CommandContextMixIn
None __init__ (self)
Generator[None, None, None] main_context (self)
_T enter_context (self, ContextManager[_T] context_provider)
Additional Inherited Members
Public Attributes inherited from pip._internal.cli.base_command.Command
name = name
summary = summary
parser
Optional[TempDirRegistry] tempdir_registry = None
cmd_opts = optparse.OptionGroup(self.parser, optgroup_name)
verbosity = options.verbose - options.quiet
Static Public Attributes inherited from pip._internal.cli.base_command.Command
str usage = ""
bool ignore_require_venv = False
Protected Member Functions inherited from pip._internal.cli.base_command.Command
int _run_wrapper (self, int level_number, Values options, List[str] args)
int _main (self, List[str] args)
Protected Attributes inherited from pip._internal.cli.command_context.CommandContextMixIn
bool _in_main_context = False
_main_context = ExitStack()
Detailed Description
Show help for commands
Definition at line 9 of file help.py.
Member Function Documentation
run()
int pip._internal.commands.help.HelpCommand.run (self, Values options, List[str] args)
Reimplemented from pip._internal.cli.base_command.Command.
Definition at line 16 of file help.py.
    def run(self, options: Values, args: List[str]) -> int:
        from pip._internal.commands import (
            commands_dict,
            create_command,
            get_similar_commands,
        )
        try:
            # 'pip help' with no args is handled by pip.__init__.parseopt()
            cmd_name = args[0]  # the command we need help for
        except IndexError:
            return SUCCESS
        if cmd_name not in commands_dict:
            guess = get_similar_commands(cmd_name)
            msg = [f'unknown command "{cmd_name}"']
            if guess:
                msg.append(f'maybe you meant "{guess}"')
            raise CommandError(" - ".join(msg))
        command = create_command(cmd_name)
        command.parser.print_help()
        return SUCCESS
References pip._internal.commands.create_command(), and pip._internal.commands.get_similar_commands().
Referenced by pylint.pyreverse.main.Run.__init__().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_internal/commands/help.py