Read&Watch: isort.exceptions.SortingFunctionDoesNotExist Class Reference
isort.exceptions.SortingFunctionDoesNotExist Class Reference
Public Member Functions
__init__ (self, str sort_order, List[str] available_sort_orders)
Public Member Functions inherited from isort.exceptions.ISortError
__reduce__ (self)
Public Attributes
sort_order = sort_order
available_sort_orders = available_sort_orders
Detailed Description
Raised when the specified sorting function isn't available
Definition at line 91 of file exceptions.py.
Constructor & Destructor Documentation
__init__()
isort.exceptions.SortingFunctionDoesNotExist.__init__ (self, str sort_order, List[str] available_sort_orders)
Definition at line 94 of file exceptions.py.
    def __init__(self, sort_order: str, available_sort_orders: List[str]):
        super().__init__(
            f"Specified sort_order of {sort_order} does not exist. "
            f"Available sort_orders: {','.join(available_sort_orders)}."
        )
        self.sort_order = sort_order
        self.available_sort_orders = available_sort_orders
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Data Documentation
available_sort_orders
isort.exceptions.SortingFunctionDoesNotExist.available_sort_orders = available_sort_orders
Definition at line 100 of file exceptions.py.
sort_order
isort.exceptions.SortingFunctionDoesNotExist.sort_order = sort_order
Definition at line 99 of file exceptions.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/isort/exceptions.py