Read&Watch: pip._internal.commands.freeze.FreezeCommand Class Reference
pip._internal.commands.freeze.FreezeCommand Class Reference
Public Member Functions
None add_options (self)
int run (self, Values options, List[str] args)
Public Member Functions inherited from pip._internal.cli.base_command.Command
None __init__ (self, str name, str summary, bool isolated=False)
None handle_pip_version_check (self, Values options)
Tuple[Values, List[str]] parse_args (self, List[str] args)
int main (self, List[str] args)
Public Member Functions inherited from pip._internal.cli.command_context.CommandContextMixIn
None __init__ (self)
Generator[None, None, None] main_context (self)
_T enter_context (self, ContextManager[_T] context_provider)
Static Public Attributes
tuple log_streams = ("ext://sys.stderr", "ext://sys.stderr")
Static Public Attributes inherited from pip._internal.cli.base_command.Command
str usage = ""
bool ignore_require_venv = False
Additional Inherited Members
Public Attributes inherited from pip._internal.cli.base_command.Command
name = name
summary = summary
parser
Optional[TempDirRegistry] tempdir_registry = None
cmd_opts = optparse.OptionGroup(self.parser, optgroup_name)
verbosity = options.verbose - options.quiet
Protected Member Functions inherited from pip._internal.cli.base_command.Command
int _run_wrapper (self, int level_number, Values options, List[str] args)
int _main (self, List[str] args)
Protected Attributes inherited from pip._internal.cli.command_context.CommandContextMixIn
bool _in_main_context = False
_main_context = ExitStack()
Detailed Description
Output installed packages in requirements format.
packages are listed in a case-insensitive sorted order.
Definition at line 25 of file freeze.py.
Member Function Documentation
add_options()
None pip._internal.commands.freeze.FreezeCommand.add_options (self)
Reimplemented from pip._internal.cli.base_command.Command.
Definition at line 37 of file freeze.py.
    def add_options(self) -> None:
        self.cmd_opts.add_option(
            "-r",
            "--requirement",
            dest="requirements",
            action="append",
            default=[],
            metavar="file",
            help=(
                "Use the order in the given requirements file and its "
                "comments when generating output. This option can be "
                "used multiple times."
            ),
        )
        self.cmd_opts.add_option(
            "-l",
            "--local",
            dest="local",
            action="store_true",
            default=False,
            help=(
                "If in a virtualenv that has global access, do not output "
                "globally-installed packages."
            ),
        )
        self.cmd_opts.add_option(
            "--user",
            dest="user",
            action="store_true",
            default=False,
            help="Only output packages installed in user-site.",
        )
        self.cmd_opts.add_option(cmdoptions.list_path())
        self.cmd_opts.add_option(
            "--all",
            dest="freeze_all",
            action="store_true",
            help=(
                "Do not skip these packages in the output:"
                " {}".format(", ".join(_dev_pkgs()))
            ),
        )
        self.cmd_opts.add_option(
            "--exclude-editable",
            dest="exclude_editable",
            action="store_true",
            help="Exclude editable package from output.",
        )
        self.cmd_opts.add_option(cmdoptions.list_exclude())
        self.parser.insert_option_group(0, self.cmd_opts)
References pip._internal.commands.freeze._dev_pkgs(), and pip._internal.cli.base_command.Command.cmd_opts.
run()
int pip._internal.commands.freeze.FreezeCommand.run (self, Values options, List[str] args)
Reimplemented from pip._internal.cli.base_command.Command.
Definition at line 89 of file freeze.py.
    def run(self, options: Values, args: List[str]) -> int:
        skip = set(stdlib_pkgs)
        if not options.freeze_all:
            skip.update(_dev_pkgs())
        if options.excludes:
            skip.update(options.excludes)
        cmdoptions.check_list_path_option(options)
        for line in freeze(
            requirement=options.requirements,
            local_only=options.local,
            user_only=options.user,
            paths=options.path,
            isolated=options.isolated_mode,
            skip=skip,
            exclude_editable=options.exclude_editable,
        ):
            sys.stdout.write(line + "\n")
        return SUCCESS
References pip._internal.commands.freeze._dev_pkgs().
Referenced by pylint.pyreverse.main.Run.__init__().
Member Data Documentation
log_streams
tuple pip._internal.commands.freeze.FreezeCommand.log_streams = ("ext://sys.stderr", "ext://sys.stderr") static
Definition at line 35 of file freeze.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_internal/commands/freeze.py