Read&Watch: pylint.checkers.base.function_checker.FunctionChecker Class Reference
pylint.checkers.base.function_checker.FunctionChecker Class Reference
Public Member Functions
None visit_functiondef (self, nodes.FunctionDef node)
None visit_asyncfunctiondef (self, nodes.AsyncFunctionDef node)
Public Member Functions inherited from pylint.checkers.base_checker.BaseChecker
None __init__ (self, PyLinter linter)
bool __gt__ (self, Any other)
bool __eq__ (self, object other)
int __hash__ (self)
str __repr__ (self)
str __str__ (self)
str get_full_documentation (self, dict[str, MessageDefinitionTuple] msgs, Iterable[tuple[str, OptionDict, Any]] options, Sequence[tuple[str, str, ReportsCallable]] reports, str|None doc=None, str|None module=None, bool show_options=True)
None add_message (self, str msgid, int|None line=None, nodes.NodeNG|None node=None, Any args=None, Confidence|None confidence=None, int|None col_offset=None, int|None end_lineno=None, int|None end_col_offset=None)
None check_consistency (self)
MessageDefinition create_message_definition_from_tuple (self, str msgid, MessageDefinitionTuple msg_tuple)
list[MessageDefinition] messages (self)
None open (self)
None close (self)
Any get_map_data (self)
None reduce_map_data (self, PyLinter linter, list[Any] data)
Public Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
None __init__ (self, _ArgumentsManager arguments_manager)
Protected Member Functions
None _check_contextmanager_generator_missing_cleanup (self, nodes.FunctionDef node)
Protected Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
Any _option_value (self, str opt)
Iterator[ tuple[str, list[tuple[str, OptionDict, Any]]]|tuple[None, dict[str, list[tuple[str, OptionDict, Any]]]]] _options_by_section (self)
Iterator[tuple[str, OptionDict, Any]] _options_and_values (self, Options|None options=None)
Static Protected Member Functions
bool _node_fails_contextmanager_cleanup (nodes.FunctionDef node, list[nodes.Yield] yield_nodes)
Additional Inherited Members
Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
linter = linter
messages
Static Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
str name = ""
dict msgs = {}
tuple reports = ()
bool enabled = True
Static Public Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
tuple options = ()
dict option_groups_descs = {}
Protected Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
_arguments_manager = arguments_manager
Detailed Description
Check if a function definition handles possible side effects.
Definition at line 17 of file function_checker.py.
Member Function Documentation
_check_contextmanager_generator_missing_cleanup()
None pylint.checkers.base.function_checker.FunctionChecker._check_contextmanager_generator_missing_cleanup (self, nodes.FunctionDef node) protected
Check a FunctionDef to find if it is a generator
that uses a contextmanager internally.
If it is, check if the contextmanager is properly cleaned up. Otherwise, add message.
:param node: FunctionDef node to check
:type node: nodes.FunctionDef
Definition at line 37 of file function_checker.py.
    ) -> None:
        """Check a FunctionDef to find if it is a generator
        that uses a contextmanager internally.
        If it is, check if the contextmanager is properly cleaned up. Otherwise, add message.
        :param node: FunctionDef node to check
        :type node: nodes.FunctionDef
        """
        # if function does not use a Yield statement, it can't be a generator
        with_nodes = list(node.nodes_of_class(nodes.With))
        if not with_nodes:
            return
        # check for Yield inside the With statement
        yield_nodes = list(
            chain.from_iterable(
                with_node.nodes_of_class(nodes.Yield) for with_node in with_nodes
            )
        )
        if not yield_nodes:
            return
        # infer the call that yields a value, and check if it is a contextmanager
        for with_node in with_nodes:
            for call, held in with_node.items:
                if held is None:
                    # if we discard the value, then we can skip checking it
                    continue
                # safe infer is a generator
                inferred_node = getattr(utils.safe_infer(call), "parent", None)
                if not isinstance(inferred_node, nodes.FunctionDef):
                    continue
                if self._node_fails_contextmanager_cleanup(inferred_node, yield_nodes):
                    self.add_message(
                        "contextmanager-generator-missing-cleanup",
                        node=with_node,
                        args=(node.name,),
                    )
References _node_fails_contextmanager_cleanup(), and pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_asyncfunctiondef(), and visit_functiondef().
_node_fails_contextmanager_cleanup()
bool pylint.checkers.base.function_checker.FunctionChecker._node_fails_contextmanager_cleanup (nodes.FunctionDef node, list[nodes.Yield] yield_nodes) static protected
Check if a node fails contextmanager cleanup.
Current checks for a contextmanager:
    - only if the context manager yields a non-constant value
    - only if the context manager lacks a finally, or does not catch GeneratorExit
    - only if some statement follows the yield, some manually cleanup happens
:param node: Node to check
:type node: nodes.FunctionDef
:return: True if fails, False otherwise
:param yield_nodes: List of Yield nodes in the function body
:type yield_nodes: list[nodes.Yield]
:rtype: bool
Definition at line 80 of file function_checker.py.
    ) -> bool:
        """Check if a node fails contextmanager cleanup.
        Current checks for a contextmanager:
            - only if the context manager yields a non-constant value
            - only if the context manager lacks a finally, or does not catch GeneratorExit
            - only if some statement follows the yield, some manually cleanup happens
        :param node: Node to check
        :type node: nodes.FunctionDef
        :return: True if fails, False otherwise
        :param yield_nodes: List of Yield nodes in the function body
        :type yield_nodes: list[nodes.Yield]
        :rtype: bool
        """
        def check_handles_generator_exceptions(try_node: nodes.Try) -> bool:
            # needs to handle either GeneratorExit, Exception, or bare except
            for handler in try_node.handlers:
                if handler.type is None:
                    # handles all exceptions (bare except)
                    return True
                inferred = utils.safe_infer(handler.type)
                if inferred and inferred.qname() in {
                    "builtins.GeneratorExit",
                    "builtins.Exception",
                }:
                    return True
            return False
        # if context manager yields a non-constant value, then continue checking
        if any(
            yield_node.value is None or isinstance(yield_node.value, nodes.Const)
            for yield_node in yield_nodes
        ):
            return False
        # Check if yield expression is last statement
        yield_nodes = list(node.nodes_of_class(nodes.Yield))
        if len(yield_nodes) == 1:
            n = yield_nodes[0].parent
            while n is not node:
                if n.next_sibling() is not None:
                    break
                n = n.parent
            else:
                # No next statement found
                return False
        # if function body has multiple Try, filter down to the ones that have a yield node
        try_with_yield_nodes = [
            try_node
            for try_node in node.nodes_of_class(nodes.Try)
            if any(try_node.nodes_of_class(nodes.Yield))
        ]
        if not try_with_yield_nodes:
            # no try blocks at all, so checks after this line do not apply
            return True
        # if the contextmanager has a finally block, then it is fine
        if all(try_node.finalbody for try_node in try_with_yield_nodes):
            return False
        # if the contextmanager catches GeneratorExit, then it is fine
        if all(
            check_handles_generator_exceptions(try_node)
            for try_node in try_with_yield_nodes
        ):
            return False
        return True
Referenced by _check_contextmanager_generator_missing_cleanup().
visit_asyncfunctiondef()
None pylint.checkers.base.function_checker.FunctionChecker.visit_asyncfunctiondef (self, nodes.AsyncFunctionDef node)
Definition at line 34 of file function_checker.py.
    def visit_asyncfunctiondef(self, node: nodes.AsyncFunctionDef) -> None:
        self._check_contextmanager_generator_missing_cleanup(node)
References _check_contextmanager_generator_missing_cleanup().
visit_functiondef()
None pylint.checkers.base.function_checker.FunctionChecker.visit_functiondef (self, nodes.FunctionDef node)
Definition at line 30 of file function_checker.py.
    def visit_functiondef(self, node: nodes.FunctionDef) -> None:
        self._check_contextmanager_generator_missing_cleanup(node)
References _check_contextmanager_generator_missing_cleanup().
Referenced by pylint.pyreverse.inspector.Linker.visit_assignname().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pylint/checkers/base/function_checker.py