Read&Watch: pip._vendor.resolvelib.providers.AbstractResolver Class Reference
pip._vendor.resolvelib.providers.AbstractResolver Class Reference
Public Member Functions
__init__ (self, provider, reporter)
resolve (self, requirements, **kwargs)
Public Attributes
provider = provider
reporter = reporter
Static Public Attributes
base_exception = Exception
Detailed Description
The thing that performs the actual resolution work.
Definition at line 112 of file providers.py.
Constructor & Destructor Documentation
__init__()
pip._vendor.resolvelib.providers.AbstractResolver.__init__ (self, provider, reporter)
Definition at line 117 of file providers.py.
    def __init__(self, provider, reporter):
        self.provider = provider
        self.reporter = reporter
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
resolve()
pip._vendor.resolvelib.providers.AbstractResolver.resolve (self, requirements, ** kwargs)
Take a collection of constraints, spit out the resolution result.
This returns a representation of the final resolution state, with one
guarenteed attribute ``mapping`` that contains resolved candidates as
values. The keys are their respective identifiers.
:param requirements: A collection of constraints.
:param kwargs: Additional keyword arguments that subclasses may accept.
:raises: ``self.base_exception`` or its subclass.
Reimplemented in pip._vendor.resolvelib.resolvers.Resolver.
Definition at line 121 of file providers.py.
    def resolve(self, requirements, **kwargs):
        """Take a collection of constraints, spit out the resolution result.
        This returns a representation of the final resolution state, with one
        guarenteed attribute ``mapping`` that contains resolved candidates as
        values. The keys are their respective identifiers.
        :param requirements: A collection of constraints.
        :param kwargs: Additional keyword arguments that subclasses may accept.
        :raises: ``self.base_exception`` or its subclass.
        """
        raise NotImplementedError
Referenced by yaml.composer.Composer.compose_mapping_node(), yaml.composer.Composer.compose_scalar_node(), yaml.composer.Composer.compose_sequence_node(), and yaml.serializer.Serializer.serialize_node().
Member Data Documentation
base_exception
pip._vendor.resolvelib.providers.AbstractResolver.base_exception = Exception static
Definition at line 115 of file providers.py.
provider
pip._vendor.resolvelib.providers.AbstractResolver.provider = provider
Definition at line 118 of file providers.py.
Referenced by pip._vendor.resolvelib.resolvers.Resolver.resolve().
reporter
pip._vendor.resolvelib.providers.AbstractResolver.reporter = reporter
Definition at line 119 of file providers.py.
Referenced by pylint.lint.pylinter.PyLinter._add_one_message(), pylint.lint.pylinter.PyLinter._report_evaluation(), pylint.lint.pylinter.PyLinter.generate_reports(), pip._vendor.resolvelib.resolvers.Resolver.resolve(), pylint.lint.pylinter.PyLinter.set_current_module(), and pylint.lint.pylinter.PyLinter.set_reporter().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/resolvelib/providers.py