Read&Watch: pip._internal.commands.cache.CacheCommand Class Reference
pip._internal.commands.cache.CacheCommand Class Reference
Public Member Functions
None add_options (self)
int run (self, Values options, List[str] args)
None get_cache_dir (self, Values options, List[Any] args)
None get_cache_info (self, Values options, List[Any] args)
None list_cache_items (self, Values options, List[Any] args)
None format_for_human (self, List[str] files)
None format_for_abspath (self, List[str] files)
None remove_cache_items (self, Values options, List[Any] args)
None purge_cache (self, Values options, List[Any] args)
Public Member Functions inherited from pip._internal.cli.base_command.Command
None __init__ (self, str name, str summary, bool isolated=False)
None handle_pip_version_check (self, Values options)
Tuple[Values, List[str]] parse_args (self, List[str] args)
int main (self, List[str] args)
Public Member Functions inherited from pip._internal.cli.command_context.CommandContextMixIn
None __init__ (self)
Generator[None, None, None] main_context (self)
_T enter_context (self, ContextManager[_T] context_provider)
Protected Member Functions
str _cache_dir (self, Values options, str subdir)
List[str] _find_http_files (self, Values options)
List[str] _find_wheels (self, Values options, str pattern)
Protected Member Functions inherited from pip._internal.cli.base_command.Command
int _run_wrapper (self, int level_number, Values options, List[str] args)
int _main (self, List[str] args)
Additional Inherited Members
Public Attributes inherited from pip._internal.cli.base_command.Command
name = name
summary = summary
parser
Optional[TempDirRegistry] tempdir_registry = None
cmd_opts = optparse.OptionGroup(self.parser, optgroup_name)
verbosity = options.verbose - options.quiet
Static Public Attributes inherited from pip._internal.cli.base_command.Command
str usage = ""
bool ignore_require_venv = False
Protected Attributes inherited from pip._internal.cli.command_context.CommandContextMixIn
bool _in_main_context = False
_main_context = ExitStack()
Detailed Description
Inspect and manage pip's wheel cache.
Subcommands:
- dir: Show the cache directory.
- info: Show information about the cache.
- list: List filenames of packages stored in the cache.
- remove: Remove one or more package from the cache.
- purge: Remove all items from the cache.
``<pattern>`` can be a glob expression or a package name.
Definition at line 15 of file cache.py.
Member Function Documentation
_cache_dir()
str pip._internal.commands.cache.CacheCommand._cache_dir (self, Values options, str subdir) protected
Definition at line 194 of file cache.py.
    def _cache_dir(self, options: Values, subdir: str) -> str:
        return os.path.join(options.cache_dir, subdir)
Referenced by _find_http_files(), _find_wheels(), and get_cache_info().
_find_http_files()
List[str] pip._internal.commands.cache.CacheCommand._find_http_files (self, Values options) protected
Definition at line 197 of file cache.py.
    def _find_http_files(self, options: Values) -> List[str]:
        old_http_dir = self._cache_dir(options, "http")
        new_http_dir = self._cache_dir(options, "http-v2")
        return filesystem.find_files(old_http_dir, "*") + filesystem.find_files(
            new_http_dir, "*"
        )
References _cache_dir().
Referenced by get_cache_info(), and remove_cache_items().
_find_wheels()
List[str] pip._internal.commands.cache.CacheCommand._find_wheels (self, Values options, str pattern) protected
Definition at line 204 of file cache.py.
    def _find_wheels(self, options: Values, pattern: str) -> List[str]:
        wheel_dir = self._cache_dir(options, "wheels")
        # The wheel filename format, as specified in PEP 427, is:
        #     {distribution}-{version}(-{build})?-{python}-{abi}-{platform}.whl
        #
        # Additionally, non-alphanumeric values in the distribution are
        # normalized to underscores (_), meaning hyphens can never occur
        # before `-{version}`.
        #
        # Given that information:
        # - If the pattern we're given contains a hyphen (-), the user is
        #   providing at least the version. Thus, we can just append `*.whl`
        #   to match the rest of it.
        # - If the pattern we're given doesn't contain a hyphen (-), the
        #   user is only providing the name. Thus, we append `-*.whl` to
        #   match the hyphen before the version, followed by anything else.
        #
        # PEP 427: https://www.python.org/dev/peps/pep-0427/
        pattern = pattern + ("*.whl" if "-" in pattern else "-*.whl")
        return filesystem.find_files(wheel_dir, pattern)
References _cache_dir().
Referenced by get_cache_info(), list_cache_items(), and remove_cache_items().
add_options()
None pip._internal.commands.cache.CacheCommand.add_options (self)
Reimplemented from pip._internal.cli.base_command.Command.
Definition at line 39 of file cache.py.
    def add_options(self) -> None:
        self.cmd_opts.add_option(
            "--format",
            action="store",
            dest="list_format",
            default="human",
            choices=("human", "abspath"),
            help="Select the output format among: human (default) or abspath",
        )
        self.parser.insert_option_group(0, self.cmd_opts)
References pip._internal.cli.base_command.Command.cmd_opts.
format_for_abspath()
None pip._internal.commands.cache.CacheCommand.format_for_abspath (self, List[str] files)
Definition at line 159 of file cache.py.
    def format_for_abspath(self, files: List[str]) -> None:
        if files:
            logger.info("\n".join(sorted(files)))
Referenced by list_cache_items().
format_for_human()
None pip._internal.commands.cache.CacheCommand.format_for_human (self, List[str] files)
Definition at line 146 of file cache.py.
    def format_for_human(self, files: List[str]) -> None:
        if not files:
            logger.info("No locally built wheels cached.")
            return
        results = []
        for filename in files:
            wheel = os.path.basename(filename)
            size = filesystem.format_file_size(filename)
            results.append(f" - {wheel} ({size})")
        logger.info("Cache contents:\n")
        logger.info("\n".join(sorted(results)))
Referenced by list_cache_items().
get_cache_dir()
None pip._internal.commands.cache.CacheCommand.get_cache_dir (self, Values options, List[Any] args)
Definition at line 83 of file cache.py.
    def get_cache_dir(self, options: Values, args: List[Any]) -> None:
        if args:
            raise CommandError("Too many arguments")
        logger.info(options.cache_dir)
Referenced by run().
get_cache_info()
None pip._internal.commands.cache.CacheCommand.get_cache_info (self, Values options, List[Any] args)
Definition at line 89 of file cache.py.
    def get_cache_info(self, options: Values, args: List[Any]) -> None:
        if args:
            raise CommandError("Too many arguments")
        num_http_files = len(self._find_http_files(options))
        num_packages = len(self._find_wheels(options, "*"))
        http_cache_location = self._cache_dir(options, "http-v2")
        old_http_cache_location = self._cache_dir(options, "http")
        wheels_cache_location = self._cache_dir(options, "wheels")
        http_cache_size = filesystem.format_size(
            filesystem.directory_size(http_cache_location)
            + filesystem.directory_size(old_http_cache_location)
        )
        wheels_cache_size = filesystem.format_directory_size(wheels_cache_location)
        message = (
            textwrap.dedent(
                """
                    Package index page cache location (pip v23.3+): {http_cache_location}
                    Package index page cache location (older pips): {old_http_cache_location}
                    Package index page cache size: {http_cache_size}
                    Number of HTTP files: {num_http_files}
                    Locally built wheels location: {wheels_cache_location}
                    Locally built wheels size: {wheels_cache_size}
                    Number of locally built wheels: {package_count}
                """  # noqa: E501
            )
            .format(
                http_cache_location=http_cache_location,
                old_http_cache_location=old_http_cache_location,
                http_cache_size=http_cache_size,
                num_http_files=num_http_files,
                wheels_cache_location=wheels_cache_location,
                package_count=num_packages,
                wheels_cache_size=wheels_cache_size,
            )
            .strip()
        )
        logger.info(message)
References _cache_dir(), _find_http_files(), and _find_wheels().
Referenced by run().
list_cache_items()
None pip._internal.commands.cache.CacheCommand.list_cache_items (self, Values options, List[Any] args)
Definition at line 131 of file cache.py.
    def list_cache_items(self, options: Values, args: List[Any]) -> None:
        if len(args) > 1:
            raise CommandError("Too many arguments")
        if args:
            pattern = args[0]
        else:
            pattern = "*"
        files = self._find_wheels(options, pattern)
        if options.list_format == "human":
            self.format_for_human(files)
        else:
            self.format_for_abspath(files)
References _find_wheels(), format_for_abspath(), and format_for_human().
Referenced by run().
purge_cache()
None pip._internal.commands.cache.CacheCommand.purge_cache (self, Values options, List[Any] args)
Definition at line 188 of file cache.py.
    def purge_cache(self, options: Values, args: List[Any]) -> None:
        if args:
            raise CommandError("Too many arguments")
        return self.remove_cache_items(options, ["*"])
References remove_cache_items().
Referenced by run().
remove_cache_items()
None pip._internal.commands.cache.CacheCommand.remove_cache_items (self, Values options, List[Any] args)
Definition at line 163 of file cache.py.
    def remove_cache_items(self, options: Values, args: List[Any]) -> None:
        if len(args) > 1:
            raise CommandError("Too many arguments")
        if not args:
            raise CommandError("Please provide a pattern")
        files = self._find_wheels(options, args[0])
        no_matching_msg = "No matching packages"
        if args[0] == "*":
            # Only fetch http files if no specific pattern given
            files += self._find_http_files(options)
        else:
            # Add the pattern to the log message
            no_matching_msg += f' for pattern "{args[0]}"'
        if not files:
            logger.warning(no_matching_msg)
        for filename in files:
            os.unlink(filename)
            logger.verbose("Removed %s", filename)
        logger.info("Files removed: %s", len(files))
References _find_http_files(), and _find_wheels().
Referenced by purge_cache(), and run().
run()
int pip._internal.commands.cache.CacheCommand.run (self, Values options, List[str] args)
Reimplemented from pip._internal.cli.base_command.Command.
Definition at line 51 of file cache.py.
    def run(self, options: Values, args: List[str]) -> int:
        handlers = {
            "dir": self.get_cache_dir,
            "info": self.get_cache_info,
            "list": self.list_cache_items,
            "remove": self.remove_cache_items,
            "purge": self.purge_cache,
        }
        if not options.cache_dir:
            logger.error("pip cache commands can not function since cache is disabled.")
            return ERROR
        # Determine action
        if not args or args[0] not in handlers:
            logger.error(
                "Need an action (%s) to perform.",
                ", ".join(sorted(handlers)),
            )
            return ERROR
        action = args[0]
        # Error handling happens here, not in the action-handlers.
        try:
            handlers[action](options, args[1:])
        except PipError as e:
            logger.error(e.args[0])
            return ERROR
        return SUCCESS
References get_cache_dir(), get_cache_info(), list_cache_items(), purge_cache(), and remove_cache_items().
Referenced by pylint.pyreverse.main.Run.__init__().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_internal/commands/cache.py