Read&Watch: apscheduler.triggers.cron.expressions.RangeExpression Class Reference
apscheduler.triggers.cron.expressions.RangeExpression Class Reference
Public Member Functions
__init__ (self, first, last=None, step=None)
validate_range (self, field_name)
get_next_value (self, date, field)
__eq__ (self, other)
__str__ (self)
__repr__ (self)
Public Member Functions inherited from apscheduler.triggers.cron.expressions.AllExpression
__init__ (self, step=None)
__eq__ (self, other)
__str__ (self)
__repr__ (self)
Public Attributes
first = first
last = last
Public Attributes inherited from apscheduler.triggers.cron.expressions.AllExpression
int step = asint(step)
Additional Inherited Members
Static Public Attributes inherited from apscheduler.triggers.cron.expressions.AllExpression
value_re = re.compile(r"\*(?:/(?P<step>\d+))?$")
Detailed Description
Definition at line 78 of file expressions.py.
Constructor & Destructor Documentation
__init__()
apscheduler.triggers.cron.expressions.RangeExpression.__init__ (self, first, last = None, step = None)
Definition at line 81 of file expressions.py.
    def __init__(self, first, last=None, step=None):
        super().__init__(step)
        first = asint(first)
        last = asint(last)
        if last is None and step is None:
            last = first
        if last is not None and first > last:
            raise ValueError(
                "The minimum value in a range must not be higher than the maximum"
            )
        self.first = first
        self.last = last
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Function Documentation
__eq__()
apscheduler.triggers.cron.expressions.RangeExpression.__eq__ (self, other)
Definition at line 130 of file expressions.py.
    def __eq__(self, other):
        return (
            isinstance(other, self.__class__)
            and self.first == other.first
            and self.last == other.last
        )
References apscheduler.triggers.cron.expressions.AllExpression.__class__, first, and last.
Referenced by pip._vendor.distlib.version.Version.__ge__(), pip._vendor.distlib.version.Version.__gt__(), pip._vendor.distlib.version.Version.__le__(), dotenv.variables.Atom.__ne__(), pip._vendor.distlib.version.Matcher.__ne__(), pip._vendor.distlib.version.Version.__ne__(), pip._vendor.msgpack.ext.Timestamp.__ne__(), pip._vendor.urllib3._collections.HTTPHeaderDict.__ne__(), responses.BaseResponse.__ne__(), and urllib3._collections.HTTPHeaderDict.__ne__().
__repr__()
apscheduler.triggers.cron.expressions.RangeExpression.__repr__ (self)
Definition at line 148 of file expressions.py.
    def __repr__(self):
        args = [str(self.first)]
        if self.last != self.first and self.last is not None or self.step:
            args.append(str(self.last))
        if self.step:
            args.append(str(self.step))
        return "{}({})".format(self.__class__.__name__, ", ".join(args))
References apscheduler.triggers.cron.expressions.AllExpression.__class__, first, last, and apscheduler.triggers.cron.expressions.AllExpression.step.
__str__()
apscheduler.triggers.cron.expressions.RangeExpression.__str__ (self)
Definition at line 137 of file expressions.py.
    def __str__(self):
        if self.last != self.first and self.last is not None:
            range = "%d-%d" % (self.first, self.last)
        else:
            range = str(self.first)
        if self.step:
            return "%s/%d" % (range, self.step)
        return range
References first, last, and apscheduler.triggers.cron.expressions.AllExpression.step.
Referenced by PIL.PdfParser.IndirectReference.__bytes__().
get_next_value()
apscheduler.triggers.cron.expressions.RangeExpression.get_next_value (self, date, field)
Reimplemented from apscheduler.triggers.cron.expressions.AllExpression.
Definition at line 113 of file expressions.py.
    def get_next_value(self, date, field):
        startval = field.get_value(date)
        minval = field.get_min(date)
        maxval = field.get_max(date)
        # Apply range limits
        minval = max(minval, self.first)
        maxval = min(maxval, self.last) if self.last is not None else maxval
        nextval = max(minval, startval)
        # Apply the step if defined
        if self.step:
            distance_to_next = (self.step - (nextval - minval)) % self.step
            nextval += distance_to_next
        return nextval if nextval <= maxval else None
References first, and last.
validate_range()
apscheduler.triggers.cron.expressions.RangeExpression.validate_range (self, field_name)
Reimplemented from apscheduler.triggers.cron.expressions.AllExpression.
Definition at line 94 of file expressions.py.
    def validate_range(self, field_name):
        from apscheduler.triggers.cron.fields import MAX_VALUES, MIN_VALUES
        super().validate_range(field_name)
        if self.first < MIN_VALUES[field_name]:
            raise ValueError(
                f"the first value ({self.first}) is lower than the minimum value ({MIN_VALUES[field_name]})"
            )
        if self.last is not None and self.last > MAX_VALUES[field_name]:
            raise ValueError(
                f"the last value ({self.last}) is higher than the maximum value ({MAX_VALUES[field_name]})"
            )
        value_range = (self.last or MAX_VALUES[field_name]) - self.first
        if self.step and self.step > value_range:
            raise ValueError(
                f"the step value ({self.step}) is higher than the total range of the "
                f"expression ({value_range})"
            )
References first, last, apscheduler.triggers.cron.expressions.AllExpression.step, and validate_range().
Referenced by validate_range().
Member Data Documentation
first
apscheduler.triggers.cron.expressions.RangeExpression.first = first
Definition at line 91 of file expressions.py.
Referenced by __eq__(), apscheduler.triggers.cron.expressions.MonthRangeExpression.__repr__(), __repr__(), apscheduler.triggers.cron.expressions.WeekdayRangeExpression.__repr__(), django.template.smartif.TokenBase.__repr__(), apscheduler.triggers.cron.expressions.MonthRangeExpression.__str__(), __str__(), apscheduler.triggers.cron.expressions.WeekdayRangeExpression.__str__(), get_next_value(), crispy_forms.templatetags.crispy_forms_tags.ForLoopSimulator.iterate(), and validate_range().
last
apscheduler.triggers.cron.expressions.RangeExpression.last = last
Definition at line 92 of file expressions.py.
Referenced by __eq__(), apscheduler.triggers.cron.expressions.MonthRangeExpression.__repr__(), __repr__(), apscheduler.triggers.cron.expressions.WeekdayRangeExpression.__repr__(), apscheduler.triggers.cron.expressions.MonthRangeExpression.__str__(), __str__(), apscheduler.triggers.cron.expressions.WeekdayRangeExpression.__str__(), pip._vendor.rich.pretty._Line.__str__(), pip._vendor.rich.pretty._Line.expand(), get_next_value(), crispy_forms.templatetags.crispy_forms_tags.ForLoopSimulator.iterate(), pip._vendor.pygments.scanner.Scanner.scan(), and validate_range().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/apscheduler/triggers/cron/expressions.py