Read&Watch: django.test.utils.Approximate Class Reference
django.test.utils.Approximate Class Reference
Public Member Functions
__init__ (self, val, places=7)
__repr__ (self)
__eq__ (self, other)
Public Attributes
int val = val
places = places
Detailed Description
Definition at line 61 of file utils.py.
Constructor & Destructor Documentation
__init__()
django.test.utils.Approximate.__init__ (self, val, places = 7)
Definition at line 62 of file utils.py.
    def __init__(self, val, places=7):
        self.val = val
        self.places = places
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
__eq__()
django.test.utils.Approximate.__eq__ (self, other)
Definition at line 69 of file utils.py.
    def __eq__(self, other):
        return self.val == other or round(abs(self.val - other), self.places) == 0
References places, and val.
Referenced by pip._vendor.distlib.version.Version.__ge__(), pip._vendor.distlib.version.Version.__gt__(), pip._vendor.distlib.version.Version.__le__(), dotenv.variables.Atom.__ne__(), pip._vendor.distlib.version.Matcher.__ne__(), pip._vendor.distlib.version.Version.__ne__(), pip._vendor.msgpack.ext.Timestamp.__ne__(), pip._vendor.urllib3._collections.HTTPHeaderDict.__ne__(), responses.BaseResponse.__ne__(), and urllib3._collections.HTTPHeaderDict.__ne__().
__repr__()
django.test.utils.Approximate.__repr__ (self)
Definition at line 66 of file utils.py.
    def __repr__(self):
        return repr(self.val)
References val.
Member Data Documentation
places
django.test.utils.Approximate.places = places
Definition at line 64 of file utils.py.
Referenced by __eq__().
val
django.test.utils.Approximate.val = val
Definition at line 63 of file utils.py.
Referenced by __eq__(), and __repr__().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/test/utils.py