Read&Watch: mccabe.PathGraphingAstVisitor Class Reference
mccabe.PathGraphingAstVisitor Class Reference
Public Member Functions
__init__ (self)
reset (self)
dispatch_list (self, node_list)
visitFunctionDef (self, node)
visitClassDef (self, node)
appendPathNode (self, name)
visitSimpleStatement (self, node)
default (self, node, *args)
visitLoop (self, node)
visitIf (self, node)
visitTryExcept (self, node)
visitWith (self, node)
Public Member Functions inherited from mccabe.ASTVisitor
__init__ (self)
dispatch (self, node, *args)
preorder (self, tree, visitor, *args)
Public Attributes
str classname = ""
dict graphs = {}
graph = None
tail = None
Public Attributes inherited from mccabe.ASTVisitor
node = None
visitor = visitor
Static Public Attributes
visitAsyncFunctionDef = visitFunctionDef
visitAsyncFor = visitLoop
visitTry = visitTryExcept
visitAsyncWith = visitWith
Protected Member Functions
_subgraph (self, node, name, extra_blocks=())
_subgraph_parse (self, node, pathnode, extra_blocks)
Additional Inherited Members
Protected Attributes inherited from mccabe.ASTVisitor
dict _cache = {}
Detailed Description
 A visitor for a parsed Abstract Syntax Tree which finds executable
    statements.
Definition at line 94 of file mccabe.py.
Constructor & Destructor Documentation
__init__()
mccabe.PathGraphingAstVisitor.__init__ (self)
Definition at line 99 of file mccabe.py.
    def __init__(self):
        super(PathGraphingAstVisitor, self).__init__()
        self.classname = ""
        self.graphs = {}
        self.reset()
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
_subgraph()
mccabe.PathGraphingAstVisitor._subgraph (self, node, name, extra_blocks = ()) protected
create the subgraphs representing any `if` and `for` statements
Definition at line 179 of file mccabe.py.
    def _subgraph(self, node, name, extra_blocks=()):
        """create the subgraphs representing any `if` and `for` statements"""
        if self.graph is None:
            # global loop
            self.graph = PathGraph(name, name, node.lineno, node.col_offset)
            pathnode = PathNode(name)
            self._subgraph_parse(node, pathnode, extra_blocks)
            self.graphs["%s%s" % (self.classname, name)] = self.graph
            self.reset()
        else:
            pathnode = self.appendPathNode(name)
            self._subgraph_parse(node, pathnode, extra_blocks)
_subgraph_parse()
mccabe.PathGraphingAstVisitor._subgraph_parse (self, node, pathnode, extra_blocks) protected
parse the body and any `else` block of `if` and `for` statements
Definition at line 192 of file mccabe.py.
    def _subgraph_parse(self, node, pathnode, extra_blocks):
        """parse the body and any `else` block of `if` and `for` statements"""
        loose_ends = []
        self.tail = pathnode
        self.dispatch_list(node.body)
        loose_ends.append(self.tail)
        for extra in extra_blocks:
            self.tail = pathnode
            self.dispatch_list(extra.body)
            loose_ends.append(self.tail)
        if node.orelse:
            self.tail = pathnode
            self.dispatch_list(node.orelse)
            loose_ends.append(self.tail)
        else:
            loose_ends.append(pathnode)
        if pathnode:
            bottom = PathNode("", look='point')
            for le in loose_ends:
                self.graph.connect(le, bottom)
            self.tail = bottom
Referenced by pylint.extensions.mccabe.PathGraphingAstVisitor._subgraph().
appendPathNode()
mccabe.PathGraphingAstVisitor.appendPathNode (self, name)
Definition at line 147 of file mccabe.py.
    def appendPathNode(self, name):
        if not self.tail:
            return
        pathnode = PathNode(name)
        self.graph.connect(self.tail, pathnode)
        self.tail = pathnode
        return pathnode
default()
mccabe.PathGraphingAstVisitor.default (self, node, * args)
Reimplemented from mccabe.ASTVisitor.
Definition at line 163 of file mccabe.py.
    def default(self, node, *args):
        if isinstance(node, ast.stmt):
            self.visitSimpleStatement(node)
        else:
            super(PathGraphingAstVisitor, self).default(node, *args)
dispatch_list()
mccabe.PathGraphingAstVisitor.dispatch_list (self, node_list)
Definition at line 109 of file mccabe.py.
    def dispatch_list(self, node_list):
        for node in node_list:
            self.dispatch(node)
Referenced by pylint.extensions.mccabe.PathGraphingAstVisitor._subgraph_parse(), and pylint.extensions.mccabe.PathGraphingAstVisitor.visitWith().
reset()
mccabe.PathGraphingAstVisitor.reset (self)
Definition at line 105 of file mccabe.py.
    def reset(self):
        self.graph = None
        self.tail = None
Referenced by responses.RequestsMock.__exit__(), django.utils.html.MLStripper.__init__(), pylint.extensions.mccabe.PathGraphingAstVisitor._subgraph(), pylint.testutils.reporter_for_tests.GenericTestReporter.finalize(), and PIL.TiffImagePlugin.ImageFileDirectory_v2.load().
visitClassDef()
mccabe.PathGraphingAstVisitor.visitClassDef (self, node)
Definition at line 141 of file mccabe.py.
    def visitClassDef(self, node):
        old_classname = self.classname
        self.classname += node.name + "."
        self.dispatch_list(node.body)
        self.classname = old_classname
visitFunctionDef()
mccabe.PathGraphingAstVisitor.visitFunctionDef (self, node)
Definition at line 113 of file mccabe.py.
    def visitFunctionDef(self, node):
        if self.classname:
            entity = '%s%s' % (self.classname, node.name)
        else:
            entity = node.name
        name = '%d:%d: %r' % (node.lineno, node.col_offset, entity)
        if self.graph is not None:
            # closure
            pathnode = self.appendPathNode(name)
            self.tail = pathnode
            self.dispatch_list(node.body)
            bottom = PathNode("", look='point')
            self.graph.connect(self.tail, bottom)
            self.graph.connect(pathnode, bottom)
            self.tail = bottom
        else:
            self.graph = PathGraph(name, entity, node.lineno, node.col_offset)
            pathnode = PathNode(name)
            self.tail = pathnode
            self.dispatch_list(node.body)
            self.graphs["%s%s" % (self.classname, node.name)] = self.graph
            self.reset()
visitIf()
mccabe.PathGraphingAstVisitor.visitIf (self, node)
Definition at line 175 of file mccabe.py.
    def visitIf(self, node):
        name = "If %d" % node.lineno
        self._subgraph(node, name)
visitLoop()
mccabe.PathGraphingAstVisitor.visitLoop (self, node)
Definition at line 169 of file mccabe.py.
    def visitLoop(self, node):
        name = "Loop %d" % node.lineno
        self._subgraph(node, name)
visitSimpleStatement()
mccabe.PathGraphingAstVisitor.visitSimpleStatement (self, node)
Definition at line 155 of file mccabe.py.
    def visitSimpleStatement(self, node):
        if node.lineno is None:
            lineno = 0
        else:
            lineno = node.lineno
        name = "Stmt %d" % lineno
        self.appendPathNode(name)
visitTryExcept()
mccabe.PathGraphingAstVisitor.visitTryExcept (self, node)
Definition at line 214 of file mccabe.py.
    def visitTryExcept(self, node):
        name = "TryExcept %d" % node.lineno
        self._subgraph(node, name, extra_blocks=node.handlers)
visitWith()
mccabe.PathGraphingAstVisitor.visitWith (self, node)
Definition at line 220 of file mccabe.py.
    def visitWith(self, node):
        name = "With %d" % node.lineno
        self.appendPathNode(name)
        self.dispatch_list(node.body)
Member Data Documentation
classname
mccabe.PathGraphingAstVisitor.classname = ""
Definition at line 101 of file mccabe.py.
graph
mccabe.PathGraphingAstVisitor.graph = None
Definition at line 106 of file mccabe.py.
Referenced by pylint.extensions.mccabe.PathGraphingAstVisitor._append_node(), pylint.extensions.mccabe.PathGraphingAstVisitor._subgraph(), pylint.extensions.mccabe.PathGraphingAstVisitor._subgraph_parse(), and pylint.extensions.mccabe.PathGraphingAstVisitor.visitFunctionDef().
graphs
dict mccabe.PathGraphingAstVisitor.graphs = {}
Definition at line 102 of file mccabe.py.
Referenced by pylint.extensions.mccabe.PathGraphingAstVisitor._subgraph().
tail
mccabe.PathGraphingAstVisitor.tail = None
Definition at line 107 of file mccabe.py.
Referenced by pylint.extensions.mccabe.PathGraphingAstVisitor._append_node(), and pylint.extensions.mccabe.PathGraphingAstVisitor._subgraph_parse().
visitAsyncFor
mccabe.PathGraphingAstVisitor.visitAsyncFor = visitLoop static
Definition at line 173 of file mccabe.py.
visitAsyncFunctionDef
mccabe.PathGraphingAstVisitor.visitAsyncFunctionDef = visitFunctionDef static
Definition at line 139 of file mccabe.py.
visitAsyncWith
mccabe.PathGraphingAstVisitor.visitAsyncWith = visitWith static
Definition at line 225 of file mccabe.py.
visitTry
mccabe.PathGraphingAstVisitor.visitTry = visitTryExcept static
Definition at line 218 of file mccabe.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/mccabe.py