Read&Watch: django.contrib.auth.backends.BaseBackend Class Reference
django.contrib.auth.backends.BaseBackend Class Reference
Public Member Functions
authenticate (self, request, **kwargs)
get_user (self, user_id)
get_user_permissions (self, user_obj, obj=None)
get_group_permissions (self, user_obj, obj=None)
get_all_permissions (self, user_obj, obj=None)
has_perm (self, user_obj, perm, obj=None)
Detailed Description
Definition at line 8 of file backends.py.
Member Function Documentation
authenticate()
django.contrib.auth.backends.BaseBackend.authenticate (self, request, ** kwargs)
Reimplemented in django.contrib.auth.backends.ModelBackend, and django.contrib.auth.backends.RemoteUserBackend.
Definition at line 9 of file backends.py.
    def authenticate(self, request, **kwargs):
        return None
get_all_permissions()
django.contrib.auth.backends.BaseBackend.get_all_permissions (self, user_obj, obj = None)
Reimplemented in django.contrib.auth.backends.ModelBackend.
Definition at line 21 of file backends.py.
    def get_all_permissions(self, user_obj, obj=None):
        return {
            *self.get_user_permissions(user_obj, obj=obj),
            *self.get_group_permissions(user_obj, obj=obj),
        }
References get_group_permissions(), and get_user_permissions().
Referenced by django.contrib.auth.backends.ModelBackend.has_module_perms(), and has_perm().
get_group_permissions()
django.contrib.auth.backends.BaseBackend.get_group_permissions (self, user_obj, obj = None)
Reimplemented in django.contrib.auth.backends.ModelBackend.
Definition at line 18 of file backends.py.
    def get_group_permissions(self, user_obj, obj=None):
        return set()
Referenced by get_all_permissions().
get_user()
django.contrib.auth.backends.BaseBackend.get_user (self, user_id)
Reimplemented in django.contrib.auth.backends.ModelBackend.
Definition at line 12 of file backends.py.
    def get_user(self, user_id):
        return None
get_user_permissions()
django.contrib.auth.backends.BaseBackend.get_user_permissions (self, user_obj, obj = None)
Reimplemented in django.contrib.auth.backends.ModelBackend.
Definition at line 15 of file backends.py.
    def get_user_permissions(self, user_obj, obj=None):
        return set()
Referenced by get_all_permissions().
has_perm()
django.contrib.auth.backends.BaseBackend.has_perm (self, user_obj, perm, obj = None)
Reimplemented in django.contrib.auth.backends.ModelBackend.
Definition at line 27 of file backends.py.
    def has_perm(self, user_obj, perm, obj=None):
        return perm in self.get_all_permissions(user_obj, obj=obj)
References get_all_permissions().
Referenced by django.contrib.auth.models.AnonymousUser.has_perms(), and django.contrib.auth.models.PermissionsMixin.has_perms().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/auth/backends.py