Read&Watch: pylint.checkers.strings.StringFormatChecker Class Reference
pylint.checkers.strings.StringFormatChecker Class Reference
Public Member Functions
None visit_binop (self, nodes.BinOp node)
None visit_joinedstr (self, nodes.JoinedStr node)
None visit_call (self, nodes.Call node)
Public Member Functions inherited from pylint.checkers.base_checker.BaseChecker
None __init__ (self, PyLinter linter)
bool __gt__ (self, Any other)
bool __eq__ (self, object other)
int __hash__ (self)
str __repr__ (self)
str __str__ (self)
str get_full_documentation (self, dict[str, MessageDefinitionTuple] msgs, Iterable[tuple[str, OptionDict, Any]] options, Sequence[tuple[str, str, ReportsCallable]] reports, str|None doc=None, str|None module=None, bool show_options=True)
None add_message (self, str msgid, int|None line=None, nodes.NodeNG|None node=None, Any args=None, Confidence|None confidence=None, int|None col_offset=None, int|None end_lineno=None, int|None end_col_offset=None)
None check_consistency (self)
MessageDefinition create_message_definition_from_tuple (self, str msgid, MessageDefinitionTuple msg_tuple)
list[MessageDefinition] messages (self)
None open (self)
None close (self)
Any get_map_data (self)
None reduce_map_data (self, PyLinter linter, list[Any] data)
Public Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
None __init__ (self, _ArgumentsManager arguments_manager)
Protected Member Functions
None _check_interpolation (self, nodes.JoinedStr node)
None _detect_vacuous_formatting (self, nodes.Call node, list[SuccessfulInferenceResult] positional_arguments)
None _check_new_format (self, nodes.Call node, bases.BoundMethod func)
None _check_new_format_specifiers (self, nodes.Call node, list[tuple[str, list[tuple[bool, str]]]] fields, dict[str, SuccessfulInferenceResult] named)
Protected Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
Any _option_value (self, str opt)
Iterator[ tuple[str, list[tuple[str, OptionDict, Any]]]|tuple[None, dict[str, list[tuple[str, OptionDict, Any]]]]] _options_by_section (self)
Iterator[tuple[str, OptionDict, Any]] _options_and_values (self, Options|None options=None)
Additional Inherited Members
Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
linter = linter
messages
Static Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
str name = ""
dict msgs = {}
tuple reports = ()
bool enabled = True
Static Public Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
tuple options = ()
dict option_groups_descs = {}
Protected Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
_arguments_manager = arguments_manager
Detailed Description
Checks string formatting operations to ensure that the format string
is valid and the arguments match the format string.
Definition at line 242 of file strings.py.
Member Function Documentation
_check_interpolation()
None pylint.checkers.strings.StringFormatChecker._check_interpolation (self, nodes.JoinedStr node) protected
Definition at line 411 of file strings.py.
    def _check_interpolation(self, node: nodes.JoinedStr) -> None:
        if isinstance(node.parent, nodes.FormattedValue):
            return
        for value in node.values:
            if isinstance(value, nodes.FormattedValue):
                return
        self.add_message("f-string-without-interpolation", node=node)
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_joinedstr().
_check_new_format()
None pylint.checkers.strings.StringFormatChecker._check_new_format (self, nodes.Call node, bases.BoundMethod func) protected
Check the new string formatting.
Definition at line 452 of file strings.py.
    def _check_new_format(self, node: nodes.Call, func: bases.BoundMethod) -> None:
        """Check the new string formatting."""
        # Skip format nodes which don't have an explicit string on the
        # left side of the format operation.
        # We do this because our inference engine can't properly handle
        # redefinition of the original string.
        # Note that there may not be any left side at all, if the format method
        # has been assigned to another variable. See issue 351. For example:
        #
        #    fmt = 'some string {}'.format
        #    fmt('arg')
        if isinstance(node.func, nodes.Attribute) and not isinstance(
            node.func.expr, nodes.Const
        ):
            return
        if node.starargs or node.kwargs:
            return
        try:
            strnode = next(func.bound.infer())
        except astroid.InferenceError:
            return
        if not (isinstance(strnode, nodes.Const) and isinstance(strnode.value, str)):
            return
        try:
            call_site = astroid.arguments.CallSite.from_call(node)
        except astroid.InferenceError:
            return
        try:
            fields, num_args, manual_pos = utils.parse_format_method_string(
                strnode.value
            )
        except utils.IncompleteFormatString:
            self.add_message("bad-format-string", node=node)
            return
        positional_arguments = call_site.positional_arguments
        named_arguments = call_site.keyword_arguments
        named_fields = {field[0] for field in fields if isinstance(field[0], str)}
        if num_args and manual_pos:
            self.add_message("format-combined-specification", node=node)
            return
        check_args = False
        # Consider "{[0]} {[1]}" as num_args.
        num_args += sum(1 for field in named_fields if not field)
        if named_fields:
            for field in named_fields:
                if field and field not in named_arguments:
                    self.add_message(
                        "missing-format-argument-key", node=node, args=(field,)
                    )
            for field in named_arguments:
                if field not in named_fields:
                    self.add_message(
                        "unused-format-string-argument", node=node, args=(field,)
                    )
            # num_args can be 0 if manual_pos is not.
            num_args = num_args or manual_pos
            if positional_arguments or num_args:
                empty = not all(field for field in named_fields)
                if named_arguments or empty:
                    # Verify the required number of positional arguments
                    # only if the .format got at least one keyword argument.
                    # This means that the format strings accepts both
                    # positional and named fields and we should warn
                    # when one of them is missing or is extra.
                    check_args = True
        else:
            check_args = True
        if check_args:
            # num_args can be 0 if manual_pos is not.
            num_args = num_args or manual_pos
            if not num_args:
                self.add_message("format-string-without-interpolation", node=node)
                return
            if len(positional_arguments) > num_args:
                self.add_message("too-many-format-args", node=node)
            elif len(positional_arguments) < num_args:
                self.add_message("too-few-format-args", node=node)
        self._detect_vacuous_formatting(node, positional_arguments)
        self._check_new_format_specifiers(node, fields, named_arguments)
References _check_new_format_specifiers(), _detect_vacuous_formatting(), pylint.checkers.base_checker.BaseChecker.add_message(), and astroid.arguments.CallSite.from_call().
Referenced by visit_call().
_check_new_format_specifiers()
None pylint.checkers.strings.StringFormatChecker._check_new_format_specifiers (self, nodes.Call node, list[tuple[str, list[tuple[bool, str]]]] fields, dict[str, SuccessfulInferenceResult] named) protected
Check attribute and index access in the format
string ("{0.a}" and "{0[a]}").
Definition at line 537 of file strings.py.
    ) -> None:
        """Check attribute and index access in the format
        string ("{0.a}" and "{0[a]}").
        """
        key: Literal[0] | str
        for key, specifiers in fields:
            # Obtain the argument. If it can't be obtained
            # or inferred, skip this check.
            if not key:
                # {[0]} will have an unnamed argument, defaulting
                # to 0. It will not be present in `named`, so use the value
                # 0 for it.
                key = 0
            if isinstance(key, int):
                try:
                    argname = utils.get_argument_from_call(node, key)
                except utils.NoSuchArgumentError:
                    continue
            else:
                if key not in named:
                    continue
                argname = named[key]
            if argname is None or isinstance(argname, util.UninferableBase):
                continue
            try:
                argument = utils.safe_infer(argname)
            except astroid.InferenceError:
                continue
            if not specifiers or not argument:
                # No need to check this key if it doesn't
                # use attribute / item access
                continue
            if argument.parent and isinstance(argument.parent, nodes.Arguments):
                # Ignore any object coming from an argument,
                # because we can't infer its value properly.
                continue
            previous = argument
            parsed: list[tuple[bool, str]] = []
            for is_attribute, specifier in specifiers:
                if isinstance(previous, util.UninferableBase):
                    break
                parsed.append((is_attribute, specifier))
                if is_attribute:
                    try:
                        previous = previous.getattr(specifier)[0]
                    except astroid.NotFoundError:
                        if (
                            hasattr(previous, "has_dynamic_getattr")
                            and previous.has_dynamic_getattr()
                        ):
                            # Don't warn if the object has a custom __getattr__
                            break
                        path = get_access_path(key, parsed)
                        self.add_message(
                            "missing-format-attribute",
                            args=(specifier, path),
                            node=node,
                        )
                        break
                else:
                    warn_error = False
                    if hasattr(previous, "getitem"):
                        try:
                            previous = previous.getitem(nodes.Const(specifier))
                        except (
                            astroid.AstroidIndexError,
                            astroid.AstroidTypeError,
                            astroid.AttributeInferenceError,
                        ):
                            warn_error = True
                        except astroid.InferenceError:
                            break
                        if isinstance(previous, util.UninferableBase):
                            break
                    else:
                        try:
                            # Lookup __getitem__ in the current node,
                            # but skip further checks, because we can't
                            # retrieve the looked object
                            previous.getattr("__getitem__")
                            break
                        except astroid.NotFoundError:
                            warn_error = True
                    if warn_error:
                        path = get_access_path(key, parsed)
                        self.add_message(
                            "invalid-format-index", args=(specifier, path), node=node
                        )
                        break
                try:
                    previous = next(previous.infer())
                except astroid.InferenceError:
                    # can't check further if we can't infer it
                    break
References pylint.checkers.base_checker.BaseChecker.add_message(), and pylint.checkers.strings.get_access_path().
Referenced by _check_new_format().
_detect_vacuous_formatting()
None pylint.checkers.strings.StringFormatChecker._detect_vacuous_formatting (self, nodes.Call node, list[SuccessfulInferenceResult] positional_arguments) protected
Definition at line 439 of file strings.py.
    ) -> None:
        counter = collections.Counter(
            arg.name for arg in positional_arguments if isinstance(arg, nodes.Name)
        )
        for name, count in counter.items():
            if count == 1:
                continue
            self.add_message(
                "duplicate-string-formatting-argument", node=node, args=(name,)
            )
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by _check_new_format().
visit_binop()
None pylint.checkers.strings.StringFormatChecker.visit_binop (self, nodes.BinOp node)
Definition at line 264 of file strings.py.
    def visit_binop(self, node: nodes.BinOp) -> None:
        if node.op != "%":
            return
        left = node.left
        args = node.right
        if not (isinstance(left, nodes.Const) and isinstance(left.value, str)):
            return
        format_string = left.value
        try:
            (
                required_keys,
                required_num_args,
                required_key_types,
                required_arg_types,
            ) = utils.parse_format_string(format_string)
        except utils.UnsupportedFormatCharacter as exc:
            formatted = format_string[exc.index]
            self.add_message(
                "bad-format-character",
                node=node,
                args=(formatted, ord(formatted), exc.index),
            )
            return
        except utils.IncompleteFormatString:
            self.add_message("truncated-format-string", node=node)
            return
        if not required_keys and not required_num_args:
            self.add_message("format-string-without-interpolation", node=node)
            return
        if required_keys and required_num_args:
            # The format string uses both named and unnamed format
            # specifiers.
            self.add_message("mixed-format-string", node=node)
        elif required_keys:
            # The format string uses only named format specifiers.
            # Check that the RHS of the % operator is a mapping object
            # that contains precisely the set of keys required by the
            # format string.
            if isinstance(args, nodes.Dict):
                keys = set()
                unknown_keys = False
                for k, _ in args.items:
                    if isinstance(k, nodes.Const):
                        key = k.value
                        if isinstance(key, str):
                            keys.add(key)
                        else:
                            self.add_message(
                                "bad-format-string-key", node=node, args=key
                            )
                    else:
                        # One of the keys was something other than a
                        # constant.  Since we can't tell what it is,
                        # suppress checks for missing keys in the
                        # dictionary.
                        unknown_keys = True
                if not unknown_keys:
                    for key in required_keys:
                        if key not in keys:
                            self.add_message(
                                "missing-format-string-key", node=node, args=key
                            )
                for key in keys:
                    if key not in required_keys:
                        self.add_message(
                            "unused-format-string-key", node=node, args=key
                        )
                for key, arg in args.items:
                    if not isinstance(key, nodes.Const):
                        continue
                    format_type = required_key_types.get(key.value, None)
                    arg_type = utils.safe_infer(arg)
                    if (
                        format_type is not None
                        and arg_type
                        and not isinstance(arg_type, util.UninferableBase)
                        and not arg_matches_format_type(arg_type, format_type)
                    ):
                        self.add_message(
                            "bad-string-format-type",
                            node=node,
                            args=(arg_type.pytype(), format_type),
                        )
            elif isinstance(args, (OTHER_NODES, nodes.Tuple)):
                type_name = type(args).__name__
                self.add_message("format-needs-mapping", node=node, args=type_name)
            # else:
            # The RHS of the format specifier is a name or
            # expression.  It may be a mapping object, so
            # there's nothing we can check.
        else:
            # The format string uses only unnamed format specifiers.
            # Check that the number of arguments passed to the RHS of
            # the % operator matches the number required by the format
            # string.
            args_elts = []
            if isinstance(args, nodes.Tuple):
                rhs_tuple = utils.safe_infer(args)
                num_args = None
                if isinstance(rhs_tuple, nodes.BaseContainer):
                    args_elts = rhs_tuple.elts
                    num_args = len(args_elts)
            elif isinstance(args, (OTHER_NODES, (nodes.Dict, nodes.DictComp))):
                args_elts = [args]
                num_args = 1
            elif isinstance(args, nodes.Name):
                inferred = utils.safe_infer(args)
                if isinstance(inferred, nodes.Tuple):
                    # The variable is a tuple, so we need to get the elements
                    # from it for further inspection
                    args_elts = inferred.elts
                    num_args = len(args_elts)
                elif isinstance(inferred, nodes.Const):
                    args_elts = [inferred]
                    num_args = 1
                else:
                    num_args = None
            else:
                # The RHS of the format specifier is an expression.
                # It could be a tuple of unknown size, so
                # there's nothing we can check.
                num_args = None
            if num_args is not None:
                if num_args > required_num_args:
                    self.add_message("too-many-format-args", node=node)
                elif num_args < required_num_args:
                    self.add_message("too-few-format-args", node=node)
                for arg, format_type in zip(args_elts, required_arg_types):
                    if not arg:
                        continue
                    arg_type = utils.safe_infer(arg)
                    if (
                        arg_type
                        and not isinstance(arg_type, util.UninferableBase)
                        and not arg_matches_format_type(arg_type, format_type)
                    ):
                        self.add_message(
                            "bad-string-format-type",
                            node=node,
                            args=(arg_type.pytype(), format_type),
                        )
References pylint.checkers.base_checker.BaseChecker.add_message(), and pylint.checkers.strings.arg_matches_format_type().
visit_call()
None pylint.checkers.strings.StringFormatChecker.visit_call (self, nodes.Call node)
Definition at line 419 of file strings.py.
    def visit_call(self, node: nodes.Call) -> None:
        func = utils.safe_infer(node.func)
        if (
            isinstance(func, astroid.BoundMethod)
            and isinstance(func.bound, astroid.Instance)
            and func.bound.name in {"str", "unicode", "bytes"}
        ):
            if func.name in {"strip", "lstrip", "rstrip"} and node.args:
                arg = utils.safe_infer(node.args[0])
                if not isinstance(arg, nodes.Const) or not isinstance(arg.value, str):
                    return
                if len(arg.value) != len(set(arg.value)):
                    self.add_message(
                        "bad-str-strip-call",
                        node=node,
                        args=(func.bound.name, func.name),
                    )
            elif func.name == "format":
                self._check_new_format(node, func)
References _check_new_format(), and pylint.checkers.base_checker.BaseChecker.add_message().
visit_joinedstr()
None pylint.checkers.strings.StringFormatChecker.visit_joinedstr (self, nodes.JoinedStr node)
Definition at line 408 of file strings.py.
    def visit_joinedstr(self, node: nodes.JoinedStr) -> None:
        self._check_interpolation(node)
References _check_interpolation().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pylint/checkers/strings.py