Read&Watch: django.contrib.auth.management.commands.changepassword.Command Class Reference
django.contrib.auth.management.commands.changepassword.Command Class Reference
Public Member Functions
add_arguments (self, parser)
handle (self, *args, **options)
Public Member Functions inherited from django.core.management.base.BaseCommand
__init__ (self, stdout=None, stderr=None, no_color=False, force_color=False)
get_version (self)
create_parser (self, prog_name, subcommand, **kwargs)
add_base_argument (self, parser, *args, **kwargs)
print_help (self, prog_name, subcommand)
run_from_argv (self, argv)
execute (self, *args, **options)
check (self, app_configs=None, tags=None, display_num_errors=False, include_deployment_checks=False, fail_level=checks.ERROR, databases=None)
check_migrations (self)
Protected Member Functions
_get_pass (self, prompt="Password: ")
Additional Inherited Members
Public Attributes inherited from django.core.management.base.BaseCommand
stdout = OutputWrapper(stdout or sys.stdout)
stderr = OutputWrapper(stderr or sys.stderr)
style = no_style()
Static Public Attributes inherited from django.core.management.base.BaseCommand
str help = ""
bool output_transaction = False
bool requires_migrations_checks = False
str requires_system_checks = "__all__"
tuple base_stealth_options = ("stderr", "stdout")
tuple stealth_options = ()
suppressed_base_arguments = set()
Static Protected Attributes inherited from django.core.management.base.BaseCommand
bool _called_from_command_line = False
Detailed Description
Definition at line 12 of file changepassword.py.
Member Function Documentation
_get_pass()
django.contrib.auth.management.commands.changepassword.Command._get_pass (self, prompt = "Password: ") protected
Definition at line 17 of file changepassword.py.
    def _get_pass(self, prompt="Password: "):
        p = getpass.getpass(prompt=prompt)
        if not p:
            raise CommandError("aborted")
        return p
Referenced by handle().
add_arguments()
django.contrib.auth.management.commands.changepassword.Command.add_arguments (self, parser)
Entry point for subclassed commands to add custom arguments.
Reimplemented from django.core.management.base.BaseCommand.
Definition at line 23 of file changepassword.py.
    def add_arguments(self, parser):
        parser.add_argument(
            "username",
            nargs="?",
            help=(
                "Username to change password for; by default, it's the current "
                "username."
            ),
        )
        parser.add_argument(
            "--database",
            default=DEFAULT_DB_ALIAS,
            choices=tuple(connections),
            help='Specifies the database to use. Default is "default".',
        )
Referenced by django.core.management.base.BaseCommand.create_parser().
handle()
django.contrib.auth.management.commands.changepassword.Command.handle (self, * args, ** options)
The actual logic of the command. Subclasses must implement
this method.
Reimplemented from django.core.management.base.BaseCommand.
Definition at line 39 of file changepassword.py.
    def handle(self, *args, **options):
        if options["username"]:
            username = options["username"]
        else:
            username = getpass.getuser()
        try:
            u = UserModel._default_manager.using(options["database"]).get(
                **{UserModel.USERNAME_FIELD: username}
            )
        except UserModel.DoesNotExist:
            raise CommandError("user '%s' does not exist" % username)
        self.stdout.write("Changing password for user '%s'" % u)
        MAX_TRIES = 3
        count = 0
        p1, p2 = 1, 2  # To make them initially mismatch.
        password_validated = False
        while (p1 != p2 or not password_validated) and count < MAX_TRIES:
            p1 = self._get_pass()
            p2 = self._get_pass("Password (again): ")
            if p1 != p2:
                self.stdout.write("Passwords do not match. Please try again.")
                count += 1
                # Don't validate passwords that don't match.
                continue
            try:
                validate_password(p2, u)
            except ValidationError as err:
                self.stderr.write("\n".join(err.messages))
                count += 1
            else:
                password_validated = True
        if count == MAX_TRIES:
            raise CommandError(
                "Aborting password change for user '%s' after %s attempts" % (u, count)
            )
        u.set_password(p1)
        u.save()
        return "Password changed successfully for user '%s'" % u
References _get_pass(), django.core.management.base.BaseCommand.stderr, and django.core.management.base.BaseCommand.stdout.
Referenced by django.core.handlers.asgi.ASGIHandler.__call__(), and django.core.management.base.BaseCommand.execute().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/auth/management/commands/changepassword.py