Read&Watch: django.contrib.admin.templatetags.base.InclusionAdminNode Class Reference
django.contrib.admin.templatetags.base.InclusionAdminNode Class Reference
Public Member Functions
__init__ (self, parser, token, func, template_name, takes_context=True)
render (self, context)
Public Member Functions inherited from django.template.library.InclusionNode
__init__ (self, func, takes_context, args, kwargs, filename)
Public Member Functions inherited from django.template.library.TagHelperNode
__init__ (self, func, takes_context, args, kwargs)
get_resolved_arguments (self, context)
Public Member Functions inherited from django.template.base.Node
render_annotated (self, context)
get_nodes_by_type (self, nodetype)
Public Attributes
template_name = template_name
Public Attributes inherited from django.template.library.InclusionNode
filename = filename
Public Attributes inherited from django.template.library.TagHelperNode
func = func
takes_context = takes_context
args = args
kwargs = kwargs
Additional Inherited Members
Static Public Attributes inherited from django.template.base.Node
bool must_be_first = False
tuple child_nodelists = ("nodelist",)
token = None
Detailed Description
Template tag that allows its template to be overridden per model, per app,
or globally.
Definition at line 6 of file base.py.
Constructor & Destructor Documentation
__init__()
django.contrib.admin.templatetags.base.InclusionAdminNode.__init__ (self, parser, token, func, template_name, takes_context = True)
Definition at line 12 of file base.py.
    def __init__(self, parser, token, func, template_name, takes_context=True):
        self.template_name = template_name
        params, varargs, varkw, defaults, kwonly, kwonly_defaults, _ = getfullargspec(
            func
        )
        bits = token.split_contents()
        args, kwargs = parse_bits(
            parser,
            bits[1:],
            params,
            varargs,
            varkw,
            defaults,
            kwonly,
            kwonly_defaults,
            takes_context,
            bits[0],
        )
        super().__init__(func, takes_context, args, kwargs, filename=None)
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
render()
django.contrib.admin.templatetags.base.InclusionAdminNode.render (self, context)
Render the specified template and context. Cache the template object
in render_context to avoid reparsing and loading when used in a for
loop.
Reimplemented from django.template.library.InclusionNode.
Definition at line 32 of file base.py.
    def render(self, context):
        opts = context["opts"]
        app_label = opts.app_label.lower()
        object_name = opts.model_name
        # Load template for this render call. (Setting self.filename isn't
        # thread-safe.)
        context.render_context[self] = context.template.engine.select_template(
            [
                "admin/%s/%s/%s" % (app_label, object_name, self.template_name),
                "admin/%s/%s" % (app_label, self.template_name),
                "admin/%s" % self.template_name,
            ]
        )
        return super().render(context)
References render(), and template_name.
Referenced by pip._vendor.rich.progress.ProgressColumn.__call__(), pip._vendor.rich.layout.Layout.__rich_console__(), pip._vendor.rich.spinner.Spinner.__rich_console__(), pip._vendor.rich.spinner.Spinner.__rich_measure__(), django.forms.widgets.Media.__str__(), django.forms.utils.RenderableFieldMixin.as_field_group(), pip._vendor.rich.console.Console.log(), pip._vendor.rich.console.Console.print(), render(), django.templatetags.i18n.BlockTranslateNode.render(), pip._vendor.rich.console.Console.render(), pip._vendor.rich.console.Console.render_lines(), django.db.migrations.writer.OperationWriter.serialize(), and pip._vendor.rich.console.Console.update_screen_lines().
Member Data Documentation
template_name
django.contrib.admin.templatetags.base.InclusionAdminNode.template_name = template_name
Definition at line 13 of file base.py.
Referenced by django.views.generic.base.TemplateResponseMixin.get_template_names(), render(), django.forms.utils.RenderableMixin.render(), django.forms.widgets.Widget.render(), django.template.response.SimpleTemplateResponse.rendered_content(), django.test.testcases._AssertTemplateNotUsedContext.test(), and django.test.testcases._AssertTemplateUsedContext.test().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/admin/templatetags/base.py