Read&Watch: django.contrib.auth.password_validation.CommonPasswordValidator Class Reference
django.contrib.auth.password_validation.CommonPasswordValidator Class Reference
Public Member Functions
DEFAULT_PASSWORD_LIST_PATH (self)
__init__ (self, password_list_path=DEFAULT_PASSWORD_LIST_PATH)
validate (self, password, user=None)
get_help_text (self)
Public Attributes
dict passwords = {x.strip() for x in f}
Detailed Description
Validate that the password is not a common password.
The password is rejected if it occurs in a provided list of passwords,
which may be gzipped. The list Django ships with contains 20000 common
passwords (lowercased and deduplicated), created by Royce Williams:
https://gist.github.com/roycewilliams/226886fd01572964e1431ac8afc999ce
The password list must be lowercased to match the comparison in validate().
Definition at line 217 of file password_validation.py.
Constructor & Destructor Documentation
__init__()
django.contrib.auth.password_validation.CommonPasswordValidator.__init__ (self, password_list_path = DEFAULT_PASSWORD_LIST_PATH)
Definition at line 232 of file password_validation.py.
    def __init__(self, password_list_path=DEFAULT_PASSWORD_LIST_PATH):
        if password_list_path is CommonPasswordValidator.DEFAULT_PASSWORD_LIST_PATH:
            password_list_path = self.DEFAULT_PASSWORD_LIST_PATH
        try:
            with gzip.open(password_list_path, "rt", encoding="utf-8") as f:
                self.passwords = {x.strip() for x in f}
        except OSError:
            with open(password_list_path) as f:
                self.passwords = {x.strip() for x in f}
References DEFAULT_PASSWORD_LIST_PATH().
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
DEFAULT_PASSWORD_LIST_PATH()
django.contrib.auth.password_validation.CommonPasswordValidator.DEFAULT_PASSWORD_LIST_PATH (self)
Definition at line 229 of file password_validation.py.
    def DEFAULT_PASSWORD_LIST_PATH(self):
        return Path(__file__).resolve().parent / "common-passwords.txt.gz"
Referenced by __init__().
get_help_text()
django.contrib.auth.password_validation.CommonPasswordValidator.get_help_text (self)
Definition at line 249 of file password_validation.py.
    def get_help_text(self):
        return _("Your password can’t be a commonly used password.")
validate()
django.contrib.auth.password_validation.CommonPasswordValidator.validate (self, password, user = None)
Definition at line 242 of file password_validation.py.
    def validate(self, password, user=None):
        if password.lower().strip() in self.passwords:
            raise ValidationError(
                _("This password is too common."),
                code="password_too_common",
            )
References passwords.
Referenced by django.db.models.fields.Field.clean(), django.forms.fields.Field.clean(), and pip._vendor.distlib.metadata.Metadata.write().
Member Data Documentation
passwords
dict django.contrib.auth.password_validation.CommonPasswordValidator.passwords = {x.strip() for x in f}
Definition at line 237 of file password_validation.py.
Referenced by validate().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/auth/password_validation.py