Read&Watch: django.contrib.messages.storage.cookie.MessageEncoder Class Reference
django.contrib.messages.storage.cookie.MessageEncoder Class Reference
Public Member Functions
default (self, obj)
Static Public Attributes
str message_key = "__json_message"
Detailed Description
Compactly serialize instances of the ``Message`` class as JSON.
Definition at line 11 of file cookie.py.
Member Function Documentation
default()
django.contrib.messages.storage.cookie.MessageEncoder.default (self, obj)
Definition at line 18 of file cookie.py.
    def default(self, obj):
        if isinstance(obj, Message):
            # Using 0/1 here instead of False/True to produce more compact json
            is_safedata = 1 if isinstance(obj.message, SafeData) else 0
            message = [self.message_key, is_safedata, obj.level, obj.message]
            if obj.extra_tags is not None:
                message.append(obj.extra_tags)
            return message
        return super().default(obj)
References default(), and message_key.
Referenced by default(), and mccabe.ASTVisitor.dispatch().
Member Data Documentation
message_key
str django.contrib.messages.storage.cookie.MessageEncoder.message_key = "__json_message" static
Definition at line 16 of file cookie.py.
Referenced by default().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/messages/storage/cookie.py