Read&Watch: astroid.bases.Instance Class Reference
astroid.bases.Instance Class Reference
Public Member Functions
None __init__ (self, nodes.ClassDef|None proxied)
Generator[InferenceResult] infer_binary_op (self, nodes.AugAssign|nodes.BinOp opnode, str operator, InferenceResult other, InferenceContext context, SuccessfulInferenceResult method)
str __repr__ (self)
str __str__ (self)
bool callable (self)
str pytype (self)
str display_type (self)
bool|UninferableBase bool_value (self, InferenceContext|None context=None)
InferenceResult|None getitem (self, nodes.Const index, InferenceContext|None context=None)
Public Member Functions inherited from astroid.bases.BaseInstance
list[InferenceResult] getattr (self, str name, InferenceContext|None context=None, bool lookupclass=True)
Iterator[InferenceResult] igetattr (self, str name, InferenceContext|None context=None)
Iterator[InferenceResult] infer_call_result (self, SuccessfulInferenceResult|None caller, InferenceContext|None context=None)
Public Member Functions inherited from astroid.bases.Proxy
None __init__ (self,(nodes.ClassDef|nodes.FunctionDef|nodes.Lambda|UnboundMethod|None) proxied=None)
Any __getattr__ (self, str name)
collections.abc.Generator[InferenceResult, None, InferenceErrorInfo|None] infer (self, InferenceContext|None context=None, **Any kwargs)
Additional Inherited Members
Static Public Attributes inherited from astroid.bases.BaseInstance
objectmodel special_attributes .ObjectModel
Protected Member Functions inherited from astroid.bases.BaseInstance
Iterator[InferenceResult] _wrap_attr (self, Iterable[InferenceResult] attrs, InferenceContext|None context=None)
Static Protected Attributes inherited from astroid.bases.Proxy
nodes _proxied .ClassDef | nodes.FunctionDef | nodes.Lambda | UnboundMethod
Detailed Description
A special node representing a class instance.
Definition at line 341 of file bases.py.
Constructor & Destructor Documentation
__init__()
None astroid.bases.Instance.__init__ (self, nodes.ClassDef | None proxied)
Definition at line 346 of file bases.py.
    def __init__(self, proxied: nodes.ClassDef | None) -> None:
        super().__init__(proxied)
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Function Documentation
__repr__()
str astroid.bases.Instance.__repr__ (self)
Definition at line 360 of file bases.py.
    def __repr__(self) -> str:
        return "<Instance of {}.{} at 0x{}>".format(
            self._proxied.root().name, self._proxied.name, id(self)
        )
References astroid.bases.Proxy._proxied.
__str__()
str astroid.bases.Instance.__str__ (self)
Definition at line 365 of file bases.py.
    def __str__(self) -> str:
        return f"Instance of {self._proxied.root().name}.{self._proxied.name}"
Referenced by PIL.PdfParser.IndirectReference.__bytes__().
bool_value()
bool | UninferableBase astroid.bases.Instance.bool_value (self, InferenceContext | None context = None)
Infer the truth value for an Instance.
The truth value of an instance is determined by these conditions:
   * if it implements __bool__ on Python 3 or __nonzero__
     on Python 2, then its bool value will be determined by
     calling this special method and checking its result.
   * when this method is not defined, __len__() is called, if it
     is defined, and the object is considered true if its result is
     nonzero. If a class defines neither __len__() nor __bool__(),
     all its instances are considered true.
Reimplemented in astroid.nodes.node_classes.BaseContainer, astroid.nodes.node_classes.Const, and astroid.nodes.node_classes.Dict.
Definition at line 381 of file bases.py.
    ) -> bool | UninferableBase:
        """Infer the truth value for an Instance.
        The truth value of an instance is determined by these conditions:
           * if it implements __bool__ on Python 3 or __nonzero__
             on Python 2, then its bool value will be determined by
             calling this special method and checking its result.
           * when this method is not defined, __len__() is called, if it
             is defined, and the object is considered true if its result is
             nonzero. If a class defines neither __len__() nor __bool__(),
             all its instances are considered true.
        """
        context = context or InferenceContext()
        context.boundnode = self
        try:
            result = _infer_method_result_truth(self, "__bool__", context)
        except (InferenceError, AttributeInferenceError):
            # Fallback to __len__.
            try:
                result = _infer_method_result_truth(self, "__len__", context)
            except (AttributeInferenceError, InferenceError):
                return True
        return result
References astroid.bases._infer_method_result_truth().
callable()
bool astroid.bases.Instance.callable (self)
Definition at line 368 of file bases.py.
    def callable(self) -> bool:
        try:
            self._proxied.getattr("__call__", class_context=False)
            return True
        except AttributeInferenceError:
            return False
References astroid.bases.Proxy._proxied, and astroid.bases.BaseInstance.getattr().
display_type()
str astroid.bases.Instance.display_type (self)
Reimplemented from astroid.bases.BaseInstance.
Definition at line 378 of file bases.py.
    def display_type(self) -> str:
        return "Instance of"
getitem()
InferenceResult | None astroid.bases.Instance.getitem (self, nodes.Const index, InferenceContext | None context = None)
Reimplemented in astroid.nodes.node_classes.Const, astroid.nodes.node_classes.Dict, astroid.nodes.node_classes.List, and astroid.nodes.node_classes.Tuple.
Definition at line 409 of file bases.py.
    ) -> InferenceResult | None:
        new_context = bind_context_to_node(context, self)
        if not context:
            context = new_context
        method = next(self.igetattr("__getitem__", context=context), None)
        # Create a new CallContext for providing index as an argument.
        new_context.callcontext = CallContext(args=[index], callee=method)
        if not isinstance(method, BoundMethod):
            raise InferenceError(
                "Could not find __getitem__ for {node!r}.", node=self, context=context
            )
        if len(method.args.arguments) != 2:  # (self, index)
            raise AstroidTypeError(
                "__getitem__ for {node!r} does not have correct signature",
                node=self,
                context=context,
            )
        return next(method.infer_call_result(self, new_context), None)
References astroid.bases.BaseInstance.igetattr().
infer_binary_op()
Generator[InferenceResult] astroid.bases.Instance.infer_binary_op (self, nodes.AugAssign | nodes.BinOp opnode, str operator, InferenceResult other, InferenceContext context, SuccessfulInferenceResult method)
Definition at line 350 of file bases.py.
    ) -> Generator[InferenceResult]:
        return method.infer_call_result(self, context)
pytype()
str astroid.bases.Instance.pytype (self)
Reimplemented in astroid.nodes.node_classes.BaseContainer, astroid.nodes.node_classes.Const, astroid.nodes.node_classes.Dict, astroid.nodes.node_classes.List, astroid.nodes.node_classes.Set, astroid.nodes.node_classes.Tuple, and astroid.objects.FrozenSet.
Definition at line 375 of file bases.py.
    def pytype(self) -> str:
        return self._proxied.qname()
References astroid.bases.Proxy._proxied.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/astroid/bases.py