Read&Watch: django.contrib.sessions.base_session.AbstractBaseSession.Meta Class Reference
django.contrib.sessions.base_session.AbstractBaseSession.Meta Class Reference
Static Public Attributes
bool abstract = True
verbose_name = _("session")
verbose_name_plural = _("sessions")
Detailed Description
Definition at line 34 of file base_session.py.
Member Data Documentation
abstract
bool django.contrib.sessions.base_session.AbstractBaseSession.Meta.abstract = True static
Definition at line 35 of file base_session.py.
Referenced by django.db.models.options.Options._expire_cache().
verbose_name
django.contrib.sessions.base_session.AbstractBaseSession.Meta.verbose_name = _("session") static
Definition at line 36 of file base_session.py.
Referenced by django.db.models.fields.Field.formfield(), django.db.models.fields.related.RelatedField.set_attributes_from_rel(), and django.db.models.options.Options.verbose_name_raw().
verbose_name_plural
django.contrib.sessions.base_session.AbstractBaseSession.Meta.verbose_name_plural = _("sessions") static
Definition at line 37 of file base_session.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/sessions/base_session.py