Read&Watch: django.db.models.expressions.Exists Class Reference
django.db.models.expressions.Exists Class Reference
Public Member Functions
__init__ (self, queryset, **kwargs)
select_format (self, compiler, sql, params)
as_sql (self, compiler, *args, **kwargs)
Public Member Functions inherited from django.db.models.expressions.Subquery
__init__ (self, queryset, output_field=None, **extra)
get_source_expressions (self)
set_source_expressions (self, exprs)
copy (self)
external_aliases (self)
get_external_cols (self)
get_group_by_cols (self)
Public Member Functions inherited from django.db.models.expressions.BaseExpression
__init__ (self, output_field=None)
__getstate__ (self)
get_db_converters (self, connection)
contains_aggregate (self)
contains_over_clause (self)
contains_column_references (self)
contains_subquery (self)
resolve_expression (self, query=None, allow_joins=True, reuse=None, summarize=False, for_save=False)
conditional (self)
field (self)
output_field (self)
convert_value (self)
get_lookup (self, lookup)
get_transform (self, name)
relabeled_clone (self, change_map)
replace_expressions (self, replacements)
get_refs (self)
prefix_references (self, prefix)
get_source_fields (self)
asc (self, **kwargs)
desc (self, **kwargs)
reverse_ordering (self)
flatten (self)
get_expression_for_validation (self)
Public Member Functions inherited from django.db.models.expressions.Combinable
__neg__ (self)
OPERATORS #.
__add__ (self, other)
__sub__ (self, other)
__mul__ (self, other)
__truediv__ (self, other)
__mod__ (self, other)
__pow__ (self, other)
__and__ (self, other)
bitand (self, other)
bitleftshift (self, other)
bitrightshift (self, other)
__xor__ (self, other)
bitxor (self, other)
__or__ (self, other)
bitor (self, other)
__radd__ (self, other)
__rsub__ (self, other)
__rmul__ (self, other)
__rtruediv__ (self, other)
__rmod__ (self, other)
__rpow__ (self, other)
__rand__ (self, other)
__ror__ (self, other)
__rxor__ (self, other)
__invert__ (self)
Additional Inherited Members
Public Attributes inherited from django.db.models.expressions.Subquery
query = getattr(queryset, "query", queryset).clone()
extra = extra
Public Attributes inherited from django.db.models.expressions.BaseExpression
output_field = output_field
contains_aggregate
Static Public Attributes inherited from django.db.models.expressions.Subquery
str template = "(%(subquery)s)"
bool subquery = True
Static Public Attributes inherited from django.db.models.expressions.BaseExpression
empty_result_set_value = NotImplemented
bool is_summary = False
bool filterable = True
bool window_compatible = False
bool allowed_default = False
bool constraint_validation_compatible = True
Static Public Attributes inherited from django.db.models.expressions.Combinable
str ADD = "+"
str SUB = "-"
str MUL = "*"
str DIV = "/"
str POW = "^"
str MOD = "%%"
str BITAND = "&"
str BITOR = "|"
str BITLEFTSHIFT = "<<"
str BITRIGHTSHIFT = ">>"
str BITXOR = "#"
Protected Member Functions inherited from django.db.models.expressions.Subquery
_resolve_output_field (self)
Protected Member Functions inherited from django.db.models.expressions.BaseExpression
_parse_expressions (self, *expressions)
_output_field_or_none (self)
Protected Member Functions inherited from django.db.models.expressions.Combinable
_combine (self, other, connector, reversed)
Static Protected Member Functions inherited from django.db.models.expressions.BaseExpression
_convert_value_noop (value, expression, connection)
Static Protected Attributes inherited from django.db.models.expressions.BaseExpression
bool _output_field_resolved_to_none = False
Detailed Description
Definition at line 1739 of file expressions.py.
Constructor & Destructor Documentation
__init__()
django.db.models.expressions.Exists.__init__ (self, queryset, ** kwargs)
Definition at line 1744 of file expressions.py.
    def __init__(self, queryset, **kwargs):
        super().__init__(queryset, **kwargs)
        self.query = self.query.exists()
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Function Documentation
as_sql()
django.db.models.expressions.Exists.as_sql (self, compiler, * connection, ** template)
Responsible for returning a (sql, [params]) tuple to be included
in the current query.
Different backends can provide their own implementation, by
providing an `as_{vendor}` method and patching the Expression:
```
def override_as_sql(self, compiler, connection):
    # custom logic
    return super().as_sql(compiler, connection)
setattr(Expression, 'as_' + connection.vendor, override_as_sql)
```
Arguments:
 * compiler: the query compiler responsible for generating the query.
   Must have a compile method, returning a (sql, [params]) tuple.
   Calling compiler(value) will return a quoted `value`.
 * connection: the database connection used for the current query.
Return: (sql, params)
  Where `sql` is a string containing ordered sql parameters to be
  replaced with the elements of the list `params`.
Reimplemented from django.db.models.expressions.Subquery.
Definition at line 1756 of file expressions.py.
    def as_sql(self, compiler, *args, **kwargs):
        try:
            return super().as_sql(compiler, *args, **kwargs)
        except EmptyResultSet:
            features = compiler.connection.features
            if not features.supports_boolean_expr_in_select_clause:
                return "1=0", ()
            return compiler.compile(Value(False))
@deconstructible(path="django.db.models.OrderBy")
References as_sql().
Referenced by as_sql(), django.db.models.expressions.SQLiteNumericMixin.as_sqlite(), django.db.backends.mysql.compiler.SQLCompiler.as_subquery_condition(), django.db.models.sql.compiler.SQLCompiler.as_subquery_condition(), django.db.models.sql.compiler.SQLCompiler.execute_sql(), and django.db.models.sql.compiler.SQLInsertCompiler.execute_sql().
select_format()
django.db.models.expressions.Exists.select_format (self, compiler, sql, params)
Custom format for select clauses. For example, EXISTS expressions need
to be wrapped in CASE WHEN on Oracle.
Reimplemented from django.db.models.expressions.BaseExpression.
Definition at line 1748 of file expressions.py.
    def select_format(self, compiler, sql, params):
        # Wrap EXISTS() with a CASE WHEN expression if a database backend
        # (e.g. Oracle) doesn't support boolean expression in SELECT or GROUP
        # BY list.
        if not compiler.connection.features.supports_boolean_expr_in_select_clause:
            sql = "CASE WHEN {} THEN 1 ELSE 0 END".format(sql)
        return sql, params
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/db/models/expressions.py