Read&Watch: PIL.TiffImagePlugin.AppendingTiffWriter Class Reference
PIL.TiffImagePlugin.AppendingTiffWriter Class Reference
Public Member Functions
None __init__ (self, StrOrBytesPath|IO[bytes] fn, bool new=False)
None setup (self)
None finalize (self)
None newFrame (self)
AppendingTiffWriter __enter__ (self)
None __exit__ (self, *object args)
int tell (self)
int seek (self, int offset, int whence=io.SEEK_SET)
None goToEnd (self)
None setEndian (self, str endian)
None skipIFDs (self)
int write (self, Buffer data)
int readShort (self)
int readLong (self)
None rewriteLastShortToLong (self, int value)
None rewriteLastShort (self, int value)
None rewriteLastLong (self, int value)
None writeShort (self, int value)
None writeLong (self, int value)
None close (self)
None fixIFD (self)
None fixOffsets (self, int count, bool isShort=False, bool isLong=False)
Public Attributes
IO[bytes] f
name = fn
bool close_fp = True
IO[bytes] beginning = self.f.tell()
int|None whereToWriteNewIFDOffset = None
int offsetOfNewPage = 0
IO[bytes] IIMM = self.f.read(4)
bool isFirst = True
endian = endian
IO[bytes] longFmt = f"{self.endian}L"
IO[bytes] shortFmt = f"{self.endian}H"
IO[bytes] tagFormat = f"{self.endian}HHL"
Static Public Attributes
list fieldSizes
dict Tags
Protected Member Functions
str _fmt (self, int field_size)
int _read (self, int field_size)
None _rewriteLast (self, int value, int field_size)
None _fixOffsets (self, int count, int field_size)
Static Protected Member Functions
None _verify_bytes_written (int|None bytes_written, int expected)
Detailed Description
Definition at line 1967 of file TiffImagePlugin.py.
Constructor & Destructor Documentation
__init__()
None PIL.TiffImagePlugin.AppendingTiffWriter.__init__ (self, StrOrBytesPath | IO[bytes] fn, bool new = False)
Definition at line 1997 of file TiffImagePlugin.py.
    def __init__(self, fn: StrOrBytesPath | IO[bytes], new: bool = False) -> None:
        self.f: IO[bytes]
        if is_path(fn):
            self.name = fn
            self.close_fp = True
            try:
                self.f = open(fn, "w+b" if new else "r+b")
            except OSError:
                self.f = open(fn, "w+b")
        else:
            self.f = cast(IO[bytes], fn)
            self.close_fp = False
        self.beginning = self.f.tell()
        self.setup()
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
__enter__()
AppendingTiffWriter PIL.TiffImagePlugin.AppendingTiffWriter.__enter__ (self)
Definition at line 2066 of file TiffImagePlugin.py.
    def __enter__(self) -> AppendingTiffWriter:
        return self
__exit__()
None PIL.TiffImagePlugin.AppendingTiffWriter.__exit__ (self, *object args)
Definition at line 2069 of file TiffImagePlugin.py.
    def __exit__(self, *args: object) -> None:
        if self.close_fp:
            self.close()
_fixOffsets()
None PIL.TiffImagePlugin.AppendingTiffWriter._fixOffsets (self, int count, int field_size) protected
Definition at line 2203 of file TiffImagePlugin.py.
    def _fixOffsets(self, count: int, field_size: int) -> None:
        for i in range(count):
            offset = self._read(field_size)
            offset += self.offsetOfNewPage
            if field_size == 2 and offset >= 65536:
                # offset is now too large - we must convert shorts to longs
                if count != 1:
                    msg = "not implemented"
                    raise RuntimeError(msg)  # XXX TODO
                # simple case - the offset is just one and therefore it is
                # local (not referenced with another offset)
                self.rewriteLastShortToLong(offset)
                self.f.seek(-10, os.SEEK_CUR)
                self.writeShort(TiffTags.LONG)  # rewrite the type to LONG
                self.f.seek(8, os.SEEK_CUR)
            else:
                self._rewriteLast(offset, field_size)
_fmt()
str PIL.TiffImagePlugin.AppendingTiffWriter._fmt (self, int field_size) protected
Definition at line 2119 of file TiffImagePlugin.py.
    def _fmt(self, field_size: int) -> str:
        try:
            return {2: "H", 4: "L", 8: "Q"}[field_size]
        except KeyError:
            msg = "offset is not supported"
            raise RuntimeError(msg)
Referenced by django.utils.log.ServerFormatter.uses_server_time().
_read()
int PIL.TiffImagePlugin.AppendingTiffWriter._read (self, int field_size) protected
Definition at line 2126 of file TiffImagePlugin.py.
    def _read(self, field_size: int) -> int:
        (value,) = struct.unpack(
            self.endian + self._fmt(field_size), self.f.read(field_size)
        )
        return value
Referenced by pip._vendor.msgpack.fallback.Unpacker._read_header(), pip._vendor.packaging._elffile.ELFFile.interpreter(), and pip._vendor.msgpack.fallback.Unpacker.read_bytes().
_rewriteLast()
None PIL.TiffImagePlugin.AppendingTiffWriter._rewriteLast (self, int value, int field_size) protected
Definition at line 2149 of file TiffImagePlugin.py.
    def _rewriteLast(self, value: int, field_size: int) -> None:
        self.f.seek(-field_size, os.SEEK_CUR)
        bytes_written = self.f.write(
            struct.pack(self.endian + self._fmt(field_size), value)
        )
        self._verify_bytes_written(bytes_written, field_size)
_verify_bytes_written()
None PIL.TiffImagePlugin.AppendingTiffWriter._verify_bytes_written (int | None bytes_written, int expected) static protected
Definition at line 2139 of file TiffImagePlugin.py.
    def _verify_bytes_written(bytes_written: int | None, expected: int) -> None:
        if bytes_written is not None and bytes_written != expected:
            msg = f"wrote only {bytes_written} bytes but wanted {expected}"
            raise RuntimeError(msg)
close()
None PIL.TiffImagePlugin.AppendingTiffWriter.close (self)
Definition at line 2170 of file TiffImagePlugin.py.
    def close(self) -> None:
        self.finalize()
        if self.close_fp:
            self.f.close()
Referenced by urllib3.contrib.emscripten.fetch._ReadStream.__del__(), django.db.backends.utils.CursorWrapper.__exit__(), pip._vendor.distlib.compat.ZipExtFile.__exit__(), pip._vendor.distlib.compat.ZipFile.__exit__(), pip._vendor.requests.models.Response.__exit__(), pip._vendor.requests.sessions.Session.__exit__(), pip._vendor.rich.progress._Reader.__exit__(), pip._vendor.urllib3.connectionpool.ConnectionPool.__exit__(), pip._vendor.urllib3.util.ssltransport.SSLTransport.__exit__(), requests.models.Response.__exit__(), requests.sessions.Session.__exit__(), urllib3.connectionpool.ConnectionPool.__exit__(), urllib3.util.ssltransport.SSLTransport.__exit__(), pip._vendor.urllib3.contrib.securetransport.WrappedSocket._custom_validate(), pip._vendor.urllib3.contrib.pyopenssl.WrappedSocket._decref_socketios(), pip._vendor.urllib3.contrib.securetransport.WrappedSocket._decref_socketios(), urllib3.contrib.pyopenssl.WrappedSocket._decref_socketios(), pip._vendor.urllib3.contrib.pyopenssl.WrappedSocket._drop(), pip._vendor.urllib3.contrib.securetransport.WrappedSocket._drop(), pip._vendor.urllib3.contrib.securetransport.WrappedSocket._raise_on_error(), urllib3.connection.HTTPConnection._tunnel(), pip._vendor.urllib3.response.HTTPResponse._update_chunk_length(), urllib3.response.HTTPResponse._update_chunk_length(), urllib3.contrib.emscripten.response.EmscriptenHttpResponseWrapper.drain_conn(), urllib3.contrib.emscripten.fetch._ReadStream.readinto(), pip._vendor.urllib3.contrib.securetransport.WrappedSocket.recv_into(), pylint.checkers.imports.ImportsChecker.reduce_map_data(), and pylint.checkers.symilar.SimilaritiesChecker.reduce_map_data().
finalize()
None PIL.TiffImagePlugin.AppendingTiffWriter.finalize (self)
Definition at line 2037 of file TiffImagePlugin.py.
    def finalize(self) -> None:
        if self.isFirst:
            return
        # fix offsets
        self.f.seek(self.offsetOfNewPage)
        iimm = self.f.read(4)
        if not iimm:
            # Make it easy to finish a frame without committing to a new one.
            return
        if iimm != self.IIMM:
            msg = "IIMM of new page doesn't match IIMM of first page"
            raise RuntimeError(msg)
        ifd_offset = self.readLong()
        ifd_offset += self.offsetOfNewPage
        assert self.whereToWriteNewIFDOffset is not None
        self.f.seek(self.whereToWriteNewIFDOffset)
        self.writeLong(ifd_offset)
        self.f.seek(ifd_offset)
        self.fixIFD()
fixIFD()
None PIL.TiffImagePlugin.AppendingTiffWriter.fixIFD (self)
Definition at line 2175 of file TiffImagePlugin.py.
    def fixIFD(self) -> None:
        num_tags = self.readShort()
        for i in range(num_tags):
            tag, field_type, count = struct.unpack(self.tagFormat, self.f.read(8))
            field_size = self.fieldSizes[field_type]
            total_size = field_size * count
            is_local = total_size <= 4
            if not is_local:
                offset = self.readLong() + self.offsetOfNewPage
                self.rewriteLastLong(offset)
            if tag in self.Tags:
                cur_pos = self.f.tell()
                if is_local:
                    self._fixOffsets(count, field_size)
                    self.f.seek(cur_pos + 4)
                else:
                    self.f.seek(offset)
                    self._fixOffsets(count, field_size)
                    self.f.seek(cur_pos)
            elif is_local:
                # skip the locally stored value that is not an offset
                self.f.seek(4, os.SEEK_CUR)
fixOffsets()
None PIL.TiffImagePlugin.AppendingTiffWriter.fixOffsets (self, int count, bool isShort = False, bool isLong = False)
Definition at line 2222 of file TiffImagePlugin.py.
    ) -> None:
        if isShort:
            field_size = 2
        elif isLong:
            field_size = 4
        else:
            field_size = 0
        return self._fixOffsets(count, field_size)
goToEnd()
None PIL.TiffImagePlugin.AppendingTiffWriter.goToEnd (self)
Definition at line 2089 of file TiffImagePlugin.py.
    def goToEnd(self) -> None:
        self.f.seek(0, os.SEEK_END)
        pos = self.f.tell()
        # pad to 16 byte boundary
        pad_bytes = 16 - pos % 16
        if 0 < pad_bytes < 16:
            self.f.write(bytes(pad_bytes))
        self.offsetOfNewPage = self.f.tell()
newFrame()
None PIL.TiffImagePlugin.AppendingTiffWriter.newFrame (self)
Definition at line 2061 of file TiffImagePlugin.py.
    def newFrame(self) -> None:
        # Call this to finish a frame.
        self.finalize()
        self.setup()
readLong()
int PIL.TiffImagePlugin.AppendingTiffWriter.readLong (self)
Definition at line 2135 of file TiffImagePlugin.py.
    def readLong(self) -> int:
        return self._read(4)
readShort()
int PIL.TiffImagePlugin.AppendingTiffWriter.readShort (self)
Definition at line 2132 of file TiffImagePlugin.py.
    def readShort(self) -> int:
        return self._read(2)
rewriteLastLong()
None PIL.TiffImagePlugin.AppendingTiffWriter.rewriteLastLong (self, int value)
Definition at line 2159 of file TiffImagePlugin.py.
    def rewriteLastLong(self, value: int) -> None:
        return self._rewriteLast(value, 4)
rewriteLastShort()
None PIL.TiffImagePlugin.AppendingTiffWriter.rewriteLastShort (self, int value)
Definition at line 2156 of file TiffImagePlugin.py.
    def rewriteLastShort(self, value: int) -> None:
        return self._rewriteLast(value, 2)
rewriteLastShortToLong()
None PIL.TiffImagePlugin.AppendingTiffWriter.rewriteLastShortToLong (self, int value)
Definition at line 2144 of file TiffImagePlugin.py.
    def rewriteLastShortToLong(self, value: int) -> None:
        self.f.seek(-2, os.SEEK_CUR)
        bytes_written = self.f.write(struct.pack(self.longFmt, value))
        self._verify_bytes_written(bytes_written, 4)
seek()
int PIL.TiffImagePlugin.AppendingTiffWriter.seek (self, int offset, int whence = io.SEEK_SET)
:param offset: Distance to seek.
:param whence: Whether the distance is relative to the start,
               end or current position.
:returns: The resulting position, relative to the start.
Definition at line 2076 of file TiffImagePlugin.py.
    def seek(self, offset: int, whence: int = io.SEEK_SET) -> int:
        """
        :param offset: Distance to seek.
        :param whence: Whether the distance is relative to the start,
                       end or current position.
        :returns: The resulting position, relative to the start.
        """
        if whence == os.SEEK_SET:
            offset += self.offsetOfNewPage
        self.f.seek(offset, whence)
        return self.tell()
Referenced by pip._internal.network.lazy_wheel.LazyZipOverHTTP._download(), pip._internal.network.lazy_wheel.LazyZipOverHTTP._stay(), and django.utils.text.StreamingBuffer.read().
setEndian()
None PIL.TiffImagePlugin.AppendingTiffWriter.setEndian (self, str endian)
Definition at line 2099 of file TiffImagePlugin.py.
    def setEndian(self, endian: str) -> None:
        self.endian = endian
        self.longFmt = f"{self.endian}L"
        self.shortFmt = f"{self.endian}H"
        self.tagFormat = f"{self.endian}HHL"
setup()
None PIL.TiffImagePlugin.AppendingTiffWriter.setup (self)
Definition at line 2012 of file TiffImagePlugin.py.
    def setup(self) -> None:
        # Reset everything.
        self.f.seek(self.beginning, os.SEEK_SET)
        self.whereToWriteNewIFDOffset: int | None = None
        self.offsetOfNewPage = 0
        self.IIMM = iimm = self.f.read(4)
        if not iimm:
            # empty file - first page
            self.isFirst = True
            return
        self.isFirst = False
        if iimm == b"II\x2a\x00":
            self.setEndian("<")
        elif iimm == b"MM\x00\x2a":
            self.setEndian(">")
        else:
            msg = "Invalid TIFF file header"
            raise RuntimeError(msg)
        self.skipIFDs()
        self.goToEnd()
skipIFDs()
None PIL.TiffImagePlugin.AppendingTiffWriter.skipIFDs (self)
Definition at line 2105 of file TiffImagePlugin.py.
    def skipIFDs(self) -> None:
        while True:
            ifd_offset = self.readLong()
            if ifd_offset == 0:
                self.whereToWriteNewIFDOffset = self.f.tell() - 4
                break
            self.f.seek(ifd_offset)
            num_tags = self.readShort()
            self.f.seek(num_tags * 12, os.SEEK_CUR)
tell()
int PIL.TiffImagePlugin.AppendingTiffWriter.tell (self)
Definition at line 2073 of file TiffImagePlugin.py.
    def tell(self) -> int:
        return self.f.tell() - self.offsetOfNewPage
Referenced by pip._internal.network.lazy_wheel.LazyZipOverHTTP._stay(), and pip._internal.network.lazy_wheel.LazyZipOverHTTP.read().
write()
int PIL.TiffImagePlugin.AppendingTiffWriter.write (self, Buffer data)
Definition at line 2116 of file TiffImagePlugin.py.
    def write(self, data: Buffer, /) -> int:
        return self.f.write(data)
Referenced by pylint.reporters.ureports.text_writer.TextWriter.default_table(), pylint.reporters.ureports.text_writer.TextWriter.visit_text(), and pylint.reporters.ureports.base_writer.BaseWriter.writeln().
writeLong()
None PIL.TiffImagePlugin.AppendingTiffWriter.writeLong (self, int value)
Definition at line 2166 of file TiffImagePlugin.py.
    def writeLong(self, value: int) -> None:
        bytes_written = self.f.write(struct.pack(self.longFmt, value))
        self._verify_bytes_written(bytes_written, 4)
writeShort()
None PIL.TiffImagePlugin.AppendingTiffWriter.writeShort (self, int value)
Definition at line 2162 of file TiffImagePlugin.py.
    def writeShort(self, value: int) -> None:
        bytes_written = self.f.write(struct.pack(self.shortFmt, value))
        self._verify_bytes_written(bytes_written, 2)
Member Data Documentation
beginning
PIL.TiffImagePlugin.AppendingTiffWriter.beginning = self.f.tell()
Definition at line 2009 of file TiffImagePlugin.py.
close_fp
bool PIL.TiffImagePlugin.AppendingTiffWriter.close_fp = True
Definition at line 2001 of file TiffImagePlugin.py.
endian
PIL.TiffImagePlugin.AppendingTiffWriter.endian = endian
Definition at line 2100 of file TiffImagePlugin.py.
f
IO[bytes] PIL.TiffImagePlugin.AppendingTiffWriter.f
Definition at line 1998 of file TiffImagePlugin.py.
Referenced by django.utils.dateformat.TimeFormat.P().
fieldSizes
list PIL.TiffImagePlugin.AppendingTiffWriter.fieldSizes static
Initial value:
=  [
        0,  # None
        1,  # byte
        1,  # ascii
        2,  # short
        4,  # long
        8,  # rational
        1,  # sbyte
        1,  # undefined
        2,  # sshort
        4,  # slong
        8,  # srational
        4,  # float
        8,  # double
        4,  # ifd
        2,  # unicode
        4,  # complex
        8,  # long8
    ]
Definition at line 1968 of file TiffImagePlugin.py.
IIMM
IO[bytes] PIL.TiffImagePlugin.AppendingTiffWriter.IIMM = self.f.read(4)
Definition at line 2019 of file TiffImagePlugin.py.
isFirst
bool PIL.TiffImagePlugin.AppendingTiffWriter.isFirst = True
Definition at line 2022 of file TiffImagePlugin.py.
longFmt
IO[bytes] PIL.TiffImagePlugin.AppendingTiffWriter.longFmt = f"{self.endian}L"
Definition at line 2101 of file TiffImagePlugin.py.
name
PIL.TiffImagePlugin.AppendingTiffWriter.name = fn
Definition at line 2000 of file TiffImagePlugin.py.
Referenced by tomlkit.items.Table.__copy__(), django.contrib.gis.gdal.geomtype.OGRGeomType.__eq__(), pip._vendor.distlib.database.Distribution.__eq__(), pip._vendor.distlib.util.ExportEntry.__eq__(), pip._vendor.packaging.requirements.Requirement.__eq__(), pip._vendor.packaging.metadata._Validator.__get__(), pip._vendor.urllib3.packages.six._LazyDescr.__get__(), six._LazyDescr.__get__(), pylint.checkers.base_checker.BaseChecker.__gt__(), pip._vendor.distlib.database.Distribution.__hash__(), pip._vendor.packaging.requirements.Requirement.__hash__(), pylint.checkers.base_checker.BaseChecker.__init__(), pylint.checkers.symilar.LineSet.__lt__(), pip._internal.models.link.LinkHash.__post_init__(), pip._vendor.distlib.metadata.Metadata.__repr__(), pip._vendor.distlib.util.ExportEntry.__repr__(), pip._vendor.rich.color.Color.__rich_repr__(), pip._vendor.rich.layout.Layout.__rich_repr__(), django.contrib.gis.gdal.driver.Driver.__str__(), django.contrib.gis.gdal.geomtype.OGRGeomType.__str__(), django.contrib.gis.gdal.layer.Layer.__str__(), pip._vendor.distlib.database.EggInfoDistribution.__str__(), pip._vendor.distlib.database.InstalledDistribution.__str__(), pip._vendor.packaging.requirements.Requirement.__str__(), pip._vendor.rich.markup.Tag.__str__(), yaml.error.Mark.__str__(), yaml.reader.ReaderError.__str__(), pip._vendor.urllib3.packages.six._SixMetaPathImporter._add_module(), six._SixMetaPathImporter._add_module(), pip._vendor.distlib.version.Matcher._check_compatible(), pip._vendor.distlib.wheel.Wheel._get_extensions(), pip._vendor.urllib3.packages.six._SixMetaPathImporter._get_module(), six._SixMetaPathImporter._get_module(), pip._internal.cli.parser.ConfigOptionParser._get_ordered_configuration_items(), pip._vendor.distlib.database.Distribution._get_requirements(), tomlkit.items.AoT._getstate(), pip._vendor.distlib.database._Cache.add(), pip._internal.req.req_install.InstallRequirement.archive(), pip._internal.models.link.LinkHash.as_hashes(), pip._vendor.distlib.wheel.Wheel.build(), yaml.reader.Reader.check_printable(), pip._vendor.distlib.database._Cache.clear(), django.contrib.gis.gdal.geomtype.OGRGeomType.django(), pip._vendor.distlib.wheel.Wheel.filename(), pip._vendor.rich.layout.Layout.get(), pip._vendor.distlib.database.InstalledDistribution.get_distinfo_file(), yaml.reader.Reader.get_mark(), pip._internal.cli.req_command.RequirementCommand.get_requirements(), pip._vendor.distlib.wheel.Wheel.get_wheel_metadata(), pip._vendor.distlib.wheel.Wheel.install(), pip._internal.models.link.LinkHash.is_hash_allowed(), pip._internal.vcs.versioncontrol.VersionControl.is_repository_directory(), pip._internal.resolution.resolvelib.requirements.SpecifierRequirement.is_satisfied_by(), pip._vendor.distro.distro.LinuxDistribution.linux_distribution(), pip._vendor.distlib.wheel.Wheel.metadata(), pip._vendor.distlib.database.Distribution.name_and_version(), pip._internal.vcs.versioncontrol.VersionControl.obtain(), pip._internal.req.req_install.InstallRequirement.prepare_metadata(), pip._vendor.distlib.database.Distribution.provides(), pip._vendor.distlib.metadata.Metadata.provides(), astroid.nodes.scoped_nodes.mixin.LocalsDictNodeNG.qname(), pip._internal.vcs.versioncontrol.VcsSupport.register(), pip._internal.vcs.versioncontrol.VersionControl.run_command(), django.contrib.gis.gdal.geomtype.OGRGeomType.to_multi(), pip._internal.req.req_install.InstallRequirement.uninstall(), pip._vendor.distlib.wheel.Wheel.update(), yaml.reader.Reader.update(), and pip._vendor.distlib.wheel.Wheel.verify().
offsetOfNewPage
PIL.TiffImagePlugin.AppendingTiffWriter.offsetOfNewPage = 0
Definition at line 2017 of file TiffImagePlugin.py.
shortFmt
IO[bytes] PIL.TiffImagePlugin.AppendingTiffWriter.shortFmt = f"{self.endian}H"
Definition at line 2102 of file TiffImagePlugin.py.
tagFormat
IO[bytes] PIL.TiffImagePlugin.AppendingTiffWriter.tagFormat = f"{self.endian}HHL"
Definition at line 2103 of file TiffImagePlugin.py.
Tags
dict PIL.TiffImagePlugin.AppendingTiffWriter.Tags static
Initial value:
=  {
        273,  # StripOffsets
        288,  # FreeOffsets
        324,  # TileOffsets
        519,  # JPEGQTables
        520,  # JPEGDCTables
        521,  # JPEGACTables
    }
Definition at line 1988 of file TiffImagePlugin.py.
whereToWriteNewIFDOffset
PIL.TiffImagePlugin.AppendingTiffWriter.whereToWriteNewIFDOffset = None
Definition at line 2016 of file TiffImagePlugin.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/PIL/TiffImagePlugin.py