Read&Watch: pylint.checkers.base.comparison_checker.ComparisonChecker Class Reference
pylint.checkers.base.comparison_checker.ComparisonChecker Class Reference
Public Member Functions
None visit_compare (self, nodes.Compare node)
Public Member Functions inherited from pylint.checkers.base_checker.BaseChecker
None __init__ (self, PyLinter linter)
bool __gt__ (self, Any other)
bool __eq__ (self, object other)
int __hash__ (self)
str __repr__ (self)
str __str__ (self)
str get_full_documentation (self, dict[str, MessageDefinitionTuple] msgs, Iterable[tuple[str, OptionDict, Any]] options, Sequence[tuple[str, str, ReportsCallable]] reports, str|None doc=None, str|None module=None, bool show_options=True)
None add_message (self, str msgid, int|None line=None, nodes.NodeNG|None node=None, Any args=None, Confidence|None confidence=None, int|None col_offset=None, int|None end_lineno=None, int|None end_col_offset=None)
None check_consistency (self)
MessageDefinition create_message_definition_from_tuple (self, str msgid, MessageDefinitionTuple msg_tuple)
list[MessageDefinition] messages (self)
None open (self)
None close (self)
Any get_map_data (self)
None reduce_map_data (self, PyLinter linter, list[Any] data)
Public Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
None __init__ (self, _ArgumentsManager arguments_manager)
Protected Member Functions
None _check_singleton_comparison (self, nodes.NodeNG left_value, nodes.NodeNG right_value, nodes.Compare root_node, bool checking_for_absence=False)
None _check_nan_comparison (self, nodes.NodeNG left_value, nodes.NodeNG right_value, nodes.Compare root_node, bool checking_for_absence=False)
None _check_literal_comparison (self, nodes.NodeNG literal, nodes.Compare node)
None _check_logical_tautology (self, nodes.Compare node)
None _check_constants_comparison (self, nodes.Compare node)
None _check_callable_comparison (self, nodes.Compare node)
None _check_unidiomatic_typecheck (self, nodes.Compare node)
None _check_type_x_is_y (self, nodes.Compare node, nodes.NodeNG left, str operator, nodes.NodeNG right)
Protected Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
Any _option_value (self, str opt)
Iterator[ tuple[str, list[tuple[str, OptionDict, Any]]]|tuple[None, dict[str, list[tuple[str, OptionDict, Any]]]]] _options_by_section (self)
Iterator[tuple[str, OptionDict, Any]] _options_and_values (self, Options|None options=None)
Additional Inherited Members
Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
linter = linter
messages
Static Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
str name = ""
dict msgs = {}
tuple reports = ()
bool enabled = True
Static Public Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
tuple options = ()
dict option_groups_descs = {}
Protected Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
_arguments_manager = arguments_manager
Detailed Description
Checks for comparisons.
- singleton comparison: 'expr == True', 'expr == False' and 'expr == None'
- yoda condition: 'const "comp" right' where comp can be '==', '!=', '<',
  '<=', '>' or '>=', and right can be a variable, an attribute, a method or
  a function
Definition at line 25 of file comparison_checker.py.
Member Function Documentation
_check_callable_comparison()
None pylint.checkers.base.comparison_checker.ComparisonChecker._check_callable_comparison (self, nodes.Compare node) protected
Definition at line 264 of file comparison_checker.py.
    def _check_callable_comparison(self, node: nodes.Compare) -> None:
        operator = node.ops[0][0]
        if operator not in COMPARISON_OPERATORS:
            return
        bare_callables = (nodes.FunctionDef, astroid.BoundMethod)
        left_operand, right_operand = node.left, node.ops[0][1]
        # this message should be emitted only when there is comparison of bare callable
        # with non bare callable.
        number_of_bare_callables = 0
        for operand in left_operand, right_operand:
            inferred = utils.safe_infer(operand)
            # Ignore callables that raise, as well as typing constants
            # implemented as functions (that raise via their decorator)
            if (
                isinstance(inferred, bare_callables)
                and "typing._SpecialForm" not in inferred.decoratornames()
                and not any(isinstance(x, nodes.Raise) for x in inferred.body)
            ):
                number_of_bare_callables += 1
        if number_of_bare_callables == 1:
            self.add_message("comparison-with-callable", node=node)
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_compare().
_check_constants_comparison()
None pylint.checkers.base.comparison_checker.ComparisonChecker._check_constants_comparison (self, nodes.Compare node) protected
When two constants are being compared it is always a logical tautology.
Definition at line 246 of file comparison_checker.py.
    def _check_constants_comparison(self, node: nodes.Compare) -> None:
        """When two constants are being compared it is always a logical tautology."""
        left_operand = node.left
        if not isinstance(left_operand, nodes.Const):
            return
        right_operand = node.ops[0][1]
        if not isinstance(right_operand, nodes.Const):
            return
        operator = node.ops[0][0]
        self.add_message(
            "comparison-of-constants",
            node=node,
            args=(left_operand.value, operator, right_operand.value),
            confidence=HIGH,
        )
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_compare(), and pylint.extensions.magic_value.MagicValueChecker.visit_compare().
_check_literal_comparison()
None pylint.checkers.base.comparison_checker.ComparisonChecker._check_literal_comparison (self, nodes.NodeNG literal, nodes.Compare node) protected
Check if we compare to a literal, which is usually what we do not want to do.
Definition at line 184 of file comparison_checker.py.
    ) -> None:
        """Check if we compare to a literal, which is usually what we do not want to do."""
        is_other_literal = isinstance(literal, (nodes.List, nodes.Dict, nodes.Set))
        is_const = False
        if isinstance(literal, nodes.Const):
            if isinstance(literal.value, bool) or literal.value is None:
                # Not interested in these values.
                return
            is_const = isinstance(literal.value, (bytes, str, int, float))
        if is_const or is_other_literal:
            incorrect_node_str = node.as_string()
            if "is not" in incorrect_node_str:
                equal_or_not_equal = "!="
                is_or_is_not = "is not"
            else:
                equal_or_not_equal = "=="
                is_or_is_not = "is"
            fixed_node_str = incorrect_node_str.replace(
                is_or_is_not, equal_or_not_equal
            )
            self.add_message(
                "literal-comparison",
                args=(
                    incorrect_node_str,
                    equal_or_not_equal,
                    is_or_is_not,
                    fixed_node_str,
                ),
                node=node,
                confidence=HIGH,
            )
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_compare().
_check_logical_tautology()
None pylint.checkers.base.comparison_checker.ComparisonChecker._check_logical_tautology (self, nodes.Compare node) protected
Check if identifier is compared against itself.
:param node: Compare node
:Example:
val = 786
if val == val:  # [comparison-with-itself]
    pass
Definition at line 219 of file comparison_checker.py.
    def _check_logical_tautology(self, node: nodes.Compare) -> None:
        """Check if identifier is compared against itself.
        :param node: Compare node
        :Example:
        val = 786
        if val == val:  # [comparison-with-itself]
            pass
        """
        left_operand = node.left
        right_operand = node.ops[0][1]
        operator = node.ops[0][0]
        if isinstance(left_operand, nodes.Const) and isinstance(
            right_operand, nodes.Const
        ):
            left_operand = left_operand.value
            right_operand = right_operand.value
        elif isinstance(left_operand, nodes.Name) and isinstance(
            right_operand, nodes.Name
        ):
            left_operand = left_operand.name
            right_operand = right_operand.name
        if left_operand == right_operand:
            suggestion = f"{left_operand} {operator} {right_operand}"
            self.add_message("comparison-with-itself", node=node, args=(suggestion,))
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_compare().
_check_nan_comparison()
None pylint.checkers.base.comparison_checker.ComparisonChecker._check_nan_comparison (self, nodes.NodeNG left_value, nodes.NodeNG right_value, nodes.Compare root_node, bool checking_for_absence = False) protected
Definition at line 139 of file comparison_checker.py.
    ) -> None:
        def _is_float_nan(node: nodes.NodeNG) -> bool:
            try:
                if isinstance(node, nodes.Call) and len(node.args) == 1:
                    if (
                        node.args[0].value.lower() == "nan"
                        and node.inferred()[0].pytype() == "builtins.float"
                    ):
                        return True
                return False
            except AttributeError:
                return False
        def _is_numpy_nan(node: nodes.NodeNG) -> bool:
            if isinstance(node, nodes.Attribute) and node.attrname == "NaN":
                if isinstance(node.expr, nodes.Name):
                    return node.expr.name in {"numpy", "nmp", "np"}
            return False
        def _is_nan(node: nodes.NodeNG) -> bool:
            return _is_float_nan(node) or _is_numpy_nan(node)
        nan_left = _is_nan(left_value)
        if not nan_left and not _is_nan(right_value):
            return
        absence_text = ""
        if checking_for_absence:
            absence_text = "not "
        if nan_left:
            suggestion = f"'{absence_text}math.isnan({right_value.as_string()})'"
        else:
            suggestion = f"'{absence_text}math.isnan({left_value.as_string()})'"
        self.add_message(
            "nan-comparison",
            node=root_node,
            args=(f"'{root_node.as_string()}'", suggestion),
        )
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_compare().
_check_singleton_comparison()
None pylint.checkers.base.comparison_checker.ComparisonChecker._check_singleton_comparison (self, nodes.NodeNG left_value, nodes.NodeNG right_value, nodes.Compare root_node, bool checking_for_absence = False) protected
Check if == or != is being used to compare a singleton value.
Definition at line 84 of file comparison_checker.py.
    ) -> None:
        """Check if == or != is being used to compare a singleton value."""
        if utils.is_singleton_const(left_value):
            singleton, other_value = left_value.value, right_value
        elif utils.is_singleton_const(right_value):
            singleton, other_value = right_value.value, left_value
        else:
            return
        singleton_comparison_example = {False: "'{} is {}'", True: "'{} is not {}'"}
        # True/False singletons have a special-cased message in case the user is
        # mistakenly using == or != to check for truthiness
        if singleton in {True, False}:
            suggestion_template = (
                "{} if checking for the singleton value {}, or {} if testing for {}"
            )
            truthiness_example = {False: "not {}", True: "{}"}
            truthiness_phrase = {True: "truthiness", False: "falsiness"}
            # Looks for comparisons like x == True or x != False
            checking_truthiness = singleton is not checking_for_absence
            suggestion = suggestion_template.format(
                singleton_comparison_example[checking_for_absence].format(
                    left_value.as_string(), right_value.as_string()
                ),
                singleton,
                (
                    "'bool({})'"
                    if not utils.is_test_condition(root_node) and checking_truthiness
                    else "'{}'"
                ).format(
                    truthiness_example[checking_truthiness].format(
                        other_value.as_string()
                    )
                ),
                truthiness_phrase[checking_truthiness],
            )
        else:
            suggestion = singleton_comparison_example[checking_for_absence].format(
                left_value.as_string(), right_value.as_string()
            )
        self.add_message(
            "singleton-comparison",
            node=root_node,
            args=(f"'{root_node.as_string()}'", suggestion),
        )
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_compare().
_check_type_x_is_y()
None pylint.checkers.base.comparison_checker.ComparisonChecker._check_type_x_is_y (self, nodes.Compare node, nodes.NodeNG left, str operator, nodes.NodeNG right) protected
Check for expressions like type(x) == Y.
Definition at line 328 of file comparison_checker.py.
    ) -> None:
        """Check for expressions like type(x) == Y."""
        left_func = utils.safe_infer(left.func)
        if not (
            isinstance(left_func, nodes.ClassDef) and left_func.qname() == TYPE_QNAME
        ):
            return
        if operator in {"is", "is not"} and _is_one_arg_pos_call(right):
            right_func = utils.safe_infer(right.func)
            if (
                isinstance(right_func, nodes.ClassDef)
                and right_func.qname() == TYPE_QNAME
            ):
                # type(x) == type(a)
                right_arg = utils.safe_infer(right.args[0])
                if not isinstance(right_arg, LITERAL_NODE_TYPES):
                    # not e.g. type(x) == type([])
                    return
        self.add_message("unidiomatic-typecheck", node=node)
References pylint.checkers.base.comparison_checker._is_one_arg_pos_call(), and pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by _check_unidiomatic_typecheck().
_check_unidiomatic_typecheck()
None pylint.checkers.base.comparison_checker.ComparisonChecker._check_unidiomatic_typecheck (self, nodes.Compare node) protected
Definition at line 321 of file comparison_checker.py.
    def _check_unidiomatic_typecheck(self, node: nodes.Compare) -> None:
        operator, right = node.ops[0]
        if operator in TYPECHECK_COMPARISON_OPERATORS:
            left = node.left
            if _is_one_arg_pos_call(left):
                self._check_type_x_is_y(node, left, operator, right)
References _check_type_x_is_y(), and pylint.checkers.base.comparison_checker._is_one_arg_pos_call().
Referenced by visit_compare().
visit_compare()
None pylint.checkers.base.comparison_checker.ComparisonChecker.visit_compare (self, nodes.Compare node)
Definition at line 296 of file comparison_checker.py.
    def visit_compare(self, node: nodes.Compare) -> None:
        self._check_callable_comparison(node)
        self._check_logical_tautology(node)
        self._check_unidiomatic_typecheck(node)
        self._check_constants_comparison(node)
        # NOTE: this checker only works with binary comparisons like 'x == 42'
        # but not 'x == y == 42'
        if len(node.ops) != 1:
            return
        left = node.left
        operator, right = node.ops[0]
        if operator in {"==", "!="}:
            self._check_singleton_comparison(
                left, right, node, checking_for_absence=operator == "!="
            )
        if operator in {"==", "!=", "is", "is not"}:
            self._check_nan_comparison(
                left, right, node, checking_for_absence=operator in {"!=", "is not"}
            )
        if operator in {"is", "is not"}:
            self._check_literal_comparison(right, node)
References _check_callable_comparison(), _check_constants_comparison(), _check_literal_comparison(), _check_logical_tautology(), _check_nan_comparison(), _check_singleton_comparison(), and _check_unidiomatic_typecheck().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pylint/checkers/base/comparison_checker.py