Read&Watch: pylint.extensions._check_docs_utils.SphinxDocstring Class Reference
pylint.extensions._check_docs_utils.SphinxDocstring Class Reference
Public Member Functions
int matching_sections (self)
set[str] exceptions (self)
bool has_params (self)
bool has_returns (self)
bool has_rtype (self)
bool has_property_returns (self)
bool has_property_type (self)
tuple[set[str], set[str]] match_param_docs (self)
Public Member Functions inherited from pylint.extensions._check_docs_utils.Docstring
None __init__ (self, nodes.Const|None doc)
str __repr__ (self)
bool has_yields (self)
bool has_yields_type (self)
bool params_documented_elsewhere (self)
Static Public Attributes
str re_type
str re_simple_container_type
str re_multiple_simple_type
str re_xref
str re_param_raw
re_param_in_docstring = re.compile(re_param_raw, re.X | re.S)
str re_type_raw
re_type_in_docstring = re.compile(re_type_raw, re.X | re.S)
str re_property_type_raw
re_property_type_in_docstring = re.compile(re_property_type_raw, re.X | re.S)
str re_raise_raw
re_raise_in_docstring = re.compile(re_raise_raw, re.X | re.S)
re_rtype_in_docstring = re.compile(r":rtype:")
re_returns_in_docstring = re.compile(r":returns?:")
Static Public Attributes inherited from pylint.extensions._check_docs_utils.Docstring
re_for_parameters_see
bool supports_yields = False
Additional Inherited Members
Public Attributes inherited from pylint.extensions._check_docs_utils.Docstring
doc = docstring.expandtabs()
Detailed Description
Definition at line 339 of file _check_docs_utils.py.
Member Function Documentation
exceptions()
set[str] pylint.extensions._check_docs_utils.SphinxDocstring.exceptions (self)
Reimplemented from pylint.extensions._check_docs_utils.Docstring.
Definition at line 428 of file _check_docs_utils.py.
    def exceptions(self) -> set[str]:
        types: set[str] = set()
        for match in re.finditer(self.re_raise_in_docstring, self.doc):
            raise_type = match.group(1)
            types.update(_split_multiple_exc_types(raise_type))
        return types
References pylint.extensions._check_docs_utils._split_multiple_exc_types(), pylint.extensions._check_docs_utils.Docstring.doc, and re_raise_in_docstring.
has_params()
bool pylint.extensions._check_docs_utils.SphinxDocstring.has_params (self)
Reimplemented from pylint.extensions._check_docs_utils.Docstring.
Definition at line 437 of file _check_docs_utils.py.
    def has_params(self) -> bool:
        if not self.doc:
            return False
        return self.re_param_in_docstring.search(self.doc) is not None
References pylint.extensions._check_docs_utils.Docstring.doc, and re_param_in_docstring.
has_property_returns()
bool pylint.extensions._check_docs_utils.SphinxDocstring.has_property_returns (self)
Reimplemented from pylint.extensions._check_docs_utils.Docstring.
Reimplemented in pylint.extensions._check_docs_utils.EpytextDocstring.
Definition at line 455 of file _check_docs_utils.py.
    def has_property_returns(self) -> bool:
        if not self.doc:
            return False
        # The summary line is the return doc,
        # so the first line must not be a known directive.
        return not self.doc.lstrip().startswith(":")
References pylint.extensions._check_docs_utils.Docstring.doc.
has_property_type()
bool pylint.extensions._check_docs_utils.SphinxDocstring.has_property_type (self)
Reimplemented from pylint.extensions._check_docs_utils.Docstring.
Definition at line 463 of file _check_docs_utils.py.
    def has_property_type(self) -> bool:
        if not self.doc:
            return False
        return bool(self.re_property_type_in_docstring.search(self.doc))
References pylint.extensions._check_docs_utils.Docstring.doc, and re_property_type_in_docstring.
has_returns()
bool pylint.extensions._check_docs_utils.SphinxDocstring.has_returns (self)
Reimplemented from pylint.extensions._check_docs_utils.Docstring.
Definition at line 443 of file _check_docs_utils.py.
    def has_returns(self) -> bool:
        if not self.doc:
            return False
        return bool(self.re_returns_in_docstring.search(self.doc))
References pylint.extensions._check_docs_utils.Docstring.doc, and re_returns_in_docstring.
has_rtype()
bool pylint.extensions._check_docs_utils.SphinxDocstring.has_rtype (self)
Reimplemented from pylint.extensions._check_docs_utils.Docstring.
Definition at line 449 of file _check_docs_utils.py.
    def has_rtype(self) -> bool:
        if not self.doc:
            return False
        return bool(self.re_rtype_in_docstring.search(self.doc))
References pylint.extensions._check_docs_utils.Docstring.doc, and re_rtype_in_docstring.
match_param_docs()
tuple[set[str], set[str]] pylint.extensions._check_docs_utils.SphinxDocstring.match_param_docs (self)
Reimplemented from pylint.extensions._check_docs_utils.Docstring.
Definition at line 469 of file _check_docs_utils.py.
    def match_param_docs(self) -> tuple[set[str], set[str]]:
        params_with_doc = set()
        params_with_type = set()
        for match in re.finditer(self.re_param_in_docstring, self.doc):
            name = match.group(2)
            # Remove escape characters necessary for asterisks
            name = name.replace("\\", "")
            params_with_doc.add(name)
            param_type = match.group(1)
            if param_type is not None:
                params_with_type.add(name)
        params_with_type.update(re.findall(self.re_type_in_docstring, self.doc))
        return params_with_doc, params_with_type
References pylint.extensions._check_docs_utils.Docstring.doc, re_param_in_docstring, and re_type_in_docstring.
matching_sections()
int pylint.extensions._check_docs_utils.SphinxDocstring.matching_sections (self)
Returns the number of matching docstring sections.
Reimplemented from pylint.extensions._check_docs_utils.Docstring.
Definition at line 415 of file _check_docs_utils.py.
    def matching_sections(self) -> int:
        """Returns the number of matching docstring sections."""
        return sum(
            bool(i)
            for i in (
                self.re_param_in_docstring.search(self.doc),
                self.re_raise_in_docstring.search(self.doc),
                self.re_rtype_in_docstring.search(self.doc),
                self.re_returns_in_docstring.search(self.doc),
                self.re_property_type_in_docstring.search(self.doc),
            )
        )
Member Data Documentation
re_multiple_simple_type
str pylint.extensions._check_docs_utils.SphinxDocstring.re_multiple_simple_type static
Initial value:
=  rf"""
        (?:{re_simple_container_type}|{re_type})
        (?:(?:\s+(?:of|or)\s+|\s*,\s*|\s+\|\s+)(?:{re_simple_container_type}|{re_type}))*
    """
Definition at line 350 of file _check_docs_utils.py.
re_param_in_docstring
pylint.extensions._check_docs_utils.SphinxDocstring.re_param_in_docstring = re.compile(re_param_raw, re.X | re.S) static
Definition at line 378 of file _check_docs_utils.py.
Referenced by has_params(), and match_param_docs().
re_param_raw
str pylint.extensions._check_docs_utils.SphinxDocstring.re_param_raw static
Initial value:
=  rf"""
        :                       # initial colon
        (?:                     # Sphinx keywords
        param|parameter|
        arg|argument|
        key|keyword
        )
        \s+                     # whitespace
        (?:                     # optional type declaration
        ({re_type}|{re_simple_container_type})
        \s+
        )?
        ((\\\*{{0,2}}\w+)|(\w+))  # Parameter name with potential asterisks
        \s*                       # whitespace
        :                         # final colon
        """
Definition at line 360 of file _check_docs_utils.py.
re_property_type_in_docstring
pylint.extensions._check_docs_utils.SphinxDocstring.re_property_type_in_docstring = re.compile(re_property_type_raw, re.X | re.S) static
Definition at line 394 of file _check_docs_utils.py.
Referenced by has_property_type().
re_property_type_raw
str pylint.extensions._check_docs_utils.SphinxDocstring.re_property_type_raw static
Initial value:
=  rf"""
        :type:                      # Sphinx keyword
        \s+                         # whitespace
        {re_multiple_simple_type}   # type declaration
        """
Definition at line 389 of file _check_docs_utils.py.
re_raise_in_docstring
pylint.extensions._check_docs_utils.SphinxDocstring.re_raise_in_docstring = re.compile(re_raise_raw, re.X | re.S) static
Definition at line 407 of file _check_docs_utils.py.
Referenced by exceptions().
re_raise_raw
str pylint.extensions._check_docs_utils.SphinxDocstring.re_raise_raw static
Initial value:
=  rf"""
        :                               # initial colon
        (?:                             # Sphinx keyword
        raises?|
        except|exception
        )
        \s+                             # whitespace
        ({re_multiple_simple_type})     # exception type
        \s*                             # whitespace
        :                               # final colon
        """
Definition at line 396 of file _check_docs_utils.py.
re_returns_in_docstring
pylint.extensions._check_docs_utils.SphinxDocstring.re_returns_in_docstring = re.compile(r":returns?:") static
Definition at line 411 of file _check_docs_utils.py.
Referenced by has_returns().
re_rtype_in_docstring
pylint.extensions._check_docs_utils.SphinxDocstring.re_rtype_in_docstring = re.compile(r":rtype:") static
Definition at line 409 of file _check_docs_utils.py.
Referenced by has_rtype().
re_simple_container_type
str pylint.extensions._check_docs_utils.SphinxDocstring.re_simple_container_type static
Initial value:
=  rf"""
        {re_type}                     # a container type
        [\‍(\[] [^\n\s]+ [\‍)\]]        # with the contents of the container
    """
Definition at line 345 of file _check_docs_utils.py.
re_type
str pylint.extensions._check_docs_utils.SphinxDocstring.re_type static
Initial value:
=  r"""
        [~!.]?               # Optional link style prefix
        \w(?:\w|\.[^\.])*    # Valid python name
        """
Definition at line 340 of file _check_docs_utils.py.
re_type_in_docstring
pylint.extensions._check_docs_utils.SphinxDocstring.re_type_in_docstring = re.compile(re_type_raw, re.X | re.S) static
Definition at line 387 of file _check_docs_utils.py.
Referenced by match_param_docs().
re_type_raw
str pylint.extensions._check_docs_utils.SphinxDocstring.re_type_raw static
Initial value:
=  rf"""
        :type                           # Sphinx keyword
        \s+                             # whitespace
        ({re_multiple_simple_type})     # Parameter name
        \s*                             # whitespace
        :                               # final colon
        """
Definition at line 380 of file _check_docs_utils.py.
re_xref
str pylint.extensions._check_docs_utils.SphinxDocstring.re_xref static
Initial value:
=  rf"""
        (?::\w+:)?                    # optional tag
        `{re_type}`                   # what to reference
        """
Definition at line 355 of file _check_docs_utils.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pylint/extensions/_check_docs_utils.py