Read&Watch: pip._vendor.msgpack.fallback.StringIO Class Reference
pip._vendor.msgpack.fallback.StringIO Class Reference
Public Member Functions
__init__ (self, s=b"")
write (self, s)
getvalue (self)
Public Attributes
builder = StringBuilder(len(s))
Detailed Description
Definition at line 18 of file fallback.py.
Constructor & Destructor Documentation
__init__()
pip._vendor.msgpack.fallback.StringIO.__init__ (self, s = b"")
Definition at line 19 of file fallback.py.
        def __init__(self, s=b""):
            if s:
                self.builder = StringBuilder(len(s))
                self.builder.append(s)
            else:
                self.builder = StringBuilder()
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
getvalue()
pip._vendor.msgpack.fallback.StringIO.getvalue (self)
Definition at line 33 of file fallback.py.
        def getvalue(self):
            return self.builder.build()
References builder.
Referenced by django.utils.text.StreamingBuffer.read().
write()
pip._vendor.msgpack.fallback.StringIO.write (self, s)
Definition at line 26 of file fallback.py.
        def write(self, s):
            if isinstance(s, memoryview):
                s = s.tobytes()
            elif isinstance(s, bytearray):
                s = bytes(s)
            self.builder.append(s)
References builder.
Referenced by pylint.reporters.ureports.text_writer.TextWriter.default_table(), pylint.reporters.ureports.text_writer.TextWriter.visit_text(), and pylint.reporters.ureports.base_writer.BaseWriter.writeln().
Member Data Documentation
builder
pip._vendor.msgpack.fallback.StringIO.builder = StringBuilder(len(s))
Definition at line 21 of file fallback.py.
Referenced by getvalue(), and write().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/msgpack/fallback.py