Read&Watch: pylint.checkers.dataclass_checker.DataclassChecker Class Reference
pylint.checkers.dataclass_checker.DataclassChecker Class Reference
Public Member Functions
None visit_call (self, nodes.Call node)
Public Member Functions inherited from pylint.checkers.base_checker.BaseChecker
None __init__ (self, PyLinter linter)
bool __gt__ (self, Any other)
bool __eq__ (self, object other)
int __hash__ (self)
str __repr__ (self)
str __str__ (self)
str get_full_documentation (self, dict[str, MessageDefinitionTuple] msgs, Iterable[tuple[str, OptionDict, Any]] options, Sequence[tuple[str, str, ReportsCallable]] reports, str|None doc=None, str|None module=None, bool show_options=True)
None add_message (self, str msgid, int|None line=None, nodes.NodeNG|None node=None, Any args=None, Confidence|None confidence=None, int|None col_offset=None, int|None end_lineno=None, int|None end_col_offset=None)
None check_consistency (self)
MessageDefinition create_message_definition_from_tuple (self, str msgid, MessageDefinitionTuple msg_tuple)
list[MessageDefinition] messages (self)
None open (self)
None close (self)
Any get_map_data (self)
None reduce_map_data (self, PyLinter linter, list[Any] data)
Public Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
None __init__ (self, _ArgumentsManager arguments_manager)
Protected Member Functions
None _check_invalid_field_call (self, nodes.Call node)
None _check_invalid_field_call_within_call (self, nodes.Call node, nodes.Call scope_node)
Protected Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
Any _option_value (self, str opt)
Iterator[ tuple[str, list[tuple[str, OptionDict, Any]]]|tuple[None, dict[str, list[tuple[str, OptionDict, Any]]]]] _options_by_section (self)
Iterator[tuple[str, OptionDict, Any]] _options_and_values (self, Options|None options=None)
Additional Inherited Members
Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
linter = linter
messages
Static Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
str name = ""
dict msgs = {}
tuple reports = ()
bool enabled = True
Static Public Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
tuple options = ()
dict option_groups_descs = {}
Protected Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
_arguments_manager = arguments_manager
Detailed Description
Checker that detects invalid or problematic usage in dataclasses.
Checks for
* invalid-field-call
Definition at line 37 of file dataclass_checker.py.
Member Function Documentation
_check_invalid_field_call()
None pylint.checkers.dataclass_checker.DataclassChecker._check_invalid_field_call (self, nodes.Call node) protected
Checks for correct usage of the dataclasses.field() specifier in
dataclasses or within the make_dataclass() function.
Emits message
when field() is detected to be used outside a class decorated with
@dataclass decorator and outside make_dataclass() function, or when it
is used improperly within a dataclass.
Definition at line 58 of file dataclass_checker.py.
    def _check_invalid_field_call(self, node: nodes.Call) -> None:
        """Checks for correct usage of the dataclasses.field() specifier in
        dataclasses or within the make_dataclass() function.
        Emits message
        when field() is detected to be used outside a class decorated with
        @dataclass decorator and outside make_dataclass() function, or when it
        is used improperly within a dataclass.
        """
        if not isinstance(node.func, (nodes.Name, nodes.Attribute)):
            return
        if not _check_name_or_attrname_eq_to(node.func, "field"):
            return
        inferred_func = utils.safe_infer(node.func)
        if not (
            isinstance(inferred_func, nodes.FunctionDef)
            and _is_dataclasses_module(inferred_func.root())
        ):
            return
        scope_node = node.parent
        while scope_node and not isinstance(scope_node, (nodes.ClassDef, nodes.Call)):
            scope_node = scope_node.parent
        if isinstance(scope_node, nodes.Call):
            self._check_invalid_field_call_within_call(node, scope_node)
            return
        if not scope_node or not scope_node.is_dataclass:
            self.add_message(
                "invalid-field-call",
                node=node,
                args=(
                    "it should be used within a dataclass or the make_dataclass() function.",
                ),
                confidence=INFERENCE,
            )
            return
        if not (isinstance(node.parent, nodes.AnnAssign) and node == node.parent.value):
            self.add_message(
                "invalid-field-call",
                node=node,
                args=("it should be the value of an assignment within a dataclass.",),
                confidence=INFERENCE,
            )
References _check_invalid_field_call_within_call(), pylint.checkers.dataclass_checker._check_name_or_attrname_eq_to(), pylint.checkers.dataclass_checker._is_dataclasses_module(), and pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_call().
_check_invalid_field_call_within_call()
None pylint.checkers.dataclass_checker.DataclassChecker._check_invalid_field_call_within_call (self, nodes.Call node, nodes.Call scope_node) protected
Checks for special case where calling field is valid as an argument of the
make_dataclass() function.
Definition at line 104 of file dataclass_checker.py.
    ) -> None:
        """Checks for special case where calling field is valid as an argument of the
        make_dataclass() function.
        """
        inferred_func = utils.safe_infer(scope_node.func)
        if (
            isinstance(scope_node.func, (nodes.Name, nodes.AssignName))
            and scope_node.func.name == "make_dataclass"
            and isinstance(inferred_func, nodes.FunctionDef)
            and _is_dataclasses_module(inferred_func.root())
        ):
            return
        self.add_message(
            "invalid-field-call",
            node=node,
            args=(
                "it should be used within a dataclass or the make_dataclass() function.",
            ),
            confidence=INFERENCE,
        )
References pylint.checkers.dataclass_checker._is_dataclasses_module(), and pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by _check_invalid_field_call().
visit_call()
None pylint.checkers.dataclass_checker.DataclassChecker.visit_call (self, nodes.Call node)
Definition at line 55 of file dataclass_checker.py.
    def visit_call(self, node: nodes.Call) -> None:
        self._check_invalid_field_call(node)
References _check_invalid_field_call().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pylint/checkers/dataclass_checker.py