Read&Watch: pip._internal.resolution.resolvelib.candidates.EditableCandidate Class Reference
pip._internal.resolution.resolvelib.candidates.EditableCandidate Class Reference
Public Member Functions
None __init__ (self, Link link, InstallRequirement template, "Factory" factory, Optional[NormalizedName] name=None, Optional[Version] version=None)
Public Member Functions inherited from pip._internal.resolution.resolvelib.candidates._InstallRequirementBackedCandidate
None __init__ (self, Link link, Link source_link, InstallRequirement ireq, "Factory" factory, Optional[NormalizedName] name=None, Optional[Version] version=None)
str __str__ (self)
str __repr__ (self)
int __hash__ (self)
bool __eq__ (self, Any other)
Optional[Link] source_link (self)
NormalizedName project_name (self)
str name (self)
Version version (self)
str format_for_error (self)
Iterable[Optional[Requirement]] iter_dependencies (self, bool with_requires)
Optional[InstallRequirement] get_install_requirement (self)
Public Member Functions inherited from pip._internal.resolution.resolvelib.base.Candidate
bool is_installed (self)
bool is_editable (self)
Protected Member Functions
BaseDistribution _prepare_distribution (self)
Protected Member Functions inherited from pip._internal.resolution.resolvelib.candidates._InstallRequirementBackedCandidate
None _check_metadata_consistency (self, BaseDistribution dist)
BaseDistribution _prepare (self)
Additional Inherited Members
Public Attributes inherited from pip._internal.resolution.resolvelib.candidates._InstallRequirementBackedCandidate
BaseDistribution dist = self._prepare()
Protected Attributes inherited from pip._internal.resolution.resolvelib.candidates._InstallRequirementBackedCandidate
_link = link
Optional[Link] _source_link = source_link
_factory = factory
_ireq = ireq
str _name = name
Version _version = version
Optional[int] _hash = None
Detailed Description
Definition at line 318 of file candidates.py.
Constructor & Destructor Documentation
__init__()
None pip._internal.resolution.resolvelib.candidates.EditableCandidate.__init__ (self, Link link, InstallRequirement template, "Factory" factory, Optional[NormalizedName] name = None, Optional[Version] version = None)
Definition at line 321 of file candidates.py.
    ) -> None:
        super().__init__(
            link=link,
            source_link=link,
            ireq=make_install_req_from_editable(link, template),
            factory=factory,
            name=name,
            version=version,
        )
References __init__(), and pip._internal.resolution.resolvelib.candidates.make_install_req_from_editable().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Function Documentation
_prepare_distribution()
BaseDistribution pip._internal.resolution.resolvelib.candidates.EditableCandidate._prepare_distribution (self) protected
Reimplemented from pip._internal.resolution.resolvelib.candidates._InstallRequirementBackedCandidate.
Definition at line 338 of file candidates.py.
    def _prepare_distribution(self) -> BaseDistribution:
        return self._factory.preparer.prepare_editable_requirement(self._ireq)
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_internal/resolution/resolvelib/candidates.py