Read&Watch: PIL.TiffTags.TagInfo Class Reference
PIL.TiffTags.TagInfo Class Reference
Public Member Functions
TagInfo __new__ (cls, int|None value=None, str name="unknown", int|None type=None, int|None length=None, dict[str, int]|None enum=None)
int|str cvt_enum (self, str value)
Additional Inherited Members
Static Public Attributes inherited from PIL.TiffTags._TagInfo
int value | None
int type | None
int length | None
dict enum [str, int]
Detailed Description
Definition at line 32 of file TiffTags.py.
Member Function Documentation
__new__()
TagInfo PIL.TiffTags.TagInfo.__new__ (cls, int | None value = None, str name = "unknown", int | None type = None, int | None length = None, dict[str, int] | None enum = None)
Definition at line 35 of file TiffTags.py.
    ) -> TagInfo:
        return super().__new__(cls, value, name, type, length, enum or {})
References __new__().
Referenced by __new__(), apscheduler.triggers.combining.BaseCombiningTrigger.__setstate__(), pip._vendor.rich.style.Style._add(), pip._vendor.rich.style.Style.clear_meta_and_links(), yaml.constructor.SafeConstructor.construct_yaml_object(), pip._vendor.rich.style.Style.copy(), pip._vendor.rich.style.Style.from_color(), pip._vendor.rich.json.JSON.from_data(), pip._vendor.rich.style.Style.from_meta(), yaml.constructor.FullConstructor.make_python_instance(), pip._vendor.rich.style.Style.update_link(), and pip._vendor.rich.style.Style.without_color().
cvt_enum()
int | str PIL.TiffTags.TagInfo.cvt_enum (self, str value)
Definition at line 45 of file TiffTags.py.
    def cvt_enum(self, value: str) -> int | str:
        # Using get will call hash(value), which can be expensive
        # for some types (e.g. Fraction). Since self.enum is rarely
        # used, it's usually better to test it first.
        return self.enum.get(value, value) if self.enum else value
References PIL.TiffTags._TagInfo.enum.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/PIL/TiffTags.py