Read&Watch: django.contrib.contenttypes.fields.GenericRel Class Reference
django.contrib.contenttypes.fields.GenericRel Class Reference
Public Member Functions
__init__ (self, field, to, related_name=None, related_query_name=None, limit_choices_to=None)
Detailed Description
Used by GenericRelation to store information about the relation.
Definition at line 282 of file fields.py.
Constructor & Destructor Documentation
__init__()
django.contrib.contenttypes.fields.GenericRel.__init__ (self, field, to, related_name = None, related_query_name = None, limit_choices_to = None)
Definition at line 287 of file fields.py.
    ):
        super().__init__(
            field,
            to,
            related_name=related_query_name or "+",
            related_query_name=related_query_name,
            limit_choices_to=limit_choices_to,
            on_delete=DO_NOTHING,
        )
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/contenttypes/fields.py