Read&Watch: pip._internal.vcs.versioncontrol.RevOptions Class Reference
pip._internal.vcs.versioncontrol.RevOptions Class Reference
Public Member Functions
str __repr__ (self)
Optional[str] arg_rev (self)
CommandArgs to_args (self)
str to_display (self)
"RevOptions" make_new (self, str rev)
Static Public Attributes
Type vc_class ["VersionControl"]
Optional rev = None
CommandArgs extra_args = field(default_factory=list)
Optional branch_name = None
Detailed Description
Encapsulates a VCS-specific revision to install, along with any VCS
install options.
Args:
    vc_class: a VersionControl subclass.
    rev: the name of the revision to install.
    extra_args: a list of extra options.
Definition at line 118 of file versioncontrol.py.
Member Function Documentation
__repr__()
str pip._internal.vcs.versioncontrol.RevOptions.__repr__ (self)
Definition at line 134 of file versioncontrol.py.
    def __repr__(self) -> str:
        return f"<RevOptions {self.vc_class.name}: rev={self.rev!r}>"
arg_rev()
Optional[str] pip._internal.vcs.versioncontrol.RevOptions.arg_rev (self)
Definition at line 138 of file versioncontrol.py.
    def arg_rev(self) -> Optional[str]:
        if self.rev is None:
            return self.vc_class.default_arg_rev
        return self.rev
References rev, and vc_class.
Referenced by to_args().
make_new()
"RevOptions" pip._internal.vcs.versioncontrol.RevOptions.make_new (self, str rev)
Make a copy of the current instance, but with a new rev.
Args:
  rev: the name of the revision for the new object.
Definition at line 162 of file versioncontrol.py.
    def make_new(self, rev: str) -> "RevOptions":
        """
        Make a copy of the current instance, but with a new rev.
        Args:
          rev: the name of the revision for the new object.
        """
        return self.vc_class.make_rev_options(rev, extra_args=self.extra_args)
References extra_args, and vc_class.
to_args()
CommandArgs pip._internal.vcs.versioncontrol.RevOptions.to_args (self)
Return the VCS-specific command arguments.
Definition at line 144 of file versioncontrol.py.
    def to_args(self) -> CommandArgs:
        """
        Return the VCS-specific command arguments.
        """
        args: CommandArgs = []
        rev = self.arg_rev
        if rev is not None:
            args += self.vc_class.get_base_rev_args(rev)
        args += self.extra_args
        return args
References arg_rev(), extra_args, and vc_class.
to_display()
str pip._internal.vcs.versioncontrol.RevOptions.to_display (self)
Definition at line 156 of file versioncontrol.py.
    def to_display(self) -> str:
        if not self.rev:
            return ""
        return f" (to revision {self.rev})"
References rev.
Member Data Documentation
branch_name
Optional pip._internal.vcs.versioncontrol.RevOptions.branch_name = None static
Definition at line 132 of file versioncontrol.py.
extra_args
CommandArgs pip._internal.vcs.versioncontrol.RevOptions.extra_args = field(default_factory=list) static
Definition at line 131 of file versioncontrol.py.
Referenced by make_new(), and to_args().
rev
Optional pip._internal.vcs.versioncontrol.RevOptions.rev = None static
Definition at line 130 of file versioncontrol.py.
Referenced by arg_rev(), and to_display().
vc_class
Type pip._internal.vcs.versioncontrol.RevOptions.vc_class ["VersionControl"] static
Definition at line 129 of file versioncontrol.py.
Referenced by arg_rev(), make_new(), and to_args().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_internal/vcs/versioncontrol.py