Read&Watch: pip._vendor.pkg_resources.WorkingSet Class Reference
pip._vendor.pkg_resources.WorkingSet Class Reference
Public Member Functions
__init__ (self, Iterable[str]|None entries=None)
add_entry (self, str entry)
bool __contains__ (self, Distribution dist)
Distribution|None find (self, Requirement req)
iter_entry_points (self, str group, str|None name=None)
run_script (self, str requires, str script_name)
Iterator[Distribution] __iter__ (self)
add (self, Distribution dist, str|None entry=None, bool insert=True, bool replace=False)
list[_DistributionT] resolve (self, Iterable[Requirement] requirements, Environment|None env, _InstallerTypeT[_DistributionT] installer, bool replace_conflicting=False, tuple[str,...]|None extras=None)
list[_DistributionT] resolve (self, Iterable[Requirement] requirements, Environment|None env=None, *, _InstallerTypeT[_DistributionT] installer, bool replace_conflicting=False, tuple[str,...]|None extras=None)
list[Distribution] resolve (self, Iterable[Requirement] requirements, Environment|None env=None, _InstallerType|None installer=None, bool replace_conflicting=False, tuple[str,...]|None extras=None)
list[Distribution]|list[_DistributionT] resolve (self, Iterable[Requirement] requirements, Environment|None env=None, _InstallerType|None|_InstallerTypeT[_DistributionT] installer=None, bool replace_conflicting=False, tuple[str,...]|None extras=None)
tuple[list[_DistributionT], dict[Distribution, Exception]] find_plugins (self, Environment plugin_env, Environment|None full_env, _InstallerTypeT[_DistributionT] installer, bool fallback=True)
tuple[list[_DistributionT], dict[Distribution, Exception]] find_plugins (self, Environment plugin_env, Environment|None full_env=None, *, _InstallerTypeT[_DistributionT] installer, bool fallback=True)
tuple[list[Distribution], dict[Distribution, Exception]] find_plugins (self, Environment plugin_env, Environment|None full_env=None, _InstallerType|None installer=None, bool fallback=True)
tuple[ list[Distribution]|list[_DistributionT], dict[Distribution, Exception],] find_plugins (self, Environment plugin_env, Environment|None full_env=None, _InstallerType|None|_InstallerTypeT[_DistributionT] installer=None, bool fallback=True)
require (self, *_NestedStr requirements)
subscribe (self, Callable[[Distribution], object] callback, bool existing=True)
__getstate__ (self)
__setstate__ (self, e_k_b_n_c)
Public Attributes
list entries = []
dict entry_keys = {}
dict by_key = {}
dict normalized_to_canonical_keys = {}
list callbacks = []
Protected Member Functions
_build_master (cls)
_build_from_requirements (cls, req_spec)
Distribution _resolve_dist (self, req, best, replace_conflicting, env, installer, required_by, to_activate)
_added_new (self, dist)
Detailed Description
A collection of active distributions on sys.path (or a similar list)
Definition at line 625 of file __init__.py.
Constructor & Destructor Documentation
__init__()
pip._vendor.pkg_resources.WorkingSet.__init__ (self, Iterable[str] | None entries = None)
Create working set from list of path entries (default=sys.path)
Definition at line 628 of file __init__.py.
    def __init__(self, entries: Iterable[str] | None = None):
        """Create working set from list of path entries (default=sys.path)"""
        self.entries: list[str] = []
        self.entry_keys = {}
        self.by_key = {}
        self.normalized_to_canonical_keys = {}
        self.callbacks = []
        if entries is None:
            entries = sys.path
        for entry in entries:
            self.add_entry(entry)
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
__contains__()
bool pip._vendor.pkg_resources.WorkingSet.__contains__ (self, Distribution dist)
True if `dist` is the active distribution for its project
Definition at line 699 of file __init__.py.
    def __contains__(self, dist: Distribution) -> bool:
        """True if `dist` is the active distribution for its project"""
        return self.by_key.get(dist.key) == dist
__getstate__()
pip._vendor.pkg_resources.WorkingSet.__getstate__ (self)
Definition at line 1088 of file __init__.py.
    def __getstate__(self):
        return (
            self.entries[:],
            self.entry_keys.copy(),
            self.by_key.copy(),
            self.normalized_to_canonical_keys.copy(),
            self.callbacks[:],
        )
__iter__()
Iterator[Distribution] pip._vendor.pkg_resources.WorkingSet.__iter__ (self)
Yield distributions for non-duplicate projects in the working set
The yield order is the order in which the items' path entries were
added to the working set.
Definition at line 749 of file __init__.py.
    def __iter__(self) -> Iterator[Distribution]:
        """Yield distributions for non-duplicate projects in the working set
        The yield order is the order in which the items' path entries were
        added to the working set.
        """
        seen = set()
        for item in self.entries:
            if item not in self.entry_keys:
                # workaround a cache issue
                continue
            for key in self.entry_keys[item]:
                if key not in seen:
                    seen.add(key)
                    yield self.by_key[key]
Referenced by django.db.models.query.BaseIterable._async_generator().
__setstate__()
pip._vendor.pkg_resources.WorkingSet.__setstate__ (self, e_k_b_n_c)
Definition at line 1097 of file __init__.py.
    def __setstate__(self, e_k_b_n_c):
        entries, keys, by_key, normalized_to_canonical_keys, callbacks = e_k_b_n_c
        self.entries = entries[:]
        self.entry_keys = keys.copy()
        self.by_key = by_key.copy()
        self.normalized_to_canonical_keys = normalized_to_canonical_keys.copy()
        self.callbacks = callbacks[:]
_added_new()
pip._vendor.pkg_resources.WorkingSet._added_new (self, dist) protected
Definition at line 1084 of file __init__.py.
    def _added_new(self, dist):
        for callback in self.callbacks:
            callback(dist)
_build_from_requirements()
pip._vendor.pkg_resources.WorkingSet._build_from_requirements (cls, req_spec) protected
Build a working set from a requirement spec. Rewrites sys.path.
Definition at line 663 of file __init__.py.
    def _build_from_requirements(cls, req_spec):
        """
        Build a working set from a requirement spec. Rewrites sys.path.
        """
        # try it without defaults already on sys.path
        # by starting with an empty path
        ws = cls([])
        reqs = parse_requirements(req_spec)
        dists = ws.resolve(reqs, Environment())
        for dist in dists:
            ws.add(dist)
        # add any missing entries from sys.path
        for entry in sys.path:
            if entry not in ws.entries:
                ws.add_entry(entry)
        # then copy back to sys.path
        sys.path[:] = ws.entries
        return ws
_build_master()
pip._vendor.pkg_resources.WorkingSet._build_master (cls) protected
Prepare the master working set.
Definition at line 643 of file __init__.py.
    def _build_master(cls):
        """
        Prepare the master working set.
        """
        ws = cls()
        try:
            from __main__ import __requires__
        except ImportError:
            # The main program does not list any requirements
            return ws
        # ensure the requirements are met
        try:
            ws.require(__requires__)
        except VersionConflict:
            return cls._build_from_requirements(__requires__)
        return ws
_resolve_dist()
Distribution pip._vendor.pkg_resources.WorkingSet._resolve_dist (self, req, best, replace_conflicting, env, installer, required_by, to_activate) protected
Definition at line 906 of file __init__.py.
    ) -> Distribution:
        dist = best.get(req.key)
        if dist is None:
            # Find the best distribution and add it to the map
            dist = self.by_key.get(req.key)
            if dist is None or (dist not in req and replace_conflicting):
                ws = self
                if env is None:
                    if dist is None:
                        env = Environment(self.entries)
                    else:
                        # Use an empty environment and workingset to avoid
                        # any further conflicts with the conflicting
                        # distribution
                        env = Environment([])
                        ws = WorkingSet([])
                dist = best[req.key] = env.best_match(
                    req, ws, installer, replace_conflicting=replace_conflicting
                )
                if dist is None:
                    requirers = required_by.get(req, None)
                    raise DistributionNotFound(req, requirers)
            to_activate.append(dist)
        if dist not in req:
            # Oops, the "best" so far conflicts with a dependency
            dependent_req = required_by[req]
            raise VersionConflict(dist, req).with_context(dependent_req)
        return dist
add()
pip._vendor.pkg_resources.WorkingSet.add (self, Distribution dist, str | None entry = None, bool insert = True, bool replace = False)
Add `dist` to working set, associated with `entry`
If `entry` is unspecified, it defaults to the ``.location`` of `dist`.
On exit from this routine, `entry` is added to the end of the working
set's ``.entries`` (if it wasn't already present).
`dist` is only added to the working set if it's for a project that
doesn't already have a distribution in the set, unless `replace=True`.
If it's added, any callbacks registered with the ``subscribe()`` method
will be called.
Definition at line 766 of file __init__.py.
    ):
        """Add `dist` to working set, associated with `entry`
        If `entry` is unspecified, it defaults to the ``.location`` of `dist`.
        On exit from this routine, `entry` is added to the end of the working
        set's ``.entries`` (if it wasn't already present).
        `dist` is only added to the working set if it's for a project that
        doesn't already have a distribution in the set, unless `replace=True`.
        If it's added, any callbacks registered with the ``subscribe()`` method
        will be called.
        """
        if insert:
            dist.insert_on(self.entries, entry, replace=replace)
        if entry is None:
            entry = dist.location
        keys = self.entry_keys.setdefault(entry, [])
        keys2 = self.entry_keys.setdefault(dist.location, [])
        if not replace and dist.key in self.by_key:
            # ignore hidden distros
            return
        self.by_key[dist.key] = dist
        normalized_name = _packaging_utils.canonicalize_name(dist.key)
        self.normalized_to_canonical_keys[normalized_name] = dist.key
        if dist.key not in keys:
            keys.append(dist.key)
        if dist.key not in keys2:
            keys2.append(dist.key)
        self._added_new(dist)
Referenced by responses.RequestsMock._add_from_file(), pip._vendor.urllib3._collections.HTTPHeaderDict.extend(), urllib3._collections.HTTPHeaderDict.extend(), and responses.RequestsMock.upsert().
add_entry()
pip._vendor.pkg_resources.WorkingSet.add_entry (self, str entry)
Add a path item to ``.entries``, finding any distributions on it
``find_distributions(entry, True)`` is used to find distributions
corresponding to the path entry, and they are added.  `entry` is
always appended to ``.entries``, even if it is already present.
(This is because ``sys.path`` can contain the same value more than
once, and the ``.entries`` of the ``sys.path`` WorkingSet should always
equal ``sys.path``.)
Definition at line 684 of file __init__.py.
    def add_entry(self, entry: str):
        """Add a path item to ``.entries``, finding any distributions on it
        ``find_distributions(entry, True)`` is used to find distributions
        corresponding to the path entry, and they are added.  `entry` is
        always appended to ``.entries``, even if it is already present.
        (This is because ``sys.path`` can contain the same value more than
        once, and the ``.entries`` of the ``sys.path`` WorkingSet should always
        equal ``sys.path``.)
        """
        self.entry_keys.setdefault(entry, [])
        self.entries.append(entry)
        for dist in find_distributions(entry, True):
            self.add(dist, entry, False)
find()
Distribution | None pip._vendor.pkg_resources.WorkingSet.find (self, Requirement req)
Find a distribution matching requirement `req`
If there is an active distribution for the requested project, this
returns it as long as it meets the version requirement specified by
`req`.  But, if there is an active distribution for the project and it
does *not* meet the `req` requirement, ``VersionConflict`` is raised.
If there is no active distribution for the requested project, ``None``
is returned.
Definition at line 703 of file __init__.py.
    def find(self, req: Requirement) -> Distribution | None:
        """Find a distribution matching requirement `req`
        If there is an active distribution for the requested project, this
        returns it as long as it meets the version requirement specified by
        `req`.  But, if there is an active distribution for the project and it
        does *not* meet the `req` requirement, ``VersionConflict`` is raised.
        If there is no active distribution for the requested project, ``None``
        is returned.
        """
        dist = self.by_key.get(req.key)
        if dist is None:
            canonical_key = self.normalized_to_canonical_keys.get(req.key)
            if canonical_key is not None:
                req.key = canonical_key
                dist = self.by_key.get(canonical_key)
        if dist is not None and dist not in req:
            # XXX add more info
            raise VersionConflict(dist, req)
        return dist
find_plugins() [1/4]
tuple[list[_DistributionT], dict[Distribution, Exception]] pip._vendor.pkg_resources.WorkingSet.find_plugins (self, Environment plugin_env, Environment | None full_env, _InstallerTypeT[_DistributionT] installer, bool fallback = True)
Definition at line 938 of file __init__.py.
    ) -> tuple[list[_DistributionT], dict[Distribution, Exception]]: ...
find_plugins() [2/4]
tuple[list[_DistributionT], dict[Distribution, Exception]] pip._vendor.pkg_resources.WorkingSet.find_plugins (self, Environment plugin_env, Environment | None full_env = None, * , _InstallerTypeT[_DistributionT] installer, bool fallback = True)
Definition at line 946 of file __init__.py.
    ) -> tuple[list[_DistributionT], dict[Distribution, Exception]]: ...
find_plugins() [3/4]
tuple[list[Distribution], dict[Distribution, Exception]] pip._vendor.pkg_resources.WorkingSet.find_plugins (self, Environment plugin_env, Environment | None full_env = None, _InstallerType | None installer = None, bool fallback = True)
Definition at line 955 of file __init__.py.
    ) -> tuple[list[Distribution], dict[Distribution, Exception]]: ...
find_plugins() [4/4]
tuple[ list[Distribution] | list[_DistributionT], dict[Distribution, Exception], ] pip._vendor.pkg_resources.WorkingSet.find_plugins (self, Environment plugin_env, Environment | None full_env = None, _InstallerType | None | _InstallerTypeT[_DistributionT] installer = None, bool fallback = True)
Find all activatable distributions in `plugin_env`
Example usage::
    distributions, errors = working_set.find_plugins(
        Environment(plugin_dirlist)
    )
    # add plugins+libs to sys.path
    map(working_set.add, distributions)
    # display errors
    print('Could not load', errors)
The `plugin_env` should be an ``Environment`` instance that contains
only distributions that are in the project's "plugin directory" or
directories. The `full_env`, if supplied, should be an ``Environment``
contains all currently-available distributions.  If `full_env` is not
supplied, one is created automatically from the ``WorkingSet`` this
method is called on, which will typically mean that every directory on
``sys.path`` will be scanned for distributions.
`installer` is a standard installer callback as used by the
``resolve()`` method. The `fallback` flag indicates whether we should
attempt to resolve older versions of a plugin if the newest version
cannot be resolved.
This method returns a 2-tuple: (`distributions`, `error_info`), where
`distributions` is a list of the distributions found in `plugin_env`
that were loadable, along with any other distributions that are needed
to resolve their dependencies.  `error_info` is a dictionary mapping
unloadable plugin distributions to an exception instance describing the
error that occurred. Usually this will be a ``DistributionNotFound`` or
``VersionConflict`` instance.
Definition at line 962 of file __init__.py.
    ]:
        """Find all activatable distributions in `plugin_env`
        Example usage::
            distributions, errors = working_set.find_plugins(
                Environment(plugin_dirlist)
            )
            # add plugins+libs to sys.path
            map(working_set.add, distributions)
            # display errors
            print('Could not load', errors)
        The `plugin_env` should be an ``Environment`` instance that contains
        only distributions that are in the project's "plugin directory" or
        directories. The `full_env`, if supplied, should be an ``Environment``
        contains all currently-available distributions.  If `full_env` is not
        supplied, one is created automatically from the ``WorkingSet`` this
        method is called on, which will typically mean that every directory on
        ``sys.path`` will be scanned for distributions.
        `installer` is a standard installer callback as used by the
        ``resolve()`` method. The `fallback` flag indicates whether we should
        attempt to resolve older versions of a plugin if the newest version
        cannot be resolved.
        This method returns a 2-tuple: (`distributions`, `error_info`), where
        `distributions` is a list of the distributions found in `plugin_env`
        that were loadable, along with any other distributions that are needed
        to resolve their dependencies.  `error_info` is a dictionary mapping
        unloadable plugin distributions to an exception instance describing the
        error that occurred. Usually this will be a ``DistributionNotFound`` or
        ``VersionConflict`` instance.
        """
        plugin_projects = list(plugin_env)
        # scan project names in alphabetic order
        plugin_projects.sort()
        error_info: dict[Distribution, Exception] = {}
        distributions: dict[Distribution, Exception | None] = {}
        if full_env is None:
            env = Environment(self.entries)
            env += plugin_env
        else:
            env = full_env + plugin_env
        shadow_set = self.__class__([])
        # put all our entries in shadow_set
        list(map(shadow_set.add, self))
        for project_name in plugin_projects:
            for dist in plugin_env[project_name]:
                req = [dist.as_requirement()]
                try:
                    resolvees = shadow_set.resolve(req, env, installer)
                except ResolutionError as v:
                    # save error info
                    error_info[dist] = v
                    if fallback:
                        # try the next older version of project
                        continue
                    else:
                        # give up on this project, keep going
                        break
                else:
                    list(map(shadow_set.add, resolvees))
                    distributions.update(dict.fromkeys(resolvees))
                    # success, no need to try any more versions of this project
                    break
        sorted_distributions = list(distributions)
        sorted_distributions.sort()
        return sorted_distributions, error_info
iter_entry_points()
pip._vendor.pkg_resources.WorkingSet.iter_entry_points (self, str group, str | None name = None)
Yield entry point objects from `group` matching `name`
If `name` is None, yields all entry points in `group` from all
distributions in the working set, otherwise only ones matching
both `group` and `name` are yielded (in distribution order).
Definition at line 727 of file __init__.py.
    def iter_entry_points(self, group: str, name: str | None = None):
        """Yield entry point objects from `group` matching `name`
        If `name` is None, yields all entry points in `group` from all
        distributions in the working set, otherwise only ones matching
        both `group` and `name` are yielded (in distribution order).
        """
        return (
            entry
            for dist in self
            for entry in dist.get_entry_map(group).values()
            if name is None or name == entry.name
        )
require()
pip._vendor.pkg_resources.WorkingSet.require (self, *_NestedStr requirements)
Ensure that distributions matching `requirements` are activated
`requirements` must be a string or a (possibly-nested) sequence
thereof, specifying the distributions and versions required.  The
return value is a sequence of the distributions that needed to be
activated to fulfill the requirements; all relevant distributions are
included, even if they were already activated in this working set.
Definition at line 1052 of file __init__.py.
    def require(self, *requirements: _NestedStr):
        """Ensure that distributions matching `requirements` are activated
        `requirements` must be a string or a (possibly-nested) sequence
        thereof, specifying the distributions and versions required.  The
        return value is a sequence of the distributions that needed to be
        activated to fulfill the requirements; all relevant distributions are
        included, even if they were already activated in this working set.
        """
        needed = self.resolve(parse_requirements(requirements))
        for dist in needed:
            self.add(dist)
        return needed
resolve() [1/4]
list[_DistributionT] pip._vendor.pkg_resources.WorkingSet.resolve (self, Iterable[Requirement] requirements, Environment | None env, _InstallerTypeT[_DistributionT] installer, bool replace_conflicting = False, tuple[str, ...] | None extras = None)
Definition at line 805 of file __init__.py.
    ) -> list[_DistributionT]: ...
Referenced by yaml.composer.Composer.compose_mapping_node(), yaml.composer.Composer.compose_scalar_node(), yaml.composer.Composer.compose_sequence_node(), and yaml.serializer.Serializer.serialize_node().
resolve() [2/4]
list[_DistributionT] pip._vendor.pkg_resources.WorkingSet.resolve (self, Iterable[Requirement] requirements, Environment | None env = None, * , _InstallerTypeT[_DistributionT] installer, bool replace_conflicting = False, tuple[str, ...] | None extras = None)
Definition at line 814 of file __init__.py.
    ) -> list[_DistributionT]: ...
Referenced by yaml.composer.Composer.compose_mapping_node(), yaml.composer.Composer.compose_scalar_node(), yaml.composer.Composer.compose_sequence_node(), and yaml.serializer.Serializer.serialize_node().
resolve() [3/4]
list[Distribution] pip._vendor.pkg_resources.WorkingSet.resolve (self, Iterable[Requirement] requirements, Environment | None env = None, _InstallerType | None installer = None, bool replace_conflicting = False, tuple[str, ...] | None extras = None)
Definition at line 824 of file __init__.py.
    ) -> list[Distribution]: ...
Referenced by yaml.composer.Composer.compose_mapping_node(), yaml.composer.Composer.compose_scalar_node(), yaml.composer.Composer.compose_sequence_node(), and yaml.serializer.Serializer.serialize_node().
resolve() [4/4]
list[Distribution] | list[_DistributionT] pip._vendor.pkg_resources.WorkingSet.resolve (self, Iterable[Requirement] requirements, Environment | None env = None, _InstallerType | None | _InstallerTypeT[_DistributionT] installer = None, bool replace_conflicting = False, tuple[str, ...] | None extras = None)
List all distributions needed to (recursively) meet `requirements`
`requirements` must be a sequence of ``Requirement`` objects.  `env`,
if supplied, should be an ``Environment`` instance.  If
not supplied, it defaults to all distributions available within any
entry or distribution in the working set.  `installer`, if supplied,
will be invoked with each requirement that cannot be met by an
already-installed distribution; it should return a ``Distribution`` or
``None``.
Unless `replace_conflicting=True`, raises a VersionConflict exception
if
any requirements are found on the path that have the correct name but
the wrong version.  Otherwise, if an `installer` is supplied it will be
invoked to obtain the correct version of the requirement and activate
it.
`extras` is a list of the extras to be used with these requirements.
This is important because extra requirements may look like `my_req;
extra = "my_extra"`, which would otherwise be interpreted as a purely
optional requirement.  Instead, we want to be able to assert that these
requirements are truly required.
Definition at line 832 of file __init__.py.
    ) -> list[Distribution] | list[_DistributionT]:
        """List all distributions needed to (recursively) meet `requirements`
        `requirements` must be a sequence of ``Requirement`` objects.  `env`,
        if supplied, should be an ``Environment`` instance.  If
        not supplied, it defaults to all distributions available within any
        entry or distribution in the working set.  `installer`, if supplied,
        will be invoked with each requirement that cannot be met by an
        already-installed distribution; it should return a ``Distribution`` or
        ``None``.
        Unless `replace_conflicting=True`, raises a VersionConflict exception
        if
        any requirements are found on the path that have the correct name but
        the wrong version.  Otherwise, if an `installer` is supplied it will be
        invoked to obtain the correct version of the requirement and activate
        it.
        `extras` is a list of the extras to be used with these requirements.
        This is important because extra requirements may look like `my_req;
        extra = "my_extra"`, which would otherwise be interpreted as a purely
        optional requirement.  Instead, we want to be able to assert that these
        requirements are truly required.
        """
        # set up the stack
        requirements = list(requirements)[::-1]
        # set of processed requirements
        processed = set()
        # key -> dist
        best = {}
        to_activate = []
        req_extras = _ReqExtras()
        # Mapping of requirement to set of distributions that required it;
        # useful for reporting info about conflicts.
        required_by = collections.defaultdict(set)
        while requirements:
            # process dependencies breadth-first
            req = requirements.pop(0)
            if req in processed:
                # Ignore cyclic or redundant dependencies
                continue
            if not req_extras.markers_pass(req, extras):
                continue
            dist = self._resolve_dist(
                req, best, replace_conflicting, env, installer, required_by, to_activate
            )
            # push the new requirements onto the stack
            new_requirements = dist.requires(req.extras)[::-1]
            requirements.extend(new_requirements)
            # Register the new requirements needed by req
            for new_requirement in new_requirements:
                required_by[new_requirement].add(req.project_name)
                req_extras[new_requirement] = req.extras
            processed.add(req)
        # return list of distros to activate
        return to_activate
Referenced by yaml.composer.Composer.compose_mapping_node(), yaml.composer.Composer.compose_scalar_node(), yaml.composer.Composer.compose_sequence_node(), and yaml.serializer.Serializer.serialize_node().
run_script()
pip._vendor.pkg_resources.WorkingSet.run_script (self, str requires, str script_name)
Locate distribution for `requires` and run `script_name` script
Definition at line 741 of file __init__.py.
    def run_script(self, requires: str, script_name: str):
        """Locate distribution for `requires` and run `script_name` script"""
        ns = sys._getframe(1).f_globals
        name = ns['__name__']
        ns.clear()
        ns['__name__'] = name
        self.require(requires)[0].run_script(script_name, ns)
subscribe()
pip._vendor.pkg_resources.WorkingSet.subscribe (self, Callable[[Distribution], object] callback, bool existing = True)
Invoke `callback` for all distributions
If `existing=True` (default),
call on all existing ones, as well.
Definition at line 1068 of file __init__.py.
    ):
        """Invoke `callback` for all distributions
        If `existing=True` (default),
        call on all existing ones, as well.
        """
        if callback in self.callbacks:
            return
        self.callbacks.append(callback)
        if not existing:
            return
        for dist in self:
            callback(dist)
Member Data Documentation
by_key
dict pip._vendor.pkg_resources.WorkingSet.by_key = {}
Definition at line 632 of file __init__.py.
callbacks
list pip._vendor.pkg_resources.WorkingSet.callbacks = []
Definition at line 634 of file __init__.py.
entries
pip._vendor.pkg_resources.WorkingSet.entries = []
Definition at line 630 of file __init__.py.
entry_keys
dict pip._vendor.pkg_resources.WorkingSet.entry_keys = {}
Definition at line 631 of file __init__.py.
normalized_to_canonical_keys
dict pip._vendor.pkg_resources.WorkingSet.normalized_to_canonical_keys = {}
Definition at line 633 of file __init__.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/pkg_resources/__init__.py