Read&Watch: django.test.utils.TestContextDecorator Class Reference
django.test.utils.TestContextDecorator Class Reference
Public Member Functions
__init__ (self, attr_name=None, kwarg_name=None)
enable (self)
disable (self)
__enter__ (self)
__exit__ (self, exc_type, exc_value, traceback)
decorate_class (self, cls)
decorate_callable (self, func)
__call__ (self, decorated)
Public Attributes
attr_name = attr_name
kwarg_name = kwarg_name
disable
setUp = setUp
Detailed Description
A base class that can either be used as a context manager during tests
or as a test function or unittest.TestCase subclass decorator to perform
temporary alterations.
`attr_name`: attribute assigned the return value of enable() if used as
             a class decorator.
`kwarg_name`: keyword argument passing the return value of enable() if
              used as a function decorator.
Definition at line 384 of file utils.py.
Constructor & Destructor Documentation
__init__()
django.test.utils.TestContextDecorator.__init__ (self, attr_name = None, kwarg_name = None)
Definition at line 397 of file utils.py.
    def __init__(self, attr_name=None, kwarg_name=None):
        self.attr_name = attr_name
        self.kwarg_name = kwarg_name
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
__call__()
django.test.utils.TestContextDecorator.__call__ (self, decorated)
Definition at line 450 of file utils.py.
    def __call__(self, decorated):
        if isinstance(decorated, type):
            return self.decorate_class(decorated)
        elif callable(decorated):
            return self.decorate_callable(decorated)
        raise TypeError("Cannot decorate object of type %s" % type(decorated))
References decorate_callable(), and decorate_class().
__enter__()
django.test.utils.TestContextDecorator.__enter__ (self)
Definition at line 407 of file utils.py.
    def __enter__(self):
        return self.enable()
References enable().
__exit__()
django.test.utils.TestContextDecorator.__exit__ (self, exc_type, exc_value, traceback)
Definition at line 410 of file utils.py.
    def __exit__(self, exc_type, exc_value, traceback):
        self.disable()
References disable.
Referenced by django.test.utils.ignore_warnings.disable().
decorate_callable()
django.test.utils.TestContextDecorator.decorate_callable (self, func)
Definition at line 428 of file utils.py.
    def decorate_callable(self, func):
        if iscoroutinefunction(func):
            # If the inner function is an async function, we must execute async
            # as well so that the `with` statement executes at the right time.
            @wraps(func)
            async def inner(*args, **kwargs):
                with self as context:
                    if self.kwarg_name:
                        kwargs[self.kwarg_name] = context
                    return await func(*args, **kwargs)
        else:
            @wraps(func)
            def inner(*args, **kwargs):
                with self as context:
                    if self.kwarg_name:
                        kwargs[self.kwarg_name] = context
                    return func(*args, **kwargs)
        return inner
References kwarg_name.
Referenced by __call__().
decorate_class()
django.test.utils.TestContextDecorator.decorate_class (self, cls)
Reimplemented in django.test.utils.override_settings.
Definition at line 413 of file utils.py.
    def decorate_class(self, cls):
        if issubclass(cls, TestCase):
            decorated_setUp = cls.setUp
            def setUp(inner_self):
                context = self.enable()
                inner_self.addCleanup(self.disable)
                if self.attr_name:
                    setattr(inner_self, self.attr_name, context)
                decorated_setUp(inner_self)
            cls.setUp = setUp
            return cls
        raise TypeError("Can only decorate subclasses of unittest.TestCase")
References enable(), and setUp.
Referenced by __call__().
disable()
django.test.utils.TestContextDecorator.disable (self)
Reimplemented in django.test.utils.ignore_warnings, django.test.utils.isolate_apps, django.test.utils.override_script_prefix, django.test.utils.override_settings, and django.test.utils.override_system_checks.
Definition at line 404 of file utils.py.
    def disable(self):
        raise NotImplementedError
Referenced by pylint.lint.pylinter.PyLinter._parse_error_mode(), pylint.lint.message_state_handler._MessageStateHandler.disable_noerror_messages(), and pylint.lint.pylinter.PyLinter.register_checker().
enable()
django.test.utils.TestContextDecorator.enable (self)
Reimplemented in django.test.utils.ignore_warnings, django.test.utils.isolate_apps, django.test.utils.modify_settings, django.test.utils.override_script_prefix, django.test.utils.override_settings, and django.test.utils.override_system_checks.
Definition at line 401 of file utils.py.
    def enable(self):
        raise NotImplementedError
Referenced by __enter__(), decorate_class(), and pylint.lint.pylinter.PyLinter.enable_fail_on_messages().
Member Data Documentation
attr_name
django.test.utils.TestContextDecorator.attr_name = attr_name
Definition at line 398 of file utils.py.
disable
django.test.utils.TestContextDecorator.disable
Reimplemented in django.test.utils.ignore_warnings, django.test.utils.isolate_apps, django.test.utils.override_script_prefix, django.test.utils.override_settings, and django.test.utils.override_system_checks.
Definition at line 419 of file utils.py.
Referenced by __exit__(), pylint.lint.pylinter.PyLinter._parse_error_mode(), pylint.lint.message_state_handler._MessageStateHandler.disable_noerror_messages(), pip._vendor.rich.progress.Progress.refresh(), pylint.lint.pylinter.PyLinter.register_checker(), and pip._vendor.rich.progress.Progress.start().
kwarg_name
django.test.utils.TestContextDecorator.kwarg_name = kwarg_name
Definition at line 399 of file utils.py.
Referenced by decorate_callable().
setUp
django.test.utils.TestContextDecorator.setUp = setUp
Definition at line 424 of file utils.py.
Referenced by decorate_class().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/test/utils.py