Read&Watch: pip._vendor.typing_extensions._LiteralForm Class Reference
pip._vendor.typing_extensions._LiteralForm Class Reference
Public Member Functions
__init__ (self, str doc)
__getitem__ (self, parameters)
Public Member Functions inherited from pip._vendor.typing_extensions._ExtensionsSpecialForm
__repr__ (self)
Protected Attributes
str _name = 'Literal'
_doc = doc
Detailed Description
Definition at line 288 of file typing_extensions.py.
Constructor & Destructor Documentation
__init__()
pip._vendor.typing_extensions._LiteralForm.__init__ (self, str doc)
Definition at line 289 of file typing_extensions.py.
        def __init__(self, doc: str):
            self._name = 'Literal'
            self._doc = self.__doc__ = doc
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
__getitem__()
pip._vendor.typing_extensions._LiteralForm.__getitem__ (self, parameters)
Definition at line 293 of file typing_extensions.py.
        def __getitem__(self, parameters):
            if not isinstance(parameters, tuple):
                parameters = (parameters,)
            parameters = _flatten_literal_params(parameters)
            val_type_pairs = list(_value_and_type_iter(parameters))
            try:
                deduped_pairs = set(val_type_pairs)
            except TypeError:
                # unhashable parameters
                pass
            else:
                # similar logic to typing._deduplicate on Python 3.9+
                if len(deduped_pairs) < len(val_type_pairs):
                    new_parameters = []
                    for pair in val_type_pairs:
                        if pair in deduped_pairs:
                            new_parameters.append(pair[0])
                            deduped_pairs.remove(pair)
                    assert not deduped_pairs, deduped_pairs
                    parameters = tuple(new_parameters)
            return _LiteralGenericAlias(self, parameters)
    Literal = _LiteralForm(doc="""\
References pip._vendor.typing_extensions._flatten_literal_params(), and pip._vendor.typing_extensions._value_and_type_iter().
Member Data Documentation
_doc
pip._vendor.typing_extensions._LiteralForm._doc = doc protected
Definition at line 291 of file typing_extensions.py.
_name
str pip._vendor.typing_extensions._LiteralForm._name = 'Literal' protected
Definition at line 290 of file typing_extensions.py.
Referenced by pip._vendor.typing_extensions._SpecialForm.__getattr__(), pip._vendor.typing_extensions._SpecialForm.__reduce__(), pip._vendor.typing_extensions._ExtensionsSpecialForm.__repr__(), and urllib3.fields.RequestField.make_multipart().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/typing_extensions.py