Read&Watch: PIL.PngImagePlugin.iTXt Class Reference
PIL.PngImagePlugin.iTXt Class Reference
Static Public Member Functions
iTXt __new__ (cls, str text, str|None lang=None, str|None tkey=None)
Static Public Attributes
str lang | bytes | None
str tkey | bytes | None
Detailed Description
Subclass of string to allow iTXt chunks to look like strings while
keeping their extra information
Definition at line 250 of file PngImagePlugin.py.
Member Function Documentation
__new__()
iTXt PIL.PngImagePlugin.iTXt.__new__ (cls, str text, str | None lang = None, str | None tkey = None) static
:param cls: the class to use when creating the instance
:param text: value for this key
:param lang: language code
:param tkey: UTF-8 version of the key name
Definition at line 261 of file PngImagePlugin.py.
    ) -> iTXt:
        """
        :param cls: the class to use when creating the instance
        :param text: value for this key
        :param lang: language code
        :param tkey: UTF-8 version of the key name
        """
        self = str.__new__(cls, text)
        self.lang = lang
        self.tkey = tkey
        return self
Referenced by apscheduler.triggers.combining.BaseCombiningTrigger.__setstate__(), pip._vendor.rich.style.Style._add(), pip._vendor.rich.style.Style.clear_meta_and_links(), yaml.constructor.SafeConstructor.construct_yaml_object(), pip._vendor.rich.style.Style.copy(), pip._vendor.rich.style.Style.from_color(), pip._vendor.rich.json.JSON.from_data(), pip._vendor.rich.style.Style.from_meta(), yaml.constructor.FullConstructor.make_python_instance(), pip._vendor.rich.style.Style.update_link(), and pip._vendor.rich.style.Style.without_color().
Member Data Documentation
lang
str PIL.PngImagePlugin.iTXt.lang | bytes | None static
Definition at line 257 of file PngImagePlugin.py.
Referenced by pip._vendor.pygments.formatters.latex.LatexEmbeddedLexer._find_safe_escape_tokens(), and pip._vendor.pygments.formatters.latex.LatexEmbeddedLexer.get_tokens_unprocessed().
tkey
str PIL.PngImagePlugin.iTXt.tkey | bytes | None static
Definition at line 258 of file PngImagePlugin.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/PIL/PngImagePlugin.py