Read&Watch: pip._internal.metadata.pkg_resources.Environment Class Reference
pip._internal.metadata.pkg_resources.Environment Class Reference
Public Member Functions
None __init__ (self, pkg_resources.WorkingSet ws)
BaseEnvironment default (cls)
BaseEnvironment from_paths (cls, Optional[List[str]] paths)
Optional[BaseDistribution] get_distribution (self, str name)
Public Member Functions inherited from pip._internal.metadata.base.BaseEnvironment
Iterator[BaseDistribution] iter_all_distributions (self)
Iterator[BaseDistribution] iter_installed_distributions (self, bool local_only=True, Container[str] skip=stdlib_pkgs, bool include_editables=True, bool editables_only=False, bool user_only=False)
Protected Member Functions
Iterator[BaseDistribution] _iter_distributions (self)
Optional[BaseDistribution] _search_distribution (self, str name)
Protected Attributes
_ws = ws
Detailed Description
Definition at line 253 of file pkg_resources.py.
Constructor & Destructor Documentation
__init__()
None pip._internal.metadata.pkg_resources.Environment.__init__ (self, pkg_resources.WorkingSet ws)
Definition at line 254 of file pkg_resources.py.
    def __init__(self, ws: pkg_resources.WorkingSet) -> None:
        self._ws = ws
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
_iter_distributions()
Iterator[BaseDistribution] pip._internal.metadata.pkg_resources.Environment._iter_distributions (self) protected
Iterate through installed distributions.
This function should be implemented by subclass, but never called
directly. Use the public ``iter_distribution()`` instead, which
implements additional logic to make sure the distributions are valid.
Reimplemented from pip._internal.metadata.base.BaseEnvironment.
Definition at line 265 of file pkg_resources.py.
    def _iter_distributions(self) -> Iterator[BaseDistribution]:
        for dist in self._ws:
            yield Distribution(dist)
References _ws.
_search_distribution()
Optional[BaseDistribution] pip._internal.metadata.pkg_resources.Environment._search_distribution (self, str name) protected
Find a distribution matching the ``name`` in the environment.
This searches from *all* distributions available in the environment, to
match the behavior of ``pkg_resources.get_distribution()``.
Definition at line 269 of file pkg_resources.py.
    def _search_distribution(self, name: str) -> Optional[BaseDistribution]:
        """Find a distribution matching the ``name`` in the environment.
        This searches from *all* distributions available in the environment, to
        match the behavior of ``pkg_resources.get_distribution()``.
        """
        canonical_name = canonicalize_name(name)
        for dist in self.iter_all_distributions():
            if dist.canonical_name == canonical_name:
                return dist
        return None
References pip._internal.metadata.base.BaseEnvironment.iter_all_distributions().
Referenced by get_distribution().
default()
BaseEnvironment pip._internal.metadata.pkg_resources.Environment.default (cls)
Reimplemented from pip._internal.metadata.base.BaseEnvironment.
Definition at line 258 of file pkg_resources.py.
    def default(cls) -> BaseEnvironment:
        return cls(pkg_resources.working_set)
from_paths()
BaseEnvironment pip._internal.metadata.pkg_resources.Environment.from_paths (cls, Optional[List[str]] paths)
Reimplemented from pip._internal.metadata.base.BaseEnvironment.
Definition at line 262 of file pkg_resources.py.
    def from_paths(cls, paths: Optional[List[str]]) -> BaseEnvironment:
        return cls(pkg_resources.WorkingSet(paths))
get_distribution()
Optional[BaseDistribution] pip._internal.metadata.pkg_resources.Environment.get_distribution (self, str name)
Given a requirement name, return the installed distributions.
The name may not be normalized. The implementation must canonicalize
it for lookup.
Reimplemented from pip._internal.metadata.base.BaseEnvironment.
Definition at line 281 of file pkg_resources.py.
    def get_distribution(self, name: str) -> Optional[BaseDistribution]:
        # Search the distribution by looking through the working set.
        dist = self._search_distribution(name)
        if dist:
            return dist
        # If distribution could not be found, call working_set.require to
        # update the working set, and try to find the distribution again.
        # This might happen for e.g. when you install a package twice, once
        # using setup.py develop and again using setup.py install. Now when
        # running pip uninstall twice, the package gets removed from the
        # working set in the first uninstall, so we have to populate the
        # working set again so that pip knows about it and the packages gets
        # picked up and is successfully uninstalled the second time too.
        try:
            # We didn't pass in any version specifiers, so this can never
            # raise pkg_resources.VersionConflict.
            self._ws.require(name)
        except pkg_resources.DistributionNotFound:
            return None
        return self._search_distribution(name)
References _search_distribution(), and _ws.
Referenced by pip._vendor.distlib.database.DistributionPath.get_file_path().
Member Data Documentation
_ws
pip._internal.metadata.pkg_resources.Environment._ws = ws protected
Definition at line 255 of file pkg_resources.py.
Referenced by _iter_distributions(), and get_distribution().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_internal/metadata/pkg_resources.py