Read&Watch: crispy_forms.bootstrap.StrictButton Class Reference
crispy_forms.bootstrap.StrictButton Class Reference
Public Member Functions
__init__ (self, content, css_id=None, css_class=None, template=None, **kwargs)
render (self, form, context, template_pack=TEMPLATE_PACK, **kwargs)
Public Member Functions inherited from crispy_forms.layout.TemplateNameMixin
get_template_name (self, template_pack)
Public Attributes
content = content
flat_attrs = flatatt(kwargs)
Public Attributes inherited from crispy_forms.layout.TemplateNameMixin
template
Static Public Attributes
str field_classes = "btn"
Detailed Description
Layout object for rendering an HTML button in a ``<button>`` tag.
Attributes
----------
template: str
    The default template which this Layout Object will be rendered
    with.
field_classes : str
    The CSS classes to be applied to the button. By defult "btn".
Parameters
----------
content : str
    The content of the button. This content is context aware, to bring
    this to life see the examples section.
css_id : str, optional
    A custom DOM id for the layout object which will be added to the
    ``<button>`` if provided. By default None.
css_class : str, optional
    Additional CSS classes to be applied to the ``<button>``. By default
    None.
template : str, optional
    Overrides the default template, if provided. By default None.
**kwargs : dict, optional
    Additional attributes are passed to `flatatt` and converted into
    key="value", pairs. These attributes are added to the ``<button>``.
Examples
--------
In your ``Layout``::
    StrictButton("button content", css_class="extra")
The content of the button is context aware, so you can do things like::
    StrictButton("Button for {{ user.username }}")
Definition at line 498 of file bootstrap.py.
Constructor & Destructor Documentation
__init__()
crispy_forms.bootstrap.StrictButton.__init__ (self, content, css_id = None, css_class = None, template = None, ** kwargs)
Definition at line 542 of file bootstrap.py.
    def __init__(self, content, css_id=None, css_class=None, template=None, **kwargs):
        self.content = content
        self.template = template or self.template
        kwargs.setdefault("type", "button")
        # We turn css_id and css_class into id and class
        if css_id:
            kwargs["id"] = css_id
        kwargs["class"] = self.field_classes
        if css_class:
            kwargs["class"] += f" {css_class}"
        self.flat_attrs = flatatt(kwargs)
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
render()
crispy_forms.bootstrap.StrictButton.render (self, form, context, template_pack = TEMPLATE_PACK, ** kwargs)
Definition at line 558 of file bootstrap.py.
    def render(self, form, context, template_pack=TEMPLATE_PACK, **kwargs):
        self.content = Template(str(self.content)).render(context)
        template = self.get_template_name(template_pack)
        context.update({"button": self})
        return render_to_string(template, context.flatten())
References content, crispy_forms.layout.TemplateNameMixin.get_template_name(), and render().
Referenced by pip._vendor.rich.progress.ProgressColumn.__call__(), pip._vendor.rich.layout.Layout.__rich_console__(), pip._vendor.rich.spinner.Spinner.__rich_console__(), pip._vendor.rich.spinner.Spinner.__rich_measure__(), django.forms.widgets.Media.__str__(), django.forms.utils.RenderableFieldMixin.as_field_group(), pip._vendor.rich.console.Console.log(), pip._vendor.rich.console.Console.print(), render(), django.templatetags.i18n.BlockTranslateNode.render(), pip._vendor.rich.console.Console.render(), pip._vendor.rich.console.Console.render_lines(), django.db.migrations.writer.OperationWriter.serialize(), and pip._vendor.rich.console.Console.update_screen_lines().
Member Data Documentation
content
crispy_forms.bootstrap.StrictButton.content = content
Definition at line 543 of file bootstrap.py.
Referenced by pip._vendor.requests.models.Response.__getstate__(), requests.models.Response.__getstate__(), django.http.response.HttpResponse.getvalue(), pip._vendor.requests.models.Response.json(), requests.models.Response.json(), crispy_forms.bootstrap.Alert.render(), render(), django.template.defaulttags.VerbatimNode.render(), django.http.response.HttpResponse.serialize(), django.http.response.HttpResponse.tell(), pip._vendor.requests.models.Response.text(), and requests.models.Response.text().
field_classes
str crispy_forms.bootstrap.StrictButton.field_classes = "btn" static
Definition at line 540 of file bootstrap.py.
flat_attrs
crispy_forms.bootstrap.StrictButton.flat_attrs = flatatt(kwargs)
Definition at line 556 of file bootstrap.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/crispy_forms/bootstrap.py