Read&Watch: isort.exceptions.LiteralSortTypeMismatch Class Reference
isort.exceptions.LiteralSortTypeMismatch Class Reference
Public Member Functions
__init__ (self, type kind, type expected_kind)
Public Member Functions inherited from isort.exceptions.ISortError
__reduce__ (self)
Public Attributes
kind = kind
expected_kind = expected_kind
Detailed Description
Raised when an isort literal sorting comment is used, with a type that doesn't match the
supplied data structure's type.
Definition at line 126 of file exceptions.py.
Constructor & Destructor Documentation
__init__()
isort.exceptions.LiteralSortTypeMismatch.__init__ (self, type kind, type expected_kind)
Definition at line 131 of file exceptions.py.
    def __init__(self, kind: type, expected_kind: type):
        super().__init__(
            f"isort was told to sort a literal of type {expected_kind} but was given "
            f"a literal of type {kind}."
        )
        self.kind = kind
        self.expected_kind = expected_kind
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Data Documentation
expected_kind
isort.exceptions.LiteralSortTypeMismatch.expected_kind = expected_kind
Definition at line 137 of file exceptions.py.
kind
isort.exceptions.LiteralSortTypeMismatch.kind = kind
Definition at line 136 of file exceptions.py.
Referenced by pip._internal.exceptions.DiagnosticPipError.__rich_console__().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/isort/exceptions.py