Read&Watch: astroid.interpreter.objectmodel.PropertyModel Class Reference
astroid.interpreter.objectmodel.PropertyModel Class Reference
Public Member Functions
attr_fget (self)
attr_fset (self)
attr_setter (self)
attr_deleter (self)
attr_getter (self)
Public Member Functions inherited from astroid.interpreter.objectmodel.ObjectModel
__init__ (self)
__repr__ (self)
__call__ (self, instance)
__get__ (self, instance, cls=None)
bool __contains__ (self, name)
list[str] attributes (self)
lookup (self, name)
bases.BoundMethod attr___new__ (self)
bases.BoundMethod attr___init__ (self)
Protected Member Functions
_init_function (self, name)
Additional Inherited Members
Protected Attributes inherited from astroid.interpreter.objectmodel.ObjectModel
_instance = None
Detailed Description
Model for a builtin property.
Definition at line 909 of file objectmodel.py.
Member Function Documentation
_init_function()
astroid.interpreter.objectmodel.PropertyModel._init_function (self, name) protected
Definition at line 912 of file objectmodel.py.
    def _init_function(self, name):
        function = nodes.FunctionDef(
            name=name,
            parent=self._instance,
            lineno=self._instance.lineno,
            col_offset=self._instance.col_offset,
            end_lineno=self._instance.end_lineno,
            end_col_offset=self._instance.end_col_offset,
        )
        args = nodes.Arguments(parent=function, vararg=None, kwarg=None)
        args.postinit(
            args=[],
            defaults=[],
            kwonlyargs=[],
            kw_defaults=[],
            annotations=[],
            posonlyargs=[],
            posonlyargs_annotations=[],
            kwonlyargs_annotations=[],
        )
        function.postinit(args=args, body=[])
        return function
References astroid.interpreter.objectmodel.ObjectModel._instance.
Referenced by attr_deleter(), attr_getter(), and attr_setter().
attr_deleter()
astroid.interpreter.objectmodel.PropertyModel.attr_deleter (self)
Definition at line 1022 of file objectmodel.py.
    def attr_deleter(self):
        return self._init_function("deleter")
References _init_function().
attr_fget()
astroid.interpreter.objectmodel.PropertyModel.attr_fget (self)
Definition at line 938 of file objectmodel.py.
    def attr_fget(self):
        func = self._instance
        class PropertyFuncAccessor(nodes.FunctionDef):
            def infer_call_result(
                self,
                caller: SuccessfulInferenceResult | None,
                context: InferenceContext | None = None,
            ) -> Iterator[InferenceResult]:
                nonlocal func
                if caller and len(caller.args) != 1:
                    raise InferenceError(
                        "fget() needs a single argument", target=self, context=context
                    )
                yield from func.function.infer_call_result(
                    caller=caller, context=context
                )
        property_accessor = PropertyFuncAccessor(
            name="fget",
            parent=self._instance,
            lineno=self._instance.lineno,
            col_offset=self._instance.col_offset,
            end_lineno=self._instance.end_lineno,
            end_col_offset=self._instance.end_col_offset,
        )
        property_accessor.postinit(args=func.args, body=func.body)
        return property_accessor
References astroid.interpreter.objectmodel.ObjectModel._instance.
attr_fset()
astroid.interpreter.objectmodel.PropertyModel.attr_fset (self)
Definition at line 969 of file objectmodel.py.
    def attr_fset(self):
        func = self._instance
        def find_setter(func: Property) -> astroid.FunctionDef | None:
            """
            Given a property, find the corresponding setter function and returns it.
            :param func: property for which the setter has to be found
            :return: the setter function or None
            """
            for target in [
                t for t in func.parent.get_children() if t.name == func.function.name
            ]:
                for dec_name in target.decoratornames():
                    if dec_name.endswith(func.function.name + ".setter"):
                        return target
            return None
        func_setter = find_setter(func)
        if not func_setter:
            raise InferenceError(
                f"Unable to find the setter of property {func.function.name}"
            )
        class PropertyFuncAccessor(nodes.FunctionDef):
            def infer_call_result(
                self,
                caller: SuccessfulInferenceResult | None,
                context: InferenceContext | None = None,
            ) -> Iterator[InferenceResult]:
                nonlocal func_setter
                if caller and len(caller.args) != 2:
                    raise InferenceError(
                        "fset() needs two arguments", target=self, context=context
                    )
                yield from func_setter.infer_call_result(caller=caller, context=context)
        property_accessor = PropertyFuncAccessor(
            name="fset",
            parent=self._instance,
            lineno=self._instance.lineno,
            col_offset=self._instance.col_offset,
            end_lineno=self._instance.end_lineno,
            end_col_offset=self._instance.end_col_offset,
        )
        property_accessor.postinit(args=func_setter.args, body=func_setter.body)
        return property_accessor
References astroid.interpreter.objectmodel.ObjectModel._instance.
attr_getter()
astroid.interpreter.objectmodel.PropertyModel.attr_getter (self)
Definition at line 1026 of file objectmodel.py.
    def attr_getter(self):
        return self._init_function("getter")
References _init_function().
attr_setter()
astroid.interpreter.objectmodel.PropertyModel.attr_setter (self)
Definition at line 1018 of file objectmodel.py.
    def attr_setter(self):
        return self._init_function("setter")
References _init_function().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/astroid/interpreter/objectmodel.py