Read&Watch: django.test.client.RedirectCycleError Class Reference
django.test.client.RedirectCycleError Class Reference
Public Member Functions
__init__ (self, message, last_response)
Public Attributes
last_response = last_response
redirect_chain = last_response.redirect_chain
Detailed Description
The test client has been asked to follow a redirect loop.
Definition at line 59 of file client.py.
Constructor & Destructor Documentation
__init__()
django.test.client.RedirectCycleError.__init__ (self, message, last_response)
Definition at line 62 of file client.py.
    def __init__(self, message, last_response):
        super().__init__(message)
        self.last_response = last_response
        self.redirect_chain = last_response.redirect_chain
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Data Documentation
last_response
django.test.client.RedirectCycleError.last_response = last_response
Definition at line 64 of file client.py.
redirect_chain
django.test.client.RedirectCycleError.redirect_chain = last_response.redirect_chain
Definition at line 65 of file client.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/test/client.py