Read&Watch: django.contrib.auth.forms.ReadOnlyPasswordHashWidget Class Reference
django.contrib.auth.forms.ReadOnlyPasswordHashWidget Class Reference
Public Member Functions
get_context (self, name, value, attrs)
id_for_label (self, id_)
Public Member Functions inherited from django.forms.widgets.Widget
__init__ (self, attrs=None)
__deepcopy__ (self, memo)
is_hidden (self)
subwidgets (self, name, value, attrs=None)
format_value (self, value)
render (self, name, value, attrs=None, renderer=None)
build_attrs (self, base_attrs, extra_attrs=None)
value_from_datadict (self, data, files, name)
value_omitted_from_data (self, data, files, name)
use_required_attribute (self, initial)
Public Member Functions inherited from django.forms.widgets.MediaDefiningClass
__new__ (mcs, name, bases, attrs)
Static Public Attributes
bool read_only = True
Static Public Attributes inherited from django.forms.widgets.Widget
bool needs_multipart_form = False
bool is_localized = False
bool is_required = False
bool supports_microseconds = True
bool use_fieldset = False
Additional Inherited Members
Public Attributes inherited from django.forms.widgets.Widget
dict attrs = {} if attrs is None else attrs.copy()
str input_type = "hidden" if hasattr(self, "input_type") else False
is_hidden
template_name
Protected Member Functions inherited from django.forms.widgets.Widget
_render (self, template_name, context, renderer=None)
Detailed Description
Definition at line 35 of file forms.py.
Member Function Documentation
get_context()
django.contrib.auth.forms.ReadOnlyPasswordHashWidget.get_context (self, name, value, attrs)
Reimplemented from django.forms.widgets.Widget.
Definition at line 39 of file forms.py.
    def get_context(self, name, value, attrs):
        context = super().get_context(name, value, attrs)
        usable_password = value and not value.startswith(UNUSABLE_PASSWORD_PREFIX)
        summary = []
        if usable_password:
            try:
                hasher = identify_hasher(value)
            except ValueError:
                summary.append(
                    {
                        "label": gettext(
                            "Invalid password format or unknown hashing algorithm."
                        )
                    }
                )
            else:
                for key, value_ in hasher.safe_summary(value).items():
                    summary.append({"label": gettext(key), "value": value_})
        else:
            summary.append({"label": gettext("No password set.")})
        context["summary"] = summary
        context["button_label"] = (
            _("Reset password") if usable_password else _("Set password")
        )
        return context
References get_context().
Referenced by get_context(), django.forms.utils.RenderableMixin.render(), django.forms.widgets.Widget.render(), and django.forms.widgets.Widget.subwidgets().
id_for_label()
django.contrib.auth.forms.ReadOnlyPasswordHashWidget.id_for_label (self, id_)
Return the HTML ID attribute of this Widget for use by a <label>, given
the ID of the field. Return an empty string if no ID is available.
This hook is necessary because some widgets have multiple HTML
elements and, thus, multiple IDs. In that case, this method should
return an ID value that corresponds to the first ID in the widget's
tags.
Reimplemented from django.forms.widgets.Widget.
Definition at line 65 of file forms.py.
    def id_for_label(self, id_):
        return None
Referenced by django.forms.widgets.ChoiceWidget.create_option().
Member Data Documentation
read_only
bool django.contrib.auth.forms.ReadOnlyPasswordHashWidget.read_only = True static
Definition at line 37 of file forms.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/auth/forms.py