Read&Watch: django.utils.choices.BaseChoiceIterator Class Reference
django.utils.choices.BaseChoiceIterator Class Reference
Public Member Functions
__eq__ (self, other)
__getitem__ (self, index)
__iter__ (self)
Detailed Description
Base class for lazy iterators for choices.
Definition at line 15 of file choices.py.
Member Function Documentation
__eq__()
django.utils.choices.BaseChoiceIterator.__eq__ (self, other)
Definition at line 18 of file choices.py.
    def __eq__(self, other):
        if isinstance(other, Iterable):
            return all(a == b for a, b in zip_longest(self, other, fillvalue=object()))
        return super().__eq__(other)
References __eq__().
Referenced by __eq__(), pip._vendor.distlib.version.Version.__ge__(), pip._vendor.distlib.version.Version.__gt__(), pip._vendor.distlib.version.Version.__le__(), dotenv.variables.Atom.__ne__(), pip._vendor.distlib.version.Matcher.__ne__(), pip._vendor.distlib.version.Version.__ne__(), pip._vendor.msgpack.ext.Timestamp.__ne__(), pip._vendor.urllib3._collections.HTTPHeaderDict.__ne__(), responses.BaseResponse.__ne__(), and urllib3._collections.HTTPHeaderDict.__ne__().
__getitem__()
django.utils.choices.BaseChoiceIterator.__getitem__ (self, index)
Definition at line 23 of file choices.py.
    def __getitem__(self, index):
        if index < 0:
            # Suboptimally consume whole iterator to handle negative index.
            return list(self)[index]
        try:
            return next(islice(self, index, index + 1))
        except StopIteration:
            raise IndexError("index out of range") from None
__iter__()
django.utils.choices.BaseChoiceIterator.__iter__ (self)
Definition at line 32 of file choices.py.
    def __iter__(self):
        raise NotImplementedError(
            "BaseChoiceIterator subclasses must implement __iter__()."
        )
Referenced by django.db.models.query.BaseIterable._async_generator().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/utils/choices.py