Read&Watch: pip._vendor.resolvelib.resolvers.ResolutionImpossible Class Reference
pip._vendor.resolvelib.resolvers.ResolutionImpossible Class Reference
Public Member Functions
__init__ (self, causes)
Public Attributes
causes = causes
Detailed Description
Definition at line 88 of file resolvers.py.
Constructor & Destructor Documentation
__init__()
pip._vendor.resolvelib.resolvers.ResolutionImpossible.__init__ (self, causes)
Definition at line 89 of file resolvers.py.
    def __init__(self, causes):
        super(ResolutionImpossible, self).__init__(causes)
        # causes is a list of RequirementInformation objects
        self.causes = causes
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Data Documentation
causes
pip._vendor.resolvelib.resolvers.ResolutionImpossible.causes = causes
Definition at line 92 of file resolvers.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/resolvelib/resolvers.py