Read&Watch: astroid.raw_building.InspectBuilder Class Reference
astroid.raw_building.InspectBuilder Class Reference
Public Member Functions
None __init__ (self, AstroidManager|None manager_instance=None)
nodes.Module inspect_build (self, types.ModuleType module, str|None modname=None, str|None path=None)
None object_build (self, nodes.Module|nodes.ClassDef node, types.ModuleType|type obj)
bool imported_member (self, node, member, str name)
Static Public Attributes
bool bootstrapped = False
Protected Attributes
_manager = manager_instance or AstroidManager()
dict _done = {}
types.ModuleType _module = member.__func__
Static Protected Attributes
dict _CONST_PROXY = {}
Detailed Description
class for building nodes from living object
this is actually a really minimal representation, including only Module,
FunctionDef and ClassDef nodes and some others as guessed.
Definition at line 422 of file raw_building.py.
Constructor & Destructor Documentation
__init__()
None astroid.raw_building.InspectBuilder.__init__ (self, AstroidManager | None manager_instance = None)
Definition at line 431 of file raw_building.py.
    def __init__(self, manager_instance: AstroidManager | None = None) -> None:
        self._manager = manager_instance or AstroidManager()
        self._done: dict[types.ModuleType | type, nodes.Module | nodes.ClassDef] = {}
        self._module: types.ModuleType
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
imported_member()
bool astroid.raw_building.InspectBuilder.imported_member (self, node, member, str name)
verify this is not an imported class or handle it
Definition at line 529 of file raw_building.py.
    def imported_member(self, node, member, name: str) -> bool:
        """verify this is not an imported class or handle it"""
        # /!\ some classes like ExtensionClass doesn't have a __module__
        # attribute ! Also, this may trigger an exception on badly built module
        # (see http://www.logilab.org/ticket/57299 for instance)
        try:
            modname = getattr(member, "__module__", None)
        except TypeError:
            modname = None
        if modname is None:
            if name in {"__new__", "__subclasshook__"}:
                # Python 2.5.1 (r251:54863, Sep  1 2010, 22:03:14)
                # >>> print object.__new__.__module__
                # None
                modname = builtins.__name__
            else:
                attach_dummy_node(node, name, member)
                return True
        # On PyPy during bootstrapping we infer _io while _module is
        # builtins. In CPython _io names itself io, see http://bugs.python.org/issue18602
        # Therefore, this basically checks whether we are not in PyPy.
        if modname == "_io" and not self._module.__name__ == "builtins":
            return False
        real_name = {"gtk": "gtk_gtk"}.get(modname, modname)
        if real_name != self._module.__name__:
            # check if it sounds valid and then add an import node, else use a
            # dummy node
            try:
                with (
                    redirect_stderr(io.StringIO()) as stderr,
                    redirect_stdout(io.StringIO()) as stdout,
                ):
                    getattr(sys.modules[modname], name)
                    stderr_value = stderr.getvalue()
                    if stderr_value:
                        logger.error(
                            "Captured stderr while getting %s from %s:\n%s",
                            name,
                            sys.modules[modname],
                            stderr_value,
                        )
                    stdout_value = stdout.getvalue()
                    if stdout_value:
                        logger.info(
                            "Captured stdout while getting %s from %s:\n%s",
                            name,
                            sys.modules[modname],
                            stdout_value,
                        )
            except (KeyError, AttributeError):
                attach_dummy_node(node, name, member)
            else:
                attach_import_node(node, modname, name)
            return True
        return False
# astroid bootstrapping ######################################################
References _module, astroid.raw_building.attach_dummy_node(), and astroid.raw_building.attach_import_node().
Referenced by object_build().
inspect_build()
nodes.Module astroid.raw_building.InspectBuilder.inspect_build (self, types.ModuleType module, str | None modname = None, str | None path = None)
build astroid from a living module (i.e. using inspect)
this is used when there is no python source code available (either
because it's a built-in module or because the .py is not available)
Definition at line 436 of file raw_building.py.
    ) -> nodes.Module:
        """build astroid from a living module (i.e. using inspect)
        this is used when there is no python source code available (either
        because it's a built-in module or because the .py is not available)
        """
        self._module = module
        if modname is None:
            modname = module.__name__
        try:
            node = build_module(modname, module.__doc__)
        except AttributeError:
            # in jython, java modules have no __doc__ (see #109562)
            node = build_module(modname)
        if path is None:
            node.path = node.file = path
        else:
            node.path = [os.path.abspath(path)]
            node.file = node.path[0]
        node.name = modname
        self._manager.cache_module(node)
        node.package = hasattr(module, "__path__")
        self._done = {}
        self.object_build(node, module)
        return node
References _done, _manager, _module, astroid.raw_building.build_module(), and object_build().
Referenced by astroid.builder.AstroidBuilder.module_build().
object_build()
None astroid.raw_building.InspectBuilder.object_build (self, nodes.Module | nodes.ClassDef node, types.ModuleType | type obj)
recursive method which create a partial ast from real objects
(only function, class, and method are handled)
Definition at line 466 of file raw_building.py.
    ) -> None:
        """recursive method which create a partial ast from real objects
        (only function, class, and method are handled)
        """
        if obj in self._done:
            return None
        self._done[obj] = node
        for name in dir(obj):
            # inspect.ismethod() and inspect.isbuiltin() in PyPy return
            # the opposite of what they do in CPython for __class_getitem__.
            pypy__class_getitem__ = IS_PYPY and name == "__class_getitem__"
            try:
                with warnings.catch_warnings():
                    warnings.simplefilter("ignore")
                    member = getattr(obj, name)
            except AttributeError:
                # damned ExtensionClass.Base, I know you're there !
                attach_dummy_node(node, name)
                continue
            if inspect.ismethod(member) and not pypy__class_getitem__:
                member = member.__func__
            if inspect.isfunction(member):
                _build_from_function(node, name, member, self._module)
            elif inspect.isbuiltin(member) or pypy__class_getitem__:
                if self.imported_member(node, member, name):
                    continue
                object_build_methoddescriptor(node, member, name)
            elif inspect.isclass(member):
                if self.imported_member(node, member, name):
                    continue
                if member in self._done:
                    class_node = self._done[member]
                    assert isinstance(class_node, nodes.ClassDef)
                    if class_node not in node.locals.get(name, ()):
                        node.add_local_node(class_node, name)
                else:
                    class_node = object_build_class(node, member, name)
                    # recursion
                    self.object_build(class_node, member)
                if name == "__class__" and class_node.parent is None:
                    class_node.parent = self._done[self._module]
            elif inspect.ismethoddescriptor(member):
                object_build_methoddescriptor(node, member, name)
            elif inspect.isdatadescriptor(member):
                object_build_datadescriptor(node, member, name)
            elif isinstance(member, _CONSTANTS):
                attach_const_node(node, name, member)
            elif inspect.isroutine(member):
                # This should be called for Jython, where some builtin
                # methods aren't caught by isbuiltin branch.
                _build_from_function(node, name, member, self._module)
            elif _safe_has_attribute(member, "__all__"):
                module = build_module(name)
                _attach_local_node(node, module, name)
                # recursion
                self.object_build(module, member)
            else:
                # create an empty node so that the name is actually defined
                attach_dummy_node(node, name, member)
        return None
References astroid.raw_building._attach_local_node(), astroid.raw_building._build_from_function(), _done, _module, astroid.raw_building._safe_has_attribute(), astroid.raw_building.attach_const_node(), astroid.raw_building.attach_dummy_node(), astroid.raw_building.build_module(), imported_member(), object_build(), astroid.raw_building.object_build_class(), astroid.raw_building.object_build_datadescriptor(), and astroid.raw_building.object_build_methoddescriptor().
Referenced by inspect_build(), and object_build().
Member Data Documentation
_CONST_PROXY
dict astroid.raw_building.InspectBuilder._CONST_PROXY = {} static protected
Definition at line 591 of file raw_building.py.
_done
dict astroid.raw_building.InspectBuilder._done = {} protected
Definition at line 433 of file raw_building.py.
Referenced by django.http.multipartparser.BoundaryIter.__next__(), inspect_build(), and object_build().
_manager
astroid.raw_building.InspectBuilder._manager = manager_instance or AstroidManager() protected
Definition at line 432 of file raw_building.py.
Referenced by astroid.builder.AstroidBuilder._data_build(), astroid.builder.AstroidBuilder._post_build(), inspect_build(), and astroid.builder.AstroidBuilder.module_build().
_module
astroid.raw_building.InspectBuilder._module = member.__func__ protected
Definition at line 434 of file raw_building.py.
Referenced by imported_member(), inspect_build(), object_build(), and pylint.utils.file_state.FileState.set_msg_status().
bootstrapped
bool astroid.raw_building.InspectBuilder.bootstrapped = False static
Definition at line 429 of file raw_building.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/astroid/raw_building.py