Read&Watch: django.forms.forms.DeclarativeFieldsMetaclass Class Reference
django.forms.forms.DeclarativeFieldsMetaclass Class Reference
Public Member Functions
__new__ (mcs, name, bases, attrs)
Public Member Functions inherited from django.forms.widgets.MediaDefiningClass
__new__ (mcs, name, bases, attrs)
Detailed Description
Collect Fields declared on the base classes.
Definition at line 21 of file forms.py.
Member Function Documentation
__new__()
django.forms.forms.DeclarativeFieldsMetaclass.__new__ (mcs, name, bases, attrs)
Definition at line 24 of file forms.py.
    def __new__(mcs, name, bases, attrs):
        # Collect fields from current class and remove them from attrs.
        attrs["declared_fields"] = {
            key: attrs.pop(key)
            for key, value in list(attrs.items())
            if isinstance(value, Field)
        }
        new_class = super().__new__(mcs, name, bases, attrs)
        # Walk through the MRO.
        declared_fields = {}
        for base in reversed(new_class.__mro__):
            # Collect fields from base class.
            if hasattr(base, "declared_fields"):
                declared_fields.update(base.declared_fields)
            # Field shadowing.
            for attr, value in base.__dict__.items():
                if value is None and attr in declared_fields:
                    declared_fields.pop(attr)
        new_class.base_fields = declared_fields
        new_class.declared_fields = declared_fields
        return new_class
References __new__().
Referenced by __new__(), django.test.selenium.SeleniumTestCaseBase.__new__(), apscheduler.triggers.combining.BaseCombiningTrigger.__setstate__(), pip._vendor.rich.style.Style._add(), pip._vendor.rich.style.Style.clear_meta_and_links(), yaml.constructor.SafeConstructor.construct_yaml_object(), pip._vendor.rich.style.Style.copy(), pip._vendor.rich.style.Style.from_color(), pip._vendor.rich.json.JSON.from_data(), pip._vendor.rich.style.Style.from_meta(), yaml.constructor.FullConstructor.make_python_instance(), pip._vendor.rich.style.Style.update_link(), and pip._vendor.rich.style.Style.without_color().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/forms/forms.py