Read&Watch: pip._vendor.distlib.wheel.Mounter Class Reference
pip._vendor.distlib.wheel.Mounter Class Reference
Public Member Functions
__init__ (self)
add (self, pathname, extensions)
remove (self, pathname)
find_module (self, fullname, path=None)
load_module (self, fullname)
Public Attributes
dict impure_wheels = {}
dict libs = {}
Detailed Description
Definition at line 133 of file wheel.py.
Constructor & Destructor Documentation
__init__()
pip._vendor.distlib.wheel.Mounter.__init__ (self)
Definition at line 135 of file wheel.py.
    def __init__(self):
        self.impure_wheels = {}
        self.libs = {}
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
add()
pip._vendor.distlib.wheel.Mounter.add (self, pathname, extensions)
Definition at line 139 of file wheel.py.
    def add(self, pathname, extensions):
        self.impure_wheels[pathname] = extensions
        self.libs.update(extensions)
References impure_wheels, and libs.
Referenced by responses.RequestsMock._add_from_file(), pip._vendor.urllib3._collections.HTTPHeaderDict.extend(), urllib3._collections.HTTPHeaderDict.extend(), and responses.RequestsMock.upsert().
find_module()
pip._vendor.distlib.wheel.Mounter.find_module (self, fullname, path = None)
Definition at line 149 of file wheel.py.
    def find_module(self, fullname, path=None):
        if fullname in self.libs:
            result = self
        else:
            result = None
        return result
References libs.
load_module()
pip._vendor.distlib.wheel.Mounter.load_module (self, fullname)
Definition at line 156 of file wheel.py.
    def load_module(self, fullname):
        if fullname in sys.modules:
            result = sys.modules[fullname]
        else:
            if fullname not in self.libs:
                raise ImportError('unable to find extension for %s' % fullname)
            result = _load_dynamic(fullname, self.libs[fullname])
            result.__loader__ = self
            parts = fullname.rsplit('.', 1)
            if len(parts) > 1:
                result.__package__ = parts[0]
        return result
References pip._vendor.distlib.wheel._load_dynamic(), and libs.
Referenced by pip._vendor.urllib3.packages.six._SixMetaPathImporter.create_module(), and six._SixMetaPathImporter.create_module().
remove()
pip._vendor.distlib.wheel.Mounter.remove (self, pathname)
Definition at line 143 of file wheel.py.
    def remove(self, pathname):
        extensions = self.impure_wheels.pop(pathname)
        for k, v in extensions:
            if k in self.libs:
                del self.libs[k]
References impure_wheels, and libs.
Referenced by tomlkit.container.Container.__delitem__(), tomlkit.items.AbstractTable.__delitem__(), and tomlkit.container.Container._replace_at().
Member Data Documentation
impure_wheels
dict pip._vendor.distlib.wheel.Mounter.impure_wheels = {}
Definition at line 136 of file wheel.py.
Referenced by add(), and remove().
libs
dict pip._vendor.distlib.wheel.Mounter.libs = {}
Definition at line 137 of file wheel.py.
Referenced by add(), find_module(), load_module(), and remove().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/distlib/wheel.py