Read&Watch: pip._internal.commands.configuration.ConfigurationCommand Class Reference
pip._internal.commands.configuration.ConfigurationCommand Class Reference
Public Member Functions
None add_options (self)
int run (self, Values options, List[str] args)
None list_values (self, Values options, List[str] args)
None get_name (self, Values options, List[str] args)
None set_name_value (self, Values options, List[str] args)
None unset_name (self, Values options, List[str] args)
None list_config_values (self, Values options, List[str] args)
None print_config_file_values (self, Kind variant)
None print_env_var_values (self)
None open_in_editor (self, Values options, List[str] args)
Public Member Functions inherited from pip._internal.cli.base_command.Command
None __init__ (self, str name, str summary, bool isolated=False)
None handle_pip_version_check (self, Values options)
Tuple[Values, List[str]] parse_args (self, List[str] args)
int main (self, List[str] args)
Public Member Functions inherited from pip._internal.cli.command_context.CommandContextMixIn
None __init__ (self)
Generator[None, None, None] main_context (self)
_T enter_context (self, ContextManager[_T] context_provider)
Public Attributes
configuration
Public Attributes inherited from pip._internal.cli.base_command.Command
name = name
summary = summary
parser
Optional[TempDirRegistry] tempdir_registry = None
cmd_opts = optparse.OptionGroup(self.parser, optgroup_name)
verbosity = options.verbose - options.quiet
Protected Member Functions
Optional[Kind] _determine_file (self, Values options, bool need_value)
Any _get_n_args (self, List[str] args, str example, int n)
None _save_configuration (self)
str _determine_editor (self, Values options)
Protected Member Functions inherited from pip._internal.cli.base_command.Command
int _run_wrapper (self, int level_number, Values options, List[str] args)
int _main (self, List[str] args)
Additional Inherited Members
Static Public Attributes inherited from pip._internal.cli.base_command.Command
str usage = ""
bool ignore_require_venv = False
Protected Attributes inherited from pip._internal.cli.command_context.CommandContextMixIn
bool _in_main_context = False
_main_context = ExitStack()
Detailed Description
Manage local and global configuration.
Subcommands:
- list: List the active configuration (or from the file specified)
- edit: Edit the configuration file in an editor
- get: Get the value associated with command.option
- set: Set the command.option=value
- unset: Unset the value associated with command.option
- debug: List the configuration files and values defined under them
Configuration keys should be dot separated command and option name,
with the special prefix "global" affecting any command. For example,
"pip config set global.index-url https://example.org/" would configure
the index url for all commands, but "pip config set download.timeout 10"
would configure a 10 second timeout only for "pip download" commands.
If none of --user, --global and --site are passed, a virtual
environment configuration file is used if one is active and the file
exists. Otherwise, all modifications happen to the user file by
default.
Definition at line 22 of file configuration.py.
Member Function Documentation
_determine_editor()
str pip._internal.commands.configuration.ConfigurationCommand._determine_editor (self, Values options) protected
Definition at line 272 of file configuration.py.
    def _determine_editor(self, options: Values) -> str:
        if options.editor is not None:
            return options.editor
        elif "VISUAL" in os.environ:
            return os.environ["VISUAL"]
        elif "EDITOR" in os.environ:
            return os.environ["EDITOR"]
        else:
            raise PipError("Could not determine editor to use.")
Referenced by open_in_editor().
_determine_file()
Optional[Kind] pip._internal.commands.configuration.ConfigurationCommand._determine_file (self, Values options, bool need_value) protected
Definition at line 141 of file configuration.py.
    def _determine_file(self, options: Values, need_value: bool) -> Optional[Kind]:
        file_options = [
            key
            for key, value in (
                (kinds.USER, options.user_file),
                (kinds.GLOBAL, options.global_file),
                (kinds.SITE, options.site_file),
            )
            if value
        ]
        if not file_options:
            if not need_value:
                return None
            # Default to user, unless there's a site file.
            elif any(
                os.path.exists(site_config_file)
                for site_config_file in get_configuration_files()[kinds.SITE]
            ):
                return kinds.SITE
            else:
                return kinds.USER
        elif len(file_options) == 1:
            return file_options[0]
        raise PipError(
            "Need exactly one file to operate upon "
            "(--user, --site, --global) to perform."
        )
Referenced by run().
_get_n_args()
Any pip._internal.commands.configuration.ConfigurationCommand._get_n_args (self, List[str] args, str example, int n) protected
Helper to make sure the command got the right number of arguments
Definition at line 247 of file configuration.py.
    def _get_n_args(self, args: List[str], example: str, n: int) -> Any:
        """Helper to make sure the command got the right number of arguments"""
        if len(args) != n:
            msg = (
                f"Got unexpected number of arguments, expected {n}. "
                f'(example: "{get_prog()} config {example}")'
            )
            raise PipError(msg)
        if n == 1:
            return args[0]
        else:
            return args
Referenced by get_name(), list_config_values(), list_values(), set_name_value(), and unset_name().
_save_configuration()
None pip._internal.commands.configuration.ConfigurationCommand._save_configuration (self) protected
Definition at line 261 of file configuration.py.
    def _save_configuration(self) -> None:
        # We successfully ran a modifying command. Need to save the
        # configuration.
        try:
            self.configuration.save()
        except Exception:
            logger.exception(
                "Unable to save configuration. Please report this as a bug."
            )
            raise PipError("Internal Error.")
References configuration.
Referenced by set_name_value(), and unset_name().
add_options()
None pip._internal.commands.configuration.ConfigurationCommand.add_options (self)
Reimplemented from pip._internal.cli.base_command.Command.
Definition at line 58 of file configuration.py.
    def add_options(self) -> None:
        self.cmd_opts.add_option(
            "--editor",
            dest="editor",
            action="store",
            default=None,
            help=(
                "Editor to use to edit the file. Uses VISUAL or EDITOR "
                "environment variables if not provided."
            ),
        )
        self.cmd_opts.add_option(
            "--global",
            dest="global_file",
            action="store_true",
            default=False,
            help="Use the system-wide configuration file only",
        )
        self.cmd_opts.add_option(
            "--user",
            dest="user_file",
            action="store_true",
            default=False,
            help="Use the user configuration file only",
        )
        self.cmd_opts.add_option(
            "--site",
            dest="site_file",
            action="store_true",
            default=False,
            help="Use the current environment configuration file only",
        )
        self.parser.insert_option_group(0, self.cmd_opts)
References pip._internal.cli.base_command.Command.cmd_opts.
get_name()
None pip._internal.commands.configuration.ConfigurationCommand.get_name (self, Values options, List[str] args)
Definition at line 177 of file configuration.py.
    def get_name(self, options: Values, args: List[str]) -> None:
        key = self._get_n_args(args, "get [name]", n=1)
        value = self.configuration.get_value(key)
        write_output("%s", value)
References _get_n_args(), and configuration.
Referenced by run().
list_config_values()
None pip._internal.commands.configuration.ConfigurationCommand.list_config_values (self, Values options, List[str] args)
List config key-value pairs across different config files
Definition at line 195 of file configuration.py.
    def list_config_values(self, options: Values, args: List[str]) -> None:
        """List config key-value pairs across different config files"""
        self._get_n_args(args, "debug", n=0)
        self.print_env_var_values()
        # Iterate over config files and print if they exist, and the
        # key-value pairs present in them if they do
        for variant, files in sorted(self.configuration.iter_config_files()):
            write_output("%s:", variant)
            for fname in files:
                with indent_log():
                    file_exists = os.path.exists(fname)
                    write_output("%s, exists: %r", fname, file_exists)
                    if file_exists:
                        self.print_config_file_values(variant)
References _get_n_args(), configuration, print_config_file_values(), and print_env_var_values().
Referenced by run().
list_values()
None pip._internal.commands.configuration.ConfigurationCommand.list_values (self, Values options, List[str] args)
Definition at line 171 of file configuration.py.
    def list_values(self, options: Values, args: List[str]) -> None:
        self._get_n_args(args, "list", n=0)
        for key, value in sorted(self.configuration.items()):
            write_output("%s=%r", key, value)
References _get_n_args(), and configuration.
Referenced by run().
open_in_editor()
None pip._internal.commands.configuration.ConfigurationCommand.open_in_editor (self, Values options, List[str] args)
Definition at line 225 of file configuration.py.
    def open_in_editor(self, options: Values, args: List[str]) -> None:
        editor = self._determine_editor(options)
        fname = self.configuration.get_file_to_edit()
        if fname is None:
            raise PipError("Could not determine appropriate file.")
        elif '"' in fname:
            # This shouldn't happen, unless we see a username like that.
            # If that happens, we'd appreciate a pull request fixing this.
            raise PipError(
                f'Can not open an editor for a file name containing "\n{fname}'
            )
        try:
            subprocess.check_call(f'{editor} "{fname}"', shell=True)
        except FileNotFoundError as e:
            if not e.filename:
                e.filename = editor
            raise
        except subprocess.CalledProcessError as e:
            raise PipError(f"Editor Subprocess exited with exit code {e.returncode}")
References _determine_editor(), and configuration.
Referenced by run().
print_config_file_values()
None pip._internal.commands.configuration.ConfigurationCommand.print_config_file_values (self, Kind variant)
Get key-value pairs from the file of a variant
Definition at line 211 of file configuration.py.
    def print_config_file_values(self, variant: Kind) -> None:
        """Get key-value pairs from the file of a variant"""
        for name, value in self.configuration.get_values_in_config(variant).items():
            with indent_log():
                write_output("%s: %s", name, value)
References configuration.
Referenced by list_config_values().
print_env_var_values()
None pip._internal.commands.configuration.ConfigurationCommand.print_env_var_values (self)
Get key-values pairs present as environment variables
Definition at line 217 of file configuration.py.
    def print_env_var_values(self) -> None:
        """Get key-values pairs present as environment variables"""
        write_output("%s:", "env_var")
        with indent_log():
            for key, value in sorted(self.configuration.get_environ_vars()):
                env_var = f"PIP_{key.upper()}"
                write_output("%s=%r", env_var, value)
References configuration.
Referenced by list_config_values().
run()
int pip._internal.commands.configuration.ConfigurationCommand.run (self, Values options, List[str] args)
Reimplemented from pip._internal.cli.base_command.Command.
Definition at line 96 of file configuration.py.
    def run(self, options: Values, args: List[str]) -> int:
        handlers = {
            "list": self.list_values,
            "edit": self.open_in_editor,
            "get": self.get_name,
            "set": self.set_name_value,
            "unset": self.unset_name,
            "debug": self.list_config_values,
        }
        # Determine action
        if not args or args[0] not in handlers:
            logger.error(
                "Need an action (%s) to perform.",
                ", ".join(sorted(handlers)),
            )
            return ERROR
        action = args[0]
        # Determine which configuration files are to be loaded
        #    Depends on whether the command is modifying.
        try:
            load_only = self._determine_file(
                options, need_value=(action in ["get", "set", "unset", "edit"])
            )
        except PipError as e:
            logger.error(e.args[0])
            return ERROR
        # Load a new configuration
        self.configuration = Configuration(
            isolated=options.isolated_mode, load_only=load_only
        )
        self.configuration.load()
        # Error handling happens here, not in the action-handlers.
        try:
            handlers[action](options, args[1:])
        except PipError as e:
            logger.error(e.args[0])
            return ERROR
        return SUCCESS
References _determine_file(), get_name(), list_config_values(), list_values(), open_in_editor(), set_name_value(), and unset_name().
Referenced by pylint.pyreverse.main.Run.__init__().
set_name_value()
None pip._internal.commands.configuration.ConfigurationCommand.set_name_value (self, Values options, List[str] args)
Definition at line 183 of file configuration.py.
    def set_name_value(self, options: Values, args: List[str]) -> None:
        key, value = self._get_n_args(args, "set [name] [value]", n=2)
        self.configuration.set_value(key, value)
        self._save_configuration()
References _get_n_args(), _save_configuration(), and configuration.
Referenced by run().
unset_name()
None pip._internal.commands.configuration.ConfigurationCommand.unset_name (self, Values options, List[str] args)
Definition at line 189 of file configuration.py.
    def unset_name(self, options: Values, args: List[str]) -> None:
        key = self._get_n_args(args, "unset [name]", n=1)
        self.configuration.unset_value(key)
        self._save_configuration()
References _get_n_args(), _save_configuration(), and configuration.
Referenced by run().
Member Data Documentation
configuration
pip._internal.commands.configuration.ConfigurationCommand.configuration
Initial value:
=  Configuration(
            isolated=options.isolated_mode, load_only=load_only
        )
Definition at line 127 of file configuration.py.
Referenced by _save_configuration(), get_name(), list_config_values(), list_values(), open_in_editor(), print_config_file_values(), print_env_var_values(), set_name_value(), and unset_name().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_internal/commands/configuration.py