Read&Watch: pip._internal.cli.parser.PrettyHelpFormatter Class Reference
pip._internal.cli.parser.PrettyHelpFormatter Class Reference
Public Member Functions
None __init__ (self, *Any args, **Any kwargs)
str format_option_strings (self, optparse.Option option)
str format_heading (self, str heading)
str format_usage (self, str usage)
str format_description (self, Optional[str] description)
str format_epilog (self, Optional[str] epilog)
str indent_lines (self, str text, str indent)
Public Attributes
parser
Protected Member Functions
str _format_option_strings (self, optparse.Option option, str mvarfmt=" <{}>", str optsep=", ")
Detailed Description
A prettier/less verbose help formatter for optparse.
Definition at line 18 of file parser.py.
Constructor & Destructor Documentation
__init__()
None pip._internal.cli.parser.PrettyHelpFormatter.__init__ (self, *Any args, **Any kwargs)
Definition at line 21 of file parser.py.
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        # help position must be aligned with __init__.parseopts.description
        kwargs["max_help_position"] = 30
        kwargs["indent_increment"] = 1
        kwargs["width"] = shutil.get_terminal_size()[0] - 2
        super().__init__(*args, **kwargs)
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Function Documentation
_format_option_strings()
str pip._internal.cli.parser.PrettyHelpFormatter._format_option_strings (self, optparse.Option option, str mvarfmt = " <{}>", str optsep = ", ") protected
Return a comma-separated list of option strings and metavars.
:param option:  tuple of (short opt, long opt), e.g: ('-f', '--format')
:param mvarfmt: metavar format string
:param optsep:  separator
Definition at line 31 of file parser.py.
    ) -> str:
        """
        Return a comma-separated list of option strings and metavars.
        :param option:  tuple of (short opt, long opt), e.g: ('-f', '--format')
        :param mvarfmt: metavar format string
        :param optsep:  separator
        """
        opts = []
        if option._short_opts:
            opts.append(option._short_opts[0])
        if option._long_opts:
            opts.append(option._long_opts[0])
        if len(opts) > 1:
            opts.insert(1, optsep)
        if option.takes_value():
            assert option.dest is not None
            metavar = option.metavar or option.dest.lower()
            opts.append(mvarfmt.format(metavar.lower()))
        return "".join(opts)
Referenced by format_option_strings().
format_description()
str pip._internal.cli.parser.PrettyHelpFormatter.format_description (self, Optional[str] description)
Definition at line 70 of file parser.py.
    def format_description(self, description: Optional[str]) -> str:
        # leave full control over description to us
        if description:
            if hasattr(self.parser, "main"):
                label = "Commands"
            else:
                label = "Description"
            # some doc strings have initial newlines, some don't
            description = description.lstrip("\n")
            # some doc strings have final newlines and spaces, some don't
            description = description.rstrip()
            # dedent, then reindent
            description = self.indent_lines(textwrap.dedent(description), "  ")
            description = f"{label}:\n{description}\n"
            return description
        else:
            return ""
format_epilog()
str pip._internal.cli.parser.PrettyHelpFormatter.format_epilog (self, Optional[str] epilog)
Definition at line 88 of file parser.py.
    def format_epilog(self, epilog: Optional[str]) -> str:
        # leave full control over epilog to us
        if epilog:
            return epilog
        else:
            return ""
format_heading()
str pip._internal.cli.parser.PrettyHelpFormatter.format_heading (self, str heading)
Definition at line 57 of file parser.py.
    def format_heading(self, heading: str) -> str:
        if heading == "Options":
            return ""
        return heading + ":\n"
format_option_strings()
str pip._internal.cli.parser.PrettyHelpFormatter.format_option_strings (self, optparse.Option option)
Definition at line 28 of file parser.py.
    def format_option_strings(self, option: optparse.Option) -> str:
        return self._format_option_strings(option)
References _format_option_strings().
format_usage()
str pip._internal.cli.parser.PrettyHelpFormatter.format_usage (self, str usage)
Ensure there is only one newline between usage and the first heading
if there is no description.
Definition at line 62 of file parser.py.
    def format_usage(self, usage: str) -> str:
        """
        Ensure there is only one newline between usage and the first heading
        if there is no description.
        """
        msg = "\nUsage: {}\n".format(self.indent_lines(textwrap.dedent(usage), "  "))
        return msg
References indent_lines().
indent_lines()
str pip._internal.cli.parser.PrettyHelpFormatter.indent_lines (self, str text, str indent)
Definition at line 95 of file parser.py.
    def indent_lines(self, text: str, indent: str) -> str:
        new_lines = [indent + line for line in text.split("\n")]
        return "\n".join(new_lines)
Referenced by format_usage().
Member Data Documentation
parser
pip._internal.cli.parser.PrettyHelpFormatter.parser
Definition at line 73 of file parser.py.
Referenced by pip._internal.cli.parser.UpdatingDefaultsHelpFormatter.expand_default().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_internal/cli/parser.py