Read&Watch: django.db.backends.sqlite3.base.SQLiteCursorWrapper Class Reference
django.db.backends.sqlite3.base.SQLiteCursorWrapper Class Reference
Public Member Functions
execute (self, query, params=None)
executemany (self, query, param_list)
convert_query (self, query, *, param_names=None)
Detailed Description
Django uses the "format" and "pyformat" styles, but Python's sqlite3 module
supports neither of these styles.
This wrapper performs the following conversions:
- "format" style to "qmark" style
- "pyformat" style to "named" style
In both cases, if you want to use a literal "%s", you'll need to use "%%s".
Definition at line 335 of file base.py.
Member Function Documentation
convert_query()
django.db.backends.sqlite3.base.SQLiteCursorWrapper.convert_query (self, query, * , param_names = None)
Definition at line 367 of file base.py.
    def convert_query(self, query, *, param_names=None):
        if param_names is None:
            # Convert from "format" style to "qmark" style.
            return FORMAT_QMARK_REGEX.sub("?", query).replace("%%", "%")
        else:
            # Convert from "pyformat" style to "named" style.
            return query % {name: f":{name}" for name in param_names}
Referenced by execute(), and executemany().
execute()
django.db.backends.sqlite3.base.SQLiteCursorWrapper.execute (self, query, params = None)
Definition at line 348 of file base.py.
    def execute(self, query, params=None):
        if params is None:
            return super().execute(query)
        # Extract names if params is a mapping, i.e. "pyformat" style is used.
        param_names = list(params) if isinstance(params, Mapping) else None
        query = self.convert_query(query, param_names=param_names)
        return super().execute(query, params)
References convert_query(), and execute().
Referenced by django.db.backends.postgresql.base.CursorMixin.callproc(), and execute().
executemany()
django.db.backends.sqlite3.base.SQLiteCursorWrapper.executemany (self, query, param_list)
Definition at line 356 of file base.py.
    def executemany(self, query, param_list):
        # Extract names if params is a mapping, i.e. "pyformat" style is used.
        # Peek carefully as a generator can be passed instead of a list/tuple.
        peekable, param_list = tee(iter(param_list))
        if (params := next(peekable, None)) and isinstance(params, Mapping):
            param_names = list(params)
        else:
            param_names = None
        query = self.convert_query(query, param_names=param_names)
        return super().executemany(query, param_list)
References convert_query(), and executemany().
Referenced by executemany().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/db/backends/sqlite3/base.py