Read&Watch: pylint.checkers.base.basic_error_checker.BasicErrorChecker Class Reference
pylint.checkers.base.basic_error_checker.BasicErrorChecker Class Reference
Public Member Functions
None open (self)
None visit_classdef (self, nodes.ClassDef node)
None visit_assign (self, nodes.Assign node)
None visit_starred (self, nodes.Starred node)
None visit_functiondef (self, nodes.FunctionDef node)
None visit_return (self, nodes.Return node)
None visit_yield (self, nodes.Yield node)
None visit_yieldfrom (self, nodes.YieldFrom node)
None visit_continue (self, nodes.Continue node)
None visit_break (self, nodes.Break node)
None visit_for (self, nodes.For node)
None visit_while (self, nodes.While node)
None visit_unaryop (self, nodes.UnaryOp node)
None visit_nonlocal (self, nodes.Nonlocal node)
None visit_call (self, nodes.Call node)
Public Member Functions inherited from pylint.checkers.base_checker.BaseChecker
None __init__ (self, PyLinter linter)
bool __gt__ (self, Any other)
bool __eq__ (self, object other)
int __hash__ (self)
str __repr__ (self)
str __str__ (self)
str get_full_documentation (self, dict[str, MessageDefinitionTuple] msgs, Iterable[tuple[str, OptionDict, Any]] options, Sequence[tuple[str, str, ReportsCallable]] reports, str|None doc=None, str|None module=None, bool show_options=True)
None add_message (self, str msgid, int|None line=None, nodes.NodeNG|None node=None, Any args=None, Confidence|None confidence=None, int|None col_offset=None, int|None end_lineno=None, int|None end_col_offset=None)
None check_consistency (self)
MessageDefinition create_message_definition_from_tuple (self, str msgid, MessageDefinitionTuple msg_tuple)
list[MessageDefinition] messages (self)
None close (self)
Any get_map_data (self)
None reduce_map_data (self, PyLinter linter, list[Any] data)
Public Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
None __init__ (self, _ArgumentsManager arguments_manager)
Static Public Attributes
None visit_asyncfunctiondef = visit_functiondef
Static Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
str name = ""
dict msgs = {}
tuple reports = ()
bool enabled = True
Static Public Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
tuple options = ()
dict option_groups_descs = {}
Protected Member Functions
bool _too_many_starred_for_tuple (self, nodes.Tuple assign_tuple)
None _check_name_used_prior_global (self, nodes.FunctionDef node)
None _check_nonlocal_and_global (self, nodes.FunctionDef node)
None _check_nonlocal_without_binding (self, nodes.Nonlocal node, str name)
None _check_inferred_class_is_abstract (self, InferenceResult inferred, nodes.Call node)
None _check_yield_outside_func (self, nodes.Yield node)
None _check_else_on_loop (self, nodes.For|nodes.While node)
None _check_in_loop (self, nodes.Continue|nodes.Break node, str node_name)
None _check_redefinition (self, str redeftype, nodes.Call|nodes.FunctionDef node)
Protected Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
Any _option_value (self, str opt)
Iterator[ tuple[str, list[tuple[str, OptionDict, Any]]]|tuple[None, dict[str, list[tuple[str, OptionDict, Any]]]]] _options_by_section (self)
Iterator[tuple[str, OptionDict, Any]] _options_and_values (self, Options|None options=None)
Protected Attributes
tuple _py38_plus = (3, 8)
Protected Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
_arguments_manager = arguments_manager
Additional Inherited Members
Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
linter = linter
messages
Detailed Description
Definition at line 98 of file basic_error_checker.py.
Member Function Documentation
_check_else_on_loop()
None pylint.checkers.base.basic_error_checker.BasicErrorChecker._check_else_on_loop (self, nodes.For | nodes.While node) protected
Check that any loop with an else clause has a break statement.
Definition at line 471 of file basic_error_checker.py.
    def _check_else_on_loop(self, node: nodes.For | nodes.While) -> None:
        """Check that any loop with an else clause has a break statement."""
        if node.orelse and not _loop_exits_early(node):
            self.add_message(
                "useless-else-on-loop",
                node=node,
                # This is not optimal, but the line previous
                # to the first statement in the else clause
                # will usually be the one that contains the else:.
                line=node.orelse[0].lineno - 1,
            )
References pylint.checkers.base.basic_error_checker._loop_exits_early(), and pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_for(), and visit_while().
_check_in_loop()
None pylint.checkers.base.basic_error_checker.BasicErrorChecker._check_in_loop (self, nodes.Continue | nodes.Break node, str node_name) protected
Check that a node is inside a for or while loop.
Definition at line 483 of file basic_error_checker.py.
    ) -> None:
        """Check that a node is inside a for or while loop."""
        for parent in node.node_ancestors():
            if isinstance(parent, (nodes.For, nodes.While)):
                if node not in parent.orelse:
                    return
            if isinstance(parent, (nodes.ClassDef, nodes.FunctionDef)):
                break
            if (
                isinstance(parent, nodes.Try)
                and node in parent.finalbody
                and isinstance(node, nodes.Continue)
                and not self._py38_plus
            ):
                self.add_message("continue-in-finally", node=node)
        self.add_message("not-in-loop", node=node, args=node_name)
References pylint.checkers.base.basic_checker.BasicChecker._py38_plus, _py38_plus, and pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_break(), and visit_continue().
_check_inferred_class_is_abstract()
None pylint.checkers.base.basic_error_checker.BasicErrorChecker._check_inferred_class_is_abstract (self, InferenceResult inferred, nodes.Call node) protected
Definition at line 428 of file basic_error_checker.py.
    ) -> None:
        if not isinstance(inferred, nodes.ClassDef):
            return
        klass = utils.node_frame_class(node)
        if klass is inferred:
            # Don't emit the warning if the class is instantiated
            # in its own body or if the call is not an instance
            # creation. If the class is instantiated into its own
            # body, we're expecting that it knows what it is doing.
            return
        # __init__ was called
        abstract_methods = _has_abstract_methods(inferred)
        if not abstract_methods:
            return
        metaclass = inferred.metaclass()
        if metaclass is None:
            # Python 3.4 has `abc.ABC`, which won't be detected
            # by ClassNode.metaclass()
            for ancestor in inferred.ancestors():
                if ancestor.qname() == "abc.ABC":
                    self.add_message(
                        "abstract-class-instantiated", args=(inferred.name,), node=node
                    )
                    break
            return
        if metaclass.qname() in ABC_METACLASSES:
            self.add_message(
                "abstract-class-instantiated", args=(inferred.name,), node=node
            )
References pylint.checkers.base.basic_error_checker._has_abstract_methods(), and pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_call().
_check_name_used_prior_global()
None pylint.checkers.base.basic_error_checker.BasicErrorChecker._check_name_used_prior_global (self, nodes.FunctionDef node) protected
Definition at line 299 of file basic_error_checker.py.
    def _check_name_used_prior_global(self, node: nodes.FunctionDef) -> None:
        scope_globals = {
            name: child
            for child in node.nodes_of_class(nodes.Global)
            for name in child.names
            if child.scope() is node
        }
        if not scope_globals:
            return
        for node_name in node.nodes_of_class(nodes.Name):
            if node_name.scope() is not node:
                continue
            name = node_name.name
            corresponding_global = scope_globals.get(name)
            if not corresponding_global:
                continue
            global_lineno = corresponding_global.fromlineno
            if global_lineno and global_lineno > node_name.fromlineno:
                self.add_message(
                    "used-prior-global-declaration", node=node_name, args=(name,)
                )
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_functiondef().
_check_nonlocal_and_global()
None pylint.checkers.base.basic_error_checker.BasicErrorChecker._check_nonlocal_and_global (self, nodes.FunctionDef node) protected
Check that a name is both nonlocal and global.
Definition at line 325 of file basic_error_checker.py.
    def _check_nonlocal_and_global(self, node: nodes.FunctionDef) -> None:
        """Check that a name is both nonlocal and global."""
        def same_scope(current: nodes.Global | nodes.Nonlocal) -> bool:
            return current.scope() is node
        from_iter = itertools.chain.from_iterable
        nonlocals = set(
            from_iter(
                child.names
                for child in node.nodes_of_class(nodes.Nonlocal)
                if same_scope(child)
            )
        )
        if not nonlocals:
            return
        global_vars = set(
            from_iter(
                child.names
                for child in node.nodes_of_class(nodes.Global)
                if same_scope(child)
            )
        )
        for name in nonlocals.intersection(global_vars):
            self.add_message("nonlocal-and-global", args=(name,), node=node)
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_functiondef().
_check_nonlocal_without_binding()
None pylint.checkers.base.basic_error_checker.BasicErrorChecker._check_nonlocal_without_binding (self, nodes.Nonlocal node, str name) protected
Definition at line 393 of file basic_error_checker.py.
    def _check_nonlocal_without_binding(self, node: nodes.Nonlocal, name: str) -> None:
        current_scope = node.scope()
        while current_scope.parent is not None:
            if not isinstance(current_scope, (nodes.ClassDef, nodes.FunctionDef)):
                self.add_message("nonlocal-without-binding", args=(name,), node=node)
                return
            # Search for `name` in the parent scope if:
            #  `current_scope` is the same scope in which the `nonlocal` name is declared
            #  or `name` is not in `current_scope.locals`.
            if current_scope is node.scope() or name not in current_scope.locals:
                current_scope = current_scope.parent.scope()
                continue
            # Okay, found it.
            return
        if not isinstance(current_scope, nodes.FunctionDef):
            self.add_message(
                "nonlocal-without-binding", args=(name,), node=node, confidence=HIGH
            )
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_nonlocal().
_check_redefinition()
None pylint.checkers.base.basic_error_checker.BasicErrorChecker._check_redefinition (self, str redeftype, nodes.Call | nodes.FunctionDef node) protected
Check for redefinition of a function / method / class name.
Definition at line 504 of file basic_error_checker.py.
    ) -> None:
        """Check for redefinition of a function / method / class name."""
        parent_frame = node.parent.frame()
        # Ignore function stubs created for type information
        redefinitions = [
            i
            for i in parent_frame.locals[node.name]
            if not (isinstance(i.parent, nodes.AnnAssign) and i.parent.simple)
        ]
        defined_self = next(
            (local for local in redefinitions if not utils.is_overload_stub(local)),
            node,
        )
        if defined_self is not node and not astroid.are_exclusive(node, defined_self):
            # Additional checks for methods which are not considered
            # redefined, since they are already part of the base API.
            if (
                isinstance(parent_frame, nodes.ClassDef)
                and node.name in REDEFINABLE_METHODS
            ):
                return
            # Skip typing.overload() functions.
            if utils.is_overload_stub(node):
                return
            # Exempt functions redefined on a condition.
            if isinstance(node.parent, nodes.If):
                # Exempt "if not <func>" cases
                if (
                    isinstance(node.parent.test, nodes.UnaryOp)
                    and node.parent.test.op == "not"
                    and isinstance(node.parent.test.operand, nodes.Name)
                    and node.parent.test.operand.name == node.name
                ):
                    return
                # Exempt "if <func> is not None" cases
                # pylint: disable=too-many-boolean-expressions
                if (
                    isinstance(node.parent.test, nodes.Compare)
                    and isinstance(node.parent.test.left, nodes.Name)
                    and node.parent.test.left.name == node.name
                    and node.parent.test.ops[0][0] == "is"
                    and isinstance(node.parent.test.ops[0][1], nodes.Const)
                    and node.parent.test.ops[0][1].value is None
                ):
                    return
            # Check if we have forward references for this node.
            try:
                redefinition_index = redefinitions.index(node)
            except ValueError:
                pass
            else:
                for redefinition in redefinitions[:redefinition_index]:
                    inferred = utils.safe_infer(redefinition)
                    if (
                        inferred
                        and isinstance(inferred, astroid.Instance)
                        and inferred.qname() == TYPING_FORWARD_REF_QNAME
                    ):
                        return
            dummy_variables_rgx = self.linter.config.dummy_variables_rgx
            if dummy_variables_rgx and dummy_variables_rgx.match(node.name):
                return
            self.add_message(
                "function-redefined",
                node=node,
                args=(redeftype, defined_self.fromlineno),
            )
References pylint.checkers.base_checker.BaseChecker.add_message(), and pylint.checkers.base_checker.BaseChecker.linter.
Referenced by visit_classdef(), and visit_functiondef().
_check_yield_outside_func()
None pylint.checkers.base.basic_error_checker.BasicErrorChecker._check_yield_outside_func (self, nodes.Yield node) protected
Definition at line 467 of file basic_error_checker.py.
    def _check_yield_outside_func(self, node: nodes.Yield) -> None:
        if not isinstance(node.frame(), (nodes.FunctionDef, nodes.Lambda)):
            self.add_message("yield-outside-function", node=node)
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by visit_yield(), and visit_yieldfrom().
_too_many_starred_for_tuple()
bool pylint.checkers.base.basic_error_checker.BasicErrorChecker._too_many_starred_for_tuple (self, nodes.Tuple assign_tuple) protected
Definition at line 214 of file basic_error_checker.py.
    def _too_many_starred_for_tuple(self, assign_tuple: nodes.Tuple) -> bool:
        starred_count = 0
        for elem in assign_tuple.itered():
            if isinstance(elem, nodes.Tuple):
                return self._too_many_starred_for_tuple(elem)
            if isinstance(elem, nodes.Starred):
                starred_count += 1
        return starred_count > 1
References _too_many_starred_for_tuple().
Referenced by _too_many_starred_for_tuple(), and visit_assign().
open()
None pylint.checkers.base.basic_error_checker.BasicErrorChecker.open (self)
Called before visiting project (i.e. set of modules).
Reimplemented from pylint.checkers.base_checker.BaseChecker.
Definition at line 206 of file basic_error_checker.py.
    def open(self) -> None:
        py_version = self.linter.config.py_version
        self._py38_plus = py_version >= (3, 8)
References pylint.checkers.base_checker.BaseChecker.linter.
Referenced by django.contrib.staticfiles.storage.HashedFilesMixin.hashed_name().
visit_assign()
None pylint.checkers.base.basic_error_checker.BasicErrorChecker.visit_assign (self, nodes.Assign node)
Definition at line 226 of file basic_error_checker.py.
    def visit_assign(self, node: nodes.Assign) -> None:
        # Check *a, *b = ...
        assign_target = node.targets[0]
        # Check *a = b
        if isinstance(node.targets[0], nodes.Starred):
            self.add_message("invalid-star-assignment-target", node=node)
        if not isinstance(assign_target, nodes.Tuple):
            return
        if self._too_many_starred_for_tuple(assign_target):
            self.add_message("too-many-star-expressions", node=node)
References _too_many_starred_for_tuple(), and pylint.checkers.base_checker.BaseChecker.add_message().
visit_break()
None pylint.checkers.base.basic_error_checker.BasicErrorChecker.visit_break (self, nodes.Break node)
Definition at line 371 of file basic_error_checker.py.
    def visit_break(self, node: nodes.Break) -> None:
        self._check_in_loop(node, "break")
References _check_in_loop().
visit_call()
None pylint.checkers.base.basic_error_checker.BasicErrorChecker.visit_call (self, nodes.Call node)
Check instantiating abstract class with
abc.ABCMeta as metaclass.
Definition at line 421 of file basic_error_checker.py.
    def visit_call(self, node: nodes.Call) -> None:
        """Check instantiating abstract class with
        abc.ABCMeta as metaclass.
        """
        for inferred in infer_all(node.func):
            self._check_inferred_class_is_abstract(inferred, node)
References _check_inferred_class_is_abstract().
visit_classdef()
None pylint.checkers.base.basic_error_checker.BasicErrorChecker.visit_classdef (self, nodes.ClassDef node)
Definition at line 211 of file basic_error_checker.py.
    def visit_classdef(self, node: nodes.ClassDef) -> None:
        self._check_redefinition("class", node)
References _check_redefinition().
Referenced by pylint.pyreverse.inspector.Linker.visit_assignname(), and pylint.checkers.exceptions.ExceptionRaiseLeafVisitor.visit_instance().
visit_continue()
None pylint.checkers.base.basic_error_checker.BasicErrorChecker.visit_continue (self, nodes.Continue node)
Definition at line 367 of file basic_error_checker.py.
    def visit_continue(self, node: nodes.Continue) -> None:
        self._check_in_loop(node, "continue")
References _check_in_loop().
visit_for()
None pylint.checkers.base.basic_error_checker.BasicErrorChecker.visit_for (self, nodes.For node)
Definition at line 375 of file basic_error_checker.py.
    def visit_for(self, node: nodes.For) -> None:
        self._check_else_on_loop(node)
References _check_else_on_loop().
visit_functiondef()
None pylint.checkers.base.basic_error_checker.BasicErrorChecker.visit_functiondef (self, nodes.FunctionDef node)
Definition at line 265 of file basic_error_checker.py.
    def visit_functiondef(self, node: nodes.FunctionDef) -> None:
        self._check_nonlocal_and_global(node)
        self._check_name_used_prior_global(node)
        if not redefined_by_decorator(
            node
        ) and not utils.is_registered_in_singledispatch_function(node):
            self._check_redefinition(node.is_method() and "method" or "function", node)
        # checks for max returns, branch, return in __init__
        returns = node.nodes_of_class(
            nodes.Return, skip_klass=(nodes.FunctionDef, nodes.ClassDef)
        )
        if node.is_method() and node.name == "__init__":
            if node.is_generator():
                self.add_message("init-is-generator", node=node)
            else:
                values = [r.value for r in returns]
                # Are we returning anything but None from constructors
                if any(v for v in values if not utils.is_none(v)):
                    self.add_message("return-in-init", node=node)
        # Check for duplicate names by clustering args with same name for detailed report
        arg_clusters = {}
        for arg in node.args.arguments:
            if arg.name in arg_clusters:
                self.add_message(
                    "duplicate-argument-name",
                    node=arg,
                    args=(arg.name,),
                    confidence=HIGH,
                )
            else:
                arg_clusters[arg.name] = arg
References _check_name_used_prior_global(), _check_nonlocal_and_global(), _check_redefinition(), pylint.checkers.base_checker.BaseChecker.add_message(), and pylint.checkers.base.basic_error_checker.redefined_by_decorator().
Referenced by pylint.pyreverse.inspector.Linker.visit_assignname().
visit_nonlocal()
None pylint.checkers.base.basic_error_checker.BasicErrorChecker.visit_nonlocal (self, nodes.Nonlocal node)
Definition at line 416 of file basic_error_checker.py.
    def visit_nonlocal(self, node: nodes.Nonlocal) -> None:
        for name in node.names:
            self._check_nonlocal_without_binding(node, name)
References _check_nonlocal_without_binding().
visit_return()
None pylint.checkers.base.basic_error_checker.BasicErrorChecker.visit_return (self, nodes.Return node)
Definition at line 354 of file basic_error_checker.py.
    def visit_return(self, node: nodes.Return) -> None:
        if not isinstance(node.frame(), nodes.FunctionDef):
            self.add_message("return-outside-function", node=node)
References pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by pylint.checkers.refactoring.refactoring_checker.RefactoringChecker.visit_assign().
visit_starred()
None pylint.checkers.base.basic_error_checker.BasicErrorChecker.visit_starred (self, nodes.Starred node)
Check that a Starred expression is used in an assignment target.
Definition at line 239 of file basic_error_checker.py.
    def visit_starred(self, node: nodes.Starred) -> None:
        """Check that a Starred expression is used in an assignment target."""
        if isinstance(node.parent, nodes.Call):
            # f(*args) is converted to Call(args=[Starred]), so ignore
            # them for this check.
            return
        if isinstance(node.parent, (nodes.List, nodes.Tuple, nodes.Set, nodes.Dict)):
            # PEP 448 unpacking.
            return
        stmt = node.statement()
        if not isinstance(stmt, nodes.Assign):
            return
        if stmt.value is node or stmt.value.parent_of(node):
            self.add_message("star-needs-assignment-target", node=node)
References pylint.checkers.base_checker.BaseChecker.add_message().
visit_unaryop()
None pylint.checkers.base.basic_error_checker.BasicErrorChecker.visit_unaryop (self, nodes.UnaryOp node)
Check use of the non-existent ++ and -- operators.
Definition at line 383 of file basic_error_checker.py.
    def visit_unaryop(self, node: nodes.UnaryOp) -> None:
        """Check use of the non-existent ++ and -- operators."""
        if (
            (node.op in "+-")
            and isinstance(node.operand, nodes.UnaryOp)
            and (node.operand.op == node.op)
            and (node.col_offset + 1 == node.operand.col_offset)
        ):
            self.add_message("nonexistent-operator", node=node, args=node.op * 2)
References pylint.checkers.base_checker.BaseChecker.add_message().
visit_while()
None pylint.checkers.base.basic_error_checker.BasicErrorChecker.visit_while (self, nodes.While node)
Definition at line 379 of file basic_error_checker.py.
    def visit_while(self, node: nodes.While) -> None:
        self._check_else_on_loop(node)
References _check_else_on_loop().
visit_yield()
None pylint.checkers.base.basic_error_checker.BasicErrorChecker.visit_yield (self, nodes.Yield node)
Definition at line 359 of file basic_error_checker.py.
    def visit_yield(self, node: nodes.Yield) -> None:
        self._check_yield_outside_func(node)
References _check_yield_outside_func().
visit_yieldfrom()
None pylint.checkers.base.basic_error_checker.BasicErrorChecker.visit_yieldfrom (self, nodes.YieldFrom node)
Definition at line 363 of file basic_error_checker.py.
    def visit_yieldfrom(self, node: nodes.YieldFrom) -> None:
        self._check_yield_outside_func(node)
References _check_yield_outside_func().
Member Data Documentation
_py38_plus
tuple pylint.checkers.base.basic_error_checker.BasicErrorChecker._py38_plus = (3, 8) protected
Definition at line 208 of file basic_error_checker.py.
Referenced by _check_in_loop(), pylint.checkers.classes.class_checker.ClassChecker._check_invalid_overridden_method(), pylint.checkers.classes.class_checker.ClassChecker._check_typing_final(), pylint.checkers.unsupported_version.UnsupportedVersionChecker._check_typing_final(), pylint.checkers.unsupported_version.UnsupportedVersionChecker.visit_arguments(), pylint.extensions.code_style.CodeStyleChecker.visit_if(), and pylint.checkers.unsupported_version.UnsupportedVersionChecker.visit_namedexpr().
visit_asyncfunctiondef
None pylint.checkers.base.basic_error_checker.BasicErrorChecker.visit_asyncfunctiondef = visit_functiondef static
Definition at line 297 of file basic_error_checker.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pylint/checkers/base/basic_error_checker.py