Read&Watch: django.db.migrations.serializer.BaseSequenceSerializer Class Reference
django.db.migrations.serializer.BaseSequenceSerializer Class Reference
Public Member Functions
serialize (self)
Public Member Functions inherited from django.db.migrations.serializer.BaseSerializer
__init__ (self, value)
Protected Member Functions
_format (self)
Additional Inherited Members
Public Attributes inherited from django.db.migrations.serializer.BaseSerializer
value = value
Detailed Description
Definition at line 41 of file serializer.py.
Member Function Documentation
_format()
django.db.migrations.serializer.BaseSequenceSerializer._format (self) protected
Reimplemented in django.db.migrations.serializer.FrozensetSerializer, django.db.migrations.serializer.SequenceSerializer, django.db.migrations.serializer.SetSerializer, and django.db.migrations.serializer.TupleSerializer.
Definition at line 42 of file serializer.py.
    def _format(self):
        raise NotImplementedError(
            "Subclasses of BaseSequenceSerializer must implement the _format() method."
        )
serialize()
django.db.migrations.serializer.BaseSequenceSerializer.serialize (self)
Reimplemented from django.db.migrations.serializer.BaseSerializer.
Definition at line 47 of file serializer.py.
    def serialize(self):
        imports = set()
        strings = []
        for item in self.value:
            item_string, item_imports = serializer_factory(item).serialize()
            imports.update(item_imports)
            strings.append(item_string)
        value = self._format()
        return value % (", ".join(strings)), imports
Referenced by django.db.migrations.writer.MigrationWriter.as_string(), pylint.reporters.json_reporter.JSON2Reporter.display_messages(), pylint.reporters.json_reporter.JSONReporter.display_messages(), pip._vendor.cachecontrol.serialize.Serializer.dumps(), and yaml.representer.BaseRepresenter.represent().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/db/migrations/serializer.py