Read&Watch: pip._internal.resolution.resolvelib.found_candidates.FoundCandidates Class Reference
pip._internal.resolution.resolvelib.found_candidates.FoundCandidates Class Reference
Public Member Functions
__init__ (self, Callable[[], Iterator[IndexCandidateInfo]] get_infos, Optional[Candidate] installed, bool prefers_installed, Set[int] incompatible_ids)
Any __getitem__ (self, Any index)
Iterator[Candidate] __iter__ (self)
int __len__ (self)
bool __bool__ (self)
Protected Attributes
_get_infos = get_infos
_installed = installed
_prefers_installed = prefers_installed
_incompatible_ids = incompatible_ids
Detailed Description
A lazy sequence to provide candidates to the resolver.
The intended usage is to return this from `find_matches()` so the resolver
can iterate through the sequence multiple times, but only access the index
page when remote packages are actually needed. This improve performances
when suitable candidates are already installed on disk.
Definition at line 127 of file found_candidates.py.
Constructor & Destructor Documentation
__init__()
pip._internal.resolution.resolvelib.found_candidates.FoundCandidates.__init__ (self, Callable[[], Iterator[IndexCandidateInfo]] get_infos, Optional[Candidate] installed, bool prefers_installed, Set[int] incompatible_ids)
Definition at line 136 of file found_candidates.py.
    ):
        self._get_infos = get_infos
        self._installed = installed
        self._prefers_installed = prefers_installed
        self._incompatible_ids = incompatible_ids
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
__bool__()
bool pip._internal.resolution.resolvelib.found_candidates.FoundCandidates.__bool__ (self)
Definition at line 171 of file found_candidates.py.
    def __bool__(self) -> bool:
        if self._prefers_installed and self._installed:
            return True
        return any(self)
References _installed, and _prefers_installed.
__getitem__()
Any pip._internal.resolution.resolvelib.found_candidates.FoundCandidates.__getitem__ (self, Any index)
Definition at line 148 of file found_candidates.py.
    def __getitem__(self, index: Any) -> Any:
        # Implemented to satisfy the ABC check. This is not needed by the
        # resolver, and should not be used by the provider either (for
        # performance reasons).
        raise NotImplementedError("don't do this")
__iter__()
Iterator[Candidate] pip._internal.resolution.resolvelib.found_candidates.FoundCandidates.__iter__ (self)
Definition at line 154 of file found_candidates.py.
    def __iter__(self) -> Iterator[Candidate]:
        infos = self._get_infos()
        if not self._installed:
            iterator = _iter_built(infos)
        elif self._prefers_installed:
            iterator = _iter_built_with_prepended(self._installed, infos)
        else:
            iterator = _iter_built_with_inserted(self._installed, infos)
        return (c for c in iterator if id(c) not in self._incompatible_ids)
References _get_infos, _incompatible_ids, _installed, pip._internal.resolution.resolvelib.found_candidates._iter_built(), pip._internal.resolution.resolvelib.found_candidates._iter_built_with_inserted(), pip._internal.resolution.resolvelib.found_candidates._iter_built_with_prepended(), and _prefers_installed.
Referenced by django.db.models.query.BaseIterable._async_generator().
__len__()
int pip._internal.resolution.resolvelib.found_candidates.FoundCandidates.__len__ (self)
Definition at line 164 of file found_candidates.py.
    def __len__(self) -> int:
        # Implemented to satisfy the ABC check. This is not needed by the
        # resolver, and should not be used by the provider either (for
        # performance reasons).
        raise NotImplementedError("don't do this")
Member Data Documentation
_get_infos
pip._internal.resolution.resolvelib.found_candidates.FoundCandidates._get_infos = get_infos protected
Definition at line 143 of file found_candidates.py.
Referenced by __iter__().
_incompatible_ids
pip._internal.resolution.resolvelib.found_candidates.FoundCandidates._incompatible_ids = incompatible_ids protected
Definition at line 146 of file found_candidates.py.
Referenced by __iter__().
_installed
pip._internal.resolution.resolvelib.found_candidates.FoundCandidates._installed = installed protected
Definition at line 144 of file found_candidates.py.
Referenced by __bool__(), and __iter__().
_prefers_installed
pip._internal.resolution.resolvelib.found_candidates.FoundCandidates._prefers_installed = prefers_installed protected
Definition at line 145 of file found_candidates.py.
Referenced by __bool__(), and __iter__().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py