Read&Watch: crispy_forms.layout.Div Class Reference
crispy_forms.layout.Div Class Reference
Public Member Functions
__init__ (self, *fields, css_id=None, css_class=None, template=None, **kwargs)
render (self, form, context, template_pack=TEMPLATE_PACK, **kwargs)
Public Member Functions inherited from crispy_forms.layout.LayoutObject
__getitem__ (self, slice)
__setitem__ (self, slice, value)
__delitem__ (self, slice)
__len__ (self)
__getattr__ (self, name)
get_field_names (self, index=None)
get_layout_objects (self, *LayoutClasses, index=None, max_level=0, greedy=False)
get_rendered_fields (self, form, context, template_pack=TEMPLATE_PACK, **kwargs)
Public Member Functions inherited from crispy_forms.layout.TemplateNameMixin
get_template_name (self, template_pack)
Public Attributes
css_id = css_id
flat_attrs = flatatt(kwargs)
Public Attributes inherited from crispy_forms.layout.LayoutObject
fields
Public Attributes inherited from crispy_forms.layout.TemplateNameMixin
template
Static Public Attributes
css_class = None
Detailed Description
Layout object. It wraps fields in a ``<div>``.
Attributes
----------
template : str
    The default template which this Layout Object will be rendered
    with.
css_class : str, optional
    CSS classes to be applied to the ``<div>``. By default None.
Parameters
----------
*fields : str, LayoutObject
    Any number of fields as positional arguments to be rendered within
    the ``<div>``.
css_id : str, optional
    A DOM id for the layout object which will be added to the ``<div>`` if
    provided. By default None.
css_class : str, optional
    Additional CSS classes to be applied in addition to those declared by
    the class itself. By default None.
template : str, optional
    Overrides the default template, if provided. By default None.
**kwargs : dict, optional
    Additional attributes are passed to ``flatatt`` and converted into
    key="value", pairs. These attributes are added to the ``<div>``.
Examples
--------
In your ``Layout`` you can::
    Div(
        'form_field_1',
        'form_field_2',
        css_id='div-example',
        css_class='divs',
    )
It is also possible to nest Layout Objects within a Div::
    Div(
        Div(
            Field('form_field', css_class='field-class'),
            css_class='div-class',
        ),
        Div('form_field_2', css_class='div-class'),
    )
Definition at line 680 of file layout.py.
Constructor & Destructor Documentation
__init__()
crispy_forms.layout.Div.__init__ (self, * fields, css_id = None, css_class = None, template = None, ** kwargs)
Definition at line 735 of file layout.py.
    def __init__(self, *fields, css_id=None, css_class=None, template=None, **kwargs):
        self.fields = list(fields)
        if self.css_class and css_class:
            self.css_class += f" {css_class}"
        elif css_class:
            self.css_class = css_class
        self.css_id = css_id
        self.template = template or self.template
        self.flat_attrs = flatatt(kwargs)
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
render()
crispy_forms.layout.Div.render (self, form, context, template_pack = TEMPLATE_PACK, ** kwargs)
Reimplemented in crispy_forms.bootstrap.Accordion, crispy_forms.bootstrap.Alert, crispy_forms.bootstrap.FieldWithButtons, crispy_forms.bootstrap.Tab, and crispy_forms.bootstrap.TabHolder.
Definition at line 747 of file layout.py.
    def render(self, form, context, template_pack=TEMPLATE_PACK, **kwargs):
        fields = self.get_rendered_fields(form, context, template_pack, **kwargs)
        template = self.get_template_name(template_pack)
        return render_to_string(template, {"div": self, "fields": fields})
References crispy_forms.layout.LayoutObject.get_rendered_fields(), and crispy_forms.layout.TemplateNameMixin.get_template_name().
Referenced by pip._vendor.rich.progress.ProgressColumn.__call__(), pip._vendor.rich.layout.Layout.__rich_console__(), pip._vendor.rich.spinner.Spinner.__rich_console__(), pip._vendor.rich.spinner.Spinner.__rich_measure__(), django.forms.widgets.Media.__str__(), django.forms.utils.RenderableFieldMixin.as_field_group(), pip._vendor.rich.console.Console.log(), pip._vendor.rich.console.Console.print(), django.templatetags.i18n.BlockTranslateNode.render(), pip._vendor.rich.console.Console.render(), pip._vendor.rich.console.Console.render_lines(), django.db.migrations.writer.OperationWriter.serialize(), and pip._vendor.rich.console.Console.update_screen_lines().
Member Data Documentation
css_class
crispy_forms.layout.Div.css_class = None static
Definition at line 733 of file layout.py.
css_id
crispy_forms.layout.Div.css_id = css_id
Definition at line 743 of file layout.py.
flat_attrs
crispy_forms.layout.Div.flat_attrs = flatatt(kwargs)
Definition at line 745 of file layout.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/crispy_forms/layout.py