Read&Watch: pip._vendor.idna.codec.Codec Class Reference
pip._vendor.idna.codec.Codec Class Reference
Public Member Functions
Tuple[bytes, int] encode (self, str data, str errors='strict')
Tuple[str, int] decode (self, bytes data, str errors='strict')
Detailed Description
Definition at line 8 of file codec.py.
Member Function Documentation
decode()
Tuple[str, int] pip._vendor.idna.codec.Codec.decode (self, bytes data, str errors = 'strict')
Definition at line 19 of file codec.py.
    def decode(self, data: bytes, errors: str = 'strict') -> Tuple[str, int]:
        if errors != 'strict':
            raise IDNAError('Unsupported error handling \"{}\"'.format(errors))
        if not data:
            return '', 0
        return decode(data), len(data)
References decode().
Referenced by django.contrib.sessions.backends.cached_db.SessionStore.aload(), decode(), and django.contrib.sessions.backends.cached_db.SessionStore.load().
encode()
Tuple[bytes, int] pip._vendor.idna.codec.Codec.encode (self, str data, str errors = 'strict')
Definition at line 10 of file codec.py.
    def encode(self, data: str, errors: str = 'strict') -> Tuple[bytes, int]:
        if errors != 'strict':
            raise IDNAError('Unsupported error handling \"{}\"'.format(errors))
        if not data:
            return b"", 0
        return encode(data), len(data)
References encode().
Referenced by encode().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/idna/codec.py