Read&Watch: pip._vendor.pkg_resources.Environment Class Reference
pip._vendor.pkg_resources.Environment Class Reference
Public Member Functions
__init__ (self, Iterable[str]|None search_path=None, str|None platform=get_supported_platform(), str|None python=PY_MAJOR)
can_add (self, Distribution dist)
remove (self, Distribution dist)
scan (self, Iterable[str]|None search_path=None)
list[Distribution] __getitem__ (self, str project_name)
add (self, Distribution dist)
_DistributionT best_match (self, Requirement req, WorkingSet working_set, _InstallerTypeT[_DistributionT] installer, bool replace_conflicting=False)
Distribution|None best_match (self, Requirement req, WorkingSet working_set, _InstallerType|None installer=None, bool replace_conflicting=False)
Distribution|None best_match (self, Requirement req, WorkingSet working_set, _InstallerType|None|_InstallerTypeT[_DistributionT] installer=None, bool replace_conflicting=False)
_DistributionT obtain (self, Requirement requirement, _InstallerTypeT[_DistributionT] installer)
None obtain (self, Requirement requirement, Callable[[Requirement], None]|None installer=None)
Distribution|None obtain (self, Requirement requirement, _InstallerType|None installer=None)
Distribution|None obtain (self, Requirement requirement, Callable[[Requirement], None]|_InstallerType|None|_InstallerTypeT[_DistributionT] installer=None)
Iterator[str] __iter__ (self)
__iadd__ (self, Distribution|Environment other)
__add__ (self, Distribution|Environment other)
Public Attributes
platform = platform
python = python
Protected Attributes
dict _distmap = {}
Detailed Description
Searchable snapshot of distributions on a search path
Definition at line 1126 of file __init__.py.
Constructor & Destructor Documentation
__init__()
pip._vendor.pkg_resources.Environment.__init__ (self, Iterable[str] | None search_path = None, str | None platform = get_supported_platform(), str | None python = PY_MAJOR)
Snapshot distributions available on a search path
Any distributions found on `search_path` are added to the environment.
`search_path` should be a sequence of ``sys.path`` items.  If not
supplied, ``sys.path`` is used.
`platform` is an optional string specifying the name of the platform
that platform-specific distributions must be compatible with.  If
unspecified, it defaults to the current platform.  `python` is an
optional string naming the desired version of Python (e.g. ``'3.6'``);
it defaults to the current version.
You may explicitly set `platform` (and/or `python`) to ``None`` if you
wish to map *all* distributions, not just those compatible with the
running platform or Python version.
Definition at line 1129 of file __init__.py.
    ):
        """Snapshot distributions available on a search path
        Any distributions found on `search_path` are added to the environment.
        `search_path` should be a sequence of ``sys.path`` items.  If not
        supplied, ``sys.path`` is used.
        `platform` is an optional string specifying the name of the platform
        that platform-specific distributions must be compatible with.  If
        unspecified, it defaults to the current platform.  `python` is an
        optional string naming the desired version of Python (e.g. ``'3.6'``);
        it defaults to the current version.
        You may explicitly set `platform` (and/or `python`) to ``None`` if you
        wish to map *all* distributions, not just those compatible with the
        running platform or Python version.
        """
        self._distmap = {}
        self.platform = platform
        self.python = python
        self.scan(search_path)
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
__add__()
pip._vendor.pkg_resources.Environment.__add__ (self, Distribution | Environment other)
Add an environment or distribution to an environment
Definition at line 1311 of file __init__.py.
    def __add__(self, other: Distribution | Environment):
        """Add an environment or distribution to an environment"""
        new = self.__class__([], platform=None, python=None)
        for env in self, other:
            new += env
        return new
# XXX backward compatibility
__getitem__()
list[Distribution] pip._vendor.pkg_resources.Environment.__getitem__ (self, str project_name)
Return a newest-to-oldest list of distributions for `project_name`
Uses case-insensitive `project_name` comparison, assuming all the
project's distributions use their project's name converted to all
lowercase as their key.
Definition at line 1189 of file __init__.py.
    def __getitem__(self, project_name: str) -> list[Distribution]:
        """Return a newest-to-oldest list of distributions for `project_name`
        Uses case-insensitive `project_name` comparison, assuming all the
        project's distributions use their project's name converted to all
        lowercase as their key.
        """
        distribution_key = project_name.lower()
        return self._distmap.get(distribution_key, [])
__iadd__()
pip._vendor.pkg_resources.Environment.__iadd__ (self, Distribution | Environment other)
In-place addition of a distribution or environment
Definition at line 1299 of file __init__.py.
    def __iadd__(self, other: Distribution | Environment):
        """In-place addition of a distribution or environment"""
        if isinstance(other, Distribution):
            self.add(other)
        elif isinstance(other, Environment):
            for project in other:
                for dist in other[project]:
                    self.add(dist)
        else:
            raise TypeError("Can't add %r to environment" % (other,))
        return self
__iter__()
Iterator[str] pip._vendor.pkg_resources.Environment.__iter__ (self)
Yield the unique project names of the available distributions
Definition at line 1293 of file __init__.py.
    def __iter__(self) -> Iterator[str]:
        """Yield the unique project names of the available distributions"""
        for key in self._distmap.keys():
            if self[key]:
                yield key
Referenced by django.db.models.query.BaseIterable._async_generator().
add()
pip._vendor.pkg_resources.Environment.add (self, Distribution dist)
Add `dist` if we ``can_add()`` it and it has not already been added
Definition at line 1200 of file __init__.py.
    def add(self, dist: Distribution):
        """Add `dist` if we ``can_add()`` it and it has not already been added"""
        if self.can_add(dist) and dist.has_version():
            dists = self._distmap.setdefault(dist.key, [])
            if dist not in dists:
                dists.append(dist)
                dists.sort(key=operator.attrgetter('hashcmp'), reverse=True)
Referenced by responses.RequestsMock._add_from_file(), pip._vendor.urllib3._collections.HTTPHeaderDict.extend(), urllib3._collections.HTTPHeaderDict.extend(), and responses.RequestsMock.upsert().
best_match() [1/3]
_DistributionT pip._vendor.pkg_resources.Environment.best_match (self, Requirement req, WorkingSet working_set, _InstallerTypeT[_DistributionT] installer, bool replace_conflicting = False)
Definition at line 1209 of file __init__.py.
    ) -> _DistributionT: ...
best_match() [2/3]
Distribution | None pip._vendor.pkg_resources.Environment.best_match (self, Requirement req, WorkingSet working_set, _InstallerType | None installer = None, bool replace_conflicting = False)
Definition at line 1217 of file __init__.py.
    ) -> Distribution | None: ...
best_match() [3/3]
Distribution | None pip._vendor.pkg_resources.Environment.best_match (self, Requirement req, WorkingSet working_set, _InstallerType | None | _InstallerTypeT[_DistributionT] installer = None, bool replace_conflicting = False)
Find distribution best matching `req` and usable on `working_set`
This calls the ``find(req)`` method of the `working_set` to see if a
suitable distribution is already active.  (This may raise
``VersionConflict`` if an unsuitable version of the project is already
active in the specified `working_set`.)  If a suitable distribution
isn't active, this method returns the newest distribution in the
environment that meets the ``Requirement`` in `req`.  If no suitable
distribution is found, and `installer` is supplied, then the result of
calling the environment's ``obtain(req, installer)`` method will be
returned.
Definition at line 1224 of file __init__.py.
    ) -> Distribution | None:
        """Find distribution best matching `req` and usable on `working_set`
        This calls the ``find(req)`` method of the `working_set` to see if a
        suitable distribution is already active.  (This may raise
        ``VersionConflict`` if an unsuitable version of the project is already
        active in the specified `working_set`.)  If a suitable distribution
        isn't active, this method returns the newest distribution in the
        environment that meets the ``Requirement`` in `req`.  If no suitable
        distribution is found, and `installer` is supplied, then the result of
        calling the environment's ``obtain(req, installer)`` method will be
        returned.
        """
        try:
            dist = working_set.find(req)
        except VersionConflict:
            if not replace_conflicting:
                raise
            dist = None
        if dist is not None:
            return dist
        for dist in self[req.key]:
            if dist in req:
                return dist
        # try to download/install
        return self.obtain(req, installer)
can_add()
pip._vendor.pkg_resources.Environment.can_add (self, Distribution dist)
Is distribution `dist` acceptable for this environment?
The distribution must match the platform and python version
requirements specified when this environment was created, or False
is returned.
Definition at line 1156 of file __init__.py.
    def can_add(self, dist: Distribution):
        """Is distribution `dist` acceptable for this environment?
        The distribution must match the platform and python version
        requirements specified when this environment was created, or False
        is returned.
        """
        py_compat = (
            self.python is None
            or dist.py_version is None
            or dist.py_version == self.python
        )
        return py_compat and compatible_platforms(dist.platform, self.platform)
obtain() [1/4]
_DistributionT pip._vendor.pkg_resources.Environment.obtain (self, Requirement requirement, _InstallerTypeT[_DistributionT] installer)
Definition at line 1258 of file __init__.py.
    ) -> _DistributionT: ...
obtain() [2/4]
Distribution | None pip._vendor.pkg_resources.Environment.obtain (self, Requirement requirement, _InstallerType | None installer = None)
Definition at line 1270 of file __init__.py.
    ) -> Distribution | None: ...
obtain() [3/4]
Distribution | None pip._vendor.pkg_resources.Environment.obtain (self, Requirement requirement, Callable[[Requirement], None] | _InstallerType | None | _InstallerTypeT[_DistributionT] installer = None)
Obtain a distribution matching `requirement` (e.g. via download)
Obtain a distro that matches requirement (e.g. via download).  In the
base ``Environment`` class, this routine just returns
``installer(requirement)``, unless `installer` is None, in which case
None is returned instead.  This method is a hook that allows subclasses
to attempt other ways of obtaining a distribution before falling back
to the `installer` argument.
Definition at line 1275 of file __init__.py.
    ) -> Distribution | None:
        """Obtain a distribution matching `requirement` (e.g. via download)
        Obtain a distro that matches requirement (e.g. via download).  In the
        base ``Environment`` class, this routine just returns
        ``installer(requirement)``, unless `installer` is None, in which case
        None is returned instead.  This method is a hook that allows subclasses
        to attempt other ways of obtaining a distribution before falling back
        to the `installer` argument."""
        return installer(requirement) if installer else None
obtain() [4/4]
None pip._vendor.pkg_resources.Environment.obtain (self, Requirement requirement, Callable[[Requirement], None] | None installer = None)
Definition at line 1264 of file __init__.py.
    ) -> None: ...
remove()
pip._vendor.pkg_resources.Environment.remove (self, Distribution dist)
Remove `dist` from the environment
Definition at line 1170 of file __init__.py.
    def remove(self, dist: Distribution):
        """Remove `dist` from the environment"""
        self._distmap[dist.key].remove(dist)
Referenced by tomlkit.container.Container.__delitem__(), tomlkit.items.AbstractTable.__delitem__(), and tomlkit.container.Container._replace_at().
scan()
pip._vendor.pkg_resources.Environment.scan (self, Iterable[str] | None search_path = None)
Scan `search_path` for distributions usable in this environment
Any distributions found are added to the environment.
`search_path` should be a sequence of ``sys.path`` items.  If not
supplied, ``sys.path`` is used.  Only distributions conforming to
the platform/python version defined at initialization are added.
Definition at line 1174 of file __init__.py.
    def scan(self, search_path: Iterable[str] | None = None):
        """Scan `search_path` for distributions usable in this environment
        Any distributions found are added to the environment.
        `search_path` should be a sequence of ``sys.path`` items.  If not
        supplied, ``sys.path`` is used.  Only distributions conforming to
        the platform/python version defined at initialization are added.
        """
        if search_path is None:
            search_path = sys.path
        for item in search_path:
            for dist in find_distributions(item):
                self.add(dist)
Referenced by pip._vendor.pygments.scanner.Scanner.get_char().
Member Data Documentation
_distmap
dict pip._vendor.pkg_resources.Environment._distmap = {} protected
Definition at line 1151 of file __init__.py.
platform
pip._vendor.pkg_resources.Environment.platform = platform
Definition at line 1152 of file __init__.py.
python
pip._vendor.pkg_resources.Environment.python = python
Definition at line 1153 of file __init__.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/pkg_resources/__init__.py