Read&Watch: django.test.runner.Shuffler Class Reference
django.test.runner.Shuffler Class Reference
Public Member Functions
__init__ (self, seed=None)
seed_display (self)
shuffle (self, items, key)
Public Attributes
seed = seed
seed_source = seed_source
Static Public Attributes
str hash_algorithm = "md5"
Protected Member Functions
_hash_text (cls, text)
_hash_item (self, item, key)
Detailed Description
This class implements shuffling with a special consistency property.
Consistency means that, for a given seed and key function, if two sets of
items are shuffled, the resulting order will agree on the intersection of
the two sets. For example, if items are removed from an original set, the
shuffled order for the new set will be the shuffled order of the original
set restricted to the smaller set.
Definition at line 577 of file runner.py.
Constructor & Destructor Documentation
__init__()
django.test.runner.Shuffler.__init__ (self, seed = None)
Definition at line 596 of file runner.py.
    def __init__(self, seed=None):
        if seed is None:
            # Limit seeds to 10 digits for simpler output.
            seed = random.randint(0, 10**10 - 1)
            seed_source = "generated"
        else:
            seed_source = "given"
        self.seed = seed
        self.seed_source = seed_source
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
_hash_item()
django.test.runner.Shuffler._hash_item (self, item, key) protected
Definition at line 610 of file runner.py.
    def _hash_item(self, item, key):
        text = "{}{}".format(self.seed, key(item))
        return self._hash_text(text)
References _hash_text(), and seed.
Referenced by shuffle().
_hash_text()
django.test.runner.Shuffler._hash_text (cls, text) protected
Definition at line 591 of file runner.py.
    def _hash_text(cls, text):
        h = hashlib.new(cls.hash_algorithm, usedforsecurity=False)
        h.update(text.encode("utf-8"))
        return h.hexdigest()
References hash_algorithm.
Referenced by _hash_item().
seed_display()
django.test.runner.Shuffler.seed_display (self)
Definition at line 607 of file runner.py.
    def seed_display(self):
        return f"{self.seed!r} ({self.seed_source})"
shuffle()
django.test.runner.Shuffler.shuffle (self, items, key)
Return a new list of the items in a shuffled order.
The `key` is a function that accepts an item in `items` and returns
a string unique for that item that can be viewed as a string id. The
order of the return value is deterministic. It depends on the seed
and key function but not on the original order.
Definition at line 614 of file runner.py.
    def shuffle(self, items, key):
        """
        Return a new list of the items in a shuffled order.
        The `key` is a function that accepts an item in `items` and returns
        a string unique for that item that can be viewed as a string id. The
        order of the return value is deterministic. It depends on the seed
        and key function but not on the original order.
        """
        hashes = {}
        for item in items:
            hashed = self._hash_item(item, key)
            if hashed in hashes:
                msg = "item {!r} has same hash {!r} as item {!r}".format(
                    item,
                    hashed,
                    hashes[hashed],
                )
                raise RuntimeError(msg)
            hashes[hashed] = item
        return [hashes[hashed] for hashed in sorted(hashes)]
References _hash_item().
Member Data Documentation
hash_algorithm
str django.test.runner.Shuffler.hash_algorithm = "md5" static
Definition at line 588 of file runner.py.
Referenced by _hash_text().
seed
django.test.runner.Shuffler.seed = seed
Definition at line 603 of file runner.py.
Referenced by _hash_item().
seed_source
django.test.runner.Shuffler.seed_source = seed_source
Definition at line 604 of file runner.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/test/runner.py