Read&Watch: pip._internal.metadata.pkg_resources.InMemoryMetadata Class Reference
pip._internal.metadata.pkg_resources.InMemoryMetadata Class Reference
Public Member Functions
None __init__ (self, Mapping[str, bytes] metadata, str wheel_name)
bool has_metadata (self, str name)
str get_metadata (self, str name)
Iterable[str] get_metadata_lines (self, str name)
bool metadata_isdir (self, str name)
List[str] metadata_listdir (self, str name)
None run_script (self, str script_name, str namespace)
Protected Attributes
_metadata = metadata
_wheel_name = wheel_name
Detailed Description
IMetadataProvider that reads metadata files from a dictionary.
This also maps metadata decoding exceptions to our internal exception type.
Definition at line 48 of file pkg_resources.py.
Constructor & Destructor Documentation
__init__()
None pip._internal.metadata.pkg_resources.InMemoryMetadata.__init__ (self, Mapping[str, bytes] metadata, str wheel_name)
Definition at line 54 of file pkg_resources.py.
    def __init__(self, metadata: Mapping[str, bytes], wheel_name: str) -> None:
        self._metadata = metadata
        self._wheel_name = wheel_name
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
get_metadata()
str pip._internal.metadata.pkg_resources.InMemoryMetadata.get_metadata (self, str name)
Definition at line 61 of file pkg_resources.py.
    def get_metadata(self, name: str) -> str:
        try:
            return self._metadata[name].decode()
        except UnicodeDecodeError as e:
            # Augment the default error with the origin of the file.
            raise UnsupportedWheel(
                f"Error decoding metadata for {self._wheel_name}: {e} in {name} file"
            )
References _metadata.
Referenced by get_metadata_lines().
get_metadata_lines()
Iterable[str] pip._internal.metadata.pkg_resources.InMemoryMetadata.get_metadata_lines (self, str name)
Definition at line 70 of file pkg_resources.py.
    def get_metadata_lines(self, name: str) -> Iterable[str]:
        return pkg_resources.yield_lines(self.get_metadata(name))
References get_metadata().
has_metadata()
bool pip._internal.metadata.pkg_resources.InMemoryMetadata.has_metadata (self, str name)
Definition at line 58 of file pkg_resources.py.
    def has_metadata(self, name: str) -> bool:
        return name in self._metadata
References _metadata.
metadata_isdir()
bool pip._internal.metadata.pkg_resources.InMemoryMetadata.metadata_isdir (self, str name)
Definition at line 73 of file pkg_resources.py.
    def metadata_isdir(self, name: str) -> bool:
        return False
metadata_listdir()
List[str] pip._internal.metadata.pkg_resources.InMemoryMetadata.metadata_listdir (self, str name)
Definition at line 76 of file pkg_resources.py.
    def metadata_listdir(self, name: str) -> List[str]:
        return []
run_script()
None pip._internal.metadata.pkg_resources.InMemoryMetadata.run_script (self, str script_name, str namespace)
Definition at line 79 of file pkg_resources.py.
    def run_script(self, script_name: str, namespace: str) -> None:
        pass
Member Data Documentation
_metadata
pip._internal.metadata.pkg_resources.InMemoryMetadata._metadata = metadata protected
Definition at line 55 of file pkg_resources.py.
Referenced by django.contrib.gis.geoip2.GeoIP2.__init__(), django.contrib.gis.geoip2.GeoIP2.__repr__(), django.contrib.gis.geoip2.GeoIP2._query(), get_metadata(), and has_metadata().
_wheel_name
pip._internal.metadata.pkg_resources.InMemoryMetadata._wheel_name = wheel_name protected
Definition at line 56 of file pkg_resources.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_internal/metadata/pkg_resources.py