Read&Watch: dill.logger.TraceFormatter Class Reference
dill.logger.TraceFormatter Class Reference
Public Member Functions
__init__ (self, *args, handler=None, **kwargs)
format (self, record)
Public Attributes
bool is_utf8 = False
Detailed Description
Generates message prefix and suffix from record.
This Formatter adds prefix and suffix strings to the log message in trace
mode (an also provides empty string defaults for normal logs).
Definition at line 170 of file logger.py.
Constructor & Destructor Documentation
__init__()
dill.logger.TraceFormatter.__init__ (self, * args, handler = None, ** kwargs)
Definition at line 177 of file logger.py.
    def __init__(self, *args, handler=None, **kwargs):
        super().__init__(*args, **kwargs)
        try:
            encoding = handler.stream.encoding
            if encoding is None:
                raise AttributeError
        except AttributeError:
            encoding = locale.getpreferredencoding()
        try:
            encoding = codecs.lookup(encoding).name
        except LookupError:
            self.is_utf8 = False
        else:
            self.is_utf8 = (encoding == codecs.lookup('utf-8').name)
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Function Documentation
format()
dill.logger.TraceFormatter.format (self, record)
Definition at line 191 of file logger.py.
    def format(self, record):
        fields = {'prefix': "", 'suffix': ""}
        if getattr(record, 'depth', 0) > 0:
            if record.msg.startswith("#"):
                prefix = (record.depth - 1)*"│" + "└"
            elif record.depth == 1:
                prefix = "┬"
            else:
                prefix = (record.depth - 2)*"│" + "├┬"
            if not self.is_utf8:
                prefix = prefix.translate(ASCII_MAP) + "-"
            fields['prefix'] = prefix + " "
        if hasattr(record, 'size') and record.size is not None and record.size >= 1:
            # Show object size in human-readable form.
            power = int(math.log(record.size, 2)) // 10
            size = record.size >> power*10
            fields['suffix'] = " [%d %sB]" % (size, "KMGTP"[power] + "i" if power else "")
        vars(record).update(fields)
        return super().format(record)
References format(), and is_utf8.
Referenced by django.utils.log.AdminEmailHandler.emit(), pip._internal.utils.logging.RichPipStreamHandler.emit(), pip._vendor.rich.logging.RichHandler.emit(), and format().
Member Data Documentation
is_utf8
bool dill.logger.TraceFormatter.is_utf8 = False
Definition at line 188 of file logger.py.
Referenced by format().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/dill/logger.py