Read&Watch: pylint.checkers.unicode.UnicodeChecker Class Reference
pylint.checkers.unicode.UnicodeChecker Class Reference
Public Member Functions
None process_module (self, nodes.Module node)
Public Member Functions inherited from pylint.checkers.base_checker.BaseChecker
None __init__ (self, PyLinter linter)
bool __gt__ (self, Any other)
bool __eq__ (self, object other)
int __hash__ (self)
str __repr__ (self)
str __str__ (self)
str get_full_documentation (self, dict[str, MessageDefinitionTuple] msgs, Iterable[tuple[str, OptionDict, Any]] options, Sequence[tuple[str, str, ReportsCallable]] reports, str|None doc=None, str|None module=None, bool show_options=True)
None add_message (self, str msgid, int|None line=None, nodes.NodeNG|None node=None, Any args=None, Confidence|None confidence=None, int|None col_offset=None, int|None end_lineno=None, int|None end_col_offset=None)
None check_consistency (self)
MessageDefinition create_message_definition_from_tuple (self, str msgid, MessageDefinitionTuple msg_tuple)
list[MessageDefinition] messages (self)
None open (self)
None close (self)
Any get_map_data (self)
None reduce_map_data (self, PyLinter linter, list[Any] data)
Public Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
None __init__ (self, _ArgumentsManager arguments_manager)
Protected Member Functions
dict[int, _BadChar] _find_line_matches (cls, bytes line, str codec)
None _check_codec (self, str codec, int codec_definition_line)
None _check_invalid_chars (self, bytes line, int lineno, str codec)
None _check_bidi_chars (self, bytes line, int lineno, str codec)
Protected Member Functions inherited from pylint.config.arguments_provider._ArgumentsProvider
Any _option_value (self, str opt)
Iterator[ tuple[str, list[tuple[str, OptionDict, Any]]]|tuple[None, dict[str, list[tuple[str, OptionDict, Any]]]]] _options_by_section (self)
Iterator[tuple[str, OptionDict, Any]] _options_and_values (self, Options|None options=None)
Static Protected Member Functions
bool _is_invalid_codec (str codec)
bool _is_unicode (str codec)
tuple[str, int] _determine_codec (io.BytesIO stream)
Additional Inherited Members
Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
linter = linter
messages
Static Public Attributes inherited from pylint.checkers.base_checker.BaseChecker
str name = ""
dict msgs = {}
tuple reports = ()
bool enabled = True
Static Public Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
tuple options = ()
dict option_groups_descs = {}
Protected Attributes inherited from pylint.config.arguments_provider._ArgumentsProvider
_arguments_manager = arguments_manager
Detailed Description
Check characters that could be used to hide bad code to humans.
This includes:
- Bidirectional Unicode (see https://trojansource.codes/)
- Bad ASCII characters (see PEP672)
    If a programmer requires to use such a character they should use the escaped
    version, that is also much easier to read and does not depend on the editor used.
The Checker also includes a check that UTF-16 and UTF-32 are not used to encode
Python files.
At the time of writing Python supported only UTF-8. See
https://stackoverflow.com/questions/69897842/ and https://bugs.python.org/issue1503789
for background.
Definition at line 300 of file unicode.py.
Member Function Documentation
_check_bidi_chars()
None pylint.checkers.unicode.UnicodeChecker._check_bidi_chars (self, bytes line, int lineno, str codec) protected
Look for Bidirectional Unicode, if we use unicode.
Definition at line 492 of file unicode.py.
    def _check_bidi_chars(self, line: bytes, lineno: int, codec: str) -> None:
        """Look for Bidirectional Unicode, if we use unicode."""
        if not self._is_unicode(codec):
            return
        for dangerous in BIDI_UNICODE:
            if _cached_encode_search(dangerous, codec) in line:
                # Note that we don't add a col_offset on purpose:
                #   Using these unicode characters it depends on the editor
                #   how it displays the location of characters in the line.
                #   So we mark the complete line.
                self.add_message(
                    "bidirectional-unicode",
                    # Currently Nodes will lead to crashes of pylint
                    # node=node,
                    line=lineno,
                    end_lineno=lineno,
                    # We mark the complete line, as bidi controls make it hard
                    # to determine the correct cursor position within an editor
                    col_offset=0,
                    end_col_offset=_line_length(line, codec),
                    confidence=pylint.interfaces.HIGH,
                )
                # We look for bidirectional unicode only once per line
                # as we mark the complete line anyway
                break
References pylint.checkers.unicode._cached_encode_search(), _is_unicode(), pylint.checkers.unicode._line_length(), and pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by process_module().
_check_codec()
None pylint.checkers.unicode.UnicodeChecker._check_codec (self, str codec, int codec_definition_line) protected
Check validity of the codec.
Definition at line 460 of file unicode.py.
    def _check_codec(self, codec: str, codec_definition_line: int) -> None:
        """Check validity of the codec."""
        if codec != "utf-8":
            msg = "bad-file-encoding"
            if self._is_invalid_codec(codec):
                msg = "invalid-unicode-codec"
            self.add_message(
                msg,
                # Currently Nodes will lead to crashes of pylint
                # node=node,
                line=codec_definition_line,
                end_lineno=codec_definition_line,
                confidence=pylint.interfaces.HIGH,
                col_offset=None,
                end_col_offset=None,
            )
References _is_invalid_codec(), and pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by process_module().
_check_invalid_chars()
None pylint.checkers.unicode.UnicodeChecker._check_invalid_chars (self, bytes line, int lineno, str codec) protected
Look for chars considered bad.
Definition at line 477 of file unicode.py.
    def _check_invalid_chars(self, line: bytes, lineno: int, codec: str) -> None:
        """Look for chars considered bad."""
        matches = self._find_line_matches(line, codec)
        for col, char in matches.items():
            self.add_message(
                char.human_code(),
                # Currently Nodes will lead to crashes of pylint
                # node=node,
                line=lineno,
                end_lineno=lineno,
                confidence=pylint.interfaces.HIGH,
                col_offset=col + 1,
                end_col_offset=col + len(char.unescaped) + 1,
            )
References _find_line_matches(), and pylint.checkers.base_checker.BaseChecker.add_message().
Referenced by process_module().
_determine_codec()
tuple[str, int] pylint.checkers.unicode.UnicodeChecker._determine_codec (io.BytesIO stream) static protected
Determine the codec from the given stream.
first tries https://www.python.org/dev/peps/pep-0263/
and if this fails also checks for BOMs of UTF-16 and UTF-32
to be future-proof.
Args:
    stream: The byte stream to analyse
Returns: A tuple consisting of:
          - normalized codec name
          - the line in which the codec was found
Raises:
    SyntaxError: if failing to detect codec
Definition at line 420 of file unicode.py.
    def _determine_codec(stream: io.BytesIO) -> tuple[str, int]:
        """Determine the codec from the given stream.
        first tries https://www.python.org/dev/peps/pep-0263/
        and if this fails also checks for BOMs of UTF-16 and UTF-32
        to be future-proof.
        Args:
            stream: The byte stream to analyse
        Returns: A tuple consisting of:
                  - normalized codec name
                  - the line in which the codec was found
        Raises:
            SyntaxError: if failing to detect codec
        """
        try:
            # First try to detect encoding with PEP 263
            # Doesn't work with UTF-16/32 at the time of writing
            # see https://bugs.python.org/issue1503789
            codec, lines = detect_encoding(stream.readline)
            # lines are empty if UTF-8 BOM is found
            codec_definition_line = len(lines) or 1
        except SyntaxError as e:
            # Codec could not be detected by Python, we try manually to check for
            # UTF 16/32 BOMs, which aren't supported by Python at the time of writing.
            # This is only included to be future save and handle these codecs as well
            stream.seek(0)
            try:
                codec = extract_codec_from_bom(stream.readline())
                codec_definition_line = 1
            except ValueError as ve:
                # Failed to detect codec, so the syntax error originated not from
                # UTF16/32 codec usage. So simply raise the error again.
                raise e from ve
        return _normalize_codec_name(codec), codec_definition_line
References pylint.checkers.unicode._normalize_codec_name(), and pylint.checkers.unicode.extract_codec_from_bom().
Referenced by process_module().
_find_line_matches()
dict[int, _BadChar] pylint.checkers.unicode.UnicodeChecker._find_line_matches (cls, bytes line, str codec) protected
Find all matches of BAD_CHARS within line.
Args:
    line: the input
    codec: that will be used to convert line/or search string into
Return:
    A dictionary with the column offset and the BadASCIIChar
Definition at line 384 of file unicode.py.
    def _find_line_matches(cls, line: bytes, codec: str) -> dict[int, _BadChar]:
        """Find all matches of BAD_CHARS within line.
        Args:
            line: the input
            codec: that will be used to convert line/or search string into
        Return:
            A dictionary with the column offset and the BadASCIIChar
        """
        # We try to decode in Unicode to get the correct column offset
        # if we would use bytes, it could be off because UTF-8 has no fixed length
        try:
            line_search = line.decode(codec, errors="strict")
            search_dict = BAD_ASCII_SEARCH_DICT
            return _map_positions_to_result(line_search, search_dict, "\n")
        except UnicodeDecodeError:
            # If we can't decode properly, we simply use bytes, even so the column offsets
            # might be wrong a bit, but it is still better then nothing
            line_search_byte = line
            search_dict_byte: dict[bytes, _BadChar] = {}
            for char in BAD_CHARS:
                # Some characters might not exist in all encodings
                with contextlib.suppress(UnicodeDecodeError):
                    search_dict_byte[_cached_encode_search(char.unescaped, codec)] = (
                        char
                    )
            return _map_positions_to_result(
                line_search_byte,
                search_dict_byte,
                _cached_encode_search("\n", codec),
                byte_str_length=_byte_to_str_length(codec),
            )
References pylint.checkers.unicode._byte_to_str_length(), pylint.checkers.unicode._cached_encode_search(), and pylint.checkers.unicode._map_positions_to_result().
Referenced by _check_invalid_chars().
_is_invalid_codec()
bool pylint.checkers.unicode.UnicodeChecker._is_invalid_codec (str codec) static protected
Definition at line 376 of file unicode.py.
    def _is_invalid_codec(codec: str) -> bool:
        return codec.startswith(("utf-16", "utf-32"))
Referenced by _check_codec().
_is_unicode()
bool pylint.checkers.unicode.UnicodeChecker._is_unicode (str codec) static protected
Definition at line 380 of file unicode.py.
    def _is_unicode(codec: str) -> bool:
        return codec.startswith("utf")
Referenced by _check_bidi_chars().
process_module()
None pylint.checkers.unicode.UnicodeChecker.process_module (self, nodes.Module node)
Perform the actual check by checking module stream.
Reimplemented from pylint.checkers.base_checker.BaseRawFileChecker.
Definition at line 518 of file unicode.py.
    def process_module(self, node: nodes.Module) -> None:
        """Perform the actual check by checking module stream."""
        with node.stream() as stream:
            codec, codec_line = self._determine_codec(stream)
            self._check_codec(codec, codec_line)
            stream.seek(0)
            # Check for invalid content (controls/chars)
            for lineno, line in enumerate(
                _fix_utf16_32_line_stream(stream, codec), start=1
            ):
                if lineno == 1:
                    line = _remove_bom(line, codec)
                self._check_bidi_chars(line, lineno, codec)
                self._check_invalid_chars(line, lineno, codec)
References _check_bidi_chars(), _check_codec(), _check_invalid_chars(), _determine_codec(), pylint.checkers.unicode._fix_utf16_32_line_stream(), and pylint.checkers.unicode._remove_bom().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pylint/checkers/unicode.py