Read&Watch: pip._internal.vcs.bazaar.Bazaar Class Reference
pip._internal.vcs.bazaar.Bazaar Class Reference
Public Member Functions
None fetch_new (self, str dest, HiddenText url, RevOptions rev_options, int verbosity)
None switch (self, str dest, HiddenText url, RevOptions rev_options)
None update (self, str dest, HiddenText url, RevOptions rev_options)
Tuple[str, Optional[str], AuthInfo] get_url_rev_and_auth (cls, str url)
str get_remote_url (cls, str location)
str get_revision (cls, str location)
bool is_commit_id_equal (cls, str dest, Optional[str] name)
Public Member Functions inherited from pip._internal.vcs.versioncontrol.VersionControl
bool should_add_vcs_url_prefix (cls, str remote_url)
Optional[str] get_subdirectory (cls, str location)
str get_requirement_revision (cls, str repo_dir)
str get_src_requirement (cls, str repo_dir, str project_name)
bool is_immutable_rev_checkout (self, str url, str dest)
RevOptions make_rev_options (cls, Optional[str] rev=None, Optional[CommandArgs] extra_args=None)
Tuple[str, Tuple[Optional[str], Optional[str]]] get_netloc_and_auth (cls, str netloc, str scheme)
Tuple[HiddenText, RevOptions] get_url_rev_options (self, HiddenText url)
bool compare_urls (cls, str url1, str url2)
None obtain (self, str dest, HiddenText url, int verbosity)
None unpack (self, str location, HiddenText url, int verbosity)
str run_command (cls, Union[List[str], CommandArgs] cmd, bool show_stdout=True, Optional[str] cwd=None, 'Literal["raise", "warn", "ignore"]' on_returncode="raise", Optional[Iterable[int]] extra_ok_returncodes=None, Optional[str] command_desc=None, Optional[Mapping[str, Any]] extra_environ=None, Optional[SpinnerInterface] spinner=None, bool log_failed_cmd=True, bool stdout_only=False)
bool is_repository_directory (cls, str path)
Optional[str] get_repository_root (cls, str location)
Static Public Member Functions
List[str] get_base_rev_args (str rev)
Static Public Member Functions inherited from pip._internal.vcs.versioncontrol.VersionControl
CommandArgs make_rev_args (Optional[str] username, Optional[HiddenText] password)
str normalize_url (str url)
Additional Inherited Members
Static Public Attributes inherited from pip._internal.vcs.versioncontrol.VersionControl
str name = ""
str dirname = ""
str repo_name = ""
tuple schemes = ()
tuple unset_environ = ()
Optional default_arg_rev = None
Protected Member Functions inherited from pip._internal.vcs.versioncontrol.VersionControl
bool _is_local_repository (cls, str repo)
Detailed Description
Definition at line 18 of file bazaar.py.
Member Function Documentation
fetch_new()
None pip._internal.vcs.bazaar.Bazaar.fetch_new (self, str dest, HiddenText url, RevOptions rev_options, int verbosity)
Fetch a revision from a repository, in the case that this is the
first fetch from the repository.
Args:
  dest: the directory to fetch the repository to.
  rev_options: a RevOptions object.
  verbosity: verbosity level.
Reimplemented from pip._internal.vcs.versioncontrol.VersionControl.
Definition at line 36 of file bazaar.py.
    ) -> None:
        rev_display = rev_options.to_display()
        logger.info(
            "Checking out %s%s to %s",
            url,
            rev_display,
            display_path(dest),
        )
        if verbosity <= 0:
            flags = ["--quiet"]
        elif verbosity == 1:
            flags = []
        else:
            flags = [f"-{'v'*verbosity}"]
        cmd_args = make_command(
            "checkout", "--lightweight", *flags, rev_options.to_args(), url, dest
        )
        self.run_command(cmd_args)
References pip._internal.vcs.versioncontrol.VersionControl.run_command().
Referenced by pip._internal.vcs.versioncontrol.VersionControl.obtain().
get_base_rev_args()
List[str] pip._internal.vcs.bazaar.Bazaar.get_base_rev_args (str rev) static
Return the base revision arguments for a vcs command.
Args:
  rev: the name of a revision to install.  Cannot be None.
Reimplemented from pip._internal.vcs.versioncontrol.VersionControl.
Definition at line 33 of file bazaar.py.
    def get_base_rev_args(rev: str) -> List[str]:
        return ["-r", rev]
get_remote_url()
str pip._internal.vcs.bazaar.Bazaar.get_remote_url (cls, str location)
Return the url used at location
Raises RemoteNotFoundError if the repository does not have a remote
url configured.
Reimplemented from pip._internal.vcs.versioncontrol.VersionControl.
Definition at line 82 of file bazaar.py.
    def get_remote_url(cls, location: str) -> str:
        urls = cls.run_command(
            ["info"], show_stdout=False, stdout_only=True, cwd=location
        )
        for line in urls.splitlines():
            line = line.strip()
            for x in ("checkout of branch: ", "parent branch: "):
                if line.startswith(x):
                    repo = line.split(x)[1]
                    if cls._is_local_repository(repo):
                        return path_to_url(repo)
                    return repo
        raise RemoteNotFoundError
References pip._internal.vcs.versioncontrol.VersionControl._is_local_repository(), and pip._internal.vcs.versioncontrol.VersionControl.run_command().
Referenced by pip._internal.vcs.versioncontrol.VersionControl.get_src_requirement(), and pip._internal.vcs.versioncontrol.VersionControl.obtain().
get_revision()
str pip._internal.vcs.bazaar.Bazaar.get_revision (cls, str location)
Return the current commit id of the files at the given location.
Reimplemented from pip._internal.vcs.versioncontrol.VersionControl.
Definition at line 97 of file bazaar.py.
    def get_revision(cls, location: str) -> str:
        revision = cls.run_command(
            ["revno"],
            show_stdout=False,
            stdout_only=True,
            cwd=location,
        )
        return revision.splitlines()[-1]
References pip._internal.vcs.versioncontrol.VersionControl.run_command().
Referenced by pip._internal.vcs.versioncontrol.VersionControl.get_requirement_revision().
get_url_rev_and_auth()
Tuple[str, Optional[str], AuthInfo] pip._internal.vcs.bazaar.Bazaar.get_url_rev_and_auth (cls, str url)
Parse the repository URL to use, and return the URL, revision,
and auth info to use.
Returns: (url, rev, (username, password)).
Reimplemented from pip._internal.vcs.versioncontrol.VersionControl.
Definition at line 74 of file bazaar.py.
    def get_url_rev_and_auth(cls, url: str) -> Tuple[str, Optional[str], AuthInfo]:
        # hotfix the URL scheme after removing bzr+ from bzr+ssh:// re-add it
        url, rev, user_pass = super().get_url_rev_and_auth(url)
        if url.startswith("ssh://"):
            url = "bzr+" + url
        return url, rev, user_pass
References get_url_rev_and_auth().
Referenced by get_url_rev_and_auth(), and pip._internal.vcs.versioncontrol.VersionControl.get_url_rev_options().
is_commit_id_equal()
bool pip._internal.vcs.bazaar.Bazaar.is_commit_id_equal (cls, str dest, Optional[str] name)
Always assume the versions don't match
Reimplemented from pip._internal.vcs.versioncontrol.VersionControl.
Definition at line 107 of file bazaar.py.
    def is_commit_id_equal(cls, dest: str, name: Optional[str]) -> bool:
        """Always assume the versions don't match"""
        return False
Referenced by pip._internal.vcs.versioncontrol.VersionControl.obtain().
switch()
None pip._internal.vcs.bazaar.Bazaar.switch (self, str dest, HiddenText url, RevOptions rev_options)
Switch the repo at ``dest`` to point to ``URL``.
Args:
  rev_options: a RevOptions object.
Reimplemented from pip._internal.vcs.versioncontrol.VersionControl.
Definition at line 57 of file bazaar.py.
    def switch(self, dest: str, url: HiddenText, rev_options: RevOptions) -> None:
        self.run_command(make_command("switch", url), cwd=dest)
References pip._internal.vcs.versioncontrol.VersionControl.run_command().
Referenced by pip._internal.vcs.versioncontrol.VersionControl.obtain().
update()
None pip._internal.vcs.bazaar.Bazaar.update (self, str dest, HiddenText url, RevOptions rev_options)
Update an already-existing repo to the given ``rev_options``.
Args:
  rev_options: a RevOptions object.
Reimplemented from pip._internal.vcs.versioncontrol.VersionControl.
Definition at line 60 of file bazaar.py.
    def update(self, dest: str, url: HiddenText, rev_options: RevOptions) -> None:
        output = self.run_command(
            make_command("info"), show_stdout=False, stdout_only=True, cwd=dest
        )
        if output.startswith("Standalone "):
            # Older versions of pip used to create standalone branches.
            # Convert the standalone branch to a checkout by calling "bzr bind".
            cmd_args = make_command("bind", "-q", url)
            self.run_command(cmd_args, cwd=dest)
        cmd_args = make_command("update", "-q", rev_options.to_args())
        self.run_command(cmd_args, cwd=dest)
References pip._internal.vcs.versioncontrol.VersionControl.run_command().
Referenced by tomlkit._types._CustomDict.__ior__(), yaml.reader.Reader.determine_encoding(), yaml.reader.Reader.forward(), pip._internal.vcs.versioncontrol.VersionControl.obtain(), pip._vendor.rich.progress.Progress.open(), yaml.reader.Reader.peek(), yaml.reader.Reader.prefix(), pip._vendor.rich.progress.Progress.track(), and pip._vendor.rich.progress.Progress.wrap_file().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_internal/vcs/bazaar.py