Read&Watch: django.contrib.gis.db.backends.oracle.models.OracleSpatialRefSys Class Reference
django.contrib.gis.db.backends.oracle.models.OracleSpatialRefSys Class Reference
Classes
class Meta
Public Member Functions
wkt (self)
Public Member Functions inherited from django.db.models.base.Model
__init__ (self, *args, **kwargs)
from_db (cls, db, field_names, values)
__repr__ (self)
__str__ (self)
__eq__ (self, other)
__hash__ (self)
__reduce__ (self)
__getstate__ (self)
__setstate__ (self, state)
get_deferred_fields (self)
refresh_from_db (self, using=None, fields=None, from_queryset=None)
arefresh_from_db (self, using=None, fields=None, from_queryset=None)
serializable_value (self, field_name)
save (self, *args, force_insert=False, force_update=False, using=None, update_fields=None)
asave (self, *args, force_insert=False, force_update=False, using=None, update_fields=None)
save_base (self, raw=False, force_insert=False, force_update=False, using=None, update_fields=None)
delete (self, using=None, keep_parents=False)
adelete (self, using=None, keep_parents=False)
prepare_database_save (self, field)
clean (self)
validate_unique (self, exclude=None)
date_error_message (self, lookup_type, field_name, unique_for)
unique_error_message (self, model_class, unique_check)
get_constraints (self)
validate_constraints (self, exclude=None)
full_clean (self, exclude=None, validate_unique=True, validate_constraints=True)
clean_fields (self, exclude=None)
check (cls, **kwargs)
Public Member Functions inherited from django.db.models.utils.AltersData
__init_subclass__ (cls, **kwargs)
Public Member Functions inherited from django.db.models.base.ModelBase
__new__ (cls, name, bases, attrs, **kwargs)
add_to_class (cls, name, value)
Public Member Functions inherited from django.contrib.gis.db.backends.base.models.SpatialRefSysMixin
srs (self)
ellipsoid (self)
name (self)
spheroid (self)
datum (self)
projected (self)
local (self)
geographic (self)
linear_name (self)
linear_units (self)
angular_name (self)
angular_units (self)
units (self)
get_units (cls, wkt)
get_spheroid (cls, wkt, string=True)
__str__ (self)
Static Public Attributes
cs_name = models.CharField(max_length=68)
srid = models.IntegerField(primary_key=True)
auth_srid = models.IntegerField()
auth_name = models.CharField(max_length=256)
wktext = models.CharField(max_length=2046)
cs_bounds = models.PolygonField(null=True)
Static Public Attributes inherited from django.db.models.base.Model
alters_data
Additional Inherited Members
Public Attributes inherited from django.db.models.base.Model
refresh_from_db
save
delete
Public Attributes inherited from django.db.models.base.ModelBase
get_next_in_order
get_previous_in_order
Public Attributes inherited from django.contrib.gis.db.backends.base.models.SpatialRefSysMixin
local
linear_units
linear_name
geographic
angular_units
angular_name
srs
Protected Member Functions inherited from django.db.models.base.Model
_get_pk_val (self, meta=None)
_set_pk_val (self, value)
_parse_params (self, *args, method_name, **kwargs)
_validate_force_insert (cls, force_insert)
_save_parents (self, cls, using, update_fields, force_insert, updated_parents=None)
_save_table (self, raw=False, cls=None, force_insert=False, force_update=False, using=None, update_fields=None)
_do_update (self, base_qs, using, pk_val, values, update_fields, forced_update)
_do_insert (self, manager, using, fields, returning_fields, raw)
_prepare_related_fields_for_save (self, operation_name, fields=None)
_get_FIELD_display (self, field)
_get_next_or_previous_by_FIELD (self, field, is_next, **kwargs)
_get_next_or_previous_in_order (self, is_next)
_get_field_expression_map (self, meta, exclude=None)
_get_unique_checks (self, exclude=None, include_meta_constraints=False)
_perform_unique_checks (self, unique_checks)
_perform_date_checks (self, date_checks)
_check_default_pk (cls)
_check_db_table_comment (cls, databases)
_check_swappable (cls)
_check_model (cls)
_check_managers (cls, **kwargs)
_check_fields (cls, **kwargs)
_check_m2m_through_same_relationship (cls)
_check_id_field (cls)
_check_field_name_clashes (cls)
_check_column_name_clashes (cls)
_check_model_name_db_lookup_clashes (cls)
_check_property_name_related_field_accessor_clashes (cls)
_check_single_primary_key (cls)
_check_unique_together (cls)
_check_indexes (cls, databases)
_check_local_fields (cls, fields, option)
_check_ordering (cls)
_check_long_column_names (cls, databases)
_get_expr_references (cls, expr)
_check_constraints (cls, databases)
Protected Member Functions inherited from django.db.models.base.ModelBase
_prepare (cls)
_base_manager (cls)
_default_manager (cls)
Protected Attributes inherited from django.db.models.base.Model
_state = ModelState()
dict _prefetched_objects_cache = {}
tuple _order
Protected Attributes inherited from django.contrib.gis.db.backends.base.models.SpatialRefSysMixin
_srs = gdal.SpatialReference(self.wkt)
Properties inherited from django.db.models.base.Model
pk = property(_get_pk_val, _set_pk_val)
Detailed Description
Definition at line 47 of file models.py.
Member Function Documentation
wkt()
django.contrib.gis.db.backends.oracle.models.OracleSpatialRefSys.wkt (self)
Reimplemented from django.contrib.gis.db.backends.base.models.SpatialRefSysMixin.
Definition at line 64 of file models.py.
    def wkt(self):
        return self.wktext
References wktext.
Member Data Documentation
auth_name
django.contrib.gis.db.backends.oracle.models.OracleSpatialRefSys.auth_name = models.CharField(max_length=256) static
Definition at line 52 of file models.py.
auth_srid
django.contrib.gis.db.backends.oracle.models.OracleSpatialRefSys.auth_srid = models.IntegerField() static
Definition at line 51 of file models.py.
cs_bounds
django.contrib.gis.db.backends.oracle.models.OracleSpatialRefSys.cs_bounds = models.PolygonField(null=True) static
Definition at line 56 of file models.py.
cs_name
django.contrib.gis.db.backends.oracle.models.OracleSpatialRefSys.cs_name = models.CharField(max_length=68) static
Definition at line 49 of file models.py.
srid
django.contrib.gis.db.backends.oracle.models.OracleSpatialRefSys.srid = models.IntegerField(primary_key=True) static
Definition at line 50 of file models.py.
Referenced by django.contrib.gis.geos.geometry.GEOSGeometryBase.__eq__(), django.contrib.gis.geos.geometry.GEOSGeometryBase.__getstate__(), django.contrib.gis.db.backends.postgis.models.PostGISGeometryColumns.__str__(), django.contrib.gis.db.backends.spatialite.models.SpatialiteGeometryColumns.__str__(), django.contrib.gis.geos.collections.GeometryCollection._get_single_external(), django.contrib.gis.geos.polygon.Polygon._get_single_external(), django.contrib.gis.geos.collections.GeometryCollection._set_list(), django.contrib.gis.geos.linestring.LineString._set_list(), django.contrib.gis.geos.point.Point._set_list(), django.contrib.gis.geos.polygon.Polygon._set_list(), django.contrib.gis.geos.geometry.GEOSGeometryBase._topology(), django.contrib.gis.forms.fields.GeometryField.clean(), django.contrib.gis.db.models.fields.BaseSpatialField.deconstruct(), django.contrib.gis.geos.geometry.GEOSGeometryBase.ewkt(), django.contrib.gis.db.models.fields.GeometryField.formfield(), django.contrib.gis.db.models.fields.BaseSpatialField.geodetic(), django.contrib.gis.gdal.geometries.OGRGeometry.geos(), django.contrib.gis.serializers.geojson.Serializer.get_dump_object(), django.contrib.gis.db.models.fields.BaseSpatialField.get_srid(), django.contrib.gis.geos.geometry.GEOSGeometryBase.make_valid(), django.contrib.gis.db.models.fields.BaseSpatialField.spheroid(), django.contrib.gis.geos.geometry.GEOSGeometryBase.srs(), django.contrib.gis.gdal.raster.source.GDALRaster.transform(), django.contrib.gis.geos.geometry.GEOSGeometryBase.transform(), django.contrib.gis.db.models.fields.BaseSpatialField.units(), and django.contrib.gis.db.models.fields.BaseSpatialField.units_name().
wktext
django.contrib.gis.db.backends.oracle.models.OracleSpatialRefSys.wktext = models.CharField(max_length=2046) static
Definition at line 53 of file models.py.
Referenced by wkt().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/gis/db/backends/oracle/models.py