Read&Watch: pip._vendor.resolvelib.resolvers.ResolutionTooDeep Class Reference
pip._vendor.resolvelib.resolvers.ResolutionTooDeep Class Reference
Public Member Functions
__init__ (self, round_count)
Public Attributes
round_count = round_count
Detailed Description
Definition at line 95 of file resolvers.py.
Constructor & Destructor Documentation
__init__()
pip._vendor.resolvelib.resolvers.ResolutionTooDeep.__init__ (self, round_count)
Definition at line 96 of file resolvers.py.
    def __init__(self, round_count):
        super(ResolutionTooDeep, self).__init__(round_count)
        self.round_count = round_count
# Resolution state in a round.
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Data Documentation
round_count
pip._vendor.resolvelib.resolvers.ResolutionTooDeep.round_count = round_count
Definition at line 98 of file resolvers.py.
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/resolvelib/resolvers.py