Read&Watch: pip._vendor.pygments.style.StyleMeta Class Reference
pip._vendor.pygments.style.StyleMeta Class Reference
Public Member Functions
__new__ (mcs, name, bases, dct)
style_for_token (cls, token)
list_styles (cls)
styles_token (cls, ttype)
__iter__ (cls)
__len__ (cls)
Protected Attributes
_styles
Detailed Description
Definition at line 58 of file style.py.
Member Function Documentation
__iter__()
pip._vendor.pygments.style.StyleMeta.__iter__ (cls)
Definition at line 162 of file style.py.
    def __iter__(cls):
        for token in cls._styles:
            yield token, cls.style_for_token(token)
Referenced by django.db.models.query.BaseIterable._async_generator().
__len__()
pip._vendor.pygments.style.StyleMeta.__len__ (cls)
Definition at line 166 of file style.py.
    def __len__(cls):
        return len(cls._styles)
References _styles.
__new__()
pip._vendor.pygments.style.StyleMeta.__new__ (mcs, name, bases, dct)
Definition at line 60 of file style.py.
    def __new__(mcs, name, bases, dct):
        obj = type.__new__(mcs, name, bases, dct)
        for token in STANDARD_TYPES:
            if token not in obj.styles:
                obj.styles[token] = ''
        def colorformat(text):
            if text in ansicolors:
                return text
            if text[0:1] == '#':
                col = text[1:]
                if len(col) == 6:
                    return col
                elif len(col) == 3:
                    return col[0] * 2 + col[1] * 2 + col[2] * 2
            elif text == '':
                return ''
            elif text.startswith('var') or text.startswith('calc'):
                return text
            assert False, f"wrong color format {text!r}"
        _styles = obj._styles = {}
        for ttype in obj.styles:
            for token in ttype.split():
                if token in _styles:
                    continue
                ndef = _styles.get(token.parent, None)
                styledefs = obj.styles.get(token, '').split()
                if not ndef or token is None:
                    ndef = ['', 0, 0, 0, '', '', 0, 0, 0]
                elif 'noinherit' in styledefs and token is not Token:
                    ndef = _styles[Token][:]
                else:
                    ndef = ndef[:]
                _styles[token] = ndef
                for styledef in obj.styles.get(token, '').split():
                    if styledef == 'noinherit':
                        pass
                    elif styledef == 'bold':
                        ndef[1] = 1
                    elif styledef == 'nobold':
                        ndef[1] = 0
                    elif styledef == 'italic':
                        ndef[2] = 1
                    elif styledef == 'noitalic':
                        ndef[2] = 0
                    elif styledef == 'underline':
                        ndef[3] = 1
                    elif styledef == 'nounderline':
                        ndef[3] = 0
                    elif styledef[:3] == 'bg:':
                        ndef[4] = colorformat(styledef[3:])
                    elif styledef[:7] == 'border:':
                        ndef[5] = colorformat(styledef[7:])
                    elif styledef == 'roman':
                        ndef[6] = 1
                    elif styledef == 'sans':
                        ndef[7] = 1
                    elif styledef == 'mono':
                        ndef[8] = 1
                    else:
                        ndef[0] = colorformat(styledef)
        return obj
Referenced by apscheduler.triggers.combining.BaseCombiningTrigger.__setstate__(), pip._vendor.rich.style.Style._add(), pip._vendor.rich.style.Style.clear_meta_and_links(), yaml.constructor.SafeConstructor.construct_yaml_object(), pip._vendor.rich.style.Style.copy(), pip._vendor.rich.style.Style.from_color(), pip._vendor.rich.json.JSON.from_data(), pip._vendor.rich.style.Style.from_meta(), yaml.constructor.FullConstructor.make_python_instance(), pip._vendor.rich.style.Style.update_link(), and pip._vendor.rich.style.Style.without_color().
list_styles()
pip._vendor.pygments.style.StyleMeta.list_styles (cls)
Definition at line 156 of file style.py.
    def list_styles(cls):
        return list(cls)
style_for_token()
pip._vendor.pygments.style.StyleMeta.style_for_token (cls, token)
Definition at line 126 of file style.py.
    def style_for_token(cls, token):
        t = cls._styles[token]
        ansicolor = bgansicolor = None
        color = t[0]
        if color in _deprecated_ansicolors:
            color = _deprecated_ansicolors[color]
        if color in ansicolors:
            ansicolor = color
            color = _ansimap[color]
        bgcolor = t[4]
        if bgcolor in _deprecated_ansicolors:
            bgcolor = _deprecated_ansicolors[bgcolor]
        if bgcolor in ansicolors:
            bgansicolor = bgcolor
            bgcolor = _ansimap[bgcolor]
        return {
            'color':        color or None,
            'bold':         bool(t[1]),
            'italic':       bool(t[2]),
            'underline':    bool(t[3]),
            'bgcolor':      bgcolor or None,
            'border':       t[5] or None,
            'roman':        bool(t[6]) or None,
            'sans':         bool(t[7]) or None,
            'mono':         bool(t[8]) or None,
            'ansicolor':    ansicolor,
            'bgansicolor':  bgansicolor,
        }
References _styles.
styles_token()
pip._vendor.pygments.style.StyleMeta.styles_token (cls, ttype)
Definition at line 159 of file style.py.
    def styles_token(cls, ttype):
        return ttype in cls._styles
References _styles.
Member Data Documentation
_styles
pip._vendor.pygments.style.StyleMeta._styles protected
Definition at line 163 of file style.py.
Referenced by __len__(), style_for_token(), and styles_token().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/pygments/style.py