Read&Watch: pip._vendor.distlib.util.Configurator Class Reference
pip._vendor.distlib.util.Configurator Class Reference
Public Member Functions
__init__ (self, config, base=None)
configure_custom (self, config)
__getitem__ (self, key)
inc_convert (self, value)
Public Member Functions inherited from pip._vendor.distlib.compat.BaseConfigurator
__init__ (self, config)
resolve (self, s)
ext_convert (self, value)
cfg_convert (self, value)
convert (self, value)
as_tuple (self, value)
Public Attributes
base = base or os.getcwd()
Public Attributes inherited from pip._vendor.distlib.compat.BaseConfigurator
config = ConvertingDict(config)
Additional Inherited Members
Static Public Attributes inherited from pip._vendor.distlib.compat.BaseConfigurator
CONVERT_PATTERN = re.compile(r'^(?P<prefix>[a-z]+)://(?P<suffix>.*)$')
WORD_PATTERN = re.compile(r'^\s*(\w+)\s*')
DOT_PATTERN = re.compile(r'^\.\s*(\w+)\s*')
INDEX_PATTERN = re.compile(r'^\[\s*(\w+)\s*\]\s*')
DIGIT_PATTERN = re.compile(r'^\d+$')
dict value_converters
importer = staticmethod(__import__)
Detailed Description
Definition at line 1675 of file util.py.
Constructor & Destructor Documentation
__init__()
pip._vendor.distlib.util.Configurator.__init__ (self, config, base = None)
Definition at line 1680 of file util.py.
    def __init__(self, config, base=None):
        super(Configurator, self).__init__(config)
        self.base = base or os.getcwd()
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
__getitem__()
pip._vendor.distlib.util.Configurator.__getitem__ (self, key)
Definition at line 1716 of file util.py.
    def __getitem__(self, key):
        result = self.config[key]
        if isinstance(result, dict) and '()' in result:
            self.config[key] = result = self.configure_custom(result)
        return result
configure_custom()
pip._vendor.distlib.util.Configurator.configure_custom (self, config)
Configure an object with a user-supplied factory.
Reimplemented from pip._vendor.distlib.compat.BaseConfigurator.
Definition at line 1684 of file util.py.
    def configure_custom(self, config):
        def convert(o):
            if isinstance(o, (list, tuple)):
                result = type(o)([convert(i) for i in o])
            elif isinstance(o, dict):
                if '()' in o:
                    result = self.configure_custom(o)
                else:
                    result = {}
                    for k in o:
                        result[k] = convert(o[k])
            else:
                result = self.convert(o)
            return result
        c = config.pop('()')
        if not callable(c):
            c = self.resolve(c)
        props = config.pop('.', None)
        # Check for valid identifiers
        args = config.pop('[]', ())
        if args:
            args = tuple([convert(o) for o in args])
        items = [(k, convert(config[k])) for k in config if valid_ident(k)]
        kwargs = dict(items)
        result = c(*args, **kwargs)
        if props:
            for n, v in props.items():
                setattr(result, n, convert(v))
        return result
inc_convert()
pip._vendor.distlib.util.Configurator.inc_convert (self, value)
Default converter for the inc:// protocol.
Definition at line 1722 of file util.py.
    def inc_convert(self, value):
        """Default converter for the inc:// protocol."""
        if not os.path.isabs(value):
            value = os.path.join(self.base, value)
        with codecs.open(value, 'r', encoding='utf-8') as f:
            result = json.load(f)
        return result
Member Data Documentation
base
pip._vendor.distlib.util.Configurator.base = base or os.getcwd()
Definition at line 1682 of file util.py.
Referenced by pylint.testutils.functional.test_file.FunctionalTestFile._file_type(), and pylint.testutils.functional.test_file.FunctionalTestFile.module().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/distlib/util.py