Read&Watch: isort.exceptions.IntroducedSyntaxErrors Class Reference
isort.exceptions.IntroducedSyntaxErrors Class Reference
Public Member Functions
__init__ (self, str file_path)
Public Member Functions inherited from isort.exceptions.ISortError
__reduce__ (self)
Public Attributes
file_path = file_path
Detailed Description
Raised when isort has introduced a syntax error in the process of sorting imports
Definition at line 40 of file exceptions.py.
Constructor & Destructor Documentation
__init__()
isort.exceptions.IntroducedSyntaxErrors.__init__ (self, str file_path)
Definition at line 43 of file exceptions.py.
    def __init__(self, file_path: str):
        super().__init__(
            f"isort introduced syntax errors when attempting to sort the imports contained within "
            f"{file_path}."
        )
        self.file_path = file_path
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Data Documentation
file_path
isort.exceptions.IntroducedSyntaxErrors.file_path = file_path
Definition at line 48 of file exceptions.py.
Referenced by django.contrib.staticfiles.handlers.StaticFilesHandlerMixin.serve(), and django.test.testcases.FSFilesHandler.serve().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/isort/exceptions.py