Read&Watch: pip._vendor.pygments.formatters.other.RawTokenFormatter Class Reference
pip._vendor.pygments.formatters.other.RawTokenFormatter Class Reference
Public Member Functions
__init__ (self, **options)
format (self, tokensource, outfile)
Public Member Functions inherited from pip._vendor.pygments.formatter.Formatter
__init__ (self, **options)
get_style_defs (self, arg='')
__class_getitem__ (cls, name)
Public Attributes
str compress
str error_color = options.get('error_color', None)
Public Attributes inherited from pip._vendor.pygments.formatter.Formatter
style = _lookup_style(options.get('style', 'default'))
full = get_bool_opt(options, 'full', False)
title = options.get('title', '')
str encoding = options.get('encoding', None) or None
options = options
Additional Inherited Members
Static Public Attributes inherited from pip._vendor.pygments.formatter.Formatter
name = None
list aliases = []
list filenames = []
bool unicodeoutput = True
Detailed Description
Format tokens as a raw representation for storing token streams.
The format is ``tokentype<TAB>repr(tokenstring)\n``. The output can later
be converted to a token stream with the `RawTokenLexer`, described in the
:doc:`lexer list <lexers>`.
Only two options are accepted:
`compress`
    If set to ``'gz'`` or ``'bz2'``, compress the output with the given
    compression algorithm after encoding (default: ``''``).
`error_color`
    If set to a color name, highlight error tokens using that color.  If
    set but with no value, defaults to ``'red'``.
    .. versionadded:: 0.11
Definition at line 36 of file other.py.
Constructor & Destructor Documentation
__init__()
pip._vendor.pygments.formatters.other.RawTokenFormatter.__init__ (self, ** options)
Definition at line 62 of file other.py.
    def __init__(self, **options):
        Formatter.__init__(self, **options)
        # We ignore self.encoding if it is set, since it gets set for lexer
        # and formatter if given with -Oencoding on the command line.
        # The RawTokenFormatter outputs only ASCII. Override here.
        self.encoding = 'ascii'  # let pygments.format() do the right thing
        self.compress = get_choice_opt(options, 'compress',
                                       ['', 'none', 'gz', 'bz2'], '')
        self.error_color = options.get('error_color', None)
        if self.error_color is True:
            self.error_color = 'red'
        if self.error_color is not None:
            try:
                colorize(self.error_color, '')
            except KeyError:
                raise ValueError(f"Invalid color {self.error_color!r} specified")
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
format()
pip._vendor.pygments.formatters.other.RawTokenFormatter.format (self, tokensource, outfile)
This method must format the tokens from the `tokensource` iterable and
write the formatted version to the file object `outfile`.
Formatter options can control how exactly the tokens are converted.
Reimplemented from pip._vendor.pygments.formatter.Formatter.
Definition at line 79 of file other.py.
    def format(self, tokensource, outfile):
        try:
            outfile.write(b'')
        except TypeError:
            raise TypeError('The raw tokens formatter needs a binary '
                            'output file')
        if self.compress == 'gz':
            import gzip
            outfile = gzip.GzipFile('', 'wb', 9, outfile)
            write = outfile.write
            flush = outfile.close
        elif self.compress == 'bz2':
            import bz2
            compressor = bz2.BZ2Compressor(9)
            def write(text):
                outfile.write(compressor.compress(text))
            def flush():
                outfile.write(compressor.flush())
                outfile.flush()
        else:
            write = outfile.write
            flush = outfile.flush
        if self.error_color:
            for ttype, value in tokensource:
                line = b"%r\t%r\n" % (ttype, value)
                if ttype is Token.Error:
                    write(colorize(self.error_color, line))
                else:
                    write(line)
        else:
            for ttype, value in tokensource:
                write(b"%r\t%r\n" % (ttype, value))
        flush()
References compress, and error_color.
Referenced by django.utils.log.AdminEmailHandler.emit(), pip._internal.utils.logging.RichPipStreamHandler.emit(), and pip._vendor.rich.logging.RichHandler.emit().
Member Data Documentation
compress
str pip._vendor.pygments.formatters.other.RawTokenFormatter.compress
Initial value:
=  get_choice_opt(options, 'compress',
                                       ['', 'none', 'gz', 'bz2'], '')
Definition at line 68 of file other.py.
Referenced by format().
error_color
pip._vendor.pygments.formatters.other.RawTokenFormatter.error_color = options.get('error_color', None)
Definition at line 70 of file other.py.
Referenced by format().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/pip/_vendor/pygments/formatters/other.py