Read&Watch: django.contrib.messages.storage.fallback.FallbackStorage Class Reference
django.contrib.messages.storage.fallback.FallbackStorage Class Reference
Public Member Functions
__init__ (self, *args, **kwargs)
Public Member Functions inherited from django.contrib.messages.storage.base.BaseStorage
__init__ (self, request, *args, **kwargs)
__len__ (self)
__iter__ (self)
__contains__ (self, item)
__repr__ (self)
update (self, response)
add (self, level, message, extra_tags="")
Public Attributes
list storages
Public Attributes inherited from django.contrib.messages.storage.base.BaseStorage
request = request
bool used = False
bool added_new = False
Static Public Attributes
tuple storage_classes = (CookieStorage, SessionStorage)
Protected Member Functions
_get (self, *args, **kwargs)
_store (self, messages, response, *args, **kwargs)
Protected Member Functions inherited from django.contrib.messages.storage.base.BaseStorage
_loaded_messages (self)
_prepare_messages (self, messages)
_get_level (self)
_set_level (self, value=None)
Protected Attributes
_used_storages = set()
Protected Attributes inherited from django.contrib.messages.storage.base.BaseStorage
list _queued_messages = []
_loaded_messages = []
_loaded_data = messages or []
_level = getattr(settings, "MESSAGE_LEVEL", constants.INFO)
Additional Inherited Members
Properties inherited from django.contrib.messages.storage.base.BaseStorage
level = property(_get_level, _set_level, _set_level)
Detailed Description
Try to store all messages in the first backend. Store any unstored
messages in each subsequent backend.
Definition at line 6 of file fallback.py.
Constructor & Destructor Documentation
__init__()
django.contrib.messages.storage.fallback.FallbackStorage.__init__ (self, * args, ** kwargs)
Definition at line 14 of file fallback.py.
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.storages = [
            storage_class(*args, **kwargs) for storage_class in self.storage_classes
        ]
        self._used_storages = set()
References __init__().
Referenced by pip._vendor.typing_extensions.deprecated.__call__(), and __init__().
Member Function Documentation
_get()
django.contrib.messages.storage.fallback.FallbackStorage._get (self, * args, ** kwargs) protected
Get a single list of messages from all storage backends.
Reimplemented from django.contrib.messages.storage.base.BaseStorage.
Definition at line 21 of file fallback.py.
    def _get(self, *args, **kwargs):
        """
        Get a single list of messages from all storage backends.
        """
        all_messages = []
        for storage in self.storages:
            messages, all_retrieved = storage._get()
            # If the backend hasn't been used, no more retrieval is necessary.
            if messages is None:
                break
            if messages:
                self._used_storages.add(storage)
            all_messages.extend(messages)
            # If this storage class contained all the messages, no further
            # retrieval is necessary
            if all_retrieved:
                break
        return all_messages, all_retrieved
References _used_storages, django.contrib.messages.storage.base.BaseStorage.add(), and storages.
Referenced by django.contrib.sitemaps.Sitemap._location(), and django.contrib.sitemaps.Sitemap._urls().
_store()
django.contrib.messages.storage.fallback.FallbackStorage._store (self, messages, response, * args, ** kwargs) protected
Store the messages and return any unstored messages after trying all
backends.
For each storage backend, any messages not stored are passed on to the
next backend.
Reimplemented from django.contrib.messages.storage.base.BaseStorage.
Definition at line 40 of file fallback.py.
    def _store(self, messages, response, *args, **kwargs):
        """
        Store the messages and return any unstored messages after trying all
        backends.
        For each storage backend, any messages not stored are passed on to the
        next backend.
        """
        for storage in self.storages:
            if messages:
                messages = storage._store(messages, response, remove_oldest=False)
            # Even if there are no more messages, continue iterating to ensure
            # storages which contained messages are flushed.
            elif storage in self._used_storages:
                storage._store([], response)
                self._used_storages.remove(storage)
        return messages
References _used_storages, and storages.
Member Data Documentation
_used_storages
django.contrib.messages.storage.fallback.FallbackStorage._used_storages = set() protected
Definition at line 19 of file fallback.py.
Referenced by _get(), and _store().
storage_classes
tuple django.contrib.messages.storage.fallback.FallbackStorage.storage_classes = (CookieStorage, SessionStorage) static
Definition at line 12 of file fallback.py.
storages
list django.contrib.messages.storage.fallback.FallbackStorage.storages
Initial value:
=  [
            storage_class(*args, **kwargs) for storage_class in self.storage_classes
        ]
Definition at line 16 of file fallback.py.
Referenced by _get(), _store(), django.contrib.staticfiles.finders.AppDirectoriesFinder.find(), django.contrib.staticfiles.finders.AppDirectoriesFinder.find_in_app(), django.contrib.staticfiles.finders.AppDirectoriesFinder.list(), and django.contrib.staticfiles.finders.FileSystemFinder.list().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/django/contrib/messages/storage/fallback.py