Read&Watch: PIL.PngImagePlugin.PngInfo Class Reference
PIL.PngImagePlugin.PngInfo Class Reference
Public Member Functions
None __init__ (self)
None add (self, bytes cid, bytes data, bool after_idat=False)
None add_itxt (self, str|bytes key, str|bytes value, str|bytes lang="", str|bytes tkey="", bool zip=False)
None add_text (self, str|bytes key, str|bytes|iTXt value, bool zip=False)
Public Attributes
list chunks = []
Detailed Description
PNG chunk container (for use with save(pnginfo=))
Definition at line 277 of file PngImagePlugin.py.
Constructor & Destructor Documentation
__init__()
None PIL.PngImagePlugin.PngInfo.__init__ (self)
Definition at line 283 of file PngImagePlugin.py.
    def __init__(self) -> None:
        self.chunks: list[tuple[bytes, bytes, bool]] = []
Referenced by pip._vendor.typing_extensions.deprecated.__call__().
Member Function Documentation
add()
None PIL.PngImagePlugin.PngInfo.add (self, bytes cid, bytes data, bool after_idat = False)
Appends an arbitrary chunk. Use with caution.
:param cid: a byte string, 4 bytes long.
:param data: a byte string of the encoded data
:param after_idat: for use with private chunks. Whether the chunk
                   should be written after IDAT
Definition at line 286 of file PngImagePlugin.py.
    def add(self, cid: bytes, data: bytes, after_idat: bool = False) -> None:
        """Appends an arbitrary chunk. Use with caution.
        :param cid: a byte string, 4 bytes long.
        :param data: a byte string of the encoded data
        :param after_idat: for use with private chunks. Whether the chunk
                           should be written after IDAT
        """
        self.chunks.append((cid, data, after_idat))
Referenced by responses.RequestsMock._add_from_file(), pip._internal.req.req_uninstall.UninstallPathSet.add(), pip._vendor.distlib.manifest.Manifest.add_many(), pip._vendor.urllib3._collections.HTTPHeaderDict.extend(), urllib3._collections.HTTPHeaderDict.extend(), pip._internal.operations.build.build_tracker.BuildTracker.track(), and responses.RequestsMock.upsert().
add_itxt()
None PIL.PngImagePlugin.PngInfo.add_itxt (self, str | bytes key, str | bytes value, str | bytes lang = "", str | bytes tkey = "", bool zip = False)
Appends an iTXt chunk.
:param key: latin-1 encodable text key name
:param value: value for this key
:param lang: language code
:param tkey: UTF-8 version of the key name
:param zip: compression flag
Definition at line 298 of file PngImagePlugin.py.
    ) -> None:
        """Appends an iTXt chunk.
        :param key: latin-1 encodable text key name
        :param value: value for this key
        :param lang: language code
        :param tkey: UTF-8 version of the key name
        :param zip: compression flag
        """
        if not isinstance(key, bytes):
            key = key.encode("latin-1", "strict")
        if not isinstance(value, bytes):
            value = value.encode("utf-8", "strict")
        if not isinstance(lang, bytes):
            lang = lang.encode("utf-8", "strict")
        if not isinstance(tkey, bytes):
            tkey = tkey.encode("utf-8", "strict")
        if zip:
            self.add(
                b"iTXt",
                key + b"\0\x01\0" + lang + b"\0" + tkey + b"\0" + zlib.compress(value),
            )
        else:
            self.add(b"iTXt", key + b"\0\0\0" + lang + b"\0" + tkey + b"\0" + value)
add_text()
None PIL.PngImagePlugin.PngInfo.add_text (self, str | bytes key, str | bytes | iTXt value, bool zip = False)
Appends a text chunk.
:param key: latin-1 encodable text key name
:param value: value for this key, text or an
   :py:class:`PIL.PngImagePlugin.iTXt` instance
:param zip: compression flag
Definition at line 333 of file PngImagePlugin.py.
    ) -> None:
        """Appends a text chunk.
        :param key: latin-1 encodable text key name
        :param value: value for this key, text or an
           :py:class:`PIL.PngImagePlugin.iTXt` instance
        :param zip: compression flag
        """
        if isinstance(value, iTXt):
            return self.add_itxt(
                key,
                value,
                value.lang if value.lang is not None else b"",
                value.tkey if value.tkey is not None else b"",
                zip=zip,
            )
        # The tEXt chunk stores latin-1 text
        if not isinstance(value, bytes):
            try:
                value = value.encode("latin-1", "strict")
            except UnicodeError:
                return self.add_itxt(key, value, zip=zip)
        if not isinstance(key, bytes):
            key = key.encode("latin-1", "strict")
        if zip:
            self.add(b"zTXt", key + b"\0\0" + zlib.compress(value))
        else:
            self.add(b"tEXt", key + b"\0" + value)
# --------------------------------------------------------------------
# PNG image stream (IHDR/IEND)
Referenced by pylint.reporters.ureports.nodes.BaseLayout.__init__().
Member Data Documentation
chunks
list PIL.PngImagePlugin.PngInfo.chunks = []
Definition at line 284 of file PngImagePlugin.py.
Referenced by django.core.files.base.File.__iter__().
The documentation for this class was generated from the following file:
project/ENV/Lib/site-packages/PIL/PngImagePlugin.py