Read&Watch: django.contrib.auth.management Namespace Reference
django.contrib.auth.management Namespace Reference
Namespaces
namespace commands
Functions
_get_all_permissions (opts)
_get_builtin_permissions (opts)
create_permissions (app_config, verbosity=2, interactive=True, using=DEFAULT_DB_ALIAS, apps=global_apps, **kwargs)
get_system_username ()
get_default_username (check_db=True, database=DEFAULT_DB_ALIAS)
Detailed Description
Creates permissions for all installed apps that need permissions.
Function Documentation
_get_all_permissions()
django.contrib.auth.management._get_all_permissions (opts) protected
Return (codename, name) for all permissions in the given opts.
Definition at line 15 of file __init__.py.
def _get_all_permissions(opts):
    """
    Return (codename, name) for all permissions in the given opts.
    """
    return [*_get_builtin_permissions(opts), *opts.permissions]
References _get_builtin_permissions().
Referenced by create_permissions().
_get_builtin_permissions()
django.contrib.auth.management._get_builtin_permissions (opts) protected
Return (codename, name) for all autogenerated permissions.
By default, this is ('add', 'change', 'delete', 'view')
Definition at line 22 of file __init__.py.
def _get_builtin_permissions(opts):
    """
    Return (codename, name) for all autogenerated permissions.
    By default, this is ('add', 'change', 'delete', 'view')
    """
    perms = []
    for action in opts.default_permissions:
        perms.append(
            (
                get_permission_codename(action, opts),
                "Can %s %s" % (action, opts.verbose_name_raw),
            )
        )
    return perms
References django.contrib.auth.get_permission_codename().
Referenced by _get_all_permissions().
create_permissions()
django.contrib.auth.management.create_permissions (app_config, verbosity = 2, interactive = True, using = DEFAULT_DB_ALIAS, apps = global_apps, ** kwargs)
Definition at line 38 of file __init__.py.
):
    if not app_config.models_module:
        return
    try:
        Permission = apps.get_model("auth", "Permission")
    except LookupError:
        return
    if not router.allow_migrate_model(using, Permission):
        return
    # Ensure that contenttypes are created for this app. Needed if
    # 'django.contrib.auth' is in INSTALLED_APPS before
    # 'django.contrib.contenttypes'.
    create_contenttypes(
        app_config,
        verbosity=verbosity,
        interactive=interactive,
        using=using,
        apps=apps,
        **kwargs,
    )
    app_label = app_config.label
    try:
        app_config = apps.get_app_config(app_label)
        ContentType = apps.get_model("contenttypes", "ContentType")
    except LookupError:
        return
    models = list(app_config.get_models())
    # Grab all the ContentTypes.
    ctypes = ContentType.objects.db_manager(using).get_for_models(
        *models, for_concrete_models=False
    )
    # Find all the Permissions that have a content_type for a model we're
    # looking for.  We don't need to check for codenames since we already have
    # a list of the ones we're going to create.
    all_perms = set(
        Permission.objects.using(using)
        .filter(
            content_type__in=set(ctypes.values()),
        )
        .values_list("content_type", "codename")
    )
    perms = []
    for model in models:
        ctype = ctypes[model]
        for codename, name in _get_all_permissions(model._meta):
            if (ctype.pk, codename) not in all_perms:
                permission = Permission()
                permission._state.db = using
                permission.codename = codename
                permission.name = name
                permission.content_type = ctype
                perms.append(permission)
    Permission.objects.using(using).bulk_create(perms)
    if verbosity >= 2:
        for perm in perms:
            print("Adding permission '%s'" % perm)
References _get_all_permissions().
get_default_username()
django.contrib.auth.management.get_default_username (check_db = True, database = DEFAULT_DB_ALIAS)
Try to determine the current system user's username to use as a default.
:param check_db: If ``True``, requires that the username does not match an
    existing ``auth.User`` (otherwise returns an empty string).
:param database: The database where the unique check will be performed.
:returns: The username, or an empty string if no username can be
    determined or the suggested username is already taken.
Definition at line 126 of file __init__.py.
def get_default_username(check_db=True, database=DEFAULT_DB_ALIAS):
    """
    Try to determine the current system user's username to use as a default.
    :param check_db: If ``True``, requires that the username does not match an
        existing ``auth.User`` (otherwise returns an empty string).
    :param database: The database where the unique check will be performed.
    :returns: The username, or an empty string if no username can be
        determined or the suggested username is already taken.
    """
    # This file is used in apps.py, it should not trigger models import.
    from django.contrib.auth import models as auth_app
    # If the User model has been swapped out, we can't make any assumptions
    # about the default user name.
    if auth_app.User._meta.swapped:
        return ""
    default_username = get_system_username()
    try:
        default_username = (
            unicodedata.normalize("NFKD", default_username)
            .encode("ascii", "ignore")
            .decode("ascii")
            .replace(" ", "")
            .lower()
        )
    except UnicodeDecodeError:
        return ""
    # Run the username validator
    try:
        auth_app.User._meta.get_field("username").run_validators(default_username)
    except exceptions.ValidationError:
        return ""
    # Don't return the default username if it is already taken.
    if check_db and default_username:
        try:
            auth_app.User._default_manager.db_manager(database).get(
                username=default_username,
            )
        except auth_app.User.DoesNotExist:
            pass
        else:
            return ""
    return default_username
References get_system_username().
Referenced by django.contrib.auth.management.commands.createsuperuser.Command.handle().
get_system_username()
django.contrib.auth.management.get_system_username ()
Return the current system user's username, or an empty string if the
username could not be determined.
Definition at line 111 of file __init__.py.
def get_system_username():
    """
    Return the current system user's username, or an empty string if the
    username could not be determined.
    """
    try:
        result = getpass.getuser()
    except (ImportError, KeyError):
        # KeyError will be raised by os.getpwuid() (called by getuser())
        # if there is no corresponding entry in the /etc/passwd file
        # (a very restricted chroot environment, for example).
        return ""
    return result
Referenced by get_default_username().