Read&Watch: urllib3.contrib.pyopenssl Namespace Reference
urllib3.contrib.pyopenssl Namespace Reference
Classes
class PyOpenSSLContext
class UnsupportedExtension
class WrappedSocket
Functions
None inject_into_urllib3 ()
None extract_from_urllib3 ()
None _validate_dependencies_met ()
str|None _dnsname_to_stdlib (str name)
list[tuple[str, str]] get_subj_alt_name (X509 peer_cert)
bool _verify_callback (OpenSSL.SSL.Connection cnx, X509 x509, int err_no, int err_depth, int return_code)
Variables
dict _openssl_versions
dict _stdlib_to_openssl_verify
dict _openssl_to_stdlib_verify = {v: k for k, v in _stdlib_to_openssl_verify.items()}
int _OP_NO_SSLv2_OR_SSLv3
int _OP_NO_TLSv1 = getattr(OpenSSL.SSL, "OP_NO_TLSv1", 0)
int _OP_NO_TLSv1_1 = getattr(OpenSSL.SSL, "OP_NO_TLSv1_1", 0)
int _OP_NO_TLSv1_2 = getattr(OpenSSL.SSL, "OP_NO_TLSv1_2", 0)
int _OP_NO_TLSv1_3 = getattr(OpenSSL.SSL, "OP_NO_TLSv1_3", 0)
dict _openssl_to_ssl_minimum_version
dict _openssl_to_ssl_maximum_version
int SSL_WRITE_BLOCKSIZE = 16384
orig_util_SSLContext = util.ssl_.SSLContext
log = logging.getLogger(__name__)
Detailed Description
Module for using pyOpenSSL as a TLS backend. This module was relevant before
the standard library ``ssl`` module supported SNI, but now that we've dropped
support for Python 2.7 all relevant Python versions support SNI so
**this module is no longer recommended**.
This needs the following packages installed:
* `pyOpenSSL`_ (tested with 16.0.0)
* `cryptography`_ (minimum 1.3.4, from pyopenssl)
* `idna`_ (minimum 2.0)
However, pyOpenSSL depends on cryptography, so while we use all three directly here we
end up having relatively few packages required.
You can install them with the following command:
.. code-block:: bash
    $ python -m pip install pyopenssl cryptography idna
To activate certificate checking, call
:func:`~urllib3.contrib.pyopenssl.inject_into_urllib3` from your Python code
before you begin making HTTP requests. This can be done in a ``sitecustomize``
module, or at any other time before your application begins using ``urllib3``,
like this:
.. code-block:: python
    try:
        import urllib3.contrib.pyopenssl
        urllib3.contrib.pyopenssl.inject_into_urllib3()
    except ImportError:
        pass
.. _pyopenssl: https://www.pyopenssl.org
.. _cryptography: https://cryptography.io
.. _idna: https://github.com/kjd/idna
Function Documentation
_dnsname_to_stdlib()
str | None urllib3.contrib.pyopenssl._dnsname_to_stdlib (str name) protected
Converts a dNSName SubjectAlternativeName field to the form used by the
standard library on the given Python version.
Cryptography produces a dNSName as a unicode string that was idna-decoded
from ASCII bytes. We need to idna-encode that string to get it back, and
then on Python 3 we also need to convert to unicode via UTF-8 (the stdlib
uses PyUnicode_FromStringAndSize on it, which decodes via UTF-8).
If the name cannot be idna-encoded then we return None signalling that
the name given should be skipped.
Definition at line 185 of file pyopenssl.py.
def _dnsname_to_stdlib(name: str) -> str | None:
    """
    Converts a dNSName SubjectAlternativeName field to the form used by the
    standard library on the given Python version.
    Cryptography produces a dNSName as a unicode string that was idna-decoded
    from ASCII bytes. We need to idna-encode that string to get it back, and
    then on Python 3 we also need to convert to unicode via UTF-8 (the stdlib
    uses PyUnicode_FromStringAndSize on it, which decodes via UTF-8).
    If the name cannot be idna-encoded then we return None signalling that
    the name given should be skipped.
    """
    def idna_encode(name: str) -> bytes | None:
        """
        Borrowed wholesale from the Python Cryptography Project. It turns out
        that we can't just safely call `idna.encode`: it can explode for
        wildcard names. This avoids that problem.
        """
        import idna
        try:
            for prefix in ["*.", "."]:
                if name.startswith(prefix):
                    name = name[len(prefix) :]
                    return prefix.encode("ascii") + idna.encode(name)
            return idna.encode(name)
        except idna.core.IDNAError:
            return None
    # Don't send IPv6 addresses through the IDNA encoder.
    if ":" in name:
        return name
    encoded_name = idna_encode(name)
    if encoded_name is None:
        return None
    return encoded_name.decode("utf-8")
_validate_dependencies_met()
None urllib3.contrib.pyopenssl._validate_dependencies_met () protected
Verifies that PyOpenSSL's package-level dependencies have been met.
Throws `ImportError` if they are not met.
Definition at line 159 of file pyopenssl.py.
def _validate_dependencies_met() -> None:
    """
    Verifies that PyOpenSSL's package-level dependencies have been met.
    Throws `ImportError` if they are not met.
    """
    # Method added in `cryptography==1.1`; not available in older versions
    from cryptography.x509.extensions import Extensions
    if getattr(Extensions, "get_extension_for_class", None) is None:
        raise ImportError(
            "'cryptography' module missing required functionality.  "
            "Try upgrading to v1.3.4 or newer."
        )
    # pyOpenSSL 0.14 and above use cryptography for OpenSSL bindings. The _x509
    # attribute is only present on those versions.
    from OpenSSL.crypto import X509
    x509 = X509()
    if getattr(x509, "_x509", None) is None:
        raise ImportError(
            "'pyOpenSSL' module missing required functionality. "
            "Try upgrading to v0.14 or newer."
        )
Referenced by inject_into_urllib3().
_verify_callback()
bool urllib3.contrib.pyopenssl._verify_callback (OpenSSL.SSL.Connection cnx, X509 x509, int err_no, int err_depth, int return_code) protected
Definition at line 545 of file pyopenssl.py.
) -> bool:
    return err_no == 0
extract_from_urllib3()
None urllib3.contrib.pyopenssl.extract_from_urllib3 ()
Definition at line 150 of file pyopenssl.py.
def extract_from_urllib3() -> None:
    "Undo monkey-patching by :func:`inject_into_urllib3`."
    util.SSLContext = orig_util_SSLContext
    util.ssl_.SSLContext = orig_util_SSLContext
    util.IS_PYOPENSSL = False
    util.ssl_.IS_PYOPENSSL = False
get_subj_alt_name()
list[tuple[str, str]] urllib3.contrib.pyopenssl.get_subj_alt_name (X509 peer_cert)
Given an PyOpenSSL certificate, provides all the subject alternative names.
Definition at line 226 of file pyopenssl.py.
def get_subj_alt_name(peer_cert: X509) -> list[tuple[str, str]]:
    """
    Given an PyOpenSSL certificate, provides all the subject alternative names.
    """
    cert = peer_cert.to_cryptography()
    # We want to find the SAN extension. Ask Cryptography to locate it (it's
    # faster than looping in Python)
    try:
        ext = cert.extensions.get_extension_for_class(x509.SubjectAlternativeName).value
    except x509.ExtensionNotFound:
        # No such extension, return the empty list.
        return []
    except (
        x509.DuplicateExtension,
        UnsupportedExtension,
        x509.UnsupportedGeneralNameType,
        UnicodeError,
    ) as e:
        # A problem has been found with the quality of the certificate. Assume
        # no SAN field is present.
        log.warning(
            "A problem was encountered with the certificate that prevented "
            "urllib3 from finding the SubjectAlternativeName field. This can "
            "affect certificate validation. The error was %s",
            e,
        )
        return []
    # We want to return dNSName and iPAddress fields. We need to cast the IPs
    # back to strings because the match_hostname function wants them as
    # strings.
    # Sadly the DNS names need to be idna encoded and then, on Python 3, UTF-8
    # decoded. This is pretty frustrating, but that's what the standard library
    # does with certificates, and so we need to attempt to do the same.
    # We also want to skip over names which cannot be idna encoded.
    names = [
        ("DNS", name)
        for name in map(_dnsname_to_stdlib, ext.get_values_for_type(x509.DNSName))
        if name is not None
    ]
    names.extend(
        ("IP Address", str(name)) for name in ext.get_values_for_type(x509.IPAddress)
    )
    return names
Referenced by urllib3.contrib.pyopenssl.WrappedSocket.getpeercert().
inject_into_urllib3()
None urllib3.contrib.pyopenssl.inject_into_urllib3 ()
Definition at line 139 of file pyopenssl.py.
def inject_into_urllib3() -> None:
    "Monkey-patch urllib3 with PyOpenSSL-backed SSL-support."
    _validate_dependencies_met()
    util.SSLContext = PyOpenSSLContext  # type: ignore[assignment]
    util.ssl_.SSLContext = PyOpenSSLContext  # type: ignore[assignment]
    util.IS_PYOPENSSL = True
    util.ssl_.IS_PYOPENSSL = True
References _validate_dependencies_met().
Variable Documentation
_OP_NO_SSLv2_OR_SSLv3
int urllib3.contrib.pyopenssl._OP_NO_SSLv2_OR_SSLv3 protected
Initial value:
=  getattr(OpenSSL.SSL, "OP_NO_SSLv2", 0) | getattr(
    OpenSSL.SSL, "OP_NO_SSLv3", 0
)
Definition at line 93 of file pyopenssl.py.
_OP_NO_TLSv1
int urllib3.contrib.pyopenssl._OP_NO_TLSv1 = getattr(OpenSSL.SSL, "OP_NO_TLSv1", 0) protected
Definition at line 96 of file pyopenssl.py.
_OP_NO_TLSv1_1
int urllib3.contrib.pyopenssl._OP_NO_TLSv1_1 = getattr(OpenSSL.SSL, "OP_NO_TLSv1_1", 0) protected
Definition at line 97 of file pyopenssl.py.
_OP_NO_TLSv1_2
int urllib3.contrib.pyopenssl._OP_NO_TLSv1_2 = getattr(OpenSSL.SSL, "OP_NO_TLSv1_2", 0) protected
Definition at line 98 of file pyopenssl.py.
_OP_NO_TLSv1_3
int urllib3.contrib.pyopenssl._OP_NO_TLSv1_3 = getattr(OpenSSL.SSL, "OP_NO_TLSv1_3", 0) protected
Definition at line 99 of file pyopenssl.py.
_openssl_to_ssl_maximum_version
dict urllib3.contrib.pyopenssl._openssl_to_ssl_maximum_version protected
Initial value:
=  {
    ssl.TLSVersion.MINIMUM_SUPPORTED: (
        _OP_NO_SSLv2_OR_SSLv3
        | _OP_NO_TLSv1
        | _OP_NO_TLSv1_1
        | _OP_NO_TLSv1_2
        | _OP_NO_TLSv1_3
    ),
    ssl.TLSVersion.TLSv1: (
        _OP_NO_SSLv2_OR_SSLv3 | _OP_NO_TLSv1_1 | _OP_NO_TLSv1_2 | _OP_NO_TLSv1_3
    ),
    ssl.TLSVersion.TLSv1_1: _OP_NO_SSLv2_OR_SSLv3 | _OP_NO_TLSv1_2 | _OP_NO_TLSv1_3,
    ssl.TLSVersion.TLSv1_2: _OP_NO_SSLv2_OR_SSLv3 | _OP_NO_TLSv1_3,
    ssl.TLSVersion.TLSv1_3: _OP_NO_SSLv2_OR_SSLv3,
    ssl.TLSVersion.MAXIMUM_SUPPORTED: _OP_NO_SSLv2_OR_SSLv3,
}
Definition at line 113 of file pyopenssl.py.
_openssl_to_ssl_minimum_version
dict urllib3.contrib.pyopenssl._openssl_to_ssl_minimum_version protected
Initial value:
=  {
    ssl.TLSVersion.MINIMUM_SUPPORTED: _OP_NO_SSLv2_OR_SSLv3,
    ssl.TLSVersion.TLSv1: _OP_NO_SSLv2_OR_SSLv3,
    ssl.TLSVersion.TLSv1_1: _OP_NO_SSLv2_OR_SSLv3 | _OP_NO_TLSv1,
    ssl.TLSVersion.TLSv1_2: _OP_NO_SSLv2_OR_SSLv3 | _OP_NO_TLSv1 | _OP_NO_TLSv1_1,
    ssl.TLSVersion.TLSv1_3: (
        _OP_NO_SSLv2_OR_SSLv3 | _OP_NO_TLSv1 | _OP_NO_TLSv1_1 | _OP_NO_TLSv1_2
    ),
    ssl.TLSVersion.MAXIMUM_SUPPORTED: (
        _OP_NO_SSLv2_OR_SSLv3 | _OP_NO_TLSv1 | _OP_NO_TLSv1_1 | _OP_NO_TLSv1_2
    ),
}
Definition at line 101 of file pyopenssl.py.
_openssl_to_stdlib_verify
dict urllib3.contrib.pyopenssl._openssl_to_stdlib_verify = {v: k for k, v in _stdlib_to_openssl_verify.items()} protected
Definition at line 89 of file pyopenssl.py.
_openssl_versions
dict urllib3.contrib.pyopenssl._openssl_versions protected
Initial value:
=  {
    util.ssl_.PROTOCOL_TLS: OpenSSL.SSL.SSLv23_METHOD,  # type: ignore[attr-defined]
    util.ssl_.PROTOCOL_TLS_CLIENT: OpenSSL.SSL.SSLv23_METHOD,  # type: ignore[attr-defined]
    ssl.PROTOCOL_TLSv1: OpenSSL.SSL.TLSv1_METHOD,
}
Definition at line 70 of file pyopenssl.py.
_stdlib_to_openssl_verify
dict urllib3.contrib.pyopenssl._stdlib_to_openssl_verify protected
Initial value:
=  {
    ssl.CERT_NONE: OpenSSL.SSL.VERIFY_NONE,
    ssl.CERT_OPTIONAL: OpenSSL.SSL.VERIFY_PEER,
    ssl.CERT_REQUIRED: OpenSSL.SSL.VERIFY_PEER
    + OpenSSL.SSL.VERIFY_FAIL_IF_NO_PEER_CERT,
}
Definition at line 83 of file pyopenssl.py.
log
urllib3.contrib.pyopenssl.log = logging.getLogger(__name__)
Definition at line 136 of file pyopenssl.py.
orig_util_SSLContext
urllib3.contrib.pyopenssl.orig_util_SSLContext = util.ssl_.SSLContext
Definition at line 133 of file pyopenssl.py.
SSL_WRITE_BLOCKSIZE
int urllib3.contrib.pyopenssl.SSL_WRITE_BLOCKSIZE = 16384
Definition at line 131 of file pyopenssl.py.