Read&Watch: dill.tests.test_extendpickle Namespace Reference
dill.tests.test_extendpickle Namespace Reference
Functions
my_fn (x)
test_extend ()
test_isdill ()
Function Documentation
my_fn()
dill.tests.test_extendpickle.my_fn (x)
Definition at line 13 of file test_extendpickle.py.
def my_fn(x):
    return x * 17
Referenced by test_extend().
test_extend()
dill.tests.test_extendpickle.test_extend ()
Definition at line 17 of file test_extendpickle.py.
def test_extend():
    obj = lambda : my_fn(34)
    assert obj() == 578
    obj_io = StringIO()
    pickler = pickle.Pickler(obj_io)
    pickler.dump(obj)
    obj_str = obj_io.getvalue()
    obj2_io = StringIO(obj_str)
    unpickler = pickle.Unpickler(obj2_io)
    obj2 = unpickler.load()
    assert obj2() == 578
References my_fn().
Referenced by test_isdill().
test_isdill()
dill.tests.test_extendpickle.test_isdill ()
Definition at line 34 of file test_extendpickle.py.
def test_isdill():
    obj_io = StringIO()
    pickler = pickle.Pickler(obj_io)
    assert pickle._dill.is_dill(pickler) is True
    pickler = pickle._dill.StockPickler(obj_io)
    assert pickle._dill.is_dill(pickler) is False
    try:
        import multiprocess as mp
        pickler = mp.reduction.ForkingPickler(obj_io)
        assert pickle._dill.is_dill(pickler, child=True) is True
        assert pickle._dill.is_dill(pickler, child=False) is False
    except Exception:
        pass
References test_extend(), and test_isdill().
Referenced by test_isdill().