Read&Watch: django.template.autoreload Namespace Reference
django.template.autoreload Namespace Reference
Functions
get_template_directories ()
reset_loaders ()
watch_for_template_changes (sender, **kwargs)
template_changed (sender, file_path, **kwargs)
Function Documentation
get_template_directories()
django.template.autoreload.get_template_directories ()
Definition at line 10 of file autoreload.py.
def get_template_directories():
    # Iterate through each template backend and find
    # any template_loader that has a 'get_dirs' method.
    # Collect the directories, filtering out Django templates.
    cwd = Path.cwd()
    items = set()
    for backend in engines.all():
        if not isinstance(backend, DjangoTemplates):
            continue
        items.update(cwd / to_path(dir) for dir in backend.engine.dirs if dir)
        for loader in backend.engine.template_loaders:
            if not hasattr(loader, "get_dirs"):
                continue
            items.update(
                cwd / to_path(directory)
                for directory in loader.get_dirs()
                if directory and not is_django_path(directory)
            )
    return items
Referenced by template_changed(), and watch_for_template_changes().
reset_loaders()
django.template.autoreload.reset_loaders ()
Definition at line 33 of file autoreload.py.
def reset_loaders():
    from django.forms.renderers import get_default_renderer
    for backend in engines.all():
        if not isinstance(backend, DjangoTemplates):
            continue
        for loader in backend.engine.template_loaders:
            loader.reset()
    backend = getattr(get_default_renderer(), "engine", None)
    if isinstance(backend, DjangoTemplates):
        for loader in backend.engine.template_loaders:
            loader.reset()
@receiver(autoreload_started, dispatch_uid="template_loaders_watch_changes")
Referenced by template_changed().
template_changed()
django.template.autoreload.template_changed (sender, file_path, ** kwargs)
Definition at line 55 of file autoreload.py.
def template_changed(sender, file_path, **kwargs):
    if file_path.suffix == ".py":
        return
    for template_dir in get_template_directories():
        if template_dir in file_path.parents:
            reset_loaders()
            return True
References get_template_directories(), and reset_loaders().
watch_for_template_changes()
django.template.autoreload.watch_for_template_changes (sender, ** kwargs)
Definition at line 49 of file autoreload.py.
def watch_for_template_changes(sender, **kwargs):
    for directory in get_template_directories():
        sender.watch_dir(directory, "**/*")
@receiver(file_changed, dispatch_uid="template_loaders_file_changed")
References get_template_directories().