Read&Watch: pylint.checkers.logging Namespace Reference
pylint.checkers.logging Namespace Reference
Classes
class LoggingChecker
Functions
bool is_method_call (bases.BoundMethod func, tuple[str,...] types=(), tuple[str,...] methods=())
bool is_complex_format_str (nodes.NodeNG node)
int _count_supplied_tokens (list[nodes.NodeNG] args)
bool str_formatting_in_f_string (nodes.JoinedStr node)
None register (PyLinter linter)
Variables
tuple MSGS
dict CHECKED_CONVENIENCE_FUNCTIONS
MOST_COMMON_FORMATTING = frozenset(["%s", "%d", "%f", "%r"])
Detailed Description
Checker for use of Python logging.
Function Documentation
_count_supplied_tokens()
int pylint.checkers.logging._count_supplied_tokens (list[nodes.NodeNG] args) protected
Counts the number of tokens in an args list.
The Python log functions allow for special keyword arguments: func,
exc_info and extra. To handle these cases correctly, we only count
arguments that aren't keywords.
Args:
  args: AST nodes that are arguments for a log format string.
Returns:
  Number of AST nodes that aren't keywords.
Definition at line 393 of file logging.py.
def _count_supplied_tokens(args: list[nodes.NodeNG]) -> int:
    """Counts the number of tokens in an args list.
    The Python log functions allow for special keyword arguments: func,
    exc_info and extra. To handle these cases correctly, we only count
    arguments that aren't keywords.
    Args:
      args: AST nodes that are arguments for a log format string.
    Returns:
      Number of AST nodes that aren't keywords.
    """
    return sum(1 for arg in args if not isinstance(arg, nodes.Keyword))
Referenced by pylint.checkers.logging.LoggingChecker._check_format_string().
is_complex_format_str()
bool pylint.checkers.logging.is_complex_format_str (nodes.NodeNG node)
Return whether the node represents a string with complex formatting specs.
Definition at line 378 of file logging.py.
def is_complex_format_str(node: nodes.NodeNG) -> bool:
    """Return whether the node represents a string with complex formatting specs."""
    inferred = utils.safe_infer(node)
    if inferred is None or not (
        isinstance(inferred, nodes.Const) and isinstance(inferred.value, str)
    ):
        return True
    try:
        parsed = list(string.Formatter().parse(inferred.value))
    except ValueError:
        # This format string is invalid
        return False
    return any(format_spec for (_, _, format_spec, _) in parsed)
Referenced by pylint.checkers.logging.LoggingChecker._check_call_func().
is_method_call()
bool pylint.checkers.logging.is_method_call (bases.BoundMethod func, tuple[str, ...] types = (), tuple[str, ...] methods = ())
Determines if a BoundMethod node represents a method call.
Args:
  func: The BoundMethod AST node to check.
  types: Optional sequence of caller type names to restrict check.
  methods: Optional sequence of method names to restrict check.
Returns:
  true if the node represents a method call for the given type and
  method names, False otherwise.
Definition at line 106 of file logging.py.
) -> bool:
    """Determines if a BoundMethod node represents a method call.
    Args:
      func: The BoundMethod AST node to check.
      types: Optional sequence of caller type names to restrict check.
      methods: Optional sequence of method names to restrict check.
    Returns:
      true if the node represents a method call for the given type and
      method names, False otherwise.
    """
    return (
        isinstance(func, astroid.BoundMethod)
        and isinstance(func.bound, astroid.Instance)
        and (func.bound.name in types if types else True)
        and (func.name in methods if methods else True)
    )
Referenced by pylint.checkers.logging.LoggingChecker._check_call_func().
register()
None pylint.checkers.logging.register (PyLinter linter)
Definition at line 422 of file logging.py.
def register(linter: PyLinter) -> None:
    linter.register_checker(LoggingChecker(linter))
str_formatting_in_f_string()
bool pylint.checkers.logging.str_formatting_in_f_string (nodes.JoinedStr node)
Determine whether the node represents an f-string with string formatting.
For example: `f'Hello %s'`
Definition at line 409 of file logging.py.
def str_formatting_in_f_string(node: nodes.JoinedStr) -> bool:
    """Determine whether the node represents an f-string with string formatting.
    For example: `f'Hello %s'`
    """
    # Check "%" presence first for performance.
    return any(
        "%" in val.value and any(x in val.value for x in MOST_COMMON_FORMATTING)
        for val in node.values
        if isinstance(val, nodes.Const)
    )
Referenced by pylint.checkers.logging.LoggingChecker._check_log_method().
Variable Documentation
CHECKED_CONVENIENCE_FUNCTIONS
dict pylint.checkers.logging.CHECKED_CONVENIENCE_FUNCTIONS
Initial value:
=  {
    "critical",
    "debug",
    "error",
    "exception",
    "fatal",
    "info",
    "warn",
    "warning",
}
Definition at line 92 of file logging.py.
MOST_COMMON_FORMATTING
pylint.checkers.logging.MOST_COMMON_FORMATTING = frozenset(["%s", "%d", "%f", "%r"])
Definition at line 103 of file logging.py.
MSGS
tuple pylint.checkers.logging.MSGS
Definition at line 25 of file logging.py.