Read&Watch: django.template.loader Namespace Reference
django.template.loader Namespace Reference
Functions
get_template (template_name, using=None)
select_template (template_name_list, using=None)
render_to_string (template_name, context=None, request=None, using=None)
_engine_list (using=None)
Function Documentation
_engine_list()
django.template.loader._engine_list (using = None) protected
Definition at line 65 of file loader.py.
def _engine_list(using=None):
    return engines.all() if using is None else [engines[using]]
Referenced by get_template(), and select_template().
get_template()
django.template.loader.get_template (template_name, using = None)
Load and return a template for the given name.
Raise TemplateDoesNotExist if no such template exists.
Definition at line 5 of file loader.py.
def get_template(template_name, using=None):
    """
    Load and return a template for the given name.
    Raise TemplateDoesNotExist if no such template exists.
    """
    chain = []
    engines = _engine_list(using)
    for engine in engines:
        try:
            return engine.get_template(template_name)
        except TemplateDoesNotExist as e:
            chain.append(e)
    raise TemplateDoesNotExist(template_name, chain=chain)
References _engine_list().
Referenced by render_to_string().
render_to_string()
django.template.loader.render_to_string (template_name, context = None, request = None, using = None)
Load a template and render it with a context. Return a string.
template_name may be a string or a list of strings.
Definition at line 52 of file loader.py.
def render_to_string(template_name, context=None, request=None, using=None):
    """
    Load a template and render it with a context. Return a string.
    template_name may be a string or a list of strings.
    """
    if isinstance(template_name, (list, tuple)):
        template = select_template(template_name, using=using)
    else:
        template = get_template(template_name, using=using)
    return template.render(context, request)
References get_template(), and select_template().
select_template()
django.template.loader.select_template (template_name_list, using = None)
Load and return a template for one of the given names.
Try names in order and return the first template found.
Raise TemplateDoesNotExist if no such template exists.
Definition at line 22 of file loader.py.
def select_template(template_name_list, using=None):
    """
    Load and return a template for one of the given names.
    Try names in order and return the first template found.
    Raise TemplateDoesNotExist if no such template exists.
    """
    if isinstance(template_name_list, str):
        raise TypeError(
            "select_template() takes an iterable of template names but got a "
            "string: %r. Use get_template() if you want to load a single "
            "template by name." % template_name_list
        )
    chain = []
    engines = _engine_list(using)
    for template_name in template_name_list:
        for engine in engines:
            try:
                return engine.get_template(template_name)
            except TemplateDoesNotExist as e:
                chain.append(e)
    if template_name_list:
        raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
    else:
        raise TemplateDoesNotExist("No template names provided")
References _engine_list().
Referenced by render_to_string().