Read&Watch: dill.tests.test_fglobals Namespace Reference
dill.tests.test_fglobals Namespace Reference
Functions
get_fun_with_strftime ()
get_fun_with_strftime2 ()
test_doc_dill_issue_219 ()
get_fun_with_internal_import ()
test_method_with_internal_import_should_work ()
Function Documentation
get_fun_with_internal_import()
dill.tests.test_fglobals.get_fun_with_internal_import ()
Definition at line 32 of file test_fglobals.py.
def get_fun_with_internal_import():
    def fun_with_import():
        import re
        return re.compile("$")
    return fun_with_import
Referenced by test_method_with_internal_import_should_work().
get_fun_with_strftime()
dill.tests.test_fglobals.get_fun_with_strftime ()
Definition at line 11 of file test_fglobals.py.
def get_fun_with_strftime():
    def fun_with_strftime():
        import datetime
        return datetime.datetime.strptime("04-01-1943", "%d-%m-%Y").strftime(
            "%Y-%m-%d %H:%M:%S"
        )
    return fun_with_strftime
Referenced by test_doc_dill_issue_219().
get_fun_with_strftime2()
dill.tests.test_fglobals.get_fun_with_strftime2 ()
Definition at line 20 of file test_fglobals.py.
def get_fun_with_strftime2():
    import datetime
    return datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
Referenced by test_doc_dill_issue_219().
test_doc_dill_issue_219()
dill.tests.test_fglobals.test_doc_dill_issue_219 ()
Definition at line 25 of file test_fglobals.py.
def test_doc_dill_issue_219():
    back_fn = dill.loads(dill.dumps(get_fun_with_strftime()))
    assert back_fn() == "1943-01-04 00:00:00"
    dupl = dill.loads(dill.dumps(get_fun_with_strftime2))
    assert dupl() == get_fun_with_strftime2()
References get_fun_with_strftime(), and get_fun_with_strftime2().
Referenced by test_method_with_internal_import_should_work().
test_method_with_internal_import_should_work()
dill.tests.test_fglobals.test_method_with_internal_import_should_work ()
Definition at line 39 of file test_fglobals.py.
def test_method_with_internal_import_should_work():
    import re
    back_fn = dill.loads(dill.dumps(get_fun_with_internal_import()))
    import inspect
    if hasattr(inspect, 'getclosurevars'):
        vars = inspect.getclosurevars(back_fn)
        assert vars.globals == {}
        assert vars.nonlocals == {}
    assert back_fn() == re.compile("$")
    assert "__builtins__" in back_fn.__globals__
References get_fun_with_internal_import(), test_doc_dill_issue_219(), and test_method_with_internal_import_should_work().
Referenced by test_method_with_internal_import_should_work().