Read&Watch: pip._vendor.pygments.plugin Namespace Reference
pip._vendor.pygments.plugin Namespace Reference
Functions
iter_entry_points (group_name)
find_plugin_lexers ()
find_plugin_formatters ()
find_plugin_styles ()
find_plugin_filters ()
Variables
str LEXER_ENTRY_POINT = 'pygments.lexers'
str FORMATTER_ENTRY_POINT = 'pygments.formatters'
str STYLE_ENTRY_POINT = 'pygments.styles'
str FILTER_ENTRY_POINT = 'pygments.filters'
Detailed Description
    pygments.plugin
    ~~~~~~~~~~~~~~~
    Pygments plugin interface.
    lexer plugins::
        [pygments.lexers]
        yourlexer = yourmodule:YourLexer
    formatter plugins::
        [pygments.formatters]
        yourformatter = yourformatter:YourFormatter
        /.ext = yourformatter:YourFormatter
    As you can see, you can define extensions for the formatter
    with a leading slash.
    syntax plugins::
        [pygments.styles]
        yourstyle = yourstyle:YourStyle
    filter plugin::
        [pygments.filter]
        yourfilter = yourfilter:YourFilter
    :copyright: Copyright 2006-2024 by the Pygments team, see AUTHORS.
    :license: BSD, see LICENSE for details.
Function Documentation
find_plugin_filters()
pip._vendor.pygments.plugin.find_plugin_filters ()
Definition at line 70 of file plugin.py.
def find_plugin_filters():
    for entrypoint in iter_entry_points(FILTER_ENTRY_POINT):
        yield entrypoint.name, entrypoint.load()
References iter_entry_points().
find_plugin_formatters()
pip._vendor.pygments.plugin.find_plugin_formatters ()
Definition at line 60 of file plugin.py.
def find_plugin_formatters():
    for entrypoint in iter_entry_points(FORMATTER_ENTRY_POINT):
        yield entrypoint.name, entrypoint.load()
References iter_entry_points().
find_plugin_lexers()
pip._vendor.pygments.plugin.find_plugin_lexers ()
Definition at line 55 of file plugin.py.
def find_plugin_lexers():
    for entrypoint in iter_entry_points(LEXER_ENTRY_POINT):
        yield entrypoint.load()
References iter_entry_points().
find_plugin_styles()
pip._vendor.pygments.plugin.find_plugin_styles ()
Definition at line 65 of file plugin.py.
def find_plugin_styles():
    for entrypoint in iter_entry_points(STYLE_ENTRY_POINT):
        yield entrypoint.name, entrypoint.load()
References iter_entry_points().
iter_entry_points()
pip._vendor.pygments.plugin.iter_entry_points (group_name)
Definition at line 43 of file plugin.py.
def iter_entry_points(group_name):
    groups = entry_points()
    if hasattr(groups, 'select'):
        # New interface in Python 3.10 and newer versions of the
        # importlib_metadata backport.
        return groups.select(group=group_name)
    else:
        # Older interface, deprecated in Python 3.10 and recent
        # importlib_metadata, but we need it in Python 3.8 and 3.9.
        return groups.get(group_name, [])
Referenced by find_plugin_filters(), find_plugin_formatters(), find_plugin_lexers(), and find_plugin_styles().
Variable Documentation
FILTER_ENTRY_POINT
str pip._vendor.pygments.plugin.FILTER_ENTRY_POINT = 'pygments.filters'
Definition at line 40 of file plugin.py.
FORMATTER_ENTRY_POINT
str pip._vendor.pygments.plugin.FORMATTER_ENTRY_POINT = 'pygments.formatters'
Definition at line 38 of file plugin.py.
LEXER_ENTRY_POINT
str pip._vendor.pygments.plugin.LEXER_ENTRY_POINT = 'pygments.lexers'
Definition at line 37 of file plugin.py.
STYLE_ENTRY_POINT
str pip._vendor.pygments.plugin.STYLE_ENTRY_POINT = 'pygments.styles'
Definition at line 39 of file plugin.py.