Read&Watch: dill.tests.test_functions Namespace Reference
dill.tests.test_functions Namespace Reference
Functions
function_a (a)
function_b (b, b1)
function_c (c, c1=1)
function_d (d, d1, d2=1)
function_with_cache (x)
function_with_unassigned_variable ()
test_issue_510 ()
test_functions ()
test_code_object ()
Variables
int globalvar = 0
f2 = f2.__get__(self)
Function Documentation
function_a()
dill.tests.test_functions.function_a (a)
Definition at line 14 of file test_functions.py.
def function_a(a):
    return a
function_b()
dill.tests.test_functions.function_b (b, b1)
Definition at line 18 of file test_functions.py.
def function_b(b, b1):
    return b + b1
function_c()
dill.tests.test_functions.function_c (c, c1 = 1)
Definition at line 22 of file test_functions.py.
def function_c(c, c1=1):
    return c + c1
function_d()
dill.tests.test_functions.function_d (d, d1, d2 = 1)
doc string
Definition at line 26 of file test_functions.py.
def function_d(d, d1, d2=1):
    """doc string"""
    return d + d1 + d2
function_with_cache()
dill.tests.test_functions.function_with_cache (x)
Definition at line 40 of file test_functions.py.
def function_with_cache(x):
    global globalvar
    globalvar += x
    return globalvar
Referenced by test_functions().
function_with_unassigned_variable()
dill.tests.test_functions.function_with_unassigned_variable ()
Definition at line 46 of file test_functions.py.
def function_with_unassigned_variable():
    if False:
        value = None
    return (lambda: value)
Referenced by test_functions().
test_code_object()
dill.tests.test_functions.test_code_object ()
Definition at line 113 of file test_functions.py.
def test_code_object():
    import warnings
    from dill._dill import ALL_CODE_PARAMS, CODE_PARAMS, CODE_VERSION, _create_code
    code = function_c.__code__
    warnings.filterwarnings('ignore', category=DeprecationWarning) # issue 597
    LNOTAB = getattr(code, 'co_lnotab', b'')
    if warnings.filters: del warnings.filters[0]
    fields = {f: getattr(code, 'co_'+f) for f in CODE_PARAMS}
    fields.setdefault('posonlyargcount', 0)         # python >= 3.8
    fields.setdefault('lnotab', LNOTAB)             # python <= 3.9
    fields.setdefault('linetable', b'')             # python >= 3.10
    fields.setdefault('qualname', fields['name'])   # python >= 3.11
    fields.setdefault('exceptiontable', b'')        # python >= 3.11
    fields.setdefault('endlinetable', None)         # python == 3.11a
    fields.setdefault('columntable', None)          # python == 3.11a
    for version, _, params in ALL_CODE_PARAMS:
        args = tuple(fields[p] for p in params.split())
        try:
            _create_code(*args)
            if version >= (3,10):
                _create_code(fields['lnotab'], *args)
        except Exception as error:
            raise Exception("failed to construct code object with format version {}".format(version)) from error
References test_code_object(), test_functions(), and test_issue_510().
Referenced by test_code_object().
test_functions()
dill.tests.test_functions.test_functions ()
Definition at line 67 of file test_functions.py.
def test_functions():
    dumped_func_a = dill.dumps(function_a)
    assert dill.loads(dumped_func_a)(0) == 0
    dumped_func_b = dill.dumps(function_b)
    assert dill.loads(dumped_func_b)(1,2) == 3
    dumped_func_c = dill.dumps(function_c)
    assert dill.loads(dumped_func_c)(1) == 2
    assert dill.loads(dumped_func_c)(1, 2) == 3
    dumped_func_d = dill.dumps(function_d)
    assert dill.loads(dumped_func_d).__doc__ == function_d.__doc__
    assert dill.loads(dumped_func_d).__module__ == function_d.__module__
    assert dill.loads(dumped_func_d)(1, 2) == 4
    assert dill.loads(dumped_func_d)(1, 2, 3) == 6
    assert dill.loads(dumped_func_d)(1, 2, d2=3) == 6
    function_with_cache(1)
    globalvar = 0
    dumped_func_cache = dill.dumps(function_with_cache)
    assert function_with_cache(2) == 3
    assert function_with_cache(1) == 1
    assert function_with_cache(3) == 6
    assert function_with_cache(2) == 3
    empty_cell = function_with_unassigned_variable()
    cell_copy = dill.loads(dill.dumps(empty_cell))
    assert 'empty' in str(cell_copy.__closure__[0])
    try:
        cell_copy()
    except Exception:
        # this is good
        pass
    else:
        raise AssertionError('cell_copy() did not read an empty cell')
    exec('''
dumped_func_e = dill.dumps(function_e)
assert dill.loads(dumped_func_e)(1, 2) == 6
assert dill.loads(dumped_func_e)(1, 2, 3) == 9
assert dill.loads(dumped_func_e)(1, 2, e2=3) == 8
assert dill.loads(dumped_func_e)(1, 2, e2=3, e3=4) == 10
assert dill.loads(dumped_func_e)(1, 2, 3, e2=4) == 12
assert dill.loads(dumped_func_e)(1, 2, 3, e2=4, e3=5) == 15''')
References function_with_cache(), and function_with_unassigned_variable().
Referenced by test_code_object().
test_issue_510()
dill.tests.test_functions.test_issue_510 ()
Definition at line 52 of file test_functions.py.
def test_issue_510():
    # A very bizzare use of functions and methods that pickle doesn't get
    # correctly for odd reasons.
    class Foo:
        def __init__(self):
                def f2(self):
                        return self
                self.f2 = f2.__get__(self)
    import dill, pickletools
    f = Foo()
    f1 = dill.copy(f)
    assert f1.f2() is f1
Referenced by test_code_object().
Variable Documentation
f2
dill.tests.test_functions.f2 = f2.__get__(self)
Definition at line 59 of file test_functions.py.
globalvar
int dill.tests.test_functions.globalvar = 0
Definition at line 37 of file test_functions.py.