Read&Watch: django.core.management Namespace Reference
django.core.management Namespace Reference
Namespaces
namespace base
namespace color
namespace commands
namespace sql
namespace templates
namespace utils
Classes
class ManagementUtility
Functions
find_commands (management_dir)
load_command_class (app_name, name)
get_commands ()
call_command (command_name, *args, **options)
execute_from_command_line (argv=None)
Function Documentation
call_command()
django.core.management.call_command (command_name, * args, ** options)
Call the given command, with the given options and args/kwargs.
This is the primary API you should use for calling specific commands.
`command_name` may be a string or a command object. Using a string is
preferred unless the command object is required for further processing or
testing.
Some examples:
    call_command('migrate')
    call_command('shell', plain=True)
    call_command('sqlmigrate', 'myapp')
    from django.core.management.commands import flush
    cmd = flush.Command()
    call_command(cmd, verbosity=0, interactive=False)
    # Do something with cmd ...
Definition at line 83 of file __init__.py.
def call_command(command_name, *args, **options):
    """
    Call the given command, with the given options and args/kwargs.
    This is the primary API you should use for calling specific commands.
    `command_name` may be a string or a command object. Using a string is
    preferred unless the command object is required for further processing or
    testing.
    Some examples:
        call_command('migrate')
        call_command('shell', plain=True)
        call_command('sqlmigrate', 'myapp')
        from django.core.management.commands import flush
        cmd = flush.Command()
        call_command(cmd, verbosity=0, interactive=False)
        # Do something with cmd ...
    """
    if isinstance(command_name, BaseCommand):
        # Command object passed in.
        command = command_name
        command_name = command.__class__.__module__.split(".")[-1]
    else:
        # Load the command object by name.
        try:
            app_name = get_commands()[command_name]
        except KeyError:
            raise CommandError("Unknown command: %r" % command_name)
        if isinstance(app_name, BaseCommand):
            # If the command is already loaded, use it directly.
            command = app_name
        else:
            command = load_command_class(app_name, command_name)
    # Simulate argument parsing to get the option defaults (see #10080 for details).
    parser = command.create_parser("", command_name)
    # Use the `dest` option name from the parser option
    opt_mapping = {
        min(s_opt.option_strings).lstrip("-").replace("-", "_"): s_opt.dest
        for s_opt in parser._actions
        if s_opt.option_strings
    }
    arg_options = {opt_mapping.get(key, key): value for key, value in options.items()}
    parse_args = []
    for arg in args:
        if isinstance(arg, (list, tuple)):
            parse_args += map(str, arg)
        else:
            parse_args.append(str(arg))
    def get_actions(parser):
        # Parser actions and actions from sub-parser choices.
        for opt in parser._actions:
            if isinstance(opt, _SubParsersAction):
                for sub_opt in opt.choices.values():
                    yield from get_actions(sub_opt)
            else:
                yield opt
    parser_actions = list(get_actions(parser))
    mutually_exclusive_required_options = {
        opt
        for group in parser._mutually_exclusive_groups
        for opt in group._group_actions
        if group.required
    }
    # Any required arguments which are passed in via **options must be passed
    # to parse_args().
    for opt in parser_actions:
        if opt.dest in options and (
            opt.required or opt in mutually_exclusive_required_options
        ):
            opt_dest_count = sum(v == opt.dest for v in opt_mapping.values())
            if opt_dest_count > 1:
                raise TypeError(
                    f"Cannot pass the dest {opt.dest!r} that matches multiple "
                    f"arguments via **options."
                )
            parse_args.append(min(opt.option_strings))
            if isinstance(opt, (_AppendConstAction, _CountAction, _StoreConstAction)):
                continue
            value = arg_options[opt.dest]
            if isinstance(value, (list, tuple)):
                parse_args += map(str, value)
            else:
                parse_args.append(str(value))
    defaults = parser.parse_args(args=parse_args)
    defaults = dict(defaults._get_kwargs(), **arg_options)
    # Raise an error if any unknown options were passed.
    stealth_options = set(command.base_stealth_options + command.stealth_options)
    dest_parameters = {action.dest for action in parser_actions}
    valid_options = (dest_parameters | stealth_options).union(opt_mapping)
    unknown_options = set(options) - valid_options
    if unknown_options:
        raise TypeError(
            "Unknown option(s) for %s command: %s. "
            "Valid options are: %s."
            % (
                command_name,
                ", ".join(sorted(unknown_options)),
                ", ".join(sorted(valid_options)),
            )
        )
    # Move positional args out of options to mimic legacy optparse
    args = defaults.pop("args", ())
    if "skip_checks" not in options:
        defaults["skip_checks"] = True
    return command.execute(*args, **defaults)
References get_commands(), and load_command_class().
Referenced by django.core.management.commands.testserver.Command.handle().
execute_from_command_line()
django.core.management.execute_from_command_line (argv = None)
Run a ManagementUtility.
Definition at line 439 of file __init__.py.
def execute_from_command_line(argv=None):
    """Run a ManagementUtility."""
    utility = ManagementUtility(argv)
    utility.execute()
find_commands()
django.core.management.find_commands (management_dir)
Given a path to a management directory, return a list of all the command
names that are available.
Definition at line 29 of file __init__.py.
def find_commands(management_dir):
    """
    Given a path to a management directory, return a list of all the command
    names that are available.
    """
    command_dir = os.path.join(management_dir, "commands")
    return [
        name
        for _, name, is_pkg in pkgutil.iter_modules([command_dir])
        if not is_pkg and not name.startswith("_")
    ]
Referenced by get_commands().
get_commands()
django.core.management.get_commands ()
Return a dictionary mapping command names to their callback applications.
Look for a management.commands package in django.core, and in each
installed application -- if a commands package exists, register all
commands in that package.
Core commands are always included. If a settings module has been
specified, also include user-defined commands.
The dictionary is in the format {command_name: app_name}. Key-value
pairs from this dictionary can then be used in calls to
load_command_class(app_name, command_name)
The dictionary is cached on the first call and reused on subsequent
calls.
Definition at line 53 of file __init__.py.
def get_commands():
    """
    Return a dictionary mapping command names to their callback applications.
    Look for a management.commands package in django.core, and in each
    installed application -- if a commands package exists, register all
    commands in that package.
    Core commands are always included. If a settings module has been
    specified, also include user-defined commands.
    The dictionary is in the format {command_name: app_name}. Key-value
    pairs from this dictionary can then be used in calls to
    load_command_class(app_name, command_name)
    The dictionary is cached on the first call and reused on subsequent
    calls.
    """
    commands = {name: "django.core" for name in find_commands(__path__[0])}
    if not settings.configured:
        return commands
    for app_config in reversed(apps.get_app_configs()):
        path = os.path.join(app_config.path, "management")
        commands.update({name: app_config.name for name in find_commands(path)})
    return commands
References find_commands().
Referenced by django.core.management.ManagementUtility.autocomplete(), call_command(), django.core.management.ManagementUtility.fetch_command(), and django.core.management.ManagementUtility.main_help_text().
load_command_class()
django.core.management.load_command_class (app_name, name)
Given a command name and an application name, return the Command
class instance. Allow all errors raised by the import process
(ImportError, AttributeError) to propagate.
Definition at line 42 of file __init__.py.
def load_command_class(app_name, name):
    """
    Given a command name and an application name, return the Command
    class instance. Allow all errors raised by the import process
    (ImportError, AttributeError) to propagate.
    """
    module = import_module("%s.management.commands.%s" % (app_name, name))
    return module.Command()
@functools.cache
Referenced by call_command(), and django.core.management.ManagementUtility.fetch_command().