Read&Watch: django.utils.functional Namespace Reference
django.utils.functional Namespace Reference
Classes
class cached_property
class classproperty
class LazyObject
class Promise
class SimpleLazyObject
Functions
lazy (func, *resultclasses)
_lazy_proxy_unpickle (func, args, kwargs, *resultclasses)
lazystr (text)
keep_lazy (*resultclasses)
keep_lazy_text (func)
new_method_proxy (func)
unpickle_lazyobject (wrapped)
partition (predicate, values)
Variables
empty = object()
_args = args
_kw = kw
Function Documentation
_lazy_proxy_unpickle()
django.utils.functional._lazy_proxy_unpickle (func, args, kwargs, * resultclasses) protected
Definition at line 200 of file functional.py.
def _lazy_proxy_unpickle(func, args, kwargs, *resultclasses):
    return lazy(func, *resultclasses)(*args, **kwargs)
References lazy().
keep_lazy()
django.utils.functional.keep_lazy (* resultclasses)
A decorator that allows a function to be called with one or more lazy
arguments. If none of the args are lazy, the function is evaluated
immediately, otherwise a __proxy__ is returned that will evaluate the
function when needed.
Definition at line 211 of file functional.py.
def keep_lazy(*resultclasses):
    """
    A decorator that allows a function to be called with one or more lazy
    arguments. If none of the args are lazy, the function is evaluated
    immediately, otherwise a __proxy__ is returned that will evaluate the
    function when needed.
    """
    if not resultclasses:
        raise TypeError("You must pass at least one argument to keep_lazy().")
    def decorator(func):
        lazy_func = lazy(func, *resultclasses)
        @wraps(func)
        def wrapper(*args, **kwargs):
            if any(
                isinstance(arg, Promise)
                for arg in itertools.chain(args, kwargs.values())
            ):
                return lazy_func(*args, **kwargs)
            return func(*args, **kwargs)
        return wrapper
    return decorator
References lazy().
Referenced by keep_lazy_text().
keep_lazy_text()
django.utils.functional.keep_lazy_text (func)
A decorator for functions that accept lazy arguments and return text.
Definition at line 238 of file functional.py.
def keep_lazy_text(func):
    """
    A decorator for functions that accept lazy arguments and return text.
    """
    return keep_lazy(str)(func)
References keep_lazy().
lazy()
django.utils.functional.lazy (func, * resultclasses)
Turn any callable into a lazy evaluated callable. result classes or types
is required -- at least one is needed so that the automatic forcing of
the lazy evaluation code is triggered. Results are not memoized; the
function is evaluated on every access.
Definition at line 77 of file functional.py.
def lazy(func, *resultclasses):
    """
    Turn any callable into a lazy evaluated callable. result classes or types
    is required -- at least one is needed so that the automatic forcing of
    the lazy evaluation code is triggered. Results are not memoized; the
    function is evaluated on every access.
    """
    class __proxy__(Promise):
        """
        Encapsulate a function call and act as a proxy for methods that are
        called on the result of that function. The function is not evaluated
        until one of the methods on the result is called.
        """
        def __init__(self, args, kw):
            self._args = args
            self._kw = kw
        def __reduce__(self):
            return (
                _lazy_proxy_unpickle,
                (func, self._args, self._kw) + resultclasses,
            )
        def __deepcopy__(self, memo):
            # Instances of this class are effectively immutable. It's just a
            # collection of functions. So we don't need to do anything
            # complicated for copying.
            memo[id(self)] = self
            return self
        def __cast(self):
            return func(*self._args, **self._kw)
        # Explicitly wrap methods which are defined on object and hence would
        # not have been overloaded by the loop over resultclasses below.
        def __repr__(self):
            return repr(self.__cast())
        def __str__(self):
            return str(self.__cast())
        def __eq__(self, other):
            if isinstance(other, Promise):
                other = other.__cast()
            return self.__cast() == other
        def __ne__(self, other):
            if isinstance(other, Promise):
                other = other.__cast()
            return self.__cast() != other
        def __lt__(self, other):
            if isinstance(other, Promise):
                other = other.__cast()
            return self.__cast() < other
        def __le__(self, other):
            if isinstance(other, Promise):
                other = other.__cast()
            return self.__cast() <= other
        def __gt__(self, other):
            if isinstance(other, Promise):
                other = other.__cast()
            return self.__cast() > other
        def __ge__(self, other):
            if isinstance(other, Promise):
                other = other.__cast()
            return self.__cast() >= other
        def __hash__(self):
            return hash(self.__cast())
        def __format__(self, format_spec):
            return format(self.__cast(), format_spec)
        # Explicitly wrap methods which are required for certain operations on
        # int/str objects to function correctly.
        def __add__(self, other):
            return self.__cast() + other
        def __radd__(self, other):
            return other + self.__cast()
        def __mod__(self, other):
            return self.__cast() % other
        def __mul__(self, other):
            return self.__cast() * other
    # Add wrappers for all methods from resultclasses which haven't been
    # wrapped explicitly above.
    for resultclass in resultclasses:
        for type_ in resultclass.mro():
            for method_name in type_.__dict__:
                # All __promise__ return the same wrapper method, they look up
                # the correct implementation when called.
                if hasattr(__proxy__, method_name):
                    continue
                # Builds a wrapper around some method. Pass method_name to
                # avoid issues due to late binding.
                def __wrapper__(self, *args, __method_name=method_name, **kw):
                    # Automatically triggers the evaluation of a lazy value and
                    # applies the given method of the result type.
                    result = func(*self._args, **self._kw)
                    return getattr(result, __method_name)(*args, **kw)
                setattr(__proxy__, method_name, __wrapper__)
    @wraps(func)
    def __wrapper__(*args, **kw):
        # Creates the proxy object, instead of the actual value.
        return __proxy__(args, kw)
    return __wrapper__
Referenced by _lazy_proxy_unpickle(), keep_lazy(), and lazystr().
lazystr()
django.utils.functional.lazystr (text)
Shortcut for the common case of a lazy callable that returns str.
Definition at line 204 of file functional.py.
def lazystr(text):
    """
    Shortcut for the common case of a lazy callable that returns str.
    """
    return lazy(str, str)(text)
References lazy().
new_method_proxy()
django.utils.functional.new_method_proxy (func)
Definition at line 248 of file functional.py.
def new_method_proxy(func):
    def inner(self, *args):
        if (_wrapped := self._wrapped) is empty:
            self._setup()
            _wrapped = self._wrapped
        return func(_wrapped, *args)
    inner._mask_wrapped = False
    return inner
Referenced by django.utils.functional.LazyObject.__deepcopy__(), django.utils.functional.SimpleLazyObject.__deepcopy__(), and django.utils.functional.LazyObject.__getattribute__().
partition()
django.utils.functional.partition (predicate, values)
Split the values into two sets, based on the return value of the function
(True/False). e.g.:
    >>> partition(lambda x: x > 3, range(5))
    [0, 1, 2, 3], [4]
Definition at line 440 of file functional.py.
def partition(predicate, values):
    """
    Split the values into two sets, based on the return value of the function
    (True/False). e.g.:
        >>> partition(lambda x: x > 3, range(5))
        [0, 1, 2, 3], [4]
    """
    results = ([], [])
    for item in values:
        results[predicate(item)].append(item)
    return results
unpickle_lazyobject()
django.utils.functional.unpickle_lazyobject (wrapped)
Used to unpickle lazy objects. Just return its argument, which will be the
wrapped object.
Definition at line 375 of file functional.py.
def unpickle_lazyobject(wrapped):
    """
    Used to unpickle lazy objects. Just return its argument, which will be the
    wrapped object.
    """
    return wrapped
Variable Documentation
_args
django.utils.functional._args = args protected
Definition at line 93 of file functional.py.
_kw
django.utils.functional._kw = kw protected
Definition at line 94 of file functional.py.
empty
django.utils.functional.empty = object()
Definition at line 245 of file functional.py.