Read&Watch: astroid.interpreter._import.spec Namespace Reference
astroid.interpreter._import.spec Namespace Reference
Classes
class _MetaPathFinder
class ExplicitNamespacePackageFinder
class Finder
class ImportlibFinder
class ModuleSpec
class ModuleType
class PathSpecFinder
class ZipFinder
Functions
bool _is_setuptools_namespace (pathlib.Path location)
Iterator[tuple[str, zipimport.zipimporter]] _get_zipimporters ()
tuple[Literal[ModuleType.PY_ZIPMODULE], str, str] _search_zip (Sequence[str] modpath)
tuple[Finder|_MetaPathFinder, ModuleSpec] _find_spec_with_path (Sequence[str] search_path, str modname, list[str] module_parts, list[str] processed, Sequence[str]|None submodule_path)
ModuleSpec find_spec (Iterable[str] modpath, Iterable[str]|None path=None)
ModuleSpec _find_spec (tuple module_path, tuple path)
Variables
tuple _SPEC_FINDERS
Function Documentation
_find_spec()
ModuleSpec astroid.interpreter._import.spec._find_spec (tuple module_path, tuple path) protected
Definition at line 488 of file spec.py.
def _find_spec(module_path: tuple, path: tuple) -> ModuleSpec:
    _path = path or sys.path
    # Need a copy for not mutating the argument.
    modpath = list(module_path)
    submodule_path = None
    module_parts = modpath[:]
    processed: list[str] = []
    while modpath:
        modname = modpath.pop(0)
        finder, spec = _find_spec_with_path(
            _path, modname, module_parts, processed, submodule_path or path
        )
        processed.append(modname)
        if modpath:
            if isinstance(finder, Finder):
                submodule_path = finder.contribute_to_path(spec, processed)
            # If modname is a package from an editable install, update submodule_path
            # so that the next module in the path will be found inside of it using importlib.
            # Existence of __name__ is guaranteed by _find_spec_with_path.
            elif finder.__name__ in _EditableFinderClasses:  # type: ignore[attr-defined]
                submodule_path = spec.submodule_search_locations
        if spec.type == ModuleType.PKG_DIRECTORY:
            spec = spec._replace(submodule_search_locations=submodule_path)
    return spec
References _find_spec_with_path().
Referenced by find_spec().
_find_spec_with_path()
tuple[Finder | _MetaPathFinder, ModuleSpec] astroid.interpreter._import.spec._find_spec_with_path (Sequence[str] search_path, str modname, list[str] module_parts, list[str] processed, Sequence[str] | None submodule_path) protected
Definition at line 411 of file spec.py.
) -> tuple[Finder | _MetaPathFinder, ModuleSpec]:
    for finder in _SPEC_FINDERS:
        finder_instance = finder(search_path)
        spec = finder_instance.find_module(
            modname, module_parts, processed, submodule_path
        )
        if spec is None:
            continue
        return finder_instance, spec
    # Support for custom finders
    for meta_finder in sys.meta_path:
        # See if we support the customer import hook of the meta_finder
        meta_finder_name = meta_finder.__class__.__name__
        if meta_finder_name not in _MetaPathFinderModuleTypes:
            # Setuptools>62 creates its EditableFinders dynamically and have
            # "type" as their __class__.__name__. We check __name__ as well
            # to see if we can support the finder.
            try:
                meta_finder_name = meta_finder.__name__  # type: ignore[attr-defined]
            except AttributeError:
                continue
            if meta_finder_name not in _MetaPathFinderModuleTypes:
                continue
        module_type = _MetaPathFinderModuleTypes[meta_finder_name]
        # Meta path finders are supposed to have a find_spec method since
        # Python 3.4. However, some third-party finders do not implement it.
        # PEP302 does not refer to find_spec as well.
        # See: https://github.com/pylint-dev/astroid/pull/1752/
        if not hasattr(meta_finder, "find_spec"):
            continue
        spec = meta_finder.find_spec(modname, submodule_path)
        if spec:
            return (
                meta_finder,
                ModuleSpec(
                    spec.name,
                    module_type,
                    spec.origin,
                    spec.origin,
                    spec.submodule_search_locations,
                ),
            )
    raise ImportError(f"No module named {'.'.join(module_parts)}")
Referenced by _find_spec().
_get_zipimporters()
Iterator[tuple[str, zipimport.zipimporter]] astroid.interpreter._import.spec._get_zipimporters () protected
Definition at line 375 of file spec.py.
def _get_zipimporters() -> Iterator[tuple[str, zipimport.zipimporter]]:
    for filepath, importer in sys.path_importer_cache.items():
        if importer is not None and isinstance(importer, zipimport.zipimporter):
            yield filepath, importer
Referenced by _search_zip().
_is_setuptools_namespace()
bool astroid.interpreter._import.spec._is_setuptools_namespace (pathlib.Path location) protected
Definition at line 362 of file spec.py.
def _is_setuptools_namespace(location: pathlib.Path) -> bool:
    try:
        with open(location / "__init__.py", "rb") as stream:
            data = stream.read(4096)
    except OSError:
        return False
    extend_path = b"pkgutil" in data and b"extend_path" in data
    declare_namespace = (
        b"pkg_resources" in data and b"declare_namespace(__name__)" in data
    )
    return extend_path or declare_namespace
Referenced by astroid.interpreter._import.spec.ImportlibFinder.contribute_to_path().
_search_zip()
tuple[Literal[ModuleType.PY_ZIPMODULE], str, str] astroid.interpreter._import.spec._search_zip (Sequence[str] modpath) protected
Definition at line 381 of file spec.py.
) -> tuple[Literal[ModuleType.PY_ZIPMODULE], str, str]:
    for filepath, importer in _get_zipimporters():
        if PY310_PLUS:
            found: Any = importer.find_spec(modpath[0])
        else:
            found = importer.find_module(modpath[0])
        if found:
            if PY310_PLUS:
                if not importer.find_spec(os.path.sep.join(modpath)):
                    raise ImportError(
                        "No module named {} in {}/{}".format(
                            ".".join(modpath[1:]), filepath, modpath
                        )
                    )
            elif not importer.find_module(os.path.sep.join(modpath)):
                raise ImportError(
                    "No module named {} in {}/{}".format(
                        ".".join(modpath[1:]), filepath, modpath
                    )
                )
            return (
                ModuleType.PY_ZIPMODULE,
                os.path.abspath(filepath) + os.path.sep + os.path.sep.join(modpath),
                filepath,
            )
    raise ImportError(f"No module named {'.'.join(modpath)}")
References _get_zipimporters().
Referenced by astroid.interpreter._import.spec.ZipFinder.find_module().
find_spec()
ModuleSpec astroid.interpreter._import.spec.find_spec (Iterable[str] modpath, Iterable[str] | None path = None)
Find a spec for the given module.
:type modpath: list or tuple
:param modpath:
  split module's name (i.e name of a module or package split
  on '.'), with leading empty strings for explicit relative import
:type path: list or None
:param path:
  optional list of path where the module or package should be
  searched (use sys.path if nothing or None is given)
:rtype: ModuleSpec
:return: A module spec, which describes how the module was
         found and where.
Definition at line 467 of file spec.py.
def find_spec(modpath: Iterable[str], path: Iterable[str] | None = None) -> ModuleSpec:
    """Find a spec for the given module.
    :type modpath: list or tuple
    :param modpath:
      split module's name (i.e name of a module or package split
      on '.'), with leading empty strings for explicit relative import
    :type path: list or None
    :param path:
      optional list of path where the module or package should be
      searched (use sys.path if nothing or None is given)
    :rtype: ModuleSpec
    :return: A module spec, which describes how the module was
             found and where.
    """
    return _find_spec(tuple(modpath), tuple(path) if path else None)
@lru_cache(maxsize=1024)
References _find_spec().
Variable Documentation
_SPEC_FINDERS
tuple astroid.interpreter._import.spec._SPEC_FINDERS protected
Initial value:
=  (
    ImportlibFinder,
    ZipFinder,
    PathSpecFinder,
    ExplicitNamespacePackageFinder,
)
Definition at line 354 of file spec.py.