Read&Watch: pylint.checkers.strings Namespace Reference
pylint.checkers.strings Namespace Reference
Classes
class StringConstantChecker
class StringFormatChecker
Functions
str get_access_path (str|Literal[0] key, list[tuple[bool, str]] parts)
bool arg_matches_format_type (SuccessfulInferenceResult arg_type, str format_type)
None register (PyLinter linter)
str str_eval (str token)
bool _is_long_string (str string_token)
str _get_quote_delimiter (str string_token)
bool _is_quote_delimiter_chosen_freely (str string_token)
Variables
tuple _AST_NODE_STR_TYPES = ("__builtin__.unicode", "__builtin__.str", "builtins.str")
dict _PREFIXES
tuple _PAREN_IGNORE_TOKEN_TYPES
SINGLE_QUOTED_REGEX = re.compile(f"({'|'.join(_PREFIXES)})?'''")
DOUBLE_QUOTED_REGEX = re.compile(f"({'|'.join(_PREFIXES)})?\"\"\"")
QUOTE_DELIMITER_REGEX = re.compile(f"({'|'.join(_PREFIXES)})?(\"|')", re.DOTALL)
tuple MSGS
tuple OTHER_NODES
Detailed Description
Checker for string formatting operations.
Function Documentation
_get_quote_delimiter()
str pylint.checkers.strings._get_quote_delimiter (str string_token) protected
Returns the quote character used to delimit this token string.
This function checks whether the token is a well-formed string.
Args:
    string_token: The token to be parsed.
Returns:
    A string containing solely the first quote delimiter character in the
    given string.
Raises:
  ValueError: No quote delimiter characters are present.
Definition at line 1060 of file strings.py.
def _get_quote_delimiter(string_token: str) -> str:
    """Returns the quote character used to delimit this token string.
    This function checks whether the token is a well-formed string.
    Args:
        string_token: The token to be parsed.
    Returns:
        A string containing solely the first quote delimiter character in the
        given string.
    Raises:
      ValueError: No quote delimiter characters are present.
    """
    match = QUOTE_DELIMITER_REGEX.match(string_token)
    if not match:
        raise ValueError(f"string token {string_token} is not a well-formed string")
    return match.group(2)
Referenced by _is_quote_delimiter_chosen_freely(), and pylint.checkers.strings.StringConstantChecker.check_for_consistent_string_delimiters().
_is_long_string()
bool pylint.checkers.strings._is_long_string (str string_token) protected
Is this string token a "longstring" (is it triple-quoted)?
Long strings are triple-quoted as defined in
https://docs.python.org/3/reference/lexical_analysis.html#string-and-bytes-literals
This function only checks characters up through the open quotes.  Because it's meant
to be applied only to tokens that represent string literals, it doesn't bother to
check for close-quotes (demonstrating that the literal is a well-formed string).
Args:
    string_token: The string token to be parsed.
Returns:
    A boolean representing whether this token matches a longstring
    regex.
Definition at line 1037 of file strings.py.
def _is_long_string(string_token: str) -> bool:
    """Is this string token a "longstring" (is it triple-quoted)?
    Long strings are triple-quoted as defined in
    https://docs.python.org/3/reference/lexical_analysis.html#string-and-bytes-literals
    This function only checks characters up through the open quotes.  Because it's meant
    to be applied only to tokens that represent string literals, it doesn't bother to
    check for close-quotes (demonstrating that the literal is a well-formed string).
    Args:
        string_token: The string token to be parsed.
    Returns:
        A boolean representing whether this token matches a longstring
        regex.
    """
    return bool(
        SINGLE_QUOTED_REGEX.match(string_token)
        or DOUBLE_QUOTED_REGEX.match(string_token)
    )
Referenced by _is_quote_delimiter_chosen_freely().
_is_quote_delimiter_chosen_freely()
bool pylint.checkers.strings._is_quote_delimiter_chosen_freely (str string_token) protected
Was there a non-awkward option for the quote delimiter?
Args:
    string_token: The quoted string whose delimiters are to be checked.
Returns:
    Whether there was a choice in this token's quote character that would
    not have involved backslash-escaping an interior quote character.  Long
    strings are excepted from this analysis under the assumption that their
    quote characters are set by policy.
Definition at line 1081 of file strings.py.
def _is_quote_delimiter_chosen_freely(string_token: str) -> bool:
    """Was there a non-awkward option for the quote delimiter?
    Args:
        string_token: The quoted string whose delimiters are to be checked.
    Returns:
        Whether there was a choice in this token's quote character that would
        not have involved backslash-escaping an interior quote character.  Long
        strings are excepted from this analysis under the assumption that their
        quote characters are set by policy.
    """
    quote_delimiter = _get_quote_delimiter(string_token)
    unchosen_delimiter = '"' if quote_delimiter == "'" else "'"
    return bool(
        quote_delimiter
        and not _is_long_string(string_token)
        and unchosen_delimiter not in str_eval(string_token)
    )
References _get_quote_delimiter(), _is_long_string(), and str_eval().
Referenced by pylint.checkers.strings.StringConstantChecker.check_for_consistent_string_delimiters().
arg_matches_format_type()
bool pylint.checkers.strings.arg_matches_format_type (SuccessfulInferenceResult arg_type, str format_type)
Definition at line 223 of file strings.py.
) -> bool:
    if format_type in "sr":
        # All types can be printed with %s and %r
        return True
    if isinstance(arg_type, astroid.Instance):
        arg_type = arg_type.pytype()
        if arg_type == "builtins.str":
            return format_type == "c"
        if arg_type == "builtins.float":
            return format_type in "deEfFgGn%"
        if arg_type == "builtins.int":
            # Integers allow all types
            return True
        return False
    return True
Referenced by pylint.checkers.strings.StringFormatChecker.visit_binop().
get_access_path()
str pylint.checkers.strings.get_access_path (str | Literal[0] key, list[tuple[bool, str]] parts)
Given a list of format specifiers, returns
the final access path (e.g. a.b.c[0][1]).
Definition at line 210 of file strings.py.
def get_access_path(key: str | Literal[0], parts: list[tuple[bool, str]]) -> str:
    """Given a list of format specifiers, returns
    the final access path (e.g. a.b.c[0][1]).
    """
    path = []
    for is_attribute, specifier in parts:
        if is_attribute:
            path.append(f".{specifier}")
        else:
            path.append(f"[{specifier!r}]")
    return str(key) + "".join(path)
Referenced by pylint.checkers.strings.StringFormatChecker._check_new_format_specifiers().
register()
None pylint.checkers.strings.register (PyLinter linter)
Definition at line 1016 of file strings.py.
def register(linter: PyLinter) -> None:
    linter.register_checker(StringFormatChecker(linter))
    linter.register_checker(StringConstantChecker(linter))
str_eval()
str pylint.checkers.strings.str_eval (str token)
Mostly replicate `ast.literal_eval(token)` manually to avoid any performance hit.
This supports f-strings, contrary to `ast.literal_eval`.
We have to support all string literal notations:
https://docs.python.org/3/reference/lexical_analysis.html#string-and-bytes-literals
Definition at line 1021 of file strings.py.
def str_eval(token: str) -> str:
    """Mostly replicate `ast.literal_eval(token)` manually to avoid any performance hit.
    This supports f-strings, contrary to `ast.literal_eval`.
    We have to support all string literal notations:
    https://docs.python.org/3/reference/lexical_analysis.html#string-and-bytes-literals
    """
    if token[0:2].lower() in {"fr", "rf"}:
        token = token[2:]
    elif token[0].lower() in {"r", "u", "f"}:
        token = token[1:]
    if token[0:3] in {'"""', "'''"}:
        return token[3:-3]
    return token[1:-1]
Referenced by _is_quote_delimiter_chosen_freely(), and pylint.checkers.strings.StringConstantChecker.process_tokens().
Variable Documentation
_AST_NODE_STR_TYPES
tuple pylint.checkers.strings._AST_NODE_STR_TYPES = ("__builtin__.unicode", "__builtin__.str", "builtins.str") protected
Definition at line 30 of file strings.py.
_PAREN_IGNORE_TOKEN_TYPES
tuple pylint.checkers.strings._PAREN_IGNORE_TOKEN_TYPES protected
Initial value:
=  (
    tokenize.NEWLINE,
    tokenize.NL,
    tokenize.COMMENT,
)
Definition at line 59 of file strings.py.
_PREFIXES
dict pylint.checkers.strings._PREFIXES protected
Initial value:
=  {
    "r",
    "u",
    "R",
    "U",
    "f",
    "F",
    "fr",
    "Fr",
    "fR",
    "FR",
    "rf",
    "rF",
    "Rf",
    "RF",
    "b",
    "B",
    "br",
    "Br",
    "bR",
    "BR",
    "rb",
    "rB",
    "Rb",
    "RB",
}
Definition at line 33 of file strings.py.
DOUBLE_QUOTED_REGEX
pylint.checkers.strings.DOUBLE_QUOTED_REGEX = re.compile(f"({'|'.join(_PREFIXES)})?\"\"\"")
Definition at line 65 of file strings.py.
MSGS
tuple pylint.checkers.strings.MSGS
Definition at line 68 of file strings.py.
OTHER_NODES
tuple pylint.checkers.strings.OTHER_NODES
Initial value:
=  (
    nodes.Const,
    nodes.List,
    nodes.Lambda,
    nodes.FunctionDef,
    nodes.ListComp,
    nodes.SetComp,
    nodes.GeneratorExp,
)
Definition at line 199 of file strings.py.
QUOTE_DELIMITER_REGEX
pylint.checkers.strings.QUOTE_DELIMITER_REGEX = re.compile(f"({'|'.join(_PREFIXES)})?(\"|')", re.DOTALL)
Definition at line 66 of file strings.py.
SINGLE_QUOTED_REGEX
pylint.checkers.strings.SINGLE_QUOTED_REGEX = re.compile(f"({'|'.join(_PREFIXES)})?'''")
Definition at line 64 of file strings.py.