Read&Watch: pip._vendor.requests.sessions Namespace Reference
pip._vendor.requests.sessions Namespace Reference
Classes
class Session
class SessionRedirectMixin
Functions
merge_setting (request_setting, session_setting, dict_class=OrderedDict)
merge_hooks (request_hooks, session_hooks, dict_class=OrderedDict)
session ()
Variables
preferred_clock = time.perf_counter
Detailed Description
requests.sessions
~~~~~~~~~~~~~~~~~
This module provides a Session object to manage and persist settings across
requests (cookies, auth, proxies).
Function Documentation
merge_hooks()
pip._vendor.requests.sessions.merge_hooks (request_hooks, session_hooks, dict_class = OrderedDict)
Properly merges both requests and session hooks.
This is necessary because when request_hooks == {'response': []}, the
merge breaks Session hooks entirely.
Definition at line 91 of file sessions.py.
def merge_hooks(request_hooks, session_hooks, dict_class=OrderedDict):
    """Properly merges both requests and session hooks.
    This is necessary because when request_hooks == {'response': []}, the
    merge breaks Session hooks entirely.
    """
    if session_hooks is None or session_hooks.get("response") == []:
        return request_hooks
    if request_hooks is None or request_hooks.get("response") == []:
        return session_hooks
    return merge_setting(request_hooks, session_hooks, dict_class)
References merge_setting().
Referenced by pip._vendor.requests.sessions.Session.prepare_request().
merge_setting()
pip._vendor.requests.sessions.merge_setting (request_setting, session_setting, dict_class = OrderedDict)
Determines appropriate setting for a given request, taking into account
the explicit setting on that request, and the setting in the session. If a
setting is a dictionary, they will be merged together using `dict_class`
Definition at line 61 of file sessions.py.
def merge_setting(request_setting, session_setting, dict_class=OrderedDict):
    """Determines appropriate setting for a given request, taking into account
    the explicit setting on that request, and the setting in the session. If a
    setting is a dictionary, they will be merged together using `dict_class`
    """
    if session_setting is None:
        return request_setting
    if request_setting is None:
        return session_setting
    # Bypass if not a dictionary (e.g. verify)
    if not (
        isinstance(session_setting, Mapping) and isinstance(request_setting, Mapping)
    ):
        return request_setting
    merged_setting = dict_class(to_key_val_list(session_setting))
    merged_setting.update(to_key_val_list(request_setting))
    # Remove keys that are set to None. Extract keys first to avoid altering
    # the dictionary during iteration.
    none_keys = [k for (k, v) in merged_setting.items() if v is None]
    for key in none_keys:
        del merged_setting[key]
    return merged_setting
Referenced by pip._vendor.requests.sessions.Session.merge_environment_settings(), merge_hooks(), and pip._vendor.requests.sessions.Session.prepare_request().
session()
pip._vendor.requests.sessions.session ()
Returns a :class:`Session` for context-management.
.. deprecated:: 1.0.0
    This method has been deprecated since version 1.0.0 and is only kept for
    backwards compatibility. New code should use :class:`~requests.sessions.Session`
    to create a session. This may be removed at a future date.
:rtype: Session
Definition at line 819 of file sessions.py.
def session():
    """
    Returns a :class:`Session` for context-management.
    .. deprecated:: 1.0.0
        This method has been deprecated since version 1.0.0 and is only kept for
        backwards compatibility. New code should use :class:`~requests.sessions.Session`
        to create a session. This may be removed at a future date.
    :rtype: Session
    """
    return Session()
Variable Documentation
preferred_clock
pip._vendor.requests.sessions.preferred_clock = time.perf_counter
Definition at line 56 of file sessions.py.
Referenced by pip._vendor.requests.sessions.Session.send().