Read&Watch: pip._vendor.rich Namespace Reference
pip._vendor.rich Namespace Reference
Namespaces
namespace __main__
namespace _cell_widths
namespace _emoji_codes
namespace _emoji_replace
namespace _export_format
namespace _extension
namespace _fileno
namespace _inspect
namespace _log_render
namespace _loop
namespace _null_file
namespace _palettes
namespace _pick
namespace _ratio
namespace _spinners
namespace _stack
namespace _timer
namespace _win32_console
namespace _windows
namespace _windows_renderer
namespace _wrap
namespace abc
namespace align
namespace ansi
namespace bar
namespace box
namespace cells
namespace color
namespace color_triplet
namespace columns
namespace console
namespace constrain
namespace containers
namespace control
namespace default_styles
namespace diagnose
namespace emoji
namespace errors
namespace file_proxy
namespace filesize
namespace highlighter
namespace json
namespace jupyter
namespace layout
namespace live
namespace live_render
namespace logging
namespace markup
namespace measure
namespace padding
namespace pager
namespace palette
namespace panel
namespace pretty
namespace progress
namespace progress_bar
namespace prompt
namespace protocol
namespace region
namespace repr
namespace rule
namespace scope
namespace screen
namespace segment
namespace spinner
namespace status
namespace style
namespace styled
namespace syntax
namespace table
namespace terminal_theme
namespace text
namespace theme
namespace themes
namespace traceback
namespace tree
Functions
"Console" get_console ()
None reconfigure (*Any args, **Any kwargs)
None print (*Any objects, str sep=" ", str end="\n", Optional[IO[str]] file=None, bool flush=False)
None print_json (Optional[str] json=None, *, Any data=None, Union[None, int, str] indent=2, bool highlight=True, bool skip_keys=False, bool ensure_ascii=False, bool check_circular=True, bool allow_nan=True, Optional[Callable[[Any], Any]] default=None, bool sort_keys=False)
None inspect (Any obj, *, Optional["Console"] console=None, Optional[str] title=None, bool help=False, bool methods=False, bool docs=True, bool private=False, bool dunder=False, bool sort=True, bool all=False, bool value=True)
Variables
Optional _console = None
_IMPORT_CWD = os.path.abspath(os.getcwd())
Detailed Description
Rich text and beautiful formatting in the terminal.
Function Documentation
get_console()
"Console" pip._vendor.rich.get_console ()
Get a global :class:`~rich.console.Console` instance. This function is used when Rich requires a Console,
and hasn't been explicitly given one.
Returns:
    Console: A console instance.
Definition at line 23 of file __init__.py.
def get_console() -> "Console":
    """Get a global :class:`~rich.console.Console` instance. This function is used when Rich requires a Console,
    and hasn't been explicitly given one.
    Returns:
        Console: A console instance.
    """
    global _console
    if _console is None:
        from .console import Console
        _console = Console()
    return _console
Referenced by pip._vendor.rich.pretty._ipy_display_hook(), pip._vendor.rich.jupyter.JupyterMixin._repr_mimebundle_(), inspect(), pip._vendor.rich.pretty.install(), pip._vendor.rich.pretty.pprint(), pip._vendor.rich.jupyter.print(), print(), print_json(), and reconfigure().
inspect()
None pip._vendor.rich.inspect (Any obj, * , Optional["Console"] console = None, Optional[str] title = None, bool help = False, bool methods = False, bool docs = True, bool private = False, bool dunder = False, bool sort = True, bool all = False, bool value = True)
Inspect any Python object.
* inspect(<OBJECT>) to see summarized info.
* inspect(<OBJECT>, methods=True) to see methods.
* inspect(<OBJECT>, help=True) to see full (non-abbreviated) help.
* inspect(<OBJECT>, private=True) to see private attributes (single underscore).
* inspect(<OBJECT>, dunder=True) to see attributes beginning with double underscore.
* inspect(<OBJECT>, all=True) to see all attributes.
Args:
    obj (Any): An object to inspect.
    title (str, optional): Title to display over inspect result, or None use type. Defaults to None.
    help (bool, optional): Show full help text rather than just first paragraph. Defaults to False.
    methods (bool, optional): Enable inspection of callables. Defaults to False.
    docs (bool, optional): Also render doc strings. Defaults to True.
    private (bool, optional): Show private attributes (beginning with underscore). Defaults to False.
    dunder (bool, optional): Show attributes starting with double underscore. Defaults to False.
    sort (bool, optional): Sort attributes alphabetically. Defaults to True.
    all (bool, optional): Show all attributes. Defaults to False.
    value (bool, optional): Pretty print value. Defaults to True.
Definition at line 120 of file __init__.py.
) -> None:
    """Inspect any Python object.
    * inspect(<OBJECT>) to see summarized info.
    * inspect(<OBJECT>, methods=True) to see methods.
    * inspect(<OBJECT>, help=True) to see full (non-abbreviated) help.
    * inspect(<OBJECT>, private=True) to see private attributes (single underscore).
    * inspect(<OBJECT>, dunder=True) to see attributes beginning with double underscore.
    * inspect(<OBJECT>, all=True) to see all attributes.
    Args:
        obj (Any): An object to inspect.
        title (str, optional): Title to display over inspect result, or None use type. Defaults to None.
        help (bool, optional): Show full help text rather than just first paragraph. Defaults to False.
        methods (bool, optional): Enable inspection of callables. Defaults to False.
        docs (bool, optional): Also render doc strings. Defaults to True.
        private (bool, optional): Show private attributes (beginning with underscore). Defaults to False.
        dunder (bool, optional): Show attributes starting with double underscore. Defaults to False.
        sort (bool, optional): Sort attributes alphabetically. Defaults to True.
        all (bool, optional): Show all attributes. Defaults to False.
        value (bool, optional): Pretty print value. Defaults to True.
    """
    _console = console or get_console()
    from pip._vendor.rich._inspect import Inspect
    # Special case for inspect(inspect)
    is_inspect = obj is inspect
    _inspect = Inspect(
        obj,
        title=title,
        help=is_inspect or help,
        methods=is_inspect or methods,
        docs=is_inspect or docs,
        private=private,
        dunder=dunder,
        sort=sort,
        all=all,
        value=value,
    )
    _console.print(_inspect)
References get_console(), and print().
Referenced by pip._vendor.rich.diagnose.report().
print()
None pip._vendor.rich.print (*Any objects, str sep = " ", str end = "\n", Optional[IO[str]] file = None, bool flush = False)
Print object(s) supplied via positional arguments.
This function has an identical signature to the built-in print.
For more advanced features, see the :class:`~rich.console.Console` class.
Args:
    sep (str, optional): Separator between printed objects. Defaults to " ".
    end (str, optional): Character to write at end of output. Defaults to "\\n".
    file (IO[str], optional): File to write to, or None for stdout. Defaults to None.
    flush (bool, optional): Has no effect as Rich always flushes output. Defaults to False.
Definition at line 53 of file __init__.py.
) -> None:
    r"""Print object(s) supplied via positional arguments.
    This function has an identical signature to the built-in print.
    For more advanced features, see the :class:`~rich.console.Console` class.
    Args:
        sep (str, optional): Separator between printed objects. Defaults to " ".
        end (str, optional): Character to write at end of output. Defaults to "\\n".
        file (IO[str], optional): File to write to, or None for stdout. Defaults to None.
        flush (bool, optional): Has no effect as Rich always flushes output. Defaults to False.
    """
    from .console import Console
    write_console = get_console() if file is None else Console(file=file)
    return write_console.print(*objects, sep=sep, end=end)
References get_console().
Referenced by pip._vendor.rich.pretty.Thing.__repr__(), pip._vendor.rich.padding.Padding.__rich_measure__(), pip._vendor.rich.traceback.bar(), pip._vendor.rich.cells.chop_cells(), pip._vendor.rich.file_proxy.FileProxy.flush(), inspect(), pip._vendor.rich.prompt.PromptBase.on_validate_error(), pip._vendor.rich.scope.render_scope(), pip._vendor.rich.scope.test(), pip._vendor.rich._timer.timer(), and pip._vendor.rich.console.ScreenContext.update().
print_json()
None pip._vendor.rich.print_json (Optional[str] json = None, * , Any data = None, Union[None, int, str] indent = 2, bool highlight = True, bool skip_keys = False, bool ensure_ascii = False, bool check_circular = True, bool allow_nan = True, Optional[Callable[[Any], Any]] default = None, bool sort_keys = False)
Pretty prints JSON. Output will be valid JSON.
Args:
    json (str): A string containing JSON.
    data (Any): If json is not supplied, then encode this data.
    indent (int, optional): Number of spaces to indent. Defaults to 2.
    highlight (bool, optional): Enable highlighting of output: Defaults to True.
    skip_keys (bool, optional): Skip keys not of a basic type. Defaults to False.
    ensure_ascii (bool, optional): Escape all non-ascii characters. Defaults to False.
    check_circular (bool, optional): Check for circular references. Defaults to True.
    allow_nan (bool, optional): Allow NaN and Infinity values. Defaults to True.
    default (Callable, optional): A callable that converts values that can not be encoded
        in to something that can be JSON encoded. Defaults to None.
    sort_keys (bool, optional): Sort dictionary keys. Defaults to False.
Definition at line 77 of file __init__.py.
) -> None:
    """Pretty prints JSON. Output will be valid JSON.
    Args:
        json (str): A string containing JSON.
        data (Any): If json is not supplied, then encode this data.
        indent (int, optional): Number of spaces to indent. Defaults to 2.
        highlight (bool, optional): Enable highlighting of output: Defaults to True.
        skip_keys (bool, optional): Skip keys not of a basic type. Defaults to False.
        ensure_ascii (bool, optional): Escape all non-ascii characters. Defaults to False.
        check_circular (bool, optional): Check for circular references. Defaults to True.
        allow_nan (bool, optional): Allow NaN and Infinity values. Defaults to True.
        default (Callable, optional): A callable that converts values that can not be encoded
            in to something that can be JSON encoded. Defaults to None.
        sort_keys (bool, optional): Sort dictionary keys. Defaults to False.
    """
    get_console().print_json(
        json,
        data=data,
        indent=indent,
        highlight=highlight,
        skip_keys=skip_keys,
        ensure_ascii=ensure_ascii,
        check_circular=check_circular,
        allow_nan=allow_nan,
        default=default,
        sort_keys=sort_keys,
    )
References get_console(), and print_json().
Referenced by print_json().
reconfigure()
None pip._vendor.rich.reconfigure (*Any args, **Any kwargs)
Reconfigures the global console by replacing it with another.
Args:
    *args (Any): Positional arguments for the replacement :class:`~rich.console.Console`.
    **kwargs (Any): Keyword arguments for the replacement :class:`~rich.console.Console`.
Definition at line 39 of file __init__.py.
def reconfigure(*args: Any, **kwargs: Any) -> None:
    """Reconfigures the global console by replacing it with another.
    Args:
        *args (Any): Positional arguments for the replacement :class:`~rich.console.Console`.
        **kwargs (Any): Keyword arguments for the replacement :class:`~rich.console.Console`.
    """
    from pip._vendor.rich.console import Console
    new_console = Console(*args, **kwargs)
    _console = get_console()
    _console.__dict__ = new_console.__dict__
References get_console().
Variable Documentation
_console
Optional pip._vendor.rich._console = None protected
Definition at line 14 of file __init__.py.
_IMPORT_CWD
str pip._vendor.rich._IMPORT_CWD = os.path.abspath(os.getcwd()) protected
Definition at line 17 of file __init__.py.