Read&Watch: urllib3.connection Namespace Reference
urllib3.connection Namespace Reference
Classes
class _WrappedAndVerifiedSocket
class BaseSSLError
class DummyConnection
class HTTPConnection
class HTTPSConnection
Functions
_WrappedAndVerifiedSocket _ssl_wrap_socket_and_match_hostname (socket.socket sock, *, None|str|int cert_reqs, None|str|int ssl_version, int|None ssl_minimum_version, int|None ssl_maximum_version, str|None cert_file, str|None key_file, str|None key_password, str|None ca_certs, str|None ca_cert_dir, None|str|bytes ca_cert_data, None|str|typing.Literal[False] assert_hostname, str|None assert_fingerprint, str|None server_hostname, ssl.SSLContext|None ssl_context, bool tls_in_tls=False)
None _match_hostname (_TYPE_PEER_CERT_RET_DICT|None cert, str asserted_hostname, bool hostname_checks_common_name=False)
ProxyError _wrap_proxy_error (Exception err, str|None proxy_scheme)
str _get_default_user_agent ()
str _url_from_connection (HTTPConnection|HTTPSConnection conn, str|None path=None)
Variables
BaseSSLError = ssl.SSLError
ssl = None
ConnectionError = ConnectionError
BrokenPipeError = BrokenPipeError
log = logging.getLogger(__name__)
dict port_by_scheme = {"http": 80, "https": 443}
RECENT_DATE = datetime.date(2023, 6, 1)
_CONTAINS_CONTROL_CHAR_RE = re.compile(r"[^-!#$%&'*+.^_`|~0-9a-zA-Z]")
_HAS_SYS_AUDIT = hasattr(sys, "audit")
HTTPSConnection = DummyConnection
VerifiedHTTPSConnection = HTTPSConnection
Function Documentation
_get_default_user_agent()
str urllib3.connection._get_default_user_agent () protected
Definition at line 1011 of file connection.py.
def _get_default_user_agent() -> str:
    return f"python-urllib3/{__version__}"
_match_hostname()
None urllib3.connection._match_hostname (_TYPE_PEER_CERT_RET_DICT | None cert, str asserted_hostname, bool hostname_checks_common_name = False) protected
Definition at line 960 of file connection.py.
) -> None:
    # Our upstream implementation of ssl.match_hostname()
    # only applies this normalization to IP addresses so it doesn't
    # match DNS SANs so we do the same thing!
    stripped_hostname = asserted_hostname.strip("[]")
    if is_ipaddress(stripped_hostname):
        asserted_hostname = stripped_hostname
    try:
        match_hostname(cert, asserted_hostname, hostname_checks_common_name)
    except CertificateError as e:
        log.warning(
            "Certificate did not match expected hostname: %s. Certificate: %s",
            asserted_hostname,
            cert,
        )
        # Add cert to exception and reraise so client code can inspect
        # the cert when catching the exception, if they want to
        e._peer_cert = cert  # type: ignore[attr-defined]
        raise
Referenced by _ssl_wrap_socket_and_match_hostname().
_ssl_wrap_socket_and_match_hostname()
_WrappedAndVerifiedSocket urllib3.connection._ssl_wrap_socket_and_match_hostname (socket.socket sock, * , None | str | int cert_reqs, None | str | int ssl_version, int | None ssl_minimum_version, int | None ssl_maximum_version, str | None cert_file, str | None key_file, str | None key_password, str | None ca_certs, str | None ca_cert_dir, None | str | bytes ca_cert_data, None | str | typing.Literal[False] assert_hostname, str | None assert_fingerprint, str | None server_hostname, ssl.SSLContext | None ssl_context, bool tls_in_tls = False) protected
Logic for constructing an SSLContext from all TLS parameters, passing
that down into ssl_wrap_socket, and then doing certificate verification
either via hostname or fingerprint. This function exists to guarantee
that both proxies and targets have the same behavior when connecting via TLS.
Definition at line 835 of file connection.py.
) -> _WrappedAndVerifiedSocket:
    """Logic for constructing an SSLContext from all TLS parameters, passing
    that down into ssl_wrap_socket, and then doing certificate verification
    either via hostname or fingerprint. This function exists to guarantee
    that both proxies and targets have the same behavior when connecting via TLS.
    """
    default_ssl_context = False
    if ssl_context is None:
        default_ssl_context = True
        context = create_urllib3_context(
            ssl_version=resolve_ssl_version(ssl_version),
            ssl_minimum_version=ssl_minimum_version,
            ssl_maximum_version=ssl_maximum_version,
            cert_reqs=resolve_cert_reqs(cert_reqs),
        )
    else:
        context = ssl_context
    context.verify_mode = resolve_cert_reqs(cert_reqs)
    # In some cases, we want to verify hostnames ourselves
    if (
        # `ssl` can't verify fingerprints or alternate hostnames
        assert_fingerprint
        or assert_hostname
        # assert_hostname can be set to False to disable hostname checking
        or assert_hostname is False
        # We still support OpenSSL 1.0.2, which prevents us from verifying
        # hostnames easily: https://github.com/pyca/pyopenssl/pull/933
        or ssl_.IS_PYOPENSSL
        or not ssl_.HAS_NEVER_CHECK_COMMON_NAME
    ):
        context.check_hostname = False
    # Try to load OS default certs if none are given. We need to do the hasattr() check
    # for custom pyOpenSSL SSLContext objects because they don't support
    # load_default_certs().
    if (
        not ca_certs
        and not ca_cert_dir
        and not ca_cert_data
        and default_ssl_context
        and hasattr(context, "load_default_certs")
    ):
        context.load_default_certs()
    # Ensure that IPv6 addresses are in the proper format and don't have a
    # scope ID. Python's SSL module fails to recognize scoped IPv6 addresses
    # and interprets them as DNS hostnames.
    if server_hostname is not None:
        normalized = server_hostname.strip("[]")
        if "%" in normalized:
            normalized = normalized[: normalized.rfind("%")]
        if is_ipaddress(normalized):
            server_hostname = normalized
    ssl_sock = ssl_wrap_socket(
        sock=sock,
        keyfile=key_file,
        certfile=cert_file,
        key_password=key_password,
        ca_certs=ca_certs,
        ca_cert_dir=ca_cert_dir,
        ca_cert_data=ca_cert_data,
        server_hostname=server_hostname,
        ssl_context=context,
        tls_in_tls=tls_in_tls,
    )
    try:
        if assert_fingerprint:
            _assert_fingerprint(
                ssl_sock.getpeercert(binary_form=True), assert_fingerprint
            )
        elif (
            context.verify_mode != ssl.CERT_NONE
            and not context.check_hostname
            and assert_hostname is not False
        ):
            cert: _TYPE_PEER_CERT_RET_DICT = ssl_sock.getpeercert()  # type: ignore[assignment]
            # Need to signal to our match_hostname whether to use 'commonName' or not.
            # If we're using our own constructed SSLContext we explicitly set 'False'
            # because PyPy hard-codes 'True' from SSLContext.hostname_checks_common_name.
            if default_ssl_context:
                hostname_checks_common_name = False
            else:
                hostname_checks_common_name = (
                    getattr(context, "hostname_checks_common_name", False) or False
                )
            _match_hostname(
                cert,
                assert_hostname or server_hostname,  # type: ignore[arg-type]
                hostname_checks_common_name,
            )
        return _WrappedAndVerifiedSocket(
            socket=ssl_sock,
            is_verified=context.verify_mode == ssl.CERT_REQUIRED
            or bool(assert_fingerprint),
        )
    except BaseException:
        ssl_sock.close()
        raise
References _match_hostname().
Referenced by urllib3.connection.HTTPSConnection._connect_tls_proxy().
_url_from_connection()
str urllib3.connection._url_from_connection (HTTPConnection | HTTPSConnection conn, str | None path = None) protected
Returns the URL from a given connection. This is mainly used for testing and logging.
Definition at line 1026 of file connection.py.
) -> str:
    """Returns the URL from a given connection. This is mainly used for testing and logging."""
    scheme = "https" if isinstance(conn, HTTPSConnection) else "http"
    return Url(scheme=scheme, host=conn.host, port=conn.port, path=path).url
Referenced by urllib3.connection.HTTPConnection.getresponse().
_wrap_proxy_error()
ProxyError urllib3.connection._wrap_proxy_error (Exception err, str | None proxy_scheme) protected
Definition at line 986 of file connection.py.
def _wrap_proxy_error(err: Exception, proxy_scheme: str | None) -> ProxyError:
    # Look for the phrase 'wrong version number', if found
    # then we should warn the user that we're very sure that
    # this proxy is HTTP-only and they have a configuration issue.
    error_normalized = " ".join(re.split("[^a-z]", str(err).lower()))
    is_likely_http_proxy = (
        "wrong version number" in error_normalized
        or "unknown protocol" in error_normalized
        or "record layer failure" in error_normalized
    )
    http_proxy_warning = (
        ". Your proxy appears to only use HTTP and not HTTPS, "
        "try changing your proxy URL to be HTTP. See: "
        "https://urllib3.readthedocs.io/en/latest/advanced-usage.html"
        "#https-proxy-error-http-proxy"
    )
    new_err = ProxyError(
        f"Unable to connect to proxy"
        f"{http_proxy_warning if is_likely_http_proxy and proxy_scheme == 'https' else ''}",
        err,
    )
    new_err.__cause__ = err
    return new_err
Variable Documentation
_CONTAINS_CONTROL_CHAR_RE
urllib3.connection._CONTAINS_CONTROL_CHAR_RE = re.compile(r"[^-!#$%&'*+.^_`|~0-9a-zA-Z]") protected
Definition at line 79 of file connection.py.
_HAS_SYS_AUDIT
urllib3.connection._HAS_SYS_AUDIT = hasattr(sys, "audit") protected
Definition at line 81 of file connection.py.
BaseSSLError
urllib3.connection.BaseSSLError = ssl.SSLError
Definition at line 33 of file connection.py.
BrokenPipeError
urllib3.connection.BrokenPipeError = BrokenPipeError
Definition at line 68 of file connection.py.
ConnectionError
urllib3.connection.ConnectionError = ConnectionError
Definition at line 67 of file connection.py.
HTTPSConnection
urllib3.connection.HTTPSConnection = DummyConnection
Definition at line 1020 of file connection.py.
log
urllib3.connection.log = logging.getLogger(__name__)
Definition at line 71 of file connection.py.
port_by_scheme
dict urllib3.connection.port_by_scheme = {"http": 80, "https": 443}
Definition at line 73 of file connection.py.
RECENT_DATE
urllib3.connection.RECENT_DATE = datetime.date(2023, 6, 1)
Definition at line 77 of file connection.py.
ssl
urllib3.connection.ssl = None
Definition at line 35 of file connection.py.
VerifiedHTTPSConnection
urllib3.connection.VerifiedHTTPSConnection = HTTPSConnection
Definition at line 1023 of file connection.py.