Read&Watch: django.contrib.gis.geos.prototypes.io Namespace Reference
django.contrib.gis.geos.prototypes.io Namespace Reference
Classes
class _WKBReader
class _WKTReader
class IOBase
class ThreadLocalIO
class WKBReader_st
class WKBReadFunc
class WKBWriteFunc
class WKBWriter
class WKBWriter_st
class WKBWriterGet
class WKBWriterSet
class WKTReader_st
class WKTWriter
class WKTWriter_st
Functions
default_trim_value ()
wkt_r ()
wkt_w (dim=2, trim=False, precision=None)
wkb_r ()
wkb_w (dim=2)
ewkb_w (dim=2)
Variables
WKT_READ_PTR = POINTER(WKTReader_st)
WKT_WRITE_PTR = POINTER(WKTWriter_st)
WKB_READ_PTR = POINTER(WKBReader_st)
WKB_WRITE_PTR = POINTER(WKBReader_st)
wkt_reader_create = GEOSFuncFactory("GEOSWKTReader_create", restype=WKT_READ_PTR)
wkt_reader_destroy = GEOSFuncFactory("GEOSWKTReader_destroy", argtypes=[WKT_READ_PTR])
wkt_reader_read
wkt_writer_create = GEOSFuncFactory("GEOSWKTWriter_create", restype=WKT_WRITE_PTR)
wkt_writer_destroy = GEOSFuncFactory("GEOSWKTWriter_destroy", argtypes=[WKT_WRITE_PTR])
wkt_writer_write
wkt_writer_get_outdim
wkt_writer_set_outdim
wkt_writer_set_trim
wkt_writer_set_precision
wkb_reader_create = GEOSFuncFactory("GEOSWKBReader_create", restype=WKB_READ_PTR)
wkb_reader_destroy = GEOSFuncFactory("GEOSWKBReader_destroy", argtypes=[WKB_READ_PTR])
wkb_reader_read = WKBReadFunc("GEOSWKBReader_read")
wkb_reader_read_hex = WKBReadFunc("GEOSWKBReader_readHEX")
wkb_writer_create = GEOSFuncFactory("GEOSWKBWriter_create", restype=WKB_WRITE_PTR)
wkb_writer_destroy = GEOSFuncFactory("GEOSWKBWriter_destroy", argtypes=[WKB_WRITE_PTR])
wkb_writer_write = WKBWriteFunc("GEOSWKBWriter_write")
wkb_writer_write_hex = WKBWriteFunc("GEOSWKBWriter_writeHEX")
wkb_writer_get_byteorder = WKBWriterGet("GEOSWKBWriter_getByteOrder")
wkb_writer_set_byteorder = WKBWriterSet("GEOSWKBWriter_setByteOrder")
wkb_writer_get_outdim = WKBWriterGet("GEOSWKBWriter_getOutputDimension")
wkb_writer_set_outdim = WKBWriterSet("GEOSWKBWriter_setOutputDimension")
wkb_writer_get_include_srid
wkb_writer_set_include_srid
DEFAULT_TRIM_VALUE = SimpleLazyObject(default_trim_value)
thread_context = ThreadLocalIO()
Function Documentation
default_trim_value()
django.contrib.gis.geos.prototypes.io.default_trim_value ()
GEOS changed the default value in 3.12.0. Can be replaced by True when
3.12.0 becomes the minimum supported version.
Definition at line 182 of file io.py.
def default_trim_value():
    """
    GEOS changed the default value in 3.12.0. Can be replaced by True when
    3.12.0 becomes the minimum supported version.
    """
    return geos_version_tuple() >= (3, 12)
ewkb_w()
django.contrib.gis.geos.prototypes.io.ewkb_w (dim = 2)
Definition at line 363 of file io.py.
def ewkb_w(dim=2):
    if not thread_context.ewkb_w:
        thread_context.ewkb_w = WKBWriter(dim=dim)
        thread_context.ewkb_w.srid = True
    else:
        thread_context.ewkb_w.outdim = dim
    return thread_context.ewkb_w
wkb_r()
django.contrib.gis.geos.prototypes.io.wkb_r ()
Definition at line 350 of file io.py.
def wkb_r():
    thread_context.wkb_r = thread_context.wkb_r or _WKBReader()
    return thread_context.wkb_r
wkb_w()
django.contrib.gis.geos.prototypes.io.wkb_w (dim = 2)
Definition at line 355 of file io.py.
def wkb_w(dim=2):
    if not thread_context.wkb_w:
        thread_context.wkb_w = WKBWriter(dim=dim)
    else:
        thread_context.wkb_w.outdim = dim
    return thread_context.wkb_w
wkt_r()
django.contrib.gis.geos.prototypes.io.wkt_r ()
Definition at line 335 of file io.py.
def wkt_r():
    thread_context.wkt_r = thread_context.wkt_r or _WKTReader()
    return thread_context.wkt_r
wkt_w()
django.contrib.gis.geos.prototypes.io.wkt_w (dim = 2, trim = False, precision = None)
Definition at line 340 of file io.py.
def wkt_w(dim=2, trim=False, precision=None):
    if not thread_context.wkt_w:
        thread_context.wkt_w = WKTWriter(dim=dim, trim=trim, precision=precision)
    else:
        thread_context.wkt_w.outdim = dim
        thread_context.wkt_w.trim = trim
        thread_context.wkt_w.precision = precision
    return thread_context.wkt_w
Variable Documentation
DEFAULT_TRIM_VALUE
django.contrib.gis.geos.prototypes.io.DEFAULT_TRIM_VALUE = SimpleLazyObject(default_trim_value)
Definition at line 190 of file io.py.
thread_context
django.contrib.gis.geos.prototypes.io.thread_context = ThreadLocalIO()
Definition at line 330 of file io.py.
WKB_READ_PTR
django.contrib.gis.geos.prototypes.io.WKB_READ_PTR = POINTER(WKBReader_st)
Definition at line 39 of file io.py.
wkb_reader_create
django.contrib.gis.geos.prototypes.io.wkb_reader_create = GEOSFuncFactory("GEOSWKBReader_create", restype=WKB_READ_PTR)
Definition at line 78 of file io.py.
wkb_reader_destroy
django.contrib.gis.geos.prototypes.io.wkb_reader_destroy = GEOSFuncFactory("GEOSWKBReader_destroy", argtypes=[WKB_READ_PTR])
Definition at line 79 of file io.py.
wkb_reader_read
django.contrib.gis.geos.prototypes.io.wkb_reader_read = WKBReadFunc("GEOSWKBReader_read")
Definition at line 93 of file io.py.
wkb_reader_read_hex
django.contrib.gis.geos.prototypes.io.wkb_reader_read_hex = WKBReadFunc("GEOSWKBReader_readHEX")
Definition at line 94 of file io.py.
WKB_WRITE_PTR
django.contrib.gis.geos.prototypes.io.WKB_WRITE_PTR = POINTER(WKBReader_st)
Definition at line 40 of file io.py.
wkb_writer_create
django.contrib.gis.geos.prototypes.io.wkb_writer_create = GEOSFuncFactory("GEOSWKBWriter_create", restype=WKB_WRITE_PTR)
Definition at line 97 of file io.py.
wkb_writer_destroy
django.contrib.gis.geos.prototypes.io.wkb_writer_destroy = GEOSFuncFactory("GEOSWKBWriter_destroy", argtypes=[WKB_WRITE_PTR])
Definition at line 98 of file io.py.
wkb_writer_get_byteorder
django.contrib.gis.geos.prototypes.io.wkb_writer_get_byteorder = WKBWriterGet("GEOSWKBWriter_getByteOrder")
Definition at line 122 of file io.py.
wkb_writer_get_include_srid
django.contrib.gis.geos.prototypes.io.wkb_writer_get_include_srid
Initial value:
=  WKBWriterGet(
    "GEOSWKBWriter_getIncludeSRID", restype=c_byte
)
Definition at line 126 of file io.py.
Referenced by django.contrib.gis.geos.prototypes.io.WKBWriter.srid().
wkb_writer_get_outdim
django.contrib.gis.geos.prototypes.io.wkb_writer_get_outdim = WKBWriterGet("GEOSWKBWriter_getOutputDimension")
Definition at line 124 of file io.py.
Referenced by django.contrib.gis.geos.prototypes.io.WKBWriter.outdim().
wkb_writer_set_byteorder
django.contrib.gis.geos.prototypes.io.wkb_writer_set_byteorder = WKBWriterSet("GEOSWKBWriter_setByteOrder")
Definition at line 123 of file io.py.
Referenced by django.contrib.gis.geos.prototypes.io.WKBWriter._set_byteorder().
wkb_writer_set_include_srid
django.contrib.gis.geos.prototypes.io.wkb_writer_set_include_srid
Initial value:
=  WKBWriterSet(
    "GEOSWKBWriter_setIncludeSRID", argtypes=[WKB_WRITE_PTR, c_byte]
)
Definition at line 129 of file io.py.
Referenced by django.contrib.gis.geos.prototypes.io.WKBWriter.srid().
wkb_writer_set_outdim
django.contrib.gis.geos.prototypes.io.wkb_writer_set_outdim = WKBWriterSet("GEOSWKBWriter_setOutputDimension")
Definition at line 125 of file io.py.
Referenced by django.contrib.gis.geos.prototypes.io.WKBWriter.outdim().
wkb_writer_write
django.contrib.gis.geos.prototypes.io.wkb_writer_write = WKBWriteFunc("GEOSWKBWriter_write")
Definition at line 108 of file io.py.
Referenced by django.contrib.gis.geos.prototypes.io.WKBWriter.write().
wkb_writer_write_hex
django.contrib.gis.geos.prototypes.io.wkb_writer_write_hex = WKBWriteFunc("GEOSWKBWriter_writeHEX")
Definition at line 109 of file io.py.
Referenced by django.contrib.gis.geos.prototypes.io.WKBWriter.write_hex().
WKT_READ_PTR
django.contrib.gis.geos.prototypes.io.WKT_READ_PTR = POINTER(WKTReader_st)
Definition at line 37 of file io.py.
wkt_reader_create
django.contrib.gis.geos.prototypes.io.wkt_reader_create = GEOSFuncFactory("GEOSWKTReader_create", restype=WKT_READ_PTR)
Definition at line 43 of file io.py.
wkt_reader_destroy
django.contrib.gis.geos.prototypes.io.wkt_reader_destroy = GEOSFuncFactory("GEOSWKTReader_destroy", argtypes=[WKT_READ_PTR])
Definition at line 44 of file io.py.
wkt_reader_read
django.contrib.gis.geos.prototypes.io.wkt_reader_read
Initial value:
=  GEOSFuncFactory(
    "GEOSWKTReader_read",
    argtypes=[WKT_READ_PTR, c_char_p],
    restype=GEOM_PTR,
    errcheck=check_geom,
)
Definition at line 46 of file io.py.
WKT_WRITE_PTR
django.contrib.gis.geos.prototypes.io.WKT_WRITE_PTR = POINTER(WKTWriter_st)
Definition at line 38 of file io.py.
wkt_writer_create
django.contrib.gis.geos.prototypes.io.wkt_writer_create = GEOSFuncFactory("GEOSWKTWriter_create", restype=WKT_WRITE_PTR)
Definition at line 53 of file io.py.
wkt_writer_destroy
django.contrib.gis.geos.prototypes.io.wkt_writer_destroy = GEOSFuncFactory("GEOSWKTWriter_destroy", argtypes=[WKT_WRITE_PTR])
Definition at line 54 of file io.py.
wkt_writer_get_outdim
django.contrib.gis.geos.prototypes.io.wkt_writer_get_outdim
Initial value:
=  GEOSFuncFactory(
    "GEOSWKTWriter_getOutputDimension", argtypes=[WKT_WRITE_PTR], restype=c_int
)
Definition at line 63 of file io.py.
Referenced by django.contrib.gis.geos.prototypes.io.WKTWriter.outdim().
wkt_writer_set_outdim
django.contrib.gis.geos.prototypes.io.wkt_writer_set_outdim
Initial value:
=  GEOSFuncFactory(
    "GEOSWKTWriter_setOutputDimension", argtypes=[WKT_WRITE_PTR, c_int]
)
Definition at line 66 of file io.py.
Referenced by django.contrib.gis.geos.prototypes.io.WKTWriter.outdim().
wkt_writer_set_precision
django.contrib.gis.geos.prototypes.io.wkt_writer_set_precision
Initial value:
=  GEOSFuncFactory(
    "GEOSWKTWriter_setRoundingPrecision", argtypes=[WKT_WRITE_PTR, c_int]
)
Definition at line 73 of file io.py.
Referenced by django.contrib.gis.geos.prototypes.io.WKTWriter.precision().
wkt_writer_set_trim
django.contrib.gis.geos.prototypes.io.wkt_writer_set_trim
Initial value:
=  GEOSFuncFactory(
    "GEOSWKTWriter_setTrim", argtypes=[WKT_WRITE_PTR, c_byte]
)
Definition at line 70 of file io.py.
Referenced by django.contrib.gis.geos.prototypes.io.WKTWriter.trim().
wkt_writer_write
django.contrib.gis.geos.prototypes.io.wkt_writer_write
Initial value:
=  GEOSFuncFactory(
    "GEOSWKTWriter_write",
    argtypes=[WKT_WRITE_PTR, GEOM_PTR],
    restype=geos_char_p,
    errcheck=check_string,
)
Definition at line 56 of file io.py.