Read&Watch: django.core.serializers.xml_serializer Namespace Reference
django.core.serializers.xml_serializer Namespace Reference
Classes
class DefusedExpatParser
class DefusedXmlException
class Deserializer
class DTDForbidden
class EntitiesForbidden
class ExternalReferenceForbidden
class Serializer
Functions
getInnerText (node)
Detailed Description
XML serializer.
Function Documentation
getInnerText()
django.core.serializers.xml_serializer.getInnerText (node)
Get all the inner text of a DOM node (recursively).
Definition at line 394 of file xml_serializer.py.
def getInnerText(node):
    """Get all the inner text of a DOM node (recursively)."""
    # inspired by https://mail.python.org/pipermail/xml-sig/2005-March/011022.html
    inner_text = []
    for child in node.childNodes:
        if (
            child.nodeType == child.TEXT_NODE
            or child.nodeType == child.CDATA_SECTION_NODE
        ):
            inner_text.append(child.data)
        elif child.nodeType == child.ELEMENT_NODE:
            inner_text.extend(getInnerText(child))
        else:
            pass
    return "".join(inner_text)
# Below code based on Christian Heimes' defusedxml
References getInnerText().
Referenced by django.core.serializers.xml_serializer.Deserializer._handle_fk_field_node(), django.core.serializers.xml_serializer.Deserializer._handle_m2m_field_node(), django.core.serializers.xml_serializer.Deserializer._handle_object(), and getInnerText().