Read&Watch: urllib3.util.ssl_ Namespace Reference
urllib3.util.ssl_ Namespace Reference
Classes
class _TYPE_PEER_CERT_RET_DICT
Functions
bool _is_bpo_43522_fixed (str implementation_name, _TYPE_VERSION_INFO version_info, _TYPE_VERSION_INFO|None pypy_version_info)
bool _is_has_never_check_common_name_reliable (str openssl_version, int openssl_version_number, str implementation_name, _TYPE_VERSION_INFO version_info, _TYPE_VERSION_INFO|None pypy_version_info)
None assert_fingerprint (bytes|None cert, str fingerprint)
VerifyMode resolve_cert_reqs (None|int|str candidate)
int resolve_ssl_version (None|int|str candidate)
ssl.SSLContext create_urllib3_context (int|None ssl_version=None, int|None cert_reqs=None, int|None options=None, str|None ciphers=None, int|None ssl_minimum_version=None, int|None ssl_maximum_version=None)
ssl.SSLSocket ssl_wrap_socket (socket.socket sock, str|None keyfile=..., str|None certfile=..., int|None cert_reqs=..., str|None ca_certs=..., str|None server_hostname=..., int|None ssl_version=..., str|None ciphers=..., ssl.SSLContext|None ssl_context=..., str|None ca_cert_dir=..., str|None key_password=..., None|str|bytes ca_cert_data=..., typing.Literal[False] tls_in_tls=...)
ssl.SSLSocket|SSLTransportType ssl_wrap_socket (socket.socket sock, str|None keyfile=..., str|None certfile=..., int|None cert_reqs=..., str|None ca_certs=..., str|None server_hostname=..., int|None ssl_version=..., str|None ciphers=..., ssl.SSLContext|None ssl_context=..., str|None ca_cert_dir=..., str|None key_password=..., None|str|bytes ca_cert_data=..., bool tls_in_tls=...)
bool is_ipaddress (str|bytes hostname)
bool _is_key_file_encrypted (str key_file)
ssl.SSLSocket|SSLTransportType _ssl_wrap_socket_impl (socket.socket sock, ssl.SSLContext ssl_context, bool tls_in_tls, str|None server_hostname=None)
Variables
SSLContext = None
SSLTransport = None
bool HAS_NEVER_CHECK_COMMON_NAME = False
bool IS_PYOPENSSL = False
list ALPN_PROTOCOLS = ["http/1.1"]
_TYPE_VERSION_INFO = typing.Tuple[int, int, int, str, int]
dict HASHFUNC_MAP
PROTOCOL_SSLv23 = PROTOCOL_TLS
int OP_NO_COMPRESSION = 0x20000
int OP_NO_TICKET = 0x4000
int OP_NO_SSLv2 = 0x1000000
int OP_NO_SSLv3 = 0x2000000
int PROTOCOL_TLS_CLIENT = 16
_TYPE_PEER_CERT_RET = typing.Union["_TYPE_PEER_CERT_RET_DICT", bytes, None]
Function Documentation
_is_bpo_43522_fixed()
bool urllib3.util.ssl_._is_bpo_43522_fixed (str implementation_name, _TYPE_VERSION_INFO version_info, _TYPE_VERSION_INFO | None pypy_version_info) protected
Return True for CPython 3.8.9+, 3.9.3+ or 3.10+ and PyPy 7.3.8+ where
setting SSLContext.hostname_checks_common_name to False works.
Outside of CPython and PyPy we don't know which implementations work
or not so we conservatively use our hostname matching as we know that works
on all implementations.
https://github.com/urllib3/urllib3/issues/2192#issuecomment-821832963
https://foss.heptapod.net/pypy/pypy/-/issues/3539
Definition at line 30 of file ssl_.py.
) -> bool:
    """Return True for CPython 3.8.9+, 3.9.3+ or 3.10+ and PyPy 7.3.8+ where
    setting SSLContext.hostname_checks_common_name to False works.
    Outside of CPython and PyPy we don't know which implementations work
    or not so we conservatively use our hostname matching as we know that works
    on all implementations.
    https://github.com/urllib3/urllib3/issues/2192#issuecomment-821832963
    https://foss.heptapod.net/pypy/pypy/-/issues/3539
    """
    if implementation_name == "pypy":
        # https://foss.heptapod.net/pypy/pypy/-/issues/3129
        return pypy_version_info >= (7, 3, 8)  # type: ignore[operator]
    elif implementation_name == "cpython":
        major_minor = version_info[:2]
        micro = version_info[2]
        return (
            (major_minor == (3, 8) and micro >= 9)
            or (major_minor == (3, 9) and micro >= 3)
            or major_minor >= (3, 10)
        )
    else:  # Defensive:
        return False
Referenced by _is_has_never_check_common_name_reliable().
_is_has_never_check_common_name_reliable()
bool urllib3.util.ssl_._is_has_never_check_common_name_reliable (str openssl_version, int openssl_version_number, str implementation_name, _TYPE_VERSION_INFO version_info, _TYPE_VERSION_INFO | None pypy_version_info) protected
Definition at line 60 of file ssl_.py.
) -> bool:
    # As of May 2023, all released versions of LibreSSL fail to reject certificates with
    # only common names, see https://github.com/urllib3/urllib3/pull/3024
    is_openssl = openssl_version.startswith("OpenSSL ")
    # Before fixing OpenSSL issue #14579, the SSL_new() API was not copying hostflags
    # like X509_CHECK_FLAG_NEVER_CHECK_SUBJECT, which tripped up CPython.
    # https://github.com/openssl/openssl/issues/14579
    # This was released in OpenSSL 1.1.1l+ (>=0x101010cf)
    is_openssl_issue_14579_fixed = openssl_version_number >= 0x101010CF
    return is_openssl and (
        is_openssl_issue_14579_fixed
        or _is_bpo_43522_fixed(implementation_name, version_info, pypy_version_info)
    )
References _is_bpo_43522_fixed().
_is_key_file_encrypted()
bool urllib3.util.ssl_._is_key_file_encrypted (str key_file) protected
Detects if a key file is encrypted or not.
Definition at line 486 of file ssl_.py.
def _is_key_file_encrypted(key_file: str) -> bool:
    """Detects if a key file is encrypted or not."""
    with open(key_file) as f:
        for line in f:
            # Look for Proc-Type: 4,ENCRYPTED
            if "ENCRYPTED" in line:
                return True
    return False
Referenced by ssl_wrap_socket().
_ssl_wrap_socket_impl()
ssl.SSLSocket | SSLTransportType urllib3.util.ssl_._ssl_wrap_socket_impl (socket.socket sock, ssl.SSLContext ssl_context, bool tls_in_tls, str | None server_hostname = None) protected
Definition at line 497 of file ssl_.py.
) -> ssl.SSLSocket | SSLTransportType:
    if tls_in_tls:
        if not SSLTransport:
            # Import error, ssl is not available.
            raise ProxySchemeUnsupported(
                "TLS in TLS requires support for the 'ssl' module"
            )
        SSLTransport._validate_ssl_context_for_tls_in_tls(ssl_context)
        return SSLTransport(sock, ssl_context, server_hostname)
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
Referenced by ssl_wrap_socket().
assert_fingerprint()
None urllib3.util.ssl_.assert_fingerprint (bytes | None cert, str fingerprint)
Checks if given fingerprint matches the supplied certificate.
:param cert:
    Certificate as bytes object.
:param fingerprint:
    Fingerprint as string of hexdigits, can be interspersed by colons.
Definition at line 150 of file ssl_.py.
def assert_fingerprint(cert: bytes | None, fingerprint: str) -> None:
    """
    Checks if given fingerprint matches the supplied certificate.
    :param cert:
        Certificate as bytes object.
    :param fingerprint:
        Fingerprint as string of hexdigits, can be interspersed by colons.
    """
    if cert is None:
        raise SSLError("No certificate for the peer.")
    fingerprint = fingerprint.replace(":", "").lower()
    digest_length = len(fingerprint)
    if digest_length not in HASHFUNC_MAP:
        raise SSLError(f"Fingerprint of invalid length: {fingerprint}")
    hashfunc = HASHFUNC_MAP.get(digest_length)
    if hashfunc is None:
        raise SSLError(
            f"Hash function implementation unavailable for fingerprint length: {digest_length}"
        )
    # We need encode() here for py32; works on py2 and p33.
    fingerprint_bytes = unhexlify(fingerprint.encode())
    cert_digest = hashfunc(cert).digest()
    if not hmac.compare_digest(cert_digest, fingerprint_bytes):
        raise SSLError(
            f'Fingerprints did not match. Expected "{fingerprint}", got "{cert_digest.hex()}"'
        )
create_urllib3_context()
ssl.SSLContext urllib3.util.ssl_.create_urllib3_context (int | None ssl_version = None, int | None cert_reqs = None, int | None options = None, str | None ciphers = None, int | None ssl_minimum_version = None, int | None ssl_maximum_version = None)
Creates and configures an :class:`ssl.SSLContext` instance for use with urllib3.
:param ssl_version:
    The desired protocol version to use. This will default to
    PROTOCOL_SSLv23 which will negotiate the highest protocol that both
    the server and your installation of OpenSSL support.
    This parameter is deprecated instead use 'ssl_minimum_version'.
:param ssl_minimum_version:
    The minimum version of TLS to be used. Use the 'ssl.TLSVersion' enum for specifying the value.
:param ssl_maximum_version:
    The maximum version of TLS to be used. Use the 'ssl.TLSVersion' enum for specifying the value.
    Not recommended to set to anything other than 'ssl.TLSVersion.MAXIMUM_SUPPORTED' which is the
    default value.
:param cert_reqs:
    Whether to require the certificate verification. This defaults to
    ``ssl.CERT_REQUIRED``.
:param options:
    Specific OpenSSL options. These default to ``ssl.OP_NO_SSLv2``,
    ``ssl.OP_NO_SSLv3``, ``ssl.OP_NO_COMPRESSION``, and ``ssl.OP_NO_TICKET``.
:param ciphers:
    Which cipher suites to allow the server to select. Defaults to either system configured
    ciphers if OpenSSL 1.1.1+, otherwise uses a secure default set of ciphers.
:returns:
    Constructed SSLContext object with specified options
:rtype: SSLContext
Definition at line 223 of file ssl_.py.
) -> ssl.SSLContext:
    """Creates and configures an :class:`ssl.SSLContext` instance for use with urllib3.
    :param ssl_version:
        The desired protocol version to use. This will default to
        PROTOCOL_SSLv23 which will negotiate the highest protocol that both
        the server and your installation of OpenSSL support.
        This parameter is deprecated instead use 'ssl_minimum_version'.
    :param ssl_minimum_version:
        The minimum version of TLS to be used. Use the 'ssl.TLSVersion' enum for specifying the value.
    :param ssl_maximum_version:
        The maximum version of TLS to be used. Use the 'ssl.TLSVersion' enum for specifying the value.
        Not recommended to set to anything other than 'ssl.TLSVersion.MAXIMUM_SUPPORTED' which is the
        default value.
    :param cert_reqs:
        Whether to require the certificate verification. This defaults to
        ``ssl.CERT_REQUIRED``.
    :param options:
        Specific OpenSSL options. These default to ``ssl.OP_NO_SSLv2``,
        ``ssl.OP_NO_SSLv3``, ``ssl.OP_NO_COMPRESSION``, and ``ssl.OP_NO_TICKET``.
    :param ciphers:
        Which cipher suites to allow the server to select. Defaults to either system configured
        ciphers if OpenSSL 1.1.1+, otherwise uses a secure default set of ciphers.
    :returns:
        Constructed SSLContext object with specified options
    :rtype: SSLContext
    """
    if SSLContext is None:
        raise TypeError("Can't create an SSLContext object without an ssl module")
    # This means 'ssl_version' was specified as an exact value.
    if ssl_version not in (None, PROTOCOL_TLS, PROTOCOL_TLS_CLIENT):
        # Disallow setting 'ssl_version' and 'ssl_minimum|maximum_version'
        # to avoid conflicts.
        if ssl_minimum_version is not None or ssl_maximum_version is not None:
            raise ValueError(
                "Can't specify both 'ssl_version' and either "
                "'ssl_minimum_version' or 'ssl_maximum_version'"
            )
        # 'ssl_version' is deprecated and will be removed in the future.
        else:
            # Use 'ssl_minimum_version' and 'ssl_maximum_version' instead.
            ssl_minimum_version = _SSL_VERSION_TO_TLS_VERSION.get(
                ssl_version, TLSVersion.MINIMUM_SUPPORTED
            )
            ssl_maximum_version = _SSL_VERSION_TO_TLS_VERSION.get(
                ssl_version, TLSVersion.MAXIMUM_SUPPORTED
            )
            # This warning message is pushing users to use 'ssl_minimum_version'
            # instead of both min/max. Best practice is to only set the minimum version and
            # keep the maximum version to be it's default value: 'TLSVersion.MAXIMUM_SUPPORTED'
            warnings.warn(
                "'ssl_version' option is deprecated and will be "
                "removed in urllib3 v2.1.0. Instead use 'ssl_minimum_version'",
                category=DeprecationWarning,
                stacklevel=2,
            )
    # PROTOCOL_TLS is deprecated in Python 3.10 so we always use PROTOCOL_TLS_CLIENT
    context = SSLContext(PROTOCOL_TLS_CLIENT)
    if ssl_minimum_version is not None:
        context.minimum_version = ssl_minimum_version
    else:  # Python <3.10 defaults to 'MINIMUM_SUPPORTED' so explicitly set TLSv1.2 here
        context.minimum_version = TLSVersion.TLSv1_2
    if ssl_maximum_version is not None:
        context.maximum_version = ssl_maximum_version
    # Unless we're given ciphers defer to either system ciphers in
    # the case of OpenSSL 1.1.1+ or use our own secure default ciphers.
    if ciphers:
        context.set_ciphers(ciphers)
    # Setting the default here, as we may have no ssl module on import
    cert_reqs = ssl.CERT_REQUIRED if cert_reqs is None else cert_reqs
    if options is None:
        options = 0
        # SSLv2 is easily broken and is considered harmful and dangerous
        options |= OP_NO_SSLv2
        # SSLv3 has several problems and is now dangerous
        options |= OP_NO_SSLv3
        # Disable compression to prevent CRIME attacks for OpenSSL 1.0+
        # (issue #309)
        options |= OP_NO_COMPRESSION
        # TLSv1.2 only. Unless set explicitly, do not request tickets.
        # This may save some bandwidth on wire, and although the ticket is encrypted,
        # there is a risk associated with it being on wire,
        # if the server is not rotating its ticketing keys properly.
        options |= OP_NO_TICKET
    context.options |= options
    # Enable post-handshake authentication for TLS 1.3, see GH #1634. PHA is
    # necessary for conditional client cert authentication with TLS 1.3.
    # The attribute is None for OpenSSL <= 1.1.0 or does not exist when using
    # an SSLContext created by pyOpenSSL.
    if getattr(context, "post_handshake_auth", None) is not None:
        context.post_handshake_auth = True
    # The order of the below lines setting verify_mode and check_hostname
    # matter due to safe-guards SSLContext has to prevent an SSLContext with
    # check_hostname=True, verify_mode=NONE/OPTIONAL.
    # We always set 'check_hostname=False' for pyOpenSSL so we rely on our own
    # 'ssl.match_hostname()' implementation.
    if cert_reqs == ssl.CERT_REQUIRED and not IS_PYOPENSSL:
        context.verify_mode = cert_reqs
        context.check_hostname = True
    else:
        context.check_hostname = False
        context.verify_mode = cert_reqs
    try:
        context.hostname_checks_common_name = False
    except AttributeError:  # Defensive: for CPython < 3.8.9 and 3.9.3; for PyPy < 7.3.8
        pass
    # Enable logging of TLS session keys via defacto standard environment variable
    # 'SSLKEYLOGFILE', if the feature is available (Python 3.8+). Skip empty values.
    if hasattr(context, "keylog_filename"):
        sslkeylogfile = os.environ.get("SSLKEYLOGFILE")
        if sslkeylogfile:
            context.keylog_filename = sslkeylogfile
    return context
@typing.overload
References SSLContext.
Referenced by ssl_wrap_socket().
is_ipaddress()
bool urllib3.util.ssl_.is_ipaddress (str | bytes hostname)
Detects whether the hostname given is an IPv4 or IPv6 address.
Also detects IPv6 addresses with Zone IDs.
:param str hostname: Hostname to examine.
:return: True if the hostname is an IP address, False otherwise.
Definition at line 473 of file ssl_.py.
def is_ipaddress(hostname: str | bytes) -> bool:
    """Detects whether the hostname given is an IPv4 or IPv6 address.
    Also detects IPv6 addresses with Zone IDs.
    :param str hostname: Hostname to examine.
    :return: True if the hostname is an IP address, False otherwise.
    """
    if isinstance(hostname, bytes):
        # IDN A-label bytes are ASCII compatible.
        hostname = hostname.decode("ascii")
    return bool(_IPV4_RE.match(hostname) or _BRACELESS_IPV6_ADDRZ_RE.match(hostname))
resolve_cert_reqs()
VerifyMode urllib3.util.ssl_.resolve_cert_reqs (None | int | str candidate)
Resolves the argument to a numeric constant, which can be passed to
the wrap_socket function/method from the ssl module.
Defaults to :data:`ssl.CERT_REQUIRED`.
If given a string it is assumed to be the name of the constant in the
:mod:`ssl` module or its abbreviation.
(So you can specify `REQUIRED` instead of `CERT_REQUIRED`.
If it's neither `None` nor a string we assume it is already the numeric
constant which can directly be passed to wrap_socket.
Definition at line 184 of file ssl_.py.
def resolve_cert_reqs(candidate: None | int | str) -> VerifyMode:
    """
    Resolves the argument to a numeric constant, which can be passed to
    the wrap_socket function/method from the ssl module.
    Defaults to :data:`ssl.CERT_REQUIRED`.
    If given a string it is assumed to be the name of the constant in the
    :mod:`ssl` module or its abbreviation.
    (So you can specify `REQUIRED` instead of `CERT_REQUIRED`.
    If it's neither `None` nor a string we assume it is already the numeric
    constant which can directly be passed to wrap_socket.
    """
    if candidate is None:
        return CERT_REQUIRED
    if isinstance(candidate, str):
        res = getattr(ssl, candidate, None)
        if res is None:
            res = getattr(ssl, "CERT_" + candidate)
        return res  # type: ignore[no-any-return]
    return candidate  # type: ignore[return-value]
resolve_ssl_version()
int urllib3.util.ssl_.resolve_ssl_version (None | int | str candidate)
like resolve_cert_reqs
Definition at line 207 of file ssl_.py.
def resolve_ssl_version(candidate: None | int | str) -> int:
    """
    like resolve_cert_reqs
    """
    if candidate is None:
        return PROTOCOL_TLS
    if isinstance(candidate, str):
        res = getattr(ssl, candidate, None)
        if res is None:
            res = getattr(ssl, "PROTOCOL_" + candidate)
        return typing.cast(int, res)
    return candidate
ssl_wrap_socket() [1/2]
ssl SSLSocket SSLTransportType urllib3.util.ssl_.ssl_wrap_socket (socket.socket sock, str|None keyfile = None, str|None certfile = None, int|None cert_reqs = None, str|None ca_certs = None, str|None server_hostname = None, int|None ssl_version = None, str|None ciphers = None, ssl.SSLContext|None ssl_context = None, str|None ca_cert_dir = None, str|None key_password = None, None|str|bytes ca_cert_data = None, bool tls_in_tls = False)
All arguments except for server_hostname, ssl_context, tls_in_tls, ca_cert_data and
ca_cert_dir have the same meaning as they do when using
:func:`ssl.create_default_context`, :meth:`ssl.SSLContext.load_cert_chain`,
:meth:`ssl.SSLContext.set_ciphers` and :meth:`ssl.SSLContext.wrap_socket`.
:param server_hostname:
    When SNI is supported, the expected hostname of the certificate
:param ssl_context:
    A pre-made :class:`SSLContext` object. If none is provided, one will
    be created using :func:`create_urllib3_context`.
:param ciphers:
    A string of ciphers we wish the client to support.
:param ca_cert_dir:
    A directory containing CA certificates in multiple separate files, as
    supported by OpenSSL's -CApath flag or the capath argument to
    SSLContext.load_verify_locations().
:param key_password:
    Optional password if the keyfile is encrypted.
:param ca_cert_data:
    Optional string containing CA certificates in PEM format suitable for
    passing as the cadata parameter to SSLContext.load_verify_locations()
:param tls_in_tls:
    Use SSLTransport to wrap the existing socket.
Definition at line 381 of file ssl_.py.
) -> ssl.SSLSocket | SSLTransportType:
    ...
References _is_key_file_encrypted(), _ssl_wrap_socket_impl(), and create_urllib3_context().
ssl_wrap_socket() [2/2]
ssl.SSLSocket urllib3.util.ssl_.ssl_wrap_socket (socket.socket sock, str | None keyfile = ..., str | None certfile = ..., int | None cert_reqs = ..., str | None ca_certs = ..., str | None server_hostname = ..., int | None ssl_version = ..., str | None ciphers = ..., ssl.SSLContext | None ssl_context = ..., str | None ca_cert_dir = ..., str | None key_password = ..., None | str | bytes ca_cert_data = ..., typing.Literal[False] tls_in_tls = ...)
Definition at line 362 of file ssl_.py.
) -> ssl.SSLSocket:
    ...
@typing.overload
Variable Documentation
_TYPE_PEER_CERT_RET
urllib3.util.ssl_._TYPE_PEER_CERT_RET = typing.Union["_TYPE_PEER_CERT_RET_DICT", bytes, None] protected
Definition at line 147 of file ssl_.py.
_TYPE_VERSION_INFO
urllib3.util.ssl_._TYPE_VERSION_INFO = typing.Tuple[int, int, int, str, int] protected
Definition at line 21 of file ssl_.py.
ALPN_PROTOCOLS
list urllib3.util.ssl_.ALPN_PROTOCOLS = ["http/1.1"]
Definition at line 19 of file ssl_.py.
HAS_NEVER_CHECK_COMMON_NAME
bool urllib3.util.ssl_.HAS_NEVER_CHECK_COMMON_NAME = False
Definition at line 17 of file ssl_.py.
HASHFUNC_MAP
dict urllib3.util.ssl_.HASHFUNC_MAP
Initial value:
=  {
    length: getattr(hashlib, algorithm, None)
    for length, algorithm in ((32, "md5"), (40, "sha1"), (64, "sha256"))
}
Definition at line 24 of file ssl_.py.
IS_PYOPENSSL
bool urllib3.util.ssl_.IS_PYOPENSSL = False
Definition at line 18 of file ssl_.py.
OP_NO_COMPRESSION
int urllib3.util.ssl_.OP_NO_COMPRESSION = 0x20000
Definition at line 139 of file ssl_.py.
OP_NO_SSLv2
int urllib3.util.ssl_.OP_NO_SSLv2 = 0x1000000
Definition at line 141 of file ssl_.py.
OP_NO_SSLv3
int urllib3.util.ssl_.OP_NO_SSLv3 = 0x2000000
Definition at line 142 of file ssl_.py.
OP_NO_TICKET
int urllib3.util.ssl_.OP_NO_TICKET = 0x4000
Definition at line 140 of file ssl_.py.
PROTOCOL_SSLv23
int urllib3.util.ssl_.PROTOCOL_SSLv23 = PROTOCOL_TLS
Definition at line 114 of file ssl_.py.
PROTOCOL_TLS_CLIENT
int urllib3.util.ssl_.PROTOCOL_TLS_CLIENT = 16
Definition at line 144 of file ssl_.py.
SSLContext
urllib3.util.ssl_.SSLContext = None
Definition at line 15 of file ssl_.py.
Referenced by create_urllib3_context().
SSLTransport
urllib3.util.ssl_.SSLTransport = None
Definition at line 16 of file ssl_.py.