Read&Watch: django.utils.text Namespace Reference
django.utils.text Namespace Reference
Classes
class StreamingBuffer
class TruncateCharsHTMLParser
class TruncateHTMLParser
class TruncateWordsHTMLParser
class Truncator
Functions
capfirst (x)
wrap (text, width)
add_truncation_text (text, truncate=None)
calculate_truncate_chars_length (length, replacement)
get_valid_filename (name)
get_text_list (list_, last_word=gettext_lazy("or"))
normalize_newlines (text)
phone2numeric (phone)
_get_random_filename (max_random_bytes)
compress_string (s, *, max_random_bytes=None)
compress_sequence (sequence, *, max_random_bytes=None)
smart_split (text)
unescape_string_literal (s)
slugify (value, allow_unicode=False)
camel_case_to_spaces (value)
_format_lazy (format_string, *args, **kwargs)
Variables
re_newlines = _lazy_re_compile(r"\r\n|\r")
re_camel_case = _lazy_re_compile(r"(((?<=[a-z])[A-Z])|([A-Z](?![A-Z]|$)))")
smart_split_re
format_lazy = lazy(_format_lazy, str)
Function Documentation
_format_lazy()
django.utils.text._format_lazy (format_string, * args, ** kwargs) protected
Apply str.format() on 'format_string' where format_string, args,
and/or kwargs might be lazy.
Definition at line 479 of file text.py.
def _format_lazy(format_string, *args, **kwargs):
    """
    Apply str.format() on 'format_string' where format_string, args,
    and/or kwargs might be lazy.
    """
    return format_string.format(*args, **kwargs)
_get_random_filename()
django.utils.text._get_random_filename (max_random_bytes) protected
Definition at line 351 of file text.py.
def _get_random_filename(max_random_bytes):
    return b"a" * secrets.randbelow(max_random_bytes)
Referenced by compress_sequence(), and compress_string().
add_truncation_text()
django.utils.text.add_truncation_text (text, truncate = None)
Definition at line 72 of file text.py.
def add_truncation_text(text, truncate=None):
    if truncate is None:
        truncate = pgettext(
            "String to return when truncating text", "%(truncated_text)s…"
        )
    if "%(truncated_text)s" in truncate:
        return truncate % {"truncated_text": text}
    # The truncation text didn't contain the %(truncated_text)s string
    # replacement argument so just append it to the text.
    if text.endswith(truncate):
        # But don't append the truncation text if the current text already ends
        # in this.
        return text
    return f"{text}{truncate}"
Referenced by django.utils.text.Truncator._text_chars(), django.utils.text.Truncator._text_words(), calculate_truncate_chars_length(), and django.utils.text.TruncateHTMLParser.handle_data().
calculate_truncate_chars_length()
django.utils.text.calculate_truncate_chars_length (length, replacement)
Definition at line 88 of file text.py.
def calculate_truncate_chars_length(length, replacement):
    truncate_len = length
    for char in add_truncation_text("", replacement):
        if not unicodedata.combining(char):
            truncate_len -= 1
            if truncate_len == 0:
                break
    return truncate_len
References add_truncation_text().
Referenced by django.utils.text.Truncator._text_chars().
camel_case_to_spaces()
django.utils.text.camel_case_to_spaces (value)
Split CamelCase and convert to lowercase. Strip surrounding whitespace.
Definition at line 472 of file text.py.
def camel_case_to_spaces(value):
    """
    Split CamelCase and convert to lowercase. Strip surrounding whitespace.
    """
    return re_camel_case.sub(r" \1", value).strip().lower()
capfirst()
django.utils.text.capfirst (x)
Capitalize the first letter of a string.
Definition at line 25 of file text.py.
def capfirst(x):
    """Capitalize the first letter of a string."""
    if not x:
        return x
    if not isinstance(x, str):
        x = str(x)
    return x[0].upper() + x[1:]
# Set up regular expressions
compress_sequence()
django.utils.text.compress_sequence (sequence, * , max_random_bytes = None)
Definition at line 379 of file text.py.
def compress_sequence(sequence, *, max_random_bytes=None):
    buf = StreamingBuffer()
    filename = _get_random_filename(max_random_bytes) if max_random_bytes else None
    with GzipFile(
        filename=filename, mode="wb", compresslevel=6, fileobj=buf, mtime=0
    ) as zfile:
        # Output headers...
        yield buf.read()
        for item in sequence:
            zfile.write(item)
            data = buf.read()
            if data:
                yield data
    yield buf.read()
# Expression to match some_token and some_token="with spaces" (and similarly
# for single-quoted strings).
References _get_random_filename().
compress_string()
django.utils.text.compress_string (s, * , max_random_bytes = None)
Definition at line 355 of file text.py.
def compress_string(s, *, max_random_bytes=None):
    compressed_data = gzip_compress(s, compresslevel=6, mtime=0)
    if not max_random_bytes:
        return compressed_data
    compressed_view = memoryview(compressed_data)
    header = bytearray(compressed_view[:10])
    header[3] = gzip.FNAME
    filename = _get_random_filename(max_random_bytes) + b"\x00"
    return bytes(header) + filename + compressed_view[10:]
References _get_random_filename().
get_text_list()
django.utils.text.get_text_list (list_, last_word = gettext_lazy("or"))
>>> get_text_list(['a', 'b', 'c', 'd'])
'a, b, c or d'
>>> get_text_list(['a', 'b', 'c'], 'and')
'a, b and c'
>>> get_text_list(['a', 'b'], 'and')
'a and b'
>>> get_text_list(['a'])
'a'
>>> get_text_list([])
''
Definition at line 286 of file text.py.
def get_text_list(list_, last_word=gettext_lazy("or")):
    """
    >>> get_text_list(['a', 'b', 'c', 'd'])
    'a, b, c or d'
    >>> get_text_list(['a', 'b', 'c'], 'and')
    'a, b and c'
    >>> get_text_list(['a', 'b'], 'and')
    'a and b'
    >>> get_text_list(['a'])
    'a'
    >>> get_text_list([])
    ''
    """
    if not list_:
        return ""
    if len(list_) == 1:
        return str(list_[0])
    return "%s %s %s" % (
        # Translators: This string is used as a separator between list elements
        _(", ").join(str(i) for i in list_[:-1]),
        str(last_word),
        str(list_[-1]),
    )
@keep_lazy_text
get_valid_filename()
django.utils.text.get_valid_filename (name)
Return the given string converted to a string that can be used for a clean
filename. Remove leading and trailing spaces; convert other spaces to
underscores; and remove anything that is not an alphanumeric, dash,
underscore, or dot.
>>> get_valid_filename("john's portrait in 2004.jpg")
'johns_portrait_in_2004.jpg'
Definition at line 269 of file text.py.
def get_valid_filename(name):
    """
    Return the given string converted to a string that can be used for a clean
    filename. Remove leading and trailing spaces; convert other spaces to
    underscores; and remove anything that is not an alphanumeric, dash,
    underscore, or dot.
    >>> get_valid_filename("john's portrait in 2004.jpg")
    'johns_portrait_in_2004.jpg'
    """
    s = str(name).strip().replace(" ", "_")
    s = re.sub(r"(?u)[^-\w.]", "", s)
    if s in {"", ".", ".."}:
        raise SuspiciousFileOperation("Could not derive file name from '%s'" % name)
    return s
@keep_lazy_text
normalize_newlines()
django.utils.text.normalize_newlines (text)
Normalize CRLF and CR newlines to just LF.
Definition at line 312 of file text.py.
def normalize_newlines(text):
    """Normalize CRLF and CR newlines to just LF."""
    return re_newlines.sub("\n", str(text))
@keep_lazy_text
phone2numeric()
django.utils.text.phone2numeric (phone)
Convert a phone number with letters into its numeric equivalent.
Definition at line 318 of file text.py.
def phone2numeric(phone):
    """Convert a phone number with letters into its numeric equivalent."""
    char2number = {
        "a": "2",
        "b": "2",
        "c": "2",
        "d": "3",
        "e": "3",
        "f": "3",
        "g": "4",
        "h": "4",
        "i": "4",
        "j": "5",
        "k": "5",
        "l": "5",
        "m": "6",
        "n": "6",
        "o": "6",
        "p": "7",
        "q": "7",
        "r": "7",
        "s": "7",
        "t": "8",
        "u": "8",
        "v": "8",
        "w": "9",
        "x": "9",
        "y": "9",
        "z": "9",
    }
    return "".join(char2number.get(c, c) for c in phone.lower())
slugify()
django.utils.text.slugify (value, allow_unicode = False)
Convert to ASCII if 'allow_unicode' is False. Convert spaces or repeated
dashes to single dashes. Remove characters that aren't alphanumerics,
underscores, or hyphens. Convert to lowercase. Also strip leading and
trailing whitespace, dashes, and underscores.
Definition at line 452 of file text.py.
def slugify(value, allow_unicode=False):
    """
    Convert to ASCII if 'allow_unicode' is False. Convert spaces or repeated
    dashes to single dashes. Remove characters that aren't alphanumerics,
    underscores, or hyphens. Convert to lowercase. Also strip leading and
    trailing whitespace, dashes, and underscores.
    """
    value = str(value)
    if allow_unicode:
        value = unicodedata.normalize("NFKC", value)
    else:
        value = (
            unicodedata.normalize("NFKD", value)
            .encode("ascii", "ignore")
            .decode("ascii")
        )
    value = re.sub(r"[^\w\s-]", "", value.lower())
    return re.sub(r"[-\s]+", "-", value).strip("-_")
smart_split()
django.utils.text.smart_split (text)
Generator that splits a string by spaces, leaving quoted phrases together.
Supports both single and double quotes, and supports escaping quotes with
backslashes. In the output, strings will keep their initial and trailing
quote marks and escaped quotes will remain escaped (the results can then
be further processed with unescape_string_literal()).
>>> list(smart_split(r'This is "a person\'s" test.'))
['This', 'is', '"a person\\\'s"', 'test.']
>>> list(smart_split(r"Another 'person\'s' test."))
['Another', "'person\\'s'", 'test.']
>>> list(smart_split(r'A "\"funky\" style" test.'))
['A', '"\\"funky\\" style"', 'test.']
Definition at line 411 of file text.py.
def smart_split(text):
    r"""
    Generator that splits a string by spaces, leaving quoted phrases together.
    Supports both single and double quotes, and supports escaping quotes with
    backslashes. In the output, strings will keep their initial and trailing
    quote marks and escaped quotes will remain escaped (the results can then
    be further processed with unescape_string_literal()).
    >>> list(smart_split(r'This is "a person\'s" test.'))
    ['This', 'is', '"a person\\\'s"', 'test.']
    >>> list(smart_split(r"Another 'person\'s' test."))
    ['Another', "'person\\'s'", 'test.']
    >>> list(smart_split(r'A "\"funky\" style" test.'))
    ['A', '"\\"funky\\" style"', 'test.']
    """
    for bit in smart_split_re.finditer(str(text)):
        yield bit[0]
@keep_lazy_text
unescape_string_literal()
django.utils.text.unescape_string_literal (s)
Convert quoted string literals to unquoted strings with escaped quotes and
backslashes unquoted::
>>> unescape_string_literal('"abc"')
'abc'
>>> unescape_string_literal("'abc'")
'abc'
>>> unescape_string_literal('"a \"bc\""')
'a "bc"'
>>> unescape_string_literal("'\'ab\' c'")
"'ab' c"
Definition at line 431 of file text.py.
def unescape_string_literal(s):
    r"""
    Convert quoted string literals to unquoted strings with escaped quotes and
    backslashes unquoted::
        >>> unescape_string_literal('"abc"')
        'abc'
        >>> unescape_string_literal("'abc'")
        'abc'
        >>> unescape_string_literal('"a \"bc\""')
        'a "bc"'
        >>> unescape_string_literal("'\'ab\' c'")
        "'ab' c"
    """
    if not s or s[0] not in "\"'" or s[-1] != s[0]:
        raise ValueError("Not a string literal: %r" % s)
    quote = s[0]
    return s[1:-1].replace(r"\%s" % quote, quote).replace(r"\\", "\\")
@keep_lazy_text
wrap()
django.utils.text.wrap (text, width)
A word-wrap function that preserves existing line breaks. Expects that
existing line breaks are posix newlines.
Preserve all white space except added line breaks consume the space on
which they break the line.
Don't wrap long words, thus the output text may have lines longer than
``width``.
Definition at line 40 of file text.py.
def wrap(text, width):
    """
    A word-wrap function that preserves existing line breaks. Expects that
    existing line breaks are posix newlines.
    Preserve all white space except added line breaks consume the space on
    which they break the line.
    Don't wrap long words, thus the output text may have lines longer than
    ``width``.
    """
    def _generator():
        for line in text.splitlines(True):  # True keeps trailing linebreaks
            max_width = min((line.endswith("\n") and width + 1 or width), width)
            while len(line) > max_width:
                space = line[: max_width + 1].rfind(" ") + 1
                if space == 0:
                    space = line.find(" ") + 1
                    if space == 0:
                        yield line
                        line = ""
                        break
                yield "%s\n" % line[: space - 1]
                line = line[space:]
                max_width = min((line.endswith("\n") and width + 1 or width), width)
            if line:
                yield line
    return "".join(_generator())
Variable Documentation
format_lazy
django.utils.text.format_lazy = lazy(_format_lazy, str)
Definition at line 487 of file text.py.
re_camel_case
django.utils.text.re_camel_case = _lazy_re_compile(r"(((?<=[a-z])[A-Z])|([A-Z](?![A-Z]|$)))")
Definition at line 36 of file text.py.
re_newlines
django.utils.text.re_newlines = _lazy_re_compile(r"\r\n|\r")
Definition at line 35 of file text.py.
smart_split_re
django.utils.text.smart_split_re
Initial value:
=  _lazy_re_compile(
    ,
    re.VERBOSE,
)
Definition at line 397 of file text.py.