Read&Watch: django.utils.duration Namespace Reference
django.utils.duration Namespace Reference
Functions
_get_duration_components (duration)
duration_string (duration)
duration_iso_string (duration)
duration_microseconds (delta)
Function Documentation
_get_duration_components()
django.utils.duration._get_duration_components (duration) protected
Definition at line 4 of file duration.py.
def _get_duration_components(duration):
    days = duration.days
    seconds = duration.seconds
    microseconds = duration.microseconds
    minutes = seconds // 60
    seconds %= 60
    hours = minutes // 60
    minutes %= 60
    return days, hours, minutes, seconds, microseconds
Referenced by duration_iso_string(), and duration_string().
duration_iso_string()
django.utils.duration.duration_iso_string (duration)
Definition at line 31 of file duration.py.
def duration_iso_string(duration):
    if duration < datetime.timedelta(0):
        sign = "-"
        duration *= -1
    else:
        sign = ""
    days, hours, minutes, seconds, microseconds = _get_duration_components(duration)
    ms = ".{:06d}".format(microseconds) if microseconds else ""
    return "{}P{}DT{:02d}H{:02d}M{:02d}{}S".format(
        sign, days, hours, minutes, seconds, ms
    )
References _get_duration_components().
duration_microseconds()
django.utils.duration.duration_microseconds (delta)
Definition at line 45 of file duration.py.
def duration_microseconds(delta):
    return (24 * 60 * 60 * delta.days + delta.seconds) * 1000000 + delta.microseconds
duration_string()
django.utils.duration.duration_string (duration)
Version of str(timedelta) which is not English specific.
Definition at line 18 of file duration.py.
def duration_string(duration):
    """Version of str(timedelta) which is not English specific."""
    days, hours, minutes, seconds, microseconds = _get_duration_components(duration)
    string = "{:02d}:{:02d}:{:02d}".format(hours, minutes, seconds)
    if days:
        string = "{} ".format(days) + string
    if microseconds:
        string += ".{:06d}".format(microseconds)
    return string
References _get_duration_components().