Read&Watch: django.db.models.sql.query Namespace Reference
django.db.models.sql.query Namespace Reference
Classes
class JoinPromoter
class Query
class RawQuery
Functions
get_field_names_from_opts (opts)
get_paths_from_expression (expr)
get_children_from_q (q)
get_child_with_renamed_prefix (prefix, replacement, child)
rename_prefix_from_q (prefix, replacement, q)
get_order_dir (field, default="ASC")
Variables
FORBIDDEN_ALIAS_PATTERN = _lazy_re_compile(r"['`\"\]\[;\s]|--|/\*|\*/")
EXPLAIN_OPTIONS_PATTERN = _lazy_re_compile(r"[\w-]+")
JoinInfo
ExplainInfo = namedtuple("ExplainInfo", ("format", "options"))
Detailed Description
Create SQL statements for QuerySets.
The code in here encapsulates all of the SQL construction so that QuerySets
themselves do not have to (and could be backed by things other than SQL
databases). The abstraction barrier only works one way: this module has to know
all about the internals of models in order to get the information it needs.
Function Documentation
get_child_with_renamed_prefix()
django.db.models.sql.query.get_child_with_renamed_prefix (prefix, replacement, child)
Definition at line 93 of file query.py.
def get_child_with_renamed_prefix(prefix, replacement, child):
    from django.db.models.query import QuerySet
    if isinstance(child, Node):
        return rename_prefix_from_q(prefix, replacement, child)
    if isinstance(child, tuple):
        lhs, rhs = child
        if lhs.startswith(prefix + LOOKUP_SEP):
            lhs = lhs.replace(prefix, replacement, 1)
        if not isinstance(rhs, F) and hasattr(rhs, "resolve_expression"):
            rhs = get_child_with_renamed_prefix(prefix, replacement, rhs)
        return lhs, rhs
    if isinstance(child, F):
        child = child.copy()
        if child.name.startswith(prefix + LOOKUP_SEP):
            child.name = child.name.replace(prefix, replacement, 1)
    elif isinstance(child, QuerySet):
        # QuerySet may contain OuterRef() references which cannot work properly
        # without repointing to the filtered annotation and will spawn a
        # different JOIN. Always raise ValueError instead of providing partial
        # support in other cases.
        raise ValueError(
            "Passing a QuerySet within a FilteredRelation is not supported."
        )
    elif hasattr(child, "resolve_expression"):
        child = child.copy()
        child.set_source_expressions(
            [
                get_child_with_renamed_prefix(prefix, replacement, grand_child)
                for grand_child in child.get_source_expressions()
            ]
        )
    return child
References get_child_with_renamed_prefix(), and rename_prefix_from_q().
Referenced by get_child_with_renamed_prefix(), and rename_prefix_from_q().
get_children_from_q()
django.db.models.sql.query.get_children_from_q (q)
Definition at line 80 of file query.py.
def get_children_from_q(q):
    for child in q.children:
        if isinstance(child, Node):
            yield from get_children_from_q(child)
        elif isinstance(child, tuple):
            lhs, rhs = child
            yield lhs
            if hasattr(rhs, "resolve_expression"):
                yield from get_paths_from_expression(rhs)
        elif hasattr(child, "resolve_expression"):
            yield from get_paths_from_expression(child)
References get_children_from_q(), and get_paths_from_expression().
Referenced by django.db.models.sql.query.Query.add_filtered_relation(), get_children_from_q(), and get_paths_from_expression().
get_field_names_from_opts()
django.db.models.sql.query.get_field_names_from_opts (opts)
Definition at line 59 of file query.py.
def get_field_names_from_opts(opts):
    if opts is None:
        return set()
    return set(
        chain.from_iterable(
            (f.name, f.attname) if f.concrete else (f.name,) for f in opts.get_fields()
        )
    )
Referenced by django.db.models.sql.query.Query.add_fields(), and django.db.models.sql.query.Query.names_to_path().
get_order_dir()
django.db.models.sql.query.get_order_dir (field, default = "ASC")
Return the field name and direction for an order specification. For
example, '-foo' is returned as ('foo', 'DESC').
The 'default' param is used to indicate which way no prefix (or a '+'
prefix) should sort. The '-' prefix always sorts the opposite way.
Definition at line 2632 of file query.py.
def get_order_dir(field, default="ASC"):
    """
    Return the field name and direction for an order specification. For
    example, '-foo' is returned as ('foo', 'DESC').
    The 'default' param is used to indicate which way no prefix (or a '+'
    prefix) should sort. The '-' prefix always sorts the opposite way.
    """
    dirn = ORDER_DIR[default]
    if field[0] == "-":
        return field[1:], dirn[1]
    return field, dirn[0]
Referenced by django.db.models.sql.compiler.SQLCompiler._order_by_pairs(), and django.db.models.sql.compiler.SQLCompiler.find_ordering_name().
get_paths_from_expression()
django.db.models.sql.query.get_paths_from_expression (expr)
Definition at line 69 of file query.py.
def get_paths_from_expression(expr):
    if isinstance(expr, F):
        yield expr.name
    elif hasattr(expr, "flatten"):
        for child in expr.flatten():
            if isinstance(child, F):
                yield child.name
            elif isinstance(child, Q):
                yield from get_children_from_q(child)
References get_children_from_q().
Referenced by get_children_from_q().
rename_prefix_from_q()
django.db.models.sql.query.rename_prefix_from_q (prefix, replacement, q)
Definition at line 129 of file query.py.
def rename_prefix_from_q(prefix, replacement, q):
    return Q.create(
        [get_child_with_renamed_prefix(prefix, replacement, c) for c in q.children],
        q.connector,
        q.negated,
    )
References get_child_with_renamed_prefix().
Referenced by django.db.models.sql.query.Query.add_filtered_relation(), and get_child_with_renamed_prefix().
Variable Documentation
EXPLAIN_OPTIONS_PATTERN
django.db.models.sql.query.EXPLAIN_OPTIONS_PATTERN = _lazy_re_compile(r"[\w-]+")
Definition at line 56 of file query.py.
ExplainInfo
django.db.models.sql.query.ExplainInfo = namedtuple("ExplainInfo", ("format", "options"))
Definition at line 216 of file query.py.
Referenced by django.db.models.sql.query.Query.explain().
FORBIDDEN_ALIAS_PATTERN
django.db.models.sql.query.FORBIDDEN_ALIAS_PATTERN = _lazy_re_compile(r"['`\"\]\[;\s]|--|/\*|\*/")
Definition at line 52 of file query.py.
JoinInfo
django.db.models.sql.query.JoinInfo
Initial value:
=  namedtuple(
    "JoinInfo",
    ("final_field", "targets", "opts", "joins", "path", "transform_function"),
)
Definition at line 137 of file query.py.
Referenced by django.db.models.sql.query.Query.setup_joins().