Read&Watch: pip._vendor.platformdirs Namespace Reference
pip._vendor.platformdirs Namespace Reference
Namespaces
namespace __main__
namespace android
namespace api
namespace macos
namespace unix
namespace version
namespace windows
Functions
type[PlatformDirsABC] _set_platform_dir_class ()
str user_data_dir (str|None appname=None, str|None|Literal[False] appauthor=None, str|None version=None, bool roaming=False, bool ensure_exists=False)
str site_data_dir (str|None appname=None, str|None|Literal[False] appauthor=None, str|None version=None, bool multipath=False, bool ensure_exists=False)
str user_config_dir (str|None appname=None, str|None|Literal[False] appauthor=None, str|None version=None, bool roaming=False, bool ensure_exists=False)
str site_config_dir (str|None appname=None, str|None|Literal[False] appauthor=None, str|None version=None, bool multipath=False, bool ensure_exists=False)
str user_cache_dir (str|None appname=None, str|None|Literal[False] appauthor=None, str|None version=None, bool opinion=True, bool ensure_exists=False)
str site_cache_dir (str|None appname=None, str|None|Literal[False] appauthor=None, str|None version=None, bool opinion=True, bool ensure_exists=False)
str user_state_dir (str|None appname=None, str|None|Literal[False] appauthor=None, str|None version=None, bool roaming=False, bool ensure_exists=False)
str user_log_dir (str|None appname=None, str|None|Literal[False] appauthor=None, str|None version=None, bool opinion=True, bool ensure_exists=False)
str user_documents_dir ()
str user_downloads_dir ()
str user_pictures_dir ()
str user_videos_dir ()
str user_music_dir ()
str user_desktop_dir ()
str user_runtime_dir (str|None appname=None, str|None|Literal[False] appauthor=None, str|None version=None, bool opinion=True, bool ensure_exists=False)
str site_runtime_dir (str|None appname=None, str|None|Literal[False] appauthor=None, str|None version=None, bool opinion=True, bool ensure_exists=False)
Path user_data_path (str|None appname=None, str|None|Literal[False] appauthor=None, str|None version=None, bool roaming=False, bool ensure_exists=False)
Path site_data_path (str|None appname=None, str|None|Literal[False] appauthor=None, str|None version=None, bool multipath=False, bool ensure_exists=False)
Path user_config_path (str|None appname=None, str|None|Literal[False] appauthor=None, str|None version=None, bool roaming=False, bool ensure_exists=False)
Path site_config_path (str|None appname=None, str|None|Literal[False] appauthor=None, str|None version=None, bool multipath=False, bool ensure_exists=False)
Path site_cache_path (str|None appname=None, str|None|Literal[False] appauthor=None, str|None version=None, bool opinion=True, bool ensure_exists=False)
Path user_cache_path (str|None appname=None, str|None|Literal[False] appauthor=None, str|None version=None, bool opinion=True, bool ensure_exists=False)
Path user_state_path (str|None appname=None, str|None|Literal[False] appauthor=None, str|None version=None, bool roaming=False, bool ensure_exists=False)
Path user_log_path (str|None appname=None, str|None|Literal[False] appauthor=None, str|None version=None, bool opinion=True, bool ensure_exists=False)
Path user_documents_path ()
Path user_downloads_path ()
Path user_pictures_path ()
Path user_videos_path ()
Path user_music_path ()
Path user_desktop_path ()
Path user_runtime_path (str|None appname=None, str|None|Literal[False] appauthor=None, str|None version=None, bool opinion=True, bool ensure_exists=False)
Path site_runtime_path (str|None appname=None, str|None|Literal[False] appauthor=None, str|None version=None, bool opinion=True, bool ensure_exists=False)
Variables
type[PlatformDirsABC] PlatformDirs = _set_platform_dir_class()
type[PlatformDirsABC] AppDirs = PlatformDirs
Detailed Description
Utilities for determining application-specific dirs.
See <https://github.com/platformdirs/platformdirs> for details and usage.
Function Documentation
_set_platform_dir_class()
type[PlatformDirsABC] pip._vendor.platformdirs._set_platform_dir_class () protected
Definition at line 23 of file __init__.py.
def _set_platform_dir_class() -> type[PlatformDirsABC]:
    if sys.platform == "win32":
        from pip._vendor.platformdirs.windows import Windows as Result  # noqa: PLC0415
    elif sys.platform == "darwin":
        from pip._vendor.platformdirs.macos import MacOS as Result  # noqa: PLC0415
    else:
        from pip._vendor.platformdirs.unix import Unix as Result  # noqa: PLC0415
    if os.getenv("ANDROID_DATA") == "/data" and os.getenv("ANDROID_ROOT") == "/system":
        if os.getenv("SHELL") or os.getenv("PREFIX"):
            return Result
        from pip._vendor.platformdirs.android import _android_folder  # noqa: PLC0415
        if _android_folder() is not None:
            from pip._vendor.platformdirs.android import Android  # noqa: PLC0415
            return Android  # return to avoid redefinition of a result
    return Result
site_cache_dir()
str pip._vendor.platformdirs.site_cache_dir (str | None appname = None, str | None | Literal[False] appauthor = None, str | None version = None, bool opinion = True, bool ensure_exists = False)
:param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
:param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
:param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
:param opinion: See `opinion <platformdirs.api.PlatformDirsABC.opinion>`.
:param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
:returns: cache directory tied to the user
Definition at line 169 of file __init__.py.
) -> str:
    """
    :param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
    :param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
    :param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
    :param opinion: See `opinion <platformdirs.api.PlatformDirsABC.opinion>`.
    :param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
    :returns: cache directory tied to the user
    """
    return PlatformDirs(
        appname=appname,
        appauthor=appauthor,
        version=version,
        opinion=opinion,
        ensure_exists=ensure_exists,
    ).site_cache_dir
References PlatformDirs.
site_cache_path()
Path pip._vendor.platformdirs.site_cache_path (str | None appname = None, str | None | Literal[False] appauthor = None, str | None version = None, bool opinion = True, bool ensure_exists = False)
:param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
:param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
:param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
:param opinion: See `opinion <platformdirs.api.PlatformDirsABC.opinion>`.
:param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
:returns: cache directory tied to the user
Definition at line 415 of file __init__.py.
) -> Path:
    """
    :param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
    :param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
    :param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
    :param opinion: See `opinion <platformdirs.api.PlatformDirsABC.opinion>`.
    :param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
    :returns: cache directory tied to the user
    """
    return PlatformDirs(
        appname=appname,
        appauthor=appauthor,
        version=version,
        opinion=opinion,
        ensure_exists=ensure_exists,
    ).site_cache_path
site_config_dir()
str pip._vendor.platformdirs.site_config_dir (str | None appname = None, str | None | Literal[False] appauthor = None, str | None version = None, bool multipath = False, bool ensure_exists = False)
:param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
:param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
:param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
:param multipath: See `roaming <platformdirs.api.PlatformDirsABC.multipath>`.
:param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
:returns: config directory shared by the users
Definition at line 121 of file __init__.py.
) -> str:
    """
    :param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
    :param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
    :param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
    :param multipath: See `roaming <platformdirs.api.PlatformDirsABC.multipath>`.
    :param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
    :returns: config directory shared by the users
    """
    return PlatformDirs(
        appname=appname,
        appauthor=appauthor,
        version=version,
        multipath=multipath,
        ensure_exists=ensure_exists,
    ).site_config_dir
References PlatformDirs.
site_config_path()
Path pip._vendor.platformdirs.site_config_path (str | None appname = None, str | None | Literal[False] appauthor = None, str | None version = None, bool multipath = False, bool ensure_exists = False)
:param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
:param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
:param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
:param multipath: See `roaming <platformdirs.api.PlatformDirsABC.multipath>`.
:param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
:returns: config path shared by the users
Definition at line 391 of file __init__.py.
) -> Path:
    """
    :param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
    :param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
    :param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
    :param multipath: See `roaming <platformdirs.api.PlatformDirsABC.multipath>`.
    :param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
    :returns: config path shared by the users
    """
    return PlatformDirs(
        appname=appname,
        appauthor=appauthor,
        version=version,
        multipath=multipath,
        ensure_exists=ensure_exists,
    ).site_config_path
site_data_dir()
str pip._vendor.platformdirs.site_data_dir (str | None appname = None, str | None | Literal[False] appauthor = None, str | None version = None, bool multipath = False, bool ensure_exists = False)
:param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
:param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
:param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
:param multipath: See `roaming <platformdirs.api.PlatformDirsABC.multipath>`.
:param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
:returns: data directory shared by users
Definition at line 73 of file __init__.py.
) -> str:
    """
    :param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
    :param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
    :param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
    :param multipath: See `roaming <platformdirs.api.PlatformDirsABC.multipath>`.
    :param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
    :returns: data directory shared by users
    """
    return PlatformDirs(
        appname=appname,
        appauthor=appauthor,
        version=version,
        multipath=multipath,
        ensure_exists=ensure_exists,
    ).site_data_dir
References PlatformDirs.
site_data_path()
Path pip._vendor.platformdirs.site_data_path (str | None appname = None, str | None | Literal[False] appauthor = None, str | None version = None, bool multipath = False, bool ensure_exists = False)
:param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
:param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
:param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
:param multipath: See `multipath <platformdirs.api.PlatformDirsABC.multipath>`.
:param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
:returns: data path shared by users
Definition at line 343 of file __init__.py.
) -> Path:
    """
    :param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
    :param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
    :param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
    :param multipath: See `multipath <platformdirs.api.PlatformDirsABC.multipath>`.
    :param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
    :returns: data path shared by users
    """
    return PlatformDirs(
        appname=appname,
        appauthor=appauthor,
        version=version,
        multipath=multipath,
        ensure_exists=ensure_exists,
    ).site_data_path
site_runtime_dir()
str pip._vendor.platformdirs.site_runtime_dir (str | None appname = None, str | None | Literal[False] appauthor = None, str | None version = None, bool opinion = True, bool ensure_exists = False)
:param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
:param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
:param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
:param opinion: See `opinion <platformdirs.api.PlatformDirsABC.opinion>`.
:param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
:returns: runtime directory shared by users
Definition at line 295 of file __init__.py.
) -> str:
    """
    :param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
    :param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
    :param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
    :param opinion: See `opinion <platformdirs.api.PlatformDirsABC.opinion>`.
    :param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
    :returns: runtime directory shared by users
    """
    return PlatformDirs(
        appname=appname,
        appauthor=appauthor,
        version=version,
        opinion=opinion,
        ensure_exists=ensure_exists,
    ).site_runtime_dir
site_runtime_path()
Path pip._vendor.platformdirs.site_runtime_path (str | None appname = None, str | None | Literal[False] appauthor = None, str | None version = None, bool opinion = True, bool ensure_exists = False)
:param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
:param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
:param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
:param opinion: See `opinion <platformdirs.api.PlatformDirsABC.opinion>`.
:param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
:returns: runtime path shared by users
Definition at line 565 of file __init__.py.
) -> Path:
    """
    :param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
    :param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
    :param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
    :param opinion: See `opinion <platformdirs.api.PlatformDirsABC.opinion>`.
    :param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
    :returns: runtime path shared by users
    """
    return PlatformDirs(
        appname=appname,
        appauthor=appauthor,
        version=version,
        opinion=opinion,
        ensure_exists=ensure_exists,
    ).site_runtime_path
user_cache_dir()
str pip._vendor.platformdirs.user_cache_dir (str | None appname = None, str | None | Literal[False] appauthor = None, str | None version = None, bool opinion = True, bool ensure_exists = False)
:param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
:param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
:param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
:param opinion: See `roaming <platformdirs.api.PlatformDirsABC.opinion>`.
:param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
:returns: cache directory tied to the user
Definition at line 145 of file __init__.py.
) -> str:
    """
    :param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
    :param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
    :param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
    :param opinion: See `roaming <platformdirs.api.PlatformDirsABC.opinion>`.
    :param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
    :returns: cache directory tied to the user
    """
    return PlatformDirs(
        appname=appname,
        appauthor=appauthor,
        version=version,
        opinion=opinion,
        ensure_exists=ensure_exists,
    ).user_cache_dir
References PlatformDirs.
user_cache_path()
Path pip._vendor.platformdirs.user_cache_path (str | None appname = None, str | None | Literal[False] appauthor = None, str | None version = None, bool opinion = True, bool ensure_exists = False)
:param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
:param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
:param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
:param opinion: See `roaming <platformdirs.api.PlatformDirsABC.opinion>`.
:param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
:returns: cache path tied to the user
Definition at line 439 of file __init__.py.
) -> Path:
    """
    :param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
    :param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
    :param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
    :param opinion: See `roaming <platformdirs.api.PlatformDirsABC.opinion>`.
    :param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
    :returns: cache path tied to the user
    """
    return PlatformDirs(
        appname=appname,
        appauthor=appauthor,
        version=version,
        opinion=opinion,
        ensure_exists=ensure_exists,
    ).user_cache_path
user_config_dir()
str pip._vendor.platformdirs.user_config_dir (str | None appname = None, str | None | Literal[False] appauthor = None, str | None version = None, bool roaming = False, bool ensure_exists = False)
:param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
:param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
:param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
:param roaming: See `roaming <platformdirs.api.PlatformDirsABC.roaming>`.
:param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
:returns: config directory tied to the user
Definition at line 97 of file __init__.py.
) -> str:
    """
    :param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
    :param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
    :param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
    :param roaming: See `roaming <platformdirs.api.PlatformDirsABC.roaming>`.
    :param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
    :returns: config directory tied to the user
    """
    return PlatformDirs(
        appname=appname,
        appauthor=appauthor,
        version=version,
        roaming=roaming,
        ensure_exists=ensure_exists,
    ).user_config_dir
References PlatformDirs.
user_config_path()
Path pip._vendor.platformdirs.user_config_path (str | None appname = None, str | None | Literal[False] appauthor = None, str | None version = None, bool roaming = False, bool ensure_exists = False)
:param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
:param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
:param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
:param roaming: See `roaming <platformdirs.api.PlatformDirsABC.roaming>`.
:param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
:returns: config path tied to the user
Definition at line 367 of file __init__.py.
) -> Path:
    """
    :param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
    :param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
    :param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
    :param roaming: See `roaming <platformdirs.api.PlatformDirsABC.roaming>`.
    :param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
    :returns: config path tied to the user
    """
    return PlatformDirs(
        appname=appname,
        appauthor=appauthor,
        version=version,
        roaming=roaming,
        ensure_exists=ensure_exists,
    ).user_config_path
user_data_dir()
str pip._vendor.platformdirs.user_data_dir (str | None appname = None, str | None | Literal[False] appauthor = None, str | None version = None, bool roaming = False, bool ensure_exists = False)
:param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
:param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
:param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
:param roaming: See `roaming <platformdirs.api.PlatformDirsABC.roaming>`.
:param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
:returns: data directory tied to the user
Definition at line 49 of file __init__.py.
) -> str:
    """
    :param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
    :param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
    :param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
    :param roaming: See `roaming <platformdirs.api.PlatformDirsABC.roaming>`.
    :param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
    :returns: data directory tied to the user
    """
    return PlatformDirs(
        appname=appname,
        appauthor=appauthor,
        version=version,
        roaming=roaming,
        ensure_exists=ensure_exists,
    ).user_data_dir
References PlatformDirs.
user_data_path()
Path pip._vendor.platformdirs.user_data_path (str | None appname = None, str | None | Literal[False] appauthor = None, str | None version = None, bool roaming = False, bool ensure_exists = False)
:param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
:param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
:param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
:param roaming: See `roaming <platformdirs.api.PlatformDirsABC.roaming>`.
:param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
:returns: data path tied to the user
Definition at line 319 of file __init__.py.
) -> Path:
    """
    :param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
    :param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
    :param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
    :param roaming: See `roaming <platformdirs.api.PlatformDirsABC.roaming>`.
    :param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
    :returns: data path tied to the user
    """
    return PlatformDirs(
        appname=appname,
        appauthor=appauthor,
        version=version,
        roaming=roaming,
        ensure_exists=ensure_exists,
    ).user_data_path
user_desktop_dir()
str pip._vendor.platformdirs.user_desktop_dir ()
:returns: desktop directory tied to the user
Definition at line 266 of file __init__.py.
def user_desktop_dir() -> str:
    """:returns: desktop directory tied to the user"""
    return PlatformDirs().user_desktop_dir
user_desktop_path()
Path pip._vendor.platformdirs.user_desktop_path ()
:returns: desktop path tied to the user
Definition at line 536 of file __init__.py.
def user_desktop_path() -> Path:
    """:returns: desktop path tied to the user"""
    return PlatformDirs().user_desktop_path
user_documents_dir()
str pip._vendor.platformdirs.user_documents_dir ()
:returns: documents directory tied to the user
Definition at line 241 of file __init__.py.
def user_documents_dir() -> str:
    """:returns: documents directory tied to the user"""
    return PlatformDirs().user_documents_dir
user_documents_path()
Path pip._vendor.platformdirs.user_documents_path ()
:returns: documents a path tied to the user
Definition at line 511 of file __init__.py.
def user_documents_path() -> Path:
    """:returns: documents a path tied to the user"""
    return PlatformDirs().user_documents_path
user_downloads_dir()
str pip._vendor.platformdirs.user_downloads_dir ()
:returns: downloads directory tied to the user
Definition at line 246 of file __init__.py.
def user_downloads_dir() -> str:
    """:returns: downloads directory tied to the user"""
    return PlatformDirs().user_downloads_dir
user_downloads_path()
Path pip._vendor.platformdirs.user_downloads_path ()
:returns: downloads path tied to the user
Definition at line 516 of file __init__.py.
def user_downloads_path() -> Path:
    """:returns: downloads path tied to the user"""
    return PlatformDirs().user_downloads_path
user_log_dir()
str pip._vendor.platformdirs.user_log_dir (str | None appname = None, str | None | Literal[False] appauthor = None, str | None version = None, bool opinion = True, bool ensure_exists = False)
:param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
:param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
:param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
:param opinion: See `roaming <platformdirs.api.PlatformDirsABC.opinion>`.
:param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
:returns: log directory tied to the user
Definition at line 217 of file __init__.py.
) -> str:
    """
    :param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
    :param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
    :param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
    :param opinion: See `roaming <platformdirs.api.PlatformDirsABC.opinion>`.
    :param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
    :returns: log directory tied to the user
    """
    return PlatformDirs(
        appname=appname,
        appauthor=appauthor,
        version=version,
        opinion=opinion,
        ensure_exists=ensure_exists,
    ).user_log_dir
References PlatformDirs.
user_log_path()
Path pip._vendor.platformdirs.user_log_path (str | None appname = None, str | None | Literal[False] appauthor = None, str | None version = None, bool opinion = True, bool ensure_exists = False)
:param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
:param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
:param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
:param opinion: See `roaming <platformdirs.api.PlatformDirsABC.opinion>`.
:param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
:returns: log path tied to the user
Definition at line 487 of file __init__.py.
) -> Path:
    """
    :param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
    :param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
    :param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
    :param opinion: See `roaming <platformdirs.api.PlatformDirsABC.opinion>`.
    :param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
    :returns: log path tied to the user
    """
    return PlatformDirs(
        appname=appname,
        appauthor=appauthor,
        version=version,
        opinion=opinion,
        ensure_exists=ensure_exists,
    ).user_log_path
user_music_dir()
str pip._vendor.platformdirs.user_music_dir ()
:returns: music directory tied to the user
Definition at line 261 of file __init__.py.
def user_music_dir() -> str:
    """:returns: music directory tied to the user"""
    return PlatformDirs().user_music_dir
user_music_path()
Path pip._vendor.platformdirs.user_music_path ()
:returns: music path tied to the user
Definition at line 531 of file __init__.py.
def user_music_path() -> Path:
    """:returns: music path tied to the user"""
    return PlatformDirs().user_music_path
user_pictures_dir()
str pip._vendor.platformdirs.user_pictures_dir ()
:returns: pictures directory tied to the user
Definition at line 251 of file __init__.py.
def user_pictures_dir() -> str:
    """:returns: pictures directory tied to the user"""
    return PlatformDirs().user_pictures_dir
user_pictures_path()
Path pip._vendor.platformdirs.user_pictures_path ()
:returns: pictures path tied to the user
Definition at line 521 of file __init__.py.
def user_pictures_path() -> Path:
    """:returns: pictures path tied to the user"""
    return PlatformDirs().user_pictures_path
user_runtime_dir()
str pip._vendor.platformdirs.user_runtime_dir (str | None appname = None, str | None | Literal[False] appauthor = None, str | None version = None, bool opinion = True, bool ensure_exists = False)
:param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
:param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
:param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
:param opinion: See `opinion <platformdirs.api.PlatformDirsABC.opinion>`.
:param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
:returns: runtime directory tied to the user
Definition at line 271 of file __init__.py.
) -> str:
    """
    :param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
    :param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
    :param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
    :param opinion: See `opinion <platformdirs.api.PlatformDirsABC.opinion>`.
    :param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
    :returns: runtime directory tied to the user
    """
    return PlatformDirs(
        appname=appname,
        appauthor=appauthor,
        version=version,
        opinion=opinion,
        ensure_exists=ensure_exists,
    ).user_runtime_dir
user_runtime_path()
Path pip._vendor.platformdirs.user_runtime_path (str | None appname = None, str | None | Literal[False] appauthor = None, str | None version = None, bool opinion = True, bool ensure_exists = False)
:param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
:param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
:param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
:param opinion: See `opinion <platformdirs.api.PlatformDirsABC.opinion>`.
:param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
:returns: runtime path tied to the user
Definition at line 541 of file __init__.py.
) -> Path:
    """
    :param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
    :param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
    :param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
    :param opinion: See `opinion <platformdirs.api.PlatformDirsABC.opinion>`.
    :param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
    :returns: runtime path tied to the user
    """
    return PlatformDirs(
        appname=appname,
        appauthor=appauthor,
        version=version,
        opinion=opinion,
        ensure_exists=ensure_exists,
    ).user_runtime_path
user_state_dir()
str pip._vendor.platformdirs.user_state_dir (str | None appname = None, str | None | Literal[False] appauthor = None, str | None version = None, bool roaming = False, bool ensure_exists = False)
:param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
:param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
:param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
:param roaming: See `roaming <platformdirs.api.PlatformDirsABC.roaming>`.
:param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
:returns: state directory tied to the user
Definition at line 193 of file __init__.py.
) -> str:
    """
    :param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
    :param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
    :param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
    :param roaming: See `roaming <platformdirs.api.PlatformDirsABC.roaming>`.
    :param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
    :returns: state directory tied to the user
    """
    return PlatformDirs(
        appname=appname,
        appauthor=appauthor,
        version=version,
        roaming=roaming,
        ensure_exists=ensure_exists,
    ).user_state_dir
References PlatformDirs.
user_state_path()
Path pip._vendor.platformdirs.user_state_path (str | None appname = None, str | None | Literal[False] appauthor = None, str | None version = None, bool roaming = False, bool ensure_exists = False)
:param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
:param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
:param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
:param roaming: See `roaming <platformdirs.api.PlatformDirsABC.roaming>`.
:param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
:returns: state path tied to the user
Definition at line 463 of file __init__.py.
) -> Path:
    """
    :param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
    :param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
    :param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
    :param roaming: See `roaming <platformdirs.api.PlatformDirsABC.roaming>`.
    :param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
    :returns: state path tied to the user
    """
    return PlatformDirs(
        appname=appname,
        appauthor=appauthor,
        version=version,
        roaming=roaming,
        ensure_exists=ensure_exists,
    ).user_state_path
user_videos_dir()
str pip._vendor.platformdirs.user_videos_dir ()
:returns: videos directory tied to the user
Definition at line 256 of file __init__.py.
def user_videos_dir() -> str:
    """:returns: videos directory tied to the user"""
    return PlatformDirs().user_videos_dir
user_videos_path()
Path pip._vendor.platformdirs.user_videos_path ()
:returns: videos path tied to the user
Definition at line 526 of file __init__.py.
def user_videos_path() -> Path:
    """:returns: videos path tied to the user"""
    return PlatformDirs().user_videos_path
Variable Documentation
AppDirs
type[PlatformDirsABC] pip._vendor.platformdirs.AppDirs = PlatformDirs
Definition at line 46 of file __init__.py.
PlatformDirs
type[PlatformDirsABC] pip._vendor.platformdirs.PlatformDirs = _set_platform_dir_class()
Definition at line 45 of file __init__.py.
Referenced by pip._vendor.platformdirs.__main__.main(), site_cache_dir(), site_config_dir(), site_data_dir(), user_cache_dir(), user_config_dir(), user_data_dir(), user_log_dir(), and user_state_dir().