Read&Watch: pylint.checkers.base.basic_error_checker Namespace Reference
pylint.checkers.base.basic_error_checker Namespace Reference
Classes
class BasicErrorChecker
Functions
nodes.For|nodes.While|None _get_break_loop_node (nodes.Break break_node)
bool _loop_exits_early (nodes.For|nodes.While loop)
bool _has_abstract_methods (nodes.ClassDef node)
bool redefined_by_decorator (nodes.FunctionDef node)
Variables
dict ABC_METACLASSES = {"_py_abc.ABCMeta", "abc.ABCMeta"}
REDEFINABLE_METHODS = frozenset(("__module__",))
str TYPING_FORWARD_REF_QNAME = "typing.ForwardRef"
Detailed Description
Basic Error checker from the basic checker.
Function Documentation
_get_break_loop_node()
nodes.For | nodes.While | None pylint.checkers.base.basic_error_checker._get_break_loop_node (nodes.Break break_node) protected
Returns the loop node that holds the break node in arguments.
Args:
    break_node (astroid.Break): the break node of interest.
Returns:
    astroid.For or astroid.While: the loop node holding the break node.
Definition at line 26 of file basic_error_checker.py.
def _get_break_loop_node(break_node: nodes.Break) -> nodes.For | nodes.While | None:
    """Returns the loop node that holds the break node in arguments.
    Args:
        break_node (astroid.Break): the break node of interest.
    Returns:
        astroid.For or astroid.While: the loop node holding the break node.
    """
    loop_nodes = (nodes.For, nodes.While)
    parent = break_node.parent
    while not isinstance(parent, loop_nodes) or break_node in getattr(
        parent, "orelse", []
    ):
        break_node = parent
        parent = parent.parent
        if parent is None:
            break
    return parent
Referenced by _loop_exits_early().
_has_abstract_methods()
bool pylint.checkers.base.basic_error_checker._has_abstract_methods (nodes.ClassDef node) protected
Determine if the given `node` has abstract methods.
The methods should be made abstract by decorating them
with `abc` decorators.
Definition at line 70 of file basic_error_checker.py.
def _has_abstract_methods(node: nodes.ClassDef) -> bool:
    """Determine if the given `node` has abstract methods.
    The methods should be made abstract by decorating them
    with `abc` decorators.
    """
    return len(utils.unimplemented_abstract_methods(node)) > 0
Referenced by pylint.checkers.base.basic_error_checker.BasicErrorChecker._check_inferred_class_is_abstract().
_loop_exits_early()
bool pylint.checkers.base.basic_error_checker._loop_exits_early (nodes.For | nodes.While loop) protected
Returns true if a loop may end with a break statement.
Args:
    loop (astroid.For, astroid.While): the loop node inspected.
Returns:
    bool: True if the loop may end with a break statement, False otherwise.
Definition at line 47 of file basic_error_checker.py.
def _loop_exits_early(loop: nodes.For | nodes.While) -> bool:
    """Returns true if a loop may end with a break statement.
    Args:
        loop (astroid.For, astroid.While): the loop node inspected.
    Returns:
        bool: True if the loop may end with a break statement, False otherwise.
    """
    loop_nodes = (nodes.For, nodes.While)
    definition_nodes = (nodes.FunctionDef, nodes.ClassDef)
    inner_loop_nodes: list[nodes.For | nodes.While] = [
        _node
        for _node in loop.nodes_of_class(loop_nodes, skip_klass=definition_nodes)
        if _node != loop
    ]
    return any(
        _node
        for _node in loop.nodes_of_class(nodes.Break, skip_klass=definition_nodes)
        if _get_break_loop_node(_node) not in inner_loop_nodes
    )
References _get_break_loop_node().
Referenced by pylint.checkers.base.basic_error_checker.BasicErrorChecker._check_else_on_loop().
redefined_by_decorator()
bool pylint.checkers.base.basic_error_checker.redefined_by_decorator (nodes.FunctionDef node)
Return True if the object is a method redefined via decorator.
For example:
    @property
    def x(self): return self._x
    @x.setter
    def x(self, value): self._x = value
Definition at line 79 of file basic_error_checker.py.
def redefined_by_decorator(node: nodes.FunctionDef) -> bool:
    """Return True if the object is a method redefined via decorator.
    For example:
        @property
        def x(self): return self._x
        @x.setter
        def x(self, value): self._x = value
    """
    if node.decorators:
        for decorator in node.decorators.nodes:
            if (
                isinstance(decorator, nodes.Attribute)
                and getattr(decorator.expr, "name", None) == node.name
            ):
                return True
    return False
Referenced by pylint.checkers.base.basic_error_checker.BasicErrorChecker.visit_functiondef().
Variable Documentation
ABC_METACLASSES
dict pylint.checkers.base.basic_error_checker.ABC_METACLASSES = {"_py_abc.ABCMeta", "abc.ABCMeta"}
Definition at line 20 of file basic_error_checker.py.
REDEFINABLE_METHODS
pylint.checkers.base.basic_error_checker.REDEFINABLE_METHODS = frozenset(("__module__",))
Definition at line 22 of file basic_error_checker.py.
TYPING_FORWARD_REF_QNAME
str pylint.checkers.base.basic_error_checker.TYPING_FORWARD_REF_QNAME = "typing.ForwardRef"
Definition at line 23 of file basic_error_checker.py.