Read&Watch: django.utils.feedgenerator Namespace Reference
django.utils.feedgenerator Namespace Reference
Classes
class Atom1Feed
class Enclosure
class Rss201rev2Feed
class RssFeed
class RssUserland091Feed
class SyndicationFeed
Functions
rfc2822_date (date)
rfc3339_date (date)
get_tag_uri (url, date)
Variables
DefaultFeed = Rss201rev2Feed
Detailed Description
Syndication feed generation library -- used for generating RSS, etc.
Sample usage:
>>> from django.utils import feedgenerator
>>> feed = feedgenerator.Rss201rev2Feed(
...     title="Poynter E-Media Tidbits",
...     link="http://www.poynter.org/column.asp?id=31",
...     description="A group blog by the sharpest minds in online journalism.",
...     language="en",
...)
>>> feed.add_item(
...     title="Hello",
...     link="http://www.holovaty.com/test/",
...     description="Testing."
...)
>>> with open('test.rss', 'w') as fp:
...     feed.write(fp, 'utf-8')
For definitions of the different versions of RSS, see:
https://web.archive.org/web/20110718035220/http://diveintomark.org/archives/2004/02/04/incompatible-rss
Function Documentation
get_tag_uri()
django.utils.feedgenerator.get_tag_uri (url, date)
Create a TagURI.
See
https://web.archive.org/web/20110514113830/http://diveintomark.org/archives/2004/05/28/howto-atom-id
Definition at line 46 of file feedgenerator.py.
def get_tag_uri(url, date):
    """
    Create a TagURI.
    See
    https://web.archive.org/web/20110514113830/http://diveintomark.org/archives/2004/05/28/howto-atom-id
    """
    bits = urlparse(url)
    d = ""
    if date is not None:
        d = ",%s" % date.strftime("%Y-%m-%d")
    return "tag:%s%s:%s/%s" % (bits.hostname, d, bits.path, bits.fragment)
Referenced by django.utils.feedgenerator.Atom1Feed.add_item_elements().
rfc2822_date()
django.utils.feedgenerator.rfc2822_date (date)
Definition at line 34 of file feedgenerator.py.
def rfc2822_date(date):
    if not isinstance(date, datetime.datetime):
        date = datetime.datetime.combine(date, datetime.time())
    return email.utils.format_datetime(date)
Referenced by django.utils.feedgenerator.Rss201rev2Feed.add_item_elements(), and django.utils.feedgenerator.RssFeed.add_root_elements().
rfc3339_date()
django.utils.feedgenerator.rfc3339_date (date)
Definition at line 40 of file feedgenerator.py.
def rfc3339_date(date):
    if not isinstance(date, datetime.datetime):
        date = datetime.datetime.combine(date, datetime.time())
    return date.isoformat() + ("Z" if date.utcoffset() is None else "")
Referenced by django.utils.feedgenerator.Atom1Feed.add_item_elements(), and django.utils.feedgenerator.Atom1Feed.add_root_elements().
Variable Documentation
DefaultFeed
django.utils.feedgenerator.DefaultFeed = Rss201rev2Feed
Definition at line 448 of file feedgenerator.py.