Read&Watch: astroid.interpreter.objectmodel Namespace Reference
astroid.interpreter.objectmodel Namespace Reference
Classes
class AsyncGeneratorModel
class BoundMethodModel
class ClassModel
class ContextManagerModel
class DictModel
class ExceptionInstanceModel
class FunctionModel
class GeneratorModel
class ImportErrorInstanceModel
class InstanceModel
class ModuleModel
class ObjectModel
class OSErrorInstanceModel
class PropertyModel
class SuperModel
class SyntaxErrorInstanceModel
class UnboundMethodModel
class UnicodeDecodeErrorInstanceModel
Functions
_dunder_dict (instance, attributes)
Any _get_bound_node (ObjectModel model)
Variables
str IMPL_PREFIX = "attr_"
LEN_OF_IMPL_PREFIX = len(IMPL_PREFIX)
dict BUILTIN_EXCEPTIONS
Detailed Description
Data object model, as per https://docs.python.org/3/reference/datamodel.html.
This module describes, at least partially, a data object model for some
of astroid's nodes. The model contains special attributes that nodes such
as functions, classes, modules etc have, such as __doc__, __class__,
__module__ etc, being used when doing attribute lookups over nodes.
For instance, inferring `obj.__class__` will first trigger an inference
of the `obj` variable. If it was successfully inferred, then an attribute
`__class__ will be looked for in the inferred object. This is the part
where the data model occurs. The model is attached to those nodes
and the lookup mechanism will try to see if attributes such as
`__class__` are defined by the model or not. If they are defined,
the model will be requested to return the corresponding value of that
attribute. Thus the model can be viewed as a special part of the lookup
mechanism.
Function Documentation
_dunder_dict()
astroid.interpreter.objectmodel._dunder_dict (instance, attributes) protected
Definition at line 49 of file objectmodel.py.
def _dunder_dict(instance, attributes):
    obj = node_classes.Dict(
        parent=instance,
        lineno=instance.lineno,
        col_offset=instance.col_offset,
        end_lineno=instance.end_lineno,
        end_col_offset=instance.end_col_offset,
    )
    # Convert the keys to node strings
    keys = [
        node_classes.Const(value=value, parent=obj) for value in list(attributes.keys())
    ]
    # The original attribute has a list of elements for each key,
    # but that is not useful for retrieving the special attribute's value.
    # In this case, we're picking the last value from each list.
    values = [elem[-1] for elem in attributes.values()]
    obj.postinit(list(zip(keys, values)))
    return obj
_get_bound_node()
Any astroid.interpreter.objectmodel._get_bound_node (ObjectModel model) protected
Definition at line 72 of file objectmodel.py.
def _get_bound_node(model: ObjectModel) -> Any:
    # TODO: Use isinstance instead of try ... except after _instance has typing
    try:
        return model._instance._proxied
    except AttributeError:
        return model._instance
Referenced by astroid.interpreter.objectmodel.ContextManagerModel.attr___enter__(), astroid.interpreter.objectmodel.ContextManagerModel.attr___exit__(), astroid.interpreter.objectmodel.ObjectModel.attr___init__(), and astroid.interpreter.objectmodel.ObjectModel.attr___new__().
Variable Documentation
BUILTIN_EXCEPTIONS
dict astroid.interpreter.objectmodel.BUILTIN_EXCEPTIONS
Initial value:
=  {
    "builtins.SyntaxError": SyntaxErrorInstanceModel,
    "builtins.ImportError": ImportErrorInstanceModel,
    "builtins.UnicodeDecodeError": UnicodeDecodeErrorInstanceModel,
    # These are all similar to OSError in terms of attributes
    "builtins.OSError": OSErrorInstanceModel,
    "builtins.BlockingIOError": OSErrorInstanceModel,
    "builtins.BrokenPipeError": OSErrorInstanceModel,
    "builtins.ChildProcessError": OSErrorInstanceModel,
    "builtins.ConnectionAbortedError": OSErrorInstanceModel,
    "builtins.ConnectionError": OSErrorInstanceModel,
    "builtins.ConnectionRefusedError": OSErrorInstanceModel,
    "builtins.ConnectionResetError": OSErrorInstanceModel,
    "builtins.FileExistsError": OSErrorInstanceModel,
    "builtins.FileNotFoundError": OSErrorInstanceModel,
    "builtins.InterruptedError": OSErrorInstanceModel,
    "builtins.IsADirectoryError": OSErrorInstanceModel,
    "builtins.NotADirectoryError": OSErrorInstanceModel,
    "builtins.PermissionError": OSErrorInstanceModel,
    "builtins.ProcessLookupError": OSErrorInstanceModel,
    "builtins.TimeoutError": OSErrorInstanceModel,
}
Definition at line 828 of file objectmodel.py.
IMPL_PREFIX
str astroid.interpreter.objectmodel.IMPL_PREFIX = "attr_"
Definition at line 45 of file objectmodel.py.
LEN_OF_IMPL_PREFIX
astroid.interpreter.objectmodel.LEN_OF_IMPL_PREFIX = len(IMPL_PREFIX)
Definition at line 46 of file objectmodel.py.