Read&Watch: pip._vendor.urllib3.connection Namespace Reference
pip._vendor.urllib3.connection Namespace Reference
Classes
class BaseSSLError
class BrokenPipeError
class ConnectionError
class DummyConnection
class HTTPConnection
class HTTPSConnection
Functions
_match_hostname (cert, asserted_hostname)
_get_default_user_agent ()
Variables
BaseSSLError = ssl.SSLError
ssl = None
ConnectionError = ConnectionError
BrokenPipeError = BrokenPipeError
log = logging.getLogger(__name__)
dict port_by_scheme = {"http": 80, "https": 443}
RECENT_DATE = datetime.date(2024, 1, 1)
_CONTAINS_CONTROL_CHAR_RE = re.compile(r"[^-!#$%&'*+.^_`|~0-9a-zA-Z]")
HTTPSConnection = DummyConnection
VerifiedHTTPSConnection = HTTPSConnection
Function Documentation
_get_default_user_agent()
pip._vendor.urllib3.connection._get_default_user_agent () protected
Definition at line 558 of file connection.py.
def _get_default_user_agent():
    return "python-urllib3/%s" % __version__
Referenced by pip._vendor.urllib3.connection.HTTPConnection.request(), and pip._vendor.urllib3.connection.HTTPConnection.request_chunked().
_match_hostname()
pip._vendor.urllib3.connection._match_hostname (cert, asserted_hostname) protected
Definition at line 536 of file connection.py.
def _match_hostname(cert, asserted_hostname):
    # Our upstream implementation of ssl.match_hostname()
    # only applies this normalization to IP addresses so it doesn't
    # match DNS SANs so we do the same thing!
    stripped_hostname = asserted_hostname.strip("u[]")
    if is_ipaddress(stripped_hostname):
        asserted_hostname = stripped_hostname
    try:
        match_hostname(cert, asserted_hostname)
    except CertificateError as e:
        log.warning(
            "Certificate did not match expected hostname: %s. Certificate: %s",
            asserted_hostname,
            cert,
        )
        # Add cert to exception and reraise so client code can inspect
        # the cert when catching the exception, if they want to
        e._peer_cert = cert
        raise
Referenced by pip._vendor.urllib3.connection.HTTPSConnection._connect_tls_proxy().
Variable Documentation
_CONTAINS_CONTROL_CHAR_RE
pip._vendor.urllib3.connection._CONTAINS_CONTROL_CHAR_RE = re.compile(r"[^-!#$%&'*+.^_`|~0-9a-zA-Z]") protected
Definition at line 73 of file connection.py.
BaseSSLError
pip._vendor.urllib3.connection.BaseSSLError = ssl.SSLError
Definition at line 20 of file connection.py.
BrokenPipeError
pip._vendor.urllib3.connection.BrokenPipeError = BrokenPipeError
Definition at line 39 of file connection.py.
ConnectionError
pip._vendor.urllib3.connection.ConnectionError = ConnectionError
Definition at line 30 of file connection.py.
HTTPSConnection
pip._vendor.urllib3.connection.HTTPSConnection = DummyConnection
Definition at line 569 of file connection.py.
log
pip._vendor.urllib3.connection.log = logging.getLogger(__name__)
Definition at line 65 of file connection.py.
port_by_scheme
dict pip._vendor.urllib3.connection.port_by_scheme = {"http": 80, "https": 443}
Definition at line 67 of file connection.py.
RECENT_DATE
pip._vendor.urllib3.connection.RECENT_DATE = datetime.date(2024, 1, 1)
Definition at line 71 of file connection.py.
ssl
pip._vendor.urllib3.connection.ssl = None
Definition at line 22 of file connection.py.
VerifiedHTTPSConnection
pip._vendor.urllib3.connection.VerifiedHTTPSConnection = HTTPSConnection
Definition at line 572 of file connection.py.