Read&Watch: PIL.PsdImagePlugin Namespace Reference
PIL.PsdImagePlugin Namespace Reference
Classes
class PsdImageFile
Image plugin for Photoshop images.
Functions
bool _accept (bytes prefix)
list[tuple[str, str, tuple[int, int, int, int], list[ImageFile._Tile]]] _layerinfo (IO[bytes] fp, int ct_bytes)
list[ImageFile._Tile] _maketile (IO[bytes] file, str mode, tuple[int, int, int, int] bbox, int channels)
Variables
dict MODES
Function Documentation
_accept()
bool PIL.PsdImagePlugin._accept (bytes prefix) protected
Definition at line 49 of file PsdImagePlugin.py.
def _accept(prefix: bytes) -> bool:
    return prefix[:4] == b"8BPS"
Referenced by PIL.PsdImagePlugin.PsdImageFile._open().
_layerinfo()
list[tuple[str, str, tuple[int, int, int, int], list[ImageFile._Tile]]] PIL.PsdImagePlugin._layerinfo (IO[bytes] fp, int ct_bytes) protected
Definition at line 187 of file PsdImagePlugin.py.
) -> list[tuple[str, str, tuple[int, int, int, int], list[ImageFile._Tile]]]:
    # read layerinfo block
    layers = []
    def read(size: int) -> bytes:
        return ImageFile._safe_read(fp, size)
    ct = si16(read(2))
    # sanity check
    if ct_bytes < (abs(ct) * 20):
        msg = "Layer block too short for number of layers requested"
        raise SyntaxError(msg)
    for _ in range(abs(ct)):
        # bounding box
        y0 = si32(read(4))
        x0 = si32(read(4))
        y1 = si32(read(4))
        x1 = si32(read(4))
        # image info
        bands = []
        ct_types = i16(read(2))
        if ct_types > 4:
            fp.seek(ct_types * 6 + 12, io.SEEK_CUR)
            size = i32(read(4))
            fp.seek(size, io.SEEK_CUR)
            continue
        for _ in range(ct_types):
            type = i16(read(2))
            if type == 65535:
                b = "A"
            else:
                b = "RGBA"[type]
            bands.append(b)
            read(4)  # size
        # figure out the image mode
        bands.sort()
        if bands == ["R"]:
            mode = "L"
        elif bands == ["B", "G", "R"]:
            mode = "RGB"
        elif bands == ["A", "B", "G", "R"]:
            mode = "RGBA"
        else:
            mode = ""  # unknown
        # skip over blend flags and extra information
        read(12)  # filler
        name = ""
        size = i32(read(4))  # length of the extra data field
        if size:
            data_end = fp.tell() + size
            length = i32(read(4))
            if length:
                fp.seek(length - 16, io.SEEK_CUR)
            length = i32(read(4))
            if length:
                fp.seek(length, io.SEEK_CUR)
            length = i8(read(1))
            if length:
                # Don't know the proper encoding,
                # Latin-1 should be a good guess
                name = read(length).decode("latin-1", "replace")
            fp.seek(data_end)
        layers.append((name, mode, (x0, y0, x1, y1)))
    # get tiles
    layerinfo = []
    for i, (name, mode, bbox) in enumerate(layers):
        tile = []
        for m in mode:
            t = _maketile(fp, m, bbox, 1)
            if t:
                tile.extend(t)
        layerinfo.append((name, mode, bbox, tile))
    return layerinfo
References _maketile().
Referenced by PIL.PsdImagePlugin.PsdImageFile.layers().
_maketile()
list[ImageFile._Tile] PIL.PsdImagePlugin._maketile (IO[bytes] file, str mode, tuple[int, int, int, int] bbox, int channels) protected
Definition at line 278 of file PsdImagePlugin.py.
) -> list[ImageFile._Tile]:
    tiles = []
    read = file.read
    compression = i16(read(2))
    xsize = bbox[2] - bbox[0]
    ysize = bbox[3] - bbox[1]
    offset = file.tell()
    if compression == 0:
        #
        # raw compression
        for channel in range(channels):
            layer = mode[channel]
            if mode == "CMYK":
                layer += ";I"
            tiles.append(ImageFile._Tile("raw", bbox, offset, layer))
            offset = offset + xsize * ysize
    elif compression == 1:
        #
        # packbits compression
        i = 0
        bytecount = read(channels * ysize * 2)
        offset = file.tell()
        for channel in range(channels):
            layer = mode[channel]
            if mode == "CMYK":
                layer += ";I"
            tiles.append(ImageFile._Tile("packbits", bbox, offset, layer))
            for y in range(ysize):
                offset = offset + i16(bytecount, i)
                i += 2
    file.seek(offset)
    if offset & 1:
        read(1)  # padding
    return tiles
# --------------------------------------------------------------------
# registry
Referenced by _layerinfo().
Variable Documentation
MODES
dict PIL.PsdImagePlugin.MODES
Initial value:
=  {
    # (photoshop mode, bits) -> (pil mode, required channels)
    (0, 1): ("1", 1),
    (0, 8): ("L", 1),
    (1, 8): ("L", 1),
    (2, 8): ("P", 1),
    (3, 8): ("RGB", 3),
    (4, 8): ("CMYK", 4),
    (7, 8): ("L", 1),  # FIXME: multilayer
    (8, 8): ("L", 1),  # duotone
    (9, 8): ("LAB", 3),
}
Definition at line 31 of file PsdImagePlugin.py.