Read&Watch: pip._vendor.packaging.specifiers Namespace Reference
pip._vendor.packaging.specifiers Namespace Reference
Classes
class BaseSpecifier
class InvalidSpecifier
class Specifier
class SpecifierSet
Functions
Version _coerce_version (UnparsedVersion version)
list[str] _version_split (str version)
str _version_join (list[str] components)
bool _is_not_suffix (str segment)
tuple[list[str], list[str]] _pad_version (list[str] left, list[str] right)
Variables
UnparsedVersion = Union[Version, str]
UnparsedVersionVar = TypeVar("UnparsedVersionVar", bound=UnparsedVersion)
CallableOperator = Callable[[Version, str], bool]
_prefix_regex = re.compile(r"^([0-9]+)((?:a|b|c|rc)[0-9]+)$")
Detailed Description
.. testsetup::
    from pip._vendor.packaging.specifiers import Specifier, SpecifierSet, InvalidSpecifier
    from pip._vendor.packaging.version import Version
Function Documentation
_coerce_version()
Version pip._vendor.packaging.specifiers._coerce_version (UnparsedVersion version) protected
Definition at line 26 of file specifiers.py.
def _coerce_version(version: UnparsedVersion) -> Version:
    if not isinstance(version, Version):
        version = Version(version)
    return version
Referenced by pip._vendor.packaging.specifiers.Specifier.contains(), pip._vendor.packaging.specifiers.Specifier.filter(), and pip._vendor.packaging.specifiers.SpecifierSet.filter().
_is_not_suffix()
bool pip._vendor.packaging.specifiers._is_not_suffix (str segment) protected
Definition at line 663 of file specifiers.py.
def _is_not_suffix(segment: str) -> bool:
    return not any(
        segment.startswith(prefix) for prefix in ("dev", "a", "b", "rc", "post")
    )
_pad_version()
tuple[list[str], list[str]] pip._vendor.packaging.specifiers._pad_version (list[str] left, list[str] right) protected
Definition at line 669 of file specifiers.py.
def _pad_version(left: list[str], right: list[str]) -> tuple[list[str], list[str]]:
    left_split, right_split = [], []
    # Get the release segment of our versions
    left_split.append(list(itertools.takewhile(lambda x: x.isdigit(), left)))
    right_split.append(list(itertools.takewhile(lambda x: x.isdigit(), right)))
    # Get the rest of our versions
    left_split.append(left[len(left_split[0]) :])
    right_split.append(right[len(right_split[0]) :])
    # Insert our padding
    left_split.insert(1, ["0"] * max(0, len(right_split[0]) - len(left_split[0])))
    right_split.insert(1, ["0"] * max(0, len(left_split[0]) - len(right_split[0])))
    return (
        list(itertools.chain.from_iterable(left_split)),
        list(itertools.chain.from_iterable(right_split)),
    )
Referenced by pip._vendor.packaging.specifiers.Specifier._compare_equal().
_version_join()
str pip._vendor.packaging.specifiers._version_join (list[str] components) protected
Join split version components into a version string.
This function assumes the input came from :func:`_version_split`, where the
first component must be the epoch (either empty or numeric), and all other
components numeric.
Definition at line 652 of file specifiers.py.
def _version_join(components: list[str]) -> str:
    """Join split version components into a version string.
    This function assumes the input came from :func:`_version_split`, where the
    first component must be the epoch (either empty or numeric), and all other
    components numeric.
    """
    epoch, *rest = components
    return f"{epoch}!{'.'.join(rest)}"
Referenced by pip._vendor.packaging.specifiers.Specifier._compare_compatible().
_version_split()
list[str] pip._vendor.packaging.specifiers._version_split (str version) protected
Split version into components.
The split components are intended for version comparison. The logic does
not attempt to retain the original version string, so joining the
components back with :func:`_version_join` may not produce the original
version string.
Definition at line 630 of file specifiers.py.
def _version_split(version: str) -> list[str]:
    """Split version into components.
    The split components are intended for version comparison. The logic does
    not attempt to retain the original version string, so joining the
    components back with :func:`_version_join` may not produce the original
    version string.
    """
    result: list[str] = []
    epoch, _, rest = version.rpartition("!")
    result.append(epoch or "0")
    for item in rest.split("."):
        match = _prefix_regex.search(item)
        if match:
            result.extend(match.groups())
        else:
            result.append(item)
    return result
Referenced by pip._vendor.packaging.specifiers.Specifier._compare_compatible(), and pip._vendor.packaging.specifiers.Specifier._compare_equal().
Variable Documentation
_prefix_regex
pip._vendor.packaging.specifiers._prefix_regex = re.compile(r"^([0-9]+)((?:a|b|c|rc)[0-9]+)$") protected
Definition at line 627 of file specifiers.py.
CallableOperator
pip._vendor.packaging.specifiers.CallableOperator = Callable[[Version, str], bool]
Definition at line 23 of file specifiers.py.
UnparsedVersion
pip._vendor.packaging.specifiers.UnparsedVersion = Union[Version, str]
Definition at line 21 of file specifiers.py.
UnparsedVersionVar
pip._vendor.packaging.specifiers.UnparsedVersionVar = TypeVar("UnparsedVersionVar", bound=UnparsedVersion)
Definition at line 22 of file specifiers.py.