Read&Watch: django.contrib.gis.geos.prototypes.errcheck Namespace Reference
django.contrib.gis.geos.prototypes.errcheck Namespace Reference
Functions
last_arg_byref (args)
check_dbl (result, func, cargs)
check_geom (result, func, cargs)
check_minus_one (result, func, cargs)
check_predicate (result, func, cargs)
check_sized_string (result, func, cargs)
check_string (result, func, cargs)
Variables
free = GEOSFuncFactory("GEOSFree")
argtypes
Detailed Description
 Error checking functions for GEOS ctypes prototype functions.
Function Documentation
check_dbl()
django.contrib.gis.geos.prototypes.errcheck.check_dbl (result, func, cargs)
Definition at line 21 of file errcheck.py.
def check_dbl(result, func, cargs):
    "Check the status code and returns the double value passed in by reference."
    # Checking the status code
    if result != 1:
        return None
    # Double passed in by reference, return its value.
    return last_arg_byref(cargs)
References last_arg_byref().
check_geom()
django.contrib.gis.geos.prototypes.errcheck.check_geom (result, func, cargs)
Definition at line 30 of file errcheck.py.
def check_geom(result, func, cargs):
    "Error checking on routines that return Geometries."
    if not result:
        raise GEOSException(
            'Error encountered checking Geometry returned from GEOS C function "%s".'
            % func.__name__
        )
    return result
check_minus_one()
django.contrib.gis.geos.prototypes.errcheck.check_minus_one (result, func, cargs)
Definition at line 40 of file errcheck.py.
def check_minus_one(result, func, cargs):
    "Error checking on routines that should not return -1."
    if result == -1:
        raise GEOSException(
            'Error encountered in GEOS C function "%s".' % func.__name__
        )
    else:
        return result
check_predicate()
django.contrib.gis.geos.prototypes.errcheck.check_predicate (result, func, cargs)
Definition at line 50 of file errcheck.py.
def check_predicate(result, func, cargs):
    "Error checking for unary/binary predicate functions."
    if result == 1:
        return True
    elif result == 0:
        return False
    else:
        raise GEOSException(
            'Error encountered on GEOS C predicate function "%s".' % func.__name__
        )
check_sized_string()
django.contrib.gis.geos.prototypes.errcheck.check_sized_string (result, func, cargs)
Error checking for routines that return explicitly sized strings.
This frees the memory allocated by GEOS at the result pointer.
Definition at line 62 of file errcheck.py.
def check_sized_string(result, func, cargs):
    """
    Error checking for routines that return explicitly sized strings.
    This frees the memory allocated by GEOS at the result pointer.
    """
    if not result:
        raise GEOSException(
            'Invalid string pointer returned by GEOS C function "%s"' % func.__name__
        )
    # A c_size_t object is passed in by reference for the second
    # argument on these routines, and its needed to determine the
    # correct size.
    s = string_at(result, last_arg_byref(cargs))
    # Freeing the memory allocated within GEOS
    free(result)
    return s
References free, and last_arg_byref().
check_string()
django.contrib.gis.geos.prototypes.errcheck.check_string (result, func, cargs)
Error checking for routines that return strings.
This frees the memory allocated by GEOS at the result pointer.
Definition at line 81 of file errcheck.py.
def check_string(result, func, cargs):
    """
    Error checking for routines that return strings.
    This frees the memory allocated by GEOS at the result pointer.
    """
    if not result:
        raise GEOSException(
            'Error encountered checking string return value in GEOS C function "%s".'
            % func.__name__
        )
    # Getting the string value at the pointer address.
    s = string_at(result)
    # Freeing the memory allocated within GEOS
    free(result)
    return s
References free.
last_arg_byref()
django.contrib.gis.geos.prototypes.errcheck.last_arg_byref (args)
Definition at line 16 of file errcheck.py.
def last_arg_byref(args):
    "Return the last C argument's value by reference."
    return args[-1]._obj.value
Referenced by check_dbl(), and check_sized_string().
Variable Documentation
argtypes
django.contrib.gis.geos.prototypes.errcheck.argtypes
Definition at line 13 of file errcheck.py.
free
django.contrib.gis.geos.prototypes.errcheck.free = GEOSFuncFactory("GEOSFree")
Definition at line 12 of file errcheck.py.
Referenced by check_sized_string(), and check_string().