Read&Watch: pip._vendor.distlib.wheel Namespace Reference
pip._vendor.distlib.wheel Namespace Reference
Classes
class Mounter
class Wheel
Functions
_derive_abi ()
_get_suffixes ()
_load_dynamic (name, path)
_get_glibc_version ()
compatible_tags ()
is_compatible (wheel, tags=None)
Variables
logger = logging.getLogger(__name__)
cache = None
str IMP_PREFIX = 'pp'
VER_SUFFIX = sysconfig.get_config_var('py_version_nodot')
str PYVER = 'py' + VER_SUFFIX
str IMPVER = IMP_PREFIX + VER_SUFFIX
ARCH = get_platform().replace('-', '_').replace('.', '_')
ABI = sysconfig.get_config_var('SOABI')
FILENAME_RE
NAME_VERSION_RE = re.compile(, re.IGNORECASE | re.VERBOSE)
SHEBANG_RE = re.compile(br'\s*#![^\r\n]*')
SHEBANG_DETAIL_RE = re.compile(br'^(\s*#!("[^"]+"|\S+))\s+(.*)$')
str SHEBANG_PYTHON = b'#!python'
str SHEBANG_PYTHONW = b'#!pythonw'
o to_posix = lambda o
imp = None
_hook = Mounter()
COMPATIBLE_TAGS = compatible_tags()
major = major
tuple major_minor = (major, minor)
str string = ''.join((str(major), str(minor)))
Function Documentation
_derive_abi()
pip._vendor.distlib.wheel._derive_abi () protected
Definition at line 58 of file wheel.py.
    def _derive_abi():
        parts = ['cp', VER_SUFFIX]
        if sysconfig.get_config_var('Py_DEBUG'):
            parts.append('d')
        if IMP_PREFIX == 'cp':
            vi = sys.version_info[:2]
            if vi < (3, 8):
                wpm = sysconfig.get_config_var('WITH_PYMALLOC')
                if wpm is None:
                    wpm = True
                if wpm:
                    parts.append('m')
                if vi < (3, 3):
                    us = sysconfig.get_config_var('Py_UNICODE_SIZE')
                    if us == 4 or (us is None and sys.maxunicode == 0x10FFFF):
                        parts.append('u')
        return ''.join(parts)
References _derive_abi().
Referenced by _derive_abi().
_get_glibc_version()
pip._vendor.distlib.wheel._get_glibc_version () protected
Definition at line 975 of file wheel.py.
def _get_glibc_version():
    import platform
    ver = platform.libc_ver()
    result = []
    if ver[0] == 'glibc':
        for s in ver[1].split('.'):
            result.append(int(s) if s.isdigit() else 0)
        result = tuple(result)
    return result
_get_suffixes()
pip._vendor.distlib.wheel._get_suffixes () protected
Definition at line 114 of file wheel.py.
def _get_suffixes():
    if imp:
        return [s[0] for s in imp.get_suffixes()]
    else:
        return importlib.machinery.EXTENSION_SUFFIXES
_load_dynamic()
pip._vendor.distlib.wheel._load_dynamic (name, path) protected
Definition at line 121 of file wheel.py.
def _load_dynamic(name, path):
    # https://docs.python.org/3/library/importlib.html#importing-a-source-file-directly
    if imp:
        return imp.load_dynamic(name, path)
    else:
        spec = importlib.util.spec_from_file_location(name, path)
        module = importlib.util.module_from_spec(spec)
        sys.modules[name] = module
        spec.loader.exec_module(module)
        return module
Referenced by pip._vendor.distlib.wheel.Mounter.load_module().
compatible_tags()
pip._vendor.distlib.wheel.compatible_tags ()
Return (pyver, abi, arch) tuples compatible with this Python.
Definition at line 986 of file wheel.py.
def compatible_tags():
    """
    Return (pyver, abi, arch) tuples compatible with this Python.
    """
    class _Version:
        def __init__(self, major, minor):
            self.major = major
            self.major_minor = (major, minor)
            self.string = ''.join((str(major), str(minor)))
        def __str__(self):
            return self.string
    versions = [
        _Version(sys.version_info.major, minor_version)
        for minor_version in range(sys.version_info.minor, -1, -1)
    ]
    abis = []
    for suffix in _get_suffixes():
        if suffix.startswith('.abi'):
            abis.append(suffix.split('.', 2)[1])
    abis.sort()
    if ABI != 'none':
        abis.insert(0, ABI)
    abis.append('none')
    result = []
    arches = [ARCH]
    if sys.platform == 'darwin':
        m = re.match(r'(\w+)_(\d+)_(\d+)_(\w+)$', ARCH)
        if m:
            name, major, minor, arch = m.groups()
            minor = int(minor)
            matches = [arch]
            if arch in ('i386', 'ppc'):
                matches.append('fat')
            if arch in ('i386', 'ppc', 'x86_64'):
                matches.append('fat3')
            if arch in ('ppc64', 'x86_64'):
                matches.append('fat64')
            if arch in ('i386', 'x86_64'):
                matches.append('intel')
            if arch in ('i386', 'x86_64', 'intel', 'ppc', 'ppc64'):
                matches.append('universal')
            while minor >= 0:
                for match in matches:
                    s = '%s_%s_%s_%s' % (name, major, minor, match)
                    if s != ARCH:  # already there
                        arches.append(s)
                minor -= 1
    # Most specific - our Python version, ABI and arch
    for i, version_object in enumerate(versions):
        version = str(version_object)
        add_abis = []
        if i == 0:
            add_abis = abis
        if IMP_PREFIX == 'cp' and version_object.major_minor >= (3, 2):
            limited_api_abi = 'abi' + str(version_object.major)
            if limited_api_abi not in add_abis:
                add_abis.append(limited_api_abi)
        for abi in add_abis:
            for arch in arches:
                result.append((''.join((IMP_PREFIX, version)), abi, arch))
                # manylinux
                if abi != 'none' and sys.platform.startswith('linux'):
                    arch = arch.replace('linux_', '')
                    parts = _get_glibc_version()
                    if len(parts) == 2:
                        if parts >= (2, 5):
                            result.append((''.join((IMP_PREFIX, version)), abi, 'manylinux1_%s' % arch))
                        if parts >= (2, 12):
                            result.append((''.join((IMP_PREFIX, version)), abi, 'manylinux2010_%s' % arch))
                        if parts >= (2, 17):
                            result.append((''.join((IMP_PREFIX, version)), abi, 'manylinux2014_%s' % arch))
                        result.append((''.join(
                            (IMP_PREFIX, version)), abi, 'manylinux_%s_%s_%s' % (parts[0], parts[1], arch)))
    # where no ABI / arch dependency, but IMP_PREFIX dependency
    for i, version_object in enumerate(versions):
        version = str(version_object)
        result.append((''.join((IMP_PREFIX, version)), 'none', 'any'))
        if i == 0:
            result.append((''.join((IMP_PREFIX, version[0])), 'none', 'any'))
    # no IMP_PREFIX, ABI or arch dependency
    for i, version_object in enumerate(versions):
        version = str(version_object)
        result.append((''.join(('py', version)), 'none', 'any'))
        if i == 0:
            result.append((''.join(('py', version[0])), 'none', 'any'))
    return set(result)
is_compatible()
pip._vendor.distlib.wheel.is_compatible (wheel, tags = None)
Definition at line 1090 of file wheel.py.
def is_compatible(wheel, tags=None):
    if not isinstance(wheel, Wheel):
        wheel = Wheel(wheel)  # assume it's a filename
    result = False
    if tags is None:
        tags = COMPATIBLE_TAGS
    for ver, abi, arch in tags:
        if ver in wheel.pyver and abi in wheel.abi and arch in wheel.arch:
            result = True
            break
    return result
Variable Documentation
_hook
pip._vendor.distlib.wheel._hook = Mounter() protected
Definition at line 170 of file wheel.py.
ABI
pip._vendor.distlib.wheel.ABI = sysconfig.get_config_var('SOABI')
Definition at line 53 of file wheel.py.
ARCH
pip._vendor.distlib.wheel.ARCH = get_platform().replace('-', '_').replace('.', '_')
Definition at line 51 of file wheel.py.
cache
pip._vendor.distlib.wheel.cache = None
Definition at line 34 of file wheel.py.
COMPATIBLE_TAGS
pip._vendor.distlib.wheel.COMPATIBLE_TAGS = compatible_tags()
Definition at line 1085 of file wheel.py.
FILENAME_RE
pip._vendor.distlib.wheel.FILENAME_RE
Initial value:
=  re.compile(
    , re.IGNORECASE | re.VERBOSE)
Definition at line 79 of file wheel.py.
imp
pip._vendor.distlib.wheel.imp = None
Definition at line 109 of file wheel.py.
IMP_PREFIX
str pip._vendor.distlib.wheel.IMP_PREFIX = 'pp'
Definition at line 37 of file wheel.py.
IMPVER
str pip._vendor.distlib.wheel.IMPVER = IMP_PREFIX + VER_SUFFIX
Definition at line 49 of file wheel.py.
logger
pip._vendor.distlib.wheel.logger = logging.getLogger(__name__)
Definition at line 32 of file wheel.py.
major
pip._vendor.distlib.wheel.major = major
Definition at line 992 of file wheel.py.
major_minor
tuple pip._vendor.distlib.wheel.major_minor = (major, minor)
Definition at line 993 of file wheel.py.
NAME_VERSION_RE
pip._vendor.distlib.wheel.NAME_VERSION_RE = re.compile(, re.IGNORECASE | re.VERBOSE)
Definition at line 90 of file wheel.py.
PYVER
str pip._vendor.distlib.wheel.PYVER = 'py' + VER_SUFFIX
Definition at line 48 of file wheel.py.
SHEBANG_DETAIL_RE
pip._vendor.distlib.wheel.SHEBANG_DETAIL_RE = re.compile(br'^(\s*#!("[^"]+"|\S+))\s+(.*)$')
Definition at line 97 of file wheel.py.
SHEBANG_PYTHON
str pip._vendor.distlib.wheel.SHEBANG_PYTHON = b'#!python'
Definition at line 98 of file wheel.py.
SHEBANG_PYTHONW
str pip._vendor.distlib.wheel.SHEBANG_PYTHONW = b'#!pythonw'
Definition at line 99 of file wheel.py.
SHEBANG_RE
pip._vendor.distlib.wheel.SHEBANG_RE = re.compile(br'\s*#![^\r\n]*')
Definition at line 96 of file wheel.py.
string
str pip._vendor.distlib.wheel.string = ''.join((str(major), str(minor)))
Definition at line 994 of file wheel.py.
to_posix
o pip._vendor.distlib.wheel.to_posix = lambda o
Definition at line 102 of file wheel.py.
Referenced by pip._vendor.distlib.wheel.Wheel.build(), and pip._vendor.distlib.wheel.Wheel.write_records().
VER_SUFFIX
str pip._vendor.distlib.wheel.VER_SUFFIX = sysconfig.get_config_var('py_version_nodot')
Definition at line 45 of file wheel.py.