Read&Watch: pip._vendor.rich.jupyter Namespace Reference
pip._vendor.rich.jupyter Namespace Reference
Classes
class JupyterMixin
class JupyterRenderable
Functions
str _render_segments (Iterable[Segment] segments)
None display (Iterable[Segment] segments, str text)
None print (*Any args, **Any kwargs)
Variables
str JUPYTER_HTML_FORMAT
Function Documentation
_render_segments()
str pip._vendor.rich.jupyter._render_segments (Iterable[Segment] segments) protected
Definition at line 59 of file jupyter.py.
def _render_segments(segments: Iterable[Segment]) -> str:
    def escape(text: str) -> str:
        """Escape html."""
        return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    fragments: List[str] = []
    append_fragment = fragments.append
    theme = DEFAULT_TERMINAL_THEME
    for text, style, control in Segment.simplify(segments):
        if control:
            continue
        text = escape(text)
        if style:
            rule = style.get_html_style(theme)
            text = f'<span style="{rule}">{text}</span>' if rule else text
            if style.link:
                text = f'<a href="{style.link}" target="_blank">{text}</a>'
        append_fragment(text)
    code = "".join(fragments)
    html = JUPYTER_HTML_FORMAT.format(code=code)
    return html
Referenced by pip._vendor.rich.jupyter.JupyterMixin._repr_mimebundle_(), and display().
display()
None pip._vendor.rich.jupyter.display (Iterable[Segment] segments, str text)
Render segments to Jupyter.
Definition at line 84 of file jupyter.py.
def display(segments: Iterable[Segment], text: str) -> None:
    """Render segments to Jupyter."""
    html = _render_segments(segments)
    jupyter_renderable = JupyterRenderable(html, text)
    try:
        from IPython.display import display as ipython_display
        ipython_display(jupyter_renderable)
    except ModuleNotFoundError:
        # Handle the case where the Console has force_jupyter=True,
        # but IPython is not installed.
        pass
References _render_segments().
print()
None pip._vendor.rich.jupyter.print (*Any args, **Any kwargs)
Proxy for Console print.
Definition at line 98 of file jupyter.py.
def print(*args: Any, **kwargs: Any) -> None:
    """Proxy for Console print."""
    console = get_console()
    return console.print(*args, **kwargs)
References pip._vendor.rich.get_console().
Variable Documentation
JUPYTER_HTML_FORMAT
str pip._vendor.rich.jupyter.JUPYTER_HTML_FORMAT
Initial value:
=  """\
<pre style="white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace">{code}</pre>
"""
Definition at line 13 of file jupyter.py.