Read&Watch: django.views.debug Namespace Reference
django.views.debug Namespace Reference
Classes
class CallableSettingWrapper
class ExceptionCycleWarning
class ExceptionReporter
class SafeExceptionReporterFilter
Functions
builtin_template_path (name)
technical_500_response (request, exc_type, exc_value, tb, status_code=500)
get_default_exception_reporter_filter ()
get_exception_reporter_filter (request)
get_exception_reporter_class (request)
get_caller (request)
technical_404_response (request, exception)
default_urlconf (request)
Variables
DEBUG_ENGINE
Function Documentation
builtin_template_path()
django.views.debug.builtin_template_path (name)
Return a path to a builtin template.
Avoid calling this function at the module level or in a class-definition
because __file__ may not exist, e.g. in frozen environments.
Definition at line 33 of file debug.py.
def builtin_template_path(name):
    """
    Return a path to a builtin template.
    Avoid calling this function at the module level or in a class-definition
    because __file__ may not exist, e.g. in frozen environments.
    """
    return Path(__file__).parent / "templates" / name
Referenced by default_urlconf(), django.views.debug.ExceptionReporter.html_template_path(), technical_404_response(), and django.views.debug.ExceptionReporter.text_template_path().
default_urlconf()
django.views.debug.default_urlconf (request)
Create an empty URLconf 404 error response.
Definition at line 655 of file debug.py.
def default_urlconf(request):
    """Create an empty URLconf 404 error response."""
    with builtin_template_path("default_urlconf.html").open(encoding="utf-8") as fh:
        t = DEBUG_ENGINE.from_string(fh.read())
    c = Context(
        {
            "version": get_docs_version(),
        }
    )
    return HttpResponse(t.render(c))
References builtin_template_path().
Referenced by technical_404_response().
get_caller()
django.views.debug.get_caller (request)
Definition at line 98 of file debug.py.
def get_caller(request):
    resolver_match = request.resolver_match
    if resolver_match is None:
        try:
            resolver_match = resolve(request.path)
        except Http404:
            pass
    return "" if resolver_match is None else resolver_match._func_path
Referenced by django.views.debug.ExceptionReporter.get_traceback_data(), and technical_404_response().
get_default_exception_reporter_filter()
django.views.debug.get_default_exception_reporter_filter ()
Definition at line 79 of file debug.py.
def get_default_exception_reporter_filter():
    # Instantiate the default filter for the first time and cache it.
    return import_string(settings.DEFAULT_EXCEPTION_REPORTER_FILTER)()
Referenced by get_exception_reporter_filter(), and technical_404_response().
get_exception_reporter_class()
django.views.debug.get_exception_reporter_class (request)
Definition at line 89 of file debug.py.
def get_exception_reporter_class(request):
    default_exception_reporter_class = import_string(
        settings.DEFAULT_EXCEPTION_REPORTER
    )
    return getattr(
        request, "exception_reporter_class", default_exception_reporter_class
    )
Referenced by technical_500_response().
get_exception_reporter_filter()
django.views.debug.get_exception_reporter_filter (request)
Definition at line 84 of file debug.py.
def get_exception_reporter_filter(request):
    default_filter = get_default_exception_reporter_filter()
    return getattr(request, "exception_reporter_filter", default_filter)
References get_default_exception_reporter_filter().
technical_404_response()
django.views.debug.technical_404_response (request, exception)
Create a technical 404 error response. `exception` is the Http404.
Definition at line 608 of file debug.py.
def technical_404_response(request, exception):
    """Create a technical 404 error response. `exception` is the Http404."""
    try:
        error_url = exception.args[0]["path"]
    except (IndexError, TypeError, KeyError):
        error_url = request.path_info[1:]  # Trim leading slash
    try:
        tried = exception.args[0]["tried"]
    except (IndexError, TypeError, KeyError):
        resolved = True
        tried = request.resolver_match.tried if request.resolver_match else None
    else:
        resolved = False
        if not tried or (  # empty URLconf
            request.path == "/"
            and len(tried) == 1
            and len(tried[0]) == 1  # default URLconf
            and getattr(tried[0][0], "app_name", "")
            == getattr(tried[0][0], "namespace", "")
            == "admin"
        ):
            return default_urlconf(request)
    urlconf = getattr(request, "urlconf", settings.ROOT_URLCONF)
    if isinstance(urlconf, types.ModuleType):
        urlconf = urlconf.__name__
    with builtin_template_path("technical_404.html").open(encoding="utf-8") as fh:
        t = DEBUG_ENGINE.from_string(fh.read())
    reporter_filter = get_default_exception_reporter_filter()
    c = Context(
        {
            "urlconf": urlconf,
            "root_urlconf": settings.ROOT_URLCONF,
            "request_path": error_url,
            "urlpatterns": tried,
            "resolved": resolved,
            "reason": str(exception),
            "request": request,
            "settings": reporter_filter.get_safe_settings(),
            "raising_view_name": get_caller(request),
        }
    )
    return HttpResponseNotFound(t.render(c))
References builtin_template_path(), default_urlconf(), get_caller(), and get_default_exception_reporter_filter().
technical_500_response()
django.views.debug.technical_500_response (request, exc_type, exc_value, tb, status_code = 500)
Create a technical server error response. The last three arguments are
the values returned from sys.exc_info() and friends.
Definition at line 62 of file debug.py.
def technical_500_response(request, exc_type, exc_value, tb, status_code=500):
    """
    Create a technical server error response. The last three arguments are
    the values returned from sys.exc_info() and friends.
    """
    reporter = get_exception_reporter_class(request)(request, exc_type, exc_value, tb)
    if request.accepts("text/html"):
        html = reporter.get_traceback_html()
        return HttpResponse(html, status=status_code)
    else:
        text = reporter.get_traceback_text()
        return HttpResponse(
            text, status=status_code, content_type="text/plain; charset=utf-8"
        )
@functools.lru_cache
References get_exception_reporter_class().
Variable Documentation
DEBUG_ENGINE
django.views.debug.DEBUG_ENGINE
Initial value:
=  Engine(
    debug=True,
    libraries={"i18n": "django.templatetags.i18n"},
)
Definition at line 27 of file debug.py.