Read&Watch: django.core.checks.security.sessions Namespace Reference
django.core.checks.security.sessions Namespace Reference
Functions
add_session_cookie_message (message)
add_httponly_message (message)
check_session_cookie_secure (app_configs, **kwargs)
check_session_cookie_httponly (app_configs, **kwargs)
_session_middleware ()
_session_app ()
Variables
W010
W011
W012
W013
W014
W015
Function Documentation
_session_app()
django.core.checks.security.sessions._session_app () protected
Definition at line 98 of file sessions.py.
def _session_app():
    return "django.contrib.sessions" in settings.INSTALLED_APPS
Referenced by check_session_cookie_httponly(), and check_session_cookie_secure().
_session_middleware()
django.core.checks.security.sessions._session_middleware () protected
Definition at line 94 of file sessions.py.
def _session_middleware():
    return "django.contrib.sessions.middleware.SessionMiddleware" in settings.MIDDLEWARE
Referenced by check_session_cookie_httponly(), and check_session_cookie_secure().
add_httponly_message()
django.core.checks.security.sessions.add_httponly_message (message)
Definition at line 36 of file sessions.py.
def add_httponly_message(message):
    return message + (
        " Using an HttpOnly session cookie makes it more difficult for "
        "cross-site scripting attacks to hijack user sessions."
    )
add_session_cookie_message()
django.core.checks.security.sessions.add_session_cookie_message (message)
Definition at line 6 of file sessions.py.
def add_session_cookie_message(message):
    return message + (
        " Using a secure-only session cookie makes it more difficult for "
        "network traffic sniffers to hijack user sessions."
    )
check_session_cookie_httponly()
django.core.checks.security.sessions.check_session_cookie_httponly (app_configs, ** kwargs)
Definition at line 81 of file sessions.py.
def check_session_cookie_httponly(app_configs, **kwargs):
    if settings.SESSION_COOKIE_HTTPONLY is True:
        return []
    errors = []
    if _session_app():
        errors.append(W013)
    if _session_middleware():
        errors.append(W014)
    if len(errors) > 1:
        errors = [W015]
    return errors
References _session_app(), and _session_middleware().
check_session_cookie_secure()
django.core.checks.security.sessions.check_session_cookie_secure (app_configs, ** kwargs)
Definition at line 67 of file sessions.py.
def check_session_cookie_secure(app_configs, **kwargs):
    if settings.SESSION_COOKIE_SECURE is True:
        return []
    errors = []
    if _session_app():
        errors.append(W010)
    if _session_middleware():
        errors.append(W011)
    if len(errors) > 1:
        errors = [W012]
    return errors
@register(Tags.security, deploy=True)
References _session_app(), and _session_middleware().
Variable Documentation
W010
django.core.checks.security.sessions.W010
Initial value:
=  Warning(
    add_session_cookie_message(
        "You have 'django.contrib.sessions' in your INSTALLED_APPS, "
        "but you have not set SESSION_COOKIE_SECURE to True."
    ),
    id="security.W010",
)
Definition at line 13 of file sessions.py.
W011
django.core.checks.security.sessions.W011
Initial value:
=  Warning(
    add_session_cookie_message(
        "You have 'django.contrib.sessions.middleware.SessionMiddleware' "
        "in your MIDDLEWARE, but you have not set "
        "SESSION_COOKIE_SECURE to True."
    ),
    id="security.W011",
)
Definition at line 21 of file sessions.py.
W012
django.core.checks.security.sessions.W012
Initial value:
=  Warning(
    add_session_cookie_message("SESSION_COOKIE_SECURE is not set to True."),
    id="security.W012",
)
Definition at line 30 of file sessions.py.
W013
django.core.checks.security.sessions.W013
Initial value:
=  Warning(
    add_httponly_message(
        "You have 'django.contrib.sessions' in your INSTALLED_APPS, "
        "but you have not set SESSION_COOKIE_HTTPONLY to True.",
    ),
    id="security.W013",
)
Definition at line 43 of file sessions.py.
W014
django.core.checks.security.sessions.W014
Initial value:
=  Warning(
    add_httponly_message(
        "You have 'django.contrib.sessions.middleware.SessionMiddleware' "
        "in your MIDDLEWARE, but you have not set "
        "SESSION_COOKIE_HTTPONLY to True."
    ),
    id="security.W014",
)
Definition at line 51 of file sessions.py.
W015
django.core.checks.security.sessions.W015
Initial value:
=  Warning(
    add_httponly_message("SESSION_COOKIE_HTTPONLY is not set to True."),
    id="security.W015",
)
Definition at line 60 of file sessions.py.