Read&Watch: pip._internal.commands.debug Namespace Reference
pip._internal.commands.debug Namespace Reference
Classes
class DebugCommand
Functions
None show_value (str name, Any value)
None show_sys_implementation ()
Dict[str, str] create_vendor_txt_map ()
Optional[ModuleType] get_module_from_module_name (str module_name)
Optional[str] get_vendor_version_from_module (str module_name)
None show_actual_vendor_versions (Dict[str, str] vendor_txt_versions)
None show_vendor_versions ()
None show_tags (Values options)
str ca_bundle_info (Configuration config)
Variables
logger = logging.getLogger(__name__)
Function Documentation
ca_bundle_info()
str pip._internal.commands.debug.ca_bundle_info (Configuration config)
Definition at line 141 of file debug.py.
def ca_bundle_info(config: Configuration) -> str:
    levels = {key.split(".", 1)[0] for key, _ in config.items()}
    if not levels:
        return "Not specified"
    levels_that_override_global = ["install", "wheel", "download"]
    global_overriding_level = [
        level for level in levels if level in levels_that_override_global
    ]
    if not global_overriding_level:
        return "global"
    if "global" in levels:
        levels.remove("global")
    return ", ".join(levels)
Referenced by pip._internal.commands.debug.DebugCommand.run().
create_vendor_txt_map()
Dict[str, str] pip._internal.commands.debug.create_vendor_txt_map ()
Definition at line 37 of file debug.py.
def create_vendor_txt_map() -> Dict[str, str]:
    with open_text_resource("pip._vendor", "vendor.txt") as f:
        # Purge non version specifying lines.
        # Also, remove any space prefix or suffixes (including comments).
        lines = [
            line.strip().split(" ", 1)[0] for line in f.readlines() if "==" in line
        ]
    # Transform into "module" -> version dict.
    return dict(line.split("==", 1) for line in lines)
Referenced by show_vendor_versions().
get_module_from_module_name()
Optional[ModuleType] pip._internal.commands.debug.get_module_from_module_name (str module_name)
Definition at line 49 of file debug.py.
def get_module_from_module_name(module_name: str) -> Optional[ModuleType]:
    # Module name can be uppercase in vendor.txt for some reason...
    module_name = module_name.lower().replace("-", "_")
    # PATCH: setuptools is actually only pkg_resources.
    if module_name == "setuptools":
        module_name = "pkg_resources"
    try:
        __import__(f"pip._vendor.{module_name}", globals(), locals(), level=0)
        return getattr(pip._vendor, module_name)
    except ImportError:
        # We allow 'truststore' to fail to import due
        # to being unavailable on Python 3.9 and earlier.
        if module_name == "truststore" and sys.version_info < (3, 10):
            return None
        raise
Referenced by get_vendor_version_from_module().
get_vendor_version_from_module()
Optional[str] pip._internal.commands.debug.get_vendor_version_from_module (str module_name)
Definition at line 67 of file debug.py.
def get_vendor_version_from_module(module_name: str) -> Optional[str]:
    module = get_module_from_module_name(module_name)
    version = getattr(module, "__version__", None)
    if module and not version:
        # Try to find version in debundled module info.
        assert module.__file__ is not None
        env = get_environment([os.path.dirname(module.__file__)])
        dist = env.get_distribution(module_name)
        if dist:
            version = str(dist.version)
    return version
References get_module_from_module_name().
Referenced by show_actual_vendor_versions().
show_actual_vendor_versions()
None pip._internal.commands.debug.show_actual_vendor_versions (Dict[str, str] vendor_txt_versions)
Log the actual version and print extra info if there is
a conflict or if the actual version could not be imported.
Definition at line 82 of file debug.py.
def show_actual_vendor_versions(vendor_txt_versions: Dict[str, str]) -> None:
    """Log the actual version and print extra info if there is
    a conflict or if the actual version could not be imported.
    """
    for module_name, expected_version in vendor_txt_versions.items():
        extra_message = ""
        actual_version = get_vendor_version_from_module(module_name)
        if not actual_version:
            extra_message = (
                " (Unable to locate actual module version, using"
                " vendor.txt specified version)"
            )
            actual_version = expected_version
        elif parse_version(actual_version) != parse_version(expected_version):
            extra_message = (
                " (CONFLICT: vendor.txt suggests version should"
                f" be {expected_version})"
            )
        logger.info("%s==%s%s", module_name, actual_version, extra_message)
References get_vendor_version_from_module().
Referenced by show_vendor_versions().
show_sys_implementation()
None pip._internal.commands.debug.show_sys_implementation ()
Definition at line 30 of file debug.py.
def show_sys_implementation() -> None:
    logger.info("sys.implementation:")
    implementation_name = sys.implementation.name
    with indent_log():
        show_value("name", implementation_name)
References show_value().
Referenced by pip._internal.commands.debug.DebugCommand.run().
show_tags()
None pip._internal.commands.debug.show_tags (Values options)
Definition at line 111 of file debug.py.
def show_tags(options: Values) -> None:
    tag_limit = 10
    target_python = make_target_python(options)
    tags = target_python.get_sorted_tags()
    # Display the target options that were explicitly provided.
    formatted_target = target_python.format_given()
    suffix = ""
    if formatted_target:
        suffix = f" (target: {formatted_target})"
    msg = f"Compatible tags: {len(tags)}{suffix}"
    logger.info(msg)
    if options.verbose < 1 and len(tags) > tag_limit:
        tags_limited = True
        tags = tags[:tag_limit]
    else:
        tags_limited = False
    with indent_log():
        for tag in tags:
            logger.info(str(tag))
        if tags_limited:
            msg = f"...\n[First {tag_limit} tags shown. Pass --verbose to show all.]"
            logger.info(msg)
Referenced by pip._internal.commands.debug.DebugCommand.run().
show_value()
None pip._internal.commands.debug.show_value (str name, Any value)
Definition at line 26 of file debug.py.
def show_value(name: str, value: Any) -> None:
    logger.info("%s: %s", name, value)
Referenced by pip._internal.commands.debug.DebugCommand.run(), and show_sys_implementation().
show_vendor_versions()
None pip._internal.commands.debug.show_vendor_versions ()
Definition at line 103 of file debug.py.
def show_vendor_versions() -> None:
    logger.info("vendored library versions:")
    vendor_txt_versions = create_vendor_txt_map()
    with indent_log():
        show_actual_vendor_versions(vendor_txt_versions)
References create_vendor_txt_map(), and show_actual_vendor_versions().
Referenced by pip._internal.commands.debug.DebugCommand.run().
Variable Documentation
logger
pip._internal.commands.debug.logger = logging.getLogger(__name__)
Definition at line 23 of file debug.py.