Read&Watch: PIL.TiffImagePlugin Namespace Reference
PIL.TiffImagePlugin Namespace Reference
Classes
class AppendingTiffWriter
class IFDRational
class ImageFileDirectory_v1
class ImageFileDirectory_v2
class TiffImageFile
Image plugin for TIFF files.
Functions
bool _accept (bytes prefix)
tuple[IntegralLike, IntegralLike] _limit_rational (float|Fraction|IFDRational val, int max_val)
tuple[IntegralLike, IntegralLike] _limit_signed_rational (IFDRational val, int max_val, int min_val)
Any _delegate (str op)
Callable[[_LoaderFunc], _LoaderFunc] _register_loader (int idx, int size)
Callable[[Callable[..., Any]], Callable[..., Any]] _register_writer (int idx)
None _register_basic (tuple[int, str, str] idx_fmt_name)
None _save (Image.Image im, IO[bytes] fp, str|bytes filename)
None _save_all (Image.Image im, IO[bytes] fp, str|bytes filename)
Variables
logger = logging.getLogger(__name__)
bool READ_LIBTIFF = False
bool WRITE_LIBTIFF = False
int STRIP_SIZE = 65536
str II = b"II"
str MM = b"MM"
int OSUBFILETYPE = 255
int IMAGEWIDTH = 256
int IMAGELENGTH = 257
int BITSPERSAMPLE = 258
int COMPRESSION = 259
int PHOTOMETRIC_INTERPRETATION = 262
int FILLORDER = 266
int IMAGEDESCRIPTION = 270
int STRIPOFFSETS = 273
int SAMPLESPERPIXEL = 277
int ROWSPERSTRIP = 278
int STRIPBYTECOUNTS = 279
int X_RESOLUTION = 282
int Y_RESOLUTION = 283
int PLANAR_CONFIGURATION = 284
int RESOLUTION_UNIT = 296
int TRANSFERFUNCTION = 301
int SOFTWARE = 305
int DATE_TIME = 306
int ARTIST = 315
int PREDICTOR = 317
int COLORMAP = 320
int TILEWIDTH = 322
int TILELENGTH = 323
int TILEOFFSETS = 324
int TILEBYTECOUNTS = 325
int SUBIFD = 330
int EXTRASAMPLES = 338
int SAMPLEFORMAT = 339
int JPEGTABLES = 347
int YCBCRSUBSAMPLING = 530
int REFERENCEBLACKWHITE = 532
int COPYRIGHT = 33432
int IPTC_NAA_CHUNK = 33723
int PHOTOSHOP_CHUNK = 34377
int ICCPROFILE = 34675
int EXIFIFD = 34665
int XMP = 700
int JPEGQUALITY = 65537
int IMAGEJ_META_DATA_BYTE_COUNTS = 50838
int IMAGEJ_META_DATA = 50839
dict COMPRESSION_INFO
dict COMPRESSION_INFO_REV = {v: k for k, v in COMPRESSION_INFO.items()}
dict OPEN_INFO
MAX_SAMPLESPERPIXEL = max(len(key_tp[4]) for key_tp in OPEN_INFO)
list PREFIXES
dict _load_dispatch = {}
Wrapper for TIFF IFDs.
dict _write_dispatch = {}
_LoaderFunc = Callable[["ImageFileDirectory_v2", bytes, bool], Any]
_IFDv2Base = MutableMapping[int, Any]
name = name.replace(" ", "_")
ImageFileDirectory = ImageFileDirectory_v1
dict SAVE_INFO
_val
Function Documentation
_accept()
bool PIL.TiffImagePlugin._accept (bytes prefix) protected
Definition at line 290 of file TiffImagePlugin.py.
def _accept(prefix: bytes) -> bool:
    return prefix[:4] in PREFIXES
Referenced by PIL.TiffImagePlugin.ImageFileDirectory_v2.__init__().
_delegate()
Any PIL.TiffImagePlugin._delegate (str op) protected
Definition at line 325 of file TiffImagePlugin.py.
def _delegate(op: str) -> Any:
    def delegate(
        self: IFDRational, *args: tuple[float, ...]
    ) -> bool | float | Fraction:
        return getattr(self._val, op)(*args)
    return delegate
Referenced by PIL.TiffImagePlugin.IFDRational.__setstate__().
_limit_rational()
tuple[IntegralLike, IntegralLike] PIL.TiffImagePlugin._limit_rational (float | Fraction | IFDRational val, int max_val) protected
Definition at line 294 of file TiffImagePlugin.py.
) -> tuple[IntegralLike, IntegralLike]:
    inv = abs(float(val)) > 1
    n_d = IFDRational(1 / val if inv else val).limit_rational(max_val)
    return n_d[::-1] if inv else n_d
Referenced by _limit_signed_rational(), and PIL.TiffImagePlugin.ImageFileDirectory_v2.write_rational().
_limit_signed_rational()
tuple[IntegralLike, IntegralLike] PIL.TiffImagePlugin._limit_signed_rational (IFDRational val, int max_val, int min_val) protected
Definition at line 302 of file TiffImagePlugin.py.
) -> tuple[IntegralLike, IntegralLike]:
    frac = Fraction(val)
    n_d: tuple[IntegralLike, IntegralLike] = frac.numerator, frac.denominator
    if min(float(i) for i in n_d) < min_val:
        n_d = _limit_rational(val, abs(min_val))
    n_d_float = tuple(float(i) for i in n_d)
    if max(n_d_float) > max_val:
        n_d = _limit_rational(n_d_float[0] / n_d_float[1], max_val)
    return n_d
References _limit_rational().
Referenced by PIL.TiffImagePlugin.ImageFileDirectory_v2.write_signed_rational().
_register_basic()
None PIL.TiffImagePlugin._register_basic (tuple[int, str, str] idx_fmt_name) protected
Definition at line 495 of file TiffImagePlugin.py.
def _register_basic(idx_fmt_name: tuple[int, str, str]) -> None:
    from .TiffTags import TYPES
    idx, fmt, name = idx_fmt_name
    TYPES[idx] = name
    size = struct.calcsize(f"={fmt}")
    def basic_handler(
        self: ImageFileDirectory_v2, data: bytes, legacy_api: bool = True
    ) -> tuple[Any, ...]:
        return self._unpack(f"{len(data) // size}{fmt}", data)
    _load_dispatch[idx] = size, basic_handler  # noqa: F821
    _write_dispatch[idx] = lambda self, *values: (  # noqa: F821
        b"".join(self._pack(fmt, value) for value in values)
    )
_register_loader()
Callable[[_LoaderFunc], _LoaderFunc] PIL.TiffImagePlugin._register_loader (int idx, int size) protected
Definition at line 475 of file TiffImagePlugin.py.
def _register_loader(idx: int, size: int) -> Callable[[_LoaderFunc], _LoaderFunc]:
    def decorator(func: _LoaderFunc) -> _LoaderFunc:
        from .TiffTags import TYPES
        if func.__name__.startswith("load_"):
            TYPES[idx] = func.__name__[5:].replace("_", " ")
        _load_dispatch[idx] = size, func  # noqa: F821
        return func
    return decorator
_register_writer()
Callable[[Callable[..., Any]], Callable[..., Any]] PIL.TiffImagePlugin._register_writer (int idx) protected
Definition at line 487 of file TiffImagePlugin.py.
def _register_writer(idx: int) -> Callable[[Callable[..., Any]], Callable[..., Any]]:
    def decorator(func: Callable[..., Any]) -> Callable[..., Any]:
        _write_dispatch[idx] = func  # noqa: F821
        return func
    return decorator
_save()
None PIL.TiffImagePlugin._save (Image.Image im, IO[bytes] fp, str | bytes filename) protected
Definition at line 1662 of file TiffImagePlugin.py.
def _save(im: Image.Image, fp: IO[bytes], filename: str | bytes) -> None:
    try:
        rawmode, prefix, photo, format, bits, extra = SAVE_INFO[im.mode]
    except KeyError as e:
        msg = f"cannot write mode {im.mode} as TIFF"
        raise OSError(msg) from e
    ifd = ImageFileDirectory_v2(prefix=prefix)
    encoderinfo = im.encoderinfo
    encoderconfig = im.encoderconfig
    try:
        compression = encoderinfo["compression"]
    except KeyError:
        compression = im.info.get("compression")
        if isinstance(compression, int):
            # compression value may be from BMP. Ignore it
            compression = None
    if compression is None:
        compression = "raw"
    elif compression == "tiff_jpeg":
        # OJPEG is obsolete, so use new-style JPEG compression instead
        compression = "jpeg"
    elif compression == "tiff_deflate":
        compression = "tiff_adobe_deflate"
    libtiff = WRITE_LIBTIFF or compression != "raw"
    # required for color libtiff images
    ifd[PLANAR_CONFIGURATION] = 1
    ifd[IMAGEWIDTH] = im.size[0]
    ifd[IMAGELENGTH] = im.size[1]
    # write any arbitrary tags passed in as an ImageFileDirectory
    if "tiffinfo" in encoderinfo:
        info = encoderinfo["tiffinfo"]
    elif "exif" in encoderinfo:
        info = encoderinfo["exif"]
        if isinstance(info, bytes):
            exif = Image.Exif()
            exif.load(info)
            info = exif
    else:
        info = {}
    logger.debug("Tiffinfo Keys: %s", list(info))
    if isinstance(info, ImageFileDirectory_v1):
        info = info.to_v2()
    for key in info:
        if isinstance(info, Image.Exif) and key in TiffTags.TAGS_V2_GROUPS:
            ifd[key] = info.get_ifd(key)
        else:
            ifd[key] = info.get(key)
        try:
            ifd.tagtype[key] = info.tagtype[key]
        except Exception:
            pass  # might not be an IFD. Might not have populated type
    legacy_ifd = {}
    if hasattr(im, "tag"):
        legacy_ifd = im.tag.to_v2()
    supplied_tags = {**legacy_ifd, **getattr(im, "tag_v2", {})}
    for tag in (
        # IFD offset that may not be correct in the saved image
        EXIFIFD,
        # Determined by the image format and should not be copied from legacy_ifd.
        SAMPLEFORMAT,
    ):
        if tag in supplied_tags:
            del supplied_tags[tag]
    # additions written by Greg Couch, gregc@cgl.ucsf.edu
    # inspired by image-sig posting from Kevin Cazabon, kcazabon@home.com
    if hasattr(im, "tag_v2"):
        # preserve tags from original TIFF image file
        for key in (
            RESOLUTION_UNIT,
            X_RESOLUTION,
            Y_RESOLUTION,
            IPTC_NAA_CHUNK,
            PHOTOSHOP_CHUNK,
            XMP,
        ):
            if key in im.tag_v2:
                if key == IPTC_NAA_CHUNK and im.tag_v2.tagtype[key] not in (
                    TiffTags.BYTE,
                    TiffTags.UNDEFINED,
                ):
                    del supplied_tags[key]
                else:
                    ifd[key] = im.tag_v2[key]
                    ifd.tagtype[key] = im.tag_v2.tagtype[key]
    # preserve ICC profile (should also work when saving other formats
    # which support profiles as TIFF) -- 2008-06-06 Florian Hoech
    icc = encoderinfo.get("icc_profile", im.info.get("icc_profile"))
    if icc:
        ifd[ICCPROFILE] = icc
    for key, name in [
        (IMAGEDESCRIPTION, "description"),
        (X_RESOLUTION, "resolution"),
        (Y_RESOLUTION, "resolution"),
        (X_RESOLUTION, "x_resolution"),
        (Y_RESOLUTION, "y_resolution"),
        (RESOLUTION_UNIT, "resolution_unit"),
        (SOFTWARE, "software"),
        (DATE_TIME, "date_time"),
        (ARTIST, "artist"),
        (COPYRIGHT, "copyright"),
    ]:
        if name in encoderinfo:
            ifd[key] = encoderinfo[name]
    dpi = encoderinfo.get("dpi")
    if dpi:
        ifd[RESOLUTION_UNIT] = 2
        ifd[X_RESOLUTION] = dpi[0]
        ifd[Y_RESOLUTION] = dpi[1]
    if bits != (1,):
        ifd[BITSPERSAMPLE] = bits
        if len(bits) != 1:
            ifd[SAMPLESPERPIXEL] = len(bits)
    if extra is not None:
        ifd[EXTRASAMPLES] = extra
    if format != 1:
        ifd[SAMPLEFORMAT] = format
    if PHOTOMETRIC_INTERPRETATION not in ifd:
        ifd[PHOTOMETRIC_INTERPRETATION] = photo
    elif im.mode in ("1", "L") and ifd[PHOTOMETRIC_INTERPRETATION] == 0:
        if im.mode == "1":
            inverted_im = im.copy()
            px = inverted_im.load()
            if px is not None:
                for y in range(inverted_im.height):
                    for x in range(inverted_im.width):
                        px[x, y] = 0 if px[x, y] == 255 else 255
                im = inverted_im
        else:
            im = ImageOps.invert(im)
    if im.mode in ["P", "PA"]:
        lut = im.im.getpalette("RGB", "RGB;L")
        colormap = []
        colors = len(lut) // 3
        for i in range(3):
            colormap += [v * 256 for v in lut[colors * i : colors * (i + 1)]]
            colormap += [0] * (256 - colors)
        ifd[COLORMAP] = colormap
    # data orientation
    w, h = ifd[IMAGEWIDTH], ifd[IMAGELENGTH]
    stride = len(bits) * ((w * bits[0] + 7) // 8)
    if ROWSPERSTRIP not in ifd:
        # aim for given strip size (64 KB by default) when using libtiff writer
        if libtiff:
            im_strip_size = encoderinfo.get("strip_size", STRIP_SIZE)
            rows_per_strip = 1 if stride == 0 else min(im_strip_size // stride, h)
            # JPEG encoder expects multiple of 8 rows
            if compression == "jpeg":
                rows_per_strip = min(((rows_per_strip + 7) // 8) * 8, h)
        else:
            rows_per_strip = h
        if rows_per_strip == 0:
            rows_per_strip = 1
        ifd[ROWSPERSTRIP] = rows_per_strip
    strip_byte_counts = 1 if stride == 0 else stride * ifd[ROWSPERSTRIP]
    strips_per_image = (h + ifd[ROWSPERSTRIP] - 1) // ifd[ROWSPERSTRIP]
    if strip_byte_counts >= 2**16:
        ifd.tagtype[STRIPBYTECOUNTS] = TiffTags.LONG
    ifd[STRIPBYTECOUNTS] = (strip_byte_counts,) * (strips_per_image - 1) + (
        stride * h - strip_byte_counts * (strips_per_image - 1),
    )
    ifd[STRIPOFFSETS] = tuple(
        range(0, strip_byte_counts * strips_per_image, strip_byte_counts)
    )  # this is adjusted by IFD writer
    # no compression by default:
    ifd[COMPRESSION] = COMPRESSION_INFO_REV.get(compression, 1)
    if im.mode == "YCbCr":
        for tag, default_value in {
            YCBCRSUBSAMPLING: (1, 1),
            REFERENCEBLACKWHITE: (0, 255, 128, 255, 128, 255),
        }.items():
            ifd.setdefault(tag, default_value)
    blocklist = [TILEWIDTH, TILELENGTH, TILEOFFSETS, TILEBYTECOUNTS]
    if libtiff:
        if "quality" in encoderinfo:
            quality = encoderinfo["quality"]
            if not isinstance(quality, int) or quality < 0 or quality > 100:
                msg = "Invalid quality setting"
                raise ValueError(msg)
            if compression != "jpeg":
                msg = "quality setting only supported for 'jpeg' compression"
                raise ValueError(msg)
            ifd[JPEGQUALITY] = quality
        logger.debug("Saving using libtiff encoder")
        logger.debug("Items: %s", sorted(ifd.items()))
        _fp = 0
        if hasattr(fp, "fileno"):
            try:
                fp.seek(0)
                _fp = fp.fileno()
            except io.UnsupportedOperation:
                pass
        # optional types for non core tags
        types = {}
        # STRIPOFFSETS and STRIPBYTECOUNTS are added by the library
        # based on the data in the strip.
        # OSUBFILETYPE is deprecated.
        # The other tags expect arrays with a certain length (fixed or depending on
        # BITSPERSAMPLE, etc), passing arrays with a different length will result in
        # segfaults. Block these tags until we add extra validation.
        # SUBIFD may also cause a segfault.
        blocklist += [
            OSUBFILETYPE,
            REFERENCEBLACKWHITE,
            STRIPBYTECOUNTS,
            STRIPOFFSETS,
            TRANSFERFUNCTION,
            SUBIFD,
        ]
        # bits per sample is a single short in the tiff directory, not a list.
        atts: dict[int, Any] = {BITSPERSAMPLE: bits[0]}
        # Merge the ones that we have with (optional) more bits from
        # the original file, e.g x,y resolution so that we can
        # save(load('')) == original file.
        for tag, value in itertools.chain(ifd.items(), supplied_tags.items()):
            # Libtiff can only process certain core items without adding
            # them to the custom dictionary.
            # Custom items are supported for int, float, unicode, string and byte
            # values. Other types and tuples require a tagtype.
            if tag not in TiffTags.LIBTIFF_CORE:
                if not getattr(Image.core, "libtiff_support_custom_tags", False):
                    continue
                if tag in ifd.tagtype:
                    types[tag] = ifd.tagtype[tag]
                elif not (isinstance(value, (int, float, str, bytes))):
                    continue
                else:
                    type = TiffTags.lookup(tag).type
                    if type:
                        types[tag] = type
            if tag not in atts and tag not in blocklist:
                if isinstance(value, str):
                    atts[tag] = value.encode("ascii", "replace") + b"\0"
                elif isinstance(value, IFDRational):
                    atts[tag] = float(value)
                else:
                    atts[tag] = value
        if SAMPLEFORMAT in atts and len(atts[SAMPLEFORMAT]) == 1:
            atts[SAMPLEFORMAT] = atts[SAMPLEFORMAT][0]
        logger.debug("Converted items: %s", sorted(atts.items()))
        # libtiff always expects the bytes in native order.
        # we're storing image byte order. So, if the rawmode
        # contains I;16, we need to convert from native to image
        # byte order.
        if im.mode in ("I;16B", "I;16"):
            rawmode = "I;16N"
        # Pass tags as sorted list so that the tags are set in a fixed order.
        # This is required by libtiff for some tags. For example, the JPEGQUALITY
        # pseudo tag requires that the COMPRESS tag was already set.
        tags = list(atts.items())
        tags.sort()
        a = (rawmode, compression, _fp, filename, tags, types)
        encoder = Image._getencoder(im.mode, "libtiff", a, encoderconfig)
        encoder.setimage(im.im, (0, 0) + im.size)
        while True:
            errcode, data = encoder.encode(ImageFile.MAXBLOCK)[1:]
            if not _fp:
                fp.write(data)
            if errcode:
                break
        if errcode < 0:
            msg = f"encoder error {errcode} when writing image file"
            raise OSError(msg)
    else:
        for tag in blocklist:
            del ifd[tag]
        offset = ifd.save(fp)
        ImageFile._save(
            im,
            fp,
            [ImageFile._Tile("raw", (0, 0) + im.size, offset, (rawmode, stride, 1))],
        )
    # -- helper for multi-page save --
    if "_debug_multipage" in encoderinfo:
        # just to access o32 and o16 (using correct byte order)
        setattr(im, "_debug_multipage", ifd)
_save_all()
None PIL.TiffImagePlugin._save_all (Image.Image im, IO[bytes] fp, str | bytes filename) protected
Definition at line 2234 of file TiffImagePlugin.py.
def _save_all(im: Image.Image, fp: IO[bytes], filename: str | bytes) -> None:
    encoderinfo = im.encoderinfo.copy()
    encoderconfig = im.encoderconfig
    append_images = list(encoderinfo.get("append_images", []))
    if not hasattr(im, "n_frames") and not append_images:
        return _save(im, fp, filename)
    cur_idx = im.tell()
    try:
        with AppendingTiffWriter(fp) as tf:
            for ims in [im] + append_images:
                ims.encoderinfo = encoderinfo
                ims.encoderconfig = encoderconfig
                if not hasattr(ims, "n_frames"):
                    nfr = 1
                else:
                    nfr = ims.n_frames
                for idx in range(nfr):
                    ims.seek(idx)
                    ims.load()
                    _save(ims, tf, filename)
                    tf.newFrame()
    finally:
        im.seek(cur_idx)
#
# --------------------------------------------------------------------
# Register
Variable Documentation
_IFDv2Base
PIL.TiffImagePlugin._IFDv2Base = MutableMapping[int, Any] protected
Definition at line 514 of file TiffImagePlugin.py.
_load_dispatch
dict PIL.TiffImagePlugin._load_dispatch = {} protected
Wrapper for TIFF IFDs.
Definition at line 321 of file TiffImagePlugin.py.
_LoaderFunc
PIL.TiffImagePlugin._LoaderFunc = Callable[["ImageFileDirectory_v2", bytes, bool], Any] protected
Definition at line 472 of file TiffImagePlugin.py.
_val
PIL.TiffImagePlugin._val protected
Definition at line 329 of file TiffImagePlugin.py.
_write_dispatch
dict PIL.TiffImagePlugin._write_dispatch = {} protected
Definition at line 322 of file TiffImagePlugin.py.
ARTIST
int PIL.TiffImagePlugin.ARTIST = 315
Definition at line 101 of file TiffImagePlugin.py.
BITSPERSAMPLE
int PIL.TiffImagePlugin.BITSPERSAMPLE = 258
Definition at line 85 of file TiffImagePlugin.py.
COLORMAP
int PIL.TiffImagePlugin.COLORMAP = 320
Definition at line 103 of file TiffImagePlugin.py.
COMPRESSION
int PIL.TiffImagePlugin.COMPRESSION = 259
Definition at line 86 of file TiffImagePlugin.py.
COMPRESSION_INFO
dict PIL.TiffImagePlugin.COMPRESSION_INFO
Initial value:
=  {
    # Compression => pil compression name
    1: "raw",
    2: "tiff_ccitt",
    3: "group3",
    4: "group4",
    5: "tiff_lzw",
    6: "tiff_jpeg",  # obsolete
    7: "jpeg",
    8: "tiff_adobe_deflate",
    32771: "tiff_raw_16",  # 16-bit padding
    32773: "packbits",
    32809: "tiff_thunderscan",
    32946: "tiff_deflate",
    34676: "tiff_sgilog",
    34677: "tiff_sgilog24",
    34925: "lzma",
    50000: "zstd",
    50001: "webp",
}
Definition at line 126 of file TiffImagePlugin.py.
COMPRESSION_INFO_REV
dict PIL.TiffImagePlugin.COMPRESSION_INFO_REV = {v: k for k, v in COMPRESSION_INFO.items()}
Definition at line 147 of file TiffImagePlugin.py.
COPYRIGHT
int PIL.TiffImagePlugin.COPYRIGHT = 33432
Definition at line 114 of file TiffImagePlugin.py.
DATE_TIME
int PIL.TiffImagePlugin.DATE_TIME = 306
Definition at line 100 of file TiffImagePlugin.py.
EXIFIFD
int PIL.TiffImagePlugin.EXIFIFD = 34665
Definition at line 118 of file TiffImagePlugin.py.
EXTRASAMPLES
int PIL.TiffImagePlugin.EXTRASAMPLES = 338
Definition at line 109 of file TiffImagePlugin.py.
FILLORDER
int PIL.TiffImagePlugin.FILLORDER = 266
Definition at line 88 of file TiffImagePlugin.py.
ICCPROFILE
int PIL.TiffImagePlugin.ICCPROFILE = 34675
Definition at line 117 of file TiffImagePlugin.py.
II
str PIL.TiffImagePlugin.II = b"II"
Definition at line 74 of file TiffImagePlugin.py.
IMAGEDESCRIPTION
int PIL.TiffImagePlugin.IMAGEDESCRIPTION = 270
Definition at line 89 of file TiffImagePlugin.py.
ImageFileDirectory
PIL.TiffImagePlugin.ImageFileDirectory = ImageFileDirectory_v1
Definition at line 1130 of file TiffImagePlugin.py.
IMAGEJ_META_DATA
int PIL.TiffImagePlugin.IMAGEJ_META_DATA = 50839
Definition at line 124 of file TiffImagePlugin.py.
IMAGEJ_META_DATA_BYTE_COUNTS
int PIL.TiffImagePlugin.IMAGEJ_META_DATA_BYTE_COUNTS = 50838
Definition at line 123 of file TiffImagePlugin.py.
IMAGELENGTH
int PIL.TiffImagePlugin.IMAGELENGTH = 257
Definition at line 84 of file TiffImagePlugin.py.
IMAGEWIDTH
int PIL.TiffImagePlugin.IMAGEWIDTH = 256
Definition at line 83 of file TiffImagePlugin.py.
IPTC_NAA_CHUNK
int PIL.TiffImagePlugin.IPTC_NAA_CHUNK = 33723
Definition at line 115 of file TiffImagePlugin.py.
JPEGQUALITY
int PIL.TiffImagePlugin.JPEGQUALITY = 65537
Definition at line 120 of file TiffImagePlugin.py.
JPEGTABLES
int PIL.TiffImagePlugin.JPEGTABLES = 347
Definition at line 111 of file TiffImagePlugin.py.
logger
PIL.TiffImagePlugin.logger = logging.getLogger(__name__)
Definition at line 67 of file TiffImagePlugin.py.
MAX_SAMPLESPERPIXEL
PIL.TiffImagePlugin.MAX_SAMPLESPERPIXEL = max(len(key_tp[4]) for key_tp in OPEN_INFO)
Definition at line 275 of file TiffImagePlugin.py.
MM
str PIL.TiffImagePlugin.MM = b"MM"
Definition at line 75 of file TiffImagePlugin.py.
name
PIL.TiffImagePlugin.name = name.replace(" ", "_")
Definition at line 1031 of file TiffImagePlugin.py.
OPEN_INFO
dict PIL.TiffImagePlugin.OPEN_INFO
Definition at line 149 of file TiffImagePlugin.py.
OSUBFILETYPE
int PIL.TiffImagePlugin.OSUBFILETYPE = 255
Definition at line 82 of file TiffImagePlugin.py.
PHOTOMETRIC_INTERPRETATION
int PIL.TiffImagePlugin.PHOTOMETRIC_INTERPRETATION = 262
Definition at line 87 of file TiffImagePlugin.py.
PHOTOSHOP_CHUNK
int PIL.TiffImagePlugin.PHOTOSHOP_CHUNK = 34377
Definition at line 116 of file TiffImagePlugin.py.
PLANAR_CONFIGURATION
int PIL.TiffImagePlugin.PLANAR_CONFIGURATION = 284
Definition at line 96 of file TiffImagePlugin.py.
PREDICTOR
int PIL.TiffImagePlugin.PREDICTOR = 317
Definition at line 102 of file TiffImagePlugin.py.
PREFIXES
list PIL.TiffImagePlugin.PREFIXES
Initial value:
=  [
    b"MM\x00\x2A",  # Valid TIFF header with big-endian byte order
    b"II\x2A\x00",  # Valid TIFF header with little-endian byte order
    b"MM\x2A\x00",  # Invalid TIFF header, assume big-endian
    b"II\x00\x2A",  # Invalid TIFF header, assume little-endian
    b"MM\x00\x2B",  # BigTIFF with big-endian byte order
    b"II\x2B\x00",  # BigTIFF with little-endian byte order
]
Definition at line 277 of file TiffImagePlugin.py.
READ_LIBTIFF
bool PIL.TiffImagePlugin.READ_LIBTIFF = False
Definition at line 70 of file TiffImagePlugin.py.
REFERENCEBLACKWHITE
int PIL.TiffImagePlugin.REFERENCEBLACKWHITE = 532
Definition at line 113 of file TiffImagePlugin.py.
RESOLUTION_UNIT
int PIL.TiffImagePlugin.RESOLUTION_UNIT = 296
Definition at line 97 of file TiffImagePlugin.py.
ROWSPERSTRIP
int PIL.TiffImagePlugin.ROWSPERSTRIP = 278
Definition at line 92 of file TiffImagePlugin.py.
SAMPLEFORMAT
int PIL.TiffImagePlugin.SAMPLEFORMAT = 339
Definition at line 110 of file TiffImagePlugin.py.
SAMPLESPERPIXEL
int PIL.TiffImagePlugin.SAMPLESPERPIXEL = 277
Definition at line 91 of file TiffImagePlugin.py.
SAVE_INFO
dict PIL.TiffImagePlugin.SAVE_INFO
Initial value:
=  {
    # mode => rawmode, byteorder, photometrics,
    #           sampleformat, bitspersample, extra
    "1": ("1", II, 1, 1, (1,), None),
    "L": ("L", II, 1, 1, (8,), None),
    "LA": ("LA", II, 1, 1, (8, 8), 2),
    "P": ("P", II, 3, 1, (8,), None),
    "PA": ("PA", II, 3, 1, (8, 8), 2),
    "I": ("I;32S", II, 1, 2, (32,), None),
    "I;16": ("I;16", II, 1, 1, (16,), None),
    "I;16S": ("I;16S", II, 1, 2, (16,), None),
    "F": ("F;32F", II, 1, 3, (32,), None),
    "RGB": ("RGB", II, 2, 1, (8, 8, 8), None),
    "RGBX": ("RGBX", II, 2, 1, (8, 8, 8, 8), 0),
    "RGBA": ("RGBA", II, 2, 1, (8, 8, 8, 8), 2),
    "CMYK": ("CMYK", II, 5, 1, (8, 8, 8, 8), None),
    "YCbCr": ("YCbCr", II, 6, 1, (8, 8, 8), None),
    "LAB": ("LAB", II, 8, 1, (8, 8, 8), None),
    "I;32BS": ("I;32BS", MM, 1, 2, (32,), None),
    "I;16B": ("I;16B", MM, 1, 1, (16,), None),
    "I;16BS": ("I;16BS", MM, 1, 2, (16,), None),
    "F;32BF": ("F;32BF", MM, 1, 3, (32,), None),
}
Definition at line 1637 of file TiffImagePlugin.py.
SOFTWARE
int PIL.TiffImagePlugin.SOFTWARE = 305
Definition at line 99 of file TiffImagePlugin.py.
STRIP_SIZE
int PIL.TiffImagePlugin.STRIP_SIZE = 65536
Definition at line 72 of file TiffImagePlugin.py.
STRIPBYTECOUNTS
int PIL.TiffImagePlugin.STRIPBYTECOUNTS = 279
Definition at line 93 of file TiffImagePlugin.py.
STRIPOFFSETS
int PIL.TiffImagePlugin.STRIPOFFSETS = 273
Definition at line 90 of file TiffImagePlugin.py.
SUBIFD
int PIL.TiffImagePlugin.SUBIFD = 330
Definition at line 108 of file TiffImagePlugin.py.
TILEBYTECOUNTS
int PIL.TiffImagePlugin.TILEBYTECOUNTS = 325
Definition at line 107 of file TiffImagePlugin.py.
TILELENGTH
int PIL.TiffImagePlugin.TILELENGTH = 323
Definition at line 105 of file TiffImagePlugin.py.
TILEOFFSETS
int PIL.TiffImagePlugin.TILEOFFSETS = 324
Definition at line 106 of file TiffImagePlugin.py.
TILEWIDTH
int PIL.TiffImagePlugin.TILEWIDTH = 322
Definition at line 104 of file TiffImagePlugin.py.
TRANSFERFUNCTION
int PIL.TiffImagePlugin.TRANSFERFUNCTION = 301
Definition at line 98 of file TiffImagePlugin.py.
WRITE_LIBTIFF
bool PIL.TiffImagePlugin.WRITE_LIBTIFF = False
Definition at line 71 of file TiffImagePlugin.py.
X_RESOLUTION
int PIL.TiffImagePlugin.X_RESOLUTION = 282
Definition at line 94 of file TiffImagePlugin.py.
XMP
int PIL.TiffImagePlugin.XMP = 700
Definition at line 119 of file TiffImagePlugin.py.
Y_RESOLUTION
int PIL.TiffImagePlugin.Y_RESOLUTION = 283
Definition at line 95 of file TiffImagePlugin.py.
YCBCRSUBSAMPLING
int PIL.TiffImagePlugin.YCBCRSUBSAMPLING = 530
Definition at line 112 of file TiffImagePlugin.py.