Read&Watch: pylint.lint.pylinter Namespace Reference
pylint.lint.pylinter Namespace Reference
Classes
class GetAstProtocol
class PyLinter
Functions
str _read_stdin ()
type[BaseReporter] _load_reporter_by_class (str reporter_class)
Variables
MANAGER = astroid.MANAGER
dict MSGS
Function Documentation
_load_reporter_by_class()
type[BaseReporter] pylint.lint.pylinter._load_reporter_by_class (str reporter_class) protected
Definition at line 86 of file pylinter.py.
def _load_reporter_by_class(reporter_class: str) -> type[BaseReporter]:
    qname = reporter_class
    module_part = astroid.modutils.get_module_part(qname)
    module = astroid.modutils.load_module_from_name(module_part)
    class_name = qname.split(".")[-1]
    klass = getattr(module, class_name)
    assert issubclass(klass, BaseReporter), f"{klass} is not a BaseReporter"
    return klass  # type: ignore[no-any-return]
# Python Linter class #########################################################
# pylint: disable-next=consider-using-namedtuple-or-dataclass
References astroid.modutils.get_module_part(), and astroid.modutils.load_module_from_name().
Referenced by pylint.lint.pylinter.PyLinter._load_reporter_by_name().
_read_stdin()
str pylint.lint.pylinter._read_stdin () protected
Definition at line 79 of file pylinter.py.
def _read_stdin() -> str:
    # See https://github.com/python/typeshed/pull/5623 for rationale behind assertion
    assert isinstance(sys.stdin, TextIOWrapper)
    sys.stdin = TextIOWrapper(sys.stdin.detach(), encoding="utf-8")
    return sys.stdin.read()
Referenced by pylint.lint.pylinter.PyLinter.check().
Variable Documentation
MANAGER
pylint.lint.pylinter.MANAGER = astroid.MANAGER
Definition at line 70 of file pylinter.py.
MSGS
dict pylint.lint.pylinter.MSGS
Definition at line 99 of file pylinter.py.