Read&Watch: pylint.utils.utils Namespace Reference
pylint.utils.utils Namespace Reference
Classes
class IsortDriver
Functions
str normalize_text (str text, int line_len=DEFAULT_LINE_LENGTH, str indent="")
int cmp (float a, float b)
str diff_string (float old, float new)
tuple[str, str] get_module_and_frameid (nodes.NodeNG node)
str get_rst_title (str title, str character)
str get_rst_section (str|None section, list[tuple[str, OptionDict, Any]] options, str|None doc=None)
codecs.StreamReader decoding_stream (BufferedReader|BytesIO stream, str encoding, Literal["strict"] errors="strict")
list[tokenize.TokenInfo] tokenize_module (nodes.Module node)
None register_plugins (PyLinter linter, str directory)
list[str] _splitstrip (str string, str sep=",")
str _unquote (str string)
Sequence[str] _check_csv (list[str]|tuple[str]|str value)
Iterable[str] _check_regexp_csv (list[str]|tuple[str]|str value)
str _comment (str string)
str _format_option_value (OptionDict optdict, Any value)
None format_section (TextIO stream, str section, list[tuple[str, OptionDict, Any]] options, str|None doc=None)
None _ini_format (TextIO stream, list[tuple[str, OptionDict, Any]] options)
Variables
bool HAS_ISORT_5 = True
int DEFAULT_LINE_LENGTH = 79
GLOBAL_OPTION_BOOL
GLOBAL_OPTION_INT = Literal["max-line-length", "docstring-min-length"]
GLOBAL_OPTION_LIST = Literal["ignored-modules"]
GLOBAL_OPTION_PATTERN
GLOBAL_OPTION_PATTERN_LIST = Literal["exclude-too-few-public-methods", "ignore-paths"]
GLOBAL_OPTION_TUPLE_INT = Literal["py-version"]
GLOBAL_OPTION_NAMES
T_GlobalOptionReturnTypes
list CMPS = ["=", "-", "+"]
Function Documentation
_check_csv()
Sequence[str] pylint.utils.utils._check_csv (list[str] | tuple[str] | str value) protected
Definition at line 241 of file utils.py.
def _check_csv(value: list[str] | tuple[str] | str) -> Sequence[str]:
    if isinstance(value, (list, tuple)):
        return value
    return _splitstrip(value)
References _splitstrip().
_check_regexp_csv()
Iterable[str] pylint.utils.utils._check_regexp_csv (list[str] | tuple[str] | str value) protected
Split a comma-separated list of regexps, taking care to avoid splitting
a regex employing a comma as quantifier, as in `\d{1,2}`.
Definition at line 247 of file utils.py.
def _check_regexp_csv(value: list[str] | tuple[str] | str) -> Iterable[str]:
    r"""Split a comma-separated list of regexps, taking care to avoid splitting
    a regex employing a comma as quantifier, as in `\d{1,2}`.
    """
    if isinstance(value, (list, tuple)):
        yield from value
    else:
        # None is a sentinel value here
        regexps: deque[deque[str] | None] = deque([None])
        open_braces = False
        for char in value:
            if char == "{":
                open_braces = True
            elif char == "}" and open_braces:
                open_braces = False
            if char == "," and not open_braces:
                regexps.append(None)
            elif regexps[-1] is None:
                regexps.pop()
                regexps.append(deque([char]))
            else:
                regexps[-1].append(char)
        yield from ("".join(regexp).strip() for regexp in regexps if regexp is not None)
_comment()
str pylint.utils.utils._comment (str string) protected
Return string as a comment.
Definition at line 273 of file utils.py.
def _comment(string: str) -> str:
    """Return string as a comment."""
    lines = [line.strip() for line in string.splitlines()]
    sep = "\n"
    return "# " + f"{sep}# ".join(lines)
Referenced by format_section().
_format_option_value()
str pylint.utils.utils._format_option_value (OptionDict optdict, Any value) protected
Return the user input's value from a 'compiled' value.
TODO: Refactor the code to not use this deprecated function
Definition at line 280 of file utils.py.
def _format_option_value(optdict: OptionDict, value: Any) -> str:
    """Return the user input's value from a 'compiled' value.
    TODO: Refactor the code to not use this deprecated function
    """
    if optdict.get("type", None) == "py_version":
        value = ".".join(str(item) for item in value)
    elif isinstance(value, (list, tuple)):
        value = ",".join(_format_option_value(optdict, item) for item in value)
    elif isinstance(value, dict):
        value = ",".join(f"{k}:{v}" for k, v in value.items())
    elif hasattr(value, "match"):  # optdict.get('type') == 'regexp'
        # compiled regexp
        value = value.pattern
    elif optdict.get("type") == "yn":
        value = "yes" if value else "no"
    elif isinstance(value, str) and value.isspace():
        value = f"'{value}'"
    return str(value)
References _format_option_value().
Referenced by _format_option_value(), _ini_format(), and get_rst_section().
_ini_format()
None pylint.utils.utils._ini_format (TextIO stream, list[tuple[str, OptionDict, Any]] options) protected
Format options using the INI format.
Definition at line 321 of file utils.py.
def _ini_format(stream: TextIO, options: list[tuple[str, OptionDict, Any]]) -> None:
    """Format options using the INI format."""
    warnings.warn(
        "_ini_format has been deprecated. It will be removed in pylint 4.0.",
        DeprecationWarning,
        stacklevel=2,
    )
    for optname, optdict, value in options:
        # Skip deprecated option
        if "kwargs" in optdict:
            assert isinstance(optdict["kwargs"], dict)
            if "new_names" in optdict["kwargs"]:
                continue
        value = _format_option_value(optdict, value)
        help_opt = optdict.get("help")
        if help_opt:
            assert isinstance(help_opt, str)
            help_opt = normalize_text(help_opt, indent="# ")
            print(file=stream)
            print(help_opt, file=stream)
        else:
            print(file=stream)
        if value in {"None", "False"}:
            print(f"#{optname}=", file=stream)
        else:
            value = str(value).strip()
            if re.match(r"^([\w-]+,)+[\w-]+$", str(value)):
                separator = "\n " + " " * len(optname)
                value = separator.join(x + "," for x in str(value).split(","))
                # remove trailing ',' from last element of the list
                value = value[:-1]
            print(f"{optname}={value}", file=stream)
References _format_option_value(), and normalize_text().
Referenced by format_section().
_splitstrip()
list[str] pylint.utils.utils._splitstrip (str string, str sep = ",") protected
Return a list of stripped string by splitting the string given as
argument on `sep` (',' by default), empty strings are discarded.
>>> _splitstrip('a, b, c   ,  4,,')
['a', 'b', 'c', '4']
>>> _splitstrip('a')
['a']
>>> _splitstrip('a,\nb,\nc,')
['a', 'b', 'c']
:type string: str or unicode
:param string: a csv line
:type sep: str or unicode
:param sep: field separator, default to the comma (',')
:rtype: str or unicode
:return: the unquoted string (or the input string if it wasn't quoted)
Definition at line 203 of file utils.py.
def _splitstrip(string: str, sep: str = ",") -> list[str]:
    r"""Return a list of stripped string by splitting the string given as
    argument on `sep` (',' by default), empty strings are discarded.
    >>> _splitstrip('a, b, c   ,  4,,')
    ['a', 'b', 'c', '4']
    >>> _splitstrip('a')
    ['a']
    >>> _splitstrip('a,\nb,\nc,')
    ['a', 'b', 'c']
    :type string: str or unicode
    :param string: a csv line
    :type sep: str or unicode
    :param sep: field separator, default to the comma (',')
    :rtype: str or unicode
    :return: the unquoted string (or the input string if it wasn't quoted)
    """
    return [word.strip() for word in string.split(sep) if word.strip()]
Referenced by _check_csv().
_unquote()
str pylint.utils.utils._unquote (str string) protected
Remove optional quotes (simple or double) from the string.
:param string: an optionally quoted string
:return: the unquoted string (or the input string if it wasn't quoted)
Definition at line 226 of file utils.py.
def _unquote(string: str) -> str:
    """Remove optional quotes (simple or double) from the string.
    :param string: an optionally quoted string
    :return: the unquoted string (or the input string if it wasn't quoted)
    """
    if not string:
        return string
    if string[0] in "\"'":
        string = string[1:]
    if string[-1] in "\"'":
        string = string[:-1]
    return string
cmp()
int pylint.utils.utils.cmp (float a, float b)
Definition at line 92 of file utils.py.
def cmp(a: float, b: float) -> int:
    return (a > b) - (a < b)
decoding_stream()
codecs.StreamReader pylint.utils.utils.decoding_stream (BufferedReader | BytesIO stream, str encoding, Literal["strict"] errors = "strict")
Definition at line 152 of file utils.py.
) -> codecs.StreamReader:
    try:
        reader_cls = codecs.getreader(encoding or sys.getdefaultencoding())
    except LookupError:
        reader_cls = codecs.getreader(sys.getdefaultencoding())
    return reader_cls(stream, errors)
diff_string()
str pylint.utils.utils.diff_string (float old, float new)
Given an old and new value, return a string representing the difference.
Definition at line 96 of file utils.py.
def diff_string(old: float, new: float) -> str:
    """Given an old and new value, return a string representing the difference."""
    diff = abs(old - new)
    diff_str = f"{CMPS[cmp(old, new)]}{diff and f'{diff:.2f}' or ''}"
    return diff_str
format_section()
None pylint.utils.utils.format_section (TextIO stream, str section, list[tuple[str, OptionDict, Any]] options, str | None doc = None)
Format an option's section using the INI format.
Definition at line 301 of file utils.py.
) -> None:
    """Format an option's section using the INI format."""
    warnings.warn(
        "format_section has been deprecated. It will be removed in pylint 4.0.",
        DeprecationWarning,
        stacklevel=2,
    )
    if doc:
        print(_comment(doc), file=stream)
    print(f"[{section}]", file=stream)
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=DeprecationWarning)
        _ini_format(stream, options)
References _comment(), and _ini_format().
get_module_and_frameid()
tuple[str, str] pylint.utils.utils.get_module_and_frameid (nodes.NodeNG node)
Return the module name and the frame id in the module.
Definition at line 103 of file utils.py.
def get_module_and_frameid(node: nodes.NodeNG) -> tuple[str, str]:
    """Return the module name and the frame id in the module."""
    frame = node.frame()
    module, obj = "", []
    while frame:
        if isinstance(frame, Module):
            module = frame.name
        else:
            obj.append(getattr(frame, "name", "<lambda>"))
        try:
            frame = frame.parent.frame()
        except AttributeError:
            break
    obj.reverse()
    return module, ".".join(obj)
get_rst_section()
str pylint.utils.utils.get_rst_section (str | None section, list[tuple[str, OptionDict, Any]] options, str | None doc = None)
Format an option's section using as a ReStructuredText formatted output.
Definition at line 127 of file utils.py.
) -> str:
    """Format an option's section using as a ReStructuredText formatted output."""
    result = ""
    if section:
        result += get_rst_title(section, "'")
    if doc:
        formatted_doc = normalize_text(doc)
        result += f"{formatted_doc}\n\n"
    for optname, optdict, value in options:
        help_opt = optdict.get("help")
        result += f":{optname}:\n"
        if help_opt:
            assert isinstance(help_opt, str)
            formatted_help = normalize_text(help_opt, indent="  ")
            result += f"{formatted_help}\n"
        if value and optname != "py-version":
            value = str(_format_option_value(optdict, value))
            result += f"\n  Default: ``{value.replace('`` ', '```` ``')}``\n"
    return result
References _format_option_value(), get_rst_title(), and normalize_text().
get_rst_title()
str pylint.utils.utils.get_rst_title (str title, str character)
Permit to get a title formatted as ReStructuredText test (underlined with a
chosen character).
Definition at line 120 of file utils.py.
def get_rst_title(title: str, character: str) -> str:
    """Permit to get a title formatted as ReStructuredText test (underlined with a
    chosen character).
    """
    return f"{title}\n{character * len(title)}\n"
Referenced by get_rst_section().
normalize_text()
str pylint.utils.utils.normalize_text (str text, int line_len = DEFAULT_LINE_LENGTH, str indent = "")
Wrap the text on the given line length.
Definition at line 77 of file utils.py.
) -> str:
    """Wrap the text on the given line length."""
    return "\n".join(
        textwrap.wrap(
            text, width=line_len, initial_indent=indent, subsequent_indent=indent
        )
    )
Referenced by _ini_format(), and get_rst_section().
register_plugins()
None pylint.utils.utils.register_plugins (PyLinter linter, str directory)
Load all module and package in the given directory, looking for a
'register' function in each one, used to register pylint checkers.
Definition at line 170 of file utils.py.
def register_plugins(linter: PyLinter, directory: str) -> None:
    """Load all module and package in the given directory, looking for a
    'register' function in each one, used to register pylint checkers.
    """
    imported = {}
    for filename in os.listdir(directory):
        base, extension = os.path.splitext(filename)
        if base in imported or base == "__pycache__":
            continue
        if (
            extension in PY_EXTS
            and base != "__init__"
            or (
                not extension
                and os.path.isdir(os.path.join(directory, base))
                and not filename.startswith(".")
            )
        ):
            try:
                module = modutils.load_module_from_file(
                    os.path.join(directory, filename)
                )
            except ValueError:
                # empty module name (usually Emacs auto-save files)
                continue
            except ImportError as exc:
                print(f"Problem importing module {filename}: {exc}", file=sys.stderr)
            else:
                if hasattr(module, "register"):
                    module.register(linter)
                    imported[base] = 1
tokenize_module()
list[tokenize.TokenInfo] pylint.utils.utils.tokenize_module (nodes.Module node)
Definition at line 164 of file utils.py.
def tokenize_module(node: nodes.Module) -> list[tokenize.TokenInfo]:
    with node.stream() as stream:
        readline = stream.readline
        return list(tokenize.tokenize(readline))
Variable Documentation
CMPS
list pylint.utils.utils.CMPS = ["=", "-", "+"]
Definition at line 88 of file utils.py.
DEFAULT_LINE_LENGTH
int pylint.utils.utils.DEFAULT_LINE_LENGTH = 79
Definition at line 39 of file utils.py.
GLOBAL_OPTION_BOOL
pylint.utils.utils.GLOBAL_OPTION_BOOL
Initial value:
=  Literal[
    "suggestion-mode",
    "analyse-fallback-blocks",
    "allow-global-unused-variables",
    "prefer-stubs",
]
Definition at line 42 of file utils.py.
GLOBAL_OPTION_INT
pylint.utils.utils.GLOBAL_OPTION_INT = Literal["max-line-length", "docstring-min-length"]
Definition at line 48 of file utils.py.
GLOBAL_OPTION_LIST
pylint.utils.utils.GLOBAL_OPTION_LIST = Literal["ignored-modules"]
Definition at line 49 of file utils.py.
GLOBAL_OPTION_NAMES
pylint.utils.utils.GLOBAL_OPTION_NAMES
Initial value:
=  Union[
    GLOBAL_OPTION_BOOL,
    GLOBAL_OPTION_INT,
    GLOBAL_OPTION_LIST,
    GLOBAL_OPTION_PATTERN,
    GLOBAL_OPTION_PATTERN_LIST,
    GLOBAL_OPTION_TUPLE_INT,
]
Definition at line 58 of file utils.py.
GLOBAL_OPTION_PATTERN
pylint.utils.utils.GLOBAL_OPTION_PATTERN
Initial value:
=  Literal[
    "no-docstring-rgx",
    "dummy-variables-rgx",
    "ignored-argument-names",
    "mixin-class-rgx",
]
Definition at line 50 of file utils.py.
GLOBAL_OPTION_PATTERN_LIST
pylint.utils.utils.GLOBAL_OPTION_PATTERN_LIST = Literal["exclude-too-few-public-methods", "ignore-paths"]
Definition at line 56 of file utils.py.
GLOBAL_OPTION_TUPLE_INT
pylint.utils.utils.GLOBAL_OPTION_TUPLE_INT = Literal["py-version"]
Definition at line 57 of file utils.py.
HAS_ISORT_5
bool pylint.utils.utils.HAS_ISORT_5 = True
Definition at line 11 of file utils.py.
T_GlobalOptionReturnTypes
pylint.utils.utils.T_GlobalOptionReturnTypes
Initial value:
=  TypeVar(
    "T_GlobalOptionReturnTypes",
    bool,
    int,
    list[str],
    Pattern[str],
    list[Pattern[str]],
    tuple[int, ...],
)
Definition at line 66 of file utils.py.