Read&Watch: django.db.transaction Namespace Reference
django.db.transaction Namespace Reference
Classes
class Atomic
Decorators / context managers #.
class TransactionManagementError
Functions
get_connection (using=None)
get_autocommit (using=None)
set_autocommit (autocommit, using=None)
commit (using=None)
rollback (using=None)
savepoint (using=None)
savepoint_rollback (sid, using=None)
savepoint_commit (sid, using=None)
clean_savepoints (using=None)
get_rollback (using=None)
set_rollback (rollback, using=None)
mark_for_rollback_on_error (using=None)
on_commit (func, using=None, robust=False)
atomic (using=None, savepoint=True, durable=False)
_non_atomic_requests (view, using)
non_atomic_requests (using=None)
Function Documentation
_non_atomic_requests()
django.db.transaction._non_atomic_requests (view, using) protected
Definition at line 326 of file transaction.py.
def _non_atomic_requests(view, using):
    try:
        view._non_atomic_requests.add(using)
    except AttributeError:
        view._non_atomic_requests = {using}
    return view
Referenced by non_atomic_requests().
atomic()
django.db.transaction.atomic (using = None, savepoint = True, durable = False)
Definition at line 316 of file transaction.py.
def atomic(using=None, savepoint=True, durable=False):
    # Bare decorator: @atomic -- although the first argument is called
    # `using`, it's actually the function being decorated.
    if callable(using):
        return Atomic(DEFAULT_DB_ALIAS, savepoint, durable)(using)
    # Decorator: @atomic(...) or context manager: with atomic(...): ...
    else:
        return Atomic(using, savepoint, durable)
clean_savepoints()
django.db.transaction.clean_savepoints (using = None)
Reset the counter used to generate unique savepoint ids in this thread.
Definition at line 73 of file transaction.py.
def clean_savepoints(using=None):
    """
    Reset the counter used to generate unique savepoint ids in this thread.
    """
    get_connection(using).clean_savepoints()
References clean_savepoints(), and get_connection().
Referenced by clean_savepoints().
commit()
django.db.transaction.commit (using = None)
Commit a transaction.
Definition at line 38 of file transaction.py.
def commit(using=None):
    """Commit a transaction."""
    get_connection(using).commit()
References commit(), and get_connection().
Referenced by commit().
get_autocommit()
django.db.transaction.get_autocommit (using = None)
Get the autocommit status of the connection.
Definition at line 28 of file transaction.py.
def get_autocommit(using=None):
    """Get the autocommit status of the connection."""
    return get_connection(using).get_autocommit()
References get_autocommit(), and get_connection().
Referenced by get_autocommit().
get_connection()
django.db.transaction.get_connection (using = None)
Get a database connection by name, or the default database connection
if no name is provided. This is a private API.
Definition at line 18 of file transaction.py.
def get_connection(using=None):
    """
    Get a database connection by name, or the default database connection
    if no name is provided. This is a private API.
    """
    if using is None:
        using = DEFAULT_DB_ALIAS
    return connections[using]
Referenced by django.db.transaction.Atomic.__enter__(), django.db.transaction.Atomic.__exit__(), clean_savepoints(), commit(), get_autocommit(), get_rollback(), mark_for_rollback_on_error(), on_commit(), rollback(), savepoint(), savepoint_commit(), savepoint_rollback(), set_autocommit(), and set_rollback().
get_rollback()
django.db.transaction.get_rollback (using = None)
Get the "needs rollback" flag -- for *advanced use* only.
Definition at line 80 of file transaction.py.
def get_rollback(using=None):
    """Get the "needs rollback" flag -- for *advanced use* only."""
    return get_connection(using).get_rollback()
References get_connection(), and get_rollback().
Referenced by get_rollback().
mark_for_rollback_on_error()
django.db.transaction.mark_for_rollback_on_error (using = None)
Internal low-level utility to mark a transaction as "needs rollback" when
an exception is raised while not enforcing the enclosed block to be in a
transaction. This is needed by Model.save() and friends to avoid starting a
transaction when in autocommit mode and a single query is executed.
It's equivalent to:
    connection = get_connection(using)
    if connection.get_autocommit():
        yield
    else:
        with transaction.atomic(using=using, savepoint=False):
            yield
but it uses low-level utilities to avoid performance overhead.
Definition at line 101 of file transaction.py.
def mark_for_rollback_on_error(using=None):
    """
    Internal low-level utility to mark a transaction as "needs rollback" when
    an exception is raised while not enforcing the enclosed block to be in a
    transaction. This is needed by Model.save() and friends to avoid starting a
    transaction when in autocommit mode and a single query is executed.
    It's equivalent to:
        connection = get_connection(using)
        if connection.get_autocommit():
            yield
        else:
            with transaction.atomic(using=using, savepoint=False):
                yield
    but it uses low-level utilities to avoid performance overhead.
    """
    try:
        yield
    except Exception as exc:
        connection = get_connection(using)
        if connection.in_atomic_block:
            connection.needs_rollback = True
            connection.rollback_exc = exc
        raise
References get_connection().
non_atomic_requests()
django.db.transaction.non_atomic_requests (using = None)
Definition at line 334 of file transaction.py.
def non_atomic_requests(using=None):
    if callable(using):
        return _non_atomic_requests(using, DEFAULT_DB_ALIAS)
    else:
        if using is None:
            using = DEFAULT_DB_ALIAS
        return lambda view: _non_atomic_requests(view, using)
References _non_atomic_requests().
on_commit()
django.db.transaction.on_commit (func, using = None, robust = False)
Register `func` to be called when the current transaction is committed.
If the current transaction is rolled back, `func` will not be called.
Definition at line 129 of file transaction.py.
def on_commit(func, using=None, robust=False):
    """
    Register `func` to be called when the current transaction is committed.
    If the current transaction is rolled back, `func` will not be called.
    """
    get_connection(using).on_commit(func, robust)
References get_connection(), and on_commit().
Referenced by on_commit().
rollback()
django.db.transaction.rollback (using = None)
Roll back a transaction.
Definition at line 43 of file transaction.py.
def rollback(using=None):
    """Roll back a transaction."""
    get_connection(using).rollback()
References get_connection(), and rollback().
Referenced by rollback().
savepoint()
django.db.transaction.savepoint (using = None)
Create a savepoint (if supported and required by the backend) inside the
current transaction. Return an identifier for the savepoint that will be
used for the subsequent rollback or commit.
Definition at line 48 of file transaction.py.
def savepoint(using=None):
    """
    Create a savepoint (if supported and required by the backend) inside the
    current transaction. Return an identifier for the savepoint that will be
    used for the subsequent rollback or commit.
    """
    return get_connection(using).savepoint()
References get_connection(), and savepoint().
Referenced by savepoint().
savepoint_commit()
django.db.transaction.savepoint_commit (sid, using = None)
Commit the most recent savepoint (if one exists). Do nothing if
savepoints are not supported.
Definition at line 65 of file transaction.py.
def savepoint_commit(sid, using=None):
    """
    Commit the most recent savepoint (if one exists). Do nothing if
    savepoints are not supported.
    """
    get_connection(using).savepoint_commit(sid)
References get_connection(), and savepoint_commit().
Referenced by savepoint_commit().
savepoint_rollback()
django.db.transaction.savepoint_rollback (sid, using = None)
Roll back the most recent savepoint (if one exists). Do nothing if
savepoints are not supported.
Definition at line 57 of file transaction.py.
def savepoint_rollback(sid, using=None):
    """
    Roll back the most recent savepoint (if one exists). Do nothing if
    savepoints are not supported.
    """
    get_connection(using).savepoint_rollback(sid)
References get_connection(), and savepoint_rollback().
Referenced by savepoint_rollback().
set_autocommit()
django.db.transaction.set_autocommit (autocommit, using = None)
Set the autocommit status of the connection.
Definition at line 33 of file transaction.py.
def set_autocommit(autocommit, using=None):
    """Set the autocommit status of the connection."""
    return get_connection(using).set_autocommit(autocommit)
References get_connection(), and set_autocommit().
Referenced by set_autocommit().
set_rollback()
django.db.transaction.set_rollback (rollback, using = None)
Set or unset the "needs rollback" flag -- for *advanced use* only.
When `rollback` is `True`, trigger a rollback when exiting the innermost
enclosing atomic block that has `savepoint=True` (that's the default). Use
this to force a rollback without raising an exception.
When `rollback` is `False`, prevent such a rollback. Use this only after
rolling back to a known-good state! Otherwise, you break the atomic block
and data corruption may occur.
Definition at line 85 of file transaction.py.
def set_rollback(rollback, using=None):
    """
    Set or unset the "needs rollback" flag -- for *advanced use* only.
    When `rollback` is `True`, trigger a rollback when exiting the innermost
    enclosing atomic block that has `savepoint=True` (that's the default). Use
    this to force a rollback without raising an exception.
    When `rollback` is `False`, prevent such a rollback. Use this only after
    rolling back to a known-good state! Otherwise, you break the atomic block
    and data corruption may occur.
    """
    return get_connection(using).set_rollback(rollback)
@contextmanager
References get_connection(), and set_rollback().
Referenced by set_rollback().