Read&Watch: responses Namespace Reference
responses Namespace Reference
Namespaces
namespace _recorder
namespace matchers
namespace registries
Classes
class BaseResponse
class Call
class CallbackResponse
class CallList
class FalseBool
class PassthroughResponse
class RequestsMock
class Response
class UnboundSend
Functions
Callable[..., Any] urlencoded_params_matcher (Optional[Dict[str, str]] params)
Callable[..., Any] json_params_matcher (Optional[Dict[str, Any]] params)
bool _has_unicode (str s)
str _clean_unicode (str url)
Callable[..., Any] get_wrapped (Callable[..., Any] func, "RequestsMock" responses, *, Optional[Any] registry=None, Optional[bool] assert_all_requests_are_fired=None)
"_URLPatternType" _ensure_url_default_path ("_URLPatternType" url)
str _get_url_and_path (str url)
Union[BufferedReader, BytesIO] _handle_body (Optional[Union[bytes, BufferedReader, str]] body)
HTTPResponse _form_response (Union[BufferedReader, BytesIO] body, Optional[Mapping[str, str]] headers, int status, Optional[str] request_method)
Any __getattr__ (str name)
Variables
_Body = Union[str, BaseException, "Response", BufferedReader, bytes, None]
_F = Callable[..., Any]
_HeaderSet = Optional[Union[Mapping[str, str], List[Tuple[str, str]]]]
_MatcherIterable = Iterable[Callable[..., Tuple[bool, str]]]
_HTTPMethodOrResponse = Optional[Union[str, "BaseResponse"]]
_URLPatternType = Union["Pattern[str]", str]
_HTTPAdapterSend
_real_send = HTTPAdapter.send
_UNSET = object()
logger = logging.getLogger("responses")
mock = RequestsMock(assert_all_requests_are_fired=False)
activate = _default_mock.activate
add = _default_mock.add
_add_from_file = _default_mock._add_from_file
add_callback = _default_mock.add_callback
add_passthru = _default_mock.add_passthru
_deprecated_assert_all_requests_are_fired = _default_mock.assert_all_requests_are_fired
assert_call_count = _default_mock.assert_call_count
calls = _default_mock.calls
delete = _default_mock.delete
DELETE = _default_mock.DELETE
get = _default_mock.get
GET = _default_mock.GET
head = _default_mock.head
HEAD = _default_mock.HEAD
options = _default_mock.options
OPTIONS = _default_mock.OPTIONS
_deprecated_passthru_prefixes = _default_mock.passthru_prefixes
patch = _default_mock.patch
PATCH = _default_mock.PATCH
post = _default_mock.post
POST = _default_mock.POST
put = _default_mock.put
PUT = _default_mock.PUT
registered = _default_mock.registered
remove = _default_mock.remove
replace = _default_mock.replace
reset = _default_mock.reset
response_callback = _default_mock.response_callback
start = _default_mock.start
stop = _default_mock.stop
_deprecated_target = _default_mock.target
upsert = _default_mock.upsert
list deprecated_names = ["assert_all_requests_are_fired", "passthru_prefixes", "target"]
Function Documentation
__getattr__()
Any responses.__getattr__ (str name)
Definition at line 1334 of file __init__.py.
def __getattr__(name: str) -> Any:
    if name in deprecated_names:
        warn(
            f"{name} is deprecated. Please use 'responses.mock.{name}",
            DeprecationWarning,
        )
        return globals()[f"_deprecated_{name}"]
    raise AttributeError(f"module {__name__} has no attribute {name}")
_clean_unicode()
str responses._clean_unicode (str url) protected
Clean up URLs, which use punycode to handle unicode chars.
Applies percent encoding to URL path and query if required.
Parameters
----------
url : str
    URL that should be cleaned from unicode
Returns
-------
str
    Cleaned URL
Definition at line 140 of file __init__.py.
def _clean_unicode(url: str) -> str:
    """Clean up URLs, which use punycode to handle unicode chars.
    Applies percent encoding to URL path and query if required.
    Parameters
    ----------
    url : str
        URL that should be cleaned from unicode
    Returns
    -------
    str
        Cleaned URL
    """
    urllist = list(urlsplit(url))
    netloc = urllist[1]
    if _has_unicode(netloc):
        domains = netloc.split(".")
        for i, d in enumerate(domains):
            if _has_unicode(d):
                d = "xn--" + d.encode("punycode").decode("ascii")
                domains[i] = d
        urllist[1] = ".".join(domains)
        url = urlunsplit(urllist)
    # Clean up path/query/params, which use url-encoding to handle unicode chars
    chars = list(url)
    for i, x in enumerate(chars):
        if ord(x) > 128:
            chars[i] = quote(x)
    return "".join(chars)
References _has_unicode().
Referenced by responses.BaseResponse._url_matches(), and responses.RequestsMock.add_passthru().
_ensure_url_default_path()
"_URLPatternType" responses._ensure_url_default_path ("_URLPatternType" url) protected
Add empty URL path '/' if doesn't exist.
Examples
--------
>>> _ensure_url_default_path("http://example.com")
"http://example.com/"
Parameters
----------
url : str or re.Pattern
    URL to validate.
Returns
-------
url : str or re.Pattern
    Modified URL if str or unchanged re.Pattern
Definition at line 268 of file __init__.py.
) -> "_URLPatternType":
    """Add empty URL path '/' if doesn't exist.
    Examples
    --------
    >>> _ensure_url_default_path("http://example.com")
    "http://example.com/"
    Parameters
    ----------
    url : str or re.Pattern
        URL to validate.
    Returns
    -------
    url : str or re.Pattern
        Modified URL if str or unchanged re.Pattern
    """
    if isinstance(url, str):
        url_parts = list(urlsplit(url))
        if url_parts[2] == "":
            url_parts[2] = "/"
            url = urlunsplit(url_parts)
    return url
Referenced by responses.RequestsMock.assert_call_count().
_form_response()
HTTPResponse responses._form_response (Union[BufferedReader, BytesIO] body, Optional[Mapping[str, str]] headers, int status, Optional[str] request_method) protected
Function to generate `urllib3.response.HTTPResponse` object.
The cookie handling functionality of the `requests` library relies on the response object
having an original response object with the headers stored in the `msg` attribute.
Instead of supplying a file-like object of type `HTTPMessage` for the headers, we provide
the headers directly. This approach eliminates the need to parse the headers into a file-like
object and then rely on the library to unparse it back. These additional conversions can
introduce potential errors.
Definition at line 531 of file __init__.py.
) -> HTTPResponse:
    """
    Function to generate `urllib3.response.HTTPResponse` object.
    The cookie handling functionality of the `requests` library relies on the response object
    having an original response object with the headers stored in the `msg` attribute.
    Instead of supplying a file-like object of type `HTTPMessage` for the headers, we provide
    the headers directly. This approach eliminates the need to parse the headers into a file-like
    object and then rely on the library to unparse it back. These additional conversions can
    introduce potential errors.
    """
    data = BytesIO()
    data.close()
    """
    The type `urllib3.response.HTTPResponse` is incorrect; we should
    use `http.client.HTTPResponse` instead. However, changing this requires opening
    a real socket to imitate the object. This may not be desired, as some users may
    want to completely restrict network access in their tests.
    See https://github.com/getsentry/responses/issues/691
    """
    orig_response = HTTPResponse(
        body=data,  # required to avoid "ValueError: Unable to determine whether fp is closed."
        msg=headers,  # type: ignore[arg-type]
        preload_content=False,
    )
    return HTTPResponse(
        status=status,
        reason=client.responses.get(status, None),
        body=body,
        headers=headers,
        original_response=orig_response,  # type: ignore[arg-type]  # See comment above
        preload_content=False,
        request_method=request_method,
    )
Referenced by responses.CallbackResponse.get_response(), and responses.Response.get_response().
_get_url_and_path()
str responses._get_url_and_path (str url) protected
Construct URL only containing scheme, netloc and path by truncating other parts.
This method complies with RFC 3986.
Examples
--------
>>> _get_url_and_path("http://example.com/path;segment?ab=xy&zed=qwe#test=1&foo=bar")
"http://example.com/path;segment"
Parameters
----------
url : str
    URL to parse.
Returns
-------
url : str
    URL with scheme, netloc and path
Definition at line 297 of file __init__.py.
def _get_url_and_path(url: str) -> str:
    """Construct URL only containing scheme, netloc and path by truncating other parts.
    This method complies with RFC 3986.
    Examples
    --------
    >>> _get_url_and_path("http://example.com/path;segment?ab=xy&zed=qwe#test=1&foo=bar")
    "http://example.com/path;segment"
    Parameters
    ----------
    url : str
        URL to parse.
    Returns
    -------
    url : str
        URL with scheme, netloc and path
    """
    url_parsed = urlsplit(url)
    url_and_path = urlunparse(
        [url_parsed.scheme, url_parsed.netloc, url_parsed.path, None, None, None]
    )
    return parse_url(url_and_path).url
Referenced by responses.BaseResponse._url_matches().
_handle_body()
Union[BufferedReader, BytesIO] responses._handle_body (Optional[Union[bytes, BufferedReader, str]] body) protected
Generates `Response` body.
Parameters
----------
body : str or bytes or BufferedReader
    Input data to generate `Response` body.
Returns
-------
body : BufferedReader or BytesIO
    `Response` body
Definition at line 326 of file __init__.py.
) -> Union[BufferedReader, BytesIO]:
    """Generates `Response` body.
    Parameters
    ----------
    body : str or bytes or BufferedReader
        Input data to generate `Response` body.
    Returns
    -------
    body : BufferedReader or BytesIO
        `Response` body
    """
    if isinstance(body, str):
        body = body.encode("utf-8")
    if isinstance(body, BufferedReader):
        return body
    data = BytesIO(body)  # type: ignore[arg-type]
    def is_closed() -> bool:
        """
        Real Response uses HTTPResponse as body object.
        Thus, when method is_closed is called first to check if there is any more
        content to consume and the file-like object is still opened
        This method ensures stability to work for both:
        https://github.com/getsentry/responses/issues/438
        https://github.com/getsentry/responses/issues/394
        where file should be intentionally be left opened to continue consumption
        """
        if not data.closed and data.read(1):
            # if there is more bytes to read then keep open, but return pointer
            data.seek(-1, 1)
            return False
        else:
            if not data.closed:
                # close but return False to mock like is still opened
                data.close()
                return False
            # only if file really closed (by us) return True
            return True
    data.isclosed = is_closed  # type: ignore[attr-defined]
    return data
Referenced by responses.CallbackResponse.get_response(), and responses.Response.get_response().
_has_unicode()
bool responses._has_unicode (str s) protected
Definition at line 136 of file __init__.py.
def _has_unicode(s: str) -> bool:
    return any(ord(char) > 128 for char in s)
Referenced by responses.Response.__init__(), _clean_unicode(), responses.BaseResponse._url_matches(), and responses.RequestsMock.add_passthru().
get_wrapped()
Callable[..., Any] responses.get_wrapped (Callable[..., Any] func, "RequestsMock" responses, * , Optional[Any] registry = None, Optional[bool] assert_all_requests_are_fired = None)
Wrap provided function inside ``responses`` context manager.
Provides a synchronous or asynchronous wrapper for the function.
Parameters
----------
func : Callable
    Function to wrap.
responses : RequestsMock
    Mock object that is used as context manager.
registry : FirstMatchRegistry, optional
    Custom registry that should be applied. See ``responses.registries``
assert_all_requests_are_fired : bool
    Raise an error if not all registered responses were executed.
Returns
-------
Callable
    Wrapped function
Definition at line 176 of file __init__.py.
) -> Callable[..., Any]:
    """Wrap provided function inside ``responses`` context manager.
    Provides a synchronous or asynchronous wrapper for the function.
    Parameters
    ----------
    func : Callable
        Function to wrap.
    responses : RequestsMock
        Mock object that is used as context manager.
    registry : FirstMatchRegistry, optional
        Custom registry that should be applied. See ``responses.registries``
    assert_all_requests_are_fired : bool
        Raise an error if not all registered responses were executed.
    Returns
    -------
    Callable
        Wrapped function
    """
    assert_mock = std_mock.patch.object(
        target=responses,
        attribute="assert_all_requests_are_fired",
        new=assert_all_requests_are_fired,
    )
    if inspect.iscoroutinefunction(func):
        # set asynchronous wrapper if requestor function is asynchronous
        @wraps(func)
        async def wrapper(*args: Any, **kwargs: Any) -> Any:  # type: ignore[misc]
            if registry is not None:
                responses._set_registry(registry)
            with assert_mock, responses:
                return await func(*args, **kwargs)
    else:
        @wraps(func)
        def wrapper(*args: Any, **kwargs: Any) -> Any:  # type: ignore[misc]
            if registry is not None:
                responses._set_registry(registry)
            with assert_mock, responses:
                # set 'assert_all_requests_are_fired' temporarily for a single run.
                # Mock automatically unsets to avoid leakage to another decorated
                # function since we still apply the value on 'responses.mock' object
                return func(*args, **kwargs)
    return wrapper
Referenced by responses.RequestsMock.activate().
json_params_matcher()
Callable[..., Any] responses.json_params_matcher (Optional[Dict[str, Any]] params)
Definition at line 128 of file __init__.py.
def json_params_matcher(params: Optional[Dict[str, Any]]) -> Callable[..., Any]:
    warn(
        "Function is deprecated. Use 'from responses.matchers import json_params_matcher'",
        DeprecationWarning,
    )
    return _json_params_matcher(params)
urlencoded_params_matcher()
Callable[..., Any] responses.urlencoded_params_matcher (Optional[Dict[str, str]] params)
Definition at line 120 of file __init__.py.
def urlencoded_params_matcher(params: Optional[Dict[str, str]]) -> Callable[..., Any]:
    warn(
        "Function is deprecated. Use 'from responses.matchers import urlencoded_params_matcher'",
        DeprecationWarning,
    )
    return _urlencoded_params_matcher(params)
Variable Documentation
_add_from_file
responses._add_from_file = _default_mock._add_from_file protected
Definition at line 1299 of file __init__.py.
_Body
responses._Body = Union[str, BaseException, "Response", BufferedReader, bytes, None] protected
Definition at line 78 of file __init__.py.
_deprecated_assert_all_requests_are_fired
responses._deprecated_assert_all_requests_are_fired = _default_mock.assert_all_requests_are_fired protected
Definition at line 1302 of file __init__.py.
_deprecated_passthru_prefixes
responses._deprecated_passthru_prefixes = _default_mock.passthru_prefixes protected
Definition at line 1313 of file __init__.py.
_deprecated_target
responses._deprecated_target = _default_mock.target protected
Definition at line 1327 of file __init__.py.
_F
responses._F = Callable[..., Any] protected
Definition at line 79 of file __init__.py.
_HeaderSet
responses._HeaderSet = Optional[Union[Mapping[str, str], List[Tuple[str, str]]]] protected
Definition at line 80 of file __init__.py.
_HTTPAdapterSend
responses._HTTPAdapterSend protected
Initial value:
=  Callable[
        [
            HTTPAdapter,
            PreparedRequest,
            bool,
            Union[float, Tuple[float, float], Tuple[float, None], None],
            Union[bool, str],
            Union[bytes, str, Tuple[Union[bytes, str], Union[bytes, str]], None],
            Optional[Mapping[str, str]],
        ],
        models.Response,
    ]
Definition at line 84 of file __init__.py.
_HTTPMethodOrResponse
responses._HTTPMethodOrResponse = Optional[Union[str, "BaseResponse"]] protected
Definition at line 82 of file __init__.py.
_MatcherIterable
responses._MatcherIterable = Iterable[Callable[..., Tuple[bool, str]]] protected
Definition at line 81 of file __init__.py.
_real_send
responses._real_send = HTTPAdapter.send protected
Definition at line 103 of file __init__.py.
_UNSET
responses._UNSET = object() protected
Definition at line 104 of file __init__.py.
_URLPatternType
responses._URLPatternType = Union["Pattern[str]", str] protected
Definition at line 83 of file __init__.py.
activate
responses.activate = _default_mock.activate
Definition at line 1297 of file __init__.py.
add
responses.add = _default_mock.add
Definition at line 1298 of file __init__.py.
Referenced by responses._recorder.Recorder._on_request(), responses.RequestsMock._on_request(), responses.RequestsMock.add(), responses.RequestsMock.add_callback(), and book.tests.BookSearchTest.test_search_books_successful_response().
add_callback
responses.add_callback = _default_mock.add_callback
Definition at line 1300 of file __init__.py.
add_passthru
responses.add_passthru = _default_mock.add_passthru
Definition at line 1301 of file __init__.py.
assert_call_count
responses.assert_call_count = _default_mock.assert_call_count
Definition at line 1303 of file __init__.py.
calls
responses.calls = _default_mock.calls
Definition at line 1304 of file __init__.py.
DELETE
responses.DELETE = _default_mock.DELETE
Definition at line 1306 of file __init__.py.
delete
responses.delete = _default_mock.delete
Definition at line 1305 of file __init__.py.
deprecated_names
list responses.deprecated_names = ["assert_all_requests_are_fired", "passthru_prefixes", "target"]
Definition at line 1331 of file __init__.py.
GET
responses.GET = _default_mock.GET
Definition at line 1308 of file __init__.py.
get
responses.get = _default_mock.get
Definition at line 1307 of file __init__.py.
Referenced by django.http.response.HttpResponseBase.reason_phrase().
HEAD
responses.HEAD = _default_mock.HEAD
Definition at line 1310 of file __init__.py.
head
responses.head = _default_mock.head
Definition at line 1309 of file __init__.py.
logger
responses.logger = logging.getLogger("responses")
Definition at line 106 of file __init__.py.
mock
responses.mock = RequestsMock(assert_all_requests_are_fired=False)
Definition at line 1256 of file __init__.py.
OPTIONS
responses.OPTIONS = _default_mock.OPTIONS
Definition at line 1312 of file __init__.py.
options
responses.options = _default_mock.options
Definition at line 1311 of file __init__.py.
PATCH
responses.PATCH = _default_mock.PATCH
Definition at line 1315 of file __init__.py.
patch
responses.patch = _default_mock.patch
Definition at line 1314 of file __init__.py.
POST
responses.POST = _default_mock.POST
Definition at line 1317 of file __init__.py.
post
responses.post = _default_mock.post
Definition at line 1316 of file __init__.py.
PUT
responses.PUT = _default_mock.PUT
Definition at line 1319 of file __init__.py.
put
responses.put = _default_mock.put
Definition at line 1318 of file __init__.py.
registered
responses.registered = _default_mock.registered
Definition at line 1320 of file __init__.py.
remove
responses.remove = _default_mock.remove
Definition at line 1321 of file __init__.py.
Referenced by responses.registries.FirstMatchRegistry.remove(), and responses.RequestsMock.remove().
replace
responses.replace = _default_mock.replace
Definition at line 1322 of file __init__.py.
Referenced by responses.matchers.multipart_matcher(), and responses.RequestsMock.replace().
reset
responses.reset = _default_mock.reset
Definition at line 1323 of file __init__.py.
Referenced by responses.RequestsMock.reset().
response_callback
responses.response_callback = _default_mock.response_callback
Definition at line 1324 of file __init__.py.
start
responses.start = _default_mock.start
Definition at line 1325 of file __init__.py.
Referenced by responses.RequestsMock.start().
stop
responses.stop = _default_mock.stop
Definition at line 1326 of file __init__.py.
Referenced by responses._recorder.Recorder.stop(), and responses.RequestsMock.stop().
upsert
responses.upsert = _default_mock.upsert
Definition at line 1328 of file __init__.py.