Read&Watch: astroid.brain.brain_io Namespace Reference
astroid.brain.brain_io Namespace Reference
Functions
_generic_io_transform (node, name, cls)
_transform_text_io_wrapper (node)
_transform_buffered (node)
None register (AstroidManager manager)
Variables
dict BUFFERED = {"BufferedWriter", "BufferedReader"}
str TextIOWrapper = "TextIOWrapper"
str FileIO = "FileIO"
str BufferedWriter = "BufferedWriter"
Detailed Description
Astroid brain hints for some of the _io C objects.
Function Documentation
_generic_io_transform()
astroid.brain.brain_io._generic_io_transform (node, name, cls) protected
Transform the given name, by adding the given *class* as a member of the
node.
Definition at line 15 of file brain_io.py.
def _generic_io_transform(node, name, cls):
    """Transform the given name, by adding the given *class* as a member of the
    node.
    """
    io_module = AstroidManager().ast_from_module_name("_io")
    attribute_object = io_module[cls]
    instance = attribute_object.instantiate_class()
    node.locals[name] = [instance]
Referenced by _transform_buffered(), and _transform_text_io_wrapper().
_transform_buffered()
astroid.brain.brain_io._transform_buffered (node) protected
Definition at line 34 of file brain_io.py.
def _transform_buffered(node):
    return _generic_io_transform(node, name="raw", cls=FileIO)
References _generic_io_transform().
_transform_text_io_wrapper()
astroid.brain.brain_io._transform_text_io_wrapper (node) protected
Definition at line 26 of file brain_io.py.
def _transform_text_io_wrapper(node):
    # This is not always correct, since it can vary with the type of the descriptor,
    # being stdout, stderr or stdin. But we cannot get access to the name of the
    # stream, which is why we are using the BufferedWriter class as a default
    # value
    return _generic_io_transform(node, name="buffer", cls=BufferedWriter)
References _generic_io_transform().
register()
None astroid.brain.brain_io.register (AstroidManager manager)
Definition at line 38 of file brain_io.py.
def register(manager: AstroidManager) -> None:
    manager.register_transform(
        ClassDef, _transform_buffered, lambda node: node.name in BUFFERED
    )
    manager.register_transform(
        ClassDef, _transform_text_io_wrapper, lambda node: node.name == TextIOWrapper
    )
Variable Documentation
BUFFERED
dict astroid.brain.brain_io.BUFFERED = {"BufferedWriter", "BufferedReader"}
Definition at line 9 of file brain_io.py.
BufferedWriter
str astroid.brain.brain_io.BufferedWriter = "BufferedWriter"
Definition at line 12 of file brain_io.py.
FileIO
str astroid.brain.brain_io.FileIO = "FileIO"
Definition at line 11 of file brain_io.py.
TextIOWrapper
str astroid.brain.brain_io.TextIOWrapper = "TextIOWrapper"
Definition at line 10 of file brain_io.py.