Read&Watch: pylint.checkers.base.name_checker.checker Namespace Reference
pylint.checkers.base.name_checker.checker Namespace Reference
Classes
class NameChecker
class TypeVarVariance
Functions
tuple[set[str], set[str]] _get_properties (argparse.Namespace config)
bool _redefines_import (nodes.AssignName node)
str _determine_function_name_type (nodes.FunctionDef node, argparse.Namespace config)
bool _is_multi_naming_match (re.Match[str]|None match, str node_type, interfaces.Confidence confidence)
Variables
_BadNamesTuple = tuple[nodes.NodeNG, str, str, interfaces.Confidence]
dict DEFAULT_PATTERNS
str BUILTIN_PROPERTY = "builtins.property"
TYPE_VAR_QNAME
dict EXEMPT_NAME_CATEGORIES = {"exempt", "ignore"}
Detailed Description
Basic checker for Python code.
Function Documentation
_determine_function_name_type()
str pylint.checkers.base.name_checker.checker._determine_function_name_type (nodes.FunctionDef node, argparse.Namespace config) protected
Determine the name type whose regex the function's name should match.
:param node: A function node.
:param config: Configuration from which to pull additional property classes.
:returns: One of ('function', 'method', 'attr')
Definition at line 104 of file checker.py.
) -> str:
    """Determine the name type whose regex the function's name should match.
    :param node: A function node.
    :param config: Configuration from which to pull additional property classes.
    :returns: One of ('function', 'method', 'attr')
    """
    property_classes, property_names = _get_properties(config)
    if not node.is_method():
        return "function"
    if is_property_setter(node) or is_property_deleter(node):
        # If the function is decorated using the prop_method.{setter,getter}
        # form, treat it like an attribute as well.
        return "attr"
    decorators = node.decorators.nodes if node.decorators else []
    for decorator in decorators:
        # If the function is a property (decorated with @property
        # or @abc.abstractproperty), the name type is 'attr'.
        if isinstance(decorator, nodes.Name) or (
            isinstance(decorator, nodes.Attribute)
            and decorator.attrname in property_names
        ):
            inferred = utils.safe_infer(decorator)
            if (
                inferred
                and hasattr(inferred, "qname")
                and inferred.qname() in property_classes
            ):
                return "attr"
    return "method"
# Name categories that are always consistent with all naming conventions.
References _get_properties().
Referenced by pylint.checkers.base.name_checker.checker.NameChecker.visit_functiondef().
_get_properties()
tuple[set[str], set[str]] pylint.checkers.base.name_checker.checker._get_properties (argparse.Namespace config) protected
Returns a tuple of property classes and names.
Property classes are fully qualified, such as 'abc.abstractproperty' and
property names are the actual names, such as 'abstract_property'.
Definition at line 66 of file checker.py.
def _get_properties(config: argparse.Namespace) -> tuple[set[str], set[str]]:
    """Returns a tuple of property classes and names.
    Property classes are fully qualified, such as 'abc.abstractproperty' and
    property names are the actual names, such as 'abstract_property'.
    """
    property_classes = {BUILTIN_PROPERTY}
    property_names: set[str] = set()  # Not returning 'property', it has its own check.
    if config is not None:
        property_classes.update(config.property_classes)
        property_names.update(
            prop.rsplit(".", 1)[-1] for prop in config.property_classes
        )
    return property_classes, property_names
Referenced by _determine_function_name_type().
_is_multi_naming_match()
bool pylint.checkers.base.name_checker.checker._is_multi_naming_match (re.Match[str] | None match, str node_type, interfaces.Confidence confidence) protected
Definition at line 145 of file checker.py.
) -> bool:
    return (
        match is not None
        and match.lastgroup is not None
        and match.lastgroup not in EXEMPT_NAME_CATEGORIES
        and (node_type != "method" or confidence != interfaces.INFERENCE_FAILURE)
    )
Referenced by pylint.checkers.base.name_checker.checker.NameChecker._check_name().
_redefines_import()
bool pylint.checkers.base.name_checker.checker._redefines_import (nodes.AssignName node) protected
Detect that the given node (AssignName) is inside an
exception handler and redefines an import from the tryexcept body.
Returns True if the node redefines an import, False otherwise.
Definition at line 82 of file checker.py.
def _redefines_import(node: nodes.AssignName) -> bool:
    """Detect that the given node (AssignName) is inside an
    exception handler and redefines an import from the tryexcept body.
    Returns True if the node redefines an import, False otherwise.
    """
    current = node
    while current and not isinstance(current.parent, nodes.ExceptHandler):
        current = current.parent
    if not current or not utils.error_of_type(current.parent, ImportError):
        return False
    try_block = current.parent.parent
    for import_node in try_block.nodes_of_class((nodes.ImportFrom, nodes.Import)):
        for name, alias in import_node.names:
            if alias:
                if alias == node.name:
                    return True
            elif name == node.name:
                return True
    return False
Referenced by pylint.checkers.base.name_checker.checker.NameChecker.visit_assignname().
Variable Documentation
_BadNamesTuple
pylint.checkers.base.name_checker.checker._BadNamesTuple = tuple[nodes.NodeNG, str, str, interfaces.Confidence] protected
Definition at line 37 of file checker.py.
BUILTIN_PROPERTY
str pylint.checkers.base.name_checker.checker.BUILTIN_PROPERTY = "builtins.property"
Definition at line 49 of file checker.py.
DEFAULT_PATTERNS
dict pylint.checkers.base.name_checker.checker.DEFAULT_PATTERNS
Initial value:
=  {
    "typevar": re.compile(
        r"^_{0,2}(?!T[A-Z])(?:[A-Z]+|(?:[A-Z]+[a-z]+)+T?(?<!Type))(?:_co(?:ntra)?)?$"
    ),
    "typealias": re.compile(
        r"^_{0,2}(?!T[A-Z]|Type)[A-Z]+[a-z0-9]+(?:[A-Z][a-z0-9]+)*$"
    ),
}
Definition at line 40 of file checker.py.
EXEMPT_NAME_CATEGORIES
dict pylint.checkers.base.name_checker.checker.EXEMPT_NAME_CATEGORIES = {"exempt", "ignore"}
Definition at line 142 of file checker.py.
TYPE_VAR_QNAME
pylint.checkers.base.name_checker.checker.TYPE_VAR_QNAME
Initial value:
=  frozenset(
    (
        "typing.TypeVar",
        "typing_extensions.TypeVar",
    )
)
Definition at line 50 of file checker.py.