Read&Watch: pylint.config._pylint_config.utils Namespace Reference
pylint.config._pylint_config.utils Namespace Reference
Classes
class InvalidUserInput
Functions
Callable[_P, _ReturnValueT] should_retry_after_invalid_input (Callable[_P, _ReturnValueT] func)
Literal["toml", "ini"] get_and_validate_format ()
bool validate_yes_no (str question, Literal["yes", "no"]|None default)
bool get_minimal_setting ()
tuple[bool, Path] get_and_validate_output_file ()
Variables
_P = ParamSpec("_P")
_ReturnValueT = TypeVar("_ReturnValueT", bool, str)
dict SUPPORTED_FORMATS = {"t", "toml", "i", "ini"}
dict YES_NO_ANSWERS = {"y", "yes", "n", "no"}
Detailed Description
Utils for the 'pylint-config' command.
Function Documentation
get_and_validate_format()
Literal["toml", "ini"] pylint.config._pylint_config.utils.get_and_validate_format ()
Make sure that the output format is either .toml or .ini.
Definition at line 57 of file utils.py.
def get_and_validate_format() -> Literal["toml", "ini"]:
    """Make sure that the output format is either .toml or .ini."""
    # pylint: disable-next=bad-builtin
    format_type = input(
        "Please choose the format of configuration, (T)oml or (I)ni (.cfg): "
    ).lower()
    if format_type not in SUPPORTED_FORMATS:
        raise InvalidUserInput(", ".join(sorted(SUPPORTED_FORMATS)), format_type)
    if format_type.startswith("t"):
        return "toml"
    return "ini"
@should_retry_after_invalid_input
get_and_validate_output_file()
tuple[bool, Path] pylint.config._pylint_config.utils.get_and_validate_output_file ()
Make sure that the output file is correct.
Definition at line 97 of file utils.py.
def get_and_validate_output_file() -> tuple[bool, Path]:
    """Make sure that the output file is correct."""
    to_file = validate_yes_no("Do you want to write the output to a file?", "no")
    if not to_file:
        return False, Path()
    # pylint: disable-next=bad-builtin
    file_name = Path(input("What should the file be called: "))
    if file_name.exists():
        overwrite = validate_yes_no(
            f"{file_name} already exists. Are you sure you want to overwrite?", "no"
        )
        if not overwrite:
            return False, file_name
        return True, file_name
    return True, file_name
References validate_yes_no().
get_minimal_setting()
bool pylint.config._pylint_config.utils.get_minimal_setting ()
Ask the user if they want to use the minimal setting.
Definition at line 90 of file utils.py.
def get_minimal_setting() -> bool:
    """Ask the user if they want to use the minimal setting."""
    return validate_yes_no(
        "Do you want a minimal configuration without comments or default values?", "no"
    )
References validate_yes_no().
should_retry_after_invalid_input()
Callable[_P, _ReturnValueT] pylint.config._pylint_config.utils.should_retry_after_invalid_input (Callable[_P, _ReturnValueT] func)
Decorator that handles InvalidUserInput exceptions and retries.
Definition at line 35 of file utils.py.
) -> Callable[_P, _ReturnValueT]:
    """Decorator that handles InvalidUserInput exceptions and retries."""
    def inner_function(*args: _P.args, **kwargs: _P.kwargs) -> _ReturnValueT:
        called_once = False
        while True:
            try:
                return func(*args, **kwargs)
            except InvalidUserInput as exc:
                if called_once and exc.input == "exit()":
                    print("Stopping 'pylint-config'.")
                    sys.exit()
                print(f"Answer should be one of {exc.valid}.")
                print("Type 'exit()' if you want to exit the program.")
                called_once = True
    return inner_function
@should_retry_after_invalid_input
validate_yes_no()
bool pylint.config._pylint_config.utils.validate_yes_no (str question, Literal["yes", "no"] | None default)
Validate that a yes or no answer is correct.
Definition at line 73 of file utils.py.
def validate_yes_no(question: str, default: Literal["yes", "no"] | None) -> bool:
    """Validate that a yes or no answer is correct."""
    question = f"{question} (y)es or (n)o "
    if default:
        question += f" (default={default}) "
    # pylint: disable-next=bad-builtin
    answer = input(question).lower()
    if not answer and default:
        answer = default
    if answer not in YES_NO_ANSWERS:
        raise InvalidUserInput(", ".join(sorted(YES_NO_ANSWERS)), answer)
    return answer.startswith("y")
Referenced by get_and_validate_output_file(), and get_minimal_setting().
Variable Documentation
_P
pylint.config._pylint_config.utils._P = ParamSpec("_P") protected
Definition at line 19 of file utils.py.
_ReturnValueT
pylint.config._pylint_config.utils._ReturnValueT = TypeVar("_ReturnValueT", bool, str) protected
Definition at line 20 of file utils.py.
SUPPORTED_FORMATS
dict pylint.config._pylint_config.utils.SUPPORTED_FORMATS = {"t", "toml", "i", "ini"}
Definition at line 22 of file utils.py.
YES_NO_ANSWERS
dict pylint.config._pylint_config.utils.YES_NO_ANSWERS = {"y", "yes", "n", "no"}
Definition at line 23 of file utils.py.