Read&Watch: PIL.ImageFile Namespace Reference
PIL.ImageFile Namespace Reference
Classes
class _Tile
class ImageFile
class Parser
class PyCodec
class PyCodecState
class PyDecoder
class PyEncoder
class StubHandler
class StubImageFile
Functions
OSError _get_oserror (int error, *, bool encoder)
OSError raise_oserror (int error)
int _tilesort (_Tile t)
None _save (Image.Image im, IO[bytes] fp, list[_Tile] tile, int bufsize=0)
None _encode_tile (Image.Image im, IO[bytes] fp, list[_Tile] tile, int bufsize, int|None fh, BaseException|None exc=None)
bytes _safe_read (IO[bytes] fp, int size)
Variables
int MAXBLOCK = 65536
int SAFEBLOCK = 1024 * 1024
bool LOAD_TRUNCATED_IMAGES = False
dict ERRORS
Function Documentation
_encode_tile()
None PIL.ImageFile._encode_tile (Image.Image im, IO[bytes] fp, list[_Tile] tile, int bufsize, int | None fh, BaseException | None exc = None) protected
Definition at line 563 of file ImageFile.py.
) -> None:
    for encoder_name, extents, offset, args in tile:
        if offset > 0:
            fp.seek(offset)
        encoder = Image._getencoder(im.mode, encoder_name, args, im.encoderconfig)
        try:
            encoder.setimage(im.im, extents)
            if encoder.pushes_fd:
                encoder.setfd(fp)
                errcode = encoder.encode_to_pyfd()[1]
            else:
                if exc:
                    # compress to Python file-compatible object
                    while True:
                        errcode, data = encoder.encode(bufsize)[1:]
                        fp.write(data)
                        if errcode:
                            break
                else:
                    # slight speedup: compress to real file object
                    assert fh is not None
                    errcode = encoder.encode_to_file(fh, bufsize)
            if errcode < 0:
                raise _get_oserror(errcode, encoder=True) from exc
        finally:
            encoder.cleanup()
References _get_oserror().
Referenced by _save().
_get_oserror()
OSError PIL.ImageFile._get_oserror (int error, * , bool encoder) protected
Definition at line 72 of file ImageFile.py.
def _get_oserror(error: int, *, encoder: bool) -> OSError:
    try:
        msg = Image.core.getcodecstatus(error)
    except AttributeError:
        msg = ERRORS.get(error)
    if not msg:
        msg = f"{'encoder' if encoder else 'decoder'} error {error}"
    msg += f" when {'writing' if encoder else 'reading'} image file"
    return OSError(msg)
Referenced by _encode_tile(), PIL.ImageFile.Parser.feed(), and raise_oserror().
_safe_read()
bytes PIL.ImageFile._safe_read (IO[bytes] fp, int size) protected
Reads large blocks in a safe way.  Unlike fp.read(n), this function
doesn't trust the user.  If the requested size is larger than
SAFEBLOCK, the file is read block by block.
:param fp: File handle.  Must implement a <b>read</b> method.
:param size: Number of bytes to read.
:returns: A string containing <i>size</i> bytes of data.
Raises an OSError if the file is truncated and the read cannot be completed
Definition at line 598 of file ImageFile.py.
def _safe_read(fp: IO[bytes], size: int) -> bytes:
    """
    Reads large blocks in a safe way.  Unlike fp.read(n), this function
    doesn't trust the user.  If the requested size is larger than
    SAFEBLOCK, the file is read block by block.
    :param fp: File handle.  Must implement a <b>read</b> method.
    :param size: Number of bytes to read.
    :returns: A string containing <i>size</i> bytes of data.
    Raises an OSError if the file is truncated and the read cannot be completed
    """
    if size <= 0:
        return b""
    if size <= SAFEBLOCK:
        data = fp.read(size)
        if len(data) < size:
            msg = "Truncated File Read"
            raise OSError(msg)
        return data
    blocks: list[bytes] = []
    remaining_size = size
    while remaining_size > 0:
        block = fp.read(min(remaining_size, SAFEBLOCK))
        if not block:
            break
        blocks.append(block)
        remaining_size -= len(block)
    if sum(len(block) for block in blocks) < size:
        msg = "Truncated File Read"
        raise OSError(msg)
    return b"".join(blocks)
_save()
None PIL.ImageFile._save (Image.Image im, IO[bytes] fp, list[_Tile] tile, int bufsize = 0) protected
Helper to save image based on tile list
:param im: Image object.
:param fp: File object.
:param tile: Tile list.
:param bufsize: Optional buffer size
Definition at line 535 of file ImageFile.py.
def _save(im: Image.Image, fp: IO[bytes], tile: list[_Tile], bufsize: int = 0) -> None:
    """Helper to save image based on tile list
    :param im: Image object.
    :param fp: File object.
    :param tile: Tile list.
    :param bufsize: Optional buffer size
    """
    im.load()
    if not hasattr(im, "encoderconfig"):
        im.encoderconfig = ()
    tile.sort(key=_tilesort)
    # FIXME: make MAXBLOCK a configuration parameter
    # It would be great if we could have the encoder specify what it needs
    # But, it would need at least the image size in most cases. RawEncode is
    # a tricky case.
    bufsize = max(MAXBLOCK, bufsize, im.size[0] * 4)  # see RawEncode.c
    try:
        fh = fp.fileno()
        fp.flush()
        _encode_tile(im, fp, tile, bufsize, fh)
    except (AttributeError, io.UnsupportedOperation) as exc:
        _encode_tile(im, fp, tile, bufsize, None, exc)
    if hasattr(fp, "flush"):
        fp.flush()
References _encode_tile().
_tilesort()
int PIL.ImageFile._tilesort (_Tile t) protected
Definition at line 93 of file ImageFile.py.
def _tilesort(t: _Tile) -> int:
    # sort on offset
    return t[2]
raise_oserror()
OSError PIL.ImageFile.raise_oserror (int error)
Definition at line 83 of file ImageFile.py.
def raise_oserror(error: int) -> OSError:
    deprecate(
        "raise_oserror",
        12,
        action="It is only useful for translating error codes returned by a codec's "
        "decode() method, which ImageFile already does automatically.",
    )
    raise _get_oserror(error, encoder=False)
References _get_oserror().
Variable Documentation
ERRORS
dict PIL.ImageFile.ERRORS
Initial value:
=  {
    -1: "image buffer overrun error",
    -2: "decoding error",
    -3: "unknown error",
    -8: "bad configuration",
    -9: "out of memory error",
}
Definition at line 53 of file ImageFile.py.
LOAD_TRUNCATED_IMAGES
bool PIL.ImageFile.LOAD_TRUNCATED_IMAGES = False
Definition at line 50 of file ImageFile.py.
MAXBLOCK
int PIL.ImageFile.MAXBLOCK = 65536
Definition at line 46 of file ImageFile.py.
SAFEBLOCK
int PIL.ImageFile.SAFEBLOCK = 1024 * 1024
Definition at line 48 of file ImageFile.py.