Read&Watch: pylint.checkers.design_analysis Namespace Reference
pylint.checkers.design_analysis Namespace Reference
Classes
class MisdesignChecker
Functions
bool _is_exempt_from_public_methods (astroid.ClassDef node)
int _count_boolean_expressions (nodes.BoolOp bool_op)
int _count_methods_in_class (nodes.ClassDef node)
Iterator[nodes.ClassDef] _get_parents_iter (nodes.ClassDef node, frozenset[str] ignored_parents)
set[nodes.ClassDef] _get_parents (nodes.ClassDef node, frozenset[str] ignored_parents)
None register (PyLinter linter)
Variables
tuple MSGS
SPECIAL_OBJ = re.compile("^_{2}[a-z]+_{2}$")
DATACLASSES_DECORATORS = frozenset({"dataclass", "attrs"})
str DATACLASS_IMPORT = "dataclasses"
ATTRS_DECORATORS = frozenset({"define", "frozen"})
str ATTRS_IMPORT = "attrs"
str TYPING_NAMEDTUPLE = "typing.NamedTuple"
str TYPING_TYPEDDICT = "typing.TypedDict"
str TYPING_EXTENSIONS_TYPEDDICT = "typing_extensions.TypedDict"
STDLIB_CLASSES_IGNORE_ANCESTOR
Detailed Description
Check for signs of poor design.
Function Documentation
_count_boolean_expressions()
int pylint.checkers.design_analysis._count_boolean_expressions (nodes.BoolOp bool_op) protected
Counts the number of boolean expressions in BoolOp `bool_op` (recursive).
example: a and (b or c or (d and e)) ==> 5 boolean expressions
Definition at line 224 of file design_analysis.py.
def _count_boolean_expressions(bool_op: nodes.BoolOp) -> int:
    """Counts the number of boolean expressions in BoolOp `bool_op` (recursive).
    example: a and (b or c or (d and e)) ==> 5 boolean expressions
    """
    nb_bool_expr = 0
    for bool_expr in bool_op.get_children():
        if isinstance(bool_expr, astroid.BoolOp):
            nb_bool_expr += _count_boolean_expressions(bool_expr)
        else:
            nb_bool_expr += 1
    return nb_bool_expr
References _count_boolean_expressions().
Referenced by pylint.checkers.design_analysis.MisdesignChecker._check_boolean_expressions(), and _count_boolean_expressions().
_count_methods_in_class()
int pylint.checkers.design_analysis._count_methods_in_class (nodes.ClassDef node) protected
Definition at line 238 of file design_analysis.py.
def _count_methods_in_class(node: nodes.ClassDef) -> int:
    all_methods = sum(1 for method in node.methods() if not method.name.startswith("_"))
    # Special methods count towards the number of public methods,
    # but don't count towards there being too many methods.
    for method in node.mymethods():
        if SPECIAL_OBJ.search(method.name) and method.name != "__init__":
            all_methods += 1
    return all_methods
Referenced by pylint.checkers.design_analysis.MisdesignChecker.leave_classdef().
_get_parents()
set[nodes.ClassDef] pylint.checkers.design_analysis._get_parents (nodes.ClassDef node, frozenset[str] ignored_parents) protected
Definition at line 284 of file design_analysis.py.
) -> set[nodes.ClassDef]:
    return set(_get_parents_iter(node, ignored_parents))
References _get_parents_iter().
Referenced by pylint.checkers.design_analysis.MisdesignChecker.visit_classdef().
_get_parents_iter()
Iterator[nodes.ClassDef] pylint.checkers.design_analysis._get_parents_iter (nodes.ClassDef node, frozenset[str] ignored_parents) protected
Get parents of ``node``, excluding ancestors of ``ignored_parents``.
If we have the following inheritance diagram:
         F
        /
    D  E
     \/
      B  C
       \/
        A      # class A(B, C): ...
And ``ignored_parents`` is ``{"E"}``, then this function will return
``{A, B, C, D}`` -- both ``E`` and its ancestors are excluded.
Definition at line 248 of file design_analysis.py.
) -> Iterator[nodes.ClassDef]:
    r"""Get parents of ``node``, excluding ancestors of ``ignored_parents``.
    If we have the following inheritance diagram:
             F
            /
        D  E
         \/
          B  C
           \/
            A      # class A(B, C): ...
    And ``ignored_parents`` is ``{"E"}``, then this function will return
    ``{A, B, C, D}`` -- both ``E`` and its ancestors are excluded.
    """
    parents: set[nodes.ClassDef] = set()
    to_explore = list(node.ancestors(recurs=False))
    while to_explore:
        parent = to_explore.pop()
        if parent.qname() in ignored_parents:
            continue
        if parent not in parents:
            # This guard might appear to be performing the same function as
            # adding the resolved parents to a set to eliminate duplicates
            # (legitimate due to diamond inheritance patterns), but its
            # additional purpose is to prevent cycles (not normally possible,
            # but potential due to inference) and thus guarantee termination
            # of the while-loop
            yield parent
            parents.add(parent)
            to_explore.extend(parent.ancestors(recurs=False))
Referenced by _get_parents().
_is_exempt_from_public_methods()
bool pylint.checkers.design_analysis._is_exempt_from_public_methods (astroid.ClassDef node) protected
Check if a class is exempt from too-few-public-methods.
Definition at line 185 of file design_analysis.py.
def _is_exempt_from_public_methods(node: astroid.ClassDef) -> bool:
    """Check if a class is exempt from too-few-public-methods."""
    # If it's a typing.Namedtuple, typing.TypedDict or an Enum
    for ancestor in node.ancestors():
        if is_enum(ancestor):
            return True
        if ancestor.qname() in (
            TYPING_NAMEDTUPLE,
            TYPING_TYPEDDICT,
            TYPING_EXTENSIONS_TYPEDDICT,
        ):
            return True
    # Or if it's a dataclass
    if not node.decorators:
        return False
    root_locals = set(node.root().locals)
    for decorator in node.decorators.nodes:
        if isinstance(decorator, astroid.Call):
            decorator = decorator.func
        if not isinstance(decorator, (astroid.Name, astroid.Attribute)):
            continue
        if isinstance(decorator, astroid.Name):
            name = decorator.name
        else:
            name = decorator.attrname
        if name in DATACLASSES_DECORATORS and (
            root_locals.intersection(DATACLASSES_DECORATORS)
            or DATACLASS_IMPORT in root_locals
        ):
            return True
        if name in ATTRS_DECORATORS and (
            root_locals.intersection(ATTRS_DECORATORS) or ATTRS_IMPORT in root_locals
        ):
            return True
    return False
Referenced by pylint.checkers.design_analysis.MisdesignChecker.leave_classdef().
register()
None pylint.checkers.design_analysis.register (PyLinter linter)
Definition at line 701 of file design_analysis.py.
def register(linter: PyLinter) -> None:
    linter.register_checker(MisdesignChecker(linter))
Variable Documentation
ATTRS_DECORATORS
pylint.checkers.design_analysis.ATTRS_DECORATORS = frozenset({"define", "frozen"})
Definition at line 94 of file design_analysis.py.
ATTRS_IMPORT
str pylint.checkers.design_analysis.ATTRS_IMPORT = "attrs"
Definition at line 95 of file design_analysis.py.
DATACLASS_IMPORT
str pylint.checkers.design_analysis.DATACLASS_IMPORT = "dataclasses"
Definition at line 93 of file design_analysis.py.
DATACLASSES_DECORATORS
pylint.checkers.design_analysis.DATACLASSES_DECORATORS = frozenset({"dataclass", "attrs"})
Definition at line 92 of file design_analysis.py.
MSGS
tuple pylint.checkers.design_analysis.MSGS
Definition at line 25 of file design_analysis.py.
SPECIAL_OBJ
pylint.checkers.design_analysis.SPECIAL_OBJ = re.compile("^_{2}[a-z]+_{2}$")
Definition at line 91 of file design_analysis.py.
STDLIB_CLASSES_IGNORE_ANCESTOR
pylint.checkers.design_analysis.STDLIB_CLASSES_IGNORE_ANCESTOR
Definition at line 101 of file design_analysis.py.
TYPING_EXTENSIONS_TYPEDDICT
str pylint.checkers.design_analysis.TYPING_EXTENSIONS_TYPEDDICT = "typing_extensions.TypedDict"
Definition at line 98 of file design_analysis.py.
TYPING_NAMEDTUPLE
str pylint.checkers.design_analysis.TYPING_NAMEDTUPLE = "typing.NamedTuple"
Definition at line 96 of file design_analysis.py.
TYPING_TYPEDDICT
str pylint.checkers.design_analysis.TYPING_TYPEDDICT = "typing.TypedDict"
Definition at line 97 of file design_analysis.py.