Read&Watch: urllib3.filepost Namespace Reference
urllib3.filepost Namespace Reference
Functions
str choose_boundary ()
typing.Iterable[RequestField] iter_field_objects (_TYPE_FIELDS fields)
tuple[bytes, str] encode_multipart_formdata (_TYPE_FIELDS fields, str|None boundary=None)
Variables
writer = codecs.lookup("utf-8")[3]
_TYPE_FIELDS_SEQUENCE
_TYPE_FIELDS
Function Documentation
choose_boundary()
str urllib3.filepost.choose_boundary ()
Our embarrassingly-simple replacement for mimetools.choose_boundary.
Definition at line 22 of file filepost.py.
def choose_boundary() -> str:
    """
    Our embarrassingly-simple replacement for mimetools.choose_boundary.
    """
    return binascii.hexlify(os.urandom(16)).decode()
Referenced by encode_multipart_formdata().
encode_multipart_formdata()
tuple[bytes, str] urllib3.filepost.encode_multipart_formdata (_TYPE_FIELDS fields, str | None boundary = None)
Encode a dictionary of ``fields`` using the multipart/form-data MIME format.
:param fields:
    Dictionary of fields or list of (key, :class:`~urllib3.fields.RequestField`).
    Values are processed by :func:`urllib3.fields.RequestField.from_tuples`.
:param boundary:
    If not specified, then a random boundary will be generated using
    :func:`urllib3.filepost.choose_boundary`.
Definition at line 51 of file filepost.py.
) -> tuple[bytes, str]:
    """
    Encode a dictionary of ``fields`` using the multipart/form-data MIME format.
    :param fields:
        Dictionary of fields or list of (key, :class:`~urllib3.fields.RequestField`).
        Values are processed by :func:`urllib3.fields.RequestField.from_tuples`.
    :param boundary:
        If not specified, then a random boundary will be generated using
        :func:`urllib3.filepost.choose_boundary`.
    """
    body = BytesIO()
    if boundary is None:
        boundary = choose_boundary()
    for field in iter_field_objects(fields):
        body.write(f"--{boundary}\r\n".encode("latin-1"))
        writer(body).write(field.render_headers())
        data = field.data
        if isinstance(data, int):
            data = str(data)  # Backwards compatibility
        if isinstance(data, str):
            writer(body).write(data)
        else:
            body.write(data)
        body.write(b"\r\n")
    body.write(f"--{boundary}--\r\n".encode("latin-1"))
    content_type = f"multipart/form-data; boundary={boundary}"
    return body.getvalue(), content_type
References choose_boundary(), iter_field_objects(), and writer.
iter_field_objects()
typing.Iterable[RequestField] urllib3.filepost.iter_field_objects (_TYPE_FIELDS fields)
Iterate over fields.
Supports list of (k, v) tuples and dicts, and lists of
:class:`~urllib3.fields.RequestField`.
Definition at line 29 of file filepost.py.
def iter_field_objects(fields: _TYPE_FIELDS) -> typing.Iterable[RequestField]:
    """
    Iterate over fields.
    Supports list of (k, v) tuples and dicts, and lists of
    :class:`~urllib3.fields.RequestField`.
    """
    iterable: typing.Iterable[RequestField | tuple[str, _TYPE_FIELD_VALUE_TUPLE]]
    if isinstance(fields, typing.Mapping):
        iterable = fields.items()
    else:
        iterable = fields
    for field in iterable:
        if isinstance(field, RequestField):
            yield field
        else:
            yield RequestField.from_tuples(*field)
Referenced by encode_multipart_formdata().
Variable Documentation
_TYPE_FIELDS
urllib3.filepost._TYPE_FIELDS protected
Initial value:
=  typing.Union[
    _TYPE_FIELDS_SEQUENCE,
    typing.Mapping[str, _TYPE_FIELD_VALUE_TUPLE],
]
Definition at line 16 of file filepost.py.
_TYPE_FIELDS_SEQUENCE
urllib3.filepost._TYPE_FIELDS_SEQUENCE protected
Initial value:
=  typing.Sequence[
    typing.Union[typing.Tuple[str, _TYPE_FIELD_VALUE_TUPLE], RequestField]
]
Definition at line 13 of file filepost.py.
writer
urllib3.filepost.writer = codecs.lookup("utf-8")[3]
Definition at line 11 of file filepost.py.
Referenced by encode_multipart_formdata().