Read&Watch: django.urls.resolvers Namespace Reference
django.urls.resolvers Namespace Reference
Classes
class CheckURLMixin
class LocalePrefixPattern
class LocaleRegexDescriptor
class LocaleRegexRouteDescriptor
class RegexPattern
class ResolverMatch
class RoutePattern
class URLPattern
class URLResolver
Functions
get_resolver (urlconf=None)
_get_cached_resolver (urlconf=None)
get_ns_resolver (ns_pattern, resolver, converters)
_route_to_regex (route, is_endpoint)
Variables
_PATH_PARAMETER_COMPONENT_RE
whitespace_set = frozenset(string.whitespace)
Detailed Description
This module converts requested URLs to callback view functions.
URLResolver is the main class here. Its resolve() method takes a URL (as
a string) and returns a ResolverMatch object which provides access to all
attributes of the resolved URL match.
Function Documentation
_get_cached_resolver()
django.urls.resolvers._get_cached_resolver (urlconf = None) protected
Definition at line 115 of file resolvers.py.
def _get_cached_resolver(urlconf=None):
    return URLResolver(RegexPattern(r"^/"), urlconf)
@functools.cache
Referenced by get_resolver().
_route_to_regex()
django.urls.resolvers._route_to_regex (route, is_endpoint) protected
Convert a path pattern into a regular expression. Return the regular
expression and a dictionary mapping the capture names to the converters.
For example, 'foo/<int:pk>' returns '^foo\\/(?P<pk>[0-9]+)'
and {'pk': <django.urls.converters.IntConverter>}.
Definition at line 250 of file resolvers.py.
def _route_to_regex(route, is_endpoint):
    """
    Convert a path pattern into a regular expression. Return the regular
    expression and a dictionary mapping the capture names to the converters.
    For example, 'foo/<int:pk>' returns '^foo\\/(?P<pk>[0-9]+)'
    and {'pk': <django.urls.converters.IntConverter>}.
    """
    parts = ["^"]
    all_converters = get_converters()
    converters = {}
    previous_end = 0
    for match_ in _PATH_PARAMETER_COMPONENT_RE.finditer(route):
        if not whitespace_set.isdisjoint(match_[0]):
            raise ImproperlyConfigured(
                f"URL route {route!r} cannot contain whitespace in angle brackets <…>."
            )
        # Default to make converter "str" if unspecified (parameter always
        # matches something).
        raw_converter, parameter = match_.groups(default="str")
        if not parameter.isidentifier():
            raise ImproperlyConfigured(
                f"URL route {route!r} uses parameter name {parameter!r} which "
                "isn't a valid Python identifier."
            )
        try:
            converter = all_converters[raw_converter]
        except KeyError as e:
            raise ImproperlyConfigured(
                f"URL route {route!r} uses invalid converter {raw_converter!r}."
            ) from e
        converters[parameter] = converter
        start, end = match_.span()
        parts.append(re.escape(route[previous_end:start]))
        previous_end = end
        parts.append(f"(?P<{parameter}>{converter.regex})")
    parts.append(re.escape(route[previous_end:]))
    if is_endpoint:
        parts.append(r"\Z")
    return "".join(parts), converters
Referenced by django.urls.resolvers.LocaleRegexRouteDescriptor.__get__().
get_ns_resolver()
django.urls.resolvers.get_ns_resolver (ns_pattern, resolver, converters)
Definition at line 120 of file resolvers.py.
def get_ns_resolver(ns_pattern, resolver, converters):
    # Build a namespaced resolver for the given parent URLconf pattern.
    # This makes it possible to have captured parameters in the parent
    # URLconf pattern.
    pattern = RegexPattern(ns_pattern)
    pattern.converters = dict(converters)
    ns_resolver = URLResolver(pattern, resolver.url_patterns)
    return URLResolver(RegexPattern(r"^/"), [ns_resolver])
get_resolver()
django.urls.resolvers.get_resolver (urlconf = None)
Definition at line 108 of file resolvers.py.
def get_resolver(urlconf=None):
    if urlconf is None:
        urlconf = settings.ROOT_URLCONF
    return _get_cached_resolver(urlconf)
@functools.cache
References _get_cached_resolver().
Variable Documentation
_PATH_PARAMETER_COMPONENT_RE
django.urls.resolvers._PATH_PARAMETER_COMPONENT_RE protected
Initial value:
=  _lazy_re_compile(
    r"<(?:(?P<converter>[^>:]+):)?(?P<parameter>[^>]+)>"
)
Definition at line 242 of file resolvers.py.
whitespace_set
django.urls.resolvers.whitespace_set = frozenset(string.whitespace)
Definition at line 246 of file resolvers.py.