Read&Watch: pip._vendor.idna.core Namespace Reference
pip._vendor.idna.core Namespace Reference
Classes
class IDNABidiError
class IDNAError
class InvalidCodepoint
class InvalidCodepointContext
Functions
int _combining_class (int cp)
bool _is_script (str cp, str script)
bytes _punycode (str s)
str _unot (int s)
bool valid_label_length (Union[bytes, str] label)
bool valid_string_length (Union[bytes, str] label, bool trailing_dot)
bool check_bidi (str label, bool check_ltr=False)
bool check_initial_combiner (str label)
bool check_hyphen_ok (str label)
None check_nfc (str label)
bool valid_contextj (str label, int pos)
bool valid_contexto (str label, int pos, bool exception=False)
None check_label (Union[str, bytes, bytearray] label)
bytes alabel (str label)
str ulabel (Union[str, bytes, bytearray] label)
str uts46_remap (str domain, bool std3_rules=True, bool transitional=False)
bytes encode (Union[str, bytes, bytearray] s, bool strict=False, bool uts46=False, bool std3_rules=False, bool transitional=False)
str decode (Union[str, bytes, bytearray] s, bool strict=False, bool uts46=False, bool std3_rules=False)
Variables
int _virama_combining_class = 9
str _alabel_prefix = b'xn--'
_unicode_dots_re = re.compile('[\u002e\u3002\uff0e\uff61]')
Function Documentation
_combining_class()
int pip._vendor.idna.core._combining_class (int cp) protected
Definition at line 32 of file core.py.
def _combining_class(cp: int) -> int:
    v = unicodedata.combining(chr(cp))
    if v == 0:
        if not unicodedata.name(chr(cp)):
            raise ValueError('Unknown character in unicodedata')
    return v
Referenced by valid_contextj().
_is_script()
bool pip._vendor.idna.core._is_script (str cp, str script) protected
Definition at line 39 of file core.py.
def _is_script(cp: str, script: str) -> bool:
    return intranges_contain(ord(cp), idnadata.scripts[script])
Referenced by valid_contexto().
_punycode()
bytes pip._vendor.idna.core._punycode (str s) protected
Definition at line 42 of file core.py.
def _punycode(s: str) -> bytes:
    return s.encode('punycode')
Referenced by alabel().
_unot()
str pip._vendor.idna.core._unot (int s) protected
Definition at line 45 of file core.py.
def _unot(s: int) -> str:
    return 'U+{:04X}'.format(s)
Referenced by check_label(), and uts46_remap().
alabel()
bytes pip._vendor.idna.core.alabel (str label)
Definition at line 255 of file core.py.
def alabel(label: str) -> bytes:
    try:
        label_bytes = label.encode('ascii')
        ulabel(label_bytes)
        if not valid_label_length(label_bytes):
            raise IDNAError('Label too long')
        return label_bytes
    except UnicodeEncodeError:
        pass
    check_label(label)
    label_bytes = _alabel_prefix + _punycode(label)
    if not valid_label_length(label_bytes):
        raise IDNAError('Label too long')
    return label_bytes
References _punycode(), check_label(), ulabel(), and valid_label_length().
Referenced by encode().
check_bidi()
bool pip._vendor.idna.core.check_bidi (str label, bool check_ltr = False)
Definition at line 61 of file core.py.
def check_bidi(label: str, check_ltr: bool = False) -> bool:
    # Bidi rules should only be applied if string contains RTL characters
    bidi_label = False
    for (idx, cp) in enumerate(label, 1):
        direction = unicodedata.bidirectional(cp)
        if direction == '':
            # String likely comes from a newer version of Unicode
            raise IDNABidiError('Unknown directionality in label {} at position {}'.format(repr(label), idx))
        if direction in ['R', 'AL', 'AN']:
            bidi_label = True
    if not bidi_label and not check_ltr:
        return True
    # Bidi rule 1
    direction = unicodedata.bidirectional(label[0])
    if direction in ['R', 'AL']:
        rtl = True
    elif direction == 'L':
        rtl = False
    else:
        raise IDNABidiError('First codepoint in label {} must be directionality L, R or AL'.format(repr(label)))
    valid_ending = False
    number_type = None  # type: Optional[str]
    for (idx, cp) in enumerate(label, 1):
        direction = unicodedata.bidirectional(cp)
        if rtl:
            # Bidi rule 2
            if not direction in ['R', 'AL', 'AN', 'EN', 'ES', 'CS', 'ET', 'ON', 'BN', 'NSM']:
                raise IDNABidiError('Invalid direction for codepoint at position {} in a right-to-left label'.format(idx))
            # Bidi rule 3
            if direction in ['R', 'AL', 'EN', 'AN']:
                valid_ending = True
            elif direction != 'NSM':
                valid_ending = False
            # Bidi rule 4
            if direction in ['AN', 'EN']:
                if not number_type:
                    number_type = direction
                else:
                    if number_type != direction:
                        raise IDNABidiError('Can not mix numeral types in a right-to-left label')
        else:
            # Bidi rule 5
            if not direction in ['L', 'EN', 'ES', 'CS', 'ET', 'ON', 'BN', 'NSM']:
                raise IDNABidiError('Invalid direction for codepoint at position {} in a left-to-right label'.format(idx))
            # Bidi rule 6
            if direction in ['L', 'EN']:
                valid_ending = True
            elif direction != 'NSM':
                valid_ending = False
    if not valid_ending:
        raise IDNABidiError('Label ends with illegal codepoint directionality')
    return True
Referenced by check_label().
check_hyphen_ok()
bool pip._vendor.idna.core.check_hyphen_ok (str label)
Definition at line 126 of file core.py.
def check_hyphen_ok(label: str) -> bool:
    if label[2:4] == '--':
        raise IDNAError('Label has disallowed hyphens in 3rd and 4th position')
    if label[0] == '-' or label[-1] == '-':
        raise IDNAError('Label must not start or end with a hyphen')
    return True
Referenced by check_label().
check_initial_combiner()
bool pip._vendor.idna.core.check_initial_combiner (str label)
Definition at line 120 of file core.py.
def check_initial_combiner(label: str) -> bool:
    if unicodedata.category(label[0])[0] == 'M':
        raise IDNAError('Label begins with an illegal combining character')
    return True
Referenced by check_label().
check_label()
None pip._vendor.idna.core.check_label (Union[str, bytes, bytearray] label)
Definition at line 228 of file core.py.
def check_label(label: Union[str, bytes, bytearray]) -> None:
    if isinstance(label, (bytes, bytearray)):
        label = label.decode('utf-8')
    if len(label) == 0:
        raise IDNAError('Empty Label')
    check_nfc(label)
    check_hyphen_ok(label)
    check_initial_combiner(label)
    for (pos, cp) in enumerate(label):
        cp_value = ord(cp)
        if intranges_contain(cp_value, idnadata.codepoint_classes['PVALID']):
            continue
        elif intranges_contain(cp_value, idnadata.codepoint_classes['CONTEXTJ']):
            if not valid_contextj(label, pos):
                raise InvalidCodepointContext('Joiner {} not allowed at position {} in {}'.format(
                    _unot(cp_value), pos+1, repr(label)))
        elif intranges_contain(cp_value, idnadata.codepoint_classes['CONTEXTO']):
            if not valid_contexto(label, pos):
                raise InvalidCodepointContext('Codepoint {} not allowed at position {} in {}'.format(_unot(cp_value), pos+1, repr(label)))
        else:
            raise InvalidCodepoint('Codepoint {} at position {} of {} not allowed'.format(_unot(cp_value), pos+1, repr(label)))
    check_bidi(label)
References _unot(), check_bidi(), check_hyphen_ok(), check_initial_combiner(), check_nfc(), valid_contextj(), and valid_contexto().
Referenced by alabel(), and ulabel().
check_nfc()
None pip._vendor.idna.core.check_nfc (str label)
Definition at line 134 of file core.py.
def check_nfc(label: str) -> None:
    if unicodedata.normalize('NFC', label) != label:
        raise IDNAError('Label must be in Normalization Form C')
Referenced by check_label().
decode()
str pip._vendor.idna.core.decode (Union[str, bytes, bytearray] s, bool strict = False, bool uts46 = False, bool std3_rules = False)
Definition at line 368 of file core.py.
def decode(s: Union[str, bytes, bytearray], strict: bool = False, uts46: bool = False, std3_rules: bool = False) -> str:
    try:
        if not isinstance(s, str):
            s = str(s, 'ascii')
    except UnicodeDecodeError:
        raise IDNAError('Invalid ASCII in A-label')
    if uts46:
        s = uts46_remap(s, std3_rules, False)
    trailing_dot = False
    result = []
    if not strict:
        labels = _unicode_dots_re.split(s)
    else:
        labels = s.split('.')
    if not labels or labels == ['']:
        raise IDNAError('Empty domain')
    if not labels[-1]:
        del labels[-1]
        trailing_dot = True
    for label in labels:
        s = ulabel(label)
        if s:
            result.append(s)
        else:
            raise IDNAError('Empty label')
    if trailing_dot:
        result.append('')
    return '.'.join(result)
References ulabel(), and uts46_remap().
Referenced by pip._vendor.idna.compat.ToUnicode().
encode()
bytes pip._vendor.idna.core.encode (Union[str, bytes, bytearray] s, bool strict = False, bool uts46 = False, bool std3_rules = False, bool transitional = False)
Definition at line 335 of file core.py.
def encode(s: Union[str, bytes, bytearray], strict: bool = False, uts46: bool = False, std3_rules: bool = False, transitional: bool = False) -> bytes:
    if not isinstance(s, str):
        try:
            s = str(s, 'ascii')
        except UnicodeDecodeError:
            raise IDNAError('should pass a unicode string to the function rather than a byte string.')
    if uts46:
        s = uts46_remap(s, std3_rules, transitional)
    trailing_dot = False
    result = []
    if strict:
        labels = s.split('.')
    else:
        labels = _unicode_dots_re.split(s)
    if not labels or labels == ['']:
        raise IDNAError('Empty domain')
    if labels[-1] == '':
        del labels[-1]
        trailing_dot = True
    for label in labels:
        s = alabel(label)
        if s:
            result.append(s)
        else:
            raise IDNAError('Empty label')
    if trailing_dot:
        result.append(b'')
    s = b'.'.join(result)
    if not valid_string_length(s, trailing_dot):
        raise IDNAError('Domain too long')
    return s
References alabel(), uts46_remap(), and valid_string_length().
Referenced by pip._vendor.idna.compat.ToASCII().
ulabel()
str pip._vendor.idna.core.ulabel (Union[str, bytes, bytearray] label)
Definition at line 274 of file core.py.
def ulabel(label: Union[str, bytes, bytearray]) -> str:
    if not isinstance(label, (bytes, bytearray)):
        try:
            label_bytes = label.encode('ascii')
        except UnicodeEncodeError:
            check_label(label)
            return label
    else:
        label_bytes = label
    label_bytes = label_bytes.lower()
    if label_bytes.startswith(_alabel_prefix):
        label_bytes = label_bytes[len(_alabel_prefix):]
        if not label_bytes:
            raise IDNAError('Malformed A-label, no Punycode eligible content found')
        if label_bytes.decode('ascii')[-1] == '-':
            raise IDNAError('A-label must not end with a hyphen')
    else:
        check_label(label_bytes)
        return label_bytes.decode('ascii')
    try:
        label = label_bytes.decode('punycode')
    except UnicodeError:
        raise IDNAError('Invalid A-label')
    check_label(label)
    return label
References check_label().
Referenced by alabel(), and decode().
uts46_remap()
str pip._vendor.idna.core.uts46_remap (str domain, bool std3_rules = True, bool transitional = False)
Re-map the characters in the string according to UTS46 processing.
Definition at line 303 of file core.py.
def uts46_remap(domain: str, std3_rules: bool = True, transitional: bool = False) -> str:
    """Re-map the characters in the string according to UTS46 processing."""
    from .uts46data import uts46data
    output = ''
    for pos, char in enumerate(domain):
        code_point = ord(char)
        try:
            uts46row = uts46data[code_point if code_point < 256 else
                bisect.bisect_left(uts46data, (code_point, 'Z')) - 1]
            status = uts46row[1]
            replacement = None  # type: Optional[str]
            if len(uts46row) == 3:
                replacement = uts46row[2]
            if (status == 'V' or
                    (status == 'D' and not transitional) or
                    (status == '3' and not std3_rules and replacement is None)):
                output += char
            elif replacement is not None and (status == 'M' or
                    (status == '3' and not std3_rules) or
                    (status == 'D' and transitional)):
                output += replacement
            elif status != 'I':
                raise IndexError()
        except IndexError:
            raise InvalidCodepoint(
                'Codepoint {} not allowed at position {} in {}'.format(
                _unot(code_point), pos + 1, repr(domain)))
    return unicodedata.normalize('NFC', output)
References _unot().
Referenced by decode(), and encode().
valid_contextj()
bool pip._vendor.idna.core.valid_contextj (str label, int pos)
Definition at line 139 of file core.py.
def valid_contextj(label: str, pos: int) -> bool:
    cp_value = ord(label[pos])
    if cp_value == 0x200c:
        if pos > 0:
            if _combining_class(ord(label[pos - 1])) == _virama_combining_class:
                return True
        ok = False
        for i in range(pos-1, -1, -1):
            joining_type = idnadata.joining_types.get(ord(label[i]))
            if joining_type == ord('T'):
                continue
            elif joining_type in [ord('L'), ord('D')]:
                ok = True
                break
            else:
                break
        if not ok:
            return False
        ok = False
        for i in range(pos+1, len(label)):
            joining_type = idnadata.joining_types.get(ord(label[i]))
            if joining_type == ord('T'):
                continue
            elif joining_type in [ord('R'), ord('D')]:
                ok = True
                break
            else:
                break
        return ok
    if cp_value == 0x200d:
        if pos > 0:
            if _combining_class(ord(label[pos - 1])) == _virama_combining_class:
                return True
        return False
    else:
        return False
References _combining_class().
Referenced by check_label().
valid_contexto()
bool pip._vendor.idna.core.valid_contexto (str label, int pos, bool exception = False)
Definition at line 186 of file core.py.
def valid_contexto(label: str, pos: int, exception: bool = False) -> bool:
    cp_value = ord(label[pos])
    if cp_value == 0x00b7:
        if 0 < pos < len(label)-1:
            if ord(label[pos - 1]) == 0x006c and ord(label[pos + 1]) == 0x006c:
                return True
        return False
    elif cp_value == 0x0375:
        if pos < len(label)-1 and len(label) > 1:
            return _is_script(label[pos + 1], 'Greek')
        return False
    elif cp_value == 0x05f3 or cp_value == 0x05f4:
        if pos > 0:
            return _is_script(label[pos - 1], 'Hebrew')
        return False
    elif cp_value == 0x30fb:
        for cp in label:
            if cp == '\u30fb':
                continue
            if _is_script(cp, 'Hiragana') or _is_script(cp, 'Katakana') or _is_script(cp, 'Han'):
                return True
        return False
    elif 0x660 <= cp_value <= 0x669:
        for cp in label:
            if 0x6f0 <= ord(cp) <= 0x06f9:
                return False
        return True
    elif 0x6f0 <= cp_value <= 0x6f9:
        for cp in label:
            if 0x660 <= ord(cp) <= 0x0669:
                return False
        return True
    return False
References _is_script().
Referenced by check_label().
valid_label_length()
bool pip._vendor.idna.core.valid_label_length (Union[bytes, str] label)
Definition at line 49 of file core.py.
def valid_label_length(label: Union[bytes, str]) -> bool:
    if len(label) > 63:
        return False
    return True
Referenced by alabel().
valid_string_length()
bool pip._vendor.idna.core.valid_string_length (Union[bytes, str] label, bool trailing_dot)
Definition at line 55 of file core.py.
def valid_string_length(label: Union[bytes, str], trailing_dot: bool) -> bool:
    if len(label) > (254 if trailing_dot else 253):
        return False
    return True
Referenced by encode().
Variable Documentation
_alabel_prefix
str pip._vendor.idna.core._alabel_prefix = b'xn--' protected
Definition at line 9 of file core.py.
_unicode_dots_re
pip._vendor.idna.core._unicode_dots_re = re.compile('[\u002e\u3002\uff0e\uff61]') protected
Definition at line 10 of file core.py.
_virama_combining_class
int pip._vendor.idna.core._virama_combining_class = 9 protected
Definition at line 8 of file core.py.