Read&Watch: django.contrib.gis.measure Namespace Reference
django.contrib.gis.measure Namespace Reference
Classes
class Area
class Distance
class MeasureBase
Functions
pretty_name (obj)
Variables
tuple NUMERIC_TYPES = (int, float, Decimal)
str AREA_PREFIX = "sq_"
D = Distance
A = Area
Detailed Description
Distance and Area objects to allow for sensible and convenient calculation
and conversions.
Authors: Robert Coup, Justin Bronn, Riccardo Di Virgilio
Inspired by GeoPy (https://github.com/geopy/geopy)
and Geoff Biggs' PhD work on dimensioned units for robotics.
Function Documentation
pretty_name()
django.contrib.gis.measure.pretty_name (obj)
Definition at line 47 of file measure.py.
def pretty_name(obj):
    return obj.__name__ if obj.__class__ == type else obj.__class__.__name__
@total_ordering
Referenced by django.contrib.gis.measure.MeasureBase.__add__(), django.contrib.gis.measure.MeasureBase.__iadd__(), django.contrib.gis.measure.MeasureBase.__imul__(), django.contrib.gis.measure.MeasureBase.__isub__(), django.contrib.gis.measure.MeasureBase.__itruediv__(), django.contrib.gis.measure.Distance.__mul__(), django.contrib.gis.measure.MeasureBase.__mul__(), django.contrib.gis.measure.MeasureBase.__repr__(), django.contrib.gis.measure.MeasureBase.__sub__(), django.contrib.gis.measure.Area.__truediv__(), and django.contrib.gis.measure.MeasureBase.__truediv__().
Variable Documentation
A
django.contrib.gis.measure.A = Area
Definition at line 373 of file measure.py.
AREA_PREFIX
str django.contrib.gis.measure.AREA_PREFIX = "sq_"
Definition at line 44 of file measure.py.
D
django.contrib.gis.measure.D = Distance
Definition at line 372 of file measure.py.
NUMERIC_TYPES
tuple django.contrib.gis.measure.NUMERIC_TYPES = (int, float, Decimal)
Definition at line 43 of file measure.py.