Read&Watch: astroid.interpreter.dunder_lookup Namespace Reference
astroid.interpreter.dunder_lookup Namespace Reference
Functions
list _lookup_in_mro (node, name)
list lookup (nodes.NodeNG node, str name, InferenceContext|None context=None)
list _class_lookup (nodes.ClassDef node, str name, InferenceContext|None context=None)
list _builtin_lookup (node, name)
Detailed Description
Contains logic for retrieving special methods.
This implementation does not rely on the dot attribute access
logic, found in ``.getattr()``. The difference between these two
is that the dunder methods are looked with the type slots
(you can find more about these here
http://lucumr.pocoo.org/2014/8/16/the-python-i-would-like-to-see/)
As such, the lookup for the special methods is actually simpler than
the dot attribute access.
Function Documentation
_builtin_lookup()
list astroid.interpreter.dunder_lookup._builtin_lookup (node, name) protected
Definition at line 72 of file dunder_lookup.py.
def _builtin_lookup(node, name) -> list:
    values = node.locals.get(name, [])
    if not values:
        raise AttributeInferenceError(attribute=name, target=node)
    return values
Referenced by lookup().
_class_lookup()
list astroid.interpreter.dunder_lookup._class_lookup (nodes.ClassDef node, str name, InferenceContext | None context = None) protected
Definition at line 62 of file dunder_lookup.py.
) -> list:
    metaclass = node.metaclass(context=context)
    if metaclass is None:
        raise AttributeInferenceError(attribute=name, target=node)
    return _lookup_in_mro(metaclass, name)
References _lookup_in_mro().
Referenced by lookup().
_lookup_in_mro()
list astroid.interpreter.dunder_lookup._lookup_in_mro (node, name) protected
Definition at line 28 of file dunder_lookup.py.
def _lookup_in_mro(node, name) -> list:
    attrs = node.locals.get(name, [])
    nodes = itertools.chain.from_iterable(
        ancestor.locals.get(name, []) for ancestor in node.ancestors(recurs=True)
    )
    values = list(itertools.chain(attrs, nodes))
    if not values:
        raise AttributeInferenceError(attribute=name, target=node)
    return values
Referenced by _class_lookup(), and lookup().
lookup()
list astroid.interpreter.dunder_lookup.lookup (nodes.NodeNG node, str name, InferenceContext | None context = None)
Lookup the given special method name in the given *node*.
If the special method was found, then a list of attributes
will be returned. Otherwise, `astroid.AttributeInferenceError`
is going to be raised.
Definition at line 41 of file dunder_lookup.py.
) -> list:
    """Lookup the given special method name in the given *node*.
    If the special method was found, then a list of attributes
    will be returned. Otherwise, `astroid.AttributeInferenceError`
    is going to be raised.
    """
    if isinstance(
        node, (astroid.List, astroid.Tuple, astroid.Const, astroid.Dict, astroid.Set)
    ):
        return _builtin_lookup(node, name)
    if isinstance(node, astroid.Instance):
        return _lookup_in_mro(node, name)
    if isinstance(node, astroid.ClassDef):
        return _class_lookup(node, name, context=context)
    raise AttributeInferenceError(attribute=name, target=node)
References _builtin_lookup(), _class_lookup(), and _lookup_in_mro().
Referenced by pylint.checkers.typecheck.TypeChecker._check_invalid_sequence_index().