Read&Watch: pip._internal.cli.cmdoptions Namespace Reference
pip._internal.cli.cmdoptions Namespace Reference
Classes
class PipOption
Functions
None raise_option_error (OptionParser parser, Option option, str msg)
OptionGroup make_option_group (Dict[str, Any] group, ConfigOptionParser parser)
None check_dist_restriction (Values options, bool check_target=False)
str _path_option_check (Option option, str opt, str value)
str _package_name_option_check (Option option, str opt, str value)
Option exists_action ()
Option extra_index_url ()
Option find_links ()
Option trusted_host ()
Option constraints ()
Option requirements ()
Option editable ()
None _handle_src (Option option, str opt_str, str value, OptionParser parser)
Any _get_format_control (Values values, Option option)
None _handle_no_binary (Option option, str opt_str, str value, OptionParser parser)
None _handle_only_binary (Option option, str opt_str, str value, OptionParser parser)
Option no_binary ()
Option only_binary ()
Tuple[Tuple[int,...], Optional[str]] _convert_python_version (str value)
None _handle_python_version (Option option, str opt_str, str value, OptionParser parser)
None add_target_python_options (OptionGroup cmd_opts)
TargetPython make_target_python (Values options)
Option prefer_binary ()
None _handle_no_cache_dir (Option option, str opt, str value, OptionParser parser)
None _handle_no_use_pep517 (Option option, str opt, str value, OptionParser parser)
None _handle_config_settings (Option option, str opt_str, str value, OptionParser parser)
None _handle_merge_hash (Option option, str opt_str, str value, OptionParser parser)
None check_list_path_option (Values options)
Variables
logger = logging.getLogger(__name__)
Callable cert
Callable client_cert
Callable index_url
Callable no_index
Callable src
Callable platforms
Callable python_version
Callable implementation
Callable abis
Callable cache_dir
Callable no_cache
Callable no_deps
Callable ignore_requires_python
Callable no_build_isolation
Callable check_build_deps
Any use_pep517
Any no_use_pep517
Callable config_settings
Callable build_options
Callable global_options
Callable no_clean
Callable pre
Callable disable_pip_version_check
Callable root_user_action
Callable hash
Callable require_hashes
Callable list_path
Callable list_exclude
Callable no_python_version_warning
list ALWAYS_ENABLED_FEATURES
Callable use_new_feature
Callable use_deprecated_feature
dict general_group
groups #
dict index_group
Detailed Description
shared options and groups
The principle here is to define options once, but *not* instantiate them
globally. One reason being that options with action='append' can carry state
between parses. pip parses general options twice internally, and shouldn't
pass on state. To be consistent, all options will follow this design.
Function Documentation
_convert_python_version()
Tuple[Tuple[int, ...], Optional[str]] pip._internal.cli.cmdoptions._convert_python_version (str value) protected
Convert a version string like "3", "37", or "3.7.3" into a tuple of ints.
:return: A 2-tuple (version_info, error_msg), where `error_msg` is
    non-None if and only if there was a parsing error.
Definition at line 548 of file cmdoptions.py.
def _convert_python_version(value: str) -> Tuple[Tuple[int, ...], Optional[str]]:
    """
    Convert a version string like "3", "37", or "3.7.3" into a tuple of ints.
    :return: A 2-tuple (version_info, error_msg), where `error_msg` is
        non-None if and only if there was a parsing error.
    """
    if not value:
        # The empty string is the same as not providing a value.
        return (None, None)
    parts = value.split(".")
    if len(parts) > 3:
        return ((), "at most three version parts are allowed")
    if len(parts) == 1:
        # Then we are in the case of "3" or "37".
        value = parts[0]
        if len(value) > 1:
            parts = [value[0], value[1:]]
    try:
        version_info = tuple(int(part) for part in parts)
    except ValueError:
        return ((), "each version part must be an integer")
    return (version_info, None)
Referenced by _handle_python_version().
_get_format_control()
Any pip._internal.cli.cmdoptions._get_format_control (Values values, Option option) protected
Get a format_control object.
Definition at line 469 of file cmdoptions.py.
def _get_format_control(values: Values, option: Option) -> Any:
    """Get a format_control object."""
    return getattr(values, option.dest)
Referenced by _handle_no_binary(), and _handle_only_binary().
_handle_config_settings()
None pip._internal.cli.cmdoptions._handle_config_settings (Option option, str opt_str, str value, OptionParser parser) protected
Definition at line 821 of file cmdoptions.py.
) -> None:
    key, sep, val = value.partition("=")
    if sep != "=":
        parser.error(f"Arguments to {opt_str} must be of the form KEY=VAL")
    dest = getattr(parser.values, option.dest)
    if dest is None:
        dest = {}
        setattr(parser.values, option.dest, dest)
    if key in dest:
        if isinstance(dest[key], list):
            dest[key].append(val)
        else:
            dest[key] = [dest[key], val]
    else:
        dest[key] = val
_handle_merge_hash()
None pip._internal.cli.cmdoptions._handle_merge_hash (Option option, str opt_str, str value, OptionParser parser) protected
Given a value spelled "algo:digest", append the digest to a list
pointed to in a dict by the algo name.
Definition at line 910 of file cmdoptions.py.
) -> None:
    """Given a value spelled "algo:digest", append the digest to a list
    pointed to in a dict by the algo name."""
    if not parser.values.hashes:
        parser.values.hashes = {}
    try:
        algo, digest = value.split(":", 1)
    except ValueError:
        parser.error(
            f"Arguments to {opt_str} must be a hash name "
            "followed by a value, like --hash=sha256:"
            "abcde..."
        )
    if algo not in STRONG_HASHES:
        parser.error(
            "Allowed hash algorithms for {} are {}.".format(
                opt_str, ", ".join(STRONG_HASHES)
            )
        )
    parser.values.hashes.setdefault(algo, []).append(digest)
_handle_no_binary()
None pip._internal.cli.cmdoptions._handle_no_binary (Option option, str opt_str, str value, OptionParser parser) protected
Definition at line 474 of file cmdoptions.py.
) -> None:
    existing = _get_format_control(parser.values, option)
    FormatControl.handle_mutual_excludes(
        value,
        existing.no_binary,
        existing.only_binary,
    )
References _get_format_control().
_handle_no_cache_dir()
None pip._internal.cli.cmdoptions._handle_no_cache_dir (Option option, str opt, str value, OptionParser parser) protected
Process a value provided for the --no-cache-dir option.
This is an optparse.Option callback for the --no-cache-dir option.
Definition at line 688 of file cmdoptions.py.
) -> None:
    """
    Process a value provided for the --no-cache-dir option.
    This is an optparse.Option callback for the --no-cache-dir option.
    """
    # The value argument will be None if --no-cache-dir is passed via the
    # command-line, since the option doesn't accept arguments.  However,
    # the value can be non-None if the option is triggered e.g. by an
    # environment variable, like PIP_NO_CACHE_DIR=true.
    if value is not None:
        # Then parse the string value to get argument error-checking.
        try:
            strtobool(value)
        except ValueError as exc:
            raise_option_error(parser, option=option, msg=str(exc))
    # Originally, setting PIP_NO_CACHE_DIR to a value that strtobool()
    # converted to 0 (like "false" or "no") caused cache_dir to be disabled
    # rather than enabled (logic would say the latter).  Thus, we disable
    # the cache directory not just on values that parse to True, but (for
    # backwards compatibility reasons) also on values that parse to False.
    # In other words, always set it to False if the option is provided in
    # some (valid) form.
    parser.values.cache_dir = False
References raise_option_error().
_handle_no_use_pep517()
None pip._internal.cli.cmdoptions._handle_no_use_pep517 (Option option, str opt, str value, OptionParser parser) protected
Process a value provided for the --no-use-pep517 option.
This is an optparse.Option callback for the no_use_pep517 option.
Definition at line 765 of file cmdoptions.py.
) -> None:
    """
    Process a value provided for the --no-use-pep517 option.
    This is an optparse.Option callback for the no_use_pep517 option.
    """
    # Since --no-use-pep517 doesn't accept arguments, the value argument
    # will be None if --no-use-pep517 is passed via the command-line.
    # However, the value can be non-None if the option is triggered e.g.
    # by an environment variable, for example "PIP_NO_USE_PEP517=true".
    if value is not None:
        msg = """A value was passed for --no-use-pep517,
        probably using either the PIP_NO_USE_PEP517 environment variable
        or the "no-use-pep517" config file option. Use an appropriate value
        of the PIP_USE_PEP517 environment variable or the "use-pep517"
        config file option instead.
        """
        raise_option_error(parser, option=option, msg=msg)
    # If user doesn't wish to use pep517, we check if setuptools and wheel are installed
    # and raise error if it is not.
    packages = ("setuptools", "wheel")
    if not all(importlib.util.find_spec(package) for package in packages):
        msg = (
            f"It is not possible to use --no-use-pep517 "
            f"without {' and '.join(packages)} installed."
        )
        raise_option_error(parser, option=option, msg=msg)
    # Otherwise, --no-use-pep517 was passed via the command-line.
    parser.values.use_pep517 = False
References raise_option_error().
_handle_only_binary()
None pip._internal.cli.cmdoptions._handle_only_binary (Option option, str opt_str, str value, OptionParser parser) protected
Definition at line 485 of file cmdoptions.py.
) -> None:
    existing = _get_format_control(parser.values, option)
    FormatControl.handle_mutual_excludes(
        value,
        existing.only_binary,
        existing.no_binary,
    )
References _get_format_control().
_handle_python_version()
None pip._internal.cli.cmdoptions._handle_python_version (Option option, str opt_str, str value, OptionParser parser) protected
Handle a provided --python-version value.
Definition at line 577 of file cmdoptions.py.
) -> None:
    """
    Handle a provided --python-version value.
    """
    version_info, error_msg = _convert_python_version(value)
    if error_msg is not None:
        msg = f"invalid --python-version value: {value!r}: {error_msg}"
        raise_option_error(parser, option=option, msg=msg)
    parser.values.python_version = version_info
References _convert_python_version(), and raise_option_error().
_handle_src()
None pip._internal.cli.cmdoptions._handle_src (Option option, str opt_str, str value, OptionParser parser) protected
Definition at line 446 of file cmdoptions.py.
def _handle_src(option: Option, opt_str: str, value: str, parser: OptionParser) -> None:
    value = os.path.abspath(value)
    setattr(parser.values, option.dest, value)
_package_name_option_check()
str pip._internal.cli.cmdoptions._package_name_option_check (Option option, str opt, str value) protected
Definition at line 106 of file cmdoptions.py.
def _package_name_option_check(option: Option, opt: str, value: str) -> str:
    return canonicalize_name(value)
_path_option_check()
str pip._internal.cli.cmdoptions._path_option_check (Option option, str opt, str value) protected
Definition at line 102 of file cmdoptions.py.
def _path_option_check(option: Option, opt: str, value: str) -> str:
    return os.path.expanduser(value)
add_target_python_options()
None pip._internal.cli.cmdoptions.add_target_python_options (OptionGroup cmd_opts)
Definition at line 646 of file cmdoptions.py.
def add_target_python_options(cmd_opts: OptionGroup) -> None:
    cmd_opts.add_option(platforms())
    cmd_opts.add_option(python_version())
    cmd_opts.add_option(implementation())
    cmd_opts.add_option(abis())
References abis, implementation, platforms, and python_version.
check_dist_restriction()
None pip._internal.cli.cmdoptions.check_dist_restriction (Values options, bool check_target = False)
Function for determining if custom platform options are allowed.
:param options: The OptionParser options.
:param check_target: Whether or not to check if --target is being used.
Definition at line 62 of file cmdoptions.py.
def check_dist_restriction(options: Values, check_target: bool = False) -> None:
    """Function for determining if custom platform options are allowed.
    :param options: The OptionParser options.
    :param check_target: Whether or not to check if --target is being used.
    """
    dist_restriction_set = any(
        [
            options.python_version,
            options.platforms,
            options.abis,
            options.implementation,
        ]
    )
    binary_only = FormatControl(set(), {":all:"})
    sdist_dependencies_allowed = (
        options.format_control != binary_only and not options.ignore_dependencies
    )
    # Installations or downloads using dist restrictions must not combine
    # source distributions and dist-specific wheels, as they are not
    # guaranteed to be locally compatible.
    if dist_restriction_set and sdist_dependencies_allowed:
        raise CommandError(
            "When restricting platform and interpreter constraints using "
            "--python-version, --platform, --abi, or --implementation, "
            "either --no-deps must be set, or --only-binary=:all: must be "
            "set and --no-binary must not be set (or must be set to "
            ":none:)."
        )
    if check_target:
        if not options.dry_run and dist_restriction_set and not options.target_dir:
            raise CommandError(
                "Can not use any platform or abi specific options unless "
                "installing via '--target' or using '--dry-run'"
            )
check_list_path_option()
None pip._internal.cli.cmdoptions.check_list_path_option (Values options)
Definition at line 971 of file cmdoptions.py.
def check_list_path_option(options: Values) -> None:
    if options.path and (options.user or options.local):
        raise CommandError("Cannot combine '--path' with '--user' or '--local'")
constraints()
Option pip._internal.cli.cmdoptions.constraints ()
Definition at line 405 of file cmdoptions.py.
def constraints() -> Option:
    return Option(
        "-c",
        "--constraint",
        dest="constraints",
        action="append",
        default=[],
        metavar="file",
        help="Constrain versions using the given constraints file. "
        "This option can be used multiple times.",
    )
editable()
Option pip._internal.cli.cmdoptions.editable ()
Definition at line 431 of file cmdoptions.py.
def editable() -> Option:
    return Option(
        "-e",
        "--editable",
        dest="editables",
        action="append",
        default=[],
        metavar="path/url",
        help=(
            "Install a project in editable mode (i.e. setuptools "
            '"develop mode") from a local project path or a VCS url.'
        ),
    )
exists_action()
Option pip._internal.cli.cmdoptions.exists_action ()
Definition at line 299 of file cmdoptions.py.
def exists_action() -> Option:
    return Option(
        # Option when path already exist
        "--exists-action",
        dest="exists_action",
        type="choice",
        choices=["s", "i", "w", "b", "a"],
        default=[],
        action="append",
        metavar="action",
        help="Default action when a path already exists: "
        "(s)witch, (i)gnore, (w)ipe, (b)ackup, (a)bort.",
    )
extra_index_url()
Option pip._internal.cli.cmdoptions.extra_index_url ()
Definition at line 354 of file cmdoptions.py.
def extra_index_url() -> Option:
    return Option(
        "--extra-index-url",
        dest="extra_index_urls",
        metavar="URL",
        action="append",
        default=[],
        help="Extra URLs of package indexes to use in addition to "
        "--index-url. Should follow the same rules as "
        "--index-url.",
    )
find_links()
Option pip._internal.cli.cmdoptions.find_links ()
Definition at line 377 of file cmdoptions.py.
def find_links() -> Option:
    return Option(
        "-f",
        "--find-links",
        dest="find_links",
        action="append",
        default=[],
        metavar="url",
        help="If a URL or path to an html file, then parse for links to "
        "archives such as sdist (.tar.gz) or wheel (.whl) files. "
        "If a local path or file:// URL that's a directory, "
        "then look for archives in the directory listing. "
        "Links to VCS project URLs are not supported.",
    )
make_option_group()
OptionGroup pip._internal.cli.cmdoptions.make_option_group (Dict[str, Any] group, ConfigOptionParser parser)
Return an OptionGroup object
group  -- assumed to be dict with 'name' and 'options' keys
parser -- an optparse Parser
Definition at line 50 of file cmdoptions.py.
def make_option_group(group: Dict[str, Any], parser: ConfigOptionParser) -> OptionGroup:
    """
    Return an OptionGroup object
    group  -- assumed to be dict with 'name' and 'options' keys
    parser -- an optparse Parser
    """
    option_group = OptionGroup(parser, group["name"])
    for option in group["options"]:
        option_group.add_option(option())
    return option_group
make_target_python()
TargetPython pip._internal.cli.cmdoptions.make_target_python (Values options)
Definition at line 653 of file cmdoptions.py.
def make_target_python(options: Values) -> TargetPython:
    target_python = TargetPython(
        platforms=options.platforms,
        py_version_info=options.python_version,
        abis=options.abis,
        implementation=options.implementation,
    )
    return target_python
no_binary()
Option pip._internal.cli.cmdoptions.no_binary ()
Definition at line 496 of file cmdoptions.py.
def no_binary() -> Option:
    format_control = FormatControl(set(), set())
    return Option(
        "--no-binary",
        dest="format_control",
        action="callback",
        callback=_handle_no_binary,
        type="str",
        default=format_control,
        help="Do not use binary packages. Can be supplied multiple times, and "
        'each time adds to the existing value. Accepts either ":all:" to '
        'disable all binary packages, ":none:" to empty the set (notice '
        "the colons), or one or more package names with commas between "
        "them (no colons). Note that some packages are tricky to compile "
        "and may fail to install when this option is used on them.",
    )
only_binary()
Option pip._internal.cli.cmdoptions.only_binary ()
Definition at line 514 of file cmdoptions.py.
def only_binary() -> Option:
    format_control = FormatControl(set(), set())
    return Option(
        "--only-binary",
        dest="format_control",
        action="callback",
        callback=_handle_only_binary,
        type="str",
        default=format_control,
        help="Do not use source packages. Can be supplied multiple times, and "
        'each time adds to the existing value. Accepts either ":all:" to '
        'disable all source packages, ":none:" to empty the set, or one '
        "or more package names with commas between them. Packages "
        "without binary distributions will fail to install when this "
        "option is used on them.",
    )
prefer_binary()
Option pip._internal.cli.cmdoptions.prefer_binary ()
Definition at line 664 of file cmdoptions.py.
def prefer_binary() -> Option:
    return Option(
        "--prefer-binary",
        dest="prefer_binary",
        action="store_true",
        default=False,
        help=(
            "Prefer binary packages over source packages, even if the "
            "source packages are newer."
        ),
    )
raise_option_error()
None pip._internal.cli.cmdoptions.raise_option_error (OptionParser parser, Option option, str msg)
Raise an option parsing error using parser.error().
Args:
  parser: an OptionParser instance.
  option: an Option instance.
  msg: the error text.
Definition at line 36 of file cmdoptions.py.
def raise_option_error(parser: OptionParser, option: Option, msg: str) -> None:
    """
    Raise an option parsing error using parser.error().
    Args:
      parser: an OptionParser instance.
      option: an Option instance.
      msg: the error text.
    """
    msg = f"{option} error: {msg}"
    msg = textwrap.fill(" ".join(msg.split()))
    parser.error(msg)
Referenced by _handle_no_cache_dir(), _handle_no_use_pep517(), and _handle_python_version().
requirements()
Option pip._internal.cli.cmdoptions.requirements ()
Definition at line 418 of file cmdoptions.py.
def requirements() -> Option:
    return Option(
        "-r",
        "--requirement",
        dest="requirements",
        action="append",
        default=[],
        metavar="file",
        help="Install from the given requirements file. "
        "This option can be used multiple times.",
    )
trusted_host()
Option pip._internal.cli.cmdoptions.trusted_host ()
Definition at line 393 of file cmdoptions.py.
def trusted_host() -> Option:
    return Option(
        "--trusted-host",
        dest="trusted_hosts",
        action="append",
        metavar="HOSTNAME",
        default=[],
        help="Mark this host or host:port pair as trusted, even though it "
        "does not have valid or any HTTPS.",
    )
Variable Documentation
abis
Callable pip._internal.cli.cmdoptions.abis
Initial value:
=  partial(
    Option,
    "--abi",
    dest="abis",
    metavar="abi",
    action="append",
    default=None,
    help=(
        "Only use wheels compatible with Python abi <abi>, e.g. 'pypy_41'. "
        "If not specified, then the current interpreter abi tag is used. "
        "Use this option multiple times to specify multiple abis supported "
        "by the target interpreter. Generally you will need to specify "
        "--implementation, --platform, and --python-version when using this "
        "option."
    ),
)
Definition at line 628 of file cmdoptions.py.
Referenced by add_target_python_options().
ALWAYS_ENABLED_FEATURES
list pip._internal.cli.cmdoptions.ALWAYS_ENABLED_FEATURES
Initial value:
=  [
    "truststore",  # always on since 24.2
    "no-binary-enable-wheel-cache",  # always on since 23.1
]
Definition at line 998 of file cmdoptions.py.
build_options
Callable pip._internal.cli.cmdoptions.build_options
Initial value:
=  partial(
    Option,
    "--build-option",
    dest="build_options",
    metavar="options",
    action="append",
    help="Extra arguments to be supplied to 'setup.py bdist_wheel'.",
)
Definition at line 854 of file cmdoptions.py.
cache_dir
Callable pip._internal.cli.cmdoptions.cache_dir
Initial value:
=  partial(
    PipOption,
    "--cache-dir",
    dest="cache_dir",
    default=USER_CACHE_DIR,
    metavar="dir",
    type="path",
    help="Store the cache data in <dir>.",
)
Definition at line 677 of file cmdoptions.py.
cert
Callable pip._internal.cli.cmdoptions.cert
Initial value:
=  partial(
    PipOption,
    "--cert",
    dest="cert",
    type="path",
    metavar="path",
    help=(
        "Path to PEM-encoded CA certificate bundle. "
        "If provided, overrides the default. "
        "See 'SSL Certificate Verification' in pip documentation "
        "for more information."
    ),
)
Definition at line 314 of file cmdoptions.py.
check_build_deps
Callable pip._internal.cli.cmdoptions.check_build_deps
Initial value:
=  partial(
    Option,
    "--check-build-dependencies",
    dest="check_build_deps",
    action="store_true",
    default=False,
    help="Check the build dependencies when PEP517 is used.",
)
Definition at line 755 of file cmdoptions.py.
client_cert
Callable pip._internal.cli.cmdoptions.client_cert
Initial value:
=  partial(
    PipOption,
    "--client-cert",
    dest="client_cert",
    type="path",
    default=None,
    metavar="path",
    help="Path to SSL client certificate, a single file containing the "
    "private key and the certificate in PEM format.",
)
Definition at line 328 of file cmdoptions.py.
config_settings
Callable pip._internal.cli.cmdoptions.config_settings
Initial value:
=  partial(
    Option,
    "-C",
    "--config-settings",
    dest="config_settings",
    type=str,
    action="callback",
    callback=_handle_config_settings,
    metavar="settings",
    help="Configuration settings to be passed to the PEP 517 build backend. "
    "Settings take the form KEY=VALUE. Use multiple --config-settings options "
    "to pass multiple keys to the backend.",
)
Definition at line 840 of file cmdoptions.py.
disable_pip_version_check
Callable pip._internal.cli.cmdoptions.disable_pip_version_check
Initial value:
=  partial(
    Option,
    "--disable-pip-version-check",
    dest="disable_pip_version_check",
    action="store_true",
    default=False,
    help="Don't periodically check PyPI to determine whether a new version "
    "of pip is available for download. Implied with --no-index.",
)
Definition at line 890 of file cmdoptions.py.
general_group
dict pip._internal.cli.cmdoptions.general_group
Initial value:
=  {
    "name": "General Options",
    "options": [
        help_,
        debug_mode,
        isolated_mode,
        require_virtualenv,
        python,
        verbose,
        version,
        quiet,
        log,
        no_input,
        keyring_provider,
        proxy,
        retries,
        timeout,
        exists_action,
        trusted_host,
        cert,
        client_cert,
        cache_dir,
        no_cache,
        disable_pip_version_check,
        no_color,
        no_python_version_warning,
        use_new_feature,
        use_deprecated_feature,
    ],
}
groups #
Definition at line 1036 of file cmdoptions.py.
global_options
Callable pip._internal.cli.cmdoptions.global_options
Initial value:
=  partial(
    Option,
    "--global-option",
    dest="global_options",
    action="append",
    metavar="options",
    help="Extra global options to be supplied to the setup.py "
    "call before the install or bdist_wheel command.",
)
Definition at line 863 of file cmdoptions.py.
hash
Callable pip._internal.cli.cmdoptions.hash
Initial value:
=  partial(
    Option,
    "--hash",
    # Hash values eventually end up in InstallRequirement.hashes due to
    # __dict__ copying in process_line().
    dest="hashes",
    action="callback",
    callback=_handle_merge_hash,
    type="string",
    help="Verify that the package's archive matches this "
    "hash before installing. Example: --hash=sha256:abcdef...",
)
Definition at line 934 of file cmdoptions.py.
ignore_requires_python
Callable pip._internal.cli.cmdoptions.ignore_requires_python
Initial value:
=  partial(
    Option,
    "--ignore-requires-python",
    dest="ignore_requires_python",
    action="store_true",
    help="Ignore the Requires-Python information.",
)
Definition at line 736 of file cmdoptions.py.
implementation
Callable pip._internal.cli.cmdoptions.implementation
Initial value:
=  partial(
    Option,
    "--implementation",
    dest="implementation",
    metavar="implementation",
    default=None,
    help=(
        "Only use wheels compatible with Python "
        "implementation <implementation>, e.g. 'pp', 'jy', 'cp', "
        " or 'ip'. If not specified, then the current "
        "interpreter implementation is used.  Use 'py' to force "
        "implementation-agnostic wheels."
    ),
)
Definition at line 612 of file cmdoptions.py.
Referenced by add_target_python_options().
index_group
dict pip._internal.cli.cmdoptions.index_group
Initial value:
=  {
    "name": "Package Index Options",
    "options": [
        index_url,
        extra_index_url,
        no_index,
        find_links,
    ],
}
Definition at line 1067 of file cmdoptions.py.
index_url
Callable pip._internal.cli.cmdoptions.index_url
Initial value:
=  partial(
    Option,
    "-i",
    "--index-url",
    "--pypi-url",
    dest="index_url",
    metavar="URL",
    default=PyPI.simple_url,
    help="Base URL of the Python Package Index (default %default). "
    "This should point to a repository compliant with PEP 503 "
    "(the simple repository API) or a local directory laid out "
    "in the same format.",
)
Definition at line 339 of file cmdoptions.py.
list_exclude
Callable pip._internal.cli.cmdoptions.list_exclude
Initial value:
=  partial(
    PipOption,
    "--exclude",
    dest="excludes",
    action="append",
    metavar="package",
    type="package_name",
    help="Exclude specified package from the output",
)
Definition at line 976 of file cmdoptions.py.
list_path
Callable pip._internal.cli.cmdoptions.list_path
Initial value:
=  partial(
    PipOption,
    "--path",
    dest="path",
    type="path",
    action="append",
    help="Restrict to the specified installation path for listing "
    "packages (can be used multiple times).",
)
Definition at line 960 of file cmdoptions.py.
logger
pip._internal.cli.cmdoptions.logger = logging.getLogger(__name__)
Definition at line 33 of file cmdoptions.py.
no_build_isolation
Callable pip._internal.cli.cmdoptions.no_build_isolation
Initial value:
=  partial(
    Option,
    "--no-build-isolation",
    dest="build_isolation",
    action="store_false",
    default=True,
    help="Disable isolation when building a modern source distribution. "
    "Build dependencies specified by PEP 518 must be already installed "
    "if this option is used.",
)
Definition at line 744 of file cmdoptions.py.
no_cache
Callable pip._internal.cli.cmdoptions.no_cache
Initial value:
=  partial(
    Option,
    "--no-cache-dir",
    dest="cache_dir",
    action="callback",
    callback=_handle_no_cache_dir,
    help="Disable the cache.",
)
Definition at line 717 of file cmdoptions.py.
no_clean
Callable pip._internal.cli.cmdoptions.no_clean
Initial value:
=  partial(
    Option,
    "--no-clean",
    action="store_true",
    default=False,
    help="Don't clean up build directories.",
)
Definition at line 873 of file cmdoptions.py.
no_deps
Callable pip._internal.cli.cmdoptions.no_deps
Initial value:
=  partial(
    Option,
    "--no-deps",
    "--no-dependencies",
    dest="ignore_dependencies",
    action="store_true",
    default=False,
    help="Don't install package dependencies.",
)
Definition at line 726 of file cmdoptions.py.
no_index
Callable pip._internal.cli.cmdoptions.no_index
Initial value:
=  partial(
    Option,
    "--no-index",
    dest="no_index",
    action="store_true",
    default=False,
    help="Ignore package index (only looking at --find-links URLs instead).",
)
Definition at line 367 of file cmdoptions.py.
no_python_version_warning
Callable pip._internal.cli.cmdoptions.no_python_version_warning
Initial value:
=  partial(
    Option,
    "--no-python-version-warning",
    dest="no_python_version_warning",
    action="store_true",
    default=False,
    help="Silence deprecation warnings for upcoming unsupported Pythons.",
)
Definition at line 987 of file cmdoptions.py.
no_use_pep517
Any pip._internal.cli.cmdoptions.no_use_pep517
Initial value:
=  partial(
    Option,
    "--no-use-pep517",
    dest="use_pep517",
    action="callback",
    callback=_handle_no_use_pep517,
    default=None,
    help=SUPPRESS_HELP,
)
Definition at line 810 of file cmdoptions.py.
platforms
Callable pip._internal.cli.cmdoptions.platforms
Initial value:
=  partial(
    Option,
    "--platform",
    dest="platforms",
    metavar="platform",
    action="append",
    default=None,
    help=(
        "Only use wheels compatible with <platform>. Defaults to the "
        "platform of the running system. Use this option multiple times to "
        "specify multiple platforms supported by the target interpreter."
    ),
)
Definition at line 532 of file cmdoptions.py.
Referenced by add_target_python_options().
pre
Callable pip._internal.cli.cmdoptions.pre
Initial value:
=  partial(
    Option,
    "--pre",
    action="store_true",
    default=False,
    help="Include pre-release and development versions. By default, "
    "pip only finds stable versions.",
)
Definition at line 881 of file cmdoptions.py.
python_version
Callable pip._internal.cli.cmdoptions.python_version
Initial value:
=  partial(
    Option,
    "--python-version",
    dest="python_version",
    metavar="python_version",
    action="callback",
    callback=_handle_python_version,
    type="str",
    default=None,
    help=dedent(
    ),
)
Definition at line 591 of file cmdoptions.py.
Referenced by add_target_python_options().
require_hashes
Callable pip._internal.cli.cmdoptions.require_hashes
Initial value:
=  partial(
    Option,
    "--require-hashes",
    dest="require_hashes",
    action="store_true",
    default=False,
    help="Require a hash to check each requirement against, for "
    "repeatable installs. This option is implied when any package in a "
    "requirements file has a --hash option.",
)
Definition at line 948 of file cmdoptions.py.
root_user_action
Callable pip._internal.cli.cmdoptions.root_user_action
Initial value:
=  partial(
    Option,
    "--root-user-action",
    dest="root_user_action",
    default="warn",
    choices=["warn", "ignore"],
    help="Action if pip is run as a root user [warn, ignore] (default: warn)",
)
Definition at line 900 of file cmdoptions.py.
src
Callable pip._internal.cli.cmdoptions.src
Initial value:
=  partial(
    PipOption,
    "--src",
    "--source",
    "--source-dir",
    "--source-directory",
    dest="src_dir",
    type="path",
    metavar="dir",
    default=get_src_prefix(),
    action="callback",
    callback=_handle_src,
    help="Directory to check out editable projects into. "
    'The default in a virtualenv is "<venv path>/src". '
    'The default for global installs is "<current dir>/src".',
)
Definition at line 451 of file cmdoptions.py.
use_deprecated_feature
Callable pip._internal.cli.cmdoptions.use_deprecated_feature
Initial value:
=  partial(
    Option,
    "--use-deprecated",
    dest="deprecated_features_enabled",
    metavar="feature",
    action="append",
    default=[],
    choices=[
        "legacy-resolver",
        "legacy-certs",
    ],
    help=("Enable deprecated functionality, that will be removed in the future."),
)
Definition at line 1017 of file cmdoptions.py.
use_new_feature
Callable pip._internal.cli.cmdoptions.use_new_feature
Initial value:
=  partial(
    Option,
    "--use-feature",
    dest="features_enabled",
    metavar="feature",
    action="append",
    default=[],
    choices=[
        "fast-deps",
    ]
    + ALWAYS_ENABLED_FEATURES,
    help="Enable new functionality, that may be backward incompatible.",
)
Definition at line 1003 of file cmdoptions.py.
use_pep517
Any pip._internal.cli.cmdoptions.use_pep517
Initial value:
=  partial(
    Option,
    "--use-pep517",
    dest="use_pep517",
    action="store_true",
    default=None,
    help="Use PEP 517 for building source distributions "
    "(use --no-use-pep517 to force legacy behaviour).",
)
Definition at line 800 of file cmdoptions.py.