Read&Watch: dotenv.main Namespace Reference
dotenv.main Namespace Reference
Classes
class DotEnv
Functions
Iterator[Binding] with_warn_for_invalid_lines (Iterator[Binding] mappings)
Optional[str] get_key (StrPath dotenv_path, str key_to_get, Optional[str] encoding="utf-8")
Iterator[Tuple[IO[str], IO[str]]] rewrite (StrPath path, Optional[str] encoding)
Tuple[Optional[bool], str, str] set_key (StrPath dotenv_path, str key_to_set, str value_to_set, str quote_mode="always", bool export=False, Optional[str] encoding="utf-8")
Tuple[Optional[bool], str] unset_key (StrPath dotenv_path, str key_to_unset, str quote_mode="always", Optional[str] encoding="utf-8")
Mapping[str, Optional[str]] resolve_variables (Iterable[Tuple[str, Optional[str]]] values, bool override)
Iterator[str] _walk_to_root (str path)
str find_dotenv (str filename='.env', bool raise_error_if_not_found=False, bool usecwd=False)
bool load_dotenv (Optional[StrPath] dotenv_path=None, Optional[IO[str]] stream=None, bool verbose=False, bool override=False, bool interpolate=True, Optional[str] encoding="utf-8")
Dict[str, Optional[str]] dotenv_values (Optional[StrPath] dotenv_path=None, Optional[IO[str]] stream=None, bool verbose=False, bool interpolate=True, Optional[str] encoding="utf-8")
Variables
StrPath = Union[str, 'os.PathLike[str]']
logger = logging.getLogger(__name__)
Function Documentation
_walk_to_root()
Iterator[str] dotenv.main._walk_to_root (str path) protected
Yield directories starting from the given directory up to the root
Definition at line 257 of file main.py.
def _walk_to_root(path: str) -> Iterator[str]:
    """
    Yield directories starting from the given directory up to the root
    """
    if not os.path.exists(path):
        raise IOError('Starting path not found')
    if os.path.isfile(path):
        path = os.path.dirname(path)
    last_dir = None
    current_dir = os.path.abspath(path)
    while last_dir != current_dir:
        yield current_dir
        parent_dir = os.path.abspath(os.path.join(current_dir, os.path.pardir))
        last_dir, current_dir = current_dir, parent_dir
Referenced by find_dotenv().
dotenv_values()
Dict[str, Optional[str]] dotenv.main.dotenv_values (Optional[StrPath] dotenv_path = None, Optional[IO[str]] stream = None, bool verbose = False, bool interpolate = True, Optional[str] encoding = "utf-8")
Parse a .env file and return its content as a dict.
The returned dict will have `None` values for keys without values in the .env file.
For example, `foo=bar` results in `{"foo": "bar"}` whereas `foo` alone results in
`{"foo": None}`
Parameters:
    dotenv_path: Absolute or relative path to the .env file.
    stream: `StringIO` object with .env content, used if `dotenv_path` is `None`.
    verbose: Whether to output a warning if the .env file is missing.
    encoding: Encoding to be used to read the file.
If both `dotenv_path` and `stream` are `None`, `find_dotenv()` is used to find the
.env file.
Definition at line 359 of file main.py.
) -> Dict[str, Optional[str]]:
    """
    Parse a .env file and return its content as a dict.
    The returned dict will have `None` values for keys without values in the .env file.
    For example, `foo=bar` results in `{"foo": "bar"}` whereas `foo` alone results in
    `{"foo": None}`
    Parameters:
        dotenv_path: Absolute or relative path to the .env file.
        stream: `StringIO` object with .env content, used if `dotenv_path` is `None`.
        verbose: Whether to output a warning if the .env file is missing.
        encoding: Encoding to be used to read the file.
    If both `dotenv_path` and `stream` are `None`, `find_dotenv()` is used to find the
    .env file.
    """
    if dotenv_path is None and stream is None:
        dotenv_path = find_dotenv()
    return DotEnv(
        dotenv_path=dotenv_path,
        stream=stream,
        verbose=verbose,
        interpolate=interpolate,
        override=True,
        encoding=encoding,
    ).dict()
References find_dotenv().
find_dotenv()
str dotenv.main.find_dotenv (str filename = '.env', bool raise_error_if_not_found = False, bool usecwd = False)
Search in increasingly higher folders for the given file
Returns path to the file if found, or an empty string otherwise
Definition at line 275 of file main.py.
) -> str:
    """
    Search in increasingly higher folders for the given file
    Returns path to the file if found, or an empty string otherwise
    """
    def _is_interactive():
        """ Decide whether this is running in a REPL or IPython notebook """
        try:
            main = __import__('__main__', None, None, fromlist=['__file__'])
        except ModuleNotFoundError:
            return False
        return not hasattr(main, '__file__')
    if usecwd or _is_interactive() or getattr(sys, 'frozen', False):
        # Should work without __file__, e.g. in REPL or IPython notebook.
        path = os.getcwd()
    else:
        # will work for .py files
        frame = sys._getframe()
        current_file = __file__
        while frame.f_code.co_filename == current_file or not os.path.exists(
            frame.f_code.co_filename
        ):
            assert frame.f_back is not None
            frame = frame.f_back
        frame_filename = frame.f_code.co_filename
        path = os.path.dirname(os.path.abspath(frame_filename))
    for dirname in _walk_to_root(path):
        check_path = os.path.join(dirname, filename)
        if os.path.isfile(check_path):
            return check_path
    if raise_error_if_not_found:
        raise IOError('File not found')
    return ''
References _walk_to_root().
Referenced by dotenv_values(), and load_dotenv().
get_key()
Optional[str] dotenv.main.get_key (StrPath dotenv_path, str key_to_get, Optional[str] encoding = "utf-8")
Get the value of a given key from the given .env.
Returns `None` if the key isn't found or doesn't have a value.
Definition at line 117 of file main.py.
) -> Optional[str]:
    """
    Get the value of a given key from the given .env.
    Returns `None` if the key isn't found or doesn't have a value.
    """
    return DotEnv(dotenv_path, verbose=True, encoding=encoding).get(key_to_get)
@contextmanager
load_dotenv()
bool dotenv.main.load_dotenv (Optional[StrPath] dotenv_path = None, Optional[IO[str]] stream = None, bool verbose = False, bool override = False, bool interpolate = True, Optional[str] encoding = "utf-8")
Parse a .env file and then load all the variables found as environment variables.
Parameters:
    dotenv_path: Absolute or relative path to .env file.
    stream: Text stream (such as `io.StringIO`) with .env content, used if
        `dotenv_path` is `None`.
    verbose: Whether to output a warning the .env file is missing.
    override: Whether to override the system environment variables with the variables
        from the `.env` file.
    encoding: Encoding to be used to read the file.
Returns:
    Bool: True if at least one environment variable is set else False
If both `dotenv_path` and `stream` are `None`, `find_dotenv()` is used to find the
.env file.
Definition at line 321 of file main.py.
) -> bool:
    """Parse a .env file and then load all the variables found as environment variables.
    Parameters:
        dotenv_path: Absolute or relative path to .env file.
        stream: Text stream (such as `io.StringIO`) with .env content, used if
            `dotenv_path` is `None`.
        verbose: Whether to output a warning the .env file is missing.
        override: Whether to override the system environment variables with the variables
            from the `.env` file.
        encoding: Encoding to be used to read the file.
    Returns:
        Bool: True if at least one environment variable is set else False
    If both `dotenv_path` and `stream` are `None`, `find_dotenv()` is used to find the
    .env file.
    """
    if dotenv_path is None and stream is None:
        dotenv_path = find_dotenv()
    dotenv = DotEnv(
        dotenv_path=dotenv_path,
        stream=stream,
        verbose=verbose,
        interpolate=interpolate,
        override=override,
        encoding=encoding,
    )
    return dotenv.set_as_environment_variables()
References find_dotenv().
resolve_variables()
Mapping[str, Optional[str]] dotenv.main.resolve_variables (Iterable[Tuple[str, Optional[str]]] values, bool override)
Definition at line 232 of file main.py.
) -> Mapping[str, Optional[str]]:
    new_values: Dict[str, Optional[str]] = {}
    for (name, value) in values:
        if value is None:
            result = None
        else:
            atoms = parse_variables(value)
            env: Dict[str, Optional[str]] = {}
            if override:
                env.update(os.environ)  # type: ignore
                env.update(new_values)
            else:
                env.update(new_values)
                env.update(os.environ)  # type: ignore
            result = "".join(atom.resolve(env) for atom in atoms)
        new_values[name] = result
    return new_values
Referenced by dotenv.main.DotEnv.dict().
rewrite()
Iterator[Tuple[IO[str], IO[str]]] dotenv.main.rewrite (StrPath path, Optional[str] encoding)
Definition at line 131 of file main.py.
) -> Iterator[Tuple[IO[str], IO[str]]]:
    pathlib.Path(path).touch()
    with tempfile.NamedTemporaryFile(mode="w", encoding=encoding, delete=False) as dest:
        error = None
        try:
            with open(path, encoding=encoding) as source:
                yield (source, dest)
        except BaseException as err:
            error = err
    if error is None:
        shutil.move(dest.name, path)
    else:
        os.unlink(dest.name)
        raise error from None
Referenced by set_key(), and unset_key().
set_key()
Tuple[Optional[bool], str, str] dotenv.main.set_key (StrPath dotenv_path, str key_to_set, str value_to_set, str quote_mode = "always", bool export = False, Optional[str] encoding = "utf-8")
Adds or Updates a key/value to the given .env
If the .env path given doesn't exist, fails instead of risking creating
an orphan .env somewhere in the filesystem
Definition at line 152 of file main.py.
) -> Tuple[Optional[bool], str, str]:
    """
    Adds or Updates a key/value to the given .env
    If the .env path given doesn't exist, fails instead of risking creating
    an orphan .env somewhere in the filesystem
    """
    if quote_mode not in ("always", "auto", "never"):
        raise ValueError(f"Unknown quote_mode: {quote_mode}")
    quote = (
        quote_mode == "always"
        or (quote_mode == "auto" and not value_to_set.isalnum())
    )
    if quote:
        value_out = "'{}'".format(value_to_set.replace("'", "\\'"))
    else:
        value_out = value_to_set
    if export:
        line_out = f'export {key_to_set}={value_out}\n'
    else:
        line_out = f"{key_to_set}={value_out}\n"
    with rewrite(dotenv_path, encoding=encoding) as (source, dest):
        replaced = False
        missing_newline = False
        for mapping in with_warn_for_invalid_lines(parse_stream(source)):
            if mapping.key == key_to_set:
                dest.write(line_out)
                replaced = True
            else:
                dest.write(mapping.original.string)
                missing_newline = not mapping.original.string.endswith("\n")
        if not replaced:
            if missing_newline:
                dest.write("\n")
            dest.write(line_out)
    return True, key_to_set, value_to_set
References rewrite(), and with_warn_for_invalid_lines().
unset_key()
Tuple[Optional[bool], str] dotenv.main.unset_key (StrPath dotenv_path, str key_to_unset, str quote_mode = "always", Optional[str] encoding = "utf-8")
Removes a given key from the given `.env` file.
If the .env path given doesn't exist, fails.
If the given key doesn't exist in the .env, fails.
Definition at line 201 of file main.py.
) -> Tuple[Optional[bool], str]:
    """
    Removes a given key from the given `.env` file.
    If the .env path given doesn't exist, fails.
    If the given key doesn't exist in the .env, fails.
    """
    if not os.path.exists(dotenv_path):
        logger.warning("Can't delete from %s - it doesn't exist.", dotenv_path)
        return None, key_to_unset
    removed = False
    with rewrite(dotenv_path, encoding=encoding) as (source, dest):
        for mapping in with_warn_for_invalid_lines(parse_stream(source)):
            if mapping.key == key_to_unset:
                removed = True
            else:
                dest.write(mapping.original.string)
    if not removed:
        logger.warning("Key %s not removed from %s - key doesn't exist.", key_to_unset, dotenv_path)
        return None, key_to_unset
    return removed, key_to_unset
References rewrite(), and with_warn_for_invalid_lines().
with_warn_for_invalid_lines()
Iterator[Binding] dotenv.main.with_warn_for_invalid_lines (Iterator[Binding] mappings)
Definition at line 25 of file main.py.
def with_warn_for_invalid_lines(mappings: Iterator[Binding]) -> Iterator[Binding]:
    for mapping in mappings:
        if mapping.error:
            logger.warning(
                "Python-dotenv could not parse statement starting at line %s",
                mapping.original.line,
            )
        yield mapping
Referenced by dotenv.main.DotEnv.parse(), set_key(), and unset_key().
Variable Documentation
logger
dotenv.main.logger = logging.getLogger(__name__)
Definition at line 22 of file main.py.
StrPath
dotenv.main.StrPath = Union[str, 'os.PathLike[str]']
Definition at line 20 of file main.py.