Read&Watch: django.test.testcases Namespace Reference
django.test.testcases Namespace Reference
Classes
class _AssertNumQueriesContext
class _AssertTemplateNotUsedContext
class _AssertTemplateUsedContext
class _DatabaseFailure
class _MediaFilesHandler
class _StaticFilesHandler
class CheckCondition
class DatabaseOperationForbidden
class FSFilesHandler
class LiveServerTestCase
class LiveServerThread
class QuietWSGIRequestHandler
class SerializeMixin
class SimpleTestCase
class TestCase
class TestData
class TransactionTestCase
Functions
_enter_context (cm, addcleanup)
to_list (value)
is_pickable (obj)
assert_and_parse_html (self, html, user_msg, msg)
connections_support_transactions (aliases=None)
connections_support_savepoints (aliases=None)
_deferredSkip (condition, reason, name)
skipIfDBFeature (*features)
skipUnlessDBFeature (*features)
skipUnlessAnyDBFeature (*features)
Variables
logger = logging.getLogger("django.test")
Function Documentation
_deferredSkip()
django.test.testcases._deferredSkip (condition, reason, name) protected
Definition at line 1522 of file testcases.py.
def _deferredSkip(condition, reason, name):
    def decorator(test_func):
        nonlocal condition
        if not (
            isinstance(test_func, type) and issubclass(test_func, unittest.TestCase)
        ):
            @wraps(test_func)
            def skip_wrapper(*args, **kwargs):
                if (
                    args
                    and isinstance(args[0], unittest.TestCase)
                    and connection.alias not in getattr(args[0], "databases", {})
                ):
                    raise ValueError(
                        "%s cannot be used on %s as %s doesn't allow queries "
                        "against the %r database."
                        % (
                            name,
                            args[0],
                            args[0].__class__.__qualname__,
                            connection.alias,
                        )
                    )
                if condition():
                    raise unittest.SkipTest(reason)
                return test_func(*args, **kwargs)
            test_item = skip_wrapper
        else:
            # Assume a class is decorated
            test_item = test_func
            databases = getattr(test_item, "databases", None)
            if not databases or connection.alias not in databases:
                # Defer raising to allow importing test class's module.
                def condition():
                    raise ValueError(
                        "%s cannot be used on %s as it doesn't allow queries "
                        "against the '%s' database."
                        % (
                            name,
                            test_item,
                            connection.alias,
                        )
                    )
            # Retrieve the possibly existing value from the class's dict to
            # avoid triggering the descriptor.
            skip = test_func.__dict__.get("__unittest_skip__")
            if isinstance(skip, CheckCondition):
                test_item.__unittest_skip__ = skip.add_condition(condition, reason)
            elif skip is not True:
                test_item.__unittest_skip__ = CheckCondition((condition, reason))
        return test_item
    return decorator
Referenced by skipIfDBFeature(), skipUnlessAnyDBFeature(), and skipUnlessDBFeature().
_enter_context()
django.test.testcases._enter_context (cm, addcleanup) protected
Definition at line 73 of file testcases.py.
    def _enter_context(cm, addcleanup):
        # Look up the special methods on the type to match the with statement.
        cls = type(cm)
        try:
            enter = cls.__enter__
            exit = cls.__exit__
        except AttributeError:
            raise TypeError(
                f"'{cls.__module__}.{cls.__qualname__}' object does not support the "
                f"context manager protocol"
            ) from None
        result = enter(cm)
        addcleanup(exit, cm, None, None, None)
        return result
assert_and_parse_html()
django.test.testcases.assert_and_parse_html (self, html, user_msg, msg)
Definition at line 108 of file testcases.py.
def assert_and_parse_html(self, html, user_msg, msg):
    try:
        dom = parse_html(html)
    except HTMLParseError as e:
        standardMsg = "%s\n%s" % (msg, e)
        self.fail(self._formatMessage(user_msg, standardMsg))
    return dom
Referenced by django.test.testcases.SimpleTestCase._assert_contains(), django.test.testcases.SimpleTestCase.assertHTMLEqual(), django.test.testcases.SimpleTestCase.assertHTMLNotEqual(), and django.test.testcases.SimpleTestCase.assertInHTML().
connections_support_savepoints()
django.test.testcases.connections_support_savepoints (aliases = None)
Return whether or not all (or specified) connections support savepoints.
Definition at line 1286 of file testcases.py.
def connections_support_savepoints(aliases=None):
    """
    Return whether or not all (or specified) connections support savepoints.
    """
    conns = (
        connections.all()
        if aliases is None
        else (connections[alias] for alias in aliases)
    )
    return all(conn.features.uses_savepoints for conn in conns)
Referenced by django.test.testcases.TestCase._databases_support_savepoints().
connections_support_transactions()
django.test.testcases.connections_support_transactions (aliases = None)
Return whether or not all (or specified) connections support
transactions.
Definition at line 1273 of file testcases.py.
def connections_support_transactions(aliases=None):
    """
    Return whether or not all (or specified) connections support
    transactions.
    """
    conns = (
        connections.all()
        if aliases is None
        else (connections[alias] for alias in aliases)
    )
    return all(conn.features.supports_transactions for conn in conns)
is_pickable()
django.test.testcases.is_pickable (obj)
Returns true if the object can be dumped and loaded through the pickle
module.
Definition at line 96 of file testcases.py.
def is_pickable(obj):
    """
    Returns true if the object can be dumped and loaded through the pickle
    module.
    """
    try:
        pickle.loads(pickle.dumps(obj))
    except (AttributeError, TypeError, pickle.PickleError):
        return False
    return True
Referenced by django.test.testcases.SimpleTestCase.__getstate__().
skipIfDBFeature()
django.test.testcases.skipIfDBFeature (* features)
Skip a test if a database has at least one of the named features.
Definition at line 1580 of file testcases.py.
def skipIfDBFeature(*features):
    """Skip a test if a database has at least one of the named features."""
    return _deferredSkip(
        lambda: any(
            getattr(connection.features, feature, False) for feature in features
        ),
        "Database has feature(s) %s" % ", ".join(features),
        "skipIfDBFeature",
    )
References _deferredSkip().
skipUnlessAnyDBFeature()
django.test.testcases.skipUnlessAnyDBFeature (* features)
Skip a test unless a database has any of the named features.
Definition at line 1602 of file testcases.py.
def skipUnlessAnyDBFeature(*features):
    """Skip a test unless a database has any of the named features."""
    return _deferredSkip(
        lambda: not any(
            getattr(connection.features, feature, False) for feature in features
        ),
        "Database doesn't support any of the feature(s): %s" % ", ".join(features),
        "skipUnlessAnyDBFeature",
    )
References _deferredSkip().
skipUnlessDBFeature()
django.test.testcases.skipUnlessDBFeature (* features)
Skip a test unless a database has all the named features.
Definition at line 1591 of file testcases.py.
def skipUnlessDBFeature(*features):
    """Skip a test unless a database has all the named features."""
    return _deferredSkip(
        lambda: not all(
            getattr(connection.features, feature, False) for feature in features
        ),
        "Database doesn't support feature(s): %s" % ", ".join(features),
        "skipUnlessDBFeature",
    )
References _deferredSkip().
to_list()
django.test.testcases.to_list (value)
Put value into a list if it's not already one.
Definition at line 89 of file testcases.py.
def to_list(value):
    """Put value into a list if it's not already one."""
    if not isinstance(value, list):
        value = [value]
    return value
Referenced by django.test.testcases.SimpleTestCase.assertFormError(), and django.test.testcases.SimpleTestCase.assertFormSetError().
Variable Documentation
logger
django.test.testcases.logger = logging.getLogger("django.test")
Definition at line 60 of file testcases.py.