Read&Watch: django.core.management.commands.makemessages Namespace Reference
django.core.management.commands.makemessages Namespace Reference
Classes
class BuildFile
class Command
class TranslatableFile
Functions
check_programs (*programs)
is_valid_locale (locale)
normalize_eols (raw_contents)
write_pot_file (potfile, msgs)
Variables
plural_forms_re
int STATUS_OK = 0
NO_LOCALE_DIR = object()
Function Documentation
check_programs()
django.core.management.commands.makemessages.check_programs (* programs)
Definition at line 34 of file makemessages.py.
def check_programs(*programs):
    for program in programs:
        if find_command(program) is None:
            raise CommandError(
                "Can't find %s. Make sure you have GNU gettext tools 0.15 or "
                "newer installed." % program
            )
is_valid_locale()
django.core.management.commands.makemessages.is_valid_locale (locale)
Definition at line 43 of file makemessages.py.
def is_valid_locale(locale):
    return re.match(r"^[a-z]+$", locale) or re.match(r"^[a-z]+_[A-Z].*$", locale)
@total_ordering
normalize_eols()
django.core.management.commands.makemessages.normalize_eols (raw_contents)
Take a block of raw text that will be passed through str.splitlines() to
get universal newlines treatment.
Return the resulting block of text with normalized `\n` EOL sequences ready
to be written to disk using current platform's native EOLs.
Definition at line 166 of file makemessages.py.
def normalize_eols(raw_contents):
    """
    Take a block of raw text that will be passed through str.splitlines() to
    get universal newlines treatment.
    Return the resulting block of text with normalized `\n` EOL sequences ready
    to be written to disk using current platform's native EOLs.
    """
    lines_list = raw_contents.splitlines()
    # Ensure last line has its EOL
    if lines_list and lines_list[-1]:
        lines_list.append("")
    return "\n".join(lines_list)
Referenced by django.core.management.commands.makemessages.Command.build_potfiles(), and django.core.management.commands.makemessages.Command.write_po_file().
write_pot_file()
django.core.management.commands.makemessages.write_pot_file (potfile, msgs)
Write the `potfile` with the `msgs` contents, making sure its format is
valid.
Definition at line 181 of file makemessages.py.
def write_pot_file(potfile, msgs):
    """
    Write the `potfile` with the `msgs` contents, making sure its format is
    valid.
    """
    pot_lines = msgs.splitlines()
    if os.path.exists(potfile):
        # Strip the header
        lines = dropwhile(len, pot_lines)
    else:
        lines = []
        found, header_read = False, False
        for line in pot_lines:
            if not found and not header_read:
                if "charset=CHARSET" in line:
                    found = True
                    line = line.replace("charset=CHARSET", "charset=UTF-8")
            if not line and not found:
                header_read = True
            lines.append(line)
    msgs = "\n".join(lines)
    # Force newlines of POT files to '\n' to work around
    # https://savannah.gnu.org/bugs/index.php?52395
    with open(potfile, "a", encoding="utf-8", newline="\n") as fp:
        fp.write(msgs)
Referenced by django.core.management.commands.makemessages.Command.process_locale_dir().
Variable Documentation
NO_LOCALE_DIR
django.core.management.commands.makemessages.NO_LOCALE_DIR = object()
Definition at line 31 of file makemessages.py.
plural_forms_re
django.core.management.commands.makemessages.plural_forms_re
Initial value:
=  _lazy_re_compile(
    r'^(?P<value>"Plural-Forms.+?\\n")\s*$', re.MULTILINE | re.DOTALL
)
Definition at line 27 of file makemessages.py.
STATUS_OK
int django.core.management.commands.makemessages.STATUS_OK = 0
Definition at line 30 of file makemessages.py.