Read&Watch: django.db.models.fields.related Namespace Reference
django.db.models.fields.related Namespace Reference
Classes
class ForeignKey
class ForeignObject
class ManyToManyField
class OneToOneField
class RelatedField
Functions
resolve_relation (scope_model, relation)
lazy_related_operation (function, model, *related_models, **kwargs)
create_many_to_many_intermediary_model (field, klass)
Variables
str RECURSIVE_RELATIONSHIP_CONSTANT = "self"
Function Documentation
create_many_to_many_intermediary_model()
django.db.models.fields.related.create_many_to_many_intermediary_model (field, klass)
Definition at line 1260 of file related.py.
def create_many_to_many_intermediary_model(field, klass):
    from django.db import models
    def set_managed(model, related, through):
        through._meta.managed = model._meta.managed or related._meta.managed
    to_model = resolve_relation(klass, field.remote_field.model)
    name = "%s_%s" % (klass._meta.object_name, field.name)
    lazy_related_operation(set_managed, klass, to_model, name)
    to = make_model_tuple(to_model)[1]
    from_ = klass._meta.model_name
    if to == from_:
        to = "to_%s" % to
        from_ = "from_%s" % from_
    meta = type(
        "Meta",
        (),
        {
            "db_table": field._get_m2m_db_table(klass._meta),
            "auto_created": klass,
            "app_label": klass._meta.app_label,
            "db_tablespace": klass._meta.db_tablespace,
            "unique_together": (from_, to),
            "verbose_name": _("%(from)s-%(to)s relationship")
            % {"from": from_, "to": to},
            "verbose_name_plural": _("%(from)s-%(to)s relationships")
            % {"from": from_, "to": to},
            "apps": field.model._meta.apps,
        },
    )
    # Construct and return the new class.
    return type(
        name,
        (models.Model,),
        {
            "Meta": meta,
            "__module__": klass.__module__,
            from_: models.ForeignKey(
                klass,
                related_name="%s+" % name,
                db_tablespace=field.db_tablespace,
                db_constraint=field.remote_field.db_constraint,
                on_delete=CASCADE,
            ),
            to: models.ForeignKey(
                to_model,
                related_name="%s+" % name,
                db_tablespace=field.db_tablespace,
                db_constraint=field.remote_field.db_constraint,
                on_delete=CASCADE,
            ),
        },
    )
References lazy_related_operation(), and resolve_relation().
Referenced by django.db.models.fields.related.ManyToManyField.contribute_to_class().
lazy_related_operation()
django.db.models.fields.related.lazy_related_operation (function, model, * related_models, ** kwargs)
Schedule `function` to be called once `model` and all `related_models`
have been imported and registered with the app registry. `function` will
be called with the newly-loaded model classes as its positional arguments,
plus any optional keyword arguments.
The `model` argument must be a model class. Each subsequent positional
argument is another model, or a reference to another model - see
`resolve_relation()` for the various forms these may take. Any relative
references will be resolved relative to `model`.
This is a convenience wrapper for `Apps.lazy_model_operation` - the app
registry model used is the one found in `model._meta.apps`.
Definition at line 70 of file related.py.
def lazy_related_operation(function, model, *related_models, **kwargs):
    """
    Schedule `function` to be called once `model` and all `related_models`
    have been imported and registered with the app registry. `function` will
    be called with the newly-loaded model classes as its positional arguments,
    plus any optional keyword arguments.
    The `model` argument must be a model class. Each subsequent positional
    argument is another model, or a reference to another model - see
    `resolve_relation()` for the various forms these may take. Any relative
    references will be resolved relative to `model`.
    This is a convenience wrapper for `Apps.lazy_model_operation` - the app
    registry model used is the one found in `model._meta.apps`.
    """
    models = [model] + [resolve_relation(model, rel) for rel in related_models]
    model_keys = (make_model_tuple(m) for m in models)
    apps = model._meta.apps
    return apps.lazy_model_operation(partial(function, **kwargs), *model_keys)
References resolve_relation().
Referenced by django.db.models.fields.related.ManyToManyField.contribute_to_class(), and create_many_to_many_intermediary_model().
resolve_relation()
django.db.models.fields.related.resolve_relation (scope_model, relation)
Transform relation into a model or fully-qualified model string of the form
"app_label.ModelName", relative to scope_model.
The relation argument can be:
  * RECURSIVE_RELATIONSHIP_CONSTANT, i.e. the string "self", in which case
    the model argument will be returned.
  * A bare model name without an app_label, in which case scope_model's
    app_label will be prepended.
  * An "app_label.ModelName" string.
  * A model class, which will be returned unchanged.
Definition at line 45 of file related.py.
def resolve_relation(scope_model, relation):
    """
    Transform relation into a model or fully-qualified model string of the form
    "app_label.ModelName", relative to scope_model.
    The relation argument can be:
      * RECURSIVE_RELATIONSHIP_CONSTANT, i.e. the string "self", in which case
        the model argument will be returned.
      * A bare model name without an app_label, in which case scope_model's
        app_label will be prepended.
      * An "app_label.ModelName" string.
      * A model class, which will be returned unchanged.
    """
    # Check for recursive relations
    if relation == RECURSIVE_RELATIONSHIP_CONSTANT:
        relation = scope_model
    # Look for an "app.Model" relation
    if isinstance(relation, str):
        if "." not in relation:
            relation = "%s.%s" % (scope_model._meta.app_label, relation)
    return relation
Referenced by django.db.models.fields.related.ManyToManyField._check_relationship_model(), create_many_to_many_intermediary_model(), and lazy_related_operation().
Variable Documentation
RECURSIVE_RELATIONSHIP_CONSTANT
str django.db.models.fields.related.RECURSIVE_RELATIONSHIP_CONSTANT = "self"
Definition at line 42 of file related.py.