Read&Watch: pip._internal.commands.search Namespace Reference
pip._internal.commands.search Namespace Reference
Classes
class SearchCommand
class TransformedHit
Functions
List["TransformedHit"] transform_hits (List[Dict[str, str]] hits)
None print_dist_installation_info (str name, str latest)
None print_results (List["TransformedHit"] hits, Optional[int] name_column_width=None, Optional[int] terminal_width=None)
str highest_version (List[str] versions)
Variables
logger = logging.getLogger(__name__)
Function Documentation
highest_version()
str pip._internal.commands.search.highest_version (List[str] versions)
Definition at line 171 of file search.py.
def highest_version(versions: List[str]) -> str:
    return max(versions, key=parse_version)
Referenced by print_results(), and transform_hits().
print_dist_installation_info()
None pip._internal.commands.search.print_dist_installation_info (str name, str latest)
Definition at line 114 of file search.py.
def print_dist_installation_info(name: str, latest: str) -> None:
    env = get_default_environment()
    dist = env.get_distribution(name)
    if dist is not None:
        with indent_log():
            if dist.version == latest:
                write_output("INSTALLED: %s (latest)", dist.version)
            else:
                write_output("INSTALLED: %s", dist.version)
                if parse_version(latest).pre:
                    write_output(
                        "LATEST:    %s (pre-release; install"
                        " with `pip install --pre`)",
                        latest,
                    )
                else:
                    write_output("LATEST:    %s", latest)
Referenced by print_results().
print_results()
None pip._internal.commands.search.print_results (List["TransformedHit"] hits, Optional[int] name_column_width = None, Optional[int] terminal_width = None)
Definition at line 133 of file search.py.
) -> None:
    if not hits:
        return
    if name_column_width is None:
        name_column_width = (
            max(
                [
                    len(hit["name"]) + len(highest_version(hit.get("versions", ["-"])))
                    for hit in hits
                ]
            )
            + 4
        )
    for hit in hits:
        name = hit["name"]
        summary = hit["summary"] or ""
        latest = highest_version(hit.get("versions", ["-"]))
        if terminal_width is not None:
            target_width = terminal_width - name_column_width - 5
            if target_width > 10:
                # wrap and indent summary to fit terminal
                summary_lines = textwrap.wrap(summary, target_width)
                summary = ("\n" + " " * (name_column_width + 3)).join(summary_lines)
        name_latest = f"{name} ({latest})"
        line = f"{name_latest:{name_column_width}} - {summary}"
        try:
            write_output(line)
            print_dist_installation_info(name, latest)
        except UnicodeEncodeError:
            pass
References highest_version(), and print_dist_installation_info().
Referenced by pip._internal.commands.search.SearchCommand.run().
transform_hits()
List["TransformedHit"] pip._internal.commands.search.transform_hits (List[Dict[str, str]] hits)
The list from pypi is really a list of versions. We want a list of
packages with the list of versions stored inline. This converts the
list from pypi into one we can use.
Definition at line 86 of file search.py.
def transform_hits(hits: List[Dict[str, str]]) -> List["TransformedHit"]:
    """
    The list from pypi is really a list of versions. We want a list of
    packages with the list of versions stored inline. This converts the
    list from pypi into one we can use.
    """
    packages: Dict[str, TransformedHit] = OrderedDict()
    for hit in hits:
        name = hit["name"]
        summary = hit["summary"]
        version = hit["version"]
        if name not in packages.keys():
            packages[name] = {
                "name": name,
                "summary": summary,
                "versions": [version],
            }
        else:
            packages[name]["versions"].append(version)
            # if this is the highest version, replace summary and score
            if version == highest_version(packages[name]["versions"]):
                packages[name]["summary"] = summary
    return list(packages.values())
References highest_version().
Referenced by pip._internal.commands.search.SearchCommand.run().
Variable Documentation
logger
pip._internal.commands.search.logger = logging.getLogger(__name__)
Definition at line 30 of file search.py.