Read&Watch: django.template.backends.django Namespace Reference
django.template.backends.django Namespace Reference
Classes
class DjangoTemplates
class Template
Functions
copy_exception (exc, backend=None)
reraise (exc, backend)
get_template_tag_modules ()
get_installed_libraries ()
get_package_libraries (pkg)
Function Documentation
copy_exception()
django.template.backends.django.copy_exception (exc, backend = None)
Create a new TemplateDoesNotExist. Preserve its declared attributes and
template debug data but discard __traceback__, __context__, and __cause__
to make this object suitable for keeping around (in a cache, for example).
Definition at line 112 of file django.py.
def copy_exception(exc, backend=None):
    """
    Create a new TemplateDoesNotExist. Preserve its declared attributes and
    template debug data but discard __traceback__, __context__, and __cause__
    to make this object suitable for keeping around (in a cache, for example).
    """
    backend = backend or exc.backend
    new = exc.__class__(*exc.args, tried=exc.tried, backend=backend, chain=exc.chain)
    if hasattr(exc, "template_debug"):
        new.template_debug = exc.template_debug
    return new
Referenced by reraise().
get_installed_libraries()
django.template.backends.django.get_installed_libraries ()
Return the built-in template tag libraries and those from installed
applications. Libraries are stored in a dictionary where keys are the
individual module names, not the full module paths. Example:
django.templatetags.i18n is stored as i18n.
Definition at line 155 of file django.py.
def get_installed_libraries():
    """
    Return the built-in template tag libraries and those from installed
    applications. Libraries are stored in a dictionary where keys are the
    individual module names, not the full module paths. Example:
    django.templatetags.i18n is stored as i18n.
    """
    return {
        module_name: full_name for module_name, full_name in get_template_tag_modules()
    }
References get_template_tag_modules().
Referenced by django.template.backends.django.DjangoTemplates.get_templatetag_libraries().
get_package_libraries()
django.template.backends.django.get_package_libraries (pkg)
Recursively yield template tag libraries defined in submodules of a
package.
Definition at line 167 of file django.py.
def get_package_libraries(pkg):
    """
    Recursively yield template tag libraries defined in submodules of a
    package.
    """
    for entry in walk_packages(pkg.__path__, pkg.__name__ + "."):
        try:
            module = import_module(entry[1])
        except ImportError as e:
            raise InvalidTemplateLibrary(
                "Invalid template library specified. ImportError raised when "
                "trying to load '%s': %s" % (entry[1], e)
            ) from e
        if hasattr(module, "register"):
            yield entry[1]
Referenced by get_template_tag_modules().
get_template_tag_modules()
django.template.backends.django.get_template_tag_modules ()
Yield (module_name, module_path) pairs for all installed template tag
libraries.
Definition at line 133 of file django.py.
def get_template_tag_modules():
    """
    Yield (module_name, module_path) pairs for all installed template tag
    libraries.
    """
    candidates = ["django.templatetags"]
    candidates.extend(
        f"{app_config.name}.templatetags" for app_config in apps.get_app_configs()
    )
    for candidate in candidates:
        try:
            pkg = import_module(candidate)
        except ImportError:
            # No templatetags package defined. This is safe to ignore.
            continue
        if hasattr(pkg, "__path__"):
            for name in get_package_libraries(pkg):
                yield name.removeprefix(candidate).lstrip("."), name
References get_package_libraries().
Referenced by django.template.backends.django.DjangoTemplates._check_for_template_tags_with_the_same_name(), and get_installed_libraries().
reraise()
django.template.backends.django.reraise (exc, backend)
Reraise TemplateDoesNotExist while maintaining template debug information.
Definition at line 125 of file django.py.
def reraise(exc, backend):
    """
    Reraise TemplateDoesNotExist while maintaining template debug information.
    """
    new = copy_exception(exc, backend)
    raise new from exc
References copy_exception().
Referenced by django.template.backends.django.DjangoTemplates.get_template(), and django.template.backends.django.Template.render().