Read&Watch: pip._internal.configuration Namespace Reference
pip._internal.configuration Namespace Reference
Classes
class Configuration
Functions
str _normalize_name (str name)
List[str] _disassemble_key (str name)
Dict[Kind, List[str]] get_configuration_files ()
Variables
RawConfigParser = configparser.RawConfigParser
Kind = NewType("Kind", str)
str CONFIG_BASENAME = "pip.ini" if WINDOWS else "pip.conf"
str ENV_NAMES_IGNORED = "version", "help"
kinds
OVERRIDE_ORDER = kinds.GLOBAL, kinds.USER, kinds.SITE, kinds.ENV, kinds.ENV_VAR
VALID_LOAD_ONLY = kinds.USER, kinds.GLOBAL, kinds.SITE
logger = getLogger(__name__)
Detailed Description
Configuration management setup
Some terminology:
- name
  As written in config files.
- value
  Value associated with a name
- key
  Name combined with it's section (section.name)
- variant
  A single word describing where the configuration key-value pair came from
Function Documentation
_disassemble_key()
List[str] pip._internal.configuration._disassemble_key (str name) protected
Definition at line 58 of file configuration.py.
def _disassemble_key(name: str) -> List[str]:
    if "." not in name:
        error_message = (
            "Key does not contain dot separated section and key. "
            f"Perhaps you wanted to use 'global.{name}' instead?"
        )
        raise ConfigurationError(error_message)
    return name.split(".", 1)
Referenced by pip._internal.configuration.Configuration.get_value(), pip._internal.configuration.Configuration.set_value(), and pip._internal.configuration.Configuration.unset_value().
_normalize_name()
str pip._internal.configuration._normalize_name (str name) protected
Make a name consistent regardless of source (environment or file)
Definition at line 50 of file configuration.py.
def _normalize_name(name: str) -> str:
    """Make a name consistent regardless of source (environment or file)"""
    name = name.lower().replace("_", "-")
    if name.startswith("--"):
        name = name[2:]  # only prefer long opts
    return name
Referenced by pip._internal.configuration.Configuration._normalized_keys(), pip._internal.configuration.Configuration.get_value(), pip._internal.configuration.Configuration.set_value(), and pip._internal.configuration.Configuration.unset_value().
get_configuration_files()
Dict[Kind, List[str]] pip._internal.configuration.get_configuration_files ()
Definition at line 68 of file configuration.py.
def get_configuration_files() -> Dict[Kind, List[str]]:
    global_config_files = [
        os.path.join(path, CONFIG_BASENAME) for path in appdirs.site_config_dirs("pip")
    ]
    site_config_file = os.path.join(sys.prefix, CONFIG_BASENAME)
    legacy_config_file = os.path.join(
        os.path.expanduser("~"),
        "pip" if WINDOWS else ".pip",
        CONFIG_BASENAME,
    )
    new_config_file = os.path.join(appdirs.user_config_dir("pip"), CONFIG_BASENAME)
    return {
        kinds.GLOBAL: global_config_files,
        kinds.SITE: [site_config_file],
        kinds.USER: [legacy_config_file, new_config_file],
    }
Referenced by pip._internal.configuration.Configuration.iter_config_files().
Variable Documentation
CONFIG_BASENAME
str pip._internal.configuration.CONFIG_BASENAME = "pip.ini" if WINDOWS else "pip.conf"
Definition at line 32 of file configuration.py.
ENV_NAMES_IGNORED
str pip._internal.configuration.ENV_NAMES_IGNORED = "version", "help"
Definition at line 33 of file configuration.py.
Kind
pip._internal.configuration.Kind = NewType("Kind", str)
Definition at line 30 of file configuration.py.
kinds
pip._internal.configuration.kinds
Initial value:
=  enum(
    USER="user",  # User Specific
    GLOBAL="global",  # System Wide
    SITE="site",  # [Virtual] Environment Specific
    ENV="env",  # from PIP_CONFIG_FILE
    ENV_VAR="env-var",  # from Environment Variables
)
Definition at line 36 of file configuration.py.
logger
pip._internal.configuration.logger = getLogger(__name__)
Definition at line 46 of file configuration.py.
OVERRIDE_ORDER
pip._internal.configuration.OVERRIDE_ORDER = kinds.GLOBAL, kinds.USER, kinds.SITE, kinds.ENV, kinds.ENV_VAR
Definition at line 43 of file configuration.py.
RawConfigParser
pip._internal.configuration.RawConfigParser = configparser.RawConfigParser
Definition at line 29 of file configuration.py.
VALID_LOAD_ONLY
pip._internal.configuration.VALID_LOAD_ONLY = kinds.USER, kinds.GLOBAL, kinds.SITE
Definition at line 44 of file configuration.py.