Read&Watch: dill.tests.test_check Namespace Reference
dill.tests.test_check Namespace Reference
Functions
raise_check (func, **kwds)
test_simple (verbose=None)
test_recurse (verbose=None)
test_byref (verbose=None)
test_protocol (verbose=None)
test_python (verbose=None)
Variables
x f = lambda x**2
Function Documentation
raise_check()
dill.tests.test_check.raise_check (func, ** kwds)
Definition at line 16 of file test_check.py.
def raise_check(func, **kwds):
    try:
        with capture('stdout') as out:
            check(func, **kwds)
    except Exception:
        e = sys.exc_info()[1]
        raise AssertionError(str(e))
    else:
        assert 'Traceback' not in out.getvalue()
    finally:
        out.close()
Referenced by test_byref(), test_protocol(), test_python(), test_recurse(), and test_simple().
test_byref()
dill.tests.test_check.test_byref (verbose = None)
Definition at line 40 of file test_check.py.
def test_byref(verbose=None):
    raise_check(f, byref=True, verbose=verbose)
References raise_check().
Referenced by test_python().
test_protocol()
dill.tests.test_check.test_protocol (verbose = None)
Definition at line 44 of file test_check.py.
def test_protocol(verbose=None):
    raise_check(f, protocol=True, verbose=verbose)
References raise_check().
Referenced by test_python().
test_python()
dill.tests.test_check.test_python (verbose = None)
Definition at line 48 of file test_check.py.
def test_python(verbose=None):
    raise_check(f, python=None, verbose=verbose)
#TODO: test incompatible versions
#TODO: test dump failure
#TODO: test load failure
References raise_check(), test_byref(), test_protocol(), test_python(), test_recurse(), and test_simple().
Referenced by test_python().
test_recurse()
dill.tests.test_check.test_recurse (verbose = None)
Definition at line 36 of file test_check.py.
def test_recurse(verbose=None):
    raise_check(f, recurse=True, verbose=verbose)
References raise_check().
Referenced by test_python().
test_simple()
dill.tests.test_check.test_simple (verbose = None)
Definition at line 32 of file test_check.py.
def test_simple(verbose=None):
    raise_check(f, verbose=verbose)
References raise_check().
Referenced by test_python().
Variable Documentation
f
x dill.tests.test_check.f = lambda x**2
Definition at line 29 of file test_check.py.