Read&Watch: django.utils.translation.trans_null Namespace Reference
django.utils.translation.trans_null Namespace Reference
Functions
gettext (message)
ngettext (singular, plural, number)
pgettext (context, message)
npgettext (context, singular, plural, number)
activate (x)
deactivate ()
get_language ()
get_language_bidi ()
check_for_language (x)
get_language_from_request (request, check_path=False)
get_language_from_path (request)
get_supported_language_variant (lang_code, strict=False)
Variables
gettext_noop = gettext
ngettext_lazy = ngettext
deactivate_all = deactivate
Function Documentation
activate()
django.utils.translation.trans_null.activate (x)
Definition at line 32 of file trans_null.py.
def activate(x):
    return None
check_for_language()
django.utils.translation.trans_null.check_for_language (x)
Definition at line 51 of file trans_null.py.
def check_for_language(x):
    return True
deactivate()
django.utils.translation.trans_null.deactivate ()
Definition at line 36 of file trans_null.py.
def deactivate():
    return None
get_language()
django.utils.translation.trans_null.get_language ()
Definition at line 43 of file trans_null.py.
def get_language():
    return settings.LANGUAGE_CODE
get_language_bidi()
django.utils.translation.trans_null.get_language_bidi ()
Definition at line 47 of file trans_null.py.
def get_language_bidi():
    return settings.LANGUAGE_CODE in settings.LANGUAGES_BIDI
get_language_from_path()
django.utils.translation.trans_null.get_language_from_path (request)
Definition at line 59 of file trans_null.py.
def get_language_from_path(request):
    return None
get_language_from_request()
django.utils.translation.trans_null.get_language_from_request (request, check_path = False)
Definition at line 55 of file trans_null.py.
def get_language_from_request(request, check_path=False):
    return settings.LANGUAGE_CODE
get_supported_language_variant()
django.utils.translation.trans_null.get_supported_language_variant (lang_code, strict = False)
Definition at line 63 of file trans_null.py.
def get_supported_language_variant(lang_code, strict=False):
    if lang_code and lang_code.lower() == settings.LANGUAGE_CODE.lower():
        return lang_code
    else:
        raise LookupError(lang_code)
gettext()
django.utils.translation.trans_null.gettext (message)
Definition at line 8 of file trans_null.py.
def gettext(message):
    return message
Referenced by pgettext().
ngettext()
django.utils.translation.trans_null.ngettext (singular, plural, number)
Definition at line 15 of file trans_null.py.
def ngettext(singular, plural, number):
    if number == 1:
        return singular
    return plural
Referenced by npgettext().
npgettext()
django.utils.translation.trans_null.npgettext (context, singular, plural, number)
Definition at line 28 of file trans_null.py.
def npgettext(context, singular, plural, number):
    return ngettext(singular, plural, number)
References ngettext().
pgettext()
django.utils.translation.trans_null.pgettext (context, message)
Definition at line 24 of file trans_null.py.
def pgettext(context, message):
    return gettext(message)
References gettext().
Variable Documentation
deactivate_all
django.utils.translation.trans_null.deactivate_all = deactivate
Definition at line 40 of file trans_null.py.
gettext_noop
django.utils.translation.trans_null.gettext_noop = gettext
Definition at line 12 of file trans_null.py.
ngettext_lazy
django.utils.translation.trans_null.ngettext_lazy = ngettext
Definition at line 21 of file trans_null.py.