Read&Watch: django.utils.translation Namespace Reference
django.utils.translation Namespace Reference
Namespaces
namespace reloader
namespace template
namespace trans_null
namespace trans_real
Classes
class override
class Trans
class TranslatorCommentWarning
Functions
gettext_noop (message)
gettext (message)
ngettext (singular, plural, number)
pgettext (context, message)
npgettext (context, singular, plural, number)
lazy_number (func, resultclass, number=None, **kwargs)
_lazy_number_unpickle (func, resultclass, number, kwargs)
ngettext_lazy (singular, plural, number=None)
npgettext_lazy (context, singular, plural, number=None)
activate (language)
deactivate ()
get_language ()
get_language_bidi ()
check_for_language (lang_code)
to_language (locale)
to_locale (language)
get_language_from_request (request, check_path=False)
get_language_from_path (path)
get_supported_language_variant (lang_code, *, strict=False)
templatize (src, **kwargs)
deactivate_all ()
get_language_info (lang_code)
trim_whitespace (s)
round_away_from_one (value)
Variables
_trans = Trans()
gettext_lazy = lazy(gettext, str)
pgettext_lazy = lazy(pgettext, str)
trim_whitespace_re = _lazy_re_compile(r"\s*\n\s*")
Detailed Description
Internationalization support.
Function Documentation
_lazy_number_unpickle()
django.utils.translation._lazy_number_unpickle (func, resultclass, number, kwargs) protected
Definition at line 167 of file __init__.py.
def _lazy_number_unpickle(func, resultclass, number, kwargs):
    return lazy_number(func, resultclass, number=number, **kwargs)
References lazy_number().
activate()
django.utils.translation.activate (language)
Definition at line 181 of file __init__.py.
def activate(language):
    return _trans.activate(language)
Referenced by django.utils.translation.override.__exit__().
check_for_language()
django.utils.translation.check_for_language (lang_code)
Definition at line 218 of file __init__.py.
def check_for_language(lang_code):
    return _trans.check_for_language(lang_code)
deactivate()
django.utils.translation.deactivate ()
Definition at line 185 of file __init__.py.
def deactivate():
    return _trans.deactivate()
deactivate_all()
django.utils.translation.deactivate_all ()
Definition at line 265 of file __init__.py.
def deactivate_all():
    return _trans.deactivate_all()
Referenced by django.utils.translation.override.__exit__().
get_language()
django.utils.translation.get_language ()
Definition at line 210 of file __init__.py.
def get_language():
    return _trans.get_language()
get_language_bidi()
django.utils.translation.get_language_bidi ()
Definition at line 214 of file __init__.py.
def get_language_bidi():
    return _trans.get_language_bidi()
get_language_from_path()
django.utils.translation.get_language_from_path (path)
Definition at line 251 of file __init__.py.
def get_language_from_path(path):
    return _trans.get_language_from_path(path)
get_language_from_request()
django.utils.translation.get_language_from_request (request, check_path = False)
Definition at line 247 of file __init__.py.
def get_language_from_request(request, check_path=False):
    return _trans.get_language_from_request(request, check_path)
get_language_info()
django.utils.translation.get_language_info (lang_code)
Definition at line 269 of file __init__.py.
def get_language_info(lang_code):
    from django.conf.locale import LANG_INFO
    try:
        lang_info = LANG_INFO[lang_code]
        if "fallback" in lang_info and "name" not in lang_info:
            info = get_language_info(lang_info["fallback"][0])
        else:
            info = lang_info
    except KeyError:
        if "-" not in lang_code:
            raise KeyError("Unknown language code %s." % lang_code)
        generic_lang_code = lang_code.split("-")[0]
        try:
            info = LANG_INFO[generic_lang_code]
        except KeyError:
            raise KeyError(
                "Unknown language code %s and %s." % (lang_code, generic_lang_code)
            )
    if info:
        info["name_translated"] = gettext_lazy(info["name"])
    return info
References get_language_info(), and gettext_lazy.
Referenced by get_language_info().
get_supported_language_variant()
django.utils.translation.get_supported_language_variant (lang_code, * , strict = False)
Definition at line 255 of file __init__.py.
def get_supported_language_variant(lang_code, *, strict=False):
    return _trans.get_supported_language_variant(lang_code, strict)
gettext()
django.utils.translation.gettext (message)
Definition at line 95 of file __init__.py.
def gettext(message):
    return _trans.gettext(message)
gettext_noop()
django.utils.translation.gettext_noop (message)
Definition at line 91 of file __init__.py.
def gettext_noop(message):
    return _trans.gettext_noop(message)
lazy_number()
django.utils.translation.lazy_number (func, resultclass, number = None, ** kwargs)
Definition at line 115 of file __init__.py.
def lazy_number(func, resultclass, number=None, **kwargs):
    if isinstance(number, int):
        kwargs["number"] = number
        proxy = lazy(func, resultclass)(**kwargs)
    else:
        original_kwargs = kwargs.copy()
        class NumberAwareString(resultclass):
            def __bool__(self):
                return bool(kwargs["singular"])
            def _get_number_value(self, values):
                try:
                    return values[number]
                except KeyError:
                    raise KeyError(
                        "Your dictionary lacks key '%s'. Please provide "
                        "it, because it is required to determine whether "
                        "string is singular or plural." % number
                    )
            def _translate(self, number_value):
                kwargs["number"] = number_value
                return func(**kwargs)
            def format(self, *args, **kwargs):
                number_value = (
                    self._get_number_value(kwargs) if kwargs and number else args[0]
                )
                return self._translate(number_value).format(*args, **kwargs)
            def __mod__(self, rhs):
                if isinstance(rhs, dict) and number:
                    number_value = self._get_number_value(rhs)
                else:
                    number_value = rhs
                translated = self._translate(number_value)
                try:
                    translated %= rhs
                except TypeError:
                    # String doesn't contain a placeholder for the number.
                    pass
                return translated
        proxy = lazy(lambda **kwargs: NumberAwareString(), NumberAwareString)(**kwargs)
        proxy.__reduce__ = lambda: (
            _lazy_number_unpickle,
            (func, resultclass, number, original_kwargs),
        )
    return proxy
Referenced by _lazy_number_unpickle(), ngettext_lazy(), and npgettext_lazy().
ngettext()
django.utils.translation.ngettext (singular, plural, number)
Definition at line 99 of file __init__.py.
def ngettext(singular, plural, number):
    return _trans.ngettext(singular, plural, number)
ngettext_lazy()
django.utils.translation.ngettext_lazy (singular, plural, number = None)
Definition at line 171 of file __init__.py.
def ngettext_lazy(singular, plural, number=None):
    return lazy_number(ngettext, str, singular=singular, plural=plural, number=number)
References lazy_number().
npgettext()
django.utils.translation.npgettext (context, singular, plural, number)
Definition at line 107 of file __init__.py.
def npgettext(context, singular, plural, number):
    return _trans.npgettext(context, singular, plural, number)
npgettext_lazy()
django.utils.translation.npgettext_lazy (context, singular, plural, number = None)
Definition at line 175 of file __init__.py.
def npgettext_lazy(context, singular, plural, number=None):
    return lazy_number(
        npgettext, str, context=context, singular=singular, plural=plural, number=number
    )
References lazy_number().
pgettext()
django.utils.translation.pgettext (context, message)
Definition at line 103 of file __init__.py.
def pgettext(context, message):
    return _trans.pgettext(context, message)
round_away_from_one()
django.utils.translation.round_away_from_one (value)
Definition at line 301 of file __init__.py.
def round_away_from_one(value):
    return int(Decimal(value - 1).quantize(Decimal("0"), rounding=ROUND_UP)) + 1
templatize()
django.utils.translation.templatize (src, ** kwargs)
Definition at line 259 of file __init__.py.
def templatize(src, **kwargs):
    from .template import templatize
    return templatize(src, **kwargs)
References templatize().
Referenced by templatize().
to_language()
django.utils.translation.to_language (locale)
Turn a locale name (en_US) into a language name (en-us).
Definition at line 222 of file __init__.py.
def to_language(locale):
    """Turn a locale name (en_US) into a language name (en-us)."""
    p = locale.find("_")
    if p >= 0:
        return locale[:p].lower() + "-" + locale[p + 1 :].lower()
    else:
        return locale.lower()
to_locale()
django.utils.translation.to_locale (language)
Turn a language name (en-us) into a locale name (en_US).
Definition at line 231 of file __init__.py.
def to_locale(language):
    """Turn a language name (en-us) into a locale name (en_US)."""
    lang, _, country = language.lower().partition("-")
    if not country:
        return language[:3].lower() + language[3:]
    # A language with > 2 characters after the dash only has its first
    # character after the dash capitalized; e.g. sr-latn becomes sr_Latn.
    # A language with 2 characters after the dash has both characters
    # capitalized; e.g. en-us becomes en_US.
    country, _, tail = country.partition("-")
    country = country.title() if len(country) > 2 else country.upper()
    if tail:
        country += "-" + tail
    return lang + "_" + country
Referenced by django.utils.translation.trans_real.DjangoTranslation.__init__(), and django.utils.translation.trans_real.check_for_language().
trim_whitespace()
django.utils.translation.trim_whitespace (s)
Definition at line 297 of file __init__.py.
def trim_whitespace(s):
    return trim_whitespace_re.sub(" ", s.strip())
Referenced by django.utils.translation.template.templatize().
Variable Documentation
_trans
django.utils.translation._trans = Trans() protected
Definition at line 85 of file __init__.py.
gettext_lazy
django.utils.translation.gettext_lazy = lazy(gettext, str)
Definition at line 111 of file __init__.py.
Referenced by get_language_info().
pgettext_lazy
django.utils.translation.pgettext_lazy = lazy(pgettext, str)
Definition at line 112 of file __init__.py.
trim_whitespace_re
django.utils.translation.trim_whitespace_re = _lazy_re_compile(r"\s*\n\s*")
Definition at line 294 of file __init__.py.