Read&Watch: PIL.Image Namespace Reference
PIL.Image Namespace Reference
Classes
class DecompressionBombError
class DecompressionBombWarning
class Dither
class Exif
class Image
class ImagePointHandler
class ImagePointTransform
class ImageTransformHandler
class Palette
class Quantize
class Resampling
class SupportsArrayInterface
class SupportsGetData
class Transform
class Transpose
Functions
TypeGuard[Image] isImageType (Any t)
tuple[tuple[int,...], str] _conv_type_shape (Image im)
str getmodebase (str mode)
str getmodetype (str mode)
tuple[str,...] getmodebandnames (str mode)
int getmodebands (str mode)
None preinit ()
bool init ()
core.ImagingDecoder|ImageFile.PyDecoder _getdecoder (str mode, str decoder_name, Any args, tuple[Any,...] extra=())
core.ImagingEncoder|ImageFile.PyEncoder _getencoder (str mode, str encoder_name, Any args, tuple[Any,...] extra=())
tuple[float, float] _getscaleoffset (Callable[[ImagePointTransform], ImagePointTransform|float] expr)
Image _wedge ()
None _check_size (Any size)
Image new (str mode, tuple[int, int]|list[int] size, float|tuple[float,...]|str|None color=0)
Image frombytes (str mode, tuple[int, int] size, bytes|bytearray|SupportsArrayInterface data, str decoder_name="raw", *Any args)
Image frombuffer (str mode, tuple[int, int] size, bytes|SupportsArrayInterface data, str decoder_name="raw", *Any args)
Image fromarray (SupportsArrayInterface obj, str|None mode=None)
ImageFile.ImageFile fromqimage (ImageQt.QImage im)
ImageFile.ImageFile fromqpixmap (ImageQt.QPixmap im)
None _decompression_bomb_check (tuple[int, int] size)
ImageFile.ImageFile open (StrOrBytesPath|IO[bytes] fp, Literal["r"] mode="r", list[str]|tuple[str,...]|None formats=None)
Image alpha_composite (Image im1, Image im2)
Image blend (Image im1, Image im2, float alpha)
Image composite (Image image1, Image image2, Image mask)
Image eval (Image image, *Callable[[int], float] args)
Image merge (str mode, Sequence[Image] bands)
None register_open (str id,(Callable[[IO[bytes], str|bytes], ImageFile.ImageFile]|type[ImageFile.ImageFile]) factory, Callable[[bytes], bool|str]|None accept=None)
None register_mime (str id, str mimetype)
None register_save (str id, Callable[[Image, IO[bytes], str|bytes], None] driver)
None register_save_all (str id, Callable[[Image, IO[bytes], str|bytes], None] driver)
None register_extension (str id, str extension)
None register_extensions (str id, list[str] extensions)
dict[str, str] registered_extensions ()
None register_decoder (str name, type[ImageFile.PyDecoder] decoder)
None register_encoder (str name, type[ImageFile.PyEncoder] encoder)
None _show (Image image, **Any options)
Image effect_mandelbrot (tuple[int, int] size, tuple[float, float, float, float] extent, int quality)
Image effect_noise (tuple[int, int] size, float sigma)
Image linear_gradient (str mode)
Image radial_gradient (str mode)
None _apply_env_variables (dict[str, str]|None env=None)
Variables
ModuleType ElementTree | None
logger = logging.getLogger(__name__)
core = DeferredError.new(ImportError("The _imaging C module is not installed."))
dict _filters_support
module = sys.modules[__name__]
DEFAULT_STRATEGY = core.DEFAULT_STRATEGY
FILTERED = core.FILTERED
HUFFMAN_ONLY = core.HUFFMAN_ONLY
RLE = core.RLE
FIXED = core.FIXED
list ID = []
dict OPEN = {}
dict MIME = {}
dict SAVE = {}
dict SAVE_ALL = {}
dict EXTENSION = {}
dict DECODERS = {}
dict ENCODERS = {}
str _ENDIAN = "little" else ">"
list MODES
tuple _MAPMODES = ("L", "P", "RGBX", "RGBA", "CMYK", "I;16", "I;16L", "I;16B")
int _initialized = 0
dict _fromarray_typemap
_ExifBase = MutableMapping[int, Any]
Function Documentation
_apply_env_variables()
None PIL.Image._apply_env_variables (dict[str, str] | None env = None) protected
Definition at line 3830 of file Image.py.
def _apply_env_variables(env: dict[str, str] | None = None) -> None:
    env_dict = env if env is not None else os.environ
    for var_name, setter in [
        ("PILLOW_ALIGNMENT", core.set_alignment),
        ("PILLOW_BLOCK_SIZE", core.set_block_size),
        ("PILLOW_BLOCKS_MAX", core.set_blocks_max),
    ]:
        if var_name not in env_dict:
            continue
        var = env_dict[var_name].lower()
        units = 1
        for postfix, mul in [("k", 1024), ("m", 1024 * 1024)]:
            if var.endswith(postfix):
                units = mul
                var = var[: -len(postfix)]
        try:
            var_int = int(var) * units
        except ValueError:
            warnings.warn(f"{var_name} is not int")
            continue
        try:
            setter(var_int)
        except ValueError as e:
            warnings.warn(f"{var_name}: {e}")
References _apply_env_variables().
Referenced by _apply_env_variables().
_check_size()
None PIL.Image._check_size (Any size) protected
Common check to enforce type and sanity check on size tuples
:param size: Should be a 2 tuple of (width, height)
:returns: None, or raises a ValueError
Definition at line 3068 of file Image.py.
def _check_size(size: Any) -> None:
    """
    Common check to enforce type and sanity check on size tuples
    :param size: Should be a 2 tuple of (width, height)
    :returns: None, or raises a ValueError
    """
    if not isinstance(size, (list, tuple)):
        msg = "Size must be a list or tuple"
        raise ValueError(msg)
    if len(size) != 2:
        msg = "Size must be a sequence of length 2"
        raise ValueError(msg)
    if size[0] < 0 or size[1] < 0:
        msg = "Width and height must be >= 0"
        raise ValueError(msg)
Referenced by frombuffer(), frombytes(), and new().
_conv_type_shape()
tuple[tuple[int, ...], str] PIL.Image._conv_type_shape (Image im) protected
Definition at line 250 of file Image.py.
def _conv_type_shape(im: Image) -> tuple[tuple[int, ...], str]:
    m = ImageMode.getmode(im.mode)
    shape: tuple[int, ...] = (im.height, im.width)
    extra = len(m.bands)
    if extra != 1:
        shape += (extra,)
    return shape, m.typestr
Referenced by PIL.Image.Image.__array_interface__().
_decompression_bomb_check()
None PIL.Image._decompression_bomb_check (tuple[int, int] size) protected
Definition at line 3392 of file Image.py.
def _decompression_bomb_check(size: tuple[int, int]) -> None:
    if MAX_IMAGE_PIXELS is None:
        return
    pixels = max(1, size[0]) * max(1, size[1])
    if pixels > 2 * MAX_IMAGE_PIXELS:
        msg = (
            f"Image size ({pixels} pixels) exceeds limit of {2 * MAX_IMAGE_PIXELS} "
            "pixels, could be decompression bomb DOS attack."
        )
        raise DecompressionBombError(msg)
    if pixels > MAX_IMAGE_PIXELS:
        warnings.warn(
            f"Image size ({pixels} pixels) exceeds limit of {MAX_IMAGE_PIXELS} pixels, "
            "could be decompression bomb DOS attack.",
            DecompressionBombWarning,
        )
Referenced by PIL.Image.Image._crop(), and open().
_getdecoder()
core.ImagingDecoder | ImageFile.PyDecoder PIL.Image._getdecoder (str mode, str decoder_name, Any args, tuple[Any, ...] extra = ()) protected
Definition at line 420 of file Image.py.
) -> core.ImagingDecoder | ImageFile.PyDecoder:
    # tweak arguments
    if args is None:
        args = ()
    elif not isinstance(args, tuple):
        args = (args,)
    try:
        decoder = DECODERS[decoder_name]
    except KeyError:
        pass
    else:
        return decoder(mode, *args + extra)
    try:
        # get decoder
        decoder = getattr(core, f"{decoder_name}_decoder")
    except AttributeError as e:
        msg = f"decoder {decoder_name} not available"
        raise OSError(msg) from e
    return decoder(mode, *args + extra)
Referenced by PIL.Image.Image.frombytes().
_getencoder()
core.ImagingEncoder | ImageFile.PyEncoder PIL.Image._getencoder (str mode, str encoder_name, Any args, tuple[Any, ...] extra = ()) protected
Definition at line 445 of file Image.py.
) -> core.ImagingEncoder | ImageFile.PyEncoder:
    # tweak arguments
    if args is None:
        args = ()
    elif not isinstance(args, tuple):
        args = (args,)
    try:
        encoder = ENCODERS[encoder_name]
    except KeyError:
        pass
    else:
        return encoder(mode, *args + extra)
    try:
        # get encoder
        encoder = getattr(core, f"{encoder_name}_encoder")
    except AttributeError as e:
        msg = f"encoder {encoder_name} not available"
        raise OSError(msg) from e
    return encoder(mode, *args + extra)
# --------------------------------------------------------------------
# Simple expression analyzer
_getscaleoffset()
tuple[float, float] PIL.Image._getscaleoffset (Callable[[ImagePointTransform], ImagePointTransform | float] expr) protected
Definition at line 516 of file Image.py.
) -> tuple[float, float]:
    a = expr(ImagePointTransform(1, 0))
    return (a.scale, a.offset) if isinstance(a, ImagePointTransform) else (0, a)
# --------------------------------------------------------------------
# Implementation wrapper
Referenced by PIL.Image.Image.point().
_show()
None PIL.Image._show (Image image, **Any options) protected
Definition at line 3772 of file Image.py.
def _show(image: Image, **options: Any) -> None:
    from . import ImageShow
    ImageShow.show(image, **options)
# --------------------------------------------------------------------
# Effects
Referenced by PIL.Image.Image.show().
_wedge()
Image PIL.Image._wedge () protected
Create grayscale wedge (for debugging only)
Definition at line 3062 of file Image.py.
def _wedge() -> Image:
    """Create grayscale wedge (for debugging only)"""
    return Image()._new(core.wedge("L"))
alpha_composite()
Image PIL.Image.alpha_composite (Image im1, Image im2)
Alpha composite im2 over im1.
:param im1: The first image. Must have mode RGBA.
:param im2: The second image.  Must have mode RGBA, and the same size as
   the first image.
:returns: An :py:class:`~PIL.Image.Image` object.
Definition at line 3543 of file Image.py.
def alpha_composite(im1: Image, im2: Image) -> Image:
    """
    Alpha composite im2 over im1.
    :param im1: The first image. Must have mode RGBA.
    :param im2: The second image.  Must have mode RGBA, and the same size as
       the first image.
    :returns: An :py:class:`~PIL.Image.Image` object.
    """
    im1.load()
    im2.load()
    return im1._new(core.alpha_composite(im1.im, im2.im))
blend()
Image PIL.Image.blend (Image im1, Image im2, float alpha)
Creates a new image by interpolating between two input images, using
a constant alpha::
    out = image1 * (1.0 - alpha) + image2 * alpha
:param im1: The first image.
:param im2: The second image.  Must have the same mode and size as
   the first image.
:param alpha: The interpolation alpha factor.  If alpha is 0.0, a
   copy of the first image is returned. If alpha is 1.0, a copy of
   the second image is returned. There are no restrictions on the
   alpha value. If necessary, the result is clipped to fit into
   the allowed output range.
:returns: An :py:class:`~PIL.Image.Image` object.
Definition at line 3558 of file Image.py.
def blend(im1: Image, im2: Image, alpha: float) -> Image:
    """
    Creates a new image by interpolating between two input images, using
    a constant alpha::
        out = image1 * (1.0 - alpha) + image2 * alpha
    :param im1: The first image.
    :param im2: The second image.  Must have the same mode and size as
       the first image.
    :param alpha: The interpolation alpha factor.  If alpha is 0.0, a
       copy of the first image is returned. If alpha is 1.0, a copy of
       the second image is returned. There are no restrictions on the
       alpha value. If necessary, the result is clipped to fit into
       the allowed output range.
    :returns: An :py:class:`~PIL.Image.Image` object.
    """
    im1.load()
    im2.load()
    return im1._new(core.blend(im1.im, im2.im, alpha))
composite()
Image PIL.Image.composite (Image image1, Image image2, Image mask)
Create composite image by blending images using a transparency mask.
:param image1: The first image.
:param image2: The second image.  Must have the same mode and
   size as the first image.
:param mask: A mask image.  This image can have mode
   "1", "L", or "RGBA", and must have the same size as the
   other two images.
Definition at line 3581 of file Image.py.
def composite(image1: Image, image2: Image, mask: Image) -> Image:
    """
    Create composite image by blending images using a transparency mask.
    :param image1: The first image.
    :param image2: The second image.  Must have the same mode and
       size as the first image.
    :param mask: A mask image.  This image can have mode
       "1", "L", or "RGBA", and must have the same size as the
       other two images.
    """
    image = image2.copy()
    image.paste(image1, None, mask)
    return image
effect_mandelbrot()
Image PIL.Image.effect_mandelbrot (tuple[int, int] size, tuple[float, float, float, float] extent, int quality)
Generate a Mandelbrot set covering the given extent.
:param size: The requested size in pixels, as a 2-tuple:
   (width, height).
:param extent: The extent to cover, as a 4-tuple:
   (x0, y0, x1, y1).
:param quality: Quality.
Definition at line 3782 of file Image.py.
) -> Image:
    """
    Generate a Mandelbrot set covering the given extent.
    :param size: The requested size in pixels, as a 2-tuple:
       (width, height).
    :param extent: The extent to cover, as a 4-tuple:
       (x0, y0, x1, y1).
    :param quality: Quality.
    """
    return Image()._new(core.effect_mandelbrot(size, extent, quality))
effect_noise()
Image PIL.Image.effect_noise (tuple[int, int] size, float sigma)
Generate Gaussian noise centered around 128.
:param size: The requested size in pixels, as a 2-tuple:
   (width, height).
:param sigma: Standard deviation of noise.
Definition at line 3797 of file Image.py.
def effect_noise(size: tuple[int, int], sigma: float) -> Image:
    """
    Generate Gaussian noise centered around 128.
    :param size: The requested size in pixels, as a 2-tuple:
       (width, height).
    :param sigma: Standard deviation of noise.
    """
    return Image()._new(core.effect_noise(size, sigma))
eval()
Image PIL.Image.eval (Image image, *Callable[[int], float] args)
Applies the function (which should take one argument) to each pixel
in the given image. If the image has more than one band, the same
function is applied to each band. Note that the function is
evaluated once for each possible pixel value, so you cannot use
random components or other generators.
:param image: The input image.
:param function: A function object, taking one integer argument.
:returns: An :py:class:`~PIL.Image.Image` object.
Definition at line 3598 of file Image.py.
def eval(image: Image, *args: Callable[[int], float]) -> Image:
    """
    Applies the function (which should take one argument) to each pixel
    in the given image. If the image has more than one band, the same
    function is applied to each band. Note that the function is
    evaluated once for each possible pixel value, so you cannot use
    random components or other generators.
    :param image: The input image.
    :param function: A function object, taking one integer argument.
    :returns: An :py:class:`~PIL.Image.Image` object.
    """
    return image.point(args[0])
fromarray()
Image PIL.Image.fromarray (SupportsArrayInterface obj, str | None mode = None)
Creates an image memory from an object exporting the array interface
(using the buffer protocol)::
  from PIL import Image
  import numpy as np
  a = np.zeros((5, 5))
  im = Image.fromarray(a)
If ``obj`` is not contiguous, then the ``tobytes`` method is called
and :py:func:`~PIL.Image.frombuffer` is used.
In the case of NumPy, be aware that Pillow modes do not always correspond
to NumPy dtypes. Pillow modes only offer 1-bit pixels, 8-bit pixels,
32-bit signed integer pixels, and 32-bit floating point pixels.
Pillow images can also be converted to arrays::
  from PIL import Image
  import numpy as np
  im = Image.open("hopper.jpg")
  a = np.asarray(im)
When converting Pillow images to arrays however, only pixel values are
transferred. This means that P and PA mode images will lose their palette.
:param obj: Object with array interface
:param mode: Optional mode to use when reading ``obj``. Will be determined from
  type if ``None``.
  This will not be used to convert the data after reading, but will be used to
  change how the data is read::
    from PIL import Image
    import numpy as np
    a = np.full((1, 1), 300)
    im = Image.fromarray(a, mode="L")
    im.getpixel((0, 0))  # 44
    im = Image.fromarray(a, mode="RGB")
    im.getpixel((0, 0))  # (44, 1, 0)
  See: :ref:`concept-modes` for general information about modes.
:returns: An image object.
.. versionadded:: 1.1.6
Definition at line 3257 of file Image.py.
def fromarray(obj: SupportsArrayInterface, mode: str | None = None) -> Image:
    """
    Creates an image memory from an object exporting the array interface
    (using the buffer protocol)::
      from PIL import Image
      import numpy as np
      a = np.zeros((5, 5))
      im = Image.fromarray(a)
    If ``obj`` is not contiguous, then the ``tobytes`` method is called
    and :py:func:`~PIL.Image.frombuffer` is used.
    In the case of NumPy, be aware that Pillow modes do not always correspond
    to NumPy dtypes. Pillow modes only offer 1-bit pixels, 8-bit pixels,
    32-bit signed integer pixels, and 32-bit floating point pixels.
    Pillow images can also be converted to arrays::
      from PIL import Image
      import numpy as np
      im = Image.open("hopper.jpg")
      a = np.asarray(im)
    When converting Pillow images to arrays however, only pixel values are
    transferred. This means that P and PA mode images will lose their palette.
    :param obj: Object with array interface
    :param mode: Optional mode to use when reading ``obj``. Will be determined from
      type if ``None``.
      This will not be used to convert the data after reading, but will be used to
      change how the data is read::
        from PIL import Image
        import numpy as np
        a = np.full((1, 1), 300)
        im = Image.fromarray(a, mode="L")
        im.getpixel((0, 0))  # 44
        im = Image.fromarray(a, mode="RGB")
        im.getpixel((0, 0))  # (44, 1, 0)
      See: :ref:`concept-modes` for general information about modes.
    :returns: An image object.
    .. versionadded:: 1.1.6
    """
    arr = obj.__array_interface__
    shape = arr["shape"]
    ndim = len(shape)
    strides = arr.get("strides", None)
    if mode is None:
        try:
            typekey = (1, 1) + shape[2:], arr["typestr"]
        except KeyError as e:
            msg = "Cannot handle this data type"
            raise TypeError(msg) from e
        try:
            mode, rawmode = _fromarray_typemap[typekey]
        except KeyError as e:
            typekey_shape, typestr = typekey
            msg = f"Cannot handle this data type: {typekey_shape}, {typestr}"
            raise TypeError(msg) from e
    else:
        rawmode = mode
    if mode in ["1", "L", "I", "P", "F"]:
        ndmax = 2
    elif mode == "RGB":
        ndmax = 3
    else:
        ndmax = 4
    if ndim > ndmax:
        msg = f"Too many dimensions: {ndim} > {ndmax}."
        raise ValueError(msg)
    size = 1 if ndim == 1 else shape[1], shape[0]
    if strides is not None:
        if hasattr(obj, "tobytes"):
            obj = obj.tobytes()
        elif hasattr(obj, "tostring"):
            obj = obj.tostring()
        else:
            msg = "'strides' requires either tobytes() or tostring()"
            raise ValueError(msg)
    return frombuffer(mode, size, obj, "raw", rawmode, 0, 1)
References frombuffer().
frombuffer()
Image PIL.Image.frombuffer (str mode, tuple[int, int] size, bytes | SupportsArrayInterface data, str decoder_name = "raw", *Any args)
Creates an image memory referencing pixel data in a byte buffer.
This function is similar to :py:func:`~PIL.Image.frombytes`, but uses data
in the byte buffer, where possible.  This means that changes to the
original buffer object are reflected in this image).  Not all modes can
share memory; supported modes include "L", "RGBX", "RGBA", and "CMYK".
Note that this function decodes pixel data only, not entire images.
If you have an entire image file in a string, wrap it in a
:py:class:`~io.BytesIO` object, and use :py:func:`~PIL.Image.open` to load it.
The default parameters used for the "raw" decoder differs from that used for
:py:func:`~PIL.Image.frombytes`. This is a bug, and will probably be fixed in a
future release. The current release issues a warning if you do this; to disable
the warning, you should provide the full set of parameters. See below for details.
:param mode: The image mode. See: :ref:`concept-modes`.
:param size: The image size.
:param data: A bytes or other buffer object containing raw
    data for the given mode.
:param decoder_name: What decoder to use.
:param args: Additional parameters for the given decoder.  For the
    default encoder ("raw"), it's recommended that you provide the
    full set of parameters::
        frombuffer(mode, size, data, "raw", mode, 0, 1)
:returns: An :py:class:`~PIL.Image.Image` object.
.. versionadded:: 1.1.4
Definition at line 3185 of file Image.py.
) -> Image:
    """
    Creates an image memory referencing pixel data in a byte buffer.
    This function is similar to :py:func:`~PIL.Image.frombytes`, but uses data
    in the byte buffer, where possible.  This means that changes to the
    original buffer object are reflected in this image).  Not all modes can
    share memory; supported modes include "L", "RGBX", "RGBA", and "CMYK".
    Note that this function decodes pixel data only, not entire images.
    If you have an entire image file in a string, wrap it in a
    :py:class:`~io.BytesIO` object, and use :py:func:`~PIL.Image.open` to load it.
    The default parameters used for the "raw" decoder differs from that used for
    :py:func:`~PIL.Image.frombytes`. This is a bug, and will probably be fixed in a
    future release. The current release issues a warning if you do this; to disable
    the warning, you should provide the full set of parameters. See below for details.
    :param mode: The image mode. See: :ref:`concept-modes`.
    :param size: The image size.
    :param data: A bytes or other buffer object containing raw
        data for the given mode.
    :param decoder_name: What decoder to use.
    :param args: Additional parameters for the given decoder.  For the
        default encoder ("raw"), it's recommended that you provide the
        full set of parameters::
            frombuffer(mode, size, data, "raw", mode, 0, 1)
    :returns: An :py:class:`~PIL.Image.Image` object.
    .. versionadded:: 1.1.4
    """
    _check_size(size)
    # may pass tuple instead of argument list
    if len(args) == 1 and isinstance(args[0], tuple):
        args = args[0]
    if decoder_name == "raw":
        if args == ():
            args = mode, 0, 1
        if args[0] in _MAPMODES:
            im = new(mode, (0, 0))
            im = im._new(core.map_buffer(data, size, decoder_name, 0, args))
            if mode == "P":
                from . import ImagePalette
                im.palette = ImagePalette.ImagePalette("RGB", im.im.getpalette("RGB"))
            im.readonly = 1
            return im
    return frombytes(mode, size, data, decoder_name, args)
References _check_size(), frombytes(), and new().
Referenced by fromarray().
frombytes()
Image PIL.Image.frombytes (str mode, tuple[int, int] size, bytes | bytearray | SupportsArrayInterface data, str decoder_name = "raw", *Any args)
Creates a copy of an image memory from pixel data in a buffer.
In its simplest form, this function takes three arguments
(mode, size, and unpacked pixel data).
You can also use any pixel decoder supported by PIL. For more
information on available decoders, see the section
:ref:`Writing Your Own File Codec <file-codecs>`.
Note that this function decodes pixel data only, not entire images.
If you have an entire image in a string, wrap it in a
:py:class:`~io.BytesIO` object, and use :py:func:`~PIL.Image.open` to load
it.
:param mode: The image mode. See: :ref:`concept-modes`.
:param size: The image size.
:param data: A byte buffer containing raw data for the given mode.
:param decoder_name: What decoder to use.
:param args: Additional parameters for the given decoder.
:returns: An :py:class:`~PIL.Image.Image` object.
Definition at line 3139 of file Image.py.
) -> Image:
    """
    Creates a copy of an image memory from pixel data in a buffer.
    In its simplest form, this function takes three arguments
    (mode, size, and unpacked pixel data).
    You can also use any pixel decoder supported by PIL. For more
    information on available decoders, see the section
    :ref:`Writing Your Own File Codec <file-codecs>`.
    Note that this function decodes pixel data only, not entire images.
    If you have an entire image in a string, wrap it in a
    :py:class:`~io.BytesIO` object, and use :py:func:`~PIL.Image.open` to load
    it.
    :param mode: The image mode. See: :ref:`concept-modes`.
    :param size: The image size.
    :param data: A byte buffer containing raw data for the given mode.
    :param decoder_name: What decoder to use.
    :param args: Additional parameters for the given decoder.
    :returns: An :py:class:`~PIL.Image.Image` object.
    """
    _check_size(size)
    im = new(mode, size)
    if im.width != 0 and im.height != 0:
        decoder_args: Any = args
        if len(decoder_args) == 1 and isinstance(decoder_args[0], tuple):
            # may pass tuple instead of argument list
            decoder_args = decoder_args[0]
        if decoder_name == "raw" and decoder_args == ():
            decoder_args = mode
        im.frombytes(data, decoder_name, decoder_args)
    return im
References _check_size(), and new().
Referenced by frombuffer().
fromqimage()
ImageFile.ImageFile PIL.Image.fromqimage (ImageQt.QImage im)
Creates an image instance from a QImage image
Definition at line 3345 of file Image.py.
def fromqimage(im: ImageQt.QImage) -> ImageFile.ImageFile:
    """Creates an image instance from a QImage image"""
    from . import ImageQt
    if not ImageQt.qt_is_installed:
        msg = "Qt bindings are not installed"
        raise ImportError(msg)
    return ImageQt.fromqimage(im)
fromqpixmap()
ImageFile.ImageFile PIL.Image.fromqpixmap (ImageQt.QPixmap im)
Creates an image instance from a QPixmap image
Definition at line 3355 of file Image.py.
def fromqpixmap(im: ImageQt.QPixmap) -> ImageFile.ImageFile:
    """Creates an image instance from a QPixmap image"""
    from . import ImageQt
    if not ImageQt.qt_is_installed:
        msg = "Qt bindings are not installed"
        raise ImportError(msg)
    return ImageQt.fromqpixmap(im)
getmodebandnames()
tuple[str, ...] PIL.Image.getmodebandnames (str mode)
Gets a list of individual band names.  Given a mode, this function returns
a tuple containing the names of individual bands (use
:py:method:`~PIL.Image.getmodetype` to get the mode used to store each
individual band.
:param mode: Input mode.
:returns: A tuple containing band names.  The length of the tuple
    gives the number of bands in an image of the given mode.
:exception KeyError: If the input mode was not a standard mode.
Definition at line 312 of file Image.py.
def getmodebandnames(mode: str) -> tuple[str, ...]:
    """
    Gets a list of individual band names.  Given a mode, this function returns
    a tuple containing the names of individual bands (use
    :py:method:`~PIL.Image.getmodetype` to get the mode used to store each
    individual band.
    :param mode: Input mode.
    :returns: A tuple containing band names.  The length of the tuple
        gives the number of bands in an image of the given mode.
    :exception KeyError: If the input mode was not a standard mode.
    """
    return ImageMode.getmode(mode).bands
getmodebands()
int PIL.Image.getmodebands (str mode)
Gets the number of individual bands for this mode.
:param mode: Input mode.
:returns: The number of bands in this mode.
:exception KeyError: If the input mode was not a standard mode.
Definition at line 327 of file Image.py.
def getmodebands(mode: str) -> int:
    """
    Gets the number of individual bands for this mode.
    :param mode: Input mode.
    :returns: The number of bands in this mode.
    :exception KeyError: If the input mode was not a standard mode.
    """
    return len(ImageMode.getmode(mode).bands)
# --------------------------------------------------------------------
# Helpers
Referenced by merge().
getmodebase()
str PIL.Image.getmodebase (str mode)
Gets the "base" mode for given mode.  This function returns "L" for
images that contain grayscale data, and "RGB" for images that
contain color data.
:param mode: Input mode.
:returns: "L" or "RGB".
:exception KeyError: If the input mode was not a standard mode.
Definition at line 287 of file Image.py.
def getmodebase(mode: str) -> str:
    """
    Gets the "base" mode for given mode.  This function returns "L" for
    images that contain grayscale data, and "RGB" for images that
    contain color data.
    :param mode: Input mode.
    :returns: "L" or "RGB".
    :exception KeyError: If the input mode was not a standard mode.
    """
    return ImageMode.getmode(mode).basemode
Referenced by PIL.Image.Image.putalpha().
getmodetype()
str PIL.Image.getmodetype (str mode)
Gets the storage type mode.  Given a mode, this function returns a
single-layer mode suitable for storing individual bands.
:param mode: Input mode.
:returns: "L", "I", or "F".
:exception KeyError: If the input mode was not a standard mode.
Definition at line 300 of file Image.py.
def getmodetype(mode: str) -> str:
    """
    Gets the storage type mode.  Given a mode, this function returns a
    single-layer mode suitable for storing individual bands.
    :param mode: Input mode.
    :returns: "L", "I", or "F".
    :exception KeyError: If the input mode was not a standard mode.
    """
    return ImageMode.getmode(mode).basetype
Referenced by merge().
init()
bool PIL.Image.init ()
Explicitly initializes the Python Imaging Library. This function
loads all available file format drivers.
It is called when opening or saving images if :py:meth:`~preinit()` is
insufficient, and by :py:meth:`~PIL.features.pilinfo`.
Definition at line 389 of file Image.py.
def init() -> bool:
    """
    Explicitly initializes the Python Imaging Library. This function
    loads all available file format drivers.
    It is called when opening or saving images if :py:meth:`~preinit()` is
    insufficient, and by :py:meth:`~PIL.features.pilinfo`.
    """
    global _initialized
    if _initialized >= 2:
        return False
    parent_name = __name__.rpartition(".")[0]
    for plugin in _plugins:
        try:
            logger.debug("Importing %s", plugin)
            __import__(f"{parent_name}.{plugin}", globals(), locals(), [])
        except ImportError as e:
            logger.debug("Image: failed to import %s: %s", plugin, e)
    if OPEN or SAVE:
        _initialized = 2
        return True
    return False
# --------------------------------------------------------------------
# Codec factories (used by tobytes/frombytes and ImageFile.load)
Referenced by open(), and registered_extensions().
isImageType()
TypeGuard[Image] PIL.Image.isImageType (Any t)
Checks if an object is an image object.
.. warning::
   This function is for internal use only.
:param t: object to check if it's an image
:returns: True if the object is an image
Definition at line 125 of file Image.py.
def isImageType(t: Any) -> TypeGuard[Image]:
    """
    Checks if an object is an image object.
    .. warning::
       This function is for internal use only.
    :param t: object to check if it's an image
    :returns: True if the object is an image
    """
    deprecate("Image.isImageType(im)", 12, "isinstance(im, Image.Image)")
    return hasattr(t, "im")
#
# Constants
# transpose
linear_gradient()
Image PIL.Image.linear_gradient (str mode)
Generate 256x256 linear gradient from black to white, top to bottom.
:param mode: Input mode.
Definition at line 3808 of file Image.py.
def linear_gradient(mode: str) -> Image:
    """
    Generate 256x256 linear gradient from black to white, top to bottom.
    :param mode: Input mode.
    """
    return Image()._new(core.linear_gradient(mode))
merge()
Image PIL.Image.merge (str mode, Sequence[Image] bands)
Merge a set of single band images into a new multiband image.
:param mode: The mode to use for the output image. See:
    :ref:`concept-modes`.
:param bands: A sequence containing one single-band image for
    each band in the output image.  All bands must have the
    same size.
:returns: An :py:class:`~PIL.Image.Image` object.
Definition at line 3614 of file Image.py.
def merge(mode: str, bands: Sequence[Image]) -> Image:
    """
    Merge a set of single band images into a new multiband image.
    :param mode: The mode to use for the output image. See:
        :ref:`concept-modes`.
    :param bands: A sequence containing one single-band image for
        each band in the output image.  All bands must have the
        same size.
    :returns: An :py:class:`~PIL.Image.Image` object.
    """
    if getmodebands(mode) != len(bands) or "*" in mode:
        msg = "wrong number of bands"
        raise ValueError(msg)
    for band in bands[1:]:
        if band.mode != getmodetype(mode):
            msg = "mode mismatch"
            raise ValueError(msg)
        if band.size != bands[0].size:
            msg = "size mismatch"
            raise ValueError(msg)
    for band in bands:
        band.load()
    return bands[0]._new(core.merge(mode, *[b.im for b in bands]))
# --------------------------------------------------------------------
# Plugin registry
References getmodebands(), and getmodetype().
Referenced by PIL.Image.Image.filter().
new()
Image PIL.Image.new (str mode, tuple[int, int] | list[int] size, float | tuple[float, ...] | str | None color = 0)
Creates a new image with the given mode and size.
:param mode: The mode to use for the new image. See:
   :ref:`concept-modes`.
:param size: A 2-tuple, containing (width, height) in pixels.
:param color: What color to use for the image.  Default is black.
   If given, this should be a single integer or floating point value
   for single-band modes, and a tuple for multi-band modes (one value
   per band).  When creating RGB or HSV images, you can also use color
   strings as supported by the ImageColor module.  If the color is
   None, the image is not initialised.
:returns: An :py:class:`~PIL.Image.Image` object.
Definition at line 3087 of file Image.py.
) -> Image:
    """
    Creates a new image with the given mode and size.
    :param mode: The mode to use for the new image. See:
       :ref:`concept-modes`.
    :param size: A 2-tuple, containing (width, height) in pixels.
    :param color: What color to use for the image.  Default is black.
       If given, this should be a single integer or floating point value
       for single-band modes, and a tuple for multi-band modes (one value
       per band).  When creating RGB or HSV images, you can also use color
       strings as supported by the ImageColor module.  If the color is
       None, the image is not initialised.
    :returns: An :py:class:`~PIL.Image.Image` object.
    """
    if mode in ("BGR;15", "BGR;16", "BGR;24"):
        deprecate(mode, 12)
    _check_size(size)
    if color is None:
        # don't initialize
        return Image()._new(core.new(mode, size))
    if isinstance(color, str):
        # css3-style specifier
        from . import ImageColor
        color = ImageColor.getcolor(color, mode)
    im = Image()
    if (
        mode == "P"
        and isinstance(color, (list, tuple))
        and all(isinstance(i, int) for i in color)
    ):
        color_ints: tuple[int, ...] = cast(tuple[int, ...], tuple(color))
        if len(color_ints) == 3 or len(color_ints) == 4:
            # RGB or RGBA value for a P image
            from . import ImagePalette
            im.palette = ImagePalette.ImagePalette()
            color = im.palette.getcolor(color_ints)
    return im._new(core.fill(mode, size, color))
References _check_size().
Referenced by frombuffer(), frombytes(), PIL.Image.Image.putalpha(), and PIL.Image.Image.transform().
open()
ImageFile.ImageFile PIL.Image.open (StrOrBytesPath | IO[bytes] fp, Literal["r"] mode = "r", list[str] | tuple[str, ...] | None formats = None)
Opens and identifies the given image file.
This is a lazy operation; this function identifies the file, but
the file remains open and the actual image data is not read from
the file until you try to process the data (or call the
:py:meth:`~PIL.Image.Image.load` method).  See
:py:func:`~PIL.Image.new`. See :ref:`file-handling`.
:param fp: A filename (string), os.PathLike object or a file object.
   The file object must implement ``file.read``,
   ``file.seek``, and ``file.tell`` methods,
   and be opened in binary mode. The file object will also seek to zero
   before reading.
:param mode: The mode.  If given, this argument must be "r".
:param formats: A list or tuple of formats to attempt to load the file in.
   This can be used to restrict the set of formats checked.
   Pass ``None`` to try all supported formats. You can print the set of
   available formats by running ``python3 -m PIL`` or using
   the :py:func:`PIL.features.pilinfo` function.
:returns: An :py:class:`~PIL.Image.Image` object.
:exception FileNotFoundError: If the file cannot be found.
:exception PIL.UnidentifiedImageError: If the image cannot be opened and
   identified.
:exception ValueError: If the ``mode`` is not "r", or if a ``StringIO``
   instance is used for ``fp``.
:exception TypeError: If ``formats`` is not ``None``, a list or a tuple.
Definition at line 3413 of file Image.py.
) -> ImageFile.ImageFile:
    """
    Opens and identifies the given image file.
    This is a lazy operation; this function identifies the file, but
    the file remains open and the actual image data is not read from
    the file until you try to process the data (or call the
    :py:meth:`~PIL.Image.Image.load` method).  See
    :py:func:`~PIL.Image.new`. See :ref:`file-handling`.
    :param fp: A filename (string), os.PathLike object or a file object.
       The file object must implement ``file.read``,
       ``file.seek``, and ``file.tell`` methods,
       and be opened in binary mode. The file object will also seek to zero
       before reading.
    :param mode: The mode.  If given, this argument must be "r".
    :param formats: A list or tuple of formats to attempt to load the file in.
       This can be used to restrict the set of formats checked.
       Pass ``None`` to try all supported formats. You can print the set of
       available formats by running ``python3 -m PIL`` or using
       the :py:func:`PIL.features.pilinfo` function.
    :returns: An :py:class:`~PIL.Image.Image` object.
    :exception FileNotFoundError: If the file cannot be found.
    :exception PIL.UnidentifiedImageError: If the image cannot be opened and
       identified.
    :exception ValueError: If the ``mode`` is not "r", or if a ``StringIO``
       instance is used for ``fp``.
    :exception TypeError: If ``formats`` is not ``None``, a list or a tuple.
    """
    if mode != "r":
        msg = f"bad mode {repr(mode)}"  # type: ignore[unreachable]
        raise ValueError(msg)
    elif isinstance(fp, io.StringIO):
        msg = (  # type: ignore[unreachable]
            "StringIO cannot be used to open an image. "
            "Binary data must be used instead."
        )
        raise ValueError(msg)
    if formats is None:
        formats = ID
    elif not isinstance(formats, (list, tuple)):
        msg = "formats must be a list or tuple"  # type: ignore[unreachable]
        raise TypeError(msg)
    exclusive_fp = False
    filename: str | bytes = ""
    if is_path(fp):
        filename = os.path.realpath(os.fspath(fp))
    if filename:
        fp = builtins.open(filename, "rb")
        exclusive_fp = True
    else:
        fp = cast(IO[bytes], fp)
    try:
        fp.seek(0)
    except (AttributeError, io.UnsupportedOperation):
        fp = io.BytesIO(fp.read())
        exclusive_fp = True
    prefix = fp.read(16)
    preinit()
    warning_messages: list[str] = []
    def _open_core(
        fp: IO[bytes],
        filename: str | bytes,
        prefix: bytes,
        formats: list[str] | tuple[str, ...],
    ) -> ImageFile.ImageFile | None:
        for i in formats:
            i = i.upper()
            if i not in OPEN:
                init()
            try:
                factory, accept = OPEN[i]
                result = not accept or accept(prefix)
                if isinstance(result, str):
                    warning_messages.append(result)
                elif result:
                    fp.seek(0)
                    im = factory(fp, filename)
                    _decompression_bomb_check(im.size)
                    return im
            except (SyntaxError, IndexError, TypeError, struct.error) as e:
                if WARN_POSSIBLE_FORMATS:
                    warning_messages.append(i + " opening failed. " + str(e))
            except BaseException:
                if exclusive_fp:
                    fp.close()
                raise
        return None
    im = _open_core(fp, filename, prefix, formats)
    if im is None and formats is ID:
        checked_formats = ID.copy()
        if init():
            im = _open_core(
                fp,
                filename,
                prefix,
                tuple(format for format in formats if format not in checked_formats),
            )
    if im:
        im._exclusive_fp = exclusive_fp
        return im
    if exclusive_fp:
        fp.close()
    for message in warning_messages:
        warnings.warn(message)
    msg = "cannot identify image file %r" % (filename if filename else fp)
    raise UnidentifiedImageError(msg)
#
# Image processing.
References _decompression_bomb_check(), init(), and preinit().
Referenced by PIL.Image.Image.get_child_images().
preinit()
None PIL.Image.preinit ()
Explicitly loads BMP, GIF, JPEG, PPM and PPM file format drivers.
It is called when opening or saving images.
Definition at line 344 of file Image.py.
def preinit() -> None:
    """
    Explicitly loads BMP, GIF, JPEG, PPM and PPM file format drivers.
    It is called when opening or saving images.
    """
    global _initialized
    if _initialized >= 1:
        return
    try:
        from . import BmpImagePlugin
        assert BmpImagePlugin
    except ImportError:
        pass
    try:
        from . import GifImagePlugin
        assert GifImagePlugin
    except ImportError:
        pass
    try:
        from . import JpegImagePlugin
        assert JpegImagePlugin
    except ImportError:
        pass
    try:
        from . import PpmImagePlugin
        assert PpmImagePlugin
    except ImportError:
        pass
    try:
        from . import PngImagePlugin
        assert PngImagePlugin
    except ImportError:
        pass
    _initialized = 1
Referenced by open().
radial_gradient()
Image PIL.Image.radial_gradient (str mode)
Generate 256x256 radial gradient from black to white, centre to edge.
:param mode: Input mode.
Definition at line 3817 of file Image.py.
def radial_gradient(mode: str) -> Image:
    """
    Generate 256x256 radial gradient from black to white, centre to edge.
    :param mode: Input mode.
    """
    return Image()._new(core.radial_gradient(mode))
# --------------------------------------------------------------------
# Resources
register_decoder()
None PIL.Image.register_decoder (str name, type[ImageFile.PyDecoder] decoder)
Registers an image decoder.  This function should not be
used in application code.
:param name: The name of the decoder
:param decoder: An ImageFile.PyDecoder object
.. versionadded:: 4.1.0
Definition at line 3742 of file Image.py.
def register_decoder(name: str, decoder: type[ImageFile.PyDecoder]) -> None:
    """
    Registers an image decoder.  This function should not be
    used in application code.
    :param name: The name of the decoder
    :param decoder: An ImageFile.PyDecoder object
    .. versionadded:: 4.1.0
    """
    DECODERS[name] = decoder
register_encoder()
None PIL.Image.register_encoder (str name, type[ImageFile.PyEncoder] encoder)
Registers an image encoder.  This function should not be
used in application code.
:param name: The name of the encoder
:param encoder: An ImageFile.PyEncoder object
.. versionadded:: 4.1.0
Definition at line 3755 of file Image.py.
def register_encoder(name: str, encoder: type[ImageFile.PyEncoder]) -> None:
    """
    Registers an image encoder.  This function should not be
    used in application code.
    :param name: The name of the encoder
    :param encoder: An ImageFile.PyEncoder object
    .. versionadded:: 4.1.0
    """
    ENCODERS[name] = encoder
# --------------------------------------------------------------------
# Simple display support.
register_extension()
None PIL.Image.register_extension (str id, str extension)
Registers an image extension.  This function should not be
used in application code.
:param id: An image format identifier.
:param extension: An extension used for this format.
Definition at line 3710 of file Image.py.
def register_extension(id: str, extension: str) -> None:
    """
    Registers an image extension.  This function should not be
    used in application code.
    :param id: An image format identifier.
    :param extension: An extension used for this format.
    """
    EXTENSION[extension.lower()] = id.upper()
Referenced by register_extensions().
register_extensions()
None PIL.Image.register_extensions (str id, list[str] extensions)
Registers image extensions.  This function should not be
used in application code.
:param id: An image format identifier.
:param extensions: A list of extensions used for this format.
Definition at line 3721 of file Image.py.
def register_extensions(id: str, extensions: list[str]) -> None:
    """
    Registers image extensions.  This function should not be
    used in application code.
    :param id: An image format identifier.
    :param extensions: A list of extensions used for this format.
    """
    for extension in extensions:
        register_extension(id, extension)
References register_extension().
register_mime()
None PIL.Image.register_mime (str id, str mimetype)
Registers an image MIME type by populating ``Image.MIME``. This function
should not be used in application code.
``Image.MIME`` provides a mapping from image format identifiers to mime
formats, but :py:meth:`~PIL.ImageFile.ImageFile.get_format_mimetype` can
provide a different result for specific images.
:param id: An image format identifier.
:param mimetype: The image MIME type for this format.
Definition at line 3668 of file Image.py.
def register_mime(id: str, mimetype: str) -> None:
    """
    Registers an image MIME type by populating ``Image.MIME``. This function
    should not be used in application code.
    ``Image.MIME`` provides a mapping from image format identifiers to mime
    formats, but :py:meth:`~PIL.ImageFile.ImageFile.get_format_mimetype` can
    provide a different result for specific images.
    :param id: An image format identifier.
    :param mimetype: The image MIME type for this format.
    """
    MIME[id.upper()] = mimetype
register_open()
None PIL.Image.register_open (str id, (Callable[[IO[bytes], str | bytes], ImageFile.ImageFile] | type[ImageFile.ImageFile]) factory, Callable[[bytes], bool | str] | None accept = None)
Register an image file plugin.  This function should not be used
in application code.
:param id: An image format identifier.
:param factory: An image file factory method.
:param accept: An optional function that can be used to quickly
   reject images having another format.
Definition at line 3645 of file Image.py.
) -> None:
    """
    Register an image file plugin.  This function should not be used
    in application code.
    :param id: An image format identifier.
    :param factory: An image file factory method.
    :param accept: An optional function that can be used to quickly
       reject images having another format.
    """
    id = id.upper()
    if id not in ID:
        ID.append(id)
    OPEN[id] = factory, accept
register_save()
None PIL.Image.register_save (str id, Callable[[Image, IO[bytes], str | bytes], None] driver)
Registers an image save function.  This function should not be
used in application code.
:param id: An image format identifier.
:param driver: A function to save images in this format.
Definition at line 3683 of file Image.py.
) -> None:
    """
    Registers an image save function.  This function should not be
    used in application code.
    :param id: An image format identifier.
    :param driver: A function to save images in this format.
    """
    SAVE[id.upper()] = driver
register_save_all()
None PIL.Image.register_save_all (str id, Callable[[Image, IO[bytes], str | bytes], None] driver)
Registers an image function to save all the frames
of a multiframe format.  This function should not be
used in application code.
:param id: An image format identifier.
:param driver: A function to save images in this format.
Definition at line 3696 of file Image.py.
) -> None:
    """
    Registers an image function to save all the frames
    of a multiframe format.  This function should not be
    used in application code.
    :param id: An image format identifier.
    :param driver: A function to save images in this format.
    """
    SAVE_ALL[id.upper()] = driver
registered_extensions()
dict[str, str] PIL.Image.registered_extensions ()
Returns a dictionary containing all file extensions belonging
to registered plugins
Definition at line 3733 of file Image.py.
def registered_extensions() -> dict[str, str]:
    """
    Returns a dictionary containing all file extensions belonging
    to registered plugins
    """
    init()
    return EXTENSION
References init().
Variable Documentation
_ENDIAN
str PIL.Image._ENDIAN = "little" else ">" protected
Definition at line 247 of file Image.py.
_ExifBase
PIL.Image._ExifBase = MutableMapping[int, Any] protected
Definition at line 3866 of file Image.py.
_filters_support
dict PIL.Image._filters_support protected
Initial value:
=  {
    Resampling.BOX: 0.5,
    Resampling.BILINEAR: 1.0,
    Resampling.HAMMING: 1.0,
    Resampling.BICUBIC: 2.0,
    Resampling.LANCZOS: 3.0,
}
Definition at line 174 of file Image.py.
_fromarray_typemap
dict PIL.Image._fromarray_typemap protected
Initial value:
=  {
    # (shape, typestr) => mode, rawmode
    # first two members of shape are set to one
    ((1, 1), "|b1"): ("1", "1;8"),
    ((1, 1), "|u1"): ("L", "L"),
    ((1, 1), "|i1"): ("I", "I;8"),
    ((1, 1), "<u2"): ("I", "I;16"),
    ((1, 1), ">u2"): ("I", "I;16B"),
    ((1, 1), "<i2"): ("I", "I;16S"),
    ((1, 1), ">i2"): ("I", "I;16BS"),
    ((1, 1), "<u4"): ("I", "I;32"),
    ((1, 1), ">u4"): ("I", "I;32B"),
    ((1, 1), "<i4"): ("I", "I;32S"),
    ((1, 1), ">i4"): ("I", "I;32BS"),
    ((1, 1), "<f4"): ("F", "F;32F"),
    ((1, 1), ">f4"): ("F", "F;32BF"),
    ((1, 1), "<f8"): ("F", "F;64F"),
    ((1, 1), ">f8"): ("F", "F;64BF"),
    ((1, 1, 2), "|u1"): ("LA", "LA"),
    ((1, 1, 3), "|u1"): ("RGB", "RGB"),
    ((1, 1, 4), "|u1"): ("RGBA", "RGBA"),
    # shortcuts:
    ((1, 1), f"{_ENDIAN}i4"): ("I", "I"),
    ((1, 1), f"{_ENDIAN}f4"): ("F", "F"),
}
Definition at line 3365 of file Image.py.
_initialized
int PIL.Image._initialized = 0 protected
Definition at line 341 of file Image.py.
_MAPMODES
tuple PIL.Image._MAPMODES = ("L", "P", "RGBX", "RGBA", "CMYK", "I;16", "I;16L", "I;16B") protected
Definition at line 284 of file Image.py.
core
PIL.Image.core = DeferredError.new(ImportError("The _imaging C module is not installed."))
Definition at line 108 of file Image.py.
DECODERS
dict PIL.Image.DECODERS = {}
Definition at line 241 of file Image.py.
DEFAULT_STRATEGY
PIL.Image.DEFAULT_STRATEGY = core.DEFAULT_STRATEGY
Definition at line 211 of file Image.py.
ElementTree
PIL.Image.ElementTree | None
Definition at line 68 of file Image.py.
ENCODERS
dict PIL.Image.ENCODERS = {}
Definition at line 242 of file Image.py.
EXTENSION
dict PIL.Image.EXTENSION = {}
Definition at line 240 of file Image.py.
FILTERED
PIL.Image.FILTERED = core.FILTERED
Definition at line 212 of file Image.py.
FIXED
PIL.Image.FIXED = core.FIXED
Definition at line 215 of file Image.py.
HUFFMAN_ONLY
PIL.Image.HUFFMAN_ONLY = core.HUFFMAN_ONLY
Definition at line 213 of file Image.py.
ID
list PIL.Image.ID = []
Definition at line 229 of file Image.py.
logger
PIL.Image.logger = logging.getLogger(__name__)
Definition at line 74 of file Image.py.
MIME
dict PIL.Image.MIME = {}
Definition at line 237 of file Image.py.
MODES
list PIL.Image.MODES
Initial value:
=  [
    "1",
    "CMYK",
    "F",
    "HSV",
    "I",
    "I;16",
    "I;16B",
    "I;16L",
    "I;16N",
    "L",
    "LA",
    "La",
    "LAB",
    "P",
    "PA",
    "RGB",
    "RGBA",
    "RGBa",
    "RGBX",
    "YCbCr",
]
Definition at line 259 of file Image.py.
module
PIL.Image.module = sys.modules[__name__]
Definition at line 204 of file Image.py.
OPEN
dict PIL.Image.OPEN = {}
Definition at line 230 of file Image.py.
RLE
PIL.Image.RLE = core.RLE
Definition at line 214 of file Image.py.
SAVE
dict PIL.Image.SAVE = {}
Definition at line 238 of file Image.py.
SAVE_ALL
dict PIL.Image.SAVE_ALL = {}
Definition at line 239 of file Image.py.