Read&Watch: pip._vendor.rich.console Namespace Reference
pip._vendor.rich.console Namespace Reference
Classes
class Capture
class CaptureError
class Console
class ConsoleDimensions
class ConsoleOptions
class ConsoleRenderable
class ConsoleThreadLocals
class Group
class NewLine
class NoChange
class PagerContext
class RenderHook
class RichCast
class ScreenContext
class ScreenUpdate
class ThemeContext
Functions
Callable[..., Callable[..., Group]] group (bool fit=True)
bool _is_jupyter ()
"WindowsConsoleFeatures" get_windows_console_features ()
bool detect_legacy_windows ()
str _svg_hash (str svg_main_code)
Variables
int JUPYTER_DEFAULT_COLUMNS = 115
int JUPYTER_DEFAULT_LINES = 100
str WINDOWS = "Windows"
HighlighterType = Callable[[Union[str, "Text"]], "Text"]
JustifyMethod = Literal["default", "left", "center", "right", "full"]
OverflowMethod = Literal["fold", "crop", "ellipsis", "ignore"]
NO_CHANGE = NoChange()
_STDIN_FILENO = sys.__stdin__.fileno()
_STDOUT_FILENO = sys.__stdout__.fileno()
_STDERR_FILENO = sys.__stderr__.fileno()
tuple _STD_STREAMS = (_STDIN_FILENO, _STDOUT_FILENO, _STDERR_FILENO)
tuple _STD_STREAMS_OUTPUT = (_STDOUT_FILENO, _STDERR_FILENO)
dict _TERM_COLORS
RenderableType = Union[ConsoleRenderable, RichCast, str]
RenderResult = Iterable[Union[RenderableType, Segment]]
_null_highlighter = NullHighlighter()
dict COLOR_SYSTEMS
dict _COLOR_SYSTEMS_NAMES = {system: name for name, system in COLOR_SYSTEMS.items()}
console = Console(record=True)
Function Documentation
_is_jupyter()
bool pip._vendor.rich.console._is_jupyter () protected
Check if we're running in a Jupyter notebook.
Definition at line 518 of file console.py.
def _is_jupyter() -> bool:  # pragma: no cover
    """Check if we're running in a Jupyter notebook."""
    try:
        get_ipython  # type: ignore[name-defined]
    except NameError:
        return False
    ipython = get_ipython()  # type: ignore[name-defined]
    shell = ipython.__class__.__name__
    if (
        "google.colab" in str(ipython.__class__)
        or os.getenv("DATABRICKS_RUNTIME_VERSION")
        or shell == "ZMQInteractiveShell"
    ):
        return True  # Jupyter notebook or qtconsole
    elif shell == "TerminalInteractiveShell":
        return False  # Terminal running IPython
    else:
        return False  # Other type (?)
_svg_hash()
str pip._vendor.rich.console._svg_hash (str svg_main_code) protected
Returns a unique hash for the given SVG main code.
Args:
    svg_main_code (str): The content we're going to inject in the SVG envelope.
Returns:
    str: a hash of the given content
Definition at line 2568 of file console.py.
def _svg_hash(svg_main_code: str) -> str:
    """Returns a unique hash for the given SVG main code.
    Args:
        svg_main_code (str): The content we're going to inject in the SVG envelope.
    Returns:
        str: a hash of the given content
    """
    return str(zlib.adler32(svg_main_code.encode()))
detect_legacy_windows()
bool pip._vendor.rich.console.detect_legacy_windows ()
Detect legacy Windows.
Definition at line 589 of file console.py.
def detect_legacy_windows() -> bool:
    """Detect legacy Windows."""
    return WINDOWS and not get_windows_console_features().vt
References get_windows_console_features().
get_windows_console_features()
"WindowsConsoleFeatures" pip._vendor.rich.console.get_windows_console_features ()
Definition at line 579 of file console.py.
def get_windows_console_features() -> "WindowsConsoleFeatures":  # pragma: no cover
    global _windows_console_features
    if _windows_console_features is not None:
        return _windows_console_features
    from ._windows import get_windows_console_features
    _windows_console_features = get_windows_console_features()
    return _windows_console_features
References get_windows_console_features().
Referenced by detect_legacy_windows(), and get_windows_console_features().
group()
Callable[..., Callable[..., Group]] pip._vendor.rich.console.group (bool fit = True)
A decorator that turns an iterable of renderables in to a group.
Args:
    fit (bool, optional): Fit dimension of group to contents, or fill available space. Defaults to True.
Definition at line 496 of file console.py.
def group(fit: bool = True) -> Callable[..., Callable[..., Group]]:
    """A decorator that turns an iterable of renderables in to a group.
    Args:
        fit (bool, optional): Fit dimension of group to contents, or fill available space. Defaults to True.
    """
    def decorator(
        method: Callable[..., Iterable[RenderableType]]
    ) -> Callable[..., Group]:
        """Convert a method that returns an iterable of renderables in to a Group."""
        @wraps(method)
        def _replace(*args: Any, **kwargs: Any) -> Group:
            renderables = method(*args, **kwargs)
            return Group(*renderables, fit=fit)
        return _replace
    return decorator
Variable Documentation
_COLOR_SYSTEMS_NAMES
dict pip._vendor.rich.console._COLOR_SYSTEMS_NAMES = {system: name for name, system in COLOR_SYSTEMS.items()} protected
Definition at line 545 of file console.py.
_null_highlighter
pip._vendor.rich.console._null_highlighter = NullHighlighter() protected
Definition at line 286 of file console.py.
_STD_STREAMS
tuple pip._vendor.rich.console._STD_STREAMS = (_STDIN_FILENO, _STDOUT_FILENO, _STDERR_FILENO) protected
Definition at line 105 of file console.py.
_STD_STREAMS_OUTPUT
tuple pip._vendor.rich.console._STD_STREAMS_OUTPUT = (_STDOUT_FILENO, _STDERR_FILENO) protected
Definition at line 106 of file console.py.
_STDERR_FILENO
int pip._vendor.rich.console._STDERR_FILENO = sys.__stderr__.fileno() protected
Definition at line 101 of file console.py.
_STDIN_FILENO
int pip._vendor.rich.console._STDIN_FILENO = sys.__stdin__.fileno() protected
Definition at line 93 of file console.py.
_STDOUT_FILENO
int pip._vendor.rich.console._STDOUT_FILENO = sys.__stdout__.fileno() protected
Definition at line 97 of file console.py.
_TERM_COLORS
dict pip._vendor.rich.console._TERM_COLORS protected
Initial value:
=  {
    "kitty": ColorSystem.EIGHT_BIT,
    "256color": ColorSystem.EIGHT_BIT,
    "16color": ColorSystem.STANDARD,
}
Definition at line 109 of file console.py.
COLOR_SYSTEMS
dict pip._vendor.rich.console.COLOR_SYSTEMS
Initial value:
=  {
    "standard": ColorSystem.STANDARD,
    "256": ColorSystem.EIGHT_BIT,
    "truecolor": ColorSystem.TRUECOLOR,
    "windows": ColorSystem.WINDOWS,
}
Definition at line 538 of file console.py.
console
pip._vendor.rich.console.console = Console(record=True)
Definition at line 2581 of file console.py.
HighlighterType
pip._vendor.rich.console.HighlighterType = Callable[[Union[str, "Text"]], "Text"]
Definition at line 81 of file console.py.
JUPYTER_DEFAULT_COLUMNS
int pip._vendor.rich.console.JUPYTER_DEFAULT_COLUMNS = 115
Definition at line 77 of file console.py.
JUPYTER_DEFAULT_LINES
int pip._vendor.rich.console.JUPYTER_DEFAULT_LINES = 100
Definition at line 78 of file console.py.
JustifyMethod
pip._vendor.rich.console.JustifyMethod = Literal["default", "left", "center", "right", "full"]
Definition at line 82 of file console.py.
NO_CHANGE
pip._vendor.rich.console.NO_CHANGE = NoChange()
Definition at line 90 of file console.py.
OverflowMethod
pip._vendor.rich.console.OverflowMethod = Literal["fold", "crop", "ellipsis", "ignore"]
Definition at line 83 of file console.py.
RenderableType
pip._vendor.rich.console.RenderableType = Union[ConsoleRenderable, RichCast, str]
Definition at line 280 of file console.py.
RenderResult
pip._vendor.rich.console.RenderResult = Iterable[Union[RenderableType, Segment]]
Definition at line 284 of file console.py.
WINDOWS
str pip._vendor.rich.console.WINDOWS = "Windows"
Definition at line 79 of file console.py.