Read&Watch: pip._internal.index.sources Namespace Reference
pip._internal.index.sources Namespace Reference
Classes
class _FlatDirectorySource
class _FlatDirectoryToUrls
class _IndexDirectorySource
class _LocalFileSource
class _RemoteFileSource
class LinkSource
Functions
bool _is_html_file (str file_url)
Tuple[Optional[str], Optional[LinkSource]] build_source (str location, *, CandidatesFromPage candidates_from_page, PageValidator page_validator, bool expand_dir, bool cache_link_parsing, str project_name)
Variables
logger = logging.getLogger(__name__)
FoundCandidates = Iterable[InstallationCandidate]
FoundLinks = Iterable[Link]
CandidatesFromPage = Callable[[Link], Iterable[InstallationCandidate]]
PageValidator = Callable[[Link], bool]
Function Documentation
_is_html_file()
bool pip._internal.index.sources._is_html_file (str file_url) protected
Definition at line 43 of file sources.py.
def _is_html_file(file_url: str) -> bool:
    return mimetypes.guess_type(file_url, strict=False)[0] == "text/html"
Referenced by pip._internal.index.sources._FlatDirectoryToUrls._scan_directory(), pip._internal.index.sources._LocalFileSource.file_links(), and pip._internal.index.sources._LocalFileSource.page_candidates().
build_source()
Tuple[Optional[str], Optional[LinkSource]] pip._internal.index.sources.build_source (str location, * , CandidatesFromPage candidates_from_page, PageValidator page_validator, bool expand_dir, bool cache_link_parsing, str project_name)
Definition at line 225 of file sources.py.
) -> Tuple[Optional[str], Optional[LinkSource]]:
    path: Optional[str] = None
    url: Optional[str] = None
    if os.path.exists(location):  # Is a local path.
        url = path_to_url(location)
        path = location
    elif location.startswith("file:"):  # A file: URL.
        url = location
        path = url_to_path(location)
    elif is_url(location):
        url = location
    if url is None:
        msg = (
            "Location '%s' is ignored: "
            "it is either a non-existing path or lacks a specific scheme."
        )
        logger.warning(msg, location)
        return (None, None)
    if path is None:
        source: LinkSource = _RemoteFileSource(
            candidates_from_page=candidates_from_page,
            page_validator=page_validator,
            link=Link(url, cache_link_parsing=cache_link_parsing),
        )
        return (url, source)
    if os.path.isdir(path):
        if expand_dir:
            source = _FlatDirectorySource(
                candidates_from_page=candidates_from_page,
                path=path,
                project_name=project_name,
            )
        else:
            source = _IndexDirectorySource(
                candidates_from_page=candidates_from_page,
                link=Link(url, cache_link_parsing=cache_link_parsing),
            )
        return (url, source)
    elif os.path.isfile(path):
        source = _LocalFileSource(
            candidates_from_page=candidates_from_page,
            link=Link(url, cache_link_parsing=cache_link_parsing),
        )
        return (url, source)
    logger.warning(
        "Location '%s' is ignored: it is neither a file nor a directory.",
        location,
    )
    return (url, None)
Variable Documentation
CandidatesFromPage
pip._internal.index.sources.CandidatesFromPage = Callable[[Link], Iterable[InstallationCandidate]]
Definition at line 24 of file sources.py.
FoundCandidates
pip._internal.index.sources.FoundCandidates = Iterable[InstallationCandidate]
Definition at line 22 of file sources.py.
FoundLinks
pip._internal.index.sources.FoundLinks = Iterable[Link]
Definition at line 23 of file sources.py.
logger
pip._internal.index.sources.logger = logging.getLogger(__name__)
Definition at line 20 of file sources.py.
PageValidator
pip._internal.index.sources.PageValidator = Callable[[Link], bool]
Definition at line 25 of file sources.py.