Read&Watch: yaml Namespace Reference
yaml Namespace Reference
Namespaces
namespace composer
namespace constructor
namespace cyaml
namespace dumper
namespace emitter
namespace error
namespace events
namespace loader
namespace nodes
namespace parser
namespace reader
namespace representer
namespace resolver
namespace scanner
namespace serializer
namespace tokens
Classes
class YAMLObject
class YAMLObjectMetaclass
Functions
warnings (settings=None)
scan (stream, Loader=Loader)
parse (stream, Loader=Loader)
compose (stream, Loader=Loader)
compose_all (stream, Loader=Loader)
load (stream, Loader)
load_all (stream, Loader)
full_load (stream)
full_load_all (stream)
safe_load (stream)
safe_load_all (stream)
unsafe_load (stream)
unsafe_load_all (stream)
emit (events, stream=None, Dumper=Dumper, canonical=None, indent=None, width=None, allow_unicode=None, line_break=None)
serialize_all (nodes, stream=None, Dumper=Dumper, canonical=None, indent=None, width=None, allow_unicode=None, line_break=None, encoding=None, explicit_start=None, explicit_end=None, version=None, tags=None)
serialize (node, stream=None, Dumper=Dumper, **kwds)
dump_all (documents, stream=None, Dumper=Dumper, default_style=None, default_flow_style=False, canonical=None, indent=None, width=None, allow_unicode=None, line_break=None, encoding=None, explicit_start=None, explicit_end=None, version=None, tags=None, sort_keys=True)
dump (data, stream=None, Dumper=Dumper, **kwds)
safe_dump_all (documents, stream=None, **kwds)
safe_dump (data, stream=None, **kwds)
add_implicit_resolver (tag, regexp, first=None, Loader=None, Dumper=Dumper)
add_path_resolver (tag, path, kind=None, Loader=None, Dumper=Dumper)
add_constructor (tag, constructor, Loader=None)
add_multi_constructor (tag_prefix, multi_constructor, Loader=None)
add_representer (data_type, representer, Dumper=Dumper)
add_multi_representer (data_type, multi_representer, Dumper=Dumper)
Function Documentation
add_constructor()
yaml.add_constructor (tag, constructor, Loader = None)
Add a constructor for the given tag.
Constructor is a function that accepts a Loader instance
and a node object and produces the corresponding Python object.
Definition at line 302 of file __init__.py.
def add_constructor(tag, constructor, Loader=None):
    """
    Add a constructor for the given tag.
    Constructor is a function that accepts a Loader instance
    and a node object and produces the corresponding Python object.
    """
    if Loader is None:
        loader.Loader.add_constructor(tag, constructor)
        loader.FullLoader.add_constructor(tag, constructor)
        loader.UnsafeLoader.add_constructor(tag, constructor)
    else:
        Loader.add_constructor(tag, constructor)
add_implicit_resolver()
yaml.add_implicit_resolver (tag, regexp, first = None, Loader = None, Dumper = Dumper)
Add an implicit scalar detector.
If an implicit scalar value matches the given regexp,
the corresponding tag is assigned to the scalar.
first is a sequence of possible initial characters or None.
Definition at line 271 of file __init__.py.
        Loader=None, Dumper=Dumper):
    """
    Add an implicit scalar detector.
    If an implicit scalar value matches the given regexp,
    the corresponding tag is assigned to the scalar.
    first is a sequence of possible initial characters or None.
    """
    if Loader is None:
        loader.Loader.add_implicit_resolver(tag, regexp, first)
        loader.FullLoader.add_implicit_resolver(tag, regexp, first)
        loader.UnsafeLoader.add_implicit_resolver(tag, regexp, first)
    else:
        Loader.add_implicit_resolver(tag, regexp, first)
    Dumper.add_implicit_resolver(tag, regexp, first)
add_multi_constructor()
yaml.add_multi_constructor (tag_prefix, multi_constructor, Loader = None)
Add a multi-constructor for the given tag prefix.
Multi-constructor is called for a node if its tag starts with tag_prefix.
Multi-constructor accepts a Loader instance, a tag suffix,
and a node object and produces the corresponding Python object.
Definition at line 315 of file __init__.py.
def add_multi_constructor(tag_prefix, multi_constructor, Loader=None):
    """
    Add a multi-constructor for the given tag prefix.
    Multi-constructor is called for a node if its tag starts with tag_prefix.
    Multi-constructor accepts a Loader instance, a tag suffix,
    and a node object and produces the corresponding Python object.
    """
    if Loader is None:
        loader.Loader.add_multi_constructor(tag_prefix, multi_constructor)
        loader.FullLoader.add_multi_constructor(tag_prefix, multi_constructor)
        loader.UnsafeLoader.add_multi_constructor(tag_prefix, multi_constructor)
    else:
        Loader.add_multi_constructor(tag_prefix, multi_constructor)
add_multi_representer()
yaml.add_multi_representer (data_type, multi_representer, Dumper = Dumper)
Add a representer for the given type.
Multi-representer is a function accepting a Dumper instance
and an instance of the given data type or subtype
and producing the corresponding representation node.
Definition at line 338 of file __init__.py.
def add_multi_representer(data_type, multi_representer, Dumper=Dumper):
    """
    Add a representer for the given type.
    Multi-representer is a function accepting a Dumper instance
    and an instance of the given data type or subtype
    and producing the corresponding representation node.
    """
    Dumper.add_multi_representer(data_type, multi_representer)
add_path_resolver()
yaml.add_path_resolver (tag, path, kind = None, Loader = None, Dumper = Dumper)
Add a path based resolver for the given tag.
A path is a list of keys that forms a path
to a node in the representation tree.
Keys can be string values, integers, or None.
Definition at line 287 of file __init__.py.
def add_path_resolver(tag, path, kind=None, Loader=None, Dumper=Dumper):
    """
    Add a path based resolver for the given tag.
    A path is a list of keys that forms a path
    to a node in the representation tree.
    Keys can be string values, integers, or None.
    """
    if Loader is None:
        loader.Loader.add_path_resolver(tag, path, kind)
        loader.FullLoader.add_path_resolver(tag, path, kind)
        loader.UnsafeLoader.add_path_resolver(tag, path, kind)
    else:
        Loader.add_path_resolver(tag, path, kind)
    Dumper.add_path_resolver(tag, path, kind)
add_representer()
yaml.add_representer (data_type, representer, Dumper = Dumper)
Add a representer for the given type.
Representer is a function accepting a Dumper instance
and an instance of the given data type
and producing the corresponding representation node.
Definition at line 329 of file __init__.py.
def add_representer(data_type, representer, Dumper=Dumper):
    """
    Add a representer for the given type.
    Representer is a function accepting a Dumper instance
    and an instance of the given data type
    and producing the corresponding representation node.
    """
    Dumper.add_representer(data_type, representer)
compose()
yaml.compose (stream, Loader = Loader)
Parse the first YAML document in a stream
and produce the corresponding representation tree.
Definition at line 51 of file __init__.py.
def compose(stream, Loader=Loader):
    """
    Parse the first YAML document in a stream
    and produce the corresponding representation tree.
    """
    loader = Loader(stream)
    try:
        return loader.get_single_node()
    finally:
        loader.dispose()
compose_all()
yaml.compose_all (stream, Loader = Loader)
Parse all YAML documents in a stream
and produce corresponding representation trees.
Definition at line 62 of file __init__.py.
def compose_all(stream, Loader=Loader):
    """
    Parse all YAML documents in a stream
    and produce corresponding representation trees.
    """
    loader = Loader(stream)
    try:
        while loader.check_node():
            yield loader.get_node()
    finally:
        loader.dispose()
dump()
yaml.dump (data, stream = None, Dumper = Dumper, ** kwds)
Serialize a Python object into a YAML stream.
If stream is None, return the produced string instead.
Definition at line 248 of file __init__.py.
def dump(data, stream=None, Dumper=Dumper, **kwds):
    """
    Serialize a Python object into a YAML stream.
    If stream is None, return the produced string instead.
    """
    return dump_all([data], stream, Dumper=Dumper, **kwds)
References dump_all().
dump_all()
yaml.dump_all (documents, stream = None, Dumper = Dumper, default_style = None, default_flow_style = False, canonical = None, indent = None, width = None, allow_unicode = None, line_break = None, encoding = None, explicit_start = None, explicit_end = None, version = None, tags = None, sort_keys = True)
Serialize a sequence of Python objects into a YAML stream.
If stream is None, return the produced string instead.
Definition at line 215 of file __init__.py.
        version=None, tags=None, sort_keys=True):
    """
    Serialize a sequence of Python objects into a YAML stream.
    If stream is None, return the produced string instead.
    """
    getvalue = None
    if stream is None:
        if encoding is None:
            stream = io.StringIO()
        else:
            stream = io.BytesIO()
        getvalue = stream.getvalue
    dumper = Dumper(stream, default_style=default_style,
            default_flow_style=default_flow_style,
            canonical=canonical, indent=indent, width=width,
            allow_unicode=allow_unicode, line_break=line_break,
            encoding=encoding, version=version, tags=tags,
            explicit_start=explicit_start, explicit_end=explicit_end, sort_keys=sort_keys)
    try:
        dumper.open()
        for data in documents:
            dumper.represent(data)
        dumper.close()
    finally:
        dumper.dispose()
    if getvalue:
        return getvalue()
Referenced by dump(), safe_dump(), and safe_dump_all().
emit()
yaml.emit (events, stream = None, Dumper = Dumper, canonical = None, indent = None, width = None, allow_unicode = None, line_break = None)
Emit YAML parsing events into a stream.
If stream is None, return the produced string instead.
Definition at line 157 of file __init__.py.
        allow_unicode=None, line_break=None):
    """
    Emit YAML parsing events into a stream.
    If stream is None, return the produced string instead.
    """
    getvalue = None
    if stream is None:
        stream = io.StringIO()
        getvalue = stream.getvalue
    dumper = Dumper(stream, canonical=canonical, indent=indent, width=width,
            allow_unicode=allow_unicode, line_break=line_break)
    try:
        for event in events:
            dumper.emit(event)
    finally:
        dumper.dispose()
    if getvalue:
        return getvalue()
full_load()
yaml.full_load (stream)
Parse the first YAML document in a stream
and produce the corresponding Python object.
Resolve all tags except those known to be
unsafe on untrusted input.
Definition at line 97 of file __init__.py.
def full_load(stream):
    """
    Parse the first YAML document in a stream
    and produce the corresponding Python object.
    Resolve all tags except those known to be
    unsafe on untrusted input.
    """
    return load(stream, FullLoader)
References load().
full_load_all()
yaml.full_load_all (stream)
Parse all YAML documents in a stream
and produce corresponding Python objects.
Resolve all tags except those known to be
unsafe on untrusted input.
Definition at line 107 of file __init__.py.
def full_load_all(stream):
    """
    Parse all YAML documents in a stream
    and produce corresponding Python objects.
    Resolve all tags except those known to be
    unsafe on untrusted input.
    """
    return load_all(stream, FullLoader)
References load_all().
load()
yaml.load (stream, Loader)
Parse the first YAML document in a stream
and produce the corresponding Python object.
Definition at line 74 of file __init__.py.
def load(stream, Loader):
    """
    Parse the first YAML document in a stream
    and produce the corresponding Python object.
    """
    loader = Loader(stream)
    try:
        return loader.get_single_data()
    finally:
        loader.dispose()
Referenced by django.core.serializers.pyyaml.Deserializer(), full_load(), safe_load(), and unsafe_load().
load_all()
yaml.load_all (stream, Loader)
Parse all YAML documents in a stream
and produce corresponding Python objects.
Definition at line 85 of file __init__.py.
def load_all(stream, Loader):
    """
    Parse all YAML documents in a stream
    and produce corresponding Python objects.
    """
    loader = Loader(stream)
    try:
        while loader.check_data():
            yield loader.get_data()
    finally:
        loader.dispose()
Referenced by full_load_all(), safe_load_all(), and unsafe_load_all().
parse()
yaml.parse (stream, Loader = Loader)
Parse a YAML stream and produce parsing events.
Definition at line 40 of file __init__.py.
def parse(stream, Loader=Loader):
    """
    Parse a YAML stream and produce parsing events.
    """
    loader = Loader(stream)
    try:
        while loader.check_event():
            yield loader.get_event()
    finally:
        loader.dispose()
safe_dump()
yaml.safe_dump (data, stream = None, ** kwds)
Serialize a Python object into a YAML stream.
Produce only basic YAML tags.
If stream is None, return the produced string instead.
Definition at line 263 of file __init__.py.
def safe_dump(data, stream=None, **kwds):
    """
    Serialize a Python object into a YAML stream.
    Produce only basic YAML tags.
    If stream is None, return the produced string instead.
    """
    return dump_all([data], stream, Dumper=SafeDumper, **kwds)
References dump_all().
safe_dump_all()
yaml.safe_dump_all (documents, stream = None, ** kwds)
Serialize a sequence of Python objects into a YAML stream.
Produce only basic YAML tags.
If stream is None, return the produced string instead.
Definition at line 255 of file __init__.py.
def safe_dump_all(documents, stream=None, **kwds):
    """
    Serialize a sequence of Python objects into a YAML stream.
    Produce only basic YAML tags.
    If stream is None, return the produced string instead.
    """
    return dump_all(documents, stream, Dumper=SafeDumper, **kwds)
References dump_all().
safe_load()
yaml.safe_load (stream)
Parse the first YAML document in a stream
and produce the corresponding Python object.
Resolve only basic YAML tags. This is known
to be safe for untrusted input.
Definition at line 117 of file __init__.py.
def safe_load(stream):
    """
    Parse the first YAML document in a stream
    and produce the corresponding Python object.
    Resolve only basic YAML tags. This is known
    to be safe for untrusted input.
    """
    return load(stream, SafeLoader)
References load().
Referenced by responses.RequestsMock._parse_response_file().
safe_load_all()
yaml.safe_load_all (stream)
Parse all YAML documents in a stream
and produce corresponding Python objects.
Resolve only basic YAML tags. This is known
to be safe for untrusted input.
Definition at line 127 of file __init__.py.
def safe_load_all(stream):
    """
    Parse all YAML documents in a stream
    and produce corresponding Python objects.
    Resolve only basic YAML tags. This is known
    to be safe for untrusted input.
    """
    return load_all(stream, SafeLoader)
References load_all().
scan()
yaml.scan (stream, Loader = Loader)
Scan a YAML stream and produce scanning tokens.
Definition at line 29 of file __init__.py.
def scan(stream, Loader=Loader):
    """
    Scan a YAML stream and produce scanning tokens.
    """
    loader = Loader(stream)
    try:
        while loader.check_token():
            yield loader.get_token()
    finally:
        loader.dispose()
serialize()
yaml.serialize (node, stream = None, Dumper = Dumper, ** kwds)
Serialize a representation tree into a YAML stream.
If stream is None, return the produced string instead.
Definition at line 208 of file __init__.py.
def serialize(node, stream=None, Dumper=Dumper, **kwds):
    """
    Serialize a representation tree into a YAML stream.
    If stream is None, return the produced string instead.
    """
    return serialize_all([node], stream, Dumper=Dumper, **kwds)
References serialize_all().
serialize_all()
yaml.serialize_all (nodes, stream = None, Dumper = Dumper, canonical = None, indent = None, width = None, allow_unicode = None, line_break = None, encoding = None, explicit_start = None, explicit_end = None, version = None, tags = None)
Serialize a sequence of representation trees into a YAML stream.
If stream is None, return the produced string instead.
Definition at line 178 of file __init__.py.
        version=None, tags=None):
    """
    Serialize a sequence of representation trees into a YAML stream.
    If stream is None, return the produced string instead.
    """
    getvalue = None
    if stream is None:
        if encoding is None:
            stream = io.StringIO()
        else:
            stream = io.BytesIO()
        getvalue = stream.getvalue
    dumper = Dumper(stream, canonical=canonical, indent=indent, width=width,
            allow_unicode=allow_unicode, line_break=line_break,
            encoding=encoding, version=version, tags=tags,
            explicit_start=explicit_start, explicit_end=explicit_end)
    try:
        dumper.open()
        for node in nodes:
            dumper.serialize(node)
        dumper.close()
    finally:
        dumper.dispose()
    if getvalue:
        return getvalue()
Referenced by serialize().
unsafe_load()
yaml.unsafe_load (stream)
Parse the first YAML document in a stream
and produce the corresponding Python object.
Resolve all tags, even those known to be
unsafe on untrusted input.
Definition at line 137 of file __init__.py.
def unsafe_load(stream):
    """
    Parse the first YAML document in a stream
    and produce the corresponding Python object.
    Resolve all tags, even those known to be
    unsafe on untrusted input.
    """
    return load(stream, UnsafeLoader)
References load().
unsafe_load_all()
yaml.unsafe_load_all (stream)
Parse all YAML documents in a stream
and produce corresponding Python objects.
Resolve all tags, even those known to be
unsafe on untrusted input.
Definition at line 147 of file __init__.py.
def unsafe_load_all(stream):
    """
    Parse all YAML documents in a stream
    and produce corresponding Python objects.
    Resolve all tags, even those known to be
    unsafe on untrusted input.
    """
    return load_all(stream, UnsafeLoader)
References load_all().
warnings()
yaml.warnings (settings = None)
Definition at line 24 of file __init__.py.
def warnings(settings=None):
    if settings is None:
        return {}
#------------------------------------------------------------------------------