Read&Watch: astroid._ast Namespace Reference
astroid._ast Namespace Reference
Classes
class FunctionType
class ParserModule
Functions
FunctionType|None parse_function_type_comment (str type_comment)
ParserModule get_parser_module (bool type_comments=True)
dict[type[ast.unaryop], str] _unary_operators_from_module ()
dict[type[ast.operator],str] _binary_operators_from_module ()
dict[type[ast.boolop], str] _bool_operators_from_module ()
dict[type[ast.cmpop], str] _compare_operators_from_module ()
dict[type[ast.expr_context], Context] _contexts_from_module ()
Function Documentation
_binary_operators_from_module()
dict[type[ast.operator], str] astroid._ast._binary_operators_from_module () protected
Definition at line 59 of file _ast.py.
def _binary_operators_from_module() -> dict[type[ast.operator], str]:
    return {
        ast.Add: "+",
        ast.BitAnd: "&",
        ast.BitOr: "|",
        ast.BitXor: "^",
        ast.Div: "/",
        ast.FloorDiv: "//",
        ast.MatMult: "@",
        ast.Mod: "%",
        ast.Mult: "*",
        ast.Pow: "**",
        ast.Sub: "-",
        ast.LShift: "<<",
        ast.RShift: ">>",
    }
Referenced by get_parser_module().
_bool_operators_from_module()
dict[type[ast.boolop], str] astroid._ast._bool_operators_from_module () protected
Definition at line 77 of file _ast.py.
def _bool_operators_from_module() -> dict[type[ast.boolop], str]:
    return {ast.And: "and", ast.Or: "or"}
Referenced by get_parser_module().
_compare_operators_from_module()
dict[type[ast.cmpop], str] astroid._ast._compare_operators_from_module () protected
Definition at line 81 of file _ast.py.
def _compare_operators_from_module() -> dict[type[ast.cmpop], str]:
    return {
        ast.Eq: "==",
        ast.Gt: ">",
        ast.GtE: ">=",
        ast.In: "in",
        ast.Is: "is",
        ast.IsNot: "is not",
        ast.Lt: "<",
        ast.LtE: "<=",
        ast.NotEq: "!=",
        ast.NotIn: "not in",
    }
Referenced by get_parser_module().
_contexts_from_module()
dict[type[ast.expr_context], Context] astroid._ast._contexts_from_module () protected
Definition at line 96 of file _ast.py.
def _contexts_from_module() -> dict[type[ast.expr_context], Context]:
    return {
        ast.Load: Context.Load,
        ast.Store: Context.Store,
        ast.Del: Context.Del,
        ast.Param: Context.Store,
    }
Referenced by get_parser_module().
_unary_operators_from_module()
dict[type[ast.unaryop], str] astroid._ast._unary_operators_from_module () protected
Definition at line 55 of file _ast.py.
def _unary_operators_from_module() -> dict[type[ast.unaryop], str]:
    return {ast.UAdd: "+", ast.USub: "-", ast.Not: "not", ast.Invert: "~"}
Referenced by get_parser_module().
get_parser_module()
ParserModule astroid._ast.get_parser_module (bool type_comments = True)
Definition at line 39 of file _ast.py.
def get_parser_module(type_comments: bool = True) -> ParserModule:
    unary_op_classes = _unary_operators_from_module()
    cmp_op_classes = _compare_operators_from_module()
    bool_op_classes = _bool_operators_from_module()
    bin_op_classes = _binary_operators_from_module()
    context_classes = _contexts_from_module()
    return ParserModule(
        unary_op_classes,
        cmp_op_classes,
        bool_op_classes,
        bin_op_classes,
        context_classes,
    )
References _binary_operators_from_module(), _bool_operators_from_module(), _compare_operators_from_module(), _contexts_from_module(), and _unary_operators_from_module().
parse_function_type_comment()
FunctionType | None astroid._ast.parse_function_type_comment (str type_comment)
Given a correct type comment, obtain a FunctionType object.
Definition at line 33 of file _ast.py.
def parse_function_type_comment(type_comment: str) -> FunctionType | None:
    """Given a correct type comment, obtain a FunctionType object."""
    func_type = ast.parse(type_comment, "<type_comment>", "func_type")  # type: ignore[attr-defined]
    return FunctionType(argtypes=func_type.argtypes, returns=func_type.returns)