Read&Watch: django.urls.base Namespace Reference
django.urls.base Namespace Reference
Functions
resolve (path, urlconf=None)
reverse (viewname, urlconf=None, args=None, kwargs=None, current_app=None)
clear_url_caches ()
set_script_prefix (prefix)
get_script_prefix ()
clear_script_prefix ()
set_urlconf (urlconf_name)
get_urlconf (default=None)
is_valid_path (path, urlconf=None)
translate_url (url, lang_code)
Variables
_prefixes = Local()
_urlconfs = Local()
reverse_lazy = lazy(reverse, str)
Function Documentation
clear_script_prefix()
django.urls.base.clear_script_prefix ()
Unset the script prefix for the current thread.
Definition at line 118 of file base.py.
def clear_script_prefix():
    """
    Unset the script prefix for the current thread.
    """
    try:
        del _prefixes.value
    except AttributeError:
        pass
clear_url_caches()
django.urls.base.clear_url_caches ()
Definition at line 94 of file base.py.
def clear_url_caches():
    get_callable.cache_clear()
    _get_cached_resolver.cache_clear()
    get_ns_resolver.cache_clear()
get_script_prefix()
django.urls.base.get_script_prefix ()
Return the currently active script prefix. Useful for client code that
wishes to construct their own URLs manually (although accessing the request
instance is normally going to be a lot cleaner).
Definition at line 109 of file base.py.
def get_script_prefix():
    """
    Return the currently active script prefix. Useful for client code that
    wishes to construct their own URLs manually (although accessing the request
    instance is normally going to be a lot cleaner).
    """
    return getattr(_prefixes, "value", "/")
Referenced by reverse().
get_urlconf()
django.urls.base.get_urlconf (default = None)
Return the root URLconf to use for the current thread if it has been
changed from the default one.
Definition at line 140 of file base.py.
def get_urlconf(default=None):
    """
    Return the root URLconf to use for the current thread if it has been
    changed from the default one.
    """
    return getattr(_urlconfs, "value", default)
Referenced by resolve(), and reverse().
is_valid_path()
django.urls.base.is_valid_path (path, urlconf = None)
Return the ResolverMatch if the given path resolves against the default URL
resolver, False otherwise. This is a convenience method to make working
with "is this a match?" cases easier, avoiding try...except blocks.
Definition at line 148 of file base.py.
def is_valid_path(path, urlconf=None):
    """
    Return the ResolverMatch if the given path resolves against the default URL
    resolver, False otherwise. This is a convenience method to make working
    with "is this a match?" cases easier, avoiding try...except blocks.
    """
    try:
        return resolve(path, urlconf)
    except Resolver404:
        return False
References resolve().
resolve()
django.urls.base.resolve (path, urlconf = None)
Definition at line 21 of file base.py.
def resolve(path, urlconf=None):
    if urlconf is None:
        urlconf = get_urlconf()
    return get_resolver(urlconf).resolve(path)
References get_urlconf(), and resolve().
Referenced by is_valid_path(), resolve(), and translate_url().
reverse()
django.urls.base.reverse (viewname, urlconf = None, args = None, kwargs = None, current_app = None)
Definition at line 27 of file base.py.
def reverse(viewname, urlconf=None, args=None, kwargs=None, current_app=None):
    if urlconf is None:
        urlconf = get_urlconf()
    resolver = get_resolver(urlconf)
    args = args or []
    kwargs = kwargs or {}
    prefix = get_script_prefix()
    if not isinstance(viewname, str):
        view = viewname
    else:
        *path, view = viewname.split(":")
        if current_app:
            current_path = current_app.split(":")
            current_path.reverse()
        else:
            current_path = None
        resolved_path = []
        ns_pattern = ""
        ns_converters = {}
        for ns in path:
            current_ns = current_path.pop() if current_path else None
            # Lookup the name to see if it could be an app identifier.
            try:
                app_list = resolver.app_dict[ns]
                # Yes! Path part matches an app in the current Resolver.
                if current_ns and current_ns in app_list:
                    # If we are reversing for a particular app, use that
                    # namespace.
                    ns = current_ns
                elif ns not in app_list:
                    # The name isn't shared by one of the instances (i.e.,
                    # the default) so pick the first instance as the default.
                    ns = app_list[0]
            except KeyError:
                pass
            if ns != current_ns:
                current_path = None
            try:
                extra, resolver = resolver.namespace_dict[ns]
                resolved_path.append(ns)
                ns_pattern += extra
                ns_converters.update(resolver.pattern.converters)
            except KeyError as key:
                if resolved_path:
                    raise NoReverseMatch(
                        "%s is not a registered namespace inside '%s'"
                        % (key, ":".join(resolved_path))
                    )
                else:
                    raise NoReverseMatch("%s is not a registered namespace" % key)
        if ns_pattern:
            resolver = get_ns_resolver(
                ns_pattern, resolver, tuple(ns_converters.items())
            )
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
References get_script_prefix(), and get_urlconf().
Referenced by translate_url().
set_script_prefix()
django.urls.base.set_script_prefix (prefix)
Set the script prefix for the current thread.
Definition at line 100 of file base.py.
def set_script_prefix(prefix):
    """
    Set the script prefix for the current thread.
    """
    if not prefix.endswith("/"):
        prefix += "/"
    _prefixes.value = prefix
set_urlconf()
django.urls.base.set_urlconf (urlconf_name)
Set the URLconf for the current thread (overriding the default one in
settings). If urlconf_name is None, revert back to the default.
Definition at line 128 of file base.py.
def set_urlconf(urlconf_name):
    """
    Set the URLconf for the current thread (overriding the default one in
    settings). If urlconf_name is None, revert back to the default.
    """
    if urlconf_name:
        _urlconfs.value = urlconf_name
    else:
        if hasattr(_urlconfs, "value"):
            del _urlconfs.value
translate_url()
django.urls.base.translate_url (url, lang_code)
Given a URL (absolute or relative), try to get its translated version in
the `lang_code` language (either by i18n_patterns or by translated regex).
Return the original URL if no translated version is found.
Definition at line 160 of file base.py.
def translate_url(url, lang_code):
    """
    Given a URL (absolute or relative), try to get its translated version in
    the `lang_code` language (either by i18n_patterns or by translated regex).
    Return the original URL if no translated version is found.
    """
    parsed = urlsplit(url)
    try:
        # URL may be encoded.
        match = resolve(unquote(parsed.path))
    except Resolver404:
        pass
    else:
        to_be_reversed = (
            "%s:%s" % (match.namespace, match.url_name)
            if match.namespace
            else match.url_name
        )
        with override(lang_code):
            try:
                url = reverse(to_be_reversed, args=match.args, kwargs=match.kwargs)
            except NoReverseMatch:
                pass
            else:
                url = urlunsplit(
                    (parsed.scheme, parsed.netloc, url, parsed.query, parsed.fragment)
                )
    return url
References resolve(), and reverse().
Variable Documentation
_prefixes
django.urls.base._prefixes = Local() protected
Definition at line 15 of file base.py.
_urlconfs
django.urls.base._urlconfs = Local() protected
Definition at line 18 of file base.py.
reverse_lazy
django.urls.base.reverse_lazy = lazy(reverse, str)
Definition at line 91 of file base.py.