Read&Watch: pip._internal.utils.compatibility_tags Namespace Reference
pip._internal.utils.compatibility_tags Namespace Reference
Functions
str version_info_to_nodot (Tuple[int,...] version_info)
List[str] _mac_platforms (str arch)
List[str] _ios_platforms (str arch)
List[str] _custom_manylinux_platforms (str arch)
List[str] _get_custom_platforms (str arch)
Optional[List[str]] _expand_allowed_platforms (Optional[List[str]] platforms)
PythonVersion _get_python_version (str version)
str _get_custom_interpreter (Optional[str] implementation=None, Optional[str] version=None)
List[Tag] get_supported (Optional[str] version=None, Optional[List[str]] platforms=None, Optional[str] impl=None, Optional[List[str]] abis=None)
Variables
_apple_arch_pat = re.compile(r"(.+)_(\d+)_(\d+)_(.+)")
Detailed Description
Generate and work with PEP 425 Compatibility Tags.
Function Documentation
_custom_manylinux_platforms()
List[str] pip._internal.utils.compatibility_tags._custom_manylinux_platforms (str arch) protected
Definition at line 67 of file compatibility_tags.py.
def _custom_manylinux_platforms(arch: str) -> List[str]:
    arches = [arch]
    arch_prefix, arch_sep, arch_suffix = arch.partition("_")
    if arch_prefix == "manylinux2014":
        # manylinux1/manylinux2010 wheels run on most manylinux2014 systems
        # with the exception of wheels depending on ncurses. PEP 599 states
        # manylinux1/manylinux2010 wheels should be considered
        # manylinux2014 wheels:
        # https://www.python.org/dev/peps/pep-0599/#backwards-compatibility-with-manylinux2010-wheels
        if arch_suffix in {"i686", "x86_64"}:
            arches.append("manylinux2010" + arch_sep + arch_suffix)
            arches.append("manylinux1" + arch_sep + arch_suffix)
    elif arch_prefix == "manylinux2010":
        # manylinux1 wheels run on most manylinux2010 systems with the
        # exception of wheels depending on ncurses. PEP 571 states
        # manylinux1 wheels should be considered manylinux2010 wheels:
        # https://www.python.org/dev/peps/pep-0571/#backwards-compatibility-with-manylinux1-wheels
        arches.append("manylinux1" + arch_sep + arch_suffix)
    return arches
Referenced by _get_custom_platforms().
_expand_allowed_platforms()
Optional[List[str]] pip._internal.utils.compatibility_tags._expand_allowed_platforms (Optional[List[str]] platforms) protected
Definition at line 101 of file compatibility_tags.py.
def _expand_allowed_platforms(platforms: Optional[List[str]]) -> Optional[List[str]]:
    if not platforms:
        return None
    seen = set()
    result = []
    for p in platforms:
        if p in seen:
            continue
        additions = [c for c in _get_custom_platforms(p) if c not in seen]
        seen.update(additions)
        result.extend(additions)
    return result
References _get_custom_platforms().
Referenced by get_supported().
_get_custom_interpreter()
str pip._internal.utils.compatibility_tags._get_custom_interpreter (Optional[str] implementation = None, Optional[str] version = None) protected
Definition at line 125 of file compatibility_tags.py.
) -> str:
    if implementation is None:
        implementation = interpreter_name()
    if version is None:
        version = interpreter_version()
    return f"{implementation}{version}"
Referenced by get_supported().
_get_custom_platforms()
List[str] pip._internal.utils.compatibility_tags._get_custom_platforms (str arch) protected
Definition at line 88 of file compatibility_tags.py.
def _get_custom_platforms(arch: str) -> List[str]:
    arch_prefix, arch_sep, arch_suffix = arch.partition("_")
    if arch.startswith("macosx"):
        arches = _mac_platforms(arch)
    elif arch.startswith("ios"):
        arches = _ios_platforms(arch)
    elif arch_prefix in ["manylinux2014", "manylinux2010"]:
        arches = _custom_manylinux_platforms(arch)
    else:
        arches = [arch]
    return arches
References _custom_manylinux_platforms(), _ios_platforms(), and _mac_platforms().
Referenced by _expand_allowed_platforms().
_get_python_version()
PythonVersion pip._internal.utils.compatibility_tags._get_python_version (str version) protected
Definition at line 118 of file compatibility_tags.py.
def _get_python_version(version: str) -> PythonVersion:
    if len(version) > 1:
        return int(version[0]), int(version[1:])
    else:
        return (int(version[0]),)
Referenced by get_supported().
_ios_platforms()
List[str] pip._internal.utils.compatibility_tags._ios_platforms (str arch) protected
Definition at line 47 of file compatibility_tags.py.
def _ios_platforms(arch: str) -> List[str]:
    match = _apple_arch_pat.match(arch)
    if match:
        name, major, minor, actual_multiarch = match.groups()
        ios_version = (int(major), int(minor))
        arches = [
            # Since we have always only checked that the platform starts
            # with "ios", for backwards-compatibility we extract the
            # actual prefix provided by the user in case they provided
            # something like "ioscustom_". It may be good to remove
            # this as undocumented or deprecate it in the future.
            "{}_{}".format(name, arch[len("ios_") :])
            for arch in ios_platforms(ios_version, actual_multiarch)
        ]
    else:
        # arch pattern didn't match (?!)
        arches = [arch]
    return arches
Referenced by _get_custom_platforms().
_mac_platforms()
List[str] pip._internal.utils.compatibility_tags._mac_platforms (str arch) protected
Definition at line 27 of file compatibility_tags.py.
def _mac_platforms(arch: str) -> List[str]:
    match = _apple_arch_pat.match(arch)
    if match:
        name, major, minor, actual_arch = match.groups()
        mac_version = (int(major), int(minor))
        arches = [
            # Since we have always only checked that the platform starts
            # with "macosx", for backwards-compatibility we extract the
            # actual prefix provided by the user in case they provided
            # something like "macosxcustom_". It may be good to remove
            # this as undocumented or deprecate it in the future.
            "{}_{}".format(name, arch[len("macosx_") :])
            for arch in mac_platforms(mac_version, actual_arch)
        ]
    else:
        # arch pattern didn't match (?!)
        arches = [arch]
    return arches
Referenced by _get_custom_platforms().
get_supported()
List[Tag] pip._internal.utils.compatibility_tags.get_supported (Optional[str] version = None, Optional[List[str]] platforms = None, Optional[str] impl = None, Optional[List[str]] abis = None)
Return a list of supported tags for each version specified in
`versions`.
:param version: a string version, of the form "33" or "32",
    or None. The version will be assumed to support our ABI.
:param platform: specify a list of platforms you want valid
    tags for, or None. If None, use the local system platform.
:param impl: specify the exact implementation you want valid
    tags for, or None. If None, use the local interpreter impl.
:param abis: specify a list of abis you want valid
    tags for, or None. If None, use the local interpreter abi.
Definition at line 135 of file compatibility_tags.py.
) -> List[Tag]:
    """Return a list of supported tags for each version specified in
    `versions`.
    :param version: a string version, of the form "33" or "32",
        or None. The version will be assumed to support our ABI.
    :param platform: specify a list of platforms you want valid
        tags for, or None. If None, use the local system platform.
    :param impl: specify the exact implementation you want valid
        tags for, or None. If None, use the local interpreter impl.
    :param abis: specify a list of abis you want valid
        tags for, or None. If None, use the local interpreter abi.
    """
    supported: List[Tag] = []
    python_version: Optional[PythonVersion] = None
    if version is not None:
        python_version = _get_python_version(version)
    interpreter = _get_custom_interpreter(impl, version)
    platforms = _expand_allowed_platforms(platforms)
    is_cpython = (impl or interpreter_name()) == "cp"
    if is_cpython:
        supported.extend(
            cpython_tags(
                python_version=python_version,
                abis=abis,
                platforms=platforms,
            )
        )
    else:
        supported.extend(
            generic_tags(
                interpreter=interpreter,
                abis=abis,
                platforms=platforms,
            )
        )
    supported.extend(
        compatible_tags(
            python_version=python_version,
            interpreter=interpreter,
            platforms=platforms,
        )
    )
    return supported
References _expand_allowed_platforms(), _get_custom_interpreter(), and _get_python_version().
version_info_to_nodot()
str pip._internal.utils.compatibility_tags.version_info_to_nodot (Tuple[int, ...] version_info)
Definition at line 22 of file compatibility_tags.py.
def version_info_to_nodot(version_info: Tuple[int, ...]) -> str:
    # Only use up to the first two numbers.
    return "".join(map(str, version_info[:2]))
Variable Documentation
_apple_arch_pat
pip._internal.utils.compatibility_tags._apple_arch_pat = re.compile(r"(.+)_(\d+)_(\d+)_(.+)") protected
Definition at line 19 of file compatibility_tags.py.