Read&Watch: urllib3.util.connection Namespace Reference
urllib3.util.connection Namespace Reference
Functions
bool is_connection_dropped (BaseHTTPConnection conn)
socket.socket create_connection (tuple[str, int] address, _TYPE_TIMEOUT timeout=_DEFAULT_TIMEOUT, tuple[str, int]|None source_address=None, _TYPE_SOCKET_OPTIONS|None socket_options=None)
None _set_socket_options (socket.socket sock, _TYPE_SOCKET_OPTIONS|None options)
socket.AddressFamily allowed_gai_family ()
bool _has_ipv6 (str host)
Variables
_TYPE_SOCKET_OPTIONS = typing.List[typing.Tuple[int, int, typing.Union[int, bytes]]]
bool HAS_IPV6 = _has_ipv6("::1")
Function Documentation
_has_ipv6()
bool urllib3.util.connection._has_ipv6 (str host) protected
Returns True if the system can bind an IPv6 address.
Definition at line 114 of file connection.py.
def _has_ipv6(host: str) -> bool:
    """Returns True if the system can bind an IPv6 address."""
    sock = None
    has_ipv6 = False
    if socket.has_ipv6:
        # has_ipv6 returns true if cPython was compiled with IPv6 support.
        # It does not tell us if the system has IPv6 support enabled. To
        # determine that we must bind to an IPv6 address.
        # https://github.com/urllib3/urllib3/pull/611
        # https://bugs.python.org/issue658327
        try:
            sock = socket.socket(socket.AF_INET6)
            sock.bind((host, 0))
            has_ipv6 = True
        except Exception:
            pass
    if sock:
        sock.close()
    return has_ipv6
_set_socket_options()
None urllib3.util.connection._set_socket_options (socket.socket sock, _TYPE_SOCKET_OPTIONS | None options) protected
Definition at line 93 of file connection.py.
) -> None:
    if options is None:
        return
    for opt in options:
        sock.setsockopt(*opt)
Referenced by create_connection().
allowed_gai_family()
socket.AddressFamily urllib3.util.connection.allowed_gai_family ()
This function is designed to work in the context of
getaddrinfo, where family=socket.AF_UNSPEC is the default and
will perform a DNS search for both IPv6 and IPv4 records.
Definition at line 103 of file connection.py.
def allowed_gai_family() -> socket.AddressFamily:
    """This function is designed to work in the context of
    getaddrinfo, where family=socket.AF_UNSPEC is the default and
    will perform a DNS search for both IPv6 and IPv4 records."""
    family = socket.AF_INET
    if HAS_IPV6:
        family = socket.AF_UNSPEC
    return family
Referenced by create_connection().
create_connection()
socket.socket urllib3.util.connection.create_connection (tuple[str, int] address, _TYPE_TIMEOUT timeout = _DEFAULT_TIMEOUT, tuple[str, int] | None source_address = None, _TYPE_SOCKET_OPTIONS | None socket_options = None)
Connect to *address* and return the socket object.
Convenience function.  Connect to *address* (a 2-tuple ``(host,
port)``) and return the socket object.  Passing the optional
*timeout* parameter will set the timeout on the socket instance
before attempting to connect.  If no *timeout* is supplied, the
global default timeout setting returned by :func:`socket.getdefaulttimeout`
is used.  If *source_address* is set it must be a tuple of (host, port)
for the socket to bind as a source address before making the connection.
An host of '' or port 0 tells the OS to use the default.
Definition at line 27 of file connection.py.
) -> socket.socket:
    """Connect to *address* and return the socket object.
    Convenience function.  Connect to *address* (a 2-tuple ``(host,
    port)``) and return the socket object.  Passing the optional
    *timeout* parameter will set the timeout on the socket instance
    before attempting to connect.  If no *timeout* is supplied, the
    global default timeout setting returned by :func:`socket.getdefaulttimeout`
    is used.  If *source_address* is set it must be a tuple of (host, port)
    for the socket to bind as a source address before making the connection.
    An host of '' or port 0 tells the OS to use the default.
    """
    host, port = address
    if host.startswith("["):
        host = host.strip("[]")
    err = None
    # Using the value from allowed_gai_family() in the context of getaddrinfo lets
    # us select whether to work with IPv4 DNS records, IPv6 records, or both.
    # The original create_connection function always returns all records.
    family = allowed_gai_family()
    try:
        host.encode("idna")
    except UnicodeError:
        raise LocationParseError(f"'{host}', label empty or too long") from None
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
        af, socktype, proto, canonname, sa = res
        sock = None
        try:
            sock = socket.socket(af, socktype, proto)
            # If provided, set socket level options before connecting.
            _set_socket_options(sock, socket_options)
            if timeout is not _DEFAULT_TIMEOUT:
                sock.settimeout(timeout)
            if source_address:
                sock.bind(source_address)
            sock.connect(sa)
            # Break explicitly a reference cycle
            err = None
            return sock
        except OSError as _:
            err = _
            if sock is not None:
                sock.close()
    if err is not None:
        try:
            raise err
        finally:
            # Break explicitly a reference cycle
            err = None
    else:
        raise OSError("getaddrinfo returns an empty list")
References _set_socket_options(), and allowed_gai_family().
is_connection_dropped()
bool urllib3.util.connection.is_connection_dropped (BaseHTTPConnection conn)
Returns True if the connection is dropped and should be closed.
:param conn: :class:`urllib3.connection.HTTPConnection` object.
Definition at line 15 of file connection.py.
def is_connection_dropped(conn: BaseHTTPConnection) -> bool:  # Platform-specific
    """
    Returns True if the connection is dropped and should be closed.
    :param conn: :class:`urllib3.connection.HTTPConnection` object.
    """
    return not conn.is_connected
# This function is copied from socket.py in the Python 2.7 standard
# library test suite. Added to its signature is only `socket_options`.
# One additional modification is that we avoid binding to IPv6 servers
# discovered in DNS if the system doesn't have IPv6 functionality.
Variable Documentation
_TYPE_SOCKET_OPTIONS
urllib3.util.connection._TYPE_SOCKET_OPTIONS = typing.List[typing.Tuple[int, int, typing.Union[int, bytes]]] protected
Definition at line 9 of file connection.py.
HAS_IPV6
bool urllib3.util.connection.HAS_IPV6 = _has_ipv6("::1")
Definition at line 137 of file connection.py.