Read&Watch: django.templatetags.tz Namespace Reference
django.templatetags.tz Namespace Reference
Classes
class datetimeobject
class GetCurrentTimezoneNode
class LocalTimeNode
class TimezoneNode
Functions
localtime (value)
utc (value)
do_timezone (value, arg)
localtime_tag (parser, token)
timezone_tag (parser, token)
get_current_timezone_tag (parser, token)
Variables
register = Library()
Function Documentation
do_timezone()
django.templatetags.tz.do_timezone (value, arg)
Convert a datetime to local time in a given time zone.
The argument must be an instance of a tzinfo subclass or a time zone name.
Naive datetimes are assumed to be in local time in the default time zone.
Definition at line 40 of file tz.py.
def do_timezone(value, arg):
    """
    Convert a datetime to local time in a given time zone.
    The argument must be an instance of a tzinfo subclass or a time zone name.
    Naive datetimes are assumed to be in local time in the default time zone.
    """
    if not isinstance(value, datetime):
        return ""
    # Obtain a timezone-aware datetime
    try:
        if timezone.is_naive(value):
            default_timezone = timezone.get_default_timezone()
            value = timezone.make_aware(value, default_timezone)
    # Filters must never raise exceptionsm, so catch everything.
    except Exception:
        return ""
    # Obtain a tzinfo instance
    if isinstance(arg, tzinfo):
        tz = arg
    elif isinstance(arg, str):
        try:
            tz = zoneinfo.ZoneInfo(arg)
        except zoneinfo.ZoneInfoNotFoundError:
            return ""
    else:
        return ""
    result = timezone.localtime(value, tz)
    # HACK: the convert_to_local_time flag will prevent
    #       automatic conversion of the value to local time.
    result = datetimeobject(
        result.year,
        result.month,
        result.day,
        result.hour,
        result.minute,
        result.second,
        result.microsecond,
        result.tzinfo,
    )
    result.convert_to_local_time = False
    return result
# Template tags
Referenced by localtime(), and utc().
get_current_timezone_tag()
django.templatetags.tz.get_current_timezone_tag (parser, token)
Store the name of the current time zone in the context.
Usage::
    {% get_current_timezone as TIME_ZONE %}
This will fetch the currently active time zone and put its name
into the ``TIME_ZONE`` context variable.
Definition at line 184 of file tz.py.
def get_current_timezone_tag(parser, token):
    """
    Store the name of the current time zone in the context.
    Usage::
        {% get_current_timezone as TIME_ZONE %}
    This will fetch the currently active time zone and put its name
    into the ``TIME_ZONE`` context variable.
    """
    # token.split_contents() isn't useful here because this tag doesn't accept
    # variable as arguments.
    args = token.contents.split()
    if len(args) != 3 or args[1] != "as":
        raise TemplateSyntaxError(
            "'get_current_timezone' requires 'as variable' (got %r)" % args
        )
    return GetCurrentTimezoneNode(args[2])
localtime()
django.templatetags.tz.localtime (value)
Convert a datetime to local time in the active time zone.
This only makes sense within a {% localtime off %} block.
Definition at line 22 of file tz.py.
def localtime(value):
    """
    Convert a datetime to local time in the active time zone.
    This only makes sense within a {% localtime off %} block.
    """
    return do_timezone(value, timezone.get_current_timezone())
@register.filter
References do_timezone().
localtime_tag()
django.templatetags.tz.localtime_tag (parser, token)
Force or prevent conversion of datetime objects to local time,
regardless of the value of ``settings.USE_TZ``.
Sample usage::
    {% localtime off %}{{ value_in_utc }}{% endlocaltime %}
Definition at line 138 of file tz.py.
def localtime_tag(parser, token):
    """
    Force or prevent conversion of datetime objects to local time,
    regardless of the value of ``settings.USE_TZ``.
    Sample usage::
        {% localtime off %}{{ value_in_utc }}{% endlocaltime %}
    """
    bits = token.split_contents()
    if len(bits) == 1:
        use_tz = True
    elif len(bits) > 2 or bits[1] not in ("on", "off"):
        raise TemplateSyntaxError("%r argument should be 'on' or 'off'" % bits[0])
    else:
        use_tz = bits[1] == "on"
    nodelist = parser.parse(("endlocaltime",))
    parser.delete_first_token()
    return LocalTimeNode(nodelist, use_tz)
@register.tag("timezone")
timezone_tag()
django.templatetags.tz.timezone_tag (parser, token)
Enable a given time zone just for this block.
The ``timezone`` argument must be an instance of a ``tzinfo`` subclass, a
time zone name, or ``None``. If it is ``None``, the default time zone is
used within the block.
Sample usage::
    {% timezone "Europe/Paris" %}
        It is {{ now }} in Paris.
    {% endtimezone %}
Definition at line 160 of file tz.py.
def timezone_tag(parser, token):
    """
    Enable a given time zone just for this block.
    The ``timezone`` argument must be an instance of a ``tzinfo`` subclass, a
    time zone name, or ``None``. If it is ``None``, the default time zone is
    used within the block.
    Sample usage::
        {% timezone "Europe/Paris" %}
            It is {{ now }} in Paris.
        {% endtimezone %}
    """
    bits = token.split_contents()
    if len(bits) != 2:
        raise TemplateSyntaxError("'%s' takes one argument (timezone)" % bits[0])
    tz = parser.compile_filter(bits[1])
    nodelist = parser.parse(("endtimezone",))
    parser.delete_first_token()
    return TimezoneNode(nodelist, tz)
@register.tag("get_current_timezone")
utc()
django.templatetags.tz.utc (value)
Convert a datetime to UTC.
Definition at line 32 of file tz.py.
def utc(value):
    """
    Convert a datetime to UTC.
    """
    return do_timezone(value, datetime_timezone.utc)
@register.filter("timezone")
References do_timezone().
Variable Documentation
register
django.templatetags.tz.register = Library()
Definition at line 9 of file tz.py.