Read&Watch: urllib3.contrib.emscripten.fetch Namespace Reference
urllib3.contrib.emscripten.fetch Namespace Reference
Classes
class _ReadStream
class _RequestError
class _StreamingError
class _StreamingFetcher
class _TimeoutError
Functions
JsProxy _obj_from_dict (dict[str, Any] dict_val)
bool is_in_browser_main_thread ()
bool is_cross_origin_isolated ()
bool is_in_node ()
bool is_worker_available ()
EmscriptenResponse|None send_streaming_request (EmscriptenRequest request)
None _show_timeout_warning ()
None _show_streaming_warning ()
EmscriptenResponse send_request (EmscriptenRequest request)
bool|None streaming_ready ()
bool wait_for_streaming_ready ()
Variables
tuple HEADERS_TO_IGNORE = ("user-agent",)
int SUCCESS_HEADER = -1
int SUCCESS_EOF = -2
int ERROR_TIMEOUT = -3
int ERROR_EXCEPTION = -4
tuple _STREAMING_WORKER_CODE
_StreamingFetcher _fetcher = None
bool _SHOWN_TIMEOUT_WARNING = False
bool _SHOWN_STREAMING_WARNING = False
Detailed Description
Support for streaming http requests in emscripten.
A few caveats -
Firstly, you can't do streaming http in the main UI thread, because atomics.wait isn't allowed.
Streaming only works if you're running pyodide in a web worker.
Secondly, this uses an extra web worker and SharedArrayBuffer to do the asynchronous fetch
operation, so it requires that you have crossOriginIsolation enabled, by serving over https
(or from localhost) with the two headers below set:
    Cross-Origin-Opener-Policy: same-origin
    Cross-Origin-Embedder-Policy: require-corp
You can tell if cross origin isolation is successfully enabled by looking at the global crossOriginIsolated variable in
javascript console. If it isn't, streaming requests will fallback to XMLHttpRequest, i.e. getting the whole
request into a buffer and then returning it. it shows a warning in the javascript console in this case.
Finally, the webworker which does the streaming fetch is created on initial import, but will only be started once
control is returned to javascript. Call `await wait_for_streaming_ready()` to wait for streaming fetch.
NB: in this code, there are a lot of javascript objects. They are named js_*
to make it clear what type of object they are.
Function Documentation
_obj_from_dict()
JsProxy urllib3.contrib.emscripten.fetch._obj_from_dict (dict[str, Any] dict_val) protected
Definition at line 88 of file fetch.py.
def _obj_from_dict(dict_val: dict[str, Any]) -> JsProxy:
    return to_js(dict_val, dict_converter=js.Object.fromEntries)
Referenced by urllib3.contrib.emscripten.fetch._ReadStream.close(), urllib3.contrib.emscripten.fetch._ReadStream.readinto(), and urllib3.contrib.emscripten.fetch._StreamingFetcher.send().
_show_streaming_warning()
None urllib3.contrib.emscripten.fetch._show_streaming_warning () protected
Definition at line 346 of file fetch.py.
def _show_streaming_warning() -> None:
    global _SHOWN_STREAMING_WARNING
    if not _SHOWN_STREAMING_WARNING:
        _SHOWN_STREAMING_WARNING = True
        message = "Can't stream HTTP requests because: \n"
        if not is_cross_origin_isolated():
            message += "  Page is not cross-origin isolated\n"
        if is_in_browser_main_thread():
            message += "  Python is running in main browser thread\n"
        if not is_worker_available():
            message += " Worker or Blob classes are not available in this environment."  # Defensive: this is always False in browsers that we test in
        if streaming_ready() is False:
            message += """ Streaming fetch worker isn't ready. If you want to be sure that streaming fetch
is working, you need to call: 'await urllib3.contrib.emscripten.fetch.wait_for_streaming_ready()`"""
        from js import console
        console.warn(message)
References is_cross_origin_isolated(), is_in_browser_main_thread(), is_worker_available(), and streaming_ready().
Referenced by send_streaming_request().
_show_timeout_warning()
None urllib3.contrib.emscripten.fetch._show_timeout_warning () protected
Definition at line 335 of file fetch.py.
def _show_timeout_warning() -> None:
    global _SHOWN_TIMEOUT_WARNING
    if not _SHOWN_TIMEOUT_WARNING:
        _SHOWN_TIMEOUT_WARNING = True
        message = "Warning: Timeout is not available on main browser thread"
        js.console.warn(message)
Referenced by send_request().
is_cross_origin_isolated()
bool urllib3.contrib.emscripten.fetch.is_cross_origin_isolated ()
Definition at line 296 of file fetch.py.
def is_cross_origin_isolated() -> bool:
    return hasattr(js, "crossOriginIsolated") and js.crossOriginIsolated
Referenced by _show_streaming_warning().
is_in_browser_main_thread()
bool urllib3.contrib.emscripten.fetch.is_in_browser_main_thread ()
Definition at line 292 of file fetch.py.
def is_in_browser_main_thread() -> bool:
    return hasattr(js, "window") and hasattr(js, "self") and js.self == js.window
Referenced by _show_streaming_warning(), and send_request().
is_in_node()
bool urllib3.contrib.emscripten.fetch.is_in_node ()
Definition at line 300 of file fetch.py.
def is_in_node() -> bool:
    return (
        hasattr(js, "process")
        and hasattr(js.process, "release")
        and hasattr(js.process.release, "name")
        and js.process.release.name == "node"
    )
is_worker_available()
bool urllib3.contrib.emscripten.fetch.is_worker_available ()
Definition at line 309 of file fetch.py.
def is_worker_available() -> bool:
    return hasattr(js, "Worker") and hasattr(js, "Blob")
Referenced by _show_streaming_warning().
send_request()
EmscriptenResponse urllib3.contrib.emscripten.fetch.send_request (EmscriptenRequest request)
Definition at line 365 of file fetch.py.
def send_request(request: EmscriptenRequest) -> EmscriptenResponse:
    try:
        js_xhr = js.XMLHttpRequest.new()
        if not is_in_browser_main_thread():
            js_xhr.responseType = "arraybuffer"
            if request.timeout:
                js_xhr.timeout = int(request.timeout * 1000)
        else:
            js_xhr.overrideMimeType("text/plain; charset=ISO-8859-15")
            if request.timeout:
                # timeout isn't available on the main thread - show a warning in console
                # if it is set
                _show_timeout_warning()
        js_xhr.open(request.method, request.url, False)
        for name, value in request.headers.items():
            if name.lower() not in HEADERS_TO_IGNORE:
                js_xhr.setRequestHeader(name, value)
        js_xhr.send(to_js(request.body))
        headers = dict(Parser().parsestr(js_xhr.getAllResponseHeaders()))
        if not is_in_browser_main_thread():
            body = js_xhr.response.to_py().tobytes()
        else:
            body = js_xhr.response.encode("ISO-8859-15")
        return EmscriptenResponse(
            status_code=js_xhr.status, headers=headers, body=body, request=request
        )
    except JsException as err:
        if err.name == "TimeoutError":
            raise _TimeoutError(err.message, request=request)
        elif err.name == "NetworkError":
            raise _RequestError(err.message, request=request)
        else:
            # general http error
            raise _RequestError(err.message, request=request)
References _show_timeout_warning(), and is_in_browser_main_thread().
send_streaming_request()
EmscriptenResponse | None urllib3.contrib.emscripten.fetch.send_streaming_request (EmscriptenRequest request)
Definition at line 324 of file fetch.py.
def send_streaming_request(request: EmscriptenRequest) -> EmscriptenResponse | None:
    if _fetcher and streaming_ready():
        return _fetcher.send(request)
    else:
        _show_streaming_warning()
        return None
References _show_streaming_warning(), and streaming_ready().
streaming_ready()
bool | None urllib3.contrib.emscripten.fetch.streaming_ready ()
Definition at line 406 of file fetch.py.
def streaming_ready() -> bool | None:
    if _fetcher:
        return _fetcher.streaming_ready
    else:
        return None  # no fetcher, return None to signify that
Referenced by _show_streaming_warning(), and send_streaming_request().
wait_for_streaming_ready()
bool urllib3.contrib.emscripten.fetch.wait_for_streaming_ready ()
Definition at line 413 of file fetch.py.
async def wait_for_streaming_ready() -> bool:
    if _fetcher:
        await _fetcher.js_worker_ready_promise
        return True
    else:
        return False
Variable Documentation
_fetcher
urllib3.contrib.emscripten.fetch._fetcher = None protected
Definition at line 313 of file fetch.py.
_SHOWN_STREAMING_WARNING
bool urllib3.contrib.emscripten.fetch._SHOWN_STREAMING_WARNING = False protected
Definition at line 343 of file fetch.py.
_SHOWN_TIMEOUT_WARNING
bool urllib3.contrib.emscripten.fetch._SHOWN_TIMEOUT_WARNING = False protected
Definition at line 332 of file fetch.py.
_STREAMING_WORKER_CODE
tuple urllib3.contrib.emscripten.fetch._STREAMING_WORKER_CODE protected
Initial value:
=  (
    files(__package__)
    .joinpath("emscripten_fetch_worker.js")
    .read_text(encoding="utf-8")
)
Definition at line 59 of file fetch.py.
ERROR_EXCEPTION
int urllib3.contrib.emscripten.fetch.ERROR_EXCEPTION = -4
Definition at line 57 of file fetch.py.
ERROR_TIMEOUT
int urllib3.contrib.emscripten.fetch.ERROR_TIMEOUT = -3
Definition at line 56 of file fetch.py.
HEADERS_TO_IGNORE
tuple urllib3.contrib.emscripten.fetch.HEADERS_TO_IGNORE = ("user-agent",)
Definition at line 52 of file fetch.py.
SUCCESS_EOF
int urllib3.contrib.emscripten.fetch.SUCCESS_EOF = -2
Definition at line 55 of file fetch.py.
SUCCESS_HEADER
int urllib3.contrib.emscripten.fetch.SUCCESS_HEADER = -1
Definition at line 54 of file fetch.py.