Read&Watch: urllib3.util.url Namespace Reference
urllib3.util.url Namespace Reference
Classes
class Url
Functions
str _encode_invalid_chars (str component, typing.Container[str] allowed_chars)
None _encode_invalid_chars (None component, typing.Container[str] allowed_chars)
str|None _encode_invalid_chars (str|None component, typing.Container[str] allowed_chars)
str _remove_path_dot_segments (str path)
None _normalize_host (None host, str|None scheme)
str _normalize_host (str host, str|None scheme)
str|None _normalize_host (str|None host, str|None scheme)
bytes _idna_encode (str name)
str _encode_target (str target)
Url parse_url (str url)
Variables
tuple _NORMALIZABLE_SCHEMES = ("http", "https", None)
_PERCENT_RE = re.compile(r"%[a-fA-F0-9]{2}")
_SCHEME_RE = re.compile(r"^(?:[a-zA-Z][a-zA-Z0-9+-]*:|/)")
_URI_RE
str _IPV4_PAT = r"(?:[0-9]{1,3}\.){3}[0-9]{1,3}"
str _HEX_PAT = "[0-9A-Fa-f]{1,4}"
str _LS32_PAT = "(?:{hex}:{hex}|{ipv4})".format(hex=_HEX_PAT, ipv4=_IPV4_PAT)
dict _subs = {"hex": _HEX_PAT, "ls32": _LS32_PAT}
list _variations
str _UNRESERVED_PAT = r"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789._\-~"
str _IPV6_PAT = "(?:" + "|".join([x % _subs for x in _variations]) + ")"
str _ZONE_ID_PAT = "(?:%25|%)(?:[" + _UNRESERVED_PAT + "]|%[a-fA-F0-9]{2})+"
str _IPV6_ADDRZ_PAT = r"\[" + _IPV6_PAT + r"(?:" + _ZONE_ID_PAT + r")?\]"
str _REG_NAME_PAT = r"(?:[^\[\]%:/?#]|%[a-fA-F0-9]{2})*"
_TARGET_RE = re.compile(r"^(/[^?#]*)(?:\?([^#]*))?(?:#.*)?$")
_IPV4_RE = re.compile("^" + _IPV4_PAT + "$")
_IPV6_RE = re.compile("^" + _IPV6_PAT + "$")
_IPV6_ADDRZ_RE = re.compile("^" + _IPV6_ADDRZ_PAT + "$")
_BRACELESS_IPV6_ADDRZ_RE = re.compile("^" + _IPV6_ADDRZ_PAT[2:-2] + "$")
_ZONE_ID_RE = re.compile("(" + _ZONE_ID_PAT + r")\]$")
tuple _HOST_PORT_PAT
_HOST_PORT_RE = re.compile(_HOST_PORT_PAT, re.UNICODE | re.DOTALL)
_UNRESERVED_CHARS
_SUB_DELIM_CHARS = set("!$&'()*+,;=")
_USERINFO_CHARS = _UNRESERVED_CHARS | _SUB_DELIM_CHARS | {":"}
_PATH_CHARS = _USERINFO_CHARS | {"@", "/"}
_QUERY_CHARS = _PATH_CHARS | {"?"}
Function Documentation
_encode_invalid_chars() [1/3]
None urllib3.util.url._encode_invalid_chars (None component, typing.Container[str] allowed_chars) protected
Definition at line 221 of file url.py.
) -> None:  # Abstract
    ...
_encode_invalid_chars() [2/3]
str urllib3.util.url._encode_invalid_chars (str component, typing.Container[str] allowed_chars) protected
Definition at line 214 of file url.py.
) -> str:  # Abstract
    ...
@typing.overload
Referenced by _encode_target(), _normalize_host(), and parse_url().
_encode_invalid_chars() [3/3]
str | None urllib3.util.url._encode_invalid_chars (str | None component, typing.Container[str] allowed_chars) protected
Percent-encodes a URI component without reapplying
onto an already percent-encoded component.
Definition at line 227 of file url.py.
) -> str | None:
    """Percent-encodes a URI component without reapplying
    onto an already percent-encoded component.
    """
    if component is None:
        return component
    component = to_str(component)
    # Normalize existing percent-encoded bytes.
    # Try to see if the component we're encoding is already percent-encoded
    # so we can skip all '%' characters but still encode all others.
    component, percent_encodings = _PERCENT_RE.subn(
        lambda match: match.group(0).upper(), component
    )
    uri_bytes = component.encode("utf-8", "surrogatepass")
    is_percent_encoded = percent_encodings == uri_bytes.count(b"%")
    encoded_component = bytearray()
    for i in range(0, len(uri_bytes)):
        # Will return a single character bytestring
        byte = uri_bytes[i : i + 1]
        byte_ord = ord(byte)
        if (is_percent_encoded and byte == b"%") or (
            byte_ord < 128 and byte.decode() in allowed_chars
        ):
            encoded_component += byte
            continue
        encoded_component.extend(b"%" + (hex(byte_ord)[2:].encode().zfill(2).upper()))
    return encoded_component.decode()
_encode_target()
str urllib3.util.url._encode_target (str target) protected
Percent-encodes a request target so that there are no invalid characters
Pre-condition for this function is that 'target' must start with '/'.
If that is the case then _TARGET_RE will always produce a match.
Definition at line 351 of file url.py.
def _encode_target(target: str) -> str:
    """Percent-encodes a request target so that there are no invalid characters
    Pre-condition for this function is that 'target' must start with '/'.
    If that is the case then _TARGET_RE will always produce a match.
    """
    match = _TARGET_RE.match(target)
    if not match:  # Defensive:
        raise LocationParseError(f"{target!r} is not a valid request URI")
    path, query = match.groups()
    encoded_target = _encode_invalid_chars(path, _PATH_CHARS)
    if query is not None:
        query = _encode_invalid_chars(query, _QUERY_CHARS)
        encoded_target += "?" + query
    return encoded_target
References _encode_invalid_chars().
_idna_encode()
bytes urllib3.util.url._idna_encode (str name) protected
Definition at line 332 of file url.py.
def _idna_encode(name: str) -> bytes:
    if not name.isascii():
        try:
            import idna
        except ImportError:
            raise LocationParseError(
                "Unable to parse URL without the 'idna' module"
            ) from None
        try:
            return idna.encode(name.lower(), strict=True, std3_rules=True)
        except idna.IDNAError:
            raise LocationParseError(
                f"Name '{name}' is not a valid IDNA label"
            ) from None
    return name.lower().encode("ascii")
Referenced by _normalize_host().
_normalize_host() [1/3]
None urllib3.util.url._normalize_host (None host, str | None scheme) protected
Definition at line 294 of file url.py.
def _normalize_host(host: None, scheme: str | None) -> None:
    ...
@typing.overload
Referenced by parse_url().
_normalize_host() [2/3]
str urllib3.util.url._normalize_host (str host, str | None scheme) protected
Definition at line 299 of file url.py.
def _normalize_host(host: str, scheme: str | None) -> str:
    ...
_normalize_host() [3/3]
str | None urllib3.util.url._normalize_host (str | None host, str | None scheme) protected
Definition at line 303 of file url.py.
def _normalize_host(host: str | None, scheme: str | None) -> str | None:
    if host:
        if scheme in _NORMALIZABLE_SCHEMES:
            is_ipv6 = _IPV6_ADDRZ_RE.match(host)
            if is_ipv6:
                # IPv6 hosts of the form 'a::b%zone' are encoded in a URL as
                # such per RFC 6874: 'a::b%25zone'. Unquote the ZoneID
                # separator as necessary to return a valid RFC 4007 scoped IP.
                match = _ZONE_ID_RE.search(host)
                if match:
                    start, end = match.span(1)
                    zone_id = host[start:end]
                    if zone_id.startswith("%25") and zone_id != "%25":
                        zone_id = zone_id[3:]
                    else:
                        zone_id = zone_id[1:]
                    zone_id = _encode_invalid_chars(zone_id, _UNRESERVED_CHARS)
                    return f"{host[:start].lower()}%{zone_id}{host[end:]}"
                else:
                    return host.lower()
            elif not _IPV4_RE.match(host):
                return to_str(
                    b".".join([_idna_encode(label) for label in host.split(".")]),
                    "ascii",
                )
    return host
References _encode_invalid_chars(), and _idna_encode().
_remove_path_dot_segments()
str urllib3.util.url._remove_path_dot_segments (str path) protected
Definition at line 263 of file url.py.
def _remove_path_dot_segments(path: str) -> str:
    # See http://tools.ietf.org/html/rfc3986#section-5.2.4 for pseudo-code
    segments = path.split("/")  # Turn the path into a list of segments
    output = []  # Initialize the variable to use to store output
    for segment in segments:
        # '.' is the current directory, so ignore it, it is superfluous
        if segment == ".":
            continue
        # Anything other than '..', should be appended to the output
        if segment != "..":
            output.append(segment)
        # In this case segment == '..', if we can, we should pop the last
        # element
        elif output:
            output.pop()
    # If the path starts with '/' and the output is empty or the first string
    # is non-empty
    if path.startswith("/") and (not output or output[0]):
        output.insert(0, "")
    # If the path starts with '/.' or '/..' ensure we add one more empty
    # string to add a trailing '/'
    if path.endswith(("/.", "/..")):
        output.append("")
    return "/".join(output)
@typing.overload
Referenced by parse_url().
parse_url()
Url urllib3.util.url.parse_url (str url)
Given a url, return a parsed :class:`.Url` namedtuple. Best-effort is
performed to parse incomplete urls. Fields not provided will be None.
This parser is RFC 3986 and RFC 6874 compliant.
The parser logic and helper functions are based heavily on
work done in the ``rfc3986`` module.
:param str url: URL to parse into a :class:`.Url` namedtuple.
Partly backwards-compatible with :mod:`urllib.parse`.
Example:
.. code-block:: python
    import urllib3
    print( urllib3.util.parse_url('http://google.com/mail/'))
    # Url(scheme='http', host='google.com', port=None, path='/mail/', ...)
    print( urllib3.util.parse_url('google.com:80'))
    # Url(scheme=None, host='google.com', port=80, path=None, ...)
    print( urllib3.util.parse_url('/foo?bar'))
    # Url(scheme=None, host=None, port=None, path='/foo', query='bar', ...)
Definition at line 369 of file url.py.
def parse_url(url: str) -> Url:
    """
    Given a url, return a parsed :class:`.Url` namedtuple. Best-effort is
    performed to parse incomplete urls. Fields not provided will be None.
    This parser is RFC 3986 and RFC 6874 compliant.
    The parser logic and helper functions are based heavily on
    work done in the ``rfc3986`` module.
    :param str url: URL to parse into a :class:`.Url` namedtuple.
    Partly backwards-compatible with :mod:`urllib.parse`.
    Example:
    .. code-block:: python
        import urllib3
        print( urllib3.util.parse_url('http://google.com/mail/'))
        # Url(scheme='http', host='google.com', port=None, path='/mail/', ...)
        print( urllib3.util.parse_url('google.com:80'))
        # Url(scheme=None, host='google.com', port=80, path=None, ...)
        print( urllib3.util.parse_url('/foo?bar'))
        # Url(scheme=None, host=None, port=None, path='/foo', query='bar', ...)
    """
    if not url:
        # Empty
        return Url()
    source_url = url
    if not _SCHEME_RE.search(url):
        url = "//" + url
    scheme: str | None
    authority: str | None
    auth: str | None
    host: str | None
    port: str | None
    port_int: int | None
    path: str | None
    query: str | None
    fragment: str | None
    try:
        scheme, authority, path, query, fragment = _URI_RE.match(url).groups()  # type: ignore[union-attr]
        normalize_uri = scheme is None or scheme.lower() in _NORMALIZABLE_SCHEMES
        if scheme:
            scheme = scheme.lower()
        if authority:
            auth, _, host_port = authority.rpartition("@")
            auth = auth or None
            host, port = _HOST_PORT_RE.match(host_port).groups()  # type: ignore[union-attr]
            if auth and normalize_uri:
                auth = _encode_invalid_chars(auth, _USERINFO_CHARS)
            if port == "":
                port = None
        else:
            auth, host, port = None, None, None
        if port is not None:
            port_int = int(port)
            if not (0 <= port_int <= 65535):
                raise LocationParseError(url)
        else:
            port_int = None
        host = _normalize_host(host, scheme)
        if normalize_uri and path:
            path = _remove_path_dot_segments(path)
            path = _encode_invalid_chars(path, _PATH_CHARS)
        if normalize_uri and query:
            query = _encode_invalid_chars(query, _QUERY_CHARS)
        if normalize_uri and fragment:
            fragment = _encode_invalid_chars(fragment, _FRAGMENT_CHARS)
    except (ValueError, AttributeError) as e:
        raise LocationParseError(source_url) from e
    # For the sake of backwards compatibility we put empty
    # string values for path if there are any defined values
    # beyond the path in the URL.
    # TODO: Remove this when we break backwards compatibility.
    if not path:
        if query is not None or fragment is not None:
            path = ""
        else:
            path = None
    return Url(
        scheme=scheme,
        auth=auth,
        host=host,
        port=port_int,
        path=path,
        query=query,
        fragment=fragment,
    )
References _encode_invalid_chars(), _normalize_host(), and _remove_path_dot_segments().
Variable Documentation
_BRACELESS_IPV6_ADDRZ_RE
urllib3.util.url._BRACELESS_IPV6_ADDRZ_RE = re.compile("^" + _IPV6_ADDRZ_PAT[2:-2] + "$") protected
Definition at line 61 of file url.py.
_HEX_PAT
str urllib3.util.url._HEX_PAT = "[0-9A-Fa-f]{1,4}" protected
Definition at line 27 of file url.py.
_HOST_PORT_PAT
tuple urllib3.util.url._HOST_PORT_PAT protected
Initial value:
=  ("^(%s|%s|%s)(?::0*?(|0|[1-9][0-9]{0,4}))?$") % (
    _REG_NAME_PAT,
    _IPV4_PAT,
    _IPV6_ADDRZ_PAT,
)
Definition at line 64 of file url.py.
_HOST_PORT_RE
urllib3.util.url._HOST_PORT_RE = re.compile(_HOST_PORT_PAT, re.UNICODE | re.DOTALL) protected
Definition at line 69 of file url.py.
_IPV4_PAT
str urllib3.util.url._IPV4_PAT = r"(?:[0-9]{1,3}\.){3}[0-9]{1,3}" protected
Definition at line 26 of file url.py.
_IPV4_RE
urllib3.util.url._IPV4_RE = re.compile("^" + _IPV4_PAT + "$") protected
Definition at line 58 of file url.py.
_IPV6_ADDRZ_PAT
str urllib3.util.url._IPV6_ADDRZ_PAT = r"\[" + _IPV6_PAT + r"(?:" + _ZONE_ID_PAT + r")?\]" protected
Definition at line 54 of file url.py.
_IPV6_ADDRZ_RE
urllib3.util.url._IPV6_ADDRZ_RE = re.compile("^" + _IPV6_ADDRZ_PAT + "$") protected
Definition at line 60 of file url.py.
_IPV6_PAT
str urllib3.util.url._IPV6_PAT = "(?:" + "|".join([x % _subs for x in _variations]) + ")" protected
Definition at line 52 of file url.py.
_IPV6_RE
urllib3.util.url._IPV6_RE = re.compile("^" + _IPV6_PAT + "$") protected
Definition at line 59 of file url.py.
_LS32_PAT
str urllib3.util.url._LS32_PAT = "(?:{hex}:{hex}|{ipv4})".format(hex=_HEX_PAT, ipv4=_IPV4_PAT) protected
Definition at line 28 of file url.py.
_NORMALIZABLE_SCHEMES
tuple urllib3.util.url._NORMALIZABLE_SCHEMES = ("http", "https", None) protected
Definition at line 11 of file url.py.
_PATH_CHARS
urllib3.util.url._PATH_CHARS = _USERINFO_CHARS | {"@", "/"} protected
Definition at line 76 of file url.py.
_PERCENT_RE
urllib3.util.url._PERCENT_RE = re.compile(r"%[a-fA-F0-9]{2}") protected
Definition at line 15 of file url.py.
_QUERY_CHARS
urllib3.util.url._QUERY_CHARS = _PATH_CHARS | {"?"} protected
Definition at line 77 of file url.py.
_REG_NAME_PAT
str urllib3.util.url._REG_NAME_PAT = r"(?:[^\[\]%:/?#]|%[a-fA-F0-9]{2})*" protected
Definition at line 55 of file url.py.
_SCHEME_RE
urllib3.util.url._SCHEME_RE = re.compile(r"^(?:[a-zA-Z][a-zA-Z0-9+-]*:|/)") protected
Definition at line 16 of file url.py.
_SUB_DELIM_CHARS
urllib3.util.url._SUB_DELIM_CHARS = set("!$&'()*+,;=") protected
Definition at line 74 of file url.py.
_subs
dict urllib3.util.url._subs = {"hex": _HEX_PAT, "ls32": _LS32_PAT} protected
Definition at line 29 of file url.py.
_TARGET_RE
urllib3.util.url._TARGET_RE = re.compile(r"^(/[^?#]*)(?:\?([^#]*))?(?:#.*)?$") protected
Definition at line 56 of file url.py.
_UNRESERVED_CHARS
urllib3.util.url._UNRESERVED_CHARS protected
Initial value:
=  set(
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789._-~"
)
Definition at line 71 of file url.py.
_UNRESERVED_PAT
str urllib3.util.url._UNRESERVED_PAT = r"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789._\-~" protected
Definition at line 51 of file url.py.
_URI_RE
urllib3.util.url._URI_RE protected
Initial value:
=  re.compile(
    r"^(?:([a-zA-Z][a-zA-Z0-9+.-]*):)?"
    r"(?://([^\\/?#]*))?"
    r"([^?#]*)"
    r"(?:\?([^#]*))?"
    r"(?:#(.*))?$",
    re.UNICODE | re.DOTALL,
)
Definition at line 17 of file url.py.
_USERINFO_CHARS
urllib3.util.url._USERINFO_CHARS = _UNRESERVED_CHARS | _SUB_DELIM_CHARS | {":"} protected
Definition at line 75 of file url.py.
_variations
list urllib3.util.url._variations protected
Initial value:
=  [
    #                            6( h16 ":" ) ls32
    "(?:%(hex)s:){6}%(ls32)s",
    #                       "::" 5( h16 ":" ) ls32
    "::(?:%(hex)s:){5}%(ls32)s",
    # [               h16 ] "::" 4( h16 ":" ) ls32
    "(?:%(hex)s)?::(?:%(hex)s:){4}%(ls32)s",
    # [ *1( h16 ":" ) h16 ] "::" 3( h16 ":" ) ls32
    "(?:(?:%(hex)s:)?%(hex)s)?::(?:%(hex)s:){3}%(ls32)s",
    # [ *2( h16 ":" ) h16 ] "::" 2( h16 ":" ) ls32
    "(?:(?:%(hex)s:){0,2}%(hex)s)?::(?:%(hex)s:){2}%(ls32)s",
    # [ *3( h16 ":" ) h16 ] "::"    h16 ":"   ls32
    "(?:(?:%(hex)s:){0,3}%(hex)s)?::%(hex)s:%(ls32)s",
    # [ *4( h16 ":" ) h16 ] "::"              ls32
    "(?:(?:%(hex)s:){0,4}%(hex)s)?::%(ls32)s",
    # [ *5( h16 ":" ) h16 ] "::"              h16
    "(?:(?:%(hex)s:){0,5}%(hex)s)?::%(hex)s",
    # [ *6( h16 ":" ) h16 ] "::"
    "(?:(?:%(hex)s:){0,6}%(hex)s)?::",
]
Definition at line 30 of file url.py.
_ZONE_ID_PAT
str urllib3.util.url._ZONE_ID_PAT = "(?:%25|%)(?:[" + _UNRESERVED_PAT + "]|%[a-fA-F0-9]{2})+" protected
Definition at line 53 of file url.py.
_ZONE_ID_RE
urllib3.util.url._ZONE_ID_RE = re.compile("(" + _ZONE_ID_PAT + r")\]$") protected
Definition at line 62 of file url.py.