Read&Watch: django.core.files.base Namespace Reference
django.core.files.base Namespace Reference
Classes
class ContentFile
class File
Functions
endswith_cr (line)
endswith_lf (line)
equals_lf (line)
Function Documentation
endswith_cr()
django.core.files.base.endswith_cr (line)
Return True if line (a text or bytestring) ends with '\r'.
Definition at line 149 of file base.py.
def endswith_cr(line):
    """Return True if line (a text or bytestring) ends with '\r'."""
    return line.endswith("\r" if isinstance(line, str) else b"\r")
Referenced by django.core.files.base.File.__iter__().
endswith_lf()
django.core.files.base.endswith_lf (line)
Return True if line (a text or bytestring) ends with '\n'.
Definition at line 154 of file base.py.
def endswith_lf(line):
    """Return True if line (a text or bytestring) ends with '\n'."""
    return line.endswith("\n" if isinstance(line, str) else b"\n")
Referenced by django.core.files.base.File.__iter__().
equals_lf()
django.core.files.base.equals_lf (line)
Return True if line (a text or bytestring) equals '\n'.
Definition at line 159 of file base.py.
def equals_lf(line):
    """Return True if line (a text or bytestring) equals '\n'."""
    return line == ("\n" if isinstance(line, str) else b"\n")
Referenced by django.core.files.base.File.__iter__().