Read&Watch: pip._vendor.urllib3.util.ssl_ Namespace Reference
pip._vendor.urllib3.util.ssl_ Namespace Reference
Classes
class SSLContext
Functions
_const_compare_digest_backport (a, b)
assert_fingerprint (cert, fingerprint)
resolve_cert_reqs (candidate)
resolve_ssl_version (candidate)
create_urllib3_context (ssl_version=None, cert_reqs=None, options=None, ciphers=None)
ssl_wrap_socket (sock, keyfile=None, certfile=None, cert_reqs=None, ca_certs=None, server_hostname=None, ssl_version=None, ciphers=None, ssl_context=None, ca_cert_dir=None, key_password=None, ca_cert_data=None, tls_in_tls=False)
is_ipaddress (hostname)
_is_key_file_encrypted (key_file)
_ssl_wrap_socket_impl (sock, ssl_context, tls_in_tls, server_hostname=None)
Variables
SSLContext = None
SSLTransport = None
bool HAS_SNI = False
bool IS_PYOPENSSL = False
bool IS_SECURETRANSPORT = False
list ALPN_PROTOCOLS = ["http/1.1"]
dict HASHFUNC_MAP
_const_compare_digest = getattr(hmac, "compare_digest", _const_compare_digest_backport)
PROTOCOL_SSLv23 = PROTOCOL_TLS
PROTOCOL_TLS_CLIENT = PROTOCOL_TLS
OP_NO_SSLv2
OP_NO_SSLv3
int OP_NO_COMPRESSION = 0x20000
int OP_NO_TICKET = 0x4000
str DEFAULT_CIPHERS
Function Documentation
_const_compare_digest_backport()
pip._vendor.urllib3.util.ssl_._const_compare_digest_backport (a, b) protected
Compare two digests of equal length in constant time.
The digests must be of type str/bytes.
Returns True if the digests match, and False otherwise.
Definition at line 33 of file ssl_.py.
def _const_compare_digest_backport(a, b):
    """
    Compare two digests of equal length in constant time.
    The digests must be of type str/bytes.
    Returns True if the digests match, and False otherwise.
    """
    result = abs(len(a) - len(b))
    for left, right in zip(bytearray(a), bytearray(b)):
        result |= left ^ right
    return result == 0
_is_key_file_encrypted()
pip._vendor.urllib3.util.ssl_._is_key_file_encrypted (key_file) protected
Detects if a key file is encrypted or not.
Definition at line 479 of file ssl_.py.
def _is_key_file_encrypted(key_file):
    """Detects if a key file is encrypted or not."""
    with open(key_file, "r") as f:
        for line in f:
            # Look for Proc-Type: 4,ENCRYPTED
            if "ENCRYPTED" in line:
                return True
    return False
Referenced by ssl_wrap_socket().
_ssl_wrap_socket_impl()
pip._vendor.urllib3.util.ssl_._ssl_wrap_socket_impl (sock, ssl_context, tls_in_tls, server_hostname = None) protected
Definition at line 490 of file ssl_.py.
def _ssl_wrap_socket_impl(sock, ssl_context, tls_in_tls, server_hostname=None):
    if tls_in_tls:
        if not SSLTransport:
            # Import error, ssl is not available.
            raise ProxySchemeUnsupported(
                "TLS in TLS requires support for the 'ssl' module"
            )
        SSLTransport._validate_ssl_context_for_tls_in_tls(ssl_context)
        return SSLTransport(sock, ssl_context, server_hostname)
    if server_hostname:
        return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
    else:
        return ssl_context.wrap_socket(sock)
Referenced by ssl_wrap_socket().
assert_fingerprint()
pip._vendor.urllib3.util.ssl_.assert_fingerprint (cert, fingerprint)
Checks if given fingerprint matches the supplied certificate.
:param cert:
    Certificate as bytes object.
:param fingerprint:
    Fingerprint as string of hexdigits, can be interspersed by colons.
Definition at line 185 of file ssl_.py.
def assert_fingerprint(cert, fingerprint):
    """
    Checks if given fingerprint matches the supplied certificate.
    :param cert:
        Certificate as bytes object.
    :param fingerprint:
        Fingerprint as string of hexdigits, can be interspersed by colons.
    """
    fingerprint = fingerprint.replace(":", "").lower()
    digest_length = len(fingerprint)
    if digest_length not in HASHFUNC_MAP:
        raise SSLError("Fingerprint of invalid length: {0}".format(fingerprint))
    hashfunc = HASHFUNC_MAP.get(digest_length)
    if hashfunc is None:
        raise SSLError(
            "Hash function implementation unavailable for fingerprint length: {0}".format(
                digest_length
            )
        )
    # We need encode() here for py32; works on py2 and p33.
    fingerprint_bytes = unhexlify(fingerprint.encode())
    cert_digest = hashfunc(cert).digest()
    if not _const_compare_digest(cert_digest, fingerprint_bytes):
        raise SSLError(
            'Fingerprints did not match. Expected "{0}", got "{1}".'.format(
                fingerprint, hexlify(cert_digest)
            )
        )
References _const_compare_digest.
create_urllib3_context()
pip._vendor.urllib3.util.ssl_.create_urllib3_context (ssl_version = None, cert_reqs = None, options = None, ciphers = None)
All arguments have the same meaning as ``ssl_wrap_socket``.
By default, this function does a lot of the same work that
``ssl.create_default_context`` does on Python 3.4+. It:
- Disables SSLv2, SSLv3, and compression
- Sets a restricted set of server ciphers
If you wish to enable SSLv3, you can do::
    from pip._vendor.urllib3.util import ssl_
    context = ssl_.create_urllib3_context()
    context.options &= ~ssl_.OP_NO_SSLv3
You can do the same to enable compression (substituting ``COMPRESSION``
for ``SSLv3`` in the last line above).
:param ssl_version:
    The desired protocol version to use. This will default to
    PROTOCOL_SSLv23 which will negotiate the highest protocol that both
    the server and your installation of OpenSSL support.
:param cert_reqs:
    Whether to require the certificate verification. This defaults to
    ``ssl.CERT_REQUIRED``.
:param options:
    Specific OpenSSL options. These default to ``ssl.OP_NO_SSLv2``,
    ``ssl.OP_NO_SSLv3``, ``ssl.OP_NO_COMPRESSION``, and ``ssl.OP_NO_TICKET``.
:param ciphers:
    Which cipher suites to allow the server to select.
:returns:
    Constructed SSLContext object with specified options
:rtype: SSLContext
Definition at line 259 of file ssl_.py.
):
    """All arguments have the same meaning as ``ssl_wrap_socket``.
    By default, this function does a lot of the same work that
    ``ssl.create_default_context`` does on Python 3.4+. It:
    - Disables SSLv2, SSLv3, and compression
    - Sets a restricted set of server ciphers
    If you wish to enable SSLv3, you can do::
        from pip._vendor.urllib3.util import ssl_
        context = ssl_.create_urllib3_context()
        context.options &= ~ssl_.OP_NO_SSLv3
    You can do the same to enable compression (substituting ``COMPRESSION``
    for ``SSLv3`` in the last line above).
    :param ssl_version:
        The desired protocol version to use. This will default to
        PROTOCOL_SSLv23 which will negotiate the highest protocol that both
        the server and your installation of OpenSSL support.
    :param cert_reqs:
        Whether to require the certificate verification. This defaults to
        ``ssl.CERT_REQUIRED``.
    :param options:
        Specific OpenSSL options. These default to ``ssl.OP_NO_SSLv2``,
        ``ssl.OP_NO_SSLv3``, ``ssl.OP_NO_COMPRESSION``, and ``ssl.OP_NO_TICKET``.
    :param ciphers:
        Which cipher suites to allow the server to select.
    :returns:
        Constructed SSLContext object with specified options
    :rtype: SSLContext
    """
    # PROTOCOL_TLS is deprecated in Python 3.10
    if not ssl_version or ssl_version == PROTOCOL_TLS:
        ssl_version = PROTOCOL_TLS_CLIENT
    context = SSLContext(ssl_version)
    context.set_ciphers(ciphers or DEFAULT_CIPHERS)
    # Setting the default here, as we may have no ssl module on import
    cert_reqs = ssl.CERT_REQUIRED if cert_reqs is None else cert_reqs
    if options is None:
        options = 0
        # SSLv2 is easily broken and is considered harmful and dangerous
        options |= OP_NO_SSLv2
        # SSLv3 has several problems and is now dangerous
        options |= OP_NO_SSLv3
        # Disable compression to prevent CRIME attacks for OpenSSL 1.0+
        # (issue #309)
        options |= OP_NO_COMPRESSION
        # TLSv1.2 only. Unless set explicitly, do not request tickets.
        # This may save some bandwidth on wire, and although the ticket is encrypted,
        # there is a risk associated with it being on wire,
        # if the server is not rotating its ticketing keys properly.
        options |= OP_NO_TICKET
    context.options |= options
    # Enable post-handshake authentication for TLS 1.3, see GH #1634. PHA is
    # necessary for conditional client cert authentication with TLS 1.3.
    # The attribute is None for OpenSSL <= 1.1.0 or does not exist in older
    # versions of Python.  We only enable on Python 3.7.4+ or if certificate
    # verification is enabled to work around Python issue #37428
    # See: https://bugs.python.org/issue37428
    if (cert_reqs == ssl.CERT_REQUIRED or sys.version_info >= (3, 7, 4)) and getattr(
        context, "post_handshake_auth", None
    ) is not None:
        context.post_handshake_auth = True
    def disable_check_hostname():
        if (
            getattr(context, "check_hostname", None) is not None
        ):  # Platform-specific: Python 3.2
            # We do our own verification, including fingerprints and alternative
            # hostnames. So disable it here
            context.check_hostname = False
    # The order of the below lines setting verify_mode and check_hostname
    # matter due to safe-guards SSLContext has to prevent an SSLContext with
    # check_hostname=True, verify_mode=NONE/OPTIONAL. This is made even more
    # complex because we don't know whether PROTOCOL_TLS_CLIENT will be used
    # or not so we don't know the initial state of the freshly created SSLContext.
    if cert_reqs == ssl.CERT_REQUIRED:
        context.verify_mode = cert_reqs
        disable_check_hostname()
    else:
        disable_check_hostname()
        context.verify_mode = cert_reqs
    # Enable logging of TLS session keys via defacto standard environment variable
    # 'SSLKEYLOGFILE', if the feature is available (Python 3.8+). Skip empty values.
    if hasattr(context, "keylog_filename"):
        sslkeylogfile = os.environ.get("SSLKEYLOGFILE")
        if sslkeylogfile:
            context.keylog_filename = sslkeylogfile
    return context
Referenced by ssl_wrap_socket().
is_ipaddress()
pip._vendor.urllib3.util.ssl_.is_ipaddress (hostname)
Detects whether the hostname given is an IPv4 or IPv6 address.
Also detects IPv6 addresses with Zone IDs.
:param str hostname: Hostname to examine.
:return: True if the hostname is an IP address, False otherwise.
Definition at line 466 of file ssl_.py.
def is_ipaddress(hostname):
    """Detects whether the hostname given is an IPv4 or IPv6 address.
    Also detects IPv6 addresses with Zone IDs.
    :param str hostname: Hostname to examine.
    :return: True if the hostname is an IP address, False otherwise.
    """
    if not six.PY2 and isinstance(hostname, bytes):
        # IDN A-label bytes are ASCII compatible.
        hostname = hostname.decode("ascii")
    return bool(IPV4_RE.match(hostname) or BRACELESS_IPV6_ADDRZ_RE.match(hostname))
Referenced by ssl_wrap_socket().
resolve_cert_reqs()
pip._vendor.urllib3.util.ssl_.resolve_cert_reqs (candidate)
Resolves the argument to a numeric constant, which can be passed to
the wrap_socket function/method from the ssl module.
Defaults to :data:`ssl.CERT_REQUIRED`.
If given a string it is assumed to be the name of the constant in the
:mod:`ssl` module or its abbreviation.
(So you can specify `REQUIRED` instead of `CERT_REQUIRED`.
If it's neither `None` nor a string we assume it is already the numeric
constant which can directly be passed to wrap_socket.
Definition at line 220 of file ssl_.py.
def resolve_cert_reqs(candidate):
    """
    Resolves the argument to a numeric constant, which can be passed to
    the wrap_socket function/method from the ssl module.
    Defaults to :data:`ssl.CERT_REQUIRED`.
    If given a string it is assumed to be the name of the constant in the
    :mod:`ssl` module or its abbreviation.
    (So you can specify `REQUIRED` instead of `CERT_REQUIRED`.
    If it's neither `None` nor a string we assume it is already the numeric
    constant which can directly be passed to wrap_socket.
    """
    if candidate is None:
        return CERT_REQUIRED
    if isinstance(candidate, str):
        res = getattr(ssl, candidate, None)
        if res is None:
            res = getattr(ssl, "CERT_" + candidate)
        return res
    return candidate
resolve_ssl_version()
pip._vendor.urllib3.util.ssl_.resolve_ssl_version (candidate)
like resolve_cert_reqs
Definition at line 243 of file ssl_.py.
def resolve_ssl_version(candidate):
    """
    like resolve_cert_reqs
    """
    if candidate is None:
        return PROTOCOL_TLS
    if isinstance(candidate, str):
        res = getattr(ssl, candidate, None)
        if res is None:
            res = getattr(ssl, "PROTOCOL_" + candidate)
        return res
    return candidate
ssl_wrap_socket()
pip._vendor.urllib3.util.ssl_.ssl_wrap_socket (sock, keyfile = None, certfile = None, cert_reqs = None, ca_certs = None, server_hostname = None, ssl_version = None, ciphers = None, ssl_context = None, ca_cert_dir = None, key_password = None, ca_cert_data = None, tls_in_tls = False)
All arguments except for server_hostname, ssl_context, and ca_cert_dir have
the same meaning as they do when using :func:`ssl.wrap_socket`.
:param server_hostname:
    When SNI is supported, the expected hostname of the certificate
:param ssl_context:
    A pre-made :class:`SSLContext` object. If none is provided, one will
    be created using :func:`create_urllib3_context`.
:param ciphers:
    A string of ciphers we wish the client to support.
:param ca_cert_dir:
    A directory containing CA certificates in multiple separate files, as
    supported by OpenSSL's -CApath flag or the capath argument to
    SSLContext.load_verify_locations().
:param key_password:
    Optional password if the keyfile is encrypted.
:param ca_cert_data:
    Optional string containing CA certificates in PEM format suitable for
    passing as the cadata parameter to SSLContext.load_verify_locations()
:param tls_in_tls:
    Use SSLTransport to wrap the existing socket.
Definition at line 364 of file ssl_.py.
):
    """
    All arguments except for server_hostname, ssl_context, and ca_cert_dir have
    the same meaning as they do when using :func:`ssl.wrap_socket`.
    :param server_hostname:
        When SNI is supported, the expected hostname of the certificate
    :param ssl_context:
        A pre-made :class:`SSLContext` object. If none is provided, one will
        be created using :func:`create_urllib3_context`.
    :param ciphers:
        A string of ciphers we wish the client to support.
    :param ca_cert_dir:
        A directory containing CA certificates in multiple separate files, as
        supported by OpenSSL's -CApath flag or the capath argument to
        SSLContext.load_verify_locations().
    :param key_password:
        Optional password if the keyfile is encrypted.
    :param ca_cert_data:
        Optional string containing CA certificates in PEM format suitable for
        passing as the cadata parameter to SSLContext.load_verify_locations()
    :param tls_in_tls:
        Use SSLTransport to wrap the existing socket.
    """
    context = ssl_context
    if context is None:
        # Note: This branch of code and all the variables in it are no longer
        # used by urllib3 itself. We should consider deprecating and removing
        # this code.
        context = create_urllib3_context(ssl_version, cert_reqs, ciphers=ciphers)
    if ca_certs or ca_cert_dir or ca_cert_data:
        try:
            context.load_verify_locations(ca_certs, ca_cert_dir, ca_cert_data)
        except (IOError, OSError) as e:
            raise SSLError(e)
    elif ssl_context is None and hasattr(context, "load_default_certs"):
        # try to load OS default certs; works well on Windows (require Python3.4+)
        context.load_default_certs()
    # Attempt to detect if we get the goofy behavior of the
    # keyfile being encrypted and OpenSSL asking for the
    # passphrase via the terminal and instead error out.
    if keyfile and key_password is None and _is_key_file_encrypted(keyfile):
        raise SSLError("Client private key is encrypted, password is required")
    if certfile:
        if key_password is None:
            context.load_cert_chain(certfile, keyfile)
        else:
            context.load_cert_chain(certfile, keyfile, key_password)
    try:
        if hasattr(context, "set_alpn_protocols"):
            context.set_alpn_protocols(ALPN_PROTOCOLS)
    except NotImplementedError:  # Defensive: in CI, we always have set_alpn_protocols
        pass
    # If we detect server_hostname is an IP address then the SNI
    # extension should not be used according to RFC3546 Section 3.1
    use_sni_hostname = server_hostname and not is_ipaddress(server_hostname)
    # SecureTransport uses server_hostname in certificate verification.
    send_sni = (use_sni_hostname and HAS_SNI) or (
        IS_SECURETRANSPORT and server_hostname
    )
    # Do not warn the user if server_hostname is an invalid SNI hostname.
    if not HAS_SNI and use_sni_hostname:
        warnings.warn(
            "An HTTPS request has been made, but the SNI (Server Name "
            "Indication) extension to TLS is not available on this platform. "
            "This may cause the server to present an incorrect TLS "
            "certificate, which can cause validation failures. You can upgrade to "
            "a newer version of Python to solve this. For more information, see "
            "https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html"
            "#ssl-warnings",
            SNIMissingWarning,
        )
    if send_sni:
        ssl_sock = _ssl_wrap_socket_impl(
            sock, context, tls_in_tls, server_hostname=server_hostname
        )
    else:
        ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
    return ssl_sock
References _is_key_file_encrypted(), _ssl_wrap_socket_impl(), create_urllib3_context(), and is_ipaddress().
Variable Documentation
_const_compare_digest
pip._vendor.urllib3.util.ssl_._const_compare_digest = getattr(hmac, "compare_digest", _const_compare_digest_backport) protected
Definition at line 46 of file ssl_.py.
Referenced by assert_fingerprint().
ALPN_PROTOCOLS
list pip._vendor.urllib3.util.ssl_.ALPN_PROTOCOLS = ["http/1.1"]
Definition at line 24 of file ssl_.py.
DEFAULT_CIPHERS
str pip._vendor.urllib3.util.ssl_.DEFAULT_CIPHERS
Initial value:
=  ":".join(
    [
        "ECDHE+AESGCM",
        "ECDHE+CHACHA20",
        "DHE+AESGCM",
        "DHE+CHACHA20",
        "ECDH+AESGCM",
        "DH+AESGCM",
        "ECDH+AES",
        "DH+AES",
        "RSA+AESGCM",
        "RSA+AES",
        "!aNULL",
        "!eNULL",
        "!MD5",
        "!DSS",
    ]
)
Definition at line 113 of file ssl_.py.
HAS_SNI
bool pip._vendor.urllib3.util.ssl_.HAS_SNI = False
Definition at line 21 of file ssl_.py.
HASHFUNC_MAP
dict pip._vendor.urllib3.util.ssl_.HASHFUNC_MAP
Initial value:
=  {
    length: getattr(hashlib, algorithm, None)
    for length, algorithm in ((32, "md5"), (40, "sha1"), (64, "sha256"))
}
Definition at line 27 of file ssl_.py.
IS_PYOPENSSL
bool pip._vendor.urllib3.util.ssl_.IS_PYOPENSSL = False
Definition at line 22 of file ssl_.py.
IS_SECURETRANSPORT
bool pip._vendor.urllib3.util.ssl_.IS_SECURETRANSPORT = False
Definition at line 23 of file ssl_.py.
OP_NO_COMPRESSION
int pip._vendor.urllib3.util.ssl_.OP_NO_COMPRESSION = 0x20000
Definition at line 87 of file ssl_.py.
OP_NO_SSLv2
pip._vendor.urllib3.util.ssl_.OP_NO_SSLv2
Definition at line 86 of file ssl_.py.
OP_NO_SSLv3
pip._vendor.urllib3.util.ssl_.OP_NO_SSLv3
Definition at line 86 of file ssl_.py.
OP_NO_TICKET
int pip._vendor.urllib3.util.ssl_.OP_NO_TICKET = 0x4000
Definition at line 93 of file ssl_.py.
PROTOCOL_SSLv23
int pip._vendor.urllib3.util.ssl_.PROTOCOL_SSLv23 = PROTOCOL_TLS
Definition at line 68 of file ssl_.py.
PROTOCOL_TLS_CLIENT
pip._vendor.urllib3.util.ssl_.PROTOCOL_TLS_CLIENT = PROTOCOL_TLS
Definition at line 80 of file ssl_.py.
SSLContext
pip._vendor.urllib3.util.ssl_.SSLContext = None
Definition at line 19 of file ssl_.py.
SSLTransport
pip._vendor.urllib3.util.ssl_.SSLTransport = None
Definition at line 20 of file ssl_.py.