Read&Watch: django.contrib.gis.gdal.libgdal Namespace Reference
django.contrib.gis.gdal.libgdal Namespace Reference
Functions
std_call (func)
gdal_version ()
gdal_full_version ()
gdal_version_info ()
err_handler (error_class, error_number, message)
function (name, args, restype)
Variables
logger = logging.getLogger("django.contrib.gis")
lib_path = settings.GDAL_LIBRARY_PATH
lib_names = None
lgdal = CDLL(lib_path)
lwingdal = WinDLL(lib_path)
_version_info = std_call("GDALVersionInfo")
argtypes
restype
GDAL_VERSION = gdal_version_info()
CPLErrorHandler = CFUNCTYPE(None, c_int, c_int, c_char_p)
err_handler = CPLErrorHandler(err_handler)
set_error_handler = function("CPLSetErrorHandler", [CPLErrorHandler], CPLErrorHandler)
Function Documentation
err_handler()
django.contrib.gis.gdal.libgdal.err_handler (error_class, error_number, message)
Definition at line 125 of file libgdal.py.
def err_handler(error_class, error_number, message):
    logger.error("GDAL_ERROR %d: %s", error_number, message)
function()
django.contrib.gis.gdal.libgdal.function (name, args, restype)
Definition at line 132 of file libgdal.py.
def function(name, args, restype):
    func = std_call(name)
    func.argtypes = args
    func.restype = restype
    return func
References std_call().
gdal_full_version()
django.contrib.gis.gdal.libgdal.gdal_full_version ()
Definition at line 105 of file libgdal.py.
def gdal_full_version():
    "Return the full GDAL version information."
    return _version_info(b"")
References _version_info.
gdal_version()
django.contrib.gis.gdal.libgdal.gdal_version ()
Definition at line 100 of file libgdal.py.
def gdal_version():
    "Return only the GDAL version number information."
    return _version_info(b"RELEASE_NAME")
References _version_info.
Referenced by gdal_version_info().
gdal_version_info()
django.contrib.gis.gdal.libgdal.gdal_version_info ()
Definition at line 110 of file libgdal.py.
def gdal_version_info():
    ver = gdal_version()
    m = re.match(rb"^(?P<major>\d+)\.(?P<minor>\d+)(?:\.(?P<subminor>\d+))?", ver)
    if not m:
        raise GDALException('Could not parse GDAL version string "%s"' % ver)
    major, minor, subminor = m.groups()
    return (int(major), int(minor), subminor and int(subminor))
References gdal_version().
std_call()
django.contrib.gis.gdal.libgdal.std_call (func)
Return the correct STDCALL function for certain OSR routines on Win32
platforms.
Definition at line 81 of file libgdal.py.
def std_call(func):
    """
    Return the correct STDCALL function for certain OSR routines on Win32
    platforms.
    """
    if os.name == "nt":
        return lwingdal[func]
    else:
        return lgdal[func]
# #### Version-information functions. ####
# Return GDAL library version information with the given key.
Referenced by function().
Variable Documentation
_version_info
django.contrib.gis.gdal.libgdal._version_info = std_call("GDALVersionInfo") protected
Definition at line 95 of file libgdal.py.
Referenced by gdal_full_version(), and gdal_version().
argtypes
django.contrib.gis.gdal.libgdal.argtypes
Definition at line 96 of file libgdal.py.
CPLErrorHandler
django.contrib.gis.gdal.libgdal.CPLErrorHandler = CFUNCTYPE(None, c_int, c_int, c_char_p)
Definition at line 122 of file libgdal.py.
err_handler
django.contrib.gis.gdal.libgdal.err_handler = CPLErrorHandler(err_handler)
Definition at line 129 of file libgdal.py.
GDAL_VERSION
django.contrib.gis.gdal.libgdal.GDAL_VERSION = gdal_version_info()
Definition at line 119 of file libgdal.py.
lgdal
django.contrib.gis.gdal.libgdal.lgdal = CDLL(lib_path)
Definition at line 69 of file libgdal.py.
lib_names
list django.contrib.gis.gdal.libgdal.lib_names = None
Definition at line 21 of file libgdal.py.
lib_path
django.contrib.gis.gdal.libgdal.lib_path = settings.GDAL_LIBRARY_PATH
Definition at line 16 of file libgdal.py.
logger
django.contrib.gis.gdal.libgdal.logger = logging.getLogger("django.contrib.gis")
Definition at line 10 of file libgdal.py.
lwingdal
django.contrib.gis.gdal.libgdal.lwingdal = WinDLL(lib_path)
Definition at line 78 of file libgdal.py.
restype
django.contrib.gis.gdal.libgdal.restype
Definition at line 97 of file libgdal.py.
set_error_handler
django.contrib.gis.gdal.libgdal.set_error_handler = function("CPLSetErrorHandler", [CPLErrorHandler], CPLErrorHandler)
Definition at line 139 of file libgdal.py.