Read&Watch: dill.tests.test_module Namespace Reference
dill.tests.test_module Namespace Reference
Functions
test_attributes ()
test_diff_attributes ()
get_lambda (str, **kwarg)
test_module_is_none ()
Variables
tuple cached
a
pik_mod = dill.dumps(module)
module = dill.loads(pik_mod)
pycache = os.path.join(os.path.dirname(module.__file__), "__pycache__")
obj = get_lambda('lambda x: math.exp(x)', math=math)
Function Documentation
get_lambda()
dill.tests.test_module.get_lambda (str, ** kwarg)
Definition at line 71 of file test_module.py.
def get_lambda(str, **kwarg):
    return eval(str, kwarg, None)
test_attributes()
dill.tests.test_module.test_attributes ()
Definition at line 29 of file test_module.py.
def test_attributes():
   #assert hasattr(module, "a") and module.a == 1234  #FIXME: -m dill.tests
    assert module.double_add(1, 2, 3) == 2 * module.fx
# Restart, and test use_diff
Referenced by test_module_is_none().
test_diff_attributes()
dill.tests.test_module.test_diff_attributes ()
Definition at line 51 of file test_module.py.
    def test_diff_attributes():
        assert hasattr(module, "a") and module.a == 1234
        assert module.double_add(1, 2, 3) == 2 * module.fx
Referenced by test_module_is_none().
test_module_is_none()
dill.tests.test_module.test_module_is_none ()
Definition at line 76 of file test_module.py.
def test_module_is_none():
    assert obj.__module__ is None
    assert dill.copy(obj)(3) == obj(3)
References obj, test_attributes(), test_diff_attributes(), and test_module_is_none().
Referenced by test_module_is_none().
Variable Documentation
a
dill.tests.test_module.a
Definition at line 18 of file test_module.py.
cached
tuple dill.tests.test_module.cached
Initial value:
=  (module.__cached__ if hasattr(module, "__cached__")
          else module.__file__.split(".", 1)[0] + ".pyc")
Definition at line 15 of file test_module.py.
module
dill.tests.test_module.module = dill.loads(pik_mod)
Definition at line 28 of file test_module.py.
obj
dill.tests.test_module.obj = get_lambda('lambda x: math.exp(x)', math=math)
Definition at line 74 of file test_module.py.
Referenced by test_module_is_none().
pik_mod
dill.tests.test_module.pik_mod = dill.dumps(module)
Definition at line 20 of file test_module.py.
pycache
dill.tests.test_module.pycache = os.path.join(os.path.dirname(module.__file__), "__pycache__")
Definition at line 63 of file test_module.py.