Read&Watch: pip._internal.models.direct_url Namespace Reference
pip._internal.models.direct_url Namespace Reference
Classes
class ArchiveInfo
class DirectUrl
class DirectUrlValidationError
class DirInfo
class VcsInfo
Functions
Optional[T] _get (Dict[str, Any] d, Type[T] expected_type, str key, Optional[T] default=None)
T _get_required (Dict[str, Any] d, Type[T] expected_type, str key, Optional[T] default=None)
"InfoType" _exactly_one_of (Iterable[Optional["InfoType"]] infos)
Dict[str, Any] _filter_none (**Any kwargs)
Variables
T = TypeVar("T")
str DIRECT_URL_METADATA_NAME = "direct_url.json"
ENV_VAR_RE = re.compile(r"^\$\{[A-Za-z0-9-_]+\}(:\$\{[A-Za-z0-9-_]+\})?$")
InfoType = Union[ArchiveInfo, DirInfo, VcsInfo]
Detailed Description
 PEP 610
Function Documentation
_exactly_one_of()
"InfoType" pip._internal.models.direct_url._exactly_one_of (Iterable[Optional["InfoType"]] infos) protected
Definition at line 50 of file direct_url.py.
def _exactly_one_of(infos: Iterable[Optional["InfoType"]]) -> "InfoType":
    infos = [info for info in infos if info is not None]
    if not infos:
        raise DirectUrlValidationError(
            "missing one of archive_info, dir_info, vcs_info"
        )
    if len(infos) > 1:
        raise DirectUrlValidationError(
            "more than one of archive_info, dir_info, vcs_info"
        )
    assert infos[0] is not None
    return infos[0]
Referenced by pip._internal.models.direct_url.DirectUrl.from_dict().
_filter_none()
Dict[str, Any] pip._internal.models.direct_url._filter_none (**Any kwargs) protected
Make dict excluding None values.
Definition at line 64 of file direct_url.py.
def _filter_none(**kwargs: Any) -> Dict[str, Any]:
    """Make dict excluding None values."""
    return {k: v for k, v in kwargs.items() if v is not None}
@dataclass
Referenced by pip._internal.models.direct_url.ArchiveInfo._to_dict(), pip._internal.models.direct_url.DirInfo._to_dict(), pip._internal.models.direct_url.VcsInfo._to_dict(), and pip._internal.models.direct_url.DirectUrl.to_dict().
_get()
Optional[T] pip._internal.models.direct_url._get (Dict[str, Any] d, Type[T] expected_type, str key, Optional[T] default = None) protected
Get value from dictionary and verify expected type.
Definition at line 27 of file direct_url.py.
) -> Optional[T]:
    """Get value from dictionary and verify expected type."""
    if key not in d:
        return default
    value = d[key]
    if not isinstance(value, expected_type):
        raise DirectUrlValidationError(
            f"{value!r} has unexpected type for {key} (expected {expected_type})"
        )
    return value
Referenced by pip._internal.models.direct_url.ArchiveInfo._from_dict(), pip._internal.models.direct_url.VcsInfo._from_dict(), _get_required(), and pip._internal.models.direct_url.DirectUrl.from_dict().
_get_required()
T pip._internal.models.direct_url._get_required (Dict[str, Any] d, Type[T] expected_type, str key, Optional[T] default = None) protected
Definition at line 41 of file direct_url.py.
) -> T:
    value = _get(d, expected_type, key, default)
    if value is None:
        raise DirectUrlValidationError(f"{key} must have a value")
    return value
References _get().
Referenced by pip._internal.models.direct_url.DirInfo._from_dict(), pip._internal.models.direct_url.VcsInfo._from_dict(), and pip._internal.models.direct_url.DirectUrl.from_dict().
Variable Documentation
DIRECT_URL_METADATA_NAME
str pip._internal.models.direct_url.DIRECT_URL_METADATA_NAME = "direct_url.json"
Definition at line 19 of file direct_url.py.
ENV_VAR_RE
pip._internal.models.direct_url.ENV_VAR_RE = re.compile(r"^\$\{[A-Za-z0-9-_]+\}(:\$\{[A-Za-z0-9-_]+\})?$")
Definition at line 20 of file direct_url.py.
InfoType
pip._internal.models.direct_url.InfoType = Union[ArchiveInfo, DirInfo, VcsInfo]
Definition at line 155 of file direct_url.py.
T
pip._internal.models.direct_url.T = TypeVar("T")
Definition at line 17 of file direct_url.py.