Read&Watch: urllib3.util.wait Namespace Reference
urllib3.util.wait Namespace Reference
Functions
bool select_wait_for_socket (socket.socket sock, bool read=False, bool write=False, float|None timeout=None)
bool poll_wait_for_socket (socket.socket sock, bool read=False, bool write=False, float|None timeout=None)
bool _have_working_poll ()
bool wait_for_socket (socket.socket sock, bool read=False, bool write=False, float|None timeout=None)
bool wait_for_read (socket.socket sock, float|None timeout=None)
bool wait_for_write (socket.socket sock, float|None timeout=None)
Function Documentation
_have_working_poll()
bool urllib3.util.wait._have_working_poll () protected
Definition at line 82 of file wait.py.
def _have_working_poll() -> bool:
    # Apparently some systems have a select.poll that fails as soon as you try
    # to use it, either due to strange configuration or broken monkeypatching
    # from libraries like eventlet/greenlet.
    try:
        poll_obj = select.poll()
        poll_obj.poll(0)
    except (AttributeError, OSError):
        return False
    else:
        return True
Referenced by wait_for_socket().
poll_wait_for_socket()
bool urllib3.util.wait.poll_wait_for_socket (socket.socket sock, bool read = False, bool write = False, float | None timeout = None)
Definition at line 57 of file wait.py.
) -> bool:
    if not read and not write:
        raise RuntimeError("must specify at least one of read=True, write=True")
    mask = 0
    if read:
        mask |= select.POLLIN
    if write:
        mask |= select.POLLOUT
    poll_obj = select.poll()
    poll_obj.register(sock, mask)
    # For some reason, poll() takes timeout in milliseconds
    def do_poll(t: float | None) -> list[tuple[int, int]]:
        if t is not None:
            t *= 1000
        return poll_obj.poll(t)
    return bool(do_poll(timeout))
select_wait_for_socket()
bool urllib3.util.wait.select_wait_for_socket (socket.socket sock, bool read = False, bool write = False, float | None timeout = None)
Definition at line 33 of file wait.py.
) -> bool:
    if not read and not write:
        raise RuntimeError("must specify at least one of read=True, write=True")
    rcheck = []
    wcheck = []
    if read:
        rcheck.append(sock)
    if write:
        wcheck.append(sock)
    # When doing a non-blocking connect, most systems signal success by
    # marking the socket writable. Windows, though, signals success by marked
    # it as "exceptional". We paper over the difference by checking the write
    # sockets for both conditions. (The stdlib selectors module does the same
    # thing.)
    fn = partial(select.select, rcheck, wcheck, wcheck)
    rready, wready, xready = fn(timeout)
    return bool(rready or wready or xready)
wait_for_read()
bool urllib3.util.wait.wait_for_read (socket.socket sock, float | None timeout = None)
Waits for reading to be available on a given socket.
Returns True if the socket is readable, or False if the timeout expired.
Definition at line 113 of file wait.py.
def wait_for_read(sock: socket.socket, timeout: float | None = None) -> bool:
    """Waits for reading to be available on a given socket.
    Returns True if the socket is readable, or False if the timeout expired.
    """
    return wait_for_socket(sock, read=True, timeout=timeout)
References wait_for_socket().
wait_for_socket()
bool urllib3.util.wait.wait_for_socket (socket.socket sock, bool read = False, bool write = False, float | None timeout = None)
Definition at line 95 of file wait.py.
) -> bool:
    # We delay choosing which implementation to use until the first time we're
    # called. We could do it at import time, but then we might make the wrong
    # decision if someone goes wild with monkeypatching select.poll after
    # we're imported.
    global wait_for_socket
    if _have_working_poll():
        wait_for_socket = poll_wait_for_socket
    elif hasattr(select, "select"):
        wait_for_socket = select_wait_for_socket
    return wait_for_socket(sock, read, write, timeout)
References _have_working_poll(), and wait_for_socket().
Referenced by wait_for_read(), wait_for_socket(), and wait_for_write().
wait_for_write()
bool urllib3.util.wait.wait_for_write (socket.socket sock, float | None timeout = None)
Waits for writing to be available on a given socket.
Returns True if the socket is readable, or False if the timeout expired.
Definition at line 120 of file wait.py.
def wait_for_write(sock: socket.socket, timeout: float | None = None) -> bool:
    """Waits for writing to be available on a given socket.
    Returns True if the socket is readable, or False if the timeout expired.
    """
    return wait_for_socket(sock, write=True, timeout=timeout)
References wait_for_socket().