Read&Watch: django.core.checks.security.base Namespace Reference
django.core.checks.security.base Namespace Reference
Functions
_security_middleware ()
_xframe_middleware ()
check_security_middleware (app_configs, **kwargs)
check_xframe_options_middleware (app_configs, **kwargs)
check_sts (app_configs, **kwargs)
check_sts_include_subdomains (app_configs, **kwargs)
check_sts_preload (app_configs, **kwargs)
check_content_type_nosniff (app_configs, **kwargs)
check_ssl_redirect (app_configs, **kwargs)
_check_secret_key (secret_key)
check_secret_key (app_configs, **kwargs)
check_secret_key_fallbacks (app_configs, **kwargs)
check_debug (app_configs, **kwargs)
check_xframe_deny (app_configs, **kwargs)
check_allowed_hosts (app_configs, **kwargs)
check_referrer_policy (app_configs, **kwargs)
check_cross_origin_opener_policy (app_configs, **kwargs)
Variables
dict CROSS_ORIGIN_OPENER_POLICY_VALUES
dict REFERRER_POLICY_VALUES
str SECRET_KEY_INSECURE_PREFIX = "django-insecure-"
int SECRET_KEY_MIN_LENGTH = 50
int SECRET_KEY_MIN_UNIQUE_CHARACTERS = 5
tuple SECRET_KEY_WARNING_MSG
W001
W002
W004
W005
W006
W008
W009
W018
W019
W020
W021
W022
E023
E024
W025 = Warning(SECRET_KEY_WARNING_MSG, id="security.W025")
Function Documentation
_check_secret_key()
django.core.checks.security.base._check_secret_key (secret_key) protected
Definition at line 207 of file base.py.
def _check_secret_key(secret_key):
    return (
        len(set(secret_key)) >= SECRET_KEY_MIN_UNIQUE_CHARACTERS
        and len(secret_key) >= SECRET_KEY_MIN_LENGTH
        and not secret_key.startswith(SECRET_KEY_INSECURE_PREFIX)
    )
@register(Tags.security, deploy=True)
Referenced by check_secret_key(), and check_secret_key_fallbacks().
_security_middleware()
django.core.checks.security.base._security_middleware () protected
Definition at line 145 of file base.py.
def _security_middleware():
    return "django.middleware.security.SecurityMiddleware" in settings.MIDDLEWARE
Referenced by check_content_type_nosniff(), check_cross_origin_opener_policy(), check_referrer_policy(), check_security_middleware(), check_ssl_redirect(), check_sts(), check_sts_include_subdomains(), and check_sts_preload().
_xframe_middleware()
django.core.checks.security.base._xframe_middleware () protected
Definition at line 149 of file base.py.
def _xframe_middleware():
    return (
        "django.middleware.clickjacking.XFrameOptionsMiddleware" in settings.MIDDLEWARE
    )
@register(Tags.security, deploy=True)
Referenced by check_xframe_deny(), and check_xframe_options_middleware().
check_allowed_hosts()
django.core.checks.security.base.check_allowed_hosts (app_configs, ** kwargs)
Definition at line 255 of file base.py.
def check_allowed_hosts(app_configs, **kwargs):
    return [] if settings.ALLOWED_HOSTS else [W020]
@register(Tags.security, deploy=True)
check_content_type_nosniff()
django.core.checks.security.base.check_content_type_nosniff (app_configs, ** kwargs)
Definition at line 194 of file base.py.
def check_content_type_nosniff(app_configs, **kwargs):
    passed_check = (
        not _security_middleware() or settings.SECURE_CONTENT_TYPE_NOSNIFF is True
    )
    return [] if passed_check else [W006]
@register(Tags.security, deploy=True)
References _security_middleware().
check_cross_origin_opener_policy()
django.core.checks.security.base.check_cross_origin_opener_policy (app_configs, ** kwargs)
Definition at line 275 of file base.py.
def check_cross_origin_opener_policy(app_configs, **kwargs):
    if (
        _security_middleware()
        and settings.SECURE_CROSS_ORIGIN_OPENER_POLICY is not None
        and settings.SECURE_CROSS_ORIGIN_OPENER_POLICY
        not in CROSS_ORIGIN_OPENER_POLICY_VALUES
    ):
        return [E024]
    return []
References _security_middleware().
check_debug()
django.core.checks.security.base.check_debug (app_configs, ** kwargs)
Definition at line 243 of file base.py.
def check_debug(app_configs, **kwargs):
    passed_check = not settings.DEBUG
    return [] if passed_check else [W018]
@register(Tags.security, deploy=True)
check_referrer_policy()
django.core.checks.security.base.check_referrer_policy (app_configs, ** kwargs)
Definition at line 260 of file base.py.
def check_referrer_policy(app_configs, **kwargs):
    if _security_middleware():
        if settings.SECURE_REFERRER_POLICY is None:
            return [W022]
        # Support a comma-separated string or iterable of values to allow fallback.
        if isinstance(settings.SECURE_REFERRER_POLICY, str):
            values = {v.strip() for v in settings.SECURE_REFERRER_POLICY.split(",")}
        else:
            values = set(settings.SECURE_REFERRER_POLICY)
        if not values <= REFERRER_POLICY_VALUES:
            return [E023]
    return []
@register(Tags.security, deploy=True)
References _security_middleware().
check_secret_key()
django.core.checks.security.base.check_secret_key (app_configs, ** kwargs)
Definition at line 216 of file base.py.
def check_secret_key(app_configs, **kwargs):
    try:
        secret_key = settings.SECRET_KEY
    except (ImproperlyConfigured, AttributeError):
        passed_check = False
    else:
        passed_check = _check_secret_key(secret_key)
    return [] if passed_check else [W009]
@register(Tags.security, deploy=True)
References _check_secret_key().
check_secret_key_fallbacks()
django.core.checks.security.base.check_secret_key_fallbacks (app_configs, ** kwargs)
Definition at line 227 of file base.py.
def check_secret_key_fallbacks(app_configs, **kwargs):
    warnings = []
    try:
        fallbacks = settings.SECRET_KEY_FALLBACKS
    except (ImproperlyConfigured, AttributeError):
        warnings.append(Warning(W025.msg % "SECRET_KEY_FALLBACKS", id=W025.id))
    else:
        for index, key in enumerate(fallbacks):
            if not _check_secret_key(key):
                warnings.append(
                    Warning(W025.msg % f"SECRET_KEY_FALLBACKS[{index}]", id=W025.id)
                )
    return warnings
@register(Tags.security, deploy=True)
References _check_secret_key().
check_security_middleware()
django.core.checks.security.base.check_security_middleware (app_configs, ** kwargs)
Definition at line 156 of file base.py.
def check_security_middleware(app_configs, **kwargs):
    passed_check = _security_middleware()
    return [] if passed_check else [W001]
@register(Tags.security, deploy=True)
References _security_middleware().
check_ssl_redirect()
django.core.checks.security.base.check_ssl_redirect (app_configs, ** kwargs)
Definition at line 202 of file base.py.
def check_ssl_redirect(app_configs, **kwargs):
    passed_check = not _security_middleware() or settings.SECURE_SSL_REDIRECT is True
    return [] if passed_check else [W008]
References _security_middleware().
check_sts()
django.core.checks.security.base.check_sts (app_configs, ** kwargs)
Definition at line 168 of file base.py.
def check_sts(app_configs, **kwargs):
    passed_check = not _security_middleware() or settings.SECURE_HSTS_SECONDS
    return [] if passed_check else [W004]
@register(Tags.security, deploy=True)
References _security_middleware().
check_sts_include_subdomains()
django.core.checks.security.base.check_sts_include_subdomains (app_configs, ** kwargs)
Definition at line 174 of file base.py.
def check_sts_include_subdomains(app_configs, **kwargs):
    passed_check = (
        not _security_middleware()
        or not settings.SECURE_HSTS_SECONDS
        or settings.SECURE_HSTS_INCLUDE_SUBDOMAINS is True
    )
    return [] if passed_check else [W005]
@register(Tags.security, deploy=True)
References _security_middleware().
check_sts_preload()
django.core.checks.security.base.check_sts_preload (app_configs, ** kwargs)
Definition at line 184 of file base.py.
def check_sts_preload(app_configs, **kwargs):
    passed_check = (
        not _security_middleware()
        or not settings.SECURE_HSTS_SECONDS
        or settings.SECURE_HSTS_PRELOAD is True
    )
    return [] if passed_check else [W021]
@register(Tags.security, deploy=True)
References _security_middleware().
check_xframe_deny()
django.core.checks.security.base.check_xframe_deny (app_configs, ** kwargs)
Definition at line 249 of file base.py.
def check_xframe_deny(app_configs, **kwargs):
    passed_check = not _xframe_middleware() or settings.X_FRAME_OPTIONS == "DENY"
    return [] if passed_check else [W019]
@register(Tags.security, deploy=True)
References _xframe_middleware().
check_xframe_options_middleware()
django.core.checks.security.base.check_xframe_options_middleware (app_configs, ** kwargs)
Definition at line 162 of file base.py.
def check_xframe_options_middleware(app_configs, **kwargs):
    passed_check = _xframe_middleware()
    return [] if passed_check else [W002]
@register(Tags.security, deploy=True)
References _xframe_middleware().
Variable Documentation
CROSS_ORIGIN_OPENER_POLICY_VALUES
dict django.core.checks.security.base.CROSS_ORIGIN_OPENER_POLICY_VALUES
Initial value:
=  {
    "same-origin",
    "same-origin-allow-popups",
    "unsafe-none",
}
Definition at line 6 of file base.py.
E023
django.core.checks.security.base.E023
Initial value:
=  Error(
    "You have set the SECURE_REFERRER_POLICY setting to an invalid value.",
    hint="Valid values are: {}.".format(", ".join(sorted(REFERRER_POLICY_VALUES))),
    id="security.E023",
)
Definition at line 127 of file base.py.
E024
django.core.checks.security.base.E024
Initial value:
=  Error(
    "You have set the SECURE_CROSS_ORIGIN_OPENER_POLICY setting to an invalid "
    "value.",
    hint="Valid values are: {}.".format(
        ", ".join(sorted(CROSS_ORIGIN_OPENER_POLICY_VALUES)),
    ),
    id="security.E024",
)
Definition at line 133 of file base.py.
REFERRER_POLICY_VALUES
dict django.core.checks.security.base.REFERRER_POLICY_VALUES
Initial value:
=  {
    "no-referrer",
    "no-referrer-when-downgrade",
    "origin",
    "origin-when-cross-origin",
    "same-origin",
    "strict-origin",
    "strict-origin-when-cross-origin",
    "unsafe-url",
}
Definition at line 11 of file base.py.
SECRET_KEY_INSECURE_PREFIX
str django.core.checks.security.base.SECRET_KEY_INSECURE_PREFIX = "django-insecure-"
Definition at line 22 of file base.py.
SECRET_KEY_MIN_LENGTH
int django.core.checks.security.base.SECRET_KEY_MIN_LENGTH = 50
Definition at line 23 of file base.py.
SECRET_KEY_MIN_UNIQUE_CHARACTERS
int django.core.checks.security.base.SECRET_KEY_MIN_UNIQUE_CHARACTERS = 5
Definition at line 24 of file base.py.
SECRET_KEY_WARNING_MSG
tuple django.core.checks.security.base.SECRET_KEY_WARNING_MSG
Initial value:
=  (
    f"Your %s has less than {SECRET_KEY_MIN_LENGTH} characters, less than "
    f"{SECRET_KEY_MIN_UNIQUE_CHARACTERS} unique characters, or it's prefixed "
    f"with '{SECRET_KEY_INSECURE_PREFIX}' indicating that it was generated "
    f"automatically by Django. Please generate a long and random value, "
    f"otherwise many of Django's security-critical features will be "
    f"vulnerable to attack."
)
Definition at line 26 of file base.py.
W001
django.core.checks.security.base.W001
Initial value:
=  Warning(
    "You do not have 'django.middleware.security.SecurityMiddleware' "
    "in your MIDDLEWARE so the SECURE_HSTS_SECONDS, "
    "SECURE_CONTENT_TYPE_NOSNIFF, SECURE_REFERRER_POLICY, "
    "SECURE_CROSS_ORIGIN_OPENER_POLICY, and SECURE_SSL_REDIRECT settings will "
    "have no effect.",
    id="security.W001",
)
Definition at line 35 of file base.py.
W002
django.core.checks.security.base.W002
Initial value:
=  Warning(
    "You do not have "
    "'django.middleware.clickjacking.XFrameOptionsMiddleware' in your "
    "MIDDLEWARE, so your pages will not be served with an "
    "'x-frame-options' header. Unless there is a good reason for your "
    "site to be served in a frame, you should consider enabling this "
    "header to help prevent clickjacking attacks.",
    id="security.W002",
)
Definition at line 44 of file base.py.
W004
django.core.checks.security.base.W004
Initial value:
=  Warning(
    "You have not set a value for the SECURE_HSTS_SECONDS setting. "
    "If your entire site is served only over SSL, you may want to consider "
    "setting a value and enabling HTTP Strict Transport Security. "
    "Be sure to read the documentation first; enabling HSTS carelessly "
    "can cause serious, irreversible problems.",
    id="security.W004",
)
Definition at line 54 of file base.py.
W005
django.core.checks.security.base.W005
Initial value:
=  Warning(
    "You have not set the SECURE_HSTS_INCLUDE_SUBDOMAINS setting to True. "
    "Without this, your site is potentially vulnerable to attack "
    "via an insecure connection to a subdomain. Only set this to True if "
    "you are certain that all subdomains of your domain should be served "
    "exclusively via SSL.",
    id="security.W005",
)
Definition at line 63 of file base.py.
W006
django.core.checks.security.base.W006
Initial value:
=  Warning(
    "Your SECURE_CONTENT_TYPE_NOSNIFF setting is not set to True, "
    "so your pages will not be served with an "
    "'X-Content-Type-Options: nosniff' header. "
    "You should consider enabling this header to prevent the "
    "browser from identifying content types incorrectly.",
    id="security.W006",
)
Definition at line 72 of file base.py.
W008
django.core.checks.security.base.W008
Initial value:
=  Warning(
    "Your SECURE_SSL_REDIRECT setting is not set to True. "
    "Unless your site should be available over both SSL and non-SSL "
    "connections, you may want to either set this setting True "
    "or configure a load balancer or reverse-proxy server "
    "to redirect all connections to HTTPS.",
    id="security.W008",
)
Definition at line 81 of file base.py.
W009
django.core.checks.security.base.W009
Initial value:
=  Warning(
    SECRET_KEY_WARNING_MSG % "SECRET_KEY",
    id="security.W009",
)
Definition at line 90 of file base.py.
W018
django.core.checks.security.base.W018
Initial value:
=  Warning(
    "You should not have DEBUG set to True in deployment.",
    id="security.W018",
)
Definition at line 95 of file base.py.
W019
django.core.checks.security.base.W019
Initial value:
=  Warning(
    "You have "
    "'django.middleware.clickjacking.XFrameOptionsMiddleware' in your "
    "MIDDLEWARE, but X_FRAME_OPTIONS is not set to 'DENY'. "
    "Unless there is a good reason for your site to serve other parts of "
    "itself in a frame, you should change it to 'DENY'.",
    id="security.W019",
)
Definition at line 100 of file base.py.
W020
django.core.checks.security.base.W020
Initial value:
=  Warning(
    "ALLOWED_HOSTS must not be empty in deployment.",
    id="security.W020",
)
Definition at line 109 of file base.py.
W021
django.core.checks.security.base.W021
Initial value:
=  Warning(
    "You have not set the SECURE_HSTS_PRELOAD setting to True. Without this, "
    "your site cannot be submitted to the browser preload list.",
    id="security.W021",
)
Definition at line 114 of file base.py.
W022
django.core.checks.security.base.W022
Initial value:
=  Warning(
    "You have not set the SECURE_REFERRER_POLICY setting. Without this, your "
    "site will not send a Referrer-Policy header. You should consider "
    "enabling this header to protect user privacy.",
    id="security.W022",
)
Definition at line 120 of file base.py.
W025
django.core.checks.security.base.W025 = Warning(SECRET_KEY_WARNING_MSG, id="security.W025")
Definition at line 142 of file base.py.