Read&Watch: django.contrib.messages.api Namespace Reference
django.contrib.messages.api Namespace Reference
Classes
class MessageFailure
Functions
add_message (request, level, message, extra_tags="", fail_silently=False)
get_messages (request)
get_level (request)
set_level (request, level)
debug (request, message, extra_tags="", fail_silently=False)
info (request, message, extra_tags="", fail_silently=False)
success (request, message, extra_tags="", fail_silently=False)
warning (request, message, extra_tags="", fail_silently=False)
error (request, message, extra_tags="", fail_silently=False)
Function Documentation
add_message()
django.contrib.messages.api.add_message (request, level, message, extra_tags = "", fail_silently = False)
Attempt to add a message to the request using the 'messages' app.
Definition at line 22 of file api.py.
def add_message(request, level, message, extra_tags="", fail_silently=False):
    """
    Attempt to add a message to the request using the 'messages' app.
    """
    try:
        messages = request._messages
    except AttributeError:
        if not hasattr(request, "META"):
            raise TypeError(
                "add_message() argument must be an HttpRequest object, not "
                "'%s'." % request.__class__.__name__
            )
        if not fail_silently:
            raise MessageFailure(
                "You cannot add messages without installing "
                "django.contrib.messages.middleware.MessageMiddleware"
            )
    else:
        return messages.add(level, message, extra_tags)
Referenced by debug(), error(), info(), success(), and warning().
debug()
django.contrib.messages.api.debug (request, message, extra_tags = "", fail_silently = False)
Add a message with the ``DEBUG`` level.
Definition at line 75 of file api.py.
def debug(request, message, extra_tags="", fail_silently=False):
    """Add a message with the ``DEBUG`` level."""
    add_message(
        request,
        constants.DEBUG,
        message,
        extra_tags=extra_tags,
        fail_silently=fail_silently,
    )
References add_message().
error()
django.contrib.messages.api.error (request, message, extra_tags = "", fail_silently = False)
Add a message with the ``ERROR`` level.
Definition at line 119 of file api.py.
def error(request, message, extra_tags="", fail_silently=False):
    """Add a message with the ``ERROR`` level."""
    add_message(
        request,
        constants.ERROR,
        message,
        extra_tags=extra_tags,
        fail_silently=fail_silently,
    )
References add_message().
get_level()
django.contrib.messages.api.get_level (request)
Return the minimum level of messages to be recorded.
The default level is the ``MESSAGE_LEVEL`` setting. If this is not found,
use the ``INFO`` level.
Definition at line 51 of file api.py.
def get_level(request):
    """
    Return the minimum level of messages to be recorded.
    The default level is the ``MESSAGE_LEVEL`` setting. If this is not found,
    use the ``INFO`` level.
    """
    storage = getattr(request, "_messages", default_storage(request))
    return storage.level
get_messages()
django.contrib.messages.api.get_messages (request)
Return the message storage on the request if it exists, otherwise return
an empty list.
Definition at line 43 of file api.py.
def get_messages(request):
    """
    Return the message storage on the request if it exists, otherwise return
    an empty list.
    """
    return getattr(request, "_messages", [])
Referenced by django.contrib.messages.test.MessagesTestMixin.assertMessages(), and django.contrib.messages.context_processors.messages().
info()
django.contrib.messages.api.info (request, message, extra_tags = "", fail_silently = False)
Add a message with the ``INFO`` level.
Definition at line 86 of file api.py.
def info(request, message, extra_tags="", fail_silently=False):
    """Add a message with the ``INFO`` level."""
    add_message(
        request,
        constants.INFO,
        message,
        extra_tags=extra_tags,
        fail_silently=fail_silently,
    )
References add_message().
set_level()
django.contrib.messages.api.set_level (request, level)
Set the minimum level of messages to be recorded, and return ``True`` if
the level was recorded successfully.
If set to ``None``, use the default level (see the get_level() function).
Definition at line 62 of file api.py.
def set_level(request, level):
    """
    Set the minimum level of messages to be recorded, and return ``True`` if
    the level was recorded successfully.
    If set to ``None``, use the default level (see the get_level() function).
    """
    if not hasattr(request, "_messages"):
        return False
    request._messages.level = level
    return True
success()
django.contrib.messages.api.success (request, message, extra_tags = "", fail_silently = False)
Add a message with the ``SUCCESS`` level.
Definition at line 97 of file api.py.
def success(request, message, extra_tags="", fail_silently=False):
    """Add a message with the ``SUCCESS`` level."""
    add_message(
        request,
        constants.SUCCESS,
        message,
        extra_tags=extra_tags,
        fail_silently=fail_silently,
    )
References add_message().
warning()
django.contrib.messages.api.warning (request, message, extra_tags = "", fail_silently = False)
Add a message with the ``WARNING`` level.
Definition at line 108 of file api.py.
def warning(request, message, extra_tags="", fail_silently=False):
    """Add a message with the ``WARNING`` level."""
    add_message(
        request,
        constants.WARNING,
        message,
        extra_tags=extra_tags,
        fail_silently=fail_silently,
    )
References add_message().