Read&Watch: tomlkit.items Namespace Reference
tomlkit.items Namespace Reference
Classes
class _ArrayItemGroup
class AbstractTable
class AoT
class Array
class Bool
class BoolType
class Comment
class Date
class DateTime
class DottedKey
class Float
class InlineTable
class Integer
class Item
class Key
class KeyType
class Null
class SingleKey
class String
class StringType
class Table
class Time
class Trivia
class Whitespace
Functions
Bool item (bool value, Item|None _parent=..., bool _sort_keys=...)
Integer item (int value, Item|None _parent=..., bool _sort_keys=...)
Float item (float value, Item|None _parent=..., bool _sort_keys=...)
String item (str value, Item|None _parent=..., bool _sort_keys=...)
DateTime item (datetime value, Item|None _parent=..., bool _sort_keys=...)
Date item (date value, Item|None _parent=..., bool _sort_keys=...)
Time item (time value, Item|None _parent=..., bool _sort_keys=...)
AoT item (Sequence[dict] value, Item|None _parent=..., bool _sort_keys=...)
Array item (Sequence value, Item|None _parent=..., bool _sort_keys=...)
InlineTable item (dict value, Array _parent=..., bool _sort_keys=...)
Table item (dict value, Item|None _parent=..., bool _sort_keys=...)
ItemT item (ItemT value, Item|None _parent=..., bool _sort_keys=...)
Item item (Any value, Item|None _parent=None, bool _sort_keys=False)
Variables
ItemT = TypeVar("ItemT", bound="Item")
Encoder = Callable[[Any], "Item"]
list CUSTOM_ENCODERS = []
AT = TypeVar("AT", bound="AbstractTable")
Function Documentation
item() [1/13]
Item tomlkit.items.item (Any value, Item | None _parent = None, bool _sort_keys = False)
Create a TOML item from a Python object.
:Example:
>>> item(42)
42
>>> item([1, 2, 3])
[1, 2, 3]
>>> item({'a': 1, 'b': 2})
a = 1
b = 2
Definition at line 104 of file items.py.
def item(value: Any, _parent: Item | None = None, _sort_keys: bool = False) -> Item:
    """Create a TOML item from a Python object.
    :Example:
    >>> item(42)
    42
    >>> item([1, 2, 3])
    [1, 2, 3]
    >>> item({'a': 1, 'b': 2})
    a = 1
    b = 2
    """
    from tomlkit.container import Container
    if isinstance(value, Item):
        return value
    if isinstance(value, bool):
        return Bool(value, Trivia())
    elif isinstance(value, int):
        return Integer(value, Trivia(), str(value))
    elif isinstance(value, float):
        return Float(value, Trivia(), str(value))
    elif isinstance(value, dict):
        table_constructor = (
            InlineTable if isinstance(_parent, (Array, InlineTable)) else Table
        )
        val = table_constructor(Container(), Trivia(), False)
        for k, v in sorted(
            value.items(),
            key=lambda i: (isinstance(i[1], dict), i[0]) if _sort_keys else 1,
        ):
            val[k] = item(v, _parent=val, _sort_keys=_sort_keys)
        return val
    elif isinstance(value, (list, tuple)):
        if (
            value
            and all(isinstance(v, dict) for v in value)
            and (_parent is None or isinstance(_parent, Table))
        ):
            a = AoT([])
            table_constructor = Table
        else:
            a = Array([], Trivia())
            table_constructor = InlineTable
        for v in value:
            if isinstance(v, dict):
                table = table_constructor(Container(), Trivia(), True)
                for k, _v in sorted(
                    v.items(),
                    key=lambda i: (isinstance(i[1], dict), i[0] if _sort_keys else 1),
                ):
                    i = item(_v, _parent=table, _sort_keys=_sort_keys)
                    if isinstance(table, InlineTable):
                        i.trivia.trail = ""
                    table[k] = i
                v = table
            a.append(v)
        return a
    elif isinstance(value, str):
        return String.from_raw(value)
    elif isinstance(value, datetime):
        return DateTime(
            value.year,
            value.month,
            value.day,
            value.hour,
            value.minute,
            value.second,
            value.microsecond,
            value.tzinfo,
            Trivia(),
            value.isoformat().replace("+00:00", "Z"),
        )
    elif isinstance(value, date):
        return Date(value.year, value.month, value.day, Trivia(), value.isoformat())
    elif isinstance(value, time):
        return Time(
            value.hour,
            value.minute,
            value.second,
            value.microsecond,
            value.tzinfo,
            Trivia(),
            value.isoformat(),
        )
    else:
        for encoder in CUSTOM_ENCODERS:
            try:
                rv = encoder(value)
            except ConvertError:
                pass
            else:
                if not isinstance(rv, Item):
                    raise ConvertError(
                        f"Custom encoder is expected to return an instance of Item, got {type(rv)}"
                    )
                return rv
    raise ConvertError(f"Unable to convert an object of {type(value)} to a TOML item")
References item().
item() [2/13]
Bool tomlkit.items.item (bool value, Item | None _parent = ..., bool _sort_keys = ...)
Definition at line 51 of file items.py.
def item(value: bool, _parent: Item | None = ..., _sort_keys: bool = ...) -> Bool: ...
@overload
Referenced by tomlkit.items.AbstractTable.__setitem__(), tomlkit.items.Array.__setitem__(), tomlkit.items.Array.add_line(), tomlkit.items.InlineTable.append(), tomlkit.items.Table.append(), tomlkit.items.AoT.insert(), tomlkit.items.Array.insert(), item(), and tomlkit.items.Table.raw_append().
item() [3/13]
Date tomlkit.items.item (date value, Item | None _parent = ..., bool _sort_keys = ...)
Definition at line 73 of file items.py.
def item(value: date, _parent: Item | None = ..., _sort_keys: bool = ...) -> Date: ...
@overload
item() [4/13]
DateTime tomlkit.items.item (datetime value, Item | None _parent = ..., bool _sort_keys = ...)
Definition at line 67 of file items.py.
) -> DateTime: ...
@overload
item() [5/13]
InlineTable tomlkit.items.item (dict value, Array _parent = ..., bool _sort_keys = ...)
Definition at line 93 of file items.py.
def item(value: dict, _parent: Array = ..., _sort_keys: bool = ...) -> InlineTable: ...
@overload
item() [6/13]
Table tomlkit.items.item (dict value, Item | None _parent = ..., bool _sort_keys = ...)
Definition at line 97 of file items.py.
def item(value: dict, _parent: Item | None = ..., _sort_keys: bool = ...) -> Table: ...
@overload
item() [7/13]
Float tomlkit.items.item (float value, Item | None _parent = ..., bool _sort_keys = ...)
Definition at line 59 of file items.py.
def item(value: float, _parent: Item | None = ..., _sort_keys: bool = ...) -> Float: ...
@overload
item() [8/13]
Integer tomlkit.items.item (int value, Item | None _parent = ..., bool _sort_keys = ...)
Definition at line 55 of file items.py.
def item(value: int, _parent: Item | None = ..., _sort_keys: bool = ...) -> Integer: ...
@overload
item() [9/13]
ItemT tomlkit.items.item (ItemT value, Item | None _parent = ..., bool _sort_keys = ...)
Definition at line 101 of file items.py.
def item(value: ItemT, _parent: Item | None = ..., _sort_keys: bool = ...) -> ItemT: ...
item() [10/13]
Array tomlkit.items.item (Sequence value, Item | None _parent = ..., bool _sort_keys = ...)
Definition at line 87 of file items.py.
) -> Array: ...
@overload
item() [11/13]
AoT tomlkit.items.item (Sequence[dict] value, Item | None _parent = ..., bool _sort_keys = ...)
Definition at line 81 of file items.py.
) -> AoT: ...
@overload
item() [12/13]
String tomlkit.items.item (str value, Item | None _parent = ..., bool _sort_keys = ...)
Definition at line 63 of file items.py.
def item(value: str, _parent: Item | None = ..., _sort_keys: bool = ...) -> String: ...
@overload
item() [13/13]
Time tomlkit.items.item (time value, Item | None _parent = ..., bool _sort_keys = ...)
Definition at line 77 of file items.py.
def item(value: time, _parent: Item | None = ..., _sort_keys: bool = ...) -> Time: ...
@overload
Variable Documentation
AT
tomlkit.items.AT = TypeVar("AT", bound="AbstractTable")
Definition at line 47 of file items.py.
CUSTOM_ENCODERS
list tomlkit.items.CUSTOM_ENCODERS = []
Definition at line 46 of file items.py.
Encoder
tomlkit.items.Encoder = Callable[[Any], "Item"]
Definition at line 45 of file items.py.
ItemT
tomlkit.items.ItemT = TypeVar("ItemT", bound="Item")
Definition at line 44 of file items.py.