Read&Watch: pip._vendor.pygments.formatters Namespace Reference
pip._vendor.pygments.formatters Namespace Reference
Namespaces
namespace _mapping
namespace bbcode
namespace groff
namespace html
namespace img
namespace irc
namespace latex
namespace other
namespace pangomarkup
namespace rtf
namespace svg
namespace terminal
namespace terminal256
Classes
class _automodule
Functions
_fn_matches (fn, glob)
_load_formatters (module_name)
get_all_formatters ()
find_formatter_class (alias)
get_formatter_by_name (_alias, **options)
load_formatter_from_file (filename, formattername="CustomFormatter", **options)
get_formatter_for_filename (fn, **options)
Variables
dict _formatter_cache = {}
dict _pattern_cache = {}
oldmod = sys.modules[__name__]
newmod = _automodule(__name__)
aliases
filenames
Detailed Description
    pygments.formatters
    ~~~~~~~~~~~~~~~~~~~
    Pygments formatters.
    :copyright: Copyright 2006-2024 by the Pygments team, see AUTHORS.
    :license: BSD, see LICENSE for details.
Function Documentation
_fn_matches()
pip._vendor.pygments.formatters._fn_matches (fn, glob) protected
Return whether the supplied file name fn matches pattern filename.
Definition at line 28 of file __init__.py.
def _fn_matches(fn, glob):
    """Return whether the supplied file name fn matches pattern filename."""
    if glob not in _pattern_cache:
        pattern = _pattern_cache[glob] = re.compile(fnmatch.translate(glob))
        return pattern.match(fn)
    return _pattern_cache[glob].match(fn)
Referenced by get_formatter_for_filename().
_load_formatters()
pip._vendor.pygments.formatters._load_formatters (module_name) protected
Load a formatter (and all others in the module too).
Definition at line 36 of file __init__.py.
def _load_formatters(module_name):
    """Load a formatter (and all others in the module too)."""
    mod = __import__(module_name, None, None, ['__all__'])
    for formatter_name in mod.__all__:
        cls = getattr(mod, formatter_name)
        _formatter_cache[cls.name] = cls
Referenced by pip._vendor.pygments.formatters._automodule.__getattr__(), find_formatter_class(), get_all_formatters(), and get_formatter_for_filename().
find_formatter_class()
pip._vendor.pygments.formatters.find_formatter_class (alias)
Lookup a formatter by alias.
Returns None if not found.
Definition at line 55 of file __init__.py.
def find_formatter_class(alias):
    """Lookup a formatter by alias.
    Returns None if not found.
    """
    for module_name, name, aliases, _, _ in FORMATTERS.values():
        if alias in aliases:
            if name not in _formatter_cache:
                _load_formatters(module_name)
            return _formatter_cache[name]
    for _, cls in find_plugin_formatters():
        if alias in cls.aliases:
            return cls
References _load_formatters().
Referenced by get_formatter_by_name().
get_all_formatters()
pip._vendor.pygments.formatters.get_all_formatters ()
Return a generator for all formatter classes.
Definition at line 44 of file __init__.py.
def get_all_formatters():
    """Return a generator for all formatter classes."""
    # NB: this returns formatter classes, not info like get_all_lexers().
    for info in FORMATTERS.values():
        if info[1] not in _formatter_cache:
            _load_formatters(info[0])
        yield _formatter_cache[info[1]]
    for _, formatter in find_plugin_formatters():
        yield formatter
References _load_formatters().
get_formatter_by_name()
pip._vendor.pygments.formatters.get_formatter_by_name (_alias, ** options)
Return an instance of a :class:`.Formatter` subclass that has `alias` in its
aliases list. The formatter is given the `options` at its instantiation.
Will raise :exc:`pygments.util.ClassNotFound` if no formatter with that
alias is found.
Definition at line 70 of file __init__.py.
def get_formatter_by_name(_alias, **options):
    """
    Return an instance of a :class:`.Formatter` subclass that has `alias` in its
    aliases list. The formatter is given the `options` at its instantiation.
    Will raise :exc:`pygments.util.ClassNotFound` if no formatter with that
    alias is found.
    """
    cls = find_formatter_class(_alias)
    if cls is None:
        raise ClassNotFound(f"no formatter found for name {_alias!r}")
    return cls(**options)
References find_formatter_class().
get_formatter_for_filename()
pip._vendor.pygments.formatters.get_formatter_for_filename (fn, ** options)
Return a :class:`.Formatter` subclass instance that has a filename pattern
matching `fn`. The formatter is given the `options` at its instantiation.
Will raise :exc:`pygments.util.ClassNotFound` if no formatter for that filename
is found.
Definition at line 118 of file __init__.py.
def get_formatter_for_filename(fn, **options):
    """
    Return a :class:`.Formatter` subclass instance that has a filename pattern
    matching `fn`. The formatter is given the `options` at its instantiation.
    Will raise :exc:`pygments.util.ClassNotFound` if no formatter for that filename
    is found.
    """
    fn = basename(fn)
    for modname, name, _, filenames, _ in FORMATTERS.values():
        for filename in filenames:
            if _fn_matches(fn, filename):
                if name not in _formatter_cache:
                    _load_formatters(modname)
                return _formatter_cache[name](**options)
    for _name, cls in find_plugin_formatters():
        for filename in cls.filenames:
            if _fn_matches(fn, filename):
                return cls(**options)
    raise ClassNotFound(f"no formatter found for file name {fn!r}")
References _fn_matches(), and _load_formatters().
load_formatter_from_file()
pip._vendor.pygments.formatters.load_formatter_from_file (filename, formattername = "CustomFormatter", ** options)
Return a `Formatter` subclass instance loaded from the provided file, relative
to the current directory.
The file is expected to contain a Formatter class named ``formattername``
(by default, CustomFormatter). Users should be very careful with the input, because
this method is equivalent to running ``eval()`` on the input file. The formatter is
given the `options` at its instantiation.
:exc:`pygments.util.ClassNotFound` is raised if there are any errors loading
the formatter.
.. versionadded:: 2.2
Definition at line 84 of file __init__.py.
def load_formatter_from_file(filename, formattername="CustomFormatter", **options):
    """
    Return a `Formatter` subclass instance loaded from the provided file, relative
    to the current directory.
    The file is expected to contain a Formatter class named ``formattername``
    (by default, CustomFormatter). Users should be very careful with the input, because
    this method is equivalent to running ``eval()`` on the input file. The formatter is
    given the `options` at its instantiation.
    :exc:`pygments.util.ClassNotFound` is raised if there are any errors loading
    the formatter.
    .. versionadded:: 2.2
    """
    try:
        # This empty dict will contain the namespace for the exec'd file
        custom_namespace = {}
        with open(filename, 'rb') as f:
            exec(f.read(), custom_namespace)
        # Retrieve the class `formattername` from that namespace
        if formattername not in custom_namespace:
            raise ClassNotFound(f'no valid {formattername} class found in {filename}')
        formatter_class = custom_namespace[formattername]
        # And finally instantiate it with the options
        return formatter_class(**options)
    except OSError as err:
        raise ClassNotFound(f'cannot read {filename}: {err}')
    except ClassNotFound:
        raise
    except Exception as err:
        raise ClassNotFound(f'error when loading custom formatter: {err}')
Variable Documentation
_formatter_cache
dict pip._vendor.pygments.formatters._formatter_cache = {} protected
Definition at line 24 of file __init__.py.
_pattern_cache
dict pip._vendor.pygments.formatters._pattern_cache = {} protected
Definition at line 25 of file __init__.py.
aliases
pip._vendor.pygments.formatters.aliases
Definition at line 66 of file __init__.py.
filenames
pip._vendor.pygments.formatters.filenames
Definition at line 134 of file __init__.py.
newmod
pip._vendor.pygments.formatters.newmod = _automodule(__name__)
Definition at line 154 of file __init__.py.
oldmod
pip._vendor.pygments.formatters.oldmod = sys.modules[__name__]
Definition at line 153 of file __init__.py.