Read&Watch: pylint.extensions._check_docs_utils Namespace Reference
pylint.extensions._check_docs_utils Namespace Reference
Classes
class Docstring
class EpytextDocstring
class GoogleDocstring
class NumpyDocstring
class SphinxDocstring
Functions
int space_indentation (str s)
str|None get_setters_property_name (nodes.FunctionDef node)
nodes.FunctionDef|None get_setters_property (nodes.FunctionDef node)
bool returns_something (nodes.Return return_node)
nodes.NodeNG|UninferableBase|None _get_raise_target (nodes.NodeNG node)
list[str] _split_multiple_exc_types (str target)
set[nodes.ClassDef] possible_exc_types (nodes.NodeNG node)
bool _is_ellipsis (nodes.NodeNG node)
Iterable[nodes.NodeNG|None] _merge_annotations (Iterable[nodes.NodeNG] annotations, Iterable[nodes.NodeNG] comment_annotations)
list[nodes.NodeNG] _annotations_list (nodes.Arguments args_node)
set[str] args_with_annotation (nodes.Arguments args_node)
Docstring docstringify (nodes.Const|None docstring, str default_type="default")
Variables
dict DOCSTRING_TYPES
Detailed Description
Utility methods for docstring checking.
Function Documentation
_annotations_list()
list[nodes.NodeNG] pylint.extensions._check_docs_utils._annotations_list (nodes.Arguments args_node) protected
Get a merged list of annotations.
The annotations can come from:
* Real type annotations.
* A type comment on the function.
* A type common on the individual argument.
:param args_node: The node to get the annotations for.
:returns: The annotations.
Definition at line 180 of file _check_docs_utils.py.
def _annotations_list(args_node: nodes.Arguments) -> list[nodes.NodeNG]:
    """Get a merged list of annotations.
    The annotations can come from:
    * Real type annotations.
    * A type comment on the function.
    * A type common on the individual argument.
    :param args_node: The node to get the annotations for.
    :returns: The annotations.
    """
    plain_annotations = args_node.annotations or ()
    func_comment_annotations = args_node.parent.type_comment_args or ()
    comment_annotations = args_node.type_comment_posonlyargs
    comment_annotations += args_node.type_comment_args or []
    comment_annotations += args_node.type_comment_kwonlyargs
    return list(
        _merge_annotations(
            plain_annotations,
            _merge_annotations(func_comment_annotations, comment_annotations),
        )
    )
References _merge_annotations().
Referenced by args_with_annotation().
_get_raise_target()
nodes.NodeNG | UninferableBase | None pylint.extensions._check_docs_utils._get_raise_target (nodes.NodeNG node) protected
Definition at line 94 of file _check_docs_utils.py.
def _get_raise_target(node: nodes.NodeNG) -> nodes.NodeNG | UninferableBase | None:
    if isinstance(node.exc, nodes.Call):
        func = node.exc.func
        if isinstance(func, (nodes.Name, nodes.Attribute)):
            return utils.safe_infer(func)
    return None
Referenced by possible_exc_types().
_is_ellipsis()
bool pylint.extensions._check_docs_utils._is_ellipsis (nodes.NodeNG node) protected
Definition at line 164 of file _check_docs_utils.py.
def _is_ellipsis(node: nodes.NodeNG) -> bool:
    return isinstance(node, nodes.Const) and node.value == Ellipsis
Referenced by _merge_annotations().
_merge_annotations()
Iterable[nodes.NodeNG | None] pylint.extensions._check_docs_utils._merge_annotations (Iterable[nodes.NodeNG] annotations, Iterable[nodes.NodeNG] comment_annotations) protected
Definition at line 168 of file _check_docs_utils.py.
) -> Iterable[nodes.NodeNG | None]:
    for ann, comment_ann in itertools.zip_longest(annotations, comment_annotations):
        if ann and not _is_ellipsis(ann):
            yield ann
        elif comment_ann and not _is_ellipsis(comment_ann):
            yield comment_ann
        else:
            yield None
References _is_ellipsis().
Referenced by _annotations_list().
_split_multiple_exc_types()
list[str] pylint.extensions._check_docs_utils._split_multiple_exc_types (str target) protected
Definition at line 102 of file _check_docs_utils.py.
def _split_multiple_exc_types(target: str) -> list[str]:
    delimiters = r"(\s*,(?:\s*or\s)?\s*|\s+or\s+)"
    return re.split(delimiters, target)
Referenced by pylint.extensions._check_docs_utils.GoogleDocstring.exceptions(), and pylint.extensions._check_docs_utils.SphinxDocstring.exceptions().
args_with_annotation()
set[str] pylint.extensions._check_docs_utils.args_with_annotation (nodes.Arguments args_node)
Definition at line 205 of file _check_docs_utils.py.
def args_with_annotation(args_node: nodes.Arguments) -> set[str]:
    result = set()
    annotations = _annotations_list(args_node)
    annotation_offset = 0
    if args_node.posonlyargs:
        posonlyargs_annotations = args_node.posonlyargs_annotations
        if not any(args_node.posonlyargs_annotations):
            num_args = len(args_node.posonlyargs)
            posonlyargs_annotations = annotations[
                annotation_offset : annotation_offset + num_args
            ]
            annotation_offset += num_args
        for arg, annotation in zip(args_node.posonlyargs, posonlyargs_annotations):
            if annotation:
                result.add(arg.name)
    if args_node.args:
        num_args = len(args_node.args)
        for arg, annotation in zip(
            args_node.args,
            annotations[annotation_offset : annotation_offset + num_args],
        ):
            if annotation:
                result.add(arg.name)
        annotation_offset += num_args
    if args_node.vararg:
        if args_node.varargannotation:
            result.add(args_node.vararg)
        elif len(annotations) > annotation_offset and annotations[annotation_offset]:
            result.add(args_node.vararg)
            annotation_offset += 1
    if args_node.kwonlyargs:
        kwonlyargs_annotations = args_node.kwonlyargs_annotations
        if not any(args_node.kwonlyargs_annotations):
            num_args = len(args_node.kwonlyargs)
            kwonlyargs_annotations = annotations[
                annotation_offset : annotation_offset + num_args
            ]
            annotation_offset += num_args
        for arg, annotation in zip(args_node.kwonlyargs, kwonlyargs_annotations):
            if annotation:
                result.add(arg.name)
    if args_node.kwarg:
        if args_node.kwargannotation:
            result.add(args_node.kwarg)
        elif len(annotations) > annotation_offset and annotations[annotation_offset]:
            result.add(args_node.kwarg)
            annotation_offset += 1
    return result
References _annotations_list().
docstringify()
Docstring pylint.extensions._check_docs_utils.docstringify (nodes.Const | None docstring, str default_type = "default")
Definition at line 264 of file _check_docs_utils.py.
) -> Docstring:
    best_match = (0, DOCSTRING_TYPES.get(default_type, Docstring)(docstring))
    for docstring_type in (
        SphinxDocstring,
        EpytextDocstring,
        GoogleDocstring,
        NumpyDocstring,
    ):
        instance = docstring_type(docstring)
        matching_sections = instance.matching_sections()
        if matching_sections > best_match[0]:
            best_match = (matching_sections, instance)
    return best_match[1]
get_setters_property()
nodes.FunctionDef | None pylint.extensions._check_docs_utils.get_setters_property (nodes.FunctionDef node)
Get the property node for the given setter node.
:param node: The node to get the property for.
:type node: nodes.FunctionDef
:rtype: nodes.FunctionDef or None
:returns: The node relating to the property of the given setter node,
    or None if one could not be found.
Definition at line 52 of file _check_docs_utils.py.
def get_setters_property(node: nodes.FunctionDef) -> nodes.FunctionDef | None:
    """Get the property node for the given setter node.
    :param node: The node to get the property for.
    :type node: nodes.FunctionDef
    :rtype: nodes.FunctionDef or None
    :returns: The node relating to the property of the given setter node,
        or None if one could not be found.
    """
    property_ = None
    property_name = get_setters_property_name(node)
    class_node = utils.node_frame_class(node)
    if property_name and class_node:
        class_attrs: list[nodes.FunctionDef] = class_node.getattr(node.name)
        for attr in class_attrs:
            if utils.decorated_with_property(attr):
                property_ = attr
                break
    return property_
References get_setters_property_name().
get_setters_property_name()
str | None pylint.extensions._check_docs_utils.get_setters_property_name (nodes.FunctionDef node)
Get the name of the property that the given node is a setter for.
:param node: The node to get the property name for.
:type node: str
:rtype: str or None
:returns: The name of the property that the node is a setter for,
    or None if one could not be found.
Definition at line 31 of file _check_docs_utils.py.
def get_setters_property_name(node: nodes.FunctionDef) -> str | None:
    """Get the name of the property that the given node is a setter for.
    :param node: The node to get the property name for.
    :type node: str
    :rtype: str or None
    :returns: The name of the property that the node is a setter for,
        or None if one could not be found.
    """
    decorators = node.decorators.nodes if node.decorators else []
    for decorator in decorators:
        if (
            isinstance(decorator, nodes.Attribute)
            and decorator.attrname == "setter"
            and isinstance(decorator.expr, nodes.Name)
        ):
            return decorator.expr.name  # type: ignore[no-any-return]
    return None
Referenced by get_setters_property().
possible_exc_types()
set[nodes.ClassDef] pylint.extensions._check_docs_utils.possible_exc_types (nodes.NodeNG node)
Gets all the possible raised exception types for the given raise node.
.. note::
    Caught exception types are ignored.
:param node: The raise node to find exception types for.
:returns: A list of exception types possibly raised by :param:`node`.
Definition at line 107 of file _check_docs_utils.py.
def possible_exc_types(node: nodes.NodeNG) -> set[nodes.ClassDef]:
    """Gets all the possible raised exception types for the given raise node.
    .. note::
        Caught exception types are ignored.
    :param node: The raise node to find exception types for.
    :returns: A list of exception types possibly raised by :param:`node`.
    """
    exceptions = []
    if isinstance(node.exc, nodes.Name):
        inferred = utils.safe_infer(node.exc)
        if inferred:
            exceptions = [inferred]
    elif node.exc is None:
        handler = node.parent
        while handler and not isinstance(handler, nodes.ExceptHandler):
            handler = handler.parent
        if handler and handler.type:
            try:
                for exception in astroid.unpack_infer(handler.type):
                    if not isinstance(exception, UninferableBase):
                        exceptions.append(exception)
            except astroid.InferenceError:
                pass
    else:
        target = _get_raise_target(node)
        if isinstance(target, nodes.ClassDef):
            exceptions = [target]
        elif isinstance(target, nodes.FunctionDef):
            for ret in target.nodes_of_class(nodes.Return):
                if ret.value is None:
                    continue
                if ret.frame() != target:
                    # return from inner function - ignore it
                    continue
                val = utils.safe_infer(ret.value)
                if val and utils.inherit_from_std_ex(val):
                    if isinstance(val, nodes.ClassDef):
                        exceptions.append(val)
                    elif isinstance(val, astroid.Instance):
                        exceptions.append(val.getattr("__class__")[0])
    try:
        return {
            exc
            for exc in exceptions
            if not utils.node_ignores_exception(node, exc.name)
        }
    except astroid.InferenceError:
        return set()
References _get_raise_target().
returns_something()
bool pylint.extensions._check_docs_utils.returns_something (nodes.Return return_node)
Check if a return node returns a value other than None.
:param return_node: The return node to check.
:type return_node: astroid.Return
:rtype: bool
:return: True if the return node returns a value other than None,
    False otherwise.
Definition at line 76 of file _check_docs_utils.py.
def returns_something(return_node: nodes.Return) -> bool:
    """Check if a return node returns a value other than None.
    :param return_node: The return node to check.
    :type return_node: astroid.Return
    :rtype: bool
    :return: True if the return node returns a value other than None,
        False otherwise.
    """
    returns = return_node.value
    if returns is None:
        return False
    return not (isinstance(returns, nodes.Const) and returns.value is None)
space_indentation()
int pylint.extensions._check_docs_utils.space_indentation (str s)
The number of leading spaces in a string.
:param str s: input string
:rtype: int
:return: number of leading spaces
Definition at line 20 of file _check_docs_utils.py.
def space_indentation(s: str) -> int:
    """The number of leading spaces in a string.
    :param str s: input string
    :rtype: int
    :return: number of leading spaces
    """
    return len(s) - len(s.lstrip(" "))
Referenced by pylint.extensions._check_docs_utils.GoogleDocstring._parse_section().
Variable Documentation
DOCSTRING_TYPES
dict pylint.extensions._check_docs_utils.DOCSTRING_TYPES
Initial value:
=  {
    "sphinx": SphinxDocstring,
    "epytext": EpytextDocstring,
    "google": GoogleDocstring,
    "numpy": NumpyDocstring,
    "default": Docstring,
}
Definition at line 936 of file _check_docs_utils.py.