Read&Watch: isort.settings Namespace Reference
isort.settings Namespace Reference
Classes
class _Config
class Config
Functions
Union[Callable[[str], Any], Type[Any]] _get_str_to_type_converter (str setting_name)
List[str] _as_list (str value)
Set[str] _abspaths (str cwd, Iterable[str] values)
Tuple[str, Dict[str, Any]] _find_config (str path)
Trie find_all_configs (str path)
Dict[str, Any] _get_config_data (str file_path, Tuple[str,...] sections)
bool _as_bool (str value)
Variables
_SHEBANG_RE = re.compile(rb"^#!.*\bpython[23w]?\b")
CYTHON_EXTENSIONS = frozenset({"pyx", "pxd"})
SUPPORTED_EXTENSIONS = frozenset({"py", "pyi", *CYTHON_EXTENSIONS})
BLOCKED_EXTENSIONS = frozenset({"pex"})
tuple FILE_SKIP_COMMENTS
int MAX_CONFIG_SEARCH_DEPTH = 25
tuple STOP_CONFIG_SEARCH_ON_DIRS = (".git", ".hg")
Tuple VALID_PY_TARGETS
tuple CONFIG_SOURCES
FrozenSet DEFAULT_SKIP
dict CONFIG_SECTIONS
tuple FALLBACK_CONFIG_SECTIONS = ("isort", "tool:isort", "tool.isort")
str IMPORT_HEADING_PREFIX = "import_heading_"
str IMPORT_FOOTER_PREFIX = "import_footer_"
str KNOWN_PREFIX = "known_"
dict KNOWN_SECTION_MAPPING
str RUNTIME_SOURCE = "runtime"
tuple DEPRECATED_SETTINGS = ("not_skip", "keep_direct_and_as_imports")
dict _STR_BOOLEAN_MAPPING
dict _DEFAULT_SETTINGS = {**vars(_Config()), "source": "defaults"}
DEFAULT_CONFIG = Config()
Detailed Description
isort/settings.py.
Defines how the default settings for isort should be loaded
Function Documentation
_abspaths()
Set[str] isort.settings._abspaths (str cwd, Iterable[str] values) protected
Definition at line 755 of file settings.py.
def _abspaths(cwd: str, values: Iterable[str]) -> Set[str]:
    paths = {
        (
            os.path.join(cwd, value)
            if not value.startswith(os.path.sep) and value.endswith(os.path.sep)
            else value
        )
        for value in values
    }
    return paths
Referenced by _get_config_data().
_as_bool()
bool isort.settings._as_bool (str value) protected
Given a string value that represents True or False, returns the Boolean equivalent.
Heavily inspired from distutils strtobool.
Definition at line 923 of file settings.py.
def _as_bool(value: str) -> bool:
    """Given a string value that represents True or False, returns the Boolean equivalent.
    Heavily inspired from distutils strtobool.
    """
    try:
        return _STR_BOOLEAN_MAPPING[value.lower()]
    except KeyError:
        raise ValueError(f"invalid truth value {value}")
Referenced by _get_config_data().
_as_list()
List[str] isort.settings._as_list (str value) protected
Definition at line 748 of file settings.py.
def _as_list(value: str) -> List[str]:
    if isinstance(value, list):
        return [item.strip() for item in value]
    filtered = [item.strip() for item in value.replace("\n", ",").split(",") if item.strip()]
    return filtered
Referenced by _get_config_data().
_find_config()
Tuple[str, Dict[str, Any]] isort.settings._find_config (str path) protected
Definition at line 767 of file settings.py.
def _find_config(path: str) -> Tuple[str, Dict[str, Any]]:
    current_directory = path
    tries = 0
    while current_directory and tries < MAX_CONFIG_SEARCH_DEPTH:
        for config_file_name in CONFIG_SOURCES:
            potential_config_file = os.path.join(current_directory, config_file_name)
            if os.path.isfile(potential_config_file):
                config_data: Dict[str, Any]
                try:
                    config_data = _get_config_data(
                        potential_config_file, CONFIG_SECTIONS[config_file_name]
                    )
                except Exception:
                    warn(f"Failed to pull configuration information from {potential_config_file}")
                    config_data = {}
                if config_data:
                    return (current_directory, config_data)
        for stop_dir in STOP_CONFIG_SEARCH_ON_DIRS:
            if os.path.isdir(os.path.join(current_directory, stop_dir)):
                return (current_directory, {})
        new_directory = os.path.split(current_directory)[0]
        if new_directory == current_directory:
            break
        current_directory = new_directory
        tries += 1
    return (path, {})
References _get_config_data().
_get_config_data()
Dict[str, Any] isort.settings._get_config_data (str file_path, Tuple[str, ...] sections) protected
Definition at line 827 of file settings.py.
def _get_config_data(file_path: str, sections: Tuple[str, ...]) -> Dict[str, Any]:
    settings: Dict[str, Any] = {}
    if file_path.endswith(".toml"):
        with open(file_path, "rb") as bin_config_file:
            config = tomllib.load(bin_config_file)
        for section in sections:
            config_section = config
            for key in section.split("."):
                config_section = config_section.get(key, {})
            settings.update(config_section)
    else:
        with open(file_path, encoding="utf-8") as config_file:
            if file_path.endswith(".editorconfig"):
                line = "\n"
                last_position = config_file.tell()
                while line:
                    line = config_file.readline()
                    if "[" in line:
                        config_file.seek(last_position)
                        break
                    last_position = config_file.tell()
            config = configparser.ConfigParser(strict=False)
            config.read_file(config_file)
        for section in sections:
            if section.startswith("*.{") and section.endswith("}"):
                extension = section[len("*.{") : -1]
                for config_key in config.keys():
                    if (
                        config_key.startswith("*.{")
                        and config_key.endswith("}")
                        and extension
                        in map(
                            lambda text: text.strip(),
                            config_key[len("*.{") : -1].split(","),  # noqa
                        )
                    ):
                        settings.update(config.items(config_key))
            elif config.has_section(section):
                settings.update(config.items(section))
    if settings:
        settings["source"] = file_path
        if file_path.endswith(".editorconfig"):
            indent_style = settings.pop("indent_style", "").strip()
            indent_size = settings.pop("indent_size", "").strip()
            if indent_size == "tab":
                indent_size = settings.pop("tab_width", "").strip()
            if indent_style == "space":
                settings["indent"] = " " * (indent_size and int(indent_size) or 4)
            elif indent_style == "tab":
                settings["indent"] = "\t" * (indent_size and int(indent_size) or 1)
            max_line_length = settings.pop("max_line_length", "").strip()
            if max_line_length and (max_line_length == "off" or max_line_length.isdigit()):
                settings["line_length"] = (
                    float("inf") if max_line_length == "off" else int(max_line_length)
                )
            settings = {
                key: value
                for key, value in settings.items()
                if key in _DEFAULT_SETTINGS.keys() or key.startswith(KNOWN_PREFIX)
            }
        for key, value in settings.items():
            existing_value_type = _get_str_to_type_converter(key)
            if existing_value_type == tuple:
                settings[key] = tuple(_as_list(value))
            elif existing_value_type == frozenset:
                settings[key] = frozenset(_as_list(settings.get(key)))  # type: ignore
            elif existing_value_type == bool:
                # Only some configuration formats support native boolean values.
                if not isinstance(value, bool):
                    value = _as_bool(value)
                settings[key] = value
            elif key.startswith(KNOWN_PREFIX):
                settings[key] = _abspaths(os.path.dirname(file_path), _as_list(value))
            elif key == "force_grid_wrap":
                try:
                    result = existing_value_type(value)
                except ValueError:  # backwards compatibility for true / false force grid wrap
                    result = 0 if value.lower().strip() == "false" else 2
                settings[key] = result
            elif key == "comment_prefix":
                settings[key] = str(value).strip("'").strip('"')
            else:
                settings[key] = existing_value_type(value)
    return settings
References _abspaths(), _as_bool(), _as_list(), and _get_str_to_type_converter().
Referenced by _find_config(), and find_all_configs().
_get_str_to_type_converter()
Union[Callable[[str], Any], Type[Any]] isort.settings._get_str_to_type_converter (str setting_name) protected
Definition at line 739 of file settings.py.
def _get_str_to_type_converter(setting_name: str) -> Union[Callable[[str], Any], Type[Any]]:
    type_converter: Union[Callable[[str], Any], Type[Any]] = type(
        _DEFAULT_SETTINGS.get(setting_name, "")
    )
    if type_converter == WrapModes:
        type_converter = wrap_mode_from_string
    return type_converter
Referenced by _get_config_data().
find_all_configs()
Trie isort.settings.find_all_configs (str path)
Looks for config files in the path provided and in all of its sub-directories.
Parses and stores any config file encountered in a trie and returns the root of
the trie
Definition at line 799 of file settings.py.
def find_all_configs(path: str) -> Trie:
    """
    Looks for config files in the path provided and in all of its sub-directories.
    Parses and stores any config file encountered in a trie and returns the root of
    the trie
    """
    trie_root = Trie("default", {})
    for dirpath, _, _ in os.walk(path):
        for config_file_name in CONFIG_SOURCES:
            potential_config_file = os.path.join(dirpath, config_file_name)
            if os.path.isfile(potential_config_file):
                config_data: Dict[str, Any]
                try:
                    config_data = _get_config_data(
                        potential_config_file, CONFIG_SECTIONS[config_file_name]
                    )
                except Exception:
                    warn(f"Failed to pull configuration information from {potential_config_file}")
                    config_data = {}
                if config_data:
                    trie_root.insert(potential_config_file, config_data)
                    break
    return trie_root
References _get_config_data().
Variable Documentation
_DEFAULT_SETTINGS
dict isort.settings._DEFAULT_SETTINGS = {**vars(_Config()), "source": "defaults"} protected
Definition at line 290 of file settings.py.
_SHEBANG_RE
isort.settings._SHEBANG_RE = re.compile(rb"^#!.*\bpython[23w]?\b") protected
Definition at line 56 of file settings.py.
_STR_BOOLEAN_MAPPING
dict isort.settings._STR_BOOLEAN_MAPPING protected
Initial value:
=  {
    "y": True,
    "yes": True,
    "t": True,
    "on": True,
    "1": True,
    "true": True,
    "n": False,
    "no": False,
    "f": False,
    "off": False,
    "0": False,
    "false": False,
}
Definition at line 124 of file settings.py.
BLOCKED_EXTENSIONS
isort.settings.BLOCKED_EXTENSIONS = frozenset({"pex"})
Definition at line 59 of file settings.py.
CONFIG_SECTIONS
dict isort.settings.CONFIG_SECTIONS
Initial value:
=  {
    ".isort.cfg": ("settings", "isort"),
    "pyproject.toml": ("tool.isort",),
    "setup.cfg": ("isort", "tool:isort"),
    "tox.ini": ("isort", "tool:isort"),
    ".editorconfig": ("*", "*.py", "**.py", "*.{py}"),
}
Definition at line 100 of file settings.py.
CONFIG_SOURCES
tuple isort.settings.CONFIG_SOURCES
Initial value:
=  (
    ".isort.cfg",
    "pyproject.toml",
    "setup.cfg",
    "tox.ini",
    ".editorconfig",
)
Definition at line 69 of file settings.py.
CYTHON_EXTENSIONS
isort.settings.CYTHON_EXTENSIONS = frozenset({"pyx", "pxd"})
Definition at line 57 of file settings.py.
DEFAULT_CONFIG
isort.settings.DEFAULT_CONFIG = Config()
Definition at line 933 of file settings.py.
DEFAULT_SKIP
FrozenSet isort.settings.DEFAULT_SKIP
Initial value:
=  frozenset(
    {
        ".venv",
        "venv",
        ".tox",
        ".eggs",
        ".git",
        ".hg",
        ".mypy_cache",
        ".nox",
        ".svn",
        ".bzr",
        "_build",
        "buck-out",
        "build",
        "dist",
        ".pants.d",
        ".direnv",
        "node_modules",
        "__pypackages__",
        ".pytype",
    }
)
Definition at line 76 of file settings.py.
DEPRECATED_SETTINGS
tuple isort.settings.DEPRECATED_SETTINGS = ("not_skip", "keep_direct_and_as_imports")
Definition at line 122 of file settings.py.
FALLBACK_CONFIG_SECTIONS
tuple isort.settings.FALLBACK_CONFIG_SECTIONS = ("isort", "tool:isort", "tool.isort")
Definition at line 107 of file settings.py.
FILE_SKIP_COMMENTS
tuple isort.settings.FILE_SKIP_COMMENTS
Initial value:
=  (
    "isort:" + "skip_file",
    "isort: " + "skip_file",
)
Definition at line 60 of file settings.py.
IMPORT_FOOTER_PREFIX
str isort.settings.IMPORT_FOOTER_PREFIX = "import_footer_"
Definition at line 110 of file settings.py.
IMPORT_HEADING_PREFIX
str isort.settings.IMPORT_HEADING_PREFIX = "import_heading_"
Definition at line 109 of file settings.py.
KNOWN_PREFIX
str isort.settings.KNOWN_PREFIX = "known_"
Definition at line 111 of file settings.py.
KNOWN_SECTION_MAPPING
dict isort.settings.KNOWN_SECTION_MAPPING
Initial value:
=  {
    STDLIB: "STANDARD_LIBRARY",
    FUTURE: "FUTURE_LIBRARY",
    FIRSTPARTY: "FIRST_PARTY",
    THIRDPARTY: "THIRD_PARTY",
    LOCALFOLDER: "LOCAL_FOLDER",
}
Definition at line 112 of file settings.py.
MAX_CONFIG_SEARCH_DEPTH
int isort.settings.MAX_CONFIG_SEARCH_DEPTH = 25
Definition at line 64 of file settings.py.
RUNTIME_SOURCE
str isort.settings.RUNTIME_SOURCE = "runtime"
Definition at line 120 of file settings.py.
STOP_CONFIG_SEARCH_ON_DIRS
tuple isort.settings.STOP_CONFIG_SEARCH_ON_DIRS = (".git", ".hg")
Definition at line 65 of file settings.py.
SUPPORTED_EXTENSIONS
isort.settings.SUPPORTED_EXTENSIONS = frozenset({"py", "pyi", *CYTHON_EXTENSIONS})
Definition at line 58 of file settings.py.
VALID_PY_TARGETS
Tuple isort.settings.VALID_PY_TARGETS
Initial value:
=  tuple(
    target.replace("py", "") for target in dir(stdlibs) if not target.startswith("_")
)
Definition at line 66 of file settings.py.