Read&Watch: pip._vendor.typing_extensions Namespace Reference
pip._vendor.typing_extensions Namespace Reference
Classes
class _AnnotatedAlias
class _AnyMeta
class _ConcatenateForm
class _ConcatenateGenericAlias
class _DefaultMixin
class _ExtensionsSpecialForm
class _Immutable
class _LiteralForm
class _LiteralGenericAlias
class _NamedTupleMeta
class _ProtocolMeta
class _ReadOnlyForm
class _RequiredForm
class _Sentinel
class _SpecialForm
class _SpecialGenericAlias
class _TypedDictMeta
class _TypeGuardForm
class _TypeIsForm
class _TypeVarLikeMeta
class _UnpackAlias
class _UnpackForm
class _UnpackSpecialForm
class Annotated
class Any
class Buffer
class deprecated
class Doc
class NewType
class NoDefaultType
class NoDefaultTypeMeta
class ParamSpec
class ParamSpecArgs
class ParamSpecKwargs
class Protocol
class SupportsAbs
class SupportsBytes
class SupportsComplex
class SupportsFloat
class SupportsIndex
class SupportsInt
class SupportsRound
class TypeAliasType
class TypeVar
class TypeVarTuple
Functions
_should_collect_from_parameters (t)
final (f)
IntVar (name)
_flatten_literal_params (parameters)
_value_and_type_iter (params)
overload (func)
get_overloads (func)
_is_dunder (attr)
_get_protocol_attrs (cls)
_caller (depth=2)
_allow_reckless_class_checks (depth=3)
_no_init (self, *args, **kwargs)
_type_check_issubclass_arg_1 (arg)
_proto_hook (cls, other)
runtime_checkable (cls)
_ensure_subclassable (mro_entries)
_get_typeddict_qualifiers (annotation_type)
TypedDict (typename, fields=_marker, *, total=True, closed=False, **kwargs)
is_typeddict (tp)
assert_type (val, typ)
_strip_extras (t)
get_type_hints (obj, globalns=None, localns=None, include_extras=False)
get_origin (tp)
get_args (tp)
TypeAlias (self, parameters)
_set_default (type_param, default)
_set_module (typevarlike)
_concatenate_getitem (self, parameters)
Concatenate (self, parameters)
TypeGuard (self, parameters)
TypeIs (self, parameters)
LiteralString (self, params)
Self (self, params)
Never (self, params)
Required (self, parameters)
NotRequired (self, parameters)
ReadOnly (self, parameters)
_is_unpack (obj)
Unpack (self, parameters)
_unpack_args (*args)
T reveal_type (T obj)
Never assert_never (Never arg)
typing.Callable[[T], T] dataclass_transform (*, bool eq_default=True, bool order_default=False, bool kw_only_default=False, bool frozen_default=False, typing.Tuple[typing.Union[typing.Type[typing.Any], typing.Callable[..., typing.Any]],...] field_specifiers=(), **typing.Any kwargs)
_F override (_F arg)
_check_generic (cls, parameters, elen=_marker)
bool _has_generic_or_protocol_as_origin ()
bool _is_unpacked_typevartuple (x)
_collect_type_vars (types, typevar_types=None)
_collect_parameters (args)
_make_nmtuple (name, types, module, defaults=())
_namedtuple_mro_entries (bases)
NamedTuple (typename, fields=_marker, **kwargs)
get_original_bases (cls)
_is_unionable (obj)
bool is_protocol (type tp)
typing.FrozenSet[str] get_protocol_members (type tp)
Variables
bool PEP_560 = True
GenericMeta = type
tuple _PEP_696_IMPLEMENTED = (3, 13, 0, "beta")
_marker = _Sentinel()
NoReturn = typing.NoReturn
T = typing.TypeVar('T')
KT = typing.TypeVar('KT')
VT = typing.TypeVar('VT')
T_co = typing.TypeVar('T_co', covariant=True)
T_contra = typing.TypeVar('T_contra', contravariant=True)
ClassVar = typing.ClassVar
Final = typing.Final
final = typing.final
Literal = typing.Literal
doc
_overload_dummy = typing._overload_dummy
overload = typing.overload
get_overloads = typing.get_overloads
clear_overloads = typing.clear_overloads
_overload_registry
Type = typing.Type
Awaitable = typing.Awaitable
Coroutine = typing.Coroutine
AsyncIterable = typing.AsyncIterable
AsyncIterator = typing.AsyncIterator
Deque = typing.Deque
DefaultDict = typing.DefaultDict
OrderedDict = typing.OrderedDict
Counter = typing.Counter
ChainMap = typing.ChainMap
Text = typing.Text
TYPE_CHECKING = typing.TYPE_CHECKING
_special_generic_alias_base
_NoneType
Generator
AsyncGenerator
ContextManager
AsyncContextManager
dict _PROTO_ALLOWLIST
_EXCLUDED_ATTRS
Protocol = typing.Protocol
runtime_checkable = typing.runtime_checkable
runtime = runtime_checkable
SupportsInt = typing.SupportsInt
SupportsFloat = typing.SupportsFloat
SupportsComplex = typing.SupportsComplex
SupportsBytes = typing.SupportsBytes
SupportsIndex = typing.SupportsIndex
SupportsAbs = typing.SupportsAbs
SupportsRound = typing.SupportsRound
bool _PEP_728_IMPLEMENTED = False
TypedDict = typing.TypedDict
_TypedDictMeta = typing._TypedDictMeta
is_typeddict = typing.is_typeddict
str _TAKES_MODULE = "module" in inspect.signature(typing._type_check).parameters
_TypedDict
tuple _TYPEDDICT_TYPES = (typing._TypedDictMeta, _TypedDictMeta)
assert_type = typing.assert_type
get_type_hints = typing.get_type_hints
Annotated = typing.Annotated
_AnnotatedAlias = typing._AnnotatedAlias
get_origin = typing.get_origin
get_args = typing.get_args
_BaseGenericAlias = typing._GenericAlias
_typing_GenericAlias = typing._GenericAlias
TypeAlias = typing.TypeAlias
NoDefault = typing.NoDefault
ParamSpecArgs = typing.ParamSpecArgs
ParamSpecKwargs = typing.ParamSpecKwargs
Concatenate = typing.Concatenate
_ConcatenateGenericAlias = typing._ConcatenateGenericAlias
TypeGuard = typing.TypeGuard
TypeIs = typing.TypeIs
LiteralString = typing.LiteralString
Self = typing.Self
Never = typing.Never
Required = typing.Required
NotRequired = typing.NotRequired
ReadOnly = typing.ReadOnly
str _UNPACK_DOC
Unpack = typing.Unpack
reveal_type = typing.reveal_type
_ASSERT_NEVER_REPR_MAX_LENGTH = typing._ASSERT_NEVER_REPR_MAX_LENGTH
assert_never = typing.assert_never
dataclass_transform = typing.dataclass_transform
override = typing.override
_F = typing.TypeVar("_F", bound=typing.Callable[..., typing.Any])
deprecated = warnings.deprecated
_T = typing.TypeVar("_T")
_check_generic
dict _TYPEVARTUPLE_TYPES = {TypeVarTuple, getattr(typing, "TypeVarTuple", None)}
_collect_type_vars
_collect_parameters
NamedTuple = typing.NamedTuple
_prohibited_namedtuple_fields = typing._prohibited
_special_namedtuple_fields = frozenset({'__module__', '__name__', '__annotations__'})
_NamedTuple
Buffer = collections.abc.Buffer
get_original_bases = _types.get_original_bases
NewType = typing.NewType
TypeAliasType = typing.TypeAliasType
is_protocol = typing.is_protocol
get_protocol_members = typing.get_protocol_members
Doc = typing.Doc
_CapsuleType = getattr(_types, "CapsuleType", None)
_CAPI = getattr(_socket, "CAPI", None)
CapsuleType = _CapsuleType
AbstractSet = typing.AbstractSet
AnyStr = typing.AnyStr
BinaryIO = typing.BinaryIO
Callable = typing.Callable
Collection = typing.Collection
Container = typing.Container
Dict = typing.Dict
ForwardRef = typing.ForwardRef
FrozenSet = typing.FrozenSet
Generic = typing.Generic
Hashable = typing.Hashable
IO = typing.IO
ItemsView = typing.ItemsView
Iterable = typing.Iterable
Iterator = typing.Iterator
KeysView = typing.KeysView
List = typing.List
Mapping = typing.Mapping
MappingView = typing.MappingView
Match = typing.Match
MutableMapping = typing.MutableMapping
MutableSequence = typing.MutableSequence
MutableSet = typing.MutableSet
Optional = typing.Optional
Pattern = typing.Pattern
Reversible = typing.Reversible
Sequence = typing.Sequence
Set = typing.Set
Sized = typing.Sized
TextIO = typing.TextIO
Tuple = typing.Tuple
Union = typing.Union
ValuesView = typing.ValuesView
cast = typing.cast
no_type_check = typing.no_type_check
no_type_check_decorator = typing.no_type_check_decorator
bool _is_runtime_protocol = True
Function Documentation
_allow_reckless_class_checks()
pip._vendor.typing_extensions._allow_reckless_class_checks (depth = 3) protected
Allow instance and class checks for special stdlib modules.
The abc and functools modules indiscriminately call isinstance() and
issubclass() on the whole MRO of a user class, which may contain protocols.
Definition at line 542 of file typing_extensions.py.
    def _allow_reckless_class_checks(depth=3):
        """Allow instance and class checks for special stdlib modules.
        The abc and functools modules indiscriminately call isinstance() and
        issubclass() on the whole MRO of a user class, which may contain protocols.
        """
        return _caller(depth) in {'abc', 'functools', None}
References _caller().
Referenced by pip._vendor.typing_extensions._ProtocolMeta.__instancecheck__(), and pip._vendor.typing_extensions._ProtocolMeta.__subclasscheck__().
_caller()
pip._vendor.typing_extensions._caller (depth = 2) protected
Definition at line 530 of file typing_extensions.py.
def _caller(depth=2):
    try:
        return sys._getframe(depth).f_globals.get('__name__', '__main__')
    except (AttributeError, ValueError):  # For platforms without _getframe()
        return None
# `__match_args__` attribute was removed from protocol members in 3.13,
# we want to backport this change to older Python versions.
Referenced by pip._vendor.typing_extensions.NewType.__init__(), pip._vendor.typing_extensions.ParamSpec.__init__(), pip._vendor.typing_extensions.TypeAliasType.__init__(), pip._vendor.typing_extensions.TypeVarTuple.__init__(), _allow_reckless_class_checks(), _set_module(), NamedTuple(), and TypedDict().
_check_generic()
pip._vendor.typing_extensions._check_generic (cls, parameters, elen = _marker) protected
Check correct count for parameters of a generic cls (internal helper).
This gives a nice error message in case of count mismatch.
Definition at line 2872 of file typing_extensions.py.
    def _check_generic(cls, parameters, elen=_marker):
        """Check correct count for parameters of a generic cls (internal helper).
        This gives a nice error message in case of count mismatch.
        """
        if not elen:
            raise TypeError(f"{cls} is not a generic class")
        if elen is _marker:
            if not hasattr(cls, "__parameters__") or not cls.__parameters__:
                raise TypeError(f"{cls} is not a generic class")
            elen = len(cls.__parameters__)
        alen = len(parameters)
        if alen != elen:
            expect_val = elen
            if hasattr(cls, "__parameters__"):
                parameters = [p for p in cls.__parameters__ if not _is_unpack(p)]
                num_tv_tuples = sum(isinstance(p, TypeVarTuple) for p in parameters)
                if (num_tv_tuples > 0) and (alen >= elen - num_tv_tuples):
                    return
                # deal with TypeVarLike defaults
                # required TypeVarLikes cannot appear after a defaulted one.
                if alen < elen:
                    # since we validate TypeVarLike default in _collect_type_vars
                    # or _collect_parameters we can safely check parameters[alen]
                    if (
                        getattr(parameters[alen], '__default__', NoDefault)
                        is not NoDefault
                    ):
                        return
                    num_default_tv = sum(getattr(p, '__default__', NoDefault)
                                         is not NoDefault for p in parameters)
                    elen -= num_default_tv
                    expect_val = f"at least {elen}"
            things = "arguments" if sys.version_info >= (3, 10) else "parameters"
            raise TypeError(f"Too {'many' if alen > elen else 'few'} {things}"
                            f" for {cls}; actual {alen}, expected {expect_val}")
References _is_unpack().
_collect_parameters()
pip._vendor.typing_extensions._collect_parameters (args) protected
Collect all type variables and parameter specifications in args
in order of first appearance (lexicographic order).
For example::
    assert _collect_parameters((T, Callable[P, T])) == (T, P)
Definition at line 3029 of file typing_extensions.py.
    def _collect_parameters(args):
        """Collect all type variables and parameter specifications in args
        in order of first appearance (lexicographic order).
        For example::
            assert _collect_parameters((T, Callable[P, T])) == (T, P)
        """
        parameters = []
        # A required TypeVarLike cannot appear after a TypeVarLike with default
        # if it was a direct call to `Generic[]` or `Protocol[]`
        enforce_default_ordering = _has_generic_or_protocol_as_origin()
        default_encountered = False
        # Also, a TypeVarLike with a default cannot appear after a TypeVarTuple
        type_var_tuple_encountered = False
        for t in args:
            if isinstance(t, type):
                # We don't want __parameters__ descriptor of a bare Python class.
                pass
            elif isinstance(t, tuple):
                # `t` might be a tuple, when `ParamSpec` is substituted with
                # `[T, int]`, or `[int, *Ts]`, etc.
                for x in t:
                    for collected in _collect_parameters([x]):
                        if collected not in parameters:
                            parameters.append(collected)
            elif hasattr(t, '__typing_subst__'):
                if t not in parameters:
                    if enforce_default_ordering:
                        has_default = (
                            getattr(t, '__default__', NoDefault) is not NoDefault
                        )
                        if type_var_tuple_encountered and has_default:
                            raise TypeError('Type parameter with a default'
                                            ' follows TypeVarTuple')
                        if has_default:
                            default_encountered = True
                        elif default_encountered:
                            raise TypeError(f'Type parameter {t!r} without a default'
                                            ' follows type parameter with a default')
                    parameters.append(t)
            else:
                if _is_unpacked_typevartuple(t):
                    type_var_tuple_encountered = True
                for x in getattr(t, '__parameters__', ()):
                    if x not in parameters:
                        parameters.append(x)
        return tuple(parameters)
References _collect_parameters, _has_generic_or_protocol_as_origin(), and _is_unpacked_typevartuple().
_collect_type_vars()
pip._vendor.typing_extensions._collect_type_vars (types, typevar_types = None) protected
Collect all type variable contained in types in order of
first appearance (lexicographic order). For example::
    _collect_type_vars((T, List[S, T])) == (T, S)
Definition at line 2989 of file typing_extensions.py.
    def _collect_type_vars(types, typevar_types=None):
        """Collect all type variable contained in types in order of
        first appearance (lexicographic order). For example::
            _collect_type_vars((T, List[S, T])) == (T, S)
        """
        if typevar_types is None:
            typevar_types = typing.TypeVar
        tvars = []
        # A required TypeVarLike cannot appear after a TypeVarLike with a default
        # if it was a direct call to `Generic[]` or `Protocol[]`
        enforce_default_ordering = _has_generic_or_protocol_as_origin()
        default_encountered = False
        # Also, a TypeVarLike with a default cannot appear after a TypeVarTuple
        type_var_tuple_encountered = False
        for t in types:
            if _is_unpacked_typevartuple(t):
                type_var_tuple_encountered = True
            elif isinstance(t, typevar_types) and t not in tvars:
                if enforce_default_ordering:
                    has_default = getattr(t, '__default__', NoDefault) is not NoDefault
                    if has_default:
                        if type_var_tuple_encountered:
                            raise TypeError('Type parameter with a default'
                                            ' follows TypeVarTuple')
                        default_encountered = True
                    elif default_encountered:
                        raise TypeError(f'Type parameter {t!r} without a default'
                                        ' follows type parameter with a default')
                tvars.append(t)
            if _should_collect_from_parameters(t):
                tvars.extend([t for t in t.__parameters__ if t not in tvars])
        return tuple(tvars)
References _has_generic_or_protocol_as_origin(), _is_unpacked_typevartuple(), and _should_collect_from_parameters().
_concatenate_getitem()
pip._vendor.typing_extensions._concatenate_getitem (self, parameters) protected
Definition at line 1798 of file typing_extensions.py.
def _concatenate_getitem(self, parameters):
    if parameters == ():
        raise TypeError("Cannot take a Concatenate of no types.")
    if not isinstance(parameters, tuple):
        parameters = (parameters,)
    if not isinstance(parameters[-1], ParamSpec):
        raise TypeError("The last parameter to Concatenate should be a "
                        "ParamSpec variable.")
    msg = "Concatenate[arg, ...]: each arg must be a type."
    parameters = tuple(typing._type_check(p, msg) for p in parameters)
    return _ConcatenateGenericAlias(self, parameters)
# 3.10+
Referenced by pip._vendor.typing_extensions._ConcatenateForm.__getitem__(), and Concatenate().
_ensure_subclassable()
pip._vendor.typing_extensions._ensure_subclassable (mro_entries) protected
Definition at line 855 of file typing_extensions.py.
def _ensure_subclassable(mro_entries):
    def inner(func):
        if sys.implementation.name == "pypy" and sys.version_info < (3, 9):
            cls_dict = {
                "__call__": staticmethod(func),
                "__mro_entries__": staticmethod(mro_entries)
            }
            t = type(func.__name__, (), cls_dict)
            return functools.update_wrapper(t(), func)
        else:
            func.__mro_entries__ = mro_entries
            return func
    return inner
# Update this to something like >=3.13.0b1 if and when
# PEP 728 is implemented in CPython
_flatten_literal_params()
pip._vendor.typing_extensions._flatten_literal_params (parameters) protected
An internal helper for Literal creation: flatten Literals among parameters
Definition at line 263 of file typing_extensions.py.
    def _flatten_literal_params(parameters):
        """An internal helper for Literal creation: flatten Literals among parameters"""
        params = []
        for p in parameters:
            if isinstance(p, _LiteralGenericAlias):
                params.extend(p.__args__)
            else:
                params.append(p)
        return tuple(params)
Referenced by pip._vendor.typing_extensions._LiteralForm.__getitem__().
_get_protocol_attrs()
pip._vendor.typing_extensions._get_protocol_attrs (cls) protected
Definition at line 518 of file typing_extensions.py.
def _get_protocol_attrs(cls):
    attrs = set()
    for base in cls.__mro__[:-1]:  # without object
        if base.__name__ in {'Protocol', 'Generic'}:
            continue
        annotations = getattr(base, '__annotations__', {})
        for attr in (*base.__dict__, *annotations):
            if (not attr.startswith('_abc_') and attr not in _EXCLUDED_ATTRS):
                attrs.add(attr)
    return attrs
Referenced by pip._vendor.typing_extensions._ProtocolMeta.__init__(), and get_protocol_members().
_get_typeddict_qualifiers()
pip._vendor.typing_extensions._get_typeddict_qualifiers (annotation_type) protected
Definition at line 894 of file typing_extensions.py.
    def _get_typeddict_qualifiers(annotation_type):
        while True:
            annotation_origin = get_origin(annotation_type)
            if annotation_origin is Annotated:
                annotation_args = get_args(annotation_type)
                if annotation_args:
                    annotation_type = annotation_args[0]
                else:
                    break
            elif annotation_origin is Required:
                yield Required
                annotation_type, = get_args(annotation_type)
            elif annotation_origin is NotRequired:
                yield NotRequired
                annotation_type, = get_args(annotation_type)
            elif annotation_origin is ReadOnly:
                yield ReadOnly
                annotation_type, = get_args(annotation_type)
            else:
                break
References get_args, and get_origin.
Referenced by pip._vendor.typing_extensions._TypedDictMeta.__new__().
_has_generic_or_protocol_as_origin()
bool pip._vendor.typing_extensions._has_generic_or_protocol_as_origin () protected
Definition at line 2954 of file typing_extensions.py.
def _has_generic_or_protocol_as_origin() -> bool:
    try:
        frame = sys._getframe(2)
    # - Catch AttributeError: not all Python implementations have sys._getframe()
    # - Catch ValueError: maybe we're called from an unexpected module
    #   and the call stack isn't deep enough
    except (AttributeError, ValueError):
        return False  # err on the side of leniency
    else:
        # If we somehow get invoked from outside typing.py,
        # also err on the side of leniency
        if frame.f_globals.get("__name__") != "typing":
            return False
        origin = frame.f_locals.get("origin")
        # Cannot use "in" because origin may be an object with a buggy __eq__ that
        # throws an error.
        return origin is typing.Generic or origin is Protocol or origin is typing.Protocol
Referenced by _collect_parameters(), and _collect_type_vars().
_is_dunder()
pip._vendor.typing_extensions._is_dunder (attr) protected
Definition at line 423 of file typing_extensions.py.
    def _is_dunder(attr):
        return attr.startswith('__') and attr.endswith('__')
Referenced by pip._vendor.typing_extensions._SpecialGenericAlias.__setattr__().
_is_unionable()
pip._vendor.typing_extensions._is_unionable (obj) protected
Corresponds to is_unionable() in unionobject.c in CPython.
Definition at line 3385 of file typing_extensions.py.
    def _is_unionable(obj):
        """Corresponds to is_unionable() in unionobject.c in CPython."""
        return obj is None or isinstance(obj, (
            type,
            _types.GenericAlias,
            _types.UnionType,
            TypeAliasType,
        ))
Referenced by pip._vendor.typing_extensions.TypeAliasType.__or__(), and pip._vendor.typing_extensions.TypeAliasType.__ror__().
_is_unpack()
pip._vendor.typing_extensions._is_unpack (obj) protected
Definition at line 2337 of file typing_extensions.py.
    def _is_unpack(obj):
        return get_origin(obj) is Unpack
References get_origin.
Referenced by _check_generic().
_is_unpacked_typevartuple()
bool pip._vendor.typing_extensions._is_unpacked_typevartuple (x) protected
Definition at line 2976 of file typing_extensions.py.
def _is_unpacked_typevartuple(x) -> bool:
    if get_origin(x) is not Unpack:
        return False
    args = get_args(x)
    return (
        bool(args)
        and len(args) == 1
        and type(args[0]) in _TYPEVARTUPLE_TYPES
    )
# Python 3.11+ _collect_type_vars was renamed to _collect_parameters
References get_args, and get_origin.
Referenced by _collect_parameters(), and _collect_type_vars().
_make_nmtuple()
pip._vendor.typing_extensions._make_nmtuple (name, types, module, defaults = ()) protected
Definition at line 3096 of file typing_extensions.py.
    def _make_nmtuple(name, types, module, defaults=()):
        fields = [n for n, t in types]
        annotations = {n: typing._type_check(t, f"field {n} annotation must be a type")
                       for n, t in types}
        nm_tpl = collections.namedtuple(name, fields,
                                        defaults=defaults, module=module)
        nm_tpl.__annotations__ = nm_tpl.__new__.__annotations__ = annotations
        # The `_field_types` attribute was removed in 3.9;
        # in earlier versions, it is the same as the `__annotations__` attribute
        if sys.version_info < (3, 9):
            nm_tpl._field_types = annotations
        return nm_tpl
Referenced by pip._vendor.typing_extensions._NamedTupleMeta.__new__(), and NamedTuple().
_namedtuple_mro_entries()
pip._vendor.typing_extensions._namedtuple_mro_entries (bases) protected
Definition at line 3184 of file typing_extensions.py.
    def _namedtuple_mro_entries(bases):
        assert NamedTuple in bases
        return (_NamedTuple,)
_no_init()
pip._vendor.typing_extensions._no_init (self, * args, ** kwargs) protected
Definition at line 549 of file typing_extensions.py.
    def _no_init(self, *args, **kwargs):
        if type(self)._is_protocol:
            raise TypeError('Protocols cannot be instantiated')
_proto_hook()
pip._vendor.typing_extensions._proto_hook (cls, other) protected
Definition at line 673 of file typing_extensions.py.
    def _proto_hook(cls, other):
        if not cls.__dict__.get('_is_protocol', False):
            return NotImplemented
        for attr in cls.__protocol_attrs__:
            for base in other.__mro__:
                # Check if the members appears in the class dictionary...
                if attr in base.__dict__:
                    if base.__dict__[attr] is None:
                        return NotImplemented
                    break
                # ...or in annotations, if it is a sub-protocol.
                annotations = getattr(base, '__annotations__', {})
                if (
                    isinstance(annotations, collections.abc.Mapping)
                    and attr in annotations
                    and is_protocol(other)
                ):
                    break
            else:
                return NotImplemented
        return True
References is_protocol.
_set_default()
pip._vendor.typing_extensions._set_default (type_param, default) protected
Definition at line 1474 of file typing_extensions.py.
def _set_default(type_param, default):
    type_param.has_default = lambda: default is not NoDefault
    type_param.__default__ = default
Referenced by pip._vendor.typing_extensions.ParamSpec.__new__(), pip._vendor.typing_extensions.TypeVar.__new__(), and pip._vendor.typing_extensions.TypeVarTuple.__new__().
_set_module()
pip._vendor.typing_extensions._set_module (typevarlike) protected
Definition at line 1479 of file typing_extensions.py.
def _set_module(typevarlike):
    # for pickling:
    def_mod = _caller(depth=3)
    if def_mod != 'typing_extensions':
        typevarlike.__module__ = def_mod
References _caller().
Referenced by pip._vendor.typing_extensions.ParamSpec.__new__(), pip._vendor.typing_extensions.TypeVar.__new__(), and pip._vendor.typing_extensions.TypeVarTuple.__new__().
_should_collect_from_parameters()
pip._vendor.typing_extensions._should_collect_from_parameters (t) protected
Definition at line 154 of file typing_extensions.py.
    def _should_collect_from_parameters(t):
        return isinstance(
            t, (typing._GenericAlias, _types.GenericAlias, _types.UnionType)
        )
Referenced by _collect_type_vars().
_strip_extras()
pip._vendor.typing_extensions._strip_extras (t) protected
Strips Annotated, Required and NotRequired from a given type.
Definition at line 1173 of file typing_extensions.py.
    def _strip_extras(t):
        """Strips Annotated, Required and NotRequired from a given type."""
        if isinstance(t, _AnnotatedAlias):
            return _strip_extras(t.__origin__)
        if hasattr(t, "__origin__") and t.__origin__ in (Required, NotRequired, ReadOnly):
            return _strip_extras(t.__args__[0])
        if isinstance(t, typing._GenericAlias):
            stripped_args = tuple(_strip_extras(a) for a in t.__args__)
            if stripped_args == t.__args__:
                return t
            return t.copy_with(stripped_args)
        if hasattr(_types, "GenericAlias") and isinstance(t, _types.GenericAlias):
            stripped_args = tuple(_strip_extras(a) for a in t.__args__)
            if stripped_args == t.__args__:
                return t
            return _types.GenericAlias(t.__origin__, stripped_args)
        if hasattr(_types, "UnionType") and isinstance(t, _types.UnionType):
            stripped_args = tuple(_strip_extras(a) for a in t.__args__)
            if stripped_args == t.__args__:
                return t
            return functools.reduce(operator.or_, stripped_args)
        return t
References _strip_extras().
Referenced by _strip_extras(), and get_type_hints().
_type_check_issubclass_arg_1()
pip._vendor.typing_extensions._type_check_issubclass_arg_1 (arg) protected
Raise TypeError if `arg` is not an instance of `type`
in `issubclass(arg, <protocol>)`.
In most cases, this is verified by type.__subclasscheck__.
Checking it again unnecessarily would slow down issubclass() checks,
so, we don't perform this check unless we absolutely have to.
For various error paths, however,
we want to ensure that *this* error message is shown to the user
where relevant, rather than a typing.py-specific error message.
Definition at line 553 of file typing_extensions.py.
    def _type_check_issubclass_arg_1(arg):
        """Raise TypeError if `arg` is not an instance of `type`
        in `issubclass(arg, <protocol>)`.
        In most cases, this is verified by type.__subclasscheck__.
        Checking it again unnecessarily would slow down issubclass() checks,
        so, we don't perform this check unless we absolutely have to.
        For various error paths, however,
        we want to ensure that *this* error message is shown to the user
        where relevant, rather than a typing.py-specific error message.
        """
        if not isinstance(arg, type):
            # Same error message as for issubclass(1, int).
            raise TypeError('issubclass() arg 1 must be a class')
Referenced by pip._vendor.typing_extensions._ProtocolMeta.__subclasscheck__().
_unpack_args()
pip._vendor.typing_extensions._unpack_args (* args) protected
Definition at line 2389 of file typing_extensions.py.
    def _unpack_args(*args):
        newargs = []
        for arg in args:
            subargs = getattr(arg, '__typing_unpacked_tuple_args__', None)
            if subargs is not None and not (subargs and subargs[-1] is ...):
                newargs.extend(subargs)
            else:
                newargs.append(arg)
        return newargs
Referenced by pip._vendor.typing_extensions.TypeVarTuple.__new__().
_value_and_type_iter()
pip._vendor.typing_extensions._value_and_type_iter (params) protected
Definition at line 273 of file typing_extensions.py.
    def _value_and_type_iter(params):
        for p in params:
            yield p, type(p)
Referenced by pip._vendor.typing_extensions._LiteralGenericAlias.__eq__(), pip._vendor.typing_extensions._LiteralForm.__getitem__(), and pip._vendor.typing_extensions._LiteralGenericAlias.__hash__().
assert_never()
Never pip._vendor.typing_extensions.assert_never (Never arg)
Assert to the type checker that a line of code is unreachable.
Example::
    def int_or_str(arg: int | str) -> None:
        match arg:
            case int():
                print("It's an int")
            case str():
                print("It's a str")
            case _:
                assert_never(arg)
If a type checker finds that a call to assert_never() is
reachable, it will emit an error.
At runtime, this throws an exception when called.
Definition at line 2572 of file typing_extensions.py.
    def assert_never(arg: Never, /) -> Never:
        """Assert to the type checker that a line of code is unreachable.
        Example::
            def int_or_str(arg: int | str) -> None:
                match arg:
                    case int():
                        print("It's an int")
                    case str():
                        print("It's a str")
                    case _:
                        assert_never(arg)
        If a type checker finds that a call to assert_never() is
        reachable, it will emit an error.
        At runtime, this throws an exception when called.
        """
        value = repr(arg)
        if len(value) > _ASSERT_NEVER_REPR_MAX_LENGTH:
            value = value[:_ASSERT_NEVER_REPR_MAX_LENGTH] + '...'
        raise AssertionError(f"Expected code to be unreachable, but got: {value}")
assert_type()
pip._vendor.typing_extensions.assert_type (val, typ)
Assert (to the type checker) that the value is of the given type.
When the type checker encounters a call to assert_type(), it
emits an error if the value is not of the specified type::
    def greet(name: str) -> None:
        assert_type(name, str)  # ok
        assert_type(name, int)  # type checker error
At runtime this returns the first argument unchanged and otherwise
does nothing.
Definition at line 1153 of file typing_extensions.py.
    def assert_type(val, typ, /):
        """Assert (to the type checker) that the value is of the given type.
        When the type checker encounters a call to assert_type(), it
        emits an error if the value is not of the specified type::
            def greet(name: str) -> None:
                assert_type(name, str)  # ok
                assert_type(name, int)  # type checker error
        At runtime this returns the first argument unchanged and otherwise
        does nothing.
        """
        return val
Concatenate()
pip._vendor.typing_extensions.Concatenate (self, parameters)
Used in conjunction with ``ParamSpec`` and ``Callable`` to represent a
higher order function which adds, removes or transforms parameters of a
callable.
For example::
   Callable[Concatenate[int, P], int]
See PEP 612 for detailed information.
Definition at line 1818 of file typing_extensions.py.
    def Concatenate(self, parameters):
        """Used in conjunction with ``ParamSpec`` and ``Callable`` to represent a
        higher order function which adds, removes or transforms parameters of a
        callable.
        For example::
           Callable[Concatenate[int, P], int]
        See PEP 612 for detailed information.
        """
        return _concatenate_getitem(self, parameters)
# 3.8
References _concatenate_getitem().
dataclass_transform()
typing.Callable[[T], T] pip._vendor.typing_extensions.dataclass_transform (* , bool eq_default = True, bool order_default = False, bool kw_only_default = False, bool frozen_default = False, typing.Tuple[ typing.Union[typing.Type[typing.Any], typing.Callable[..., typing.Any]], ... ] field_specifiers = (), **typing.Any kwargs)
Decorator that marks a function, class, or metaclass as providing
dataclass-like behavior.
Example:
    from pip._vendor.typing_extensions import dataclass_transform
    _T = TypeVar("_T")
    # Used on a decorator function
    @dataclass_transform()
    def create_model(cls: type[_T]) -> type[_T]:
        ...
        return cls
    @create_model
    class CustomerModel:
        id: int
        name: str
    # Used on a base class
    @dataclass_transform()
    class ModelBase: ...
    class CustomerModel(ModelBase):
        id: int
        name: str
    # Used on a metaclass
    @dataclass_transform()
    class ModelMeta(type): ...
    class ModelBase(metaclass=ModelMeta): ...
    class CustomerModel(ModelBase):
        id: int
        name: str
Each of the ``CustomerModel`` classes defined in this example will now
behave similarly to a dataclass created with the ``@dataclasses.dataclass``
decorator. For example, the type checker will synthesize an ``__init__``
method.
The arguments to this decorator can be used to customize this behavior:
- ``eq_default`` indicates whether the ``eq`` parameter is assumed to be
  True or False if it is omitted by the caller.
- ``order_default`` indicates whether the ``order`` parameter is
  assumed to be True or False if it is omitted by the caller.
- ``kw_only_default`` indicates whether the ``kw_only`` parameter is
  assumed to be True or False if it is omitted by the caller.
- ``frozen_default`` indicates whether the ``frozen`` parameter is
  assumed to be True or False if it is omitted by the caller.
- ``field_specifiers`` specifies a static list of supported classes
  or functions that describe fields, similar to ``dataclasses.field()``.
At runtime, this decorator records its arguments in the
``__dataclass_transform__`` attribute on the decorated object.
See PEP 681 for details.
Definition at line 2602 of file typing_extensions.py.
    ) -> typing.Callable[[T], T]:
        """Decorator that marks a function, class, or metaclass as providing
        dataclass-like behavior.
        Example:
            from pip._vendor.typing_extensions import dataclass_transform
            _T = TypeVar("_T")
            # Used on a decorator function
            @dataclass_transform()
            def create_model(cls: type[_T]) -> type[_T]:
                ...
                return cls
            @create_model
            class CustomerModel:
                id: int
                name: str
            # Used on a base class
            @dataclass_transform()
            class ModelBase: ...
            class CustomerModel(ModelBase):
                id: int
                name: str
            # Used on a metaclass
            @dataclass_transform()
            class ModelMeta(type): ...
            class ModelBase(metaclass=ModelMeta): ...
            class CustomerModel(ModelBase):
                id: int
                name: str
        Each of the ``CustomerModel`` classes defined in this example will now
        behave similarly to a dataclass created with the ``@dataclasses.dataclass``
        decorator. For example, the type checker will synthesize an ``__init__``
        method.
        The arguments to this decorator can be used to customize this behavior:
        - ``eq_default`` indicates whether the ``eq`` parameter is assumed to be
          True or False if it is omitted by the caller.
        - ``order_default`` indicates whether the ``order`` parameter is
          assumed to be True or False if it is omitted by the caller.
        - ``kw_only_default`` indicates whether the ``kw_only`` parameter is
          assumed to be True or False if it is omitted by the caller.
        - ``frozen_default`` indicates whether the ``frozen`` parameter is
          assumed to be True or False if it is omitted by the caller.
        - ``field_specifiers`` specifies a static list of supported classes
          or functions that describe fields, similar to ``dataclasses.field()``.
        At runtime, this decorator records its arguments in the
        ``__dataclass_transform__`` attribute on the decorated object.
        See PEP 681 for details.
        """
        def decorator(cls_or_fn):
            cls_or_fn.__dataclass_transform__ = {
                "eq_default": eq_default,
                "order_default": order_default,
                "kw_only_default": kw_only_default,
                "frozen_default": frozen_default,
                "field_specifiers": field_specifiers,
                "kwargs": kwargs,
            }
            return cls_or_fn
        return decorator
final()
pip._vendor.typing_extensions.final (f)
This decorator can be used to indicate to type checkers that
the decorated method cannot be overridden, and decorated class
cannot be subclassed. For example:
    class Base:
        @final
        def done(self) -> None:
            ...
    class Sub(Base):
        def done(self) -> None:  # Error reported by type checker
            ...
    @final
    class Leaf:
        ...
    class Other(Leaf):  # Error reported by type checker
        ...
There is no runtime checking of these properties. The decorator
sets the ``__final__`` attribute to ``True`` on the decorated object
to allow runtime introspection.
Definition at line 223 of file typing_extensions.py.
    def final(f):
        """This decorator can be used to indicate to type checkers that
        the decorated method cannot be overridden, and decorated class
        cannot be subclassed. For example:
            class Base:
                @final
                def done(self) -> None:
                    ...
            class Sub(Base):
                def done(self) -> None:  # Error reported by type checker
                    ...
            @final
            class Leaf:
                ...
            class Other(Leaf):  # Error reported by type checker
                ...
        There is no runtime checking of these properties. The decorator
        sets the ``__final__`` attribute to ``True`` on the decorated object
        to allow runtime introspection.
        """
        try:
            f.__final__ = True
        except (AttributeError, TypeError):
            # Skip the attribute silently if it is not writable.
            # AttributeError happens if the object has __slots__ or a
            # read-only property, TypeError if it's a builtin class.
            pass
        return f
get_args()
pip._vendor.typing_extensions.get_args (tp)
Get type arguments with all substitutions performed.
For unions, basic simplifications used by Union constructor are performed.
Examples::
    get_args(Dict[str, int]) == (str, int)
    get_args(int) == ()
    get_args(Union[int, Union[T, int], str][int]) == (int, str)
    get_args(Union[int, Tuple[T, int]][str]) == (int, Tuple[str, int])
    get_args(Callable[[], T][int]) == ([], int)
Definition at line 1388 of file typing_extensions.py.
    def get_args(tp):
        """Get type arguments with all substitutions performed.
        For unions, basic simplifications used by Union constructor are performed.
        Examples::
            get_args(Dict[str, int]) == (str, int)
            get_args(int) == ()
            get_args(Union[int, Union[T, int], str][int]) == (int, str)
            get_args(Union[int, Tuple[T, int]][str]) == (int, Tuple[str, int])
            get_args(Callable[[], T][int]) == ([], int)
        """
        if isinstance(tp, _AnnotatedAlias):
            return (tp.__origin__, *tp.__metadata__)
        if isinstance(tp, (typing._GenericAlias, _typing_GenericAlias)):
            if getattr(tp, "_special", False):
                return ()
            res = tp.__args__
            if get_origin(tp) is collections.abc.Callable and res[0] is not Ellipsis:
                res = (list(res[:-1]), res[-1])
            return res
        return ()
# 3.10+
References get_origin.
get_origin()
pip._vendor.typing_extensions.get_origin (tp)
Get the unsubscripted version of a type.
This supports generic types, Callable, Tuple, Union, Literal, Final, ClassVar
and Annotated. Return None for unsupported types. Examples::
    get_origin(Literal[42]) is Literal
    get_origin(int) is None
    get_origin(ClassVar[int]) is ClassVar
    get_origin(Generic) is Generic
    get_origin(Generic[T]) is Generic
    get_origin(Union[T, int]) is Union
    get_origin(List[Tuple[T, T]][int]) == list
    get_origin(P.args) is P
Definition at line 1364 of file typing_extensions.py.
    def get_origin(tp):
        """Get the unsubscripted version of a type.
        This supports generic types, Callable, Tuple, Union, Literal, Final, ClassVar
        and Annotated. Return None for unsupported types. Examples::
            get_origin(Literal[42]) is Literal
            get_origin(int) is None
            get_origin(ClassVar[int]) is ClassVar
            get_origin(Generic) is Generic
            get_origin(Generic[T]) is Generic
            get_origin(Union[T, int]) is Union
            get_origin(List[Tuple[T, T]][int]) == list
            get_origin(P.args) is P
        """
        if isinstance(tp, _AnnotatedAlias):
            return Annotated
        if isinstance(tp, (typing._GenericAlias, _typing_GenericAlias, _BaseGenericAlias,
                           ParamSpecArgs, ParamSpecKwargs)):
            return tp.__origin__
        if tp is typing.Generic:
            return typing.Generic
        return None
get_original_bases()
pip._vendor.typing_extensions.get_original_bases (cls)
Return the class's "original" bases prior to modification by `__mro_entries__`.
Examples::
    from typing import TypeVar, Generic
    from pip._vendor.typing_extensions import NamedTuple, TypedDict
    T = TypeVar("T")
    class Foo(Generic[T]): ...
    class Bar(Foo[int], float): ...
    class Baz(list[str]): ...
    Eggs = NamedTuple("Eggs", [("a", int), ("b", str)])
    Spam = TypedDict("Spam", {"a": int, "b": str})
    assert get_original_bases(Bar) == (Foo[int], float)
    assert get_original_bases(Baz) == (list[str],)
    assert get_original_bases(Eggs) == (NamedTuple,)
    assert get_original_bases(Spam) == (TypedDict,)
    assert get_original_bases(int) == (object,)
Definition at line 3288 of file typing_extensions.py.
    def get_original_bases(cls, /):
        """Return the class's "original" bases prior to modification by `__mro_entries__`.
        Examples::
            from typing import TypeVar, Generic
            from pip._vendor.typing_extensions import NamedTuple, TypedDict
            T = TypeVar("T")
            class Foo(Generic[T]): ...
            class Bar(Foo[int], float): ...
            class Baz(list[str]): ...
            Eggs = NamedTuple("Eggs", [("a", int), ("b", str)])
            Spam = TypedDict("Spam", {"a": int, "b": str})
            assert get_original_bases(Bar) == (Foo[int], float)
            assert get_original_bases(Baz) == (list[str],)
            assert get_original_bases(Eggs) == (NamedTuple,)
            assert get_original_bases(Spam) == (TypedDict,)
            assert get_original_bases(int) == (object,)
        """
        try:
            return cls.__dict__.get("__orig_bases__", cls.__bases__)
        except AttributeError:
            raise TypeError(
                f'Expected an instance of type, not {type(cls).__name__!r}'
            ) from None
# NewType is a class on Python 3.10+, making it pickleable
# The error message for subclassing instances of NewType was improved on 3.11+
get_overloads()
pip._vendor.typing_extensions.get_overloads (func)
Return all defined overloads for *func* as a sequence.
Definition at line 386 of file typing_extensions.py.
    def get_overloads(func):
        """Return all defined overloads for *func* as a sequence."""
        # classmethod and staticmethod
        f = getattr(func, "__func__", func)
        if f.__module__ not in _overload_registry:
            return []
        mod_dict = _overload_registry[f.__module__]
        if f.__qualname__ not in mod_dict:
            return []
        return list(mod_dict[f.__qualname__].values())
get_protocol_members()
typing.FrozenSet[str] pip._vendor.typing_extensions.get_protocol_members (type tp)
Return the set of members defined in a Protocol.
Example::
    >>> from typing_extensions import Protocol, get_protocol_members
    >>> class P(Protocol):
    ...     def a(self) -> str: ...
    ...     b: int
    >>> get_protocol_members(P)
    frozenset({'a', 'b'})
Raise a TypeError for arguments that are not Protocols.
Definition at line 3529 of file typing_extensions.py.
    def get_protocol_members(tp: type, /) -> typing.FrozenSet[str]:
        """Return the set of members defined in a Protocol.
        Example::
            >>> from typing_extensions import Protocol, get_protocol_members
            >>> class P(Protocol):
            ...     def a(self) -> str: ...
            ...     b: int
            >>> get_protocol_members(P)
            frozenset({'a', 'b'})
        Raise a TypeError for arguments that are not Protocols.
        """
        if not is_protocol(tp):
            raise TypeError(f'{tp!r} is not a Protocol')
        if hasattr(tp, '__protocol_attrs__'):
            return frozenset(tp.__protocol_attrs__)
        return frozenset(_get_protocol_attrs(tp))
References _get_protocol_attrs(), and is_protocol.
get_type_hints()
pip._vendor.typing_extensions.get_type_hints (obj, globalns = None, localns = None, include_extras = False)
Return type hints for an object.
This is often the same as obj.__annotations__, but it handles
forward references encoded as string literals, adds Optional[t] if a
default value equal to None is set and recursively replaces all
'Annotated[T, ...]', 'Required[T]' or 'NotRequired[T]' with 'T'
(unless 'include_extras=True').
The argument may be a module, class, method, or function. The annotations
are returned as a dictionary. For classes, annotations include also
inherited members.
TypeError is raised if the argument is not of a type that can contain
annotations, and an empty dictionary is returned if no annotations are
present.
BEWARE -- the behavior of globalns and localns is counterintuitive
(unless you are familiar with how eval() and exec() work).  The
search order is locals first, then globals.
- If no dict arguments are passed, an attempt is made to use the
  globals from obj (or the respective module's globals for classes),
  and these are also used as the locals.  If the object does not appear
  to have globals, an empty dictionary is used.
- If one dict argument is passed, it is used for both globals and
  locals.
- If two dict arguments are passed, they specify globals and
  locals, respectively.
Definition at line 1197 of file typing_extensions.py.
    def get_type_hints(obj, globalns=None, localns=None, include_extras=False):
        """Return type hints for an object.
        This is often the same as obj.__annotations__, but it handles
        forward references encoded as string literals, adds Optional[t] if a
        default value equal to None is set and recursively replaces all
        'Annotated[T, ...]', 'Required[T]' or 'NotRequired[T]' with 'T'
        (unless 'include_extras=True').
        The argument may be a module, class, method, or function. The annotations
        are returned as a dictionary. For classes, annotations include also
        inherited members.
        TypeError is raised if the argument is not of a type that can contain
        annotations, and an empty dictionary is returned if no annotations are
        present.
        BEWARE -- the behavior of globalns and localns is counterintuitive
        (unless you are familiar with how eval() and exec() work).  The
        search order is locals first, then globals.
        - If no dict arguments are passed, an attempt is made to use the
          globals from obj (or the respective module's globals for classes),
          and these are also used as the locals.  If the object does not appear
          to have globals, an empty dictionary is used.
        - If one dict argument is passed, it is used for both globals and
          locals.
        - If two dict arguments are passed, they specify globals and
          locals, respectively.
        """
        if hasattr(typing, "Annotated"):  # 3.9+
            hint = typing.get_type_hints(
                obj, globalns=globalns, localns=localns, include_extras=True
            )
        else:  # 3.8
            hint = typing.get_type_hints(obj, globalns=globalns, localns=localns)
        if include_extras:
            return hint
        return {k: _strip_extras(t) for k, t in hint.items()}
# Python 3.9+ has PEP 593 (Annotated)
References _strip_extras().
IntVar()
pip._vendor.typing_extensions.IntVar (name)
Definition at line 255 of file typing_extensions.py.
def IntVar(name):
    return typing.TypeVar(name)
# A Literal bug was fixed in 3.11.0, 3.10.1 and 3.9.8
is_protocol()
bool pip._vendor.typing_extensions.is_protocol (type tp)
Return True if the given type is a Protocol.
Example::
    >>> from typing_extensions import Protocol, is_protocol
    >>> class P(Protocol):
    ...     def a(self) -> str: ...
    ...     b: int
    >>> is_protocol(P)
    True
    >>> is_protocol(int)
    False
Definition at line 3508 of file typing_extensions.py.
    def is_protocol(tp: type, /) -> bool:
        """Return True if the given type is a Protocol.
        Example::
            >>> from typing_extensions import Protocol, is_protocol
            >>> class P(Protocol):
            ...     def a(self) -> str: ...
            ...     b: int
            >>> is_protocol(P)
            True
            >>> is_protocol(int)
            False
        """
        return (
            isinstance(tp, type)
            and getattr(tp, '_is_protocol', False)
            and tp is not Protocol
            and tp is not typing.Protocol
        )
is_typeddict()
pip._vendor.typing_extensions.is_typeddict (tp)
Check if an annotation is a TypedDict class
For example::
    class Film(TypedDict):
        title: str
        year: int
    is_typeddict(Film)  # => True
    is_typeddict(Union[list, str])  # => False
Definition at line 1132 of file typing_extensions.py.
    def is_typeddict(tp):
        """Check if an annotation is a TypedDict class
        For example::
            class Film(TypedDict):
                title: str
                year: int
            is_typeddict(Film)  # => True
            is_typeddict(Union[list, str])  # => False
        """
        # On 3.8, this would otherwise return True
        if hasattr(typing, "TypedDict") and tp is typing.TypedDict:
            return False
        return isinstance(tp, _TYPEDDICT_TYPES)
LiteralString()
pip._vendor.typing_extensions.LiteralString (self, params)
Represents an arbitrary literal string.
Example::
  from pip._vendor.typing_extensions import LiteralString
  def query(sql: LiteralString) -> ...:
      ...
  query("SELECT * FROM table")  # ok
  query(f"SELECT * FROM {input()}")  # not ok
See PEP 675 for details.
Definition at line 2094 of file typing_extensions.py.
    def LiteralString(self, params):
        """Represents an arbitrary literal string.
        Example::
          from pip._vendor.typing_extensions import LiteralString
          def query(sql: LiteralString) -> ...:
              ...
          query("SELECT * FROM table")  # ok
          query(f"SELECT * FROM {input()}")  # not ok
        See PEP 675 for details.
        """
        raise TypeError(f"{self} is not subscriptable")
NamedTuple()
pip._vendor.typing_extensions.NamedTuple (typename, fields = _marker, ** kwargs)
Typed version of namedtuple.
Usage::
    class Employee(NamedTuple):
        name: str
        id: int
This is equivalent to::
    Employee = collections.namedtuple('Employee', ['name', 'id'])
The resulting class has an extra __annotations__ attribute, giving a
dict that maps field names to types.  (The field names are also in
the _fields attribute, which is part of the namedtuple API.)
An alternative equivalent functional syntax is also accepted::
    Employee = NamedTuple('Employee', [('name', str), ('id', int)])
Definition at line 3189 of file typing_extensions.py.
    def NamedTuple(typename, fields=_marker, /, **kwargs):
        """Typed version of namedtuple.
        Usage::
            class Employee(NamedTuple):
                name: str
                id: int
        This is equivalent to::
            Employee = collections.namedtuple('Employee', ['name', 'id'])
        The resulting class has an extra __annotations__ attribute, giving a
        dict that maps field names to types.  (The field names are also in
        the _fields attribute, which is part of the namedtuple API.)
        An alternative equivalent functional syntax is also accepted::
            Employee = NamedTuple('Employee', [('name', str), ('id', int)])
        """
        if fields is _marker:
            if kwargs:
                deprecated_thing = "Creating NamedTuple classes using keyword arguments"
                deprecation_msg = (
                    "{name} is deprecated and will be disallowed in Python {remove}. "
                    "Use the class-based or functional syntax instead."
                )
            else:
                deprecated_thing = "Failing to pass a value for the 'fields' parameter"
                example = f"`{typename} = NamedTuple({typename!r}, [])`"
                deprecation_msg = (
                    "{name} is deprecated and will be disallowed in Python {remove}. "
                    "To create a NamedTuple class with 0 fields "
                    "using the functional syntax, "
                    "pass an empty list, e.g. "
                ) + example + "."
        elif fields is None:
            if kwargs:
                raise TypeError(
                    "Cannot pass `None` as the 'fields' parameter "
                    "and also specify fields using keyword arguments"
                )
            else:
                deprecated_thing = "Passing `None` as the 'fields' parameter"
                example = f"`{typename} = NamedTuple({typename!r}, [])`"
                deprecation_msg = (
                    "{name} is deprecated and will be disallowed in Python {remove}. "
                    "To create a NamedTuple class with 0 fields "
                    "using the functional syntax, "
                    "pass an empty list, e.g. "
                ) + example + "."
        elif kwargs:
            raise TypeError("Either list of fields or keywords"
                            " can be provided to NamedTuple, not both")
        if fields is _marker or fields is None:
            warnings.warn(
                deprecation_msg.format(name=deprecated_thing, remove="3.15"),
                DeprecationWarning,
                stacklevel=2,
            )
            fields = kwargs.items()
        nt = _make_nmtuple(typename, fields, module=_caller())
        nt.__orig_bases__ = (NamedTuple,)
        return nt
References _caller(), and _make_nmtuple().
Never()
pip._vendor.typing_extensions.Never (self, params)
The bottom type, a type that has no members.
This can be used to define a function that should never be
called, or a function that never returns::
    from pip._vendor.typing_extensions import Never
    def never_call_me(arg: Never) -> None:
        pass
    def int_or_str(arg: int | str) -> None:
        never_call_me(arg)  # type checker error
        match arg:
            case int():
                print("It's an int")
            case str():
                print("It's a str")
            case _:
                never_call_me(arg)  # ok, arg is of type Never
Definition at line 2138 of file typing_extensions.py.
    def Never(self, params):
        """The bottom type, a type that has no members.
        This can be used to define a function that should never be
        called, or a function that never returns::
            from pip._vendor.typing_extensions import Never
            def never_call_me(arg: Never) -> None:
                pass
            def int_or_str(arg: int | str) -> None:
                never_call_me(arg)  # type checker error
                match arg:
                    case int():
                        print("It's an int")
                    case str():
                        print("It's a str")
                    case _:
                        never_call_me(arg)  # ok, arg is of type Never
        """
        raise TypeError(f"{self} is not subscriptable")
NotRequired()
pip._vendor.typing_extensions.NotRequired (self, parameters)
A special typing construct to mark a key of a TypedDict as
potentially missing. For example:
    class Movie(TypedDict):
        title: str
        year: NotRequired[int]
    m = Movie(
        title='The Matrix',  # typechecker error if key is omitted
        year=1999,
    )
Definition at line 2189 of file typing_extensions.py.
    def NotRequired(self, parameters):
        """A special typing construct to mark a key of a TypedDict as
        potentially missing. For example:
            class Movie(TypedDict):
                title: str
                year: NotRequired[int]
            m = Movie(
                title='The Matrix',  # typechecker error if key is omitted
                year=1999,
            )
        """
        item = typing._type_check(parameters, f'{self._name} accepts only a single type.')
        return typing._GenericAlias(self, (item,))
overload()
pip._vendor.typing_extensions.overload (func)
Decorator for overloaded functions/methods.
In a stub file, place two or more stub definitions for the same
function in a row, each decorated with @overload.  For example:
@overload
def utf8(value: None) -> None: ...
@overload
def utf8(value: bytes) -> bytes: ...
@overload
def utf8(value: str) -> bytes: ...
In a non-stub file (i.e. a regular .py file), do the same but
follow it with an implementation.  The implementation should *not*
be decorated with @overload.  For example:
@overload
def utf8(value: None) -> None: ...
@overload
def utf8(value: bytes) -> bytes: ...
@overload
def utf8(value: str) -> bytes: ...
def utf8(value):
    # implementation goes here
The overloads for a function can be retrieved at runtime using the
get_overloads() function.
Definition at line 346 of file typing_extensions.py.
    def overload(func):
        """Decorator for overloaded functions/methods.
        In a stub file, place two or more stub definitions for the same
        function in a row, each decorated with @overload.  For example:
        @overload
        def utf8(value: None) -> None: ...
        @overload
        def utf8(value: bytes) -> bytes: ...
        @overload
        def utf8(value: str) -> bytes: ...
        In a non-stub file (i.e. a regular .py file), do the same but
        follow it with an implementation.  The implementation should *not*
        be decorated with @overload.  For example:
        @overload
        def utf8(value: None) -> None: ...
        @overload
        def utf8(value: bytes) -> bytes: ...
        @overload
        def utf8(value: str) -> bytes: ...
        def utf8(value):
            # implementation goes here
        The overloads for a function can be retrieved at runtime using the
        get_overloads() function.
        """
        # classmethod and staticmethod
        f = getattr(func, "__func__", func)
        try:
            _overload_registry[f.__module__][f.__qualname__][
                f.__code__.co_firstlineno
            ] = func
        except AttributeError:
            # Not a normal function; ignore.
            pass
        return _overload_dummy
override()
_F pip._vendor.typing_extensions.override (_F arg)
Indicate that a method is intended to override a method in a base class.
Usage:
    class Base:
        def method(self) -> None:
            pass
    class Child(Base):
        @override
        def method(self) -> None:
            super().method()
When this decorator is applied to a method, the type checker will
validate that it overrides a method with the same name on a base class.
This helps prevent bugs that may occur when a base class is changed
without an equivalent change to a child class.
There is no runtime checking of these properties. The decorator
sets the ``__override__`` attribute to ``True`` on the decorated object
to allow runtime introspection.
See PEP 698 for details.
Definition at line 2693 of file typing_extensions.py.
    def override(arg: _F, /) -> _F:
        """Indicate that a method is intended to override a method in a base class.
        Usage:
            class Base:
                def method(self) -> None:
                    pass
            class Child(Base):
                @override
                def method(self) -> None:
                    super().method()
        When this decorator is applied to a method, the type checker will
        validate that it overrides a method with the same name on a base class.
        This helps prevent bugs that may occur when a base class is changed
        without an equivalent change to a child class.
        There is no runtime checking of these properties. The decorator
        sets the ``__override__`` attribute to ``True`` on the decorated object
        to allow runtime introspection.
        See PEP 698 for details.
        """
        try:
            arg.__override__ = True
        except (AttributeError, TypeError):
            # Skip the attribute silently if it is not writable.
            # AttributeError happens if the object has __slots__ or a
            # read-only property, TypeError if it's a builtin class.
            pass
        return arg
ReadOnly()
pip._vendor.typing_extensions.ReadOnly (self, parameters)
A special typing construct to mark an item of a TypedDict as read-only.
For example:
    class Movie(TypedDict):
        title: ReadOnly[str]
        year: int
    def mutate_movie(m: Movie) -> None:
        m["year"] = 1992  # allowed
        m["title"] = "The Matrix"  # typechecker error
There is no runtime checking for this property.
Definition at line 2249 of file typing_extensions.py.
    def ReadOnly(self, parameters):
        """A special typing construct to mark an item of a TypedDict as read-only.
        For example:
            class Movie(TypedDict):
                title: ReadOnly[str]
                year: int
            def mutate_movie(m: Movie) -> None:
                m["year"] = 1992  # allowed
                m["title"] = "The Matrix"  # typechecker error
        There is no runtime checking for this property.
        """
        item = typing._type_check(parameters, f'{self._name} accepts only a single type.')
        return typing._GenericAlias(self, (item,))
Required()
pip._vendor.typing_extensions.Required (self, parameters)
A special typing construct to mark a key of a total=False TypedDict
as required. For example:
    class Movie(TypedDict, total=False):
        title: Required[str]
        year: int
    m = Movie(
        title='The Matrix',  # typechecker error if key is omitted
        year=1999,
    )
There is no runtime checking that a required key is actually provided
when instantiating a related TypedDict.
Definition at line 2169 of file typing_extensions.py.
    def Required(self, parameters):
        """A special typing construct to mark a key of a total=False TypedDict
        as required. For example:
            class Movie(TypedDict, total=False):
                title: Required[str]
                year: int
            m = Movie(
                title='The Matrix',  # typechecker error if key is omitted
                year=1999,
            )
        There is no runtime checking that a required key is actually provided
        when instantiating a related TypedDict.
        """
        item = typing._type_check(parameters, f'{self._name} accepts only a single type.')
        return typing._GenericAlias(self, (item,))
reveal_type()
T pip._vendor.typing_extensions.reveal_type (T obj)
Reveal the inferred type of a variable.
When a static type checker encounters a call to ``reveal_type()``,
it will emit the inferred type of the argument::
    x: int = 1
    reveal_type(x)
Running a static type checker (e.g., ``mypy``) on this example
will produce output similar to 'Revealed type is "builtins.int"'.
At runtime, the function prints the runtime type of the
argument and returns it unchanged.
Definition at line 2543 of file typing_extensions.py.
    def reveal_type(obj: T, /) -> T:
        """Reveal the inferred type of a variable.
        When a static type checker encounters a call to ``reveal_type()``,
        it will emit the inferred type of the argument::
            x: int = 1
            reveal_type(x)
        Running a static type checker (e.g., ``mypy``) on this example
        will produce output similar to 'Revealed type is "builtins.int"'.
        At runtime, the function prints the runtime type of the
        argument and returns it unchanged.
        """
        print(f"Runtime type is {type(obj).__name__!r}", file=sys.stderr)
        return obj
runtime_checkable()
pip._vendor.typing_extensions.runtime_checkable (cls)
Mark a protocol class as a runtime protocol.
Such protocol can be used with isinstance() and issubclass().
Raise TypeError if applied to a non-protocol class.
This allows a simple-minded structural check very similar to
one trick ponies in collections.abc such as Iterable.
For example::
    @runtime_checkable
    class Closable(Protocol):
        def close(self): ...
    assert isinstance(open('/some/file'), Closable)
Warning: this will check only the presence of the required methods,
not their type signatures!
Definition at line 722 of file typing_extensions.py.
    def runtime_checkable(cls):
        """Mark a protocol class as a runtime protocol.
        Such protocol can be used with isinstance() and issubclass().
        Raise TypeError if applied to a non-protocol class.
        This allows a simple-minded structural check very similar to
        one trick ponies in collections.abc such as Iterable.
        For example::
            @runtime_checkable
            class Closable(Protocol):
                def close(self): ...
            assert isinstance(open('/some/file'), Closable)
        Warning: this will check only the presence of the required methods,
        not their type signatures!
        """
        if not issubclass(cls, typing.Generic) or not getattr(cls, '_is_protocol', False):
            raise TypeError(f'@runtime_checkable can be only applied to protocol classes,'
                            f' got {cls!r}')
        cls._is_runtime_protocol = True
        # typing.Protocol classes on <=3.11 break if we execute this block,
        # because typing.Protocol classes on <=3.11 don't have a
        # `__protocol_attrs__` attribute, and this block relies on the
        # `__protocol_attrs__` attribute. Meanwhile, typing.Protocol classes on 3.12.2+
        # break if we *don't* execute this block, because *they* assume that all
        # protocol classes have a `__non_callable_proto_members__` attribute
        # (which this block sets)
        if isinstance(cls, _ProtocolMeta) or sys.version_info >= (3, 12, 2):
            # PEP 544 prohibits using issubclass()
            # with protocols that have non-method members.
            # See gh-113320 for why we compute this attribute here,
            # rather than in `_ProtocolMeta.__init__`
            cls.__non_callable_proto_members__ = set()
            for attr in cls.__protocol_attrs__:
                try:
                    is_callable = callable(getattr(cls, attr, None))
                except Exception as e:
                    raise TypeError(
                        f"Failed to determine whether protocol member {attr!r} "
                        "is a method member"
                    ) from e
                else:
                    if not is_callable:
                        cls.__non_callable_proto_members__.add(attr)
        return cls
# The "runtime" alias exists for backwards compatibility.
Self()
pip._vendor.typing_extensions.Self (self, params)
Used to spell the type of "self" in classes.
Example::
  from typing import Self
  class ReturnsSelf:
      def parse(self, data: bytes) -> Self:
          ...
          return self
Definition at line 2117 of file typing_extensions.py.
    def Self(self, params):
        """Used to spell the type of "self" in classes.
        Example::
          from typing import Self
          class ReturnsSelf:
              def parse(self, data: bytes) -> Self:
                  ...
                  return self
        """
        raise TypeError(f"{self} is not subscriptable")
TypeAlias()
pip._vendor.typing_extensions.TypeAlias (self, parameters)
Special marker indicating that an assignment should
be recognized as a proper type alias definition by type
checkers.
For example::
    Predicate: TypeAlias = Callable[..., bool]
It's invalid when used anywhere except as in the example above.
Definition at line 1417 of file typing_extensions.py.
    def TypeAlias(self, parameters):
        """Special marker indicating that an assignment should
        be recognized as a proper type alias definition by type
        checkers.
        For example::
            Predicate: TypeAlias = Callable[..., bool]
        It's invalid when used anywhere except as in the example above.
        """
        raise TypeError(f"{self} is not subscriptable")
# 3.8
TypedDict()
pip._vendor.typing_extensions.TypedDict (typename, fields = _marker, * , total = True, closed = False, ** kwargs)
A simple typed namespace. At runtime it is equivalent to a plain dict.
TypedDict creates a dictionary type such that a type checker will expect all
instances to have a certain set of keys, where each key is
associated with a value of a consistent type. This expectation
is not checked at runtime.
Usage::
    class Point2D(TypedDict):
        x: int
        y: int
        label: str
    a: Point2D = {'x': 1, 'y': 2, 'label': 'good'}  # OK
    b: Point2D = {'z': 3, 'label': 'bad'}           # Fails type check
    assert Point2D(x=1, y=2, label='first') == dict(x=1, y=2, label='first')
The type info can be accessed via the Point2D.__annotations__ dict, and
the Point2D.__required_keys__ and Point2D.__optional_keys__ frozensets.
TypedDict supports an additional equivalent form::
    Point2D = TypedDict('Point2D', {'x': int, 'y': int, 'label': str})
By default, all keys must be present in a TypedDict. It is possible
to override this by specifying totality::
    class Point2D(TypedDict, total=False):
        x: int
        y: int
This means that a Point2D TypedDict can have any of the keys omitted. A type
checker is only expected to support a literal False or True as the value of
the total argument. True is the default, and makes all items defined in the
class body be required.
The Required and NotRequired special forms can also be used to mark
individual keys as being required or not required::
    class Point2D(TypedDict):
        x: int  # the "x" key must always be present (Required is the default)
        y: NotRequired[int]  # the "y" key can be omitted
See PEP 655 for more details on Required and NotRequired.
Definition at line 1039 of file typing_extensions.py.
    def TypedDict(typename, fields=_marker, /, *, total=True, closed=False, **kwargs):
        """A simple typed namespace. At runtime it is equivalent to a plain dict.
        TypedDict creates a dictionary type such that a type checker will expect all
        instances to have a certain set of keys, where each key is
        associated with a value of a consistent type. This expectation
        is not checked at runtime.
        Usage::
            class Point2D(TypedDict):
                x: int
                y: int
                label: str
            a: Point2D = {'x': 1, 'y': 2, 'label': 'good'}  # OK
            b: Point2D = {'z': 3, 'label': 'bad'}           # Fails type check
            assert Point2D(x=1, y=2, label='first') == dict(x=1, y=2, label='first')
        The type info can be accessed via the Point2D.__annotations__ dict, and
        the Point2D.__required_keys__ and Point2D.__optional_keys__ frozensets.
        TypedDict supports an additional equivalent form::
            Point2D = TypedDict('Point2D', {'x': int, 'y': int, 'label': str})
        By default, all keys must be present in a TypedDict. It is possible
        to override this by specifying totality::
            class Point2D(TypedDict, total=False):
                x: int
                y: int
        This means that a Point2D TypedDict can have any of the keys omitted. A type
        checker is only expected to support a literal False or True as the value of
        the total argument. True is the default, and makes all items defined in the
        class body be required.
        The Required and NotRequired special forms can also be used to mark
        individual keys as being required or not required::
            class Point2D(TypedDict):
                x: int  # the "x" key must always be present (Required is the default)
                y: NotRequired[int]  # the "y" key can be omitted
        See PEP 655 for more details on Required and NotRequired.
        """
        if fields is _marker or fields is None:
            if fields is _marker:
                deprecated_thing = "Failing to pass a value for the 'fields' parameter"
            else:
                deprecated_thing = "Passing `None` as the 'fields' parameter"
            example = f"`{typename} = TypedDict({typename!r}, {{}})`"
            deprecation_msg = (
                f"{deprecated_thing} is deprecated and will be disallowed in "
                "Python 3.15. To create a TypedDict class with 0 fields "
                "using the functional syntax, pass an empty dictionary, e.g. "
            ) + example + "."
            warnings.warn(deprecation_msg, DeprecationWarning, stacklevel=2)
            if closed is not False and closed is not True:
                kwargs["closed"] = closed
                closed = False
            fields = kwargs
        elif kwargs:
            raise TypeError("TypedDict takes either a dict or keyword arguments,"
                            " but not both")
        if kwargs:
            if sys.version_info >= (3, 13):
                raise TypeError("TypedDict takes no keyword arguments")
            warnings.warn(
                "The kwargs-based syntax for TypedDict definitions is deprecated "
                "in Python 3.11, will be removed in Python 3.13, and may not be "
                "understood by third-party type checkers.",
                DeprecationWarning,
                stacklevel=2,
            )
        ns = {'__annotations__': dict(fields)}
        module = _caller()
        if module is not None:
            # Setting correct module is necessary to make typed dict classes pickleable.
            ns['__module__'] = module
        td = _TypedDictMeta(typename, (), ns, total=total, closed=closed)
        td.__orig_bases__ = (TypedDict,)
        return td
References _caller().
TypeGuard()
pip._vendor.typing_extensions.TypeGuard (self, parameters)
Special typing form used to annotate the return type of a user-defined
type guard function.  ``TypeGuard`` only accepts a single type argument.
At runtime, functions marked this way should return a boolean.
``TypeGuard`` aims to benefit *type narrowing* -- a technique used by static
type checkers to determine a more precise type of an expression within a
program's code flow.  Usually type narrowing is done by analyzing
conditional code flow and applying the narrowing to a block of code.  The
conditional expression here is sometimes referred to as a "type guard".
Sometimes it would be convenient to use a user-defined boolean function
as a type guard.  Such a function should use ``TypeGuard[...]`` as its
return type to alert static type checkers to this intention.
Using  ``-> TypeGuard`` tells the static type checker that for a given
function:
1. The return value is a boolean.
2. If the return value is ``True``, the type of its argument
is the type inside ``TypeGuard``.
For example::
    def is_str(val: Union[str, float]):
        # "isinstance" type guard
        if isinstance(val, str):
            # Type of ``val`` is narrowed to ``str``
            ...
        else:
            # Else, type of ``val`` is narrowed to ``float``.
            ...
Strict type narrowing is not enforced -- ``TypeB`` need not be a narrower
form of ``TypeA`` (it can even be a wider form) and this may lead to
type-unsafe results.  The main reason is to allow for things like
narrowing ``List[object]`` to ``List[str]`` even though the latter is not
a subtype of the former, since ``List`` is invariant.  The responsibility of
writing type-safe type guards is left to the user.
``TypeGuard`` also works with type variables.  For more information, see
PEP 647 (User-Defined Type Guards).
Definition at line 1855 of file typing_extensions.py.
    def TypeGuard(self, parameters):
        """Special typing form used to annotate the return type of a user-defined
        type guard function.  ``TypeGuard`` only accepts a single type argument.
        At runtime, functions marked this way should return a boolean.
        ``TypeGuard`` aims to benefit *type narrowing* -- a technique used by static
        type checkers to determine a more precise type of an expression within a
        program's code flow.  Usually type narrowing is done by analyzing
        conditional code flow and applying the narrowing to a block of code.  The
        conditional expression here is sometimes referred to as a "type guard".
        Sometimes it would be convenient to use a user-defined boolean function
        as a type guard.  Such a function should use ``TypeGuard[...]`` as its
        return type to alert static type checkers to this intention.
        Using  ``-> TypeGuard`` tells the static type checker that for a given
        function:
        1. The return value is a boolean.
        2. If the return value is ``True``, the type of its argument
        is the type inside ``TypeGuard``.
        For example::
            def is_str(val: Union[str, float]):
                # "isinstance" type guard
                if isinstance(val, str):
                    # Type of ``val`` is narrowed to ``str``
                    ...
                else:
                    # Else, type of ``val`` is narrowed to ``float``.
                    ...
        Strict type narrowing is not enforced -- ``TypeB`` need not be a narrower
        form of ``TypeA`` (it can even be a wider form) and this may lead to
        type-unsafe results.  The main reason is to allow for things like
        narrowing ``List[object]`` to ``List[str]`` even though the latter is not
        a subtype of the former, since ``List`` is invariant.  The responsibility of
        writing type-safe type guards is left to the user.
        ``TypeGuard`` also works with type variables.  For more information, see
        PEP 647 (User-Defined Type Guards).
        """
        item = typing._type_check(parameters, f'{self} accepts only a single type.')
        return typing._GenericAlias(self, (item,))
# 3.8
TypeIs()
pip._vendor.typing_extensions.TypeIs (self, parameters)
Special typing form used to annotate the return type of a user-defined
type narrower function.  ``TypeIs`` only accepts a single type argument.
At runtime, functions marked this way should return a boolean.
``TypeIs`` aims to benefit *type narrowing* -- a technique used by static
type checkers to determine a more precise type of an expression within a
program's code flow.  Usually type narrowing is done by analyzing
conditional code flow and applying the narrowing to a block of code.  The
conditional expression here is sometimes referred to as a "type guard".
Sometimes it would be convenient to use a user-defined boolean function
as a type guard.  Such a function should use ``TypeIs[...]`` as its
return type to alert static type checkers to this intention.
Using  ``-> TypeIs`` tells the static type checker that for a given
function:
1. The return value is a boolean.
2. If the return value is ``True``, the type of its argument
is the intersection of the type inside ``TypeGuard`` and the argument's
previously known type.
For example::
    def is_awaitable(val: object) -> TypeIs[Awaitable[Any]]:
        return hasattr(val, '__await__')
    def f(val: Union[int, Awaitable[int]]) -> int:
        if is_awaitable(val):
            assert_type(val, Awaitable[int])
        else:
            assert_type(val, int)
``TypeIs`` also works with type variables.  For more information, see
PEP 742 (Narrowing types with TypeIs).
Definition at line 1959 of file typing_extensions.py.
    def TypeIs(self, parameters):
        """Special typing form used to annotate the return type of a user-defined
        type narrower function.  ``TypeIs`` only accepts a single type argument.
        At runtime, functions marked this way should return a boolean.
        ``TypeIs`` aims to benefit *type narrowing* -- a technique used by static
        type checkers to determine a more precise type of an expression within a
        program's code flow.  Usually type narrowing is done by analyzing
        conditional code flow and applying the narrowing to a block of code.  The
        conditional expression here is sometimes referred to as a "type guard".
        Sometimes it would be convenient to use a user-defined boolean function
        as a type guard.  Such a function should use ``TypeIs[...]`` as its
        return type to alert static type checkers to this intention.
        Using  ``-> TypeIs`` tells the static type checker that for a given
        function:
        1. The return value is a boolean.
        2. If the return value is ``True``, the type of its argument
        is the intersection of the type inside ``TypeGuard`` and the argument's
        previously known type.
        For example::
            def is_awaitable(val: object) -> TypeIs[Awaitable[Any]]:
                return hasattr(val, '__await__')
            def f(val: Union[int, Awaitable[int]]) -> int:
                if is_awaitable(val):
                    assert_type(val, Awaitable[int])
                else:
                    assert_type(val, int)
        ``TypeIs`` also works with type variables.  For more information, see
        PEP 742 (Narrowing types with TypeIs).
        """
        item = typing._type_check(parameters, f'{self} accepts only a single type.')
        return typing._GenericAlias(self, (item,))
# 3.8
Unpack()
pip._vendor.typing_extensions.Unpack (self, parameters)
Definition at line 2361 of file typing_extensions.py.
    def Unpack(self, parameters):
        item = typing._type_check(parameters, f'{self._name} accepts only a single type.')
        return _UnpackAlias(self, (item,))
Variable Documentation
_AnnotatedAlias
pip._vendor.typing_extensions._AnnotatedAlias = typing._AnnotatedAlias protected
Definition at line 1245 of file typing_extensions.py.
_ASSERT_NEVER_REPR_MAX_LENGTH
int pip._vendor.typing_extensions._ASSERT_NEVER_REPR_MAX_LENGTH = typing._ASSERT_NEVER_REPR_MAX_LENGTH protected
Definition at line 2564 of file typing_extensions.py.
_BaseGenericAlias
pip._vendor.typing_extensions._BaseGenericAlias = typing._GenericAlias protected
Definition at line 1357 of file typing_extensions.py.
_CAPI
pip._vendor.typing_extensions._CAPI = getattr(_socket, "CAPI", None) protected
Definition at line 3593 of file typing_extensions.py.
_CapsuleType
pip._vendor.typing_extensions._CapsuleType = getattr(_types, "CapsuleType", None) protected
Definition at line 3585 of file typing_extensions.py.
_check_generic
pip._vendor.typing_extensions._check_generic protected
Check correct count for parameters of a generic cls (internal helper).
This gives a nice error message in case of count mismatch.
Definition at line 2951 of file typing_extensions.py.
_collect_parameters
pip._vendor.typing_extensions._collect_parameters protected
Definition at line 3086 of file typing_extensions.py.
Referenced by _collect_parameters().
_collect_type_vars
pip._vendor.typing_extensions._collect_type_vars protected
Definition at line 3027 of file typing_extensions.py.
_ConcatenateGenericAlias
pip._vendor.typing_extensions._ConcatenateGenericAlias = typing._ConcatenateGenericAlias protected
Definition at line 1814 of file typing_extensions.py.
_EXCLUDED_ATTRS
pip._vendor.typing_extensions._EXCLUDED_ATTRS protected
Initial value:
=  frozenset(typing.EXCLUDED_ATTRIBUTES) | {
    "__match_args__", "__protocol_attrs__", "__non_callable_proto_members__",
    "__final__",
}
Definition at line 512 of file typing_extensions.py.
_F
pip._vendor.typing_extensions._F = typing.TypeVar("_F", bound=typing.Callable[..., typing.Any]) protected
Definition at line 2691 of file typing_extensions.py.
_is_runtime_protocol
bool pip._vendor.typing_extensions._is_runtime_protocol = True protected
Definition at line 744 of file typing_extensions.py.
_marker
pip._vendor.typing_extensions._marker = _Sentinel() protected
Definition at line 150 of file typing_extensions.py.
_NamedTuple
pip._vendor.typing_extensions._NamedTuple protected
Definition at line 3182 of file typing_extensions.py.
_NoneType
pip._vendor.typing_extensions._NoneType protected
Definition at line 481 of file typing_extensions.py.
_overload_dummy
pip._vendor.typing_extensions._overload_dummy = typing._overload_dummy protected
Definition at line 333 of file typing_extensions.py.
_overload_registry
pip._vendor.typing_extensions._overload_registry protected
Initial value:
=  collections.defaultdict(
        functools.partial(collections.defaultdict, dict)
    )
Definition at line 342 of file typing_extensions.py.
_PEP_696_IMPLEMENTED
tuple pip._vendor.typing_extensions._PEP_696_IMPLEMENTED = (3, 13, 0, "beta") protected
Definition at line 139 of file typing_extensions.py.
_PEP_728_IMPLEMENTED
bool pip._vendor.typing_extensions._PEP_728_IMPLEMENTED = False protected
Definition at line 872 of file typing_extensions.py.
_prohibited_namedtuple_fields
pip._vendor.typing_extensions._prohibited_namedtuple_fields = typing._prohibited protected
Definition at line 3109 of file typing_extensions.py.
_PROTO_ALLOWLIST
dict pip._vendor.typing_extensions._PROTO_ALLOWLIST protected
Initial value:
=  {
    'collections.abc': [
        'Callable', 'Awaitable', 'Iterable', 'Iterator', 'AsyncIterable',
        'Hashable', 'Sized', 'Container', 'Collection', 'Reversible', 'Buffer',
    ],
    'contextlib': ['AbstractContextManager', 'AbstractAsyncContextManager'],
    'typing_extensions': ['Buffer'],
}
Definition at line 502 of file typing_extensions.py.
_special_generic_alias_base
pip._vendor.typing_extensions._special_generic_alias_base protected
Initial value:
=  getattr(
        typing, "_SpecialGenericAlias", typing._GenericAlias
    )
Definition at line 427 of file typing_extensions.py.
_special_namedtuple_fields
pip._vendor.typing_extensions._special_namedtuple_fields = frozenset({'__module__', '__name__', '__annotations__'}) protected
Definition at line 3110 of file typing_extensions.py.
_T
pip._vendor.typing_extensions._T = typing.TypeVar("_T") protected
Definition at line 2732 of file typing_extensions.py.
_TAKES_MODULE
str pip._vendor.typing_extensions._TAKES_MODULE = "module" in inspect.signature(typing._type_check).parameters protected
Definition at line 892 of file typing_extensions.py.
_TypedDict
pip._vendor.typing_extensions._TypedDict protected
Definition at line 1036 of file typing_extensions.py.
_TYPEDDICT_TYPES
tuple pip._vendor.typing_extensions._TYPEDDICT_TYPES = (typing._TypedDictMeta, _TypedDictMeta) protected
Definition at line 1128 of file typing_extensions.py.
_TypedDictMeta
pip._vendor.typing_extensions._TypedDictMeta = typing._TypedDictMeta protected
Definition at line 888 of file typing_extensions.py.
_TYPEVARTUPLE_TYPES
dict pip._vendor.typing_extensions._TYPEVARTUPLE_TYPES = {TypeVarTuple, getattr(typing, "TypeVarTuple", None)} protected
Definition at line 2973 of file typing_extensions.py.
_typing_GenericAlias
pip._vendor.typing_extensions._typing_GenericAlias = typing._GenericAlias protected
Definition at line 1362 of file typing_extensions.py.
_UNPACK_DOC
str pip._vendor.typing_extensions._UNPACK_DOC protected
Definition at line 2292 of file typing_extensions.py.
AbstractSet
pip._vendor.typing_extensions.AbstractSet = typing.AbstractSet
Definition at line 3606 of file typing_extensions.py.
Annotated
pip._vendor.typing_extensions.Annotated = typing.Annotated
Definition at line 1242 of file typing_extensions.py.
AnyStr
pip._vendor.typing_extensions.AnyStr = typing.AnyStr
Definition at line 3607 of file typing_extensions.py.
assert_never
pip._vendor.typing_extensions.assert_never = typing.assert_never
Definition at line 2570 of file typing_extensions.py.
assert_type
pip._vendor.typing_extensions.assert_type = typing.assert_type
Definition at line 1150 of file typing_extensions.py.
AsyncContextManager
pip._vendor.typing_extensions.AsyncContextManager
Initial value:
=  _SpecialGenericAlias(
        contextlib.AbstractAsyncContextManager,
        2,
        name="AsyncContextManager",
        defaults=(typing.Optional[bool],)
    )
Definition at line 494 of file typing_extensions.py.
AsyncGenerator
pip._vendor.typing_extensions.AsyncGenerator
Initial value:
=  _SpecialGenericAlias(
        collections.abc.AsyncGenerator, 2, defaults=(_NoneType,)
    )
Definition at line 485 of file typing_extensions.py.
AsyncIterable
pip._vendor.typing_extensions.AsyncIterable = typing.AsyncIterable
Definition at line 409 of file typing_extensions.py.
AsyncIterator
pip._vendor.typing_extensions.AsyncIterator = typing.AsyncIterator
Definition at line 410 of file typing_extensions.py.
Awaitable
pip._vendor.typing_extensions.Awaitable = typing.Awaitable
Definition at line 407 of file typing_extensions.py.
BinaryIO
pip._vendor.typing_extensions.BinaryIO = typing.BinaryIO
Definition at line 3608 of file typing_extensions.py.
Buffer
pip._vendor.typing_extensions.Buffer = collections.abc.Buffer
Definition at line 3256 of file typing_extensions.py.
Callable
pip._vendor.typing_extensions.Callable = typing.Callable
Definition at line 3609 of file typing_extensions.py.
CapsuleType
pip._vendor.typing_extensions.CapsuleType = _CapsuleType
Definition at line 3598 of file typing_extensions.py.
cast
pip._vendor.typing_extensions.cast = typing.cast
Definition at line 3639 of file typing_extensions.py.
ChainMap
pip._vendor.typing_extensions.ChainMap = typing.ChainMap
Definition at line 415 of file typing_extensions.py.
ClassVar
pip._vendor.typing_extensions.ClassVar = typing.ClassVar
Definition at line 207 of file typing_extensions.py.
clear_overloads
pip._vendor.typing_extensions.clear_overloads () = typing.clear_overloads
Clear all overloads in the registry.
Definition at line 339 of file typing_extensions.py.
Collection
pip._vendor.typing_extensions.Collection = typing.Collection
Definition at line 3610 of file typing_extensions.py.
Concatenate
pip._vendor.typing_extensions.Concatenate = typing.Concatenate
Definition at line 1813 of file typing_extensions.py.
Container
pip._vendor.typing_extensions.Container = typing.Container
Definition at line 3611 of file typing_extensions.py.
ContextManager
pip._vendor.typing_extensions.ContextManager
Initial value:
=  _SpecialGenericAlias(
        contextlib.AbstractContextManager,
        2,
        name="ContextManager",
        defaults=(typing.Optional[bool],)
    )
Definition at line 488 of file typing_extensions.py.
Coroutine
pip._vendor.typing_extensions.Coroutine = typing.Coroutine
Definition at line 408 of file typing_extensions.py.
Counter
pip._vendor.typing_extensions.Counter = typing.Counter
Definition at line 414 of file typing_extensions.py.
dataclass_transform
pip._vendor.typing_extensions.dataclass_transform = typing.dataclass_transform
Definition at line 2600 of file typing_extensions.py.
DefaultDict
pip._vendor.typing_extensions.DefaultDict = typing.DefaultDict
Definition at line 412 of file typing_extensions.py.
deprecated
pip._vendor.typing_extensions.deprecated = warnings.deprecated
Definition at line 2730 of file typing_extensions.py.
Deque
pip._vendor.typing_extensions.Deque = typing.Deque
Definition at line 411 of file typing_extensions.py.
Dict
pip._vendor.typing_extensions.Dict = typing.Dict
Definition at line 3612 of file typing_extensions.py.
Doc
pip._vendor.typing_extensions.Doc = typing.Doc
Definition at line 3551 of file typing_extensions.py.
doc
pip._vendor.typing_extensions.doc
Definition at line 318 of file typing_extensions.py.
Final
pip._vendor.typing_extensions.Final = typing.Final
Definition at line 215 of file typing_extensions.py.
final
pip._vendor.typing_extensions.final = typing.final
Definition at line 218 of file typing_extensions.py.
ForwardRef
pip._vendor.typing_extensions.ForwardRef = typing.ForwardRef
Definition at line 3613 of file typing_extensions.py.
FrozenSet
pip._vendor.typing_extensions.FrozenSet = typing.FrozenSet
Definition at line 3614 of file typing_extensions.py.
Generator
pip._vendor.typing_extensions.Generator
Initial value:
=  _SpecialGenericAlias(
        collections.abc.Generator, 3, defaults=(_NoneType, _NoneType)
    )
Definition at line 482 of file typing_extensions.py.
Generic
pip._vendor.typing_extensions.Generic = typing.Generic
Definition at line 3615 of file typing_extensions.py.
GenericMeta
pip._vendor.typing_extensions.GenericMeta = type
Definition at line 138 of file typing_extensions.py.
get_args
pip._vendor.typing_extensions.get_args = typing.get_args
Definition at line 1350 of file typing_extensions.py.
Referenced by _get_typeddict_qualifiers(), and _is_unpacked_typevartuple().
get_origin
pip._vendor.typing_extensions.get_origin = typing.get_origin
Definition at line 1349 of file typing_extensions.py.
Referenced by pip._vendor.typing_extensions.Annotated.__class_getitem__(), _get_typeddict_qualifiers(), _is_unpack(), _is_unpacked_typevartuple(), and get_args().
get_original_bases
pip._vendor.typing_extensions.get_original_bases = _types.get_original_bases
Definition at line 3286 of file typing_extensions.py.
get_overloads
pip._vendor.typing_extensions.get_overloads = typing.get_overloads
Definition at line 338 of file typing_extensions.py.
get_protocol_members
pip._vendor.typing_extensions.get_protocol_members = typing.get_protocol_members
Definition at line 3506 of file typing_extensions.py.
get_type_hints
pip._vendor.typing_extensions.get_type_hints = typing.get_type_hints
Definition at line 1170 of file typing_extensions.py.
Hashable
pip._vendor.typing_extensions.Hashable = typing.Hashable
Definition at line 3616 of file typing_extensions.py.
IO
pip._vendor.typing_extensions.IO = typing.IO
Definition at line 3617 of file typing_extensions.py.
is_protocol
pip._vendor.typing_extensions.is_protocol = typing.is_protocol
Definition at line 3505 of file typing_extensions.py.
Referenced by pip._vendor.typing_extensions._ProtocolMeta.__new__(), _proto_hook(), and get_protocol_members().
is_typeddict
pip._vendor.typing_extensions.is_typeddict = typing.is_typeddict
Definition at line 889 of file typing_extensions.py.
ItemsView
pip._vendor.typing_extensions.ItemsView = typing.ItemsView
Definition at line 3618 of file typing_extensions.py.
Iterable
pip._vendor.typing_extensions.Iterable = typing.Iterable
Definition at line 3619 of file typing_extensions.py.
Iterator
pip._vendor.typing_extensions.Iterator = typing.Iterator
Definition at line 3620 of file typing_extensions.py.
KeysView
pip._vendor.typing_extensions.KeysView = typing.KeysView
Definition at line 3621 of file typing_extensions.py.
KT
pip._vendor.typing_extensions.KT = typing.TypeVar('KT')
Definition at line 171 of file typing_extensions.py.
List
pip._vendor.typing_extensions.List = typing.List
Definition at line 3622 of file typing_extensions.py.
Literal
pip._vendor.typing_extensions.Literal = typing.Literal
Definition at line 261 of file typing_extensions.py.
LiteralString
pip._vendor.typing_extensions.LiteralString = typing.LiteralString
Definition at line 2091 of file typing_extensions.py.
Mapping
pip._vendor.typing_extensions.Mapping = typing.Mapping
Definition at line 3623 of file typing_extensions.py.
MappingView
pip._vendor.typing_extensions.MappingView = typing.MappingView
Definition at line 3624 of file typing_extensions.py.
Match
pip._vendor.typing_extensions.Match = typing.Match
Definition at line 3625 of file typing_extensions.py.
MutableMapping
pip._vendor.typing_extensions.MutableMapping = typing.MutableMapping
Definition at line 3626 of file typing_extensions.py.
MutableSequence
pip._vendor.typing_extensions.MutableSequence = typing.MutableSequence
Definition at line 3627 of file typing_extensions.py.
MutableSet
pip._vendor.typing_extensions.MutableSet = typing.MutableSet
Definition at line 3628 of file typing_extensions.py.
NamedTuple
pip._vendor.typing_extensions.NamedTuple = typing.NamedTuple
Definition at line 3094 of file typing_extensions.py.
Never
pip._vendor.typing_extensions.Never = typing.Never
Definition at line 2135 of file typing_extensions.py.
NewType
pip._vendor.typing_extensions.NewType = typing.NewType
Definition at line 3320 of file typing_extensions.py.
no_type_check
pip._vendor.typing_extensions.no_type_check = typing.no_type_check
Definition at line 3640 of file typing_extensions.py.
no_type_check_decorator
pip._vendor.typing_extensions.no_type_check_decorator = typing.no_type_check_decorator
Definition at line 3641 of file typing_extensions.py.
NoDefault
pip._vendor.typing_extensions.NoDefault = typing.NoDefault
Definition at line 1447 of file typing_extensions.py.
NoReturn
pip._vendor.typing_extensions.NoReturn = typing.NoReturn
Definition at line 166 of file typing_extensions.py.
NotRequired
pip._vendor.typing_extensions.NotRequired = typing.NotRequired
Definition at line 2166 of file typing_extensions.py.
Optional
pip._vendor.typing_extensions.Optional = typing.Optional
Definition at line 3629 of file typing_extensions.py.
OrderedDict
pip._vendor.typing_extensions.OrderedDict = typing.OrderedDict
Definition at line 413 of file typing_extensions.py.
overload
pip._vendor.typing_extensions.overload = typing.overload
Definition at line 337 of file typing_extensions.py.
override
pip._vendor.typing_extensions.override = typing.override
Definition at line 2689 of file typing_extensions.py.
ParamSpecArgs
pip._vendor.typing_extensions.ParamSpecArgs = typing.ParamSpecArgs
Definition at line 1543 of file typing_extensions.py.
ParamSpecKwargs
pip._vendor.typing_extensions.ParamSpecKwargs = typing.ParamSpecKwargs
Definition at line 1544 of file typing_extensions.py.
Pattern
pip._vendor.typing_extensions.Pattern = typing.Pattern
Definition at line 3630 of file typing_extensions.py.
PEP_560
bool pip._vendor.typing_extensions.PEP_560 = True
Definition at line 137 of file typing_extensions.py.
Protocol
pip._vendor.typing_extensions.Protocol = typing.Protocol
Definition at line 540 of file typing_extensions.py.
ReadOnly
pip._vendor.typing_extensions.ReadOnly = typing.ReadOnly
Definition at line 2246 of file typing_extensions.py.
Required
pip._vendor.typing_extensions.Required = typing.Required
Definition at line 2165 of file typing_extensions.py.
reveal_type
pip._vendor.typing_extensions.reveal_type = typing.reveal_type
Definition at line 2541 of file typing_extensions.py.
Reversible
pip._vendor.typing_extensions.Reversible = typing.Reversible
Definition at line 3631 of file typing_extensions.py.
runtime
pip._vendor.typing_extensions.runtime = runtime_checkable
Definition at line 775 of file typing_extensions.py.
runtime_checkable
pip._vendor.typing_extensions.runtime_checkable = typing.runtime_checkable
Definition at line 720 of file typing_extensions.py.
Self
pip._vendor.typing_extensions.Self = typing.Self
Definition at line 2114 of file typing_extensions.py.
Sequence
pip._vendor.typing_extensions.Sequence = typing.Sequence
Definition at line 3632 of file typing_extensions.py.
Set
pip._vendor.typing_extensions.Set = typing.Set
Definition at line 3633 of file typing_extensions.py.
Sized
pip._vendor.typing_extensions.Sized = typing.Sized
Definition at line 3634 of file typing_extensions.py.
SupportsAbs
pip._vendor.typing_extensions.SupportsAbs = typing.SupportsAbs
Definition at line 785 of file typing_extensions.py.
SupportsBytes
pip._vendor.typing_extensions.SupportsBytes = typing.SupportsBytes
Definition at line 783 of file typing_extensions.py.
SupportsComplex
pip._vendor.typing_extensions.SupportsComplex = typing.SupportsComplex
Definition at line 782 of file typing_extensions.py.
SupportsFloat
pip._vendor.typing_extensions.SupportsFloat = typing.SupportsFloat
Definition at line 781 of file typing_extensions.py.
SupportsIndex
pip._vendor.typing_extensions.SupportsIndex = typing.SupportsIndex
Definition at line 784 of file typing_extensions.py.
SupportsInt
pip._vendor.typing_extensions.SupportsInt = typing.SupportsInt
Definition at line 780 of file typing_extensions.py.
SupportsRound
pip._vendor.typing_extensions.SupportsRound = typing.SupportsRound
Definition at line 786 of file typing_extensions.py.
T
pip._vendor.typing_extensions.T = typing.TypeVar('T')
Definition at line 170 of file typing_extensions.py.
T_co
pip._vendor.typing_extensions.T_co = typing.TypeVar('T_co', covariant=True)
Definition at line 173 of file typing_extensions.py.
T_contra
pip._vendor.typing_extensions.T_contra = typing.TypeVar('T_contra', contravariant=True)
Definition at line 174 of file typing_extensions.py.
Text
pip._vendor.typing_extensions.Text = typing.Text
Definition at line 416 of file typing_extensions.py.
TextIO
pip._vendor.typing_extensions.TextIO = typing.TextIO
Definition at line 3635 of file typing_extensions.py.
Tuple
pip._vendor.typing_extensions.Tuple = typing.Tuple
Definition at line 3636 of file typing_extensions.py.
Type
pip._vendor.typing_extensions.Type = typing.Type
Definition at line 403 of file typing_extensions.py.
TYPE_CHECKING
pip._vendor.typing_extensions.TYPE_CHECKING = typing.TYPE_CHECKING
Definition at line 417 of file typing_extensions.py.
TypeAlias
pip._vendor.typing_extensions.TypeAlias = typing.TypeAlias
Definition at line 1413 of file typing_extensions.py.
TypeAliasType
pip._vendor.typing_extensions.TypeAliasType = typing.TypeAliasType
Definition at line 3383 of file typing_extensions.py.
TypedDict
pip._vendor.typing_extensions.TypedDict = typing.TypedDict
Definition at line 887 of file typing_extensions.py.
TypeGuard
pip._vendor.typing_extensions.TypeGuard = typing.TypeGuard
Definition at line 1851 of file typing_extensions.py.
TypeIs
pip._vendor.typing_extensions.TypeIs = typing.TypeIs
Definition at line 1955 of file typing_extensions.py.
Union
pip._vendor.typing_extensions.Union = typing.Union
Definition at line 3637 of file typing_extensions.py.
Unpack
pip._vendor.typing_extensions.Unpack = typing.Unpack
Definition at line 2335 of file typing_extensions.py.
ValuesView
pip._vendor.typing_extensions.ValuesView = typing.ValuesView
Definition at line 3638 of file typing_extensions.py.
VT
pip._vendor.typing_extensions.VT = typing.TypeVar('VT')
Definition at line 172 of file typing_extensions.py.