Read&Watch: dill.tests.test_dictviews Namespace Reference
dill.tests.test_dictviews Namespace Reference
Functions
test_dictproxy ()
test_dictviews ()
test_dictproxy_trick ()
Function Documentation
test_dictproxy()
dill.tests.test_dictviews.test_dictproxy ()
Definition at line 12 of file test_dictviews.py.
def test_dictproxy():
    assert dill.copy(DictProxyType({'a': 2}))
Referenced by test_dictproxy_trick().
test_dictproxy_trick()
dill.tests.test_dictviews.test_dictproxy_trick ()
Definition at line 21 of file test_dictviews.py.
def test_dictproxy_trick():
    if not OLD310 and MAPPING_PROXY_TRICK:
        x = {'a': 1}
        all_views = (x.values(), x.items(), x.keys(), x)
        seperate_views = dill.copy(all_views)
        new_x = seperate_views[-1]
        new_x['b'] = 2
        new_x['c'] = 1
        assert len(new_x) == 3 and len(x) == 1
        assert len(seperate_views[0]) == 3 and len(all_views[0]) == 1
        assert len(seperate_views[1]) == 3 and len(all_views[1]) == 1
        assert len(seperate_views[2]) == 3 and len(all_views[2]) == 1
        assert dict(all_views[1]) == x
        assert dict(seperate_views[1]) == new_x
References test_dictproxy(), test_dictproxy_trick(), and test_dictviews().
Referenced by test_dictproxy_trick().
test_dictviews()
dill.tests.test_dictviews.test_dictviews ()
Definition at line 15 of file test_dictviews.py.
def test_dictviews():
    x = {'a': 1}
    assert dill.copy(x.keys())
    assert dill.copy(x.values())
    assert dill.copy(x.items())
Referenced by test_dictproxy_trick().