Read&Watch: tomlkit.container Namespace Reference
tomlkit.container Namespace Reference
Classes
class Container
class OutOfOrderTableProxy
Functions
bool ends_with_whitespace (Any it)
Variables
_NOT_SET = object()
Function Documentation
ends_with_whitespace()
bool tomlkit.container.ends_with_whitespace (Any it)
Returns ``True`` if the given item ``it`` is a ``Table`` or ``AoT`` object
ending with a ``Whitespace``.
Definition at line 888 of file container.py.
def ends_with_whitespace(it: Any) -> bool:
    """Returns ``True`` if the given item ``it`` is a ``Table`` or ``AoT`` object
    ending with a ``Whitespace``.
    """
    return (
        isinstance(it, Table) and isinstance(it.value._previous_item(), Whitespace)
    ) or (isinstance(it, AoT) and len(it) > 0 and isinstance(it[-1], Whitespace))
Referenced by tomlkit.container.Container._insert_at(), tomlkit.container.Container._replace_at(), and tomlkit.container.Container.append().
Variable Documentation
_NOT_SET
tomlkit.container._NOT_SET = object() protected
Definition at line 26 of file container.py.