Read&Watch: django.db.backends.postgresql.psycopg_any Namespace Reference
django.db.backends.postgresql.psycopg_any Namespace Reference
Classes
class BaseTzLoader
class DjangoRangeDumper
class IsolationLevel
class Jsonb
Functions
mogrify (sql, params, connection)
register_tzloader (tz, context)
get_adapters_template (use_tz, timezone)
_quote (value, connection=None)
Variables
Inet = ipaddress.ip_address
DateRange = Range
tuple RANGE_TYPES = (Range,)
TSRANGE_OID = types["tsrange"].oid
TSTZRANGE_OID = types["tstzrange"].oid
bool is_psycopg3 = True
quote
Function Documentation
_quote()
django.db.backends.postgresql.psycopg_any._quote (value, connection = None) protected
Definition at line 96 of file psycopg_any.py.
    def _quote(value, connection=None):
        adapted = extensions.adapt(value)
        if hasattr(adapted, "encoding"):
            adapted.encoding = "utf8"
        # getquoted() returns a quoted bytestring of the adapted value.
        return adapted.getquoted().decode()
get_adapters_template()
django.db.backends.postgresql.psycopg_any.get_adapters_template (use_tz, timezone)
Definition at line 55 of file psycopg_any.py.
    def get_adapters_template(use_tz, timezone):
        # Create at adapters map extending the base one.
        ctx = adapt.AdaptersMap(adapters)
        # Register a no-op dumper to avoid a round trip from psycopg version 3
        # decode to json.dumps() to json.loads(), when using a custom decoder
        # in JSONField.
        ctx.register_loader("jsonb", TextLoader)
        # Don't convert automatically from PostgreSQL network types to Python
        # ipaddress.
        ctx.register_loader("inet", TextLoader)
        ctx.register_loader("cidr", TextLoader)
        ctx.register_dumper(Range, DjangoRangeDumper)
        # Register a timestamptz loader configured on self.timezone.
        # This, however, can be overridden by create_cursor.
        register_tzloader(timezone, ctx)
        return ctx
References register_tzloader().
mogrify()
django.db.backends.postgresql.psycopg_any.mogrify (sql, params, connection)
Definition at line 20 of file psycopg_any.py.
    def mogrify(sql, params, connection):
        with connection.cursor() as cursor:
            return ClientCursor(cursor.connection).mogrify(sql, params)
References mogrify().
Referenced by mogrify().
register_tzloader()
django.db.backends.postgresql.psycopg_any.register_tzloader (tz, context)
Definition at line 37 of file psycopg_any.py.
    def register_tzloader(tz, context):
        class SpecificTzLoader(BaseTzLoader):
            timezone = tz
        context.adapters.register_loader("timestamptz", SpecificTzLoader)
Referenced by get_adapters_template().
Variable Documentation
DateRange
django.db.backends.postgresql.psycopg_any.DateRange = Range
Definition at line 14 of file psycopg_any.py.
Inet
django.db.backends.postgresql.psycopg_any.Inet = ipaddress.ip_address
Definition at line 12 of file psycopg_any.py.
is_psycopg3
bool django.db.backends.postgresql.psycopg_any.is_psycopg3 = True
Definition at line 72 of file psycopg_any.py.
quote
django.db.backends.postgresql.psycopg_any.quote
Definition at line 103 of file psycopg_any.py.
RANGE_TYPES
tuple django.db.backends.postgresql.psycopg_any.RANGE_TYPES = (Range,)
Definition at line 15 of file psycopg_any.py.
TSRANGE_OID
django.db.backends.postgresql.psycopg_any.TSRANGE_OID = types["tsrange"].oid
Definition at line 17 of file psycopg_any.py.
TSTZRANGE_OID
django.db.backends.postgresql.psycopg_any.TSTZRANGE_OID = types["tstzrange"].oid
Definition at line 18 of file psycopg_any.py.