Read&Watch: pip._vendor.rich._win32_console Namespace Reference
pip._vendor.rich._win32_console Namespace Reference
Classes
class CONSOLE_CURSOR_INFO
class CONSOLE_SCREEN_BUFFER_INFO
class LegacyWindowsError
class LegacyWindowsTerm
class WindowsCoordinates
Functions
wintypes.HANDLE GetStdHandle (int handle=STDOUT)
int GetConsoleMode (wintypes.HANDLE std_handle)
int FillConsoleOutputCharacter (wintypes.HANDLE std_handle, str char, int length, WindowsCoordinates start)
int FillConsoleOutputAttribute (wintypes.HANDLE std_handle, int attributes, int length, WindowsCoordinates start)
bool SetConsoleTextAttribute (wintypes.HANDLE std_handle, wintypes.WORD attributes)
CONSOLE_SCREEN_BUFFER_INFO GetConsoleScreenBufferInfo (wintypes.HANDLE std_handle)
bool SetConsoleCursorPosition (wintypes.HANDLE std_handle, WindowsCoordinates coords)
bool GetConsoleCursorInfo (wintypes.HANDLE std_handle, CONSOLE_CURSOR_INFO cursor_info)
bool SetConsoleCursorInfo (wintypes.HANDLE std_handle, CONSOLE_CURSOR_INFO cursor_info)
bool SetConsoleTitle (str title)
Variables
Any windll = None
int STDOUT = -11
int ENABLE_VIRTUAL_TERMINAL_PROCESSING = 4
COORD = wintypes._COORD
Any _GetStdHandle = windll.kernel32.GetStdHandle
argtypes
restype
Any _GetConsoleMode = windll.kernel32.GetConsoleMode
Any _FillConsoleOutputCharacterW = windll.kernel32.FillConsoleOutputCharacterW
Any _FillConsoleOutputAttribute = windll.kernel32.FillConsoleOutputAttribute
Any _SetConsoleTextAttribute = windll.kernel32.SetConsoleTextAttribute
Any _GetConsoleScreenBufferInfo = windll.kernel32.GetConsoleScreenBufferInfo
Any _SetConsoleCursorPosition = windll.kernel32.SetConsoleCursorPosition
Any _GetConsoleCursorInfo = windll.kernel32.GetConsoleCursorInfo
Any _SetConsoleCursorInfo = windll.kernel32.SetConsoleCursorInfo
Any _SetConsoleTitle = windll.kernel32.SetConsoleTitleW
wintypes.HANDLE handle = GetStdHandle()
console = Console()
term = LegacyWindowsTerm(sys.stdout)
style = Style(color="black", bgcolor="red")
heading = Style.parse("black on green")
Detailed Description
Light wrapper around the Win32 Console API - this module should only be imported on Windows
The API that this module wraps is documented at https://docs.microsoft.com/en-us/windows/console/console-functions
Function Documentation
FillConsoleOutputAttribute()
int pip._vendor.rich._win32_console.FillConsoleOutputAttribute (wintypes.HANDLE std_handle, int attributes, int length, WindowsCoordinates start)
Sets the character attributes for a specified number of character cells,
beginning at the specified coordinates in a screen buffer.
Args:
    std_handle (wintypes.HANDLE): A handle to the console input buffer or the console screen buffer.
    attributes (int): Integer value representing the foreground and background colours of the cells.
    length (int): The number of cells to set the output attribute of.
    start (WindowsCoordinates): The coordinates of the first cell whose attributes are to be set.
Returns:
    int: The number of cells whose attributes were actually set.
Definition at line 168 of file _win32_console.py.
) -> int:
    """Sets the character attributes for a specified number of character cells,
    beginning at the specified coordinates in a screen buffer.
    Args:
        std_handle (wintypes.HANDLE): A handle to the console input buffer or the console screen buffer.
        attributes (int): Integer value representing the foreground and background colours of the cells.
        length (int): The number of cells to set the output attribute of.
        start (WindowsCoordinates): The coordinates of the first cell whose attributes are to be set.
    Returns:
        int: The number of cells whose attributes were actually set.
    """
    num_cells = wintypes.DWORD(length)
    style_attrs = wintypes.WORD(attributes)
    num_written = wintypes.DWORD(0)
    _FillConsoleOutputAttribute(
        std_handle, style_attrs, num_cells, start, byref(num_written)
    )
    return num_written.value
References _FillConsoleOutputAttribute.
Referenced by pip._vendor.rich._win32_console.LegacyWindowsTerm.erase_end_of_line(), pip._vendor.rich._win32_console.LegacyWindowsTerm.erase_line(), and pip._vendor.rich._win32_console.LegacyWindowsTerm.erase_start_of_line().
FillConsoleOutputCharacter()
int pip._vendor.rich._win32_console.FillConsoleOutputCharacter (wintypes.HANDLE std_handle, str char, int length, WindowsCoordinates start)
Writes a character to the console screen buffer a specified number of times, beginning at the specified coordinates.
Args:
    std_handle (wintypes.HANDLE): A handle to the console input buffer or the console screen buffer.
    char (str): The character to write. Must be a string of length 1.
    length (int): The number of times to write the character.
    start (WindowsCoordinates): The coordinates to start writing at.
Returns:
    int: The number of characters written.
Definition at line 127 of file _win32_console.py.
) -> int:
    """Writes a character to the console screen buffer a specified number of times, beginning at the specified coordinates.
    Args:
        std_handle (wintypes.HANDLE): A handle to the console input buffer or the console screen buffer.
        char (str): The character to write. Must be a string of length 1.
        length (int): The number of times to write the character.
        start (WindowsCoordinates): The coordinates to start writing at.
    Returns:
        int: The number of characters written.
    """
    character = ctypes.c_char(char.encode())
    num_characters = wintypes.DWORD(length)
    num_written = wintypes.DWORD(0)
    _FillConsoleOutputCharacterW(
        std_handle,
        character,
        num_characters,
        start,
        byref(num_written),
    )
    return num_written.value
References _FillConsoleOutputCharacterW.
Referenced by pip._vendor.rich._win32_console.LegacyWindowsTerm.erase_end_of_line(), pip._vendor.rich._win32_console.LegacyWindowsTerm.erase_line(), and pip._vendor.rich._win32_console.LegacyWindowsTerm.erase_start_of_line().
GetConsoleCursorInfo()
bool pip._vendor.rich._win32_console.GetConsoleCursorInfo (wintypes.HANDLE std_handle, CONSOLE_CURSOR_INFO cursor_info)
Get the cursor info - used to get cursor visibility and width
Args:
    std_handle (wintypes.HANDLE): A handle to the console input buffer or the console screen buffer.
    cursor_info (CONSOLE_CURSOR_INFO): CONSOLE_CURSOR_INFO ctype struct that receives information
        about the console's cursor.
Returns:
      bool: True if the function succeeds, otherwise False.
Definition at line 274 of file _win32_console.py.
) -> bool:
    """Get the cursor info - used to get cursor visibility and width
    Args:
        std_handle (wintypes.HANDLE): A handle to the console input buffer or the console screen buffer.
        cursor_info (CONSOLE_CURSOR_INFO): CONSOLE_CURSOR_INFO ctype struct that receives information
            about the console's cursor.
    Returns:
          bool: True if the function succeeds, otherwise False.
    """
    return bool(_GetConsoleCursorInfo(std_handle, byref(cursor_info)))
References _GetConsoleCursorInfo.
GetConsoleMode()
int pip._vendor.rich._win32_console.GetConsoleMode (wintypes.HANDLE std_handle)
Retrieves the current input mode of a console's input buffer
or the current output mode of a console screen buffer.
Args:
    std_handle (wintypes.HANDLE): A handle to the console input buffer or the console screen buffer.
Raises:
    LegacyWindowsError: If any error occurs while calling the Windows console API.
Returns:
    int: Value representing the current console mode as documented at
        https://docs.microsoft.com/en-us/windows/console/getconsolemode#parameters
Definition at line 94 of file _win32_console.py.
def GetConsoleMode(std_handle: wintypes.HANDLE) -> int:
    """Retrieves the current input mode of a console's input buffer
    or the current output mode of a console screen buffer.
    Args:
        std_handle (wintypes.HANDLE): A handle to the console input buffer or the console screen buffer.
    Raises:
        LegacyWindowsError: If any error occurs while calling the Windows console API.
    Returns:
        int: Value representing the current console mode as documented at
            https://docs.microsoft.com/en-us/windows/console/getconsolemode#parameters
    """
    console_mode = wintypes.DWORD()
    success = bool(_GetConsoleMode(std_handle, console_mode))
    if not success:
        raise LegacyWindowsError("Unable to get legacy Windows Console Mode")
    return console_mode.value
References _GetConsoleMode.
GetConsoleScreenBufferInfo()
CONSOLE_SCREEN_BUFFER_INFO pip._vendor.rich._win32_console.GetConsoleScreenBufferInfo (wintypes.HANDLE std_handle)
Retrieves information about the specified console screen buffer.
Args:
    std_handle (wintypes.HANDLE): A handle to the console input buffer or the console screen buffer.
Returns:
    CONSOLE_SCREEN_BUFFER_INFO: A CONSOLE_SCREEN_BUFFER_INFO ctype struct contain information about
        screen size, cursor position, colour attributes, and more.
Definition at line 227 of file _win32_console.py.
) -> CONSOLE_SCREEN_BUFFER_INFO:
    """Retrieves information about the specified console screen buffer.
    Args:
        std_handle (wintypes.HANDLE): A handle to the console input buffer or the console screen buffer.
    Returns:
        CONSOLE_SCREEN_BUFFER_INFO: A CONSOLE_SCREEN_BUFFER_INFO ctype struct contain information about
            screen size, cursor position, colour attributes, and more."""
    console_screen_buffer_info = CONSOLE_SCREEN_BUFFER_INFO()
    _GetConsoleScreenBufferInfo(std_handle, byref(console_screen_buffer_info))
    return console_screen_buffer_info
References _GetConsoleScreenBufferInfo.
Referenced by pip._vendor.rich._win32_console.LegacyWindowsTerm.cursor_position(), and pip._vendor.rich._win32_console.LegacyWindowsTerm.screen_size().
GetStdHandle()
wintypes.HANDLE pip._vendor.rich._win32_console.GetStdHandle (int handle = STDOUT)
Retrieves a handle to the specified standard device (standard input, standard output, or standard error).
Args:
    handle (int): Integer identifier for the handle. Defaults to -11 (stdout).
Returns:
    wintypes.HANDLE: The handle
Definition at line 77 of file _win32_console.py.
def GetStdHandle(handle: int = STDOUT) -> wintypes.HANDLE:
    """Retrieves a handle to the specified standard device (standard input, standard output, or standard error).
    Args:
        handle (int): Integer identifier for the handle. Defaults to -11 (stdout).
    Returns:
        wintypes.HANDLE: The handle
    """
    return cast(wintypes.HANDLE, _GetStdHandle(handle))
References _GetStdHandle.
Referenced by pip._vendor.rich._win32_console.LegacyWindowsTerm.__init__().
SetConsoleCursorInfo()
bool pip._vendor.rich._win32_console.SetConsoleCursorInfo (wintypes.HANDLE std_handle, CONSOLE_CURSOR_INFO cursor_info)
Set the cursor info - used for adjusting cursor visibility and width
Args:
    std_handle (wintypes.HANDLE): A handle to the console input buffer or the console screen buffer.
    cursor_info (CONSOLE_CURSOR_INFO): CONSOLE_CURSOR_INFO ctype struct containing the new cursor info.
Returns:
      bool: True if the function succeeds, otherwise False.
Definition at line 298 of file _win32_console.py.
) -> bool:
    """Set the cursor info - used for adjusting cursor visibility and width
    Args:
        std_handle (wintypes.HANDLE): A handle to the console input buffer or the console screen buffer.
        cursor_info (CONSOLE_CURSOR_INFO): CONSOLE_CURSOR_INFO ctype struct containing the new cursor info.
    Returns:
          bool: True if the function succeeds, otherwise False.
    """
    return bool(_SetConsoleCursorInfo(std_handle, byref(cursor_info)))
References _SetConsoleCursorInfo.
SetConsoleCursorPosition()
bool pip._vendor.rich._win32_console.SetConsoleCursorPosition (wintypes.HANDLE std_handle, WindowsCoordinates coords)
Set the position of the cursor in the console screen
Args:
    std_handle (wintypes.HANDLE): A handle to the console input buffer or the console screen buffer.
    coords (WindowsCoordinates): The coordinates to move the cursor to.
Returns:
    bool: True if the function succeeds, otherwise False.
Definition at line 251 of file _win32_console.py.
) -> bool:
    """Set the position of the cursor in the console screen
    Args:
        std_handle (wintypes.HANDLE): A handle to the console input buffer or the console screen buffer.
        coords (WindowsCoordinates): The coordinates to move the cursor to.
    Returns:
        bool: True if the function succeeds, otherwise False.
    """
    return bool(_SetConsoleCursorPosition(std_handle, coords))
References _SetConsoleCursorPosition.
Referenced by pip._vendor.rich._win32_console.LegacyWindowsTerm.move_cursor_backward(), pip._vendor.rich._win32_console.LegacyWindowsTerm.move_cursor_down(), pip._vendor.rich._win32_console.LegacyWindowsTerm.move_cursor_forward(), pip._vendor.rich._win32_console.LegacyWindowsTerm.move_cursor_to(), pip._vendor.rich._win32_console.LegacyWindowsTerm.move_cursor_to_column(), and pip._vendor.rich._win32_console.LegacyWindowsTerm.move_cursor_up().
SetConsoleTextAttribute()
bool pip._vendor.rich._win32_console.SetConsoleTextAttribute (wintypes.HANDLE std_handle, wintypes.WORD attributes)
Set the colour attributes for all text written after this function is called.
Args:
    std_handle (wintypes.HANDLE): A handle to the console input buffer or the console screen buffer.
    attributes (int): Integer value representing the foreground and background colours.
Returns:
    bool: True if the attribute was set successfully, otherwise False.
Definition at line 203 of file _win32_console.py.
) -> bool:
    """Set the colour attributes for all text written after this function is called.
    Args:
        std_handle (wintypes.HANDLE): A handle to the console input buffer or the console screen buffer.
        attributes (int): Integer value representing the foreground and background colours.
    Returns:
        bool: True if the attribute was set successfully, otherwise False.
    """
    return bool(_SetConsoleTextAttribute(std_handle, attributes))
References _SetConsoleTextAttribute.
Referenced by pip._vendor.rich._win32_console.LegacyWindowsTerm.write_styled().
SetConsoleTitle()
bool pip._vendor.rich._win32_console.SetConsoleTitle (str title)
Sets the title of the current console window
Args:
    title (str): The new title of the console window.
Returns:
    bool: True if the function succeeds, otherwise False.
Definition at line 318 of file _win32_console.py.
def SetConsoleTitle(title: str) -> bool:
    """Sets the title of the current console window
    Args:
        title (str): The new title of the console window.
    Returns:
        bool: True if the function succeeds, otherwise False.
    """
    return bool(_SetConsoleTitle(title))
References _SetConsoleTitle.
Variable Documentation
_FillConsoleOutputAttribute
Any pip._vendor.rich._win32_console._FillConsoleOutputAttribute = windll.kernel32.FillConsoleOutputAttribute protected
Definition at line 157 of file _win32_console.py.
Referenced by FillConsoleOutputAttribute().
_FillConsoleOutputCharacterW
Any pip._vendor.rich._win32_console._FillConsoleOutputCharacterW = windll.kernel32.FillConsoleOutputCharacterW protected
Definition at line 116 of file _win32_console.py.
Referenced by FillConsoleOutputCharacter().
_GetConsoleCursorInfo
Any pip._vendor.rich._win32_console._GetConsoleCursorInfo = windll.kernel32.GetConsoleCursorInfo protected
Definition at line 266 of file _win32_console.py.
Referenced by GetConsoleCursorInfo().
_GetConsoleMode
Any pip._vendor.rich._win32_console._GetConsoleMode = windll.kernel32.GetConsoleMode protected
Definition at line 89 of file _win32_console.py.
Referenced by GetConsoleMode().
_GetConsoleScreenBufferInfo
Any pip._vendor.rich._win32_console._GetConsoleScreenBufferInfo = windll.kernel32.GetConsoleScreenBufferInfo protected
Definition at line 219 of file _win32_console.py.
Referenced by GetConsoleScreenBufferInfo().
_GetStdHandle
Any pip._vendor.rich._win32_console._GetStdHandle = windll.kernel32.GetStdHandle protected
Definition at line 70 of file _win32_console.py.
Referenced by GetStdHandle().
_SetConsoleCursorInfo
Any pip._vendor.rich._win32_console._SetConsoleCursorInfo = windll.kernel32.SetConsoleCursorInfo protected
Definition at line 290 of file _win32_console.py.
Referenced by SetConsoleCursorInfo().
_SetConsoleCursorPosition
Any pip._vendor.rich._win32_console._SetConsoleCursorPosition = windll.kernel32.SetConsoleCursorPosition protected
Definition at line 243 of file _win32_console.py.
Referenced by SetConsoleCursorPosition().
_SetConsoleTextAttribute
Any pip._vendor.rich._win32_console._SetConsoleTextAttribute = windll.kernel32.SetConsoleTextAttribute protected
Definition at line 195 of file _win32_console.py.
Referenced by SetConsoleTextAttribute().
_SetConsoleTitle
Any pip._vendor.rich._win32_console._SetConsoleTitle = windll.kernel32.SetConsoleTitleW protected
Definition at line 313 of file _win32_console.py.
Referenced by SetConsoleTitle().
argtypes
pip._vendor.rich._win32_console.argtypes
Definition at line 71 of file _win32_console.py.
console
pip._vendor.rich._win32_console.console = Console()
Definition at line 581 of file _win32_console.py.
COORD
pip._vendor.rich._win32_console.COORD = wintypes._COORD
Definition at line 25 of file _win32_console.py.
Referenced by pip._vendor.rich._win32_console.WindowsCoordinates.from_param().
ENABLE_VIRTUAL_TERMINAL_PROCESSING
int pip._vendor.rich._win32_console.ENABLE_VIRTUAL_TERMINAL_PROCESSING = 4
Definition at line 23 of file _win32_console.py.
handle
wintypes.HANDLE pip._vendor.rich._win32_console.handle = GetStdHandle()
Definition at line 577 of file _win32_console.py.
heading
pip._vendor.rich._win32_console.heading = Style.parse("black on green")
Definition at line 588 of file _win32_console.py.
restype
pip._vendor.rich._win32_console.restype
Definition at line 74 of file _win32_console.py.
STDOUT
int pip._vendor.rich._win32_console.STDOUT = -11
Definition at line 22 of file _win32_console.py.
style
pip._vendor.rich._win32_console.style = Style(color="black", bgcolor="red")
Definition at line 586 of file _win32_console.py.
term
pip._vendor.rich._win32_console.term = LegacyWindowsTerm(sys.stdout)
Definition at line 583 of file _win32_console.py.
windll
pip._vendor.rich._win32_console.windll = None
Definition at line 9 of file _win32_console.py.