Read&Watch: django.contrib.admin.options Namespace Reference
django.contrib.admin.options Namespace Reference
Classes
class BaseModelAdmin
class IncorrectLookupParameters
class InlineModelAdmin
class ModelAdmin
class ShowFacets
class StackedInline
class TabularInline
Functions
get_content_type_for_model (obj)
get_ul_class (radio_style)
Variables
str IS_POPUP_VAR = "_popup"
str TO_FIELD_VAR = "_to_field"
str IS_FACETS_VAR = "_facets"
dict FORMFIELD_FOR_DBFIELD_DEFAULTS
csrf_protect_m = method_decorator(csrf_protect)
Function Documentation
get_content_type_for_model()
django.contrib.admin.options.get_content_type_for_model (obj)
Definition at line 88 of file options.py.
def get_content_type_for_model(obj):
    # Since this module gets imported in the application's root package,
    # it cannot import models from other applications at the module level.
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)
Referenced by django.contrib.admin.options.BaseModelAdmin.get_view_on_site_url(), django.contrib.admin.options.ModelAdmin.history_view(), django.contrib.admin.options.ModelAdmin.log_deletion(), and django.contrib.admin.options.ModelAdmin.render_change_form().
get_ul_class()
django.contrib.admin.options.get_ul_class (radio_style)
Definition at line 96 of file options.py.
def get_ul_class(radio_style):
    return "radiolist" if radio_style == VERTICAL else "radiolist inline"
Referenced by django.contrib.admin.options.BaseModelAdmin.formfield_for_choice_field(), and django.contrib.admin.options.BaseModelAdmin.formfield_for_foreignkey().
Variable Documentation
csrf_protect_m
django.contrib.admin.options.csrf_protect_m = method_decorator(csrf_protect)
Definition at line 125 of file options.py.
FORMFIELD_FOR_DBFIELD_DEFAULTS
dict django.contrib.admin.options.FORMFIELD_FOR_DBFIELD_DEFAULTS
Initial value:
=  {
    models.DateTimeField: {
        "form_class": forms.SplitDateTimeField,
        "widget": widgets.AdminSplitDateTime,
    },
    models.DateField: {"widget": widgets.AdminDateWidget},
    models.TimeField: {"widget": widgets.AdminTimeWidget},
    models.TextField: {"widget": widgets.AdminTextareaWidget},
    models.URLField: {"widget": widgets.AdminURLFieldWidget},
    models.IntegerField: {"widget": widgets.AdminIntegerFieldWidget},
    models.BigIntegerField: {"widget": widgets.AdminBigIntegerFieldWidget},
    models.CharField: {"widget": widgets.AdminTextInputWidget},
    models.ImageField: {"widget": widgets.AdminFileWidget},
    models.FileField: {"widget": widgets.AdminFileWidget},
    models.EmailField: {"widget": widgets.AdminEmailInputWidget},
    models.UUIDField: {"widget": widgets.AdminUUIDInputWidget},
}
Definition at line 107 of file options.py.
IS_FACETS_VAR
str django.contrib.admin.options.IS_FACETS_VAR = "_facets"
Definition at line 76 of file options.py.
IS_POPUP_VAR
str django.contrib.admin.options.IS_POPUP_VAR = "_popup"
Definition at line 74 of file options.py.
TO_FIELD_VAR
str django.contrib.admin.options.TO_FIELD_VAR = "_to_field"
Definition at line 75 of file options.py.