Read&Watch: pylint.checkers.variables Namespace Reference
pylint.checkers.variables Namespace Reference
Classes
class NamesConsumer
class ScopeConsumer
class VariablesChecker
class VariableVisitConsumerAction
Functions
bool|None _is_from_future_import (nodes.ImportFrom stmt, str name)
str _get_unpacking_extra_info (nodes.Assign node, InferenceResult inferred)
bool _detect_global_scope (nodes.Name node, nodes.LocalsDictNodeNG frame, nodes.LocalsDictNodeNG defframe)
Generator[InferenceResult] _infer_name_module (nodes.Import node, str name)
list[tuple[str, _base_nodes.ImportNode]] _fix_dot_imports (dict[str, list[nodes.NodeNG]] not_consumed)
bool _find_frame_imports (str name, nodes.LocalsDictNodeNG frame)
bool _import_name_is_global (nodes.Global|_base_nodes.ImportNode stmt, set[str] global_names)
set[str] _flattened_scope_names (Iterator[nodes.Global|nodes.Nonlocal] iterator)
bool _assigned_locally (nodes.Name name_node)
bool _has_locals_call_after_node (nodes.NodeNG stmt, nodes.FunctionDef scope)
None register (PyLinter linter)
Variables
SPECIAL_OBJ = re.compile("^_{2}[a-z]+_{2}$")
str FUTURE = "__future__"
IGNORED_ARGUMENT_NAMES = re.compile("_.*|^ignored_|^unused_")
dict METACLASS_NAME_TRANSFORMS = {"_py_abc": "abc"}
str BUILTIN_RANGE = "builtins.range"
str TYPING_MODULE = "typing"
TYPING_NAMES
tuple DICT_TYPES
tuple NODES_WITH_VALUE_ATTR
dict MSGS
Detailed Description
Variables checkers for Python code.
Function Documentation
_assigned_locally()
bool pylint.checkers.variables._assigned_locally (nodes.Name name_node) protected
Checks if name_node has corresponding assign statement in same scope.
Definition at line 347 of file variables.py.
def _assigned_locally(name_node: nodes.Name) -> bool:
    """Checks if name_node has corresponding assign statement in same scope."""
    name_node_scope = name_node.scope()
    assign_stmts = name_node_scope.nodes_of_class(nodes.AssignName)
    return any(a.name == name_node.name for a in assign_stmts) or _find_frame_imports(
        name_node.name, name_node_scope
    )
References _find_frame_imports().
Referenced by pylint.checkers.variables.VariablesChecker._is_variable_violation().
_detect_global_scope()
bool pylint.checkers.variables._detect_global_scope (nodes.Name node, nodes.LocalsDictNodeNG frame, nodes.LocalsDictNodeNG defframe) protected
Detect that the given frames share a global scope.
Two frames share a global scope when neither
of them are hidden under a function scope, as well
as any parent scope of them, until the root scope.
In this case, depending from something defined later on
will only work if guarded by a nested function definition.
Example:
    class A:
        # B has the same global scope as `C`, leading to a NameError.
        # Return True to indicate a shared scope.
        class B(C): ...
    class C: ...
Whereas this does not lead to a NameError:
    class A:
        def guard():
            # Return False to indicate no scope sharing.
            class B(C): ...
    class C: ...
Definition at line 176 of file variables.py.
) -> bool:
    """Detect that the given frames share a global scope.
    Two frames share a global scope when neither
    of them are hidden under a function scope, as well
    as any parent scope of them, until the root scope.
    In this case, depending from something defined later on
    will only work if guarded by a nested function definition.
    Example:
        class A:
            # B has the same global scope as `C`, leading to a NameError.
            # Return True to indicate a shared scope.
            class B(C): ...
        class C: ...
    Whereas this does not lead to a NameError:
        class A:
            def guard():
                # Return False to indicate no scope sharing.
                class B(C): ...
        class C: ...
    """
    def_scope = scope = None
    if frame and frame.parent:
        scope = frame.parent.scope()
    if defframe and defframe.parent:
        def_scope = defframe.parent.scope()
    if (
        isinstance(frame, nodes.ClassDef)
        and scope is not def_scope
        and scope is utils.get_node_first_ancestor_of_type(node, nodes.FunctionDef)
    ):
        # If the current node's scope is a class nested under a function,
        # and the def_scope is something else, then they aren't shared.
        return False
    if isinstance(frame, nodes.FunctionDef):
        # If the parent of the current node is a
        # function, then it can be under its scope (defined in); or
        # the `->` part of annotations. The same goes
        # for annotations of function arguments, they'll have
        # their parent the Arguments node.
        if frame.parent_of(defframe):
            return node.lineno < defframe.lineno  # type: ignore[no-any-return]
        if not isinstance(node.parent, (nodes.FunctionDef, nodes.Arguments)):
            return False
    break_scopes = []
    for current_scope in (scope or frame, def_scope):
        # Look for parent scopes. If there is anything different
        # than a module or a class scope, then the frames don't
        # share a global scope.
        parent_scope = current_scope
        while parent_scope:
            if not isinstance(parent_scope, (nodes.ClassDef, nodes.Module)):
                break_scopes.append(parent_scope)
                break
            if parent_scope.parent:
                parent_scope = parent_scope.parent.scope()
            else:
                break
    if len(set(break_scopes)) > 1:
        # Store different scopes than expected.
        # If the stored scopes are, in fact, the very same, then it means
        # that the two frames (frame and defframe) share the same scope,
        # and we could apply our lineno analysis over them.
        # For instance, this works when they are inside a function, the node
        # that uses a definition and the definition itself.
        return False
    # At this point, we are certain that frame and defframe share a scope
    # and the definition of the first depends on the second.
    return frame.lineno < defframe.lineno  # type: ignore[no-any-return]
Referenced by pylint.checkers.variables.VariablesChecker._is_variable_violation().
_find_frame_imports()
bool pylint.checkers.variables._find_frame_imports (str name, nodes.LocalsDictNodeNG frame) protected
Detect imports in the frame, with the required *name*.
Such imports can be considered assignments if they are not globals.
Returns True if an import for the given name was found.
Definition at line 304 of file variables.py.
def _find_frame_imports(name: str, frame: nodes.LocalsDictNodeNG) -> bool:
    """Detect imports in the frame, with the required *name*.
    Such imports can be considered assignments if they are not globals.
    Returns True if an import for the given name was found.
    """
    if name in _flattened_scope_names(frame.nodes_of_class(nodes.Global)):
        return False
    imports = frame.nodes_of_class((nodes.Import, nodes.ImportFrom))
    for import_node in imports:
        for import_name, import_alias in import_node.names:
            # If the import uses an alias, check only that.
            # Otherwise, check only the import name.
            if import_alias:
                if import_alias == name:
                    return True
            elif import_name and import_name == name:
                return True
    return False
References _flattened_scope_names().
Referenced by _assigned_locally().
_fix_dot_imports()
list[tuple[str, _base_nodes.ImportNode]] pylint.checkers.variables._fix_dot_imports (dict[str, list[nodes.NodeNG]] not_consumed) protected
Try to fix imports with multiple dots, by returning a dictionary
with the import names expanded.
The function unflattens root imports,
like 'xml' (when we have both 'xml.etree' and 'xml.sax'), to 'xml.etree'
and 'xml.sax' respectively.
Definition at line 258 of file variables.py.
) -> list[tuple[str, _base_nodes.ImportNode]]:
    """Try to fix imports with multiple dots, by returning a dictionary
    with the import names expanded.
    The function unflattens root imports,
    like 'xml' (when we have both 'xml.etree' and 'xml.sax'), to 'xml.etree'
    and 'xml.sax' respectively.
    """
    names: dict[str, _base_nodes.ImportNode] = {}
    for name, stmts in not_consumed.items():
        if any(
            isinstance(stmt, nodes.AssignName)
            and isinstance(stmt.assign_type(), nodes.AugAssign)
            for stmt in stmts
        ):
            continue
        for stmt in stmts:
            if not isinstance(stmt, (nodes.ImportFrom, nodes.Import)):
                continue
            for imports in stmt.names:
                second_name = None
                import_module_name = imports[0]
                if import_module_name == "*":
                    # In case of wildcard imports,
                    # pick the name from inside the imported module.
                    second_name = name
                else:
                    name_matches_dotted_import = False
                    if (
                        import_module_name.startswith(name)
                        and import_module_name.find(".") > -1
                    ):
                        name_matches_dotted_import = True
                    if name_matches_dotted_import or name in imports:
                        # Most likely something like 'xml.etree',
                        # which will appear in the .locals as 'xml'.
                        # Only pick the name if it wasn't consumed.
                        second_name = import_module_name
                if second_name and second_name not in names:
                    names[second_name] = stmt
    return sorted(names.items(), key=lambda a: a[1].fromlineno)
Referenced by pylint.checkers.variables.VariablesChecker._check_imports().
_flattened_scope_names()
set[str] pylint.checkers.variables._flattened_scope_names (Iterator[nodes.Global | nodes.Nonlocal] iterator) protected
Definition at line 340 of file variables.py.
) -> set[str]:
    values = (set(stmt.names) for stmt in iterator)
    return set(itertools.chain.from_iterable(values))
Referenced by _find_frame_imports(), and pylint.checkers.variables.VariablesChecker.leave_functiondef().
_get_unpacking_extra_info()
str pylint.checkers.variables._get_unpacking_extra_info (nodes.Assign node, InferenceResult inferred) protected
Return extra information to add to the message for unpacking-non-sequence
and unbalanced-tuple/dict-unpacking errors.
Definition at line 153 of file variables.py.
def _get_unpacking_extra_info(node: nodes.Assign, inferred: InferenceResult) -> str:
    """Return extra information to add to the message for unpacking-non-sequence
    and unbalanced-tuple/dict-unpacking errors.
    """
    more = ""
    if isinstance(inferred, DICT_TYPES):
        if isinstance(node, nodes.Assign):
            more = node.value.as_string()
        elif isinstance(node, nodes.For):
            more = node.iter.as_string()
        return more
    inferred_module = inferred.root().name
    if node.root().name == inferred_module:
        if node.lineno == inferred.lineno:
            more = f"'{inferred.as_string()}'"
        elif inferred.lineno:
            more = f"defined at line {inferred.lineno}"
    elif inferred.lineno:
        more = f"defined at line {inferred.lineno} of {inferred_module}"
    return more
Referenced by pylint.checkers.variables.VariablesChecker._check_unpacking(), and pylint.checkers.variables.VariablesChecker.visit_for().
_has_locals_call_after_node()
bool pylint.checkers.variables._has_locals_call_after_node (nodes.NodeNG stmt, nodes.FunctionDef scope) protected
Definition at line 356 of file variables.py.
def _has_locals_call_after_node(stmt: nodes.NodeNG, scope: nodes.FunctionDef) -> bool:
    skip_nodes = (
        nodes.FunctionDef,
        nodes.ClassDef,
        nodes.Import,
        nodes.ImportFrom,
    )
    for call in scope.nodes_of_class(nodes.Call, skip_klass=skip_nodes):
        inferred = utils.safe_infer(call.func)
        if (
            utils.is_builtin_object(inferred)
            and getattr(inferred, "name", None) == "locals"
        ):
            if stmt.lineno < call.lineno:
                return True
    return False
Referenced by pylint.checkers.variables.VariablesChecker._check_is_unused().
_import_name_is_global()
bool pylint.checkers.variables._import_name_is_global (nodes.Global | _base_nodes.ImportNode stmt, set[str] global_names) protected
Definition at line 326 of file variables.py.
) -> bool:
    for import_name, import_alias in stmt.names:
        # If the import uses an alias, check only that.
        # Otherwise, check only the import name.
        if import_alias:
            if import_alias in global_names:
                return True
        elif import_name in global_names:
            return True
    return False
Referenced by pylint.checkers.variables.VariablesChecker._check_is_unused().
_infer_name_module()
Generator[InferenceResult] pylint.checkers.variables._infer_name_module (nodes.Import node, str name) protected
Definition at line 252 of file variables.py.
def _infer_name_module(node: nodes.Import, name: str) -> Generator[InferenceResult]:
    context = astroid.context.InferenceContext()
    context.lookupname = name
    return node.infer(context, asname=False)  # type: ignore[no-any-return]
Referenced by pylint.checkers.variables.VariablesChecker.visit_import().
_is_from_future_import()
bool | None pylint.checkers.variables._is_from_future_import (nodes.ImportFrom stmt, str name) protected
Check if the name is a future import from another module.
Definition at line 140 of file variables.py.
def _is_from_future_import(stmt: nodes.ImportFrom, name: str) -> bool | None:
    """Check if the name is a future import from another module."""
    try:
        module = stmt.do_import_module(stmt.modname)
    except astroid.AstroidBuildingError:
        return None
    for local_node in module.locals.get(name, []):
        if isinstance(local_node, nodes.ImportFrom) and local_node.modname == FUTURE:
            return True
    return None
Referenced by pylint.checkers.variables.VariablesChecker._check_imports().
register()
None pylint.checkers.variables.register (PyLinter linter)
Definition at line 3440 of file variables.py.
def register(linter: PyLinter) -> None:
    linter.register_checker(VariablesChecker(linter))
Variable Documentation
BUILTIN_RANGE
str pylint.checkers.variables.BUILTIN_RANGE = "builtins.range"
Definition at line 50 of file variables.py.
DICT_TYPES
tuple pylint.checkers.variables.DICT_TYPES
Initial value:
=  (
    astroid.objects.DictValues,
    astroid.objects.DictKeys,
    astroid.objects.DictItems,
    astroid.nodes.node_classes.Dict,
)
Definition at line 110 of file variables.py.
FUTURE
str pylint.checkers.variables.FUTURE = "__future__"
Definition at line 43 of file variables.py.
IGNORED_ARGUMENT_NAMES
pylint.checkers.variables.IGNORED_ARGUMENT_NAMES = re.compile("_.*|^ignored_|^unused_")
Definition at line 45 of file variables.py.
METACLASS_NAME_TRANSFORMS
dict pylint.checkers.variables.METACLASS_NAME_TRANSFORMS = {"_py_abc": "abc"}
Definition at line 49 of file variables.py.
MSGS
dict pylint.checkers.variables.MSGS
Definition at line 374 of file variables.py.
NODES_WITH_VALUE_ATTR
tuple pylint.checkers.variables.NODES_WITH_VALUE_ATTR
Initial value:
=  (
    nodes.Assign,
    nodes.AnnAssign,
    nodes.AugAssign,
    nodes.Expr,
    nodes.Return,
    nodes.Match,
    nodes.TypeAlias,
)
Definition at line 117 of file variables.py.
SPECIAL_OBJ
pylint.checkers.variables.SPECIAL_OBJ = re.compile("^_{2}[a-z]+_{2}$")
Definition at line 42 of file variables.py.
TYPING_MODULE
str pylint.checkers.variables.TYPING_MODULE = "typing"
Definition at line 51 of file variables.py.
TYPING_NAMES
pylint.checkers.variables.TYPING_NAMES
Definition at line 52 of file variables.py.