Read&Watch: pip._internal.resolution.resolvelib.found_candidates Namespace Reference
pip._internal.resolution.resolvelib.found_candidates Namespace Reference
Classes
class FoundCandidates
Functions
Iterator[Candidate] _iter_built (Iterator[IndexCandidateInfo] infos)
Iterator[Candidate] _iter_built_with_prepended (Candidate installed, Iterator[IndexCandidateInfo] infos)
Iterator[Candidate] _iter_built_with_inserted (Candidate installed, Iterator[IndexCandidateInfo] infos)
Variables
logger = logging.getLogger(__name__)
IndexCandidateInfo = Tuple[_BaseVersion, Callable[[], Optional[Candidate]]]
SequenceCandidate = Sequence[Candidate]
Detailed Description
Utilities to lazily create and visit candidates found.
Creating and visiting a candidate is a *very* costly operation. It involves
fetching, extracting, potentially building modules from source, and verifying
distribution metadata. It is therefore crucial for performance to keep
everything here lazy all the way down, so we only touch candidates that we
absolutely need, and not "download the world" when we only need one version of
something.
Function Documentation
_iter_built()
Iterator[Candidate] pip._internal.resolution.resolvelib.found_candidates._iter_built (Iterator[IndexCandidateInfo] infos) protected
Iterator for ``FoundCandidates``.
This iterator is used when the package is not already installed. Candidates
from index come later in their normal ordering.
Definition at line 42 of file found_candidates.py.
def _iter_built(infos: Iterator[IndexCandidateInfo]) -> Iterator[Candidate]:
    """Iterator for ``FoundCandidates``.
    This iterator is used when the package is not already installed. Candidates
    from index come later in their normal ordering.
    """
    versions_found: Set[_BaseVersion] = set()
    for version, func in infos:
        if version in versions_found:
            continue
        try:
            candidate = func()
        except MetadataInvalid as e:
            logger.warning(
                "Ignoring version %s of %s since it has invalid metadata:\n"
                "%s\n"
                "Please use pip<24.1 if you need to use this version.",
                version,
                e.ireq.name,
                e,
            )
            # Mark version as found to avoid trying other candidates with the same
            # version, since they most likely have invalid metadata as well.
            versions_found.add(version)
        else:
            if candidate is None:
                continue
            yield candidate
            versions_found.add(version)
Referenced by pip._internal.resolution.resolvelib.found_candidates.FoundCandidates.__iter__().
_iter_built_with_inserted()
Iterator[Candidate] pip._internal.resolution.resolvelib.found_candidates._iter_built_with_inserted (Candidate installed, Iterator[IndexCandidateInfo] infos) protected
Iterator for ``FoundCandidates``.
This iterator is used when the resolver prefers to upgrade an
already-installed package. Candidates from index are returned in their
normal ordering, except replaced when the version is already installed.
The implementation iterates through and yields other candidates, inserting
the installed candidate exactly once before we start yielding older or
equivalent candidates, or after all other candidates if they are all newer.
Definition at line 95 of file found_candidates.py.
) -> Iterator[Candidate]:
    """Iterator for ``FoundCandidates``.
    This iterator is used when the resolver prefers to upgrade an
    already-installed package. Candidates from index are returned in their
    normal ordering, except replaced when the version is already installed.
    The implementation iterates through and yields other candidates, inserting
    the installed candidate exactly once before we start yielding older or
    equivalent candidates, or after all other candidates if they are all newer.
    """
    versions_found: Set[_BaseVersion] = set()
    for version, func in infos:
        if version in versions_found:
            continue
        # If the installed candidate is better, yield it first.
        if installed.version >= version:
            yield installed
            versions_found.add(installed.version)
        candidate = func()
        if candidate is None:
            continue
        yield candidate
        versions_found.add(version)
    # If the installed candidate is older than all other candidates.
    if installed.version not in versions_found:
        yield installed
Referenced by pip._internal.resolution.resolvelib.found_candidates.FoundCandidates.__iter__().
_iter_built_with_prepended()
Iterator[Candidate] pip._internal.resolution.resolvelib.found_candidates._iter_built_with_prepended (Candidate installed, Iterator[IndexCandidateInfo] infos) protected
Iterator for ``FoundCandidates``.
This iterator is used when the resolver prefers the already-installed
candidate and NOT to upgrade. The installed candidate is therefore
always yielded first, and candidates from index come later in their
normal ordering, except skipped when the version is already installed.
Definition at line 73 of file found_candidates.py.
) -> Iterator[Candidate]:
    """Iterator for ``FoundCandidates``.
    This iterator is used when the resolver prefers the already-installed
    candidate and NOT to upgrade. The installed candidate is therefore
    always yielded first, and candidates from index come later in their
    normal ordering, except skipped when the version is already installed.
    """
    yield installed
    versions_found: Set[_BaseVersion] = {installed.version}
    for version, func in infos:
        if version in versions_found:
            continue
        candidate = func()
        if candidate is None:
            continue
        yield candidate
        versions_found.add(version)
Referenced by pip._internal.resolution.resolvelib.found_candidates.FoundCandidates.__iter__().
Variable Documentation
IndexCandidateInfo
pip._internal.resolution.resolvelib.found_candidates.IndexCandidateInfo = Tuple[_BaseVersion, Callable[[], Optional[Candidate]]]
Definition at line 24 of file found_candidates.py.
logger
pip._internal.resolution.resolvelib.found_candidates.logger = logging.getLogger(__name__)
Definition at line 22 of file found_candidates.py.
SequenceCandidate
pip._internal.resolution.resolvelib.found_candidates.SequenceCandidate = Sequence[Candidate]
Definition at line 27 of file found_candidates.py.