Read&Watch: pip._vendor.pygments.filters Namespace Reference
pip._vendor.pygments.filters Namespace Reference
Classes
class CodeTagFilter
class ErrorToken
class GobbleFilter
class KeywordCaseFilter
class NameHighlightFilter
class RaiseOnErrorTokenFilter
class SymbolFilter
class TokenMergeFilter
class VisibleWhitespaceFilter
Functions
find_filter_class (filtername)
get_filter_by_name (filtername, **options)
get_all_filters ()
_replace_special (ttype, value, regex, specialttype, replacefunc=lambda x:x)
Variables
dict FILTERS
Detailed Description
    pygments.filters
    ~~~~~~~~~~~~~~~~
    Module containing filter lookup functions and default
    filters.
    :copyright: Copyright 2006-2024 by the Pygments team, see AUTHORS.
    :license: BSD, see LICENSE for details.
Function Documentation
_replace_special()
pip._vendor.pygments.filters._replace_special (ttype, value, regex, specialttype, replacefunc = lambda x: x) protected
Definition at line 52 of file __init__.py.
                     replacefunc=lambda x: x):
    last = 0
    for match in regex.finditer(value):
        start, end = match.start(), match.end()
        if start != last:
            yield ttype, value[last:start]
        yield specialttype, replacefunc(value[start:end])
        last = end
    if last != len(value):
        yield ttype, value[last:]
Referenced by pip._vendor.pygments.filters.CodeTagFilter.filter(), and pip._vendor.pygments.filters.VisibleWhitespaceFilter.filter().
find_filter_class()
pip._vendor.pygments.filters.find_filter_class (filtername)
Lookup a filter by name. Return None if not found.
Definition at line 22 of file __init__.py.
def find_filter_class(filtername):
    """Lookup a filter by name. Return None if not found."""
    if filtername in FILTERS:
        return FILTERS[filtername]
    for name, cls in find_plugin_filters():
        if name == filtername:
            return cls
    return None
Referenced by get_filter_by_name().
get_all_filters()
pip._vendor.pygments.filters.get_all_filters ()
Return a generator of all filter names.
Definition at line 45 of file __init__.py.
def get_all_filters():
    """Return a generator of all filter names."""
    yield from FILTERS
    for name, _ in find_plugin_filters():
        yield name
get_filter_by_name()
pip._vendor.pygments.filters.get_filter_by_name (filtername, ** options)
Return an instantiated filter.
Options are passed to the filter initializer if wanted.
Raise a ClassNotFound if not found.
Definition at line 32 of file __init__.py.
def get_filter_by_name(filtername, **options):
    """Return an instantiated filter.
    Options are passed to the filter initializer if wanted.
    Raise a ClassNotFound if not found.
    """
    cls = find_filter_class(filtername)
    if cls:
        return cls(**options)
    else:
        raise ClassNotFound(f'filter {filtername!r} not found')
References find_filter_class().
Variable Documentation
FILTERS
dict pip._vendor.pygments.filters.FILTERS
Initial value:
=  {
    'codetagify':     CodeTagFilter,
    'keywordcase':    KeywordCaseFilter,
    'highlight':      NameHighlightFilter,
    'raiseonerror':   RaiseOnErrorTokenFilter,
    'whitespace':     VisibleWhitespaceFilter,
    'gobble':         GobbleFilter,
    'tokenmerge':     TokenMergeFilter,
    'symbols':        SymbolFilter,
}
Definition at line 931 of file __init__.py.