Read&Watch: django.core.validators Namespace Reference
django.core.validators Namespace Reference
Classes
class BaseValidator
class DecimalValidator
class DomainNameValidator
class EmailValidator
class FileExtensionValidator
class MaxLengthValidator
class MaxValueValidator
class MinLengthValidator
class MinValueValidator
class ProhibitNullCharactersValidator
class RegexValidator
class StepValueValidator
class URLValidator
Functions
validate_integer (value)
validate_ipv4_address (value)
validate_ipv6_address (value)
validate_ipv46_address (value)
ip_address_validators (protocol, unpack_ipv4)
int_list_validator (sep=",", message=None, code="invalid", allow_negative=False)
get_available_image_extensions ()
validate_image_file_extension (value)
Variables
tuple EMPTY_VALUES = (None, "", [], (), {})
validate_domain_name = DomainNameValidator()
integer_validator
validate_email = EmailValidator()
slug_re = _lazy_re_compile(r"^[-a-zA-Z0-9_]+\Z")
validate_slug
slug_unicode_re = _lazy_re_compile(r"^[-\w]+\Z")
validate_unicode_slug
dict ip_address_validator_map
validate_comma_separated_integer_list
Function Documentation
get_available_image_extensions()
django.core.validators.get_available_image_extensions ()
Definition at line 657 of file validators.py.
def get_available_image_extensions():
    try:
        from PIL import Image
    except ImportError:
        return []
    else:
        Image.init()
        return [ext.lower()[1:] for ext in Image.EXTENSION]
Referenced by validate_image_file_extension().
int_list_validator()
django.core.validators.int_list_validator (sep = ",", message = None, code = "invalid", allow_negative = False)
Definition at line 381 of file validators.py.
def int_list_validator(sep=",", message=None, code="invalid", allow_negative=False):
    regexp = _lazy_re_compile(
        r"^%(neg)s\d+(?:%(sep)s%(neg)s\d+)*\Z"
        % {
            "neg": "(-)?" if allow_negative else "",
            "sep": re.escape(sep),
        }
    )
    return RegexValidator(regexp, message=message, code=code)
ip_address_validators()
django.core.validators.ip_address_validators (protocol, unpack_ipv4)
Depending on the given parameters, return the appropriate validators for
the GenericIPAddressField.
Definition at line 363 of file validators.py.
def ip_address_validators(protocol, unpack_ipv4):
    """
    Depending on the given parameters, return the appropriate validators for
    the GenericIPAddressField.
    """
    if protocol != "both" and unpack_ipv4:
        raise ValueError(
            "You can only use `unpack_ipv4` if `protocol` is set to 'both'"
        )
    try:
        return ip_address_validator_map[protocol.lower()]
    except KeyError:
        raise ValueError(
            "The protocol '%s' is unknown. Supported: %s"
            % (protocol, list(ip_address_validator_map))
        )
validate_image_file_extension()
django.core.validators.validate_image_file_extension (value)
Definition at line 667 of file validators.py.
def validate_image_file_extension(value):
    return FileExtensionValidator(allowed_extensions=get_available_image_extensions())(
        value
    )
@deconstructible
References get_available_image_extensions().
validate_integer()
django.core.validators.validate_integer (value)
Definition at line 218 of file validators.py.
def validate_integer(value):
    return integer_validator(value)
@deconstructible
References integer_validator.
validate_ipv46_address()
django.core.validators.validate_ipv46_address (value)
Definition at line 342 of file validators.py.
def validate_ipv46_address(value):
    try:
        validate_ipv4_address(value)
    except ValidationError:
        try:
            validate_ipv6_address(value)
        except ValidationError:
            raise ValidationError(
                _("Enter a valid %(protocol)s address."),
                code="invalid",
                params={"protocol": _("IPv4 or IPv6"), "value": value},
            )
References validate_ipv4_address(), and validate_ipv6_address().
Referenced by django.core.validators.EmailValidator.validate_domain_part().
validate_ipv4_address()
django.core.validators.validate_ipv4_address (value)
Definition at line 322 of file validators.py.
def validate_ipv4_address(value):
    try:
        ipaddress.IPv4Address(value)
    except ValueError:
        raise ValidationError(
            _("Enter a valid %(protocol)s address."),
            code="invalid",
            params={"protocol": _("IPv4"), "value": value},
        )
Referenced by validate_ipv46_address().
validate_ipv6_address()
django.core.validators.validate_ipv6_address (value)
Definition at line 333 of file validators.py.
def validate_ipv6_address(value):
    if not is_valid_ipv6_address(value):
        raise ValidationError(
            _("Enter a valid %(protocol)s address."),
            code="invalid",
            params={"protocol": _("IPv6"), "value": value},
        )
Referenced by django.core.validators.URLValidator.__call__(), and validate_ipv46_address().
Variable Documentation
EMPTY_VALUES
tuple django.core.validators.EMPTY_VALUES = (None, "", [], (), {})
Definition at line 16 of file validators.py.
integer_validator
django.core.validators.integer_validator
Initial value:
=  RegexValidator(
    _lazy_re_compile(r"^-?\d+\Z"),
    message=_("Enter a valid integer."),
    code="invalid",
)
Definition at line 211 of file validators.py.
Referenced by validate_integer().
ip_address_validator_map
dict django.core.validators.ip_address_validator_map
Initial value:
=  {
    "both": [validate_ipv46_address],
    "ipv4": [validate_ipv4_address],
    "ipv6": [validate_ipv6_address],
}
Definition at line 356 of file validators.py.
slug_re
django.core.validators.slug_re = _lazy_re_compile(r"^[-a-zA-Z0-9_]+\Z")
Definition at line 303 of file validators.py.
slug_unicode_re
django.core.validators.slug_unicode_re = _lazy_re_compile(r"^[-\w]+\Z")
Definition at line 311 of file validators.py.
validate_comma_separated_integer_list
django.core.validators.validate_comma_separated_integer_list
Initial value:
=  int_list_validator(
    message=_("Enter only digits separated by commas."),
)
Definition at line 392 of file validators.py.
validate_domain_name
django.core.validators.validate_domain_name = DomainNameValidator()
Definition at line 123 of file validators.py.
validate_email
django.core.validators.validate_email = EmailValidator()
Definition at line 301 of file validators.py.
validate_slug
django.core.validators.validate_slug
Initial value:
=  RegexValidator(
    slug_re,
    # Translators: "letters" means latin letters: a-z and A-Z.
    _("Enter a valid “slug” consisting of letters, numbers, underscores or hyphens."),
    "invalid",
)
Definition at line 304 of file validators.py.
validate_unicode_slug
django.core.validators.validate_unicode_slug
Initial value:
=  RegexValidator(
    slug_unicode_re,
    _(
        "Enter a valid “slug” consisting of Unicode letters, numbers, underscores, or "
        "hyphens."
    ),
    "invalid",
)
Definition at line 312 of file validators.py.