Read&Watch: django.utils.version Namespace Reference
django.utils.version Namespace Reference
Functions
get_version (version=None)
get_main_version (version=None)
get_complete_version (version=None)
get_docs_version (version=None)
get_git_changeset ()
get_version_tuple (version)
Variables
str PYPY = "pypy"
tuple PY38 = (3, 8)
tuple PY39 = (3, 9)
tuple PY310 = (3, 10)
tuple PY311 = (3, 11)
tuple PY312 = (3, 12)
tuple PY313 = (3, 13)
version_component_re = _lazy_re_compile(r"(\d+|[a-z]+|\.)")
Function Documentation
get_complete_version()
django.utils.version.get_complete_version (version = None)
Return a tuple of the django version. If version argument is non-empty,
check for correctness of the tuple provided.
Definition at line 55 of file version.py.
def get_complete_version(version=None):
    """
    Return a tuple of the django version. If version argument is non-empty,
    check for correctness of the tuple provided.
    """
    if version is None:
        from django import VERSION as version
    else:
        assert len(version) == 5
        assert version[3] in ("alpha", "beta", "rc", "final")
    return version
Referenced by get_docs_version(), get_main_version(), and get_version().
get_docs_version()
django.utils.version.get_docs_version (version = None)
Definition at line 69 of file version.py.
def get_docs_version(version=None):
    version = get_complete_version(version)
    if version[3] != "final":
        return "dev"
    else:
        return "%d.%d" % version[:2]
@functools.lru_cache
References get_complete_version().
get_git_changeset()
django.utils.version.get_git_changeset ()
Return a numeric identifier of the latest git changeset.
The result is the UTC timestamp of the changeset in YYYYMMDDHHMMSS format.
This value isn't guaranteed to be unique, but collisions are very unlikely,
so it's sufficient for generating the development version numbers.
Definition at line 78 of file version.py.
def get_git_changeset():
    """Return a numeric identifier of the latest git changeset.
    The result is the UTC timestamp of the changeset in YYYYMMDDHHMMSS format.
    This value isn't guaranteed to be unique, but collisions are very unlikely,
    so it's sufficient for generating the development version numbers.
    """
    # Repository may not be found if __file__ is undefined, e.g. in a frozen
    # module.
    if "__file__" not in globals():
        return None
    repo_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    git_log = subprocess.run(
        "git log --pretty=format:%ct --quiet -1 HEAD",
        capture_output=True,
        shell=True,
        cwd=repo_dir,
        text=True,
    )
    timestamp = git_log.stdout
    tz = datetime.timezone.utc
    try:
        timestamp = datetime.datetime.fromtimestamp(int(timestamp), tz=tz)
    except ValueError:
        return None
    return timestamp.strftime("%Y%m%d%H%M%S")
Referenced by get_version().
get_main_version()
django.utils.version.get_main_version (version = None)
Return main version (X.Y[.Z]) from VERSION.
Definition at line 48 of file version.py.
def get_main_version(version=None):
    """Return main version (X.Y[.Z]) from VERSION."""
    version = get_complete_version(version)
    parts = 2 if version[2] == 0 else 3
    return ".".join(str(x) for x in version[:parts])
References get_complete_version().
Referenced by get_version().
get_version()
django.utils.version.get_version (version = None)
Return a PEP 440-compliant version number from VERSION.
Definition at line 24 of file version.py.
def get_version(version=None):
    """Return a PEP 440-compliant version number from VERSION."""
    version = get_complete_version(version)
    # Now build the two parts of the version number:
    # main = X.Y[.Z]
    # sub = .devN - for pre-alpha releases
    #     | {a|b|rc}N - for alpha, beta, and rc releases
    main = get_main_version(version)
    sub = ""
    if version[3] == "alpha" and version[4] == 0:
        git_changeset = get_git_changeset()
        if git_changeset:
            sub = ".dev%s" % git_changeset
    elif version[3] != "final":
        mapping = {"alpha": "a", "beta": "b", "rc": "rc"}
        sub = mapping[version[3]] + str(version[4])
    return main + sub
References get_complete_version(), get_git_changeset(), and get_main_version().
get_version_tuple()
django.utils.version.get_version_tuple (version)
Return a tuple of version numbers (e.g. (1, 2, 3)) from the version
string (e.g. '1.2.3').
Definition at line 109 of file version.py.
def get_version_tuple(version):
    """
    Return a tuple of version numbers (e.g. (1, 2, 3)) from the version
    string (e.g. '1.2.3').
    """
    version_numbers = []
    for item in version_component_re.split(version):
        if item and item != ".":
            try:
                component = int(item)
            except ValueError:
                break
            else:
                version_numbers.append(component)
    return tuple(version_numbers)
Variable Documentation
PY310
tuple django.utils.version.PY310 = (3, 10)
Definition at line 18 of file version.py.
PY311
tuple django.utils.version.PY311 = (3, 11)
Definition at line 19 of file version.py.
PY312
tuple django.utils.version.PY312 = (3, 12)
Definition at line 20 of file version.py.
PY313
tuple django.utils.version.PY313 = (3, 13)
Definition at line 21 of file version.py.
PY38
tuple django.utils.version.PY38 = (3, 8)
Definition at line 16 of file version.py.
PY39
tuple django.utils.version.PY39 = (3, 9)
Definition at line 17 of file version.py.
PYPY
str django.utils.version.PYPY = "pypy"
Definition at line 10 of file version.py.
version_component_re
django.utils.version.version_component_re = _lazy_re_compile(r"(\d+|[a-z]+|\.)")
Definition at line 106 of file version.py.