Read&Watch: django.contrib.auth.password_validation Namespace Reference
django.contrib.auth.password_validation Namespace Reference
Classes
class CommonPasswordValidator
class MinimumLengthValidator
class NumericPasswordValidator
class UserAttributeSimilarityValidator
Functions
get_default_password_validators ()
get_password_validators (validator_config)
validate_password (password, user=None, password_validators=None)
password_changed (password, user=None, password_validators=None)
password_validators_help_texts (password_validators=None)
_password_validators_help_text_html (password_validators=None)
exceeds_maximum_length_ratio (password, max_similarity, value)
Variables
password_validators_help_text_html = lazy(_password_validators_help_text_html, str)
Function Documentation
_password_validators_help_text_html()
django.contrib.auth.password_validation._password_validators_help_text_html (password_validators = None) protected
Return an HTML string with all help texts of all configured validators
in an <ul>.
Definition at line 84 of file password_validation.py.
def _password_validators_help_text_html(password_validators=None):
    """
    Return an HTML string with all help texts of all configured validators
    in an <ul>.
    """
    help_texts = password_validators_help_texts(password_validators)
    help_items = format_html_join(
        "", "<li>{}</li>", ((help_text,) for help_text in help_texts)
    )
    return format_html("<ul>{}</ul>", help_items) if help_items else ""
References password_validators_help_texts().
exceeds_maximum_length_ratio()
django.contrib.auth.password_validation.exceeds_maximum_length_ratio (password, max_similarity, value)
Test that value is within a reasonable range of password.
The following ratio calculations are based on testing SequenceMatcher like
this:
for i in range(0,6):
  print(10**i, SequenceMatcher(a='A', b='A'*(10**i)).quick_ratio())
which yields:
1 1.0
10 0.18181818181818182
100 0.019801980198019802
1000 0.001998001998001998
10000 0.00019998000199980003
100000 1.999980000199998e-05
This means a length_ratio of 10 should never yield a similarity higher than
0.2, for 100 this is down to 0.02 and for 1000 it is 0.002. This can be
calculated via 2 / length_ratio. As a result we avoid the potentially
expensive sequence matching.
Definition at line 129 of file password_validation.py.
def exceeds_maximum_length_ratio(password, max_similarity, value):
    """
    Test that value is within a reasonable range of password.
    The following ratio calculations are based on testing SequenceMatcher like
    this:
    for i in range(0,6):
      print(10**i, SequenceMatcher(a='A', b='A'*(10**i)).quick_ratio())
    which yields:
    1 1.0
    10 0.18181818181818182
    100 0.019801980198019802
    1000 0.001998001998001998
    10000 0.00019998000199980003
    100000 1.999980000199998e-05
    This means a length_ratio of 10 should never yield a similarity higher than
    0.2, for 100 this is down to 0.02 and for 1000 it is 0.002. This can be
    calculated via 2 / length_ratio. As a result we avoid the potentially
    expensive sequence matching.
    """
    pwd_len = len(password)
    length_bound_similarity = max_similarity / 2 * pwd_len
    value_len = len(value)
    return pwd_len >= 10 * value_len and value_len < length_bound_similarity
Referenced by django.contrib.auth.password_validation.UserAttributeSimilarityValidator.validate().
get_default_password_validators()
django.contrib.auth.password_validation.get_default_password_validators ()
Definition at line 21 of file password_validation.py.
def get_default_password_validators():
    return get_password_validators(settings.AUTH_PASSWORD_VALIDATORS)
References get_password_validators().
Referenced by password_changed(), password_validators_help_texts(), and validate_password().
get_password_validators()
django.contrib.auth.password_validation.get_password_validators (validator_config)
Definition at line 25 of file password_validation.py.
def get_password_validators(validator_config):
    validators = []
    for validator in validator_config:
        try:
            klass = import_string(validator["NAME"])
        except ImportError:
            msg = (
                "The module in NAME could not be imported: %s. Check your "
                "AUTH_PASSWORD_VALIDATORS setting."
            )
            raise ImproperlyConfigured(msg % validator["NAME"])
        validators.append(klass(**validator.get("OPTIONS", {})))
    return validators
Referenced by get_default_password_validators().
password_changed()
django.contrib.auth.password_validation.password_changed (password, user = None, password_validators = None)
Inform all validators that have implemented a password_changed() method
that the password has been changed.
Definition at line 60 of file password_validation.py.
def password_changed(password, user=None, password_validators=None):
    """
    Inform all validators that have implemented a password_changed() method
    that the password has been changed.
    """
    if password_validators is None:
        password_validators = get_default_password_validators()
    for validator in password_validators:
        password_changed = getattr(validator, "password_changed", lambda *a: None)
        password_changed(password, user)
References get_default_password_validators(), and password_changed().
Referenced by password_changed().
password_validators_help_texts()
django.contrib.auth.password_validation.password_validators_help_texts (password_validators = None)
Return a list of all help texts of all configured validators.
Definition at line 72 of file password_validation.py.
def password_validators_help_texts(password_validators=None):
    """
    Return a list of all help texts of all configured validators.
    """
    help_texts = []
    if password_validators is None:
        password_validators = get_default_password_validators()
    for validator in password_validators:
        help_texts.append(validator.get_help_text())
    return help_texts
References get_default_password_validators().
Referenced by _password_validators_help_text_html().
validate_password()
django.contrib.auth.password_validation.validate_password (password, user = None, password_validators = None)
Validate that the password meets all validator requirements.
If the password is valid, return ``None``.
If the password is invalid, raise ValidationError with all error messages.
Definition at line 41 of file password_validation.py.
def validate_password(password, user=None, password_validators=None):
    """
    Validate that the password meets all validator requirements.
    If the password is valid, return ``None``.
    If the password is invalid, raise ValidationError with all error messages.
    """
    errors = []
    if password_validators is None:
        password_validators = get_default_password_validators()
    for validator in password_validators:
        try:
            validator.validate(password, user)
        except ValidationError as error:
            errors.append(error)
    if errors:
        raise ValidationError(errors)
References get_default_password_validators().
Variable Documentation
password_validators_help_text_html
django.contrib.auth.password_validation.password_validators_help_text_html = lazy(_password_validators_help_text_html, str)
Definition at line 96 of file password_validation.py.