Read&Watch: pip._internal.self_outdated_check Namespace Reference
pip._internal.self_outdated_check Namespace Reference
Classes
class SelfCheckState
class UpgradePrompt
Functions
str _get_statefile_name (str key)
datetime.datetime _convert_date (str isodate)
bool was_installed_by_pip (str pkg)
Optional[str] _get_current_remote_pip_version (PipSession session, optparse.Values options)
Optional[UpgradePrompt] _self_version_check_logic (*, SelfCheckState state, datetime.datetime current_time, Version local_version, Callable[[], Optional[str]] get_remote_version)
None pip_self_version_check (PipSession session, optparse.Values options)
Variables
_WEEK = datetime.timedelta(days=7)
logger = logging.getLogger(__name__)
Function Documentation
_convert_date()
datetime.datetime pip._internal.self_outdated_check._convert_date (str isodate) protected
Convert an ISO format string to a date.
Handles the format 2020-01-22T14:24:01Z (trailing Z)
which is not supported by older versions of fromisoformat.
Definition at line 42 of file self_outdated_check.py.
def _convert_date(isodate: str) -> datetime.datetime:
    """Convert an ISO format string to a date.
    Handles the format 2020-01-22T14:24:01Z (trailing Z)
    which is not supported by older versions of fromisoformat.
    """
    return datetime.datetime.fromisoformat(isodate.replace("Z", "+00:00"))
Referenced by pip._internal.self_outdated_check.SelfCheckState.get().
_get_current_remote_pip_version()
Optional[str] pip._internal.self_outdated_check._get_current_remote_pip_version (PipSession session, optparse.Values options) protected
Definition at line 162 of file self_outdated_check.py.
) -> Optional[str]:
    # Lets use PackageFinder to see what the latest pip version is
    link_collector = LinkCollector.create(
        session,
        options=options,
        suppress_no_index=True,
    )
    # Pass allow_yanked=False so we don't suggest upgrading to a
    # yanked version.
    selection_prefs = SelectionPreferences(
        allow_yanked=False,
        allow_all_prereleases=False,  # Explicitly set to False
    )
    finder = PackageFinder.create(
        link_collector=link_collector,
        selection_prefs=selection_prefs,
    )
    best_candidate = finder.find_best_candidate("pip").best_candidate
    if best_candidate is None:
        return None
    return str(best_candidate.version)
_get_statefile_name()
str pip._internal.self_outdated_check._get_statefile_name (str key) protected
Definition at line 36 of file self_outdated_check.py.
def _get_statefile_name(key: str) -> str:
    key_bytes = key.encode()
    name = hashlib.sha224(key_bytes).hexdigest()
    return name
_self_version_check_logic()
Optional[UpgradePrompt] pip._internal.self_outdated_check._self_version_check_logic (* , SelfCheckState state, datetime.datetime current_time, Version local_version, Callable[[], Optional[str]] get_remote_version) protected
Definition at line 190 of file self_outdated_check.py.
) -> Optional[UpgradePrompt]:
    remote_version_str = state.get(current_time)
    if remote_version_str is None:
        remote_version_str = get_remote_version()
        if remote_version_str is None:
            logger.debug("No remote pip version found")
            return None
        state.set(remote_version_str, current_time)
    remote_version = parse_version(remote_version_str)
    logger.debug("Remote version of pip: %s", remote_version)
    logger.debug("Local version of pip:  %s", local_version)
    pip_installed_by_pip = was_installed_by_pip("pip")
    logger.debug("Was pip installed by pip? %s", pip_installed_by_pip)
    if not pip_installed_by_pip:
        return None  # Only suggest upgrade if pip is installed by pip.
    local_version_is_older = (
        local_version < remote_version
        and local_version.base_version != remote_version.base_version
    )
    if local_version_is_older:
        return UpgradePrompt(old=str(local_version), new=remote_version_str)
    return None
References was_installed_by_pip().
Referenced by pip_self_version_check().
pip_self_version_check()
None pip._internal.self_outdated_check.pip_self_version_check (PipSession session, optparse.Values options)
Check for an update for pip.
Limit the frequency of checks to once per week. State is stored either in
the active virtualenv or in the user's USER_CACHE_DIR keyed off the prefix
of the pip script path.
Definition at line 224 of file self_outdated_check.py.
def pip_self_version_check(session: PipSession, options: optparse.Values) -> None:
    """Check for an update for pip.
    Limit the frequency of checks to once per week. State is stored either in
    the active virtualenv or in the user's USER_CACHE_DIR keyed off the prefix
    of the pip script path.
    """
    installed_dist = get_default_environment().get_distribution("pip")
    if not installed_dist:
        return
    upgrade_prompt = _self_version_check_logic(
        state=SelfCheckState(cache_dir=options.cache_dir),
        current_time=datetime.datetime.now(datetime.timezone.utc),
        local_version=installed_dist.version,
        get_remote_version=functools.partial(
            _get_current_remote_pip_version, session, options
        ),
    )
    if upgrade_prompt is not None:
        logger.warning("%s", upgrade_prompt, extra={"rich": True})
References _self_version_check_logic().
was_installed_by_pip()
bool pip._internal.self_outdated_check.was_installed_by_pip (str pkg)
Checks whether pkg was installed by pip
This is used not to display the upgrade message when pip is in fact
installed by system package manager, such as dnf on Fedora.
Definition at line 152 of file self_outdated_check.py.
def was_installed_by_pip(pkg: str) -> bool:
    """Checks whether pkg was installed by pip
    This is used not to display the upgrade message when pip is in fact
    installed by system package manager, such as dnf on Fedora.
    """
    dist = get_default_environment().get_distribution(pkg)
    return dist is not None and "pip" == dist.installer
Referenced by _self_version_check_logic().
Variable Documentation
_WEEK
pip._internal.self_outdated_check._WEEK = datetime.timedelta(days=7) protected
Definition at line 31 of file self_outdated_check.py.
logger
pip._internal.self_outdated_check.logger = logging.getLogger(__name__)
Definition at line 33 of file self_outdated_check.py.