Read&Watch: astroid.brain.brain_numpy_utils Namespace Reference
astroid.brain.brain_numpy_utils Namespace Reference
Functions
bool numpy_supports_type_hints ()
tuple[str, str, str] _get_numpy_version ()
infer_numpy_member (src, node, InferenceContext|None context=None)
bool _is_a_numpy_module (Name node)
bool name_looks_like_numpy_member (str member_name, Name node)
bool attribute_looks_like_numpy_member (str member_name, Attribute node)
Variables
tuple NUMPY_VERSION_TYPE_HINTS_SUPPORT = ("1", "20", "0")
Detailed Description
Different utilities for the numpy brains.
Function Documentation
_get_numpy_version()
tuple[str, str, str] astroid.brain.brain_numpy_utils._get_numpy_version () protected
Return the numpy version number if numpy can be imported.
Otherwise returns ('0', '0', '0')
Definition at line 23 of file brain_numpy_utils.py.
def _get_numpy_version() -> tuple[str, str, str]:
    """
    Return the numpy version number if numpy can be imported.
    Otherwise returns ('0', '0', '0')
    """
    try:
        import numpy  # pylint: disable=import-outside-toplevel
        return tuple(numpy.version.version.split("."))
    except (ImportError, AttributeError):
        return ("0", "0", "0")
Referenced by numpy_supports_type_hints().
_is_a_numpy_module()
bool astroid.brain.brain_numpy_utils._is_a_numpy_module (Name node) protected
Returns True if the node is a representation of a numpy module.
For example in :
    import numpy as np
    x = np.linspace(1, 2)
The node <Name.np> is a representation of the numpy module.
:param node: node to test
:return: True if the node is a representation of the numpy module.
Definition at line 42 of file brain_numpy_utils.py.
def _is_a_numpy_module(node: Name) -> bool:
    """
    Returns True if the node is a representation of a numpy module.
    For example in :
        import numpy as np
        x = np.linspace(1, 2)
    The node <Name.np> is a representation of the numpy module.
    :param node: node to test
    :return: True if the node is a representation of the numpy module.
    """
    module_nickname = node.name
    potential_import_target = [
        x for x in node.lookup(module_nickname)[1] if isinstance(x, Import)
    ]
    return any(
        ("numpy", module_nickname) in target.names or ("numpy", None) in target.names
        for target in potential_import_target
    )
Referenced by attribute_looks_like_numpy_member().
attribute_looks_like_numpy_member()
bool astroid.brain.brain_numpy_utils.attribute_looks_like_numpy_member (str member_name, Attribute node)
Returns True if the Attribute is a member of numpy whose
name is member_name.
Definition at line 72 of file brain_numpy_utils.py.
def attribute_looks_like_numpy_member(member_name: str, node: Attribute) -> bool:
    """
    Returns True if the Attribute is a member of numpy whose
    name is member_name.
    """
    return (
        node.attrname == member_name
        and isinstance(node.expr, Name)
        and _is_a_numpy_module(node.expr)
    )
References _is_a_numpy_module().
infer_numpy_member()
astroid.brain.brain_numpy_utils.infer_numpy_member (src, node, InferenceContext | None context = None)
Definition at line 37 of file brain_numpy_utils.py.
def infer_numpy_member(src, node, context: InferenceContext | None = None):
    node = extract_node(src)
    return node.infer(context=context)
name_looks_like_numpy_member()
bool astroid.brain.brain_numpy_utils.name_looks_like_numpy_member (str member_name, Name node)
Returns True if the Name is a member of numpy whose
name is member_name.
Definition at line 64 of file brain_numpy_utils.py.
def name_looks_like_numpy_member(member_name: str, node: Name) -> bool:
    """
    Returns True if the Name is a member of numpy whose
    name is member_name.
    """
    return node.name == member_name and node.root().name.startswith("numpy")
numpy_supports_type_hints()
bool astroid.brain.brain_numpy_utils.numpy_supports_type_hints ()
Returns True if numpy supports type hints.
Definition at line 17 of file brain_numpy_utils.py.
def numpy_supports_type_hints() -> bool:
    """Returns True if numpy supports type hints."""
    np_ver = _get_numpy_version()
    return np_ver and np_ver > NUMPY_VERSION_TYPE_HINTS_SUPPORT
References _get_numpy_version().
Variable Documentation
NUMPY_VERSION_TYPE_HINTS_SUPPORT
tuple astroid.brain.brain_numpy_utils.NUMPY_VERSION_TYPE_HINTS_SUPPORT = ("1", "20", "0")
Definition at line 14 of file brain_numpy_utils.py.