Read&Watch: django.db.backends.base.schema Namespace Reference
django.db.backends.base.schema Namespace Reference
Classes
class BaseDatabaseSchemaEditor
Functions
_is_relevant_relation (relation, altered_field)
_all_related_fields (model)
_related_non_m2m_objects (old_field, new_field)
Variables
logger = logging.getLogger("django.db.backends.schema")
Function Documentation
_all_related_fields()
django.db.backends.base.schema._all_related_fields (model) protected
Definition at line 40 of file schema.py.
def _all_related_fields(model):
    # Related fields must be returned in a deterministic order.
    return sorted(
        model._meta._get_fields(
            forward=False,
            reverse=True,
            include_hidden=True,
            include_parents=False,
        ),
        key=operator.attrgetter("name"),
    )
Referenced by _related_non_m2m_objects().
_is_relevant_relation()
django.db.backends.base.schema._is_relevant_relation (relation, altered_field) protected
When altering the given field, must constraints on its model from the given
relation be temporarily dropped?
Definition at line 24 of file schema.py.
def _is_relevant_relation(relation, altered_field):
    """
    When altering the given field, must constraints on its model from the given
    relation be temporarily dropped?
    """
    field = relation.field
    if field.many_to_many:
        # M2M reverse field
        return False
    if altered_field.primary_key and field.to_fields == [None]:
        # Foreign key constraint on the primary key, which is being altered.
        return True
    # Is the constraint targeting the field being altered?
    return altered_field.name in field.to_fields
Referenced by _related_non_m2m_objects().
_related_non_m2m_objects()
django.db.backends.base.schema._related_non_m2m_objects (old_field, new_field) protected
Definition at line 53 of file schema.py.
def _related_non_m2m_objects(old_field, new_field):
    # Filter out m2m objects from reverse relations.
    # Return (old_relation, new_relation) tuples.
    related_fields = zip(
        (
            obj
            for obj in _all_related_fields(old_field.model)
            if _is_relevant_relation(obj, old_field)
        ),
        (
            obj
            for obj in _all_related_fields(new_field.model)
            if _is_relevant_relation(obj, new_field)
        ),
    )
    for old_rel, new_rel in related_fields:
        yield old_rel, new_rel
        yield from _related_non_m2m_objects(
            old_rel.remote_field,
            new_rel.remote_field,
        )
References _all_related_fields(), _is_relevant_relation(), and _related_non_m2m_objects().
Referenced by django.db.backends.base.schema.BaseDatabaseSchemaEditor._alter_field(), and _related_non_m2m_objects().
Variable Documentation
logger
django.db.backends.base.schema.logger = logging.getLogger("django.db.backends.schema")
Definition at line 21 of file schema.py.