Read&Watch: pip._vendor.certifi.core Namespace Reference
pip._vendor.certifi.core Namespace Reference
Functions
None exit_cacert_ctx ()
str where ()
str contents ()
str read_text (Package package, Resource resource, str encoding='utf-8', str errors='strict')
Variables
_CACERT_CTX = None
_CACERT_PATH = None
Package = Union[types.ModuleType, str]
Resource = Union[str, "os.PathLike"]
Detailed Description
certifi.py
~~~~~~~~~~
This module returns the installation location of cacert.pem or its contents.
Function Documentation
contents()
str pip._vendor.certifi.core.contents ()
Definition at line 46 of file core.py.
    def contents() -> str:
        return files("pip._vendor.certifi").joinpath("cacert.pem").read_text(encoding="ascii")
References read_text().
exit_cacert_ctx()
None pip._vendor.certifi.core.exit_cacert_ctx ()
Definition at line 10 of file core.py.
def exit_cacert_ctx() -> None:
    _CACERT_CTX.__exit__(None, None, None)  # type: ignore[union-attr]
read_text()
str pip._vendor.certifi.core.read_text (Package package, Resource resource, str encoding = 'utf-8', str errors = 'strict')
Definition at line 97 of file core.py.
    ) -> str:
        with open(where(), encoding=encoding) as data:
            return data.read()
References read_text(), and where().
Referenced by contents(), and read_text().
where()
str pip._vendor.certifi.core.where ()
Definition at line 21 of file core.py.
    def where() -> str:
        # This is slightly terrible, but we want to delay extracting the file
        # in cases where we're inside of a zipimport situation until someone
        # actually calls where(), but we don't want to re-extract the file
        # on every call of where(), so we'll do it once then store it in a
        # global variable.
        global _CACERT_CTX
        global _CACERT_PATH
        if _CACERT_PATH is None:
            # This is slightly janky, the importlib.resources API wants you to
            # manage the cleanup of this file, so it doesn't actually return a
            # path, it returns a context manager that will give you the path
            # when you enter it and will do any cleanup when you leave it. In
            # the common case of not needing a temporary file, it will just
            # return the file system location and the __exit__() is a no-op.
            #
            # We also have to hold onto the actual context manager, because
            # it will do the cleanup whenever it gets garbage collected, so
            # we will also store that at the global level as well.
            _CACERT_CTX = as_file(files("pip._vendor.certifi").joinpath("cacert.pem"))
            _CACERT_PATH = str(_CACERT_CTX.__enter__())
            atexit.register(exit_cacert_ctx)
        return _CACERT_PATH
Referenced by read_text().
Variable Documentation
_CACERT_CTX
pip._vendor.certifi.core._CACERT_CTX = None protected
Definition at line 18 of file core.py.
_CACERT_PATH
pip._vendor.certifi.core._CACERT_PATH = None protected
Definition at line 19 of file core.py.
Package
pip._vendor.certifi.core.Package = Union[types.ModuleType, str]
Definition at line 90 of file core.py.
Resource
pip._vendor.certifi.core.Resource = Union[str, "os.PathLike"]
Definition at line 91 of file core.py.