Read&Watch: astroid.bases Namespace Reference
astroid.bases Namespace Reference
Classes
class AsyncGenerator
class BaseInstance
class BoundMethod
class Generator
class Instance
class Proxy
class UnboundMethod
class UnionType
Functions
bool _is_property (nodes.FunctionDef|UnboundMethod meth, InferenceContext|None context=None)
collections.abc.Generator[InferenceResult] _infer_stmts (Iterable[InferenceResult] stmts, InferenceContext|None context, nodes.NodeNG|BaseInstance|None frame=None)
bool|UninferableBase _infer_method_result_truth (Instance instance, str method_name, InferenceContext context)
Variables
dict PROPERTIES = {"builtins.property", "abc.abstractproperty"}
dict POSSIBLE_PROPERTIES
Detailed Description
This module contains base classes and functions for the nodes and some
inference utils.
Function Documentation
_infer_method_result_truth()
bool | UninferableBase astroid.bases._infer_method_result_truth (Instance instance, str method_name, InferenceContext context) protected
Definition at line 200 of file bases.py.
) -> bool | UninferableBase:
    # Get the method from the instance and try to infer
    # its return's truth value.
    meth = next(instance.igetattr(method_name, context=context), None)
    if meth and hasattr(meth, "infer_call_result"):
        if not meth.callable():
            return Uninferable
        try:
            context.callcontext = CallContext(args=[], callee=meth)
            for value in meth.infer_call_result(instance, context=context):
                if isinstance(value, UninferableBase):
                    return value
                try:
                    inferred = next(value.infer(context=context))
                except StopIteration as e:
                    raise InferenceError(context=context) from e
                return inferred.bool_value()
        except InferenceError:
            pass
    return Uninferable
Referenced by astroid.bases.Instance.bool_value().
_infer_stmts()
collections.abc.Generator[InferenceResult] astroid.bases._infer_stmts (Iterable[InferenceResult] stmts, InferenceContext | None context, nodes.NodeNG | BaseInstance | None frame = None) protected
Return an iterator on statements inferred by each statement in *stmts*.
Definition at line 146 of file bases.py.
) -> collections.abc.Generator[InferenceResult]:
    """Return an iterator on statements inferred by each statement in *stmts*."""
    inferred = False
    constraint_failed = False
    if context is not None:
        name = context.lookupname
        context = context.clone()
        if name is not None:
            constraints = context.constraints.get(name, {})
        else:
            constraints = {}
    else:
        name = None
        constraints = {}
        context = InferenceContext()
    for stmt in stmts:
        if isinstance(stmt, UninferableBase):
            yield stmt
            inferred = True
            continue
        context.lookupname = stmt._infer_name(frame, name)
        try:
            stmt_constraints: set[Constraint] = set()
            for constraint_stmt, potential_constraints in constraints.items():
                if not constraint_stmt.parent_of(stmt):
                    stmt_constraints.update(potential_constraints)
            for inf in stmt.infer(context=context):
                if all(constraint.satisfied_by(inf) for constraint in stmt_constraints):
                    yield inf
                    inferred = True
                else:
                    constraint_failed = True
        except NameInferenceError:
            continue
        except InferenceError:
            yield Uninferable
            inferred = True
    if not inferred and constraint_failed:
        yield Uninferable
    elif not inferred:
        raise InferenceError(
            "Inference failed for all members of {stmts!r}.",
            stmts=stmts,
            frame=frame,
            context=context,
        )
Referenced by astroid.bases.BaseInstance.igetattr().
_is_property()
bool astroid.bases._is_property (nodes.FunctionDef | UnboundMethod meth, InferenceContext | None context = None) protected
Definition at line 68 of file bases.py.
) -> bool:
    decoratornames = meth.decoratornames(context=context)
    if PROPERTIES.intersection(decoratornames):
        return True
    stripped = {
        name.split(".")[-1]
        for name in decoratornames
        if not isinstance(name, UninferableBase)
    }
    if any(name in stripped for name in POSSIBLE_PROPERTIES):
        return True
    # Lookup for subclasses of *property*
    if not meth.decorators:
        return False
    for decorator in meth.decorators.nodes or ():
        inferred = safe_infer(decorator, context=context)
        if inferred is None or isinstance(inferred, UninferableBase):
            continue
        if isinstance(inferred, nodes.ClassDef):
            for base_class in inferred.bases:
                if not isinstance(base_class, nodes.Name):
                    continue
                module, _ = base_class.lookup(base_class.name)
                if (
                    isinstance(module, nodes.Module)
                    and module.name == "builtins"
                    and base_class.name == "property"
                ):
                    return True
    return False
Referenced by astroid.bases.BaseInstance._wrap_attr().
Variable Documentation
POSSIBLE_PROPERTIES
dict astroid.bases.POSSIBLE_PROPERTIES
Initial value:
=  {
    "cached_property",
    "cachedproperty",
    "lazyproperty",
    "lazy_property",
    "reify",
    "lazyattribute",
    "lazy_attribute",
    "LazyProperty",
    "lazy",
    "cache_readonly",
    "DynamicClassAttribute",
}
Definition at line 53 of file bases.py.
PROPERTIES
dict astroid.bases.PROPERTIES = {"builtins.property", "abc.abstractproperty"}
Definition at line 41 of file bases.py.