Read&Watch: pip._internal.metadata.importlib._compat Namespace Reference
pip._internal.metadata.importlib._compat Namespace Reference
Classes
class BadMetadata
class BasePath
Functions
Optional[BasePath] get_info_location (importlib.metadata.Distribution d)
Tuple[Optional[str], Optional[str]] parse_name_and_version_from_info_directory (importlib.metadata.Distribution dist)
NormalizedName get_dist_canonical_name (importlib.metadata.Distribution dist)
Function Documentation
get_dist_canonical_name()
NormalizedName pip._internal.metadata.importlib._compat.get_dist_canonical_name (importlib.metadata.Distribution dist)
Get the distribution's normalized name.
The ``name`` attribute is only available in Python 3.10 or later. We are
targeting exactly that, but Mypy does not know this.
Definition at line 73 of file _compat.py.
def get_dist_canonical_name(dist: importlib.metadata.Distribution) -> NormalizedName:
    """Get the distribution's normalized name.
    The ``name`` attribute is only available in Python 3.10 or later. We are
    targeting exactly that, but Mypy does not know this.
    """
    if name := parse_name_and_version_from_info_directory(dist)[0]:
        return canonicalize_name(name)
    name = cast(Any, dist).name
    if not isinstance(name, str):
        raise BadMetadata(dist, reason="invalid metadata entry 'name'")
    return canonicalize_name(name)
References parse_name_and_version_from_info_directory().
get_info_location()
Optional[BasePath] pip._internal.metadata.importlib._compat.get_info_location (importlib.metadata.Distribution d)
Find the path to the distribution's metadata directory.
HACK: This relies on importlib.metadata's private ``_path`` attribute. Not
all distributions exist on disk, so importlib.metadata is correct to not
expose the attribute as public. But pip's code base is old and not as clean,
so we do this to avoid having to rewrite too many things. Hopefully we can
eliminate this some day.
Definition at line 37 of file _compat.py.
def get_info_location(d: importlib.metadata.Distribution) -> Optional[BasePath]:
    """Find the path to the distribution's metadata directory.
    HACK: This relies on importlib.metadata's private ``_path`` attribute. Not
    all distributions exist on disk, so importlib.metadata is correct to not
    expose the attribute as public. But pip's code base is old and not as clean,
    so we do this to avoid having to rewrite too many things. Hopefully we can
    eliminate this some day.
    """
    return getattr(d, "_path", None)
Referenced by parse_name_and_version_from_info_directory().
parse_name_and_version_from_info_directory()
Tuple[Optional[str], Optional[str]] pip._internal.metadata.importlib._compat.parse_name_and_version_from_info_directory (importlib.metadata.Distribution dist)
Get a name and version from the metadata directory name.
This is much faster than reading distribution metadata.
Definition at line 49 of file _compat.py.
) -> Tuple[Optional[str], Optional[str]]:
    """Get a name and version from the metadata directory name.
    This is much faster than reading distribution metadata.
    """
    info_location = get_info_location(dist)
    if info_location is None:
        return None, None
    stem, suffix = os.path.splitext(info_location.name)
    if suffix == ".dist-info":
        name, sep, version = stem.partition("-")
        if sep:
            return name, version
    if suffix == ".egg-info":
        name = stem.split("-", 1)[0]
        return name, None
    return None, None
References get_info_location().
Referenced by get_dist_canonical_name().