Read&Watch: django.utils.timezone Namespace Reference
django.utils.timezone Namespace Reference
Classes
class override
Functions
get_fixed_timezone (offset)
get_default_timezone ()
get_default_timezone_name ()
get_current_timezone ()
get_current_timezone_name ()
_get_timezone_name (timezone)
activate (timezone)
deactivate ()
template_localtime (value, use_tz=None)
localtime (value=None, timezone=None)
localdate (value=None, timezone=None)
now ()
is_aware (value)
is_naive (value)
make_aware (value, timezone=None)
make_naive (value, timezone=None)
_datetime_ambiguous_or_imaginary (dt, tz)
Variables
_active = Local()
Detailed Description
Timezone-related classes and functions.
Function Documentation
_datetime_ambiguous_or_imaginary()
django.utils.timezone._datetime_ambiguous_or_imaginary (dt, tz) protected
Definition at line 258 of file timezone.py.
def _datetime_ambiguous_or_imaginary(dt, tz):
    return tz.utcoffset(dt.replace(fold=not dt.fold)) != tz.utcoffset(dt)
_get_timezone_name()
django.utils.timezone._get_timezone_name (timezone) protected
Return the offset for fixed offset timezones, or the name of timezone if
not set.
Definition at line 74 of file timezone.py.
def _get_timezone_name(timezone):
    """
    Return the offset for fixed offset timezones, or the name of timezone if
    not set.
    """
    return timezone.tzname(None) or str(timezone)
# Timezone selection functions.
# These functions don't change os.environ['TZ'] and call time.tzset()
# because it isn't thread safe.
Referenced by get_current_timezone_name(), and get_default_timezone_name().
activate()
django.utils.timezone.activate (timezone)
Set the time zone for the current thread.
The ``timezone`` argument must be an instance of a tzinfo subclass or a
time zone name.
Definition at line 88 of file timezone.py.
def activate(timezone):
    """
    Set the time zone for the current thread.
    The ``timezone`` argument must be an instance of a tzinfo subclass or a
    time zone name.
    """
    if isinstance(timezone, tzinfo):
        _active.value = timezone
    elif isinstance(timezone, str):
        _active.value = zoneinfo.ZoneInfo(timezone)
    else:
        raise ValueError("Invalid timezone: %r" % timezone)
deactivate()
django.utils.timezone.deactivate ()
Unset the time zone for the current thread.
Django will then use the time zone defined by settings.TIME_ZONE.
Definition at line 103 of file timezone.py.
def deactivate():
    """
    Unset the time zone for the current thread.
    Django will then use the time zone defined by settings.TIME_ZONE.
    """
    if hasattr(_active, "value"):
        del _active.value
Referenced by django.utils.timezone.override.__exit__().
get_current_timezone()
django.utils.timezone.get_current_timezone ()
Return the currently active time zone as a tzinfo instance.
Definition at line 64 of file timezone.py.
def get_current_timezone():
    """Return the currently active time zone as a tzinfo instance."""
    return getattr(_active, "value", get_default_timezone())
References get_default_timezone().
Referenced by get_current_timezone_name(), localtime(), make_aware(), and make_naive().
get_current_timezone_name()
django.utils.timezone.get_current_timezone_name ()
Return the name of the currently active time zone.
Definition at line 69 of file timezone.py.
def get_current_timezone_name():
    """Return the name of the currently active time zone."""
    return _get_timezone_name(get_current_timezone())
References _get_timezone_name(), and get_current_timezone().
get_default_timezone()
django.utils.timezone.get_default_timezone ()
Return the default time zone as a tzinfo instance.
This is the time zone defined by settings.TIME_ZONE.
Definition at line 46 of file timezone.py.
def get_default_timezone():
    """
    Return the default time zone as a tzinfo instance.
    This is the time zone defined by settings.TIME_ZONE.
    """
    return zoneinfo.ZoneInfo(settings.TIME_ZONE)
# This function exists for consistency with get_current_timezone_name
Referenced by get_current_timezone(), and get_default_timezone_name().
get_default_timezone_name()
django.utils.timezone.get_default_timezone_name ()
Return the name of the default time zone.
Definition at line 56 of file timezone.py.
def get_default_timezone_name():
    """Return the name of the default time zone."""
    return _get_timezone_name(get_default_timezone())
References _get_timezone_name(), and get_default_timezone().
get_fixed_timezone()
django.utils.timezone.get_fixed_timezone (offset)
Return a tzinfo instance with a fixed offset from UTC.
Definition at line 33 of file timezone.py.
def get_fixed_timezone(offset):
    """Return a tzinfo instance with a fixed offset from UTC."""
    if isinstance(offset, timedelta):
        offset = offset.total_seconds() // 60
    sign = "-" if offset < 0 else "+"
    hhmm = "%02d%02d" % divmod(abs(offset), 60)
    name = sign + hhmm
    return timezone(timedelta(minutes=offset), name)
# In order to avoid accessing settings at compile time,
# wrap the logic in a function and cache the result.
@functools.lru_cache
is_aware()
django.utils.timezone.is_aware (value)
Determine if a given datetime.datetime is aware.
The concept is defined in Python's docs:
https://docs.python.org/library/datetime.html#datetime.tzinfo
Assuming value.tzinfo is either None or a proper datetime.tzinfo,
value.utcoffset() implements the appropriate logic.
Definition at line 211 of file timezone.py.
def is_aware(value):
    """
    Determine if a given datetime.datetime is aware.
    The concept is defined in Python's docs:
    https://docs.python.org/library/datetime.html#datetime.tzinfo
    Assuming value.tzinfo is either None or a proper datetime.tzinfo,
    value.utcoffset() implements the appropriate logic.
    """
    return value.utcoffset() is not None
Referenced by make_aware().
is_naive()
django.utils.timezone.is_naive (value)
Determine if a given datetime.datetime is naive.
The concept is defined in Python's docs:
https://docs.python.org/library/datetime.html#datetime.tzinfo
Assuming value.tzinfo is either None or a proper datetime.tzinfo,
value.utcoffset() implements the appropriate logic.
Definition at line 224 of file timezone.py.
def is_naive(value):
    """
    Determine if a given datetime.datetime is naive.
    The concept is defined in Python's docs:
    https://docs.python.org/library/datetime.html#datetime.tzinfo
    Assuming value.tzinfo is either None or a proper datetime.tzinfo,
    value.utcoffset() implements the appropriate logic.
    """
    return value.utcoffset() is None
Referenced by localtime(), make_naive(), and template_localtime().
localdate()
django.utils.timezone.localdate (value = None, timezone = None)
Convert an aware datetime to local time and return the value's date.
Only aware datetimes are allowed. When value is omitted, it defaults to
now().
Local time is defined by the current time zone, unless another time zone is
specified.
Definition at line 187 of file timezone.py.
def localdate(value=None, timezone=None):
    """
    Convert an aware datetime to local time and return the value's date.
    Only aware datetimes are allowed. When value is omitted, it defaults to
    now().
    Local time is defined by the current time zone, unless another time zone is
    specified.
    """
    return localtime(value, timezone).date()
References localtime().
localtime()
django.utils.timezone.localtime (value = None, timezone = None)
Convert an aware datetime.datetime to local time.
Only aware datetimes are allowed. When value is omitted, it defaults to
now().
Local time is defined by the current time zone, unless another time zone
is specified.
Definition at line 167 of file timezone.py.
def localtime(value=None, timezone=None):
    """
    Convert an aware datetime.datetime to local time.
    Only aware datetimes are allowed. When value is omitted, it defaults to
    now().
    Local time is defined by the current time zone, unless another time zone
    is specified.
    """
    if value is None:
        value = now()
    if timezone is None:
        timezone = get_current_timezone()
    # Emulate the behavior of astimezone() on Python < 3.6.
    if is_naive(value):
        raise ValueError("localtime() cannot be applied to a naive datetime")
    return value.astimezone(timezone)
References get_current_timezone(), is_naive(), and now().
Referenced by localdate(), and template_localtime().
make_aware()
django.utils.timezone.make_aware (value, timezone = None)
Make a naive datetime.datetime in a given time zone aware.
Definition at line 237 of file timezone.py.
def make_aware(value, timezone=None):
    """Make a naive datetime.datetime in a given time zone aware."""
    if timezone is None:
        timezone = get_current_timezone()
    # Check that we won't overwrite the timezone of an aware datetime.
    if is_aware(value):
        raise ValueError("make_aware expects a naive datetime, got %s" % value)
    # This may be wrong around DST changes!
    return value.replace(tzinfo=timezone)
References get_current_timezone(), and is_aware().
make_naive()
django.utils.timezone.make_naive (value, timezone = None)
Make an aware datetime.datetime naive in a given time zone.
Definition at line 248 of file timezone.py.
def make_naive(value, timezone=None):
    """Make an aware datetime.datetime naive in a given time zone."""
    if timezone is None:
        timezone = get_current_timezone()
    # Emulate the behavior of astimezone() on Python < 3.6.
    if is_naive(value):
        raise ValueError("make_naive() cannot be applied to a naive datetime")
    return value.astimezone(timezone).replace(tzinfo=None)
References get_current_timezone(), and is_naive().
now()
django.utils.timezone.now ()
Return an aware or naive datetime.datetime, depending on settings.USE_TZ.
Definition at line 200 of file timezone.py.
def now():
    """
    Return an aware or naive datetime.datetime, depending on settings.USE_TZ.
    """
    return datetime.now(tz=timezone.utc if settings.USE_TZ else None)
# By design, these four functions don't perform any checks on their arguments.
# The caller should ensure that they don't receive an invalid value like None.
Referenced by localtime().
template_localtime()
django.utils.timezone.template_localtime (value, use_tz = None)
Check if value is a datetime and converts it to local time if necessary.
If use_tz is provided and is not None, that will force the value to
be converted (or not), overriding the value of settings.USE_TZ.
This function is designed for use by the template engine.
Definition at line 146 of file timezone.py.
def template_localtime(value, use_tz=None):
    """
    Check if value is a datetime and converts it to local time if necessary.
    If use_tz is provided and is not None, that will force the value to
    be converted (or not), overriding the value of settings.USE_TZ.
    This function is designed for use by the template engine.
    """
    should_convert = (
        isinstance(value, datetime)
        and (settings.USE_TZ if use_tz is None else use_tz)
        and not is_naive(value)
        and getattr(value, "convert_to_local_time", True)
    )
    return localtime(value) if should_convert else value
# Utilities
References is_naive(), and localtime().
Variable Documentation
_active
django.utils.timezone._active = Local() protected
Definition at line 61 of file timezone.py.