Read&Watch: PIL.GifImagePlugin Namespace Reference
PIL.GifImagePlugin Namespace Reference
Classes
class _Frame
class GifImageFile
Image plugin for GIF images.
class LoadingStrategy
Functions
bool _accept (bytes prefix)
Image.Image _normalize_mode (Image.Image im)
Image.Image _normalize_palette (Image.Image im, _Palette|None palette, dict[str, Any] info)
None _write_single_frame (Image.Image im, IO[bytes] fp, _Palette|None palette)
tuple[Image.Image, tuple[int, int, int, int]|None] _getbbox (Image.Image base_im, Image.Image im_frame)
bool _write_multiple_frames (Image.Image im, IO[bytes] fp, _Palette|None palette)
None _save_all (Image.Image im, IO[bytes] fp, str|bytes filename)
None _save (Image.Image im, IO[bytes] fp, str|bytes filename, bool save_all=False)
int get_interlace (Image.Image im)
None _write_local_header (IO[bytes] fp, Image.Image im, tuple[int, int] offset, int flags)
None _save_netpbm (Image.Image im, IO[bytes] fp, str|bytes filename)
list[int]|None _get_optimize (Image.Image im, dict[str, Any] info)
int _get_color_table_size (bytes palette_bytes)
bytes _get_header_palette (bytes palette_bytes)
bytes _get_palette_bytes (Image.Image im)
int _get_background (Image.Image im, int|tuple[int, int, int]|tuple[int, int, int, int]|None info_background)
list[bytes] _get_global_header (Image.Image im, dict[str, Any] info)
None _write_frame_data (IO[bytes] fp, Image.Image im_frame, tuple[int, int] offset, dict[str, Any] params)
tuple[list[bytes], list[int]|None] getheader (Image.Image im, _Palette|None palette=None, dict[str, Any]|None info=None)
list[bytes] getdata (Image.Image im, tuple[int, int] offset=(0, 0), **Any params)
Variables
LOADING_STRATEGY = LoadingStrategy.RGB_AFTER_FIRST
dict RAWMODE = {"1": "L", "L": "L", "P": "P"}
_Palette = Union[bytes, bytearray, list[int], ImagePalette.ImagePalette]
bool _FORCE_OPTIMIZE = False
Function Documentation
_accept()
bool PIL.GifImagePlugin._accept (bytes prefix) protected
Definition at line 69 of file GifImagePlugin.py.
def _accept(prefix: bytes) -> bool:
    return prefix[:6] in [b"GIF87a", b"GIF89a"]
Referenced by PIL.GifImagePlugin.GifImageFile._open().
_get_background()
int PIL.GifImagePlugin._get_background (Image.Image im, int | tuple[int, int, int] | tuple[int, int, int, int] | None info_background) protected
Definition at line 1001 of file GifImagePlugin.py.
) -> int:
    background = 0
    if info_background:
        if isinstance(info_background, tuple):
            # WebPImagePlugin stores an RGBA value in info["background"]
            # So it must be converted to the same format as GifImagePlugin's
            # info["background"] - a global color table index
            assert im.palette is not None
            try:
                background = im.palette.getcolor(info_background, im)
            except ValueError as e:
                if str(e) not in (
                    # If all 256 colors are in use,
                    # then there is no need for the background color
                    "cannot allocate more than 256 colors",
                    # Ignore non-opaque WebP background
                    "cannot add non-opaque RGBA color to RGB palette",
                ):
                    raise
        else:
            background = info_background
    return background
Referenced by _write_multiple_frames().
_get_color_table_size()
int PIL.GifImagePlugin._get_color_table_size (bytes palette_bytes) protected
Definition at line 957 of file GifImagePlugin.py.
def _get_color_table_size(palette_bytes: bytes) -> int:
    # calculate the palette size for the header
    if not palette_bytes:
        return 0
    elif len(palette_bytes) < 9:
        return 1
    else:
        return math.ceil(math.log(len(palette_bytes) // 3, 2)) - 1
Referenced by _get_header_palette(), and _write_local_header().
_get_global_header()
list[bytes] PIL.GifImagePlugin._get_global_header (Image.Image im, dict[str, Any] info) protected
Return a list of strings representing a GIF header
Definition at line 1028 of file GifImagePlugin.py.
def _get_global_header(im: Image.Image, info: dict[str, Any]) -> list[bytes]:
    """Return a list of strings representing a GIF header"""
    # Header Block
    # https://www.matthewflickinger.com/lab/whatsinagif/bits_and_bytes.asp
    version = b"87a"
    if im.info.get("version") == b"89a" or (
        info
        and (
            "transparency" in info
            or info.get("loop") is not None
            or info.get("duration")
            or info.get("comment")
        )
    ):
        version = b"89a"
    background = _get_background(im, info.get("background"))
    palette_bytes = _get_palette_bytes(im)
    color_table_size = _get_color_table_size(palette_bytes)
    header = [
        b"GIF"  # signature
        + version  # version
        + o16(im.size[0])  # canvas width
        + o16(im.size[1]),  # canvas height
        # Logical Screen Descriptor
        # size of global color table + global color table flag
        o8(color_table_size + 128),  # packed fields
        # background + reserved/aspect
        o8(background) + o8(0),
        # Global Color Table
        _get_header_palette(palette_bytes),
    ]
    if info.get("loop") is not None:
        header.append(
            b"!"
            + o8(255)  # extension intro
            + o8(11)
            + b"NETSCAPE2.0"
            + o8(3)
            + o8(1)
            + o16(info["loop"])  # number of loops
            + o8(0)
        )
    if info.get("comment"):
        comment_block = b"!" + o8(254)  # extension intro
        comment = info["comment"]
        if isinstance(comment, str):
            comment = comment.encode()
        for i in range(0, len(comment), 255):
            subblock = comment[i : i + 255]
            comment_block += o8(len(subblock)) + subblock
        comment_block += o8(0)
        header.append(comment_block)
    return header
Referenced by _write_multiple_frames(), and _write_single_frame().
_get_header_palette()
bytes PIL.GifImagePlugin._get_header_palette (bytes palette_bytes) protected
Returns the palette, null padded to the next power of 2 (*3) bytes
suitable for direct inclusion in the GIF header
:param palette_bytes: Unpadded palette bytes, in RGBRGB form
:returns: Null padded palette
Definition at line 967 of file GifImagePlugin.py.
def _get_header_palette(palette_bytes: bytes) -> bytes:
    """
    Returns the palette, null padded to the next power of 2 (*3) bytes
    suitable for direct inclusion in the GIF header
    :param palette_bytes: Unpadded palette bytes, in RGBRGB form
    :returns: Null padded palette
    """
    color_table_size = _get_color_table_size(palette_bytes)
    # add the missing amount of bytes
    # the palette has to be 2<<n in size
    actual_target_size_diff = (2 << color_table_size) - len(palette_bytes) // 3
    if actual_target_size_diff > 0:
        palette_bytes += o8(0) * 3 * actual_target_size_diff
    return palette_bytes
References _get_color_table_size().
Referenced by _write_local_header().
_get_optimize()
list[int] | None PIL.GifImagePlugin._get_optimize (Image.Image im, dict[str, Any] info) protected
Palette optimization is a potentially expensive operation.
This function determines if the palette should be optimized using
some heuristics, then returns the list of palette entries in use.
:param im: Image object
:param info: encoderinfo
:returns: list of indexes of palette entries in use, or None
Definition at line 909 of file GifImagePlugin.py.
def _get_optimize(im: Image.Image, info: dict[str, Any]) -> list[int] | None:
    """
    Palette optimization is a potentially expensive operation.
    This function determines if the palette should be optimized using
    some heuristics, then returns the list of palette entries in use.
    :param im: Image object
    :param info: encoderinfo
    :returns: list of indexes of palette entries in use, or None
    """
    if im.mode in ("P", "L") and info and info.get("optimize"):
        # Potentially expensive operation.
        # The palette saves 3 bytes per color not used, but palette
        # lengths are restricted to 3*(2**N) bytes. Max saving would
        # be 768 -> 6 bytes if we went all the way down to 2 colors.
        # * If we're over 128 colors, we can't save any space.
        # * If there aren't any holes, it's not worth collapsing.
        # * If we have a 'large' image, the palette is in the noise.
        # create the new palette if not every color is used
        optimise = _FORCE_OPTIMIZE or im.mode == "L"
        if optimise or im.width * im.height < 512 * 512:
            # check which colors are used
            used_palette_colors = []
            for i, count in enumerate(im.histogram()):
                if count:
                    used_palette_colors.append(i)
            if optimise or max(used_palette_colors) >= len(used_palette_colors):
                return used_palette_colors
            assert im.palette is not None
            num_palette_colors = len(im.palette.palette) // Image.getmodebands(
                im.palette.mode
            )
            current_palette_size = 1 << (num_palette_colors - 1).bit_length()
            if (
                # check that the palette would become smaller when saved
                len(used_palette_colors) <= current_palette_size // 2
                # check that the palette is not already the smallest possible size
                and current_palette_size > 2
            ):
                return used_palette_colors
    return None
Referenced by _normalize_palette().
_get_palette_bytes()
bytes PIL.GifImagePlugin._get_palette_bytes (Image.Image im) protected
Gets the palette for inclusion in the gif header
:param im: Image object
:returns: Bytes, len<=768 suitable for inclusion in gif header
Definition at line 985 of file GifImagePlugin.py.
def _get_palette_bytes(im: Image.Image) -> bytes:
    """
    Gets the palette for inclusion in the gif header
    :param im: Image object
    :returns: Bytes, len<=768 suitable for inclusion in gif header
    """
    if not im.palette:
        return b""
    palette = bytes(im.palette.palette)
    if im.palette.mode == "RGBA":
        palette = b"".join(palette[i * 4 : i * 4 + 3] for i in range(len(palette) // 3))
    return palette
Referenced by _write_local_header().
_getbbox()
tuple[Image.Image, tuple[int, int, int, int] | None] PIL.GifImagePlugin._getbbox (Image.Image base_im, Image.Image im_frame) protected
Definition at line 631 of file GifImagePlugin.py.
) -> tuple[Image.Image, tuple[int, int, int, int] | None]:
    palette_bytes = [
        bytes(im.palette.palette) if im.palette else b"" for im in (base_im, im_frame)
    ]
    if palette_bytes[0] != palette_bytes[1]:
        im_frame = im_frame.convert("RGBA")
        base_im = base_im.convert("RGBA")
    delta = ImageChops.subtract_modulo(im_frame, base_im)
    return delta, delta.getbbox(alpha_only=False)
Referenced by _write_multiple_frames().
_normalize_mode()
Image.Image PIL.GifImagePlugin._normalize_mode (Image.Image im) protected
Takes an image (or frame), returns an image in a mode that is appropriate
for saving in a Gif.
It may return the original image, or it may return an image converted to
palette or 'L' mode.
:param im: Image object
:returns: Image object
Definition at line 503 of file GifImagePlugin.py.
def _normalize_mode(im: Image.Image) -> Image.Image:
    """
    Takes an image (or frame), returns an image in a mode that is appropriate
    for saving in a Gif.
    It may return the original image, or it may return an image converted to
    palette or 'L' mode.
    :param im: Image object
    :returns: Image object
    """
    if im.mode in RAWMODE:
        im.load()
        return im
    if Image.getmodebase(im.mode) == "RGB":
        im = im.convert("P", palette=Image.Palette.ADAPTIVE)
        assert im.palette is not None
        if im.palette.mode == "RGBA":
            for rgba in im.palette.colors:
                if rgba[3] == 0:
                    im.info["transparency"] = im.palette.colors[rgba]
                    break
        return im
    return im.convert("L")
Referenced by _write_multiple_frames(), and _write_single_frame().
_normalize_palette()
Image.Image PIL.GifImagePlugin._normalize_palette (Image.Image im, _Palette | None palette, dict[str, Any] info) protected
Normalizes the palette for image.
  - Sets the palette to the incoming palette, if provided.
  - Ensures that there's a palette for L mode images
  - Optimizes the palette if necessary/desired.
:param im: Image object
:param palette: bytes object containing the source palette, or ....
:param info: encoderinfo
:returns: Image object
Definition at line 532 of file GifImagePlugin.py.
) -> Image.Image:
    """
    Normalizes the palette for image.
      - Sets the palette to the incoming palette, if provided.
      - Ensures that there's a palette for L mode images
      - Optimizes the palette if necessary/desired.
    :param im: Image object
    :param palette: bytes object containing the source palette, or ....
    :param info: encoderinfo
    :returns: Image object
    """
    source_palette = None
    if palette:
        # a bytes palette
        if isinstance(palette, (bytes, bytearray, list)):
            source_palette = bytearray(palette[:768])
        if isinstance(palette, ImagePalette.ImagePalette):
            source_palette = bytearray(palette.palette)
    if im.mode == "P":
        if not source_palette:
            im_palette = im.getpalette(None)
            assert im_palette is not None
            source_palette = bytearray(im_palette)
    else:  # L-mode
        if not source_palette:
            source_palette = bytearray(i // 3 for i in range(768))
        im.palette = ImagePalette.ImagePalette("RGB", palette=source_palette)
    assert source_palette is not None
    if palette:
        used_palette_colors: list[int | None] = []
        assert im.palette is not None
        for i in range(0, len(source_palette), 3):
            source_color = tuple(source_palette[i : i + 3])
            index = im.palette.colors.get(source_color)
            if index in used_palette_colors:
                index = None
            used_palette_colors.append(index)
        for i, index in enumerate(used_palette_colors):
            if index is None:
                for j in range(len(used_palette_colors)):
                    if j not in used_palette_colors:
                        used_palette_colors[i] = j
                        break
        dest_map: list[int] = []
        for index in used_palette_colors:
            assert index is not None
            dest_map.append(index)
        im = im.remap_palette(dest_map)
    else:
        optimized_palette_colors = _get_optimize(im, info)
        if optimized_palette_colors is not None:
            im = im.remap_palette(optimized_palette_colors, source_palette)
            if "transparency" in info:
                try:
                    info["transparency"] = optimized_palette_colors.index(
                        info["transparency"]
                    )
                except ValueError:
                    del info["transparency"]
            return im
    assert im.palette is not None
    im.palette.palette = source_palette
    return im
References _get_optimize().
Referenced by _write_multiple_frames(), and _write_single_frame().
_save()
None PIL.GifImagePlugin._save (Image.Image im, IO[bytes] fp, str | bytes filename, bool save_all = False) protected
Definition at line 777 of file GifImagePlugin.py.
) -> None:
    # header
    if "palette" in im.encoderinfo or "palette" in im.info:
        palette = im.encoderinfo.get("palette", im.info.get("palette"))
    else:
        palette = None
        im.encoderinfo.setdefault("optimize", True)
    if not save_all or not _write_multiple_frames(im, fp, palette):
        _write_single_frame(im, fp, palette)
    fp.write(b";")  # end of file
    if hasattr(fp, "flush"):
        fp.flush()
References _write_multiple_frames(), and _write_single_frame().
Referenced by _save_all().
_save_all()
None PIL.GifImagePlugin._save_all (Image.Image im, IO[bytes] fp, str | bytes filename) protected
Definition at line 773 of file GifImagePlugin.py.
def _save_all(im: Image.Image, fp: IO[bytes], filename: str | bytes) -> None:
    _save(im, fp, filename, save_all=True)
References _save().
_save_netpbm()
None PIL.GifImagePlugin._save_netpbm (Image.Image im, IO[bytes] fp, str | bytes filename) protected
Definition at line 856 of file GifImagePlugin.py.
def _save_netpbm(im: Image.Image, fp: IO[bytes], filename: str | bytes) -> None:
    # Unused by default.
    # To use, uncomment the register_save call at the end of the file.
    #
    # If you need real GIF compression and/or RGB quantization, you
    # can use the external NETPBM/PBMPLUS utilities.  See comments
    # below for information on how to enable this.
    tempfile = im._dump()
    try:
        with open(filename, "wb") as f:
            if im.mode != "RGB":
                subprocess.check_call(
                    ["ppmtogif", tempfile], stdout=f, stderr=subprocess.DEVNULL
                )
            else:
                # Pipe ppmquant output into ppmtogif
                # "ppmquant 256 %s | ppmtogif > %s" % (tempfile, filename)
                quant_cmd = ["ppmquant", "256", tempfile]
                togif_cmd = ["ppmtogif"]
                quant_proc = subprocess.Popen(
                    quant_cmd, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL
                )
                togif_proc = subprocess.Popen(
                    togif_cmd,
                    stdin=quant_proc.stdout,
                    stdout=f,
                    stderr=subprocess.DEVNULL,
                )
                # Allow ppmquant to receive SIGPIPE if ppmtogif exits
                assert quant_proc.stdout is not None
                quant_proc.stdout.close()
                retcode = quant_proc.wait()
                if retcode:
                    raise subprocess.CalledProcessError(retcode, quant_cmd)
                retcode = togif_proc.wait()
                if retcode:
                    raise subprocess.CalledProcessError(retcode, togif_cmd)
    finally:
        try:
            os.unlink(tempfile)
        except OSError:
            pass
# Force optimization so that we can test performance against
# cases where it took lots of memory and time previously.
_write_frame_data()
None PIL.GifImagePlugin._write_frame_data (IO[bytes] fp, Image.Image im_frame, tuple[int, int] offset, dict[str, Any] params) protected
Definition at line 1090 of file GifImagePlugin.py.
) -> None:
    try:
        im_frame.encoderinfo = params
        # local image header
        _write_local_header(fp, im_frame, offset, 0)
        ImageFile._save(
            im_frame,
            fp,
            [ImageFile._Tile("gif", (0, 0) + im_frame.size, 0, RAWMODE[im_frame.mode])],
        )
        fp.write(b"\0")  # end of image data
    finally:
        del im_frame.encoderinfo
# --------------------------------------------------------------------
# Legacy GIF utilities
Referenced by _write_multiple_frames().
_write_local_header()
None PIL.GifImagePlugin._write_local_header (IO[bytes] fp, Image.Image im, tuple[int, int] offset, int flags) protected
Definition at line 806 of file GifImagePlugin.py.
) -> None:
    try:
        transparency = im.encoderinfo["transparency"]
    except KeyError:
        transparency = None
    if "duration" in im.encoderinfo:
        duration = int(im.encoderinfo["duration"] / 10)
    else:
        duration = 0
    disposal = int(im.encoderinfo.get("disposal", 0))
    if transparency is not None or duration != 0 or disposal:
        packed_flag = 1 if transparency is not None else 0
        packed_flag |= disposal << 2
        fp.write(
            b"!"
            + o8(249)  # extension intro
            + o8(4)  # length
            + o8(packed_flag)  # packed fields
            + o16(duration)  # duration
            + o8(transparency or 0)  # transparency index
            + o8(0)
        )
    include_color_table = im.encoderinfo.get("include_color_table")
    if include_color_table:
        palette_bytes = _get_palette_bytes(im)
        color_table_size = _get_color_table_size(palette_bytes)
        if color_table_size:
            flags = flags | 128  # local color table flag
            flags = flags | color_table_size
    fp.write(
        b","
        + o16(offset[0])  # offset
        + o16(offset[1])
        + o16(im.size[0])  # size
        + o16(im.size[1])
        + o8(flags)  # flags
    )
    if include_color_table and color_table_size:
        fp.write(_get_header_palette(palette_bytes))
    fp.write(o8(8))  # bits
References _get_color_table_size(), _get_header_palette(), and _get_palette_bytes().
Referenced by _write_single_frame().
_write_multiple_frames()
bool PIL.GifImagePlugin._write_multiple_frames (Image.Image im, IO[bytes] fp, _Palette | None palette) protected
Definition at line 650 of file GifImagePlugin.py.
) -> bool:
    duration = im.encoderinfo.get("duration")
    disposal = im.encoderinfo.get("disposal", im.info.get("disposal"))
    im_frames: list[_Frame] = []
    previous_im: Image.Image | None = None
    frame_count = 0
    background_im = None
    for imSequence in itertools.chain([im], im.encoderinfo.get("append_images", [])):
        for im_frame in ImageSequence.Iterator(imSequence):
            # a copy is required here since seek can still mutate the image
            im_frame = _normalize_mode(im_frame.copy())
            if frame_count == 0:
                for k, v in im_frame.info.items():
                    if k == "transparency":
                        continue
                    if isinstance(k, str):
                        im.encoderinfo.setdefault(k, v)
            encoderinfo = im.encoderinfo.copy()
            if "transparency" in im_frame.info:
                encoderinfo.setdefault("transparency", im_frame.info["transparency"])
            im_frame = _normalize_palette(im_frame, palette, encoderinfo)
            if isinstance(duration, (list, tuple)):
                encoderinfo["duration"] = duration[frame_count]
            elif duration is None and "duration" in im_frame.info:
                encoderinfo["duration"] = im_frame.info["duration"]
            if isinstance(disposal, (list, tuple)):
                encoderinfo["disposal"] = disposal[frame_count]
            frame_count += 1
            diff_frame = None
            if im_frames and previous_im:
                # delta frame
                delta, bbox = _getbbox(previous_im, im_frame)
                if not bbox:
                    # This frame is identical to the previous frame
                    if encoderinfo.get("duration"):
                        im_frames[-1].encoderinfo["duration"] += encoderinfo["duration"]
                    continue
                if im_frames[-1].encoderinfo.get("disposal") == 2:
                    if background_im is None:
                        color = im.encoderinfo.get(
                            "transparency", im.info.get("transparency", (0, 0, 0))
                        )
                        background = _get_background(im_frame, color)
                        background_im = Image.new("P", im_frame.size, background)
                        assert im_frames[0].im.palette is not None
                        background_im.putpalette(im_frames[0].im.palette)
                    bbox = _getbbox(background_im, im_frame)[1]
                elif encoderinfo.get("optimize") and im_frame.mode != "1":
                    if "transparency" not in encoderinfo:
                        assert im_frame.palette is not None
                        try:
                            encoderinfo["transparency"] = (
                                im_frame.palette._new_color_index(im_frame)
                            )
                        except ValueError:
                            pass
                    if "transparency" in encoderinfo:
                        # When the delta is zero, fill the image with transparency
                        diff_frame = im_frame.copy()
                        fill = Image.new("P", delta.size, encoderinfo["transparency"])
                        if delta.mode == "RGBA":
                            r, g, b, a = delta.split()
                            mask = ImageMath.lambda_eval(
                                lambda args: args["convert"](
                                    args["max"](
                                        args["max"](
                                            args["max"](args["r"], args["g"]), args["b"]
                                        ),
                                        args["a"],
                                    )
                                    * 255,
                                    "1",
                                ),
                                r=r,
                                g=g,
                                b=b,
                                a=a,
                            )
                        else:
                            if delta.mode == "P":
                                # Convert to L without considering palette
                                delta_l = Image.new("L", delta.size)
                                delta_l.putdata(delta.getdata())
                                delta = delta_l
                            mask = ImageMath.lambda_eval(
                                lambda args: args["convert"](args["im"] * 255, "1"),
                                im=delta,
                            )
                        diff_frame.paste(fill, mask=ImageOps.invert(mask))
            else:
                bbox = None
            previous_im = im_frame
            im_frames.append(_Frame(diff_frame or im_frame, bbox, encoderinfo))
    if len(im_frames) == 1:
        if "duration" in im.encoderinfo:
            # Since multiple frames will not be written, use the combined duration
            im.encoderinfo["duration"] = im_frames[0].encoderinfo["duration"]
        return False
    for frame_data in im_frames:
        im_frame = frame_data.im
        if not frame_data.bbox:
            # global header
            for s in _get_global_header(im_frame, frame_data.encoderinfo):
                fp.write(s)
            offset = (0, 0)
        else:
            # compress difference
            if not palette:
                frame_data.encoderinfo["include_color_table"] = True
            im_frame = im_frame.crop(frame_data.bbox)
            offset = frame_data.bbox[:2]
        _write_frame_data(fp, im_frame, offset, frame_data.encoderinfo)
    return True
References _get_background(), _get_global_header(), _getbbox(), _normalize_mode(), _normalize_palette(), and _write_frame_data().
Referenced by _save().
_write_single_frame()
None PIL.GifImagePlugin._write_single_frame (Image.Image im, IO[bytes] fp, _Palette | None palette) protected
Definition at line 603 of file GifImagePlugin.py.
) -> None:
    im_out = _normalize_mode(im)
    for k, v in im_out.info.items():
        if isinstance(k, str):
            im.encoderinfo.setdefault(k, v)
    im_out = _normalize_palette(im_out, palette, im.encoderinfo)
    for s in _get_global_header(im_out, im.encoderinfo):
        fp.write(s)
    # local image header
    flags = 0
    if get_interlace(im):
        flags = flags | 64
    _write_local_header(fp, im, (0, 0), flags)
    im_out.encoderconfig = (8, get_interlace(im))
    ImageFile._save(
        im_out, fp, [ImageFile._Tile("gif", (0, 0) + im.size, 0, RAWMODE[im_out.mode])]
    )
    fp.write(b"\0")  # end of image data
References _get_global_header(), _normalize_mode(), _normalize_palette(), _write_local_header(), and get_interlace().
Referenced by _save().
get_interlace()
int PIL.GifImagePlugin.get_interlace (Image.Image im)
Definition at line 796 of file GifImagePlugin.py.
def get_interlace(im: Image.Image) -> int:
    interlace = im.encoderinfo.get("interlace", 1)
    # workaround for @PIL153
    if min(im.size) < 16:
        interlace = 0
    return interlace
Referenced by _write_single_frame().
getdata()
list[bytes] PIL.GifImagePlugin.getdata (Image.Image im, tuple[int, int] offset = (0, 0), **Any params)
Legacy Method
Return a list of strings representing this image.
The first string is a local image header, the rest contains
encoded image data.
To specify duration, add the time in milliseconds,
e.g. ``getdata(im_frame, duration=1000)``
:param im: Image object
:param offset: Tuple of (x, y) pixels. Defaults to (0, 0)
:param \\**params: e.g. duration or other encoder info parameters
:returns: List of bytes containing GIF encoded frame data
Definition at line 1147 of file GifImagePlugin.py.
) -> list[bytes]:
    """
    Legacy Method
    Return a list of strings representing this image.
    The first string is a local image header, the rest contains
    encoded image data.
    To specify duration, add the time in milliseconds,
    e.g. ``getdata(im_frame, duration=1000)``
    :param im: Image object
    :param offset: Tuple of (x, y) pixels. Defaults to (0, 0)
    :param \\**params: e.g. duration or other encoder info parameters
    :returns: List of bytes containing GIF encoded frame data
    """
    from io import BytesIO
    class Collector(BytesIO):
        data = []
        def write(self, data: Buffer) -> int:
            self.data.append(data)
            return len(data)
    im.load()  # make sure raster data is available
    fp = Collector()
    _write_frame_data(fp, im, offset, params)
    return fp.data
# --------------------------------------------------------------------
# Registry
getheader()
tuple[list[bytes], list[int] | None] PIL.GifImagePlugin.getheader (Image.Image im, _Palette | None palette = None, dict[str, Any] | None info = None)
Legacy Method to get Gif data from image.
Warning:: May modify image data.
:param im: Image object
:param palette: bytes object containing the source palette, or ....
:param info: encoderinfo
:returns: tuple of(list of header items, optimized palette)
Definition at line 1117 of file GifImagePlugin.py.
) -> tuple[list[bytes], list[int] | None]:
    """
    Legacy Method to get Gif data from image.
    Warning:: May modify image data.
    :param im: Image object
    :param palette: bytes object containing the source palette, or ....
    :param info: encoderinfo
    :returns: tuple of(list of header items, optimized palette)
    """
    if info is None:
        info = {}
    used_palette_colors = _get_optimize(im, info)
    if "background" not in info and "background" in im.info:
        info["background"] = im.info["background"]
    im_mod = _normalize_palette(im, palette, info)
    im.palette = im_mod.palette
    im.im = im_mod.im
    header = _get_global_header(im, info)
    return header, used_palette_colors
Variable Documentation
_FORCE_OPTIMIZE
bool PIL.GifImagePlugin._FORCE_OPTIMIZE = False protected
Definition at line 906 of file GifImagePlugin.py.
_Palette
PIL.GifImagePlugin._Palette = Union[bytes, bytearray, list[int], ImagePalette.ImagePalette] protected
Definition at line 529 of file GifImagePlugin.py.
LOADING_STRATEGY
PIL.GifImagePlugin.LOADING_STRATEGY = LoadingStrategy.RGB_AFTER_FIRST
Definition at line 63 of file GifImagePlugin.py.
RAWMODE
dict PIL.GifImagePlugin.RAWMODE = {"1": "L", "L": "L", "P": "P"}
Definition at line 500 of file GifImagePlugin.py.