Read&Watch: django.db.models.options Namespace Reference
django.db.models.options Namespace Reference
Classes
class Options
Functions
normalize_together (option_together)
make_immutable_fields_list (name, data)
Variables
PROXY_PARENTS = object()
tuple EMPTY_RELATION_TREE = ()
tuple IMMUTABLE_WARNING
tuple DEFAULT_NAMES
Function Documentation
make_immutable_fields_list()
django.db.models.options.make_immutable_fields_list (name, data)
Definition at line 79 of file options.py.
def make_immutable_fields_list(name, data):
    return ImmutableList(data, warning=IMMUTABLE_WARNING % name)
Referenced by django.db.models.options.Options._get_fields(), django.db.models.options.Options.concrete_fields(), django.db.models.options.Options.fields(), django.db.models.options.Options.local_concrete_fields(), django.db.models.options.Options.managers(), django.db.models.options.Options.many_to_many(), and django.db.models.options.Options.related_objects().
normalize_together()
django.db.models.options.normalize_together (option_together)
option_together can be either a tuple of tuples, or a single
tuple of two strings. Normalize it to a tuple of tuples, so that
calling code can uniformly expect that.
Definition at line 57 of file options.py.
def normalize_together(option_together):
    """
    option_together can be either a tuple of tuples, or a single
    tuple of two strings. Normalize it to a tuple of tuples, so that
    calling code can uniformly expect that.
    """
    try:
        if not option_together:
            return ()
        if not isinstance(option_together, (tuple, list)):
            raise TypeError
        first_element = option_together[0]
        if not isinstance(first_element, (tuple, list)):
            option_together = (option_together,)
        # Normalize everything to tuples
        return tuple(tuple(ot) for ot in option_together)
    except TypeError:
        # If the value of option_together isn't valid, return it
        # verbatim; this will be picked up by the check framework later.
        return option_together
Variable Documentation
DEFAULT_NAMES
tuple django.db.models.options.DEFAULT_NAMES
Initial value:
=  (
    "verbose_name",
    "verbose_name_plural",
    "db_table",
    "db_table_comment",
    "ordering",
    "unique_together",
    "permissions",
    "get_latest_by",
    "order_with_respect_to",
    "app_label",
    "db_tablespace",
    "abstract",
    "managed",
    "proxy",
    "swappable",
    "auto_created",
    "apps",
    "default_permissions",
    "select_on_save",
    "default_related_name",
    "required_db_features",
    "required_db_vendor",
    "base_manager_name",
    "default_manager_name",
    "indexes",
    "constraints",
)
Definition at line 27 of file options.py.
EMPTY_RELATION_TREE
tuple django.db.models.options.EMPTY_RELATION_TREE = ()
Definition at line 20 of file options.py.
IMMUTABLE_WARNING
tuple django.db.models.options.IMMUTABLE_WARNING
Initial value:
=  (
    "The return type of '%s' should never be mutated. If you want to manipulate this "
    "list for your own use, make a copy first."
)
Definition at line 22 of file options.py.
PROXY_PARENTS
django.db.models.options.PROXY_PARENTS = object()
Definition at line 18 of file options.py.