Read&Watch: pip._vendor.urllib3.contrib.pyopenssl Namespace Reference
pip._vendor.urllib3.contrib.pyopenssl Namespace Reference
Classes
class PyOpenSSLContext
class UnsupportedExtension
class WrappedSocket
Functions
inject_into_urllib3 ()
extract_from_urllib3 ()
_validate_dependencies_met ()
_dnsname_to_stdlib (name)
get_subj_alt_name (peer_cert)
makefile (self, mode, bufsize=-1)
_verify_callback (cnx, x509, err_no, err_depth, return_code)
Variables
_fileobject = None
category
stacklevel
bool HAS_SNI = True
dict _openssl_versions
dict _stdlib_to_openssl_verify
_openssl_to_stdlib_verify = dict((v, k) for k, v in _stdlib_to_openssl_verify.items())
int SSL_WRITE_BLOCKSIZE = 16384
bool orig_util_HAS_SNI = util.HAS_SNI
orig_util_SSLContext = util.ssl_.SSLContext
log = logging.getLogger(__name__)
makefile = backport_makefile
Detailed Description
TLS with SNI_-support for Python 2. Follow these instructions if you would
like to verify TLS certificates in Python 2. Note, the default libraries do
*not* do certificate checking; you need to do additional work to validate
certificates yourself.
This needs the following packages installed:
* `pyOpenSSL`_ (tested with 16.0.0)
* `cryptography`_ (minimum 1.3.4, from pyopenssl)
* `idna`_ (minimum 2.0, from cryptography)
However, pyopenssl depends on cryptography, which depends on idna, so while we
use all three directly here we end up having relatively few packages required.
You can install them with the following command:
.. code-block:: bash
    $ python -m pip install pyopenssl cryptography idna
To activate certificate checking, call
:func:`~urllib3.contrib.pyopenssl.inject_into_urllib3` from your Python code
before you begin making HTTP requests. This can be done in a ``sitecustomize``
module, or at any other time before your application begins using ``urllib3``,
like this:
.. code-block:: python
    try:
        import pip._vendor.urllib3.contrib.pyopenssl as pyopenssl
        pyopenssl.inject_into_urllib3()
    except ImportError:
        pass
Now you can use :mod:`urllib3` as you normally would, and it will support SNI
when the required modules are installed.
Activating this module also has the positive side effect of disabling SSL/TLS
compression in Python 2 (see `CRIME attack`_).
.. _sni: https://en.wikipedia.org/wiki/Server_Name_Indication
.. _crime attack: https://en.wikipedia.org/wiki/CRIME_(security_exploit)
.. _pyopenssl: https://www.pyopenssl.org
.. _cryptography: https://cryptography.io
.. _idna: https://github.com/kjd/idna
Function Documentation
_dnsname_to_stdlib()
pip._vendor.urllib3.contrib.pyopenssl._dnsname_to_stdlib (name) protected
Converts a dNSName SubjectAlternativeName field to the form used by the
standard library on the given Python version.
Cryptography produces a dNSName as a unicode string that was idna-decoded
from ASCII bytes. We need to idna-encode that string to get it back, and
then on Python 3 we also need to convert to unicode via UTF-8 (the stdlib
uses PyUnicode_FromStringAndSize on it, which decodes via UTF-8).
If the name cannot be idna-encoded then we return None signalling that
the name given should be skipped.
Definition at line 180 of file pyopenssl.py.
def _dnsname_to_stdlib(name):
    """
    Converts a dNSName SubjectAlternativeName field to the form used by the
    standard library on the given Python version.
    Cryptography produces a dNSName as a unicode string that was idna-decoded
    from ASCII bytes. We need to idna-encode that string to get it back, and
    then on Python 3 we also need to convert to unicode via UTF-8 (the stdlib
    uses PyUnicode_FromStringAndSize on it, which decodes via UTF-8).
    If the name cannot be idna-encoded then we return None signalling that
    the name given should be skipped.
    """
    def idna_encode(name):
        """
        Borrowed wholesale from the Python Cryptography Project. It turns out
        that we can't just safely call `idna.encode`: it can explode for
        wildcard names. This avoids that problem.
        """
        from pip._vendor import idna
        try:
            for prefix in [u"*.", u"."]:
                if name.startswith(prefix):
                    name = name[len(prefix) :]
                    return prefix.encode("ascii") + idna.encode(name)
            return idna.encode(name)
        except idna.core.IDNAError:
            return None
    # Don't send IPv6 addresses through the IDNA encoder.
    if ":" in name:
        return name
    name = idna_encode(name)
    if name is None:
        return None
    elif sys.version_info >= (3, 0):
        name = name.decode("utf-8")
    return name
_validate_dependencies_met()
pip._vendor.urllib3.contrib.pyopenssl._validate_dependencies_met () protected
Verifies that PyOpenSSL's package-level dependencies have been met.
Throws `ImportError` if they are not met.
Definition at line 154 of file pyopenssl.py.
def _validate_dependencies_met():
    """
    Verifies that PyOpenSSL's package-level dependencies have been met.
    Throws `ImportError` if they are not met.
    """
    # Method added in `cryptography==1.1`; not available in older versions
    from cryptography.x509.extensions import Extensions
    if getattr(Extensions, "get_extension_for_class", None) is None:
        raise ImportError(
            "'cryptography' module missing required functionality.  "
            "Try upgrading to v1.3.4 or newer."
        )
    # pyOpenSSL 0.14 and above use cryptography for OpenSSL bindings. The _x509
    # attribute is only present on those versions.
    from OpenSSL.crypto import X509
    x509 = X509()
    if getattr(x509, "_x509", None) is None:
        raise ImportError(
            "'pyOpenSSL' module missing required functionality. "
            "Try upgrading to v0.14 or newer."
        )
Referenced by inject_into_urllib3().
_verify_callback()
pip._vendor.urllib3.contrib.pyopenssl._verify_callback (cnx, x509, err_no, err_depth, return_code) protected
Definition at line 517 of file pyopenssl.py.
def _verify_callback(cnx, x509, err_no, err_depth, return_code):
    return err_no == 0
extract_from_urllib3()
pip._vendor.urllib3.contrib.pyopenssl.extract_from_urllib3 ()
Definition at line 143 of file pyopenssl.py.
def extract_from_urllib3():
    "Undo monkey-patching by :func:`inject_into_urllib3`."
    util.SSLContext = orig_util_SSLContext
    util.ssl_.SSLContext = orig_util_SSLContext
    util.HAS_SNI = orig_util_HAS_SNI
    util.ssl_.HAS_SNI = orig_util_HAS_SNI
    util.IS_PYOPENSSL = False
    util.ssl_.IS_PYOPENSSL = False
get_subj_alt_name()
pip._vendor.urllib3.contrib.pyopenssl.get_subj_alt_name (peer_cert)
Given an PyOpenSSL certificate, provides all the subject alternative names.
Definition at line 223 of file pyopenssl.py.
def get_subj_alt_name(peer_cert):
    """
    Given an PyOpenSSL certificate, provides all the subject alternative names.
    """
    # Pass the cert to cryptography, which has much better APIs for this.
    if hasattr(peer_cert, "to_cryptography"):
        cert = peer_cert.to_cryptography()
    else:
        der = OpenSSL.crypto.dump_certificate(OpenSSL.crypto.FILETYPE_ASN1, peer_cert)
        cert = x509.load_der_x509_certificate(der, openssl_backend)
    # We want to find the SAN extension. Ask Cryptography to locate it (it's
    # faster than looping in Python)
    try:
        ext = cert.extensions.get_extension_for_class(x509.SubjectAlternativeName).value
    except x509.ExtensionNotFound:
        # No such extension, return the empty list.
        return []
    except (
        x509.DuplicateExtension,
        UnsupportedExtension,
        x509.UnsupportedGeneralNameType,
        UnicodeError,
    ) as e:
        # A problem has been found with the quality of the certificate. Assume
        # no SAN field is present.
        log.warning(
            "A problem was encountered with the certificate that prevented "
            "urllib3 from finding the SubjectAlternativeName field. This can "
            "affect certificate validation. The error was %s",
            e,
        )
        return []
    # We want to return dNSName and iPAddress fields. We need to cast the IPs
    # back to strings because the match_hostname function wants them as
    # strings.
    # Sadly the DNS names need to be idna encoded and then, on Python 3, UTF-8
    # decoded. This is pretty frustrating, but that's what the standard library
    # does with certificates, and so we need to attempt to do the same.
    # We also want to skip over names which cannot be idna encoded.
    names = [
        ("DNS", name)
        for name in map(_dnsname_to_stdlib, ext.get_values_for_type(x509.DNSName))
        if name is not None
    ]
    names.extend(
        ("IP Address", str(name)) for name in ext.get_values_for_type(x509.IPAddress)
    )
    return names
Referenced by pip._vendor.urllib3.contrib.pyopenssl.WrappedSocket.getpeercert().
inject_into_urllib3()
pip._vendor.urllib3.contrib.pyopenssl.inject_into_urllib3 ()
Definition at line 130 of file pyopenssl.py.
def inject_into_urllib3():
    "Monkey-patch urllib3 with PyOpenSSL-backed SSL-support."
    _validate_dependencies_met()
    util.SSLContext = PyOpenSSLContext
    util.ssl_.SSLContext = PyOpenSSLContext
    util.HAS_SNI = HAS_SNI
    util.ssl_.HAS_SNI = HAS_SNI
    util.IS_PYOPENSSL = True
    util.ssl_.IS_PYOPENSSL = True
References _validate_dependencies_met().
makefile()
pip._vendor.urllib3.contrib.pyopenssl.makefile (self, mode, bufsize = -1)
Definition at line 413 of file pyopenssl.py.
    def makefile(self, mode, bufsize=-1):
        self._makefile_refs += 1
        return _fileobject(self, mode, bufsize, close=True)
References _fileobject.
Variable Documentation
_fileobject
pip._vendor.urllib3.contrib.pyopenssl._fileobject = None protected
Definition at line 70 of file pyopenssl.py.
Referenced by makefile().
_openssl_to_stdlib_verify
pip._vendor.urllib3.contrib.pyopenssl._openssl_to_stdlib_verify = dict((v, k) for k, v in _stdlib_to_openssl_verify.items()) protected
Definition at line 118 of file pyopenssl.py.
_openssl_versions
dict pip._vendor.urllib3.contrib.pyopenssl._openssl_versions protected
Initial value:
=  {
    util.PROTOCOL_TLS: OpenSSL.SSL.SSLv23_METHOD,
    PROTOCOL_TLS_CLIENT: OpenSSL.SSL.SSLv23_METHOD,
    ssl.PROTOCOL_TLSv1: OpenSSL.SSL.TLSv1_METHOD,
}
Definition at line 96 of file pyopenssl.py.
_stdlib_to_openssl_verify
dict pip._vendor.urllib3.contrib.pyopenssl._stdlib_to_openssl_verify protected
Initial value:
=  {
    ssl.CERT_NONE: OpenSSL.SSL.VERIFY_NONE,
    ssl.CERT_OPTIONAL: OpenSSL.SSL.VERIFY_PEER,
    ssl.CERT_REQUIRED: OpenSSL.SSL.VERIFY_PEER
    + OpenSSL.SSL.VERIFY_FAIL_IF_NO_PEER_CERT,
}
Definition at line 112 of file pyopenssl.py.
category
pip._vendor.urllib3.contrib.pyopenssl.category
Definition at line 86 of file pyopenssl.py.
HAS_SNI
bool pip._vendor.urllib3.contrib.pyopenssl.HAS_SNI = True
Definition at line 93 of file pyopenssl.py.
log
pip._vendor.urllib3.contrib.pyopenssl.log = logging.getLogger(__name__)
Definition at line 127 of file pyopenssl.py.
makefile
pip._vendor.urllib3.contrib.pyopenssl.makefile = backport_makefile
Definition at line 418 of file pyopenssl.py.
orig_util_HAS_SNI
bool pip._vendor.urllib3.contrib.pyopenssl.orig_util_HAS_SNI = util.HAS_SNI
Definition at line 123 of file pyopenssl.py.
orig_util_SSLContext
pip._vendor.urllib3.contrib.pyopenssl.orig_util_SSLContext = util.ssl_.SSLContext
Definition at line 124 of file pyopenssl.py.
SSL_WRITE_BLOCKSIZE
int pip._vendor.urllib3.contrib.pyopenssl.SSL_WRITE_BLOCKSIZE = 16384
Definition at line 121 of file pyopenssl.py.
stacklevel
pip._vendor.urllib3.contrib.pyopenssl.stacklevel
Definition at line 87 of file pyopenssl.py.