Read&Watch: pylint.lint.run Namespace Reference
pylint.lint.run Namespace Reference
Classes
class _PylintConfigRun
class Run
Functions
int|None _query_cpu ()
int|None _query_cpu_cgroupv2 ()
int|None _query_cpu_cgroupsv1 ()
int|None _query_cpu_handle_k8s_pods (int|None avail_cpu)
int _cpu_count ()
Variables
multiprocessing = None
ProcessPoolExecutor = None
Function Documentation
_cpu_count()
int pylint.lint.run._cpu_count () protected
Use sched_affinity if available for virtualized or containerized
environments.
Definition at line 103 of file run.py.
def _cpu_count() -> int:
    """Use sched_affinity if available for virtualized or containerized
    environments.
    """
    cpu_share = _query_cpu()
    cpu_count = None
    sched_getaffinity = getattr(os, "sched_getaffinity", None)
    # pylint: disable=not-callable,using-constant-test,useless-suppression
    if sched_getaffinity:
        cpu_count = len(sched_getaffinity(0))
    elif multiprocessing:
        cpu_count = multiprocessing.cpu_count()
    else:
        cpu_count = 1
    if sys.platform == "win32":
        # See also https://github.com/python/cpython/issues/94242
        cpu_count = min(cpu_count, 56)  # pragma: no cover
    if cpu_share is not None:
        return min(cpu_share, cpu_count)
    return cpu_count
References _query_cpu().
_query_cpu()
int | None pylint.lint.run._query_cpu () protected
Try to determine number of CPUs allotted in a docker container.
This is based on discussion and copied from suggestions in
https://bugs.python.org/issue36054.
Definition at line 40 of file run.py.
def _query_cpu() -> int | None:
    """Try to determine number of CPUs allotted in a docker container.
    This is based on discussion and copied from suggestions in
    https://bugs.python.org/issue36054.
    """
    if Path("/sys/fs/cgroup/cpu.max").is_file():
        avail_cpu = _query_cpu_cgroupv2()
    else:
        avail_cpu = _query_cpu_cgroupsv1()
    return _query_cpu_handle_k8s_pods(avail_cpu)
References _query_cpu_cgroupsv1(), _query_cpu_cgroupv2(), and _query_cpu_handle_k8s_pods().
Referenced by _cpu_count().
_query_cpu_cgroupsv1()
int | None pylint.lint.run._query_cpu_cgroupsv1 () protected
Definition at line 68 of file run.py.
def _query_cpu_cgroupsv1() -> int | None:
    cpu_quota, avail_cpu = None, None
    if Path("/sys/fs/cgroup/cpu/cpu.cfs_quota_us").is_file():
        with open("/sys/fs/cgroup/cpu/cpu.cfs_quota_us", encoding="utf-8") as file:
            # Not useful for AWS Batch based jobs as result is -1, but works on local linux systems
            cpu_quota = int(file.read().rstrip())
    if (
        cpu_quota
        and cpu_quota != -1
        and Path("/sys/fs/cgroup/cpu/cpu.cfs_period_us").is_file()
    ):
        with open("/sys/fs/cgroup/cpu/cpu.cfs_period_us", encoding="utf-8") as file:
            cpu_period = int(file.read().rstrip())
        # Divide quota by period and you should get num of allotted CPU to the container,
        # rounded down if fractional.
        avail_cpu = int(cpu_quota / cpu_period)
    elif Path("/sys/fs/cgroup/cpu/cpu.shares").is_file():
        with open("/sys/fs/cgroup/cpu/cpu.shares", encoding="utf-8") as file:
            cpu_shares = int(file.read().rstrip())
        # For AWS, gives correct value * 1024.
        avail_cpu = int(cpu_shares / 1024)
    return avail_cpu
Referenced by _query_cpu().
_query_cpu_cgroupv2()
int | None pylint.lint.run._query_cpu_cgroupv2 () protected
Definition at line 53 of file run.py.
def _query_cpu_cgroupv2() -> int | None:
    avail_cpu = None
    with open("/sys/fs/cgroup/cpu.max", encoding="utf-8") as file:
        line = file.read().rstrip()
        fields = line.split()
        if len(fields) == 2:
            str_cpu_quota = fields[0]
            cpu_period = int(fields[1])
            # Make sure this is not in an unconstrained cgroup
            if str_cpu_quota != "max":
                cpu_quota = int(str_cpu_quota)
                avail_cpu = int(cpu_quota / cpu_period)
    return avail_cpu
Referenced by _query_cpu().
_query_cpu_handle_k8s_pods()
int | None pylint.lint.run._query_cpu_handle_k8s_pods (int | None avail_cpu) protected
Definition at line 93 of file run.py.
def _query_cpu_handle_k8s_pods(avail_cpu: int | None) -> int | None:
    # In K8s Pods also a fraction of a single core could be available
    # As multiprocessing is not able to run only a "fraction" of process
    # assume we have 1 CPU available
    if avail_cpu == 0:
        avail_cpu = 1
    return avail_cpu
Referenced by _query_cpu().
Variable Documentation
multiprocessing
pylint.lint.run.multiprocessing = None
Definition at line 32 of file run.py.
ProcessPoolExecutor
pylint.lint.run.ProcessPoolExecutor = None
Definition at line 37 of file run.py.