Read&Watch: django.utils.autoreload Namespace Reference
django.utils.autoreload Namespace Reference
Classes
class BaseReloader
class StatReloader
class WatchmanReloader
class WatchmanUnavailable
Functions
is_django_module (module)
is_django_path (path)
check_errors (fn)
raise_last_exception ()
ensure_echo_on ()
iter_all_python_module_files ()
iter_modules_and_files (modules, extra_files)
common_roots (paths)
sys_path_directories ()
get_child_arguments ()
trigger_reload (filename)
restart_with_reloader ()
get_reloader ()
start_django (reloader, main_func, *args, **kwargs)
run_with_reloader (main_func, *args, **kwargs)
Variables
autoreload_started = Signal()
file_changed = Signal()
str DJANGO_AUTORELOAD_ENV = "RUN_MAIN"
logger = logging.getLogger("django.utils.autoreload")
list _error_files = []
_exception = None
termios = None
pywatchman = None
Function Documentation
check_errors()
django.utils.autoreload.check_errors (fn)
Definition at line 59 of file autoreload.py.
def check_errors(fn):
    @wraps(fn)
    def wrapper(*args, **kwargs):
        global _exception
        try:
            fn(*args, **kwargs)
        except Exception:
            _exception = sys.exc_info()
            et, ev, tb = _exception
            if getattr(ev, "filename", None) is None:
                # get the filename from the last item in the stack
                filename = traceback.extract_tb(tb)[-1][0]
            else:
                filename = ev.filename
            if filename not in _error_files:
                _error_files.append(filename)
            raise
    return wrapper
Referenced by start_django().
common_roots()
django.utils.autoreload.common_roots (paths)
Return a tuple of common roots that are shared between the given paths.
File system watchers operate on directories and aren't cheap to create.
Try to find the minimum set of directories to watch that encompass all of
the files that need to be watched.
Definition at line 174 of file autoreload.py.
def common_roots(paths):
    """
    Return a tuple of common roots that are shared between the given paths.
    File system watchers operate on directories and aren't cheap to create.
    Try to find the minimum set of directories to watch that encompass all of
    the files that need to be watched.
    """
    # Inspired from Werkzeug:
    # https://github.com/pallets/werkzeug/blob/7477be2853df70a022d9613e765581b9411c3c39/werkzeug/_reloader.py
    # Create a sorted list of the path components, longest first.
    path_parts = sorted([x.parts for x in paths], key=len, reverse=True)
    tree = {}
    for chunks in path_parts:
        node = tree
        # Add each part of the path to the tree.
        for chunk in chunks:
            node = node.setdefault(chunk, {})
        # Clear the last leaf in the tree.
        node.clear()
    # Turn the tree into a list of Path instances.
    def _walk(node, path):
        for prefix, child in node.items():
            yield from _walk(child, path + (prefix,))
        if not node:
            yield Path(*path)
    return tuple(_walk(tree, ()))
Referenced by django.utils.autoreload.WatchmanReloader._update_watches().
ensure_echo_on()
django.utils.autoreload.ensure_echo_on ()
Ensure that echo mode is enabled. Some tools such as PDB disable
it which causes usability issues after reload.
Definition at line 90 of file autoreload.py.
def ensure_echo_on():
    """
    Ensure that echo mode is enabled. Some tools such as PDB disable
    it which causes usability issues after reload.
    """
    if not termios or not sys.stdin.isatty():
        return
    attr_list = termios.tcgetattr(sys.stdin)
    if not attr_list[3] & termios.ECHO:
        attr_list[3] |= termios.ECHO
        if hasattr(signal, "SIGTTOU"):
            old_handler = signal.signal(signal.SIGTTOU, signal.SIG_IGN)
        else:
            old_handler = None
        termios.tcsetattr(sys.stdin, termios.TCSANOW, attr_list)
        if old_handler is not None:
            signal.signal(signal.SIGTTOU, old_handler)
Referenced by start_django().
get_child_arguments()
django.utils.autoreload.get_child_arguments ()
Return the executable. This contains a workaround for Windows if the
executable is reported to not have the .exe extension which can cause bugs
on reloading.
Definition at line 221 of file autoreload.py.
def get_child_arguments():
    """
    Return the executable. This contains a workaround for Windows if the
    executable is reported to not have the .exe extension which can cause bugs
    on reloading.
    """
    import __main__
    py_script = Path(sys.argv[0])
    exe_entrypoint = py_script.with_suffix(".exe")
    args = [sys.executable] + ["-W%s" % o for o in sys.warnoptions]
    if sys.implementation.name in ("cpython", "pypy"):
        args.extend(
            f"-X{key}" if value is True else f"-X{key}={value}"
            for key, value in sys._xoptions.items()
        )
    # __spec__ is set when the server was started with the `-m` option,
    # see https://docs.python.org/3/reference/import.html#main-spec
    # __spec__ may not exist, e.g. when running in a Conda env.
    if getattr(__main__, "__spec__", None) is not None and not exe_entrypoint.exists():
        spec = __main__.__spec__
        if (spec.name == "__main__" or spec.name.endswith(".__main__")) and spec.parent:
            name = spec.parent
        else:
            name = spec.name
        args += ["-m", name]
        args += sys.argv[1:]
    elif not py_script.exists():
        # sys.argv[0] may not exist for several reasons on Windows.
        # It may exist with a .exe extension or have a -script.py suffix.
        if exe_entrypoint.exists():
            # Should be executed directly, ignoring sys.executable.
            return [exe_entrypoint, *sys.argv[1:]]
        script_entrypoint = py_script.with_name("%s-script.py" % py_script.name)
        if script_entrypoint.exists():
            # Should be executed as usual.
            return [*args, script_entrypoint, *sys.argv[1:]]
        raise RuntimeError("Script %s does not exist." % py_script)
    else:
        args += sys.argv
    return args
Referenced by restart_with_reloader().
get_reloader()
django.utils.autoreload.get_reloader ()
Return the most suitable reloader for this environment.
Definition at line 640 of file autoreload.py.
def get_reloader():
    """Return the most suitable reloader for this environment."""
    try:
        WatchmanReloader.check_availability()
    except WatchmanUnavailable:
        return StatReloader()
    return WatchmanReloader()
Referenced by run_with_reloader().
is_django_module()
django.utils.autoreload.is_django_module (module)
Return True if the given module is nested under Django.
Definition at line 49 of file autoreload.py.
def is_django_module(module):
    """Return True if the given module is nested under Django."""
    return module.__name__.startswith("django.")
is_django_path()
django.utils.autoreload.is_django_path (path)
Return True if the given file path is nested under Django.
Definition at line 54 of file autoreload.py.
def is_django_path(path):
    """Return True if the given file path is nested under Django."""
    return Path(django.__file__).parent in Path(path).parents
iter_all_python_module_files()
django.utils.autoreload.iter_all_python_module_files ()
Definition at line 109 of file autoreload.py.
def iter_all_python_module_files():
    # This is a hot path during reloading. Create a stable sorted list of
    # modules based on the module name and pass it to iter_modules_and_files().
    # This ensures cached results are returned in the usual case that modules
    # aren't loaded on the fly.
    keys = sorted(sys.modules)
    modules = tuple(
        m
        for m in map(sys.modules.__getitem__, keys)
        if not isinstance(m, weakref.ProxyTypes)
    )
    return iter_modules_and_files(modules, frozenset(_error_files))
@lru_cache(maxsize=1)
References iter_modules_and_files().
Referenced by django.utils.autoreload.BaseReloader.watched_files().
iter_modules_and_files()
django.utils.autoreload.iter_modules_and_files (modules, extra_files)
Iterate through all modules needed to be watched.
Definition at line 124 of file autoreload.py.
def iter_modules_and_files(modules, extra_files):
    """Iterate through all modules needed to be watched."""
    sys_file_paths = []
    for module in modules:
        # During debugging (with PyDev) the 'typing.io' and 'typing.re' objects
        # are added to sys.modules, however they are types not modules and so
        # cause issues here.
        if not isinstance(module, ModuleType):
            continue
        if module.__name__ in ("__main__", "__mp_main__"):
            # __main__ (usually manage.py) doesn't always have a __spec__ set.
            # Handle this by falling back to using __file__, resolved below.
            # See https://docs.python.org/reference/import.html#main-spec
            # __file__ may not exists, e.g. when running ipdb debugger.
            if hasattr(module, "__file__"):
                sys_file_paths.append(module.__file__)
            continue
        if getattr(module, "__spec__", None) is None:
            continue
        spec = module.__spec__
        # Modules could be loaded from places without a concrete location. If
        # this is the case, skip them.
        if spec.has_location:
            origin = (
                spec.loader.archive
                if isinstance(spec.loader, zipimporter)
                else spec.origin
            )
            sys_file_paths.append(origin)
    results = set()
    for filename in itertools.chain(sys_file_paths, extra_files):
        if not filename:
            continue
        path = Path(filename)
        try:
            if not path.exists():
                # The module could have been removed, don't fail loudly if this
                # is the case.
                continue
        except ValueError as e:
            # Network filesystems may return null bytes in file paths.
            logger.debug('"%s" raised when resolving path: "%s"', e, path)
            continue
        resolved_path = path.resolve().absolute()
        results.add(resolved_path)
    return frozenset(results)
@lru_cache(maxsize=1)
Referenced by iter_all_python_module_files().
raise_last_exception()
django.utils.autoreload.raise_last_exception ()
Definition at line 84 of file autoreload.py.
def raise_last_exception():
    global _exception
    if _exception is not None:
        raise _exception[1]
restart_with_reloader()
django.utils.autoreload.restart_with_reloader ()
Definition at line 270 of file autoreload.py.
def restart_with_reloader():
    new_environ = {**os.environ, DJANGO_AUTORELOAD_ENV: "true"}
    args = get_child_arguments()
    while True:
        p = subprocess.run(args, env=new_environ, close_fds=False)
        if p.returncode != 3:
            return p.returncode
References get_child_arguments().
Referenced by run_with_reloader().
run_with_reloader()
django.utils.autoreload.run_with_reloader (main_func, * args, ** kwargs)
Definition at line 663 of file autoreload.py.
def run_with_reloader(main_func, *args, **kwargs):
    signal.signal(signal.SIGTERM, lambda *args: sys.exit(0))
    try:
        if os.environ.get(DJANGO_AUTORELOAD_ENV) == "true":
            reloader = get_reloader()
            logger.info(
                "Watching for file changes with %s", reloader.__class__.__name__
            )
            start_django(reloader, main_func, *args, **kwargs)
        else:
            exit_code = restart_with_reloader()
            sys.exit(exit_code)
    except KeyboardInterrupt:
        pass
References get_reloader(), restart_with_reloader(), and start_django().
start_django()
django.utils.autoreload.start_django (reloader, main_func, * args, ** kwargs)
Definition at line 649 of file autoreload.py.
def start_django(reloader, main_func, *args, **kwargs):
    ensure_echo_on()
    main_func = check_errors(main_func)
    django_main_thread = threading.Thread(
        target=main_func, args=args, kwargs=kwargs, name="django-main-thread"
    )
    django_main_thread.daemon = True
    django_main_thread.start()
    while not reloader.should_stop:
        reloader.run(django_main_thread)
References check_errors(), and ensure_echo_on().
Referenced by run_with_reloader().
sys_path_directories()
django.utils.autoreload.sys_path_directories ()
Yield absolute directories from sys.path, ignoring entries that don't
exist.
Definition at line 204 of file autoreload.py.
def sys_path_directories():
    """
    Yield absolute directories from sys.path, ignoring entries that don't
    exist.
    """
    for path in sys.path:
        path = Path(path)
        if not path.exists():
            continue
        resolved_path = path.resolve().absolute()
        # If the path is a file (like a zip file), watch the parent directory.
        if resolved_path.is_file():
            yield resolved_path.parent
        else:
            yield resolved_path
Referenced by django.utils.autoreload.WatchmanReloader.watched_roots().
trigger_reload()
django.utils.autoreload.trigger_reload (filename)
Definition at line 265 of file autoreload.py.
def trigger_reload(filename):
    logger.info("%s changed, reloading.", filename)
    sys.exit(3)
Referenced by django.utils.autoreload.BaseReloader.notify_file_changed().
Variable Documentation
_error_files
list django.utils.autoreload._error_files = [] protected
Definition at line 34 of file autoreload.py.
_exception
django.utils.autoreload._exception = None protected
Definition at line 35 of file autoreload.py.
autoreload_started
django.utils.autoreload.autoreload_started = Signal()
Definition at line 24 of file autoreload.py.
DJANGO_AUTORELOAD_ENV
str django.utils.autoreload.DJANGO_AUTORELOAD_ENV = "RUN_MAIN"
Definition at line 27 of file autoreload.py.
file_changed
django.utils.autoreload.file_changed = Signal()
Definition at line 25 of file autoreload.py.
logger
django.utils.autoreload.logger = logging.getLogger("django.utils.autoreload")
Definition at line 29 of file autoreload.py.
pywatchman
django.utils.autoreload.pywatchman = None
Definition at line 46 of file autoreload.py.
termios
django.utils.autoreload.termios = None
Definition at line 40 of file autoreload.py.