Read&Watch: django.test.client Namespace Reference
django.test.client Namespace Reference
Classes
class AsyncClient
class AsyncClientHandler
class AsyncRequestFactory
class Client
class ClientHandler
class ClientMixin
class FakePayload
class RedirectCycleError
class RequestFactory
Functions
closing_iterator_wrapper (iterable, close)
aclosing_iterator_wrapper (iterable, close)
conditional_content_removal (request, response)
store_rendered_templates (store, signal, sender, template, context, **kwargs)
encode_multipart (boundary, data)
encode_file (boundary, key, file)
Variables
str BOUNDARY = "BoUnDaRyStRiNg"
str MULTIPART_CONTENT = "multipart/form-data; boundary=%s" % BOUNDARY
CONTENT_TYPE_RE = _lazy_re_compile(r".*; charset=([\w-]+);?")
JSON_CONTENT_TYPE_RE = _lazy_re_compile(r"^application\/(.+\+)?json")
REDIRECT_STATUS_CODES
Function Documentation
aclosing_iterator_wrapper()
django.test.client.aclosing_iterator_wrapper (iterable, close)
Definition at line 129 of file client.py.
async def aclosing_iterator_wrapper(iterable, close):
    try:
        async for chunk in iterable:
            yield chunk
    finally:
        request_finished.disconnect(close_old_connections)
        close()  # will fire request_finished
        request_finished.connect(close_old_connections)
Referenced by django.test.client.AsyncClientHandler.__call__(), and django.test.client.ClientHandler.__call__().
closing_iterator_wrapper()
django.test.client.closing_iterator_wrapper (iterable, close)
Definition at line 120 of file client.py.
def closing_iterator_wrapper(iterable, close):
    try:
        yield from iterable
    finally:
        request_finished.disconnect(close_old_connections)
        close()  # will fire request_finished
        request_finished.connect(close_old_connections)
Referenced by django.test.client.AsyncClientHandler.__call__(), and django.test.client.ClientHandler.__call__().
conditional_content_removal()
django.test.client.conditional_content_removal (request, response)
Simulate the behavior of most web servers by removing the content of
responses for HEAD requests, 1xx, 204, and 304 responses. Ensure
compliance with RFC 9112 Section 6.3.
Definition at line 139 of file client.py.
def conditional_content_removal(request, response):
    """
    Simulate the behavior of most web servers by removing the content of
    responses for HEAD requests, 1xx, 204, and 304 responses. Ensure
    compliance with RFC 9112 Section 6.3.
    """
    if 100 <= response.status_code < 200 or response.status_code in (204, 304):
        if response.streaming:
            response.streaming_content = []
        else:
            response.content = b""
    if request.method == "HEAD":
        if response.streaming:
            response.streaming_content = []
        else:
            response.content = b""
    return response
Referenced by django.test.client.AsyncClientHandler.__call__(), and django.test.client.ClientHandler.__call__().
encode_file()
django.test.client.encode_file (boundary, key, file)
Definition at line 340 of file client.py.
def encode_file(boundary, key, file):
    def to_bytes(s):
        return force_bytes(s, settings.DEFAULT_CHARSET)
    # file.name might not be a string. For example, it's an int for
    # tempfile.TemporaryFile().
    file_has_string_name = hasattr(file, "name") and isinstance(file.name, str)
    filename = os.path.basename(file.name) if file_has_string_name else ""
    if hasattr(file, "content_type"):
        content_type = file.content_type
    elif filename:
        content_type = mimetypes.guess_type(filename)[0]
    else:
        content_type = None
    if content_type is None:
        content_type = "application/octet-stream"
    filename = filename or key
    return [
        to_bytes("--%s" % boundary),
        to_bytes(
            'Content-Disposition: form-data; name="%s"; filename="%s"' % (key, filename)
        ),
        to_bytes("Content-Type: %s" % content_type),
        b"",
        to_bytes(file.read()),
    ]
Referenced by encode_multipart().
encode_multipart()
django.test.client.encode_multipart (boundary, data)
Encode multipart POST data from a dictionary of form values.
The key will be used as the form data name; the value will be transmitted
as content. If the value is a file, the contents of the file will be sent
as an application/octet-stream; otherwise, str(value) will be sent.
Definition at line 278 of file client.py.
def encode_multipart(boundary, data):
    """
    Encode multipart POST data from a dictionary of form values.
    The key will be used as the form data name; the value will be transmitted
    as content. If the value is a file, the contents of the file will be sent
    as an application/octet-stream; otherwise, str(value) will be sent.
    """
    lines = []
    def to_bytes(s):
        return force_bytes(s, settings.DEFAULT_CHARSET)
    # Not by any means perfect, but good enough for our purposes.
    def is_file(thing):
        return hasattr(thing, "read") and callable(thing.read)
    # Each bit of the multipart form data could be either a form value or a
    # file, or a *list* of form values and/or files. Remember that HTTP field
    # names can be duplicated!
    for key, value in data.items():
        if value is None:
            raise TypeError(
                "Cannot encode None for key '%s' as POST data. Did you mean "
                "to pass an empty string or omit the value?" % key
            )
        elif is_file(value):
            lines.extend(encode_file(boundary, key, value))
        elif not isinstance(value, str) and isinstance(value, Iterable):
            for item in value:
                if is_file(item):
                    lines.extend(encode_file(boundary, key, item))
                else:
                    lines.extend(
                        to_bytes(val)
                        for val in [
                            "--%s" % boundary,
                            'Content-Disposition: form-data; name="%s"' % key,
                            "",
                            item,
                        ]
                    )
        else:
            lines.extend(
                to_bytes(val)
                for val in [
                    "--%s" % boundary,
                    'Content-Disposition: form-data; name="%s"' % key,
                    "",
                    value,
                ]
            )
    lines.extend(
        [
            to_bytes("--%s--" % boundary),
            b"",
        ]
    )
    return b"\r\n".join(lines)
References encode_file().
Referenced by django.test.client.RequestFactory._encode_data().
store_rendered_templates()
django.test.client.store_rendered_templates (store, signal, sender, template, context, ** kwargs)
Store templates and contexts that are rendered.
The context is copied so that it is an accurate representation at the time
of rendering.
Definition at line 265 of file client.py.
def store_rendered_templates(store, signal, sender, template, context, **kwargs):
    """
    Store templates and contexts that are rendered.
    The context is copied so that it is an accurate representation at the time
    of rendering.
    """
    store.setdefault("templates", []).append(template)
    if "context" not in store:
        store["context"] = ContextList()
    store["context"].append(copy(context))
Variable Documentation
BOUNDARY
str django.test.client.BOUNDARY = "BoUnDaRyStRiNg"
Definition at line 42 of file client.py.
CONTENT_TYPE_RE
django.test.client.CONTENT_TYPE_RE = _lazy_re_compile(r".*; charset=([\w-]+);?")
Definition at line 44 of file client.py.
JSON_CONTENT_TYPE_RE
django.test.client.JSON_CONTENT_TYPE_RE = _lazy_re_compile(r"^application\/(.+\+)?json")
Definition at line 46 of file client.py.
MULTIPART_CONTENT
str django.test.client.MULTIPART_CONTENT = "multipart/form-data; boundary=%s" % BOUNDARY
Definition at line 43 of file client.py.
REDIRECT_STATUS_CODES
django.test.client.REDIRECT_STATUS_CODES
Initial value:
=  frozenset(
    [
        HTTPStatus.MOVED_PERMANENTLY,
        HTTPStatus.FOUND,
        HTTPStatus.SEE_OTHER,
        HTTPStatus.TEMPORARY_REDIRECT,
        HTTPStatus.PERMANENT_REDIRECT,
    ]
)
Definition at line 48 of file client.py.