Read&Watch: pip._vendor.distlib.markers Namespace Reference
pip._vendor.distlib.markers Namespace Reference
Classes
class Evaluator
Functions
_is_version_marker (s)
_is_literal (o)
_get_versions (s)
default_context ()
interpret (marker, execution_context=None)
Variables
_VERSION_PATTERN = re.compile(r'((\d+(\.\d+)*\w*)|\'(\d+(\.\d+)*\w*)\'|\"(\d+(\.\d+)*\w*)\")')
dict _VERSION_MARKERS = {'python_version', 'python_full_version'}
_DIGITS = re.compile(r'\d+\.\d+')
DEFAULT_CONTEXT = default_context()
evaluator = Evaluator()
Detailed Description
Parser for the environment markers micro-language defined in PEP 508.
Function Documentation
_get_versions()
pip._vendor.distlib.markers._get_versions (s) protected
Definition at line 40 of file markers.py.
def _get_versions(s):
    return {LV(m.groups()[0]) for m in _VERSION_PATTERN.finditer(s)}
Referenced by pip._vendor.distlib.markers.Evaluator.evaluate().
_is_literal()
pip._vendor.distlib.markers._is_literal (o) protected
Definition at line 34 of file markers.py.
def _is_literal(o):
    if not isinstance(o, string_types) or not o:
        return False
    return o[0] in '\'"'
Referenced by pip._vendor.distlib.markers.Evaluator.evaluate().
_is_version_marker()
pip._vendor.distlib.markers._is_version_marker (s) protected
Definition at line 30 of file markers.py.
def _is_version_marker(s):
    return isinstance(s, string_types) and s in _VERSION_MARKERS
Referenced by pip._vendor.distlib.markers.Evaluator.evaluate().
default_context()
pip._vendor.distlib.markers.default_context ()
Definition at line 102 of file markers.py.
def default_context():
    def format_full_version(info):
        version = '%s.%s.%s' % (info.major, info.minor, info.micro)
        kind = info.releaselevel
        if kind != 'final':
            version += kind[0] + str(info.serial)
        return version
    if hasattr(sys, 'implementation'):
        implementation_version = format_full_version(sys.implementation.version)
        implementation_name = sys.implementation.name
    else:
        implementation_version = '0'
        implementation_name = ''
    ppv = platform.python_version()
    m = _DIGITS.match(ppv)
    pv = m.group(0)
    result = {
        'implementation_name': implementation_name,
        'implementation_version': implementation_version,
        'os_name': os.name,
        'platform_machine': platform.machine(),
        'platform_python_implementation': platform.python_implementation(),
        'platform_release': platform.release(),
        'platform_system': platform.system(),
        'platform_version': platform.version(),
        'platform_in_venv': str(in_venv()),
        'python_full_version': ppv,
        'python_version': pv,
        'sys_platform': sys.platform,
    }
    return result
interpret()
pip._vendor.distlib.markers.interpret (marker, execution_context = None)
Interpret a marker and return a result depending on environment.
:param marker: The marker to interpret.
:type marker: str
:param execution_context: The context used for name lookup.
:type execution_context: mapping
Definition at line 144 of file markers.py.
def interpret(marker, execution_context=None):
    """
    Interpret a marker and return a result depending on environment.
    :param marker: The marker to interpret.
    :type marker: str
    :param execution_context: The context used for name lookup.
    :type execution_context: mapping
    """
    try:
        expr, rest = parse_marker(marker)
    except Exception as e:
        raise SyntaxError('Unable to interpret marker syntax: %s: %s' % (marker, e))
    if rest and rest[0] != '#':
        raise SyntaxError('unexpected trailing data in marker: %s: %s' % (marker, rest))
    context = dict(DEFAULT_CONTEXT)
    if execution_context:
        context.update(execution_context)
    return evaluator.evaluate(expr, context)
Variable Documentation
_DIGITS
pip._vendor.distlib.markers._DIGITS = re.compile(r'\d+\.\d+') protected
Definition at line 99 of file markers.py.
_VERSION_MARKERS
dict pip._vendor.distlib.markers._VERSION_MARKERS = {'python_version', 'python_full_version'} protected
Definition at line 27 of file markers.py.
_VERSION_PATTERN
pip._vendor.distlib.markers._VERSION_PATTERN = re.compile(r'((\d+(\.\d+)*\w*)|\'(\d+(\.\d+)*\w*)\'|\"(\d+(\.\d+)*\w*)\")') protected
Definition at line 26 of file markers.py.
DEFAULT_CONTEXT
pip._vendor.distlib.markers.DEFAULT_CONTEXT = default_context()
Definition at line 138 of file markers.py.
evaluator
pip._vendor.distlib.markers.evaluator = Evaluator()
Definition at line 141 of file markers.py.