Read&Watch: pip._vendor.distlib.metadata Namespace Reference
pip._vendor.distlib.metadata Namespace Reference
Classes
class LegacyMetadata
class Metadata
class MetadataConflictError
class MetadataInvalidError
class MetadataMissingError
class MetadataUnrecognizedVersionError
Functions
_version2fieldlist (version)
_best_version (fields)
_get_name_and_version (name, version, for_filename=False)
Variables
logger = logging.getLogger(__name__)
str PKG_INFO_ENCODING = 'utf-8'
str PKG_INFO_PREFERRED_VERSION = '1.1'
_LINE_PREFIX_1_2 = re.compile('\n \\|')
_LINE_PREFIX_PRE_1_2 = re.compile('\n ')
tuple _241_FIELDS
tuple _314_FIELDS
tuple _314_MARKERS = ('Obsoletes', 'Provides', 'Requires', 'Classifier', 'Download-URL')
tuple _345_FIELDS
tuple _345_MARKERS
tuple _426_FIELDS
tuple _426_MARKERS = ('Private-Version', 'Provides-Extra', 'Obsoleted-By', 'Setup-Requires-Dist', 'Extension')
tuple _566_FIELDS = _426_FIELDS + ('Description-Content-Type', 'Requires', 'Provides', 'Obsoletes')
tuple _566_MARKERS = ('Description-Content-Type',)
tuple _643_MARKERS = ('Dynamic', 'License-File')
tuple _643_FIELDS = _566_FIELDS + _643_MARKERS
_ALL_FIELDS = set()
EXTRA_RE = re.compile()
dict _ATTR2FIELD = {name.lower().replace("-", "_"): name for name in _ALL_FIELDS}
dict _FIELD2ATTR = {field: attr for attr, field in _ATTR2FIELD.items()}
tuple _PREDICATE_FIELDS = ('Requires-Dist', 'Obsoletes-Dist', 'Provides-Dist')
tuple _VERSIONS_FIELDS = ('Requires-Python',)
tuple _VERSION_FIELDS = ('Version',)
tuple _LISTFIELDS
tuple _LISTTUPLEFIELDS = ('Project-URL',)
tuple _ELEMENTSFIELD = ('Keywords',)
tuple _UNICODEFIELDS = ('Author', 'Maintainer', 'Summary', 'Description')
_MISSING = object()
_FILESAFE = re.compile('[^A-Za-z0-9.]+')
str METADATA_FILENAME = 'pydist.json'
str WHEEL_METADATA_FILENAME = 'metadata.json'
str LEGACY_METADATA_FILENAME = 'METADATA'
Detailed Description
Implementation of the Metadata for Python packages PEPs.
Supports all metadata formats (1.0, 1.1, 1.2, 1.3/2.1 and 2.2).
Function Documentation
_best_version()
pip._vendor.distlib.metadata._best_version (fields) protected
Detect the best version depending on the fields used.
Definition at line 121 of file metadata.py.
def _best_version(fields):
    """Detect the best version depending on the fields used."""
    def _has_marker(keys, markers):
        return any(marker in keys for marker in markers)
    keys = [key for key, value in fields.items() if value not in ([], 'UNKNOWN', None)]
    possible_versions = ['1.0', '1.1', '1.2', '1.3', '2.1', '2.2']  # 2.0 removed
    # first let's try to see if a field is not part of one of the version
    for key in keys:
        if key not in _241_FIELDS and '1.0' in possible_versions:
            possible_versions.remove('1.0')
            logger.debug('Removed 1.0 due to %s', key)
        if key not in _314_FIELDS and '1.1' in possible_versions:
            possible_versions.remove('1.1')
            logger.debug('Removed 1.1 due to %s', key)
        if key not in _345_FIELDS and '1.2' in possible_versions:
            possible_versions.remove('1.2')
            logger.debug('Removed 1.2 due to %s', key)
        if key not in _566_FIELDS and '1.3' in possible_versions:
            possible_versions.remove('1.3')
            logger.debug('Removed 1.3 due to %s', key)
        if key not in _566_FIELDS and '2.1' in possible_versions:
            if key != 'Description':  # In 2.1, description allowed after headers
                possible_versions.remove('2.1')
                logger.debug('Removed 2.1 due to %s', key)
        if key not in _643_FIELDS and '2.2' in possible_versions:
            possible_versions.remove('2.2')
            logger.debug('Removed 2.2 due to %s', key)
        # if key not in _426_FIELDS and '2.0' in possible_versions:
        # possible_versions.remove('2.0')
        # logger.debug('Removed 2.0 due to %s', key)
    # possible_version contains qualified versions
    if len(possible_versions) == 1:
        return possible_versions[0]  # found !
    elif len(possible_versions) == 0:
        logger.debug('Out of options - unknown metadata set: %s', fields)
        raise MetadataConflictError('Unknown metadata set')
    # let's see if one unique marker is found
    is_1_1 = '1.1' in possible_versions and _has_marker(keys, _314_MARKERS)
    is_1_2 = '1.2' in possible_versions and _has_marker(keys, _345_MARKERS)
    is_2_1 = '2.1' in possible_versions and _has_marker(keys, _566_MARKERS)
    # is_2_0 = '2.0' in possible_versions and _has_marker(keys, _426_MARKERS)
    is_2_2 = '2.2' in possible_versions and _has_marker(keys, _643_MARKERS)
    if int(is_1_1) + int(is_1_2) + int(is_2_1) + int(is_2_2) > 1:
        raise MetadataConflictError('You used incompatible 1.1/1.2/2.1/2.2 fields')
    # we have the choice, 1.0, or 1.2, 2.1 or 2.2
    #   - 1.0 has a broken Summary field but works with all tools
    #   - 1.1 is to avoid
    #   - 1.2 fixes Summary but has little adoption
    #   - 2.1 adds more features
    #   - 2.2 is the latest
    if not is_1_1 and not is_1_2 and not is_2_1 and not is_2_2:
        # we couldn't find any specific marker
        if PKG_INFO_PREFERRED_VERSION in possible_versions:
            return PKG_INFO_PREFERRED_VERSION
    if is_1_1:
        return '1.1'
    if is_1_2:
        return '1.2'
    if is_2_1:
        return '2.1'
    # if is_2_2:
    # return '2.2'
    return '2.2'
# This follows the rules about transforming keys as described in
# https://www.python.org/dev/peps/pep-0566/#id17
Referenced by pip._vendor.distlib.metadata.LegacyMetadata.set_metadata_version().
_get_name_and_version()
pip._vendor.distlib.metadata._get_name_and_version (name, version, for_filename = False) protected
Return the distribution name with version.
If for_filename is true, return a filename-escaped form.
Definition at line 215 of file metadata.py.
def _get_name_and_version(name, version, for_filename=False):
    """Return the distribution name with version.
    If for_filename is true, return a filename-escaped form."""
    if for_filename:
        # For both name and version any runs of non-alphanumeric or '.'
        # characters are replaced with a single '-'.  Additionally any
        # spaces in the version string become '.'
        name = _FILESAFE.sub('-', name)
        version = _FILESAFE.sub('-', version.replace(' ', '.'))
    return '%s-%s' % (name, version)
Referenced by pip._vendor.distlib.metadata.LegacyMetadata.get_fullname().
_version2fieldlist()
pip._vendor.distlib.metadata._version2fieldlist (version) protected
Definition at line 103 of file metadata.py.
def _version2fieldlist(version):
    if version == '1.0':
        return _241_FIELDS
    elif version == '1.1':
        return _314_FIELDS
    elif version == '1.2':
        return _345_FIELDS
    elif version in ('1.3', '2.1'):
        # avoid adding field names if already there
        return _345_FIELDS + tuple(f for f in _566_FIELDS if f not in _345_FIELDS)
    elif version == '2.0':
        raise ValueError('Metadata 2.0 is withdrawn and not supported')
        # return _426_FIELDS
    elif version == '2.2':
        return _643_FIELDS
    raise MetadataUnrecognizedVersionError(version)
Referenced by pip._vendor.distlib.metadata.LegacyMetadata.keys(), pip._vendor.distlib.metadata.LegacyMetadata.todict(), and pip._vendor.distlib.metadata.LegacyMetadata.write_file().
Variable Documentation
_241_FIELDS
tuple pip._vendor.distlib.metadata._241_FIELDS protected
Initial value:
=  ('Metadata-Version', 'Name', 'Version', 'Platform', 'Summary', 'Description', 'Keywords', 'Home-page',
               'Author', 'Author-email', 'License')
Definition at line 55 of file metadata.py.
_314_FIELDS
tuple pip._vendor.distlib.metadata._314_FIELDS protected
Initial value:
=  ('Metadata-Version', 'Name', 'Version', 'Platform', 'Supported-Platform', 'Summary', 'Description',
               'Keywords', 'Home-page', 'Author', 'Author-email', 'License', 'Classifier', 'Download-URL', 'Obsoletes',
               'Provides', 'Requires')
Definition at line 58 of file metadata.py.
_314_MARKERS
tuple pip._vendor.distlib.metadata._314_MARKERS = ('Obsoletes', 'Provides', 'Requires', 'Classifier', 'Download-URL') protected
Definition at line 62 of file metadata.py.
_345_FIELDS
tuple pip._vendor.distlib.metadata._345_FIELDS protected
Initial value:
=  ('Metadata-Version', 'Name', 'Version', 'Platform', 'Supported-Platform', 'Summary', 'Description',
               'Keywords', 'Home-page', 'Author', 'Author-email', 'Maintainer', 'Maintainer-email', 'License',
               'Classifier', 'Download-URL', 'Obsoletes-Dist', 'Project-URL', 'Provides-Dist', 'Requires-Dist',
               'Requires-Python', 'Requires-External')
Definition at line 64 of file metadata.py.
_345_MARKERS
tuple pip._vendor.distlib.metadata._345_MARKERS protected
Initial value:
=  ('Provides-Dist', 'Requires-Dist', 'Requires-Python', 'Obsoletes-Dist', 'Requires-External',
                'Maintainer', 'Maintainer-email', 'Project-URL')
Definition at line 69 of file metadata.py.
_426_FIELDS
tuple pip._vendor.distlib.metadata._426_FIELDS protected
Initial value:
=  ('Metadata-Version', 'Name', 'Version', 'Platform', 'Supported-Platform', 'Summary', 'Description',
               'Keywords', 'Home-page', 'Author', 'Author-email', 'Maintainer', 'Maintainer-email', 'License',
               'Classifier', 'Download-URL', 'Obsoletes-Dist', 'Project-URL', 'Provides-Dist', 'Requires-Dist',
               'Requires-Python', 'Requires-External', 'Private-Version', 'Obsoleted-By', 'Setup-Requires-Dist',
               'Extension', 'Provides-Extra')
Definition at line 72 of file metadata.py.
_426_MARKERS
tuple pip._vendor.distlib.metadata._426_MARKERS = ('Private-Version', 'Provides-Extra', 'Obsoleted-By', 'Setup-Requires-Dist', 'Extension') protected
Definition at line 78 of file metadata.py.
_566_FIELDS
tuple pip._vendor.distlib.metadata._566_FIELDS = _426_FIELDS + ('Description-Content-Type', 'Requires', 'Provides', 'Obsoletes') protected
Definition at line 84 of file metadata.py.
_566_MARKERS
tuple pip._vendor.distlib.metadata._566_MARKERS = ('Description-Content-Type',) protected
Definition at line 86 of file metadata.py.
_643_FIELDS
tuple pip._vendor.distlib.metadata._643_FIELDS = _566_FIELDS + _643_MARKERS protected
Definition at line 90 of file metadata.py.
_643_MARKERS
tuple pip._vendor.distlib.metadata._643_MARKERS = ('Dynamic', 'License-File') protected
Definition at line 88 of file metadata.py.
_ALL_FIELDS
pip._vendor.distlib.metadata._ALL_FIELDS = set() protected
Definition at line 92 of file metadata.py.
_ATTR2FIELD
dict pip._vendor.distlib.metadata._ATTR2FIELD = {name.lower().replace("-", "_"): name for name in _ALL_FIELDS} protected
Definition at line 195 of file metadata.py.
_ELEMENTSFIELD
tuple pip._vendor.distlib.metadata._ELEMENTSFIELD = ('Keywords',) protected
Definition at line 206 of file metadata.py.
_FIELD2ATTR
dict pip._vendor.distlib.metadata._FIELD2ATTR = {field: attr for attr, field in _ATTR2FIELD.items()} protected
Definition at line 196 of file metadata.py.
_FILESAFE
pip._vendor.distlib.metadata._FILESAFE = re.compile('[^A-Za-z0-9.]+') protected
Definition at line 212 of file metadata.py.
_LINE_PREFIX_1_2
pip._vendor.distlib.metadata._LINE_PREFIX_1_2 = re.compile('\n \\|') protected
Definition at line 53 of file metadata.py.
_LINE_PREFIX_PRE_1_2
pip._vendor.distlib.metadata._LINE_PREFIX_PRE_1_2 = re.compile('\n ') protected
Definition at line 54 of file metadata.py.
_LISTFIELDS
tuple pip._vendor.distlib.metadata._LISTFIELDS protected
Initial value:
=  ('Platform', 'Classifier', 'Obsoletes', 'Requires', 'Provides', 'Obsoletes-Dist', 'Provides-Dist',
               'Requires-Dist', 'Requires-External', 'Project-URL', 'Supported-Platform', 'Setup-Requires-Dist',
               'Provides-Extra', 'Extension', 'License-File')
Definition at line 201 of file metadata.py.
_LISTTUPLEFIELDS
tuple pip._vendor.distlib.metadata._LISTTUPLEFIELDS = ('Project-URL',) protected
Definition at line 204 of file metadata.py.
_MISSING
pip._vendor.distlib.metadata._MISSING = object() protected
Definition at line 210 of file metadata.py.
_PREDICATE_FIELDS
tuple pip._vendor.distlib.metadata._PREDICATE_FIELDS = ('Requires-Dist', 'Obsoletes-Dist', 'Provides-Dist') protected
Definition at line 198 of file metadata.py.
_UNICODEFIELDS
tuple pip._vendor.distlib.metadata._UNICODEFIELDS = ('Author', 'Maintainer', 'Summary', 'Description') protected
Definition at line 208 of file metadata.py.
_VERSION_FIELDS
tuple pip._vendor.distlib.metadata._VERSION_FIELDS = ('Version',) protected
Definition at line 200 of file metadata.py.
_VERSIONS_FIELDS
tuple pip._vendor.distlib.metadata._VERSIONS_FIELDS = ('Requires-Python',) protected
Definition at line 199 of file metadata.py.
EXTRA_RE
pip._vendor.distlib.metadata.EXTRA_RE = re.compile()
Definition at line 100 of file metadata.py.
LEGACY_METADATA_FILENAME
str pip._vendor.distlib.metadata.LEGACY_METADATA_FILENAME = 'METADATA'
Definition at line 581 of file metadata.py.
logger
pip._vendor.distlib.metadata.logger = logging.getLogger(__name__)
Definition at line 24 of file metadata.py.
METADATA_FILENAME
str pip._vendor.distlib.metadata.METADATA_FILENAME = 'pydist.json'
Definition at line 579 of file metadata.py.
PKG_INFO_ENCODING
str pip._vendor.distlib.metadata.PKG_INFO_ENCODING = 'utf-8'
Definition at line 47 of file metadata.py.
PKG_INFO_PREFERRED_VERSION
str pip._vendor.distlib.metadata.PKG_INFO_PREFERRED_VERSION = '1.1'
Definition at line 51 of file metadata.py.
WHEEL_METADATA_FILENAME
str pip._vendor.distlib.metadata.WHEEL_METADATA_FILENAME = 'metadata.json'
Definition at line 580 of file metadata.py.