Read&Watch: tomlkit.api Namespace Reference
tomlkit.api Namespace Reference
Functions
TOMLDocument loads (str|bytes string)
str dumps (Mapping data, bool sort_keys=False)
TOMLDocument load (IO[str]|IO[bytes] fp)
None dump (Mapping data, IO[str] fp, *, bool sort_keys=False)
TOMLDocument parse (str|bytes string)
TOMLDocument document ()
Integer integer (str|int raw)
Float float_ (str|float raw)
Bool boolean (str raw)
String string (str raw, *, bool literal=False, bool multiline=False, bool escape=True)
Date date (str raw)
Time time (str raw)
DateTime datetime (str raw)
Array array (str raw="[]")
Table table (bool|None is_super_table=None)
InlineTable inline_table ()
AoT aot ()
Key key (str|Iterable[str] k)
_Item value (str raw)
tuple[Key, _Item] key_value (str src)
Whitespace ws (str src)
Whitespace nl ()
Comment comment (str string)
E register_encoder (E encoder)
None unregister_encoder (Encoder encoder)
Variables
E = TypeVar("E", bound=Encoder)
Function Documentation
aot()
AoT tomlkit.api.aot ()
Create an array of table.
:Example:
>>> doc = document()
>>> aot = aot()
>>> aot.append(item({'x': 1}))
>>> doc.append('foo', aot)
>>> print(doc.as_string())
[[foo]]
x = 1
Definition at line 216 of file api.py.
def aot() -> AoT:
    """Create an array of table.
    :Example:
    >>> doc = document()
    >>> aot = aot()
    >>> aot.append(item({'x': 1}))
    >>> doc.append('foo', aot)
    >>> print(doc.as_string())
    [[foo]]
    x = 1
    """
    return AoT([])
array()
Array tomlkit.api.array (str raw = "[]")
Create an array item for its string representation.
:Example:
>>> array("[1, 2, 3]")  # Create from a string
[1, 2, 3]
>>> a = array()
>>> a.extend([1, 2, 3])  # Create from a list
>>> a
[1, 2, 3]
Definition at line 168 of file api.py.
def array(raw: str = "[]") -> Array:
    """Create an array item for its string representation.
    :Example:
    >>> array("[1, 2, 3]")  # Create from a string
    [1, 2, 3]
    >>> a = array()
    >>> a.extend([1, 2, 3])  # Create from a list
    >>> a
    [1, 2, 3]
    """
    return value(raw)
References value().
boolean()
Bool tomlkit.api.boolean (str raw)
Turn `true` or `false` into a boolean item.
Definition at line 112 of file api.py.
def boolean(raw: str) -> Bool:
    """Turn `true` or `false` into a boolean item."""
    return item(raw == "true")
comment()
Comment tomlkit.api.comment (str string)
Create a comment item.
Definition at line 290 of file api.py.
def comment(string: str) -> Comment:
    """Create a comment item."""
    return Comment(Trivia(comment_ws="  ", comment="# " + string))
date()
Date tomlkit.api.date (str raw)
Create a TOML date.
Definition at line 141 of file api.py.
def date(raw: str) -> Date:
    """Create a TOML date."""
    value = parse_rfc3339(raw)
    if not isinstance(value, _datetime.date):
        raise ValueError("date() only accepts date strings.")
    return item(value)
datetime()
DateTime tomlkit.api.datetime (str raw)
Create a TOML datetime.
Definition at line 159 of file api.py.
def datetime(raw: str) -> DateTime:
    """Create a TOML datetime."""
    value = parse_rfc3339(raw)
    if not isinstance(value, _datetime.datetime):
        raise ValueError("datetime() only accepts datetime strings.")
    return item(value)
document()
TOMLDocument tomlkit.api.document ()
Returns a new TOMLDocument instance.
Definition at line 94 of file api.py.
def document() -> TOMLDocument:
    """
    Returns a new TOMLDocument instance.
    """
    return TOMLDocument()
# Items
dump()
None tomlkit.api.dump (Mapping data, IO[str] fp, * , bool sort_keys = False)
Dump a TOMLDocument into a writable file stream.
:param data: a dict-like object to dump
:param sort_keys: if true, sort the keys in alphabetic order
:Example:
>>> with open("output.toml", "w") as fp:
...     tomlkit.dump(data, fp)
Definition at line 72 of file api.py.
def dump(data: Mapping, fp: IO[str], *, sort_keys: bool = False) -> None:
    """
    Dump a TOMLDocument into a writable file stream.
    :param data: a dict-like object to dump
    :param sort_keys: if true, sort the keys in alphabetic order
    :Example:
    >>> with open("output.toml", "w") as fp:
    ...     tomlkit.dump(data, fp)
    """
    fp.write(dumps(data, sort_keys=sort_keys))
References dumps().
dumps()
str tomlkit.api.dumps (Mapping data, bool sort_keys = False)
Dumps a TOMLDocument into a string.
Definition at line 49 of file api.py.
def dumps(data: Mapping, sort_keys: bool = False) -> str:
    """
    Dumps a TOMLDocument into a string.
    """
    if not isinstance(data, Container) and isinstance(data, Mapping):
        data = item(dict(data), _sort_keys=sort_keys)
    try:
        # data should be a `Container` (and therefore implement `as_string`)
        # for all type safe invocations of this function
        return data.as_string()  # type: ignore[attr-defined]
    except AttributeError as ex:
        msg = f"Expecting Mapping or TOML Container, {type(data)} given"
        raise TypeError(msg) from ex
Referenced by dump().
float_()
Float tomlkit.api.float_ (str | float raw)
Create an float item from a number or string.
Definition at line 107 of file api.py.
def float_(raw: str | float) -> Float:
    """Create an float item from a number or string."""
    return item(float(raw))
inline_table()
InlineTable tomlkit.api.inline_table ()
Create an inline table.
:Example:
>>> table = inline_table()
>>> table.update({'x': 1, 'y': 2})
>>> print(table.as_string())
{x = 1, y = 2}
Definition at line 203 of file api.py.
def inline_table() -> InlineTable:
    """Create an inline table.
    :Example:
    >>> table = inline_table()
    >>> table.update({'x': 1, 'y': 2})
    >>> print(table.as_string())
    {x = 1, y = 2}
    """
    return InlineTable(Container(), Trivia(), new=True)
integer()
Integer tomlkit.api.integer (str | int raw)
Create an integer item from a number or string.
Definition at line 102 of file api.py.
def integer(raw: str | int) -> Integer:
    """Create an integer item from a number or string."""
    return item(int(raw))
key()
Key tomlkit.api.key (str | Iterable[str] k)
Create a key from a string. When a list of string is given,
it will create a dotted key.
:Example:
>>> doc = document()
>>> doc.append(key('foo'), 1)
>>> doc.append(key(['bar', 'baz']), 2)
>>> print(doc.as_string())
foo = 1
bar.baz = 2
Definition at line 232 of file api.py.
def key(k: str | Iterable[str]) -> Key:
    """Create a key from a string. When a list of string is given,
    it will create a dotted key.
    :Example:
    >>> doc = document()
    >>> doc.append(key('foo'), 1)
    >>> doc.append(key(['bar', 'baz']), 2)
    >>> print(doc.as_string())
    foo = 1
    bar.baz = 2
    """
    if isinstance(k, str):
        return SingleKey(k)
    return DottedKey([key(_k) for _k in k])
References key().
Referenced by key().
key_value()
tuple[Key, _Item] tomlkit.api.key_value (str src)
Parse a key-value pair from a string.
:Example:
>>> key_value("foo = 1")
(Key('foo'), 1)
Definition at line 269 of file api.py.
def key_value(src: str) -> tuple[Key, _Item]:
    """Parse a key-value pair from a string.
    :Example:
    >>> key_value("foo = 1")
    (Key('foo'), 1)
    """
    return Parser(src)._parse_key_value()
load()
TOMLDocument tomlkit.api.load (IO[str] | IO[bytes] fp)
Load toml document from a file-like object.
Definition at line 65 of file api.py.
def load(fp: IO[str] | IO[bytes]) -> TOMLDocument:
    """
    Load toml document from a file-like object.
    """
    return parse(fp.read())
References parse().
loads()
TOMLDocument tomlkit.api.loads (str | bytes string)
Parses a string into a TOMLDocument.
Alias for parse().
Definition at line 40 of file api.py.
def loads(string: str | bytes) -> TOMLDocument:
    """
    Parses a string into a TOMLDocument.
    Alias for parse().
    """
    return parse(string)
References parse().
nl()
Whitespace tomlkit.api.nl ()
Create a newline item.
Definition at line 285 of file api.py.
def nl() -> Whitespace:
    """Create a newline item."""
    return ws("\n")
References ws().
parse()
TOMLDocument tomlkit.api.parse (str | bytes string)
Parses a string or bytes into a TOMLDocument.
Definition at line 87 of file api.py.
def parse(string: str | bytes) -> TOMLDocument:
    """
    Parses a string or bytes into a TOMLDocument.
    """
    return Parser(string).parse()
References parse().
Referenced by load(), loads(), and parse().
register_encoder()
E tomlkit.api.register_encoder (E encoder)
Add a custom encoder, which should be a function that will be called
if the value can't otherwise be converted. It should takes a single value
and return a TOMLKit item or raise a ``TypeError``.
Definition at line 298 of file api.py.
def register_encoder(encoder: E) -> E:
    """Add a custom encoder, which should be a function that will be called
    if the value can't otherwise be converted. It should takes a single value
    and return a TOMLKit item or raise a ``TypeError``.
    """
    CUSTOM_ENCODERS.append(encoder)
    return encoder
string()
String tomlkit.api.string (str raw, * , bool literal = False, bool multiline = False, bool escape = True)
Create a string item.
By default, this function will create *single line basic* strings, but
boolean flags (e.g. ``literal=True`` and/or ``multiline=True``)
can be used for personalization.
For more information, please check the spec: `<https://toml.io/en/v1.0.0#string>`__.
Common escaping rules will be applied for basic strings.
This can be controlled by explicitly setting ``escape=False``.
Please note that, if you disable escaping, you will have to make sure that
the given strings don't contain any forbidden character or sequence.
Definition at line 117 of file api.py.
) -> String:
    """Create a string item.
    By default, this function will create *single line basic* strings, but
    boolean flags (e.g. ``literal=True`` and/or ``multiline=True``)
    can be used for personalization.
    For more information, please check the spec: `<https://toml.io/en/v1.0.0#string>`__.
    Common escaping rules will be applied for basic strings.
    This can be controlled by explicitly setting ``escape=False``.
    Please note that, if you disable escaping, you will have to make sure that
    the given strings don't contain any forbidden character or sequence.
    """
    type_ = _StringType.select(literal, multiline)
    return String.from_raw(raw, type_, escape)
table()
Table tomlkit.api.table (bool | None is_super_table = None)
Create an empty table.
:param is_super_table: if true, the table is a super table
:Example:
>>> doc = document()
>>> foo = table(True)
>>> bar = table()
>>> bar.update({'x': 1})
>>> foo.append('bar', bar)
>>> doc.append('foo', foo)
>>> print(doc.as_string())
[foo.bar]
x = 1
Definition at line 183 of file api.py.
def table(is_super_table: bool | None = None) -> Table:
    """Create an empty table.
    :param is_super_table: if true, the table is a super table
    :Example:
    >>> doc = document()
    >>> foo = table(True)
    >>> bar = table()
    >>> bar.update({'x': 1})
    >>> foo.append('bar', bar)
    >>> doc.append('foo', foo)
    >>> print(doc.as_string())
    [foo.bar]
    x = 1
    """
    return Table(Container(), Trivia(), False, is_super_table)
time()
Time tomlkit.api.time (str raw)
Create a TOML time.
Definition at line 150 of file api.py.
def time(raw: str) -> Time:
    """Create a TOML time."""
    value = parse_rfc3339(raw)
    if not isinstance(value, _datetime.time):
        raise ValueError("time() only accepts time strings.")
    return item(value)
unregister_encoder()
None tomlkit.api.unregister_encoder (Encoder encoder)
Unregister a custom encoder.
Definition at line 307 of file api.py.
def unregister_encoder(encoder: Encoder) -> None:
    """Unregister a custom encoder."""
    with contextlib.suppress(ValueError):
        CUSTOM_ENCODERS.remove(encoder)
value()
_Item tomlkit.api.value (str raw)
Parse a simple value from a string.
:Example:
>>> value("1")
1
>>> value("true")
True
>>> value("[1, 2, 3]")
[1, 2, 3]
Definition at line 250 of file api.py.
def value(raw: str) -> _Item:
    """Parse a simple value from a string.
    :Example:
    >>> value("1")
    1
    >>> value("true")
    True
    >>> value("[1, 2, 3]")
    [1, 2, 3]
    """
    parser = Parser(raw)
    v = parser._parse_value()
    if not parser.end():
        raise parser.parse_error(UnexpectedCharError, char=parser._current)
    return v
Referenced by array().
ws()
Whitespace tomlkit.api.ws (str src)
Create a whitespace from a string.
Definition at line 280 of file api.py.
def ws(src: str) -> Whitespace:
    """Create a whitespace from a string."""
    return Whitespace(src, fixed=True)
Referenced by nl().
Variable Documentation
E
tomlkit.api.E = TypeVar("E", bound=Encoder)
Definition at line 295 of file api.py.