Read&Watch: isort.comments Namespace Reference
isort.comments Namespace Reference
Functions
Tuple[str, str] parse (str line)
str add_to_line (Optional[List[str]] comments, str original_string="", bool removed=False, str comment_prefix="")
Function Documentation
add_to_line()
str isort.comments.add_to_line (Optional[List[str]] comments, str original_string = "", bool removed = False, str comment_prefix = "")
Returns a string with comments added if removed is not set.
Definition at line 15 of file comments.py.
) -> str:
    """Returns a string with comments added if removed is not set."""
    if removed:
        return parse(original_string)[0]
    if not comments:
        return original_string
    unique_comments: List[str] = []
    for comment in comments:
        if comment not in unique_comments:
            unique_comments.append(comment)
    return f"{parse(original_string)[0]}{comment_prefix} {'; '.join(unique_comments)}"
Referenced by isort.wrap_modes._vertical_grid_common(), isort.wrap_modes.grid(), isort.wrap_modes.hanging_indent(), isort.wrap_modes.hanging_indent_with_parentheses(), isort.wrap_modes.vertical(), isort.wrap_modes.vertical_hanging_indent(), and isort.wrap_modes.vertical_prefix_from_module_import().
parse()
Tuple[str, str] isort.comments.parse (str line)
Parses import lines for comments and returns back the
import statement and the associated comment.
Definition at line 4 of file comments.py.
def parse(line: str) -> Tuple[str, str]:
    """Parses import lines for comments and returns back the
    import statement and the associated comment.
    """
    comment_start = line.find("#")
    if comment_start != -1:
        return (line[:comment_start], line[comment_start + 1 :].strip())
    return (line, "")