Read&Watch: django.utils.html Namespace Reference
django.utils.html Namespace Reference
Classes
class CountsDict
class MLStripper
class Urlizer
Functions
escape (text)
escapejs (value)
json_script (value, element_id=None, encoder=None)
conditional_escape (text)
format_html (format_string, *args, **kwargs)
format_html_join (sep, format_string, args_generator)
linebreaks (value, autoescape=False)
_strip_once (value)
strip_tags (value)
strip_spaces_between_tags (value)
smart_urlquote (url)
urlize (text, trim_url_limit=None, nofollow=False, autoescape=False)
avoid_wrapping (value)
html_safe (klass)
Variables
VOID_ELEMENTS
int MAX_URL_LENGTH = 2048
dict _js_escapes
dict _json_script_escapes
urlizer = Urlizer()
Detailed Description
HTML utilities suitable for global use.
Function Documentation
_strip_once()
django.utils.html._strip_once (value) protected
Internal tag stripping utility used by strip_tags.
Definition at line 195 of file html.py.
def _strip_once(value):
    """
    Internal tag stripping utility used by strip_tags.
    """
    s = MLStripper()
    s.feed(value)
    s.close()
    return s.get_data()
@keep_lazy_text
Referenced by strip_tags().
avoid_wrapping()
django.utils.html.avoid_wrapping (value)
Avoid text wrapping in the middle of a phrase by adding non-breaking
spaces where there previously were normal spaces.
Definition at line 478 of file html.py.
def avoid_wrapping(value):
    """
    Avoid text wrapping in the middle of a phrase by adding non-breaking
    spaces where there previously were normal spaces.
    """
    return value.replace(" ", "\xa0")
conditional_escape()
django.utils.html.conditional_escape (text)
Similar to escape(), except that it doesn't operate on pre-escaped strings.
This function relies on the __html__ convention used both by Django's
SafeData class and by third-party libraries like markupsafe.
Definition at line 109 of file html.py.
def conditional_escape(text):
    """
    Similar to escape(), except that it doesn't operate on pre-escaped strings.
    This function relies on the __html__ convention used both by Django's
    SafeData class and by third-party libraries like markupsafe.
    """
    if isinstance(text, Promise):
        text = str(text)
    if hasattr(text, "__html__"):
        return text.__html__()
    else:
        return escape(text)
References escape().
Referenced by format_html(), and format_html_join().
escape()
django.utils.html.escape (text)
Return the given text with ampersands, quotes and angle brackets encoded
for use in HTML.
Always escape input, even if it's already escaped and marked as such.
This may result in double-escaping. If this is a concern, use
conditional_escape() instead.
Definition at line 45 of file html.py.
def escape(text):
    """
    Return the given text with ampersands, quotes and angle brackets encoded
    for use in HTML.
    Always escape input, even if it's already escaped and marked as such.
    This may result in double-escaping. If this is a concern, use
    conditional_escape() instead.
    """
    return SafeString(html.escape(str(text)))
Referenced by conditional_escape(), django.utils.html.Urlizer.handle_word(), and linebreaks().
escapejs()
django.utils.html.escapejs (value)
Hex encode characters for use in JavaScript strings.
Definition at line 77 of file html.py.
def escapejs(value):
    """Hex encode characters for use in JavaScript strings."""
    return mark_safe(str(value).translate(_js_escapes))
format_html()
django.utils.html.format_html (format_string, * args, ** kwargs)
Similar to str.format, but pass all arguments through conditional_escape(),
and call mark_safe() on the result. This function should be used instead
of str.format or % interpolation to build up small HTML fragments.
Definition at line 124 of file html.py.
def format_html(format_string, *args, **kwargs):
    """
    Similar to str.format, but pass all arguments through conditional_escape(),
    and call mark_safe() on the result. This function should be used instead
    of str.format or % interpolation to build up small HTML fragments.
    """
    if not (args or kwargs):
        # RemovedInDjango60Warning: when the deprecation ends, replace with:
        # raise TypeError("args or kwargs must be provided.")
        warnings.warn(
            "Calling format_html() without passing args or kwargs is deprecated.",
            RemovedInDjango60Warning,
            stacklevel=2,
        )
    args_safe = map(conditional_escape, args)
    kwargs_safe = {k: conditional_escape(v) for (k, v) in kwargs.items()}
    return mark_safe(format_string.format(*args_safe, **kwargs_safe))
References conditional_escape().
Referenced by format_html_join(), and json_script().
format_html_join()
django.utils.html.format_html_join (sep, format_string, args_generator)
A wrapper of format_html, for the common case of a group of arguments that
need to be formatted using the same format string, and then joined using
'sep'. 'sep' is also passed through conditional_escape.
'args_generator' should be an iterator that returns the sequence of 'args'
that will be passed to format_html.
Example:
  format_html_join('\n', "<li>{} {}</li>", ((u.first_name, u.last_name)
                                              for u in users))
Definition at line 143 of file html.py.
def format_html_join(sep, format_string, args_generator):
    """
    A wrapper of format_html, for the common case of a group of arguments that
    need to be formatted using the same format string, and then joined using
    'sep'. 'sep' is also passed through conditional_escape.
    'args_generator' should be an iterator that returns the sequence of 'args'
    that will be passed to format_html.
    Example:
      format_html_join('\n', "<li>{} {}</li>", ((u.first_name, u.last_name)
                                                  for u in users))
    """
    return mark_safe(
        conditional_escape(sep).join(
            format_html(format_string, *args) for args in args_generator
        )
    )
@keep_lazy_text
References conditional_escape(), and format_html().
html_safe()
django.utils.html.html_safe (klass)
A decorator that defines the __html__ method. This helps non-Django
templates to detect classes whose __str__ methods return SafeString.
Definition at line 486 of file html.py.
def html_safe(klass):
    """
    A decorator that defines the __html__ method. This helps non-Django
    templates to detect classes whose __str__ methods return SafeString.
    """
    if "__html__" in klass.__dict__:
        raise ValueError(
            "can't apply @html_safe to %s because it defines "
            "__html__()." % klass.__name__
        )
    if "__str__" not in klass.__dict__:
        raise ValueError(
            "can't apply @html_safe to %s because it doesn't "
            "define __str__()." % klass.__name__
        )
    klass_str = klass.__str__
    klass.__str__ = lambda self: mark_safe(klass_str(self))
    klass.__html__ = lambda self: str(self)
    return klass
json_script()
django.utils.html.json_script (value, element_id = None, encoder = None)
Escape all the HTML/XML special characters with their unicode escapes, so
value is safe to be output anywhere except for inside a tag attribute. Wrap
the escaped JSON in a script tag.
Definition at line 89 of file html.py.
def json_script(value, element_id=None, encoder=None):
    """
    Escape all the HTML/XML special characters with their unicode escapes, so
    value is safe to be output anywhere except for inside a tag attribute. Wrap
    the escaped JSON in a script tag.
    """
    from django.core.serializers.json import DjangoJSONEncoder
    json_str = json.dumps(value, cls=encoder or DjangoJSONEncoder).translate(
        _json_script_escapes
    )
    if element_id:
        template = '<script id="{}" type="application/json">{}</script>'
        args = (element_id, mark_safe(json_str))
    else:
        template = '<script type="application/json">{}</script>'
        args = (mark_safe(json_str),)
    return format_html(template, *args)
References format_html().
linebreaks()
django.utils.html.linebreaks (value, autoescape = False)
Convert newlines into <p> and <br>s.
Definition at line 165 of file html.py.
def linebreaks(value, autoescape=False):
    """Convert newlines into <p> and <br>s."""
    value = normalize_newlines(value)
    paras = re.split("\n{2,}", str(value))
    if autoescape:
        paras = ["<p>%s</p>" % escape(p).replace("\n", "<br>") for p in paras]
    else:
        paras = ["<p>%s</p>" % p.replace("\n", "<br>") for p in paras]
    return "\n\n".join(paras)
References escape().
smart_urlquote()
django.utils.html.smart_urlquote (url)
Quote a URL if it isn't already quoted.
Definition at line 226 of file html.py.
def smart_urlquote(url):
    """Quote a URL if it isn't already quoted."""
    def unquote_quote(segment):
        segment = unquote(segment)
        # Tilde is part of RFC 3986 Section 2.3 Unreserved Characters,
        # see also https://bugs.python.org/issue16285
        return quote(segment, safe=RFC3986_SUBDELIMS + RFC3986_GENDELIMS + "~")
    # Handle IDN before quoting.
    try:
        scheme, netloc, path, query, fragment = urlsplit(url)
    except ValueError:
        # invalid IPv6 URL (normally square brackets in hostname part).
        return unquote_quote(url)
    try:
        netloc = punycode(netloc)  # IDN -> ACE
    except UnicodeError:  # invalid domain part
        return unquote_quote(url)
    if query:
        # Separately unquoting key/value, so as to not mix querystring separators
        # included in query values. See #22267.
        query_parts = [
            (unquote(q[0]), unquote(q[1]))
            for q in parse_qsl(query, keep_blank_values=True)
        ]
        # urlencode will take care of quoting
        query = urlencode(query_parts)
    path = unquote_quote(path)
    fragment = unquote_quote(fragment)
    return urlunsplit((scheme, netloc, path, query, fragment))
Referenced by django.utils.html.Urlizer.handle_word().
strip_spaces_between_tags()
django.utils.html.strip_spaces_between_tags (value)
Return the given HTML with spaces between tags removed.
Definition at line 221 of file html.py.
def strip_spaces_between_tags(value):
    """Return the given HTML with spaces between tags removed."""
    return re.sub(r">\s+<", "><", str(value))
strip_tags()
django.utils.html.strip_tags (value)
Return the given HTML with all tags stripped.
Definition at line 206 of file html.py.
def strip_tags(value):
    """Return the given HTML with all tags stripped."""
    # Note: in typical case this loop executes _strip_once once. Loop condition
    # is redundant, but helps to reduce number of executions of _strip_once.
    value = str(value)
    while "<" in value and ">" in value:
        new_value = _strip_once(value)
        if value.count("<") == new_value.count("<"):
            # _strip_once wasn't able to detect more tags.
            break
        value = new_value
    return value
@keep_lazy_text
References _strip_once().
urlize()
django.utils.html.urlize (text, trim_url_limit = None, nofollow = False, autoescape = False)
Definition at line 472 of file html.py.
def urlize(text, trim_url_limit=None, nofollow=False, autoescape=False):
    return urlizer(
        text, trim_url_limit=trim_url_limit, nofollow=nofollow, autoescape=autoescape
    )
References urlizer.
Variable Documentation
_js_escapes
dict django.utils.html._js_escapes protected
Initial value:
=  {
    ord("\\"): "\\u005C",
    ord("'"): "\\u0027",
    ord('"'): "\\u0022",
    ord(">"): "\\u003E",
    ord("<"): "\\u003C",
    ord("&"): "\\u0026",
    ord("="): "\\u003D",
    ord("-"): "\\u002D",
    ord(";"): "\\u003B",
    ord("`"): "\\u0060",
    ord("\u2028"): "\\u2028",
    ord("\u2029"): "\\u2029",
}
Definition at line 57 of file html.py.
_json_script_escapes
dict django.utils.html._json_script_escapes protected
Initial value:
=  {
    ord(">"): "\\u003E",
    ord("<"): "\\u003C",
    ord("&"): "\\u0026",
}
Definition at line 82 of file html.py.
MAX_URL_LENGTH
int django.utils.html.MAX_URL_LENGTH = 2048
Definition at line 41 of file html.py.
urlizer
django.utils.html.urlizer = Urlizer()
Definition at line 468 of file html.py.
Referenced by urlize().
VOID_ELEMENTS
django.utils.html.VOID_ELEMENTS
Initial value:
=  frozenset(
    (
        "area",
        "base",
        "br",
        "col",
        "embed",
        "hr",
        "img",
        "input",
        "link",
        "meta",
        "param",
        "source",
        "track",
        "wbr",
        # Deprecated tags.
        "frame",
        "spacer",
    )
)
Definition at line 19 of file html.py.