Read&Watch: PIL.SpiderImagePlugin Namespace Reference
PIL.SpiderImagePlugin Namespace Reference
Classes
class SpiderImageFile
Functions
int isInt (Any f)
int isSpiderHeader (tuple[float,...] t)
int isSpiderImage (str filename)
list[SpiderImageFile]|None loadImageSeries (list[str]|None filelist=None)
list[bytes] makeSpiderHeader (Image.Image im)
None _save (Image.Image im, IO[bytes] fp, str|bytes filename)
None _save_spider (Image.Image im, IO[bytes] fp, str|bytes filename)
Variables
list iforms = [1, 3, -11, -12, -21, -22]
filename = sys.argv[1]
end
outfile = sys.argv[2]
im = im.transpose(Image.Transpose.FLIP_LEFT_RIGHT)
Function Documentation
_save()
None PIL.SpiderImagePlugin._save (Image.Image im, IO[bytes] fp, str | bytes filename) protected
Definition at line 270 of file SpiderImagePlugin.py.
def _save(im: Image.Image, fp: IO[bytes], filename: str | bytes) -> None:
    if im.mode[0] != "F":
        im = im.convert("F")
    hdr = makeSpiderHeader(im)
    if len(hdr) < 256:
        msg = "Error creating Spider header"
        raise OSError(msg)
    # write the SPIDER header
    fp.writelines(hdr)
    rawmode = "F;32NF"  # 32-bit native floating point
    ImageFile._save(
        im, fp, [ImageFile._Tile("raw", (0, 0) + im.size, 0, (rawmode, 0, 1))]
    )
References makeSpiderHeader().
Referenced by _save_spider().
_save_spider()
None PIL.SpiderImagePlugin._save_spider (Image.Image im, IO[bytes] fp, str | bytes filename) protected
Definition at line 288 of file SpiderImagePlugin.py.
def _save_spider(im: Image.Image, fp: IO[bytes], filename: str | bytes) -> None:
    # get the filename extension and register it with Image
    filename_ext = os.path.splitext(filename)[1]
    ext = filename_ext.decode() if isinstance(filename_ext, bytes) else filename_ext
    Image.register_extension(SpiderImageFile.format, ext)
    _save(im, fp, filename)
# --------------------------------------------------------------------
References _save().
isInt()
int PIL.SpiderImagePlugin.isInt (Any f)
Definition at line 45 of file SpiderImagePlugin.py.
def isInt(f: Any) -> int:
    try:
        i = int(f)
        if f - i == 0:
            return 1
        else:
            return 0
    except (ValueError, OverflowError):
        return 0
Referenced by isSpiderHeader().
isSpiderHeader()
int PIL.SpiderImagePlugin.isSpiderHeader (tuple[float, ...] t)
Definition at line 65 of file SpiderImagePlugin.py.
def isSpiderHeader(t: tuple[float, ...]) -> int:
    h = (99,) + t  # add 1 value so can use spider header index start=1
    # header values 1,2,5,12,13,22,23 should be integers
    for i in [1, 2, 5, 12, 13, 22, 23]:
        if not isInt(h[i]):
            return 0
    # check iform
    iform = int(h[5])
    if iform not in iforms:
        return 0
    # check other header values
    labrec = int(h[13])  # no. records in file header
    labbyt = int(h[22])  # total no. of bytes in header
    lenbyt = int(h[23])  # record length in bytes
    if labbyt != (labrec * lenbyt):
        return 0
    # looks like a valid header
    return labbyt
References isInt().
Referenced by isSpiderImage().
isSpiderImage()
int PIL.SpiderImagePlugin.isSpiderImage (str filename)
Definition at line 85 of file SpiderImagePlugin.py.
def isSpiderImage(filename: str) -> int:
    with open(filename, "rb") as fp:
        f = fp.read(92)  # read 23 * 4 bytes
    t = struct.unpack(">23f", f)  # try big-endian first
    hdrlen = isSpiderHeader(t)
    if hdrlen == 0:
        t = struct.unpack("<23f", f)  # little-endian
        hdrlen = isSpiderHeader(t)
    return hdrlen
References isSpiderHeader().
Referenced by loadImageSeries().
loadImageSeries()
list[SpiderImageFile] | None PIL.SpiderImagePlugin.loadImageSeries (list[str] | None filelist = None)
create a list of :py:class:`~PIL.Image.Image` objects for use in a montage
Definition at line 214 of file SpiderImagePlugin.py.
def loadImageSeries(filelist: list[str] | None = None) -> list[SpiderImageFile] | None:
    """create a list of :py:class:`~PIL.Image.Image` objects for use in a montage"""
    if filelist is None or len(filelist) < 1:
        return None
    imglist = []
    for img in filelist:
        if not os.path.exists(img):
            print(f"unable to find {img}")
            continue
        try:
            with Image.open(img) as im:
                im = im.convert2byte()
        except Exception:
            if not isSpiderImage(img):
                print(f"{img} is not a Spider image file")
            continue
        im.info["filename"] = img
        imglist.append(im)
    return imglist
# --------------------------------------------------------------------
# For saving images in Spider format
References isSpiderImage().
makeSpiderHeader()
list[bytes] PIL.SpiderImagePlugin.makeSpiderHeader (Image.Image im)
Definition at line 240 of file SpiderImagePlugin.py.
def makeSpiderHeader(im: Image.Image) -> list[bytes]:
    nsam, nrow = im.size
    lenbyt = nsam * 4  # There are labrec records in the header
    labrec = int(1024 / lenbyt)
    if 1024 % lenbyt != 0:
        labrec += 1
    labbyt = labrec * lenbyt
    nvalues = int(labbyt / 4)
    if nvalues < 23:
        return []
    hdr = [0.0] * nvalues
    # NB these are Fortran indices
    hdr[1] = 1.0  # nslice (=1 for an image)
    hdr[2] = float(nrow)  # number of rows per slice
    hdr[3] = float(nrow)  # number of records in the image
    hdr[5] = 1.0  # iform for 2D image
    hdr[12] = float(nsam)  # number of pixels per line
    hdr[13] = float(labrec)  # number of records in file header
    hdr[22] = float(labbyt)  # total number of bytes in header
    hdr[23] = float(lenbyt)  # record length in bytes
    # adjust for Fortran indexing
    hdr = hdr[1:]
    hdr.append(0.0)
    # pack binary data into a string
    return [struct.pack("f", v) for v in hdr]
Referenced by _save().
Variable Documentation
end
PIL.SpiderImagePlugin.end
Definition at line 317 of file SpiderImagePlugin.py.
filename
PIL.SpiderImagePlugin.filename = sys.argv[1]
Definition at line 307 of file SpiderImagePlugin.py.
iforms
list PIL.SpiderImagePlugin.iforms = [1, 3, -11, -12, -21, -22]
Definition at line 56 of file SpiderImagePlugin.py.
im
PIL.SpiderImagePlugin.im = im.transpose(Image.Transpose.FLIP_LEFT_RIGHT)
Definition at line 324 of file SpiderImagePlugin.py.
outfile
PIL.SpiderImagePlugin.outfile = sys.argv[2]
Definition at line 321 of file SpiderImagePlugin.py.