Read&Watch: django.test.runner Namespace Reference
django.test.runner Namespace Reference
Classes
class DebugSQLTextTestResult
class DiscoverRunner
class DummyList
class ParallelTestSuite
class PDBDebugResult
class RemoteTestResult
class RemoteTestRunner
class Shuffler
Functions
get_max_test_processes ()
parallel_type (value)
_init_worker (counter, initial_settings=None, serialized_contents=None, process_setup=None, process_setup_args=None, debug_mode=None, used_aliases=None)
_run_subsuite (args)
_process_setup_stub (*args)
try_importing (label)
find_top_level (top_level)
_class_shuffle_key (cls)
shuffle_tests (tests, shuffler)
reorder_test_bin (tests, shuffler=None, reverse=False)
reorder_tests (tests, classes, reverse=False, shuffler=None)
partition_suite_by_case (suite)
test_match_tags (test, tags, exclude_tags)
filter_tests_by_tags (tests, tags, exclude_tags)
Variables
tblib = None
int _worker_id = 0
Function Documentation
_class_shuffle_key()
django.test.runner._class_shuffle_key (cls) protected
Definition at line 1129 of file runner.py.
def _class_shuffle_key(cls):
    return f"{cls.__module__}.{cls.__qualname__}"
_init_worker()
django.test.runner._init_worker (counter, initial_settings = None, serialized_contents = None, process_setup = None, process_setup_args = None, debug_mode = None, used_aliases = None) protected
Switch to databases dedicated to this worker.
This helper lives at module-level because of the multiprocessing module's
requirements.
Definition at line 402 of file runner.py.
):
    """
    Switch to databases dedicated to this worker.
    This helper lives at module-level because of the multiprocessing module's
    requirements.
    """
    global _worker_id
    with counter.get_lock():
        counter.value += 1
        _worker_id = counter.value
    start_method = multiprocessing.get_start_method()
    if start_method == "spawn":
        if process_setup and callable(process_setup):
            if process_setup_args is None:
                process_setup_args = ()
            process_setup(*process_setup_args)
        django.setup()
        setup_test_environment(debug=debug_mode)
    db_aliases = used_aliases if used_aliases is not None else connections
    for alias in db_aliases:
        connection = connections[alias]
        if start_method == "spawn":
            # Restore initial settings in spawned processes.
            connection.settings_dict.update(initial_settings[alias])
            if value := serialized_contents.get(alias):
                connection._test_serialized_contents = value
        connection.creation.setup_worker_connection(_worker_id)
References django.setup().
_process_setup_stub()
django.test.runner._process_setup_stub (* args) protected
Stub method to simplify run() implementation.
Definition at line 458 of file runner.py.
def _process_setup_stub(*args):
    """Stub method to simplify run() implementation."""
    pass
_run_subsuite()
django.test.runner._run_subsuite (args) protected
Run a suite of tests with a RemoteTestRunner and return a RemoteTestResult.
This helper lives at module-level and its arguments are wrapped in a tuple
because of the multiprocessing module's requirements.
Definition at line 445 of file runner.py.
def _run_subsuite(args):
    """
    Run a suite of tests with a RemoteTestRunner and return a RemoteTestResult.
    This helper lives at module-level and its arguments are wrapped in a tuple
    because of the multiprocessing module's requirements.
    """
    runner_class, subsuite_index, subsuite, failfast, buffer = args
    runner = runner_class(failfast=failfast, buffer=buffer)
    result = runner.run(subsuite)
    return subsuite_index, result.events
filter_tests_by_tags()
django.test.runner.filter_tests_by_tags (tests, tags, exclude_tags)
Return the matching tests as an iterator.
Definition at line 1234 of file runner.py.
def filter_tests_by_tags(tests, tags, exclude_tags):
    """Return the matching tests as an iterator."""
    return (test for test in tests if test_match_tags(test, tags, exclude_tags))
References test_match_tags().
Referenced by django.test.runner.DiscoverRunner.build_suite().
find_top_level()
django.test.runner.find_top_level (top_level)
Definition at line 1105 of file runner.py.
def find_top_level(top_level):
    # Try to be a bit smarter than unittest about finding the default top-level
    # for a given directory path, to avoid breaking relative imports.
    # (Unittest's default is to set top-level equal to the path, which means
    # relative imports will result in "Attempted relative import in
    # non-package.").
    # We'd be happy to skip this and require dotted module paths (which don't
    # cause this problem) instead of file paths (which do), but in the case of
    # a directory in the cwd, which would be equally valid if considered as a
    # top-level module or as a directory path, unittest unfortunately prefers
    # the latter.
    while True:
        init_py = os.path.join(top_level, "__init__.py")
        if not os.path.exists(init_py):
            break
        try_next = os.path.dirname(top_level)
        if try_next == top_level:
            # __init__.py all the way down? give up.
            break
        top_level = try_next
    return top_level
Referenced by django.test.runner.DiscoverRunner.load_tests_for_label().
get_max_test_processes()
django.test.runner.get_max_test_processes ()
The maximum number of test processes when using the --parallel option.
Definition at line 373 of file runner.py.
def get_max_test_processes():
    """
    The maximum number of test processes when using the --parallel option.
    """
    # The current implementation of the parallel test runner requires
    # multiprocessing to start subprocesses with fork() or spawn().
    if multiprocessing.get_start_method() not in {"fork", "spawn"}:
        return 1
    try:
        return int(os.environ["DJANGO_TEST_PROCESSES"])
    except KeyError:
        return multiprocessing.cpu_count()
parallel_type()
django.test.runner.parallel_type (value)
Parse value passed to the --parallel option.
Definition at line 387 of file runner.py.
def parallel_type(value):
    """Parse value passed to the --parallel option."""
    if value == "auto":
        return value
    try:
        return int(value)
    except ValueError:
        raise argparse.ArgumentTypeError(
            f"{value!r} is not an integer or the string 'auto'"
        )
partition_suite_by_case()
django.test.runner.partition_suite_by_case (suite)
Partition a test suite by TestCase, preserving the order of tests.
Definition at line 1211 of file runner.py.
def partition_suite_by_case(suite):
    """Partition a test suite by TestCase, preserving the order of tests."""
    suite_class = type(suite)
    all_tests = iter_test_cases(suite)
    return [suite_class(tests) for _, tests in itertools.groupby(all_tests, type)]
Referenced by django.test.runner.DiscoverRunner.build_suite().
reorder_test_bin()
django.test.runner.reorder_test_bin (tests, shuffler = None, reverse = False)
Return an iterator that reorders the given tests, keeping tests next to
other tests of their class.
`tests` should be an iterable of tests that supports reversed().
Definition at line 1152 of file runner.py.
def reorder_test_bin(tests, shuffler=None, reverse=False):
    """
    Return an iterator that reorders the given tests, keeping tests next to
    other tests of their class.
    `tests` should be an iterable of tests that supports reversed().
    """
    if shuffler is None:
        if reverse:
            return reversed(tests)
        # The function must return an iterator.
        return iter(tests)
    tests = shuffle_tests(tests, shuffler)
    if not reverse:
        return tests
    # Arguments to reversed() must be reversible.
    return reversed(list(tests))
References shuffle_tests().
Referenced by reorder_tests().
reorder_tests()
django.test.runner.reorder_tests (tests, classes, reverse = False, shuffler = None)
Reorder an iterable of tests, grouping by the given TestCase classes.
This function also removes any duplicates and reorders so that tests of the
same type are consecutive.
The result is returned as an iterator. `classes` is a sequence of types.
Tests that are instances of `classes[0]` are grouped first, followed by
instances of `classes[1]`, etc. Tests that are not instances of any of the
classes are grouped last.
If `reverse` is True, the tests within each `classes` group are reversed,
but without reversing the order of `classes` itself.
The `shuffler` argument is an optional instance of this module's `Shuffler`
class. If provided, tests will be shuffled within each `classes` group, but
keeping tests with other tests of their TestCase class. Reversing is
applied after shuffling to allow reversing the same random order.
Definition at line 1172 of file runner.py.
def reorder_tests(tests, classes, reverse=False, shuffler=None):
    """
    Reorder an iterable of tests, grouping by the given TestCase classes.
    This function also removes any duplicates and reorders so that tests of the
    same type are consecutive.
    The result is returned as an iterator. `classes` is a sequence of types.
    Tests that are instances of `classes[0]` are grouped first, followed by
    instances of `classes[1]`, etc. Tests that are not instances of any of the
    classes are grouped last.
    If `reverse` is True, the tests within each `classes` group are reversed,
    but without reversing the order of `classes` itself.
    The `shuffler` argument is an optional instance of this module's `Shuffler`
    class. If provided, tests will be shuffled within each `classes` group, but
    keeping tests with other tests of their TestCase class. Reversing is
    applied after shuffling to allow reversing the same random order.
    """
    # Each bin maps TestCase class to OrderedSet of tests. This permits tests
    # to be grouped by TestCase class even if provided non-consecutively.
    bins = [defaultdict(OrderedSet) for i in range(len(classes) + 1)]
    *class_bins, last_bin = bins
    for test in tests:
        for test_bin, test_class in zip(class_bins, classes):
            if isinstance(test, test_class):
                break
        else:
            test_bin = last_bin
        test_bin[type(test)].add(test)
    for test_bin in bins:
        # Call list() since reorder_test_bin()'s input must support reversed().
        tests = list(itertools.chain.from_iterable(test_bin.values()))
        yield from reorder_test_bin(tests, shuffler=shuffler, reverse=reverse)
References reorder_test_bin().
Referenced by django.test.runner.DiscoverRunner.build_suite().
shuffle_tests()
django.test.runner.shuffle_tests (tests, shuffler)
Return an iterator over the given tests in a shuffled order, keeping tests
next to other tests of their class.
`tests` should be an iterable of tests.
Definition at line 1133 of file runner.py.
def shuffle_tests(tests, shuffler):
    """
    Return an iterator over the given tests in a shuffled order, keeping tests
    next to other tests of their class.
    `tests` should be an iterable of tests.
    """
    tests_by_type = {}
    for _, class_tests in itertools.groupby(tests, type):
        class_tests = list(class_tests)
        test_type = type(class_tests[0])
        class_tests = shuffler.shuffle(class_tests, key=lambda test: test.id())
        tests_by_type[test_type] = class_tests
    classes = shuffler.shuffle(tests_by_type, key=_class_shuffle_key)
    return itertools.chain(*(tests_by_type[cls] for cls in classes))
Referenced by reorder_test_bin().
test_match_tags()
django.test.runner.test_match_tags (test, tags, exclude_tags)
Definition at line 1218 of file runner.py.
def test_match_tags(test, tags, exclude_tags):
    if isinstance(test, unittest.loader._FailedTest):
        # Tests that couldn't load always match to prevent tests from falsely
        # passing due e.g. to syntax errors.
        return True
    test_tags = set(getattr(test, "tags", []))
    test_fn_name = getattr(test, "_testMethodName", str(test))
    if hasattr(test, test_fn_name):
        test_fn = getattr(test, test_fn_name)
        test_fn_tags = list(getattr(test_fn, "tags", []))
        test_tags = test_tags.union(test_fn_tags)
    if tags and test_tags.isdisjoint(tags):
        return False
    return test_tags.isdisjoint(exclude_tags)
Referenced by filter_tests_by_tags().
try_importing()
django.test.runner.try_importing (label)
Try importing a test label, and return (is_importable, is_package).
Relative labels like "." and ".." are seen as directories.
Definition at line 1091 of file runner.py.
def try_importing(label):
    """
    Try importing a test label, and return (is_importable, is_package).
    Relative labels like "." and ".." are seen as directories.
    """
    try:
        mod = import_module(label)
    except (ImportError, TypeError):
        return (False, False)
    return (True, hasattr(mod, "__path__"))
Referenced by django.test.runner.DiscoverRunner.load_tests_for_label().
Variable Documentation
_worker_id
int django.test.runner._worker_id = 0 protected
Definition at line 399 of file runner.py.
tblib
django.test.runner.tblib = None
Definition at line 42 of file runner.py.