Read&Watch: PIL.GimpGradientFile Namespace Reference
PIL.GimpGradientFile Namespace Reference
Classes
class GimpGradientFile
class GradientFile
Functions
float linear (float middle, float pos)
float curved (float middle, float pos)
float sine (float middle, float pos)
float sphere_increasing (float middle, float pos)
float sphere_decreasing (float middle, float pos)
Variables
int EPSILON = 1e-10
list SEGMENTS = [linear, curved, sine, sphere_increasing, sphere_decreasing]
Detailed Description
Stuff to translate curve segments to palette values (derived from
the corresponding code in GIMP, written by Federico Mena Quintero.
See the GIMP distribution for more information.)
Function Documentation
curved()
float PIL.GimpGradientFile.curved (float middle, float pos)
Definition at line 47 of file GimpGradientFile.py.
def curved(middle: float, pos: float) -> float:
    return pos ** (log(0.5) / log(max(middle, EPSILON)))
linear()
float PIL.GimpGradientFile.linear (float middle, float pos)
Definition at line 32 of file GimpGradientFile.py.
def linear(middle: float, pos: float) -> float:
    if pos <= middle:
        if middle < EPSILON:
            return 0.0
        else:
            return 0.5 * pos / middle
    else:
        pos = pos - middle
        middle = 1.0 - middle
        if middle < EPSILON:
            return 1.0
        else:
            return 0.5 + 0.5 * pos / middle
Referenced by sine(), sphere_decreasing(), and sphere_increasing().
sine()
float PIL.GimpGradientFile.sine (float middle, float pos)
Definition at line 51 of file GimpGradientFile.py.
def sine(middle: float, pos: float) -> float:
    return (sin((-pi / 2.0) + pi * linear(middle, pos)) + 1.0) / 2.0
References linear().
sphere_decreasing()
float PIL.GimpGradientFile.sphere_decreasing (float middle, float pos)
Definition at line 59 of file GimpGradientFile.py.
def sphere_decreasing(middle: float, pos: float) -> float:
    return 1.0 - sqrt(1.0 - linear(middle, pos) ** 2)
References linear().
sphere_increasing()
float PIL.GimpGradientFile.sphere_increasing (float middle, float pos)
Definition at line 55 of file GimpGradientFile.py.
def sphere_increasing(middle: float, pos: float) -> float:
    return sqrt(1.0 - (linear(middle, pos) - 1.0) ** 2)
References linear().
Variable Documentation
EPSILON
int PIL.GimpGradientFile.EPSILON = 1e-10
Definition at line 28 of file GimpGradientFile.py.
SEGMENTS
list PIL.GimpGradientFile.SEGMENTS = [linear, curved, sine, sphere_increasing, sphere_decreasing]
Definition at line 63 of file GimpGradientFile.py.