Read&Watch: django.core.mail.message Namespace Reference
django.core.mail.message Namespace Reference
Classes
class BadHeaderError
class EmailMessage
class EmailMultiAlternatives
class MIMEMixin
class SafeMIMEMessage
class SafeMIMEMultipart
class SafeMIMEText
Functions
forbid_multi_line_headers (name, val, encoding)
sanitize_address (addr, encoding)
Variables
utf8_charset = Charset.Charset("utf-8")
body_encoding
utf8_charset_qp = Charset.Charset("utf-8")
str DEFAULT_ATTACHMENT_MIME_TYPE = "application/octet-stream"
int RFC5322_EMAIL_LINE_LENGTH_LIMIT = 998
dict ADDRESS_HEADERS
Function Documentation
forbid_multi_line_headers()
django.core.mail.message.forbid_multi_line_headers (name, val, encoding)
Forbid multi-line headers to prevent header injection.
Definition at line 55 of file message.py.
def forbid_multi_line_headers(name, val, encoding):
    """Forbid multi-line headers to prevent header injection."""
    encoding = encoding or settings.DEFAULT_CHARSET
    val = str(val)  # val may be lazy
    if "\n" in val or "\r" in val:
        raise BadHeaderError(
            "Header values can't contain newlines (got %r for header %r)" % (val, name)
        )
    try:
        val.encode("ascii")
    except UnicodeEncodeError:
        if name.lower() in ADDRESS_HEADERS:
            val = ", ".join(
                sanitize_address(addr, encoding) for addr in getaddresses((val,))
            )
        else:
            val = Header(val, encoding).encode()
    else:
        if name.lower() == "subject":
            val = Header(val).encode()
    return name, val
References sanitize_address().
Referenced by django.core.mail.message.SafeMIMEMessage.__setitem__(), django.core.mail.message.SafeMIMEMultipart.__setitem__(), and django.core.mail.message.SafeMIMEText.__setitem__().
sanitize_address()
django.core.mail.message.sanitize_address (addr, encoding)
Format a pair of (name, address) or an email address string.
Definition at line 78 of file message.py.
def sanitize_address(addr, encoding):
    """
    Format a pair of (name, address) or an email address string.
    """
    address = None
    if not isinstance(addr, tuple):
        addr = force_str(addr)
        try:
            token, rest = parser.get_mailbox(addr)
        except (HeaderParseError, ValueError, IndexError):
            raise ValueError('Invalid address "%s"' % addr)
        else:
            if rest:
                # The entire email address must be parsed.
                raise ValueError(
                    'Invalid address; only %s could be parsed from "%s"' % (token, addr)
                )
            nm = token.display_name or ""
            localpart = token.local_part
            domain = token.domain or ""
    else:
        nm, address = addr
        if "@" not in address:
            raise ValueError(f'Invalid address "{address}"')
        localpart, domain = address.rsplit("@", 1)
    address_parts = nm + localpart + domain
    if "\n" in address_parts or "\r" in address_parts:
        raise ValueError("Invalid address; address parts cannot contain newlines.")
    # Avoid UTF-8 encode, if it's possible.
    try:
        nm.encode("ascii")
        nm = Header(nm).encode()
    except UnicodeEncodeError:
        nm = Header(nm, encoding).encode()
    try:
        localpart.encode("ascii")
    except UnicodeEncodeError:
        localpart = Header(localpart, encoding).encode()
    domain = punycode(domain)
    parsed_address = Address(username=localpart, domain=domain)
    return formataddr((nm, parsed_address.addr_spec))
Referenced by forbid_multi_line_headers().
Variable Documentation
ADDRESS_HEADERS
dict django.core.mail.message.ADDRESS_HEADERS
Initial value:
=  {
    "from",
    "sender",
    "reply-to",
    "to",
    "cc",
    "bcc",
    "resent-from",
    "resent-sender",
    "resent-to",
    "resent-cc",
    "resent-bcc",
}
Definition at line 40 of file message.py.
body_encoding
django.core.mail.message.body_encoding
Definition at line 24 of file message.py.
DEFAULT_ATTACHMENT_MIME_TYPE
str django.core.mail.message.DEFAULT_ATTACHMENT_MIME_TYPE = "application/octet-stream"
Definition at line 30 of file message.py.
RFC5322_EMAIL_LINE_LENGTH_LIMIT
int django.core.mail.message.RFC5322_EMAIL_LINE_LENGTH_LIMIT = 998
Definition at line 32 of file message.py.
utf8_charset
django.core.mail.message.utf8_charset = Charset.Charset("utf-8")
Definition at line 23 of file message.py.
utf8_charset_qp
django.core.mail.message.utf8_charset_qp = Charset.Charset("utf-8")
Definition at line 25 of file message.py.