Read&Watch: django.core.serializers Namespace Reference
django.core.serializers Namespace Reference
Namespaces
namespace base
namespace json
namespace jsonl
namespace python
namespace pyyaml
namespace xml_serializer
Classes
class BadSerializer
Functions
register_serializer (format, serializer_module, serializers=None)
unregister_serializer (format)
get_serializer (format)
get_serializer_formats ()
get_public_serializer_formats ()
get_deserializer (format)
serialize (format, queryset, **options)
deserialize (format, stream_or_string, **options)
_load_serializers ()
sort_dependencies (app_list, allow_cycles=False)
Variables
dict BUILTIN_SERIALIZERS
dict _serializers = {}
Detailed Description
Interfaces for serializing Django objects.
Usage::
    from django.core import serializers
    json = serializers.serialize("json", some_queryset)
    objects = list(serializers.deserialize("json", json))
To add your own serializers, use the SERIALIZATION_MODULES setting::
    SERIALIZATION_MODULES = {
        "csv": "path.to.csv.serializer",
        "txt": "path.to.txt.serializer",
    }
Function Documentation
_load_serializers()
django.core.serializers._load_serializers () protected
Register built-in and settings-defined serializers. This is done lazily so
that user code has a chance to (e.g.) set up custom settings without
needing to be careful of import order.
Definition at line 149 of file __init__.py.
def _load_serializers():
    """
    Register built-in and settings-defined serializers. This is done lazily so
    that user code has a chance to (e.g.) set up custom settings without
    needing to be careful of import order.
    """
    global _serializers
    serializers = {}
    for format in BUILTIN_SERIALIZERS:
        register_serializer(format, BUILTIN_SERIALIZERS[format], serializers)
    if hasattr(settings, "SERIALIZATION_MODULES"):
        for format in settings.SERIALIZATION_MODULES:
            register_serializer(
                format, settings.SERIALIZATION_MODULES[format], serializers
            )
    _serializers = serializers
References register_serializer().
Referenced by get_deserializer(), get_public_serializer_formats(), get_serializer(), get_serializer_formats(), register_serializer(), and unregister_serializer().
deserialize()
django.core.serializers.deserialize (format, stream_or_string, ** options)
Deserialize a stream or a string. Return an iterator that yields ``(obj,
m2m_relation_dict)``, where ``obj`` is an instantiated -- but *unsaved* --
object, and ``m2m_relation_dict`` is a dictionary of ``{m2m_field_name :
list_of_related_objects}``.
Definition at line 138 of file __init__.py.
def deserialize(format, stream_or_string, **options):
    """
    Deserialize a stream or a string. Return an iterator that yields ``(obj,
    m2m_relation_dict)``, where ``obj`` is an instantiated -- but *unsaved* --
    object, and ``m2m_relation_dict`` is a dictionary of ``{m2m_field_name :
    list_of_related_objects}``.
    """
    d = get_deserializer(format)
    return d(stream_or_string, **options)
References get_deserializer().
get_deserializer()
django.core.serializers.get_deserializer (format)
Definition at line 120 of file __init__.py.
def get_deserializer(format):
    if not _serializers:
        _load_serializers()
    if format not in _serializers:
        raise SerializerDoesNotExist(format)
    return _serializers[format].Deserializer
References _load_serializers().
Referenced by deserialize().
get_public_serializer_formats()
django.core.serializers.get_public_serializer_formats ()
Definition at line 114 of file __init__.py.
def get_public_serializer_formats():
    if not _serializers:
        _load_serializers()
    return [k for k, v in _serializers.items() if not v.Serializer.internal_use_only]
References _load_serializers().
get_serializer()
django.core.serializers.get_serializer (format)
Definition at line 100 of file __init__.py.
def get_serializer(format):
    if not _serializers:
        _load_serializers()
    if format not in _serializers:
        raise SerializerDoesNotExist(format)
    return _serializers[format].Serializer
References _load_serializers().
Referenced by serialize().
get_serializer_formats()
django.core.serializers.get_serializer_formats ()
Definition at line 108 of file __init__.py.
def get_serializer_formats():
    if not _serializers:
        _load_serializers()
    return list(_serializers)
References _load_serializers().
register_serializer()
django.core.serializers.register_serializer (format, serializer_module, serializers = None)
Register a new serializer.
``serializer_module`` should be the fully qualified module name
for the serializer.
If ``serializers`` is provided, the registration will be added
to the provided dictionary.
If ``serializers`` is not provided, the registration will be made
directly into the global register of serializers. Adding serializers
directly is not a thread-safe operation.
Definition at line 55 of file __init__.py.
def register_serializer(format, serializer_module, serializers=None):
    """Register a new serializer.
    ``serializer_module`` should be the fully qualified module name
    for the serializer.
    If ``serializers`` is provided, the registration will be added
    to the provided dictionary.
    If ``serializers`` is not provided, the registration will be made
    directly into the global register of serializers. Adding serializers
    directly is not a thread-safe operation.
    """
    if serializers is None and not _serializers:
        _load_serializers()
    try:
        module = importlib.import_module(serializer_module)
    except ImportError as exc:
        bad_serializer = BadSerializer(exc)
        module = type(
            "BadSerializerModule",
            (),
            {
                "Deserializer": bad_serializer,
                "Serializer": bad_serializer,
            },
        )
    if serializers is None:
        _serializers[format] = module
    else:
        serializers[format] = module
References _load_serializers().
Referenced by _load_serializers().
serialize()
django.core.serializers.serialize (format, queryset, ** options)
Serialize a queryset (or any iterator that returns database objects) using
a certain serializer.
Definition at line 128 of file __init__.py.
def serialize(format, queryset, **options):
    """
    Serialize a queryset (or any iterator that returns database objects) using
    a certain serializer.
    """
    s = get_serializer(format)()
    s.serialize(queryset, **options)
    return s.getvalue()
References get_serializer().
sort_dependencies()
django.core.serializers.sort_dependencies (app_list, allow_cycles = False)
Sort a list of (app_config, models) pairs into a single list of models.
The single list of models is sorted so that any model with a natural key
is serialized before a normal model, and any model with a natural key
dependency has it's dependencies serialized first.
If allow_cycles is True, return the best-effort ordering that will respect
most of dependencies but ignore some of them to break the cycles.
Definition at line 167 of file __init__.py.
def sort_dependencies(app_list, allow_cycles=False):
    """Sort a list of (app_config, models) pairs into a single list of models.
    The single list of models is sorted so that any model with a natural key
    is serialized before a normal model, and any model with a natural key
    dependency has it's dependencies serialized first.
    If allow_cycles is True, return the best-effort ordering that will respect
    most of dependencies but ignore some of them to break the cycles.
    """
    # Process the list of models, and get the list of dependencies
    model_dependencies = []
    models = set()
    for app_config, model_list in app_list:
        if model_list is None:
            model_list = app_config.get_models()
        for model in model_list:
            models.add(model)
            # Add any explicitly defined dependencies
            if hasattr(model, "natural_key"):
                deps = getattr(model.natural_key, "dependencies", [])
                if deps:
                    deps = [apps.get_model(dep) for dep in deps]
            else:
                deps = []
            # Now add a dependency for any FK relation with a model that
            # defines a natural key
            for field in model._meta.fields:
                if field.remote_field:
                    rel_model = field.remote_field.model
                    if hasattr(rel_model, "natural_key") and rel_model != model:
                        deps.append(rel_model)
            # Also add a dependency for any simple M2M relation with a model
            # that defines a natural key.  M2M relations with explicit through
            # models don't count as dependencies.
            for field in model._meta.many_to_many:
                if field.remote_field.through._meta.auto_created:
                    rel_model = field.remote_field.model
                    if hasattr(rel_model, "natural_key") and rel_model != model:
                        deps.append(rel_model)
            model_dependencies.append((model, deps))
    model_dependencies.reverse()
    # Now sort the models to ensure that dependencies are met. This
    # is done by repeatedly iterating over the input list of models.
    # If all the dependencies of a given model are in the final list,
    # that model is promoted to the end of the final list. This process
    # continues until the input list is empty, or we do a full iteration
    # over the input models without promoting a model to the final list.
    # If we do a full iteration without a promotion, that means there are
    # circular dependencies in the list.
    model_list = []
    while model_dependencies:
        skipped = []
        changed = False
        while model_dependencies:
            model, deps = model_dependencies.pop()
            # If all of the models in the dependency list are either already
            # on the final model list, or not on the original serialization list,
            # then we've found another model with all it's dependencies satisfied.
            if all(d not in models or d in model_list for d in deps):
                model_list.append(model)
                changed = True
            else:
                skipped.append((model, deps))
        if not changed:
            if allow_cycles:
                # If cycles are allowed, add the last skipped model and ignore
                # its dependencies. This could be improved by some graph
                # analysis to ignore as few dependencies as possible.
                model, _ = skipped.pop()
                model_list.append(model)
            else:
                raise RuntimeError(
                    "Can't resolve dependencies for %s in serialized app list."
                    % ", ".join(
                        model._meta.label
                        for model, deps in sorted(
                            skipped, key=lambda obj: obj[0].__name__
                        )
                    ),
                )
        model_dependencies = skipped
    return model_list
unregister_serializer()
django.core.serializers.unregister_serializer (format)
Definition at line 91 of file __init__.py.
def unregister_serializer(format):
    "Unregister a given serializer. This is not a thread-safe operation."
    if not _serializers:
        _load_serializers()
    if format not in _serializers:
        raise SerializerDoesNotExist(format)
    del _serializers[format]
References _load_serializers().
Variable Documentation
_serializers
dict django.core.serializers._serializers = {} protected
Definition at line 34 of file __init__.py.
BUILTIN_SERIALIZERS
dict django.core.serializers.BUILTIN_SERIALIZERS
Initial value:
=  {
    "xml": "django.core.serializers.xml_serializer",
    "python": "django.core.serializers.python",
    "json": "django.core.serializers.json",
    "yaml": "django.core.serializers.pyyaml",
    "jsonl": "django.core.serializers.jsonl",
}
Definition at line 26 of file __init__.py.