Read&Watch: django.contrib.gis.gdal.prototypes.errcheck Namespace Reference
django.contrib.gis.gdal.prototypes.errcheck Namespace Reference
Functions
arg_byref (args, offset=-1)
ptr_byref (args, offset=-1)
check_const_string (result, func, cargs, offset=None, cpl=False)
check_string (result, func, cargs, offset=-1, str_result=False)
check_envelope (result, func, cargs, offset=-1)
check_geom (result, func, cargs)
check_geom_offset (result, func, cargs, offset=-1)
check_srs (result, func, cargs)
check_arg_errcode (result, func, cargs, cpl=False)
check_errcode (result, func, cargs, cpl=False)
check_pointer (result, func, cargs)
check_str_arg (result, func, cargs)
Detailed Description
 This module houses the error-checking routines used by the GDAL
 ctypes prototypes.
Function Documentation
arg_byref()
django.contrib.gis.gdal.prototypes.errcheck.arg_byref (args, offset = -1)
Definition at line 14 of file errcheck.py.
def arg_byref(args, offset=-1):
    "Return the pointer argument's by-reference value."
    return args[offset]._obj.value
Referenced by check_arg_errcode().
check_arg_errcode()
django.contrib.gis.gdal.prototypes.errcheck.check_arg_errcode (result, func, cargs, cpl = False)
The error code is returned in the last argument, by reference.
Check its value with `check_err` before returning the result.
Definition at line 108 of file errcheck.py.
def check_arg_errcode(result, func, cargs, cpl=False):
    """
    The error code is returned in the last argument, by reference.
    Check its value with `check_err` before returning the result.
    """
    check_err(arg_byref(cargs), cpl=cpl)
    return result
References arg_byref().
check_const_string()
django.contrib.gis.gdal.prototypes.errcheck.check_const_string (result, func, cargs, offset = None, cpl = False)
Similar functionality to `check_string`, but does not free the pointer.
Definition at line 25 of file errcheck.py.
def check_const_string(result, func, cargs, offset=None, cpl=False):
    """
    Similar functionality to `check_string`, but does not free the pointer.
    """
    if offset:
        check_err(result, cpl=cpl)
        ptr = ptr_byref(cargs, offset)
        return ptr.value
    else:
        return result
References ptr_byref().
check_envelope()
django.contrib.gis.gdal.prototypes.errcheck.check_envelope (result, func, cargs, offset = -1)
Definition at line 70 of file errcheck.py.
def check_envelope(result, func, cargs, offset=-1):
    "Check a function that returns an OGR Envelope by reference."
    return ptr_byref(cargs, offset)
# ### Geometry error-checking routines ###
References ptr_byref().
check_errcode()
django.contrib.gis.gdal.prototypes.errcheck.check_errcode (result, func, cargs, cpl = False)
Check the error code returned (c_int).
Definition at line 117 of file errcheck.py.
def check_errcode(result, func, cargs, cpl=False):
    """
    Check the error code returned (c_int).
    """
    check_err(result, cpl=cpl)
check_geom()
django.contrib.gis.gdal.prototypes.errcheck.check_geom (result, func, cargs)
Definition at line 76 of file errcheck.py.
def check_geom(result, func, cargs):
    "Check a function that returns a geometry."
    # OGR_G_Clone may return an integer, even though the
    # restype is set to c_void_p
    if isinstance(result, int):
        result = c_void_p(result)
    if not result:
        raise GDALException(
            'Invalid geometry pointer returned from "%s".' % func.__name__
        )
    return result
Referenced by check_geom_offset().
check_geom_offset()
django.contrib.gis.gdal.prototypes.errcheck.check_geom_offset (result, func, cargs, offset = -1)
Definition at line 89 of file errcheck.py.
def check_geom_offset(result, func, cargs, offset=-1):
    "Check the geometry at the given offset in the C parameter list."
    check_err(result)
    geom = ptr_byref(cargs, offset=offset)
    return check_geom(geom, func, cargs)
# ### Spatial Reference error-checking routines ###
References check_geom(), and ptr_byref().
check_pointer()
django.contrib.gis.gdal.prototypes.errcheck.check_pointer (result, func, cargs)
Definition at line 124 of file errcheck.py.
def check_pointer(result, func, cargs):
    "Make sure the result pointer is valid."
    if isinstance(result, int):
        result = c_void_p(result)
    if result:
        return result
    else:
        raise GDALException('Invalid pointer returned from "%s"' % func.__name__)
check_srs()
django.contrib.gis.gdal.prototypes.errcheck.check_srs (result, func, cargs)
Definition at line 97 of file errcheck.py.
def check_srs(result, func, cargs):
    if isinstance(result, int):
        result = c_void_p(result)
    if not result:
        raise SRSException(
            'Invalid spatial reference pointer returned from "%s".' % func.__name__
        )
    return result
# ### Other error-checking routines ###
check_str_arg()
django.contrib.gis.gdal.prototypes.errcheck.check_str_arg (result, func, cargs)
This is for the OSRGet[Angular|Linear]Units functions, which
require that the returned string pointer not be freed.  This
returns both the double and string values.
Definition at line 134 of file errcheck.py.
def check_str_arg(result, func, cargs):
    """
    This is for the OSRGet[Angular|Linear]Units functions, which
    require that the returned string pointer not be freed.  This
    returns both the double and string values.
    """
    dbl = result
    ptr = cargs[-1]._obj
    return dbl, ptr.value.decode()
check_string()
django.contrib.gis.gdal.prototypes.errcheck.check_string (result, func, cargs, offset = -1, str_result = False)
Check the string output returned from the given function, and free
the string pointer allocated by OGR.  The `str_result` keyword
may be used when the result is the string pointer, otherwise
the OGR error code is assumed.  The `offset` keyword may be used
to extract the string pointer passed in by-reference at the given
slice offset in the function arguments.
Definition at line 37 of file errcheck.py.
def check_string(result, func, cargs, offset=-1, str_result=False):
    """
    Check the string output returned from the given function, and free
    the string pointer allocated by OGR.  The `str_result` keyword
    may be used when the result is the string pointer, otherwise
    the OGR error code is assumed.  The `offset` keyword may be used
    to extract the string pointer passed in by-reference at the given
    slice offset in the function arguments.
    """
    if str_result:
        # For routines that return a string.
        ptr = result
        if not ptr:
            s = None
        else:
            s = string_at(result)
    else:
        # Error-code return specified.
        check_err(result)
        ptr = ptr_byref(cargs, offset)
        # Getting the string value
        s = ptr.value
    # Correctly freeing the allocated memory behind GDAL pointer
    # with the VSIFree routine.
    if ptr:
        lgdal.VSIFree(ptr)
    return s
# ### DataSource, Layer error-checking ###
# ### Envelope checking ###
References ptr_byref().
ptr_byref()
django.contrib.gis.gdal.prototypes.errcheck.ptr_byref (args, offset = -1)
Definition at line 19 of file errcheck.py.
def ptr_byref(args, offset=-1):
    "Return the pointer argument passed in by-reference."
    return args[offset]._obj
# ### String checking Routines ###
Referenced by check_const_string(), check_envelope(), check_geom_offset(), and check_string().