Read&Watch: pip._vendor.cachecontrol._cmd Namespace Reference
pip._vendor.cachecontrol._cmd Namespace Reference
Functions
None setup_logging ()
requests.Session get_session ()
Namespace get_args ()
None main ()
Function Documentation
get_args()
Namespace pip._vendor.cachecontrol._cmd.get_args ()
Definition at line 40 of file _cmd.py.
def get_args() -> Namespace:
    parser = ArgumentParser()
    parser.add_argument("url", help="The URL to try and cache")
    return parser.parse_args()
Referenced by main().
get_session()
requests.Session pip._vendor.cachecontrol._cmd.get_session ()
Definition at line 28 of file _cmd.py.
def get_session() -> requests.Session:
    adapter = CacheControlAdapter(
        DictCache(), cache_etags=True, serializer=None, heuristic=None
    )
    sess = requests.Session()
    sess.mount("http://", adapter)
    sess.mount("https://", adapter)
    sess.cache_controller = adapter.controller  # type: ignore[attr-defined]
    return sess
Referenced by main().
main()
None pip._vendor.cachecontrol._cmd.main ()
Definition at line 46 of file _cmd.py.
def main() -> None:
    args = get_args()
    sess = get_session()
    # Make a request to get a response
    resp = sess.get(args.url)
    # Turn on logging
    setup_logging()
    # try setting the cache
    cache_controller: CacheController = (
        sess.cache_controller  # type: ignore[attr-defined]
    )
    cache_controller.cache_response(resp.request, resp.raw)
    # Now try to get it
    if cache_controller.cached_request(resp.request):
        print("Cached!")
    else:
        print("Not cached :(")
References get_args(), get_session(), main(), and setup_logging().
Referenced by main().
setup_logging()
None pip._vendor.cachecontrol._cmd.setup_logging ()
Definition at line 22 of file _cmd.py.
def setup_logging() -> None:
    logger.setLevel(logging.DEBUG)
    handler = logging.StreamHandler()
    logger.addHandler(handler)
Referenced by main().