Read&Watch: pip._internal.operations.build.wheel_legacy Namespace Reference
pip._internal.operations.build.wheel_legacy Namespace Reference
Functions
str format_command_result (List[str] command_args, str command_output)
Optional[str] get_legacy_build_wheel_path (List[str] names, str temp_dir, str name, List[str] command_args, str command_output)
Optional[str] build_wheel_legacy (str name, str setup_py_path, str source_dir, List[str] global_options, List[str] build_options, str tempd)
Variables
logger = logging.getLogger(__name__)
Function Documentation
build_wheel_legacy()
Optional[str] pip._internal.operations.build.wheel_legacy.build_wheel_legacy (str name, str setup_py_path, str source_dir, List[str] global_options, List[str] build_options, str tempd)
Build one unpacked package using the "legacy" build process.
Returns path to wheel if successfully built. Otherwise, returns None.
Definition at line 59 of file wheel_legacy.py.
) -> Optional[str]:
    """Build one unpacked package using the "legacy" build process.
    Returns path to wheel if successfully built. Otherwise, returns None.
    """
    wheel_args = make_setuptools_bdist_wheel_args(
        setup_py_path,
        global_options=global_options,
        build_options=build_options,
        destination_dir=tempd,
    )
    spin_message = f"Building wheel for {name} (setup.py)"
    with open_spinner(spin_message) as spinner:
        logger.debug("Destination directory: %s", tempd)
        try:
            output = call_subprocess(
                wheel_args,
                command_desc="python setup.py bdist_wheel",
                cwd=source_dir,
                spinner=spinner,
            )
        except Exception:
            spinner.finish("error")
            logger.error("Failed building wheel for %s", name)
            return None
        names = os.listdir(tempd)
        wheel_path = get_legacy_build_wheel_path(
            names=names,
            temp_dir=tempd,
            name=name,
            command_args=wheel_args,
            command_output=output,
        )
        return wheel_path
References get_legacy_build_wheel_path().
format_command_result()
str pip._internal.operations.build.wheel_legacy.format_command_result (List[str] command_args, str command_output)
Format command information for logging.
Definition at line 12 of file wheel_legacy.py.
) -> str:
    """Format command information for logging."""
    command_desc = format_command_args(command_args)
    text = f"Command arguments: {command_desc}\n"
    if not command_output:
        text += "Command output: None"
    elif logger.getEffectiveLevel() > logging.DEBUG:
        text += "Command output: [use --verbose to show]"
    else:
        if not command_output.endswith("\n"):
            command_output += "\n"
        text += f"Command output:\n{command_output}"
    return text
Referenced by get_legacy_build_wheel_path().
get_legacy_build_wheel_path()
Optional[str] pip._internal.operations.build.wheel_legacy.get_legacy_build_wheel_path (List[str] names, str temp_dir, str name, List[str] command_args, str command_output)
Return the path to the wheel in the temporary build directory.
Definition at line 32 of file wheel_legacy.py.
) -> Optional[str]:
    """Return the path to the wheel in the temporary build directory."""
    # Sort for determinism.
    names = sorted(names)
    if not names:
        msg = f"Legacy build of wheel for {name!r} created no files.\n"
        msg += format_command_result(command_args, command_output)
        logger.warning(msg)
        return None
    if len(names) > 1:
        msg = (
            f"Legacy build of wheel for {name!r} created more than one file.\n"
            f"Filenames (choosing first): {names}\n"
        )
        msg += format_command_result(command_args, command_output)
        logger.warning(msg)
    return os.path.join(temp_dir, names[0])
References format_command_result().
Referenced by build_wheel_legacy().
Variable Documentation
logger
pip._internal.operations.build.wheel_legacy.logger = logging.getLogger(__name__)
Definition at line 9 of file wheel_legacy.py.