Read&Watch: pip._vendor.truststore._api Namespace Reference
pip._vendor.truststore._api Namespace Reference
Classes
class SSLContext
Functions
None inject_into_ssl ()
None extract_from_ssl ()
list[bytes] _get_unverified_chain_bytes (ssl.SSLObject sslobj)
None _verify_peercerts (ssl.SSLSocket|ssl.SSLObject sock_or_sslobj, str|None server_hostname)
Variables
typing _StrOrBytesPath = str | bytes | os.PathLike[str] | os.PathLike[bytes]
typing _PasswordType = str | bytes | typing.Callable[[], str | bytes]
Function Documentation
_get_unverified_chain_bytes()
list[bytes] pip._vendor.truststore._api._get_unverified_chain_bytes (ssl.SSLObject sslobj) protected
Definition at line 285 of file _api.py.
    def _get_unverified_chain_bytes(sslobj: ssl.SSLObject) -> list[bytes]:
        unverified_chain = sslobj.get_unverified_chain() or ()  # type: ignore[attr-defined]
        return [
            cert if isinstance(cert, bytes) else cert.public_bytes(_ssl.ENCODING_DER)
            for cert in unverified_chain
        ]
Referenced by _verify_peercerts().
_verify_peercerts()
None pip._vendor.truststore._api._verify_peercerts (ssl.SSLSocket | ssl.SSLObject sock_or_sslobj, str | None server_hostname) protected
Verifies the peer certificates from an SSLSocket or SSLObject
against the certificates in the OS trust store.
Definition at line 299 of file _api.py.
) -> None:
    """
    Verifies the peer certificates from an SSLSocket or SSLObject
    against the certificates in the OS trust store.
    """
    sslobj: ssl.SSLObject = sock_or_sslobj  # type: ignore[assignment]
    try:
        while not hasattr(sslobj, "get_unverified_chain"):
            sslobj = sslobj._sslobj  # type: ignore[attr-defined]
    except AttributeError:
        pass
    cert_bytes = _get_unverified_chain_bytes(sslobj)
    _verify_peercerts_impl(
        sock_or_sslobj.context, cert_bytes, server_hostname=server_hostname
    )
References _get_unverified_chain_bytes().
Referenced by pip._vendor.truststore._api.SSLContext.wrap_socket().
extract_from_ssl()
None pip._vendor.truststore._api.extract_from_ssl ()
Restores the :class:`ssl.SSLContext` class to its original state
Definition at line 47 of file _api.py.
def extract_from_ssl() -> None:
    """Restores the :class:`ssl.SSLContext` class to its original state"""
    setattr(ssl, "SSLContext", _original_SSLContext)
    try:
        import pip._vendor.urllib3.util.ssl_ as urllib3_ssl
        urllib3_ssl.SSLContext = _original_SSLContext  # type: ignore[assignment]
    except ImportError:
        pass
inject_into_ssl()
None pip._vendor.truststore._api.inject_into_ssl ()
Injects the :class:`truststore.SSLContext` into the ``ssl``
module by replacing :class:`ssl.SSLContext`.
Definition at line 32 of file _api.py.
def inject_into_ssl() -> None:
    """Injects the :class:`truststore.SSLContext` into the ``ssl``
    module by replacing :class:`ssl.SSLContext`.
    """
    setattr(ssl, "SSLContext", SSLContext)
    # urllib3 holds on to its own reference of ssl.SSLContext
    # so we need to replace that reference too.
    try:
        import pip._vendor.urllib3.util.ssl_ as urllib3_ssl
        setattr(urllib3_ssl, "SSLContext", SSLContext)
    except ImportError:
        pass
Variable Documentation
_PasswordType
typing pip._vendor.truststore._api._PasswordType = str | bytes | typing.Callable[[], str | bytes] protected
Definition at line 29 of file _api.py.
_StrOrBytesPath
typing pip._vendor.truststore._api._StrOrBytesPath = str | bytes | os.PathLike[str] | os.PathLike[bytes] protected
Definition at line 28 of file _api.py.