Read&Watch: pip._internal.utils.misc Namespace Reference
pip._internal.utils.misc Namespace Reference
Classes
class ConfiguredBuildBackendHookCaller
class HiddenText
class StreamWrapper
Functions
str get_pip_version ()
Tuple[int, int, int] normalize_version_info (Tuple[int,...] py_version_info)
None ensure_dir (str path)
str get_prog ()
None rmtree (str dir, bool ignore_errors=False, Optional[OnExc] onexc=None)
None _onerror_ignore (*Any _args)
None _onerror_reraise (*Any _args)
None rmtree_errorhandler (FunctionType func, Path path, Union[ExcInfo, BaseException] exc_info, *, OnExc onexc=_onerror_reraise)
str display_path (str path)
str backup_dir (str dir, str ext=".bak")
str ask_path_exists (str message, Iterable[str] options)
None _check_no_input (str message)
str ask (str message, Iterable[str] options)
str ask_input (str message)
str ask_password (str message)
int strtobool (str val)
str format_size (float bytes)
Tuple[List[str], List[int]] tabulate (Iterable[Iterable[Any]] rows)
bool is_installable_dir (str path)
Generator[bytes, None, None] read_chunks (BinaryIO file, int size=FILE_CHUNK_SIZE)
str normalize_path (str path, bool resolve_symlinks=True)
Tuple[str, str] splitext (str path)
None renames (str old, str new)
bool is_local (str path)
None write_output (Any msg, *Any args)
Type[Any] enum (*Any sequential, **Any named)
str build_netloc (str host, Optional[int] port)
str build_url_from_netloc (str netloc, str scheme="https")
Tuple[Optional[str], Optional[int]] parse_netloc (str netloc)
NetlocTuple split_auth_from_netloc (str netloc)
str redact_netloc (str netloc)
Tuple[str, NetlocTuple] _transform_url (str url, Callable[[str], Tuple[Any,...]] transform_netloc)
NetlocTuple _get_netloc (str netloc)
Tuple[str] _redact_netloc (str netloc)
Tuple[str, str, Tuple[Optional[str], Optional[str]]] split_auth_netloc_from_url (str url)
str remove_auth_from_url (str url)
str redact_auth_from_url (str url)
str redact_auth_from_requirement (Requirement req)
HiddenText hide_value (str value)
HiddenText hide_url (str url)
None protect_pip_from_modification_on_windows (bool modifying_pip)
None check_externally_managed ()
bool is_console_interactive ()
Tuple[Any, int] hash_file (str path, int blocksize=1<< 20)
Iterator[Tuple[Any, Any]] pairwise (Iterable[Any] iterable)
Tuple[Iterable[T], Iterable[T]] partition (Callable[[T], bool] pred, Iterable[T] iterable)
None warn_if_run_as_root ()
Variables
logger = logging.getLogger(__name__)
T = TypeVar("T")
ExcInfo = Tuple[Type[BaseException], BaseException, TracebackType]
VersionInfo = Tuple[int, int, int]
NetlocTuple = Tuple[str, Tuple[Optional[str], Optional[str]]]
OnExc = Callable[[FunctionType, Path, BaseException], Any]
OnErr = Callable[[FunctionType, Path, ExcInfo], Any]
int FILE_CHUNK_SIZE = 1024 * 1024
Function Documentation
_check_no_input()
None pip._internal.utils.misc._check_no_input (str message) protected
Raise an error if no input is allowed.
Definition at line 216 of file misc.py.
def _check_no_input(message: str) -> None:
    """Raise an error if no input is allowed."""
    if os.environ.get("PIP_NO_INPUT"):
        raise Exception(
            f"No input was expected ($PIP_NO_INPUT set); question: {message}"
        )
Referenced by ask(), ask_input(), and ask_password().
_get_netloc()
NetlocTuple pip._internal.utils.misc._get_netloc (str netloc) protected
Definition at line 501 of file misc.py.
def _get_netloc(netloc: str) -> NetlocTuple:
    return split_auth_from_netloc(netloc)
References split_auth_from_netloc().
_onerror_ignore()
None pip._internal.utils.misc._onerror_ignore (*Any _args) protected
Definition at line 140 of file misc.py.
def _onerror_ignore(*_args: Any) -> None:
    pass
_onerror_reraise()
None pip._internal.utils.misc._onerror_reraise (*Any _args) protected
Definition at line 144 of file misc.py.
def _onerror_reraise(*_args: Any) -> None:
    raise  # noqa: PLE0704 - Bare exception used to reraise existing exception
_redact_netloc()
Tuple[str] pip._internal.utils.misc._redact_netloc (str netloc) protected
Definition at line 505 of file misc.py.
def _redact_netloc(netloc: str) -> Tuple[str]:
    return (redact_netloc(netloc),)
References redact_netloc().
_transform_url()
Tuple[str, NetlocTuple] pip._internal.utils.misc._transform_url (str url, Callable[[str], Tuple[Any, ...]] transform_netloc) protected
Transform and replace netloc in a url.
transform_netloc is a function taking the netloc and returning a
tuple. The first element of this tuple is the new netloc. The
entire tuple is returned.
Returns a tuple containing the transformed url as item 0 and the
original tuple returned by transform_netloc as item 1.
Definition at line 481 of file misc.py.
) -> Tuple[str, NetlocTuple]:
    """Transform and replace netloc in a url.
    transform_netloc is a function taking the netloc and returning a
    tuple. The first element of this tuple is the new netloc. The
    entire tuple is returned.
    Returns a tuple containing the transformed url as item 0 and the
    original tuple returned by transform_netloc as item 1.
    """
    purl = urllib.parse.urlsplit(url)
    netloc_tuple = transform_netloc(purl.netloc)
    # stripped url
    url_pieces = (purl.scheme, netloc_tuple[0], purl.path, purl.query, purl.fragment)
    surl = urllib.parse.urlunsplit(url_pieces)
    return surl, cast("NetlocTuple", netloc_tuple)
Referenced by redact_auth_from_url(), remove_auth_from_url(), and split_auth_netloc_from_url().
ask()
str pip._internal.utils.misc.ask (str message, Iterable[str] options)
Ask the message interactively, with the given possible responses
Definition at line 224 of file misc.py.
def ask(message: str, options: Iterable[str]) -> str:
    """Ask the message interactively, with the given possible responses"""
    while 1:
        _check_no_input(message)
        response = input(message)
        response = response.strip().lower()
        if response not in options:
            print(
                "Your response ({!r}) was not one of the expected responses: "
                "{}".format(response, ", ".join(options))
            )
        else:
            return response
References _check_no_input().
Referenced by ask_path_exists().
ask_input()
str pip._internal.utils.misc.ask_input (str message)
Ask for input interactively.
Definition at line 239 of file misc.py.
def ask_input(message: str) -> str:
    """Ask for input interactively."""
    _check_no_input(message)
    return input(message)
References _check_no_input().
ask_password()
str pip._internal.utils.misc.ask_password (str message)
Ask for a password interactively.
Definition at line 245 of file misc.py.
def ask_password(message: str) -> str:
    """Ask for a password interactively."""
    _check_no_input(message)
    return getpass.getpass(message)
References _check_no_input().
ask_path_exists()
str pip._internal.utils.misc.ask_path_exists (str message, Iterable[str] options)
Definition at line 209 of file misc.py.
def ask_path_exists(message: str, options: Iterable[str]) -> str:
    for action in os.environ.get("PIP_EXISTS_ACTION", "").split():
        if action in options:
            return action
    return ask(message, options)
References ask().
backup_dir()
str pip._internal.utils.misc.backup_dir (str dir, str ext = ".bak")
Figure out the name of a directory to back up the given dir to
(adding .bak, .bak2, etc)
Definition at line 198 of file misc.py.
def backup_dir(dir: str, ext: str = ".bak") -> str:
    """Figure out the name of a directory to back up the given dir to
    (adding .bak, .bak2, etc)"""
    n = 1
    extension = ext
    while os.path.exists(dir + extension):
        n += 1
        extension = ext + str(n)
    return dir + extension
build_netloc()
str pip._internal.utils.misc.build_netloc (str host, Optional[int] port)
Build a netloc from a host-port pair
Definition at line 401 of file misc.py.
def build_netloc(host: str, port: Optional[int]) -> str:
    """
    Build a netloc from a host-port pair
    """
    if port is None:
        return host
    if ":" in host:
        # Only wrap host with square brackets when it is IPv6
        host = f"[{host}]"
    return f"{host}:{port}"
build_url_from_netloc()
str pip._internal.utils.misc.build_url_from_netloc (str netloc, str scheme = "https")
Build a full URL from a netloc.
Definition at line 413 of file misc.py.
def build_url_from_netloc(netloc: str, scheme: str = "https") -> str:
    """
    Build a full URL from a netloc.
    """
    if netloc.count(":") >= 2 and "@" not in netloc and "[" not in netloc:
        # It must be a bare IPv6 address, so wrap it with brackets.
        netloc = f"[{netloc}]"
    return f"{scheme}://{netloc}"
Referenced by parse_netloc().
check_externally_managed()
None pip._internal.utils.misc.check_externally_managed ()
Check whether the current environment is externally managed.
If the ``EXTERNALLY-MANAGED`` config file is found, the current environment
is considered externally managed, and an ExternallyManagedEnvironment is
raised.
Definition at line 596 of file misc.py.
def check_externally_managed() -> None:
    """Check whether the current environment is externally managed.
    If the ``EXTERNALLY-MANAGED`` config file is found, the current environment
    is considered externally managed, and an ExternallyManagedEnvironment is
    raised.
    """
    if running_under_virtualenv():
        return
    marker = os.path.join(sysconfig.get_path("stdlib"), "EXTERNALLY-MANAGED")
    if not os.path.isfile(marker):
        return
    raise ExternallyManagedEnvironment.from_config(marker)
display_path()
str pip._internal.utils.misc.display_path (str path)
Gives the display value for a given path, making it relative to cwd
if possible.
Definition at line 189 of file misc.py.
def display_path(path: str) -> str:
    """Gives the display value for a given path, making it relative to cwd
    if possible."""
    path = os.path.normcase(os.path.abspath(path))
    if path.startswith(os.getcwd() + os.path.sep):
        path = "." + path[len(os.getcwd()) :]
    return path
ensure_dir()
None pip._internal.utils.misc.ensure_dir (str path)
os.path.makedirs without EEXIST.
Definition at line 101 of file misc.py.
def ensure_dir(path: str) -> None:
    """os.path.makedirs without EEXIST."""
    try:
        os.makedirs(path)
    except OSError as e:
        # Windows can raise spurious ENOTEMPTY errors. See #6426.
        if e.errno != errno.EEXIST and e.errno != errno.ENOTEMPTY:
            raise
enum()
Type[Any] pip._internal.utils.misc.enum (*Any sequential, **Any named)
Definition at line 394 of file misc.py.
def enum(*sequential: Any, **named: Any) -> Type[Any]:
    enums = dict(zip(sequential, range(len(sequential))), **named)
    reverse = {value: key for key, value in enums.items()}
    enums["reverse_mapping"] = reverse
    return type("Enum", (), enums)
format_size()
str pip._internal.utils.misc.format_size (float bytes)
Definition at line 267 of file misc.py.
def format_size(bytes: float) -> str:
    if bytes > 1000 * 1000:
        return f"{bytes / 1000.0 / 1000:.1f} MB"
    elif bytes > 10 * 1000:
        return f"{int(bytes / 1000)} kB"
    elif bytes > 1000:
        return f"{bytes / 1000.0:.1f} kB"
    else:
        return f"{int(bytes)} bytes"
get_pip_version()
str pip._internal.utils.misc.get_pip_version ()
Definition at line 75 of file misc.py.
def get_pip_version() -> str:
    pip_pkg_dir = os.path.join(os.path.dirname(__file__), "..", "..")
    pip_pkg_dir = os.path.abspath(pip_pkg_dir)
    return f"pip {__version__} from {pip_pkg_dir} (python {get_major_minor_version()})"
get_prog()
str pip._internal.utils.misc.get_prog ()
Definition at line 111 of file misc.py.
def get_prog() -> str:
    try:
        prog = os.path.basename(sys.argv[0])
        if prog in ("__main__.py", "-c"):
            return f"{sys.executable} -m pip"
        else:
            return prog
    except (AttributeError, TypeError, IndexError):
        pass
    return "pip"
# Retry every half second for up to 3 seconds
@retry(stop_after_delay=3, wait=0.5)
hash_file()
Tuple[Any, int] pip._internal.utils.misc.hash_file (str path, int blocksize = 1 << 20)
Return (hash, length) for path using hashlib.sha256()
Definition at line 616 of file misc.py.
def hash_file(path: str, blocksize: int = 1 << 20) -> Tuple[Any, int]:
    """Return (hash, length) for path using hashlib.sha256()"""
    h = hashlib.sha256()
    length = 0
    with open(path, "rb") as f:
        for block in read_chunks(f, size=blocksize):
            length += len(block)
            h.update(block)
    return h, length
References read_chunks().
hide_url()
HiddenText pip._internal.utils.misc.hide_url (str url)
Definition at line 565 of file misc.py.
def hide_url(url: str) -> HiddenText:
    redacted = redact_auth_from_url(url)
    return HiddenText(url, redacted=redacted)
References redact_auth_from_url().
hide_value()
HiddenText pip._internal.utils.misc.hide_value (str value)
Definition at line 561 of file misc.py.
def hide_value(value: str) -> HiddenText:
    return HiddenText(value, redacted="****")
is_console_interactive()
bool pip._internal.utils.misc.is_console_interactive ()
Is this console interactive?
Definition at line 611 of file misc.py.
def is_console_interactive() -> bool:
    """Is this console interactive?"""
    return sys.stdin is not None and sys.stdin.isatty()
is_installable_dir()
bool pip._internal.utils.misc.is_installable_dir (str path)
Is path is a directory containing pyproject.toml or setup.py?
If pyproject.toml exists, this is a PEP 517 project. Otherwise we look for
a legacy setuptools layout by identifying setup.py. We don't check for the
setup.cfg because using it without setup.py is only available for PEP 517
projects, which are already covered by the pyproject.toml check.
Definition at line 292 of file misc.py.
def is_installable_dir(path: str) -> bool:
    """Is path is a directory containing pyproject.toml or setup.py?
    If pyproject.toml exists, this is a PEP 517 project. Otherwise we look for
    a legacy setuptools layout by identifying setup.py. We don't check for the
    setup.cfg because using it without setup.py is only available for PEP 517
    projects, which are already covered by the pyproject.toml check.
    """
    if not os.path.isdir(path):
        return False
    if os.path.isfile(os.path.join(path, "pyproject.toml")):
        return True
    if os.path.isfile(os.path.join(path, "setup.py")):
        return True
    return False
is_local()
bool pip._internal.utils.misc.is_local (str path)
Return True if path is within sys.prefix, if we're running in a virtualenv.
If we're not in a virtualenv, all paths are considered "local."
Caution: this function assumes the head of path has been normalized
with normalize_path.
Definition at line 359 of file misc.py.
def is_local(path: str) -> bool:
    """
    Return True if path is within sys.prefix, if we're running in a virtualenv.
    If we're not in a virtualenv, all paths are considered "local."
    Caution: this function assumes the head of path has been normalized
    with normalize_path.
    """
    if not running_under_virtualenv():
        return True
    return path.startswith(normalize_path(sys.prefix))
References normalize_path().
normalize_path()
str pip._internal.utils.misc.normalize_path (str path, bool resolve_symlinks = True)
Convert a path to its canonical, case-normalized, absolute version.
Definition at line 320 of file misc.py.
def normalize_path(path: str, resolve_symlinks: bool = True) -> str:
    """
    Convert a path to its canonical, case-normalized, absolute version.
    """
    path = os.path.expanduser(path)
    if resolve_symlinks:
        path = os.path.realpath(path)
    else:
        path = os.path.abspath(path)
    return os.path.normcase(path)
Referenced by is_local().
normalize_version_info()
Tuple[int, int, int] pip._internal.utils.misc.normalize_version_info (Tuple[int, ...] py_version_info)
Convert a tuple of ints representing a Python version to one of length
three.
:param py_version_info: a tuple of ints representing a Python version,
    or None to specify no version. The tuple can have any length.
:return: a tuple of length three if `py_version_info` is non-None.
    Otherwise, return `py_version_info` unchanged (i.e. None).
Definition at line 82 of file misc.py.
def normalize_version_info(py_version_info: Tuple[int, ...]) -> Tuple[int, int, int]:
    """
    Convert a tuple of ints representing a Python version to one of length
    three.
    :param py_version_info: a tuple of ints representing a Python version,
        or None to specify no version. The tuple can have any length.
    :return: a tuple of length three if `py_version_info` is non-None.
        Otherwise, return `py_version_info` unchanged (i.e. None).
    """
    if len(py_version_info) < 3:
        py_version_info += (3 - len(py_version_info)) * (0,)
    elif len(py_version_info) > 3:
        py_version_info = py_version_info[:3]
    return cast("VersionInfo", py_version_info)
pairwise()
Iterator[Tuple[Any, Any]] pip._internal.utils.misc.pairwise (Iterable[Any] iterable)
Return paired elements.
For example:
    s -> (s0, s1), (s2, s3), (s4, s5), ...
Definition at line 628 of file misc.py.
def pairwise(iterable: Iterable[Any]) -> Iterator[Tuple[Any, Any]]:
    """
    Return paired elements.
    For example:
        s -> (s0, s1), (s2, s3), (s4, s5), ...
    """
    iterable = iter(iterable)
    return zip_longest(iterable, iterable)
parse_netloc()
Tuple[Optional[str], Optional[int]] pip._internal.utils.misc.parse_netloc (str netloc)
Return the host-port pair from a netloc.
Definition at line 423 of file misc.py.
def parse_netloc(netloc: str) -> Tuple[Optional[str], Optional[int]]:
    """
    Return the host-port pair from a netloc.
    """
    url = build_url_from_netloc(netloc)
    parsed = urllib.parse.urlparse(url)
    return parsed.hostname, parsed.port
References build_url_from_netloc().
partition()
Tuple[Iterable[T], Iterable[T]] pip._internal.utils.misc.partition (Callable[[T], bool] pred, Iterable[T] iterable)
Use a predicate to partition entries into false entries and true entries,
like
    partition(is_odd, range(10)) --> 0 2 4 6 8   and  1 3 5 7 9
Definition at line 639 of file misc.py.
) -> Tuple[Iterable[T], Iterable[T]]:
    """
    Use a predicate to partition entries into false entries and true entries,
    like
        partition(is_odd, range(10)) --> 0 2 4 6 8   and  1 3 5 7 9
    """
    t1, t2 = tee(iterable)
    return filterfalse(pred, t1), filter(pred, t2)
protect_pip_from_modification_on_windows()
None pip._internal.utils.misc.protect_pip_from_modification_on_windows (bool modifying_pip)
Protection of pip.exe from modification on Windows
On Windows, any operation modifying pip should be run as:
    python -m pip ...
Definition at line 570 of file misc.py.
def protect_pip_from_modification_on_windows(modifying_pip: bool) -> None:
    """Protection of pip.exe from modification on Windows
    On Windows, any operation modifying pip should be run as:
        python -m pip ...
    """
    pip_names = [
        "pip",
        f"pip{sys.version_info.major}",
        f"pip{sys.version_info.major}.{sys.version_info.minor}",
    ]
    # See https://github.com/pypa/pip/issues/1299 for more discussion
    should_show_use_python_msg = (
        modifying_pip and WINDOWS and os.path.basename(sys.argv[0]) in pip_names
    )
    if should_show_use_python_msg:
        new_command = [sys.executable, "-m", "pip"] + sys.argv[1:]
        raise CommandError(
            "To modify pip, please run the following command:\n{}".format(
                " ".join(new_command)
            )
        )
read_chunks()
Generator[bytes, None, None] pip._internal.utils.misc.read_chunks (BinaryIO file, int size = FILE_CHUNK_SIZE)
Yield pieces of data from a file-like object until EOF.
Definition at line 309 of file misc.py.
) -> Generator[bytes, None, None]:
    """Yield pieces of data from a file-like object until EOF."""
    while True:
        chunk = file.read(size)
        if not chunk:
            break
        yield chunk
Referenced by hash_file().
redact_auth_from_requirement()
str pip._internal.utils.misc.redact_auth_from_requirement (Requirement req)
Replace the password in a given requirement url with ****.
Definition at line 533 of file misc.py.
def redact_auth_from_requirement(req: Requirement) -> str:
    """Replace the password in a given requirement url with ****."""
    if not req.url:
        return str(req)
    return str(req).replace(req.url, redact_auth_from_url(req.url))
@dataclass(frozen=True)
References redact_auth_from_url().
redact_auth_from_url()
str pip._internal.utils.misc.redact_auth_from_url (str url)
Replace the password in a given url with ****.
Definition at line 528 of file misc.py.
def redact_auth_from_url(url: str) -> str:
    """Replace the password in a given url with ****."""
    return _transform_url(url, _redact_netloc)[0]
References _transform_url().
Referenced by hide_url(), and redact_auth_from_requirement().
redact_netloc()
str pip._internal.utils.misc.redact_netloc (str netloc)
Replace the sensitive data in a netloc with "****", if it exists.
For example:
    - "user:pass@example.com" returns "user:****@example.com"
    - "accesstoken@example.com" returns "****@example.com"
Definition at line 461 of file misc.py.
def redact_netloc(netloc: str) -> str:
    """
    Replace the sensitive data in a netloc with "****", if it exists.
    For example:
        - "user:pass@example.com" returns "user:****@example.com"
        - "accesstoken@example.com" returns "****@example.com"
    """
    netloc, (user, password) = split_auth_from_netloc(netloc)
    if user is None:
        return netloc
    if password is None:
        user = "****"
        password = ""
    else:
        user = urllib.parse.quote(user)
        password = ":****"
    return f"{user}{password}@{netloc}"
References split_auth_from_netloc().
Referenced by _redact_netloc().
remove_auth_from_url()
str pip._internal.utils.misc.remove_auth_from_url (str url)
Return a copy of url with 'username:password@' removed.
Definition at line 521 of file misc.py.
def remove_auth_from_url(url: str) -> str:
    """Return a copy of url with 'username:password@' removed."""
    # username/pass params are passed to subversion through flags
    # and are not recognized in the url.
    return _transform_url(url, _get_netloc)[0]
References _transform_url().
renames()
None pip._internal.utils.misc.renames (str old, str new)
Like os.renames(), but handles renaming across devices.
Definition at line 342 of file misc.py.
def renames(old: str, new: str) -> None:
    """Like os.renames(), but handles renaming across devices."""
    # Implementation borrowed from os.renames().
    head, tail = os.path.split(new)
    if head and tail and not os.path.exists(head):
        os.makedirs(head)
    shutil.move(old, new)
    head, tail = os.path.split(old)
    if head and tail:
        try:
            os.removedirs(head)
        except OSError:
            pass
rmtree()
None pip._internal.utils.misc.rmtree (str dir, bool ignore_errors = False, Optional[OnExc] onexc = None)
Definition at line 125 of file misc.py.
) -> None:
    if ignore_errors:
        onexc = _onerror_ignore
    if onexc is None:
        onexc = _onerror_reraise
    handler: OnErr = partial(rmtree_errorhandler, onexc=onexc)
    if sys.version_info >= (3, 12):
        # See https://docs.python.org/3.12/whatsnew/3.12.html#shutil.
        shutil.rmtree(dir, onexc=handler)  # type: ignore
    else:
        shutil.rmtree(dir, onerror=handler)  # type: ignore
rmtree_errorhandler()
None pip._internal.utils.misc.rmtree_errorhandler (FunctionType func, Path path, Union[ExcInfo, BaseException] exc_info, * , OnExc onexc = _onerror_reraise)
`rmtree` error handler to 'force' a file remove (i.e. like `rm -f`).
* If a file is readonly then it's write flag is set and operation is
  retried.
* `onerror` is the original callback from `rmtree(... onerror=onerror)`
  that is chained at the end if the "rm -f" still fails.
Definition at line 148 of file misc.py.
) -> None:
    """
    `rmtree` error handler to 'force' a file remove (i.e. like `rm -f`).
    * If a file is readonly then it's write flag is set and operation is
      retried.
    * `onerror` is the original callback from `rmtree(... onerror=onerror)`
      that is chained at the end if the "rm -f" still fails.
    """
    try:
        st_mode = os.stat(path).st_mode
    except OSError:
        # it's equivalent to os.path.exists
        return
    if not st_mode & stat.S_IWRITE:
        # convert to read/write
        try:
            os.chmod(path, st_mode | stat.S_IWRITE)
        except OSError:
            pass
        else:
            # use the original function to repeat the operation
            try:
                func(path)
                return
            except OSError:
                pass
    if not isinstance(exc_info, BaseException):
        _, exc_info, _ = exc_info
    onexc(func, path, exc_info)
split_auth_from_netloc()
NetlocTuple pip._internal.utils.misc.split_auth_from_netloc (str netloc)
Parse out and remove the auth information from a netloc.
Returns: (netloc, (username, password)).
Definition at line 432 of file misc.py.
def split_auth_from_netloc(netloc: str) -> NetlocTuple:
    """
    Parse out and remove the auth information from a netloc.
    Returns: (netloc, (username, password)).
    """
    if "@" not in netloc:
        return netloc, (None, None)
    # Split from the right because that's how urllib.parse.urlsplit()
    # behaves if more than one @ is present (which can be checked using
    # the password attribute of urlsplit()'s return value).
    auth, netloc = netloc.rsplit("@", 1)
    pw: Optional[str] = None
    if ":" in auth:
        # Split from the left because that's how urllib.parse.urlsplit()
        # behaves if more than one : is present (which again can be checked
        # using the password attribute of the return value)
        user, pw = auth.split(":", 1)
    else:
        user, pw = auth, None
    user = urllib.parse.unquote(user)
    if pw is not None:
        pw = urllib.parse.unquote(pw)
    return netloc, (user, pw)
Referenced by _get_netloc(), and redact_netloc().
split_auth_netloc_from_url()
Tuple[str, str, Tuple[Optional[str], Optional[str]]] pip._internal.utils.misc.split_auth_netloc_from_url (str url)
Parse a url into separate netloc, auth, and url with no auth.
Returns: (url_without_auth, netloc, (username, password))
Definition at line 509 of file misc.py.
) -> Tuple[str, str, Tuple[Optional[str], Optional[str]]]:
    """
    Parse a url into separate netloc, auth, and url with no auth.
    Returns: (url_without_auth, netloc, (username, password))
    """
    url_without_auth, (netloc, auth) = _transform_url(url, _get_netloc)
    return url_without_auth, netloc, auth
References _transform_url().
splitext()
Tuple[str, str] pip._internal.utils.misc.splitext (str path)
Like os.path.splitext, but take off .tar too
Definition at line 333 of file misc.py.
def splitext(path: str) -> Tuple[str, str]:
    """Like os.path.splitext, but take off .tar too"""
    base, ext = posixpath.splitext(path)
    if base.lower().endswith(".tar"):
        ext = base[-4:] + ext
        base = base[:-4]
    return base, ext
strtobool()
int pip._internal.utils.misc.strtobool (str val)
Convert a string representation of truth to true (1) or false (0).
True values are 'y', 'yes', 't', 'true', 'on', and '1'; false values
are 'n', 'no', 'f', 'false', 'off', and '0'.  Raises ValueError if
'val' is anything else.
Definition at line 251 of file misc.py.
def strtobool(val: str) -> int:
    """Convert a string representation of truth to true (1) or false (0).
    True values are 'y', 'yes', 't', 'true', 'on', and '1'; false values
    are 'n', 'no', 'f', 'false', 'off', and '0'.  Raises ValueError if
    'val' is anything else.
    """
    val = val.lower()
    if val in ("y", "yes", "t", "true", "on", "1"):
        return 1
    elif val in ("n", "no", "f", "false", "off", "0"):
        return 0
    else:
        raise ValueError(f"invalid truth value {val!r}")
tabulate()
Tuple[List[str], List[int]] pip._internal.utils.misc.tabulate (Iterable[Iterable[Any]] rows)
Return a list of formatted rows and a list of column sizes.
For example::
>>> tabulate([['foobar', 2000], [0xdeadbeef]])
(['foobar     2000', '3735928559'], [10, 4])
Definition at line 278 of file misc.py.
def tabulate(rows: Iterable[Iterable[Any]]) -> Tuple[List[str], List[int]]:
    """Return a list of formatted rows and a list of column sizes.
    For example::
    >>> tabulate([['foobar', 2000], [0xdeadbeef]])
    (['foobar     2000', '3735928559'], [10, 4])
    """
    rows = [tuple(map(str, row)) for row in rows]
    sizes = [max(map(len, col)) for col in zip_longest(*rows, fillvalue="")]
    table = [" ".join(map(str.ljust, row, sizes)).rstrip() for row in rows]
    return table, sizes
warn_if_run_as_root()
None pip._internal.utils.misc.warn_if_run_as_root ()
Output a warning for sudo users on Unix.
In a virtual environment, sudo pip still writes to virtualenv.
On Windows, users may run pip as Administrator without issues.
This warning only applies to Unix root users outside of virtualenv.
Definition at line 742 of file misc.py.
def warn_if_run_as_root() -> None:
    """Output a warning for sudo users on Unix.
    In a virtual environment, sudo pip still writes to virtualenv.
    On Windows, users may run pip as Administrator without issues.
    This warning only applies to Unix root users outside of virtualenv.
    """
    if running_under_virtualenv():
        return
    if not hasattr(os, "getuid"):
        return
    # On Windows, there are no "system managed" Python packages. Installing as
    # Administrator via pip is the correct way of updating system environments.
    #
    # We choose sys.platform over utils.compat.WINDOWS here to enable Mypy platform
    # checks: https://mypy.readthedocs.io/en/stable/common_issues.html
    if sys.platform == "win32" or sys.platform == "cygwin":
        return
    if os.getuid() != 0:
        return
    logger.warning(
        "Running pip as the 'root' user can result in broken permissions and "
        "conflicting behaviour with the system package manager, possibly "
        "rendering your system unusable."
        "It is recommended to use a virtual environment instead: "
        "https://pip.pypa.io/warnings/venv. "
        "Use the --root-user-action option if you know what you are doing and "
        "want to suppress this warning."
    )
write_output()
None pip._internal.utils.misc.write_output (Any msg, *Any args)
Definition at line 373 of file misc.py.
def write_output(msg: Any, *args: Any) -> None:
    logger.info(msg, *args)
Variable Documentation
ExcInfo
pip._internal.utils.misc.ExcInfo = Tuple[Type[BaseException], BaseException, TracebackType]
Definition at line 66 of file misc.py.
FILE_CHUNK_SIZE
int pip._internal.utils.misc.FILE_CHUNK_SIZE = 1024 * 1024
Definition at line 72 of file misc.py.
logger
pip._internal.utils.misc.logger = logging.getLogger(__name__)
Definition at line 63 of file misc.py.
NetlocTuple
pip._internal.utils.misc.NetlocTuple = Tuple[str, Tuple[Optional[str], Optional[str]]]
Definition at line 68 of file misc.py.
OnErr
pip._internal.utils.misc.OnErr = Callable[[FunctionType, Path, ExcInfo], Any]
Definition at line 70 of file misc.py.
OnExc
pip._internal.utils.misc.OnExc = Callable[[FunctionType, Path, BaseException], Any]
Definition at line 69 of file misc.py.
T
pip._internal.utils.misc.T = TypeVar("T")
Definition at line 65 of file misc.py.
VersionInfo
pip._internal.utils.misc.VersionInfo = Tuple[int, int, int]
Definition at line 67 of file misc.py.