Read&Watch: pip._vendor.distlib.database Namespace Reference
pip._vendor.distlib.database Namespace Reference
Classes
class _Cache
class BaseInstalledDistribution
class DependencyGraph
class Distribution
class DistributionPath
class EggInfoDistribution
class InstalledDistribution
Functions
make_graph (dists, scheme='default')
get_dependent_dists (dists, dist)
get_required_dists (dists, dist)
make_dist (name, version, **kwargs)
Variables
logger = logging.getLogger(__name__)
str EXPORTS_FILENAME = 'pydist-exports.json'
str COMMANDS_FILENAME = 'pydist-commands.json'
tuple DIST_FILES = ('INSTALLER', METADATA_FILENAME, 'RECORD', 'REQUESTED', 'RESOURCES', EXPORTS_FILENAME, 'SHARED')
str DISTINFO_EXT = '.dist-info'
new_dist_class = InstalledDistribution
old_dist_class = EggInfoDistribution
Detailed Description
PEP 376 implementation.
Function Documentation
get_dependent_dists()
pip._vendor.distlib.database.get_dependent_dists (dists, dist)
Recursively generate a list of distributions from *dists* that are
dependent on *dist*.
:param dists: a list of distributions
:param dist: a distribution, member of *dists* for which we are interested
Definition at line 1265 of file database.py.
def get_dependent_dists(dists, dist):
    """Recursively generate a list of distributions from *dists* that are
    dependent on *dist*.
    :param dists: a list of distributions
    :param dist: a distribution, member of *dists* for which we are interested
    """
    if dist not in dists:
        raise DistlibException('given distribution %r is not a member '
                               'of the list' % dist.name)
    graph = make_graph(dists)
    dep = [dist]  # dependent distributions
    todo = graph.reverse_list[dist]  # list of nodes we should inspect
    while todo:
        d = todo.pop()
        dep.append(d)
        for succ in graph.reverse_list[d]:
            if succ not in dep:
                todo.append(succ)
    dep.pop(0)  # remove dist from dep, was there to prevent infinite loops
    return dep
References make_graph().
get_required_dists()
pip._vendor.distlib.database.get_required_dists (dists, dist)
Recursively generate a list of distributions from *dists* that are
required by *dist*.
:param dists: a list of distributions
:param dist: a distribution, member of *dists* for which we are interested
             in finding the dependencies.
Definition at line 1291 of file database.py.
def get_required_dists(dists, dist):
    """Recursively generate a list of distributions from *dists* that are
    required by *dist*.
    :param dists: a list of distributions
    :param dist: a distribution, member of *dists* for which we are interested
                 in finding the dependencies.
    """
    if dist not in dists:
        raise DistlibException('given distribution %r is not a member '
                               'of the list' % dist.name)
    graph = make_graph(dists)
    req = set()  # required distributions
    todo = graph.adjacency_list[dist]  # list of nodes we should inspect
    seen = set(t[0] for t in todo)  # already added to todo
    while todo:
        d = todo.pop()[0]
        req.add(d)
        pred_list = graph.adjacency_list[d]
        for pred in pred_list:
            d = pred[0]
            if d not in req and d not in seen:
                seen.add(d)
                todo.append(pred)
    return req
References make_graph().
make_dist()
pip._vendor.distlib.database.make_dist (name, version, ** kwargs)
A convenience method for making a dist given just a name and version.
Definition at line 1320 of file database.py.
def make_dist(name, version, **kwargs):
    """
    A convenience method for making a dist given just a name and version.
    """
    summary = kwargs.pop('summary', 'Placeholder for summary')
    md = Metadata(**kwargs)
    md.name = name
    md.version = version
    md.summary = summary or 'Placeholder for summary'
    return Distribution(md)
make_graph()
pip._vendor.distlib.database.make_graph (dists, scheme = 'default')
Makes a dependency graph from the given distributions.
:parameter dists: a list of distributions
:type dists: list of :class:`distutils2.database.InstalledDistribution` and
             :class:`distutils2.database.EggInfoDistribution` instances
:rtype: a :class:`DependencyGraph` instance
Definition at line 1213 of file database.py.
def make_graph(dists, scheme='default'):
    """Makes a dependency graph from the given distributions.
    :parameter dists: a list of distributions
    :type dists: list of :class:`distutils2.database.InstalledDistribution` and
                 :class:`distutils2.database.EggInfoDistribution` instances
    :rtype: a :class:`DependencyGraph` instance
    """
    scheme = get_scheme(scheme)
    graph = DependencyGraph()
    provided = {}  # maps names to lists of (version, dist) tuples
    # first, build the graph and find out what's provided
    for dist in dists:
        graph.add_distribution(dist)
        for p in dist.provides:
            name, version = parse_name_and_version(p)
            logger.debug('Add to provided: %s, %s, %s', name, version, dist)
            provided.setdefault(name, []).append((version, dist))
    # now make the edges
    for dist in dists:
        requires = (dist.run_requires | dist.meta_requires | dist.build_requires | dist.dev_requires)
        for req in requires:
            try:
                matcher = scheme.matcher(req)
            except UnsupportedVersionError:
                # XXX compat-mode if cannot read the version
                logger.warning('could not read version %r - using name only', req)
                name = req.split()[0]
                matcher = scheme.matcher(name)
            name = matcher.key  # case-insensitive
            matched = False
            if name in provided:
                for version, provider in provided[name]:
                    try:
                        match = matcher.match(version)
                    except UnsupportedVersionError:
                        match = False
                    if match:
                        graph.add_edge(dist, provider, req)
                        matched = True
                        break
            if not matched:
                graph.add_missing(dist, req)
    return graph
Referenced by get_dependent_dists(), and get_required_dists().
Variable Documentation
COMMANDS_FILENAME
str pip._vendor.distlib.database.COMMANDS_FILENAME = 'pydist-commands.json'
Definition at line 34 of file database.py.
DIST_FILES
tuple pip._vendor.distlib.database.DIST_FILES = ('INSTALLER', METADATA_FILENAME, 'RECORD', 'REQUESTED', 'RESOURCES', EXPORTS_FILENAME, 'SHARED')
Definition at line 36 of file database.py.
DISTINFO_EXT
str pip._vendor.distlib.database.DISTINFO_EXT = '.dist-info'
Definition at line 38 of file database.py.
EXPORTS_FILENAME
str pip._vendor.distlib.database.EXPORTS_FILENAME = 'pydist-exports.json'
Definition at line 33 of file database.py.
logger
pip._vendor.distlib.database.logger = logging.getLogger(__name__)
Definition at line 31 of file database.py.
new_dist_class
pip._vendor.distlib.database.new_dist_class = InstalledDistribution
Definition at line 1067 of file database.py.
Referenced by pip._vendor.distlib.database.DistributionPath._yield_distributions().
old_dist_class
pip._vendor.distlib.database.old_dist_class = EggInfoDistribution
Definition at line 1068 of file database.py.
Referenced by pip._vendor.distlib.database.DistributionPath._yield_distributions().