Read&Watch: PIL.PdfParser Namespace Reference
PIL.PdfParser Namespace Reference
Classes
class IndirectObjectDef
class IndirectReference
class IndirectReferenceTuple
class PdfArray
class PdfBinary
class PdfDict
class PdfFormatError
class PdfName
class PdfParser
class PdfStream
class XrefTable
Functions
bytes encode_text (str s)
str decode_text (bytes b)
None check_format_condition (bool condition, str error_message)
bytes pdf_repr (Any x)
Variables
dict PDFDocEncoding
_DictBase = collections.UserDict[Union[str, bytes], Any]
Function Documentation
check_format_condition()
None PIL.PdfParser.check_format_condition (bool condition, str error_message)
Definition at line 79 of file PdfParser.py.
def check_format_condition(condition: bool, error_message: str) -> None:
    if not condition:
        raise PdfFormatError(error_message)
Referenced by PIL.PdfParser.PdfParser.get_value(), PIL.PdfParser.PdfParser.interpret_trailer(), PIL.PdfParser.PdfParser.linearize_page_tree(), PIL.PdfParser.PdfParser.read_indirect(), PIL.PdfParser.PdfParser.read_prev_trailer(), PIL.PdfParser.PdfParser.read_trailer(), PIL.PdfParser.PdfParser.read_xref_table(), and PIL.PdfParser.XrefTable.write().
decode_text()
str PIL.PdfParser.decode_text (bytes b)
Definition at line 65 of file PdfParser.py.
def decode_text(b: bytes) -> str:
    if b[: len(codecs.BOM_UTF16_BE)] == codecs.BOM_UTF16_BE:
        return b[len(codecs.BOM_UTF16_BE) :].decode("utf_16_be")
    else:
        return "".join(PDFDocEncoding.get(byte, chr(byte)) for byte in b)
Referenced by PIL.PdfParser.PdfDict.__getattr__().
encode_text()
bytes PIL.PdfParser.encode_text (str s)
Definition at line 16 of file PdfParser.py.
def encode_text(s: str) -> bytes:
    return codecs.BOM_UTF16_BE + s.encode("utf_16_be")
Referenced by pdf_repr().
pdf_repr()
bytes PIL.PdfParser.pdf_repr (Any x)
Definition at line 337 of file PdfParser.py.
def pdf_repr(x: Any) -> bytes:
    if x is True:
        return b"true"
    elif x is False:
        return b"false"
    elif x is None:
        return b"null"
    elif isinstance(x, (PdfName, PdfDict, PdfArray, PdfBinary)):
        return bytes(x)
    elif isinstance(x, (int, float)):
        return str(x).encode("us-ascii")
    elif isinstance(x, time.struct_time):
        return b"(D:" + time.strftime("%Y%m%d%H%M%SZ", x).encode("us-ascii") + b")"
    elif isinstance(x, dict):
        return bytes(PdfDict(x))
    elif isinstance(x, list):
        return bytes(PdfArray(x))
    elif isinstance(x, str):
        return pdf_repr(encode_text(x))
    elif isinstance(x, bytes):
        # XXX escape more chars? handle binary garbage
        x = x.replace(b"\\", b"\\\\")
        x = x.replace(b"(", b"\\(")
        x = x.replace(b")", b"\\)")
        return b"(" + x + b")"
    else:
        return bytes(x)
References encode_text(), and pdf_repr().
Referenced by PIL.PdfParser.PdfArray.__bytes__(), PIL.PdfParser.PdfDict.__bytes__(), pdf_repr(), and PIL.PdfParser.PdfParser.write_obj().
Variable Documentation
_DictBase
PIL.PdfParser._DictBase = collections.UserDict[Union[str, bytes], Any] protected
Definition at line 255 of file PdfParser.py.
PDFDocEncoding
dict PIL.PdfParser.PDFDocEncoding
Definition at line 20 of file PdfParser.py.