Read&Watch: dill.tests.test_weakref Namespace Reference
dill.tests.test_weakref Namespace Reference
Classes
class _callable_class
class _class
Functions
_function ()
test_weakref ()
test_dictproxy ()
Function Documentation
_function()
dill.tests.test_weakref._function () protected
Definition at line 21 of file test_weakref.py.
def _function():
    pass
test_dictproxy()
dill.tests.test_weakref.test_dictproxy ()
Definition at line 58 of file test_weakref.py.
def test_dictproxy():
    from dill._dill import DictProxyType
    try:
        m = DictProxyType({"foo": "bar"})
    except Exception:
        m = type.__dict__
    mp = dill.copy(m)
    assert mp.items() == m.items()
References test_dictproxy(), and test_weakref().
Referenced by test_dictproxy().
test_weakref()
dill.tests.test_weakref.test_weakref ()
Definition at line 25 of file test_weakref.py.
def test_weakref():
    o = _class()
    oc = _callable_class()
    f = _function
    x = _class
    # ReferenceType
    r = weakref.ref(o)
    d_r = weakref.ref(_class())
    fr = weakref.ref(f)
    xr = weakref.ref(x)
    # ProxyType
    p = weakref.proxy(o)
    d_p = weakref.proxy(_class())
    # CallableProxyType
    cp = weakref.proxy(oc)
    d_cp = weakref.proxy(_callable_class())
    fp = weakref.proxy(f)
    xp = weakref.proxy(x)
    objlist = [r,d_r,fr,xr, p,d_p, cp,d_cp,fp,xp]
    #dill.detect.trace(True)
    for obj in objlist:
      res = dill.detect.errors(obj)
      if res:
        print ("%r:\n  %s" % (obj, res))
    # else:
    #   print ("PASS: %s" % obj)
      assert not res
Referenced by test_dictproxy().