Read&Watch: asgiref.sync Namespace Reference
asgiref.sync Namespace Reference
Classes
class AsyncToSync
class SyncToAsync
class ThreadSensitiveContext
Functions
None _restore_context (contextvars.Context context)
_F markcoroutinefunction (_F func)
Callable[[Union[Callable[_P, Coroutine[Any, Any, _R]], Callable[_P, Awaitable[_R]]]], Callable[_P, _R],] async_to_sync (*, bool force_new_loop=False)
Callable[_P, _R] async_to_sync (Union[Callable[_P, Coroutine[Any, Any, _R]], Callable[_P, Awaitable[_R]],] awaitable, *, bool force_new_loop=False)
Union[ Callable[[Union[Callable[_P, Coroutine[Any, Any, _R]], Callable[_P, Awaitable[_R]]]], Callable[_P, _R],], Callable[_P, _R],] async_to_sync (Optional[Union[Callable[_P, Coroutine[Any, Any, _R]], Callable[_P, Awaitable[_R]],]] awaitable=None, *, bool force_new_loop=False)
Callable[[Callable[_P, _R]], Callable[_P, Coroutine[Any, Any, _R]]] sync_to_async (*, bool thread_sensitive=True, Optional["ThreadPoolExecutor"] executor=None)
Callable[_P, Coroutine[Any, Any, _R]] sync_to_async (Callable[_P, _R] func, *, bool thread_sensitive=True, Optional["ThreadPoolExecutor"] executor=None)
Union[ Callable[[Callable[_P, _R]], Callable[_P, Coroutine[Any, Any, _R]]], Callable[_P, Coroutine[Any, Any, _R]],] sync_to_async (Optional[Callable[_P, _R]] func=None, *, bool thread_sensitive=True, Optional["ThreadPoolExecutor"] executor=None)
Variables
_F = TypeVar("_F", bound=Callable[..., Any])
_P = ParamSpec("_P")
_R = TypeVar("_R")
iscoroutinefunction = inspect.iscoroutinefunction
Callable markcoroutinefunction = inspect.markcoroutinefunction
Function Documentation
_restore_context()
None asgiref.sync._restore_context (contextvars.Context context) protected
Definition at line 44 of file sync.py.
def _restore_context(context: contextvars.Context) -> None:
    # Check for changes in contextvars, and set them to the current
    # context for downstream consumers
    for cvar in context:
        cvalue = context.get(cvar)
        try:
            if cvar.get() != cvalue:
                cvar.set(cvalue)
        except LookupError:
            cvar.set(cvalue)
# Python 3.12 deprecates asyncio.iscoroutinefunction() as an alias for
# inspect.iscoroutinefunction(), whilst also removing the _is_coroutine marker.
# The latter is replaced with the inspect.markcoroutinefunction decorator.
# Until 3.12 is the minimum supported Python version, provide a shim.
Referenced by asgiref.sync.AsyncToSync.__call__(), asgiref.sync.SyncToAsync.__call__(), and asgiref.sync.AsyncToSync.main_wrap().
async_to_sync() [1/3]
Callable[ [Union[Callable[_P, Coroutine[Any, Any, _R]], Callable[_P, Awaitable[_R]]]], Callable[_P, _R], ] asgiref.sync.async_to_sync (* , bool force_new_loop = False)
Definition at line 526 of file sync.py.
]:
    ...
@overload
async_to_sync() [2/3]
Union[ Callable[ [Union[Callable[_P, Coroutine[Any, Any, _R]], Callable[_P, Awaitable[_R]]]], Callable[_P, _R], ], Callable[_P, _R], ] asgiref.sync.async_to_sync (Optional[ Union[ Callable[_P, Coroutine[Any, Any, _R]], Callable[_P, Awaitable[_R]], ] ] awaitable = None, * , bool force_new_loop = False)
Definition at line 548 of file sync.py.
]:
    if awaitable is None:
        return lambda f: AsyncToSync(
            f,
            force_new_loop=force_new_loop,
        )
    return AsyncToSync(
        awaitable,
        force_new_loop=force_new_loop,
    )
@overload
async_to_sync() [3/3]
Callable[_P, _R] asgiref.sync.async_to_sync (Union[ Callable[_P, Coroutine[Any, Any, _R]], Callable[_P, Awaitable[_R]], ] awaitable, * , bool force_new_loop = False)
Definition at line 537 of file sync.py.
) -> Callable[_P, _R]:
    ...
markcoroutinefunction()
_F asgiref.sync.markcoroutinefunction (_F func)
Definition at line 67 of file sync.py.
    def markcoroutinefunction(func: _F) -> _F:
        func._is_coroutine = asyncio.coroutines._is_coroutine  # type: ignore
        return func
sync_to_async() [1/3]
Callable[[Callable[_P, _R]], Callable[_P, Coroutine[Any, Any, _R]]] asgiref.sync.sync_to_async (* , bool thread_sensitive = True, Optional["ThreadPoolExecutor"] executor = None)
Definition at line 576 of file sync.py.
) -> Callable[[Callable[_P, _R]], Callable[_P, Coroutine[Any, Any, _R]]]:
    ...
@overload
sync_to_async() [2/3]
Callable[_P, Coroutine[Any, Any, _R]] asgiref.sync.sync_to_async (Callable[_P, _R] func, * , bool thread_sensitive = True, Optional["ThreadPoolExecutor"] executor = None)
Definition at line 585 of file sync.py.
) -> Callable[_P, Coroutine[Any, Any, _R]]:
    ...
sync_to_async() [3/3]
Union[ Callable[[Callable[_P, _R]], Callable[_P, Coroutine[Any, Any, _R]]], Callable[_P, Coroutine[Any, Any, _R]], ] asgiref.sync.sync_to_async (Optional[Callable[_P, _R]] func = None, * , bool thread_sensitive = True, Optional["ThreadPoolExecutor"] executor = None)
Definition at line 594 of file sync.py.
]:
    if func is None:
        return lambda f: SyncToAsync(
            f,
            thread_sensitive=thread_sensitive,
            executor=executor,
        )
    return SyncToAsync(
        func,
        thread_sensitive=thread_sensitive,
        executor=executor,
    )
Variable Documentation
_F
asgiref.sync._F = TypeVar("_F", bound=Callable[..., Any]) protected
Definition at line 39 of file sync.py.
_P
asgiref.sync._P = ParamSpec("_P") protected
Definition at line 40 of file sync.py.
_R
asgiref.sync._R = TypeVar("_R") protected
Definition at line 41 of file sync.py.
iscoroutinefunction
asgiref.sync.iscoroutinefunction = inspect.iscoroutinefunction
Definition at line 62 of file sync.py.
Referenced by asgiref.sync.AsyncToSync.__init__(), and asgiref.sync.SyncToAsync.__init__().
markcoroutinefunction
Callable asgiref.sync.markcoroutinefunction = inspect.markcoroutinefunction
Definition at line 63 of file sync.py.