Read&Watch: pip._vendor.pkg_resources Namespace Reference
pip._vendor.pkg_resources Namespace Reference
Classes
class _LoaderProtocol
class _ReqExtras
class _ZipLoaderModule
class ContextualVersionConflict
class DefaultProvider
class DistInfoDistribution
class Distribution
class DistributionNotFound
class EggInfoDistribution
class EggMetadata
class EggProvider
class EmptyProvider
class EntryPoint
class Environment
class ExtractionError
class FileMetadata
class IMetadataProvider
class IResourceProvider
class MemoizedZipManifests
class NoDists
class NullProvider
class PathMetadata
class PEP440Warning
class PkgResourcesDeprecationWarning
class Requirement
class RequirementParseError
class ResolutionError
class ResourceManager
class UnknownExtra
class VersionConflict
class WorkingSet
class ZipManifests
class ZipProvider
Functions
_T _declare_state (str vartype, str varname, _T initial_value)
dict[str, Any] __getstate__ ()
dict[str, Any] __setstate__ (dict[str, Any] state)
_sget_dict (val)
_sset_dict (key, ob, state)
_sget_object (val)
_sset_object (key, ob, state)
get_supported_platform ()
register_loader_type (type[_ModuleLike] loader_type, _ProviderFactoryType provider_factory)
IResourceProvider get_provider (str moduleOrReq)
Distribution get_provider (Requirement moduleOrReq)
IResourceProvider|Distribution get_provider (str|Requirement moduleOrReq)
_macos_vers ()
_macos_arch (machine)
get_build_platform ()
compatible_platforms (str|None provided, str|None required)
_DistributionT get_distribution (_DistributionT dist)
Distribution get_distribution (_PkgReqType dist)
Distribution get_distribution (Distribution|_PkgReqType dist)
_ResolvedEntryPoint load_entry_point (_EPDistType dist, str group, str name)
dict[str, dict[str, EntryPoint]] get_entry_map (_EPDistType dist, None group=None)
dict[str, EntryPoint] get_entry_map (_EPDistType dist, str group)
get_entry_map (_EPDistType dist, str|None group=None)
get_entry_info (_EPDistType dist, str group, str name)
str get_default_cache ()
safe_name (str name)
safe_version (str version)
_forgiving_version (version)
_safe_segment (segment)
safe_extra (str extra)
to_filename (str name)
invalid_marker (str text)
bool evaluate_marker (str text, str|None extra=None)
_parents (path)
register_finder (type[_T] importer_type, _DistFinderType[_T] distribution_finder)
find_distributions (str path_item, bool only=False)
Iterator[Distribution] find_eggs_in_zip (zipimport.zipimporter importer, str path_item, bool only=False)
find_nothing (object|None importer, str|None path_item, bool|None only=False)
find_on_path (object|None importer, path_item, only=False)
dist_factory (path_item, entry, only)
safe_listdir (StrOrBytesPath path)
distributions_from_metadata (str path)
non_empty_lines (path)
resolve_egg_link (path)
register_namespace_handler (type[_T] importer_type, _NSHandlerType[_T] namespace_handler)
_handle_ns (packageName, path_item)
_rebuild_mod_path (orig_path, package_name, types.ModuleType module)
declare_namespace (str packageName)
fixup_namespace_packages (str path_item, str|None parent=None)
file_ns_handler (object importer, StrPath path_item, str packageName, types.ModuleType module)
null_ns_handler (object importer, str|None path_item, str|None packageName, _ModuleLike|None module)
str normalize_path (StrPath filename)
bytes normalize_path (BytesPath filename)
normalize_path (StrOrBytesPath filename)
_cygwin_patch (StrOrBytesPath filename)
str _normalize_cached (StrPath filename)
bytes _normalize_cached (BytesPath filename)
str|bytes _normalize_cached (StrOrBytesPath filename)
_normalize_cached (filename)
_is_egg_path (path)
_is_zip_egg (path)
_is_unpacked_egg (path)
_set_parent_ns (packageName)
_version_from_file (lines)
issue_warning (*args, **kw)
parse_requirements (_NestedStr strs)
_always_object (classes)
_AdapterT _find_adapter (Mapping[type, _AdapterT] registry, object ob)
ensure_directory (StrOrBytesPath path)
_bypass_ensure_directory (path)
Iterator[tuple[str|None, list[str]]] split_sections (_NestedStr s)
_mkstemp (*args, **kw)
str _read_utf8_with_fallback (str file, fallback_encoding=_LOCALE_ENCODING)
_call_aside (f, *args, **kwargs)
_initialize (g=globals())
_initialize_master_working_set ()
Variables
bool WRITE_SUPPORT = True
_T = TypeVar("_T")
_DistributionT = TypeVar("_DistributionT", bound="Distribution")
_NestedStr = Union[str, Iterable[Union[str, Iterable["_NestedStr"]]]]
_InstallerTypeT = Callable[["Requirement"], "_DistributionT"]
_InstallerType = Callable[["Requirement"], Union["Distribution", None]]
_PkgReqType = Union[str, "Requirement"]
_EPDistType = Union["Distribution", _PkgReqType]
_MetadataType = Union["IResourceProvider", None]
_ResolvedEntryPoint = Any
_ResourceStream = Any
_ModuleLike = Union[object, types.ModuleType]
_ProviderFactoryType = Callable[[Any], "IResourceProvider"]
_DistFinderType = Callable[[_T, str, bool], Iterable["Distribution"]]
_NSHandlerType = Callable[[_T, str, str, types.ModuleType], Union[str, None]]
_AdapterT
_PEP440_FALLBACK = re.compile(r"^v?(?P<safe>(?:[0-9]+!)?[0-9]+(?:\.[0-9]+)*)", re.I)
parse_version = _packaging_version.Version
dict _state_vars = {}
None _sget_none = lambda *args
str PY_MAJOR = '{}.{}'.format(*sys.version_info)
int EGG_DIST = 3
int BINARY_DIST = 2
int SOURCE_DIST = 1
int CHECKOUT_DIST = 0
int DEVELOP_DIST = -1
macosVersionString = re.compile(r"macosx-(\d+)\.(\d+)-(.*)")
darwinVersionString = re.compile(r"darwin-(\d+)\.(\d+)\.(\d+)-(.*)")
get_platform = get_build_platform
AvailableDistributions = Environment
empty_provider = EmptyProvider()
dict _namespace_handlers
dict _namespace_packages
MODULE = re.compile(r"\w+(\.\w+)*$").match
EGG_NAME
dict _distributionImpl
category
PEP440Warning
append
tuple _LOCALE_ENCODING = (3, 10) else None
resource_exists = __resource_manager.resource_exists
resource_isdir = __resource_manager.resource_isdir
resource_filename = __resource_manager.resource_filename
resource_stream = __resource_manager.resource_stream
resource_string = __resource_manager.resource_string
resource_listdir = __resource_manager.resource_listdir
set_extraction_path = __resource_manager.set_extraction_path
cleanup_resources = __resource_manager.cleanup_resources
working_set = WorkingSet()
require = working_set.require
iter_entry_points = working_set.iter_entry_points
add_activation_listener = working_set.subscribe
run_script = working_set.run_script
run_main = run_script
Detailed Description
Package resource API
--------------------
A resource is a logical file contained within a package, or a logical
subdirectory thereof.  The package resource API expects resource names
to have their path parts separated with ``/``, *not* whatever the local
path separator is.  Do not use os.path operations to manipulate resource
names being passed into the API.
The package resource API is designed to work with normal filesystem packages,
.egg files, and unpacked .egg files.  It can also work in a limited way with
.zip files and with custom PEP 302 loaders that support the ``get_data()``
method.
This module is deprecated. Users are directed to :mod:`importlib.resources`,
:mod:`importlib.metadata` and :pypi:`packaging` instead.
Function Documentation
__getstate__()
dict[str, Any] pip._vendor.pkg_resources.__getstate__ ()
Definition at line 164 of file __init__.py.
def __getstate__() -> dict[str, Any]:
    state = {}
    g = globals()
    for k, v in _state_vars.items():
        state[k] = g['_sget_' + v](g[k])
    return state
__setstate__()
dict[str, Any] pip._vendor.pkg_resources.__setstate__ (dict[str, Any] state)
Definition at line 172 of file __init__.py.
def __setstate__(state: dict[str, Any]) -> dict[str, Any]:
    g = globals()
    for k, v in state.items():
        g['_sset_' + _state_vars[k]](k, g[k], v)
    return state
_always_object()
pip._vendor.pkg_resources._always_object (classes) protected
Ensure object appears in the mro even
for old-style classes.
Definition at line 3480 of file __init__.py.
def _always_object(classes):
    """
    Ensure object appears in the mro even
    for old-style classes.
    """
    if object not in classes:
        return classes + (object,)
    return classes
_bypass_ensure_directory()
pip._vendor.pkg_resources._bypass_ensure_directory (path) protected
Sandbox-bypassing version of ensure_directory()
Definition at line 3507 of file __init__.py.
def _bypass_ensure_directory(path):
    """Sandbox-bypassing version of ensure_directory()"""
    if not WRITE_SUPPORT:
        raise OSError('"os.mkdir" not supported on this platform.')
    dirname, filename = split(path)
    if dirname and filename and not isdir(dirname):
        _bypass_ensure_directory(dirname)
        try:
            mkdir(dirname, 0o755)
        except FileExistsError:
            pass
_call_aside()
pip._vendor.pkg_resources._call_aside (f, * args, ** kwargs) protected
Definition at line 3606 of file __init__.py.
def _call_aside(f, *args, **kwargs):
    f(*args, **kwargs)
    return f
@_call_aside
_cygwin_patch()
pip._vendor.pkg_resources._cygwin_patch (StrOrBytesPath filename) protected
Contrary to POSIX 2008, on Cygwin, getcwd (3) contains
symlink components. Using
os.path.abspath() works around this limitation. A fix in os.getcwd()
would probably better, in Cygwin even more so, except
that this seems to be by design...
Definition at line 2608 of file __init__.py.
def _cygwin_patch(filename: StrOrBytesPath):  # pragma: nocover
    """
    Contrary to POSIX 2008, on Cygwin, getcwd (3) contains
    symlink components. Using
    os.path.abspath() works around this limitation. A fix in os.getcwd()
    would probably better, in Cygwin even more so, except
    that this seems to be by design...
    """
    return os.path.abspath(filename) if sys.platform == 'cygwin' else filename
_declare_state()
_T pip._vendor.pkg_resources._declare_state (str vartype, str varname, _T initial_value) protected
Definition at line 159 of file __init__.py.
def _declare_state(vartype: str, varname: str, initial_value: _T) -> _T:
    _state_vars[varname] = vartype
    return initial_value
_find_adapter()
_AdapterT pip._vendor.pkg_resources._find_adapter (Mapping[type, _AdapterT] registry, object ob) protected
Return an adapter factory for `ob` from `registry`
Definition at line 3490 of file __init__.py.
def _find_adapter(registry: Mapping[type, _AdapterT], ob: object) -> _AdapterT:
    """Return an adapter factory for `ob` from `registry`"""
    types = _always_object(inspect.getmro(getattr(ob, '__class__', type(ob))))
    for t in types:
        if t in registry:
            return registry[t]
    # _find_adapter would previously return None, and immediately be called.
    # So we're raising a TypeError to keep backward compatibility if anyone depended on that behaviour.
    raise TypeError(f"Could not find adapter for {registry} and {ob}")
Referenced by get_provider().
_forgiving_version()
pip._vendor.pkg_resources._forgiving_version (version) protected
Fallback when ``safe_version`` is not safe enough
>>> parse_version(_forgiving_version('0.23ubuntu1'))
<Version('0.23.dev0+sanitized.ubuntu1')>
>>> parse_version(_forgiving_version('0.23-'))
<Version('0.23.dev0+sanitized')>
>>> parse_version(_forgiving_version('0.-_'))
<Version('0.dev0+sanitized')>
>>> parse_version(_forgiving_version('42.+?1'))
<Version('42.dev0+sanitized.1')>
>>> parse_version(_forgiving_version('hello world'))
<Version('0.dev0+sanitized.hello.world')>
Definition at line 1555 of file __init__.py.
def _forgiving_version(version):
    """Fallback when ``safe_version`` is not safe enough
    >>> parse_version(_forgiving_version('0.23ubuntu1'))
    <Version('0.23.dev0+sanitized.ubuntu1')>
    >>> parse_version(_forgiving_version('0.23-'))
    <Version('0.23.dev0+sanitized')>
    >>> parse_version(_forgiving_version('0.-_'))
    <Version('0.dev0+sanitized')>
    >>> parse_version(_forgiving_version('42.+?1'))
    <Version('42.dev0+sanitized.1')>
    >>> parse_version(_forgiving_version('hello world'))
    <Version('0.dev0+sanitized.hello.world')>
    """
    version = version.replace(' ', '.')
    match = _PEP440_FALLBACK.search(version)
    if match:
        safe = match["safe"]
        rest = version[len(safe) :]
    else:
        safe = "0"
        rest = version
    local = f"sanitized.{_safe_segment(rest)}".strip(".")
    return f"{safe}.dev0+{local}"
_handle_ns()
pip._vendor.pkg_resources._handle_ns (packageName, path_item) protected
Ensure that named package includes a subpath of path_item (if needed)
Definition at line 2436 of file __init__.py.
def _handle_ns(packageName, path_item):
    """Ensure that named package includes a subpath of path_item (if needed)"""
    importer = get_importer(path_item)
    if importer is None:
        return None
    # use find_spec (PEP 451) and fall-back to find_module (PEP 302)
    try:
        spec = importer.find_spec(packageName)
    except AttributeError:
        # capture warnings due to #1111
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            loader = importer.find_module(packageName)
    else:
        loader = spec.loader if spec else None
    if loader is None:
        return None
    module = sys.modules.get(packageName)
    if module is None:
        module = sys.modules[packageName] = types.ModuleType(packageName)
        module.__path__ = []
        _set_parent_ns(packageName)
    elif not hasattr(module, '__path__'):
        raise TypeError("Not a package:", packageName)
    handler = _find_adapter(_namespace_handlers, importer)
    subpath = handler(importer, path_item, packageName, module)
    if subpath is not None:
        path = module.__path__
        path.append(subpath)
        importlib.import_module(packageName)
        _rebuild_mod_path(path, packageName, module)
    return subpath
_initialize()
pip._vendor.pkg_resources._initialize (g = globals()) protected
Definition at line 3612 of file __init__.py.
def _initialize(g=globals()):
    "Set up global resource manager (deliberately not state-saved)"
    manager = ResourceManager()
    g['_manager'] = manager
    g.update(
        (name, getattr(manager, name))
        for name in dir(manager)
        if not name.startswith('_')
    )
@_call_aside
_initialize_master_working_set()
pip._vendor.pkg_resources._initialize_master_working_set () protected
Prepare the master working set and make the ``require()``
API available.
This function has explicit effects on the global state
of pkg_resources. It is intended to be invoked once at
the initialization of this module.
Invocation by other packages is unsupported and done
at their own risk.
Definition at line 3624 of file __init__.py.
def _initialize_master_working_set():
    """
    Prepare the master working set and make the ``require()``
    API available.
    This function has explicit effects on the global state
    of pkg_resources. It is intended to be invoked once at
    the initialization of this module.
    Invocation by other packages is unsupported and done
    at their own risk.
    """
    working_set = _declare_state('object', 'working_set', WorkingSet._build_master())
    require = working_set.require
    iter_entry_points = working_set.iter_entry_points
    add_activation_listener = working_set.subscribe
    run_script = working_set.run_script
    # backward compatibility
    run_main = run_script
    # Activate all distributions already on sys.path with replace=False and
    # ensure that all distributions added to the working set in the future
    # (e.g. by calling ``require()``) will get activated as well,
    # with higher priority (replace=True).
    tuple(dist.activate(replace=False) for dist in working_set)
    add_activation_listener(
        lambda dist: dist.activate(replace=True),
        existing=False,
    )
    working_set.entries = []
    # match order
    list(map(working_set.add_entry, sys.path))
    globals().update(locals())
_is_egg_path()
pip._vendor.pkg_resources._is_egg_path (path) protected
Determine if given path appears to be an egg.
Definition at line 2634 of file __init__.py.
def _is_egg_path(path):
    """
    Determine if given path appears to be an egg.
    """
    return _is_zip_egg(path) or _is_unpacked_egg(path)
_is_unpacked_egg()
pip._vendor.pkg_resources._is_unpacked_egg (path) protected
Determine if given path appears to be an unpacked egg.
Definition at line 2649 of file __init__.py.
def _is_unpacked_egg(path):
    """
    Determine if given path appears to be an unpacked egg.
    """
    return path.lower().endswith('.egg') and os.path.isfile(
        os.path.join(path, 'EGG-INFO', 'PKG-INFO')
    )
_is_zip_egg()
pip._vendor.pkg_resources._is_zip_egg (path) protected
Definition at line 2641 of file __init__.py.
def _is_zip_egg(path):
    return (
        path.lower().endswith('.egg')
        and os.path.isfile(path)
        and zipfile.is_zipfile(path)
    )
_macos_arch()
pip._vendor.pkg_resources._macos_arch (machine) protected
Definition at line 447 of file __init__.py.
def _macos_arch(machine):
    return {'PowerPC': 'ppc', 'Power_Macintosh': 'ppc'}.get(machine, machine)
Referenced by get_build_platform().
_macos_vers()
pip._vendor.pkg_resources._macos_vers () protected
Definition at line 434 of file __init__.py.
def _macos_vers():
    version = platform.mac_ver()[0]
    # fallback for MacPorts
    if version == '':
        plist = '/System/Library/CoreServices/SystemVersion.plist'
        if os.path.exists(plist):
            with open(plist, 'rb') as fh:
                plist_content = plistlib.load(fh)
            if 'ProductVersion' in plist_content:
                version = plist_content['ProductVersion']
    return version.split('.')
Referenced by get_build_platform(), and get_supported_platform().
_mkstemp()
pip._vendor.pkg_resources._mkstemp (* args, ** kw) protected
Definition at line 3546 of file __init__.py.
def _mkstemp(*args, **kw):
    old_open = os.open
    try:
        # temporarily bypass sandboxing
        os.open = os_open
        return tempfile.mkstemp(*args, **kw)
    finally:
        # and then put it back
        os.open = old_open
# Silence the PEP440Warning by default, so that end users don't get hit by it
# randomly just because they use pkg_resources. We want to append the rule
# because we want earlier uses of filterwarnings to take precedence over this
# one.
_normalize_cached() [1/4]
bytes pip._vendor.pkg_resources._normalize_cached (BytesPath filename) protected
Definition at line 2625 of file __init__.py.
    def _normalize_cached(filename: BytesPath) -> bytes: ...
_normalize_cached() [2/4]
pip._vendor.pkg_resources._normalize_cached (filename) protected
Definition at line 2630 of file __init__.py.
    def _normalize_cached(filename):
        return normalize_path(filename)
_normalize_cached() [3/4]
str | bytes pip._vendor.pkg_resources._normalize_cached (StrOrBytesPath filename) protected
Definition at line 2626 of file __init__.py.
    def _normalize_cached(filename: StrOrBytesPath) -> str | bytes: ...
_normalize_cached() [4/4]
str pip._vendor.pkg_resources._normalize_cached (StrPath filename) protected
Definition at line 2623 of file __init__.py.
    def _normalize_cached(filename: StrPath) -> str: ...
_parents()
pip._vendor.pkg_resources._parents (path) protected
yield all parents of path including path
Definition at line 1839 of file __init__.py.
def _parents(path):
    """
    yield all parents of path including path
    """
    last = None
    while path != last:
        yield path
        last = path
        path, _ = os.path.split(path)
_read_utf8_with_fallback()
str pip._vendor.pkg_resources._read_utf8_with_fallback (str file, fallback_encoding = _LOCALE_ENCODING) protected
See setuptools.unicode_utils._read_utf8_with_fallback
Definition at line 3577 of file __init__.py.
def _read_utf8_with_fallback(file: str, fallback_encoding=_LOCALE_ENCODING) -> str:
    """See setuptools.unicode_utils._read_utf8_with_fallback"""
    try:
        with open(file, "r", encoding="utf-8") as f:
            return f.read()
    except UnicodeDecodeError:  # pragma: no cover
        msg = f"""\
        ********************************************************************************
        `encoding="utf-8"` fails with {file!r}, trying `encoding={fallback_encoding!r}`.
        This fallback behaviour is considered **deprecated** and future versions of
        `setuptools/pkg_resources` may not implement it.
        Please encode {file!r} with "utf-8" to ensure future builds will succeed.
        If this file was produced by `setuptools` itself, cleaning up the cached files
        and re-building/re-installing the package with a newer version of `setuptools`
        (e.g. by updating `build-system.requires` in its `pyproject.toml`)
        might solve the problem.
        ********************************************************************************
        """
        # TODO: Add a deadline?
        #       See comment in setuptools.unicode_utils._Utf8EncodingNeeded
        warnings.warn(msg, PkgResourcesDeprecationWarning, stacklevel=2)
        with open(file, "r", encoding=fallback_encoding) as f:
            return f.read()
# from jaraco.functools 1.3
_rebuild_mod_path()
pip._vendor.pkg_resources._rebuild_mod_path (orig_path, package_name, types.ModuleType module) protected
Rebuild module.__path__ ensuring that all entries are ordered
corresponding to their sys.path order
Definition at line 2473 of file __init__.py.
def _rebuild_mod_path(orig_path, package_name, module: types.ModuleType):
    """
    Rebuild module.__path__ ensuring that all entries are ordered
    corresponding to their sys.path order
    """
    sys_path = [_normalize_cached(p) for p in sys.path]
    def safe_sys_path_index(entry):
        """
        Workaround for #520 and #513.
        """
        try:
            return sys_path.index(entry)
        except ValueError:
            return float('inf')
    def position_in_sys_path(path):
        """
        Return the ordinal of the path based on its position in sys.path
        """
        path_parts = path.split(os.sep)
        module_parts = package_name.count('.') + 1
        parts = path_parts[:-module_parts]
        return safe_sys_path_index(_normalize_cached(os.sep.join(parts)))
    new_path = sorted(orig_path, key=position_in_sys_path)
    new_path = [_normalize_cached(p) for p in new_path]
    if isinstance(module.__path__, list):
        module.__path__[:] = new_path
    else:
        module.__path__ = new_path
_safe_segment()
pip._vendor.pkg_resources._safe_segment (segment) protected
Convert an arbitrary string into a safe segment
Definition at line 1580 of file __init__.py.
def _safe_segment(segment):
    """Convert an arbitrary string into a safe segment"""
    segment = re.sub('[^A-Za-z0-9.]+', '-', segment)
    segment = re.sub('-[^A-Za-z0-9]+', '-', segment)
    return re.sub(r'\.[^A-Za-z0-9]+', '.', segment).strip(".-")
_set_parent_ns()
pip._vendor.pkg_resources._set_parent_ns (packageName) protected
Definition at line 2658 of file __init__.py.
def _set_parent_ns(packageName):
    parts = packageName.split('.')
    name = parts.pop()
    if parts:
        parent = '.'.join(parts)
        setattr(sys.modules[parent], name, sys.modules[packageName])
_sget_dict()
pip._vendor.pkg_resources._sget_dict (val) protected
Definition at line 179 of file __init__.py.
def _sget_dict(val):
    return val.copy()
_sget_object()
pip._vendor.pkg_resources._sget_object (val) protected
Definition at line 188 of file __init__.py.
def _sget_object(val):
    return val.__getstate__()
_sset_dict()
pip._vendor.pkg_resources._sset_dict (key, ob, state) protected
Definition at line 183 of file __init__.py.
def _sset_dict(key, ob, state):
    ob.clear()
    ob.update(state)
_sset_object()
pip._vendor.pkg_resources._sset_object (key, ob, state) protected
Definition at line 192 of file __init__.py.
def _sset_object(key, ob, state):
    ob.__setstate__(state)
_version_from_file()
pip._vendor.pkg_resources._version_from_file (lines) protected
Given an iterable of lines from a Metadata file, return
the value of the Version field, if present, or None otherwise.
Definition at line 2856 of file __init__.py.
def _version_from_file(lines):
    """
    Given an iterable of lines from a Metadata file, return
    the value of the Version field, if present, or None otherwise.
    """
    def is_version_line(line):
        return line.lower().startswith('version:')
    version_lines = filter(is_version_line, lines)
    line = next(iter(version_lines), '')
    _, _, value = line.partition(':')
    return safe_version(value.strip()) or None
compatible_platforms()
pip._vendor.pkg_resources.compatible_platforms (str | None provided, str | None required)
Can code for the `provided` platform run on the `required` platform?
Returns true if either platform is ``None``, or the platforms are equal.
XXX Needs compatibility checks for Linux and other unixy OSes.
Definition at line 482 of file __init__.py.
def compatible_platforms(provided: str | None, required: str | None):
    """Can code for the `provided` platform run on the `required` platform?
    Returns true if either platform is ``None``, or the platforms are equal.
    XXX Needs compatibility checks for Linux and other unixy OSes.
    """
    if provided is None or required is None or provided == required:
        # easy case
        return True
    # macOS special cases
    reqMac = macosVersionString.match(required)
    if reqMac:
        provMac = macosVersionString.match(provided)
        # is this a Mac package?
        if not provMac:
            # this is backwards compatibility for packages built before
            # setuptools 0.6. All packages built after this point will
            # use the new macOS designation.
            provDarwin = darwinVersionString.match(provided)
            if provDarwin:
                dversion = int(provDarwin.group(1))
                macosversion = "%s.%s" % (reqMac.group(1), reqMac.group(2))
                if (
                    dversion == 7
                    and macosversion >= "10.3"
                    or dversion == 8
                    and macosversion >= "10.4"
                ):
                    return True
            # egg isn't macOS or legacy darwin
            return False
        # are they the same major version and machine type?
        if provMac.group(1) != reqMac.group(1) or provMac.group(3) != reqMac.group(3):
            return False
        # is the required OS major update >= the provided one?
        if int(provMac.group(2)) > int(reqMac.group(2)):
            return False
        return True
    # XXX Linux and other platforms' special cases should go here
    return False
@overload
declare_namespace()
pip._vendor.pkg_resources.declare_namespace (str packageName)
Declare that package 'packageName' is a namespace package
Definition at line 2507 of file __init__.py.
def declare_namespace(packageName: str):
    """Declare that package 'packageName' is a namespace package"""
    msg = (
        f"Deprecated call to `pkg_resources.declare_namespace({packageName!r})`.\n"
        "Implementing implicit namespace packages (as specified in PEP 420) "
        "is preferred to `pkg_resources.declare_namespace`. "
        "See https://setuptools.pypa.io/en/latest/references/"
        "keywords.html#keyword-namespace-packages"
    )
    warnings.warn(msg, DeprecationWarning, stacklevel=2)
    _imp.acquire_lock()
    try:
        if packageName in _namespace_packages:
            return
        path: MutableSequence[str] = sys.path
        parent, _, _ = packageName.rpartition('.')
        if parent:
            declare_namespace(parent)
            if parent not in _namespace_packages:
                __import__(parent)
            try:
                path = sys.modules[parent].__path__
            except AttributeError as e:
                raise TypeError("Not a package:", parent) from e
        # Track what packages are namespaces, so when new path items are added,
        # they can be updated
        _namespace_packages.setdefault(parent or None, []).append(packageName)
        _namespace_packages.setdefault(packageName, [])
        for path_item in path:
            # Ensure all the parent's path items are reflected in the child,
            # if they apply
            _handle_ns(packageName, path_item)
    finally:
        _imp.release_lock()
dist_factory()
pip._vendor.pkg_resources.dist_factory (path_item, entry, only)
Return a dist_factory for the given entry.
Definition at line 2311 of file __init__.py.
def dist_factory(path_item, entry, only):
    """Return a dist_factory for the given entry."""
    lower = entry.lower()
    is_egg_info = lower.endswith('.egg-info')
    is_dist_info = lower.endswith('.dist-info') and os.path.isdir(
        os.path.join(path_item, entry)
    )
    is_meta = is_egg_info or is_dist_info
    return (
        distributions_from_metadata
        if is_meta
        else find_distributions
        if not only and _is_egg_path(entry)
        else resolve_egg_link
        if not only and lower.endswith('.egg-link')
        else NoDists()
    )
distributions_from_metadata()
pip._vendor.pkg_resources.distributions_from_metadata (str path)
Definition at line 2362 of file __init__.py.
def distributions_from_metadata(path: str):
    root = os.path.dirname(path)
    if os.path.isdir(path):
        if len(os.listdir(path)) == 0:
            # empty metadata dir; skip
            return
        metadata: _MetadataType = PathMetadata(root, path)
    else:
        metadata = FileMetadata(path)
    entry = os.path.basename(path)
    yield Distribution.from_location(
        root,
        entry,
        metadata,
        precedence=DEVELOP_DIST,
    )
ensure_directory()
pip._vendor.pkg_resources.ensure_directory (StrOrBytesPath path)
Ensure that the parent directory of `path` exists
Definition at line 3501 of file __init__.py.
def ensure_directory(path: StrOrBytesPath):
    """Ensure that the parent directory of `path` exists"""
    dirname = os.path.dirname(path)
    os.makedirs(dirname, exist_ok=True)
evaluate_marker()
bool pip._vendor.pkg_resources.evaluate_marker (str text, str | None extra = None)
Evaluate a PEP 508 environment marker.
Return a boolean indicating the marker result in this environment.
Raise SyntaxError if marker is invalid.
This implementation uses the 'pyparsing' module.
Definition at line 1618 of file __init__.py.
def evaluate_marker(text: str, extra: str | None = None) -> bool:
    """
    Evaluate a PEP 508 environment marker.
    Return a boolean indicating the marker result in this environment.
    Raise SyntaxError if marker is invalid.
    This implementation uses the 'pyparsing' module.
    """
    try:
        marker = _packaging_markers.Marker(text)
        return marker.evaluate()
    except _packaging_markers.InvalidMarker as e:
        raise SyntaxError(e) from e
file_ns_handler()
pip._vendor.pkg_resources.file_ns_handler (object importer, StrPath path_item, str packageName, types.ModuleType module)
Compute an ns-package subpath for a filesystem or zipfile importer
Definition at line 2562 of file __init__.py.
):
    """Compute an ns-package subpath for a filesystem or zipfile importer"""
    subpath = os.path.join(path_item, packageName.split('.')[-1])
    normalized = _normalize_cached(subpath)
    for item in module.__path__:
        if _normalize_cached(item) == normalized:
            break
    else:
        # Only return the path if it's not already there
        return subpath
find_distributions()
pip._vendor.pkg_resources.find_distributions (str path_item, bool only = False)
Yield distributions accessible via `path_item`
Definition at line 2244 of file __init__.py.
def find_distributions(path_item: str, only: bool = False):
    """Yield distributions accessible via `path_item`"""
    importer = get_importer(path_item)
    finder = _find_adapter(_distribution_finders, importer)
    return finder(importer, path_item, only)
find_eggs_in_zip()
Iterator[Distribution] pip._vendor.pkg_resources.find_eggs_in_zip (zipimport.zipimporter importer, str path_item, bool only = False)
Find eggs in zip files; possibly multiple nested eggs.
Definition at line 2251 of file __init__.py.
) -> Iterator[Distribution]:
    """
    Find eggs in zip files; possibly multiple nested eggs.
    """
    if importer.archive.endswith('.whl'):
        # wheels are not supported with this finder
        # they don't have PKG-INFO metadata, and won't ever contain eggs
        return
    metadata = EggMetadata(importer)
    if metadata.has_metadata('PKG-INFO'):
        yield Distribution.from_filename(path_item, metadata=metadata)
    if only:
        # don't yield nested distros
        return
    for subitem in metadata.resource_listdir(''):
        if _is_egg_path(subitem):
            subpath = os.path.join(path_item, subitem)
            dists = find_eggs_in_zip(zipimport.zipimporter(subpath), subpath)
            yield from dists
        elif subitem.lower().endswith(('.dist-info', '.egg-info')):
            subpath = os.path.join(path_item, subitem)
            submeta = EggMetadata(zipimport.zipimporter(subpath))
            submeta.egg_info = subpath
            yield Distribution.from_location(path_item, subitem, submeta)
find_nothing()
pip._vendor.pkg_resources.find_nothing (object | None importer, str | None path_item, bool | None only = False)
Definition at line 2282 of file __init__.py.
):
    return ()
find_on_path()
pip._vendor.pkg_resources.find_on_path (object | None importer, path_item, only = False)
Yield distributions accessible on a sys.path directory
Definition at line 2291 of file __init__.py.
def find_on_path(importer: object | None, path_item, only=False):
    """Yield distributions accessible on a sys.path directory"""
    path_item = _normalize_cached(path_item)
    if _is_unpacked_egg(path_item):
        yield Distribution.from_filename(
            path_item,
            metadata=PathMetadata(path_item, os.path.join(path_item, 'EGG-INFO')),
        )
        return
    entries = (os.path.join(path_item, child) for child in safe_listdir(path_item))
    # scan for .egg and .egg-info in directory
    for entry in sorted(entries):
        fullpath = os.path.join(path_item, entry)
        factory = dist_factory(path_item, entry, only)
        yield from factory(fullpath)
fixup_namespace_packages()
pip._vendor.pkg_resources.fixup_namespace_packages (str path_item, str | None parent = None)
Ensure that previously-declared namespace packages include path_item
Definition at line 2550 of file __init__.py.
def fixup_namespace_packages(path_item: str, parent: str | None = None):
    """Ensure that previously-declared namespace packages include path_item"""
    _imp.acquire_lock()
    try:
        for package in _namespace_packages.get(parent, ()):
            subpath = _handle_ns(package, path_item)
            if subpath:
                fixup_namespace_packages(subpath, package)
    finally:
        _imp.release_lock()
get_build_platform()
pip._vendor.pkg_resources.get_build_platform ()
Return this platform's string for platform-specific distributions
XXX Currently this is the same as ``distutils.util.get_platform()``, but it
needs some hacks for Linux and macOS.
Definition at line 451 of file __init__.py.
def get_build_platform():
    """Return this platform's string for platform-specific distributions
    XXX Currently this is the same as ``distutils.util.get_platform()``, but it
    needs some hacks for Linux and macOS.
    """
    from sysconfig import get_platform
    plat = get_platform()
    if sys.platform == "darwin" and not plat.startswith('macosx-'):
        try:
            version = _macos_vers()
            machine = os.uname()[4].replace(" ", "_")
            return "macosx-%d.%d-%s" % (
                int(version[0]),
                int(version[1]),
                _macos_arch(machine),
            )
        except ValueError:
            # if someone is running a non-Mac darwin system, this will fall
            # through to the default implementation
            pass
    return plat
References _macos_arch(), _macos_vers(), and get_platform.
Referenced by get_supported_platform().
get_default_cache()
str pip._vendor.pkg_resources.get_default_cache ()
Return the ``PYTHON_EGG_CACHE`` environment variable
or a platform-relevant user cache dir for an app
named "Python-Eggs".
Definition at line 1526 of file __init__.py.
def get_default_cache() -> str:
    """
    Return the ``PYTHON_EGG_CACHE`` environment variable
    or a platform-relevant user cache dir for an app
    named "Python-Eggs".
    """
    return os.environ.get('PYTHON_EGG_CACHE') or _user_cache_dir(appname='Python-Eggs')
get_distribution() [1/3]
_DistributionT pip._vendor.pkg_resources.get_distribution (_DistributionT dist)
Definition at line 532 of file __init__.py.
def get_distribution(dist: _DistributionT) -> _DistributionT: ...
@overload
get_distribution() [2/3]
Distribution pip._vendor.pkg_resources.get_distribution (_PkgReqType dist)
Definition at line 534 of file __init__.py.
def get_distribution(dist: _PkgReqType) -> Distribution: ...
get_distribution() [3/3]
Distribution pip._vendor.pkg_resources.get_distribution (Distribution | _PkgReqType dist)
Return a current distribution object for a Requirement or string
Definition at line 535 of file __init__.py.
def get_distribution(dist: Distribution | _PkgReqType) -> Distribution:
    """Return a current distribution object for a Requirement or string"""
    if isinstance(dist, str):
        dist = Requirement.parse(dist)
    if isinstance(dist, Requirement):
        # Bad type narrowing, dist has to be a Requirement here, so get_provider has to return Distribution
        dist = get_provider(dist)  # type: ignore[assignment]
    if not isinstance(dist, Distribution):
        raise TypeError("Expected str, Requirement, or Distribution", dist)
    return dist
References get_provider().
get_entry_info()
pip._vendor.pkg_resources.get_entry_info (_EPDistType dist, str group, str name)
Return the EntryPoint object for `group`+`name`, or ``None``
Definition at line 563 of file __init__.py.
def get_entry_info(dist: _EPDistType, group: str, name: str):
    """Return the EntryPoint object for `group`+`name`, or ``None``"""
    return get_distribution(dist).get_entry_info(group, name)
get_entry_map() [1/3]
dict[str, dict[str, EntryPoint]] pip._vendor.pkg_resources.get_entry_map (_EPDistType dist, None group = None)
Definition at line 553 of file __init__.py.
) -> dict[str, dict[str, EntryPoint]]: ...
@overload
get_entry_map() [2/3]
dict[str, EntryPoint] pip._vendor.pkg_resources.get_entry_map (_EPDistType dist, str group)
Definition at line 557 of file __init__.py.
def get_entry_map(dist: _EPDistType, group: str) -> dict[str, EntryPoint]: ...
get_entry_map() [3/3]
pip._vendor.pkg_resources.get_entry_map (_EPDistType dist, str | None group = None)
Return the entry point map for `group`, or the full entry map
Definition at line 558 of file __init__.py.
def get_entry_map(dist: _EPDistType, group: str | None = None):
    """Return the entry point map for `group`, or the full entry map"""
    return get_distribution(dist).get_entry_map(group)
get_provider() [1/3]
Distribution pip._vendor.pkg_resources.get_provider (Requirement moduleOrReq)
Definition at line 419 of file __init__.py.
def get_provider(moduleOrReq: Requirement) -> Distribution: ...
get_provider() [2/3]
IResourceProvider pip._vendor.pkg_resources.get_provider (str moduleOrReq)
Definition at line 417 of file __init__.py.
def get_provider(moduleOrReq: str) -> IResourceProvider: ...
@overload
Referenced by get_distribution().
get_provider() [3/3]
IResourceProvider | Distribution pip._vendor.pkg_resources.get_provider (str | Requirement moduleOrReq)
Return an IResourceProvider for the named module or requirement
Definition at line 420 of file __init__.py.
def get_provider(moduleOrReq: str | Requirement) -> IResourceProvider | Distribution:
    """Return an IResourceProvider for the named module or requirement"""
    if isinstance(moduleOrReq, Requirement):
        return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
    try:
        module = sys.modules[moduleOrReq]
    except KeyError:
        __import__(moduleOrReq)
        module = sys.modules[moduleOrReq]
    loader = getattr(module, '__loader__', None)
    return _find_adapter(_provider_factories, loader)(module)
@functools.lru_cache(maxsize=None)
References _find_adapter(), and require.
get_supported_platform()
pip._vendor.pkg_resources.get_supported_platform ()
Return this platform's maximum compatible version.
distutils.util.get_platform() normally reports the minimum version
of macOS that would be required to *use* extensions produced by
distutils.  But what we want when checking compatibility is to know the
version of macOS that we are *running*.  To allow usage of packages that
explicitly require a newer version of macOS, we must also know the
current version of the OS.
If this condition occurs for any other platform with a version in its
platform strings, this function should be extended accordingly.
Definition at line 199 of file __init__.py.
def get_supported_platform():
    """Return this platform's maximum compatible version.
    distutils.util.get_platform() normally reports the minimum version
    of macOS that would be required to *use* extensions produced by
    distutils.  But what we want when checking compatibility is to know the
    version of macOS that we are *running*.  To allow usage of packages that
    explicitly require a newer version of macOS, we must also know the
    current version of the OS.
    If this condition occurs for any other platform with a version in its
    platform strings, this function should be extended accordingly.
    """
    plat = get_build_platform()
    m = macosVersionString.match(plat)
    if m is not None and sys.platform == "darwin":
        try:
            plat = 'macosx-%s-%s' % ('.'.join(_macos_vers()[:2]), m.group(3))
        except ValueError:
            # not macOS
            pass
    return plat
References _macos_vers(), and get_build_platform().
invalid_marker()
pip._vendor.pkg_resources.invalid_marker (str text)
Validate text as a PEP 508 environment marker; return an exception
if invalid or False otherwise.
Definition at line 1604 of file __init__.py.
def invalid_marker(text: str):
    """
    Validate text as a PEP 508 environment marker; return an exception
    if invalid or False otherwise.
    """
    try:
        evaluate_marker(text)
    except SyntaxError as e:
        e.filename = None
        e.lineno = None
        return e
    return False
issue_warning()
pip._vendor.pkg_resources.issue_warning (* args, ** kw)
Definition at line 3405 of file __init__.py.
def issue_warning(*args, **kw):
    level = 1
    g = globals()
    try:
        # find the first stack frame that is *not* code in
        # the pkg_resources module, to use for the warning
        while sys._getframe(level).f_globals is g:
            level += 1
    except ValueError:
        pass
    warnings.warn(stacklevel=level + 1, *args, **kw)
load_entry_point()
_ResolvedEntryPoint pip._vendor.pkg_resources.load_entry_point (_EPDistType dist, str group, str name)
Return `name` entry point of `group` for `dist` or raise ImportError
Definition at line 547 of file __init__.py.
def load_entry_point(dist: _EPDistType, group: str, name: str) -> _ResolvedEntryPoint:
    """Return `name` entry point of `group` for `dist` or raise ImportError"""
    return get_distribution(dist).load_entry_point(group, name)
@overload
non_empty_lines()
pip._vendor.pkg_resources.non_empty_lines (path)
Yield non-empty lines from file at path
Definition at line 2380 of file __init__.py.
def non_empty_lines(path):
    """
    Yield non-empty lines from file at path
    """
    for line in _read_utf8_with_fallback(path).splitlines():
        line = line.strip()
        if line:
            yield line
normalize_path() [1/3]
bytes pip._vendor.pkg_resources.normalize_path (BytesPath filename)
Definition at line 2602 of file __init__.py.
def normalize_path(filename: BytesPath) -> bytes: ...
normalize_path() [2/3]
pip._vendor.pkg_resources.normalize_path (StrOrBytesPath filename)
Normalize a file/dir name for comparison purposes
Definition at line 2603 of file __init__.py.
def normalize_path(filename: StrOrBytesPath):
    """Normalize a file/dir name for comparison purposes"""
    return os.path.normcase(os.path.realpath(os.path.normpath(_cygwin_patch(filename))))
normalize_path() [3/3]
str pip._vendor.pkg_resources.normalize_path (StrPath filename)
Definition at line 2600 of file __init__.py.
def normalize_path(filename: StrPath) -> str: ...
@overload
null_ns_handler()
pip._vendor.pkg_resources.null_ns_handler (object importer, str | None path_item, str | None packageName, _ModuleLike | None module)
Definition at line 2587 of file __init__.py.
):
    return None
parse_requirements()
pip._vendor.pkg_resources.parse_requirements (_NestedStr strs)
Yield ``Requirement`` objects for each specification in `strs`.
`strs` must be a string, or a (possibly-nested) iterable thereof.
Definition at line 3418 of file __init__.py.
def parse_requirements(strs: _NestedStr):
    """
    Yield ``Requirement`` objects for each specification in `strs`.
    `strs` must be a string, or a (possibly-nested) iterable thereof.
    """
    return map(Requirement, join_continuation(map(drop_comment, yield_lines(strs))))
register_finder()
pip._vendor.pkg_resources.register_finder (type[_T] importer_type, _DistFinderType[_T] distribution_finder)
Register `distribution_finder` to find distributions in sys.path items
`importer_type` is the type or class of a PEP 302 "Importer" (sys.path item
handler), and `distribution_finder` is a callable that, passed a path
item and the importer instance, yields ``Distribution`` instances found on
that path item.  See ``pkg_resources.find_on_path`` for an example.
Definition at line 2234 of file __init__.py.
def register_finder(importer_type: type[_T], distribution_finder: _DistFinderType[_T]):
    """Register `distribution_finder` to find distributions in sys.path items
    `importer_type` is the type or class of a PEP 302 "Importer" (sys.path item
    handler), and `distribution_finder` is a callable that, passed a path
    item and the importer instance, yields ``Distribution`` instances found on
    that path item.  See ``pkg_resources.find_on_path`` for an example."""
    _distribution_finders[importer_type] = distribution_finder
register_loader_type()
pip._vendor.pkg_resources.register_loader_type (type[_ModuleLike] loader_type, _ProviderFactoryType provider_factory)
Register `provider_factory` to make providers for `loader_type`
`loader_type` is the type or class of a PEP 302 ``module.__loader__``,
and `provider_factory` is a function that, passed a *module* object,
returns an ``IResourceProvider`` for that module.
Definition at line 404 of file __init__.py.
):
    """Register `provider_factory` to make providers for `loader_type`
    `loader_type` is the type or class of a PEP 302 ``module.__loader__``,
    and `provider_factory` is a function that, passed a *module* object,
    returns an ``IResourceProvider`` for that module.
    """
    _provider_factories[loader_type] = provider_factory
@overload
register_namespace_handler()
pip._vendor.pkg_resources.register_namespace_handler (type[_T] importer_type, _NSHandlerType[_T] namespace_handler)
Register `namespace_handler` to declare namespace packages
`importer_type` is the type or class of a PEP 302 "Importer" (sys.path item
handler), and `namespace_handler` is a callable like this::
    def namespace_handler(importer, path_entry, moduleName, module):
        # return a path_entry to use for child packages
Namespace handlers are only called if the importer object has already
agreed that it can handle the relevant path item, and they should only
return a subpath if the module __path__ does not already contain an
equivalent subpath.  For an example namespace handler, see
``pkg_resources.file_ns_handler``.
Definition at line 2416 of file __init__.py.
):
    """Register `namespace_handler` to declare namespace packages
    `importer_type` is the type or class of a PEP 302 "Importer" (sys.path item
    handler), and `namespace_handler` is a callable like this::
        def namespace_handler(importer, path_entry, moduleName, module):
            # return a path_entry to use for child packages
    Namespace handlers are only called if the importer object has already
    agreed that it can handle the relevant path item, and they should only
    return a subpath if the module __path__ does not already contain an
    equivalent subpath.  For an example namespace handler, see
    ``pkg_resources.file_ns_handler``.
    """
    _namespace_handlers[importer_type] = namespace_handler
resolve_egg_link()
pip._vendor.pkg_resources.resolve_egg_link (path)
Given a path to an .egg-link, resolve distributions
present in the referenced path.
Definition at line 2390 of file __init__.py.
def resolve_egg_link(path):
    """
    Given a path to an .egg-link, resolve distributions
    present in the referenced path.
    """
    referenced_paths = non_empty_lines(path)
    resolved_paths = (
        os.path.join(os.path.dirname(path), ref) for ref in referenced_paths
    )
    dist_groups = map(find_distributions, resolved_paths)
    return next(dist_groups, ())
safe_extra()
pip._vendor.pkg_resources.safe_extra (str extra)
Convert an arbitrary string to a standard 'extra' name
Any runs of non-alphanumeric characters are replaced with a single '_',
and the result is always lowercased.
Definition at line 1587 of file __init__.py.
def safe_extra(extra: str):
    """Convert an arbitrary string to a standard 'extra' name
    Any runs of non-alphanumeric characters are replaced with a single '_',
    and the result is always lowercased.
    """
    return re.sub('[^A-Za-z0-9.-]+', '_', extra).lower()
safe_listdir()
pip._vendor.pkg_resources.safe_listdir (StrOrBytesPath path)
Attempt to list contents of path, but suppress some exceptions.
Definition at line 2346 of file __init__.py.
def safe_listdir(path: StrOrBytesPath):
    """
    Attempt to list contents of path, but suppress some exceptions.
    """
    try:
        return os.listdir(path)
    except (PermissionError, NotADirectoryError):
        pass
    except OSError as e:
        # Ignore the directory if does not exist, not a directory or
        # permission denied
        if e.errno not in (errno.ENOTDIR, errno.EACCES, errno.ENOENT):
            raise
    return ()
safe_name()
pip._vendor.pkg_resources.safe_name (str name)
Convert an arbitrary string to a standard distribution name
Any runs of non-alphanumeric/. characters are replaced with a single '-'.
Definition at line 1535 of file __init__.py.
def safe_name(name: str):
    """Convert an arbitrary string to a standard distribution name
    Any runs of non-alphanumeric/. characters are replaced with a single '-'.
    """
    return re.sub('[^A-Za-z0-9.]+', '-', name)
safe_version()
pip._vendor.pkg_resources.safe_version (str version)
Convert an arbitrary string to a standard version string
Definition at line 1543 of file __init__.py.
def safe_version(version: str):
    """
    Convert an arbitrary string to a standard version string
    """
    try:
        # normalize the version
        return str(_packaging_version.Version(version))
    except _packaging_version.InvalidVersion:
        version = version.replace(' ', '.')
        return re.sub('[^A-Za-z0-9.]+', '-', version)
split_sections()
Iterator[tuple[str | None, list[str]]] pip._vendor.pkg_resources.split_sections (_NestedStr s)
Split a string or iterable thereof into (section, content) pairs
Each ``section`` is a stripped version of the section header ("[section]")
and each ``content`` is a list of stripped lines excluding blank lines and
comment-only lines.  If there are any such lines before the first section
header, they're returned in a first ``section`` of ``None``.
Definition at line 3520 of file __init__.py.
def split_sections(s: _NestedStr) -> Iterator[tuple[str | None, list[str]]]:
    """Split a string or iterable thereof into (section, content) pairs
    Each ``section`` is a stripped version of the section header ("[section]")
    and each ``content`` is a list of stripped lines excluding blank lines and
    comment-only lines.  If there are any such lines before the first section
    header, they're returned in a first ``section`` of ``None``.
    """
    section = None
    content = []
    for line in yield_lines(s):
        if line.startswith("["):
            if line.endswith("]"):
                if section or content:
                    yield section, content
                section = line[1:-1].strip()
                content = []
            else:
                raise ValueError("Invalid section heading", line)
        else:
            content.append(line)
    # wrap up last segment
    yield section, content
to_filename()
pip._vendor.pkg_resources.to_filename (str name)
Convert a project or version name to its filename-escaped form
Any '-' characters are currently replaced with '_'.
Definition at line 1596 of file __init__.py.
def to_filename(name: str):
    """Convert a project or version name to its filename-escaped form
    Any '-' characters are currently replaced with '_'.
    """
    return name.replace('-', '_')
Variable Documentation
_AdapterT
pip._vendor.pkg_resources._AdapterT protected
Initial value:
=  TypeVar(
    "_AdapterT", _DistFinderType[Any], _ProviderFactoryType, _NSHandlerType[Any]
)
Definition at line 129 of file __init__.py.
_DistFinderType
pip._vendor.pkg_resources._DistFinderType = Callable[[_T, str, bool], Iterable["Distribution"]] protected
Definition at line 127 of file __init__.py.
_distributionImpl
dict pip._vendor.pkg_resources._distributionImpl protected
Initial value:
=  {
    '.egg': Distribution,
    '.egg-info': EggInfoDistribution,
    '.dist-info': DistInfoDistribution,
}
Definition at line 3398 of file __init__.py.
_DistributionT
pip._vendor.pkg_resources._DistributionT = TypeVar("_DistributionT", bound="Distribution") protected
Definition at line 113 of file __init__.py.
_EPDistType
pip._vendor.pkg_resources._EPDistType = Union["Distribution", _PkgReqType] protected
Definition at line 119 of file __init__.py.
_InstallerType
pip._vendor.pkg_resources._InstallerType = Callable[["Requirement"], Union["Distribution", None]] protected
Definition at line 117 of file __init__.py.
_InstallerTypeT
pip._vendor.pkg_resources._InstallerTypeT = Callable[["Requirement"], "_DistributionT"] protected
Definition at line 116 of file __init__.py.
_LOCALE_ENCODING
tuple pip._vendor.pkg_resources._LOCALE_ENCODING = (3, 10) else None protected
Definition at line 3574 of file __init__.py.
_MetadataType
pip._vendor.pkg_resources._MetadataType = Union["IResourceProvider", None] protected
Definition at line 120 of file __init__.py.
_ModuleLike
pip._vendor.pkg_resources._ModuleLike = Union[object, types.ModuleType] protected
Definition at line 124 of file __init__.py.
_namespace_handlers
dict pip._vendor.pkg_resources._namespace_handlers protected
Initial value:
=  _declare_state(
    'dict', '_namespace_handlers', {}
)
Definition at line 2408 of file __init__.py.
_namespace_packages
dict pip._vendor.pkg_resources._namespace_packages protected
Initial value:
=  _declare_state(
    'dict', '_namespace_packages', {}
)
Definition at line 2411 of file __init__.py.
_NestedStr
pip._vendor.pkg_resources._NestedStr = Union[str, Iterable[Union[str, Iterable["_NestedStr"]]]] protected
Definition at line 115 of file __init__.py.
_NSHandlerType
pip._vendor.pkg_resources._NSHandlerType = Callable[[_T, str, str, types.ModuleType], Union[str, None]] protected
Definition at line 128 of file __init__.py.
_PEP440_FALLBACK
pip._vendor.pkg_resources._PEP440_FALLBACK = re.compile(r"^v?(?P<safe>(?:[0-9]+!)?[0-9]+(?:\.[0-9]+)*)", re.I) protected
Definition at line 143 of file __init__.py.
_PkgReqType
pip._vendor.pkg_resources._PkgReqType = Union[str, "Requirement"] protected
Definition at line 118 of file __init__.py.
_ProviderFactoryType
pip._vendor.pkg_resources._ProviderFactoryType = Callable[[Any], "IResourceProvider"] protected
Definition at line 126 of file __init__.py.
_ResolvedEntryPoint
pip._vendor.pkg_resources._ResolvedEntryPoint = Any protected
Definition at line 121 of file __init__.py.
_ResourceStream
pip._vendor.pkg_resources._ResourceStream = Any protected
Definition at line 122 of file __init__.py.
_sget_none
None pip._vendor.pkg_resources._sget_none = lambda *args protected
Definition at line 196 of file __init__.py.
_state_vars
dict pip._vendor.pkg_resources._state_vars = {} protected
Definition at line 156 of file __init__.py.
_T
pip._vendor.pkg_resources._T = TypeVar("_T") protected
Definition at line 112 of file __init__.py.
add_activation_listener
pip._vendor.pkg_resources.add_activation_listener = working_set.subscribe
Definition at line 3674 of file __init__.py.
append
pip._vendor.pkg_resources.append
Definition at line 3561 of file __init__.py.
AvailableDistributions
pip._vendor.pkg_resources.AvailableDistributions = Environment
Definition at line 1320 of file __init__.py.
BINARY_DIST
int pip._vendor.pkg_resources.BINARY_DIST = 2
Definition at line 398 of file __init__.py.
category
pip._vendor.pkg_resources.category
Definition at line 3561 of file __init__.py.
CHECKOUT_DIST
int pip._vendor.pkg_resources.CHECKOUT_DIST = 0
Definition at line 400 of file __init__.py.
cleanup_resources
pip._vendor.pkg_resources.cleanup_resources = __resource_manager.cleanup_resources
Definition at line 3669 of file __init__.py.
darwinVersionString
pip._vendor.pkg_resources.darwinVersionString = re.compile(r"darwin-(\d+)\.(\d+)\.(\d+)-(.*)")
Definition at line 477 of file __init__.py.
DEVELOP_DIST
int pip._vendor.pkg_resources.DEVELOP_DIST = -1
Definition at line 401 of file __init__.py.
EGG_DIST
int pip._vendor.pkg_resources.EGG_DIST = 3
Definition at line 397 of file __init__.py.
EGG_NAME
pip._vendor.pkg_resources.EGG_NAME
Initial value:
=  re.compile(
    ,
    re.VERBOSE | re.IGNORECASE,
).match
Definition at line 2667 of file __init__.py.
empty_provider
pip._vendor.pkg_resources.empty_provider = EmptyProvider()
Definition at line 1921 of file __init__.py.
get_platform
pip._vendor.pkg_resources.get_platform = get_build_platform
Definition at line 479 of file __init__.py.
Referenced by get_build_platform().
iter_entry_points
pip._vendor.pkg_resources.iter_entry_points = working_set.iter_entry_points
Definition at line 3673 of file __init__.py.
macosVersionString
pip._vendor.pkg_resources.macosVersionString = re.compile(r"macosx-(\d+)\.(\d+)-(.*)")
Definition at line 476 of file __init__.py.
MODULE
pip._vendor.pkg_resources.MODULE = re.compile(r"\w+(\.\w+)*$").match
Definition at line 2666 of file __init__.py.
parse_version
pip._vendor.pkg_resources.parse_version = _packaging_version.Version
Definition at line 153 of file __init__.py.
PEP440Warning
pip._vendor.pkg_resources.PEP440Warning
Definition at line 3561 of file __init__.py.
PY_MAJOR
str pip._vendor.pkg_resources.PY_MAJOR = '{}.{}'.format(*sys.version_info)
Definition at line 396 of file __init__.py.
require
pip._vendor.pkg_resources.require = working_set.require
Definition at line 3672 of file __init__.py.
Referenced by get_provider().
resource_exists
pip._vendor.pkg_resources.resource_exists = __resource_manager.resource_exists
Definition at line 3662 of file __init__.py.
resource_filename
pip._vendor.pkg_resources.resource_filename = __resource_manager.resource_filename
Definition at line 3664 of file __init__.py.
resource_isdir
pip._vendor.pkg_resources.resource_isdir = __resource_manager.resource_isdir
Definition at line 3663 of file __init__.py.
resource_listdir
pip._vendor.pkg_resources.resource_listdir = __resource_manager.resource_listdir
Definition at line 3667 of file __init__.py.
resource_stream
pip._vendor.pkg_resources.resource_stream = __resource_manager.resource_stream
Definition at line 3665 of file __init__.py.
resource_string
pip._vendor.pkg_resources.resource_string = __resource_manager.resource_string
Definition at line 3666 of file __init__.py.
run_main
pip._vendor.pkg_resources.run_main = run_script
Definition at line 3676 of file __init__.py.
run_script
pip._vendor.pkg_resources.run_script = working_set.run_script
Definition at line 3675 of file __init__.py.
set_extraction_path
pip._vendor.pkg_resources.set_extraction_path = __resource_manager.set_extraction_path
Definition at line 3668 of file __init__.py.
SOURCE_DIST
int pip._vendor.pkg_resources.SOURCE_DIST = 1
Definition at line 399 of file __init__.py.
working_set
pip._vendor.pkg_resources.working_set = WorkingSet()
Definition at line 3671 of file __init__.py.
WRITE_SUPPORT
bool pip._vendor.pkg_resources.WRITE_SUPPORT = True
Definition at line 85 of file __init__.py.