Read&Watch: django.db.backends.utils Namespace Reference
django.db.backends.utils Namespace Reference
Classes
class CursorDebugWrapper
class CursorWrapper
Functions
debug_transaction (connection, sql)
split_tzname_delta (tzname)
typecast_date (s)
Converters from database (string) to Python #.
typecast_time (s)
typecast_timestamp (s)
split_identifier (identifier)
Converters from Python to database (string) #.
truncate_name (identifier, length=None, hash_len=4)
names_digest (*args, length)
format_number (value, max_digits, decimal_places)
strip_quotes (table_name)
Variables
logger = logging.getLogger("django.db.backends")
Function Documentation
debug_transaction()
django.db.backends.utils.debug_transaction (connection, sql)
Definition at line 167 of file utils.py.
def debug_transaction(connection, sql):
    start = time.monotonic()
    try:
        yield
    finally:
        if connection.queries_logged:
            stop = time.monotonic()
            duration = stop - start
            connection.queries_log.append(
                {
                    "sql": "%s" % sql,
                    "time": "%.3f" % duration,
                }
            )
            logger.debug(
                "(%.3f) %s; args=%s; alias=%s",
                duration,
                sql,
                None,
                connection.alias,
                extra={
                    "duration": duration,
                    "sql": sql,
                    "alias": connection.alias,
                },
            )
format_number()
django.db.backends.utils.format_number (value, max_digits, decimal_places)
Format a number into a string with the requisite number of digits and
decimal places.
Definition at line 315 of file utils.py.
def format_number(value, max_digits, decimal_places):
    """
    Format a number into a string with the requisite number of digits and
    decimal places.
    """
    if value is None:
        return None
    context = decimal.getcontext().copy()
    if max_digits is not None:
        context.prec = max_digits
    if decimal_places is not None:
        value = value.quantize(
            decimal.Decimal(1).scaleb(-decimal_places), context=context
        )
    else:
        context.traps[decimal.Rounded] = 1
        value = context.create_decimal(value)
    return "{:f}".format(value)
names_digest()
django.db.backends.utils.names_digest (* args, length)
Generate a 32-bit digest of a set of arguments that can be used to shorten
identifying names.
Definition at line 304 of file utils.py.
def names_digest(*args, length):
    """
    Generate a 32-bit digest of a set of arguments that can be used to shorten
    identifying names.
    """
    h = md5(usedforsecurity=False)
    for arg in args:
        h.update(arg.encode())
    return h.hexdigest()[:length]
Referenced by truncate_name().
split_identifier()
django.db.backends.utils.split_identifier (identifier)
Converters from Python to database (string) #.
Split an SQL identifier into a two element tuple of (namespace, name).
The identifier could be a table, column, or sequence name might be prefixed
by a namespace.
Definition at line 269 of file utils.py.
def split_identifier(identifier):
    """
    Split an SQL identifier into a two element tuple of (namespace, name).
    The identifier could be a table, column, or sequence name might be prefixed
    by a namespace.
    """
    try:
        namespace, name = identifier.split('"."')
    except ValueError:
        namespace, name = "", identifier
    return namespace.strip('"'), name.strip('"')
Referenced by truncate_name().
split_tzname_delta()
django.db.backends.utils.split_tzname_delta (tzname)
Split a time zone name into a 3-tuple of (name, sign, offset).
Definition at line 195 of file utils.py.
def split_tzname_delta(tzname):
    """
    Split a time zone name into a 3-tuple of (name, sign, offset).
    """
    for sign in ["+", "-"]:
        if sign in tzname:
            name, offset = tzname.rsplit(sign, 1)
            if offset and parse_time(offset):
                if ":" not in offset:
                    offset = f"{offset}:00"
                return name, sign, offset
    return tzname, None, None
strip_quotes()
django.db.backends.utils.strip_quotes (table_name)
Strip quotes off of quoted table names to make them safe for use in index
names, sequence names, etc. For example '"USER"."TABLE"' (an Oracle naming
scheme) becomes 'USER"."TABLE'.
Definition at line 335 of file utils.py.
def strip_quotes(table_name):
    """
    Strip quotes off of quoted table names to make them safe for use in index
    names, sequence names, etc. For example '"USER"."TABLE"' (an Oracle naming
    scheme) becomes 'USER"."TABLE'.
    """
    has_quotes = table_name.startswith('"') and table_name.endswith('"')
    return table_name[1:-1] if has_quotes else table_name
truncate_name()
django.db.backends.utils.truncate_name (identifier, length = None, hash_len = 4)
Shorten an SQL identifier to a repeatable mangled version with the given
length.
If a quote stripped name contains a namespace, e.g. USERNAME"."TABLE,
truncate the table portion only.
Definition at line 283 of file utils.py.
def truncate_name(identifier, length=None, hash_len=4):
    """
    Shorten an SQL identifier to a repeatable mangled version with the given
    length.
    If a quote stripped name contains a namespace, e.g. USERNAME"."TABLE,
    truncate the table portion only.
    """
    namespace, name = split_identifier(identifier)
    if length is None or len(name) <= length:
        return identifier
    digest = names_digest(name, length=hash_len)
    return "%s%s%s" % (
        '%s"."' % namespace if namespace else "",
        name[: length - hash_len],
        digest,
    )
References names_digest(), and split_identifier().
typecast_date()
django.db.backends.utils.typecast_date (s)
Converters from database (string) to Python #.
Definition at line 214 of file utils.py.
def typecast_date(s):
    return (
        datetime.date(*map(int, s.split("-"))) if s else None
    )  # return None if s is null
Referenced by typecast_timestamp().
typecast_time()
django.db.backends.utils.typecast_time (s)
Definition at line 220 of file utils.py.
def typecast_time(s):  # does NOT store time zone information
    if not s:
        return None
    hour, minutes, seconds = s.split(":")
    if "." in seconds:  # check whether seconds have a fractional part
        seconds, microseconds = seconds.split(".")
    else:
        microseconds = "0"
    return datetime.time(
        int(hour), int(minutes), int(seconds), int((microseconds + "000000")[:6])
    )
typecast_timestamp()
django.db.backends.utils.typecast_timestamp (s)
Definition at line 233 of file utils.py.
def typecast_timestamp(s):  # does NOT store time zone information
    # "2005-07-29 15:48:00.590358-05"
    # "2005-07-29 09:56:00-05"
    if not s:
        return None
    if " " not in s:
        return typecast_date(s)
    d, t = s.split()
    # Remove timezone information.
    if "-" in t:
        t, _ = t.split("-", 1)
    elif "+" in t:
        t, _ = t.split("+", 1)
    dates = d.split("-")
    times = t.split(":")
    seconds = times[2]
    if "." in seconds:  # check whether seconds have a fractional part
        seconds, microseconds = seconds.split(".")
    else:
        microseconds = "0"
    return datetime.datetime(
        int(dates[0]),
        int(dates[1]),
        int(dates[2]),
        int(times[0]),
        int(times[1]),
        int(seconds),
        int((microseconds + "000000")[:6]),
    )
References typecast_date().
Variable Documentation
logger
django.db.backends.utils.logger = logging.getLogger("django.db.backends")
Definition at line 14 of file utils.py.