Read&Watch: responses._recorder Namespace Reference
responses._recorder Namespace Reference
Classes
class Recorder
Functions
"Any" _remove_nones ("Any" d)
"Any" _remove_default_headers ("Any" data)
None _dump ("List[BaseResponse]" registered, "Union[BinaryIO, TextIOWrapper]" destination, "Callable[[Union[Dict[Any, Any], List[Any]], Union[BinaryIO, TextIOWrapper]], Any]" dumper)
Variables
recorder = Recorder()
record = recorder.record
Function Documentation
_dump()
None responses._recorder._dump ("List[BaseResponse]" registered, "Union[BinaryIO, TextIOWrapper]" destination, "Callable[[Union[Dict[Any, Any], List[Any]], Union[BinaryIO, TextIOWrapper]], Any]" dumper) protected
Definition at line 63 of file _recorder.py.
) -> None:
    data: Dict[str, Any] = {"responses": []}
    for rsp in registered:
        try:
            content_length = rsp.auto_calculate_content_length  # type: ignore[attr-defined]
            data["responses"].append(
                {
                    "response": {
                        "method": rsp.method,
                        "url": rsp.url,
                        "body": rsp.body,
                        "status": rsp.status,
                        "headers": rsp.headers,
                        "content_type": rsp.content_type,
                        "auto_calculate_content_length": content_length,
                    }
                }
            )
        except AttributeError as exc:  # pragma: no cover
            raise AttributeError(
                "Cannot dump response object."
                "Probably you use custom Response object that is missing required attributes"
            ) from exc
    dumper(_remove_default_headers(_remove_nones(data)), destination)
References _remove_default_headers(), and _remove_nones().
Referenced by responses._recorder.Recorder.dump_to_file().
_remove_default_headers()
"Any" responses._recorder._remove_default_headers ("Any" data) protected
It would be too verbose to store these headers in the file generated by the
record functionality.
Definition at line 40 of file _recorder.py.
def _remove_default_headers(data: "Any") -> "Any":
    """
    It would be too verbose to store these headers in the file generated by the
    record functionality.
    """
    if isinstance(data, dict):
        keys_to_remove = [
            "Content-Length",
            "Content-Type",
            "Date",
            "Server",
            "Connection",
            "Content-Encoding",
        ]
        for i, response in enumerate(data["responses"]):
            for key in keys_to_remove:
                if key in response["response"]["headers"]:
                    del data["responses"][i]["response"]["headers"][key]
            if not response["response"]["headers"]:
                del data["responses"][i]["response"]["headers"]
    return data
Referenced by _dump().
_remove_nones()
"Any" responses._recorder._remove_nones ("Any" d) protected
Definition at line 32 of file _recorder.py.
def _remove_nones(d: "Any") -> "Any":
    if isinstance(d, dict):
        return {k: _remove_nones(v) for k, v in d.items() if v is not None}
    if isinstance(d, list):
        return [_remove_nones(i) for i in d]
    return d
References _remove_nones().
Referenced by _dump(), and _remove_nones().
Variable Documentation
record
responses._recorder.record = recorder.record
Definition at line 165 of file _recorder.py.
recorder
responses._recorder.recorder = Recorder()
Definition at line 164 of file _recorder.py.