Read&Watch: django.db.models.fields.json Namespace Reference
django.db.models.fields.json Namespace Reference
Classes
class CaseInsensitiveMixin
class ContainedBy
class DataContains
class HasAnyKeys
class HasKey
class HasKeyLookup
class HasKeyOrArrayIndex
class HasKeys
class JSONExact
class JSONField
class JSONIContains
class KeyTextTransform
class KeyTransform
class KeyTransformEndsWith
class KeyTransformExact
class KeyTransformFactory
class KeyTransformGt
class KeyTransformGte
class KeyTransformIContains
class KeyTransformIEndsWith
class KeyTransformIExact
class KeyTransformIn
class KeyTransformIRegex
class KeyTransformIsNull
class KeyTransformIStartsWith
class KeyTransformLt
class KeyTransformLte
class KeyTransformNumericLookupMixin
class KeyTransformRegex
class KeyTransformStartsWith
class KeyTransformTextLookupMixin
Functions
compile_json_path (key_transforms, include_root=True)
Variables
KT = KeyTextTransform.from_lookup
Function Documentation
compile_json_path()
django.db.models.fields.json.compile_json_path (key_transforms, include_root = True)
Definition at line 146 of file json.py.
def compile_json_path(key_transforms, include_root=True):
    path = ["$"] if include_root else []
    for key_transform in key_transforms:
        try:
            num = int(key_transform)
        except ValueError:  # non-integer
            path.append(".")
            path.append(json.dumps(key_transform))
        else:
            path.append("[%s]" % num)
    return "".join(path)
Referenced by django.db.models.fields.json.KeyTextTransform.as_mysql(), django.db.models.fields.json.KeyTransform.as_mysql(), django.db.models.fields.json.KeyTransform.as_oracle(), django.db.models.fields.json.KeyTransform.as_sqlite(), and django.db.models.fields.json.HasKeyOrArrayIndex.compile_json_path_final_key().
Variable Documentation
KT
django.db.models.fields.json.KT = KeyTextTransform.from_lookup
Definition at line 419 of file json.py.