Read&Watch: django.db.migrations.serializer Namespace Reference
django.db.migrations.serializer Namespace Reference
Classes
class BaseSequenceSerializer
class BaseSerializer
class BaseSimpleSerializer
class BaseUnorderedSequenceSerializer
class ChoicesSerializer
class DatetimeDatetimeSerializer
class DateTimeSerializer
class DecimalSerializer
class DeconstructableSerializer
class DictionarySerializer
class EnumSerializer
class FloatSerializer
class FrozensetSerializer
class FunctionTypeSerializer
class FunctoolsPartialSerializer
class IterableSerializer
class ModelFieldSerializer
class ModelManagerSerializer
class OperationSerializer
class PathLikeSerializer
class PathSerializer
class RegexSerializer
class SequenceSerializer
class Serializer
class SetSerializer
class SettingsReferenceSerializer
class TupleSerializer
class TypeSerializer
class UUIDSerializer
Functions
serializer_factory (value)
Variables
tuple FUNCTION_TYPES = (types.FunctionType, types.BuiltinFunctionType, types.MethodType)
Function Documentation
serializer_factory()
django.db.migrations.serializer.serializer_factory (value)
Definition at line 379 of file serializer.py.
def serializer_factory(value):
    if isinstance(value, Promise):
        value = str(value)
    elif isinstance(value, LazyObject):
        # The unwrapped value is returned as the first item of the arguments
        # tuple.
        value = value.__reduce__()[1][0]
    if isinstance(value, models.Field):
        return ModelFieldSerializer(value)
    if isinstance(value, models.manager.BaseManager):
        return ModelManagerSerializer(value)
    if isinstance(value, Operation):
        return OperationSerializer(value)
    if isinstance(value, type):
        return TypeSerializer(value)
    # Anything that knows how to deconstruct itself.
    if hasattr(value, "deconstruct"):
        return DeconstructableSerializer(value)
    for type_, serializer_cls in Serializer._registry.items():
        if isinstance(value, type_):
            return serializer_cls(value)
    raise ValueError(
        "Cannot serialize: %r\nThere are some values Django cannot serialize into "
        "migration files.\nFor more, see https://docs.djangoproject.com/en/%s/"
        "topics/migrations/#migration-serializing" % (value, get_docs_version())
    )
Referenced by django.db.migrations.serializer.ChoicesSerializer.serialize(), django.db.migrations.serializer.DictionarySerializer.serialize(), django.db.migrations.serializer.FunctoolsPartialSerializer.serialize(), django.db.migrations.serializer.RegexSerializer.serialize(), and django.db.migrations.serializer.DeconstructableSerializer.serialize_deconstructed().
Variable Documentation
FUNCTION_TYPES
tuple django.db.migrations.serializer.FUNCTION_TYPES = (types.FunctionType, types.BuiltinFunctionType, types.MethodType)
Definition at line 21 of file serializer.py.