Read&Watch: django.contrib.auth.models Namespace Reference
django.contrib.auth.models Namespace Reference
Classes
class AbstractUser
class AnonymousUser
class Group
class GroupManager
class Permission
class PermissionManager
class PermissionsMixin
class User
class UserManager
Functions
update_last_login (sender, user, **kwargs)
_user_get_permissions (user, obj, from_name)
_user_has_perm (user, perm, obj)
_user_has_module_perms (user, app_label)
Function Documentation
_user_get_permissions()
django.contrib.auth.models._user_get_permissions (user, obj, from_name) protected
Definition at line 204 of file models.py.
def _user_get_permissions(user, obj, from_name):
    permissions = set()
    name = "get_%s_permissions" % from_name
    for backend in auth.get_backends():
        if hasattr(backend, name):
            permissions.update(getattr(backend, name)(user, obj))
    return permissions
Referenced by django.contrib.auth.models.AnonymousUser.get_all_permissions(), django.contrib.auth.models.PermissionsMixin.get_all_permissions(), django.contrib.auth.models.PermissionsMixin.get_group_permissions(), django.contrib.auth.models.AnonymousUser.get_user_permissions(), and django.contrib.auth.models.PermissionsMixin.get_user_permissions().
_user_has_module_perms()
django.contrib.auth.models._user_has_module_perms (user, app_label) protected
A backend can raise `PermissionDenied` to short-circuit permission checking.
Definition at line 228 of file models.py.
def _user_has_module_perms(user, app_label):
    """
    A backend can raise `PermissionDenied` to short-circuit permission checking.
    """
    for backend in auth.get_backends():
        if not hasattr(backend, "has_module_perms"):
            continue
        try:
            if backend.has_module_perms(user, app_label):
                return True
        except PermissionDenied:
            return False
    return False
Referenced by django.contrib.auth.models.AnonymousUser.has_module_perms(), and django.contrib.auth.models.PermissionsMixin.has_module_perms().
_user_has_perm()
django.contrib.auth.models._user_has_perm (user, perm, obj) protected
A backend can raise `PermissionDenied` to short-circuit permission checking.
Definition at line 213 of file models.py.
def _user_has_perm(user, perm, obj):
    """
    A backend can raise `PermissionDenied` to short-circuit permission checking.
    """
    for backend in auth.get_backends():
        if not hasattr(backend, "has_perm"):
            continue
        try:
            if backend.has_perm(user, perm, obj):
                return True
        except PermissionDenied:
            return False
    return False
Referenced by django.contrib.auth.models.AnonymousUser.has_perm(), and django.contrib.auth.models.PermissionsMixin.has_perm().
update_last_login()
django.contrib.auth.models.update_last_login (sender, user, ** kwargs)
A signal receiver which updates the last_login date for
the user logging in.
Definition at line 18 of file models.py.
def update_last_login(sender, user, **kwargs):
    """
    A signal receiver which updates the last_login date for
    the user logging in.
    """
    user.last_login = timezone.now()
    user.save(update_fields=["last_login"])