Read&Watch: pip._internal.network.download Namespace Reference
pip._internal.network.download Namespace Reference
Classes
class BatchDownloader
class Downloader
Functions
Optional[int] _get_http_response_size (Response resp)
Iterable[bytes] _prepare_download (Response resp, Link link, str progress_bar)
str sanitize_content_filename (str filename)
str parse_content_disposition (str content_disposition, str default_filename)
str _get_http_response_filename (Response resp, Link link)
Response _http_get_download (PipSession session, Link link)
Variables
logger = logging.getLogger(__name__)
Detailed Description
Download files with progress indicators.
Function Documentation
_get_http_response_filename()
str pip._internal.network.download._get_http_response_filename (Response resp, Link link) protected
Get an ideal filename from the given HTTP response, falling back to
the link filename if not provided.
Definition at line 95 of file download.py.
def _get_http_response_filename(resp: Response, link: Link) -> str:
    """Get an ideal filename from the given HTTP response, falling back to
    the link filename if not provided.
    """
    filename = link.filename  # fallback
    # Have a look at the Content-Disposition header for a better guess
    content_disposition = resp.headers.get("content-disposition")
    if content_disposition:
        filename = parse_content_disposition(content_disposition, filename)
    ext: Optional[str] = splitext(filename)[1]
    if not ext:
        ext = mimetypes.guess_extension(resp.headers.get("content-type", ""))
        if ext:
            filename += ext
    if not ext and link.url != resp.url:
        ext = os.path.splitext(resp.url)[1]
        if ext:
            filename += ext
    return filename
References parse_content_disposition().
Referenced by pip._internal.network.download.BatchDownloader.__call__(), and pip._internal.network.download.Downloader.__call__().
_get_http_response_size()
Optional[int] pip._internal.network.download._get_http_response_size (Response resp) protected
Definition at line 24 of file download.py.
def _get_http_response_size(resp: Response) -> Optional[int]:
    try:
        return int(resp.headers["content-length"])
    except (ValueError, KeyError, TypeError):
        return None
Referenced by _prepare_download().
_http_get_download()
Response pip._internal.network.download._http_get_download (PipSession session, Link link) protected
Definition at line 116 of file download.py.
def _http_get_download(session: PipSession, link: Link) -> Response:
    target_url = link.url.split("#", 1)[0]
    resp = session.get(target_url, headers=HEADERS, stream=True)
    raise_for_status(resp)
    return resp
Referenced by pip._internal.network.download.BatchDownloader.__call__(), and pip._internal.network.download.Downloader.__call__().
_prepare_download()
Iterable[bytes] pip._internal.network.download._prepare_download (Response resp, Link link, str progress_bar) protected
Definition at line 31 of file download.py.
) -> Iterable[bytes]:
    total_length = _get_http_response_size(resp)
    if link.netloc == PyPI.file_storage_domain:
        url = link.show_url
    else:
        url = link.url_without_fragment
    logged_url = redact_auth_from_url(url)
    if total_length:
        logged_url = f"{logged_url} ({format_size(total_length)})"
    if is_from_cache(resp):
        logger.info("Using cached %s", logged_url)
    else:
        logger.info("Downloading %s", logged_url)
    if logger.getEffectiveLevel() > logging.INFO:
        show_progress = False
    elif is_from_cache(resp):
        show_progress = False
    elif not total_length:
        show_progress = True
    elif total_length > (512 * 1024):
        show_progress = True
    else:
        show_progress = False
    chunks = response_chunks(resp)
    if not show_progress:
        return chunks
    renderer = get_download_progress_renderer(bar_type=progress_bar, size=total_length)
    return renderer(chunks)
References _get_http_response_size().
Referenced by pip._internal.network.download.BatchDownloader.__call__(), and pip._internal.network.download.Downloader.__call__().
parse_content_disposition()
str pip._internal.network.download.parse_content_disposition (str content_disposition, str default_filename)
Parse the "filename" value from a Content-Disposition header, and
return the default filename if the result is empty.
Definition at line 80 of file download.py.
def parse_content_disposition(content_disposition: str, default_filename: str) -> str:
    """
    Parse the "filename" value from a Content-Disposition header, and
    return the default filename if the result is empty.
    """
    m = email.message.Message()
    m["content-type"] = content_disposition
    filename = m.get_param("filename")
    if filename:
        # We need to sanitize the filename to prevent directory traversal
        # in case the filename contains ".." path parts.
        filename = sanitize_content_filename(str(filename))
    return filename or default_filename
References sanitize_content_filename().
Referenced by _get_http_response_filename().
sanitize_content_filename()
str pip._internal.network.download.sanitize_content_filename (str filename)
Sanitize the "filename" value from a Content-Disposition header.
Definition at line 73 of file download.py.
def sanitize_content_filename(filename: str) -> str:
    """
    Sanitize the "filename" value from a Content-Disposition header.
    """
    return os.path.basename(filename)
Referenced by parse_content_disposition().
Variable Documentation
logger
pip._internal.network.download.logger = logging.getLogger(__name__)
Definition at line 21 of file download.py.