Read&Watch: urllib3._collections Namespace Reference
urllib3._collections Namespace Reference
Classes
class _Sentinel
class HasGettableStringKeys
class HTTPHeaderDict
class HTTPHeaderDictItemView
class RecentlyUsedContainer
Functions
ValidHTTPHeaderSource|None ensure_can_construct_http_header_dict (object potential)
Variables
_KT = typing.TypeVar("_KT")
_VT = typing.TypeVar("_VT")
_DT = typing.TypeVar("_DT")
ValidHTTPHeaderSource
Function Documentation
ensure_can_construct_http_header_dict()
ValidHTTPHeaderSource | None urllib3._collections.ensure_can_construct_http_header_dict (object potential)
Definition at line 45 of file _collections.py.
) -> ValidHTTPHeaderSource | None:
    if isinstance(potential, HTTPHeaderDict):
        return potential
    elif isinstance(potential, typing.Mapping):
        # Full runtime checking of the contents of a Mapping is expensive, so for the
        # purposes of typechecking, we assume that any Mapping is the right shape.
        return typing.cast(typing.Mapping[str, str], potential)
    elif isinstance(potential, typing.Iterable):
        # Similarly to Mapping, full runtime checking of the contents of an Iterable is
        # expensive, so for the purposes of typechecking, we assume that any Iterable
        # is the right shape.
        return typing.cast(typing.Iterable[typing.Tuple[str, str]], potential)
    elif hasattr(potential, "keys") and hasattr(potential, "__getitem__"):
        return typing.cast("HasGettableStringKeys", potential)
    else:
        return None
Referenced by urllib3._collections.HTTPHeaderDict.__eq__(), urllib3._collections.HTTPHeaderDict.__ior__(), urllib3._collections.HTTPHeaderDict.__or__(), and urllib3._collections.HTTPHeaderDict.__ror__().
Variable Documentation
_DT
urllib3._collections._DT = typing.TypeVar("_DT") protected
Definition at line 31 of file _collections.py.
_KT
urllib3._collections._KT = typing.TypeVar("_KT") protected
Definition at line 27 of file _collections.py.
_VT
urllib3._collections._VT = typing.TypeVar("_VT") protected
Definition at line 29 of file _collections.py.
ValidHTTPHeaderSource
urllib3._collections.ValidHTTPHeaderSource
Initial value:
=  typing.Union[
    "HTTPHeaderDict",
    typing.Mapping[str, str],
    typing.Iterable[typing.Tuple[str, str]],
    "HasGettableStringKeys",
]
Definition at line 33 of file _collections.py.