Read&Watch: astroid.raw_building Namespace Reference
astroid.raw_building Namespace Reference
Classes
class InspectBuilder
Functions
None _attach_local_node (parent, node, str name)
None _add_dunder_class (func, member)
None attach_dummy_node (node, str name, runtime_object=_EMPTY_OBJECT_MARKER)
None attach_const_node (node, str name, value)
None attach_import_node (node, str modname, str membername)
nodes.Module build_module (str name, str|None doc=None)
nodes.ClassDef build_class (str name, Iterable[str] basenames=(), str|None doc=None)
nodes.FunctionDef build_function (str name, list[str]|None args=None, list[str]|None posonlyargs=None, list[Any]|None defaults=None, str|None doc=None, list[str]|None kwonlyargs=None, list[Any]|None kwonlydefaults=None)
nodes.ImportFrom build_from_import (str fromname, list[str] names)
None register_arguments (nodes.FunctionDef func, list|None args=None)
nodes.ClassDef object_build_class (nodes.Module|nodes.ClassDef node, type member, str localname)
tuple[list[str], list[str], list[Any], list[str], list[Any]] _get_args_info_from_callable (_FunctionTypes member)
None object_build_function (nodes.Module|nodes.ClassDef node, _FunctionTypes member, str localname)
nodes.ClassDef object_build_datadescriptor (nodes.Module|nodes.ClassDef node, type member, str name)
None object_build_methoddescriptor (nodes.Module|nodes.ClassDef node, _FunctionTypes member, str localname)
nodes.ClassDef _base_class_object_build (nodes.Module|nodes.ClassDef node, type member, list[str] basenames, str|None name=None, str|None localname=None)
None _build_from_function (nodes.Module|nodes.ClassDef node, str name, _FunctionTypes member, types.ModuleType module)
bool _safe_has_attribute (obj, str member)
nodes.ClassDef _set_proxied (const)
None _astroid_bootstrapping ()
Variables
logger = logging.getLogger(__name__)
_FunctionTypes
_CONSTANTS = tuple(node_classes.CONST_CLS)
TYPE_NONE = type(None)
TYPE_NOTIMPLEMENTED = type(NotImplemented)
TYPE_ELLIPSIS = type(...)
Detailed Description
this module contains a set of functions to create astroid trees from scratch
(build_* functions) or from living object (object_build_* functions)
Function Documentation
_add_dunder_class()
None astroid.raw_building._add_dunder_class (func, member) protected
Add a __class__ member to the given func node, if we can determine it.
Definition at line 52 of file raw_building.py.
def _add_dunder_class(func, member) -> None:
    """Add a __class__ member to the given func node, if we can determine it."""
    python_cls = member.__class__
    cls_name = getattr(python_cls, "__name__", None)
    if not cls_name:
        return
    cls_bases = [ancestor.__name__ for ancestor in python_cls.__bases__]
    ast_klass = build_class(cls_name, cls_bases, python_cls.__doc__)
    func.instance_attrs["__class__"] = [ast_klass]
References build_class().
Referenced by object_build_methoddescriptor().
_astroid_bootstrapping()
None astroid.raw_building._astroid_bootstrapping () protected
astroid bootstrapping the builtins module
Definition at line 599 of file raw_building.py.
def _astroid_bootstrapping() -> None:
    """astroid bootstrapping the builtins module"""
    # this boot strapping is necessary since we need the Const nodes to
    # inspect_build builtins, and then we can proxy Const
    builder = InspectBuilder()
    astroid_builtin = builder.inspect_build(builtins)
    for cls, node_cls in node_classes.CONST_CLS.items():
        if cls is TYPE_NONE:
            proxy = build_class("NoneType")
            proxy.parent = astroid_builtin
        elif cls is TYPE_NOTIMPLEMENTED:
            proxy = build_class("NotImplementedType")
            proxy.parent = astroid_builtin
        elif cls is TYPE_ELLIPSIS:
            proxy = build_class("Ellipsis")
            proxy.parent = astroid_builtin
        else:
            proxy = astroid_builtin.getattr(cls.__name__)[0]
            assert isinstance(proxy, nodes.ClassDef)
        if cls in (dict, list, set, tuple):
            node_cls._proxied = proxy
        else:
            _CONST_PROXY[cls] = proxy
    # Set the builtin module as parent for some builtins.
    nodes.Const._proxied = property(_set_proxied)
    _GeneratorType = nodes.ClassDef(
        types.GeneratorType.__name__,
        lineno=0,
        col_offset=0,
        end_lineno=0,
        end_col_offset=0,
        parent=nodes.Unknown(),
    )
    _GeneratorType.parent = astroid_builtin
    generator_doc_node = (
        nodes.Const(value=types.GeneratorType.__doc__)
        if types.GeneratorType.__doc__
        else None
    )
    _GeneratorType.postinit(
        bases=[],
        body=[],
        decorators=None,
        doc_node=generator_doc_node,
    )
    bases.Generator._proxied = _GeneratorType
    builder.object_build(bases.Generator._proxied, types.GeneratorType)
    if hasattr(types, "AsyncGeneratorType"):
        _AsyncGeneratorType = nodes.ClassDef(
            types.AsyncGeneratorType.__name__,
            lineno=0,
            col_offset=0,
            end_lineno=0,
            end_col_offset=0,
            parent=nodes.Unknown(),
        )
        _AsyncGeneratorType.parent = astroid_builtin
        async_generator_doc_node = (
            nodes.Const(value=types.AsyncGeneratorType.__doc__)
            if types.AsyncGeneratorType.__doc__
            else None
        )
        _AsyncGeneratorType.postinit(
            bases=[],
            body=[],
            decorators=None,
            doc_node=async_generator_doc_node,
        )
        bases.AsyncGenerator._proxied = _AsyncGeneratorType
        builder.object_build(bases.AsyncGenerator._proxied, types.AsyncGeneratorType)
    if hasattr(types, "UnionType"):
        _UnionTypeType = nodes.ClassDef(
            types.UnionType.__name__,
            lineno=0,
            col_offset=0,
            end_lineno=0,
            end_col_offset=0,
            parent=nodes.Unknown(),
        )
        _UnionTypeType.parent = astroid_builtin
        union_type_doc_node = (
            nodes.Const(value=types.UnionType.__doc__)
            if types.UnionType.__doc__
            else None
        )
        _UnionTypeType.postinit(
            bases=[],
            body=[],
            decorators=None,
            doc_node=union_type_doc_node,
        )
        bases.UnionType._proxied = _UnionTypeType
        builder.object_build(bases.UnionType._proxied, types.UnionType)
    builtin_types = (
        types.GetSetDescriptorType,
        types.GeneratorType,
        types.MemberDescriptorType,
        TYPE_NONE,
        TYPE_NOTIMPLEMENTED,
        types.FunctionType,
        types.MethodType,
        types.BuiltinFunctionType,
        types.ModuleType,
        types.TracebackType,
    )
    for _type in builtin_types:
        if _type.__name__ not in astroid_builtin:
            klass = nodes.ClassDef(
                _type.__name__,
                lineno=0,
                col_offset=0,
                end_lineno=0,
                end_col_offset=0,
                parent=nodes.Unknown(),
            )
            klass.parent = astroid_builtin
            klass.postinit(
                bases=[],
                body=[],
                decorators=None,
                doc_node=nodes.Const(value=_type.__doc__) if _type.__doc__ else None,
            )
            builder.object_build(klass, _type)
            astroid_builtin[_type.__name__] = klass
    InspectBuilder.bootstrapped = True
    # pylint: disable-next=import-outside-toplevel
    from astroid.brain.brain_builtin_inference import on_bootstrap
    # Instantiates an AstroidBuilder(), which is where
    # InspectBuilder.bootstrapped is checked, so place after bootstrapped=True.
    on_bootstrap()
References build_class().
_attach_local_node()
None astroid.raw_building._attach_local_node (parent, node, str name) protected
Definition at line 47 of file raw_building.py.
def _attach_local_node(parent, node, name: str) -> None:
    node.name = name  # needed by add_local_node
    parent.add_local_node(node)
Referenced by attach_const_node(), attach_dummy_node(), attach_import_node(), and astroid.raw_building.InspectBuilder.object_build().
_base_class_object_build()
nodes.ClassDef astroid.raw_building._base_class_object_build (nodes.Module | nodes.ClassDef node, type member, list[str] basenames, str | None name = None, str | None localname = None) protected
create astroid for a living class object, with a given set of base names
(e.g. ancestors)
Definition at line 348 of file raw_building.py.
) -> nodes.ClassDef:
    """create astroid for a living class object, with a given set of base names
    (e.g. ancestors)
    """
    class_name = name or getattr(member, "__name__", None) or localname
    assert isinstance(class_name, str)
    klass = build_class(
        class_name,
        basenames,
        member.__doc__,
    )
    klass._newstyle = isinstance(member, type)
    node.add_local_node(klass, localname)
    try:
        # limit the instantiation trick since it's too dangerous
        # (such as infinite test execution...)
        # this at least resolves common case such as Exception.args,
        # OSError.errno
        if issubclass(member, Exception):
            instdict = member().__dict__
        else:
            raise TypeError
    except TypeError:
        pass
    else:
        for item_name, obj in instdict.items():
            valnode = nodes.EmptyNode()
            valnode.object = obj
            valnode.parent = klass
            valnode.lineno = 1
            klass.instance_attrs[item_name] = [valnode]
    return klass
References build_class().
Referenced by object_build_class(), and object_build_datadescriptor().
_build_from_function()
None astroid.raw_building._build_from_function (nodes.Module | nodes.ClassDef node, str name, _FunctionTypes member, types.ModuleType module) protected
Definition at line 388 of file raw_building.py.
) -> None:
    # verify this is not an imported function
    try:
        code = member.__code__  # type: ignore[union-attr]
    except AttributeError:
        # Some implementations don't provide the code object,
        # such as Jython.
        code = None
    filename = getattr(code, "co_filename", None)
    if filename is None:
        assert isinstance(member, object)
        object_build_methoddescriptor(node, member, name)
    elif filename != getattr(module, "__file__", None):
        attach_dummy_node(node, name, member)
    else:
        object_build_function(node, member, name)
References attach_dummy_node(), object_build_function(), and object_build_methoddescriptor().
Referenced by astroid.raw_building.InspectBuilder.object_build().
_get_args_info_from_callable()
tuple[list[str], list[str], list[Any], list[str], list[Any]] astroid.raw_building._get_args_info_from_callable (_FunctionTypes member) protected
Returns args, posonlyargs, defaults, kwonlyargs.
:note: currently ignores the return annotation.
Definition at line 268 of file raw_building.py.
) -> tuple[list[str], list[str], list[Any], list[str], list[Any]]:
    """Returns args, posonlyargs, defaults, kwonlyargs.
    :note: currently ignores the return annotation.
    """
    signature = inspect.signature(member)
    args: list[str] = []
    defaults: list[Any] = []
    posonlyargs: list[str] = []
    kwonlyargs: list[str] = []
    kwonlydefaults: list[Any] = []
    for param_name, param in signature.parameters.items():
        if param.kind == inspect.Parameter.POSITIONAL_ONLY:
            posonlyargs.append(param_name)
        elif param.kind == inspect.Parameter.POSITIONAL_OR_KEYWORD:
            args.append(param_name)
        elif param.kind == inspect.Parameter.VAR_POSITIONAL:
            args.append(param_name)
        elif param.kind == inspect.Parameter.VAR_KEYWORD:
            args.append(param_name)
        elif param.kind == inspect.Parameter.KEYWORD_ONLY:
            kwonlyargs.append(param_name)
            if param.default is not inspect.Parameter.empty:
                kwonlydefaults.append(param.default)
            continue
        if param.default is not inspect.Parameter.empty:
            defaults.append(param.default)
    return args, posonlyargs, defaults, kwonlyargs, kwonlydefaults
Referenced by object_build_function().
_safe_has_attribute()
bool astroid.raw_building._safe_has_attribute (obj, str member) protected
Required because unexpected RunTimeError can be raised.
See https://github.com/pylint-dev/astroid/issues/1958
Definition at line 411 of file raw_building.py.
def _safe_has_attribute(obj, member: str) -> bool:
    """Required because unexpected RunTimeError can be raised.
    See https://github.com/pylint-dev/astroid/issues/1958
    """
    try:
        return hasattr(obj, member)
    except Exception:  # pylint: disable=broad-except
        return False
Referenced by astroid.raw_building.InspectBuilder.object_build().
_set_proxied()
nodes.ClassDef astroid.raw_building._set_proxied (const) protected
Definition at line 594 of file raw_building.py.
def _set_proxied(const) -> nodes.ClassDef:
    # TODO : find a nicer way to handle this situation;
    return _CONST_PROXY[const.value.__class__]
attach_const_node()
None astroid.raw_building.attach_const_node (node, str name, value)
create a Const node and register it in the locals of the given
node with the specified name
Definition at line 72 of file raw_building.py.
def attach_const_node(node, name: str, value) -> None:
    """create a Const node and register it in the locals of the given
    node with the specified name
    """
    if name not in node.special_attributes:
        _attach_local_node(node, nodes.const_factory(value), name)
References _attach_local_node().
Referenced by astroid.raw_building.InspectBuilder.object_build().
attach_dummy_node()
None astroid.raw_building.attach_dummy_node (node, str name, runtime_object = _EMPTY_OBJECT_MARKER)
create a dummy node and register it in the locals of the given
node with the specified name
Definition at line 63 of file raw_building.py.
def attach_dummy_node(node, name: str, runtime_object=_EMPTY_OBJECT_MARKER) -> None:
    """create a dummy node and register it in the locals of the given
    node with the specified name
    """
    enode = nodes.EmptyNode()
    enode.object = runtime_object
    _attach_local_node(node, enode, name)
References _attach_local_node().
Referenced by _build_from_function(), astroid.raw_building.InspectBuilder.imported_member(), and astroid.raw_building.InspectBuilder.object_build().
attach_import_node()
None astroid.raw_building.attach_import_node (node, str modname, str membername)
create a ImportFrom node and register it in the locals of the given
node with the specified name
Definition at line 80 of file raw_building.py.
def attach_import_node(node, modname: str, membername: str) -> None:
    """create a ImportFrom node and register it in the locals of the given
    node with the specified name
    """
    from_node = nodes.ImportFrom(modname, [(membername, None)])
    _attach_local_node(node, from_node, membername)
References _attach_local_node().
Referenced by astroid.raw_building.InspectBuilder.imported_member().
build_class()
nodes.ClassDef astroid.raw_building.build_class (str name, Iterable[str] basenames = (), str | None doc = None)
Create and initialize an astroid ClassDef node.
Definition at line 98 of file raw_building.py.
) -> nodes.ClassDef:
    """Create and initialize an astroid ClassDef node."""
    node = nodes.ClassDef(
        name,
        lineno=0,
        col_offset=0,
        end_lineno=0,
        end_col_offset=0,
        parent=nodes.Unknown(),
    )
    node.postinit(
        bases=[
            nodes.Name(
                name=base,
                lineno=0,
                col_offset=0,
                parent=node,
                end_lineno=None,
                end_col_offset=None,
            )
            for base in basenames
        ],
        body=[],
        decorators=None,
        doc_node=nodes.Const(value=doc) if doc else None,
    )
    return node
Referenced by _add_dunder_class(), _astroid_bootstrapping(), and _base_class_object_build().
build_from_import()
nodes.ImportFrom astroid.raw_building.build_from_import (str fromname, list[str] names)
create and initialize an astroid ImportFrom import statement
Definition at line 232 of file raw_building.py.
def build_from_import(fromname: str, names: list[str]) -> nodes.ImportFrom:
    """create and initialize an astroid ImportFrom import statement"""
    return nodes.ImportFrom(fromname, [(name, None) for name in names])
build_function()
nodes.FunctionDef astroid.raw_building.build_function (str name, list[str] | None args = None, list[str] | None posonlyargs = None, list[Any] | None defaults = None, str | None doc = None, list[str] | None kwonlyargs = None, list[Any] | None kwonlydefaults = None)
create and initialize an astroid FunctionDef node
Definition at line 129 of file raw_building.py.
) -> nodes.FunctionDef:
    """create and initialize an astroid FunctionDef node"""
    # first argument is now a list of decorators
    func = nodes.FunctionDef(
        name,
        lineno=0,
        col_offset=0,
        parent=node_classes.Unknown(),
        end_col_offset=0,
        end_lineno=0,
    )
    argsnode = nodes.Arguments(parent=func, vararg=None, kwarg=None)
    # If args is None we don't have any information about the signature
    # (in contrast to when there are no arguments and args == []). We pass
    # this to the builder to indicate this.
    if args is not None:
        # We set the lineno and col_offset to 0 because we don't have any
        # information about the location of the function definition.
        arguments = [
            nodes.AssignName(
                name=arg,
                parent=argsnode,
                lineno=0,
                col_offset=0,
                end_lineno=None,
                end_col_offset=None,
            )
            for arg in args
        ]
    else:
        arguments = None
    default_nodes: list[nodes.NodeNG] | None
    if defaults is None:
        default_nodes = None
    else:
        default_nodes = []
        for default in defaults:
            default_node = nodes.const_factory(default)
            default_node.parent = argsnode
            default_nodes.append(default_node)
    kwonlydefault_nodes: list[nodes.NodeNG | None] | None
    if kwonlydefaults is None:
        kwonlydefault_nodes = None
    else:
        kwonlydefault_nodes = []
        for kwonlydefault in kwonlydefaults:
            kwonlydefault_node = nodes.const_factory(kwonlydefault)
            kwonlydefault_node.parent = argsnode
            kwonlydefault_nodes.append(kwonlydefault_node)
    # We set the lineno and col_offset to 0 because we don't have any
    # information about the location of the kwonly and posonlyargs.
    argsnode.postinit(
        args=arguments,
        defaults=default_nodes,
        kwonlyargs=[
            nodes.AssignName(
                name=arg,
                parent=argsnode,
                lineno=0,
                col_offset=0,
                end_lineno=None,
                end_col_offset=None,
            )
            for arg in kwonlyargs or ()
        ],
        kw_defaults=kwonlydefault_nodes,
        annotations=[],
        posonlyargs=[
            nodes.AssignName(
                name=arg,
                parent=argsnode,
                lineno=0,
                col_offset=0,
                end_lineno=None,
                end_col_offset=None,
            )
            for arg in posonlyargs or ()
        ],
        kwonlyargs_annotations=[],
        posonlyargs_annotations=[],
    )
    func.postinit(
        args=argsnode,
        body=[],
        doc_node=nodes.Const(value=doc) if doc else None,
    )
    if args:
        register_arguments(func)
    return func
References register_arguments().
Referenced by object_build_function(), and object_build_methoddescriptor().
build_module()
nodes.Module astroid.raw_building.build_module (str name, str | None doc = None)
create and initialize an astroid Module node
Definition at line 88 of file raw_building.py.
def build_module(name: str, doc: str | None = None) -> nodes.Module:
    """create and initialize an astroid Module node"""
    node = nodes.Module(name, pure_python=False, package=False)
    node.postinit(
        body=[],
        doc_node=nodes.Const(value=doc) if doc else None,
    )
    return node
Referenced by astroid.raw_building.InspectBuilder.inspect_build(), and astroid.raw_building.InspectBuilder.object_build().
object_build_class()
nodes.ClassDef astroid.raw_building.object_build_class (nodes.Module | nodes.ClassDef node, type member, str localname)
create astroid for a living class object
Definition at line 260 of file raw_building.py.
) -> nodes.ClassDef:
    """create astroid for a living class object"""
    basenames = [base.__name__ for base in member.__bases__]
    return _base_class_object_build(node, member, basenames, localname=localname)
References _base_class_object_build().
Referenced by astroid.raw_building.InspectBuilder.object_build().
object_build_datadescriptor()
nodes.ClassDef astroid.raw_building.object_build_datadescriptor (nodes.Module | nodes.ClassDef node, type member, str name)
create astroid for a living data descriptor object
Definition at line 327 of file raw_building.py.
) -> nodes.ClassDef:
    """create astroid for a living data descriptor object"""
    return _base_class_object_build(node, member, [], name)
References _base_class_object_build().
Referenced by astroid.raw_building.InspectBuilder.object_build().
object_build_function()
None astroid.raw_building.object_build_function (nodes.Module | nodes.ClassDef node, _FunctionTypes member, str localname)
create astroid for a living function object
Definition at line 302 of file raw_building.py.
) -> None:
    """create astroid for a living function object"""
    (
        args,
        posonlyargs,
        defaults,
        kwonlyargs,
        kwonly_defaults,
    ) = _get_args_info_from_callable(member)
    func = build_function(
        getattr(member, "__name__", None) or localname,
        args,
        posonlyargs,
        defaults,
        member.__doc__,
        kwonlyargs=kwonlyargs,
        kwonlydefaults=kwonly_defaults,
    )
    node.add_local_node(func, localname)
References _get_args_info_from_callable(), and build_function().
Referenced by _build_from_function().
object_build_methoddescriptor()
None astroid.raw_building.object_build_methoddescriptor (nodes.Module | nodes.ClassDef node, _FunctionTypes member, str localname)
create astroid for a living method descriptor object
Definition at line 334 of file raw_building.py.
) -> None:
    """create astroid for a living method descriptor object"""
    # FIXME get arguments ?
    func = build_function(
        getattr(member, "__name__", None) or localname, doc=member.__doc__
    )
    node.add_local_node(func, localname)
    _add_dunder_class(func, member)
References _add_dunder_class(), and build_function().
Referenced by _build_from_function(), and astroid.raw_building.InspectBuilder.object_build().
register_arguments()
None astroid.raw_building.register_arguments (nodes.FunctionDef func, list | None args = None)
add given arguments to local
args is a list that may contains nested lists
(i.e. def func(a, (b, c, d)): ...)
Definition at line 237 of file raw_building.py.
def register_arguments(func: nodes.FunctionDef, args: list | None = None) -> None:
    """add given arguments to local
    args is a list that may contains nested lists
    (i.e. def func(a, (b, c, d)): ...)
    """
    # If no args are passed in, get the args from the function.
    if args is None:
        if func.args.vararg:
            func.set_local(func.args.vararg, func.args)
        if func.args.kwarg:
            func.set_local(func.args.kwarg, func.args)
        args = func.args.args
        # If the function has no args, there is nothing left to do.
        if args is None:
            return
    for arg in args:
        if isinstance(arg, nodes.AssignName):
            func.set_local(arg.name, arg)
        else:
            register_arguments(func, arg.elts)
References register_arguments().
Referenced by build_function(), and register_arguments().
Variable Documentation
_CONSTANTS
astroid.raw_building._CONSTANTS = tuple(node_classes.CONST_CLS) protected
Definition at line 41 of file raw_building.py.
_FunctionTypes
astroid.raw_building._FunctionTypes protected
Initial value:
=  Union[
    types.FunctionType,
    types.MethodType,
    types.BuiltinFunctionType,
    types.WrapperDescriptorType,
    types.MethodDescriptorType,
    types.ClassMethodDescriptorType,
]
Definition at line 31 of file raw_building.py.
logger
astroid.raw_building.logger = logging.getLogger(__name__)
Definition at line 28 of file raw_building.py.
TYPE_ELLIPSIS
astroid.raw_building.TYPE_ELLIPSIS = type(...)
Definition at line 44 of file raw_building.py.
TYPE_NONE
astroid.raw_building.TYPE_NONE = type(None)
Definition at line 42 of file raw_building.py.
TYPE_NOTIMPLEMENTED
astroid.raw_building.TYPE_NOTIMPLEMENTED = type(NotImplemented)
Definition at line 43 of file raw_building.py.