Read&Watch: pip._internal.locations._sysconfig Namespace Reference
pip._internal.locations._sysconfig Namespace Reference
Functions
bool _should_use_osx_framework_prefix ()
str _infer_prefix ()
str _infer_user ()
str _infer_home ()
Scheme get_scheme (str dist_name, bool user=False, typing.Optional[str] home=None, typing.Optional[str] root=None, bool isolated=False, typing.Optional[str] prefix=None)
str get_bin_prefix ()
str get_purelib ()
str get_platlib ()
Variables
logger = logging.getLogger(__name__)
_AVAILABLE_SCHEMES = set(sysconfig.get_scheme_names())
_PREFERRED_SCHEME_API = getattr(sysconfig, "get_preferred_scheme", None)
list _HOME_KEYS
Function Documentation
_infer_home()
str pip._internal.locations._sysconfig._infer_home () protected
Try to find a home for the current platform.
Definition at line 101 of file _sysconfig.py.
def _infer_home() -> str:
    """Try to find a home for the current platform."""
    if _PREFERRED_SCHEME_API:
        return _PREFERRED_SCHEME_API("home")
    suffixed = f"{os.name}_home"
    if suffixed in _AVAILABLE_SCHEMES:
        return suffixed
    return "posix_home"
# Update these keys if the user sets a custom home.
References _PREFERRED_SCHEME_API.
Referenced by get_scheme().
_infer_prefix()
str pip._internal.locations._sysconfig._infer_prefix () protected
Try to find a prefix scheme for the current platform.
This tries:
* A special ``osx_framework_library`` for Python distributed by Apple's
  Command Line Tools, when not running in a virtual environment.
* Implementation + OS, used by PyPy on Windows (``pypy_nt``).
* Implementation without OS, used by PyPy on POSIX (``pypy``).
* OS + "prefix", used by CPython on POSIX (``posix_prefix``).
* Just the OS name, used by CPython on Windows (``nt``).
If none of the above works, fall back to ``posix_prefix``.
Definition at line 55 of file _sysconfig.py.
def _infer_prefix() -> str:
    """Try to find a prefix scheme for the current platform.
    This tries:
    * A special ``osx_framework_library`` for Python distributed by Apple's
      Command Line Tools, when not running in a virtual environment.
    * Implementation + OS, used by PyPy on Windows (``pypy_nt``).
    * Implementation without OS, used by PyPy on POSIX (``pypy``).
    * OS + "prefix", used by CPython on POSIX (``posix_prefix``).
    * Just the OS name, used by CPython on Windows (``nt``).
    If none of the above works, fall back to ``posix_prefix``.
    """
    if _PREFERRED_SCHEME_API:
        return _PREFERRED_SCHEME_API("prefix")
    if _should_use_osx_framework_prefix():
        return "osx_framework_library"
    implementation_suffixed = f"{sys.implementation.name}_{os.name}"
    if implementation_suffixed in _AVAILABLE_SCHEMES:
        return implementation_suffixed
    if sys.implementation.name in _AVAILABLE_SCHEMES:
        return sys.implementation.name
    suffixed = f"{os.name}_prefix"
    if suffixed in _AVAILABLE_SCHEMES:
        return suffixed
    if os.name in _AVAILABLE_SCHEMES:  # On Windows, prefx is just called "nt".
        return os.name
    return "posix_prefix"
References _PREFERRED_SCHEME_API, and _should_use_osx_framework_prefix().
Referenced by get_scheme().
_infer_user()
str pip._internal.locations._sysconfig._infer_user () protected
Try to find a user scheme for the current platform.
Definition at line 86 of file _sysconfig.py.
def _infer_user() -> str:
    """Try to find a user scheme for the current platform."""
    if _PREFERRED_SCHEME_API:
        return _PREFERRED_SCHEME_API("user")
    if is_osx_framework() and not running_under_virtualenv():
        suffixed = "osx_framework_user"
    else:
        suffixed = f"{os.name}_user"
    if suffixed in _AVAILABLE_SCHEMES:
        return suffixed
    if "posix_user" not in _AVAILABLE_SCHEMES:  # User scheme unavailable.
        raise UserInstallationInvalid()
    return "posix_user"
References _PREFERRED_SCHEME_API.
Referenced by get_scheme().
_should_use_osx_framework_prefix()
bool pip._internal.locations._sysconfig._should_use_osx_framework_prefix () protected
Check for Apple's ``osx_framework_library`` scheme.
Python distributed by Apple's Command Line Tools has this special scheme
that's used when:
* This is a framework build.
* We are installing into the system prefix.
This does not account for ``pip install --prefix`` (also means we're not
installing to the system prefix), which should use ``posix_prefix``, but
logic here means ``_infer_prefix()`` outputs ``osx_framework_library``. But
since ``prefix`` is not available for ``sysconfig.get_default_scheme()``,
which is the stdlib replacement for ``_infer_prefix()``, presumably Apple
wouldn't be able to magically switch between ``osx_framework_library`` and
``posix_prefix``. ``_infer_prefix()`` returning ``osx_framework_library``
means its behavior is consistent whether we use the stdlib implementation
or our own, and we deal with this special case in ``get_scheme()`` instead.
Definition at line 29 of file _sysconfig.py.
def _should_use_osx_framework_prefix() -> bool:
    """Check for Apple's ``osx_framework_library`` scheme.
    Python distributed by Apple's Command Line Tools has this special scheme
    that's used when:
    * This is a framework build.
    * We are installing into the system prefix.
    This does not account for ``pip install --prefix`` (also means we're not
    installing to the system prefix), which should use ``posix_prefix``, but
    logic here means ``_infer_prefix()`` outputs ``osx_framework_library``. But
    since ``prefix`` is not available for ``sysconfig.get_default_scheme()``,
    which is the stdlib replacement for ``_infer_prefix()``, presumably Apple
    wouldn't be able to magically switch between ``osx_framework_library`` and
    ``posix_prefix``. ``_infer_prefix()`` returning ``osx_framework_library``
    means its behavior is consistent whether we use the stdlib implementation
    or our own, and we deal with this special case in ``get_scheme()`` instead.
    """
    return (
        "osx_framework_library" in _AVAILABLE_SCHEMES
        and not running_under_virtualenv()
        and is_osx_framework()
    )
Referenced by _infer_prefix().
get_bin_prefix()
str pip._internal.locations._sysconfig.get_bin_prefix ()
Definition at line 202 of file _sysconfig.py.
def get_bin_prefix() -> str:
    # Forcing to use /usr/local/bin for standard macOS framework installs.
    if sys.platform[:6] == "darwin" and sys.prefix[:16] == "/System/Library/":
        return "/usr/local/bin"
    return sysconfig.get_paths()["scripts"]
get_platlib()
str pip._internal.locations._sysconfig.get_platlib ()
Definition at line 213 of file _sysconfig.py.
def get_platlib() -> str:
    return sysconfig.get_paths()["platlib"]
get_purelib()
str pip._internal.locations._sysconfig.get_purelib ()
Definition at line 209 of file _sysconfig.py.
def get_purelib() -> str:
    return sysconfig.get_paths()["purelib"]
get_scheme()
Scheme pip._internal.locations._sysconfig.get_scheme (str dist_name, bool user = False, typing.Optional[str] home = None, typing.Optional[str] root = None, bool isolated = False, typing.Optional[str] prefix = None)
Get the "scheme" corresponding to the input parameters.
:param dist_name: the name of the package to retrieve the scheme for, used
    in the headers scheme path
:param user: indicates to use the "user" scheme
:param home: indicates to use the "home" scheme
:param root: root under which other directories are re-based
:param isolated: ignored, but kept for distutils compatibility (where
    this controls whether the user-site pydistutils.cfg is honored)
:param prefix: indicates to use the "prefix" scheme and provides the
    base directory for the same
Definition at line 124 of file _sysconfig.py.
) -> Scheme:
    """
    Get the "scheme" corresponding to the input parameters.
    :param dist_name: the name of the package to retrieve the scheme for, used
        in the headers scheme path
    :param user: indicates to use the "user" scheme
    :param home: indicates to use the "home" scheme
    :param root: root under which other directories are re-based
    :param isolated: ignored, but kept for distutils compatibility (where
        this controls whether the user-site pydistutils.cfg is honored)
    :param prefix: indicates to use the "prefix" scheme and provides the
        base directory for the same
    """
    if user and prefix:
        raise InvalidSchemeCombination("--user", "--prefix")
    if home and prefix:
        raise InvalidSchemeCombination("--home", "--prefix")
    if home is not None:
        scheme_name = _infer_home()
    elif user:
        scheme_name = _infer_user()
    else:
        scheme_name = _infer_prefix()
    # Special case: When installing into a custom prefix, use posix_prefix
    # instead of osx_framework_library. See _should_use_osx_framework_prefix()
    # docstring for details.
    if prefix is not None and scheme_name == "osx_framework_library":
        scheme_name = "posix_prefix"
    if home is not None:
        variables = {k: home for k in _HOME_KEYS}
    elif prefix is not None:
        variables = {k: prefix for k in _HOME_KEYS}
    else:
        variables = {}
    paths = sysconfig.get_paths(scheme=scheme_name, vars=variables)
    # Logic here is very arbitrary, we're doing it for compatibility, don't ask.
    # 1. Pip historically uses a special header path in virtual environments.
    # 2. If the distribution name is not known, distutils uses 'UNKNOWN'. We
    #    only do the same when not running in a virtual environment because
    #    pip's historical header path logic (see point 1) did not do this.
    if running_under_virtualenv():
        if user:
            base = variables.get("userbase", sys.prefix)
        else:
            base = variables.get("base", sys.prefix)
        python_xy = f"python{get_major_minor_version()}"
        paths["include"] = os.path.join(base, "include", "site", python_xy)
    elif not dist_name:
        dist_name = "UNKNOWN"
    scheme = Scheme(
        platlib=paths["platlib"],
        purelib=paths["purelib"],
        headers=os.path.join(paths["include"], dist_name),
        scripts=paths["scripts"],
        data=paths["data"],
    )
    if root is not None:
        converted_keys = {}
        for key in SCHEME_KEYS:
            converted_keys[key] = change_root(root, getattr(scheme, key))
        scheme = Scheme(**converted_keys)
    return scheme
References _infer_home(), _infer_prefix(), and _infer_user().
Variable Documentation
_AVAILABLE_SCHEMES
pip._internal.locations._sysconfig._AVAILABLE_SCHEMES = set(sysconfig.get_scheme_names()) protected
Definition at line 24 of file _sysconfig.py.
_HOME_KEYS
list pip._internal.locations._sysconfig._HOME_KEYS protected
Initial value:
=  [
    "installed_base",
    "base",
    "installed_platbase",
    "platbase",
    "prefix",
    "exec_prefix",
]
Definition at line 112 of file _sysconfig.py.
_PREFERRED_SCHEME_API
pip._internal.locations._sysconfig._PREFERRED_SCHEME_API = getattr(sysconfig, "get_preferred_scheme", None) protected
Definition at line 26 of file _sysconfig.py.
Referenced by _infer_home(), _infer_prefix(), and _infer_user().
logger
pip._internal.locations._sysconfig.logger = logging.getLogger(__name__)
Definition at line 13 of file _sysconfig.py.