Read&Watch: PIL.ImageTk Namespace Reference
PIL.ImageTk Namespace Reference
Classes
class BitmapImage
class PhotoImage
Functions
ImageFile.ImageFile|None _get_image_from_kw (dict[str, Any] kw)
None _pyimagingtkcall (str command, PhotoImage|tkinter.PhotoImage photo, CapsuleType ptr)
Image.Image getimage (PhotoImage photo)
None _show (Image.Image image, str|None title)
Variables
BitmapImage|PhotoImage image
Function Documentation
_get_image_from_kw()
ImageFile.ImageFile | None PIL.ImageTk._get_image_from_kw (dict[str, Any] kw) protected
Definition at line 42 of file ImageTk.py.
def _get_image_from_kw(kw: dict[str, Any]) -> ImageFile.ImageFile | None:
    source = None
    if "file" in kw:
        source = kw.pop("file")
    elif "data" in kw:
        source = BytesIO(kw.pop("data"))
    if not source:
        return None
    return Image.open(source)
Referenced by PIL.ImageTk.BitmapImage.__init__(), and PIL.ImageTk.PhotoImage.__init__().
_pyimagingtkcall()
None PIL.ImageTk._pyimagingtkcall (str command, PhotoImage | tkinter.PhotoImage photo, CapsuleType ptr) protected
Definition at line 53 of file ImageTk.py.
) -> None:
    tk = photo.tk
    try:
        tk.call(command, photo, repr(ptr))
    except tkinter.TclError:
        # activate Tkinter hook
        # may raise an error if it cannot attach to Tkinter
        from . import _imagingtk
        _imagingtk.tkinit(tk.interpaddr())
        tk.call(command, photo, repr(ptr))
# --------------------------------------------------------------------
# PhotoImage
Referenced by getimage(), and PIL.ImageTk.PhotoImage.paste().
_show()
None PIL.ImageTk._show (Image.Image image, str | None title) protected
Helper for the Image.show method.
Definition at line 268 of file ImageTk.py.
def _show(image: Image.Image, title: str | None) -> None:
    """Helper for the Image.show method."""
    class UI(tkinter.Label):
        def __init__(self, master: tkinter.Toplevel, im: Image.Image) -> None:
            self.image: BitmapImage | PhotoImage
            if im.mode == "1":
                self.image = BitmapImage(im, foreground="white", master=master)
            else:
                self.image = PhotoImage(im, master=master)
            if TYPE_CHECKING:
                image = cast(tkinter._Image, self.image)
            else:
                image = self.image
            super().__init__(master, image=image, bg="black", bd=0)
    if not getattr(tkinter, "_default_root"):
        msg = "tkinter not initialized"
        raise OSError(msg)
    top = tkinter.Toplevel()
    if title:
        top.title(title)
    UI(top, image).pack()
getimage()
Image.Image PIL.ImageTk.getimage (PhotoImage photo)
Copies the contents of a PhotoImage to a PIL image memory.
Definition at line 259 of file ImageTk.py.
def getimage(photo: PhotoImage) -> Image.Image:
    """Copies the contents of a PhotoImage to a PIL image memory."""
    im = Image.new("RGBA", (photo.width(), photo.height()))
    _pyimagingtkcall("PyImagingPhotoGet", photo, im.getim())
    return im
References _pyimagingtkcall().
Variable Documentation
image
BitmapImage | PhotoImage PIL.ImageTk.image
Definition at line 273 of file ImageTk.py.