Read&Watch: django.core.files.locks Namespace Reference
django.core.files.locks Namespace Reference
Classes
class _OFFSET
class _OFFSET_UNION
class OVERLAPPED
Functions
_fd (f)
lock (f, flags)
unlock (f)
Variables
int LOCK_SH = 0
int LOCK_NB = 0x1
int LOCK_EX = 0x2
ULONG_PTR = c_int64
PVOID = c_void_p
LPOVERLAPPED
kernel32 = WinDLL("kernel32")
LockFileEx = kernel32.LockFileEx
restype
argtypes
UnlockFileEx = kernel32.UnlockFileEx
Detailed Description
Portable file locking utilities.
Based partially on an example by Jonathan Feignberg in the Python
Cookbook [1] (licensed under the Python Software License) and a ctypes port by
Anatoly Techtonik for Roundup [2] (license [3]).
[1] https://code.activestate.com/recipes/65203/
[2] https://sourceforge.net/p/roundup/code/ci/default/tree/roundup/backends/portalocker.py  # NOQA
[3] https://sourceforge.net/p/roundup/code/ci/default/tree/COPYING.txt
Example Usage::
    >>> from django.core.files import locks
    >>> with open('./file', 'wb') as f:
    ...     locks.lock(f, locks.LOCK_EX)
    ...     f.write('Django')
Function Documentation
_fd()
django.core.files.locks._fd (f) protected
Get a filedescriptor from something which could be a file or an fd.
Definition at line 25 of file locks.py.
def _fd(f):
    """Get a filedescriptor from something which could be a file or an fd."""
    return f.fileno() if hasattr(f, "fileno") else f
Referenced by lock(), and unlock().
lock()
django.core.files.locks.lock (f, flags)
Definition at line 85 of file locks.py.
    def lock(f, flags):
        hfile = msvcrt.get_osfhandle(_fd(f))
        overlapped = OVERLAPPED()
        ret = LockFileEx(hfile, flags, 0, 0, 0xFFFF0000, byref(overlapped))
        return bool(ret)
References _fd(), and LockFileEx.
unlock()
django.core.files.locks.unlock (f)
Definition at line 91 of file locks.py.
    def unlock(f):
        hfile = msvcrt.get_osfhandle(_fd(f))
        overlapped = OVERLAPPED()
        ret = UnlockFileEx(hfile, 0, 0, 0xFFFF0000, byref(overlapped))
        return bool(ret)
References _fd(), and UnlockFileEx.
Variable Documentation
argtypes
django.core.files.locks.argtypes
Definition at line 80 of file locks.py.
kernel32
django.core.files.locks.kernel32 = WinDLL("kernel32")
Definition at line 77 of file locks.py.
LOCK_EX
int django.core.files.locks.LOCK_EX = 0x2
Definition at line 47 of file locks.py.
LOCK_NB
int django.core.files.locks.LOCK_NB = 0x1
Definition at line 46 of file locks.py.
LOCK_SH
int django.core.files.locks.LOCK_SH = 0
Definition at line 45 of file locks.py.
LockFileEx
django.core.files.locks.LockFileEx = kernel32.LockFileEx
Definition at line 78 of file locks.py.
Referenced by lock().
LPOVERLAPPED
django.core.files.locks.LPOVERLAPPED
Definition at line 74 of file locks.py.
PVOID
django.core.files.locks.PVOID = c_void_p
Definition at line 55 of file locks.py.
restype
django.core.files.locks.restype
Definition at line 79 of file locks.py.
ULONG_PTR
django.core.files.locks.ULONG_PTR = c_int64
Definition at line 52 of file locks.py.
UnlockFileEx
django.core.files.locks.UnlockFileEx = kernel32.UnlockFileEx
Definition at line 81 of file locks.py.
Referenced by unlock().