Read&Watch: django.utils.translation.trans_real Namespace Reference
django.utils.translation.trans_real Namespace Reference
Classes
class DjangoTranslation
class TranslationCatalog
Functions
reset_cache (*, setting, **kwargs)
translation (language)
activate (language)
deactivate ()
deactivate_all ()
get_language ()
get_language_bidi ()
catalog ()
gettext (message)
pgettext (context, message)
gettext_noop (message)
do_ntranslate (singular, plural, number, translation_function)
ngettext (singular, plural, number)
npgettext (context, singular, plural, number)
all_locale_paths ()
check_for_language (lang_code)
get_languages ()
get_supported_language_variant (lang_code, strict=False)
get_language_from_path (path, strict=False)
get_language_from_request (request, check_path=False)
_parse_accept_lang_header (lang_string)
parse_accept_lang_header (lang_string)
Variables
dict _translations = {}
_active = Local()
_default = None
str CONTEXT_SEPARATOR = "\x04"
int LANGUAGE_CODE_MAX_LENGTH = 500
accept_language_re
language_code_re
language_code_prefix_re = _lazy_re_compile(r"^/(\w+([@-]\w+){0,2})(/|$)")
Detailed Description
Translation helper functions.
Function Documentation
_parse_accept_lang_header()
django.utils.translation.trans_real._parse_accept_lang_header (lang_string) protected
Parse the lang_string, which is the body of an HTTP Accept-Language
header, and return a tuple of (lang, q-value), ordered by 'q' values.
Return an empty tuple if there are any format errors in lang_string.
Definition at line 610 of file trans_real.py.
def _parse_accept_lang_header(lang_string):
    """
    Parse the lang_string, which is the body of an HTTP Accept-Language
    header, and return a tuple of (lang, q-value), ordered by 'q' values.
    Return an empty tuple if there are any format errors in lang_string.
    """
    result = []
    pieces = accept_language_re.split(lang_string.lower())
    if pieces[-1]:
        return ()
    for i in range(0, len(pieces) - 1, 3):
        first, lang, priority = pieces[i : i + 3]
        if first:
            return ()
        if priority:
            priority = float(priority)
        else:
            priority = 1.0
        result.append((lang, priority))
    result.sort(key=lambda k: k[1], reverse=True)
    return tuple(result)
Referenced by parse_accept_lang_header().
activate()
django.utils.translation.trans_real.activate (language)
Fetch the translation object for a given language and install it as the
current translation object for the current thread.
Definition at line 298 of file trans_real.py.
def activate(language):
    """
    Fetch the translation object for a given language and install it as the
    current translation object for the current thread.
    """
    if not language:
        return
    _active.value = translation(language)
all_locale_paths()
django.utils.translation.trans_real.all_locale_paths ()
Return a list of paths to user-provides languages files.
Definition at line 449 of file trans_real.py.
def all_locale_paths():
    """
    Return a list of paths to user-provides languages files.
    """
    globalpath = os.path.join(
        os.path.dirname(sys.modules[settings.__module__].__file__), "locale"
    )
    app_paths = []
    for app_config in apps.get_app_configs():
        locale_path = os.path.join(app_config.path, "locale")
        if os.path.exists(locale_path):
            app_paths.append(locale_path)
    return [globalpath, *settings.LOCALE_PATHS, *app_paths]
@functools.lru_cache(maxsize=1000)
Referenced by check_for_language().
catalog()
django.utils.translation.trans_real.catalog ()
Return the current active catalog for further processing.
This can be used if you need to modify the catalog or want to access the
whole message catalog instead of just translating one string.
Definition at line 354 of file trans_real.py.
def catalog():
    """
    Return the current active catalog for further processing.
    This can be used if you need to modify the catalog or want to access the
    whole message catalog instead of just translating one string.
    """
    global _default
    t = getattr(_active, "value", None)
    if t is not None:
        return t
    if _default is None:
        _default = translation(settings.LANGUAGE_CODE)
    return _default
check_for_language()
django.utils.translation.trans_real.check_for_language (lang_code)
Check whether there is a global language file for the given language
code. This is used to decide whether a user-provided language is
available.
lru_cache should have a maxsize to prevent from memory exhaustion attacks,
as the provided language codes are taken from the HTTP request. See also
<https://www.djangoproject.com/weblog/2007/oct/26/security-fix/>.
Definition at line 465 of file trans_real.py.
def check_for_language(lang_code):
    """
    Check whether there is a global language file for the given language
    code. This is used to decide whether a user-provided language is
    available.
    lru_cache should have a maxsize to prevent from memory exhaustion attacks,
    as the provided language codes are taken from the HTTP request. See also
    <https://www.djangoproject.com/weblog/2007/oct/26/security-fix/>.
    """
    # First, a quick check to make sure lang_code is well-formed (#21458)
    if lang_code is None or not language_code_re.search(lang_code):
        return False
    return any(
        gettext_module.find("django", path, [to_locale(lang_code)]) is not None
        for path in all_locale_paths()
    )
@functools.lru_cache
References all_locale_paths(), and django.utils.translation.to_locale().
Referenced by get_language_from_request(), and get_supported_language_variant().
deactivate()
django.utils.translation.trans_real.deactivate ()
Uninstall the active translation object so that further _() calls resolve
to the default translation object.
Definition at line 308 of file trans_real.py.
def deactivate():
    """
    Uninstall the active translation object so that further _() calls resolve
    to the default translation object.
    """
    if hasattr(_active, "value"):
        del _active.value
deactivate_all()
django.utils.translation.trans_real.deactivate_all ()
Make the active translation object a NullTranslations() instance. This is
useful when we want delayed translations to appear as the original string
for some reason.
Definition at line 317 of file trans_real.py.
def deactivate_all():
    """
    Make the active translation object a NullTranslations() instance. This is
    useful when we want delayed translations to appear as the original string
    for some reason.
    """
    _active.value = gettext_module.NullTranslations()
    _active.value.to_language = lambda *args: None
do_ntranslate()
django.utils.translation.trans_real.do_ntranslate (singular, plural, number, translation_function)
Definition at line 417 of file trans_real.py.
def do_ntranslate(singular, plural, number, translation_function):
    global _default
    t = getattr(_active, "value", None)
    if t is not None:
        return getattr(t, translation_function)(singular, plural, number)
    if _default is None:
        _default = translation(settings.LANGUAGE_CODE)
    return getattr(_default, translation_function)(singular, plural, number)
Referenced by ngettext().
get_language()
django.utils.translation.trans_real.get_language ()
Return the currently selected language.
Definition at line 327 of file trans_real.py.
def get_language():
    """Return the currently selected language."""
    t = getattr(_active, "value", None)
    if t is not None:
        try:
            return t.to_language()
        except AttributeError:
            pass
    # If we don't have a real translation object, assume it's the default language.
    return settings.LANGUAGE_CODE
Referenced by get_language_bidi().
get_language_bidi()
django.utils.translation.trans_real.get_language_bidi ()
Return selected language's BiDi layout.
* False = left-to-right layout
* True = right-to-left layout
Definition at line 339 of file trans_real.py.
def get_language_bidi():
    """
    Return selected language's BiDi layout.
    * False = left-to-right layout
    * True = right-to-left layout
    """
    lang = get_language()
    if lang is None:
        return False
    else:
        base_lang = get_language().split("-")[0]
        return base_lang in settings.LANGUAGES_BIDI
References get_language().
get_language_from_path()
django.utils.translation.trans_real.get_language_from_path (path, strict = False)
Return the language code if there's a valid language code found in `path`.
If `strict` is False (the default), look for a country-specific variant
when neither the language code nor its generic variant is found.
Definition at line 545 of file trans_real.py.
def get_language_from_path(path, strict=False):
    """
    Return the language code if there's a valid language code found in `path`.
    If `strict` is False (the default), look for a country-specific variant
    when neither the language code nor its generic variant is found.
    """
    regex_match = language_code_prefix_re.match(path)
    if not regex_match:
        return None
    lang_code = regex_match[1]
    try:
        return get_supported_language_variant(lang_code, strict=strict)
    except LookupError:
        return None
References get_supported_language_variant().
Referenced by get_language_from_request().
get_language_from_request()
django.utils.translation.trans_real.get_language_from_request (request, check_path = False)
Analyze the request to find what language the user wants the system to
show. Only languages listed in settings.LANGUAGES are taken into account.
If the user requests a sublanguage where we have a main language, we send
out the main language.
If check_path is True, the URL path prefix will be checked for a language
code, otherwise this is skipped for backwards compatibility.
Definition at line 562 of file trans_real.py.
def get_language_from_request(request, check_path=False):
    """
    Analyze the request to find what language the user wants the system to
    show. Only languages listed in settings.LANGUAGES are taken into account.
    If the user requests a sublanguage where we have a main language, we send
    out the main language.
    If check_path is True, the URL path prefix will be checked for a language
    code, otherwise this is skipped for backwards compatibility.
    """
    if check_path:
        lang_code = get_language_from_path(request.path_info)
        if lang_code is not None:
            return lang_code
    lang_code = request.COOKIES.get(settings.LANGUAGE_COOKIE_NAME)
    if (
        lang_code is not None
        and lang_code in get_languages()
        and check_for_language(lang_code)
    ):
        return lang_code
    try:
        return get_supported_language_variant(lang_code)
    except LookupError:
        pass
    accept = request.META.get("HTTP_ACCEPT_LANGUAGE", "")
    for accept_lang, unused in parse_accept_lang_header(accept):
        if accept_lang == "*":
            break
        if not language_code_re.search(accept_lang):
            continue
        try:
            return get_supported_language_variant(accept_lang)
        except LookupError:
            continue
    try:
        return get_supported_language_variant(settings.LANGUAGE_CODE)
    except LookupError:
        return settings.LANGUAGE_CODE
@functools.lru_cache(maxsize=1000)
References check_for_language(), get_language_from_path(), get_languages(), get_supported_language_variant(), and parse_accept_lang_header().
get_languages()
django.utils.translation.trans_real.get_languages ()
Cache of settings.LANGUAGES in a dictionary for easy lookups by key.
Convert keys to lowercase as they should be treated as case-insensitive.
Definition at line 485 of file trans_real.py.
def get_languages():
    """
    Cache of settings.LANGUAGES in a dictionary for easy lookups by key.
    Convert keys to lowercase as they should be treated as case-insensitive.
    """
    return {key.lower(): value for key, value in dict(settings.LANGUAGES).items()}
@functools.lru_cache(maxsize=1000)
Referenced by get_language_from_request(), and get_supported_language_variant().
get_supported_language_variant()
django.utils.translation.trans_real.get_supported_language_variant (lang_code, strict = False)
Return the language code that's listed in supported languages, possibly
selecting a more generic variant. Raise LookupError if nothing is found.
If `strict` is False (the default), look for a country-specific variant
when neither the language code nor its generic variant is found.
The language code is truncated to a maximum length to avoid potential
denial of service attacks.
lru_cache should have a maxsize to prevent from memory exhaustion attacks,
as the provided language codes are taken from the HTTP request. See also
<https://www.djangoproject.com/weblog/2007/oct/26/security-fix/>.
Definition at line 494 of file trans_real.py.
def get_supported_language_variant(lang_code, strict=False):
    """
    Return the language code that's listed in supported languages, possibly
    selecting a more generic variant. Raise LookupError if nothing is found.
    If `strict` is False (the default), look for a country-specific variant
    when neither the language code nor its generic variant is found.
    The language code is truncated to a maximum length to avoid potential
    denial of service attacks.
    lru_cache should have a maxsize to prevent from memory exhaustion attacks,
    as the provided language codes are taken from the HTTP request. See also
    <https://www.djangoproject.com/weblog/2007/oct/26/security-fix/>.
    """
    if lang_code:
        # Truncate the language code to a maximum length to avoid potential
        # denial of service attacks.
        if len(lang_code) > LANGUAGE_CODE_MAX_LENGTH:
            if (
                not strict
                and (index := lang_code.rfind("-", 0, LANGUAGE_CODE_MAX_LENGTH)) > 0
            ):
                # There is a generic variant under the maximum length accepted length.
                lang_code = lang_code[:index]
            else:
                raise LookupError(lang_code)
        # If 'zh-hant-tw' is not supported, try special fallback or subsequent
        # language codes i.e. 'zh-hant' and 'zh'.
        possible_lang_codes = [lang_code]
        try:
            possible_lang_codes.extend(LANG_INFO[lang_code]["fallback"])
        except KeyError:
            pass
        i = None
        while (i := lang_code.rfind("-", 0, i)) > -1:
            possible_lang_codes.append(lang_code[:i])
        generic_lang_code = possible_lang_codes[-1]
        supported_lang_codes = get_languages()
        for code in possible_lang_codes:
            if code.lower() in supported_lang_codes and check_for_language(code):
                return code
        if not strict:
            # if fr-fr is not supported, try fr-ca.
            for supported_code in supported_lang_codes:
                if supported_code.startswith(generic_lang_code + "-"):
                    return supported_code
    raise LookupError(lang_code)
References check_for_language(), and get_languages().
Referenced by get_language_from_path(), and get_language_from_request().
gettext()
django.utils.translation.trans_real.gettext (message)
Translate the 'message' string. It uses the current thread to find the
translation object to use. If no current translation is activated, the
message will be run through the default translation object.
Definition at line 370 of file trans_real.py.
def gettext(message):
    """
    Translate the 'message' string. It uses the current thread to find the
    translation object to use. If no current translation is activated, the
    message will be run through the default translation object.
    """
    global _default
    eol_message = message.replace("\r\n", "\n").replace("\r", "\n")
    if eol_message:
        _default = _default or translation(settings.LANGUAGE_CODE)
        translation_object = getattr(_active, "value", _default)
        result = translation_object.gettext(eol_message)
    else:
        # Return an empty value of the corresponding type if an empty message
        # is given, instead of metadata, which is the default gettext behavior.
        result = type(message)("")
    if isinstance(message, SafeData):
        return mark_safe(result)
    return result
Referenced by pgettext().
gettext_noop()
django.utils.translation.trans_real.gettext_noop (message)
Mark strings for translation but don't translate them now. This can be
used to store strings in global variables that should stay in the base
language (because they might be used externally) and will be translated
later.
Definition at line 407 of file trans_real.py.
def gettext_noop(message):
    """
    Mark strings for translation but don't translate them now. This can be
    used to store strings in global variables that should stay in the base
    language (because they might be used externally) and will be translated
    later.
    """
    return message
ngettext()
django.utils.translation.trans_real.ngettext (singular, plural, number)
Return a string of the translation of either the singular or plural,
based on the number.
Definition at line 428 of file trans_real.py.
def ngettext(singular, plural, number):
    """
    Return a string of the translation of either the singular or plural,
    based on the number.
    """
    return do_ntranslate(singular, plural, number, "ngettext")
References do_ntranslate().
Referenced by npgettext().
npgettext()
django.utils.translation.trans_real.npgettext (context, singular, plural, number)
Definition at line 436 of file trans_real.py.
def npgettext(context, singular, plural, number):
    msgs_with_ctxt = (
        "%s%s%s" % (context, CONTEXT_SEPARATOR, singular),
        "%s%s%s" % (context, CONTEXT_SEPARATOR, plural),
        number,
    )
    result = ngettext(*msgs_with_ctxt)
    if CONTEXT_SEPARATOR in result:
        # Translation not found
        result = ngettext(singular, plural, number)
    return result
References ngettext().
parse_accept_lang_header()
django.utils.translation.trans_real.parse_accept_lang_header (lang_string)
Parse the value of the Accept-Language header up to a maximum length.
The value of the header is truncated to a maximum length to avoid potential
denial of service and memory exhaustion attacks. Excessive memory could be
used if the raw value is very large as it would be cached due to the use of
functools.lru_cache() to avoid repetitive parsing of common header values.
Definition at line 634 of file trans_real.py.
def parse_accept_lang_header(lang_string):
    """
    Parse the value of the Accept-Language header up to a maximum length.
    The value of the header is truncated to a maximum length to avoid potential
    denial of service and memory exhaustion attacks. Excessive memory could be
    used if the raw value is very large as it would be cached due to the use of
    functools.lru_cache() to avoid repetitive parsing of common header values.
    """
    # If the header value doesn't exceed the maximum allowed length, parse it.
    if len(lang_string) <= LANGUAGE_CODE_MAX_LENGTH:
        return _parse_accept_lang_header(lang_string)
    # If there is at least one comma in the value, parse up to the last comma
    # before the max length, skipping any truncated parts at the end of the
    # header value.
    if (index := lang_string.rfind(",", 0, LANGUAGE_CODE_MAX_LENGTH)) > 0:
        return _parse_accept_lang_header(lang_string[:index])
    # Don't attempt to parse if there is only one language-range value which is
    # longer than the maximum allowed length and so truncated.
    return ()
References _parse_accept_lang_header().
Referenced by get_language_from_request().
pgettext()
django.utils.translation.trans_real.pgettext (context, message)
Definition at line 396 of file trans_real.py.
def pgettext(context, message):
    msg_with_ctxt = "%s%s%s" % (context, CONTEXT_SEPARATOR, message)
    result = gettext(msg_with_ctxt)
    if CONTEXT_SEPARATOR in result:
        # Translation not found
        result = message
    elif isinstance(message, SafeData):
        result = mark_safe(result)
    return result
References gettext().
reset_cache()
django.utils.translation.trans_real.reset_cache (* , setting, ** kwargs)
Reset global state when LANGUAGES setting has been changed, as some
languages should no longer be accepted.
Definition at line 62 of file trans_real.py.
def reset_cache(*, setting, **kwargs):
    """
    Reset global state when LANGUAGES setting has been changed, as some
    languages should no longer be accepted.
    """
    if setting in ("LANGUAGES", "LANGUAGE_CODE"):
        check_for_language.cache_clear()
        get_languages.cache_clear()
        get_supported_language_variant.cache_clear()
translation()
django.utils.translation.trans_real.translation (language)
Return a translation object in the default 'django' domain.
Definition at line 288 of file trans_real.py.
def translation(language):
    """
    Return a translation object in the default 'django' domain.
    """
    global _translations
    if language not in _translations:
        _translations[language] = DjangoTranslation(language)
    return _translations[language]
Variable Documentation
_active
django.utils.translation.trans_real._active = Local() protected
Definition at line 26 of file trans_real.py.
_default
django.utils.translation.trans_real._default = None protected
Definition at line 29 of file trans_real.py.
_translations
dict django.utils.translation.trans_real._translations = {} protected
Definition at line 25 of file trans_real.py.
accept_language_re
django.utils.translation.trans_real.accept_language_re
Initial value:
=  _lazy_re_compile(
    ,
    re.VERBOSE,
)
Definition at line 42 of file trans_real.py.
CONTEXT_SEPARATOR
str django.utils.translation.trans_real.CONTEXT_SEPARATOR = "\x04"
Definition at line 32 of file trans_real.py.
LANGUAGE_CODE_MAX_LENGTH
int django.utils.translation.trans_real.LANGUAGE_CODE_MAX_LENGTH = 500
Definition at line 38 of file trans_real.py.
language_code_prefix_re
django.utils.translation.trans_real.language_code_prefix_re = _lazy_re_compile(r"^/(\w+([@-]\w+){0,2})(/|$)")
Definition at line 58 of file trans_real.py.
language_code_re
django.utils.translation.trans_real.language_code_re
Initial value:
=  _lazy_re_compile(
    r"^[a-z]{1,8}(?:-[a-z0-9]{1,8})*(?:@[a-z0-9]{1,20})?$", re.IGNORECASE
)
Definition at line 54 of file trans_real.py.