Read&Watch: django.db.models.expressions Namespace Reference
django.db.models.expressions Namespace Reference
Classes
class BaseExpression
class Case
class Col
class Combinable
class CombinedExpression
class DatabaseDefault
class DurationExpression
class Exists
class Expression
class ExpressionList
class ExpressionWrapper
class F
class Func
class NegatedExpression
class OrderBy
class OrderByList
class OuterRef
class RawSQL
class Ref
class ResolvedOuterRef
class RowRange
class Sliced
class SQLiteNumericMixin
class Star
class Subquery
class TemporalSubtraction
class Value
class ValueRange
class When
class Window
class WindowFrame
class WindowFrameExclusion
Functions
register_combinable_fields (lhs, connector, rhs, result)
_resolve_combined_type (connector, lhs_type, rhs_type)
Variables
list _connector_combinations
_connector_combinators = defaultdict(list)
Function Documentation
_resolve_combined_type()
django.db.models.expressions._resolve_combined_type (connector, lhs_type, rhs_type) protected
Definition at line 691 of file expressions.py.
def _resolve_combined_type(connector, lhs_type, rhs_type):
    combinators = _connector_combinators.get(connector, ())
    for combinator_lhs_type, combinator_rhs_type, combined_type in combinators:
        if issubclass(lhs_type, combinator_lhs_type) and issubclass(
            rhs_type, combinator_rhs_type
        ):
            return combined_type
Referenced by django.db.models.expressions.CombinedExpression._resolve_output_field().
register_combinable_fields()
django.db.models.expressions.register_combinable_fields (lhs, connector, rhs, result)
Register combinable types:
    lhs <connector> rhs -> result
e.g.
    register_combinable_fields(
        IntegerField, Combinable.ADD, FloatField, FloatField
    )
Definition at line 672 of file expressions.py.
def register_combinable_fields(lhs, connector, rhs, result):
    """
    Register combinable types:
        lhs <connector> rhs -> result
    e.g.
        register_combinable_fields(
            IntegerField, Combinable.ADD, FloatField, FloatField
        )
    """
    _connector_combinators[connector].append((lhs, rhs, result))
References register_combinable_fields().
Referenced by register_combinable_fields().
Variable Documentation
_connector_combinations
list django.db.models.expressions._connector_combinations protected
Definition at line 548 of file expressions.py.
_connector_combinators
django.db.models.expressions._connector_combinators = defaultdict(list) protected
Definition at line 669 of file expressions.py.