Read&Watch: django.db.backends.oracle.base Namespace Reference
django.db.backends.oracle.base Namespace Reference
Classes
class _UninitializedOperatorsDescriptor
class DatabaseWrapper
class FormatStylePlaceholderCursor
class OracleParam
class VariableWrapper
Functions
_setup_environment (environ)
wrap_oracle_errors ()
Detailed Description
Oracle database backend for Django.
Requires oracledb: https://oracle.github.io/python-oracledb/
Function Documentation
_setup_environment()
django.db.backends.oracle.base._setup_environment (environ) protected
Definition at line 25 of file base.py.
def _setup_environment(environ):
    # Cygwin requires some special voodoo to set the environment variables
    # properly so that Oracle will see them.
    if platform.system().upper().startswith("CYGWIN"):
        try:
            import ctypes
        except ImportError as e:
            raise ImproperlyConfigured(
                "Error loading ctypes: %s; "
                "the Oracle backend requires ctypes to "
                "operate correctly under Cygwin." % e
            )
        kernel32 = ctypes.CDLL("kernel32")
        for name, value in environ:
            kernel32.SetEnvironmentVariableA(name, value)
    else:
        os.environ.update(environ)
References _setup_environment().
Referenced by _setup_environment().
wrap_oracle_errors()
django.db.backends.oracle.base.wrap_oracle_errors ()
Definition at line 68 of file base.py.
def wrap_oracle_errors():
    try:
        yield
    except Database.DatabaseError as e:
        # oracledb raises a oracledb.DatabaseError exception with the
        # following attributes and values:
        #  code = 2091
        #  message = 'ORA-02091: transaction rolled back
        #            'ORA-02291: integrity constraint (TEST_DJANGOTEST.SYS
        #               _C00102056) violated - parent key not found'
        #            or:
        #            'ORA-00001: unique constraint (DJANGOTEST.DEFERRABLE_
        #               PINK_CONSTRAINT) violated
        # Convert that case to Django's IntegrityError exception.
        x = e.args[0]
        if (
            hasattr(x, "code")
            and hasattr(x, "message")
            and x.code == 2091
            and ("ORA-02291" in x.message or "ORA-00001" in x.message)
        ):
            raise IntegrityError(*tuple(e.args))
        raise
Referenced by django.db.backends.oracle.base.DatabaseWrapper._commit(), django.db.backends.oracle.base.FormatStylePlaceholderCursor.execute(), and django.db.backends.oracle.base.FormatStylePlaceholderCursor.executemany().