Read&Watch: dill._dill Namespace Reference
dill._dill Namespace Reference
Classes
class _attrgetter_helper
class _dictproxy_helper
class _itemgetter_helper
class match
class MetaCatchingDict
End: Shorthands ###.
class Pickler
class PickleWarning
class PicklingWarning
class Sentinel
Shims for different versions of Python and dill.
class Unpickler
class UnpicklingWarning
Functions
__hook__ ()
ndarraysubclassinstance (obj_type)
numpyufunc (obj_type)
numpydtype (obj_type)
get_file_type (*args, **kwargs)
copy (obj, *args, **kwds)
Shorthands (modified from python2.5/lib/pickle.py)
dump (obj, file, protocol=None, byref=None, fmode=None, recurse=None, **kwds)
dumps (obj, protocol=None, byref=None, fmode=None, recurse=None, **kwds)
load (file, ignore=None, **kwds)
loads (str, ignore=None, **kwds)
pickle (t, func)
register (t)
_revert_extension ()
use_diff (on=True)
_create_typemap ()
_unmarshal (string)
_load_type (name)
_create_type (typeobj, *args)
_create_function (fcode, fglobals, fname=None, fdefaults=None, fclosure=None, fdict=None, fkwdefaults=None)
_create_code (*args)
_create_ftype (ftypeobj, func, args, kwds)
_create_typing_tuple (argz, *args)
_create_thread_handle (ident, done, *args)
_create_lock (locked, *args)
_create_rlock (count, owner, *args)
_create_filehandle (name, mode, position, closed, open, strictio, fmode, fdata)
_create_stringi (value, position, closed)
_create_stringo (value, position, closed)
_create_cell (contents=None)
_create_weakref (obj, *args)
_create_weakproxy (obj, callable=False, *args)
_eval_repr (repr_str)
_create_array (f, args, state, npdict=None)
_create_dtypemeta (scalar_type)
_create_namedtuple (name, fieldnames, modulename, defaults=None)
_create_capsule (pointer, name, context, destructor)
_getattr (objclass, name, repr_str)
_get_attr (self, name)
_import_module (import_name, safe=False)
_getattribute (obj, name)
_locate_function (obj, pickler=None)
_setitems (dest, source)
_save_with_postproc (pickler, reduction, is_pickler_dill=None, obj=Getattr.NO_DEFAULT, postproc_list=None)
save_code (pickler, obj)
_repr_dict (obj)
save_module_dict (pickler, obj)
save_dict_view (dicttype)
save_classobj (pickler, obj)
save_generic_alias (pickler, obj)
save_thread_handle (pickler, obj)
save_lock (pickler, obj)
save_rlock (pickler, obj)
save_socket (pickler, obj)
_save_file (pickler, obj, open_)
save_file (pickler, obj)
save_stringi (pickler, obj)
save_stringo (pickler, obj)
save_lru_cache (pickler, obj)
save_super (pickler, obj)
save_instancemethod0 (pickler, obj)
save_wrapper_descriptor (pickler, obj)
save_cell (pickler, obj)
save_dictproxy (pickler, obj)
save_slice (pickler, obj)
save_singleton (pickler, obj)
_proxy_helper (obj)
_locate_object (address, module=None)
save_weakref (pickler, obj)
save_weakproxy (pickler, obj)
_is_builtin_module (module)
_is_imported_module (module)
save_module (pickler, obj)
_get_typedict_type (cls, clsdict, attrs, postproc_list)
_get_typedict_abc (obj, _dict, attrs, postproc_list)
save_type (pickler, obj, postproc_list=None)
save_property (pickler, obj)
save_classmethod (pickler, obj)
save_function (pickler, obj)
save_capsule (pickler, obj)
save_dataclasses_HAS_DEFAULT_FACTORY_CLASS (pickler, obj)
A quick fix for issue #500 This should be removed when a better solution is found.
save_dataclasses_MISSING_TYPE (pickler, obj)
save_dataclasses_KW_ONLY_TYPE (pickler, obj)
save_dataclasses_FIELD_BASE (pickler, obj)
pickles (obj, exact=False, safe=False, **kwds)
check (obj, *args, **kwds)
is_dill (pickler, child=None)
_extend ()
Variables
log = logger
diff = None
bool _use_diff = False
tuple OLD38 = (sys.hexversion < 0x3080000)
tuple OLD39 = (sys.hexversion < 0x3090000)
tuple OLD310 = (sys.hexversion < 0x30a0000)
tuple OLD312a7 = (sys.hexversion < 0x30c00a7)
ExceptHookArgsType = None
ThreadHandleType = None
BufferType = memoryview
ClassType = type
EllipsisType = type(Ellipsis)
NotImplementedType = type(NotImplemented)
SliceType = slice
TypeType = type
XRangeType = range
bool GENERATOR_FAIL = False
EXTENSION_SUFFIXES = tuple(importlib.machinery.EXTENSION_SUFFIXES)
bool HAS_CTYPES = True
IS_PYPY = not hasattr(ctypes, 'pythonapi')
NumpyUfuncType = None
NumpyDType = None
NumpyArrayType = None
CellType = type((lambda x: lambda y: x)(0).__closure__[0])
PartialType = type(partial(int, base=2))
SuperType = type(super(Exception, TypeError()))
ItemGetterType = type(itemgetter(0))
AttrGetterType = type(attrgetter('__repr__'))
LRUCacheType = None
str IS_PYODIDE = 'emscripten'
FileType = get_file_type('rb', buffering=0)
TextWrapperType = get_file_type('r', buffering=-1)
str BufferedRandomType = None if IS_PYODIDE else get_file_type('r+b', buffering=-1)
BufferedReaderType = get_file_type('rb', buffering=-1)
BufferedWriterType = get_file_type('wb', buffering=-1)
PyTextWrapperType = get_file_type('r', buffering=-1, open=_open)
str PyBufferedRandomType = None if IS_PYODIDE else get_file_type('r+b', buffering=-1, open=_open)
PyBufferedReaderType = get_file_type('rb', buffering=-1, open=_open)
PyBufferedWriterType = get_file_type('wb', buffering=-1, open=_open)
InputType = None
IS_IPYTHON = __IPYTHON__
ExitType = None
tuple IPYTHON_SINGLETONS = ('exit', 'quit', 'get_ipython')
int HANDLE_FMODE = 0
File modes : Pickles the file handle, preserving mode.
int CONTENTS_FMODE = 1
int FILE_FMODE = 2
pickle_dispatch_copy = StockPickler.dispatch.copy()
_reverse_typemap = dict(_create_typemap())
x = OrderedDict()
dict _incedental_reverse_typemap
_incedental_types = set(_incedental_reverse_typemap.values())
_typemap = dict((v, k) for k, v in _reverse_typemap.items())
list ALL_CODE_PARAMS
CODE_VERSION = version
CODE_PARAMS = params.split()
ENCODE_PARAMS
_dictproxy_helper_instance = _dictproxy_helper()
dict MAPPING_PROXY_TRICK = __d is (DictProxyType(__d) | _dictproxy_helper_instance)
_CELL_REF = None
_CELL_EMPTY = Sentinel('_CELL_EMPTY')
_PyCapsule_New = ctypes.pythonapi.PyCapsule_New
argtypes
restype
_PyCapsule_GetPointer = ctypes.pythonapi.PyCapsule_GetPointer
_PyCapsule_GetDestructor = ctypes.pythonapi.PyCapsule_GetDestructor
_PyCapsule_GetContext = ctypes.pythonapi.PyCapsule_GetContext
_PyCapsule_GetName = ctypes.pythonapi.PyCapsule_GetName
_PyCapsule_IsValid = ctypes.pythonapi.PyCapsule_IsValid
_PyCapsule_SetContext = ctypes.pythonapi.PyCapsule_SetContext
_PyCapsule_SetDestructor = ctypes.pythonapi.PyCapsule_SetDestructor
_PyCapsule_SetName = ctypes.pythonapi.PyCapsule_SetName
_PyCapsule_SetPointer = ctypes.pythonapi.PyCapsule_SetPointer
str _testcapsule_name = b'dill._dill._testcapsule'
_testcapsule
PyCapsuleType = type(_testcapsule)
Detailed Description
dill: a utility for serialization of python objects
The primary functions in `dill` are :func:`dump` and
:func:`dumps` for serialization ("pickling") to a
file or to a string, respectively, and :func:`load`
and :func:`loads` for deserialization ("unpickling"),
similarly, from a file or from a string. Other notable
functions are :func:`~dill.dump_module` and
:func:`~dill.load_module`, which are used to save and
restore module objects, including an intepreter session.
Based on code written by Oren Tirosh and Armin Ronacher.
Extended to a (near) full set of the builtin types (in types module),
and coded to the pickle interface, by <mmckerns@caltech.edu>.
Initial port to python3 by Jonathan Dobson, continued by mmckerns.
Tested against "all" python types (Std. Lib. CH 1-15 @ 2.7) by mmckerns.
Tested against CH16+ Std. Lib. ... TBD.
Function Documentation
__hook__()
dill._dill.__hook__ ()
Definition at line 113 of file _dill.py.
def __hook__():
    global NumpyArrayType, NumpyDType, NumpyUfuncType
    from numpy import ufunc as NumpyUfuncType
    from numpy import ndarray as NumpyArrayType
    from numpy import dtype as NumpyDType
    return True
Referenced by _create_dtypemeta(), ndarraysubclassinstance(), and numpydtype().
_create_array()
dill._dill._create_array (f, args, state, npdict = None) protected
Definition at line 964 of file _dill.py.
def _create_array(f, args, state, npdict=None):
   #array = numpy.core.multiarray._reconstruct(*args)
    array = f(*args)
    array.__setstate__(state)
    if npdict is not None: # we also have saved state in __dict__
        array.__dict__.update(npdict)
    return array
_create_capsule()
dill._dill._create_capsule (pointer, name, context, destructor) protected
Definition at line 986 of file _dill.py.
def _create_capsule(pointer, name, context, destructor):
    attr_found = False
    try:
        # based on https://github.com/python/cpython/blob/f4095e53ab708d95e019c909d5928502775ba68f/Objects/capsule.c#L209-L231
        uname = name.decode('utf8')
        for i in range(1, uname.count('.')+1):
            names = uname.rsplit('.', i)
            try:
                module = __import__(names[0])
            except ImportError:
                pass
            obj = module
            for attr in names[1:]:
                obj = getattr(obj, attr)
            capsule = obj
            attr_found = True
            break
    except Exception:
        pass
    if attr_found:
        if _PyCapsule_IsValid(capsule, name):
            return capsule
        raise UnpicklingError("%s object exists at %s but a PyCapsule object was expected." % (type(capsule), name))
    else:
        #warnings.warn('Creating a new PyCapsule %s for a C data structure that may not be present in memory. Segmentation faults or other memory errors are possible.' % (name,), UnpicklingWarning)
        capsule = _PyCapsule_New(pointer, name, destructor)
        _PyCapsule_SetContext(capsule, context)
        return capsule
References _PyCapsule_IsValid, _PyCapsule_New, and _PyCapsule_SetContext.
_create_cell()
dill._dill._create_cell (contents = None) protected
Definition at line 941 of file _dill.py.
def _create_cell(contents=None):
    if contents is not _CELL_EMPTY:
        value = contents
    return (lambda: value).__closure__[0]
_create_code()
dill._dill._create_code (* args) protected
Definition at line 680 of file _dill.py.
def _create_code(*args):
    if not isinstance(args[0], int): # co_lnotab stored from >= 3.10
        LNOTAB, *args = args
    else: # from < 3.10 (or pre-LNOTAB storage)
        LNOTAB = b''
    with match(args) as m:
        # Python 3.11/3.12a (18 members)
        if m.case((
            'argcount', 'posonlyargcount', 'kwonlyargcount', 'nlocals', 'stacksize', 'flags',     # args[0:6]
            'code', 'consts', 'names', 'varnames', 'filename', 'name', 'qualname', 'firstlineno', # args[6:14]
            'linetable', 'exceptiontable', 'freevars', 'cellvars'                                 # args[14:]
        )):
            if CODE_VERSION == (3,11):
                return CodeType(
                    *args[:6],
                    args[6].encode() if hasattr(args[6], 'encode') else args[6], # code
                    *args[7:14],
                    args[14].encode() if hasattr(args[14], 'encode') else args[14], # linetable
                    args[15].encode() if hasattr(args[15], 'encode') else args[15], # exceptiontable
                    args[16],
                    args[17],
                )
            fields = m.fields
        # Python 3.10 or 3.8/3.9 (16 members)
        elif m.case((
            'argcount', 'posonlyargcount', 'kwonlyargcount', 'nlocals', 'stacksize', 'flags', # args[0:6]
            'code', 'consts', 'names', 'varnames', 'filename', 'name', 'firstlineno',         # args[6:13]
            'LNOTAB_OR_LINETABLE', 'freevars', 'cellvars'                                     # args[13:]
        )):
            if CODE_VERSION == (3,10) or CODE_VERSION == (3,8):
                return CodeType(
                    *args[:6],
                    args[6].encode() if hasattr(args[6], 'encode') else args[6], # code
                    *args[7:13],
                    args[13].encode() if hasattr(args[13], 'encode') else args[13], # lnotab/linetable
                    args[14],
                    args[15],
                )
            fields = m.fields
            if CODE_VERSION >= (3,10):
                fields['linetable'] = m.LNOTAB_OR_LINETABLE
            else:
                fields['lnotab'] = LNOTAB if LNOTAB else m.LNOTAB_OR_LINETABLE
        # Python 3.7 (15 args)
        elif m.case((
            'argcount', 'kwonlyargcount', 'nlocals', 'stacksize', 'flags',            # args[0:5]
            'code', 'consts', 'names', 'varnames', 'filename', 'name', 'firstlineno', # args[5:12]
            'lnotab', 'freevars', 'cellvars'                                          # args[12:]
        )):
            if CODE_VERSION == (3,7):
                return CodeType(
                    *args[:5],
                    args[5].encode() if hasattr(args[5], 'encode') else args[5], # code
                    *args[6:12],
                    args[12].encode() if hasattr(args[12], 'encode') else args[12], # lnotab
                    args[13],
                    args[14],
                )
            fields = m.fields
        # Python 3.11a (20 members)
        elif m.case((
            'argcount', 'posonlyargcount', 'kwonlyargcount', 'nlocals', 'stacksize', 'flags',     # args[0:6]
            'code', 'consts', 'names', 'varnames', 'filename', 'name', 'qualname', 'firstlineno', # args[6:14]
            'linetable', 'endlinetable', 'columntable', 'exceptiontable', 'freevars', 'cellvars'  # args[14:]
        )):
            if CODE_VERSION == (3,11,'a'):
                return CodeType(
                    *args[:6],
                    args[6].encode() if hasattr(args[6], 'encode') else args[6], # code
                    *args[7:14],
                    *(a.encode() if hasattr(a, 'encode') else a for a in args[14:18]), # linetable-exceptiontable
                    args[18],
                    args[19],
                )
            fields = m.fields
        else:
            raise UnpicklingError("pattern match for code object failed")
    # The args format doesn't match this version.
    fields.setdefault('posonlyargcount', 0)         # from python <= 3.7
    fields.setdefault('lnotab', LNOTAB)             # from python >= 3.10
    fields.setdefault('linetable', b'')             # from python <= 3.9
    fields.setdefault('qualname', fields['name'])   # from python <= 3.10
    fields.setdefault('exceptiontable', b'')        # from python <= 3.10
    fields.setdefault('endlinetable', None)         # from python != 3.11a
    fields.setdefault('columntable', None)          # from python != 3.11a
    args = (fields[k].encode() if k in ENCODE_PARAMS and hasattr(fields[k], 'encode') else fields[k]
            for k in CODE_PARAMS)
    return CodeType(*args)
_create_dtypemeta()
dill._dill._create_dtypemeta (scalar_type) protected
Definition at line 972 of file _dill.py.
def _create_dtypemeta(scalar_type):
    if NumpyDType is True: __hook__() # a bit hacky I think
    if scalar_type is None:
        return NumpyDType
    return type(NumpyDType(scalar_type))
References __hook__(), and NumpyDType.
_create_filehandle()
dill._dill._create_filehandle (name, mode, position, closed, open, strictio, fmode, fdata) protected
Definition at line 811 of file _dill.py.
def _create_filehandle(name, mode, position, closed, open, strictio, fmode, fdata): # buffering=0
    # only pickles the handle, not the file contents... good? or StringIO(data)?
    # (for file contents see: http://effbot.org/librarybook/copy-reg.htm)
    # NOTE: handle special cases first (are there more special cases?)
    names = {'<stdin>':sys.__stdin__, '<stdout>':sys.__stdout__,
             '<stderr>':sys.__stderr__} #XXX: better fileno=(0,1,2) ?
    if name in list(names.keys()):
        f = names[name] #XXX: safer "f=sys.stdin"
    elif name == '<tmpfile>':
        f = os.tmpfile()
    elif name == '<fdopen>':
        import tempfile
        f = tempfile.TemporaryFile(mode)
    else:
        try:
            exists = os.path.exists(name)
        except Exception:
            exists = False
        if not exists:
            if strictio:
                raise FileNotFoundError("[Errno 2] No such file or directory: '%s'" % name)
            elif "r" in mode and fmode != FILE_FMODE:
                name = '<fdopen>' # or os.devnull?
            current_size = 0 # or maintain position?
        else:
            current_size = os.path.getsize(name)
        if position > current_size:
            if strictio:
                raise ValueError("invalid buffer size")
            elif fmode == CONTENTS_FMODE:
                position = current_size
        # try to open the file by name
        # NOTE: has different fileno
        try:
            #FIXME: missing: *buffering*, encoding, softspace
            if fmode == FILE_FMODE:
                f = open(name, mode if "w" in mode else "w")
                f.write(fdata)
                if "w" not in mode:
                    f.close()
                    f = open(name, mode)
            elif name == '<fdopen>': # file did not exist
                import tempfile
                f = tempfile.TemporaryFile(mode)
            # treat x mode as w mode
            elif fmode == CONTENTS_FMODE \
               and ("w" in mode or "x" in mode):
                # stop truncation when opening
                flags = os.O_CREAT
                if "+" in mode:
                    flags |= os.O_RDWR
                else:
                    flags |= os.O_WRONLY
                f = os.fdopen(os.open(name, flags), mode)
                # set name to the correct value
                r = getattr(f, "buffer", f)
                r = getattr(r, "raw", r)
                r.name = name
                assert f.name == name
            else:
                f = open(name, mode)
        except (IOError, FileNotFoundError):
            err = sys.exc_info()[1]
            raise UnpicklingError(err)
    if closed:
        f.close()
    elif position >= 0 and fmode != HANDLE_FMODE:
        f.seek(position)
    return f
_create_ftype()
dill._dill._create_ftype (ftypeobj, func, args, kwds) protected
Definition at line 772 of file _dill.py.
def _create_ftype(ftypeobj, func, args, kwds):
    if kwds is None:
        kwds = {}
    if args is None:
        args = ()
    return ftypeobj(func, *args, **kwds)
_create_function()
dill._dill._create_function (fcode, fglobals, fname = None, fdefaults = None, fclosure = None, fdict = None, fkwdefaults = None) protected
Definition at line 603 of file _dill.py.
                     fclosure=None, fdict=None, fkwdefaults=None):
    # same as FunctionType, but enable passing __dict__ to new function,
    # __dict__ is the storehouse for attributes added after function creation
    func = FunctionType(fcode, fglobals or dict(), fname, fdefaults, fclosure)
    if fdict is not None:
        func.__dict__.update(fdict) #XXX: better copy? option to copy?
    if fkwdefaults is not None:
        func.__kwdefaults__ = fkwdefaults
    # 'recurse' only stores referenced modules/objects in fglobals,
    # thus we need to make sure that we have __builtins__ as well
    if "__builtins__" not in func.__globals__:
        func.__globals__["__builtins__"] = globals()["__builtins__"]
    # assert id(fglobals) == id(func.__globals__)
    return func
_create_lock()
dill._dill._create_lock (locked, * args) protected
Definition at line 794 of file _dill.py.
def _create_lock(locked, *args): #XXX: ignores 'blocking'
    from threading import Lock
    lock = Lock()
    if locked:
        if not lock.acquire(False):
            raise UnpicklingError("Cannot acquire lock")
    return lock
_create_namedtuple()
dill._dill._create_namedtuple (name, fieldnames, modulename, defaults = None) protected
Definition at line 978 of file _dill.py.
def _create_namedtuple(name, fieldnames, modulename, defaults=None):
    class_ = _import_module(modulename + '.' + name, safe=True)
    if class_ is not None:
        return class_
    import collections
    t = collections.namedtuple(name, fieldnames, defaults=defaults, module=modulename)
    return t
References _import_module().
_create_rlock()
dill._dill._create_rlock (count, owner, * args) protected
Definition at line 802 of file _dill.py.
def _create_rlock(count, owner, *args): #XXX: ignores 'blocking'
    lock = RLockType()
    if owner is not None:
        lock._acquire_restore((count, owner))
    if owner and not lock._is_owned():
        raise UnpicklingError("Cannot acquire lock")
    return lock
# thanks to matsjoyce for adding all the different file modes
_create_stringi()
dill._dill._create_stringi (value, position, closed) protected
Definition at line 882 of file _dill.py.
def _create_stringi(value, position, closed):
    f = StringIO(value)
    if closed: f.close()
    else: f.seek(position)
    return f
_create_stringo()
dill._dill._create_stringo (value, position, closed) protected
Definition at line 888 of file _dill.py.
def _create_stringo(value, position, closed):
    f = StringIO()
    if closed: f.close()
    else:
       f.write(value)
       f.seek(position)
    return f
_create_thread_handle()
dill._dill._create_thread_handle (ident, done, * args) protected
Definition at line 787 of file _dill.py.
    def _create_thread_handle(ident, done, *args): #XXX: ignores 'blocking'
        from threading import _make_thread_handle
        handle = _make_thread_handle(ident)
        if done:
            handle._set_done()
        return handle
_create_type()
dill._dill._create_type (typeobj, * args) protected
Definition at line 600 of file _dill.py.
def _create_type(typeobj, *args):
    return typeobj(*args)
_create_typemap()
dill._dill._create_typemap () protected
Definition at line 508 of file _dill.py.
def _create_typemap():
    import types
    d = dict(list(__builtin__.__dict__.items()) + \
             list(types.__dict__.items())).items()
    for key, value in d:
        if getattr(value, '__module__', None) == 'builtins' \
                and type(value) is type:
            yield key, value
    return
_create_typing_tuple()
dill._dill._create_typing_tuple (argz, * args) protected
Definition at line 779 of file _dill.py.
def _create_typing_tuple(argz, *args): #NOTE: workaround python/cpython#94245
    if not argz:
        return typing.Tuple[()].copy_with(())
    if argz == ((),):
        return typing.Tuple[()]
    return typing.Tuple[argz]
_create_weakproxy()
dill._dill._create_weakproxy (obj, callable = False, * args) protected
Definition at line 953 of file _dill.py.
def _create_weakproxy(obj, callable=False, *args):
    from weakref import proxy
    if obj is None: # it's dead
        if callable: return proxy(lambda x:x, *args)
        from collections import UserDict
        return proxy(UserDict(), *args)
    return proxy(obj, *args)
_create_weakref()
dill._dill._create_weakref (obj, * args) protected
Definition at line 946 of file _dill.py.
def _create_weakref(obj, *args):
    from weakref import ref
    if obj is None: # it's dead
        from collections import UserDict
        return ref(UserDict(), *args)
    return ref(obj, *args)
_eval_repr()
dill._dill._eval_repr (repr_str) protected
Definition at line 961 of file _dill.py.
def _eval_repr(repr_str):
    return eval(repr_str)
_extend()
dill._dill._extend () protected
extend pickle with all of dill's registered types
Definition at line 2214 of file _dill.py.
def _extend():
    """extend pickle with all of dill's registered types"""
    # need to have pickle not choke on _main_module?  use is_dill(pickler)
    for t,func in Pickler.dispatch.items():
        try:
            StockPickler.dispatch[t] = func
        except Exception: #TypeError, PicklingError, UnpicklingError
            logger.trace(pickler, "skip: %s", t)
    return
_get_attr()
dill._dill._get_attr (self, name) protected
Definition at line 1032 of file _dill.py.
def _get_attr(self, name):
    # stop recursive pickling
    return getattr(self, name, None) or getattr(__builtin__, name)
_get_typedict_abc()
dill._dill._get_typedict_abc (obj, _dict, attrs, postproc_list) protected
Definition at line 1753 of file _dill.py.
def _get_typedict_abc(obj, _dict, attrs, postproc_list):
    if hasattr(abc, '_get_dump'):
        (registry, _, _, _) = abc._get_dump(obj)
        register = obj.register
        postproc_list.extend((register, (reg(),)) for reg in registry)
    elif hasattr(obj, '_abc_registry'):
        registry = obj._abc_registry
        register = obj.register
        postproc_list.extend((register, (reg,)) for reg in registry)
    else:
        raise PicklingError("Cannot find registry of ABC %s", obj)
    if '_abc_registry' in _dict:
        _dict.pop('_abc_registry', None)
        _dict.pop('_abc_cache', None)
        _dict.pop('_abc_negative_cache', None)
        # _dict.pop('_abc_negative_cache_version', None)
    else:
        _dict.pop('_abc_impl', None)
    return _dict, attrs
@register(TypeType)
Referenced by save_type().
_get_typedict_type()
dill._dill._get_typedict_type (cls, clsdict, attrs, postproc_list) protected
Retrieve a copy of the dict of a class without the inherited methods
Definition at line 1728 of file _dill.py.
def _get_typedict_type(cls, clsdict, attrs, postproc_list):
    """Retrieve a copy of the dict of a class without the inherited methods"""
    if len(cls.__bases__) == 1:
        inherited_dict = cls.__bases__[0].__dict__
    else:
        inherited_dict = {}
        for base in reversed(cls.__bases__):
            inherited_dict.update(base.__dict__)
    to_remove = []
    for name, value in dict.items(clsdict):
        try:
            base_value = inherited_dict[name]
            if value is base_value and hasattr(value, '__qualname__'):
                to_remove.append(name)
        except KeyError:
            pass
    for name in to_remove:
        dict.pop(clsdict, name)
    if issubclass(type(cls), type):
        clsdict.pop('__dict__', None)
        clsdict.pop('__weakref__', None)
        # clsdict.pop('__prepare__', None)
    return clsdict, attrs
Referenced by save_type().
_getattr()
dill._dill._getattr (objclass, name, repr_str) protected
Definition at line 1016 of file _dill.py.
def _getattr(objclass, name, repr_str):
    # hack to grab the reference directly
    try: #XXX: works only for __builtin__ ?
        attr = repr_str.split("'")[3]
        return eval(attr+'.__dict__["'+name+'"]')
    except Exception:
        try:
            attr = objclass.__dict__
            if type(attr) is DictProxyType:
                attr = attr[name]
            else:
                attr = getattr(objclass,name)
        except (AttributeError, KeyError):
            attr = getattr(objclass,name)
        return attr
_getattribute()
dill._dill._getattribute (obj, name) protected
Definition at line 1056 of file _dill.py.
def _getattribute(obj, name):
    for subpath in name.split('.'):
        if subpath == '<locals>':
            raise AttributeError("Can't get local attribute {!r} on {!r}"
                                 .format(name, obj))
        try:
            parent = obj
            obj = getattr(obj, subpath)
        except AttributeError:
            raise AttributeError("Can't get attribute {!r} on {!r}"
                                 .format(name, obj))
    return obj, parent
Referenced by _locate_function(), and save_function().
_import_module()
dill._dill._import_module (import_name, safe = False) protected
Definition at line 1036 of file _dill.py.
def _import_module(import_name, safe=False):
    try:
        if import_name.startswith('__runtime__.'):
            return sys.modules[import_name]
        elif '.' in import_name:
            items = import_name.split('.')
            module = '.'.join(items[:-1])
            obj = items[-1]
            submodule = getattr(__import__(module, None, None, [obj]), obj)
            if isinstance(submodule, (ModuleType, type)):
                return submodule
            return __import__(import_name, None, None, [obj])
        else:
            return __import__(import_name)
    except (ImportError, AttributeError, KeyError):
        if safe:
            return None
        raise
# https://github.com/python/cpython/blob/a8912a0f8d9eba6d502c37d522221f9933e976db/Lib/pickle.py#L322-L333
Referenced by _create_namedtuple(), _locate_function(), save_function(), and save_module_dict().
_is_builtin_module()
dill._dill._is_builtin_module (module) protected
Definition at line 1656 of file _dill.py.
def _is_builtin_module(module):
    if not hasattr(module, "__file__"): return True
    if module.__file__ is None: return False
    # If a module file name starts with prefix, it should be a builtin
    # module, so should always be pickled as a reference.
    names = ["base_prefix", "base_exec_prefix", "exec_prefix", "prefix", "real_prefix"]
    rp = os.path.realpath
    # See https://github.com/uqfoundation/dill/issues/566
    return (
        any(
            module.__file__.startswith(getattr(sys, name))
            or rp(module.__file__).startswith(rp(getattr(sys, name)))
            for name in names
            if hasattr(sys, name)
        )
        or module.__file__.endswith(EXTENSION_SUFFIXES)
        or 'site-packages' in module.__file__
    )
Referenced by save_module().
_is_imported_module()
dill._dill._is_imported_module (module) protected
Definition at line 1675 of file _dill.py.
def _is_imported_module(module):
    return getattr(module, '__loader__', None) is not None or module in sys.modules.values()
@register(ModuleType)
Referenced by save_module().
_load_type()
dill._dill._load_type (name) protected
Definition at line 597 of file _dill.py.
def _load_type(name):
    return _reverse_typemap[name]
_locate_function()
dill._dill._locate_function (obj, pickler = None) protected
Definition at line 1069 of file _dill.py.
def _locate_function(obj, pickler=None):
    module_name = getattr(obj, '__module__', None)
    if module_name in ['__main__', None] or \
            pickler and is_dill(pickler, child=False) and pickler._session and module_name == pickler._main.__name__:
        return False
    if hasattr(obj, '__qualname__'):
        module = _import_module(module_name, safe=True)
        try:
            found, _ = _getattribute(module, obj.__qualname__)
            return found is obj
        except AttributeError:
            return False
    else:
        found = _import_module(module_name + '.' + obj.__name__, safe=True)
        return found is obj
References _getattribute(), _import_module(), and is_dill().
Referenced by save_classobj(), save_function(), and save_type().
_locate_object()
dill._dill._locate_object (address, module = None) protected
get object located at the given memory address (inverse of id(obj))
Definition at line 1621 of file _dill.py.
def _locate_object(address, module=None):
    """get object located at the given memory address (inverse of id(obj))"""
    special = [None, True, False] #XXX: more...?
    for obj in special:
        if address == id(obj): return obj
    if module:
        objects = iter(module.__dict__.values())
    else: objects = iter(gc.get_objects())
    for obj in objects:
        if address == id(obj): return obj
    # all bad below... nothing found so throw ReferenceError or TypeError
    try: address = hex(address)
    except TypeError:
        raise TypeError("'%s' is not a valid memory address" % str(address))
    raise ReferenceError("Cannot reference object at '%s'" % address)
@register(ReferenceType)
Referenced by save_weakproxy().
_proxy_helper()
dill._dill._proxy_helper (obj) protected
get memory address of proxy's reference object
Definition at line 1600 of file _dill.py.
def _proxy_helper(obj): # a dead proxy returns a reference to None
    """get memory address of proxy's reference object"""
    _repr = repr(obj)
    try: _str = str(obj)
    except ReferenceError: # it's a dead proxy
        return id(None)
    if _str == _repr: return id(obj) # it's a repr
    try: # either way, it's a proxy from here
        address = int(_str.rstrip('>').split(' at ')[-1], base=16)
    except ValueError: # special case: proxy of a 'type'
        if not IS_PYPY:
            address = int(_repr.rstrip('>').split(' at ')[-1], base=16)
        else:
            objects = iter(gc.get_objects())
            for _obj in objects:
                if repr(_obj) == _str: return id(_obj)
            # all bad below... nothing found so throw ReferenceError
            msg = "Cannot reference object for proxy at '%s'" % id(obj)
            raise ReferenceError(msg)
    return address
Referenced by save_weakproxy().
_repr_dict()
dill._dill._repr_dict (obj) protected
Make a short string representation of a dictionary.
Definition at line 1207 of file _dill.py.
def _repr_dict(obj):
    """Make a short string representation of a dictionary."""
    return "<%s object at %#012x>" % (type(obj).__name__, id(obj))
@register(dict)
Referenced by save_dictproxy(), and save_module_dict().
_revert_extension()
dill._dill._revert_extension () protected
drop dill-registered types from pickle's dispatch table
Definition at line 483 of file _dill.py.
def _revert_extension():
    """drop dill-registered types from pickle's dispatch table"""
    for type, func in list(StockPickler.dispatch.items()):
        if func.__module__ == __name__:
            del StockPickler.dispatch[type]
            if type in pickle_dispatch_copy:
                StockPickler.dispatch[type] = pickle_dispatch_copy[type]
_save_file()
dill._dill._save_file (pickler, obj, open_) protected
Definition at line 1357 of file _dill.py.
def _save_file(pickler, obj, open_):
    if obj.closed:
        position = 0
    else:
        obj.flush()
        if obj in (sys.__stdout__, sys.__stderr__, sys.__stdin__):
            position = -1
        else:
            position = obj.tell()
    if is_dill(pickler, child=True) and pickler._fmode == FILE_FMODE:
        f = open_(obj.name, "r")
        fdata = f.read()
        f.close()
    else:
        fdata = ""
    if is_dill(pickler, child=True):
        strictio = pickler._strictio
        fmode = pickler._fmode
    else:
        strictio = False
        fmode = 0 # HANDLE_FMODE
    pickler.save_reduce(_create_filehandle, (obj.name, obj.mode, position,
                                             obj.closed, open_, strictio,
                                             fmode, fdata), obj=obj)
    return
@register(FileType) #XXX: in 3.x has buffer=0, needs different _create?
@register(BufferedReaderType)
@register(BufferedWriterType)
@register(TextWrapperType)
References is_dill().
Referenced by save_file().
_save_with_postproc()
dill._dill._save_with_postproc (pickler, reduction, is_pickler_dill = None, obj = Getattr.NO_DEFAULT, postproc_list = None) protected
Definition at line 1091 of file _dill.py.
def _save_with_postproc(pickler, reduction, is_pickler_dill=None, obj=Getattr.NO_DEFAULT, postproc_list=None):
    if obj is Getattr.NO_DEFAULT:
        obj = Reduce(reduction) # pragma: no cover
    if is_pickler_dill is None:
        is_pickler_dill = is_dill(pickler, child=True)
    if is_pickler_dill:
        # assert id(obj) not in pickler._postproc, str(obj) + ' already pushed on stack!'
        # if not hasattr(pickler, 'x'): pickler.x = 0
        # print(pickler.x*' ', 'push', obj, id(obj), pickler._recurse)
        # pickler.x += 1
        if postproc_list is None:
            postproc_list = []
        # Recursive object not supported. Default to a global instead.
        if id(obj) in pickler._postproc:
            name = '%s.%s ' % (obj.__module__, getattr(obj, '__qualname__', obj.__name__)) if hasattr(obj, '__module__') else ''
            warnings.warn('Cannot pickle %r: %shas recursive self-references that trigger a RecursionError.' % (obj, name), PicklingWarning)
            pickler.save_global(obj)
            return
        pickler._postproc[id(obj)] = postproc_list
    # TODO: Use state_setter in Python 3.8 to allow for faster cPickle implementations
    pickler.save_reduce(*reduction, obj=obj)
    if is_pickler_dill:
        # pickler.x -= 1
        # print(pickler.x*' ', 'pop', obj, id(obj))
        postproc = pickler._postproc.pop(id(obj))
        # assert postproc_list == postproc, 'Stack tampered!'
        for reduction in reversed(postproc):
            if reduction[0] is _setitems:
                # use the internal machinery of pickle.py to speedup when
                # updating a dictionary in postproc
                dest, source = reduction[1]
                if source:
                    pickler.write(pickler.get(pickler.memo[id(dest)][0]))
                    pickler._batch_setitems(iter(source.items()))
                else:
                    # Updating with an empty dictionary. Same as doing nothing.
                    continue
            else:
                pickler.save_reduce(*reduction)
            # pop None created by calling preprocessing step off stack
            pickler.write(POP)
#@register(CodeType)
#def save_code(pickler, obj):
#    logger.trace(pickler, "Co: %s", obj)
#    pickler.save_reduce(_unmarshal, (marshal.dumps(obj),), obj=obj)
#    logger.trace(pickler, "# Co")
#    return
# The following function is based on 'save_codeobject' from 'cloudpickle'
# Copyright (c) 2012, Regents of the University of California.
# Copyright (c) 2009 `PiCloud, Inc. <http://www.picloud.com>`_.
# License: https://github.com/cloudpipe/cloudpickle/blob/master/LICENSE
@register(CodeType)
References is_dill().
Referenced by save_function(), and save_type().
_setitems()
dill._dill._setitems (dest, source) protected
Definition at line 1086 of file _dill.py.
def _setitems(dest, source):
    for k, v in source.items():
        dest[k] = v
_unmarshal()
dill._dill._unmarshal (string) protected
Definition at line 594 of file _dill.py.
def _unmarshal(string):
    return marshal.loads(string)
check()
dill._dill.check (obj, * args, ** kwds)
Check pickling of an object across another process.
*python* is the path to the python interpreter (defaults to sys.executable)
Set *verbose=True* to print the unpickled object in the other process.
Additional keyword arguments are as :func:`dumps` and :func:`loads`.
Definition at line 2166 of file _dill.py.
def check(obj, *args, **kwds):
    """
    Check pickling of an object across another process.
    *python* is the path to the python interpreter (defaults to sys.executable)
    Set *verbose=True* to print the unpickled object in the other process.
    Additional keyword arguments are as :func:`dumps` and :func:`loads`.
    """
   # == undocumented ==
   # python -- the string path or executable name of the selected python
   # verbose -- if True, be verbose about printing warning messages
   # all other args and kwds are passed to dill.dumps #FIXME: ignore on load
    verbose = kwds.pop('verbose', False)
    python = kwds.pop('python', None)
    if python is None:
        import sys
        python = sys.executable
    # type check
    isinstance(python, str)
    import subprocess
    fail = True
    try:
        _obj = dumps(obj, *args, **kwds)
        fail = False
    finally:
        if fail and verbose:
            print("DUMP FAILED")
    #FIXME: fails if python interpreter path contains spaces
    # Use the following instead (which also processes the 'ignore' keyword):
    #    ignore = kwds.pop('ignore', None)
    #    unpickle = "dill.loads(%s, ignore=%s)"%(repr(_obj), repr(ignore))
    #    cmd = [python, "-c", "import dill; print(%s)"%unpickle]
    #    msg = "SUCCESS" if not subprocess.call(cmd) else "LOAD FAILED"
    msg = "%s -c import dill; print(dill.loads(%s))" % (python, repr(_obj))
    msg = "SUCCESS" if not subprocess.call(msg.split(None,2)) else "LOAD FAILED"
    if verbose:
        print(msg)
    return
# use to protect against missing attributes
copy()
dill._dill.copy (obj, * args, ** kwds)
Shorthands (modified from python2.5/lib/pickle.py)
Use pickling to 'copy' an object (i.e. `loads(dumps(obj))`).
See :func:`dumps` and :func:`loads` for keyword arguments.
Definition at line 241 of file _dill.py.
def copy(obj, *args, **kwds):
    """
    Use pickling to 'copy' an object (i.e. `loads(dumps(obj))`).
    See :func:`dumps` and :func:`loads` for keyword arguments.
    """
    ignore = kwds.pop('ignore', Unpickler.settings['ignore'])
    return loads(dumps(obj, *args, **kwds), ignore=ignore)
References dumps(), and loads().
Referenced by pickles().
dump()
dill._dill.dump (obj, file, protocol = None, byref = None, fmode = None, recurse = None, ** kwds)
Pickle an object to a file.
See :func:`dumps` for keyword arguments.
Definition at line 250 of file _dill.py.
def dump(obj, file, protocol=None, byref=None, fmode=None, recurse=None, **kwds):#, strictio=None):
    """
    Pickle an object to a file.
    See :func:`dumps` for keyword arguments.
    """
    from .settings import settings
    protocol = settings['protocol'] if protocol is None else int(protocol)
    _kwds = kwds.copy()
    _kwds.update(dict(byref=byref, fmode=fmode, recurse=recurse))
    Pickler(file, protocol, **_kwds).dump(obj)
    return
References dump().
Referenced by dump(), and dumps().
dumps()
dill._dill.dumps (obj, protocol = None, byref = None, fmode = None, recurse = None, ** kwds)
Pickle an object to a string.
*protocol* is the pickler protocol, as defined for Python *pickle*.
If *byref=True*, then dill behaves a lot more like pickle as certain
objects (like modules) are pickled by reference as opposed to attempting
to pickle the object itself.
If *recurse=True*, then objects referred to in the global dictionary
are recursively traced and pickled, instead of the default behavior
of attempting to store the entire global dictionary. This is needed for
functions defined via *exec()*.
*fmode* (:const:`HANDLE_FMODE`, :const:`CONTENTS_FMODE`,
or :const:`FILE_FMODE`) indicates how file handles will be pickled.
For example, when pickling a data file handle for transfer to a remote
compute service, *FILE_FMODE* will include the file contents in the
pickle and cursor position so that a remote method can operate
transparently on an object with an open file handle.
Default values for keyword arguments can be set in :mod:`dill.settings`.
Definition at line 263 of file _dill.py.
def dumps(obj, protocol=None, byref=None, fmode=None, recurse=None, **kwds):#, strictio=None):
    """
    Pickle an object to a string.
    *protocol* is the pickler protocol, as defined for Python *pickle*.
    If *byref=True*, then dill behaves a lot more like pickle as certain
    objects (like modules) are pickled by reference as opposed to attempting
    to pickle the object itself.
    If *recurse=True*, then objects referred to in the global dictionary
    are recursively traced and pickled, instead of the default behavior
    of attempting to store the entire global dictionary. This is needed for
    functions defined via *exec()*.
    *fmode* (:const:`HANDLE_FMODE`, :const:`CONTENTS_FMODE`,
    or :const:`FILE_FMODE`) indicates how file handles will be pickled.
    For example, when pickling a data file handle for transfer to a remote
    compute service, *FILE_FMODE* will include the file contents in the
    pickle and cursor position so that a remote method can operate
    transparently on an object with an open file handle.
    Default values for keyword arguments can be set in :mod:`dill.settings`.
    """
    file = StringIO()
    dump(obj, file, protocol, byref, fmode, recurse, **kwds)#, strictio)
    return file.getvalue()
References dump().
Referenced by copy().
get_file_type()
dill._dill.get_file_type (* args, ** kwargs)
Definition at line 162 of file _dill.py.
def get_file_type(*args, **kwargs):
    open = kwargs.pop("open", __builtin__.open)
    f = open(os.devnull, *args, **kwargs)
    t = type(f)
    f.close()
    return t
is_dill()
dill._dill.is_dill (pickler, child = None)
Definition at line 2208 of file _dill.py.
def is_dill(pickler, child=None):
    "check the dill-ness of your pickler"
    if child is False or not hasattr(pickler.__class__, 'mro'):
        return 'dill' in pickler.__module__
    return Pickler in pickler.__class__.mro()
Referenced by _locate_function(), _save_file(), _save_with_postproc(), save_cell(), save_module(), save_module_dict(), and dill.logger.TraceAdapter.trace_setup().
load()
dill._dill.load (file, ignore = None, ** kwds)
Unpickle an object from a file.
See :func:`loads` for keyword arguments.
Definition at line 291 of file _dill.py.
def load(file, ignore=None, **kwds):
    """
    Unpickle an object from a file.
    See :func:`loads` for keyword arguments.
    """
    return Unpickler(file, ignore=ignore, **kwds).load()
References load().
Referenced by load(), and loads().
loads()
dill._dill.loads (str, ignore = None, ** kwds)
Unpickle an object from a string.
If *ignore=False* then objects whose class is defined in the module
*__main__* are updated to reference the existing class in *__main__*,
otherwise they are left to refer to the reconstructed type, which may
be different.
Default values for keyword arguments can be set in :mod:`dill.settings`.
Definition at line 299 of file _dill.py.
def loads(str, ignore=None, **kwds):
    """
    Unpickle an object from a string.
    If *ignore=False* then objects whose class is defined in the module
    *__main__* are updated to reference the existing class in *__main__*,
    otherwise they are left to refer to the reconstructed type, which may
    be different.
    Default values for keyword arguments can be set in :mod:`dill.settings`.
    """
    file = StringIO(str)
    return load(file, ignore, **kwds)
# def dumpzs(obj, protocol=None):
#     """pickle an object to a compressed string"""
#     return zlib.compress(dumps(obj, protocol))
# def loadzs(str):
#     """unpickle an object from a compressed string"""
#     return loads(zlib.decompress(str))
References load().
Referenced by copy().
ndarraysubclassinstance()
dill._dill.ndarraysubclassinstance (obj_type)
Definition at line 120 of file _dill.py.
    def ndarraysubclassinstance(obj_type):
        if all((c.__module__, c.__name__) != ('numpy', 'ndarray') for c in obj_type.__mro__):
            return False
        # anything below here is a numpy array (or subclass) instance
        __hook__() # import numpy (so the following works!!!)
        # verify that __reduce__ has not been overridden
        if obj_type.__reduce_ex__ is not NumpyArrayType.__reduce_ex__ \
                or obj_type.__reduce__ is not NumpyArrayType.__reduce__:
            return False
        return True
References __hook__().
Referenced by dill._dill.Pickler.save().
numpydtype()
dill._dill.numpydtype (obj_type)
Definition at line 132 of file _dill.py.
    def numpydtype(obj_type):
        if all((c.__module__, c.__name__) != ('numpy', 'dtype') for c in obj_type.__mro__):
            return False
        # anything below here is a numpy dtype
        __hook__() # import numpy (so the following works!!!)
        return obj_type is type(NumpyDType) # handles subclasses
References __hook__().
Referenced by dill._dill.Pickler.save().
numpyufunc()
dill._dill.numpyufunc (obj_type)
Definition at line 130 of file _dill.py.
    def numpyufunc(obj_type):
        return any((c.__module__, c.__name__) == ('numpy', 'ufunc') for c in obj_type.__mro__)
Referenced by dill._dill.Pickler.save().
pickle()
dill._dill.pickle (t, func)
expose :attr:`~Pickler.dispatch` table for user-created extensions
Definition at line 471 of file _dill.py.
def pickle(t, func):
    """expose :attr:`~Pickler.dispatch` table for user-created extensions"""
    Pickler.dispatch[t] = func
    return
pickles()
dill._dill.pickles (obj, exact = False, safe = False, ** kwds)
Quick check if object pickles with dill.
If *exact=True* then an equality test is done to check if the reconstructed
object matches the original object.
If *safe=True* then any exception will raised in copy signal that the
object is not picklable, otherwise only pickling errors will be trapped.
Additional keyword arguments are as :func:`dumps` and :func:`loads`.
Definition at line 2129 of file _dill.py.
def pickles(obj,exact=False,safe=False,**kwds):
    """
    Quick check if object pickles with dill.
    If *exact=True* then an equality test is done to check if the reconstructed
    object matches the original object.
    If *safe=True* then any exception will raised in copy signal that the
    object is not picklable, otherwise only pickling errors will be trapped.
    Additional keyword arguments are as :func:`dumps` and :func:`loads`.
    """
    if safe: exceptions = (Exception,) # RuntimeError, ValueError
    else:
        exceptions = (TypeError, AssertionError, NotImplementedError, PicklingError, UnpicklingError)
    try:
        pik = copy(obj, **kwds)
        #FIXME: should check types match first, then check content if "exact"
        try:
            #FIXME: should be "(pik == obj).all()" for numpy comparison, though that'll fail if shapes differ
            result = bool(pik.all() == obj.all())
        except (AttributeError, TypeError):
            warnings.filterwarnings('ignore') #FIXME: be specific
            result = pik == obj
            if warnings.filters: del warnings.filters[0]
        if hasattr(result, 'toarray'): # for unusual types like sparse matrix
            result = result.toarray().all()
        if result: return True
        if not exact:
            result = type(pik) == type(obj)
            if result: return result
            # class instances might have been dumped with byref=False
            return repr(type(pik)) == repr(type(obj)) #XXX: InstanceType?
        return False
    except exceptions:
        return False
References copy().
register()
dill._dill.register (t)
decorator to register types to Pickler's :attr:`~Pickler.dispatch` table
Definition at line 476 of file _dill.py.
def register(t):
    """decorator to register types to Pickler's :attr:`~Pickler.dispatch` table"""
    def proxy(func):
        Pickler.dispatch[t] = func
        return func
    return proxy
save_capsule()
dill._dill.save_capsule (pickler, obj)
Definition at line 2078 of file _dill.py.
    def save_capsule(pickler, obj):
        logger.trace(pickler, "Cap: %s", obj)
        name = _PyCapsule_GetName(obj)
        #warnings.warn('Pickling a PyCapsule (%s) does not pickle any C data structures and could cause segmentation faults or other memory errors when unpickling.' % (name,), PicklingWarning)
        pointer = _PyCapsule_GetPointer(obj, name)
        context = _PyCapsule_GetContext(obj)
        destructor = _PyCapsule_GetDestructor(obj)
        pickler.save_reduce(_create_capsule, (pointer, name, context, destructor), obj=obj)
        logger.trace(pickler, "# Cap")
References _PyCapsule_GetContext, _PyCapsule_GetDestructor, _PyCapsule_GetName, and _PyCapsule_GetPointer.
save_cell()
dill._dill.save_cell (pickler, obj)
Definition at line 1524 of file _dill.py.
def save_cell(pickler, obj):
    try:
        f = obj.cell_contents
    except ValueError: # cell is empty
        logger.trace(pickler, "Ce3: %s", obj)
        # _shims._CELL_EMPTY is defined in _shims.py to support PyPy 2.7.
        # It unpickles to a sentinel object _dill._CELL_EMPTY, also created in
        # _shims.py. This object is not present in Python 3 because the cell's
        # contents can be deleted in newer versions of Python. The reduce object
        # will instead unpickle to None if unpickled in Python 3.
        # When breaking changes are made to dill, (_shims._CELL_EMPTY,) can
        # be replaced by () OR the delattr function can be removed repending on
        # whichever is more convienient.
        pickler.save_reduce(_create_cell, (_shims._CELL_EMPTY,), obj=obj)
        # Call the function _delattr on the cell's cell_contents attribute
        # The result of this function call will be None
        pickler.save_reduce(_shims._delattr, (obj, 'cell_contents'))
        # pop None created by calling _delattr off stack
        pickler.write(POP)
        logger.trace(pickler, "# Ce3")
        return
    if is_dill(pickler, child=True):
        if id(f) in pickler._postproc:
            # Already seen. Add to its postprocessing.
            postproc = pickler._postproc[id(f)]
        else:
            # Haven't seen it. Add to the highest possible object and set its
            # value as late as possible to prevent cycle.
            postproc = next(iter(pickler._postproc.values()), None)
        if postproc is not None:
            logger.trace(pickler, "Ce2: %s", obj)
            # _CELL_REF is defined in _shims.py to support older versions of
            # dill. When breaking changes are made to dill, (_CELL_REF,) can
            # be replaced by ()
            pickler.save_reduce(_create_cell, (_CELL_REF,), obj=obj)
            postproc.append((_shims._setattr, (obj, 'cell_contents', f)))
            logger.trace(pickler, "# Ce2")
            return
    logger.trace(pickler, "Ce1: %s", obj)
    pickler.save_reduce(_create_cell, (f,), obj=obj)
    logger.trace(pickler, "# Ce1")
    return
References is_dill().
save_classmethod()
dill._dill.save_classmethod (pickler, obj)
Definition at line 1913 of file _dill.py.
def save_classmethod(pickler, obj):
    logger.trace(pickler, "Cm: %s", obj)
    orig_func = obj.__func__
    # if type(obj.__dict__) is dict:
    #     if obj.__dict__:
    #         state = obj.__dict__
    #     else:
    #         state = None
    # else:
    #     state = (None, {'__dict__', obj.__dict__})
    pickler.save_reduce(type(obj), (orig_func,), obj=obj)
    logger.trace(pickler, "# Cm")
@register(FunctionType)
save_classobj()
dill._dill.save_classobj (pickler, obj)
Definition at line 1294 of file _dill.py.
def save_classobj(pickler, obj): #FIXME: enable pickler._byref
    if not _locate_function(obj, pickler):
        logger.trace(pickler, "C1: %s", obj)
        pickler.save_reduce(ClassType, (obj.__name__, obj.__bases__,
                                        obj.__dict__), obj=obj)
                                       #XXX: or obj.__dict__.copy()), obj=obj) ?
        logger.trace(pickler, "# C1")
    else:
        logger.trace(pickler, "C2: %s", obj)
        name = getattr(obj, '__qualname__', getattr(obj, '__name__', None))
        StockPickler.save_global(pickler, obj, name=name)
        logger.trace(pickler, "# C2")
    return
@register(typing._GenericAlias)
References _locate_function().
save_code()
dill._dill.save_code (pickler, obj)
Definition at line 1149 of file _dill.py.
def save_code(pickler, obj):
    logger.trace(pickler, "Co: %s", obj)
    if hasattr(obj, "co_endlinetable"): # python 3.11a (20 args)
        args = (
            obj.co_lnotab, # for < python 3.10 [not counted in args]
            obj.co_argcount, obj.co_posonlyargcount,
            obj.co_kwonlyargcount, obj.co_nlocals, obj.co_stacksize,
            obj.co_flags, obj.co_code, obj.co_consts, obj.co_names,
            obj.co_varnames, obj.co_filename, obj.co_name, obj.co_qualname,
            obj.co_firstlineno, obj.co_linetable, obj.co_endlinetable,
            obj.co_columntable, obj.co_exceptiontable, obj.co_freevars,
            obj.co_cellvars
        )
    elif hasattr(obj, "co_exceptiontable"): # python 3.11 (18 args)
        with warnings.catch_warnings():
            if not OLD312a7: # issue 597
                warnings.filterwarnings('ignore', category=DeprecationWarning)
            args = (
                obj.co_lnotab, # for < python 3.10 [not counted in args]
                obj.co_argcount, obj.co_posonlyargcount,
                obj.co_kwonlyargcount, obj.co_nlocals, obj.co_stacksize,
                obj.co_flags, obj.co_code, obj.co_consts, obj.co_names,
                obj.co_varnames, obj.co_filename, obj.co_name, obj.co_qualname,
                obj.co_firstlineno, obj.co_linetable, obj.co_exceptiontable,
                obj.co_freevars, obj.co_cellvars
            )
    elif hasattr(obj, "co_linetable"): # python 3.10 (16 args)
        args = (
            obj.co_lnotab, # for < python 3.10 [not counted in args]
            obj.co_argcount, obj.co_posonlyargcount,
            obj.co_kwonlyargcount, obj.co_nlocals, obj.co_stacksize,
            obj.co_flags, obj.co_code, obj.co_consts, obj.co_names,
            obj.co_varnames, obj.co_filename, obj.co_name,
            obj.co_firstlineno, obj.co_linetable, obj.co_freevars,
            obj.co_cellvars
        )
    elif hasattr(obj, "co_posonlyargcount"): # python 3.8 (16 args)
        args = (
            obj.co_argcount, obj.co_posonlyargcount,
            obj.co_kwonlyargcount, obj.co_nlocals, obj.co_stacksize,
            obj.co_flags, obj.co_code, obj.co_consts, obj.co_names,
            obj.co_varnames, obj.co_filename, obj.co_name,
            obj.co_firstlineno, obj.co_lnotab, obj.co_freevars,
            obj.co_cellvars
        )
    else: # python 3.7 (15 args)
        args = (
            obj.co_argcount, obj.co_kwonlyargcount, obj.co_nlocals,
            obj.co_stacksize, obj.co_flags, obj.co_code, obj.co_consts,
            obj.co_names, obj.co_varnames, obj.co_filename,
            obj.co_name, obj.co_firstlineno, obj.co_lnotab,
            obj.co_freevars, obj.co_cellvars
        )
    pickler.save_reduce(_create_code, args, obj=obj)
    logger.trace(pickler, "# Co")
    return
save_dataclasses_FIELD_BASE()
dill._dill.save_dataclasses_FIELD_BASE (pickler, obj)
Definition at line 2121 of file _dill.py.
    def save_dataclasses_FIELD_BASE(pickler, obj):
        logger.trace(pickler, "DcFB: %s", obj)
        pickler.write(GLOBAL + b"dataclasses\n" + obj.name.encode() + b"\n")
        logger.trace(pickler, "# DcFB")
save_dataclasses_HAS_DEFAULT_FACTORY_CLASS()
dill._dill.save_dataclasses_HAS_DEFAULT_FACTORY_CLASS (pickler, obj)
A quick fix for issue #500 This should be removed when a better solution is found.
Definition at line 2100 of file _dill.py.
    def save_dataclasses_HAS_DEFAULT_FACTORY_CLASS(pickler, obj):
        logger.trace(pickler, "DcHDF: %s", obj)
        pickler.write(GLOBAL + b"dataclasses\n_HAS_DEFAULT_FACTORY\n")
        logger.trace(pickler, "# DcHDF")
save_dataclasses_KW_ONLY_TYPE()
dill._dill.save_dataclasses_KW_ONLY_TYPE (pickler, obj)
Definition at line 2114 of file _dill.py.
    def save_dataclasses_KW_ONLY_TYPE(pickler, obj):
        logger.trace(pickler, "DcKWO: %s", obj)
        pickler.write(GLOBAL + b"dataclasses\nKW_ONLY\n")
        logger.trace(pickler, "# DcKWO")
save_dataclasses_MISSING_TYPE()
dill._dill.save_dataclasses_MISSING_TYPE (pickler, obj)
Definition at line 2107 of file _dill.py.
    def save_dataclasses_MISSING_TYPE(pickler, obj):
        logger.trace(pickler, "DcM: %s", obj)
        pickler.write(GLOBAL + b"dataclasses\nMISSING\n")
        logger.trace(pickler, "# DcM")
save_dict_view()
dill._dill.save_dict_view (dicttype)
Definition at line 1239 of file _dill.py.
    def save_dict_view(dicttype):
        def save_dict_view_for_function(func):
            def _save_dict_view(pickler, obj):
                logger.trace(pickler, "Dkvi: <%s>", obj)
                mapping = obj.mapping | _dictproxy_helper_instance
                pickler.save_reduce(func, (mapping,), obj=obj)
                logger.trace(pickler, "# Dkvi")
            return _save_dict_view
        return [
            (funcname, save_dict_view_for_function(getattr(dicttype, funcname)))
            for funcname in ('keys', 'values', 'items')
        ]
References save_dict_view().
Referenced by save_dict_view().
save_dictproxy()
dill._dill.save_dictproxy (pickler, obj)
Definition at line 1570 of file _dill.py.
    def save_dictproxy(pickler, obj):
        logger.trace(pickler, "Mp: %s", _repr_dict(obj)) # obj
        mapping = obj | _dictproxy_helper_instance
        pickler.save_reduce(DictProxyType, (mapping,), obj=obj)
        logger.trace(pickler, "# Mp")
        return
References _repr_dict().
save_file()
dill._dill.save_file (pickler, obj)
Definition at line 1388 of file _dill.py.
def save_file(pickler, obj):
    logger.trace(pickler, "Fi: %s", obj)
    f = _save_file(pickler, obj, open)
    logger.trace(pickler, "# Fi")
    return f
References _save_file().
save_function()
dill._dill.save_function (pickler, obj)
Definition at line 1929 of file _dill.py.
def save_function(pickler, obj):
    if not _locate_function(obj, pickler):
        if type(obj.__code__) is not CodeType:
            # Some PyPy builtin functions have no module name, and thus are not
            # able to be located
            module_name = getattr(obj, '__module__', None)
            if module_name is None:
                module_name = __builtin__.__name__
            module = _import_module(module_name, safe=True)
            _pypy_builtin = False
            try:
                found, _ = _getattribute(module, obj.__qualname__)
                if getattr(found, '__func__', None) is obj:
                    _pypy_builtin = True
            except AttributeError:
                pass
            if _pypy_builtin:
                logger.trace(pickler, "F3: %s", obj)
                pickler.save_reduce(getattr, (found, '__func__'), obj=obj)
                logger.trace(pickler, "# F3")
                return
        logger.trace(pickler, "F1: %s", obj)
        _recurse = getattr(pickler, '_recurse', None)
        _postproc = getattr(pickler, '_postproc', None)
        _main_modified = getattr(pickler, '_main_modified', None)
        _original_main = getattr(pickler, '_original_main', __builtin__)#'None'
        postproc_list = []
        if _recurse:
            # recurse to get all globals referred to by obj
            from .detect import globalvars
            globs_copy = globalvars(obj, recurse=True, builtin=True)
            # Add the name of the module to the globs dictionary to prevent
            # the duplication of the dictionary. Pickle the unpopulated
            # globals dictionary and set the remaining items after the function
            # is created to correctly handle recursion.
            globs = {'__name__': obj.__module__}
        else:
            globs_copy = obj.__globals__
            # If the globals is the __dict__ from the module being saved as a
            # session, substitute it by the dictionary being actually saved.
            if _main_modified and globs_copy is _original_main.__dict__:
                globs_copy = getattr(pickler, '_main', _original_main).__dict__
                globs = globs_copy
            # If the globals is a module __dict__, do not save it in the pickle.
            elif globs_copy is not None and obj.__module__ is not None and \
                    getattr(_import_module(obj.__module__, True), '__dict__', None) is globs_copy:
                globs = globs_copy
            else:
                globs = {'__name__': obj.__module__}
        if globs_copy is not None and globs is not globs_copy:
            # In the case that the globals are copied, we need to ensure that
            # the globals dictionary is updated when all objects in the
            # dictionary are already created.
            glob_ids = {id(g) for g in globs_copy.values()}
            for stack_element in _postproc:
                if stack_element in glob_ids:
                    _postproc[stack_element].append((_setitems, (globs, globs_copy)))
                    break
            else:
                postproc_list.append((_setitems, (globs, globs_copy)))
        closure = obj.__closure__
        state_dict = {}
        for fattrname in ('__doc__', '__kwdefaults__', '__annotations__'):
            fattr = getattr(obj, fattrname, None)
            if fattr is not None:
                state_dict[fattrname] = fattr
        if obj.__qualname__ != obj.__name__:
            state_dict['__qualname__'] = obj.__qualname__
        if '__name__' not in globs or obj.__module__ != globs['__name__']:
            state_dict['__module__'] = obj.__module__
        state = obj.__dict__
        if type(state) is not dict:
            state_dict['__dict__'] = state
            state = None
        if state_dict:
            state = state, state_dict
        _save_with_postproc(pickler, (_create_function, (
                obj.__code__, globs, obj.__name__, obj.__defaults__,
                closure
        ), state), obj=obj, postproc_list=postproc_list)
        # Lift closure cell update to earliest function (#458)
        if _postproc:
            topmost_postproc = next(iter(_postproc.values()), None)
            if closure and topmost_postproc:
                for cell in closure:
                    possible_postproc = (setattr, (cell, 'cell_contents', obj))
                    try:
                        topmost_postproc.remove(possible_postproc)
                    except ValueError:
                        continue
                    # Change the value of the cell
                    pickler.save_reduce(*possible_postproc)
                    # pop None created by calling preprocessing step off stack
                    pickler.write(POP)
        logger.trace(pickler, "# F1")
    else:
        logger.trace(pickler, "F2: %s", obj)
        name = getattr(obj, '__qualname__', getattr(obj, '__name__', None))
        StockPickler.save_global(pickler, obj, name=name)
        logger.trace(pickler, "# F2")
    return
References _getattribute(), _import_module(), _locate_function(), and _save_with_postproc().
save_generic_alias()
dill._dill.save_generic_alias (pickler, obj)
Definition at line 1309 of file _dill.py.
def save_generic_alias(pickler, obj):
    args = obj.__args__
    if type(obj.__reduce__()) is str:
        logger.trace(pickler, "Ga0: %s", obj)
        StockPickler.save_global(pickler, obj, name=obj.__reduce__())
        logger.trace(pickler, "# Ga0")
    elif obj.__origin__ is tuple and (not args or args == ((),)):
        logger.trace(pickler, "Ga1: %s", obj)
        pickler.save_reduce(_create_typing_tuple, (args,), obj=obj)
        logger.trace(pickler, "# Ga1")
    else:
        logger.trace(pickler, "Ga2: %s", obj)
        StockPickler.save_reduce(pickler, *obj.__reduce__(), obj=obj)
        logger.trace(pickler, "# Ga2")
    return
save_instancemethod0()
dill._dill.save_instancemethod0 (pickler, obj)
Definition at line 1478 of file _dill.py.
    def save_instancemethod0(pickler, obj):
        code = getattr(obj.__func__, '__code__', None)
        if code is not None and type(code) is not CodeType \
              and getattr(obj.__self__, obj.__name__) == obj:
            # Some PyPy builtin functions have no module name
            logger.trace(pickler, "Me2: %s", obj)
            # TODO: verify that this works for all PyPy builtin methods
            pickler.save_reduce(getattr, (obj.__self__, obj.__name__), obj=obj)
            logger.trace(pickler, "# Me2")
            return
        logger.trace(pickler, "Me1: %s", obj)
        pickler.save_reduce(MethodType, (obj.__func__, obj.__self__), obj=obj)
        logger.trace(pickler, "# Me1")
        return
save_lock()
dill._dill.save_lock (pickler, obj)
Definition at line 1334 of file _dill.py.
def save_lock(pickler, obj):
    logger.trace(pickler, "Lo: %s", obj)
    pickler.save_reduce(_create_lock, (obj.locked(),), obj=obj)
    logger.trace(pickler, "# Lo")
    return
@register(RLockType)
save_lru_cache()
dill._dill.save_lru_cache (pickler, obj)
Definition at line 1453 of file _dill.py.
    def save_lru_cache(pickler, obj):
        logger.trace(pickler, "LRU: %s", obj)
        if OLD39:
            kwargs = obj.cache_info()
            args = (kwargs.maxsize,)
        else:
            kwargs = obj.cache_parameters()
            args = (kwargs['maxsize'], kwargs['typed'])
        if args != lru_cache.__defaults__:
            wrapper = Reduce(lru_cache, args, is_callable=True)
        else:
            wrapper = lru_cache
        pickler.save_reduce(wrapper, (obj.__wrapped__,), obj=obj)
        logger.trace(pickler, "# LRU")
        return
@register(SuperType)
save_module()
dill._dill.save_module (pickler, obj)
Definition at line 1679 of file _dill.py.
def save_module(pickler, obj):
    if False: #_use_diff:
        if obj.__name__.split('.', 1)[0] != "dill":
            try:
                changed = diff.whats_changed(obj, seen=pickler._diff_cache)[0]
            except RuntimeError:  # not memorised module, probably part of dill
                pass
            else:
                logger.trace(pickler, "M2: %s with diff", obj)
                logger.info("Diff: %s", changed.keys())
                pickler.save_reduce(_import_module, (obj.__name__,), obj=obj,
                                    state=changed)
                logger.trace(pickler, "# M2")
                return
        logger.trace(pickler, "M1: %s", obj)
        pickler.save_reduce(_import_module, (obj.__name__,), obj=obj)
        logger.trace(pickler, "# M1")
    else:
        builtin_mod = _is_builtin_module(obj)
        is_session_main = is_dill(pickler, child=True) and obj is pickler._main
        if (obj.__name__ not in ("builtins", "dill", "dill._dill") and not builtin_mod
                or is_session_main):
            logger.trace(pickler, "M1: %s", obj)
            # Hack for handling module-type objects in load_module().
            mod_name = obj.__name__ if _is_imported_module(obj) else '__runtime__.%s' % obj.__name__
            # Second references are saved as __builtin__.__main__ in save_module_dict().
            main_dict = obj.__dict__.copy()
            for item in ('__builtins__', '__loader__'):
                main_dict.pop(item, None)
            for item in IPYTHON_SINGLETONS: #pragma: no cover
                if getattr(main_dict.get(item), '__module__', '').startswith('IPython'):
                    del main_dict[item]
            pickler.save_reduce(_import_module, (mod_name,), obj=obj, state=main_dict)
            logger.trace(pickler, "# M1")
        elif obj.__name__ == "dill._dill":
            logger.trace(pickler, "M2: %s", obj)
            pickler.save_global(obj, name="_dill")
            logger.trace(pickler, "# M2")
        else:
            logger.trace(pickler, "M2: %s", obj)
            pickler.save_reduce(_import_module, (obj.__name__,), obj=obj)
            logger.trace(pickler, "# M2")
    return
# The following function is based on '_extract_class_dict' from 'cloudpickle'
# Copyright (c) 2012, Regents of the University of California.
# Copyright (c) 2009 `PiCloud, Inc. <http://www.picloud.com>`_.
# License: https://github.com/cloudpipe/cloudpickle/blob/master/LICENSE
References _is_builtin_module(), _is_imported_module(), and is_dill().
save_module_dict()
dill._dill.save_module_dict (pickler, obj)
Definition at line 1212 of file _dill.py.
def save_module_dict(pickler, obj):
    if is_dill(pickler, child=False) and obj == pickler._main.__dict__ and \
            not (pickler._session and pickler._first_pass):
        logger.trace(pickler, "D1: %s", _repr_dict(obj)) # obj
        pickler.write(bytes('c__builtin__\n__main__\n', 'UTF-8'))
        logger.trace(pickler, "# D1")
    elif (not is_dill(pickler, child=False)) and (obj == _main_module.__dict__):
        logger.trace(pickler, "D3: %s", _repr_dict(obj)) # obj
        pickler.write(bytes('c__main__\n__dict__\n', 'UTF-8'))  #XXX: works in general?
        logger.trace(pickler, "# D3")
    elif '__name__' in obj and obj != _main_module.__dict__ \
            and type(obj['__name__']) is str \
            and obj is getattr(_import_module(obj['__name__'],True), '__dict__', None):
        logger.trace(pickler, "D4: %s", _repr_dict(obj)) # obj
        pickler.write(bytes('c%s\n__dict__\n' % obj['__name__'], 'UTF-8'))
        logger.trace(pickler, "# D4")
    else:
        logger.trace(pickler, "D2: %s", _repr_dict(obj)) # obj
        if is_dill(pickler, child=False) and pickler._session:
            # we only care about session the first pass thru
            pickler._first_pass = False
        StockPickler.save_dict(pickler, obj)
        logger.trace(pickler, "# D2")
    return
References _import_module(), _repr_dict(), and is_dill().
save_property()
dill._dill.save_property (pickler, obj)
Definition at line 1903 of file _dill.py.
def save_property(pickler, obj):
    logger.trace(pickler, "Pr: %s", obj)
    pickler.save_reduce(type(obj), (obj.fget, obj.fset, obj.fdel, obj.__doc__),
                        obj=obj)
    logger.trace(pickler, "# Pr")
@register(staticmethod)
@register(classmethod)
@register(abc.abstractstaticmethod)
@register(abc.abstractclassmethod)
save_rlock()
dill._dill.save_rlock (pickler, obj)
Definition at line 1341 of file _dill.py.
def save_rlock(pickler, obj):
    logger.trace(pickler, "RL: %s", obj)
    r = obj.__repr__() # don't use _release_save as it unlocks the lock
    count = int(r.split('count=')[1].split()[0].rstrip('>'))
    owner = int(r.split('owner=')[1].split()[0])
    pickler.save_reduce(_create_rlock, (count,owner,), obj=obj)
    logger.trace(pickler, "# RL")
    return
#@register(SocketType) #FIXME: causes multiprocess test_pickling FAIL
save_singleton()
dill._dill.save_singleton (pickler, obj)
Definition at line 1594 of file _dill.py.
def save_singleton(pickler, obj):
    logger.trace(pickler, "Si: %s", obj)
    pickler.save_reduce(_eval_repr, (obj.__repr__(),), obj=obj)
    logger.trace(pickler, "# Si")
    return
save_slice()
dill._dill.save_slice (pickler, obj)
Definition at line 1585 of file _dill.py.
def save_slice(pickler, obj):
    logger.trace(pickler, "Sl: %s", obj)
    pickler.save_reduce(slice, (obj.start, obj.stop, obj.step), obj=obj)
    logger.trace(pickler, "# Sl")
    return
@register(XRangeType)
@register(EllipsisType)
@register(NotImplementedType)
save_socket()
dill._dill.save_socket (pickler, obj)
Definition at line 1351 of file _dill.py.
def save_socket(pickler, obj):
    logger.trace(pickler, "So: %s", obj)
    pickler.save_reduce(*reduce_socket(obj))
    logger.trace(pickler, "# So")
    return
save_stringi()
dill._dill.save_stringi (pickler, obj)
Definition at line 1427 of file _dill.py.
    def save_stringi(pickler, obj):
        logger.trace(pickler, "Io: %s", obj)
        if obj.closed:
            value = ''; position = 0
        else:
            value = obj.getvalue(); position = obj.tell()
        pickler.save_reduce(_create_stringi, (value, position, \
                                              obj.closed), obj=obj)
        logger.trace(pickler, "# Io")
        return
save_stringo()
dill._dill.save_stringo (pickler, obj)
Definition at line 1439 of file _dill.py.
    def save_stringo(pickler, obj):
        logger.trace(pickler, "Io: %s", obj)
        if obj.closed:
            value = ''; position = 0
        else:
            value = obj.getvalue(); position = obj.tell()
        pickler.save_reduce(_create_stringo, (value, position, \
                                              obj.closed), obj=obj)
        logger.trace(pickler, "# Io")
        return
save_super()
dill._dill.save_super (pickler, obj)
Definition at line 1470 of file _dill.py.
def save_super(pickler, obj):
    logger.trace(pickler, "Su: %s", obj)
    pickler.save_reduce(super, (obj.__thisclass__, obj.__self__), obj=obj)
    logger.trace(pickler, "# Su")
    return
save_thread_handle()
dill._dill.save_thread_handle (pickler, obj)
Definition at line 1327 of file _dill.py.
    def save_thread_handle(pickler, obj):
        logger.trace(pickler, "Th: %s", obj)
        pickler.save_reduce(_create_thread_handle, (obj.ident, obj.is_done()), obj=obj)
        logger.trace(pickler, "# Th")
        return
@register(LockType) #XXX: copied Thread will have new Event (due to new Lock)
save_type()
dill._dill.save_type (pickler, obj, postproc_list = None)
Definition at line 1775 of file _dill.py.
def save_type(pickler, obj, postproc_list=None):
    if obj in _typemap:
        logger.trace(pickler, "T1: %s", obj)
        # if obj in _incedental_types:
        #     warnings.warn('Type %r may only exist on this implementation of Python and cannot be unpickled in other implementations.' % (obj,), PicklingWarning)
        pickler.save_reduce(_load_type, (_typemap[obj],), obj=obj)
        logger.trace(pickler, "# T1")
    elif obj.__bases__ == (tuple,) and all([hasattr(obj, attr) for attr in ('_fields','_asdict','_make','_replace')]):
        # special case: namedtuples
        logger.trace(pickler, "T6: %s", obj)
        obj_name = getattr(obj, '__qualname__', getattr(obj, '__name__', None))
        if obj.__name__ != obj_name:
            if postproc_list is None:
                postproc_list = []
            postproc_list.append((setattr, (obj, '__qualname__', obj_name)))
        if not obj._field_defaults:
            _save_with_postproc(pickler, (_create_namedtuple, (obj.__name__, obj._fields, obj.__module__)), obj=obj, postproc_list=postproc_list)
        else:
            defaults = [obj._field_defaults[field] for field in obj._fields if field in obj._field_defaults]
            _save_with_postproc(pickler, (_create_namedtuple, (obj.__name__, obj._fields, obj.__module__, defaults)), obj=obj, postproc_list=postproc_list)
        logger.trace(pickler, "# T6")
        return
    # special caes: NoneType, NotImplementedType, EllipsisType, EnumMeta, etc
    elif obj is type(None):
        logger.trace(pickler, "T7: %s", obj)
        #XXX: pickler.save_reduce(type, (None,), obj=obj)
        pickler.write(GLOBAL + b'__builtin__\nNoneType\n')
        logger.trace(pickler, "# T7")
    elif obj is NotImplementedType:
        logger.trace(pickler, "T7: %s", obj)
        pickler.save_reduce(type, (NotImplemented,), obj=obj)
        logger.trace(pickler, "# T7")
    elif obj is EllipsisType:
        logger.trace(pickler, "T7: %s", obj)
        pickler.save_reduce(type, (Ellipsis,), obj=obj)
        logger.trace(pickler, "# T7")
    elif obj is EnumMeta:
        logger.trace(pickler, "T7: %s", obj)
        pickler.write(GLOBAL + b'enum\nEnumMeta\n')
        logger.trace(pickler, "# T7")
    elif obj is ExceptHookArgsType: #NOTE: must be after NoneType for pypy
        logger.trace(pickler, "T7: %s", obj)
        pickler.write(GLOBAL + b'threading\nExceptHookArgs\n')
        logger.trace(pickler, "# T7")
    else:
        _byref = getattr(pickler, '_byref', None)
        obj_recursive = id(obj) in getattr(pickler, '_postproc', ())
        incorrectly_named = not _locate_function(obj, pickler)
        if not _byref and not obj_recursive and incorrectly_named: # not a function, but the name was held over
            if postproc_list is None:
                postproc_list = []
            # thanks to Tom Stepleton pointing out pickler._session unneeded
            logger.trace(pickler, "T2: %s", obj)
            _dict, attrs = _get_typedict_type(obj, obj.__dict__.copy(), None, postproc_list) # copy dict proxy to a dict
           #print (_dict)
           #print ("%s\n%s" % (type(obj), obj.__name__))
           #print ("%s\n%s" % (obj.__bases__, obj.__dict__))
            slots = _dict.get('__slots__', ())
            if type(slots) == str:
                # __slots__ accepts a single string
                slots = (slots,)
            for name in slots:
                _dict.pop(name, None)
            if isinstance(obj, abc.ABCMeta):
                logger.trace(pickler, "ABC: %s", obj)
                _dict, attrs = _get_typedict_abc(obj, _dict, attrs, postproc_list)
                logger.trace(pickler, "# ABC")
            qualname = getattr(obj, '__qualname__', None)
            if attrs is not None:
                for k, v in attrs.items():
                    postproc_list.append((setattr, (obj, k, v)))
                # TODO: Consider using the state argument to save_reduce?
            if qualname is not None:
                postproc_list.append((setattr, (obj, '__qualname__', qualname)))
            if not hasattr(obj, '__orig_bases__'):
                _save_with_postproc(pickler, (_create_type, (
                    type(obj), obj.__name__, obj.__bases__, _dict
                )), obj=obj, postproc_list=postproc_list)
            else:
                # This case will always work, but might be overkill.
                _metadict = {
                    'metaclass': type(obj)
                }
                if _dict:
                    _dict_update = PartialType(_setitems, source=_dict)
                else:
                    _dict_update = None
                _save_with_postproc(pickler, (new_class, (
                    obj.__name__, obj.__orig_bases__, _metadict, _dict_update
                )), obj=obj, postproc_list=postproc_list)
            logger.trace(pickler, "# T2")
        else:
            obj_name = getattr(obj, '__qualname__', getattr(obj, '__name__', None))
            logger.trace(pickler, "T4: %s", obj)
            if incorrectly_named:
                warnings.warn(
                    "Cannot locate reference to %r." % (obj,),
                    PicklingWarning,
                    stacklevel=3,
                )
            if obj_recursive:
                warnings.warn(
                    "Cannot pickle %r: %s.%s has recursive self-references that "
                    "trigger a RecursionError." % (obj, obj.__module__, obj_name),
                    PicklingWarning,
                    stacklevel=3,
                )
           #print (obj.__dict__)
           #print ("%s\n%s" % (type(obj), obj.__name__))
           #print ("%s\n%s" % (obj.__bases__, obj.__dict__))
            StockPickler.save_global(pickler, obj, name=obj_name)
            logger.trace(pickler, "# T4")
    return
@register(property)
@register(abc.abstractproperty)
References _get_typedict_abc(), _get_typedict_type(), _locate_function(), _save_with_postproc(), and PartialType.
save_weakproxy()
dill._dill.save_weakproxy (pickler, obj)
Definition at line 1648 of file _dill.py.
def save_weakproxy(pickler, obj):
    # Must do string substitution here and use %r to avoid ReferenceError.
    logger.trace(pickler, "R2: %r" % obj)
    refobj = _locate_object(_proxy_helper(obj))
    pickler.save_reduce(_create_weakproxy, (refobj, callable(obj)), obj=obj)
    logger.trace(pickler, "# R2")
    return
References _locate_object(), and _proxy_helper().
save_weakref()
dill._dill.save_weakref (pickler, obj)
Definition at line 1638 of file _dill.py.
def save_weakref(pickler, obj):
    refobj = obj()
    logger.trace(pickler, "R1: %s", obj)
   #refobj = ctypes.pythonapi.PyWeakref_GetObject(obj) # dead returns "None"
    pickler.save_reduce(_create_weakref, (refobj,), obj=obj)
    logger.trace(pickler, "# R1")
    return
@register(ProxyType)
@register(CallableProxyType)
save_wrapper_descriptor()
dill._dill.save_wrapper_descriptor (pickler, obj)
Definition at line 1507 of file _dill.py.
    def save_wrapper_descriptor(pickler, obj):
        logger.trace(pickler, "Wr: %s", obj)
        pickler.save_reduce(_getattr, (obj.__objclass__, obj.__name__,
                                       obj.__repr__()), obj=obj)
        logger.trace(pickler, "# Wr")
        return
use_diff()
dill._dill.use_diff (on = True)
Reduces size of pickles by only including object which have changed.
Decreases pickle size but increases CPU time needed.
Also helps avoid some unpickleable objects.
MUST be called at start of script, otherwise changes will not be recorded.
Definition at line 491 of file _dill.py.
def use_diff(on=True):
    """
    Reduces size of pickles by only including object which have changed.
    Decreases pickle size but increases CPU time needed.
    Also helps avoid some unpickleable objects.
    MUST be called at start of script, otherwise changes will not be recorded.
    """
    global _use_diff, diff
    _use_diff = on
    if _use_diff and diff is None:
        try:
            from . import diff as d
        except ImportError:
            import diff as d
        diff = d
Variable Documentation
_CELL_EMPTY
dill._dill._CELL_EMPTY = Sentinel('_CELL_EMPTY') protected
Definition at line 939 of file _dill.py.
_CELL_REF
dill._dill._CELL_REF = None protected
Definition at line 938 of file _dill.py.
_dictproxy_helper_instance
dill._dill._dictproxy_helper_instance = _dictproxy_helper() protected
Definition at line 921 of file _dill.py.
_incedental_reverse_typemap
dict dill._dill._incedental_reverse_typemap protected
Initial value:
=  {
    'FileType': FileType,
    'BufferedRandomType': BufferedRandomType,
    'BufferedReaderType': BufferedReaderType,
    'BufferedWriterType': BufferedWriterType,
    'TextWrapperType': TextWrapperType,
    'PyBufferedRandomType': PyBufferedRandomType,
    'PyBufferedReaderType': PyBufferedReaderType,
    'PyBufferedWriterType': PyBufferedWriterType,
    'PyTextWrapperType': PyTextWrapperType,
}
Definition at line 535 of file _dill.py.
_incedental_types
dill._dill._incedental_types = set(_incedental_reverse_typemap.values()) protected
Definition at line 588 of file _dill.py.
_PyCapsule_GetContext
dill._dill._PyCapsule_GetContext = ctypes.pythonapi.PyCapsule_GetContext protected
Definition at line 2052 of file _dill.py.
Referenced by save_capsule().
_PyCapsule_GetDestructor
dill._dill._PyCapsule_GetDestructor = ctypes.pythonapi.PyCapsule_GetDestructor protected
Definition at line 2049 of file _dill.py.
Referenced by save_capsule().
_PyCapsule_GetName
dill._dill._PyCapsule_GetName = ctypes.pythonapi.PyCapsule_GetName protected
Definition at line 2055 of file _dill.py.
Referenced by save_capsule().
_PyCapsule_GetPointer
dill._dill._PyCapsule_GetPointer = ctypes.pythonapi.PyCapsule_GetPointer protected
Definition at line 2046 of file _dill.py.
Referenced by save_capsule().
_PyCapsule_IsValid
dill._dill._PyCapsule_IsValid = ctypes.pythonapi.PyCapsule_IsValid protected
Definition at line 2058 of file _dill.py.
Referenced by _create_capsule().
_PyCapsule_New
dill._dill._PyCapsule_New = ctypes.pythonapi.PyCapsule_New protected
Definition at line 2043 of file _dill.py.
Referenced by _create_capsule().
_PyCapsule_SetContext
dill._dill._PyCapsule_SetContext = ctypes.pythonapi.PyCapsule_SetContext protected
Definition at line 2061 of file _dill.py.
Referenced by _create_capsule().
_PyCapsule_SetDestructor
dill._dill._PyCapsule_SetDestructor = ctypes.pythonapi.PyCapsule_SetDestructor protected
Definition at line 2063 of file _dill.py.
_PyCapsule_SetName
dill._dill._PyCapsule_SetName = ctypes.pythonapi.PyCapsule_SetName protected
Definition at line 2065 of file _dill.py.
_PyCapsule_SetPointer
dill._dill._PyCapsule_SetPointer = ctypes.pythonapi.PyCapsule_SetPointer protected
Definition at line 2067 of file _dill.py.
_reverse_typemap
dill._dill._reverse_typemap = dict(_create_typemap()) protected
Definition at line 517 of file _dill.py.
_testcapsule
dill._dill._testcapsule protected
Initial value:
=  _PyCapsule_New(
        ctypes.cast(_PyCapsule_New, ctypes.c_void_p),
        ctypes.c_char_p(_testcapsule_name),
        None
    )
Definition at line 2071 of file _dill.py.
_testcapsule_name
str dill._dill._testcapsule_name = b'dill._dill._testcapsule' protected
Definition at line 2070 of file _dill.py.
_typemap
dill._dill._typemap = dict((v, k) for k, v in _reverse_typemap.items()) protected
Definition at line 592 of file _dill.py.
_use_diff
bool dill._dill._use_diff = False protected
Definition at line 48 of file _dill.py.
ALL_CODE_PARAMS
list dill._dill.ALL_CODE_PARAMS
Initial value:
=  [
    # Version     New attribute         CodeType parameters
    ((3,11,'a'), 'co_endlinetable',    'argcount posonlyargcount kwonlyargcount nlocals stacksize flags code consts names varnames filename name qualname firstlineno linetable endlinetable columntable exceptiontable freevars cellvars'),
    ((3,11),     'co_exceptiontable',  'argcount posonlyargcount kwonlyargcount nlocals stacksize flags code consts names varnames filename name qualname firstlineno linetable                          exceptiontable freevars cellvars'),
    ((3,10),     'co_linetable',       'argcount posonlyargcount kwonlyargcount nlocals stacksize flags code consts names varnames filename name          firstlineno linetable                                         freevars cellvars'),
    ((3,8),      'co_posonlyargcount', 'argcount posonlyargcount kwonlyargcount nlocals stacksize flags code consts names varnames filename name          firstlineno lnotab                                            freevars cellvars'),
    ((3,7),      'co_kwonlyargcount',  'argcount                 kwonlyargcount nlocals stacksize flags code consts names varnames filename name          firstlineno lnotab                                            freevars cellvars'),
    ]
Definition at line 664 of file _dill.py.
argtypes
dill._dill.argtypes
Definition at line 2044 of file _dill.py.
AttrGetterType
dill._dill.AttrGetterType = type(attrgetter('__repr__'))
Definition at line 152 of file _dill.py.
BufferedRandomType
str dill._dill.BufferedRandomType = None if IS_PYODIDE else get_file_type('r+b', buffering=-1)
Definition at line 173 of file _dill.py.
BufferedReaderType
dill._dill.BufferedReaderType = get_file_type('rb', buffering=-1)
Definition at line 174 of file _dill.py.
BufferedWriterType
dill._dill.BufferedWriterType = get_file_type('wb', buffering=-1)
Definition at line 175 of file _dill.py.
BufferType
dill._dill.BufferType = memoryview
Definition at line 70 of file _dill.py.
CellType
dill._dill.CellType = type((lambda x: lambda y: x)(0).__closure__[0])
Definition at line 148 of file _dill.py.
ClassType
dill._dill.ClassType = type
Definition at line 71 of file _dill.py.
CODE_PARAMS
dill._dill.CODE_PARAMS = params.split()
Definition at line 675 of file _dill.py.
CODE_VERSION
dill._dill.CODE_VERSION = version
Definition at line 674 of file _dill.py.
CONTENTS_FMODE
int dill._dill.CONTENTS_FMODE = 1
Definition at line 236 of file _dill.py.
diff
dill._dill.diff = None
Definition at line 47 of file _dill.py.
EllipsisType
dill._dill.EllipsisType = type(Ellipsis)
Definition at line 72 of file _dill.py.
ENCODE_PARAMS
dill._dill.ENCODE_PARAMS
Initial value:
=  set(CODE_PARAMS).intersection(
        ['code', 'lnotab', 'linetable', 'endlinetable', 'columntable', 'exceptiontable'])
Definition at line 677 of file _dill.py.
ExceptHookArgsType
dill._dill.ExceptHookArgsType = None
Definition at line 62 of file _dill.py.
ExitType
dill._dill.ExitType = None
Definition at line 191 of file _dill.py.
EXTENSION_SUFFIXES
dill._dill.EXTENSION_SUFFIXES = tuple(importlib.machinery.EXTENSION_SUFFIXES)
Definition at line 93 of file _dill.py.
FILE_FMODE
int dill._dill.FILE_FMODE = 2
Definition at line 238 of file _dill.py.
FileType
dill._dill.FileType = get_file_type('rb', buffering=0)
Definition at line 171 of file _dill.py.
GENERATOR_FAIL
bool dill._dill.GENERATOR_FAIL = False
Definition at line 91 of file _dill.py.
HANDLE_FMODE
int dill._dill.HANDLE_FMODE = 0
File modes : Pickles the file handle, preserving mode.
The position of the unpickled : object is as for a new file handle.
Definition at line 232 of file _dill.py.
HAS_CTYPES
bool dill._dill.HAS_CTYPES = True
Definition at line 96 of file _dill.py.
InputType
dill._dill.InputType = None
Definition at line 185 of file _dill.py.
IPYTHON_SINGLETONS
tuple dill._dill.IPYTHON_SINGLETONS = ('exit', 'quit', 'get_ipython')
Definition at line 192 of file _dill.py.
IS_IPYTHON
bool dill._dill.IS_IPYTHON = __IPYTHON__
Definition at line 190 of file _dill.py.
IS_PYODIDE
str dill._dill.IS_PYODIDE = 'emscripten'
Definition at line 169 of file _dill.py.
IS_PYPY
bool dill._dill.IS_PYPY = not hasattr(ctypes, 'pythonapi')
Definition at line 98 of file _dill.py.
ItemGetterType
dill._dill.ItemGetterType = type(itemgetter(0))
Definition at line 151 of file _dill.py.
log
dill._dill.log = logger
Definition at line 43 of file _dill.py.
LRUCacheType
dill._dill.LRUCacheType = None
Definition at line 157 of file _dill.py.
MAPPING_PROXY_TRICK
bool dill._dill.MAPPING_PROXY_TRICK = __d is (DictProxyType(__d) | _dictproxy_helper_instance)
Definition at line 929 of file _dill.py.
NotImplementedType
dill._dill.NotImplementedType = type(NotImplemented)
Definition at line 74 of file _dill.py.
NumpyArrayType
bool dill._dill.NumpyArrayType = None
Definition at line 104 of file _dill.py.
NumpyDType
bool dill._dill.NumpyDType = None
Definition at line 103 of file _dill.py.
Referenced by _create_dtypemeta().
NumpyUfuncType
bool dill._dill.NumpyUfuncType = None
Definition at line 102 of file _dill.py.
OLD310
tuple dill._dill.OLD310 = (sys.hexversion < 0x30a0000)
Definition at line 51 of file _dill.py.
OLD312a7
tuple dill._dill.OLD312a7 = (sys.hexversion < 0x30c00a7)
Definition at line 52 of file _dill.py.
OLD38
tuple dill._dill.OLD38 = (sys.hexversion < 0x3080000)
Definition at line 49 of file _dill.py.
OLD39
tuple dill._dill.OLD39 = (sys.hexversion < 0x3090000)
Definition at line 50 of file _dill.py.
PartialType
dill._dill.PartialType = type(partial(int, base=2))
Definition at line 149 of file _dill.py.
Referenced by save_type().
pickle_dispatch_copy
dill._dill.pickle_dispatch_copy = StockPickler.dispatch.copy()
Definition at line 469 of file _dill.py.
PyBufferedRandomType
str dill._dill.PyBufferedRandomType = None if IS_PYODIDE else get_file_type('r+b', buffering=-1, open=_open)
Definition at line 179 of file _dill.py.
PyBufferedReaderType
dill._dill.PyBufferedReaderType = get_file_type('rb', buffering=-1, open=_open)
Definition at line 180 of file _dill.py.
PyBufferedWriterType
dill._dill.PyBufferedWriterType = get_file_type('wb', buffering=-1, open=_open)
Definition at line 181 of file _dill.py.
PyCapsuleType
dill._dill.PyCapsuleType = type(_testcapsule)
Definition at line 2076 of file _dill.py.
PyTextWrapperType
str dill._dill.PyTextWrapperType = get_file_type('r', buffering=-1, open=_open)
Definition at line 178 of file _dill.py.
restype
dill._dill.restype
Definition at line 2045 of file _dill.py.
SliceType
dill._dill.SliceType = slice
Definition at line 75 of file _dill.py.
SuperType
dill._dill.SuperType = type(super(Exception, TypeError()))
Definition at line 150 of file _dill.py.
TextWrapperType
dill._dill.TextWrapperType = get_file_type('r', buffering=-1)
Definition at line 172 of file _dill.py.
ThreadHandleType
dill._dill.ThreadHandleType = None
Definition at line 66 of file _dill.py.
TypeType
dill._dill.TypeType = type
Definition at line 76 of file _dill.py.
x
dill._dill.x = OrderedDict()
Definition at line 534 of file _dill.py.
XRangeType
dill._dill.XRangeType = range
Definition at line 77 of file _dill.py.