Read&Watch: django.utils.inspect Namespace Reference
django.utils.inspect Namespace Reference
Functions
_get_func_parameters (func, remove_first)
_get_callable_parameters (meth_or_func)
get_func_args (func)
get_func_full_args (func)
func_accepts_kwargs (func)
func_accepts_var_args (func)
method_has_no_args (meth)
func_supports_parameter (func, name)
Variables
ARG_KINDS
Function Documentation
_get_callable_parameters()
django.utils.inspect._get_callable_parameters (meth_or_func) protected
Definition at line 13 of file inspect.py.
def _get_callable_parameters(meth_or_func):
    is_method = inspect.ismethod(meth_or_func)
    func = meth_or_func.__func__ if is_method else meth_or_func
    return _get_func_parameters(func, remove_first=is_method)
References _get_func_parameters().
Referenced by func_accepts_kwargs(), func_accepts_var_args(), func_supports_parameter(), get_func_args(), get_func_full_args(), and method_has_no_args().
_get_func_parameters()
django.utils.inspect._get_func_parameters (func, remove_first) protected
Definition at line 6 of file inspect.py.
def _get_func_parameters(func, remove_first):
    parameters = tuple(inspect.signature(func).parameters.values())
    if remove_first:
        parameters = parameters[1:]
    return parameters
Referenced by _get_callable_parameters().
func_accepts_kwargs()
django.utils.inspect.func_accepts_kwargs (func)
Return True if function 'func' accepts keyword arguments **kwargs.
Definition at line 57 of file inspect.py.
def func_accepts_kwargs(func):
    """Return True if function 'func' accepts keyword arguments **kwargs."""
    return any(p for p in _get_callable_parameters(func) if p.kind == p.VAR_KEYWORD)
References _get_callable_parameters().
func_accepts_var_args()
django.utils.inspect.func_accepts_var_args (func)
Return True if function 'func' accepts positional arguments *args.
Definition at line 62 of file inspect.py.
def func_accepts_var_args(func):
    """
    Return True if function 'func' accepts positional arguments *args.
    """
    return any(p for p in _get_callable_parameters(func) if p.kind == p.VAR_POSITIONAL)
References _get_callable_parameters().
func_supports_parameter()
django.utils.inspect.func_supports_parameter (func, name)
Definition at line 75 of file inspect.py.
def func_supports_parameter(func, name):
    return any(param.name == name for param in _get_callable_parameters(func))
References _get_callable_parameters().
get_func_args()
django.utils.inspect.get_func_args (func)
Definition at line 28 of file inspect.py.
def get_func_args(func):
    params = _get_callable_parameters(func)
    return [param.name for param in params if param.kind in ARG_KINDS]
References _get_callable_parameters().
get_func_full_args()
django.utils.inspect.get_func_full_args (func)
Return a list of (argument name, default value) tuples. If the argument
does not have a default value, omit it in the tuple. Arguments such as
*args and **kwargs are also included.
Definition at line 33 of file inspect.py.
def get_func_full_args(func):
    """
    Return a list of (argument name, default value) tuples. If the argument
    does not have a default value, omit it in the tuple. Arguments such as
    *args and **kwargs are also included.
    """
    params = _get_callable_parameters(func)
    args = []
    for param in params:
        name = param.name
        # Ignore 'self'
        if name == "self":
            continue
        if param.kind == inspect.Parameter.VAR_POSITIONAL:
            name = "*" + name
        elif param.kind == inspect.Parameter.VAR_KEYWORD:
            name = "**" + name
        if param.default != inspect.Parameter.empty:
            args.append((name, param.default))
        else:
            args.append((name,))
    return args
References _get_callable_parameters().
method_has_no_args()
django.utils.inspect.method_has_no_args (meth)
Return True if a method only accepts 'self'.
Definition at line 69 of file inspect.py.
def method_has_no_args(meth):
    """Return True if a method only accepts 'self'."""
    count = len([p for p in _get_callable_parameters(meth) if p.kind in ARG_KINDS])
    return count == 0 if inspect.ismethod(meth) else count == 1
References _get_callable_parameters().
Variable Documentation
ARG_KINDS
django.utils.inspect.ARG_KINDS
Initial value:
=  frozenset(
    {
        inspect.Parameter.POSITIONAL_ONLY,
        inspect.Parameter.KEYWORD_ONLY,
        inspect.Parameter.POSITIONAL_OR_KEYWORD,
    }
)
Definition at line 19 of file inspect.py.