Read&Watch: pylint.checkers.symilar Namespace Reference
pylint.checkers.symilar Namespace Reference
Classes
class Commonality
class CplSuccessiveLinesLimits
class LinesChunk
class LineSet
class LineSetStartCouple
class LineSpecifs
class SimilaritiesChecker
class SuccessiveLinesLimits
class Symilar
Functions
tuple[HashToIndex_T, IndexToLines_T] hash_lineset (LineSet lineset, int min_common_lines=DEFAULT_MIN_SIMILARITY_LINE)
None remove_successive (CplIndexToCplLines_T all_couples)
int filter_noncode_lines (LineSet ls_1, Index stindex_1, LineSet ls_2, Index stindex_2, int common_lines_nb)
list[LineSpecifs] stripped_lines (Iterable[str] lines, bool ignore_comments, bool ignore_docstrings, bool ignore_imports, bool ignore_signatures, Callable[[str, int], bool]|None line_enabled_callback=None)
None report_similarities (Section sect, LinterStats stats, LinterStats|None old_stats)
None register (PyLinter linter)
NoReturn Run (Sequence[str]|None argv=None)
Variables
int DEFAULT_MIN_SIMILARITY_LINE = 4
REGEX_FOR_LINES_WITH_CONTENT = re.compile(r".*\w+")
Index = NewType("Index", int)
LineNumber = NewType("LineNumber", int)
HashToIndex_T = dict["LinesChunk", list[Index]]
IndexToLines_T = dict[Index, "SuccessiveLinesLimits"]
STREAM_TYPES = Union[TextIO, BufferedReader, BytesIO]
CplIndexToCplLines_T = dict["LineSetStartCouple", CplSuccessiveLinesLimits]
LinesChunkLimits_T = tuple["LineSet", LineNumber, LineNumber]
Detailed Description
A similarities / code duplication command line tool and pylint checker.
The algorithm is based on comparing the hash value of n successive lines of a file.
First the files are read and any line that doesn't fulfill requirement are removed
(comments, docstrings...)
Those stripped lines are stored in the LineSet class which gives access to them.
Then each index of the stripped lines collection is associated with the hash of n
successive entries of the stripped lines starting at the current index (n is the
minimum common lines option).
The common hashes between both linesets are then looked for. If there are matches, then
the match indices in both linesets are stored and associated with the corresponding
couples (start line number/end line number) in both files.
This association is then post-processed to handle the case of successive matches. For
example if the minimum common lines setting is set to four, then the hashes are
computed with four lines. If one of match indices couple (12, 34) is the
successor of another one (11, 33) then it means that there are in fact five lines which
are common.
Once post-processed the values of association table are the result looked for, i.e.
start and end lines numbers of common lines in both files.
Function Documentation
filter_noncode_lines()
int pylint.checkers.symilar.filter_noncode_lines (LineSet ls_1, Index stindex_1, LineSet ls_2, Index stindex_2, int common_lines_nb)
Return the effective number of common lines between lineset1
and lineset2 filtered from non code lines.
That is to say the number of common successive stripped
lines except those that do not contain code (for example
a line with only an ending parenthesis)
:param ls_1: first lineset
:param stindex_1: first lineset starting index
:param ls_2: second lineset
:param stindex_2: second lineset starting index
:param common_lines_nb: number of common successive stripped lines before being filtered from non code lines
:return: the number of common successive stripped lines that contain code
Definition at line 291 of file symilar.py.
) -> int:
    """Return the effective number of common lines between lineset1
    and lineset2 filtered from non code lines.
    That is to say the number of common successive stripped
    lines except those that do not contain code (for example
    a line with only an ending parenthesis)
    :param ls_1: first lineset
    :param stindex_1: first lineset starting index
    :param ls_2: second lineset
    :param stindex_2: second lineset starting index
    :param common_lines_nb: number of common successive stripped lines before being filtered from non code lines
    :return: the number of common successive stripped lines that contain code
    """
    stripped_l1 = [
        lspecif.text
        for lspecif in ls_1.stripped_lines[stindex_1 : stindex_1 + common_lines_nb]
        if REGEX_FOR_LINES_WITH_CONTENT.match(lspecif.text)
    ]
    stripped_l2 = [
        lspecif.text
        for lspecif in ls_2.stripped_lines[stindex_2 : stindex_2 + common_lines_nb]
        if REGEX_FOR_LINES_WITH_CONTENT.match(lspecif.text)
    ]
    return sum(sline_1 == sline_2 for sline_1, sline_2 in zip(stripped_l1, stripped_l2))
Referenced by pylint.checkers.symilar.Symilar._find_common().
hash_lineset()
tuple[HashToIndex_T, IndexToLines_T] pylint.checkers.symilar.hash_lineset (LineSet lineset, int min_common_lines = DEFAULT_MIN_SIMILARITY_LINE)
Return two dicts.
The first associates the hash of successive stripped lines of a lineset
to the indices of the starting lines.
The second dict, associates the index of the starting line in the lineset's stripped lines to the
couple [start, end] lines number in the corresponding file.
:param lineset: lineset object (i.e the lines in a file)
:param min_common_lines: number of successive lines that are used to compute the hash
:return: a dict linking hashes to corresponding start index and a dict that links this
         index to the start and end lines in the file
Definition at line 207 of file symilar.py.
) -> tuple[HashToIndex_T, IndexToLines_T]:
    """Return two dicts.
    The first associates the hash of successive stripped lines of a lineset
    to the indices of the starting lines.
    The second dict, associates the index of the starting line in the lineset's stripped lines to the
    couple [start, end] lines number in the corresponding file.
    :param lineset: lineset object (i.e the lines in a file)
    :param min_common_lines: number of successive lines that are used to compute the hash
    :return: a dict linking hashes to corresponding start index and a dict that links this
             index to the start and end lines in the file
    """
    hash2index = defaultdict(list)
    index2lines = {}
    # Comments, docstring and other specific patterns maybe excluded -> call to stripped_lines
    # to get only what is desired
    lines = tuple(x.text for x in lineset.stripped_lines)
    # Need different iterators on same lines but each one is shifted 1 from the precedent
    shifted_lines = [iter(lines[i:]) for i in range(min_common_lines)]
    for i, *succ_lines in enumerate(zip(*shifted_lines)):
        start_linenumber = LineNumber(lineset.stripped_lines[i].line_number)
        try:
            end_linenumber = lineset.stripped_lines[i + min_common_lines].line_number
        except IndexError:
            end_linenumber = LineNumber(lineset.stripped_lines[-1].line_number + 1)
        index = Index(i)
        index2lines[index] = SuccessiveLinesLimits(
            start=start_linenumber, end=end_linenumber
        )
        l_c = LinesChunk(lineset.name, index, *succ_lines)
        hash2index[l_c].append(index)
    return hash2index, index2lines
References Index, and LineNumber.
Referenced by pylint.checkers.symilar.Symilar._find_common().
register()
None pylint.checkers.symilar.register (PyLinter linter)
Definition at line 879 of file symilar.py.
def register(linter: PyLinter) -> None:
    linter.register_checker(SimilaritiesChecker(linter))
remove_successive()
None pylint.checkers.symilar.remove_successive (CplIndexToCplLines_T all_couples)
Removes all successive entries in the dictionary in argument.
:param all_couples: collection that has to be cleaned up from successive entries.
                    The keys are couples of indices that mark the beginning of common entries
                    in both linesets. The values have two parts. The first one is the couple
                    of starting and ending line numbers of common successive lines in the first file.
                    The second part is the same for the second file.
For example consider the following dict:
>>> all_couples
{(11, 34): ([5, 9], [27, 31]),
 (23, 79): ([15, 19], [45, 49]),
 (12, 35): ([6, 10], [28, 32])}
There are two successive keys (11, 34) and (12, 35).
It means there are two consecutive similar chunks of lines in both files.
Thus remove last entry and update the last line numbers in the first entry
>>> remove_successive(all_couples)
>>> all_couples
{(11, 34): ([5, 10], [27, 32]),
 (23, 79): ([15, 19], [45, 49])}
Definition at line 248 of file symilar.py.
def remove_successive(all_couples: CplIndexToCplLines_T) -> None:
    """Removes all successive entries in the dictionary in argument.
    :param all_couples: collection that has to be cleaned up from successive entries.
                        The keys are couples of indices that mark the beginning of common entries
                        in both linesets. The values have two parts. The first one is the couple
                        of starting and ending line numbers of common successive lines in the first file.
                        The second part is the same for the second file.
    For example consider the following dict:
    >>> all_couples
    {(11, 34): ([5, 9], [27, 31]),
     (23, 79): ([15, 19], [45, 49]),
     (12, 35): ([6, 10], [28, 32])}
    There are two successive keys (11, 34) and (12, 35).
    It means there are two consecutive similar chunks of lines in both files.
    Thus remove last entry and update the last line numbers in the first entry
    >>> remove_successive(all_couples)
    >>> all_couples
    {(11, 34): ([5, 10], [27, 32]),
     (23, 79): ([15, 19], [45, 49])}
    """
    couple: LineSetStartCouple
    for couple in tuple(all_couples.keys()):
        to_remove = []
        test = couple.increment(Index(1))
        while test in all_couples:
            all_couples[couple].first_file.end = all_couples[test].first_file.end
            all_couples[couple].second_file.end = all_couples[test].second_file.end
            all_couples[couple].effective_cmn_lines_nb += 1
            to_remove.append(test)
            test = test.increment(Index(1))
        for target in to_remove:
            try:
                all_couples.pop(target)
            except KeyError:
                pass
References Index.
Referenced by pylint.checkers.symilar.Symilar._find_common().
report_similarities()
None pylint.checkers.symilar.report_similarities (Section sect, LinterStats stats, LinterStats | None old_stats)
Make a layout with some stats about duplication.
Definition at line 731 of file symilar.py.
) -> None:
    """Make a layout with some stats about duplication."""
    lines = ["", "now", "previous", "difference"]
    lines += table_lines_from_stats(stats, old_stats, "duplicated_lines")
    sect.append(Table(children=lines, cols=4, rheaders=1, cheaders=1))
# wrapper to get a pylint checker from the similar class
References pylint.checkers.table_lines_from_stats().
Run()
NoReturn pylint.checkers.symilar.Run (Sequence[str] | None argv = None)
Standalone command line access point.
Definition at line 883 of file symilar.py.
def Run(argv: Sequence[str] | None = None) -> NoReturn:
    """Standalone command line access point."""
    parser = argparse.ArgumentParser(
        prog="symilar", description="Finds copy pasted blocks in a set of files."
    )
    parser.add_argument("files", nargs="+")
    parser.add_argument(
        "-d",
        "--duplicates",
        type=int,
        default=DEFAULT_MIN_SIMILARITY_LINE,
        help=SimilaritiesChecker.MIN_SIMILARITY_HELP,
    )
    parser.add_argument(
        "-i",
        "--ignore-comments",
        action="store_true",
        help=SimilaritiesChecker.IGNORE_COMMENTS_HELP,
    )
    parser.add_argument(
        "--ignore-docstrings",
        action="store_true",
        help=SimilaritiesChecker.IGNORE_DOCSTRINGS_HELP,
    )
    parser.add_argument(
        "--ignore-imports",
        action="store_true",
        help=SimilaritiesChecker.IGNORE_IMPORTS_HELP,
    )
    parser.add_argument(
        "--ignore-signatures",
        action="store_true",
        help=SimilaritiesChecker.IGNORE_SIGNATURES_HELP,
    )
    parsed_args = parser.parse_args(args=argv)
    similar_runner = Symilar(
        min_lines=parsed_args.duplicates,
        ignore_comments=parsed_args.ignore_comments,
        ignore_docstrings=parsed_args.ignore_docstrings,
        ignore_imports=parsed_args.ignore_imports,
        ignore_signatures=parsed_args.ignore_signatures,
    )
    for filename in parsed_args.files:
        with open(filename, encoding="utf-8") as stream:
            similar_runner.append_stream(filename, stream)
    similar_runner.run()
    # the sys exit must be kept because of the unit tests that rely on it
    sys.exit(0)
References Run().
Referenced by Run().
stripped_lines()
list[LineSpecifs] pylint.checkers.symilar.stripped_lines (Iterable[str] lines, bool ignore_comments, bool ignore_docstrings, bool ignore_imports, bool ignore_signatures, Callable[[str, int], bool] | None line_enabled_callback = None)
Return tuples of line/line number/line type with leading/trailing white-space and
any ignored code features removed.
:param lines: a collection of lines
:param ignore_comments: if true, any comment in the lines collection is removed from the result
:param ignore_docstrings: if true, any line that is a docstring is removed from the result
:param ignore_imports: if true, any line that is an import is removed from the result
:param ignore_signatures: if true, any line that is part of a function signature is removed from the result
:param line_enabled_callback: If called with "R0801" and a line number, a return value of False will disregard
       the line
:return: the collection of line/line number/line type tuples
Definition at line 568 of file symilar.py.
) -> list[LineSpecifs]:
    """Return tuples of line/line number/line type with leading/trailing white-space and
    any ignored code features removed.
    :param lines: a collection of lines
    :param ignore_comments: if true, any comment in the lines collection is removed from the result
    :param ignore_docstrings: if true, any line that is a docstring is removed from the result
    :param ignore_imports: if true, any line that is an import is removed from the result
    :param ignore_signatures: if true, any line that is part of a function signature is removed from the result
    :param line_enabled_callback: If called with "R0801" and a line number, a return value of False will disregard
           the line
    :return: the collection of line/line number/line type tuples
    """
    ignore_lines: set[int] = set()
    if ignore_imports or ignore_signatures:
        tree = astroid.parse("".join(lines))
        if ignore_imports:
            ignore_lines.update(
                chain.from_iterable(
                    range(node.lineno, (node.end_lineno or node.lineno) + 1)
                    for node in tree.nodes_of_class((nodes.Import, nodes.ImportFrom))
                )
            )
        if ignore_signatures:
            def _get_functions(
                functions: list[nodes.NodeNG], tree: nodes.NodeNG
            ) -> list[nodes.NodeNG]:
                """Recursively get all functions including nested in the classes from
                the.
                tree.
                """
                for node in tree.body:
                    if isinstance(node, (nodes.FunctionDef, nodes.AsyncFunctionDef)):
                        functions.append(node)
                    if isinstance(
                        node,
                        (nodes.ClassDef, nodes.FunctionDef, nodes.AsyncFunctionDef),
                    ):
                        _get_functions(functions, node)
                return functions
            functions = _get_functions([], tree)
            ignore_lines.update(
                chain.from_iterable(
                    range(
                        func.lineno,
                        func.body[0].lineno if func.body else func.tolineno + 1,
                    )
                    for func in functions
                )
            )
    strippedlines = []
    docstring = None
    for lineno, line in enumerate(lines, start=1):
        if line_enabled_callback is not None and not line_enabled_callback(
            "R0801", lineno
        ):
            continue
        line = line.strip()
        if ignore_docstrings:
            if not docstring:
                if line.startswith(('"""', "'''")):
                    docstring = line[:3]
                    line = line[3:]
                elif line.startswith(('r"""', "r'''")):
                    docstring = line[1:4]
                    line = line[4:]
            if docstring:
                if line.endswith(docstring):
                    docstring = None
                line = ""
        if ignore_comments:
            line = line.split("#", 1)[0].strip()
        if lineno in ignore_lines:
            line = ""
        if line:
            strippedlines.append(
                LineSpecifs(text=line, line_number=LineNumber(lineno - 1))
            )
    return strippedlines
@functools.total_ordering
References LineNumber.
Variable Documentation
CplIndexToCplLines_T
pylint.checkers.symilar.CplIndexToCplLines_T = dict["LineSetStartCouple", CplSuccessiveLinesLimits]
Definition at line 105 of file symilar.py.
DEFAULT_MIN_SIMILARITY_LINE
int pylint.checkers.symilar.DEFAULT_MIN_SIMILARITY_LINE = 4
Definition at line 57 of file symilar.py.
HashToIndex_T
pylint.checkers.symilar.HashToIndex_T = dict["LinesChunk", list[Index]]
Definition at line 76 of file symilar.py.
Index
pylint.checkers.symilar.Index = NewType("Index", int)
Definition at line 62 of file symilar.py.
Referenced by hash_lineset(), pylint.checkers.symilar.LineSetStartCouple.increment(), and remove_successive().
IndexToLines_T
pylint.checkers.symilar.IndexToLines_T = dict[Index, "SuccessiveLinesLimits"]
Definition at line 79 of file symilar.py.
LineNumber
pylint.checkers.symilar.LineNumber = NewType("LineNumber", int)
Definition at line 65 of file symilar.py.
Referenced by hash_lineset(), and stripped_lines().
LinesChunkLimits_T
pylint.checkers.symilar.LinesChunkLimits_T = tuple["LineSet", LineNumber, LineNumber]
Definition at line 204 of file symilar.py.
REGEX_FOR_LINES_WITH_CONTENT
pylint.checkers.symilar.REGEX_FOR_LINES_WITH_CONTENT = re.compile(r".*\w+")
Definition at line 59 of file symilar.py.
STREAM_TYPES
pylint.checkers.symilar.STREAM_TYPES = Union[TextIO, BufferedReader, BytesIO]
Definition at line 82 of file symilar.py.