Read&Watch: pip._internal.network.cache Namespace Reference
pip._internal.network.cache Namespace Reference
Classes
class SafeFileCache
Functions
bool is_from_cache (Response response)
Generator[None, None, None] suppressed_cache_errors ()
Detailed Description
HTTP cache implementation.
Function Documentation
is_from_cache()
bool pip._internal.network.cache.is_from_cache (Response response)
Definition at line 17 of file cache.py.
def is_from_cache(response: Response) -> bool:
    return getattr(response, "from_cache", False)
@contextmanager
suppressed_cache_errors()
Generator[None, None, None] pip._internal.network.cache.suppressed_cache_errors ()
If we can't access the cache then we can just skip caching and process
requests as if caching wasn't enabled.
Definition at line 22 of file cache.py.
def suppressed_cache_errors() -> Generator[None, None, None]:
    """If we can't access the cache then we can just skip caching and process
    requests as if caching wasn't enabled.
    """
    try:
        yield
    except OSError:
        pass
Referenced by pip._internal.network.cache.SafeFileCache._write(), pip._internal.network.cache.SafeFileCache.delete(), pip._internal.network.cache.SafeFileCache.get(), and pip._internal.network.cache.SafeFileCache.get_body().