Read&Watch: django.contrib.admindocs.views Namespace Reference
django.contrib.admindocs.views Namespace Reference
Classes
class BaseAdminDocsView
class BookmarkletsView
class ModelDetailView
class ModelIndexView
class TemplateDetailView
class TemplateFilterIndexView
class TemplateTagIndexView
class ViewDetailView
class ViewIndexView
Functions
get_return_data_type (func_name)
get_readable_field_data_type (field)
extract_views_from_urlpatterns (urlpatterns, base="", namespace=None)
simplify_regex (pattern)
Variables
tuple MODEL_METHODS_EXCLUDE = ("_", "add_", "delete", "save", "set_")
Function Documentation
extract_views_from_urlpatterns()
django.contrib.admindocs.views.extract_views_from_urlpatterns (urlpatterns, base = "", namespace = None)
Return a list of views from a list of urlpatterns.
Each object in the returned list is a 4-tuple:
(view_func, regex, namespace, name)
Definition at line 460 of file views.py.
def extract_views_from_urlpatterns(urlpatterns, base="", namespace=None):
    """
    Return a list of views from a list of urlpatterns.
    Each object in the returned list is a 4-tuple:
    (view_func, regex, namespace, name)
    """
    views = []
    for p in urlpatterns:
        if hasattr(p, "url_patterns"):
            try:
                patterns = p.url_patterns
            except ImportError:
                continue
            views.extend(
                extract_views_from_urlpatterns(
                    patterns,
                    base + str(p.pattern),
                    (namespace or []) + (p.namespace and [p.namespace] or []),
                )
            )
        elif hasattr(p, "callback"):
            try:
                views.append((p.callback, base + str(p.pattern), namespace, p.name))
            except ViewDoesNotExist:
                continue
        else:
            raise TypeError(_("%s does not appear to be a urlpattern object") % p)
    return views
References extract_views_from_urlpatterns().
Referenced by extract_views_from_urlpatterns(), and django.contrib.admindocs.views.ViewIndexView.get_context_data().
get_readable_field_data_type()
django.contrib.admindocs.views.get_readable_field_data_type (field)
Return the description for a given field type, if it exists. Fields'
descriptions can contain format strings, which will be interpolated with
the values of field.__dict__ before being output.
Definition at line 451 of file views.py.
def get_readable_field_data_type(field):
    """
    Return the description for a given field type, if it exists. Fields'
    descriptions can contain format strings, which will be interpolated with
    the values of field.__dict__ before being output.
    """
    return field.description % field.__dict__
get_return_data_type()
django.contrib.admindocs.views.get_return_data_type (func_name)
Return a somewhat-helpful data type given a function name
Definition at line 441 of file views.py.
def get_return_data_type(func_name):
    """Return a somewhat-helpful data type given a function name"""
    if func_name.startswith("get_"):
        if func_name.endswith("_list"):
            return "List"
        elif func_name.endswith("_count"):
            return "Integer"
    return ""
simplify_regex()
django.contrib.admindocs.views.simplify_regex (pattern)
Clean up urlpattern regexes into something more readable by humans. For
example, turn "^(?P<sport_slug>\w+)/athletes/(?P<athlete_slug>\w+)/$"
into "/<sport_slug>/athletes/<athlete_slug>/".
Definition at line 491 of file views.py.
def simplify_regex(pattern):
    r"""
    Clean up urlpattern regexes into something more readable by humans. For
    example, turn "^(?P<sport_slug>\w+)/athletes/(?P<athlete_slug>\w+)/$"
    into "/<sport_slug>/athletes/<athlete_slug>/".
    """
    pattern = remove_non_capturing_groups(pattern)
    pattern = replace_named_groups(pattern)
    pattern = replace_unnamed_groups(pattern)
    pattern = replace_metacharacters(pattern)
    if not pattern.startswith("/"):
        pattern = "/" + pattern
    return pattern
Referenced by django.contrib.admindocs.views.ViewIndexView.get_context_data().
Variable Documentation
MODEL_METHODS_EXCLUDE
tuple django.contrib.admindocs.views.MODEL_METHODS_EXCLUDE = ("_", "add_", "delete", "save", "set_")
Definition at line 36 of file views.py.