Read&Watch: pylint.checkers.unicode Namespace Reference
pylint.checkers.unicode Namespace Reference
Classes
class _BadChar
class UnicodeChecker
Functions
int _line_length (_StrLike line, str codec)
dict[int, _BadChar] _map_positions_to_result (_StrLike line, dict[_StrLike, _BadChar] search_dict, _StrLike new_line, int byte_str_length=1)
str _normalize_codec_name (str codec)
bytes _remove_bom (bytes encoded, str encoding)
bytes _encode_without_bom (str string, str encoding)
int _byte_to_str_length (str codec)
bytes _cached_encode_search (str string, str encoding)
Iterable[bytes] _fix_utf16_32_line_stream (Iterable[bytes] steam, str codec)
str extract_codec_from_bom (bytes first_line)
None register (pylint.lint.PyLinter linter)
Variables
_StrLike = TypeVar("_StrLike", str, bytes)
list BIDI_UNICODE
list BAD_CHARS
dict BAD_ASCII_SEARCH_DICT = {char.unescaped: char for char in BAD_CHARS}
dict UNICODE_BOMS
BOM_SORTED_TO_CODEC
UTF_NAME_REGEX_COMPILED
Detailed Description
Unicode and some other ASCII characters can be used to create programs that run
much different compared to what a human reader would expect from them.
PEP 672 lists some examples.
See: https://www.python.org/dev/peps/pep-0672/
The following checkers are intended to make users are aware of these issues.
Function Documentation
_byte_to_str_length()
int pylint.checkers.unicode._byte_to_str_length (str codec) protected
Return how many byte are usually(!) a character point.
Definition at line 233 of file unicode.py.
def _byte_to_str_length(codec: str) -> int:
    """Return how many byte are usually(!) a character point."""
    if codec.startswith("utf-32"):
        return 4
    if codec.startswith("utf-16"):
        return 2
    return 1
@lru_cache(maxsize=1000)
Referenced by pylint.checkers.unicode.UnicodeChecker._find_line_matches().
_cached_encode_search()
bytes pylint.checkers.unicode._cached_encode_search (str string, str encoding) protected
A cached version of encode used for search pattern.
Definition at line 244 of file unicode.py.
def _cached_encode_search(string: str, encoding: str) -> bytes:
    """A cached version of encode used for search pattern."""
    return _encode_without_bom(string, encoding)
References _encode_without_bom().
Referenced by pylint.checkers.unicode.UnicodeChecker._check_bidi_chars(), pylint.checkers.unicode.UnicodeChecker._find_line_matches(), and _fix_utf16_32_line_stream().
_encode_without_bom()
bytes pylint.checkers.unicode._encode_without_bom (str string, str encoding) protected
Encode a string but remove the BOM.
Definition at line 228 of file unicode.py.
def _encode_without_bom(string: str, encoding: str) -> bytes:
    """Encode a string but remove the BOM."""
    return _remove_bom(string.encode(encoding), encoding)
References _remove_bom().
Referenced by _cached_encode_search().
_fix_utf16_32_line_stream()
Iterable[bytes] pylint.checkers.unicode._fix_utf16_32_line_stream (Iterable[bytes] steam, str codec) protected
Handle line ending for UTF16 and UTF32 correctly.
Currently, Python simply strips the required zeros after \n after the
line ending. Leading to lines that can't be decoded properly
Definition at line 249 of file unicode.py.
def _fix_utf16_32_line_stream(steam: Iterable[bytes], codec: str) -> Iterable[bytes]:
    r"""Handle line ending for UTF16 and UTF32 correctly.
    Currently, Python simply strips the required zeros after \n after the
    line ending. Leading to lines that can't be decoded properly
    """
    if not codec.startswith("utf-16") and not codec.startswith("utf-32"):
        yield from steam
    else:
        # First we get all the bytes in memory
        content = b"".join(line for line in steam)
        new_line = _cached_encode_search("\n", codec)
        # Now we split the line by the real new line in the correct encoding
        # we can't use split as it would strip the \n that we need
        start = 0
        while True:
            pos = content.find(new_line, start)
            if pos >= 0:
                yield content[start : pos + len(new_line)]
            else:
                # Yield the rest and finish
                if content[start:]:
                    yield content[start:]
                break
            start = pos + len(new_line)
References _cached_encode_search().
Referenced by pylint.checkers.unicode.UnicodeChecker.process_module().
_line_length()
int pylint.checkers.unicode._line_length (_StrLike line, str codec) protected
Get the length of a string like line as displayed in an editor.
Definition at line 141 of file unicode.py.
def _line_length(line: _StrLike, codec: str) -> int:
    """Get the length of a string like line as displayed in an editor."""
    if isinstance(line, bytes):
        decoded = _remove_bom(line, codec).decode(codec, "replace")
    else:
        decoded = line
    stripped = decoded.rstrip("\n")
    if stripped != decoded:
        stripped = stripped.rstrip("\r")
    return len(stripped)
References _remove_bom().
Referenced by pylint.checkers.unicode.UnicodeChecker._check_bidi_chars().
_map_positions_to_result()
dict[int, _BadChar] pylint.checkers.unicode._map_positions_to_result (_StrLike line, dict[_StrLike, _BadChar] search_dict, _StrLike new_line, int byte_str_length = 1) protected
Get all occurrences of search dict keys within line.
Ignores Windows end of line and can handle bytes as well as string.
Also takes care of encodings for which the length of an encoded code point does not
default to 8 Bit.
Definition at line 156 of file unicode.py.
) -> dict[int, _BadChar]:
    """Get all occurrences of search dict keys within line.
    Ignores Windows end of line and can handle bytes as well as string.
    Also takes care of encodings for which the length of an encoded code point does not
    default to 8 Bit.
    """
    result: dict[int, _BadChar] = {}
    for search_for, char in search_dict.items():
        if search_for not in line:
            continue
        # Special Handling for Windows '\r\n'
        if char.unescaped == "\r" and line.endswith(new_line):
            ignore_pos = len(line) - 2 * byte_str_length
        else:
            ignore_pos = None
        start = 0
        pos = line.find(search_for, start)
        while pos > 0:
            if pos != ignore_pos:
                # Calculate the column
                col = int(pos / byte_str_length)
                result[col] = char
            start = pos + 1
            pos = line.find(search_for, start)
    return result
Referenced by pylint.checkers.unicode.UnicodeChecker._find_line_matches().
_normalize_codec_name()
str pylint.checkers.unicode._normalize_codec_name (str codec) protected
Make sure the codec name is always given as defined in the BOM dict.
Definition at line 213 of file unicode.py.
def _normalize_codec_name(codec: str) -> str:
    """Make sure the codec name is always given as defined in the BOM dict."""
    return UTF_NAME_REGEX_COMPILED.sub(r"utf-\1\2", codec).lower()
Referenced by pylint.checkers.unicode.UnicodeChecker._determine_codec().
_remove_bom()
bytes pylint.checkers.unicode._remove_bom (bytes encoded, str encoding) protected
Remove the bom if given from a line.
Definition at line 218 of file unicode.py.
def _remove_bom(encoded: bytes, encoding: str) -> bytes:
    """Remove the bom if given from a line."""
    if encoding not in UNICODE_BOMS:
        return encoded
    bom = UNICODE_BOMS[encoding]
    if encoded.startswith(bom):
        return encoded[len(bom) :]
    return encoded
Referenced by _encode_without_bom(), _line_length(), and pylint.checkers.unicode.UnicodeChecker.process_module().
extract_codec_from_bom()
str pylint.checkers.unicode.extract_codec_from_bom (bytes first_line)
Try to extract the codec (unicode only) by checking for the BOM.
For details about BOM see https://unicode.org/faq/utf_bom.html#BOM
Args:
    first_line: the first line of a file
Returns:
    a codec name
Raises:
    ValueError: if no codec was found
Definition at line 279 of file unicode.py.
def extract_codec_from_bom(first_line: bytes) -> str:
    """Try to extract the codec (unicode only) by checking for the BOM.
    For details about BOM see https://unicode.org/faq/utf_bom.html#BOM
    Args:
        first_line: the first line of a file
    Returns:
        a codec name
    Raises:
        ValueError: if no codec was found
    """
    for bom, codec in BOM_SORTED_TO_CODEC.items():
        if first_line.startswith(bom):
            return codec
    raise ValueError("No BOM found. Could not detect Unicode codec.")
Referenced by pylint.checkers.unicode.UnicodeChecker._determine_codec().
register()
None pylint.checkers.unicode.register (pylint.lint.PyLinter linter)
Definition at line 536 of file unicode.py.
def register(linter: pylint.lint.PyLinter) -> None:
    linter.register_checker(UnicodeChecker(linter))
Variable Documentation
_StrLike
pylint.checkers.unicode._StrLike = TypeVar("_StrLike", str, bytes) protected
Definition at line 32 of file unicode.py.
BAD_ASCII_SEARCH_DICT
dict pylint.checkers.unicode.BAD_ASCII_SEARCH_DICT = {char.unescaped: char for char in BAD_CHARS}
Definition at line 138 of file unicode.py.
BAD_CHARS
list pylint.checkers.unicode.BAD_CHARS
Definition at line 80 of file unicode.py.
BIDI_UNICODE
list pylint.checkers.unicode.BIDI_UNICODE
Initial value:
=  [
    "\u202A",  # \N{LEFT-TO-RIGHT EMBEDDING}
    "\u202B",  # \N{RIGHT-TO-LEFT EMBEDDING}
    "\u202C",  # \N{POP DIRECTIONAL FORMATTING}
    "\u202D",  # \N{LEFT-TO-RIGHT OVERRIDE}
    "\u202E",  # \N{RIGHT-TO-LEFT OVERRIDE}
    "\u2066",  # \N{LEFT-TO-RIGHT ISOLATE}
    "\u2067",  # \N{RIGHT-TO-LEFT ISOLATE}
    "\u2068",  # \N{FIRST STRONG ISOLATE}
    "\u2069",  # \N{POP DIRECTIONAL ISOLATE}
    # The following was part of PEP 672:
    # https://www.python.org/dev/peps/pep-0672/
    # so the list above might not be complete
    "\u200F",  # \n{RIGHT-TO-LEFT MARK}
    # We don't use    #   "\u200E" # \n{LEFT-TO-RIGHT MARK}    # as this is the default for latin files and can't be used
    # to hide code
]
Definition at line 37 of file unicode.py.
BOM_SORTED_TO_CODEC
pylint.checkers.unicode.BOM_SORTED_TO_CODEC
Initial value:
=  OrderedDict(
    # Sorted by length of BOM of each codec
    (UNICODE_BOMS[codec], codec)
    for codec in ("utf-32le", "utf-32be", "utf-8", "utf-16le", "utf-16be")
)
Definition at line 202 of file unicode.py.
UNICODE_BOMS
dict pylint.checkers.unicode.UNICODE_BOMS
Initial value:
=  {
    "utf-8": codecs.BOM_UTF8,
    "utf-16": codecs.BOM_UTF16,
    "utf-32": codecs.BOM_UTF32,
    "utf-16le": codecs.BOM_UTF16_LE,
    "utf-16be": codecs.BOM_UTF16_BE,
    "utf-32le": codecs.BOM_UTF32_LE,
    "utf-32be": codecs.BOM_UTF32_BE,
}
Definition at line 193 of file unicode.py.
UTF_NAME_REGEX_COMPILED
pylint.checkers.unicode.UTF_NAME_REGEX_COMPILED
Initial value:
=  re.compile(
    "utf[ -]?(8|16|32)[ -]?(le|be|)?(sig)?", flags=re.IGNORECASE
)
Definition at line 208 of file unicode.py.