Read&Watch: dill.tests.test_classdef Namespace Reference
dill.tests.test_classdef Namespace Reference
Classes
class _class
class _class2
class _meta
class _newclass
class _newclass2
class customIntList
class Y
class Y2
Functions
__call__ (self)
ok (self)
test_class_instances ()
test_class_objects ()
test_specialtypes ()
test_namedtuple ()
test_dtype ()
test_array_nested ()
test_array_subclass ()
test_method_decorator ()
test_slots ()
test_origbases ()
test_attr ()
test_metaclass ()
test_enummeta ()
test_inherit ()
Variables
_mclass = _meta("_mclass", (object,), {"__call__": __call__, "ok": ok})
o = _class()
oc = _class2()
n = _newclass()
nc = _newclass2()
m = _mclass()
Z = namedtuple("Z", ['a','b'])
Zi = Z(0,1)
X = namedtuple("Y", ['a','b'])
Xi = X(0,1)
Bad = namedtuple("FakeName", ['a','b'])
Badi = Bad(0,1)
Defaults = namedtuple('Defaults', ['x', 'y'], defaults=[1])
Defaultsi = Defaults(2)
int value = 123
y = Y(value)
color = obj.color
Function Documentation
__call__()
dill.tests.test_classdef.__call__ (self)
Definition at line 42 of file test_classdef.py.
def __call__(self):
    pass
ok()
dill.tests.test_classdef.ok (self)
Definition at line 44 of file test_classdef.py.
def ok(self):
    return True
test_array_nested()
dill.tests.test_classdef.test_array_nested ()
Definition at line 159 of file test_classdef.py.
def test_array_nested():
    try:
        import numpy as np
        x = np.array([1])
        y = (x,)
        assert y == dill.copy(y)
    except ImportError: pass
Referenced by test_inherit().
test_array_subclass()
dill.tests.test_classdef.test_array_subclass ()
Definition at line 170 of file test_classdef.py.
def test_array_subclass():
    try:
        import numpy as np
        class TestArray(np.ndarray):
            def __new__(cls, input_array, color):
                obj = np.asarray(input_array).view(cls)
                obj.color = color
                return obj
            def __array_finalize__(self, obj):
                if obj is None:
                    return
                if isinstance(obj, type(self)):
                    self.color = obj.color
            def __getnewargs__(self):
                return np.asarray(self), self.color
        a1 = TestArray(np.zeros(100), color='green')
        if not dill._dill.IS_PYPY:
            assert dill.pickles(a1)
            assert a1.__dict__ == dill.copy(a1).__dict__
        a2 = a1[0:9]
        if not dill._dill.IS_PYPY:
            assert dill.pickles(a2)
            assert a2.__dict__ == dill.copy(a2).__dict__
        class TestArray2(np.ndarray):
            color = 'blue'
        a3 = TestArray2([1,2,3,4,5])
        a3.color = 'green'
        if not dill._dill.IS_PYPY:
            assert dill.pickles(a3)
            assert a3.__dict__ == dill.copy(a3).__dict__
    except ImportError: pass
Referenced by test_inherit().
test_attr()
dill.tests.test_classdef.test_attr ()
Definition at line 245 of file test_classdef.py.
def test_attr():
    import attr
    @attr.s
    class A:
        a = attr.ib()
    v = A(1)
    assert dill.copy(v) == v
test_class_instances()
dill.tests.test_classdef.test_class_instances ()
Definition at line 67 of file test_classdef.py.
def test_class_instances():
    assert dill.pickles(o)
    assert dill.pickles(oc)
    assert dill.pickles(n)
    assert dill.pickles(nc)
    assert dill.pickles(m)
Referenced by test_inherit().
test_class_objects()
dill.tests.test_classdef.test_class_objects ()
Definition at line 74 of file test_classdef.py.
def test_class_objects():
    clslist = [_class,_class2,_newclass,_newclass2,_mclass]
    objlist = [o,oc,n,nc,m]
    _clslist = [dill.dumps(obj) for obj in clslist]
    _objlist = [dill.dumps(obj) for obj in objlist]
    for obj in clslist:
        globals().pop(obj.__name__)
    del clslist
    for obj in ['o','oc','n','nc']:
        globals().pop(obj)
    del objlist
    del obj
    for obj,cls in zip(_objlist,_clslist):
        _cls = dill.loads(cls)
        _obj = dill.loads(obj)
        assert _obj.ok()
        assert _cls.ok(_cls())
        if _cls.__name__ == "_mclass":
            assert type(_cls).__name__ == "_meta"
# test NoneType
Referenced by test_inherit().
test_dtype()
dill.tests.test_classdef.test_dtype ()
Definition at line 149 of file test_classdef.py.
def test_dtype():
    try:
        import numpy as np
        dti = np.dtype('int')
        assert np.dtype == dill.copy(np.dtype)
        assert dti == dill.copy(dti)
    except ImportError: pass
Referenced by test_inherit().
test_enummeta()
dill.tests.test_classdef.test_enummeta ()
Definition at line 273 of file test_classdef.py.
def test_enummeta():
    from http import HTTPStatus
    import enum
    assert dill.copy(HTTPStatus.OK) is HTTPStatus.OK
    assert dill.copy(enum.EnumMeta) is enum.EnumMeta
Referenced by test_inherit().
test_inherit()
dill.tests.test_classdef.test_inherit ()
Definition at line 279 of file test_classdef.py.
def test_inherit(): #NOTE: see issue #612
    class Foo:
        w = 0
        x = 1
        y = 1.1
        a = ()
        b = (1,)
        n = None
    class Bar(Foo):
        w = 2
        x = 1
        y = 1.1
        z = 0.2
        a = ()
        b = (1,)
        c = (2,)
        n = None
    Baz = dill.copy(Bar)
    import platform
    is_pypy = platform.python_implementation() == 'PyPy'
    assert Bar.__dict__ == Baz.__dict__
    # ints
    assert 'w' in Bar.__dict__ and 'w' in Baz.__dict__
    assert Bar.__dict__['w'] is Baz.__dict__['w']
    assert 'x' in Bar.__dict__ and 'x' in Baz.__dict__
    assert Bar.__dict__['x'] is Baz.__dict__['x']
    # floats
    assert 'y' in Bar.__dict__ and 'y' in Baz.__dict__
    same = Bar.__dict__['y'] is Baz.__dict__['y']
    assert same if is_pypy else not same
    assert 'z' in Bar.__dict__ and 'z' in Baz.__dict__
    same = Bar.__dict__['z'] is Baz.__dict__['z']
    assert same if is_pypy else not same
    # tuples
    assert 'a' in Bar.__dict__ and 'a' in Baz.__dict__
    assert Bar.__dict__['a'] is Baz.__dict__['a']
    assert 'b' in Bar.__dict__ and 'b' in Baz.__dict__
    assert Bar.__dict__['b'] is not Baz.__dict__['b']
    assert 'c' in Bar.__dict__ and 'c' in Baz.__dict__
    assert Bar.__dict__['c'] is not Baz.__dict__['c']
    # None
    assert 'n' in Bar.__dict__ and 'n' in Baz.__dict__
    assert Bar.__dict__['n'] is Baz.__dict__['n']
References test_array_nested(), test_array_subclass(), test_class_instances(), test_class_objects(), test_dtype(), test_enummeta(), test_inherit(), test_metaclass(), test_method_decorator(), test_namedtuple(), test_origbases(), test_slots(), and test_specialtypes().
Referenced by test_inherit().
test_metaclass()
dill.tests.test_classdef.test_metaclass ()
Definition at line 254 of file test_classdef.py.
def test_metaclass():
    class metaclass_with_new(type):
        def __new__(mcls, name, bases, ns, **kwds):
            cls = super().__new__(mcls, name, bases, ns, **kwds)
            assert mcls is not None
            assert cls.method(mcls)
            return cls
        def method(cls, mcls):
            return isinstance(cls, mcls)
    l = locals()
    exec("""class subclass_with_new(metaclass=metaclass_with_new):
        def __new__(cls):
            self = super().__new__(cls)
            return self""", None, l)
    subclass_with_new = l['subclass_with_new']
    assert dill.copy(subclass_with_new())
Referenced by test_inherit().
test_method_decorator()
dill.tests.test_classdef.test_method_decorator ()
Definition at line 209 of file test_classdef.py.
def test_method_decorator():
    class A(object):
      @classmethod
      def test(cls):
        pass
    a = A()
    res = dill.dumps(a)
    new_obj = dill.loads(res)
    new_obj.__class__.test()
# test slots
Referenced by test_inherit().
test_namedtuple()
dill.tests.test_classdef.test_namedtuple ()
Definition at line 116 of file test_classdef.py.
def test_namedtuple():
    assert Z is dill.loads(dill.dumps(Z))
    assert Zi == dill.loads(dill.dumps(Zi))
    assert X is dill.loads(dill.dumps(X))
    assert Xi == dill.loads(dill.dumps(Xi))
    assert Defaults is dill.loads(dill.dumps(Defaults))
    assert Defaultsi == dill.loads(dill.dumps(Defaultsi))
    assert Bad is not dill.loads(dill.dumps(Bad))
    assert Bad._fields == dill.loads(dill.dumps(Bad))._fields
    assert tuple(Badi) == tuple(dill.loads(dill.dumps(Badi)))
    class A:
        class B(namedtuple("C", ["one", "two"])):
            '''docstring'''
        B.__module__ = 'testing'
    a = A()
    assert dill.copy(a)
    assert dill.copy(A.B).__name__ == 'B'
    assert dill.copy(A.B).__qualname__.endswith('.<locals>.A.B')
    assert dill.copy(A.B).__doc__ == 'docstring'
    assert dill.copy(A.B).__module__ == 'testing'
    from typing import NamedTuple
    def A():
        class B(NamedTuple):
            x: int
        return B
    assert type(dill.copy(A()(8))).__qualname__ == type(A()(8)).__qualname__
Referenced by test_inherit().
test_origbases()
dill.tests.test_classdef.test_origbases ()
Definition at line 242 of file test_classdef.py.
def test_origbases():
    assert dill.copy(customIntList).__orig_bases__ == customIntList.__orig_bases__
Referenced by test_inherit().
test_slots()
dill.tests.test_classdef.test_slots ()
Definition at line 235 of file test_classdef.py.
def test_slots():
    assert dill.pickles(Y)
    assert dill.pickles(y)
    assert dill.pickles(Y.y)
    assert dill.copy(y).y == value
    assert dill.copy(Y2(value)).y == value
Referenced by test_inherit().
test_specialtypes()
dill.tests.test_classdef.test_specialtypes ()
Definition at line 97 of file test_classdef.py.
def test_specialtypes():
    assert dill.pickles(type(None))
    assert dill.pickles(type(NotImplemented))
    assert dill.pickles(type(Ellipsis))
    assert dill.pickles(type(EnumMeta))
Referenced by test_inherit().
Variable Documentation
_mclass
dill.tests.test_classdef._mclass = _meta("_mclass", (object,), {"__call__": __call__, "ok": ok}) protected
Definition at line 47 of file test_classdef.py.
Bad
dill.tests.test_classdef.Bad = namedtuple("FakeName", ['a','b'])
Definition at line 110 of file test_classdef.py.
Badi
dill.tests.test_classdef.Badi = Bad(0,1)
Definition at line 111 of file test_classdef.py.
color
dill.tests.test_classdef.color = obj.color
Definition at line 183 of file test_classdef.py.
Defaults
dill.tests.test_classdef.Defaults = namedtuple('Defaults', ['x', 'y'], defaults=[1])
Definition at line 112 of file test_classdef.py.
Defaultsi
dill.tests.test_classdef.Defaultsi = Defaults(2)
Definition at line 113 of file test_classdef.py.
m
dill.tests.test_classdef.m = _mclass()
Definition at line 56 of file test_classdef.py.
n
dill.tests.test_classdef.n = _newclass()
Definition at line 54 of file test_classdef.py.
nc
dill.tests.test_classdef.nc = _newclass2()
Definition at line 55 of file test_classdef.py.
o
dill.tests.test_classdef.o = _class()
Definition at line 52 of file test_classdef.py.
oc
dill.tests.test_classdef.oc = _class2()
Definition at line 53 of file test_classdef.py.
value
int dill.tests.test_classdef.value = 123
Definition at line 227 of file test_classdef.py.
X
dill.tests.test_classdef.X = namedtuple("Y", ['a','b'])
Definition at line 106 of file test_classdef.py.
Xi
dill.tests.test_classdef.Xi = X(0,1)
Definition at line 109 of file test_classdef.py.
y
dill.tests.test_classdef.y = Y(value)
Definition at line 228 of file test_classdef.py.
Z
dill.tests.test_classdef.Z = namedtuple("Z", ['a','b'])
Definition at line 104 of file test_classdef.py.
Zi
dill.tests.test_classdef.Zi = Z(0,1)
Definition at line 105 of file test_classdef.py.