Read&Watch: sqlparse Namespace Reference
sqlparse Namespace Reference
Namespaces
namespace __main__
namespace cli
namespace engine
namespace exceptions
namespace filters
namespace formatter
namespace keywords
namespace lexer
namespace sql
namespace tokens
namespace utils
Functions
parse (sql, encoding=None)
parsestream (stream, encoding=None)
format (sql, encoding=None, **options)
split (sql, encoding=None, strip_semicolon=False)
Detailed Description
Parse SQL statements.
Function Documentation
format()
sqlparse.format (sql, encoding = None, ** options)
Format *sql* according to *options*.
Available options are documented in :ref:`formatting`.
In addition to the formatting options this function accepts the
keyword "encoding" which determines the encoding of the statement.
:returns: The formatted SQL statement as string.
Definition at line 45 of file __init__.py.
def format(sql, encoding=None, **options):
    """Format *sql* according to *options*.
    Available options are documented in :ref:`formatting`.
    In addition to the formatting options this function accepts the
    keyword "encoding" which determines the encoding of the statement.
    :returns: The formatted SQL statement as string.
    """
    stack = engine.FilterStack()
    options = formatter.validate_options(options)
    stack = formatter.build_filter_stack(stack, options)
    stack.postprocess.append(filters.SerializerUnicode())
    return ''.join(stack.run(sql, encoding))
Referenced by sqlparse.sql.Token.__repr__(), sqlparse.cli._error(), sqlparse.sql.TokenList._pprint_tree(), sqlparse.filters.aligned_indent.AlignedIndentFilter._process(), sqlparse.filters.reindent.ReindentFilter._process(), sqlparse.filters.right_margin.RightMarginFilter._process(), sqlparse.filters.others.StripWhitespaceFilter._stripws(), sqlparse.cli.create_parser(), sqlparse.cli.main(), django.db.backends.base.operations.BaseDatabaseOperations.prepare_sql_script(), and sqlparse.filters.output.OutputFilter.process().
parse()
sqlparse.parse (sql, encoding = None)
Parse sql and return a list of statements.
:param sql: A string containing one or more SQL statements.
:param encoding: The encoding of the statement (optional).
:returns: A tuple of :class:`~sqlparse.sql.Statement` instances.
Definition at line 23 of file __init__.py.
def parse(sql, encoding=None):
    """Parse sql and return a list of statements.
    :param sql: A string containing one or more SQL statements.
    :param encoding: The encoding of the statement (optional).
    :returns: A tuple of :class:`~sqlparse.sql.Statement` instances.
    """
    return tuple(parsestream(sql, encoding))
References parsestream().
Referenced by django.db.backends.sqlite3.introspection.DatabaseIntrospection._get_column_collations(), django.db.backends.sqlite3.introspection.DatabaseIntrospection._get_index_columns_orders(), django.db.backends.mysql.introspection.DatabaseIntrospection._parse_constraint_columns(), and django.db.backends.sqlite3.introspection.DatabaseIntrospection._parse_table_constraints().
parsestream()
sqlparse.parsestream (stream, encoding = None)
Parses sql statements from file-like object.
:param stream: A file-like object.
:param encoding: The encoding of the stream contents (optional).
:returns: A generator of :class:`~sqlparse.sql.Statement` instances.
Definition at line 33 of file __init__.py.
def parsestream(stream, encoding=None):
    """Parses sql statements from file-like object.
    :param stream: A file-like object.
    :param encoding: The encoding of the stream contents (optional).
    :returns: A generator of :class:`~sqlparse.sql.Statement` instances.
    """
    stack = engine.FilterStack()
    stack.enable_grouping()
    return stack.run(stream, encoding)
Referenced by parse().
split()
sqlparse.split (sql, encoding = None, strip_semicolon = False)
Split *sql* into single statements.
:param sql: A string containing one or more SQL statements.
:param encoding: The encoding of the statement (optional).
:param strip_semicolon: If True, remove trainling semicolons
    (default: False).
:returns: A list of strings.
Definition at line 62 of file __init__.py.
def split(sql, encoding=None, strip_semicolon=False):
    """Split *sql* into single statements.
    :param sql: A string containing one or more SQL statements.
    :param encoding: The encoding of the statement (optional).
    :param strip_semicolon: If True, remove trainling semicolons
        (default: False).
    :returns: A list of strings.
    """
    stack = engine.FilterStack(strip_semicolon=strip_semicolon)
    return [str(stmt).strip() for stmt in stack.run(sql, encoding)]
Referenced by sqlparse.sql.Token._get_repr_name(), and django.db.backends.base.operations.BaseDatabaseOperations.prepare_sql_script().