Read&Watch: pip._vendor.packaging.utils Namespace Reference
pip._vendor.packaging.utils Namespace Reference
Classes
class InvalidName
class InvalidSdistFilename
class InvalidWheelFilename
Functions
NormalizedName canonicalize_name (str name, *, bool validate=False)
bool is_normalized_name (str name)
str canonicalize_version (Version|str version, *, bool strip_trailing_zero=True)
tuple[NormalizedName, Version, BuildTag, frozenset[Tag]] parse_wheel_filename (str filename)
tuple[NormalizedName, Version] parse_sdist_filename (str filename)
Variables
BuildTag = Union[Tuple[()], Tuple[int, str]]
NormalizedName = NewType("NormalizedName", str)
_validate_regex
_canonicalize_regex = re.compile(r"[-_.]+")
_normalized_regex = re.compile(r"^([a-z0-9]|[a-z0-9]([a-z0-9-](?!--))*[a-z0-9])$")
_build_tag_regex = re.compile(r"(\d+)(.*)")
Function Documentation
canonicalize_name()
NormalizedName pip._vendor.packaging.utils.canonicalize_name (str name, * , bool validate = False)
Definition at line 45 of file utils.py.
def canonicalize_name(name: str, *, validate: bool = False) -> NormalizedName:
    if validate and not _validate_regex.match(name):
        raise InvalidName(f"name is invalid: {name!r}")
    # This is taken from PEP 503.
    value = _canonicalize_regex.sub("-", name).lower()
    return cast(NormalizedName, value)
Referenced by parse_sdist_filename(), and parse_wheel_filename().
canonicalize_version()
str pip._vendor.packaging.utils.canonicalize_version (Version | str version, * , bool strip_trailing_zero = True)
This is very similar to Version.__str__, but has one subtle difference
with the way it handles the release segment.
Definition at line 57 of file utils.py.
) -> str:
    """
    This is very similar to Version.__str__, but has one subtle difference
    with the way it handles the release segment.
    """
    if isinstance(version, str):
        try:
            parsed = Version(version)
        except InvalidVersion:
            # Legacy versions cannot be normalized
            return version
    else:
        parsed = version
    parts = []
    # Epoch
    if parsed.epoch != 0:
        parts.append(f"{parsed.epoch}!")
    # Release segment
    release_segment = ".".join(str(x) for x in parsed.release)
    if strip_trailing_zero:
        # NB: This strips trailing '.0's to normalize
        release_segment = re.sub(r"(\.0)+$", "", release_segment)
    parts.append(release_segment)
    # Pre-release
    if parsed.pre is not None:
        parts.append("".join(str(x) for x in parsed.pre))
    # Post-release
    if parsed.post is not None:
        parts.append(f".post{parsed.post}")
    # Development release
    if parsed.dev is not None:
        parts.append(f".dev{parsed.dev}")
    # Local version segment
    if parsed.local is not None:
        parts.append(f"+{parsed.local}")
    return "".join(parts)
is_normalized_name()
bool pip._vendor.packaging.utils.is_normalized_name (str name)
Definition at line 53 of file utils.py.
def is_normalized_name(name: str) -> bool:
    return _normalized_regex.match(name) is not None
parse_sdist_filename()
tuple[NormalizedName, Version] pip._vendor.packaging.utils.parse_sdist_filename (str filename)
Definition at line 148 of file utils.py.
def parse_sdist_filename(filename: str) -> tuple[NormalizedName, Version]:
    if filename.endswith(".tar.gz"):
        file_stem = filename[: -len(".tar.gz")]
    elif filename.endswith(".zip"):
        file_stem = filename[: -len(".zip")]
    else:
        raise InvalidSdistFilename(
            f"Invalid sdist filename (extension must be '.tar.gz' or '.zip'):"
            f" {filename}"
        )
    # We are requiring a PEP 440 version, which cannot contain dashes,
    # so we split on the last dash.
    name_part, sep, version_part = file_stem.rpartition("-")
    if not sep:
        raise InvalidSdistFilename(f"Invalid sdist filename: {filename}")
    name = canonicalize_name(name_part)
    try:
        version = Version(version_part)
    except InvalidVersion as e:
        raise InvalidSdistFilename(
            f"Invalid sdist filename (invalid version): {filename}"
        ) from e
    return (name, version)
References canonicalize_name().
parse_wheel_filename()
tuple[NormalizedName, Version, BuildTag, frozenset[Tag]] pip._vendor.packaging.utils.parse_wheel_filename (str filename)
Definition at line 105 of file utils.py.
) -> tuple[NormalizedName, Version, BuildTag, frozenset[Tag]]:
    if not filename.endswith(".whl"):
        raise InvalidWheelFilename(
            f"Invalid wheel filename (extension must be '.whl'): {filename}"
        )
    filename = filename[:-4]
    dashes = filename.count("-")
    if dashes not in (4, 5):
        raise InvalidWheelFilename(
            f"Invalid wheel filename (wrong number of parts): {filename}"
        )
    parts = filename.split("-", dashes - 2)
    name_part = parts[0]
    # See PEP 427 for the rules on escaping the project name.
    if "__" in name_part or re.match(r"^[\w\d._]*$", name_part, re.UNICODE) is None:
        raise InvalidWheelFilename(f"Invalid project name: {filename}")
    name = canonicalize_name(name_part)
    try:
        version = Version(parts[1])
    except InvalidVersion as e:
        raise InvalidWheelFilename(
            f"Invalid wheel filename (invalid version): {filename}"
        ) from e
    if dashes == 5:
        build_part = parts[2]
        build_match = _build_tag_regex.match(build_part)
        if build_match is None:
            raise InvalidWheelFilename(
                f"Invalid build number: {build_part} in '{filename}'"
            )
        build = cast(BuildTag, (int(build_match.group(1)), build_match.group(2)))
    else:
        build = ()
    tags = parse_tag(parts[-1])
    return (name, version, build, tags)
References canonicalize_name().
Variable Documentation
_build_tag_regex
pip._vendor.packaging.utils._build_tag_regex = re.compile(r"(\d+)(.*)") protected
Definition at line 42 of file utils.py.
_canonicalize_regex
pip._vendor.packaging.utils._canonicalize_regex = re.compile(r"[-_.]+") protected
Definition at line 39 of file utils.py.
_normalized_regex
pip._vendor.packaging.utils._normalized_regex = re.compile(r"^([a-z0-9]|[a-z0-9]([a-z0-9-](?!--))*[a-z0-9])$") protected
Definition at line 40 of file utils.py.
_validate_regex
pip._vendor.packaging.utils._validate_regex protected
Initial value:
=  re.compile(
    r"^([A-Z0-9]|[A-Z0-9][A-Z0-9._-]*[A-Z0-9])$", re.IGNORECASE
)
Definition at line 36 of file utils.py.
BuildTag
pip._vendor.packaging.utils.BuildTag = Union[Tuple[()], Tuple[int, str]]
Definition at line 13 of file utils.py.
NormalizedName
pip._vendor.packaging.utils.NormalizedName = NewType("NormalizedName", str)
Definition at line 14 of file utils.py.