Read&Watch: django.db.models.base Namespace Reference
django.db.models.base Namespace Reference
Classes
class Deferred
class Model
class ModelBase
class ModelState
class ModelStateFieldsCacheDescriptor
Functions
subclass_exception (name, bases, module, attached_to)
_has_contribute_to_class (value)
method_set_order (self, ordered_obj, id_list, using=None)
method_get_order (self, ordered_obj)
make_foreign_order_accessors (model, related_model)
model_unpickle (model_id)
MISC #.
Variables
DEFERRED = Deferred()
Function Documentation
_has_contribute_to_class()
django.db.models.base._has_contribute_to_class (value) protected
Definition at line 87 of file base.py.
def _has_contribute_to_class(value):
    # Only call contribute_to_class() if it's bound.
    return not inspect.isclass(value) and hasattr(value, "contribute_to_class")
Referenced by django.db.models.base.ModelBase.__new__(), and django.db.models.base.ModelBase.add_to_class().
make_foreign_order_accessors()
django.db.models.base.make_foreign_order_accessors (model, related_model)
Definition at line 2455 of file base.py.
def make_foreign_order_accessors(model, related_model):
    setattr(
        related_model,
        "get_%s_order" % model.__name__.lower(),
        partialmethod(method_get_order, model),
    )
    setattr(
        related_model,
        "set_%s_order" % model.__name__.lower(),
        partialmethod(method_set_order, model),
    )
method_get_order()
django.db.models.base.method_get_order (self, ordered_obj)
Definition at line 2448 of file base.py.
def method_get_order(self, ordered_obj):
    order_wrt = ordered_obj._meta.order_with_respect_to
    filter_args = order_wrt.get_forward_related_filter(self)
    pk_name = ordered_obj._meta.pk.name
    return ordered_obj.objects.filter(**filter_args).values_list(pk_name, flat=True)
method_set_order()
django.db.models.base.method_set_order (self, ordered_obj, id_list, using = None)
Definition at line 2439 of file base.py.
def method_set_order(self, ordered_obj, id_list, using=None):
    order_wrt = ordered_obj._meta.order_with_respect_to
    filter_args = order_wrt.get_forward_related_filter(self)
    ordered_obj.objects.db_manager(using).filter(**filter_args).bulk_update(
        [ordered_obj(pk=pk, _order=order) for order, pk in enumerate(id_list)],
        ["_order"],
    )
model_unpickle()
django.db.models.base.model_unpickle (model_id)
MISC #.
Used to unpickle Model subclasses with deferred fields.
Definition at line 2473 of file base.py.
def model_unpickle(model_id):
    """Used to unpickle Model subclasses with deferred fields."""
    if isinstance(model_id, tuple):
        model = apps.get_model(*model_id)
    else:
        # Backwards compat - the model was cached directly in earlier versions.
        model = model_id
    return model.__new__(model)
subclass_exception()
django.db.models.base.subclass_exception (name, bases, module, attached_to)
Create exception subclass. Used by ModelBase below.
The exception is created in a way that allows it to be pickled, assuming
that the returned exception class will be added as an attribute to the
'attached_to' class.
Definition at line 69 of file base.py.
def subclass_exception(name, bases, module, attached_to):
    """
    Create exception subclass. Used by ModelBase below.
    The exception is created in a way that allows it to be pickled, assuming
    that the returned exception class will be added as an attribute to the
    'attached_to' class.
    """
    return type(
        name,
        bases,
        {
            "__module__": module,
            "__qualname__": "%s.%s" % (attached_to.__qualname__, name),
        },
    )
Referenced by django.db.models.base.ModelBase.__new__().
Variable Documentation
DEFERRED
django.db.models.base.DEFERRED = Deferred()
Definition at line 66 of file base.py.