Read&Watch: django.http.request Namespace Reference
django.http.request Namespace Reference
Classes
class HttpHeaders
class HttpRequest
class MediaType
class QueryDict
class RawPostDataException
class UnreadablePostError
Functions
bytes_to_text (s, encoding)
split_domain_port (host)
validate_host (host, allowed_hosts)
parse_accept_header (header)
Variables
RAISE_ERROR = object()
host_validation_re
Function Documentation
bytes_to_text()
django.http.request.bytes_to_text (s, encoding)
Convert bytes objects to strings, using the given encoding. Illegally
encoded input characters are replaced with Unicode "unknown" codepoint
(\ufffd).
Return any non-bytes objects without change.
Definition at line 689 of file request.py.
def bytes_to_text(s, encoding):
    """
    Convert bytes objects to strings, using the given encoding. Illegally
    encoded input characters are replaced with Unicode "unknown" codepoint
    (\ufffd).
    Return any non-bytes objects without change.
    """
    if isinstance(s, bytes):
        return str(s, encoding, "replace")
    else:
        return s
Referenced by django.http.request.QueryDict.__setitem__(), django.http.request.QueryDict.appendlist(), django.http.request.QueryDict.setdefault(), and django.http.request.QueryDict.setlist().
parse_accept_header()
django.http.request.parse_accept_header (header)
Definition at line 737 of file request.py.
def parse_accept_header(header):
    return [MediaType(token) for token in header.split(",") if token.strip()]
Referenced by django.http.request.HttpRequest.accepted_types().
split_domain_port()
django.http.request.split_domain_port (host)
Return a (domain, port) tuple from a given host.
Returned domain is lowercased. If the host is invalid, the domain will be
empty.
Definition at line 703 of file request.py.
def split_domain_port(host):
    """
    Return a (domain, port) tuple from a given host.
    Returned domain is lowercased. If the host is invalid, the domain will be
    empty.
    """
    if match := host_validation_re.fullmatch(host.lower()):
        domain, port = match.groups(default="")
        # Remove a trailing dot (if present) from the domain.
        return domain.removesuffix("."), port
    return "", ""
Referenced by django.http.request.HttpRequest.get_host().
validate_host()
django.http.request.validate_host (host, allowed_hosts)
Validate the given host for this site.
Check that the host looks valid and matches a host or host pattern in the
given list of ``allowed_hosts``. Any pattern beginning with a period
matches a domain and all its subdomains (e.g. ``.example.com`` matches
``example.com`` and any subdomain), ``*`` matches anything, and anything
else must match exactly.
Note: This function assumes that the given host is lowercased and has
already had the port, if any, stripped off.
Return ``True`` for a valid host, ``False`` otherwise.
Definition at line 717 of file request.py.
def validate_host(host, allowed_hosts):
    """
    Validate the given host for this site.
    Check that the host looks valid and matches a host or host pattern in the
    given list of ``allowed_hosts``. Any pattern beginning with a period
    matches a domain and all its subdomains (e.g. ``.example.com`` matches
    ``example.com`` and any subdomain), ``*`` matches anything, and anything
    else must match exactly.
    Note: This function assumes that the given host is lowercased and has
    already had the port, if any, stripped off.
    Return ``True`` for a valid host, ``False`` otherwise.
    """
    return any(
        pattern == "*" or is_same_domain(host, pattern) for pattern in allowed_hosts
    )
Referenced by django.http.request.HttpRequest.get_host().
Variable Documentation
host_validation_re
django.http.request.host_validation_re
Initial value:
=  _lazy_re_compile(
    r"^([a-z0-9.-]+|\[[a-f0-9]*:[a-f0-9.:]+\])(?::([0-9]+))?$"
)
Definition at line 33 of file request.py.
RAISE_ERROR
django.http.request.RAISE_ERROR = object()
Definition at line 32 of file request.py.