Read&Watch: pylint.pyreverse.utils Namespace Reference
pylint.pyreverse.utils Namespace Reference
Classes
class FilterMixIn
class LocalsVisitor
Functions
list[str] get_default_options ()
None insert_default_options ()
str get_visibility (str name)
bool is_exception (nodes.ClassDef node)
str get_annotation_label (nodes.Name|nodes.NodeNG ann)
nodes.Name|nodes.Subscript|None get_annotation (nodes.AssignAttr|nodes.AssignName node)
set[InferenceResult] infer_node (nodes.AssignAttr|nodes.AssignName node)
None check_graphviz_availability ()
None check_if_graphviz_supports_format (str output_format)
Variables
_CallbackT
_CallbackTupleT = tuple[Optional[_CallbackT], Optional[_CallbackT]]
str RCFILE = ".pyreverserc"
SPECIAL = re.compile(r"^__([^\W_]_*)+__$")
PRIVATE = re.compile(r"^__(_*[^\W_])+_?$")
PROTECTED = re.compile(r"^_\w*$")
int _SPECIAL = 2
int _PROTECTED = 4
int _PRIVATE = 8
dict MODES
dict VIS_MOD
Detailed Description
Generic classes/functions for pyreverse core/extensions.
Function Documentation
check_graphviz_availability()
None pylint.pyreverse.utils.check_graphviz_availability ()
Check if the ``dot`` command is available on the machine.
This is needed if image output is desired and ``dot`` is used to convert
from *.dot or *.gv into the final output format.
Definition at line 235 of file utils.py.
def check_graphviz_availability() -> None:
    """Check if the ``dot`` command is available on the machine.
    This is needed if image output is desired and ``dot`` is used to convert
    from *.dot or *.gv into the final output format.
    """
    if shutil.which("dot") is None:
        print("'Graphviz' needs to be installed for your chosen output format.")
        sys.exit(32)
check_if_graphviz_supports_format()
None pylint.pyreverse.utils.check_if_graphviz_supports_format (str output_format)
Check if the ``dot`` command supports the requested output format.
This is needed if image output is desired and ``dot`` is used to convert
from *.gv into the final output format.
Definition at line 246 of file utils.py.
def check_if_graphviz_supports_format(output_format: str) -> None:
    """Check if the ``dot`` command supports the requested output format.
    This is needed if image output is desired and ``dot`` is used to convert
    from *.gv into the final output format.
    """
    dot_output = subprocess.run(
        ["dot", "-T?"], capture_output=True, check=False, encoding="utf-8"
    )
    match = re.match(
        pattern=r".*Use one of: (?P<formats>(\S*\s?)+)",
        string=dot_output.stderr.strip(),
    )
    if not match:
        print(
            "Unable to determine Graphviz supported output formats. "
            "Pyreverse will continue, but subsequent error messages "
            "regarding the output format may come from Graphviz directly."
        )
        return
    supported_formats = match.group("formats")
    if output_format not in supported_formats.split():
        print(
            f"Format {output_format} is not supported by Graphviz. It supports: {supported_formats}"
        )
        sys.exit(32)
get_annotation()
nodes.Name | nodes.Subscript | None pylint.pyreverse.utils.get_annotation (nodes.AssignAttr | nodes.AssignName node)
Return the annotation for `node`.
Definition at line 175 of file utils.py.
) -> nodes.Name | nodes.Subscript | None:
    """Return the annotation for `node`."""
    ann = None
    if isinstance(node.parent, nodes.AnnAssign):
        ann = node.parent.annotation
    elif isinstance(node, nodes.AssignAttr):
        init_method = node.parent.parent
        try:
            annotations = dict(zip(init_method.locals, init_method.args.annotations))
            ann = annotations.get(node.parent.value.name)
        except AttributeError:
            pass
    else:
        return ann
    try:
        default, *_ = node.infer()
    except astroid.InferenceError:
        default = ""
    label = get_annotation_label(ann)
    if (
        ann
        and getattr(default, "value", "value") is None
        and not label.startswith("Optional")
        and (
            not isinstance(ann, nodes.BinOp)
            or not any(
                isinstance(child, nodes.Const) and child.value is None
                for child in ann.get_children()
            )
        )
    ):
        label = rf"Optional[{label}]"
    if label and ann:
        ann.name = label
    return ann
References get_annotation_label().
Referenced by infer_node().
get_annotation_label()
str pylint.pyreverse.utils.get_annotation_label (nodes.Name | nodes.NodeNG ann)
Definition at line 167 of file utils.py.
def get_annotation_label(ann: nodes.Name | nodes.NodeNG) -> str:
    if isinstance(ann, nodes.Name) and ann.name is not None:
        return ann.name  # type: ignore[no-any-return]
    if isinstance(ann, nodes.NodeNG):
        return ann.as_string()  # type: ignore[no-any-return]
    return ""
Referenced by get_annotation().
get_default_options()
list[str] pylint.pyreverse.utils.get_default_options ()
Read config file and return list of options.
Definition at line 34 of file utils.py.
def get_default_options() -> list[str]:
    """Read config file and return list of options."""
    options = []
    home = os.environ.get("HOME", "")
    if home:
        rcfile = os.path.join(home, RCFILE)
        try:
            with open(rcfile, encoding="utf-8") as file_handle:
                options = file_handle.read().split()
        except OSError:
            pass  # ignore if no config file found
    return options
Referenced by insert_default_options().
get_visibility()
str pylint.pyreverse.utils.get_visibility (str name)
Return the visibility from a name: public, protected, private or special.
Definition at line 62 of file utils.py.
def get_visibility(name: str) -> str:
    """Return the visibility from a name: public, protected, private or special."""
    if SPECIAL.match(name):
        visibility = "special"
    elif PRIVATE.match(name):
        visibility = "private"
    elif PROTECTED.match(name):
        visibility = "protected"
    else:
        visibility = "public"
    return visibility
Referenced by pylint.pyreverse.utils.FilterMixIn.show_attr().
infer_node()
set[InferenceResult] pylint.pyreverse.utils.infer_node (nodes.AssignAttr | nodes.AssignName node)
Return a set containing the node annotation if it exists
otherwise return a set of the inferred types using the NodeNG.infer method.
Definition at line 218 of file utils.py.
def infer_node(node: nodes.AssignAttr | nodes.AssignName) -> set[InferenceResult]:
    """Return a set containing the node annotation if it exists
    otherwise return a set of the inferred types using the NodeNG.infer method.
    """
    ann = get_annotation(node)
    try:
        if ann:
            if isinstance(ann, nodes.Subscript) or (
                isinstance(ann, nodes.BinOp) and ann.op == "|"
            ):
                return {ann}
            return set(ann.infer())
        return set(node.infer())
    except astroid.InferenceError:
        return {ann} if ann else set()
References get_annotation().
insert_default_options()
None pylint.pyreverse.utils.insert_default_options ()
Insert default options to sys.argv.
Definition at line 48 of file utils.py.
def insert_default_options() -> None:
    """Insert default options to sys.argv."""
    options = get_default_options()
    options.reverse()
    for arg in options:
        sys.argv.insert(1, arg)
# astroid utilities ###########################################################
References get_default_options().
is_exception()
bool pylint.pyreverse.utils.is_exception (nodes.ClassDef node)
Definition at line 76 of file utils.py.
def is_exception(node: nodes.ClassDef) -> bool:
    # bw compatibility
    return node.type == "exception"  # type: ignore[no-any-return]
# Helpers #####################################################################
Variable Documentation
_CallbackT
pylint.pyreverse.utils._CallbackT protected
Initial value:
=  Callable[
        [nodes.NodeNG],
        Union[tuple[ClassDiagram], tuple[PackageDiagram, ClassDiagram], None],
    ]
Definition at line 24 of file utils.py.
_CallbackTupleT
pylint.pyreverse.utils.LocalsVisitor._CallbackTupleT = tuple[Optional[_CallbackT], Optional[_CallbackT]] protected
Definition at line 28 of file utils.py.
_PRIVATE
int pylint.pyreverse.utils._PRIVATE = 8 protected
Definition at line 85 of file utils.py.
_PROTECTED
int pylint.pyreverse.utils._PROTECTED = 4 protected
Definition at line 84 of file utils.py.
_SPECIAL
int pylint.pyreverse.utils._SPECIAL = 2 protected
Definition at line 83 of file utils.py.
MODES
dict pylint.pyreverse.utils.MODES
Initial value:
=  {
    "ALL": 0,
    "PUB_ONLY": _SPECIAL + _PROTECTED + _PRIVATE,
    "SPECIAL": _SPECIAL,
    "OTHER": _PROTECTED + _PRIVATE,
}
Definition at line 86 of file utils.py.
PRIVATE
pylint.pyreverse.utils.PRIVATE = re.compile(r"^__(_*[^\W_])+_?$")
Definition at line 58 of file utils.py.
PROTECTED
pylint.pyreverse.utils.PROTECTED = re.compile(r"^_\w*$")
Definition at line 59 of file utils.py.
RCFILE
str pylint.pyreverse.utils.RCFILE = ".pyreverserc"
Definition at line 31 of file utils.py.
SPECIAL
pylint.pyreverse.utils.SPECIAL = re.compile(r"^__([^\W_]_*)+__$")
Definition at line 57 of file utils.py.
VIS_MOD
dict pylint.pyreverse.utils.VIS_MOD
Initial value:
=  {
    "special": _SPECIAL,
    "protected": _PROTECTED,
    "private": _PRIVATE,
    "public": 0,
}
Definition at line 92 of file utils.py.