Read&Watch: PIL.ImageShow Namespace Reference
PIL.ImageShow Namespace Reference
Classes
class DisplayViewer
class EogViewer
class GmDisplayViewer
class IPythonViewer
class MacViewer
class UnixViewer
class Viewer
class WindowsViewer
class XDGViewer
class XVViewer
Functions
None register (type[Viewer]|Viewer viewer, int order=1)
bool show (Image.Image image, str|None title=None, **Any options)
Variables
list _viewers = []
Function Documentation
register()
None PIL.ImageShow.register (type[Viewer] | Viewer viewer, int order = 1)
The :py:func:`register` function is used to register additional viewers::
    from PIL import ImageShow
    ImageShow.register(MyViewer())  # MyViewer will be used as a last resort
    ImageShow.register(MySecondViewer(), 0)  # MySecondViewer will be prioritised
    ImageShow.register(ImageShow.XVViewer(), 0)  # XVViewer will be prioritised
:param viewer: The viewer to be registered.
:param order:
    Zero or a negative integer to prepend this viewer to the list,
    a positive integer to append it.
Definition at line 29 of file ImageShow.py.
def register(viewer: type[Viewer] | Viewer, order: int = 1) -> None:
    """
    The :py:func:`register` function is used to register additional viewers::
        from PIL import ImageShow
        ImageShow.register(MyViewer())  # MyViewer will be used as a last resort
        ImageShow.register(MySecondViewer(), 0)  # MySecondViewer will be prioritised
        ImageShow.register(ImageShow.XVViewer(), 0)  # XVViewer will be prioritised
    :param viewer: The viewer to be registered.
    :param order:
        Zero or a negative integer to prepend this viewer to the list,
        a positive integer to append it.
    """
    if isinstance(viewer, type) and issubclass(viewer, Viewer):
        viewer = viewer()
    if order > 0:
        _viewers.append(viewer)
    else:
        _viewers.insert(0, viewer)
Referenced by PIL.ImageShow.MacViewer.show_file(), PIL.ImageShow.WindowsViewer.show_file(), PIL.ImageShow.XVViewer.show_file(), and PIL.ImageShow.IPythonViewer.show_image().
show()
bool PIL.ImageShow.show (Image.Image image, str | None title = None, **Any options)
Display a given image.
:param image: An image object.
:param title: Optional title. Not all viewers can display the title.
:param \**options: Additional viewer options.
:returns: ``True`` if a suitable viewer was found, ``False`` otherwise.
Definition at line 51 of file ImageShow.py.
def show(image: Image.Image, title: str | None = None, **options: Any) -> bool:
    r"""
    Display a given image.
    :param image: An image object.
    :param title: Optional title. Not all viewers can display the title.
    :param \**options: Additional viewer options.
    :returns: ``True`` if a suitable viewer was found, ``False`` otherwise.
    """
    for viewer in _viewers:
        if viewer.show(image, title=title, **options):
            return True
    return False
Variable Documentation
_viewers
list PIL.ImageShow._viewers = [] protected
Definition at line 26 of file ImageShow.py.