Read&Watch: isort.place Namespace Reference
isort.place Namespace Reference
Functions
str module (str name, Config config=DEFAULT_CONFIG)
Tuple[str, str] module_with_reason (str name, Config config=DEFAULT_CONFIG)
Optional[Tuple[str, str]] _forced_separate (str name, Config config)
Optional[Tuple[str, str]] _local (str name, Config config)
Optional[Tuple[str, str]] _known_pattern (str name, Config config)
Optional[Tuple[str, str]] _src_path (str name, Config config, Optional[Iterable[Path]] src_paths=None, Tuple[str,...] prefix=())
bool _is_module (Path path)
bool _is_package (Path path)
bool _is_namespace_package (Path path, FrozenSet[str] src_extensions)
bool _src_path_is_module (Path src_path, str module_name)
Variables
str LOCAL = "LOCALFOLDER"
Detailed Description
Contains all logic related to placing an import within a certain section.
Function Documentation
_forced_separate()
Optional[Tuple[str, str]] isort.place._forced_separate (str name, Config config) protected
Definition at line 33 of file place.py.
def _forced_separate(name: str, config: Config) -> Optional[Tuple[str, str]]:
    for forced_separate in config.forced_separate:
        # Ensure all forced_separate patterns will match to end of string
        path_glob = forced_separate
        if not forced_separate.endswith("*"):
            path_glob = f"{forced_separate}*"
        if fnmatch(name, path_glob) or fnmatch(name, "." + path_glob):
            return (forced_separate, f"Matched forced_separate ({forced_separate}) config value.")
    return None
Referenced by module_with_reason().
_is_module()
bool isort.place._is_module (Path path) protected
Definition at line 99 of file place.py.
def _is_module(path: Path) -> bool:
    return (
        exists_case_sensitive(str(path.with_suffix(".py")))
        or any(
            exists_case_sensitive(str(path.with_suffix(ext_suffix)))
            for ext_suffix in importlib.machinery.EXTENSION_SUFFIXES
        )
        or exists_case_sensitive(str(path / "__init__.py"))
    )
Referenced by _src_path().
_is_namespace_package()
bool isort.place._is_namespace_package (Path path, FrozenSet[str] src_extensions) protected
Definition at line 114 of file place.py.
def _is_namespace_package(path: Path, src_extensions: FrozenSet[str]) -> bool:
    if not _is_package(path):
        return False
    init_file = path / "__init__.py"
    if not init_file.exists():
        filenames = [
            filepath
            for filepath in path.iterdir()
            if filepath.suffix.lstrip(".") in src_extensions
            or filepath.name.lower() in ("setup.cfg", "pyproject.toml")
        ]
        if filenames:
            return False
    else:
        with init_file.open("rb") as open_init_file:
            file_start = open_init_file.read(4096)
            if (
                b"__import__('pkg_resources').declare_namespace(__name__)" not in file_start
                and b'__import__("pkg_resources").declare_namespace(__name__)' not in file_start
                and b"__path__ = __import__('pkgutil').extend_path(__path__, __name__)"
                not in file_start
                and b'__path__ = __import__("pkgutil").extend_path(__path__, __name__)'
                not in file_start
            ):
                return False
    return True
References _is_package().
Referenced by _src_path().
_is_package()
bool isort.place._is_package (Path path) protected
Definition at line 110 of file place.py.
def _is_package(path: Path) -> bool:
    return exists_case_sensitive(str(path)) and path.is_dir()
Referenced by _is_namespace_package(), and _src_path().
_known_pattern()
Optional[Tuple[str, str]] isort.place._known_pattern (str name, Config config) protected
Definition at line 53 of file place.py.
def _known_pattern(name: str, config: Config) -> Optional[Tuple[str, str]]:
    parts = name.split(".")
    module_names_to_check = (".".join(parts[:first_k]) for first_k in range(len(parts), 0, -1))
    for module_name_to_check in module_names_to_check:
        for pattern, placement in config.known_patterns:
            if placement in config.sections and pattern.match(module_name_to_check):
                return (placement, f"Matched configured known pattern {pattern}")
    return None
Referenced by module_with_reason().
_local()
Optional[Tuple[str, str]] isort.place._local (str name, Config config) protected
Definition at line 46 of file place.py.
def _local(name: str, config: Config) -> Optional[Tuple[str, str]]:
    if name.startswith("."):
        return (LOCAL, "Module name started with a dot.")
    return None
Referenced by module_with_reason().
_src_path()
Optional[Tuple[str, str]] isort.place._src_path (str name, Config config, Optional[Iterable[Path]] src_paths = None, Tuple[str, ...] prefix = ()) protected
Definition at line 64 of file place.py.
) -> Optional[Tuple[str, str]]:
    if src_paths is None:
        src_paths = config.src_paths
    root_module_name, *nested_module = name.split(".", 1)
    new_prefix = prefix + (root_module_name,)
    namespace = ".".join(new_prefix)
    for src_path in src_paths:
        module_path = (src_path / root_module_name).resolve()
        if not prefix and not module_path.is_dir() and src_path.name == root_module_name:
            module_path = src_path.resolve()
        if nested_module and (
            namespace in config.namespace_packages
            or (
                config.auto_identify_namespace_packages
                and _is_namespace_package(module_path, config.supported_extensions)
            )
        ):
            return _src_path(nested_module[0], config, (module_path,), new_prefix)
        if (
            _is_module(module_path)
            or _is_package(module_path)
            or _src_path_is_module(src_path, root_module_name)
        ):
            return (sections.FIRSTPARTY, f"Found in one of the configured src_paths: {src_path}.")
    return None
References _is_module(), _is_namespace_package(), _is_package(), _src_path(), and _src_path_is_module().
Referenced by _src_path(), and module_with_reason().
_src_path_is_module()
bool isort.place._src_path_is_module (Path src_path, str module_name) protected
Definition at line 143 of file place.py.
def _src_path_is_module(src_path: Path, module_name: str) -> bool:
    return (
        module_name == src_path.name and src_path.is_dir() and exists_case_sensitive(str(src_path))
    )
Referenced by _src_path().
module()
str isort.place.module (str name, Config config = DEFAULT_CONFIG)
Returns the section placement for the given module name.
Definition at line 16 of file place.py.
def module(name: str, config: Config = DEFAULT_CONFIG) -> str:
    """Returns the section placement for the given module name."""
    return module_with_reason(name, config)[0]
@lru_cache(maxsize=1000)
References module_with_reason().
module_with_reason()
Tuple[str, str] isort.place.module_with_reason (str name, Config config = DEFAULT_CONFIG)
Returns the section placement for the given module name alongside the reasoning.
Definition at line 22 of file place.py.
def module_with_reason(name: str, config: Config = DEFAULT_CONFIG) -> Tuple[str, str]:
    """Returns the section placement for the given module name alongside the reasoning."""
    return (
        _forced_separate(name, config)
        or _local(name, config)
        or _known_pattern(name, config)
        or _src_path(name, config)
        or (config.default_section, "Default option in Config or universal default.")
    )
References _forced_separate(), _known_pattern(), _local(), and _src_path().
Referenced by module().
Variable Documentation
LOCAL
str isort.place.LOCAL = "LOCALFOLDER"
Definition at line 13 of file place.py.