Read&Watch: pylint.checkers.refactoring.refactoring_checker Namespace Reference
pylint.checkers.refactoring.refactoring_checker Namespace Reference
Classes
class ConsiderUsingWithStack
class RefactoringChecker
Functions
bool _if_statement_is_always_returning (nodes.If if_node, nodes.NodeNG returning_node_class)
bool _except_statement_is_always_returning (nodes.Try node, nodes.NodeNG returning_node_class)
bool _is_trailing_comma (list[tokenize.TokenInfo] tokens, int index)
bool _is_inside_context_manager (nodes.Call node)
bool _is_a_return_statement (nodes.Call node)
bool _is_part_of_with_items (nodes.Call node)
bool _will_be_released_automatically (nodes.Call node)
bool _is_part_of_assignment_target (nodes.NodeNG node)
Variables
NodesWithNestedBlocks = Union[nodes.Try, nodes.While, nodes.For, nodes.If]
dict KNOWN_INFINITE_ITERATORS = {"itertools.count", "itertools.cycle"}
BUILTIN_EXIT_FUNCS = frozenset(("quit", "exit"))
CALLS_THAT_COULD_BE_REPLACED_BY_WITH
CALLS_RETURNING_CONTEXT_MANAGERS
Function Documentation
_except_statement_is_always_returning()
bool pylint.checkers.refactoring.refactoring_checker._except_statement_is_always_returning (nodes.Try node, nodes.NodeNG returning_node_class) protected
Detect if all except statements return.
Definition at line 72 of file refactoring_checker.py.
) -> bool:
    """Detect if all except statements return."""
    return all(
        any(isinstance(child, returning_node_class) for child in handler.body)
        for handler in node.handlers
    )
Referenced by pylint.checkers.refactoring.refactoring_checker.RefactoringChecker._check_superfluous_else().
_if_statement_is_always_returning()
bool pylint.checkers.refactoring.refactoring_checker._if_statement_is_always_returning (nodes.If if_node, nodes.NodeNG returning_node_class) protected
Definition at line 66 of file refactoring_checker.py.
) -> bool:
    return any(isinstance(node, returning_node_class) for node in if_node.body)
Referenced by pylint.checkers.refactoring.refactoring_checker.RefactoringChecker._check_superfluous_else().
_is_a_return_statement()
bool pylint.checkers.refactoring.refactoring_checker._is_a_return_statement (nodes.Call node) protected
Definition at line 136 of file refactoring_checker.py.
def _is_a_return_statement(node: nodes.Call) -> bool:
    frame = node.frame()
    for parent in node.node_ancestors():
        if parent is frame:
            break
        if isinstance(parent, nodes.Return):
            return True
    return False
Referenced by pylint.checkers.refactoring.refactoring_checker.RefactoringChecker._check_consider_using_with().
_is_inside_context_manager()
bool pylint.checkers.refactoring.refactoring_checker._is_inside_context_manager (nodes.Call node) protected
Definition at line 125 of file refactoring_checker.py.
def _is_inside_context_manager(node: nodes.Call) -> bool:
    frame = node.frame()
    if not isinstance(
        frame, (nodes.FunctionDef, astroid.BoundMethod, astroid.UnboundMethod)
    ):
        return False
    return frame.name == "__enter__" or utils.decorated_with(
        frame, "contextlib.contextmanager"
    )
Referenced by pylint.checkers.refactoring.refactoring_checker.RefactoringChecker._append_context_managers_to_stack(), and pylint.checkers.refactoring.refactoring_checker.RefactoringChecker._check_consider_using_with().
_is_part_of_assignment_target()
bool pylint.checkers.refactoring.refactoring_checker._is_part_of_assignment_target (nodes.NodeNG node) protected
Check whether use of a variable is happening as part of the left-hand
side of an assignment.
This requires recursive checking, because destructuring assignment can have
arbitrarily nested tuples and lists to unpack.
Definition at line 179 of file refactoring_checker.py.
def _is_part_of_assignment_target(node: nodes.NodeNG) -> bool:
    """Check whether use of a variable is happening as part of the left-hand
    side of an assignment.
    This requires recursive checking, because destructuring assignment can have
    arbitrarily nested tuples and lists to unpack.
    """
    if isinstance(node.parent, nodes.Assign):
        return node in node.parent.targets
    if isinstance(node.parent, nodes.AugAssign):
        return node == node.parent.target  # type: ignore[no-any-return]
    if isinstance(node.parent, (nodes.Tuple, nodes.List)):
        return _is_part_of_assignment_target(node.parent)
    return False
References _is_part_of_assignment_target().
Referenced by pylint.checkers.refactoring.refactoring_checker.RefactoringChecker._check_unnecessary_dict_index_lookup(), pylint.checkers.refactoring.refactoring_checker.RefactoringChecker._check_unnecessary_list_index_lookup(), and _is_part_of_assignment_target().
_is_part_of_with_items()
bool pylint.checkers.refactoring.refactoring_checker._is_part_of_with_items (nodes.Call node) protected
Checks if one of the node's parents is a ``nodes.With`` node and that the node
itself is located somewhere under its ``items``.
Definition at line 146 of file refactoring_checker.py.
def _is_part_of_with_items(node: nodes.Call) -> bool:
    """Checks if one of the node's parents is a ``nodes.With`` node and that the node
    itself is located somewhere under its ``items``.
    """
    frame = node.frame()
    current = node
    while current != frame:
        if isinstance(current, nodes.With):
            items_start = current.items[0][0].lineno
            items_end = current.items[-1][0].tolineno
            return items_start <= node.lineno <= items_end  # type: ignore[no-any-return]
        current = current.parent
    return False
Referenced by pylint.checkers.refactoring.refactoring_checker.RefactoringChecker._check_consider_using_with().
_is_trailing_comma()
bool pylint.checkers.refactoring.refactoring_checker._is_trailing_comma (list[tokenize.TokenInfo] tokens, int index) protected
Check if the given token is a trailing comma.
:param tokens: Sequence of modules tokens
:type tokens: list[tokenize.TokenInfo]
:param int index: Index of token under check in tokens
:returns: True if the token is a comma which trails an expression
:rtype: bool
Definition at line 82 of file refactoring_checker.py.
def _is_trailing_comma(tokens: list[tokenize.TokenInfo], index: int) -> bool:
    """Check if the given token is a trailing comma.
    :param tokens: Sequence of modules tokens
    :type tokens: list[tokenize.TokenInfo]
    :param int index: Index of token under check in tokens
    :returns: True if the token is a comma which trails an expression
    :rtype: bool
    """
    token = tokens[index]
    if token.exact_type != tokenize.COMMA:
        return False
    # Must have remaining tokens on the same line such as NEWLINE
    left_tokens = itertools.islice(tokens, index + 1, None)
    more_tokens_on_line = False
    for remaining_token in left_tokens:
        if remaining_token.start[0] == token.start[0]:
            more_tokens_on_line = True
            # If one of the remaining same line tokens is not NEWLINE or COMMENT
            # the comma is not trailing.
            if remaining_token.type not in (tokenize.NEWLINE, tokenize.COMMENT):
                return False
    if not more_tokens_on_line:
        return False
    def get_curline_index_start() -> int:
        """Get the index denoting the start of the current line."""
        for subindex, token in enumerate(reversed(tokens[:index])):
            # See Lib/tokenize.py and Lib/token.py in cpython for more info
            if token.type == tokenize.NEWLINE:
                return index - subindex
        return 0
    curline_start = get_curline_index_start()
    expected_tokens = {"return", "yield"}
    return any(
        "=" in prevtoken.string or prevtoken.string in expected_tokens
        for prevtoken in tokens[curline_start:index]
    )
Referenced by pylint.checkers.refactoring.refactoring_checker.RefactoringChecker.process_tokens().
_will_be_released_automatically()
bool pylint.checkers.refactoring.refactoring_checker._will_be_released_automatically (nodes.Call node) protected
Checks if a call that could be used in a ``with`` statement is used in an
alternative construct which would ensure that its __exit__ method is called.
Definition at line 161 of file refactoring_checker.py.
def _will_be_released_automatically(node: nodes.Call) -> bool:
    """Checks if a call that could be used in a ``with`` statement is used in an
    alternative construct which would ensure that its __exit__ method is called.
    """
    callables_taking_care_of_exit = frozenset(
        (
            "contextlib._BaseExitStack.enter_context",
            "contextlib.ExitStack.enter_context",  # necessary for Python 3.6 compatibility
        )
    )
    if not isinstance(node.parent, nodes.Call):
        return False
    func = utils.safe_infer(node.parent.func)
    if not func:
        return False
    return func.qname() in callables_taking_care_of_exit
Referenced by pylint.checkers.refactoring.refactoring_checker.RefactoringChecker._check_consider_using_with().
Variable Documentation
BUILTIN_EXIT_FUNCS
pylint.checkers.refactoring.refactoring_checker.BUILTIN_EXIT_FUNCS = frozenset(("quit", "exit"))
Definition at line 33 of file refactoring_checker.py.
CALLS_RETURNING_CONTEXT_MANAGERS
pylint.checkers.refactoring.refactoring_checker.CALLS_RETURNING_CONTEXT_MANAGERS
Initial value:
=  frozenset(
    (
        "_io.open",  # regular 'open()' call
        "pathlib.Path.open",
        "pathlib._local.Path.open",  # Python 3.13
        "codecs.open",
        "urllib.request.urlopen",
        "tempfile.NamedTemporaryFile",
        "tempfile.SpooledTemporaryFile",
        "tempfile.TemporaryDirectory",
        "tempfile.TemporaryFile",
        "zipfile.ZipFile",
        "zipfile.PyZipFile",
        "zipfile.ZipFile.open",
        "zipfile.PyZipFile.open",
        "tarfile.TarFile",
        "tarfile.TarFile.open",
        "multiprocessing.context.BaseContext.Pool",
        "subprocess.Popen",
    )
)
Definition at line 43 of file refactoring_checker.py.
CALLS_THAT_COULD_BE_REPLACED_BY_WITH
pylint.checkers.refactoring.refactoring_checker.CALLS_THAT_COULD_BE_REPLACED_BY_WITH
Initial value:
=  frozenset(
    (
        "threading.lock.acquire",
        "threading._RLock.acquire",
        "threading.Semaphore.acquire",
        "multiprocessing.managers.BaseManager.start",
        "multiprocessing.managers.SyncManager.start",
    )
)
Definition at line 34 of file refactoring_checker.py.
KNOWN_INFINITE_ITERATORS
dict pylint.checkers.refactoring.refactoring_checker.KNOWN_INFINITE_ITERATORS = {"itertools.count", "itertools.cycle"}
Definition at line 32 of file refactoring_checker.py.
NodesWithNestedBlocks
pylint.checkers.refactoring.refactoring_checker.NodesWithNestedBlocks = Union[nodes.Try, nodes.While, nodes.For, nodes.If]
Definition at line 30 of file refactoring_checker.py.