Read&Watch: django.db.models.fields Namespace Reference
django.db.models.fields Namespace Reference
Namespaces
namespace files
namespace generated
namespace json
namespace mixins
namespace proxy
namespace related
namespace related_descriptors
namespace related_lookups
namespace reverse_related
Classes
class AutoField
class AutoFieldMeta
class AutoFieldMixin
class BigAutoField
class BigIntegerField
class BinaryField
class BooleanField
class CharField
class CommaSeparatedIntegerField
class DateField
class DateTimeCheckMixin
class DateTimeField
class DecimalField
class DurationField
class EmailField
class Empty
class Field
class FilePathField
class FloatField
class GenericIPAddressField
class IntegerField
class IPAddressField
class NOT_PROVIDED
class NullBooleanField
class PositiveBigIntegerField
class PositiveIntegerField
class PositiveIntegerRelDbTypeMixin
class PositiveSmallIntegerField
class SlugField
class SmallAutoField
class SmallIntegerField
class TextField
class TimeField
class URLField
class UUIDField
Functions
_load_field (app_label, model_name, field_name)
_empty (of_cls)
return_None ()
_to_naive (value)
_get_naive_now ()
Variables
list BLANK_CHOICE_DASH = [("", "---------")]
Function Documentation
_empty()
django.db.models.fields._empty (of_cls) protected
Definition at line 108 of file __init__.py.
def _empty(of_cls):
    new = Empty()
    new.__class__ = of_cls
    return new
_get_naive_now()
django.db.models.fields._get_naive_now () protected
Definition at line 1340 of file __init__.py.
def _get_naive_now():
    return _to_naive(timezone.now())
References _to_naive().
Referenced by django.db.models.fields.TimeField._check_fix_default_value(), and django.db.models.fields.DateTimeCheckMixin._check_if_value_fixed().
_load_field()
django.db.models.fields._load_field (app_label, model_name, field_name) protected
Definition at line 88 of file __init__.py.
def _load_field(app_label, model_name, field_name):
    return apps.get_model(app_label, model_name)._meta.get_field(field_name)
# A guide to Field parameters:
#
#   * name:      The name of the field specified in the model.
#   * attname:   The attribute to use on the model object. This is the same as
#                "name", except in the case of ForeignKeys, where "_id" is
#                appended.
#   * db_column: The db_column specified in the model (or None).
#   * column:    The database column for this field. This is the same as
#                "attname", except if db_column is specified.
#
# Code that introspects values, or does other dynamic things, should use
# attname. For example, this gets the primary key value of object "obj":
#
#     getattr(obj, opts.pk.attname)
_to_naive()
django.db.models.fields._to_naive (value) protected
Definition at line 1334 of file __init__.py.
def _to_naive(value):
    if timezone.is_aware(value):
        value = timezone.make_naive(value, datetime.timezone.utc)
    return value
Referenced by django.db.models.fields.DateField._check_fix_default_value(), django.db.models.fields.DateTimeCheckMixin._check_if_value_fixed(), and _get_naive_now().
return_None()
django.db.models.fields.return_None ()
Definition at line 114 of file __init__.py.
def return_None():
    return None
@total_ordering
Variable Documentation
BLANK_CHOICE_DASH
list django.db.models.fields.BLANK_CHOICE_DASH = [("", "---------")]
Definition at line 85 of file __init__.py.