Read&Watch: pip._vendor.resolvelib.resolvers Namespace Reference
pip._vendor.resolvelib.resolvers Namespace Reference
Classes
class Criterion
class InconsistentCandidate
class RequirementsConflicted
class Resolution
class ResolutionError
class ResolutionImpossible
class ResolutionTooDeep
class Resolver
class ResolverException
Functions
_has_route_to_root (criteria, key, all_keys, connected)
_build_result (state)
Variables
RequirementInformation
State = collections.namedtuple("State", "mapping criteria backtrack_causes")
Result = collections.namedtuple("Result", "mapping graph criteria")
Function Documentation
_build_result()
pip._vendor.resolvelib.resolvers._build_result (state) protected
Definition at line 482 of file resolvers.py.
def _build_result(state):
    mapping = state.mapping
    all_keys = {id(v): k for k, v in mapping.items()}
    all_keys[id(None)] = None
    graph = DirectedGraph()
    graph.add(None)  # Sentinel as root dependencies' parent.
    connected = {None}
    for key, criterion in state.criteria.items():
        if not _has_route_to_root(state.criteria, key, all_keys, connected):
            continue
        if key not in graph:
            graph.add(key)
        for p in criterion.iter_parent():
            try:
                pkey = all_keys[id(p)]
            except KeyError:
                continue
            if pkey not in graph:
                graph.add(pkey)
            graph.connect(pkey, key)
    return Result(
        mapping={k: v for k, v in mapping.items() if k in connected},
        graph=graph,
        criteria=state.criteria,
    )
References _has_route_to_root(), and Result.
Referenced by pip._vendor.resolvelib.resolvers.Resolver.resolve().
_has_route_to_root()
pip._vendor.resolvelib.resolvers._has_route_to_root (criteria, key, all_keys, connected) protected
Definition at line 460 of file resolvers.py.
def _has_route_to_root(criteria, key, all_keys, connected):
    if key in connected:
        return True
    if key not in criteria:
        return False
    for p in criteria[key].iter_parent():
        try:
            pkey = all_keys[id(p)]
        except KeyError:
            continue
        if pkey in connected:
            connected.add(key)
            return True
        if _has_route_to_root(criteria, pkey, all_keys, connected):
            connected.add(key)
            return True
    return False
References _has_route_to_root().
Referenced by _build_result(), and _has_route_to_root().
Variable Documentation
RequirementInformation
pip._vendor.resolvelib.resolvers.RequirementInformation
Initial value:
=  collections.namedtuple(
    "RequirementInformation", ["requirement", "parent"]
)
Definition at line 8 of file resolvers.py.
Referenced by pip._vendor.resolvelib.resolvers.Resolution._add_to_criteria().
Result
pip._vendor.resolvelib.resolvers.Result = collections.namedtuple("Result", "mapping graph criteria")
Definition at line 479 of file resolvers.py.
Referenced by _build_result().
State
pip._vendor.resolvelib.resolvers.State = collections.namedtuple("State", "mapping criteria backtrack_causes")
Definition at line 102 of file resolvers.py.
Referenced by pip._vendor.resolvelib.resolvers.Resolution._push_new_state(), and pip._vendor.resolvelib.resolvers.Resolution.resolve().