Read&Watch: six Namespace Reference
six Namespace Reference
Classes
class _LazyDescr
class _LazyModule
class _MovedItems
class _SixMetaPathImporter
class Iterator
class Module_six_moves_urllib
class Module_six_moves_urllib_error
class Module_six_moves_urllib_parse
class Module_six_moves_urllib_request
class Module_six_moves_urllib_response
class Module_six_moves_urllib_robotparser
class MovedAttribute
class MovedModule
class X
Functions
_add_doc (func, doc)
_import_module (name)
add_move (move)
remove_move (name)
advance_iterator (it)
callable (obj)
get_unbound_function (unbound)
create_unbound_method (func, cls)
create_bound_method (func, obj)
iterkeys (d, **kw)
itervalues (d, **kw)
iteritems (d, **kw)
iterlists (d, **kw)
b (s)
u (s)
byte2int (bs)
indexbytes (buf, i)
assertCountEqual (self, *args, **kwargs)
assertRaisesRegex (self, *args, **kwargs)
assertRegex (self, *args, **kwargs)
assertNotRegex (self, *args, **kwargs)
reraise (tp, value, tb=None)
exec_ (_code_, _globs_=None, _locs_=None)
raise_from (value, from_value)
print_ (*args, **kwargs)
_update_wrapper (wrapper, wrapped, assigned=functools.WRAPPER_ASSIGNMENTS, updated=functools.WRAPPER_UPDATES)
wraps (wrapped, assigned=functools.WRAPPER_ASSIGNMENTS, updated=functools.WRAPPER_UPDATES)
with_metaclass (meta, *bases)
add_metaclass (metaclass)
ensure_binary (s, encoding='utf-8', errors='strict')
ensure_str (s, encoding='utf-8', errors='strict')
ensure_text (s, encoding='utf-8', errors='strict')
python_2_unicode_compatible (klass)
Variables
int PY2 = 2
int PY3 = 3
tuple PY34 = (3, 4)
string_types = str,
integer_types = int,
class_types = type,
text_type = str
binary_type = bytes
MAXSIZE = sys.maxsize
spec_from_loader = None
_importer = _SixMetaPathImporter(__name__)
list _moved_attributes
moves = _MovedItems(__name__ + ".moves")
list _urllib_parse_moved_attributes
list _urllib_error_moved_attributes
list _urllib_request_moved_attributes
list _urllib_response_moved_attributes
list _urllib_robotparser_moved_attributes
str _meth_func = "__func__"
str _meth_self = "__self__"
str _func_closure = "__closure__"
str _func_code = "__code__"
str _func_defaults = "__defaults__"
str _func_globals = "__globals__"
advance_iterator = next
next = advance_iterator
callable = callable
create_bound_method = types.MethodType
Iterator = object
get_method_function = operator.attrgetter(_meth_func)
get_method_self = operator.attrgetter(_meth_self)
get_function_closure = operator.attrgetter(_func_closure)
get_function_code = operator.attrgetter(_func_code)
get_function_defaults = operator.attrgetter(_func_defaults)
get_function_globals = operator.attrgetter(_func_globals)
viewkeys = operator.methodcaller("keys")
viewvalues = operator.methodcaller("values")
viewitems = operator.methodcaller("items")
unichr = chr
int2byte = struct.Struct(">B").pack
byte2int = operator.itemgetter(0)
indexbytes = operator.getitem
iterbytes = iter
StringIO = io.StringIO
BytesIO = io.BytesIO
str _assertCountEqual = "assertCountEqual"
str _assertRaisesRegex = "assertRaisesRegexp"
str _assertRegex = "assertRegexpMatches"
str _assertNotRegex = "assertNotRegexpMatches"
exec_ = getattr(moves.builtins, "exec")
print_ = getattr(moves.builtins, "print", None)
_print = print_
wraps = functools.wraps
submodule_search_locations
Detailed Description
Utilities for writing code that runs on Python 2 and 3
Function Documentation
_add_doc()
six._add_doc (func, doc) protected
Add documentation to a function.
Definition at line 80 of file six.py.
def _add_doc(func, doc):
    """Add documentation to a function."""
    func.__doc__ = doc
_import_module()
six._import_module (name) protected
Import module, returning the module after the last dot.
Definition at line 85 of file six.py.
def _import_module(name):
    """Import module, returning the module after the last dot."""
    __import__(name)
    return sys.modules[name]
Referenced by six.MovedAttribute._resolve(), and six.MovedModule._resolve().
_update_wrapper()
six._update_wrapper (wrapper, wrapped, assigned = functools.WRAPPER_ASSIGNMENTS, updated = functools.WRAPPER_UPDATES) protected
Definition at line 830 of file six.py.
                        updated=functools.WRAPPER_UPDATES):
        for attr in assigned:
            try:
                value = getattr(wrapped, attr)
            except AttributeError:
                continue
            else:
                setattr(wrapper, attr, value)
        for attr in updated:
            getattr(wrapper, attr).update(getattr(wrapped, attr, {}))
        wrapper.__wrapped__ = wrapped
        return wrapper
add_metaclass()
six.add_metaclass (metaclass)
Class decorator for creating a class with a metaclass.
Definition at line 880 of file six.py.
def add_metaclass(metaclass):
    """Class decorator for creating a class with a metaclass."""
    def wrapper(cls):
        orig_vars = cls.__dict__.copy()
        slots = orig_vars.get('__slots__')
        if slots is not None:
            if isinstance(slots, str):
                slots = [slots]
            for slots_var in slots:
                orig_vars.pop(slots_var)
        orig_vars.pop('__dict__', None)
        orig_vars.pop('__weakref__', None)
        if hasattr(cls, '__qualname__'):
            orig_vars['__qualname__'] = cls.__qualname__
        return metaclass(cls.__name__, cls.__bases__, orig_vars)
    return wrapper
add_move()
six.add_move (move)
Add an item to six.moves.
Definition at line 510 of file six.py.
def add_move(move):
    """Add an item to six.moves."""
    setattr(_MovedItems, move.name, move)
advance_iterator()
six.advance_iterator (it)
Definition at line 547 of file six.py.
    def advance_iterator(it):
        return it.next()
assertCountEqual()
six.assertCountEqual (self, * args, ** kwargs)
Definition at line 694 of file six.py.
def assertCountEqual(self, *args, **kwargs):
    return getattr(self, _assertCountEqual)(*args, **kwargs)
assertNotRegex()
six.assertNotRegex (self, * args, ** kwargs)
Definition at line 706 of file six.py.
def assertNotRegex(self, *args, **kwargs):
    return getattr(self, _assertNotRegex)(*args, **kwargs)
assertRaisesRegex()
six.assertRaisesRegex (self, * args, ** kwargs)
Definition at line 698 of file six.py.
def assertRaisesRegex(self, *args, **kwargs):
    return getattr(self, _assertRaisesRegex)(*args, **kwargs)
assertRegex()
six.assertRegex (self, * args, ** kwargs)
Definition at line 702 of file six.py.
def assertRegex(self, *args, **kwargs):
    return getattr(self, _assertRegex)(*args, **kwargs)
b()
six.b (s)
Definition at line 643 of file six.py.
    def b(s):
        return s.encode("latin-1")
byte2int()
six.byte2int (bs)
Definition at line 678 of file six.py.
    def byte2int(bs):
        return ord(bs[0])
callable()
six.callable (obj)
Definition at line 555 of file six.py.
    def callable(obj):
        return any("__call__" in klass.__dict__ for klass in type(obj).__mro__)
create_bound_method()
six.create_bound_method (func, obj)
Definition at line 573 of file six.py.
    def create_bound_method(func, obj):
        return types.MethodType(func, obj, obj.__class__)
create_unbound_method()
six.create_unbound_method (func, cls)
Definition at line 565 of file six.py.
    def create_unbound_method(func, cls):
        return func
ensure_binary()
six.ensure_binary (s, encoding = 'utf-8', errors = 'strict')
Coerce **s** to six.binary_type.
For Python 2:
  - `unicode` -> encoded to `str`
  - `str` -> `str`
For Python 3:
  - `str` -> encoded to `bytes`
  - `bytes` -> `bytes`
Definition at line 898 of file six.py.
def ensure_binary(s, encoding='utf-8', errors='strict'):
    """Coerce **s** to six.binary_type.
    For Python 2:
      - `unicode` -> encoded to `str`
      - `str` -> `str`
    For Python 3:
      - `str` -> encoded to `bytes`
      - `bytes` -> `bytes`
    """
    if isinstance(s, binary_type):
        return s
    if isinstance(s, text_type):
        return s.encode(encoding, errors)
    raise TypeError("not expecting type '%s'" % type(s))
Referenced by pip._vendor.urllib3.contrib.pyopenssl.PyOpenSSLContext.set_alpn_protocols(), and pip._vendor.urllib3.contrib.securetransport.SecureTransportContext.set_alpn_protocols().
ensure_str()
six.ensure_str (s, encoding = 'utf-8', errors = 'strict')
Coerce *s* to `str`.
For Python 2:
  - `unicode` -> encoded to `str`
  - `str` -> `str`
For Python 3:
  - `str` -> `str`
  - `bytes` -> decoded to `str`
Definition at line 916 of file six.py.
def ensure_str(s, encoding='utf-8', errors='strict'):
    """Coerce *s* to `str`.
    For Python 2:
      - `unicode` -> encoded to `str`
      - `str` -> `str`
    For Python 3:
      - `str` -> `str`
      - `bytes` -> decoded to `str`
    """
    # Optimization: Fast return for the common case.
    if type(s) is str:
        return s
    if PY2 and isinstance(s, text_type):
        return s.encode(encoding, errors)
    elif PY3 and isinstance(s, binary_type):
        return s.decode(encoding, errors)
    elif not isinstance(s, (text_type, binary_type)):
        raise TypeError("not expecting type '%s'" % type(s))
    return s
Referenced by pip._vendor.urllib3.util.url._normalize_host(), pip._vendor.urllib3.connection.HTTPConnection.putheader(), pip._vendor.urllib3.connection.HTTPConnection.request(), pip._vendor.urllib3.connection.HTTPConnection.request_chunked(), and pip._vendor.urllib3.connectionpool.HTTPConnectionPool.urlopen().
ensure_text()
six.ensure_text (s, encoding = 'utf-8', errors = 'strict')
Coerce *s* to six.text_type.
For Python 2:
  - `unicode` -> `unicode`
  - `str` -> `unicode`
For Python 3:
  - `str` -> `str`
  - `bytes` -> decoded to `str`
Definition at line 939 of file six.py.
def ensure_text(s, encoding='utf-8', errors='strict'):
    """Coerce *s* to six.text_type.
    For Python 2:
      - `unicode` -> `unicode`
      - `str` -> `unicode`
    For Python 3:
      - `str` -> `str`
      - `bytes` -> decoded to `str`
    """
    if isinstance(s, binary_type):
        return s.decode(encoding, errors)
    elif isinstance(s, text_type):
        return s
    else:
        raise TypeError("not expecting type '%s'" % type(s))
Referenced by pip._vendor.urllib3.util.url._encode_invalid_chars().
exec_()
six.exec_ (_code_, _globs_ = None, _locs_ = None)
Execute code in a namespace.
Definition at line 725 of file six.py.
    def exec_(_code_, _globs_=None, _locs_=None):
        """Execute code in a namespace."""
        if _globs_ is None:
            frame = sys._getframe(1)
            _globs_ = frame.f_globals
            if _locs_ is None:
                _locs_ = frame.f_locals
            del frame
        elif _locs_ is None:
            _locs_ = _globs_
        exec("""exec _code_ in _globs_, _locs_""")
get_unbound_function()
six.get_unbound_function (unbound)
Definition at line 560 of file six.py.
    def get_unbound_function(unbound):
        return unbound
indexbytes()
six.indexbytes (buf, i)
Definition at line 681 of file six.py.
    def indexbytes(buf, i):
        return ord(buf[i])
iteritems()
six.iteritems (d, ** kw)
Definition at line 604 of file six.py.
    def iteritems(d, **kw):
        return iter(d.items(**kw))
Referenced by pip._vendor.urllib3.filepost.iter_field_objects(), and pip._vendor.urllib3.filepost.iter_fields().
iterkeys()
six.iterkeys (d, ** kw)
Definition at line 598 of file six.py.
    def iterkeys(d, **kw):
        return iter(d.keys(**kw))
Referenced by pip._vendor.urllib3.poolmanager.PoolManager.urlopen().
iterlists()
six.iterlists (d, ** kw)
Definition at line 607 of file six.py.
    def iterlists(d, **kw):
        return iter(d.lists(**kw))
itervalues()
six.itervalues (d, ** kw)
Definition at line 601 of file six.py.
    def itervalues(d, **kw):
        return iter(d.values(**kw))
print_()
six.print_ (* args, ** kwargs)
The new-style print function for Python 2.4 and 2.5.
Definition at line 759 of file six.py.
    def print_(*args, **kwargs):
        """The new-style print function for Python 2.4 and 2.5."""
        fp = kwargs.pop("file", sys.stdout)
        if fp is None:
            return
        def write(data):
            if not isinstance(data, basestring):
                data = str(data)
            # If the file has an encoding, encode unicode with it.
            if (isinstance(fp, file) and
                    isinstance(data, unicode) and
                    fp.encoding is not None):
                errors = getattr(fp, "errors", None)
                if errors is None:
                    errors = "strict"
                data = data.encode(fp.encoding, errors)
            fp.write(data)
        want_unicode = False
        sep = kwargs.pop("sep", None)
        if sep is not None:
            if isinstance(sep, unicode):
                want_unicode = True
            elif not isinstance(sep, str):
                raise TypeError("sep must be None or a string")
        end = kwargs.pop("end", None)
        if end is not None:
            if isinstance(end, unicode):
                want_unicode = True
            elif not isinstance(end, str):
                raise TypeError("end must be None or a string")
        if kwargs:
            raise TypeError("invalid keyword arguments to print()")
        if not want_unicode:
            for arg in args:
                if isinstance(arg, unicode):
                    want_unicode = True
                    break
        if want_unicode:
            newline = unicode("\n")
            space = unicode(" ")
        else:
            newline = "\n"
            space = " "
        if sep is None:
            sep = space
        if end is None:
            end = newline
        for i, arg in enumerate(args):
            if i:
                write(sep)
            write(arg)
        write(end)
python_2_unicode_compatible()
six.python_2_unicode_compatible (klass)
A class decorator that defines __unicode__ and __str__ methods under Python 2.
Under Python 3 it does nothing.
To support Python 2 and 3 with a single code base, define a __str__ method
returning text and apply this decorator to the class.
Definition at line 958 of file six.py.
def python_2_unicode_compatible(klass):
    """
    A class decorator that defines __unicode__ and __str__ methods under Python 2.
    Under Python 3 it does nothing.
    To support Python 2 and 3 with a single code base, define a __str__ method
    returning text and apply this decorator to the class.
    """
    if PY2:
        if '__str__' not in klass.__dict__:
            raise ValueError("@python_2_unicode_compatible cannot be applied "
                             "to %s because it doesn't define __str__()." %
                             klass.__name__)
        klass.__unicode__ = klass.__str__
        klass.__str__ = lambda self: self.__unicode__().encode('utf-8')
    return klass
# Complete the moves implementation.
# This code is at the end of this module to speed up module loading.
# Turn this module into a package.
raise_from()
six.raise_from (value, from_value)
Definition at line 753 of file six.py.
    def raise_from(value, from_value):
        raise value
Referenced by pip._vendor.urllib3.util.url._idna_encode(), pip._vendor.urllib3.connectionpool.HTTPConnectionPool._make_request(), pip._vendor.urllib3.util.connection.create_connection(), and pip._vendor.urllib3.util.url.parse_url().
remove_move()
six.remove_move (name)
Remove item from six.moves.
Definition at line 515 of file six.py.
def remove_move(name):
    """Remove item from six.moves."""
    try:
        delattr(_MovedItems, name)
    except AttributeError:
        try:
            del moves.__dict__[name]
        except KeyError:
            raise AttributeError("no such move, %r" % (name,))
reraise()
six.reraise (tp, value, tb = None)
Definition at line 713 of file six.py.
    def reraise(tp, value, tb=None):
        try:
            if value is None:
                value = tp()
            if value.__traceback__ is not tb:
                raise value.with_traceback(tb)
            raise value
        finally:
            value = None
            tb = None
Referenced by pip._vendor.urllib3.util.retry.Retry.increment().
u()
six.u (s)
Definition at line 646 of file six.py.
    def u(s):
        return s
with_metaclass()
six.with_metaclass (meta, * bases)
Create a base class with a metaclass.
Definition at line 856 of file six.py.
def with_metaclass(meta, *bases):
    """Create a base class with a metaclass."""
    # This requires a bit of explanation: the basic idea is to make a dummy
    # metaclass for one level of class instantiation that replaces itself with
    # the actual metaclass.
    class metaclass(type):
        def __new__(cls, name, this_bases, d):
            if sys.version_info[:2] >= (3, 7):
                # This version introduced PEP 560 that requires a bit
                # of extra care (we mimic what is done by __build_class__).
                resolved_bases = types.resolve_bases(bases)
                if resolved_bases is not bases:
                    d['__orig_bases__'] = bases
            else:
                resolved_bases = bases
            return meta(name, resolved_bases, d)
        @classmethod
        def __prepare__(cls, name, this_bases):
            return meta.__prepare__(name, bases)
    return type.__new__(metaclass, 'temporary_class', (), {})
wraps()
six.wraps (wrapped, assigned = functools.WRAPPER_ASSIGNMENTS, updated = functools.WRAPPER_UPDATES)
Definition at line 846 of file six.py.
              updated=functools.WRAPPER_UPDATES):
        return functools.partial(_update_wrapper, wrapped=wrapped,
                                 assigned=assigned, updated=updated)
Variable Documentation
_assertCountEqual
str six._assertCountEqual = "assertCountEqual" protected
Definition at line 659 of file six.py.
_assertNotRegex
str six._assertNotRegex = "assertNotRegexpMatches" protected
Definition at line 663 of file six.py.
_assertRaisesRegex
str six._assertRaisesRegex = "assertRaisesRegexp" protected
Definition at line 661 of file six.py.
_assertRegex
str six._assertRegex = "assertRegexpMatches" protected
Definition at line 662 of file six.py.
_func_closure
str six._func_closure = "__closure__" protected
Definition at line 530 of file six.py.
_func_code
str six._func_code = "__code__" protected
Definition at line 531 of file six.py.
_func_defaults
str six._func_defaults = "__defaults__" protected
Definition at line 532 of file six.py.
_func_globals
str six._func_globals = "__globals__" protected
Definition at line 533 of file six.py.
_importer
six._importer = _SixMetaPathImporter(__name__) protected
Definition at line 242 of file six.py.
_meth_func
str six._meth_func = "__func__" protected
Definition at line 527 of file six.py.
_meth_self
str six._meth_self = "__self__" protected
Definition at line 528 of file six.py.
_moved_attributes
six._moved_attributes protected
Definition at line 251 of file six.py.
_print
six._print = print_ protected
Definition at line 813 of file six.py.
_urllib_error_moved_attributes
list six._urllib_error_moved_attributes protected
Initial value:
=  [
    MovedAttribute("URLError", "urllib2", "urllib.error"),
    MovedAttribute("HTTPError", "urllib2", "urllib.error"),
    MovedAttribute("ContentTooShortError", "urllib", "urllib.error"),
]
Definition at line 387 of file six.py.
_urllib_parse_moved_attributes
list six._urllib_parse_moved_attributes protected
Initial value:
=  [
    MovedAttribute("ParseResult", "urlparse", "urllib.parse"),
    MovedAttribute("SplitResult", "urlparse", "urllib.parse"),
    MovedAttribute("parse_qs", "urlparse", "urllib.parse"),
    MovedAttribute("parse_qsl", "urlparse", "urllib.parse"),
    MovedAttribute("urldefrag", "urlparse", "urllib.parse"),
    MovedAttribute("urljoin", "urlparse", "urllib.parse"),
    MovedAttribute("urlparse", "urlparse", "urllib.parse"),
    MovedAttribute("urlsplit", "urlparse", "urllib.parse"),
    MovedAttribute("urlunparse", "urlparse", "urllib.parse"),
    MovedAttribute("urlunsplit", "urlparse", "urllib.parse"),
    MovedAttribute("quote", "urllib", "urllib.parse"),
    MovedAttribute("quote_plus", "urllib", "urllib.parse"),
    MovedAttribute("unquote", "urllib", "urllib.parse"),
    MovedAttribute("unquote_plus", "urllib", "urllib.parse"),
    MovedAttribute("unquote_to_bytes", "urllib", "urllib.parse", "unquote", "unquote_to_bytes"),
    MovedAttribute("urlencode", "urllib", "urllib.parse"),
    MovedAttribute("splitquery", "urllib", "urllib.parse"),
    MovedAttribute("splittag", "urllib", "urllib.parse"),
    MovedAttribute("splituser", "urllib", "urllib.parse"),
    MovedAttribute("splitvalue", "urllib", "urllib.parse"),
    MovedAttribute("uses_fragment", "urlparse", "urllib.parse"),
    MovedAttribute("uses_netloc", "urlparse", "urllib.parse"),
    MovedAttribute("uses_params", "urlparse", "urllib.parse"),
    MovedAttribute("uses_query", "urlparse", "urllib.parse"),
    MovedAttribute("uses_relative", "urlparse", "urllib.parse"),
]
Definition at line 345 of file six.py.
_urllib_request_moved_attributes
list six._urllib_request_moved_attributes protected
Definition at line 407 of file six.py.
_urllib_response_moved_attributes
list six._urllib_response_moved_attributes protected
Initial value:
=  [
    MovedAttribute("addbase", "urllib", "urllib.response"),
    MovedAttribute("addclosehook", "urllib", "urllib.response"),
    MovedAttribute("addinfo", "urllib", "urllib.response"),
    MovedAttribute("addinfourl", "urllib", "urllib.response"),
]
Definition at line 459 of file six.py.
_urllib_robotparser_moved_attributes
list six._urllib_robotparser_moved_attributes protected
Initial value:
=  [
    MovedAttribute("RobotFileParser", "robotparser", "urllib.robotparser"),
]
Definition at line 480 of file six.py.
advance_iterator
six.advance_iterator = next
Definition at line 545 of file six.py.
binary_type
six.binary_type = bytes
Definition at line 45 of file six.py.
byte2int
six.byte2int = operator.itemgetter(0)
Definition at line 652 of file six.py.
BytesIO
six.BytesIO = io.BytesIO
Definition at line 657 of file six.py.
callable
six.callable = callable
Definition at line 553 of file six.py.
class_types
tuple six.class_types = type,
Definition at line 43 of file six.py.
create_bound_method
six.create_bound_method = types.MethodType
Definition at line 563 of file six.py.
exec_
six.exec_ = getattr(moves.builtins, "exec")
Definition at line 711 of file six.py.
get_function_closure
six.get_function_closure = operator.attrgetter(_func_closure)
Definition at line 591 of file six.py.
get_function_code
six.get_function_code = operator.attrgetter(_func_code)
Definition at line 592 of file six.py.
get_function_defaults
six.get_function_defaults = operator.attrgetter(_func_defaults)
Definition at line 593 of file six.py.
get_function_globals
six.get_function_globals = operator.attrgetter(_func_globals)
Definition at line 594 of file six.py.
get_method_function
six.get_method_function = operator.attrgetter(_meth_func)
Definition at line 589 of file six.py.
get_method_self
six.get_method_self = operator.attrgetter(_meth_self)
Definition at line 590 of file six.py.
indexbytes
six.indexbytes = operator.getitem
Definition at line 653 of file six.py.
int2byte
six.int2byte = struct.Struct(">B").pack
Definition at line 650 of file six.py.
integer_types
tuple six.integer_types = int,
Definition at line 42 of file six.py.
Iterator
six.Iterator = object
Definition at line 568 of file six.py.
iterbytes
six.iterbytes = iter
Definition at line 654 of file six.py.
MAXSIZE
six.MAXSIZE = sys.maxsize
Definition at line 47 of file six.py.
moves
six.moves = _MovedItems(__name__ + ".moves")
Definition at line 336 of file six.py.
next
six.next = advance_iterator
Definition at line 549 of file six.py.
print_
six.print_ = getattr(moves.builtins, "print", None)
Definition at line 757 of file six.py.
PY2
int six.PY2 = 2
Definition at line 36 of file six.py.
PY3
int six.PY3 = 3
Definition at line 37 of file six.py.
PY34
tuple six.PY34 = (3, 4)
Definition at line 38 of file six.py.
spec_from_loader
six.spec_from_loader = None
Definition at line 77 of file six.py.
Referenced by six._SixMetaPathImporter.find_spec().
string_types
six.string_types = str,
Definition at line 41 of file six.py.
StringIO
six.StringIO = io.StringIO
Definition at line 656 of file six.py.
submodule_search_locations
six.submodule_search_locations
Definition at line 982 of file six.py.
text_type
six.text_type = str
Definition at line 44 of file six.py.
Referenced by users.tokens.AccountActivationTokenGenerator._make_hash_value().
unichr
six.unichr = chr
Definition at line 648 of file six.py.
Referenced by pip._vendor.urllib3.fields.format_header_param_rfc2231().
viewitems
six.viewitems = operator.methodcaller("items")
Definition at line 614 of file six.py.
viewkeys
six.viewkeys = operator.methodcaller("keys")
Definition at line 610 of file six.py.
viewvalues
six.viewvalues = operator.methodcaller("values")
Definition at line 612 of file six.py.
wraps
six.wraps = functools.wraps
Definition at line 853 of file six.py.