Read&Watch: pip._internal.operations.check Namespace Reference
pip._internal.operations.check Namespace Reference
Classes
class PackageDetails
Functions
Tuple[PackageSet, bool] create_package_set_from_installed ()
CheckResult check_package_set (PackageSet package_set, Optional[Callable[[str], bool]] should_ignore=None)
ConflictDetails check_install_conflicts (List[InstallRequirement] to_install)
Generator[BaseDistribution, None, None] check_unsupported (Iterable[BaseDistribution] packages, Iterable[Tag] supported_tags)
Set[NormalizedName] _simulate_installation_of (List[InstallRequirement] to_install, PackageSet package_set)
Set[NormalizedName] _create_whitelist (Set[NormalizedName] would_be_installed, PackageSet package_set)
Variables
logger = logging.getLogger(__name__)
PackageSet = Dict[NormalizedName, PackageDetails]
Missing = Tuple[NormalizedName, Requirement]
Conflicting = Tuple[NormalizedName, Version, Requirement]
MissingDict = Dict[NormalizedName, List[Missing]]
ConflictingDict = Dict[NormalizedName, List[Conflicting]]
CheckResult = Tuple[MissingDict, ConflictingDict]
ConflictDetails = Tuple[PackageSet, CheckResult]
Detailed Description
Validation of dependencies of packages
Function Documentation
_create_whitelist()
Set[NormalizedName] pip._internal.operations.check._create_whitelist (Set[NormalizedName] would_be_installed, PackageSet package_set) protected
Definition at line 167 of file check.py.
) -> Set[NormalizedName]:
    packages_affected = set(would_be_installed)
    for package_name in package_set:
        if package_name in packages_affected:
            continue
        for req in package_set[package_name].dependencies:
            if canonicalize_name(req.name) in packages_affected:
                packages_affected.add(package_name)
                break
    return packages_affected
Referenced by check_install_conflicts().
_simulate_installation_of()
Set[NormalizedName] pip._internal.operations.check._simulate_installation_of (List[InstallRequirement] to_install, PackageSet package_set) protected
Computes the version of packages after installing to_install.
Definition at line 148 of file check.py.
) -> Set[NormalizedName]:
    """Computes the version of packages after installing to_install."""
    # Keep track of packages that were installed
    installed = set()
    # Modify it as installing requirement_set would (assuming no errors)
    for inst_req in to_install:
        abstract_dist = make_distribution_for_install_requirement(inst_req)
        dist = abstract_dist.get_metadata_distribution()
        name = dist.canonical_name
        package_set[name] = PackageDetails(dist.version, list(dist.iter_dependencies()))
        installed.add(name)
    return installed
Referenced by check_install_conflicts().
check_install_conflicts()
ConflictDetails pip._internal.operations.check.check_install_conflicts (List[InstallRequirement] to_install)
For checking if the dependency graph would be consistent after \
installing given requirements
Definition at line 112 of file check.py.
def check_install_conflicts(to_install: List[InstallRequirement]) -> ConflictDetails:
    """For checking if the dependency graph would be consistent after \
    installing given requirements
    """
    # Start from the current state
    package_set, _ = create_package_set_from_installed()
    # Install packages
    would_be_installed = _simulate_installation_of(to_install, package_set)
    # Only warn about directly-dependent packages; create a whitelist of them
    whitelist = _create_whitelist(would_be_installed, package_set)
    return (
        package_set,
        check_package_set(
            package_set, should_ignore=lambda name: name not in whitelist
        ),
    )
References _create_whitelist(), _simulate_installation_of(), check_package_set(), and create_package_set_from_installed().
check_package_set()
CheckResult pip._internal.operations.check.check_package_set (PackageSet package_set, Optional[Callable[[str], bool]] should_ignore = None)
Check if a package set is consistent
If should_ignore is passed, it should be a callable that takes a
package name and returns a boolean.
Definition at line 67 of file check.py.
) -> CheckResult:
    """Check if a package set is consistent
    If should_ignore is passed, it should be a callable that takes a
    package name and returns a boolean.
    """
    missing = {}
    conflicting = {}
    for package_name, package_detail in package_set.items():
        # Info about dependencies of package_name
        missing_deps: Set[Missing] = set()
        conflicting_deps: Set[Conflicting] = set()
        if should_ignore and should_ignore(package_name):
            continue
        for req in package_detail.dependencies:
            name = canonicalize_name(req.name)
            # Check if it's missing
            if name not in package_set:
                missed = True
                if req.marker is not None:
                    missed = req.marker.evaluate({"extra": ""})
                if missed:
                    missing_deps.add((name, req))
                continue
            # Check if there's a conflict
            version = package_set[name].version
            if not req.specifier.contains(version, prereleases=True):
                conflicting_deps.add((name, version, req))
        if missing_deps:
            missing[package_name] = sorted(missing_deps, key=str)
        if conflicting_deps:
            conflicting[package_name] = sorted(conflicting_deps, key=str)
    return missing, conflicting
Referenced by check_install_conflicts().
check_unsupported()
Generator[BaseDistribution, None, None] pip._internal.operations.check.check_unsupported (Iterable[BaseDistribution] packages, Iterable[Tag] supported_tags)
Definition at line 132 of file check.py.
) -> Generator[BaseDistribution, None, None]:
    for p in packages:
        with suppress(FileNotFoundError):
            wheel_file = p.read_text("WHEEL")
            wheel_tags: FrozenSet[Tag] = reduce(
                frozenset.union,
                map(parse_tag, Parser().parsestr(wheel_file).get_all("Tag", [])),
                frozenset(),
            )
            if wheel_tags.isdisjoint(supported_tags):
                yield p
create_package_set_from_installed()
Tuple[PackageSet, bool] pip._internal.operations.check.create_package_set_from_installed ()
Converts a list of distributions into a PackageSet.
Definition at line 50 of file check.py.
def create_package_set_from_installed() -> Tuple[PackageSet, bool]:
    """Converts a list of distributions into a PackageSet."""
    package_set = {}
    problems = False
    env = get_default_environment()
    for dist in env.iter_installed_distributions(local_only=False, skip=()):
        name = dist.canonical_name
        try:
            dependencies = list(dist.iter_dependencies())
            package_set[name] = PackageDetails(dist.version, dependencies)
        except (OSError, ValueError) as e:
            # Don't crash on unreadable or broken metadata.
            logger.warning("Error parsing dependencies of %s: %s", name, e)
            problems = True
    return package_set, problems
Referenced by check_install_conflicts().
Variable Documentation
CheckResult
pip._internal.operations.check.CheckResult = Tuple[MissingDict, ConflictingDict]
Definition at line 46 of file check.py.
ConflictDetails
pip._internal.operations.check.ConflictDetails = Tuple[PackageSet, CheckResult]
Definition at line 47 of file check.py.
Conflicting
pip._internal.operations.check.Conflicting = Tuple[NormalizedName, Version, Requirement]
Definition at line 42 of file check.py.
ConflictingDict
pip._internal.operations.check.ConflictingDict = Dict[NormalizedName, List[Conflicting]]
Definition at line 45 of file check.py.
logger
pip._internal.operations.check.logger = logging.getLogger(__name__)
Definition at line 31 of file check.py.
Missing
pip._internal.operations.check.Missing = Tuple[NormalizedName, Requirement]
Definition at line 41 of file check.py.
MissingDict
pip._internal.operations.check.MissingDict = Dict[NormalizedName, List[Missing]]
Definition at line 44 of file check.py.
PackageSet
pip._internal.operations.check.PackageSet = Dict[NormalizedName, PackageDetails]
Definition at line 40 of file check.py.