Read&Watch: django.contrib.admin.checks Namespace Reference
django.contrib.admin.checks Namespace Reference
Classes
class BaseModelAdminChecks
class InlineModelAdminChecks
class ModelAdminChecks
Functions
_issubclass (cls, classinfo)
_contains_subclass (class_path, candidate_paths)
check_admin_app (app_configs, **kwargs)
check_dependencies (**kwargs)
must_be (type, option, obj, id)
must_inherit_from (parent, option, obj, id)
refer_to_missing_field (field, option, obj, id)
Function Documentation
_contains_subclass()
django.contrib.admin.checks._contains_subclass (class_path, candidate_paths) protected
Return whether or not a dotted class path (or a subclass of that class) is
found in a list of candidate paths.
Definition at line 30 of file checks.py.
def _contains_subclass(class_path, candidate_paths):
    """
    Return whether or not a dotted class path (or a subclass of that class) is
    found in a list of candidate paths.
    """
    cls = import_string(class_path)
    for path in candidate_paths:
        try:
            candidate_cls = import_string(path)
        except ImportError:
            # ImportErrors are raised elsewhere.
            continue
        if _issubclass(candidate_cls, cls):
            return True
    return False
References _issubclass().
Referenced by check_dependencies().
_issubclass()
django.contrib.admin.checks._issubclass (cls, classinfo) protected
issubclass() variant that doesn't raise an exception if cls isn't a
class.
Definition at line 19 of file checks.py.
def _issubclass(cls, classinfo):
    """
    issubclass() variant that doesn't raise an exception if cls isn't a
    class.
    """
    try:
        return issubclass(cls, classinfo)
    except TypeError:
        return False
Referenced by django.contrib.admin.checks.BaseModelAdminChecks._check_form(), django.contrib.admin.checks.InlineModelAdminChecks._check_formset(), django.contrib.admin.checks.ModelAdminChecks._check_inlines_item(), django.contrib.admin.checks.ModelAdminChecks._check_list_filter_item(), and _contains_subclass().
check_admin_app()
django.contrib.admin.checks.check_admin_app (app_configs, ** kwargs)
Definition at line 47 of file checks.py.
def check_admin_app(app_configs, **kwargs):
    from django.contrib.admin.sites import all_sites
    errors = []
    for site in all_sites:
        errors.extend(site.check(app_configs))
    return errors
check_dependencies()
django.contrib.admin.checks.check_dependencies (** kwargs)
Check that the admin's dependencies are correctly installed.
Definition at line 56 of file checks.py.
def check_dependencies(**kwargs):
    """
    Check that the admin's dependencies are correctly installed.
    """
    from django.contrib.admin.sites import all_sites
    if not apps.is_installed("django.contrib.admin"):
        return []
    errors = []
    app_dependencies = (
        ("django.contrib.contenttypes", 401),
        ("django.contrib.auth", 405),
        ("django.contrib.messages", 406),
    )
    for app_name, error_code in app_dependencies:
        if not apps.is_installed(app_name):
            errors.append(
                checks.Error(
                    "'%s' must be in INSTALLED_APPS in order to use the admin "
                    "application." % app_name,
                    id="admin.E%d" % error_code,
                )
            )
    for engine in engines.all():
        if isinstance(engine, DjangoTemplates):
            django_templates_instance = engine.engine
            break
    else:
        django_templates_instance = None
    if not django_templates_instance:
        errors.append(
            checks.Error(
                "A 'django.template.backends.django.DjangoTemplates' instance "
                "must be configured in TEMPLATES in order to use the admin "
                "application.",
                id="admin.E403",
            )
        )
    else:
        if (
            "django.contrib.auth.context_processors.auth"
            not in django_templates_instance.context_processors
            and _contains_subclass(
                "django.contrib.auth.backends.ModelBackend",
                settings.AUTHENTICATION_BACKENDS,
            )
        ):
            errors.append(
                checks.Error(
                    "'django.contrib.auth.context_processors.auth' must be "
                    "enabled in DjangoTemplates (TEMPLATES) if using the default "
                    "auth backend in order to use the admin application.",
                    id="admin.E402",
                )
            )
        if (
            "django.contrib.messages.context_processors.messages"
            not in django_templates_instance.context_processors
        ):
            errors.append(
                checks.Error(
                    "'django.contrib.messages.context_processors.messages' must "
                    "be enabled in DjangoTemplates (TEMPLATES) in order to use "
                    "the admin application.",
                    id="admin.E404",
                )
            )
        sidebar_enabled = any(site.enable_nav_sidebar for site in all_sites)
        if (
            sidebar_enabled
            and "django.template.context_processors.request"
            not in django_templates_instance.context_processors
        ):
            errors.append(
                checks.Warning(
                    "'django.template.context_processors.request' must be enabled "
                    "in DjangoTemplates (TEMPLATES) in order to use the admin "
                    "navigation sidebar.",
                    id="admin.W411",
                )
            )
    if not _contains_subclass(
        "django.contrib.auth.middleware.AuthenticationMiddleware", settings.MIDDLEWARE
    ):
        errors.append(
            checks.Error(
                "'django.contrib.auth.middleware.AuthenticationMiddleware' must "
                "be in MIDDLEWARE in order to use the admin application.",
                id="admin.E408",
            )
        )
    if not _contains_subclass(
        "django.contrib.messages.middleware.MessageMiddleware", settings.MIDDLEWARE
    ):
        errors.append(
            checks.Error(
                "'django.contrib.messages.middleware.MessageMiddleware' must "
                "be in MIDDLEWARE in order to use the admin application.",
                id="admin.E409",
            )
        )
    if not _contains_subclass(
        "django.contrib.sessions.middleware.SessionMiddleware", settings.MIDDLEWARE
    ):
        errors.append(
            checks.Error(
                "'django.contrib.sessions.middleware.SessionMiddleware' must "
                "be in MIDDLEWARE in order to use the admin application.",
                hint=(
                    "Insert "
                    "'django.contrib.sessions.middleware.SessionMiddleware' "
                    "before "
                    "'django.contrib.auth.middleware.AuthenticationMiddleware'."
                ),
                id="admin.E410",
            )
        )
    return errors
References _contains_subclass().
must_be()
django.contrib.admin.checks.must_be (type, option, obj, id)
Definition at line 1331 of file checks.py.
def must_be(type, option, obj, id):
    return [
        checks.Error(
            "The value of '%s' must be %s." % (option, type),
            obj=obj.__class__,
            id=id,
        ),
    ]
Referenced by django.contrib.admin.checks.BaseModelAdminChecks._check_autocomplete_fields(), django.contrib.admin.checks.BaseModelAdminChecks._check_autocomplete_fields_item(), django.contrib.admin.checks.ModelAdminChecks._check_date_hierarchy(), django.contrib.admin.checks.BaseModelAdminChecks._check_exclude(), django.contrib.admin.checks.InlineModelAdminChecks._check_extra(), django.contrib.admin.checks.BaseModelAdminChecks._check_fields(), django.contrib.admin.checks.BaseModelAdminChecks._check_fieldsets(), django.contrib.admin.checks.BaseModelAdminChecks._check_fieldsets_item(), django.contrib.admin.checks.BaseModelAdminChecks._check_filter_horizontal(), django.contrib.admin.checks.BaseModelAdminChecks._check_filter_item(), django.contrib.admin.checks.BaseModelAdminChecks._check_filter_vertical(), django.contrib.admin.checks.ModelAdminChecks._check_inlines(), django.contrib.admin.checks.ModelAdminChecks._check_inlines_item(), django.contrib.admin.checks.ModelAdminChecks._check_list_display(), django.contrib.admin.checks.ModelAdminChecks._check_list_display_links(), django.contrib.admin.checks.ModelAdminChecks._check_list_editable(), django.contrib.admin.checks.ModelAdminChecks._check_list_filter(), django.contrib.admin.checks.ModelAdminChecks._check_list_max_show_all(), django.contrib.admin.checks.ModelAdminChecks._check_list_per_page(), django.contrib.admin.checks.ModelAdminChecks._check_list_select_related(), django.contrib.admin.checks.InlineModelAdminChecks._check_max_num(), django.contrib.admin.checks.InlineModelAdminChecks._check_min_num(), django.contrib.admin.checks.BaseModelAdminChecks._check_ordering(), django.contrib.admin.checks.BaseModelAdminChecks._check_prepopulated_fields(), django.contrib.admin.checks.BaseModelAdminChecks._check_prepopulated_fields_value(), django.contrib.admin.checks.BaseModelAdminChecks._check_radio_fields(), django.contrib.admin.checks.BaseModelAdminChecks._check_raw_id_fields(), django.contrib.admin.checks.BaseModelAdminChecks._check_raw_id_fields_item(), django.contrib.admin.checks.BaseModelAdminChecks._check_readonly_fields(), django.contrib.admin.checks.ModelAdminChecks._check_save_as(), django.contrib.admin.checks.ModelAdminChecks._check_save_on_top(), and django.contrib.admin.checks.ModelAdminChecks._check_search_fields().
must_inherit_from()
django.contrib.admin.checks.must_inherit_from (parent, option, obj, id)
Definition at line 1341 of file checks.py.
def must_inherit_from(parent, option, obj, id):
    return [
        checks.Error(
            "The value of '%s' must inherit from '%s'." % (option, parent),
            obj=obj.__class__,
            id=id,
        ),
    ]
Referenced by django.contrib.admin.checks.BaseModelAdminChecks._check_form(), django.contrib.admin.checks.InlineModelAdminChecks._check_formset(), and django.contrib.admin.checks.ModelAdminChecks._check_list_filter_item().
refer_to_missing_field()
django.contrib.admin.checks.refer_to_missing_field (field, option, obj, id)
Definition at line 1351 of file checks.py.
def refer_to_missing_field(field, option, obj, id):
    return [
        checks.Error(
            "The value of '%s' refers to '%s', which is not a field of '%s'."
            % (option, field, obj.model._meta.label),
            obj=obj.__class__,
            id=id,
        ),
    ]
Referenced by django.contrib.admin.checks.BaseModelAdminChecks._check_autocomplete_fields_item(), django.contrib.admin.checks.BaseModelAdminChecks._check_filter_item(), django.contrib.admin.checks.ModelAdminChecks._check_list_editable_item(), django.contrib.admin.checks.BaseModelAdminChecks._check_ordering_item(), django.contrib.admin.checks.BaseModelAdminChecks._check_prepopulated_fields_key(), django.contrib.admin.checks.BaseModelAdminChecks._check_prepopulated_fields_value_item(), django.contrib.admin.checks.BaseModelAdminChecks._check_radio_fields_key(), and django.contrib.admin.checks.BaseModelAdminChecks._check_raw_id_fields_item().