Read&Watch: PIL.ImageQt Namespace Reference
PIL.ImageQt Namespace Reference
Classes
class ImageQt
Functions
int rgb (int r, int g, int b, int a=255)
ImageFile.ImageFile fromqimage (QImage|QPixmap im)
ImageFile.ImageFile fromqpixmap (QPixmap im)
bytes align8to32 (bytes bytes, int width, str mode)
dict[str, Any] _toqclass_helper (Image.Image|str|QByteArray im)
ImageQt toqimage (Image.Image|str|QByteArray im)
QPixmap toqpixmap (Image.Image|str|QByteArray im)
Variables
type QByteArray = Union[PyQt6.QtCore.QByteArray, PySide6.QtCore.QByteArray]
QIODevice = Union[PyQt6.QtCore.QIODevice, PySide6.QtCore.QIODevice]
QImage = Union[PyQt6.QtGui.QImage, PySide6.QtGui.QImage]
QPixmap = Union[PyQt6.QtGui.QPixmap, PySide6.QtGui.QPixmap]
str qt_version | None
list qt_versions
key
modules
reverse
Callable qRgba [[int, int, int, int], int]
bool qt_is_installed = True
Function Documentation
_toqclass_helper()
dict[str, Any] PIL.ImageQt._toqclass_helper (Image.Image | str | QByteArray im) protected
Definition at line 132 of file ImageQt.py.
def _toqclass_helper(im: Image.Image | str | QByteArray) -> dict[str, Any]:
    data = None
    colortable = None
    exclusive_fp = False
    # handle filename, if given instead of image name
    if hasattr(im, "toUtf8"):
        # FIXME - is this really the best way to do this?
        im = str(im.toUtf8(), "utf-8")
    if is_path(im):
        im = Image.open(im)
        exclusive_fp = True
    assert isinstance(im, Image.Image)
    qt_format = getattr(QImage, "Format") if qt_version == "6" else QImage
    if im.mode == "1":
        format = getattr(qt_format, "Format_Mono")
    elif im.mode == "L":
        format = getattr(qt_format, "Format_Indexed8")
        colortable = [rgb(i, i, i) for i in range(256)]
    elif im.mode == "P":
        format = getattr(qt_format, "Format_Indexed8")
        palette = im.getpalette()
        assert palette is not None
        colortable = [rgb(*palette[i : i + 3]) for i in range(0, len(palette), 3)]
    elif im.mode == "RGB":
        # Populate the 4th channel with 255
        im = im.convert("RGBA")
        data = im.tobytes("raw", "BGRA")
        format = getattr(qt_format, "Format_RGB32")
    elif im.mode == "RGBA":
        data = im.tobytes("raw", "BGRA")
        format = getattr(qt_format, "Format_ARGB32")
    elif im.mode == "I;16":
        im = im.point(lambda i: i * 256)
        format = getattr(qt_format, "Format_Grayscale16")
    else:
        if exclusive_fp:
            im.close()
        msg = f"unsupported image mode {repr(im.mode)}"
        raise ValueError(msg)
    size = im.size
    __data = data or align8to32(im.tobytes(), size[0], im.mode)
    if exclusive_fp:
        im.close()
    return {"data": __data, "size": size, "format": format, "colortable": colortable}
References align8to32(), and rgb().
Referenced by PIL.ImageQt.ImageQt.__init__().
align8to32()
bytes PIL.ImageQt.align8to32 (bytes bytes, int width, str mode)
converts each scanline of data from 8 bit to 32 bit aligned
Definition at line 106 of file ImageQt.py.
def align8to32(bytes: bytes, width: int, mode: str) -> bytes:
    """
    converts each scanline of data from 8 bit to 32 bit aligned
    """
    bits_per_pixel = {"1": 1, "L": 8, "P": 8, "I;16": 16}[mode]
    # calculate bytes per line and the extra padding if needed
    bits_per_line = bits_per_pixel * width
    full_bytes_per_line, remaining_bits_per_line = divmod(bits_per_line, 8)
    bytes_per_line = full_bytes_per_line + (1 if remaining_bits_per_line else 0)
    extra_padding = -bytes_per_line % 4
    # already 32 bit aligned by luck
    if not extra_padding:
        return bytes
    new_data = [
        bytes[i * bytes_per_line : (i + 1) * bytes_per_line] + b"\x00" * extra_padding
        for i in range(len(bytes) // bytes_per_line)
    ]
    return b"".join(new_data)
Referenced by _toqclass_helper().
fromqimage()
ImageFile.ImageFile PIL.ImageQt.fromqimage (QImage | QPixmap im)
:param im: QImage or PIL ImageQt object
Definition at line 73 of file ImageQt.py.
def fromqimage(im: QImage | QPixmap) -> ImageFile.ImageFile:
    """
    :param im: QImage or PIL ImageQt object
    """
    buffer = QBuffer()
    qt_openmode: object
    if qt_version == "6":
        try:
            qt_openmode = getattr(QIODevice, "OpenModeFlag")
        except AttributeError:
            qt_openmode = getattr(QIODevice, "OpenMode")
    else:
        qt_openmode = QIODevice
    buffer.open(getattr(qt_openmode, "ReadWrite"))
    # preserve alpha channel with png
    # otherwise ppm is more friendly with Image.open
    if im.hasAlphaChannel():
        im.save(buffer, "png")
    else:
        im.save(buffer, "ppm")
    b = BytesIO()
    b.write(buffer.data())
    buffer.close()
    b.seek(0)
    return Image.open(b)
Referenced by fromqpixmap().
fromqpixmap()
ImageFile.ImageFile PIL.ImageQt.fromqpixmap (QPixmap im)
Definition at line 102 of file ImageQt.py.
def fromqpixmap(im: QPixmap) -> ImageFile.ImageFile:
    return fromqimage(im)
References fromqimage().
rgb()
int PIL.ImageQt.rgb (int r, int g, int b, int a = 255)
(Internal) Turns an RGB color into a Qt compatible color integer.
Definition at line 66 of file ImageQt.py.
def rgb(r: int, g: int, b: int, a: int = 255) -> int:
    """(Internal) Turns an RGB color into a Qt compatible color integer."""
    # use qRgb to pack the colors, and then turn the resulting long
    # into a negative integer with the same bitpattern.
    return qRgba(r, g, b, a) & 0xFFFFFFFF
References qRgba.
Referenced by _toqclass_helper().
toqimage()
ImageQt PIL.ImageQt.toqimage (Image.Image | str | QByteArray im)
Definition at line 210 of file ImageQt.py.
def toqimage(im: Image.Image | str | QByteArray) -> ImageQt:
    return ImageQt(im)
Referenced by toqpixmap().
toqpixmap()
QPixmap PIL.ImageQt.toqpixmap (Image.Image | str | QByteArray im)
Definition at line 214 of file ImageQt.py.
def toqpixmap(im: Image.Image | str | QByteArray) -> QPixmap:
    qimage = toqimage(im)
    return getattr(QPixmap, "fromImage")(qimage)
References toqimage().
Variable Documentation
key
PIL.ImageQt.key
Definition at line 46 of file ImageQt.py.
modules
PIL.ImageQt.modules
Definition at line 46 of file ImageQt.py.
QByteArray
type PIL.ImageQt.QByteArray = Union[PyQt6.QtCore.QByteArray, PySide6.QtCore.QByteArray]
Definition at line 34 of file ImageQt.py.
QImage
PIL.ImageQt.QImage = Union[PyQt6.QtGui.QImage, PySide6.QtGui.QImage]
Definition at line 36 of file ImageQt.py.
QIODevice
PIL.ImageQt.QIODevice = Union[PyQt6.QtCore.QIODevice, PySide6.QtCore.QIODevice]
Definition at line 35 of file ImageQt.py.
QPixmap
PIL.ImageQt.QPixmap = Union[PyQt6.QtGui.QPixmap, PySide6.QtGui.QPixmap]
Definition at line 37 of file ImageQt.py.
qRgba
Callable PIL.ImageQt.qRgba [[int, int, int, int], int]
Definition at line 49 of file ImageQt.py.
Referenced by rgb().
qt_is_installed
bool PIL.ImageQt.qt_is_installed = True
Definition at line 58 of file ImageQt.py.
qt_version
PIL.ImageQt.qt_version | None
Definition at line 39 of file ImageQt.py.
qt_versions
list PIL.ImageQt.qt_versions
Initial value:
=  [
    ["6", "PyQt6"],
    ["side6", "PySide6"],
]
Definition at line 40 of file ImageQt.py.
reverse
PIL.ImageQt.reverse
Definition at line 46 of file ImageQt.py.