Read&Watch: astroid.constraint Namespace Reference
astroid.constraint Namespace Reference
Classes
class Constraint
class NoneConstraint
Functions
dict[nodes.If, set[Constraint]] get_constraints (_NameNodes expr, nodes.LocalsDictNodeNG frame)
bool _matches (nodes.NodeNG|bases.Proxy node1, nodes.NodeNG node2)
Iterator[Constraint] _match_constraint (_NameNodes node, nodes.NodeNG expr, bool invert=False)
Variables
_NameNodes = Union[nodes.AssignAttr, nodes.Attribute, nodes.AssignName, nodes.Name]
ALL_CONSTRAINT_CLASSES = frozenset((NoneConstraint,))
Detailed Description
Classes representing different types of constraints on inference values.
Function Documentation
_match_constraint()
Iterator[Constraint] astroid.constraint._match_constraint (_NameNodes node, nodes.NodeNG expr, bool invert = False) protected
Yields all constraint patterns for node that match.
Definition at line 133 of file constraint.py.
) -> Iterator[Constraint]:
    """Yields all constraint patterns for node that match."""
    for constraint_cls in ALL_CONSTRAINT_CLASSES:
        constraint = constraint_cls.match(node, expr, invert)
        if constraint:
            yield constraint
Referenced by get_constraints().
_matches()
bool astroid.constraint._matches (nodes.NodeNG | bases.Proxy node1, nodes.NodeNG node2) protected
Returns True if the two nodes match.
Definition at line 121 of file constraint.py.
def _matches(node1: nodes.NodeNG | bases.Proxy, node2: nodes.NodeNG) -> bool:
    """Returns True if the two nodes match."""
    if isinstance(node1, nodes.Name) and isinstance(node2, nodes.Name):
        return node1.name == node2.name
    if isinstance(node1, nodes.Attribute) and isinstance(node2, nodes.Attribute):
        return node1.attrname == node2.attrname and _matches(node1.expr, node2.expr)
    if isinstance(node1, nodes.Const) and isinstance(node2, nodes.Const):
        return node1.value == node2.value
    return False
References _matches().
Referenced by _matches(), astroid.constraint.NoneConstraint.match(), and astroid.constraint.NoneConstraint.satisfied_by().
get_constraints()
dict[nodes.If, set[Constraint]] astroid.constraint.get_constraints (_NameNodes expr, nodes.LocalsDictNodeNG frame)
Returns the constraints for the given expression.
The returned dictionary maps the node where the constraint was generated to the
corresponding constraint(s).
Constraints are computed statically by analysing the code surrounding expr.
Currently this only supports constraints generated from if conditions.
Definition at line 87 of file constraint.py.
) -> dict[nodes.If, set[Constraint]]:
    """Returns the constraints for the given expression.
    The returned dictionary maps the node where the constraint was generated to the
    corresponding constraint(s).
    Constraints are computed statically by analysing the code surrounding expr.
    Currently this only supports constraints generated from if conditions.
    """
    current_node: nodes.NodeNG | None = expr
    constraints_mapping: dict[nodes.If, set[Constraint]] = {}
    while current_node is not None and current_node is not frame:
        parent = current_node.parent
        if isinstance(parent, nodes.If):
            branch, _ = parent.locate_child(current_node)
            constraints: set[Constraint] | None = None
            if branch == "body":
                constraints = set(_match_constraint(expr, parent.test))
            elif branch == "orelse":
                constraints = set(_match_constraint(expr, parent.test, invert=True))
            if constraints:
                constraints_mapping[parent] = constraints
        current_node = parent
    return constraints_mapping
References _match_constraint().
Variable Documentation
_NameNodes
astroid.constraint._NameNodes = Union[nodes.AssignAttr, nodes.Attribute, nodes.AssignName, nodes.Name] protected
Definition at line 24 of file constraint.py.
ALL_CONSTRAINT_CLASSES
astroid.constraint.ALL_CONSTRAINT_CLASSES = frozenset((NoneConstraint,))
Definition at line 117 of file constraint.py.