Read&Watch: astroid.nodes.node_classes Namespace Reference
astroid.nodes.node_classes Namespace Reference
Classes
class AnnAssign
class Arguments
class Assert
class Assign
class AssignAttr
class AssignName
class AsyncFor
class AsyncWith
class Attribute
class AugAssign
class Await
class BaseContainer
class BinOp
class BoolOp
class Break
class Call
class Compare
class Comprehension
class Const
class Continue
class Decorators
class DelAttr
class Delete
class DelName
class Dict
class DictUnpack
class EmptyNode
class EvaluatedObject
class ExceptHandler
class Expr
class For
class FormattedValue
class Global
class If
class IfExp
class Import
class ImportFrom
class JoinedStr
class Keyword
class List
class Match
class MatchAs
class MatchCase
class MatchClass
class MatchMapping
class MatchOr
class MatchSequence
class MatchSingleton
class MatchStar
class MatchValue
class Name
class NamedExpr
class Nonlocal
class ParamSpec
class Pass
class Pattern
class Raise
class Return
class Set
class Slice
class Starred
class Subscript
class Try
class TryStar
class Tuple
class TypeAlias
class TypeVar
class TypeVarTuple
class UnaryOp
class Unknown
class While
class With
class Yield
class YieldFrom
Functions
bool _is_const (value)
unpack_infer (stmt, InferenceContext|None context=None)
bool are_exclusive (stmt1, stmt2, list[str]|None exceptions=None)
_slice_value (index, InferenceContext|None context=None)
_infer_slice (node, InferenceContext|None context=None)
_container_getitem (instance, elts, index, InferenceContext|None context=None)
_find_arg (argname, args)
str _format_args (args, defaults=None, annotations=None, set[str]|None skippable_names=None)
Generator[InferenceResult, None, InferenceErrorInfo] _infer_attribute (nodes.AssignAttr|nodes.Attribute node, InferenceContext|None context=None, **Any kwargs)
list[NodeNG] _create_basic_elements (Iterable[Any] value, List|Set|Tuple node)
list[tuple[SuccessfulInferenceResult, SuccessfulInferenceResult]] _create_dict_items (Mapping[Any, Any] values, Dict node)
ConstFactoryResult const_factory (Any value)
Variables
_NodesT = typing.TypeVar("_NodesT", bound=NodeNG)
_BadOpMessageT = typing.TypeVar("_BadOpMessageT", bound=util.BadOperationMessage)
AssignedStmtsPossibleNode = Union["List", "Tuple", "AssignName", "AssignAttr", None]
AssignedStmtsCall
InferBinaryOperation
InferLHS
InferUnaryOp = Callable[[_NodesT, str], ConstFactoryResult]
_SLICE_SENTINEL = object()
str DEPRECATED_ARGUMENT_DEFAULT = "DEPRECATED_ARGUMENT_DEFAULT"
dict UNINFERABLE_OPS
dict UNARY_OP_METHOD
str MISSING_VALUE = "{MISSING_VALUE}"
Detailed Description
Module for some node classes. More nodes in scoped_nodes.py
Function Documentation
_container_getitem()
astroid.nodes.node_classes._container_getitem (instance, elts, index, InferenceContext | None context = None) protected
Get a slice or an item, using the given *index*, for the given sequence.
Definition at line 241 of file node_classes.py.
def _container_getitem(instance, elts, index, context: InferenceContext | None = None):
    """Get a slice or an item, using the given *index*, for the given sequence."""
    try:
        if isinstance(index, Slice):
            index_slice = _infer_slice(index, context=context)
            new_cls = instance.__class__()
            new_cls.elts = elts[index_slice]
            new_cls.parent = instance.parent
            return new_cls
        if isinstance(index, Const):
            return elts[index.value]
    except ValueError as exc:
        raise AstroidValueError(
            message="Slice {index!r} cannot index container",
            node=instance,
            index=index,
            context=context,
        ) from exc
    except IndexError as exc:
        raise AstroidIndexError(
            message="Index {index!s} out of range",
            node=instance,
            index=index,
            context=context,
        ) from exc
    except TypeError as exc:
        raise AstroidTypeError(
            message="Type error {error!r}", node=instance, index=index, context=context
        ) from exc
    raise AstroidTypeError(f"Could not use {index} as subscript index")
References _infer_slice().
_create_basic_elements()
list[NodeNG] astroid.nodes.node_classes._create_basic_elements (Iterable[Any] value, List | Set | Tuple node) protected
Create a list of nodes to function as the elements of a new node.
Definition at line 5485 of file node_classes.py.
) -> list[NodeNG]:
    """Create a list of nodes to function as the elements of a new node."""
    elements: list[NodeNG] = []
    for element in value:
        element_node = const_factory(element)
        element_node.parent = node
        elements.append(element_node)
    return elements
References const_factory().
Referenced by const_factory().
_create_dict_items()
list[tuple[SuccessfulInferenceResult, SuccessfulInferenceResult]] astroid.nodes.node_classes._create_dict_items (Mapping[Any, Any] values, Dict node) protected
Create a list of node pairs to function as the items of a new dict node.
Definition at line 5497 of file node_classes.py.
) -> list[tuple[SuccessfulInferenceResult, SuccessfulInferenceResult]]:
    """Create a list of node pairs to function as the items of a new dict node."""
    elements: list[tuple[SuccessfulInferenceResult, SuccessfulInferenceResult]] = []
    for key, value in values.items():
        key_node = const_factory(key)
        key_node.parent = node
        value_node = const_factory(value)
        value_node.parent = node
        elements.append((key_node, value_node))
    return elements
References const_factory().
Referenced by const_factory().
_find_arg()
astroid.nodes.node_classes._find_arg (argname, args) protected
Definition at line 1040 of file node_classes.py.
def _find_arg(argname, args):
    for i, arg in enumerate(args):
        if arg.name == argname:
            return i, arg
    return None, None
Referenced by astroid.nodes.node_classes.Arguments.default_value().
_format_args()
str astroid.nodes.node_classes._format_args (args, defaults = None, annotations = None, set[str] | None skippable_names = None) protected
Definition at line 1047 of file node_classes.py.
) -> str:
    if skippable_names is None:
        skippable_names = set()
    values = []
    if args is None:
        return ""
    if annotations is None:
        annotations = []
    if defaults is not None:
        default_offset = len(args) - len(defaults)
    else:
        default_offset = None
    packed = itertools.zip_longest(args, annotations)
    for i, (arg, annotation) in enumerate(packed):
        if arg.name in skippable_names:
            continue
        if isinstance(arg, Tuple):
            values.append(f"({_format_args(arg.elts)})")
        else:
            argname = arg.name
            default_sep = "="
            if annotation is not None:
                argname += ": " + annotation.as_string()
                default_sep = " = "
            values.append(argname)
            if default_offset is not None and i >= default_offset:
                if defaults[i - default_offset] is not None:
                    values[-1] += default_sep + defaults[i - default_offset].as_string()
    return ", ".join(values)
Referenced by astroid.nodes.node_classes.Arguments.format_args().
_infer_attribute()
Generator[InferenceResult, None, InferenceErrorInfo] astroid.nodes.node_classes._infer_attribute (nodes.AssignAttr | nodes.Attribute node, InferenceContext | None context = None, **Any kwargs) protected
Infer an AssignAttr/Attribute node by using getattr on the associated object.
Definition at line 1081 of file node_classes.py.
) -> Generator[InferenceResult, None, InferenceErrorInfo]:
    """Infer an AssignAttr/Attribute node by using getattr on the associated object."""
    # pylint: disable=import-outside-toplevel
    from astroid.constraint import get_constraints
    from astroid.nodes import ClassDef
    for owner in node.expr.infer(context):
        if isinstance(owner, util.UninferableBase):
            yield owner
            continue
        context = copy_context(context)
        old_boundnode = context.boundnode
        try:
            context.boundnode = owner
            if isinstance(owner, (ClassDef, Instance)):
                frame = owner if isinstance(owner, ClassDef) else owner._proxied
                context.constraints[node.attrname] = get_constraints(node, frame=frame)
            if node.attrname == "argv" and owner.name == "sys":
                # sys.argv will never be inferable during static analysis
                # It's value would be the args passed to the linter itself
                yield util.Uninferable
            else:
                yield from owner.igetattr(node.attrname, context)
        except (
            AttributeInferenceError,
            InferenceError,
            AttributeError,
        ):
            pass
        finally:
            context.boundnode = old_boundnode
    return InferenceErrorInfo(node=node, context=context)
Referenced by astroid.nodes.node_classes.Attribute._infer(), and astroid.nodes.node_classes.AssignAttr.infer_lhs().
_infer_slice()
astroid.nodes.node_classes._infer_slice (node, InferenceContext | None context = None) protected
Definition at line 226 of file node_classes.py.
def _infer_slice(node, context: InferenceContext | None = None):
    lower = _slice_value(node.lower, context)
    upper = _slice_value(node.upper, context)
    step = _slice_value(node.step, context)
    if all(elem is not _SLICE_SENTINEL for elem in (lower, upper, step)):
        return slice(lower, upper, step)
    raise AstroidTypeError(
        message="Could not infer slice used in subscript",
        node=node,
        index=node.parent,
        context=context,
    )
References _slice_value().
Referenced by _container_getitem(), and astroid.nodes.node_classes.Const.getitem().
_is_const()
bool astroid.nodes.node_classes._is_const (value) protected
Definition at line 66 of file node_classes.py.
def _is_const(value) -> bool:
    return isinstance(value, tuple(CONST_CLS))
Referenced by astroid.nodes.node_classes.BaseContainer.from_elements().
_slice_value()
astroid.nodes.node_classes._slice_value (index, InferenceContext | None context = None) protected
Get the value of the given slice index.
Definition at line 199 of file node_classes.py.
def _slice_value(index, context: InferenceContext | None = None):
    """Get the value of the given slice index."""
    if isinstance(index, Const):
        if isinstance(index.value, (int, type(None))):
            return index.value
    elif index is None:
        return None
    else:
        # Try to infer what the index actually is.
        # Since we can't return all the possible values,
        # we'll stop at the first possible value.
        try:
            inferred = next(index.infer(context=context))
        except (InferenceError, StopIteration):
            pass
        else:
            if isinstance(inferred, Const):
                if isinstance(inferred.value, (int, type(None))):
                    return inferred.value
    # Use a sentinel, because None can be a valid
    # value that this function can return,
    # as it is the case for unspecified bounds.
    return _SLICE_SENTINEL
Referenced by _infer_slice().
are_exclusive()
bool astroid.nodes.node_classes.are_exclusive (stmt1, stmt2, list[str] | None exceptions = None)
return true if the two given statements are mutually exclusive
`exceptions` may be a list of exception names. If specified, discard If
branches and check one of the statement is in an exception handler catching
one of the given exceptions.
algorithm :
 1) index stmt1's parents
 2) climb among stmt2's parents until we find a common parent
 3) if the common parent is a If or Try statement, look if nodes are
    in exclusive branches
Definition at line 121 of file node_classes.py.
def are_exclusive(stmt1, stmt2, exceptions: list[str] | None = None) -> bool:
    """return true if the two given statements are mutually exclusive
    `exceptions` may be a list of exception names. If specified, discard If
    branches and check one of the statement is in an exception handler catching
    one of the given exceptions.
    algorithm :
     1) index stmt1's parents
     2) climb among stmt2's parents until we find a common parent
     3) if the common parent is a If or Try statement, look if nodes are
        in exclusive branches
    """
    # index stmt1's parents
    stmt1_parents = {}
    children = {}
    previous = stmt1
    for node in stmt1.node_ancestors():
        stmt1_parents[node] = 1
        children[node] = previous
        previous = node
    # climb among stmt2's parents until we find a common parent
    previous = stmt2
    for node in stmt2.node_ancestors():
        if node in stmt1_parents:
            # if the common parent is a If or Try statement, look if
            # nodes are in exclusive branches
            if isinstance(node, If) and exceptions is None:
                c2attr, c2node = node.locate_child(previous)
                c1attr, c1node = node.locate_child(children[node])
                if "test" in (c1attr, c2attr):
                    # If any node is `If.test`, then it must be inclusive with
                    # the other node (`If.body` and `If.orelse`)
                    return False
                if c1attr != c2attr:
                    # different `If` branches (`If.body` and `If.orelse`)
                    return True
            elif isinstance(node, Try):
                c2attr, c2node = node.locate_child(previous)
                c1attr, c1node = node.locate_child(children[node])
                if c1node is not c2node:
                    first_in_body_caught_by_handlers = (
                        c2attr == "handlers"
                        and c1attr == "body"
                        and previous.catch(exceptions)
                    )
                    second_in_body_caught_by_handlers = (
                        c2attr == "body"
                        and c1attr == "handlers"
                        and children[node].catch(exceptions)
                    )
                    first_in_else_other_in_handlers = (
                        c2attr == "handlers" and c1attr == "orelse"
                    )
                    second_in_else_other_in_handlers = (
                        c2attr == "orelse" and c1attr == "handlers"
                    )
                    if any(
                        (
                            first_in_body_caught_by_handlers,
                            second_in_body_caught_by_handlers,
                            first_in_else_other_in_handlers,
                            second_in_else_other_in_handlers,
                        )
                    ):
                        return True
                elif c2attr == "handlers" and c1attr == "handlers":
                    return previous is not children[node]
            return False
        previous = node
    return False
# getitem() helpers.
const_factory()
ConstFactoryResult astroid.nodes.node_classes.const_factory (Any value)
Return an astroid node for a python value.
Definition at line 5511 of file node_classes.py.
def const_factory(value: Any) -> ConstFactoryResult:
    """Return an astroid node for a python value."""
    assert not isinstance(value, NodeNG)
    # This only handles instances of the CONST types. Any
    # subclasses get inferred as EmptyNode.
    # TODO: See if we should revisit these with the normal builder.
    if value.__class__ not in CONST_CLS:
        node = EmptyNode()
        node.object = value
        return node
    instance: List | Set | Tuple | Dict
    initializer_cls = CONST_CLS[value.__class__]
    if issubclass(initializer_cls, (List, Set, Tuple)):
        instance = initializer_cls(
            lineno=None,
            col_offset=None,
            parent=None,
            end_lineno=None,
            end_col_offset=None,
        )
        instance.postinit(_create_basic_elements(value, instance))
        return instance
    if issubclass(initializer_cls, Dict):
        instance = initializer_cls(
            lineno=None,
            col_offset=None,
            parent=None,
            end_lineno=None,
            end_col_offset=None,
        )
        instance.postinit(_create_dict_items(value, instance))
        return instance
    return Const(value)
References _create_basic_elements(), and _create_dict_items().
Referenced by _create_basic_elements(), _create_dict_items(), astroid.nodes.node_classes.UnaryOp._infer_unaryop(), astroid.nodes.node_classes.Slice._wrap_attribute(), astroid.nodes.node_classes.BaseContainer.from_elements(), and astroid.nodes.node_classes.Const.itered().
unpack_infer()
astroid.nodes.node_classes.unpack_infer (stmt, InferenceContext | None context = None)
recursively generate nodes inferred by the given statement.
If the inferred value is a list or a tuple, recurse on the elements
Definition at line 95 of file node_classes.py.
def unpack_infer(stmt, context: InferenceContext | None = None):
    """recursively generate nodes inferred by the given statement.
    If the inferred value is a list or a tuple, recurse on the elements
    """
    if isinstance(stmt, (List, Tuple)):
        for elt in stmt.elts:
            if elt is util.Uninferable:
                yield elt
                continue
            yield from unpack_infer(elt, context)
        return {"node": stmt, "context": context}
    # if inferred is a final node, return it and stop
    inferred = next(stmt.infer(context), util.Uninferable)
    if inferred is stmt:
        yield inferred
        return {"node": stmt, "context": context}
    # else, infer recursively, except Uninferable object that should be returned as is
    for inferred in stmt.infer(context):
        if isinstance(inferred, util.UninferableBase):
            yield inferred
        else:
            yield from unpack_infer(inferred, context)
    return {"node": stmt, "context": context}
References unpack_infer().
Referenced by unpack_infer().
Variable Documentation
_BadOpMessageT
astroid.nodes.node_classes._BadOpMessageT = typing.TypeVar("_BadOpMessageT", bound=util.BadOperationMessage) protected
Definition at line 71 of file node_classes.py.
_NodesT
astroid.nodes.node_classes._NodesT = typing.TypeVar("_NodesT", bound=NodeNG) protected
Definition at line 70 of file node_classes.py.
_SLICE_SENTINEL
astroid.nodes.node_classes._SLICE_SENTINEL = object() protected
Definition at line 196 of file node_classes.py.
AssignedStmtsCall
astroid.nodes.node_classes.AssignedStmtsCall
Initial value:
=  Callable[
    [
        _NodesT,
        AssignedStmtsPossibleNode,
        Optional[InferenceContext],
        Optional[list[int]],
    ],
    Any,
]
Definition at line 74 of file node_classes.py.
AssignedStmtsPossibleNode
astroid.nodes.node_classes.AssignedStmtsPossibleNode = Union["List", "Tuple", "AssignName", "AssignAttr", None]
Definition at line 73 of file node_classes.py.
DEPRECATED_ARGUMENT_DEFAULT
str astroid.nodes.node_classes.DEPRECATED_ARGUMENT_DEFAULT = "DEPRECATED_ARGUMENT_DEFAULT"
Definition at line 604 of file node_classes.py.
InferBinaryOperation
astroid.nodes.node_classes.InferBinaryOperation
Initial value:
=  Callable[
    [_NodesT, Optional[InferenceContext]],
    Generator[Union[InferenceResult, _BadOpMessageT]],
]
Definition at line 83 of file node_classes.py.
InferLHS
astroid.nodes.node_classes.InferLHS
Initial value:
=  Callable[
    [_NodesT, Optional[InferenceContext]],
    Generator[InferenceResult, None, Optional[InferenceErrorInfo]],
]
Definition at line 87 of file node_classes.py.
InferUnaryOp
astroid.nodes.node_classes.InferUnaryOp = Callable[[_NodesT, str], ConstFactoryResult]
Definition at line 91 of file node_classes.py.
MISSING_VALUE
str astroid.nodes.node_classes.MISSING_VALUE = "{MISSING_VALUE}"
Definition at line 4708 of file node_classes.py.
UNARY_OP_METHOD
dict astroid.nodes.node_classes.UNARY_OP_METHOD
Initial value:
=  {
    "+": "__pos__",
    "-": "__neg__",
    "~": "__invert__",
    "not": None,  # XXX not '__nonzero__'
}
Definition at line 4221 of file node_classes.py.
UNINFERABLE_OPS
dict astroid.nodes.node_classes.UNINFERABLE_OPS
Initial value:
=  {
    "is",
    "is not",
}
Definition at line 1802 of file node_classes.py.