Read&Watch: pip._vendor.platformdirs.unix Namespace Reference
pip._vendor.platformdirs.unix Namespace Reference
Classes
class Unix
Functions
NoReturn getuid ()
str _get_user_media_dir (str env_var, str fallback_tilde_path)
str|None _get_user_dirs_folder (str key)
Detailed Description
Unix.
Function Documentation
_get_user_dirs_folder()
str | None pip._vendor.platformdirs.unix._get_user_dirs_folder (str key) protected
Return directory from user-dirs.dirs config file.
See https://freedesktop.org/wiki/Software/xdg-user-dirs/.
Definition at line 248 of file unix.py.
def _get_user_dirs_folder(key: str) -> str | None:
    """
    Return directory from user-dirs.dirs config file.
    See https://freedesktop.org/wiki/Software/xdg-user-dirs/.
    """
    user_dirs_config_path = Path(Unix().user_config_dir) / "user-dirs.dirs"
    if user_dirs_config_path.exists():
        parser = ConfigParser()
        with user_dirs_config_path.open() as stream:
            # Add fake section header, so ConfigParser doesn't complain
            parser.read_string(f"[top]\n{stream.read()}")
        if key not in parser["top"]:
            return None
        path = parser["top"][key].strip('"')
        # Handle relative home paths
        return path.replace("$HOME", os.path.expanduser("~"))  # noqa: PTH111
    return None
Referenced by _get_user_media_dir().
_get_user_media_dir()
str pip._vendor.platformdirs.unix._get_user_media_dir (str env_var, str fallback_tilde_path) protected
Definition at line 238 of file unix.py.
def _get_user_media_dir(env_var: str, fallback_tilde_path: str) -> str:
    media_dir = _get_user_dirs_folder(env_var)
    if media_dir is None:
        media_dir = os.environ.get(env_var, "").strip()
        if not media_dir:
            media_dir = os.path.expanduser(fallback_tilde_path)  # noqa: PTH111
    return media_dir
References _get_user_dirs_folder().
Referenced by pip._vendor.platformdirs.unix.Unix.user_desktop_dir(), pip._vendor.platformdirs.unix.Unix.user_documents_dir(), pip._vendor.platformdirs.unix.Unix.user_downloads_dir(), pip._vendor.platformdirs.unix.Unix.user_music_dir(), pip._vendor.platformdirs.unix.Unix.user_pictures_dir(), and pip._vendor.platformdirs.unix.Unix.user_videos_dir().
getuid()
NoReturn pip._vendor.platformdirs.unix.getuid ()
Definition at line 15 of file unix.py.
    def getuid() -> NoReturn:
        msg = "should only be used on Unix"
        raise RuntimeError(msg)