Read&Watch: pylint.config.find_default_config_files Namespace Reference
pylint.config.find_default_config_files Namespace Reference
Functions
Path _find_pyproject ()
bool _toml_has_config (Path|str path)
bool _cfg_or_ini_has_config (Path|str path)
Iterator[Path] _yield_default_files ()
Iterator[Path] _find_project_config ()
Iterator[Path] _find_config_in_home_or_environment ()
Iterator[Path] find_default_config_files ()
Variables
tuple RC_NAMES
PYPROJECT_NAME = Path("pyproject.toml")
tuple CONFIG_NAMES = (*RC_NAMES, PYPROJECT_NAME, Path("setup.cfg"), Path("tox.ini"))
Function Documentation
_cfg_or_ini_has_config()
bool pylint.config.find_default_config_files._cfg_or_ini_has_config (Path | str path) protected
Definition at line 58 of file find_default_config_files.py.
def _cfg_or_ini_has_config(path: Path | str) -> bool:
    parser = configparser.ConfigParser()
    try:
        parser.read(path, encoding="utf-8")
    except configparser.Error:
        return False
    return any(
        section == "pylint" or section.startswith("pylint.")
        for section in parser.sections()
    )
Referenced by _yield_default_files().
_find_config_in_home_or_environment()
Iterator[Path] pylint.config.find_default_config_files._find_config_in_home_or_environment () protected
Find a config file in the specified environment var or the home directory.
Definition at line 103 of file find_default_config_files.py.
def _find_config_in_home_or_environment() -> Iterator[Path]:
    """Find a config file in the specified environment var or the home directory."""
    if "PYLINTRC" in os.environ and Path(os.environ["PYLINTRC"]).exists():
        if Path(os.environ["PYLINTRC"]).is_file():
            yield Path(os.environ["PYLINTRC"]).resolve()
    else:
        try:
            user_home = Path.home()
        except RuntimeError:
            # If the home directory does not exist a RuntimeError will be raised
            user_home = None
        if user_home is not None and str(user_home) not in ("~", "/root"):
            home_rc = user_home / ".pylintrc"
            if home_rc.is_file():
                yield home_rc.resolve()
            home_rc = user_home / ".config" / "pylintrc"
            if home_rc.is_file():
                yield home_rc.resolve()
Referenced by find_default_config_files().
_find_project_config()
Iterator[Path] pylint.config.find_default_config_files._find_project_config () protected
Traverse up the directory tree to find a config file.
Stop if no '__init__' is found and thus we are no longer in a package.
Definition at line 88 of file find_default_config_files.py.
def _find_project_config() -> Iterator[Path]:
    """Traverse up the directory tree to find a config file.
    Stop if no '__init__' is found and thus we are no longer in a package.
    """
    if Path("__init__.py").is_file():
        curdir = Path(os.getcwd()).resolve()
        while (curdir / "__init__.py").is_file():
            curdir = curdir.parent
            for rc_name in RC_NAMES:
                rc_path = curdir / rc_name
                if rc_path.is_file():
                    yield rc_path.resolve()
Referenced by find_default_config_files().
_find_pyproject()
Path pylint.config.find_default_config_files._find_pyproject () protected
Search for file pyproject.toml in the parent directories recursively.
It resolves symlinks, so if there is any symlink up in the tree, it does not respect them
Definition at line 28 of file find_default_config_files.py.
def _find_pyproject() -> Path:
    """Search for file pyproject.toml in the parent directories recursively.
    It resolves symlinks, so if there is any symlink up in the tree, it does not respect them
    """
    current_dir = Path.cwd().resolve()
    is_root = False
    while not is_root:
        if (current_dir / PYPROJECT_NAME).is_file():
            return current_dir / PYPROJECT_NAME
        is_root = (
            current_dir == current_dir.parent
            or (current_dir / ".git").is_dir()
            or (current_dir / ".hg").is_dir()
        )
        current_dir = current_dir.parent
    return current_dir
Referenced by find_default_config_files().
_toml_has_config()
bool pylint.config.find_default_config_files._toml_has_config (Path | str path) protected
Definition at line 48 of file find_default_config_files.py.
def _toml_has_config(path: Path | str) -> bool:
    with open(path, mode="rb") as toml_handle:
        try:
            content = tomllib.load(toml_handle)
        except tomllib.TOMLDecodeError as error:
            print(f"Failed to load '{path}': {error}")
            return False
    return "pylint" in content.get("tool", [])
Referenced by _yield_default_files(), and find_default_config_files().
_yield_default_files()
Iterator[Path] pylint.config.find_default_config_files._yield_default_files () protected
Iterate over the default config file names and see if they exist.
Definition at line 70 of file find_default_config_files.py.
def _yield_default_files() -> Iterator[Path]:
    """Iterate over the default config file names and see if they exist."""
    for config_name in CONFIG_NAMES:
        try:
            if config_name.is_file():
                if config_name.suffix == ".toml" and not _toml_has_config(config_name):
                    continue
                if config_name.suffix in {
                    ".cfg",
                    ".ini",
                } and not _cfg_or_ini_has_config(config_name):
                    continue
                yield config_name.resolve()
        except OSError:
            pass
References _cfg_or_ini_has_config(), and _toml_has_config().
Referenced by find_default_config_files().
find_default_config_files()
Iterator[Path] pylint.config.find_default_config_files.find_default_config_files ()
Find all possible config files.
Definition at line 125 of file find_default_config_files.py.
def find_default_config_files() -> Iterator[Path]:
    """Find all possible config files."""
    yield from _yield_default_files()
    try:
        yield from _find_project_config()
    except OSError:
        pass
    try:
        parent_pyproject = _find_pyproject()
        if parent_pyproject.is_file() and _toml_has_config(parent_pyproject):
            yield parent_pyproject.resolve()
    except OSError:
        pass
    try:
        yield from _find_config_in_home_or_environment()
    except OSError:
        pass
    try:
        if os.path.isfile("/etc/pylintrc"):
            yield Path("/etc/pylintrc").resolve()
    except OSError:
        pass
References _find_config_in_home_or_environment(), _find_project_config(), _find_pyproject(), _toml_has_config(), and _yield_default_files().
Variable Documentation
CONFIG_NAMES
tuple pylint.config.find_default_config_files.CONFIG_NAMES = (*RC_NAMES, PYPROJECT_NAME, Path("setup.cfg"), Path("tox.ini"))
Definition at line 25 of file find_default_config_files.py.
PYPROJECT_NAME
pylint.config.find_default_config_files.PYPROJECT_NAME = Path("pyproject.toml")
Definition at line 24 of file find_default_config_files.py.
RC_NAMES
tuple pylint.config.find_default_config_files.RC_NAMES
Initial value:
=  (
    Path("pylintrc"),
    Path("pylintrc.toml"),
    Path(".pylintrc"),
    Path(".pylintrc.toml"),
)
Definition at line 18 of file find_default_config_files.py.