Read&Watch: django.views.decorators.cache Namespace Reference
django.views.decorators.cache Namespace Reference
Functions
cache_page (timeout, *, cache=None, key_prefix=None)
_check_request (request, decorator_name)
cache_control (**kwargs)
never_cache (view_func)
Function Documentation
_check_request()
django.views.decorators.cache._check_request (request, decorator_name) protected
Definition at line 31 of file cache.py.
def _check_request(request, decorator_name):
    # Ensure argument looks like a request.
    if not hasattr(request, "META"):
        raise TypeError(
            f"{decorator_name} didn't receive an HttpRequest. If you are "
            "decorating a classmethod, be sure to use @method_decorator."
        )
Referenced by cache_control(), and never_cache().
cache_control()
django.views.decorators.cache.cache_control (** kwargs)
Definition at line 40 of file cache.py.
def cache_control(**kwargs):
    def _cache_controller(viewfunc):
        if iscoroutinefunction(viewfunc):
            async def _view_wrapper(request, *args, **kw):
                _check_request(request, "cache_control")
                response = await viewfunc(request, *args, **kw)
                patch_cache_control(response, **kwargs)
                return response
        else:
            def _view_wrapper(request, *args, **kw):
                _check_request(request, "cache_control")
                response = viewfunc(request, *args, **kw)
                patch_cache_control(response, **kwargs)
                return response
        return wraps(viewfunc)(_view_wrapper)
    return _cache_controller
References _check_request().
cache_page()
django.views.decorators.cache.cache_page (timeout, * , cache = None, key_prefix = None)
Decorator for views that tries getting the page from the cache and
populates the cache if the page isn't in the cache yet.
The cache is keyed by the URL and some data from the headers.
Additionally there is the key prefix that is used to distinguish different
cache areas in a multi-site setup. You could use the
get_current_site().domain, for example, as that is unique across a Django
project.
Additionally, all headers from the response's Vary header will be taken
into account on caching -- just like the middleware does.
Definition at line 10 of file cache.py.
def cache_page(timeout, *, cache=None, key_prefix=None):
    """
    Decorator for views that tries getting the page from the cache and
    populates the cache if the page isn't in the cache yet.
    The cache is keyed by the URL and some data from the headers.
    Additionally there is the key prefix that is used to distinguish different
    cache areas in a multi-site setup. You could use the
    get_current_site().domain, for example, as that is unique across a Django
    project.
    Additionally, all headers from the response's Vary header will be taken
    into account on caching -- just like the middleware does.
    """
    return decorator_from_middleware_with_args(CacheMiddleware)(
        page_timeout=timeout,
        cache_alias=cache,
        key_prefix=key_prefix,
    )
never_cache()
django.views.decorators.cache.never_cache (view_func)
Decorator that adds headers to a response so that it will never be cached.
Definition at line 63 of file cache.py.
def never_cache(view_func):
    """
    Decorator that adds headers to a response so that it will never be cached.
    """
    if iscoroutinefunction(view_func):
        async def _view_wrapper(request, *args, **kwargs):
            _check_request(request, "never_cache")
            response = await view_func(request, *args, **kwargs)
            add_never_cache_headers(response)
            return response
    else:
        def _view_wrapper(request, *args, **kwargs):
            _check_request(request, "never_cache")
            response = view_func(request, *args, **kwargs)
            add_never_cache_headers(response)
            return response
    return wraps(view_func)(_view_wrapper)
References _check_request().