Read&Watch: django.utils.lorem_ipsum Namespace Reference
django.utils.lorem_ipsum Namespace Reference
Functions
sentence ()
paragraph ()
paragraphs (count, common=True)
words (count, common=True)
Variables
tuple COMMON_P
tuple WORDS
tuple COMMON_WORDS
Detailed Description
Utility functions for generating "lorem ipsum" Latin text.
Function Documentation
paragraph()
django.utils.lorem_ipsum.paragraph ()
Return a randomly generated paragraph of lorem ipsum text.
The paragraph consists of between 1 and 4 sentences, inclusive.
Definition at line 243 of file lorem_ipsum.py.
def paragraph():
    """
    Return a randomly generated paragraph of lorem ipsum text.
    The paragraph consists of between 1 and 4 sentences, inclusive.
    """
    return " ".join(sentence() for i in range(random.randint(1, 4)))
References sentence().
Referenced by paragraphs().
paragraphs()
django.utils.lorem_ipsum.paragraphs (count, common = True)
Return a list of paragraphs as returned by paragraph().
If `common` is True, then the first paragraph will be the standard
'lorem ipsum' paragraph. Otherwise, the first paragraph will be random
Latin text. Either way, subsequent paragraphs will be random Latin text.
Definition at line 252 of file lorem_ipsum.py.
def paragraphs(count, common=True):
    """
    Return a list of paragraphs as returned by paragraph().
    If `common` is True, then the first paragraph will be the standard
    'lorem ipsum' paragraph. Otherwise, the first paragraph will be random
    Latin text. Either way, subsequent paragraphs will be random Latin text.
    """
    paras = []
    for i in range(count):
        if common and i == 0:
            paras.append(COMMON_P)
        else:
            paras.append(paragraph())
    return paras
References paragraph().
sentence()
django.utils.lorem_ipsum.sentence ()
Return a randomly generated sentence of lorem ipsum text.
The first word is capitalized, and the sentence ends in either a period or
question mark. Commas are added at random.
Definition at line 225 of file lorem_ipsum.py.
def sentence():
    """
    Return a randomly generated sentence of lorem ipsum text.
    The first word is capitalized, and the sentence ends in either a period or
    question mark. Commas are added at random.
    """
    # Determine the number of comma-separated sections and number of words in
    # each section for this sentence.
    sections = [
        " ".join(random.sample(WORDS, random.randint(3, 12)))
        for i in range(random.randint(1, 5))
    ]
    s = ", ".join(sections)
    # Convert to sentence case and add end punctuation.
    return "%s%s%s" % (s[0].upper(), s[1:], random.choice("?."))
Referenced by paragraph().
words()
django.utils.lorem_ipsum.words (count, common = True)
Return a string of `count` lorem ipsum words separated by a single space.
If `common` is True, then the first 19 words will be the standard
'lorem ipsum' words. Otherwise, all words will be selected randomly.
Definition at line 269 of file lorem_ipsum.py.
def words(count, common=True):
    """
    Return a string of `count` lorem ipsum words separated by a single space.
    If `common` is True, then the first 19 words will be the standard
    'lorem ipsum' words. Otherwise, all words will be selected randomly.
    """
    word_list = list(COMMON_WORDS) if common else []
    c = len(word_list)
    if count > c:
        count -= c
        while count > 0:
            c = min(count, len(WORDS))
            count -= c
            word_list += random.sample(WORDS, c)
    else:
        word_list = word_list[:count]
    return " ".join(word_list)
Variable Documentation
COMMON_P
tuple django.utils.lorem_ipsum.COMMON_P
Initial value:
=  (
    "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod "
    "tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim "
    "veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea "
    "commodo consequat. Duis aute irure dolor in reprehenderit in voluptate "
    "velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint "
    "occaecat cupidatat non proident, sunt in culpa qui officia deserunt "
    "mollit anim id est laborum."
)
Definition at line 7 of file lorem_ipsum.py.
COMMON_WORDS
tuple django.utils.lorem_ipsum.COMMON_WORDS
Initial value:
=  (
    "lorem",
    "ipsum",
    "dolor",
    "sit",
    "amet",
    "consectetur",
    "adipisicing",
    "elit",
    "sed",
    "do",
    "eiusmod",
    "tempor",
    "incididunt",
    "ut",
    "labore",
    "et",
    "dolore",
    "magna",
    "aliqua",
)
Definition at line 202 of file lorem_ipsum.py.
WORDS
tuple django.utils.lorem_ipsum.WORDS
Definition at line 17 of file lorem_ipsum.py.