Read&Watch: django.core.signing Namespace Reference
django.core.signing Namespace Reference
Classes
class BadSignature
class JSONSerializer
class SignatureExpired
class Signer
class TimestampSigner
Functions
b62_encode (s)
b62_decode (s)
b64_encode (s)
b64_decode (s)
base64_hmac (salt, value, key, algorithm="sha1")
_cookie_signer_key (key)
get_cookie_signer (salt="django.core.signing.get_cookie_signer")
dumps (obj, key=None, salt="django.core.signing", serializer=JSONSerializer, compress=False)
loads (s, key=None, salt="django.core.signing", serializer=JSONSerializer, max_age=None, fallback_keys=None)
Variables
_SEP_UNSAFE = _lazy_re_compile(r"^[A-z0-9-_=]*$")
str BASE62_ALPHABET = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
Detailed Description
Functions for creating and restoring url-safe signed JSON objects.
The format used looks like this:
>>> signing.dumps("hello")
'ImhlbGxvIg:1QaUZC:YIye-ze3TTx7gtSv422nZA4sgmk'
There are two components here, separated by a ':'. The first component is a
URLsafe base64 encoded JSON of the object passed to dumps(). The second
component is a base64 encoded hmac/SHA-256 hash of "$first_component:$secret"
signing.loads(s) checks the signature and returns the deserialized object.
If the signature fails, a BadSignature exception is raised.
>>> signing.loads("ImhlbGxvIg:1QaUZC:YIye-ze3TTx7gtSv422nZA4sgmk")
'hello'
>>> signing.loads("ImhlbGxvIg:1QaUZC:YIye-ze3TTx7gtSv42-modified")
...
BadSignature: Signature "ImhlbGxvIg:1QaUZC:YIye-ze3TTx7gtSv42-modified" does not match
You can optionally compress the JSON prior to base64 encoding it to save
space, using the compress=True argument. This checks if compression actually
helps and only applies compression if the result is a shorter string:
>>> signing.dumps(list(range(1, 20)), compress=True)
'.eJwFwcERACAIwLCF-rCiILN47r-GyZVJsNgkxaFxoDgxcOHGxMKD_T7vhAml:1QaUaL:BA0thEZrp4FQVXIXuOvYJtLJSrQ'
The fact that the string is compressed is signalled by the prefixed '.' at the
start of the base64 JSON.
There are 65 url-safe characters: the 64 used by url-safe base64 and the ':'.
These functions make use of all of them.
Function Documentation
_cookie_signer_key()
django.core.signing._cookie_signer_key (key) protected
Definition at line 104 of file signing.py.
def _cookie_signer_key(key):
    # SECRET_KEYS items may be str or bytes.
    return b"django.http.cookies" + force_bytes(key)
Referenced by get_cookie_signer().
b62_decode()
django.core.signing.b62_decode (s)
Definition at line 76 of file signing.py.
def b62_decode(s):
    if s == "0":
        return 0
    sign = 1
    if s[0] == "-":
        s = s[1:]
        sign = -1
    decoded = 0
    for digit in s:
        decoded = decoded * 62 + BASE62_ALPHABET.index(digit)
    return sign * decoded
Referenced by django.core.signing.TimestampSigner.unsign().
b62_encode()
django.core.signing.b62_encode (s)
Definition at line 64 of file signing.py.
def b62_encode(s):
    if s == 0:
        return "0"
    sign = "-" if s < 0 else ""
    s = abs(s)
    encoded = ""
    while s > 0:
        s, remainder = divmod(s, 62)
        encoded = BASE62_ALPHABET[remainder] + encoded
    return sign + encoded
Referenced by django.core.signing.TimestampSigner.timestamp().
b64_decode()
django.core.signing.b64_decode (s)
Definition at line 93 of file signing.py.
def b64_decode(s):
    pad = b"=" * (-len(s) % 4)
    return base64.urlsafe_b64decode(s + pad)
Referenced by django.core.signing.Signer.unsign_object().
b64_encode()
django.core.signing.b64_encode (s)
Definition at line 89 of file signing.py.
def b64_encode(s):
    return base64.urlsafe_b64encode(s).strip(b"=")
Referenced by base64_hmac(), and django.core.signing.Signer.sign_object().
base64_hmac()
django.core.signing.base64_hmac (salt, value, key, algorithm = "sha1")
Definition at line 98 of file signing.py.
def base64_hmac(salt, value, key, algorithm="sha1"):
    return b64_encode(
        salted_hmac(salt, value, key, algorithm=algorithm).digest()
    ).decode()
References b64_encode().
Referenced by django.core.signing.Signer.signature().
dumps()
django.core.signing.dumps (obj, key = None, salt = "django.core.signing", serializer = JSONSerializer, compress = False)
Return URL-safe, hmac signed base64 compressed JSON string. If key is
None, use settings.SECRET_KEY instead. The hmac algorithm is the default
Signer algorithm.
If compress is True (not the default), check if compressing using zlib can
save some space. Prepend a '.' to signify compression. This is included
in the signature, to protect against zip bombs.
Salt can be used to namespace the hash, so that a signed string is
only valid for a given namespace. Leaving this at the default
value or re-using a salt value across different parts of your
application without good cause is a security risk.
The serializer is expected to return a bytestring.
Definition at line 131 of file signing.py.
):
    """
    Return URL-safe, hmac signed base64 compressed JSON string. If key is
    None, use settings.SECRET_KEY instead. The hmac algorithm is the default
    Signer algorithm.
    If compress is True (not the default), check if compressing using zlib can
    save some space. Prepend a '.' to signify compression. This is included
    in the signature, to protect against zip bombs.
    Salt can be used to namespace the hash, so that a signed string is
    only valid for a given namespace. Leaving this at the default
    value or re-using a salt value across different parts of your
    application without good cause is a security risk.
    The serializer is expected to return a bytestring.
    """
    return TimestampSigner(key=key, salt=salt).sign_object(
        obj, serializer=serializer, compress=compress
    )
Referenced by django.core.signing.Signer.sign_object().
get_cookie_signer()
django.core.signing.get_cookie_signer (salt = "django.core.signing.get_cookie_signer")
Definition at line 109 of file signing.py.
def get_cookie_signer(salt="django.core.signing.get_cookie_signer"):
    Signer = import_string(settings.SIGNING_BACKEND)
    return Signer(
        key=_cookie_signer_key(settings.SECRET_KEY),
        fallback_keys=map(_cookie_signer_key, settings.SECRET_KEY_FALLBACKS),
        salt=salt,
    )
References _cookie_signer_key().
loads()
django.core.signing.loads (s, key = None, salt = "django.core.signing", serializer = JSONSerializer, max_age = None, fallback_keys = None)
Reverse of dumps(), raise BadSignature if signature fails.
The serializer is expected to accept a bytestring.
Definition at line 155 of file signing.py.
):
    """
    Reverse of dumps(), raise BadSignature if signature fails.
    The serializer is expected to accept a bytestring.
    """
    return TimestampSigner(
        key=key, salt=salt, fallback_keys=fallback_keys
    ).unsign_object(
        s,
        serializer=serializer,
        max_age=max_age,
    )
Referenced by django.core.signing.Signer.unsign_object().
Variable Documentation
_SEP_UNSAFE
django.core.signing._SEP_UNSAFE = _lazy_re_compile(r"^[A-z0-9-_=]*$") protected
Definition at line 48 of file signing.py.
BASE62_ALPHABET
str django.core.signing.BASE62_ALPHABET = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
Definition at line 49 of file signing.py.