Read&Watch: django.middleware.csrf Namespace Reference
django.middleware.csrf Namespace Reference
Classes
class CsrfViewMiddleware
class InvalidTokenFormat
class RejectRequest
Functions
_get_failure_view ()
_get_new_csrf_string ()
_mask_cipher_secret (secret)
_unmask_cipher_token (token)
_add_new_csrf_cookie (request)
get_token (request)
rotate_token (request)
_check_token_format (token)
_does_token_match (request_csrf_token, csrf_secret)
Variables
logger = logging.getLogger("django.security.csrf")
invalid_token_chars_re = _lazy_re_compile("[^a-zA-Z0-9]")
str REASON_BAD_ORIGIN = "Origin checking failed - %s does not match any trusted origins."
str REASON_NO_REFERER = "Referer checking failed - no Referer."
str REASON_BAD_REFERER = "Referer checking failed - %s does not match any trusted origins."
str REASON_NO_CSRF_COOKIE = "CSRF cookie not set."
str REASON_CSRF_TOKEN_MISSING = "CSRF token missing."
str REASON_MALFORMED_REFERER = "Referer checking failed - Referer is malformed."
tuple REASON_INSECURE_REFERER
str REASON_INCORRECT_LENGTH = "has incorrect length"
str REASON_INVALID_CHARACTERS = "has invalid characters"
int CSRF_SECRET_LENGTH = 32
int CSRF_TOKEN_LENGTH = 2 * CSRF_SECRET_LENGTH
CSRF_ALLOWED_CHARS = string.ascii_letters + string.digits
str CSRF_SESSION_KEY = "_csrftoken"
Detailed Description
Cross Site Request Forgery Middleware.
This module provides a middleware that implements protection
against request forgeries from other sites.
Function Documentation
_add_new_csrf_cookie()
django.middleware.csrf._add_new_csrf_cookie (request) protected
Generate a new random CSRF_COOKIE value, and add it to request.META.
Definition at line 84 of file csrf.py.
def _add_new_csrf_cookie(request):
    """Generate a new random CSRF_COOKIE value, and add it to request.META."""
    csrf_secret = _get_new_csrf_string()
    request.META.update(
        {
            "CSRF_COOKIE": csrf_secret,
            "CSRF_COOKIE_NEEDS_UPDATE": True,
        }
    )
    return csrf_secret
References _get_new_csrf_string().
Referenced by get_token(), django.middleware.csrf.CsrfViewMiddleware.process_request(), and rotate_token().
_check_token_format()
django.middleware.csrf._check_token_format (token) protected
Raise an InvalidTokenFormat error if the token has an invalid length or
characters that aren't allowed. The token argument can be a CSRF cookie
secret or non-cookie CSRF token, and either masked or unmasked.
Definition at line 130 of file csrf.py.
def _check_token_format(token):
    """
    Raise an InvalidTokenFormat error if the token has an invalid length or
    characters that aren't allowed. The token argument can be a CSRF cookie
    secret or non-cookie CSRF token, and either masked or unmasked.
    """
    if len(token) not in (CSRF_TOKEN_LENGTH, CSRF_SECRET_LENGTH):
        raise InvalidTokenFormat(REASON_INCORRECT_LENGTH)
    # Make sure all characters are in CSRF_ALLOWED_CHARS.
    if invalid_token_chars_re.search(token):
        raise InvalidTokenFormat(REASON_INVALID_CHARACTERS)
Referenced by django.middleware.csrf.CsrfViewMiddleware._check_token(), and django.middleware.csrf.CsrfViewMiddleware._get_secret().
_does_token_match()
django.middleware.csrf._does_token_match (request_csrf_token, csrf_secret) protected
Return whether the given CSRF token matches the given CSRF secret, after
unmasking the token if necessary.
This function assumes that the request_csrf_token argument has been
validated to have the correct length (CSRF_SECRET_LENGTH or
CSRF_TOKEN_LENGTH characters) and allowed characters, and that if it has
length CSRF_TOKEN_LENGTH, it is a masked secret.
Definition at line 143 of file csrf.py.
def _does_token_match(request_csrf_token, csrf_secret):
    """
    Return whether the given CSRF token matches the given CSRF secret, after
    unmasking the token if necessary.
    This function assumes that the request_csrf_token argument has been
    validated to have the correct length (CSRF_SECRET_LENGTH or
    CSRF_TOKEN_LENGTH characters) and allowed characters, and that if it has
    length CSRF_TOKEN_LENGTH, it is a masked secret.
    """
    # Only unmask tokens that are exactly CSRF_TOKEN_LENGTH characters long.
    if len(request_csrf_token) == CSRF_TOKEN_LENGTH:
        request_csrf_token = _unmask_cipher_token(request_csrf_token)
    assert len(request_csrf_token) == CSRF_SECRET_LENGTH
    return constant_time_compare(request_csrf_token, csrf_secret)
References _unmask_cipher_token().
Referenced by django.middleware.csrf.CsrfViewMiddleware._check_token().
_get_failure_view()
django.middleware.csrf._get_failure_view () protected
Return the view to be used for CSRF rejections.
Definition at line 50 of file csrf.py.
def _get_failure_view():
    """Return the view to be used for CSRF rejections."""
    return get_callable(settings.CSRF_FAILURE_VIEW)
Referenced by django.middleware.csrf.CsrfViewMiddleware._reject().
_get_new_csrf_string()
django.middleware.csrf._get_new_csrf_string () protected
Definition at line 55 of file csrf.py.
def _get_new_csrf_string():
    return get_random_string(CSRF_SECRET_LENGTH, allowed_chars=CSRF_ALLOWED_CHARS)
Referenced by _add_new_csrf_cookie(), and _mask_cipher_secret().
_mask_cipher_secret()
django.middleware.csrf._mask_cipher_secret (secret) protected
Given a secret (assumed to be a string of CSRF_ALLOWED_CHARS), generate a
token by adding a mask and applying it to the secret.
Definition at line 59 of file csrf.py.
def _mask_cipher_secret(secret):
    """
    Given a secret (assumed to be a string of CSRF_ALLOWED_CHARS), generate a
    token by adding a mask and applying it to the secret.
    """
    mask = _get_new_csrf_string()
    chars = CSRF_ALLOWED_CHARS
    pairs = zip((chars.index(x) for x in secret), (chars.index(x) for x in mask))
    cipher = "".join(chars[(x + y) % len(chars)] for x, y in pairs)
    return mask + cipher
References _get_new_csrf_string().
Referenced by get_token().
_unmask_cipher_token()
django.middleware.csrf._unmask_cipher_token (token) protected
Given a token (assumed to be a string of CSRF_ALLOWED_CHARS, of length
CSRF_TOKEN_LENGTH, and that its first half is a mask), use it to decrypt
the second half to produce the original secret.
Definition at line 71 of file csrf.py.
def _unmask_cipher_token(token):
    """
    Given a token (assumed to be a string of CSRF_ALLOWED_CHARS, of length
    CSRF_TOKEN_LENGTH, and that its first half is a mask), use it to decrypt
    the second half to produce the original secret.
    """
    mask = token[:CSRF_SECRET_LENGTH]
    token = token[CSRF_SECRET_LENGTH:]
    chars = CSRF_ALLOWED_CHARS
    pairs = zip((chars.index(x) for x in token), (chars.index(x) for x in mask))
    return "".join(chars[x - y] for x, y in pairs)  # Note negative values are ok
Referenced by _does_token_match(), and django.middleware.csrf.CsrfViewMiddleware._get_secret().
get_token()
django.middleware.csrf.get_token (request)
Return the CSRF token required for a POST form. The token is an
alphanumeric value. A new token is created if one is not already set.
A side effect of calling this function is to make the csrf_protect
decorator and the CsrfViewMiddleware add a CSRF cookie and a 'Vary: Cookie'
header to the outgoing response.  For this reason, you may need to use this
function lazily, as is done by the csrf context processor.
Definition at line 96 of file csrf.py.
def get_token(request):
    """
    Return the CSRF token required for a POST form. The token is an
    alphanumeric value. A new token is created if one is not already set.
    A side effect of calling this function is to make the csrf_protect
    decorator and the CsrfViewMiddleware add a CSRF cookie and a 'Vary: Cookie'
    header to the outgoing response.  For this reason, you may need to use this
    function lazily, as is done by the csrf context processor.
    """
    if "CSRF_COOKIE" in request.META:
        csrf_secret = request.META["CSRF_COOKIE"]
        # Since the cookie is being used, flag to send the cookie in
        # process_response() (even if the client already has it) in order to
        # renew the expiry timer.
        request.META["CSRF_COOKIE_NEEDS_UPDATE"] = True
    else:
        csrf_secret = _add_new_csrf_cookie(request)
    return _mask_cipher_secret(csrf_secret)
References _add_new_csrf_cookie(), and _mask_cipher_secret().
rotate_token()
django.middleware.csrf.rotate_token (request)
Change the CSRF token in use for a request - should be done on login
for security purposes.
Definition at line 117 of file csrf.py.
def rotate_token(request):
    """
    Change the CSRF token in use for a request - should be done on login
    for security purposes.
    """
    _add_new_csrf_cookie(request)
References _add_new_csrf_cookie().
Variable Documentation
CSRF_ALLOWED_CHARS
django.middleware.csrf.CSRF_ALLOWED_CHARS = string.ascii_letters + string.digits
Definition at line 46 of file csrf.py.
CSRF_SECRET_LENGTH
int django.middleware.csrf.CSRF_SECRET_LENGTH = 32
Definition at line 44 of file csrf.py.
CSRF_SESSION_KEY
str django.middleware.csrf.CSRF_SESSION_KEY = "_csrftoken"
Definition at line 47 of file csrf.py.
CSRF_TOKEN_LENGTH
int django.middleware.csrf.CSRF_TOKEN_LENGTH = 2 * CSRF_SECRET_LENGTH
Definition at line 45 of file csrf.py.
invalid_token_chars_re
django.middleware.csrf.invalid_token_chars_re = _lazy_re_compile("[^a-zA-Z0-9]")
Definition at line 27 of file csrf.py.
logger
django.middleware.csrf.logger = logging.getLogger("django.security.csrf")
Definition at line 25 of file csrf.py.
REASON_BAD_ORIGIN
str django.middleware.csrf.REASON_BAD_ORIGIN = "Origin checking failed - %s does not match any trusted origins."
Definition at line 29 of file csrf.py.
REASON_BAD_REFERER
str django.middleware.csrf.REASON_BAD_REFERER = "Referer checking failed - %s does not match any trusted origins."
Definition at line 31 of file csrf.py.
REASON_CSRF_TOKEN_MISSING
str django.middleware.csrf.REASON_CSRF_TOKEN_MISSING = "CSRF token missing."
Definition at line 33 of file csrf.py.
REASON_INCORRECT_LENGTH
str django.middleware.csrf.REASON_INCORRECT_LENGTH = "has incorrect length"
Definition at line 41 of file csrf.py.
REASON_INSECURE_REFERER
tuple django.middleware.csrf.REASON_INSECURE_REFERER
Initial value:
=  (
    "Referer checking failed - Referer is insecure while host is secure."
)
Definition at line 35 of file csrf.py.
REASON_INVALID_CHARACTERS
str django.middleware.csrf.REASON_INVALID_CHARACTERS = "has invalid characters"
Definition at line 42 of file csrf.py.
REASON_MALFORMED_REFERER
str django.middleware.csrf.REASON_MALFORMED_REFERER = "Referer checking failed - Referer is malformed."
Definition at line 34 of file csrf.py.
REASON_NO_CSRF_COOKIE
str django.middleware.csrf.REASON_NO_CSRF_COOKIE = "CSRF cookie not set."
Definition at line 32 of file csrf.py.
REASON_NO_REFERER
str django.middleware.csrf.REASON_NO_REFERER = "Referer checking failed - no Referer."
Definition at line 30 of file csrf.py.