Read&Watch: django.contrib.staticfiles.finders Namespace Reference
django.contrib.staticfiles.finders Namespace Reference
Classes
class AppDirectoriesFinder
class BaseFinder
class BaseStorageFinder
class DefaultStorageFinder
class FileSystemFinder
Functions
find (path, all=False)
get_finders ()
get_finder (import_path)
Variables
list searched_locations = []
Function Documentation
find()
django.contrib.staticfiles.finders.find (path, all = False)
Find a static file with the given path using all enabled finders.
If ``all`` is ``False`` (default), return the first matching
absolute path (or ``None`` if no match). Otherwise return a list.
Definition at line 288 of file finders.py.
def find(path, all=False):
    """
    Find a static file with the given path using all enabled finders.
    If ``all`` is ``False`` (default), return the first matching
    absolute path (or ``None`` if no match). Otherwise return a list.
    """
    searched_locations[:] = []
    matches = []
    for finder in get_finders():
        result = finder.find(path, all=all)
        if not all and result:
            return result
        if not isinstance(result, (list, tuple)):
            result = [result]
        matches.extend(result)
    if matches:
        return matches
    # No match.
    return [] if all else None
References get_finders().
get_finder()
django.contrib.staticfiles.finders.get_finder (import_path)
Import the staticfiles finder class described by import_path, where
import_path is the full Python path to the class.
Definition at line 316 of file finders.py.
def get_finder(import_path):
    """
    Import the staticfiles finder class described by import_path, where
    import_path is the full Python path to the class.
    """
    Finder = import_string(import_path)
    if not issubclass(Finder, BaseFinder):
        raise ImproperlyConfigured(
            'Finder "%s" is not a subclass of "%s"' % (Finder, BaseFinder)
        )
    return Finder()
Referenced by get_finders().
get_finders()
django.contrib.staticfiles.finders.get_finders ()
Definition at line 310 of file finders.py.
def get_finders():
    for finder_path in settings.STATICFILES_FINDERS:
        yield get_finder(finder_path)
@functools.cache
References get_finder().
Referenced by find().
Variable Documentation
searched_locations
list django.contrib.staticfiles.finders.searched_locations = []
Definition at line 15 of file finders.py.