Read&Watch: django.db.backends.sqlite3._functions Namespace Reference
django.db.backends.sqlite3._functions Namespace Reference
Classes
class ListAggregate
class StdDevPop
class StdDevSamp
class VarPop
class VarSamp
Functions
register (connection)
_sqlite_datetime_parse (dt, tzname=None, conn_tzname=None)
_sqlite_date_trunc (lookup_type, dt, tzname, conn_tzname)
_sqlite_time_trunc (lookup_type, dt, tzname, conn_tzname)
_sqlite_datetime_cast_date (dt, tzname, conn_tzname)
_sqlite_datetime_cast_time (dt, tzname, conn_tzname)
_sqlite_datetime_extract (lookup_type, dt, tzname=None, conn_tzname=None)
_sqlite_datetime_trunc (lookup_type, dt, tzname, conn_tzname)
_sqlite_time_extract (lookup_type, dt)
_sqlite_prepare_dtdelta_param (conn, param)
_sqlite_format_dtdelta (connector, lhs, rhs)
_sqlite_time_diff (lhs, rhs)
_sqlite_timestamp_diff (lhs, rhs)
_sqlite_regexp (pattern, string)
_sqlite_acos (x)
_sqlite_asin (x)
_sqlite_atan (x)
_sqlite_atan2 (y, x)
_sqlite_bitxor (x, y)
_sqlite_ceiling (x)
_sqlite_cos (x)
_sqlite_cot (x)
_sqlite_degrees (x)
_sqlite_exp (x)
_sqlite_floor (x)
_sqlite_ln (x)
_sqlite_log (base, x)
_sqlite_lpad (text, length, fill_text)
_sqlite_md5 (text)
_sqlite_mod (x, y)
_sqlite_pi ()
_sqlite_power (x, y)
_sqlite_radians (x)
_sqlite_repeat (text, count)
_sqlite_reverse (text)
_sqlite_rpad (text, length, fill_text)
_sqlite_sha1 (text)
_sqlite_sha224 (text)
_sqlite_sha256 (text)
_sqlite_sha384 (text)
_sqlite_sha512 (text)
_sqlite_sign (x)
_sqlite_sin (x)
_sqlite_sqrt (x)
_sqlite_tan (x)
Detailed Description
Implementations of SQL functions for SQLite.
Function Documentation
_sqlite_acos()
django.db.backends.sqlite3._functions._sqlite_acos (x) protected
Definition at line 310 of file _functions.py.
def _sqlite_acos(x):
    if x is None:
        return None
    return acos(x)
_sqlite_asin()
django.db.backends.sqlite3._functions._sqlite_asin (x) protected
Definition at line 316 of file _functions.py.
def _sqlite_asin(x):
    if x is None:
        return None
    return asin(x)
_sqlite_atan()
django.db.backends.sqlite3._functions._sqlite_atan (x) protected
Definition at line 322 of file _functions.py.
def _sqlite_atan(x):
    if x is None:
        return None
    return atan(x)
_sqlite_atan2()
django.db.backends.sqlite3._functions._sqlite_atan2 (y, x) protected
Definition at line 328 of file _functions.py.
def _sqlite_atan2(y, x):
    if y is None or x is None:
        return None
    return atan2(y, x)
_sqlite_bitxor()
django.db.backends.sqlite3._functions._sqlite_bitxor (x, y) protected
Definition at line 334 of file _functions.py.
def _sqlite_bitxor(x, y):
    if x is None or y is None:
        return None
    return x ^ y
_sqlite_ceiling()
django.db.backends.sqlite3._functions._sqlite_ceiling (x) protected
Definition at line 340 of file _functions.py.
def _sqlite_ceiling(x):
    if x is None:
        return None
    return ceil(x)
_sqlite_cos()
django.db.backends.sqlite3._functions._sqlite_cos (x) protected
Definition at line 346 of file _functions.py.
def _sqlite_cos(x):
    if x is None:
        return None
    return cos(x)
_sqlite_cot()
django.db.backends.sqlite3._functions._sqlite_cot (x) protected
Definition at line 352 of file _functions.py.
def _sqlite_cot(x):
    if x is None:
        return None
    return 1 / tan(x)
_sqlite_date_trunc()
django.db.backends.sqlite3._functions._sqlite_date_trunc (lookup_type, dt, tzname, conn_tzname) protected
Definition at line 128 of file _functions.py.
def _sqlite_date_trunc(lookup_type, dt, tzname, conn_tzname):
    dt = _sqlite_datetime_parse(dt, tzname, conn_tzname)
    if dt is None:
        return None
    if lookup_type == "year":
        return f"{dt.year:04d}-01-01"
    elif lookup_type == "quarter":
        month_in_quarter = dt.month - (dt.month - 1) % 3
        return f"{dt.year:04d}-{month_in_quarter:02d}-01"
    elif lookup_type == "month":
        return f"{dt.year:04d}-{dt.month:02d}-01"
    elif lookup_type == "week":
        dt -= timedelta(days=dt.weekday())
        return f"{dt.year:04d}-{dt.month:02d}-{dt.day:02d}"
    elif lookup_type == "day":
        return f"{dt.year:04d}-{dt.month:02d}-{dt.day:02d}"
    raise ValueError(f"Unsupported lookup type: {lookup_type!r}")
References _sqlite_datetime_parse().
_sqlite_datetime_cast_date()
django.db.backends.sqlite3._functions._sqlite_datetime_cast_date (dt, tzname, conn_tzname) protected
Definition at line 167 of file _functions.py.
def _sqlite_datetime_cast_date(dt, tzname, conn_tzname):
    dt = _sqlite_datetime_parse(dt, tzname, conn_tzname)
    if dt is None:
        return None
    return dt.date().isoformat()
References _sqlite_datetime_parse().
_sqlite_datetime_cast_time()
django.db.backends.sqlite3._functions._sqlite_datetime_cast_time (dt, tzname, conn_tzname) protected
Definition at line 174 of file _functions.py.
def _sqlite_datetime_cast_time(dt, tzname, conn_tzname):
    dt = _sqlite_datetime_parse(dt, tzname, conn_tzname)
    if dt is None:
        return None
    return dt.time().isoformat()
References _sqlite_datetime_parse().
_sqlite_datetime_extract()
django.db.backends.sqlite3._functions._sqlite_datetime_extract (lookup_type, dt, tzname = None, conn_tzname = None) protected
Definition at line 181 of file _functions.py.
def _sqlite_datetime_extract(lookup_type, dt, tzname=None, conn_tzname=None):
    dt = _sqlite_datetime_parse(dt, tzname, conn_tzname)
    if dt is None:
        return None
    if lookup_type == "week_day":
        return (dt.isoweekday() % 7) + 1
    elif lookup_type == "iso_week_day":
        return dt.isoweekday()
    elif lookup_type == "week":
        return dt.isocalendar().week
    elif lookup_type == "quarter":
        return ceil(dt.month / 3)
    elif lookup_type == "iso_year":
        return dt.isocalendar().year
    else:
        return getattr(dt, lookup_type)
References _sqlite_datetime_parse().
_sqlite_datetime_parse()
django.db.backends.sqlite3._functions._sqlite_datetime_parse (dt, tzname = None, conn_tzname = None) protected
Definition at line 106 of file _functions.py.
def _sqlite_datetime_parse(dt, tzname=None, conn_tzname=None):
    if dt is None:
        return None
    try:
        dt = typecast_timestamp(dt)
    except (TypeError, ValueError):
        return None
    if conn_tzname:
        dt = dt.replace(tzinfo=zoneinfo.ZoneInfo(conn_tzname))
    if tzname is not None and tzname != conn_tzname:
        tzname, sign, offset = split_tzname_delta(tzname)
        if offset:
            hours, minutes = offset.split(":")
            offset_delta = timedelta(hours=int(hours), minutes=int(minutes))
            dt += offset_delta if sign == "+" else -offset_delta
        # The tzname may originally be just the offset e.g. "+3:00",
        # which becomes an empty string after splitting the sign and offset.
        # In this case, use the conn_tzname as fallback.
        dt = timezone.localtime(dt, zoneinfo.ZoneInfo(tzname or conn_tzname))
    return dt
Referenced by _sqlite_date_trunc(), _sqlite_datetime_cast_date(), _sqlite_datetime_cast_time(), _sqlite_datetime_extract(), _sqlite_datetime_trunc(), and _sqlite_time_trunc().
_sqlite_datetime_trunc()
django.db.backends.sqlite3._functions._sqlite_datetime_trunc (lookup_type, dt, tzname, conn_tzname) protected
Definition at line 199 of file _functions.py.
def _sqlite_datetime_trunc(lookup_type, dt, tzname, conn_tzname):
    dt = _sqlite_datetime_parse(dt, tzname, conn_tzname)
    if dt is None:
        return None
    if lookup_type == "year":
        return f"{dt.year:04d}-01-01 00:00:00"
    elif lookup_type == "quarter":
        month_in_quarter = dt.month - (dt.month - 1) % 3
        return f"{dt.year:04d}-{month_in_quarter:02d}-01 00:00:00"
    elif lookup_type == "month":
        return f"{dt.year:04d}-{dt.month:02d}-01 00:00:00"
    elif lookup_type == "week":
        dt -= timedelta(days=dt.weekday())
        return f"{dt.year:04d}-{dt.month:02d}-{dt.day:02d} 00:00:00"
    elif lookup_type == "day":
        return f"{dt.year:04d}-{dt.month:02d}-{dt.day:02d} 00:00:00"
    elif lookup_type == "hour":
        return f"{dt.year:04d}-{dt.month:02d}-{dt.day:02d} {dt.hour:02d}:00:00"
    elif lookup_type == "minute":
        return (
            f"{dt.year:04d}-{dt.month:02d}-{dt.day:02d} "
            f"{dt.hour:02d}:{dt.minute:02d}:00"
        )
    elif lookup_type == "second":
        return (
            f"{dt.year:04d}-{dt.month:02d}-{dt.day:02d} "
            f"{dt.hour:02d}:{dt.minute:02d}:{dt.second:02d}"
        )
    raise ValueError(f"Unsupported lookup type: {lookup_type!r}")
References _sqlite_datetime_parse().
_sqlite_degrees()
django.db.backends.sqlite3._functions._sqlite_degrees (x) protected
Definition at line 358 of file _functions.py.
def _sqlite_degrees(x):
    if x is None:
        return None
    return degrees(x)
_sqlite_exp()
django.db.backends.sqlite3._functions._sqlite_exp (x) protected
Definition at line 364 of file _functions.py.
def _sqlite_exp(x):
    if x is None:
        return None
    return exp(x)
_sqlite_floor()
django.db.backends.sqlite3._functions._sqlite_floor (x) protected
Definition at line 370 of file _functions.py.
def _sqlite_floor(x):
    if x is None:
        return None
    return floor(x)
_sqlite_format_dtdelta()
django.db.backends.sqlite3._functions._sqlite_format_dtdelta (connector, lhs, rhs) protected
LHS and RHS can be either:
- An integer number of microseconds
- A string representing a datetime
- A scalar value, e.g. float
Definition at line 249 of file _functions.py.
def _sqlite_format_dtdelta(connector, lhs, rhs):
    """
    LHS and RHS can be either:
    - An integer number of microseconds
    - A string representing a datetime
    - A scalar value, e.g. float
    """
    if connector is None or lhs is None or rhs is None:
        return None
    connector = connector.strip()
    try:
        real_lhs = _sqlite_prepare_dtdelta_param(connector, lhs)
        real_rhs = _sqlite_prepare_dtdelta_param(connector, rhs)
    except (ValueError, TypeError):
        return None
    if connector == "+":
        # typecast_timestamp() returns a date or a datetime without timezone.
        # It will be formatted as "%Y-%m-%d" or "%Y-%m-%d %H:%M:%S[.%f]"
        out = str(real_lhs + real_rhs)
    elif connector == "-":
        out = str(real_lhs - real_rhs)
    elif connector == "*":
        out = real_lhs * real_rhs
    else:
        out = real_lhs / real_rhs
    return out
References _sqlite_prepare_dtdelta_param().
_sqlite_ln()
django.db.backends.sqlite3._functions._sqlite_ln (x) protected
Definition at line 376 of file _functions.py.
def _sqlite_ln(x):
    if x is None:
        return None
    return log(x)
_sqlite_log()
django.db.backends.sqlite3._functions._sqlite_log (base, x) protected
Definition at line 382 of file _functions.py.
def _sqlite_log(base, x):
    if base is None or x is None:
        return None
    # Arguments reversed to match SQL standard.
    return log(x, base)
_sqlite_lpad()
django.db.backends.sqlite3._functions._sqlite_lpad (text, length, fill_text) protected
Definition at line 389 of file _functions.py.
def _sqlite_lpad(text, length, fill_text):
    if text is None or length is None or fill_text is None:
        return None
    delta = length - len(text)
    if delta <= 0:
        return text[:length]
    return (fill_text * length)[:delta] + text
_sqlite_md5()
django.db.backends.sqlite3._functions._sqlite_md5 (text) protected
Definition at line 398 of file _functions.py.
def _sqlite_md5(text):
    if text is None:
        return None
    return md5(text.encode()).hexdigest()
_sqlite_mod()
django.db.backends.sqlite3._functions._sqlite_mod (x, y) protected
Definition at line 404 of file _functions.py.
def _sqlite_mod(x, y):
    if x is None or y is None:
        return None
    return fmod(x, y)
_sqlite_pi()
django.db.backends.sqlite3._functions._sqlite_pi () protected
Definition at line 410 of file _functions.py.
def _sqlite_pi():
    return pi
_sqlite_power()
django.db.backends.sqlite3._functions._sqlite_power (x, y) protected
Definition at line 414 of file _functions.py.
def _sqlite_power(x, y):
    if x is None or y is None:
        return None
    return x**y
_sqlite_prepare_dtdelta_param()
django.db.backends.sqlite3._functions._sqlite_prepare_dtdelta_param (conn, param) protected
Definition at line 240 of file _functions.py.
def _sqlite_prepare_dtdelta_param(conn, param):
    if conn in ["+", "-"]:
        if isinstance(param, int):
            return timedelta(0, 0, param)
        else:
            return typecast_timestamp(param)
    return param
Referenced by _sqlite_format_dtdelta().
_sqlite_radians()
django.db.backends.sqlite3._functions._sqlite_radians (x) protected
Definition at line 420 of file _functions.py.
def _sqlite_radians(x):
    if x is None:
        return None
    return radians(x)
_sqlite_regexp()
django.db.backends.sqlite3._functions._sqlite_regexp (pattern, string) protected
Definition at line 302 of file _functions.py.
def _sqlite_regexp(pattern, string):
    if pattern is None or string is None:
        return None
    if not isinstance(string, str):
        string = str(string)
    return bool(re_search(pattern, string))
_sqlite_repeat()
django.db.backends.sqlite3._functions._sqlite_repeat (text, count) protected
Definition at line 426 of file _functions.py.
def _sqlite_repeat(text, count):
    if text is None or count is None:
        return None
    return text * count
_sqlite_reverse()
django.db.backends.sqlite3._functions._sqlite_reverse (text) protected
Definition at line 432 of file _functions.py.
def _sqlite_reverse(text):
    if text is None:
        return None
    return text[::-1]
_sqlite_rpad()
django.db.backends.sqlite3._functions._sqlite_rpad (text, length, fill_text) protected
Definition at line 438 of file _functions.py.
def _sqlite_rpad(text, length, fill_text):
    if text is None or length is None or fill_text is None:
        return None
    return (text + fill_text * length)[:length]
_sqlite_sha1()
django.db.backends.sqlite3._functions._sqlite_sha1 (text) protected
Definition at line 444 of file _functions.py.
def _sqlite_sha1(text):
    if text is None:
        return None
    return sha1(text.encode()).hexdigest()
_sqlite_sha224()
django.db.backends.sqlite3._functions._sqlite_sha224 (text) protected
Definition at line 450 of file _functions.py.
def _sqlite_sha224(text):
    if text is None:
        return None
    return sha224(text.encode()).hexdigest()
_sqlite_sha256()
django.db.backends.sqlite3._functions._sqlite_sha256 (text) protected
Definition at line 456 of file _functions.py.
def _sqlite_sha256(text):
    if text is None:
        return None
    return sha256(text.encode()).hexdigest()
_sqlite_sha384()
django.db.backends.sqlite3._functions._sqlite_sha384 (text) protected
Definition at line 462 of file _functions.py.
def _sqlite_sha384(text):
    if text is None:
        return None
    return sha384(text.encode()).hexdigest()
_sqlite_sha512()
django.db.backends.sqlite3._functions._sqlite_sha512 (text) protected
Definition at line 468 of file _functions.py.
def _sqlite_sha512(text):
    if text is None:
        return None
    return sha512(text.encode()).hexdigest()
_sqlite_sign()
django.db.backends.sqlite3._functions._sqlite_sign (x) protected
Definition at line 474 of file _functions.py.
def _sqlite_sign(x):
    if x is None:
        return None
    return (x > 0) - (x < 0)
_sqlite_sin()
django.db.backends.sqlite3._functions._sqlite_sin (x) protected
Definition at line 480 of file _functions.py.
def _sqlite_sin(x):
    if x is None:
        return None
    return sin(x)
_sqlite_sqrt()
django.db.backends.sqlite3._functions._sqlite_sqrt (x) protected
Definition at line 486 of file _functions.py.
def _sqlite_sqrt(x):
    if x is None:
        return None
    return sqrt(x)
_sqlite_tan()
django.db.backends.sqlite3._functions._sqlite_tan (x) protected
Definition at line 492 of file _functions.py.
def _sqlite_tan(x):
    if x is None:
        return None
    return tan(x)
_sqlite_time_diff()
django.db.backends.sqlite3._functions._sqlite_time_diff (lhs, rhs) protected
Definition at line 277 of file _functions.py.
def _sqlite_time_diff(lhs, rhs):
    if lhs is None or rhs is None:
        return None
    left = typecast_time(lhs)
    right = typecast_time(rhs)
    return (
        (left.hour * 60 * 60 * 1000000)
        + (left.minute * 60 * 1000000)
        + (left.second * 1000000)
        + (left.microsecond)
        - (right.hour * 60 * 60 * 1000000)
        - (right.minute * 60 * 1000000)
        - (right.second * 1000000)
        - (right.microsecond)
    )
_sqlite_time_extract()
django.db.backends.sqlite3._functions._sqlite_time_extract (lookup_type, dt) protected
Definition at line 230 of file _functions.py.
def _sqlite_time_extract(lookup_type, dt):
    if dt is None:
        return None
    try:
        dt = typecast_time(dt)
    except (ValueError, TypeError):
        return None
    return getattr(dt, lookup_type)
_sqlite_time_trunc()
django.db.backends.sqlite3._functions._sqlite_time_trunc (lookup_type, dt, tzname, conn_tzname) protected
Definition at line 147 of file _functions.py.
def _sqlite_time_trunc(lookup_type, dt, tzname, conn_tzname):
    if dt is None:
        return None
    dt_parsed = _sqlite_datetime_parse(dt, tzname, conn_tzname)
    if dt_parsed is None:
        try:
            dt = typecast_time(dt)
        except (ValueError, TypeError):
            return None
    else:
        dt = dt_parsed
    if lookup_type == "hour":
        return f"{dt.hour:02d}:00:00"
    elif lookup_type == "minute":
        return f"{dt.hour:02d}:{dt.minute:02d}:00"
    elif lookup_type == "second":
        return f"{dt.hour:02d}:{dt.minute:02d}:{dt.second:02d}"
    raise ValueError(f"Unsupported lookup type: {lookup_type!r}")
References _sqlite_datetime_parse().
_sqlite_timestamp_diff()
django.db.backends.sqlite3._functions._sqlite_timestamp_diff (lhs, rhs) protected
Definition at line 294 of file _functions.py.
def _sqlite_timestamp_diff(lhs, rhs):
    if lhs is None or rhs is None:
        return None
    left = typecast_timestamp(lhs)
    right = typecast_timestamp(rhs)
    return duration_microseconds(left - right)
register()
django.db.backends.sqlite3._functions.register (connection)
Definition at line 40 of file _functions.py.
def register(connection):
    create_deterministic_function = functools.partial(
        connection.create_function,
        deterministic=True,
    )
    create_deterministic_function("django_date_extract", 2, _sqlite_datetime_extract)
    create_deterministic_function("django_date_trunc", 4, _sqlite_date_trunc)
    create_deterministic_function(
        "django_datetime_cast_date", 3, _sqlite_datetime_cast_date
    )
    create_deterministic_function(
        "django_datetime_cast_time", 3, _sqlite_datetime_cast_time
    )
    create_deterministic_function(
        "django_datetime_extract", 4, _sqlite_datetime_extract
    )
    create_deterministic_function("django_datetime_trunc", 4, _sqlite_datetime_trunc)
    create_deterministic_function("django_time_extract", 2, _sqlite_time_extract)
    create_deterministic_function("django_time_trunc", 4, _sqlite_time_trunc)
    create_deterministic_function("django_time_diff", 2, _sqlite_time_diff)
    create_deterministic_function("django_timestamp_diff", 2, _sqlite_timestamp_diff)
    create_deterministic_function("django_format_dtdelta", 3, _sqlite_format_dtdelta)
    create_deterministic_function("regexp", 2, _sqlite_regexp)
    create_deterministic_function("BITXOR", 2, _sqlite_bitxor)
    create_deterministic_function("COT", 1, _sqlite_cot)
    create_deterministic_function("LPAD", 3, _sqlite_lpad)
    create_deterministic_function("MD5", 1, _sqlite_md5)
    create_deterministic_function("REPEAT", 2, _sqlite_repeat)
    create_deterministic_function("REVERSE", 1, _sqlite_reverse)
    create_deterministic_function("RPAD", 3, _sqlite_rpad)
    create_deterministic_function("SHA1", 1, _sqlite_sha1)
    create_deterministic_function("SHA224", 1, _sqlite_sha224)
    create_deterministic_function("SHA256", 1, _sqlite_sha256)
    create_deterministic_function("SHA384", 1, _sqlite_sha384)
    create_deterministic_function("SHA512", 1, _sqlite_sha512)
    create_deterministic_function("SIGN", 1, _sqlite_sign)
    # Don't use the built-in RANDOM() function because it returns a value
    # in the range [-1 * 2^63, 2^63 - 1] instead of [0, 1).
    connection.create_function("RAND", 0, random.random)
    connection.create_aggregate("STDDEV_POP", 1, StdDevPop)
    connection.create_aggregate("STDDEV_SAMP", 1, StdDevSamp)
    connection.create_aggregate("VAR_POP", 1, VarPop)
    connection.create_aggregate("VAR_SAMP", 1, VarSamp)
    # Some math functions are enabled by default in SQLite 3.35+.
    sql = "select sqlite_compileoption_used('ENABLE_MATH_FUNCTIONS')"
    if not connection.execute(sql).fetchone()[0]:
        create_deterministic_function("ACOS", 1, _sqlite_acos)
        create_deterministic_function("ASIN", 1, _sqlite_asin)
        create_deterministic_function("ATAN", 1, _sqlite_atan)
        create_deterministic_function("ATAN2", 2, _sqlite_atan2)
        create_deterministic_function("CEILING", 1, _sqlite_ceiling)
        create_deterministic_function("COS", 1, _sqlite_cos)
        create_deterministic_function("DEGREES", 1, _sqlite_degrees)
        create_deterministic_function("EXP", 1, _sqlite_exp)
        create_deterministic_function("FLOOR", 1, _sqlite_floor)
        create_deterministic_function("LN", 1, _sqlite_ln)
        create_deterministic_function("LOG", 2, _sqlite_log)
        create_deterministic_function("MOD", 2, _sqlite_mod)
        create_deterministic_function("PI", 0, _sqlite_pi)
        create_deterministic_function("POWER", 2, _sqlite_power)
        create_deterministic_function("RADIANS", 1, _sqlite_radians)
        create_deterministic_function("SIN", 1, _sqlite_sin)
        create_deterministic_function("SQRT", 1, _sqlite_sqrt)
        create_deterministic_function("TAN", 1, _sqlite_tan)