Read&Watch: dill.tests.test_recursive Namespace Reference
dill.tests.test_recursive Namespace Reference
Classes
class Machine
class Machine2
class Model
class obj1
class obj2
class obj3
class obj4
class SubMachine
Functions
copy (obj, byref=False, recurse=False)
test_super ()
get_trigger (model)
test_partial ()
test_partials ()
test_circular_reference ()
f ()
test_function_cells ()
fib (n)
test_recursive_function ()
collection_function_recursion ()
test_collection_function_recursion ()
Function Documentation
collection_function_recursion()
dill.tests.test_recursive.collection_function_recursion ()
Definition at line 155 of file test_recursive.py.
def collection_function_recursion():
    d = {}
    def g():
        return d
    d['g'] = g
    return g
Referenced by test_collection_function_recursion().
copy()
dill.tests.test_recursive.copy (obj, byref = False, recurse = False)
Definition at line 13 of file test_recursive.py.
def copy(obj, byref=False, recurse=False):
    if byref:
        try:
            return dill.copy(obj, byref=byref, recurse=recurse)
        except Exception:
            pass
        else:
            raise AssertionError('Copy of %s with byref=True should have given a warning!' % (obj,))
        warnings.simplefilter('ignore')
        val = dill.copy(obj, byref=byref, recurse=recurse)
        warnings.simplefilter('error')
        return val
    else:
        return dill.copy(obj, byref=byref, recurse=recurse)
Referenced by test_circular_reference(), test_collection_function_recursion(), test_function_cells(), test_partials(), test_recursive_function(), and test_super().
f()
dill.tests.test_recursive.f ()
Definition at line 119 of file test_recursive.py.
def f():
    def g():
       return g
    return g
Referenced by test_function_cells().
fib()
dill.tests.test_recursive.fib (n)
Definition at line 129 of file test_recursive.py.
def fib(n):
    assert n >= 0
    if n <= 1:
        return n
    else:
        return fib(n-1) + fib(n-2)
References fib().
Referenced by fib().
get_trigger()
dill.tests.test_recursive.get_trigger (model)
Definition at line 61 of file test_recursive.py.
def get_trigger(model):
    pass
test_circular_reference()
dill.tests.test_recursive.test_circular_reference ()
Definition at line 112 of file test_recursive.py.
def test_circular_reference():
    assert copy(obj4())
    obj4_copy = dill.loads(dill.dumps(obj4()))
    assert type(obj4_copy) is type(obj4_copy).__init__.__closure__[0].cell_contents
    assert type(obj4_copy.b) is type(obj4_copy.b).__init__.__closure__[0].cell_contents
References copy().
Referenced by test_collection_function_recursion().
test_collection_function_recursion()
dill.tests.test_recursive.test_collection_function_recursion ()
Definition at line 163 of file test_recursive.py.
def test_collection_function_recursion():
    g = copy(collection_function_recursion())
    assert g()['g'] is g
References collection_function_recursion(), copy(), test_circular_reference(), test_collection_function_recursion(), test_function_cells(), test_partial(), test_partials(), test_recursive_function(), and test_super().
Referenced by test_collection_function_recursion().
test_function_cells()
dill.tests.test_recursive.test_function_cells ()
Definition at line 125 of file test_recursive.py.
def test_function_cells():
    assert copy(f())
References copy(), and f().
Referenced by test_collection_function_recursion().
test_partial()
dill.tests.test_recursive.test_partial ()
Definition at line 75 of file test_recursive.py.
def test_partial():
    assert copy(Machine(), byref=True)
    assert copy(Machine(), byref=True, recurse=True)
    assert copy(Machine(), recurse=True)
    assert copy(Machine())
Referenced by test_collection_function_recursion().
test_partials()
dill.tests.test_recursive.test_partials ()
Definition at line 94 of file test_recursive.py.
def test_partials():
    assert copy(SubMachine(), byref=True)
    assert copy(SubMachine(), byref=True, recurse=True)
    assert copy(SubMachine(), recurse=True)
    assert copy(SubMachine())
References copy().
Referenced by test_collection_function_recursion().
test_recursive_function()
dill.tests.test_recursive.test_recursive_function ()
Definition at line 137 of file test_recursive.py.
def test_recursive_function():
    global fib
    fib2 = copy(fib, recurse=True)
    fib3 = copy(fib)
    fib4 = fib
    del fib
    assert fib2(5) == 5
    for _fib in (fib3, fib4):
        try:
            _fib(5)
        except Exception:
            # This is expected to fail because fib no longer exists
            pass
        else:
            raise AssertionError("Function fib shouldn't have been found")
    fib = fib4
References copy().
Referenced by test_collection_function_recursion().
test_super()
dill.tests.test_recursive.test_super ()
Definition at line 44 of file test_recursive.py.
def test_super():
    assert copy(obj1(), byref=True)
    assert copy(obj1(), byref=True, recurse=True)
    assert copy(obj1(), recurse=True)
    assert copy(obj1())
    assert copy(obj2(), byref=True)
    assert copy(obj2(), byref=True, recurse=True)
    assert copy(obj2(), recurse=True)
    assert copy(obj2())
    assert copy(obj3(), byref=True)
    assert copy(obj3(), byref=True, recurse=True)
    assert copy(obj3(), recurse=True)
    assert copy(obj3())
References copy().
Referenced by test_collection_function_recursion().