Read&Watch: django.contrib.auth.hashers Namespace Reference
django.contrib.auth.hashers Namespace Reference
Classes
class Argon2PasswordHasher
class BasePasswordHasher
class BCryptPasswordHasher
class BCryptSHA256PasswordHasher
class MD5PasswordHasher
class PBKDF2PasswordHasher
class PBKDF2SHA1PasswordHasher
class ScryptPasswordHasher
Functions
is_password_usable (encoded)
verify_password (password, encoded, preferred="default")
check_password (password, encoded, setter=None, preferred="default")
acheck_password (password, encoded, setter=None, preferred="default")
make_password (password, salt=None, hasher="default")
get_hashers ()
get_hashers_by_algorithm ()
reset_hashers (*, setting, **kwargs)
get_hasher (algorithm="default")
identify_hasher (encoded)
mask_hash (hash, show=6, char="*")
must_update_salt (salt, expected_entropy)
Variables
str UNUSABLE_PASSWORD_PREFIX = "!"
tuple UNUSABLE_PASSWORD_SUFFIX_LENGTH
Function Documentation
acheck_password()
django.contrib.auth.hashers.acheck_password (password, encoded, setter = None, preferred = "default")
See check_password().
Definition at line 86 of file hashers.py.
async def acheck_password(password, encoded, setter=None, preferred="default"):
    """See check_password()."""
    is_correct, must_update = verify_password(password, encoded, preferred=preferred)
    if setter and is_correct and must_update:
        await setter(password)
    return is_correct
References verify_password().
check_password()
django.contrib.auth.hashers.check_password (password, encoded, setter = None, preferred = "default")
Return a boolean of whether the raw password matches the three part encoded
digest.
If setter is specified, it'll be called when you need to regenerate the
password.
Definition at line 72 of file hashers.py.
def check_password(password, encoded, setter=None, preferred="default"):
    """
    Return a boolean of whether the raw password matches the three part encoded
    digest.
    If setter is specified, it'll be called when you need to regenerate the
    password.
    """
    is_correct, must_update = verify_password(password, encoded, preferred=preferred)
    if setter and is_correct and must_update:
        setter(password)
    return is_correct
References verify_password().
get_hasher()
django.contrib.auth.hashers.get_hasher (algorithm = "default")
Return an instance of a loaded password hasher.
If algorithm is 'default', return the default hasher. Lazily import hashers
specified in the project's settings file if needed.
Definition at line 142 of file hashers.py.
def get_hasher(algorithm="default"):
    """
    Return an instance of a loaded password hasher.
    If algorithm is 'default', return the default hasher. Lazily import hashers
    specified in the project's settings file if needed.
    """
    if hasattr(algorithm, "algorithm"):
        return algorithm
    elif algorithm == "default":
        return get_hashers()[0]
    else:
        hashers = get_hashers_by_algorithm()
        try:
            return hashers[algorithm]
        except KeyError:
            raise ValueError(
                "Unknown password hashing algorithm '%s'. "
                "Did you specify it in the PASSWORD_HASHERS "
                "setting?" % algorithm
            )
References get_hashers(), and get_hashers_by_algorithm().
Referenced by identify_hasher(), make_password(), and verify_password().
get_hashers()
django.contrib.auth.hashers.get_hashers ()
Definition at line 117 of file hashers.py.
def get_hashers():
    hashers = []
    for hasher_path in settings.PASSWORD_HASHERS:
        hasher_cls = import_string(hasher_path)
        hasher = hasher_cls()
        if not getattr(hasher, "algorithm"):
            raise ImproperlyConfigured(
                "hasher doesn't specify an algorithm name: %s" % hasher_path
            )
        hashers.append(hasher)
    return hashers
@functools.lru_cache
Referenced by get_hasher(), and get_hashers_by_algorithm().
get_hashers_by_algorithm()
django.contrib.auth.hashers.get_hashers_by_algorithm ()
Definition at line 131 of file hashers.py.
def get_hashers_by_algorithm():
    return {hasher.algorithm: hasher for hasher in get_hashers()}
@receiver(setting_changed)
References get_hashers().
Referenced by get_hasher().
identify_hasher()
django.contrib.auth.hashers.identify_hasher (encoded)
Return an instance of a loaded password hasher.
Identify hasher algorithm by examining encoded hash, and call
get_hasher() to return hasher. Raise ValueError if
algorithm cannot be identified, or if hasher is not loaded.
Definition at line 167 of file hashers.py.
def identify_hasher(encoded):
    """
    Return an instance of a loaded password hasher.
    Identify hasher algorithm by examining encoded hash, and call
    get_hasher() to return hasher. Raise ValueError if
    algorithm cannot be identified, or if hasher is not loaded.
    """
    # Ancient versions of Django created plain MD5 passwords and accepted
    # MD5 passwords with an empty salt.
    if (len(encoded) == 32 and "$" not in encoded) or (
        len(encoded) == 37 and encoded.startswith("md5$$")
    ):
        algorithm = "unsalted_md5"
    # Ancient versions of Django accepted SHA1 passwords with an empty salt.
    elif len(encoded) == 46 and encoded.startswith("sha1$$"):
        algorithm = "unsalted_sha1"
    else:
        algorithm = encoded.split("$", 1)[0]
    return get_hasher(algorithm)
References get_hasher().
Referenced by verify_password().
is_password_usable()
django.contrib.auth.hashers.is_password_usable (encoded)
Return True if this password wasn't generated by
User.set_unusable_password(), i.e. make_password(None).
Definition at line 28 of file hashers.py.
def is_password_usable(encoded):
    """
    Return True if this password wasn't generated by
    User.set_unusable_password(), i.e. make_password(None).
    """
    return encoded is None or not encoded.startswith(UNUSABLE_PASSWORD_PREFIX)
Referenced by verify_password().
make_password()
django.contrib.auth.hashers.make_password (password, salt = None, hasher = "default")
Turn a plain-text password into a hash for database storage
Same as encode() but generate a new random salt. If password is None then
return a concatenation of UNUSABLE_PASSWORD_PREFIX and a random string,
which disallows logins. Additional random string reduces chances of gaining
access to staff or superuser accounts. See ticket #20079 for more info.
Definition at line 94 of file hashers.py.
def make_password(password, salt=None, hasher="default"):
    """
    Turn a plain-text password into a hash for database storage
    Same as encode() but generate a new random salt. If password is None then
    return a concatenation of UNUSABLE_PASSWORD_PREFIX and a random string,
    which disallows logins. Additional random string reduces chances of gaining
    access to staff or superuser accounts. See ticket #20079 for more info.
    """
    if password is None:
        return UNUSABLE_PASSWORD_PREFIX + get_random_string(
            UNUSABLE_PASSWORD_SUFFIX_LENGTH
        )
    if not isinstance(password, (bytes, str)):
        raise TypeError(
            "Password must be a string or bytes, got %s." % type(password).__qualname__
        )
    hasher = get_hasher(hasher)
    salt = salt or hasher.salt()
    return hasher.encode(password, salt)
@functools.lru_cache
References get_hasher().
Referenced by verify_password().
mask_hash()
django.contrib.auth.hashers.mask_hash (hash, show = 6, char = "*")
Return the given hash, with only the first ``show`` number shown. The
rest are masked with ``char`` for security reasons.
Definition at line 189 of file hashers.py.
def mask_hash(hash, show=6, char="*"):
    """
    Return the given hash, with only the first ``show`` number shown. The
    rest are masked with ``char`` for security reasons.
    """
    masked = hash[:show]
    masked += char * len(hash[show:])
    return masked
Referenced by django.contrib.auth.hashers.Argon2PasswordHasher.safe_summary(), django.contrib.auth.hashers.BCryptSHA256PasswordHasher.safe_summary(), django.contrib.auth.hashers.MD5PasswordHasher.safe_summary(), django.contrib.auth.hashers.PBKDF2PasswordHasher.safe_summary(), and django.contrib.auth.hashers.ScryptPasswordHasher.safe_summary().
must_update_salt()
django.contrib.auth.hashers.must_update_salt (salt, expected_entropy)
Definition at line 199 of file hashers.py.
def must_update_salt(salt, expected_entropy):
    # Each character in the salt provides log_2(len(alphabet)) bits of entropy.
    return len(salt) * math.log2(len(RANDOM_STRING_CHARS)) < expected_entropy
Referenced by django.contrib.auth.hashers.Argon2PasswordHasher.must_update(), and django.contrib.auth.hashers.PBKDF2PasswordHasher.must_update().
reset_hashers()
django.contrib.auth.hashers.reset_hashers (* , setting, ** kwargs)
Definition at line 136 of file hashers.py.
def reset_hashers(*, setting, **kwargs):
    if setting == "PASSWORD_HASHERS":
        get_hashers.cache_clear()
        get_hashers_by_algorithm.cache_clear()
verify_password()
django.contrib.auth.hashers.verify_password (password, encoded, preferred = "default")
Return two booleans. The first is whether the raw password matches the
three part encoded digest, and the second whether to regenerate the
password.
Definition at line 36 of file hashers.py.
def verify_password(password, encoded, preferred="default"):
    """
    Return two booleans. The first is whether the raw password matches the
    three part encoded digest, and the second whether to regenerate the
    password.
    """
    fake_runtime = password is None or not is_password_usable(encoded)
    preferred = get_hasher(preferred)
    try:
        hasher = identify_hasher(encoded)
    except ValueError:
        # encoded is gibberish or uses a hasher that's no longer installed.
        fake_runtime = True
    if fake_runtime:
        # Run the default password hasher once to reduce the timing difference
        # between an existing user with an unusable password and a nonexistent
        # user or missing hasher (similar to #20760).
        make_password(get_random_string(UNUSABLE_PASSWORD_SUFFIX_LENGTH))
        return False, False
    hasher_changed = hasher.algorithm != preferred.algorithm
    must_update = hasher_changed or preferred.must_update(encoded)
    is_correct = hasher.verify(password, encoded)
    # If the hasher didn't change (we don't protect against enumeration if it
    # does) and the password should get updated, try to close the timing gap
    # between the work factor of the current encoded password and the default
    # work factor.
    if not is_correct and not hasher_changed and must_update:
        hasher.harden_runtime(password, encoded)
    return is_correct, must_update
References get_hasher(), identify_hasher(), is_password_usable(), and make_password().
Referenced by acheck_password(), and check_password().
Variable Documentation
UNUSABLE_PASSWORD_PREFIX
str django.contrib.auth.hashers.UNUSABLE_PASSWORD_PREFIX = "!"
Definition at line 22 of file hashers.py.
UNUSABLE_PASSWORD_SUFFIX_LENGTH
tuple django.contrib.auth.hashers.UNUSABLE_PASSWORD_SUFFIX_LENGTH
Initial value:
=  (
    40  # number of random chars to add after UNUSABLE_PASSWORD_PREFIX
)
Definition at line 23 of file hashers.py.