Read&Watch: astroid.nodes.scoped_nodes.scoped_nodes Namespace Reference
astroid.nodes.scoped_nodes.scoped_nodes Namespace Reference
Classes
class AsyncFunctionDef
class ClassDef
class DictComp
class FunctionDef
class GeneratorExp
class Lambda
class ListComp
class Module
class SetComp
Functions
_c3_merge (sequences, cls, context)
None clean_typing_generic_mro (list[list[ClassDef]] sequences)
list[list[ClassDef]] clean_duplicates_mro (list[list[ClassDef]] sequences, ClassDef cls, InferenceContext|None context)
function_to_method (n, klass)
_infer_decorator_callchain (node)
bool _is_metaclass (ClassDef klass, set[str]|None seen=None, InferenceContext|None context=None)
Literal["class", "exception", "metaclass"] _class_type (ClassDef klass, set[str]|None ancestors=None, InferenceContext|None context=None)
get_wrapping_class (node)
None __init__ (self, str name, int lineno, int col_offset, NodeNG parent, *, int|None end_lineno, int|None end_col_offset)
Literal[1] implicit_parameters (self)
implicit_locals (self)
None postinit (self, list[SuccessfulInferenceResult] bases, list[NodeNG] body, node_classes.Decorators|None decorators, bool|None newstyle=None, NodeNG|None metaclass=None, list[node_classes.Keyword]|None keywords=None, *, Position|None position=None, Const|None doc_node=None,(list[nodes.TypeVar|nodes.ParamSpec|nodes.TypeVarTuple]|None) type_params=None)
_newstyle_impl (self, InferenceContext|None context=None)
blockstart_tolineno (self)
tuple[int, int] block_range (self, int lineno)
Literal["builtins.type", "builtins.classobj"] pytype (self)
str display_type (self)
bool callable (self)
bool is_subtype_of (self, type_name, InferenceContext|None context=None)
_infer_type_call (self, caller, context)
Iterator[InferenceResult] infer_call_result (self, SuccessfulInferenceResult|None caller, InferenceContext|None context=None)
tuple[LocalsDictNodeNG, list[nodes.NodeNG]] scope_lookup (self, LookupMixIn node, str name, int offset=0)
basenames (self)
Generator[ClassDef] ancestors (self, bool recurs=True, InferenceContext|None context=None)
local_attr_ancestors (self, name, InferenceContext|None context=None)
instance_attr_ancestors (self, name, InferenceContext|None context=None)
bool has_base (self, node)
local_attr (self, name, InferenceContext|None context=None)
instance_attr (self, name, InferenceContext|None context=None)
bases.Instance instantiate_class (self)
list[InferenceResult] getattr (self, str name, InferenceContext|None context=None, bool class_context=True)
_metaclass_lookup_attribute (self, name, context)
_get_attribute_from_metaclass (self, cls, name, context)
Iterator[InferenceResult] igetattr (self, str name, InferenceContext|None context=None, bool class_context=True)
bool has_dynamic_getattr (self, InferenceContext|None context=None)
getitem (self, index, InferenceContext|None context=None)
methods (self)
mymethods (self)
implicit_metaclass (self)
SuccessfulInferenceResult|None declared_metaclass (self, InferenceContext|None context=None)
SuccessfulInferenceResult|None _find_metaclass (self, set[ClassDef]|None seen=None, InferenceContext|None context=None)
SuccessfulInferenceResult|None metaclass (self, InferenceContext|None context=None)
has_metaclass_hack (self)
_islots (self)
_slots (self)
_all_slots (self)
slots (self)
_inferred_bases (self, InferenceContext|None context=None)
_compute_mro (self, InferenceContext|None context=None)
list[ClassDef] mro (self, InferenceContext|None context=None)
Literal[True] bool_value (self, InferenceContext|None context=None)
get_children (self)
_assign_nodes_in_scope (self)
_T frame (_T self, *, Literal[None, True] future=None)
Generator[ClassDef] _infer (self, InferenceContext|None context=None, **Any kwargs)
Variables
tuple ITER_METHODS = ("__iter__", "__getitem__")
EXCEPTION_BASE_CLASSES = frozenset({"Exception", "BaseException"})
BUILTIN_DESCRIPTORS
_T = TypeVar("_T")
disable
tuple _astroid_fields
decorators = None
special_attributes = ClassModel()
Literal _type = None
NodeNG _metaclass = None
bool _metaclass_hack = False
bool hide = False
tuple _other_fields = ("name", "is_dataclass", "position")
tuple _other_other_fields = ("locals", "_newstyle")
bool _newstyle = None
tuple infer_binary_op
dict instance_attrs = {}
dict locals = {}
list keywords = []
list bases = []
list body = []
name = name
Const|None doc_node = None
bool is_dataclass = False
tuple type_params
position = position
fromlineno
parent
Properties
type
newstyle
Detailed Description
This module contains the classes for "scoped" node, i.e. which are opening a
new local scope in the language definition : Module, ClassDef, FunctionDef (and
Lambda, GeneratorExp, DictComp and SetComp to some extent).
Function Documentation
__init__()
None astroid.nodes.scoped_nodes.scoped_nodes.__init__ (self, str name, int lineno, int col_offset, NodeNG parent, * , int | None end_lineno, int | None end_col_offset)
Definition at line 1886 of file scoped_nodes.py.
    ) -> None:
        self.instance_attrs: dict[str, NodeNG] = {}
        self.locals = {}
        """A map of the name of a local variable to the node defining it."""
        self.keywords: list[node_classes.Keyword] = []
        """The keywords given to the class definition.
        This is usually for :pep:`3115` style metaclass declaration.
        """
        self.bases: list[SuccessfulInferenceResult] = []
        """What the class inherits from."""
        self.body: list[NodeNG] = []
        """The contents of the class body."""
        self.name = name
        """The name of the class."""
        self.decorators = None
        """The decorators that are applied to this class."""
        self.doc_node: Const | None = None
        """The doc node associated with this node."""
        self.is_dataclass: bool = False
        """Whether this class is a dataclass."""
        self.type_params: list[nodes.TypeVar | nodes.ParamSpec | nodes.TypeVarTuple] = (
            []
        )
        """PEP 695 (Python 3.12+) type params, e.g. class MyClass[T]: ..."""
        super().__init__(
            lineno=lineno,
            col_offset=col_offset,
            end_lineno=end_lineno,
            end_col_offset=end_col_offset,
            parent=parent,
        )
        if parent and not isinstance(parent, Unknown):
            parent.frame().set_local(name, self)
        for local_name, node in self.implicit_locals():
            self.add_local_node(node, local_name)
_all_slots()
astroid.nodes.scoped_nodes.scoped_nodes._all_slots (self) protected
Get all the slots for this node.
:returns: The names of slots for this class.
    If the class doesn't define any slot, through the ``__slots__``
    variable, then this function will return a None.
    Also, it will return None in the case the slots were not inferred.
:rtype: list(str) or None
Definition at line 2827 of file scoped_nodes.py.
    def _all_slots(self):
        """Get all the slots for this node.
        :returns: The names of slots for this class.
            If the class doesn't define any slot, through the ``__slots__``
            variable, then this function will return a None.
            Also, it will return None in the case the slots were not inferred.
        :rtype: list(str) or None
        """
        def grouped_slots(
            mro: list[ClassDef],
        ) -> Iterator[node_classes.NodeNG | None]:
            for cls in mro:
                # Not interested in object, since it can't have slots.
                if cls.qname() == "builtins.object":
                    continue
                try:
                    cls_slots = cls._slots()
                except NotImplementedError:
                    continue
                if cls_slots is not None:
                    yield from cls_slots
                else:
                    yield None
        if not self.newstyle:
            raise NotImplementedError(
                "The concept of slots is undefined for old-style classes."
            )
        try:
            mro = self.mro()
        except MroError as e:
            raise NotImplementedError(
                "Cannot get slots while parsing mro fails."
            ) from e
        slots = list(grouped_slots(mro))
        if not all(slot is not None for slot in slots):
            return None
        return sorted(set(slots), key=lambda item: item.value)
_assign_nodes_in_scope()
astroid.nodes.scoped_nodes.scoped_nodes._assign_nodes_in_scope (self) protected
Definition at line 2970 of file scoped_nodes.py.
    def _assign_nodes_in_scope(self):
        children_assign_nodes = (
            child_node._assign_nodes_in_scope for child_node in self.body
        )
        return list(itertools.chain.from_iterable(children_assign_nodes))
_c3_merge()
astroid.nodes.scoped_nodes.scoped_nodes._c3_merge (sequences, cls, context) protected
Merges MROs in *sequences* to a single MRO using the C3 algorithm.
Adapted from http://www.python.org/download/releases/2.3/mro/.
Definition at line 76 of file scoped_nodes.py.
def _c3_merge(sequences, cls, context):
    """Merges MROs in *sequences* to a single MRO using the C3 algorithm.
    Adapted from http://www.python.org/download/releases/2.3/mro/.
    """
    result = []
    while True:
        sequences = [s for s in sequences if s]  # purge empty sequences
        if not sequences:
            return result
        for s1 in sequences:  # find merge candidates among seq heads
            candidate = s1[0]
            for s2 in sequences:
                if candidate in s2[1:]:
                    candidate = None
                    break  # reject the current head, it appears later
            else:
                break
        if not candidate:
            # Show all the remaining bases, which were considered as
            # candidates for the next mro sequence.
            raise InconsistentMroError(
                message="Cannot create a consistent method resolution order "
                "for MROs {mros} of class {cls!r}.",
                mros=sequences,
                cls=cls,
                context=context,
            )
        result.append(candidate)
        # remove the chosen candidate
        for seq in sequences:
            if seq[0] == candidate:
                del seq[0]
    return None
Referenced by _compute_mro().
_class_type()
Literal["class", "exception", "metaclass"] astroid.nodes.scoped_nodes.scoped_nodes._class_type (ClassDef klass, set[str] | None ancestors = None, InferenceContext | None context = None) protected
return a ClassDef node type to differ metaclass and exception
from 'regular' classes
Definition at line 1774 of file scoped_nodes.py.
) -> Literal["class", "exception", "metaclass"]:
    """return a ClassDef node type to differ metaclass and exception
    from 'regular' classes
    """
    # XXX we have to store ancestors in case we have an ancestor loop
    if klass._type is not None:
        return klass._type
    if _is_metaclass(klass, context=context):
        klass._type = "metaclass"
    elif klass.name.endswith("Exception"):
        klass._type = "exception"
    else:
        if ancestors is None:
            ancestors = set()
        klass_name = klass.qname()
        if klass_name in ancestors:
            # XXX we are in loop ancestors, and have found no type
            klass._type = "class"
            return "class"
        ancestors.add(klass_name)
        for base in klass.ancestors(recurs=False):
            name = _class_type(base, ancestors)
            if name != "class":
                if name == "metaclass" and klass._type != "metaclass":
                    # don't propagate it if the current class
                    # can't be a metaclass
                    continue
                klass._type = base.type
                break
    if klass._type is None:
        klass._type = "class"
    return klass._type
References _class_type(), and _is_metaclass().
Referenced by _class_type().
_compute_mro()
astroid.nodes.scoped_nodes.scoped_nodes._compute_mro (self, InferenceContext | None context = None) protected
Definition at line 2913 of file scoped_nodes.py.
    def _compute_mro(self, context: InferenceContext | None = None):
        if self.qname() == "builtins.object":
            return [self]
        inferred_bases = list(self._inferred_bases(context=context))
        bases_mro = []
        for base in inferred_bases:
            if base is self:
                continue
            try:
                mro = base._compute_mro(context=context)
                bases_mro.append(mro)
            except NotImplementedError:
                # Some classes have in their ancestors both newstyle and
                # old style classes. For these we can't retrieve the .mro,
                # although in Python it's possible, since the class we are
                # currently working is in fact new style.
                # So, we fallback to ancestors here.
                ancestors = list(base.ancestors(context=context))
                bases_mro.append(ancestors)
        unmerged_mro: list[list[ClassDef]] = [[self], *bases_mro, inferred_bases]
        unmerged_mro = clean_duplicates_mro(unmerged_mro, self, context)
        clean_typing_generic_mro(unmerged_mro)
        return _c3_merge(unmerged_mro, self, context)
References _c3_merge(), clean_duplicates_mro(), and clean_typing_generic_mro().
_find_metaclass()
SuccessfulInferenceResult | None astroid.nodes.scoped_nodes.scoped_nodes._find_metaclass (self, set[ClassDef] | None seen = None, InferenceContext | None context = None) protected
Definition at line 2726 of file scoped_nodes.py.
    ) -> SuccessfulInferenceResult | None:
        if seen is None:
            seen = set()
        seen.add(self)
        klass = self.declared_metaclass(context=context)
        if klass is None:
            for parent in self.ancestors(context=context):
                if parent not in seen:
                    klass = parent._find_metaclass(seen)
                    if klass is not None:
                        break
        return klass
_get_attribute_from_metaclass()
astroid.nodes.scoped_nodes.scoped_nodes._get_attribute_from_metaclass (self, cls, name, context) protected
Definition at line 2446 of file scoped_nodes.py.
    def _get_attribute_from_metaclass(self, cls, name, context):
        from astroid import objects  # pylint: disable=import-outside-toplevel
        try:
            attrs = cls.getattr(name, context=context, class_context=True)
        except AttributeInferenceError:
            return
        for attr in bases._infer_stmts(attrs, context, frame=cls):
            if not isinstance(attr, FunctionDef):
                yield attr
                continue
            if isinstance(attr, objects.Property):
                yield attr
                continue
            if attr.type == "classmethod":
                # If the method is a classmethod, then it will
                # be bound to the metaclass, not to the class
                # from where the attribute is retrieved.
                # get_wrapping_class could return None, so just
                # default to the current class.
                frame = get_wrapping_class(attr) or self
                yield bases.BoundMethod(attr, frame)
            elif attr.type == "staticmethod":
                yield attr
            else:
                yield bases.BoundMethod(attr, self)
References get_wrapping_class().
_infer()
Generator[ClassDef] astroid.nodes.scoped_nodes.scoped_nodes._infer (self, InferenceContext | None context = None, **Any kwargs) protected
Definition at line 2986 of file scoped_nodes.py.
    ) -> Generator[ClassDef]:
        yield self
_infer_decorator_callchain()
astroid.nodes.scoped_nodes.scoped_nodes._infer_decorator_callchain (node) protected
Detect decorator call chaining and see if the end result is a
static or a classmethod.
Definition at line 837 of file scoped_nodes.py.
def _infer_decorator_callchain(node):
    """Detect decorator call chaining and see if the end result is a
    static or a classmethod.
    """
    if not isinstance(node, FunctionDef):
        return None
    if not node.parent:
        return None
    try:
        result = next(node.infer_call_result(node.parent), None)
    except InferenceError:
        return None
    if isinstance(result, bases.Instance):
        result = result._proxied
    if isinstance(result, ClassDef):
        if result.is_subtype_of("builtins.classmethod"):
            return "classmethod"
        if result.is_subtype_of("builtins.staticmethod"):
            return "staticmethod"
    if isinstance(result, FunctionDef):
        if not result.decorators:
            return None
        # Determine if this function is decorated with one of the builtin descriptors we want.
        for decorator in result.decorators.nodes:
            if isinstance(decorator, node_classes.Name):
                if decorator.name in BUILTIN_DESCRIPTORS:
                    return decorator.name
            if (
                isinstance(decorator, node_classes.Attribute)
                and isinstance(decorator.expr, node_classes.Name)
                and decorator.expr.name == "builtins"
                and decorator.attrname in BUILTIN_DESCRIPTORS
            ):
                return decorator.attrname
    return None
_infer_type_call()
astroid.nodes.scoped_nodes.scoped_nodes._infer_type_call (self, caller, context) protected
Definition at line 2072 of file scoped_nodes.py.
    def _infer_type_call(self, caller, context):
        try:
            name_node = next(caller.args[0].infer(context))
        except StopIteration as e:
            raise InferenceError(node=caller.args[0], context=context) from e
        if isinstance(name_node, node_classes.Const) and isinstance(
            name_node.value, str
        ):
            name = name_node.value
        else:
            return util.Uninferable
        result = ClassDef(
            name,
            lineno=0,
            col_offset=0,
            end_lineno=0,
            end_col_offset=0,
            parent=Unknown(),
        )
        # Get the bases of the class.
        try:
            class_bases = next(caller.args[1].infer(context))
        except StopIteration as e:
            raise InferenceError(node=caller.args[1], context=context) from e
        if isinstance(class_bases, (node_classes.Tuple, node_classes.List)):
            bases = []
            for base in class_bases.itered():
                inferred = next(base.infer(context=context), None)
                if inferred:
                    bases.append(
                        node_classes.EvaluatedObject(original=base, value=inferred)
                    )
            result.bases = bases
        else:
            # There is currently no AST node that can represent an 'unknown'
            # node (Uninferable is not an AST node), therefore we simply return Uninferable here
            # although we know at least the name of the class.
            return util.Uninferable
        # Get the members of the class
        try:
            members = next(caller.args[2].infer(context))
        except (InferenceError, StopIteration):
            members = None
        if members and isinstance(members, node_classes.Dict):
            for attr, value in members.items:
                if isinstance(attr, node_classes.Const) and isinstance(attr.value, str):
                    result.locals[attr.value] = [value]
        result.parent = caller.parent
        return result
_inferred_bases()
astroid.nodes.scoped_nodes.scoped_nodes._inferred_bases (self, InferenceContext | None context = None) protected
Definition at line 2874 of file scoped_nodes.py.
    def _inferred_bases(self, context: InferenceContext | None = None):
        # Similar with .ancestors, but the difference is when one base is inferred,
        # only the first object is wanted. That's because
        # we aren't interested in superclasses, as in the following
        # example:
        #
        # class SomeSuperClass(object): pass
        # class SomeClass(SomeSuperClass): pass
        # class Test(SomeClass): pass
        #
        # Inferring SomeClass from the Test's bases will give
        # us both SomeClass and SomeSuperClass, but we are interested
        # only in SomeClass.
        if context is None:
            context = InferenceContext()
        if not self.bases and self.qname() != "builtins.object":
            yield builtin_lookup("object")[1][0]
            return
        for stmt in self.bases:
            try:
                # Find the first non-None inferred base value
                baseobj = next(
                    b
                    for b in stmt.infer(context=context.clone())
                    if not (isinstance(b, Const) and b.value is None)
                )
            except (InferenceError, StopIteration):
                continue
            if isinstance(baseobj, bases.Instance):
                baseobj = baseobj._proxied
            if not isinstance(baseobj, ClassDef):
                continue
            if not baseobj.hide:
                yield baseobj
            else:
                yield from baseobj.bases
_is_metaclass()
bool astroid.nodes.scoped_nodes.scoped_nodes._is_metaclass (ClassDef klass, set[str] | None seen = None, InferenceContext | None context = None) protected
Return if the given class can be
used as a metaclass.
Definition at line 1738 of file scoped_nodes.py.
) -> bool:
    """Return if the given class can be
    used as a metaclass.
    """
    if klass.name == "type":
        return True
    if seen is None:
        seen = set()
    for base in klass.bases:
        try:
            for baseobj in base.infer(context=context):
                baseobj_name = baseobj.qname()
                if baseobj_name in seen:
                    continue
                seen.add(baseobj_name)
                if isinstance(baseobj, bases.Instance):
                    # not abstract
                    return False
                if baseobj is klass:
                    continue
                if not isinstance(baseobj, ClassDef):
                    continue
                if baseobj._type == "metaclass":
                    return True
                if _is_metaclass(baseobj, seen, context=context):
                    return True
        except InferenceError:
            continue
    return False
Referenced by _class_type().
_islots()
astroid.nodes.scoped_nodes.scoped_nodes._islots (self) protected
Return an iterator with the inferred slots.
Definition at line 2758 of file scoped_nodes.py.
    def _islots(self):
        """Return an iterator with the inferred slots."""
        if "__slots__" not in self.locals:
            return None
        for slots in self.igetattr("__slots__"):
            # check if __slots__ is a valid type
            for meth in ITER_METHODS:
                try:
                    slots.getattr(meth)
                    break
                except AttributeInferenceError:
                    continue
            else:
                continue
            if isinstance(slots, node_classes.Const):
                # a string. Ignore the following checks,
                # but yield the node, only if it has a value
                if slots.value:
                    yield slots
                continue
            if not hasattr(slots, "itered"):
                # we can't obtain the values, maybe a .deque?
                continue
            if isinstance(slots, node_classes.Dict):
                values = [item[0] for item in slots.items]
            else:
                values = slots.itered()
            if isinstance(values, util.UninferableBase):
                continue
            if not values:
                # Stop the iteration, because the class
                # has an empty list of slots.
                return values
            for elt in values:
                try:
                    for inferred in elt.infer():
                        if not isinstance(
                            inferred, node_classes.Const
                        ) or not isinstance(inferred.value, str):
                            continue
                        if not inferred.value:
                            continue
                        yield inferred
                except InferenceError:
                    continue
        return None
_metaclass_lookup_attribute()
astroid.nodes.scoped_nodes.scoped_nodes._metaclass_lookup_attribute (self, name, context) protected
Search the given name in the implicit and the explicit metaclass.
Definition at line 2434 of file scoped_nodes.py.
    def _metaclass_lookup_attribute(self, name, context):
        """Search the given name in the implicit and the explicit metaclass."""
        attrs = set()
        implicit_meta = self.implicit_metaclass()
        context = copy_context(context)
        metaclass = self.metaclass(context=context)
        for cls in (implicit_meta, metaclass):
            if cls and cls != self and isinstance(cls, ClassDef):
                cls_attributes = self._get_attribute_from_metaclass(cls, name, context)
                attrs.update(set(cls_attributes))
        return attrs
_newstyle_impl()
astroid.nodes.scoped_nodes.scoped_nodes._newstyle_impl (self, InferenceContext | None context = None) protected
Definition at line 1990 of file scoped_nodes.py.
    def _newstyle_impl(self, context: InferenceContext | None = None):
        if context is None:
            context = InferenceContext()
        if self._newstyle is not None:
            return self._newstyle
        for base in self.ancestors(recurs=False, context=context):
            if base._newstyle_impl(context):
                self._newstyle = True
                break
        klass = self.declared_metaclass()
        # could be any callable, we'd need to infer the result of klass(name,
        # bases, dict).  punt if it's not a class node.
        if klass is not None and isinstance(klass, ClassDef):
            self._newstyle = klass._newstyle_impl(context)
        if self._newstyle is None:
            self._newstyle = False
        return self._newstyle
_slots()
astroid.nodes.scoped_nodes.scoped_nodes._slots (self) protected
Definition at line 2809 of file scoped_nodes.py.
    def _slots(self):
        if not self.newstyle:
            raise NotImplementedError(
                "The concept of slots is undefined for old-style classes."
            )
        slots = self._islots()
        try:
            first = next(slots)
        except StopIteration as exc:
            # The class doesn't have a __slots__ definition or empty slots.
            if exc.args and exc.args[0] not in ("", None):
                return exc.args[0]
            return None
        return [first, *slots]
ancestors()
Generator[ClassDef] astroid.nodes.scoped_nodes.scoped_nodes.ancestors (self, bool recurs = True, InferenceContext | None context = None)
Iterate over the base classes in prefixed depth first order.
:param recurs: Whether to recurse or return direct ancestors only.
:returns: The base classes
Definition at line 2223 of file scoped_nodes.py.
    ) -> Generator[ClassDef]:
        """Iterate over the base classes in prefixed depth first order.
        :param recurs: Whether to recurse or return direct ancestors only.
        :returns: The base classes
        """
        # FIXME: should be possible to choose the resolution order
        # FIXME: inference make infinite loops possible here
        yielded = {self}
        if context is None:
            context = InferenceContext()
        if not self.bases and self.qname() != "builtins.object":
            # This should always be a ClassDef (which we don't assert for)
            yield builtin_lookup("object")[1][0]  # type: ignore[misc]
            return
        for stmt in self.bases:
            with context.restore_path():
                try:
                    for baseobj in stmt.infer(context):
                        if not isinstance(baseobj, ClassDef):
                            if isinstance(baseobj, bases.Instance):
                                baseobj = baseobj._proxied
                            else:
                                continue
                        if not baseobj.hide:
                            if baseobj in yielded:
                                continue
                            yielded.add(baseobj)
                            yield baseobj
                        if not recurs:
                            continue
                        for grandpa in baseobj.ancestors(recurs=True, context=context):
                            if grandpa is self:
                                # This class is the ancestor of itself.
                                break
                            if grandpa in yielded:
                                continue
                            yielded.add(grandpa)
                            yield grandpa
                except InferenceError:
                    continue
basenames()
astroid.nodes.scoped_nodes.scoped_nodes.basenames (self)
The names of the parent classes
Names are given in the order they appear in the class definition.
:type: list(str)
Definition at line 2214 of file scoped_nodes.py.
    def basenames(self):
        """The names of the parent classes
        Names are given in the order they appear in the class definition.
        :type: list(str)
        """
        return [bnode.as_string() for bnode in self.bases]
block_range()
tuple[int, int] astroid.nodes.scoped_nodes.scoped_nodes.block_range (self, int lineno)
Get a range from the given line number to where this node ends.
:param lineno: Unused.
:returns: The range of line numbers that this node belongs to,
Definition at line 2025 of file scoped_nodes.py.
    def block_range(self, lineno: int) -> tuple[int, int]:
        """Get a range from the given line number to where this node ends.
        :param lineno: Unused.
        :returns: The range of line numbers that this node belongs to,
        """
        return self.fromlineno, self.tolineno
blockstart_tolineno()
astroid.nodes.scoped_nodes.scoped_nodes.blockstart_tolineno (self)
The line on which the beginning of this block ends.
:type: int
Definition at line 2015 of file scoped_nodes.py.
    def blockstart_tolineno(self):
        """The line on which the beginning of this block ends.
        :type: int
        """
        if self.bases:
            return self.bases[-1].tolineno
        return self.fromlineno
bool_value()
Literal[True] astroid.nodes.scoped_nodes.scoped_nodes.bool_value (self, InferenceContext | None context = None)
Determine the boolean value of this node.
:returns: The boolean value of this node.
    For a :class:`ClassDef` this is always ``True``.
Definition at line 2950 of file scoped_nodes.py.
    def bool_value(self, context: InferenceContext | None = None) -> Literal[True]:
        """Determine the boolean value of this node.
        :returns: The boolean value of this node.
            For a :class:`ClassDef` this is always ``True``.
        """
        return True
callable()
bool astroid.nodes.scoped_nodes.scoped_nodes.callable (self)
Whether this node defines something that is callable.
:returns: Whether this defines something that is callable.
    For a :class:`ClassDef` this is always ``True``.
Definition at line 2051 of file scoped_nodes.py.
    def callable(self) -> bool:
        """Whether this node defines something that is callable.
        :returns: Whether this defines something that is callable.
            For a :class:`ClassDef` this is always ``True``.
        """
        return True
clean_duplicates_mro()
list[list[ClassDef]] astroid.nodes.scoped_nodes.scoped_nodes.clean_duplicates_mro (list[list[ClassDef]] sequences, ClassDef cls, InferenceContext | None context)
Definition at line 150 of file scoped_nodes.py.
) -> list[list[ClassDef]]:
    for sequence in sequences:
        seen = set()
        for node in sequence:
            lineno_and_qname = (node.lineno, node.qname())
            if lineno_and_qname in seen:
                raise DuplicateBasesError(
                    message="Duplicates found in MROs {mros} for {cls!r}.",
                    mros=sequences,
                    cls=cls,
                    context=context,
                )
            seen.add(lineno_and_qname)
    return sequences
Referenced by _compute_mro().
clean_typing_generic_mro()
None astroid.nodes.scoped_nodes.scoped_nodes.clean_typing_generic_mro (list[list[ClassDef]] sequences)
A class can inherit from typing.Generic directly, as base,
and as base of bases. The merged MRO must however only contain the last entry.
To prepare for _c3_merge, remove some typing.Generic entries from
sequences if multiple are present.
This method will check if Generic is in inferred_bases and also
part of bases_mro. If true, remove it from inferred_bases
as well as its entry the bases_mro.
Format sequences: [[self]] + bases_mro + [inferred_bases]
Definition at line 114 of file scoped_nodes.py.
def clean_typing_generic_mro(sequences: list[list[ClassDef]]) -> None:
    """A class can inherit from typing.Generic directly, as base,
    and as base of bases. The merged MRO must however only contain the last entry.
    To prepare for _c3_merge, remove some typing.Generic entries from
    sequences if multiple are present.
    This method will check if Generic is in inferred_bases and also
    part of bases_mro. If true, remove it from inferred_bases
    as well as its entry the bases_mro.
    Format sequences: [[self]] + bases_mro + [inferred_bases]
    """
    bases_mro = sequences[1:-1]
    inferred_bases = sequences[-1]
    # Check if Generic is part of inferred_bases
    for i, base in enumerate(inferred_bases):
        if base.qname() == "typing.Generic":
            position_in_inferred_bases = i
            break
    else:
        return
    # Check if also part of bases_mro
    # Ignore entry for typing.Generic
    for i, seq in enumerate(bases_mro):
        if i == position_in_inferred_bases:
            continue
        if any(base.qname() == "typing.Generic" for base in seq):
            break
    else:
        return
    # Found multiple Generics in mro, remove entry from inferred_bases
    # and the corresponding one from bases_mro
    inferred_bases.pop(position_in_inferred_bases)
    bases_mro.pop(position_in_inferred_bases)
Referenced by _compute_mro().
declared_metaclass()
SuccessfulInferenceResult | None astroid.nodes.scoped_nodes.scoped_nodes.declared_metaclass (self, InferenceContext | None context = None)
Return the explicit declared metaclass for the current class.
An explicit declared metaclass is defined
either by passing the ``metaclass`` keyword argument
in the class definition line (Python 3) or (Python 2) by
having a ``__metaclass__`` class attribute, or if there are
no explicit bases but there is a global ``__metaclass__`` variable.
:returns: The metaclass of this class,
    or None if one could not be found.
Definition at line 2689 of file scoped_nodes.py.
    ) -> SuccessfulInferenceResult | None:
        """Return the explicit declared metaclass for the current class.
        An explicit declared metaclass is defined
        either by passing the ``metaclass`` keyword argument
        in the class definition line (Python 3) or (Python 2) by
        having a ``__metaclass__`` class attribute, or if there are
        no explicit bases but there is a global ``__metaclass__`` variable.
        :returns: The metaclass of this class,
            or None if one could not be found.
        """
        for base in self.bases:
            try:
                for baseobj in base.infer(context=context):
                    if isinstance(baseobj, ClassDef) and baseobj.hide:
                        self._metaclass = baseobj._metaclass
                        self._metaclass_hack = True
                        break
            except InferenceError:
                pass
        if self._metaclass:
            # Expects this from Py3k TreeRebuilder
            try:
                return next(
                    node
                    for node in self._metaclass.infer(context=context)
                    if not isinstance(node, util.UninferableBase)
                )
            except (InferenceError, StopIteration):
                return None
        return None
display_type()
str astroid.nodes.scoped_nodes.scoped_nodes.display_type (self)
A human readable type of this node.
:returns: The type of this node.
:rtype: str
Definition at line 2043 of file scoped_nodes.py.
    def display_type(self) -> str:
        """A human readable type of this node.
        :returns: The type of this node.
        :rtype: str
        """
        return "Class"
frame()
_T astroid.nodes.scoped_nodes.scoped_nodes.frame (_T self, * , Literal[None, True] future = None)
The node's frame node.
A frame node is a :class:`Module`, :class:`FunctionDef`,
:class:`ClassDef` or :class:`Lambda`.
:returns: The node itself.
Definition at line 2976 of file scoped_nodes.py.
    def frame(self: _T, *, future: Literal[None, True] = None) -> _T:
        """The node's frame node.
        A frame node is a :class:`Module`, :class:`FunctionDef`,
        :class:`ClassDef` or :class:`Lambda`.
        :returns: The node itself.
        """
        return self
function_to_method()
astroid.nodes.scoped_nodes.scoped_nodes.function_to_method (n, klass)
Definition at line 170 of file scoped_nodes.py.
def function_to_method(n, klass):
    if isinstance(n, FunctionDef):
        if n.type == "classmethod":
            return bases.BoundMethod(n, klass)
        if n.type == "property":
            return n
        if n.type != "staticmethod":
            return bases.UnboundMethod(n)
    return n
Referenced by igetattr().
get_children()
astroid.nodes.scoped_nodes.scoped_nodes.get_children (self)
Definition at line 2958 of file scoped_nodes.py.
    def get_children(self):
        if self.decorators is not None:
            yield self.decorators
        yield from self.bases
        if self.keywords is not None:
            yield from self.keywords
        yield from self.type_params
        yield from self.body
get_wrapping_class()
astroid.nodes.scoped_nodes.scoped_nodes.get_wrapping_class (node)
Get the class that wraps the given node.
We consider that a class wraps a node if the class
is a parent for the said node.
:returns: The class that wraps the given node
:rtype: ClassDef or None
Definition at line 1812 of file scoped_nodes.py.
def get_wrapping_class(node):
    """Get the class that wraps the given node.
    We consider that a class wraps a node if the class
    is a parent for the said node.
    :returns: The class that wraps the given node
    :rtype: ClassDef or None
    """
    klass = node.frame()
    while klass is not None and not isinstance(klass, ClassDef):
        if klass.parent is None:
            klass = None
        else:
            klass = klass.parent.frame()
    return klass
Referenced by _get_attribute_from_metaclass().
getattr()
list[InferenceResult] astroid.nodes.scoped_nodes.scoped_nodes.getattr (self, str name, InferenceContext | None context = None, bool class_context = True)
Get an attribute from this class, using Python's attribute semantic.
This method doesn't look in the :attr:`instance_attrs` dictionary
since it is done by an :class:`Instance` proxy at inference time.
It may return an :class:`Uninferable` object if
the attribute has not been
found, but a ``__getattr__`` or ``__getattribute__`` method is defined.
If ``class_context`` is given, then it is considered that the
attribute is accessed from a class context,
e.g. ClassDef.attribute, otherwise it might have been accessed
from an instance as well. If ``class_context`` is used in that
case, then a lookup in the implicit metaclass and the explicit
metaclass will be done.
:param name: The attribute to look for.
:param class_context: Whether the attribute can be accessed statically.
:returns: The attribute.
:raises AttributeInferenceError: If the attribute cannot be inferred.
Definition at line 2374 of file scoped_nodes.py.
    ) -> list[InferenceResult]:
        """Get an attribute from this class, using Python's attribute semantic.
        This method doesn't look in the :attr:`instance_attrs` dictionary
        since it is done by an :class:`Instance` proxy at inference time.
        It may return an :class:`Uninferable` object if
        the attribute has not been
        found, but a ``__getattr__`` or ``__getattribute__`` method is defined.
        If ``class_context`` is given, then it is considered that the
        attribute is accessed from a class context,
        e.g. ClassDef.attribute, otherwise it might have been accessed
        from an instance as well. If ``class_context`` is used in that
        case, then a lookup in the implicit metaclass and the explicit
        metaclass will be done.
        :param name: The attribute to look for.
        :param class_context: Whether the attribute can be accessed statically.
        :returns: The attribute.
        :raises AttributeInferenceError: If the attribute cannot be inferred.
        """
        if not name:
            raise AttributeInferenceError(target=self, attribute=name, context=context)
        # don't modify the list in self.locals!
        values: list[InferenceResult] = list(self.locals.get(name, []))
        for classnode in self.ancestors(recurs=True, context=context):
            values += classnode.locals.get(name, [])
        if name in self.special_attributes and class_context and not values:
            result = [self.special_attributes.lookup(name)]
            if name == "__bases__":
                # Need special treatment, since they are mutable
                # and we need to return all the values.
                result += values
            return result
        if class_context:
            values += self._metaclass_lookup_attribute(name, context)
        # Remove AnnAssigns without value, which are not attributes in the purest sense.
        for value in values.copy():
            if isinstance(value, node_classes.AssignName):
                stmt = value.statement()
                if isinstance(stmt, node_classes.AnnAssign) and stmt.value is None:
                    values.pop(values.index(value))
        if not values:
            raise AttributeInferenceError(target=self, attribute=name, context=context)
        return values
Referenced by has_dynamic_getattr().
getitem()
astroid.nodes.scoped_nodes.scoped_nodes.getitem (self, index, InferenceContext | None context = None)
Return the inference of a subscript.
This is basically looking up the method in the metaclass and calling it.
:returns: The inferred value of a subscript to this class.
:rtype: NodeNG
:raises AstroidTypeError: If this class does not define a
    ``__getitem__`` method.
Definition at line 2599 of file scoped_nodes.py.
    def getitem(self, index, context: InferenceContext | None = None):
        """Return the inference of a subscript.
        This is basically looking up the method in the metaclass and calling it.
        :returns: The inferred value of a subscript to this class.
        :rtype: NodeNG
        :raises AstroidTypeError: If this class does not define a
            ``__getitem__`` method.
        """
        try:
            methods = lookup(self, "__getitem__", context=context)
        except AttributeInferenceError as exc:
            if isinstance(self, ClassDef):
                # subscripting a class definition may be
                # achieved thanks to __class_getitem__ method
                # which is a classmethod defined in the class
                # that supports subscript and not in the metaclass
                try:
                    methods = self.getattr("__class_getitem__")
                    # Here it is assumed that the __class_getitem__ node is
                    # a FunctionDef. One possible improvement would be to deal
                    # with more generic inference.
                except AttributeInferenceError:
                    raise AstroidTypeError(node=self, context=context) from exc
            else:
                raise AstroidTypeError(node=self, context=context) from exc
        method = methods[0]
        # Create a new callcontext for providing index as an argument.
        new_context = bind_context_to_node(context, self)
        new_context.callcontext = CallContext(args=[index], callee=method)
        try:
            return next(method.infer_call_result(self, new_context), util.Uninferable)
        except AttributeError:
            # Starting with python3.9, builtin types list, dict etc...
            # are subscriptable thanks to __class_getitem___ classmethod.
            # However in such case the method is bound to an EmptyNode and
            # EmptyNode doesn't have infer_call_result method yielding to
            # AttributeError
            if (
                isinstance(method, node_classes.EmptyNode)
                and self.pytype() == "builtins.type"
            ):
                return self
            raise
        except InferenceError:
            return util.Uninferable
has_base()
bool astroid.nodes.scoped_nodes.scoped_nodes.has_base (self, node)
Whether this class directly inherits from the given node.
:param node: The node to check for.
:type node: NodeNG
:returns: Whether this class directly inherits from the given node.
Definition at line 2304 of file scoped_nodes.py.
    def has_base(self, node) -> bool:
        """Whether this class directly inherits from the given node.
        :param node: The node to check for.
        :type node: NodeNG
        :returns: Whether this class directly inherits from the given node.
        """
        return node in self.bases
has_dynamic_getattr()
bool astroid.nodes.scoped_nodes.scoped_nodes.has_dynamic_getattr (self, InferenceContext | None context = None)
Check if the class has a custom __getattr__ or __getattribute__.
If any such method is found and it is not from
builtins, nor from an extension module, then the function
will return True.
:returns: Whether the class has a custom __getattr__ or __getattribute__.
Definition at line 2574 of file scoped_nodes.py.
    def has_dynamic_getattr(self, context: InferenceContext | None = None) -> bool:
        """Check if the class has a custom __getattr__ or __getattribute__.
        If any such method is found and it is not from
        builtins, nor from an extension module, then the function
        will return True.
        :returns: Whether the class has a custom __getattr__ or __getattribute__.
        """
        def _valid_getattr(node):
            root = node.root()
            return root.name != "builtins" and getattr(root, "pure_python", None)
        try:
            return _valid_getattr(self.getattr("__getattr__", context)[0])
        except AttributeInferenceError:
            # if self.newstyle: XXX cause an infinite recursion error
            try:
                getattribute = self.getattr("__getattribute__", context)[0]
                return _valid_getattr(getattribute)
            except AttributeInferenceError:
                pass
        return False
References getattr().
has_metaclass_hack()
astroid.nodes.scoped_nodes.scoped_nodes.has_metaclass_hack (self)
Definition at line 2755 of file scoped_nodes.py.
    def has_metaclass_hack(self):
        return self._metaclass_hack
igetattr()
Iterator[InferenceResult] astroid.nodes.scoped_nodes.scoped_nodes.igetattr (self, str name, InferenceContext | None context = None, bool class_context = True)
Infer the possible values of the given variable.
:param name: The name of the variable to infer.
:returns: The inferred possible values.
Definition at line 2475 of file scoped_nodes.py.
    ) -> Iterator[InferenceResult]:
        """Infer the possible values of the given variable.
        :param name: The name of the variable to infer.
        :returns: The inferred possible values.
        """
        from astroid import objects  # pylint: disable=import-outside-toplevel
        # set lookup name since this is necessary to infer on import nodes for
        # instance
        context = copy_context(context)
        context.lookupname = name
        metaclass = self.metaclass(context=context)
        try:
            attributes = self.getattr(name, context, class_context=class_context)
            # If we have more than one attribute, make sure that those starting from
            # the second one are from the same scope. This is to account for modifications
            # to the attribute happening *after* the attribute's definition (e.g. AugAssigns on lists)
            if len(attributes) > 1:
                first_attr, attributes = attributes[0], attributes[1:]
                first_scope = first_attr.parent.scope()
                attributes = [first_attr] + [
                    attr
                    for attr in attributes
                    if attr.parent and attr.parent.scope() == first_scope
                ]
            functions = [attr for attr in attributes if isinstance(attr, FunctionDef)]
            setter = None
            for function in functions:
                dec_names = function.decoratornames(context=context)
                for dec_name in dec_names:
                    if dec_name is util.Uninferable:
                        continue
                    if dec_name.split(".")[-1] == "setter":
                        setter = function
                if setter:
                    break
            if functions:
                # Prefer only the last function, unless a property is involved.
                last_function = functions[-1]
                attributes = [
                    a
                    for a in attributes
                    if a not in functions or a is last_function or bases._is_property(a)
                ]
            for inferred in bases._infer_stmts(attributes, context, frame=self):
                # yield Uninferable object instead of descriptors when necessary
                if not isinstance(inferred, node_classes.Const) and isinstance(
                    inferred, bases.Instance
                ):
                    try:
                        inferred._proxied.getattr("__get__", context)
                    except AttributeInferenceError:
                        yield inferred
                    else:
                        yield util.Uninferable
                elif isinstance(inferred, objects.Property):
                    function = inferred.function
                    if not class_context:
                        if not context.callcontext and not setter:
                            context.callcontext = CallContext(
                                args=function.args.arguments, callee=function
                            )
                        # Through an instance so we can solve the property
                        yield from function.infer_call_result(
                            caller=self, context=context
                        )
                    # If we're in a class context, we need to determine if the property
                    # was defined in the metaclass (a derived class must be a subclass of
                    # the metaclass of all its bases), in which case we can resolve the
                    # property. If not, i.e. the property is defined in some base class
                    # instead, then we return the property object
                    elif metaclass and function.parent.scope() is metaclass:
                        # Resolve a property as long as it is not accessed through
                        # the class itself.
                        yield from function.infer_call_result(
                            caller=self, context=context
                        )
                    else:
                        yield inferred
                else:
                    yield function_to_method(inferred, self)
        except AttributeInferenceError as error:
            if not name.startswith("__") and self.has_dynamic_getattr(context):
                # class handle some dynamic attributes, return a Uninferable object
                yield util.Uninferable
            else:
                raise InferenceError(
                    str(error), target=self, attribute=name, context=context
                ) from error
References function_to_method().
implicit_locals()
astroid.nodes.scoped_nodes.scoped_nodes.implicit_locals (self)
Get implicitly defined class definition locals.
:returns: the the name and Const pair for each local
:rtype: tuple(tuple(str, node_classes.Const), ...)
Definition at line 1949 of file scoped_nodes.py.
    def implicit_locals(self):
        """Get implicitly defined class definition locals.
        :returns: the the name and Const pair for each local
        :rtype: tuple(tuple(str, node_classes.Const), ...)
        """
        locals_ = (("__module__", self.special_attributes.attr___module__),)
        # __qualname__ is defined in PEP3155
        locals_ += (
            ("__qualname__", self.special_attributes.attr___qualname__),
            ("__annotations__", self.special_attributes.attr___annotations__),
        )
        return locals_
implicit_metaclass()
astroid.nodes.scoped_nodes.scoped_nodes.implicit_metaclass (self)
Get the implicit metaclass of the current class.
For newstyle classes, this will return an instance of builtins.type.
For oldstyle classes, it will simply return None, since there's
no implicit metaclass there.
:returns: The metaclass.
:rtype: builtins.type or None
Definition at line 2675 of file scoped_nodes.py.
    def implicit_metaclass(self):
        """Get the implicit metaclass of the current class.
        For newstyle classes, this will return an instance of builtins.type.
        For oldstyle classes, it will simply return None, since there's
        no implicit metaclass there.
        :returns: The metaclass.
        :rtype: builtins.type or None
        """
        if self.newstyle:
            return builtin_lookup("type")[1][0]
        return None
implicit_parameters()
Literal[1] astroid.nodes.scoped_nodes.scoped_nodes.implicit_parameters (self)
Definition at line 1946 of file scoped_nodes.py.
    def implicit_parameters(self) -> Literal[1]:
        return 1
infer_call_result()
Iterator[InferenceResult] astroid.nodes.scoped_nodes.scoped_nodes.infer_call_result (self, SuccessfulInferenceResult | None caller, InferenceContext | None context = None)
infer what a class is returning when called
Definition at line 2127 of file scoped_nodes.py.
    ) -> Iterator[InferenceResult]:
        """infer what a class is returning when called"""
        if self.is_subtype_of("builtins.type", context) and len(caller.args) == 3:
            result = self._infer_type_call(caller, context)
            yield result
            return
        dunder_call = None
        try:
            metaclass = self.metaclass(context=context)
            if metaclass is not None:
                # Only get __call__ if it's defined locally for the metaclass.
                # Otherwise we will find ObjectModel.__call__ which will
                # return an instance of the metaclass. Instantiating the class is
                # handled later.
                if "__call__" in metaclass.locals:
                    dunder_call = next(metaclass.igetattr("__call__", context))
        except (AttributeInferenceError, StopIteration):
            pass
        if dunder_call and dunder_call.qname() != "builtins.type.__call__":
            # Call type.__call__ if not set metaclass
            # (since type is the default metaclass)
            context = bind_context_to_node(context, self)
            context.callcontext.callee = dunder_call
            yield from dunder_call.infer_call_result(caller, context)
        else:
            yield self.instantiate_class()
instance_attr()
astroid.nodes.scoped_nodes.scoped_nodes.instance_attr (self, name, InferenceContext | None context = None)
Get the list of nodes associated to the given attribute name.
Assignments are looked for in both this class and in parents.
:returns: The list of assignments to the given name.
:rtype: list(NodeNG)
:raises AttributeInferenceError: If no attribute with this name
    can be found in this class or parent classes.
Definition at line 2337 of file scoped_nodes.py.
    def instance_attr(self, name, context: InferenceContext | None = None):
        """Get the list of nodes associated to the given attribute name.
        Assignments are looked for in both this class and in parents.
        :returns: The list of assignments to the given name.
        :rtype: list(NodeNG)
        :raises AttributeInferenceError: If no attribute with this name
            can be found in this class or parent classes.
        """
        # Return a copy, so we don't modify self.instance_attrs,
        # which could lead to infinite loop.
        values = list(self.instance_attrs.get(name, []))
        # get all values from parents
        for class_node in self.instance_attr_ancestors(name, context):
            values += class_node.instance_attrs[name]
        values = [n for n in values if not isinstance(n, node_classes.DelAttr)]
        if values:
            return values
        raise AttributeInferenceError(target=self, attribute=name, context=context)
instance_attr_ancestors()
astroid.nodes.scoped_nodes.scoped_nodes.instance_attr_ancestors (self, name, InferenceContext | None context = None)
Iterate over the parents that define the given name as an attribute.
:param name: The name to find definitions for.
:type name: str
:returns: The parents that define the given name as
    an instance attribute.
:rtype: iterable(NodeNG)
Definition at line 2290 of file scoped_nodes.py.
    def instance_attr_ancestors(self, name, context: InferenceContext | None = None):
        """Iterate over the parents that define the given name as an attribute.
        :param name: The name to find definitions for.
        :type name: str
        :returns: The parents that define the given name as
            an instance attribute.
        :rtype: iterable(NodeNG)
        """
        for astroid in self.ancestors(context=context):
            if name in astroid.instance_attrs:
                yield astroid
instantiate_class()
bases.Instance astroid.nodes.scoped_nodes.scoped_nodes.instantiate_class (self)
Get an :class:`Instance` of the :class:`ClassDef` node.
:returns: An :class:`Instance` of the :class:`ClassDef` node
Definition at line 2359 of file scoped_nodes.py.
    def instantiate_class(self) -> bases.Instance:
        """Get an :class:`Instance` of the :class:`ClassDef` node.
        :returns: An :class:`Instance` of the :class:`ClassDef` node
        """
        from astroid import objects  # pylint: disable=import-outside-toplevel
        try:
            if any(cls.name in EXCEPTION_BASE_CLASSES for cls in self.mro()):
                # Subclasses of exceptions can be exception instances
                return objects.ExceptionInstance(self)
        except MroError:
            pass
        return bases.Instance(self)
is_subtype_of()
bool astroid.nodes.scoped_nodes.scoped_nodes.is_subtype_of (self, type_name, InferenceContext | None context = None)
Whether this class is a subtype of the given type.
:param type_name: The name of the type of check against.
:type type_name: str
:returns: Whether this class is a subtype of the given type.
Definition at line 2059 of file scoped_nodes.py.
    def is_subtype_of(self, type_name, context: InferenceContext | None = None) -> bool:
        """Whether this class is a subtype of the given type.
        :param type_name: The name of the type of check against.
        :type type_name: str
        :returns: Whether this class is a subtype of the given type.
        """
        if self.qname() == type_name:
            return True
        return any(anc.qname() == type_name for anc in self.ancestors(context=context))
local_attr()
astroid.nodes.scoped_nodes.scoped_nodes.local_attr (self, name, InferenceContext | None context = None)
Get the list of assign nodes associated to the given name.
Assignments are looked for in both this class and in parents.
:returns: The list of assignments to the given name.
:rtype: list(NodeNG)
:raises AttributeInferenceError: If no attribute with this name
    can be found in this class or parent classes.
Definition at line 2314 of file scoped_nodes.py.
    def local_attr(self, name, context: InferenceContext | None = None):
        """Get the list of assign nodes associated to the given name.
        Assignments are looked for in both this class and in parents.
        :returns: The list of assignments to the given name.
        :rtype: list(NodeNG)
        :raises AttributeInferenceError: If no attribute with this name
            can be found in this class or parent classes.
        """
        result = []
        if name in self.locals:
            result = self.locals[name]
        else:
            class_node = next(self.local_attr_ancestors(name, context), None)
            if class_node:
                result = class_node.locals[name]
        result = [n for n in result if not isinstance(n, node_classes.DelAttr)]
        if result:
            return result
        raise AttributeInferenceError(target=self, attribute=name, context=context)
local_attr_ancestors()
astroid.nodes.scoped_nodes.scoped_nodes.local_attr_ancestors (self, name, InferenceContext | None context = None)
Iterate over the parents that define the given name.
:param name: The name to find definitions for.
:type name: str
:returns: The parents that define the given name.
:rtype: iterable(NodeNG)
Definition at line 2269 of file scoped_nodes.py.
    def local_attr_ancestors(self, name, context: InferenceContext | None = None):
        """Iterate over the parents that define the given name.
        :param name: The name to find definitions for.
        :type name: str
        :returns: The parents that define the given name.
        :rtype: iterable(NodeNG)
        """
        # Look up in the mro if we can. This will result in the
        # attribute being looked up just as Python does it.
        try:
            ancestors: Iterable[ClassDef] = self.mro(context)[1:]
        except MroError:
            # Fallback to use ancestors, we can't determine
            # a sane MRO.
            ancestors = self.ancestors(context=context)
        for astroid in ancestors:
            if name in astroid:
                yield astroid
metaclass()
SuccessfulInferenceResult | None astroid.nodes.scoped_nodes.scoped_nodes.metaclass (self, InferenceContext | None context = None)
Get the metaclass of this class.
If this class does not define explicitly a metaclass,
then the first defined metaclass in ancestors will be used
instead.
:returns: The metaclass of this class.
Definition at line 2742 of file scoped_nodes.py.
    ) -> SuccessfulInferenceResult | None:
        """Get the metaclass of this class.
        If this class does not define explicitly a metaclass,
        then the first defined metaclass in ancestors will be used
        instead.
        :returns: The metaclass of this class.
        """
        return self._find_metaclass(context=context)
methods()
astroid.nodes.scoped_nodes.scoped_nodes.methods (self)
Iterate over all of the method defined in this class and its parents.
:returns: The methods defined on the class.
:rtype: iterable(FunctionDef)
Definition at line 2651 of file scoped_nodes.py.
    def methods(self):
        """Iterate over all of the method defined in this class and its parents.
        :returns: The methods defined on the class.
        :rtype: iterable(FunctionDef)
        """
        done = {}
        for astroid in itertools.chain(iter((self,)), self.ancestors()):
            for meth in astroid.mymethods():
                if meth.name in done:
                    continue
                done[meth.name] = None
                yield meth
mro()
list[ClassDef] astroid.nodes.scoped_nodes.scoped_nodes.mro (self, InferenceContext | None context = None)
Get the method resolution order, using C3 linearization.
:returns: The list of ancestors, sorted by the mro.
:rtype: list(NodeNG)
:raises DuplicateBasesError: Duplicate bases in the same class base
:raises InconsistentMroError: A class' MRO is inconsistent
Definition at line 2940 of file scoped_nodes.py.
    def mro(self, context: InferenceContext | None = None) -> list[ClassDef]:
        """Get the method resolution order, using C3 linearization.
        :returns: The list of ancestors, sorted by the mro.
        :rtype: list(NodeNG)
        :raises DuplicateBasesError: Duplicate bases in the same class base
        :raises InconsistentMroError: A class' MRO is inconsistent
        """
        return self._compute_mro(context=context)
mymethods()
astroid.nodes.scoped_nodes.scoped_nodes.mymethods (self)
Iterate over all of the method defined in this class only.
:returns: The methods defined on the class.
:rtype: iterable(FunctionDef)
Definition at line 2665 of file scoped_nodes.py.
    def mymethods(self):
        """Iterate over all of the method defined in this class only.
        :returns: The methods defined on the class.
        :rtype: iterable(FunctionDef)
        """
        for member in self.values():
            if isinstance(member, FunctionDef):
                yield member
postinit()
None astroid.nodes.scoped_nodes.scoped_nodes.postinit (self, list[SuccessfulInferenceResult] bases, list[NodeNG] body, node_classes.Decorators | None decorators, bool | None newstyle = None, NodeNG | None metaclass = None, list[node_classes.Keyword] | None keywords = None, * , Position | None position = None, Const | None doc_node = None, (list[nodes.TypeVar | nodes.ParamSpec | nodes.TypeVarTuple] | None) type_params = None)
Definition at line 1964 of file scoped_nodes.py.
    ) -> None:
        if keywords is not None:
            self.keywords = keywords
        self.bases = bases
        self.body = body
        self.decorators = decorators
        self._newstyle = newstyle
        self._metaclass = metaclass
        self.position = position
        self.doc_node = doc_node
        self.type_params = type_params or []
pytype()
Literal["builtins.type", "builtins.classobj"] astroid.nodes.scoped_nodes.scoped_nodes.pytype (self)
Get the name of the type that this node represents.
:returns: The name of the type.
Definition at line 2034 of file scoped_nodes.py.
    def pytype(self) -> Literal["builtins.type", "builtins.classobj"]:
        """Get the name of the type that this node represents.
        :returns: The name of the type.
        """
        if self.newstyle:
            return "builtins.type"
        return "builtins.classobj"
scope_lookup()
tuple[LocalsDictNodeNG, list[nodes.NodeNG]] astroid.nodes.scoped_nodes.scoped_nodes.scope_lookup (self, LookupMixIn node, str name, int offset = 0)
Lookup where the given name is assigned.
:param node: The node to look for assignments up to.
    Any assignments after the given node are ignored.
:param name: The name to find assignments for.
:param offset: The line offset to filter statements up to.
:returns: This scope node and the list of assignments associated to the
    given name according to the scope where it has been found (locals,
    globals or builtin).
Definition at line 2160 of file scoped_nodes.py.
    ) -> tuple[LocalsDictNodeNG, list[nodes.NodeNG]]:
        """Lookup where the given name is assigned.
        :param node: The node to look for assignments up to.
            Any assignments after the given node are ignored.
        :param name: The name to find assignments for.
        :param offset: The line offset to filter statements up to.
        :returns: This scope node and the list of assignments associated to the
            given name according to the scope where it has been found (locals,
            globals or builtin).
        """
        # If the name looks like a builtin name, just try to look
        # into the upper scope of this class. We might have a
        # decorator that it's poorly named after a builtin object
        # inside this class.
        lookup_upper_frame = (
            isinstance(node.parent, node_classes.Decorators)
            and name in AstroidManager().builtins_module
        )
        if (
            any(
                node == base or base.parent_of(node) and not self.type_params
                for base in self.bases
            )
            or lookup_upper_frame
        ):
            # Handle the case where we have either a name
            # in the bases of a class, which exists before
            # the actual definition or the case where we have
            # a Getattr node, with that name.
            #
            # name = ...
            # class A(name):
            #     def name(self): ...
            #
            # import name
            # class A(name.Name):
            #     def name(self): ...
            if not self.parent:
                raise ParentMissingError(target=self)
            frame = self.parent.frame()
            # line offset to avoid that class A(A) resolve the ancestor to
            # the defined class
            offset = -1
        else:
            frame = self
        return frame._scope_lookup(node, name, offset)
slots()
astroid.nodes.scoped_nodes.scoped_nodes.slots (self)
Definition at line 2871 of file scoped_nodes.py.
    def slots(self):
        return self._all_slots
Variable Documentation
_astroid_fields
tuple astroid.nodes.scoped_nodes.scoped_nodes._astroid_fields protected
Initial value:
=  (
        "decorators",
        "bases",
        "keywords",
        "doc_node",
        "body",
        "type_params",
    )
Class representing an :class:`ast.ClassDef` node.
>>> import astroid
>>> node = astroid.extract_node('''
class Thing:
    def my_meth(self, arg):
        return arg + self.offset
''')
>>> node
<ClassDef.Thing l.2 at 0x7f23b2e9e748>
Definition at line 1850 of file scoped_nodes.py.
_metaclass
NodeNG astroid.nodes.scoped_nodes.scoped_nodes._metaclass = None protected
Definition at line 1871 of file scoped_nodes.py.
_metaclass_hack
bool astroid.nodes.scoped_nodes.scoped_nodes._metaclass_hack = False protected
Definition at line 1872 of file scoped_nodes.py.
_newstyle
astroid.nodes.scoped_nodes.scoped_nodes._newstyle = None protected
Definition at line 1884 of file scoped_nodes.py.
_other_fields
tuple astroid.nodes.scoped_nodes.scoped_nodes._other_fields = ("name", "is_dataclass", "position") protected
Definition at line 1882 of file scoped_nodes.py.
_other_other_fields
tuple astroid.nodes.scoped_nodes.scoped_nodes._other_other_fields = ("locals", "_newstyle") protected
Definition at line 1883 of file scoped_nodes.py.
_T
astroid.nodes.scoped_nodes.scoped_nodes._T = TypeVar("_T") protected
Definition at line 73 of file scoped_nodes.py.
_type
Literal astroid.nodes.scoped_nodes.scoped_nodes._type = None protected
The names of special attributes that this class has.
:type: objectmodel.ClassModel
Definition at line 1870 of file scoped_nodes.py.
bases
list astroid.nodes.scoped_nodes.scoped_nodes.bases = []
Definition at line 1906 of file scoped_nodes.py.
body
list astroid.nodes.scoped_nodes.scoped_nodes.body = []
Definition at line 1909 of file scoped_nodes.py.
BUILTIN_DESCRIPTORS
astroid.nodes.scoped_nodes.scoped_nodes.BUILTIN_DESCRIPTORS
Initial value:
=  frozenset(
    {"classmethod", "staticmethod", "builtins.classmethod", "builtins.staticmethod"}
)
Definition at line 69 of file scoped_nodes.py.
decorators
astroid.nodes.scoped_nodes.scoped_nodes.decorators = None
Definition at line 1859 of file scoped_nodes.py.
disable
astroid.nodes.scoped_nodes.scoped_nodes.disable
Definition at line 1831 of file scoped_nodes.py.
doc_node
Const | None astroid.nodes.scoped_nodes.scoped_nodes.doc_node = None
Definition at line 1918 of file scoped_nodes.py.
EXCEPTION_BASE_CLASSES
astroid.nodes.scoped_nodes.scoped_nodes.EXCEPTION_BASE_CLASSES = frozenset({"Exception", "BaseException"})
Definition at line 68 of file scoped_nodes.py.
fromlineno
astroid.nodes.scoped_nodes.scoped_nodes.fromlineno
Definition at line 2032 of file scoped_nodes.py.
hide
bool astroid.nodes.scoped_nodes.scoped_nodes.hide = False
Definition at line 1873 of file scoped_nodes.py.
infer_binary_op
tuple astroid.nodes.scoped_nodes.scoped_nodes.infer_binary_op
Initial value:
=  (
        protocols.instance_class_infer_binary_op
    )
Definition at line 1942 of file scoped_nodes.py.
instance_attrs
dict astroid.nodes.scoped_nodes.scoped_nodes.instance_attrs = {}
Definition at line 1896 of file scoped_nodes.py.
is_dataclass
bool astroid.nodes.scoped_nodes.scoped_nodes.is_dataclass = False
Definition at line 1921 of file scoped_nodes.py.
ITER_METHODS
tuple astroid.nodes.scoped_nodes.scoped_nodes.ITER_METHODS = ("__iter__", "__getitem__")
Definition at line 67 of file scoped_nodes.py.
keywords
list astroid.nodes.scoped_nodes.scoped_nodes.keywords = []
Definition at line 1900 of file scoped_nodes.py.
locals
dict astroid.nodes.scoped_nodes.scoped_nodes.locals = {}
Definition at line 1897 of file scoped_nodes.py.
name
astroid.nodes.scoped_nodes.scoped_nodes.name = name
Definition at line 1912 of file scoped_nodes.py.
parent
astroid.nodes.scoped_nodes.scoped_nodes.parent
Definition at line 2203 of file scoped_nodes.py.
position
astroid.nodes.scoped_nodes.scoped_nodes.position = position
Definition at line 1986 of file scoped_nodes.py.
special_attributes
astroid.nodes.scoped_nodes.scoped_nodes.special_attributes = ClassModel()
The decorators that are applied to this class.
:type: Decorators or None
Definition at line 1864 of file scoped_nodes.py.
type_params
tuple astroid.nodes.scoped_nodes.scoped_nodes.type_params
Initial value:
=  (
            []
        )
Definition at line 1924 of file scoped_nodes.py.
Property Documentation
type
astroid.nodes.scoped_nodes.scoped_nodes.type
Initial value:
=  property(
        _class_type,
        doc=(
            "The class type for this node.\n\n"
            "Possible values are: class, metaclass, exception.\n\n"
            ":type: str"
        ),
    )
Definition at line 1874 of file scoped_nodes.py.
newstyle
astroid.nodes.scoped_nodes.scoped_nodes.newstyle
Initial value:
=  property(
        _newstyle_impl,
        doc=("Whether this is a new style class or not\n\n" ":type: bool or None"),
    )
Definition at line 2009 of file scoped_nodes.py.