Read&Watch: pylint.extensions.empty_comment Namespace Reference
pylint.extensions.empty_comment Namespace Reference
Classes
class CommentChecker
Functions
bool is_line_commented (bytes line)
bool comment_part_of_string (bytes line, int comment_idx)
None register (PyLinter linter)
Function Documentation
comment_part_of_string()
bool pylint.extensions.empty_comment.comment_part_of_string (bytes line, int comment_idx)
Checks if the symbol at comment_idx is part of a string.
Definition at line 27 of file empty_comment.py.
def comment_part_of_string(line: bytes, comment_idx: int) -> bool:
    """Checks if the symbol at comment_idx is part of a string."""
    if (
        line[:comment_idx].count(b"'") % 2 == 1
        and line[comment_idx:].count(b"'") % 2 == 1
    ) or (
        line[:comment_idx].count(b'"') % 2 == 1
        and line[comment_idx:].count(b'"') % 2 == 1
    ):
        return True
    return False
Referenced by is_line_commented().
is_line_commented()
bool pylint.extensions.empty_comment.is_line_commented (bytes line)
Checks if a `# symbol that is not part of a string was found in line.
Definition at line 17 of file empty_comment.py.
def is_line_commented(line: bytes) -> bool:
    """Checks if a `# symbol that is not part of a string was found in line."""
    comment_idx = line.find(b"#")
    if comment_idx == -1:
        return False
    if comment_part_of_string(line, comment_idx):
        return is_line_commented(line[:comment_idx] + line[comment_idx + 1 :])
    return True
References comment_part_of_string(), and is_line_commented().
Referenced by is_line_commented(), and pylint.extensions.empty_comment.CommentChecker.process_module().
register()
None pylint.extensions.empty_comment.register (PyLinter linter)
Definition at line 62 of file empty_comment.py.
def register(linter: PyLinter) -> None:
    linter.register_checker(CommentChecker(linter))