Read&Watch: dill.tests.test_selected Namespace Reference
dill.tests.test_selected Namespace Reference
Classes
class _d
Functions
test_dict_contents ()
_g (x)
_f ()
test_class_descriptors ()
test_class ()
test_frame_related ()
test_typing ()
Variables
bool verbose = False
pickleable
True
unpickleable
_newclass = objects['ClassObjectType']
Detailed Description
testing some selected object types
Function Documentation
_f()
dill.tests.test_selected._f () protected
Definition at line 30 of file test_selected.py.
def _f():
  try: raise
  except Exception:
    from sys import exc_info
    e, er, tb = exc_info()
    return er, tb
Referenced by test_frame_related().
_g()
dill.tests.test_selected._g (x) protected
Definition at line 28 of file test_selected.py.
def _g(x): yield x;
Referenced by test_frame_related().
test_class()
dill.tests.test_selected.test_class ()
Definition at line 71 of file test_selected.py.
def test_class():
  o = _d()
  oo = _newclass()
  ok = dill.pickles(o)
  if verbose: print ("%s: %s, %s" % (ok, type(o), o))
  assert ok
  ok = dill.pickles(oo)
  if verbose: print ("%s: %s, %s" % (ok, type(oo), oo))
  assert ok
  if verbose: print ("")
# frames, generators, and tracebacks (all depend on frame)
References _newclass.
Referenced by test_typing().
test_class_descriptors()
dill.tests.test_selected.test_class_descriptors ()
Definition at line 56 of file test_selected.py.
def test_class_descriptors():
  d = _d.__dict__
  for i in d.values():
    ok = dill.pickles(i)
    if verbose: print ("%s: %s, %s" % (ok, type(i), i))
    assert ok
  if verbose: print ("")
  od = _newclass.__dict__
  for i in od.values():
    ok = dill.pickles(i)
    if verbose: print ("%s: %s, %s" % (ok, type(i), i))
    assert ok
  if verbose: print ("")
# (__main__) class instance for new-style classes
Referenced by test_typing().
test_dict_contents()
dill.tests.test_selected.test_dict_contents ()
Definition at line 17 of file test_selected.py.
def test_dict_contents():
  c = type.__dict__
  for i,j in c.items():
   #try:
    ok = dill.pickles(j)
   #except Exception:
   #  print ("FAIL: %s with %s" % (i, dill.detect.errors(j)))
    if verbose: print ("%s: %s, %s" % (ok, type(j), j))
    assert ok
  if verbose: print ("")
Referenced by test_typing().
test_frame_related()
dill.tests.test_selected.test_frame_related ()
Definition at line 83 of file test_selected.py.
def test_frame_related():
  g = _g(1)
  f = g.gi_frame
  e,t = _f()
  _is = lambda ok: ok
  ok = dill.pickles(f)
  if verbose: print ("%s: %s, %s" % (ok, type(f), f))
  assert not ok
  ok = dill.pickles(g)
  if verbose: print ("%s: %s, %s" % (ok, type(g), g))
  assert _is(not ok) #XXX: dill fails
  ok = dill.pickles(t)
  if verbose: print ("%s: %s, %s" % (ok, type(t), t))
  assert not ok #XXX: dill fails
  ok = dill.pickles(e)
  if verbose: print ("%s: %s, %s" % (ok, type(e), e))
  assert ok
  if verbose: print ("")
References _f(), and _g().
Referenced by test_typing().
test_typing()
dill.tests.test_selected.test_typing ()
Definition at line 102 of file test_selected.py.
def test_typing():
  import typing
  x = typing.Any
  assert x == dill.copy(x)
  x = typing.Dict[int, str]
  assert x == dill.copy(x)
  x = typing.List[int]
  assert x == dill.copy(x)
  x = typing.Tuple[int, str]
  assert x == dill.copy(x)
  x = typing.Tuple[int]
  assert x == dill.copy(x)
  x = typing.Tuple[()]
  assert x == dill.copy(x)
  x = typing.Tuple[()].copy_with(())
  assert x == dill.copy(x)
  return
References test_class(), test_class_descriptors(), test_dict_contents(), test_frame_related(), and test_typing().
Referenced by test_typing().
Variable Documentation
_newclass
dill.tests.test_selected._newclass = objects['ClassObjectType'] protected
Definition at line 44 of file test_selected.py.
Referenced by test_class().
pickleable
dill.tests.test_selected.pickleable
Definition at line 43 of file test_selected.py.
True
dill.tests.test_selected.True
Definition at line 43 of file test_selected.py.
unpickleable
dill.tests.test_selected.unpickleable
Definition at line 43 of file test_selected.py.
verbose
bool dill.tests.test_selected.verbose = False
Definition at line 15 of file test_selected.py.