Read&Watch: tomlkit._utils Namespace Reference
tomlkit._utils Namespace Reference
Functions
datetime|date|time parse_rfc3339 (str string)
str _unicode_escape (str seq)
str escape_string (str s, Collection[str] escape_sequences=_basic_escapes)
dict merge_dicts (dict d1, dict d2)
Variables
RFC_3339_LOOSE
RFC_3339_DATETIME
RFC_3339_DATE = re.compile("^([0-9]+)-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])$")
RFC_3339_TIME
_utc = timezone(timedelta(), "UTC")
CONTROL_CHARS = frozenset(chr(c) for c in range(0x20)) | {chr(0x7F)}
dict _escaped
dict _compact_escapes
_basic_escapes = CONTROL_CHARS | {'"', "\\"}
Function Documentation
_unicode_escape()
str tomlkit._utils._unicode_escape (str seq) protected
Definition at line 120 of file _utils.py.
def _unicode_escape(seq: str) -> str:
    return "".join(f"\\u{ord(c):04x}" for c in seq)
Referenced by escape_string().
escape_string()
str tomlkit._utils.escape_string (str s, Collection[str] escape_sequences = _basic_escapes)
Definition at line 124 of file _utils.py.
def escape_string(s: str, escape_sequences: Collection[str] = _basic_escapes) -> str:
    s = decode(s)
    res = []
    start = 0
    def flush(inc=1):
        if start != i:
            res.append(s[start:i])
        return i + inc
    found_sequences = {seq for seq in escape_sequences if seq in s}
    i = 0
    while i < len(s):
        for seq in found_sequences:
            seq_len = len(seq)
            if s[i:].startswith(seq):
                start = flush(seq_len)
                res.append(_compact_escapes.get(seq) or _unicode_escape(seq))
                i += seq_len - 1  # fast-forward escape sequence
        i += 1
    flush()
    return "".join(res)
References _unicode_escape().
merge_dicts()
dict tomlkit._utils.merge_dicts (dict d1, dict d2)
Definition at line 153 of file _utils.py.
def merge_dicts(d1: dict, d2: dict) -> dict:
    for k, v in d2.items():
        if k in d1 and isinstance(d1[k], dict) and isinstance(v, Mapping):
            merge_dicts(d1[k], v)
        else:
            d1[k] = d2[k]
References merge_dicts().
Referenced by merge_dicts().
parse_rfc3339()
datetime | date | time tomlkit._utils.parse_rfc3339 (str string)
Definition at line 45 of file _utils.py.
def parse_rfc3339(string: str) -> datetime | date | time:
    m = RFC_3339_DATETIME.match(string)
    if m:
        year = int(m.group(1))
        month = int(m.group(2))
        day = int(m.group(3))
        hour = int(m.group(4))
        minute = int(m.group(5))
        second = int(m.group(6))
        microsecond = 0
        if m.group(7):
            microsecond = int((f"{m.group(8):<06s}")[:6])
        if m.group(9):
            # Timezone
            tz = m.group(9)
            if tz.upper() == "Z":
                tzinfo = _utc
            else:
                sign = m.group(11)[0]
                hour_offset, minute_offset = int(m.group(12)), int(m.group(13))
                offset = timedelta(seconds=hour_offset * 3600 + minute_offset * 60)
                if sign == "-":
                    offset = -offset
                tzinfo = timezone(offset, f"{sign}{m.group(12)}:{m.group(13)}")
            return datetime(
                year, month, day, hour, minute, second, microsecond, tzinfo=tzinfo
            )
        else:
            return datetime(year, month, day, hour, minute, second, microsecond)
    m = RFC_3339_DATE.match(string)
    if m:
        year = int(m.group(1))
        month = int(m.group(2))
        day = int(m.group(3))
        return date(year, month, day)
    m = RFC_3339_TIME.match(string)
    if m:
        hour = int(m.group(1))
        minute = int(m.group(2))
        second = int(m.group(3))
        microsecond = 0
        if m.group(4):
            microsecond = int((f"{m.group(5):<06s}")[:6])
        return time(hour, minute, second, microsecond)
    raise ValueError("Invalid RFC 339 string")
# https://toml.io/en/v1.0.0#string
Variable Documentation
_basic_escapes
tomlkit._utils._basic_escapes = CONTROL_CHARS | {'"', "\\"} protected
Definition at line 117 of file _utils.py.
_compact_escapes
dict tomlkit._utils._compact_escapes protected
Initial value:
=  {
    **{v: f"\\{k}" for k, v in _escaped.items()},
    '"""': '""\\"',
}
Definition at line 113 of file _utils.py.
_escaped
dict tomlkit._utils._escaped protected
Initial value:
=  {
    "b": "\b",
    "t": "\t",
    "n": "\n",
    "f": "\f",
    "r": "\r",
    '"': '"',
    "\\": "\\",
}
Definition at line 104 of file _utils.py.
_utc
tomlkit._utils._utc = timezone(timedelta(), "UTC") protected
Definition at line 42 of file _utils.py.
CONTROL_CHARS
tomlkit._utils.CONTROL_CHARS = frozenset(chr(c) for c in range(0x20)) | {chr(0x7F)}
Definition at line 103 of file _utils.py.
RFC_3339_DATE
tomlkit._utils.RFC_3339_DATE = re.compile("^([0-9]+)-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])$")
Definition at line 36 of file _utils.py.
RFC_3339_DATETIME
tomlkit._utils.RFC_3339_DATETIME
Initial value:
=  re.compile(
    "^"
    "([0-9]+)-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])"  # Date
    "[Tt ]"  # Separator
    r"([01][0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9]|60)(\.([0-9]+))?"  # Time
    r"(([Zz])|([\+|\-]([01][0-9]|2[0-3]):([0-5][0-9])))?"  # Timezone
    "$"
)
Definition at line 27 of file _utils.py.
RFC_3339_LOOSE
tomlkit._utils.RFC_3339_LOOSE
Initial value:
=  re.compile(
    "^"
    r"(([0-9]+)-(\d{2})-(\d{2}))?"  # Date
    "("
    "([Tt ])?"  # Separator
    r"(\d{2}):(\d{2}):(\d{2})(\.([0-9]+))?"  # Time
    r"(([Zz])|([\+|\-]([01][0-9]|2[0-3]):([0-5][0-9])))?"  # Timezone
    ")?"
    "$"
)
Definition at line 16 of file _utils.py.
RFC_3339_TIME
tomlkit._utils.RFC_3339_TIME
Initial value:
=  re.compile(
    r"^([01][0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9]|60)(\.([0-9]+))?$"
)
Definition at line 38 of file _utils.py.