Read&Watch: pylint.checkers.typecheck Namespace Reference
pylint.checkers.typecheck Namespace Reference
Classes
class IterableChecker
class TypeChecker
class VERSION_COMPATIBLE_OVERLOAD
Functions
bool _is_owner_ignored (SuccessfulInferenceResult owner, str|None attrname, Iterable[str] ignored_classes, Iterable[str] ignored_modules)
Iterable[str] _node_names (SuccessfulInferenceResult node)
Iterable[str] _ (nodes.ClassDef|bases.Instance node)
int _string_distance (str seq1, str seq2)
list[str] _similar_names (SuccessfulInferenceResult owner, str|None attrname, int distance_threshold, int max_choices)
str _missing_member_hint (SuccessfulInferenceResult owner, str|None attrname, int distance_threshold, int max_choices)
bool _emit_no_member (nodes.Attribute|nodes.AssignAttr|nodes.DelAttr node, InferenceResult owner, str|None owner_name, Pattern[str] mixin_class_rgx, bool ignored_mixins=True, bool ignored_none=True)
set[str] _get_all_attribute_assignments (nodes.FunctionDef node, str|None name=None)
bool _enum_has_attribute (astroid.Instance|nodes.ClassDef owner, nodes.Attribute node)
tuple[CallableObjects, int, str] _determine_callable (nodes.NodeNG callable_obj)
bool _has_parent_of_type (nodes.Call node, nodes.Keyword|nodes.Starred node_type, _base_nodes.Statement statement)
bool _no_context_variadic_keywords (nodes.Call node, nodes.Lambda scope)
bool _no_context_variadic_positional (nodes.Call node, nodes.Lambda scope)
bool _no_context_variadic (nodes.Call node, str|None variadic_name, nodes.Keyword|nodes.Starred variadic_type, list[nodes.Keyword|nodes.Starred] variadics)
bool _is_invalid_metaclass (nodes.ClassDef metaclass)
InferenceResult|None _infer_from_metaclass_constructor (nodes.ClassDef cls, nodes.FunctionDef func)
bool _is_c_extension (InferenceResult module_node)
bool _is_invalid_isinstance_type (nodes.NodeNG arg)
None register (PyLinter linter)
Variables
CallableObjects
dict STR_FORMAT = {"builtins.str.format"}
str ASYNCIO_COROUTINE = "asyncio.coroutines.coroutine"
str BUILTIN_TUPLE = "builtins.tuple"
tuple TYPE_ANNOTATION_NODES_TYPES
dict BUILTINS_IMPLICIT_RETURN_NONE
VERSION_COMPATIBLE_OVERLOAD_SENTINEL = VERSION_COMPATIBLE_OVERLOAD()
dict MSGS
dict SEQUENCE_TYPES
str name = "type" for cls in mro)
Detailed Description
Try to find more bugs in the code using astroid inference capabilities.
Function Documentation
_()
Iterable[str] pylint.checkers.typecheck._ (nodes.ClassDef | bases.Instance node) protected
Definition at line 141 of file typecheck.py.
def _(node: nodes.ClassDef | bases.Instance) -> Iterable[str]:
    values = itertools.chain(node.instance_attrs.keys(), node.locals.keys())
    try:
        mro = node.mro()[1:]
    except (NotImplementedError, TypeError, astroid.MroError):
        mro = node.ancestors()
    other_values = [value for cls in mro for value in _node_names(cls)]
    return itertools.chain(values, other_values)
References _node_names().
_determine_callable()
tuple[CallableObjects, int, str] pylint.checkers.typecheck._determine_callable (nodes.NodeNG callable_obj) protected
Definition at line 607 of file typecheck.py.
) -> tuple[CallableObjects, int, str]:
    # TODO: The typing of the second return variable is actually Literal[0,1]
    # We need typing on astroid.NodeNG.implicit_parameters for this
    # TODO: The typing of the third return variable can be narrowed to a Literal
    # We need typing on astroid.NodeNG.type for this
    # Ordering is important, since BoundMethod is a subclass of UnboundMethod,
    # and Function inherits Lambda.
    parameters = 0
    if hasattr(callable_obj, "implicit_parameters"):
        parameters = callable_obj.implicit_parameters()
    if isinstance(callable_obj, bases.BoundMethod):
        # Bound methods have an extra implicit 'self' argument.
        return callable_obj, parameters, callable_obj.type
    if isinstance(callable_obj, bases.UnboundMethod):
        return callable_obj, parameters, "unbound method"
    if isinstance(callable_obj, nodes.FunctionDef):
        return callable_obj, parameters, callable_obj.type
    if isinstance(callable_obj, nodes.Lambda):
        return callable_obj, parameters, "lambda"
    if isinstance(callable_obj, nodes.ClassDef):
        # Class instantiation, lookup __new__ instead.
        # If we only find object.__new__, we can safely check __init__
        # instead. If __new__ belongs to builtins, then we look
        # again for __init__ in the locals, since we won't have
        # argument information for the builtin __new__ function.
        try:
            # Use the last definition of __new__.
            new = callable_obj.local_attr("__new__")[-1]
        except astroid.NotFoundError:
            new = None
        from_object = new and new.parent.scope().name == "object"
        from_builtins = new and new.root().name in sys.builtin_module_names
        if not new or from_object or from_builtins:
            try:
                # Use the last definition of __init__.
                callable_obj = callable_obj.local_attr("__init__")[-1]
            except astroid.NotFoundError as e:
                raise ValueError from e
        else:
            callable_obj = new
        if not isinstance(callable_obj, nodes.FunctionDef):
            raise ValueError
        # both have an extra implicit 'cls'/'self' argument.
        return callable_obj, parameters, "constructor"
    raise ValueError
Referenced by pylint.checkers.typecheck.TypeChecker.visit_call().
_emit_no_member()
bool pylint.checkers.typecheck._emit_no_member (nodes.Attribute | nodes.AssignAttr | nodes.DelAttr node, InferenceResult owner, str | None owner_name, Pattern[str] mixin_class_rgx, bool ignored_mixins = True, bool ignored_none = True) protected
Try to see if no-member should be emitted for the given owner.
The following cases are ignored:
    * the owner is a function and it has decorators.
    * the owner is an instance and it has __getattr__, __getattribute__ implemented
    * the module is explicitly ignored from no-member checks
    * the owner is a class and the name can be found in its metaclass.
    * The access node is protected by an except handler, which handles
      AttributeError, Exception or bare except.
    * The node is guarded behind and `IF` or `IFExp` node
Definition at line 427 of file typecheck.py.
) -> bool:
    """Try to see if no-member should be emitted for the given owner.
    The following cases are ignored:
        * the owner is a function and it has decorators.
        * the owner is an instance and it has __getattr__, __getattribute__ implemented
        * the module is explicitly ignored from no-member checks
        * the owner is a class and the name can be found in its metaclass.
        * The access node is protected by an except handler, which handles
          AttributeError, Exception or bare except.
        * The node is guarded behind and `IF` or `IFExp` node
    """
    # pylint: disable = too-many-return-statements, too-many-branches
    if node_ignores_exception(node, AttributeError):
        return False
    if ignored_none and isinstance(owner, nodes.Const) and owner.value is None:
        return False
    if is_super(owner) or getattr(owner, "type", None) == "metaclass":
        return False
    if owner_name and ignored_mixins and mixin_class_rgx.match(owner_name):
        return False
    if isinstance(owner, nodes.FunctionDef) and (
        owner.decorators or owner.is_abstract()
    ):
        return False
    if isinstance(owner, (astroid.Instance, nodes.ClassDef)):
        # Issue #2565: Don't ignore enums, as they have a `__getattr__` but it's not
        # invoked at this point.
        try:
            metaclass = owner.metaclass()
        except astroid.MroError:
            pass
        else:
            # Renamed in Python 3.10 to `EnumType`
            if metaclass and metaclass.qname() in {"enum.EnumMeta", "enum.EnumType"}:
                return not _enum_has_attribute(owner, node)
        if owner.has_dynamic_getattr():
            return False
        if not has_known_bases(owner):
            return False
        # Exclude typed annotations, since these might actually exist
        # at some point during the runtime of the program.
        if utils.is_attribute_typed_annotation(owner, node.attrname):
            return False
    if isinstance(owner, astroid.objects.Super):
        # Verify if we are dealing with an invalid Super object.
        # If it is invalid, then there's no point in checking that
        # it has the required attribute. Also, don't fail if the
        # MRO is invalid.
        try:
            owner.super_mro()
        except (astroid.MroError, astroid.SuperError):
            return False
        if not all(has_known_bases(base) for base in owner.type.mro()):
            return False
    if isinstance(owner, nodes.Module):
        try:
            owner.getattr("__getattr__")
            return False
        except astroid.NotFoundError:
            pass
    if owner_name and node.attrname.startswith("_" + owner_name):
        # Test if an attribute has been mangled ('private' attribute)
        unmangled_name = node.attrname.split("_" + owner_name)[-1]
        try:
            if owner.getattr(unmangled_name, context=None) is not None:
                return False
        except astroid.NotFoundError:
            return True
    # Don't emit no-member if guarded behind `IF` or `IFExp`
    #   * Walk up recursively until if statement is found.
    #   * Check if condition can be inferred as `Const`,
    #       would evaluate as `False`,
    #       and whether the node is part of the `body`.
    #   * Continue checking until scope of node is reached.
    scope: nodes.NodeNG = node.scope()
    node_origin: nodes.NodeNG = node
    parent: nodes.NodeNG = node.parent
    while parent != scope:
        if isinstance(parent, (nodes.If, nodes.IfExp)):
            inferred = safe_infer(parent.test)
            if (  # pylint: disable=too-many-boolean-expressions
                isinstance(inferred, nodes.Const)
                and inferred.bool_value() is False
                and (
                    isinstance(parent, nodes.If)
                    and node_origin in parent.body
                    or isinstance(parent, nodes.IfExp)
                    and node_origin == parent.body
                )
            ):
                return False
        node_origin, parent = parent, parent.parent
    return True
References _enum_has_attribute().
Referenced by pylint.checkers.typecheck.TypeChecker.visit_attribute().
_enum_has_attribute()
bool pylint.checkers.typecheck._enum_has_attribute (astroid.Instance | nodes.ClassDef owner, nodes.Attribute node) protected
Definition at line 557 of file typecheck.py.
) -> bool:
    if isinstance(owner, astroid.Instance):
        enum_def = next(
            (b.parent for b in owner.bases if isinstance(b.parent, nodes.ClassDef)),
            None,
        )
        if enum_def is None:
            # We don't inherit from anything, so try to find the parent
            # class definition and roll with that
            enum_def = node
            while enum_def is not None and not isinstance(enum_def, nodes.ClassDef):
                enum_def = enum_def.parent
        # If this blows, something is clearly wrong
        assert enum_def is not None, "enum_def unexpectedly None"
    else:
        enum_def = owner
    # Find __new__ and __init__
    dunder_new = next((m for m in enum_def.methods() if m.name == "__new__"), None)
    dunder_init = next((m for m in enum_def.methods() if m.name == "__init__"), None)
    enum_attributes: set[str] = set()
    # Find attributes defined in __new__
    if dunder_new:
        # Get the object returned in __new__
        returned_obj_name = next(
            (c.value for c in dunder_new.get_children() if isinstance(c, nodes.Return)),
            None,
        )
        if isinstance(returned_obj_name, nodes.Name):
            # Find all attribute assignments to the returned object
            enum_attributes |= _get_all_attribute_assignments(
                dunder_new, returned_obj_name.name
            )
    # Find attributes defined in __init__
    if dunder_init and dunder_init.body and dunder_init.args:
        # Grab the name referring to `self` from the function def
        enum_attributes |= _get_all_attribute_assignments(
            dunder_init, dunder_init.args.arguments[0].name
        )
    return node.attrname in enum_attributes
References _get_all_attribute_assignments().
Referenced by _emit_no_member().
_get_all_attribute_assignments()
set[str] pylint.checkers.typecheck._get_all_attribute_assignments (nodes.FunctionDef node, str | None name = None) protected
Definition at line 534 of file typecheck.py.
) -> set[str]:
    attributes: set[str] = set()
    for child in node.nodes_of_class((nodes.Assign, nodes.AnnAssign)):
        targets = []
        if isinstance(child, nodes.Assign):
            targets = child.targets
        elif isinstance(child, nodes.AnnAssign):
            targets = [child.target]
        for assign_target in targets:
            if isinstance(assign_target, nodes.Tuple):
                targets.extend(assign_target.elts)
                continue
            if (
                isinstance(assign_target, nodes.AssignAttr)
                and isinstance(assign_target.expr, nodes.Name)
                and (name is None or assign_target.expr.name == name)
            ):
                attributes.add(assign_target.attrname)
    return attributes
Referenced by _enum_has_attribute().
_has_parent_of_type()
bool pylint.checkers.typecheck._has_parent_of_type (nodes.Call node, nodes.Keyword | nodes.Starred node_type, _base_nodes.Statement statement) protected
Check if the given node has a parent of the given type.
Definition at line 661 of file typecheck.py.
) -> bool:
    """Check if the given node has a parent of the given type."""
    parent = node.parent
    while not isinstance(parent, node_type) and statement.parent_of(parent):
        parent = parent.parent
    return isinstance(parent, node_type)
Referenced by _no_context_variadic().
_infer_from_metaclass_constructor()
InferenceResult | None pylint.checkers.typecheck._infer_from_metaclass_constructor (nodes.ClassDef cls, nodes.FunctionDef func) protected
Try to infer what the given *func* constructor is building.
:param astroid.FunctionDef func:
    A metaclass constructor. Metaclass definitions can be
    functions, which should accept three arguments, the name of
    the class, the bases of the class and the attributes.
    The function could return anything, but usually it should
    be a proper metaclass.
:param astroid.ClassDef cls:
    The class for which the *func* parameter should generate
    a metaclass.
:returns:
    The class generated by the function or None,
    if we couldn't infer it.
:rtype: astroid.ClassDef
Definition at line 758 of file typecheck.py.
) -> InferenceResult | None:
    """Try to infer what the given *func* constructor is building.
    :param astroid.FunctionDef func:
        A metaclass constructor. Metaclass definitions can be
        functions, which should accept three arguments, the name of
        the class, the bases of the class and the attributes.
        The function could return anything, but usually it should
        be a proper metaclass.
    :param astroid.ClassDef cls:
        The class for which the *func* parameter should generate
        a metaclass.
    :returns:
        The class generated by the function or None,
        if we couldn't infer it.
    :rtype: astroid.ClassDef
    """
    context = astroid.context.InferenceContext()
    class_bases = nodes.List()
    class_bases.postinit(elts=cls.bases)
    attrs = nodes.Dict(
        lineno=0, col_offset=0, parent=None, end_lineno=0, end_col_offset=0
    )
    local_names = [(name, values[-1]) for name, values in cls.locals.items()]
    attrs.postinit(local_names)
    builder_args = nodes.Tuple()
    builder_args.postinit([cls.name, class_bases, attrs])
    context.callcontext = astroid.context.CallContext(builder_args)
    try:
        inferred = next(func.infer_call_result(func, context), None)
    except astroid.InferenceError:
        return None
    return inferred or None
Referenced by pylint.checkers.typecheck.TypeChecker.visit_classdef().
_is_c_extension()
bool pylint.checkers.typecheck._is_c_extension (InferenceResult module_node) protected
Definition at line 799 of file typecheck.py.
def _is_c_extension(module_node: InferenceResult) -> bool:
    return (
        isinstance(module_node, nodes.Module)
        and not astroid.modutils.is_stdlib_module(module_node.name)
        and not module_node.fully_defined()
    )
References astroid.modutils.is_stdlib_module().
Referenced by pylint.checkers.typecheck.TypeChecker._get_nomember_msgid_hint().
_is_invalid_isinstance_type()
bool pylint.checkers.typecheck._is_invalid_isinstance_type (nodes.NodeNG arg) protected
Definition at line 807 of file typecheck.py.
def _is_invalid_isinstance_type(arg: nodes.NodeNG) -> bool:
    # Return True if we are sure that arg is not a type
    if PY310_PLUS and isinstance(arg, nodes.BinOp) and arg.op == "|":
        return any(
            _is_invalid_isinstance_type(elt) and not is_none(elt)
            for elt in (arg.left, arg.right)
        )
    inferred = utils.safe_infer(arg)
    if not inferred:
        # Cannot infer it so skip it.
        return False
    if isinstance(inferred, nodes.Tuple):
        return any(_is_invalid_isinstance_type(elt) for elt in inferred.elts)
    if isinstance(inferred, nodes.ClassDef):
        return False
    if isinstance(inferred, astroid.Instance) and inferred.qname() == BUILTIN_TUPLE:
        return False
    if PY310_PLUS and isinstance(inferred, bases.UnionType):
        return any(
            _is_invalid_isinstance_type(elt) and not is_none(elt)
            for elt in (inferred.left, inferred.right)
        )
    return True
References _is_invalid_isinstance_type().
Referenced by pylint.checkers.typecheck.TypeChecker._check_isinstance_args(), and _is_invalid_isinstance_type().
_is_invalid_metaclass()
bool pylint.checkers.typecheck._is_invalid_metaclass (nodes.ClassDef metaclass) protected
Definition at line 750 of file typecheck.py.
def _is_invalid_metaclass(metaclass: nodes.ClassDef) -> bool:
    try:
        mro = metaclass.mro()
    except (astroid.DuplicateBasesError, astroid.InconsistentMroError):
        return True
    return not any(is_builtin_object(cls) and cls.name == "type" for cls in mro)
Referenced by pylint.checkers.typecheck.TypeChecker.visit_classdef().
_is_owner_ignored()
bool pylint.checkers.typecheck._is_owner_ignored (SuccessfulInferenceResult owner, str | None attrname, Iterable[str] ignored_classes, Iterable[str] ignored_modules) protected
Check if the given owner should be ignored.
This will verify if the owner's module is in *ignored_modules*
or the owner's module fully qualified name is in *ignored_modules*
or if the *ignored_modules* contains a pattern which catches
the fully qualified name of the module.
Also, similar checks are done for the owner itself, if its name
matches any name from the *ignored_classes* or if its qualified
name can be found in *ignored_classes*.
Definition at line 106 of file typecheck.py.
) -> bool:
    """Check if the given owner should be ignored.
    This will verify if the owner's module is in *ignored_modules*
    or the owner's module fully qualified name is in *ignored_modules*
    or if the *ignored_modules* contains a pattern which catches
    the fully qualified name of the module.
    Also, similar checks are done for the owner itself, if its name
    matches any name from the *ignored_classes* or if its qualified
    name can be found in *ignored_classes*.
    """
    if is_module_ignored(owner.root().qname(), ignored_modules):
        return True
    # Match against ignored classes.
    ignored_classes = set(ignored_classes)
    qname = owner.qname() if hasattr(owner, "qname") else ""
    return any(ignore in (attrname, qname) for ignore in ignored_classes)
@singledispatch
Referenced by pylint.checkers.typecheck.TypeChecker.visit_attribute().
_missing_member_hint()
str pylint.checkers.typecheck._missing_member_hint (SuccessfulInferenceResult owner, str | None attrname, int distance_threshold, int max_choices) protected
Definition at line 204 of file typecheck.py.
) -> str:
    names = _similar_names(owner, attrname, distance_threshold, max_choices)
    if not names:
        # No similar name.
        return ""
    names = [repr(name) for name in names]
    if len(names) == 1:
        names_hint = ", ".join(names)
    else:
        names_hint = f"one of {', '.join(names[:-1])} or {names[-1]}"
    return f"; maybe {names_hint}?"
References _similar_names().
Referenced by pylint.checkers.typecheck.TypeChecker._get_nomember_msgid_hint().
_no_context_variadic()
bool pylint.checkers.typecheck._no_context_variadic (nodes.Call node, str | None variadic_name, nodes.Keyword | nodes.Starred variadic_type, list[nodes.Keyword | nodes.Starred] variadics) protected
Verify if the given call node has variadic nodes without context.
This is a workaround for handling cases of nested call functions
which don't have the specific call context at hand.
Variadic arguments (variable positional arguments and variable
keyword arguments) are inferred, inherently wrong, by astroid
as a Tuple, respectively a Dict with empty elements.
This can lead pylint to believe that a function call receives
too few arguments.
Definition at line 697 of file typecheck.py.
) -> bool:
    """Verify if the given call node has variadic nodes without context.
    This is a workaround for handling cases of nested call functions
    which don't have the specific call context at hand.
    Variadic arguments (variable positional arguments and variable
    keyword arguments) are inferred, inherently wrong, by astroid
    as a Tuple, respectively a Dict with empty elements.
    This can lead pylint to believe that a function call receives
    too few arguments.
    """
    scope = node.scope()
    is_in_lambda_scope = not isinstance(scope, nodes.FunctionDef) and isinstance(
        scope, nodes.Lambda
    )
    statement = node.statement()
    for name in statement.nodes_of_class(nodes.Name):
        if name.name != variadic_name:
            continue
        inferred = safe_infer(name)
        if isinstance(inferred, (nodes.List, nodes.Tuple)):
            length = len(inferred.elts)
        elif isinstance(inferred, nodes.Dict):
            length = len(inferred.items)
        else:
            continue
        if is_in_lambda_scope and isinstance(inferred.parent, nodes.Arguments):
            # The statement of the variadic will be the assignment itself,
            # so we need to go the lambda instead
            inferred_statement = inferred.parent.parent
        else:
            inferred_statement = inferred.statement()
        if not length and isinstance(
            inferred_statement, (nodes.Lambda, nodes.FunctionDef)
        ):
            is_in_starred_context = _has_parent_of_type(node, variadic_type, statement)
            used_as_starred_argument = any(
                variadic.value == name or variadic.value.parent_of(name)
                for variadic in variadics
            )
            if is_in_starred_context or used_as_starred_argument:
                return True
    return False
References _has_parent_of_type().
Referenced by _no_context_variadic_keywords(), and _no_context_variadic_positional().
_no_context_variadic_keywords()
bool pylint.checkers.typecheck._no_context_variadic_keywords (nodes.Call node, nodes.Lambda scope) protected
Definition at line 673 of file typecheck.py.
def _no_context_variadic_keywords(node: nodes.Call, scope: nodes.Lambda) -> bool:
    statement = node.statement()
    variadics = []
    if (
        isinstance(scope, nodes.Lambda)
        and not isinstance(scope, nodes.FunctionDef)
        or isinstance(statement, nodes.With)
    ):
        variadics = list(node.keywords or []) + node.kwargs
    elif isinstance(statement, (nodes.Return, nodes.Expr, nodes.Assign)) and isinstance(
        statement.value, nodes.Call
    ):
        call = statement.value
        variadics = list(call.keywords or []) + call.kwargs
    return _no_context_variadic(node, scope.args.kwarg, nodes.Keyword, variadics)
References _no_context_variadic().
Referenced by pylint.checkers.typecheck.TypeChecker.visit_call().
_no_context_variadic_positional()
bool pylint.checkers.typecheck._no_context_variadic_positional (nodes.Call node, nodes.Lambda scope) protected
Definition at line 692 of file typecheck.py.
def _no_context_variadic_positional(node: nodes.Call, scope: nodes.Lambda) -> bool:
    variadics = node.starargs + node.kwargs
    return _no_context_variadic(node, scope.args.vararg, nodes.Starred, variadics)
References _no_context_variadic().
Referenced by pylint.checkers.typecheck.TypeChecker.visit_call().
_node_names()
Iterable[str] pylint.checkers.typecheck._node_names (SuccessfulInferenceResult node) protected
Definition at line 133 of file typecheck.py.
def _node_names(node: SuccessfulInferenceResult) -> Iterable[str]:
    if not hasattr(node, "locals"):
        return []
    return node.locals.keys()  # type: ignore[no-any-return]
@_node_names.register(nodes.ClassDef)
@_node_names.register(astroid.Instance)
Referenced by _(), and _similar_names().
_similar_names()
list[str] pylint.checkers.typecheck._similar_names (SuccessfulInferenceResult owner, str | None attrname, int distance_threshold, int max_choices) protected
Given an owner and a name, try to find similar names.
The similar names are searched given a distance metric and only
a given number of choices will be returned.
Definition at line 171 of file typecheck.py.
) -> list[str]:
    """Given an owner and a name, try to find similar names.
    The similar names are searched given a distance metric and only
    a given number of choices will be returned.
    """
    possible_names: list[tuple[str, int]] = []
    names = _node_names(owner)
    for name in names:
        if name == attrname:
            continue
        distance = _string_distance(attrname or "", name)
        if distance <= distance_threshold:
            possible_names.append((name, distance))
    # Now get back the values with a minimum, up to the given
    # limit or choices.
    picked = [
        name
        for (name, _) in heapq.nsmallest(
            max_choices, possible_names, key=operator.itemgetter(1)
        )
    ]
    return sorted(picked)
References _node_names(), and _string_distance().
Referenced by _missing_member_hint().
_string_distance()
int pylint.checkers.typecheck._string_distance (str seq1, str seq2) protected
Definition at line 153 of file typecheck.py.
def _string_distance(seq1: str, seq2: str) -> int:
    seq2_length = len(seq2)
    row = [*list(range(1, seq2_length + 1)), 0]
    for seq1_index, seq1_char in enumerate(seq1):
        last_row = row
        row = [0] * seq2_length + [seq1_index + 1]
        for seq2_index, seq2_char in enumerate(seq2):
            row[seq2_index] = min(
                last_row[seq2_index] + 1,
                row[seq2_index - 1] + 1,
                last_row[seq2_index - 1] + (seq1_char != seq2_char),
            )
    return row[seq2_length - 1]
Referenced by _similar_names().
register()
None pylint.checkers.typecheck.register (PyLinter linter)
Definition at line 2337 of file typecheck.py.
def register(linter: PyLinter) -> None:
    linter.register_checker(TypeChecker(linter))
    linter.register_checker(IterableChecker(linter))
Variable Documentation
ASYNCIO_COROUTINE
str pylint.checkers.typecheck.ASYNCIO_COROUTINE = "asyncio.coroutines.coroutine"
Definition at line 68 of file typecheck.py.
BUILTIN_TUPLE
str pylint.checkers.typecheck.BUILTIN_TUPLE = "builtins.tuple"
Definition at line 69 of file typecheck.py.
BUILTINS_IMPLICIT_RETURN_NONE
dict pylint.checkers.typecheck.BUILTINS_IMPLICIT_RETURN_NONE
Initial value:
=  {
    "builtins.dict": {"clear", "update"},
    "builtins.list": {
        "append",
        "clear",
        "extend",
        "insert",
        "remove",
        "reverse",
        "sort",
    },
    "builtins.set": {
        "add",
        "clear",
        "difference_update",
        "discard",
        "intersection_update",
        "remove",
        "symmetric_difference_update",
        "update",
    },
}
Definition at line 75 of file typecheck.py.
CallableObjects
pylint.checkers.typecheck.CallableObjects
Initial value:
=  Union[
    bases.BoundMethod,
    bases.UnboundMethod,
    nodes.FunctionDef,
    nodes.Lambda,
    nodes.ClassDef,
]
Definition at line 59 of file typecheck.py.
MSGS
dict pylint.checkers.typecheck.MSGS
Definition at line 224 of file typecheck.py.
name
pylint.checkers.typecheck.name = "type" for cls in mro)
Definition at line 755 of file typecheck.py.
SEQUENCE_TYPES
dict pylint.checkers.typecheck.SEQUENCE_TYPES
Initial value:
=  {
    "str",
    "unicode",
    "list",
    "tuple",
    "bytearray",
    "xrange",
    "range",
    "bytes",
    "memoryview",
}
Definition at line 414 of file typecheck.py.
STR_FORMAT
dict pylint.checkers.typecheck.STR_FORMAT = {"builtins.str.format"}
Definition at line 67 of file typecheck.py.
TYPE_ANNOTATION_NODES_TYPES
tuple pylint.checkers.typecheck.TYPE_ANNOTATION_NODES_TYPES
Initial value:
=  (
    nodes.AnnAssign,
    nodes.Arguments,
    nodes.FunctionDef,
)
Definition at line 70 of file typecheck.py.
VERSION_COMPATIBLE_OVERLOAD_SENTINEL
pylint.checkers.typecheck.VERSION_COMPATIBLE_OVERLOAD_SENTINEL = VERSION_COMPATIBLE_OVERLOAD()
Definition at line 103 of file typecheck.py.