Read&Watch: pip._vendor.packaging._musllinux Namespace Reference
pip._vendor.packaging._musllinux Namespace Reference
Classes
class _MuslVersion
Functions
_MuslVersion|None _parse_musl_version (str output)
_MuslVersion|None _get_musl_version (str executable)
Iterator[str] platform_tags (Sequence[str] archs)
Variables
plat = sysconfig.get_platform()
end
t
Detailed Description
PEP 656 support.
This module implements logic to detect if the currently running Python is
linked against musl, and what musl version is used.
Function Documentation
_get_musl_version()
_MuslVersion | None pip._vendor.packaging._musllinux._get_musl_version (str executable) protected
Detect currently-running musl runtime version.
This is done by checking the specified executable's dynamic linking
information, and invoking the loader to parse its output for a version
string. If the loader is musl, the output would be something like::
    musl libc (x86_64)
    Version 1.2.2
    Dynamic Program Loader
Definition at line 34 of file _musllinux.py.
def _get_musl_version(executable: str) -> _MuslVersion | None:
    """Detect currently-running musl runtime version.
    This is done by checking the specified executable's dynamic linking
    information, and invoking the loader to parse its output for a version
    string. If the loader is musl, the output would be something like::
        musl libc (x86_64)
        Version 1.2.2
        Dynamic Program Loader
    """
    try:
        with open(executable, "rb") as f:
            ld = ELFFile(f).interpreter
    except (OSError, TypeError, ValueError):
        return None
    if ld is None or "musl" not in ld:
        return None
    proc = subprocess.run([ld], stderr=subprocess.PIPE, text=True)
    return _parse_musl_version(proc.stderr)
References _parse_musl_version().
Referenced by platform_tags().
_parse_musl_version()
_MuslVersion | None pip._vendor.packaging._musllinux._parse_musl_version (str output) protected
Definition at line 23 of file _musllinux.py.
def _parse_musl_version(output: str) -> _MuslVersion | None:
    lines = [n for n in (n.strip() for n in output.splitlines()) if n]
    if len(lines) < 2 or lines[0][:4] != "musl":
        return None
    m = re.match(r"Version (\d+)\.(\d+)", lines[1])
    if not m:
        return None
    return _MuslVersion(major=int(m.group(1)), minor=int(m.group(2)))
@functools.lru_cache
Referenced by _get_musl_version().
platform_tags()
Iterator[str] pip._vendor.packaging._musllinux.platform_tags (Sequence[str] archs)
Generate musllinux tags compatible to the current platform.
:param archs: Sequence of compatible architectures.
    The first one shall be the closest to the actual architecture and be the part of
    platform tag after the ``linux_`` prefix, e.g. ``x86_64``.
    The ``linux_`` prefix is assumed as a prerequisite for the current platform to
    be musllinux-compatible.
:returns: An iterator of compatible musllinux tags.
Definition at line 56 of file _musllinux.py.
def platform_tags(archs: Sequence[str]) -> Iterator[str]:
    """Generate musllinux tags compatible to the current platform.
    :param archs: Sequence of compatible architectures.
        The first one shall be the closest to the actual architecture and be the part of
        platform tag after the ``linux_`` prefix, e.g. ``x86_64``.
        The ``linux_`` prefix is assumed as a prerequisite for the current platform to
        be musllinux-compatible.
    :returns: An iterator of compatible musllinux tags.
    """
    sys_musl = _get_musl_version(sys.executable)
    if sys_musl is None:  # Python not dynamically linked against musl.
        return
    for arch in archs:
        for minor in range(sys_musl.minor, -1, -1):
            yield f"musllinux_{sys_musl.major}_{minor}_{arch}"
References _get_musl_version().
Variable Documentation
end
pip._vendor.packaging._musllinux.end
Definition at line 83 of file _musllinux.py.
plat
pip._vendor.packaging._musllinux.plat = sysconfig.get_platform()
Definition at line 78 of file _musllinux.py.
t
pip._vendor.packaging._musllinux.t
Definition at line 85 of file _musllinux.py.