Read&Watch: dill Namespace Reference
dill Namespace Reference
Namespaces
namespace __diff
namespace __info__
namespace _dill
namespace _objects
namespace _shims
namespace detect
namespace logger
namespace objtypes
namespace pointers
namespace session
namespace settings
namespace source
namespace temp
namespace tests
Functions
extend (use_dill=True)
license ()
citation ()
Variables
parent = os.path.dirname(os.path.abspath(os.path.dirname(__file__)))
dict objects = {}
True
unpickleable
Function Documentation
citation()
dill.citation ()
print citation
Definition at line 114 of file __init__.py.
def citation():
    """print citation"""
    print (__doc__[-491:-118])
    return
# end of file
extend()
dill.extend (use_dill = True)
add (or remove) dill types to/from the pickle registry
by default, ``dill`` populates its types to ``pickle.Pickler.dispatch``.
Thus, all ``dill`` types are available upon calling ``'import pickle'``.
To drop all ``dill`` types from the ``pickle`` dispatch, *use_dill=False*.
Args:
    use_dill (bool, default=True): if True, extend the dispatch table.
Returns:
    None
Definition at line 88 of file __init__.py.
def extend(use_dill=True):
    '''add (or remove) dill types to/from the pickle registry
    by default, ``dill`` populates its types to ``pickle.Pickler.dispatch``.
    Thus, all ``dill`` types are available upon calling ``'import pickle'``.
    To drop all ``dill`` types from the ``pickle`` dispatch, *use_dill=False*.
    Args:
        use_dill (bool, default=True): if True, extend the dispatch table.
    Returns:
        None
    '''
    from ._dill import _revert_extension, _extend
    if use_dill: _extend()
    else: _revert_extension()
    return
References extend().
Referenced by extend().
license()
dill.license ()
print license
Definition at line 109 of file __init__.py.
def license():
    """print license"""
    print (__license__)
    return
Variable Documentation
objects
dict dill.objects = {}
Definition at line 45 of file __init__.py.
parent
dill.parent = os.path.dirname(os.path.abspath(os.path.dirname(__file__)))
Definition at line 15 of file __init__.py.
Referenced by dill.tests.test_detect.test_parent().
True
dill.True
Definition at line 54 of file __init__.py.
unpickleable
dill.unpickleable
Definition at line 54 of file __init__.py.