Read&Watch: dill.tests.test_nested Namespace Reference
dill.tests.test_nested Namespace Reference
Classes
class basic
class basic2
class c2adder
class cadder
Functions
adder (augend)
test_basic ()
test_basic_class ()
test_c2adder ()
test_pickled_cadder ()
test_raw_adder_and_inner ()
test_pickled_adder ()
test_pickled_inner ()
test_moduledict_where_not_main ()
Variables
int x = 5
int y = 1
Detailed Description
test dill's ability to handle nested functions
Function Documentation
adder()
dill.tests.test_nested.adder (augend)
Definition at line 20 of file test_nested.py.
def adder(augend):
    zero = [0]
    def inner(addend):
        return addend + augend + zero[0]
    return inner
# rewrite the nested function using a class: standard pickle should work here.
Referenced by test_pickled_inner(), and test_raw_adder_and_inner().
test_basic()
dill.tests.test_nested.test_basic ()
Definition at line 61 of file test_nested.py.
def test_basic():
    a = [0, 1, 2]
    pa = pickle.dumps(a)
    pmath = pickle.dumps(math) #XXX: FAILS in pickle
    pmap = pickle.dumps(map)
    # ...
    la = pickle.loads(pa)
    lmath = pickle.loads(pmath)
    lmap = pickle.loads(pmap)
    assert list(map(math.sin, a)) == list(lmap(lmath.sin, la))
Referenced by test_moduledict_where_not_main().
test_basic_class()
dill.tests.test_nested.test_basic_class ()
Definition at line 73 of file test_nested.py.
def test_basic_class():
    pbasic2 = pickle.dumps(basic2)
    _pbasic2 = pickle.loads(pbasic2)()
    pbasic = pickle.dumps(basic)
    _pbasic = pickle.loads(pbasic)()
Referenced by test_moduledict_where_not_main().
test_c2adder()
dill.tests.test_nested.test_c2adder ()
Definition at line 80 of file test_nested.py.
def test_c2adder():
    pc2adder = pickle.dumps(c2adder)
    pc2add5 = pickle.loads(pc2adder)(x)
    assert pc2add5(y) == x+y
Referenced by test_moduledict_where_not_main().
test_moduledict_where_not_main()
dill.tests.test_nested.test_moduledict_where_not_main ()
Definition at line 110 of file test_nested.py.
def test_moduledict_where_not_main():
    try:
        from . import test_moduledict
    except ImportError:
        import test_moduledict
    name = 'test_moduledict.py'
    if os.path.exists(name) and os.path.exists(name+'c'):
        os.remove(name+'c')
    if os.path.exists(name) and hasattr(test_moduledict, "__cached__") \
       and os.path.exists(test_moduledict.__cached__):
        os.remove(getattr(test_moduledict, "__cached__"))
    if os.path.exists("__pycache__") and not os.listdir("__pycache__"):
        os.removedirs("__pycache__")
References test_basic(), test_basic_class(), test_c2adder(), test_moduledict_where_not_main(), test_pickled_adder(), test_pickled_cadder(), test_pickled_inner(), and test_raw_adder_and_inner().
Referenced by test_moduledict_where_not_main().
test_pickled_adder()
dill.tests.test_nested.test_pickled_adder ()
Definition at line 97 of file test_nested.py.
def test_pickled_adder():
    padder = pickle.dumps(adder)
    padd5 = pickle.loads(padder)(x)
    assert padd5(y) == x+y
Referenced by test_moduledict_where_not_main().
test_pickled_cadder()
dill.tests.test_nested.test_pickled_cadder ()
Definition at line 86 of file test_nested.py.
def test_pickled_cadder():
    pcadder = pickle.dumps(cadder)
    pcadd5 = pickle.loads(pcadder)(x)
    assert pcadd5(y) == x+y
Referenced by test_moduledict_where_not_main().
test_pickled_inner()
dill.tests.test_nested.test_pickled_inner ()
Definition at line 103 of file test_nested.py.
def test_pickled_inner():
    add5 = adder(x)
    pinner = pickle.dumps(add5) #XXX: FAILS in pickle
    p5add = pickle.loads(pinner)
    assert p5add(y) == x+y
References adder().
Referenced by test_moduledict_where_not_main().
test_raw_adder_and_inner()
dill.tests.test_nested.test_raw_adder_and_inner ()
Definition at line 92 of file test_nested.py.
def test_raw_adder_and_inner():
    add5 = adder(x)
    assert add5(y) == x+y
References adder().
Referenced by test_moduledict_where_not_main().
Variable Documentation
x
int dill.tests.test_nested.x = 5
Definition at line 57 of file test_nested.py.
y
int dill.tests.test_nested.y = 1
Definition at line 58 of file test_nested.py.