Read&Watch: dill.tests.test_temp Namespace Reference
dill.tests.test_temp Namespace Reference
Classes
class Bar
class Foo
Functions
test_code_to_tempfile ()
test_code_to_stream ()
test_pickle_to_tempfile ()
test_pickle_to_stream ()
g (x)
h (x)
add (x, y)
test_two_arg_functions ()
test_one_arg_functions ()
test_the_rest ()
Variables
str WINDOWS = 'win'
x f = lambda x**2
now testing the objects ###
list x = [1,2,3,4,5]
_foo = Foo()
x squared = lambda x**2
_bar = Bar()
Function Documentation
add()
dill.tests.test_temp.add (x, y)
Definition at line 57 of file test_temp.py.
def add(x,y):
  return x+y
# yes, same as 'f', but things are tricky when it comes to pointers
g()
dill.tests.test_temp.g (x)
Definition at line 46 of file test_temp.py.
def g(x): return f(x) - x
h()
dill.tests.test_temp.h (x)
Definition at line 48 of file test_temp.py.
def h(x):
  def g(x): return x
  return g(x) - x
test_code_to_stream()
dill.tests.test_temp.test_code_to_stream ()
Definition at line 26 of file test_temp.py.
def test_code_to_stream():
    pyfile = dumpIO_source(f, alias='_f')
    _f = loadIO_source(pyfile)
    assert _f(4) == f(4)
# pickle to tempfile
References f.
Referenced by test_the_rest().
test_code_to_tempfile()
dill.tests.test_temp.test_code_to_tempfile ()
Definition at line 19 of file test_temp.py.
def test_code_to_tempfile():
    if not WINDOWS:  #see: https://bugs.python.org/issue14243
        pyfile = dump_source(f, alias='_f')
        _f = load_source(pyfile)
        assert _f(4) == f(4)
# source code to stream
References f.
Referenced by test_the_rest().
test_one_arg_functions()
dill.tests.test_temp.test_one_arg_functions ()
Definition at line 76 of file test_temp.py.
def test_one_arg_functions():
  for obj in [g, h, squared]:
    pyfile = dumpIO_source(obj, alias='_obj')
    _obj = loadIO_source(pyfile)
    assert _obj(4) == obj(4)
# test instance-type objects
#for obj in [_bar, _foo]:
#  pyfile = dumpIO_source(obj, alias='_obj')
#  _obj = loadIO_source(pyfile)
#  assert type(_obj) == type(obj)
# test the rest of the objects
Referenced by test_the_rest().
test_pickle_to_stream()
dill.tests.test_temp.test_pickle_to_stream ()
Definition at line 39 of file test_temp.py.
def test_pickle_to_stream():
    dumpfile = dumpIO(x)
    _x = loadIO(dumpfile)
    assert _x == x
Referenced by test_the_rest().
test_pickle_to_tempfile()
dill.tests.test_temp.test_pickle_to_tempfile ()
Definition at line 32 of file test_temp.py.
def test_pickle_to_tempfile():
    if not WINDOWS:  #see: https://bugs.python.org/issue14243
        dumpfile = dump(x)
        _x = load(dumpfile)
        assert _x == x
# pickle to stream
Referenced by test_the_rest().
test_the_rest()
dill.tests.test_temp.test_the_rest ()
Definition at line 89 of file test_temp.py.
def test_the_rest():
  for obj in [Bar, Foo, Foo.bar, _foo.bar]:
    pyfile = dumpIO_source(obj, alias='_obj')
    _obj = loadIO_source(pyfile)
    assert _obj.__name__ == obj.__name__
References test_code_to_stream(), test_code_to_tempfile(), test_one_arg_functions(), test_pickle_to_stream(), test_pickle_to_tempfile(), test_the_rest(), and test_two_arg_functions().
Referenced by test_the_rest().
test_two_arg_functions()
dill.tests.test_temp.test_two_arg_functions ()
Definition at line 69 of file test_temp.py.
def test_two_arg_functions():
  for obj in [add]:
    pyfile = dumpIO_source(obj, alias='_obj')
    _obj = loadIO_source(pyfile)
    assert _obj(4,2) == obj(4,2)
# test function-type objects that take 1 arg
Referenced by test_the_rest().
Variable Documentation
_bar
dill.tests.test_temp._bar = Bar() protected
Definition at line 65 of file test_temp.py.
_foo
dill.tests.test_temp._foo = Foo() protected
Definition at line 55 of file test_temp.py.
f
x dill.tests.test_temp.f = lambda x**2
now testing the objects ###
Definition at line 15 of file test_temp.py.
Referenced by test_code_to_stream(), and test_code_to_tempfile().
squared
x dill.tests.test_temp.squared = lambda x**2
Definition at line 61 of file test_temp.py.
WINDOWS
str dill.tests.test_temp.WINDOWS = 'win'
Definition at line 12 of file test_temp.py.
x
list dill.tests.test_temp.x = [1,2,3,4,5]
Definition at line 16 of file test_temp.py.