Read&Watch: pylint.lint.caching Namespace Reference
pylint.lint.caching Namespace Reference
Functions
Path _get_pdata_path (Path base_name, int recurs, Path pylint_home=PYLINT_HOME_AS_PATH)
LinterStats|None load_results (str|Path base, str|Path pylint_home=PYLINT_HOME)
None save_results (LinterStats results, str|Path base, str|Path pylint_home=PYLINT_HOME)
Variables
PYLINT_HOME_AS_PATH = Path(PYLINT_HOME)
Function Documentation
_get_pdata_path()
Path pylint.lint.caching._get_pdata_path (Path base_name, int recurs, Path pylint_home = PYLINT_HOME_AS_PATH) protected
Definition at line 18 of file caching.py.
) -> Path:
    # We strip all characters that can't be used in a filename. Also strip '/' and
    # '\\' because we want to create a single file, not sub-directories.
    underscored_name = "_".join(
        str(p.replace(":", "_").replace("/", "_").replace("\\", "_"))
        for p in base_name.parts
    )
    return pylint_home / f"{underscored_name}_{recurs}.stats"
Referenced by load_results(), and save_results().
load_results()
LinterStats | None pylint.lint.caching.load_results (str | Path base, str | Path pylint_home = PYLINT_HOME)
Definition at line 30 of file caching.py.
) -> LinterStats | None:
    base = Path(base)
    pylint_home = Path(pylint_home)
    data_file = _get_pdata_path(base, 1, pylint_home)
    if not data_file.exists():
        return None
    try:
        with open(data_file, "rb") as stream:
            data = pickle.load(stream)
            if not isinstance(data, LinterStats):
                warnings.warn(
                    "You're using an old pylint cache with invalid data following "
                    f"an upgrade, please delete '{data_file}'.",
                    UserWarning,
                    stacklevel=2,
                )
                raise TypeError
            return data
    except Exception:  # pylint: disable=broad-except
        # There's an issue with the cache but we just continue as if it isn't there
        return None
References _get_pdata_path().
save_results()
None pylint.lint.caching.save_results (LinterStats results, str | Path base, str | Path pylint_home = PYLINT_HOME)
Definition at line 57 of file caching.py.
) -> None:
    base = Path(base)
    pylint_home = Path(pylint_home)
    try:
        pylint_home.mkdir(parents=True, exist_ok=True)
    except OSError:  # pragma: no cover
        print(f"Unable to create directory {pylint_home}", file=sys.stderr)
    data_file = _get_pdata_path(base, 1)
    try:
        with open(data_file, "wb") as stream:
            pickle.dump(results, stream)
    except OSError as ex:  # pragma: no cover
        print(f"Unable to create file {data_file}: {ex}", file=sys.stderr)
References _get_pdata_path().
Variable Documentation
PYLINT_HOME_AS_PATH
pylint.lint.caching.PYLINT_HOME_AS_PATH = Path(PYLINT_HOME)
Definition at line 15 of file caching.py.