Read&Watch: dill.tests.test_detect Namespace Reference
dill.tests.test_detect Namespace Reference
Classes
class _class
class Foo
Functions
test_bad_things ()
test_parent ()
squared (x)
foo (x)
test_globals ()
test_getstate ()
test_deleted ()
test_lambdify ()
Variables
a
b
c
list bar = [0]
f = Foo()
Function Documentation
foo()
dill.tests.test_detect.foo (x)
Definition at line 52 of file test_detect.py.
def foo(x):
  def bar(y):
    return squared(x)+y
  return bar
References squared().
squared()
dill.tests.test_detect.squared (x)
Definition at line 49 of file test_detect.py.
def squared(x):
  return a+x**2
Referenced by foo().
test_bad_things()
dill.tests.test_detect.test_bad_things ()
Definition at line 18 of file test_detect.py.
def test_bad_things():
    f = inspect.currentframe()
    assert baditems(f) == [f]
    #assert baditems(globals()) == [f] #XXX
    assert badobjects(f) is f
    assert badtypes(f) == type(f)
    assert type(errors(f)) is TypeError
    d = badtypes(f, 1)
    assert isinstance(d, dict)
    assert list(badobjects(f, 1).keys()) == list(d.keys())
    assert list(errors(f, 1).keys()) == list(d.keys())
    s = set([(err.__class__.__name__,err.args[0]) for err in list(errors(f, 1).values())])
    a = dict(s)
    if not os.environ.get('COVERAGE'): #XXX: travis-ci
        proxy = 0 if type(f.f_locals) is dict else 1
        assert len(s) == len(a) + proxy # TypeError (and possibly PicklingError)
    n = 2
    assert len(a) is n if 'PicklingError' in a.keys() else n-1
Referenced by test_lambdify().
test_deleted()
dill.tests.test_detect.test_deleted ()
Definition at line 119 of file test_detect.py.
def test_deleted():
    global sin
    from dill import dumps, loads
    from math import sin, pi
    def sinc(x):
        return sin(x)/x
    settings['recurse'] = True
    _sinc = dumps(sinc)
    sin = globals().pop('sin')
    sin = 1
    del sin
    sinc_ = loads(_sinc) # no NameError... pickling preserves 'sin'
    res = sinc_(1)
    from math import sin
    assert sinc(1) == res
Referenced by test_lambdify().
test_getstate()
dill.tests.test_detect.test_getstate ()
Definition at line 109 of file test_detect.py.
def test_getstate():
    from dill import dumps, loads
    dumps(f)
    b = bar[0]
    dumps(lambda: f, recurse=False) # doesn't call __getstate__
    assert bar[0] == b
    dumps(lambda: f, recurse=True) # calls __getstate__
    assert bar[0] == b + 1
#97 serialize lambdas in test files
Referenced by test_lambdify().
test_globals()
dill.tests.test_detect.test_globals ()
Definition at line 63 of file test_detect.py.
def test_globals():
    def f():
        a
        def g():
            b
            def h():
                c
    assert globalvars(f) == dict(a=1, b=2, c=3)
    res = globalvars(foo, recurse=True)
    assert set(res) == set(['squared', 'a'])
    res = globalvars(foo, recurse=False)
    assert res == {}
    zap = foo(2)
    res = globalvars(zap, recurse=True)
    assert set(res) == set(['squared', 'a'])
    res = globalvars(zap, recurse=False)
    assert set(res) == set(['squared'])
    del zap
    res = globalvars(squared)
    assert set(res) == set(['a'])
    # FIXME: should find referenced __builtins__
    #res = globalvars(_class, recurse=True)
    #assert set(res) == set(['True'])
    #res = globalvars(_class, recurse=False)
    #assert res == {}
    #res = globalvars(_class.ok, recurse=True)
    #assert set(res) == set(['True'])
    #res = globalvars(_class.ok, recurse=False)
    #assert set(res) == set(['True'])
#98 dill ignores __getstate__ in interactive lambdas
Referenced by test_lambdify().
test_lambdify()
dill.tests.test_detect.test_lambdify ()
Definition at line 138 of file test_detect.py.
def test_lambdify():
    try:
        from sympy import symbols, lambdify
    except ImportError:
        return
    settings['recurse'] = True
    x = symbols("x")
    y = x**2
    f = lambdify([x], y)
    z = min
    d = globals()
    globalvars(f, recurse=True, builtin=True)
    assert z is min
    assert d is globals()
References test_bad_things(), test_deleted(), test_getstate(), test_globals(), test_lambdify(), and test_parent().
Referenced by test_lambdify().
test_parent()
dill.tests.test_detect.test_parent ()
Definition at line 37 of file test_detect.py.
def test_parent():
    x = [4,5,6,7]
    listiter = iter(x)
    obj = parent(listiter, list)
    assert obj is x
    if IS_PYPY: assert parent(obj, int) is None
    else: assert parent(obj, int) is x[-1] # python oddly? finds last int
    assert at(id(at)) is at
References dill.parent.
Referenced by test_lambdify().
Variable Documentation
a
dill.tests.test_detect.a
Definition at line 47 of file test_detect.py.
b
dill.tests.test_detect.b
Definition at line 47 of file test_detect.py.
bar
list dill.tests.test_detect.bar = [0]
Definition at line 96 of file test_detect.py.
c
dill.tests.test_detect.c
Definition at line 47 of file test_detect.py.
f
dill.tests.test_detect.f = Foo()
Definition at line 107 of file test_detect.py.