Read&Watch: pip._internal.commands.install Namespace Reference
pip._internal.commands.install Namespace Reference
Classes
class InstallCommand
Functions
List[str] get_lib_location_guesses (bool user=False, Optional[str] home=None, Optional[str] root=None, bool isolated=False, Optional[str] prefix=None)
bool site_packages_writable (Optional[str] root, bool isolated)
bool decide_user_install (Optional[bool] use_user_site, Optional[str] prefix_path=None, Optional[str] target_dir=None, Optional[str] root_path=None, bool isolated_mode=False)
str create_os_error_message (OSError error, bool show_traceback, bool using_user_site)
Variables
logger = getLogger(__name__)
Function Documentation
create_os_error_message()
str pip._internal.commands.install.create_os_error_message (OSError error, bool show_traceback, bool using_user_site)
Format an error message for an OSError
It may occur anytime during the execution of the install command.
Definition at line 729 of file install.py.
) -> str:
    """Format an error message for an OSError
    It may occur anytime during the execution of the install command.
    """
    parts = []
    # Mention the error if we are not going to show a traceback
    parts.append("Could not install packages due to an OSError")
    if not show_traceback:
        parts.append(": ")
        parts.append(str(error))
    else:
        parts.append(".")
    # Spilt the error indication from a helper message (if any)
    parts[-1] += "\n"
    # Suggest useful actions to the user:
    #  (1) using user site-packages or (2) verifying the permissions
    if error.errno == errno.EACCES:
        user_option_part = "Consider using the `--user` option"
        permissions_part = "Check the permissions"
        if not running_under_virtualenv() and not using_user_site:
            parts.extend(
                [
                    user_option_part,
                    " or ",
                    permissions_part.lower(),
                ]
            )
        else:
            parts.append(permissions_part)
        parts.append(".\n")
    # Suggest the user to enable Long Paths if path length is
    # more than 260
    if (
        WINDOWS
        and error.errno == errno.ENOENT
        and error.filename
        and len(error.filename) > 260
    ):
        parts.append(
            "HINT: This error might have occurred since "
            "this system does not have Windows Long Path "
            "support enabled. You can find information on "
            "how to enable this at "
            "https://pip.pypa.io/warnings/enable-long-paths\n"
        )
    return "".join(parts).strip() + "\n"
Referenced by pip._internal.commands.install.InstallCommand.run().
decide_user_install()
bool pip._internal.commands.install.decide_user_install (Optional[bool] use_user_site, Optional[str] prefix_path = None, Optional[str] target_dir = None, Optional[str] root_path = None, bool isolated_mode = False)
Determine whether to do a user install based on the input options.
If use_user_site is False, no additional checks are done.
If use_user_site is True, it is checked for compatibility with other
options.
If use_user_site is None, the default behaviour depends on the environment,
which is provided by the other arguments.
Definition at line 668 of file install.py.
) -> bool:
    """Determine whether to do a user install based on the input options.
    If use_user_site is False, no additional checks are done.
    If use_user_site is True, it is checked for compatibility with other
    options.
    If use_user_site is None, the default behaviour depends on the environment,
    which is provided by the other arguments.
    """
    # In some cases (config from tox), use_user_site can be set to an integer
    # rather than a bool, which 'use_user_site is False' wouldn't catch.
    if (use_user_site is not None) and (not use_user_site):
        logger.debug("Non-user install by explicit request")
        return False
    if use_user_site:
        if prefix_path:
            raise CommandError(
                "Can not combine '--user' and '--prefix' as they imply "
                "different installation locations"
            )
        if virtualenv_no_global():
            raise InstallationError(
                "Can not perform a '--user' install. User site-packages "
                "are not visible in this virtualenv."
            )
        logger.debug("User install by explicit request")
        return True
    # If we are here, user installs have not been explicitly requested/avoided
    assert use_user_site is None
    # user install incompatible with --prefix/--target
    if prefix_path or target_dir:
        logger.debug("Non-user install due to --prefix or --target option")
        return False
    # If user installs are not enabled, choose a non-user install
    if not site.ENABLE_USER_SITE:
        logger.debug("Non-user install because user site-packages disabled")
        return False
    # If we have permission for a non-user install, do that,
    # otherwise do a user install.
    if site_packages_writable(root=root_path, isolated=isolated_mode):
        logger.debug("Non-user install because site-packages writeable")
        return False
    logger.info(
        "Defaulting to user installation because normal site-packages "
        "is not writeable"
    )
    return True
References site_packages_writable().
Referenced by pip._internal.commands.install.InstallCommand.run().
get_lib_location_guesses()
List[str] pip._internal.commands.install.get_lib_location_guesses (bool user = False, Optional[str] home = None, Optional[str] root = None, bool isolated = False, Optional[str] prefix = None)
Definition at line 643 of file install.py.
) -> List[str]:
    scheme = get_scheme(
        "",
        user=user,
        home=home,
        root=root,
        isolated=isolated,
        prefix=prefix,
    )
    return [scheme.purelib, scheme.platlib]
Referenced by pip._internal.commands.install.InstallCommand.run(), and site_packages_writable().
site_packages_writable()
bool pip._internal.commands.install.site_packages_writable (Optional[str] root, bool isolated)
Definition at line 661 of file install.py.
def site_packages_writable(root: Optional[str], isolated: bool) -> bool:
    return all(
        test_writable_dir(d)
        for d in set(get_lib_location_guesses(root=root, isolated=isolated))
    )
References get_lib_location_guesses().
Referenced by decide_user_install().
Variable Documentation
logger
pip._internal.commands.install.logger = getLogger(__name__)
Definition at line 50 of file install.py.