Read&Watch: isort.api Namespace Reference
isort.api Namespace Reference
Classes
class ImportKey
Functions
str sort_code_string (str code, Optional[str] extension=None, Config config=DEFAULT_CONFIG, Optional[Path] file_path=None, bool disregard_skip=False, Union[bool, TextIO] show_diff=False, **Any config_kwargs)
bool check_code_string (str code, Union[bool, TextIO] show_diff=False, Optional[str] extension=None, Config config=DEFAULT_CONFIG, Optional[Path] file_path=None, bool disregard_skip=False, **Any config_kwargs)
bool sort_stream (TextIO input_stream, TextIO output_stream, Optional[str] extension=None, Config config=DEFAULT_CONFIG, Optional[Path] file_path=None, bool disregard_skip=False, Union[bool, TextIO] show_diff=False, bool raise_on_skip=True, **Any config_kwargs)
bool check_stream (TextIO input_stream, Union[bool, TextIO] show_diff=False, Optional[str] extension=None, Config config=DEFAULT_CONFIG, Optional[Path] file_path=None, bool disregard_skip=False, **Any config_kwargs)
bool check_file (Union[str, Path] filename, Union[bool, TextIO] show_diff=False, Config config=DEFAULT_CONFIG, Optional[Path] file_path=None, bool disregard_skip=True, Optional[str] extension=None, **Any config_kwargs)
Path _tmp_file (File source_file)
Iterator[TextIO] _in_memory_output_stream_context ()
Iterator[TextIO] _file_output_stream_context (Union[str, Path] filename, File source_file)
bool sort_file (Union[str, Path] filename, Optional[str] extension=None, Config config=DEFAULT_CONFIG, Optional[Path] file_path=None, bool disregard_skip=True, bool ask_to_apply=False, Union[bool, TextIO] show_diff=False, bool write_to_stdout=False, Optional[TextIO] output=None, **Any config_kwargs)
Iterator[identify.Import] find_imports_in_code (str code, Config config=DEFAULT_CONFIG, Optional[Path] file_path=None, Union[bool, ImportKey] unique=False, bool top_only=False, **Any config_kwargs)
Iterator[identify.Import] find_imports_in_stream (TextIO input_stream, Config config=DEFAULT_CONFIG, Optional[Path] file_path=None, Union[bool, ImportKey] unique=False, bool top_only=False, Optional[Set[str]] _seen=None, **Any config_kwargs)
Iterator[identify.Import] find_imports_in_file (Union[str, Path] filename, Config config=DEFAULT_CONFIG, Optional[Path] file_path=None, Union[bool, ImportKey] unique=False, bool top_only=False, **Any config_kwargs)
Iterator[identify.Import] find_imports_in_paths (Iterator[Union[str, Path]] paths, Config config=DEFAULT_CONFIG, Optional[Path] file_path=None, Union[bool, ImportKey] unique=False, bool top_only=False, **Any config_kwargs)
Config _config (Optional[Path] path=None, Config config=DEFAULT_CONFIG, **Any config_kwargs)
Function Documentation
_config()
Config isort.api._config (Optional[Path] path = None, Config config = DEFAULT_CONFIG, **Any config_kwargs) protected
Definition at line 632 of file api.py.
) -> Config:
    if path and (
        config is DEFAULT_CONFIG
        and "settings_path" not in config_kwargs
        and "settings_file" not in config_kwargs
    ):
        config_kwargs["settings_path"] = path
    if config_kwargs:
        if config is not DEFAULT_CONFIG:
            raise ValueError(
                "You can either specify custom configuration options using kwargs or "
                "passing in a Config object. Not Both!"
            )
        config = Config(**config_kwargs)
    return config
Referenced by check_code_string(), check_stream(), find_imports_in_paths(), find_imports_in_stream(), sort_code_string(), sort_file(), and sort_stream().
_file_output_stream_context()
Iterator[TextIO] isort.api._file_output_stream_context (Union[str, Path] filename, File source_file) protected
Definition at line 359 of file api.py.
def _file_output_stream_context(filename: Union[str, Path], source_file: File) -> Iterator[TextIO]:
    tmp_file = _tmp_file(source_file)
    with tmp_file.open("w+", encoding=source_file.encoding, newline="") as output_stream:
        shutil.copymode(filename, tmp_file)
        yield output_stream
# Ignore DeepSource cyclomatic complexity check for this function. It is one
# the main entrypoints so sort of expected to be complex.
# skipcq: PY-R1000
References _tmp_file().
Referenced by sort_file().
_in_memory_output_stream_context()
Iterator[TextIO] isort.api._in_memory_output_stream_context () protected
Definition at line 354 of file api.py.
def _in_memory_output_stream_context() -> Iterator[TextIO]:
    yield StringIO(newline=None)
@contextlib.contextmanager
Referenced by sort_file().
_tmp_file()
Path isort.api._tmp_file (File source_file) protected
Definition at line 349 of file api.py.
def _tmp_file(source_file: File) -> Path:
    return source_file.path.with_suffix(source_file.path.suffix + ".isorted")
@contextlib.contextmanager
Referenced by _file_output_stream_context(), and sort_file().
check_code_string()
bool isort.api.check_code_string (str code, Union[bool, TextIO] show_diff = False, Optional[str] extension = None, Config config = DEFAULT_CONFIG, Optional[Path] file_path = None, bool disregard_skip = False, **Any config_kwargs)
Checks the order, format, and categorization of imports within the provided code string.
Returns `True` if everything is correct, otherwise `False`.
- **code**: The string of code with imports that need to be sorted.
- **show_diff**: If `True` the changes that need to be done will be printed to stdout, if a
TextIO stream is provided results will be written to it, otherwise no diff will be computed.
- **extension**: The file extension that contains imports. Defaults to filename extension or py.
- **config**: The config object to use when sorting imports.
- **file_path**: The disk location where the code string was pulled from.
- **disregard_skip**: set to `True` if you want to ignore a skip set in config for this file.
- ****config_kwargs**: Any config modifications.
Definition at line 105 of file api.py.
) -> bool:
    """Checks the order, format, and categorization of imports within the provided code string.
    Returns `True` if everything is correct, otherwise `False`.
    - **code**: The string of code with imports that need to be sorted.
    - **show_diff**: If `True` the changes that need to be done will be printed to stdout, if a
    TextIO stream is provided results will be written to it, otherwise no diff will be computed.
    - **extension**: The file extension that contains imports. Defaults to filename extension or py.
    - **config**: The config object to use when sorting imports.
    - **file_path**: The disk location where the code string was pulled from.
    - **disregard_skip**: set to `True` if you want to ignore a skip set in config for this file.
    - ****config_kwargs**: Any config modifications.
    """
    config = _config(path=file_path, config=config, **config_kwargs)
    return check_stream(
        StringIO(code),
        show_diff=show_diff,
        extension=extension,
        config=config,
        file_path=file_path,
        disregard_skip=disregard_skip,
    )
References _config(), and check_stream().
check_file()
bool isort.api.check_file (Union[str, Path] filename, Union[bool, TextIO] show_diff = False, Config config = DEFAULT_CONFIG, Optional[Path] file_path = None, bool disregard_skip = True, Optional[str] extension = None, **Any config_kwargs)
Checks any imports within the provided file, returning `False` if any unsorted or
incorrectly imports are found or `True` if no problems are identified.
- **filename**: The name or Path of the file to check.
- **show_diff**: If `True` the changes that need to be done will be printed to stdout, if a
TextIO stream is provided results will be written to it, otherwise no diff will be computed.
- **config**: The config object to use when sorting imports.
- **file_path**: The disk location where the code string was pulled from.
- **disregard_skip**: set to `True` if you want to ignore a skip set in config for this file.
- **extension**: The file extension that contains imports. Defaults to filename extension or py.
- ****config_kwargs**: Any config modifications.
Definition at line 305 of file api.py.
) -> bool:
    """Checks any imports within the provided file, returning `False` if any unsorted or
    incorrectly imports are found or `True` if no problems are identified.
    - **filename**: The name or Path of the file to check.
    - **show_diff**: If `True` the changes that need to be done will be printed to stdout, if a
    TextIO stream is provided results will be written to it, otherwise no diff will be computed.
    - **config**: The config object to use when sorting imports.
    - **file_path**: The disk location where the code string was pulled from.
    - **disregard_skip**: set to `True` if you want to ignore a skip set in config for this file.
    - **extension**: The file extension that contains imports. Defaults to filename extension or py.
    - ****config_kwargs**: Any config modifications.
    """
    file_config: Config = config
    if "config_trie" in config_kwargs:
        config_trie = config_kwargs.pop("config_trie", None)
        if config_trie:
            config_info = config_trie.search(filename)
            if config.verbose:
                print(f"{config_info[0]} used for file {filename}")
            file_config = Config(**config_info[1])
    with io.File.read(filename) as source_file:
        return check_stream(
            source_file.stream,
            show_diff=show_diff,
            extension=extension,
            config=file_config,
            file_path=file_path or source_file.path,
            disregard_skip=disregard_skip,
            **config_kwargs,
        )
References check_stream().
check_stream()
bool isort.api.check_stream (TextIO input_stream, Union[bool, TextIO] show_diff = False, Optional[str] extension = None, Config config = DEFAULT_CONFIG, Optional[Path] file_path = None, bool disregard_skip = False, **Any config_kwargs)
Checks any imports within the provided code stream, returning `False` if any unsorted or
incorrectly imports are found or `True` if no problems are identified.
- **input_stream**: The stream of code with imports that need to be sorted.
- **show_diff**: If `True` the changes that need to be done will be printed to stdout, if a
TextIO stream is provided results will be written to it, otherwise no diff will be computed.
- **extension**: The file extension that contains imports. Defaults to filename extension or py.
- **config**: The config object to use when sorting imports.
- **file_path**: The disk location where the code string was pulled from.
- **disregard_skip**: set to `True` if you want to ignore a skip set in config for this file.
- ****config_kwargs**: Any config modifications.
Definition at line 238 of file api.py.
) -> bool:
    """Checks any imports within the provided code stream, returning `False` if any unsorted or
    incorrectly imports are found or `True` if no problems are identified.
    - **input_stream**: The stream of code with imports that need to be sorted.
    - **show_diff**: If `True` the changes that need to be done will be printed to stdout, if a
    TextIO stream is provided results will be written to it, otherwise no diff will be computed.
    - **extension**: The file extension that contains imports. Defaults to filename extension or py.
    - **config**: The config object to use when sorting imports.
    - **file_path**: The disk location where the code string was pulled from.
    - **disregard_skip**: set to `True` if you want to ignore a skip set in config for this file.
    - ****config_kwargs**: Any config modifications.
    """
    config = _config(path=file_path, config=config, **config_kwargs)
    if show_diff:
        input_stream = StringIO(input_stream.read())
    changed: bool = sort_stream(
        input_stream=input_stream,
        output_stream=Empty,
        extension=extension,
        config=config,
        file_path=file_path,
        disregard_skip=disregard_skip,
    )
    printer = create_terminal_printer(
        color=config.color_output, error=config.format_error, success=config.format_success
    )
    if not changed:
        if config.verbose and not config.only_modified:
            printer.success(f"{file_path or ''} Everything Looks Good!")
        return True
    printer.error(f"{file_path or ''} Imports are incorrectly sorted and/or formatted.")
    if show_diff:
        output_stream = StringIO()
        input_stream.seek(0)
        file_contents = input_stream.read()
        sort_stream(
            input_stream=StringIO(file_contents),
            output_stream=output_stream,
            extension=extension,
            config=config,
            file_path=file_path,
            disregard_skip=disregard_skip,
        )
        output_stream.seek(0)
        show_unified_diff(
            file_input=file_contents,
            file_output=output_stream.read(),
            file_path=file_path,
            output=None if show_diff is True else show_diff,
            color_output=config.color_output,
        )
    return False
References _config(), and sort_stream().
Referenced by check_code_string(), and check_file().
find_imports_in_code()
Iterator[identify.Import] isort.api.find_imports_in_code (str code, Config config = DEFAULT_CONFIG, Optional[Path] file_path = None, Union[bool, ImportKey] unique = False, bool top_only = False, **Any config_kwargs)
Finds and returns all imports within the provided code string.
- **code**: The string of code with imports that need to be sorted.
- **config**: The config object to use when sorting imports.
- **file_path**: The disk location where the code string was pulled from.
- **unique**: If True, only the first instance of an import is returned.
- **top_only**: If True, only return imports that occur before the first function or class.
- ****config_kwargs**: Any config modifications.
Definition at line 504 of file api.py.
) -> Iterator[identify.Import]:
    """Finds and returns all imports within the provided code string.
    - **code**: The string of code with imports that need to be sorted.
    - **config**: The config object to use when sorting imports.
    - **file_path**: The disk location where the code string was pulled from.
    - **unique**: If True, only the first instance of an import is returned.
    - **top_only**: If True, only return imports that occur before the first function or class.
    - ****config_kwargs**: Any config modifications.
    """
    yield from find_imports_in_stream(
        input_stream=StringIO(code),
        config=config,
        file_path=file_path,
        unique=unique,
        top_only=top_only,
        **config_kwargs,
    )
References find_imports_in_stream().
find_imports_in_file()
Iterator[identify.Import] isort.api.find_imports_in_file (Union[str, Path] filename, Config config = DEFAULT_CONFIG, Optional[Path] file_path = None, Union[bool, ImportKey] unique = False, bool top_only = False, **Any config_kwargs)
Finds and returns all imports within the provided source file.
- **filename**: The name or Path of the file to look for imports in.
- **extension**: The file extension that contains imports. Defaults to filename extension or py.
- **config**: The config object to use when sorting imports.
- **file_path**: The disk location where the code string was pulled from.
- **unique**: If True, only the first instance of an import is returned.
- **top_only**: If True, only return imports that occur before the first function or class.
- ****config_kwargs**: Any config modifications.
Definition at line 573 of file api.py.
) -> Iterator[identify.Import]:
    """Finds and returns all imports within the provided source file.
    - **filename**: The name or Path of the file to look for imports in.
    - **extension**: The file extension that contains imports. Defaults to filename extension or py.
    - **config**: The config object to use when sorting imports.
    - **file_path**: The disk location where the code string was pulled from.
    - **unique**: If True, only the first instance of an import is returned.
    - **top_only**: If True, only return imports that occur before the first function or class.
    - ****config_kwargs**: Any config modifications.
    """
    with io.File.read(filename) as source_file:
        yield from find_imports_in_stream(
            input_stream=source_file.stream,
            config=config,
            file_path=file_path or source_file.path,
            unique=unique,
            top_only=top_only,
            **config_kwargs,
        )
References find_imports_in_stream().
Referenced by find_imports_in_paths().
find_imports_in_paths()
Iterator[identify.Import] isort.api.find_imports_in_paths (Iterator[Union[str, Path]] paths, Config config = DEFAULT_CONFIG, Optional[Path] file_path = None, Union[bool, ImportKey] unique = False, bool top_only = False, **Any config_kwargs)
Finds and returns all imports within the provided source paths.
- **paths**: A collection of paths to recursively look for imports within.
- **extension**: The file extension that contains imports. Defaults to filename extension or py.
- **config**: The config object to use when sorting imports.
- **file_path**: The disk location where the code string was pulled from.
- **unique**: If True, only the first instance of an import is returned.
- **top_only**: If True, only return imports that occur before the first function or class.
- ****config_kwargs**: Any config modifications.
Definition at line 602 of file api.py.
) -> Iterator[identify.Import]:
    """Finds and returns all imports within the provided source paths.
    - **paths**: A collection of paths to recursively look for imports within.
    - **extension**: The file extension that contains imports. Defaults to filename extension or py.
    - **config**: The config object to use when sorting imports.
    - **file_path**: The disk location where the code string was pulled from.
    - **unique**: If True, only the first instance of an import is returned.
    - **top_only**: If True, only return imports that occur before the first function or class.
    - ****config_kwargs**: Any config modifications.
    """
    config = _config(config=config, **config_kwargs)
    seen: Optional[Set[str]] = set() if unique else None
    yield from chain(
        *(
            find_imports_in_file(
                file_name, unique=unique, config=config, top_only=top_only, _seen=seen
            )
            for file_name in files.find(map(str, paths), config, [], [])
        )
    )
References _config(), and find_imports_in_file().
find_imports_in_stream()
Iterator[identify.Import] isort.api.find_imports_in_stream (TextIO input_stream, Config config = DEFAULT_CONFIG, Optional[Path] file_path = None, Union[bool, ImportKey] unique = False, bool top_only = False, Optional[Set[str]] _seen = None, **Any config_kwargs)
Finds and returns all imports within the provided code stream.
- **input_stream**: The stream of code with imports that need to be sorted.
- **config**: The config object to use when sorting imports.
- **file_path**: The disk location where the code string was pulled from.
- **unique**: If True, only the first instance of an import is returned.
- **top_only**: If True, only return imports that occur before the first function or class.
- **_seen**: An optional set of imports already seen. Generally meant only for internal use.
- ****config_kwargs**: Any config modifications.
Definition at line 531 of file api.py.
) -> Iterator[identify.Import]:
    """Finds and returns all imports within the provided code stream.
    - **input_stream**: The stream of code with imports that need to be sorted.
    - **config**: The config object to use when sorting imports.
    - **file_path**: The disk location where the code string was pulled from.
    - **unique**: If True, only the first instance of an import is returned.
    - **top_only**: If True, only return imports that occur before the first function or class.
    - **_seen**: An optional set of imports already seen. Generally meant only for internal use.
    - ****config_kwargs**: Any config modifications.
    """
    config = _config(config=config, **config_kwargs)
    identified_imports = identify.imports(
        input_stream, config=config, file_path=file_path, top_only=top_only
    )
    if not unique:
        yield from identified_imports
    seen: Set[str] = set() if _seen is None else _seen
    for identified_import in identified_imports:
        if unique in (True, ImportKey.ALIAS):
            key = identified_import.statement()
        elif unique == ImportKey.ATTRIBUTE:
            key = f"{identified_import.module}.{identified_import.attribute}"
        elif unique == ImportKey.MODULE:
            key = identified_import.module
        elif unique == ImportKey.PACKAGE:  # pragma: no branch # type checking ensures this
            key = identified_import.module.split(".")[0]
        if key and key not in seen:
            seen.add(key)
            yield identified_import
References _config().
Referenced by find_imports_in_code(), and find_imports_in_file().
sort_code_string()
str isort.api.sort_code_string (str code, Optional[str] extension = None, Config config = DEFAULT_CONFIG, Optional[Path] file_path = None, bool disregard_skip = False, Union[bool, TextIO] show_diff = False, **Any config_kwargs)
Sorts any imports within the provided code string, returning a new string with them sorted.
- **code**: The string of code with imports that need to be sorted.
- **extension**: The file extension that contains imports. Defaults to filename extension or py.
- **config**: The config object to use when sorting imports.
- **file_path**: The disk location where the code string was pulled from.
- **disregard_skip**: set to `True` if you want to ignore a skip set in config for this file.
- **show_diff**: If `True` the changes that need to be done will be printed to stdout, if a
TextIO stream is provided results will be written to it, otherwise no diff will be computed.
- ****config_kwargs**: Any config modifications.
Definition at line 69 of file api.py.
) -> str:
    """Sorts any imports within the provided code string, returning a new string with them sorted.
    - **code**: The string of code with imports that need to be sorted.
    - **extension**: The file extension that contains imports. Defaults to filename extension or py.
    - **config**: The config object to use when sorting imports.
    - **file_path**: The disk location where the code string was pulled from.
    - **disregard_skip**: set to `True` if you want to ignore a skip set in config for this file.
    - **show_diff**: If `True` the changes that need to be done will be printed to stdout, if a
    TextIO stream is provided results will be written to it, otherwise no diff will be computed.
    - ****config_kwargs**: Any config modifications.
    """
    input_stream = StringIO(code)
    output_stream = StringIO()
    config = _config(path=file_path, config=config, **config_kwargs)
    sort_stream(
        input_stream,
        output_stream,
        extension=extension,
        config=config,
        file_path=file_path,
        disregard_skip=disregard_skip,
        show_diff=show_diff,
    )
    output_stream.seek(0)
    return output_stream.read()
References _config(), and sort_stream().
sort_file()
bool isort.api.sort_file (Union[str, Path] filename, Optional[str] extension = None, Config config = DEFAULT_CONFIG, Optional[Path] file_path = None, bool disregard_skip = True, bool ask_to_apply = False, Union[bool, TextIO] show_diff = False, bool write_to_stdout = False, Optional[TextIO] output = None, **Any config_kwargs)
Sorts and formats any groups of imports imports within the provided file or Path.
 Returns `True` if the file has been changed, otherwise `False`.
- **filename**: The name or Path of the file to format.
- **extension**: The file extension that contains imports. Defaults to filename extension or py.
- **config**: The config object to use when sorting imports.
- **file_path**: The disk location where the code string was pulled from.
- **disregard_skip**: set to `True` if you want to ignore a skip set in config for this file.
- **ask_to_apply**: If `True`, prompt before applying any changes.
- **show_diff**: If `True` the changes that need to be done will be printed to stdout, if a
TextIO stream is provided results will be written to it, otherwise no diff will be computed.
- **write_to_stdout**: If `True`, write to stdout instead of the input file.
- **output**: If a TextIO is provided, results will be written there rather than replacing
the original file content.
- ****config_kwargs**: Any config modifications.
Definition at line 369 of file api.py.
) -> bool:
    """Sorts and formats any groups of imports imports within the provided file or Path.
     Returns `True` if the file has been changed, otherwise `False`.
    - **filename**: The name or Path of the file to format.
    - **extension**: The file extension that contains imports. Defaults to filename extension or py.
    - **config**: The config object to use when sorting imports.
    - **file_path**: The disk location where the code string was pulled from.
    - **disregard_skip**: set to `True` if you want to ignore a skip set in config for this file.
    - **ask_to_apply**: If `True`, prompt before applying any changes.
    - **show_diff**: If `True` the changes that need to be done will be printed to stdout, if a
    TextIO stream is provided results will be written to it, otherwise no diff will be computed.
    - **write_to_stdout**: If `True`, write to stdout instead of the input file.
    - **output**: If a TextIO is provided, results will be written there rather than replacing
    the original file content.
    - ****config_kwargs**: Any config modifications.
    """
    file_config: Config = config
    if "config_trie" in config_kwargs:
        config_trie = config_kwargs.pop("config_trie", None)
        if config_trie:
            config_info = config_trie.search(filename)
            if config.verbose:
                print(f"{config_info[0]} used for file {filename}")
            file_config = Config(**config_info[1])
    with io.File.read(filename) as source_file:
        actual_file_path = file_path or source_file.path
        config = _config(path=actual_file_path, config=file_config, **config_kwargs)
        changed: bool = False
        try:
            if write_to_stdout:
                changed = sort_stream(
                    input_stream=source_file.stream,
                    output_stream=sys.stdout,
                    config=config,
                    file_path=actual_file_path,
                    disregard_skip=disregard_skip,
                    extension=extension,
                )
            else:
                if output is None:
                    try:
                        if config.overwrite_in_place:
                            output_stream_context = _in_memory_output_stream_context()
                        else:
                            output_stream_context = _file_output_stream_context(
                                filename, source_file
                            )
                        with output_stream_context as output_stream:
                            changed = sort_stream(
                                input_stream=source_file.stream,
                                output_stream=output_stream,
                                config=config,
                                file_path=actual_file_path,
                                disregard_skip=disregard_skip,
                                extension=extension,
                            )
                            output_stream.seek(0)
                            if changed:
                                if show_diff or ask_to_apply:
                                    source_file.stream.seek(0)
                                    show_unified_diff(
                                        file_input=source_file.stream.read(),
                                        file_output=output_stream.read(),
                                        file_path=actual_file_path,
                                        output=(
                                            None if show_diff is True else cast(TextIO, show_diff)
                                        ),
                                        color_output=config.color_output,
                                    )
                                    if show_diff or (
                                        ask_to_apply
                                        and not ask_whether_to_apply_changes_to_file(
                                            str(source_file.path)
                                        )
                                    ):
                                        return False
                                source_file.stream.close()
                                if config.overwrite_in_place:
                                    output_stream.seek(0)
                                    with source_file.path.open("w") as fs:
                                        shutil.copyfileobj(output_stream, fs)
                        if changed:
                            if not config.overwrite_in_place:
                                tmp_file = _tmp_file(source_file)
                                tmp_file.replace(source_file.path)
                            if not config.quiet:
                                print(f"Fixing {source_file.path}")
                    finally:
                        if not config.overwrite_in_place:  # pragma: no branch
                            tmp_file = _tmp_file(source_file)
                            tmp_file.unlink(missing_ok=True)
                else:
                    changed = sort_stream(
                        input_stream=source_file.stream,
                        output_stream=output,
                        config=config,
                        file_path=actual_file_path,
                        disregard_skip=disregard_skip,
                        extension=extension,
                    )
                    if changed and show_diff:
                        source_file.stream.seek(0)
                        output.seek(0)
                        show_unified_diff(
                            file_input=source_file.stream.read(),
                            file_output=output.read(),
                            file_path=actual_file_path,
                            output=None if show_diff is True else show_diff,
                            color_output=config.color_output,
                        )
                    source_file.stream.close()
        except ExistingSyntaxErrors:
            warn(f"{actual_file_path} unable to sort due to existing syntax errors")
        except IntroducedSyntaxErrors:  # pragma: no cover
            warn(f"{actual_file_path} unable to sort as isort introduces new syntax errors")
        return changed
References _config(), _file_output_stream_context(), _in_memory_output_stream_context(), _tmp_file(), and sort_stream().
sort_stream()
bool isort.api.sort_stream (TextIO input_stream, TextIO output_stream, Optional[str] extension = None, Config config = DEFAULT_CONFIG, Optional[Path] file_path = None, bool disregard_skip = False, Union[bool, TextIO] show_diff = False, bool raise_on_skip = True, **Any config_kwargs)
Sorts any imports within the provided code stream, outputs to the provided output stream.
 Returns `True` if anything is modified from the original input stream, otherwise `False`.
- **input_stream**: The stream of code with imports that need to be sorted.
- **output_stream**: The stream where sorted imports should be written to.
- **extension**: The file extension that contains imports. Defaults to filename extension or py.
- **config**: The config object to use when sorting imports.
- **file_path**: The disk location where the code string was pulled from.
- **disregard_skip**: set to `True` if you want to ignore a skip set in config for this file.
- **show_diff**: If `True` the changes that need to be done will be printed to stdout, if a
TextIO stream is provided results will be written to it, otherwise no diff will be computed.
- ****config_kwargs**: Any config modifications.
Definition at line 137 of file api.py.
) -> bool:
    """Sorts any imports within the provided code stream, outputs to the provided output stream.
     Returns `True` if anything is modified from the original input stream, otherwise `False`.
    - **input_stream**: The stream of code with imports that need to be sorted.
    - **output_stream**: The stream where sorted imports should be written to.
    - **extension**: The file extension that contains imports. Defaults to filename extension or py.
    - **config**: The config object to use when sorting imports.
    - **file_path**: The disk location where the code string was pulled from.
    - **disregard_skip**: set to `True` if you want to ignore a skip set in config for this file.
    - **show_diff**: If `True` the changes that need to be done will be printed to stdout, if a
    TextIO stream is provided results will be written to it, otherwise no diff will be computed.
    - ****config_kwargs**: Any config modifications.
    """
    extension = extension or (file_path and file_path.suffix.lstrip(".")) or "py"
    if show_diff:
        _output_stream = StringIO()
        _input_stream = StringIO(input_stream.read())
        changed = sort_stream(
            input_stream=_input_stream,
            output_stream=_output_stream,
            extension=extension,
            config=config,
            file_path=file_path,
            disregard_skip=disregard_skip,
            raise_on_skip=raise_on_skip,
            **config_kwargs,
        )
        _output_stream.seek(0)
        _input_stream.seek(0)
        show_unified_diff(
            file_input=_input_stream.read(),
            file_output=_output_stream.read(),
            file_path=file_path,
            output=output_stream if show_diff is True else show_diff,
            color_output=config.color_output,
        )
        return changed
    config = _config(path=file_path, config=config, **config_kwargs)
    content_source = str(file_path or "Passed in content")
    if not disregard_skip and file_path and config.is_skipped(file_path):
        raise FileSkipSetting(content_source)
    _internal_output = output_stream
    if config.atomic:
        try:
            file_content = input_stream.read()
            compile(file_content, content_source, "exec", flags=0, dont_inherit=True)
        except SyntaxError:
            if extension not in CYTHON_EXTENSIONS:
                raise ExistingSyntaxErrors(content_source)
            if config.verbose:
                warn(
                    f"{content_source} Python AST errors found but ignored due to Cython extension"
                )
        input_stream = StringIO(file_content)
        if not output_stream.readable():
            _internal_output = StringIO()
    try:
        changed = core.process(
            input_stream,
            _internal_output,
            extension=extension,
            config=config,
            raise_on_skip=raise_on_skip,
        )
    except FileSkipComment:
        raise FileSkipComment(content_source)
    if config.atomic:
        _internal_output.seek(0)
        try:
            compile(_internal_output.read(), content_source, "exec", flags=0, dont_inherit=True)
            _internal_output.seek(0)
        except SyntaxError:  # pragma: no cover
            if extension not in CYTHON_EXTENSIONS:
                raise IntroducedSyntaxErrors(content_source)
            if config.verbose:
                warn(
                    f"{content_source} Python AST errors found but ignored due to Cython extension"
                )
        if _internal_output != output_stream:
            output_stream.write(_internal_output.read())
    return changed
References _config(), and sort_stream().
Referenced by check_stream(), sort_code_string(), sort_file(), and sort_stream().