Read&Watch: pylint.graph Namespace Reference
pylint.graph Namespace Reference
Classes
class DotBackend
Functions
tuple[str, str, str] target_info_from_filename (str filename)
str normalize_node_id (str nid)
Sequence[list[str]] get_cycles (dict[str, set[str]] graph_dict, list[str]|None vertices=None)
None _get_cycles (dict[str, set[str]] graph_dict, list[str] path, set[str] visited, list[list[str]] result, str vertice)
Detailed Description
Graph manipulation utilities.
(dot generation adapted from pypy/translator/tool/make_dot.py)
Function Documentation
_get_cycles()
None pylint.graph._get_cycles (dict[str, set[str]] graph_dict, list[str] path, set[str] visited, list[list[str]] result, str vertice) protected
Recursive function doing the real work for get_cycles.
Definition at line 181 of file graph.py.
) -> None:
    """Recursive function doing the real work for get_cycles."""
    if vertice in path:
        cycle = [vertice]
        for node in path[::-1]:
            if node == vertice:
                break
            cycle.insert(0, node)
        # make a canonical representation
        start_from = min(cycle)
        index = cycle.index(start_from)
        cycle = cycle[index:] + cycle[0:index]
        # append it to result if not already in
        if cycle not in result:
            result.append(cycle)
        return
    path.append(vertice)
    try:
        for node in graph_dict[vertice]:
            # don't check already visited nodes again
            if node not in visited:
                _get_cycles(graph_dict, path, visited, result, node)
                visited.add(node)
    except KeyError:
        pass
    path.pop()
References _get_cycles().
Referenced by _get_cycles(), and get_cycles().
get_cycles()
Sequence[list[str]] pylint.graph.get_cycles (dict[str, set[str]] graph_dict, list[str] | None vertices = None)
Return a list of detected cycles based on an ordered graph (i.e. keys are
vertices and values are lists of destination vertices representing edges).
Definition at line 165 of file graph.py.
) -> Sequence[list[str]]:
    """Return a list of detected cycles based on an ordered graph (i.e. keys are
    vertices and values are lists of destination vertices representing edges).
    """
    if not graph_dict:
        return ()
    result: list[list[str]] = []
    if vertices is None:
        vertices = list(graph_dict.keys())
    for vertice in vertices:
        _get_cycles(graph_dict, [], set(), result, vertice)
    return result
References _get_cycles().
normalize_node_id()
str pylint.graph.normalize_node_id (str nid)
Returns a suitable DOT node id for `nid`.
Definition at line 160 of file graph.py.
def normalize_node_id(nid: str) -> str:
    """Returns a suitable DOT node id for `nid`."""
    return f'"{nid}"'
Referenced by pylint.graph.DotBackend.emit_edge().
target_info_from_filename()
tuple[str, str, str] pylint.graph.target_info_from_filename (str filename)
Transforms /some/path/foo.png into ('/some/path', 'foo.png', 'png').
Definition at line 21 of file graph.py.
def target_info_from_filename(filename: str) -> tuple[str, str, str]:
    """Transforms /some/path/foo.png into ('/some/path', 'foo.png', 'png')."""
    basename = os.path.basename(filename)
    storedir = os.path.dirname(os.path.abspath(filename))
    target = os.path.splitext(filename)[-1][1:]
    return storedir, basename, target
Referenced by pylint.graph.DotBackend.generate().