Read&Watch: pylint.checkers.imports Namespace Reference
pylint.checkers.imports Namespace Reference
Classes
class ImportsChecker
Functions
tuple[nodes.Import|nodes.ImportFrom|None, str|None] _get_first_import (ImportNode node, nodes.LocalsDictNodeNG context, str name, str|None base, int|None level, str|None alias)
bool _ignore_import_failure (ImportNode node, str modname, Sequence[str] ignored_modules)
_ImportTree _make_tree_defs (ItemsView[str, set[str]] mod_files_list)
str _repr_tree_defs (_ImportTree data, str|None indent_str=None)
str _dependencies_graph (str filename, dict[str, set[str]] dep_info)
None _make_graph (str filename, dict[str, set[str]] dep_info, Section sect, str gtype)
None register (PyLinter linter)
Variables
_ImportTree = dict[str, Union[list[dict[str, Any]], list[str]]]
dict DEPRECATED_MODULES
dict MSGS
tuple DEFAULT_STANDARD_LIBRARY = ()
tuple DEFAULT_KNOWN_THIRD_PARTY = ("enchant",)
tuple DEFAULT_PREFERRED_MODULES = ()
Detailed Description
Imports checkers for Python code.
Function Documentation
_dependencies_graph()
str pylint.checkers.imports._dependencies_graph (str filename, dict[str, set[str]] dep_info) protected
Write dependencies as a dot (graphviz) file.
Definition at line 197 of file imports.py.
def _dependencies_graph(filename: str, dep_info: dict[str, set[str]]) -> str:
    """Write dependencies as a dot (graphviz) file."""
    done = {}
    printer = DotBackend(os.path.splitext(os.path.basename(filename))[0], rankdir="LR")
    printer.emit('URL="." node[shape="box"]')
    for modname, dependencies in sorted(dep_info.items()):
        sorted_dependencies = sorted(dependencies)
        done[modname] = 1
        printer.emit_node(modname)
        for depmodname in sorted_dependencies:
            if depmodname not in done:
                done[depmodname] = 1
                printer.emit_node(depmodname)
    for depmodname, dependencies in sorted(dep_info.items()):
        for modname in sorted(dependencies):
            printer.emit_edge(modname, depmodname)
    return printer.generate(filename)
Referenced by _make_graph().
_get_first_import()
tuple[nodes.Import | nodes.ImportFrom | None, str | None] pylint.checkers.imports._get_first_import (ImportNode node, nodes.LocalsDictNodeNG context, str name, str | None base, int | None level, str | None alias) protected
Return the node where [base.]<name> is imported or None if not found.
Definition at line 86 of file imports.py.
) -> tuple[nodes.Import | nodes.ImportFrom | None, str | None]:
    """Return the node where [base.]<name> is imported or None if not found."""
    fullname = f"{base}.{name}" if base else name
    first = None
    found = False
    msg = "reimported"
    for first in context.body:
        if first is node:
            continue
        if first.scope() is node.scope() and first.fromlineno > node.fromlineno:
            continue
        if isinstance(first, nodes.Import):
            if any(fullname == iname[0] for iname in first.names):
                found = True
                break
            for imported_name, imported_alias in first.names:
                if not imported_alias and imported_name == alias:
                    found = True
                    msg = "shadowed-import"
                    break
            if found:
                break
        elif isinstance(first, nodes.ImportFrom):
            if level == first.level:
                for imported_name, imported_alias in first.names:
                    if fullname == f"{first.modname}.{imported_name}":
                        found = True
                        break
                    if (
                        name != "*"
                        and name == imported_name
                        and not (alias or imported_alias)
                    ):
                        found = True
                        break
                    if not imported_alias and imported_name == alias:
                        found = True
                        msg = "shadowed-import"
                        break
                if found:
                    break
    if found and not astroid.are_exclusive(first, node):
        return first, msg
    return None, None
Referenced by pylint.checkers.imports.ImportsChecker._check_reimport().
_ignore_import_failure()
bool pylint.checkers.imports._ignore_import_failure (ImportNode node, str modname, Sequence[str] ignored_modules) protected
Definition at line 141 of file imports.py.
) -> bool:
    if is_module_ignored(modname, ignored_modules):
        return True
    # Ignore import failure if part of guarded import block
    # I.e. `sys.version_info` or `typing.TYPE_CHECKING`
    if in_type_checking_block(node):
        return True
    if isinstance(node.parent, nodes.If) and is_sys_guard(node.parent):
        return True
    return node_ignores_exception(node, ImportError)
# utilities to represents import dependencies as tree and dot graph ###########
Referenced by pylint.checkers.imports.ImportsChecker._get_imported_module().
_make_graph()
None pylint.checkers.imports._make_graph (str filename, dict[str, set[str]] dep_info, Section sect, str gtype) protected
Generate a dependencies graph and add some information about it in the
report's section.
Definition at line 216 of file imports.py.
) -> None:
    """Generate a dependencies graph and add some information about it in the
    report's section.
    """
    outputfile = _dependencies_graph(filename, dep_info)
    sect.append(Paragraph((f"{gtype}imports graph has been written to {outputfile}",)))
# the import checker itself ###################################################
References _dependencies_graph().
Referenced by pylint.checkers.imports.ImportsChecker._report_dependencies_graph().
_make_tree_defs()
_ImportTree pylint.checkers.imports._make_tree_defs (ItemsView[str, set[str]] mod_files_list) protected
Get a list of 2-uple (module, list_of_files_which_import_this_module),
it will return a dictionary to represent this as a tree.
Definition at line 162 of file imports.py.
def _make_tree_defs(mod_files_list: ItemsView[str, set[str]]) -> _ImportTree:
    """Get a list of 2-uple (module, list_of_files_which_import_this_module),
    it will return a dictionary to represent this as a tree.
    """
    tree_defs: _ImportTree = {}
    for mod, files in mod_files_list:
        node: list[_ImportTree | list[str]] = [tree_defs, []]
        for prefix in mod.split("."):
            assert isinstance(node[0], dict)
            node = node[0].setdefault(prefix, ({}, []))  # type: ignore[arg-type,assignment]
        assert isinstance(node[1], list)
        node[1].extend(files)
    return tree_defs
Referenced by pylint.checkers.imports.ImportsChecker._report_external_dependencies().
_repr_tree_defs()
str pylint.checkers.imports._repr_tree_defs (_ImportTree data, str | None indent_str = None) protected
Return a string which represents imports as a tree.
Definition at line 177 of file imports.py.
def _repr_tree_defs(data: _ImportTree, indent_str: str | None = None) -> str:
    """Return a string which represents imports as a tree."""
    lines = []
    nodes_items = data.items()
    for i, (mod, (sub, files)) in enumerate(sorted(nodes_items, key=lambda x: x[0])):
        files_list = "" if not files else f"({','.join(sorted(files))})"
        if indent_str is None:
            lines.append(f"{mod} {files_list}")
            sub_indent_str = "  "
        else:
            lines.append(rf"{indent_str}\-{mod} {files_list}")
            if i == len(nodes_items) - 1:
                sub_indent_str = f"{indent_str}  "
            else:
                sub_indent_str = f"{indent_str}| "
        if sub and isinstance(sub, dict):
            lines.append(_repr_tree_defs(sub, sub_indent_str))
    return "\n".join(lines)
References _repr_tree_defs().
Referenced by pylint.checkers.imports.ImportsChecker._report_external_dependencies(), and _repr_tree_defs().
register()
None pylint.checkers.imports.register (PyLinter linter)
Definition at line 1262 of file imports.py.
def register(linter: PyLinter) -> None:
    linter.register_checker(ImportsChecker(linter))
Variable Documentation
_ImportTree
pylint.checkers.imports._ImportTree = dict[str, Union[list[dict[str, Any]], list[str]]] protected
Definition at line 46 of file imports.py.
DEFAULT_KNOWN_THIRD_PARTY
tuple pylint.checkers.imports.DEFAULT_KNOWN_THIRD_PARTY = ("enchant",)
Definition at line 322 of file imports.py.
DEFAULT_PREFERRED_MODULES
tuple pylint.checkers.imports.DEFAULT_PREFERRED_MODULES = ()
Definition at line 323 of file imports.py.
DEFAULT_STANDARD_LIBRARY
tuple pylint.checkers.imports.DEFAULT_STANDARD_LIBRARY = ()
Definition at line 321 of file imports.py.
DEPRECATED_MODULES
dict pylint.checkers.imports.DEPRECATED_MODULES
Definition at line 48 of file imports.py.
MSGS
dict pylint.checkers.imports.MSGS
Definition at line 228 of file imports.py.