Read&Watch: pip._vendor.packaging._parser Namespace Reference
pip._vendor.packaging._parser Namespace Reference
Classes
class Node
class Op
class ParsedRequirement
class Value
class Variable
Functions
ParsedRequirement parse_requirement (str source)
ParsedRequirement _parse_requirement (Tokenizer tokenizer)
tuple[str, str, MarkerList|None] _parse_requirement_details (Tokenizer tokenizer)
MarkerList _parse_requirement_marker (Tokenizer tokenizer, *, int span_start, str after)
list[str] _parse_extras (Tokenizer tokenizer)
list[str] _parse_extras_list (Tokenizer tokenizer)
str _parse_specifier (Tokenizer tokenizer)
str _parse_version_many (Tokenizer tokenizer)
MarkerList parse_marker (str source)
MarkerList _parse_full_marker (Tokenizer tokenizer)
MarkerList _parse_marker (Tokenizer tokenizer)
MarkerAtom _parse_marker_atom (Tokenizer tokenizer)
MarkerItem _parse_marker_item (Tokenizer tokenizer)
MarkerVar _parse_marker_var (Tokenizer tokenizer)
Variable process_env_var (str env_var)
Value process_python_str (str python_str)
Op _parse_marker_op (Tokenizer tokenizer)
Variables
MarkerVar = Union[Variable, Value]
MarkerItem = Tuple[MarkerVar, Op, MarkerVar]
MarkerAtom = Union[MarkerItem, Sequence["MarkerAtom"]]
MarkerList = Sequence[Union["MarkerList", MarkerAtom, str]]
Detailed Description
Handwritten parser of dependency specifiers.
The docstring for each __parse_* function contains EBNF-inspired grammar representing
the implementation.
Function Documentation
_parse_extras()
list[str] pip._vendor.packaging._parser._parse_extras (Tokenizer tokenizer) protected
extras = (LEFT_BRACKET wsp* extras_list? wsp* RIGHT_BRACKET)?
Definition at line 157 of file _parser.py.
def _parse_extras(tokenizer: Tokenizer) -> list[str]:
    """
    extras = (LEFT_BRACKET wsp* extras_list? wsp* RIGHT_BRACKET)?
    """
    if not tokenizer.check("LEFT_BRACKET", peek=True):
        return []
    with tokenizer.enclosing_tokens(
        "LEFT_BRACKET",
        "RIGHT_BRACKET",
        around="extras",
    ):
        tokenizer.consume("WS")
        extras = _parse_extras_list(tokenizer)
        tokenizer.consume("WS")
    return extras
References _parse_extras_list().
Referenced by _parse_requirement().
_parse_extras_list()
list[str] pip._vendor.packaging._parser._parse_extras_list (Tokenizer tokenizer) protected
extras_list = identifier (wsp* ',' wsp* identifier)*
Definition at line 176 of file _parser.py.
def _parse_extras_list(tokenizer: Tokenizer) -> list[str]:
    """
    extras_list = identifier (wsp* ',' wsp* identifier)*
    """
    extras: list[str] = []
    if not tokenizer.check("IDENTIFIER"):
        return extras
    extras.append(tokenizer.read().text)
    while True:
        tokenizer.consume("WS")
        if tokenizer.check("IDENTIFIER", peek=True):
            tokenizer.raise_syntax_error("Expected comma between extra names")
        elif not tokenizer.check("COMMA"):
            break
        tokenizer.read()
        tokenizer.consume("WS")
        extra_token = tokenizer.expect("IDENTIFIER", expected="extra name after comma")
        extras.append(extra_token.text)
    return extras
Referenced by _parse_extras().
_parse_full_marker()
MarkerList pip._vendor.packaging._parser._parse_full_marker (Tokenizer tokenizer) protected
Definition at line 256 of file _parser.py.
def _parse_full_marker(tokenizer: Tokenizer) -> MarkerList:
    retval = _parse_marker(tokenizer)
    tokenizer.expect("END", expected="end of marker expression")
    return retval
References _parse_marker().
Referenced by parse_marker().
_parse_marker()
MarkerList pip._vendor.packaging._parser._parse_marker (Tokenizer tokenizer) protected
marker = marker_atom (BOOLOP marker_atom)+
Definition at line 262 of file _parser.py.
def _parse_marker(tokenizer: Tokenizer) -> MarkerList:
    """
    marker = marker_atom (BOOLOP marker_atom)+
    """
    expression = [_parse_marker_atom(tokenizer)]
    while tokenizer.check("BOOLOP"):
        token = tokenizer.read()
        expr_right = _parse_marker_atom(tokenizer)
        expression.extend((token.text, expr_right))
    return expression
References _parse_marker_atom().
Referenced by _parse_full_marker(), _parse_marker_atom(), and _parse_requirement_marker().
_parse_marker_atom()
MarkerAtom pip._vendor.packaging._parser._parse_marker_atom (Tokenizer tokenizer) protected
marker_atom = WS? LEFT_PARENTHESIS WS? marker WS? RIGHT_PARENTHESIS WS?
            | WS? marker_item WS?
Definition at line 274 of file _parser.py.
def _parse_marker_atom(tokenizer: Tokenizer) -> MarkerAtom:
    """
    marker_atom = WS? LEFT_PARENTHESIS WS? marker WS? RIGHT_PARENTHESIS WS?
                | WS? marker_item WS?
    """
    tokenizer.consume("WS")
    if tokenizer.check("LEFT_PARENTHESIS", peek=True):
        with tokenizer.enclosing_tokens(
            "LEFT_PARENTHESIS",
            "RIGHT_PARENTHESIS",
            around="marker expression",
        ):
            tokenizer.consume("WS")
            marker: MarkerAtom = _parse_marker(tokenizer)
            tokenizer.consume("WS")
    else:
        marker = _parse_marker_item(tokenizer)
    tokenizer.consume("WS")
    return marker
References _parse_marker(), and _parse_marker_item().
Referenced by _parse_marker().
_parse_marker_item()
MarkerItem pip._vendor.packaging._parser._parse_marker_item (Tokenizer tokenizer) protected
marker_item = WS? marker_var WS? marker_op WS? marker_var WS?
Definition at line 296 of file _parser.py.
def _parse_marker_item(tokenizer: Tokenizer) -> MarkerItem:
    """
    marker_item = WS? marker_var WS? marker_op WS? marker_var WS?
    """
    tokenizer.consume("WS")
    marker_var_left = _parse_marker_var(tokenizer)
    tokenizer.consume("WS")
    marker_op = _parse_marker_op(tokenizer)
    tokenizer.consume("WS")
    marker_var_right = _parse_marker_var(tokenizer)
    tokenizer.consume("WS")
    return (marker_var_left, marker_op, marker_var_right)
References _parse_marker_op(), and _parse_marker_var().
Referenced by _parse_marker_atom().
_parse_marker_op()
Op pip._vendor.packaging._parser._parse_marker_op (Tokenizer tokenizer) protected
marker_op = IN | NOT IN | OP
Definition at line 336 of file _parser.py.
def _parse_marker_op(tokenizer: Tokenizer) -> Op:
    """
    marker_op = IN | NOT IN | OP
    """
    if tokenizer.check("IN"):
        tokenizer.read()
        return Op("in")
    elif tokenizer.check("NOT"):
        tokenizer.read()
        tokenizer.expect("WS", expected="whitespace after 'not'")
        tokenizer.expect("IN", expected="'in' after 'not'")
        return Op("not in")
    elif tokenizer.check("OP"):
        return Op(tokenizer.read().text)
    else:
        return tokenizer.raise_syntax_error(
            "Expected marker operator, one of "
            "<=, <, !=, ==, >=, >, ~=, ===, in, not in"
        )
Referenced by _parse_marker_item().
_parse_marker_var()
MarkerVar pip._vendor.packaging._parser._parse_marker_var (Tokenizer tokenizer) protected
marker_var = VARIABLE | QUOTED_STRING
Definition at line 310 of file _parser.py.
def _parse_marker_var(tokenizer: Tokenizer) -> MarkerVar:
    """
    marker_var = VARIABLE | QUOTED_STRING
    """
    if tokenizer.check("VARIABLE"):
        return process_env_var(tokenizer.read().text.replace(".", "_"))
    elif tokenizer.check("QUOTED_STRING"):
        return process_python_str(tokenizer.read().text)
    else:
        tokenizer.raise_syntax_error(
            message="Expected a marker variable or quoted string"
        )
References process_env_var(), and process_python_str().
Referenced by _parse_marker_item().
_parse_requirement()
ParsedRequirement pip._vendor.packaging._parser._parse_requirement (Tokenizer tokenizer) protected
requirement = WS? IDENTIFIER WS? extras WS? requirement_details
Definition at line 65 of file _parser.py.
def _parse_requirement(tokenizer: Tokenizer) -> ParsedRequirement:
    """
    requirement = WS? IDENTIFIER WS? extras WS? requirement_details
    """
    tokenizer.consume("WS")
    name_token = tokenizer.expect(
        "IDENTIFIER", expected="package name at the start of dependency specifier"
    )
    name = name_token.text
    tokenizer.consume("WS")
    extras = _parse_extras(tokenizer)
    tokenizer.consume("WS")
    url, specifier, marker = _parse_requirement_details(tokenizer)
    tokenizer.expect("END", expected="end of dependency specifier")
    return ParsedRequirement(name, url, extras, specifier, marker)
References _parse_extras(), and _parse_requirement_details().
Referenced by parse_requirement().
_parse_requirement_details()
tuple[str, str, MarkerList | None] pip._vendor.packaging._parser._parse_requirement_details (Tokenizer tokenizer) protected
requirement_details = AT URL (WS requirement_marker?)?
                    | specifier WS? (requirement_marker)?
Definition at line 86 of file _parser.py.
) -> tuple[str, str, MarkerList | None]:
    """
    requirement_details = AT URL (WS requirement_marker?)?
                        | specifier WS? (requirement_marker)?
    """
    specifier = ""
    url = ""
    marker = None
    if tokenizer.check("AT"):
        tokenizer.read()
        tokenizer.consume("WS")
        url_start = tokenizer.position
        url = tokenizer.expect("URL", expected="URL after @").text
        if tokenizer.check("END", peek=True):
            return (url, specifier, marker)
        tokenizer.expect("WS", expected="whitespace after URL")
        # The input might end after whitespace.
        if tokenizer.check("END", peek=True):
            return (url, specifier, marker)
        marker = _parse_requirement_marker(
            tokenizer, span_start=url_start, after="URL and whitespace"
        )
    else:
        specifier_start = tokenizer.position
        specifier = _parse_specifier(tokenizer)
        tokenizer.consume("WS")
        if tokenizer.check("END", peek=True):
            return (url, specifier, marker)
        marker = _parse_requirement_marker(
            tokenizer,
            span_start=specifier_start,
            after=(
                "version specifier"
                if specifier
                else "name and no valid version specifier"
            ),
        )
    return (url, specifier, marker)
References _parse_requirement_marker(), and _parse_specifier().
Referenced by _parse_requirement().
_parse_requirement_marker()
MarkerList pip._vendor.packaging._parser._parse_requirement_marker (Tokenizer tokenizer, * , int span_start, str after) protected
requirement_marker = SEMICOLON marker WS?
Definition at line 137 of file _parser.py.
) -> MarkerList:
    """
    requirement_marker = SEMICOLON marker WS?
    """
    if not tokenizer.check("SEMICOLON"):
        tokenizer.raise_syntax_error(
            f"Expected end or semicolon (after {after})",
            span_start=span_start,
        )
    tokenizer.read()
    marker = _parse_marker(tokenizer)
    tokenizer.consume("WS")
    return marker
References _parse_marker().
Referenced by _parse_requirement_details().
_parse_specifier()
str pip._vendor.packaging._parser._parse_specifier (Tokenizer tokenizer) protected
specifier = LEFT_PARENTHESIS WS? version_many WS? RIGHT_PARENTHESIS
          | WS? version_many WS?
Definition at line 203 of file _parser.py.
def _parse_specifier(tokenizer: Tokenizer) -> str:
    """
    specifier = LEFT_PARENTHESIS WS? version_many WS? RIGHT_PARENTHESIS
              | WS? version_many WS?
    """
    with tokenizer.enclosing_tokens(
        "LEFT_PARENTHESIS",
        "RIGHT_PARENTHESIS",
        around="version specifier",
    ):
        tokenizer.consume("WS")
        parsed_specifiers = _parse_version_many(tokenizer)
        tokenizer.consume("WS")
    return parsed_specifiers
References _parse_version_many().
Referenced by _parse_requirement_details().
_parse_version_many()
str pip._vendor.packaging._parser._parse_version_many (Tokenizer tokenizer) protected
version_many = (SPECIFIER (WS? COMMA WS? SPECIFIER)*)?
Definition at line 220 of file _parser.py.
def _parse_version_many(tokenizer: Tokenizer) -> str:
    """
    version_many = (SPECIFIER (WS? COMMA WS? SPECIFIER)*)?
    """
    parsed_specifiers = ""
    while tokenizer.check("SPECIFIER"):
        span_start = tokenizer.position
        parsed_specifiers += tokenizer.read().text
        if tokenizer.check("VERSION_PREFIX_TRAIL", peek=True):
            tokenizer.raise_syntax_error(
                ".* suffix can only be used with `==` or `!=` operators",
                span_start=span_start,
                span_end=tokenizer.position + 1,
            )
        if tokenizer.check("VERSION_LOCAL_LABEL_TRAIL", peek=True):
            tokenizer.raise_syntax_error(
                "Local version label can only be used with `==` or `!=` operators",
                span_start=span_start,
                span_end=tokenizer.position,
            )
        tokenizer.consume("WS")
        if not tokenizer.check("COMMA"):
            break
        parsed_specifiers += tokenizer.read().text
        tokenizer.consume("WS")
    return parsed_specifiers
# --------------------------------------------------------------------------------------
# Recursive descent parser for marker expression
# --------------------------------------------------------------------------------------
Referenced by _parse_specifier().
parse_marker()
MarkerList pip._vendor.packaging._parser.parse_marker (str source)
Definition at line 252 of file _parser.py.
def parse_marker(source: str) -> MarkerList:
    return _parse_full_marker(Tokenizer(source, rules=DEFAULT_RULES))
References _parse_full_marker().
parse_requirement()
ParsedRequirement pip._vendor.packaging._parser.parse_requirement (str source)
Definition at line 61 of file _parser.py.
def parse_requirement(source: str) -> ParsedRequirement:
    return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
References _parse_requirement().
process_env_var()
Variable pip._vendor.packaging._parser.process_env_var (str env_var)
Definition at line 324 of file _parser.py.
def process_env_var(env_var: str) -> Variable:
    if env_var in ("platform_python_implementation", "python_implementation"):
        return Variable("platform_python_implementation")
    else:
        return Variable(env_var)
Referenced by _parse_marker_var().
process_python_str()
Value pip._vendor.packaging._parser.process_python_str (str python_str)
Definition at line 331 of file _parser.py.
def process_python_str(python_str: str) -> Value:
    value = ast.literal_eval(python_str)
    return Value(str(value))
Referenced by _parse_marker_var().
Variable Documentation
MarkerAtom
pip._vendor.packaging._parser.MarkerAtom = Union[MarkerItem, Sequence["MarkerAtom"]]
Definition at line 46 of file _parser.py.
MarkerItem
pip._vendor.packaging._parser.MarkerItem = Tuple[MarkerVar, Op, MarkerVar]
Definition at line 45 of file _parser.py.
MarkerList
pip._vendor.packaging._parser.MarkerList = Sequence[Union["MarkerList", MarkerAtom, str]]
Definition at line 47 of file _parser.py.
MarkerVar
pip._vendor.packaging._parser.MarkerVar = Union[Variable, Value]
Definition at line 44 of file _parser.py.