Read&Watch: django.db.models.query Namespace Reference
django.db.models.query Namespace Reference
Classes
class BaseIterable
class EmptyQuerySet
class FlatValuesListIterable
class InstanceCheckMeta
class ModelIterable
class NamedValuesListIterable
class Prefetch
class QuerySet
class RawModelIterable
class RawQuerySet
class RelatedPopulator
class ValuesIterable
class ValuesListIterable
Functions
normalize_prefetch_lookups (lookups, prefix=None)
prefetch_related_objects (model_instances, *related_lookups)
aprefetch_related_objects (model_instances, *related_lookups)
get_prefetcher (instance, through_attr, to_attr)
prefetch_one_level (instances, prefetcher, lookup, level)
get_related_populators (klass_info, select, db)
Variables
int MAX_GET_RESULTS = 21
int REPR_OUTPUT_SIZE = 20
Detailed Description
The main QuerySet implementation. This provides the public API for the ORM.
Function Documentation
aprefetch_related_objects()
django.db.models.query.aprefetch_related_objects (model_instances, * related_lookups)
See prefetch_related_objects().
Definition at line 2433 of file query.py.
async def aprefetch_related_objects(model_instances, *related_lookups):
    """See prefetch_related_objects()."""
    return await sync_to_async(prefetch_related_objects)(
        model_instances, *related_lookups
    )
Referenced by django.db.models.query.QuerySet.aiterator().
get_prefetcher()
django.db.models.query.get_prefetcher (instance, through_attr, to_attr)
For the attribute 'through_attr' on the given instance, find
an object that has a get_prefetch_querysets().
Return a 4 tuple containing:
(the object with get_prefetch_querysets (or None),
 the descriptor object representing this relationship (or None),
 a boolean that is False if the attribute was not found at all,
 a function that takes an instance and returns a boolean that is True if
 the attribute has already been fetched for that instance)
Definition at line 2440 of file query.py.
def get_prefetcher(instance, through_attr, to_attr):
    """
    For the attribute 'through_attr' on the given instance, find
    an object that has a get_prefetch_querysets().
    Return a 4 tuple containing:
    (the object with get_prefetch_querysets (or None),
     the descriptor object representing this relationship (or None),
     a boolean that is False if the attribute was not found at all,
     a function that takes an instance and returns a boolean that is True if
     the attribute has already been fetched for that instance)
    """
    def is_to_attr_fetched(model, to_attr):
        # Special case cached_property instances because hasattr() triggers
        # attribute computation and assignment.
        if isinstance(getattr(model, to_attr, None), cached_property):
            def has_cached_property(instance):
                return to_attr in instance.__dict__
            return has_cached_property
        def has_to_attr_attribute(instance):
            return hasattr(instance, to_attr)
        return has_to_attr_attribute
    prefetcher = None
    is_fetched = is_to_attr_fetched(instance.__class__, to_attr)
    # For singly related objects, we have to avoid getting the attribute
    # from the object, as this will trigger the query. So we first try
    # on the class, in order to get the descriptor object.
    rel_obj_descriptor = getattr(instance.__class__, through_attr, None)
    if rel_obj_descriptor is None:
        attr_found = hasattr(instance, through_attr)
    else:
        attr_found = True
        if rel_obj_descriptor:
            # singly related object, descriptor object has the
            # get_prefetch_querysets() method.
            if (
                hasattr(rel_obj_descriptor, "get_prefetch_querysets")
                # RemovedInDjango60Warning.
                or hasattr(rel_obj_descriptor, "get_prefetch_queryset")
            ):
                prefetcher = rel_obj_descriptor
                # If to_attr is set, check if the value has already been set,
                # which is done with has_to_attr_attribute(). Do not use the
                # method from the descriptor, as the cache_name it defines
                # checks the field name, not the to_attr value.
                if through_attr == to_attr:
                    is_fetched = rel_obj_descriptor.is_cached
            else:
                # descriptor doesn't support prefetching, so we go ahead and get
                # the attribute on the instance rather than the class to
                # support many related managers
                rel_obj = getattr(instance, through_attr)
                if (
                    hasattr(rel_obj, "get_prefetch_querysets")
                    # RemovedInDjango60Warning.
                    or hasattr(rel_obj, "get_prefetch_queryset")
                ):
                    prefetcher = rel_obj
                if through_attr == to_attr:
                    def in_prefetched_cache(instance):
                        return through_attr in instance._prefetched_objects_cache
                    is_fetched = in_prefetched_cache
    return prefetcher, rel_obj_descriptor, attr_found, is_fetched
Referenced by prefetch_related_objects().
get_related_populators()
django.db.models.query.get_related_populators (klass_info, select, db)
Definition at line 2726 of file query.py.
def get_related_populators(klass_info, select, db):
    iterators = []
    related_klass_infos = klass_info.get("related_klass_infos", [])
    for rel_klass_info in related_klass_infos:
        rel_cls = RelatedPopulator(rel_klass_info, select, db)
        iterators.append(rel_cls)
    return iterators
Referenced by django.db.models.query.ModelIterable.__iter__().
normalize_prefetch_lookups()
django.db.models.query.normalize_prefetch_lookups (lookups, prefix = None)
Normalize lookups into Prefetch objects.
Definition at line 2267 of file query.py.
def normalize_prefetch_lookups(lookups, prefix=None):
    """Normalize lookups into Prefetch objects."""
    ret = []
    for lookup in lookups:
        if not isinstance(lookup, Prefetch):
            lookup = Prefetch(lookup)
        if prefix:
            lookup.add_prefix(prefix)
        ret.append(lookup)
    return ret
Referenced by prefetch_related_objects().
prefetch_one_level()
django.db.models.query.prefetch_one_level (instances, prefetcher, lookup, level)
Helper function for prefetch_related_objects().
Run prefetches on all instances using the prefetcher object,
assigning results to relevant caches in instance.
Return the prefetched objects along with any additional prefetches that
must be done due to prefetch_related lookups found from default managers.
Definition at line 2513 of file query.py.
def prefetch_one_level(instances, prefetcher, lookup, level):
    """
    Helper function for prefetch_related_objects().
    Run prefetches on all instances using the prefetcher object,
    assigning results to relevant caches in instance.
    Return the prefetched objects along with any additional prefetches that
    must be done due to prefetch_related lookups found from default managers.
    """
    # prefetcher must have a method get_prefetch_querysets() which takes a list
    # of instances, and returns a tuple:
    # (queryset of instances of self.model that are related to passed in instances,
    #  callable that gets value to be matched for returned instances,
    #  callable that gets value to be matched for passed in instances,
    #  boolean that is True for singly related objects,
    #  cache or field name to assign to,
    #  boolean that is True when the previous argument is a cache name vs a field name).
    # The 'values to be matched' must be hashable as they will be used
    # in a dictionary.
    if hasattr(prefetcher, "get_prefetch_querysets"):
        (
            rel_qs,
            rel_obj_attr,
            instance_attr,
            single,
            cache_name,
            is_descriptor,
        ) = prefetcher.get_prefetch_querysets(
            instances, lookup.get_current_querysets(level)
        )
    else:
        warnings.warn(
            "The usage of get_prefetch_queryset() in prefetch_related_objects() is "
            "deprecated. Implement get_prefetch_querysets() instead.",
            RemovedInDjango60Warning,
            stacklevel=2,
        )
        queryset = None
        if querysets := lookup.get_current_querysets(level):
            queryset = querysets[0]
        (
            rel_qs,
            rel_obj_attr,
            instance_attr,
            single,
            cache_name,
            is_descriptor,
        ) = prefetcher.get_prefetch_queryset(instances, queryset)
    # We have to handle the possibility that the QuerySet we just got back
    # contains some prefetch_related lookups. We don't want to trigger the
    # prefetch_related functionality by evaluating the query. Rather, we need
    # to merge in the prefetch_related lookups.
    # Copy the lookups in case it is a Prefetch object which could be reused
    # later (happens in nested prefetch_related).
    additional_lookups = [
        copy.copy(additional_lookup)
        for additional_lookup in getattr(rel_qs, "_prefetch_related_lookups", ())
    ]
    if additional_lookups:
        # Don't need to clone because the manager should have given us a fresh
        # instance, so we access an internal instead of using public interface
        # for performance reasons.
        rel_qs._prefetch_related_lookups = ()
    all_related_objects = list(rel_qs)
    rel_obj_cache = {}
    for rel_obj in all_related_objects:
        rel_attr_val = rel_obj_attr(rel_obj)
        rel_obj_cache.setdefault(rel_attr_val, []).append(rel_obj)
    to_attr, as_attr = lookup.get_current_to_attr(level)
    # Make sure `to_attr` does not conflict with a field.
    if as_attr and instances:
        # We assume that objects retrieved are homogeneous (which is the premise
        # of prefetch_related), so what applies to first object applies to all.
        model = instances[0].__class__
        try:
            model._meta.get_field(to_attr)
        except exceptions.FieldDoesNotExist:
            pass
        else:
            msg = "to_attr={} conflicts with a field on the {} model."
            raise ValueError(msg.format(to_attr, model.__name__))
    # Whether or not we're prefetching the last part of the lookup.
    leaf = len(lookup.prefetch_through.split(LOOKUP_SEP)) - 1 == level
    for obj in instances:
        instance_attr_val = instance_attr(obj)
        vals = rel_obj_cache.get(instance_attr_val, [])
        if single:
            val = vals[0] if vals else None
            if as_attr:
                # A to_attr has been given for the prefetch.
                setattr(obj, to_attr, val)
            elif is_descriptor:
                # cache_name points to a field name in obj.
                # This field is a descriptor for a related object.
                setattr(obj, cache_name, val)
            else:
                # No to_attr has been given for this prefetch operation and the
                # cache_name does not point to a descriptor. Store the value of
                # the field in the object's field cache.
                obj._state.fields_cache[cache_name] = val
        else:
            if as_attr:
                setattr(obj, to_attr, vals)
            else:
                manager = getattr(obj, to_attr)
                if leaf and lookup.queryset is not None:
                    qs = manager._apply_rel_filters(lookup.queryset)
                else:
                    qs = manager.get_queryset()
                qs._result_cache = vals
                # We don't want the individual qs doing prefetch_related now,
                # since we have merged this into the current work.
                qs._prefetch_done = True
                obj._prefetched_objects_cache[cache_name] = qs
    return all_related_objects, additional_lookups
Referenced by prefetch_related_objects().
prefetch_related_objects()
django.db.models.query.prefetch_related_objects (model_instances, * related_lookups)
Populate prefetched object caches for a list of model instances based on
the lookups/Prefetch instances given.
Definition at line 2279 of file query.py.
def prefetch_related_objects(model_instances, *related_lookups):
    """
    Populate prefetched object caches for a list of model instances based on
    the lookups/Prefetch instances given.
    """
    if not model_instances:
        return  # nothing to do
    # We need to be able to dynamically add to the list of prefetch_related
    # lookups that we look up (see below).  So we need some book keeping to
    # ensure we don't do duplicate work.
    done_queries = {}  # dictionary of things like 'foo__bar': [results]
    auto_lookups = set()  # we add to this as we go through.
    followed_descriptors = set()  # recursion protection
    all_lookups = normalize_prefetch_lookups(reversed(related_lookups))
    while all_lookups:
        lookup = all_lookups.pop()
        if lookup.prefetch_to in done_queries:
            if lookup.queryset is not None:
                raise ValueError(
                    "'%s' lookup was already seen with a different queryset. "
                    "You may need to adjust the ordering of your lookups."
                    % lookup.prefetch_to
                )
            continue
        # Top level, the list of objects to decorate is the result cache
        # from the primary QuerySet. It won't be for deeper levels.
        obj_list = model_instances
        through_attrs = lookup.prefetch_through.split(LOOKUP_SEP)
        for level, through_attr in enumerate(through_attrs):
            # Prepare main instances
            if not obj_list:
                break
            prefetch_to = lookup.get_current_prefetch_to(level)
            if prefetch_to in done_queries:
                # Skip any prefetching, and any object preparation
                obj_list = done_queries[prefetch_to]
                continue
            # Prepare objects:
            good_objects = True
            for obj in obj_list:
                # Since prefetching can re-use instances, it is possible to have
                # the same instance multiple times in obj_list, so obj might
                # already be prepared.
                if not hasattr(obj, "_prefetched_objects_cache"):
                    try:
                        obj._prefetched_objects_cache = {}
                    except (AttributeError, TypeError):
                        # Must be an immutable object from
                        # values_list(flat=True), for example (TypeError) or
                        # a QuerySet subclass that isn't returning Model
                        # instances (AttributeError), either in Django or a 3rd
                        # party. prefetch_related() doesn't make sense, so quit.
                        good_objects = False
                        break
            if not good_objects:
                break
            # Descend down tree
            # We assume that objects retrieved are homogeneous (which is the premise
            # of prefetch_related), so what applies to first object applies to all.
            first_obj = obj_list[0]
            to_attr = lookup.get_current_to_attr(level)[0]
            prefetcher, descriptor, attr_found, is_fetched = get_prefetcher(
                first_obj, through_attr, to_attr
            )
            if not attr_found:
                raise AttributeError(
                    "Cannot find '%s' on %s object, '%s' is an invalid "
                    "parameter to prefetch_related()"
                    % (
                        through_attr,
                        first_obj.__class__.__name__,
                        lookup.prefetch_through,
                    )
                )
            if level == len(through_attrs) - 1 and prefetcher is None:
                # Last one, this *must* resolve to something that supports
                # prefetching, otherwise there is no point adding it and the
                # developer asking for it has made a mistake.
                raise ValueError(
                    "'%s' does not resolve to an item that supports "
                    "prefetching - this is an invalid parameter to "
                    "prefetch_related()." % lookup.prefetch_through
                )
            obj_to_fetch = None
            if prefetcher is not None:
                obj_to_fetch = [obj for obj in obj_list if not is_fetched(obj)]
            if obj_to_fetch:
                obj_list, additional_lookups = prefetch_one_level(
                    obj_to_fetch,
                    prefetcher,
                    lookup,
                    level,
                )
                # We need to ensure we don't keep adding lookups from the
                # same relationships to stop infinite recursion. So, if we
                # are already on an automatically added lookup, don't add
                # the new lookups from relationships we've seen already.
                if not (
                    prefetch_to in done_queries
                    and lookup in auto_lookups
                    and descriptor in followed_descriptors
                ):
                    done_queries[prefetch_to] = obj_list
                    new_lookups = normalize_prefetch_lookups(
                        reversed(additional_lookups), prefetch_to
                    )
                    auto_lookups.update(new_lookups)
                    all_lookups.extend(new_lookups)
                followed_descriptors.add(descriptor)
            else:
                # Either a singly related object that has already been fetched
                # (e.g. via select_related), or hopefully some other property
                # that doesn't support prefetching but needs to be traversed.
                # We replace the current list of parent objects with the list
                # of related objects, filtering out empty or missing values so
                # that we can continue with nullable or reverse relations.
                new_obj_list = []
                for obj in obj_list:
                    if through_attr in getattr(obj, "_prefetched_objects_cache", ()):
                        # If related objects have been prefetched, use the
                        # cache rather than the object's through_attr.
                        new_obj = list(obj._prefetched_objects_cache.get(through_attr))
                    else:
                        try:
                            new_obj = getattr(obj, through_attr)
                        except exceptions.ObjectDoesNotExist:
                            continue
                    if new_obj is None:
                        continue
                    # We special-case `list` rather than something more generic
                    # like `Iterable` because we don't want to accidentally match
                    # user models that define __iter__.
                    if isinstance(new_obj, list):
                        new_obj_list.extend(new_obj)
                    else:
                        new_obj_list.append(new_obj)
                obj_list = new_obj_list
References get_prefetcher(), normalize_prefetch_lookups(), and prefetch_one_level().
Referenced by django.db.models.query.QuerySet._iterator(), django.db.models.query.QuerySet._prefetch_related_objects(), and django.db.models.query.RawQuerySet._prefetch_related_objects().
Variable Documentation
MAX_GET_RESULTS
int django.db.models.query.MAX_GET_RESULTS = 21
Definition at line 40 of file query.py.
REPR_OUTPUT_SIZE
int django.db.models.query.REPR_OUTPUT_SIZE = 20
Definition at line 43 of file query.py.