Read&Watch: charset_normalizer.utils Namespace Reference
charset_normalizer.utils Namespace Reference
Functions
bool is_accentuated (str character)
str remove_accent (str character)
Optional[str] unicode_range (str character)
bool is_latin (str character)
bool is_punctuation (str character)
bool is_symbol (str character)
bool is_emoticon (str character)
bool is_separator (str character)
bool is_case_variable (str character)
bool is_cjk (str character)
bool is_hiragana (str character)
bool is_katakana (str character)
bool is_hangul (str character)
bool is_thai (str character)
bool is_arabic (str character)
bool is_arabic_isolated_form (str character)
bool is_unicode_range_secondary (str range_name)
bool is_unprintable (str character)
Optional[str] any_specified_encoding (bytes sequence, int search_zone=8192)
bool is_multi_byte_encoding (str name)
Tuple[Optional[str], bytes] identify_sig_or_bom (bytes sequence)
bool should_strip_sig_or_bom (str iana_encoding)
str iana_name (str cp_name, bool strict=True)
List[str] range_scan (str decoded_sequence)
float cp_similarity (str iana_name_a, str iana_name_b)
bool is_cp_similar (str iana_name_a, str iana_name_b)
None set_logging_handler (str name="charset_normalizer", int level=logging.INFO, str format_string="%(asctime)s | %(levelname)s | %(message)s")
Generator[str, None, None] cut_sequence_chunks (bytes sequences, str encoding_iana, range offsets, int chunk_size, bool bom_or_sig_available, bool strip_sig_or_bom, bytes sig_payload, bool is_multi_byte_decoder, Optional[str] decoded_payload=None)
Function Documentation
any_specified_encoding()
Optional[str] charset_normalizer.utils.any_specified_encoding (bytes sequence, int search_zone = 8192)
Extract using ASCII-only decoder any specified encoding in the first n-bytes.
Definition at line 215 of file utils.py.
def any_specified_encoding(sequence: bytes, search_zone: int = 8192) -> Optional[str]:
    """
    Extract using ASCII-only decoder any specified encoding in the first n-bytes.
    """
    if not isinstance(sequence, bytes):
        raise TypeError
    seq_len: int = len(sequence)
    results: List[str] = findall(
        RE_POSSIBLE_ENCODING_INDICATION,
        sequence[: min(seq_len, search_zone)].decode("ascii", errors="ignore"),
    )
    if len(results) == 0:
        return None
    for specified_encoding in results:
        specified_encoding = specified_encoding.lower().replace("-", "_")
        encoding_alias: str
        encoding_iana: str
        for encoding_alias, encoding_iana in aliases.items():
            if encoding_alias == specified_encoding:
                return encoding_iana
            if encoding_iana == specified_encoding:
                return encoding_iana
    return None
@lru_cache(maxsize=128)
cp_similarity()
float charset_normalizer.utils.cp_similarity (str iana_name_a, str iana_name_b)
Definition at line 320 of file utils.py.
def cp_similarity(iana_name_a: str, iana_name_b: str) -> float:
    if is_multi_byte_encoding(iana_name_a) or is_multi_byte_encoding(iana_name_b):
        return 0.0
    decoder_a = importlib.import_module(
        "encodings.{}".format(iana_name_a)
    ).IncrementalDecoder
    decoder_b = importlib.import_module(
        "encodings.{}".format(iana_name_b)
    ).IncrementalDecoder
    id_a: IncrementalDecoder = decoder_a(errors="ignore")
    id_b: IncrementalDecoder = decoder_b(errors="ignore")
    character_match_count: int = 0
    for i in range(255):
        to_be_decoded: bytes = bytes([i])
        if id_a.decode(to_be_decoded) == id_b.decode(to_be_decoded):
            character_match_count += 1
    return character_match_count / 254
References is_multi_byte_encoding().
cut_sequence_chunks()
Generator[str, None, None] charset_normalizer.utils.cut_sequence_chunks (bytes sequences, str encoding_iana, range offsets, int chunk_size, bool bom_or_sig_available, bool strip_sig_or_bom, bytes sig_payload, bool is_multi_byte_decoder, Optional[str] decoded_payload = None)
Definition at line 368 of file utils.py.
) -> Generator[str, None, None]:
    if decoded_payload and is_multi_byte_decoder is False:
        for i in offsets:
            chunk = decoded_payload[i : i + chunk_size]
            if not chunk:
                break
            yield chunk
    else:
        for i in offsets:
            chunk_end = i + chunk_size
            if chunk_end > len(sequences) + 8:
                continue
            cut_sequence = sequences[i : i + chunk_size]
            if bom_or_sig_available and strip_sig_or_bom is False:
                cut_sequence = sig_payload + cut_sequence
            chunk = cut_sequence.decode(
                encoding_iana,
                errors="ignore" if is_multi_byte_decoder else "strict",
            )
            # multi-byte bad cutting detector and adjustment
            # not the cleanest way to perform that fix but clever enough for now.
            if is_multi_byte_decoder and i > 0:
                chunk_partial_size_chk: int = min(chunk_size, 16)
                if (
                    decoded_payload
                    and chunk[:chunk_partial_size_chk] not in decoded_payload
                ):
                    for j in range(i, i - 4, -1):
                        cut_sequence = sequences[j:chunk_end]
                        if bom_or_sig_available and strip_sig_or_bom is False:
                            cut_sequence = sig_payload + cut_sequence
                        chunk = cut_sequence.decode(encoding_iana, errors="ignore")
                        if chunk[:chunk_partial_size_chk] in decoded_payload:
                            break
            yield chunk
iana_name()
str charset_normalizer.utils.iana_name (str cp_name, bool strict = True)
Definition at line 290 of file utils.py.
def iana_name(cp_name: str, strict: bool = True) -> str:
    cp_name = cp_name.lower().replace("-", "_")
    encoding_alias: str
    encoding_iana: str
    for encoding_alias, encoding_iana in aliases.items():
        if cp_name in [encoding_alias, encoding_iana]:
            return encoding_iana
    if strict:
        raise ValueError("Unable to retrieve IANA for '{}'".format(cp_name))
    return cp_name
identify_sig_or_bom()
Tuple[Optional[str], bytes] charset_normalizer.utils.identify_sig_or_bom (bytes sequence)
Identify and extract SIG/BOM in given sequence.
Definition at line 268 of file utils.py.
def identify_sig_or_bom(sequence: bytes) -> Tuple[Optional[str], bytes]:
    """
    Identify and extract SIG/BOM in given sequence.
    """
    for iana_encoding in ENCODING_MARKS:
        marks: Union[bytes, List[bytes]] = ENCODING_MARKS[iana_encoding]
        if isinstance(marks, bytes):
            marks = [marks]
        for mark in marks:
            if sequence.startswith(mark):
                return iana_encoding, mark
    return None, b""
is_accentuated()
bool charset_normalizer.utils.is_accentuated (str character)
Definition at line 23 of file utils.py.
def is_accentuated(character: str) -> bool:
    try:
        description: str = unicodedata.name(character)
    except ValueError:
        return False
    return (
        "WITH GRAVE" in description
        or "WITH ACUTE" in description
        or "WITH CEDILLA" in description
        or "WITH DIAERESIS" in description
        or "WITH CIRCUMFLEX" in description
        or "WITH TILDE" in description
        or "WITH MACRON" in description
        or "WITH RING ABOVE" in description
    )
@lru_cache(maxsize=UTF8_MAXIMAL_ALLOCATION)
is_arabic()
bool charset_normalizer.utils.is_arabic (str character)
Definition at line 180 of file utils.py.
def is_arabic(character: str) -> bool:
    try:
        character_name = unicodedata.name(character)
    except ValueError:
        return False
    return "ARABIC" in character_name
@lru_cache(maxsize=UTF8_MAXIMAL_ALLOCATION)
is_arabic_isolated_form()
bool charset_normalizer.utils.is_arabic_isolated_form (str character)
Definition at line 190 of file utils.py.
def is_arabic_isolated_form(character: str) -> bool:
    try:
        character_name = unicodedata.name(character)
    except ValueError:
        return False
    return "ARABIC" in character_name and "ISOLATED FORM" in character_name
@lru_cache(maxsize=len(UNICODE_RANGES_COMBINED))
is_case_variable()
bool charset_normalizer.utils.is_case_variable (str character)
Definition at line 125 of file utils.py.
def is_case_variable(character: str) -> bool:
    return character.islower() != character.isupper()
@lru_cache(maxsize=UTF8_MAXIMAL_ALLOCATION)
is_cjk()
bool charset_normalizer.utils.is_cjk (str character)
Definition at line 130 of file utils.py.
def is_cjk(character: str) -> bool:
    try:
        character_name = unicodedata.name(character)
    except ValueError:
        return False
    return "CJK" in character_name
@lru_cache(maxsize=UTF8_MAXIMAL_ALLOCATION)
is_cp_similar()
bool charset_normalizer.utils.is_cp_similar (str iana_name_a, str iana_name_b)
Determine if two code page are at least 80% similar. IANA_SUPPORTED_SIMILAR dict was generated using
the function cp_similarity.
Definition at line 344 of file utils.py.
def is_cp_similar(iana_name_a: str, iana_name_b: str) -> bool:
    """
    Determine if two code page are at least 80% similar. IANA_SUPPORTED_SIMILAR dict was generated using
    the function cp_similarity.
    """
    return (
        iana_name_a in IANA_SUPPORTED_SIMILAR
        and iana_name_b in IANA_SUPPORTED_SIMILAR[iana_name_a]
    )
is_emoticon()
bool charset_normalizer.utils.is_emoticon (str character)
Definition at line 105 of file utils.py.
def is_emoticon(character: str) -> bool:
    character_range: Optional[str] = unicode_range(character)
    if character_range is None:
        return False
    return "Emoticons" in character_range or "Pictographs" in character_range
@lru_cache(maxsize=UTF8_MAXIMAL_ALLOCATION)
References unicode_range().
is_hangul()
bool charset_normalizer.utils.is_hangul (str character)
Definition at line 160 of file utils.py.
def is_hangul(character: str) -> bool:
    try:
        character_name = unicodedata.name(character)
    except ValueError:
        return False
    return "HANGUL" in character_name
@lru_cache(maxsize=UTF8_MAXIMAL_ALLOCATION)
is_hiragana()
bool charset_normalizer.utils.is_hiragana (str character)
Definition at line 140 of file utils.py.
def is_hiragana(character: str) -> bool:
    try:
        character_name = unicodedata.name(character)
    except ValueError:
        return False
    return "HIRAGANA" in character_name
@lru_cache(maxsize=UTF8_MAXIMAL_ALLOCATION)
is_katakana()
bool charset_normalizer.utils.is_katakana (str character)
Definition at line 150 of file utils.py.
def is_katakana(character: str) -> bool:
    try:
        character_name = unicodedata.name(character)
    except ValueError:
        return False
    return "KATAKANA" in character_name
@lru_cache(maxsize=UTF8_MAXIMAL_ALLOCATION)
is_latin()
bool charset_normalizer.utils.is_latin (str character)
Definition at line 66 of file utils.py.
def is_latin(character: str) -> bool:
    try:
        description: str = unicodedata.name(character)
    except ValueError:
        return False
    return "LATIN" in description
@lru_cache(maxsize=UTF8_MAXIMAL_ALLOCATION)
is_multi_byte_encoding()
bool charset_normalizer.utils.is_multi_byte_encoding (str name)
Verify is a specific encoding is a multi byte one based on it IANA name
Definition at line 248 of file utils.py.
def is_multi_byte_encoding(name: str) -> bool:
    """
    Verify is a specific encoding is a multi byte one based on it IANA name
    """
    return name in {
        "utf_8",
        "utf_8_sig",
        "utf_16",
        "utf_16_be",
        "utf_16_le",
        "utf_32",
        "utf_32_le",
        "utf_32_be",
        "utf_7",
    } or issubclass(
        importlib.import_module("encodings.{}".format(name)).IncrementalDecoder,
        MultibyteIncrementalDecoder,
    )
Referenced by cp_similarity().
is_punctuation()
bool charset_normalizer.utils.is_punctuation (str character)
Definition at line 75 of file utils.py.
def is_punctuation(character: str) -> bool:
    character_category: str = unicodedata.category(character)
    if "P" in character_category:
        return True
    character_range: Optional[str] = unicode_range(character)
    if character_range is None:
        return False
    return "Punctuation" in character_range
@lru_cache(maxsize=UTF8_MAXIMAL_ALLOCATION)
References unicode_range().
is_separator()
bool charset_normalizer.utils.is_separator (str character)
Definition at line 115 of file utils.py.
def is_separator(character: str) -> bool:
    if character.isspace() or character in {"", "+", "<", ">"}:
        return True
    character_category: str = unicodedata.category(character)
    return "Z" in character_category or character_category in {"Po", "Pd", "Pc"}
@lru_cache(maxsize=UTF8_MAXIMAL_ALLOCATION)
is_symbol()
bool charset_normalizer.utils.is_symbol (str character)
Definition at line 90 of file utils.py.
def is_symbol(character: str) -> bool:
    character_category: str = unicodedata.category(character)
    if "S" in character_category or "N" in character_category:
        return True
    character_range: Optional[str] = unicode_range(character)
    if character_range is None:
        return False
    return "Forms" in character_range and character_category != "Lo"
@lru_cache(maxsize=UTF8_MAXIMAL_ALLOCATION)
References unicode_range().
is_thai()
bool charset_normalizer.utils.is_thai (str character)
Definition at line 170 of file utils.py.
def is_thai(character: str) -> bool:
    try:
        character_name = unicodedata.name(character)
    except ValueError:
        return False
    return "THAI" in character_name
@lru_cache(maxsize=UTF8_MAXIMAL_ALLOCATION)
is_unicode_range_secondary()
bool charset_normalizer.utils.is_unicode_range_secondary (str range_name)
Definition at line 200 of file utils.py.
def is_unicode_range_secondary(range_name: str) -> bool:
    return any(keyword in range_name for keyword in UNICODE_SECONDARY_RANGE_KEYWORD)
@lru_cache(maxsize=UTF8_MAXIMAL_ALLOCATION)
is_unprintable()
bool charset_normalizer.utils.is_unprintable (str character)
Definition at line 205 of file utils.py.
def is_unprintable(character: str) -> bool:
    return (
        character.isspace() is False  # includes \n \t \r \v
        and character.isprintable() is False
        and character != "\x1A"  # Why? Its the ASCII substitute character.
        and character != "\ufeff"  # bug discovered in Python,
        # Zero Width No-Break Space located in  Arabic Presentation Forms-B, Unicode 1.1 not acknowledged as space.
    )
range_scan()
List[str] charset_normalizer.utils.range_scan (str decoded_sequence)
Definition at line 306 of file utils.py.
def range_scan(decoded_sequence: str) -> List[str]:
    ranges: Set[str] = set()
    for character in decoded_sequence:
        character_range: Optional[str] = unicode_range(character)
        if character_range is None:
            continue
        ranges.add(character_range)
    return list(ranges)
References unicode_range().
remove_accent()
str charset_normalizer.utils.remove_accent (str character)
Definition at line 41 of file utils.py.
def remove_accent(character: str) -> str:
    decomposed: str = unicodedata.decomposition(character)
    if not decomposed:
        return character
    codes: List[str] = decomposed.split(" ")
    return chr(int(codes[0], 16))
@lru_cache(maxsize=UTF8_MAXIMAL_ALLOCATION)
set_logging_handler()
None charset_normalizer.utils.set_logging_handler (str name = "charset_normalizer", int level = logging.INFO, str format_string = "%(asctime)s | %(levelname)s | %(message)s")
Definition at line 355 of file utils.py.
) -> None:
    logger = logging.getLogger(name)
    logger.setLevel(level)
    handler = logging.StreamHandler()
    handler.setFormatter(logging.Formatter(format_string))
    logger.addHandler(handler)
should_strip_sig_or_bom()
bool charset_normalizer.utils.should_strip_sig_or_bom (str iana_encoding)
Definition at line 286 of file utils.py.
def should_strip_sig_or_bom(iana_encoding: str) -> bool:
    return iana_encoding not in {"utf_16", "utf_32"}
unicode_range()
Optional[str] charset_normalizer.utils.unicode_range (str character)
Retrieve the Unicode range official name from a single character.
Definition at line 52 of file utils.py.
def unicode_range(character: str) -> Optional[str]:
    """
    Retrieve the Unicode range official name from a single character.
    """
    character_ord: int = ord(character)
    for range_name, ord_range in UNICODE_RANGES_COMBINED.items():
        if character_ord in ord_range:
            return range_name
    return None
@lru_cache(maxsize=UTF8_MAXIMAL_ALLOCATION)
Referenced by is_emoticon(), is_punctuation(), is_symbol(), and range_scan().