Read&Watch: pip._vendor.cachecontrol.heuristics Namespace Reference
pip._vendor.cachecontrol.heuristics Namespace Reference
Classes
class BaseHeuristic
class ExpiresAfter
class LastModified
class OneDayCache
Functions
datetime expire_after (timedelta delta, datetime|None date=None)
str datetime_to_header (datetime dt)
Variables
str TIME_FMT = "%a, %d %b %Y %H:%M:%S GMT"
Function Documentation
datetime_to_header()
str pip._vendor.cachecontrol.heuristics.datetime_to_header (datetime dt)
Definition at line 23 of file heuristics.py.
def datetime_to_header(dt: datetime) -> str:
    return formatdate(calendar.timegm(dt.timetuple()))
Referenced by pip._vendor.cachecontrol.heuristics.ExpiresAfter.update_headers(), and pip._vendor.cachecontrol.heuristics.OneDayCache.update_headers().
expire_after()
datetime pip._vendor.cachecontrol.heuristics.expire_after (timedelta delta, datetime | None date = None)
Definition at line 18 of file heuristics.py.
def expire_after(delta: timedelta, date: datetime | None = None) -> datetime:
    date = date or datetime.now(timezone.utc)
    return date + delta
Referenced by pip._vendor.cachecontrol.heuristics.ExpiresAfter.update_headers(), and pip._vendor.cachecontrol.heuristics.OneDayCache.update_headers().
Variable Documentation
TIME_FMT
str pip._vendor.cachecontrol.heuristics.TIME_FMT = "%a, %d %b %Y %H:%M:%S GMT"
Definition at line 15 of file heuristics.py.