Read&Watch: pylint.checkers.exceptions Namespace Reference
pylint.checkers.exceptions Namespace Reference
Classes
class BaseVisitor
class ExceptionRaiseLeafVisitor
class ExceptionRaiseRefVisitor
class ExceptionsChecker
Functions
set[str] _builtin_exceptions ()
Generator[tuple[nodes.NodeNG, SuccessfulInferenceResult]] _annotated_unpack_infer (nodes.NodeNG stmt, InferenceContext|None context=None)
bool _is_raising (list[nodes.NodeNG] body)
None register (PyLinter linter)
Variables
dict MSGS
Detailed Description
Checks for various exception related errors.
Function Documentation
_annotated_unpack_infer()
Generator[tuple[nodes.NodeNG, SuccessfulInferenceResult]] pylint.checkers.exceptions._annotated_unpack_infer (nodes.NodeNG stmt, InferenceContext | None context = None) protected
Recursively generate nodes inferred by the given statement.
If the inferred value is a list or a tuple, recurse on the elements.
Returns an iterator which yields tuples in the format
('original node', 'inferred node').
Definition at line 36 of file exceptions.py.
) -> Generator[tuple[nodes.NodeNG, SuccessfulInferenceResult]]:
    """Recursively generate nodes inferred by the given statement.
    If the inferred value is a list or a tuple, recurse on the elements.
    Returns an iterator which yields tuples in the format
    ('original node', 'inferred node').
    """
    if isinstance(stmt, (nodes.List, nodes.Tuple)):
        for elt in stmt.elts:
            inferred = utils.safe_infer(elt)
            if inferred and not isinstance(inferred, util.UninferableBase):
                yield elt, inferred
        return
    for inferred in stmt.infer(context):
        if isinstance(inferred, util.UninferableBase):
            continue
        yield stmt, inferred
Referenced by pylint.checkers.exceptions.ExceptionRaiseRefVisitor.visit_name(), and pylint.checkers.exceptions.ExceptionsChecker.visit_try().
_builtin_exceptions()
set[str] pylint.checkers.exceptions._builtin_exceptions () protected
Definition at line 28 of file exceptions.py.
def _builtin_exceptions() -> set[str]:
    def predicate(obj: Any) -> bool:
        return isinstance(obj, type) and issubclass(obj, BaseException)
    members = inspect.getmembers(builtins, predicate)
    return {exc.__name__ for (_, exc) in members}
_is_raising()
bool pylint.checkers.exceptions._is_raising (list[nodes.NodeNG] body) protected
Return whether the given statement node raises an exception.
Definition at line 57 of file exceptions.py.
def _is_raising(body: list[nodes.NodeNG]) -> bool:
    """Return whether the given statement node raises an exception."""
    return any(isinstance(node, nodes.Raise) for node in body)
Referenced by pylint.checkers.exceptions.ExceptionsChecker._check_try_except_raise(), and pylint.checkers.exceptions.ExceptionsChecker.visit_try().
register()
None pylint.checkers.exceptions.register (PyLinter linter)
Definition at line 653 of file exceptions.py.
def register(linter: PyLinter) -> None:
    linter.register_checker(ExceptionsChecker(linter))
Variable Documentation
MSGS
dict pylint.checkers.exceptions.MSGS
Definition at line 62 of file exceptions.py.