Read&Watch: pip._vendor.packaging.markers Namespace Reference
pip._vendor.packaging.markers Namespace Reference
Classes
class Environment
class InvalidMarker
class Marker
class UndefinedComparison
class UndefinedEnvironmentName
Functions
Any _normalize_extra_values (Any results)
str _format_marker (list[str]|MarkerAtom|str marker, bool|None first=True)
bool _eval_op (str lhs, Op op, str rhs)
tuple[str,...] _normalize (*str values, str key)
bool _evaluate_markers (MarkerList markers, dict[str, str] environment)
str format_full_version (sys._version_info info)
Environment default_environment ()
Variables
Operator = Callable[[str, str], bool]
dict _operators
Function Documentation
_eval_op()
bool pip._vendor.packaging.markers._eval_op (str lhs, Op op, str rhs) protected
Definition at line 177 of file markers.py.
def _eval_op(lhs: str, op: Op, rhs: str) -> bool:
    try:
        spec = Specifier("".join([op.serialize(), rhs]))
    except InvalidSpecifier:
        pass
    else:
        return spec.contains(lhs, prereleases=True)
    oper: Operator | None = _operators.get(op.serialize())
    if oper is None:
        raise UndefinedComparison(f"Undefined {op!r} on {lhs!r} and {rhs!r}.")
    return oper(lhs, rhs)
Referenced by _evaluate_markers().
_evaluate_markers()
bool pip._vendor.packaging.markers._evaluate_markers (MarkerList markers, dict[str, str] environment) protected
Definition at line 204 of file markers.py.
def _evaluate_markers(markers: MarkerList, environment: dict[str, str]) -> bool:
    groups: list[list[bool]] = [[]]
    for marker in markers:
        assert isinstance(marker, (list, tuple, str))
        if isinstance(marker, list):
            groups[-1].append(_evaluate_markers(marker, environment))
        elif isinstance(marker, tuple):
            lhs, op, rhs = marker
            if isinstance(lhs, Variable):
                environment_key = lhs.value
                lhs_value = environment[environment_key]
                rhs_value = rhs.value
            else:
                lhs_value = lhs.value
                environment_key = rhs.value
                rhs_value = environment[environment_key]
            lhs_value, rhs_value = _normalize(lhs_value, rhs_value, key=environment_key)
            groups[-1].append(_eval_op(lhs_value, op, rhs_value))
        else:
            assert marker in ["and", "or"]
            if marker == "or":
                groups.append([])
    return any(all(item) for item in groups)
References _eval_op(), _evaluate_markers(), and _normalize().
Referenced by _evaluate_markers(), and pip._vendor.packaging.markers.Marker.evaluate().
_format_marker()
str pip._vendor.packaging.markers._format_marker (list[str] | MarkerAtom | str marker, bool | None first = True) protected
Definition at line 137 of file markers.py.
) -> str:
    assert isinstance(marker, (list, tuple, str))
    # Sometimes we have a structure like [[...]] which is a single item list
    # where the single item is itself it's own list. In that case we want skip
    # the rest of this function so that we don't get extraneous () on the
    # outside.
    if (
        isinstance(marker, list)
        and len(marker) == 1
        and isinstance(marker[0], (list, tuple))
    ):
        return _format_marker(marker[0])
    if isinstance(marker, list):
        inner = (_format_marker(m, first=False) for m in marker)
        if first:
            return " ".join(inner)
        else:
            return "(" + " ".join(inner) + ")"
    elif isinstance(marker, tuple):
        return " ".join([m.serialize() for m in marker])
    else:
        return marker
References _format_marker().
Referenced by pip._vendor.packaging.markers.Marker.__str__(), and _format_marker().
_normalize()
tuple[str, ...] pip._vendor.packaging.markers._normalize (*str values, str key) protected
Definition at line 192 of file markers.py.
def _normalize(*values: str, key: str) -> tuple[str, ...]:
    # PEP 685 – Comparison of extra names for optional distribution dependencies
    # https://peps.python.org/pep-0685/
    # > When comparing extra names, tools MUST normalize the names being
    # > compared using the semantics outlined in PEP 503 for names
    if key == "extra":
        return tuple(canonicalize_name(v) for v in values)
    # other environment markers don't have such standards
    return values
Referenced by _evaluate_markers().
_normalize_extra_values()
Any pip._vendor.packaging.markers._normalize_extra_values (Any results) protected
Normalize extra values.
Definition at line 121 of file markers.py.
def _normalize_extra_values(results: Any) -> Any:
    """
    Normalize extra values.
    """
    if isinstance(results[0], tuple):
        lhs, op, rhs = results[0]
        if isinstance(lhs, Variable) and lhs.value == "extra":
            normalized_extra = canonicalize_name(rhs.value)
            rhs = Value(normalized_extra)
        elif isinstance(rhs, Variable) and rhs.value == "extra":
            normalized_extra = canonicalize_name(lhs.value)
            lhs = Value(normalized_extra)
        results[0] = lhs, op, rhs
    return results
default_environment()
Environment pip._vendor.packaging.markers.default_environment ()
Definition at line 242 of file markers.py.
def default_environment() -> Environment:
    iver = format_full_version(sys.implementation.version)
    implementation_name = sys.implementation.name
    return {
        "implementation_name": implementation_name,
        "implementation_version": iver,
        "os_name": os.name,
        "platform_machine": platform.machine(),
        "platform_release": platform.release(),
        "platform_system": platform.system(),
        "platform_version": platform.version(),
        "python_full_version": platform.python_version(),
        "platform_python_implementation": platform.python_implementation(),
        "python_version": ".".join(platform.python_version_tuple()[:2]),
        "sys_platform": sys.platform,
    }
References format_full_version().
Referenced by pip._vendor.packaging.markers.Marker.evaluate().
format_full_version()
str pip._vendor.packaging.markers.format_full_version (sys._version_info info)
Definition at line 234 of file markers.py.
def format_full_version(info: sys._version_info) -> str:
    version = "{0.major}.{0.minor}.{0.micro}".format(info)
    kind = info.releaselevel
    if kind != "final":
        version += kind[0] + str(info.serial)
    return version
Referenced by default_environment().
Variable Documentation
_operators
dict pip._vendor.packaging.markers._operators protected
Initial value:
=  {
    "in": lambda lhs, rhs: lhs in rhs,
    "not in": lambda lhs, rhs: lhs not in rhs,
    "<": operator.lt,
    "<=": operator.le,
    "==": operator.eq,
    "!=": operator.ne,
    ">=": operator.ge,
    ">": operator.gt,
}
Definition at line 165 of file markers.py.
Operator
pip._vendor.packaging.markers.Operator = Callable[[str, str], bool]
Definition at line 27 of file markers.py.