Read&Watch: dill.tests.test_threads Namespace Reference
dill.tests.test_threads Namespace Reference
Functions
test_new_thread ()
test_run_thread ()
test_join_thread ()
Function Documentation
test_join_thread()
dill.tests.test_threads.test_join_thread ()
Definition at line 31 of file test_threads.py.
def test_join_thread():
    import threading
    t = threading.Thread()
    t.start()
    t.join()
    t_ = dill.copy(t)
    assert t.is_alive() == t_.is_alive()
    for i in ['daemon','name','ident','native_id']:
        if hasattr(t, i):
            assert getattr(t, i) == getattr(t_, i)
References test_join_thread(), test_new_thread(), and test_run_thread().
Referenced by test_join_thread().
test_new_thread()
dill.tests.test_threads.test_new_thread ()
Definition at line 12 of file test_threads.py.
def test_new_thread():
    import threading
    t = threading.Thread()
    t_ = dill.copy(t)
    assert t.is_alive() == t_.is_alive()
    for i in ['daemon','name','ident','native_id']:
        if hasattr(t, i):
            assert getattr(t, i) == getattr(t_, i)
Referenced by test_join_thread().
test_run_thread()
dill.tests.test_threads.test_run_thread ()
Definition at line 21 of file test_threads.py.
def test_run_thread():
    import threading
    t = threading.Thread()
    t.start()
    t_ = dill.copy(t)
    assert t.is_alive() == t_.is_alive()
    for i in ['daemon','name','ident','native_id']:
        if hasattr(t, i):
            assert getattr(t, i) == getattr(t_, i)
Referenced by test_join_thread().