Read&Watch: dotenv.parser Namespace Reference
dotenv.parser Namespace Reference
Classes
class Binding
class Error
class Original
class Position
class Reader
Functions
Pattern[str] make_regex (str string, int extra_flags=0)
str decode_escapes (Pattern[str] regex, str string)
Optional[str] parse_key (Reader reader)
str parse_unquoted_value (Reader reader)
str parse_value (Reader reader)
Binding parse_binding (Reader reader)
Iterator[Binding] parse_stream (IO[str] stream)
Variables
Pattern[str] _newline = make_regex(r"(\r\n|\n|\r)")
Pattern[str] _multiline_whitespace = make_regex(r"\s*", extra_flags=re.MULTILINE)
Pattern[str] _whitespace = make_regex(r"[^\S\r\n]*")
Pattern[str] _export = make_regex(r"(?:export[^\S\r\n]+)?")
Pattern[str] _single_quoted_key = make_regex(r"'([^']+)'")
Pattern[str] _unquoted_key = make_regex(r"([^=\#\s]+)")
Pattern[str] _equal_sign = make_regex(r"(=[^\S\r\n]*)")
Pattern[str] _single_quoted_value = make_regex(r"'((?:\\'|[^'])*)'")
Pattern[str] _double_quoted_value = make_regex(r'"((?:\\"|[^"])*)"')
Pattern[str] _unquoted_value = make_regex(r"([^\r\n]*)")
Pattern[str] _comment = make_regex(r"(?:[^\S\r\n]*#[^\r\n]*)?")
Pattern[str] _end_of_line = make_regex(r"[^\S\r\n]*(?:\r\n|\n|\r|$)")
Pattern[str] _rest_of_line = make_regex(r"[^\r\n]*(?:\r|\n|\r\n)?")
Pattern[str] _double_quote_escapes = make_regex(r"\\[\\'\"abfnrtv]")
Pattern[str] _single_quote_escapes = make_regex(r"\\[\\']")
Function Documentation
decode_escapes()
str dotenv.parser.decode_escapes (Pattern[str] regex, str string)
Definition at line 98 of file parser.py.
def decode_escapes(regex: Pattern[str], string: str) -> str:
    def decode_match(match: Match[str]) -> str:
        return codecs.decode(match.group(0), 'unicode-escape')  # type: ignore
    return regex.sub(decode_match, string)
Referenced by parse_value().
make_regex()
Pattern[str] dotenv.parser.make_regex (str string, int extra_flags = 0)
Definition at line 7 of file parser.py.
def make_regex(string: str, extra_flags: int = 0) -> Pattern[str]:
    return re.compile(string, re.UNICODE | extra_flags)
parse_binding()
Binding dotenv.parser.parse_binding (Reader reader)
Definition at line 135 of file parser.py.
def parse_binding(reader: Reader) -> Binding:
    reader.set_mark()
    try:
        reader.read_regex(_multiline_whitespace)
        if not reader.has_next():
            return Binding(
                key=None,
                value=None,
                original=reader.get_marked(),
                error=False,
            )
        reader.read_regex(_export)
        key = parse_key(reader)
        reader.read_regex(_whitespace)
        if reader.peek(1) == "=":
            reader.read_regex(_equal_sign)
            value: Optional[str] = parse_value(reader)
        else:
            value = None
        reader.read_regex(_comment)
        reader.read_regex(_end_of_line)
        return Binding(
            key=key,
            value=value,
            original=reader.get_marked(),
            error=False,
        )
    except Error:
        reader.read_regex(_rest_of_line)
        return Binding(
            key=None,
            value=None,
            original=reader.get_marked(),
            error=True,
        )
References parse_key(), and parse_value().
Referenced by parse_stream().
parse_key()
Optional[str] dotenv.parser.parse_key (Reader reader)
Definition at line 105 of file parser.py.
def parse_key(reader: Reader) -> Optional[str]:
    char = reader.peek(1)
    if char == "#":
        return None
    elif char == "'":
        (key,) = reader.read_regex(_single_quoted_key)
    else:
        (key,) = reader.read_regex(_unquoted_key)
    return key
Referenced by parse_binding().
parse_stream()
Iterator[Binding] dotenv.parser.parse_stream (IO[str] stream)
Definition at line 172 of file parser.py.
def parse_stream(stream: IO[str]) -> Iterator[Binding]:
    reader = Reader(stream)
    while reader.has_next():
        yield parse_binding(reader)
References parse_binding().
parse_unquoted_value()
str dotenv.parser.parse_unquoted_value (Reader reader)
Definition at line 116 of file parser.py.
def parse_unquoted_value(reader: Reader) -> str:
    (part,) = reader.read_regex(_unquoted_value)
    return re.sub(r"\s+#.*", "", part).rstrip()
Referenced by parse_value().
parse_value()
str dotenv.parser.parse_value (Reader reader)
Definition at line 121 of file parser.py.
def parse_value(reader: Reader) -> str:
    char = reader.peek(1)
    if char == u"'":
        (value,) = reader.read_regex(_single_quoted_value)
        return decode_escapes(_single_quote_escapes, value)
    elif char == u'"':
        (value,) = reader.read_regex(_double_quoted_value)
        return decode_escapes(_double_quote_escapes, value)
    elif char in (u"", u"\n", u"\r"):
        return u""
    else:
        return parse_unquoted_value(reader)
References decode_escapes(), and parse_unquoted_value().
Referenced by parse_binding().
Variable Documentation
_comment
Pattern[str] dotenv.parser._comment = make_regex(r"(?:[^\S\r\n]*#[^\r\n]*)?") protected
Definition at line 21 of file parser.py.
_double_quote_escapes
Pattern[str] dotenv.parser._double_quote_escapes = make_regex(r"\\[\\'\"abfnrtv]") protected
Definition at line 24 of file parser.py.
_double_quoted_value
Pattern[str] dotenv.parser._double_quoted_value = make_regex(r'"((?:\\"|[^"])*)"') protected
Definition at line 19 of file parser.py.
_end_of_line
Pattern[str] dotenv.parser._end_of_line = make_regex(r"[^\S\r\n]*(?:\r\n|\n|\r|$)") protected
Definition at line 22 of file parser.py.
_equal_sign
Pattern[str] dotenv.parser._equal_sign = make_regex(r"(=[^\S\r\n]*)") protected
Definition at line 17 of file parser.py.
_export
Pattern[str] dotenv.parser._export = make_regex(r"(?:export[^\S\r\n]+)?") protected
Definition at line 14 of file parser.py.
_multiline_whitespace
Pattern[str] dotenv.parser._multiline_whitespace = make_regex(r"\s*", extra_flags=re.MULTILINE) protected
Definition at line 12 of file parser.py.
_newline
Pattern[str] dotenv.parser._newline = make_regex(r"(\r\n|\n|\r)") protected
Definition at line 11 of file parser.py.
_rest_of_line
Pattern[str] dotenv.parser._rest_of_line = make_regex(r"[^\r\n]*(?:\r|\n|\r\n)?") protected
Definition at line 23 of file parser.py.
_single_quote_escapes
Pattern[str] dotenv.parser._single_quote_escapes = make_regex(r"\\[\\']") protected
Definition at line 25 of file parser.py.
_single_quoted_key
Pattern[str] dotenv.parser._single_quoted_key = make_regex(r"'([^']+)'") protected
Definition at line 15 of file parser.py.
_single_quoted_value
Pattern[str] dotenv.parser._single_quoted_value = make_regex(r"'((?:\\'|[^'])*)'") protected
Definition at line 18 of file parser.py.
_unquoted_key
Pattern[str] dotenv.parser._unquoted_key = make_regex(r"([^=\#\s]+)") protected
Definition at line 16 of file parser.py.
_unquoted_value
Pattern[str] dotenv.parser._unquoted_value = make_regex(r"([^\r\n]*)") protected
Definition at line 20 of file parser.py.
_whitespace
Pattern[str] dotenv.parser._whitespace = make_regex(r"[^\S\r\n]*") protected
Definition at line 13 of file parser.py.