Read&Watch: isort.literal Namespace Reference
isort.literal Namespace Reference
Classes
class ISortPrettyPrinter
Functions
str assignments (str code)
str assignment (str code, str sort_type, str extension, Config config=DEFAULT_CONFIG)
Callable[[Callable[[Any, ISortPrettyPrinter], str]], Callable[[Any, ISortPrettyPrinter], str]] register_type (str name, type kind)
str _dict (Dict[Any, Any] value, ISortPrettyPrinter printer)
str _list (List[Any] value, ISortPrettyPrinter printer)
str _unique_list (List[Any] value, ISortPrettyPrinter printer)
str _set (Set[Any] value, ISortPrettyPrinter printer)
str _tuple (Tuple[Any,...] value, ISortPrettyPrinter printer)
str _unique_tuple (Tuple[Any,...] value, ISortPrettyPrinter printer)
Function Documentation
_dict()
str isort.literal._dict (Dict[Any, Any] value, ISortPrettyPrinter printer) protected
Definition at line 88 of file literal.py.
def _dict(value: Dict[Any, Any], printer: ISortPrettyPrinter) -> str:
    return printer.pformat(dict(sorted(value.items(), key=lambda item: item[1])))
@register_type("list", list)
_list()
str isort.literal._list (List[Any] value, ISortPrettyPrinter printer) protected
Definition at line 93 of file literal.py.
def _list(value: List[Any], printer: ISortPrettyPrinter) -> str:
    return printer.pformat(sorted(value))
@register_type("unique-list", list)
_set()
str isort.literal._set (Set[Any] value, ISortPrettyPrinter printer) protected
Definition at line 103 of file literal.py.
def _set(value: Set[Any], printer: ISortPrettyPrinter) -> str:
    return "{" + printer.pformat(tuple(sorted(value)))[1:-1] + "}"
@register_type("tuple", tuple)
_tuple()
str isort.literal._tuple (Tuple[Any, ...] value, ISortPrettyPrinter printer) protected
Definition at line 108 of file literal.py.
def _tuple(value: Tuple[Any, ...], printer: ISortPrettyPrinter) -> str:
    return printer.pformat(tuple(sorted(value)))
@register_type("unique-tuple", tuple)
_unique_list()
str isort.literal._unique_list (List[Any] value, ISortPrettyPrinter printer) protected
Definition at line 98 of file literal.py.
def _unique_list(value: List[Any], printer: ISortPrettyPrinter) -> str:
    return printer.pformat(list(sorted(set(value))))
@register_type("set", set)
_unique_tuple()
str isort.literal._unique_tuple (Tuple[Any, ...] value, ISortPrettyPrinter printer) protected
Definition at line 113 of file literal.py.
def _unique_tuple(value: Tuple[Any, ...], printer: ISortPrettyPrinter) -> str:
    return printer.pformat(tuple(sorted(set(value))))
assignment()
str isort.literal.assignment (str code, str sort_type, str extension, Config config = DEFAULT_CONFIG)
Sorts the literal present within the provided code against the provided sort type,
returning the sorted representation of the source code.
Definition at line 38 of file literal.py.
def assignment(code: str, sort_type: str, extension: str, config: Config = DEFAULT_CONFIG) -> str:
    """Sorts the literal present within the provided code against the provided sort type,
    returning the sorted representation of the source code.
    """
    if sort_type == "assignments":
        return assignments(code)
    if sort_type not in type_mapping:
        raise ValueError(
            "Trying to sort using an undefined sort_type. "
            f"Defined sort types are {', '.join(type_mapping.keys())}."
        )
    variable_name, literal = code.split("=")
    variable_name = variable_name.strip()
    literal = literal.lstrip()
    try:
        value = ast.literal_eval(literal)
    except Exception as error:
        raise LiteralParsingFailure(code, error)
    expected_type, sort_function = type_mapping[sort_type]
    if type(value) is not expected_type:
        raise LiteralSortTypeMismatch(type(value), expected_type)
    printer = ISortPrettyPrinter(config)
    sorted_value_code = f"{variable_name} = {sort_function(value, printer)}"
    if config.formatting_function:
        sorted_value_code = config.formatting_function(
            sorted_value_code, extension, config
        ).rstrip()
    sorted_value_code += code[len(code.rstrip()) :]
    return sorted_value_code
References assignments().
Referenced by isort.core.process().
assignments()
str isort.literal.assignments (str code)
Definition at line 23 of file literal.py.
def assignments(code: str) -> str:
    values = {}
    for line in code.splitlines(keepends=True):
        if not line.strip():
            continue
        if " = " not in line:
            raise AssignmentsFormatMismatch(code)
        variable_name, value = line.split(" = ", 1)
        values[variable_name] = value
    return "".join(
        f"{variable_name} = {values[variable_name]}" for variable_name in sorted(values.keys())
    )
Referenced by assignment().
register_type()
Callable[[Callable[[Any, ISortPrettyPrinter], str]], Callable[[Any, ISortPrettyPrinter], str]] isort.literal.register_type (str name, type kind)
Registers a new literal sort type.
Definition at line 73 of file literal.py.
) -> Callable[[Callable[[Any, ISortPrettyPrinter], str]], Callable[[Any, ISortPrettyPrinter], str]]:
    """Registers a new literal sort type."""
    def wrap(
        function: Callable[[Any, ISortPrettyPrinter], str]
    ) -> Callable[[Any, ISortPrettyPrinter], str]:
        type_mapping[name] = (kind, function)
        return function
    return wrap
@register_type("dict", dict)