Read&Watch: pylint.checkers.dataclass_checker Namespace Reference
pylint.checkers.dataclass_checker Namespace Reference
Classes
class DataclassChecker
Functions
bool _is_dataclasses_module (nodes.Module node)
bool _check_name_or_attrname_eq_to (nodes.Name|nodes.Attribute node, str check_with)
None register (PyLinter linter)
Detailed Description
Dataclass checkers for Python code.
Function Documentation
_check_name_or_attrname_eq_to()
bool pylint.checkers.dataclass_checker._check_name_or_attrname_eq_to (nodes.Name | nodes.Attribute node, str check_with) protected
Utility function to check either a Name/Attribute node's name/attrname with a
given string.
Definition at line 26 of file dataclass_checker.py.
) -> bool:
    """Utility function to check either a Name/Attribute node's name/attrname with a
    given string.
    """
    if isinstance(node, nodes.Name):
        return str(node.name) == check_with
    return str(node.attrname) == check_with
Referenced by pylint.checkers.dataclass_checker.DataclassChecker._check_invalid_field_call().
_is_dataclasses_module()
bool pylint.checkers.dataclass_checker._is_dataclasses_module (nodes.Module node) protected
Utility function to check if node is from dataclasses_module.
Definition at line 21 of file dataclass_checker.py.
def _is_dataclasses_module(node: nodes.Module) -> bool:
    """Utility function to check if node is from dataclasses_module."""
    return node.name in DATACLASS_MODULES
Referenced by pylint.checkers.dataclass_checker.DataclassChecker._check_invalid_field_call(), and pylint.checkers.dataclass_checker.DataclassChecker._check_invalid_field_call_within_call().
register()
None pylint.checkers.dataclass_checker.register (PyLinter linter)
Definition at line 128 of file dataclass_checker.py.
def register(linter: PyLinter) -> None:
    linter.register_checker(DataclassChecker(linter))