Read&Watch: django.template.defaultfilters Namespace Reference
django.template.defaultfilters Namespace Reference
Functions
stringfilter (func)
STRING DECORATOR #.
addslashes (value)
STRINGS #.
capfirst (value)
escapejs_filter (value)
json_script (value, element_id=None)
floatformat (text, arg=-1)
iriencode (value)
linenumbers (value, autoescape=True)
lower (value)
make_list (value)
slugify (value)
stringformat (value, arg)
title (value)
truncatechars (value, arg)
truncatechars_html (value, arg)
truncatewords (value, arg)
truncatewords_html (value, arg)
upper (value)
urlencode (value, safe=None)
urlize (value, autoescape=True)
urlizetrunc (value, limit, autoescape=True)
wordcount (value)
wordwrap (value, arg)
ljust (value, arg)
rjust (value, arg)
center (value, arg)
cut (value, arg)
escape_filter (value)
HTML STRINGS #.
escapeseq (value)
force_escape (value)
linebreaks_filter (value, autoescape=True)
linebreaksbr (value, autoescape=True)
safe (value)
safeseq (value)
striptags (value)
_property_resolver (arg)
LISTS #.
dictsort (value, arg)
dictsortreversed (value, arg)
first (value)
join (value, arg, autoescape=True)
last (value)
length (value)
random (value)
slice_filter (value, arg)
unordered_list (value, autoescape=True)
add (value, arg)
INTEGERS #.
get_digit (value, arg)
date (value, arg=None)
DATES #.
time (value, arg=None)
timesince_filter (value, arg=None)
timeuntil_filter (value, arg=None)
default (value, arg)
LOGIC #.
default_if_none (value, arg)
divisibleby (value, arg)
yesno (value, arg=None)
filesizeformat (bytes_)
MISC #.
pluralize (value, arg="s")
phone2numeric_filter (value)
pprint (value)
Variables
register = Library()
Detailed Description
Default variable filters.
Function Documentation
_property_resolver()
django.template.defaultfilters._property_resolver (arg) protected
LISTS #.
When arg is convertible to float, behave like operator.itemgetter(arg)
Otherwise, chain __getitem__() and getattr().
>>> _property_resolver(1)('abc')
'b'
>>> _property_resolver('1')('abc')
Traceback (most recent call last):
...
TypeError: string indices must be integers
>>> class Foo:
...     a = 42
...     b = 3.14
...     c = 'Hey!'
>>> _property_resolver('b')(Foo())
3.14
Definition at line 535 of file defaultfilters.py.
def _property_resolver(arg):
    """
    When arg is convertible to float, behave like operator.itemgetter(arg)
    Otherwise, chain __getitem__() and getattr().
    >>> _property_resolver(1)('abc')
    'b'
    >>> _property_resolver('1')('abc')
    Traceback (most recent call last):
    ...
    TypeError: string indices must be integers
    >>> class Foo:
    ...     a = 42
    ...     b = 3.14
    ...     c = 'Hey!'
    >>> _property_resolver('b')(Foo())
    3.14
    """
    try:
        float(arg)
    except ValueError:
        if VARIABLE_ATTRIBUTE_SEPARATOR + "_" in arg or arg[0] == "_":
            raise AttributeError("Access to private variables is forbidden.")
        parts = arg.split(VARIABLE_ATTRIBUTE_SEPARATOR)
        def resolve(value):
            for part in parts:
                try:
                    value = value[part]
                except (AttributeError, IndexError, KeyError, TypeError, ValueError):
                    value = getattr(value, part)
            return value
        return resolve
    else:
        return itemgetter(arg)
@register.filter(is_safe=False)
Referenced by dictsort(), and dictsortreversed().
add()
django.template.defaultfilters.add (value, arg)
INTEGERS #.
Add the arg to the value.
Definition at line 741 of file defaultfilters.py.
def add(value, arg):
    """Add the arg to the value."""
    try:
        return int(value) + int(arg)
    except (ValueError, TypeError):
        try:
            return value + arg
        except Exception:
            return ""
@register.filter(is_safe=False)
addslashes()
django.template.defaultfilters.addslashes (value)
STRINGS #.
Add slashes before quotes. Useful for escaping strings in CSV, for
example. Less useful for escaping JavaScript; use the ``escapejs``
filter instead.
Definition at line 62 of file defaultfilters.py.
def addslashes(value):
    """
    Add slashes before quotes. Useful for escaping strings in CSV, for
    example. Less useful for escaping JavaScript; use the ``escapejs``
    filter instead.
    """
    return value.replace("\\", "\\\\").replace('"', '\\"').replace("'", "\\'")
@register.filter(is_safe=True)
@stringfilter
capfirst()
django.template.defaultfilters.capfirst (value)
Capitalize the first character of the value.
Definition at line 73 of file defaultfilters.py.
def capfirst(value):
    """Capitalize the first character of the value."""
    return value and value[0].upper() + value[1:]
@register.filter("escapejs")
@stringfilter
References upper().
center()
django.template.defaultfilters.center (value, arg)
Center the value in a field of a given width.
Definition at line 431 of file defaultfilters.py.
def center(value, arg):
    """Center the value in a field of a given width."""
    return value.center(int(arg))
@register.filter
@stringfilter
cut()
django.template.defaultfilters.cut (value, arg)
Remove all values of arg from the given string.
Definition at line 438 of file defaultfilters.py.
def cut(value, arg):
    """Remove all values of arg from the given string."""
    safe = isinstance(value, SafeData)
    value = value.replace(arg, "")
    if safe and arg != ";":
        return mark_safe(value)
    return value
date()
django.template.defaultfilters.date (value, arg = None)
DATES #.
Format a date according to the given format.
Definition at line 779 of file defaultfilters.py.
def date(value, arg=None):
    """Format a date according to the given format."""
    if value in (None, ""):
        return ""
    try:
        return formats.date_format(value, arg)
    except AttributeError:
        try:
            return format(value, arg)
        except AttributeError:
            return ""
@register.filter(expects_localtime=True, is_safe=False)
default()
django.template.defaultfilters.default (value, arg)
LOGIC #.
If value is unavailable, use given default.
Definition at line 836 of file defaultfilters.py.
def default(value, arg):
    """If value is unavailable, use given default."""
    return value or arg
@register.filter(is_safe=False)
default_if_none()
django.template.defaultfilters.default_if_none (value, arg)
If value is None, use given default.
Definition at line 842 of file defaultfilters.py.
def default_if_none(value, arg):
    """If value is None, use given default."""
    if value is None:
        return arg
    return value
@register.filter(is_safe=False)
dictsort()
django.template.defaultfilters.dictsort (value, arg)
Given a list of dicts, return that list sorted by the property given in
the argument.
Definition at line 574 of file defaultfilters.py.
def dictsort(value, arg):
    """
    Given a list of dicts, return that list sorted by the property given in
    the argument.
    """
    try:
        return sorted(value, key=_property_resolver(arg))
    except (AttributeError, TypeError):
        return ""
@register.filter(is_safe=False)
References _property_resolver().
dictsortreversed()
django.template.defaultfilters.dictsortreversed (value, arg)
Given a list of dicts, return that list sorted in reverse order by the
property given in the argument.
Definition at line 586 of file defaultfilters.py.
def dictsortreversed(value, arg):
    """
    Given a list of dicts, return that list sorted in reverse order by the
    property given in the argument.
    """
    try:
        return sorted(value, key=_property_resolver(arg), reverse=True)
    except (AttributeError, TypeError):
        return ""
@register.filter(is_safe=False)
References _property_resolver().
divisibleby()
django.template.defaultfilters.divisibleby (value, arg)
Return True if the value is divisible by the argument.
Definition at line 850 of file defaultfilters.py.
def divisibleby(value, arg):
    """Return True if the value is divisible by the argument."""
    return int(value) % int(arg) == 0
@register.filter(is_safe=False)
escape_filter()
django.template.defaultfilters.escape_filter (value)
HTML STRINGS #.
Mark the value as a string that should be auto-escaped.
Definition at line 454 of file defaultfilters.py.
def escape_filter(value):
    """Mark the value as a string that should be auto-escaped."""
    return conditional_escape(value)
@register.filter(is_safe=True)
escapejs_filter()
django.template.defaultfilters.escapejs_filter (value)
Hex encode characters for use in JavaScript strings.
Definition at line 80 of file defaultfilters.py.
def escapejs_filter(value):
    """Hex encode characters for use in JavaScript strings."""
    return escapejs(value)
@register.filter(is_safe=True)
escapeseq()
django.template.defaultfilters.escapeseq (value)
An "escape" filter for sequences. Mark each element in the sequence,
individually, as a string that should be auto-escaped. Return a list with
the results.
Definition at line 460 of file defaultfilters.py.
def escapeseq(value):
    """
    An "escape" filter for sequences. Mark each element in the sequence,
    individually, as a string that should be auto-escaped. Return a list with
    the results.
    """
    return [conditional_escape(obj) for obj in value]
@register.filter(is_safe=True)
@stringfilter
filesizeformat()
django.template.defaultfilters.filesizeformat (bytes_)
MISC #.
Format the value like a 'human-readable' file size (i.e. 13 KB, 4.1 MB,
102 bytes, etc.).
Definition at line 895 of file defaultfilters.py.
def filesizeformat(bytes_):
    """
    Format the value like a 'human-readable' file size (i.e. 13 KB, 4.1 MB,
    102 bytes, etc.).
    """
    try:
        bytes_ = int(bytes_)
    except (TypeError, ValueError, UnicodeDecodeError):
        value = ngettext("%(size)d byte", "%(size)d bytes", 0) % {"size": 0}
        return avoid_wrapping(value)
    def filesize_number_format(value):
        return formats.number_format(round(value, 1), 1)
    KB = 1 << 10
    MB = 1 << 20
    GB = 1 << 30
    TB = 1 << 40
    PB = 1 << 50
    negative = bytes_ < 0
    if negative:
        bytes_ = -bytes_  # Allow formatting of negative numbers.
    if bytes_ < KB:
        value = ngettext("%(size)d byte", "%(size)d bytes", bytes_) % {"size": bytes_}
    elif bytes_ < MB:
        value = gettext("%s KB") % filesize_number_format(bytes_ / KB)
    elif bytes_ < GB:
        value = gettext("%s MB") % filesize_number_format(bytes_ / MB)
    elif bytes_ < TB:
        value = gettext("%s GB") % filesize_number_format(bytes_ / GB)
    elif bytes_ < PB:
        value = gettext("%s TB") % filesize_number_format(bytes_ / TB)
    else:
        value = gettext("%s PB") % filesize_number_format(bytes_ / PB)
    if negative:
        value = "-%s" % value
    return avoid_wrapping(value)
@register.filter(is_safe=False)
first()
django.template.defaultfilters.first (value)
Return the first item in a list.
Definition at line 598 of file defaultfilters.py.
def first(value):
    """Return the first item in a list."""
    try:
        return value[0]
    except IndexError:
        return ""
@register.filter(is_safe=True, needs_autoescape=True)
floatformat()
django.template.defaultfilters.floatformat (text, arg = -1)
Display a float to a specified number of decimal places.
If called without an argument, display the floating point number with one
decimal place -- but only if there's a decimal place to be displayed:
* num1 = 34.23234
* num2 = 34.00000
* num3 = 34.26000
* {{ num1|floatformat }} displays "34.2"
* {{ num2|floatformat }} displays "34"
* {{ num3|floatformat }} displays "34.3"
If arg is positive, always display exactly arg number of decimal places:
* {{ num1|floatformat:3 }} displays "34.232"
* {{ num2|floatformat:3 }} displays "34.000"
* {{ num3|floatformat:3 }} displays "34.260"
If arg is negative, display arg number of decimal places -- but only if
there are places to be displayed:
* {{ num1|floatformat:"-3" }} displays "34.232"
* {{ num2|floatformat:"-3" }} displays "34"
* {{ num3|floatformat:"-3" }} displays "34.260"
If arg has the 'g' suffix, force the result to be grouped by the
THOUSAND_SEPARATOR for the active locale. When the active locale is
en (English):
* {{ 6666.6666|floatformat:"2g" }} displays "6,666.67"
* {{ 10000|floatformat:"g" }} displays "10,000"
If arg has the 'u' suffix, force the result to be unlocalized. When the
active locale is pl (Polish):
* {{ 66666.6666|floatformat:"2" }} displays "66666,67"
* {{ 66666.6666|floatformat:"2u" }} displays "66666.67"
If the input float is infinity or NaN, display the string representation
of that value.
Definition at line 95 of file defaultfilters.py.
def floatformat(text, arg=-1):
    """
    Display a float to a specified number of decimal places.
    If called without an argument, display the floating point number with one
    decimal place -- but only if there's a decimal place to be displayed:
    * num1 = 34.23234
    * num2 = 34.00000
    * num3 = 34.26000
    * {{ num1|floatformat }} displays "34.2"
    * {{ num2|floatformat }} displays "34"
    * {{ num3|floatformat }} displays "34.3"
    If arg is positive, always display exactly arg number of decimal places:
    * {{ num1|floatformat:3 }} displays "34.232"
    * {{ num2|floatformat:3 }} displays "34.000"
    * {{ num3|floatformat:3 }} displays "34.260"
    If arg is negative, display arg number of decimal places -- but only if
    there are places to be displayed:
    * {{ num1|floatformat:"-3" }} displays "34.232"
    * {{ num2|floatformat:"-3" }} displays "34"
    * {{ num3|floatformat:"-3" }} displays "34.260"
    If arg has the 'g' suffix, force the result to be grouped by the
    THOUSAND_SEPARATOR for the active locale. When the active locale is
    en (English):
    * {{ 6666.6666|floatformat:"2g" }} displays "6,666.67"
    * {{ 10000|floatformat:"g" }} displays "10,000"
    If arg has the 'u' suffix, force the result to be unlocalized. When the
    active locale is pl (Polish):
    * {{ 66666.6666|floatformat:"2" }} displays "66666,67"
    * {{ 66666.6666|floatformat:"2u" }} displays "66666.67"
    If the input float is infinity or NaN, display the string representation
    of that value.
    """
    force_grouping = False
    use_l10n = True
    if isinstance(arg, str):
        last_char = arg[-1]
        if arg[-2:] in {"gu", "ug"}:
            force_grouping = True
            use_l10n = False
            arg = arg[:-2] or -1
        elif last_char == "g":
            force_grouping = True
            arg = arg[:-1] or -1
        elif last_char == "u":
            use_l10n = False
            arg = arg[:-1] or -1
    try:
        input_val = str(text)
        d = Decimal(input_val)
    except InvalidOperation:
        try:
            d = Decimal(str(float(text)))
        except (ValueError, InvalidOperation, TypeError):
            return ""
    try:
        p = int(arg)
    except ValueError:
        return input_val
    _, digits, exponent = d.as_tuple()
    try:
        number_of_digits_and_exponent_sum = len(digits) + abs(exponent)
    except TypeError:
        # Exponent values can be "F", "n", "N".
        number_of_digits_and_exponent_sum = 0
    # Values with more than 200 digits, or with a large exponent, are returned "as is"
    # to avoid high memory consumption and potential denial-of-service attacks.
    # The cut-off of 200 is consistent with django.utils.numberformat.floatformat().
    if number_of_digits_and_exponent_sum > 200:
        return input_val
    try:
        m = int(d) - d
    except (ValueError, OverflowError, InvalidOperation):
        return input_val
    if not m and p <= 0:
        return mark_safe(
            formats.number_format(
                "%d" % (int(d)),
                0,
                use_l10n=use_l10n,
                force_grouping=force_grouping,
            )
        )
    exp = Decimal(1).scaleb(-abs(p))
    # Set the precision high enough to avoid an exception (#15789).
    tupl = d.as_tuple()
    units = len(tupl[1])
    units += -tupl[2] if m else tupl[2]
    prec = abs(p) + units + 1
    prec = max(getcontext().prec, prec)
    # Avoid conversion to scientific notation by accessing `sign`, `digits`,
    # and `exponent` from Decimal.as_tuple() directly.
    rounded_d = d.quantize(exp, ROUND_HALF_UP, Context(prec=prec))
    sign, digits, exponent = rounded_d.as_tuple()
    digits = [str(digit) for digit in reversed(digits)]
    while len(digits) <= abs(exponent):
        digits.append("0")
    digits.insert(-exponent, ".")
    if sign and rounded_d:
        digits.append("-")
    number = "".join(reversed(digits))
    return mark_safe(
        formats.number_format(
            number,
            abs(p),
            use_l10n=use_l10n,
            force_grouping=force_grouping,
        )
    )
@register.filter(is_safe=True)
@stringfilter
References join().
force_escape()
django.template.defaultfilters.force_escape (value)
Escape a string's HTML. Return a new string containing the escaped
characters (as opposed to "escape", which marks the content for later
possible escaping).
Definition at line 471 of file defaultfilters.py.
def force_escape(value):
    """
    Escape a string's HTML. Return a new string containing the escaped
    characters (as opposed to "escape", which marks the content for later
    possible escaping).
    """
    return escape(value)
@register.filter("linebreaks", is_safe=True, needs_autoescape=True)
@stringfilter
get_digit()
django.template.defaultfilters.get_digit (value, arg)
Given a whole number, return the requested digit of it, where 1 is the
right-most digit, 2 is the second-right-most digit, etc. Return the
original value for invalid input (if input or argument is not an integer,
or if argument is less than 1). Otherwise, output is always an integer.
Definition at line 753 of file defaultfilters.py.
def get_digit(value, arg):
    """
    Given a whole number, return the requested digit of it, where 1 is the
    right-most digit, 2 is the second-right-most digit, etc. Return the
    original value for invalid input (if input or argument is not an integer,
    or if argument is less than 1). Otherwise, output is always an integer.
    """
    try:
        arg = int(arg)
        value = int(value)
    except ValueError:
        return value  # Fail silently for an invalid argument
    if arg < 1:
        return value
    try:
        return int(str(value)[-arg])
    except IndexError:
        return 0
iriencode()
django.template.defaultfilters.iriencode (value)
Escape an IRI value for use in a URL.
Definition at line 224 of file defaultfilters.py.
def iriencode(value):
    """Escape an IRI value for use in a URL."""
    return iri_to_uri(value)
@register.filter(is_safe=True, needs_autoescape=True)
@stringfilter
join()
django.template.defaultfilters.join (value, arg, autoescape = True)
Join a list with a string, like Python's ``str.join(list)``.
Definition at line 607 of file defaultfilters.py.
def join(value, arg, autoescape=True):
    """Join a list with a string, like Python's ``str.join(list)``."""
    try:
        if autoescape:
            data = conditional_escape(arg).join([conditional_escape(v) for v in value])
        else:
            data = arg.join(value)
    except TypeError:  # Fail silently if arg isn't iterable.
        return value
    return mark_safe(data)
@register.filter(is_safe=True)
References join().
Referenced by floatformat(), join(), linenumbers(), and unordered_list().
json_script()
django.template.defaultfilters.json_script (value, element_id = None)
Output value JSON-encoded, wrapped in a <script type="application/json">
tag (with an optional id).
Definition at line 86 of file defaultfilters.py.
def json_script(value, element_id=None):
    """
    Output value JSON-encoded, wrapped in a <script type="application/json">
    tag (with an optional id).
    """
    return _json_script(value, element_id)
@register.filter(is_safe=True)
last()
django.template.defaultfilters.last (value)
Return the last item in a list.
Definition at line 620 of file defaultfilters.py.
def last(value):
    """Return the last item in a list."""
    try:
        return value[-1]
    except IndexError:
        return ""
@register.filter(is_safe=False)
length()
django.template.defaultfilters.length (value)
Return the length of the value - useful for lists.
Definition at line 629 of file defaultfilters.py.
def length(value):
    """Return the length of the value - useful for lists."""
    try:
        return len(value)
    except (ValueError, TypeError):
        return 0
@register.filter(is_safe=True)
linebreaks_filter()
django.template.defaultfilters.linebreaks_filter (value, autoescape = True)
Replace line breaks in plain text with appropriate HTML; a single
newline becomes an HTML line break (``<br>``) and a new line
followed by a blank line becomes a paragraph break (``</p>``).
Definition at line 482 of file defaultfilters.py.
def linebreaks_filter(value, autoescape=True):
    """
    Replace line breaks in plain text with appropriate HTML; a single
    newline becomes an HTML line break (``<br>``) and a new line
    followed by a blank line becomes a paragraph break (``</p>``).
    """
    autoescape = autoescape and not isinstance(value, SafeData)
    return mark_safe(linebreaks(value, autoescape))
@register.filter(is_safe=True, needs_autoescape=True)
@stringfilter
linebreaksbr()
django.template.defaultfilters.linebreaksbr (value, autoescape = True)
Convert all newlines in a piece of plain text to HTML line breaks
(``<br>``).
Definition at line 494 of file defaultfilters.py.
def linebreaksbr(value, autoescape=True):
    """
    Convert all newlines in a piece of plain text to HTML line breaks
    (``<br>``).
    """
    autoescape = autoescape and not isinstance(value, SafeData)
    value = normalize_newlines(value)
    if autoescape:
        value = escape(value)
    return mark_safe(value.replace("\n", "<br>"))
@register.filter(is_safe=True)
@stringfilter
linenumbers()
django.template.defaultfilters.linenumbers (value, autoescape = True)
Display text with line numbers.
Definition at line 231 of file defaultfilters.py.
def linenumbers(value, autoescape=True):
    """Display text with line numbers."""
    lines = value.split("\n")
    # Find the maximum width of the line count, for use with zero padding
    # string format command
    width = str(len(str(len(lines))))
    if not autoescape or isinstance(value, SafeData):
        for i, line in enumerate(lines):
            lines[i] = ("%0" + width + "d. %s") % (i + 1, line)
    else:
        for i, line in enumerate(lines):
            lines[i] = ("%0" + width + "d. %s") % (i + 1, escape(line))
    return mark_safe("\n".join(lines))
@register.filter(is_safe=True)
@stringfilter
References join().
ljust()
django.template.defaultfilters.ljust (value, arg)
Left-align the value in a field of a given width.
Definition at line 417 of file defaultfilters.py.
def ljust(value, arg):
    """Left-align the value in a field of a given width."""
    return value.ljust(int(arg))
@register.filter(is_safe=True)
@stringfilter
lower()
django.template.defaultfilters.lower (value)
Convert a string into all lowercase.
Definition at line 248 of file defaultfilters.py.
def lower(value):
    """Convert a string into all lowercase."""
    return value.lower()
@register.filter(is_safe=False)
@stringfilter
Referenced by title().
make_list()
django.template.defaultfilters.make_list (value)
Return the value turned into a list.
For an integer, it's a list of digits.
For a string, it's a list of characters.
Definition at line 255 of file defaultfilters.py.
def make_list(value):
    """
    Return the value turned into a list.
    For an integer, it's a list of digits.
    For a string, it's a list of characters.
    """
    return list(value)
@register.filter(is_safe=True)
@stringfilter
phone2numeric_filter()
django.template.defaultfilters.phone2numeric_filter (value)
Take a phone number and converts it in to its numerical equivalent.
Definition at line 980 of file defaultfilters.py.
def phone2numeric_filter(value):
    """Take a phone number and converts it in to its numerical equivalent."""
    return phone2numeric(value)
@register.filter(is_safe=True)
pluralize()
django.template.defaultfilters.pluralize (value, arg = "s")
Return a plural suffix if the value is not 1, '1', or an object of
length 1. By default, use 's' as the suffix:
* If value is 0, vote{{ value|pluralize }} display "votes".
* If value is 1, vote{{ value|pluralize }} display "vote".
* If value is 2, vote{{ value|pluralize }} display "votes".
If an argument is provided, use that string instead:
* If value is 0, class{{ value|pluralize:"es" }} display "classes".
* If value is 1, class{{ value|pluralize:"es" }} display "class".
* If value is 2, class{{ value|pluralize:"es" }} display "classes".
If the provided argument contains a comma, use the text before the comma
for the singular case and the text after the comma for the plural case:
* If value is 0, cand{{ value|pluralize:"y,ies" }} display "candies".
* If value is 1, cand{{ value|pluralize:"y,ies" }} display "candy".
* If value is 2, cand{{ value|pluralize:"y,ies" }} display "candies".
Definition at line 938 of file defaultfilters.py.
def pluralize(value, arg="s"):
    """
    Return a plural suffix if the value is not 1, '1', or an object of
    length 1. By default, use 's' as the suffix:
    * If value is 0, vote{{ value|pluralize }} display "votes".
    * If value is 1, vote{{ value|pluralize }} display "vote".
    * If value is 2, vote{{ value|pluralize }} display "votes".
    If an argument is provided, use that string instead:
    * If value is 0, class{{ value|pluralize:"es" }} display "classes".
    * If value is 1, class{{ value|pluralize:"es" }} display "class".
    * If value is 2, class{{ value|pluralize:"es" }} display "classes".
    If the provided argument contains a comma, use the text before the comma
    for the singular case and the text after the comma for the plural case:
    * If value is 0, cand{{ value|pluralize:"y,ies" }} display "candies".
    * If value is 1, cand{{ value|pluralize:"y,ies" }} display "candy".
    * If value is 2, cand{{ value|pluralize:"y,ies" }} display "candies".
    """
    if "," not in arg:
        arg = "," + arg
    bits = arg.split(",")
    if len(bits) > 2:
        return ""
    singular_suffix, plural_suffix = bits[:2]
    try:
        return singular_suffix if float(value) == 1 else plural_suffix
    except ValueError:  # Invalid string that's not a number.
        pass
    except TypeError:  # Value isn't a string or a number; maybe it's a list?
        try:
            return singular_suffix if len(value) == 1 else plural_suffix
        except TypeError:  # len() of unsized object.
            pass
    return ""
@register.filter("phone2numeric", is_safe=True)
pprint()
django.template.defaultfilters.pprint (value)
A wrapper around pprint.pprint -- for debugging, really.
Definition at line 986 of file defaultfilters.py.
def pprint(value):
    """A wrapper around pprint.pprint -- for debugging, really."""
    try:
        return pformat(value)
    except Exception as e:
        return "Error in formatting: %s: %s" % (e.__class__.__name__, e)
random()
django.template.defaultfilters.random (value)
Return a random item from the list.
Definition at line 638 of file defaultfilters.py.
def random(value):
    """Return a random item from the list."""
    try:
        return random_module.choice(value)
    except IndexError:
        return ""
@register.filter("slice", is_safe=True)
rjust()
django.template.defaultfilters.rjust (value, arg)
Right-align the value in a field of a given width.
Definition at line 424 of file defaultfilters.py.
def rjust(value, arg):
    """Right-align the value in a field of a given width."""
    return value.rjust(int(arg))
@register.filter(is_safe=True)
@stringfilter
safe()
django.template.defaultfilters.safe (value)
Mark the value as a string that should not be auto-escaped.
Definition at line 508 of file defaultfilters.py.
def safe(value):
    """Mark the value as a string that should not be auto-escaped."""
    return mark_safe(value)
@register.filter(is_safe=True)
safeseq()
django.template.defaultfilters.safeseq (value)
A "safe" filter for sequences. Mark each element in the sequence,
individually, as safe, after converting them to strings. Return a list
with the results.
Definition at line 514 of file defaultfilters.py.
def safeseq(value):
    """
    A "safe" filter for sequences. Mark each element in the sequence,
    individually, as safe, after converting them to strings. Return a list
    with the results.
    """
    return [mark_safe(obj) for obj in value]
@register.filter(is_safe=True)
@stringfilter
slice_filter()
django.template.defaultfilters.slice_filter (value, arg)
Return a slice of the list using the same syntax as Python's list slicing.
Definition at line 647 of file defaultfilters.py.
def slice_filter(value, arg):
    """
    Return a slice of the list using the same syntax as Python's list slicing.
    """
    try:
        bits = []
        for x in str(arg).split(":"):
            if not x:
                bits.append(None)
            else:
                bits.append(int(x))
        return value[slice(*bits)]
    except (ValueError, TypeError, KeyError):
        return value  # Fail silently.
@register.filter(is_safe=True, needs_autoescape=True)
slugify()
django.template.defaultfilters.slugify (value)
Convert to ASCII. Convert spaces to hyphens. Remove characters that aren't
alphanumerics, underscores, or hyphens. Convert to lowercase. Also strip
leading and trailing whitespace.
Definition at line 267 of file defaultfilters.py.
def slugify(value):
    """
    Convert to ASCII. Convert spaces to hyphens. Remove characters that aren't
    alphanumerics, underscores, or hyphens. Convert to lowercase. Also strip
    leading and trailing whitespace.
    """
    return _slugify(value)
@register.filter(is_safe=True)
stringfilter()
django.template.defaultfilters.stringfilter (func)
STRING DECORATOR #.
Decorator for filters which should only receive strings. The object
passed as the first positional argument will be converted to a string.
Definition at line 38 of file defaultfilters.py.
def stringfilter(func):
    """
    Decorator for filters which should only receive strings. The object
    passed as the first positional argument will be converted to a string.
    """
    @wraps(func)
    def _dec(first, *args, **kwargs):
        first = str(first)
        result = func(first, *args, **kwargs)
        if isinstance(first, SafeData) and getattr(unwrap(func), "is_safe", False):
            result = mark_safe(result)
        return result
    return _dec
stringformat()
django.template.defaultfilters.stringformat (value, arg)
Format the variable according to the arg, a string formatting specifier.
This specifier uses Python string formatting syntax, with the exception
that the leading "%" is dropped.
See https://docs.python.org/library/stdtypes.html#printf-style-string-formatting
for documentation of Python string formatting.
Definition at line 277 of file defaultfilters.py.
def stringformat(value, arg):
    """
    Format the variable according to the arg, a string formatting specifier.
    This specifier uses Python string formatting syntax, with the exception
    that the leading "%" is dropped.
    See https://docs.python.org/library/stdtypes.html#printf-style-string-formatting
    for documentation of Python string formatting.
    """
    if isinstance(value, tuple):
        value = str(value)
    try:
        return ("%" + str(arg)) % value
    except (ValueError, TypeError):
        return ""
@register.filter(is_safe=True)
@stringfilter
striptags()
django.template.defaultfilters.striptags (value)
Strip all [X]HTML tags.
Definition at line 525 of file defaultfilters.py.
def striptags(value):
    """Strip all [X]HTML tags."""
    return strip_tags(value)
time()
django.template.defaultfilters.time (value, arg = None)
Format a time according to the given format.
Definition at line 793 of file defaultfilters.py.
def time(value, arg=None):
    """Format a time according to the given format."""
    if value in (None, ""):
        return ""
    try:
        return formats.time_format(value, arg)
    except (AttributeError, TypeError):
        try:
            return time_format(value, arg)
        except (AttributeError, TypeError):
            return ""
@register.filter("timesince", is_safe=False)
timesince_filter()
django.template.defaultfilters.timesince_filter (value, arg = None)
Format a date as the time since that date (i.e. "4 days, 6 hours").
Definition at line 807 of file defaultfilters.py.
def timesince_filter(value, arg=None):
    """Format a date as the time since that date (i.e. "4 days, 6 hours")."""
    if not value:
        return ""
    try:
        if arg:
            return timesince(value, arg)
        return timesince(value)
    except (ValueError, TypeError):
        return ""
@register.filter("timeuntil", is_safe=False)
timeuntil_filter()
django.template.defaultfilters.timeuntil_filter (value, arg = None)
Format a date as the time until that date (i.e. "4 days, 6 hours").
Definition at line 820 of file defaultfilters.py.
def timeuntil_filter(value, arg=None):
    """Format a date as the time until that date (i.e. "4 days, 6 hours")."""
    if not value:
        return ""
    try:
        return timeuntil(value, arg)
    except (ValueError, TypeError):
        return ""
title()
django.template.defaultfilters.title (value)
Convert a string into titlecase.
Definition at line 297 of file defaultfilters.py.
def title(value):
    """Convert a string into titlecase."""
    t = re.sub("([a-z])'([A-Z])", lambda m: m[0].lower(), value.title())
    return re.sub(r"\d([A-Z])", lambda m: m[0].lower(), t)
@register.filter(is_safe=True)
@stringfilter
References lower().
truncatechars()
django.template.defaultfilters.truncatechars (value, arg)
Truncate a string after `arg` number of characters.
Definition at line 305 of file defaultfilters.py.
def truncatechars(value, arg):
    """Truncate a string after `arg` number of characters."""
    try:
        length = int(arg)
    except ValueError:  # Invalid literal for int().
        return value  # Fail silently.
    return Truncator(value).chars(length)
@register.filter(is_safe=True)
@stringfilter
truncatechars_html()
django.template.defaultfilters.truncatechars_html (value, arg)
Truncate HTML after `arg` number of chars.
Preserve newlines in the HTML.
Definition at line 316 of file defaultfilters.py.
def truncatechars_html(value, arg):
    """
    Truncate HTML after `arg` number of chars.
    Preserve newlines in the HTML.
    """
    try:
        length = int(arg)
    except ValueError:  # invalid literal for int()
        return value  # Fail silently.
    return Truncator(value).chars(length, html=True)
@register.filter(is_safe=True)
@stringfilter
truncatewords()
django.template.defaultfilters.truncatewords (value, arg)
Truncate a string after `arg` number of words.
Remove newlines within the string.
Definition at line 330 of file defaultfilters.py.
def truncatewords(value, arg):
    """
    Truncate a string after `arg` number of words.
    Remove newlines within the string.
    """
    try:
        length = int(arg)
    except ValueError:  # Invalid literal for int().
        return value  # Fail silently.
    return Truncator(value).words(length, truncate=" ")
@register.filter(is_safe=True)
@stringfilter
truncatewords_html()
django.template.defaultfilters.truncatewords_html (value, arg)
Truncate HTML after `arg` number of words.
Preserve newlines in the HTML.
Definition at line 344 of file defaultfilters.py.
def truncatewords_html(value, arg):
    """
    Truncate HTML after `arg` number of words.
    Preserve newlines in the HTML.
    """
    try:
        length = int(arg)
    except ValueError:  # invalid literal for int()
        return value  # Fail silently.
    return Truncator(value).words(length, html=True, truncate=" ")
@register.filter(is_safe=False)
@stringfilter
unordered_list()
django.template.defaultfilters.unordered_list (value, autoescape = True)
Recursively take a self-nested list and return an HTML unordered list --
WITHOUT opening and closing <ul> tags.
Assume the list is in the proper format. For example, if ``var`` contains:
``['States', ['Kansas', ['Lawrence', 'Topeka'], 'Illinois']]``, then
``{{ var|unordered_list }}`` returns::
    <li>States
    <ul>
            <li>Kansas
            <ul>
                    <li>Lawrence</li>
                    <li>Topeka</li>
            </ul>
            </li>
            <li>Illinois</li>
    </ul>
    </li>
Definition at line 665 of file defaultfilters.py.
def unordered_list(value, autoescape=True):
    """
    Recursively take a self-nested list and return an HTML unordered list --
    WITHOUT opening and closing <ul> tags.
    Assume the list is in the proper format. For example, if ``var`` contains:
    ``['States', ['Kansas', ['Lawrence', 'Topeka'], 'Illinois']]``, then
    ``{{ var|unordered_list }}`` returns::
        <li>States
        <ul>
                <li>Kansas
                <ul>
                        <li>Lawrence</li>
                        <li>Topeka</li>
                </ul>
                </li>
                <li>Illinois</li>
        </ul>
        </li>
    """
    if autoescape:
        escaper = conditional_escape
    else:
        def escaper(x):
            return x
    def walk_items(item_list):
        item_iterator = iter(item_list)
        try:
            item = next(item_iterator)
            while True:
                try:
                    next_item = next(item_iterator)
                except StopIteration:
                    yield item, None
                    break
                if isinstance(next_item, (list, tuple, types.GeneratorType)):
                    try:
                        iter(next_item)
                    except TypeError:
                        pass
                    else:
                        yield item, next_item
                        item = next(item_iterator)
                        continue
                yield item, None
                item = next_item
        except StopIteration:
            pass
    def list_formatter(item_list, tabs=1):
        indent = "\t" * tabs
        output = []
        for item, children in walk_items(item_list):
            sublist = ""
            if children:
                sublist = "\n%s<ul>\n%s\n%s</ul>\n%s" % (
                    indent,
                    list_formatter(children, tabs + 1),
                    indent,
                    indent,
                )
            output.append("%s<li>%s%s</li>" % (indent, escaper(item), sublist))
        return "\n".join(output)
    return mark_safe(list_formatter(value))
References join().
upper()
django.template.defaultfilters.upper (value)
Convert a string into all uppercase.
Definition at line 358 of file defaultfilters.py.
def upper(value):
    """Convert a string into all uppercase."""
    return value.upper()
@register.filter(is_safe=False)
@stringfilter
Referenced by capfirst().
urlencode()
django.template.defaultfilters.urlencode (value, safe = None)
Escape a value for use in a URL.
The ``safe`` parameter determines the characters which should not be
escaped by Python's quote() function. If not provided, use the default safe
characters (but an empty string can be provided when *all* characters
should be escaped).
Definition at line 365 of file defaultfilters.py.
def urlencode(value, safe=None):
    """
    Escape a value for use in a URL.
    The ``safe`` parameter determines the characters which should not be
    escaped by Python's quote() function. If not provided, use the default safe
    characters (but an empty string can be provided when *all* characters
    should be escaped).
    """
    kwargs = {}
    if safe is not None:
        kwargs["safe"] = safe
    return quote(value, **kwargs)
@register.filter(is_safe=True, needs_autoescape=True)
@stringfilter
urlize()
django.template.defaultfilters.urlize (value, autoescape = True)
Convert URLs in plain text into clickable links.
Definition at line 382 of file defaultfilters.py.
def urlize(value, autoescape=True):
    """Convert URLs in plain text into clickable links."""
    return mark_safe(_urlize(value, nofollow=True, autoescape=autoescape))
@register.filter(is_safe=True, needs_autoescape=True)
@stringfilter
urlizetrunc()
django.template.defaultfilters.urlizetrunc (value, limit, autoescape = True)
Convert URLs into clickable links, truncating URLs to the given character
limit, and adding 'rel=nofollow' attribute to discourage spamming.
Argument: Length to truncate URLs to.
Definition at line 389 of file defaultfilters.py.
def urlizetrunc(value, limit, autoescape=True):
    """
    Convert URLs into clickable links, truncating URLs to the given character
    limit, and adding 'rel=nofollow' attribute to discourage spamming.
    Argument: Length to truncate URLs to.
    """
    return mark_safe(
        _urlize(value, trim_url_limit=int(limit), nofollow=True, autoescape=autoescape)
    )
@register.filter(is_safe=False)
@stringfilter
wordcount()
django.template.defaultfilters.wordcount (value)
Return the number of words.
Definition at line 403 of file defaultfilters.py.
def wordcount(value):
    """Return the number of words."""
    return len(value.split())
@register.filter(is_safe=True)
@stringfilter
wordwrap()
django.template.defaultfilters.wordwrap (value, arg)
Wrap words at `arg` line length.
Definition at line 410 of file defaultfilters.py.
def wordwrap(value, arg):
    """Wrap words at `arg` line length."""
    return wrap(value, int(arg))
@register.filter(is_safe=True)
@stringfilter
yesno()
django.template.defaultfilters.yesno (value, arg = None)
Given a string mapping values for true, false, and (optionally) None,
return one of those strings according to the value:
==========  ======================  ==================================
Value       Argument                Outputs
==========  ======================  ==================================
``True``    ``"yeah,no,maybe"``     ``yeah``
``False``   ``"yeah,no,maybe"``     ``no``
``None``    ``"yeah,no,maybe"``     ``maybe``
``None``    ``"yeah,no"``           ``"no"`` (converts None to False
                                    if no mapping for None is given.
==========  ======================  ==================================
Definition at line 856 of file defaultfilters.py.
def yesno(value, arg=None):
    """
    Given a string mapping values for true, false, and (optionally) None,
    return one of those strings according to the value:
    ==========  ======================  ==================================
    Value       Argument                Outputs
    ==========  ======================  ==================================
    ``True``    ``"yeah,no,maybe"``     ``yeah``
    ``False``   ``"yeah,no,maybe"``     ``no``
    ``None``    ``"yeah,no,maybe"``     ``maybe``
    ``None``    ``"yeah,no"``           ``"no"`` (converts None to False
                                        if no mapping for None is given.
    ==========  ======================  ==================================
    """
    if arg is None:
        # Translators: Please do not add spaces around commas.
        arg = gettext("yes,no,maybe")
    bits = arg.split(",")
    if len(bits) < 2:
        return value  # Invalid arg.
    try:
        yes, no, maybe = bits
    except ValueError:
        # Unpack list of wrong size (no "maybe" value provided).
        yes, no, maybe = bits[0], bits[1], bits[1]
    if value is None:
        return maybe
    if value:
        return yes
    return no
Variable Documentation
register
django.template.defaultfilters.register = Library()
Definition at line 30 of file defaultfilters.py.