Read&Watch: django.dispatch.dispatcher Namespace Reference
django.dispatch.dispatcher Namespace Reference
Classes
class Signal
Functions
_make_id (target)
receiver (signal, **kwargs)
Variables
logger = logging.getLogger("django.dispatch")
NONE_ID = _make_id(None)
NO_RECEIVERS = object()
Function Documentation
_make_id()
django.dispatch.dispatcher._make_id (target) protected
Definition at line 13 of file dispatcher.py.
def _make_id(target):
    if hasattr(target, "__func__"):
        return (id(target.__self__), id(target.__func__))
    return id(target)
Referenced by django.dispatch.dispatcher.Signal._live_receivers(), django.dispatch.dispatcher.Signal.connect(), and django.dispatch.dispatcher.Signal.disconnect().
receiver()
django.dispatch.dispatcher.receiver (signal, ** kwargs)
A decorator for connecting receivers to signals. Used by passing in the
signal (or list of signals) and keyword arguments to connect::
    @receiver(post_save, sender=MyModel)
    def signal_receiver(sender, **kwargs):
        ...
    @receiver([post_save, post_delete], sender=MyModel)
    def signals_receiver(sender, **kwargs):
        ...
Definition at line 472 of file dispatcher.py.
def receiver(signal, **kwargs):
    """
    A decorator for connecting receivers to signals. Used by passing in the
    signal (or list of signals) and keyword arguments to connect::
        @receiver(post_save, sender=MyModel)
        def signal_receiver(sender, **kwargs):
            ...
        @receiver([post_save, post_delete], sender=MyModel)
        def signals_receiver(sender, **kwargs):
            ...
    """
    def _decorator(func):
        if isinstance(signal, (list, tuple)):
            for s in signal:
                s.connect(func, **kwargs)
        else:
            signal.connect(func, **kwargs)
        return func
    return _decorator
Referenced by django.dispatch.dispatcher.Signal._live_receivers(), django.dispatch.dispatcher.Signal.asend(), django.dispatch.dispatcher.Signal.asend_robust(), django.dispatch.dispatcher.Signal.send(), and django.dispatch.dispatcher.Signal.send_robust().
Variable Documentation
logger
django.dispatch.dispatcher.logger = logging.getLogger("django.dispatch")
Definition at line 10 of file dispatcher.py.
NO_RECEIVERS
django.dispatch.dispatcher.NO_RECEIVERS = object()
Definition at line 22 of file dispatcher.py.
NONE_ID
django.dispatch.dispatcher.NONE_ID = _make_id(None)
Definition at line 19 of file dispatcher.py.