Read&Watch: astroid.builder Namespace Reference
astroid.builder Namespace Reference
Classes
class AstroidBuilder
Functions
tuple[TextIOWrapper, str, str] open_source_file (str filename)
bool _can_assign_attr (nodes.ClassDef node, str|None attrname)
nodes.Module build_namespace_package_module (str name, Sequence[str] path)
nodes.Module parse (str code, str module_name="", str|None path=None, bool apply_transforms=True)
Iterator[nodes.NodeNG] _extract_expressions (nodes.NodeNG node)
nodes.NodeNG|None _find_statement_by_line (nodes.NodeNG node, int line)
nodes.NodeNG|list[nodes.NodeNG] extract_node (str code, str module_name="")
nodes.NodeNG _extract_single_node (str code, str module_name="")
tuple[ast.Module, ParserModule] _parse_string (str data, bool type_comments=True, str|None modname=None)
Variables
str _TRANSIENT_FUNCTION = "__"
str _STATEMENT_SELECTOR = "#@"
Detailed Description
The AstroidBuilder makes astroid from living object and / or from _ast.
The builder is not thread safe and can't be used to parse different sources
at the same time.
Function Documentation
_can_assign_attr()
bool astroid.builder._can_assign_attr (nodes.ClassDef node, str | None attrname) protected
Definition at line 51 of file builder.py.
def _can_assign_attr(node: nodes.ClassDef, attrname: str | None) -> bool:
    try:
        slots = node.slots()
    except NotImplementedError:
        pass
    else:
        if slots and attrname not in {slot.value for slot in slots}:
            return False
    return node.qname() != "builtins.object"
Referenced by astroid.builder.AstroidBuilder.delayed_assattr().
_extract_expressions()
Iterator[nodes.NodeNG] astroid.builder._extract_expressions (nodes.NodeNG node) protected
Find expressions in a call to _TRANSIENT_FUNCTION and extract them.
The function walks the AST recursively to search for expressions that
are wrapped into a call to _TRANSIENT_FUNCTION. If it finds such an
expression, it completely removes the function call node from the tree,
replacing it by the wrapped expression inside the parent.
:param node: An astroid node.
:type node:  astroid.bases.NodeNG
:yields: The sequence of wrapped expressions on the modified tree
expression can be found.
Definition at line 303 of file builder.py.
def _extract_expressions(node: nodes.NodeNG) -> Iterator[nodes.NodeNG]:
    """Find expressions in a call to _TRANSIENT_FUNCTION and extract them.
    The function walks the AST recursively to search for expressions that
    are wrapped into a call to _TRANSIENT_FUNCTION. If it finds such an
    expression, it completely removes the function call node from the tree,
    replacing it by the wrapped expression inside the parent.
    :param node: An astroid node.
    :type node:  astroid.bases.NodeNG
    :yields: The sequence of wrapped expressions on the modified tree
    expression can be found.
    """
    if (
        isinstance(node, nodes.Call)
        and isinstance(node.func, nodes.Name)
        and node.func.name == _TRANSIENT_FUNCTION
    ):
        real_expr = node.args[0]
        assert node.parent
        real_expr.parent = node.parent
        # Search for node in all _astng_fields (the fields checked when
        # get_children is called) of its parent. Some of those fields may
        # be lists or tuples, in which case the elements need to be checked.
        # When we find it, replace it by real_expr, so that the AST looks
        # like no call to _TRANSIENT_FUNCTION ever took place.
        for name in node.parent._astroid_fields:
            child = getattr(node.parent, name)
            if isinstance(child, list):
                for idx, compound_child in enumerate(child):
                    if compound_child is node:
                        child[idx] = real_expr
            elif child is node:
                setattr(node.parent, name, real_expr)
        yield real_expr
    else:
        for child in node.get_children():
            yield from _extract_expressions(child)
References _extract_expressions().
Referenced by _extract_expressions(), and extract_node().
_extract_single_node()
nodes.NodeNG astroid.builder._extract_single_node (str code, str module_name = "") protected
Call extract_node while making sure that only one value is returned.
Definition at line 464 of file builder.py.
def _extract_single_node(code: str, module_name: str = "") -> nodes.NodeNG:
    """Call extract_node while making sure that only one value is returned."""
    ret = extract_node(code, module_name)
    if isinstance(ret, list):
        return ret[0]
    return ret
References extract_node().
_find_statement_by_line()
nodes.NodeNG | None astroid.builder._find_statement_by_line (nodes.NodeNG node, int line) protected
Extracts the statement on a specific line from an AST.
If the line number of node matches line, it will be returned;
otherwise its children are iterated and the function is called
recursively.
:param node: An astroid node.
:type node: astroid.bases.NodeNG
:param line: The line number of the statement to extract.
:type line: int
:returns: The statement on the line, or None if no statement for the line
  can be found.
:rtype:  astroid.bases.NodeNG or None
Definition at line 343 of file builder.py.
def _find_statement_by_line(node: nodes.NodeNG, line: int) -> nodes.NodeNG | None:
    """Extracts the statement on a specific line from an AST.
    If the line number of node matches line, it will be returned;
    otherwise its children are iterated and the function is called
    recursively.
    :param node: An astroid node.
    :type node: astroid.bases.NodeNG
    :param line: The line number of the statement to extract.
    :type line: int
    :returns: The statement on the line, or None if no statement for the line
      can be found.
    :rtype:  astroid.bases.NodeNG or None
    """
    if isinstance(node, (nodes.ClassDef, nodes.FunctionDef, nodes.MatchCase)):
        # This is an inaccuracy in the AST: the nodes that can be
        # decorated do not carry explicit information on which line
        # the actual definition (class/def), but .fromline seems to
        # be close enough.
        node_line = node.fromlineno
    else:
        node_line = node.lineno
    if node_line == line:
        return node
    for child in node.get_children():
        result = _find_statement_by_line(child, line)
        if result:
            return result
    return None
References _find_statement_by_line().
Referenced by _find_statement_by_line(), and extract_node().
_parse_string()
tuple[ast.Module, ParserModule] astroid.builder._parse_string (str data, bool type_comments = True, str | None modname = None) protected
Definition at line 472 of file builder.py.
) -> tuple[ast.Module, ParserModule]:
    parser_module = get_parser_module(type_comments=type_comments)
    try:
        parsed = parser_module.parse(
            data + "\n", type_comments=type_comments, filename=modname
        )
    except SyntaxError as exc:
        # If the type annotations are misplaced for some reason, we do not want
        # to fail the entire parsing of the file, so we need to retry the
        # parsing without type comment support. We use a heuristic for
        # determining if the error is due to type annotations.
        type_annot_related = re.search(r"#\s+type:", exc.text or "")
        if not (type_annot_related and type_comments):
            raise
        parser_module = get_parser_module(type_comments=False)
        parsed = parser_module.parse(data + "\n", type_comments=False)
    return parsed, parser_module
Referenced by astroid.builder.AstroidBuilder._data_build().
build_namespace_package_module()
nodes.Module astroid.builder.build_namespace_package_module (str name, Sequence[str] path)
Definition at line 275 of file builder.py.
def build_namespace_package_module(name: str, path: Sequence[str]) -> nodes.Module:
    module = nodes.Module(name, path=path, package=True)
    module.postinit(body=[], doc_node=None)
    return module
extract_node()
nodes.NodeNG | list[nodes.NodeNG] astroid.builder.extract_node (str code, str module_name = "")
Parses some Python code as a module and extracts a designated AST node.
Statements:
 To extract one or more statement nodes, append #@ to the end of the line
 Examples:
   >>> def x():
   >>>   def y():
   >>>     return 1 #@
   The return statement will be extracted.
   >>> class X(object):
   >>>   def meth(self): #@
   >>>     pass
  The function object 'meth' will be extracted.
Expressions:
 To extract arbitrary expressions, surround them with the fake
 function call __(...). After parsing, the surrounded expression
 will be returned and the whole AST (accessible via the returned
 node's parent attribute) will look like the function call was
 never there in the first place.
 Examples:
   >>> a = __(1)
   The const node will be extracted.
   >>> def x(d=__(foo.bar)): pass
   The node containing the default argument will be extracted.
   >>> def foo(a, b):
   >>>   return 0 < __(len(a)) < b
   The node containing the function call 'len' will be extracted.
If no statements or expressions are selected, the last toplevel
statement will be returned.
If the selected statement is a discard statement, (i.e. an expression
turned into a statement), the wrapped expression is returned instead.
For convenience, singleton lists are unpacked.
:param str code: A piece of Python code that is parsed as
a module. Will be passed through textwrap.dedent first.
:param str module_name: The name of the module.
:returns: The designated node from the parse tree, or a list of nodes.
Definition at line 378 of file builder.py.
def extract_node(code: str, module_name: str = "") -> nodes.NodeNG | list[nodes.NodeNG]:
    """Parses some Python code as a module and extracts a designated AST node.
    Statements:
     To extract one or more statement nodes, append #@ to the end of the line
     Examples:
       >>> def x():
       >>>   def y():
       >>>     return 1 #@
       The return statement will be extracted.
       >>> class X(object):
       >>>   def meth(self): #@
       >>>     pass
      The function object 'meth' will be extracted.
    Expressions:
     To extract arbitrary expressions, surround them with the fake
     function call __(...). After parsing, the surrounded expression
     will be returned and the whole AST (accessible via the returned
     node's parent attribute) will look like the function call was
     never there in the first place.
     Examples:
       >>> a = __(1)
       The const node will be extracted.
       >>> def x(d=__(foo.bar)): pass
       The node containing the default argument will be extracted.
       >>> def foo(a, b):
       >>>   return 0 < __(len(a)) < b
       The node containing the function call 'len' will be extracted.
    If no statements or expressions are selected, the last toplevel
    statement will be returned.
    If the selected statement is a discard statement, (i.e. an expression
    turned into a statement), the wrapped expression is returned instead.
    For convenience, singleton lists are unpacked.
    :param str code: A piece of Python code that is parsed as
    a module. Will be passed through textwrap.dedent first.
    :param str module_name: The name of the module.
    :returns: The designated node from the parse tree, or a list of nodes.
    """
    def _extract(node: nodes.NodeNG | None) -> nodes.NodeNG | None:
        if isinstance(node, nodes.Expr):
            return node.value
        return node
    requested_lines: list[int] = []
    for idx, line in enumerate(code.splitlines()):
        if line.strip().endswith(_STATEMENT_SELECTOR):
            requested_lines.append(idx + 1)
    tree = parse(code, module_name=module_name)
    if not tree.body:
        raise ValueError("Empty tree, cannot extract from it")
    extracted: list[nodes.NodeNG | None] = []
    if requested_lines:
        extracted = [_find_statement_by_line(tree, line) for line in requested_lines]
    # Modifies the tree.
    extracted.extend(_extract_expressions(tree))
    if not extracted:
        extracted.append(tree.body[-1])
    extracted = [_extract(node) for node in extracted]
    extracted_without_none = [node for node in extracted if node is not None]
    if len(extracted_without_none) == 1:
        return extracted_without_none[0]
    return extracted_without_none
References _extract_expressions(), _find_statement_by_line(), and parse().
Referenced by _extract_single_node().
open_source_file()
tuple[TextIOWrapper, str, str] astroid.builder.open_source_file (str filename)
Definition at line 42 of file builder.py.
def open_source_file(filename: str) -> tuple[TextIOWrapper, str, str]:
    # pylint: disable=consider-using-with
    with open(filename, "rb") as byte_stream:
        encoding = detect_encoding(byte_stream.readline)[0]
    stream = open(filename, newline=None, encoding=encoding)
    data = stream.read()
    return stream, encoding, data
Referenced by astroid.builder.AstroidBuilder.file_build().
parse()
nodes.Module astroid.builder.parse (str code, str module_name = "", str | None path = None, bool apply_transforms = True)
Parses a source string in order to obtain an astroid AST from it.
:param str code: The code for the module.
:param str module_name: The name for the module, if any
:param str path: The path for the module
:param bool apply_transforms:
    Apply the transforms for the give code. Use it if you
    don't want the default transforms to be applied.
Definition at line 281 of file builder.py.
) -> nodes.Module:
    """Parses a source string in order to obtain an astroid AST from it.
    :param str code: The code for the module.
    :param str module_name: The name for the module, if any
    :param str path: The path for the module
    :param bool apply_transforms:
        Apply the transforms for the give code. Use it if you
        don't want the default transforms to be applied.
    """
    code = textwrap.dedent(code)
    builder = AstroidBuilder(
        manager=AstroidManager(), apply_transforms=apply_transforms
    )
    return builder.string_build(code, modname=module_name, path=path)
Referenced by extract_node().
Variable Documentation
_STATEMENT_SELECTOR
str astroid.builder._STATEMENT_SELECTOR = "#@" protected
Definition at line 36 of file builder.py.
_TRANSIENT_FUNCTION
str astroid.builder._TRANSIENT_FUNCTION = "__" protected
Definition at line 32 of file builder.py.