Read&Watch: pylint.config.argument Namespace Reference
pylint.config.argument Namespace Reference
Classes
class _Argument
class _BaseStoreArgument
class _CallableArgument
class _DeprecationArgument
class _ExtendArgument
class _StoreArgument
class _StoreNewNamesArgument
class _StoreOldNamesArgument
class _StoreTrueArgument
Functions
Sequence[str] _confidence_transformer (str value)
Sequence[str] _csv_transformer (str value)
bool _yn_transformer (str value)
str _non_empty_string_transformer (str value)
str _path_transformer (str value)
Sequence[str] _glob_paths_csv_transformer (str value)
tuple[int,...] _py_version_transformer (str value)
Pattern[str] _regex_transformer (str value)
Sequence[Pattern[str]] _regexp_csv_transfomer (str value)
Sequence[Pattern[str]] _regexp_paths_csv_transfomer (str value)
Variables
_ArgumentTypes
dict YES_VALUES = {"y", "yes", "true"}
dict NO_VALUES = {"n", "no", "false"}
dict _TYPE_TRANSFORMERS
Detailed Description
Definition of an Argument class and transformers for various argument types.
An Argument instance represents a pylint option to be handled by an argparse.ArgumentParser
Function Documentation
_confidence_transformer()
Sequence[str] pylint.config.argument._confidence_transformer (str value) protected
Transforms a comma separated string of confidence values.
Definition at line 39 of file argument.py.
def _confidence_transformer(value: str) -> Sequence[str]:
    """Transforms a comma separated string of confidence values."""
    if not value:
        return interfaces.CONFIDENCE_LEVEL_NAMES
    values = pylint_utils._check_csv(value)
    for confidence in values:
        if confidence not in interfaces.CONFIDENCE_LEVEL_NAMES:
            raise argparse.ArgumentTypeError(
                f"{value} should be in {*interfaces.CONFIDENCE_LEVEL_NAMES,}"
            )
    return values
_csv_transformer()
Sequence[str] pylint.config.argument._csv_transformer (str value) protected
Transforms a comma separated string.
Definition at line 52 of file argument.py.
def _csv_transformer(value: str) -> Sequence[str]:
    """Transforms a comma separated string."""
    return pylint_utils._check_csv(value)
Referenced by _glob_paths_csv_transformer(), and _regexp_paths_csv_transfomer().
_glob_paths_csv_transformer()
Sequence[str] pylint.config.argument._glob_paths_csv_transformer (str value) protected
Transforms a comma separated list of paths while expanding user and
variables and glob patterns.
Definition at line 85 of file argument.py.
def _glob_paths_csv_transformer(value: str) -> Sequence[str]:
    """Transforms a comma separated list of paths while expanding user and
    variables and glob patterns.
    """
    paths: list[str] = []
    for path in _csv_transformer(value):
        paths.extend(glob(_path_transformer(path), recursive=True))
    return paths
References _csv_transformer(), and _path_transformer().
_non_empty_string_transformer()
str pylint.config.argument._non_empty_string_transformer (str value) protected
Check that a string is not empty and remove quotes.
Definition at line 73 of file argument.py.
def _non_empty_string_transformer(value: str) -> str:
    """Check that a string is not empty and remove quotes."""
    if not value:
        raise argparse.ArgumentTypeError("Option cannot be an empty string.")
    return pylint_utils._unquote(value)
_path_transformer()
str pylint.config.argument._path_transformer (str value) protected
Expand user and variables in a path.
Definition at line 80 of file argument.py.
def _path_transformer(value: str) -> str:
    """Expand user and variables in a path."""
    return os.path.expandvars(os.path.expanduser(value))
Referenced by _glob_paths_csv_transformer().
_py_version_transformer()
tuple[int, ...] pylint.config.argument._py_version_transformer (str value) protected
Transforms a version string into a version tuple.
Definition at line 95 of file argument.py.
def _py_version_transformer(value: str) -> tuple[int, ...]:
    """Transforms a version string into a version tuple."""
    try:
        version = tuple(int(val) for val in value.replace(",", ".").split("."))
    except ValueError:
        raise argparse.ArgumentTypeError(
            f"{value} has an invalid format, should be a version string. E.g., '3.8'"
        ) from None
    return version
_regex_transformer()
Pattern[str] pylint.config.argument._regex_transformer (str value) protected
Prevents 're.error' from propagating and crash pylint.
Definition at line 106 of file argument.py.
def _regex_transformer(value: str) -> Pattern[str]:
    """Prevents 're.error' from propagating and crash pylint."""
    try:
        return re.compile(value)
    except re.error as e:
        msg = f"Error in provided regular expression: {value} beginning at index {e.pos}: {e.msg}"
        raise argparse.ArgumentTypeError(msg) from e
Referenced by _regexp_csv_transfomer(), and _regexp_paths_csv_transfomer().
_regexp_csv_transfomer()
Sequence[Pattern[str]] pylint.config.argument._regexp_csv_transfomer (str value) protected
Transforms a comma separated list of regular expressions.
Definition at line 115 of file argument.py.
def _regexp_csv_transfomer(value: str) -> Sequence[Pattern[str]]:
    """Transforms a comma separated list of regular expressions."""
    patterns: list[Pattern[str]] = []
    for pattern in pylint_utils._check_regexp_csv(value):
        patterns.append(_regex_transformer(pattern))
    return patterns
References _regex_transformer().
_regexp_paths_csv_transfomer()
Sequence[Pattern[str]] pylint.config.argument._regexp_paths_csv_transfomer (str value) protected
Transforms a comma separated list of regular expressions paths.
Definition at line 123 of file argument.py.
def _regexp_paths_csv_transfomer(value: str) -> Sequence[Pattern[str]]:
    """Transforms a comma separated list of regular expressions paths."""
    patterns: list[Pattern[str]] = []
    for pattern in _csv_transformer(value):
        patterns.append(
            _regex_transformer(
                str(pathlib.PureWindowsPath(pattern)).replace("\\", "\\\\")
                + "|"
                + pathlib.PureWindowsPath(pattern).as_posix()
            )
        )
    return patterns
References _csv_transformer(), and _regex_transformer().
_yn_transformer()
bool pylint.config.argument._yn_transformer (str value) protected
Transforms a yes/no or stringified bool into a bool.
Definition at line 61 of file argument.py.
def _yn_transformer(value: str) -> bool:
    """Transforms a yes/no or stringified bool into a bool."""
    value = value.lower()
    if value in YES_VALUES:
        return True
    if value in NO_VALUES:
        return False
    raise argparse.ArgumentTypeError(
        None, f"Invalid yn value '{value}', should be in {*YES_VALUES, *NO_VALUES}"
    )
Variable Documentation
_ArgumentTypes
pylint.config.argument._ArgumentTypes protected
Initial value:
=  Union[
    str,
    int,
    float,
    bool,
    Pattern[str],
    Sequence[str],
    Sequence[Pattern[str]],
    tuple[int, ...],
]
Definition at line 26 of file argument.py.
_TYPE_TRANSFORMERS
dict pylint.config.argument._TYPE_TRANSFORMERS protected
Initial value:
=  {
    "choice": str,
    "csv": _csv_transformer,
    "float": float,
    "int": int,
    "confidence": _confidence_transformer,
    "non_empty_string": _non_empty_string_transformer,
    "path": _path_transformer,
    "glob_paths_csv": _glob_paths_csv_transformer,
    "py_version": _py_version_transformer,
    "regexp": _regex_transformer,
    "regexp_csv": _regexp_csv_transfomer,
    "regexp_paths_csv": _regexp_paths_csv_transfomer,
    "string": pylint_utils._unquote,
    "yn": _yn_transformer,
}
Definition at line 137 of file argument.py.
NO_VALUES
dict pylint.config.argument.NO_VALUES = {"n", "no", "false"}
Definition at line 58 of file argument.py.
YES_VALUES
dict pylint.config.argument.YES_VALUES = {"y", "yes", "true"}
Definition at line 57 of file argument.py.