Read&Watch: pylint.utils.docs Namespace Reference
pylint.utils.docs Namespace Reference
Functions
dict[str, dict[str, Any]] _get_checkers_infos (PyLinter linter)
str _get_global_options_documentation (PyLinter linter)
str _get_checkers_documentation (PyLinter linter, bool show_options=True)
None print_full_documentation (PyLinter linter, TextIO stream=sys.stdout, bool show_options=True)
Detailed Description
Various helper functions to create the docs of a linter object.
Function Documentation
_get_checkers_documentation()
str pylint.utils.docs._get_checkers_documentation (PyLinter linter, bool show_options = True) protected
Get documentation for individual checkers.
Definition at line 60 of file docs.py.
def _get_checkers_documentation(linter: PyLinter, show_options: bool = True) -> str:
    """Get documentation for individual checkers."""
    if show_options:
        result = _get_global_options_documentation(linter)
    else:
        result = ""
    result += get_rst_title("Pylint checkers' options and switches", "-")
    result += """\
Pylint checkers can provide three set of features:
* options that control their execution,
* messages that they can raise,
* reports that they can generate.
Below is a list of all checkers and their features.
"""
    by_checker = _get_checkers_infos(linter)
    for checker_name in sorted(by_checker):
        information = by_checker[checker_name]
        checker = information["checker"]
        del information["checker"]
        result += checker.get_full_documentation(
            **information, show_options=show_options
        )
    return result
References _get_checkers_infos(), and _get_global_options_documentation().
Referenced by print_full_documentation().
_get_checkers_infos()
dict[str, dict[str, Any]] pylint.utils.docs._get_checkers_infos (PyLinter linter) protected
Get info from a checker and handle KeyError.
Definition at line 19 of file docs.py.
def _get_checkers_infos(linter: PyLinter) -> dict[str, dict[str, Any]]:
    """Get info from a checker and handle KeyError."""
    by_checker: dict[str, dict[str, Any]] = {}
    for checker in linter.get_checkers():
        name = checker.name
        if name != MAIN_CHECKER_NAME:
            try:
                by_checker[name]["checker"] = checker
                by_checker[name]["options"] += checker._options_and_values()
                by_checker[name]["msgs"].update(checker.msgs)
                by_checker[name]["reports"] += checker.reports
            except KeyError:
                by_checker[name] = {
                    "checker": checker,
                    "options": list(checker._options_and_values()),
                    "msgs": dict(checker.msgs),
                    "reports": list(checker.reports),
                }
    return by_checker
Referenced by _get_checkers_documentation().
_get_global_options_documentation()
str pylint.utils.docs._get_global_options_documentation (PyLinter linter) protected
Get documentation for the main checker.
Definition at line 40 of file docs.py.
def _get_global_options_documentation(linter: PyLinter) -> str:
    """Get documentation for the main checker."""
    result = get_rst_title("Pylint global options and switches", "-")
    result += """
Pylint provides global options and switches.
"""
    for checker in linter.get_checkers():
        if checker.name == MAIN_CHECKER_NAME and checker.options:
            for section, options in checker._options_by_section():
                if section is None:
                    title = "General options"
                else:
                    title = f"{section.capitalize()} options"
                result += get_rst_title(title, "~")
                assert isinstance(options, list)
                result += f"{get_rst_section(None, options)}\n"
    return result
Referenced by _get_checkers_documentation().
print_full_documentation()
None pylint.utils.docs.print_full_documentation (PyLinter linter, TextIO stream = sys.stdout, bool show_options = True)
Output a full documentation in ReST format.
Definition at line 90 of file docs.py.
) -> None:
    """Output a full documentation in ReST format."""
    print(
        _get_checkers_documentation(linter, show_options=show_options)[:-3], file=stream
    )
References _get_checkers_documentation().