Read&Watch: PIL.IptcImagePlugin Namespace Reference
PIL.IptcImagePlugin Namespace Reference
Classes
class IptcImageFile
Image plugin for IPTC/NAA datastreams.
Functions
bytes __getattr__ (str name)
int _i (bytes c)
int _i8 (int|bytes c)
int i (bytes c)
None dump (Sequence[int|bytes] c)
dict[tuple[int, int], bytes|list[bytes]]|None getiptcinfo (ImageFile.ImageFile im)
Variables
dict COMPRESSION = {1: "raw", 5: "jpeg"}
Function Documentation
__getattr__()
bytes PIL.IptcImagePlugin.__getattr__ (str name)
Definition at line 31 of file IptcImagePlugin.py.
def __getattr__(name: str) -> bytes:
    if name == "PAD":
        deprecate("IptcImagePlugin.PAD", 12)
        return b"\0\0\0\0"
    msg = f"module '{__name__}' has no attribute '{name}'"
    raise AttributeError(msg)
#
# Helpers
_i()
int PIL.IptcImagePlugin._i (bytes c) protected
Definition at line 43 of file IptcImagePlugin.py.
def _i(c: bytes) -> int:
    return i32((b"\0\0\0\0" + c)[-4:])
Referenced by PIL.IptcImagePlugin.IptcImageFile.field(), PIL.IptcImagePlugin.IptcImageFile.getint(), and i().
_i8()
int PIL.IptcImagePlugin._i8 (int | bytes c) protected
Definition at line 47 of file IptcImagePlugin.py.
def _i8(c: int | bytes) -> int:
    return c if isinstance(c, int) else c[0]
dump()
None PIL.IptcImagePlugin.dump (Sequence[int | bytes] c)
.. deprecated:: 10.2.0
Definition at line 57 of file IptcImagePlugin.py.
def dump(c: Sequence[int | bytes]) -> None:
    """.. deprecated:: 10.2.0"""
    deprecate("IptcImagePlugin.dump", 12)
    for i in c:
        print(f"{_i8(i):02x}", end=" ")
    print()
getiptcinfo()
dict[tuple[int, int], bytes | list[bytes]] | None PIL.IptcImagePlugin.getiptcinfo (ImageFile.ImageFile im)
Get IPTC information from TIFF, JPEG, or IPTC file.
:param im: An image containing IPTC data.
:returns: A dictionary containing IPTC information, or None if
    no IPTC information block was found.
Definition at line 190 of file IptcImagePlugin.py.
) -> dict[tuple[int, int], bytes | list[bytes]] | None:
    """
    Get IPTC information from TIFF, JPEG, or IPTC file.
    :param im: An image containing IPTC data.
    :returns: A dictionary containing IPTC information, or None if
        no IPTC information block was found.
    """
    from . import JpegImagePlugin, TiffImagePlugin
    data = None
    info: dict[tuple[int, int], bytes | list[bytes]] = {}
    if isinstance(im, IptcImageFile):
        # return info dictionary right away
        for k, v in im.info.items():
            if isinstance(k, tuple):
                info[k] = v
        return info
    elif isinstance(im, JpegImagePlugin.JpegImageFile):
        # extract the IPTC/NAA resource
        photoshop = im.info.get("photoshop")
        if photoshop:
            data = photoshop.get(0x0404)
    elif isinstance(im, TiffImagePlugin.TiffImageFile):
        # get raw data from the IPTC/NAA tag (PhotoShop tags the data
        # as 4-byte integers, so we cannot use the get method...)
        try:
            data = im.tag_v2[TiffImagePlugin.IPTC_NAA_CHUNK]
        except KeyError:
            pass
    if data is None:
        return None  # no properties
    # create an IptcImagePlugin object without initializing it
    class FakeImage:
        pass
    fake_im = FakeImage()
    fake_im.__class__ = IptcImageFile  # type: ignore[assignment]
    iptc_im = cast(IptcImageFile, fake_im)
    # parse the IPTC information chunk
    iptc_im.info = {}
    iptc_im.fp = BytesIO(data)
    try:
        iptc_im._open()
    except (IndexError, KeyError):
        pass  # expected failure
    for k, v in iptc_im.info.items():
        if isinstance(k, tuple):
            info[k] = v
    return info
i()
int PIL.IptcImagePlugin.i (bytes c)
.. deprecated:: 10.2.0
Definition at line 51 of file IptcImagePlugin.py.
def i(c: bytes) -> int:
    """.. deprecated:: 10.2.0"""
    deprecate("IptcImagePlugin.i", 12)
    return _i(c)
References _i().
Variable Documentation
COMPRESSION
dict PIL.IptcImagePlugin.COMPRESSION = {1: "raw", 5: "jpeg"}
Definition at line 28 of file IptcImagePlugin.py.