Read&Watch: django.db.migrations.state Namespace Reference
django.db.migrations.state Namespace Reference
Classes
class AppConfigStub
class ModelState
class ProjectState
class StateApps
Functions
_get_app_label_and_model_name (model, app_label="")
_get_related_models (m)
get_related_models_tuples (model)
get_related_models_recursive (model)
Function Documentation
_get_app_label_and_model_name()
django.db.migrations.state._get_app_label_and_model_name (model, app_label = "") protected
Definition at line 25 of file state.py.
def _get_app_label_and_model_name(model, app_label=""):
    if isinstance(model, str):
        split = model.split(".", 1)
        return tuple(split) if len(split) == 2 else (app_label, split[0])
    else:
        return model._meta.app_label, model._meta.model_name
Referenced by django.db.migrations.state.ProjectState._find_reload_model().
_get_related_models()
django.db.migrations.state._get_related_models (m) protected
Return all models that have a direct relationship to the given model.
Definition at line 33 of file state.py.
def _get_related_models(m):
    """Return all models that have a direct relationship to the given model."""
    related_models = [
        subclass
        for subclass in m.__subclasses__()
        if issubclass(subclass, models.Model)
    ]
    related_fields_models = set()
    for f in m._meta.get_fields(include_parents=True, include_hidden=True):
        if (
            f.is_relation
            and f.related_model is not None
            and not isinstance(f.related_model, str)
        ):
            related_fields_models.add(f.model)
            related_models.append(f.related_model)
    # Reverse accessors of foreign keys to proxy models are attached to their
    # concrete proxied model.
    opts = m._meta
    if opts.proxy and m in related_fields_models:
        related_models.append(opts.concrete_model)
    return related_models
Referenced by get_related_models_recursive(), and get_related_models_tuples().
get_related_models_recursive()
django.db.migrations.state.get_related_models_recursive (model)
Return all models that have a direct or indirect relationship
to the given model.
Relationships are either defined by explicit relational fields, like
ForeignKey, ManyToManyField or OneToOneField, or by inheriting from another
model (a superclass is related to its subclasses, but not vice versa). Note,
however, that a model inheriting from a concrete model is also related to
its superclass through the implicit *_ptr OneToOneField on the subclass.
Definition at line 68 of file state.py.
def get_related_models_recursive(model):
    """
    Return all models that have a direct or indirect relationship
    to the given model.
    Relationships are either defined by explicit relational fields, like
    ForeignKey, ManyToManyField or OneToOneField, or by inheriting from another
    model (a superclass is related to its subclasses, but not vice versa). Note,
    however, that a model inheriting from a concrete model is also related to
    its superclass through the implicit *_ptr OneToOneField on the subclass.
    """
    seen = set()
    queue = _get_related_models(model)
    for rel_mod in queue:
        rel_app_label, rel_model_name = (
            rel_mod._meta.app_label,
            rel_mod._meta.model_name,
        )
        if (rel_app_label, rel_model_name) in seen:
            continue
        seen.add((rel_app_label, rel_model_name))
        queue.extend(_get_related_models(rel_mod))
    return seen - {(model._meta.app_label, model._meta.model_name)}
References _get_related_models().
Referenced by django.db.migrations.state.ProjectState._find_reload_model().
get_related_models_tuples()
django.db.migrations.state.get_related_models_tuples (model)
Return a list of typical (app_label, model_name) tuples for all related
models for the given model.
Definition at line 57 of file state.py.
def get_related_models_tuples(model):
    """
    Return a list of typical (app_label, model_name) tuples for all related
    models for the given model.
    """
    return {
        (rel_mod._meta.app_label, rel_mod._meta.model_name)
        for rel_mod in _get_related_models(model)
    }
References _get_related_models().
Referenced by django.db.migrations.state.ProjectState._find_reload_model().