Read&Watch: django.contrib.gis.db.models.fields Namespace Reference
django.contrib.gis.db.models.fields Namespace Reference
Classes
class BaseSpatialField
class ExtentField
class GeometryCollectionField
class GeometryField
class LineStringField
class MultiLineStringField
class MultiPointField
class MultiPolygonField
class PointField
class PolygonField
class RasterField
Functions
get_srid_info (srid, connection)
Variables
_srid_cache = defaultdict(dict)
SRIDCacheEntry
Function Documentation
get_srid_info()
django.contrib.gis.db.models.fields.get_srid_info (srid, connection)
Return the units, unit name, and spheroid WKT associated with the
given SRID from the `spatial_ref_sys` (or equivalent) spatial database
table for the given database connection.  These results are cached.
Definition at line 32 of file fields.py.
def get_srid_info(srid, connection):
    """
    Return the units, unit name, and spheroid WKT associated with the
    given SRID from the `spatial_ref_sys` (or equivalent) spatial database
    table for the given database connection.  These results are cached.
    """
    from django.contrib.gis.gdal import SpatialReference
    global _srid_cache
    try:
        # The SpatialRefSys model for the spatial backend.
        SpatialRefSys = connection.ops.spatial_ref_sys()
    except NotImplementedError:
        SpatialRefSys = None
    alias, get_srs = (
        (
            connection.alias,
            lambda srid: SpatialRefSys.objects.using(connection.alias)
            .get(srid=srid)
            .srs,
        )
        if SpatialRefSys
        else (None, SpatialReference)
    )
    if srid not in _srid_cache[alias]:
        srs = get_srs(srid)
        units, units_name = srs.units
        _srid_cache[alias][srid] = SRIDCacheEntry(
            units=units,
            units_name=units_name,
            spheroid='SPHEROID["%s",%s,%s]'
            % (srs["spheroid"], srs.semi_major, srs.inverse_flattening),
            geodetic=srs.geographic,
        )
    return _srid_cache[alias][srid]
References SRIDCacheEntry.
Referenced by django.contrib.gis.db.models.fields.BaseSpatialField.geodetic(), django.contrib.gis.db.models.fields.BaseSpatialField.spheroid(), django.contrib.gis.db.models.fields.BaseSpatialField.units(), and django.contrib.gis.db.models.fields.BaseSpatialField.units_name().
Variable Documentation
_srid_cache
django.contrib.gis.db.models.fields._srid_cache = defaultdict(dict) protected
Definition at line 24 of file fields.py.
SRIDCacheEntry
django.contrib.gis.db.models.fields.SRIDCacheEntry
Initial value:
=  namedtuple(
    "SRIDCacheEntry", ["units", "units_name", "spheroid", "geodetic"]
)
Definition at line 27 of file fields.py.
Referenced by get_srid_info().