Read&Watch: django.core.handlers.wsgi Namespace Reference
django.core.handlers.wsgi Namespace Reference
Classes
class LimitedStream
class WSGIHandler
class WSGIRequest
Functions
get_path_info (environ)
get_script_name (environ)
get_bytes_from_wsgi (environ, key, default)
get_str_from_wsgi (environ, key, default)
Variables
_slashes_re = _lazy_re_compile(rb"/+")
Function Documentation
get_bytes_from_wsgi()
django.core.handlers.wsgi.get_bytes_from_wsgi (environ, key, default)
Get a value from the WSGI environ dictionary as bytes.
key and default should be strings.
Definition at line 187 of file wsgi.py.
def get_bytes_from_wsgi(environ, key, default):
    """
    Get a value from the WSGI environ dictionary as bytes.
    key and default should be strings.
    """
    value = environ.get(key, default)
    # Non-ASCII values in the WSGI environ are arbitrarily decoded with
    # ISO-8859-1. This is wrong for Django websites where UTF-8 is the default.
    # Re-encode to recover the original bytestring.
    return value.encode("iso-8859-1")
Referenced by django.core.handlers.wsgi.WSGIRequest.GET(), get_path_info(), get_script_name(), and get_str_from_wsgi().
get_path_info()
django.core.handlers.wsgi.get_path_info (environ)
Return the HTTP request's PATH_INFO as a string.
Definition at line 147 of file wsgi.py.
def get_path_info(environ):
    """Return the HTTP request's PATH_INFO as a string."""
    path_info = get_bytes_from_wsgi(environ, "PATH_INFO", "/")
    return repercent_broken_unicode(path_info).decode()
References get_bytes_from_wsgi().
Referenced by django.core.handlers.wsgi.WSGIRequest.__init__().
get_script_name()
django.core.handlers.wsgi.get_script_name (environ)
Return the equivalent of the HTTP request's SCRIPT_NAME environment
variable. If Apache mod_rewrite is used, return what would have been
the script name prior to any rewriting (so it's the script name as seen
from the client's perspective), unless the FORCE_SCRIPT_NAME setting is
set (to anything).
Definition at line 154 of file wsgi.py.
def get_script_name(environ):
    """
    Return the equivalent of the HTTP request's SCRIPT_NAME environment
    variable. If Apache mod_rewrite is used, return what would have been
    the script name prior to any rewriting (so it's the script name as seen
    from the client's perspective), unless the FORCE_SCRIPT_NAME setting is
    set (to anything).
    """
    if settings.FORCE_SCRIPT_NAME is not None:
        return settings.FORCE_SCRIPT_NAME
    # If Apache's mod_rewrite had a whack at the URL, Apache set either
    # SCRIPT_URL or REDIRECT_URL to the full resource URL before applying any
    # rewrites. Unfortunately not every web server (lighttpd!) passes this
    # information through all the time, so FORCE_SCRIPT_NAME, above, is still
    # needed.
    script_url = get_bytes_from_wsgi(environ, "SCRIPT_URL", "") or get_bytes_from_wsgi(
        environ, "REDIRECT_URL", ""
    )
    if script_url:
        if b"//" in script_url:
            # mod_wsgi squashes multiple successive slashes in PATH_INFO,
            # do the same with script_url before manipulating paths (#17133).
            script_url = _slashes_re.sub(b"/", script_url)
        path_info = get_bytes_from_wsgi(environ, "PATH_INFO", "")
        script_name = script_url.removesuffix(path_info)
    else:
        script_name = get_bytes_from_wsgi(environ, "SCRIPT_NAME", "")
    return script_name.decode()
References get_bytes_from_wsgi().
Referenced by django.core.handlers.wsgi.WSGIHandler.__call__(), and django.core.handlers.wsgi.WSGIRequest.__init__().
get_str_from_wsgi()
django.core.handlers.wsgi.get_str_from_wsgi (environ, key, default)
Get a value from the WSGI environ dictionary as str.
key and default should be str objects.
Definition at line 200 of file wsgi.py.
def get_str_from_wsgi(environ, key, default):
    """
    Get a value from the WSGI environ dictionary as str.
    key and default should be str objects.
    """
    value = get_bytes_from_wsgi(environ, key, default)
    return value.decode(errors="replace")
References get_bytes_from_wsgi().
Referenced by django.core.handlers.wsgi.WSGIRequest.COOKIES().
Variable Documentation
_slashes_re
django.core.handlers.wsgi._slashes_re = _lazy_re_compile(rb"/+") protected
Definition at line 12 of file wsgi.py.