Read&Watch: django.test.utils Namespace Reference
django.test.utils Namespace Reference
Classes
class _TestState
class Approximate
class CaptureQueriesContext
class ContextList
class ignore_warnings
class isolate_apps
class LoggingCaptureMixin
class modify_settings
class NullTimeKeeper
class override_script_prefix
class override_settings
class override_system_checks
class TestContextDecorator
class TimeKeeper
Functions
instrumented_test_render (self, context)
setup_test_environment (debug=None)
teardown_test_environment ()
setup_databases (verbosity, interactive, *, time_keeper=None, keepdb=False, debug_sql=False, parallel=0, aliases=None, serialized_aliases=None, **kwargs)
iter_test_cases (tests)
dependency_ordered (test_databases, dependencies)
get_unique_databases_and_mirrors (aliases=None)
teardown_databases (old_config, verbosity, parallel=0, keepdb=False)
get_runner (settings, test_runner_class=None)
compare_xml (want, got)
extend_sys_path (*paths)
isolate_lru_cache (lru_cache_object)
captured_output (stream_name)
captured_stdout ()
captured_stderr ()
captured_stdin ()
freeze_time (t)
require_jinja2 (test_func)
tag (*tags)
register_lookup (field, *lookups, lookup_name=None)
garbage_collect ()
Variables
jinja2 = None
TZ_SUPPORT = hasattr(time, "tzset")
requires_tz_support
Function Documentation
captured_output()
django.test.utils.captured_output (stream_name)
Return a context manager used by captured_stdout/stdin/stderr
that temporarily replaces the sys stream *stream_name* with a StringIO.
Note: This function and the following ``captured_std*`` are copied
      from CPython's ``test.support`` module.
Definition at line 785 of file utils.py.
def captured_output(stream_name):
    """Return a context manager used by captured_stdout/stdin/stderr
    that temporarily replaces the sys stream *stream_name* with a StringIO.
    Note: This function and the following ``captured_std*`` are copied
          from CPython's ``test.support`` module."""
    orig_stdout = getattr(sys, stream_name)
    setattr(sys, stream_name, StringIO())
    try:
        yield getattr(sys, stream_name)
    finally:
        setattr(sys, stream_name, orig_stdout)
Referenced by captured_stderr(), captured_stdin(), and captured_stdout().
captured_stderr()
django.test.utils.captured_stderr ()
Capture the output of sys.stderr:
with captured_stderr() as stderr:
    print("hello", file=sys.stderr)
self.assertEqual(stderr.getvalue(), "hello\n")
Definition at line 809 of file utils.py.
def captured_stderr():
    """Capture the output of sys.stderr:
    with captured_stderr() as stderr:
        print("hello", file=sys.stderr)
    self.assertEqual(stderr.getvalue(), "hello\n")
    """
    return captured_output("stderr")
References captured_output().
captured_stdin()
django.test.utils.captured_stdin ()
Capture the input to sys.stdin:
with captured_stdin() as stdin:
    stdin.write('hello\n')
    stdin.seek(0)
    # call test code that consumes from sys.stdin
    captured = input()
self.assertEqual(captured, "hello")
Definition at line 819 of file utils.py.
def captured_stdin():
    """Capture the input to sys.stdin:
    with captured_stdin() as stdin:
        stdin.write('hello\n')
        stdin.seek(0)
        # call test code that consumes from sys.stdin
        captured = input()
    self.assertEqual(captured, "hello")
    """
    return captured_output("stdin")
@contextmanager
References captured_output().
captured_stdout()
django.test.utils.captured_stdout ()
Capture the output of sys.stdout:
with captured_stdout() as stdout:
    print("hello")
self.assertEqual(stdout.getvalue(), "hello\n")
Definition at line 799 of file utils.py.
def captured_stdout():
    """Capture the output of sys.stdout:
    with captured_stdout() as stdout:
        print("hello")
    self.assertEqual(stdout.getvalue(), "hello\n")
    """
    return captured_output("stdout")
References captured_output().
compare_xml()
django.test.utils.compare_xml (want, got)
Try to do a 'xml-comparison' of want and got. Plain string comparison
doesn't always work because, for example, attribute ordering should not be
important. Ignore comment nodes, processing instructions, document type
node, and leading and trailing whitespaces.
Based on https://github.com/lxml/lxml/blob/master/src/lxml/doctestcompare.py
Definition at line 624 of file utils.py.
def compare_xml(want, got):
    """
    Try to do a 'xml-comparison' of want and got. Plain string comparison
    doesn't always work because, for example, attribute ordering should not be
    important. Ignore comment nodes, processing instructions, document type
    node, and leading and trailing whitespaces.
    Based on https://github.com/lxml/lxml/blob/master/src/lxml/doctestcompare.py
    """
    _norm_whitespace_re = re.compile(r"[ \t\n][ \t\n]+")
    def norm_whitespace(v):
        return _norm_whitespace_re.sub(" ", v)
    def child_text(element):
        return "".join(
            c.data for c in element.childNodes if c.nodeType == Node.TEXT_NODE
        )
    def children(element):
        return [c for c in element.childNodes if c.nodeType == Node.ELEMENT_NODE]
    def norm_child_text(element):
        return norm_whitespace(child_text(element))
    def attrs_dict(element):
        return dict(element.attributes.items())
    def check_element(want_element, got_element):
        if want_element.tagName != got_element.tagName:
            return False
        if norm_child_text(want_element) != norm_child_text(got_element):
            return False
        if attrs_dict(want_element) != attrs_dict(got_element):
            return False
        want_children = children(want_element)
        got_children = children(got_element)
        if len(want_children) != len(got_children):
            return False
        return all(
            check_element(want, got) for want, got in zip(want_children, got_children)
        )
    def first_node(document):
        for node in document.childNodes:
            if node.nodeType not in (
                Node.COMMENT_NODE,
                Node.DOCUMENT_TYPE_NODE,
                Node.PROCESSING_INSTRUCTION_NODE,
            ):
                return node
    want = want.strip().replace("\\n", "\n")
    got = got.strip().replace("\\n", "\n")
    # If the string is not a complete xml document, we may need to add a
    # root element. This allow us to compare fragments, like "<foo/><bar/>"
    if not want.startswith("<?xml"):
        wrapper = "<root>%s</root>"
        want = wrapper % want
        got = wrapper % got
    # Parse the want and got strings, and compare the parsings.
    want_root = first_node(parseString(want))
    got_root = first_node(parseString(got))
    return check_element(want_root, got_root)
dependency_ordered()
django.test.utils.dependency_ordered (test_databases, dependencies)
Reorder test_databases into an order that honors the dependencies
described in TEST[DEPENDENCIES].
Definition at line 260 of file utils.py.
def dependency_ordered(test_databases, dependencies):
    """
    Reorder test_databases into an order that honors the dependencies
    described in TEST[DEPENDENCIES].
    """
    ordered_test_databases = []
    resolved_databases = set()
    # Maps db signature to dependencies of all its aliases
    dependencies_map = {}
    # Check that no database depends on its own alias
    for sig, (_, aliases) in test_databases:
        all_deps = set()
        for alias in aliases:
            all_deps.update(dependencies.get(alias, []))
        if not all_deps.isdisjoint(aliases):
            raise ImproperlyConfigured(
                "Circular dependency: databases %r depend on each other, "
                "but are aliases." % aliases
            )
        dependencies_map[sig] = all_deps
    while test_databases:
        changed = False
        deferred = []
        # Try to find a DB that has all its dependencies met
        for signature, (db_name, aliases) in test_databases:
            if dependencies_map[signature].issubset(resolved_databases):
                resolved_databases.update(aliases)
                ordered_test_databases.append((signature, (db_name, aliases)))
                changed = True
            else:
                deferred.append((signature, (db_name, aliases)))
        if not changed:
            raise ImproperlyConfigured("Circular dependency in TEST[DEPENDENCIES]")
        test_databases = deferred
    return ordered_test_databases
Referenced by get_unique_databases_and_mirrors().
extend_sys_path()
django.test.utils.extend_sys_path (* paths)
Context manager to temporarily add paths to sys.path.
Definition at line 764 of file utils.py.
def extend_sys_path(*paths):
    """Context manager to temporarily add paths to sys.path."""
    _orig_sys_path = sys.path[:]
    sys.path.extend(paths)
    try:
        yield
    finally:
        sys.path = _orig_sys_path
@contextmanager
freeze_time()
django.test.utils.freeze_time (t)
Context manager to temporarily freeze time.time(). This temporarily
modifies the time function of the time module. Modules which import the
time function directly (e.g. `from time import time`) won't be affected
This isn't meant as a public API, but helps reduce some repetitive code in
Django's test suite.
Definition at line 833 of file utils.py.
def freeze_time(t):
    """
    Context manager to temporarily freeze time.time(). This temporarily
    modifies the time function of the time module. Modules which import the
    time function directly (e.g. `from time import time`) won't be affected
    This isn't meant as a public API, but helps reduce some repetitive code in
    Django's test suite.
    """
    _real_time = time.time
    time.time = lambda: t
    try:
        yield
    finally:
        time.time = _real_time
garbage_collect()
django.test.utils.garbage_collect ()
Definition at line 990 of file utils.py.
def garbage_collect():
    gc.collect()
    if PYPY:
        # Collecting weakreferences can take two collections on PyPy.
        gc.collect()
get_runner()
django.test.utils.get_runner (settings, test_runner_class = None)
Definition at line 372 of file utils.py.
def get_runner(settings, test_runner_class=None):
    test_runner_class = test_runner_class or settings.TEST_RUNNER
    test_path = test_runner_class.split(".")
    # Allow for relative paths
    if len(test_path) > 1:
        test_module_name = ".".join(test_path[:-1])
    else:
        test_module_name = "."
    test_module = __import__(test_module_name, {}, {}, test_path[-1])
    return getattr(test_module, test_path[-1])
get_unique_databases_and_mirrors()
django.test.utils.get_unique_databases_and_mirrors (aliases = None)
Figure out which databases actually need to be created.
Deduplicate entries in DATABASES that correspond the same database or are
configured as test mirrors.
Return two values:
- test_databases: ordered mapping of signatures to (name, list of aliases)
                  where all aliases share the same underlying database.
- mirrored_aliases: mapping of mirror aliases to original aliases.
Definition at line 302 of file utils.py.
def get_unique_databases_and_mirrors(aliases=None):
    """
    Figure out which databases actually need to be created.
    Deduplicate entries in DATABASES that correspond the same database or are
    configured as test mirrors.
    Return two values:
    - test_databases: ordered mapping of signatures to (name, list of aliases)
                      where all aliases share the same underlying database.
    - mirrored_aliases: mapping of mirror aliases to original aliases.
    """
    if aliases is None:
        aliases = connections
    mirrored_aliases = {}
    test_databases = {}
    dependencies = {}
    default_sig = connections[DEFAULT_DB_ALIAS].creation.test_db_signature()
    for alias in connections:
        connection = connections[alias]
        test_settings = connection.settings_dict["TEST"]
        if test_settings["MIRROR"]:
            # If the database is marked as a test mirror, save the alias.
            mirrored_aliases[alias] = test_settings["MIRROR"]
        elif alias in aliases:
            # Store a tuple with DB parameters that uniquely identify it.
            # If we have two aliases with the same values for that tuple,
            # we only need to create the test database once.
            item = test_databases.setdefault(
                connection.creation.test_db_signature(),
                (connection.settings_dict["NAME"], []),
            )
            # The default database must be the first because data migrations
            # use the default alias by default.
            if alias == DEFAULT_DB_ALIAS:
                item[1].insert(0, alias)
            else:
                item[1].append(alias)
            if "DEPENDENCIES" in test_settings:
                dependencies[alias] = test_settings["DEPENDENCIES"]
            else:
                if (
                    alias != DEFAULT_DB_ALIAS
                    and connection.creation.test_db_signature() != default_sig
                ):
                    dependencies[alias] = test_settings.get(
                        "DEPENDENCIES", [DEFAULT_DB_ALIAS]
                    )
    test_databases = dict(dependency_ordered(test_databases.items(), dependencies))
    return test_databases, mirrored_aliases
References dependency_ordered().
Referenced by setup_databases().
instrumented_test_render()
django.test.utils.instrumented_test_render (self, context)
An instrumented Template render method, providing a signal that can be
intercepted by the test Client.
Definition at line 108 of file utils.py.
def instrumented_test_render(self, context):
    """
    An instrumented Template render method, providing a signal that can be
    intercepted by the test Client.
    """
    template_rendered.send(sender=self, template=self, context=context)
    return self.nodelist.render(context)
isolate_lru_cache()
django.test.utils.isolate_lru_cache (lru_cache_object)
Clear the cache of an LRU cache object on entering and exiting.
Definition at line 775 of file utils.py.
def isolate_lru_cache(lru_cache_object):
    """Clear the cache of an LRU cache object on entering and exiting."""
    lru_cache_object.cache_clear()
    try:
        yield
    finally:
        lru_cache_object.cache_clear()
@contextmanager
iter_test_cases()
django.test.utils.iter_test_cases (tests)
Return an iterator over a test suite's unittest.TestCase objects.
The tests argument can also be an iterable of TestCase objects.
Definition at line 239 of file utils.py.
def iter_test_cases(tests):
    """
    Return an iterator over a test suite's unittest.TestCase objects.
    The tests argument can also be an iterable of TestCase objects.
    """
    for test in tests:
        if isinstance(test, str):
            # Prevent an unfriendly RecursionError that can happen with
            # strings.
            raise TypeError(
                f"Test {test!r} must be a test case or test suite not string "
                f"(was found in {tests!r})."
            )
        if isinstance(test, TestCase):
            yield test
        else:
            # Otherwise, assume it is a test suite.
            yield from iter_test_cases(test)
References iter_test_cases().
Referenced by iter_test_cases().
register_lookup()
django.test.utils.register_lookup (field, * lookups, lookup_name = None)
Context manager to temporarily register lookups on a model field using
lookup_name (or the lookup's lookup_name if not provided).
Definition at line 976 of file utils.py.
def register_lookup(field, *lookups, lookup_name=None):
    """
    Context manager to temporarily register lookups on a model field using
    lookup_name (or the lookup's lookup_name if not provided).
    """
    try:
        for lookup in lookups:
            field.register_lookup(lookup, lookup_name)
        yield
    finally:
        for lookup in lookups:
            field._unregister_lookup(lookup, lookup_name)
require_jinja2()
django.test.utils.require_jinja2 (test_func)
Decorator to enable a Jinja2 template engine in addition to the regular
Django template engine for a test or skip it if Jinja2 isn't available.
Definition at line 849 of file utils.py.
def require_jinja2(test_func):
    """
    Decorator to enable a Jinja2 template engine in addition to the regular
    Django template engine for a test or skip it if Jinja2 isn't available.
    """
    test_func = skipIf(jinja2 is None, "this test requires jinja2")(test_func)
    return override_settings(
        TEMPLATES=[
            {
                "BACKEND": "django.template.backends.django.DjangoTemplates",
                "APP_DIRS": True,
            },
            {
                "BACKEND": "django.template.backends.jinja2.Jinja2",
                "APP_DIRS": True,
                "OPTIONS": {"keep_trailing_newline": True},
            },
        ]
    )(test_func)
setup_databases()
django.test.utils.setup_databases (verbosity, interactive, * , time_keeper = None, keepdb = False, debug_sql = False, parallel = 0, aliases = None, serialized_aliases = None, ** kwargs)
Create the test databases.
Definition at line 173 of file utils.py.
):
    """Create the test databases."""
    if time_keeper is None:
        time_keeper = NullTimeKeeper()
    test_databases, mirrored_aliases = get_unique_databases_and_mirrors(aliases)
    old_names = []
    for db_name, aliases in test_databases.values():
        first_alias = None
        for alias in aliases:
            connection = connections[alias]
            old_names.append((connection, db_name, first_alias is None))
            # Actually create the database for the first connection
            if first_alias is None:
                first_alias = alias
                with time_keeper.timed("  Creating '%s'" % alias):
                    serialize_alias = (
                        serialized_aliases is None or alias in serialized_aliases
                    )
                    connection.creation.create_test_db(
                        verbosity=verbosity,
                        autoclobber=not interactive,
                        keepdb=keepdb,
                        serialize=serialize_alias,
                    )
                if parallel > 1:
                    for index in range(parallel):
                        with time_keeper.timed("  Cloning '%s'" % alias):
                            connection.creation.clone_test_db(
                                suffix=str(index + 1),
                                verbosity=verbosity,
                                keepdb=keepdb,
                            )
            # Configure all other connections as mirrors of the first one
            else:
                connections[alias].creation.set_as_test_mirror(
                    connections[first_alias].settings_dict
                )
    # Configure the test mirrors.
    for alias, mirror_alias in mirrored_aliases.items():
        connections[alias].creation.set_as_test_mirror(
            connections[mirror_alias].settings_dict
        )
    if debug_sql:
        for alias in connections:
            connections[alias].force_debug_cursor = True
    return old_names
References get_unique_databases_and_mirrors().
setup_test_environment()
django.test.utils.setup_test_environment (debug = None)
Perform global pre-test setup, such as installing the instrumented template
renderer and setting the email backend to the locmem email backend.
Definition at line 121 of file utils.py.
def setup_test_environment(debug=None):
    """
    Perform global pre-test setup, such as installing the instrumented template
    renderer and setting the email backend to the locmem email backend.
    """
    if hasattr(_TestState, "saved_data"):
        # Executing this function twice would overwrite the saved values.
        raise RuntimeError(
            "setup_test_environment() was already called and can't be called "
            "again without first calling teardown_test_environment()."
        )
    if debug is None:
        debug = settings.DEBUG
    saved_data = SimpleNamespace()
    _TestState.saved_data = saved_data
    saved_data.allowed_hosts = settings.ALLOWED_HOSTS
    # Add the default host of the test client.
    settings.ALLOWED_HOSTS = [*settings.ALLOWED_HOSTS, "testserver"]
    saved_data.debug = settings.DEBUG
    settings.DEBUG = debug
    saved_data.email_backend = settings.EMAIL_BACKEND
    settings.EMAIL_BACKEND = "django.core.mail.backends.locmem.EmailBackend"
    saved_data.template_render = Template._render
    Template._render = instrumented_test_render
    mail.outbox = []
    deactivate()
tag()
django.test.utils.tag (* tags)
Decorator to add tags to a test class or method.
Definition at line 962 of file utils.py.
def tag(*tags):
    """Decorator to add tags to a test class or method."""
    def decorator(obj):
        if hasattr(obj, "tags"):
            obj.tags = obj.tags.union(tags)
        else:
            setattr(obj, "tags", set(tags))
        return obj
    return decorator
@contextmanager
teardown_databases()
django.test.utils.teardown_databases (old_config, verbosity, parallel = 0, keepdb = False)
Destroy all the non-mirror databases.
Definition at line 358 of file utils.py.
def teardown_databases(old_config, verbosity, parallel=0, keepdb=False):
    """Destroy all the non-mirror databases."""
    for connection, old_name, destroy in old_config:
        if destroy:
            if parallel > 1:
                for index in range(parallel):
                    connection.creation.destroy_test_db(
                        suffix=str(index + 1),
                        verbosity=verbosity,
                        keepdb=keepdb,
                    )
            connection.creation.destroy_test_db(old_name, verbosity, keepdb)
teardown_test_environment()
django.test.utils.teardown_test_environment ()
Perform any global post-test teardown, such as restoring the original
template renderer and restoring the email sending functions.
Definition at line 157 of file utils.py.
def teardown_test_environment():
    """
    Perform any global post-test teardown, such as restoring the original
    template renderer and restoring the email sending functions.
    """
    saved_data = _TestState.saved_data
    settings.ALLOWED_HOSTS = saved_data.allowed_hosts
    settings.DEBUG = saved_data.debug
    settings.EMAIL_BACKEND = saved_data.email_backend
    Template._render = saved_data.template_render
    del _TestState.saved_data
    del mail.outbox
Variable Documentation
jinja2
django.test.utils.jinja2 = None
Definition at line 36 of file utils.py.
requires_tz_support
django.test.utils.requires_tz_support
Initial value:
=  skipUnless(
    TZ_SUPPORT,
    "This test relies on the ability to run a program in an arbitrary "
    "time zone, but your operating system isn't able to do that.",
)
Definition at line 756 of file utils.py.
TZ_SUPPORT
django.test.utils.TZ_SUPPORT = hasattr(time, "tzset")
Definition at line 58 of file utils.py.