Read&Watch: pip._internal.operations.prepare Namespace Reference
pip._internal.operations.prepare Namespace Reference
Classes
class File
class RequirementPreparer
Functions
BaseDistribution _get_prepared_distribution (InstallRequirement req, BuildTracker build_tracker, PackageFinder finder, bool build_isolation, bool check_build_deps)
None unpack_vcs_link (Link link, str location, int verbosity)
File get_http_url (Link link, Downloader download, Optional[str] download_dir=None, Optional[Hashes] hashes=None)
File get_file_url (Link link, Optional[str] download_dir=None, Optional[Hashes] hashes=None)
Optional[File] unpack_url (Link link, str location, Downloader download, int verbosity, Optional[str] download_dir=None, Optional[Hashes] hashes=None)
Optional[str] _check_download_dir (Link link, str download_dir, Optional[Hashes] hashes, bool warn_on_hash_mismatch=True)
Variables
logger = getLogger(__name__)
Detailed Description
Prepares a distribution for installation
Function Documentation
_check_download_dir()
Optional[str] pip._internal.operations.prepare._check_download_dir (Link link, str download_dir, Optional[Hashes] hashes, bool warn_on_hash_mismatch = True) protected
Check download_dir for previously downloaded file with correct hash
If a correct file is found return its path else None
Definition at line 185 of file prepare.py.
) -> Optional[str]:
    """Check download_dir for previously downloaded file with correct hash
    If a correct file is found return its path else None
    """
    download_path = os.path.join(download_dir, link.filename)
    if not os.path.exists(download_path):
        return None
    # If already downloaded, does its hash match?
    logger.info("File was already downloaded %s", download_path)
    if hashes:
        try:
            hashes.check_against_path(download_path)
        except HashMismatch:
            if warn_on_hash_mismatch:
                logger.warning(
                    "Previously-downloaded file %s has bad hash. Re-downloading.",
                    download_path,
                )
            os.unlink(download_path)
            return None
    return download_path
Referenced by get_file_url(), get_http_url(), pip._internal.operations.prepare.RequirementPreparer.prepare_linked_requirement(), and pip._internal.operations.prepare.RequirementPreparer.prepare_linked_requirements_more().
_get_prepared_distribution()
BaseDistribution pip._internal.operations.prepare._get_prepared_distribution (InstallRequirement req, BuildTracker build_tracker, PackageFinder finder, bool build_isolation, bool check_build_deps) protected
Prepare a distribution for installation.
Definition at line 60 of file prepare.py.
) -> BaseDistribution:
    """Prepare a distribution for installation."""
    abstract_dist = make_distribution_for_install_requirement(req)
    tracker_id = abstract_dist.build_tracker_id
    if tracker_id is not None:
        with build_tracker.track(req, tracker_id):
            abstract_dist.prepare_distribution_metadata(
                finder, build_isolation, check_build_deps
            )
    return abstract_dist.get_metadata_distribution()
Referenced by pip._internal.operations.prepare.RequirementPreparer._prepare_linked_requirement(), and pip._internal.operations.prepare.RequirementPreparer.prepare_editable_requirement().
get_file_url()
File pip._internal.operations.prepare.get_file_url (Link link, Optional[str] download_dir = None, Optional[Hashes] hashes = None)
Get file and optionally check its hash.
Definition at line 118 of file prepare.py.
) -> File:
    """Get file and optionally check its hash."""
    # If a download dir is specified, is the file already there and valid?
    already_downloaded_path = None
    if download_dir:
        already_downloaded_path = _check_download_dir(link, download_dir, hashes)
    if already_downloaded_path:
        from_path = already_downloaded_path
    else:
        from_path = link.file_path
    # If --require-hashes is off, `hashes` is either empty, the
    # link's embedded hash, or MissingHashes; it is required to
    # match. If --require-hashes is on, we are satisfied by any
    # hash in `hashes` matching: a URL-based or an option-based
    # one; no internet-sourced hash will be in `hashes`.
    if hashes:
        hashes.check_against_path(from_path)
    return File(from_path, None)
References _check_download_dir().
Referenced by unpack_url().
get_http_url()
File pip._internal.operations.prepare.get_http_url (Link link, Downloader download, Optional[str] download_dir = None, Optional[Hashes] hashes = None)
Definition at line 94 of file prepare.py.
) -> File:
    temp_dir = TempDirectory(kind="unpack", globally_managed=True)
    # If a download dir is specified, is the file already downloaded there?
    already_downloaded_path = None
    if download_dir:
        already_downloaded_path = _check_download_dir(link, download_dir, hashes)
    if already_downloaded_path:
        from_path = already_downloaded_path
        content_type = None
    else:
        # let's download to a tmp dir
        from_path, content_type = download(link, temp_dir.path)
        if hashes:
            hashes.check_against_path(from_path)
    return File(from_path, content_type)
References _check_download_dir().
Referenced by pip._internal.operations.prepare.RequirementPreparer._fetch_metadata_using_link_data_attr(), and unpack_url().
unpack_url()
Optional[File] pip._internal.operations.prepare.unpack_url (Link link, str location, Downloader download, int verbosity, Optional[str] download_dir = None, Optional[Hashes] hashes = None)
Unpack link into location, downloading if required.
:param hashes: A Hashes object, one of whose embedded hashes must match,
    or HashMismatch will be raised. If the Hashes is empty, no matches are
    required, and unhashable types of requirements (like VCS ones, which
    would ordinarily raise HashUnsupported) are allowed.
Definition at line 142 of file prepare.py.
) -> Optional[File]:
    """Unpack link into location, downloading if required.
    :param hashes: A Hashes object, one of whose embedded hashes must match,
        or HashMismatch will be raised. If the Hashes is empty, no matches are
        required, and unhashable types of requirements (like VCS ones, which
        would ordinarily raise HashUnsupported) are allowed.
    """
    # non-editable vcs urls
    if link.is_vcs:
        unpack_vcs_link(link, location, verbosity=verbosity)
        return None
    assert not link.is_existing_dir()
    # file urls
    if link.is_file:
        file = get_file_url(link, download_dir, hashes=hashes)
    # http urls
    else:
        file = get_http_url(
            link,
            download,
            download_dir,
            hashes=hashes,
        )
    # unpack the archive to the build dir location. even when only downloading
    # archives, they have to be unpacked to parse dependencies, except wheels
    if not link.is_wheel:
        unpack_file(file.path, location, file.content_type)
    return file
References get_file_url(), get_http_url(), and unpack_vcs_link().
Referenced by pip._internal.operations.prepare.RequirementPreparer._prepare_linked_requirement().
unpack_vcs_link()
None pip._internal.operations.prepare.unpack_vcs_link (Link link, str location, int verbosity)
Definition at line 78 of file prepare.py.
def unpack_vcs_link(link: Link, location: str, verbosity: int) -> None:
    vcs_backend = vcs.get_backend_for_scheme(link.scheme)
    assert vcs_backend is not None
    vcs_backend.unpack(location, url=hide_url(link.url), verbosity=verbosity)
@dataclass
Referenced by unpack_url().
Variable Documentation
logger
pip._internal.operations.prepare.logger = getLogger(__name__)
Definition at line 57 of file prepare.py.