Read&Watch: pip._vendor.platformdirs.android Namespace Reference
pip._vendor.platformdirs.android Namespace Reference
Classes
class Android
Functions
str|None _android_folder ()
str _android_documents_folder ()
str _android_downloads_folder ()
str _android_pictures_folder ()
str _android_videos_folder ()
str _android_music_folder ()
Detailed Description
Android.
Function Documentation
_android_documents_folder()
str pip._vendor.platformdirs.android._android_documents_folder () protected
:return: documents folder for the Android OS
Definition at line 168 of file android.py.
def _android_documents_folder() -> str:
    """:return: documents folder for the Android OS"""
    # Get directories with pyjnius
    try:
        from jnius import autoclass  # noqa: PLC0415
        context = autoclass("android.content.Context")
        environment = autoclass("android.os.Environment")
        documents_dir: str = context.getExternalFilesDir(environment.DIRECTORY_DOCUMENTS).getAbsolutePath()
    except Exception:  # noqa: BLE001
        documents_dir = "/storage/emulated/0/Documents"
    return documents_dir
@lru_cache(maxsize=1)
Referenced by pip._vendor.platformdirs.android.Android.user_documents_dir().
_android_downloads_folder()
str pip._vendor.platformdirs.android._android_downloads_folder () protected
:return: downloads folder for the Android OS
Definition at line 184 of file android.py.
def _android_downloads_folder() -> str:
    """:return: downloads folder for the Android OS"""
    # Get directories with pyjnius
    try:
        from jnius import autoclass  # noqa: PLC0415
        context = autoclass("android.content.Context")
        environment = autoclass("android.os.Environment")
        downloads_dir: str = context.getExternalFilesDir(environment.DIRECTORY_DOWNLOADS).getAbsolutePath()
    except Exception:  # noqa: BLE001
        downloads_dir = "/storage/emulated/0/Downloads"
    return downloads_dir
@lru_cache(maxsize=1)
Referenced by pip._vendor.platformdirs.android.Android.user_downloads_dir().
_android_folder()
str | None pip._vendor.platformdirs.android._android_folder () protected
:return: base folder for the Android OS or None if it cannot be found
Definition at line 120 of file android.py.
def _android_folder() -> str | None:  # noqa: C901, PLR0912
    """:return: base folder for the Android OS or None if it cannot be found"""
    result: str | None = None
    # type checker isn't happy with our "import android", just don't do this when type checking see
    # https://stackoverflow.com/a/61394121
    if not TYPE_CHECKING:
        try:
            # First try to get a path to android app using python4android (if available)...
            from android import mActivity  # noqa: PLC0415
            context = cast("android.content.Context", mActivity.getApplicationContext())  # noqa: F821
            result = context.getFilesDir().getParentFile().getAbsolutePath()
        except Exception:  # noqa: BLE001
            result = None
    if result is None:
        try:
            # ...and fall back to using plain pyjnius, if python4android isn't available or doesn't deliver any useful
            # result...
            from jnius import autoclass  # noqa: PLC0415
            context = autoclass("android.content.Context")
            result = context.getFilesDir().getParentFile().getAbsolutePath()
        except Exception:  # noqa: BLE001
            result = None
    if result is None:
        # and if that fails, too, find an android folder looking at path on the sys.path
        # warning: only works for apps installed under /data, not adopted storage etc.
        pattern = re.compile(r"/data/(data|user/\d+)/(.+)/files")
        for path in sys.path:
            if pattern.match(path):
                result = path.split("/files")[0]
                break
        else:
            result = None
    if result is None:
        # one last try: find an android folder looking at path on the sys.path taking adopted storage paths into
        # account
        pattern = re.compile(r"/mnt/expand/[a-fA-F0-9-]{36}/(data|user/\d+)/(.+)/files")
        for path in sys.path:
            if pattern.match(path):
                result = path.split("/files")[0]
                break
        else:
            result = None
    return result
@lru_cache(maxsize=1)
Referenced by pip._vendor.platformdirs.android.Android.user_cache_dir(), pip._vendor.platformdirs.android.Android.user_config_dir(), and pip._vendor.platformdirs.android.Android.user_data_dir().
_android_music_folder()
str pip._vendor.platformdirs.android._android_music_folder () protected
:return: music folder for the Android OS
Definition at line 232 of file android.py.
def _android_music_folder() -> str:
    """:return: music folder for the Android OS"""
    # Get directories with pyjnius
    try:
        from jnius import autoclass  # noqa: PLC0415
        context = autoclass("android.content.Context")
        environment = autoclass("android.os.Environment")
        music_dir: str = context.getExternalFilesDir(environment.DIRECTORY_MUSIC).getAbsolutePath()
    except Exception:  # noqa: BLE001
        music_dir = "/storage/emulated/0/Music"
    return music_dir
Referenced by pip._vendor.platformdirs.android.Android.user_music_dir().
_android_pictures_folder()
str pip._vendor.platformdirs.android._android_pictures_folder () protected
:return: pictures folder for the Android OS
Definition at line 200 of file android.py.
def _android_pictures_folder() -> str:
    """:return: pictures folder for the Android OS"""
    # Get directories with pyjnius
    try:
        from jnius import autoclass  # noqa: PLC0415
        context = autoclass("android.content.Context")
        environment = autoclass("android.os.Environment")
        pictures_dir: str = context.getExternalFilesDir(environment.DIRECTORY_PICTURES).getAbsolutePath()
    except Exception:  # noqa: BLE001
        pictures_dir = "/storage/emulated/0/Pictures"
    return pictures_dir
@lru_cache(maxsize=1)
Referenced by pip._vendor.platformdirs.android.Android.user_pictures_dir().
_android_videos_folder()
str pip._vendor.platformdirs.android._android_videos_folder () protected
:return: videos folder for the Android OS
Definition at line 216 of file android.py.
def _android_videos_folder() -> str:
    """:return: videos folder for the Android OS"""
    # Get directories with pyjnius
    try:
        from jnius import autoclass  # noqa: PLC0415
        context = autoclass("android.content.Context")
        environment = autoclass("android.os.Environment")
        videos_dir: str = context.getExternalFilesDir(environment.DIRECTORY_DCIM).getAbsolutePath()
    except Exception:  # noqa: BLE001
        videos_dir = "/storage/emulated/0/DCIM/Camera"
    return videos_dir
@lru_cache(maxsize=1)
Referenced by pip._vendor.platformdirs.android.Android.user_videos_dir().