Read&Watch: astroid.brain.brain_nose Namespace Reference
astroid.brain.brain_nose Namespace Reference
Functions
_pep8 (name, caps=CAPITALS)
_nose_tools_functions ()
_nose_tools_transform (node)
_nose_tools_trivial_transform ()
None register (AstroidManager manager)
Variables
CAPITALS = re.compile("([A-Z])")
Detailed Description
Hooks for nose library.
Function Documentation
_nose_tools_functions()
astroid.brain.brain_nose._nose_tools_functions () protected
Get an iterator of names and bound methods.
Definition at line 24 of file brain_nose.py.
def _nose_tools_functions():
    """Get an iterator of names and bound methods."""
    module = AstroidBuilder().string_build(
        textwrap.dedent(
            """
    import unittest
    class Test(unittest.TestCase):
        pass
    a = Test()
    """
        )
    )
    try:
        case = next(module["a"].infer())
    except (InferenceError, StopIteration):
        return
    for method in case.methods():
        if method.name.startswith("assert") and "_" not in method.name:
            pep8_name = _pep8(method.name)
            yield pep8_name, BoundMethod(method, case)
        if method.name == "assertEqual":
            # nose also exports assert_equals.
            yield "assert_equals", BoundMethod(method, case)
References _pep8().
Referenced by _nose_tools_transform(), and _nose_tools_trivial_transform().
_nose_tools_transform()
astroid.brain.brain_nose._nose_tools_transform (node) protected
Definition at line 50 of file brain_nose.py.
def _nose_tools_transform(node):
    for method_name, method in _nose_tools_functions():
        node.locals[method_name] = [method]
References _nose_tools_functions().
_nose_tools_trivial_transform()
astroid.brain.brain_nose._nose_tools_trivial_transform () protected
Custom transform for the nose.tools module.
Definition at line 55 of file brain_nose.py.
def _nose_tools_trivial_transform():
    """Custom transform for the nose.tools module."""
    stub = AstroidBuilder().string_build("""__all__ = []""")
    all_entries = ["ok_", "eq_"]
    for pep8_name, method in _nose_tools_functions():
        all_entries.append(pep8_name)
        stub[pep8_name] = method
    # Update the __all__ variable, since nose.tools
    # does this manually with .append.
    all_assign = stub["__all__"].parent
    all_object = List(all_entries)
    all_object.parent = all_assign
    all_assign.value = all_object
    return stub
References _nose_tools_functions().
_pep8()
astroid.brain.brain_nose._pep8 (name, caps = CAPITALS) protected
Definition at line 20 of file brain_nose.py.
def _pep8(name, caps=CAPITALS):
    return caps.sub(lambda m: "_" + m.groups()[0].lower(), name)
Referenced by _nose_tools_functions().
register()
None astroid.brain.brain_nose.register (AstroidManager manager)
Definition at line 73 of file brain_nose.py.
def register(manager: AstroidManager) -> None:
    register_module_extender(
        manager, "nose.tools.trivial", _nose_tools_trivial_transform
    )
    manager.register_transform(
        Module, _nose_tools_transform, lambda n: n.name == "nose.tools"
    )
Variable Documentation
CAPITALS
astroid.brain.brain_nose.CAPITALS = re.compile("([A-Z])")
Definition at line 17 of file brain_nose.py.