Read&Watch: pylint.checkers.classes.class_checker Namespace Reference
pylint.checkers.classes.class_checker Namespace Reference
Classes
class _CallSignature
class _DefaultMissing
class _ParameterSignature
class ClassChecker
class ScopeAccessMap
Functions
_CallSignature _signature_from_call (nodes.Call call)
_ParameterSignature _signature_from_arguments (nodes.Arguments arguments)
bool _definition_equivalent_to_call (_ParameterSignature definition, _CallSignature call)
bool _is_trivial_super_delegation (nodes.FunctionDef function)
list[nodes.AssignName] _positional_parameters (nodes.FunctionDef method)
bool _has_different_parameters_default_value (nodes.Arguments original, nodes.Arguments overridden)
list[str] _has_different_parameters (list[nodes.AssignName] original, list[nodes.AssignName] overridden, Pattern[str] dummy_parameter_regex)
list[str] _has_different_keyword_only_parameters (list[nodes.AssignName] original, list[nodes.AssignName] overridden)
list[str] _different_parameters (nodes.FunctionDef original, nodes.FunctionDef overridden, Pattern[str] dummy_parameter_regex)
bool _is_invalid_base_class (nodes.ClassDef cls)
bool _has_data_descriptor (nodes.ClassDef cls, str attr)
bool _called_in_methods (LocalsDictNodeNG func, nodes.ClassDef klass, Sequence[str] methods)
bool _is_attribute_property (str name, nodes.ClassDef klass)
bool _has_same_layout_slots (list[nodes.Const|None] slots, nodes.Name assigned_value)
defaultdict[str, list[_AccessNodes]] _scope_default ()
dict[nodes.ClassDef, bases.UnboundMethod] _ancestors_to_call (nodes.ClassDef klass_node, str method_name="__init__")
Variables
_AccessNodes = Union[nodes.Attribute, nodes.AssignAttr]
dict INVALID_BASE_CLASSES = {"bool", "range", "slice", "memoryview"}
dict ALLOWED_PROPERTIES = {"bultins.property", "functools.cached_property"}
dict BUILTIN_DECORATORS = {"builtins.property", "builtins.classmethod"}
dict ASTROID_TYPE_COMPARATORS
_DEFAULT_MISSING = _DefaultMissing()
dict MSGS
Detailed Description
Classes checker for Python code.
Function Documentation
_ancestors_to_call()
dict[nodes.ClassDef, bases.UnboundMethod] pylint.checkers.classes.class_checker._ancestors_to_call (nodes.ClassDef klass_node, str method_name = "__init__") protected
Return a dictionary where keys are the list of base classes providing
the queried method, and so that should/may be called from the method node.
Definition at line 2433 of file class_checker.py.
) -> dict[nodes.ClassDef, bases.UnboundMethod]:
    """Return a dictionary where keys are the list of base classes providing
    the queried method, and so that should/may be called from the method node.
    """
    to_call: dict[nodes.ClassDef, bases.UnboundMethod] = {}
    for base_node in klass_node.ancestors(recurs=False):
        try:
            init_node = next(base_node.igetattr(method_name))
            if not isinstance(init_node, astroid.UnboundMethod):
                continue
            if init_node.is_abstract():
                continue
            to_call[base_node] = init_node
        except astroid.InferenceError:
            continue
    return to_call
Referenced by pylint.checkers.classes.class_checker.ClassChecker._check_init().
_called_in_methods()
bool pylint.checkers.classes.class_checker._called_in_methods (LocalsDictNodeNG func, nodes.ClassDef klass, Sequence[str] methods) protected
Check if the func was called in any of the given methods,
belonging to the *klass*.
Returns True if so, False otherwise.
Definition at line 415 of file class_checker.py.
) -> bool:
    """Check if the func was called in any of the given methods,
    belonging to the *klass*.
    Returns True if so, False otherwise.
    """
    if not isinstance(func, nodes.FunctionDef):
        return False
    for method in methods:
        try:
            inferred = klass.getattr(method)
        except astroid.NotFoundError:
            continue
        for infer_method in inferred:
            for call in infer_method.nodes_of_class(nodes.Call):
                try:
                    bound = next(call.func.infer())
                except (astroid.InferenceError, StopIteration):
                    continue
                if not isinstance(bound, astroid.BoundMethod):
                    continue
                func_obj = bound._proxied
                if isinstance(func_obj, astroid.UnboundMethod):
                    func_obj = func_obj._proxied
                if func_obj.name == func.name:
                    return True
    return False
Referenced by pylint.checkers.classes.class_checker.ClassChecker._check_attribute_defined_outside_init().
_definition_equivalent_to_call()
bool pylint.checkers.classes.class_checker._definition_equivalent_to_call (_ParameterSignature definition, _CallSignature call) protected
Check if a definition signature is equivalent to a call.
Definition at line 122 of file class_checker.py.
) -> bool:
    """Check if a definition signature is equivalent to a call."""
    if definition.kwargs:
        if definition.kwargs not in call.starred_kws:
            return False
    elif call.starred_kws:
        return False
    if definition.varargs:
        if definition.varargs not in call.starred_args:
            return False
    elif call.starred_args:
        return False
    if any(kw not in call.kws for kw in definition.kwonlyargs):
        return False
    if definition.args != call.args:
        return False
    # No extra kwargs in call.
    return all(kw in call.args or kw in definition.kwonlyargs for kw in call.kws)
Referenced by pylint.checkers.classes.class_checker.ClassChecker._check_useless_super_delegation().
_different_parameters()
list[str] pylint.checkers.classes.class_checker._different_parameters (nodes.FunctionDef original, nodes.FunctionDef overridden, Pattern[str] dummy_parameter_regex) protected
Determine if the two methods have different parameters.
They are considered to have different parameters if:
   * they have different positional parameters, including different names
   * one of the methods is having variadics, while the other is not
   * they have different keyword only parameters.
Definition at line 315 of file class_checker.py.
) -> list[str]:
    """Determine if the two methods have different parameters.
    They are considered to have different parameters if:
       * they have different positional parameters, including different names
       * one of the methods is having variadics, while the other is not
       * they have different keyword only parameters.
    """
    output_messages = []
    original_parameters = _positional_parameters(original)
    overridden_parameters = _positional_parameters(overridden)
    # Copy kwonlyargs list so that we don't affect later function linting
    original_kwonlyargs = original.args.kwonlyargs
    # Allow positional/keyword variadic in overridden to match against any
    # positional/keyword argument in original.
    # Keep any arguments that are found separately in overridden to satisfy
    # later tests
    if overridden.args.vararg:
        overridden_names = [v.name for v in overridden_parameters]
        original_parameters = [
            v for v in original_parameters if v.name in overridden_names
        ]
    if overridden.args.kwarg:
        overridden_names = [v.name for v in overridden.args.kwonlyargs]
        original_kwonlyargs = [
            v for v in original.args.kwonlyargs if v.name in overridden_names
        ]
    different_positional = _has_different_parameters(
        original_parameters, overridden_parameters, dummy_parameter_regex
    )
    different_kwonly = _has_different_keyword_only_parameters(
        original_kwonlyargs, overridden.args.kwonlyargs
    )
    if different_kwonly and different_positional:
        if "Number " in different_positional[0] and "Number " in different_kwonly[0]:
            output_messages.append("Number of parameters ")
            output_messages += different_positional[1:]
            output_messages += different_kwonly[1:]
        else:
            output_messages += different_positional
            output_messages += different_kwonly
    else:
        if different_positional:
            output_messages += different_positional
        if different_kwonly:
            output_messages += different_kwonly
    # Arguments will only violate LSP if there are variadics in the original
    # that are then removed from the overridden
    kwarg_lost = original.args.kwarg and not overridden.args.kwarg
    vararg_lost = original.args.vararg and not overridden.args.vararg
    if kwarg_lost or vararg_lost:
        output_messages += ["Variadics removed in"]
    if original.name in PYMETHODS:
        # Ignore the difference for special methods. If the parameter
        # numbers are different, then that is going to be caught by
        # unexpected-special-method-signature.
        # If the names are different, it doesn't matter, since they can't
        # be used as keyword arguments anyway.
        output_messages.clear()
    return output_messages
References _has_different_keyword_only_parameters(), _has_different_parameters(), and _positional_parameters().
Referenced by pylint.checkers.classes.class_checker.ClassChecker._check_signature().
_has_data_descriptor()
bool pylint.checkers.classes.class_checker._has_data_descriptor (nodes.ClassDef cls, str attr) protected
Definition at line 396 of file class_checker.py.
def _has_data_descriptor(cls: nodes.ClassDef, attr: str) -> bool:
    attributes = cls.getattr(attr)
    for attribute in attributes:
        try:
            for inferred in attribute.infer():
                if isinstance(inferred, astroid.Instance):
                    try:
                        inferred.getattr("__get__")
                        inferred.getattr("__set__")
                    except astroid.NotFoundError:
                        continue
                    else:
                        return True
        except astroid.InferenceError:
            # Can't infer, avoid emitting a false positive in this case.
            return True
    return False
Referenced by pylint.checkers.classes.class_checker.ClassChecker._check_in_slots().
_has_different_keyword_only_parameters()
list[str] pylint.checkers.classes.class_checker._has_different_keyword_only_parameters (list[nodes.AssignName] original, list[nodes.AssignName] overridden) protected
Determine if the two methods have different keyword only parameters.
Definition at line 292 of file class_checker.py.
) -> list[str]:
    """Determine if the two methods have different keyword only parameters."""
    original_names = [i.name for i in original]
    overridden_names = [i.name for i in overridden]
    if any(name not in overridden_names for name in original_names):
        return ["Number of parameters "]
    for name in overridden_names:
        if name in original_names:
            continue
        try:
            overridden[0].parent.default_value(name)
        except astroid.NoDefault:
            return ["Number of parameters "]
    return []
Referenced by _different_parameters().
_has_different_parameters()
list[str] pylint.checkers.classes.class_checker._has_different_parameters (list[nodes.AssignName] original, list[nodes.AssignName] overridden, Pattern[str] dummy_parameter_regex) protected
Definition at line 261 of file class_checker.py.
) -> list[str]:
    result: list[str] = []
    zipped = zip_longest(original, overridden)
    for original_param, overridden_param in zipped:
        if not overridden_param:
            return ["Number of parameters "]
        if not original_param:
            try:
                overridden_param.parent.default_value(overridden_param.name)
                continue
            except astroid.NoDefault:
                return ["Number of parameters "]
        # check for the arguments' name
        names = [param.name for param in (original_param, overridden_param)]
        if any(dummy_parameter_regex.match(name) for name in names):
            continue
        if original_param.name != overridden_param.name:
            result.append(
                f"Parameter '{original_param.name}' has been renamed "
                f"to '{overridden_param.name}' in"
            )
    return result
Referenced by _different_parameters().
_has_different_parameters_default_value()
bool pylint.checkers.classes.class_checker._has_different_parameters_default_value (nodes.Arguments original, nodes.Arguments overridden) protected
Check if original and overridden methods arguments have different default values.
Return True if one of the overridden arguments has a default
value different from the default value of the original argument
If one of the method doesn't have argument (.args is None)
return False
Definition at line 215 of file class_checker.py.
) -> bool:
    """Check if original and overridden methods arguments have different default values.
    Return True if one of the overridden arguments has a default
    value different from the default value of the original argument
    If one of the method doesn't have argument (.args is None)
    return False
    """
    if original.args is None or overridden.args is None:
        return False
    for param in chain(original.args, original.kwonlyargs):
        try:
            original_default = original.default_value(param.name)
        except astroid.exceptions.NoDefault:
            original_default = _DEFAULT_MISSING
        try:
            overridden_default = overridden.default_value(param.name)
            if original_default is _DEFAULT_MISSING:
                # Only the original has a default.
                return True
        except astroid.exceptions.NoDefault:
            if original_default is _DEFAULT_MISSING:
                # Both have a default, no difference
                continue
            # Only the override has a default.
            return True
        original_type = type(original_default)
        if not isinstance(overridden_default, original_type):
            # Two args with same name but different types
            return True
        is_same_fn: Callable[[Any, Any], bool] | None = ASTROID_TYPE_COMPARATORS.get(
            original_type
        )
        if is_same_fn is None:
            # If the default value comparison is unhandled, assume the value is different
            return True
        if not is_same_fn(original_default, overridden_default):
            # Two args with same type but different values
            return True
    return False
Referenced by pylint.checkers.classes.class_checker.ClassChecker._check_useless_super_delegation().
_has_same_layout_slots()
bool pylint.checkers.classes.class_checker._has_same_layout_slots (list[nodes.Const | None] slots, nodes.Name assigned_value) protected
Definition at line 483 of file class_checker.py.
) -> bool:
    inferred = next(assigned_value.infer())
    if isinstance(inferred, nodes.ClassDef):
        other_slots = inferred.slots()
        if all(
            first_slot and second_slot and first_slot.value == second_slot.value
            for (first_slot, second_slot) in zip_longest(slots, other_slots)
        ):
            return True
    return False
Referenced by pylint.checkers.classes.class_checker.ClassChecker._check_in_slots().
_is_attribute_property()
bool pylint.checkers.classes.class_checker._is_attribute_property (str name, nodes.ClassDef klass) protected
Check if the given attribute *name* is a property in the given *klass*.
It will look for `property` calls or for functions
with the given name, decorated by `property` or `property`
subclasses.
Returns ``True`` if the name is a property in the given klass,
``False`` otherwise.
Definition at line 448 of file class_checker.py.
def _is_attribute_property(name: str, klass: nodes.ClassDef) -> bool:
    """Check if the given attribute *name* is a property in the given *klass*.
    It will look for `property` calls or for functions
    with the given name, decorated by `property` or `property`
    subclasses.
    Returns ``True`` if the name is a property in the given klass,
    ``False`` otherwise.
    """
    try:
        attributes = klass.getattr(name)
    except astroid.NotFoundError:
        return False
    property_name = "builtins.property"
    for attr in attributes:
        if isinstance(attr, util.UninferableBase):
            continue
        try:
            inferred = next(attr.infer())
        except astroid.InferenceError:
            continue
        if isinstance(inferred, nodes.FunctionDef) and decorated_with_property(
            inferred
        ):
            return True
        if inferred.pytype() != property_name:
            continue
        cls = node_frame_class(inferred)
        if cls == klass.declared_metaclass():
            continue
        return True
    return False
Referenced by pylint.checkers.classes.class_checker.ClassChecker._check_in_slots(), and pylint.checkers.classes.class_checker.ClassChecker._check_protected_attribute_access().
_is_invalid_base_class()
bool pylint.checkers.classes.class_checker._is_invalid_base_class (nodes.ClassDef cls) protected
Definition at line 392 of file class_checker.py.
def _is_invalid_base_class(cls: nodes.ClassDef) -> bool:
    return cls.name in INVALID_BASE_CLASSES and is_builtin_object(cls)
Referenced by pylint.checkers.classes.class_checker.ClassChecker._check_proper_bases().
_is_trivial_super_delegation()
bool pylint.checkers.classes.class_checker._is_trivial_super_delegation (nodes.FunctionDef function) protected
Check whether a function definition is a method consisting only of a
call to the same function on the superclass.
Definition at line 145 of file class_checker.py.
def _is_trivial_super_delegation(function: nodes.FunctionDef) -> bool:
    """Check whether a function definition is a method consisting only of a
    call to the same function on the superclass.
    """
    if (
        not function.is_method()
        # Adding decorators to a function changes behavior and
        # constitutes a non-trivial change.
        or function.decorators
    ):
        return False
    body = function.body
    if len(body) != 1:
        # Multiple statements, which means this overridden method
        # could do multiple things we are not aware of.
        return False
    statement = body[0]
    if not isinstance(statement, (nodes.Expr, nodes.Return)):
        # Doing something else than what we are interested in.
        return False
    call = statement.value
    if (
        not isinstance(call, nodes.Call)
        # Not a super() attribute access.
        or not isinstance(call.func, nodes.Attribute)
    ):
        return False
    # Anything other than a super call is non-trivial.
    super_call = safe_infer(call.func.expr)
    if not isinstance(super_call, astroid.objects.Super):
        return False
    # The name should be the same.
    if call.func.attrname != function.name:
        return False
    # Should be a super call with the MRO pointer being the
    # current class and the type being the current instance.
    current_scope = function.parent.scope()
    if (
        super_call.mro_pointer != current_scope
        or not isinstance(super_call.type, astroid.Instance)
        or super_call.type.name != current_scope.name
    ):
        return False
    return True
# Deal with parameters overriding in two methods.
Referenced by pylint.checkers.classes.class_checker.ClassChecker._check_useless_super_delegation().
_positional_parameters()
list[nodes.AssignName] pylint.checkers.classes.class_checker._positional_parameters (nodes.FunctionDef method) protected
Definition at line 201 of file class_checker.py.
def _positional_parameters(method: nodes.FunctionDef) -> list[nodes.AssignName]:
    positional = method.args.args
    if method.is_bound() and method.type in {"classmethod", "method"}:
        positional = positional[1:]
    return positional  # type: ignore[no-any-return]
Referenced by _different_parameters().
_scope_default()
defaultdict[str, list[_AccessNodes]] pylint.checkers.classes.class_checker._scope_default () protected
Definition at line 741 of file class_checker.py.
def _scope_default() -> defaultdict[str, list[_AccessNodes]]:
    # It's impossible to nest defaultdicts so we must use a function
    return defaultdict(list)
_signature_from_arguments()
_ParameterSignature pylint.checkers.classes.class_checker._signature_from_arguments (nodes.Arguments arguments) protected
Definition at line 110 of file class_checker.py.
def _signature_from_arguments(arguments: nodes.Arguments) -> _ParameterSignature:
    kwarg = arguments.kwarg
    vararg = arguments.vararg
    args = [
        arg.name
        for arg in chain(arguments.posonlyargs, arguments.args)
        if arg.name != "self"
    ]
    kwonlyargs = [arg.name for arg in arguments.kwonlyargs]
    return _ParameterSignature(args, kwonlyargs, vararg, kwarg)
Referenced by pylint.checkers.classes.class_checker.ClassChecker._check_useless_super_delegation().
_signature_from_call()
_CallSignature pylint.checkers.classes.class_checker._signature_from_call (nodes.Call call) protected
Definition at line 81 of file class_checker.py.
def _signature_from_call(call: nodes.Call) -> _CallSignature:
    kws = {}
    args = []
    starred_kws = []
    starred_args = []
    for keyword in call.keywords or []:
        arg, value = keyword.arg, keyword.value
        if arg is None and isinstance(value, nodes.Name):
            # Starred node, and we are interested only in names,
            # otherwise some transformation might occur for the parameter.
            starred_kws.append(value.name)
        elif isinstance(value, nodes.Name):
            kws[arg] = value.name
        else:
            kws[arg] = None
    for arg in call.args:
        if isinstance(arg, nodes.Starred) and isinstance(arg.value, nodes.Name):
            # Positional variadic and a name, otherwise some transformation
            # might have occurred.
            starred_args.append(arg.value.name)
        elif isinstance(arg, nodes.Name):
            args.append(arg.name)
        else:
            args.append(None)
    return _CallSignature(args, kws, starred_args, starred_kws)
Referenced by pylint.checkers.classes.class_checker.ClassChecker._check_useless_super_delegation().
Variable Documentation
_AccessNodes
pylint.checkers.classes.class_checker._AccessNodes = Union[nodes.Attribute, nodes.AssignAttr] protected
Definition at line 49 of file class_checker.py.
_DEFAULT_MISSING
pylint.checkers.classes.class_checker._DEFAULT_MISSING = _DefaultMissing() protected
Definition at line 212 of file class_checker.py.
ALLOWED_PROPERTIES
dict pylint.checkers.classes.class_checker.ALLOWED_PROPERTIES = {"bultins.property", "functools.cached_property"}
Definition at line 52 of file class_checker.py.
ASTROID_TYPE_COMPARATORS
dict pylint.checkers.classes.class_checker.ASTROID_TYPE_COMPARATORS
Initial value:
=  {
    nodes.Const: lambda a, b: a.value == b.value,
    nodes.ClassDef: lambda a, b: a.qname == b.qname,
    nodes.Tuple: lambda a, b: a.elts == b.elts,
    nodes.List: lambda a, b: a.elts == b.elts,
    nodes.Dict: lambda a, b: a.items == b.items,
    nodes.Name: lambda a, b: set(a.infer()) == set(b.infer()),
}
Definition at line 54 of file class_checker.py.
BUILTIN_DECORATORS
dict pylint.checkers.classes.class_checker.BUILTIN_DECORATORS = {"builtins.property", "builtins.classmethod"}
Definition at line 53 of file class_checker.py.
INVALID_BASE_CLASSES
dict pylint.checkers.classes.class_checker.INVALID_BASE_CLASSES = {"bool", "range", "slice", "memoryview"}
Definition at line 51 of file class_checker.py.
MSGS
dict pylint.checkers.classes.class_checker.MSGS
Definition at line 497 of file class_checker.py.